### PR TITLE
py-rpy2: Update to version 3.4.5, Remove Python 35, Add Python 39, Bugfix

### PR DESCRIPTION
**Pull request by essandess**
py-rpy2: Update to version 3.4.5, Remove Python 35, Add Python 39, Bugfix

* Update to version 3.4.5
* Remove Python 35
  * Check that `port echo depends:py35-rpy2` is empty
* Add Python 39
* Fixes: https://trac.macports.org/ticket/61327

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.4 20F71 x86_64
Xcode 12.5 12E262

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by essandess** [comment]
These build errors appear to be timeouts. I do not observe errors with a trace-mode install. This is ready to merge to the best of my knowledge.

**Comment by essandess** [comment]
These appear to be simple CI timeouts. I do not observe the CI issue with a trace install. The logs end with:
```
2021-06-13T18:02:36.0149760Z Installing dependency (76 of 99) 'pkgconfig' with variants '' (requesting '') ... [OK]
2021-06-13T18:03:12.8024680Z Installing dependency (77 of 99) 'python36' with variants '' (requesting '') ... [OK]
2021-06-13T18:03:35.7418970Z ##[error]The operation was canceled.
```

@reneeotten, @cjones051073 Would you please sanity check and merge if you agree? This PR fixes a longstanding bug.

**Comment by SurferGreg** [comment]
@essandess is right; this *is* a longstanding bug! @reneeotten, @cjones051073: merge?

**Comment by essandess** [comment]
@stromnov Would you please weigh in on this PR? We'd like to get it merged to address this longstanding issue that breaks the Python interface with R.

**Comment by SurferGreg** [comment]
Thank you everyone (@essandess, @cjones051073, et al.); it's wonderful to have this port back up and running, and much appreciated!!

**Pull request merged**
