### PR TITLE
py*-beancount: upgrade to 2.3.4

### PR DESCRIPTION
**Pull request by sutra**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.2 21D49 x86_64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
@mrdomino is this okay?

**Comment by mrdomino** [comment]
looks ok, except why is chardet a requirement?

**Comment by sutra** [comment]
> why is chardet a requirement?

https://github.com/beancount/beancount/blob/5adf7b9a3be99f631f4b8cd161287f1479dce377/setup.py#L117

**Comment by mrdomino** [comment]
Great, thanks.

**Pull request merged**
