### PR TITLE
OpenBLAS: follow up after switch to cmake

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [x] bugfix

###### Tested on

macOS 10.5.8 9L34 i386
Xcode 3.1.4 9M2809

macOS 10.7.5 11G63 x86_64
Xcode 4.6.3 4H1503

macOS 10.15.7 19H2026 x86_64
Xcode 12.4 12D4e

macOS 12.7.1 21G920 x86_64
Xcode 14.2 14C18

macOS 13.6.1 22G313 arm64
Xcode 15.0.1 15A507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by catap** [comment]
I run tests on 10.5 but it requires a few hours to finish.

**Comment by barracuda156** [comment]
Version from 3a3d9b579e8 successfully built on 14.1.1 with Xcode 15.0.1.

**Comment by cjones051073** [comment]
With this update OpenBLAS indeed builds for me again on macOS14 arm. However, I then get this

```
--->  Scanning binaries for linking errors
Could not open /opt/local/lib/libopenblas-r1.dylib: Error opening or reading file (referenced from /opt/local/libexec/root6/lib/root/libTMVA.6.30.01.so)
```

and indeed that lib is no long present.

Is it expected that this library is no longer built by the port ?

Chris

**Comment by catap** [comment]
@cjones051073 yes, and I made massive revbump to relink for Lay-out which is produced by cmake

**Comment by cjones051073** [comment]
> @cjones051073 yes, and I made massive revbump to relink for Lay-out which is produced by cmake

ok, I was just checking.

root6 is now rebuilding here. If it is indeed fine I'll merge this.

**Comment by catap** [comment]
@cjones051073 thanks, if you merge it.

I've spent last couple of days to hunting down all issues and this seems to be stable enoug. Thus, this PR is also fixing build on everything before 11 and can you (some how) reschedule all affected ports from this commit? https://github.com/macports/macports-ports/commit/7882fbb52b86a91d92dc20d7916155bff6ed9d7f

**Comment by cjones051073** [comment]
> @cjones051073 thanks, if you merge it.
> 
> I've spent last couple of days to hunting down all issues and this seems to be stable enoug. Thus, this PR is also fixing build on everything before 11 and can you (some how) reschedule all affected ports from this commit? [7882fbb](https://github.com/macports/macports-ports/commit/7882fbb52b86a91d92dc20d7916155bff6ed9d7f)

Another rev-bump is not required, the original one is enough. I will though trigger a rebuild in the builedbot for all ports depending on OpenBLAS to catch those that already failed there because of the OpenBLAS regression.

**Comment by cjones051073** [comment]
@catap Your fix here is seemingly not complete. The builds still fail on e.g. 10.6, maybe others. See e.g.

https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/179452/steps/install-port/logs/stdio

**Comment by cjones051073** [comment]
you can monitor all the remaining failures at 

https://ports.macports.org/port/OpenBLAS/builds/

**Comment by catap** [comment]
@cjones051073 I'm thanks.

**Pull request merged**
