### PR TITLE
pass-otp, pass-update: Fix bash completion location

### PR DESCRIPTION
**Pull request by judaew**
#### Description

See https://trac.macports.org/ticket/61651

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.0.1 20B29
Xcode 12.2 12B45b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by rnkn** [comment]
Would it be worthwhile adding a note with instructions on adding this to one's `.bash_profile` similar to the note on `pass`?

**Comment by lpefferkorn** [comment]
👍

**Comment by mf2k** [comment]
In your first commit message, change:

`See https://trac.macports.org/ticket/61651`

To:

`Fixes: https://trac.macports.org/ticket/61651`

So that the ticket will get closed.

**Comment by judaew** [comment]
> So that the ticket will get closed.

Thanks ☺️

**Comment by judaew** [comment]
LGTM, tests are passed.

**Comment by rnkn** [comment]
Thanks!

**Pull request merged**
