### PR TITLE
Okapi: new port

### PR DESCRIPTION
**Pull request by amake**
#### Description
Okapi is a framework and application suite for localization.

###### Tested on
macOS 10.13.2 17C88

Xcode 9.2 9C40b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by amake** [comment]
I assume you are referring to the wrapper scripts?

In that case, there are two reasons:

1. The upstream scripts refer to resource files by relative paths and need to be invoked by their actual path (otherwise I would just symlink them)
2. In the case of Rainbow.app, the program can be launched normally with a GUI but also offers CLI functionality, so it would be nice to have that easily accessible as e.g. `rainbow` (but it can't be a symlink per 1 above)

**Comment by pmetzger** [comment]
@amake Are the wrapper scripts the only binaries in question?

@neverpanic Are wrapper scripts okay? (Should we perhaps be including those in `files`?)

**Comment by amake** [comment]
@pmetzger The port installs a couple apps to /Applications/MacPorts as well.

As for generating wrapper scripts in code rather than in `files`, there are numerous examples of this in other ports such as `jython`.

**Comment by pmetzger** [comment]
@neverpanic Advice?

**Comment by neverpanic** [comment]
I didn't notice this was Java. We in fact do usually ship upstream binaries for Java software.

It's just other languages where we normally require compilation from source, so I guess this is fine.

**Comment by pmetzger** [comment]
@neverpanic Any other comments on the portfile, or should I just pull and close?

**Comment by neverpanic** [comment]
@pmetzger No other comments from me, feel free to merge.

**Comment by pmetzger** [comment]
Merged! Thanks for your patience, @amake.

**Comment by amake** [comment]
Thanks @pmetzger for taking a look at an old PR :)

**Pull request merged**
