### PR TITLE
nicotine-plus: update to 3.3.0

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mathiascode** [comment]
Thank you for updating the package. The python3-gdbm dependency is no longer required in 3.3.0.

Any reason for force-enabling the GTK 3 version of Nicotine+ (NICOTINE_GTK_VERSION=3)? It will still work for now, but only the GTK 4 version will be actively tested on macOS and Windows moving forward.

**Comment by barracuda156** [comment]
@mathiascode Thank you for the info!
I am not sure I tried to build it with Gtk4 (and to be honest, not sure whether it works in Macports, since I had problems with building something else against it on Sonoma), I will try. It may or may not be desirable to keep some older macOS versions at Gtk3 (has to be tested), but that is no big deal, and for sure it is preferable to use the Gtk version actively supported by the upstream, at least on the current macOS.

**Comment by kencu** [comment]
gtk4 works in macports.

the quartz variant of gtk4 is much more rigorously tested upstream than the x11 variant is on Darwin.

**Comment by barracuda156** [comment]
@kencu Got it, I will move this to `gtk4` with the next update then, if not for all systems, then at least for new ones.

**Pull request merged**
