### PR TITLE
minivmac-devel: Update to 36.00alpha-20180715

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

Updates minivmac-devel to 36.00alpha-20180715.

The configuration system has changed from a 68K Macintosh application that must be run within Mini vMac to a C program that can be compiled and run on macOS. This lets us throw out all the code for running a bootstrap copy of Mini vMac and shuttling data between the build machine and the emulator, which makes the build much faster. It also means the port can now be built without needing the Macintosh Plus ROM file.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.6 17G65
Xcode 9.4.1 9F2000 

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] checked your Portfile with `port lint`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by gingerbeardman** [comment]
It's interesting that this build has blurry graphics, as I also see this in my builds.

But official versions downloaded from gryphel have sharp graphics.

Perhaps some sort of retina-compatibility compiler/setup issue.

- macports
  Screen shot 2021-03-07 at 14 25 36
- my own
  Screen shot 2021-03-07 at 14 26 37
- official
  Screen shot 2021-03-07 at 14 25 36

**Comment by ryandesign** [comment]
Thanks for reporting it but a comment in a nearly three year old resolved pull request is not a good place to report a bug. The place to report MacPorts bugs is [our issue tracker](https://trac.macports.org) but I don't think this is a MacPorts-specific bug. 

It looks like this blurry graphics issue has been reported to the developer of mini vmac before ([once](https://www.gryphel.com/c/mail/v10.html#m210), [twice](https://www.gryphel.com/c/mail/v10.html#m220)).

Assuming you are using macOS Catalina or later, the difference you observe between compiling on your system (or using our version) and the version available from Gryphel might be explained by the Gryphel binary being compiled with an older SDK. If so, that means mini vmac isn't fully compatible with new behaviors introduced in the 10.15 SDK.

I did not see the problem on High Sierra when I sent Paul the small [patch to enable retina support](https://www.gryphel.com/c/mail/v8.html#m86) in 2018.

Assuming you are running the latest version of mini vmac 37 from this year, you might report it to him again to remind him.

Presumably you could work around the problem by disabling retina mode (get info on mini vmac in the finder and enable the low resolution checkbox).

If you have an older system you could try compiling mini vmac with the 10.14 SDK or earlier (and then moving that binary to your 10.15 or newer system) to see if that solves the problem.

**Comment by gingerbeardman** [comment]
Thanks, I do appreciate this is not the best place for this. I filed it here to try to make it specific to this port rather than MacPorts as a whole. Apologies.

I'm already compiling and using on 10.14.6. I may try a

The *Run in Low Resolution* trick is a good idea, but sadly it doesn't fix the issue completely (it's blurry during use but fine for screen grabs).

So I've reported it to the developer again (the two previous reports you quote are actually the same one). Thanks again

**Comment by ryandesign** [comment]
> Thanks, I do appreciate this is not the best place for this. I filed it here to try to make it specific to this port rather than MacPorts as a whole. Apologies.

Our issue tracker is the correct place to report bugs in ports. Set the Component field to "ports".

> I'm already compiling and using on 10.14.6. I may try a High Sierra VM.

If you're using Xcode 11, you still only have the 10.15 SDK even if you are on 10.14. You could try Xcode 10 instead which has the 10.14 SDK.

> (the two previous reports you quote are actually the same one)

One was from March and wasn't signed with a name and the other was from April so it's hard to tell if they were from the same person.

**Comment by gingerbeardman** [comment]
You're correct about the two issues, my mistake. Will try Xcode 10.

**Comment by gingerbeardman** [comment]
Xcode 10 and related tools - no change

**Comment by gingerbeardman** [comment]
Success! Xcode 9.4.1, specifying -ev 9410 on the command line, builds with sharp graphics.

Thanks again and sorry for cluttering up this old PR.

**Pull request merged**
