### PR TITLE
prima: update homepage

### PR DESCRIPTION
**Pull request by zaikunzhang**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@zaikunzhang Could you please make the commit title in a form “prima: update homepage” or something like that. It should start with the port name.

**Comment by barracuda156** [comment]
@zaikunzhang By the way, feel free to add yourself as a maintainer for `prima`.

**Review by barracuda156 — CHANGES_REQUESTED** [review]
We also need the commit message to be changed accordingly, because that will reflect in commit history, and it should be easily readable.

**Comment by zaikunzhang** [comment]
Thank you @barracuda156 . I opened a new one.

**Pull request closed without merging**
