### PR TITLE
haskell_cabal PG: Fix arm builds

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6 21G115 arm64
Xcode 14.0 14A309

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by neverpanic** [comment]
So, is this not required for arm64, or will this just produce broken binaries on arm64?

If it's the latter, what do we actually gain from merging this now?

**Comment by neverpanic** [comment]
Ah, I've found https://trac.macports.org/ticket/65890 now. I guess we could just re-sign the binaries after this modification to prevent the crash, and the hack would still work on arm64?

**Comment by essandess** [comment]
> So, is this not required for arm64, or will this just produce broken binaries on arm64?
> 
> If it's the latter, what do we actually gain from merging this now?

I discovered that the existing `datadir` hack breaks `arm` binaries, so I disabled this hack for `arm`. (Upstream `cabal` has acknowledged and prioritized this issue.)

We want to merge ASAP because MacPorts is now distributing broken `arm` binaries for these ports, as well as breaking the buildbot builds for the ports that rely upon them.

**Review by neverpanic — CHANGES_REQUESTED** [review]
Please replace this patch with this instead:

```diff
diff --git a/_resources/port1.0/group/haskell_cabal-1.0.tcl b/_resources/port1.0/group/haskell_cabal-1.0.tcl
index dfa56f1b8c0..9501b157e84 100644
--- a/_resources/port1.0/group/haskell_cabal-1.0.tcl
+++ b/_resources/port1.0/group/haskell_cabal-1.0.tcl
@@ -297,6 +297,9 @@ post-destroot {
             xinstall -m 0755 \
                     ${binfile}.slash_hack \
                     ${binfile}
+            if {${configure.build_arch} eq "arm64"} {
+                system "codesign -f -s - ${binfile}"
+            }
             delete  ${binfile}.slash_hack
         }
     }
```

**Comment by essandess** [comment]
> Ah, I've found https://trac.macports.org/ticket/65890 now. I guess we could just re-sign the binaries after this modification to prevent the crash, and the hack would still work on arm64?

Is there a way to get this hack to work? My preference is to throw in the towel unless it’s easy. And just wait for upstream to fix this. Practically, there is a limited number of ways to hit this issue.

**Comment by neverpanic** [comment]
> Is there a way to get this hack to work? My preference is to throw in the towel unless it’s easy. And just wait for upstream to fix this. Practically, there is a limited number of ways to hit this issue.

Yes, see my proposed patch. I verified that this works on arm64.

**Comment by essandess** [comment]
> see my proposed patch. I verified that this works on arm64.

Holy smokes it works—thanks! I didn't know about `codesign`.
```sh
^@/opt/local///////////////////////////////////////////////////////////////////////\
///////////////////////////////share/alex^@^@^@^@^@^@alex_datadir^@^@^@^@

$ alex --help
Usage: alex [OPTION...] file
```

**Comment by essandess** [comment]
> Please replace this patch with this instead:

Done, thanks again.

**Comment by neverpanic** [comment]
Unfortunately you now modified the last commit `lhs2tex: revbump` to contain the fixes, but the original `haskell_cabal PG: Fix arm builds` still just disables the datadir handling on arm64.

Can you fix that?

**Comment by essandess** [comment]
Oops, fixed, thanks.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
