### PR TITLE
py-pytorch-lightning: Submission

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Review by cjones051073 — CHANGES_REQUESTED** [review]
Can you fix the lint warnings please.

**Comment by essandess** [comment]
> Can you fix the lint warnings please.

Done thanks.

**Comment by essandess** [comment]
PR dependency:

#8783 → #10459

**Comment by essandess** [comment]
I’m unable to see the macOS 11 CI error. Is this simply a timeout?

**Comment by cjones051073** [comment]
> I’m unable to see the macOS 11 CI error. Is this simply a timeout?

most probably yes.

**Comment by cjones051073** [comment]
ok. py38 version build fine here for me on macOS11.

**Pull request merged**
