### PR TITLE
grass: update to GRASS 8.0 (revitalize obsolete port), 2nd attempt

### PR DESCRIPTION
**Pull request by nilason**
#### Description

GRASS GIS has now released a new major version 8.0.0. Efforts have been made to move from "versioned" executable, e.g. starting version 7.8.x was made with grass78, now the default is grass.

This PR suggests to revitalize the old grass port, for coming releases. The transition from 6 to 7 (up till 7.8) was a troublesome period (integration of Python as API and GUI, and then Python 2 to 3 etc.) which necessitated to a degree distinction of version. Now the situation is more stable.

The intention of this PR is to replace grass7 and grass8 with grass, for any upcoming versions (GRASS 8+).

Continuation of #13801.

###### Tested on

macOS 12.3 21E230 arm64
Xcode 13.3 13E113

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by nilason** [comment]
@Veence Reopening this, for replacing not only grass7 but also grass8.
I think grass7 could stay for a while, but grass8 should be made obsolete and deleted as soon as possible.

I moved over the OpenMP stuff from grass8. Now visible. That's great addition, with GRASS 8.2 (very soon to be released) a number of modules will be updated with openmp support.

Note: I added Python 3.10 support, but present wxPython 4.1.1 is very buggy with 3.10 so GUI will not work as expected (shouldn't be any problem non-gui use though).

@ryandesign Thanks for the tip:
> 
> ```
> pre-configure {
>     configure.args-append --with-grass=[exec ${prefix}/bin/grass --config path]
> }
> ```
> 
> (It has to be in `pre-configure`, not out in the main part of the Portfile, because you can't be sure until right before the configure phase that the dependencies (grass) have been installed.)

that should be useful for QGIS I suppose.

**Comment by nilason** [comment]
@Veence What do you say?

**Comment by Veence** [comment]
Oh, sorry, I was following the mail and did not notice there was something to merge.
I’ll do it right away

**Comment by Veence** [comment]
Done

**Comment by nilason** [comment]
Great, thanks!

**Comment by Veence** [comment]
You’re more than welcome

**Pull request merged**
