### PR TITLE
nektarpp: update to 5.5.0

### PR DESCRIPTION
**Pull request by mdave**
#### Description

Updates `nektarpp` to 5.5.0. Patches small issue with `zlib` detection which has been submitted upstream for next release.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 14.2 23C64 arm64
Xcode 15.2 15C500b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
CI failed, apparently because of weird options being passed to `find`.

**Comment by reneeotten** [comment]
> CI failed, apparently because of weird options being passed to `find`.

No, the "checksums" are wrong.

**Comment by pmetzger** [comment]
Odd error that I saw in the CI then. Regardless, it needs fixing so it can be merged.

**Comment by reneeotten** [comment]
ping @mdave

**Comment by pmetzger** [comment]
@mdave We'll have to close this if it doesn't get fixed, which would be a great shame.

**Comment by mdave** [comment]
@pmetzger @reneeotten apologies for the delay, have been afk for a few days - have just updated checksums, hopefully this is now corrected.

**Comment by pmetzger** [comment]
@mdave It's still failing unfortunately.

**Comment by mdave** [comment]
@pmetzger thanks -- I think the issue here is that `opencascade` requires a revbump after the last `onetbb` update. I had spotted this before, and put in a temporary symlink to resolve but forgot to do this before this PR. I've pushed that change and will see if that fixes it. I just tested locally and it seems to now work.

**Comment by reneeotten** [comment]
> @pmetzger thanks -- I think the issue here is that `opencascade` requires a revbump after the last `onetbb` update. 

that indeed seems to resolve the build failure. Please separate this in two different commit, each touching only one Portfile; after that we can merge. Thanks!

**Comment by mdave** [comment]
@reneeotten No problem, have done.

**Pull request merged**
