### PR TITLE
youtube-viewer: submission of new port (v3.8.0)

### PR DESCRIPTION
**Pull request by TheKevJames**
#### Description
Create new port for the `youtube-viewer` project. [Link](https://github.com/trizen/youtube-viewer).

This is my first Portfile submission, please let me know if I've made a mistake!

~I'm especially curious if there's a good way to alias the package name -- though this is build as a perl5 package and thus automagically renamed to `p${perl.major}-${full_pkg_namespace}`, I suspect it may be easier for users to find if we could alias `youtube-viewer` to `p5-www-youtubeviewer`. I am not sure if there is a policy in place for perl5 modules which are also end-user applications like this -- please let me know!~

_Solved, thanks @dbevans!_

~This changeset currently includes a second new port (`p5-lwp-useragent-cached`). Please ignore it for now: I've opened #9003 for tracking that particular submission and will rebase this changeset once the other is merged. Since `youtube-viewer` relies on `p5-lsp-useragent-cached` for the `+perf` variant, I figured it would make more sense to introduce them in a dependency chain.~

_Solved and rebased, #9003 has been merged!_

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix
- [x] submission

###### Tested on
macOS 10.15.5 19F101
Xcode 12.1 12A7403

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by dbevans — CHANGES_REQUESTED** [review]
You're right about not makmaking this a p5- port.  The usual approach in this instance is to ask the perl5 PG to create perl variants of the form +perl5_28 instead of versioned subports.  The way to do this is to start with the following

```
perl5.require_variant      yes
perl5.conflict_variants    yes
perl5.branches             5.26 5.28 5.30
perl5.default_branch       5.28
perl5.create_variants      ${perl5.branches}

name youtube-viewer
```
you can then remove the conditional based on subport version as there won't be any.  Just declare the dependencies directly.

For an example, look at the Portfile for port ack.

**Comment by TheKevJames** [comment]
@dbevans thanks, that seems to have done the trick wonderfully! Updated the changeset with your recommendations.

**Comment by TheKevJames** [comment]
```
--->  Verifying Portfile for youtube-viewer
Warning: Dependency port:perl5.28 specified multiple times in depends_lib
--->  0 errors and 1 warnings found.
```
Hmm, I seem to be missing something here -- as far as I can tell, I'm not even specifying this _once_!

**Comment by TheKevJames** [comment]
@dbevans did you have a chance to take another look at this?

**Comment by kencu** [comment]
I thought I would test this for you, but mpv won't build so I can't.

I did wonder why it was in the audio section, assuming it is  youtube video viewer....

**Comment by TheKevJames** [comment]
@kencu appreciate the eyes on this! What issue did you run into with `mpv`? I just pulled in the few months of changes to other ports, in case there have been mainline changes to `mpv` in the meantime, but I can't say I've run into anything here myself; I've been running a `youtube-viewer` installed off this PR for months now. If you have an error message I can take a look at, that'd be great! I'm still pretty new to writing portfiles and it's totally possible I missed something there.

As for why it's in `audio`... that's a great question! It completely slipped my mind to consider putting it anywhere else, since my own usecase is just for listening to music. I'll move it over to `multimedia`.

**Comment by TheKevJames** [comment]
Looks like the job failure is unrelated -- just an issue uploading logs to the Github Actions artifact host. I noticed in some personal projects Github Actions was running a bit slow yesterday.

@reneeotten any chance you could take a look at this? :)

**Pull request closed without merging**
