### PR TITLE
libzzip: update to 0.13.69

### PR DESCRIPTION
**Pull request by mojca**
#### Description

@kencu: testing on  any older system greatly appreciated.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.3 17D102
Xcode 9.2 9C40b 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`? **tests FAIL**
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mojca** [comment]
I thought the release would happen sooner. Removing PR until release.

**Comment by mojca** [comment]
I like the failed log:
```
DEBUG: Portfile is from the future - check date and time of your system
    while executing
"open_statefile"
    (procedure "target_run" line 14)
    invoked from within
"{*}$handler $ditem"
Error: Portfile is from the future - check date and time of your system
Error: See /opt/local/var/macports/logs/_Users_travis_build_macports_macports-ports_archivers_libzzip/libzzip/main.log for details.
```

**Comment by pmetzger** [comment]
@mojca Another spurious Travis error. :(

Do you think we can merge this now?

**Comment by mojca** [comment]
Oh, no, this is in fact an error in MacPorts. I'm not saying it couldn't have been caused by a tiny clock difference between servers, but it's still strange.

**Pull request merged**
