### PR TITLE
openjdk{17,18}: Fix builds on arm64

### PR DESCRIPTION
**Pull request by usersxx**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by usersxx** [comment]
@saagarjha, This or brings you patch back on `openjdk17` and `openjdk18`

**Comment by usersxx** [comment]
> @saagarjha, This brings you patch back on `openjdk17` and `openjdk18`

I though this change was already done but it has been applied on newer versions.

**Comment by usersxx** [comment]
@mascguy, Can you merge this pr

**Comment by mascguy** [comment]
> @mascguy, Can you merge this pr

Sure, I'll do so as soon as CI completes.

**Pull request merged**
