### PR TITLE
py-tensorflow-metal: Update to version 0.6.0; py-tensorflow-macos: Update to version 2.10.0

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6 21G115 x86_64
Xcode 14.0 14A309

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Looks good, with just one sole complaint: Can you eliminate these references?

```
port lint py310-tensorflow-macos:
Error: conflicts references unknown port: py310-tensorflow
Error: conflicts references unknown port: py310-tensorflow1
Error: conflicts references unknown port: py310-tensorflow-addons
```

After that's done, we're good-to-go.

**Review by mascguy — APPROVED** [review]
LGTM. Will merge once lint errors fixed.

**Comment by essandess** [comment]
> LGTM. Will merge once lint errors fixed.

Those aren't actual errors—port `port lint` false alarms that have long existed. OIt's okay the port declares a conflict with a nonexistent port, that, we hope, will exist soon from #15397.

Please merge asap because this is our only working tensorflow port.

**Comment by mascguy** [comment]
> > LGTM. Will merge once lint errors fixed.
> 
> Those aren't actual errors—port `port lint` false alarms that have long existed. OIt's okay the port declares a conflict with a nonexistent port, that, we hope, will exist soon from #15397.
> 
> Please merge asap because this is our only working tensorflow port.

No worries, I'll let it go this time...  ;-)

**Pull request merged**
