### PR TITLE
py-poppler-qt5: use_xcode when py-pyqt5 uses it

### PR DESCRIPTION
**Pull request by dliessi**
Closes: https://trac.macports.org/ticket/65600

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G14042 x86_64
Xcode 10.1 10B61
(actually not tested on my system)

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by dliessi** [comment]
I'm sorry, the description says "tested on" and my system's info, but I actually didn't test the change, since it does not affect my version of macOS.

I would appreciate if whoever commits this change can also either test whether frescobaldi installs correctly on Monterey and/or Big Sur, or schedule a build of frescobaldi on the buildbots.
Thank you.

**Comment by mascguy** [comment]
@dliessi I just added a 2nd proposed commit, to remove support for Python 3.5 and 3.6. Let me know if that's OK with you.

**Comment by mascguy** [comment]
> @dliessi I just added a 2nd proposed commit, to remove support for Python 3.5 and 3.6. Let me know if that's OK with you.

Removed Python 2.7 as well. Again, let me know your thoughts!

**Comment by mascguy** [comment]
> > @dliessi I just added a 2nd proposed commit, to remove support for Python 3.5 and 3.6. Let me know if that's OK with you.
> 
> Removed Python 2.7 as well. Again, let me know your thoughts!

No ports depend on the Python 2.7, 3.5, and 3.6 subports, and they don't build anyway. So no need for further discussion on this.

Merging.

**Pull request merged**
