### PR TITLE
py-wxpython-4.0: add python 3.11

### PR DESCRIPTION
**Pull request by pietvo**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 13.4 22F66 x86_64
Xcode 14.3 14E222b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by nilason** [comment]
Be careful with this, if I remember correctly wxPython 4.2 is not working well (at all) with Python 3.11.

**Comment by nilason** [comment]
> Be careful with this, if I remember correctly wxPython 4.2 is not working well (at all) with Python 3.11.

I just tested with grass and it seems to work fine with Python 3.11 + wxPython 4.2.0.

**Comment by pietvo** [comment]
> Be careful with this, if I remember correctly wxPython 4.2 is not working well (at all) with Python 3.11.

I have been using it dor a couple of months now. Of course my use is limited, so there might be areas where it fails. But that could be dealt with later if it occurs.

**Comment by nilason** [comment]
> > Be careful with this, if I remember correctly wxPython 4.2 is not working well (at all) with Python 3.11.
> 
> I have been using it for a couple of months now. Of course my use is limited, so there might be areas where it fails. But that could be dealt with later if it occurs.

I was first hit by the list of issues: https://github.com/wxWidgets/Phoenix/issues?q=is%3Aissue+is%3Aopen+3.11, but now I actually tested this PR with GRASS and Python 3.11 and there seems to be no problem. One of the upstream issues is dealt with already one of the patches.

**Review by reneeotten — CHANGES_REQUESTED** [review]
there is a recent release of version 4.2.1 which has added the Python 3.11 classifier so it should be supported in that version. Can you please make the update to this latest release as part of this PR and then we can merge?!

**Comment by pietvo** [comment]
> there is a recent release of version 4.2.1 which has added the Python 3.11 classifier so it should be supported in that version. Can you please make the update to this latest release as part of this PR and then we can merge?!

OK, I'm testing this.

**Comment by nilason** [comment]
Version 4.2.1 and Python 3.11 works fine with `grass`. Looks good to me!

**Review by reneeotten — APPROVED** [review]

**Comment by reneeotten** [comment]
thanks @pietvo for the update and @nilason for the additional testing!

**Pull request merged**
