### PR TITLE
libnick, parabolic: new ports and their deps

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

A port for this library: https://github.com/NickvisionApps/libnick
It will allow to build some useful apps which depend on it.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.7
Xcode 15.4

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
@barracuda156 what's the status here; the PR queue is not for parking unfinished stuff

**Comment by reneeotten** [comment]
> @reneeotten Everything works, I just waited for a release to drop a huge backport. Will do that soon, been busy today with other stuff.

that sounds like a good plan - nobody wants to add 9000+ lines ;)

**Comment by barracuda156** [comment]
I need to resolve something still. To be updated soon.

**Comment by barracuda156** [comment]
@reneeotten Once CI pass, should be good to go. All patches are dropped now.

(I got a weird error on Rosetta yesterday, but it is not a reason to postpone this, native powerpc works fine.)

**Comment by barracuda156** [comment]
@reneeotten @reneeotten This is ready to go.

**Pull request merged**
