### PR TITLE
py-astropy: update to 3.0.1

### PR DESCRIPTION
**Pull request by lpsinger**
#### Description

And fall back to 2.0.5 for Python < 3.5.

###### Type(s)

- [X] enhancement

###### Tested on

macOS 10.13.4 17E199
Xcode 9.3 9E145

### CODE REVIEW

**Comment by pmetzger** [comment]
@lpsinger Could you resolve the (very minor) conflict? Also @cdeil has said he can no longer maintain astropy so I'll merge as soon as you fix that.

**Comment by cdeil** [comment]
>  @cdeil has said he can no longer maintain astropy

No. For now, I just removed myself from the Astrometric ports
https://github.com/macports/macports-ports/pull/1648
That is something different from Astropy.

👍 to this update!

**Comment by pmetzger** [comment]
@cdeil Apologies!

**Comment by pmetzger** [comment]
Merged. Thank you, @lpsinger!

**Pull request merged**
