### PR TITLE
toxic: update to 0.13.1

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by reneeotten — CHANGES_REQUESTED** [review]
the "toxcore" port should ideally be using Python 3.12 after MacPorts changed its default version to that on January 1st.

**Comment by barracuda156** [comment]
@reneeotten I will start moving my Python-using ports to 3.12 once https://github.com/macports/macports-ports/pull/20761 is merged. While that issue was not evident earlier, 3.12 just fails to build without that.

**Comment by reneeotten** [comment]
> @reneeotten I will start moving my Python-using ports to 3.12 once https://github.com/macports/macports-ports/pull/20761 is merged. While that issue was not evident earlier, 3.12 just fails to build without that.

well that PR has been open for months and from looking at the comments that has very little change of being merged...

**Comment by pmetzger** [comment]
@reneeotten I suspect that's correct.

**Comment by barracuda156** [comment]
@jmroot @mascguy How about we unbreak Python 3.12 finally? The fix in question literally affects exclusively PowerPC, is genuinely needed and has been used elsewhere outside of Macports. Admittedly, PPC is of little concern to most of people here, but then why not merge it still, nothing else is touched.

I do not want to move my ports to a Python which does not build from master but requires local hacks. (This is opensource and I do not own any ports, obviously, so anyone could still do that, but I need a working Python as long as I maintain them.)

**Comment by pmetzger** [comment]
@barracuda156 You can always create a set of patches that apply only on PPC I suppose. Might I ask, though, why it is so important to keep machines that haven't been made in 18 years running? It seems to be taking a great deal of your time.

**Comment by barracuda156** [comment]
@pmetzger Sure, I will change that PR, making a separate patch version to be applied only for `darwin powerpc`. And nothing will be changed otherwise. I am totally okay with that.

Why bother supporting? This question is not specific to PPC: why bother supporting 10.7, or i386? (Why support anything at all aside of what one uses personally?)
One answer is that because there are people using those (regardless of whether we personally are among them). Why not do a little good to others when it costs nothing?
However, it is not needed to care about other people preferences here in order to conclude that it makes sense, as long as you care about Macports project in general.
Because in result of someone doing work for a specific platform (which does not benefit you as such in any way) we get bugs fixed (and this may benefit much more users), we get new ports added, Macports acquires more users and enjoys “free advertising”, so to speak.

Sure enough, all this may not outweigh costs of fixing a bug for an older platform for a given developer, as resources including time are finite. But I do not get why it could make a better sense to forego improvements, leave bugs unfixed if they do not show up in someone’s personal setup, disincentivize contributions and lose some potential end-users (however few at the margin), when the work is done by someone else, so costs are zero. Ex ante improvements are minimal? Okay, but it costs nothing.

**Comment by pmetzger** [comment]
The thing is, I think the PPC support *is*, in fact, taking a lot of time, probably time disproportionate to the size of the community still using 18 year old machines. Anyway, given that this now only impacts PPC, I think we can probably commit it.

**Comment by barracuda156** [comment]
@pmetzger Thank you for merging.

P. S. Just to be clear, here (in this port) we did not have anything PowerPC-specific. @reneeotten asked if I can switch it to use Python 3.12, and Python does need a PowerPC-specific fix, which upon your advice I made now as a separate patch, with non-PPC systems being totally untouched. (Even though the PPC addition is minimal and safe so can be added into a general < 10.7 patch, I have no objections to have a separate patch either.) That PR is unmerged so far, and until it gets merged in some form, I am not moving my ports to the new python.
However, this PR indeed is totally fine, since Python 3.11 works.

**Comment by pmetzger** [comment]
I understood. I might not have made my comment comprehensible enough.

**Pull request merged**
