### PR TITLE
biblatex-biber: update version & Perl dependency

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.2
Xcode 10.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM.

**Comment by drkp** [comment]
So, this completely broke biber. 

biber 2.12 is not compatible with biblatex 3.11, which is what's in the current version of texlive. (Yes, biber is not backwards-compatible, and yes, this is pretty awful.)

Is the upgrade to 2.12 needed for some reason? It looks like 2.11 also works fine with perl 5.28...

**Comment by mojca** [comment]
@pmetzger: this is what you get when accepting "trivial updates" faster than in 72 hours :)

No, of course there's absolutely no need to upgrade. I assume @MarcusCalhoun-Lopez simply did it while upgrading to a newer version of Perl and noticing the software was out of date. I would do the exact same thing and then leave it to the maintainer to properly test the changes. I assume that updating biblatex before TL19 is not quite trivial.

**Comment by pmetzger** [comment]
@mojca It's true, several times a year something bad happens, but on the other hand, that's vs. hundreds and hundreds of pull requests. Generally I think the right thing is probably to get ourselves better CI infrastructure so we have better ways of noticing breakage in advance; sadly Travis isn't good enough for this right now.

**Comment by mojca** [comment]
Better Travis would not help in any way given our lack of tests :)

**Comment by pmetzger** [comment]
Well, right now, a very large fraction (a majority in fact) of things that actually are fine fail the CI tests for spurious reasons, so better CI would at least let us distinguish what builds from what doesn't. Even reliably knowing what builds so that a failing CI test could let us veto a change would be a win.

Another significant improvement would be metadata about which package updates would require dependents to be bumped; it would allow us to automate warnings about changes.

**Pull request merged**
