### PR TITLE
Gpsd updates

### PR DESCRIPTION
**Pull request by michaelld**
#### Description

Fix gpsd to build using Boost 1.67.0+ via a patch that's already committed upstream. Add michaelld as comaintainer. Add gpsd-devel subport.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.12.6 16G1510
Xcode 9.2 9C40b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by michaelld** [comment]
Mentioned in one of the commits, but I'll do it here too:

Closes: https://trac.macports.org/ticket/56309

**Comment by pmetzger** [comment]
The commits seem to be doubled or some such when I look at them?

**Comment by pmetzger** [comment]
(There's also a conflict.)

**Comment by michaelld** [comment]
OK we're back to just the 3 main commits. If the buildbots work, then these changes are good to go IMHO. Once these are in place, I'll update the devel port for +pythonXY variants, based on more recent gpsd commits than that in this PR.

**Comment by michaelld** [comment]
Is @ryandesign OK with me adding myself as comaintainer? I know in theory it's OK, but I think it's best to check / verify first.

**Comment by michaelld** [comment]
OK well it's been long enough so I'm going ahead and merging this PR.

**Comment by ryandesign** [comment]
Sure, that's fine. Sorry, there's too much MacPorts mail these days for me to be able to read it all.

**Comment by michaelld** [comment]
Thx. I didn't think you'd have an issue, otherwise I'd have waited longer. MacPorts mail / Trac / GitHub is pretty busy these days: yes!

**Comment by pmetzger** [comment]
@ryandesign I suggest sorting the mail into multiple boxes so things where you are tagged become more obvious.

**Pull request merged**
