### PR TITLE
Re: https://trac.macports.org/ticket/54438

### PR DESCRIPTION
**Pull request by hexadecagram**
PR submitted as per the suggestion of kencu.

### CODE REVIEW

**Comment by kencu** [comment]
The failed checks have nothing to do with your commit. Looks good! Just will need to have a member adjust the commit message to the macports style. Thanks!

**Comment by raimue** [comment]
Please follow [CommitMessages](https://trac.macports.org/wiki/CommitMessages) for the commit message format.

Is there actually a need to run both autoreconf and automake? I guess autoreconf should be enough.

**Comment by kencu** [comment]
message sent to @hexadecagram by email with instructions. He should fix up shortly.

**Comment by kuni255** [comment]
I'll propose different solution for this problem ( https://trac.macports.org/ticket/54467#ticket ). So I close this request.

**Comment by neverpanic** [comment]
Closing as requested.

**Comment by kencu** [comment]
Hold on. I'm not sure what @kuni255 was thinking, but the link he referenced appears to nothing to do with this PR. Please consider reopening (and committing) this PR, and then maybe we can figure out what @kuni255 is trying to accomplish.

**Comment by neverpanic** [comment]
Sorry, I didn't see that @kuni255 wasn't who submitted the PR.

**Comment by neverpanic** [comment]
A dependency on `gtk-doc` was required because of the autoconf modules used by `libvirt-glib`'s configure system are provided by `gtk-doc`.

I added the dependency and committed the change. Thanks for the PR!

**Comment by kencu** [comment]
Thanks! @hexadecagram , congratulations, you are now a contributor!

**Pull request closed without merging**
