### PR TITLE
docker-compose: use python311

### PR DESCRIPTION
**Pull request by mohd-akram**
#### Description

Closes: https://trac.macports.org/ticket/67693

###### Type(s)

- [x] enhancement

###### Tested on
macOS 13.4.1 22F770820d x86_64
Xcode 14.3.1 14E300c

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
Just a side note: why not migrate to podman / podman-compose? :)

**Comment by mohd-akram** [comment]
podman-compose lacks many features. docker-compose can be used with podman (after running `podman-mac-helper`).

**Comment by catap** [comment]
@mohd-akram thanks, the only one feature which I've encountered as missed is https://github.com/containers/podman-compose/issues/540

**Comment by catap** [comment]
Thus, MacPorts has quite old (python based) version of docker-compose; I guess it also hasn't got all features :(

**Comment by mohd-akram** [comment]
@catap It's not too old (yet), I'm not sure what features the Go version adds, but most scripts still use V1 I think.

Is this good to merge?

**Comment by catap** [comment]
@mohd-akram unfortunately I haven't got write access. Let me ping @mascguy or @reneeotten.

**Review by mascguy — APPROVED** [review]

**Comment by mohd-akram** [comment]
Thanks @mascguy.

**Pull request merged**
