### PR TITLE
port:opencv : cleanup and fixes

### PR DESCRIPTION
**Pull request by RJVB**
The main fix allows building opencv on 10.12 where the QuickTime and
QTKit SDKs have been made unavailable. This is done by building against
AVFoundation on 10.9 and newer.

Confusion between installed Qt versions is avoided by specifying the
desired version (`-DWITH_QT={4,5}`)

OpenCV supports building bindings for Python 2 and Python 3; the port
now allows that too. Python2.7 is used for building, unless only Python 3
bindings are requested.

Two additional variants expose OpenCV's support for the AVX and AVX2
instruction sets. I'm not sure if there are still a significant number
of Macs that have SSE4x but no AVX (nor if SSE4x support gives a
noticeable performance boost on such systems) so I have coupled SSE4x
with AVX support.

The patch also does some cleanup, moving candidate patches
that have to be checked out (by the port maintainer!) to a subdirectory.

### CODE REVIEW

**Comment by larryv** [comment]
This commit is very large and should be broken up.

**Comment by RJVB** [comment]
It's a bit of an overhaul but one that looks larger than it is. I guess that ultimately it'll be up to stromnov to decide how he (she?) incorporates the changes.

**Comment by RJVB** [comment]
On Thursday November 24 2016 01:14:59 Mojca Miklavec wrote:

> This change is weird. A variant that conflicts with an empty set of variants?

Thanks, that's an oversight. Strange that this doesn't lead to an error, but yes, the intention is to remove the conflict between the python 2.x and python 3.x variants, while keeping a conflict between the Python 3.x variants (and that was tested to work despite the weird syntax).

**Comment by mkae** [comment]
Oh, sorry, I had completely forgotten about this PR here and just worked from trac, closing the respective `opencv` [issue 52328](https://trac.macports.org/ticket/52328) already.

An oversight on my end!!! :-(

Can you update your PR accordingly, @RJVB?

**Comment by RJVB** [comment]
What can I do about this? The Portfile as I would propose it hasn't changed.

Do I have to close this PR, delete the corresponding branch, and then recreate the whole thing from scratch? That would suck...

**Comment by larryv** [comment]
That would definitely suck. You just have to rebase your local `opencv` branch against our current master, resolve the conflicts manually, and force-push it. The PR should pick up the new branch.

**Comment by mkae** [comment]
@RJVB, stay put, I am trying to recover from my mistake and will do my best to rebase your macstrop version on top of the current git repo head.

**Comment by mkae** [comment]
So, I've committed these changes to [the main git repo just now](https://github.com/macports/macports-ports/commit/14a1fa8d5e1d4e07a6f2538d1779f5f42714aed3), as I didn't manage to push my changes in your branch here... It always claimed that there're nothing to push! :-(

OTOH, I am not 100% sure that this commit is fine as is. Could it be, that it needs another revbump??

**Comment by RJVB** [comment]
Marko, you missed 2 details:

- `-DCMAKE_VERBOSE=ON` : this is not a CMake option, and the variable isn't used in opencv's CMake files either.

- the `patch-pchsupport.diff` patch is obsolete.

**Comment by RJVB** [comment]
Is there still a reason for me to keep the opencv branch around?

**Pull request closed without merging**
