### PR TITLE
ghc: Update to version 9.6.4; hscolour: Update to version 1.25; alex: Update to version 3.5.0.0

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.2.1 23C71 x86_64
Xcode 15.2 15C500b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by essandess** [comment]
I believe that these CI errors are timeouts and that this PR may be merged.

**Comment by pmetzger** [comment]
120 minutes is well below the timeout line.

**Comment by pmetzger** [comment]
It took about a minute to look at it and find:

> find: /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_lang_ghc/ghc/work/.gnupg/private-keys-v1.d: Permission denied

I will look at this PR again at the point where the summary page indicates that the CI is working.

**Comment by essandess** [comment]
> It took about a minute to look at it and find:
> 
> > find: /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_lang_ghc/ghc/work/.gnupg/private-keys-v1.d: Permission denied

That's still a CI issue. I don't have any control over that. Please merge this PR to update `ghc`.

**Comment by pmetzger** [comment]
No one else is having trouble with the CI, and certainly no one else is getting this error message. My strong assumption based on experience is that this is a mistake you made that you're not willing to try to debug. If you can find a specific issue, please tell the -dev list. When this passes the CI, I can merge it. Until then I'm leaving it alone. If someone else wants to go hunting to debug your problem they can do so, but I'm not really willing to spend more time on it.

**Comment by essandess** [comment]
These are CI errors to the best of my knowledge.

And I’ve already [asked](https://github.com/macports/macports-ports/pull/20749#issuecomment-1756588513) you previously to refrain from your inappropriate habit of making unwarranted and unprofessional personal attacks.

**Comment by pmetzger** [comment]
I'm not making attacks. And I'm now withdrawing from this. Other people can handle your PRs.

**Comment by essandess** [comment]
Superseded by #22398, #22397, #22396.

**Pull request closed without merging**
