### PR TITLE
libjpeg-turbo-devel: update to 2.1.2

### PR DESCRIPTION
**Pull request by judaew**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.0.1 21A559 x86_64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Can you please update `libjpeg-turbo-devel` instead?

Once that's been fully validated, I'll update `libjpeg-turbo`.

**Comment by judaew** [comment]
Sure, done.

**Comment by mascguy** [comment]
Thanks! I'll merge this as soon as the CI jobs complete.

**Comment by mascguy** [comment]
@evanmiller Evan, the 2.1.2 release of `libjpeg-turbo` appears to include the AltiVec detection changes, per our brief discussion a few weeks ago:

https://github.com/libjpeg-turbo/libjpeg-turbo/commit/d401d6251412a2985810ffaffb90b448a6ee12a9

Would you mind re-testing `libjpeg-turbo-devel` on your PPC system(s), and verify that everything still works properly? Also, does that change potentially help with the work you had to do, relative to detecting AltiVec via the portfile?

**Comment by kencu** [comment]
Ah ha -- libjpeg-turbo tries to do runtime detection of altivec instead of compile-time. This is of course 100% exactly the correct thing to do.

However, it looks to me that the code just assumes that all Apple systems will have altivec, so it appears that they just enable it and don't do any runtime testing on Apple:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/d401d6251412a2985810ffaffb90b448a6ee12a9/simd/powerpc/jsimd.c#L137

Perhaps something like what they are doing on BSD here would look like the actual right kind of fix for this issue, if was made to / translated to / verified to work on Apple systems:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/d401d6251412a2985810ffaffb90b448a6ee12a9/simd/powerpc/jsimd.c#L149

**Comment by evanmiller** [comment]
@kencu Off the top of your head, do you know if the main dylib will still be loadable on a G3? My concern is that unless the Altivec-enabled functions are housed in a separate dylib, then dyld will simply see `ppc7400` in the dylib header and refuse to load it at all.

**Comment by kencu** [comment]
well, yes, good point...at this point I can't guess and would have to actually try some things to be sure.

**Comment by mascguy** [comment]
Just tested these changes on my PowerBook G4, and they appear to work fine. But with the caveat being that the machine has a PPC 7450.

**Comment by mascguy** [comment]
Evan, let us know when you've had a chance to test on your PPC systems.

Not urgent by any means. But would be great to be able to update our non-Devel port, once we're confident that all is well.

**Comment by evanmiller** [comment]
Builds OK here

**Comment by mascguy** [comment]
> Builds OK here

Do the various binaries work as well?

**Comment by evanmiller** [comment]
@mascguy The dylib loads fine but I have not tried specific functions

**Comment by mascguy** [comment]
> @mascguy The dylib loads fine but I have not tried specific functions

Sounds good.

Do the various binaries work (cjpeg, djpeg, etc)?

**Comment by evanmiller** [comment]
@mascguy `djpeg` works fine!

**Comment by mascguy** [comment]
Sounds good. And updated `libjpeg-turbo`, to correspond with this change.

Thanks for the confirmation Evan!

**Pull request merged**
