### PR TITLE
VLC: upgrade to v3.0.6 and introduce port:(lib)VLC2 for older systems

### PR DESCRIPTION
**Pull request by RJVB**
The VLC v3 series only build on Darwin 14 and up; while libVLC can still be built on Darwin 13.

This proposal copies the current VLC and libVLC ports to VLC2 (libVLC2) and upgrades them to v3.0.6 . 
Logic is introduced that aims to
- replace (install) port:VLC with (instead of) port:VLC2 on 10.9-
- replace (install) port:libVLC with (instead of) port:libVLC2 on 10.8-
- do the reverse when those systems are upgraded

- [X] bugfix
- [X] enhancement

###### Tested on
Mac OS X 10.9.5 (by me)
on 10.13 and/or 10.14 by at least one user of my macstrop repo

Closes: https://trac.macports.org/ticket/56799

### CODE REVIEW

**Comment by RJVB** [comment]
>Adding port multimedia/VLC
>Adding subport libVLC
>Warning: PortGroup locale_select 1.0 could not be located. locale_select-1.0.tcl does not exist.

I had already corrected this, a priori...
>Adding port multimedia/VLC2
>Warning: PortGroup locale_select 1.0 could not be located. locale_select-1.0.tcl does not exist.
>Adding subport libVLC2

>Error: Line 41 repeats inclusion of PortGroup obsolete

That's an error in lint then. The PG is included conditionally in 2 distinct subports.

**Comment by dbevans** [comment]
@RJVB: A few nits left with port lint:
```
$ port lint --nitpick VLC VLC2
--->  Verifying Portfile for VLC
Warning: Line 27 should be a newline (after PortGroup)
Error: Line 41 repeats inclusion of PortGroup obsolete
Warning: Line 42 should be a newline (after PortGroup)
--->  1 errors and 3 warnings found.
--->  Verifying Portfile for VLC2
Warning: Line 27 should be a newline (after PortGroup)
Error: Line 39 repeats inclusion of PortGroup obsolete
Warning: Line 40 should be a newline (after PortGroup)
```
Also I note that in the new VLC port, you've removed your GitHub handle,, email remains. Is that intentional?

**Comment by RJVB** [comment]
>@RJVB: A few nits left with port lint:

Yes, one of which is still a false alarm. The other ... do you really think a newline before a closing brace is useful and improves readability?
I don't, so I'm going to leave that as something to nitpick on (and point to port:qt5 for precedence).

>Also I note that in the new VLC port, you've removed your GitHub handle,, email remains. Is that intentional?

Actually, it was never there (in my original copy) and that is indeed intentional.

**Comment by mojca** [comment]
>> Also I note that in the new VLC port, you've removed your GitHub handle, email remains. Is that intentional?
> Actually, it was never there (in my original copy) and that is indeed intentional.

GitHub handle in upstream MacPorts repository is not meant to be optional. Your fork may contain arbitrary stuff, but we want to keep the handle here as long as you stay a maintainer.

**Comment by RJVB** [comment]
As you could have seen I already fixed this missing-whim-I-keep-my-repo-clean-off issue.

**Comment by dbevans** [comment]
Testing update on:
```
macOS 10.14.3 18D109
Xcode 10.1 10B61 

```
VLC builds and runs as expected against a number of difference audio and video formats. Thanks for your effort in bringing this up-to-date.  I know it's a PITA.

However, when trying to build VLC2 (which should error out with a message that VLC2 is obsolete and replaced by VLC),  the port skips the fetch, checksum and extract phases as expected but then error out trying to patch files in the resulting empty work directory.

```
--->  Applying buildfix-package.mak.patch
DEBUG: Environment: 
CC_PRINT_OPTIONS='YES'
CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/_opt_github.com_macports_macports-ports_multimedia_VLC2/VLC2/work/.CC_PRINT_OPTIONS'
CPATH='/opt/local/include'
LIBRARY_PATH='/opt/local/lib'
MACOSX_DEPLOYMENT_TARGET='10.14'
Executing:  cd "/opt/local/var/macports/build/_opt_github.com_macports_macports-ports_multimedia_VLC2/VLC2/work/vlc-2.2.8" && /usr/bin/patch -p0 < '/opt/github.com/macports/macports-ports/multimedia/VLC2/files/buildfix-package.mak.patch'
DEBUG: system:  cd "/opt/local/var/macports/build/_opt_github.com_macports_macports-ports_multimedia_VLC2/VLC2/work/vlc-2.2.8" && /usr/bin/patch -p0 < '/opt/github.com/macports/macports-ports/multimedia/VLC2/files/buildfix-package.mak.patch'
can't find file to patch at input line 5

```

The problem is the obsolete check doesn't occur until the configure phase and your obsolete logic
```
if {${subport} eq ${name}} {
    if {${os.major} > 13} {
        replaced_by     VLC
        PortGroup       obsolete 1.0
    }
    conflicts           lib${name} libVLC
}

# VLC-2.1 and later are x86_64-only: https://trac.videolan.org/vlc/ticket/8161
universal_variant       no
supported_archs         x86_64

##
###################  ports VLC and libVLC  ###################
##
if {(${subport} eq ${name}) || (${subport} eq "lib${name}")} {
    version             2.2.8
    license             GPL-2+

```
allows execution to fall through to the next if statement and set patchfiles before then.  To work as expected, these sections should be mutually exclusive so that neither patchfiles nor dependencies are set in the obsolete case.

**Comment by RJVB** [comment]
> VLC builds and runs as expected against a number of difference audio and video formats.

Thanks for testing, but you weren't the first :) I've been able to test libVLC myself, but couldn't have reached this stage without the constructive feedback from a few users.

> allows execution to fall through to the next if statement and set patchfiles before then.  To work as expected, these sections should be mutually exclusive so that neither patchfiles nor dependencies are set in the obsolete case.

Not certain if I understand this. Normally you're not supposed to use an if/else construct to get a port to be replaced_by another, I think? 
I did notice in another case that I had to put the replaced_by/obsolete pair at the bottom of the Portfile. I'll try to experiment with different options tomorrow.

**Comment by dbevans** [comment]
Putting at the bottom would probably work if you blank out portfiles and any dependencies at that point.  Otherwise, it may still try to patch and download dependencies.  See mlt-qt5 for a case
where there aren't patches but the port installs dependencies before announcing itself obsolete.

**Comment by RJVB** [comment]
Given the organisation of the Portfiles (which I really didn't feel like overhauling) I went for the easier solution: just override the `patch{}` phase. No surprises that way.

Sadly one cannot override pre- and post-phases so I had to make those conditional on `replaced_by` not being set.

The whole obsolete PG is a bit of a hack anyway, one which could have gotten a proper implementation in "base" long ago...

**Comment by dbevans** [comment]
Well, that fixed my obsolete issue and the VLC port still works so will go ahead and commit.  Thanks again for updating this port to the current version.

**Comment by RJVB** [comment]
>Well, that fixed my obsolete issue and the VLC port still works so will go ahead and commit.  Thanks again for updating this port to the current version.

I just wish I could say it was fun (nothing about this port is...) ;)

**Pull request merged**
