### PR TITLE
Use extract.mkdir yes

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

Use `extract.mkdir yes` rather than making the directory manually.

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

### CODE REVIEW

**Comment by ryandesign** [comment]
> Port passogva fail on xcode9.3.

Fixed: 9f40b9339e149ec1e9be9039861577a91155783d

**Comment by pmetzger** [comment]
@ryandesign Could you push a non-conflicting version?

**Comment by ryandesign** [comment]
> Port tex-beamerposter's dependencies fail on xcode9.3. Log
> Port brs fail on xcode9.3. Log

Travis is broken: `Could not resolve host`

**Comment by pmetzger** [comment]
@ryandesign Travis is broken far too often. The point of a CI system is to give us confidence that what we're committing works. I continue to feel that we may want to bring the Travis functionality in-house, but who would supply the machines or the manpower to do it is a big question mark.

**Pull request merged**
