### PR TITLE
pure-gen: Update to version 0.25, use PG haskell_cabal, Bugfix

### PR DESCRIPTION
**Pull request by essandess**
#### Description

Depends upon #16154

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6 21G115 x86_64
Xcode 14.0 14A309

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by essandess** [comment]
It appears that something is messed up with the `pure` binary on macOS 11:
```sh
dyld: Library not loaded: /opt/local/lib/libffi.7.dylib
    Referenced from: /opt/local/bin/pure
    Reason: image not found
```

**Comment by kencu** [comment]
```
% port contents libffi | grep dylib
  /opt/local/lib/libffi.8.dylib
  /opt/local/lib/libffi.dylib

```

**Comment by ryandesign** [comment]
I'm fixing pure by revbumping it shortly.

**Comment by kencu** [comment]
probably got missed because it doesn’t list a dep on libffi

**Comment by ryandesign** [comment]
Yup I'm fixing that too.

**Comment by mascguy** [comment]
Ryan's fixed were made (per commit https://github.com/macports/macports-ports/commit/78be9fb3c8ab0ecb0747dd185d91121f2013a0a9), so we're good-to-go.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
