### PR TITLE
podman-compose: new port

### PR DESCRIPTION
**Pull request by judaew**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.6 20G165 x86_64
Xcode 12.5.1 12E507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
is this port intended to (or can) be used as a library and imported in Python or as a "stand-alone" program for which it doesn't really matter which Python version is used? If it's the latter, than this should likely be a port that doesn't have the `py-` prefix - right?

**Comment by judaew** [comment]
Sure, I agree with you.

**Comment by reneeotten** [comment]
> Sure, I agree with you.

then let's not bother with `variants` either, just pick which one you want to use...

**Comment by judaew** [comment]
Well, done.

**Pull request merged**
