### PR TITLE
icu: update to 73.1

### PR DESCRIPTION
**Pull request by catap**
#### Description

An update ICU and revbump all of it dependencies.

I haven't tried to build all dependencies, but I'm living on `icu-devel` port which was updated to 73.1 a few weeks ago.

###### Type(s)

- [x] enhancement

###### Tested on

macOS 12.6.3 21G419 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
rebased to solve conflict with qt6

**Review by mascguy — APPROVED** [review]
Haven't had a chance to test with this, but definitely fine with it!

Anyone else?

**Comment by catap** [comment]
One more rebase to solve conflicts in `darktable` and `darktable-devel`.

**Comment by mascguy** [comment]
We'll wait another day or so, to give maintainers a chance to review. (And the buildbots are still catching up with various updates over the past week.)

Assuming there aren't any objections, let's plan to merge Friday evening, after 8:00pm EST.

**Comment by mascguy** [comment]
The buildbots are mostly idle at this point, apart from 10.12 and 10.14. So this is as good a time as any. Merging.

**Comment by catap** [comment]
Thanks!

**Pull request merged**
