### PR TITLE
pandoc: update to 2.14.0.3

### PR DESCRIPTION
**Pull request by szhorvat**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.6 18G9216 x86_64
Xcode 11.3.1 11C504

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by szhorvat** [comment]
This will not compile with ccache enabled (i.e. `configureccache yes` in `macports.conf`), so I added `configure.ccache no`.

It is possible that this problem is not specific to this port, and should instead be fixed in the `haskell_stack` portgroup. Someone should investigate this. Ping @essandess

**Comment by szhorvat** [comment]
https://trac.macports.org/ticket/60571

**Comment by essandess** [comment]
> ###### Tested on
> macOS 10.14.6 18G9216 x86_64
> Xcode 11.3.1 11C504

I do not see this issue on macOS 11—`pandoc` version 2.14.0.3 builds successfully with ccache.

macOS 11.4 20F71 x86_64
Xcode 12.5.1 12E507

I see that @cjones051073 disabled ccache in port `stack`: https://github.com/macports/macports-ports/commit/ceab9e1424be3914f784d3d0eba53cd4d3a917db#diff-cf93ab709a7a1e022a95a8b2fb855770e3bc2586c0b27dffbf982f668402fc9a

I honestly don't have enough background knowledge of ccache or MacPorts to recommend whether 

```
configure.ccache    no
```

be included in the portgroup `haskell_stack` for all such builds.

I'll defer to however @cjones051073, @neverpanic, @ryandesign wish to address this.

**Comment by cjones051073** [comment]
Its possible its a similar reason, but I would have to investigate to be sure. Lets merge then investigate later.

**Pull request merged**
