### PR TITLE
Update Xft2 to 2.3.6

### PR DESCRIPTION
**Pull request by ThomasDickey**
#### Description

New release:
- update documentation
- add support for BGRA glyphs and scaling
- add option for tracking glyph memory usage, unloading oldest

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 12.6 21G115 x86_64
Xcode 14.0 14A309

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ThomasDickey** [comment]
That "6 commits" puzzles me, since I merged upstream to master, and branched from master.

**Comment by ryandesign** [comment]
I guess you don't want to "merge"; you want to "rebase".

**Comment by ThomasDickey** [comment]
I'll see how that goes :-)

**Comment by ThomasDickey** [comment]
will redo this...

**Pull request closed without merging**
