### PR TITLE
transmission: update to 4.0.1

### PR DESCRIPTION
**Pull request by wwalexander**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.2.1 22D68 arm64
Xcode 14.1 14B47b

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] checked your Portfile with `port lint --nitpick`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?
- [X] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by kurthindenburg** [comment]
Thanks, I was wondering if we should keep version 3 around - maybe as a variant or sub-port.

**Comment by kurthindenburg** [comment]
I'm still looking at this - thanks

**Comment by kurthindenburg** [comment]
typically we want to disable sparkle; also I need to check that the prefix doesn't need corrected (I would assume it does).  Please don't merge this w/o my consent.

**Comment by wwalexander** [comment]
> typically we want to disable sparkle; also I need to check that the prefix doesn't need corrected (I would assume it does). Please don't merge this w/o my consent.

Sorry, may have been overzealous removing Chesterton's fence there! Makes sense, will wait for you to take a deeper look.

**Comment by kurthindenburg** [comment]
closing this as someone else updated it

**Pull request closed without merging**
