### PR TITLE
claws-mail: update to version 3.17.4, configuration, dependencies

### PR DESCRIPTION
**Pull request by dbevans**
This PR can be seen as a temporary (hopefully more palatible) alternative to previous PR3527 that
completely disabled building of the fancy plugin due to the dependency on deprecated webkit-gtk.

By default, this new PR disables plugins fancy and new litehtml_viewer (which requires Google's
libgumbo not yet ported to MacPorts). The improper dependency on webkit2-gtk has been removed
and a +fancy variant is added which correctly adds the dependency on webkit-gtk and enables the
build of the fancy plugin.  This eliminates the previously reported behavior of opportunisticaly building
the fancy plugin if webgit-gtk happened to be installed and requires the user to make a conscious decision
to build the plugin.

Note that progress is being made (slowly) on the upstream gtk3 branch which not only updates claws-mail to gtk3
but ports the fancy plugin to webkit2-gtk3.

See https://trac.macports.org/ticket/52408
See https://github.com/macports/macports-ports/pull/3527

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [x] partial security fix

###### Tested on

macOS 10.15 19A546d (public beta 7)
Xcode 11.0 11M392r (public beta 7)

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
This looks good to me. Have you tried adding a libgumbo port and it proved too hard, or is that something you haven't tried yet? If it's easy I'd like us to add it.

**Comment by pmetzger** [comment]
BTW, I'm having a quick go at packaging https://github.com/google/gumbo-parser (presuming that's what is needed.)

**Comment by pmetzger** [comment]
I've now committed a port of gumbo-parser.

**Comment by pmetzger** [comment]
I tried doing a naive update to add the litehtml_viewer but it seems to somehow fail to configure it. You want to have a wack at it, @dbevans? (It's also, very weirdly, failing to find the python 3.7 shared libraries.)

**Comment by dbevans** [comment]
> I tried doing a naive update to add the litehtml_viewer but it seems to somehow fail to configure it. You want to have a wack at it, @dbevans? (It's also, very weirdly, failing to find the python 3.7 shared libraries.)

Will take a look.

**Comment by pmetzger** [comment]
@dbevans Did you ever get a chance to poke at it?

**Pull request merged**
