### PR TITLE
py-tensor*1: new ports copied from version 1.15.x of py-tensor*

### PR DESCRIPTION
**Pull request by blair**
See: https://trac.macports.org/ticket/59179

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.6 17G8037
Xcode 10.1 10B61 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by blair** [comment]
The only differences on the new ports are

1. trimming trailing whitespace
1. adding a trailing 1 to the port name
1. updating the livecheck regex

**Comment by cjones051073** [comment]
Any idea what is wrong with the travis/azure builds ?

**Comment by cjones051073** [comment]
LGTM.

**Comment by cjones051073** [comment]
build failures probably not relevant. Lets see what buildbots do.

**Pull request merged**
