### PR TITLE
R-V8: new R package; v8-8.3: new port in lang

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

A brief on the status of V8 itself:

– Confirmed to build reliably for x86_64; confirmed to be functional on x86_64.

– Confirmed to build on aarch64.
– Builds for `ppc`, but needs further work on it.

While my aim with this is to support PPC, I guess, merging it first (given that Intel is good) will make it easier to debug and fix powerpc installation. Then, provided this works, we can get NodeJS built against external V8; this version should support NodeJS 14.

`R-V8`: _tests pass on x86_64;_ on ppc and aarch64 it fails to build at the moment.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

macOS 10.6.8 Server
Xcode 4.2

macOS 14
Xcode 15

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
macos-12 `patch` is unable to use paths with `..`, facepalm. Okay, will change that.

**Comment by barracuda156** [comment]
I will test now on 10.6.8/x86_64 to confirm if it builds and is actually usable.

**Comment by barracuda156** [comment]
Testing this against `R-V8`, I can confirm this works nicely on 10.6.8 Intel:
```
Executing:  cd "/opt/local/var/macports/build/_opt_SLports_R_R-V8/R-V8/work/V8" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_opt_SLports_R_R-V8/R-V8/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library --install-tests 
* installing *source* package ‘V8’ ...
file ‘configure’ has the wrong MD5 checksum
** using staged installation
Found C++17 compiler: /opt/local/bin/clang++-mp-11
Using Macports installation of V8!
Using CXXCPP=/opt/local/bin/clang++-mp-11 -std=gnu++17 -E
Using PKG_CFLAGS=-I/opt/local/libexec/v8-8.3/include
Using PKG_LIBS=-L/opt/local/libexec/v8-8.3/lib -lv8_base_without_compiler -lv8_compiler -lv8_initializers -lv8_inspector -lv8_libbase -lv8_libplatform -lv8_libsampler -lv8_snapshot
Running feature test for pointer compression...
Pointer compression not needed
** libs
using C++ compiler: ‘clang version 11.1.0’
using C++17
Warning in system2("xcrun", "--show-sdk-path", TRUE, TRUE) :
  running command ''xcrun' --show-sdk-path 2>&1' had status 64
using SDK: ‘NA’‘NA’‘NA’‘NA’‘NA’‘NA’
rm -f V8.so RcppExports.o bindings.o
/opt/local/bin/clang++-mp-11 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/opt/local/libexec/v8-8.3/include -DV8_ENABLE_CHECKS -I'/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/Rcpp/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include    -fPIC  -pipe -Os -stdlib=libc++ -arch x86_64  -c RcppExports.cpp -o RcppExports.o
/opt/local/bin/clang++-mp-11 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/opt/local/libexec/v8-8.3/include -DV8_ENABLE_CHECKS -I'/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/Rcpp/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include    -fPIC  -pipe -Os -stdlib=libc++ -arch x86_64  -c bindings.cpp -o bindings.o
/opt/local/bin/clang++-mp-11 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/local/Library/Frameworks/R.framework/Resources/lib -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/local/lib/libgcc -L/opt/local/lib -lMacportsLegacySupport -arch x86_64 -o V8.so RcppExports.o bindings.o -L/opt/local/libexec/v8-8.3/lib -lv8_base_without_compiler -lv8_compiler -lv8_initializers -lv8_inspector -lv8_libbase -lv8_libplatform -lv8_libsampler -lv8_snapshot -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /opt/local/var/macports/build/_opt_SLports_R_R-V8/R-V8/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/00LOCK-V8/00new/V8/libs
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (V8)
```

```
--->  Testing R-V8
* using log directory ‘/opt/local/var/macports/build/_opt_SLports_R_R-V8/R-V8/work/V8/V8.Rcheck’
* using R version 4.3.2 (2023-10-31)
* using platform: x86_64-apple-darwin10.8.0 (64-bit)
* R was compiled by
    clang version 11.1.0
    GNU Fortran (MacPorts gcc12 12.3.0_3+stdlib_flag) 12.3.0
* running under: OS X Snow Leopard 10.6.8
* using session charset: UTF-8
* using option ‘--ignore-vignettes’
* checking for file ‘V8/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘V8’ version ‘4.4.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘V8’ can be installed ... OK
* used C++ compiler: ‘clang version 11.1.0’
* used SDK: ‘NA’‘NA’‘NA’‘NA’‘NA’‘NA’
* checking C++ specification ... OK
  Not all R platforms support C++17
* checking installed package size ... NOTE
  installed size is 19.1Mb
  sub-directories of 1Mb or more:
    doc    1.8Mb
    libs  17.1Mb
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking startup messages can be suppressed ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in shell scripts ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking compiled code ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... SKIPPED
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘engine.R’
  Comparing ‘engine.Rout’ to ‘engine.Rout.save’ ...4d3
< Using V8 engine 8.3.110.13
  Running ‘testthat.R’
 OK
```

**Comment by barracuda156** [comment]
I have fixed it for aarch64, let me update the PR.

**Comment by barracuda156** [comment]
@herbygillot I think we can merge this. Intel is all good, which is what the most people use, for ppc – build works, which never did earlier, a good start. On aarch64 both ports build; an error in tests of R-V8 may well be due to unrelated reasons (our R has a broken R BATCH, for example).

**Comment by herbygillot** [comment]
> @herbygillot I think we can merge this. Intel is all good, which is what the most people use, for ppc – build works, which never did earlier, a good start. On aarch64 both ports build; an error in tests of R-V8 may well be due to unrelated reasons (our R has a broken R BATCH, for example).

Acknowledged & merged.

**Pull request merged**
