### PR TITLE
Update to spyder and its dependencies

### PR DESCRIPTION
**Pull request by jsalort**
#### Description

This PR enables Python 3.10 for Spyder and its dependencies.
It was also necessary to bump ipykernel and jupyter_client versions to match spyder requirements.

* add py310 to py-spyder, py-applaunchservices, py-helpdev, py-ipykernel, py-jupyter_client, py-libsass, py-pyls-spyder, py-python-lsp-black, py-python-lsp-server, py-qdarkstyle, py-qtsass, py-rtree, py-spyder-kernels and py-spyder
* update py-ipykernel to 6.6.1
* update py-jupyter_client to 7.1.0

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.1 21C52 arm64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
thanks for the PR @jsalort ! Last time I checked there were quite a few dependencies of Spyder (mainly related to `python-lsp-server` ) that didn't support Python 3.10 yet (i.e., the test-suite failed or upstream explicitly stated that it wasn't supported yet). But presumably it now all works for you locally - right? I am happy to give it a test-run (hopefully in the near future) and if everything indeed works as intended we can add a subport for Python 3.10. 

However, the CI fails with an issue due to `py-ipykernel` port that you also changed here - can you please take a look at that?

**Comment by jsalort** [comment]
> thanks for the PR @jsalort ! Last time I checked there were quite a few dependencies of Spyder (mainly related to `python-lsp-server` ) that didn't support Python 3.10 yet (i.e., the test-suite failed or upstream explicitly stated that it wasn't supported yet). But presumably it now all works for you locally - right? I am happy to give it a test-run (hopefully in the near future) and if everything indeed works as intended we can add a subport for Python 3.10.
> 
> However, the CI fails with an issue due to `py-ipykernel` port that you also changed here - can you please take a look at that?
> 
> [edit: you should ideally have one commit for each Portfile that you change, unless it's really only adding subport for Python 3.10, then you can probably combine them. Also, we don't want to have merge commits... but that's all something we can deal with once the decision is made to in principle merge the PR].

Spyder works for me, as far as I can tell.
So does the python-lsp-server test suites:

```bash
============================= test session starts ==============================
platform darwin -- Python 3.10.2, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /Users/jsalort/python-lsp-server, configfile: setup.cfg, testpaths: test
plugins: flaky-3.7.0, cov-3.0.0
collected 134 items                                                            

test/test_document.py .........                                          [  6%]
test/test_language_server.py ss..                                        [  9%]
test/test_uris.py ...sss..ss..                                           [ 18%]
test/test_utils.py ......                                                [ 23%]
test/test_workspace.py .................                                 [ 35%]
test/plugins/test_autopep8_format.py ....                                [ 38%]
test/plugins/test_completion.py ............................s.           [ 61%]
test/plugins/test_definitions.py ....                                    [ 64%]
test/plugins/test_flake8_lint.py ......                                  [ 68%]
test/plugins/test_folding.py ..                                          [ 70%]
test/plugins/test_highlight.py ..                                        [ 71%]
test/plugins/test_hover.py ...                                           [ 73%]
test/plugins/test_jedi_rename.py .                                       [ 74%]
test/plugins/test_mccabe_lint.py ..                                      [ 76%]
test/plugins/test_pycodestyle_lint.py ..                                 [ 77%]
test/plugins/test_pydocstyle_lint.py ....                                [ 80%]
test/plugins/test_pyflakes_lint.py ....                                  [ 83%]
test/plugins/test_pylint_lint.py ..s...                                  [ 88%]
test/plugins/test_references.py ..                                       [ 89%]
test/plugins/test_rope_rename.py .                                       [ 90%]
test/plugins/test_signature.py ......                                    [ 94%]
test/plugins/test_symbols.py ..s                                         [ 97%]
test/plugins/test_yapf_format.py ....                                    [100%]

[...]

================= 124 passed, 10 skipped, 7 warnings in 31.79s =================
```

They mention a PR about python 3.10 compatibility in their changelog for version 1.3.3.

I will try to look into the CI failure.

I am sorry for the merge commit. But the time I realised that I was behind upstream, I didn't know how to squash since the PR was already created.

**Comment by reneeotten** [comment]
> Spyder works for me, as far as I can tell. So does the python-lsp-server test suites:

okay, I will take a look
 
> I am sorry for the merge commit. But the time I realised that I was behind upstream, I didn't know how to squash since the PR was already created.

Ideally you should make changes in a branch and not on `master` as is described on the [Wiki](https://trac.macports.org/wiki/WorkingWithGit#branch) and elsewhere on the internet. Secondly, when getting upstream changes you should do a `rebase` instead of `merge`; you can likely do that in one step with `git pull --rebase` or first `fetch` and then `rebase`, which is what I normally do.

**Comment by reneeotten** [comment]
`py-ipython` in MacPorts was update to 8.0.1 in 9d150ca0bd5066921783b1ece47737056c027e18 and that's now too new according to Spyder... The strict pinning of dependencies by upstream is quite annoying; additionally Spyder released a new minor version - so I'll have to see how to resolve this... first of all for the current versions and then possibly adding Python 3.10.

**Comment by someuser12** [comment]
One way to deal with this last issue, I mean having a working spyder at least for Python < 3.10:

-  update py-jupyter_client (see https://github.com/macports/macports-ports/pull/13756)
-  create a port like py-ipython7 to be able to install ipython < 8.0.0 as requested by spyder (see attached Portfile proposal),
-  modify py-ipykernel's Portfile to depend on either py-ipython or py-ipython7, and by the way update to 6.7.0 (see attached diff proposal),
-  modify spyder's Portfile to depend on py-ipython7.
[Portfile_for_py-ipython7.txt](https://github.com/macports/macports-ports/files/7921690/Portfile_for_py-ipython7.txt)
[Portfile_for_py-ipykernel.diff.txt](https://github.com/macports/macports-ports/files/7921696/Portfile_for_py-ipykernel.diff.txt)

I tried it on my machine (upgrading py-jupyter_client, deactivating py-ipython, installing py-ipython7, upgrading py-ipykernel, without modifying the Portfile of spyder yet) and was able to launch spyder-3.8 again.

If this is a suitable way, I can try to submit pull requests. Thanks anyway for your efforts.

**Comment by reneeotten** [comment]
> One way to deal with this last issue, I mean having a working spyder at least for Python < 3.10:
> 
>     * update py-jupyter_client (see [py-jupyter_client: update to 7.1.2 #13756](https://github.com/macports/macports-ports/pull/13756))
> 
>     * create a port like py-ipython7 to be able to install ipython < 8.0.0 as requested by spyder (see attached Portfile proposal),
> 
>     * modify py-ipykernel's Portfile to depend on either py-ipython or py-ipython7, and by the way update to 6.7.0 (see attached diff proposal),
> 
>     * modify spyder's Portfile to depend on py-ipython7.
>       [Portfile_for_py-ipython7.txt](https://github.com/macports/macports-ports/files/7921690/Portfile_for_py-ipython7.txt)
>       [Portfile_for_py-ipykernel.diff.txt](https://github.com/macports/macports-ports/files/7921696/Portfile_for_py-ipykernel.diff.txt)
> 
> 
> I tried it on my machine (upgrading py-jupyter_client, deactivating py-ipython, installing py-ipython7, upgrading py-ipykernel, without modifying the Portfile of spyder yet) and was able to launch spyder-3.8 again.
> 
> If this is a suitable way, I can try to submit pull requests. Thanks anyway for your efforts.

Yes, there are probably many ways of going about this. We typically don't want to maintain multiple versions of a port for the obvious reasons, so I would not want to create a IPython 7 port. As I said I will look into it.

**Comment by jsalort** [comment]
The build bot fails to install py37-spyder, but I am not able to reproduce the problem. py37-spyder installs fine locally for me. So I don't know how to fix the issue.

**Comment by reneeotten** [comment]
@jsalort thanks for the PR and the legwork for these changes. I've verified that Python 3.10 indeeds seems to work for Spyder, at least the test-suite for `py-python-lsp-server` passes as you pointed out and a day of using Spyder with Python 3.10 didn't result in crashed/failures... so let's hope for the best. I did make a few changes to the `py-ipykernel` and `py-jupyter_client` Portfiles as the dependencies were not all correct for the latest upstream versions in this PR. 

Since you did not make the PR from a "branch" but directly from the `master` branch in your fork, I didn't push my changes to your fork. Instead I took this PR, made the changes and committed them directly, still giving you the credit for the changes of course. 

So I'll close this PR now as all your suggested changes + a few more have been incorporated. Hopefully this all works now as intended - give it a try and feel free to open a Trac ticket if you run into trouble!

**Pull request closed without merging**
