### PR TITLE
speedtest-cli: upgrade to python311

### PR DESCRIPTION
**Pull request by jrabinow**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 13.1 22C65 arm64
Xcode 14.1 14B47b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by kurthindenburg** [comment]
Is this a bit early or are other ports defaulting to 3.11?

**Comment by jrabinow** [comment]
python3.11 is now the [default in macports](https://github.com/macports/macports-ports/commit/ab2f9e7fbdf613ef9b10fc05e99074fd573b6df5).

So far, I'm only seeing the following ports with python3.11 as default
- graphtage
- pyupgrade
- codespell
- meson
- nvchecker
- youtube-dl

so maybe you'd feel more comfortable waiting a bit?

**Comment by kurthindenburg** [comment]
It might be a little early but I'm fine with it.  Thanks.

**Comment by ryandesign** [comment]
You forgot to increase the revision, which caused https://trac.macports.org/ticket/67902.

**Comment by jrabinow** [comment]
@ryandesign apologies. I see it's already fixed https://github.com/macports/macports-ports/commit/e401f8b5a2746807bab42609de110c1f56be0dc5, thanks for that

**Pull request merged**
