### PR TITLE
asciidoc @10.2.0 Warning: invalid escape sequence '\S'

### PR DESCRIPTION
**Pull request by christophecvr**
asciidoc: Update to 10.2.1

Closes: https://trac.macports.org/ticket/70039
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.7
Xcode 11.5 / Command Line Tools 11.5.0
Compiler Apple clang 11.0.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
I assume you meant macOS 10.15.7?

When we merge this (or beforehand by force-pushing if you wish) we should reword the commit message to remove the square brackets around the URL.

**Comment by ryandesign** [comment]
The first line of the commit message should also be reworded to say "asciidoc: Update to 10.2.1"

**Comment by christophecvr** [comment]
> I assume you meant macOS 10.15.7?
> 
> When we merge this (or beforehand by force-pushing if you wish) we should reword the commit message to remove the square brackets around the URL.

Yes corrected to 10.15.7 

The commit message self can't be edited, but I updated the message here
First line update to asciidoc: to 10.2.1
and the link here Fixes : [...] is removed

Solves: link set instead.

**Comment by ryandesign** [comment]
Changing the text of the PR isn't relevant. The commit message can be edited. Then you force push. Or we can edit the message when we merge the PR.

**Comment by christophecvr** [comment]
@ryandesign 
Would this be the perfect commit initial message created with vi editor perfect ?
Since I did not commit the change to my personal work branch in my github fork of macports.
I took the opportunity to test it.

For just this last patch update asciidoc: to 10.2.1
[example](https://github.com/christophecvr/macports-ports/commit/add0c3de8f49542a101fdb4349687146a4fc3b78)

**Comment by markemer** [comment]
Should we recommend `asciidoctor` as that has replaced this as Asciidoc's reference implementation?

**Comment by christophecvr** [comment]
> Should we recommend `asciidoctor` as that has replaced this as Asciidoc's reference implementation?

This is asciidoc-py  not asciidocter . asciidocter also a converter but is another utility. aciidoctor has also a port.

**Comment by christophecvr** [comment]
> Changing the text of the PR isn't relevant. The commit message can be edited. Then you force push. Or we can edit the message when we merge the PR.

Ok sorry forgot about the git amend followed by forced push. Is just done now

**Review by neverpanic — APPROVED** [review]

**Pull request merged**
