### PR TITLE
pcsc-tools: update to 1.5.2

### PR DESCRIPTION
**Pull request by lbschenkel**
Remove Makefile patch, use configure script.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.2 17C205
Xcode 9.2 9C40b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by lbschenkel** [comment]
Since this was a slightly bigger change than the usual version bump, I'm opening a PR instead and e-mailing the link to the maintainer.

**Comment by pmetzger** [comment]
I presume we're now past the 72 hour timeout for the maintainer?

**Comment by pmetzger** [comment]
Yes, we seem to be. I'm going to merge.

**Comment by lbschenkel** [comment]
Thanks

**Pull request merged**
