### PR TITLE
R: updates to packages – 3

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

_Nothing will be added here._

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@reneeotten @herbygillot Why do we have this broken?
```
--->  Fetching archive for R-xml2
DEBUG: Executing proc-pre-org.macports.archivefetch-archivefetch-0
DEBUG: Executing org.macports.archivefetch (R-xml2)
DEBUG: euid/egid changed to: 0/0
DEBUG: chowned /opt/local/var/macports/incoming to macports
DEBUG: euid/egid changed to: 502/501
--->  R-xml2-1.3.5_0.darwin_22.x86_64.tbz2 doesn't seem to exist in /opt/local/var/macports/incoming/verified
--->  Attempting to fetch R-xml2-1.3.5_0.darwin_22.x86_64.tbz2 from https://packages.macports.org/R-xml2
--->  Attempting to fetch R-xml2-1.3.5_0.darwin_22.x86_64.tbz2.rmd160 from https://packages.macports.org/R-xml2
DEBUG: The requested URL returned error: 503
    while executing
"curl fetch --effective-url effectiveURL {*}$fetch_options ${file_url}.rmd160 $signature"
Error: Failed to archivefetch R-xml2: Failed to fetch signature for archive: The requested URL returned error: 503
DEBUG: Error code: NONE
DEBUG: Backtrace: Failed to fetch signature for archive: The requested URL returned error: 503
    while executing
"portarchivefetch::fetchfiles"
    (procedure "portarchivefetch::archivefetch_main" line 5)
    invoked from within
"$procedure $targetname"
Error: See /opt/local/var/macports/logs/_Users_runner_work_macports-ports_macports-ports_ports_R_R-xml2/R-xml2/main.log for details.
Build of dependency 'R-xml2' with variants '' failed, aborting.
```
This is just a dependency, unmodified in this PR. And many now fail.

**Comment by barracuda156** [comment]
We are still stuck with ridiculous random failures:
```
  Building 7 dependencies of R-callr:
  Building dependency (1 of 7) 'gperf' with variants '' ... [FAIL]
```

**Comment by barracuda156** [comment]
@jmroot Could you please take a look? I am not exactly sure what breaks this, but errors now are clearly random (unchanged PR fails with different ports failing), again multiple errors with untouched dependencies, including those unrelated to `R`.

**Comment by jmroot** [comment]
Well the packages server is clearly giving 503 errors (Service Unavailable) intermittently. No idea why.

**Comment by barracuda156** [comment]
@herbygillot @reneeotten And this one ready.

**Pull request merged**
