### PR TITLE
openssl3: Update to 3.4.0

### PR DESCRIPTION
**Pull request by neverpanic**
#### Description

```
38dc87dbf30 openss[lh], freeradius, p5-net-ssleay: revbump
487f204a127 openssl3: Update to 3.4.0
```

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 14.7 23H124 arm64
Xcode 16.0 16A242d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test -- +test +fips`?
- [x] tried a full install with `sudo port -vs install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@neverpanic I am back to my hardware (both powerpc and x86) on 27 Oct. I should be able to run the build same day, but not prior to that.
So if there are security fixes here, just go ahead, and if anything gets broken, we deal with that in a few days. Otherwise I verify builds on 27th.

**Comment by neverpanic** [comment]
To my knowledge, there are no security fixes in there, so I guess I can hold off for a few days.

**Comment by barracuda156** [comment]
@neverpanic Thank you.
BTW, do we need to revbump `R-openssl` here?

**Comment by neverpanic** [comment]
@barracuda156 I don't know. If it dynamically links against OpenSSL and doesn't do a check comparing the openssl version at build time with the openssl version at runtime, I don't think so.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@neverpanic I'll take a look later too after I try to resolve a trouble with libomp.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@neverpanic on SL no longer builds with the system compiler:

```
make[1]: Entering directory `/opt/local/var/macports/build/_Users_strega_macports-ports_devel_openssl3/openssl3/work/openssl-3.4.0'
/usr/bin/llvm-gcc-4.2 -fPIC -arch x86_64 -pipe -Os -arch x86_64 -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/opt/local/libexec/openssl3/etc/openssl\"" -DENGINESDIR="\"/opt/local/libexec/openssl3/lib/engines-3\"" -DMODULESDIR="\"/opt/local/libexec/openssl3/lib/ossl-modules\"" -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -I/opt/local/include -c -o crypto/aes/libcrypto-lib-aes-x86_64.o crypto/aes/aes-x86_64.s
crypto/aes/aes-x86_64.s:2642:Unknown pseudo-op: .previous
```

Perhaps instead of blocking the use of AES intrinsics we should try building with [`clang-11-bootstrap`](https://ports.macports.org/port/clang-11-bootstrap/details/) on legacy systems.

**Comment by barracuda156** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou If that is done, please make sure it is conditional on the arch being x86, since that is both unneeded (those are Intel-specific SIMD) and breaking (clang does not work for ppc) on Rosetta.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@barracuda156 I have successfully compiled using this hack.
In addition to being limited to x86, it should only apply to pre-Mojave versions. I think Clemens will add this to PR, after which I will try to fix the [libressl build](https://trac.macports.org/ticket/69490) again.

**Comment by neverpanic** [comment]
Can you elaborate what I need to change? I'm not familiar with building with clang-11-bootstrap. Alternatively, I'd welcome a patch against my branch.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@neverpanic I think the following should be added after line 83:

```
if {${os.platform} eq "darwin" && ${os.major} < 18} {
    if {${configure.build_arch} eq "x86_64"} {
        depends_build-append port:clang-11-bootstrap
        configure.cc ${prefix}/libexec/clang-11-bootstrap/bin/clang
        configure.cxx ${prefix}/libexec/clang-11-bootstrap/bin/clang++
    }
}
```

**Comment by barracuda156** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou What about `i386`?

**Comment by barracuda156** [comment]
@neverpanic At least on Rosetta 3.4.0 builds fine:
```
$ port -v installed openssl3 | grep active
  openssl3 @3.4.0_0 (active) requested_variants='' platform='darwin 10' archs='ppc' date='2024-10-27T15:59:49+0800'
```
So I think powerpc is good.

**Comment by neverpanic** [comment]
> @neverpanic I think the following should be added after line 83:
> 
> ```
> if {${os.platform} eq "darwin" && ${os.major} < 18} {
>     if {${configure.build_arch} eq "x86_64"} {
>         depends_build-append port:clang-11-bootstrap
>         configure.cc ${prefix}/libexec/clang-11-bootstrap/bin/clang
>         configure.cxx ${prefix}/libexec/clang-11-bootstrap/bin/clang++
>     }
> }
> ```

Done, also for i386.

**Comment by barracuda156** [comment]
@neverpanic Just in case, I did not test i386 build.

I will verify a native PowerPC build today in a couple of hours, but pretty sure it is fine, given Rosetta one worked.

**Comment by neverpanic** [comment]
> @neverpanic @aeiouaeiouaeiouaeiouaeiouaeiou I just thought that requiring clang gonna break universal builds on old OS (not sure if clang11-bootstrap builds on 10.4 i386, but surely it won't build on 10.5.8 ppc). While this is not a typical case, perhaps, it is a legitimate one (and so far building `openssl3 +universal` worked, AFAIK, at least on 10.5.8 and 10.6.8 Rosetta). Could this be avoided with some simple change to the portfile logic?

As always for these operating systems, patches welcome. Tested ones, even more.

**Comment by barracuda156** [comment]
@neverpanic I did not mean to do anything with the openssl code, just to avoid breaking universal builds via adjusting portfile logic.
This is not something of a great importance to me personally, just a consideration. It is not a stopper for merging this PR, of course.

**Comment by barracuda156** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou Is it possible to disable AES completely for the case of physical cpu being powerpc? That should fix universal builds which include i386 but done on powerpc.

I.e. `platform darwin powerpc` case.

**Comment by barracuda156** [comment]
@neverpanic @aeiouaeiouaeiouaeiouaeiouaeiou Perhaps this is uncontroversial?
```
if {${os.platform} eq "darwin" && ${os.major} < 18 && ${os.arch} ne "powerpc"} {
    if {${configure.build_arch} in {"i386" "x86_64"}} {
        depends_build-append port:clang-11-bootstrap
        configure.cc ${prefix}/libexec/clang-11-bootstrap/bin/clang
        configure.cxx ${prefix}/libexec/clang-11-bootstrap/bin/clang++
    }
}
```

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@barracuda156 we can add a fix for PowerPC in a separate PR, for now I want to see how this current fix works on buildbots.

**Comment by barracuda156** [comment]
> @barracuda156 we can add a fix for PowerPC in a separate PR, for now I want to see how this current fix works on buildbots.

@aeiouaeiouaeiouaeiouaeiouaeiou PowerPC does not need any fixes, it works fine (well, at least it builds both on standard 10.6.8 Rosetta and on 10.6 PPC).

What gonna break is building for Intel on physical PowerPC hardware, because suggested code will require clang11 based on configure.build_arch. So the fix is incorrect in this sense: it gonna break universal builds on old systems.

**Comment by neverpanic** [comment]
> > @barracuda156 we can add a fix for PowerPC in a separate PR, for now I want to see how this current fix works on buildbots.
> 
> @aeiouaeiouaeiouaeiouaeiouaeiou PowerPC does not need any fixes, it works fine (well, at least it builds both on standard 10.6.8 Rosetta and on 10.6 PPC).
> 
> What gonna break is building for Intel on physical PowerPC hardware, because suggested code will require clang11 based on configure.build_arch. So the fix is incorrect in this sense: it gonna break universal builds on old systems (I am not sure re 10.4 i386, but 10.5.8 universal will break).

Why would anyone build for Intel on PPC hardware? Presumably, they're not going to migrate to Intel hardware (new machines are arm64, not intel), and they made a choice to run PPC hardware specifically. Is this not just a case that we can fully ignore?

In any case, it sounds like what's currently in the PR is good to go. Unless somebody shouts "no1!1!!" soon, I'll merge that.

**Review by aeiouaeiouaeiouaeiouaeiouaeiou — APPROVED** [review]

**Comment by barracuda156** [comment]
@neverpanic I recall there are ports that want to be built as universal like darwinbuild which depends on openssl, but as I said, this is not a big concern for me. I gave up on universal builds long ago, it is too broken in MacPorts anyway.

This is good to merge, PowerPC build confirmed from my side.

**Pull request merged**
