### PR TITLE
stlink: GUI needs adwaita-icon-theme

### PR DESCRIPTION
**Pull request by evanmiller**
#### Description

Closes: https://trac.macports.org/ticket/63474

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by evanmiller** [comment]
Looks like stlink is not building with the current version of libusb; see here for a report:

https://githubmemory.com/repo/libusb/libusb/issues/931

**Comment by evanmiller** [comment]
This commit will likely fix the CI build:

https://github.com/stlink-org/stlink/commit/468b1d2daa853b975c33ab69876c486734f2c6a7

**Comment by mascguy** [comment]
Rerunning the CI jobs, now that https://github.com/macports/macports-ports/pull/14087 has been merged.

**Comment by mascguy** [comment]
Rebased against master, to pull in the changes for https://github.com/macports/macports-ports/pull/14087

**Pull request merged**
