### PR TITLE
emacs-mac-app: update to 6.3 (emacs 25.2)

### PR DESCRIPTION
**Pull request by amake**
###### Description
Update the emacs-mac-app port to 6.3 (emacs 25.2).

### CODE REVIEW

**Comment by seanfarley** [comment]
Seems this was merged as 5b1fb8c123

**Comment by amake** [comment]
@seanfarley That's a different port.

**Comment by seanfarley** [comment]
Sigh. I wish I could read.

**Comment by seanfarley** [comment]
Finally closed in 64463a570d (sorry for the confusion!)

**Comment by amake** [comment]
@seanfarley No worries! Thanks!

**Pull request closed without merging**
