### PR TITLE
gdb: Fix x86_64 builds on Apple silicon a different way

### PR DESCRIPTION
**Pull request by Gcenx**
#### Description

@kencu heres a much cleaner way to handle this.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Typo in the title, should be `gdb`.

**Comment by kencu** [comment]
magical mystical port group magic. -- hah hah, gotta love it.

Now why would the universal PortGroup be doing anything at all on a build that is not universal?

Would anyone (including me) ever think it would be?

**Comment by Gcenx** [comment]
> magical mystical port group magic. -- hah hah, gotta love it.

Yep I’ve moved everything I’m maintaining in my overlay to muniversal-1.1 for all these special little things.

> Now why would the muniversal PortGroup be doing anything at all on a build that is not universal?

When cross-compiling it’s common to set --build & --host, these are not always needed when you have a cross-toolchain installed but we don’t in the case of macOS so we simply telling configure we’re xyz host and building for xyz since we match no need to look for prefixed tools.

Apples entire toolchain is a cross-toolchain but configure based projects can get confused so we’re simply helping them understand what’s todo.

> Would anyone (including me) ever think it would be?

If you don’t commonly cross-compile you might not look for something like this.

**Comment by kencu** [comment]
Yeah, but what I mean is the muniversal PortGroup should do **nothing** when you are not building universal.

**Comment by Gcenx** [comment]
> Yeah, but what I mean is the muniversal PortGroup should do **nothing** when you are not building universal.

That’s not how muniversal-1.1 works though with legitimate reason.

You can have separate configure.args etc for specific architectures without special blocks, this makes makes Portfiles way less complicated.

To build a project for x86_64 from arm64 we required setting --build & --host, this being an example of a port that requires this.

**Comment by Gcenx** [comment]
> Typo in the title, should be `gdb`.

That’s due to the commit being wrong that’s what I get for doing that on mobile…., Ken fixed the Pr title and I’ve just pushed a fixed commit message thanks for noticing.

**Comment by kencu** [comment]
I think we'll stick with the one I tested, but I will look at Marcus' group in future, thanks, perhaps for the next update.

**Comment by Gcenx** [comment]
> I think we'll stick with the one I tested, but I will look at Marcus' group in future, thanks, perhaps for the next update.

You really should muniversal-1.1 has really helped shrink down the usual B.S especially when specific arguments are required per arch.

**Pull request closed without merging**
