### PR TITLE
graphviz-devel: remove Clang '_Nullable' work around

### PR DESCRIPTION
**Pull request by Smattr**
#### Description

Graphviz commit b517af6738b5900b10dd5397a918760d6c14f76f removed the offending file quoted in the comment here. This commit made it into Graphviz 4.0.0, so this suppression should no longer be required.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

I do not have a macOS environment in which to test this. I am just one of the upstream Graphviz maintainers who noticed this in driving by.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
> I do not have a macOS environment in which to test this.

[According to Wikipedia](https://en.wikipedia.org/wiki/Xcode#Xcode_7.0_-_10.x_(since_Free_On-Device_Development)_2), Apple clang 900 was approximately equal to llvm.org clang 4.0.0. Have you checked if you are able to build Graphviz on your non-Mac with llvm.org clang versions earlier than 4.0.0?

**Comment by kencu** [comment]
> > I do not have a macOS environment in which to test this.
> 
> [According to Wikipedia](https://en.wikipedia.org/wiki/Xcode#Xcode_7.0_-_10.x_(since_Free_On-Device_Development)_2), Apple clang 900 was approximately equal to llvm.org clang 4.0.0.

llvm.org clang 9.0.0

**Comment by ryandesign** [comment]
> > [According to Wikipedia](https://en.wikipedia.org/wiki/Xcode#Xcode_7.0_-_10.x_(since_Free_On-Device_Development)_2), Apple clang 900 was approximately equal to llvm.org clang 4.0.0.
> 
> llvm.org clang 9.0.0

No, llvm.org clang 4.0.0.

**Comment by kencu** [comment]
> > > [According to Wikipedia](https://en.wikipedia.org/wiki/Xcode#Xcode_7.0_-_10.x_(since_Free_On-Device_Development)_2), Apple clang 900 was approximately equal to llvm.org clang 4.0.0.
> > 
> > 
> > llvm.org clang 9.0.0
> 
> No, llvm.org clang 4.0.0.

no, llvm.org clang 9.0.0.

**Comment by mascguy** [comment]
Converting to draft, as we need to validate this change on older macOS releases.

**Comment by chrstphrchvz** [comment]
> > > > [According to Wikipedia](https://en.wikipedia.org/wiki/Xcode#Xcode_7.0_-_10.x_(since_Free_On-Device_Development)_2), Apple clang 900 was approximately equal to llvm.org clang 4.0.0.
> > > 
> > > 
> > > llvm.org clang 9.0.0
> > 
> > 
> > No, llvm.org clang 4.0.0.
> 
> no, llvm.org clang 9.0.0.
> 
> You’ve misread the Swift version instead, probably.

I think Ryan is right; he is referring to the "LLVM" column of the table, not the "Swift version string" column. Apple clang 1103 (Xcode 11.4) was the earliest to be based on LLVM.org clang 9.0.0.

**Comment by kencu** [comment]
Looks like I might have misread the table :)

Thanks

**Comment by mascguy** [comment]
I've dropped the update to `graphviz`, as we'll need to validate it first via `graphviz-devel`.

**Comment by Smattr** [comment]
I cannot parse which Clang/LLVM version was the consensus, so I picked the older one (tag `llvmorg-4.0.0`) and built this on Ubuntu 22.04. To build this older version with GCC 11.4.0 required this patch based on https://github.com/sunziping2016/aur-llvm39/blob/master/0004-fix-lambda-parameter-name-redeclared.patch:

```diff
diff --git clang/lib/CodeGen/CGOpenMPRuntime.cpp clang/lib/CodeGen/CGOpenMPRuntime.cpp
index 40252171368b..40a73ef7429e 100644
--- clang/lib/CodeGen/CGOpenMPRuntime.cpp
+++ clang/lib/CodeGen/CGOpenMPRuntime.cpp
@@ -6271,7 +6271,7 @@ void CGOpenMPRuntime::emitTargetDataCalls(
   // Generate the code for the opening of the data environment. Capture all the
   // arguments of the runtime call by reference because they are used in the
   // closing of the region.
-  auto &&BeginThenGen = [&D, &CGF, Device, &Info, &CodeGen, &NoPrivAction](
+  auto &&BeginThenGen = [&D, Device, &Info, &CodeGen, &NoPrivAction](
       CodeGenFunction &CGF, PrePostActionTy &) {
     // Fill up the arrays with all the mapped variables.
     MappableExprsHandler::MapBaseValuesArrayTy BasePointers;
@@ -6318,7 +6318,7 @@ void CGOpenMPRuntime::emitTargetDataCalls(
   };
 
   // Generate code for the closing of the data region.
-  auto &&EndThenGen = [&CGF, Device, &Info](CodeGenFunction &CGF,
+  auto &&EndThenGen = [Device, &Info](CodeGenFunction &CGF,
                                             PrePostActionTy &) {
     assert(Info.isValid() && "Invalid data environment closing arguments.");
 
@@ -6397,7 +6397,7 @@ void CGOpenMPRuntime::emitTargetDataStandAloneCall(
          "Expecting either target enter, exit data, or update directives.");
 
   // Generate the code for the opening of the data environment.
-  auto &&ThenGen = [&D, &CGF, Device](CodeGenFunction &CGF, PrePostActionTy &) {
+  auto &&ThenGen = [&D, Device](CodeGenFunction &CGF, PrePostActionTy &) {
     // Fill up the arrays with all the mapped variables.
     MappableExprsHandler::MapBaseValuesArrayTy BasePointers;
     MappableExprsHandler::MapValuesArrayTy Pointers;
```

and this one based on https://bugzilla.redhat.com/attachment.cgi?id=1389687&action=diff:

```diff
diff --git llvm/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h llvm/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h
index 8647db56cd2f..7117acc22273 100644
--- llvm/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h
+++ llvm/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h
@@ -687,7 +687,7 @@ private:
 
   uint32_t getTrampolineSize() const { return RemoteTrampolineSize; }
 
-  Expected<std::vector<char>> readMem(char *Dst, JITTargetAddress Src,
+  Expected<std::vector<uint8_t>> readMem(char *Dst, JITTargetAddress Src,
                                       uint64_t Size) {
     // Check for an 'out-of-band' error, e.g. from an MM destructor.
     if (ExistingError)
```

With no flags, `./configure` of Graphviz 9.0.0 fails because Qt bumps the C++ requirement to C++17 which this version of Clang is too old to support. With `--without-qt` which it looks like you’re applying, the build then fails in the OCaml bindings due to an old SWIG issue. Applying `--disable-ocaml` which it also looks like you’re applying, the next issue we hit is with the Ruby bindings. Applying `--disable-ruby` which it also looks like you’re applying, build and installation succeeds.

I did this incrementally rather than just applying the `./configure` flags you’re using in the Portfile to get a better overview of what breaks if you further try to enable more Graphviz components.

**Comment by kencu** [comment]
I was in error, and Apple clang 900 is much closer to llvm-4.0 than I had recalled. It's an easy enough mistake to make, in my defence, when you see this all the time:

```
$ clang -v
Apple LLVM version 9.0.0 (clang-900.0.39.2)
```

but I shouldn't have been so dogmatic about it without specifically checking.

Between clang 900 and 1300 there was a big catchup in version numbering, and clang-1316 is derived from llvm-13.  From there on, the numbering makes a lot more sense.

**Comment by reneeotten** [comment]
so, this has been a draft for two weeks without any visible progress. Please follow-up here on what the plan is or please close the PR.

**Comment by Smattr** [comment]
Is that a question to me? I believed I followed up on what was requested: Graphviz 9.0.0 builds with llvm-4.0.0 on Linux. My understanding was that this PR was still in draft because it needs macOS validation. I have no way of doing this.

**Comment by reneeotten** [comment]
> Is that a question to me? I believed I followed up on what was requested: Graphviz 9.0.0 builds with llvm-4.0.0 on Linux. My understanding was that this PR was still in draft because it needs macOS validation. I have no way of doing this.

well, you open the PR and the CI systems is still failing. So something needs to be done here to get that to pass, then sure one can check whatever OS version someone wants to check. But it has to work on the last three released versions; that's the responsibility of the PR submitter to sort out.

**Comment by Smattr** [comment]
Oh sorry, I misunderstood you. I choose to abandon this.

**Comment by ryandesign** [comment]
> well, you opened the PR and the CI systems are still failing. So something needs to be done here to get that to pass, then sure one can check whatever OS version someone wants to check. But it has to work on the last three released versions; that's the responsibility of the PR submitter to sort out.

The CI failure is due to https://trac.macports.org/ticket/68417 which is unrelated to this PR.

While successful CI builds can be reassuring I don't consider them to be a requirement for a PR to be accepted. We would not, for example, turn down an obviously-correct PR that fixes typos in a port even if that PR does not fix all preexisting build failures in the port.

This proposed change only removes blacklisting of compilers that are older than any tested by CI, so even if CI builds succeeded it would not indicate whether this change is correct.

I have now tried building graphviz 9.0.0 on Mac OS X 10.7.5 using the clang installed by Xcode 4.6.3:

```
$ clang --version
Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)
Target: x86_64-apple-darwin11.4.2
Thread model: posix
```

and the one installed by the clang-3.7 port:

```
$ clang-mp-3.7 --version
clang version 3.7.1 (tags/RELEASE_371/final)
Target: x86_64-apple-darwin11.4.2
Thread model: posix
```

and both succeeded so I am satisfied that old compilers no longer need to be excluded for graphviz.

Since this was the only use of compiler blacklisting by version in the port, the inclusion of the compiler_blacklist_versions portgroup at the top of the portfile should also be removed.

The same changes should be made in the graphviz port since it and the graphviz-devel port should be kept as similar as possible.

I'll make these changes in a moment and merge the PR.

@Smattr Thanks for helping to clean up the port!

**Comment by ryandesign** [comment]
> The same changes should be made in the graphviz port since it and the graphviz-devel port should be kept as similar as possible.

I see that you submitted it this way originally and @mascguy changed it to only graphviz-devel. Chris, there's nothing to be gained by this. This doesn't help us "validate" that the fix is correct. The version and revision are (correctly) unchanged so the buildbot is not going to do new builds as a result of this change, so any validation needs to happen by manual builds on your own machine, as I did above.

**Comment by mascguy** [comment]
> > The same changes should be made in the graphviz port since it and the graphviz-devel port should be kept as similar as possible.
> 
> I see that you submitted it this way originally and @mascguy changed it to only graphviz-devel. Chris, there's nothing to be gained by this. This doesn't help us "validate" that the fix is correct. The version and revision are (correctly) unchanged so the buildbot is not going to do new builds as a result of this change, so any validation needs to happen by manual builds on your own machine, as I did above.

Agreed, thanks for taking care of this Ryan!

**Pull request merged**
