### PR TITLE
mysql57-connector-cpp: new port

### PR DESCRIPTION
**Pull request by jdvornek**
Adds MySQL Connector/C++ 1.1.9 for the mysql57 port

#### Description

I added this as a new port as opposed to enhancing the older mysql55-connector-cpp since the testing requirements would have been much higher (that port currently supports MySQL <= 5.5, MariaDB, and Percona).  This port enables the latest Connector/C++ to be used against the latest version of MySQL server currently available in MacPorts.  If the maintainers of mysql55-connector-cpp want to backport it, I believe it would be straightforward.

###### Tested on

macOS 10.13.1
Xcode 9.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jdvornek** [comment]
I did see that some of the mirrors were only hosting 1.1.8, but 1.1.9 has been the latest generally available version of the library since 2017-05-16: [MySQL Connector/C++](https://dev.mysql.com/downloads/connector/cpp/), [changelog](https://dev.mysql.com/doc/relnotes/connector-cpp/en/news-1-1.html).

**Comment by pmetzger** [comment]
@jdvornek Do you think you could squash the commits to make merging easier?

@mojca Do you see any remaining reason not to merge?

**Comment by jdvornek** [comment]
@pmetzger - squashed.

**Comment by mojca** [comment]
One valid reason for not merging would be if @pixilla was willing to incorporate it into his master port where all those databases are supported. This is the only one that then "sticks out". But if he's not willing to do it, that's of course another story.

**Comment by jdvornek** [comment]
Absent feedback from @pixilla, couldn't this be merged as-is and an incorporation into the other port done as a later enhancement?

**Comment by mojca** [comment]
Yes, it could. We only CC-ed him four days ago and it's polite to give maintainer three days before any such changes are made to "their" ports. But if he doesn't reply and if nobody is willing to step in and do the merge, this can surely be committed as a standalone port. I would perhaps make a small note in both ports that a merge would be desired though, so that next time when someone takes time to update one port or the other gets reminded to look into this. (It could be done as a separate commit.)

**Comment by pmetzger** [comment]
@mojca Do you want to do the merge (and the shepherding forward from here?)

**Comment by pixilla** [comment]
What email?

—
Brad

**Comment by mojca** [comment]
I should have said `@mentioned`. You should have gotten a notification, if nothing else when one adds @pixilla to comments. But maybe you disabled notifications altogether due to too much traffic?

**Comment by pixilla** [comment]
Thank you for the clarification. This “new” port is largely based on my “master” port that serves multiple versions of mysql.

Let me see if it builds easily,.

**Comment by pixilla** [comment]
@jdvornek I updated mysql55-connector-cpp port with your work and updated the list of mysql versions to:
mysql51
mysql55
mysql56
mysql57
mariadb
percona

All these installed for me with the exception of mysql51 which I cannot test on my High Sierra system. There is an examples-CMakeLists.txt file which you authored and contributed. Do you have any objection to me updating the existing mysql55-connector-cpp port with your work adding support for the listed mysql versions here?

**Comment by jdvornek** [comment]
@pixilla no objection from me, thanks for updating your port.

**Comment by pixilla** [comment]
Ok, thanks. Mysql51-connector-cpp built under El Capitan so I'll push the updates. We should probably retire mysql51, mysql55 and mariadb soon. The mysql-connector-cpp does not build as is against our mariadb-10.{0,1,2} ports. I see a fork but I'll let interested parties request this before looking further.

**Comment by pmetzger** [comment]
@pixilla So should this PR be closed?

**Comment by pmetzger** [comment]
(And if so, could you close it?)

**Comment by pixilla** [comment]
Closing because we updated current port based on work here.

**Comment by mojca** [comment]
@pixilla: it makes sense to add `Closes: https://github.com/macports/macports-ports/pull/1386` to the commit next time which creates the cross-references.

01b2ce0aea11b55dd9e07a90751ca423dcb69fe3

**Pull request closed without merging**
