### PR TITLE
KeePassXC: update to 2.3.1

### PR DESCRIPTION
**Pull request by yan12125**
###### Type(s)
- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.3 17D102
Xcode 9.2 9C40b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? (N/A)
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`? (N/A)
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by yan12125** [comment]
[Building against 10.9 was broken](https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/49813/steps/install-port/logs/stdio), and I'd like to fix that in the same PR. I believe the second commit ("KeePassXC: fix building on 10.9") works, but I don't have a 10.9 machine to test it. Can anyone test that?

Building on 10.8 or earlier requires https://trac.macports.org/ticket/51516 as KeePassXC source tarballs are on GitHub, which [requires TLS 1.2 now](https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/).

**Comment by yan12125** [comment]
Travis CI failed with seemingly unrelated errors:

> Post https://paste.macports.org/: dial tcp: lookup paste.macports.org: no such host

**Comment by pmetzger** [comment]
Yah, I really wouldn't worry too much about the Travis errors. Travis seems to fail for no reason all the time.

Do you think you could split this into two PRs? The update for 2.3.1 is really trivial, and I can merge that immediately. I'd like someone else to look at the 10.9 issue.

**Comment by yan12125** [comment]
> Do you think you could split this into two PRs?

Sure. This PR now contain only trivial changes :)

I'll create a PR for 10.9 later.

**Comment by pmetzger** [comment]
Merged! Thank you!

**Pull request merged**
