### PR TITLE
gjs-devel: update to 1.74.1

### PR DESCRIPTION
**Pull request by evanmiller**
#### Description

Builds fine, ran the test suite. The Cairo module tests are failing, but everything else is passing.

CI is failing because the build needs glib2-devel and gobject-introspection-devel.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by evanmiller** [comment]
Bump. Maybe @michaelld or @kencu can take a look?

**Comment by mascguy** [comment]
Hey Evan, sorry for being MIA for so long! Just rebased against master, fixed the conflicts, and squashed.

Next up is updating `glib2` and `glib2-devel`. (Both are high on my priority list, and hoping to tackle those soon.) More to follow.

**Comment by evanmiller** [comment]
Looks like 1.76.0 was released in the meantime... Will keep an eye on `glib` and friends, welcome back :-)

**Comment by michaelld** [comment]
I've been MIA for along time too ... slowly getting back into things as my time allows.

Do we not have `glib2-devel` and `gobject-introspection-devel` yet? Those would be useful

**Comment by mascguy** [comment]
> I've been MIA for along time too ... slowly getting back into things as my time allows.
> 
> Do we not have `glib2-devel` and `gobject-introspection-devel` yet? Those would be useful

Glad you're back too Michael!

As for those two ports, they exist... but they're a bit out-of-date due to my absence.

**Review by mascguy — APPROVED** [review]
Tested locally with `gobject-introspection-devel` and `glib2-devel` on 10.15, and looks good. If there are any buildbot failures for other macOS releases, I'll tackle those promptly.

Thanks as always Evan!

**Comment by mascguy** [comment]
> Tested locally with `gobject-introspection-devel` and `glib2-devel` on 10.15, and looks good. If there are any buildbot failures for other macOS releases, I'll tackle those promptly.

To clarify: This port will fail across-the-board on the buildbots, due to the dependencies on `glib2-devel` and `gobject-introspection-devel`. But I plan to test locally on a wide swath of macOS releases, and will commit any fixes if necessary. (Evan is already aware of this, but for any casual/interested observers...)

**Comment by evanmiller** [comment]
> > Tested locally with `gobject-introspection-devel` and `glib2-devel` on 10.15, and looks good. If there are any buildbot failures for other macOS releases, I'll tackle those promptly.
> 
> To clarify: This port will fail across-the-board on the buildbots, due to the dependencies on `glib2-devel` and `gobject-introspection-devel`. But I plan to test locally on a wide swath of macOS releases, and will commit any fixes if necessary. (Evan is already aware of this, but for any casual/interested observers...)

FYI this port should be depending on glib2-devel and not glib2-upstream

**Comment by mascguy** [comment]
> FYI this port should be depending on glib2-devel and not glib2-upstream

No worries, I'll add that to my to-do list. Thanks Evan!

**Pull request merged**
