### PR TITLE
glom: use one python version

### PR DESCRIPTION
**Pull request by catap**
#### Description

This PR is required for https://github.com/macports/macports-ports/pull/15987

Anyway, it is unrelated to update ICU => keep it as dedicated PR.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.5.1 21G83 x86_64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
@mascguy what should I do with this one?

It was built by some side-effects, upstream hasn't say a word about support of python-3.10 and by default boost is installed with python310 variant.

:(

**Comment by mascguy** [comment]
> @mascguy what should I do with this one?
> 
> It was built by some side-effects, upstream hasn't say a word about support of python-3.10 and by default boost is installed with python310 variant.
> 
> :(

Do tests pass for Python 3.10? (Assuming it builds?)

**Comment by mascguy** [comment]
> Do tests pass for Python 3.10? (Assuming it builds?)

Or if there aren't any tests, does it build/work, using Python 3.10?

**Comment by catap** [comment]
> > Do tests pass for Python 3.10? (Assuming it builds?)
> 
> Or if there aren't any tests, does it build/work, using Python 3.10?

I haven't tried tests and they seems for me more for C that for Python: https://gitlab.gnome.org/GNOME/glom/-/tree/master/tests

**Comment by mascguy** [comment]
> I haven't tried tests and they seems for me more for C that for Python: https://gitlab.gnome.org/GNOME/glom/-/tree/master/tests

I'd try to test locally with Python 3.10 then. (And if you're using Quartz for other GUI ports, install with `+quartz` to avoid pulling in X11 stuff...)

**Comment by catap** [comment]
> > I haven't tried tests and they seems for me more for C that for Python: https://gitlab.gnome.org/GNOME/glom/-/tree/master/tests
> 
> I'd try to test locally with Python 3.10 then. (And if you're using Quartz for other GUI ports, install with `+quartz` to avoid pulling in X11 stuff...)

Thanks, I may do it but in couple of hours at best. I'm near finish of patching everything for icu ;)

**Comment by mascguy** [comment]
> > I'd try to test locally with Python 3.10 then. (And if you're using Quartz for other GUI ports, install with `+quartz` to avoid pulling in X11 stuff...)
> 
> Thanks, I may do it but in couple of hours at best. I'm near finish of patching everything for icu ;)

No worries. I'll test building with Python 3.10, and let you know the result.

**Comment by mascguy** [comment]
> No worries. I'll test building with Python 3.10, and let you know the result.

The build looks fine. But when launching, the app fails with a Python module import error:

```
sys:1: PyGIWarning: Gda was imported without specifying a version first. Use gi.require_version('Gda', '5.0') before import to ensure that the right version gets loaded.
boost::python::object Glom::import_module(const char *): boost::python::import() failed while importing module: glom_1_32
void Glom::ShowTrace(): Glom: Python Error:
Glib::ustring Glom::get_traceback(): traceback = 0
ImportError: dynamic module does not define module export function (PyInit_glom_1_32)

boost::python::object Glom::import_module(const char *): Glom: A python import of a module failed: glom_1_32
Your installation of Glom is not complete, because the Glom Python module is not available on your system.
```

Based on what the port is installing, it almost looks (?) as if the Python module isn't complete:

```
/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glom_1_32.so
```

And that lib is the only thing installed. Shouldn't there be more, or is that enough for certain cases...?

**Comment by catap** [comment]
@mascguy thanks, I'll try to fix it.

**Comment by catap** [comment]
@mascguy I've pushed that I did. Anyway, I'm run out of ideas. It simple doesn't work.

```
high-sierra:~ catap$ nm /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glom_1_32.so | grep PyInit_glom_1_32
0000000000009b67 t _PyInit_glom_1_32
0000000000019298 b __ZGVZ16PyInit_glom_1_32E9moduledef
0000000000015340 s __ZZ16PyInit_glom_1_32E14initial_m_base
0000000000019210 b __ZZ16PyInit_glom_1_32E15initial_methods
0000000000019230 b __ZZ16PyInit_glom_1_32E9moduledef
high-sierra:~ catap$ python3.10
Python 3.10.6 (main, Aug  3 2022, 06:17:53) [Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import glom_1_32
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_glom_1_32)
>>> 
```

Symbol exists, but it hasn't load it.

**Comment by mascguy** [comment]
> @mascguy I've pushed that I did. Anyway, I'm run out of ideas. It simple doesn't work.
> 
> ```
> high-sierra:~ catap$ nm /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glom_1_32.so | grep PyInit_glom_1_32
> 0000000000009b67 t _PyInit_glom_1_32
> 0000000000019298 b __ZGVZ16PyInit_glom_1_32E9moduledef
> 0000000000015340 s __ZZ16PyInit_glom_1_32E14initial_m_base
> 0000000000019210 b __ZZ16PyInit_glom_1_32E15initial_methods
> 0000000000019230 b __ZZ16PyInit_glom_1_32E9moduledef
> high-sierra:~ catap$ python3.10
> Python 3.10.6 (main, Aug  3 2022, 06:17:53) [Clang 9.1.0 (clang-902.0.39.2)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import glom_1_32
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: dynamic module does not define module export function (PyInit_glom_1_32)
> >>> 
> ```
> 
> Symbol exists, but it hasn't load it.

I can take a closer look tomorrow, if you're still focused on other work related to `icu`.

**Comment by catap** [comment]
@mascguy now it works:
```
Python 3.10.6 (main, Aug  3 2022, 05:37:08) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import glom_1_32
>>> 
```

**Comment by mascguy** [comment]
> @mascguy now it should work:
> 
> ```
> Python 3.10.6 (main, Aug  3 2022, 05:37:08) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import glom_1_32
> >>> 
> ```

Awesome, I'll merge once CI completes. Great work Kirill!

**Comment by mascguy** [comment]
It looks like you have similar changes in your PR for `icu`. Do you want to merge this first, and then rebase your `icu` PR?

**Comment by catap** [comment]
> It looks like you have similar changes in your PR for `icu`. Do you want to merge this first, and then rebase your other one?

Yes, I'd love to merge this one first. And allow `icu` PR to keep opeened for a few more days for the case that someone says NOOOO.

**Comment by catap** [comment]
@mascguy maybe you would like to be co-maintaner? ;)

**Review by mascguy — APPROVED** [review]

**Pull request merged**
