### PR TITLE
py-xxhash: Update to version 3.3.0; Add Python 311

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
Hi @essandess! You have a bunch of py-* updates stuck in the queue because the CI fails for more or less all of them. Can you either fix them so that the CI passes, tell us (convincingly) why the CI failing doesn't matter, or withdraw them?

**Comment by reneeotten** [comment]
@essandess looks like you're missing the `setuptools_scm` package?

**Comment by pmetzger** [comment]
@reneeotten I'm starting to get inclined to close all of @essandess's open `py-*` PRs that fail the CI. He does not currently appear to be responsive about trying to clear them out. He can always reopen them if he wishes to later. There are a *lot* of them in the queue. The responsibility of a submitter is to make sure that their PRs pass CI and to be responsive when questions get asked. Perhaps he is having some trouble at the moment that makes communication difficult, but if so, he can always reopen these later.

**Comment by kencu** [comment]
I think the basic issue seem to be a 0% trust in the CI system to work properly by the submitter, so 100% of  the build failures are felt to be bogus and therefore to be ignored.

**Comment by pmetzger** [comment]
In this case, 100% of the CI failures appear to be real. However, the submitter is also not actually communicating, which makes achieving progress quite hard.

**Comment by pmetzger** [comment]
@essandess Could you let us know if you intend to address the CI failure? I believe @reneeotten has described the problem.

**Comment by pmetzger** [comment]
Hi @essandess! It's been over a month and we haven't heard from you on this and the pull request doesn't pass the CI and you've neither explained nor fixed that. I'm going to close this for now. Feel free to request the pull again if it passes the CI or there's a good reason it doesn't.

**Pull request closed without merging**
