### PR TITLE
the new minetest-devel port delivering a cutting edge Minetest to MacPorts

### PR DESCRIPTION
**Pull request by Zweihorn**
This PR is a DRAFT and **WIP** until further notice.

The _minetest_ port is at MT 5.6.1 current level, however the build is **not optimal** IMO. 

#### Description

This is the new **minetest-devel** port, delivering a cutting edge **Minetest** to macOS by help of MacPorts.

The contribution and core commit is the **improved Portfile** derived from the legacy Portfile.

This PR addresses the Ticket at <https://trac.macports.org/ticket/66562>
Please take the time to thoroughly read the complete Description text of this Ticket.

TO DO: Please note Test and Verification shall be accomplished in due time.

Please be aware, my work and/or contribution to Open Source Endeavour is always published under the **EUPL-1.2** license. This fits my legal requirement as an European citizen thus outside U.S. jurisdiction. Furthermore, the Open Source Initiative (OSI) approves of EUPL-1.2 and agrees, that **public domain doesn't exist in Europe**.

  * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12

More information in section _License_ added below.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.7.2 20G1020 x86_64
Command Line Tools 13.2.0.0.1.1638488800

###### Verification 

Have you - **Stay tuned.** 

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`? - see below
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?

##### Portfile check

```
$ port lint --nitpick -F Portfile
--->  Verifying Portfile for minetest-devel
Warning: Line 15 seems to hardcode the version number, consider using ${version} instead
--->  0 errors and 1 warnings found.
Error: Unrecognized action "port PortSystem"
```

##### Licence

@Zweihorn - 2022-12-26
This work is derived from work under the LGPL-1.2+ on MacPorts ports.

Licensed under the EUPL-1.2-or-later

The text of the European Union Public Licence (EUPL) version 1.2, 
published in Official Journal of 19 May 2017 and available in 23
official languages of the European Union (SPDX identifier EUPL-1.2), is
found at:

  * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12

The a.m. page contains all the official versions of the European Union
Public Licence (EUPL-1.2).  The preamble written for v 1.0, explaining
the purpose of this Free/Open Source Software Licence, together with
links to further information on the licence is valid for later versions.

The Joinup Licensing Assistant (JLA) may be worth a visit to find and
compare software licenses with:

  * https://joinup.ec.europa.eu/collection/eupl/solution/joinup-licensing-assistant/jla-find-and-compare-software-licenses

The JLA is linked to SPDX (for Software Package Data Exchange), an
initiative of the LINUX foundation that attempts to standardize the way
in which organizations refer to software licenses: each licence is
identified by a full name, such as "European Union Public Licence 1.2"
and a shorter identifier, here "EUPL-1.2".

### CODE REVIEW

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
I can't see what the point of this PR is, since Minetest is already on [5.6.1](https://ports.macports.org/port/minetest/details/) and versions sync with [GitHub Releases](https://github.com/minetest/minetest/releases).
In the meantime, I should test and create a separate port with the latest compatible version for SL as [`libsdl2-snowleopard`](https://ports.macports.org/port/libsdl2-snowleopard/details/).

CC @l2dy

**Comment by Zweihorn** [comment]
> I can't see what the point of this PR is, since Minetest is already on [5.6.1](https://ports.macports.org/port/minetest/details/) and versions sync with [GitHub Releases](https://github.com/minetest/minetest/releases). In the meantime, I should test and create a separate port with the latest compatible version for SL as [`libsdl2-snowleopard`](https://ports.macports.org/port/libsdl2-snowleopard/details/).
> 
> CC @l2dy

THX - That is correct to some degree.

Both minetest and minetest-devel are at MT 5.6.1 version. However, the build depends are different in some detail.

As written in the a.m. Ticket certain specifics have been overlooked apparently and the updated build depends in the derived Portfile of minetest-devel are addressing this. Furthermore there is a rationale why it may be worthile to have a minetest and a mineport-devel in parallel.

NB - I miss Snow Leopard and the (formely) quite promising **Mac OSX Server** quite utterly today.
Where did all the former Darwin Unix experts of Apple Inc. go? I wonder sometimes. Success devours its children.

NB - A very Merry Christmas and a Happy New Year to you and family if I may.

**Comment by Zweihorn** [comment]
Lesson learned: Always prode a **diff** between the old and new Profile for a new port derived from an old one.

**Comment by Zweihorn** [comment]
Question 1: Why did the intentionally provided "[skip notification]" in the PR text **not work** as expected?

**Comment by Zweihorn** [comment]
This PR was made **obsolete** by the more mature PR #17080

PR closed

**Comment by Zweihorn** [comment]
IMO this was a good learning experience.

My sincere thanks to the developers involved involuntarily and/or giving advice.

**Pull request closed without merging**
