### PR TITLE
transmission-x11: update to 4.0.3, fix powerpc

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

PowerPC status: CLI on PowerPC is actually working (not just building). GUI needs more work: https://trac.macports.org/ticket/67654

@i0ntempest Adding myself as a co-maintainer, since this port does not get much attention recently, but if there are any objections, I drop myself, this is not important for the PR.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Guess we need to tune configure for recent macOS. Will deal with this soon.

**Comment by i0ntempest** [comment]
You're very welcomed to take maintainership on this. I actually want to drop this since it's basically for people running legacy systems who can't run the aqua `transmission` port, and I don't have any old systems to test stuff. So you may just remove me from this port and I'll focus on maintaining the aqua `transmission` port.

**Comment by barracuda156** [comment]
@i0ntempest Makes sense, thank you.

Should we try fixing GTK build on newer systems or just restrict the port to older ones?

**Comment by i0ntempest** [comment]
If you can make it build that would be the best option, otherwise I guess it’s fine to restrict it since again it’s a fallback.

**Comment by barracuda156** [comment]
@i0ntempest Fixed it! Just a missing dependency :)

**Pull request merged**
