### PR TITLE
Php tideways xhprof submission

### PR DESCRIPTION
**Pull request by stronk7**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G103
Xcode 11.1 11A1027 

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by stronk7** [comment]
Note I've left 2 commits, the original one, v4.1.7, that I've been using for all my php 7.x versions since some months ago and working ok.

And the brand-new v5.0.1, just released today and that builds ok and my preliminary tests say that it's working as expected (but have not used it too much yet).

Ciao :-)

**Comment by mf2k** [comment]
In general this LGTM. I hope Ryan will take a look though. 

The commits needs to be squashed with the message being:

`php-tideways_xhprof: New port
`

**Comment by ryandesign** [comment]
Agree with Frank, generally this is good. Looks like [the xhprof situation is stupid](https://secure.phabricator.com/T9805#233567) and the original developer is no longer developing it and expects those wishing to continue its development to fork and rename; tideways_xhprof is one of those forks and we should have it in MacPorts. (The other is longxinH/xhprof and we have [a ticket](https://trac.macports.org/ticket/57340) about that.)

One error, as shown above:

> Port php73-tideways_xhprof **fail** on xcode7.3. [Log](https://paste.macports.org/123e07a0ddff)

```
./timer.h:68:23: error: use of undeclared identifier 'CLOCK_MONOTONIC'
```

Probably the legacysupport portgroup will help with this.

**Comment by stronk7** [comment]
Have squashed and amended the commit message as requested. If/when I've some time I'll look to that "legacysupport portgroup" concept that is brand new for me :-)

Thanks!

**Comment by mf2k** [comment]
I'm going to commit this because it appears to work for modern versions of macOS.

**Pull request merged**
