### PR TITLE
lua-language-server: update nvim-lspconfig link

### PR DESCRIPTION
**Pull request by williamboman**
Hello! I arrived here from GitHub search 🤓. This link was recently changed, so I figured I'd update as many inbound links as possible

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by judaew** [comment]
Thank you @williamboman 🌟

**Comment by reneeotten** [comment]
@judaew please make sure the PR checklist has been completed before merging (i.e., commit message follows our guidelines)

**Comment by judaew** [comment]
@reneeotten I apologize, I didn't see that the commit has a different header. I will be more attentive 😔

**Comment by williamboman** [comment]
My bad! I figured it'd do a squash commit using the PR title

**Comment by reneeotten** [comment]
@judaew @williamboman no worries, that happens - just for future reference ;)

**Pull request merged**
