### PR TITLE
support meson cross-compiling

### PR DESCRIPTION
**Pull request by kencu**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

### CODE REVIEW

**Comment by SoapZA** [comment]
looks good @kencu

**Comment by kencu** [comment]
@ryandesign -- this seems to do the right thing, and works for ```dav1d``` at least. There are a number of other ports we've had trouble with when cross-compiling with meson as well, and these have not all been tested with this yet.

**Comment by kencu** [comment]
Universal builds on PPC will fail, but hardly anyone is doing those any longer anyway. I'll add a PPC cross file in due course, once I sort out what it should be.

An arm64 cross file should be quite trivial to write as well, once we get to that.

meson has trouble sometimes figuring out what to do with some systems. It is possible we might decide to always pass the crossfile for all builds, not just universal builds, so we can control meson better (e.g. PowerPC which meson always seems to mess up, and building i386 software on systems that have x86_64 subsystems and vice versa).

**Comment by kencu** [comment]
couple of things to make sure of:

1. can we spec the compiler for the host build properly?
1. can we send in the linker?
1. what about any other host environment variables we want to set -- are they passed down to the cross-build?

**Comment by michaelld** [comment]
This reads well to me @kencu  ... I haven't tried it out yet.

**Comment by kencu** [comment]
passing the desired compiler and linker (and other flags) via envvars may be problematic with cross builds <https://mesonbuild.com/Running-Meson.html#environment-variables>.

It can get frustrating trying to undo all the "helpful" stuff these new build systems do to assist you...

**Comment by kencu** [comment]
the cross files can be layered; we can have an arch-specific one as we have here as a base, and then add a second one that has just the chosen compilers and linkers added...that second one could be written specifically for each build.

**Comment by kencu** [comment]
Well, **despite** what the docs say above, meson does seems to pick up our specified compiler and flags from our env vars and uses them during cross builds:
```
Build type: cross build
Project name: dav1d
Project version: 0.7.1
C compiler for the build machine: cc (clang 10.0.0 "Apple LLVM version 10.0.0 (clang-1000.10.44.4)")
C linker for the build machine: cc ld64 409.12
Using 'CC' from environment with value: '/opt/local/bin/clang-mp-9.0'
Using 'CFLAGS' from environment with value: '-pipe -Os -arch i386'
Using 'LDFLAGS' from environment with value: '-Wl,-read_only_relocs,suppress,-no_compact_unwind -L/opt/local/lib -Wl,-headerpad_max_install_names -arch i386'
Using 'CPPFLAGS' from environment with value: '-I/opt/local/include'
C compiler for the host machine: /opt/local/bin/clang-mp-9.0 (clang 9.0.1 "clang version 9.0.1 ")
C linker for the host machine: /opt/local/bin/clang-mp-9.0 ld64 450.3
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86
Host machine cpu: i386
Target machine cpu family: x86
Target machine cpu: i386
```
and the build lines all look right:
```
[40/98] /opt/local/bin/clang-mp-9.0 -Isrc/libdav1d_bitdepth_16.a.p -Isrc -I../dav1d_0.7.1-i386/src -I. -I../dav1d_0.7.1-i386 -Iinclude/dav1d -I../dav1d_0.7.1-i386/include/dav1d -Iinclude -I../dav1d_0.7.1-i386/include -I/opt/local/include -Xclang -fcolor-diagnostics -DNDEBUG -pipe -Wall -Winvalid-pch -Wextra -std=c99 -O3 -D_DARWIN_C_SOURCE -fvisibility=hidden -Wundef -Werror=vla -Wno-missing-field-initializers -Wno-unused-parameter -Werror=missing-prototypes -Wshorten-64-to-32 -msse2 -mfpmath=sse -fomit-frame-pointer -ffast-math -Os -arch i386 -DBITDEPTH=16 -MD -MQ src/libdav1d_bitdepth_16.a.p/x86_loopfilter_init_tmpl.c.o -MF src/libdav1d_bitdepth_16.a.p/x86_loopfilter_init_tmpl.c.o.d -o src/libdav1d_bitdepth_16.a.p/x86_loopfilter_init_tmpl.c.o -c ../dav1d_0.7.1-i386/src/x86/loopfilter_init_tmpl.c
```

I don't know exactly what to think about this:
```
C compiler for the build machine: cc (clang 10.0.0 "Apple LLVM version 10.0.0 (clang-1000.10.44.4)")
C linker for the build machine: cc ld64 409.12
```
but it appears meson ignores those two lines during the actual build, so I guess they are not an issue.

This PR brings us a step forward in cross compiling with meson -- simple universal builds can be done as they are now, without the muniversal PG, just letting the compiler do the cross compiling internally. That will cover the bulk of our troubles. But there are several ports that use meson that configure themselves differently based on the architecture, and dav1d is one of them, and for those ports, you need to have something like this to have them configure properly.

The build lines do complain about the lack of a cross-build strip binary. That might be something we need to consider adding.

So I'd say let's push this, and then we can refine it by adding a layered compiler / binaries file setting if we find we have to later on.

**Pull request merged**
