### PR TITLE
remove obsolete Python subports (maintainer: stromnov)

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR removes obsolete Python subports for an initial subset of ports maintained by @stromnov that have no dependencies. Subports for newer Python versions were added if the test-suite passes. 

###### Tested on
macOS 10.14.6 18G95
Xcode 10.3 10G8

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`? Yes, but only for ports where I added new subports
- [x] tried a full install with `sudo port -vst install`? Yes, but only for ports where I added new subports
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
The CI failures appear unrelated to the changes in this PR I think... it seems the failure already happens when listing the subports. @jmroot can this be related to the recent changes you made to ```mpbb```, which is the only thing I can find that possibly could affect this.

**Comment by jmroot** [comment]
Is there a log with the actual error somewhere?

**Comment by reneeotten** [comment]
> Is there a log with the actual error somewhere?

Yes, in the Travis or Azure builds in this PR; for example [this one](https://api.travis-ci.org/v3/job/609735352/log.txt)

**Comment by jmroot** [comment]
All that has is a bunch of messages like
```
--9bba227c544541bbafbe7a4fc806bab5489eae04f16d9303cac42e9eff2e

Content-Disposition: form-data; name="port-py-DAWG-subports-fail"

exit status 1
```

**Comment by jmroot** [comment]
@l2dy Any clue?

**Pull request merged**
