### PR TITLE
nsis: update to 3.05

### PR DESCRIPTION
**Pull request by idleberg**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G1012
Xcode 10.3 10G8

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
This appears to have a checksum failure.

**Comment by idleberg** [comment]
> This appears to have a checksum failure.

It's not the first time this has happened, I wonder what I'm doing wrong. The SHA256 hashes are certainly correct, the same ones are used in the [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/3b825a50e470965e3dd6b32a0fe21a43c80ef815/Formula/makensis.rb). As for RIPEMD160, I'm using the following to determine the hash:

```sh
$  openssl rmd160 nsis-3.05.zip
RIPEMD160(nsis-3.05.zip)= 5e799781fe6a93b4d21f6dac53355ca0e925ffce

$  openssl rmd160 nsis-3.05-src.tar.bz2
RIPEMD160(nsis-3.05-src.tar.bz2)= 8666b74da1b04d2810aaaf4aa7bba202b6a78e3c
```

These are the same checksums as in my PR, so I'm not sure what might be wrong.

**Comment by mf2k** [comment]
The commits need to be squashed.

**Comment by idleberg** [comment]
@mf2k looks like this is first successful squash

**Comment by mf2k** [comment]
Looks good. Thank you.

**Pull request merged**
