### PR TITLE
welle.io: update to 2.1

### PR DESCRIPTION
**Pull request by tenzap**
* update to 2.1 
* update welle.io-devel to 20191204 
* update license to GPL-3+ (see https://trac.macports.org/ticket/59779)

Closes: https://trac.macports.org/ticket/59779

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65
Xcode 9.4.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
The commit message should have one item per line.

**Comment by tenzap** [comment]
What do you mean by commit message ?
this

"welle.io: update to 2.1 and welle.io-devel to 20191204 and license to GPL-3+"

or that ?

"    update to 2.1
    update welle.io-devel to 20191204
    update license to GPL-3+ (see https://trac.macports.org/ticket/59779)

Closes: https://trac.macports.org/ticket/59779"

**Comment by tenzap** [comment]
Any news here ? I changed the title of the PR and the content was already following your guidelines.

**Comment by mf2k** [comment]
I mean the GitHub commit message, and not the PR description. So the first choice you listed.

**Comment by tenzap** [comment]
I'm still not sure if it's right, if not could you please be more precise on what you mean ?
For now I got the inspiration from the example of the guidelines

**Comment by mf2k** [comment]
You got it right this time!

**Pull request merged**
