### PR TITLE
Erlang: Fix incorrect symlink target for erts directory

### PR DESCRIPTION
**Pull request by enquora**
erts 12.2 doesn't exist, version 15.0 is the one included with Erlang 27. This doesn't resolve the presence of an erts-10.7.2.1 directory - it exists but its purpose is unclear.

###### Type(s)

- [ x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 15.0
Xcode 16.1 

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
This would change files the port installs so the `revision` must be increased.

**Comment by ryandesign** [comment]
> * [ ]  followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?

Please reword the commit message to conform to the guidelines.

**Comment by enquora** [comment]
I will leave this to others with more experience committing to MacPorts.
It was submitted mostly as a far easier way to highlight the problem compared to navigating the bug reporting process.
For my own usage, installation using `asdf` has proven a better fit.

Note that compiling Couchdb from source requires scripted usage of `epmd` and the current state of the repo makes it impossible to do so. 
Please feel free to close this PR without further action - I will otherwise do so in several days.

**Comment by kencu** [comment]
There is a learning curve to contributing to MacPorts.

Don't be too frustrated. It takes a while to get up to speed.

**Comment by enquora** [comment]
> There is a learning curve to contributing to MacPorts.
> 
> Don't be too frustrated. It takes a while to get up to speed.

I am a core maintainer of a non-trivial open-source project and simply don't have time to "get up to speed".
The bug is a de-facto typo, clearly neither tested nor easily testable.
I does, nevertheless, prevent Couchdb from successfully compiling using MacPorts Erlang.

Additionally, the creation of an additional erts-10.7.2.1 subsystem isn't documented, but suggests this is better left to someone more familiar with the port.

I have no need of credit for fixing this, and am happy for someone with a better understanding of the context to modify and merge or to close un-merged and recreate with supporting tests.
Failing that, I will close myself in a few days.

**Comment by enquora** [comment]
Note also that fixing with a focus on Couchdb is problematic - the Erlang port maintains only a single current version, and couchdb often falls behind supporting the latest Erlang release.

**Comment by kencu** [comment]
> > There is a learning curve to contributing to MacPorts.
> > Don't be too frustrated. It takes a while to get up to speed.
> 
> I am a core maintainer of a non-trivial open-source project and simply don't have time to "get up to speed". 

I understand. 

It would seem that you'd be best off to provide your suggested fixes (which we appreciate) as tickets or opinions and patches attached to tickets, to minimize your frustrations in the future with the trivialities of MacPorts' style of doing commits, etc.

We can then take those from there.

**Comment by kencu** [comment]
Someone will look over your suggestion, test it out, and add a commit in the MacPorts style and with the needed idiosyncratic bits added.

**Pull request closed without merging**
