### PR TITLE
dcc: Submission of new port for the Distributed Checksum Clearinghouses

### PR DESCRIPTION
**Pull request by essandess**
#### Description

dcc: Propose new port for the Distributed Checksum Clearinghouses code

* New port file for https://www.dcc-servers.net/dcc/
* Used for bulk spam detection

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.4 18E226
Xcode 10.2.1 10E1001

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
@essandess, Many thanks for these updates, it’s appreciated you are making them, but I am getting a little tired of asking you to follow our commit guidelines. You need to squash all the commits into one and make sure the commit message follows out guidelines. If you do not know how to correctly rebase and squash commits, I suggest you take the time to learn now, before making any more PRs with the same mistakes.

**Comment by cjones051073** [comment]
OK, I thought I would try and be helpful and make the required changes here, just to show you how you can go about doing what was requested. Note the are a number of ways it can be done, but what I will show below tends to be the way I go about doing this sort of thing.

1. Checkout the branch in question

```
git checkout dcc
```

2. Make sure its up to date with the main master

```
git pull --rebase --autostash origin master
```

Note here I am assuming the main MacPorts repo is called origin. This is the most likely scenario, but you should check for your local clone, which you can do with `git remote -v`

Also note, and this is important, I used the rebase option above. This is to avoid merge commits appearing in the git history, which we do not want.

3. Work out how many commits you need to squash. I tend to do this by first running

```
git log
```

This will show something like

```
Oberon ~/Projects/MacPorts/ports > git log
commit 892b0df28d37059bc490942116d67face1bcd525 (HEAD -> dcc)
Author: Steven Thomas Smith <s.t.smith@ieee.org>
Date:   Tue Apr 30 09:36:05 2019 -0400

    dcc: Add platforms

commit 3810e83f2954c84acca5c221e7cecdb59862440d
Author: Steven Thomas Smith <s.t.smith@ieee.org>
Date:   Tue Apr 30 09:33:53 2019 -0400

    dcc: Add startupitem and don't run as root

commit 3482aeab92bd9ab62475f724c81fef712f30e56f
Author: Steven Thomas Smith <s.t.smith@ieee.org>
Date:   Tue Apr 30 01:10:03 2019 -0400

    dcc: Add platforms

commit 155ad0c164ded9db4e398a8204f7e388747d49b1
Author: Steven Thomas Smith <s.t.smith@ieee.org>
Date:   Tue Apr 30 01:03:06 2019 -0400

    dcc: Propose new port for the Distributed Checksum Clearinghouses code
    
    * New port file for https://www.dcc-servers.net/dcc/
    * Used for bulk spam detection

commit e3e15e81b45c04c4610db0d5ea133c017b9192ae (origin/master, origin/HEAD)
Author: Mojca Miklavec <mojca@macports.org>
Date:   Fri Apr 26 22:05:13 2019 +0200

    MoarVM, nqp, rakudo: update to 2019.03[.1]
    
    Also update website to use https.
    
    Closes: https://trac.macports.org/ticket/58316
<snip>
```

So above, you can see the branch has 4 commits newer than those in origin/master. So its 4 commits we need to squash. 

4. Undo the 4 commits

```
git reset --soft HEAD~4
```

that will un-commit those last 4 commits, and put them back in the staging area. You can then simply re-commit all the changes in one go

```
git commit
```

making sure of course you use a commit message that follows our guidelines. 

After you have done this, the history should look like

```
Oberon ~/Projects/MacPorts/ports > git log
commit 2e1a282d71277938039cf66179e3356d05a942b1 (HEAD -> dcc)
Author: Chris Jones <jonesc@macports.org>
Date:   Tue Apr 30 15:43:15 2019 +0100

    dcc: new port for the Distributed Checksum Clearinghouses code
    
        * New port file for https://www.dcc-servers.net/dcc/
        * Used for bulk spam detection

commit e3e15e81b45c04c4610db0d5ea133c017b9192ae (origin/master, origin/HEAD)
Author: Mojca Miklavec <mojca@macports.org>
Date:   Fri Apr 26 22:05:13 2019 +0200

    MoarVM, nqp, rakudo: update to 2019.03[.1]
    
    Also update website to use https.
    
    Closes: https://trac.macports.org/ticket/58316

<snip>
```

So you can see now there is only one commit newer than `origin/master`.

5. Finally, you need to (force) push the changes back.

```
git push --force essandess dcc
```

The force option is needed as you have rewritten history in the branch.

I hope this is helpful. Please now can you go and make the similar changes needed in a number of other PRs you have open ?

**Comment by essandess** [comment]
@cjones051073 It's not for lack of trying that these commits are not squashed. The `git` infrastructure is far too fragile for this (see all the errors below on multiple reasonable attempts).

I'm perplexed why a single commit would be necessary in the first place.

I'm trying to add working ports, not debug arcane `git` commands.

Example `git` FAIL notes on this PR: https://github.com/macports/macports-ports/pull/4210#issuecomment-487982275:

None of these methods work, and completely destroy my branch.
* https://stackoverflow.com/questions/25356810/git-how-to-squash-all-commits-on-branch
* https://feeding.cloud.geek.nz/posts/combining-multiple-commits-into-one/
* https://markpasc.livejournal.com/189329.html

```
git rebase -i 02403dacfa6d130c48ea75c12c3d4eb70e8e1b57
hint: Waiting for your editor to close the file... error: There was a problem with the editor 'vi'.
Please supply the message using either -m or -F option.
Could not apply d07b17a8ef... apache-solr8: Proposed port of latest solr v.8.0.0 with improved Portfile
```

```
git branch
* (no branch, rebasing apache-solr8)
  apache-solr8
  dcc
  master
  rspamd
```

```
git log -1 --pretty=oneline
f56d3e68f30da4e6399d70dfd3b29651372a11b2 (HEAD) apache-solr8: Proposed port of latest solr v.8.0.0 with improved Portfile

git checkout apache-solr8
Warning: you are leaving 1 commit behind, not connected to
any of your branches:

  f56d3e68f3 apache-solr8: Proposed port of latest solr v.8.0.0 with improved Portfile

If you want to keep it by creating a new branch, this may be a good time
to do so with:

 git branch <new-branch-name> f56d3e68f3

Switched to branch 'apache-solr8'
Your branch is up to date with 'origin/apache-solr8'.

git merge f56d3e68f3
CONFLICT (add/add): Merge conflict in java/apache-solr8/Portfile
Auto-merging java/apache-solr8/Portfile
Automatic merge failed; fix conflicts and then commit the result.
```

Try again…

```
git reset --hard
HEAD is now at d07b17a8ef apache-solr8: Proposed port of latest solr v.8.0.0 with improved Portfile

git rebase -i 02403dacfa6d130c48ea75c12c3d4eb70e8e1b57
fatal: It seems that there is already a rebase-merge directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
	git rebase (--continue | --abort | --skip)
If that is not the case, please
	rm -fr ".git/rebase-merge"
and run me again.  I am stopping in case you still have something
valuable there.

git rebase --abort

git status
On branch apache-solr8
Your branch is up to date with 'origin/apache-solr8'.

nothing to commit, working tree clean

git rebase -i 02403dacfa6d130c48ea75c12c3d4eb70e8e1b57
[detached HEAD 54bbcc4895] apache-solr8: Proposed port of latest solr v.8.0.0 with improved Portfile

git push
To github.com:essandess/macports-ports.git
 ! [rejected]              apache-solr8 -> apache-solr8 (non-fast-forward)
error: failed to push some refs to 'git@github.com:essandess/macports-ports.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

git pull
Merge made by the 'recursive' strategy.

git push
Enumerating objects: 2, done.
Counting objects: 100% (2/2), done.
Delta compression using up to 8 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 598 bytes | 598.00 KiB/s, done.
Total 2 (delta 0), reused 0 (delta 0)
To github.com:essandess/macports-ports.git
   d07b17a8ef..499c902011  apache-solr8 -> apache-solr8
```

**Comment by essandess** [comment]
@cjones051073 I followed the commands you posted above, but there are still multiple commits, as you can see.

Here's what I did:

```
git checkout dcc
Switched to branch 'dcc'
Your branch is up to date with 'origin/dcc'.

git log -1 --pretty=oneline

git reset --soft HEAD~4

git commit

git log -1 --pretty=oneline

git push --force origin dcc
```

I'd encourage MacPorts to add some documentation on how you'd like port submissions to be added. None of the steps you describe are mentioned at https://trac.macports.org/wiki/CommitMessages.

**Comment by cjones051073** [comment]
@essandess you mistake above is you did not run the rebase. That is why the two merge commits are appearing in the history of this PR. Please go back and look again at the steps I posted, and run them *exactly* as I describe. In particular the step

```
git pull --rebase --autostash origin master
```

is not optional.

**Comment by cjones051073** [comment]
> @essandess your mistake above is you did not run the rebase. That is why the two merge commits are appearing in the history of this PR. Please go back and look again at the steps I posted, and run them _exactly_ as I describe. In particular the step
> 
> ```
> git pull --rebase --autostash origin master
> ```
> 
> is not optional.

Note though, the number of commits you need to squash this time will probably be 3, not 4... you need to carefully check this in the `git log` step.

**Comment by essandess** [comment]
Also, I'm hesitant about the necessity of using `--force` to rewrite git history in the process you describe.

MacPorts own  [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages) you get when you issue a PR explicitly disallow this, and for good reason: 

<blockquote>
Publishing this alternate history would require force-pushing, which we ​[disallow](https://help.github.com/articles/about-protected-branches) because it's ​[bad practice](https://git-scm.com/book/en/v2/Git-Branching-Rebasing#The-Perils-of-Rebasing).)
</blockquote>

I'm still very perplexed how MacPorts expects iterative changes to made during PR review, while at the same time expecting a single commit per PR.

**Comment by cjones051073** [comment]
> @cjones051073 I followed the commands you posted above, but there are still multiple commits, as you can see.
> 
> Here's what I did:
> 
> ```
> git checkout dcc
> Switched to branch 'dcc'
> Your branch is up to date with 'origin/dcc'.
> 
> git log -1 --pretty=oneline
> 
> git reset --soft HEAD~4
> 
> git commit
> 
> git log -1 --pretty=oneline
> 
> git push --force origin dcc
> ```
> 
> I'd encourage MacPorts to add some documentation on how you'd like port submissions to be added. None of the steps you describe are mentioned at https://trac.macports.org/wiki/CommitMessages.

The commit guidelines are documented in the "Have you squashed and minimised your commits" link in the description.

https://guide.macports.org/#project.github

Note though, that page is not intended to be a full and complete guide to git. That is beyond what the MacPorts guide is for. Instead it directs you to some external resources, and it is expected that contributors do their own learning to become familiar enough with git to contribute.

**Comment by essandess** [comment]
@cjones051073 I did issue the command `git pull --rebase --autostash origin master`, but simply didn't cut-and-paste that into the comment box. I edited the comment above to reflect this.

Here's what I did:

```
Here's what I did:

```
git checkout dcc
Switched to branch 'dcc'
Your branch is up to date with 'origin/dcc'.

git pull --rebase --autostash origin master
From github.com:essandess/macports-ports
 * branch                  master     -> FETCH_HEAD
Current branch dcc is up to date.

git log -1 --pretty=oneline

git reset --soft HEAD~4

git commit

git log -1 --pretty=oneline

git push --force origin dcc
``````

**Comment by cjones051073** [comment]
> Also, I'm hesitant about the necessity of using `--force` to rewrite git history in the process you describe.
> 
> MacPorts own [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages) you get when you issue a PR explicitly disallow this, and for good reason:
> 
> > Publishing this alternate history would require force-pushing, which we ​[disallow](https://help.github.com/articles/about-protected-branches) because it's ​[bad practice](https://git-scm.com/book/en/v2/Git-Branching-Rebasing#The-Perils-of-Rebasing).)
> 
> I'm still very perplexed how MacPorts expects iterative changes to made during PR review, while at the same time expecting a single commit per PR.

Changing the git history is indeed disallowed in the main master branch. We are not doing this hear, but fixing the commits in your feature branch for a PR, prior to it being merged. 

Squashing commits is very common practise. It is often than changes are requested during the review of the PR, and we do not want each and every little change to have its own commit in this case. Hence the requirement to squash all the changes during the PR review into one commit, such that when the PR is merged there is a single clean commit for it.

So, yes, force push is required in this case. You need to do this.

**Comment by cjones051073** [comment]
can you please run

```
git remote -v
```

and post what that gives. I think the issue here is the names you have used for the various forks are different to what I expected.

**Comment by essandess** [comment]
```
git remote -v
origin	git@github.com:essandess/macports-ports.git (fetch)
origin	git@github.com:essandess/macports-ports.git (push)
upstream	git@github.com:macports/macports-ports.git (fetch)
upstream	git@github.com:macports/macports-ports.git (push)
```

**Comment by cjones051073** [comment]
OK, so I see what is happening...

When you do the rebase, these needs to be from the main repo, not your fork. So in your case you need to run

```
git pull --rebase --autostash upstream master
```

This will rebase your PR branch against the primary upstream master branch.

Then follow on with my commands as above. Make sure again to correctly ID the number of commits to be squashed via the git log.

Then, at the end, you need to push back to your fork, so its

```
git push --force origin dcc
```

**Comment by essandess** [comment]
@cjones051073 Thanks. Trying again:

```
git checkout dcc
Already on 'dcc'
Your branch is up to date with 'origin/dcc'.

git pull --rebase --autostash upstream master
```

Now the commits tab above shows three commits, starting at 02403dacfa6d130c48ea75c12c3d4eb70e8e1b57:
1. 02403dacfa6d130c48ea75c12c3d4eb70e8e1b57
2. 23e1fa5d6c4a2fea54ce67ff49f30425a57e96b9
3. a722b258d3c68553a6dd179fcc8d5e553e3383c2

Should I say this here, then follow as you describe to get these into a single commit?

```
git reset --soft 02403dacfa6d130c48ea75c12c3d4eb70e8e1b57 
```

**Comment by cjones051073** [comment]
b.t.w. what we are discussing here are the steps needed to fix up a PR that already has unwanted multiple commits in it. This is indeed more complicated than what is normally required. 

If you submit a PR, that at the start has a single commit, but then during the course of the review of the PR changes are requested, it is *much* easier to add those to the PR without adding new commits. In this case what I do is simply when committing the required changes, use

```
git commit --amend --no-edit
```

the amend option means 'do not make a new commit, but just add these to the last commit in this branch'. The no-edit option means you do not wish to change the commit message (if you do of course, omit this option).

then it is just

```
git push --force <repo> <branch>
```

to push the changes to git. force is again required as you have changed previous commits. 

So to answer your question above, it is really trivial to make requested changes to PRs during a review, whilst at the same time abiding by our single commit policy.

**Comment by cjones051073** [comment]
> @cjones051073 Thanks. Trying again:
> 
> ```
> git checkout dcc
> Already on 'dcc'
> Your branch is up to date with 'origin/dcc'.
> 
> git pull --rebase --autostash upstream master
> ```
> 
> Now the commits tab above shows three commits, starting at [02403da](https://github.com/macports/macports-ports/commit/02403dacfa6d130c48ea75c12c3d4eb70e8e1b57):
> 
> 1. [02403da](https://github.com/macports/macports-ports/commit/02403dacfa6d130c48ea75c12c3d4eb70e8e1b57)
> 2. [23e1fa5](https://github.com/macports/macports-ports/commit/23e1fa5d6c4a2fea54ce67ff49f30425a57e96b9)
> 3. [a722b25](https://github.com/macports/macports-ports/commit/a722b258d3c68553a6dd179fcc8d5e553e3383c2)
> 
> Should I say this here, then follow as you describe to get these into a single commit?
> 
> ```
> git reset --soft 02403dacfa6d130c48ea75c12c3d4eb70e8e1b57 
> ```

I always use the `HEAD~N` syntax, to avoid having to faff with commit IDs here. So run

```
git log
```

and simply count how many individual commits you wish to roll back. Then just run

```
git reset --sort HEAD~N
```

replacing N with the number you identified.

**Comment by essandess** [comment]
I performed these commands. Now there are two commits and **48** (!) file changes.

This is an extraordinarily fragile process.

```
git checkout dcc
Already on 'dcc'
Your branch is up to date with 'origin/dcc'.

git pull --rebase --autostash upstream master

git reset --soft 02403dacfa6d130c48ea75c12c3d4eb70e8e1b57

git commit

git log -1 --pretty=oneline

git push --force origin dcc
```

**Comment by cjones051073** [comment]
Sorry, but something has now gone very wrong for you now... This PR now has 48 changed files, most of which completely unrelated to this PR... I strongly suspect you rolled back too many commits....

I am going to (again) for push the changes I have locally here, to fix this. Please do *not* over write this in this PR.

**Comment by cjones051073** [comment]
OK, I have corrected things in your githb branch. 

Please run the following in your local checkout of the branch.

```
git fetch --all
git reset --hard origin/dcc
```

that will force your checkout to be exactly what I have pushed.

**Comment by essandess** [comment]
> during the course of the review of the PR changes are requested, it is *much* easier to add those to the PR without adding new commits. In this case what I do is simply when committing the required changes, use `git commit --amend --no-edit`

None of these basic submission steps are documented in the [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)

Would you please make a request to add documentation to avoid issues like this in the future?

**Comment by essandess** [comment]
> OK, I have corrected things in your GitHub branch.

Thank you. Would you please repeat that step for these two other PR's?
* https://github.com/macports/macports-ports/pull/4210
* https://github.com/macports/macports-ports/pull/4201

**Comment by cjones051073** [comment]
> I performed these commands. Now there are two commits and **48** (!) file changes.
> 
> This is an extraordinarily fragile process.
> 
> ```
> git checkout dcc
> Already on 'dcc'
> Your branch is up to date with 'origin/dcc'.
> 
> git pull --rebase --autostash upstream master
> 
> git reset --soft 02403dacfa6d130c48ea75c12c3d4eb70e8e1b57
> 
> git commit
> 
> git log -1 --pretty=oneline
> 
> git push --force origin dcc
> ```

git is powerful. You have to learn how to use it correctly. Yes, it is easy to make mistakes, as you have here. Its also easy to do really great things with git once you get used to it.

**Comment by cjones051073** [comment]
> > OK, I have corrected things in your GitHub branch.
> 
> Thank you. Would you please repeat that step for these two other PR's?
> 
> * #4210
> * #4201

No, you should try and do it yourself. If you have problems I (or someone else) will step in, but better you do it yourself.

**Comment by essandess** [comment]
> you should try and do it yourself. If you have problems I (or someone else) will step in, but better you do it yourself.

I did try, and [documented the multiple errors](https://github.com/macports/macports-ports/pull/4210#issuecomment-487982275).

I am telling you explicitly that I am having problems with these submissions and asking you to format them as you would like.

I'd like to contribute these ports and move on. I've granted edit written to those branches to the maintainers if they'd like to have a working Solr or Rspamd in MacPorts.

**Pull request merged**
