### PR TITLE
gtkglext: avoid name conflict with strings.h func

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [X] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13
Xcode 8.x

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by MarcusCalhoun-Lopez** [comment]
I am afraid I know neither the GitHub handle nor how to look it up.
Any ideas?

**Comment by pmetzger** [comment]
Email them?

**Comment by pmetzger** [comment]
Merged. You might want to email the maintainer anyway, if only to get their handle.

**Comment by MarcusCalhoun-Lopez** [comment]
Thank you for merging this.
I did send an email, but I did not get a response.

**Comment by pmetzger** [comment]
Perhaps we should then do a `port abandoned` ticket?

**Pull request merged**
