### PR TITLE
abseil: update to 20240722.0, fixing MacOS 10.14 build

### PR DESCRIPTION
**Pull request by tuffnatty**
#### Description
 
Updated devel/abseil to 20240722.0, where MacOS 10.14 build is fixed. Revbumped abseil's dependents according to the Portfile note.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G9323 x86_64
Xcode 11.3.1 11C505

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
I will rely on CI for `s2geometry`, but `abseil` itself builds fine for powerpc:
```
  abseil @20240722.0_0 (active) requested_variants='' platform='darwin 10' archs='ppc' date='2024-08-28T15:25:08+0800'
```

**Review by barracuda156 — APPROVED** [review]

**Comment by judaew** [comment]
Failed for `py-grpcio`. @barracuda156, remind me if there was similar behavior in previous versions?

**Comment by barracuda156** [comment]
@judaew I recall those python subports were always a pain, but I am not sure what was the last actual status of those.

**Comment by barracuda156** [comment]
@judaew MacPorts has a really archaic `grpc`, maybe it just has to be updated. I have a newer version locally on my 10.6 ppc, 1.54.2 :)

**Comment by tuffnatty** [comment]
> Failed for `py-grpcio`. @barracuda156, remind me if there was similar behavior in previous versions?

@judaew According to https://ports.macports.org/port/py38-grpcio/details/ , Port Health section, it's been broken already on most platforms.

**Comment by judaew** [comment]
In that case, I think this can be merged, and additional changes can be made later.

**Review by judaew — APPROVED** [review]
LGTM

**Pull request merged**
