### PR TITLE
tmux: update livecheck regex

### PR DESCRIPTION
**Pull request by herbygillot**
Fix livecheck regex for tmux

### CODE REVIEW

**Comment by tessus** [comment]
I can't merge, since I don't have the permissions, but I'm ok with the change.

Although it's not fixing, but adding a livecheck. ;-)

**Comment by herbygillot** [comment]
Thanks @tessus, @kencu

**Comment by ryandesign** [comment]
> Although it's not fixing, but adding a livecheck. ;-)

It's fixing the livecheck, by overriding the default livecheck.

Except that it also breaks livecheck, if the project ever releases a version that does not end with a letter, like it did previously with versions 3.0 and 3.1.

**Comment by herbygillot** [comment]
> > Although it's not fixing, but adding a livecheck. ;-)
> 
> It's fixing the livecheck, by overriding the default livecheck.
> 
> Except that it also breaks livecheck, if the project ever releases a version that does not end with a letter, like it did previously with versions 3.0 and 3.1.

You're right, my fault.  This was why I made it a PR for peer review.

I've fixed it in this commit: https://github.com/macports/macports-ports/commit/ac7f63ec55f26b8356fb37c852340633e13e53d0

**Pull request merged**
