### PR TITLE
openjdk8, openjdk11: Add new port for OpenJDK 8 and migrate OpenJDK 11 to AdoptOpenJDK

### PR DESCRIPTION
**Pull request by breun**
#### Description

The [AdoptOpenJDK](https://adoptopenjdk.net) project will provide longer support for OpenJDK than Oracle going forward, and also provides a GPL-licensed OpenJDK 8.

The `openjdk10` subport still uses Oracle's build, because AdoptOpenJDK does not yet provide a build with the [Mac-native JDK directory layout](https://blog.adoptopenjdk.net/2018/10/macos-binary-changes). It is unclear if this will be made available at some point in the future, since OpenJDK 10 has already reached end of life.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.1 18B75
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Would it be better to name this "openjdk" at this point given that all the versions are under one portfile?

**Comment by breun** [comment]
I believe the directory name needs to match the name of the ‘main’ port? There is no logical ‘main’ port, but I don’t believe there is a way to have all ports be subports?

**Comment by pmetzger** [comment]
Python ports are typically done this way, that is, there are many pyNN-foo ports and there's no actual py-foo port, and yet python/py-foo/Portfile is where they all live.

**Comment by breun** [comment]
I'm not sure that's comparable. When I for instance install `py-yaml`, it does get installed, but installs a specific subport (`py27-yaml`) as a dependency:

```
$ sudo port install py-yaml
--->  Computing dependencies for py-yaml
The following dependencies will be installed: 
 libyaml
 py27-yaml
(...)
$ port installed | grep yaml
  libyaml @0.2.1_0 (active)
  py-yaml @3.13_0 (active)
  py27-yaml @3.13_0 (active)
```

So there is an actual `py-yaml` port, that 'main' port is not something that can be hidden AFAIK.

I would personally prefer to have a separate port file for each major OpenJDK version, because then I think it's way easier to understand what's going on when reading a Portfile, but when I recently submitted my portfiles like that I was told I should use subports.

**Comment by pmetzger** [comment]
You were told by one person to use subports. I agree it isn't necessary. @mf2k was the person in that discussion, right?

**Comment by mf2k** [comment]
I think using openjdk8 is completely fine and so is keeping the sub-ports. The python ports are different and also confusing. Installing py-foo actually installs nothing. It then installs the "real" port like py36-foo. And you are left with a shell py-foo port installed. Then people mistakenly try to use py-foo as a dependency when that does not work.

**Comment by pmetzger** [comment]
@mf2k So, I find it odd to have jdk10 as a subport of the jdk8...

**Comment by breun** [comment]
I do too, but since currently `openjdk11` is already a subport (of `openjdk10`), maybe this pull request can get merged as-is so `openjdk8` will be available in MacPorts?

**Comment by pmetzger** [comment]
@mf2k Do you concur with merging?

**Comment by mf2k** [comment]
I think either option is odd. Having a shell port called openjdk ultimately serves no purpose. Having a subport of openjdk8 called openjdk10 does not seem odd to me at all and it far less confusing to users. 

So yes, I'm good with merging the once the conflicts are resolved!

**Comment by breun** [comment]
Ah, someone updated `openjdk11` to Oracle's OpenJDK 11.0.1 in the meantime and AdoptOpenJDK still needs to do their 11.0.1 release. I'll wait until the AdoptOpenJDK version of OpenJDK 11.0.1 is available (expected this week) and then I'll fix this pull request.

**Comment by cjones051073** [comment]
The `bazel` port requires openjdk10 to build. Have you checked if this port builds correctly with the changes you have made here ? if not, please do this before merging.

**Comment by cjones051073** [comment]
Also, the various `py-tensorflow` ports require the `openjdk11` port to build. Please can you make sure these build properly before merging the changes you propose here to the source of the JDKs.

**Comment by breun** [comment]
@cjones051073 I installed the OpenJDK 11.0.1 from AdoptOpenJDK locally and tried installing `py-tensonflow` and I didn't see any issues during the installation.

**Comment by breun** [comment]
I believe this ready for merging now. The Devoxx conference (big Java conference in Europe) starts tomorrow, would be if I could announce the availability of OpenJDK 8 in MacPorts. :)

**Comment by cjones051073** [comment]
> @cjones051073 I installed the OpenJDK 11.0.1 from AdoptOpenJDK locally and tried installing `py-tensonflow` and I didn't see any issues during the installation.

Just to be clear, you did install from source, and not using the binary tarballs ? If not please uninstall them and then try reinstalling `bazel` and `py36-tensorflow` with

```
sudo port -s install bazel
sudo port -s install py36-tensorflow
```

**Comment by cjones051073** [comment]
Could you attach a complete log for the bazel build failure ?

I agree though, this PR does not change anything w.r.y. JDK 10, so its unclear why its failing for you, but likely not really related to the changes here...

**Comment by cjones051073** [comment]
one little detail. YOur commit message does not mention the change of source for the JDK11. Could you modify the message to explicitly mention this port is being changed and in what way ?

**Comment by breun** [comment]
@cjones051073 It says '(...) switch to AdoptOpenJDK', right?

**Comment by cjones051073** [comment]
The fact it is a sub-port is irrelevant, an implementation detail. The commit messages should explicitly reference all (sub)ports they modify.

**Comment by cjones051073** [comment]
OK, so if you prefer

```
openjdk8, openjdk11: Add new port for JDK8 and migrate JDK11 to AdoptOpenJDK
```

I personally prefer what I first posted, but its up to you. The main point is the changes to openjdk11 need to be explicitly mentioned.

**Comment by cjones051073** [comment]
I cannot reproduce your `bazel` build failure. I think though this really has nothing to do with the PR so I suggest we stop discussing it here. It would be useful if you could open a trac ticket on it though, posting a full clean log file with the failure, where it can be followed up. But I see no reason to have it impact on applying this PR.

**Comment by breun** [comment]
I'd also prefer using separate lines, but have had merge requests rejected in the past because of not following the commit message guidelines. But I'll change it.

**Comment by cjones051073** [comment]
OK, I'm happy with this. Lets roll.

**Comment by breun** [comment]
@cjones051073 I tried installing `bazel` from source again and this time I also couldn't reproduce the error.

**Comment by cjones051073** [comment]
Ok, just gremlins then...

**Comment by breun** [comment]
@cjones051073 I see https://github.com/macports/macports-ports/blob/master/devel/bazel/Portfile depends on `openjdk10` because of incompatibility with OpenJDK 11. Is this still true for OpenJDK 11.0.1? I'd actually like to remove the `openjdk10` port from MacPorts when possible, since OpenJDK 10 is no longer supported with updates.

**Comment by cjones051073** [comment]
Yes, it still does not work with OpenJDK 11.

Please, don't remove the OpenJDK10 port... At least not yet.

**Pull request merged**
