### PR TITLE
sqite3: update to 3.44.0

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with ~`sudo port -vst install`~ `sudo port -d destroot`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by Schamschula** [comment]
I know that the port is marked as `openmaintainer`. This is for the case I'm off line.

However I prefer to update this port myself. I like to make sure all subports work before committing. 

You have only updated `sqlite3`, but forgotten to update `sqlite3-tools`, which has it's own distfiles and needs to be updated at the same time.

**Comment by herbygillot** [comment]
> I know that the port is marked as `openmaintainer`. This is for the case I'm off line.
> 
> However I prefer to update this port myself. I like to make sure all subports work before committing.
> 
> You have only updated `sqlite3`, but forgotten to update `sqlite3-tools`, which has it's own distfiles and needs to be updated at the same time.

Understood - I'll leave it to you. Thanks.

**Comment by pmetzger** [comment]
@Schamschula I assume you'll be updating soon?

**Comment by Schamschula** [comment]
Updated: https://github.com/macports/macports-ports/commit/a89c5cc3cdfb5e0ab5174a87020be0881dcb9d62

**Pull request closed without merging**
