### PR TITLE
gallery: remove unmaintained software's port

### PR DESCRIPTION
**Pull request by kurthindenburg**
This software has not been maintained upstream since 2014.  There
appears no other effects to continue maintaining upstream.  There are
no open tickets and such a complex software needs to be maintained.
The newest version is 3.0.9 at http://galleryproject.org

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Do we have equivalents to use instead?

**Comment by kurthindenburg** [comment]
No, I don't think so - spidereyeballs is the only one I found and it doesn't appear to be a straight replacement.

**Comment by pmetzger** [comment]
No one else seems to have an opinion. I'd give it another day or so before removing it.

**Comment by pmetzger** [comment]
Merged!

**Pull request merged**
