### PR TITLE
uv: Update to 0.1.11

### PR DESCRIPTION
**Pull request by TheRealKeto**
#### Description

Update `uv` to its latest released version, 0.1.11.

###### Tested on

macOS 12.6 21G115 arm64
Command Line Tools 14.2.0.0.1.1668646533

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -d destroot`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
please also update your GitHub handle

**Comment by TheRealKeto** [comment]
> please also update your GitHub handle

@reneeotten What's wrong with the Github handle?

**Comment by reneeotten** [comment]
> @reneeotten What's wrong with the Github handle?

the macportsbot didn't label this PR as originating from the maintainer, which is likely because of the inconsistency between the capitalization.

**Comment by TheRealKeto** [comment]
> > @reneeotten What's wrong with the Github handle?
> 
> the macportsbot didn't label this PR as originating from the maintainer, which is likely because of the inconsistency between the capitalization.

This issue should be addressed in a new PR, as there are other ports I maintain. I think this is the best, but if that hinders this PR from being merged, then I'll do each port when they receive a new update.

**Comment by reneeotten** [comment]
I am pretty sure this isn't the first time this cane up and then you also said you'd do it in another PR, which never happened 😉. So please make the change here for this port since you are updating it already. Others you can do in a separate PR or whenever a port gets updated.

**Pull request merged**
