### PR TITLE
nlohmann-json: update version to 3.7.3

### PR DESCRIPTION
**Pull request by ra1nb0w**
#### Description

- update version to 3.7.3
- add myself as co-maintainer

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.15.3 19D76
Xcode 11.3.1 11C504

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by emcrisostomo** [comment]
Restarting failed Travis CI job, since it seems like a spurious issue.

**Comment by emcrisostomo** [comment]
The restarted job completed successfully.

**Comment by ra1nb0w** [comment]
[7.4.1](https://guide.macports.org/#project.update-policies.nonmaintainer) we should wait 72 hour

**Comment by Lord-Kamina** [comment]
> [7.4.1](https://guide.macports.org/#project.update-policies.nonmaintainer) we should wait 72 hour

Sorry I didn't weigh in because I wasn't at home. And seeing how it's such a trivial modification, *shrugs*

**Pull request merged**
