### PR TITLE
R: new PG and some 150+ ports

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Let us see if this all builds. (Locally it did on PPC.)

@catap @i0ntempest @Schamschula @michaelld Take a look if you got time, please.

`rstan` and `blavaan` model building and sampling works.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

macOS 10A190
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by catap** [comment]
180 commits. I guess this is the record for PR. Isn't it?

**Comment by barracuda156** [comment]
> 180 commits. I guess this is the record for PR. Isn't it?

@catap What to do, R developers write tiny packages, and then to build something actually useful one needs a dozen or more dependencies 🤷🏻‍♂️
Also since we have had none at all, this looks huge. It will be easier after this is merged. Say, to build `BRMS` (perhaps the best thing for Bayesian statistical modeling out there) not much will be needed to add.
(I am not planning to pull every existing R package, I just want a fully functional environment for econometrics and probabilistic modelling.)

**Comment by barracuda156** [comment]
Gimme a few days to deal with this. On a positive side, PG seems to work [mostly] fine. A bit surprising that a number of packages still fail to build on Intel – majority of them needed no patching even on my exotic PPC OS. Few needed fixes for PPC – but they are supposed to work on Intel as-is.

@catap @i0ntempest Any idea what goes wrong?

**Comment by barracuda156** [comment]
- [ ] @andrjohns @wardbrian Just notifying you that I am bring `rstan` to Macports. Finally! PPC builds and seems to work fine (something still links to a wrong `libgcc` which results in a bunch of malloc errors when I start `rstan`, however model compilation and sampling works fine both in Stan directly and in `blavaan` which uses Stan). Still need to fix CI checks here, but we are close to have it all working.

Once @catap and my PRs to `oneTBB` are merged, we can move away from using Rcpp, hopefully, and use external Boost, Eigen and oneTBB.

**Comment by barracuda156** [comment]
@catap Looks like we are getting one error across a number of R packages. Example with `Rcpp`:
```
2022-12-07T20:27:49.0229470Z * installing *source* package ‘Rcpp’ ...
2022-12-07T20:27:49.0893930Z ** package ‘Rcpp’ successfully unpacked and MD5 sums checked
2022-12-07T20:27:49.0894530Z ** using staged installation
2022-12-07T20:27:49.1188160Z ** libs
2022-12-07T20:27:49.1380940Z /opt/local/bin/clang++-mp-14 -std=gnu++14 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/  -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk   -fPIC  -pipe -Os -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64  -c api.cpp -o api.o
2022-12-07T20:27:49.1426400Z /bin/sh: /opt/local/bin/clang++-mp-14: No such file or directory
2022-12-07T20:27:49.1427240Z make: *** [api.o] Error 127
2022-12-07T20:27:49.1435160Z ERROR: compilation failed for package ‘Rcpp’
2022-12-07T20:27:49.1440200Z * removing ‘/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-Rcpp/R-Rcpp/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp’
2022-12-07T20:27:49.1581230Z Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-Rcpp/R-Rcpp/work/Rcpp_1.0.9" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-Rcpp/R-Rcpp/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/library 
2022-12-07T20:27:49.1582300Z Exit code: 1
2022-12-07T20:27:49.1586120Z Error: Failed to destroot R-Rcpp: command execution failed
2022-12-07T20:27:49.1586420Z DEBUG: Error code: CHILDSTATUS 35075 1
```

This ` /bin/sh: /opt/local/bin/clang++-mp-14: No such file or directory` shows up on many instances. Any idea why that happens to err out?

**Comment by barracuda156** [comment]
Let me try blacklisting Apple Clangs and see if LLVM Clang work correctly then.

**Comment by barracuda156** [comment]
@ryandesign Maybe you could suggest how to enforce right compiler? This should have removed Apple clangs from options, AFAIU: https://github.com/macports/macports-ports/pull/16916/commits/bb12086fba729c03e69af366a3408f6bf8243e57
But it did not:
```
2022-12-12T13:36:23.3087180Z DEBUG: Preferred compilers: clang macports-clang-14 macports-clang-13 macports-clang-12 macports-clang-11 macports-clang-10 macports-clang-9.0
2022-12-12T13:36:23.3087680Z DEBUG: Using compiler 'Xcode Clang'
2022-12-12T13:36:23.3089780Z DEBUG: Executing proc-pre-org.macports.configure-configure-0
2022-12-12T13:36:23.3098040Z DEBUG: Active variants check for source-type install considers depends_fetch depends_extract depends_lib depends_build depends_run: R
2022-12-12T13:36:23.3104300Z DEBUG: R is installed with the following variants: +builtin_lapack+cairo+gcc12+openmp+recommended+x11
2022-12-12T13:36:23.3104670Z DEBUG:   required: recommended, forbidden: 
2022-12-12T13:36:23.3105390Z DEBUG:   accepted
2022-12-12T13:36:23.3105790Z DEBUG: Executing org.macports.configure (R-CompQuadForm)
2022-12-12T13:36:23.3190050Z DEBUG: Environment: 
2022-12-12T13:36:23.3190470Z CC='/usr/bin/clang'
2022-12-12T13:36:23.3190750Z CC_PRINT_OPTIONS='YES'
2022-12-12T13:36:23.3191340Z CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-CompQuadForm/R-CompQuadForm/work/.CC_PRINT_OPTIONS'
2022-12-12T13:36:23.3191970Z CFLAGS='-pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64'
2022-12-12T13:36:23.3192340Z CPATH='/opt/local/include'
2022-12-12T13:36:23.3192780Z CPPFLAGS='-I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk'
2022-12-12T13:36:23.3193140Z CXX='/usr/bin/clang++'
2022-12-12T13:36:23.3193610Z CXXFLAGS='-pipe -Os -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64'
2022-12-12T13:36:23.3194080Z DEVELOPER_DIR='/Library/Developer/CommandLineTools'
2022-12-12T13:36:23.3194400Z F90FLAGS='-pipe -Os -m64'
2022-12-12T13:36:23.3194680Z FCFLAGS='-pipe -Os -m64'
2022-12-12T13:36:23.3194960Z FFLAGS='-pipe -Os -m64'
2022-12-12T13:36:23.3195250Z INSTALL='/usr/bin/install -c'
2022-12-12T13:36:23.3196110Z LDFLAGS='-L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64'
2022-12-12T13:36:23.3196640Z LIBRARY_PATH='/opt/local/lib'
2022-12-12T13:36:23.3196930Z MACOSX_DEPLOYMENT_TARGET='12.0'
2022-12-12T13:36:23.3197220Z OBJC='/usr/bin/clang'
2022-12-12T13:36:23.3197650Z OBJCFLAGS='-pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64'
2022-12-12T13:36:23.3198010Z OBJCXX='/usr/bin/clang++'
2022-12-12T13:36:23.3198490Z OBJCXXFLAGS='-pipe -Os -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64'
```

**Comment by barracuda156** [comment]
This “missing” Clang is apparently the only thing that prevents the whole setup from working. Once fixed, we should have R environment building at least from 10.5.8 up, and I can add some extra packages so that _bleeding edge_ statistical modelling tools work (I also want to have complete `devtools` and extra mathematical modules).

**Comment by kencu** [comment]
As it appears that clang-14 is required by R as the build compiler on many systems:

https://ports.macports.org/port/R/details/

The best guess would be that /opt/local/bin/clang++-mp-14 is baked into R somewhere, to be used when building packages.

**Comment by barracuda156** [comment]
> As it appears that clang-14 is required by R as the build compiler on many systems:
> 
> https://ports.macports.org/port/R/details/
> 
> The best guess would be that /opt/local/bin/clang++-mp-14 is baked into R somewhere, to be used when building packages.

I don’t mind it being used on Intel at all, but why build system cannot find it?

**Comment by kencu** [comment]
It's just the way R installs itself. It records it's build compiler, to use when building packages. You have to work around that in some way, probably by adding a runtime dep for the R build compiler.

**Comment by kencu** [comment]
here too, looks like:

Library/Frameworks/R.framework/Versions/4.2/Resources/bin/libtool

**Comment by kencu** [comment]
that's just luck, though. You just need to record the build compiler as a runtime dependency.

Or (much uglier project) strip out all the compiler recording in an R post-destroot phase. This could get messy.

**Comment by kencu** [comment]
There is a possible problem having the R PortGroup recompute the compiler that was likely used to build R and is embedded in the R scripts. Things can change, and the new computed compiler might not in fact be the one that R was built with. In this case, you would get build failures again.

Your block of code to compute the name of the compiler port looks quite good. I haven't tested it, but I suspect it works fine.

However, I am wondering if this block should be in the "R" Portfile, so that it is 100% certain that the compiler used to build R, which is the one embedded in the scripts, is actually the one that is specified as a runtime dependency.

What do you think?

**Comment by barracuda156** [comment]
What is still needed:

– Make sure tarballs are not moved into install location. (I changed destroot at some point in order for its code to sit in PG, turned out it fails to delete tarballs.)
– Fix rpath for `libtbb` from `RcppParallel`, so that `rstanarm` can find it.
– Move compiler selection into R port.
– Implement livecheck for CRAN packages.
– Add a few packages needed for `devtools`.

**Comment by barracuda156** [comment]
Almost there: one more port needs fortran (single error in the latest CI run), and I wanna fix `rstanarm`.

**Comment by barracuda156** [comment]
@kencu @catap It worked!

I will try fixing rpath for rstanarm, that’s the only important package left to add.

@kencu Regarding compiler selection block, do you suggest adding it into R portfile and having it in R PG in a same fashion? That gonna imply blacklist of Apple clangs (which is probably a good move anyway, but just to confirm).

I don’t know how livecheck is done, but will look for examples. How to verify it works correctly though?

**Comment by kencu** [comment]
I suspect the compiler selection block should only be in the R portfile, as it is completely ignored in the R PortGroup anyway (as you saw) because the compiler is baked into the R build files.

I am not sure why Apple clangs are being blacklisted exactly, as (for example) the current Apple clang is clang-14 anyway ... but I don't have time to figure that out, so I will leave that to someone who wants it to work.

**Comment by barracuda156** [comment]
> I suspect the compiler selection block should only be in the R portfile, as it is completely ignored in the R PortGroup anyway (as you saw) because the compiler is baked into the R build files.
> 
> 
> 
> I am not sure why Apple clangs are being blacklisted exactly, as (for example) the current Apple clang is clang-14 anyway ... but I don't have time to figure that out, so I will leave that to someone who wants it to work.

@kencu Without that block in R PG we had a persisting error when Apple clang was used in configure but macports-clang was used by the build and not found.
But I will try having it only in R port – if it gonna fail, it gonna fail pretty fast.

**Comment by kencu** [comment]
> @kencu Without that block in R PG we had a persisting error when Apple clang was used in configure but macports-clang was used by the build and not found. But I will try having it only in R port – if it gonna fail, it gonna fail pretty fast.

Oh, a bit messy -- I can see how that could happen.

**Comment by barracuda156** [comment]
> > @kencu Without that block in R PG we had a persisting error when Apple clang was used in configure but macports-clang was used by the build and not found. But I will try having it only in R port – if it gonna fail, it gonna fail pretty fast.
> 
> 
> Oh, a bit messy -- I can see how that could happen.
> 

Maybe adding a run dependency on the build compiler gonna help.

Re Apple clangs, wonder if they are even used to build R on some systems. From what you said above, it seems that Macports clang is normally picked.

**Comment by barracuda156** [comment]
Looks like a few ports were updated, and CRAN does not retain old versions, so fetch fails. Silly, TBH.

Aside of a few fetch errors, `Rfast` pulls clang-15 and can’t find it. Same issue of mismatching Clangs like before.

That’s it.

I will fix these today–tomorrow, and won’t add any more ports into the PR.
Whatever I wanted, now is here (`rstanarm` should be fixed, plus some time series and math packages added).

I will think of an elegant solution for Clang mismatching, this remains the issue in a sense it is indeed fragile, like @kencu suggested. `Rfast` perhaps tried using different Clang due to C++17 standard added into the portfile: this certainly should not result in a broken build. Need to fix this behavior.

Then, livecheck for CRAN. I will see if I can move CRAN handling into R PG. I wanted to initially, but could not make it work correctly.

**Comment by barracuda156** [comment]
I will probably reset the tree to master and add all commits anew (possibly dropping few ports, so that CI do not fail due to overtime). This will get rid of commits with checksums and fortran fixups and let me avoid changing already added ports: I made some changes to R portgroup, which gonna require slightly different portfile syntax for all R ports.

**Comment by barracuda156** [comment]
UPD. So yeah, I am gonna kill all commits, rebase, add new R PG and then add R ports in several goes. Since I currently have almost 500 ports ready locally, I will leave a half for another PR, otherwise CI fail to complete.

**Comment by barracuda156** [comment]
Okay, let’s see how this works. I will keep this PR to below 100 ports :) Once merged, the rest gonna follow.

**Comment by barracuda156** [comment]
@herbygillot @i0ntempest @michaelld Whomever can take a look at this, please :)

I hope we can merge this batch relatively fast, otherwise I need to keep updating packages – and there are many.

Here I mostly put packages without multiple dependencies, but predominantly those which need compilation. Some of these are rather heavy (my original version of the PR with everything in began to fail on time-out).

I hope in the next go we can have everything else – I got ports ready.

**Comment by barracuda156** [comment]
@herbygillot I would greatly appreciate help with this :) I need a chunk of R ports to be merged first, otherwise everything in one go times out on CIs.

**Comment by herbygillot** [comment]
I think you'll need to rebase this branch on top of the latest master

**Comment by barracuda156** [comment]
> I think you'll need to rebase this branch on top of the latest master

Gimme a min, will do now.

**Comment by barracuda156** [comment]
@herbygillot Checks passed.

**Comment by herbygillot** [comment]
@catap wasn't wrong. This branch is so large that Github isn't allowing for it to be merged through here (github.com).  This branch will need to be manually merged and committed directly via `git`. I will look into doing that soon.

**Comment by barracuda156** [comment]
> @catap wasn't wrong. This branch is so large that Github isn't allowing for it to be merged through here (github.com). This branch will need to be manually merged and committed directly via `git`. I will look into doing that soon.

Thank you! (Now it is 1/4 of what it was, haha.)

**Comment by herbygillot** [comment]
This branch has now been manually committed to `master`, starting with this commit: https://github.com/macports/macports-ports/commit/11ef9629518c3d47d445094be20443d2a3542cda

This PR can be closed.

**Comment by barracuda156** [comment]
@herbygillot Thank you very much! Great.

**Pull request closed without merging**
