### PR TITLE
gretl: update to 2024a

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@mascguy Hmm, any idea why GTK3 may fail on macOS 13?
```
  Building 3 dependencies of gretl:
  Building dependency (1 of 3) 'gtk3' with variants '+x11' ... [FAIL]
Error: Failed to install dependencies for gretl
/Users/runner/work/_temp/4eb12795-7756-458f-88ee-014757c0e065.sh: line 117:  6605 Terminated: 15          tail -f "$workdir/logs/dependencies-progress.txt" 2> /dev/null
```

**Comment by mascguy** [comment]
> @mascguy Hmm, any idea why GTK3 may fail on macOS 13?
> 
> ```
>   Building 3 dependencies of gretl:
>   Building dependency (1 of 3) 'gtk3' with variants '+x11' ... [FAIL]
> Error: Failed to install dependencies for gretl
> /Users/runner/work/_temp/4eb12795-7756-458f-88ee-014757c0e065.sh: line 117:  6605 Terminated: 15          tail -f "$workdir/logs/dependencies-progress.txt" 2> /dev/null
> ```

That may be related to the Xcode version currently being used, or something else entirely. (Per other recent PRs.)

As long as the other three are fine, I'm not too concerned.

**Comment by barracuda156** [comment]
@mascguy Got it, thank you. Then perhaps good to merge.

**Comment by mascguy** [comment]
You may also want to rebase against master, in case the failure for macOS 13 relates to `gstreamer*` ports.

**Comment by barracuda156** [comment]
Let me try.

**Comment by barracuda156** [comment]
@mascguy Awesome, this worked.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
