### PR TITLE
update pymol Portfile to new 2.3.0 release and update py-pmw 2.0.0 for python3.

### PR DESCRIPTION
**Pull request by jwhowarth**
update pymol Portfile to new 2.3.0 release and associated pymol git release checksums.

###### Type(s)

- [ ] bugfix
- [x ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.3 18D109
Xcode 10.1 10B61 

###### Verification 
Have you

- [ x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ x] checked your Portfile with `port lint`?
- [x ] tried existing tests with `sudo port test`?
- [x ] tried a full install with `sudo port -vst install`?
- [ x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
@jwhowarth, any idea why the Azure Pipelines CI failed? (I'm sure Travis won't complete, we can ignore that.)

**Comment by reneeotten** [comment]
the current failure is:
```
Error: Failed to configure pymol: tcl must be installed without +corefoundation.
DEBUG: Error code: NONE
DEBUG: Backtrace: tcl must be installed without +corefoundation.
```
Nevertheless, this should not be merged as is because the update is more than just a version number. There are new/updated [dependencies](https://github.com/schrodinger/pymol-open-source/blob/master/INSTALL) and it seems that those are not taken into account.
For example, ```msgpack-c 2.1.5+``` is now required and a patched version of ```py-pmw``` is needed for the legacy plugins. If ```freeglut``` is installed it needs to be explicitly enabled, ```mmtf-cpp``` is a new dependency, unless disabled with configure arguments, ```catch2``` is needed now for tests. I haven't looked in detail, but to me it seems a larger overhaul of the Portfile is needed; ideally one would also separate the new PyQt from the legacy Tk interface.

**Comment by mf2k** [comment]
The commit message does not follow our standards. It needs to start with the port name. Something like:

`pymol: Update to version 2.3.0
`

Then add a brief description of the changes mentioned by Renee.

**Comment by jwhowarth** [comment]
Separating the pymol package into PyQt and tk variants is still problematic. The APBS Tool plugin requires Tk since it hasn't been rewritten to use pmg_qt so one would lose the ability to run electrostatic calculations via APBS.

**Comment by reneeotten** [comment]
> Separating the pymol package into PyQt and tk variants is still problematic. The APBS Tool plugin requires Tk since it hasn't been rewritten to use pmg_qt so one would lose the ability to run electrostatic calculations via APBS.

that is probably true, but none of the legacy plugins will work with Python 3 anyway. So I would suggest to only support/install the legacy plugins for Python 2.7. The PyQT interface and legacy Tk interface can be separated into variants in case people prefer the old interface on newer Python versions, but in my opinion that should not be the default.

**Comment by jwhowarth** [comment]
I'll look at updating the pmw-py packaging to use the pymol git repository but I'm not really convinced that they have truly made it compatible with python 3.x yet. I suspect that it is just a future WIP thing to triage the orphan-ware pmw.

**Comment by jwhowarth** [comment]
I have tweaked the changes to address the previous complaints but adding the newly required --glut option for the tk interface to work and --use-msgpackc=no to drop the use of the available msgpack2 package. I also added the new dependency for libxml2.

As for pmw-py, I have discovered that we only need to add the upstream pymol change of...

[https://github.com/schrodinger/pmw-patched/commit/c1a52a2712a4671882960b44781b6f4e617454ae](url)

to fix the APBS Tools plugin under python 3.7. The APBS Tools plugin now works fine with pre-generated pqr files under python3 but the use of pqr2pdb is broken as that package isn't python3 compatible yet.  I'll file a bug with the pymol developers and see if they can suggest a patch for that package.

**Comment by jwhowarth** [comment]
I can also confirm that with that single Pmw_2_0_1-py36.patch applied to pmw-py that pymol under the PyQT interface now has a functional legacy APBS Tools plugin. Sweet.

**Comment by jwhowarth** [comment]
Note that I have been leery of updating py-pmw to 2.0.1 as that actually is an upstream alpha release. It was never finished as a real release as the developers went MIA.

**Comment by jwhowarth** [comment]
Just to clarify the situation with pdb2pqr,py used by the pymol APBS Tools plugin. Currently there are python3 patches for pdb2pqr but not for pdb2pka as the scons build system isn't python3 compatible for running the pdb2pqr/pdb2pka test suite under python3.

[https://github.com/Electrostatics/apbs-pdb2pqr/pull/516](https://github.com/Electrostatics/apbs-pdb2pqr/pull/516)

[https://github.com/Electrostatics/apbs-pdb2pqr/pull/440](https://github.com/Electrostatics/apbs-pdb2pqr/pull/440)

We may be able to add these patches to our pdb2pqr package but it will have to be left built against python2.7. This might be sufficient to get pdb2pqr.py to run under python3 for pymol's use.

**Comment by jwhowarth** [comment]
The current changes are all I intend to make to the proposed pymol 2.3.0-0 and py-pmw 2.0.0-1 packaging for now. I had a chance to look at the proposed upstream pdb2pqr changes for python3 support and they are quite incomplete so we can't expect to see that fixed in the short term without a massive rewrite of pdb2pqr. For now, folks using pymol under python3 will just have to use pre-generated pqr files for ABPS Tools.

**Comment by reneeotten** [comment]
thanks @jwhowarth this looks good to me! It appears indeed that one still needs the ```py-tkinter``` to use legacy-plugins even when you use the new Qt interface. So we can keep all of the dependencies for right now and split them up later (I assume that pymol will eventually drop support for the old interface).

Please squash your commits into two separate ones (one for the pymol and one for the py-pmw port) and rephrase the commit messages to better reflect their purpose (as @mf2k also said earlier). After that this should be ready to merge!

**Comment by reneeotten** [comment]
@jwhowarth can you please squash the commits and re-write the messages - besides that it's ready to commit, right?! Otherwise, can someone with commit access (@mf2k or @pmetzger , just because you responded earlier to this PR) take care of this?

**Comment by reneeotten** [comment]
anyone? This has been sitting in the PR queue now for more than a month and the only thing is requires is to squash commits and rewrite the messages, that can't be that hard... @jwhowarth as a maintainer of the port you do have some "obligation" to finish this up and get it merged (at least in my opinion).

**Comment by pmetzger** [comment]
@jwhowarth ??

**Comment by jwhowarth** [comment]
I have been doing all of this from the GitHub web interface and haven't been able to find the claimed 'squash' button described here...

https://help.github.com/en/articles/merging-a-pull-request

Any idea where that is hidden on their web interface?

**Comment by jwhowarth** [comment]
I am wondering if this claimed 'squash' option in the github web interface is only available when merging directly into the target branch and not on the local one?

https://github.blog/2016-04-01-squash-your-commits/

**Comment by jwhowarth** [comment]
Ah, I don't think I can do it myself. See the bottom of...

https://github.com/macports/macports-ports/pull/3639

where it says...

This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests.

It appears squashing can only be done during the actual merging process (which I don't have authority to execute).

**Comment by jwhowarth** [comment]
Oops. You won't see that message because you likely have merge authority already unlike myself.

**Comment by reneeotten** [comment]
I don't know if you're able to do this with the web-interface. There is indeed an option to squash commits when merging a PR, but that's not appropriate here - it's the PR submitter's responsibility to take care of this. 

You can easily do this in a terminal:
```git rebase -i HEAD~4``` will give you the last four commits. You can then change ```pick``` to something else, see descriptions in the interface or [on the web](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History). In this case you'll want to keep two commits, one for the ```pymol``` and one for ```py-pmw``` and change the commit messages (i.e., ```reword````. So select ```reword``` for the two of the commits and choose ```fixup``` for the two commits that you want to combine. That will result in two commits and will give you the change to change the commit messages.

**Comment by jwhowarth** [comment]
Just remove me as maintainer from all of my packages. I really don't have time for this. Thanks in advance.

**Comment by mojca** [comment]
> There is indeed an option to squash commits when merging a PR, but that's not appropriate here - it's the PR submitter's responsibility to take care of this.

I disagree. We should be grateful for any contributions in any form. If the PR author takes care of all those dirty details and nitpicking, it greatly simplifies things for committers of course, but we should not expect from each and every contributor to do stuff they are not comfortable with, and in particular we should not discourage contributors from submitting imperfect stuff that's easy to fix by ourselves.

Now, I try to spend time to nitpick and ask contributors to fix mistakes themselves, so that the same person would not repeat the same mistake in the future, making it faster for everyone to contribute and accept changes in future rounds. But I would prefer to make those fixes myself each time if the PR author is not comfortable doing such changes, it's just that I probably don't know which kind of contributor I'm dealing with. I would also prefer to have "imperfect history" than driving important contributors away.

**Comment by reneeotten** [comment]
@jwhowarth @mojca I am not ungrateful to the contributions at all and I apologize it the first paragraph is interpreted like that! I merely intended to give a description on how to squash the commits and try to move this PR forward - I would be very happy to get this update merged. Of course a committer could take care of this as well, but it appears that nobody feels like doing so for more than a month now... and I cannot do it myself either. It would be ideal if @jhowarth would stay on as a valuable maintainer of his ports and someone with commit access would deal with this PR.

**Comment by pmetzger** [comment]
Generally, I think that if someone can't really navigate git etc., it is probably better for them not to be the maintainer, or to tell us that they'll need help doing the actual maintenance and allowing someone else to co-maintain with them.

**Comment by mf2k** [comment]
Indeed there is nothing difficult being asked here. I didn't know git at all until Macports switched to it.

**Comment by pmetzger** [comment]
Even if it was difficult (which I don't think it is), git is too integrated into our process to avoid. To be effective, a maintainer needs to be able to use it. That said, although it's a little finicky, the parts one needs to know to be an effective maintainer are indeed quickly learned.

**Comment by jwhowarth** [comment]
Okay, the GitHub Desktop app makes this more tolerable. I've started over though and created two new separate pull requests...

https://github.com/macports/macports-ports/pull/3950

and

https://github.com/macports/macports-ports/pull/3949

**Comment by pmetzger** [comment]
Should we be closing this PR then?

**Comment by mojca** [comment]
I can look into it.

**Comment by jwhowarth** [comment]
The py-pmw section that makes it python 3.6+ compatible has been committed. So we only need the https://github.com/macports/macports-ports/pull/3950 pull request to update pymol to the current 2.3.0 release committed.

**Comment by reneeotten** [comment]
the commits in this PR have been merged already in two separate PRs (#3967 and #3950); closing this one.

**Pull request closed without merging**
