### PR TITLE
Update xcrysden to 1.6.2

### PR DESCRIPTION
**Pull request by dstrubbe**
#### Description

Update xcrysden to 1.6.2, which entailed creating a new Togl-2.0 port (since the newer Togl version does not work with this code).

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.12.6 16G2136
Xcode 9.2 9C40b 

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by dstrubbe** [comment]
@MarcusCalhoun-Lopez Are you ok with this approach to the Togl issue?

**Comment by MarcusCalhoun-Lopez** [comment]
I will take a look as soon as I get a chance.

**Comment by mf2k** [comment]
So Togl version 2.0 is specifically required and not 2.1 as provided by the current Togl port? If so, a sub-port of the existing Portfile should be used instead for easier maintenance and to reduce duplication.

**Comment by dstrubbe** [comment]
> So Togl version 2.0 is specifically required and not 2.1 as provided by the current Togl port? If so, a sub-port of the existing Portfile should be used instead for easier maintenance and to reduce duplication.

I agree in principle, but in practice the Portfiles are quite different because the "2.1" version is packaged from a different source than the Togl website. So there isn't much in common between them that would save on maintenance. I created the Togl-2.0 Portfile primarily from the Togl version 1.7 Portfile (with some substantial changes to that too). And yes, only version 2.0 works with this port; I get errors with Togl 2.1 and found a discussion on the XCrySDen email list in which the author says only 2.0 will work.

**Comment by dstrubbe** [comment]
Look good, @MarcusCalhoun-Lopez?

**Comment by dstrubbe** [comment]
> I will take a look as soon as I get a chance.

I guess you haven't gotten a chance. Well, I'll commit in a couple of days unless you have feedback.

**Pull request merged**
