### PR TITLE
py-numexpr: update to 2.8.7; py-numpy: update to 1.26.2, revbump old versions, unbreak < 10.8 

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.1.1
Xcode 15.0.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Failing subports are due to broken `py-numpy` which was broken by `OpenBLAS` update: https://trac.macports.org/ticket/68816

**Comment by reneeotten** [comment]
is this OpenBLAS and NumPy stuff resolved by now so that this can be rebased / merged?

**Comment by barracuda156** [comment]
@reneeotten NumPy is badly broken by the last update and usage of non-Macports meson, but OpenBLAS is almost fine.

I can try rebasing, for CI subset of systems may work.

**Comment by barracuda156** [comment]
@reneeotten Rebased now, let us see.

P. S. For `numpy` I am waiting for one issue to be fixed from upstream side, that can wait since it only affects < 10.8.

**Comment by barracuda156** [comment]
@catap Any idea why this fails for Python 3.8 and earlier?
```
  * Getting build dependencies for wheel...
  Traceback (most recent call last):
    File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/__init__.py", line 23, in <module>
      from . import multiarray
    File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/multiarray.py", line 10, in <module>
      from . import overrides
    File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/overrides.py", line 6, in <module>
      from numpy.core._multiarray_umath import (
  ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 0x0002): Library not loaded: '/opt/local/lib/libopenblas-r1.dylib'
    Referenced from: '/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so'
    Reason: tried: '/opt/local/lib/libopenblas-r1.dylib' (no such file), '/usr/local/lib/libopenblas-r1.dylib' (no such file), '/usr/lib/libopenblas-r1.dylib' (no such file)
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 16, in <module>
    File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/__init__.py", line 141, in <module>
      from . import core
    File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/__init__.py", line 49, in <module>
      raise ImportError(msg)
  ImportError: 
  
  IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
  
  Importing the numpy C-extensions failed. This error can happen for
  many reasons, often due to issues with your setup or how NumPy was
  installed.
  
  We have compiled some common reasons and troubleshooting tips at:
  
      https://numpy.org/devdocs/user/troubleshooting-importerror.html
  
  Please note and check the following:
  
    * The Python version is: Python3.8 from "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8"
    * The NumPy version is: "1.24.1"
  
  and make sure that they are the versions you expect.
  Please carefully study the documentation linked above for further help.
  
  Original error was: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 0x0002): Library not loaded: '/opt/local/lib/libopenblas-r1.dylib'
    Referenced from: '/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so'
    Reason: tried: '/opt/local/lib/libopenblas-r1.dylib' (no such file), '/usr/local/lib/libopenblas-r1.dylib' (no such file), '/usr/lib/libopenblas-r1.dylib' (no such file)
  
  
  ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-numexpr/py38-numexpr/work/numexpr-2.8.7" && /opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m build --no-isolation --wheel --outdir /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-numexpr/py38-numexpr/work 
  Error: Failed to build py38-numexpr: command execution failed
  DEBUG: Error code: CHILDSTATUS 50885 1
```

**Comment by catap** [comment]
Seems you need a revbump of py-numpy

**Comment by barracuda156** [comment]
@catap Ah, it has a zoo of revisions, perhaps some were revbumped and some not.

**Comment by barracuda156** [comment]
@reneeotten Should be good to go. Also fixes builds on <10.8 – until upstream fixed the bug in the script (only relevant for <10.8).

**Comment by catap** [comment]
@barracuda156 I suggest to marked ticked https://trac.macports.org/ticket/68807 as closed by your commit with revbump.

**Comment by barracuda156** [comment]
@catap Done.

@reneeotten Should be good to merge once CI pass (they should, I only edited commit message now).

**Pull request merged**
