### PR TITLE
sane-backends: update to 1.0.31 and fix build error

### PR DESCRIPTION
**Pull request by someuser12**
#### Description

Update sane-backends to 1.0.31 and fix build error due to recent Xcode 12 change
See: https://trac.macports.org/ticket/61362

###### Type(s)

- [x] bugfix
- [x] enhancement

###### Tested on

macOS 10.15.7 19H2
Xcode 12.1 12A7403

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
I was working on this update too. I don't believe your changes are sufficient. For one thing:
```
configure: WARNING: unrecognized options: --without-api-spec, --enable-avahi
```
`--without-api-spec` is gone and `--enable-avahi` changed to `--with-avahi`.

And also:
```
checking whether to enable IPv6... no (couldn't compile test program)
```
In config.log we see this failed because:
```
conftest.c:141:7: error: implicitly declaring library function 'exit' with type 'void (int) __attribute__((noreturn))' [-Werror,-Wimplicit-function-declaration]
          exit(1);
          ^
conftest.c:141:7: note: include the header <stdlib.h> or explicitly provide a declaration for 'exit'
```
So that also needs to be fixed.

I was also going to use the opportunity to rename some of the variants whose names use prefixes that we don't recommend using.

**Comment by amake** [comment]
@ryandesign I think I addressed all the issues. Could you take a look?

Also is there anything I should do to help migrate the variants? Is there any sort of way to signal "variant foo is now bar"?

**Comment by JacquesLB** [comment]
I just tried a new install, but ...no luck. Is it too early for the new patch to be available?

":info:build scanimage.c:1229:42: error: implicit declaration of function 'basename' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
:info:build               png_set_iCCP(*png_ptr, *info_ptr, basename(icc_profile), PNG_COMPRESSION_TYPE_BASE, icc_buffer, icc_size);
:info:build                                                 ^
"
Thanks anyway.

**Comment by amake** [comment]
> I just tried a new install, but ...no luck. Is it too early for the new patch to be available?

As you can see, the PR is not yet merged.

Did you check out this branch, make sure MacPorts has your clone registered as a source, etc.?

**Comment by JacquesLB** [comment]
Sorry, I do no understand your answer. All I do is upgrade outdated ports, then try to install tellico, and answer yes to any question.
What is a "PR"?

**Pull request merged**
