### PR TITLE
godot: update to version 3.2.3

### PR DESCRIPTION
**Pull request by jasonliu--**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.11.6 15G22010
Xcode 8.2.1 8C1002

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
> Port godot **fail** on xcode7.3. [Log](https://paste.macports.org/d5986051a40a)

```
platform/osx/os_osx.mm:785:25: error: use of undeclared identifier 'NSEventSubtypeTabletPoint'; did you mean 'kCGEventMouseSubtypeTabletPoint'?
        if ([event subtype] == NSEventSubtypeTabletPoint) {
                               ^~~~~~~~~~~~~~~~~~~~~~~~~
                               kCGEventMouseSubtypeTabletPoint
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGEventTypes.h:383:3: note: 'kCGEventMouseSubtypeTabletPoint' declared here
  kCGEventMouseSubtypeTabletPoint       = 1,
  ^
platform/osx/os_osx.mm:1878:24: error: use of undeclared identifier 'NSAlertStyleWarning'
        [window setAlertStyle:NSAlertStyleWarning];
                              ^
platform/osx/os_osx.mm:2787:45: error: use of undeclared identifier 'NSOpenGLContextParameterSurfaceOpacity'
                        [context setValues:&opacity forParameter:NSOpenGLContextParameterSurfaceOpacity];
                                                                 ^
platform/osx/os_osx.mm:2794:45: error: use of undeclared identifier 'NSOpenGLContextParameterSurfaceOpacity'
                        [context setValues:&opacity forParameter:NSOpenGLContextParameterSurfaceOpacity];
                                                                 ^
4 errors generated.
```

This indicates source code incompatibilities with macOS 10.11 and earlier. (MacPorts might consider working around these, if there aren't too many other issues, but this likely isn't something this PR needs to address.) `NSEventSubtypeTabletPoint`, `NSAlertStyleWarning`, and `NSOpenGLContextParameterSurfaceOpacity` were formerly known as `NSTabletPointEventSubtype`, `NSWarningAlertStyle`, and `NSOpenGLCPSurfaceOpacity ` in 10.11 and earlier. (@jasonliu-- more ideas for AppKit compatibility layer?)

**Comment by jasonliu--** [comment]
Yes, this is quite possibly another case where my compatibility layer would come into play. Although interestingly, I'm not getting these errors when I compile Godot locally on my 10.11 machine, which admittedly has Xcode 8.2.1 and not Xcode 7.3.

Also, just to be pedantic, and more of a note to myself, all of the enums that @chrstphrchvz listed are ones that were deprecated going from 10.11 to 10.12, except for `NSOpenGLCPSurfaceOpacity` / `NSOpenGLContextParameterSurfaceOpacity`. It's quite possible that this particular enum was deprecated at some point after 10.12.

**Comment by jasonliu--** [comment]
Yes, this is quite possibly another case where my compatibility layer would come into play. Although interestingly, I'm not getting these errors when I compile Godot locally on my 10.11 machine, which admittedly has Xcode 8.2.1 and not Xcode 7.3.

Also, just to be pedantic, and more of a note to myself, all of the enums that @chrstphrchvz listed are ones that were deprecated going from 10.11 to 10.12, except for `NSOpenGLCPSurfaceOpacity` / `NSOpenGLContextParameterSurfaceOpacity`. It's quite possible that this particular enum was deprecated at some point after 10.12.

**Comment by jasonliu--** [comment]
Yes, this is quite possibly another case where my compatibility layer would come into play. Although interestingly, I'm not getting these errors when I compile Godot locally on my 10.11 machine, which admittedly has Xcode 8.2.1 and not Xcode 7.3.

Also, just to be pedantic, and more of a note to myself, all of the enums that @chrstphrchvz listed are ones that were deprecated going from 10.11 to 10.12, except for `NSOpenGLCPSurfaceOpacity` / `NSOpenGLContextParameterSurfaceOpacity`. It's quite possible that this particular enum was deprecated at some point after 10.12.

**Comment by chrstphrchvz** [comment]
> Also, just to be pedantic, and more of a note to myself, all of the enums that @chrstphrchvz listed are ones that were deprecated going from 10.11 to 10.12, except for `NSOpenGLCPSurfaceOpacity` / `NSOpenGLContextParameterSurfaceOpacity`. It's quite possible that this particular enum was deprecated at some point after 10.12.

I had looked at [NSOpenGL.h from 10.12](https://github.com/phracker/MacOSX-SDKs/blob/9fc3ed0ad0345950ac25c28695b0427846eea966/MacOSX10.12.sdk/System/Library/Frameworks/AppKit.framework/Versions/C/Headers/NSOpenGL.h#L282), and `NSOpenGLCPSurfaceOpacity` looked like it too was deprecated in favor of the new `NSOpenGLContextParameterSurfaceOpacity`.

**Comment by jasonliu--** [comment]
Interesting. Apple's own documentation claims that both `NSOpenGLCPSurfaceOpacity` and `NSOpenGLContextParameterSurfaceOpacity` were deprecated at the same time in 10.14:

* https://developer.apple.com/documentation/appkit/nsopenglcpsurfaceopacity
* https://developer.apple.com/documentation/appkit/nsopenglcontextparameter/nsopenglcontextparametersurfaceopacity

Usually, the online documentation is pretty accurate in terms of what version the deprecation occurred, such as the page for `NSWarningAlertStyle`:

https://developer.apple.com/documentation/appkit/nswarningalertstyle

These NSOpenGL constants are a pretty good example of why even creating the version of the AppKit compatibility mapping  file that I currently have was such a headache.

**Pull request merged**
