### PR TITLE
borgbackup: remove already applied patch

### PR DESCRIPTION
**Pull request by vallon**
patch-allow-msgpack-1.0.8 was already applied upstream between 1.2.7 and 1.2.8.  patch ends up assuming it is reversed, and undoes it.

#### Description

Upstream borgbackup applied the changes in the patch-file removed here: https://github.com/borgbackup/borg/compare/1.2.7...1.2.8

Specifically, here: https://github.com/borgbackup/borg/commit/faa0705ddab99e527b8591375df9c999a2e59a69

"port patch" seems to ask "Patch reversed?" (no patch --force or --forward), so it gets undone:

Before:

```
# port patch borgbackup
# grep msgpack /opt/local/.../borgbackup-1.2.8/{setup.py,src/borg/helpers/msgpack.py} | grep '<='
.../setup.py:    'msgpack >=0.5.6, <=1.0.7, !=1.0.1',
.../src/borg/helpers/msgpack.py:    return (0, 5, 6) <= msgpack.version <= (1, 0, 7) and \
```

With this:

```
# port patch borgbackup
# grep msgpack /opt/local/.../borgbackup-1.2.8/{setup.py,src/borg/helpers/msgpack.py} | grep '<='
.../setup.py:    'msgpack >=0.5.6, <=1.0.8, !=1.0.1',
.../src/borg/helpers/msgpack.py:    return (0, 5, 6) <= msgpack.version <= (1, 0, 8) and \
```

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.6.3 22G436 x86_64
Xcode 14.3 14E222b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by vallon** [comment]
The symptom from borg was it complained:

```
Remote: You do not have a supported version of the msgpack python package installed. Terminating.
Remote: This should never happen as specific, supported versions are required by our setup.py.
Remote: Do not contact borgbackup support about this.
```

macports uses msgpack 1.0.8, but borgbackup was confused and checking version <= 1.0.7.

**Comment by ryandesign** [comment]
> patch ends up assuming it is reversed, and undoes it.

Specifically, `patch` on macOS 14 behaves this way. This `patch` program sucks. Anybody submitting updates to MacPorts should probably be using macOS 13 or earlier so that they avoid macOS 14's `patch` program.

**Comment by ryandesign** [comment]
We do have CI machines to verify builds for macOS 11–14 so this would have been caught if the update to 1.2.8 had gone through a pull request, but it didn't; it was committed directly.

Looking at the buildbot status, it failed on macOS 12 and earlier. So maybe it was already macOS 13 that included the new `patch` program.

**Comment by judaew** [comment]
@ryandesign Is it possible to use patch from MacPorts, e.g. `gpatch` port?

**Comment by kencu** [comment]
when I created "diffutils-for-muniversal" to get past issues with "diff" on newer systems, I mentioned in a comment we might need to do the exact same thing for "patch" was has been misbehaving like this for a long time now.

https://github.com/macports/macports-ports/commit/5dccc228b10aff819500672c6f4203da53849dc3

**Comment by vallon** [comment]
> > patch ends up assuming it is reversed, and undoes it.
> 
> Specifically, `patch` on macOS ~14~ 13 behaves this way. This `patch` program sucks. Anybody submitting updates to MacPorts should probably be using macOS ~13~ 12 or earlier so that they avoid macOS ~14~ 13's `patch` program.

That would work for now, but that means 13 is performing some validation that 15 (and potentially beyond) isn't, which would be lost when 13 is dropped.

```patch --forward``` seems to have the required behavior.  It doesn't ask "Patch reversed", and writes failures to *.rej along with non-zero exit:

This snippet demonstrates --forward's behavior.  It never asks "Reversed?", and writes failed (reversed) patches to *.rej:

```
  yes | head -n 20 | cat -n > file0
  sed -e '5s/y/n/' < file0 > file1
  diff -u file0 file1 > patch01
  cp file1 target
  if patch --forward target < patch01 ; then echo ok 01 ; else echo fail 01 ; fi
  sed -e '15s/y/n/' < file1 > file2
  diff -u file0 file2 > patch02
  cp file1 target
  if patch --forward target < patch02 ; then echo ok 02 ; else echo fail 02 ; fi
```

outputs:

```
fail 01
fail 02
```

**Pull request merged**
