### PR TITLE
xulrunner, xulrunner-devel: delete ports

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Ports are outdated, `nomaintainer`, and discontinued upstream.

**Edit:** removed `openvrml +mozilla_plugin` variant due to dependency on XULRunner.

Closes:
https://trac.macports.org/ticket/29556
https://trac.macports.org/ticket/36908
https://trac.macports.org/ticket/39639
https://trac.macports.org/ticket/46571

#### Description
XULRunner was considered experimental and was discontinued by its developer in 2015. Some package managers have already removed XULRunner.

The XULRunner ports were originally created in 2009 for use by the `firefox-x11` and `thunderbird-x11` ports, which were removed in 2014. The XULRunner ports were reportedly difficult to maintain.

Deprecation is another option, but I think deletion may be preferable in this case.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
> Nothing depends on these ports.

However I did find this mention of xulrunner in `openvrml`, I do not know if it is affected:
https://github.com/macports/macports-ports/blob/088c5bbfcfe41d013eb6686ea680cff350ffa5f4/graphics/openvrml/Portfile#L100-L106

**Comment by l2dy** [comment]
> > Nothing depends on these ports.
> 
> However I did find this mention of xulrunner in `openvrml`, I do not know if it is affected:
> 
> [macports-ports/graphics/openvrml/Portfile](https://github.com/macports/macports-ports/blob/088c5bbfcfe41d013eb6686ea680cff350ffa5f4/graphics/openvrml/Portfile#L100-L106)
> 
> Lines 100 to 106 in [088c5bb](/macports/macports-ports/commit/088c5bbfcfe41d013eb6686ea680cff350ffa5f4)
> ```
>  variant mozilla_plugin requires xembed description {Build the Mozilla plug-in} { 
>      depends_lib-append          path:lib/xulrunner/libxul.dylib:xulrunner 
>      configure.args-delete       --disable-mozilla-plugin 
>      configure.args-append       --enable-mozilla-plugin 
>      build.args-append           mozpluginsdir=${prefix}/lib/nsplugins 
>      destroot.args-append        mozpluginsdir=${prefix}/lib/nsplugins 
>  }
> ```

Yes, this variant would be affected. If maintainer approves, we can just delete the variant.

**Comment by chrstphrchvz** [comment]
> > > Nothing depends on these ports.
> > 
> > 
> > However I did find this mention of xulrunner in `openvrml`, I do not know if it is affected:
> > [macports-ports/graphics/openvrml/Portfile](https://github.com/macports/macports-ports/blob/088c5bbfcfe41d013eb6686ea680cff350ffa5f4/graphics/openvrml/Portfile#L100-L106)
> > Lines 100 to 106 in [088c5bb](/macports/macports-ports/commit/088c5bbfcfe41d013eb6686ea680cff350ffa5f4)
> > ```
> >  variant mozilla_plugin requires xembed description {Build the Mozilla plug-in} { 
> >      depends_lib-append          path:lib/xulrunner/libxul.dylib:xulrunner 
> >      configure.args-delete       --disable-mozilla-plugin 
> >      configure.args-append       --enable-mozilla-plugin 
> >      build.args-append           mozpluginsdir=${prefix}/lib/nsplugins 
> >      destroot.args-append        mozpluginsdir=${prefix}/lib/nsplugins 
> >  }
> > ```
> 
> Yes, this variant would be affected. If maintainer approves, we can just delete the variant.

@raphael-st Can the `openvrml +mozilla_plugin` variant be removed due to its dependency on XULRunner?

**Comment by raphael-st** [comment]
> @raphael-st Can the `openvrml +mozilla_plugin` variant be removed due to its dependency on XULRunner?

Yes, you can remove the `+mozilla_plugin` variant of `openvrml`.

**Comment by chrstphrchvz** [comment]
> > @raphael-st Can the `openvrml +mozilla_plugin` variant be removed due to its dependency on XULRunner?
> 
> Yes, you can remove the `+mozilla_plugin` variant of `openvrml`.

Thanks. I have pushed a revised commit to remove it.

**Comment by pmetzger** [comment]
Seems like a good idea to me.

**Pull request merged**
