### PR TITLE
Submission dns-server: named DNS server working configuration

### PR DESCRIPTION
**Pull request by essandess**
Submission dns-server: named DNS server working configuration

* Basic, working, easily modifiable LAN DNS server
* Example LAN, .private, and localhost zones
* A, PTR, and CNAME (alias) records
* MX, SPF, DKIM, and DMARC records for email servers
* URI, TXT, and SRV records for Kerberos servers
* Semi-automated initial configuration using LAN setup

###### Type(s)

- [x] submission
- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.5 18F132
Xcode 10.2.1 10E1001 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
This looks to be a great addition to the port mix. Thanks for the effort!

**Comment by essandess** [comment]
Thanks. macOS Server.app took all the oxygen out of this open source server space while it was a viable server product, but it no longer is, so it’s necessary to stand up a few `*-server` ports. 

We’ve now got `macos-vpn-server`, `clamav-server`, `dns-server`. Next up are `mail-server` and `ccs-calendarserver`.

**Comment by mf2k** [comment]
Per our convention, the commit message should start with the port name. So just remove the "Submission " part at the beginning.

**Comment by essandess** [comment]
Thanks! Done.

**Comment by mf2k** [comment]
Thank you!

**Comment by tobypeterson** [comment]
This port is broken on 10.15, it makes incorrect assumptions about the output of netstat (looks like you want $4).

More generally, the use of shell scripts in this port is... rather objectionable.

**Comment by tobypeterson** [comment]
Pushed a quick fix so I can at least run portindex without errors. Please investigate other ways to get this network info.

**Comment by kencu** [comment]
Perhaps put the scripts in a pre-build block so they aren’t run on a simple port index or port info.

**Comment by raimue** [comment]
Most of the commands are just string operations using `/usr/bin/sed`. There should be no need to use `exec` for those. Please use builtin Tcl commands such as `split`/`join` or the [strsed](https://guide.macports.org/chunked/reference.tcl-extensions.html) extension.

**Comment by mf2k** [comment]
Let's not discuss this on a merged commit. I have created https://trac.macports.org/ticket/58668 for this issue.

**Comment by essandess** [comment]
@mf2k @kencu @tobypeterson @raimue Please see comments/questions at https://trac.macports.org/ticket/58668.

**Pull request merged**
