### PR TITLE
arora: update with upstream patches, revbump

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

All patches are from the upstream master.
(I only skipped Korean locale ones, since they do not apply cleanly, and not essential anyway.)

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
Upstream hasn't updated in many years. Why aren't we just removing this thing?

**Comment by barracuda156** [comment]
> Upstream hasn't updated in many years. Why aren't we just removing this thing?

_It works,_ on some sites it works better than tenfourfox. Not to say it builds quickly, while TFF takes hours on the fastest G5.

**Comment by pmetzger** [comment]
No browser that has been left fallow this long is safe to run; it will inevitably be filled with security vulns.

**Comment by barracuda156** [comment]
> No browser that has been left fallow this long is safe to run; it will inevitably be filled with security vulns.

Refraining to update it does not make things any better.
Everything potentially has security vulnerability, but Fedora and Ubuntu have this browser: https://repology.org/project/arora/versions
There is no reason for us to remove it and no reason not to update it now.

**Comment by barracuda156** [comment]
@pmetzger Thank you!

**Pull request merged**
