### PR TITLE
play: update to 1.5.2, use github portgroup (from #1760)

### PR DESCRIPTION
**Pull request by mojca**
#### Description

This does some further modifications to work started by @slewsys in #1760:
* update to a newer version
* by using the github portgroup, the renaming patch becomes obsolete anyway

I'll remove this port from the mentioned PR. Note that I only changed the PortGroup-related functionality (apart from updating). I did not closely inspect the removed patches or the changes in `destroot`. I really really hope that the maintainer (@ci42) will respond.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G3025
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
I don't have high confidence that @ci42 will respond, but, fwiw, this LGTM.

**Comment by pmetzger** [comment]
Should we be removing play (see #3245) or committing this port? @mojca and @slewsys? I note that @ci42 doesn't seem to be responding particularly quickly so I'll presume they're not that interested.

**Comment by mojca** [comment]
I noticed one (apparently non-fatal) error:
```
javadoc: error - Error fetching URL: https://docs.oracle.com/javase/
```

**Comment by mojca** [comment]
Replying to https://github.com/macports/macports-ports/pull/3245#issuecomment-449635152:
> Looking at #2951, here's my best guess as to what would need to be added to make `play` version 1.5.2 a viable port.
> 
> The [play1](https://github.com/playframework/play1) branch on GitHub is still actively maintained. And version 1.5.2 does appear to work on macOS (10.13 in my case). The problem is that the `play` Python script loads modules relative to the directory containing `play`. See [line 10 in the script](https://github.com/playframework/play1/blob/master/play):
> 
> ```python
> sys.path.append(os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])), 'framework', 'pym'))
> ```
> 
> Under _framework/pym_ are three Python modules: `simplejson`, `yaml` and `play`. The first two can be handled as dependencies upon existing ports. But it seems that the `play` Python module should be installed as well under ${prefix}/Library/Frameworks/Python.framework. Then perhaps line 10 above could be removed and the `play` script itself installed in ${prefix}/Library/Frameworks/Python.framework/Versions/Current/bin/.

I tried to fix the packaging now. However, the code is full of problematic places:
```python
    play_version_file = os.path.join(play_env["basedir"], 'framework', 'src', 'play', 'version')
    if not os.path.exists(play_version_file):
        print "~ Oops. %s file not found" % os.path.normpath(os.path.join(play_env["basedir"], 'framework', 'src', 'play', 'version'))
        print "~ Is the framework compiled? "
        print "~"
        sys.exit(-1)
```

This is consistent with their [README](https://github.com/playframework/play1/blob/c252bb6e9514852f364adf666c0e28bab398cd99/README.textile) file:
```
1. Install the latest version of Play framework and unzip it anywhere you want:
    unzip play-*.zip -d /opt/play
2. Add the play script to your PATH:
    export PATH=$PATH:/opt/play
```
but they are totally lacking the concept of actually installing something via `pip` or in some other similar way. Someone should bring this upstream. It's less than 3000 lines of code, so even porting to python3 is not unthinkable. This should be fixable without too much hassle, if there's interest.

**Comment by pmetzger** [comment]
@mojca So what needs to be done next?

**Comment by cjones051073** [comment]
So,  can we now make any progress on this ?

**Comment by pmetzger** [comment]
I worry that this PR is going to survive to its first birthday. That wouldn't be a good thing.

**Comment by pmetzger** [comment]
Might I suggest that maybe this be closed until such time as someone has time to work on it?

**Comment by mojca** [comment]
Between uselessly outdated version (which might not be fully functional either) and somewhat broken newer version I somewhat favour the latter, so simply merging and addressing the remaining problems later?

**Comment by pmetzger** [comment]
Yes. That seems reasonable.

**Pull request merged**
