### PR TITLE
meld: upgrade to new app PG features, and update to 3.18.1

### PR DESCRIPTION
**Pull request by kencu**
###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 10K549
Xcode 4.2 4C199 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

This is the first port I'll try updating to the new app PG features. I added a separate commit to upgrade the port as well, to force a rebuild / reinstall.

It fixes the app launch on some systems that error out with the "-p" flag sent (like mine), by using the launch script option.

It hides the dock icon with the x11 build to prevent it bouncing forever. 

It defaults to x11 because that's what gtk2 and gtk3 do. That might cause some issue if the user previously had `meld` installed without any variants (as there were none before), and wants `+quartz`. Any way around this?

Looking for opinions on this style, what errors might there there be in this logic, and the usual eyeballs on the process, esp @ryandesign .

I don't see how to make this much simpler. I had wondered if some of this might be put into the app PG itself, but I guess not.

If this one works out, I'd like to do pan2, and then others if everyone likes this...

### CODE REVIEW

**Comment by ryandesign** [comment]
> It fixes the app launch on some systems that error out with the "-p" flag sent (like mine), by using the launch script option.

You mean the `-psn_######` flag, added by OS X 10.8 and earlier, IIRC.

> It defaults to x11 because that's what gtk2 and gtk3 do. That might cause some issue if the user previously had meld installed without any variants (as there were none before), and wants +quartz. Any way around this?

I don't think there should be any problem here. The user who wants +quartz already has that in their variants.conf, and this updated port will respect that when the user upgrades.

> Looking for opinions on this style, what errors might there there be in this logic, and the usual eyeballs on the process, esp @ryandesign .

Looking at the changes visually, they seem logical to me. I haven't tried to install it, and I haven't used the `app.use_launch_script` or `app.hide_dock_icon` options.

> I don't see how to make this much simpler. I had wondered if some of this might be put into the app PG itself, but I guess not.

Which part? I suppose it might be nice to "[hide] the dock icon with the x11 build to prevent it bouncing forever" automatically for any x11 variant, since the problem is likely to affect all ports when using that variant. That could be accomplished by changing the default value of `app.hide_dock_icon` to something like:

    default app.hide_dock_icon  {[variant_exists x11] && [variant_isset x11]}

**Comment by kencu** [comment]
Yes -- I was trying to find an elegant way to include the app.icon hiding logic in the PG for gtk2 or gtk3 ports without affecting any other ports (that may not use gtk2 or gtk3) from having their doc icon messed with. 

But in the end I think it probably needs to be done on a port-by-port basis, to avoid messing with the QT ports and all the other non-gtk ports...

**Comment by kencu** [comment]
what I was thinking was that some user might have `+x11` in his variants.conf or somehow gets it into the equation, and then installs a qt5 port that uses the app PG, and finds there is no dock icon and has no idea why not .... but maybe that's too much corner case to worry about ...

is that even possible? Can you set a variant like `+x11` on a port that doesn't inherently recognize that variant?

**Comment by ryandesign** [comment]
>     default app.hide_dock_icon  {[variant_exists x11] && [variant_isset x11]}

This only sets the default to `yes` if the x11 variant exists in the port and the user has selected it.

**Comment by kencu** [comment]
Ah -- yes, then, that should fix it if we put it in the PG. Would avoid duplicating the same code over and over. I can't come up with a downside to that.

**Comment by kencu** [comment]
I tried Ryan's portgroup enhancement, but I'm getting errors about the variable not being defined. We will work through this, but for now I think we can commit this PR and get things moving, for at least one to test. I truly hope it works as well for everyone else as for me.

**Comment by kencu** [comment]
OK. It works as it should on my end, with an x11 install. Using the launch script may have some unforeseen effects that I don't know about yet -- for example, do quartz apps respond to files dropped or dragged onto the icons at launch or after they are open? If so, then this may not work correctly. It could be that the launch script is only suitable for x11 apps in the end. Please report back any findings or issues, so I/we can tweak this until it's as good as we can make it.

**Comment by kencu** [comment]
Oh-oh. On another system (MacPro 10.13) I just installed this (using +x11) and I'm seeing an Abort Trap 5 error when I run it (from the command line or from the app)... I hope this is just something specific to my machine here...

**Pull request merged**
