### PR TITLE
tDOM: update to 0.9.1

### PR DESCRIPTION
**Pull request by kurthindenburg**
Move to tdom.org since github repo has not been updated in years

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kurthindenburg** [comment]
I likely should do a maintainer abandonment for this and his other ports.

**Comment by pmetzger** [comment]
> I likely should do a maintainer abandonment for this and his other ports.

You mean wu.ac.at:neumann?

**Comment by pmetzger** [comment]
Anyway, LGTM, we have to wait the three days though.

**Comment by kurthindenburg** [comment]
Yes, I didn't see any recent activity from the maintainer.

**Comment by pmetzger** [comment]
@kurthindenburg You should also file an abandonment ticket.

**Comment by gustafn** [comment]
interestingly, the updated port builds fine locally, but not by the build-bots (see e.g.
https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/33435/steps/install-port/logs/stdio) It seems that it does not find the "configure" file, although this is included in the .tgz file. Is this a hickup with the built-bot, or is some magic missing to make this work?

**Comment by kurthindenburg** [comment]
I vaguely recall something about the buildbots are on case-sensitive filesystems.

On my local systems the folder is tdom-0.9.1, on buildbot tDOM-0.9.1

I don't know  how to resolve ATM

**Comment by gustafn** [comment]
interesting!
maybe: 
   worksrcdir tdom-${version}

The upstream tar files is nowadays just lower case.

**Comment by kurthindenburg** [comment]
Thanks for the note, I forget to check the build bots at times.  It looks like it worked.

https://build.macports.org/builders/ports-10.13_x86_64-watcher/builds/8583

**Comment by pmetzger** [comment]
Can we get the `maintainers` line for this port updated?

**Comment by kurthindenburg** [comment]
Is neumann@wu.ac.at still valid for you?  I can add gustafn  and openmaintainer to the 3 ports if that's fine with you.

**Comment by gustafn** [comment]
yes, this email address is still working. no objection for openmaintainer for the three ports.
So far i have not made any updates for the "new" github infrastructure, have not looked at the new procedures in detail ... but i will do so soon, since nsf 2.2 is ante portas... 

greetings from greece (vacation).

**Pull request merged**
