### PR TITLE
emacs-app: update inline patch

### PR DESCRIPTION
**Pull request by l2dy**
#### Description
https://qiita.com/takaxp/items/e07bb286d80fa9dd8e05

> 最後に，locateが en で，Google IME を使う人は，次を（パッチが違います）

Google Translate: Finally, if locate is en and who uses the Google IME, (patch is different)

So the generic inline patch is https://gist.github.com/takaxp/3314a153f6d02d82ef1833638d338ecf, not https://gist.github.com/takaxp/5294b6c52782d0be0b25342be62e4a77.

### CODE REVIEW

**Comment by pmetzger** [comment]
What does this patch do?

**Comment by l2dy** [comment]
@pmetzger Partly for https://debbugs.gnu.org/cgi/bugreport.cgi?bug=23412, from the NOTE1 mail thread mentioned in https://qiita.com/takaxp/items/e07bb286d80fa9dd8e05.

**Comment by pmetzger** [comment]
Wouldn't it be better to get that upstreamed than to apply it here?

**Comment by l2dy** [comment]
The inline patch was added 6 years ago in 398fd73cf82310c0d8a76d9ca245f2bf19d1cf34. I'm just fixing the patch incorrectly updated in 36b60fd44e67f7655e00994280c8915f715f2d5b.

**Comment by wyuenho** [comment]
I just looked at the patches again, you are right. Apologies for the mistake.

**Comment by l2dy** [comment]
BTW, @wyuenho Why did you switch the patch upstream? Just because it's newer than the old one, or that you can actually benefit from some changes in the new patch?

**Comment by wyuenho** [comment]
Mostly just because it's newer, there are a couple of offset and whitespace changes, and it's the one recommended by the blog post. The old patch will still apply if you prefer to roll back.

**Comment by l2dy** [comment]
@drkp We need your input here, is this PR ready to be merged?

**Comment by pmetzger** [comment]
@drkp ?

**Comment by drkp** [comment]
This seems fine, but I would actually prefer to remove this patch entirely, unless anyone objects strongly. If nothing else, we should make it non-default.

I am troubled by the fact that we are basically applying a patch from blog posts where we can't keep track of the latest version (perhaps because I don't read Japanese?).

**Comment by pmetzger** [comment]
I'm good with removing it. If it's worth having, it's worth the upstream applying it, not us.

**Comment by l2dy** [comment]
I prefer removing it too, because it is claimed that "In Emacs 24.4 and later, inline input is possible without applying any patches" in https://ja.osdn.net/projects/macemacsjp/lists/archive/users/2017-April/001756.html. However, I propose adding the following short patch as a variant to address https://debbugs.gnu.org/cgi/bugreport.cgi?bug=23412.

[emacs-25.x-flicker-prevention-patch](https://osdn.net/projects/macemacsjp/releases/p15426)

```
$ cat patch-emacs-25.x-flicker-prevention.diff
diff -uprN emacs-25.1.org/src/keyboard.c emacs-25.1/src/keyboard.c
--- src/keyboard.c	2016-08-02 17:06:01.000000000 +0900
+++ src/keyboard.c	2017-04-17 00:47:59.000000000 +0900
@@ -2467,10 +2467,8 @@ read_char (int commandflag, Lisp_Object
 	swallow_events (false);		/* May clear input_pending.  */

       /* Redisplay if no pending input.  */
-      while (!(input_pending
-	       && (input_was_pending || !redisplay_dont_pause)))
+      while (!input_pending)
 	{
-	  input_was_pending = input_pending;
 	  if (help_echo_showing_p && !EQ (selected_window, minibuf_window))
 	    redisplay_preserve_echo_area (5);
 	  else
```

**Comment by wyuenho** [comment]
You know, funnily enough, I can't reproduce the bug described at all on 10.13 with Traditional and Simplified Chinese IMEs. Does anyone have older Macs to test if this is an OS issue or Emacs issue? If this bug can't be reproduced anymore, we can remove the patch.

**Comment by wyuenho** [comment]
In any case, I support removing it, it's not something MacPorts should attempt to deal with unless MacPorts can't build it without patching.

**Comment by l2dy** [comment]
Closing because everyone seems to agree that the inline patch should be removed.

**Pull request closed without merging**
