### PR TITLE
MoarVM: enable mimalloc support in a separate variant

### PR DESCRIPTION
**Pull request by aeiouaeiouaeiouaeiouaeiouaeiou**
#### Description

https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/197004/steps/install-port/logs/stdio
https://developer.apple.com/documentation/kernel/mach_task_basic_info_t

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 10K549 x86_64
Xcode 3.2.6 10M2518

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by barracuda156 — CHANGES_REQUESTED** [review]
@aeiouaeiouaeiouaeiouaeiouaeiou While I do not know whether we _need_ `mimalloc`, I suggest to do the following:

1. Make it an explicit variant instead of a sneaky configure arg.
2. Set the variant as default on whichever systems you would like to.
3. Actually fix `mimalloc` variant for older systems, API is there, FWIU, just naming differs: https://developer.apple.com/documentation/kernel/task_basic_info_t

We do not have to make it default for legacy systems though.

I can handle #3, could you take care of the variant? (Subsequent fix for #3 will not require a revbump.)

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@barracuda156 sounds good while I'm busy but I'll fix it.

**Comment by barracuda156** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou Maybe do it straightforward? It is a bit counter-intuitive to have a variant to remove a feature. What I meant is make `+mimalloc` the default for new systems, but not for old. Then I can see if mimalloc variant will be fixable for old systems (but I do not intend make it a default there at the moment).

**Review by barracuda156 — APPROVED** [review]

**Comment by barracuda156** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou Thank you!

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@herbygillot @reneeotten @pmetzger

**Comment by barracuda156** [comment]
P. S. I guess, we need a revbump though, since either way the build will differ from before. Not a big deal for MoarVM, it builds fast even on legacy systems.

**Comment by reneeotten** [comment]
> P. S. I guess, we need a revbump though, since either way the build will differ from before. Not a big deal for MoarVM, it builds fast even on legacy systems.

so why would one leave it enabled (i.e., as a default variant) for newer systems? If you'd do that then there is no need for a `revbump` and the status quo hasn't changed.

**Comment by barracuda156** [comment]
@reneeotten I am fine with either enabling (for newer systems only) or not enabling (generally).
If no revbumping required, then it is good to merge.

**Comment by reneeotten** [comment]
sorry I meant *not* enabled above.. Right now the build is different on newer systems with this PR and it seems that there is no real reason for that.

**Comment by barracuda156** [comment]
> sorry I meant *not* enabled above.. Right now the build is different on newer systems with this PR and it seems that there is no real reason for that. 

I am indifferent regarding having mimalloc used or not on newer systems, since I have no idea what benefits we get.
(At the moment it should not be used on older systems, clearly.)

I would like to have it via a variant though, since it allows a user to know whether it is enabled and control the behavior in this regard, which is an improvement over silent and unilateral modification of configure args.

**Comment by barracuda156** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou @reneeotten By the way, apparently it used bundled `mimalloc` instead of MacPorts one, why? No surprise it is broken, since we have fixes for it which are only partly merged to upstream (and I have no idea which version MoarVM bundle).

There may be a good reason to use bundled version (see an issue with libuv), so I do not imply it _must_ be switched to MacPorts one. But if a bundled is used, perhaps we should port our patches. (This I can deal with myself.)

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@barracuda156 @reneeotten the main reason for this PR was to fix the build on macOS <10.8. I force-pushed three different commits here, so which one should be cherry-picked in the end (each of them builds fine)?

**Review by barracuda156 — APPROVED** [review]

**Comment by barracuda156** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou I am okay with the current commit, but I cannot merge anything, no commit access.

**Comment by reneeotten** [comment]
> @aeiouaeiouaeiouaeiouaeiouaeiou I am okay with the current commit, but I cannot merge anything, no commit access.

If you want to stick to this then you'll have to increase the `revision` as you've now changed the build/behavior on newer systems where before this PR `mimalloc` was enabled. Again, I don't really care what you decide but the current commit isn't correct and can thus not be merged.

**Comment by barracuda156** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou Could you please revbump and squash commits? Nothing else to change, we just need to increase revision as @reneeotten says.

**Pull request merged**
