### PR TITLE
oauth2-proxy: new port

### PR DESCRIPTION
**Pull request by herbygillot**
- fixes: https://trac.macports.org/ticket/60948

###### Tested on

macOS 10.15.6 19G73
Xcode 11.6 11E708

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -d install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
That was quick, thanks!

Your Portfile has the standard modeline which states indentations are at multiples of 4 spaces, but the file doesn't actually follow that.

I notice you used a custom launchd plist and custom notes to tell the user about it. We of course want the MacPorts launchd plist creation method to be suitable for most ports, though I know it presently has some deficiencies. What was missing with it that didn't work for this port?

**Comment by herbygillot** [comment]
> That was quick, thanks!

No worries

> Your Portfile has the standard modeline which states indentations are at multiples of 4 spaces, but the file doesn't actually follow that.

I will fix

> I notice you used a custom launchd plist and custom notes to tell the user about it. We of course want the MacPorts launchd plist creation method to be suitable for most ports, though I know it presently has some deficiencies. What was missing with it that didn't work for this port?

Support for setting `UserName` and `GroupName` in the plist.  I had planned on adding this functionality to `macports-base` but was running into a complete lack of infra for unit testing it.  I can take another look in time, but the problem is also that I don't know at which macOS version specifically `launchd` started to support the `UserName` and `GroupName` options.

**Comment by ryandesign** [comment]
> which macOS version specifically `launchd` started to support the `UserName` and `GroupName` options

I think it's always been there. [This unofficial reference](https://www.manpagez.com/man/5/launchd.plist/osx-10.4.php) shows it existing in 10.4, which was the first version to have launchd.

**Comment by herbygillot** [comment]
> > which macOS version specifically `launchd` started to support the `UserName` and `GroupName` options
> 
> I think it's always been there. [This unofficial reference](https://www.manpagez.com/man/5/launchd.plist/osx-10.4.php) shows it existing in 10.4, which was the first version to have launchd.

OK, sounds good.

**Pull request merged**
