### PR TITLE
py-cryptography2: Move py-cryptography to py-cryptography2

### PR DESCRIPTION
**Pull request by essandess**
py-cryptography2: Move py-cryptography to py-cryptography2

* Create py-cryptography2 port for legacy support of outdated version 2.9.2
* Remove EOL Python 35
* See #10835 for updated py-cryptography version
* Update the ports:
    *  `port echo depends:py27-cryptography`
    *  `port echo depends:py35-cryptography`

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by amake** [comment]
This PR will conflict with #10835 because it deletes the py-cryptography Portfile. It also can't be merged until #10835 is merged because it removes py-cryptography entirely, which will break any ports not switching to py-cryptography2.

If you restored the py-cryptography Portfile as-is in this PR then this could go in at any time and wouldn't conflict.

**Comment by essandess** [comment]
> This PR will conflict with #10835 because it deletes the py-cryptography portfile. It also can't be merged until #10835 is merged because it removes py-cryptography entirely, which will break any ports not switching to py-cryptography2.
> 
> If you restored the py-cryptography Portfile as-is in this PR then this could go in at any time and wouldn't conflict.

@reneeotten requested that this be a separate PR: https://github.com/macports/macports-ports/pull/10835#issuecomment-830490674

These issues are easily rwsolved by adding #10835‘s commits to this PR. Is this approach agreeable to everyone?

**Comment by amake** [comment]
The suggestion was to make a new py-cryptography2 port. That doesn't mean you have to remove the existing py-cryptography in the same PR.

**Comment by Schamschula** [comment]
Why can't you pin the unsupported Python versions to the older version of py-cryptography? We do this al the time.

**Comment by amake** [comment]
> Why can't you pin the unsupported Python versions to the older version of py-cryptography? We do this al the time.

@essandess was requested to do so in https://github.com/macports/macports-ports/pull/10835#issuecomment-830490674

But I agree:

- We have plenty of Python ports that pin different library versions for different Python versions
- This naming convention conflicts with any future `cryptography2` library, which is a not-uncommon naming scheme

**Comment by essandess** [comment]
> Why can't you pin the unsupported Python versions to the older version of py-cryptography? We do this al the time.

I did this originally, but followed @reneeotten’s request to have a separate Portfile: https://github.com/macports/macports-ports/pull/10835#issuecomment-830490674

For posterity, a Portfile that does this: https://github.com/macports/macports-ports/compare/ac42fce40d8602288cb276144acfb414d22e79ea..b4f1fb7b78b1d88f35bbe88bf34a7176a0fddac8

This would be my preference. Should we go back to this approach?

**Comment by essandess** [comment]
> The suggestion was to make a new py-cryptography2 port. That doesn't mean you have to remove the existing py-cryptography in the same PR.

This may be trivially addressed once the larger conflicting suggested approaches are sorted out.

**Comment by essandess** [comment]
@am

> > Why can't you pin the unsupported Python versions to the older version of py-cryptography? We do this al the time.
> 
> I did this originally, but followed @reneeotten’s request to have a separate Portfile: [#10835 (comment)](https://github.com/macports/macports-ports/pull/10835#issuecomment-830490674)
> 
> For posterity, a Portfile that does this: https://github.com/macports/macports-ports/compare/ac42fce40d8602288cb276144acfb414d22e79ea..b4f1fb7b78b1d88f35bbe88bf34a7176a0fddac8
> 
> This would be my preference. Should we go back to this approach?

@amake @Schamschula @reneeotten I will go back to this approach and move the commits from this PR to #10835 in 1–2 days unless I hear further comment, then close this PR.

**Comment by reneeotten** [comment]
> > I did this originally, but followed @reneeotten’s request to have a separate Portfile: [#10835 (comment)](https://github.com/macports/macports-ports/pull/10835#issuecomment-830490674)
> > For posterity, a Portfile that does this: https://github.com/macports/macports-ports/compare/ac42fce40d8602288cb276144acfb414d22e79ea..b4f1fb7b78b1d88f35bbe88bf34a7176a0fddac8
> > This would be my preference. Should we go back to this approach?
> 
> @amake @Schamschula @reneeotten I will go back to this approach and move the commits from this PR to #10835 in 1–2 days unless I hear further comment, then close this PR.

I personally don't think that's a good idea. In the commit you mention you pretty much copied the original Portfile as `py-cryptography2` in a subport in the `py-cryptography` Porfile. If you want to generate a new `py-cryptography2` (sub)port than it should be in a separate file as you did here (IMHO). 

If I read @Schamschula and @amake their comments correctly, I *think* they suggest to not rename the port at all but just limit it to an older version for the PY27 subport or when installing on an earlier system. In that case the name would just remain `py-cryptography` and you wouldn't need to change any of the ports that depend on it. That would be a fine approach as well.

**Comment by Schamschula** [comment]
> If I read @Schamschula and @amake their comments correctly, I _think_ they suggest to not rename the port at all but just limit it to an older version for the PY27 subport or when installing on an earlier system that do not support `rust`. In that case the name would just remain `py-cryptography` and you wouldn't need to change any of the ports that depend on it. That would be a fine approach as well.

Correct!

**Comment by essandess** [comment]
> > If I read @Schamschula and @amake their comments correctly, I _think_ they suggest to not rename the port at all but just limit it to an older version for the PY27 subport or when installing on an earlier system that do not support `rust`. In that case the name would just remain `py-cryptography` and you wouldn't need to change any of the ports that depend on it. That would be a fine approach as well.
> 
> Correct!

Okay, got it. Sounds like a good approach.

**Comment by essandess** [comment]
Done. This PR is superseded by [force-push](https://github.com/macports/macports-ports/compare/4c5a2dc81bd8e7d944a663db03ead00ab3502527..4a111a52bcfed9211c5a11b25c7db175d0ff2504) in #10835 and may be closed.

**Pull request closed without merging**
