### PR TITLE
rust: update to 1.83.0

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with ~`sudo port -vst install`~ `sudo port -d install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mascguy** [comment]
Herby, are you going to update `cargo-c` as well? That looks outdated as well:

```
$ port -v livecheck cargo-c
cargo-c seems to have been updated (port version: 0.10.4, new version: 0.10.7)
```

**Comment by herbygillot** [comment]
> Herby, are you going to update `cargo-c` as well? That looks outdated too:
> 
> ```
> $ port -v livecheck cargo-c
> cargo-c seems to have been updated (port version: 0.10.4, new version: 0.10.7)
> ```

Good catch. Will merge this update in, then open a new PR for that.

**Comment by mascguy** [comment]
It looks like there are a lot of failures across older macOS releases, blocking a lot of ports from building.

So I'm wondering if we should be utilizing Devel ports for Rust and Cargo, to pre-validate these updates?

**Comment by mascguy** [comment]
> It looks like there are a lot of failures across older macOS releases, blocking a lot of ports from building.
> 
> So I'm wondering if we should be utilizing Devel ports for Rust and Cargo, to pre-validate these updates?

Hmmm, actually the builds look good (apart from 10.6), something failed during mirroring. So never mind. Lol

**Comment by herbygillot** [comment]
> It looks like there are a lot of failures across older macOS releases, blocking a lot of ports from building.
> 
> So I'm wondering if we should be utilizing Devel ports for Rust and Cargo, to pre-validate these updates?

macOS 10.12 and below are pegged to an older version of Rust, so there's been no change there for quite a while.

The failures you saw weren't failures building Rust, but failures _mirroring_ it due to some legacy compiler blacklist issues.  I think Ryan had opened a ticket on this, I need to follow up.

**Pull request merged**
