### PR TITLE
apr-util: use the right compiler

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
See https://trac.macports.org/wiki/UsingTheRightCompiler

No revbump since installed files do not change.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by danielluke** [comment]
Can you include information on the failure you saw (and how this fixes it?) - This again looks OK, but I want to make sure I understand when this was needed/why this is the first I've heard of this problem with the port.

Thanks.

**Comment by MarcusCalhoun-Lopez** [comment]
I have my system set up to [test](https://trac.macports.org/wiki/UsingTheRightCompiler#testing) that `${configure.cc}` is being respected.
Without `CC = @CC@`, the value of `CC` defaults to `cc` instead of the desired `${configure.cc}`.
This triggers an error from the fake [cc](https://trac.macports.org/browser/users/ryandesign/no_default_gcc/cc).

**Comment by danielluke** [comment]
Do you have the build error handy? We'll want to report this upstream too and I find it way easier to work back from the failed build log than to dig through the autoconf stuff directly.

**Comment by MarcusCalhoun-Lopez** [comment]
The error message is very MacPorts centric, but it is

```
:info:build cc -pipe -Os -DHAVE_CONFIG_H -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -I/opt/local/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_apr-util/apr-util/wor\
k/apr-util-1.6.3/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_apr-util/apr-util/work/apr-util-1.6.3/include/private -I/opt/local/include -I/opt/local/include/ap\
r-1 -I/opt/local/include -c buckets/apr_buckets_flush.c -fno-common -DPIC -o buckets/.libs/apr_buckets_flush.o
:info:build cc: Error: You should be using ${configure.cc}
:info:build See https://trac.macports.org/wiki/UsingTheRightCompiler
:info:build cc -pipe -Os -DHAVE_CONFIG_H -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -I/opt/local/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_apr-util/apr-util/wor\
k/apr-util-1.6.3/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_apr-util/apr-util/work/apr-util-1.6.3/include/private -I/opt/local/include -I/opt/local/include/ap\
r-1 -I/opt/local/include -c buckets/apr_buckets.c -fno-common -DPIC -o buckets/.libs/apr_buckets.o
:info:build cc: Error: You should be using ${configure.cc}
:info:build See https://trac.macports.org/wiki/UsingTheRightCompiler
:info:build cc -pipe -Os -DHAVE_CONFIG_H -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -I/opt/local/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_apr-util/apr-util/wor\
k/apr-util-1.6.3/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_apr-util/apr-util/work/apr-util-1.6.3/include/private -I/opt/local/include -I/opt/local/include/ap\
r-1 -I/opt/local/include -c buckets/apr_brigade.c -fno-common -DPIC -o buckets/.libs/apr_brigade.o
:info:build cc: Error: You should be using ${configure.cc}
:info:build See https://trac.macports.org/wiki/UsingTheRightCompiler
:info:build cc -pipe -Os -DHAVE_CONFIG_H -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -I/opt/local/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_apr-util/apr-util/wor\
k/apr-util-1.6.3/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_apr-util/apr-util/work/apr-util-1.6.3/include/private -I/opt/local/include -I/opt/local/include/ap\
r-1 -I/opt/local/include -c buckets/apr_buckets_alloc.c -fno-common -DPIC -o buckets/.libs/apr_buckets_alloc.o
:info:build cc: Error: You should be using ${configure.cc}
:info:build See https://trac.macports.org/wiki/UsingTheRightCompiler
:info:build cc -pipe -Os -DHAVE_CONFIG_H -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -I/opt/local/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_apr-util/apr-util/wor\
k/apr-util-1.6.3/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_apr-util/apr-util/work/apr-util-1.6.3/include/private -I/opt/local/include -I/opt/local/include/ap\
r-1 -I/opt/local/include -c buckets/apr_buckets_mmap.c -fno-common -DPIC -o buckets/.libs/apr_buckets_mmap.o
:info:build cc: Error: You should be using ${configure.cc}
```

**Comment by jmroot** [comment]
Libtool is run with `--silent` so the compiler invocations aren't actually shown, but the build logs do show `cc` being passed to libtool as the compiler command. E.g.
 - https://build.macports.org/builders/ports-12_arm64-builder/builds/84679
 - https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/156041

**Comment by danielluke** [comment]
Yep. Thanks @ MarcusCalhoun-Lopez - did you want to open a ticket upstream for this?

**Comment by MarcusCalhoun-Lopez** [comment]
I will try to open an upstream ticket for this and #17729 as as soon as I can, but I have to research their ticket system.

**Comment by danielluke** [comment]
Thank you - let me know if you run into trouble (and include me on the ticket you open if you can).

**Pull request merged**
