### PR TITLE
neomutt: fix build failure on macOS <= 10.6

### PR DESCRIPTION
**Pull request by lbschenkel**
###### Description

This is a tentative fix for upstream regression reported on https://github.com/neomutt/neomutt/issues/879. I've incorporated the upstream patch however I don't have an old box to test if it works. I would like somebody to test it and I can report back to upstream so they can merge it.

If the fix works I might wait until the next upstream release instead of incorporating the patch as is. In that case I will change this PR accordingly. Please don't merge this PR in the meantime.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

### CODE REVIEW

**Comment by kencu** [comment]
Some kind of a configure error, nothing to do with the missing ws* function, though:
```
:debug:configure Environment: 
:debug:configure CC='/opt/local/bin/clang-mp-3.9'
:debug:configure CC_PRINT_OPTIONS='YES'
:debug:configure CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_mail_neomutt/neomutt/work/.CC_PRINT_OPTIONS'
:debug:configure CFLAGS='-pipe -Os -arch x86_64'
:debug:configure CPATH='/opt/local/include'
:debug:configure CPPFLAGS='-I/opt/local/include'
:debug:configure CXX='/opt/local/bin/clang++-mp-3.9'
:debug:configure CXXFLAGS='-pipe -Os -stdlib=libc++ -arch x86_64'
:debug:configure F77FLAGS='-m64'
:debug:configure F90FLAGS='-pipe -Os -m64'
:debug:configure FCFLAGS='-pipe -Os -m64'
:debug:configure FFLAGS='-pipe -Os'
:debug:configure INSTALL='/usr/bin/install -c'
:debug:configure LDFLAGS='-L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64'
:debug:configure LIBRARY_PATH='/opt/local/lib'
:debug:configure MACOSX_DEPLOYMENT_TARGET='10.6'
:debug:configure OBJC='/opt/local/bin/clang-mp-3.9'
:debug:configure OBJCFLAGS='-pipe -Os -arch x86_64'
:debug:configure OBJCXX='/opt/local/bin/clang++-mp-3.9'
:debug:configure OBJCXXFLAGS='-pipe -Os -stdlib=libc++ -arch x86_64'
:info:configure Executing:  cd "/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_mail_neomutt/neomutt/work/neomutt-20171013" && ./configure.autosetup --prefix=/opt/local --with-idn=/opt/local --with-ncurses=/opt/local --with-nls=/opt/local --with-ssl=/opt/local 
:debug:configure system:  cd "/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_mail_neomutt/neomutt/work/neomutt-20171013" && ./configure.autosetup --prefix=/opt/local --with-idn=/opt/local --with-ncurses=/opt/local --with-nls=/opt/local --with-ssl=/opt/local 
:info:configure Host System...x86_64-apple-darwin10.8.0
:info:configure Build System...x86_64-apple-darwin10.8.0
:info:configure C compiler...ccache /opt/local/bin/clang-mp-3.9 -pipe -Os -arch x86_64
:info:configure C++ compiler...ccache /opt/local/bin/clang++-mp-3.9 -pipe -Os -stdlib=libc++ -arch x86_64
:info:configure Build C compiler...cc
:info:configure Checking for stdlib.h...not found
:info:configure Error: Compiler does not work. See config.log
:info:configure Try: 'configure.autosetup --help' for options
:info:configure Command failed:  cd "/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_mail_neomutt/neomutt/work/neomutt-20171013" && ./configure.autosetup --prefix=/opt/local --with-idn=/opt/local --with-ncurses=/opt/local --with-nls=/opt/local --with-ssl=/opt/local 
:info:configure Exit code: 1
```

[neomutt.fail.main.log.zip](https://github.com/macports/macports-ports/files/1402464/neomutt.fail.main.log.zip)

seems to get embroiled in ccache? There is a Portfile setting to turn ccache off. 

I just tested the setup by building aria2 with the same compiler setup, and it built fine. I haven't seen this error in other ports before...

**Comment by lbschenkel** [comment]
@kencu: just for the sake of doing a sanity check, do you get the same error if you try to build the version in the tree? The buildbot at least could go past the configure phase: https://build.macports.org/builders/ports-10.6_x86_64_legacy-builder/builds/44056/steps/install-port/logs/stdio

I'm trying to figure out if the failure you're experiencing is due to this patch.

**Comment by lbschenkel** [comment]
And if you could provide the `config.log` it would also be very helpful, because I can submit that to upstream.

**Comment by kencu** [comment]
OK. I got the same error in the version in tree. I have ccache installed, but it is disabled in my macports.conf. I tried adding `configure.ccache no` but that didn't work.

So I deactivated ccache in MacPorts, and it builds through successfully with your 10.6 patch. Thanks!
```
$ port -v installed neomutt
The following ports are currently installed:
  neomutt @20171013_1+idn+mutt (active) platform='darwin 10' archs='x86_64' date='2017-10-20T08:50:51-0700'
```

**Comment by lbschenkel** [comment]
@kencu: thanks for the help. I'll report to upstream that the patch worked. If you could please give me the `config.log` from the broken build with `ccache` enabled, I can use it to open a new issue with upstream.

**Comment by kencu** [comment]
Will do. You might reproduce this by `sudo port -v install neomutt configure.compiler=macports-clang-4.0` for yourself...

**Comment by kencu** [comment]
config.log turns out to be pretty short when it fails with ccache:
```
3 cunningh$ cat config.log
Invoked as: ./configure.autosetup --prefix=/opt/local --with-idn=/opt/local --with-ncurses=/opt/local --with-nls=/opt/local --with-ssl=/opt/local
Failed: ccache /opt/local/bin/clang-mp-3.9 -pipe -Os -arch x86_64 -c -g0 conftest__.c -o conftest__.o
ccache: error: Failed to create directory /opt/local/var/macports/build/.ccache/tmp: Operation not permitted
child process exited abnormally
============
The failed code was:
int main(void) {

return 0;
}
============
Failed: ccache /opt/local/bin/clang-mp-3.9 -pipe -Os -arch x86_64 -c conftest__.c -o conftest__.o
ccache: error: Failed to create directory /opt/local/var/macports/build/.ccache/tmp: Operation not permitted
child process exited abnormally
============
The failed code was:
#include <stdlib.h>
int main(void) {

return 0;
}
```

**Comment by lbschenkel** [comment]
Hmmm... that actually looks more like a bug in `ccache` to me (or even MacPorts).

**Comment by raimue** [comment]
For the ccache issue I described above, see https://github.com/macports/macports-ports/pull/941.

**Comment by kencu** [comment]
Yeah - might even be something in my local setup I've never come across before. Shall we commit your 10.6 Patch? Looks good to go!

**Comment by raimue** [comment]
@kencu Unless ccache is enabled by MacPorts, the path `${prefix}/var/macports/build/.ccache/` is not allowed in the sandbox, therefore the write failed. The patch in #941 should fix that.

**Comment by lbschenkel** [comment]
I want to wait until I hear upstream's plans, in case there's a new release soon (let's say the next couple of days) I would prefer to wait so I don't need to add the patch now and remove later.

**Comment by lbschenkel** [comment]
But if others overwhelmingly vote for merging this now, I won't get in the way...

**Comment by lbschenkel** [comment]
I'm not annoyed, but I *did* write "Please don't merge this PR in the meantime."... :-)

**Comment by kencu** [comment]
@raimue : yep, that makes sense. Glad to see I don't have to go prospecting my system

@lbschenkel : ah, I missed that bit about not merging it. I'm sorry. Just trying to be helpful.

**Pull request merged**
