### PR TITLE
a2ps: update to 4.15

### PR DESCRIPTION
**Pull request by srirangav**
#### Description

Update a2ps to the latest stable release

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6.3 21G419 arm64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by reneeotten — CHANGES_REQUESTED** [review]
@srirangav can you please make sure to align fields consistently throughout the Portfile?

**Comment by srirangav** [comment]
> @srirangav can you please make sure to align fields consistently throughout the Portfile?

Hi @reneeotten,

The portfile used tabs which I think caused the alignment issues.  I've changes this to use spaces.  Hopefully this is acceptable.

Thanks,

-ranga

**Comment by reneeotten** [comment]
ideally the functional changes and whitespace changes should be in two separate commits.

**Comment by srirangav** [comment]
> ideally the functional changes and whitespace changes should be in two separate commits.

Hi @reneeotten,

Would you like me to back out the formatting changes and then submit them as a separate pull request?  I'm happy to do that.  

Thanks,

-ranga

**Comment by reneeotten** [comment]
Yes, that would be great! That's the recommended way of doing it - sorry for not mentioning that when I requested the formatting changes.

**Comment by reneeotten** [comment]
@srirangav I guess we could to that - is there are reason why you don't add the whitespace changes as a second commit to this PR instead?

**Pull request merged**
