### PR TITLE
go: update to 1.10.3

### PR DESCRIPTION
**Pull request by l2dy**
#### Description
[skip notification]

### CODE REVIEW

**Comment by l2dy** [comment]
569d075a0387372bd38b58a0d227455dd9dcf543

**Comment by pmetzger** [comment]
Why did this get opened and closed?

**Comment by l2dy** [comment]
@pmetzger It was merged in 569d075a0387372bd38b58a0d227455dd9dcf543.

**Comment by pmetzger** [comment]
Sure, but then why do a pull request instead of just committing? (I suppose my real request is: if you do stuff like this, it saves me time if you explain in the comments what happened so I don't have to look.)

**Comment by l2dy** [comment]
So that I could do a quick test with Travis CI. I did add a reference to the merged commit.

Please ignore my closed PRs ;)

**Pull request closed without merging**
