### PR TITLE
upx-devel: attempt to fix build on older compilers

### PR DESCRIPTION
**Pull request by l2dy**
`cc1plus: error: unrecognized command line option "-Wvla"`

### CODE REVIEW

**Comment by tobypeterson** [comment]
I don't think there's any need to bump the revision here; a warning flag should have no effect on the build result.

**Comment by l2dy** [comment]
@tobypeterson Without a rev bump can I trigger a rebuild?

https://build.macports.org/builders/ports-10.7_x86_64_legacy-builder/builds/17168

**Comment by tobypeterson** [comment]
Nothing to rebuild if it hasn't built yet!

**Comment by l2dy** [comment]
Fixed.

**Pull request merged**
