### PR TITLE
gnome-voice: update to version 0.4.0

### PR DESCRIPTION
**Pull request by oleaamot**
#### Description

Voice 0.4.0 for GNOME 43 from https://download.gnome.org/sources/gnome-voice/0.4/gnome-voice-0.4.0.tar.xz

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.5 21G72 arm64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
@oleaamot it's almost impossible that this did build for you locally in trace-mode because of the issue reported by the CI build:
```
  Requested 'geoclue-2.0 >= 2.6.0' but version of Geoclue is 2.4.12
  Requested 'libgeoclue-2.0 >= 2.6.0' but version of Geoclue Client Library is 2.4.12
```

Please verify that PRs build locally *in trace-mode* before submitting a PR - many of the recent ones had issues with dependencies.

**Comment by oleaamot** [comment]
:info:configure Requested 'geoclue-2.0 >= 2.6.0' but version of Geoclue is
2.4.1
2
:info:configure Requested 'libgeoclue-2.0 >= 2.6.0' but version of Geoclue
Clien
t Library is 2.4.12

Work in pending in geoclue-2.0 and libgeoclue-2.0 modules and gnome-voice
builds with geoclue 2.6.0 and libgeoclue 2.6.0 manually installed.

Best,
Ole

**Comment by reneeotten** [comment]
>Work in pending in geoclue-2.0 and libgeoclue-2.0 modules and gnome-voice builds with geoclue 2.6.0 and libgeoclue 2.6.0 manually installed.

You cannot rely on manually installed newer versions of packages, it all has to go through MacPorts. Once you have updated/added the required dependencies feel free to do this update again.

**Comment by oleaamot** [comment]
OK.  Makes perfect sense!

**Pull request closed without merging**
