### PR TITLE
nmap: correct licence to Restrictive/Distributable

### PR DESCRIPTION
**Pull request by danchr**
Nmap is licensed under unique terms, derived from the GPL but explicitly inconsistent with it. The licence doesn't seem to restrict MacPorts redistributing neither source nor archives, but it is definitely incompatible with other GPL-licensed software. So, `Restrictive/Distributable` seems the apt choice.

As the `OpenSSLException` clarification is irrelevant to this licence, I removed it.

While at it, I adjusted the modeline to prevent `port lint nmap` from complaining about tabs.

See: https://github.com/nmap/nmap/issues/2199
Closes: https://trac.macports.org/ticket/63941

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM

**Comment by danchr** [comment]
Please note that this is tagged as requiring approval from the maintainer, and was merged nonetheless. Discussion was still ongoing in the linked issue.

**Comment by herbygillot** [comment]
> Please note that this is tagged as requiring approval from the maintainer, and was merged nonetheless. Discussion was still ongoing in the linked issue.

I apologize. I merged it off of @pmetzger's "LGTM". I'll look to be more aware going forward.

**Comment by pmetzger** [comment]
When I say LGTM it doesn't mean "please merge", it means "I looked through it and it seems like the changes are sane". I make such comments when I've bothered to actually look over a request but don't feel I should merge it (for example, because the maintainer hasn't yet had a chance to weigh in.) I will try to be more explicit about that in the future.

**Pull request merged**
