### PR TITLE
moreutils: update to 0.66

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -d install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
Azure CI failure looks to be because of an expired SSL cert.

**Comment by kurthindenburg** [comment]
I hadn't update since the freebsd mirrors didn't have the new version.  Is there really any reason to use the snapshot?   Does that only change w/ new versions?

**Comment by herbygillot** [comment]
I was using the snapshot precisely because the FreeBSD mirrors didn't have the new version. I don't see an official release tarball - wouldn't the snapshot for the given version be a correct asset to use?

**Comment by kurthindenburg** [comment]
I don't know how that snapshot link works.  If you're using the new version w/o issue, go ahead as I won't block it.

**Comment by herbygillot** [comment]
> I don't know how that snapshot link works.

The snapshot link looks to work similarly to Github's archive links.  It downloads a tarball of the specified git tag from the author's original Git repository.

You can see everything here: https://git.joeyh.name/index.cgi/moreutils.git/

**Review by kurthindenburg — APPROVED** [review]
Thanks, this is better than waiting for freebsd to have it.

**Pull request merged**
