### PR TITLE
Update py-pymysql port.

### PR DESCRIPTION
**Pull request by xeron**
* new version 0.7.9
* remove Id line
* use python portgroup variables
* use pypi livecheck
* indentation cleanup

### CODE REVIEW

**Comment by xeron** [comment]
Just curious, I see some PRs being merged and some are committed with different commit hash, why?

**Comment by mojca** [comment]
The commits will never have the same commit hash, if nothing else because it's nearly impossible to have the same parent unless the change is merged super fast.

On the other hand this might have been my fault. I added "Closes NN" at the end of the commit message (right after working on another PR that actually needed some editing and merging of commits where I didn't want to turn the user away by insisting he did a zillion iterations for trivial things). I'm not sure if this is a good or a bad thing to do, maybe it's a bad one, in particular if that breaks the GitHub interface. It's not like your PR needed any changes whatsoever.

I'm also not 100% confident in my skills using zillion merging options, so I used cherry-pick just in case. I'm not sure whether cherry-picking keeps or breaks the "merged" flag on GitHub.

**Comment by neverpanic** [comment]
I've seen the same thing recently, and I'm also not sure how to keep the GitHub PR UI "happy" so that it recognizes that I actually merged the change. For example, I would have expected GitHub to recognize that I rebased (but otherwise deliberately left unmodified) the change in #4 committed in a2792f4120bbf7fc5b7f771930da83895fd504f1, but it didn't.

Did I do something wrong, or does GitHub just not recognize rebased versions of PRs being merged?

**Comment by mojca** [comment]
Maybe GitHub is only happy if you press the button? :)

**Comment by neverpanic** [comment]
I've previously seen PRs that were marked merged by merging the code from the command line, but that might be using the merge strategy only where the commit is exactly the same.

**Pull request closed without merging**
