### PR TITLE
Add macports clang 9.0

### PR DESCRIPTION
**Pull request by cjones051073**
Adds Macports clang 9.0 as a known compiler option.

@kencu @jeremyhu FYI

### CODE REVIEW

**Comment by kencu** [comment]
Looks fine to commit, assuming cctools builds with the +llvm90 variant.

**Comment by kencu** [comment]
Thanks for all your help and observances, Chris.

**Comment by cjones051073** [comment]
> Looks fine to commit, assuming cctools builds with the +llvm90 variant.

yes it does, I've tested that variant.

**Comment by kencu** [comment]
Then IMHO go ahead and commit.

**Pull request merged**
