### PR TITLE
Add GitHub handle davidnich

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

Add GitHub handle @davidnich

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

### CODE REVIEW

**Comment by pmetzger** [comment]
I'm not sure these should really require maintainer approval given the circumstances. Also, if you do all these as pull requests, we'll clog up Travis with lots of spurious CI builds. Maybe you should just commit them directly since there are going to be a ton of them?

**Comment by ryandesign** [comment]
See https://trac.macports.org/ticket/56050#comment:1 for why I don't want to do a mass commit of all ports needing this change. I want to do small batches spaced out over the course of weeks, and breaking up the batches by maintainer is reasonable since it makes for only a single person needing to approve the change.

I think it's reasonable to send a PR so that the maintainer receives it, and is thus made explicitly aware of our desire for this change to be made, so that the maintainer considers it for any future ports they create or adopt. It also gives the maintainer the opportunity to visit the GitHub web interface and click the merge button; a maintainer who has not added their GitHub handle yet may not yet have participated in GitHub in this way.

What Travis does with the PRs is not something I'm concerned about.

**Comment by pmetzger** [comment]
Okay, @ryandesign, I presume I can commit these now (given that the maintainer timeout has passed)?

**Comment by pmetzger** [comment]
Merged.

**Pull request merged**
