### PR TITLE
libreoffice: use python 3.10

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by i0ntempest** [comment]
Also FYI - the current does not build with the latest Xcode because macOS 12.3 SDK is not supported in the configure script for now. Symlinking 12.3 sdk to 12.1 works for now.

**Comment by mascguy** [comment]
> Also FYI - the current does not build with the latest Xcode because macOS 12.3 SDK is not supported in the configure script for now. Symlinking 12.3 sdk to 12.1 works for now.

Would it make sense to patch the configure script, rather than forcing users to hack their setup?

**Comment by i0ntempest** [comment]
> > Also FYI - the current does not build with the latest Xcode because macOS 12.3 SDK is not supported in the configure script for now. Symlinking 12.3 sdk to 12.1 works for now.
> 
> Would it make sense to patch the configure script, rather than forcing users to hack their setup?

I tried editing configure script before running it, for some reason it always gets reverted. Probably some time stamp check. I’m not sure but if u want to patch it you might need to hack autoconf and stuff.

**Comment by Tatsh** [comment]
> > > > Also FYI - the current does not build with the latest Xcode because macOS 12.3 SDK is not supported in the configure script for now. Symlinking 12.3 sdk to 12.1 works for now.
> > > 
> > > 
> > > Would it make sense to patch the configure script, rather than forcing users to hack their setup?
> > 
> > 
> > I tried editing configure script before running it, for some reason it always gets reverted. Probably some time stamp check. I’m not sure but if u want to patch it you might need to hack autoconf and stuff.
> 
> Does anyone know of a quick/established fix for this? If not, I can take a look... with the caveat that I'm not an autotools guru. Lol

This has already been patched upstream. It probably won't make the next release. Add [this patch](https://github.com/LibreOffice/core/commit/3733772279ba8968f18a9f73a3294f43aebe53ac)

**Comment by i0ntempest** [comment]
Patches added! Working for me on my system.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
