### PR TITLE
courier-imap ports: multiple updates

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with ~`sudo port -vst install`~ `sudo port -d destroot`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
@herbygillot is the CI failure a real issue or not here? If so, are you addressing that - there hasn't been activity in two weeks here 😉

**Comment by herbygillot** [comment]
I've made some changes, but CI is insisting on running tests... can someone remind me how to convince it not to?

`test.run no` is being summarily ignored...

**Comment by reneeotten** [comment]
> I've made some changes, but CI is insisting on running tests... can someone remind me how to convince it not to?
> 
> `test.run no` is being summarily ignored...

`test.ignore_archs yes` - that should be resolved in MacPorts 2.9.2

**Comment by herbygillot** [comment]
> `test.ignore_archs yes` - that should be resolved in MacPorts 2.9.2

Thanks

**Pull request merged**
