### PR TITLE
openldap: update to version 2.4.46 - not tested against libressl

### PR DESCRIPTION
**Pull request by Schamschula**
#### Description
I have built openldap 2.4.46 against openssl. I have had to remove one hunk from libressl.patch, as gstdtlsconnection.c was modified upstream. 
###### Type(s)
- [ x] update

###### Tested on
macOS 10.13.3
Xcode 9.2

### CODE REVIEW

**Comment by pmetzger** [comment]
@Schamschula Can you squish the commits? Then I can merge this.

**Comment by Schamschula** [comment]
@pmetzger I wanted to get feedback to see if this builds under libressl (default is openssl), so I'm leaving this open for the moment. I forgot to ask @jeremyhu as he is the one who added the libressl patch, to comment. Doing so now.

**Comment by pmetzger** [comment]
Either way, you'll want to squash the commits. The libressl fix is readable either way. :)

**Comment by Schamschula** [comment]
Well, that's what I didn't want to do: this merge should not have been committed.

**Comment by pmetzger** [comment]
Did you click merge by accident?

**Comment by Schamschula** [comment]
Yes. More precisely, that was the only merge option I was presented.

**Comment by pmetzger** [comment]
Yah, squishing your commits is something you do in your own repository, not in the pull queue. For now why don't we leave this and fix anything that @jeremyhu thinks still needs repair with another commit.

**Comment by Schamschula** [comment]
Too many repos...
I forked macports-ports for this PR. However, that's not my working repo and I have no local instance of it to squash.

**Pull request merged**
