### PR TITLE
tor-devel: update to 0.3.5.2-alpha

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by pmetzger** [comment]
Howdy, @rex4539! Thanks for submitting an update. Unfortunately you cut out the entire form that the pull request system provides to make it easy for the people processing your request to learn if you've tested the requested pull and the like. As a result, I can't really proceed with this.

**Comment by rex4539** [comment]
The changes to update this port are really trivial.

I have also been then main updater of this port for the last few months :)

I tested it locally and works fine.

**Comment by pmetzger** [comment]
> The changes to update this port are really trivial.
[...]
> I tested it locally and works fine.

The reason we have the form is so that I don't have to ask if you tested it and the like. It also makes sure you ran port lint and that you checked for things like trac tickets outstanding. Please don't toss it out.

**Comment by pmetzger** [comment]
Merged. Thanks for the update, @rex4539.

**Pull request merged**
