### PR TITLE
lua-luasocket: update to 3.1.0, fix Rosetta and universal build

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update to 3.1.0, drop redundant patches.
Fix Rosetta and universal build.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server (x86_64 + ppc)
Xcode 3.2.6

macOS 10A190
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Hmm, Clang cannot find `lua.h`. GCC build is all good. Let me try fixing Clang build.

**Comment by barracuda156** [comment]
@herbygillot Could we merge this, please?

**Review by harens — APPROVED** [review]
Thanks for your work on this @barracuda156

**Comment by barracuda156** [comment]
> Thanks for your work on this @barracuda156

@harens Thank you!

**Pull request merged**
