### PR TITLE
pdfpc: update to 4.7.0, fix build on powerpc

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update, fix

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
macOS 15 CI fails on a dependency, so unrelated.

```
Building dependency (1 of 304) 'discount' with variants '' ... [FAIL]
```

**Review by maehne — APPROVED** [review]
Looks good to me. However, version 4.7.0 got released just three days ago. Maybe, consider to update this PR to the latest release.

**Comment by barracuda156** [comment]
> Looks good to me. However, version 4.7.0 got released just three days ago. Maybe, consider to update this PR to the latest release.

Ok, I will do this today.

**Review by maehne — APPROVED** [review]
Looks good to me! You may change the title of this PR to reflect the updated version.

**Comment by barracuda156** [comment]
> Looks good to me! You may change the title of this PR to reflect the updated version.

Fair enough, done.

**Comment by reneeotten** [comment]
this fails everywhere on the CI - please take a look. One message is:

  --   No package 'webkit2gtk-4.1' found

**Comment by barracuda156** [comment]
@reneeotten Thanks, I will check that. (This dependency is not used on powerpc, as per portfile, so no error locally.)

**Comment by barracuda156** [comment]
@reneeotten @maehne Looks like they want a much newer version than MacPorts has: https://ports.macports.org/port/webkit2-gtk
Can’t do anything about this. I am not gonna try updating `webkit2-gtk`.

Solution would be either to keep the port at 4.6.0 and just fix it (what I did originally) or update it to 4.7.0, but disable `webkit2-gtk` unconditionally. Or do nothing and leave it broken.

**Comment by reneeotten** [comment]
> You tell me what to do, I would like to close this PR this or that way. Preferably merging, but not leaving pending.

I have personally no interest in this port, so don't care which solution is picked. I am fine with merging this, if @maehne wants to re-enable the option that requires a newer version of `webkit2-gtk`; then he has to work on updating that package as well.

**Comment by barracuda156** [comment]
> But before I can/will merge the CI has to pass.

@reneeotten Yes, of course. Will sort that out.

**Comment by barracuda156** [comment]
@reneeotten This is ready now, on macOS 15 it is a dependency that fails:
```
Building 259 dependencies of pdfpc:
 Building dependency (1 of 259) 'discount' with variants '' ... [FAIL]
```

**Pull request merged**
