### PR TITLE
Add GitHub handle RJVB to maintainers

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

Add GitHub handle @RJVB to maintainers

### CODE REVIEW

**Comment by pmetzger** [comment]
@mojca Not really appropriate for this set of changes. @ryandesign is just trying to push out updates to the `maintainer` lines. That said, I think it might be reasonable for us to separately consider having something crawl the entire ports database and make a list of everything with lint warnings for us to slowly fix.

**Comment by ryandesign** [comment]
> it might be reasonable for us to separately consider having something crawl the entire ports database and make a list of everything with lint warnings for us to slowly fix

Anyone can generate that list anytime by running `port lint all` and work through any part of it that they want.

**Comment by ryandesign** [comment]
> Anyone can generate that list anytime by running `port lint all` and work through any part of it that they want.

See also https://trac.macports.org/ticket/56345 for a more helpful view of that information.

**Comment by pmetzger** [comment]
Merge. Thank you as always, Ryan!

**Pull request merged**
