### PR TITLE
onetbb: set supported_archs & create tests variant

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@MarcusCalhoun-Lopez @mohd-akram Could we please not set archs? I have a PR for restoring 32-bit support, just waiting for upstream to merge it.

We need `oneTBB` for Stan, and we want Stan on PPC :)

**Comment by MarcusCalhoun-Lopez** [comment]
@barracuda156, I saw you have been [doing a great deal of work](https://github.com/macports/macports-ports/pull/17312#issuecomment-1382783437) to get 32-bit support.
That is much appreciated.

Setting `supported_archs` is just a recognition of the current situation and allows for a more graceful failure.
Once your work is complete an update or pull request should easily be able to remove this one line of code.

**Comment by barracuda156** [comment]
> @barracuda156, I saw you have been [doing a great deal of work](https://github.com/macports/macports-ports/pull/17312#issuecomment-1382783437) to get 32-bit support. That is much appreciated.

Thank you. This is the PR with upstream btw: https://github.com/oneapi-src/oneTBB/pull/840

For `supported_archs`, not a big deal indeed, I will just remove that in the PR to restore 32-bit support. Upstream is not fast with reviewing, I may actually do it here first – need to rebase my PR anyway after recent changes to the port by @catap

**Review by mohd-akram — APPROVED** [review]
Thanks!

**Comment by barracuda156** [comment]
BTW, `ppc64` should be in supported_archs, I think, even now. While 10.5.8 needs a couple of extra fixes, `ppc64` is supported among 64-bit archs.

**Comment by barracuda156** [comment]
Ok, now I can update the PR to fix this for other archs.

**Pull request merged**
