### PR TITLE
libavif/libheif: enable aom for earlier systems; unbreak build with gcc

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

1. `aom` has been fixed for `ppc` since then and enabled in `ffmpeg` etc.
2. Flags added to `libheif` recently to fix clang builds break build with gcc. Make them compiler-specific.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mascguy** [comment]
If you want, make the same fix for `libavif` as part of the this PR too.

**Comment by barracuda156** [comment]
> If you want, make the same fix for `libavif` as part of this PR too.

@mascguy I have checked its portfile now, if `aom` was disabled earlier, that has already been removed. (And no clang-specific flags are set.)

P. S. I remember about `guile`, finishing my `R` updates soon and gonna deal with it.

**Comment by mascguy** [comment]
This is the last update you made to one of our tracking tickets, so more to include:

```
Comment (by barracuda156):

What is still due:

1. Disable `libsdl2` for Rosetta until fixed.
2. Enable `aom` for 10.6.
3. Enable `dav1d` for 10.6 ppc/Rosetta (i.e., remove blacklist of `ppc`).
4. Enable `svt-av1` for 10.6.
```

**Comment by mascguy** [comment]
You can also enable `rav1e` for 10.6 as well, as that has also been fixed. (Not sure about PPC, but certainly for Intel.)

**Comment by barracuda156** [comment]
> This is the last update you made to one of our tracking tickets, so more to include:
> 
> ```
> Comment (by barracuda156):
> 
> What is still due:
> 
> 1. Disable `libsdl2` for Rosetta until fixed.
> 2. Enable `aom` for 10.6.
> 3. Enable `dav1d` for 10.6 ppc/Rosetta (i.e., remove blacklist of `ppc`).
> 4. Enable `svt-av1` for 10.6.
> ```

These were done, I believe.

Let me however try building `aom` on Tiger – that no one might have tested. If it fails, then we keep dropping `aom`, but for < 9.

**Comment by barracuda156** [comment]
> You can also enable `rav1e` for 10.6 as well, as that has also been fixed. (Not sure about PPC, but certainly for Intel.)

It requires Rust, doesn’t it? Then need to exclude `ppc`, yes.

**Comment by barracuda156** [comment]
@mascguy Hmm, I have a second thought on Tiger: maybe disable `aom` for it just out of consideration for slow G4 machines, where it is expected to run? My PowerBook G4 now failed to _fetch_ `aom` properly with `cannot pread pack file`, and then froze. I will reboot the Quad to Tiger and try there just to find out if it builds, but maybe it makes sense not to enable it for Tiger regardless. No personal preference here, TBH, I do not use Tiger besides occasional testing.

**Comment by mascguy** [comment]
> @mascguy Hmm, I have a second thought on Tiger: maybe disable `aom` for it just out of consideration for slow G4 machines, where it is expected to run? My PowerBook G4 now failed to _fetch_ `aom` properly with `cannot pread pack file`, and then froze. I will reboot the Quad to Tiger and try there just to find out if it builds, but maybe it makes sense not to enable it for Tiger regardless. No personal preference here, TBH, I do not use Tiger besides occasional testing.

Sure, we can keep it disabled for 10.4. But it works fine for 10.5, so at least enable it for the latter.

@evanmiller Any thoughts/preferences on this, relative to Tiger?

**Comment by barracuda156** [comment]
Since we decided to allow Tiger to build `aom` (it builds fine, confirmed), I will finalize this PR now.

**Comment by barracuda156** [comment]
@mascguy Provisionally should be good, waiting for CI to pass.

**Review by mascguy — APPROVED** [review]
LGTM

**Comment by barracuda156** [comment]
Forgot to revbump `libavif`, done now.

**Comment by barracuda156** [comment]
CIs passed, should be good to merge.

**Comment by MarcusCalhoun-Lopez** [comment]
I am sorry to be late to this conversation, but why is
```
                            -Wno-nonportable-include-path \
                            -Wno-error=nonportable-include-path \
                            -Wno-unknown-warning-option \
                            -Wno-error=unknown-warning-option
```
necessary?

According to the [ticket](https://trac.macports.org/ticket/67404), the compiler complained about `<DAV1D/version.h>` and `<dav1d/dav1d.h>`, but it was not clear to me where `DAV1D/version.h` was coming from.

If the port dav1d is somehow installing DAV1D/version.h instead of dav1d/dav1d.h, wouldn't it be better to fix it there?

**Comment by mascguy** [comment]
> I am sorry to be late to this conversation, but why is
> 
> ```
>                             -Wno-nonportable-include-path \
>                             -Wno-error=nonportable-include-path \
>                             -Wno-unknown-warning-option \
>                             -Wno-error=unknown-warning-option
> ```
> 
> necessary?
> 
> According to the [ticket](https://trac.macports.org/ticket/67404), the compiler complained about `<DAV1D/version.h>` and `<dav1d/dav1d.h>`, but it was not clear to me where `DAV1D/version.h` was coming from.
> 
> If the port dav1d is somehow installing DAV1D/version.h instead of dav1d/dav1d.h, wouldn't it be better to fix it there?

I'm convinced this is a Clang bug, as the uppercase paths are nowhere to be found. However, I am able to reproduce the issue for older macOS releases, so it's definitely necessary to disable those options.

**Comment by MarcusCalhoun-Lopez** [comment]
Thanks for the insight.
Another option is to track down the Clang issue and then blacklist as needed.

**Comment by mascguy** [comment]
> Thanks for the insight. Another option is to track down the Clang issue and then blacklist as needed.

I'll have to check which version of Clang is being used where, but I'll get around to it eventually.

**Pull request merged**
