### PR TITLE
lastfm-desktop: new port

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Let’s see if this builds.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by aeiouaeiouaeiouaeiouaeiouaeiou — APPROVED** [review]

**Comment by reneeotten** [comment]
that project seems dead with no activity in over 5 years. Do we really need a port for this...?

**Comment by barracuda156** [comment]
> that project seems dead with no activity in over 5 years. Do we really need a port for this...?

@reneeotten LastFM is not dead at all. I use it myself on Intel and arm64.
But wait with merging a day, I need to change something here a bit.

**Comment by barracuda156** [comment]
@reneeotten @aeiouaeiouaeiouaeiouaeiouaeiou Good news, the app works on x86. However it complains about iTunes plugin version, I need to look into that.
lastfm

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
>no album covers, but scrobbling works

Last.fm uses Fastly CDN for cover images, perhaps this problem is caused by an [expired certificate](https://logi.wiki/index.php/ERR_CERT_INVALID).

**Comment by barracuda156** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou So that is to be addressed on OS level, not in the port?

I will hopefully finish this one tomorrow. It needs a fix for linking of fingerprint binary (installs with wrong paths) and a tiny fix for Leopard compatibility.

**Comment by barracuda156** [comment]
@reneeotten @aeiouaeiouaeiouaeiouaeiouaeiou Should be ready to merge now.

**Comment by barracuda156** [comment]
@herbygillot @reneeotten Could we merge this now?

**Pull request merged**
