### PR TITLE
elmerfem: update to 2023.11.09

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@szhorvat Did we break something with `OpenBLAS` in https://github.com/macports/macports-ports/pull/21127 commit? `elmerfem` port was building fine before, but now fails on macos-13 on CI (at the same time it builds fine on macos-12):
```
  [ 11%] Linking Fortran shared library libarpack.dylib
  cd /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_elmerfem/elmerfem/work/build/mathlibs/src/arpack && /opt/local/bin/cmake -E cmake_link_script CMakeFiles/arpack.dir/link.txt --verbose=ON
  /opt/local/bin/gfortran-mp-13 -pipe -Os -m64 -fallow-argument-mismatch -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -mmacosx-version-min=13.0 -dynamiclib -Wl,-headerpad_max_install_names -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/local/lib/libgcc -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -o libarpack.dylib -install_name @rpath/libarpack.dylib CMakeFiles/arpack.dir/cgetv0.o CMakeFiles/arpack.dir/cnaitr.o CMakeFiles/arpack.dir/cnapps.o CMakeFiles/arpack.dir/cnaup2.o CMakeFiles/arpack.dir/cnaupd.o CMakeFiles/arpack.dir/cneigh.o CMakeFiles/arpack.dir/cneupd.o CMakeFiles/arpack.dir/cngets.o CMakeFiles/arpack.dir/csortc.o CMakeFiles/arpack.dir/cstatn.o CMakeFiles/arpack.dir/dgetv0.o CMakeFiles/arpack.dir/dlaqrb.o CMakeFiles/arpack.dir/dnaitr.o CMakeFiles/arpack.dir/dnapps.o CMakeFiles/arpack.dir/dnaup2.o CMakeFiles/arpack.dir/dnaupd.o CMakeFiles/arpack.dir/dnconv.o CMakeFiles/arpack.dir/dneigh.o CMakeFiles/arpack.dir/dneupd.o CMakeFiles/arpack.dir/dngets.o CMakeFiles/arpack.dir/dsaitr.o CMakeFiles/arpack.dir/dsapps.o CMakeFiles/arpack.dir/dsaup2.o CMakeFiles/arpack.dir/dsaupd.o CMakeFiles/arpack.dir/dsconv.o CMakeFiles/arpack.dir/dseigt.o CMakeFiles/arpack.dir/dsesrt.o CMakeFiles/arpack.dir/dseupd.o CMakeFiles/arpack.dir/dsgets.o CMakeFiles/arpack.dir/dsortc.o CMakeFiles/arpack.dir/dsortr.o CMakeFiles/arpack.dir/dstatn.o CMakeFiles/arpack.dir/dstats.o CMakeFiles/arpack.dir/dstqrb.o CMakeFiles/arpack.dir/sgetv0.o CMakeFiles/arpack.dir/slaqrb.o CMakeFiles/arpack.dir/snaitr.o CMakeFiles/arpack.dir/snapps.o CMakeFiles/arpack.dir/snaup2.o CMakeFiles/arpack.dir/snaupd.o CMakeFiles/arpack.dir/snconv.o CMakeFiles/arpack.dir/sneigh.o CMakeFiles/arpack.dir/sneupd.o CMakeFiles/arpack.dir/sngets.o CMakeFiles/arpack.dir/ssaitr.o CMakeFiles/arpack.dir/ssapps.o CMakeFiles/arpack.dir/ssaup2.o CMakeFiles/arpack.dir/ssaupd.o CMakeFiles/arpack.dir/ssconv.o CMakeFiles/arpack.dir/sseigt.o CMakeFiles/arpack.dir/ssesrt.o CMakeFiles/arpack.dir/sseupd.o CMakeFiles/arpack.dir/ssgets.o CMakeFiles/arpack.dir/ssortc.o CMakeFiles/arpack.dir/ssortr.o CMakeFiles/arpack.dir/sstatn.o CMakeFiles/arpack.dir/sstats.o CMakeFiles/arpack.dir/sstqrb.o CMakeFiles/arpack.dir/zgetv0.o CMakeFiles/arpack.dir/znaitr.o CMakeFiles/arpack.dir/znapps.o CMakeFiles/arpack.dir/znaup2.o CMakeFiles/arpack.dir/znaupd.o CMakeFiles/arpack.dir/zneigh.o CMakeFiles/arpack.dir/zneupd.o CMakeFiles/arpack.dir/zngets.o CMakeFiles/arpack.dir/zsortc.o CMakeFiles/arpack.dir/zstatn.o CMakeFiles/arpack.dir/cmout.o CMakeFiles/arpack.dir/cvout.o CMakeFiles/arpack.dir/dmout.o CMakeFiles/arpack.dir/dvout.o CMakeFiles/arpack.dir/icnteq.o CMakeFiles/arpack.dir/icopy.o CMakeFiles/arpack.dir/iset.o CMakeFiles/arpack.dir/iswap.o CMakeFiles/arpack.dir/ivout.o CMakeFiles/arpack.dir/second.o CMakeFiles/arpack.dir/smout.o CMakeFiles/arpack.dir/svout.o CMakeFiles/arpack.dir/zmout.o CMakeFiles/arpack.dir/zvout.o  -Wl,-rpath,/opt/local/lib /opt/local/lib/libopenblas.dylib /opt/local/lib/libopenblas.dylib 
  ld: warning: duplicate -rpath '/opt/local/lib/libgcc' ignored
  ld: warning: duplicate -rpath '/opt/local/lib' ignored
  ld: warning: ignoring duplicate libraries: '-lgcc', '-lgcc_s.1.1'
  ld: multiple errors: duplicate LC_RPATH '/opt/local/lib/libgcc' in '/opt/local/lib/libopenblas-r1.dylib'; duplicate LC_RPATH '/opt/local/lib/libgcc' in '/opt/local/lib/libopenblas-r1.dylib'
  collect2: error: ld returned 1 exit status
  make[2]: *** [mathlibs/src/arpack/libarpack.dylib] Error 1
  make[2]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_elmerfem/elmerfem/work/build'
  make[1]: *** [mathlibs/src/arpack/CMakeFiles/arpack.dir/all] Error 2
  make[1]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_elmerfem/elmerfem/work/build'
  make: *** [all] Error 2
```

**Comment by szhorvat** [comment]
It'll be a couple of days before I can look in detail. Do you have access to Xcode 15 to test this before then, by reverting #21127 locally? Or perhaps just push an extra commit in this draft PR as an experiment to see if that's indeed the issue?

**Comment by szhorvat** [comment]
Something I notice in your snippet above is the duplicate library warnings. This would mean that it is not actually using the classic linker. The `-Wl,-ld_classic` flag that the linalg PR added does not seem to be present in the linking command in this snippet.

**Comment by szhorvat** [comment]
This port is not using the `linear_algebra` port group at all. Instead it hard-codes linking to OpenBLAS. What if you actually start using that port group, and let it add the flag that chooses the classic linker? Will that fix it?

**Comment by barracuda156** [comment]
@szhorvat Got it, thank you. I think it did not link with Accelerate, and unfortunately PG hardcodes it as default for most systems. I could not override it, so had to hardcode OpenBLAS directly instead.

**Comment by barracuda156** [comment]
Let’s see if the PG helps. I set it conditionally now, retaining an override for older OS.

**Comment by barracuda156** [comment]
@szhorvat I remembered incorrectly. Looking now at the code, turns out Accelerate was fine, what was broken is OpenBLAS finding at configure. It is still broken via PG, it seems.

**Pull request merged**
