### PR TITLE
uv: Upgrade to 0.4.16

### PR DESCRIPTION
**Pull request by halostatue**
#### Description

uv: Upgrade to 0.4.16

##### Tested on

macOS 14.6.1 23G93 arm64
Xcode 15.4 15F31d

##### Verification

Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by TheRealKeto** [comment]
The `cargo.crates` stanza creates too big of a diff for me to accept this, largely due to the indentation size being changed. Neither `cargo2ports` or `cargo2port` suggest this large of a diff.

**Comment by halostatue** [comment]
> The `cargo.crates` stanza creates too big of a diff for me to accept this, largely due to the indentation size being changed. Neither `cargo2ports` or `cargo2port` suggest this large of a diff.

Apologies. The tool that I use by default (https://github.com/halostatue/crate2port) uses a new flag default (`--align=justify`) that's in `cargo2port` master and not yet released. This generally works better with the *other* Rust ports that I submit, and I didn't double check the size of the diff. I’ve pushed the changes and they’re much more reasonable now.

(I haven't made a port for `crate2port` which can get the `cargo.crates` without checking out the repo because the changes needed aren't yet tagged in l2dy/cargo2port.)

**Review by TheRealKeto — APPROVED** [review]
LGTM!

**Comment by herbygillot** [comment]
Thank you both.

**Pull request merged**
