### PR TITLE
readline: update version 7.0.005->8.0.000

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
Update dependencies due to library name change.

See https://trac.macports.org/ticket/57871

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.2
Xcode 10.1 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by lbschenkel** [comment]
+1 for the revbumps on `ncmpcpp`, `pspg`, `opensc`

**Comment by markemer** [comment]
+1 for `Io`

**Comment by Schamschula** [comment]
+1 for `gawk`, `GiNaC`, `pyxplot`, `inetutils`, `lftp`

In order to get those to build, I also re-built `hunspell`, `lua`, `lua52`, `guile`, `postgresql96`, 
`augeas`, `fluidsynth`, `gdbm`, `ruby`, `R`, `gnudatalanguage`, `gnuplot` and `octave`.

I also found an issue with `fcron`: @kurthindenburg it has a runtime dependency on `readline`.

**Comment by RJVB** [comment]
I have no issues with a revbump of my ports if that's required.

**Comment by blair** [comment]
LGTM for my revbumps.

**Comment by dstrubbe** [comment]
Looks fine with regard to paraview.

**Comment by cjones051073** [comment]
b.t.w. this PR now has conflicts against master, which you need to resolve before it can be merged.

**Comment by tessus** [comment]
Just a dumb question? How shall I test it with my port? Apply the PR locally and try building my port? What's the procedure for that? (I don't need an answer right away. I have to get some sleep, because I should get up in 4 hours.)

**Comment by RJVB** [comment]
Just realise that if you do that, a PR like this will cause a local rebuild of everything you have installed that depends on readline. MacPorts doesn't make it easy at all to avoid that, but with some manual tweaking you can get around that (for testing!) and only rebuild the ports you want against the new dependency.

**Comment by cjones051073** [comment]
Not true. If you follow my suggestions then at the end only run `sudo port upgrade <port-in-question>` then only the minimal required deps will be rebuilt.

**Comment by RJVB** [comment]
You'd want to add `--no-rev` in that case, because you'll end up with an unknown number of broken ports, and by default an attempt will be made to rebuild those. And you'll need to revert the changes to your port, readline *and* those other dependencies in order to get back to a stable install (whereas with what I had in mind you only revert readline and your own port).

HOWEVER:

- there should be no need to test anything if your port doesn't depend on readline directly but through some other dependency (say it uses an embedded interpreter which needs readline; in that case the depspec is probably superfluous).
- it is very likely that you don't need to *upgrade* your port, but that a `port -n destroot myport` is good enough. Most readline dependencies only use a very small subset of the readline API (more or less a single "prompt the user for some input and return it" call) and in that case just checking if the destroot completes should be enough.

**Comment by cjones051073** [comment]
My suggestion was offered only as a way to test build a specific port, not how to have a complete and functioning ecosystem. In my opinion it is not enough to *only* update readline plus your port in question. To properly test the build you must also update all other dependencies of your port. Otherwise you are not properly testing anything. Please also not I am making this comment in general terms, not specific to readline here. 

My assumption was after doing this you would indeed revert your checkout back to master and (force) reinstall the updated ports back to their original versions.

**Comment by NicosPavlov** [comment]
Seems all good for analitza. 

Looking at the ports announced as broken in my list, it seems that fontforge would also need a rebuild.

**Comment by kencu** [comment]
good by me

**Comment by tessus** [comment]
@cjones051073 Thanks, same here. I also use a full git clone. I'm not asking for advice on git, but how the MacPorts procedure is to test something like this. So I guess my idea to apply the PR locally was correct. ;-) Thank you for your reply and help.

**Pull request merged**
