### PR TITLE
Updated iTerm to build only on 10.12

### PR DESCRIPTION
**Pull request by markemer**
Fixes https://trac.macports.org/ticket/51983

### CODE REVIEW

**Comment by mojca** [comment]
Does it build with a newer SDK on 10.11?

**Comment by markemer** [comment]
I hadn't thought of that. If you use Xcode 8 on 10.11, it very well might work. If it does I should probably change this to require Xcode 8.

**Comment by markemer** [comment]
Ok, so I screwed up my pull here. I need to fix my branches by starting over.

**Comment by mojca** [comment]
Note that you can still do a clean push to your iTerm2-10.12 branch and that will delete all the wrong commits.

**Pull request closed without merging**
