### PR TITLE
rsyncrypto: Use active_variants portgroup

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Comment by mf2k** [comment]
The gzip port does not have a `+rsyncable` variant.

**Comment by raimue** [comment]
The gzip +rsyncable variant existed a long time ago, but was incorporated into upstream since then. Without testing I guess this part of the description can just be deleted without any replacement required.

**Comment by mf2k** [comment]
Done. Closing this request.

**Comment by grimreaper** [comment]
ha. I tested this without the variant and forgot to test /with/ which would have caught this.

**Pull request closed without merging**
