### PR TITLE
netpbm: do not use extract.rename if available

### PR DESCRIPTION
**Pull request by michaelld**
#### Description

netpbm: do not use extract.rename if available

This is because the git hash that's part of the tarball is already specified as part of the github info. This change does not impact `port` base 2.8.0 or prior since `extract.rename` was only added in the last month-ish.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.7.3 20G1102 x86_64
Xcode 12.3 12C33

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
Why is this needed?

**Comment by michaelld** [comment]
Using current `base` (20230109 / 6b422f1e), current `port`, and `libnetpbm` port without the PR:
```
% sudo port -v patch subport=libnetpbm
Password:
--->  Fetching distfiles for libnetpbm
--->  Verifying checksums for libnetpbm
--->  Checksumming advanced-r4489.tar.gz
--->  Checksumming userguide-r4475.tar.gz
--->  Extracting libnetpbm
--->  Extracting advanced-r4489.tar.gz
Executing:  cd "/opt/local/var/macports/build/_opt_sources_MacPorts_ports_github_michaelld_graphics_netpbm/libnetpbm/work" && /usr/bin/gzip -dc '/opt/sources/MacPorts/distfiles/netpbm/advanced-r4489.tar.gz' | /usr/bin/tar -xf -
--->  Extracting userguide-r4475.tar.gz
Executing:  cd "/opt/local/var/macports/build/_opt_sources_MacPorts_ports_github_michaelld_graphics_netpbm/libnetpbm/work" && /usr/bin/gzip -dc '/opt/sources/MacPorts/distfiles/netpbm/userguide-r4475.tar.gz' | /usr/bin/tar -xf -
Error: Failed to extract libnetpbm: extract.rename: multiple directories exist in /opt/local/var/macports/build/_opt_sources_MacPorts_ports_github_michaelld_graphics_netpbm/libnetpbm/work: /opt/local/var/macports/build/_opt_sources_MacPorts_ports_github_michaelld_graphics_netpbm/libnetpbm/work/netpbm-mirror-62c62a8423c7d6746f437f46c35499281c39e4dd /opt/local/var/macports/build/_opt_sources_MacPorts_ports_github_michaelld_graphics_netpbm/libnetpbm/work/netpbm-mirror-a70405848cb06782036364a88e27f452fb0a0b32
Error: See /opt/local/var/macports/logs/_opt_sources_MacPorts_ports_github_michaelld_graphics_netpbm/libnetpbm/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port netpbm failed

% pushd work
/opt/sources/MacPorts/ports/github_michaelld/graphics/netpbm/work /opt/sources/MacPorts/ports/github_michaelld/graphics/netpbm

% ll
total 8
drwxr-xr-x    2 macports  wheel     64 Jan 12 17:09 .home/
-rw-r--r--    1 macports  wheel    143 Jan 12 17:09 .macports.libnetpbm.state
drwxr-xr-x    2 macports  wheel     64 Jan 12 17:09 .tmp/
drwxr-xr-x  434 macports  wheel  13888 Dec  4 18:38 netpbm-mirror-62c62a8423c7d6746f437f46c35499281c39e4dd/
drwxr-xr-x   25 macports  wheel    800 Dec 30 19:32 netpbm-mirror-a70405848cb06782036364a88e27f452fb0a0b32/
```

**Comment by michaelld** [comment]
With the PR addition:
```
% sudo port -v patch subport=libnetpbm
--->  Fetching distfiles for libnetpbm
--->  Verifying checksums for libnetpbm
--->  Checksumming advanced-r4489.tar.gz
--->  Checksumming userguide-r4475.tar.gz
--->  Extracting libnetpbm
--->  Extracting advanced-r4489.tar.gz
Executing:  cd "/opt/local/var/macports/build/_opt_sources_MacPorts_ports_github_michaelld_graphics_netpbm/libnetpbm/work" && /usr/bin/gzip -dc '/opt/sources/MacPorts/distfiles/netpbm/advanced-r4489.tar.gz' | /usr/bin/tar -xf -
--->  Extracting userguide-r4475.tar.gz
Executing:  cd "/opt/local/var/macports/build/_opt_sources_MacPorts_ports_github_michaelld_graphics_netpbm/libnetpbm/work" && /usr/bin/gzip -dc '/opt/sources/MacPorts/distfiles/netpbm/userguide-r4475.tar.gz' | /usr/bin/tar -xf -
--->  Applying patches to libnetpbm
--->  Applying patch-lib-Makefile.diff
Executing:  cd "/opt/local/var/macports/build/_opt_sources_MacPorts_ports_github_michaelld_graphics_netpbm/libnetpbm/work/advanced-r4489" && /usr/bin/patch -p0 < '/opt/sources/MacPorts/ports/github_michaelld/graphics/netpbm/files/patch-lib-Makefile.diff'
patching file lib/Makefile
--->  Applying patch-other-pamx-Makefile.diff
Executing:  cd "/opt/local/var/macports/build/_opt_sources_MacPorts_ports_github_michaelld_graphics_netpbm/libnetpbm/work/advanced-r4489" && /usr/bin/patch -p0 < '/opt/sources/MacPorts/ports/github_michaelld/graphics/netpbm/files/patch-other-pamx-Makefile.diff'
patching file other/pamx/Makefile
--->  Applying patch-python.diff
Executing:  cd "/opt/local/var/macports/build/_opt_sources_MacPorts_ports_github_michaelld_graphics_netpbm/libnetpbm/work/advanced-r4489" && /usr/bin/patch -p0 < '/opt/sources/MacPorts/ports/github_michaelld/graphics/netpbm/files/patch-python.diff'
patching file buildtools/makeman
patching file buildtools/manpage.mk
--->  Patching makeman: s|__MACPORTS_PYTHON__|/opt/local/bin/python3.10|g
--->  Patching manpage.mk: s|__MACPORTS_PYTHON__|/opt/local/bin/python3.10|g
```

**Comment by michaelld** [comment]
Maybe the logic on the GH PR could be tweaked for situations like this and `cargo` (https://github.com/macports/macports-ports/pull/17296)

**Comment by michaelld** [comment]
This tweak to `base` ( https://github.com/macports/macports-base/commit/d43dd953c6b0ff9e9b0bb0c18c8e6c1da17f9617 ) works for `cargo` but not `netpbm` ... this port contains multiple directories & still shows the error noted above. Might be some other solutions in `base` or GH PG for this

**Comment by ryandesign** [comment]
I haven't followed all the changes that have happened, but netpbm hasn't need any manual overrides for this situation before, so it seems crappy for it (and undoubtedly countless other ports that are set up similarly) to suddenly need manual overrides now. It should be handled by base and/or the github portgroup, as it has been so far.

**Comment by michaelld** [comment]
@ryandesign agreed! My main purpose of these PRs of recent is to get attention to the `extract.rename` changes that are not yet part of a release and try to get them fixed -- preferably in `base` or a PG -- before the next release happens. Changes to the Portfile itself should be rare & hopefully as this feature develops these Portfile changes can be reverted.

**Comment by jmroot** [comment]
Fixed in 07931f78b1c476d3f7c5d9ed7baa8b895c12f81b.

**Pull request closed without merging**
