### PR TITLE
teg: update to 0.12.0

### PR DESCRIPTION
**Pull request by evanmiller**
#### Description

Move to the new GitHub home and get rid of outdated GConf stuff.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by evanmiller** [comment]
CI needs a restart (dependencies failed to install)

**Comment by evanmiller** [comment]
Looks like `libnice` is not installing, will need to research

**Comment by pmetzger** [comment]
@evanmiller any progress?

**Comment by evanmiller** [comment]
@pmetzger Maybe just restart CI, `libnice` builds OK according to the build bots.

**Comment by pmetzger** [comment]
restarted.

**Comment by pmetzger** [comment]
@evanmiller ?

**Comment by evanmiller** [comment]
Failing on libnice again. I have no idea why. libnice is all green on the Build Bots.

**Comment by pmetzger** [comment]
Does this build correctly for you?

**Comment by evanmiller** [comment]
The port builds correctly on my 10.6 test machine. If merged I will keep an eye on build bots to see if we can get any more info on the libnice problem.

**Pull request merged**
