### PR TITLE
giter8: update to 0.13.1

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.1 21C52 x86_64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
LGTM. Anyone else?

**Comment by ryandesign** [comment]
Please make 2 commits: 1 to reformat the whitespace and 1 to update the port. By combining both into one, it's impossible to see what functional changes are being made.

**Comment by catap** [comment]
@ryandesign to be honest this port has been rewritten from scratch. This include different way to install giter8 which was suggested by upstream here: https://github.com/foundweekends/giter8/pull/644

**Comment by catap** [comment]
@mascguy what should we do with this one?

**Comment by catap** [comment]
@ryandesign ping here!

**Pull request merged**
