### PR TITLE
bind9: use https, fix livecheck

### PR DESCRIPTION
**Pull request by l2dy**
#### Description
```
$ curl -I http://www.isc.org
HTTP/1.1 301 Moved Permanently

Location: https://www.isc.org/
```

### CODE REVIEW

**Comment by danielluke** [comment]
I'm glad the process worked normally for this - but I don't think I ever got email about this when it was assigned or when the review was requested.

**Comment by l2dy** [comment]
@danielluke GitHub is responsible for that, maybe you should check your [notification settings](https://github.com/settings/notifications)?

**Comment by danielluke** [comment]
They're set to send me mail. It looks like I did receive messages, but they all have List-Id set, so they got filtered into a folder with other macports-ports messages and I missed them (since macports-ports gets too much mail).

**Comment by pmetzger** [comment]
Filter them separately.

**Comment by danielluke** [comment]
@pmetzger that's not really helpful. Filtering on 'To' isn't useful, normally filtering on List-Id works perfectly, but it looks like github behavior breaks that. I'll start a thread on macports-dev to see how others deal with it. I can collect some data and put a recipe on the wiki to help others out too.

**Comment by pmetzger** [comment]
I filter github stuff on List-Id and it works fine. The problem is you're filtering multiple lists into one box. If you only use the word "macports" in the List-Id to filter you won't separate out the github traffic.

**Comment by danielluke** [comment]
That's not an accurate description of how I'm filtering or of the problem. For example, the message that was sent to me with your above comment has this List-Id:

List-ID: macports/macports-ports <macports-ports.macports.github.com>

I'm not going to look at all github macports-ports mail in any kind of timely fashion. I do care about mail for ports that I maintain, and would be happy to see those messages.

**Comment by pmetzger** [comment]
> I'm not going to look at all github macports-ports mail in any kind of timely fashion. I do care about mail for ports that I maintain, and would be happy to see those messages.

It won't send you mail on all of them by default. If you don't watch the repository, it will only send you notifications about things you maintain or are mentioned in.

**Comment by danielluke** [comment]
At the expense of me looking through that mailbox when I do have time and commenting or contributing on issues where I'm not mentioned or aren't about things I maintain.

Not optimal, but at least I'll respond to PRs against my ports that way.

**Comment by pmetzger** [comment]
> At the expense of me looking through that mailbox when I do have time and commenting or contributing on issues where I'm not mentioned or aren't about things I maintain

Again, if you don't ask it to, it won't send you email on any issue where you're not @-mentioned.

**Comment by danielluke** [comment]
I want to differentiate between @-mentions and all mail - I don't think it's that hard to understand. With the macports trac setup, I could get both the firehose of all information from the mailing list and get messages directed specifically to me filtered into different boxes very easily. Ideally I'd like to replicate that.

**Pull request merged**
