### PR TITLE
openrct2: update to 0.3.5, update objects

### PR DESCRIPTION
**Pull request by Tatsh**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.0.1 21A559 x86_64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Any idea why the CI failed?

**Comment by Tatsh** [comment]
Unfortunately `objects.zip` got updated and it does not have a distinct filename with version, so the old version is in MacPorts' distfiles. I think it needs to be blocked from being mirrored as well as `title-sequences.zip`.

**Comment by Tatsh** [comment]
@pmetzger The files `objects.zip` and `title-sequences.zip` should be deleted from here: https://distfiles.macports.org/openrct2/ . Otherwise installation errors will occur unless the user disables the main MacPorts distfiles host.

**Comment by pmetzger** [comment]
Shouldn't new versions be fetched because the portfile has been updated?

**Comment by Tatsh** [comment]
Well I tried last night and still got the checksum error. Had to manually download objects.zip into the correct place.

@ryandesign thoughts?

**Pull request merged**
