### PR TITLE
openssh: update to 8.4p1, drop keychain patch and hpn variant

### PR DESCRIPTION
**Pull request by Schamschula**
update gsskex patches

#### Description

openssh has been updated several times upstream since the last MacPorts update.
MacPorts has tried to maintain the unsupported Apple keychain patch.
Homebrew dropped support for this patch in 2016: https://archive.is/hSB6d#10%25

7.7p1, in 2018,  was the last version to support the hpn option in FreeBSD Freshports:
https://www.freshports.org/security/openssh-portable/

###### Type(s)

- [x] update
- [x] security fix

###### Tested on

macOS 10.14.6 18G6042
Xcode 10.3 10G8

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by neverpanic** [comment]
This now has a merge commit – please rebase it so the merge commit goes away.

**Comment by Schamschula** [comment]
I'm having a bit of an issue squashing things tonight...

**Comment by Schamschula** [comment]
I have no idea where the merge commit came from.

**Comment by Schamschula** [comment]
Something in the GitHub workflow changed. I used to be able to squash commits w/o any issues. Given that I'm stuck removing one last file, I'll start over.

**Comment by Schamschula** [comment]
See previous comment.

**Pull request closed without merging**
