### PR TITLE
vulkan-loader: new port

### PR DESCRIPTION
**Pull request by eintw1ck**
###### Tested on
macOS 10.14.4 18E226
Xcode 10.2 10E125

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by eintw1ck** [comment]
How can I make sure that python3 is in path for the build process in the Portfile?

**Comment by cjones051073** [comment]
> How can I make sure that python3 is in path (as python) for the build process in the Portfile?

You cannot. You should declare a dependency on a particle MacPorts python version, say 3.7, then configure the build to use the particular *versioned* python excitable that port provides. i.e. `${prefix}/bin/python3.7`

**Comment by cjones051073** [comment]
@eintw1ck not sure what you changed, but guess you fixed then python configuration issue ?

Xcode 7 failure seems expected, given MoltenVK’s limitations.

**Comment by cjones051073** [comment]
There was a bug in the portfile leading to build failures in the build bots, due to them not finding cmake. This was caused because you explicitly set the build deps, not appending to them, and thus removed the cmake dependency from the portgroup. I have pushed an update that hopefully will fix this.

**Comment by eintw1ck** [comment]
@cjones051073 Ah! thank you, I'm still learning how macports and the portfiles work :)

**Pull request merged**
