### PR TITLE
giflib: update to 5.1.4

### PR DESCRIPTION
**Pull request by Rechi**
###### Type(s)
- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G5019
Xcode 9.2 9C40b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
Thank you for suggesting this update, but it is most likely more complicated than just updating the giflib port. I expect you will also need to touch every port that uses the giflib port. See https://trac.macports.org/ticket/49876.

**Comment by pmetzger** [comment]
Hrm. I hadn't looked at this before because it is Ryan's bailiwick, but I just noticed the CI failed?

**Comment by cjones051073** [comment]
So whats the status of this PR ? We should either close it, or make progress.

**Comment by kencu** [comment]
it's failing the fetch, for one.

**Comment by cjones051073** [comment]
Closing due to lack of progress. Please reopen if/when you wish to proceed.

**Pull request closed without merging**
