### PR TITLE
argon2: Don't use rpath or -march=native; do install manpage

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

argon2: Don't use rpath or -march=native; do install manpage

###### Type(s)

- [X] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.6 17G14019
Xcode 9.4.1 9F2000

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
This one just chewed me too, when updating php73 on Tiger.

**Comment by viunyk** [comment]
Hi, could you please help me?
What I should do to apply these changes and fix this problem on localhost?

**Comment by kencu** [comment]
our 72hr timeout policy has just expired on this PR, and Kurt has been around MP without commenting here, so given that everything is broken until this is committed, we'll commit this today and you should be good again.

**Comment by kencu** [comment]
seeing no objections, and with all php installations broken at present, we'll push this.

**Comment by ryandesign** [comment]
> with all php installations broken at present

All PHP installations were not broken without this. It had worked on my system prior to this change. But thank you for merging it.

**Comment by kencu** [comment]
I took this as to indicate at least some found it broken <https://trac.macports.org/ticket/61735> but perhaps they were mistaken, and it was really working correctly all along.

**Pull request merged**
