### PR TITLE
python/py-awscli: Update to @1.14.7

### PR DESCRIPTION
**Pull request by emcrisostomo**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix
- [x] update

###### Tested on

macOS 10.13.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by emcrisostomo** [comment]
I updated the PR to update it to 1.14.5 instead. I had an issue (that's why I updated it just to 1.12.x), but now I pushed another PR to `python/py-botocore` (https://github.com/macports/macports-ports/pull/1090) on which this PR depends.

If there's a better way to manage dependencies between port updates, please let me know.

**Comment by mojca** [comment]
If one PR depends on another PR it sometimes makes sense to simply add another commit to an existing PR. In this case it makes even more sense because the maintainer is the same and very often dependent ports need to be updated when a dependency changes in some important way. I'm not sure whether this is the case here as it's a python module. For compiled libraries one would certainly need a revbump.

**Comment by emcrisostomo** [comment]
Thank you very much @mojca. I'm then adding the changeset on which this PR depends into and I'm going to close #1090.

**Comment by emcrisostomo** [comment]
Gentle bump!

@mojca Do you have any idea whether Travis build's timing out is normal?

**Comment by mojca** [comment]
That's a limitation of a free service. And yes, it's expected. Our alternative would be to run the builds on buildbot, but then someone would need to implement all the security measures which is highly non-trivial.

**Comment by mojca** [comment]
Just to explain. We usually give maintainers three days to respond to tickets, so this already counts as maintainer timeout for @pixilla and we are now free to merge this PR. It looks ok to me, those Travis builds that did not time out were passed successfully, so nothing to worry about.

The only other change that someone (either you or any committer) needs to do is something like `git rebase -i HEAD~7` to squash the commits together and end up with two commits only without any merges etc. (I'm currently not on my working machine to do it straight away.) If you happen to do it, you may also delete the `python/` prefix and the `@` sign before the version number (those cosmetic fixes are mostly irrelevant, but we strive to keep the history simple, so we do try to avoid too many commits and merges).

**Comment by emcrisostomo** [comment]
Thanks @mojca, I'll do the squash as soon as I can. Thank you.

**Comment by emcrisostomo** [comment]
Hi @mojca, I squashed the commits and I'm afraid I squashed the too much: instead of leaving two commits (one per port), I left only one commit. Is that a problem? I'm not sure how I could revert this change.

**Comment by mojca** [comment]
```
git reset HEAD~
git add python/py-botocore/Portfile
git commit
git add python/py-awscli/Portfile
git commit
git push -f ...
```

**Comment by emcrisostomo** [comment]
Thanks @mojca!

**Pull request merged**
