### PR TITLE
Upgrade all users to KDE PortGroup 1.1

### PR DESCRIPTION
**Pull request by grimreaper**
I tested taglib-devel and kde/koffice2-devel

### CODE REVIEW

**Comment by TheStormN** [comment]
It seems like Travis error not caused by the MR. Could someone trigger a new build?

**Comment by pmetzger** [comment]
I'm going to merge this if @grimreaper confirms the two ports build for him after the change is made.

**Comment by grimreaper** [comment]
They built at the time I made this change. I am not aware of anything that might cause this to differ now.

**Comment by pmetzger** [comment]
Thanks. Merged.

**Pull request merged**
