### PR TITLE
MoarVM: fix build on 10.8 and earlier

### PR DESCRIPTION
**Pull request by evanmiller**
#### Description

Attempt to fix failing build bots, e.g. https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/83899

Tested locally through configure on an unaffected system.

See: https://github.com/MoarVM/MoarVM/issues/1149
Closes: https://trac.macports.org/ticket/64587

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mojca — APPROVED** [review]
Looks good to me. But you probably wanted to get #14336 merged first?

**Comment by evanmiller** [comment]
> Looks good to me. But you probably wanted to get #14336 merged first?

These are parallel changes.

**Comment by mojca** [comment]
> > Looks good to me. But you probably wanted to get #14336 merged first?
> 
> These are parallel changes.

Oh, I failed to notice that this is about the conflicting port rather than about a dependency.

**Comment by evanmiller** [comment]
@mojca The "master plan" here is:

1) move libtommath into a dependency
2) fix up MoarVM on all legacy systems
3) update MoarVM to the latest version

**Comment by barracuda156** [comment]
@evanmiller Why don't we allow macports-gcc-7 and later for PowerPC? Otherwise it forces to build gcc6, which otherwise is redundant.

P. S. You have already replied there, but for others' reference: @2022.02 version will require adding another flag to bypass mimalloc errors: https://github.com/macports/macports-ports/pull/14359?notification_referrer_id=NT_kwDOBXwLlrMzMzI3NDk1MTU4OjkyMDE1NTEw#issuecomment-1080319781

**Comment by evanmiller** [comment]
> @evanmiller Why don't we allow macports-gcc-7 and later for PowerPC? Otherwise it forces to build gcc6, which otherwise is redundant.

This section of the Portfile predates Ken's GCC7 work. The whole block can likely be removed.

**Pull request merged**
