### PR TITLE
git: update to 2.10.2

### PR DESCRIPTION
**Pull request by xeron**
* new version 2.10.2
* remove `Id` line

### CODE REVIEW

**Comment by larryv** [comment]
@ci42 removed the Python variants a few weeks ago (macports/macports-ports@e08b6cdac7b5c880d19a3b4e188e3ff11ffa0b9b), and I do not think we should restore them. As a whole, we've been moving away from providing Python/Perl variants.

**Comment by mojca** [comment]
I don't really see any added benefit of python variants for git either.

**Comment by xeron** [comment]
What's the problem with python variants? Git is the only port on my system which prevents me from removing python27 and keeping only python35.

**Comment by raimue** [comment]
I guess the variant was removed as we no longer want to support python26. If git works with Python 3, I see no reason not to add a variant for +python35. I don't think we need to support python34 much longer, but I would leave that to the maintainer.

If python is a hard dependency of git, there needs to be a check that at least one python variant is always selected.

**Comment by xeron** [comment]
Yep, it will use `python27` by default:

```
~/workspace/devel/macports-ports[git-python3]$ sudo port -u install git
--->  Computing dependencies for git
The following dependencies will be installed: 
 db48
 python27
 python2_select
```

I can remove `python34` if we don't want to support it.

**Comment by larryv** [comment]
Does Python 3 actually work? The current Git documentation [suggests not][doc]:

> - Python version 2.4 or later (but not 3.x, which is not
> 	  supported by Perforce) is needed to use the git-p4 interface
> 	  to Perforce.

[doc]: https://github.com/git/git/blob/be5a750939c212bc0781ffa04fabcfd2b2bd744e/INSTALL#L147

**Comment by xeron** [comment]
@larryv oops, you're right. I tried to search for supported pythons version but overlooked this information.

I've removed commit for python variants.

**Pull request closed without merging**
