### PR TITLE
Add lua54 subport and lua_select

### PR DESCRIPTION
**Pull request by natecraddock**
#### Description

Adds `lua54` as a subport to `lua`. Adds a new port `lua_select` for selecting the default version of Lua.

I based this off the patches for lua and lua52, but I did make a small modification when I noticed that readline was not working. This should be fixed in the other versions of Lua as well.

Long term I think it would be good to also add the `lua50` and `lua51` to the select group, and also as subports, but I think this is enough for now. I am also interested in being a maintainer of Lua in the future.

Note that I'm really new to MacPorts and Tcl, so if there is anything to be improved (even small things) please let me know!

Also, with the `lua_select` port, I followed examples I saw for other tools, but I couldn't find documentation otherwise so hopefully it is correct. I also wasn't sure where to place the port so currently it is in the `./lua` directory.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 12.6 21G115 arm64
Command Line Tools 14.0.0.0.1.1661618636

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by natecraddock** [comment]
@dbevans I hope you don't mind me pinging you. The guide mentions to send a message on the mailing list after a few days of no activity, but I figured I would try this first. You were the last person to commit updates for Lua, and I noticed you are active in committing to macports

**Comment by halostatue** [comment]
Upgrades to the lite-xl require this port because it looks like lite-xl 2.1 requires Lua 5.4 (and no longer supports luajit).

**Review by harens — COMMENTED** [review]
I maintain the lite-xl port, so updating lua was on my todo list. I was just about to submit a PR until I see you've already done it! Thanks for that @natecraddock :)

My main comment is that the high level port should probably be lua5.4, with a 5.3 subport instead. This would then require modifying the patches for lua5.3 so that it has the `-5.3` suffix.

My changes, as well as some other fixes, can be found here: https://github.com/harens/macports-ports/tree/lua/lang/lua. Please feel free to copy anything, or I might open a separate PR later if required. Thanks for your first contribution to MacPorts @natecraddock! 🎉

**Comment by harens** [comment]
> @harens The reason I made lua5.4 as a subport is because I was under the impression that updating the main lua package to 5.4 would require updating all the ports that depend on lua to point to the 5.3 subport.. but I'm really new to this so 🤷‍♂️

You're completely right. This was discussed back in https://trac.macports.org/ticket/46621 with the update from 5.2 -> 5.3, so it's not a straightforward process.

> Anyway, I'm really busy right now and don't have the time to fix this. Feel free to close/revise this PR!

Thanks for the time you put into the PR @natecraddock :)

**Pull request closed without merging**
