### PR TITLE
poedit1: revive old Poedit port for old OS

### PR DESCRIPTION
**Pull request by l2dy**
This partially reverts commit e70cecc5b3e9ffe4fcaf4d61dd781872833bd06d.

### CODE REVIEW

**Comment by mojca** [comment]
If you really want to support 10.6 and lower: what about some if-else in the main port to provide different version of the same port for older oses? I don't know why one would want to use the old version on 10.13.

**Comment by l2dy** [comment]
The two Portfiles differ greatly:
* different type of fetch from different locations
* different handling of dependencies
* new version uses Xcode

See also `TeXShop` and `TeXShop4`. A user might install `TeXShop` and then (from port notes) realize it's a very old version released years ago.
> TeXShop 2.47 is designed for OS X 10.6 Snow Leopard and older; for OS X 10.9 Mavericks and newer you may prefer to use the TeXShop4 port.

But users are less likely to install `poedit1` accidentally, so I think it's OK in this case.

**Comment by pmetzger** [comment]
Could we refuse to install on the newer OS? That would seem to be a good way to avoid accidents. Generally, of course, we need a way of saying "not for these OS versions", but I can't remember the Trac ticket for that.

**Comment by l2dy** [comment]
While usually no one would install the old version on newer OS, I don't think it's a good idea to refuse to install for this reason and it will make Travis builds fail. I'll add a note like the one in `TeXShop`.

**Comment by ryandesign** [comment]
> See also TeXShop and TeXShop4

...where [the same suggestion](https://lists.macports.org/pipermail/macports-dev/2018-April/038342.html) (to combine them) was made, and Marius replied by private email to concur. The differences between the versions can be handled with an `if {...} else {...}` block. However, if it makes the portfile overly complicated, it's acceptable to make the older version available in a separate port.

**Comment by pmetzger** [comment]
`if {...} else {...}` still seems optimal to me, too. :(

**Comment by pmetzger** [comment]
So what do we do to move this forward?

**Comment by l2dy** [comment]
See top comment:
> *WIP*, need to test the transmem variant with db48.

**Comment by pmetzger** [comment]
@l2dy Cool. So the next person who has to act is you, and that test is the next step. Thank you. (I like clarity on who needs to do the next thing and what the thing is, it makes it easier to figure out what the status of any given PR is.)

**Comment by l2dy** [comment]
TM works, but throws several wxWidgets Debug Alerts.

> wxWidgets Debug Alert
```
/opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.0/include/wx-3.0/wx/strvararg.h(456): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type

Call stack:
[00] int wxString::Printf<unsigned long>(wxFormatString const&, unsigned long) 
[01] PoeditFrame::AutoTranslateCatalog()     
[02] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) 
[03] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) 
[04] wxEvtHandler::TryHereOnly(wxEvent&)     
[05] wxEvtHandler::ProcessEventLocally(wxEvent&) 
[06] wxEvtHandler::ProcessEvent(wxEvent&)    
[07] wxWindowBase::TryAfter(wxEvent&)        
[08] wxEvtHandler::SafelyProcessEvent(wxEvent&) 
[09] wxMenuBase::SendEvent(int, int)         
[10] wxMenu::HandleCommandProcess(wxMenuItem*, wxWindow*) 
[11] -[wxNSMenuItem clickedAction:]          
[12] -[NSApplication(NSResponder) sendAction:to:from:] 
[13] -[NSMenuItem _corePerformAction]        
[14] -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] 
[15] -[NSMenu performActionForItemAtIndex:]  
[16] -[NSMenu _internalPerformActionForItemAtIndex:] 
[17] -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] 
[18] NSSLMMenuEventHandler                   
[19] DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) 
[20] SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) 
Do you want to stop the program?
You can also choose [Cancel] to suppress further warnings.
```

**Comment by l2dy** [comment]
Fixed the format specifier with a patch.

**Pull request merged**
