### PR TITLE
arm-none-eabi-*: Update to latest version

### PR DESCRIPTION
**Pull request by judaew**
#### Description

The `arm-none-eabi-*` ports have not been updated for a very long time. The `gdb` uses version 7.1, which I think is from 2010. So I took the liberty of updating the ports.

I'm not good at building such difficult ports, so I need help. These changes need to be well tested. Most of the changes for `arm-none-eabi-gdb` I took from `gdb` port. ~~But needs to update the `crossgdb::fixinfo` function, so that the port doesn't conflict with `gdb`.~~

I think the `arm-none-eabi-gcc` port should probably work correctly, but without support for `arm64` yet.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.0.1 21A559 x86_64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by judaew** [comment]
I compiled the project today with `arm-none-eabi-gcc`, everything worked correctly for me.

**Comment by mascguy** [comment]
Added @cjones051073 and @kencu as reviewers, as they can provide good toolchain-related feedback and insight.

**Comment by judaew** [comment]
Thanks @mascguy

**Review by kencu — COMMENTED** [review]
I won't be able to build this to actually test it, but scanning what was done looks reasonable to me.

**Comment by judaew** [comment]
I can't fully test `arm-none-eabi-gdb`, but the simple debugging work for me.

**Comment by judaew** [comment]
Thank you @kencu

**Comment by mascguy** [comment]
> I won't be able to build this to actually test it, but scanning what was done looks reasonable to me.

Thanks Ken!

@cjones051073 ?

**Comment by judaew** [comment]
@mascguy Thanks for merging 🌟

**Pull request merged**
