### PR TITLE
poedit: new port @2.0.7

### PR DESCRIPTION
**Pull request by l2dy**

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM.

**Comment by mojca** [comment]
See https://github.com/macports/macports-ports/commit/e70cecc5b3e9ffe4fcaf4d61dd781872833bd06d.

**Comment by mojca** [comment]
Strange. No dependency on wxWidgets?

**Comment by l2dy** [comment]
Merged as 438bed1dafbb47ae0dd3597dd1b3a08ffd9013c3.

**Pull request closed without merging**
