### PR TITLE
deluge: switch to python312 and boost181 to match libtorrent-rasterbar, fix dependencies

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

`libtorrent-rasterbar` has been switched to python312 earlier without considering `deluge`, which uses python311 by default. In addition, it uses a different Boost.
Also, on of its Python dependencies does not build at all, which leaves it broken.

Fix this.

P. S. Running `deluge` also requires these:
https://github.com/macports/macports-ports/pull/24679
https://github.com/macports/macports-ports/pull/24658

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
deluge

And now it works on PowerPC.

**Comment by barracuda156** [comment]
CI fail due to some dependencies of py27 subports. (Likely something was thrown away without checking it is has dependents.) I merely add py312 subports to those ports; py27 is not my concern here, and I do not plan to fix it.

On a side note, `deluge` itself should be updated to 2.1.1: https://github.com/deluge-torrent/deluge/tags
I can handle that tomorrow after verifying it works. (Looks like no strict requirements for dependencies being added, so perhaps it will.)

**Comment by pmetzger** [comment]
We should not be fixing anything related to python 2.7, we should be purging things connected to python 2.7.

**Comment by barracuda156** [comment]
@pmetzger I do not fix anything for Python 2.7 here. Since `libtorrent-rasterbar` was switched to Python 3.12, `deluge` must use the same, and only `py312-*` dependencies are relevant.

These do build and work, which can be seen in details for CI.

**Comment by pmetzger** [comment]
Supporting Tiger is not a primary goal of the project.

**Comment by barracuda156** [comment]
> Supporting Tiger is not a primary goal of the project.

Sure, but there is no goal to break something for Tiger either.

**Comment by pmetzger** [comment]
@barracuda156 If someone maintains a port and wants to update it in a way that does not immediately support Tiger, they are free to do so. People are not expected to spend significant time and effort on such things. If you want to spend time on it, to the extent that it doesn't harm anything else, that's fine.

**Comment by barracuda156** [comment]
@pmetzger I agree, but _spending time_ to break a port for others makes no sense.

**Comment by pmetzger** [comment]
If someone wants to update stuff, don't harangue them about support for machines almost no one uses.

**Comment by barracuda156** [comment]
With Python ports I have been pressured to _remove_ stuff. This takes a lot of time _and_ potentially introduces breakages.

I am not expecting anyone to support old systems actively (regardless of my view on the matter, it simply won’t be done anyway, so expecting otherwise is silly). But often it takes more time to break stuff than to keep what works unbothered. On many occasions retaining support for older systems amounts to a few lines of copy-paste code and 5 minutes extra spent. While nobody is obliged to do anything whatsoever, I do think this is a good practice to maintain support at least in this sense.

**Comment by pmetzger** [comment]
If you mean I pressured you not to put in fallback support of security critical software for very obsolete versions of Python that's right. You're not winning points by trying to explain why we should be maintaining insecure software in MacPorts.

**Pull request merged**
