### PR TITLE
Pure portgroup overhaul

### PR DESCRIPTION
**Pull request by agraef**
#### Description

2nd attempt (cf. #1573). Updates the pure port group so that it installs from Github now. Made sure that all required tarballs are on GH. Also updated a few modules along the way. These are all trivial updates to the latest versions (rev. 452bbf73e7272e91ae1b45466befdcdb7c27133e), except the following:

- faust2pd, pure-faust and pd-faust were already updated recently in #1272, #1273 and #1274; these were reworked in rev. 452bbf73e7272e91ae1b45466befdcdb7c27133e so that they use the (new) pure port group now

- pure-gen 0.21 (rev. fe90b226273e5e36c2926fe6f4e0a09012638226): I broke this out into a separate commit because the older version didn't build any more, and some adjustments in the build target and dependencies were needed to make the port build again using the new `maintainer-build` target (which avoids an external dependency on the language-c package and is also being used on Linux and Windows now)

- gnumeric-pure (rev. e59be304a725a7eb26ec38e5b502796d591592e3): some dependencies won't build on Sierra any more, so I completely removed this port for now. I don't know of anyone who's using it, it pulls in a gazillion of dependencies, and it's generally just a major headache to maintain because the dependencies are moving targets. So I'm not really maintaining this module any more (it's not supported on Ubuntu and Windows either, for the same reasons). If anyone else wants to keep maintaining it, be my guest. I can also leave it in (by removing rev. e59be304a725a7eb26ec38e5b502796d591592e3), but then the Travis CI will most likely fail on it, so I really recommend getting rid of it *now*.

Please note that this PR *will* be required for all module updates from now on, as all new module releases will be on GH.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.12.6 16G1314
Xcode 9.2 9C40b

Tested all ports included here, and of course also the modified port group.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? (N/A)

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`? (N/A)
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by agraef** [comment]
Well, the Travis builds all timed out after pure-g2. What now?

**Comment by ryandesign** [comment]
Sorry for creating additional work for you, but thank you!

**Comment by mojca** [comment]
This looks ok to me to commit.

**Comment by agraef** [comment]
@ryandesign no worries, I'm glad that it's all done and dusted now, that really was the cleanest solution. And thanks for fixing the little glitch with pure-lilv, looks like this somehow escaped my attention.

**Pull request merged**
