### PR TITLE
libreoffice: update to 7.2.3.1

### PR DESCRIPTION
**Pull request by Tatsh**
#### Description

Bump LibreOffice to 7.2.3.1

Also attempting to use system libcmis in the second commit. I will remove it if it does not work in CI.

I cannot test this locally as glm does not build on Monterey.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.0.1 21A559 x86_64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
CI failed. @Tatsh, what would you like to do?

**Comment by Tatsh** [comment]
Issue is related to a dep:

>Installing dependency (243 of 293) 'cargo-c' with variants '' (requesting '') ... [FAIL]

**Comment by Tatsh** [comment]
Which is related to OpenSSL 3. I guess it needs to rerun?

**Comment by pmetzger** [comment]
I'll try the CI again. I assume you've checked the build yourself?

**Comment by Tatsh** [comment]
> I'll try the CI again. I assume you've checked the build yourself?

I can't because the dependency `glm` is broken on Monterey.

**Comment by pmetzger** [comment]
Should we fix the dependency? This would seem like an important port. We're also not getting good feedback from the CI so being able to test locally would be good.

**Comment by Tatsh** [comment]
I'm willing to wait till glm is fixed. There has been no activity on that port and the issue has a ticket.

**Comment by pmetzger** [comment]
@Tatsh Sometimes the best way to get something to happen is to do it yourself...

**Comment by Tatsh** [comment]
Fixed glm with this PR, and not going to use system CMIS as it won't get past configure phase.

**Comment by Tatsh** [comment]
@pmetzger if you don't want to wait for CI, this built perfectly on my Monterey machine.

**Comment by pmetzger** [comment]
Merged. That said, I think the glm fix is a bit brute force. Which is to say, if there are warnings, they probably should get fixed.

**Comment by Tatsh** [comment]
> Merged. That said, I think the glm fix is a bit brute force. Which is to say, if there are warnings, they probably should get fixed.

If you want to do it differently let me know. The fix in code would be to explicitly cast, and the other possible fix is to add another exception to the flags: `-Wno-implicit-int-conversion`. You can see on lines 9 and 10 of the file upstream already sets a lot of exceptions after `-Werror`.

**Comment by pmetzger** [comment]
Is upstream maintained? Perhaps you should report the issue to them?

**Comment by Tatsh** [comment]
Not really sure what happened but they disabled issues on GitHub. I can make a PR to get their attention. https://github.com/g-truc/glm

**Pull request merged**
