### PR TITLE
fontforge: update to 20190801

### PR DESCRIPTION
**Pull request by kencu**
minor change in distfile layout
change to python37 as upstream recommends python > 3
add woff2 support

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 10K549
Xcode 4.2 4C199 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of some binary files?

### CODE REVIEW

**Comment by kencu** [comment]
@mojca -- I believe you have an interest in this port.

**Comment by mojca** [comment]
> @mojca -- I believe you have an interest in this port.

Yes, but hardly any time to test or even use it at the moment; GSOC & [MacPorts Meeting](https://trac.macports.org/wiki/Meetings/MacPortsMeeting2019) currenly eat enough of my already-lacking free time.

If you are willing to check whether lilypond (@lemzwerg) & pdf2htmlex build ok to start with (or maybe require revbump), that's already fine by me. I'm not even sure if pdf2htmlex is currently functional.

**Comment by lemzwerg** [comment]
LGTM.  On my GNU/Linux box I normally use the git version of FontForge to build LilyPond; as soon as this pull request is in `macports-ports` I will rebuild `lilypond-devel` – I don't expect any special problems (I don't use the `lilypond` port).

[Note that yesterday I submitted #5185 to clean up `lilypond-devel` a bit.]

In general, there are some rounding issues with removal of overlapping outlines; however, these FontForge problems are generic (nobody is taking care of this particular piece of code currently) and not specific to the Mac.

**Comment by kencu** [comment]
Thanks!

**Pull request merged**
