### PR TITLE
py-scipy: update to 1.14.1

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
Apologies.... I messed something up with PR #26441 and there are parse failures now (even though they are not there locally). Anyway, let's just close that PR and have here only the changes related to `py-scipy` and dependents.

- update to latest upstream version
- drop py38, add py313 subport (to py-scipy as well as dependents)
- pin to 1.13.1 for py39 subport
- switch to PyPI
- add BLAS/LAPACK variants
- add myself as co-maintainer
- completely switch to 'meson' as build backend

Closes: https://trac.macports.org/ticket/70931
Closes: https://trac.macports.org/ticket/69538

@barracuda156 @aeiouaeiouaeiouaeiouaeiouaeiou same invitation to test building on older OSes. Please note that we have switched not completely to the `meson` backend; that is what upstream has done and thus not negotiable ;)

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 15.1 24B83 x86_64
Xcode 16.1 16B40

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
huh... the same parse failure is still present here as well. That must be another problem that is not related/caused to/by this PR I think

**Comment by barracuda156** [comment]
@reneeotten I will try the fix tomorrow once back to the machine. Thank you for addressing that.

**Comment by reneeotten** [comment]
> @reneeotten I will try the fix tomorrow once back to the machine. Thank you for addressing that.

Perhaps it's fixed already by the patch I added, I can just not test it...

**Comment by barracuda156** [comment]
Yeah, I mean I will try running the build with your patch.

**Comment by barracuda156** [comment]
@reneeotten Your fix works as intended, `py-scipy` configured with no issues now. Thank you! 
Build is running, will update soon on the outcome. So far so good.

**Comment by barracuda156** [comment]
@reneeotten This may be worse:
```
In file included from ../scipy/special/special/specfun.h:4,
                 from ../scipy/special/special.h:6,
                 from ../scipy/special/_special_ufuncs.cpp:7:
../scipy/special/special/specfun/specfun.h: In instantiation of 'std::complex<_Tp> special::specfun::e1z(std::complex<_Tp>) [with T = float]':
../scipy/special/special/expint.h:17:40:   required from 'std::complex<_Tp> special::exp1(std::complex<_Tp>) [with T = float]'
   17 |     std::complex<T> outz = specfun::e1z(z);
      |                            ~~~~~~~~~~~~^~~
../scipy/special/_special_ufuncs.cpp:304:47:   required from here
  304 |          static_cast<func_F_F_t>(special::exp1), static_cast<func_D_D_t>(special::exp1)},
      |                                               ^
../scipy/special/special/specfun/specfun.h:2099:70: error: no match for 'operator*' (operand types are 'double' and 'std::complex<float>')
 2099 |             ce1 = -el - std::log(-z) + z*ce1 - copysign(pi, z.imag())*std::complex<T>(0.0, 1.0);
      |                                                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/gcc14/c++/complex:400:5: note: candidate: 'template<class _Tp> std::complex<_Tp> std::operator*(const complex<_Tp>&, const complex<_Tp>&)'
  400 |     operator*(const complex<_Tp>& __x, const complex<_Tp>& __y)
      |     ^~~~~~~~
/opt/local/include/gcc14/c++/complex:400:5: note:   template argument deduction/substitution failed:
../scipy/special/special/specfun/specfun.h:2099:70: note:   mismatched types 'const std::complex<_Tp>' and 'double'
 2099 |             ce1 = -el - std::log(-z) + z*ce1 - copysign(pi, z.imag())*std::complex<T>(0.0, 1.0);
      |                                                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/gcc14/c++/complex:409:5: note: candidate: 'template<class _Tp> std::complex<_Tp> std::operator*(const complex<_Tp>&, const _Tp&)'
  409 |     operator*(const complex<_Tp>& __x, const _Tp& __y)
      |     ^~~~~~~~
/opt/local/include/gcc14/c++/complex:409:5: note:   template argument deduction/substitution failed:
../scipy/special/special/specfun/specfun.h:2099:70: note:   mismatched types 'const std::complex<_Tp>' and 'double'
 2099 |             ce1 = -el - std::log(-z) + z*ce1 - copysign(pi, z.imag())*std::complex<T>(0.0, 1.0);
      |                                                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/gcc14/c++/complex:418:5: note: candidate: 'template<class _Tp> std::complex<_Tp> std::operator*(const _Tp&, const complex<_Tp>&)'
  418 |     operator*(const _Tp& __x, const complex<_Tp>& __y)
      |     ^~~~~~~~
/opt/local/include/gcc14/c++/complex:418:5: note:   template argument deduction/substitution failed:
../scipy/special/special/specfun/specfun.h:2099:70: note:   deduced conflicting types for parameter '_Tp' ('double' and 'float')
 2099 |             ce1 = -el - std::log(-z) + z*ce1 - copysign(pi, z.imag())*std::complex<T>(0.0, 1.0);
      |                                                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by barracuda156** [comment]
@reneeotten I will rebuild a few times, starting with just dropping out earlier related hacks to make sure that is not messing the build up.

**Comment by reneeotten** [comment]
@barracuda156 from the upstream bug report it looks like the SciPy folks tried their best to help out but we're kind of on our own to try and get this fixed, which is fair. 
I don't want to hold up this PR until you had the chance to look at things (we don't even know if it's PPC related or if it will fail on other, older OSes). So can you build version `1.11.4` if the rest of the Portfile remains the same? If so, then I'll merge this PR and once we figure out where the failures start to happen on the buildbots, I will restrict these earlier OSes to version 1.11.4.

**Comment by reneeotten** [comment]
Pushed a fix for the `${os.minor}` comparison to decide whether or not we are macOS 13.3+

**Comment by barracuda156** [comment]
@reneeotten Allow me one day please, if this can wait until tomorrow. I will see if I can fix it overnight and if not, will at least run the build on x86_64 to be sure if the error is SDK-related, arch-related or compiler-related.

**Comment by barracuda156** [comment]
@reneeotten Could you say how to enable normal terminal output, so that args passed to compiler are seen?

**Comment by reneeotten** [comment]
I think you're supposed to be able to add "-v" or "-verbose" as build  arguments but haven't tried. It would be nice to set an option in the meson PortGroup to toggle that or, if the output isn't too large enable by default. 

Another way is probably to look at the "ninja.build" file(s) that are generated.

**Comment by barracuda156** [comment]
Nah, I can’t figure it out, meson is a disaster, as usual. Annoyingly, it also restarts build from scratch if I modify any source files (not meson.build but just code). Can this be prevented? Normally MacPorts allows to resume the build as long as portfile is untouched.

**Comment by reneeotten** [comment]
I can probably take a look later tonight. Does the "introspect" option work after you build (and the build stops): 

https://mesonbuild.com/Commands.html#introspect

**Comment by barracuda156** [comment]
Ok, build was done from scratch every time because meson uses a temp dir which is removed by meson (not MacPorts) upon a failure. `-Cbuild-dir=` seems to set a proper, non-temp, build directory.

**Comment by barracuda156** [comment]
I have probably found a way to fix `cmath` mess in a neat way without reverting commits like earlier. (So 1.12.0 should be buildable, but to save some time I am back to debugging 1.14.1 build.)

**Comment by barracuda156** [comment]
@reneeotten Mystery solved. It is `legacysupport` breaking it somehow. I.e., if I cd to build folder and run the command manually, this fails:
```
36-50% sudo   /opt/local/bin/g++-mp-14 -I/opt/local/include/LegacySupport -Iscipy/special/_special_ufuncs.cpython-311-darwin.so.p -Iscipy/special -I../scipy/special -Iscipy/_lib -I../scipy/_lib -I../scipy/_build_utils/src -I../../../../../../../../Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -DNDEBUG -Wall -Winvalid-pch -std=gnu++17 -O3 -D_GLIBCXX_USE_CXX11_ABI=0 -isysroot/ -DSP_SPECFUN_ERROR -DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION -MD -MQ scipy/special/_special_ufuncs.cpython-311-darwin.so.p/_special_ufuncs.cpp.o -MF scipy/special/_special_ufuncs.cpython-311-darwin.so.p/_special_ufuncs.cpp.o.d -o scipy/special/_special_ufuncs.cpython-311-darwin.so.p/_special_ufuncs.cpp.o -c ../scipy/special/_special_ufuncs.cpp
In file included from ../scipy/special/special/specfun.h:4,
                 from ../scipy/special/special.h:6,
                 from ../scipy/special/_special_ufuncs.cpp:7:
../scipy/special/special/specfun/specfun.h: In instantiation of 'std::complex<_Tp> special::specfun::e1z(std::complex<_Tp>) [with T = float]':
../scipy/special/special/expint.h:17:40:   required from 'std::complex<_Tp> special::exp1(std::complex<_Tp>) [with T = float]'
   17 |     std::complex<T> outz = specfun::e1z(z);
      |                            ~~~~~~~~~~~~^~~
../scipy/special/_special_ufuncs.cpp:304:47:   required from here
  304 |          static_cast<func_F_F_t>(special::exp1), static_cast<func_D_D_t>(special::exp1)},
      |                                               ^
../scipy/special/special/specfun/specfun.h:2099:70: error: no match for 'operator*' (operand types are 'double' and 'std::complex<float>')
 2099 |             ce1 = -el - std::log(-z) + z*ce1 - copysign(pi, z.imag())*std::complex<T>(0.0, 1.0);
      |                                                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../scipy/special/special/error.h:27,
                 from ../scipy/special/sf_error_state.h:4,
                 from ../scipy/special/sf_error.h:3,
                 from ../scipy/special/ufunc.h:17,
                 from ../scipy/special/_special_ufuncs.cpp:1:
/opt/local/include/gcc14/c++/complex:400:5: note: candidate: 'template<class _Tp> std::complex<_Tp> std::operator*(const complex<_Tp>&, const complex<_Tp>&)'
  400 |     operator*(const complex<_Tp>& __x, const complex<_Tp>& __y)
      |     ^~~~~~~~
/opt/local/include/gcc14/c++/complex:400:5: note:   template argument deduction/substitution failed:
../scipy/special/special/specfun/specfun.h:2099:70: note:   mismatched types 'const std::complex<_Tp>' and 'double'
 2099 |             ce1 = -el - std::log(-z) + z*ce1 - copysign(pi, z.imag())*std::complex<T>(0.0, 1.0);
      |                                                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/gcc14/c++/complex:409:5: note: candidate: 'template<class _Tp> std::complex<_Tp> std::operator*(const complex<_Tp>&, const _Tp&)'
  409 |     operator*(const complex<_Tp>& __x, const _Tp& __y)
      |     ^~~~~~~~
/opt/local/include/gcc14/c++/complex:409:5: note:   template argument deduction/substitution failed:
../scipy/special/special/specfun/specfun.h:2099:70: note:   mismatched types 'const std::complex<_Tp>' and 'double'
 2099 |             ce1 = -el - std::log(-z) + z*ce1 - copysign(pi, z.imag())*std::complex<T>(0.0, 1.0);
      |                                                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/gcc14/c++/complex:418:5: note: candidate: 'template<class _Tp> std::complex<_Tp> std::operator*(const _Tp&, const complex<_Tp>&)'
  418 |     operator*(const _Tp& __x, const complex<_Tp>& __y)
      |     ^~~~~~~~
/opt/local/include/gcc14/c++/complex:418:5: note:   template argument deduction/substitution failed:
../scipy/special/special/specfun/specfun.h:2099:70: note:   deduced conflicting types for parameter '_Tp' ('double' and 'float')
 2099 |             ce1 = -el - std::log(-z) + z*ce1 - copysign(pi, z.imag())*std::complex<T>(0.0, 1.0);
      |                                                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
```
But this compiles fine:
```
36-50% sudo   /opt/local/bin/g++-mp-14 -Iscipy/special/_special_ufuncs.cpython-311-darwin.so.p -Iscipy/special -I../scipy/special -Iscipy/_lib -I../scipy/_lib -I../scipy/_build_utils/src -I../../../../../../../../Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -DNDEBUG -Wall -Winvalid-pch -std=gnu++17 -O3 -D_GLIBCXX_USE_CXX11_ABI=0 -isysroot/ -DSP_SPECFUN_ERROR -DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION -MD -MQ scipy/special/_special_ufuncs.cpython-311-darwin.so.p/_special_ufuncs.cpp.o -MF scipy/special/_special_ufuncs.cpython-311-darwin.so.p/_special_ufuncs.cpp.o.d -o scipy/special/_special_ufuncs.cpython-311-darwin.so.p/_special_ufuncs.cpp.o -c ../scipy/special/_special_ufuncs.cpp

36-50%
```

So nothing about powerpc, SDK, gcc, C++ ABI and what's not. It is a bug in our library.

**Comment by barracuda156** [comment]
I have opened a ticket for `legacysupport`: https://trac.macports.org/ticket/71272

For `scipy`, we cannot just throw it away, since it was added for some good reason. I will see what can be done about this now.

**Comment by barracuda156** [comment]
@reneeotten Ok, I got it building.
```
36-50% port -v installed py311-scipy | grep active 
  py311-scipy @1.14.1_0+gfortran+openblas (active) requested_variants='' platform='darwin 10' archs='ppc' date='2024-11-10T17:30:05+0800'
```

**Comment by barracuda156** [comment]
P. S. Now it should be linked correctly, I hope. Earlier usage of PG revealed some issue with that, when a dependency of scipy failed to build.

```
36-50% otool -L /opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/sparse/linalg/_propack/_zpropack.cpython-311-darwin.so
/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scipy/sparse/linalg/_propack/_zpropack.cpython-311-darwin.so:
	/opt/local/lib/libMacportsLegacySupport.dylib (compatibility version 1.0.0, current version 1.3.99)
	/opt/local/lib/libopenblas.0.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libgcc/libgfortran.5.dylib (compatibility version 6.0.0, current version 6.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 117.0.0)
```

**Comment by barracuda156** [comment]
@reneeotten Half of that patch already merged: https://github.com/scipy/scipy/pull/21861
Also see the comment there.

**Comment by barracuda156** [comment]
@reneeotten Sorry, I missed one reinplace file in the portfile, will fix it soon.

Testing now a fix from `numpy` upstream also.

**Comment by barracuda156** [comment]
@reneeotten Was `-Cbuild-dir=` not added to the PG or elsewhere? I am getting an error with `py-scipy` now (possibly unrelated to the port), and `meson` uses temporary dir again.

**Comment by reneeotten** [comment]
> @reneeotten Was `-Cbuild-dir=` not added to the PG or elsewhere? I am getting an error with `py-scipy` now (possibly unrelated to the port), and `meson` uses temporary dir again.
> 
> Update. No issues with `py-scipy`, there is some bug in the current OpenBLAS upstream.

I forgot... but it's added now 43e90e3a517276b6333aaeab0a4b7db65c5c20be

**Comment by barracuda156** [comment]
> there is some bug in the current OpenBLAS upstream.

The bug has been identified, but it only affects native optimizations on G5, so not that OpenBLAS is just broken.

**Pull request merged**
