### PR TITLE
exact-image: Use the right -arch flags and other flags

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

This PR began in an effort to fix the universal build failure I reported [here](https://trac.macports.org/ticket/57607). But there are so many things wrong in this build system that it took a larger effort to fix. I'm submitting it as a PR so that I can separate each logical change into its own commit, and to get a second opinion on whether I've done anything wrong. But it builds universal now for me, where it did not before. @MarcusCalhoun-Lopez, maybe you can take a look, since I'm changing a lot of stuff you added in the update to 1.0.1.

###### Type(s)

- [X] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.6 17G65
Xcode 9.4.1 9F2000 

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
> ```
> checking whether the C++ compiler works ... no
> A C++ compiler is not installed or does not work correctly.
> A C++ compiler is vital for exact-image - so you need to install it first.
> ```

That's not what it did on my system. Hmm...

**Comment by ryandesign** [comment]
Ah, I have the bash @4.4.23 port installed. Looks like some syntax I used doesn't work with macOS stock bash version 3.

**Comment by ryandesign** [comment]
Ok, this version of my modifications seems to work with bash 2, 3, or 4.

**Comment by pmetzger** [comment]
@ryandesign Will you be merging this on your own?

**Comment by ryandesign** [comment]
Yes, unless someone reviews it and finds something wrong with it.

**Pull request merged**
