### PR TITLE
octave: update to 6.1.0

### PR DESCRIPTION
**Pull request by kencu**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G6042
Xcode 11.3.1 11C504

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
@Schamschula FYI.

I'm not sure about how this might or might not affect the extensive octave ecosystem, but it builds and runs.

**Comment by kencu** [comment]
I think the two patches that fail to apply are no longer needed and will delete them if all agree.

**Comment by kencu** [comment]
mmm... the qt4 gui is still here, but it is not building for me at present on Mojave, at least. I'll try it on a couple of other systems. qt4 is meant to be removed in octave 7.0.

If we can't get the qt4 variant to build, then we might spin off octave5 as the last version of octave that did use qt4 for all the systems that can't run the needed version of qt5.

**Comment by kencu** [comment]
I'll reopen this later I think, once I sort out the qt4 issue.

**Comment by Schamschula** [comment]
@kencu FYI: Any version update to octave requires a revision bump to all octave packages.

**Comment by kencu** [comment]
I will reopen this so interested users can see how it works, try it out -- it is working fine for me with the qt5 variant on newer systems. But we either have to fix or remove the qt4 variant, and if we remove it, decide if we'll leave octave 5.x behind for those users with systems that can't support the qt5 variant of this port.

**Comment by Schamschula** [comment]
I don't think upstream is still supporting qt4. Best to remove it.

I certainly haven't installed octave other than with the qt5 variant in several years.

**Comment by kencu** [comment]
> I don't think upstream is still supporting qt4. Best to remove it.
> 
> I certainly haven't installed octave other than with the qt5 variant in several years.

I installed octave 5 with qt4 a few days ago, on Tiger PPC, and I have it installed qt4 on 10.5 and 10.6 as well.

Upstream says qt4 is deprecated, and will be removed in octave 7. They are not accepting bugs upstream, but give me a bit of time to see if I can get the qt4 variant working. If so, we can bring all the systems along another octave generation. If not, then then either stick with octave 5.x + the qt4 gui, or use octave 6+ without the gui (which is still pretty good, to be honest).

**Comment by kencu** [comment]
I have the qt4 variant building and running now. WIll update with proper patch shortly. The interface is not in English, but in a foreign language for some reason.... will see if I can fix that.

The qt5 variant also builds on 10.6.8, but there is some issue with it as no window shows up.

**Comment by kencu** [comment]
So this PR looks pretty much ready to go, as far as octave itself is concerned. 

The last time octave was bumped (4.x to 5.x) a large number of octave deps had to be individually rev-bumped, and some of them needed patches and similar to build. <https://github.com/macports/macports-ports/commit/6d31fd8e7db8e5cdfb8123babb73c5a7f233da0f>

I guess something similar might be needed here with this move to 6.1. I am expecting some help to fix any wreckage in octave deps that might be found with this. And how many of these octave deps might better be updated rather than rev-bumped is not clear at this moment in time.

**Comment by kencu** [comment]
except we now seem to have a conflict....

**Comment by Schamschula** [comment]
I've been waiting to update octave-video to version 2.0.0. It doesn't support octave 5.1.0.

**Comment by kencu** [comment]
Ok. I will go ahead and just rev-bump the same list as last time, and any others I can spot or find, and then push this.

**Comment by kencu** [comment]
OK, I revbumped nearly 100 deps.

This is fragile, so I will commit this in the morning unless someone does it sooner, or unless someone finds an issue.

**Pull request merged**
