### PR TITLE
samba4: fix error "get_user_groups: failed to get the unix group list"

### PR DESCRIPTION
**Pull request by ph7**
#### Description

Make samba4 work on macOS (Solves "get_user_groups: failed to get the unix group list" error message)

Steps to reproduce problem:

server:
/opt/local/sbin/smbd --debuglevel=4 --port=2000 --configfile=smb.conf --log-basename=. -F -i

client connection:
/opt/local/bin/smbclient -p 2000 '\\127.0.0.1\qemu'

Without the patch you then get
```
get_user_groups: failed to get the unix group list
```

with a smb.conf file:

```
[global]
private dir=/Users/ph7/.Trash/qemu-smb.KT53D1
interfaces=127.0.0.1
bind interfaces only=yes
pid directory=/Users/ph7/.Trash/qemu-smb.KT53D1
lock directory=/Users/ph7/.Trash/qemu-smb.KT53D1
state directory=/Users/ph7/.Trash/qemu-smb.KT53D1
cache directory=/Users/ph7/.Trash/qemu-smb.KT53D1
ncalrpc dir=/Users/ph7/.Trash/qemu-smb.KT53D1/ncalrpc
log file=/Users/ph7/.Trash/qemu-smb.KT53D1/log.smbd
smb passwd file=/Users/ph7/.Trash/qemu-smb.KT53D1/smbpasswd
security = user
map to guest = Bad User
load printers = no
printing = bsd
disable spoolss = yes
usershare max shares = 0
[qemu]
path=/Users/Shared/My-Folder
read only=no
guest ok=yes
force user=ph7

```
This is impacting qemu + samba usage in particular.

There are some (pre-existing) errors with port lint, but fixing them (tabs) leads to a diff that is hard to review. So I refrain from it.

###### Type(s)

- [X] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.6.1 20G224 x86_64
Xcode 12.5.1 12E507

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Phil, welcome to MacPorts, and thank you for your first contribution!

You'll want to update your commit message to follow our guidelines, so it should be something akin to:

`samba4: fix get_user_groups issue`.

That should be the first commit line. You can also include more detail in the second line of the message though, such as:

`Add patch to resolve error: "get_user_groups: failed to get the unix group list"`

**Comment by ph7** [comment]
Commit message updated, and I also added a second commit removing the tabs.

Thank you for the quick feedback.

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
LGTM. Anyone else?

**Comment by mascguy** [comment]
Phil, it looks like the CI builds are failing, during the patch phase. So those may need to be updated.

Can you double-check whether builds are succeeding for you locally?

**Comment by mascguy** [comment]
> Phil, it looks like the CI builds are failing, during the patch phase. So those may need to be updated.
> 
> Can you double-check whether builds are succeeding for you locally?

Just tested locally. And can confirm there's an issue one of the existing patches, specifically `patch-fix-debug.diff`.

**Comment by mascguy** [comment]
> Just tested locally. And can confirm there's an issue with one of the existing patches, specifically `patch-fix-debug.diff`.

Phil, it looks like you added patch `patch-fix-debug.diff` twice in your portfile, which is what was causing the CI build to fail. I just pushed a fix for that.

On a separate note - and this is minor, but still notable - the indentation wasn't correct: It looks like you may have replaced each tab with four spaces? No worries regardless; I corrected that as well.

**Comment by mascguy** [comment]
Tested locally, and looks good.

Phil, thanks again for your contribution, it's much appreciated!

**Comment by ph7** [comment]
Thank you Chris, and very sorry for the extra trouble generated (double-patch, indentation).
It will be awesome to have this merged upstream, since samba is a great mechanism to get "shared folders" between host and guest running via qemu on macOS.

**Comment by mascguy** [comment]
> Thank you Chris, and very sorry for the extra trouble generated (double-patch, indentation).

No worries. You did the hard work, so we're happy to assist with minor details like formatting.

> It will be awesome to have this merged upstream, since samba is a great mechanism to get "shared folders" between host and guest running via qemu on macOS.

Definitely!

**Comment by ryandesign** [comment]
Since this changes runtime behavior, you have to increase the port's revision.

**Comment by ryandesign** [comment]
Ah, it looks like that was done afterwards in a68644b8b83b5a489d9f8de862819796f583145a.

**Pull request merged**
