### PR TITLE
gtkwave: update to 3.3.115

### PR DESCRIPTION
**Pull request by langly**
* Updated gtkwave to 3.3.115
* Added a maintainer to the portfile

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.2.1 22D68 arm64
Xcode 14.3 14E222b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
the CI failed with:

  Installing dependency (69 of 107) 'gtk-osx-application-common-gtk2' with variants '' ... [FAIL]

You did not observe that locally? Any idea how to fix that?

**Comment by langly** [comment]
For some reason I did not see that locally. Unsure as to why though. Is some time since I looked at this but can try again

**Comment by mascguy** [comment]
> Installing dependency (69 of 107) 'gtk-osx-application-common-gtk2' with variants '' ... [FAIL]
> 
> You did not observe that locally? Any idea how to fix that?
> 
> [ edit: that port [appears](https://ports.macports.org/port/gtk-osx-application-common-gtk2/details/) to fail everywhere... @mascguy ]

Yes, that's simply the nature of the `gtk-osx-application-xxx` ports, as they require everything to be installed with Quartz. So they'll never build successfully on the buildbots, nor for CI. (At least not until/unless we ever make Quartz the default.)

But testing locally with trace mode, two additional dependencies were needed (`harfbuzz` and `pango`). Took care of that, and force-pushed.

With those in place, looks good! Merging.

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
Thank you for your contribution!

**Pull request merged**
