### PR TITLE
Add implicit func decl whitelist files - missing SDKs

### PR DESCRIPTION
**Pull request by Gcenx**
#### Description

Add the missing SDK symlinks/files
- macosx12.1.sdk.list
- macosx12.3.sdk.list
- macosx13.sdk.list
- macosx13.0.sdk.list
- macosx13.1.sdk.list

###### Type(s)

- [x] enhancement

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

### CODE REVIEW

**Comment by Gcenx** [comment]
@jmroot

**Comment by chrstphrchvz** [comment]
I believe this PR is still applicable. A symlink for macosx13.1.sdk can also now be added.

**Comment by Gcenx** [comment]
> I believe this PR is still applicable. A symlink for macosx13.1.sdk can also now be added.

Added

**Comment by chrstphrchvz** [comment]
There is a conflict presumably for macosx13.sdk.list. A symlink for macosx13.3.sdk can also now be added. Once this PR is ready again, I suggest writing to macports-dev requesting this be reviewed/merged.

**Pull request merged**
