### PR TITLE
libsoup-devel: update to @3.0.6

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update `libsoup-devel` to @3.0.6, disable `vapigen` for PowerPC until fixed, remove obsolete `gnome` option.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

### CODE REVIEW

**Review by mascguy — APPROVED** [review]

**Comment by barracuda156** [comment]
@mascguy Here were are stuck, again, because Macports does not want to upgrade `glib2` :(

Writing this just to be clear. My update does work (well, it should), but I cannot fix it here unless `glib2` is updated, and my PR for that got stuck indefinitely.

**Comment by mascguy** [comment]
> @mascguy Here were are stuck, again, because Macports does not want to upgrade `glib2` :(

You just need to be patient, as @ryandesign is definitely interested in updating `glib2`. But since there are a tremendous number of ports dependent on it, we need to carefully - and gradually - update it.

**Comment by barracuda156** [comment]
> > @mascguy Here were are stuck, again, because Macports does not want to upgrade `glib2` :(
> 
> You just need to be patient, as @ryandesign is definitely interested in updating `glib2`. But since there are a tremendous number of ports dependent on it, we need to carefully - and gradually - update it.

I am not in a hurry – on my end it is updated long back. I just wanted to leave a note that I did not forget or ignore this PR :)

**Comment by mascguy** [comment]
> I am not in a hurry – on my end it is updated long back. I just wanted to leave a note that I did not forget or ignore this PR :)

Hey Sergey, since this update requires a hard dependency on `glib2-upstream` - and we can't require all users to install that - we can instead do this via new port `libsoup-devel`. That's been committed, and you can now update this PR to modify that instead.

**Comment by mascguy** [comment]
Updated to modify `libsoup-devel` instead. Will merge, once CI completes successfully. Thanks Sergey!

**Comment by mascguy** [comment]
Ugh, it looks like I lost your patch when rebasing. Can you paste the contents here, and I'll re-add it?

**Comment by barracuda156** [comment]
@mascguy Thank you very much!

**Pull request merged**
