### PR TITLE
go: update to 1.21.0

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with ~`sudo port -vst install`~ `sudo port -d destroot`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by jpeeler** [comment]
@herbygillot I noticed that go.env was missing in /opt/local/lib/go. After putting the file in place, GOPROXY functioned as expected: https://github.com/golang/go/issues/61928.

**Comment by saj** [comment]
I'm seeing the same problem on `go@1.21.0_0`.

```
% go mod init foo
go: creating new go.mod: module foo
% go get golang.org/x/exp/rand
go: golang.org/x/exp/rand: GOPROXY list is not the empty string, but contains no entries
```

To elaborate on what jpeeler wrote above...

```
curl -LSsf -o /opt/local/lib/go/go.env https://raw.githubusercontent.com/golang/go/go1.21.0/go.env
```

`go.env` was added in upstream CR [462198](https://go-review.googlesource.com/c/go/+/462198) and landed in [7aa85e](https://github.com/golang/go/commit/7aa85e01376d840acc8bb931156d607a00b64a60); first appeared in go1.21rc1.

golang/go#61928 was closed by the reporter but I wonder whether this is an upstream bug.
[`readEnvFile`](https://github.com/golang/go/blob/aa5d483f25e89f3bf399362ccc9a5b146cae5c79/src/cmd/go/internal/cfg/cfg.go#L327-L330) tolerates `ENOENT`; it is only [later](https://github.com/golang/go/blob/aa5d483f25e89f3bf399362ccc9a5b146cae5c79/src/cmd/go/internal/modfetch/proxy.go#L118-L124) when the error is returned.

```
len(proxyOnce.list) == 0
```

Is that not expected if a downstream chooses to disable `GOPROXY=`?

In any case, I think we probably want to copy `go.env` into the destroot.

**Comment by herbygillot** [comment]
@jpeeler @saj Thank you both for catching and commenting on this, tracking this in MacPorts Trac here: https://trac.macports.org/ticket/67961

This PR is meant to fix this: https://github.com/macports/macports-ports/pull/19892

**Comment by herbygillot** [comment]
This issue should now be fixed.

**Pull request merged**
