### PR TITLE
Subports for sapmachine (openjdk meta port)

### PR DESCRIPTION
**Pull request by usersxx**
#### Description
Openjdk new subports openjdk11-sap and openjdk17-sap (openjdk meta port)

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65 x86_64
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by usersxx** [comment]
@breun .
Can these new subports `openjdk11-sap` and `openjdk17-sap` be added

**Comment by breun** [comment]
Looks good to me.

**Comment by usersxx** [comment]
@pmetzger Why did you cancel the checks ?

**Comment by usersxx** [comment]
This pull request can be merged because I am not going to commit.

**Comment by usersxx** [comment]
@breun  You need to update openjdk8-openj9, openjdk11-openj9 and openjdk17-openj9

**Comment by breun** [comment]
> @breun You need to update openjdk8-openj9, openjdk11-openj9 and openjdk17-openj9

Thanks for the heads up: https://github.com/macports/macports-ports/pull/13904

**Comment by usersxx** [comment]
There is some bug or macOS Catalina and macOS Big Sur be install on i386.
See this https://github.com/macports/macports-ports/pull/13843/checks#step:8:89 and this 
 https://github.com/macports/macports-ports/pull/13843/checks#step:8:89

**Comment by usersxx** [comment]
> > @breun You need to update openjdk8-openj9, openjdk11-openj9 and openjdk17-openj9
> 
> Thanks for the heads up: #13904

Welcome

**Comment by pmetzger** [comment]
> This pull request can be merged because I am not going to commit.

I have no idea what that means.

> Why did you cancel the checks aka workflow runs ?

I didn't cancel them. I started them.

**Comment by usersxx** [comment]
Ok

**Comment by usersxx** [comment]
I will not going to commit to this pull request

**Comment by pmetzger** [comment]
You cannot commit this request, you don't have commit privileges on the repository. Are you indicating that you are abandoning this merge request? If so, please close it.

**Comment by usersxx** [comment]
I don't need to add, remove or fix anything in this portfile so why would I need to commit. By the way I have commit privileges on this repository.

**Comment by usersxx** [comment]
@breun Openjdk 17.0.3 is going to release after few days. See the source code of openjdk here https://github.com/openjdk/jdk17u/tags

**Comment by usersxx** [comment]
@breun  You should merge `openjdk11-sap` and `openjdk17-sap` if you would like to as openjdk 17.0.3 and openjdk 11.0.15 is going to release

**Comment by breun** [comment]
I am a port maintainer, but I don't have commit privileges. But as a maintainer I'm ok with adding these subports.

**Comment by usersxx** [comment]
Ok

**Comment by usersxx** [comment]
You can request a maintainer to merge this pull request.

**Comment by breun** [comment]
@pmetzger Can you merge this PR?

**Comment by pmetzger** [comment]
@breun Sorry, I was away for a few days.

**Comment by breun** [comment]
In the meantime @usersxx closed this MR. I don't know why.

**Comment by pmetzger** [comment]
Neither do I but I'm not going to push.

**Comment by usersxx** [comment]
Closed pull request due to openjdk 11.0.14.1 update

**Comment by usersxx** [comment]
Also messed up the master branch of my folk of this repository

**Comment by usersxx** [comment]
@pmetzger you can merge this pull request`https://github.com/macports/macports-ports/pull/14032`

**Comment by usersxx** [comment]
This is updated one

**Comment by usersxx** [comment]
That is updated one
I refolked macports repository as I had commited in master branch instead of creating one

**Pull request closed without merging**
