### PR TITLE
chromedriver: Update to version 110.0.5481.77; py-undetected-chromedriver: Update to version 3.4.6

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.2.1 22D68 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by essandess** [comment]
@ultrafunkamsterdam I'm unable to file an upstream bug report to https://github.com/ultrafunkamsterdam/undetected-chromedriver because of the permission settings.

Please note this bug fix in this patch: https://github.com/macports/macports-ports/pull/17718/files#diff-3ce99c00144ed97d79fa9c4376f02c4776978b37b5607f67fae67c835a4b777e
> undetected_chromedriver/patcher.py: Fix comparison issue with `version_main`
> 
> * `executable_path` with default `version_main=None` cause comparison issue
> * Set `version_main` from `chromedriver --version` output

**Comment by essandess** [comment]
@ultrafunkamsterdam Also please note that on Apple Silicon you must codesign your patched binaries in `Patcher`. This is done in this PR for MacPorts with this call:
> ```tcl
>         if {${configure.build_arch} eq {arm64}} {
>              system "codesign -f -s - ${worksrcpath}/${name}"
>          }
> ```

**Comment by reneeotten** [comment]
@catap any comments on this PR?

**Comment by catap** [comment]
@reneeotten fine for me to merge it.

Sorry, the last weeks was insane.

**Review by catap — APPROVED** [review]

**Pull request merged**
