### PR TITLE
bind9: fix on Leopard and PowerPC

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

1. Fix compiler blacklist to avoid gcc-4.0.
2. Fix broken PowerPC assembler code in rwlock.
3. Do not depend on `jemalloc` on Leopard and Tiger, it does not build there, as of now.
4. Use path-style dependencies, where appropriate.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by danielluke** [comment]
Sorry, I just saw this - I just have one comment (and if you could also resolve the conflicts it should be good to merge):

- port-style dependencies are generally preferred over path-style dependencies. Did you switch these to solve a particular problem? If not, I'd like to remove those changes.

**Comment by barracuda156** [comment]
@danielluke I won’t insist, of course, but not switching to path-style will make it impossible to install `bind9` when `jemalloc-devel` and/or `libuv-devel` are installed. (This is just to explain the suggested change; I will drop this if you confirm that is preferred nevertheless.)

**Comment by danielluke** [comment]
> @danielluke I won’t insist, of course, but not switching to path-style will make it impossible to install `bind9` – at least in a straightforward manner – when `jemalloc-devel` and/or `libuv-devel` are installed. (This is just to explain the suggested change; I will drop this if you confirm that avoiding path-style deps is preferred nevertheless.)

Nope, that's a good reason to change them, you can keep them in. Resolve conflicts and I'll merge.

**Comment by barracuda156** [comment]
> Nope, that's a good reason to change them, you can keep them in. Resolve conflicts and I'll merge.

@danielluke Rebased. Thank you.

**Comment by barracuda156** [comment]
Are we good to merge this? Or something extra needed?

**Comment by barracuda156** [comment]
@danielluke If you have a minute, could you please take a look at this [comment](https://forums.macrumors.com/threads/unofficial-macports-10-5-binary-repo.2376248/page-3?post=32941304#post-32941304)? It is not related to PowerPC build and therefore unrelated to this PR (and needs not be addressed here), but I cannot deal with the user feedback there, since I do not use this personally – I was requested to fixed the build, and that is done (once PR merged).

**Comment by danielluke** [comment]
I swear I clicked 'squash and merge' on this yesterday.

**Pull request merged**
