### PR TITLE
py-pyobjc: update to 8.4.1

### PR DESCRIPTION
**Pull request by danchr**
#### Description

I elected to drop most of the patching of the build infrastructure, and just use PEP-517 on each directory instead. Since the tools don't actually support multiple directories or wheels, I added two small scripts to do that. Hopefully this should prove more reliable and maintainable in the long run.

Closes: https://trac.macports.org/ticket/64766

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
@danchr Any idea why the CI failed?

**Comment by mascguy** [comment]
> @danchr Any idea why the CI failed?

Based on a quick local test, this appears to be the issue:

```
:info:build sphinx-build-3.10 -b html -d _build/doctrees . _build/html
:info:build Running Sphinx v4.5.0
:info:build Extension error:
:info:build Could not import extension sphinxcontrib.blockdiag (exception: No module named 'sphinxcontrib.blockdiag')
:info:build make: *** [html] Error 2
:info:build Command failed: make -j24 html
```

**Comment by mascguy** [comment]
Updated to include a build dep for new port `py-sphinxcontrib-blockdiag`.

**Comment by mascguy** [comment]
Dan/All, based on local testing, all subports now builds successfully. (With the key addition of a dependency on `py-sphinxcontrib-blockdiag`.)

There's just one catch: Since there is also a dependency on `py-blockdiag` - and we don't provide a Python 3.6 subport for the latter - we also have to remove support for Python 3.6 here. Otherwise we'll need to disable building of docs for Python 3.6.

Thoughts?

**Pull request merged**
