### PR TITLE
newran: update to v. 03

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update, clean-up portfile.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by herbygillot** [comment]
Can the master_site be HTTPS as well?

**Comment by barracuda156** [comment]
> Can the master_site be HTTPS as well?

Done. Also added license.

P. S. The following implies BSD, right?
http://www.robertnz.net/nr03doc.htm
> There are no restrictions on the use of newran except that I take no liability for any problems that may arise from its use.

**Comment by barracuda156** [comment]
@herbygillot Are we good with this or something to change?

**Comment by herbygillot** [comment]
I'm not sure that the license qualifies as BSD.  We may just set `license` as "Permissive".

**Comment by barracuda156** [comment]
> I'm not sure that the license qualifies as BSD. We may just set `license` as "Permissive".

Done

**Pull request merged**
