### PR TITLE
py-numpy: update to 1.26.1, add py312 subport; likewise for dependencies

### PR DESCRIPTION
**Pull request by markmentovai**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.0 23A344 arm64
Xcode 15.0.1 15A507

macOS 14.0 23A344 x86_64
Xcode 15.0.1 15A507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by cjones051073 — APPROVED** [review]
Fine for py-mkl

**Comment by markmentovai** [comment]
CI is failing for `py27-numpy` on macOS 13 because of [Trac ticket 68359](https://trac.macports.org/ticket/68359), the same reason as [Trac ticket 68329](https://trac.macports.org/ticket/68329). The default variant for `py27-numpy` on x86_64 is `+openblas`, and `libopenblas-r1.dylib` contains duplicate identical `LC_RPATH` commands, which the new `ld` in Xcode 15 (and thus macOS 14) is intolerant of.

**Comment by cjones051073** [comment]
> CI is failing for `py27-numpy` on macOS 13 because of [Trac ticket 68359](https://trac.macports.org/ticket/68359), the same reason as [Trac ticket 68329](https://trac.macports.org/ticket/68329). The default variant for `py27-numpy` on x86_64 is `+openblas`, and `libopenblas-r1.dylib` contains duplicate identical `LC_RPATH` commands, which the new `ld` in Xcode 15 (and thus macOS 14) is intolerant of.

The LC_RPATH messages are just warnings. They are not the issue that fails the build, that is just the new linker not liking binaries built with GCC.

**Comment by markmentovai** [comment]
https://github.com/macports/macports-ports/pull/21003#issuecomment-1773719739:
> > CI is failing for `py27-numpy` on macOS 13 because of [Trac ticket 68359](https://trac.macports.org/ticket/68359), the same reason as [Trac ticket 68329](https://trac.macports.org/ticket/68329). The default variant for `py27-numpy` on x86_64 is `+openblas`, and `libopenblas-r1.dylib` contains duplicate identical `LC_RPATH` commands, which the new `ld` in Xcode 15 (and thus macOS 14) is intolerant of.
> 
> The LC_RPATH messages are just warnings. They are not the issue that fails the build, that is just the new linker not liking binaries built with GCC.

They aren’t just warnings. The `LC_RPATH` messages are the errors that are causing the build to fail. See my detailed analysis at [ticket 68329 comment 14](https://trac.macports.org/ticket/68329#comment:14).

There are two different messages about rpaths:

When linking a library with two `-rpath`s naming the same path on the line, `ld` and `ld-classic` will issue this warning: 

```
ld: warning: duplicate -rpath '/opt/local/lib/libgcc' ignored
```

This one is only a warning. But, contrary to what it says, `ld-classic` doesn’t actually ignore the duplicate, and does embed multiple identical `LC_RPATH` load commands into its output. The new `ld`, not `ld-classic`, does ignore the duplicate as the warning states. But since OpenBLAS builds with MacPorts GCC, which is using `ld-classic`, the duplicate isn’t ignored. This is how `libopenblas-r1.dylib` is created, and how it winds up with two load commands.

The other message occurs when linking against a module that has multiple identical `LC_RPATH` load commands, such as one produced above. It is:

```
ld: duplicate LC_RPATH '/opt/local/lib/libgcc' in '/opt/local/lib/libopenblas-r1.dylib'
```

This one is not a warning, it’s a hard error. It’s how numpy links against `-lopenblas`. And it is the reason that the py27-numpy+openblas build is failing in this ticket, and the reason that the other ports that build against openblas are failing in a variety of other tickets.

There is, in fact, another form of this message:

```
ld: warning: duplicate LC_RPATH are deprecated ('/opt/local/lib/libgcc')
```
but that’s not what we’re seeing here, we’re absolutely seeing the hard error.

**Comment by markmentovai** [comment]
There’s a further discussion of the difference between the ld warning and the ld error at [ticket 68329 comment 22](https://trac.macports.org/ticket/68329#comment:22).

I don’t think that any of this `LC_RPATH` stuff should hold up this pull request. I investigated and explained here because the `LC_RPATH` problem caused the CI to fail to build `py27-numpy` (which I wasn’t touching) for this change on macOS 13/Xcode 15, but I’ve determined that the problem has nothing to do with this change.

**Comment by pmetzger** [comment]
What's the status on this? Should it be merged?

**Comment by markmentovai** [comment]
Yes, this is still ready to go as far as I’m concerned.

**Review by michaelld — APPROVED** [review]
Based on @markmentovai 's explanation I'm approving of this PR & it sounds like the `LC_RPATH` issue is beyond the scope of this PR ... will be fixed in some other way

**Comment by barracuda156** [comment]
This has resulted in spectacular breakage :)

P. S. Besides, what was the need to move pre-3.12 versions to pep517 without testing those properly?

**Comment by kencu** [comment]
looks like 10.8 and newer are OK:

https://ports.macports.org/port/py310-numpy/details/

so not exactly “spectacular”.

**Comment by barracuda156** [comment]
@kencu So we still have 4 systems broken for 4 archs, by an unnecessary change in build system.

**Comment by kencu** [comment]
Just < 10.8, and looks like a trivial fix due to an xcrun call not supported on ancient systems. No need for major drama.

**Comment by barracuda156** [comment]
> Just < 10.8, and looks like a trivial fix due to an xcrun call not supported on ancient systems. No need for major drama. 


I am not sure it is `xcrun` breaking it (though it may), and there is another problem with arch detection on PowerPC (that one I fixed, perhaps), but on a side note: can we get rid of `xcrun` somehow globally? It is either refund or breaks stuff.

**Comment by kencu** [comment]
responded here

https://trac.macports.org/ticket/68908#comment:13

**Pull request merged**
