### PR TITLE
ocaml-js_of_ocaml: update to 5.8.1

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@pmetzger Unless something changed relatively recently, OCaml 5 is supposed to support bytecode-only mode, if you mean that. Or do we have some other concerns?

**Comment by pmetzger** [comment]
I don't understand your question.

We've been holding off on moving to 5.x because the official claim is that the last 4.x release should be regarded as LTS and OCaml 5 should be (currently) regarded as more experimental, with a number of features still broken. However, that's rapidly being corrected, and so at some point we will need to move to OCaml 5. I would guess 5.3 will be the first release considered more stable than what we have now.

**Comment by barracuda156** [comment]
@pmetzger Have you got a preliminary version of a port for 5.x? Let me ensure it builds on ppc and older x86 before it is released here, so we do not have a sudden breakage.

Does 5.x maintain backward compatibility by the way? I mean, there is software which was written for 4.x and may not have been updated ever since.

**Comment by pmetzger** [comment]
I haven't done the portfile but it won't be hard; the build process hadn't really changed much. There are some backwards incompatibilities, but I think we should mostly ignore them. People who want to run OCaml software seriously should be using opam, not MacPorts, and some of that can be accommodated through opam. The main point of having OCaml support in macports is to let people run applications that need the OCaml compiler to build.

**Comment by barracuda156** [comment]
@pmetzger Nothing Dune-based will work outside of MacPorts on older MacOS, for example, and while I admit that it won’t happen in a commercial enterprise context, nothing prevents a professional who happens to be an enthusiast of legacy computing to use OCaml software for its intended uses on older machines with MacPorts. As far as I know at least.

Opam is just working as a package manager, isn’t it?

**Comment by barracuda156** [comment]
> Dune works fine if you build it as bytecode. There's no way to build many of the packages without Dune anyway, full stop. opam is "just" a package manager but it's the one the OCaml people use and expect; everything now depends on opam and most things depend on dune.

Dune works fine _in MacPorts,_ it won’t work fine on old systems on its own, since a) as I recall, upstream never merged their own patch for older macOS, b) specific environment setting is needed to make it work. It is not only about 32-bit and native/bytecode targets.

**Comment by pmetzger** [comment]
I understand that you care a great deal about machines that haven't been built in decades. I'm afraid I don't, but I do care about being able to run modern software on machines that are reasonably recent, and it will indeed be necessary to update many packages and the OCaml compiler in the not that distant future. If it's possible to run the code on old machines, that's fine, but it's not the highest possible priority here.

**Comment by barracuda156** [comment]
@pmetzger There are no objections whatsoever from my side, I am interested to try OCaml 5 in fact. It is happens that it won’t work on older systems, I will take care of the fallback for those, though presumably byte code should work normally like it does with 4.14.

**Comment by pmetzger** [comment]
The OCaml 5 compiler should work fine both compiled into bytecode and to compile bytecode. I believe that the team has also repaired some of the PowerPC code (though I think possibly only 64 bit.)

**Pull request merged**
