### PR TITLE
Gildas: update to 201903a

### PR DESCRIPTION
**Pull request by bardeau**
@smaret or anyone else, can you please merge this PR for the March release? Thanks.

### CODE REVIEW

**Comment by pmetzger** [comment]
The CI system (the one that actually works, Azure Pipelines) failed.

**Comment by mf2k** [comment]
It looks like the problem was that the builder was not able to automatically build a dependency correctly. cfitsio does not have the appropriate default variant required by this port. 

```
DEBUG: cfitsio is installed with the following variants: 
DEBUG:   required: gcc7, forbidden: 
DEBUG:   rejected, because required variant gcc7 is missing
Error: Install cfitsio with a Fortran variant (e.g. +gfortran, +gccX, +g95)
Error: Failed to configure gildas: cfitsio not installed with a Fortran variant

```

**Comment by pmetzger** [comment]
This problem of variants breaking the CI system really needs to be addressed, if only by special casing the build of such variants when needed to CI some other package.

**Comment by pmetzger** [comment]
Merged, thank you, @bardeau!

**Pull request merged**
