### PR TITLE
update poppler 0.71 and dependents

### PR DESCRIPTION
**Pull request by dbevans**
#### Description
Submitting this PR as WIP since not all broken dependents are included.  Should not be merged until fixes for inkscape, inkscape-devel and texlive-bin are included.

@dbevans is working on inkscape, inkscape-devel now
@drkp should be aware that texlive svn includes fixes for poppler 0.71 in texk/web2c/pdftexdir

```
------------------------------------------------------------------------
r49040 | kakuto | 2018-10-31 16:54:33 -0700 (Wed, 31 Oct 2018) | 1 line

add new files to support system poppler 0.71.0
------------------------------------------------------------------------
```
texk/web2c/luatexdir now uses pplib and no longer requires poppler thus explicit fixes for 0.71.0 are not available upstream. Should probably update luatexdir to at least r48594:

```
------------------------------------------------------------------------
r48594 | lscarso | 2018-09-05 14:57:30 -0700 (Wed, 05 Sep 2018) | 1 line

luatex: correct  automake file for pplib; replaced cweb files with c files.
------------------------------------------------------------------------
r48593 | lscarso | 2018-09-05 14:35:27 -0700 (Wed, 05 Sep 2018) | 1 line

pplib for luatex: removed udeless files
------------------------------------------------------------------------
r48592 | lscarso | 2018-09-05 14:32:42 -0700 (Wed, 05 Sep 2018) | 1 line

pplib for luatex
------------------------------------------------------------------------
```

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G3025
Xcode 10.1 10B61 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by yan12125** [comment]
Hi, as you're now working on the poppler port, could you consider also including a patch for fixing https://trac.macports.org/ticket/57167?
```Diff
diff --git CMakeLists.txt CMakeLists.txt
index 88a53c47..26cefd28 100644
--- CMakeLists.txt
+++ CMakeLists.txt
@@ -1,7 +1,7 @@
-project(poppler)
-
 cmake_minimum_required(VERSION 3.1.0 FATAL_ERROR)
 
+project(poppler)
+
 set(CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/modules)
 
 include(PopplerDefaults)
```
See the commit message for a similar issue for details: https://github.com/macports/macports-ports/commit/98445d69fc13be9c968abe4c597de8324b0ceee6

**Comment by mojca** [comment]
The situation with LuaTeX is a bit strange at this point (in-between two TeX Live releases). If it's non-trivial to repeat the same patches for LuaTeX as done for pdfTeX, maybe the easiest thing would be to remove LuaTeX from texlive-bin and then build LuaTeX separately from its own repository? At least until TL 2019 comes out. I would say we could keep this setup longer (= separate LuaTeX, like we do for dvisvgm or asymptote for example), but LuaTeX is not going to see much active further development from this point on anyway (developers will work on a new engine & challenge). Updating just LuaTeX from within TeX Live sources could be a bit tricky (not undoable, but ...)

**Comment by mojca** [comment]
Also worth considering:
* pplib in LuaTeX is completely new (written from scratch) and thus definitely not bug-free, a number of bugs were discovered the first day this was released. It would be easier to fix bugs if switching directly to LuaTeX repository than to keep updating LuaTeX from within TeX Live and rebuild the whole TeX Live every time a bugfix is needed.
* ConTeXt will be completely broken if you update just LuaTeX (and not also ConTeXt, but updating ConTeXt is its own problem, it sees "releases" every few days, sometimes multiple times per day, it usually works with just a single version of LuaTeX, the latest released one at the time of ConTeXt release; there's just one slightly more official release which gets somewhat more testing once per year when TeX Live comes out). Not that I expect any serious ConTeXt users to be using TeX Live, but ...

Maybe Debian has some patches for poppler for the old LuaTeX?

**Comment by dbevans** [comment]
> If it's non-trivial to repeat the same patches for LuaTeX as done for pdfTeX

@mojca:  I made a good faith attempt to patch LuaTeX for 0.71 but luatex is much less straight forward than pdftex and I ran into a couple of areas where what I would call "clever software tricks"
made it difficult to understand how to fix the problem without a major overhaul of the luatex code.
That being the case and the flack last time over just going ahead with the poppler update, led me to the approach I've taken here.  I'll be happy with any solution that @drkp and others that understand the code better than I do come up with. However, I have developed an appreciation for why the upstream texlive developers decided to dispense with poppler in this case.  It might be easier to fix the issues with pplib than try to fix the poppler issues with the old code.

**Comment by mojca** [comment]
@dbevans: OK, if you already tried and gave up, there's no need to continue. It's a mess not worth going into. I would suggest to use https://github.com/TeX-Live/luatex as the upstream source for LuaTeX (it's a mirror, but the real sources are well hidden in some subversion hole with no web interface ...) and build LuaTeX separately, remove the LuaTeX build from texlive-bin, and then take some random ConTeXt version from upstream rather than TeX Live and use that one.

@norbusan: How did you fix the issue with the new poppler & TeX Live/LuaTeX in Debian? Or just not yet?

**Comment by norbusan** [comment]
@mojca I reverted to luatex 1.08 because even with the latest context in TL it is broken. Sorry to say, but this is such a nee mess to break API i na step from 1.08 to 1.09, incomprehensible to me. 

I gave up on all th these luatex games and revert to the state of released binaries.

**Comment by norbusan** [comment]
Aah, concerning luatex and poppler, that is the next PITA. Poppler is just brain damaged in their release management and API changes. Also here i have given up to use system poppler afair (in the train now) and user the poppler lib shipped with TL. In the last 10+ years poppler has broken down other apps without announcement too many times, ridiculous.

**Comment by mojca** [comment]
Ok, this is another thing that I didn't think of earlier. We could use the older poppler library shipped with TeX Live instead of relying on system poppler. TeX Live uses such a small subset of poppler that security might not even be an issues after all. (I'm not a security expert though, so I don't want to make any misleading claims, but until TeX Live 2019 which will be out in a few months this could be a viable option ...)

**Comment by dbevans** [comment]
> # --with-system-poppler \

If we do this then the poppler dependency can be removed entirely which probably means that all the previous poppler compatibility patches can be removed as well.  This should remove texlive-bin as a block to future poppler upgrades. I like it.

**Comment by dbevans** [comment]
poppler port updated to only apply build conflict to the main poppler port only rather than both poppler and poppler-qt5.  Since poppler-qt5 depends on poppler, this was blocking the build of
poppler-qt5.

**Comment by pmetzger** [comment]
What's next?

**Comment by dbevans** [comment]
> What's next?

We need to hear from @drkp concerning texlive-bin.  If he agrees to side with @mojca and myself and switch to using texlive's embedded poppler instead of our system poppler, then he can go ahead and commit that change before merging this PR. Doing so should decouple texlive-bin from this and future poppler API changes.

Then I need to fix inkscape and inkscape-devel and add them to this PR. 

With that done, it can be merged.

**Comment by mojca** [comment]
It's also maintainer timeout ...

**Comment by pmetzger** [comment]
Indeed, at this point we're well past the timeout stage.

**Comment by drkp** [comment]
Sorry, I have been tied up with work the last few days.

I think the easiest option here is to switch texlive-bin to use its own internal version of poppler, at least for now. I don't love that, especially since poppler has a history of security problems, but it sounds like the use is pretty minimal and the other options are pretty complicated. We can revisit when TeX Live 2019 is closer to release, which isn't that far off.

**Comment by drkp** [comment]
I'll commit the texlive-bin change once it finishes building.

**Comment by dbevans** [comment]
> I'll commit the texlive-bin change once it finishes building.

Thanks, once you commit texlive-bin, I'll go ahead a merge this PR.

**Comment by dbevans** [comment]
BTW, texlive-bin's internal version of poppler appears to be 0.63 so its not that far behind the current.

**Comment by drkp** [comment]
Done: 590c88fc60

**Comment by dbevans** [comment]
> Done: [590c88f](https://github.com/macports/macports-ports/commit/590c88fc604cb5d2f70a4ef6aafa49da0067654e)

Great!  FYI, poppler 0.72 was released today and once again it is ABI/API incompatible with 0.71.

Typical build error (from extractpdfmark) is:

```
:info:build destname.cc:35:28: error: no member named 'getCString' in 'GooString'
:info:build   return std::string {goo->getCString (),
:info:build                       ~~~  ^

```

but that will be for the next round.

**Comment by norbusan** [comment]
> Great! FYI, poppler 0.72 was released today and once again it is ABI/API incompatible with 0.71.

This is one of the reasons we (TeX LIve team) are trying to get rid of poppler as soon as possible. For 2019 luatex will not need it anymore. Patches for xetex to use ppllib (TL internal lib) instead of poppler are available. For 2020 we should have pdftex, xetex, luatex all use pplib instead of poppler. 

And one nightmare less would be achieved ...

**Comment by lemzwerg** [comment]
BTW, I've informed the author of extractpdfmark about the problem.

**Pull request merged**
