### PR TITLE
Rename docbook-xsl to docbook-xsl-nons and update docbook-xsl-ns

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

The docbook-xsl developers used to develop the non-namespaced version and generate the namespaced version from it. With 1.79.2 this has reversed, and they now develop the namespaced version and generate the non-namespaced version from it. With this change, the package names have changed.

Rename docbook-xsl to docbook-xsl-nons to match new upstream naming.

Update docbook-xsl-ns to the same version and make it a subport of docbook-xsl to ease future updating. It would be confusing at this time to rename docbook-xsl-ns to docbook-xsl to match the new upstream naming, so I'm not doing that now, and am not certain if I will ever do it given that it would make the name more ambiguous.

Move documentation from docbook-xsl to new docbook-xsl-docs subport.

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.12.6 16G1212
Xcode 9.2 9C40b 

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] checked your Portfile with `port lint`?
- [X] tried a full install with `sudo port -vst install`?

### CODE REVIEW

**Comment by lbschenkel** [comment]
+1 from me

**Comment by raimue** [comment]
Isn't this change causing more problems than it solves? Everyone else is packaging the non-ns version as "docbook-xsl". Tutorials will tell people to install "docbook-xsl", but they would actually need "docbok-xsl-nons".

**Comment by ryandesign** [comment]
> Isn't this change causing more problems than it solves?

You are presumably referring specifically to the aspect of this change that renames the docbook-xsl port to docbook-xsl-nons. There are other aspects of this change, including updating docbook-xsl-ns to the current version and breaking the documentation out into a separate docbook-xsl-docs subport, to which you presumably do not object.

> Everyone else is packaging the non-ns version as "docbook-xsl". Tutorials will tell people to install "docbook-xsl", but they would actually need "docbok-xsl-nons".

Upstream just (with the latest release, 1.79.2) changed the package names. According to upstream, "docbook-xsl" is now the namespaced version, and no longer the non-namespaced version. According to repology, only 5 distributions including MacPorts are up-to-date enough to offer docbook-xsl 1.79.2, and none offer docbook-xsl-ns 1.79.2 yet. Perhaps other distributions, like MacPorts initially, did not realize that the package formerly known as docbook-xsl-ns is now known by upstream as docbook-xsl, and so they have not noticed that new files exist for it yet. Other distributions might adopt the new names as they update, but what other distributions do is not really a guiding principle for me.

If a user tries to install docbook-xsl, per some old tutorial, they will be instructed (via `replaced_by`) to install docbook-xsl-nons instead, so there is no problem there. In the future, I might rename docbook-xsl-ns to docbook-xsl, to match upstream, or I might make it print an error message guiding the user toward the two possible subports.

**Comment by ryandesign** [comment]
> Port postgis fail on xcode7.3. Log

Some docbook-xsl paths that are no longer valid are hardcoded into portfiles, patchfiles and portgroups. I'll update them.

**Comment by ryandesign** [comment]
> It is really unfortunate that upstream introduced this major change with such a minor increase in the version number, while claiming in the release notes it would not contain user visible changes

That's what I thought too. Not only that, but they changed the canonical URLs, so that all existing projects referencing the old canonical URLs can no longer find the catalogs, resulting in build failures. To fix that, we [installed a compatibility catalog with the old URL](https://trac.macports.org/ticket/55255), but because we didn't understand that the name change had taken place, we inadvertently made the compatibility URL point to the wrong new URL, which resulted in the [erroneous output from xsltproc](https://trac.macports.org/ticket/56354) when it received namespaced stylesheets but was expecting to receive non-namespaced stylesheets, which is why we now have to revbump a ton of ports that got their manpages built incorrectly.

> generating the man pages in base and generating the guide will also break due to the path changes.

Ahh, I now see where in MacPorts base the path is hardcoded. Do you know why we have done it that way? My understanding was that one is supposed to reference these catalogs by their canonical URL. The docbook-xsl-* ports register their contents to those URLs, so that other ports that require them can find them by the URLs and don't need to know where in the filesystem they're installed.

> Maybe we should provide a symlink ${prefix}/share/xsl/docbook-xsl -> docbook-xsl-nons for backwards compatibility?

We could, but if we do, I would like it to be for a very limited period of time. Going forward, as distributions update to the new package names, developers will become accustomed to "docbook-xsl" being the namespaced version, at which point such a compatibility symlink to the non-namespaced version will cause confusion. Also, I wouldn't have discovered that the path to the old directory was hardcoded into our portfiles, patches and portgroups if such a compatibility symlink had existed.

**Comment by raimue** [comment]
> Ahh, I now see where in MacPorts base the path is hardcoded. Do you know why we have done it that way?

The path is not actually passed to xsltproc, `doc/manpage.xsl` uses the URL to find the stylesheet. The idea was to check what is missing and give the user a hint what they need to to install. Otherwise, if docbook-xsl was not installed, `xsltproc` failed with a non-helpful and confusing error message (something about not being able to fetch the stylesheet, which is not allowed due to `-nonet`).

**Comment by ryandesign** [comment]
Ok. Well then I would just change the paths in the Makefile, after this PR is merged.

**Comment by mojca** [comment]
I might not manage to test, but feel free to proceed for my port.

**Comment by seanfarley** [comment]
This has my approval as well.

**Comment by pmetzger** [comment]
FYI, we're now past the 72 hour window for maintainer comments.

**Comment by pmetzger** [comment]
If I don't hear otherwise, I intend to merge this some time later today or early tomorrow.

**Comment by ryandesign** [comment]
> The Travis builds seem to be failing though.

because "The job exceeded the maximum time limit for jobs, and has been terminated." So, that doesn't speak against merging the changes.

**Pull request merged**
