### PR TITLE
paraview: update version 5.5.2->5.6.1

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.5
Xcode 10.2.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jjstickel** [comment]
Have the issues of 5.6.0 been resolved in 5.6.1? See #3400, @rubendibattista

**Comment by rubendibattista** [comment]
@jjstickel I just checked the commits and nothing seem to address the problems I had. 

@MarcusCalhoun-Lopez Did you try to compile it with `+mpich +python3.7`?

**Comment by rubendibattista** [comment]
Moreover this is still the old version of the `Portfile`.  In [my tree](https://github.com/rubendibattista/macports-ports/tree/paraview) I added a smarter way to add `python` variants and, more importantly, the `python3.7` variant. @MarcusCalhoun-Lopez can you try to work on top of it and see if you are able to make it work with `python37` and an mpi variant enabled at the same time? Because for me, on `5.6.0`, it was not working. 

You can find my version @ https://github.com/rubendibattista/macports-ports/tree/paraview

**Comment by rubendibattista** [comment]
Sorry. For what concerns #3400, the UI redrawing issues are fixed. But there are other issues related to `python37` variant here: #4045. 

I'm currently on holidays, I'll  get back to #4045 when back. If you're in a hurry you can merge this one and then I'll se if I can fix the problems with `python3.7` build with MPI enabled later when I'll be back.

**Comment by rubendibattista** [comment]
Can we maybe centralize the efforts in #4045?

**Comment by rubendibattista** [comment]
```
--->  Computing dependencies for paraview
Error: Dependency 'PEGTL' not found.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
```

Am I missing something?

**Comment by MarcusCalhoun-Lopez** [comment]
No, you are not missing anything.
I forgot to add PEGTL to the master branch.
Sorry.
PEGTL should [now be added](https://github.com/macports/macports-ports/commit/e726f6e875528807cd5c0ba76d2bfe5ec64dce20).
Thank you for pointing out the error.

> --->  Computing dependencies for paraview
> Error: Dependency 'PEGTL' not found.
> Error: Follow https://guide.macports.org/#project.tickets to report a bug.
> ```
> 
> 
> Am I missing something?

**Comment by rubendibattista** [comment]
Ehi, this is not building for me :)

```
:info:build In file included from /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:44:
:info:build /opt/local/include/diy2/diy/master.hpp:319:117: error: too many arguments to function call, expected 2, have 3
:info:build       void  execute(void* b, const ProxyWithLink& cp) const                         { f(static_cast<Block*>(b), cp, aux); }
:info:build                                                                                       ~                             ^~~
:info:build /opt/local/include/diy2/diy/master.hpp:316:13: note: in instantiation of member function 'diy::Master::Command<void, void (*)((anonymous namespace)::DiyBlock *, const diy::Master::ProxyWithLink &), diy::Master::NeverSkip>::execute' requested here
:info:build             Command(const Functor& f_, const Skip& s_, void* aux_):
:info:build             ^
:info:build /opt/local/include/diy2/diy/master.hpp:678:29: note: in instantiation of member function 'diy::Master::Command<void, void (*)((anonymous namespace)::DiyBlock *, const diy::Master::ProxyWithLink &), diy::Master::NeverSkip>::Command' requested here
:info:build     commands_.push_back(new Command<Block, Functor, Skip>(f, skip, aux));
:info:build                             ^
:info:build /opt/local/include/diy2/diy/master.hpp:227:59: note: in instantiation of function template specialization 'diy::Master::foreach<void, void (*)((anonymous namespace)::DiyBlock *, const diy::Master::ProxyWithLink &), diy::Master::NeverSkip>' requested here
:info:build       void          foreach(const Functor& f, T* aux)   { foreach<Block>(f, NeverSkip(), aux); }
:info:build                                                           ^
:info:build /opt/local/include/diy2/diy/master.hpp:221:59: note: in instantiation of function template specialization 'diy::Master::foreach<void, void (*)((anonymous namespace)::DiyBlock *, const diy::Master::ProxyWithLink &), void>' requested here
:info:build       void          foreach(const Functor& f)           { foreach<Block>(f, (void*) 0); }
:info:build                                                           ^
:info:build /opt/local/include/diy2/diy/master.hpp:218:59: note: in instantiation of function template specialization 'diy::Master::foreach<void, void (*)((anonymous namespace)::DiyBlock *, const diy::Master::ProxyWithLink &)>' requested here
:info:build       void          foreach(const Functor& f)           { foreach<void>(f); }
:info:build                                                           ^
:info:build /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1174:10: note: in instantiation of function template specialization 'diy::Master::foreach<void (*)((anonymous namespace)::DiyBlock *, const diy::Master::ProxyWithLink &)>' requested here
:info:build   master.foreach(&FindPointsToSend);
:info:build          ^
:info:build In file included from /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:44:
:info:build /opt/local/include/diy2/diy/master.hpp:319:87: error: no matching function for call to object of type 'const (lambda at /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1180:18)'
:info:build       void  execute(void* b, const ProxyWithLink& cp) const                         { f(static_cast<Block*>(b), cp, aux); }
:info:build                                                                                       ^
:info:build /opt/local/include/diy2/diy/master.hpp:316:13: note: in instantiation of member function 'diy::Master::Command<void, (lambda at /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1180:18), diy::Master::NeverSkip>::execute' requested here
:info:build             Command(const Functor& f_, const Skip& s_, void* aux_):
:info:build             ^
:info:build /opt/local/include/diy2/diy/master.hpp:678:29: note: in instantiation of member function 'diy::Master::Command<void, (lambda at /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1180:18), diy::Master::NeverSkip>::Command' requested here
:info:build     commands_.push_back(new Command<Block, Functor, Skip>(f, skip, aux));
:info:build                             ^
:info:build /opt/local/include/diy2/diy/master.hpp:227:59: note: in instantiation of function template specialization 'diy::Master::foreach<void, (lambda at /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1180:18), diy::Master::NeverSkip>' requested here
:info:build       void          foreach(const Functor& f, T* aux)   { foreach<Block>(f, NeverSkip(), aux); }
:info:build                                                           ^
:info:build /opt/local/include/diy2/diy/master.hpp:221:59: note: in instantiation of function template specialization 'diy::Master::foreach<void, (lambda at /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1180:18), void>' requested here
:info:build       void          foreach(const Functor& f)           { foreach<Block>(f, (void*) 0); }
:info:build                                                           ^
:info:build /opt/local/include/diy2/diy/master.hpp:218:59: note: in instantiation of function template specialization 'diy::Master::foreach<void, (lambda at /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1180:18)>' requested here
:info:build       void          foreach(const Functor& f)           { foreach<void>(f); }
:info:build                                                           ^
:info:build /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1180:10: note: in instantiation of function template specialization 'diy::Master::foreach<(lambda at /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1180:18)>' requested here
:info:build   master.foreach([&] (DiyBlock* block_, const diy::Master::ProxyWithLink& cp) { PerformResampling(block_, cp, this->Prober.GetPointer()); });
:info:build          ^
:info:build /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1180:18: note: candidate function not viable: requires 2 arguments, but 3 were provided
:info:build   master.foreach([&] (DiyBlock* block_, const diy::Master::ProxyWithLink& cp) { PerformResampling(block_, cp, this->Prober.GetPointer()); });
:info:build                  ^
:info:build In file included from /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:44:
:info:build /opt/local/include/diy2/diy/master.hpp:319:87: error: no matching function for call to object of type 'const (lambda at /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1183:18)'
:info:build       void  execute(void* b, const ProxyWithLink& cp) const                         { f(static_cast<Block*>(b), cp, aux); }
:info:build                                                                                       ^
:info:build /opt/local/include/diy2/diy/master.hpp:316:13: note: in instantiation of member function 'diy::Master::Command<void, (lambda at /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1183:18), diy::Master::NeverSkip>::execute' requested here
:info:build             Command(const Functor& f_, const Skip& s_, void* aux_):
:info:build             ^
:info:build /opt/local/include/diy2/diy/master.hpp:678:29: note: in instantiation of member function 'diy::Master::Command<void, (lambda at /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1183:18), diy::Master::NeverSkip>::Command' requested here
:info:build     commands_.push_back(new Command<Block, Functor, Skip>(f, skip, aux));
:info:build                             ^
:info:build /opt/local/include/diy2/diy/master.hpp:227:59: note: in instantiation of function template specialization 'diy::Master::foreach<void, (lambda at /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1183:18), diy::Master::NeverSkip>' requested here
:info:build       void          foreach(const Functor& f, T* aux)   { foreach<Block>(f, NeverSkip(), aux); }
:info:build                                                           ^
:info:build /opt/local/include/diy2/diy/master.hpp:221:59: note: in instantiation of function template specialization 'diy::Master::foreach<void, (lambda at /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1183:18), void>' requested here
:info:build       void          foreach(const Functor& f)           { foreach<Block>(f, (void*) 0); }
:info:build                                                           ^
:info:build /opt/local/include/diy2/diy/master.hpp:218:59: note: in instantiation of function template specialization 'diy::Master::foreach<void, (lambda at /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1183:18)>' requested here
:info:build       void          foreach(const Functor& f)           { foreach<void>(f); }
:info:build                                                           ^
:info:build /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1183:10: note: in instantiation of function template specialization 'diy::Master::foreach<(lambda at /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1183:18)>' requested here
:info:build   master.foreach([&] (DiyBlock* block_, const diy::Master::ProxyWithLink& cp) { ReceiveResampledPoints(block_, cp, this->Prober->GetValidPointMaskArrayName()); });
:info:build          ^
:info:build /opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/ParaView-v5.6.1/VTK/Filters/ParallelDIY2/vtkPResampleWithDataSet.cxx:1183:18: note: candidate function not viable: requires 2 arguments, but 3 were provided
:info:build   master.foreach([&] (DiyBlock* block_, const diy::Master::ProxyWithLink& cp) { ReceiveResampledPoints(block_, cp, this->Prober->GetValidPointMaskArrayName()); });
:info:build                  ^
:info:build 3 errors generated.
:info:build make[2]: *** [VTK/Filters/ParallelDIY2/CMakeFiles/vtkFiltersParallelDIY2.dir/vtkPResampleWithDataSet.cxx.o] Error 1
:info:build make[2]: Leaving directory `/opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/build'
:info:build make[1]: *** [VTK/Filters/ParallelDIY2/CMakeFiles/vtkFiltersParallelDIY2.dir/all] Error 2
:info:build make[1]: Leaving directory `/opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/build'
:info:build make: *** [all] Error 2
:info:build make: Leaving directory `/opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/build'
:info:build Command failed:  cd "/opt/local/var/macports/build/_Users_****_git_macports-ports_science_paraview/paraview/work/build" && /usr/bin/make -w all VERBOSE=ON 
:info:build Exit code: 2
:error:build Failed to build paraview: command execution failed
:debug:build Error code: CHILDSTATUS 10705 2
:debug:build Backtrace: command execution failed
:debug:build     while executing
:debug:build "system {*}$notty {*}$nice $fullcmdstring"
:debug:build     invoked from within
:debug:build "command_exec build"
:debug:build     (procedure "portbuild::build_main" line 8)
:debug:build     invoked from within
:debug:build "$procedure $targetname"
:error:build See /opt/local/var/macports/logs/_Users_****_git_macports-ports_science_paraview/paraview/main.log for details.
```
[main.log.gz](https://github.com/macports/macports-ports/files/3431794/main.log.gz)

**Comment by rubendibattista** [comment]
The `DiY2` shipped with ParaView has a patch if I remember well. That's why I did not enable all the system libraries.

**Comment by MarcusCalhoun-Lopez** [comment]
> The `DiY2` shipped with ParaView has a patch if I remember well. That's why I did not enable all the system libraries.

I am sorry, but I am unable to reproduce this problem.
I am still trying to track down the discrepancy.

**Comment by rubendibattista** [comment]
If you check other package managers, like for example [spack](https://github.com/spack/spack/blob/4f9116dae24138fee4cf1c2f8527ad5a53dda042/var/spack/repos/builtin/packages/paraview/package.py#L186), they also do not enable `diy2`. 

I stumbled into this previously, I think while I was improving the `spack` [VTK package](https://github.com/spack/spack/blob/4f9116dae24138fee4cf1c2f8527ad5a53dda042/var/spack/repos/builtin/packages/vtk/package.py#L140).

For what it looks like, if `mpi` is enabled, system `diy2` does not work.

Are you building with mpi variant?

**Pull request merged**
