### PR TITLE
libuv: bump older systems to 1.29.1

### PR DESCRIPTION
**Pull request by kencu**
add patch for older gcc versions to not error on pragmas
add patch for 32bit code to link correctly
add bypass path for Tiger, that doesn't seem to have
  a non-cancellable close function available
closes: https://trac.macports.org/ticket/58507

### CODE REVIEW

**Comment by markemer** [comment]
Tiger? That's commitment.

**Comment by kencu** [comment]
I'm not completely sure I have those defines just right in that GNUC/pragma stuff. We want those pragmas active for clang, as I presume that's why they are there. Also, the MINGW stuff can be left out.

The close$NOCANCEL$UNIX2003 business seems to compile and link on 10.5+, but failed on 10.4. I don't really know how to rigorously test that, but I think that is working OK.

**Comment by michaelld** [comment]
When I was updating libuv recently, I thought about rearranging the Portfile to have just the release & devel, and then clauses specific for each group of OSs already represented. I decided against it because it seems like libuv needs to be tested with each release and devel commit for compatibility with these older OSs ... and, looks like I was correct this time (¿yay me?)!

**Comment by michaelld** [comment]
I'll add a note to test these changes out at work tomorrow on some of my build computers including my fresh & new 10.4 PPC boot!

**Comment by kencu** [comment]
I tweaked it a bit -- I think this is more like what we need.

**Comment by kencu** [comment]
see also <https://github.com/libuv/libuv/pull/2309> for part of the PR (thought I would got at it bit by bit there)

**Comment by michaelld** [comment]
Trying this on 10.4 PPC right now. Has to update `libiconv` first, so it'll be a few hours LOL

**Comment by kencu** [comment]
I have a feeling I might be able to improve Tiger by making it do the linux thing
```
#elif defined(__linux__)
return syscall(SYS_close, fd);
 ```

but I'm not sure it's worth the spaghetti code...

**Comment by michaelld** [comment]
This builds nicely on 10.4 PPC. Let me try on 10.5.

**Comment by michaelld** [comment]
Plenty of "make check" errors, but whatever it does build!

**Comment by michaelld** [comment]
Worked on 10.5 Intel too. Same "make check" errors; same-same all around. I'm good with this if you are @kencu .

**Comment by michaelld** [comment]
Interestingly, the compile does have a few warnings (I think just 3), which look easy to fix & would be upstream-able.

**Comment by kencu** [comment]
Sure, I think it's good to go. I don't know if we'll ever squash all the make check and compile warnings, but pretty functional I believe.

**Comment by kencu** [comment]
Upstream has set 10.7 as their focus point, but if I'm gentle and don't make too much pasta of their code, they'll accept small fixes that make our life easier on this end.

**Pull request merged**
