### PR TITLE
Chatty: new port and its dependencies

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

`olm` update is needed for `libcmatrix`.

Since both `libcmatrix` itself and `Chatty` need `libsoup3`, existing `e-d-s` port does not work (build succeeds, the app fails to launch). So I add -gtk4 version to support `Chatty` without affecting existing gtk3-based Gnome ports.

A couple of ports here list both gtk3 and gtk4 as dependencies: that is not a mistake.

P. S. Cannot test build on powerpc at the moment, but it will be done somewhat later.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.7
Xcode 15.4

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
How do I force clang-18+? Blacklists do not work as I thought they would.

**Comment by barracuda156** [comment]
@reneeotten @herbygillot Bump

**Comment by reneeotten** [comment]
did upstream accepted/commented on any of the patches?

**Comment by barracuda156** [comment]
This needs some extra fixes to build on older systems. Draft until everything works.

**Comment by barracuda156** [comment]
macOS 15 times out. Everything builds fine, including legacy systems.

**Pull request merged**
