### PR TITLE
SoapySDR modules

### PR DESCRIPTION
**Pull request by ra1nb0w**
#### Description

Support for the following devices on SoapySDR:
- SoapyPlutoSDR
- SoapyRemote
- SoapyBladeRF
- SoapyAirspyHF
- SoapyAudio
- SoapyAirspy
- SoapyHackRF
- SoapyUHD
- SoapyRedPitaya

In this way you can use those devices with clients that support SoapySDR API, like CubicSDR.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.4 18E226
Xcode 10.2 10E125

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
@michaelld Are you OK with the changes here ?

**Comment by michaelld** [comment]
@cjones051073 broadly speaking, I'm OK ... I haven't had time to test / verify yet. Give me through the weekend & then we can commit Monday (regardless of my efforts, but hopefully I'll find the time do check these out).

**Comment by chrstphrchvz** [comment]
Note that there is already request for `SoapyRemote` from a couple years ago: https://trac.macports.org/ticket/52540

I have again left a comment asking if the original requester would like to co-maintain the port.

**Comment by ra1nb0w** [comment]
> I have again left a comment asking if the original requester would like to co-maintain the port.

thank you

**Comment by michaelld** [comment]
I did some basic testing & it all worked. I'm going to go ahead and merge & we can fix up maintainers and/or other issues later, if/as need by. Thanks again!

**Comment by ra1nb0w** [comment]
Thank you @michaelld

**Pull request merged**
