### PR TITLE
jd-gui: update to 1.6.6

### PR DESCRIPTION
**Pull request by lhaeger**
###### Tested on

macOS 10.15.2 19C57
Xcode 11.3 11C29

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
@lhaeger This seems okay to me but I really don't feel qualified to evaluate the Java changes. Have you submitted those upstream, btw?

**Comment by lhaeger** [comment]
@pmetzger Yes, I've send a pull request for patch to enable native macOS file dialogs in parallel to the jd-gui project (--> https://github.com/java-decompiler/jd-gui/pull/283) but did not want to wait for approval since it's pretty concise and straight forward and just seems to work.
I could remove the `default_variants` statement and make it an optional choice until upstream includes the patch, if you think that's a safer choice.

**Comment by pmetzger** [comment]
I don't really have an opinion on whether it's a better choice or not. What we need is someone better qualified to evaluate this PR.

**Comment by lhaeger** [comment]
> I don't really have an opinion on whether it's a better choice or not. What we need is someone better qualified to evaluate this PR.

I've removed the default_variants statement and added "experimental" to the variant description, so nobody should get the patch by default and those who choose to use it should understand that it's at their own risk.
If/when upstream merges their pull request this will tickle down into the non-variant code anyway and until then it's an easy way to try it out (which might help getting the upstream PR validated and accepted).

**Pull request merged**
