### PR TITLE
harfbuzz: update version to 2.4.0

### PR DESCRIPTION
**Pull request by ra1nb0w**
#### Description

- bump version to 2.4.0
- remove patch dont-use-TARGET_OS_OSX.patch because it is in upstream

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.4 18E226
Xcode 10.2 10E125

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
> Port harfbuzz **fail** on xcode7.3. [Log](https://paste.macports.org/6e016821e793)
> Port harfbuzz-icu's dependencies **fail** on xcode7.3. [Log](https://paste.macports.org/777aa3e2df59)

```
./hb-algs.hh:49:3: error: default initialization of an object of const type 'const struct (anonymous struct at ./hb-algs.hh:35:14)' without a user-provided default constructor
} hb_hash HB_UNUSED;
  ^
```

I filed [an upstream bug report](https://github.com/harfbuzz/harfbuzz/issues/1651) for this. Let's wait and see whether it can be fixed with a patch or whether we need to `compiler.blacklist-append {clang < 800}`.

**Comment by ra1nb0w** [comment]
I see. thank you for the report.

**Comment by ryandesign** [comment]
The error we're seeing with Apple clang < 800 (Xcode < 8) was considered a bug in the C++ standard; the C++ standard was changed and Apple clang >= 800 (Xcode >= 8) observe the revised standard and no longer issue the error. Harfbuzz developers are discussing how to handle this.

I also tested MacPorts clang 4 and 5 and they don't exhibit the error. Makes sense, since clang 4 was released 6 months after Xcode 8. I didn't bother testing earlier versions since MacPorts C++11 support already requires MacPorts clang 5.

Note that [upstream has rereleased the 2.4.0 tarball](https://github.com/harfbuzz/harfbuzz/issues/1641#issuecomment-480475195), so the checksums in this PR are no longer correct.

**Comment by ra1nb0w** [comment]
thank you for the testing. Update and tested on my macOS 10.14

**Comment by ryandesign** [comment]
I forgot about this PR and the reasons why I wasn't merging it, and updated the ports to 2.4.0 in 06280710096891a3d39e75dc58c611ca1b2b3c22. They appear to have built fine on all OS versions.

**Comment by ra1nb0w** [comment]
thank you

**Pull request closed without merging**
