### PR TITLE
ImageMagick: Bump version and revbump dependents

### PR DESCRIPTION
**Pull request by rubendibattista**
#### Description

See #5014 for reference. I updated imagemagick to the last version 6 and rev-bumped all the dependents ports (hopefully). This also fix a bug I was experiencing while converting `svgs` and `eps` files.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by neverpanic** [comment]
Are the revbumps actually needed for what seems to be a minor update of ImageMagick? Did the ABI or API change?

**Comment by rubendibattista** [comment]
From #5014, it seems that the library version changed with this update... So yes.  (cit. @ryandesign )

**Comment by ryandesign** [comment]
The developers of ImageMagick have no concept of semver or sensible API/ABI versioning. Library major versions often change in seemingly minor version updates.

**Comment by ryandesign** [comment]
Instead of deleting the `revision` line from ImageMagick, please set it to `revision 0`, and add that line to p5-perlmagick as well after the line containing the version. (We used to recommend not using `revision 0` lines since that's the default, but we now prefer to add them, as it helps other developers know where to revbump; this is all the more helpful in ports that have subports, where each subport might have a different revision.)

The ticket that this commit resolves should be mentioned in the commit message, like this:

```
ImageMagick: Update to 6.9.10-60 and revbump dependents

Closes: https://trac.macports.org/ticket/57903
```

That way, Trac will automatically reference the commit in the ticket and close the ticket.

**Comment by ryandesign** [comment]
> I haven't yet checked if this revbumps all of the ports that need to be revbumped.

Ok, it looks like you did identify all of the ports that mention a dependency on `port:ImageMagick`. Did you just go by that, or did you install each port to see if it actually links with the libraries?

Some of those ports have the dependency in `depends_run`, which indicates that the dependency is only needed at runtime, not at compile time, which (if the dependency has been declared correctly, which we hope, but which is not necessarily the case) means it cannot be using the libraries and doesn't need to be revbumped. (Those ports are probably only using the `convert` program at runtime.) Here is a possibly incomplete list of those ports:

```
$ port echo depends_run:imagemagick
kde4-kile
latex2rtf
mediawiki
scapy
scapy-devel
spidereyeballs
vcs
vis5d
wv
yap-app
```

Similarly, ports that mention the dependency in `depends_build` probably only need the `convert` program at build time (again, assuming the dependency declaration is correct) so they don't need to be revbumped either. Here is a possibly incomplete list of those ports:

```
$ port echo depends_build:imagemagick
advi
awesome
chemical-mime-data
enigma
enigma-devel
gri
metview
postgis
tango-icon-theme
tango-icon-theme-extras
vis5d
```

Even those ports having the dependency in `depends_lib` do not necessarily link with the library. But they might need the `convert` program at runtime, and they might check for its presence at configure time, and in those cases, rather than listing a dependency twice, once in `depends_build` and again in `depends_run`, our current practice is to just list it in `depends_lib`.

You didn't modify the ports that mention a dependency on `bin:convert:ImageMagick` (ftgl, kde4-kile, latex2rtf) which is ok because those ports claim to only need the `convert` binary and therefore hopefully don't link with the libraries.

Someday I had hoped to separate the libraries into subports different from the main ImageMagick port which would then install only the programs like `convert` and their manuals. If that were done, then ports could specify more precisely what they depended on—the programs or the libraries—and that would make it easier to know what to revbump. (Compare with netpbm where I already separated the libraries out into a libnetpbm subport for this reason, among others.) But I certainly don't expect you to do that as part of this PR.

**Comment by rubendibattista** [comment]
@ryandesign Thanks for doing the review. Ok, I'll apply what you suggest. What I did is I just grepped for `port:ImageMagick` in the port tree and updated all the revisions. I know, a bit a shotgun approach :). But TIL `port echo depends_build`, I should probably check the `man` page more often. 

I'll also update the commit message to make it recognisable by the trac system.

**Comment by rubendibattista** [comment]
Ok, I fixed the revbumps for `depends_run` and `depends_build`.

**Comment by rubendibattista** [comment]
I don't understand what's happening with `Azure` pipelines. Why they fail? Time limit?

**Comment by neverpanic** [comment]
Since they both failed after 6h and 10 minutes, that's probably the reason, yes.

**Comment by rubendibattista** [comment]
Ok, so I think this is ok. The only doubt I have is about `tiff`. I needed to add autotools dependency since it was erroring on Xcode 7.4 and 8.4. Do I need to restrict the dependency only to those?

**Comment by ryandesign** [comment]
> The only doubt I have is about `tiff`. I needed to add autotools dependency since it was erroring on Xcode 7.4 and 8.4. Do I need to restrict the dependency only to those?

It looks like the *only* change you made to the tiff port was to add those dependencies. So it has nothing to do with this PR and should be removed from it. If you are having problems building tiff without those dependencies, you should submit a bug report with a log so it can be investigated.

**Comment by rubendibattista** [comment]
@ryandesign I think the problem with `tiff` was on the Azure pipelines or Travis, so I'm not able to reproduce it on my machine and I cannot post a log. 

I reverted the change... Hopefully I can get the log back from the pipelines.

@kencu I'll incorporate also your change.

**Comment by rubendibattista** [comment]
Anyone can help me understanding why I'm not able to see the logs on Azure anymore?

**Comment by rubendibattista** [comment]
If someone could help me to get the logs on Azure, I'll try to see if the problem with autotools deps with `tiff` are really needed or not.

**Comment by kencu** [comment]
Some other things got mixed up in the part of the PR that was related to disabling openmp. not sure how, but I guess that should be deleted and then we can address that separately -- sorry about the hassle.

**Comment by rubendibattista** [comment]
@kencu Wait I don't understand. The fact that the commit contains other stuff is because I'm rebasing time after time and applying edits to fix conflicts without adding a commit each time...

**Comment by pmetzger** [comment]
Okay, where is this stuck at this point?

**Comment by rubendibattista** [comment]
Always at the same point. I'm not able to read the output of the Azure pipelines, and I need it since it's there that I saw the problem with `libtiff` and the missing `autotools` dependency.

I'm currently just rebasing on `master`. I need someone that helps me getting the logs of the builds on the pipelines...

**Comment by kencu** [comment]
I’m not sure that Ryan has any intention of merging this, otherwise it would have been done by now.

**Comment by pmetzger** [comment]
@kencu I think @rubendibattista is having trouble because he can't read the Azure output.

**Comment by rubendibattista** [comment]
Ok people, since nobody seems able to help me with the logs, since this builds on my machine, if you can test it manually also yourselves, we can merge it and then deal with issues if they come by...

**Comment by ryandesign** [comment]
> I’m not sure that Ryan has any intention of merging this, otherwise it would have been done by now.

I don't have time/interest. Others should please take the lead and do whatever is correct.

**Comment by ryandesign** [comment]
If this can be updated to version 6.9.10-71 it will fix https://trac.macports.org/ticket/57740 as well.

**Comment by ryandesign** [comment]
My mistake, https://trac.macports.org/ticket/57740 was fixed in 6.9.10-39 so this PR already covers it. However, updating to 6.9.10-71 is still a good idea.

**Comment by pmetzger** [comment]
@mf2k Do you suppose you could help me shepherd this through?

**Comment by mf2k** [comment]
@pmetzger: What do you propose? I am not particularly knowledgable about this software and @ryandesign is the maintainer. I was skipping this PR entirely and assuming he would push this through. I would say commit it with maintainer timeout if you think it is good.

**Comment by mf2k** [comment]
Once the conflicts get resolved.

**Comment by pmetzger** [comment]
I'm going to commit this. @ryandesign do you want to be taken off as the port maintainer?

**Comment by ryandesign** [comment]
No I don't want to be taken off as maintainer just yet.

It looks like we forgot to revbump pstoedit (see 9655006705378a72c7dc7aa5da309a581d907842) and inkscape (see 23359ff17e75f14ad0dd6cf3b8e6ce4b532b25e2). How did we forget those, and did we forget anything else?

**Comment by rubendibattista** [comment]
@ryandesign I guess it's my fault. My grepping around was not perfect! :)

**Pull request merged**
