### PR TITLE
libedit: Update to 20210910-3.1

### PR DESCRIPTION
**Pull request by judaew**
#### Description

I tested this change only for macOS 11.. As this update introduces many changes, it should be well tested. That's why I don't squashed this.

- libedit: update to 20210910-3.1
- libedit: Remove readline.c and history patch
  Revision 1.163-1.164 should fix this problem. 
See: http://cvsweb.netbsd.org/bsdweb.cgi/src/lib/libedit/readline.c?sortby=date#rev1.164
- libedit: Update src__Makefile.in patch
- libedit: getline.c is now exist in the new version

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.6 20G165 x86_64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by judaew** [comment]
I checked for [trac-57584](https://trac.macports.org/ticket/57584) after removing the history patch. It looks like the problem is fixed in upstream.

**Comment by pmetzger** [comment]
FYI, Christos (the upstream dev) is a very nice guy, so anything you find, he'll almost certainly be responsive to and fix.

**Comment by pmetzger** [comment]
Given that @MarcusCalhoun-Lopez hasn't answered in a while, if you are comfortable that this is in good shape, @judaew, I think you can commit it.

**Comment by judaew** [comment]
@pmetzger Thank you for your attention, I just thought about it. This update looks good to me. I added myself to the maintainers. If something breaks for older versions of macOS, I'll try to fix it quickly.

**Comment by judaew** [comment]
In any case, sooner or later we will have to update this port.

**Comment by MarcusCalhoun-Lopez** [comment]
I am sorry about not being able to look at any of these pull requests.
Repercussions from the pandemic have caused formidable demands on my time.
Hopefully, I can get back to my MacPorts responsibilities soon.
Whatever the consensus is fine with me.

**Comment by pmetzger** [comment]
Merged. And thanks for all your help over time, @MarcusCalhoun-Lopez . Don't worry about it if you have other things you need to deal with!

**Comment by judaew** [comment]
All is well 🌟

Maintaining in MacPorts doesn't bring in cash, it works for the soul in your free time if you have it. Otherwise, other members will help.

The pandemic also changed my life, I understand that very well. I sincerely wish you good luck with your things!

**Pull request merged**
