### PR TITLE
update multiple python ports

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.5 21G72 x86_64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
@mascguy I'm a co-mainater or maintaner of all this ports with exception of `py-werkzeug` where I'd like to be.

Am I right that we should wait 72 hours?

**Comment by mascguy** [comment]
> @mascguy I'm a co-mainater or maintaner of all this ports with exception of `py-werkzeug` where I'd like to be.
> 
> Am I right that we should wait 72 hours?

Yes, unless Andrew approves sooner.

**Review by mascguy — APPROVED** [review]
LGTM. @stromnov?

**Comment by stromnov** [comment]
Yep, LGTM too.

**Pull request merged**
