### PR TITLE
py-sentence-transformers: Update to version 2.0.0

### PR DESCRIPTION
**Pull request by essandess**
py-sentence-transformers: Update to version 2.0.0

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.5 20G71 x86_64
Xcode 12.5.1 12E507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
> [essandess](/essandess) [force-pushed](/macports/macports-ports/compare/02727dacbaf9b0d6bd6a64d4ddbaf2be4ea948af..9040521dc5b8ec47e3f317bb74b251d5b3415ed3) the essandess:py-sentence-transformers  branch

Did something change?

**Comment by essandess** [comment]
> Did something change?

No, the build error looked like a CI error, so I just amended an empty commit to kick off the build again.

**Comment by ryandesign** [comment]
I think the previous CI runs failed because they took too long, same as in #11669.

**Comment by ryandesign** [comment]
And they take too long because of mpbb bug https://trac.macports.org/ticket/62621

**Pull request merged**
