### PR TITLE
various ports: use Python 3.12

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
Python 3.12 is MacPorts' default Python version since January 1st, start having ports use this.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 14.3 23D56 x86_64
Xcode 15.2 15C500b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
> Python 3.12 is MacPorts' default Python version since January 1st

While this is true, have you checked each of these ports to ensure that they're compatible with Python 3.12? And I don't just mean that it builds successfully. Have you checked each project's release notes or web site for a statement of Python 3.12 compatibility? In several other ports, we've already encountered problems as a result of having switched to Python 3.12 without having tested everything properly and I want to avoid that happening with any further ports.

**Comment by reneeotten** [comment]
> > Python 3.12 is MacPorts' default Python version since January 1st
> 
> While this is true, have you checked each of these ports to ensure that they're compatible with Python 3.12? And I don't just mean that they build successfully. Have you checked each project's release notes or web site for a statement of Python 3.12 compatibility, or checked their issue trackers for Python 3.12-related problems? In several other ports, we've already encountered problems as a result of having switched to Python 3.12 without having tested everything properly and I want to avoid that happening with any further ports.

well, I have done what is reasonable to ask from someone who doesn't maintain the ports. It builds for all, all scripts and/or programs run without throwing an error message. I did not check all upstream repositories to see whether it's "officially" supported, but as we all know classifiers aren't always updated even though it works fine. All maintainers are notified and can/should feel free to verify that it works in their usual workflow.

I am not sure what other ports you refer to had issues with a change to Python 3.12 - sure there have been some issues with the removal of `disutils` but other than that I haven't seen many problems.

**Comment by danchr** [comment]
Please leave out the Mercurial ports, as the `rust` variant doesn't work with 3.12, last I checked.

**Comment by ryandesign** [comment]
> well, I have done what is reasonable to ask from someone who doesn't maintain the ports. It builds for all, all scripts and/or programs run without throwing an error message. I did not check all upstream repositories to see whether it's "officially" supported, but as we all know classifiers aren't always updated even though it works fine. All maintainers are notified and can/should feel free to verify that it works in their usual workflow.

Yes, I understand all that, and I appreciate the effort… What I feel is likely to happen is that a maintainer will ignore the PR notification, or they will visit the PR, see what looks like a minor routine change, see that the CI succeeded (which it hasn't yet, actually), and then do nothing or indicate their approval of the PR without testing it further. After three days, someone will see that maintainer timeout has occurred and will merge the PR, at which point the problem reports will start rolling in, which will take time to identify and resolve, and until then some of the ports will be broken. I'm suggesting that it might be preferable to leave ports using a version of Python they're known to work with until someone can devote the time and energy to verifying Python 3.12 compatibility and dealing with any followup fixes that might be needed.

> I am not sure what other ports you refer to had issues with a change to Python 3.12

A few problems caused by updating to Python 3.12 that come to mind are those with [glib2](https://trac.macports.org/ticket/69036), [gobject-introspection](https://trac.macports.org/ticket/69105), and [xonsh](https://trac.macports.org/ticket/69228). The first two were caused by the removal of distutils, the third one is something different. The point is that the builds succeeded and it wasn't until after the changes were committed that users realized the installed programs didn't work, which inconvenienced users.

I also encountered new warnings when switching magic to Python 3.12 (which I fixed, and which didn't seem to cause problems, but I don't know if that's always going to be the case), and I was [unable to switch mongodb to Python 3.12](https://jira.mongodb.org/browse/SERVER-85760) because of build failures (which I reported and the developers have not responded to yet). I'm also regretting that I already switched scons to Python 3.12; I have a feeling there are probably SConscript files out there that are not compatible with Python 3.12. (I mean, I'm still finding ports with SConscript files that aren't compatible with any version of Python 3.)

**Pull request closed without merging**
