### PR TITLE
libjpeg-turbo: update to 2.1.0

### PR DESCRIPTION
**Pull request by kencu**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G9028 x86_64
Xcode 11.3.1 11C504

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

there are some new cmake files included in this version:
```
  /opt/local/lib/cmake/libjpeg-turbo/libjpeg-turboConfig.cmake
  /opt/local/lib/cmake/libjpeg-turbo/libjpeg-turboConfigVersion.cmake
  /opt/local/lib/cmake/libjpeg-turbo/libjpeg-turboTargets-macports.cmake
  /opt/local/lib/cmake/libjpeg-turbo/libjpeg-turboTargets.cmake
```

and NB there are several test failures on Mojave with this version that were not present with the previous version:
```
The following tests FAILED:
	 66 - cjpeg-shared-420-q100-ifast-prog (Failed)
	 67 - cjpeg-shared-420-q100-ifast-prog-cmp (Failed)
	 68 - djpeg-shared-420-q100-ifast-prog (Failed)
	 69 - djpeg-shared-420-q100-ifast-prog-cmp (Failed)
	 70 - djpeg-shared-420m-q100-ifast-prog (Failed)
	 71 - djpeg-shared-420m-q100-ifast-prog-cmp (Failed)
```

I am not quite sure yet why these errors are happening now.
```
 66/310 Test  #66: cjpeg-shared-420-q100-ifast-prog ..................***Failed    0.01 sec
Missing Huffman code table entry

        Start  67: cjpeg-shared-420-q100-ifast-prog-cmp
 67/310 Test  #67: cjpeg-shared-420-q100-ifast-prog-cmp ..............***Failed    0.01 sec
testout_420_q100_ifast_prog.jpg: FAILED.  Checksum is cb6cd6cac6911a5d11b78083275c19e3

        Start  68: djpeg-shared-420-q100-ifast-prog
 68/310 Test  #68: djpeg-shared-420-q100-ifast-prog ..................***Failed    0.01 sec
Corrupt JPEG data: premature end of data segment

        Start  69: djpeg-shared-420-q100-ifast-prog-cmp
 69/310 Test  #69: djpeg-shared-420-q100-ifast-prog-cmp ..............***Failed    0.01 sec
testout_420_q100_ifast.ppm: FAILED.  Checksum is d0c7f04752a3b0ca4223937fc7a60cd9

        Start  70: djpeg-shared-420m-q100-ifast-prog
 70/310 Test  #70: djpeg-shared-420m-q100-ifast-prog .................***Failed    0.01 sec
Corrupt JPEG data: premature end of data segment

        Start  71: djpeg-shared-420m-q100-ifast-prog-cmp
 71/310 Test  #71: djpeg-shared-420m-q100-ifast-prog-cmp .............***Failed    0.01 sec
testout_420m_q100_ifast.ppm: FAILED.  Checksum is 02b554ba2f46b763af007d1e3db5b28b

```

### CODE REVIEW

**Comment by kencu** [comment]
also both the old and new dylibs have a somewhat wonky compatibility version that is supposed to be not an allowable version, but there it is anyway:
```
/opt/local/lib/libturbojpeg.0.dylib (compatibility version 0.0.0, current version 0.2.0)
```

**Comment by kencu** [comment]
I suppose we really should sort out those test failures before this is committed. In the past, the message has been to just commit these PRs even if the tests fail, because passing tests is not MacPorts' problem to fix, it is upstream's problem to fix.

SO if that approach holds, feel free to commit and we can sort out any issues that turn up later.

**Comment by kencu** [comment]
given the unexplained test failures I'll close this pending some upstream fix or explanation.

**Comment by kencu** [comment]
attempt to close number deux

**Comment by jmroot** [comment]
The patch and the code setting `OVERRIDE_SYSTEM_PROCESSOR` should be OK to remove, since the build system now obeys `CMAKE_OSX_ARCHITECTURES` (but only supports a single value, so muniversal is still needed.)

**Comment by kencu** [comment]
sounds good. I'll also confirm building on this 10.7 machine in my lap while I'm at it.

**Comment by kencu** [comment]
10.7 builds it without issue, universal as well, with the removed patch.

exact same test failures on 10.7.5 noted, whatever they mean.

**Pull request merged**
