### PR TITLE
py-jsonschema-specifications: added new port, version 2023.11.1

### PR DESCRIPTION
**Pull request by johankytt**
#### Description

Port required for future py-jsonschema upgrade

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.6.2 22G320 arm64
Xcode 15.0.1 15A507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] ~~squashed and [minimized your commits](https://guide.macports.org/#project.github)?~~
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] ~~referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?~~ 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] ~~tried existing tests with `sudo port test`?~~
- [x] tried a full install with `sudo port -vst install`?
- [ ] ~~tested basic functionality of all binary files?~~
- [ ] ~~checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?~~

### CODE REVIEW

**Comment by reneeotten** [comment]
@johankytt please add missing dependency in a separate commit to this PR.

**Comment by reneeotten** [comment]
please "rebase" with master and force-push to this PR. We don't want merge commits.

**Comment by johankytt** [comment]
> please "rebase" with master and force-push to this PR. We don't want merge commits.

mmm, what do you mean exactly? The missing dependency is now available on macports and there's nothing else to merge with this PR.

**Comment by reneeotten** [comment]
> mmm, what do you mean exactly? The missing dependency is now available on macports and there's nothing else to merge with this PR.

If you check your commits you will see that there are now two of them, with the last one being:
```[Merge branch 'macports:master' into py-jsonschema-specifications]```

that one shouldn't be there.

**Comment by johankytt** [comment]
> > mmm, what do you mean exactly? The missing dependency is now available on macports and there's nothing else to merge with this PR.
> 
> If you check your commits you will see that there are now two of them, with the last one being: `[Merge branch 'macports:master' into py-jsonschema-specifications]`
> 
> that one shouldn't be there.

Ah, right. That must be because of syncing my fork with macports repo. Will try to sort it out.

**Comment by reneeotten** [comment]
@johankytt I did a rebase and pushed to your fork - all good now. Thanks for the submission!

**Pull request merged**
