### PR TITLE
curl: update to 8.8.0

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with ~`sudo port -vst install`~ `sudo port -d destroot`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
Curl 8.8.0 has a regression fixed here:

https://github.com/curl/curl/pull/13741

A patch for this should be included in this PR.

**Comment by herbygillot** [comment]
> Curl 8.8.0 has a regression fixed here:
> 
> [curl/curl#13741](https://github.com/curl/curl/pull/13741)
> 
> A patch for this should be included in this PR.

Added

**Comment by ryandesign** [comment]
curl-config.1 still doesn't get installed because the patch is for Makefile.am which does not take effect because the port does not use autoreconf. It's undesirable to use autoreconf since it adds dependencies and time to the build. I'd rather see the corresponding changes made to Makefile.in. To find the corresponding changes, manually run autoreconf and compare the newly-generated Makefile.in with the one from the distribution. If you don't use the same exact version of automake and other related dependences as the creator of the distribution, the set of differences may include irrelevancies which should not be included in the patch.

**Comment by herbygillot** [comment]
The patch has now been switched over to patching `Makefile.in`, and it looks like `curl-config.1` is now being installed.

**Pull request merged**
