### PR TITLE
Remove two old ports that are incompatible with OpenSSL 1.1

### PR DESCRIPTION
**Pull request by yan12125**
#### Description

Both ports:

* Have replacements
* Incompatible with OpenSSL 1.1
* No maintainer
* No dependents
* The build failure with OpenSSL 1.1 is the only remaining open Trac ticket

So I propose to remove them rather than fix them for OpenSSL 1.1 compatibility.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
Untested

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
s-nail may now be s-mailx, fwiw.

**Comment by yan12125** [comment]
Ah good catch. I didn't notice the "later S-mailx" note in https://www.sdaoden.eu/code.html. I think it's not a big deal as both names are used in the upstream site and `port search mailx` also includes s-nail.

**Comment by pmetzger** [comment]
I personally wouldn't have thought to look at "s-nail" for a mailx replacement though. (Or do do "port search" to find what I was looking for, I tend to use the web site.)

**Comment by yan12125** [comment]
I think you are right. Feel free to create s-mailx and obsolete s-nail.

**Comment by pmetzger** [comment]
It isn't clear to me what the official name is really supposed to be, though. :(

**Comment by yan12125** [comment]
I think I should ask on upstream mailing list (https://lists.sdaoden.eu/mailman/listinfo.cgi/s-mailx) for clarification. Do you want me to CC you (e.g., using the email listed on https://github.com/pmetzger)?

**Comment by pmetzger** [comment]
Please do if you like, yes!

**Pull request closed without merging**
