### PR TITLE
binutils: update to 2.29

### PR DESCRIPTION
**Pull request by l2dy**
###### Tested on
macOS 10.12
Xcode 8.3.3

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by l2dy** [comment]
@mojca binutils update again.

**Comment by mojca** [comment]
Thank you. Usually these updates work pretty well, at least for ports with the `crossbinutils` portgroup. I see that `arm-aout-binutils` is broken, maybe we could have a closer look at that one. Version 2.27 has been built successfully at least based on `http://packages.macports.org/arm-aout-binutils/`. (I have nasty ideas about trying to force push this several times, until all subports have been tested ... - don't take this idea seriously though :)

Go ahead with updates of my ports.

@g5pw: ping, many of your binutils ports are still outdated.

**Comment by l2dy** [comment]
@mojca I commented about `arm-aout-binutils` in the last binutils PR https://github.com/macports/macports-ports/pull/361#issuecomment-286034401.

```
*** Configuration arm-unknown-aout is obsolete.
*** Specify --enable-obsolete to build it anyway.
*** Support will be REMOVED in the next major release of BINUTILS,
*** unless a maintainer comes forward.
```

**Comment by l2dy** [comment]
@mojca Should I add a comment in the ticket?

**Pull request merged**
