### PR TITLE
newlisp: update to 10.7.5, restore PPC and i386

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update, restore archs dropped for no good reason. Add test target.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.8.5
Xcode 5.1.1

macOS 10.6.8 Server (ppc, x86_64)
Xcode 3.2.6

macOS 10A190 (ppc)
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
Test results on 10.6.8 `x86_64`:
```
--->  Testing newlisp
Executing:  cd "/opt/x86_64/var/macports/build/_opt_x86_64_SnowLeopardPorts_lang_newlisp/newlisp/work/newlisp-10.7.5" && /usr/bin/make check 
./newlisp qa-dot

Testing built-in functions ...
                               
Testing contexts as objects and scoping rules ...

total time: 2631

>>>>> ALL FUNCTIONS FINISHED SUCCESSFUL: ./newlisp

./newlisp qa-specific-tests/qa-dictionary

Testing and benchmarking namespaces
N of associations: 10000
number of cells before creating Lex: 40818
time to aquire from association list: 4.429 ms
time to aquire one entry: 0.443 μs
time reading and verifying entries ... : 7 ms
time to read and verify one entry: 0.700 μs
time to only read one entry: 0.500 μs
number of cells after creating Lex: 50819
N of symbols in Lex: 10000
time to save to file: 17.89 ms
time to delete namespace: 3.856 ms
time to delete one symbol: 0.386 μs
number of cells after deleting Lex: 40818
time to load namespace: 10.968 ms
number of cells after loading Lex: 50818
time to save Lex2: 16.716 ms

>>>>> Dictionary API tested SUCCESSFUL
./newlisp qa-specific-tests/qa-xml

Testing XML functions
testing: xml-parse and xml-type-tags
true true true true true

>>>>> XML API tested SUCCESSFUL

Testing xml-parse with callback feature
parsed expresson:(NAME "apple"), source:<NAME>apple</NAME>
parsed expresson:(COLOR "red"), source:<COLOR>red</COLOR>
parsed expresson:(PRICE "0.80"), source:<PRICE>0.80</PRICE>
parsed expresson:(NAME "orange"), source:<NAME>orange</NAME>
parsed expresson:(COLOR "orange"), source:<COLOR>orange</COLOR>
parsed expresson:(PRICE "1.00"), source:<PRICE>1.00</PRICE>
parsed expresson:(NAME "banana"), source:<NAME>banana</NAME>
parsed expresson:(COLOR "yellow"), source:<COLOR>yellow</COLOR>
parsed expresson:(PRICE "0.60"), source:<PRICE>0.60</PRICE>


>>>>> XML callback tested SUCCESSFUL

./newlisp qa-specific-tests/qa-json
>>>>> JSON translation tested SUCESSFUL

./newlisp qa-specific-tests/qa-setsig

Testing signals

...sig-1 .sig-2 ...sig-3 .sig-4 ..sig-5 ..sig-6 ...sig-7 .sig-8 ..sig-10 ..sig-11 ..sig-12 ..sig-13 ..sig-14 ...sig-15 .sig-16 
sent: (1 2 3 4 5 6 7 8 10 11 12 13 14 15 16)
received: (1 2 3 4 5 6 7 8 10 11 12 13 14 15 16)

>>>>> Signal testing SUCCESSFUL

./newlisp qa-specific-tests/qa-net

Testing network API and server mode IPv4
Testing IPv4 networking functions

target URL: http://localhost:10001//opt/x86_64/var/macports/build/_opt_x86_64_SnowLeopardPorts_lang_newlisp/newlisp/work/newlisp-10.7.5/qa-junk.txt
host: localhost
port: 10001
path: /opt/x86_64/var/macports/build/_opt_x86_64_SnowLeopardPorts_lang_newlisp/newlisp/work/newlisp-10.7.5/qa-junk.txt
Starting server on localhost
waiting for server ...
net-connect to wrong port ->OK
get-url ->OK
net-eval normal mode ->OK
net-eval error reporting ->OK
save to URL ->OK
loading target URL: http://localhost:10001//opt/x86_64/var/macports/build/_opt_x86_64_SnowLeopardPorts_lang_newlisp/newlisp/work/newlisp-10.7.5/qa-junk.txt
load from URL ->OK
100000 bytes transferred for qa-junk.txt
write-file to remote URL ->OK
read-file from remote URL ->OK
delete-file from remote URL ->OK
destroy -> 25854 ->true

duration -> 1050 ms

>>>>> Network eval and network file functions IPv4 SUCCESSFUL

./newlisp qa-specific-tests/qa-cilk

Testing Cilk API
(abort) -> true
(sync)  -> ()
(sync) -> (25885 25884 25883 25882 25881 25880 25879 25878 25877 25876)
N of processes -> 10
waiting  to sync -> true
fibo(5) -> (needs 15 processes) => wait/sync up to 20 secs
wait/sync up to 20 secs
wait/sync up to 20 secs
wait/sync up to 20 secs
wait/sync up to 20 secs
wait/sync up to 20 secs
wait/sync up to 20 secs
8
inlet pid: 25900 p1:400
inlet pid: 25901 p2:500
true

>>>>> The Cilk API tested SUCCESSFUL

./newlisp qa-specific-tests/qa-ref

testing reference passing to/from built-in functions

>>>>> Reference testing SUCCESSFUL
./newlisp qa-specific-tests/qa-message

testing message API
10 child processes transmit 100 random status numbers
>>>>> Time per simple message: 7 micro seconds

10 round trips to 10 child processes
send out and receive it back uppercased with child pid appended
>>>>> Time per round trip : 380 micros seconds

A:25924-> parent-proxy:25903 -> B:25925

parent exiting ...

>>>>> Time per proxy trip: 20 micro seconds

>>>>> Message API tested SUCCESSFUL
./newlisp qa-specific-tests/qa-win-dll

Testing Windows DLL calls
not tested on OSX
./newlisp qa-specific-tests/qa-bigint 10000
>>>>> testing big ints arithmetik ... 
..........
..........
>>>>> abs bigint float gcd length zero? + - * / % ++ -- big ints tested SUCCESSFUL
./newlisp qa-specific-tests/qa-bench

254 non I/O functions performed SUCCESSFUL in 3.959 ms

>>>>> Benchmarking all non I/O primitives ... (may take a while)
>>>>> total time: 2433.477000000001
>>>>> Performance ratio: 0.98 (1.0 on macOS 10.12, MacBook (Retina, 12-inch, Early 2016), newLISP v10.7.3-64-bit)
```

**Comment by barracuda156** [comment]
Test results on 10.6.8 Rosetta `ppc`:
```
Testing built-in functions ...
                               
Testing contexts as objects and scoping rules ...

total time: 3447

>>>>> TESTING: ./newlisp FINISHED WITH ERRORS:

 >>>> semaphore failed nil
tar czvf newlisp-macos-utf8.tgz newlisp newlisp.dylib
a newlisp
a newlisp.dylib
make: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_newlisp/newlisp/work/newlisp-10.7.5'
--->  Testing newlisp
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_newlisp/newlisp/work/newlisp-10.7.5" && /usr/bin/make check 
./newlisp qa-dot

Testing built-in functions ...
                               
Testing contexts as objects and scoping rules ...

total time: 3429

>>>>> TESTING: ./newlisp FINISHED WITH ERRORS:

 >>>> semaphore failed nil
./newlisp qa-specific-tests/qa-dictionary

Testing and benchmarking namespaces
N of associations: 10000
number of cells before creating Lex: 40818
time to aquire from association list: 13.236 ms
time to aquire one entry: 1.324 μs
time reading and verifying entries ... : 28 ms
time to read and verify one entry: 2.800 μs
time to only read one entry: 1.800 μs
number of cells after creating Lex: 50819
N of symbols in Lex: 10000
time to save to file: 52.761 ms
time to delete namespace: 12.14 ms
time to delete one symbol: 1.214 μs
number of cells after deleting Lex: 40818
time to load namespace: 64.09699999999999 ms
number of cells after loading Lex: 50818
time to save Lex2: 46.193 ms

>>>>> Dictionary API tested SUCCESSFUL
./newlisp qa-specific-tests/qa-xml

Testing XML functions
testing: xml-parse and xml-type-tags
true true true true true

>>>>> XML API tested SUCCESSFUL

Testing xml-parse with callback feature
parsed expresson:(NAME "apple"), source:<NAME>apple</NAME>
parsed expresson:(COLOR "red"), source:<COLOR>red</COLOR>
parsed expresson:(PRICE "0.80"), source:<PRICE>0.80</PRICE>
parsed expresson:(NAME "orange"), source:<NAME>orange</NAME>
parsed expresson:(COLOR "orange"), source:<COLOR>orange</COLOR>
parsed expresson:(PRICE "1.00"), source:<PRICE>1.00</PRICE>
parsed expresson:(NAME "banana"), source:<NAME>banana</NAME>
parsed expresson:(COLOR "yellow"), source:<COLOR>yellow</COLOR>
parsed expresson:(PRICE "0.60"), source:<PRICE>0.60</PRICE>


>>>>> XML callback tested SUCCESSFUL

./newlisp qa-specific-tests/qa-json
>>>>> JSON translation tested SUCESSFUL

./newlisp qa-specific-tests/qa-setsig

Testing signals

...sig-1 ..sig-2 ..sig-3 ..sig-4 ..sig-5 ..sig-6 ..sig-7 ..sig-8 ..sig-10 ..sig-11 ..sig-12 ..sig-13 ..sig-14 ..sig-15 ..sig-16 
sent: (1 2 3 4 5 6 7 8 10 11 12 13 14 15 16)
received: (1 2 3 4 5 6 7 8 10 11 12 13 14 15 16)

>>>>> Signal testing SUCCESSFUL

./newlisp qa-specific-tests/qa-net

Testing network API and server mode IPv4
Testing IPv4 networking functions

target URL: http://localhost:10001//opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_newlisp/newlisp/work/newlisp-10.7.5/qa-junk.txt
host: localhost
port: 10001
path: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_newlisp/newlisp/work/newlisp-10.7.5/qa-junk.txt
Starting server on localhost
waiting for server ...
net-connect to wrong port ->OK
get-url ->OK
net-eval normal mode ->OK
net-eval error reporting ->OK
save to URL ->OK
loading target URL: http://localhost:10001//opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_newlisp/newlisp/work/newlisp-10.7.5/qa-junk.txt
load from URL ->OK
100000 bytes transferred for qa-junk.txt
write-file to remote URL ->OK
read-file from remote URL ->OK
delete-file from remote URL ->OK
destroy -> 25370 ->true

duration -> 1169 ms

>>>>> Network eval and network file functions IPv4 SUCCESSFUL

./newlisp qa-specific-tests/qa-cilk

Testing Cilk API
(abort) -> true
(sync)  -> ()
(sync) -> (25401 25400 25399 25398 25397 25396 25395 25394 25393 25392)
N of processes -> 10
waiting  to sync -> true
fibo(5) -> (needs 15 processes) => wait/sync up to 20 secs
wait/sync up to 20 secs
wait/sync up to 20 secs
wait/sync up to 20 secs
wait/sync up to 20 secs
wait/sync up to 20 secs
wait/sync up to 20 secs
8
inlet pid: 25416 p1:400
inlet pid: 25417 p2:500
true

>>>>> The Cilk API tested SUCCESSFUL

./newlisp qa-specific-tests/qa-ref

testing reference passing to/from built-in functions

>>>>> Reference testing SUCCESSFUL
./newlisp qa-specific-tests/qa-message

testing message API
10 child processes transmit 100 random status numbers
>>>>> Time per simple message: 29 micro seconds

10 round trips to 10 child processes
send out and receive it back uppercased with child pid appended
>>>>> Time per round trip : 940 micros seconds

A:25440-> parent-proxy:25419 -> B:25441

parent exiting ...

>>>>> Time per proxy trip: 100 micro seconds

>>>>> Message API tested SUCCESSFUL
./newlisp qa-specific-tests/qa-win-dll

Testing Windows DLL calls
not tested on OSX
./newlisp qa-specific-tests/qa-bigint 10000
>>>>> testing big ints arithmetik ... 
..........
..........
>>>>> abs bigint float gcd length zero? + - * / % ++ -- big ints tested SUCCESSFUL
./newlisp qa-specific-tests/qa-bench

254 non I/O functions performed SUCCESSFUL in 60.483 ms

>>>>> Benchmarking all non I/O primitives ... (may take a while)
>>>>> total time: 7996.899
>>>>> Performance ratio: 3.11 (1.0 on macOS 10.12, MacBook (Retina, 12-inch, Early 2016), newLISP v10.7.3-64-bit)
```
So only semaphores fail (libdispatch broken for `ppc`). Slow, but it is in Rosetta.

**Comment by barracuda156** [comment]
@kencu Could you test this on i386?

**Comment by pmetzger** [comment]
Given that i386 wasn't working before it's certainly no worse having committed. Thanks for the update.

**Pull request merged**
