### PR TITLE
kismet: update to 2022-02-R1

### PR DESCRIPTION
**Pull request by aque**
#### Description

I updated kismet to the latest release. It builds and works on my system running Big Sur, but I would like feedback on a couple of items:

1. Kismet split their configuration into smaller `*.conf` files. [Instructions to users](https://www.kismetwireless.net/docs/readme/config_files/#configuration-override-files---kismet_siteconf) has them create a file (`kismet_site.conf`) to override options in `*.conf`. Because of this, the `*.conf` files supplied with the package are overwritten on upgrades/installs. I mention in the notes that changes to these default `*.conf` files are lost but I wonder if there is a better way to handle this.

2. [Kismet strongly recommends](https://www.kismetwireless.net/docs/readme/suid/) not running it as root. Is this something that should be called out in notes (as I have done)?

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 11.6.7 20G630 x86_64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

Closing old tickets.
Closes: https://trac.macports.org/ticket/41206
Closes: https://trac.macports.org/ticket/52931

### CODE REVIEW

**Comment by mascguy** [comment]
Added @ryandesign and @jmroot as reviewers, as they can provide guidance on your two questions:

> 1. Kismet split their configuration into smaller `*.conf` files. [Instructions to users](https://www.kismetwireless.net/docs/readme/config_files/#configuration-override-files---kismet_siteconf) has them create a file (`kismet_site.conf`) to override options in `*.conf`. Because of this, the `*.conf` files supplied with the package are overwritten on upgrades/installs. I mention in the notes that changes to these default `*.conf` files are lost but I wonder if there is a better way to handle this.
>
> 2. [Kismet strongly recommends](https://www.kismetwireless.net/docs/readme/suid/) not running it as root. Is this something that should be called out in notes (as I have done)?

**Comment by pmetzger** [comment]
We should find a way to get this resolved.

**Comment by mascguy** [comment]
> Added @ryandesign and @jmroot as reviewers, as they can provide guidance on your two questions:
> 
> > 1. Kismet split their configuration into smaller `*.conf` files. [Instructions to users](https://www.kismetwireless.net/docs/readme/config_files/#configuration-override-files---kismet_siteconf) has them create a file (`kismet_site.conf`) to override options in `*.conf`. Because of this, the `*.conf` files supplied with the package are overwritten on upgrades/installs. I mention in the notes that changes to these default `*.conf` files are lost but I wonder if there is a better way to handle this.
> > 2. [Kismet strongly recommends](https://www.kismetwireless.net/docs/readme/suid/) not running it as root. Is this something that should be called out in notes (as I have done)?

@pmetzger I have no concerns with merging as-is. However, given Allan's questions regarding config files and such, I thought it might be good to have @ryandesign and/or @jmroot provide guidance.

**Comment by mascguy** [comment]
> I have no particular concerns.

Okay, let's merge then. We can always refine it via a later PR, if needed, based on feedback from @ryandesign and @jmroot.

And thanks for your contribution Allan!

**Review by mascguy — APPROVED** [review]

**Pull request merged**
