### PR TITLE
liblogmich: new port submission

### PR DESCRIPTION
**Pull request by ken-cunningham-webuse**
a simple C++ logging library
ultimately, it turned out to be far simpler and better to just write up a new Cmake build file

### CODE REVIEW

**Comment by larryv** [comment]
It doesn't seem wise to roll our own build for someone else's software.

**Comment by ken-cunningham-webuse** [comment]
I heartily agree. But I have to say scons is truly a bear to customize the build environment, and the supplied build file was - well, take a peek - very specific to gcc and quite incomplete for a package management system. No install routine, no install-name, etc. The cmake version took only a couple of minutes to write (two source files and two headers), and is sufficiently complete for our purposes, I think. Fixing the scons build file just seemed like a whole whole lot more work. In fact, if he's interested, I'll probably donate the cmake file to the project and see if he would like to use that going forward...

**Comment by mojca** [comment]
Just curious, why was this pull request closed?

@larryv: I disagree. This wouldn't be the first port to do so and it is definitely much much much better than doing
```
system -W ${worksrcpath} "${configure.compiler} ${configure.cxxflags} ..."
```
inside the Portfile.

Sure, it might be wise to submit the patch for the build upstream, but note that the software doesn't provide any build support at all. (It could be that the author envisioned copying the whole thing inside another project rathe than shipping it as a library, but I don't know.)

**Comment by ken-cunningham-webuse** [comment]
Hi mojca, - ultimately I came to believe there was no chance this port was going to get merged in as is. I'll submit the cmake build file upstream and see if the authour likes it. Best - Ken

**Comment by larryv** [comment]
@mojca
My inclination would be to use the scons build stuff that already exists. Otherwise, a normal makefile would be preferable to adding a dependency on `cmake`.

**Comment by mojca** [comment]
I'm sorry, I didn't spot the scons build file as I have never seen it before and still don't know how to use it. But yes, I agree that if someone knows how to use scons, that one could be used instead of cmake.

OK, cmake adds an additional dependency indeed, but I can hardly imagine anyone doing source builds to survive without having `cmake` already installed (and it's not calling for qmake and putting in a dependency on Qt5 or the latest clang, any of which would require forever to build). And for people getting a "binary" package this won't be an additional dependency at all. (Probably not in this case, but using autotools could just as well add an additional dependency on pkg-config, automake, autoconf, ...) While I agree that a Makefile might be simpler in principle, it requires additional work now that an alternative has already been written, I would bet that a Makefile has approximately zero chances to be accepted upstream, and I also see no reason to ask the contributor to put so much more extra effort into this (in particular not asking him to learn autotools). If using autotools, we would either be adding dependencies on automake and autoconf or adding a monstrous generated configure file that would be much worse at the end.

Let's not make contributors' life more difficult.

@kencu:
> ultimately I came to believe there was no chance this port was going to get merged in as is

If you would like to see this port added to MacPorts, feel free to re-open the ticket. Even if some modifications would be required, the patch can always be improved. There's no reason to close the ticket yourself. It's usually up to "nasty developers" that close tickets with `wontfix` :).

The lack of timely feedback is mostly due to lack of manpower. But we have 4k open tickets anyway, one more won't make a noticeable difference :)

**Comment by kencu** [comment]
The scons build file here is pretty elementary. It would need extensive rewriting to be functional on a package mgmt system. And then you would still wind up with the dependency on scons, which I'd argue is all but useless as it is used so little. And scons is - well - a dinosaur not worth spending the time to learn, IMHO.

Makefiles are not easy to write comprehensively from scratch -- even the one Ryan wrote up for libpointing doesn't work correctly on my system. But not doubt somebody could do it. I work on furthering my skills on these sometimes (like yesterday, writing a build file for a c++ port that builds on Leopard/PPC with clang and libc++ and that needed very custom build instructions).

Cmake is pretty easy to write, and easy to use. I believe I'll use that for all my new projects. Most developers seem to be going towards it for their newer projects too. And I know how to use it already. Pingus (where this port came from) also wrote up their own cmake build for it.

But this port is unimportant to me now. Pingus is in, with this integrated. If the cmake build is not wanted, somebody else can mess around with scons or write a makefile for it.

**Pull request closed without merging**
