### PR TITLE
textproc/qpdf: update to 11.0.0

### PR DESCRIPTION
**Pull request by adfernandes**
* update to 11.0.0
* use the new crypto provider settings
* unfortunately now conflicts_build with itself

Signed-off-by: Andrew Fernandes <andrew@fernandes.org>

### CODE REVIEW

**Comment by Schamschula** [comment]
I already have updated this Portfile myself (minus the workaround for the old headers). However, there is a reason I haven't pushed it:

The update breaks py-pikepdf. See: https://github.com/pikepdf/pikepdf/issues/389

I'm waiting for py-pikepdf to catch up before committing qpdf 11.0.0.

**Comment by adfernandes** [comment]
> I already have updated this Portfile myself

_Grrrr_ ... I *really* must be losing my mind... I swear I searched for PRs before doing this!

Anyway, **thank you**!

_BTW, a (minor) thing that's worth  noting on the `Portfile` is the face that multiple (pluggable) crypto providers are now supported._

**Comment by Schamschula** [comment]
The whole `platform darwin 8 `block can go. No more `qmake`!

**Comment by Schamschula** [comment]
I'm including parts of this PR in my update.

**Pull request closed without merging**
