### PR TITLE
glslang: use compiler.cxx_standard 2011

### PR DESCRIPTION
**Pull request by chrstphrchvz**
…instead of deprecated cxx11 1.1 portgroup

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
The GitHub handle in the portfile (`@eintw1ck`) is invalid.

Cc @jdek who submitted and has been maintaining this port.

**Comment by chrstphrchvz** [comment]
Maintainer handle updated in 81f58b7285d. @jdek, please confirm if you are still interested in maintaining this port, and if so whether the information in the portfile is now correct.

**Comment by jdek** [comment]
@chrstphrchvz I'm no longer using Macports (or even macOS) at all, so I'm not able to easily continue to maintain these ports. Feel free to take over maintainership or just remove me entirely if you'd prefer. Openmaintainer should be enough since they shouldn't really need much work, the Vulkan ports are still waiting on custom macOS SDK support in macports which I don't think has been implemented yet (the relevant ticket should still be open).

**Comment by kencu** [comment]
@chrstphrchvz - want to switch these to nomaintainer while you've got the PR and branch open?

**Comment by chrstphrchvz** [comment]
@jdek Thanks for the quick response and for your past contributions. These ports will be set to nomaintainer:

```
glslang
spirv-tools
vulkan-headers
vulkan-loader
vulkan-tools
vulkan-validationlayers
```

When merging, https://trac.macports.org/ticket/60554 can be unassigned.

**Pull request merged**
