### PR TITLE
R: support more plug-ins for Rcmdr

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Another attempt, see if CI again freeze for no reason.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Given there is nothing here to build, I guess it is stuck again doing nothing.

**Comment by barracuda156** [comment]
@herbygillot Could you do me a favor and verify this locally? (No urgency here.)
I do not know why, but the same story with freezing and then failing after 6+ hours on time-out CI repeats. For some reason, CI do not like `tcltk`-depending packages.
There are just 18 ports here, and all are `noarch`.  Should install in a minute.

**Comment by herbygillot** [comment]
> @herbygillot Could you do me a favor and verify this locally? (No urgency here.) I do not know why, but the same story with freezing and then failing after 6+ hours on time-out CI repeats. For some reason, CI do not like `tcltk`-depending packages. There are just 18 ports here, and all are `noarch`. Should install in a minute.

Unfortunately I'm unable to build on my arm64 machine running macOS Monterey (macOS 12).  `gcc12` won't build:

```
Error: gcc12 cannot be built with Xcode/CLT 14.0.x
Error: Either upgrade both Xcode and the Command Line Tools to 14.1 or later, or downgrade to 13.4.
Error: Failed to fetch gcc12-libcxx: incompatible Xcode/CLT version
```

I may be able to try on a different machine, but that's not something I'll be able to do very soon.

**Comment by barracuda156** [comment]
Oh wow, gcc12 is broken. Never mind, I will think about some solution. This PR is not something of a crucial importance.

**Comment by barracuda156** [comment]
@herbygillot Well, I suggest just skip CI here.

P. S. We have merged earlier all needed ports for this, so only `Rcmdr` plug-ins are left here. Everything is `noarch`. And we already have a few similar plug-ins: https://ports.macports.org/port/R-RcmdrPlugin.HH

**Pull request merged**
