### PR TITLE
npth: update to 1.3

### PR DESCRIPTION
**Pull request by l2dy**

### CODE REVIEW

**Comment by g5pw** [comment]
@l2dy same here. Mind adopting this one too? 😄

**Comment by l2dy** [comment]
I'm not familiar with this port so couldn't take this one. Sorry about that.

**Comment by g5pw** [comment]
No problem. This looks  good to me, a minor nitpick would be omitting the `index.html` from homepage for brevity's sake 😄

**Comment by l2dy** [comment]
Fixed. The link with index.html came from https://gnupg.org/related_software/libraries.html.

**Comment by g5pw** [comment]
Thanks for indulging me 😆  Merging!

**Pull request merged**
