### PR TITLE
mediawiki: delete neglected port

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Upstream continues to publish new releases frequently; version in port is from 2014 and has known security issues. Port has not been installable due to deleted dependencies.

Closes: https://trac.macports.org/ticket/45147
See: https://trac.macports.org/ticket/53522

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

### CODE REVIEW

**Comment by dbevans** [comment]
If mediawiki is active upstream maybe it should be updated rather than deleted.  What would it take to do this?

**Comment by kencu** [comment]
current deps:
```
Required software as of MediaWiki 1.34.0:

* Web server with PHP 7.2.9 or higher, plus the following extensions:
** ctype
** dom
** fileinfo
** iconv
** json
** mbstring
** xml
* A SQL server, the following types are supported
** MySQL 5.5.8 or higher
** PostgreSQL 9.2 or higher
** SQLite 3.8.0 or higher
```

**Comment by chrstphrchvz** [comment]
No one has reported any issues against this port [since 2016](https://trac.macports.org/ticket/51813), and no one requested it be updated since when it was last updated in 2014. I don't think anyone wants this port badly enough, and I would rather it be removed than rescued in order for it to end up unused and neglected all over again. I would think there are other ports people want to use that need attention, and where effort would be better spent.

**Comment by dbevans** [comment]
> No one has reported any issues against this port [since 2016](https://trac.macports.org/ticket/51813), and no one requested it be updated since when it was last updated in 2014. I don't think anyone wants this port badly enough, and I would rather it be removed than rescued in order for it to end up unused and neglected all over again. I would think there are other ports people want to use that need attention, and where effort would be better spent.

Using this philosophy, one might remove all nomaintainer ports.  But seriously, there are many ports currently existing that don't work or don't build and are not supported upstream or even don't have a working homepage any more and they're still with us. I'd propose removing some of them before removing a port that is well maintained upstream.  I agree that with a limited supply of maintainer hours available it might make sense to winnow out some of the chaff but prioritizing such ports, say, by their ugliness would be a time saver as well.

@ryandesign, do you have a thought to share on this subject since you maintain a lot of PHP ports and are, I perceive, often reticent to remove ports for  the sake of doing so?  At any rate, I'm fine with any criteria others think is reasonable.

**Comment by kencu** [comment]
I am also not a big fan of aggressive culling of ports for no good reason. 

I feel there are many many cases where these older ports are useful to people. Just because upstream is dormant is no reason to kill them off. 

For ports that have been all worked out but haven't been updated in a while, just leave them, and people can much more easily tweak an existing port than start from scratch.

Now if a port is totally broken, unfixable, and upstream is dead -- no arguments there I guess. It's dead.

**Comment by ryandesign** [comment]
mediawiki hasn't been installable for ages due to depending on php5-web which cannot be installed; see https://trac.macports.org/ticket/61016.

I had hoped someone might develop a good strategy for how to offer web apps in MacPorts, that mediawiki and other web app ports could adopt, but it hasn't happened.

**Comment by chrstphrchvz** [comment]
I still think this port should be removed, but since leaving PRs open is a problem, I give up on being part of that effort.

**Pull request closed without merging**
