### PR TITLE
clang-11-bootstrap: prefer configure.build_arch over build_arch, use universal_possible

### PR DESCRIPTION
**Pull request by catap**
#### Description

Closes: https://trac.macports.org/ticket/68789

###### Type(s)

- [x] bugfix

###### Tested on

macOS 13.6.1 22G313 arm64
Xcode 15.0.1 15A507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by kencu** [comment]
building now on 10.7

**Comment by kencu** [comment]
looks like that fixed almost all the archive libraries and dylibs, yes. Just these are single arch:
```
$pwd
/opt/local/libexec/clang-11-bootstrap/lib/clang/11.1.0/lib/darwin

$ file *.a
libclang_rt.fuzzer_no_main_osx.a: current ar archive random library
libclang_rt.fuzzer_osx.a:         current ar archive random library
```
but this one, the one we needed, is universal:
```
libclang_rt.osx.a:                Mach-O universal binary with 2 architectures
libclang_rt.osx.a (for architecture i386):	current ar archive random library
libclang_rt.osx.a (for architecture x86_64):	current ar archive random library
```

I don't know -- maybe the fuzzers can't be built universal. 


I was hoping to use this new, fixed clang-11-bootstrap to build openssl3, but sadly  it doesn't work for some reason:
```
/opt/local/libexec/clang-11-bootstrap/bin/clang  -Iapps -I. -Iinclude -Iapps/include  -arch i386 -pipe -Os -arch i386 -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -I/opt/local/include -MMD -MF apps/openssl-bin-x509.d.tmp -MT apps/openssl-bin-x509.o -c -o apps/openssl-bin-x509.o apps/x509.c
rm -f fuzz/cmp-test
${LDCMD:-/opt/local/libexec/clang-11-bootstrap/bin/clang} -arch i386 -pipe -Os -arch i386 -Wl,-search_paths_first -L/opt/local/lib -Wl,-headerpad_max_install_names -arch i386 -L/opt/local/lib \
		-o fuzz/cmp-test \
		fuzz/cmp-test-bin-cmp.o fuzz/cmp-test-bin-fuzz_rand.o fuzz/cmp-test-bin-test-corpus.o \
		libcrypto.a -lz 
rm -f fuzz/pem-test
${LDCMD:-/opt/local/libexec/clang-11-bootstrap/bin/clang} -arch i386 -pipe -Os -arch i386 -Wl,-search_paths_first -L/opt/local/lib -Wl,-headerpad_max_install_names -arch i386 -L/opt/local/lib \
		-o fuzz/pem-test \
		fuzz/pem-test-bin-pem.o fuzz/pem-test-bin-test-corpus.o \
		libcrypto.a -lz 
rm -f fuzz/punycode-test
${LDCMD:-/opt/local/libexec/clang-11-bootstrap/bin/clang} -arch i386 -pipe -Os -arch i386 -Wl,-search_paths_first -L/opt/local/lib -Wl,-headerpad_max_install_names -arch i386 -L/opt/local/lib \
		-o fuzz/punycode-test \
		fuzz/punycode-test-bin-punycode.o fuzz/punycode-test-bin-test-corpus.o \
		libcrypto.a -lz 
rm -f fuzz/quic-client-test
${LDCMD:-/opt/local/libexec/clang-11-bootstrap/bin/clang} -arch i386 -pipe -Os -arch i386 -Wl,-search_paths_first -L/opt/local/lib -Wl,-headerpad_max_install_names -arch i386 -L/opt/local/lib \
		-o fuzz/quic-client-test \
		fuzz/quic-client-test-bin-fuzz_rand.o fuzz/quic-client-test-bin-quic-client.o \
		fuzz/quic-client-test-bin-test-corpus.o \
		libssl.a libcrypto.a -lz 
Undefined symbols for architecture i386:
  "___atomic_is_lock_free", referenced from:
      _CRYPTO_atomic_or in libcrypto.a(libcrypto-lib-threads_pthread.o)
      _CRYPTO_atomic_load in libcrypto.a(libcrypto-lib-threads_pthread.o)
Undefined symbols for architecture i386:
  "___atomic_is_lock_free", referenced from:
      _CRYPTO_atomic_or in libcrypto.a(libcrypto-lib-threads_pthread.o)
      _CRYPTO_atomic_load in libcrypto.a(libcrypto-lib-threads_pthread.o)
  "___atomic_load", referenced from:
      _CRYPTO_atomic_load in libcrypto.a(libcrypto-lib-threads_pthread.o)
     (maybe you meant: ___atomic_load_8, ___atomic_load_1 , ___atomic_load_2   "___atomic_load", referenced from:
      _CRYPTO_atomic_load in libcrypto.a(libcrypto-lib-threads_pthread.o)
, ___atomic_load_4 , ___atomic_load_c )
     (maybe you meant: ___atomic_load_8, ___atomic_load_2 , ___atomic_load_1 , ___atomic_load_c , ___atomic_load_4 )
ld: symbol(s) not found for architecture i386
ld: symbol(s) not found for architecture i386
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [fuzz/pem-test] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [fuzz/cmp-test] Error 1
Undefined symbols for architecture i386:
  "___atomic_is_lock_free", referenced from:
      _CRYPTO_atomic_or in libcrypto.a(libcrypto-lib-threads_pthread.o)
      _CRYPTO_atomic_load in libcrypto.a(libcrypto-lib-threads_pthread.o)
  "___atomic_load", referenced from:
      _CRYPTO_atomic_load in libcrypto.a(libcrypto-lib-threads_pthread.o)
     (maybe you meant: ___atomic_load_8, ___atomic_load_4 , ___atomic_load_1 , ___atomic_load_c , ___atomic_load_2 )
ld: symbol(s) not found for architecture i386
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [fuzz/punycode-test] Error 1
Undefined symbols for architecture i386:
  "___atomic_is_lock_free", referenced from:
      _CRYPTO_atomic_or in libcrypto.a(libcrypto-lib-threads_pthread.o)
      _CRYPTO_atomic_load in libcrypto.a(libcrypto-lib-threads_pthread.o)
  "___atomic_load", referenced from:
      _CRYPTO_atomic_load in libcrypto.a(libcrypto-lib-threads_pthread.o)
     (maybe you meant: ___atomic_load_8, ___atomic_load_2 , ___atomic_load_1 , ___atomic_load_c , ___atomic_load_4 )
ld: symbol(s) not found for architecture i386
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [fuzz/quic-client-test] Error 1
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_openssl3/openssl3/work/openssl-3.2.0-i386'
make: *** [build_sw] Error 2
make: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_openssl3/openssl3/work/openssl-3.2.0-i386'
Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_openssl3/openssl3/work/openssl-3.2.0-i386" && /usr/bin/make -j4 -w all 
Exit code: 2
Error: Failed to build openssl3: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_openssl3/openssl3/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port openssl3 failed
```

whereas building openssl3 with macports-clang-16 as +universal worked just fine.

So somewhere there is an issue happening. There are some atomic symbols not being found in arch i386 using this compiler:

```
$ nm -arch i386 libclang_rt.osx.a | grep atomic
libclang_rt.osx.a(atomic.c.o):
00000510 T ___atomic_compare_exchange_1
00000530 T ___atomic_compare_exchange_2
00000560 T ___atomic_compare_exchange_4
00000580 T ___atomic_compare_exchange_8
00000190 T ___atomic_compare_exchange_c
000004b0 T ___atomic_exchange_1
000004c0 T ___atomic_exchange_2
000004d0 T ___atomic_exchange_4
000004e0 T ___atomic_exchange_8
00000300 T ___atomic_exchange_c
000005c0 T ___atomic_fetch_add_1
000005d0 T ___atomic_fetch_add_2
000005e0 T ___atomic_fetch_add_4
000005f0 T ___atomic_fetch_add_8
00000710 T ___atomic_fetch_and_1
00000740 T ___atomic_fetch_and_2
00000760 T ___atomic_fetch_and_4
00000780 T ___atomic_fetch_and_8
000007f0 T ___atomic_fetch_or_1
00000820 T ___atomic_fetch_or_2
00000840 T ___atomic_fetch_or_4
00000860 T ___atomic_fetch_or_8
00000660 T ___atomic_fetch_sub_1
00000670 T ___atomic_fetch_sub_2
00000690 T ___atomic_fetch_sub_4
000006a0 T ___atomic_fetch_sub_8
000008d0 T ___atomic_fetch_xor_1
00000900 T ___atomic_fetch_xor_2
00000920 T ___atomic_fetch_xor_4
00000940 T ___atomic_fetch_xor_8
00000400 T ___atomic_load_1
00000410 T ___atomic_load_2
00000420 T ___atomic_load_4
00000430 T ___atomic_load_8
00000000 T ___atomic_load_c
00000450 T ___atomic_store_1
00000460 T ___atomic_store_2
00000470 T ___atomic_store_4
00000480 T ___atomic_store_8
000000d0 T ___atomic_store_c
libclang_rt.osx.a(atomic_flag_clear.c.o):
00000000 T _atomic_flag_clear
libclang_rt.osx.a(atomic_flag_clear_explicit.c.o):
00000000 T _atomic_flag_clear_explicit
libclang_rt.osx.a(atomic_flag_test_and_set.c.o):
00000000 T _atomic_flag_test_and_set
libclang_rt.osx.a(atomic_flag_test_and_set_explicit.c.o):
00000000 T _atomic_flag_test_and_set_explicit
libclang_rt.osx.a(atomic_signal_fence.c.o):
00000000 T _atomic_signal_fence
libclang_rt.osx.a(atomic_thread_fence.c.o):
00000000 T _atomic_thread_fence
```

**Comment by catap** [comment]
Ken, two stage build should fix this issue, if I skip all details.

It is a bit tricky and I'm working on it for a while, so I see that as opportunity to finish it ASAP.

Let keep it as draft for a week or so.

**Comment by catap** [comment]
Something very strange happening here.

1. `nm /opt/local/libexec/llvm-11/lib/clang/11.1.0/lib/darwin/libclang_rt.osx.a | grep atomic_is_lock_free` returns nothing on my test machine.
2. https://github.com/openssl/openssl/blob/openssl-3.2.0/crypto/threads_pthread.c#L223-L247 `__atomic_is_lock_free` is used inside `CRYPTO_atomic_or` only when `# if defined(__GNUC__) && defined(__ATOMIC_ACQ_REL) && !defined(BROKEN_CLANG_ATOMICS)` holds. It shouldn't be true for clang build.

**Comment by catap** [comment]
BTW may I ask you to share your diff for portfile to build it universal? I'd like to try on my clean machine from scratch.

**Comment by catap** [comment]
After spending couple of hours on two stage build I not sure that it is good move at all.

Ken, may you share a port file which I can use to reproduce your issue?

**Comment by catap** [comment]
How do you enable (5)? Like this?
```tcl
    configure.compiler.add_deps no
    depends_build-append port:clang-11-bootstrap
    depends_skip_archcheck-append clang-11-bootstrap
    pre-configure {
        configure.cc    ${prefix}/libexec/clang-11-bootstrap/bin/clang
        configure.cxx   ${prefix}/libexec/clang-11-bootstrap/bin/clang++
    }
```

**Comment by kencu** [comment]
yeah, like that

**Comment by catap** [comment]
I haven’t pushed anything to this branch.

I’ve tried 2-stage build locally and dismissed that.

so, nothing had here.

**Comment by kencu** [comment]
however openssl3 turns out, this seems an improvement, to get a universal clang runtime. Thanks for your attention.

**Pull request merged**
