### PR TITLE
gnuradio: move 'graphviz' to a build dependency & rev-bump

### PR DESCRIPTION
**Pull request by michaelld**
Small tweak as discussed here: https://github.com/macports/macports-ports/pull/6880#issuecomment-662045139 ... hopefully this clears up the licensing issue with GraphViz ...

### CODE REVIEW

**Comment by ryandesign** [comment]
Usually doxygen is a build dependency too. Usually it's doxygen that brings in the graphviz dependency.

**Comment by ra1nb0w** [comment]
doxygen doesn't import graphviz.
Moving everything to build (should be correct)
```
 variant docs description "Install GNU Radio documentation" {

-    depends_lib-append \
+    depends_build-append \
         port:doxygen \
         path:bin/dot:graphviz \
-        port:xmlto
-
-    depends_build-append \
+        port:xmlto \
         port:py${active_python_version_no_dot}-sphinx \
         port:texlive-latex
```
seems doesn't change the situation:
`"gnuradio" is not distributable because its license "gpl" conflicts with license "EPL-1" of dependency "graphviz"`
and this is strange since it is only a build dependency. Anyway, disabling `-doc` still remain OpenSSL issue but this is a dependency of cmake and should not matter. Probably I lost some point :)

Just a TIP: script to check the build license issue: `macports-infrastructure/jobs/port_binary_distributable.tcl`

**Comment by ryandesign** [comment]
> doxygen doesn't import graphviz.

What do you mean? If you mean that doxygen doesn't declare a dependency on graphviz, that's correct. But I'm saying that there is often a pairing of doxygen and graphviz build dependencies in ports, because doxygen can optionally use graphviz to render graphs in documentation, and ports whose documentation files do that then have both dependencies.

> Moving everything to build [...] seems doesn't change the situation:
> `"gnuradio" is not distributable because its license "gpl" conflicts with license "EPL-1" of dependency "graphviz"`
> and this is strange since it is only a build dependency.

Not strange. The license checker has no way of knowing whether gnuradio (GPL licensed) might be using parts of graphviz (EPL licensed) that would cause a combined work to be created. If that situation occurs, [the result is not legally distributable](https://en.wikipedia.org/wiki/Eclipse_Public_License#Compatibility) so the script errs on the side of caution and assumes that that has occurred. If you know that that situation does not occur, you can declare that there is no license conflict with graphviz in the gnuradio port.

**Comment by ra1nb0w** [comment]
> If you mean that doxygen doesn't declare a dependency on graphviz, that's correct. 

yes, I mean this.

> If you know that that situation does not occur, you can declare that there is no license conflict with graphviz in the gnuradio port.

ok. seems not the case but @michaelld knows better the point. Seems the same thing for OpenSSL, right?

**Comment by michaelld** [comment]
I checked all of the DYLIB / SO created by GR and none of them link to doxygen / graphviz libraries (nor openSSL). They just use the executables and data to create documentation. Hence, no conflict IMHO.

How do I declare no license conflict? I've never done that before & don't even know where to start looking for the info on how to do it ... thx!

> > If you mean that doxygen doesn't declare a dependency on graphviz, that's correct.
> 
> yes, I mean this.
> 
> > If you know that that situation does not occur, you can declare that there is no license conflict with graphviz in the gnuradio port.
> 
> ok. seems not the case but @michaelld knows better the point. Seems the same thing for OpenSSL, right?

**Comment by michaelld** [comment]
I do agree that doxygen should be a build dependency, not a general lib one. I'll move that and tweak the license in the next go-around.

**Comment by ra1nb0w** [comment]
Probably this is also valid for uhd and maybe other gr-*

**Comment by michaelld** [comment]
> Probably this is also valid for uhd and maybe other gr-*

yup!

**Comment by ryandesign** [comment]
> I checked all of the DYLIB / SO created by GR and none of them link to doxygen / graphviz libraries (nor openSSL). They just use the executables and data to create documentation. Hence, no conflict IMHO.

That is not a guarantee of no conflict. What about all of the libraries that gnuradio links with? Do any of them link with openssl or graphviz libraries? What about any of the libraries those libraries link with? And so on.

Also, linking with libraries is not the only way that a combined work could be created.

> How do I declare no license conflict? I've never done that before & don't even know where to start looking for the info on how to do it ... thx!

***IF*** you are sure there is no license conflict, then you would use e.g.

```
license_noconflict  graphviz
```

**Comment by michaelld** [comment]
> > I checked all of the DYLIB / SO created by GR and none of them link to doxygen / graphviz libraries (nor openSSL). They just use the executables and data to create documentation. Hence, no conflict IMHO.
> 
> That is not a guarantee of no conflict. What about all of the libraries that gnuradio links with? Do any of them link with openssl or graphviz libraries? What about any of the libraries those libraries link with? And so on.

Hmm ... this would be the case if someone wanted to distribute a stand-alone application, for example "GNURadio.app", which included all libraries and data including for all dependencies.

It's not clear to me that that's the intent of the MP license attribute in the Portfile. If I had to guess, it's meant for pre-compiled binary distribution to end-users of just the port itself, with each dependency treated separately. Thus, if there are license conflicts then the end-user has to build from source (e.g., "ffmpeg +nonfree"). If no conflicts, then a pre-compiled binary can be created and distributed. Please correct me if I'm wrong here.

> Also, linking with libraries is not the only way that a combined work could be created.

True. A "derivative work" may be made through linking libraries, using just headers, and/or using a specifically-licensed application to process information. For GR, this last one is the question for graphviz ... specifically: (1) is any part of "graphviz" actually used by any version of GR MP currently supports? and (2) If so, what is the license for the output from using a graphviz executable to process output data (but not link libraries or use headers; the "MP GV Use Case" below)?

(1) I'm testing this right now. I've deactivated graphviz and removed it from the GR Portfile and am building GR37 and GR to see. I'm thinking it was required for some previous GR and no longer is. Just Doxygen. I'll keep at this for a bit.

(2) Here is the graphviz license: https://graphviz.org/license/ -- "Common Public License Version 1.0". This license should cover both the source code as well as "derivative works" such as the MP GV Use Case.

In my reading, the license itself says nothing about licensing requirements for the MP GV Use Case; the license is purely for the source code. I'll admit that IANAL (etc), but to me the language is clear enough.

A quick search of this license (text) as well as the internet (various including "derivative works" of) doesn't help much.  I'll do some more digging into this issue & make a decision.

> > How do I declare no license conflict? I've never done that before & don't even know where to start looking for the info on how to do it ... thx!
> 
> _**IF**_ you are sure there is no license conflict, then you would use e.g.
> 
> ```
> license_noconflict  graphviz
> ```

OK thanks. Hopefully I don't have to use this at all.

**Comment by michaelld** [comment]
I just chatted with the lead GR dev, and he thinks that the graphviz license covers just the source code ... maybe the ABI / API too via "derivative works" ... but not the output data created by any graphviz executable.

His thought here, which I totally agree with, is that since graphviz is used so ubiquitously & for so long, if there -were- an issue with licensing of executable outputs, it would have come up by now -- that our discussion here cannot be the first time this has come up -- and hence it is very likely that there is no conflict between the licenses in this regard.

Hence, there is no license conflict in his opinion. He self-admits that HINAL and stuff, of course. Anyway: graphviz is an -optional- build dependency via Doxygen, via the `dot` utility. It is also as it turns out used in the `ctrlport` Python script `gr-perf-monitorx` for display purposes ... so, I'll add just 'graphviz' to that area too with a note about the dependency.

**Comment by michaelld** [comment]
OK I just pushed the new changes. I think this should fix the license conflict & also make the dependencies more correct overall. I'll let the CI run & then merge if that all comes out OK.

**Comment by ra1nb0w** [comment]
Thank you very much @michaelld for the enlightenment. Still remain the openssl issue: the dependency tree is cmake -> curl -> libpsl-> python38 and I think that since we can also use python38 it blocks. How can manage this?
Then gnuradio it is binary distributable and probably many others gr-* and uhd with the same fix.

**Comment by michaelld** [comment]
> Thank you very much @michaelld for the enlightenment. Still remain the openssl issue: the dependency tree is cmake -> curl -> libpsl-> python38 and I think that since we can also use python38 it blocks. How can manage this?
> Then gnuradio it is binary distributable and probably many others gr-* and uhd with the same fix.

Is cmake a build dependency hopefully? GR does not link to or use cmake in a license-conflicting manner.

**Comment by michaelld** [comment]
So if we need to add a nonconflict there that's doable quickly!

**Comment by ra1nb0w** [comment]
> Is cmake a build dependency hopefully? GR does not link to or use cmake in a license-conflicting manner.

In fact, and this is why I have not clear the motivation of the conflict. We need an enlightenment from @ryandesign :)

**Comment by michaelld** [comment]
@ra1nb0w where are we here with noconflict? do I need to add for "cmake" only? or some other port(s)? how do I figure this out on my own?

**Comment by ra1nb0w** [comment]
There is OpenSSL conflict from cmake-->curl-->libpsl-->python38 but I don't know why.

**Comment by michaelld** [comment]
> There is OpenSSL conflict from cmake-->curl-->libpsl-->python38 but I don't know why since it is a build dependency.

OK ... which port do I need to declare no license conflict with here then?

**Comment by ra1nb0w** [comment]
I don't know since I don't understand the "source" of the problem. `libpsl` is already binary distributable and other projects that are using cmake portgroup don't have this problem.

**Comment by michaelld** [comment]
Ok. What command do I use to determine license compatibility? I’ve never done this before ...

**Comment by ra1nb0w** [comment]
> Ok. What command do I use to determine license compatibility? I’ve never done this before ...

[this script](https://github.com/macports/macports-infrastructure/blob/master/jobs/port_binary_distributable.tcl) with `./port_binary_distributable.tcl -v gnuradio`

**Comment by michaelld** [comment]
OK thanks. With some ado, I've fixed the license conflict issue. I'm closing this PR and will just merge in directly.

**Comment by michaelld** [comment]
c9593d4ff3611239b56b29a4972ebfc3e3f014df

**Comment by ra1nb0w** [comment]
thank you! maybe the same thing for uhd and others port?

**Comment by ryandesign** [comment]
> Hmm ... this would be the case if someone wanted to distribute a stand-alone application, for example "GNURadio.app", which included all libraries and data including for all dependencies.
> 
> It's not clear to me that that's the intent of the MP license attribute in the Portfile. If I had to guess, it's meant for pre-compiled binary distribution to end-users of just the port itself, with each dependency treated separately. Thus, if there are license conflicts then the end-user has to build from source (e.g., "ffmpeg +nonfree"). If no conflicts, then a pre-compiled binary can be created and distributed. Please correct me if I'm wrong here.

My understanding is that a license violation occurs if [a program or library *X* that is GPL licensed and does not have an OpenSSL exception in its license] is loaded into memory and an OpenSSL library is loaded into that same process. This might occur if *X* links directly with an OpenSSL library; if another library that *X* links with directly or indirectly links with an OpenSSL library; or if *X* or another library it links with `dlopen`s an OpenSSL library. This is why MacPorts license checking checks not only a port's direct dependencies but all of the dependencies down the chain, stopping only if it encounters ports that declare `installs_libs no`. If a port does not install libraries, it should declare `installs_libs no`. cmake for example does declare that, so the licenses of cmake and its dependencies did not affect the distributability of gnuradio.

**Pull request closed without merging**
