### PR TITLE
libbluray: update to 1.2.0

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
My only comment is that this might require all ports that depend on this port to increase the revision by 1 so that they get rebuilt properly. Have you tested this?

```
$ port echo depends:libbluray
ffmpeg                          
ffmpeg-devel                    
libVLC                          
libVLC2                         
mpv                             
mythtv-core.28                  
VLC                             
VLC2                            
xine-lib           

```

**Comment by i0ntempest** [comment]
mpv (and subsequently ffmpeg) seems to work fine without rebuilding. For other ports how do I test if I'm not already using them?

**Comment by mf2k** [comment]
Well the only way, that I know, is to install them all using the current version of libbluray, then upgrade it and see if any need to be rebuilt.

**Comment by mf2k** [comment]
But it's a good sign if ffmpeg did not need to be rebuilt.

**Comment by ryandesign** [comment]
> My only comment is that this might require all ports that depend on this port to increase the revision by 1 so that they get rebuilt properly.

If the library version changed, then yes. Did it? Let's see...

On my system I see that libbluray 1.1.2 installed /opt/local/lib/libbluray.2.dylib. And looking at the build logs above, I see that libbluray 1.2.0 still installs /opt/local/lib/libbluray.2.dylib. So that indicates upstream thinks it's a drop-in replacement for the older version and would not require other ports to be rebuilt. (They could always have made a mistake in their library versioning or inadvertently made a backwards-incompatible change, but let's not start from that assumption.)

**Comment by mf2k** [comment]
@ryandesign : Thank you for clarifying!

**Pull request merged**
