### PR TITLE
lang/sbcl/2.4.4

### PR DESCRIPTION
**Pull request by easye**
works for me

### CODE REVIEW

**Review by catap — APPROVED** [review]

**Comment by barracuda156** [comment]
@catap We have broken it for ppc :)

**Comment by catap** [comment]
I assume that upstream did it!

**Comment by catap** [comment]
can you try to bootstrap it with clisp? It will be long. Extreamly long. But probably works.

**Comment by barracuda156** [comment]
> can you try to bootstrap it with clisp? It will be long. Extreamly long. But probably works.

Maybe a two-stage with SBCL will be better? We would generally prefer to avoid anything extremely long on ppc, else someone with G4 may get upset.

**Pull request merged**
