### PR TITLE
update py-prompt_toolkit and dependents

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
As discussed in [Trac ticket 57933](https://trac.macports.org/ticket/57933) there are some upgrade-issue related to ```py-prompt_toolkit``` and its non-compatible v1.x and v2.x branches. The version 2.x branch was released in June 2018 and at some point we'll have to deal with this... This PR attempts to resolve the issues as follows (I have tried to take the comments in above-mentioned ticked into account).

- ```py-prompt_toolkit```: update to 2.09, and pin to 1.0.15 for PY27 and PY34; this is mainly dictated by ```py-ipython``` its dependency requirements, but in my opinion also works well for other ports.

Ports that depend on ```py-prompt_toolkit``` and their changes:
- ```mycli```: update to 1.19.0 (requires v2), pin to 1.18.0 for py27/py34 (latest version that requires v1)
@xeron: it might be worth considering to update to ```default_variants +python37```?
- ```pgcli```: update to 2.02 (requires v2), pin to 1.11.0 for py27/py34 (latest version that requires v1)
@g5pw @xeron: it might be worth considering to update to ```default_variants +python37```?
- ```xonsh```: nothing to do, does not specify version caps on py-prompt_toolkit and the tests (on the projects GitHub page) pass with newer versions
@Schamschula: the port builds fine, but I haven't tested anything else - could you check?
- ```topydo```: nothing to do, requires >= 0.53, builds fine with the latest and tests pass on the projects GitHub page
- ```http-prompt```: added patches to work with py-prompt_toolkit v2 (see PR on projects GitHub page). The patches were submitted by the author of py-prompt_toolkit to help in the transition to v2. 
The packages builds fine and only one tests fails, I don't know if that's important (the test-suite doesn't pass with the previous py-prompt_toolkit either).
@lbschenkel @g5pw: can you please take a look?
- ```py-ipython```: update to 7.3.0 (requires v2), pin to earlier versions for py27/py34 (require v1)
- ```py-jupyter_console```: update to 6.0.0 (requires v2), pin to 5.2.0 for py27/py34 (requires v1)

###### Tested on

macOS 10.14.3 18D109
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`? Yes, where available
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by xeron** [comment]
@reneeotten I'm OK with using `+python37` as default variant for `pgcli`/`mycli`.

**Comment by lbschenkel** [comment]
I'm OK with the changes to `http-prompt`. Thanks.

**Comment by reneeotten** [comment]
thanks for the comments so far. I will update the ```default_variant``` to ```python37``` for ```mycli``` / ```pgcli``` and look into the failures for ```py-ipython```/```py-jupyter_console```.

**Comment by g5pw** [comment]
Might as well bump `httpie` and `http-prompt` to python37 if @lbschenkel agrees.

**Comment by reneeotten** [comment]
> Might as well bump `httpie` and `http-prompt` to python37 if @lbschenkel agrees.

sure, feel free to do so after this PR as this is outside of its scope. You might want to update ```httpie``` to its newest version at the same time:
```
port -v livecheck httpie
httpie seems to have been updated (port version: 0.9.9, new version: 1.0.2)
```

**Comment by lbschenkel** [comment]
> > Might as well bump `httpie` and `http-prompt` to python37 if @lbschenkel agrees.
> 
> sure, feel free to do so after this PR as this is outside of its scope. You might want to update `httpie` to its newest version at the same time:
> 
> ```
> port -v livecheck httpie
> httpie seems to have been updated (port version: 0.9.9, new version: 1.0.2)
> ```
I would gladly update `http-prompt` but I agree that there's no need to include it in this PR, it can wait. But since `http-prompt` is just a wrapper over `httpie`, the latter is the one really defining the Python version. If it depended on me both would always use the latest stable Python.

**Comment by reneeotten** [comment]
I take from PR3851 from @stromnov that builds on (and requires) this PR that he agrees with the changes proposed here. So what do we do from here - wait a few more days for possible comments or go ahead and merge? After that PR3851 might needs some updates/fixes, but then we'll have at least recent versions again of py-ipython and friends.

**Comment by reneeotten** [comment]
so, it seems that everyone involved agrees that this can be merged? If so, can someone with sufficient permissions take care of this or do we need to discuss (or wait on) anything else? Thanks!

**Comment by g5pw** [comment]
Merging. Thanks for your contribution to Macports!

**Pull request merged**
