### PR TITLE
gobject-introspection-devel: update to 1.70.0

### PR DESCRIPTION
**Pull request by evanmiller**
#### Description

Update gobject-introspection-devel to latest stable. This port is a perennial source of bugs so let's test it thoroughly before merging.

See: https://trac.macports.org/ticket/43079
See: https://trac.macports.org/ticket/45448
See: https://trac.macports.org/ticket/53699
See: https://trac.macports.org/ticket/59940
See: https://trac.macports.org/ticket/62863

###### Type(s)
- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.6.8
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Hey Evan, I just created a new Devel port to pre-validate these changes. Go ahead and update your PR to modify that instead.

**Comment by mascguy** [comment]
Updated the commit to change the Devel port instead, to save you time. (It's the least I could do, since you did the hard work!)

Tested locally on 10.13, and looks good.

The only issue I noticed, is that the build fails with trace mode enabled.

**Comment by mascguy** [comment]
Let me know when you're done with your commits, as there's one minor update I'd like to make as well.

**Comment by evanmiller** [comment]
@mascguy I'm done, for now!

**Comment by mascguy** [comment]
Just pushed a minor change: Added Cython as a build dependency.

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
And thanks so much for this Evan, the update is definitely long-overdue!

**Comment by mascguy** [comment]
FYI, updated all dependents to use a path-style dep for `gobject-introspection`, so that we can easily test with the Devel port. (Along with updating the portgroup.)

**Pull request merged**
