### PR TITLE
doxygen: update to 1.9.8

### PR DESCRIPTION
**Pull request by pguyot**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.0 23A344 x86_64
Xcode 15.0.1 15A507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mascguy** [comment]
@herbygillot Per the comment in portfile, this update should have been pre-validated via `doxygen-devel` first, given that this is a foundational port:

```
# please don't update doxygen without first checking the build status of doxygen-devel
```

**Comment by mascguy** [comment]
> @herbygillot Per the comment in the portfile, this update should have been pre-validated via `doxygen-devel` first, given that this is a foundational port:
> 
> ```
> # please don't update doxygen without first checking the build status of doxygen-devel
> ```

Had that been done, it would be have been clear that the latest releases don't build everywhere:

* [Issue 65314 - doxygen-devel: build fails for 10.7 through 10.12: undefined vtable symbols](https://trac.macports.org/ticket/65314)
* [Issue 68529 - doxygen @1.9.8_0 Fails to Build - Undefined symbols](https://trac.macports.org/ticket/68529)

**Comment by pguyot** [comment]
@mascguy shall we revert and bump the epoch?

**Comment by mascguy** [comment]
> @mascguy shall we revert and bump the epoch?

No we're good: I'm working on a fix for 1.9.8, and will be pushing that shortly.

Thanks for the offer though! And no worries regarding the update, we needed to tackle this all anyway.

**Comment by pguyot** [comment]
@mascguy thank you for sorting this out and sorry for being responsible for it being at the top.

As GitHub CI is limited to macOS 11-13, I didn't realize compatibility with older versions of macOS was a (nice) feature of the project now.

**Comment by mascguy** [comment]
> @mascguy thank you for sorting this out and sorry for being responsible for it being at the top.
> 
> As GitHub CI is limited to macOS 11-13, I didn't realize compatibility with older versions of macOS was a (nice) feature of the project now.

No worries whatsoever, it's easy enough to miss something like this. And thanks as always for your contributions Paul!

**Comment by herbygillot** [comment]
My fault for missing that.

**Comment by mascguy** [comment]
> My fault for missing that.

No worries Herby, easy enough to miss.

And the build failures for 10.7 thru 10.12, have been fixed with commit: https://github.com/macports/macports-ports/commit/610b7cc0e3ff4596287bf8328df9c7bcba47e036

**Pull request merged**
