### PR TITLE
mongodb: update to 3.7.2

### PR DESCRIPTION
**Pull request by emcrisostomo**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix
- [x] update
###### Tested on

macOS 10.13.3 17D102
Xcode 9.2 9C40b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
We will not update the mongodb / mongo-tools ports to development versions, only stable versions. livecheck is already set up to only notify you of stable versions.

**Comment by emcrisostomo** [comment]
Hi @ryandesign, thank you, I didn't realise those were non-production versions. By the way, I decided to update the port _just_ because livecheck told me:

```
mongo-tools seems to have been updated (port version: 3.6.3, new version: 3.7.2)
```

I guess we should fix that, then.

**Comment by ryandesign** [comment]
`github.livecheck.regex` was added to the github portgroup; see https://trac.macports.org/ticket/56065.

**Comment by emcrisostomo** [comment]
Thanks for the notice Ryan

**Pull request closed without merging**
