### PR TITLE
py-pyregion: add Python 3.5 and update to version 1.2

### PR DESCRIPTION
**Pull request by cdeil**
cc port maintainer @astrofrog

### CODE REVIEW

**Comment by mkae** [comment]
@cdeil, on which OSX/macOS systems did you test-run this?

**Comment by cdeil** [comment]
@mkae - I didn't do any testing if this works within Macports.
(If there are instructions how to do it now with git, please share a link to them and I'll try to learn how to do it in the future)

That said - I did the upstream package release on PyPI and we did test this release with pip / conda on Python 2.7 / 3.4 / 3.5 at the time. I don't expect any problems with this update in Macports, and I'll check on macOS Sierra with Python  2.7 / 3.4 / 3.5 once this is merged.

Good enough?

**Comment by mkae** [comment]
Yes, good enough. Perhaps it's overkill that I am asking those who supply patches, but as I have no idea how to  test these things reliably I thought some educated answer would be nice. And you delivered, thanks very much for the patch and for the information!! 👍

**Comment by cdeil** [comment]
Many Python packages (including this one) can be tested via:
```
python -c 'import pyregions; pyregions.test()
```
I just never figured out (or can remember) how to build Port packages and test them locally with acceptable time investment (i.e. 5 min, do these commands). If that's written up and you point me there I'll try to do it in the future.

Thanks for accepting this one without further testing.

**Comment by mkae** [comment]
Well, a good [starting point for setting up a local git clone of the ports repository is on our trac wiki](https://trac.macports.org/wiki/WorkingWithGit). It describes how to configure git in such a way that you can work with git with little hassle. But I guess you've managed to get that sorted already, otherwise you'd not be able to submit a PR. ;-)

Anyway, once your `macports/macports-ports` fork is on your machine (e.g. at `~/WC/GIT/MP/my-macports-ports/`) you have to add that to your list of sources in `/opt/local/etc/macports/sources.conf` as `file:///Users/YOU/WC/GIT/MP/my-macports-ports [nosync]`.

In the root directory of your ports clone you'd have to run `portindex` every time you updated that clone by pulling from somewhere or by making your own edits and commits locally.

More info regarding all that you can find also on the [wiki's home page](https://trac.macports.org/wiki). You can always contact the user ML if things are unclear.

The [guide](https://guide.macports.org/#development.local-repositories) might actually still point to `SVN` in many places, as we only migrated to `GitHub` very recently.

**Comment by cdeil** [comment]
For the record: for me ` python -c 'import pyregion; pyregion.test()'` works with Python 2.7, 3.4 and 3.5 with pyregion 1.2 from Macports on macOS Sierra.

I think I've read https://guide.macports.org/#development.local-repositories and even done it once.

But it doesn't really walk you through the common cycle of adding or updating a port, how to test it locally, and then how to get rid of the local changes again after it landed in master.
It only tells you how to modify local portfiles, but people like me that are a little tempted to do it would need a little bit of a tutorial-style intro example walking us through the full process.
(and no, sorry, I don't have time to contribute to Macports docs ... maybe in 2017 :-)

**Comment by mkae** [comment]
I know what you mean! Said [WorkingWithGit](https://trac.macports.org/wiki/WorkingWithGit) wiki page could be a starting point for such a tutorial for a on-and-off user like you - who just wants to quickly test a port change, file a PR and then get rid of it again once it's merged. It's not that complicated, but someone has to sit down and write it up in an understandable manner. Perhaps you can do so in 2017. That would be awesome!!! 👍

**Pull request merged**
