### PR TITLE
bakefile: update to 0.2.13

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update to 0.2.13.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
This won’t build yet:
```
--->  Building bakefile
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_bakefile/bakefile/work/bakefile-0.2.13" && /usr/bin/make -j6 -w all 
make: Entering directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_bakefile/bakefile/work/vslavik-bakefile-0016ab5'
Making all in doc
make[1]: Entering directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_bakefile/bakefile/work/vslavik-bakefile-0016ab5/doc'
make[1]: *** No rule to make target `man/bakefile.1', needed by `all-am'.  Stop.
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_bakefile/bakefile/work/vslavik-bakefile-0016ab5/doc'
make: *** [all-recursive] Error 1
```

**Comment by barracuda156** [comment]
@mascguy This one is finally ready.

**Comment by reneeotten** [comment]
any reason this isn't updated to the [latest upstream version](https://github.com/vslavik/bakefile/releases)?

**Comment by barracuda156** [comment]
> any reason this isn't updated to the [latest upstream version](https://github.com/vslavik/bakefile/releases)?

@reneeotten Technically, 0.2.13 is _the latest_ release: https://github.com/vslavik/bakefile/releases/tag/v0.2.13
There are two branches with incompatible API. The 1.x branch can be added as a separate port, if desirable. This is not on my priority list though. For now, let us have already existing version updated.

**Comment by barracuda156** [comment]
@reneeotten Good to merge or any corrections due?

**Pull request merged**
