### PR TITLE
xorg-server: update to 1.20.9

### PR DESCRIPTION
**Pull request by exg**
Fixes multiple CVEs: https://lists.x.org/archives/xorg-announce/2020-August/003058.html

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
@exg I suggest updating `xorg-server-devel` to 1.20.9 as well, since that one is rather out-of-date (1.20.4).

**Comment by chrstphrchvz** [comment]
> @exg I suggest updating `xorg-server-devel` to 1.20.9 as well, since that one is rather out-of-date (1.20.4).

If you do, https://trac.macports.org/ticket/58744 can be closed.

**Comment by ryandesign** [comment]
I am in favor of updating xorg-server and xorg-server-devel, but I am wary of combining them into a single portfile without Jeremy's approval. I know that some other maintainers like that style, but Jeremy has not used that style in his ports before, so I would err on the side of leaving the portfiles separate the way he had them, especially given that there is also still the separate xorg-server-1.18 portfile.

**Comment by chrstphrchvz** [comment]
It might also be time to consider discontinuing `xorg-server-devel`. It's not several years out-of-date as some now-deleted devel ports have been, but maybe it is no longer useful to have and maintain. If it were, then I would think more users/other maintainers would be interested in keeping it up to date, and/or having it track upstream master (1.20.99) rather than 1.20.x.

**Comment by jeremyhu** [comment]
Yeah, let's keep the two separate.  -devel should bump to track master but I haven't gotten around to that yet.  Often, there are differences which will cause the patch series to be slightly different for release and devel.

**Comment by exg** [comment]
Allright, I removed the commit to bump xorg-server-devel. It doesn't seem worth to sync it with xorg-server now if the plan is to change it to track master.

**Review by neverpanic — APPROVED** [review]

**Pull request merged**
