### PR TITLE
ioping: new port

### PR DESCRIPTION
**Pull request by harens**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.6 19G73
xcode-select version 2373

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
Looks good @harens, thanks for this submission

**Comment by herbygillot** [comment]
One realization I just had is that this utility might be better suited in the `sysutils` category, and less so `devel`.

**Comment by herbygillot** [comment]
Also `supported_archs     noarch` is incorrect; this is a C program, so it will compile down to a specific architecture wherever it's built.

`noarch` is meant more for things like interpreted software like Javascript or Python, where the runnable source is not tied to any specific processor architecture.

**Comment by harens** [comment]
Thanks @herbygillot for your detailed response. I'll correct the mistakes I made and send it as a PR if that's acceptable.

**Pull request merged**
