### PR TITLE
gmt5, gmt6: fix common_sighandler patch

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Finally, fix this correctly.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
`gmt5` fails now everywhere: https://trac.macports.org/ticket/71306
Unrelated to the fix in this PR.

**Comment by barracuda156** [comment]
I will just drop `gmt5` from here, so that CI can pass.

**Comment by remkos** [comment]
I agree (as one of the GMT developers) that it can be dropped from Macports, since we no longer maintain GMT5 anymore in any case. Users should make the transition to gmt6.

- Can we just move the Portfile to science/gmt6 instead and then remove gmt5 support from it?
- Alternatively: remove gmt6 from science/gmt5 and create a new science/gmt6.

The latter might be the preferred option and then later remove science/gmt5.

**Comment by remkos** [comment]
I suggest to close this PR in preference of #26679

**Comment by barracuda156** [comment]
@remkos Sure, thank you for handling this!

**Pull request closed without merging**
