### PR TITLE
Add GitHub handle jswhit to maintainers

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

Add GitHub handle @jswhit to maintainers

### CODE REVIEW

**Comment by pmetzger** [comment]
@ryandesign I presume based on recent activity that you're doing the rest of these at an increased pace? (That's intended as cheering, not criticism.)

**Comment by seanfarley** [comment]
LGTM

**Comment by ryandesign** [comment]
I just work on it whenever I get around to it. The goal is to modify small batches of ports at a time, so as not to overload the buildbot. PRs like this one affect few ports, which may result in me submitting more PRs at once.

**Comment by pmetzger** [comment]
Merged. Thank you!

**Pull request merged**
