### PR TITLE
submission: dupd: version 1.5: initial port

### PR DESCRIPTION
**Pull request by jvirkki**
#### Description

New port submission: dupd (version 1.5): Convenient and fast CLI to find duplicate files.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.11.6 15G17023
Xcode 8.1 8B62 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
I merged your two commits and pushed to master.

**Comment by kencu** [comment]
Looking it over further, and although it installs just fine, I see this 
```

+destroot.destdir      DESTDIR=${destroot}${prefix} \
+                      MAN_BASE=${destroot}${prefix}/share/man
```
and I suspect these two lines are not needed, as they look to be macports defaults.  I should have tried a little deeper to see if these lines could be deleted without issue.

**Comment by jvirkki** [comment]
Correct. I also thought the default DESTDIR from macports would (should?) include the prefix, but apparently it doesn't. So without the above lines the values end up being:

```
DESTDIR is /opt/local/var/macports/build/_Users_jyri_local.macports_sysutils_dupd/dupd/work/destroot
MAN_BASE is /opt/local/var/macports/build/_Users_jyri_local.macports_sysutils_dupd/dupd/work/destroot/man
```

which means it ends up installing the binary (dupd) in /bin/dupd.

Thanks!

**Comment by kencu** [comment]
It is a deficiency in your Makefile, not in MacPorts. I don't have the skills to fix it for you, but your installation destination needs to look something like ```$DESTROOT$PREFIX/bin``` etc. 

There are some real Makefile experts in MacPorts admin -- perhaps @ryandesign will have a look at it for you and fix it up if he has time.

**Comment by kencu** [comment]
Here's one I wrote up that works well with MacPorts -- perhaps there is a hint in this for you to ponder <https://github.com/kencu/snowleopardfixes/blob/master/Makefile>

**Comment by jvirkki** [comment]
Unfortunately PREFIX is not being set in the env when macports calls make. Removing the destroot.destdir line from the Portfile results in the following values being set when make is called:

```
DESTDIR is /opt/local/var/macports/build/_Users_jyri_local.macports_sysutils_dupd/dupd/work/destroot
PREFIX is
```

Possibly there is some setting I need to set to make macports define PREFIX (without manually doing so in the Portfile), but not sure what it is.

**Comment by kencu** [comment]
Ah. You could be right about that. Here's my snowleopardfixes Portfile:
```
build.env           CXX="${configure.cxx}" \
                    CXXFLAGS="${configure.cxxflags} [get_canonical_archflags cxx]" \
                    CC="${configure.cc}" \
                    CFLAGS="${configure.cflags}" \
                    LDFLAGS="${configure.ldflags}  [get_canonical_archflags ld]" \
                    PREFIX=${prefix}

destroot.env        PREFIX=${prefix}
```

**Comment by jvirkki** [comment]
Got it. What I'll do for the next release is to set PREFIX separately in the Portfile (as above) to make it clearer.

**Pull request closed without merging**
