### PR TITLE
rust-analyzer: update to 2021-08-16

### PR DESCRIPTION
**Pull request by herbygillot**
- Closes: https://trac.macports.org/ticket/63283

###### Tested on

macOS 10.15.7 19H1323 x86_64
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -d install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by fabius — APPROVED** [review]
LGTM, thank you @herbygillot !

**Comment by herbygillot** [comment]
Thanks @fabius

**Comment by pmetzger** [comment]
BTW, apparently rust-analyzer is under very heavy development and there's a new release every week or two. I'm not sure what the right way to deal with that is. I looked myself at doing the update but I have to admit I'm a bit scared of the cargo ports.

**Comment by pmetzger** [comment]
Could your python script for this be added to macports-contrib? Also, would there be any way to automate the process even further? (And maybe you want to add some documentation on all of this somewhere?)

**Pull request merged**
