### PR TITLE
ddrescue: fix compilation error related to std::exit

### PR DESCRIPTION
**Pull request by mascguy**
### Description

File `loggers.cc` references `std::exit`, without including `cstdlib`. This works with some compilers, but not others.

Fixes: https://trac.macports.org/ticket/65300

### Tested on

* macOS 10.7
* macOS 10.9
* macOS 10.11

### CODE REVIEW

**Review by jmroot — CHANGES_REQUESTED** [review]
Changing compilers is not the right fix for a missing include.

**Comment by mascguy** [comment]
> Changing compilers is not the right fix for a missing include.

PR updated

**Comment by mascguy** [comment]
Retested on 10.7, 10.9, and 10.11, with latest approach. And looks good on all three.

**Review by raimue — APPROVED** [review]
Looks good to me. :+1:

**Pull request merged**
