### PR TITLE
R-app: revbump for new R

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Forgotten revbump

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Sonoma as usual:
```
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_math_R-app/R-app/work/Mac-GUI-1.80/REngine/Rinit.m:110:23: error: incompatible function pointer types assigning to 'void (*)(const char *)' from 'void (char *)' [-Wincompatible-function-pointer-types]
      ptr_R_ShowMessage = Re_ShowMessage;
                        ^ ~~~~~~~~~~~~~~
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_math_R-app/R-app/work/Mac-GUI-1.80/REngine/Rinit.m:111:23: error: incompatible function pointer types assigning to 'int (*)(const char *, unsigned char *, int, int)' from 'int (char *, unsigned char *, int, int)' [-Wincompatible-function-pointer-types]
      ptr_R_ReadConsole =  Re_ReadConsole;
                        ^  ~~~~~~~~~~~~~~
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_math_R-app/R-app/work/Mac-GUI-1.80/REngine/Rinit.m:113:26: error: incompatible function pointer types assigning to 'void (*)(const char *, int, int)' from 'void (char *, int, int)' [-Wincompatible-function-pointer-types]
      ptr_R_WriteConsoleEx = Re_WriteConsoleEx;
                           ^ ~~~~~~~~~~~~~~~~~
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_math_R-app/R-app/work/Mac-GUI-1.80/REngine/Rinit.m:124:20: error: incompatible function pointer types assigning to 'int (*)(const char *)' from 'int (char *)' [-Wincompatible-function-pointer-types]
      ptr_R_EditFile = Re_Edit;
                     ^ ~~~~~~~
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_math_R-app/R-app/work/Mac-GUI-1.80/REngine/Rinit.m:126:21: error: incompatible function pointer types assigning to 'int (*)(int, const char **, const char **, const char *, Rboolean, const char *)' from 'int (int, char **, char **, char *, Rboolean, char *)' [-Wincompatible-function-pointer-types]
      ptr_R_ShowFiles = Re_ShowFiles;
                      ^ ~~~~~~~~~~~~
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_math_R-app/R-app/work/Mac-GUI-1.80/REngine/Rinit.m:127:21: error: incompatible function pointer types assigning to 'int (*)(int, const char **, const char **, const char *)' from 'int (int, char **, char **, char *)' [-Wincompatible-function-pointer-types]
      ptr_R_EditFiles = Re_EditFiles;
                      ^ ~~~~~~~~~~~~
  6 errors generated.
```

**Comment by barracuda156** [comment]
Opened an issue: https://github.com/R-macos/Mac-GUI/issues/15

**Comment by i0ntempest** [comment]
`rel_r_ver` variable is the version of R when this version of R app was released (hardcoded in the source of R app). Since no new R-app is released it should not be changed, otherwise the reinplace command would fail.

**Comment by barracuda156** [comment]
I don’t think anything failed for me locally, but I will drop that change. We still require revbump though.

**Comment by i0ntempest** [comment]
> I don’t think anything failed for me locally, but I will drop that change. We still require revbump though.

Yes, because reinplace failures are not hard errors and won't stop the build. We do still need a revbump, a change of `rel_r_ver` is only needed if we have a new R app source release which we have not seen in a while.

**Comment by barracuda156** [comment]
What should we do about the Sonoma CI failure btw?

**Comment by i0ntempest** [comment]
There is this `-Wno-error=incompatible-function-pointer-types`cflag we can use to get pass this error, but 1 we'll need to patch the Xcode project to put it in which is a pain in the ass and 2 I'm not sure if this is a case like the implicit function declaration errors where bypassing the error with a flag would result in undefined behaviors.

**Comment by barracuda156** [comment]
Oops, I have pushed to this branch something else. I close this PR and will make another one for R-app. Sorry.

**Pull request closed without merging**
