### PR TITLE
fastfetch: fix the port for old systems and powerpc

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

@herbygillot Last time I gave up on this, but now it worked through.
Some modules are disabled; maybe I fix something extra, but for now this. AFAICT, the app is functional now.

fastfetch_ppc

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by aeiouaeiouaeiouaeiouaeiouaeiou — APPROVED** [review]

**Comment by herbygillot** [comment]
A lot of patches to maintain, but thank you nonetheless, @barracuda156.

**Comment by barracuda156** [comment]
> A lot of patches to maintain, but thank you nonetheless, @barracuda156.

@herbygillot It was not pleasant to fix for myself either LOL

Upstream is not really interested to support older OS, it seems, though something could be accepted selectively, perhaps (one patch is merged btw).

I suggest pegging old systems, once patches fail to apply with minimal adjustments.
If I am still around and have time, I can fix it and unpeg, otherwise this kind of app should be good for years, since macOS itself won’t change.

**Comment by barracuda156** [comment]
@herbygillot Any idea why we have `glib2` failing?

> Dependency 'glib2' with variants '+x11' has previously failed and is required.
Port glib2 previously failed in build https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/210987

**Comment by barracuda156** [comment]
@herbygillot Re updates: if you tag me with every next update, I can handle rebasing (or pegging, once rebasing becomes painful or something further gets broken).

Next update will need at least a trivial two-lines change to CMakeLists patch, since bluetoothradio module has been added.

**Comment by barracuda156** [comment]
@herbygillot LOL, the new version is out and of course patches do not apply cleanly. Let me handle it.

Besides, I got it running on Tiger :)

**Comment by herbygillot** [comment]
@barracuda156, apologies, I should have made that next update a PR and tagged you

**Comment by barracuda156** [comment]
@herbygillot I will make a follow up, finishing the rebase now.

**Comment by barracuda156** [comment]
@herbygillot Should I peg it now, to the same version (which gonna look odd), in order to avoid breakages in the future? The upstream gets regular updates, and they are likely to break patches _and_ break the build by newly added components.

**Comment by herbygillot** [comment]
> @herbygillot Should I peg it now, to the same version (which gonna look odd), in order to avoid breakages in the future? The upstream gets regular updates, and they are likely to break patches _and_ break the build by newly added components.

Yeah, pegging the version is fine it if it will make life easier for managing the older macOS versions

**Pull request merged**
