### PR TITLE
libffi: use Apple-provided sources on Big Sur

### PR DESCRIPTION
**Pull request by danchr**
Apple added some symbols to the `libffi` included with Big Sur, and PyObjC uses some of them. To fix this, I just switched the port to use that on Big Sur. I'm not sufficiently familiar with `libffi` to know whether there's a more clever fix.

Fixes: https://trac.macports.org/ticket/62475

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
Its not ideal to use different sources on different OSes. Do you know if Apple have submitted their changed back to upstream ?

**Comment by danchr** [comment]
> Its not ideal to use different sources on different OSes. Do you know if Apple have submitted their changed back to upstream ?

AFAICT they have at least two pending pull requests:

https://github.com/libffi/libffi/pull/620
https://github.com/libffi/libffi/pull/621

They changes are rather involved, so extracting them individually to patches isn't straightforward. One option is to simply generate a patch containing all of Apple's changes.

**Comment by kencu** [comment]
https://raw.githubusercontent.com/Homebrew/formula-patches/06252df03c68aee70856e5842f85f20b259e5250/libffi/libffi-3.3-arm64.patch

**Comment by cjones051073** [comment]
I would propose then changing this PR to stick with the original source, but use the homebrew patch to apply the update. It should also, assuming it builds on all OSes be applied across the board, not just to big sur.

**Comment by kencu** [comment]
Someone should run the test suites on at least a couple of systems.. 

This patch is right from Jeremy's PRs (and another issue post is useful too). It is likely to work on arm64 (that is the only place Homebrew is using it). The other systems? Who knows. 

Last time libffi was updated I ran the test suites on 10.4 up through every system, and moved several fixes upstream.

**Comment by danchr** [comment]
I've updated this with a quick attempt at applying the patch from HomeBrew. As far as I can tell, importing PyObjC does work, and no longer gives this error:

```
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/objc/_objc.cpython-39-darwin.so, 2): Symbol not found: _ffi_find_closure_for_code_np
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/objc/_objc.cpython-39-darwin.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/objc/_objc.cpython-39-darwin.so
```

The reason the error passed silently was that MacPorts' `libffi` is installed as a bare `ffi.h`, but PyObjC picked up the system header by including `ffi/ffi.h`.

**Comment by ryandesign** [comment]
The patch is enormous, presumably primarily because of unrelated changes due to regenerating with automake 1.16.3 instead of the 1.16.1 used originally. Could the patch be made as small as possible, please, for example by generating with automake 1.16.1?

**Comment by danchr** [comment]
> The patch is enormous, presumably primarily because of unrelated changes due to regenerating with automake 1.16.3 instead of the 1.16.1 used originally. Could the patch be made as small as possible, please, for example by generating with automake 1.16.1?

I've removed the autogenerated parts, and enabled `use_automake` instead.

**Comment by coderprodigy** [comment]
> I've updated this with a quick attempt at applying the patch from HomeBrew. As far as I can tell, importing PyObjC does work, and no longer gives this error:
> 
> ```
> ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/objc/_objc.cpython-39-darwin.so, 2): Symbol not found: _ffi_find_closure_for_code_np
>   Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/objc/_objc.cpython-39-darwin.so
>   Expected in: flat namespace
>  in /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/objc/_objc.cpython-39-darwin.so
> ```
> 
> The reason the error passed silently was that MacPorts' `libffi` is installed as a bare `ffi.h`, but PyObjC picked up the system header by including `ffi/ffi.h`.

I am still facing this issue. I have updated PyObjC but the error is the same. What shall I do?

**Comment by danchr** [comment]
Closing; I managed to force using the system libffi.

**Comment by danchr** [comment]
> Closing; I managed to force using the system libffi.

Fix applied in 217d8731dcc6247f67004de48d3f4760b07e33db.

**Pull request closed without merging**
