### PR TITLE
nodejs*: drop nodejs{5,7,9}

### PR DESCRIPTION
**Pull request by yan12125**
#### Description

Those versions are non-LTS and have reached their end-of-life [1].

Closes: https://trac.macports.org/ticket/53799
Closes: https://trac.macports.org/ticket/54083
Closes: https://trac.macports.org/ticket/55655
Closes: https://trac.macports.org/ticket/55656

I don't think there's a node.js package compatible with a non-LTS version but none of LTS versions. I don't touch nodejs 4 as newer nodejs versions does not work on 10.6 [2].

[1] https://github.com/nodejs/Release
[2] https://trac.macports.org/ticket/53166

###### Type(s)
- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
Not tested

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
There was a similar effort but abandoned https://github.com/macports/macports-ports/pull/420.
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
If you wouldn't mind terribly, I would appreciate a few days to see which of these is the actual latest version that 10.6.8 can support.

So much has changed with the legacysupport PG and libc++ that these older ideas of what is compatible with what might no longer be actually true...

**Comment by yan12125** [comment]
Sorry, I don't have enough disk space to maintain a 10.6 VM :(

**Comment by kencu** [comment]
looks like many of the even numbered maintenance versions do build on older systems, so feel free to bin these defunct versions from my point of view.

**Comment by l2dy** [comment]
Maintainer timeout! I also agree with removing non-LTS versions, so I'm going to merge this now. Thanks for your contribution.

**Comment by yan12125** [comment]
Thanks for looking into this PR. With awesome efforts in https://github.com/macports/macports-ports/pull/4119, I guess nodejs 4 can be dropped, too. Will do that in another PR.

**Pull request merged**
