### PR TITLE
maxima: update to 5.43.0

### PR DESCRIPTION
**Pull request by pietvo**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.6 17G10021
Xcode 9.4.1 9F2000
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by tomio-arisaka** [comment]
Thanks for having an interest in Maxima.

(1) Current Maxima needs '**gsed**' (GNU sed) instead of 'sed' (BSD sed).
I think you should add '**port:gsed**' to '**depends_build**'.
Therefore, the '_**build_html.sh.in.patch**_' file is not needed.
See <https://sourceforge.net/p/maxima/code/ci/aa7d8228f369821aa6cbf14a6f7e552bb771e247/>

(2) What does "_the ystem TeX_" mean?  Why are _cm-super fonts_ checked?

(3) Maxima-5.43.1 has been released.
See <https://sourceforge.net/projects/maxima/files/Maxima-source/>

(4) I don't know why you wrote "# git describe --tags : _branch-xxx???_".
But the development version of Maxima is based on the git tags.
For example:
```
$ git describe --tags
branch-5_43-base-266-g1a9e53f9f

$ maxima --version
Maxima branch_5_43_base_266_g1a9e53f9f_dirty

```

**Comment by pietvo** [comment]
> Thanks for having an interest in Maxima.
> 
> (1) Current Maxima needs '**gsed**' (GNU sed) instead of 'sed' (BSD sed).
> I think you should add '**port:gsed**' to '**depends_build**'.
> Therefore, the '_**build_html.sh.in.patch**_' file is not needed.
> See https://sourceforge.net/p/maxima/code/ci/aa7d8228f369821aa6cbf14a6f7e552bb771e247/

The first time I installed Maxima with my Profile, it used `/usr/bin/sed`, which caused that problem (it doesn't interpret  `\n` as newline in the `sed` arguments. So that's why I made this change. Later installs did use `gsed`, however. I have no idea why the difference, because `used` had been installed all the time. And the patch does no harm for `gsed`. So the question is, if you add the `port:gsed`, is there still a chance that the install will use `/usr/bin/sed`?

> (2) What does "_the ystem TeX_" mean? Why are _cm-super fonts_ checked?

Typo: it should have been "the system TeX", which means the TeX that's installed outside of macports. I have the MacTeX system installed on my computer, and I don't want to have macports TeX to be installed just to generate the documentation. So, like some other ports I tried to use the system TeX instead, if it is installed.

`cm-super` fonts are needed by `texinfo` for non-ASCII characters. That's why the requirement `port:texlive-fonts-recommended` was there. These contain (a.o.) the `cm-super` fonts. But if you need this ports, large part of TeX are also installed, so I tried to avoid that if there were already installed.

> (3) Maxima-5.43.1 has been released.
> See https://sourceforge.net/projects/maxima/files/Maxima-source/

OK, thanks, I hadn't noticed that. I will change it to use that version.

> (4) I don't know why you wrote "# git describe --tags : _branch-xxx???_".
> But the development version of Maxima is based on the git tags.

The previous version had `# git describe --tags : branch-5_41-base-415-g7e71fc4`, which obviously is no longer applicable. But I could't find the current branch/tag for the development version, so I left in this comment with the to be changed parts replaced by question marks.

> For example:
> 
> ```
> $ git describe --tags
> branch-5_43-base-266-g1a9e53f9f
> 
> $ maxima --version
> Maxima branch_5_43_base_266_g1a9e53f9f_dirty
> ```

I didn't checkout maxima on my own computer (other than letting macports do it), so I couldn't run these commands. Thanks for the info. So maybe I should clone maxima, just to find out this info.

I'll update to 5.43.1 and then amend the PR.

**Comment by tomio-arisaka** [comment]
>> (1) Current Maxima needs 'gsed' (GNU sed) instead of 'sed' (BSD sed).
>> I think you should add 'port:gsed' to 'depends_build'.
>> Therefore, the 'build_html.sh.in.patch' file is not needed.
> 
> The first time I installed Maxima with my Profile, it used /usr/bin/sed, which caused that problem (it doesn't interpret \n as newline in the sed arguments. So that's why I made this change. Later installs did use gsed, however. I have no idea why the difference, because gsed had been installed all the time. And the patch does no harm for gsed. So the question is, if you add the port:gsed, is there still a chance that the install will use /usr/bin/sed?

When running '**configure**' of Maxima, installed '**gsed**' is detected.
I have checked the difference between '**gsed**' and '**sed**' outputs as follows:

```
$ 
$ tar xf ./maxima-5.43.1.tar.gz 
$ 
$ cat ./test_info_w_sed.sh 
#!/bin/sh

SED=sed
TMP1=`pwd`/${SED}-output/originalTranslation
TMP2=`pwd`/${SED}-output/modifiedTranslation
mkdir -p ${TMP1} ${TMP2}

for f in $1/*.texi
do
  ${SED} -e 's/^@\(deffn\|defvr\)  *{[^}]*}  *\([^[:blank:]]*\).*/@anchor{Item: \2}\n&/;' -e 's/^@node  *\([^,]*\).*/@anchor{Item: \1}\n&/' $f > ${TMP1}/$(basename $f)
  ${SED} -e 's/^@\(deffn\|defvr\)  *{[^}]*}  *\([^[:blank:]]*\).*/@anchor{Item: \2}\'$'\n&/;' -e 's/^@node  *\([^,]*\).*/@anchor{Item: \1}\'$'\n&/' $f > ${TMP2}/$(basename $f)
done 

$ 
$ sh ./test_info_w_sed.sh ./maxima-5.43.1/doc/info
$ 
$ ls -ltT ./sed-output/
total 0
drwxr-xr-x  101 name  staff  3434  1 22 22:06:48 2020 modifiedTranslation
drwxr-xr-x  101 name  staff  3434  1 22 22:06:48 2020 originalTranslation
$ 
$ 
$ cat ./test_info_w_gsed.sh 
#!/bin/sh

SED=gsed
TMP1=`pwd`/${SED}-output/originalTranslation
TMP2=`pwd`/${SED}-output/modifiedTranslation
mkdir -p ${TMP1} ${TMP2}

for f in $1/*.texi
do
  ${SED} -e 's/^@\(deffn\|defvr\)  *{[^}]*}  *\([^[:blank:]]*\).*/@anchor{Item: \2}\n&/;' -e 's/^@node  *\([^,]*\).*/@anchor{Item: \1}\n&/' $f > ${TMP1}/$(basename $f)
  ${SED} -e 's/^@\(deffn\|defvr\)  *{[^}]*}  *\([^[:blank:]]*\).*/@anchor{Item: \2}\'$'\n&/;' -e 's/^@node  *\([^,]*\).*/@anchor{Item: \1}\'$'\n&/' $f > ${TMP2}/$(basename $f)
done 

$ 
$ sh ./test_info_w_gsed.sh ./maxima-5.43.1/doc/info
$ 
$ ls -ltT ./gsed-output/
total 0
drwxr-xr-x  101 name  staff  3434  1 22 22:07:16 2020 modifiedTranslation
drwxr-xr-x  101 name  staff  3434  1 22 22:07:16 2020 originalTranslation
$ 
```
I think the outputs show that the '**_build_html.sh.in.patch_**' file is not needed.


>>  (2) What does "the ystem TeX" mean? Why are cm-super fonts checked?
> 
> Typo: it should have been "the system TeX", which means the TeX that's installed outside of macports. I have the MacTeX system installed on my computer, and I don't want to have macports TeX to be installed just to generate the documentation. So, like some other ports I tried to use the system TeX instead, if it is installed.
> 
> cm-super fonts are needed by texinfo for non-ASCII characters. That's why the requirement port:texlive-fonts-recommended was there. These contain (a.o.) the cm-super fonts. But if you need this ports, large part of TeX are also installed, so I tried to avoid that if there were already installed.
> 

I see.
But I don't know whether checking the software installed without MacPorts is allowed or not.
I hope someone who is a member of MacPorts will help you.

**Comment by pietvo** [comment]
> When running '**configure**' of Maxima, installed '**gsed**' is detected.

Yes, I see that now. No idea why that did not work the first time.

> I have checked the difference between '**gsed**' and '**sed**' outputs as follows:
> 
> ```
> [...]
> $ ls -ltT ./sed-output/
> total 0
> drwxr-xr-x  101 name  staff  3434  1 22 22:06:48 2020 modifiedTranslation
> drwxr-xr-x  101 name  staff  3434  1 22 22:06:48 2020 originalTranslation
> [...]
> $ ls -ltT ./gsed-output/
> total 0
> drwxr-xr-x  101 name  staff  3434  1 22 22:07:16 2020 modifiedTranslation
> drwxr-xr-x  101 name  staff  3434  1 22 22:07:16 2020 originalTranslation
> $ 
> ```

It shows that the directories have the same size. It doesn't say anything about whether the files inside are the same.

> I think the outputs show that the '**_build_html.sh.in.patch_**' file is not needed.

It all depends on which `sed` is chosen. For example, `gsed` can be installed to have a link in `/opt/local/libexec/gnubin/sed`, and so if that is in your PATH, `sed` will effectively be `gsed` and the patch isn't necessary. But if `sed` is `usr/bin/sed` as it is on my system, it is necessary. 
See the following diffs:
```
bash-3.2$ diff -r gsed-output/*
bash-3.2$ diff -r sed-output/*
diff -r sed-output/modifiedTranslation/Affine.texi sed-output/originalTranslation/Affine.texi
7,8c7
< @anchor{Item: Introduction to Affine}
< @node Introduction to Affine, Functions and Variables for Affine, Affine, Affine
---
> @anchor{Item: Introduction to Affine}n@node Introduction to Affine, Functions and Variables for Affine, Affine, Affine
21,22c20
< @anchor{Item: Functions and Variables for Affine}
< @node Functions and Variables for Affine,  , Introduction to Affine, Affine
---
> @anchor{Item: Functions and Variables for Affine}n@node Functions and Variables for Affine,  , Introduction to Affine, Affine
[...]
```
So for `gsed`, it doesn't make a difference, but for `sed` it does. And it introduced just these problems that makes the installation fail.

But as the install now seems to prefer `gsed` (and I have added `port:gsed`), it seems no longer to be necessary.
>
> But I don't know whether checking the software installed without MacPorts is allowed or not.
> I hope someone who is a member of MacPorts will help you.

I have seem this construction in other ports (mainly also related to TeX), so I assume it is OK.

I have installed 5.43.1 now, so I am going to close this PR, and open a new one for 5.43.1, without that patch, and with the `maxima-devel` port updated.

Thanks for your input.

**Pull request closed without merging**
