### PR TITLE
clang{5-9}: Use portconfigure::get_clang_compilers to get clang version list

### PR DESCRIPTION
**Pull request by cjones051073**
See discussion in https://github.com/macports/macports-ports/pull/5563

### CODE REVIEW

**Comment by kencu** [comment]
The only issue I have with this sort of thing is trying to figure out what is going wrong when things start breaking.

**Comment by jmroot** [comment]
Nothing inside the portconfigure namespace should be considered public API. But TBH, it's probably better for reproducibility not to change which compiler is used based on which compilers happen to be installed already.

**Comment by cjones051073** [comment]
> The only issue I have with this sort of thing is trying to figure out what is going wrong when things start breaking.

I can add a ui_debug message in the loop, if you think that would help ? 

The cost of a minor convenience like you mention is (IMHO) tiny compared to making things much more robust to adding new compilers. Now, just adding a new one to https://github.com/macports/macports-ports/blob/master/_resources/port1.0/compilers/clang_compilers.tcl is all that is required, everything else is automatic.

**Comment by cjones051073** [comment]
> Nothing inside the portconfigure namespace should be considered public API. 

OK, but we really could do with public methods to get this lists, to avoid exactly what was done before, hardcoding the same list in a gazillion places...

**Comment by cjones051073** [comment]
> Nothing inside the portconfigure namespace should be considered public API. But TBH, it's probably better for reproducibility not to change which compiler is used based on which compilers happen to be installed already.

I do agree the whole logic in the clang compilers that change the behaviour on what happens to be installed is anyway a bit funky, but this PR does not change anything in that regard. It at least gets rid of the hardcoded lists...

**Comment by cjones051073** [comment]
@jmroot Does a public way to access the list of *all* valid compiler options exist ? From that I could at least filter out the macports clang ones to get the version list required here ? If not, could it be added to base ?

**Comment by jmroot** [comment]
Of course, the compiler.fallback option exists.

**Comment by cjones051073** [comment]
I don't see how I can use that to get the list of all possible valid compilers ?

**Comment by cjones051073** [comment]
maybe I just mis-understand what `compiler.fallback` contains. Is it really guaranteed to have all valid compiler options in it ?

**Comment by jmroot** [comment]
It certainly contains all the compilers that you could possibly need to blacklist.

**Comment by cjones051073** [comment]
> It certainly contains all the compilers that you could possibly need to blacklist.

Thats not what I need. This PR is just aiming to replacing the hardcoded clang list with one dynamically created. A quick test with llvm-9.0 shows what I thought, that ${compiler.fallback} only contains 'clang'. So I cannot use it as a replacement for what portconfigure::get_clang_compilers gives.

**Comment by jmroot** [comment]
Of course it only contains clang after it's set to that in the portfile...

**Comment by cjones051073** [comment]
> Of course it only contains clang after it's set to that in the portfile...

Duh, how did I miss that...

**Comment by cjones051073** [comment]
OK, now using ${compiler.fallback} list. Thanks for the suggestion.

**Pull request closed without merging**
