### PR TITLE
openmpi: Add gcc10.

### PR DESCRIPTION
**Pull request by dstrubbe**
openmpi: Add gcc10. Closes https://trac.macports.org/ticket/60491.

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.12.6
Xcode 9.2

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by dstrubbe** [comment]
Oops, shouldn't have had the mpich part in here.

**Comment by ryandesign** [comment]
Not sure how to deal with "merge upstream changes (#1)" and the 268 files this PR now changes...

**Comment by dstrubbe** [comment]
I was trying to figure out how to update the branch so the mpich commit (which is already in master) wouldn't show up. Any suggestion? Otherwise I guess maybe I need to delete all of this and try again.

**Comment by ryandesign** [comment]
Normally you wouldn't delete the PR and branch and make a new one. Instead, you would fix your local branch by rebasing it on the new master and then force-pushing the changes up.

The new PR is #7667.

**Comment by dstrubbe** [comment]
Ok. Well, git seems designed to make this sort of task as difficult as possible, so I decided to just try again.

**Pull request closed without merging**
