### PR TITLE
py27-zopfli: fixed build

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
@mascguy I have no idea why does it fails on `py36-zopfli` :(

**Comment by reneeotten** [comment]
> @mascguy I have no idea why does it fails on `py36-zopfli` :(

if you check the CI you'll see:
```'py36-six' with variants '' (requesting '') ... [FAIL] (archivefetch)```

so for some reason on that builder it couldn't fetch the archive - probably an intermittent issue and nothing to worry about. You could just restart the build and see if it finishes..

**Comment by mascguy** [comment]
> > @mascguy I have no idea why does it fails on `py36-zopfli` :(
> 
> if you check the CI you'll see: `'py36-six' with variants '' (requesting '') ... [FAIL] (archivefetch)`
> 
> so for some reason on that builder it couldn't fetch the archive - probably an intermittent issue and nothing to worry about. You could just restart the build and see if it finishes..

Great point Renee. I've restarted the CI jobs, and hopefully they'll complete successfully this time.

**Comment by catap** [comment]
@reneeotten I can't restart CI :(

**Comment by mascguy** [comment]
> @reneeotten I can't restart CI :(

That's okay, I already took care of it for you.

**Comment by jmroot** [comment]
Is this purely because pep517 doesn't work with python 2.7? If so, leave it enabled for py36 and later, and there's no need to bump the revision.

**Comment by jmroot** [comment]
I don't think it's worth the effort to add the needed modules for py27. At least some of them have dropped 2.7 support in the latest versions.

**Comment by catap** [comment]
@jmroot I've tried and I need to enable py27 for a few ports and one of them is failed as:
```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/opt/local/share/py-bootstrap-modules/build/__init__.py", line 39
    TOMLDecodeError: Type[Exception]
```

=> I'm moving forward with your suggstion

**Comment by catap** [comment]
@jmroot here it is

**Comment by mascguy** [comment]
@jmroot and @reneeotten Any thoughts/concerns at this point?

Are we ready to merge, or...?

**Pull request merged**
