### PR TITLE
Update openSCAD to latest release 2019.05

### PR DESCRIPTION
**Pull request by sxntxn**
#### Description

This branch:
* adds port lib3mf, needed for the most recent release of OpenSCAD
* updates OpenSCAD to the most recent release (2019.05, though)
* marks OpenSCAD's -devel subport as obsolete, as it is also older than the release (I haven't gauged the amount of work needed for a -devel subport based on current master, though)

Please let me know what you think.

###### Type(s)
- [x] submission
- [x] update

###### Tested on
macOS 10.15.5 19F101
Xcode 11.5 11E608c 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`? -> `lib3mf has no tests turned on` , `openscad has no tests turned on`
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by dstrubbe** [comment]
Hello, can you please comment on the removal of the patches, most of the destroot phase lines, and the testing for this OpenSCAD version? Is it the case the patches were fixed upstream? Are there no longer tests included with the code?

I don't this is really the intended use of the obsolete portgroup. It is for something that is discontinued, not just that we happen not to have updated the -devel subport lately.

**Comment by dstrubbe** [comment]
Can you enable and try the tests of lib3mf? Your configure.args line turns them off, so it seems there must be some that can be turned on.

**Comment by sxntxn** [comment]
> Hello, can you please comment on the removal of the patches, most of the destroot phase lines, and the testing for this OpenSCAD version? Is it the case that the patched issues were fixed upstream? Are there no longer tests included with the code?

It is the version I got to compile, run, and work with. I don't remember about patches (I maintained this in a private tree).

> I don't think this is really the intended use of the obsolete portgroup. It is for something that is discontinued, not just that we happen not to have updated the -devel subport lately.

Well, how to progress? What are the alternatives?

> Can you enable and try the tests of lib3mf? Your configure.args line turns them off, so it seems there must be some that can be turned on.

That results in:
```
LIB3MF_TESTS ... ON
CMake Error at UnitTests/CMakeLists.txt:1 (ADD_SUBDIRECTORY):
  The source directory

    /opt/local/var/macports/build/_opt_local_var_macports_sources_github.com_macports_macports-ports_science_lib3mf/lib3mf/work/lib3mf-1.8.1/UnitTests/googletest

  does not contain a CMakeLists.txt file.
```

**Comment by dstrubbe** [comment]
> > Hello, can you please comment on the removal of the patches, most of the destroot phase lines, and the testing for this OpenSCAD version? Is it the case that the patched issues were fixed upstream? Are there no longer tests included with the code?
> 
> It is the version I got to compile, run, and work with. I don't remember details about the single patches (I maintained this in a private tree).

Ok, well please investigate these issues then. I would assume the patches and destroot code is still needed unless you have evident that they aren't. And we should enable and try out tests whenever available.

> 
> > I don't think this is really the intended use of the obsolete portgroup. It is for something that is discontinued, not just that we happen not to have updated the -devel subport lately.
> 
> Well, how to progress? What are the alternatives?

So we can leave it as is, and just make sure the version in this port is identified correctly.

**Comment by dstrubbe** [comment]
Hello @sxntxn, are you interested in getting this pull request ready for merging?

**Comment by sxntxn** [comment]
It looks like there's an OpenSCAD 2020.12 release in preparation. I'd prefer to aim for that.

**Comment by dstrubbe** [comment]
Ok. The same questions we have discussed here will arise for that, about patches, tests, etc.

**Comment by kencu** [comment]
given all this, and the conflcts, and the fact that @dstrubbe is the maintainer and will update this port at the right time, I'm going to close this. Thanks for the dialog and your contributions! @dstrubbe -- back to you to update when/as you see fit!

**Pull request closed without merging**
