### PR TITLE
r: add quartz variant

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.4 19E266
Xcode 11.4 11E146

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ra1nb0w** [comment]
build fine for me. maintainer timeout. merge
thank you
what do you think to become co-maintainer?

**Comment by i0ntempest** [comment]
Sure, would like to.

**Comment by ra1nb0w** [comment]
open a new PR.

**Comment by i0ntempest** [comment]
#6853

**Comment by ryandesign** [comment]
Since this changed the files that get installed (it added manpage symlinks), the revision needed to have been increased. Done in 1ce3492d206a520e451001e460b7ec4df4bd7307.

**Pull request merged**
