### PR TITLE
glab: new port

### PR DESCRIPTION
**Pull request by harens**
#### Description

See https://github.com/macports/macports-ports/pull/9874

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.1 20C69
xcode-select version 2384.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
Thanks for the submission @harens

**Comment by harens** [comment]
Thanks for merging @herbygillot. As always, I really appreciate it.

**Comment by profclems** [comment]
Thanks @harens for maintaining this port. Looking forward to reviewing your PR with the installation instructions on [glab](http://github.com/profclems/glab)

**Comment by herbygillot** [comment]
Just a note, but perhaps https://glab.readthedocs.io might be a more suitable homepage for this port.

As of right now, `homepage` is automatically pointing to the GitHub project, since it is set by the  `github` portgroup (which the `golang` portgroup uses whenever the project domain is github.com).

**Pull request merged**
