### PR TITLE
libebur128 portfile update

### PR DESCRIPTION
**Pull request by audionuma**
Update libebur128 portfile to version 1.2.3

### CODE REVIEW

**Comment by audionuma** [comment]
sorry, messed up some things.
Coming back with a clean pull request

**Comment by mojca** [comment]
You don't need to close a PR. Just force push something "cleaner" to the same branch.

**Comment by mojca** [comment]
You can go to your branch, run
```
git rebase -i HEAD~3
```
and delete the first and last commit. If you are happy with the history, run `git push -f ...`

**Comment by mojca** [comment]
Please also add your GitHub handle. That is: replace
```
maintainers         gmail.com:audionuma openmaintainer
```
with
```
maintainers         {gmail.com:audionuma @audionuma} openmaintainer
```
For the next time (or this time in case you are not to affraid of a bit of history editing): the commit message should be
```
libebur128: update to version 1.2.3
```
Apart from those tiny things the PR looks ok. Let us know if you want to try to do those changes yourself or if you need help with rewriting history.

**Comment by audionuma** [comment]
I did my best to clean my own mess and edit the commit as suggested.
Hope it's correct now.

**Comment by mojca** [comment]
There's still a superfluous merge (but I can try to get rid of it for you from the command line).

**Comment by mojca** [comment]
Hint for next time: make your own local branch rather than committing to the `master` branch of your fork. If you commit your changes to master, you will probably only ever be able to make one single pull request at a time and even once you do, you'll have to deal with weird conflicts.

```
git branch <something>
git checkout <something>
<do your changes>
git commit
git push <labelofyourfork>
...
<long time passes>
...
git checkout master
git pull origin master --rebase # rebase is just in case
git checkout something
git rebase master
<do further changes>
git push -f <labelofyourfork>
git checkout master
```

**Comment by audionuma** [comment]
Thanks for the hint.

**Pull request merged**
