### PR TITLE
Fixing vigra port for debug builds

### PR DESCRIPTION
**Pull request by BSeppke**
#### Description
https://trac.macports.org/ticket/59970 describes an issue, which hinders vigra from being compiled in debug build. The patch of this pull request should fix this issue.

###### Type(s)

- [X] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.6 18G2022
Xcode 11.3.1 11C504 

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
LGTM. But please fix the commit message to conform to our guidelines.

**Comment by mf2k** [comment]
https://trac.macports.org/wiki/CommitMessages

**Comment by BSeppke** [comment]
OKay, I changed the commit message accordingly.

**Comment by mf2k** [comment]
You only need to reference the ticket once in the CM. Just use:

`Closes: https://trac.macports.org/ticket/59970
`

**Comment by BSeppke** [comment]
Okay edited the closing note and changed default variant from +python27 to +python37. This is necessaary for the automated testing to succees, since boost has +python37 variant by default.

**Pull request merged**
