### PR TITLE
liboggz: submission

### PR DESCRIPTION
**Pull request by sbooth**
#### Description

Submission of liboggz version 1.1.1

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.5 21G72 x86_64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
I have been told by others here that `platforms darwin` is a default option and does not have to be explicitly specified in a portfile.

**Comment by mascguy** [comment]
> P. S. I have been told by others here that `platforms darwin` is a default option and does not have to be explicitly specified in a portfile. (I think the same applies to `use_parallel_build yes`.)

Correct on both counts, these can be removed.

**Review by mascguy — APPROVED** [review]

**Comment by jmroot** [comment]
@mascguy Please squash multiple commits at merge time when they're just fixups for a previous commit in the PR.

**Comment by mascguy** [comment]
> @mascguy Please squash multiple commits at merge time when they're just fixups for a previous commit in the PR.

Yep, completely zoned out on the commit messages, for this PR. Ditto for https://github.com/macports/macports-ports/pull/15448.

The 3rd time was the charm though, and did squash the commits for https://github.com/macports/macports-ports/pull/15449.

Yesterday was one of those days...  Lol

**Pull request merged**
