### PR TITLE
py-spyder-kernels[-devel]/py-corner/py-emcee: add py37 subports

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
- py-spyder-kernels/py-spyder-kernels-devel: add py37 subports
- py-corner: whitespace changes, add py37 subport
- py-emcee: add py37 subport, enable tests

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65
Xcode 10.0 10A255
Python 3.7

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`? only applicable for py-emcee
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
LGTM for `py-corner`.

**Comment by mojca** [comment]
I'm not maintainer of any of the ports, but it looks ok.

**Comment by lpsinger** [comment]
LGTM

**Comment by pmetzger** [comment]
Merged. Thanks as always, @reneeotten!

**Pull request merged**
