### PR TITLE
avidemux: update to 2.8.1, unbreak PowerPC

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Let’s see if this builds. I cannot check Qt5 build – but Qt4 works fine.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by kencu** [comment]
common issue with c++17 and VERSION file conflict with version header

**Comment by barracuda156** [comment]
> common issue with c++17 and VERSION file conflict with version header

Use `clang-14`? Or what should we do here?

**Comment by kencu** [comment]
usual fixvis to move or delete the VERSION file, depending on if the build actually uses it

**Comment by barracuda156** [comment]
@kencu Well, I am not really sure if it is used. Let us see if CI pass with `clang-14` to begin with; if the build itself works, then I will just go with your and @ryandesign suggestion on which fix is preferable.

**Comment by barracuda156** [comment]
Ok, `clang-14` fails likewise:
```
  In file included from /opt/local/libexec/llvm-14/bin/../include/c++/v1/new:91:
  In file included from /opt/local/libexec/llvm-14/bin/../include/c++/v1/cstddef:37:
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_multimedia_avidemux/avidemux/work/build_core/ffmpeg/source/version:1:1: error: expected unqualified-id
  4.4.2
  ^
  In file included from /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_core/src/ADM_cpuCap.cpp:13:
  In file included from /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_core/include/ADM_default.h:41:
  In file included from /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_core/include/ADM_assert.h:35:
  In file included from /opt/local/libexec/llvm-14/bin/../include/c++/v1/new:93:
  In file included from /opt/local/libexec/llvm-14/bin/../include/c++/v1/exception:84:
  In file included from /opt/local/libexec/llvm-14/bin/../include/c++/v1/type_traits:421:
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_multimedia_avidemux/avidemux/work/build_core/ffmpeg/source/version:1:1: error: expected unqualified-id
  4.4.2
  ^
```

**Comment by kencu** [comment]
> And distribution uses bundled archive of FFmpeg, so it is not easy to delete anything from it -_-

It would be unfortunate if it is impossible … but luckily, there is generally a way.

**Comment by barracuda156** [comment]
> it would have made no difference ifvit did or not, as we can’t use that “fix” anyway

Numerous ports have been fixed by a choice of specific compilers over years, and no one died :)
(But here it does not help.)

> haha… yes, you have been having some luck with that :)

I simply meant that I can follow your advice on what to choose. Since compiler-based solution does not work, there is no choice now.

> But still, people will have to come along later and do a proper fix, sooner or later.

That is what I am doing here by the way, after the port was broken for multiple systems (not just powerpc) for no reason whatsoever by an [unconditional switching to Qt5 support](https://github.com/macports/macports-ports/commit/f014af6823814551c4f5a7893199838095646084) instead of adding a few extra lines of code to support both versions of Qt (while the upstream maintains support for Qt4 up till now).

**Comment by kencu** [comment]
the compiler fix we accept is, generally, blacklisting older compilers, as you know…

**Comment by kencu** [comment]
OK, I thought I'd help with this. Starting out on 10.14, we get:

````
[ 63%] Building CXX object ADM_coreImage/src/CMakeFiles/ADM_coreImage6.dir/ADM_colorspace.cpp.o
cd /opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/build_core/ADM_coreImage/src && /opt/local/bin/ccache /usr/bin/clang++ -DADM_coreImage6_EXPORTS -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/build_core/config -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_core/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreAudioFilter/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreAudioParser/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreAudio/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreAudioDevice/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreAudioEncoder/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreDemuxer/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreDemuxer/include/unix -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreDemuxerMpeg/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreImage/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreMuxer/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreScript/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreUI/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreUtils/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreVideoEncoder/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreVideoFilter/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreVideoCodec/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreImageLoader/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreJobs/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreSocket/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreAudioCodec/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/build_core/ffmpeg/source -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/build_core/ffmpeg/build -Os -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1 -stdlib=libc++ -D__STRICT_ANSI__ -Qunused-arguments   -fsanitize=address -fno-omit-frame-pointer -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -std=gnu++11 -MD -MT ADM_coreImage/src/CMakeFiles/ADM_coreImage6.dir/ADM_colorspace.cpp.o -MF CMakeFiles/ADM_coreImage6.dir/ADM_colorspace.cpp.o.d -o CMakeFiles/ADM_coreImage6.dir/ADM_colorspace.cpp.o -c /opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreImage/src/ADM_colorspace.cpp
/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreImage/src/ADM_colorspace.cpp:640:16: error: non-constant-expression cannot be narrowed from type 'unsigned int' to 'int' in initializer list [-Wc++11-narrowing]
    int xs[4]={ADM_IMAGE_ALIGN(arg->srcWidth),0,0,0};
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

so let me try a newer compiler, and I'll see if I can get it building.

**Comment by kencu** [comment]
blacklisting {clang < 1101}, we get the version-related error. The conflcting file seems to be here:
```
./build_core/ffmpeg/source/VERSION
```
but as you say, it is decompressed during the actual build it appears, so not available to us to modify in a post-extract, patch, pre-configure, configure, post-configure, or pre-build phase, as far as it seems.

**Comment by barracuda156** [comment]
@kencu Thank you. What options in principle do we have? (Besides a silly one with unpacking the archive manually, deleting the file and either packing it back or modifying build config in a way it picks the unpacked one.)

From the commit history it seems no one bothered to address the error: https://github.com/mean00/avidemux2/commits/master/avidemux_core/ffmpeg_package (unless I missed something or it was buried in an unrelated commit).

**Comment by kencu** [comment]
when avidemux builds ffmpeg, it applies a fair number of patches from a patch directory in the avidemux source code.

It globs the list of the patches from the patch directory and just applies them all, so I have added a patch to remove the VERSION file to the list of patches that the build applies automatically.

So far, that seems to be working... the build is continuing past the usual failure point, anyway... will report back shortly on final outcome.

**Comment by kencu** [comment]
Ah, well ... it gets past the error with the VERSION file, but then trips up on the same error as before. At least we can build with a newer compiler now, but the build still doesn't finish even with clang-15:

```
[ 63%] Building CXX object ADM_coreImage/src/CMakeFiles/ADM_coreImage6.dir/ADM_colorspace.cpp.o
cd /opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/build_core/ADM_coreImage/src && /opt/local/bin/ccache /opt/local/bin/clang++-mp-15 -DADM_coreImage6_EXPORTS -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/build_core/config -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_core/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreAudioFilter/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreAudioParser/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreAudio/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreAudioDevice/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreAudioEncoder/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreDemuxer/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreDemuxer/include/unix -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreDemuxerMpeg/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreImage/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreMuxer/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreScript/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreUI/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreUtils/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreVideoEncoder/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreVideoFilter/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreVideoCodec/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreImageLoader/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreJobs/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreSocket/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreAudioCodec/include -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/build_core/ffmpeg/source -I/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/build_core/ffmpeg/build -Os -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1 -stdlib=libc++ -D__STRICT_ANSI__ -Qunused-arguments   -fsanitize=address -fno-omit-frame-pointer -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -std=gnu++11 -MD -MT ADM_coreImage/src/CMakeFiles/ADM_coreImage6.dir/ADM_colorspace.cpp.o -MF CMakeFiles/ADM_coreImage6.dir/ADM_colorspace.cpp.o.d -o CMakeFiles/ADM_coreImage6.dir/ADM_colorspace.cpp.o -c /opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreImage/src/ADM_colorspace.cpp
/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreImage/src/ADM_colorspace.cpp:640:16: error: non-constant-expression cannot be narrowed from type 'unsigned int' to 'int' in initializer list [-Wc++11-narrowing]
    int xs[4]={ADM_IMAGE_ALIGN(arg->srcWidth),0,0,0};
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by kencu** [comment]
```
$ git diff
diff --git a/multimedia/avidemux/Portfile b/multimedia/avidemux/Portfile
index 1e55f97c082..0bc6b9d60ac 100644
--- a/multimedia/avidemux/Portfile
+++ b/multimedia/avidemux/Portfile
@@ -3,6 +3,7 @@
 PortSystem                  1.0
 PortGroup                   cmake 1.1
 PortGroup                   app 1.0
+PortGroup                   compiler_blacklist_versions 1.0
 
 if {${os.platform} eq "darwin" && ${os.major} < 14} {
     PortGroup               qt4 1.0
@@ -46,6 +47,10 @@ patchfiles-append           0001-ADM_imageSave.cpp-add-missing-header.patch \
                             0002-ADM_coreUtils.h-fix-symbols-export.patch \
                             0003-Fix-missing-ADM_swap64.patch
 
+# remove VERSION file from ffmpeg source, that conflicts with newer compilers
+# that have a <version> header
+patchfiles-append           patch-avidemux-remove-VERSION.diff
+
 depends_build-append        port:bash \
                             port:gmake \
                             port:pkgconfig \
@@ -69,6 +74,8 @@ compiler.cxx_standard       2011
 
 cmake.set_cxx_standard      yes
 
+compiler.blacklist-append   {clang < 1101}
+
 configure.cxxflags-append   -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1
 
 configure.args-append       -DCMAKE_C_COMPILER=${configure.cc} \
```

and here's the patchfile:
[remove-version.patch](https://github.com/macports/macports-ports/files/12243961/remove-version.patch)

**Comment by kencu** [comment]
possibly upstream has already fixed this?
```
/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_multimedia_avidemux/avidemux/work/avidemux_2.8.1/avidemux_core/ADM_coreImage/src/ADM_colorspace.cpp:640:16: error: non-constant-expression cannot be narrowed from type 'unsigned int' to 'int' in initializer list [-Wc++11-narrowing]
    int xs[4]={ADM_IMAGE_ALIGN(arg->srcWidth),0,0,0};
```

if not, it will need to be fixed, perhaps with an explicit cast.

**Comment by kencu** [comment]
yeah, they have already fixed it here:

https://github.com/mean00/avidemux2/commit/65878cb39f3d9a2e51cb248cdab9724824f80558

**Comment by kencu** [comment]
OK, things are building away now and that last patch has fixed the narrowing error.

Blacklisting the older clang compiler does not appear required any longer. Just the two tiny patches will be needed.

No doubt upstream will find a similar way to remove the VERSION file themselves in due course, if they haven't already sorted something out.

I'll run some tests with the default clang on 10.14, which will probably work now with the patch, and with clang-16 and clang-15 to be sure they are happy, and report back when all that is done.

**Comment by kencu** [comment]
avidemux has updated their ffmpeg version to version 6.0.

ffmpeg version 6.0 does not have a VERSION file in it. So that will fix that, next time we update avidemux.

https://git.ffmpeg.org/gitweb/ffmpeg.git/tree/refs/heads/release/6.0

**Comment by barracuda156** [comment]
@kencu Awesome, thank you very much for helping with this!

**Comment by kencu** [comment]
whoa -- all three checks passed... better than we would have hoped.

OK -- there are likely to be build failures on the "in-between systems" ... 10.7 through 10.12 ... but we can't anticipate every one of those ahead of time, and I'm not going to build this on all those systems to find out. So... good enough.

**Pull request merged**
