### PR TITLE
py-torchtext: Update to version 0.15.2; Add Python 311

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mascguy** [comment]
Another PR wasting CI resources, and clearly not going to build successfully:

```
Warning: port lint py311-torchtext:
Error: Unknown dependency: py311-spaCy
Error: Unknown dependency: py311-pytorch
```

**Comment by essandess** [comment]
See:
* https://github.com/macports/macports-ports/pull/19712
* https://github.com/macports/macports-ports/pull/19967


The dependency chain for transformers is so convoluted there’s no other option but to submit these individually and just rebase as upstream dependencies are merged. There’s no way a huge multi-port PR will ever work.

**Comment by mascguy** [comment]
> The dependency chain for transformers is so convoluted there’s no other option but to submit these individually and just rebase as upstream dependencies are merged. There’s no way a huge multi-port PR will ever work.

Understood. But for PRs that are dependents on others, it would be good to both a) switch them to draft, and b) commit with `[skip ci]` to avoid wasted CI resources.

**Comment by pmetzger** [comment]
How do we move this forward?

**Comment by pmetzger** [comment]
Hi @essandess! It's been over a month and we haven't heard from you on this and the pull request doesn't pass the CI. Feel free to request the pull again if it passes the CI or there's a good reason it doesn't and a way to move forward.

**Pull request closed without merging**
