### PR TITLE
demeter, ifeffit: Add GitHub handle to maintainers

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

@joefowler This adds your GitHub handle to the `maintainers` line.

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] checked your Portfile with `port lint`?

### CODE REVIEW

**Comment by pmetzger** [comment]
Question: should it require maintainer approval to fix a maintainer line this way? I'd argue it probably shouldn't, since in many cases maintainers wouldn't be aware of things like pull requests involving their ports without the fix.

**Comment by mojca** [comment]
No, at some point we should simply mass-edit all the remaining ports for which we know the handles.

**Comment by pmetzger** [comment]
@mojca I agree with that. Given that, perhaps @ryandesign should just commit this and we should get a general policy ruling on the -dev list.

**Comment by ryandesign** [comment]
I don't know everybody's GitHub handle, nor do I wish to go to the effort of fixing everybody's portfile right now. I also want to wait on any mass edits to Portfiles until after distfile mirroring is working. I did learn Joe's handle, so I added it. As with any PR or ticket, Joe can give his approval, or if no response in 72 hours we can commit. He will be notified of this conversation because I tagged his handle in the PR description. There were recent admonishments on the mailing list about committing to other people's ports, even openmaintainer ones, and I am trying to practice creating PRs, hence this PR.

**Comment by pmetzger** [comment]
We don't and can't know everyone's github handle. However, I think it might be reasonable for us to clean up a bunch of things for which we do know them. However, this is best discussed on the list I think.

**Comment by joefowler** [comment]
I don't have an opinion on what the MacPorts policy should be about adding GitHub handles in general, but I am happy to approve of this patch, which adds my own handle to the ports I maintain (or, do my best to maintain).

**Comment by pmetzger** [comment]
Merged!

**Pull request merged**
