### PR TITLE
R: fourth batch of new R packages

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

New ports :)

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

macOS 10A190
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@herbygillot Is this size of PR fitting or should I drop some commits?

**Comment by herbygillot** [comment]
Looks good, but can you squash the "fix deps" commit into its original targets?

**Comment by barracuda156** [comment]
> Looks good, but can you squash the "fix deps" commit into its original targets?

Yes, sure, just wanted to confirm regarding the size prior to that.
I will rebase now.

**Comment by herbygillot** [comment]
Thanks @barracuda156

**Comment by szhorvat** [comment]
@barracuda156 Are you considering adding [igraph](https://cran.r-project.org/web/packages/igraph/), or if I add it, would you be willing to be co-maintainer?

**Comment by barracuda156** [comment]
> @barracuda156 Are you considering adding [igraph](https://cran.r-project.org/web/packages/igraph/), or if I add it, would you be willing to be co-maintainer?

@szhorvat Yes, I have it ready among some 250 other packages. I am adding those in small batches for technical reasons.

However, you are more than welcome to make a PR for it from your side (I have enough other packages to add), and yes, I can be a co-maintainer.
Also please add whichever other packages you are interested in. That will be great.

**Comment by barracuda156** [comment]
> @barracuda156 Are you considering adding [igraph](https://cran.r-project.org/web/packages/igraph/), or if I add it, would you be willing to be co-maintainer?

@szhorvat I actually need it for `shinystan` now, so went ahead adding it to the follow-up PR. I added you as a maintainer, hope you don’t mind that. (Besides, if you happen to have interest in any R ports that I have submitted, let me know, I add you as a co-maintainer too.)

**Pull request merged**
