### PR TITLE
hstr: update to 2.6.0

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
I hadn't updated the port because I noticed they hadn't posted a release tarball. I assumed they had forgotten to do so and would do so later, at which time I would update the port. But now it's been a few weeks and they still haven't. Do you know whether they have intentionally stopped publishing release downloads? (If so, can you point to where that's stated?) Otherwise, I would prefer that we file an issue with them asking them to publish the release download for 2.6.0 and then update to that and not switch to archive downloads.

**Comment by herbygillot** [comment]
Well there is a release, but it's pointing to the archive tarball ( https://github.com/dvorka/hstr/releases/tag/2.6 ). So I was thinking to just use archives for this version, and switch to release tarballs later when they become available.

But that said, I opened an issue: https://github.com/dvorka/hstr/issues/474

**Comment by herbygillot** [comment]
Updated to use the newly added release tarball for 2.6.0

**Comment by ryandesign** [comment]
`use_autoreconf yes` shouldn't be needed with the release tarball, right?

**Comment by herbygillot** [comment]
> 

Removed.

**Pull request merged**
