### PR TITLE
asciidoctor: update to ruby31, fixes PPC

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

This PR is motivated by fixing `asciidoctor` and `ccache` for PPC, where we currently have `ruby31`, but not `ruby30`.
If there are objections to updating `asciidoctor` to `ruby31`, there are two alternatives:

1. Update it only for ppc/ppc64, leaving everything else at `ruby30`.
2. Fix `ruby30` (possible, but a more painful option).

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
If there are objections to this from anyone, I can make fixes to ruby30 instead.

**Comment by pmetzger** [comment]
Can you resolve the conflicts and push?

**Comment by barracuda156** [comment]
> Can you resolve the conflicts and push?

Sure, will do today.

**Comment by barracuda156** [comment]
Fixed in: https://github.com/macports/macports-ports/commit/93b793acfebdc3fb04d6d2f2511d11192b16b7e6

**Pull request closed without merging**
