### PR TITLE
notmuch: Update to version 0.30

### PR DESCRIPTION
**Pull request by rseichter**
Feature release 0.30, see [upstream news](https://notmuchmail.org/news/).

### CODE REVIEW

**Comment by ryandesign** [comment]
Could we take this opportunity to update the port to use python38, since that's the latest stable version?

**Comment by rseichter** [comment]
I had actually considered switching this port to Python 3.8 myself. However, I did not know if it was OK to force users to update their Python version. I also thought about splitting Python 3.7 and 3.8 variants. My personal preference would be to switch to Python 3.8 and leave things at that.

**Comment by ryandesign** [comment]
I would say that ports should be updated to use the latest stable version of python wherever possible, and if you're already updating the version of the port that's a great time to include that change.

Variants could be offered but I wouldn't bother with that for now.

**Comment by rseichter** [comment]
I have updated the port to Python 3.8 and pushed the changes.

**Pull request merged**
