### PR TITLE
py-*: remove obsolete py26/py33 subports from various Python ports

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR contains a second round of housekeeping on various Python ports in the tree by removing obsolete py26/py33 subports.

In here is the first half of ports that (i) have a maintainer listed and (ii) have nothing depend on them. No other changes were made, so if a port doesn't build it should not be caused by this PR.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65
Xcode 9.4.1 9F2000

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
In requested commits can be squashed, right now there is one commit per port.
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by blair** [comment]
LGTM for py-couchdb and py-couchdbkit.

**Comment by jmroot** [comment]
No thanks, I'll drop support in mine when upstream does. Also, the whole point of the backports modules is that they are for old python versions.

**Comment by yan12125** [comment]
> Also, the whole point of the backports modules is that they are for old python versions.

Is there a point to keep unsupported Python versions? Even for the latest Python 3.7, upstream supports as old OS X as 10.6 [1], and MacPorts supports 10.5 [2].

[1] https://www.python.org/downloads/release/python-370/
[2] https://packages.macports.org/python37/

**Comment by jmroot** [comment]
Mostly the point is to allow testing code with older versions, which are still in use elsewhere for various, mostly non-technical, reasons. (You'd be surprised for how long sometimes.)

Obviously we should discourage use of versions that are no longer getting security updates, and ports of python-using apps shouldn't use them.

**Comment by mojca** [comment]
@jmroot: then let's prepare the exact list of ports that need to keep support for old versions, and remove everything else.

**Comment by g5pw** [comment]
👍 LGTM for `py-chronic` and `py-colorama`. For the record, I'm against keeping packages for unsupported Python versions. We keep `py-virtualenv` and `pip` around for testing code for old versions. I wouldn't want users to install packages for old, unsupported Python versions.

**Comment by jmroot** [comment]
> We keep py-virtualenv and pip around for testing code for old versions.

Apparently not: be83b67

**Comment by yan12125** [comment]
> We keep py-virtualenv and pip around for testing code for old versions.

I would propose changes to the convention/policy. Dedicated projects like [pyenv](https://github.com/pyenv/pyenv) and [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv) are more suitable than system package managers like MacPorts for testing purposes.

**Comment by reneeotten** [comment]
@jmroot sure, that's why PRs are for - to see if the maintainer agrees with proposed changes. So I will drop the commits affection your ports and will not touch those anymore in the future.

For some reason GitHub didn't notify me of the comments you left on be83b67, so that's why I didn't respond there. Do I understand it correctly that the (previous) consensus was that ```pyXY-{setuptools,pip,virtualenv}``` should stay for all Python versions that are still available in MacPorts? (I removed py26 from ```py-virtualenv``` because upstream doesn't support it anymore with the latest version, but if needed that can be pinned to an earlier release.) 

I am certainly fine with keeping these ports around for people who need to test old Python versions, but would prefer to remove all traces from EOL Python versions elsewhere (both in py?? subports as well as in variants for other things that rely on Python). Regarding the backports modules, if ```pyXY-{setuptools,pip,virtualenv}``` are kept around they can be installed from other sources than MacPorts and could be removed, agreed?

**Comment by pmetzger** [comment]
@jmroot:

> No thanks, I'll drop support in mine when upstream does. Also, the whole point of the backports modules is that they are for old python versions.

Python 2.6 and 3.3 are no longer supported upstream. I think we have widespread consensus that we're removing support for them. There is little to no point in keeping them around, either, since the differences vs. 2.7 and higher versions of 3 are quite minimal.

**Comment by michaelld** [comment]
LGTM for py-cheetah

**Comment by pmetzger** [comment]
> Do I understand it correctly that the (previous) consensus was that pyXY-{setuptools,pip,virtualenv} should stay for all Python versions that are still available in MacPorts?

I don't think that's consensus. At least, I don't think that's consensus.

**Comment by gorticus** [comment]
ACK for `py-ftputil`

**Comment by jjstickel** [comment]
No objections from me.

**Comment by elelay** [comment]
OK for py-eyed3 and py-mutagen.
Thanks,

**Comment by jmroot** [comment]
> Do I understand it correctly that the (previous) consensus was that pyXY-{setuptools,pip,virtualenv} should stay for all Python versions that are still available in MacPorts?

Yes.

> I am certainly fine with keeping these ports around for people who need to test old Python versions, but would prefer to remove all traces from EOL Python versions elsewhere (both in py?? subports as well as in variants for other things that rely on Python). Regarding the backports modules, if pyXY-{setuptools,pip,virtualenv} are kept around they can be installed from other sources than MacPorts and could be removed, agreed?

Sure, that works for modules for which all dependencies can be installed with pip.

**Comment by pmetzger** [comment]
I'm having difficulty tracking which subset of maintainers have approved the changes vs. who actually needs to approve because their ports aren't `openmaintainer`. At worst we can merge in 48 hours from now.

**Comment by reneeotten** [comment]
okay, I dropped the commits for the following ports maintained by @jmroot (py-SDL2, py-bdist_mpkg, py-dice3ds). 

@pmetzger: these subports have been there for years probably so there is no real rush to merge ;) Here is an overview, still awaiting comments for the following ports most of which are openmaintainer.

@astrofrog for port py-idlsave [not openmaintainer], py-montage
@jfcaron3 for port py-PyRSS2Gen
@jwhowarth for port py-minfx [not openmaintainer]
@seanfarley for port py-cycler, py-generator, py-lz4
@nerdling for port py-elementtree, py-igraph, py-mustache 
@Ionic for port py-distutils-extra 
@esafak for port py-isodate [not openmaintainer]
@drkp for port py-fuse
@stromnov for port py-babel, py-backports-ssl_match_hostname, py-backports_abc, py-cogen, py-deap, py-ecdsa, py-freeling, py-gevent, py-hat-trie, py-hiredis, py-iso8601, py-jug, py-kivy, py-kyotocabinet, py-lepl, py-macfsevents, py-meta-devel, py-meta, py-milk, py-msgpack, py-multipledispatch

**Comment by esafak** [comment]
+1 for py-isodate

**Comment by pmetzger** [comment]
Merged. Thank you as always, @reneeotten.

**Pull request merged**
