### PR TITLE
MacVim: disable sparkle auto update

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by raimue** [comment]
That means the patch alone was not enough? Or why is that now necessary?

**Comment by i0ntempest** [comment]
Apparantly your patch modified the xib files to remove the entry to check update, but today installed MacVim, launched it a few times (twice maybe) and got a popup asking if I want automatic updates. So I think Sparkle is still there? Removing the appcast URL from Info.plist will render the updater completely useless.

**Comment by thomasnyman** [comment]
Was this the actual updater prompt or the new "What's New"  pane which was added in r177?

image

Commit 35198990c3630519d6356ad3232a0d6176971162 disables the menu entry for the new pane, but I believe it can still be displayed once after updating the port from r176 to r177.

**Comment by raimue** [comment]
You are right, we are removing the UI for the updater. In the past it was possible to remove Sparkle completely from the build, but that gets complicated to maintain over time.

The solution to remove the URL from the Info.plist seems reasonable. Let's go with this.

**Pull request merged**
