### PR TITLE
fswatch: add git dependency

### PR DESCRIPTION
**Pull request by kencu**
closes https://trac.macports.org/ticket/55173

### CODE REVIEW

**Comment by kencu** [comment]
@emcrisostomo - please review. Sorry about going ahead with the last commit without waiting for you to review that one. Let me know if any issues of concern.

**Comment by emcrisostomo** [comment]
Hi @kencu,

it's fine, thanks for fixing it. I'm going to remove this dependency in the next release because it's only required by the maintainer and it shouldn't have crept to the release tarball.

**Comment by kencu** [comment]
Good to know. Your portfile is now very simple, neat & tidy. Should be easy to maintain. Thanks for keeping your build system so clean.

**Comment by emcrisostomo** [comment]
Thanks!

**Pull request merged**
