### PR TITLE
grass7: fix trac issues

### PR DESCRIPTION
**Pull request by nilason**
#### Description

This PR addresses two trac issues:

**_Upgradability_**

Fixes bug introduced with update to 7.8.3, making upgrading fail.

https://trac.macports.org/ticket/60445

**_python34 variant_**

Removes the python34 variant, see https://trac.macports.org/ticket/59953, which depends on sub-ports that have been removed.

```
$ port lint grass7 +python34
--->  Verifying Portfile for grass7
Error: Unknown dependency: py34-Pillow
Error: Unknown dependency: py34-numpy
Error: Unknown dependency: py34-psycopg2
--->  3 errors and 0 warnings found.
```

See also comment on original commit:
https://github.com/macports/macports-ports/commit/216ccac434fb61d04a79762b82d3059c96d75c63#commitcomment-36480013
and subsequent reply by original author.

I'm not sure, should I bump revision too with this?

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6
Xcode 10.2.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by Veence** [comment]
What the heck? Why do I have a version different from yours?

**Comment by nilason** [comment]
> What the heck? Why do I have a version different from yours?

@Veence I'm not sure what you mean. But here's what have happened:

For the 7.8.3 upgrade commit https://github.com/macports/macports-ports/commit/591997f9170e64303c77db087bfe839213d9dd25 due to changes in `Install.make` I remade the patch and accidentally missed one line, which lead to trac issue [60445](https://trac.macports.org/ticket/60445), rendering upgrade failure (but not install failure). I then put up this PR, which at that point remained unmerged.
With your commit https://github.com/macports/macports-ports/commit/9c8b20efc17d155768e638df3c9a63eeda7618d8, you accidentally (again!) introduced another, even more critical issue [trac 60466](https://trac.macports.org/ticket/60466).
Your commit was then reverted and this PR was merged.

**Comment by Veence** [comment]
Hi! Okay, I mean thanks a lot for getting involved while I was mainly absent due to the current Covid crisis. What I do not understand is why the patch I committed works for me and not for you…

**Comment by nilason** [comment]
Aha, at the head of your patch-file there is the

```
 --- Install.make.orig	2020-05-10 13:10:50.000000000 +0200
 +++ Install.make	2020-05-10 13:12:43.000000000 +0200
```
should have been:

```
 --- include/Make/Install.make.orig	2020-05-10 13:10:50.000000000 +0200
 +++ include/Make/Install.make	2020-05-10 13:12:43.000000000 +0200
```

And I thank You for the tremendous work you're doing with the various GIS ports!

**Comment by Veence** [comment]
Jeez. I overlooked this. Thanks so much for putting out the blaze! :)
And also, you’re quite welcome. Thanks for helping when I botch things up!

**Pull request merged**
