### PR TITLE
xorg-server: Update to 1.20.4

### PR DESCRIPTION
**Pull request by cjones051073**
#### Description

Updates (the currently quite outdated) xorg-server to 1.20.4.

Note, the 1.20.x series has been available as per the `xorg-ser-devel` port for some time now. I have been using it exclusively on a number of machines and not seen any issues. So I believe it stable enough for mainstream now, and updating fixes a number of CVEs against the current old version we are shipping.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [x] security fix

###### Tested on

macOS 10.14.3 18D109
Xcode 10.1 10B61 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
@macportsbot retry

**Comment by pmetzger** [comment]
@cjones051073 Azure pipelines failed?

**Comment by cjones051073** [comment]
Yeah, but what is actually going wrong with these tests ? 

I know the version builds fine as part of the `xorg-server-devel` port, which is building exactly the same as this proposed update. A couple platforms failed, but these are for issues w.r.t. the build bots (e.g. fails due to disk space issues) not the port itself. So I am not sure what to make of the travis/azure failures.

**Comment by cjones051073** [comment]
e.g. look at 1.20.4 builds at

http://packages.macports.org/xorg-server-devel/

Three builds are missing. Darwin 11 failed because of missing dependencies (which are because of previous builedbot failures due to disk space issues, with clang). Likewise, Darwin 10 i386 failed because of a missing dependency. Darwin 9 PPC buildbot is just offline so hasn't got around to it yet, I think.

In addition 1.20.3 built fine for all platforms.

**Comment by cjones051073** [comment]
After much poking around in the logs, I see the azure builds fail with

```
2019-03-18T23:46:58.9707010Z Installing dependency (158 of 170) 'font-misc-ethiopic' with variants '' (requesting '') ... [FAIL]
```

This is the same dependency failure I saw affecting the Darwin10 i386 buildbot. Its thus not an issue with the port itself.

**Comment by cjones051073** [comment]
Turns out the azure issue was a missing dependency in a dependent port, font-misc-ethiopic. Now added and azure build has passed. Have restarted travis builds to see if they are affected by the same issue.

**Comment by cjones051073** [comment]
travis builds are still timing out. Looking again at the azure build it took 55mins, so perhaps the 50min timeout in travis is real. It surprises me it takes that long (the actual build of the port takes minutes) but perhaps for some reason installing all the deps takes a while. if so, it really makes the travis builds somewhat useless I would say as the number of reps here is not that long...

**Comment by pmetzger** [comment]
I only pay attention to the Azure Pipelines builds myself. I'd suggest you commit this; it is now building properly.

**Comment by pmetzger** [comment]
(Or I can, but I don't have a lot of time at the moment.)

**Comment by cjones051073** [comment]
Ideally I would like @jeremyhu's opinion on this, but he tends not to comment often, and I also don't think we need to update this port sometime....

**Comment by jeremyhu** [comment]
I have no problem with someone making this bump as long as they’ve tested it on at least a few different versions of the OS.  XQuartz itself hasn’t changed other than a few bugs I fixed over the past ~5 years, so only DIX changes are related here (which *should* be fine).

**Comment by cjones051073** [comment]
Thanks for the feedback. I have been using it via the devel port on my two main machines regularly (most days). These machines are kept up to date, so currently 10.13 and 10.14 but previously older OSes.  I also have used it on a collection of VMs i have going back to 10.6, which i only use for macports testing, and not seen any problems there either. Of course, I can only comment on the usage of X11 I have tried, which is the normal multi window mode, displaying applications running either locally or remotely over ssh. It is of course impossible to test all possible applications with it that users might be running, so at some point we just merge and see if anything comes up i think.

**Comment by kencu** [comment]
I confirm it is building and working well right back to 10.4 PPC Tiger, and on every system I have.

**Pull request merged**
