### PR TITLE
adblock2privoxy: Update to version 2.1.1; Add proxy_settings variant

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.1.1 23B81 arm64
Xcode 15.0.1 15A507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by essandess** [comment]
The build failures appear to be CI related. I do not observe any issues on either x86_64 or arm64 machines.

**Comment by reneeotten** [comment]
> The build failures appear to be CI related. I do not observe any issues on either x86_64 or arm64 machines.

It seems unable to find file(s); that seems like a problems. Ports need to be able to install in a clean environment like the CI. 

Please take another look. I doubt you build it locally in trace-mode as that is currently not working.

**Comment by essandess** [comment]
> It seems unable to find file(s); that seems like a problems.

@reneeotten Thanks. It appears that the issue is at the activation stage, where a block of openssl commands is run to generate a baseline working PKI. There is a new issue with `openssl` version 2.3 that causes the `openssl req` command to fail: https://github.com/openssl/openssl/issues/22966.

Because this PR is necessary to fix an issue building with the latest package base version, I'll fall back to openssl-1.1 in the Portfile and we can go back to the latest openssl version when this issue is resolved.

Please note this will affect other ports (`privoxy`, `mail-server`) that must generate example PKI at activation.

**Comment by pmetzger** [comment]
Unless the CI passes, we cannot merge a pull request.

**Comment by essandess** [comment]
I'm going to modify the new `proxy_settings` logic to capture existing environment variables.

**Comment by essandess** [comment]
This is ready to merge as soon as the CI builds.

**Comment by pmetzger** [comment]
OpenSSL 1.1 is no longer supported. We should not move new ports to it.

**Comment by essandess** [comment]
> OpenSSL 1.1 is no longer supported. We should not move new ports to it.

We’re not. We’re just using the last working version of OpenSSL until issue https://github.com/openssl/openssl/issues/22966 is resolved.

Furthermore, the latest versions of OpenSSL do not create PKCS12 files that can be imported into either macOS or iOS keychains, so we all have an implicit dependency on OpenSSL 1.1.

**Comment by essandess** [comment]
The draft OpenSSL 1.1 dependency is now removed. The underlying issue was not with OpenSSL v. 3.2, but the CSR command that included an unnecessary (and now incorrect) `-extensions`, now fixed.

**Pull request merged**
