### PR TITLE
webkit2-gtk: bump to 2.26.1

### PR DESCRIPTION
**Pull request by kencu**
adjust patches
gtk2 support is now gone
currently builds and runs on Mojave +x11

Please help! Needs testing on:

1. all other system versions
2. with +quartz variants
3. any ideas or bugfixes for the intermittent page load failures (also noted with previous version)

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G103
Xcode 11.1 11A1027 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
So please no style nits just yet. I'm hoping for some help getting as many people as there are interested to try building this on your systems and report back success/failure, what you had to do to get it to work properly, how it worked +quartz.

We'll polish it to a fine gloss once we have it shaped up better, but it's a huge port with a lot of system variations to try and I would appreciate anyone interested to chime in.

**Comment by dbevans** [comment]
Thanks, running test builds overnight.

**Comment by yan12125** [comment]
Awesome! I'd like to test +quartz, but there are way too many binary-distributable packages still on the queue (https://build.macports.org/waterfall?tag=10.14). I will test this after the queue is cleared. Currently waiting on `rust @1.38.0_1` for building `librsvg +quartz`.

**Comment by kencu** [comment]
The < 10.13 blockers will need to be adjusted a bit. `ENABLE_SUBTLE_CRYPTO` has had a name change,  I think it was to `ENABLE_WEB_CRYPTO`  And I think at least some of the patches will need to be re-enabled for +quartz. Yan did all the magic on that last time we did this.

**Comment by kencu** [comment]
Well three systems built, anyway! Is the first one (macports.macports-port) 10.15? 

I'm finding I've had to add back most of the patches, one by one, for 10.6.8, so I guess many of them will still be needed for the older systems...

**Comment by dbevans** [comment]
Built +x11 on 10.15 last night 

```
MacPorts 2.6.1
macOS 10.15 19A583 (release)
Xcode 11.1 11A1027 (release)
Command Line Tools for 11.0 (release)
```

and tested with  devhelp, empathy, epiphany, liferea and yelp.  All worked fine with only one deprecation issued in epiphany which should hopefully go away on update since it involves a security issue.

`** (epiphany:93946): WARNING **: 10:51:26.129: webkit_web_context_set_web_process_count_limit is deprecated and does nothing. Limiting the number of web processes is no longer possible for security reasons`

In particular, the embedded videos in yelp under the Getting Started heading work well. Will defer the +quartz build and testing for now since others are looking at this and have personal issues. 

I plan to go ahead and update the apps mentioned above to current levels and see if I run into anything there.

Recommended changes so far:

* webkit2-gtk now depends on enchant2 rather than the older enchant.
* revert livecheck to its previous version so that only updates on the current stable branch are displayed. Leave the unlimited version for -devel.
* add @kencu as co-maintainer, if he is willing, due to his expertise on the older platforms.

**Comment by kencu** [comment]
thanks Dave!

**Comment by kencu** [comment]
This MacTypes.h business is a headache. I wonder if we could wrap the MacTypes.h call in a sanitizer wrapper like they do in xorg-server or fontforge to keep it manageably sane.

**Comment by dbevans** [comment]
> This MacTypes.h business is a headache. I wonder if we could wrap the MacTypes.h call in a sanitizer wrapper like they do in xorg-server or fontforge to keep it manageably sane.

Ok by me if you can get it to work.

**Comment by kencu** [comment]
OK. Just about done, except for the `+quartz` builds.

```
$ port -v installed webkit2-gtk
The following ports are currently installed:
  webkit2-gtk @2.26.1_0+x11 (active) platform='darwin 10' archs='x86_64' date='2019-10-15T20:42:57-0700'
```

**Comment by dbevans** [comment]
> OK. Just about done, except for the `+quartz` builds.
> 
> ```
> $ port -v installed webkit2-gtk
> The following ports are currently installed:
>   webkit2-gtk @2.26.1_0+x11 (active) platform='darwin 10' archs='x86_64' date='2019-10-15T20:42:57-0700'
> ```

Great.  I'm pulling a new copy to rebuild now.  I've been updating dependents as promised.  Only difficulty so far is that latest epiphany needs glib2 >= 2.61.2.  So that's my priority. I've got a version that is 80% complete and will post a PR for @ryandesign that he can review as soon as I finish up the last meson bits.

**Comment by kencu** [comment]
Yeah -- upstream has done something to fix the JIT on 10.6.8, so it's super-snappy now :>

If I could get rid of those random page-load errors, this would be the current browser of choice for all systems < current macOS.

**Comment by kencu** [comment]
and more happiness, at least on 10.13:
```
$ port -v installed | grep webkit2-gtk
  webkit2-gtk @2.26.1_0+minibrowser+quartz (active) platform='darwin 17' archs='x86_64' date='2019-10-17T09:47:53-0700'
```

Screen Shot 2019-10-17 at 9 50 11 AM

**Comment by kencu** [comment]
Well this is getting pretty close to a final cleanup, stripping out the unused patches, and then committing it and letting the buildbots have their way with it. I'll do that final cleanup today.

There **will** be some ```+quartz``` issues that come up with older systems related to `MacTypes.h` name collisions, but we'll have to take those on as we find them I think. My current thought on how to most efficiently manage that is to make a new directory in the `webkit2-gtk` source tree, and put a header named `MacTypes.h` in there that sanitizes the name collisions prior to calling the real `MacTypes.h` with `#include_next`, and then unsantizes after. We can add a line to the top-level `CMakeLists.txt` to prepend this folder as a system include folder for the whole project. Then -- if we're lucky -- no more name collisions from the global namespace. At least in theory sounds good. Other projects do this (e.g. fontforge, as I mentioned above).

**Comment by kencu** [comment]
Hah -- webkit2-gtk in epiphany sometimes does a better job rendering pages than does Safari -- who would have thought? This is Safari on the left, epiphany on the right.

Screen Shot 2019-10-17 at 10 12 14 AM

**Comment by kencu** [comment]
This is looking pretty good, but now I'm running into some new uber-strictness from clang-9.0 pulling in some conflicting definitions from the global namespace in MacTypes.h that clang-5.0 allows to slip by without generating an error. Sigh.

**Comment by dbevans** [comment]
@kencu Just to confirm that +quartz +minibrowser builds and runs without problems on Catalina with the exception that the +minibrowser variant needs an additional runtime dependency on adwaita-icon-theme to ensure that icons display properly.  I'm ok with merging the PR at this point but will leave it to your discretion due to your ongoing issues. Will continue to test with upgraded dependents.

**Comment by dbevans** [comment]
Oops!  Also need to remove "with optional support for GTK+2 plugins" from the description.

**Comment by dbevans** [comment]
> Oops! Also need to remove "with optional support for GTK+2 plugins" from the description.

Fixed in your latest update.  BTW I agree that setting +minibrowser as a default, at least in +quartz, is a good idea as it's about the only way to easily test there. Rebuilding with new update.

**Comment by ewenmcneill** [comment]
By way of cross references, see also [MacPorts Trac 59387](https://trac.macports.org/ticket/59387) (for the older `webkit2-gtk` `2.20.5_1`), where there may now (since the `icu` update to 65.1) need to be another patch added to `webkit2-gtk` to work around `U16_NEXT` macro changes.  I believe the [upstream patch](https://gitlab.gnome.org/GNOME/jhbuild/commit/e8b48870602c3a8e474e54cf1c6151b98651aae9) was merged to `webkit` `master` a week ago, but probably isn't in 2.26.1 (which was [released about three weeks ago](https://webkitgtk.org/2019/09/23/webkitgtk2.26.1-released.html)).  It's a pretty small patch though so hopefully is easy to add here.

(At a guess that `icu` 65.1 Portfile update (https://github.com/macports/macports-ports/commit/8cf9b206c3c2fcca0e0f6ee2a46f47bc828a3cb7) is probably the conflict currently showing as needing to be resolved.)

Ewen

**Comment by dbevans** [comment]
> By way of cross references, see also [MacPorts Trac 59387](https://trac.macports.org/ticket/59387) (for the older `webkit2-gtk` `2.20.5_1`), where there may now (since the `icu` update to 65.1) need to be another patch added to `webkit2-gtk` to work around `U16_NEXT` macro changes. I believe the [upstream patch](https://gitlab.gnome.org/GNOME/jhbuild/commit/e8b48870602c3a8e474e54cf1c6151b98651aae9) was merged to `webkit` `master` a week ago, but probably isn't in 2.26.1 (which was [released about three weeks ago](https://webkitgtk.org/2019/09/23/webkitgtk2.26.1-released.html)). It's a pretty small patch though so hopefully is easy to add here.
> 
> (At a guess that `icu` 65.1 Portfile update ([8cf9b20](https://github.com/macports/macports-ports/commit/8cf9b206c3c2fcca0e0f6ee2a46f47bc828a3cb7)) is probably the conflict currently showing as needing to be resolved.)
> 
> Ewen

Yes, I've confirmed empirically that the problem stems from the icu update.  After rolling back to the previous version of icu, this PR builds without problems.  The problem seems not to be with respect to the U16_NEXT macro itself but the fact that there is no semi-colon terminating the statement (compare to other uses of the macro throughout the code).  However, the problem is not in the initial source file
but in the derived source file generated from it.  Haven't been able yet to understand the exact mechanism for the faulty generation of the derived source but it does seem to be related to the icu update.  Any further insights into what's going on here is appreciated.

**Comment by dbevans** [comment]
BTW, the merge conflict in Portfile that has appeared is a by product of the icu update as well, caused by the revbump of the old port and is easily resolved.

**Comment by ewenmcneill** [comment]
>  The problem seems not to be with respect to the `U16_NEXT` macro itself but the fact that there is no semi-colon terminating the statement (compare to other uses of the macro throughout the code)

Yes, it looks like just some missing trailing semicolons which are now required.

FWIW, my expectation (without looking in depth) is that the `U16_NEXT` macro changed between `icu` 58.x and 65.1 so that a semicolon was *not* previously *required*, to a form where it is now required.  Typically that's where the macro was written such that it was, eg, a stand alone block (eg, inside { }).  In that case any trailing semicolon would become an empty statement ("`;`") that was then discarded by the compiler.  Presumably with `icu` 65.1 `U16_NEXT` has a form where it does expect a trailing semicolon, maybe a function call or similar without the semicolon included in the macro definition (which is the convention for macro definitions that aren't blocks in braces).

So before the semicolon was optional, and now it is required.  Presumably previously most uses of `U16_NEXT` did have semicolons anyway.

It does seem odd that the problem doesn't exist in the original source file but does exist in a derived file.  Sorry I don't have any details on the mechanism causing that.  But FTR the upstream patch (to `webkit` for the new `icu`) does patch `WebCore/dom/Document.cpp` directly, so my assumption is that is what needs fixing for the MacPorts build  (I did notice during build that the error is reported in something else that apparently includes `dom/Document.cpp`.)

Thanks for looking into it.

Ewen

PS: I agree the best path forward is to get this new version building again and merge that in.  There doesn't seem any point putting in work to make the old (2.20.x) version build again since this PR to update to 2.26.x is so close to ready.

**Comment by kencu** [comment]
OK; here's hoping that this is it. The new icu patch from gnome applies cleanly. I ran into a little rebasing hiccup that I think I `git-fu'd` properly. It's running against the new ICU here.

I whitelisted macports-clang-5.0; it's the only compiler I know works on 10.6.8, and clang-9.0 failed. I though we might get this in, hopefully clang-5.0 would build it across the spectrum of older systems, and then if motivated, we can broaden out  the compiler choices if we get some time to build this behemoth against clang 6, 7, 8, devel.

**Comment by kencu** [comment]
OK Dave!! Here we go!

**Comment by dbevans** [comment]
> OK Dave!! Here we go!

Great!  Rebuilt overnight and all looks good on Catalina. Thanks for taking the lead on this one, I really appreciate it.  I still think you ought to add yourself as a maintainer.

**Comment by yan12125** [comment]
Sorry my Macbook is slightly broken the last week. Kudos to Ken!

**Pull request merged**
