### PR TITLE
github-1.0.tcl: fix curly bracket

### PR DESCRIPTION
**Pull request by ra1nb0w**
#### Description

fix curly bracket

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.15 19A602
Xcode 11.1 11A1027

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ra1nb0w** [comment]
thank you and sorry for the mistake!

**Comment by ryandesign** [comment]
This change is wrong. Please revert or explain why it was made.

**Comment by ra1nb0w** [comment]
Because otherwise `port info` result for port with github homepage is like as follow (not resolved)
```
Homepage:             ${github.homepage}
```
`homepage` manualy setted works fine.

See also https://github.com/macports/macports-ports/commit/958e5487a2477f38ed164bf2e196fa8cea70c457

**Comment by ryandesign** [comment]
Hm. Ok. In this specific case, this is ok, because it is not expected that ports would override the value of `${github.homepage}`. However in general the value supplied to `default theOptionName` must be enclosed in curly brackets so that it is evaluated later (after a port has potentially changed the values of the variables referenced), rather than immediately.

**Comment by ra1nb0w** [comment]
I got it. Thank you!

**Pull request merged**
