### PR TITLE
py-pyqtgraph:  add py34 and py35 subports to py-graveyard

### PR DESCRIPTION
**Pull request by jjstickel**
- [x] bugfix

Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Thanks, @jjstickel!

**Comment by jjstickel** [comment]
I wasn't sure of the version number to use for the subports that went in py-graveyard. I used the last version number that had those subports (not the new updated version). Is that correct?

**Comment by pmetzger** [comment]
I am not sure that is correct, actually. @mojca?

**Comment by pmetzger** [comment]
(And probably a comment in the py-graveyard Portfile should explain such things...)

**Comment by mf2k** [comment]
You need to increase the revision by 1 so people with the port installed see the change. So the version should be changed to `0.9.10_1`.

**Comment by pmetzger** [comment]
@jjstickel Okay, submit again and I'll merge again. Could you also add some documentation comments to the Portfile so this is easier for the next person?

**Comment by jjstickel** [comment]
Ugh, this is annoying. Can one of you developers just add the two characters "_1"? Also some comments about how to use py-graveyard because it is not intuitive. I won't do that part because it is above my "pay grade" (well, volunteer status).

**Comment by pmetzger** [comment]
(And don't worry about it being above your pay grade, someone will tell us if there are any mistakes and I'll edit it.)

**Comment by mojca** [comment]
This change was problematic for several reasons:
* First of all, it doesn't actually do anything because the revision was too low anyway
* Second, we did not yet start deprecating `py35` subports. If we start deprecating random subports, we'll run into troubles because other ports might still need a dependency on `py35`. We should in the future ideally try to deprecate one version of python at once. This port doesn't seem to have any dependent ports, but in general doing this might sooner or later lead to unexpected consequences. It's ok if we remove all traces of python 3.5, but not if we do it just for a subset of ports.
* Our graveyard port is problematic because it would replace py33 with py34, while it would replace py34 with py35, and then py35 with py36. So we end up with double or triple redirects.

I'll send this to the developer mailing list, but just for the sake of the near future ... can we please *not* remove py35 just yet?

**Comment by mf2k** [comment]
I reinstated py35 and increased the revision in the graveyard. 

https://github.com/macports/macports-ports/commit/355ca641350637f63133056f4ba8b3fca9fa624c

**Comment by jjstickel** [comment]
@mf2k, thanks. It would have taken me a few days.
@mojca, please add general comments to py-graveyard explaining its use, related to your comments above. There are currently no instructions and I did **not** find it intuitive.

**Pull request merged**
