### PR TITLE
auto-multiple-choice-devel: update to version 1.5.0-rc1

### PR DESCRIPTION
**Pull request by nortcele**
auto-multiple-choice-devel: update to version 1.5.0-rc1

• Update to 1.5.0-rc1-6-g83952a21
• Reorganize port to use pre-compiled sources with embedded
  documentation to avoid missing font errors during build.

Close https://trac.macports.org/ticket/55802
Close https://trac.macports.org/ticket/58936

#### Description
The new portfile update auto-multiple-choice-devel to version 1.5.0-rc1-6-g83952a21.

Working with auto-multiple-choice' developer, the new version of the portfile is modified to use pre-compiled sources with documentation already generated. This greatly simplify the build and reduce build errors.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on (standard and devel versions)

macOS 11.2 20D64
Xcode 12.4 12D4e 

macOS 11.1 20C69
Xcode 12.4 12D4e 

+mactex
macOS 10.15.7 19H114
Xcode 12.4 12D4e 

macOS 10.14.6 18G7016
Xcode 11.3.1 11C504 

macOS 10.13.6 17G14042
Xcode 10.1 10B61 

macOS 10.12.6 16G2136
Xcode 9.2 9C40b 

macOS 10.11.6 15G22010
Xcode 8.2.1 8C1002 

macOS 10.10.5 14F2511
Xcode 7.2.1 7C1002 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
nice testing effort, thanks!

will merge after CI has built it.

**Comment by nortcele** [comment]
I made errors in the description.
Test on 10.10.5 failed.
Test on 11.2 is in progress. I've just updated to 11.2 and a lot of depencies still need to be build form sources.

**Comment by nortcele** [comment]
As usual CI fail with a timeout. Too many dependencies.

**Comment by nortcele** [comment]
Phew, it's over. Installation and tests on 11.2 went fine for auto-multiple-choice and auto-multiple-choice devel.

**Comment by kencu** [comment]
The CI system has stroked out again. This is your port to maintain, you tested it as much as anyone could -- let's go with this.

**Pull request merged**
