### PR TITLE
apache-arrow: Fix checksum

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Review by reneeotten — CHANGES_REQUESTED** [review]
@essandess why did the checksums change; did you verify the changes between the two archives? Since there is no change in the `version`, this should likely be treated as a [stealth update](https://trac.macports.org/wiki/PortfileRecipes#stealth-updates)

**Comment by mascguy** [comment]
> @essandess why did the checksums change; did you verify the changes between the two archives? Since there is no change in the `version`, this should likely be treated as a [stealth update](https://trac.macports.org/wiki/PortfileRecipes#stealth-updates)

Based on a quick local test, the checksums do appear to have changed:

```
$ sudo port -v checksum apache-arrow
--->  Fetching distfiles for apache-arrow
--->  Attempting to fetch arrow-8.0.0.tar.gz from https://codeload.github.com/apache/arrow/legacy.tar.gz/apache-arrow-8.0.0?dummy=
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16.9M    0 16.9M    0     0  2757k      0 --:--:--  0:00:06 --:--:-- 4392k
--->  Verifying checksums for apache-arrow
--->  Checksumming arrow-8.0.0.tar.gz
Error: Checksum (rmd160) mismatch for arrow-8.0.0.tar.gz
Portfile checksum: arrow-8.0.0.tar.gz rmd160 b10d2a50b39966e70dc611b36fb4de1900914640
Distfile checksum: arrow-8.0.0.tar.gz rmd160 37c669b5c80b034f58ecdafe7fa4476e041255a6
Error: Checksum (sha256) mismatch for arrow-8.0.0.tar.gz
Portfile checksum: arrow-8.0.0.tar.gz sha256 0a360636cdc24fd8a480e497788f6c1f53d51dcde5f1ad035f1267e6e4cdc346
Distfile checksum: arrow-8.0.0.tar.gz sha256 0086ea4b5fc65f759a01ecb98fdce83033258822350b9e92162c6e18c037babf
Error: Checksum (size) mismatch for arrow-8.0.0.tar.gz
Portfile checksum: arrow-8.0.0.tar.gz size 17715015
Distfile checksum: arrow-8.0.0.tar.gz size 17725097
The correct checksum line may be:
checksums           rmd160  37c669b5c80b034f58ecdafe7fa4476e041255a6 \
                    sha256  0086ea4b5fc65f759a01ecb98fdce83033258822350b9e92162c6e18c037babf \
                    size    17725097
```

So yes, we should treat this as a stealth update.

**Comment by reneeotten** [comment]
Sure, but please first verify what the difference between the `distfiles` is

**Comment by mascguy** [comment]
> Sure, but please first verify what the difference between the `distfiles` is

@reneeotten Unfortunately I'm not able to find a tarball snapshot, which matches the previous (now invalid) checksums: Our distfile repo doesn't have it, nor is it available via Apache's - or 3rd-party - mirrors. I also did some quick digging via internet archives, but no bueno.

So unless this is available via GitHub or some other means (?), that history is lost.

Regardless, this needs to be fixed, so let's move forward.

**Review by mascguy — APPROVED** [review]
Added stealth update fix, and looks good locally. Merging.

**Pull request merged**
