### PR TITLE
paraview: Bump version

### PR DESCRIPTION
**Pull request by rubendibattista**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by rubendibattista** [comment]
I'm experiencing UI re-drawing problems with this new version: https://gitlab.kitware.com/paraview/paraview/issues/18702

They look strangely similar to: https://trac.macports.org/ticket/57641

Something related to Metal?

**Comment by rubendibattista** [comment]
Also related: https://gitlab.kitware.com/paraview/paraview/issues/18660

**Comment by pmetzger** [comment]
@rubendibattista If you're having problems, should we hold off on merging this?

**Comment by rubendibattista** [comment]
Yes, I think so. I will keep on eye on the Kitware Issue tracker to see if
and when they fix it...

**Comment by rubendibattista** [comment]
@pmetzger Ok, I'll close it and I'll come back if a fix comes around!

**Comment by luzpaz** [comment]
@rubendibattista thanks for trying.

**Comment by rubendibattista** [comment]
It seems that with the new revision of `qt5` (5.12.2) the problems is solved on Mojave. Can we bump the version? 

https://gitlab.kitware.com/paraview/paraview/issues/18660

**Comment by pmetzger** [comment]
@rubendibattista Perhaps file a ticket on trac?

**Pull request closed without merging**
