### PR TITLE
Update various unmaintained Python ports

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
- see commit messages for a description of the updates

###### Tested on

macOS 10.14.3 18D42
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? N/A
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`? Yes, where applicable
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
it appears there is an issue with the latest version of ```py-appscript```; the changelog states that it "added macOS 10.14 Automation permissions APIs to py-appscript; deleted objc-appscript (superseded by AppleEventBridge)".

It compiles happily locally on my computer but for older Xcode versions it appears that ```py27-appscript``` has an issue. Not sure why yet, but I can take a quick look - if it's not obvious I will just remove that update from this PR for now.

**Comment by reneeotten** [comment]
okay, it's not clear to me and to be fair I don't want to spend more time right now so I just removed the update of the ```py-appscript``` port..

**Comment by yan12125** [comment]
Gonna merge as Azure Pipelines are satisfied.

Regarding the appscript issue: maybe it's time to consider removing it as it's declared dead upstream 7 years ago [1].

[1] http://appscript.sourceforge.net/status.html

**Comment by yan12125** [comment]
Oops, I didn't notice appscript is revived and there are some commits in 2019.

https://sourceforge.net/p/appscript/code/HEAD/tree/

**Pull request merged**
