### PR TITLE
py-rich: add Python 3.13 subport

### PR DESCRIPTION
**Pull request by breun**
#### Description

Add Python 3.13 subport.

###### Tested on

macOS 15.1.1 24B91 arm64
Xcode 16.1 16B40

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by breun** [comment]
Waiting for https://github.com/macports/macports-ports/pull/26983 to get merged before re-running this one.

**Comment by reneeotten** [comment]
as I said yesterday as well: please submit ports that depend on each other in the same PR (but with different commits). This is just "polluting" the PR queue without any chance of succeeding on the CI.

**Comment by reneeotten** [comment]
> Do you know how long it typically takes for a new port to become available for subsequent PR CI builds?

You will need to rebase your PR branch with “master” after the merge and push to the PR to pick up the changes.

**Comment by breun** [comment]
I made a bit of a mess of this PR. I will handle the change via https://github.com/macports/macports-ports/pull/27021 instead.

**Pull request closed without merging**
