### PR TITLE
wolfssl: fix build on older systems and powerpc

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Some fixups

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
let's see what upstream thinks about these patches as we really don't want to cary them forward ourselves.

**Comment by JacobBarthelmeh** [comment]
@barracuda156 thanks for the work on this! It looks to be related to this pending pull request on wolfSSL (https://github.com/wolfSSL/wolfssl/pull/7931). Placing the pull request link here in comment to follow upstream status.

**Comment by barracuda156** [comment]
> @barracuda156 thanks for the work on this! It looks to be related to this pending pull request on wolfSSL ([wolfSSL/wolfssl#7931](https://github.com/wolfSSL/wolfssl/pull/7931)). Placing the pull request link here in comment to follow upstream status.

And this for dispatch part: https://github.com/wolfSSL/wolfssl/pull/7932

**Comment by barracuda156** [comment]
@reneeotten @JacobBarthelmeh Merged to upstream:
https://github.com/wolfSSL/wolfssl/commit/10c1fa208803969b790df5ed476d9b06fc3428b0
https://github.com/wolfSSL/wolfssl/commit/500a3b41e41ec7a16f5034e5760487d4e5a12cb9

**Comment by barracuda156** [comment]
@JacobBarthelmeh @reneeotten So can this be merged now?

**Comment by barracuda156** [comment]
@reneeotten @herbygillot This should have been merged already, I believe. Upstream accepted patches.

**Pull request merged**
