### PR TITLE
rrdtool: update to 1.7.1

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Drop configure-dont-run-libtool.patch (relevant lines have been commented out upstream); rebase configure-remove-cute-output.patch

revbump ports using librrd
Closes: https://trac.macports.org/ticket/56771

`py-rrdtool`: update to 0.1.15 (instead of revbumping; no functional changes from 0.1.14)

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.5 18F132
Xcode 10.2.1 10E1001 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
I would like assistance in finding the ports which need to have their revision incremented (see https://trac.macports.org/ticket/56771), unless that is considered beyond the scope of this PR. So far I did not find any past update commits that give an idea of what those are.

**Comment by ryandesign** [comment]
> I would like assistance in finding the ports which need to have their revision incremented

I would start with the output of

```
port file all | sort -u | xargs grep -E ':rrdtool( |$)'
```

**Comment by chrstphrchvz** [comment]
I have revised this to revbump with the ports I found which link to librrd, with the exception of `ntop` since it is incompatible with recent librrd (and should instead be replaced by e.g. `ntopng`; see https://trac.macports.org/ticket/55550), and `py-rrdtool` (since it can be updated to 0.1.15; no functional changes from 0.1.14)

(The remaining `rrdtool` dependents appear to use the Perl library or invoke the `rrdtool` command directly.)

Cc @neverpanic @raimue (`collectd`), @ryandesign (`php-rrd`)

**Comment by pmetzger** [comment]
Should this be merged now?

**Comment by chrstphrchvz** [comment]
A port abandoned ticket was opened for `rrdtool`: https://trac.macports.org/ticket/58642

**Comment by pmetzger** [comment]
@chrstphrchvz Port abandoned or no, should the current PR be merged?

**Comment by chrstphrchvz** [comment]
@pmetzger sorry, I did not realize you were asking me if this should be merged. If you think enough time has passed for any feedback/objections from @pdvnl, or from @neverpanic and @raimue regarding `collectd` revbump, then I believe this can be merged. Thanks

**Pull request merged**
