### PR TITLE
ImageMagick: add openmp variant

### PR DESCRIPTION
**Pull request by kencu**
closes: https://trac.macports.org/ticket/54050

### CODE REVIEW

**Comment by ctreleaven** [comment]
There are several dozen ports that depend on ImageMagick.  Do we have any reasonable way to test whether they are negatively affected by the openmp variant?

**Comment by kencu** [comment]
Excellent question, and actually part of the issue with ImageMagick/OpenMP as it is. Most people right now would probably have no idea if they have ImageMagick with OpenMP enabled, because it's done automatically in the background at present, if the compiler supports it.

So all ImageMagick built with gcc has OpenMP, and anyone who built it accidentally or purposefully with clang > 3.8 has it. All others, including all Xcode builds, do not have it.

So I would think that means that all recent (10.9+) installations of ImageMagick done via standard MacPorts installs (without adjusting the compiler manually) do not have OpenMP installed. That's why I left the default as disabled.

**Comment by eborisch** [comment]
I'm away from a real computer, and can't recall for this specific case; does this make sure the compiler (and by extension libomp) is marked either depends-lib or depends-run? If not, add libomp to depends-lib in the openmp variant.

**Comment by kencu** [comment]
clang-3.9 declares the dep on libomp itself, and there's no clang-3.9 variant to build without libomp. Would that not be sufficient? (clang-3.9 also has plenty of other deps...)

**Comment by ryandesign** [comment]
You've changed the port to disable openmp by default. Based on prior tickets, openmp is on by default on Snow Leopard, so this will change installed files for some users, so the revision should be increased.

You check `os.major` without first checking `os.platform`. You presumably intend to confirm that `os.platform` is "darwin" before checking that `os.major` is greater than 9.

You're whitelisting MacPorts clang 3.9 and 4.0. MacPorts will choose the first compiler in the whitelist that is not blacklisted. The port doesn't blacklist any compilers, so MacPorts clang 3.9 will always be used. If that's what you intended, fine; I would think we'd want to use 4.0, since that's the latest stable version.

MacPorts clang 3.5 and greater require libc++, so this will be a problem for users of Mountain Lion and earlier who have not followed [these instructions](https://trac.macports.org/wiki/LibcxxOnOlderSystems), but you've targeted Snow Leopard and later. Was that your intention?

**Comment by mojca** [comment]
Ryan, this is off-topic and I had the same thoughts about missing check for `darwin`, but while grepping for `os.major` I realized that lots of ports skip this check. Maybe that requires a separate ticket.

**Comment by ryandesign** [comment]
A lot of ports have a lot of mistakes; when we can, we shouldn't repeat them.

**Comment by kencu** [comment]
although macports clang 3.5+ requires libc++ to run, it doesn't require libcxxonoldersystems to be enabled. The versions of clang that need libc++ install it themselves as a dep. Clang will build against libstdc++ very happily. So forcing libcxxonoldersystems instructions is not needed.

will add os_platform check -- it seemed that was more or less disappearing, because as far as I can see other than Rene, nobody uses macports on anything but macos. At least, they are silent about it. But happy enough to add it in for you.

Revbump is fine --  some users in the gcc-compiler era will have imagemagick with openmp enabled, as well as some random users that built it with a macports-clang-3.8+ compiler. If we revbump them, they will lose it, unless they know enough to add the variant. But it's time everyone figured that out.

**Comment by kencu** [comment]
Hmmm. For some reason now the version in my working branch was slightly behind the current release. I think this is because I was doing this  on two different machines. So I fixed that to the current version of imagemagick, but now it lists a version / checksum change as well as the variant addition. Argh. Force-pushing fixes and working on multiple machines. Happy to close this off if needed -- you have seen ideas for the openmp variant if you ever want to add it. Or maybe the 'resolve conflicts' thing might work. Up to you.

**Comment by kencu** [comment]
My attempt to fix the conflict by merging in new changes from macports-ports into the branch and resolving the conflicts in the portfile did not work out as hoped, now the PR says it can't be rebased. I'll leave this around here for a few days to see if anyone knows a way / wants to resuscitate it somehow, but it looks dead and buried to me. I'll close this PR in a few days if nobody sees a way to rescue it.

**Comment by mojca** [comment]
I'll fix your PR.

How I did it:
```
git checkout master
git branch pr456
git cherry-pick 4fe37fb717af6ebc378f1f
# edit the file
git add graphics/ImageMagick/Portfile
# minor edit of the commit message
git cherry-pick --continue
```

Btw: you need an empty line after the first line of commit message.

**Comment by mojca** [comment]
@ryandesign: I'm willing to do the job of merging, but I would like your confirmation or rejection of the current patch (you can just add `.patch` to the URL to get a raw patch).

I can confirm that clang 3.9 and 4.0 can be installed without following the special instructions.

**Comment by kencu** [comment]
I'm rather afraid to change and force-push this PR any further after Mojca's much appreciated repair work. Hope it gets committed as is. On the other hand, I've repaired clang-4.0 for 10.6, so if it is decide to go with that as the default whitelisted compiler for this, I'm good with that.

**Comment by kencu** [comment]
This PR seems to generate a certain amount of uncertainty. I already have this working locally, so it's not an issue for me. I had helped the person in ticket 54050 sufficiently in accomplishing this that I thought I might as well put that effort forward for any others who might want it rather than waste that knowledge. But this can certainly be closed off if it's not for the general repo for some reason.

**Comment by mojca** [comment]
@kencu: please don't panick (and ask for closing a PR) if stuff is not committed immediately.

@ryandesign: are you OK with this patch or do you have further concerns? (I don't want to use maintainer timeout for active maintainers if I don't have to.)

**Comment by kencu** [comment]
I think it's fair to say at this point that if Ryan wanted to include the PR, he'd have done so by now. I'll kill it, and leave the PR here for anyone who might someday want to have openmp on this port.

**Comment by kencu** [comment]
We will make this happen.

**Comment by pmetzger** [comment]
@kencu First step in making it happen: redo/rebase to resolve conflicts. :)

**Comment by kencu** [comment]
You are right. I will have to figure out how this can work, but this PR can't do it. I will open a separate PR for this.

**Pull request closed without merging**
