### PR TITLE
mbedtls: default to python39

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by Schamschula** [comment]
Thanks for pointing this out!

I'll tweak the Portfile a little more after this change.

**Comment by i0ntempest** [comment]
No prob, are you planning to maintain a port for 3.x as well? If so are you going to rename this port to something like mbedtls2?

**Comment by Schamschula** [comment]
Currently most dependent ports don't build against mbedtls 3.x. The API of new version is not backwards compatible. Hopefully, this will be fixed upstream and we can move on to version 3.x. Otherwise, there will need to be mbedtls2 and mbedtls3.

**Comment by i0ntempest** [comment]
Well I was actually trying to build openvpn3 i submitted a while ago with this and it won't even build with this 2.27 version. They are probably maintaining a few branches in parallel like openssl.

**Pull request merged**
