### PR TITLE
p5-test-simple: Remove optional dependency, fix circular deps.

### PR DESCRIPTION
**Pull request by Dave-Allured**
#### Description

* Fix dependency cycle.
* Remove optional dependency p5-module-pluggable.
* Closes https://trac.macports.org/ticket/70547

###### Type(s)

- [x] bugfix

###### Tested on

macOS 14.6.1 23G93 Sonoma, x86_64
Xcode 15.4 15F31d
CLT 15.3.0

macOS 14.5 23F79 arm64
Xcode 16.0 16A242d

macOS 10.15.7 Macbookpro mid 2010 Intel i7 x86_64
Xcode 11.5
CommandLineTools 11.5

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tried a full install with `sudo port -s install`?
- [x] Confirmed absence of dependency cycle?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
A change in lib or run dependency requires increasing the revision.

**Comment by Dave-Allured** [comment]
Rev bump added.  Thanks for the reminder.

Maintainer, please squash these commits when merging.  With github website only, I do not have that capability.

**Comment by lcvisser** [comment]
Works for

```
macOS 14.5 23F79 arm64
Xcode 16.0 16A242d
```

**Comment by Dave-Allured** [comment]
Closing.  Replaced by updated PR https://github.com/macports/macports-ports/pull/25942.

**Comment by reneeotten** [comment]
> Closing.  Replaced by updated PR https://github.com/macports/macports-ports/pull/25942.

Why - there doesn't appear anything different in that PR. We really prefer not to do this and instead keep everything in one PR (as discussed many times before).

**Pull request closed without merging**
