### PR TITLE
epubcheck: delete port

### PR DESCRIPTION
**Pull request by chrstphrchvz**
**Proposing that this port be deleted rather than attempting to update/improve it. Please leave open long enough for discussion.**

Upstream project is still maintained (moved to GitHub), but this
port has been outdated since the release of EpubCheck 3.0 in 2013.
Has fallback dependency on `kaffe`. No dependents.

See: https://trac.macports.org/ticket/53467
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

### CODE REVIEW

**Comment by neverpanic** [comment]
This tool actually looks useful. Maybe somebody will step up to update it.

**Comment by pmetzger** [comment]
@neverpanic Indeed! But who?

**Comment by mf2k** [comment]
If we delete the port, then no one will. I don't think we should be deleting ports that can be updated. Only the ones that are dead upstream and cannot be built on modern computers.

**Comment by pmetzger** [comment]
@mf2k Okay, reasonable. But could we perhaps set some sort of intermediate flag? Maybe if we had a tag in the portfile indicating not just that there's no maintainer but that something is in need of an update? Then someone could look for such things on the web app and take them on as work projects?

**Comment by mojca** [comment]
> Okay, reasonable. But could we perhaps set some sort of intermediate flag? Maybe if we had a tag in the portfile indicating not just that there's no maintainer but that something is in need of an update? Then someone could look for such things on the web app and take them on as work projects?

@arjunsalyan

One of the next top priorities would be to run `livecheck` on the buildbot and show a list of outdated ports. The reason why I didn't do this yet is because it needs a bit of testing and a slightly different strategy of running. Most likely its own macports installation or at least its own port tree. During `livecheck` we may not perform some other operations on the same macports instance, and we should not be blocking other tasks in the meantime. I was thinking of maybe spending time and integrate and test this step into the buildbot 2 setup that @rajdeepbharati has been working on (not expecting him to write it, just use his work as a starting point).

An alternative cheating approach would be to help Repology brainstorm about a new API with mapping of macports -> repology package names and get the info about outdated port from there.

One of the other relatively high priority things would be to write some powerful filters / search functionality. Then you could easily browse through all the outdated ports (as indicated by `livecheck` results) and sort them according to popularity or arbitrary other metrics.

And we desperately need some "Are you a beginner and want to help? Here's a list of things that we would be grateful for and that you can help us with with very little skill." That list could include tasks as easy as fixing website URLs as indicated by https://repology.org/repository/macports/problems, for example. (This task could probably use scripting.)

**Comment by mojca** [comment]
Also, we could use [trac tickets](https://trac.macports.org/query?status=!closed&type=update&component=ports&desc=1&order=time) as a starting point for the source of such information. Adding this info to ports themselves sounds strange.

**Comment by pmetzger** [comment]
@mojca The info I want to add is something to the effect of "known well behind, needs someone". It seems like portfiles might be a good place to add it, but trac tickets could also work if there was an expectation they could be acted on and closed quickly. One reason I don't know if it's good to add it to trac is that there's an expectation that a ticket should be a short lived item.

**Comment by chrstphrchvz** [comment]
Thanks for the feedback everyone; this is indeed more of the sort of discussion I was hoping for. There appears to be interest in keeping this port, so that is enough for me to close this PR. I will not immediately attempt to update this myself, so I have opened a ticket to update it: https://trac.macports.org/ticket/58906

> If we delete the port, then no one will [update it]

I don't think this is necessarily true; I believe there have been a couple of times where deleting a port was enough to prompt another member to restore it and put in some effort improving it (though ideally this scenario is avoided).

I do think it should be documented as part of normal port submission/requesting process to check if a port previously existed.

> But could we perhaps set some sort of intermediate flag? Maybe if we had a tag in the portfile indicating not just that there's no maintainer but that something is in need of an update?

There is the deprecated portgroup and its `deprecated.macports_support no` option, but I don't think the notice it currently displays is necessarily phrased as a "help wanted" message, even if that might be what using the portgroup implies.

**Comment by pmetzger** [comment]
I think "deprecated" does not imply "help wanted". We probably want something that implies "rotting, need not be rotting if someone cares".

**Pull request closed without merging**
