### PR TITLE
snac: update to version 2.35

### PR DESCRIPTION
**Pull request by artkiver**
###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 13.4 22F66 arm64
Xcode 14.3.1 14E300c

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by artkiver** [comment]
Weird. Looks as if the build bots failed to grab the tarball?

I ran port clean -f --all and re-running port -v fetch locally seems OK:

```
--->  Attempting to fetch 2.35.tar.gz from https://codeberg.org/grunfink/snac2/archive
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  114k  100  114k    0     0  78335      0  0:00:01  0:00:01 --:--:-- 78391
```

I'm not sure how to debug the build bots further, nor even get them to attempt to re-run without submitting another PR or push.

**Comment by artkiver** [comment]
Looks as if the second run is even more confusing, insomuch as one of the builds was successful.

The errors on the other two for the second run seem to be in a different format?



```
023-06-16T07:15:57.6416830Z macOS version: 12.6.5
2023-06-16T07:15:58.1205520Z IP address: 199.7.166.18
2023-06-16T07:15:58.6243050Z curl: (22) The requested URL returned error: 403
2023-06-16T07:15:58.6243740Z Can reach private packages server: no
```

```
2023-06-16T07:16:30.8298380Z ##[group]Cleaning up between ports
2023-06-16T07:16:30.8815680Z df: getattrlist failed: Input/output error
2023-06-16T07:16:30.8841830Z ----> Free disk space before cleanup: 150GiB
2023-06-16T07:16:30.8842540Z 
2023-06-16T07:16:30.8844450Z 
2023-06-16T07:16:30.8845240Z ----> Deleting build
2023-06-16T07:16:30.8950260Z 
2023-06-16T07:16:30.8951640Z ----> Deleting logs
2023-06-16T07:16:30.9051260Z 
2023-06-16T07:16:30.9091140Z df: getattrlist failed: Input/output error
2023-06-16T07:16:30.9114780Z ----> Free disk space after cleanup: 150GiB
2023-06-16T07:16:30.9128360Z ----> Disk space saved by cleanup: 0KiB
2023-06-16T07:16:30.9144360Z ##[endgroup]
2023-06-16T07:16:30.9145430Z ##[group]Installing dependencies for snac
2023-06-16T07:16:59.5811860Z ##[error]The operation was canceled.
```

I am not sure if I am reading the above correctly; it appears as if perhaps the other two checks were cancelled due to a failure to resolve dependencies and were unable to reach an internal package repository?

At least one of the checks succeeded. 

From my vantage, I am guessing maybe something is amiss with the build bots? p

**Comment by artkiver** [comment]
Ah, I see; the note for macos-12 and macos-11 is that they were cancelled by @reneeotten.

Perhaps they would have completed successfully? Or maybe something else was going on with the build bots? I am uncertain.

**Comment by reneeotten** [comment]
no I restarted the build that initially failed; the others were canceled in the first CI run because of the failure. It looks like now I am able to restart the other two as well, which I will do now.

**Comment by artkiver** [comment]
> no I restarted the build that initially failed; the others were canceled in the first CI run because of the failure. It looks like now I am able to restart the other two as well, which I will do now.

Ah, thank you! 

It appears as if your last attempt functioned OK on macOS-12 as well,  though from GitHub's UI it is still showing the third attempt on macOS-11 as cancelled.

I don't think I understand enough about the build bots to diagnose that, it seems confusing.

**Comment by artkiver** [comment]
Thank you @reneeotten ! 🙏

**Pull request merged**
