### PR TITLE
inkscape: update to 1.1.2

### PR DESCRIPTION
**Pull request by evanmiller**
#### Description

Update Inkscape to the latest stable version. The Inkscape build is currently broken due to the recent poppler update, which requires C++17.

Depends on #14057 – leaving this PR as Draft until that one is merged.

Closes: https://trac.macports.org/ticket/50210
Closes: https://trac.macports.org/ticket/51287
Closes: https://trac.macports.org/ticket/51407
Closes: https://trac.macports.org/ticket/54944
Closes: https://trac.macports.org/ticket/60927
Closes: https://trac.macports.org/ticket/61404
Closes: https://trac.macports.org/ticket/64660

CC @mascguy 

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Restarted the CI jobs, now that https://github.com/macports/macports-ports/pull/14057 has been merged.

**Comment by mascguy** [comment]
You're a lifesaver Evan, thank you!

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
Evan, updated per your feedback for the Devel port.

**Comment by evanmiller** [comment]
@mascguy Sounds good. Once this is green / merged I'll open a PR for a pre-release build that I'm playing with...

**Pull request merged**
