### PR TITLE
py-botocore, py-awscli, py-boto3: Update to 1.21.36, 1.20.36 and 1.18.36

### PR DESCRIPTION
**Pull request by judaew**
- py-botocore: update to 1.21.34
- py-awscli: update to 1.20.34
- py-boto3: update to 1.18.34

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.5.2 20G95 x86_64
Xcode 12.5.1 12E507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by judaew** [comment]
```
:info:build ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so, 2): Library not loaded: /opt/local/lib/libffi.7.dylib
:info:build   Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so
:info:build   Reason: image not found
```

The ports for python36 and python37 are not built because they cannot find libffi.7.dylib. This seems to be related to yesterday's update of the `libffi` library in 2d03a1daf938a7130f1850b84dda2f2f96f4d3d2:

```console
$ git show 2d03a1daf938a7130f1850b84dda2f2f96f4d3d2
commit 2d03a1daf938a7130f1850b84dda2f2f96f4d3d2
Author: Joshua Root <jmr@macports.org>
Date:   Wed Sep 1 05:59:32 2021 +1000

    libffi: update to 3.4.2
    
    Not binary compatible with the previous release:
    libffi.7.dylib -> libffi.8.dylib
```

**Comment by judaew** [comment]
@jmroot I bumped revision in follow PR https://github.com/macports/macports-ports/pull/12056.

**Comment by reneeotten** [comment]
@judaew if you rebase this PR to resolve the conflicts I'll merge it - thanks!

**Comment by judaew** [comment]
Thanks @reneeotten.  I'm doing that right now, and I will also update the ports to `*.*.36`.

**Comment by judaew** [comment]
After passing checks in CI, you can merge it. As always, thanks 🌟

**Pull request merged**
