### PR TITLE
ftgl: attempt to fix build on macOS 11, other minor fixes

### PR DESCRIPTION
**Pull request by chrstphrchvz**
See: https://trac.macports.org/ticket/61210

#### Description
Also switch from deprecated `cxx11 1.1` portgroup to `compiler.cxx_standard 2011`, and specify glibtoolize path to avoid complaint:

```
Warning:  libtoolize does not appear to be available.  This means that
the automatic build preparation via autoreconf will probably not work.
Preparing the build by running each step individually, however, should
work and will be done automatically for you if autoreconf fails.

Fortunately, glibtoolize was found which means that your system may simply
have a non-standard or incomplete GNU Autotools install.  If you have
sufficient system access, it may be possible to quell this warning by
running:

   ln -s /opt/local/bin/glibtoolize /opt/local/bin/libtoolize

Run that as root or with proper permissions to the /opt/local/bin directory
```

###### Type(s)

- [x] bugfix

###### Tested on

macOS 10.15.7
Xcode 12.4 command line tools

I have verified the approach appends `-framework GLUT` to the affected linking command on macOS 10.15, but have constrained it to apply only to on macOS 11 and later where the issue is observed.
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
Commits separated for clarity.
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
https://github.com/macports/macports-ports/runs/1876592156?check_suite_focus=true#step:8:453

```
  checking for GL library... host=x86_64-apple-darwin20.3.0
  no
  configure: error: GL library could not be found, please specify its location with --with-gl-lib.
```

This is different from the error described in https://trac.macports.org/ticket/61210, but resembles the error encountered by the macOS 11 arm64 builder: https://build.macports.org/builders/ports-11_arm64-builder/builds/8561/steps/install-port/logs/stdio

```
checking for GL library... host=aarch64-apple-darwin20.1.0
no
configure: error: GL library could not be found, please specify its location with --with-gl-lib.
```

**Comment by chrstphrchvz** [comment]
Awaiting new macOS 11 CI results…

**Comment by ryandesign** [comment]
Please close this; I have the correct fix and will commit momentarily.

**Comment by kencu** [comment]
OK

**Pull request closed without merging**
