### PR TITLE
pd-faust: update to 0.15

### PR DESCRIPTION
**Pull request by agraef**
#### Description

Update to latest release (now hosted on Github, so I adjusted the Portfile accordingly).

###### Tested on
macOS 10.12.6 16G1212
Xcode 9.2 9C40b

### CODE REVIEW

**Comment by agraef** [comment]
@ryandesign this is the last update of Pure-related packages (see #1258 and #1259 for the others) which are prompted by the recent update of the Faust ports (#1257 still pending right now). Thus it would be nice if these could all be merged at the same time.

Also note that I've recently moved Pure over to Github (https://agraef.github.io/pure-lang/), so I had to adjust the Portfiles of faust2pd, pure-faust and pd-faust accordingly (these all use the github port group for the time being). The rest of the tarball releases of the Pure system are still on Bitbucket, so I'd suggest to keep the pure port group as it is for now. I will eventually move all of the releases to Github (at which point we might go about adjusting the pure port group itself), but that's still some time in the future.

Last but not least, I'm teaching courses later this week where having the latest version of these packages would be nice to have, do you think you can merge my PRs before Thursday? That would be much appreciated, thanks.

**Comment by neverpanic** [comment]
Looks good to me in general. I'm wondering on the other flags that the pure portgroup used to pass, such as setting `PUREC_FLAGS=-mcpu=generic` and the `${configure.*_archflags}` in `build.args-append`.

Does the pure build system now build for generic machines (i.e. not optimized for the host CPUs at hand) by default? Our buildbots would probably be producing binary packages for these ports, so this question is important.

The archflags are usually there to make sure universal builds work properly in absence of a configure system. We usually set them when setting `use_configure no`. Are those no longer required either?

I'm sure you're the expert on these ports, so I'm inclined to just trust your judgement on this, if you could just clarify these points.

**Comment by agraef** [comment]
@neverpanic you're right, I totally forgot about that. :( I'll have to take a look at this. Should I mark the affected PRs as "WIP" until I'm done with this, or what's the recommended procedure here?

**Comment by pmetzger** [comment]
There's no particular procedure. I'd recommend either closing and reopening or closing and later resubmitting...

**Comment by agraef** [comment]
Needs to be augmented, closing for now.

**Pull request closed without merging**
