### PR TITLE
pdal: update to version 2.5.2

### PR DESCRIPTION
**Pull request by nilason**
#### Description

Upgrade PDAL to version 2.5.2

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6.3 21G419 arm64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

I have tested with `grass` (8.2.1).

### CODE REVIEW

**Comment by nilason** [comment]
Port lint gives following error:
`port lint PDAL: Error: Portfile directory pdal does not match port name PDAL`
This is nothing caused by this version bump.
Should I address this here?

**Comment by ryandesign** [comment]
> `port lint PDAL: Error: Portfile directory pdal does not match port name PDAL`
> This is nothing caused by this version bump.

This was caused by e38c8933c41c67d25f283337f94ebceb7de78bd8. Veence should decide whether the port name should be PDAL (rename the directory) or pdal (fix the port name). All ports that depend on pdal should be confirmed to use the correct case after that decision is made.

**Comment by nilason** [comment]
> > `port lint PDAL: Error: Portfile directory pdal does not match port name PDAL`
> > This is nothing caused by this version bump.
> 
> This was caused by [e38c893](https://github.com/macports/macports-ports/commit/e38c8933c41c67d25f283337f94ebceb7de78bd8). Veence should decide whether the port name should be PDAL (rename the directory) or pdal (fix the port name). All ports that depend on pdal should be confirmed to use the correct case after that decision is made.

Personally, I'd prefer lower cased port name, in line with gdal, grass etc...

**Comment by reneeotten** [comment]
well... I'll merge this PR for now  because waiting until @Veence responds seems not practical

**Comment by nilason** [comment]
> well... I'll merge this PR for now because waiting until @Veence responds seems not practical

Thanks!

**Pull request merged**
