### PR TITLE
OLA - Support later protobuf. Closes https://trac.macports.org/ticket/59585

### PR DESCRIPTION
**Pull request by peternewman**
#### Description
Support later protobuf. Closes https://trac.macports.org/ticket/59585

###### Type(s)
- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
Travis only!

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)? - Mostly
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)? - Do it on merge?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`? - Not unless Travis does
- [ ] tried existing tests with `sudo port test`? - Not unless Travis does
- [ ] tried a full install with `sudo port -vst install`? - Not unless Travis does
- [ ] tested basic functionality of all binary files? - Not unless Travis does a make check

### CODE REVIEW

**Comment by mf2k** [comment]
The patch patch-google_check.diff failed to apply.

**Comment by peternewman** [comment]
This pair at least apply cleanly :crossed_fingers:

**Comment by peternewman** [comment]
Progress, although I'll have practically released 0.10.8 at this rate!

**Comment by peternewman** [comment]
It would be nice if the bots didn't waste their time doing expired commits on PRs and more confusingly didn't comment on them. As long as Travis passes the last two builds this should be good to go!

**Pull request merged**
