### PR TITLE
gptfdisk: update to 1.0.5

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.4 19E287
Xcode 11.4 11E146 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
Thanks for the update!

you've patched in changes to the build Makefile that are not really the way we do things on MacPorts, hard-coding in build options that we normally control during the build.

**Comment by i0ntempest** [comment]
I made a new patch file cuz the old one doesn’t work... should I just remove it?

**Comment by kencu** [comment]
it's possible this port never worked properly before. MacPorts sets environment variables that builds are meant to use, to spec the compiler, flags, etc depending on the user's setup. This patch seems to override that, and chooses some options that no doubt work on some (most) systems, but doesn't appear to allow MP's methods to function...

**Comment by i0ntempest** [comment]
Okay, I removed the patch and reinplace (it doesn't do anything). Builds and works fine on my system.

**Comment by i0ntempest** [comment]
Can this be merged?

**Pull request merged**
