### PR TITLE
i2pd: update to 2.45.0

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@herbygillot We should add tests now. I was waiting for my PR to be merged to upstream, and it is: https://github.com/PurpleI2P/i2pd/pull/1812

Something like this: https://github.com/barracuda156/macports-ports/blob/d29c8c80d615b455ab09d8569137f0451757801c/security/i2pd/Portfile#L141

**Comment by barracuda156** [comment]
Alternatively, we may just enable building tests by default, without a variant.

P. S. One tests fails to pass on PPC, but all do build. x86 needs to be verified.

**Comment by barracuda156** [comment]
@herbygillot It actually won’t hurt merging this first and enabling tests in another PR. This is good as is.

**Comment by herbygillot** [comment]
Hey @barracuda156, I actually looked into enabling tests but they weren't running properly as they were in a separate directory - I'll take another look, but will just check in as you suggest if it continues not to work.

**Comment by barracuda156** [comment]
> Hey @barracuda156, I actually looked into enabling tests but they weren't running properly as they were in a separate directory - I'll take another look, but will just check in as you suggest if it continues not to work.

I believe they should build and run with `sudo port -v test i2pd +tests` and the variant being added to portfile: https://github.com/barracuda156/macports-ports/blob/d29c8c80d615b455ab09d8569137f0451757801c/security/i2pd/Portfile#L141
One tests fails to pass on PPC, but that is not a stopper to add tests.

**Comment by barracuda156** [comment]
@herbygillot Could you please update to 2.45.1 before merging? https://github.com/PurpleI2P/i2pd/releases/tag/2.45.1

Tests we can handle with @catap in another PR.

**Comment by barracuda156** [comment]
@herbygillot I will make a PR for tests support. We also need to fix this: https://github.com/PurpleI2P/i2pd/issues/1846

**Pull request merged**
