### PR TITLE
bind9: fix include flag ordering

### PR DESCRIPTION
**Pull request by jmroot**
Closes: https://trac.macports.org/ticket/64683

###### Type(s)

- [x] bugfix

### CODE REVIEW

**Comment by jmroot** [comment]
This will conflict with #14046 unfortunately, so I'll have to rebase whichever one gets merged second.

**Comment by danielluke** [comment]
Thanks so much. If you want to also maintain this port, you are welcome to add yourself.

**Comment by danielluke** [comment]
Sorry I broke this by using the github webUI to resolve the conflicts :-\

**Comment by danielluke** [comment]
oh, but I can squash and merge, so I didn't ruin everything.

**Pull request merged**
