### PR TITLE
py-tensor2tensor: Submission with dependencies

### PR DESCRIPTION
**Pull request by essandess**
py-tensor2tensor: Submission with dependencies

* Depends upon:
    * https://github.com/macports/macports-ports/pull/6261
    * https://github.com/macports/macports-ports/pull/7514

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
I think the reason that no one has even commented on this PR is that there are too many new Portfiles. I suggest opening a PR for each new port separately one at a time. It will also make the builder happy.

**Comment by kencu** [comment]
and now -- there is a conflict.

**Comment by essandess** [comment]
There's some dependency hell issues with related PRs. I'll wait until those are fixed in their upstreams and get back to this then.

**Comment by essandess** [comment]
@kencu, PR #6261 is to the best of my knowledge ready to merge. This PR depends on it.

**Comment by kencu** [comment]
OK Steve, the PR you were waiting for was merged.

**Comment by essandess** [comment]
> I think the reason that no one has even commented on this PR is that there are too many new Portfiles. I suggest opening a PR for each new port separately one at a time. It will also make the builder happy.

To the extent possible, I’ll break this PR into separate submissions.

**Comment by essandess** [comment]
This PR also depends on:
* `py-tensorflow-data-validation`, `py-tfx-bsl`: #7791 (`apache-arrow`)
* [Apache Arrow](https://github.com/apache/arrow) (recently upgraded to 3.0.0) depends upon a cmake build of `grpc`.
* `apache-arrow`: #9729 (`grpc`)

https://github.com/tensorflow/data-validation/blob/15b0dd1b8d8e31b971a39a50849a3c5e54978b30/setup.py#L188

https://github.com/tensorflow/tfx-bsl/blob/19df0b53e004404ae1971d4140a3242f3490f2d4/setup.py#L170

**Comment by essandess** [comment]
> > I think the reason that no one has even commented on this PR is that there are too many new Portfiles. I suggest opening a PR for each new port separately one at a time. It will also make the builder happy.
> 
> To the extent possible, I’ll break this PR into separate submissions.

This is now done.

**Comment by cjones051073** [comment]
There are still lint errors referring to missing deps.

**Comment by essandess** [comment]
> There are still lint errors referring to missing deps.

* #10301 
* #10436

**Pull request merged**
