### PR TITLE
multiple ports: Remove $Id$ line

### PR DESCRIPTION
**Pull request by jeremyhu**
```sh
sed -i '' '/^#.*\$Id\$.*$/d' Portfile
```

Signed-off-by: Jeremy Huddleston Sequoia <jeremyhu@macports.org>

### CODE REVIEW

**Comment by ryandesign** [comment]
Please don't merge this until after we have implemented the [buildbot success cache](https://trac.macports.org/ticket/52765).

**Comment by jeremyhu** [comment]
Sounds good.  That's why I wanted to ask first =)

**Comment by larryv** [comment]
Here's one that also removes leftover blank first lines.

**Comment by jmroot** [comment]
Success cache is now in place. Do we dare to merge this now? (Has some conflicts that need resolving first of course.)

**Comment by mojca** [comment]
Personally I would still vote for cancelling the build job on the buildbots (definitely we need to cancel it on 10.5 if we don't want to end up waiting for another year for the job to be done), but I leave it up to others to decide. I would almost bet that the buildbot would crash anyway.

If you still want to keep the builds, here are some optional suggestions we might want to consider:
* I would first try to build "`all`" on a single build slave (for example 10.10) to spot potential problem. I suspect this should work out-of-the-box if you put `all` to `Port list`. We can try at least. (The bottom line is that if this works, there's no reason not to cancel the build because we can start a full build at any time anyway.)
* There's another change that we might want to commit "in the same batch" (not in the same commit, but push it at the same time and make sure that we only start a single build at port watcher). That's automatic addition of github usernames to all maintainers (where we have that information). But we can easily commit that other one later (and cancel it).
* Perhaps look at https://trac.macports.org/ticket/52810 (not the the email in question will be useful to anyone anyway).

**Comment by larryv** [comment]
Updating the branch should be a simple matter of re-running the script in the commit I pushed and force-pushing the results.
```sh
for pf in /path/to/ports/*/*/Portfile
do
    ed -s "$pf" <<-'EOF'
	1,3g/^[[:space:]]*#[[:space:]]*\$Id.*\$[[:space:]]*$/d
	1g/^[[:space:]]*$/d
	w
	q
	EOF
done
```
I have no particular opinion on whether to cancel the build, although it would be interesting to let it be and observe how and when it fails.

I see no benefit in putting this off to add GitHub usernames to ports.

**Comment by larryv** [comment]
Sorry, disregard what I just said. The conflicts need to be fixed manually.

**Comment by larryv** [comment]
Disregard _that_. The first thing I said was more correct. Pushing updated commit now.

**Comment by mojca** [comment]
Oh, another point that just came to my mind.

A whole lot of ports fail to compile on older OSes just because our distfiles mirroring is currently down and fetching from HTTPS doesn't work. One particularly annoying example is `py-setuptools` which means that almost anything that depends on some python package fails to build.

Again, my preference would be to simply commit this, cancel the build job and rebuild everything later, but it's up to others to decide.

**Comment by mojca** [comment]
This PR has been open for a relatively long time. I still believe that we have quite some issues left to resolve at the buildbot end and I find it pointless to wait for resolution of those to commit something as trivial as the removal of `$Id$`. (I could start listing them all, but the list is long and might take months to fix.)

Wouldn't it be better to simply commit this, cancel the build jobs on the port watcher and rather implement https://trac.macports.org/ticket/52989 if we want to start building all ports?

**Pull request merged**
