### PR TITLE
librsvg, libsrvg-devel (fallback ports): update to 2.40.21

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description
https://download.gnome.org/sources/librsvg/2.40/librsvg-2.40.21.news

###### Type(s)

- [x] bugfix
- [x] security fix

###### Tested on

Untested
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mascguy** [comment]
> LGTM, though I plan to test locally first. (Since CI doesn't help with the fallback version.)

@pmetzger Perry, the intent was for me to test this locally first, as the fallback version only applies to 10.5 and earlier. So we have no idea whether it builds, since our buildbots only cover 10.6+.

But to be fair, I could have switched the status to draft. And perhaps that's the best approach in these cases, so folks don't inadvertently merge.

No worries regardless though, we'll make it work.

**Comment by pmetzger** [comment]
It's a security fix. We couldn't afford to wait days to put it in. Loads of stuff depends on rsvg and was vulnerable. Given that 10.5 and earlier are riddled with security holes, anyone running those systems is probably willing to put up with that, but for the benefit of users running a current OS that's fully patched it seemed necessary to do the update. When things are labeled "security" we rush them.

**Comment by chrstphrchvz** [comment]
This security update was from 2020. librsvg 2.40.x has already been considered unsupported since 2017. Its maintainer has advised against using it due to other bugs: https://viruta.org/do-not-use-librsvg-2.40.x.html

**Comment by pmetzger** [comment]
@chrstphrchvz He says don't use 2.40.x; he advises using the latest (which has been ported to Rust but has C bindings.)

Why don't we do an update to that?

**Comment by mascguy** [comment]
> @chrstphrchvz He says don't use 2.40.x; he advises using the latest (which has been ported to Rust but has C bindings.)
> 
> Why don't we do an update to that?

As I've already explained to @chrstphrchvz , we can't do that until `cargo` and `rust` are fixed across all macOS releases: This is a foundational port, required by portgroups like `app`. So if `librsvg` is broken anywhere, that causes a cascading series of failures.

So the Rust-based port will remain as-is, until someone fixes Rust and Cargo.

Refer to the open tickets I filed, for details.

**Comment by pmetzger** [comment]
I'm sorry, but we cannot prioritize people on ancient PowerPC hardware etc. They can be supported to the extent that it doesn't harm people who are using their Macs that are less than a decade old for real work. If you want to maintain an "old" rsvg library for hobbyists who don't have current machines that is fine, but they cannot be a priority over the day to day safety of the overwhelming bulk of the users.

**Comment by pmetzger** [comment]
BTW, I want to be blunt here: this is not a retrocomputing project for hobbyists who like Macs from twenty years ago. People use MacPorts to get their work done, and most of them use machines that are running the current OS and have hardware that's within a few years of current. The old librsvg is a security risk. We must stop using it immediately. It doesn't matter if this breaks people who want to run very old machines. If you want to work hard to keep such people functioning that's fine, but not at the expense of the safety of normal users or their ability to get work done.

**Comment by pmetzger** [comment]
@chrstphrchvz If you want to submit an update to the Portfile to update rsvg to the Rust version, please do. If others want to patch it so that it still uses the C version for people who are into retrocomputing that's fine, provided it doesn't hurt normal users.

**Comment by mascguy** [comment]
> I'm sorry, but we cannot prioritize people on ancient PowerPC hardware etc. They can be supported to the extent that it doesn't harm people who are using their Macs that are less than a decade old for real work. If you want to maintain an "old" rsvg library for hobbyists who don't have current machines that is fine, but they cannot be a priority over the day to day safety of the overwhelming bulk of the users.

Of note, we do not have Rust and Cargo available for folks with 10.5 and earlier. So it's a moot point, and we have no other choice but to use the non-Rust based version for those systems.

**Comment by pmetzger** [comment]
10.5 is ancient. If you care about it, fine, but it cannot block having current users of MacPorts have a secure version of rsvg. It matters to maybe a handful of people, while many thousands use the current version of the OS. MacPorts is not a museum. We are going to update rsvg. If you want to kludge something for the old OSes that's fine, but it is not a priority.

**Comment by pmetzger** [comment]
BTW, just to be blunt: being the maintainer of a port doesn't mean you own it the way you own your car, it means you've pledged to be responsible for it on behalf of all of the users of the system. It doesn't give you the right to unilaterally decide security isn't as important as having the three people using 10.5 happy.

**Comment by cjones051073** [comment]
> 10.5 is ancient. If you care about it, fine, but it cannot block having current users of MacPorts have a secure version of rsvg. It matters to maybe a handful of people, while many thousands use the current version of the OS. MacPorts is not a museum. We are going to update rsvg. If you want to kludge something for the old OSes that's fine, but it is not a priority.

The version used on 10.5 and older is in no way blocking updates to the much more up to date version based on rust used on 10.6. 10.6 and newer are already using 2.56.3, a pretty up to date release.

https://github.com/macports/macports-ports/blob/7010eb50df7086578b984c98eef15ec246f904ef/graphics/librsvg/Portfile#L100

**Comment by mascguy** [comment]
> BTW, just to be blunt: being the maintainer of a port doesn't mean you own it the way you own your car, it means you've pledged to be responsible for it on behalf of all of the users of the system. It doesn't give you the right to unilaterally decide security isn't as important as having the three people using 10.5 happy.

Well, the problem is that you're venturing into MacPorts manager territory, when you jump into a situation like this.

And frankly you're overstepping your authority, plain and simple.

Helping to motivate folks to complete their PRs is one thing. And it's great that you're doing that!

However, it might be good to avoid trampling on maintainer's toes: Suggesting that folks simply go ahead and submit a PR to update someone's ports - and making an end-run around the maintainer, who's actively involved in the discussion, no less! - well, that's not appropriate for your role. Or for any of us either for that matter, apart from the management team.

**Comment by pmetzger** [comment]
@cjones051073 it would have been nice if @mascguy had bothered mentioning that, since he was obviously aware of it, but I think he enjoyed not mentioning it far too much. I have a rather sour taste in my mouth from this whole thing.

**Comment by cjones051073** [comment]
> @cjones051073 it would have been nice if @mascguy had bothered mentioning that, since he was obviously aware of it, but I think he enjoyed not mentioning it far too much. I have a rather sour taste in my mouth from this whole thing.

With respect, the fault here was entirely yours for not taking a moment to look at the complete Portfile before commenting as you did, as if you had it should have been self evident to you. @mascguy clearly did not appreciate you had missed the point that the old version was only used for 10.5, and if he had I suspect he would have taken the time to point it out and thus avoid the whole unfortunate discussion.

**Comment by mascguy** [comment]
> @cjones051073 it would have been nice if @mascguy had bothered mentioning that, since he was obviously aware of it, but I think he enjoyed not mentioning it far too much. I have a rather sour taste in my mouth from this whole thing.

Perry, to be fair, I could have been a bit more diplomatic from the start. The suggestion to drag the managers in, for example, wasn't necessary.

With that being said, I'll reiterate that you overstepped your bounds. And you can't expect folks to take kindly to that, particularly if they're a reasonably seasoned member.

Also bear in mind that many of us have day jobs, which often prevents us from responding immediately.

Nonetheless, the point regarding Rust availability was brought up reasonably quickly, once I was able to look at my phone.

So there's absolutely no joy in any of this. And indeed, it reflects badly on all of us, when we don't get along. (Which is why I chose to forgo responding to the discussion on the Dev mailing list, as doing so wouldn't accomplish anything positive.)

**Pull request merged**
