### PR TITLE
qgis3: update to version 3.32.0 and new ‘qgis3-ltr’ subport

### PR DESCRIPTION
**Pull request by nilason**
#### Description

Bump to QGIS version 3.28.8.

EDIT:
In addition to the original version bump of QGIS, following changes are included: 

- Creation of a new subport `qgis3-ltr` which will follow long term release versions
  (similar to some Linux and FreeBSD packaging systems).
- The port `qgis3` will follow the latest version
- `saga` update to 9.1.0
- `gdal` update to 3.7.1

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6.6 21G646 arm64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by nilason** [comment]
I have now added a commit, which creates a new subport `qgis3-ltr`. The new port will follow the QGIS long term release version. The (old) port `qgis3` follows from now on the latest release version.

[QGIS Road Map](https://www.qgis.org/en/site/getinvolved/development/roadmap.html)

**Comment by nilason** [comment]
To reduce rebuilds, I have now added update of SAGA to 9.1.0 and GDAL to 3.7.1.

@Veence Please take a look and merge if good!

**Comment by nilason** [comment]
@Veence ping

**Comment by nilason** [comment]
I believe it's high time to get this one moving.
Perhaps @mascguy, @reneeotten or @herbygillot (or anyone else, I'm not picky :-) can step in.

**Comment by Veence** [comment]
Sorry for the delay. I’m on holiday with a flaky Internet connection

**Comment by nilason** [comment]
@Veence Thanks!

**Pull request merged**
