### PR TITLE
py-sphinx, etc.: add py38 support

### PR DESCRIPTION
**Pull request by danchr**
#### Description

Add Python 3.8 support for Sphinx and its dependencies.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by lpsinger** [comment]
Oops, sorry, I saw the email and didn't realize that there was a pull request, so I added the subport for roman.

**Comment by jmroot** [comment]
Conditionally approved so long as someone checks that sphinx actually works under 3.8 before merging.

**Comment by danchr** [comment]
> Conditionally approved so long as someone checks that sphinx actually works under 3.8 before merging.

I've used this for building PyObjC's documentation — is that sufficient?

**Comment by jmroot** [comment]
Sure. You just didn't check any of the checklist items, so I wasn't sure.

**Comment by MarcusCalhoun-Lopez** [comment]
For my ports, it might be a few days before I could test them properly.
The changes seem reasonable, so if others have had success, then I have no objections to merging.

**Comment by cjones051073** [comment]
Minor complaint, but I would have preferred if you had not merged all port updates into a single commit, as it means most ports touched are not explicitly mentioned (just as the ‘etc.’ bit). Woukd be better I think to give each its own commit.

**Comment by reneeotten** [comment]
what's the status here - can this be moved along?

**Comment by pmetzger** [comment]
I'm going to merge this as it looks like it's okay. In the unlikely event that we later discover an associated failure in one of the changed ports, we can fix it in a separate commit.

**Pull request merged**
