### PR TITLE
Update Frescobaldi to 3.1.3; related changes in dependencies

### PR DESCRIPTION
**Pull request by dliessi**
#### Description

See individual commit messages for more information.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G14042
Xcode 9.4.1 9F2000

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`? **(not for py39-poppler-qt4 and frescobaldi2)**
- [x] tested basic functionality of all binary files? **(not for py39-poppler-qt4 and frescobaldi2)**

### CODE REVIEW

**Comment by dliessi** [comment]
> * [x]  tried a full install with `sudo port -vst install`? **(not for py39-poppler-qt4 and frescobaldi2)**
> * [x]  tested basic functionality of all binary files? **(not for py39-poppler-qt4 and frescobaldi2)**

I tested also py39-poppler-qt4 and frescobaldi2.
frescobaldi2 crashes when opening the "About" window, but that is likely unrelated to the update (I haven't tested frescobaldi2 in a long time) and everything else seems to be working correctly.

**Comment by dliessi** [comment]
> frescobaldi2 crashes when opening the "About" window, but that is likely unrelated to the update

I investigated a bit more: the crash is due to py-poppler-qt4 and happens only with Python 3.9 and not with Python 3.7 (I haven't tested Python3.8).
Given that development on py-poppler-qt4 (and on poppler-qt4 and qt4) has halted, let's stick to Python 3.7 for frescobaldi2.
Sorry for the noise.

**Comment by dliessi** [comment]
I removed some unnecessary code.

**Comment by g5pw** [comment]
Merged, thank you for your contribution to Macports, @dliessi!

**Pull request merged**
