### PR TITLE
grafana: update to 10.0.3

### PR DESCRIPTION
**Pull request by slashapp**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.5
Xcode 14.3.1 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by slashapp** [comment]
build process raised OOM failure 

`
/2023-08-04T11:04:48.0455710Z FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
2023-08-04T11:04:48.0456780Z  1: 0x107447917 node::Abort() [/opt/local/bin/node]
2023-08-04T11:04:48.0457820Z  2: 0x107447b13 node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/opt/local/bin/node]
2023-08-04T11:04:48.0458960Z  3: 0x10757b20a v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/opt/local/bin/node]
`

**Comment by herbygillot** [comment]
Alright, I've tested this, and it builds. We can merge this, but will need to squash the second commit into the first. MacPorts prefers most changes to be in a single commit with a description in the format of `<port name>: <description>`.  So in this PR, just squash the `nodejs` correction into your original commit.

**Comment by slashapp** [comment]
get it , already pushed single commit.

**Comment by herbygillot** [comment]
Thank you for your efforts on this port.

**Pull request merged**
