### PR TITLE
qtruby: fix build, add modern ruby support

### PR DESCRIPTION
**Pull request by barracuda156**
Fixes: https://trac.macports.org/ticket/66518
Closes: https://trac.macports.org/ticket/67838

#### Description

Let’s see if this builds.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@mascguy @ryandesign If someone could review this, would be great. Currently the port is broken: https://ports.macports.org/port/qtruby/details

**Comment by barracuda156** [comment]
@ryandesign @mascguy Reminding of this one.

**Comment by barracuda156** [comment]
Bump

**Comment by barracuda156** [comment]
@mascguy I think so, but for sure oldest one and newest one. (Not really sure we got a use-case for Ruby19, might as well just drop it.)

**Review by mascguy — APPROVED** [review]

**Pull request merged**
