### PR TITLE
ncmpc: trying to solve build failure on 10.14

### PR DESCRIPTION
**Pull request by lbschenkel**
I'm the maintainer. Checking on Travis before pushing to master.

### CODE REVIEW

**Comment by lbschenkel** [comment]
As suspected, failed to build on 10.14: https://paste.z0k.xyz/2beb0a07f2ce
```
/Applications/Xcode_10.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/experimental/string_view:11:2: error: "<experimental/string_view> has been removed. Use <string_view> instead."
#error "<experimental/string_view> has been removed. Use <string_view> instead."
```
However, this `#include <experimental/...>`  does not seem to be coming from upstream (I checked the repo and found no such import in the code) but from Boost. I'm afraid I'm out of my league here. Any clues, @ryandesign?

**Comment by cjones051073** [comment]
This is indeed a boost issue

https://github.com/boostorg/asio/pull/91

The boost version  we ship in MacPorts has been outdated for a while now. We really need to make progress on updating it. I believe @michaelld was looking into this. Why do we stand on this now ?

**Comment by cjones051073** [comment]
https://trac.macports.org/ticket/56294

**Comment by michaelld** [comment]
@cjones051073 Getting closer from last week. See < https://trac.macports.org/ticket/56294#comment:26 >.

**Comment by lbschenkel** [comment]
So, it seems that I could find a temporary workaround. I changed the port to patch `meson.build` on macOS >= 10.14 to forcefully define `BOOST_ASIO_HAS_STD_STRING_VIEW` and coerce Boost into including `<string_view>` and not `<experimental/string_view>`.

I know this is a kludge, but it seems to work. I could build the binary, launch it and play with it. Naturally it will be removed at first opportunity.

Opinions?

**Comment by michaelld** [comment]
If it works right now, go for it! You can always revisit once the Boost update is in place. And, actually, you'll probably be tagged on a PR for the Boost update to make sure your port works with the updated Boost.

**Pull request merged**
