### PR TITLE
jython: update to 2.7.1

### PR DESCRIPTION
**Pull request by amake**

### CODE REVIEW

**Comment by ilovezfs** [comment]
website (and livecheck) still show 2.7.0

**Comment by amake** [comment]
The official website apparently has not been updated yet.

Release announcement on official userlist:
https://sourceforge.net/p/jython/mailman/message/35923248/

**Comment by ilovezfs** [comment]
@amake cool thanks: https://github.com/Homebrew/homebrew-core/pull/15226

**Comment by raimue** [comment]
Why was the check for java removed? The commit message does not mention or explain it.

**Comment by amake** [comment]
Because the source can now be built with Java 8. It previously required Java 7, which is no longer readily available.

**Pull request closed without merging**
