### PR TITLE
MacPass: New port

### PR DESCRIPTION
**Pull request by Janosch**
#### Description
[Macpass](https://github.com/MacPass/MacPass), a native macOS KeePass client.

###### Tested on

macOS 11.1 20C69
Xcode 12.3.0.0.1.1607026830

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by Janosch** [comment]
Note: As proposed from Andrew from macports-users, I will create separate portfiles for all dependencies currently fetched by carthage. This will take some time.

**Please do not merge yet!**

**Comment by Janosch** [comment]
Status update: The macpass ports and its depedencies are now working on Big Sur. I also got rid of the Sparkle dependency as suggested on macports-users.

Currently I am investigating if I can get rid of fetching the submodules via git. This was also suggested on macports-users. Will report back soon.

**Comment by Janosch** [comment]
This PR is now ready to get reviewed. Please note that macpass depends on macOS SDK 11. The submodules are not fetched with git anymore, as suggested on the mailing list.

**Comment by Janosch** [comment]
@kencu Can you please remove the wip label? I think I don't have the permission to do that.

**Comment by Janosch** [comment]
FYI: The _macos-10.15_ and _macports.macports-ports_ checks fail because this port only builds for macOS SDK 11, so this is not a surprise. The _macos-11.0_ check is cancelled because the aforementioned checks failed. Therefore, the failing checks do not have much significance.

**Comment by kencu** [comment]
OK, thanks.

**Pull request merged**
