### PR TITLE
ompl: add variant for Python 3.8

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.3
Xcode 11.4 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
It fails in configure phase:
`Error: Failed to configure ompl: boost-numpy must be installed with +python27.
`

**Comment by MarcusCalhoun-Lopez** [comment]
> It fails in the configure phase:
> `Error: Failed to configure ompl: boost-numpy must be installed with +python27.`

What (if any) variants are you using?
By default, `ompl` uses [Python 2.7](https://github.com/macports/macports-ports/blob/13acb0474da92f07499ac7683b3dec4a645faae3/science/ompl/Portfile#L147).

How is `boost-numpy` installed?
Both `ompl` and `boost-numpy` must be using the [same Python](https://github.com/macports/macports-ports/blob/13acb0474da92f07499ac7683b3dec4a645faae3/science/ompl/Portfile#L108).

None of these behaviors are new.
The pull request just adds Python 3.8 to the mix.

**Comment by mf2k** [comment]
The error is from the builder.

**Comment by MarcusCalhoun-Lopez** [comment]
> The error is from the builder.

That is because the default Python versions for `boost-numpy` and `ompl` are different (3.8 and 2.7 respectively).
Again, this behavior is not new.

**Comment by mamoll** [comment]
The default version of Python in ompl should match the one in boost-numpy. Can you update the PR to change the default in OMPL?

**Comment by MarcusCalhoun-Lopez** [comment]
The requested changes have been made.

**Pull request merged**
