### PR TITLE
qt5, py-pyside2: update to 5.15.12

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Apply recent security patches

#### Description
https://github.com/qt/qtreleasenotes/blob/dev/qt/5.15.12/release-note.md

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [x] security fix

###### Tested on

macOS 12.7.1
Xcode 14.2
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
@chrstphrchvz @pmetzger please add the py312 subport for `py-pyside2` as well

**Comment by chrstphrchvz** [comment]
> @chrstphrchvz @pmetzger please add the py312 subport for `py-pyside2` as well

I will not attempt this anytime soon. Please see https://wiki.qt.io/Qt_for_Python_Development_Notes
This 5.15.12 release predates upstream efforts to support Python 3.12. In February 2023, upstream said:

> 3.12 compatibility changes will reach 5.15, 6.2, and the future 6.5 LTS

…but then said in July 2023:

> Python 3.12 support will be back-ported to 6.5 only, and not 6.2

I do not know if “compatibility changes” and “support” mean different things, so I would not be certain that PySide2 will work with Python 3.12.
To my knowledge, PySide2 is not included in the KDE Qt5 patch collection. Maybe some other package manager will make PySide2 work with Python 3.12, but I am currently not interested in copying that effort over to MacPorts.

**Comment by chrstphrchvz** [comment]
The macOS 12 CI failed to build `qt5-mysql-plugin` using `mariadb`. This is due to a change in 5.15.12. The problem was reported upstream: https://bugreports.qt.io/browse/QTBUG-109832
…and should be fixed in 5.15.13, so I will likely attempt to backport the fix.

**Comment by pmetzger** [comment]
Should I be committing this given the CI failure?

**Comment by chrstphrchvz** [comment]
I expect the CI to fail to build qt5-qtwebengine (and dependents) and qt5-qtwebkit rather than time out, as seen before: https://github.com/macports/macports-ports/pull/20264#issuecomment-1703701842

**Comment by pmetzger** [comment]
But again, should I be committing this?

**Comment by chrstphrchvz** [comment]
The latest CI run timed out, and the only failed builds were for qt5-qtwebengine, for the reason expected. So I do not think the CI failure should prevent merging.

**Pull request merged**
