### PR TITLE
rav1e: update 0.5.1->0.6.2 & revbump dependents

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by i0ntempest** [comment]
Seems to be missing libiconv dep

**Comment by MarcusCalhoun-Lopez** [comment]
> Seems to be missing libiconv dep

Thank you for noticing.
libiconv should now be a library dependency.

**Comment by i0ntempest** [comment]
Looks like the addition did not solve this error:
```
= note: Undefined symbols for architecture x86_64:
[3037](https://github.com/macports/macports-ports/actions/runs/3843092670/jobs/6545043766#step:8:3052)
              "_libiconv", referenced from:
[3038](https://github.com/macports/macports-ports/actions/runs/3843092670/jobs/6545043766#step:8:3053)
                  _git_fs_path_iconv in liblibgit2_sys-8584dfb77a26ba6a.rlib(fs_path.o)
[3039](https://github.com/macports/macports-ports/actions/runs/3843092670/jobs/6545043766#step:8:3054)
              "_libiconv_close", referenced from:
[3040](https://github.com/macports/macports-ports/actions/runs/3843092670/jobs/6545043766#step:8:3055)
                  _git_fs_path_iconv_clear in liblibgit2_sys-8584dfb77a26ba6a.rlib(fs_path.o)
[3041](https://github.com/macports/macports-ports/actions/runs/3843092670/jobs/6545043766#step:8:3056)
              "_libiconv_open", referenced from:
[3042](https://github.com/macports/macports-ports/actions/runs/3843092670/jobs/6545043766#step:8:3057)
                  _git_fs_path_iconv_init_precompose in liblibgit2_sys-8584dfb77a26ba6a.rlib(fs_path.o)
[3043](https://github.com/macports/macports-ports/actions/runs/3843092670/jobs/6545043766#step:8:3058)
            ld: symbol(s) not found for architecture x86_64
[3044](https://github.com/macports/macports-ports/actions/runs/3843092670/jobs/6545043766#step:8:3059)
            clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by MarcusCalhoun-Lopez** [comment]
I am not sure why this error only happens sometimes on my machine, but the problem seems fixes when LIBRARY_PATH is set to ${prefix}/lib.
The latest pull request should reflect this.

**Review by i0ntempest — APPROVED** [review]

**Comment by i0ntempest** [comment]
Merging in 24h if no one objects

**Comment by MarcusCalhoun-Lopez** [comment]
Thank you.
I certainly have no objections.

**Pull request merged**
