### PR TITLE
qt5-{qtbase,qtscript}: remove unneeded dependencies

### PR DESCRIPTION
**Pull request by yan12125**
#### Description

1. libmng and tiff for qtbase

Apparently vestiges from qt4. The usages have been split into
qtimageformats.

2. qttools for qtscript

qt5-qttools brings clang and several other heavy ports. That
dependency is not needed for qtscript as analyzed below.

The dependency qttools of qtscript was added in 5251d66664e3 to be
consistent with http://code.qt.io/cgit/qt/qt5.git/tree/.gitmodules.
Here are some relevant commits in qt5.git:

https://code.qt.io/cgit/qt/qt5.git/commit/?id=06c3d40cc90ae33a4d06b3dc21b9c0f23ad00c35
(move module dependencies from qt.pro to .gitmodules)

https://code.qt.io/cgit/qt/qt5.git/commit/?id=758d922716ebdedeaa6fa26369c8dbb9dff4bae4
(Refine qt-module dependencies for massively parallel builds)

In the second commit, qttools is added as a dependency of qtscript as

> QtScript should be build after QtTools because an example uses UiTools.

As the qt5-qtscript port does not build examples, the dependency
qt5-qttools is not needed.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
Not tested

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Seems like a good idea but this is @MarcusCalhoun-Lopez's department.

**Comment by yan12125** [comment]
Thank you! I addressed the issues for aqua/qt5. Could you have a look again? If that looks good, I will mirror changes to older qt5 ports.

**Comment by MarcusCalhoun-Lopez** [comment]
These changes look good.
As soon as they are mirrored in the other Qt 5 ports (thanks for volunteering), we can go ahead and merge.

**Comment by yan12125** [comment]
Done mirroring!

**Comment by MarcusCalhoun-Lopez** [comment]
Thank you for your work.

**Comment by tenzap** [comment]
Seems there are regressions ? qt511-qtbase doesn't compile on ElCapitan and there are also issues with qt5-qtbase on Sierra for eg.

See tickets :
https://trac.macports.org/ticket/59314
https://trac.macports.org/ticket/59315

**Pull request merged**
