### PR TITLE
ghidra: update to 11.1.2

### PR DESCRIPTION
**Pull request by crowell**
#### Description

[ghidra: update to 11.1.2](https://github.com/macports/macports-ports/commit/5022bb5f11bd2e6ad51263e11181b9bfb2b31bf5)

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.5 23F79 arm64
Xcode 15.4 15F31d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
CI failed. Any idea what happened?

**Comment by pmetzger** [comment]
@crowell Any news?

**Comment by pmetzger** [comment]
@crowell Are you still working on this?

**Comment by ryandesign** [comment]
> CI failed. Any idea what happened?

We can easily look into the CI logs to see what happened:

```
> Configure project :
Gradle: 8.9
Python3 command:  python3 (version 3.9)
Python3 pip version: 21.2.4
OS: Mac OS X
Arch: aarch64
Using platform: mac_arm_64

> Configure project :Debugger-agent-dbgeng
WARNING: dbgmodel.tlb omitted from ghidradbg python package

> Task :init FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':init'.
> Aborting build initialization due to existing files in the project directory: '/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_ghidra/ghidra/work/ghidra-11.1.2'.

* Try:
> Remove any existing files in the project directory and run the init task again.
> Enable the --overwrite option to allow existing files to be overwritten.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.9/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1m 3s
1 actionable task: 1 executed
```

I'm not able to make sense of that however; I don't grok gradle.

**Comment by pmetzger** [comment]
@crowell ?

**Comment by reneeotten** [comment]
please reopen once you had time to work out the issues.

**Pull request closed without merging**
