### PR TITLE
creduce: bump to 2.8.0

### PR DESCRIPTION
**Pull request by kencu**
change llvm dependency to 6.0
remove unrequired dependencies on
  astyle, gindent, p5-sys-cpu
add size param
add tests

closes:  https://trac.macports.org/ticket/57591
closes:  https://trac.macports.org/ticket/57592

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.2 18C54
Xcode 10.1 10B61 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
Not certain at this moment if this port also needs to force `libc++` on systems configured to `non-libc++` -- it probably does, and that might cause issues. So therefore for now, at least, <https://trac.macports.org/ticket/52998> is left open.

Builds and runs without trouble. I ran the test suite -- it does really quite poorly on the test suite -- which was quite disheartening until I ran the test suite on the previous version of `creduce` on 10.13 and it did almost exactly as bad.

I did not actually use `creduce 2.8.0` to reduce a build failure, FYI.

**Comment by kencu** [comment]
The port builds down to 10.9, but on 10.8 configured with the default (non-libc++) configuration, the cxx11 1.1 PG throws in some confusion with a build line like this, which is clearly not going to work out.
```
/opt/local/bin/clang++-mp-5.0 -DHAVE_CONFIG_H -I. -I..   -I"/opt/local/libexec/llvm-6.0/include/clang" -I/opt/local/include -I/opt/local/libexec/llvm-6.0/include -pipe -std=c++11 -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -std=c++11 -DNDEBUG -fno-exceptions -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti -fno-exceptions -pipe -Os -D_GLIBCXX_USE_CXX11_ABI=0 -stdlib=macports-libstdc++ -arch x86_64 -MT clang_delta-RemoveTrivialBaseTemplate.o -MD -MP -MF .deps/clang_delta-RemoveTrivialBaseTemplate.Tpo -c -o clang_delta-RemoveTrivialBaseTemplate.o `test -f 'RemoveTrivialBaseTemplate.cpp' || echo './'`RemoveTrivialBaseTemplate.cpp
```
And that then generates screenfuls of c++11-ABI mismatched link errors to no great surprise.

Most likely we need to disable builds if the stdlib is not libc++ (or force it to libc++)

**Comment by pmetzger** [comment]
@kencu I'll leave it to you to figure out what to do here. I'm guessing we won't hear from @larryv though I could be surprised. I don't really know enough to have a personal opinion on correctness.

**Comment by kencu** [comment]
I'm sure about the fixes. Bikeshedding is always on the horizon, tho. Port is broken on cuurent OS. Give it the 72h, then we'll commit.

**Comment by kencu** [comment]
Agreed. This works. Port is currently broken on the present lead system. I'll take the heat for any fallout.

**Pull request merged**
