### PR TITLE
Update pure and pure-docs to 0.66

### PR DESCRIPTION
**Pull request by agraef**
This updates pure to 0.66, the latest bugfix release, along with the corresponding documentation package pure-docs. It also removes all the "hotfix" patches; the corresponding changes are all in 0.65+ now and thus the patches are not needed any more.

Note that I also removed the "openbrowser" patch. This has been there for a *long* time; I think that Ryan Schmidt originally added it as a special convenience for OS X users (it replaces the default action to invoke w3m as help browser in the interpreter with the default browser).

The problems with the "openbrowser" patch are (1) that it is at odds with how the Pure interpreter works by default on *every* other platform, and (2) that it broke virtually *every* update of the pure port in MP, as the patch *never* applied cleanly because of source and documentation changes. This added a lot of complication to keeping the port updated, for something that the user can easily do him/herself by just adding `PURE_HELP=open` to the environment.

### CODE REVIEW

**Comment by agraef** [comment]
Augmented the pure-docs Portfile to add a variant which allows the TeXmacs-formatted documentation to be installed along with the html documentation.

**Comment by agraef** [comment]
No takers yet? Can someone with commit access **please** take a look? This is a bugfix release fixing a crash bug in the compiler, so it's important enough for *some* users.

**Comment by agraef** [comment]
Pure 0.66 was released. Rebased and updated the Portfiles accordingly.

**Comment by g5pw** [comment]
👍 The patches look good to me. The openbrowser patch is probably to avoid depending on `w3m`? I'd like @ryandesign to OK the removal of that before committing though.

**Comment by agraef** [comment]
@g5pw, thanks a lot for having a look! Concerning the openbrowser feature, don't you think that @ryandesign would have commented already if he considered it essential? Also, I should mention that this feature doesn't even *work* in the latest MP any more. (Sorry, I forgot to record the error message I get when using this, but I can reproduce it if needed.) So Pure's `help` command is actually *broken* with the openbrowser patch right now, which is a really bad regression being caused by MP, not upstream.

Thus IMHO there's in fact **no** other option than to remove the openbrowser patch at present, unless someone fixes the openbrowser utility really quickly (not me). And as Pure's main developer I certainly feel that this update, which has been hanging in the queue here already for more than a week, shouldn't be delayed any longer. After all it brings some *really* important bugfixes, whereas the openbrowser issue is rather trivial in comparison, and can in any case be addressed at a later time. So I can only ~~strongly urge~~ politely ask you to get this PR merged *now*. :)

**Comment by g5pw** [comment]
> Also, I should mention that this feature doesn't even work in the latest MP any more. (Sorry, I forgot to record the error message I get when using this, but I can reproduce it if needed.) So Pure's help command is actually broken with the openbrowser patch right now, which is a really bad regression being caused by MP, not upstream.

Well yeah, you *should* have mentioned that 😄

> So I can only politely ask you to get this PR merged now. :)

Well, you *did* raise a valid point, so...

**Comment by agraef** [comment]
> The openbrowser patch is probably to avoid depending on w3m?

Not really, I guess the original intent was to improve usability for typical Mac users, who might feel uncomfortable with text-based browsers.

I'd argue that, however. If someone, even a Mac user, feels uncomfortable working in the terminal, he probably shouldn't be running the interpreter from the command line in the first place. There are other options to run the interpreter interactively, e.g., via Pure Emacs mode in [Aquamacs](https://bitbucket.org/purelang/pure-lang/wiki/PureOnMacOSX#markdown-header-pure-and-aquamacs). In any case, I updated the Pure wiki with information for Mac users concerning this precise issue in the [Pure on Mac OS X](https://bitbucket.org/purelang/pure-lang/wiki/PureOnMacOSX#markdown-header-browsing-the-online-help) wiki page, so any Mac user should be able to figure out how to set the `PURE_HELP` variable now.

**Comment by agraef** [comment]
> Well yeah, you should have mentioned that 😄

@g5pw, sure thing, but I submitted this PR before even noticing that openbrowser was broken. 😉

**Comment by agraef** [comment]
Also, thanks for merging. I'm at ease again. 😎

**Comment by g5pw** [comment]
No problem. I guess we can always backport the patch if there's need.

**Comment by agraef** [comment]
There seems to be something going wrong with the buildbots. I'm getting a bunch of failures due to the build servers not being able to get the source tarballs from Bitbucket, even though they are all there and download all right for me. The errors look like this:

~~~
Error: Failed to fetch pure: Operation too slow. Less than 1024 bytes/sec transfered the last 60 seconds
~~~

@g5pw Do you have access to the build servers and see what's going on there?

**Comment by ryandesign** [comment]
> Concerning the openbrowser feature, don't you think that @ryandesign would have commented already if he considered it essential?

I have not been reading this PR, so I was not aware you were proposing removing openbrowser, nor was I aware it was not working. Please file a ticket for the latter.

**Comment by agraef** [comment]
@ryandesign, sorry, I forgot to explicit mention you with your MP handle. Anyway, here's the ticket that you asked for: https://trac.macports.org/ticket/53745. There's also an older ticket for El Capitan which has been open for 11 months now; the error message is different, though: https://trac.macports.org/ticket/51102

Note that I'm *not* proposing to completely remove openbrowser, just the openbrowser *patch* in the pure port, for the reasons laid out in the description of this PR. openbrowser itself is definitely useful, once it's fixed up to work with the latest supported macOS versions.

**Pull request merged**
