### PR TITLE
qt5-qtwebkit: switch jpeg dependencies to libjpeg-turbo

### PR DESCRIPTION
**Pull request by jhoyt4**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.2.1 20D74
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jhoyt4** [comment]
@jmroot - Hi Josh, I caught last week that qt5-qtwebkit didn't get updated properly in the mass libjpeg-turbo shift.  I've updated the qt5 Portfile to correct this.  Would you mind reviewing my updates?

**Comment by kencu** [comment]
this is a beast. all the ci builds fail. please show a few successful builds that you have so we know it works.

I notice you don't do anything beyond make sure that turbojpeg is installed when this is built. Is it found somehow automagically by the build script if it is sitting there? Are we supposed to send some kind of configuration to the build to make sure it is used?

Could you show a bit of info showing that it is actually linked in to something to prove that it was in fact picked up and is being used?

**Comment by kencu** [comment]
And, I guess -- how many systems did you try this on? Your commit message there says just BigSur 11.2.1 -- intel only no doubt as it doesn't build on arm64 as I recall.

According to <https://ports.macports.org/port/qt5-qtwebkit/summary> this was not building on BigSur Intel on the buildbot, although I seem to recall I built it on BigSur just before I pushed all the updates to this back in December.

**Comment by jmroot** [comment]
The CI failures are concerning (looks like it timed out?), but the change looks OK. I take it the build just links with -ljpeg, so it previous got the link to IJG libjpeg.9.dylib (pulled in by a dependency) but now would get libjpeg-turbo's libjpeg.8.dylib.

**Comment by jhoyt4** [comment]
That is correct about updating the dylibs - I discovered last week that I had a user unable to run an app I was bundling (mythtv), due to qt5-webkit missing libjpeg.9.dylib. @ctreleaven pointed me to the mass libjpeg-turbo update from weeks back and speculated that this package was missed as there was no note in the port file.

Currently it inherits whatever libjpeg is installed by qt5-qtbase.  Unfortunately for users that already have qt5.15.2 installed, this means they got an update in qt5-qtbase to libjpeg-turbo but no update to qt5-webkit without uninstalling jpeg and running a rev-upgrade (which triggers a qt5-webkit recompile).  This caused me a bunch of pain, so this update is to try to prevent that pain on other users.

As for the logs, I was watching the 10.15 pipeline when it went into limbo.  Basically it justified  stopped scrolling at the 3.5 hour mark, not errors from what I could see.  I was waiting for a full timeout to double check the logs.

**Comment by ctreleaven** [comment]
John, I meant to get back to you on this.  I looked with otool -L at the dylibs that qt5-qtwebkit installs and saw no linkage to anything jpeg.  Where does this link happen?

**Comment by jhoyt4** [comment]
to answer some of @kencu's questions which have disappeared:

"Is it found somehow automagically by the build script if it is sitting there?" - To be honest, I am not sure.  I do know it will pick up whatever libjpeg is installed by qt5-base.  I just wanted something in the subport pointing to the same libjpeg to trigger a rebuild keeping qt5-qtwebkit in sync with qt5-base.  Happy to have a suggestion on a better method.

"Are we supposed to send some kind of configuration to the build to make sure it is used?" Not that I am aware of.  After uninstalling jpeg, the a rev-upgrade got everything working and pointed to libjpeg-turbo without any changes to the current port file

"Could you show a bit of info showing that it is actually linked in to something to prove that it was in fact picked up and is being used?" Well crud, apparently I need to do more here to get it linking.  Suggestions on what to try next?
```
QtWebKit.framework % otool -L QtWebKit 
QtWebKit:
    ::snip::
	/opt/local/lib/libjpeg.8.dylib (compatibility version 8.0.0, current version 8.2.2)
	::snip::
```

"how many systems did you try this on?" I have built on Big Sur, Catalina, and High Sierra and shown to work but that's porbably due to it pointing back to libjpeg.8.dylib...

**Comment by jhoyt4** [comment]
Hi Craig - here's the full path to the QtWebKit lib that links in libjpeg:

/opt/local/libexec/qt5/lib/QtWebKit.framework/QtWebKit

**Comment by jmroot** [comment]
> "Could you show a bit of info showing that it is actually linked in to something to prove that it was in fact picked up and is being used?" Well crud, apparently I need to do more here to get it linking. Suggestions on what to try next?
> 
> ```
> QtWebKit.framework % otool -L QtWebKit 
> QtWebKit:
>     ::snip::
> 	/opt/local/lib/libjpeg.8.dylib (compatibility version 8.0.0, current version 8.2.2)
> 	::snip::
> ```

I'm not sure what you mean. That's the way I would expect it to be linked.

**Comment by jhoyt4** [comment]
> I'm not sure what you mean. That's the way I would expect it to be linked.

Happy to be wrong :) - I had [incorrectly] assumed that it would point to /opt/local/libexec/ - not sure why, probably need more coffee this AM.

**Comment by jhoyt4** [comment]
I just pulled down the logs from the buildbot - the 10.15 build just stops on this line (no errors):
`2021-02-13T17:38:05.5012200Z ./share/nls/fi_FI.ISO8859-15 missing (created)`

11 dies with this message:
`2021-02-13T21:27:31.3603430Z ##[error]The operation was canceled.`

Both issues indicate some underlying issue with the buildbot timing out.  This was also the case on the last few updates to qt5.  The full Portfile is a beast that takes many many hours to fully build everything.

**Comment by kencu** [comment]
> to answer some of @kencu's questions which have disappeared:

Yeah -- I had a few questions. But Josh came along right after me and said it all looked fine to him, so my questions then just seemed silly in that context, so I deleted them.

**Pull request merged**
