### PR TITLE
fava: update to 1.27, use py312

### PR DESCRIPTION
**Pull request by mrdomino**
#### Description

The py311-markdown2 tests fail, but they also fail for py310-markdown2 in the same way, so this does not look like a regression in this change.

fava itself has tests, but I could not get them working after some fiddling, so I gave up. The program itself works on my test case (my personal finances.)

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.2.1 23C71 arm64
Xcode 15.2 15C500b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
Our default version of python is now 3.12; does the package work with 3.12?

**Comment by mrdomino** [comment]
It does; I've pushed commits that make it do so, including pulling in #22182, which it depends on. Let me know how you want me to handle squashing the commits.

**Comment by mrdomino** [comment]
I'm having a hard time understanding the github actions log, but it looks like it's failing on py-markdown2, and that may be an expected failure.

**Comment by pmetzger** [comment]
@reneeotten Opinion?

**Comment by mrdomino** [comment]
Ah, okay, it seems like the failure is on installing `py27-protobuf3`?

**Comment by mrdomino** [comment]
So, if we want to merge these separately, I guess I (or you?) can rebase after the dependent changes are merged. The order would be: 1. #22212, 2. #22182, 3. #22183.

Or just take this PR as an omnibus, and I can squash everything into one commit.

**Comment by mrdomino** [comment]
(Rebased post #22212.)

**Comment by pmetzger** [comment]
Okay, I think they're all done now!

**Pull request merged**
