### PR TITLE
kdepimlibs4: fix compiler choice

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Also improve text layout in portfile.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
CI failures are unrelated to fixes here, obviously.
See: https://trac.macports.org/ticket/68452

**Comment by ryandesign** [comment]
Why is C++11 required? What was the error?

**Comment by barracuda156** [comment]
> Why is C++11 required? What was the error?

Should have been something obvious, but now I will need to rerun the build without it to see.

**Comment by barracuda156** [comment]
@ryandesign Oh well, take a look at the next line :)
It is MacPorts which forces C++11, but does not set the standard, which breaks the configure, obviously:
```
-- Check for working CXX compiler: /usr/bin/g++-4.2
-- Check for working CXX compiler: /usr/bin/g++-4.2 - broken
CMake Error at /opt/local/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:73 (message):
  The C++ compiler

    "/usr/bin/g++-4.2"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_kde_kdepimlibs4/kdepimlibs4/work/build/CMakeFiles/CMakeScratch/TryCompile-ksYUaX'
    
    Run Build Command(s): /opt/local/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_aa3d4/fast
    /usr/bin/make  -f CMakeFiles/cmTC_aa3d4.dir/build.make CMakeFiles/cmTC_aa3d4.dir/build
    Building CXX object CMakeFiles/cmTC_aa3d4.dir/testCXXCompiler.cxx.o
    /usr/bin/g++-4.2   -std=c++11  -arch ppc -mmacosx-version-min=10.6 -o CMakeFiles/cmTC_aa3d4.dir/testCXXCompiler.cxx.o -c /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_kde_kdepimlibs4/kdepimlibs4/work/build/CMakeFiles/CMakeScratch/TryCompile-ksYUaX/testCXXCompiler.cxx
    cc1plus: error: unrecognized command line option "-std=c++11"
    make[1]: *** [CMakeFiles/cmTC_aa3d4.dir/testCXXCompiler.cxx.o] Error 1
    make: *** [cmTC_aa3d4/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


-- Configuring incomplete, errors occurred!
```

**Pull request merged**
