### PR TITLE
KeePassXC: new port, version 2.2.0

### PR DESCRIPTION
**Pull request by yan12125**
###### Description

Apparently security/KeePassX is no longer maintained. KeePassXC is a
continuation of the original project.

###### Tested on
macOS 10.12.5 (Sierra)
Xcode 8.3.3

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? (no relevant trac ticket)

- [x] checked your Portfile with `port lint`?
Currently it says:
```
Error: invalid license CC0-1: missing hyphen before version.
```
However, CC0 is the exact name of the license. The number 0 indicates the author of relevant files keep NO rights, not its version number. The version KeePassXC uses is CC0 1.0, which can be seen from https://github.com/keepassxreboot/keepassxc/blob/develop/LICENSE.CC0
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by l2dy** [comment]
KeePassXC is under `GPL-2+`. The CC0 license file is only for a few icons.

See https://github.com/keepassxreboot/keepassxc/blob/develop/COPYING#L205.

**Comment by yan12125** [comment]
Thanks updated.

**Comment by yan12125** [comment]
Hmm, Travis tests failed as cairo can't install, just like #522. Any news for more verbose logs on Travis?

**Comment by l2dy** [comment]
I'm working on it. Logs will be uploaded to https://paste.macports.org/.

The cairo bug is probably related to https://lists.macports.org/pipermail/macports-dev/2017-June/035978.html.

**Comment by l2dy** [comment]
The cairo bug was fixed but Travis test failed.

https://paste.macports.org/bd9fc4a79c89:
```
CMake Error at CMakeLists.txt:211 (find_package):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  (requested version 5.2) with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
```

**Comment by yan12125** [comment]
Thanks for fixing cairo. Seems the error is caused by missing qttools. I don't have access to Mac until the next week. Let me try blind testing it by adding the necessary dependency.

**Comment by michaellass** [comment]
This port works fine for me. Thanks for your work on this! 👍

**Comment by neverpanic** [comment]
Merged, thanks for the feedback and the contribution.

**Comment by neverpanic** [comment]
Btw, @yan12125, do you want to maintain this port?

**Comment by yan12125** [comment]
> do you want to maintain this port?

That's my honor. Anything I need to do?

**Comment by neverpanic** [comment]
Send a pull request that changes the maintainer line of the port. See https://guide.macports.org/#reference.keywords.maintainers for the reference documentation of the `maintainer` keyword. If you add an email address, please use the bracketed syntax `{@githubuser domain.tld:localpart}`.

Please also decide if you want to make the port `openmaintainer` as explained in https://guide.macports.org/#project.update-policies.nonmaintainer.

**Comment by yan12125** [comment]
Thanks for the detailed guide! Opened #612

**Pull request merged**
