### PR TITLE
privoxy: Bugfix, add privoxy-pki-bundle subport that depends on other PKI bundles

### PR DESCRIPTION
**Pull request by essandess**
* Fixes: https://trac.macports.org/ticket/64892

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.3 21E230 x86_64
Xcode 13.3 13E113

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by essandess** [comment]
Note: I don't believe that the new port `privoxy-pki-bundle` should not be built by a buildbot and provided by MacPorts so that the CAs are guaranteed to be as recent as the latest ones provided by the dependent ports. How should this be reflected in the Portfile?

**Comment by mascguy** [comment]
Steve, I need to test locally with these changes, once I can take a few minutes away from work.

In the interim, if you're interested in cleaning up the path copy-pasta too, I took a stab at it here. (I only ran a quick test, but seems to work properly.) Feel free to apply my changes to this PR, if you're comfortable with that.

https://github.com/mascguy/macports-ports/tree/mascguy-privoxy-cleanup

**Comment by essandess** [comment]
@mascguy Thank you very much for the suggestions. (I imagined you had a different issue in mind with all the temp file redirections.)

Honestly, I prefer the full references in the commands to be able to follow along directly, rather than cross checking against a list of indirect references in variables, as well not clearly indicating what's in `destroot` and what's in the final install. Therefore, my preference is for the implementation in the current PR.

**Comment by mascguy** [comment]
> Honestly, I prefer the full references in the commands to be able to follow along directly, rather than cross checking against a list of indirect references in variables, as well not clearly indicating what's in `destroot` and what's in the final install. Therefore, my preference is for the implementation in the current PR.

No worries, I'm fine with that.

I'll merge once I've had a chance to test the fix locally. (Hopefully during lunch today.)

**Comment by mascguy** [comment]
> Steve, activation still fails, at least when upgrading.

Ah, just noticed your comment in the ticket, stating that forced activation is still required.

I'm guessing this isn't a new scenario though. Have you checked the Portfile Recipes page on our wiki? (Haven't re-reviewed it yet, but wouldn't be surprised if this is covered...)

**Review by mascguy — APPROVED** [review]

**Pull request merged**
