### PR TITLE
moc: patches to build on BigSur / M1

### PR DESCRIPTION
**Pull request by srirangav**
#### Description

Update to build on BigSur / M1

###### Type(s)

- [X] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.6
Xcode 12.5.1

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
@srirangav I don't know anything about this port but why would you need to (re)define `snprintf` - isn't that part of the standard C library?

**Comment by srirangav** [comment]
Hi @reneeotten,

I think that a prototype for snprintf should normally be found in <stdio.h>, but for some reason in the two files I patched, interface_elements.c and utf8.c, despite <stdio.h> being included in both files (in interface_elements.c it is included directly, and in utf8.c it is included indirectly through log.h), during the build on BigSur / M1, I see the following error (full log attached):

`interface_elements.c:2549:4: error: implicitly declaring library function 'snprintf' with type 'int (char *, unsigned long, const char *, ...)' [-Werror,-Wimplicit-function-declaration]
                        snprintf (pct, sizeof (pct), "  %02.0f%%  ", b->filled);
                        ^
interface_elements.c:2549:4: note: include the header <stdio.h> or explicitly provide a declaration for 'snprintf'
1 error generated.`

I added in an explicit prototype for snprintf to get past this error and get moc to build.  I'm not sure this is the right way to do this, but it seemed like the simplest way to fix the problem.

**Comment by reneeotten** [comment]
@srirangav I don't claim I understand this... but a quick search shows that @ryandesign experienced a similar issue and fixed it like this (see https://github.com/gphoto/libgphoto2/issues/553):

```
configure.cflags-append \
                -D_DARWIN_C_SOURCE
```

can you try that?

**Comment by srirangav** [comment]
Hi @reneeotten,

I made the change you suggested and remove the two patch files I added.  The port seems to build and install correctly.  I've committed my change and have tried to squash my commits.  Hopefully this has worked properly.

Thanks,

-ranga

**Comment by reneeotten** [comment]
> I made the change you suggested and remove the two patch files I added. The port seems to build and install correctly. I've committed my change and have tried to squash my commits. Hopefully this has worked properly.

thanks for the changes @srirangav, the squashing didn't work properly as you still have two commits but we can do that while merging for now. For future reference you can either amend a commit when changes are requested (i.e., do `git commit --amend` once you've made the changes) or you can add new commits and then squash them afterwards. The latter would be ```git rebase -i HEAD~N``` (where N = the number of commit you have so in this case 2), then for every commit you want to be incorporated in the first one you would change `pick` to `fixup`); since you rewrote your git history by doing so you'll need to force-push the changes to your fork (i.e., `git push origin -f`). 

That explanation should hopefully be clear enough, otherwise Googling "git rebase" will give you many more examples/explanations.

**Comment by srirangav** [comment]
Hi @reneeotten,

I have a question about quashing my commits - I did `git commit --amend` when I made my most recent commit, then I did a `git push origin -f moc-2.6-alpha1_6` to push it back to the branch I made for this pull request.  But based on your comment above, that didn't work right.  Should I just have done a `git push origin -f` without any branch?

Thanks,

-ranga

**Pull request merged**
