### PR TITLE
albafetch: fix build on macOS <10.9, refactor patch

### PR DESCRIPTION
**Pull request by aeiouaeiouaeiouaeiouaeiouaeiou**
#### Description

Tweaked the patch a bit, I'll do a PR in the upstream later.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 10K549 x86_64
Xcode 3.2.6 10M2518

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by barracuda156 — APPROVED** [review]
Assuming this has been tested, LGTM

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@reneeotten @herbygillot

**Comment by barracuda156** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou While a non-functional matter, but IMO it will be still useful to have commit titles reflecting what is fixed more accurately.

Someone looking through history will assume it was broken on < 10.9 before, which is not strictly the case. What was broken is only one of 3 arches (or 2 of 4, if we assume ppc64 is buildable).

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@barracuda156 that's why I added "refactor", let's see which solution is better by the maintainers.

**Comment by barracuda156** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou I would rather see ”fix 64-bit builds on < 10.9” (or smth to the same effect), but no big deal.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@barracuda156 oops, [this commit](https://github.com/macports/macports-ports/commit/a3f708165116c9db1c03a60be4d73ad17383f771) was better because built binary from the packages server causes a segmentation error (`MAC_OS_X_VERSION_MIN_REQUIRED` should be in both parts of the code, but it was fine with the local test) :/

**Comment by barracuda156** [comment]
> @barracuda156 oops, [this commit](https://github.com/macports/macports-ports/commit/a3f708165116c9db1c03a60be4d73ad17383f771) was better because built binary from the packages server causes a segmentation error (`MAC_OS_X_VERSION_MIN_REQUIRED` should be in both parts of the code, but it was fine with the local test) :/

@aeiouaeiouaeiouaeiouaeiouaeiou I thought it is a fairly trivial change and did not compare patch versions, but locally it works fine, at least it starts without issues, I just tried.

**Pull request merged**
