### PR TITLE
PULL_REQUEST_TEMPLATE.md: add line about variants

### PR DESCRIPTION
**Pull request by cooljeanius**
#### Description

One of the things I like about MacPorts is how many ports offer variants to enable extra features. I often try to install my ports with maximum possible variants enabled when possible. Unfortunately, it seems that some of the non-default variants don't get tested as much, which often leads to breakage when I try to update. This PR simply adds an extra checkbox to the PR template reminding PR authors to check their variants. The header for that section includes a `<!-- (delete not applicable items) -->` comment, so if it isn't relevant to certain ports, it can always be skipped. This is just to give a bit of an extra reminder for the cases where variants *are* relevant.

###### Type(s)
- [x] enhancement

###### Tested on
macOS 11.7.1 20G918 x86_64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked that any [variants](https://trac.macports.org/wiki/Variants) the Portfile may have haven't been broken?

### CODE REVIEW

**Comment by catap** [comment]
Not sure that it is good idea.

For example `mpi` PG introduces a low of heavy variants: https://ports.macports.org/port/mumps/details/ which conflicts and simple enable all of them is not possible.

**Comment by barracuda156** [comment]
There are, I believe, arch-specific variants, which cannot be built on some other archs.

**Comment by cooljeanius** [comment]
I mean yeah, I get that testing every single combination of variants is often impossible, but I still think it ought to be possible for maintainers to at least test more variants than they're currently testing.

**Review by neverpanic — APPROVED** [review]
I like the idea. This gets a +1 from me.

**Comment by catap** [comment]
To be clear: I also like this idea, but I afraid that it can't be required for a lot of ports. But, still, as reminder to test it... it is very nice idea.

**Comment by cooljeanius** [comment]
> To be clear: I also like this idea, but I afraid that it can't be required for a lot of ports. But, still, as reminder to test it... it is very nice idea.

Is the change in wording in [c0d7f5a](https://github.com/macports/macports-ports/pull/16773/commits/c0d7f5aa3e52a8da4bb65547b0015be9e9f57890) an improvement? I tried to make it sound like less of a requirement to do all of them, and instead more of a reminder just to check the most important ones.

**Comment by catap** [comment]
@cooljeanius cleaner, thanks! I like that!

**Comment by cooljeanius** [comment]
> @cooljeanius cleaner, thanks! I like that!

OK, someone else will need to merge it, then, as I don't have the permissions necessary for that...

**Pull request merged**
