### PR TITLE
libsdl2 support libs: require immintrin.h

### PR DESCRIPTION
**Pull request by kencu**
not found with gcc-3.* or gcc-4.*

fixes build on 10.6 where clang is not the default

### CODE REVIEW

**Comment by cjones051073** [comment]
LGTM

**Comment by jmroot** [comment]
Chris, please don't merge PRs for maintained ports without maintainer approval or timeout. https://guide.macports.org/chunked/project.update-policies.html

**Comment by cjones051073** [comment]
I am always caught out by what I consider an inconsistency in the guidelines, in that  committers are allowed to directly make ‘minor’ changes directly for open maintainer ports, but if those very same changes are submitted as a PR it has to wait for timeout. In this case the change is in my opinion minor as it just adds compiler blacklist, fixing builds on older platforms.

**Comment by jmroot** [comment]
It's not an inconsistency, it's a way for committers to request review. Tickets with a patch attached should be treated the same way.

Ken is perfectly capable of glancing at his change and concluding that it looks superficially reasonable himself. A maintainer can often offer more insight based on their experience with the specific port.

**Comment by cjones051073** [comment]
OK, so then it depends who submits the PR.. If a committer submits it then, as they could have directly committed it themselves I agree they are implicitly asking for some kind of review, and as such I perhaps should not have merged this, my apologies. However,  note this is different to if a non committer submits a Pr with a minor change. In this case, if a committer concludes the change is minor, and something they could have directly committed themselves, then its only consistent to allow the committer to immediately accept that pr, in my view.

Please note I am really not trying to wiggle my way out of following the guidelines here, I really am not. Just trying to explain why as I review PRs and merge them, as I have been trying to do recently, its not utterly trivial to decide when something can be immediately merged or not, and as its inevitable occasionally little mistakes will be made.

**Comment by jmroot** [comment]
Thank you for trying to understand and comply with the project policies.

Yes, there is technically a loophole in that any committer could decide to commit the same thing as a proposed patch (in a PR or otherwise). But I hope good judgement would be applied before doing something like that. It could be argued that a non-committers patches are more in need of maintainer review, not less.

I think in general there's no harm in leaving the maintaining to the maintainer, until timeout occurs.

**Pull request merged**
