### PR TITLE
py-tensorflow-probability: Submission

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by essandess** [comment]
@cjones051073 I've update this to the bazel PG, but am seeing this tcl `{` issue being thrown to bash in the `post-build` block for both `bazel.post_build_cmd` and `clean`:

```
INFO: Build completed successfully, 644 total actions
DEBUG: Executing proc-post-org.macports.build-build-0
DEBUG: system -W /opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow-probability/py39-tensorflow-probability/work/probability-0.12.1: {./bazel-bin/pip_pkg /opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow-probability/py39-tensorflow-probability/work}
sh: {./bazel-bin/pip_pkg: No such file or directory
Command failed: {./bazel-bin/pip_pkg /opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow-probability/py39-tensorflow-probability/work}
Exit code: 127
Error: Failed to build py39-tensorflow-probability: command execution failed
```

**Comment by cjones051073** [comment]
> @cjones051073 I've update this to the bazel PG, but am seeing this tcl `{` issue being thrown to bash in the `post-build` block for both `bazel.post_build_cmd` and `clean`:
> 
> ```
> INFO: Build completed successfully, 644 total actions
> DEBUG: Executing proc-post-org.macports.build-build-0
> DEBUG: system -W /opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow-probability/py39-tensorflow-probability/work/probability-0.12.1: {./bazel-bin/pip_pkg /opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow-probability/py39-tensorflow-probability/work}
> sh: {./bazel-bin/pip_pkg: No such file or directory
> Command failed: {./bazel-bin/pip_pkg /opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow-probability/py39-tensorflow-probability/work}
> Exit code: 127
> Error: Failed to build py39-tensorflow-probability: command execution failed
> ```

look at how I define the command in the tensor flow port. You need to remove the quotes.

**Comment by essandess** [comment]
> look at how I define the command in the tensor flow port. You need to remove the quotes.

Thanks! That works, but there's still the `clean` line. I haven't touched that…

```
Build complete. Wheel files are in /opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow-probability/py39-tensorflow-probability/work
DEBUG: system -W /opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow-probability/py39-tensorflow-probability/work/probability-0.12.1: {CC_OPT_FLAGS=-march=x86-64 BAZEL_USE_CPP_ONLY_TOOLCHAIN=1  bazel --max_idle_secs=30 --output_user_root=/opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow-probability/py39-tensorflow-probability/work/bazel_build} clean
sh: {CC_OPT_FLAGS=-march=x86-64: command not found
Command failed: {CC_OPT_FLAGS=-march=x86-64 BAZEL_USE_CPP_ONLY_TOOLCHAIN=1  bazel --max_idle_secs=30 --output_user_root=/opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow-probability/py39-tensorflow-probability/work/bazel_build} clean
Exit code: 127
Error: Failed to build py39-tensorflow-probability: command execution failed
```

**Comment by cjones051073** [comment]
> > look at how I define the command in the tensor flow port. You need to remove the quotes.
> 
> Thanks! That works, but there's still the `clean` line. I haven't touched that…
> 
> ```
> Build complete. Wheel files are in /opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow-probability/py39-tensorflow-probability/work
> DEBUG: system -W /opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow-probability/py39-tensorflow-probability/work/probability-0.12.1: {CC_OPT_FLAGS=-march=x86-64 BAZEL_USE_CPP_ONLY_TOOLCHAIN=1  bazel --max_idle_secs=30 --output_user_root=/opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow-probability/py39-tensorflow-probability/work/bazel_build} clean
> sh: {CC_OPT_FLAGS=-march=x86-64: command not found
> Command failed: {CC_OPT_FLAGS=-march=x86-64 BAZEL_USE_CPP_ONLY_TOOLCHAIN=1  bazel --max_idle_secs=30 --output_user_root=/opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow-probability/py39-tensorflow-probability/work/bazel_build} clean
> Exit code: 127
> Error: Failed to build py39-tensorflow-probability: command execution failed
> ```

your ports tree cannot be up to date, as I removed the use of the env vars in the clean line some time ago. Please update and try again.

**Comment by essandess** [comment]
> your ports tree cannot be up to date, as I removed the use of the env vars in the clean line some time ago. Please update and try again.

Indeed, thank you. For posterity, I wasn't aware of this `portindex` behavior when you add `file://${prefix}/ports` to `${prefix}/etc/macports/sources.conf` and throw stuff into `${prefix}/ports/_resources/port1.0/group/`. `portindex` uses the local port groups too! That can be handy. But also confusing if you're using an out-of-date copy:

```bash
sudo rm ${prefix}/ports/_resources/port1.0/group/bazel-1.0.tcl
```

**Pull request merged**
