### PR TITLE
BlackHole: Adding maintainer

### PR DESCRIPTION
**Pull request by adarshp**
#### Description

This PR adds myself as a maintainer on the BlackHole port.

### CODE REVIEW

**Comment by adarshp** [comment]
Not sure why this is failing. Build @202000412.18 fails with this error message in the 'test' phase:

    Building 'BlackHole' ... [ERROR] maintainers: adarsh@arizona.edu

But I had simply followed the pattern in https://guide.macports.org/chunked/reference.html#reference.keywords.maintainers . (`sudo port -vst install` succeeds for me on my computer)

**Comment by ra1nb0w** [comment]
the log is https://paste.z0k.xyz/b88593b3d0a0
failure is in the install phase (`/Library/Audio/Plug-Ins/HAL/BlackHole.driver`)
All is correct. merge. thank you.

**Comment by adarshp** [comment]
> the log is https://paste.z0k.xyz/b88593b3d0a0
> failure is in the install phase (`/Library/Audio/Plug-Ins/HAL/BlackHole.driver`)
> All is correct. merge. thank you.

Thanks!

**Comment by ra1nb0w** [comment]
next time, be more precise with the commit message (in this case: "add myself as co-maintainer")

**Comment by adarshp** [comment]
> next time, be more precise with the commit message (in this case: "add myself as co-maintainer")

Sure thing, will do.

**Pull request merged**
