### PR TITLE
qtiplot: fix the build

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

This should fix the build. Currently the port has been failing across the board: https://ports.macports.org/port/qtiplot/details/

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
Hmm, why though? This is unrelated to my patches.

```
2022-08-06T20:26:24.4114830Z clang: error: no such file or directory: '../3rdparty/qwtplot3d/lib/libqwtplot3d.a'
2022-08-06T20:26:24.4159950Z make[1]: *** [qtiplot.app/Contents/MacOS/qtiplot] Error 1
2022-08-06T20:26:24.4160960Z make[1]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_aqua_qtiplot/qtiplot/work/qtiplot-0.9.8.9/qtiplot'
2022-08-06T20:26:24.4168930Z make: *** [sub-qtiplot-all] Error 2
```

**Comment by barracuda156** [comment]
@mascguy Any idea why bot complains? The error cannot be caused by my patches.

**Comment by mascguy** [comment]
> @mascguy Any idea why bot complains? The error cannot be caused by my patches.

This port is failing to build everywhere, so additional work is needed to fix it:

https://ports.macports.org/port/qtiplot/details/

**Comment by barracuda156** [comment]
> > @mascguy Any idea why bot complains? The error cannot be caused by my patches.
> 
> This port is failing to build everywhere, so additional work is needed to fix it:
> 
> https://ports.macports.org/port/qtiplot/details/

@mascguy I know that is was failing, but I fixed compilation errors and built it :)
```
10:~ svacchanda$ sw_vers
ProductName:	Mac OS X Server
ProductVersion:	10.6.8
BuildVersion:	10K549
10:~ svacchanda$ port -v installed qtiplot
The following ports are currently installed:
  qtiplot @0.9.8.9_21 (active) requested_variants='' platform='darwin 10' archs='ppc' date='2022-08-07T01:56:21+0545'
```

**Comment by mascguy** [comment]
> @mascguy I know that is was failing, but I fixed compilation errors and built it :)

While it's great that it builds for 10.6, you still have more work to do...  😉

**Comment by barracuda156** [comment]
@mascguy `clang` is broken, as usual, even on Intel LOL

Here is the error due to which the library did not build:
```
2022-08-06T20:21:01.3869430Z src/qwt3d_lighting.cpp:178:27: error: non-constant-expression cannot be narrowed from type 'double' to 'GLfloat' (aka 'float') in initializer list [-Wc++11-narrowing]
2022-08-06T20:21:01.3903960Z   GLfloat lightPos[4] = { lights_[light].shift.x, lights_[light].shift.y, lights_[light].shift.z, 1.0};
2022-08-06T20:21:01.4004960Z                           ^~~~~~~~~~~~~~~~~~~~~~
2022-08-06T20:21:01.4012260Z src/qwt3d_lighting.cpp:178:27: note: insert an explicit cast to silence this issue
2022-08-06T20:21:01.4040680Z   GLfloat lightPos[4] = { lights_[light].shift.x, lights_[light].shift.y, lights_[light].shift.z, 1.0};
2022-08-06T20:21:01.4059660Z                           ^~~~~~~~~~~~~~~~~~~~~~
2022-08-06T20:21:01.4136010Z                           static_cast<GLfloat>( )
2022-08-06T20:21:01.4187850Z src/qwt3d_lighting.cpp:178:51: error: non-constant-expression cannot be narrowed from type 'double' to 'GLfloat' (aka 'float') in initializer list [-Wc++11-narrowing]
2022-08-06T20:21:01.4255530Z   GLfloat lightPos[4] = { lights_[light].shift.x, lights_[light].shift.y, lights_[light].shift.z, 1.0};
2022-08-06T20:21:01.4301310Z                                                   ^~~~~~~~~~~~~~~~~~~~~~
2022-08-06T20:21:01.4315240Z src/qwt3d_lighting.cpp:178:51: note: insert an explicit cast to silence this issue
2022-08-06T20:21:01.4384880Z   GLfloat lightPos[4] = { lights_[light].shift.x, lights_[light].shift.y, lights_[light].shift.z, 1.0};
2022-08-06T20:21:01.4429540Z                                                   ^~~~~~~~~~~~~~~~~~~~~~
2022-08-06T20:21:01.4450580Z                                                   static_cast<GLfloat>( )
2022-08-06T20:21:01.4542140Z src/qwt3d_lighting.cpp:178:75: error: non-constant-expression cannot be narrowed from type 'double' to 'GLfloat' (aka 'float') in initializer list [-Wc++11-narrowing]
2022-08-06T20:21:01.4575160Z   GLfloat lightPos[4] = { lights_[light].shift.x, lights_[light].shift.y, lights_[light].shift.z, 1.0};
2022-08-06T20:21:01.4664910Z                                                                           ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by barracuda156** [comment]
@mascguy Okay, I fixed it for bots too.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
