### PR TITLE
py-*: remove old subports without dependencies

### PR DESCRIPTION
**Pull request by catap**
#### Description

Goal is cleaning up unused py27...py37 ports.

How? I've run the script:
```
port echo maintainer:catap | grep '^py[23][0-7]-' | while read port
do
    if [[ -z $(port echo depends:$port) ]]; then
        echo $port
    fi
done
```
and removes all subport which it find. And repeat it a few times, until it returned an empty string.

Here I've touched only ports where I'm a (co)maintainer.

###### Type(s)

- [x] enhancement

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

### CODE REVIEW

**Comment by catap** [comment]
I've tried to use generic version of that script to cleanup from old subports:
```
port echo 'py[23][0-7]-*' | while read port
do
    if [[ -z $(port echo depends:$port) ]]; then
        echo $port
    fi
done
```
but impact are huge and I have no idea how to automatically validate that here no exists a non-default variant which used it :(

**Comment by jmroot** [comment]
> I have no idea how to automatically validate that here no exists a non-default variant which used it :(

Yes, that's a hard problem unfortunately. You can grep the ports tree for the rootname of each module, but that will sometimes give false positives.

**Comment by xeron** [comment]
Sorry I actually don't use macports anymore. I should probably remove myself from maintainers list.

**Comment by catap** [comment]
@xeron np, I'm a co-maintainer and take care of pycryptodome (and pycryptodomex).

**Comment by catap** [comment]
@herbygillot may I ask you to merge also this PR? Thanks!

**Comment by catap** [comment]
Thanks!

**Pull request merged**
