### PR TITLE
py-matplotlib: update to 3.9.2

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
- update to latest upstream version
- separate the PY27 subport into its own Portfile
- drop PY38 subport
- do not build `macosx` backend on system < 10.12 - which should allow the latest version to -hopefully- be used on all OSes

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 15.0.1 24A348 x86_64
Xcode 16.1 16B40

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
@barracuda156 @aeiouaeiouaeiouaeiouaeiouaeiou @RobK88 @kencu would any of you be so kind to test the latest version which uses `meson` as build system? I have disabled the compilation of the `macosx` backend on systems below 10.12 as indicated by upstream. I would hope that with that the latest version will work on older OSes without any additional patching as well, but would like someone to verify that before I merge this. Thanks!

**Comment by barracuda156** [comment]
@reneeotten I will try it now.

**Comment by barracuda156** [comment]
Builds fine for me.
```
--->  Building py311-matplotlib
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2" && /opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 -m build --no-isolation --wheel --outdir /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work -Csetup-args=-Dsystem-freetype=True -Csetup-args=-Dsystem-qhull=True -Csetup-args=-Dmacosx=False 
* Getting build dependencies for wheel...
* Building wheel...
+ meson-3.11 setup /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2 /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/.mesonpy-jppqlw4x -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dsystem-freetype=True -Dsystem-qhull=True -Dmacosx=False --native-file=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/.mesonpy-jppqlw4x/meson-python-native-file.ini
The Meson build system
Version: 1.6.0
Source dir: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2
Build dir: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/.mesonpy-jppqlw4x
Build type: native build
Program /opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 found: YES (/opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11)
Project name: matplotlib
Project version: 3.9.2
C compiler for the host machine: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/compwrap/cc/opt/local/bin/gcc-mp-14 (gcc 14.2.0 "gcc-mp-14 (MacPorts gcc14 14.2.0_1+stdlib_flag) 14.2.0")
C linker for the host machine: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/compwrap/cc/opt/local/bin/gcc-mp-14 ld64 97.17
C++ compiler for the host machine: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/compwrap/cxx/opt/local/bin/g++-mp-14 (gcc 14.2.0 "g++-mp-14 (MacPorts gcc14 14.2.0_1+stdlib_flag) 14.2.0")
C++ linker for the host machine: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/compwrap/cxx/opt/local/bin/g++-mp-14 ld64 97.17
Host machine cpu family: ppc
Host machine cpu: power macintosh
Program python found: YES (/opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11)
Found pkg-config: YES (/opt/local/bin/pkg-config) 0.29.2
Run-time dependency python found: YES 3.11
Run-time dependency pybind11 found: YES 2.13.6
Run-time dependency freetype2 found: YES 26.2.20
Run-time dependency qhull_r found: YES 8.0.2
Run-time dependency dl found: YES
Configuring _version.py using configuration
Program /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/tools/generate_matplotlibrc.py found: YES (/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/tools/generate_matplotlibrc.py)
Build targets in project: 12

matplotlib 3.9.2

  User defined options
    Native files   : /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/.mesonpy-jppqlw4x/meson-python-native-file.ini
    b_ndebug       : if-release
    b_vscrt        : md
    buildtype      : release
    macosx         : False
    system-freetype: True
    system-qhull   : True

Found ninja-1.12.1 at /opt/local/bin/ninja
+ /opt/local/bin/ninja                                                         
[1/40] Compiling C++ object extern/agg24-svn/libagg.a.p/src_agg_image_filters.cpp.o
[2/40] Compiling C++ object extern/agg24-svn/libagg.a.p/src_agg_trans_affine.cpp.o
[3/40] Compiling C++ object extern/agg24-svn/libagg.a.p/src_agg_bezier_arc.cpp.o
[4/40] Compiling C++ object extern/agg24-svn/libagg.a.p/src_agg_vcgen_dash.cpp.o
[5/40] Compiling C++ object extern/agg24-svn/libagg.a.p/src_agg_vpgen_segmentator.cpp.o
[6/40] Compiling C++ object extern/agg24-svn/libagg.a.p/src_agg_curves.cpp.o
[7/40] Compiling C++ object extern/agg24-svn/libagg.a.p/src_agg_vcgen_contour.cpp.o
[8/40] Compiling C++ object extern/ttconv/libttconv.a.p/ttutil.cpp.o
[9/40] Compiling C++ object extern/agg24-svn/libagg.a.p/src_agg_vcgen_stroke.cpp.o
[10/40] Linking static target extern/agg24-svn/libagg.a
[11/40] Compiling C++ object extern/ttconv/libttconv.a.p/pprdrv_tt2.cpp.o
[12/40] Compiling C++ object extern/ttconv/libttconv.a.p/pprdrv_tt.cpp.o
[13/40] Linking static target extern/ttconv/libttconv.a
[14/40] Compiling C++ object src/_backend_agg.cpython-311-darwin.so.p/py_converters.cpp.o
[15/40] Compiling C++ object src/ft2font.cpython-311-darwin.so.p/py_converters.cpp.o
[16/40] Compiling C++ object src/ft2font.cpython-311-darwin.so.p/ft2font_wrapper.cpp.o
[17/40] Compiling C++ object src/ft2font.cpython-311-darwin.so.p/ft2font.cpp.o
[18/40] Compiling C++ object src/_backend_agg.cpython-311-darwin.so.p/_backend_agg.cpp.o
[19/40] Compiling C++ object src/_path.cpython-311-darwin.so.p/py_converters.cpp.o
[20/40] Compiling C++ object src/_c_internal_utils.cpython-311-darwin.so.p/_c_internal_utils.cpp.o
[21/40] Compiling C++ object src/_backend_agg.cpython-311-darwin.so.p/_backend_agg_wrapper.cpp.o
[22/40] Compiling C++ object src/_image.cpython-311-darwin.so.p/py_converters_11.cpp.o
[23/40] Compiling C++ object src/_path.cpython-311-darwin.so.p/py_converters_11.cpp.o
[24/40] Compiling C++ object src/_qhull.cpython-311-darwin.so.p/_qhull_wrapper.cpp.o
[25/40] Compiling C++ object src/_tkagg.cpython-311-darwin.so.p/_tkagg.cpp.o
[26/40] Compiling C++ object src/_path.cpython-311-darwin.so.p/_path_wrapper.cpp.o
[27/40] Linking target src/_backend_agg.cpython-311-darwin.so
[28/40] Compiling C++ object src/_tri.cpython-311-darwin.so.p/tri__tri_wrapper.cpp.o
[29/40] Compiling C++ object src/_tri.cpython-311-darwin.so.p/tri__tri.cpp.o
[30/40] Linking target src/ft2font.cpython-311-darwin.so
[31/40] Compiling C++ object src/_image.cpython-311-darwin.so.p/_image_wrapper.cpp.o
[32/40] Compiling C++ object src/_ttconv.cpython-311-darwin.so.p/_ttconv.cpp.o
[33/40] Linking target src/_c_internal_utils.cpython-311-darwin.so
[34/40] Linking target src/_path.cpython-311-darwin.so
[35/40] Generating lib/matplotlib/mpl-data/matplotlibrc with a custom command
[36/40] Linking target src/_qhull.cpython-311-darwin.so
[37/40] Linking target src/_tkagg.cpython-311-darwin.so
[38/40] Linking target src/_tri.cpython-311-darwin.so
[39/40] Linking target src/_ttconv.cpython-311-darwin.so
[40/40] Linking target src/_image.cpython-311-darwin.so
[1/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/.mesonpy-jppqlw4x/src/_backend_agg.cpython-311-darwin.so
[2/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/.mesonpy-jppqlw4x/src/_c_internal_utils.cpython-311-darwin.so
[3/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/.mesonpy-jppqlw4x/src/ft2font.cpython-311-darwin.so
[4/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/.mesonpy-jppqlw4x/src/_image.cpython-311-darwin.so
[5/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/.mesonpy-jppqlw4x/src/_path.cpython-311-darwin.so
[6/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/.mesonpy-jppqlw4x/src/_qhull.cpython-311-darwin.so
[7/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/.mesonpy-jppqlw4x/src/_tkagg.cpython-311-darwin.so
[8/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/.mesonpy-jppqlw4x/src/_tri.cpython-311-darwin.so
[9/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/.mesonpy-jppqlw4x/src/_ttconv.cpython-311-darwin.so
[10/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/.mesonpy-jppqlw4x/lib/matplotlib/mpl-data/matplotlibrc
[11/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/pylab.py
[12/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/__init__.py
[13/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_afm.py
[14/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_animation_data.py
[15/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_blocking_input.py
[16/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_cm.py
[17/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_cm_listed.py
[18/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_color_data.py
[19/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_constrained_layout.py
[20/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_docstring.py
[21/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_enums.py
[22/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_fontconfig_pattern.py
[23/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_internal_utils.py
[24/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_layoutgrid.py
[25/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_mathtext.py
[26/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_mathtext_data.py
[27/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_pylab_helpers.py
[28/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_text_helpers.py
[29/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_tight_bbox.py
[30/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/_tight_layout.py
. . .
[581/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/mpl-data/stylelib/seaborn-v0_8-white.mplstyle
[582/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/mpl-data/stylelib/seaborn-v0_8-whitegrid.mplstyle
[583/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/mpl-data/stylelib/seaborn-v0_8.mplstyle
[584/584] /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-matplotlib/py311-matplotlib/work/matplotlib-3.9.2/lib/matplotlib/mpl-data/stylelib/tableau-colorblind10.mplstyle
Successfully built matplotlib-3.9.2-cp311-cp311-macosx_10_6_PowerPC.whl
--->  Staging py311-matplotlib into destroot
```

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
I'm busy, but I'll try to test this today.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Unfortunately, the build does not work on SL x86_64 for this reason:

```
ld: in build/temp.macosx-10.6-x86_64-cpython-312/matplotlib.ft2font/src/ft2font.o, unknown scope for symbol __ZTVNSt3__119basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE in bitcode file build/temp.macosx-10.6-x86_64-cpython-312/matplotlib.ft2font/src/ft2font.o for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by barracuda156** [comment]
> Unfortunately, the build does not work on SL x86_64 for this reason:

Which clang with, for the record?

**Comment by reneeotten** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou thanks... it looks like though from [ports.macports.org](https://ports.macports.org/port/py312-matplotlib/details/) that the current version also doesn't build so the status quo doesn't change. 
If you can provide a complete build log and/or suggest changes to make this work, I am happy to accept those. But other than that I will merge this in the weekend and we'll see if something can be fixed down the line.

**Comment by reneeotten** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou if you don't mind could you also retry after adding "use_parallel_build no" to the Portfile. I didn't see any issues anymore so removed it, but perhaps there are still situations where this causes issues.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@reneeotten it's okay to merge it because support for ancient systems is not a strict requirement.

**Comment by reneeotten** [comment]
look like `macports-clang-11` doesn't work as that's what gets selected on SL; `macports-clang-17` does work though, as that results in a successful build on ML. If someone on SL can figure out more precisely what compilers to blacklist please let me know or open a PR; otherwise I guess we can just try and make sure that it uses `macports-clang-17` everywhere, but perhaps there are versions in between that are okay as well.

**Comment by barracuda156** [comment]
> look like `macports-clang-11` doesn't work as that's what gets selected on SL; `macports-clang-17` does work though, as that results in a successful build on ML. If someone on SL can figure out more precisely what compilers to blacklist please let me know or open a PR; otherwise I guess we can just try and make sure that it uses `macports-clang-17` everywhere, but perhaps there are versions in between that are okay as well.

A bit on a side note, but I do not really get what is the point of keeping and _requiring_ all the zoo of clang versions, it takes forever to build from source even on a decent x86_64 hardware. Like single gcc is preferred, it would be nice to have a single default clang, built with the Xcode compiler or clang-11-bootstrap.
I.e., IMO it is preferable to use clang-17 everywhere, rather than picking a different minimal one on every OS version.

**Pull request merged**
