### PR TITLE
py-fortranformat: update to 2.0.0

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Long due update.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@smithsp Ok, sure, will do now.

**Comment by barracuda156** [comment]
@smithsp Done.

**Comment by smithsp** [comment]
@barracuda156 Thanks.  
The MacPorts maintainers will want you to go through all of the steps in the top comment before merging.

**Review by reneeotten — COMMENTED** [review]
could you align line 28 correctly with four spaces (I know not you're doing, but let's fix it now at the same time); then it should be ready to merge

**Comment by barracuda156** [comment]
> could you align line 28 correctly with four spaces (I know not you're doing, but let's fix it now at the same time); then it should be ready to merge

@reneeotten Sure, will do now.

**Comment by barracuda156** [comment]
@reneeotten Perhaps good now, please take a look.

**Pull request merged**
