### PR TITLE
libsamplerate: drop old patch

### PR DESCRIPTION
**Pull request by janstary**
This removes the six years old patch introduced in https://github.com/macports/macports-ports/commit/3c65e7cddca467fda65bd9c89503e553b518984b

Tested on 10.13.2 with XCode 9.2 - please test everywhere,
on old systems in particular. Do we still use pre-C99 compilers somewhere?

If it compiles at all, then there is no functional change :-)

### CODE REVIEW

**Comment by janstary** [comment]
An upstream  PR https://github.com/erikd/libsamplerate/pull/27 will hopefully incorporate our patch into the next release.

I would gladly drop the other patch too, and have a simple port,
but it seems we need it: not to save half a second by not building the examples,
but because `examples/audio_out.c:#include <Carbon.h>` does not compile
on newer MacOS versions, where the audio framework has changed again.

**Comment by janstary** [comment]
Does anyone know about a compiler that actually has a problem with this?
(That is, a compiler we care about?)

**Comment by pmetzger** [comment]
I suspect the trailing comma works on all compilers that MacOS has used, but I'm not 100% certain.

**Comment by kencu** [comment]
I know @ryandesign just went to the trouble of fixing this particular issue on another port not a month ago <https://github.com/macports/macports-ports/commit/2c4fbaf661ad58a7ed5ecef17007580c9dbd8601#diff-b60f084c582874896f393b71e459b9e4> so I guess I'd say to leave it in.

**Comment by janstary** [comment]
I'll test on 10.5.8. with apple gcc 4.2.1 too.

**Comment by kencu** [comment]
From what I can recall, the particular series of events that needs to happen to cause trouble apparently would include:

1. use the specified header with the dangling comma in some build
2. build with no c standard specified on an older compiler that defaults to c89 (or less likely with c89 explicitly specified)
3. build with -Wpedantic

**Comment by pmetzger** [comment]
Why would you build with -Wpedantic in c89 mode, though? Loads of stuff breaks if you do that.

**Comment by janstary** [comment]
It builds just fine without the patch on 10.5.8.
`./configure` detects `gcc-4.2` when `checking for gcc`, which is

```
Using built-in specs.
Target: i686-apple-darwin9
Configured with: /var/tmp/gcc_42/gcc_42-5574~1/src/configure --disable-checking --enable-werror --prefix=/usr --mandir=/usr/share/man --enable-languages=c,objc,c++,obj-c++ --program-transform-name=/^[cg][^.-]*$/s/$/-4.2/ --with-slibdir=/usr/lib --build=i686-apple-darwin9 --with-gxx-include-dir=/usr/include/c++/4.0.0 --host=i686-apple-darwin9 --target=i686-apple-darwin9
Thread model: posix
gcc version 4.2.1 (Apple Inc. build 5574)
```

**Comment by janstary** [comment]
It also builds fine on 10.6.8, where `./configure` detects `/usr/bin/gcc-4.2`, which is

```
Using built-in specs.
Target: i686-apple-darwin10
Configured with: /var/tmp/gcc/gcc-5666.3~6/src/configure --disable-checking --enable-werror --prefix=/usr --mandir=/usr/share/man --enable-languages=c,objc,c++,obj-c++ --program-transform-name=/^[cg][^.-]*$/s/$/-4.2/ --with-slibdir=/usr/lib --build=i686-apple-darwin10 --with-gxx-include-dir=/usr/include/c++/4.2.1 --host=i686-apple-darwin10 --target=i686-apple-darwin10
Thread model: posix
gcc version 4.2.1 (Apple Inc. build 5666) (dot 3)
```

**Comment by janstary** [comment]
Can anyone give an example of a situation where the patch is needed?
Do we care about something older than gcc 4.2.1 on MacOS 10.5.8?

**Comment by pmetzger** [comment]
I don't think MacPorts is supported on anything older than 10.5.

**Comment by kencu** [comment]
I have no horse in this race. You're the maintainer, after all. Perhaps all the old software like ```darkice +samplerate``` that used to trigger errors has died or been fixed. Anyway, if any tickets open, you'll be the one to fix them. I build everything on older systems with compilers that would not notice this anyway. If you want this patch removed, just say the word.

**Pull request merged**
