### PR TITLE
spice-gtk: Add x11 variant to gtk3 dependency

### PR DESCRIPTION
**Pull request by AlD**
gtk3 +quartz doesn't come with gdk/gdkx.h.

### CODE REVIEW

**Comment by mojca** [comment]
The patch looks reasonable, but let's wait for maintainer to approve it.

I would change the commit message to say "require x11 variant in/of? gtk3 dependency" (probably not grammatically correct?), else it sounds almost as if you added a variant to the gtk3 port itself.

**Comment by danchr** [comment]
Are sure this is necessary? I wrote this port with the quartz variant active, and in general I try my best to avoid X11. I can't check right now, since I'm on holiday, but I'll take a look later!

**Comment by AlD** [comment]
Travis seems to agree. I'll verify what exactly fails on my machine and follow up here if necessary.

**Comment by danchr** [comment]
@AlD Travis? I didn't know MacPorts had an instance — is it documented somewhere?

**Comment by AlD** [comment]
Seems to be pretty new:
https://github.com/macports/macports-ports/commits/master/.travis.yml
https://github.com/macports/macports-ports/commits/master/_ci

**Comment by AlD** [comment]
OK, the problem is xorg-libX11, which provides X11/XKBlib.h, which in turn causes spice-gtk to #define HAVE_X11_XKBLIB_H 1.

And then the ui files have these includes:
#ifdef HAVE_X11_XKBLIB_H
#include <X11/XKBlib.h>
#include <gdk/gdkx.h>
#endif
#ifdef GDK_WINDOWING_X11
#include <X11/Xlib.h>
#include <gdk/gdkx.h>
#endif

**Comment by danchr** [comment]
Ah, in that case the cause is likely X11 being installed combined with the absence of trace mode — which I always use. We should fix that. Would you like to update the pull request, or should I look into it?

(Oh, and nice to see other people using the port. I assume you're trying to install @virt-manager@? It mostly works, but isn't terribly useful on a Mac.)

**Comment by AlD** [comment]
I actually sent a patch to spice-gtk to remove the check for HAVE_X11_XKBLIB_H and hinge on GDK_WINDOWING_X11 instead, because I think that's actually the correct way.

My patch mail got caught in greylisting and I didn't have a proper mail(1) setup on my laptop, so I just resent that mail. Should arrive on spice-devel@lists.freedesktop.org in a few minutes.

And yeah, I was hoping to use virt-manager, but no dice yet ;)

**Pull request closed without merging**
