### PR TITLE
ffmpeg7: new symlink variant, add usage notes

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by i0ntempest** [comment]
Right, I know I have brought this up [before](https://github.com/macports/macports-ports/pull/23315) and the maintainer wasn't sure about the changes. It's ffmpeg v7 time so I'm bringing this out again for a reconsideration. If this got in I'll sync the changes to v6 and devel ports.
What this does:
1. add a new symlink variant for users who want a simple way to mask the old ffmpeg v4 binaries (by modifying PATH). If the symlink is enabled (which is the default nothing changes)
2. Add notes on how to properly use the libraries and binaries (if symlink variant is disabled) in this port.

**Comment by barracuda156** [comment]
@i0ntempest What benefit does this provide?

**Comment by i0ntempest** [comment]
> @i0ntempest What benefit does this provide? How does it hurt having symlinks?

Having symlinks doesn't hurt, what I really want is to remove the `7` binary suffix and make it easy to mask old v4 binaries in terminal by adding `/opt/local/libexec/ffmpeg7/bin` to `PATH` (which is what ImageMagick7 port does).
I actually prefer just removing the suffix from the binaries but keep the suffix on the symlinks - which is easier and less clutter, but the other maintainer didn't really like it, so the symlink variant toggling symlink creation AND binary suffix is really just a compromise.

> P. S. Formally: commit title refers to ffmpeg6, commit contents to ffmpeg7. ffmpeg-devel is forgotten – it is v. 7 now, not v. 4.

Copypasta bad - fixed

**Comment by barracuda156** [comment]
@i0ntempest At the same time you can easily do the reverse without forcing everyone to rebuild.
Make a non-default variant symlinks which adds symlinks from ffmpeg7 to ffmpeg inside its prefix.
This solves your issue, as I understand, and does not require anyone’s approval, since it will change nothing at all by default and will not require rebuild.

**Comment by i0ntempest** [comment]
> @i0ntempest At the same time you can easily do the reverse without forcing everyone to rebuild. Make a non-default variant symlinks which adds symlinks from ffmpeg7 to ffmpeg inside its prefix. This solves your issue, as I understand, and does not require anyone’s approval, since it will change nothing at all by default and will not require rebuild.

Good idea - though I still prefer removing binary suffices which imo is cleaner. Let's hear what @mascguy says first.

**Comment by mascguy** [comment]
> > @i0ntempest At the same time you can easily do the reverse without forcing everyone to rebuild. Make a non-default variant symlinks which adds symlinks from ffmpeg7 to ffmpeg inside its prefix. This solves your issue, as I understand, and does not require anyone’s approval, since it will change nothing at all by default and will not require rebuild.
> 
> Good idea - though I still prefer removing binary suffices which imo is cleaner. Let's hear what @mascguy says first.

That's a great idea, and I'm totally fine with that approach. Users will be happier too, as it avoids an unnecessary port update/rebuild.

**Comment by i0ntempest** [comment]
> > > @i0ntempest At the same time you can easily do the reverse without forcing everyone to rebuild. Make a non-default variant symlinks which adds symlinks from ffmpeg7 to ffmpeg inside its prefix. This solves your issue, as I understand, and does not require anyone’s approval, since it will change nothing at all by default and will not require rebuild.
> > 
> > 
> > Good idea - though I still prefer removing binary suffices which imo is cleaner. Let's hear what @mascguy says first.
> 
> That's a great idea, and I'm totally fine with that approach. Users will be happier too, as it avoids an unnecessary port update/rebuild.

Cool - I’ll take that. I’ll directly commit the change later along with the new notes.

**Pull request closed without merging**
