### PR TITLE
tk: fix +quartz build on older systems

### PR DESCRIPTION
**Pull request by mojca**
Closes: https://trac.macports.org/ticket/54673

###### Description

I'm submitting a potential fix for a broken `tk +quartz` build from suggestions by @auriocus.

Ideally someone should test this on 10.6 (@kencu?) and 10.12.

(I also removed an orphaned patch which I realize I should probably mention in the commit message or split it to another commit, sorry for that. I can fix that later if needed.)

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.7.5 11G63b
Xcode 4.6.3 4H1503

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
I can confirm that tk @8.6.7 +quartz builds & installs on a stock 10.6/libstdc++ setup, and the widgets demos work - with one error.

When using the File Selection dialog box, set to "All Files ()", there is an exception, and no files can be selected. The error shown is:
```
2017-08-30 12:50:37.539 wish8.6[14301:60f] HIToolbox: ignoring exception 'File types array cannot be empty' that raised inside Carbon event dispatch
(
	0   CoreFoundation                      0x00007fff801ca784 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x00007fff89694f03 objc_exception_throw + 45
	2   CoreFoundation                      0x00007fff801ca5a7 +[NSException raise:format:arguments:] + 103
	3   CoreFoundation                      0x00007fff801ca534 +[NSException raise:format:] + 148
	4   AppKit                              0x00007fff876dd638 -[NSSavePanel setAllowedFileTypes:] + 580
	5   libtk8.6.dylib                      0x00000001000bfbfb -[TKApplication(TKDialog) selectFormat:] + 71
	6   AppKit                              0x00007fff87390eda -[NSApplication sendAction:to:from:] + 95
	7   AppKit                              0x00007fff87390e39 -[NSControl sendAction:to:] + 94
	8   AppKit                              0x00007fff87390eda -[NSApplication sendAction:to:from:] + 95
	9   AppKit                              0x00007fff873b546a -[NSMenuItem _corePerformAction] + 365
	10  AppKit                              0x00007fff873b51d4 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 121
	11  AppKit                              0x00007fff8763acf4 -[NSMenu _internalPerformActionForItemAtIndex:] + 35
	12  AppKit                              0x00007fff874ec9e9 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 136
	13  AppKit                              0x00007fff8739799c NSSLMMenuEventHandler + 321
	14  HIToolbox                           0x00007fff806c47f7 _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1002
	15  HIToolbox                           0x00007fff806c3d46 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 395
	16  HIToolbox                           0x00007fff806e1a81 SendEventToEventTarget + 45
	17  HIToolbox                           0x00007fff80710c35 _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 387
	18  HIToolbox                           0x00007fff8073da0a SendMenuCommandWithContextAndModifiers + 56
	19  HIToolbox                           0x00007fff8073d9c2 SendMenuItemSelectedEvent + 101
	20  HIToolbox                           0x00007fff8073d8d2 _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 150
	21  HIToolbox                           0x00007fff80846a69 _ZL19PopUpMenuSelectCoreP8MenuData5PointdS1_tjPK4RecttjS4_S4_PK10__CFStringPP13OpaqueMenuRefPt + 1618
	22  HIToolbox                           0x00007fff80846dc2 _HandlePopUpMenuSelection7 + 665
	23  AppKit                              0x00007fff874e999b _NSSLMPopUpCarbonMenu3 + 3720
	24  AppKit                              0x00007fff8769957e -[NSPopUpButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 554
	25  AppKit                              0x00007fff8741b2f5 -[NSControl mouseDown:] + 624
	26  AppKit                              0x00007fff873353a7 -[NSWindow sendEvent:] + 5409
	27  AppKit                              0x00007fff8726aafa -[NSApplication sendEvent:] + 4719
	28  libtk8.6.dylib                      0x00000001000d3047 -[TKApplication(TKNotify) sendEvent:] + 39
	29  AppKit                              0x00007fff87476e06 -[NSApplication _realDoModalLoop:peek:] + 509
	30  AppKit                              0x00007fff87474951 -[NSApplication runModalForWindow:] + 129
	31  libtk8.6.dylib                      0x00000001000c2671 Tk_GetOpenFileObjCmd + 2358
	32  libtcl8.6.dylib                     0x0000000100189ed0 TclNRRunCallbacks + 58
	33  libtk8.6.dylib                      0x00000001000b3aa8 Ttk_InvokeEnsemble + 148
	34  libtk8.6.dylib                      0x00000001000bb918 WidgetInstanceObjCmd + 92
	35  libtcl8.6.dylib                     0x0000000100189ed0 TclNRRunCallbacks + 58
	36  libtk8.6.dylib                      0x00000001000bb190 TtkWidgetInstateCommand + 219
	37  libtk8.6.dylib                      0x00000001000b3aa8 Ttk_InvokeEnsemble + 148
	38  libtk8.6.dylib                      0x00000001000bb918 WidgetInstanceObjCmd + 92
	39  libtcl8.6.dylib                     0x0000000100189ed0 TclNRRunCallbacks + 58
	40  libtk8.6.dylib                      0x00000001000bb190 TtkWidgetInstateCommand + 219
	41  libtk8.6.dylib                      0x00000001000b3aa8 Ttk_InvokeEnsemble + 148
	42  libtk8.6.dylib                      0x00000001000bb918 WidgetInstanceObjCmd + 92
	43  libtcl8.6.dylib                     0x0000000100189ed0 TclNRRunCallbacks + 58
	44  libtcl8.6.dylib                     0x000000010018a9e8 TclEvalEx + 2219
	45  libtcl8.6.dylib                     0x000000010018addb Tcl_EvalEx + 26
	46  libtk8.6.dylib                      0x00000001000131c3 Tk_BindEvent + 4192
	47  libtk8.6.dylib                      0x00000001000175c8 TkBindEventProc + 342
	48  libtk8.6.dylib                      0x000000010001dfbf Tk_HandleEvent + 1432
	49  libtk8.6.dylib                      0x000000010001e090 WindowEventProc + 92
	50  libtcl8.6.dylib                     0x000000010022fda8 Tcl_ServiceEvent + 147
	51  libtcl8.6.dylib                     0x0000000100230098 Tcl_DoOneEvent + 314
	52  libtk8.6.dylib                      0x000000010001d7e1 Tk_MainLoop + 24
	53  libtk8.6.dylib                      0x000000010002bac6 Tk_MainEx + 1418
	54  wish8.6                             0x0000000100005435 main + 56
	55  wish8.6                             0x0000000100005370 start + 52
)
```

**Comment by kencu** [comment]
You know, that same file open dialog box doesn't seem to work correctly on Sierra, either. It doesn't raise an exception like the above, but you can't select any file to open either. I think the code that is implementing that feature might need a bit of work still...

**Comment by auriocus** [comment]
Am 30.08.17 um 22:00 schrieb Ken:
> I can confirm that tk @8.6.7 +quartz builds & installs on a stock 
> 10.6/libstdc++ setup, and the widgets demos work - with one error.
> 
> When using the File Selection dialog box, set to "All Files ()", there 
> is an exception, and no files can be selected. The error shown is:
> 
> |2017-08-30 12:50:37.539 wish8.6[14301:60f] HIToolbox: ignoring exception 
> 'File types array cannot be empty' 

I can confirm the bug on Sierra. Apparently the "All files" mask needs 
special handling, which was not detected during testing.

Best regards,

     Christian

**Comment by mojca** [comment]
Thank you both for testing and helping me fix the build problem. I hope that the next version of Tk will include the fix for both issues :)

**Comment by auriocus** [comment]
Am 31.08.17 um 13:38 schrieb Mojca Miklavec:
> Thank you both for testing and helping me fix the build problem. I hope 
> that the next version of Tk will include the fix for both issues :)
> 

I will look into the issue with the all files filter and send a combined 
patch to Kevin Walzer, who has commit rights for Tk.

	Auriocus

**Pull request merged**
