### PR TITLE
gping: new port

### PR DESCRIPTION
**Pull request by harens**
#### Description

This is a portfile for [gping](https://github.com/orf/gping) as well as its original python version.

Just to note, I wasn't sure what to call the python subport (since it's not a library), so I called it `gping-python`. I'm happy to change this if necessary. 

I also hardcoded the version number of the subport to the version in the [`setup.py`](https://github.com/orf/gping/blob/python/setup.py), since its [tag](https://github.com/orf/gping/releases/tag/python) on GitHub is simply called "python".

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.6 19G73
xcode-select version 2373

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
Why make gping-python a subport? The two subports appear to be completely unrelated. I'd make it a separate Portfile, if it's needed at all.

**Comment by herbygillot** [comment]
> Why make gping-python a subport? The two subports appear to be completely unrelated. I'd make it a separate Portfile, if it's needed at all.

Agreed.  It looks like both the Python and Rust versions run completely independently.  They should most certainly be two separate ports with a separate PR for each.

As a matter of fact, since it's implied that the Python version is the old version, and may not be updated anymore, then maybe only have the port for the Rust version?

Additionally, I would say this port's primary category should be `net` since it's a network utility.  Or you can add both `net` and `sysutils`.

**Comment by harens** [comment]
Thanks @ryandesign and @herbygillot.

It might be useful to have the python version, seeing that a [new version](https://github.com/orf/gping/commit/65b8470562a697a1ad3bb5c471ea115892c64429) was released 2 weeks ago with a different layout to the rust version, and both [nixpkgs stable](https://github.com/NixOS/nixpkgs/blob/release-20.09/pkgs/tools/networking/gping/default.nix) and [unstable](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/networking/gping/default.nix) choose to package it.

However, I agree that it might not even be updated anymore since it is certainly not a priority, so we can leave that discussion for another time. In the unlikely event a new version is released for it, I'll send a separate PR then.

Thanks for your suggestions about the subport and the category. I have taken them into account and added them accordingly.

**Comment by herbygillot** [comment]
Hey @harens, are we good for this Portfile?

**Comment by harens** [comment]
It should be all good now. v0.1.7 was released whilst the PR was open, so I updated the portfile and applied the changes mentioned.

**Comment by herbygillot** [comment]
OK, merged.  Thanks.

**Comment by harens** [comment]
Thanks @herbygillot and @ryandesign for your help.

**Pull request merged**
