### PR TITLE
neomutt: update to 20171013

### PR DESCRIPTION
**Pull request by lbschenkel**
###### Description

- Updated to NeoMutt 20171013
  - upstream now uses `autosetup` to build
  - upstream now installs as `neomutt`
- Build using `autosetup`
- Install `mutt` symlink by default to keep existing behaviour (configurable via `+mutt` variant)
- Add new `+gss` and `+lua` variants 
- Handle config files properly (do not overwrite user changes)
- Fix documentation generation bug (https://trac.macports.org/ticket/54219)
- Do not block installation of `pgpring`, auxiliary binaries are now installed to a new location that does not conflict with other ports

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.13 17A405
Xcode 9.0 9A235 

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by l2dy** [comment]
Ack. This is indeed a special release.

**Comment by lbschenkel** [comment]
@l2dy: I have pushed the preliminary work, maybe you want to take a look? Due to the amount of variants in this port, is really impractical for me to test the binary for all the possible combinations. Having said that, apart from the variants controlling all the different databases, I think I did test all the other variants and at the very least they're all building successfully.

**Comment by l2dy** [comment]
@lbschenkel NeoMutt 2017-10-13 was released.

**Comment by l2dy** [comment]
Due to https://github.com/neomutt/neomutt/commit/37b9c6d8db0377d67611fa13879b744f5ee5cd1b#diff-d7a42b46f92cf19e4e0f24d5d1c97186, we have to reinplace these rc files in contrib.

**Comment by l2dy** [comment]
`${prefix}/etc/neomuttrc` is gone...

**Comment by lbschenkel** [comment]
Good catch. I didn't notice that the config files were installed by the `doc` Makefile, and since I introduced the `+doc` variant (which defaults to off) they don't get installed.

I *could* remove the `+doc` variant and just build the docs but building them requires too many dependencies for my taste. I'm going to manually install the config files in `/etc` and do it property (since until now they were installed as normal files so they would overwrite users' changes).

In the interest of decreasing the amount of variants, I'm strongly considering removing `+ssl`. I think it's very rare nowadays for users not to have or want openssl installed.

In the meantime, I have pushed some additional work.

**Comment by lbschenkel** [comment]
I have pushed new changes:
- removed `+ssl` variant, now mandatory
- removed `+doc` variant, now mandatory because of `neomuttrc` (against to my original wish, but there's pre-processing going on at build time and I can't simply do a file copy)
- config files are properly handled, user changes are not overwritten
- updated to 20171013

I *think* this should be ready to go now, barring anything I overlooked there's no additional work for me to do.

**Comment by l2dy** [comment]
Build failed on OS X 10.6.
```
/usr/bin/gcc-4.2 -o neomutt account.o addrbook.o alias.o attach.o bcache.o body.o browser.o buffy.o charset.o color.o commands.o complete.o compose.o compress.o conststrings.o copy.o curs_lib.o curs_main.o edit.o editmsg.o enter.o envelope.o filter.o flags.o from.o getdomain.o group.o handler.o hdrline.o headers.o help.o history.o hook.o init.o keymap.o main.o mbox.o mbyte.o menu.o mh.o muttlib.o mutt_idna.o mutt_sasl_plain.o mutt_socket.o mutt_tags.o mutt_tunnel.o mx.o newsrc.o nntp.o pager.o parameter.o parse.o pattern.o pop.o pop_auth.o pop_lib.o postpone.o query.o recvattach.o recvcmd.o rfc1524.o rfc2047.o rfc2231.o rfc3676.o rfc822.o safe_asprintf.o score.o send.o sendlib.o sidebar.o signal.o smtp.o sort.o state.o status.o system.o thread.o url.o version.o resize.o mutt_ssl.o libmutt.a libncrypt.a libimap.a -L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64  -lidn -lz -lssl -lcrypto -lncursesw -lintl -liconv
Undefined symbols:
  "_wcscasecmp", referenced from:
      _text_enriched_handler in handler.o
      _text_enriched_handler in handler.o
      _text_enriched_handler in handler.o
      _text_enriched_handler in handler.o
      _text_enriched_handler in handler.o
      _text_enriched_handler in handler.o
      _text_enriched_handler in handler.o
      _text_enriched_handler in handler.o
      _text_enriched_handler in handler.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
make: *** [neomutt] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory `/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_mail_neomutt/neomutt/work/neomutt-20171013'
Command failed:  cd "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_mail_neomutt/neomutt/work/neomutt-20171013" && /usr/bin/make -j8 -w all 
Exit code: 2

```

**Comment by lbschenkel** [comment]
I have reported it to upstream: https://github.com/neomutt/neomutt/issues/879
It looks like it's a regression from the change to `autosetup`, upstream has a replacement for the missing function but I don't see `autosetup` checking for its presence.

**Comment by kencu** [comment]
I have this function "on deck" for libsnowleopardfixes but haven't got around to including it yet. Give me a bit and I'll see if it will integrate easily.

**Comment by l2dy** [comment]
@kencu NeoMutt already have https://github.com/neomutt/neomutt/blob/neomutt-20171013/wcscasecmp.c, so I don't think libsnowleopardfixes is needed for this port.

**Comment by lbschenkel** [comment]
Precisely, I believe it's just that the upstream migration to `autosetup` disabled the check for the function.

However, having said that, if `libsnowleopardfixes` is being maintained by a team of people who has hands-on experience in making software build in these old versions, I wouldn't oppose linking to it when applicable since it would lead to leaner binaries that share the same battle-tested replacements. Many times the upstream projects lack expertise or resources to test on older boxes (no idea if that's the case for NeoMutt, I'm generalising right now).

@kencu In your experience on older systems, what do you think works better in practice? Using upstream replacements when available, or linking against `libsnowleopardfixes`? Since I'm not an user of these older boxes, as a maintainer I would prefer to choose something that is more convenient to the users (and hopefully doesn't increase the maintainership burden).

**Comment by kencu** [comment]
if upstream has an integrated replacement (autotools, usually) that is better imho.

**Comment by lbschenkel** [comment]
@kencu: If you have access to an old box, would you be so kind to test that https://github.com/macports/macports-ports/pull/938 fixes the build issue, so I can report back to upstream? Unfortunately I don't have access to an old box.

**Pull request merged**
