### PR TITLE
cross compilers: revbump for isl update

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
See https://github.com/macports/macports-ports/commit/422ccdd2b844c1234d11ab462319e6284235e3f7
See https://lists.macports.org/pipermail/macports-dev/2019-May/040678.html

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.4
Xcode 10.2.1 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mojca** [comment]
I simply upgraded my ports to avoid revbumping. I'm pretty sure that the other ports at 8.2.0 could simply be upgraded to 9.1.0 instead of revbumping.

For the ancient ones see also #3336 (not sure how to proceed with that one).

**Comment by MarcusCalhoun-Lopez** [comment]
> I simply upgraded my ports to avoid revbumping. I'm pretty sure that the other ports at 8.2.0 could simply be upgraded to 9.1.0 instead of revbumping.
> 
> For the ancient ones see also #3336 (not sure how to proceed with that one).

If this pull request is not the proper way to proceed, I will close it.

**Comment by mojca** [comment]
Not sure why you closed this?

**Comment by MarcusCalhoun-Lopez** [comment]
> Not sure why you closed this?

I may have misunderstood.
I thought your previous comments indicated that this pull request was not the best way to proceed.
Should I reopen and push the change?

**Comment by mojca** [comment]
Side note. I tried upgrading `arm-none-eabi-gcc`, but it fails with
```
checking if mkdir takes one argument... no
Don't know the target cpu
make[1]: *** [configure-gcc] Error 1
```

**Pull request merged**
