### PR TITLE
libgit2: update to 1.6.4

### PR DESCRIPTION
**Pull request by ioquatix**
Previous version bump: https://github.com/macports/macports-ports/pull/17800

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ioquatix** [comment]
cc @herbygillot I have tested this with the Ruby rugged gem and it looks good to me.

**Comment by herbygillot** [comment]
1.5.2 to 1.6.4 is a major version change, which has the potential to be disruptive to many of the ports which depend on `libgit2`.

The PR you linked to only updates the minor version; it updated `libgit2` from 1.5.1 to 1.5.2. A minor version update does not change the API in a major enough way to be a risky update.

So we need to be more careful with upgrading to 1.6.4 and test more than just Ruby's rugged.  For example, we'd also need to test that Rust's `cargo` can build against this version, amongst many other dependent ports.

**Comment by herbygillot** [comment]
We can add commits incrementing the revision of dependent ports to the branch after this update commit to rebuild them against the updated `libgit2`.  The one limitation with this approach is that the build process here on Github is time constrained, so the CI job will cancel if it's taking too long to rebuild everything we revision bump. I'll add some revision bump commits in a few.  We should probably start with `cargo`.

**Comment by mascguy** [comment]
> We can add commits incrementing the revision of dependent ports to the branch after this update commit to rebuild them against the updated `libgit2`. The one limitation with this approach is that the build process here on Github is time constrained, so the CI job will cancel if it's taking too long to rebuild everything we revision bump. I'll add some revision bump commits in a few. We should probably start with `cargo`.

Sounds good to me Herby!

**Comment by ioquatix** [comment]
Thanks, that sounds like a good plan!

**Comment by herbygillot** [comment]
Everything seems to have built successfully.  I am merging these.  There are additional ports that need to be bumped, but they are downstream of `rust` and `cargo`, and so should build fine since `rust` & `cargo` built fine.

**Comment by ioquatix** [comment]
Thanks!

**Pull request merged**
