### PR TITLE
qt4-mac: backport qt5 QSettings fix + support building on Tiger + maybe support High Sierra

### PR DESCRIPTION
**Pull request by devernay**
###### Description

All the tiger-specific patches are suffixed with -tiger, and don't break anything when compiling with more recent SDKs.

Only one patch, patch-src_gui_dialogs_qfontdialog_mac.mm-tiger.diff, reintroduces in the Tiger version only a Qt bug (QTBUG-27415) which cannot be fixed with the Tiger SDK (the fix requires Leopard).

Patch (19) seems wrong when building frameworks and breaks the build (older versions of qt4-mac allowed building with libraries only, I guess this patch is remnant from that time). I commented it out, and did not remove the patch file in case someone wants to take a closer look at it.

Also, since qt4-mac only uses the JPEG 8 API, libjpeg-turbo can be used instead (see https://trac.macports.org/ticket/38907)

Patches (30) (backport qt5 QSettings fix) and (31) (support High Sierra) were taken from homebrew. I did not test building on macOS High Sierra, and thus left the restriction.

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.12 and 10.4
Xcode 8.3.3 8E3004b and Xcode 2.5

###### Verification 
Have you
- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by michaelld** [comment]
@kencu : Can you test on your setups? I'll test on mine.

**Comment by kencu** [comment]
i had a crash that the author is looking into.

**Comment by kencu** [comment]
The revised patches that include the webkit fix as well work very nicely on 10.4 PPC. All qt4 apps build correctly and appear to work as expected with 10 minutes testing - menus, etc -all good. Looks good. Fred has some significant talent in this area... hope to see more of him around here!

**Comment by michaelld** [comment]
Seems like the "-tiger" patches internally check for the Mac OS X / macOS version & could just be applied to all installs, not just 10.4. Or am I mis-reading them?

Are some of the other patch changes generic / wise enough to warrant general inclusion? Some of them seem like they do some value checking, which might avoid a NULL reference or something like it.

**Comment by kencu** [comment]
Oh oh - one of Fred's patches needed some minor patchlevel tweaking, which I did and sent him, but I guess that fix hasn't made it here yet -- <https://github.com/devernay/TigerPorts/pull/1/commits/8c000538472794ce571eafbba2f4a0d9528f572b>.

**Comment by michaelld** [comment]
So ... is this one ready to commit? Or are there changes to it? I'll admit that I haven't tested yet, but I see no issues on first reading. I think some of the patches are generic enough to be used for any OS, not just tiger.

**Comment by kencu** [comment]
One of Fred's patches needs to be fixed and force pushed or just pushed first. 

I have only tested this set of patches on Tiger (where they work just fine, once the patch is fixed). I'll see if it builds on Sierra, before we get terribly brave :> I agree though, almost all of the fixes are blocked with 10.5+ blocks, except for a couple that apply broadly.

**Comment by kencu** [comment]
I tried this on Sierra, both with the patches guarded to Tiger only (works, of course) and then with all the patches enabled (removing the Tiger guard in the portfile). 

Both builds go through to completion, and appear to work normally. All the apps load, menus work, and seem to function correctly with 10 minutes worth of testing.

I haven't tried it with all patches enabled on all the myriad of other variations of systems in between, and haven't tried it +universal, or 32bit only -- but it works on Tiger, and AFAICT it works on Sierra.

**Comment by michaelld** [comment]
OK; good. I'd actually prefer to use generic patches that work for all OSs if/when possible. Yes, the patch itself is checking internally for the OS, but that's fair since any project of the complexity of Qt will do that anyway. Please ping here when all of the patches are in place for this PR & I'll test on +universal & so forth as best I can on my systems. From first reading of the patches, I don't see any obvious issues.

**Comment by kencu** [comment]
OK. No response from Fred for quite a while now, so I edited that one patch to fix the patchlevel and force-pushed it up to his PR as per our guidelines on how to do that. None of the Travis builds will finish, but they will double-check my patching at least (works fine here, of course).

**Comment by devernay** [comment]
Thanks Ken, and sorry about not being so responsive

**Comment by kencu** [comment]
Hi Michael. I think we should probably move on this PR soonishly. Now that #833 was committed, we have a conflict. I think the way is was originally handled in this PR is probably the right way to do that fix, so I guess I'd probably revert #833 and commit this PR.

What do you think?

**Comment by kencu** [comment]
Well I tried to resolve this conflicts in this commit using the web editor. I may not have done it quite correctly, however, as I see there are still conflicts, and I have a "merge branch master into qt4-mac-tiger" commit registered now. Truly hope I didn't make things worse by trying to make them better...

**Comment by michaelld** [comment]
I massaged the patches & verified building on Intel 10.8, 10.12, and 10.13. @kencu verified on PPC 10.4 and 10.5. Thus, I just committed what I think were all of the fixes from this PR. Hence I'm closing this PR. If I missed something or there are more fixes out there, please open a ticket to address them.

**Pull request closed without merging**
