### PR TITLE
py-trio: update to 0.13.0, add python38 variant

### PR DESCRIPTION
**Pull request by jandemter**
* update to version 0.13.0
* add python38 variant for trio and dependencies
* remove patch that isn't necessary anymore

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.3 19D76
Xcode 11.3.1 11C504

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. @reneeotten ?

**Comment by reneeotten** [comment]
> LGTM. @reneeotten ?

I'd agree, the changes look good. It does change four ports in one commit though, but since the others are only adding a PY38 subport I think that might be okay.

**Comment by pmetzger** [comment]
I think it's okay.

**Comment by reneeotten** [comment]
thanks @jandemter !

**Pull request merged**
