### PR TITLE
openttd: update to version 1.7.1

### PR DESCRIPTION
**Pull request by kencu**
delete patchfiles for fixes incorporated into 1.7.1

@neverpanic 
###### Description

It looks like the upstream devs have incorporated fixes and adjustments for the three patchfiles that were previously needed; none are needed any longer.

###### Tested on
macOS 10.6, macOS 10.12
Xcode 4.2, 8.3

The above systems build, launch, and appear to work correctly.
I did not try a build on systems between 10.7 and 10.11, nor on 10.4 or 10.5 PPC.

### CODE REVIEW

**Comment by l2dy** [comment]
Please clear revision.

**Comment by kencu** [comment]
Thanks, @l2dy - I had told myself twice to remember to do that, but still is slipped past me. Done now.

**Comment by kencu** [comment]
Hmm. Interesting. The cairo build is failing during the travis check. I have cairo installed on both 10.6 and 10.12, though. I wonder why it's failing on Travis?
```
$ port -v installed cairo
Warning: port definitions are more than two weeks old, consider updating them by running 'port selfupdate'.
The following ports are currently installed:
  cairo @1.14.6_0+quartz+universal+x11 platform='darwin 16' archs='i386 x86_64' date='2016-10-12T00:30:39-0700'
  cairo @1.14.8_0+quartz+universal+x11 (active) platform='darwin 16' archs='i386 x86_64' date='2016-12-17T11:04:12-0800'
```
```
$ port -v installed cairo
The following ports are currently installed:
  cairo @1.14.8_0+quartz+universal+x11 (active) platform='darwin 10' archs='i386 x86_64' date='2016-12-20T07:36:32-0800'
```

**Comment by neverpanic** [comment]
Don't worry about it, it might just be running into a timeout or something equally trivial. It's a new system, so I'm not surprised it's not very stable yet.

I'll give it a shot locally.

**Comment by mojca** [comment]
Cool!!!
@l2dy and @neverpanic: thanks for going live with the builds. Time for the first beer, even if one dependency failed.

**Pull request merged**
