### PR TITLE
nco: update to 5.0.4

### PR DESCRIPTION
**Pull request by remkos**
#### Description

Simple update to upstream version 5.0.4 (from 5.0.3).
I also added myself as maintainer as this port appears abandoned. See https://trac.macports.org/ticket/64213

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 12.1 21C52 x86_64
Xcode Command Line Tools 13.2.0.0.1.1638488800

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
> I also added myself as maintainer as this port appears abandoned. See https://trac.macports.org/ticket/64213

then please add: `Closes: https://trac.macports.org/ticket/64213` to body of the commit message such that this ticket will be closed automatically when the PR is merged. We'll have to wait the usual 72 hours, but I'll merge this as soon as that time has passed.

**Comment by remkos** [comment]
Thanks @reneeotten for the comment. I keep learning how to do things. 
I did not manage to update and squash properly, so I will start a new PR. Otherwise it is going to take too much frustration. Sorry if this takes a bit more time for you.

**Comment by reneeotten** [comment]
@remkos it would be beneficial to brush up on your git vodoo a little bit ;) You already started off correctly by making a separate branch (i.e., `remkos-nco`), made changes there and submitted a PR. If changes are requested the easiest way is to do (assuming that your using `git` from the command-line, if not you really should switch to that!):

1. `git checkout remkos-nco`
2. make the requested changes
3. `git commit -a --amend`; this will amend your previous commit, if needed you can change the commit message as well
4. since you now rewrote the git history (which is fine in a PR by the way), you will need to force-push to your branch, assuming that your fork is called `origin` that would be done with `git push origin -f`. If you want to be extra careful and make sure you're pushing to the correct place you can first add the `--dry-run` flag.

**Comment by remkos** [comment]
Thanks @reneeotten for the refresher. I must say I've gotten lazy and dependent on the GitHub App or Sourcetree for all that. And somehow after doing the amend and squash, I could not avoid the merge. Since I know the demand of Macports to have only one commit per PR, I wanted to avoid the merge, but did not manage. 
Interesting enough, I did not have this issue when making two commits and then squash.
Well, let's see next time. I'll improve over time :)

**Pull request closed without merging**
