### PR TITLE
openjdk build fixes

### PR DESCRIPTION
**Pull request by saagarjha**
#### Description

A couple of fixes for building the openjdk ports.

###### Type(s)

- [X] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.4 21F5048e
Xcode 13.3 13E113 

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] checked your Portfile with `port lint --nitpick`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by usersxx** [comment]
Looks good to me

**Comment by usersxx** [comment]
This pr can be merged after the ci successfully completes

**Review by usersxx — COMMENTED** [review]
Add a patchfile with:
```
--- make/autoconf/toolchain.m4.orig
+++ make/autoconf/toolchain.m4
@@ -1,5 +1,5 @@
 #
-# Copyright (c) 2011, 2021, Oracle and/or its affiliates. All rights reserved.
+# Copyright (c) 2011, 2022, Oracle and/or its affiliates. All rights reserved.
 # DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 #
 # This code is free software; you can redistribute it and/or modify it
@@ -234,7 +234,7 @@ AC_DEFUN_ONCE([TOOLCHAIN_DETERMINE_TOOLCHAIN_TYPE],
   if test "x$OPENJDK_TARGET_OS" = xmacosx; then
     if test -n "$XCODEBUILD"; then
       # On Mac OS X, default toolchain to clang after Xcode 5
-      XCODE_VERSION_OUTPUT=`"$XCODEBUILD" -version 2>&1 | $HEAD -n 1`
+      XCODE_VERSION_OUTPUT=`"$XCODEBUILD" -version | $HEAD -n 1`
       $ECHO "$XCODE_VERSION_OUTPUT" | $GREP "Xcode " > /dev/null
       if test $? -ne 0; then
         AC_MSG_NOTICE([xcodebuild output: $XCODE_VERSION_OUTPUT])
```

This will fix build for macOS Monterey arm64

**Comment by saagarjha** [comment]
I have that patchfile, it only helps with the OpenJDK 18 build. For OpenJDK 17 you need that as well as the backported patch I added, which fixes some UB that causes the JVM’s assembler to not function properly due to a miscompile.

**Comment by usersxx** [comment]
> Add a patchfile with:
> 
> ```
> --- make/autoconf/toolchain.m4.orig
> +++ make/autoconf/toolchain.m4
> @@ -1,5 +1,5 @@
>  #
> -# Copyright (c) 2011, 2021, Oracle and/or its affiliates. All rights reserved.
> +# Copyright (c) 2011, 2022, Oracle and/or its affiliates. All rights reserved.
>  # DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
>  #
>  # This code is free software; you can redistribute it and/or modify it
> @@ -234,7 +234,7 @@ AC_DEFUN_ONCE([TOOLCHAIN_DETERMINE_TOOLCHAIN_TYPE],
>    if test "x$OPENJDK_TARGET_OS" = xmacosx; then
>      if test -n "$XCODEBUILD"; then
>        # On Mac OS X, default toolchain to clang after Xcode 5
> -      XCODE_VERSION_OUTPUT=`"$XCODEBUILD" -version 2>&1 | $HEAD -n 1`
> +      XCODE_VERSION_OUTPUT=`"$XCODEBUILD" -version | $HEAD -n 1`
>        $ECHO "$XCODE_VERSION_OUTPUT" | $GREP "Xcode " > /dev/null
>        if test $? -ne 0; then
>          AC_MSG_NOTICE([xcodebuild output: $XCODE_VERSION_OUTPUT])
> ```
> 
> This will fix build for macOS Monterey arm64

Oops, The patch is already added for `openjdk17` port.

**Review by usersxx — APPROVED** [review]

**Review by usersxx — APPROVED** [review]

**Comment by usersxx** [comment]
@mascguy, You may merge this pr

**Review by mascguy — APPROVED** [review]

**Pull request merged**
