### PR TITLE
qt4-mac: fix build on aarch64

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Fix this finally

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.7
Xcode 15.4

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Well, so the current status is: Qt4 itself works and its own GUI apps work. However other apps when built with it fail to launch. Something is not yet right.

**Comment by barracuda156** [comment]
@ryandesign @michaelld @mascguy @RJVB Anyone interested to try this out? (And improve upon?)

My interest was to be able to test QMPlay2 builds with Qt4 on arm64, since it is fast, and I may need numerous rebuilds to fix what I work on. Unfortunately, for this aim it does not work (QMPlay2 app builds but fails to launch). However, QMPlay2 that I try to build is a heavily patched version, where patches were made obviously not on arm64. So this is not a reference case.

AFAICT, Qt4 own apps (Designer, qdbusviewer) are functional normally. I was also able to build Qt4-based version of Obsession hotline client, and it connected to hotline servers, with chats and file browsing. So at least for these cases it appears to be fully working.

This is not something I really need for its own sake or care much if it gets merged, by I am interested to have it working for QMPlay2 testing. So if someone has some motivation to have this working, please, take a look.

**Comment by RJVB** [comment]
On Monday November 25 2024 11:22:31 Sergey Fedorov wrote:
>@ryandesign @michaelld @mascguy @RJVB Anyone interested to try this out? (And improve upon?)

How would I test this out - are you offering me an ASi machine? ;)

**Comment by barracuda156** [comment]
I guess no one has interest in getting in on arm64, closing.

**Comment by mascguy** [comment]
> I guess no one has interest in getting in on arm64, closing.

Sergey, try to be patient. No response doesn't mean folks aren't interested.

In my case, I don't have an arm-based Mac, so I can't test. But this would definitely be a nice addition.

@kencu, anyone... is there someone that can help test this?

**Comment by RJVB** [comment]
On Sunday December 01 2024 08:10:01 Christopher Nielsen wrote:

>In my case, I don't have an arm-based Mac, so I can't test. But this would definitely be a nice addition.

I guess there's always the possibility to test the transparency of this patch on non-ARM systems and just commit it when satisfied there are no side-effects (I run a very different Qt4 port locally so my contribution wouldn't be authorative here).
If the port is currently broken on ARM anyway even an imperfect fix will be progress that can be further improved upon if and when bug reports from real-world application come in.

**Review by mascguy — APPROVED** [review]
LGTM, let's merge and see if the build is fixed for ARM.

**Comment by barracuda156** [comment]
@mascguy Build should work; Qt4 itself may need extra fixes from someone who knows both the platform and Qt well enough.

**Comment by mascguy** [comment]
> @mascguy Build should work; Qt4 itself may need extra fixes from someone who knows both the platform and Qt well enough.

Confirmed, the arm build looks good:

https://build.macports.org/builders/ports-14_arm64-builder/builds/47921

**Comment by RJVB** [comment]
Now let's just hope that those who actually use this will understand that ARM support is experimental and that issues should be reported! :)

**Comment by barracuda156** [comment]
I have something working beyond `Obsession`:

lazarus_qt4

**Comment by RJVB** [comment]
Not sure what I'm looking at but I'm reminded why back in the day we decided that QtCurve would be the "official" widget style to use in KDE4 applications... (a priori with one of my configuration sets).

**Comment by barracuda156** [comment]
> Not sure what I'm looking at

Ah, just showing that Qt4 is usable on arm64: this is Lazarus IDE built with Qt4 backend on Sonoma.

**Pull request merged**
