### PR TITLE
binutils: update to 2.41; fix build before 10.10

### PR DESCRIPTION
**Pull request by catap**
#### Description

Closes: https://trac.macports.org/ticket/65621

###### Type(s)

- [x] bugfix

###### Tested on

macOS 10.5.8 9L34 i386
Xcode 3.1.4 9M2809

macOS 10.6.8 10K549 x86_64
Xcode 3.2.6 10M2518

macOS 12.7.1 21G920 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou may I ask you to test it?

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
The result on a Snow Leopard VM:

```
make[4]: Entering directory `/opt/local/var/macports/build/_Users_strega_macports-ports_devel_binutils/binutils/work/binutils-2.40/binutils'
/bin/sh ./libtool  --tag=CC   --mode=link /opt/local/bin/clang-mp-11 -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -I./../zlib  -pipe -Os -arch x86_64      -L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64 -o objdump objdump.o dwarf.o prdbg.o demanguse.o rddbg.o debug.o stabs.o rdcoff.o bucomm.o version.o filemode.o elfcomm.o od-macho.o ../opcodes/libopcodes.la ../libctf/libctf.la ../bfd/libbfd.la ../libiberty/libiberty.a -lintl  ../libsframe/libsframe.la
libtool: link: /opt/local/bin/clang-mp-11 -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -I./../zlib -pipe -Os -arch x86_64 -Wl,-headerpad_max_install_names -arch x86_64 -o .libs/objdump objdump.o dwarf.o prdbg.o demanguse.o rddbg.o debug.o stabs.o rdcoff.o bucomm.o version.o filemode.o elfcomm.o od-macho.o  -L/opt/local/lib ../opcodes/.libs/libopcodes.dylib -L/opt/local/var/macports/build/_Users_strega_macports-ports_devel_binutils/binutils/work/binutils-2.40/bfd/../libiberty/pic -L/opt/local/var/macports/build/_Users_strega_macports-ports_devel_binutils/binutils/work/binutils-2.40/zlib -L/opt/local/var/macports/build/_Users_strega_macports-ports_devel_binutils/binutils/work/binutils-2.40/opcodes/../libiberty/pic ../libctf/.libs/libctf.dylib -L/opt/local/var/macports/build/_Users_strega_macports-ports_devel_binutils/binutils/work/binutils-2.40/libctf/../libiberty/pic /opt/local/var/macports/build/_Users_strega_macports-ports_devel_binutils/binutils/work/binutils-2.40/bfd/.libs/libbfd.dylib ../bfd/.libs/libbfd.dylib -liberty -ldl -lz -lzstd /opt/local/var/macports/build/_Users_strega_macports-ports_devel_binutils/binutils/work/binutils-2.40/libsframe/.libs/libsframe.dylib ../libiberty/libiberty.a /opt/local/lib/libintl.dylib ../libsframe/.libs/libsframe.dylib
Undefined symbols for architecture x86_64:
  "_ctf_import", referenced from:
      _dump_bfd in objdump.o
  "_ctf_dump", referenced from:
      _dump_bfd in objdump.o
  "_ctf_dict_close", referenced from:
      _dump_bfd in objdump.o
  "_ctf_close", referenced from:
      _dump_bfd in objdump.o
  "_ctf_parent_name", referenced from:
      _dump_bfd in objdump.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by catap** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou thanks, I've tested it on 10.5 and it works like a charm. So, keep it as draft until it fixed and tested everywhere. Probably today.

**Comment by catap** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou should be fixed now

**Comment by catap** [comment]
Wired, I can't switch from draft to PR :(

**Review by aeiouaeiouaeiouaeiouaeiouaeiou — APPROVED** [review]
Finally the build is completed successfully, LGTM

**Pull request merged**
