### PR TITLE
qgis3, qgis3-ltr, pdal: updates

### PR DESCRIPTION
**Pull request by nilason**
#### Description

Update `qgis3` to version 3.36.0.
Update `qgis3-ltr` to version 3.34.4.
Update `pdal` to version 2.6.3.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.3.1 23D60 arm64
Xcode 15.2 15C500b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

Broken dependencies reported in [ticket#69415](https://trac.macports.org/ticket/69415) will cause failure for qgis3/qgis3-ltr with the default `+plugin_support[pyver]` variant, it works fine with the variant disabled.

### CODE REVIEW

**Comment by nilason** [comment]
Added a commit which temporary disables the dependency on `py-plotly` (part of variant `+plugin_support[pyver]`), which is broken and _not_ necessary for the workings of core QGIS. If the CIs pass, this is ready to be merged.

**Comment by nilason** [comment]
The failed macos11 run is time-outed. This is good to be merged as far as I'm concerned.

**Comment by i0ntempest** [comment]
This has broken the grass variant because a patched file is removed (or moved?) in the source.

**Comment by nilason** [comment]
> This has broken the grass variant because a patched file is removed (or moved?) in the source.

Nice catch, I was too occupied with py-plotly and overlooked this. However, the file being patched was only renamed with QGIS 3.36, so #22891 addresses this for LTR version.

**Pull request merged**
