### PR TITLE
update LibreSSL to the current 2.7.2

### PR DESCRIPTION
**Pull request by janstary**
There has been a lot of improvement since 2.5.5
Beside many others:

 * Fixed builds macOS 10.11 and older.

 * Added support for many OpenSSL 1.0.2 and 1.1 APIs, based on
   observations of real-world usage in applications. These are
   implemented in parallel with existing OpenSSL 1.0.1 APIs - visibility
   changes have not been made to existing structs, allowing code written
   for older OpenSSL APIs to continue working.

 * Extensive corrections, improvements, and additions to the
   API documentation, including new public APIs from OpenSSL that had
   no pre-existing documentation.

Tested on MacOS 10.13.2 with:
curl, cvs, kerberos5, lynx, opusfile, python27, python36, tcpdump, unbound, wget, xar

Closes https://trac.macports.org/ticket/55264

### CODE REVIEW

**Comment by janstary** [comment]
libevent also builds fine, and no longer needs the patch.

**Comment by janstary** [comment]
sysutils/ntp also builds fine with the new LibreSSL.
Bundled with the libevent commit, sorry.

**Comment by raimue** [comment]
Could you add the "Closes:" lines to the commit message? Then the tickets will be closed automatically when this is merged.

To do this and to separate the changes in the previous commit, just force-push revised commits to your branch.

**Comment by janstary** [comment]
net/qpid-proton also builds, with a trivial `#ifdef`

**Comment by janstary** [comment]
Rebased and fixed to separate the commits properly,
and to include the respective "Closes:"  in the commit messages.
Thanks, @raimue .

**Comment by janstary** [comment]
The Travis fail, perhaps to have some variability, is now:
"Portfile is from the future - check date and time of your system"

**Comment by raimue** [comment]
See the comment from maintainer @jeremyhu at [Trac#55264](https://trac.macports.org/ticket/55264#comment:9).

**Comment by janstary** [comment]
Commenting there.

**Comment by janstary** [comment]
maportsbot says maintainer timeout. what happens now?

**Comment by pmetzger** [comment]
Now I would recommend waiting a bit longer for @jeremyhu and probably bringing up this PR on the -dev mailing list. It's infrastructure rather than a leaf port so it probably deserves an actual comment from him or someone equally skilled.

**Comment by raimue** [comment]
This is not maintainer timeout, as @jeremyhu reacted in the corresponding ticket. The bot does not know that, though.

**Comment by pmetzger** [comment]
@raimue I am reading @jeremyhu as having said he doesn't want this done for the moment. Am I reading that correctly? If so, we should close this temporarily until a solution is found for Trac ticket 54744.

**Comment by janstary** [comment]
> I'm happy to bump libressl-devel

@jeremyhu , does that mean you are OK with doing the same for libressl-devel,
as opposed to libressl, which I did here? That would be one more commit to this.

**Comment by kencu** [comment]
I read it as you could do it with libressl-devel, but not this port, to avoid revupgrade hell. That would be a commit *instead* of this.

**Comment by janstary** [comment]
Yes, instead of the first commit in this branch.
The changes to the other ports would remain the same.

**Comment by janstary** [comment]
updating libressl-devel instead on https://github.com/macports/macports-ports/pull/1671

**Pull request closed without merging**
