### PR TITLE
gtk{2,3}{,-devel}: Use GTK3 version of `gtk-update-icon-cache` by default

### PR DESCRIPTION
**Pull request by qwertychouskie**
#### Description

If building a port that needs to run `gtk-update-icon-cache`, but `gtk2` is no longer installed, the port will fail to build.  This is because gtk3's `gtk-update-icon-cache` is currently renamed to `gtk-update-icon-cache-3.0` to not conflict with the `gtk2` version.  This PR makes it so the gtk2 version is renamed to `gtk-update-icon-cache-2.0`, and the gtk3 version keeps the default name of `gtk-update-icon-cache`.  GTK2 is long deprecated, the list of things still using it is shrinking over time, and therefore the likelyhood of having a build fail due to `gtk-update-icon-cache` missing is going to keep going up if we depend on the gtk2 version being installed. In fact, as I get to updating more XFCE stuff, the list of things depending on `gtk2` is going to get even smaller.

FWIW, on my Ubuntu system, `gtk-update-icon-cache` is installed as a separate package, and is built from the GTK3 sources.  There does not appear to be a gtk2 version of this binary even available.

See https://github.com/macports/macports-ports/pull/23674#issuecomment-2080224907 for an updated build that is broken by the old behavior.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 14.4.1 23E224 arm64
Xcode 15.3 15E204a

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mascguy** [comment]
Converting to draft for a few days, until I've had a chance to test with dependent ports. (Otherwise it might get merged at the 72-hour mark, and these ports are critical.)

**Comment by kencu** [comment]
and about 77 ports have already been configured to use gtk-update-icon-cache-3.0 now, so all those will presumably have to be changed if this is done:

https://github.com/search?q=repo%3Amacports%2Fmacports-ports%20gtk-update-icon-cache-3.0&type=code

**Comment by kencu** [comment]
not to mention that gtk-update-icon-cache-4.0 will be the new kid soon enough... wouldn't it be nice if there was a "fix this once" approach to some of these things that didn't require redoing the same work over and over...

**Comment by qwertychouskie** [comment]
> not to mention that gtk-update-icon-cache-4.0 will be the new kid soon enough... wouldn't it be nice if there was a "fix this once" approach to some of these things that didn't require redoing the same work over and over...

It doesn't look like GTK4 has a `gtk-update-icon-cache` binary.  Hopefully this change is just one-and-done.

**Comment by qwertychouskie** [comment]
> and about 77 ports have already been configured to use gtk-update-icon-cache-3.0 now, so all those will presumably have to be changed if this is done:
> 
> https://github.com/search?q=repo%3Amacports%2Fmacports-ports%20gtk-update-icon-cache-3.0&type=code

Is it best to update one port per commit or have one supercommit updating all the ports?

**Comment by mohd-akram** [comment]
This would be nice to have. I think one commit is fine in this case since it’s all the same change.

**Comment by mascguy** [comment]
> This would be nice to have. I think one commit is fine in this case since it’s all the same change.

The following comment summarizes the key concern with this PR:

https://github.com/macports/macports-ports/pull/23674#issuecomment-2106825881

**Comment by mohd-akram** [comment]
I don't think a find and replace is a lot of work tbh. It's also used in the activate stage AFAIK so no rev-bump needed. And we get rid of a bunch of patches.

**Comment by reneeotten** [comment]
@mascguy ease take care of this PR and the few that depends on them. If nothing happens in the next week, I will start closing them.

**Comment by qwertychouskie** [comment]
@reneeotten @mascguy I finally had a good chance to address updating all the Portfiles for applications that call `gtk-update-icon-cache` to call the correct versions (`gtk-update-icon-cache-2.0` for GTK2 apps, `gtk-update-icon-cache` for GTK3 apps).  This PR should be ready to merge.

**Comment by mascguy** [comment]
> @reneeotten @mascguy I finally had a good chance to address updating all the Portfiles for applications that call `gtk-update-icon-cache` to call the correct versions (`gtk-update-icon-cache-2.0` for GTK2 apps, `gtk-update-icon-cache` for GTK3 apps).  This PR should be ready to merge.

There's another gotcha that you need to deal with: Users routinely have both GTK2 and GTK3 installed. And when that's the case, you have a problem: These updated ports will try to overwrite the `gtk-update-icon-cache` binary of the other port. So MacPorts will correctly fail to install the update, due to that conflict.

So we'll need to add the so-called "deactivate hack," deactivating the other port prior to activation. But it should only be done for the previous version/revision.

Let me know if this makes sense. I can also dig up a reusable tcl procedure, which I've used previously for such a case.

**Comment by qwertychouskie** [comment]
> I can also dig up a reusable tcl procedure, which I've used previously for such a case.

That would be perfect.  Alternatively, I do have maintainer edits turned on for this PR, so you could commit it directly yourself it you prefer.

**Comment by qwertychouskie** [comment]
@mascguy Any update?  Perhaps another route would be to make the new revision of gtk3 conflict with the old revision of gtk2, so the gtk2 update will always get installed first (if MacPorts' dependency resolution works like that).  Would that work?

**Comment by qwertychouskie** [comment]
> I can also dig up a reusable tcl procedure, which I've used previously for such a case.

@mascguy I just wanted to check on this since it's been over a month with no response.  Other updates are pending this PR being merged (e.g. https://github.com/macports/macports-ports/pull/24851), so I'd like to get this finished and merged as quickly as possible.

**Comment by mascguy** [comment]
> > I can also dig up a reusable tcl procedure, which I've used previously for such a case.
> 
> @mascguy I just wanted to check on this since it's been over a month with no response.  Other updates are pending this PR being merged (e.g. https://github.com/macports/macports-ports/pull/24851), so I'd like to get this finished and merged as quickly as possible.

Here's our documentation for the deactivation logic, which includes a good example.

For your purposes, you'll need to check for two ports: Both the regular one, and `-devel`.

Take a look, and let me know if it makes sense.

**Comment by mascguy** [comment]
> > @mascguy I just wanted to check on this since it's been over a month with no response.  Other updates are pending this PR being merged (e.g. https://github.com/macports/macports-ports/pull/24851), so I'd like to get this finished and merged as quickly as possible.
> 
> Here's our documentation for the deactivation logic, which includes a good example.
> 
> For your purposes, you'll need to check for two ports: Both the regular one, and `-devel`.
> 
> Take a look, and let me know if it makes sense.

Sorry, forgot the link:

https://trac.macports.org/wiki/PortfileRecipes#deactivatehack

**Comment by reneeotten** [comment]
so is anyone going to work on this and resolve it anytime soon? If not, I am going to close the PR and the ones that depend on it. 

You can always reopen them once you had the time to work on it - the PR queue isn't here to park unfinished PRs for extended periods of time.

**Comment by qwertychouskie** [comment]
> so is anyone going to work on this and resolve it anytime soon? If not, I am going to close the PR and the ones that depend on it.
> 
> You can always reopen them once you had the time to work on it - the PR queue isn't here to park unfinished PRs for extended periods of time.

I can probably finish it this weekend now that I have been provided the information needed to finish it.

**Comment by qwertychouskie** [comment]
Alright, I believe this should be ready to be merged now.

**Comment by reneeotten** [comment]
@mascguy as the relevant maintainer please take care of this PR

**Comment by qwertychouskie** [comment]
@mascguy Any chance you could take a look at this PR and merge it if everything is good?

**Comment by qwertychouskie** [comment]
Rebased onto latest `master`.

Are there any plans to merge this?  I have other port updates that are waiting on this PR being merged, and I'd like to get these upstreamed soon so my local state isn't constantly diverged from upstream.

**Comment by reneeotten** [comment]
@mascguy this has been open now for more than 6 months; anytime would be good now or I will close the PR

**Comment by mohd-akram** [comment]
What's the update on this? The CI log seems fine.

**Pull request merged**
