### PR TITLE
execline: update to 2.9.5.1

### PR DESCRIPTION
**Pull request by saj**
#### Description

There was a small [bug](https://skarnet.org/lists/skaware/2003.html) in execline 2.9.5.0.  Laurent [released a fix](https://skarnet.org/lists/skaware/2008.html) in .1.

Thank you, @herbygillot, for keeping this port up to date.

This works on my machine™, though GitHub Actions is complaining about some inscrutable failure on macOS 14.  I am unable to test on macOS 14.  Let me know if this is a true positive failure, and I will rework somehow.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.7.4 21H1123 x86_64
Command Line Tools 14.2.0.0.1.1668646533

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
That's an odd one.  Perhaps add a commit right before yours that revbumps `skalibs` to see if `target` gets updated to a different value, and if then `skalib`'s `configure` will match it...?

**Comment by saj** [comment]
> Perhaps add a commit right before yours that revbumps `skalibs`

Good idea.  This worked.

(GHA is queued again because I amended my commit message with the observations below, then pushed once more.  Now I have no idea how to dig out the previous build that passed. 😞   Sorry.)

I downloaded and extracted the following tarball.
https://kmq.jp.packages.macports.org/skalibs/skalibs-2.14.1.1_0.darwin_23.arm64.tbz2

```
% cat opt/local/lib/skalibs/sysdeps/target 
arm64-apple-darwin23.2.0
```

And here is the error from GitHub Actions for macos-14.

```
   Checking target system type...
    ... arm64-apple-darwin23.4.0
  ./configure: error: target arm64-apple-darwin23.4.0 does not match the contents of /opt/local/lib/skalibs/sysdeps/target
```

```
% uname -r
21.6.0
```

I guess we had avoided this problem in the past because Laurent usually cuts a release for {skalibs, execline, s6} simultaneously, and because you had fastidiously bumped all three at around the same time in the past. :)

Apple appear to have dropped all security support for Monterey, so `21.6.0` is probably the last Darwin/XNU release I will see.  Maybe we just got lucky/unlucky with Ventura and Sonoma, respectively.

I think this means we need a revbump on s6 as well?

```
% port echo depends:skalibs
execline                        
s6
```

```
% port cat s6 | grep version
version             2.12.0.4
```

2.12.0.4 is still [current](https://skarnet.org/software/s6/).

Should I revbump s6 in a separate commit?  If a separate commit, should I copy-paste the rationale, or would it be sufficient to say 'see parent'?

**Comment by herbygillot** [comment]
I think it's fine to include a commit that revbumps `s6` as part of this PR, no need for a separate one.

**Comment by herbygillot** [comment]
Minor nitpick: since `s6` depends on both `execline` and `skalibs`, its revbump should probably happen _after_ the commit that updates `execline`.

**Comment by herbygillot** [comment]
Looks good, thank you very much @saj.

**Comment by saj** [comment]
Thank you!

**Pull request merged**
