### PR TITLE
dns-server: fix typo in long_description

### PR DESCRIPTION
**Pull request by grundoon**
#### Description

Corrects `VPN server` reference to `DNS server`.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?

### CODE REVIEW

**Comment by essandess** [comment]
Thank you very much for this correction, @grundoon.

**Comment by grundoon** [comment]
(oops sorry, noticed another tiny one – done now 😄)

**Comment by essandess** [comment]
Thanks again. Please squash the commits.

**Comment by grundoon** [comment]
Apologies, working directly on GitHub, no cli available at the moment – closing this and resubmitting combined PR.

**Pull request closed without merging**
