### PR TITLE
crossgcc: Add support for spec files from libgloss

### PR DESCRIPTION
**Pull request by mojca**
#### Description

This adds a symlink to `libgloss` and updates some cross-compilers.

I need to at least revbump (or update?) `msp430-elf-gcc`, but the page seems down at the moment.

Hopefully closes:    
* https://trac.macports.org/ticket/51397
* https://trac.macports.org/ticket/57572

See also #3336.

I tested the builds of some cross-compilers, but not all of them. I did not test the functionality itself.

@g5pw @ekawahyu

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mojca** [comment]
@raimue added some multilib patches in ec32f2908ae790f46639c41fe6a8f235b5f47d9 (see https://trac.macports.org/ticket/48543).

But looking at the [origin](https://git.archlinux.org/svntogit/community.git/log/trunk?h=packages/arm-none-eabi-gcc) of those patches it seems that the file has first been [changed](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/arm-none-eabi-gcc&id=b392f053c6c4ac07b085ccbc4e8fc4bf88849dbd) and then [removed](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/arm-none-eabi-gcc&id=5e0bb605d8587876356e89e9c0229da46094b4e1).

I first tested my changes with 9.1.0, then figured out I could increase the version instead of revbumping, so that changes to `crossgcc` would be taken into account, but finally I noticed that the patch no longer applies and started looking into the issue.

**Comment by mojca** [comment]
What archlinux seems to do in addition (and we are missing) is the following chunk of code:
```bash
  make DESTDIR="$pkgdir" install -j1

  cd $srcdir/build-gcc-nano
  make DESTDIR="$pkgdir.nano" install -j1
  # we need only libstdc nano files
  multilibs=( $($pkgdir/usr/bin/$_target-gcc -print-multi-lib 2>/dev/null) )
  for multilib in "${multilibs[@]}"; do
    dir="${multilib%%;*}"
    from_dir=$pkgdir.nano/usr/$_target/lib/$dir
    to_dir=$pkgdir/usr/$_target/lib/$dir
    cp -f $from_dir/libstdc++.a $to_dir/libstdc++_nano.a
    cp -f $from_dir/libsupc++.a $to_dir/libsupc++_nano.a
  done
```

**Comment by g5pw** [comment]
It looks like some patches are failing...

**Comment by mojca** [comment]
Yes, I accidentally upgraded without testing, as I wrote in the above notes. I'll push new changes (basically removing the patch completely) once I come back to my mac and let you know.

I'll also update msp430, even though that one is apparently (on purpose?) missing the spec files.

**Comment by mojca** [comment]
I updated the ports. Apart from the anomaly with msp430 that has been pointed out to me:
* https://sourceware.org/ml/newlib/2015/msg00926.html
* https://sourceware.org/ml/newlib/2015/msg00923.html

this should now hopefully work.

**Comment by mojca** [comment]
Strange, failing at
```
Installing dependency (10 of 12) 'msp430-elf-binutils' with variants '' (requesting '') ... [FAIL] (fetch)
```

**Pull request merged**
