### PR TITLE
remove obsolete python 3.7 variants

### PR DESCRIPTION
**Pull request by dgilman**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 13.6.1 22G313 x86_64
Command Line Tools 15.0.0.0.1.1694021235

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ra1nb0w** [comment]
ok for PothosLiquidDSP

**Comment by mndavidoff** [comment]
pipx: looks good. Thanks!

**Comment by funasoul** [comment]
OK for libsbml and libsbmlsim.
Thanks!

**Comment by Schamschula** [comment]
All my ports look good!

**Comment by herbygillot** [comment]
👍🏾 from me.

**Review by lpsinger — APPROVED** [review]

**Comment by dgilman** [comment]
I've rebased the branch and made some minor fixes from the port lint output:
- gpodder: remove missing variant
- rdiff-backup: remove duplicate dependency
- certbot-dns-namecheap: add homepage

**Comment by mamoll** [comment]
👍 for ompl

**Pull request merged**
