### PR TITLE
libtool: update to 2.4.7

### PR DESCRIPTION
**Pull request by michaelld**
#### Description

libtool: update to 2.4.7

remove now-unnecessary `xattr` sections as well as integrated or now-unnecessary patches

Closes: https://trac.macports.org/ticket/55652
Closes: https://trac.macports.org/ticket/63736

I have been using this new version since it was released & have not had any issues. I know that some of the ports I update use libtool, so all seems good from my experience.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.6.5 20G526
Xcode 12.3 12C33

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by michaelld** [comment]
NOTE: This PR is as a courtesy to the other maintainer as much as anything. If you are not the other maintainer, please allow at least the standard maintainer timeout before merging. I will do the same. Thank you!

**Comment by mascguy** [comment]
@larryv Larry, are you still an active MacPorts member, or more semi-retired...?

**Comment by pmetzger** [comment]
@michaelld Would it be best if you merged after you felt enough time had passed? Then we don't risk the rest of us cutting it off too soon for your tastes.

**Comment by michaelld** [comment]
@pmetzger Yes that's the intent; thanks for asking! I wanted to give @larryv a solid "maintainer timeout" to review. Unless I hear otherwise, I'll merge tomorrow, probably in the morning (US/Eastern). I've been using this version now since the day it was released with no issues.

**Pull request merged**
