### PR TITLE
topydo: Use Python 37

### PR DESCRIPTION
**Pull request by essandess**
#### Description

Fixes https://trac.macports.org/ticket/60046

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
Please add the Trac ticket reference to the commit message.

**Comment by essandess** [comment]
@mf2k I see it there: https://github.com/macports/macports-ports/pull/6313/commits/5c8d8f8a21b839da850d3940d416ec80d4e49828

**Comment by essandess** [comment]
@mf2k I see it there: https://github.com/macports/macports-ports/pull/6313/commits/5c8d8f8a21b839da850d3940d416ec80d4e49828

**Comment by mf2k** [comment]
Since the dependencies are changing, the `revision` line needs to be added and set to 1.

**Comment by essandess** [comment]
@mf2k Done thank you.

**Comment by reneeotten** [comment]
looks good to me. When running the test-suite it has some failures though, but these are present for both PY36 and PY37 so the Python version itself doesn't cause this.

**Pull request merged**
