### PR TITLE
poppler: update to 20.11.0

### PR DESCRIPTION
**Pull request by michaelld**
#### Description

poppler: update to 20.11.0

+ Remove integrated patchfiles (patch-bug106417.diff, patch-327a7ce0.diff)

+ Integrate residual of patch-bug106417.diff into patch-glib_CMakeFiles.txt-fix-include-ordering.diff

+ update patches to apply cleanly

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.0.1 20B5012d
Xcode 12.2 12B5035g

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by michaelld** [comment]
Doing this because I knew there would be multiple patch changes to keep the fixes from my prior PR working. The new patches are more robust than the prior set, and should be easier to maintain moving forward.

**Comment by michaelld** [comment]
I neglected to fix the patch for `poppler-qt5` ... working on that right now & will push that fix shortly & we'll see if the CI is happier :)

**Comment by michaelld** [comment]
CI looks better now. At least both subports pass on newer CI. Looks like the "thread local" setting isn't being correctly dealt with by "port" internally, but that's not an issue for this PR to fix. Thus, I think this PR is good to go.

**Comment by michaelld** [comment]
> Thanks, testing now. I assume this requires #8985 as well?

Correct!

**Review by dbevans — APPROVED** [review]
This looks good.  Tested with poppler-data 0.4.10 and #8985.  Note that this version of poppler increments the core libpoppler version so ports that still use the core library will have to be rebuilt as is often the case.

**Pull request merged**
