### PR TITLE
onetbb: update to 2021.10.0

### PR DESCRIPTION
**Pull request by mohd-akram**
###### Tested on
macOS 13.4.1 22F770820d x86_64
Xcode 14.3.1 14E300c

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?

### CODE REVIEW

**Comment by barracuda156** [comment]
Did they pick an updated `doctest.h` where this has been fixed?

P. S. Allow me to try this please prior to merging.

**Comment by catap** [comment]
@mohd-akram shall it include revbump of all ports which linked against OneTBB?

**Comment by catap** [comment]
> @mohd-akram shall it include revbump of all ports which linked against OneTBB?

Seems that no need this time. Or at least some packages which is installed on my system.

**Comment by barracuda156** [comment]
@mohd-akram @catap GCC build is broken, unsupported flag is passed:
```
[ 38%] Linking C shared library ../../gnu_11.3_cxx11_32_macports/libtbbmalloc.dylib
cd /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_onetbb/onetbb/work/build/src/tbbmalloc && /opt/local/bin/cmake -E cmake_link_script CMakeFiles/tbbmalloc.dir/link.txt --verbose=ON
/opt/local/bin/gcc-mp-11 -pipe -Os -DNDEBUG -I/opt/local/include -arch ppc -mmacosx-version-min=10.6 -dynamiclib -Wl,-headerpad_max_install_names -Wl,-exported_symbols_list,"/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_onetbb/onetbb/work/oneTBB-2021.10.0/src/tbbmalloc/def/mac32-tbbmalloc.def" -Wl,-z,relro,-z,now,-z,noexecstack -L/opt/local/lib -Wl,-headerpad_max_install_names -latomic -compatibility_version 2.0.0 -current_version 2.10.0 -o ../../gnu_11.3_cxx11_32_macports/libtbbmalloc.2.10.dylib -install_name /opt/local/libexec/onetbb/lib/libtbbmalloc.2.dylib CMakeFiles/tbbmalloc.dir/backend.cpp.o CMakeFiles/tbbmalloc.dir/backref.cpp.o CMakeFiles/tbbmalloc.dir/frontend.cpp.o CMakeFiles/tbbmalloc.dir/large_objects.cpp.o CMakeFiles/tbbmalloc.dir/tbbmalloc.cpp.o CMakeFiles/tbbmalloc.dir/__/tbb/itt_notify.cpp.o  -Wl,-rpath,/opt/local/lib -Wl,-rpath,/opt/local/libexec/onetbb/lib -ldl 
ld: unknown option: -z
collect2: error: ld returned 1 exit status
make[2]: *** [gnu_11.3_cxx11_32_macports/libtbbmalloc.2.10.dylib] Error 1
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_onetbb/onetbb/work/build'
make[1]: *** [src/tbbmalloc/CMakeFiles/tbbmalloc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by barracuda156** [comment]
Flags come from here, apparently: https://github.com/oneapi-src/oneTBB/blob/f91f55f25ad121a39c5de3a1cacbd6c56ed7313c/cmake/compilers/GNU.cmake#L76
But I do not know what pulls them in.

**Comment by barracuda156** [comment]
Reported to upstream in an new issue, otherwise no one may see the comment in a closed PR dating back to February.
https://github.com/oneapi-src/oneTBB/issues/1148

**Comment by barracuda156** [comment]
Supposed to be fixed in https://github.com/oneapi-src/oneTBB/commit/539cbb3e67f8cde4b54c767626e015997755770b

**Comment by mohd-akram** [comment]
The build succeeded though? What specifically is it unsupported on?

**Comment by barracuda156** [comment]
> The build succeeded though? What specifically is it unsupported on?

@mohd-akram 
Yes, once wrong flags removed, it works.
I think you may just pick the commit from upstream addressing the issue which I linked above.

**Comment by mohd-akram** [comment]
I mean in the CI and locally for me. It seems like the commit is not quite right since it does work on macOS in some cases.

**Comment by barracuda156** [comment]
> I mean in the CI and locally for me. It seems like the commit is not quite right since it does work on macOS in some cases.

Looking at the upstream commit, it should disable -z flags, which fixes the problem. With Apple Clang those flags were not used to begin with, so that problem did not arise.

**Comment by mascguy** [comment]
> I mean in the CI and locally for me. It seems like the commit is not quite right since it does work on macOS in some cases.

Sergey is interested in getting the port to build with gcc too.

**Comment by barracuda156** [comment]
Upstream assumption was Apple == Apple Clang, so everything else was not considered. From multiple reports online I would assume that -z flags are generally unsupported by Apple linker and would break the build with Clang, if used. But with Apple Clang they are and were not picked, relevant CMake settings file lacks them.

**Comment by mohd-akram** [comment]
Thanks, that makes sense. I've added the commit as a patch. If it's good to go, we can merge this.

**Comment by barracuda156** [comment]
Should be good to go IMO.

**Review by mascguy — APPROVED** [review]

**Comment by catap** [comment]
I've discovered an issue with this update.

`opencascade` caches path to used OpenTBB, and one which I've installed from distfiles contains `libtbb.12.9.dylib` when this update installs `libtbb.12.10.dylib`

**Pull request merged**
