### PR TITLE
gdal: fix opportunistic linking to pcre2

### PR DESCRIPTION
**Pull request by nilason**
#### Description

Closes: https://trac.macports.org/ticket/67596

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6.6 21G646 arm64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by nilason** [comment]
> @nilason this port has a lot of variants to enable different features. May you add one more for pcre?

I did consider it and I wouldn't object too much either. I'm not absolutely positive though, that it will make any difference with sqlite3 not using it (see https://gdal.org/development/building_from_source.html#pcre2).

**Comment by nilason** [comment]
Let's investigate this a bit better. Perhaps adding pcre2 as a dependent would be preferable to yet another variant.

**Comment by nilason** [comment]
> In linux world there is a package called [sqlite3-pcre](https://repology.org/project/sqlite3-pcre/versions).

A small sqlite extension located at http://git.altlinux.org/people/at/packages/?p=sqlite3-pcre.git

**Comment by catap** [comment]
@nilason seems like a trivial additional to your update? :)

**Comment by nilason** [comment]
> @nilason seems like a trivial additional to your update? :)

Couldn't resist the challenge, ended up with #19094. However, after finishing that one, I took a closer look at GDAL source. The SQLite extension code needed is already included! I changed this PR to add `pcre2` as a dependency.

(#19094 still is useful for general sqlite and spatialite use).

**Comment by nilason** [comment]
@Veence ?

**Pull request merged**
