### PR TITLE
Port Update sgwi to version 1.1.8

### PR DESCRIPTION
**Pull request by saptarshi1729**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.3 19D76

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
thanks for the update! It appears however that PR #6685 attempts the same update? You can always push more commits to a PR, so please do not open a new one (just decide which one you want to continue working on and close the other). 

Additionally, you ideally should do the tasks that are listed in the PR check: make sure that it builds and works locally before submitting a PR.

**Comment by saptarshi1729** [comment]
> thanks for the update! It appears however that PR #6685 attempts the same update? You can always push more commits to a PR, so please do not open a new one (just decide which one you want to continue working on and close the other).
> 
> Additionally, you ideally should do the tasks that are listed in the PR check: make sure that it builds and works locally before submitting a PR.

Hi, Thanks for going through the pull request and giving your valuable feedback. I've gone through the logs but am not finding any error, it only says that the build on MacOS 10.13 has remained queued or has timed out. In an attempt to cross-verify, I had opened a new PR. Since it has worked in MacOS 10.14, can you please convey if it's alright or needs any changes?

Also, regarding local checks, I'd inform you that I'm unable to build the files locally due to "sudo port test" not working on my local machine saying "Unable to access file or directory", despite giving 777 permission to all folders in /opt as well as the parents of .../Portfile, due to which I'm forced to rely on remote build checks. Any suggestions to rectify or mend this problem would be of great help. Thanks again for your feedback.

**Comment by reneeotten** [comment]
are you still working on fixing this port @saptarshi1729 - if not please close this PR

**Comment by reneeotten** [comment]
closing this PR for now due to the lack of progress - feel free to reopen if you continue to work on this!

**Pull request closed without merging**
