### PR TITLE
mumps: allow non-parallel installation

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.13
Xcode 10.0

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by seanfarley** [comment]
I truly and utterly hate mumps. Is there any specific motivation for this change? Last time I tried this, there were library errors due to `mpiuni` on top of the fact that it made things even more complicated with trying to build downstream packages (e.g. petsc, fenics, etc.).

**Comment by MarcusCalhoun-Lopez** [comment]
> Is there any specific motivation for this change?

I have an idea for a side project (long term/low priority).
I would like to test several different math/science libraries to see which is best (and to learn more about them).

The problem I am running into is that mixing parallel and serial versions of libraries seems to be causing difficulties.
For example, installing the parallel version of HDF5 means it cannot be used with Octave.
Installing the serial version means it cannot be used with PETSc.

My solution has been to slowly try to install all ports as either serial or parallel.
Looking through the source, MUMPS seems to have a serial version and PETSc seems to support it.
However, I am at best an enthusiastic amateur, and you have a great deal more knowledge on these topics than I do.

**Comment by seanfarley** [comment]
Ah, I see. Your project sounds a bit like ATLAS, no? Where you're doing some parameter-like tuning to see which version works better.

I remember at PETSc we didn't recommend mpiuni with mumps due to some bugs; I can't remember exactly though. So, be careful about that.

Also, packages like MUMPS and metis / parmetis are problematic because they're "academic" codes: projects that are barely updated by today's standards and move at a glacial pace.

If you have no high priority for this, I'd prefer if you keep this in a branch for now so you can still experiment and we can discuss your results at a later time. If you have a higher priority come, then I guess let's discuss offline so I can get a better idea of the scope of your project.

**Comment by MarcusCalhoun-Lopez** [comment]
Thank you for the evaluation.

**Pull request closed without merging**
