### PR TITLE
toxiproxy: new port

### PR DESCRIPTION
**Pull request by amake**
#### Description

[toxiproxy](https://github.com/Shopify/toxiproxy) is a proxy that lets you simulate network problems.

###### Tested on
macOS 10.13.3 17D102
Xcode 9.2 9C40b 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Merged. That said, I'm not overly fond of the indentation — could you submit a PR to make it consistent? And thank you for your ongoing contributions to MacPorts!

**Comment by amake** [comment]
@pmetzger I assume you're talking about the `long_description`? My impression from having followed things for a while is that to avoid spurious commits it is preferred that a formatting-only change should wait until the next time the port needs updating for a more urgent reason. But if you really want it I will fix it.

Also I thought I'd point out that the current indenting is the default applied by emacs. Is there no way to enforce the desired indenting with more modeline magic?

**Comment by mf2k** [comment]
The indentation looks fine to me as is. Many portfiles do that in the `long_description` when there is a lot of text. 

My only comment is to add the new `size` variable in the `checksums`.

**Comment by pmetzger** [comment]
If the consensus is that it's fine then it's fine.

**Pull request merged**
