### PR TITLE
nhc98: update to 1.22, fix a broken build

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Finally fixed `nhc98`. Closes my own ticket: https://trac.macports.org/ticket/64996
(Notice that `i386` has not been tested, though it is supported and should build too.)

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6 PPC (10A190)
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
@evanmiller Could you please test if this builds for you?

**Comment by barracuda156** [comment]
Hmm, it looks like it has been built earlier on `x86_64` too: https://ports.macports.org/port/nhc98/stats/
Let me enable it then.

**Comment by barracuda156** [comment]
Reverted to 32-bit. FreeBSD has it for i386-only: https://cgit.freebsd.org/ports/tree/lang/nhc98/Makefile
Likely MP stats is just an error.

**Review by mascguy — APPROVED** [review]
While it's preferable to use a separate commit for general cleanup, given the number of other changes necessary anyway... I'm not going to ask you to split this.

And thanks as always for your contributions Sergey!

**Comment by barracuda156** [comment]
@mascguy Thank you! (Yeah, will do cleanup changes in separate commits. Started with recent PRs.)

**Comment by barracuda156** [comment]
@evanmiller If you will have time to try this, please update me!

**Comment by evanmiller** [comment]
Builds OK here on 10.4.11. Would be great to add the test targets to the Portfile.

**Comment by barracuda156** [comment]
@evanmiller Great, many thanks! I will try to remember adding them once I am back to my PPC machines (on a trip atm).

**Comment by barracuda156** [comment]
@mascguy @kencu What do you think, why Macports stats shows that someone built this port on 10.13 and 12? It might build for `x86_64`, but from what I understand in 32-bit mode. Here it failed on bots when I tried including `x86_64` arch.

P. S. Source code suggests that only `gcc` or otherwise Haskell compilers are supported (i.e. no `clang`). I did not try building it with `ghc` myself after fixing a build with `gcc`, but I will try it next month. As you perhaps remember, I have only `ghc` 7.6.3 on PPC at the moment though.

**Pull request merged**
