### PR TITLE
cmake: update release to 3.17.0 and devel to 20200323 (8638c49f)

### PR DESCRIPTION
**Pull request by michaelld**
Moving CMake from 3.16 to 3.17 ... shouldn't be an issue, but when I did the same for 3.15 to 3.16 I got a little pushback. So, putting in a PR for folks to test out; give y'all a week for feedback & testing, then unless there's a very good reason not to, I'll merge.

### CODE REVIEW

**Comment by michaelld** [comment]
Both devel and release build and test as expected for me on OSX 10.14 ... I'll also test on OSX 10.15, but I expect the same there.

**Comment by michaelld** [comment]
Feel free to tag others to test if/as you see fit.

**Comment by kencu** [comment]
good on 10.4 Tiger Intel:
```
$ port -v installed | grep cmake
  cmake @3.16.5_0 platform='darwin 8' archs='i386' date='2020-03-16T01:09:40-0700'
  cmake @3.17.0_0 (active) platform='darwin 8' archs='i386' date='2020-03-23T17:20:46-0700'
```

**Comment by kencu** [comment]
and good on 10.5 PPC (with libgcc7 7.4.0, at least):
```
$ port -v installed cmake
The following ports are currently installed:
  cmake @3.13.2_0 platform='darwin 9' archs='ppc' date='2018-12-18T23:04:28-0800'
  cmake @3.13.3_0 platform='darwin 9' archs='ppc' date='2019-01-14T23:25:06-0800'
  cmake @3.13.4_0 platform='darwin 9' archs='ppc' date='2019-02-03T23:05:37-0800'
  cmake @3.14.1_0 platform='darwin 9' archs='ppc' date='2019-03-30T16:49:25-0700'
  cmake @3.14.2_1 platform='darwin 9' archs='ppc' date='2019-04-20T13:26:33-0700'
  cmake @3.14.3_0 platform='darwin 9' archs='ppc' date='2019-04-23T19:56:32-0700'
  cmake @3.14.3_1 platform='darwin 9' archs='ppc' date='2019-05-12T11:25:31-0700'
  cmake @3.14.4_0 platform='darwin 9' archs='ppc' date='2019-05-24T23:24:02-0700'
  cmake @3.14.5_0 platform='darwin 9' archs='ppc' date='2019-06-29T19:56:21-0700'
  cmake @3.15.2_0 platform='darwin 9' archs='ppc' date='2019-08-16T21:56:30-0700'
  cmake @3.15.3_0 platform='darwin 9' archs='ppc' date='2019-09-23T00:56:08-0700'
  cmake @3.15.4_0 platform='darwin 9' archs='ppc' date='2019-10-05T23:40:42-0700'
  cmake @3.15.5_0 platform='darwin 9' archs='ppc' date='2019-12-04T20:44:15-0800'
  cmake @3.16.4_0 platform='darwin 9' archs='ppc' date='2020-03-10T20:05:57-0700'
  cmake @3.16.5_1 platform='darwin 9' archs='ppc' date='2020-03-20T15:13:17-0700'
  cmake @3.17.0_0 (active) platform='darwin 9' archs='ppc' date='2020-03-23T18:13:11-0700'
```

**Comment by eborisch** [comment]
If you're interested, you can start using the gitlab portgroup with `gitlab.instance https://gitlab.kitware.com`; otherwise it's very similar to the GitHub purtgroup. (`gitlab.setup cmake cmake 3.17.0 v` would take care of master_sites, live check, etc.)

**Comment by michaelld** [comment]
> If you're interested, you can start using the gitlab portgroup with `gitlab.instance https://gitlab.kitware.com`; otherwise it's very similar to the GitHub purtgroup. (`gitlab.setup cmake cmake 3.17.0 v` would take care of master_sites, live check, etc.)

Oh .... nice! Let me look into that! Thx for the pointer ... I didn't get a chance to review the GL PG, so totally forgot it's there.

**Comment by michaelld** [comment]
Thanks for the quick reviews. I'm going to merge as-is, and move to GitLab PG separately.

**Pull request merged**
