### PR TITLE
ocaml: needs runtime dep on clang-3.4 on < 10.7

### PR DESCRIPTION
**Pull request by kencu**

### CODE REVIEW

**Comment by pmetzger** [comment]
Does the `depends_run-append port:clang-3.4` also force that to be the compiler we build with? I'd like it if we forced MacOS < 10.7 to build with clang-3.4 as well as forcing that to be present at runtime. That way we won't ever get a mismatch.

**Comment by kencu** [comment]
No, but the current compiler selection logic leads to clang-3.4 on all those systems. To force that compiler to be the build compiler, we would do something like this:
```
        # compiler selection pulls in clang-3.4 on 10.6 and less
        # and this compiler is needed for this port to run once installed
        compiler.whitelist    macports-clang-3.4
        depends_run-append port:clang-3.4
```

That would force clang-3.4 on all those systems, unless (like me) you have that overridden in macports.conf with a better default_compiler.

**Comment by kencu** [comment]
There you go. It doesn't change the current build compiler (so therefore no revbump needed) but it does explicitly specify it.

**Comment by pmetzger** [comment]
Merged!

**Comment by pmetzger** [comment]
If we don't do the revbump, though, it won't force the package to run depend on the compiler, right? So we probably need that to force the rebuild on 10.6 systems, yes?

**Comment by kencu** [comment]
I think we should be OK.  The new portfile will pull in clang-3.4 as a runtime dep when ocaml is installed on the buildbot, so it should work without a revbump forcing everyone to rebuild ocaml.

**Comment by pmetzger** [comment]
So how long until Buildbot tells us if we did good or ill?

**Comment by pmetzger** [comment]
(And how can we check if all the downstream dependent ports that were broken built correctly? I can't find an easy way to query buildbot for the status of given ports...)

**Comment by kencu** [comment]
Two options. Force a build on the buildbot of one or more of the failed ports. That will confirm the fix works, and rebuild the failed builds.

Or bump a slight Portfile change to them all -- a comment or something -- all the ones that failed to build will try to build again.

**Pull request merged**
