### PR TITLE
dash: update to 0.5.12

### PR DESCRIPTION
**Pull request by herbygillot**
- switch to cgit portgroup, download from git.kernel.org
- remove patches which are no longer needed

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with ~`sudo port -vst install`~ `sudo port -d destroot`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by herbygillot** [comment]
Odd issue here.... CI is failing saying `aclocal: not found`, but it's included in the `automake` port present in `depends_build`....

**Comment by kencu** [comment]
setting autoconf.cmd resets the depends_build  deps, as I recall.

try moving the depends_build below the other autoconf stuff.

**Comment by herbygillot** [comment]
Thanks @kencu, I'll give that a shot.

**Comment by herbygillot** [comment]
Looks like that did it. Thanks @kencu.

**Comment by Synss** [comment]
LGTM. Thank you!

**Comment by herbygillot** [comment]
Thank you @Synss

**Pull request merged**
