### PR TITLE
hyfetch: support host info for PowerPC Macs and MacPorts on Linux/BSD

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

See commits

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
hyfetch

**Comment by TheRealKeto** [comment]
@barracuda156 Would you mind changing the `maintainers` field to match my Github handle? The field is case-sensitive (and I initially didn't know this) which [creates an issue that's become a remnant of when I started opening submissions.](https://github.com/macports/macports-ports/pull/22830#issuecomment-1970095174)

Otherwise, I'm fine with that changes and everything looks good!

**Comment by barracuda156** [comment]
@TheRealKeto Fixed

**Review by TheRealKeto — APPROVED** [review]
Thanks. Let's wait for the CI to finish before asking someone to merge. Thanks again!

**Pull request merged**
