### PR TITLE
prosody, lua-luasec: fix builds

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

`prosody` is broken on El Captain down: https://ports.macports.org/port/prosody/details

`lua-luasec` was broken by the recent update which threw away my patch -_- https://github.com/macports/macports-ports/pull/17988/commits/e07cc681e5a19213cdab5222b6f9489419041eac

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Clang fails on headers:
```
/usr/bin/clang -Os -fPIC -mmacosx-version-min=11.0 -I/opt/local/include   -c -o net.o net.c
  hashes.c:26:10: fatal error: 'openssl/crypto.h' file not found
  #include <openssl/crypto.h>
           ^~~~~~~~~~~~~~~~~~
  encodings.c:271:10: fatal error: 'unicode/usprep.h' file not found
  #include <unicode/usprep.h>
           ^~~~~~~~~~~~~~~~~~
  11 error generated.
   error generated.
  make[1]: *** [hashes.o] Error 1
  make[1]: *** Waiting for unfinished jobs....
  make[1]: *** [encodings.o] Error 1
```

**Comment by barracuda156** [comment]
@reneeotten @harens Could you please help with merging this?

**Comment by MarcusCalhoun-Lopez** [comment]
@barracuda156, thank you for looking into this.

lua-luasec:
Has this patch been submitted [upstream](https://github.com/brunoos/luasec)?
It seems like a good candidate.

prosody:
Why is `-std=c99` necessary?
Adding comments would help clarify for future modifiers.
Although the results would be the same, using `configure.cflags-append -std=c99` would be a better way to achieve the same results.

**Comment by barracuda156** [comment]
> lua-luasec: Has this patch been submitted [upstream](https://github.com/brunoos/luasec)? It seems like a good candidate.

Not yet, but I can do it.

> prosody: Why is `-std=c99` necessary?

It fails otherwise with gcc-4.2, with a typical error we have seen multiple times (`for` used outside of C99 something).

> Adding comments would help clarify for future modifiers. Although the results would be the same, using `configure.cflags-append -std=c99` would be a better way to achieve the same effect.

I have no objections to that, but it will be more code: configure.args already set cflags, why not just add there?

**Comment by MarcusCalhoun-Lopez** [comment]
> > lua-luasec: Has this patch been submitted [upstream](https://github.com/brunoos/luasec)? It seems like a good candidate.
> 
> Not yet, but I can do it.

Thank you.

> > prosody: Why is `-std=c99` necessary?
> 
> It fails otherwise with gcc-4.2, with a typical error we have seen multiple times (`for` used outside of C99 something).

Thank you for the clarification.

> > Adding comments would help clarify for future modifiers. Although the results would be the same, using `configure.cflags-append -std=c99` would be a better way to achieve the same effect.
> 
> I have no objections to that (provided it gonna work with lua), but it will be more code: configure.args already set cflags, why not just add there?

It is a minor issue.
However, there is already a line of code `configure.cflags-append  -fPIC`, so adding other cflags in other places makes it seems like `-std=c99` is somehow different than the other cflags.
Again, it is a minor issue.

**Comment by barracuda156** [comment]
> It is a minor issue. However, there is already a line of code `configure.cflags-append -fPIC`, so adding other cflags in other places makes it seems like `-std=c99` is somehow different than the other cflags. Again, it is a minor issue.

Ah, missed that. Then sure, I will move it there.

**Comment by barracuda156** [comment]
@reneeotten @harens Bump. Everything ready now :)

**Comment by MarcusCalhoun-Lopez** [comment]
Are there any objections to merging this PR?

**Comment by barracuda156** [comment]
> Are there any objections to merging this PR?

Should not be any, I believe.

@reneeotten @harens Could someone help, please?

**Pull request merged**
