### PR TITLE
nds2-client, nds2-client-*: update

### PR DESCRIPTION
**Pull request by chrstphrchvz**
nds2-client: update to 0.16.5,
nds2-client-swig: update to 0.16.7

nds2-client-java: Migrate to Java portgroup; specify LTS Java fallback; avoid dependency on `gnu-classpath` and fallback dependency on `kaffe`
See: https://trac.macports.org/ticket/60206

Use HTTPS URL for master_sites

###### Tested on

Untested.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
It looks like the `nds2-client-matlab` port could also be migrated to the Java portgroup so as to avoid depending on `gnu-classpath`. Would the `configure.javac` arguments from `nds2-client-java` be needed?

**Comment by chrstphrchvz** [comment]
I wonder if the CI build failures are due to them using Java 12+ to compile; there is an update available for `nds2-client-java` which addresses Java 12+ compatibility, so maybe the `nds2-client` and `nds2-client-*` ports should first be updated.

**Comment by chrstphrchvz** [comment]
@emaros @lpsinger I have also proposed updating `lscsoft-deps +nds2_swig` to drop the `gnu-classpath` dependency, since `nds2-client-java` and `nds2-client-matlab` would no longer be using it.

**Comment by chrstphrchvz** [comment]
> [Travis Build #13257](https://travis-ci.org/macports/macports-ports/builds/716574661) Errored.
> 

> Port nds2-client-java's dependencies **fail** on xcode9.4. [Log](https://paste.macports.org/ff0587952340)
> Port nds2-client-matlab's dependencies **fail** on xcode9.4. [Log](https://paste.macports.org/3f8574c35b00)
> Port nds2-client-octave's dependencies **fail** on xcode9.4. [Log](https://paste.macports.org/1b85d65ad56b)
> Port nds2-client-swig's dependencies **fail** on xcode9.4. [Log](https://paste.macports.org/6d39a9e05eee)
> Port py27-nds2-client's dependencies **fail** on xcode9.4. [Log](https://paste.macports.org/c4a3800dbe55)
> Port py35-nds2-client's dependencies **fail** on xcode9.4. [Log](https://paste.macports.org/37c5376e6aca)
> Port py36-nds2-client's dependencies **fail** on xcode9.4. [Log](https://paste.macports.org/a6e3bcedc405)
> Port py37-nds2-client's dependencies **fail** on xcode9.4. [Log](https://paste.macports.org/6cdaef6174c2)
> Port py38-nds2-client's dependencies **fail** on xcode9.4. [Log](https://paste.macports.org/744b6eaf1c79)
> Port nds2-client's dependencies **fail** on xcode9.4. [Log](https://paste.macports.org/c024f8d02f82)


This error once again:
```
Error: Portfile is from the future - check date and time of your system
```

**Comment by chrstphrchvz** [comment]
@emaros The `nds2-client-swig` ports fail to build:

```
nds2-client-swig-0.16.7/common/module/nds_channel.i:19: Error: Syntax error in input(1).
```

I'm not familiar with CMake or SWIG, so I'm not sure what is wrong that is causing this error.

The relevant portion of nds_channel.i (line numbers added):
```
14    %shared_ptr( channel );
15    %shared_ptr( std::vector< std::shared_ptr< epoch > > );
16
17    %nds_doc_class_seperator
18
19    %nds_doc_class_begin(channel)
20    %nds_doc_brief("Represents a LIGO data channel")
21    %nds_doc_details("A channel encasulates the meta data of LIGO data.  It has a name and parameters.")
22    %nds_doc_class_end
23    class channel
24    {
```

**Comment by chrstphrchvz** [comment]
I am inclined to drop any changes superseded by #8930 so that this PR only updates `lscsoft-deps` (to be merged after #8930).

**Comment by lpsinger** [comment]
I'm sorry, I don't have time to maintain this particular package anymore. I'm no longer a regular user of NDS2, so I can't do realistic testing of the binaries. Would you like to take over maintaining it?

**Comment by chrstphrchvz** [comment]
I am not familiar enough with this port to maintain it; I was merely hunting down `kaffe` port dependents, and tried seeing if the port could be easily updated simultaneously.

**Comment by lpsinger** [comment]
Perhaps @emaros could review this patch and then take over maintainership?

**Comment by emaros** [comment]
Please use #8930 as a base for work as it has already addressed the issue of the default swig being 4.x by using swig 3 explicitly. Many of the changes listed here have been moved forward to #8930. 



Again, please drop this merge request.

**Comment by mf2k** [comment]
Done

**Pull request closed without merging**
