### PR TITLE
Python38 devel

### PR DESCRIPTION
**Pull request by Themanwithoutaplan**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix
- [x] update

###### Tested on

macOS 10.14.6 18G103
Xcode 11.0 11A420a

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [ ] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [ x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
@Themanwithoutaplan  please rebase with current ```master``` to resolve the conflicts

**Comment by Themanwithoutaplan** [comment]
I hope I've done it correctly this time.

**Comment by Themanwithoutaplan** [comment]
Hm, that's not working for me in the shell. Sorry, too inexperience with git. I'll try again at the weekend.

**Comment by reneeotten** [comment]
> Hm, that's not working for me in the shell. Sorry, too inexperience with git. I'll try again at the weekend.

Can you elaborate on what is not working. Of course, I am assuming that the upstream MacPorts repository is called ```upstream```... What is the output of ```git remote -v```  for you when you're in the directory that contains the Portfile you changed?

**Comment by pmetzger** [comment]
I just did a squash-and-merge of @Themanwithoutaplan's changes. It would be good if this got done better next time but for now I thought I'd just fix it.

**Comment by Themanwithoutaplan** [comment]
Thanks and I do apologise for the mess. I'm trying to learn how to do this without deleting the fork or branch all the time. I very rarely use git so, as with these all things, it's all difficult until you've done a few times. I think I understand things now: pull from upstream and rebase the branch. Hopefully things will be better with my next PR.

**Pull request merged**
