### PR TITLE
py-tensorflow-macos: Update to version 2.13.0; py-tensorflow-metal: Update to version 1.0.1

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.4.1 22F770820d arm64
Xcode 14.3.1 14E300c

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by essandess** [comment]
I believe that this PR is ready to merge and that the CI errors are timeouts.

**Comment by mascguy** [comment]
Steve, it looks like there are some issues that need to be addressed first, based on the errors from `port lint` (visible in the "Files Changed" tab):

```
port lint py311-tensorflow-macos:
Error: Unknown dependency: py311-absl
Error: Unknown dependency: py311-astunparse
Error: Unknown dependency: py311-grpcio
Error: Unknown dependency: py311-keras
Error: Unknown dependency: py311-keras_preprocessing
Error: Unknown dependency: py311-opt_einsum
Error: Unknown dependency: py311-tensorflow_estimator
Error: Unknown dependency: py311-tensorboard
Error: conflicts references unknown port: py311-tensorflow
Error: conflicts references unknown port: py311-tensorflow1
Error: conflicts references unknown port: py311-tensorflow-addons

port lint py38-tensorflow-macos:
Error: conflicts references unknown port: py38-tensorflow

port lint py310-tensorflow-macos:
Error: conflicts references unknown port: py310-tensorflow1
Error: conflicts references unknown port: py310-tensorflow-addons
```

**Comment by essandess** [comment]
This PR depends upon:
* #19665
* #19672

**Comment by essandess** [comment]
> Steve, it looks like there are some issues that need to be addressed first, based on the errors from `port lint` (visible in the "Files Changed" tab):

I believe that this PR is ready to merge. The other errors are either ports that depend on this PR, or inconsequential conflicts with the broken `py-tensorflow` ports.

**Comment by pmetzger** [comment]
Steve, unless you can help us out here, none of these are likely to move forward. Please at least tell us what merge requests have to be done in what order so that each will pass the CI.

**Comment by pmetzger** [comment]
Hi @essandess! It's been over a month and we haven't heard from you on this. Feel free to request the pull again when you are ready and able to help us get it through.

**Pull request closed without merging**
