### PR TITLE
py-pyqtgraph: pin to latest supported version for Python < 3.7

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
- pin to latest supported version for Python < 3.7 (shouldn't require an increase of `epoch` as it presumably didn't build due to the `python_requires=">=3.7"` in the `setup.py`)
- conform to modeline
- use `https` for homepage
- set Qt5 as default variant for all Python versions

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.15.7 19H1417 x86_64
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Review by michaelld — APPROVED** [review]
LGTM; thx!

**Comment by michaelld** [comment]
Let's let CI finish & then assuming it passes then merge

**Comment by michaelld** [comment]
2/3 of CI failed ; trying it again

**Comment by reneeotten** [comment]
> 2/3 of CI failed ; trying it again

these are probably just timeouts - right?

**Comment by michaelld** [comment]
not clear if just timeouts or what

**Comment by reneeotten** [comment]
> not clear if just timeouts or what

to me it seems like it's a CI issue and not with the actual install of the port. But please do test this yourself locally and merge whenever you're okay with it.

**Comment by michaelld** [comment]
Agreed, Merging

**Pull request merged**
