### PR TITLE
py-google-api, py-oauth2client, py-uritemplate: Update to uritemplate 3.0.0, add python 3.7 support

### PR DESCRIPTION
**Pull request by mrdomino**
#### Description

Adds "37" to the list of supported python versions for google-api and oauth2client. Also uses the latest uritemplate from pypi -- the [prior repo](https://github.com/uri-templates/uritemplate-py) instructs people to use the new one instead. AFAICT only py-google-api and py-oauth2client depend on py-uritemplate.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.4 18E226
Xcode 10.2.1 10E1001

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mrdomino** [comment]
The CI failure is a bit inscrutable to me... is this an issue with py-uritemplate having no maintainer, or is something else going on?

**Comment by reneeotten** [comment]
> The CI failure is a bit inscrutable to me... is this an issue with py-uritemplate having no maintainer, or is something else going on?

It appears the ```py-setuptools``` dependency is missing in ```py-uritemplate```. 

```
DEBUG: system:  cd "/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_python_py-uritemplate/py27-uritemplate/work/uritemplate-3.0.0" && /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 setup.py --no-user-cfg build 
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
ImportError: No module named setuptools
```

Please insert ```depends_build-append port:py${python.version}-setuptools``` at line 36 in that Portfile to declare this dependency.

**Comment by mrdomino** [comment]
Done, thank you.

**Comment by reneeotten** [comment]
thank you for your contribution @mrdomino !

**Pull request merged**
