### PR TITLE
buildbot: update to 2.6.0

### PR DESCRIPTION
**Pull request by rajdeepbharati**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mojca** [comment]
Could you perhaps update #6195 instead? Or close that one and switch to python 3.8 here? Maybe you can just cherry-pick (and optionally squash) commits with some luck?

**Comment by mojca** [comment]
I actually wanted to suggest to combine the two and merge them together to avoid having to rebuild stuff twice. But now that you merged the other commit, you need to manually resolve the conflict anyway. Please at least set the revision back to 0.

**Comment by rajdeepbharati** [comment]
I rebased it and set revision as 1. Is that ok?

**Comment by rajdeepbharati** [comment]
Ok, got it. BTW, why hadn't you changed revision in the py-buildbot-** ports in this [commit](https://github.com/macports/macports-ports/commit/a1a79194de884fd7a56415a09cc82379ba99c784) ?

**Comment by mojca** [comment]
That's because the python modules actually install different ports. The new ports are named `py38-buildbot`, for example, while the old ones were called `py37-buildbot`, which is considered a different port.

**Comment by rajdeepbharati** [comment]
Okay, thanks.

**Pull request merged**
