### PR TITLE
qca-qt5: fix build on macOS 10.7-10.11

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description

Fix builds for 10.7 through 10.11.

Fixes: https://trac.macports.org/ticket/63980
Fixes: https://trac.macports.org/ticket/63983

###### Tested on
Testing on older macOS releases - at a minimum, 10.7 and 10.9 - currently in-progress. The PR description will be updated, once everything has been validated.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by RJVB** [comment]
LGTM. We might consider rolling this new patchfile and the one for `std::unique_ptr` into a single file, maybe (`patch-missing-headers.diff`)? My guess would be that the number of missing headers will only increase because upstream clearly develops on much more recent systems than the ones we support. And possibly only tests with GCC which might be doing all kinds of includes as a courtesy (and despite what the C++ standard seems to suggest).

**Comment by chrstphrchvz** [comment]
Combining the patches sounds fine, though I do think they should be submitted upstream, as it is improper to not be using features from `<cstdlib>`, `<memory>`, etc. without include the headers.

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
Rene, are you interested in merging this as-is, or would you prefer to have additional changes made?

**Comment by RJVB** [comment]
You could extend the fix down to OS X 10.7 (right?) and include the updated patchfile I just attached to ticket 63983. Other than that I see nothing else to change.

**Comment by mascguy** [comment]
Folks, I added a 2nd commit, with the latest patch from [63983 - qca-qt5: error: no member named 'toSecsSinceEpoch' in 'QDateTime'](https://trac.macports.org/ticket/63983). The author is set to Rene for the subsequent change, and the commit message will close that ticket.

**Comment by mascguy** [comment]
p.s. I'm also planning to test this on a few older macOS releases - 10.7 and 10.9, at a minimum - before we merge.

**Comment by mascguy** [comment]
Folks, I can confirm that `qca-qt5` builds successfully on both 10.7 and 10.9, with all of these changes. (I also installed `qca` as well, just for completeness.)

While it's not practical to try and test this across every macOS release, are there any other scenarios we should test against?

**Comment by RJVB** [comment]
>While it's not practical to try and test this across every macOS release, are there any other scenarios we should test against?

Is there any interest in getting 10.6 or even lower supported as well? In other words, which OS versions where port:qca-qt5* were in use are now left out? The easiest way to re-support them would be to bump them back down to v2.2.1

**Comment by mascguy** [comment]
> Is there any interest in getting 10.6 or even lower supported as well? In other words, which OS versions where port:qca-qt5* were in use are now left out? The easiest way to re-support them would be to bump them back down to v2.2.1

If you folks are willing to support 10.6 as well, I'll happily help validate it!

I'm wondering if we should do that as a separate PR though, so we can release these fixes? Thoughts?

**Comment by RJVB** [comment]
>I'm wondering if we should do that as a separate PR though, so we can release these fixes? Thoughts?

Yes that would be better because doing this would take time I can't spend on it right now (whether I manage to add the support to v2.3.4 or downgrade the port for the earlier OS versions)

**Comment by mascguy** [comment]
> Yes that would be better because doing this would take time I can't spend on it right now (whether I manage to add the support to v2.3.4 or downgrade the port for the earlier OS versions)

Sounds great, I'll merge this PR then. And let me know when we're ready to add support for 10.6, and I'll help test.

And thanks again for all the work on this folks, this is great for our users!

**Comment by chrstphrchvz** [comment]
Upstream pull request for patch-missing-headers.diff opened: https://invent.kde.org/libraries/qca/-/merge_requests/65

**Comment by RJVB** [comment]
>Upstream pull request for patch-missing-headers.diff opened: https://invent.kde.org/libraries/qca/-/merge_requests/65

Well, you beat me to it! And 't was merged already, without as much as a wisecrack that maybe Xcode 8.2.1 couldn't be used anyway because from a system not supported by the minimum required Qt version. I expected more vigilance from the KDE guys ;)

**Comment by RJVB** [comment]
ALERT ALERT ...

A syntax error slipped into the Qt5 support patch: the first hunk for qca-ossl.cpp introduces a `##else` which somehow got past all of us.

It causes a build failure port:qca-qt5-ossl so it can be fixed by a simple commit, without any revbumping. Can you take care of that please, Christopher?

**Comment by chrstphrchvz** [comment]
> Can you take care of that please, Christopher?

Which Christopher—me or @mascguy (the one with commit rights)? :^)

See #13072

**Comment by chrstphrchvz** [comment]
`qca-qt5-ossl` **did** fail on the CI builds, so maybe we should have caught it earlier.

**Comment by RJVB** [comment]
>Which Christopher—me or @mascguy (the one with commit rights)? :^)

I'll admit I was a bit confused myself but I meant the latter ;)

Little point in asking another "mere mortal" maintainer, right...

**Pull request merged**
