### PR TITLE
transmission@2.9.2 : fix missing libcrypto.0.9.8

### PR DESCRIPTION
**Pull request by kencu**
hardlinks against libcrypto.0.9.8 which does not exist on all systems
changes to link against libcrypto
this patch will not be needed in transmission @2.9.3

closes: https://trac.macports.org/ticket/52749
closes: https://trac.macports.org/ticket/53743

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.12
Xcode 8.3

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
I don't know if you want this patch, or just want to wait out the fix coming out downstream eventually...

**Comment by kencu** [comment]
hmm. Looks like this port requires xcode 7 or later to bulid as well.

**Comment by kurthindenburg** [comment]
I was hoping they'd release .3 soon(er) - if it fixes a build issue, I have no objection to any patch

**Comment by kencu** [comment]
NB - I noticed the Xcode 6 build failure on Travis, so I popped an update into that as well while I was doing this PR that you can optionally consider if you want.

**Comment by kencu** [comment]
I think this error works out pretty good, on systems that can't build or run transmission:
```
Error: transmission 2.92 requires Xcode 7.0 or greater to build and macOS 10.9 to run.
Error: Consider installing transmission-x11 instead.
Error: Failed to fetch transmission: incompatible OS X version
```

**Pull request merged**
