### PR TITLE
gdal: enable AAIGrid driver

### PR DESCRIPTION
**Pull request by fhanzer**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.7 19H1323 x86_64
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by Veence** [comment]
Does this need an additional dependency?

**Comment by fhanzer** [comment]
No, no additional dependencies are required. The driver always used to be enabled, I only recently discovered it is now missing (I assume since 419217e19b9456bb453c8e8f53d1ab4f721074c7).

**Comment by Veence** [comment]
I probably overlooked that driver, I apologise for that. I’m going to commit your change immediately. Please wait for it to propagate and recompile.

**Comment by fhanzer** [comment]
Great, thank you!

**Pull request merged**
