### PR TITLE
cmake: update to v3.29.0

### PR DESCRIPTION
**Pull request by kencu**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

several systems, not Tiger

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

There are dozens and dozens of cmake tickets. I will go through them all individually later and close all the ones that are no longer relevant. Most likely all the cmake and cmake-devel tickets that exist can be closed by this, except for anything involving Tiger which may still need tweaking.

I don't know everything (anything) about how the gitlab livechecks are supposed to work. Is this set right for the cmake port?

### CODE REVIEW

**Comment by kencu** [comment]
There is one hiccup to be fixed still.

cmake-gui and cmake-docs both are trying to install the same file, so activating one if the other is active will fail.

```
Error: Failed to activate cmake-docs: Image error: /opt/local/share/doc/cmake/cmcppdap/NOTICE is being used by the active cmake-gui port.  Please deactivate this port first, or use 'port -f activate cmake-docs' to force the activation.
    while executing
"throw registry::image-error $msg"
    ("foreach" body line 47)
    invoked from within
"foreach file $imagefiles {
                set srcfile "${extracted_dir}${file}"

                # To be able to install links, we test if we can lst..."
    invoked from within
"registry::write {
            foreach file $imagefiles {
                set srcfile "${extracted_dir}${file}"

                # To be able to instal..."
Error: See /opt/local/var/macports/logs/_opt_macports-ports_devel_cmake/cmake-docs/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port cmake failed
```
That file contains this:
```
'cppdap' is a C++11 library implementation of the Debug Adapter Protocol.
Version as of 2023-01-06
Copyright Google LLC

This product includes software developed at Google.
```
so I suppose it should belong to cmake or cmake-gui, and as cmake doesn't install it (apparently) we'll leave it with cmake-gui to install. I will delete it from the cmake-docs installation.

**Comment by kencu** [comment]
there were other files in that doc directory as well, so just let cmake-gui install them

**Comment by kencu** [comment]
as expected, livecheck doesn't work.
```
% port livecheck
Error: cannot check if cmake was updated (regex didn't match)
```

anyone know the magic incantation for it?

```
DEBUG: Executing org.macports.main (cmake)
DEBUG: livecheck phase started at Tue Mar 26 09:07:27 PDT 2024
DEBUG: Executing org.macports.livecheck (cmake)
DEBUG: Port (livecheck) version is v3.29.0
DEBUG: Fetching https://gitlab.kitware.com/cmake/cmake/-/tags?format=atom
DEBUG: Using CURL options --append-http-header {Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8} --enable-compression
DEBUG: The regex is "tags/([0-9.]+)</id>"
Error: cannot check if cmake was updated (regex didn't match)
```

**Comment by Dave-Allured** [comment]
@kencu, I recently updated another gitlab port (gjs).  For livecheck I just let the `gitlab` portgroup handle it.  I added the PG and deleted all left-over old livecheck commands.  That seems to be working fine.  Now I admit, that was on a **gnome** instance, which might behave differently than **kitware**.

What happens if you just remove `livecheck.type`?

**Comment by Dave-Allured** [comment]
Hmmm.  Here is a **kitware** port with an apparently working livecheck, that does **not** use the gitlab portgroup.  Perhaps copy this livecheck?  I do not know how this would interact with the gitlab PG, which you are using.  Also there is no guarantee that they are using the same URL structure for both `cmake` and `vtk`.
https://github.com/macports/macports-ports/blob/master/graphics/vtk/Portfile

**Pull request merged**
