### PR TITLE
hdf5: 1.12.2 and related bumps.

### PR DESCRIPTION
**Pull request by eborisch**
Maintainer update.

HDF5 1.12.2 and all ports advertising dependency on hdf5.

[Release notes](https://www.hdfgroup.org/2022/04/release-of-hdf5-1-12-2-newsletter-183/).

Tagging listed maintainers:

@BSeppke
@MarcusCalhoun-Lopez
@Schamschula
@Veence
@egull
@emaros
@galexv
@jcupitt
@jjstickel
@johndesanto
@jswhit
@lpsinger
@mf2k
@mtorrent
@neurodroid
@petrrr
@piyushrpt
@ra1nb0w
@ryanvolz
@stromnov
@tenomoto

### CODE REVIEW

**Review by Schamschula — APPROVED** [review]
Neither armadillo, nor mathgl actually needed to be revision bumped.

**Comment by eborisch** [comment]
> Neither armadillo, nor mathgl actually needed to be revision bumped.

Ok. I grab everything that lists HDF5 as a dep; anything that links against it needs a bump due to how HDF checks and complains about version mid-matches.

**Review by mf2k — APPROVED** [review]
Looks good for ncpp.

**Comment by remkos** [comment]
Looks good for cdo, nco, netcdf

**Pull request merged**
