### PR TITLE
wxMaxima: Various little fixes

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

Here are a bunch of little fixes for wxMaxima; see the commit messages for details.

###### Type(s)

- [X] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.6 17G12034
Xcode 9.4.1 9F2000

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
@ryandesign: Thanks for your fixes - I appreciate it!

**Comment by ryandesign** [comment]
> Shouldn't the regexp strip the Version- prefix used in wxMaxima? This is project specific and I don't see how github would do this automatically.

You specified it when you called `github.setup`.

**Comment by MSoegtropIMC** [comment]
> > Shouldn't the regexp strip the Version- prefix used in wxMaxima? This is project specific and I don't see how github would do this automatically.
> 
> You specified it when you called `github.setup`.

I see, thanks!

**Comment by MSoegtropIMC** [comment]
@ryandesin: I approved each individual commit - thanks for fixing all these little details which for sure sometime or for someone cause problems. I also learned quite a bit from your changes.

I am unsure what the procedure is now. Since I don't have write rights on the repo I cannot merge. Is there something I should do now to trigger the merge?

**Comment by ryandesign** [comment]
Just leaving a comment saying you approve is good enough. I'll merge it, or someone else would've seen your approval and merged it.

**Pull request merged**
