### PR TITLE
py-uvicorn: Update to version 0.23.2; Add Python 311

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
@reneeotten Do you have any idea why this failed? He made minimal changes.

**Comment by reneeotten** [comment]
it looks like it needs "hatch" as the python.pep517_backend" with this new version.

**Comment by pmetzger** [comment]
@essandess Can you please push a version you have tested locally that is known to work and that passes the CI? Otherwise I think we're going to have to close this and similar pull requests.

**Comment by pmetzger** [comment]
@essandess BTW, please note that you can run the CI on your own fork of the repository.

**Comment by pmetzger** [comment]
Hi @essandess! It's been over a month and we haven't heard from you on this and the pull request doesn't pass the CI and you've neither explained nor fixed that. I'm going to close this for now. Feel free to request the pull again if it passes the CI or there's a good reason it doesn't.

**Pull request closed without merging**
