### PR TITLE
folly and friends: update to 2024.01.08.00

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

I will add the rest of the group here. Let us see if `folly` builds fine first.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.2.1
Xcode 15.2

macOS 10.6
Xcode 3.2

(For obvious reasons, `edencommon` and `watchman` were not tested on 10.6, but only on 14.2.1.)

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
`watchman` fails on CI on this:
```
  Traceback (most recent call last):
    File "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_sysutils_watchman/watchman/work/watchman-2023.11.13.00/watchman/python/setup.py", line 12, in <module>
      from setuptools import Extension, setup
  ModuleNotFoundError: No module named 'setuptools'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_sysutils_watchman/watchman/work/watchman-2023.11.13.00/watchman/python/setup.py", line 14, in <module>
      from distutils.core import Extension, setup
  ModuleNotFoundError: No module named 'distutils'
```
I cannot reproduce the error:
```
warning: `watchmanctl` (bin "watchmanctl") generated 3 warnings (run `cargo fix --bin "watchmanctl"` to apply 3 suggestions)
    Finished release [optimized] target(s) in 0.11s
[1/2] Install the project...
-- Install configuration: "MacPorts"
running install
/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running build
running build_py
running build_ext
running build_scripts
running install_lib
creating /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework
creating /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions
creating /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12
creating /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib
creating /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12
creating /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages
creating /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywatchman
copying build/lib.macosx-14.0-arm64-cpython-312/pywatchman/pybser.py -> /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywatchman
copying build/lib.macosx-14.0-arm64-cpython-312/pywatchman/bser.cpython-312-darwin.so -> /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywatchman
copying build/lib.macosx-14.0-arm64-cpython-312/pywatchman/encoding.py -> /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywatchman
copying build/lib.macosx-14.0-arm64-cpython-312/pywatchman/__init__.py -> /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywatchman
copying build/lib.macosx-14.0-arm64-cpython-312/pywatchman/capabilities.py -> /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywatchman
copying build/lib.macosx-14.0-arm64-cpython-312/pywatchman/windows.py -> /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywatchman
copying build/lib.macosx-14.0-arm64-cpython-312/pywatchman/load.py -> /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywatchman
byte-compiling /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywatchman/pybser.py to pybser.cpython-312.pyc
byte-compiling /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywatchman/encoding.py to encoding.cpython-312.pyc
byte-compiling /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywatchman/__init__.py to __init__.cpython-312.pyc
byte-compiling /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywatchman/capabilities.py to capabilities.cpython-312.pyc
byte-compiling /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywatchman/windows.py to windows.cpython-312.pyc
byte-compiling /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywatchman/load.py to load.cpython-312.pyc
running install_egg_info
running egg_info
creating /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/watchman-2023.11.13.00/watchman/python/pywatchman.egg-info
writing /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/watchman-2023.11.13.00/watchman/python/pywatchman.egg-info/PKG-INFO
writing dependency_links to /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/watchman-2023.11.13.00/watchman/python/pywatchman.egg-info/dependency_links.txt
writing top-level names to /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/watchman-2023.11.13.00/watchman/python/pywatchman.egg-info/top_level.txt
writing manifest file '/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/watchman-2023.11.13.00/watchman/python/pywatchman.egg-info/SOURCES.txt'
reading manifest file '/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/watchman-2023.11.13.00/watchman/python/pywatchman.egg-info/SOURCES.txt'
writing manifest file '/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/watchman-2023.11.13.00/watchman/python/pywatchman.egg-info/SOURCES.txt'
Copying /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/watchman-2023.11.13.00/watchman/python/pywatchman.egg-info to /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywatchman-1.4.1-py3.12.egg-info
running install_scripts
creating /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/bin
copying build/scripts-3.12/watchman-wait -> /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/bin
copying build/scripts-3.12/watchman-replicate-subscription -> /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/bin
copying build/scripts-3.12/watchman-make -> /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/bin
changing mode of /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/bin/watchman-wait to 755
changing mode of /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/bin/watchman-replicate-subscription to 755
changing mode of /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.12/bin/watchman-make to 755
-- Installing: /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/bin/watchman
-- Installing: /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/bin/watchman-diag
-- Installing: /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/bin/watchman-make
-- Installing: /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/bin/watchman-replicate-subscription
-- Installing: /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/bin/watchman-wait
-- Installing: /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot/opt/local/bin/watchmanctl
--->  Installing watchman @2023.11.13.00_1
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_sysutils_watchman/watchman/work/destroot" && /usr/bin/tar -cvf - . | /opt/local/bin/lbzip2 -c9 > /opt/local/var/macports/software/watchman/watchman-2023.11.13.00_1.darwin_23.arm64.tbz2
```

**Comment by barracuda156** [comment]
@danchr Could you please help with `watchman`? Everything else is done.
`watchman` in fact builds locally for me on Sonoma with a mere revbump, but on CI fails with some python-related errors.

**Comment by pmetzger** [comment]
Is this ready to merge?

**Comment by barracuda156** [comment]
@pmetzger From my side everything is done.

**Comment by danchr** [comment]
> @pmetzger From my side everything is done.

That's an interesting definition of “done” — you knowingly broke `watchman`…

**Comment by barracuda156** [comment]
@danchr Sorry, if it was misleading. I tagged you here above, asking about `watchman`, and I said “from my side”, since for my ports everything has been done.

Locally on Sonoma the existing version of `watchman` built fine for me with new `folly` and all on Sonoma. I am not sure why CI failed for it; I quote the error above.

**Comment by barracuda156** [comment]
```
svacchanda@43-95 ~ % port -v installed folly
The following ports are currently installed:
  folly @2024.01.08.00_0 (active) requested_variants='' platform='darwin 23' archs='arm64' date='2024-01-12T06:57:08+0800'
svacchanda@43-95 ~ % port -v installed edencommon
The following ports are currently installed:
  edencommon @2024.01.08.00_0 (active) requested_variants='' platform='darwin 23' archs='arm64' date='2024-01-12T13:12:04+0800'
svacchanda@43-95 ~ % port -v installed watchman
The following ports are currently installed:
  watchman @2023.11.13.00_1 (active) requested_variants='' platform='darwin 23' archs='arm64' date='2024-01-12T13:20:44+0800'
```

**Comment by danchr** [comment]
```
$ port -v installed watchman folly
The following ports are currently installed:
  folly @2024.01.08.00_0 (active) requested_variants='' platform='darwin 21' archs='x86_64' date='2024-01-13T11:22:26+0100'
  watchman @2023.11.13.00_0 (active) requested_variants='' platform='darwin 21' archs='x86_64' date='2023-11-26T22:03:28+0100'
$ watchman
zsh: segmentation fault  watchman
$ lldb watchman
(lldb) target create "watchman"
Current executable set to 'watchman' (x86_64).
(lldb) run
Process 14108 launched: '/opt/local/bin/watchman' (x86_64)
Process 14108 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000000000000
error: memory read failed for 0x0
Target 0: (watchman) stopped.
```

I'll look into getting `watchman` updated, but please don't do this again, okay?

**Comment by danchr** [comment]
Sadly, I don't have more time to spend on this today. Anyway, if it both builds _and_ works — merely executing `watchman` is a good enough test — please consider pushing your changes.

The Python-related breakage you saw is caused by the default changing to Python 3.12; the likely reason you aren't seeing it yourself is that you have `py312-setuptools` installed.

> …since for my ports everything has been done.

To finish off, I just want to object to this one: In general, upgrades shouldn't break other ports, and the `Portfile` for `folly` has a comment that clearly states that you should also update dependents. So you're not “done” updating `folly` until you've done so.

**Comment by barracuda156** [comment]
@danchr Let me try to fix it now. Thank you for advice re setuptools.

**Comment by pmetzger** [comment]
@barracuda156 I was asking if it was okay to commit. You gave an answer that seemed to indicate it was. Please do not do that again unless you are *certain* that it is okay to commit something. If you say "it's okay by me" or something like that, I'm going to assume that you don't mean "it's okay by me _but it is going to harm other people_."

**Comment by barracuda156** [comment]
@pmetzger Yes, you are right.

**Comment by pmetzger** [comment]
Looks like more than just a revbump. Let's continue the conversation there.

**Pull request merged**
