### PR TITLE
grass: update to version 8.3.2

### PR DESCRIPTION
**Pull request by nilason**
#### Description

Update `grass` to version 8.3.2.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by nilason** [comment]
This fails on `Error: Unknown dependency: py312-wxpython-4.0` for `grass-gui` caused by untested commit:
https://github.com/macports/macports-ports/commit/99ec1766d582d85c51b613c8cfe35b2e61986562.

@i0ntempest Please do not commit such changes without at least CI checks.

**Comment by i0ntempest** [comment]
My bad for missing grass-gui but I can just add py312 subport to that port and you can then rebase to use it. Python 3.13 is getting close to release and it makes no sense to stick with 3.11.

**Comment by nilason** [comment]
> My bad for missing grass-gui but I can just add py312 subport to that port and you can then rebase to use it. Python 3.13 is getting close to release and it makes no sense to stick with 3.11.

I've tried with wxPython for 3.12, but it isn't really stable with present version (see https://github.com/wxWidgets/Phoenix/issues/2479). This is one of the reasons I've been hesitant going py312 with some GIS ports.  However, I see there is work going on,  brining it here with https://github.com/macports/macports-ports/pull/23065.

**Comment by pmetzger** [comment]
Should this be committed now?

**Comment by nilason** [comment]
> Should this be committed now?

Yes, there were some unexpected issues with Python 3.12, which now are sorted out. Ready to merge.

**Pull request merged**
