### PR TITLE
nomaintainer freedesktop.org ports: use HTTPS URLs

### PR DESCRIPTION
**Pull request by chrstphrchvz**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
@chrstphrchvz -- can you confirm for me that you actually tried each  one of these and they work?

**Comment by chrstphrchvz** [comment]
I thought I checked that all of these were redirecting to HTTPS, but I am mistaken. After checking again, tango.freedesktop.org doesn't seem to: trying to connect with HTTPS shows it has an invalid certificate, and isn't loading the same resources. So I have dropped the changes to tango.freedesktop.org.

**Comment by dbevans** [comment]
Similarly, the Tango icon theme and library can be found here: https://gitlab.freedesktop.org/tango

**Comment by kencu** [comment]
you can do tango separately when you get time.

**Pull request merged**
