### PR TITLE
gcc/libgcc ports: Update gcc8 to stable 8.2.0 release and update devel ports to gcc9 snapshot 

### PR DESCRIPTION
**Pull request by cjones051073**
Updates to the various gcc<X> and libgcc<X> ports to update gcc8 to 8.2 stable release
and to add new gcc9 port based on a current beta snapshot. libgcc-devel consequently
updated to now be based of the same gcc9 snapshsot.

```
libgcc:       Updated to be a standalone port, that picks the correct gcc primary runtime.
gcc8:         Update to gcc 8.2.0
libgcc8:      New port providing gcc 8.2.0 runtime
libgcc7:      New port based gcc 7.3.0. Contains older API library versions updated in libgcc.
gcc7:         Update to depend on libgcc7.
libgcc-devel: Update to gcc snapshot 9-20180722.
gcc9:         New port based on gcc snapshot 9-20180722.
    
compilers-1.0.tcl : Updated to adapt to the new libgcc runtims as above
languages-1.0.tcl   and to add gcc8 as a compiler option.
```

Closes: https://trac.macports.org/ticket/56521

###### Tested libgcc-devel/gcc9 on

macOS 10.13.6 17G65
Xcode 9.4.1 9F2000

macOS 10.7.5 11G63
Xcode 4.6.3 4H1503 

macOS 10.6.8 10K549
Xcode 3.2.6 DevToolsSupport-1806.0 10M2518 

###### Tested libgcc/gcc8 on

macOS 10.13.6 17G65
Xcode 9.4.1 9F2000

macOS 10.12.6 16G1510
Xcode 8.3.3 8E3004b 

macOS 10.11.6 15G22010
Xcode 7.3.1 7D1014 

macOS 10.10.5 14F2511
Xcode 7.0.1 7A1001 

macOS 10.9.5 13F1911
Xcode 6.2 6C131e 

macOS 10.8.5 12F2560
Xcode 5.1.1 5B1008 

macOS 10.7.5 11G63
Xcode 4.6.3 4H1503 

macOS 10.6.8 10K549
Xcode 3.2.6 DevToolsSupport-1806.0 10M2518 

- [x] enhancement
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by MarcusCalhoun-Lopez** [comment]
I think it would be best to hold off on this.
There is a [upstream patch](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81033) that is supposed to allow libgcc to build even with cctools.
That would certainly simplify the Portfile logic.

Although I have not thoroughly tested it, I have been able to build libgcc 9 with cctools.
I can post what I have so far (perhaps on the [ticket](https://trac.macports.org/ticket/56521)) or in a different pull request.

**Comment by cjones051073** [comment]
Interesting thinks. I have been sitting on this for a while and submitted it as much to get feedback on what others had been up to as much as anything else.

The logic in this PR to switch the behaviour on Xcode version is pretty easy to rip out, and once that is done what is left would be more or less just a basic version bump. So if as you suggest gcc upstream releases something at some point in the future that fixes the underlying issue all the better. The question is how long is this going to be, and if there is interest from users in having access to gcc8+ (albeit only on the newer macOS releases) in the meantime.

Either way, this PR has most of the basic version bump donkey work done so I think can act as a basis.

**Comment by cjones051073** [comment]
Just reading the bug report, another option might be to manually apply the patch mentioned towards the end of that report to see if that helps. I think I will give that a go tomorrow...

**Comment by MarcusCalhoun-Lopez** [comment]
Just to clarify, I was only able to build libgcc 9 with cctools **after** applying the patch at the end of the report.

**Comment by cjones051073** [comment]
Exactly. Let me see if I can apply the same patch to gcc8 and gcc9, and if that helps I could then remove the Xcode version flipping logic...

make WIP whilst I work on this...

**Comment by ryandesign** [comment]
> The gcc8 and gcc9 based ports, due to issue with the compiler tool kit, are only supported (at the moment) on Xcode 9 or newer systems. For the issues surrounding this see
> 
> https://trac.macports.org/ticket/56521

Are you certain about this? I thought the cause of that ticket was using the cctools port's `as` which was too old—older than Xcode's, on newer systems. I assumed that on older systems, where cctools' `as` is as new as or newer than Xcode's, it would build fine. Did you try to build the new gcc8 and gcc9 on older systems, and it didn't work?

> Whereas on Xcode < 9 systems the gcc8 and gcc9 based ports are (currently) not supported and libgcc is still based on gcc 7.3.0 as before.

This is bound to cause problems. The pregenerated portindex that we distribute to users via rsync does not vary based on Xcode version. It only varies based on `os.major`, `os.arch`, and some code was written to make it vary based on `configure.cxx_stdlib` but that hasn't been committed yet. The portindexes for all systems are generated on our build server, by faking different values of those variables (see [mprsyncup](https://github.com/macports/macports-infrastructure/blob/master/jobs/mprsyncup)). We don't fake any other variables, so the value of `xcodeversion` that the portindex process sees—for all OS versions—will be whatever's installed on the build server, which happens to run OS X 10.11 El Capitan with Xcode 8.2.1 but that's not a detail that's supposed to matter. Ports should not change things that get stored in the index (name, variants, portdir, description, homepage, epoch, platforms, name, license, maintainers, long_description, dependencies, categories, version, revision) based on variables other than the three mentioned above (or, if there is a very good reason why that should be allowed, then code needs to be added to MacPorts base and mprsyncup to handle it).

Are you certain you handled the dylibs correctly? You may have, I didn't look at what you did very closely, but I remember that when I last looked into this update, I was distressed by the number of places that the list of dylibs and their versions was repeated, and that the port had no safeguards to ensure that the maintainer notices and makes the necessary adjustments when a library's version number increases. I began to wonder if the current state of the ports was correct—for example, the libgcc45 port provides libobjc-gnu.2.dylib, while the libgcc @7.3.0 port provides libobjc-gnu.4.dylib. What happened to libobjc-gnu.3.dylib? What version of gcc used that, and shouldn't we have created a libgccXY port for it?

**Comment by ryandesign** [comment]
> There is a upstream patch that is supposed to allow libgcc to build even with cctools.

I had not kept up with the fact that the upstream bug I had been following was duped to another report which I hadn't read before. I would favor using the patch, and offering the same gcc versions to every OS, if the developer says the patch is correct. (Sounds like he's still testing it at the moment.)

**Comment by cjones051073** [comment]
> Are you certain about this? I thought the cause of that ticket was using the cctools port's as which was too old—older than Xcode's, on newer systems. I assumed that on older systems, where cctools' as is as new as or newer than Xcode's, it would build fine. Did you try to build the new gcc8 and gcc9 on older systems, and it didn't work?

Yes I did. It failed on older systems with the same errors as in https://trac.macports.org/ticket/56521

The issue is not if the version of the tools provided by cctools matches that provided by Xcode, but basically just the age of the tools. The tools in the pre Xcode 9 versions where/are too old and generated the errors as in the ticket above.

**Comment by cjones051073** [comment]
>Are you certain you handled the dylibs correctly? You may have, I didn't look at what you did very closely, but I remember that when I last looked into this update, I was distressed by the number of places that the list of dylibs and their versions was repeated, and that the port had no safeguards to ensure that the maintainer notices and makes the necessary adjustments when a library's version number increases. I began to wonder if the current state of the ports was correct—for example, the libgcc45 port provides libobjc-gnu.2.dylib, while the libgcc @7.3.0 port provides libobjc-gnu.4.dylib. What happened to libobjc-gnu.3.dylib? What version of gcc used that, and shouldn't we have created a libgccXY port for it?

100% certain ? no, but I think I understand the logic and adapted to it.

I agree about your comment regarding repeated lists in a number of places. That is still there, but I have infact fixed a few minor bugs in this area. There where a few binaries in the gcc7 ports where the version listed in the port file did not actually match that created. I have fixed these, but I do agree there is probably a better way to handle these dylib lists...

**Comment by cjones051073** [comment]
> I had not kept up with the fact that the upstream bug I had been following was duped to another report which I hadn't read before. I would favor using the patch, and offering the same gcc versions to every OS, if the developer says the patch is correct. (Sounds like he's still testing it at the moment.)

100% agree. Let me see how it works.

based on your previous comment anyway, my current logic that changes then ports on the Xcode version cannot be deployed, so either I need to get the patch working or this update cannot be applied. Lets focus on that.

**Comment by kencu** [comment]
> The issue is not if the version of the tools provided by cctools matches that provided by Xcode, but basically just the age of the tools

The way I read the referenced gcc bug report, the older assembler had a strictness to handling atoms that the newer assembler was more lax on. "The cctools assembler is strict about the atom definitions, the LLVM-based one is apparently more relaxed." <https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81033#c37>.

So the older assember is not at fault. And it appears gcc is fixing the issue properly.

**Comment by cjones051073** [comment]
> The way I read the referenced gcc bug report, the older assembler had a strictness to handling atoms that the newer assembler was more lax on. "The cctools assembler is strict about the atom definitions, the LLVM-based one is apparently more relaxed." https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81033#c37.
> So the older assember is not at fault. And it appears gcc is fixing the issue properly.

Yes, quite right. I did exactly describe the issue. My mistake.

In any case I am currently trying to get the patch included and to then build the port with that. Currently building on macOS10.13 looks good, but I need to try on some older systems... I only have a couple machine with a number of VMs (which I can only fire up one at a time for resource reasons) so it will take me a little time to test things properly on a number of systems.

**Comment by cjones051073** [comment]
... and, needless to say building gcc takes a while, so testing this is a bit long winded...

**Comment by cjones051073** [comment]
please note I will be using this branch to sync the ports between numerous different VMs and machines. So please do not pay attention to the commits etc. until further notice. I will squash everything back to a single commit once I am done testing....

**Comment by cjones051073** [comment]
@MarcusCalhoun-Lopez many thanks to point me towards that patch, it has done the job. Now the gcc/libgcc 8.2.0 ports build fine all the way back to OSX 10.6 (the oldest I can test). 

I have updated this PR to remove the Xcode version switching, so now it simply updates `gcc`/`libgcc` to 8.2.0 and adds `gcc9`.

One test I cannot do is test on `Darwin 9 PPC`, which looking at

http://packages.macports.org/libgcc

Is the oldest currently supported platform. Does anyone have one of these machines and is willing to test this PR on it ?

**Comment by kencu** [comment]
> Does anyone have one of these machines and is willing to test this PR on it ?

I won't be able to get to it for a few weeks, at least. But don't let that stop progress. If it builds all the way to 10.6.8, that's great. Either we can fix gcc8+ to work on PPC, or if we can't then PPC stays with gcc6 / gcc7, which will be sufficient to compile anything we need to compile for many years to come.

**Comment by cjones051073** [comment]
I agree, however there is a specific issue here in the way the the various ports are (currently) set up here.

`libgcc` is designed to provide a number of libraries, which then are used by *all* the various `gcc<X>` ports. For instance it currently has

```
  /opt/local/lib/libgcc/libasan.5.dylib
  /opt/local/lib/libgcc/libatomic.1.dylib
  /opt/local/lib/libgcc/libgcc_ext.10.4.dylib
  /opt/local/lib/libgcc/libgcc_ext.10.5.dylib
  /opt/local/lib/libgcc/libgcc_s.1.dylib
  /opt/local/lib/libgcc/libgfortran.5.dylib
  /opt/local/lib/libgcc/libgomp.1.dylib
  /opt/local/lib/libgcc/libitm.1.dylib
  /opt/local/lib/libgcc/libobjc-gnu.4.dylib
  /opt/local/lib/libgcc/libquadmath.0.dylib
  /opt/local/lib/libgcc/libssp.0.dylib
  /opt/local/lib/libgcc/libstdc++.6.dylib
  /opt/local/lib/libgcc/libubsan.1.dylib
```

The `libgcc6` and `libgcc7` ports then *only* install older versions of the above, as required by those particular compiler toolkits. e.g.

```
 > port contents libgcc7
Port libgcc7 contains:
  /opt/local/lib/libgcc/libasan.4.dylib
  /opt/local/lib/libgcc/libcilkrts.5.dylib
  /opt/local/lib/libgcc/libgfortran.4.dylib
  /opt/local/lib/libgcc/libubsan.0.dylib
```

```
> port contents libgcc6
Port libgcc6 contains:
  /opt/local/lib/libgcc/libgfortran.3.dylib
```

what this means is `gcc7` and `gcc6` both depend on `libgcc`, and thus to install and use them you need to be able to install the *newer* `libgcc` version. 

This is why wanted to test `Darwin 9 PPC`. If it turns out `gcc8` does not work there, we either need to fix it or come up with a way to allow `libgcc` to use a different gcc version on different platforms. I have some ideas on perhaps how this could be done (that would avoid @ryandesign concerns above) but it would be simpler if it just worked OK ;)

**Comment by ryandesign** [comment]
> This is why wanted to test Darwin 9 PPC

Unfortunately it doesn't build; here's the bug report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85669

**Comment by cjones051073** [comment]
@ryandesign Thanks for the test and the link to the upstream bug. 

Shame it does not work. I guess we should keep an eye on that bug report and see how it progresses.

That said, I think there is a fundamental flaw in the way the `libgccX` are currently set up, which is as it stands the older `libgccX` depend on newer versions. So `libgcc6` depends on `libgcc7` which in term requires `libgccX`. The reason for this is we want each to share the same runtime as much as possible, and for each the newest gcc build to provide what it can. However it relies on the assumption we can always build newer releases on older platforms, and this is an assumption that will, eventually fall over. A time will come, perhaps now with gcc8, where older platforms will fall off the supported list.

I have an idea how to change things to fix this, that basically will end up with allowing for some (older) systems older `libgcc` versions to install the primary runtime. Maybe the bug above will get fixed sometime, but going forward I feel sometime we will need something like this, so I think I will look into it. I don't think it will be that complicated.

**Comment by kencu** [comment]
Interesting that it seems to fail on something related to the math functions again. There is a longstanding issue with the math functions and gcc on 10.5, related to some missing definitions in `math.h`. When I get back to the farm, I'll try it on 10.5 Intel and see if it comes up with the same errors. It's possible that this failure to build might not be related to PPC at all...

**Comment by cjones051073** [comment]
I have just pushed an update that implements the possibility that some (older) systems might not always support all gcc versions. The way it works is

 - `libgcc` is now a port on its own, no longer a sub-port of a particular `gccX` version. It doesn't in itself install anything much (just a README) but its main job is to make a decision as to which `libgccX` version to depend on. For Darwin > 9 its now `libgcc8` whereas for 9 and older `libgcc7`.

- `libgcc7` has a little bit of logic, mirroring that in `libgcc` to decide if it is the primary gcc runtime, which means it should install the complete list of dylibs and includes, or if it is a secondary one and thus only installs the older  dylibs updated in the newer `libgcc8` runtime.

- `gcc8`/`libgcc8` declares itself incompatible with Darwin 9 and older.

The requirement `Darwin > 9` can easily be changed if required. The only requirement is whatever is used must be consistent in the three places above.

**Comment by cjones051073** [comment]
So, what do people think ?

I have run a number of tests of the last few days, checking up various upgrade paths. If a user has the various gcc ports installed, as per `master`, then this update now goes smoothly (I had to add a few deactivate hacks to gcc7/8 to handle the change in the `libgcc` port). Maybe I have missed something, but I think this PR is ready to be merged now...

**Comment by cjones051073** [comment]
I should also add I have tested the logic that fallbacks to `gcc7` on older systems (by just temporarily changing the test to a new Darwin version I have access to) and am confident this also works OK.

**Comment by kencu** [comment]
I think you've put a lot of work in.
I agree it's inevitable that libgcc will need to be related to something less than the latest/greatest gcc version on older systems at some point, and the time could well be now.
I think it's a complicated set of changes, and it will not be possible to forsee completely all the fallout.

With that in mind, if it works on your tests, IMHO we are not likely to do a whole lot better without diving in and and then mopping up.

**Comment by pmetzger** [comment]
> So, what do people think ?

I suspect most of us have no basis for an opinion. (I have none.)

**Comment by cjones051073** [comment]
I guess then my question is does anyone have any objection to my merging this ?

I'll give it a few days for comments, but I don't get any objections then I will merge it.

**Comment by cjones051073** [comment]
OK, no comments so will commit.

**Pull request merged**
