### PR TITLE
neovim*: combine -devel as subport of neovim

### PR DESCRIPTION
**Pull request by casr**
#### Description

These two ports don't really differ all that much that it seems easier to combine them. What do you think?

###### Type(s)

- [x] enhancement

###### Tested on

macOS 12.6.7 21G651 arm64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
@raimue Thoughts?

**Review by raimue — APPROVED** [review]
Looks good to me.
@l2dy @judaew Any preference?

**Comment by pmetzger** [comment]
Merged.

**Comment by casr** [comment]
Thanks!

**Pull request merged**
