### PR TITLE
lilypond-devel: update to v2.19.84

### PR DESCRIPTION
**Pull request by Jahrme**
#### Description

LilyPond version 2.19.84 has been released. Changes to LilyPond have greatly simplified its dependencies, for example, Clang can now be used for compiling (previously `gcc` was necessary). Because of these dependency changes, I was able to tune the dependency lists which will make installation faster and smaller (for reference, the mpkg size went from 215.7MB to 188.8MB).

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.3 19D76
Xcode 11.3.1 11C504

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by nerdling** [comment]
There's a lot of stylistic whitespace change in this PR. For future PRs, please avoid.

So far so good on other changes.

**Comment by Jahrme** [comment]
@nerdling, I can revert the whitespace changes if you'd like; given how much shorter the Portfile was at the end I felt it was a good time to re-align the columns, but I also recognize that it creates a larger diff.

**Comment by mf2k** [comment]
We prefer to have whitespace changes in a separate commit. It is fine to have that in a PR.

**Comment by lemzwerg** [comment]
I disagree to this patch.  In particular, it completely removes the `+mactex` variant for no good reason (I use this for testing LilyPond on my Mac) – and this isn't mentioned at all in the commit message!

@Jahrme, please have a look at my pull request (https://github.com/macports/macports-ports/pull/6379, which I posted without seeing your try, sorry).  Maybe you can improve it further and merge your changed into it (or vice versa)?

**Comment by lemzwerg** [comment]
Any progress?

**Comment by nerdling** [comment]
I've merged the other PR which handles the upgrade. This PR will need to be reworked from that, notably the mactex variant being dropped is an issue.

**Pull request closed without merging**
