### PR TITLE
MacVim/vim: add ruby30 variant

### PR DESCRIPTION
**Pull request by sstallion**
#### Description

This PR adds a `ruby30` variant to the Portfile. This is especially useful for users that need Ruby scripting support (eg. Command-T) with version parity to the latest MacVim release.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.4 21F79 arm64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mascguy — APPROVED** [review]
LGTM. @raimue ?

**Comment by raimue** [comment]
Thank you for the patch! :+1: 

However, as you already mention this is also of interest for users of MacVim for which we also have a port. I try to keep vim and MacVim as close as possible as they share the same configuration files. Can we please get the same change for a +ruby30 variant into `editors/MacVim/Portfile`?

**Comment by mascguy** [comment]
> Thank you for the patch! 👍
> 
> However, as you already mention this is also of interest for users of MacVim for which we also have a port. I try to keep vim and MacVim as close as possible as they share the same configuration files. Can we please get the same change for a +ruby30 variant into `editors/MacVim/Portfile`?

Rainer, would you like to merge this as-is, and have a 2nd PR created? Or would you prefer that MacVim be updated too, as part of this PR?

**Comment by raimue** [comment]
I think it would be better to do this within this PR. Then users can switch to `+ruby30` for both and rely upon it in their scripts.

**Comment by sstallion** [comment]
> I think it would be better to do this within this PR. Then users can switch to `+ruby30` for both and rely upon it in their scripts.

Will do! At the moment MacVim seems to be broken on the latest version of Monterey (I haven't been able to get a successful build on amd64 since upgrading from Big Sur and I haven't attempted on M1 yet).

**Comment by raimue** [comment]
The build failure on arm64 seems unrelated to this change. It might be due to the `XCODEFLAGS` being set in the Portfile, but I am not sure. In any case, as +ruby30 is not in the default variants, the CI does not help that much to test it.

**Comment by raimue** [comment]
Thanks again for the additional work on MacVim! :+1:

**Pull request merged**
