### PR TITLE
Add Python version 3.6 for more ports

### PR DESCRIPTION
**Pull request by cdeil**
This pull request adds Python version 3.6  to 18 more ports.

@g5pw - Please review.

### CODE REVIEW

**Comment by cdeil** [comment]
Anyone available to review and merge this PR?

**Comment by tobypeterson** [comment]
Sure, looks ok to me. Guess nobody else is looking at pull requests. I've been delinquent

**Comment by cdeil** [comment]
I tested all the packages added here with Python 3.6 a bit.

Here's the issues I found:

pylint doesn't work with Python 3.6 yet: https://github.com/PyCQA/pylint/issues/1241
Sorry! My suggestion would be to leave as-is in Macports (because very few people presumably are on Python 3.6 yet) and update pylint to the new release when it comes out (a week or two?).

pep8 isn't available with Python 3.6 yet:
https://github.com/macports/macports-ports/blob/master/python/py-pep8/Portfile#L32
Again, sorry, not sure how I missed that.
I'll file a PR to add the Python 3.6 version for `py-pep8` (and possibly it's dependencies) shortly.

**Comment by tobypeterson** [comment]
Sounds good. I merged this request because it looked fairly innocuous; I didn't test anything. Any additional issues can be dealt with in future PRs.

**Pull request merged**
