### PR TITLE
py-pip: disable vendoring of packages on non-deprecated versions

### PR DESCRIPTION
**Pull request by danchr**
#### Description

This is similar to, and inspired by, what Ubuntu and Debian do. I restricted the change to actually supported versions. Pip patches some of its dependencies, but only one of these seems relevant:

https://github.com/pypa/pip/blob/master/tools/automation/vendoring/patches/appdirs.patch

I'm not sure whether we should apply that one.

See: https://pip.pypa.io/en/stable/development/vendoring-policy/#debundling

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by dgilman** [comment]
LGTM

**Comment by ryandesign** [comment]
What's the motivation for doing this? What does it improve? What are the risks?

**Comment by kencu** [comment]
so what's up here?

sitting now for months, waiting for what?

**Comment by danchr** [comment]
I think other packagers mostly did this to keep the footprint low. It doesn't really add all that much for MacPorts…

**Pull request closed without merging**
