### PR TITLE
fix azure pipeline

### PR DESCRIPTION
**Pull request by catap**
#### Description

The fix is simple: let's remove expired root CA from `/etc/ssl/cert.pem` which is used by `curl` which is shipped with macOS

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
@catap this is not the (main) problem, see my previous commit and revert of this file. Until there is a version of MacPorts generated on Azure this will not work.

**Comment by catap** [comment]
@reneeotten curl from macOS 10.14 had been broken since let’s encrypt certificate is expired. And this commit is the way to fix it.

**Comment by catap** [comment]
@reneeotten I guess I got that you mean. Right now uploading from azure pipeline from https://github.com/macports/macports-ci-files doesn't work.

Until it is fixed, azure can't be fixed because it stuck on macports before 2.7.1

**Comment by jmroot** [comment]
Someone could manually build a 10.14 binary, either in the format currently expected by CI, or as a .pkg with the necessary postflight change. Not a great long-term solution of course.

**Comment by catap** [comment]
@jmroot / @reneeotten any thoughts?

**Comment by jmroot** [comment]
> Anyway, I feel that the right long term solution is using official `.pkg`.

The official pkg is not suitable because it wants to do a `port selfupdate` in the postflight script, which wastes a lot of precious CI time.  It would be possible to build a variant pkg with a customised postflight that doesn't do this.

**Comment by reneeotten** [comment]
I guess that once GitHub actions has the `macos-11` image available we can just test the latest three macOS versions there and retire Azure pipelines? That would just "solve" the current problem ;)

**Comment by catap** [comment]
@reneeotten to be honest retire azure seems as very good option.

**Comment by jmroot** [comment]
> @reneeotten to be honest retire azure seems as very good option.

If it breaks again we probably will. But for now, it seems to be working.

**Pull request closed without merging**
