### PR TITLE
qt5*: update version 5.12.4->5.12.5

### PR DESCRIPTION
**Pull request by rex4539**
#### Description

qt5*: update version 5.12.4->5.12.5

###### Type(s)

- [X] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.15 19A573a
Xcode 11.1 11A1027

###### Verification
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] checked your Portfile with `port lint`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
@MarcusCalhoun-Lopez this is your bailiwick, yes?

**Comment by mojca** [comment]
Do any dependencies need a revbump?

**Comment by rex4539** [comment]
Ping.

**Comment by MarcusCalhoun-Lopez** [comment]
Sorry for the delay in responding.
I have been working on upgrading Qt to 5.13, so my current system is a little out of sorts.
If you wouldn't mind waiting until the weekend, I should get a chance to test the changes and merge the pull request.

**Comment by rex4539** [comment]
@MarcusCalhoun-Lopez Did you have a chance to test this?

**Comment by mojca** [comment]
This probably needs some cleanup of commit history?

**Comment by rex4539** [comment]
Some weird git mixup. Fixed.

**Pull request merged**
