### PR TITLE
get_iplayer: Update to v3.0.0 resolves #54100

### PR DESCRIPTION
**Pull request by Themanwithoutaplan**
###### Description

https://trac.macports.org/ticket/54100

###### Tested on
macOS 10.x
Xcode 8.x

###### Verification 
Have you
- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by dliessi** [comment]
I tested the new version and it seems to work as expected.

`port lint` gives a warning about Perl variant conflicting with non-existing variant: this is a left-over from when there were many Perl versions (also the perl5 port itself gives this warning).
(@mojca How should we treat this?)

The commit message needs to be reworked, though: commit messages should conform to the [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages).
Given that you also opened a Trac ticket that we need to close, an appropriate commit message is the following:
```
get_iplayer: update to 3.0.0

Closes https://trac.macports.org/ticket/54100
```
Note in particular that the first line should mention the name of the affected port(s) and that Trac tickets need to be referenced with their full url, since #XXXXX now references to GitHub issues and pull requests.

Please use `git commit --amend` or `git rebase -i` (e.g., `git rebase -i origin/master`) to fix the commit message.
(I would do it myself, but I do not have commit rights.)

**Comment by Themanwithoutaplan** [comment]
Amend the commit message as suggested.

**Comment by mojca** [comment]
Please mention the name of the port in the ticket.

**Comment by Themanwithoutaplan** [comment]
The port is already in the ticket both in the title and the port.

**Comment by mojca** [comment]
I meant: next time. I fixed the title already.

What about removing these lines altogether (keep just `perl5.branches 5.24`)?

~~~tcl
perl5.require_variant   yes
perl5.conflict_variants yes
perl5.create_variants   ${perl5.branches}
~~~~~

There's no need for variants right now anyway.

I would say that there is a bug in `perl5-1.0.tcl`, but the code was written by @jmroot, maybe he has more clue.

**Comment by dliessi** [comment]
@mojca Removing the variants is ok for me.

Anyway, the current state of the pull request has three commits, one of which is a merge commit (which we don't want), and none of them has the correct commit message.
This really needs to be one single commit.

Given that I need to remove the Perl variant and I also want to add my GitHub handle to the maintainer line, please keep this pull request on hold: I will open a new pull request later tonight with the Perl and GitHub handle changes in one commit and the original commit by @Themanwithoutaplan (with the changed commit message, but retaining his authorship) rebased on top of that.

**Comment by mojca** [comment]
No, please don't open a new request. Just fix this one.

**Comment by mojca** [comment]
Oh, wait. I guess you can't for the lack of commit rights?

I wanted to say that you can just add a few additional commits and someone from the team can merge them, but then I realised that you cannot do that either.

I wonder if @Themanwithoutaplan can give you permissions to commit to this branch.

Sorry, I don't know what's the best solution in this solution. Anything that works, I guess.

**Comment by mojca** [comment]
@dliessi: since you are the maintainer and if you say you agree with the changes (minus weird commit history) and just want to add your github handle & remove the perl lines, I guess I can fix this as well.

**Comment by dliessi** [comment]
> I guess you can't for the lack of commit rights?

That's indeed the problem.

It is OK for me if you can take care of this.
Thanks in advance.

(I guess it's time for me to apply for commit rights...)

**Comment by Themanwithoutaplan** [comment]
Am I correct in assuming that there's nothing more for me to do? I'm not much of a git expert but did what was requested. I'll try and be better in future PRs.

**Comment by mojca** [comment]
@Themanwithoutaplan: you could have played with git rebase a bit further, but now I force pushed to your branch. In the future it makes sense to use `git rebase master` in your branch rather than merging.

@dliessi: please double-check whether this is what you want.

**Comment by dliessi** [comment]
@mojca The changes are ok for me. Thanks for taking care of this. 

@Themanwithoutaplan Thanks for your contribution.

**Pull request merged**
