### PR TITLE
glib2: update to 2.62.5

### PR DESCRIPTION
**Pull request by kencu**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G9323 x86_64
Xcode 11.3.1 11C504

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
This a complete redo of glib2. There is at present a push on for glib2 to be updated as a number of ports, in particular now gimp2, cannot be updated until glib2 is updated.

NB: It is highly likely there are still issues to be resolved. 

There are two open tickets about issues with glib2-devel, upon which this PR is based, that are unresolved at present:

glib2-devel @2.62.5 +universal is missing some i386 bits:
https://trac.macports.org/ticket/62700

glib2-devel @2.62.5: does not build on 10.4 Tiger i386:
https://trac.macports.org/ticket/63344

There was a suggestion that perhaps multiple simultaneous versions of glib2 could be installed, but I believe this is impossible as glib2 is part of a core ecosystem of gnome ports, and I believe they all must share a single version of glib2 so as to pass compatible structures between components.

**Comment by kencu** [comment]
It is not clear to me if the many dependents of glib2 will need to be revbumped with this PR. In my testing of glib2-devel, that was not needed.

glibmm will need to be updated to glibmm-devel once this is felt to be acceptable.

Whether all the many dependents of glib2 still build properly against this newer version of glib2 is a large project that we need to undertake.

**Comment by nerdling** [comment]
I spotted no linking issues either. Checked against these:
```
atk
cairo
gdk-pixbuf2
gobject-introspection
gtk3
gtksourceview3
gts
harfbuzz
json-glib
libproxy
libpsl
libquvi
librsvg
pango
pioneers
poppler
pspp-devel
quvi
shared-mime-info
vala
```

**Comment by kencu** [comment]
[glib2-265-test-Leopard-i386.txt](https://github.com/macports/macports-ports/files/6951116/glib2-265-test-Leopard-i386.txt)
[glib2-265-test-Mojave.txt](https://github.com/macports/macports-ports/files/6951119/glib2-265-test-Mojave.txt)

**Comment by kencu** [comment]
I might do a bit of minor style cleanup, but this is the final version for committing -- unless there are issues or objections, I will commit this tomorrow.

**Comment by kencu** [comment]
I think the Tiger/Leopard patch needs an ```autoreleasepool``` added:

```
--- stderr ---
2021-08-08 09:44:22.587 testglib[16899] *** _NSAutoreleaseNoPool(): Object 0x603f80 of class NSCFArray autoreleased with no pool in place - just leaking
2021-08-08 09:44:22.588 testglib[16899] *** _NSAutoreleaseNoPool(): Object 0x6052b0 of class NSCFString autoreleased with no pool in place - just leaking
2021-08-08 09:44:22.588 testglib[16899] *** _NSAutoreleaseNoPool(): Object 0x606250 of class NSCFString autoreleased with no pool in place - just leaking
2021-08-08 09:44:22.588 testglib[16899] *** _NSAutoreleaseNoPool(): Object 0x6065a0 of class NSPathStore2 autoreleased with no pool in place - just leaking
2021-08-08 09:44:22.588 testglib[16899] *** _NSAutoreleaseNoPool(): Object 0x6065f0 of class NSPathStore2 autoreleased with no pool in place - just leaking
2021-08-08 09:44:22.588 testglib[16899] *** _NSAutoreleaseNoPool(): Object 0x606830 of class NSCFArray autoreleased with no pool in place - just leaking
2021-08-08 09:44:22.588 testglib[16899] *** _NSAutoreleaseNoPool(): Object 0x606870 of class NSCFData autoreleased with no pool in place - just leaking
2021-08-08 09:44:22.588 testglib[16899] *** _NSAutoreleaseNoPool(): Object 0x606c60 of class NSCFArray autoreleased with no pool in place - just leaking
2021-08-08 09:44:22.588 testglib[16899] *** _NSAutoreleaseNoPool(): Object 0x606c90 of class NSCFString autoreleased with no pool in place - just leaking
```

**Comment by kencu** [comment]
Yes indeed, it looks like there is something in newer glib2 that will need tweaking for qemu to work the way it should. If it still applies to 2.70 and no MacOS systems are working properly, then I guess upstream should probably be fixing this (surprising they haven't already). Perhaps that would be a good place to report this issue, and see what they come up with to fix it?

**Pull request merged**
