### PR TITLE
go: add herbygillot as maintainer

### PR DESCRIPTION
**Pull request by herbygillot**

### CODE REVIEW

**Comment by jasperweiss** [comment]
Off-topic: @herbygillot out of curiosity, how do you manage to maintain over 160 ports? Do you have some automation going on?

**Comment by herbygillot** [comment]
> Off-topic: @herbygillot out of curiosity, how do you manage to maintain over 160 ports? Do you have some automation going on?

:) Actually getting some sort of automation set up has been on my list for a while.  That said, I'm pretty sure there are maintainers managing way more ports than that.

**Comment by kencu** [comment]
@herbygillot --- please update for the conflicts and then push this when you get 10 seconds -- thanks

**Comment by herbygillot** [comment]
> @herbygillot --- please update for the conflicts and then push this when you get 10 seconds -- thanks

OK, updated

**Pull request merged**
