### PR TITLE
gmm: update to 5.4.2

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Just an update.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
@barracuda156 this PR fails to build ; please do complete the PR checklist locally before submitting a PR. It would be good if you could look into this (perhaps let's try and wrap up the collections of open PRs you have currently before submitting new ones?)

**Comment by barracuda156** [comment]
> @barracuda156 this PR fails to build ; please do complete the PR checklist locally before submitting a PR. It would be good if you could look into this (perhaps let's try and wrap up the collections of open PRs you have currently before submitting new ones?)

I will try fixing it soon. Sure.

**Comment by barracuda156** [comment]
@reneeotten After adding config.arg `--disable-dependency-tracking` it builds, but fails at destroot:
```
.././install-sh -c -d '/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_gmm/gmm/work/destroot/opt/local/include'
  /bin/sh: .././install-sh: Permission denied
  make[2]: *** [install-nobase_includeHEADERS] Error 1
  make[2]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_gmm/gmm/work/gmm-5.4.2/include'
  make[1]: *** [install-am] Error 2
  make[1]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_gmm/gmm/work/gmm-5.4.2/include'
  make: *** [install-recursive] Error 1
  make: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_gmm/gmm/work/gmm-5.4.2'
  Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_gmm/gmm/work/gmm-5.4.2" && /usr/bin/make -w install DESTDIR=/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_gmm/gmm/work/destroot 
  Exit code: 2
  Error: Failed to destroot gmm: command execution failed
  DEBUG: Error code: CHILDSTATUS 3821 2
```
Any suggestions, what may be going wrong?

**Comment by reneeotten** [comment]
looks like a permissions problem:```/bin/sh: .././install-sh: Permission denied``` - does this work for you locally?

**Comment by barracuda156** [comment]
> looks like a permissions problem:```/bin/sh: .././install-sh: Permission denied``` - does this work for you locally?

Yes, of course. The port built normally with no tricks from the beginning.

**Comment by barracuda156** [comment]
@mascguy This I will sort out today a bit later.

**Comment by barracuda156** [comment]
@mascguy Fixed :)

**Comment by mascguy** [comment]
Sergey, `gmm` is a header-only component. So dependent `gmsh` will need to be rev-bumped, to pick up the changes.

(You can ignore the other dependent - `koffice2-devel` - as that's broken across-the-board. So don't waste your time on trying to fix it.)

**Comment by barracuda156** [comment]
@mascguy Thank you, will do it.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
