### PR TITLE
direnv: simplify port, use golang-1.0 portgroup

### PR DESCRIPTION
**Pull request by amake**
#### Description

Simplify the direnv port and use the golang-1.0 portgroup.

The patches for the makefiles were simply not necessary; instead the desired effect can be achieved by supplying an appropriate value for `DESTDIR`.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14 18A391
Xcode 10.0 10A255

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by michaelld** [comment]
Cool! I love simplifications! Let me verify locally & get back.

**Comment by pmetzger** [comment]
@michaelld Any progress?

**Comment by michaelld** [comment]
Got busy with work. I've been hold off of updating direnv so that this PR doesn't go stale. Will try to get to this over the weekend.

**Comment by pmetzger** [comment]
@michaelld Given that this builds, would it be okay to merge this and then check later?

**Comment by michaelld** [comment]
Yes that's fine. I'll do it now.

**Comment by michaelld** [comment]
Sorry for not getting to this PR; work has been hell with deadlines this past while! It's not normally this intense!

**Pull request merged**
