### PR TITLE
speex: update to version 1.2.1

### PR DESCRIPTION
**Pull request by sbooth**
#### Description

Update speex to version 1.2.1

This also removes speexDSP as a subport and uses a separate speexdsp port.

Depends on #15448 

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.5 21G72 x86_64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
@sbooth Install phase fails for me:
```
Making install in src
make[1]: Entering directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/speex-1.2.1/src'
make[2]: Entering directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/speex-1.2.1/src'
 /opt/local/bin/gmkdir -p '/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/destroot/opt/local/bin'
  /bin/sh ../libtool   --mode=install /usr/bin/install -c speexenc speexdec '/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/destroot/opt/local/bin'
libtool: warning: '../libspeex/libspeex.la' has not been installed in '/opt/local/lib'
libtool: install: /usr/bin/install -c .libs/speexenc /opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/destroot/opt/local/bin/speexenc
libtool: warning: '../libspeex/libspeex.la' has not been installed in '/opt/local/lib'
libtool: install: /usr/bin/install -c .libs/speexdec /opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/destroot/opt/local/bin/speexdec
 /opt/local/bin/gmkdir -p '/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/destroot/opt/local/share/man/man1'
 /usr/bin/install -c -m 644 speexenc.1 speexdec.1 '/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/destroot/opt/local/share/man/man1'
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/speex-1.2.1/src'
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/speex-1.2.1/src'
make[1]: Entering directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/speex-1.2.1'
make[2]: Entering directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/speex-1.2.1'
make[2]: Nothing to be done for `install-exec-am'.
 /opt/local/bin/gmkdir -p '/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/destroot/opt/local/share/aclocal'
 /usr/bin/install -c -m 644 speex.m4 '/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/destroot/opt/local/share/aclocal'
 /opt/local/bin/gmkdir -p '/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/destroot/opt/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 speex.pc '/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/destroot/opt/local/lib/pkgconfig'
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/speex-1.2.1'
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/speex-1.2.1'
make: Leaving directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/speex-1.2.1'
--->  Patching libspeex.la: /dependency_libs/ s/'.*'/''/
--->  Compressing man pages for speex
man1/speexdec.1:	 52.4% -- replaced with man1/speexdec.1.gz
man1/speexdec.1.gz: changing permissions from 00644 to 00444
man1/speexenc.1:	 54.2% -- replaced with man1/speexenc.1.gz
man1/speexenc.1.gz: changing permissions from 00644 to 00444
--->  Installing speex @1.2.1_0
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/destroot" && /usr/bin/tar -cvf - . | /opt/local/bin/lbzip2 -c9 > /opt/local/var/macports/software/speex/speex-1.2.1_0.darwin_10.ppc.tbz2 
a .
a ./+COMMENT
a ./+CONTENTS
a ./+DESC
a ./._+PORTFILE
a ./+PORTFILE
a ./+STATE
a ./opt
a ./opt/local
a ./opt/local/bin
a ./opt/local/include
a ./opt/local/lib
a ./opt/local/share
a ./opt/local/share/aclocal
a ./opt/local/share/doc
a ./opt/local/share/man
a ./opt/local/share/man/man1
a ./opt/local/share/man/man1/speexdec.1.gz
a ./opt/local/share/man/man1/speexenc.1.gz
a ./opt/local/share/doc/speex
a ./opt/local/share/doc/speex/manual.pdf
a ./opt/local/share/aclocal/speex.m4
a ./opt/local/lib/libspeex.1.dylib
a ./opt/local/lib/libspeex.a
a ./opt/local/lib/libspeex.dylib
a ./opt/local/lib/libspeex.la
a ./opt/local/lib/pkgconfig
a ./opt/local/lib/pkgconfig/speex.pc
a ./opt/local/include/speex
a ./opt/local/include/speex/speex.h
a ./opt/local/include/speex/speex_bits.h
a ./opt/local/include/speex/speex_callbacks.h
a ./opt/local/include/speex/speex_config_types.h
a ./opt/local/include/speex/speex_header.h
a ./opt/local/include/speex/speex_stereo.h
a ./opt/local/include/speex/speex_types.h
a ./opt/local/bin/speexdec
a ./opt/local/bin/speexenc
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_audio_speex/speex/work/destroot" && /usr/bin/tar -cvf - . | /opt/local/bin/lbzip2 -c9 > /opt/local/var/macports/software/speex/speex-1.2.1_0.darwin_10.ppc.tbz2 
Exit code: 1
Error: Failed to install speex: command execution failed
Error: See /opt/local/var/macports/logs/_opt_PPCRosettaPorts_audio_speex/speex/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there
is a bug.
Error: Processing of port speex failed
```

**Comment by sbooth** [comment]
@barracuda156 That's expected until #15448 is merged since this package depends on a package provided by that PR. I wasn't sure if you'd prefer two separate, dependent PRs or a single PR with two Portfiles.

**Comment by barracuda156** [comment]
> @barracuda156 That's expected until #15448 is merged since this package depends on a package provided by that PR. I wasn't sure if you'd prefer two separate, dependent PRs or a single PR with two Portfiles.

Nah, I have installed `speexdsp` from your PR, the error is not related to that. In fact, existing Macports `speex` version fails at install stage too.

**Comment by sbooth** [comment]
I'll have to investigate further, it is working for me:

```
--->  Computing dependencies for speex
The following dependencies will be installed:  speexdsp
Continue? [Y/n]: 
--->  Fetching distfiles for speexdsp
--->  Verifying checksums for speexdsp
--->  Extracting speexdsp
--->  Configuring speexdsp
Warning: Configuration logfiles contain indications of -Wimplicit-function-declaration; check that features were not accidentally disabled:
  vld1_s16: found in speexdsp-1.2.1/config.log
  vmull_s16: found in speexdsp-1.2.1/config.log
--->  Building speexdsp
--->  Staging speexdsp into destroot                     
--->  Installing speexdsp @1.2.1_0
--->  Activating speexdsp @1.2.1_0
--->  Cleaning speexdsp
--->  Fetching distfiles for speex
--->  Verifying checksums for speex
--->  Extracting speex
--->  Configuring speex
--->  Building speex                                     
--->  Staging speex into destroot                        
--->  Installing speex @1.2.1_0                          
--->  Activating speex @1.2.1_0
--->  Cleaning speex
--->  Scanning binaries for linking errors
--->  No broken files found.
--->  No broken ports found.
```

**Comment by barracuda156** [comment]
I don’t understand really what’s going wrong here. (Potentially, it may not be `speex` issue as such.)

Here is the log of @1.2.0_0:
```
:info:install Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_speex/speex/work/destroot" && /usr/bin/tar -cvf - . | /opt/local/bin/lbzip2 -c9 > /opt/local/var/macports/software/speex/speex-1.2.0_0.darwin_10.ppc.tbz2 
:info:install Exit code: 1
:error:install Failed to install speex: command execution failed
:debug:install Error code: CHILDSTATUS 12773 1
:debug:install Backtrace: command execution failed
:debug:install     while executing
:debug:install "system {*}$notty {*}$callback {*}$nice $fullcmdstring"
:debug:install     invoked from within
:debug:install "command_exec archive"
:debug:install     (procedure "create_archive" line 236)
:debug:install     invoked from within
:debug:install "create_archive $location $portarchivetype"
:debug:install     (procedure "portinstall::install_main" line 27)
:debug:install     invoked from within
:debug:install "$procedure $targetname"
```
[speex_1.2.0_10.6.8.log](https://github.com/macports/macports-ports/files/9174201/speex_1.2.0_10.6.8.log)

**Comment by barracuda156** [comment]
@sbooth And the log for your PR version:

[speex_1.2.1_10.6.8.log](https://github.com/macports/macports-ports/files/9174205/speex_1.2.1_10.6.8.log)

**Comment by sbooth** [comment]
@barracuda156 I'm not sure what is going on either. Could it be a problem with `lbzip2`? I don't have access to a PPC machine to test on, unfortunately.

**Comment by barracuda156** [comment]
> @barracuda156 I'm not sure what is going on either. Could it be a problem with `lbzip2`? I don't have access to a PPC machine to test on, unfortunately.

@sbooth My current results do not automatically extend to all PPC systems, since Rosetta is quite specific, and there are ports that fail only on Rosetta. I can test native PPC build next month only.

@evanmiller Could you please check if this builds fine on Leopard and/or Tiger?

**Comment by kencu** [comment]
@barracuda156 this looks like the same lbzip error you’re reporting you have in other builds

https://trac.macports.org/ticket/65526

so it appears yours is broken somehow…

**Comment by barracuda156** [comment]
> @barracuda156 this looks like the same lbzip error you’re reporting you have in other builds
> 
> 
> 
> https://trac.macports.org/ticket/65526
> 
> 
> 
> so it appears yours is broken somehow…

@kencu Thank you! Any idea how to try fixing that on my end? AFAIR I did not get these errors on Rosetta before. So perhaps something was changed since end of May that broke it.

**Comment by mascguy** [comment]
Restarting CI jobs, now that https://github.com/macports/macports-ports/pull/15448 has been merged.

**Comment by mascguy** [comment]
> Restarting CI jobs, now that #15448 has been merged.

Ah, you'll need to rebase against master, for CI to succeed.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
