### PR TITLE
py-tensorflow: update to 1.6.0

### PR DESCRIPTION
**Pull request by emcrisostomo**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix
- [x] update

###### Tested on

macOS 10.13.3 17D2104
Xcode 9.2 9C40b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Mostly looks good to me, but I don't quite get what's going on for py-grpcio — is that downloading binaries of some sort? (I only had a quick glance.)

**Comment by emcrisostomo** [comment]
@pmetzger Hi, yes, it's installing precompiled wheel packages (for 27, 35 and 36). BTW, I was waiting for Travis for this PR too. My plan is waiting until tomorrow morning (UTC+1).

**Comment by pmetzger** [comment]
Generally MacPorts prefers to build from source rather than using binaries. Is there a reason binaries are necessary in this context?

**Comment by emcrisostomo** [comment]
@pmetzger It's not required, but I thought it's a good idea. The rationale is the following: TensorFlow packages are tested and supported (with their given set of dependencies) on macOS. This is where my python-noob-reasoning may get flaky. Since those dependencies are declared and get installed using pip/wheel packages, and since wheel packages are documented to "have the advantage" of not needing being recompiled, I thought it was a good idea to pull them in and install them as is. This way, the _final_ state of the installation would be exactly as if a user would have followed the suggested, supported installation instructions. If it helps understanding my point, the analogy would be a Java package declaring dependencies installed via a package manager (e.g.: Maven) and coming from a reliable source (in this case http://pypi.python.org).

Nonetheless, I think we can try to build it from sources if it fits better with the MacPorts philosophy. I just want to strike the right balance between non duplicating upstream work (and potentially introducing subtle problems) and rebuild everything from source as it's typically done by BSD ports.

**Comment by pmetzger** [comment]
@emcrisostomo Not sure what the right thing is. Do you want to bring it up on the mailing list maybe?

**Comment by pmetzger** [comment]
@emcrisostomo So where do we go from here to get this moved forward? Ideas?

**Comment by emcrisostomo** [comment]
@pmetzger, I'm now trying to get one of the dependency (py-grpcio) to build correctly using MacPorts' `openssl`. If and when that works, it's possible I would consider splitting this PR to allow the changes to go to `master` without waiting for Tensorflow to build correctly.

**Comment by pmetzger** [comment]
Yah, splitting seems sensible. If you do a new PR for all the parts that will just go in immediately, then we can focus on the hard part on its own.

**Comment by emcrisostomo** [comment]
@pmetzger Just FYI, I've split the PR into multiple ones since the other submissions can be considered independently. When the other changes are committed I'll come back to this PR, I will rebase it against latest `master` and will start working on it.

**Comment by pmetzger** [comment]
@emcrisostomo Perhaps you should close this meanwhile and request a pull again when you're ready? The Pull Request queue is really meant for things that are actively about to be pulled...

**Comment by emcrisostomo** [comment]
@pmetzger You're right. Since I'm working locally and it will still take a while, I'm going to close this one.

**Pull request closed without merging**
