### PR TITLE
libmcs: remove port

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Closes https://trac.macports.org/ticket/58022

#### Description

I should say this is merely **proposing** to remove libmcs; please leave open long enough for discussion.

Q: Should `libmowgli` also be removed? `libmcs` was the only port depending on it; it has been succeeded by libmowgli 2.x, and other package managers have begun dropping libmowgli 1.x.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
No other open tickets for this port.

### CODE REVIEW

**Comment by pmetzger** [comment]
> please leave open long enough for discussion

How long do you consider that to be? (There's a good chance you'll get no real comments.)

**Comment by chrstphrchvz** [comment]
> How long do you consider that to be? (There's a good chance you'll get no real comments.)

Well, at least more than 12 hours—I get the impression that #3556 was merged too quickly (even though the idea for their removal was brought up in #3545), leaving the debate over whether deleting those ports was even appropriate to the mailing list.

Though I first asked if `libmcs` could be removed in the [ticket opened 5 weeks ago](https://trac.macports.org/ticket/58022), and so far only @mf2k has seconded the removal.

**Comment by MarcusCalhoun-Lopez** [comment]
I have no strong feelings about whether to remove this port or not.
However, it still builds with minimal patching, and I tend to be a little conservative when it comes to deleting ports.
We could just update the homepage and master_sites to use https://github.com/atheme-legacy/libmcs.
That shouldn't take too long, and I would be willing to make the changes myself.

The issues in [ticket 58022](https://trac.macports.org/ticket/58022) also seem fairly easy to fix.

**Comment by pmetzger** [comment]
@MarcusCalhoun-Lopez The problem is, if no one is using or cares about something, it takes up time that could be used on other things.

**Comment by MarcusCalhoun-Lopez** [comment]
Sorry about invalidating this pull request.
I realized it would happen about 10 seconds after I pushed the changes.
Hopefully, rebasing a deletion is not too much trouble.

I just wanted to offer an alternative to deleting a port right away: [marking it as deprecated](https://github.com/macports/macports-ports/commit/0147d314e6c235b2194204aa321c33db4f722156).
If no one likes this idea, then I have no objections to deleting this port.

Again, sorry for invalidating the pull request.

**Comment by chrstphrchvz** [comment]
@MarcusCalhoun-Lopez no problem at all, thanks for the heads up. I have rebased this PR.

Thanks also for looking into the libmowgli ports, and for creating the `deprecated` portgroup, which I think is a useful addition. It lets ports remain available while better informing users of potential or known issues. It provides an alternative somewhere between simply keeping a port "as-is" (without informing users of the port's condition) and obsoleting/deleting it.

However, does this portgroup need more feedback before keeping/using it? I would be interested in marking more ports as deprecated (e.g. ports of known discontinued projects like `DesktopManager`). But I wonder if others will object to deprecation notices as being "noisy" or unnecessary, or see deprecation as effectively stalling the deletion of ports that should be deleted (which is not how I see it—at a minimum it helps identify ports to consider deleting). 

For `libmcs`, I'm not sure there's consensus yet for whether to keep or remove it, though it is now marked as deprecated, and maybe that's enough for now. The issues in https://trac.macports.org/ticket/58022 I feel have been addressed, so closing that would be fine with me.

**Comment by pmetzger** [comment]
So where are we on this?

**Comment by MarcusCalhoun-Lopez** [comment]
> So where are we on this?

Unfortunately, there seems to be no clear consensus on when a port should be deleted, either in this pull request or on the [mailing list](https://lists.macports.org/pipermail/macports-dev/2019-February/thread.html#40071).
I believe it is an important issue, but I am not sure where to go from here.

**Comment by pmetzger** [comment]
@MarcusCalhoun-Lopez As you stepped in initially, I'll leave you to manage the situation as you see fit.

**Comment by cjones051073** [comment]
We should either make progress i. Merging this, or close it. It shouldn’t be left hanging.

**Comment by MarcusCalhoun-Lopez** [comment]
Since marking something as deprecated is still fairly new, let us close this until a better consensus emerges about how to handle these types of ports.

**Pull request closed without merging**
