### PR TITLE
OpenBLAS: keep cmake integration

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [x] bugfix

###### Tested on

macOS 12.7.1 21G920 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by catap** [comment]
FYI: @szhorvat

**Comment by jmroot** [comment]
Typo in the commit message: cmake->camke

**Comment by catap** [comment]
@jmroot thanks for catching that up.

**Comment by szhorvat** [comment]
#21423 is dependent on this.

**Comment by szhorvat** [comment]
Still can't test this on my system because the build process also tries to run the tests, and the tests fail (one crash, then hangs).

**Comment by catap** [comment]
Thanks, Perry!

**Pull request merged**
