### PR TITLE
cpprestsdk: update to 2.10.11

### PR DESCRIPTION
**Pull request by mohd-akram**
###### Tested on
macOS 10.14.3 18D109
Xcode 10.1 10B61

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
@mohd-akram are the test failures here anything to be concerned over ?

**Comment by mohd-akram** [comment]
I'm not sure, I don't know what this means:

    DEBUG: dlist_eval: all entries in dependency list have unsatisfied dependencies; can't process

Might need to trigger tests again.

**Comment by mf2k** [comment]
That was due to `cmake`, temporarily, having a cyclical dependency added. That has since been fixed. So the builds should be re-triggered. I'm not sure how to tell the buildbots to do that outside of updating the PR.

**Comment by cjones051073** [comment]
All looks good now, thanks.

**Pull request merged**
