### PR TITLE
log4cpp: update to 1.1.4

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with ~`sudo port -vst install`~ `sudo port -d destroot`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by michaelld — APPROVED** [review]
LGTM ; thx!

**Comment by michaelld** [comment]
CI/QA is not happy with this change. I'm rerunning to see if that helps.

**Comment by michaelld** [comment]
Here's the error:
```
  /bin/sh ../libtool  --tag=CXX   --mode=compile /usr/bin/clang++ -DHAVE_CONFIG_H -I. -I../include  -I../include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk  -pipe -Os -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -arch x86_64 -Wall -Wno-unused -pedantic -MT StringUtil.lo -MD -MP -MF .deps/StringUtil.Tpo -c -o StringUtil.lo StringUtil.cpp
  libtool: compile:  /usr/bin/clang++ -DHAVE_CONFIG_H -I. -I../include -I../include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -pipe -Os -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -arch x86_64 -Wall -Wno-unused -pedantic -MT StringUtil.lo -MD -MP -MF .deps/StringUtil.Tpo -c StringUtil.cpp  -fno-common -DPIC -o .libs/StringUtil.o
   StringUtil.cpp:45:23: error: array type 'va_list' (aka '__builtin_va_list') is not assignable
              args_copy = args;
              ~~~~~~~~~ ^
  1 error generated.
  make[1]: *** [StringUtil.lo] Error 1
```

**Comment by michaelld** [comment]
@herbygillot can you debug the CI/QA build issue?

**Comment by michaelld** [comment]
CI/QA is still unhappy. Will need to build locally to verify. I'm assuming you did this on your system before pushing the PR, yes?

**Comment by herbygillot** [comment]
> CI/QA is still unhappy. Will need to build locally to verify. I'm assuming you did this on your system before pushing the PR, yes?

Yes, this is building just fine for me locally. I haven't yet figured out how to resolve the issue we're seeing in CI. Here are the details on my local environment:

macOS 12.6.6 21G646 arm64
Xcode 14.0 14A309

**Comment by pmetzger** [comment]
@herbygillot Any ideas on how to get this unstuck?

**Comment by pmetzger** [comment]
Looks like the CI is still not happy.

**Comment by pmetzger** [comment]
@herbygillot Poke.

**Comment by pmetzger** [comment]
@herbygillot Looks like the CI died again.

**Comment by herbygillot** [comment]
Close to just giving up on this, but going to try one or two more things.

**Comment by pmetzger** [comment]
I assume it works locally on your machine in trace mode?

**Comment by herbygillot** [comment]
> I assume it works locally on your machine in trace mode?

Yes, it's been building just fine locally the entire time.  Was only seeing these failures in CI.  Looks like it's good now.

**Pull request merged**
