### PR TITLE
pgpointcloud: respect CXX configuration variable

### PR DESCRIPTION
**Pull request by nilason**
#### Description

The build does not respect the `CXX` variable. This PR adds a patch, which fixes this.
(The patch is submitted upstreams.)

The port's patch files are now split into separate files according to issue.

Closes https://trac.macports.org/ticket/68723

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.6.2 22G320 arm64
Xcode 15.0.1 15A507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
Great but it still doesn't respect the CXXFLAGS environment variable. Maybe adding `@CXXFLAGS@` to the end of the `CXXFLAGS` line, mirroring the earlier `CFLAGS` line, is all that's needed.

In fact, it's weird that it says `CFLAGS = @CFLAGS@` (meaning: any CFLAGS specified as environment variables at build time are overwritten by those that were specified at configure time, which is probably fine for a project that uses a configure script) yet it says `CXXFLAGS += -fPIC -std=c++0x` (meaning: any CXXFLAGS specified as environment variables at build time are appended to and any specified at configure time are ignored). They should both respect choices made at configure time, and they should both either ignore build-time environment variables or make use of them, I don't care which, it just makes no sense that the two variables are handled differently from one another.

**Comment by nilason** [comment]
> Great but it still doesn't respect the CXXFLAGS environment variable. Maybe adding `@CXXFLAGS@` to the end of the `CXXFLAGS` line, mirroring the earlier `CFLAGS` line, is all that's needed.
> 
> In fact, it's weird that it says `CFLAGS = @CFLAGS@` (meaning: any CFLAGS specified as environment variables at build time are overwritten by those that were specified at configure time, which is probably fine for a project that uses a configure script) yet it says `CXXFLAGS += -fPIC -std=c++0x` (meaning: any CXXFLAGS specified as environment variables at build time are appended to and any specified at configure time are ignored). They should both respect choices made at configure time, and they should both either ignore build-time environment variables or make use of them, I don't care which, it just makes no sense that the two variables are handled differently from one another.

I agree that there is inconsistence, what do you think of changing to this:

```
CC = @CC@
CFLAGS += @CFLAGS@
CXX = @CXX@
CXXFLAGS += -fPIC -std=c++11 @CXXFLAGS@
```

**Comment by pmetzger** [comment]
@nilason You may have to come up with a solution on your own. Ryan is often busy and doesn't have the time to respond. Let me know when you feel you have something you are comfortable committing.

**Comment by nilason** [comment]
> @nilason You may have to come up with a solution on your own. Ryan is often busy and doesn't have the time to respond. Let me know when you feel you have something you are comfortable committing.

Thanks, will give this some more thought and ping you when the time has come.

**Comment by nilason** [comment]
@pmetzger Now I'm good for merge.

**Pull request merged**
