### PR TITLE
wireshark{3,4}: fix python selection

### PR DESCRIPTION
**Pull request by i0ntempest**
Closes: https://trac.macports.org/ticket/68362

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by reneeotten — CHANGES_REQUESTED** [review]
it looks like this would need a "revision" increase to make sure the change is picked up for everyone?

**Comment by i0ntempest** [comment]
> it looks like this would need a "revision" increase to make sure the change is picked up for everyone?

Are you sure? This only fixes a build error, I think python is only used during build and won’t affect installed content.

**Comment by reneeotten** [comment]
> > it looks like this would need a "revision" increase to make sure the change is picked up for everyone?
> 
> Are you sure? This only fixes a build error, I think python is only used during build and won’t affect installed content.

okay, that's a good point - in that case it is indeed not needed. Next question then is why would one have Python variants to decide which version to use when building the port - that makes zero sense. Just pick the default in MacPorts and use that...

**Comment by i0ntempest** [comment]
> > > it looks like this would need a "revision" increase to make sure the change is picked up for everyone?
> > 
> > 
> > Are you sure? This only fixes a build error, I think python is only used during build and won’t affect installed content.
> 
> okay, that's a good point - in that case it is indeed not needed. Next question then is why would one have Python variants to decide which version to use when building the port - that makes zero sense. Just pick the default in MacPorts and use that...

That you’ll have to ask @ghosthound. But I do know that due to a deprecated module being removed, Python 3.12 will not work here.

**Comment by pmetzger** [comment]
Is this ready to merge?

**Comment by i0ntempest** [comment]
I consider this ready.

**Pull request merged**
