### PR TITLE
got: update to version 0.74.

### PR DESCRIPTION
**Pull request by artkiver**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.4 21F79 arm64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
Minor nitpick, but can we align the checksums?

**Comment by artkiver** [comment]
> Minor nitpick, but can we align the checksums?

Ah, looking at this on my local system in vi, the checksums look alligned, same for on GitHub, but maybe the Size relative to the output could use an extra space? Let me see what I can do. (I would probably typically just close this PR and create a new one, is that acceptable?)

**Comment by herbygillot** [comment]
If you feel you need to close this PR and open a new one, then nevermind. Thanks @artkiver

**Comment by artkiver** [comment]
Oh! Are they not aligned? Sorry, using vi on my local system and I don't
observe a discrepancy.

**Pull request merged**
