### PR TITLE
cmake-devel: remove homebrewisms

### PR DESCRIPTION
**Pull request by kencu**
there are some hardcoded references to homebrew paths that have crept into cmake over time. Remove these.

prevents homebrew-installed software like python from being detected over the settings in PATH and PREFIX, if the user happens to have homebrew installed in /opt/homebrew

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.0 23A344 arm64
Xcode 15.0 15A240d

with both macports and homebrew installed, homebrew in /opt/homebrew
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by kencu** [comment]
I know MacPorts does not in any way support having both macports and homebrew installed, but folks do this anyway, so we might as well not shoot ourselves in the foot.

(Now that homebrew has realized that installing it's files into /usr/local has always been a bad idea and no longer recommends or does this on newer systems, having them both installed is actually very simple to manage for a wiser user.)

**Comment by mascguy** [comment]
> I know MacPorts does not in any way support having both macports and homebrew installed, but folks do this anyway, so we might as well not shoot ourselves in the foot.
> 
> (Now that homebrew has announced that installing it's files into /usr/local has always been a bad idea and no longer recommends or does this on newer systems, having them both installed is actually very simple to manage for a wiser user.)

Sounds great to me, was planning to fix eventually anyway.

Thanks for taking care of this Ken!

**Review by mascguy — APPROVED** [review]

**Comment by kencu** [comment]
(btw cmake 3.27.7 is released now https://cmake.org/download/, so pretty soon cmake-devel might roll into cmake.)

**Comment by kencu** [comment]
oh, whoopsie -- I just realized that  ```_brew_framework_path``` is not initialized to anything now ... let me make sure that is not used later on somewhere.

**Comment by mascguy** [comment]
> oh, whoopsie -- I just realized that  ```_brew_framework_path``` is not initialized to anything now ... let me make sure that is not used later on somewhere.
> 
> -- no, not used anywhere, so still all OK.
> 
> There is one last "brewism" in FindIce.cmake but that one is less obviously a problem and needs someone who knows about that package to weigh in.

Would you like to keep this PR open for now then?

**Comment by kencu** [comment]
> Would you like to keep this PR open for now then?

Yes, I think this is OK. It helps the situation quite a bit, and FindIce.cmake I suspect may not need tweaking in the end.

**Comment by michaelld** [comment]
@kencu this is great; thx! Let us know when you're done & I for one will definitely approve!

**Pull request merged**
