### PR TITLE
update LibreSSL to 3.4.2 see: https://trac.macports.org/ticket/63615

### PR DESCRIPTION
**Pull request by artkiver**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [x] security fix

###### Tested on

macOS 12.0.1 21A559 arm64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by artkiver** [comment]
update LibreSSL to 3.4.2 see: https://trac.macports.org/ticket/63615

**Comment by reneeotten** [comment]
@artkiver can you please clean-up your commits: do a `rebase` and squash them so that there is only one left with your proposed changes?

**Comment by artkiver** [comment]
@reneeotten did a rebase, and dropped the 3.4.0 commit. Hopefully that is sufficient?

Also see: https://github.com/artkiver/macports-ports/commit/9462c9d48300a3be4307832a85ac0dc18b5d96e7

**Comment by mascguy** [comment]
Just approved your CI jobs. And welcome to MacPorts!

**Comment by reneeotten** [comment]
> @reneeotten did a rebase, and dropped the 3.4.0 commit. Hopefully that is sufficient?

not really, as you can see there are 8 commits in this PR including "merge commits", as I said above please do a rebase and make sure you have only 1 commit left with your proposed changes. 

When doing that please make sure your commit message follows our guidelines, which you checked off in the PR checklist but didn't do. It should be `libressl: update to 3.4.2` and then have `Fixed: https://trac.macports.org/ticket/63615` in the body of the commit message (assuming that is closes that ticket).

**Comment by artkiver** [comment]
Closing this pull request. Please see updated attempt here: https://github.com/macports/macports-ports/pull/13311

**Pull request closed without merging**
