### PR TITLE
taco: new port in math

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

New port: https://github.com/tensor-compiler/taco

Tests mostly pass on 10.6.8 `x86_64`:
```
99% tests passed, 2 tests failed out of 231

Total Test time (real) = 294.20 sec

The following tests did not run:
	 43 - expr.accumulate (Disabled)
	 55 - format.mm_permute_formats (Disabled)
	101 - qcd.mul3 (Disabled)
	127 - generate_evaluation_files.cpu (Disabled)
	128 - generate_evaluation_files.gpu (Disabled)
	129 - generate_figures.cpu (Disabled)
	130 - scheduling_eval.bfsPullScheduled (Disabled)
	193 - tensor_types.complex_mul_scalar (Disabled)
	198 - tensor_types.coordinate_types (Disabled)
	204 - lower.transpose (Disabled)
	205 - lower.transpose2 (Disabled)
	206 - lower.transpose3 (Disabled)

The following tests FAILED:
	 99 - qcd.mul1 (Failed)
	243 - taco-cli-test (Failed)
Errors while running CTest
```

PPC does not work presently: https://github.com/tensor-compiler/taco/issues/541 (`malloc` errors, and adding `DYDL_LIBRARY_PATH` to `test.env` fails to help, whether directly or via `legacysupport` PG).

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Let me see if something can be done for PPC first.

**Comment by mascguy** [comment]
> Let me see if something can be done for PPC first.

Don't forget this PR too...

**Comment by barracuda156** [comment]
> > Let me see if something can be done for PPC first.
> 
> Don't forget this PR too...

I was discussing with upstream in a hope to get some advice, but apparently we are on our own here: https://github.com/tensor-compiler/taco/issues/541

Of course we could merge this first with a note that PPC needs fixes, but given that nothing depends on this port, I would rather give myself some extra time to see if PPC is fixable. I will try to get to this, say, within a week.
But I am also okay with merging now and fixing PPC a bit later, no issues.

**Comment by reneeotten** [comment]
@barracuda156 where are we with this?

**Comment by barracuda156** [comment]
@reneeotten Please keep this alive. In the process, let me do an update for upstream issue tomorrow.

In the meanwhile, could you help to merge PRs which are long back ready? I would also appreciate a clean-up and have only unfinished PRs open.

**Comment by reneeotten** [comment]
like which PRs do you consider ready?

**Comment by barracuda156** [comment]
> like which PRs do you consider ready? 

#19751
#19716
#19629
#19527

**Comment by pmetzger** [comment]
So all of those are merged. Can we close this? @barracuda156 closing a PR doesn't mean the update is dead. It just means no one but the person working on it is expected to spend time on it. If stuff is sitting in the queue, people are supposed to be checking on it and shepherding it through. If you have a private queue of things you're working on and that others shouldn't be thinking about, those should be in your repo. The PR queue is really for things we think are ready to work on and get committed.

**Comment by barracuda156** [comment]
@pmetzger @reneeotten Yeah, sure. I will return to it, I hope, but it is fine to close it atm.
I am travelling presently, so away from PPC and x86 hardware and somewhat short on time too.

**Pull request closed without merging**
