### PR TITLE
bpack: update to 2.4.0

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
CI just do not want to work today.

**Comment by barracuda156** [comment]
```
Updating PortIndex
  From https://github.com/macports/macports-ports
   * branch              master     -> FETCH_HEAD
   * [new branch]        master     -> macports/master
  curl: (35) Recv failure: Connection reset by peer
```

**Comment by barracuda156** [comment]
```
  Installing dependency (4::endgroup::
  Error: Failed to install dependencies for bpack
```

**Comment by barracuda156** [comment]
@cjones051073 Could you say why this may be failing?
```
  Building 2 dependencies of bpack:
  Building dependency (1 of 2) 'mpich-clang16' with variants '+gcc13' ... [FAIL]
Error: Failed to install dependencies for bpack
```
Untouched in the PR, of course.

**Comment by barracuda156** [comment]
@szhorvat @catap @cjones051073 Any idea why this is left broken? Dependencies fail to install, log has `'mpich-clang16' with variants '+gcc13' ... [FAIL]`.

**Comment by catap** [comment]
@barracuda156 my guess that github updates xcode on macOS 13 runner and we enjoying xcode 15 incompatibility on mpich.

We should wait until mpich is updated.

**Comment by barracuda156** [comment]
Well, that will leave a lot of ports broken.

**Pull request merged**
