### PR TITLE
libssh2: apply pragma patch for gcc versions, not OS

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Rosetta also needs existing patch, otherwise build fails with:
```
x11.c: In function ‘main’:
x11.c:328: error: #pragma GCC diagnostic not allowed inside functions
x11.c:329: error: #pragma GCC diagnostic not allowed inside functions
x11.c:333: error: #pragma GCC diagnostic not allowed inside functions
make[1]: *** [x11.o] Error 1
```

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
I really don't like all this 10.6-PPC spaghetti fixes. They are both fragile and cumbersome and I believe we (you) can do better than this. 

A better fix, that would happen to fix rosetta and 10.6 on PPC too, would be to match against the gcc versions that won't support these pragmas. For example, something that would match *gcc-4.* would probably do it. That is a fair, general, correct fix without the 10.6 on PPC specific hacks in there.

However, A=an even better, possibly upstreamable fix, is to use some predefined compiler definitions to sort out which compilers can support pragmas inside functions, and then only use them if supported, like I did here:

https://github.com/macports/macports-ports/blob/master/devel/libuv/files/patch-libuv-unix-core-close-nocancel.diff

I would much prefer if your fixes were generic and not 10.6-on-PPC specific. I think everyone would.

**Comment by barracuda156** [comment]
> I really don't like all this 10.6-PPC spaghetti fixes. They are both fragile and cumbersome and I believe we (you) can do better than this.
> A better fix, that would happen to fix rosetta and 10.6 on PPC too, would be to match against the gcc versions that won't support these pragmas. For example, something that would match `*gcc-4.*` would probably do it. That is a fair, general, correct fix without the 10.6 on PPC specific hacks in there.
> However, an even better, possibly upstreamable fix, is to use some predefined compiler definitions to sort out which compilers can support pragmas inside functions, and then only use them if supported, like I did here:
> 
> https://github.com/macports/macports-ports/blob/master/devel/libuv/files/patch-libuv-unix-core-close-nocancel.diff

This makes sense. Matching against `gcc` version is certainly doable (and indeed better than against OS – after all, gcc-4.* can be used on much later OS that 10.6), and I will look into compiler definitions alternative too.

**Comment by barracuda156** [comment]
@kencu By the way, speaking about more correct and general fixes: what could be done with ports which fail to use Macports build_arch settings, forcing instead cpu_arch (which breaks some ports on Rosetta)? Who is at fault here – why in many cases triple is correct but in some we get x86 or i386 when building for PPC? (To be clear, I refer to configure/makefiles-based ports here, not cmake/meson-based ones.)

**Comment by kencu** [comment]
> @kencu By the way, speaking about more correct and general fixes: what could be done with ports which fail to use Macports build_arch settings, forcing instead cpu_arch (which breaks some ports on Rosetta)? Who is at fault here – why in many cases triple is correct but in some we get x86 or i386 when building for PPC? (To be clear, I refer to configure/makefiles-based ports here, not cmake/meson-based ones.)

There may well be some inconsistencies uncovered in your copious cross-compiling using rosetta that have never been uncovered before. All these should be fixed, if you flag them as tickets they will get attention, and if base needs something Josh or Ryan will weigh in too.

**Comment by kencu** [comment]
@barracuda156 -- if you confirm this works, no issues, we can push

**Comment by barracuda156** [comment]
> @barracuda156 -- if you confirm this works, no issues, we can push

@kencu Yes, it works.

**Comment by kencu** [comment]
thank you, very nice

**Pull request merged**
