### PR TITLE
Update beets-devel and some plugins

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.4 21F79 x86_64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mascguy — APPROVED** [review]
LGTM, will merge once CI completes.

**Comment by catap** [comment]
@mascguy do you have any idea why CI did fail?

**Comment by catap** [comment]
rebased to the last master to trigger one more CI cycle

**Comment by mascguy** [comment]
Just tested locally, and everything looks good... with one exception: While you updated the checksum for `beets-ibroadcast`, it looks like version was updated.

**Comment by mascguy** [comment]
Just tested locally, and everything looks good... with one exception: While you updated the checksum for `beets-ibroadcast`, it looks like the version wasn't updated.

**Comment by catap** [comment]
@mascguy thanks! it might be the root cause of CI failure.

**Comment by mascguy** [comment]
> @mascguy thanks! it might be the root cause of CI failure.

Just tested your update, and looks good! So even if CI still fails, I'm fine with merging.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
