### PR TITLE
Add GitHub handle pvanek to maintainers

### PR DESCRIPTION
**Pull request by ryandesign**
Add GitHub handle @pvanek to maintainers and update email address.

As far as I can tell, this is your current email address and GitHub handle. If that's not correct or if you don't wish to maintain these ports anymore please let me know.

### CODE REVIEW

**Comment by mf2k** [comment]
See also https://trac.macports.org/ticket/54429.

**Comment by pmetzger** [comment]
@mf2k Would you like to commit a change of these ports to "nomaintainer" and close this PR? I'd do it but I'm up to my eyeballs in tasks for the day.

**Comment by mf2k** [comment]
Like always, I commit things as I have time, which is not very often.

**Comment by mf2k** [comment]
I think this PR should be closed and the ports set to nomaintainer.

**Comment by pvanek** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Hi guys. Pvanek here. I do apologize but I don't own a mac anymore.Please use nomaintainer.Thanks for understandingPetr                                                                                                                                                                        Sent from my BlackBerry - the most secure mobile device                                                                                                                                                                           From: notifications@github.comSent: July 15, 2018 8:19 PMTo: macports-ports@noreply.github.comReply-to: reply@reply.github.comCc: petr@yarpen.cz; mention@noreply.github.comSubject: Re: [macports/macports-ports] Add GitHub handle pvanek to maintainers (#2185)  I think this PR should be closed and the ports set to nomaintainer.

**Comment by pmetzger** [comment]
@ryandesign Perhaps you should set these to nomaintainer then?

**Comment by pmetzger** [comment]
Rather than wait I've just set these to nomaintainer.

**Pull request closed without merging**
