### PR TITLE
auto-multiple-choice: update to 1.3.0.2132

### PR DESCRIPTION
**Pull request by nortcele**
auto-multiple-choice, auto-multiple-choice-devel: update to 1.3.0.2132

#### Description

* add githup handle
* add bitbucket portgroup
* add texlive portgroup
* update to 1.3.0.2132
* remove CUPS information from description
* replace variant -latex by variant +mactex
* remove patchfile
* add conflicts with auto-multiple-choice-devel
* add auto-multiple-choice-devel port

######Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

######Tested on

macOS 10.13.1 17B1003
Xcode 9.1 9B55 

macOS 10.9.5 13F1911
Xcode 6.2 6C131e

######Verification

Have you

- [x] followed our Commit Message Guidelines?
- [x] checked that there aren't other open pull requests for the same change?
- [ ] referenced existing tickets on Trac with full URL?
- [x] checked your Portfile with port lint?
- [ ] tried existing tests with sudo port test?
- [x] tried a full install with sudo port -vst install?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mojca** [comment]
Can you make the `-devel` port a subport of the main one?

**Comment by nortcele** [comment]
I return back to the guide to see what how to make a subport…

After reading one more time the [](https://trac.macports.org/wiki/CommitMessages), I see that I should have merged my developpment branch before my push. Should I cancel this push and come with a new one after having merge?

**Comment by mojca** [comment]
I'm not sure what exactly you are asking with respect to merging, but no, you don't need to close the PR. Just force push to your branch whatever is needed in case you think something went wrong (but I don't see anything obvious right now).

To make a subport, put a statement like
```
subport ${name}-devel {
    ...
}
```
somewhere in your `Portfile` and put everything that's specific to that subport there. You could also use
```
if {${name} eq ${subport}} {
    ...
} else {
    ...
}
```
to distinguish between what a the main and what the devel subport should do. I'm not sure if we have any good documentation about subports (I never checked), but there are plenty of ports that use it which you could check for examples. The idea is to share whatever repetition is needed between the two ports. I guess you mostly need different versions/checksums, perhaps different patches.

**Comment by mojca** [comment]
And in case you need help, feel free to ask, either on IRC, on the mailing list or here. I can try to help if it takes you too long to figure it out, it should be relatively straightforward.

**Comment by nortcele** [comment]
Concerning documentation there is nothing clear about subports but I found a port (devel/jsoncpp) that helped me to understand usage.

I could easily, transform the devel port to a subport as there no notable divergence between the port and the subport.

I'll try to ask on IRC

**Comment by nortcele** [comment]
Is a subportis desirable when there is a long delay between major releases and frequent changes in the devel version?

**Comment by nortcele** [comment]
Change port auto-multiple-choice-devel to a subport or auto-multiple-choice

**Pull request merged**
