### PR TITLE
kotlin: update to 1.2.10

### PR DESCRIPTION
**Pull request by breun**
#### Description

Updated Kotlin to 1.2.10. Also changed maintainer from @amake to myself, as suggested here: https://github.com/macports/macports-ports/pull/1068#issuecomment-348089774

###### Tested on

macOS 10.13.2 17C88
Xcode 9.2 9C40b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by l2dy** [comment]
Please amend the commit message to mention that the maintainer was changed.

**Comment by breun** [comment]
I've amended the commit message.

**Comment by l2dy** [comment]
First line of the commit message should use no more than 60 characters, see https://trac.macports.org/wiki/CommitMessages.

**Comment by breun** [comment]
Ok, I've shortened the message.

**Pull request merged**
