### PR TITLE
swift-format: new port

### PR DESCRIPTION
**Pull request by goranmoomin**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.2.1 21D62 arm64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by reneeotten — CHANGES_REQUESTED** [review]
please do not close a PR (#11143) and then open an identical one... there is no context here anymore and/or information about what was requested in the past. If it didn't get merged last time that probably means it's not ready or nobody has been sufficiently interested to look at it. If you want to get attention to a PR you could instead send a message to the development mailing list.

**Comment by goranmoomin** [comment]
@reneeotten Sorry for the noise on the closed PR. The PR is significantly different from the last one (rewritten from scratch after studying a bit on MacPort internals) and I thought I've already closed the old one when submitting this first (and that it was 4AM in the morning when I finally decided to open the PR). Should I just reopen the old PR and close this then in this case?

**Comment by reneeotten** [comment]
> @reneeotten Sorry for the noise on the closed PR. The PR is significantly different from the last one (rewritten from scratch after studying a bit on MacPort internals) and I thought I've already closed the old one when submitting this first (and that it was 4AM in the morning when I finally decided to open the PR). Should I just reopen the old PR and close this then in this case?

ah sorry, I see now that you first pushed changes to that PR, closed it and then opened this one. That part I missed... I thought you just closed the other one and opened a new PR with the exact same code as 8 months ago (which was the impression I got when I compared the Portfiles from both PRs). It would probably still be better to just have updated the other PR but since we're here already now, just leave it as-is.

**Comment by reneeotten** [comment]
there is a failure on macOS 11 though in the CI:
```
  /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/XCTest.swiftmodule/x86_64-apple-macos.swiftinterface:7:8: error: no such module '_Concurrency'
```

any idea on how to fix that?

**Comment by goranmoomin** [comment]
I'm investigating on it, but I currently don't have access to a macOS 11 machine. No idea why building is failing on macOS internal headers...

(I've just force-pushed a possible fix. Maybe this might succeed?)

**Comment by usersxx** [comment]
> I'm investigating on it, but I currently don't have access to a macOS 11 machine. No idea why building is failing on macOS internal headers...
> 
> (~I've just force-pushed a possible fix. Maybe this might succeed?~ Turns out it fails in macOS 10.15.)

You can test `swift-format` on macOS 12 arm64 (since this port supports arm64) by following steps:
1) Add file:///path/to/localportsrepository to /opt/local/etc/macports/sources.conf file. 
2) Use `cd /path/to/localportsrepository` command in terminal
3) Use `portindex` command in terminal
4) Type `sudo port install swift-format` in terminal

**Comment by goranmoomin** [comment]
@usersxx I've already tested installing before I opened the PR. It works on my machine... I'm suspecting that the build error is a macOS 11-specific problem.

**Comment by usersxx** [comment]
> 

You can update to macos-11, if you computer supports.

**Comment by goranmoomin** [comment]
@usersxx I'm on a ARM64 macOS 12 machine, with no downgrade path (it shipped with Monterey).

Looking at the build error itself, it seems that the swift compiler is failing to compile the concurrency-related parts of the Xcode XCTest headers – I have no idea why that's happening: The Xcode looks recent enough to have a swift compiler with concurrency support baked in. 

Would it be possible that the build machines are using `swift` binaries that doesn't come from Xcode at all?

**Comment by goranmoomin** [comment]
I've just pushed a change to try using `xcrun` to run the swift compiler just in case that the swift compiler and the Xcode version is out of sync for some reason.

**Comment by usersxx** [comment]
I would suggest you to change `xcodeversion_range  13.0` to `xcodeversion_range  13.0 13.1` because I assume that xcode 13.1 has been tested on swift-format 0.50500.0 based on swift format readme.md (https://github.com/apple/swift-format/blob/main/README.md#matching-swift-format-to-your-swift-version)

**Comment by usersxx** [comment]
I would suggest you to change `xcodeversion_range  13.0` to `xcodeversion_range  13.0 13.1` because I assume that swift-format 0.50500.0 has been tested with XCode 13.1 based on swift format readme.md (https://github.com/apple/swift-format/blob/main/README.md#matching-swift-format-to-your-swift-version)

**Comment by goranmoomin** [comment]
@usersxx I've been building it with my Xcode 13.2 installation, so I really don't think that's the problem – but I think I'll just paper over this problem by just not building the test-related stuff.

**Comment by usersxx** [comment]
> @usersxx I've been building it with my Xcode 13.2 installation, so I really don't think that's the problem – ~but I think I'll just paper over this problem by just not building the test-related stuff.~ and... I didn't realize that doesn't work at well. Ugh!

@goranmoomin, Could you check the source code and add any [patchfiles](https://guide.macports.org/chunked/development.patches.html#development.patches.source) to fix the build. That would be awesome.

**Comment by pmetzger** [comment]
This has now been stuck in the queue for well over a year. I propose we close it.

**Comment by goranmoomin** [comment]
Yup in fact the upstream has a new version scheme, so I'll have to significantly update the port. Will close.

**Pull request closed without merging**
