### PR TITLE
ghc: Update to version 9.2.1 and add native arm64 support

### PR DESCRIPTION
**Pull request by essandess**
#### Description

The prebuilt binaries work.

Bootstrapping doesn't currently work because of this issue: https://gitlab.haskell.org/ghc/ghc/-/issues/19631

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.6.1 20G224 x86_64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
You put "WIP" into the title here. Does that mean you don't want this committed?

**Comment by essandess** [comment]
> You put "WIP" into the title here. Does that mean you don't want this committed?

My preference is that we wait until upstream fixes the bootstrapping issue, of which they're aware. But if there is demand now for a prebuilt binary, especially for native M1 builds, we have this in our pocket.

**Comment by pmetzger** [comment]
I don't love "WIP" merge requests because they make it harder for people doing maintenance on the merge queue to see what they do and don't have to work on. However for now I've just added the "wip" tag.

**Comment by cjones051073** [comment]
If you wish to indicate a PR is not ready, please use the github draft feature, which actually prevents it from being merged, rather than just adding random labels which don’t prevent merging, thanks.

**Comment by cjones051073** [comment]
> I don't love "WIP" merge requests because they make it harder for people doing maintenance on the merge queue to see what they do and don't have to work on. However for now I've just added the "wip" tag.

Once a PR has been made draft, you can just exclude it from the list of PRs you need to scan through by just appending draft:false to the filters… i.e.

https://github.com/macports/macports-ports/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse

**Comment by pmetzger** [comment]
@essandess any progress on this? It would be nice to have things like pandoc working right on M1.

**Comment by essandess** [comment]
@pmetzger This is an upstream issue and has nothing to do with us.

Also, `ghc` and `pandoc` and other `stack`-based `x86_64` builds already work on M1. They’re just not native binaries.

**Comment by pmetzger** [comment]
> This is an upstream issue and has nothing to do with us.

I know, but have they done anything? It's been a while.

**Comment by essandess** [comment]
> > This is an upstream issue and has nothing to do with us.
> I know, but have they done anything? It's been a while.

The issue link is in the commit above. Clicking on it., I see that it’s open and that they’re working the issue.

**Comment by reneeotten** [comment]
what's the plan here. If we're waiting for upstream to fix something before we can merge this PR let's just close it for now and you can submit something again once that has happened.

**Comment by essandess** [comment]
> what's the plan here. If we're waiting for upstream to fix something before we can merge this PR let's just close it for now and you can submit something again once that has happened.

Yep, waiting for upstream. I’ll close for now.

**Pull request closed without merging**
