### PR TITLE
py-spaCy: Update to version 3.4.0, Add Python 310; py-spaCy-models: Add Python 310

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Steve, is this building for you locally? If so, which combination of macOS and Xcode are you using?

**Comment by essandess** [comment]
> Steve, is this building for you locally? If so, which combination of macOS and Xcode are you using?

Yes, and I'm testing with `port -vstd install py310-spaCy`.

macOS 12.5.1 21G83 x86_64
Xcode 13.4.1 13F100

**Comment by essandess** [comment]
> Steve, is this building for you locally? If so, which combination of macOS and Xcode are you using?

@mascguy The issue you're seeing is likely that I've had to [force-push](https://github.com/macports/macports-ports/compare/72b88fb8b5ba386a25546062fb93eb41180e8118..66636c900fba24f7460bed05a7bb88663c0cc8d5) some changes to get the build working in trace and within the CI.

You appear to be writing over these changes when you rebase, giving an older version that will not build.

To avoid stepping on each other's toes, I suggest something like this workflow to keep remote edits intact:
```sh
git checkout ${MYBRANCH}
git fetch
git reset --hard origin/${MYBRANCH}
```

**Comment by essandess** [comment]
The CI is failing on Python 37. That’s EOL soon anyway and there are only two dependencies currently in PR so let’s just toss that one overboard.

**Review by mascguy — APPROVED** [review]
CI looks good, merging!

**Pull request merged**
