### PR TITLE
Lisp new ports 6

### PR DESCRIPTION
**Pull request by catap**
#### Description

Here the sixth out of seven portion of new lisp ports that required to bring nyxt.

###### Type(s)

- [x] enhancement

###### Tested on

macOS 12.6.8 21G725 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
Ooops, I've pushed the whole queue, repushed

**Comment by pmetzger** [comment]
@catap This is clearly your show, right? There's no one in a better position to review this stuff than you, so should we just commit when it's done?

**Comment by catap** [comment]
@pmetzger yes, I'll be very appricieted. I do have one more huge bulk of commits with some lisp dependencies... and after that MacPorts has majority of popular lisp libraries :)

**Comment by catap** [comment]
@pmetzger, @herbygillot, @mascguy this is ready as it can be. May I ask you to merge it?

**Pull request merged**
