### PR TITLE
hevea: update to 2.36, allow build on PPC

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update to current version. Use `byte` target for PPC until `ocamlopt` is fixed for it.
Fix lint warning, improve alignments, use https for homepage.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
I'd propose we hack the OCaml portgroup to automatically select the byte compiler on PPC. (FWIW, I think the byte compiler is the right solution permanently for PPC; there's no real way given the impending OCaml 5.0 release to maintain the native compiler for PPC.)

**Comment by barracuda156** [comment]
@pmetzger Sounds good, but will it work, given that target names differ quite randomly? Though perhaps if it can remove opt target and choose whatever left, that could work.

**Comment by mascguy** [comment]
> I'd propose we hack the OCaml portgroup to automatically select the byte compiler on PPC. (FWIW, I think the byte compiler is the right solution permanently for PPC; there's no real way given the impending OCaml 5.0 release to maintain the native compiler for PPC.)

Has this been done already, or...?

**Comment by barracuda156** [comment]
@mascguy PG changes – no. It is non-trivial to implement.

I think this should be made in a separate PR anyway. Nothing stops from updating `hevea` first.

**Comment by barracuda156** [comment]
@aom @evanmiller So, `aom` 3.6.0 does build with `gcc7` on Tiger. Whether to enable it or not, you guys decide.

**Comment by mascguy** [comment]
> @aom @evanmiller So, `aom` 3.6.0 does build with `gcc7` on Tiger. Whether to enable it or not, you guys decide.

Great, go ahead and enable then.

**Comment by barracuda156** [comment]
> > @aom @evanmiller So, `aom` 3.6.0 does build with `gcc7` on Tiger. Whether to enable it or not, you guys decide.
> 
> Great, go ahead and enable then.

@mascguy OK. Sorry for replying in a wrong thread, too many tabs opened :)

**Comment by barracuda156** [comment]
@mascguy CIs pass for this. Should we do something else for it?
(Please, leave the PG stuff for later. It may be desirable in principle, but a complicated thing which will require substantial testing.)

**Comment by mascguy** [comment]
You should also rev-bump the two dependents:

```
* coq
* bibtex2html
```

**Comment by barracuda156** [comment]
@mascguy Done, let us see if they build. `coq` is super-outdated in Macports (I have it updated and build fixed locally, but it needs its standard library too, which is not yet done).

**Comment by barracuda156** [comment]
@mascguy So to no surprise, `coq` fails. It will probably fail just as much with an existing `hevea`.

**Comment by mascguy** [comment]
> @mascguy So to no surprise, `coq` fails. It will probably fail just as much with an existing `hevea`.

Okay, so would you prefer to hold off until you can include an update for `coq` too?

**Comment by barracuda156** [comment]
Sure. I will to handle that during the week.

**Comment by pmetzger** [comment]
I'd suggest that we do an update to OCaml 5 as long as we're doing this much archaeology. It shouldn't take too long at this point.

**Comment by mascguy** [comment]
> I'd suggest that we do an update to OCaml 5 as long as we're doing this much archaeology. It shouldn't take too long at this point.

Sounds great to me!

**Comment by barracuda156** [comment]
> I'd suggest that we do an update to OCaml 5 as long as we're doing this much archaeology. It shouldn't take too long at this point.

@pmetzger @mascguy Let me try building it on PPC, that has not been done so far.

**Comment by reneeotten** [comment]
@pmetzger @barracuda156 what's the status here? Please move towards finishing this up or close the PR until you're ready.

**Comment by pmetzger** [comment]
@barracuda156 Let's just do the OCaml 5 update. Do you think you can manage it or do you need my help?

**Comment by barracuda156** [comment]
@pmetzger I need your help with OCaml5. I tried it, apparently the build system changed quite a bit, so it did not work.

The only thing to keep in mind is that any `ppc` (all platforms, since no 32-bit natively with v. 5) and `ppc64` (Darwin only) must build only bytecode target, not native.

**Comment by pmetzger** [comment]
Based on new advice, I've decided we should push off the OCaml 5 update until Q1 of next year. I've updated to 4.14.1

**Comment by pmetzger** [comment]
@barracuda156 I'm going to update Hevea and Coq. After that, if you could do a separate pull request for the Hevea build fixes for ppc I'd appreciate it. I'll post here when I've done that.

**Comment by pmetzger** [comment]
Okay, hevea was updated (though I did not do your ppc hack.) Please do a pull request just for the ppc thing.

**Comment by pmetzger** [comment]
I'll be updating coq shortly hopefully. Closing this now.

**Comment by barracuda156** [comment]
@pmetzger Thank you! Will handle the PR soon then.
We may need an extra fix for Coq too, depending on which version you use.

**Comment by pmetzger** [comment]
I'm having a great deal of trouble packaging the latest Coq regardless right now. You should see that finished within a couple of days I hope.

**Comment by barracuda156** [comment]
@pmetzger Thank you, that would be awesome! Back then I wanted to add a port which depends on Coq, but the lack of standard library turned to be a problem.

P. S. Coq upstream was quite responsive and helpful, just in case.

**Comment by pmetzger** [comment]
They're not responsive and helpful at the moment.

**Pull request closed without merging**
