### PR TITLE
libcaca: remove need for compiler blacklist

### PR DESCRIPTION
**Pull request by evanmiller**
#### Description

This allows building with older Clang, fixes the build with GCC, and generally simplifies the existing workarounds to https://github.com/cacalabs/libcaca/issues/59

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.4.11 8S165 Power Macintosh
Component versions: DevToolsCore-798.0; DevToolsSupport-794.0

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
thanks @evanmiller can you perhaps also traige which of the [Trac tickets](https://trac.macports.org/query?0_port=libcaca&0_port_mode=%7E&0_status=%21closed&col=id&col=summary&col=port&col=status&col=owner&col=type&col=priority&col=time&col=changetime) are still relevant or could be closed?

**Review by mascguy — APPROVED** [review]

**Comment by evanmiller** [comment]
@reneeotten

Close:

https://trac.macports.org/ticket/42124
https://trac.macports.org/ticket/45171

Keep open:

https://trac.macports.org/ticket/63758

Not sure:

https://trac.macports.org/ticket/46939

**Comment by mascguy** [comment]
Given that I'm the one that recently added the compiler blacklisting, it seems only fair that I merge this! LOL

**Comment by mascguy** [comment]
> Close:
> 
> [42124 - libcaca should not depend on port:imlib2](https://trac.macports.org/ticket/42124)

The Mavericks-related ticket (46939) was fixed by my blacklist-related commit a few days ago, so I closed that one too.

However, can you confirm that the imlib2-related ticket should be closed? It looks like there's still a dependency on that port...

**Pull request merged**
