### PR TITLE
grpc: Use cmake build; Update to version 1.36.2

### PR DESCRIPTION
**Pull request by essandess**
grpc: Use cmake build; Update to version 1.35.0
* Use cmake build for grpc dependencies
* Update to version 1.35.0
* Remove obsolete patch files patch-Makefile.diff that don't work with latest version
* Fixes https://trac.macports.org/ticket/62128

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.7 19H114
Xcode 12.3 12C33

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
another massive PR. No interest so far from maintaine in these changes. CI system build failures abound, but the CI system is so unreliable it's impossible to know if that is real or not.

@essandess -- we have about 10 of these massive PRs sitting in the PR queue going back a year or more now. This method of getting massive changes into MacPorts is not working very well, is it?

**Comment by essandess** [comment]
`grpc` needs a cmake build to integrate with other projects. What’s the alternative?

> another massive PR. No interest so far from maintainer in these changes. CI system build failures abound, but the CI system is so unreliable it's impossible to know if that is real or not.
> 
> @essandess -- we have about 10 of these massive PRs sitting in the PR queue going back a year or more now. This method of getting massive changes into MacPorts is not working very well, is it?

**Comment by essandess** [comment]
@emcrisostomo Would you please take a look at this PR? A cmake build is required for `apache-arrow`, itself required by Huggingface 🤗 Transformers, and other AI/ML frameworks?

See https://github.com/macports/macports-ports/pull/8783#issuecomment-750310963

I confirm that it builds and works on my 10.15 box.

**Comment by essandess** [comment]
I have asked for assistance to merge these ML frameworks and their dependencies on other MacPorts channels: e.g., **[Request Merge of Machine Learning Frameworks](https://lists.macports.org/pipermail/macports-dev/2020-October/042494.html)**.

These ML frameworks are large and interdependent. That a PR for a package manager build is also large and interdependent should come as no surprise, and is impossible with a “5 or 10 line change.”

If there’s an alternative to adopting these ML frameworks to MacPorts, I’m not aware of it.

> IMHO -- the PR method is good for small changes. Like a version bump, or adding a variant maybe.
> 
> A 5 or 10 line change that we can check over and commit in 10 seconds (like we do all day long).
> 
> But if you want a 250 to 5000 line change in a port -- nobody is ever going to commit a PR like that. At least -- no body has been. And no surprise, really.
> 
> Maybe those are better worked through in a ticket.
> 
> No doubt many will disagree -- but they are also not committing these massive PRs, going back a year or more now. So the proof, as they say, is in the pudding.

**Comment by kencu** [comment]
Of course it is impossible with a 5 or 10 line change.

What I'm getting at is that trying to do a massive change in a port through a PR is lost cause, because the maintainer, who runs the show, is not going to want to use your PR, and it's too much of a PITA to go back and forth 300 times on a PR to get you to change it the way he wants it. 

Or so it seems, as you have 10 of these going back a year that are not moving.

I am wondering-- thinking -- that this format is not a good one for this. Unless the maintainer takes over the PR completely, and you offer suggestions that the maintainer either does or does not accept.

Like in a ticket.

**Comment by reneeotten** [comment]
what's the benefit here of moving everything into one massive file. I would be in favor of just keeping the Python ports separately as they are now - why doesn't that work?

**Comment by essandess** [comment]
@reneeotten I’ll defer to your Python port mastery, but here are the benefits as I see them to the proposed `py-*` subports:
* Common build approach from source code across all `grpc` ports. Currently, the Python installs come from prebuilt `.whl` files at pypi: https://pypi.org/project/grpcio/#files
* Common versioning, as you point out

These suggested benefits are secondary to the necessity of a cmake build of `grpc`, so I’ll go with whatever approach you say for the Python bindings.

**Comment by reneeotten** [comment]
> @reneeotten I’ll defer to your Python port mastery, but here are the benefits as I see them to the proposed `py-*` subports:
> 
>     * Common build approach from source code across all `grpc` ports. Currently, the Python installs come from prebuilt `.whl` files at pypi: https://pypi.org/project/grpcio/#files
> 
>     * Common versioning, as you point out
> 
> 
> These suggested benefits are secondary to the necessity of a cmake build of `grpc`, so I’ll go with whatever approach you say for the Python bindings.

The Python ports are currently build from the `.tar.gz` file and so from source as far as I can tell. If there are changes needed to the `grpc` port, by all means do make them. I would be in favor of keeping the `py-` ports where they are, and of course feel free to update them. As @kencu also pointed out having small PRs makes the chance that someone will actually look into it/merge much bigger.

**Comment by ryandesign** [comment]
Please make whitespace changes, if they must be made, in a separate commit from functional changes. That makes it easier to review your proposed functional changes.

**Comment by essandess** [comment]
Thanks—done.

> I would be in favor of keeping the `py-` ports where they are

**Comment by essandess** [comment]
Also please note that the current port's Makefile approach is broken and does not work to build the latest `grpc` versions.

Use of the cmake system fixes this issue now and into the future.

> @emcrisostomo Would you please take a look at this PR? A cmake build is required for `apache-arrow`, itself required by Huggingface 🤗 Transformers, and other AI/ML frameworks.
> 
> See [#8783 (comment)](https://github.com/macports/macports-ports/pull/8783#issuecomment-750310963)
> 
> I confirm that it builds and works on my 10.15 box.

**Comment by kencu** [comment]
why the added deps on cctools, ld64, and libunwind?

some of these at least exist in macports:
post-fetch {
     system -W ${worksrcpath}/third_party "git submodule update --init benchmark"
     system -W ${worksrcpath}/third_party "git submodule update --init bloaty"
     system -W ${worksrcpath}/third_party "git submodule update --init envoy-api"
     system -W ${worksrcpath}/third_party "git submodule update --init googleapis"
     system -W ${worksrcpath}/third_party "git submodule update --init googletest"
     system -W ${worksrcpath}/third_party "git submodule update --init libuv"
     system -W ${worksrcpath}/third_party "git submodule update --init protoc-gen-validate"
     system -W ${worksrcpath}/third_party "git submodule update --init udpa"
 }

**Comment by essandess** [comment]
None of these exist as `gRPC_*_PROVIDER` package flags in the cmake build:

https://github.com/grpc/grpc/blob/59c38f4e4daf88062b274c7a4f7bbd5db614ef3a/CMakeLists.txt#L72-L88

> some of these at least exist in macports:
> post-fetch {
> system -W ${worksrcpath}/third_party "git submodule update --init benchmark"
> system -W ${worksrcpath}/third_party "git submodule update --init bloaty"
> system -W ${worksrcpath}/third_party "git submodule update --init envoy-api"
> system -W ${worksrcpath}/third_party "git submodule update --init googleapis"
> system -W ${worksrcpath}/third_party "git submodule update --init googletest"
> system -W ${worksrcpath}/third_party "git submodule update --init libuv"
> system -W ${worksrcpath}/third_party "git submodule update --init protoc-gen-validate"
> system -W ${worksrcpath}/third_party "git submodule update --init udpa"
> }

**Comment by kencu** [comment]
libuv certainly exists in macports.

and no doubt others.

**Comment by essandess** [comment]
I confirm a successful build of `grpc` using MacPorts `libuv`. I've added this dependency.

> libuv certainly exists in macports.
> 
> and no doubt others.
> 
> edit -- oh you meant that grpc is unable to use a system libuv? If so, that is unfortunate, as it has that capabilty for many other packages, it seems, and that would be -- odd.

**Comment by essandess** [comment]
@kencu May we please merge this requirement for upstream PRs?

**Comment by essandess** [comment]
`grpc` is now at version 1.36.2 and this PR builds it robustly. May we please merge after the CI confirms?

**Comment by essandess** [comment]
@emcrisostomo @reneeotten @kencu

I've updated this PR and all the Python bindings to version 1.36.2.

Please note that I've put the Python bindings in the same Portfile.

To keep up with the upstream build process and be able to build from source, as well as ease of maintenance, it's necessary to combine the Python bindings as subports.

**Comment by cjones051073** [comment]
@essandess as others have noted it is difficult to review PR like this that make a lot of changes, so please in future try and minimise the changes each PR makes as much as possible. Whitespace changes for instance should not be made at the same time as real functional changes, so please try and avoid doing this. Reordering things, or reindenting should be left to separate  PRs.

that said, this PR is now starting to hold up a number of others, and as it seems to pass the build tests I am going to be the one who jumps and merges it. Please be ready though to help address any issues that come up.

**Comment by essandess** [comment]
> Please be ready though to help address any issues that come up.

Thanks—sure thing.

**Comment by cjones051073** [comment]
@essandess There are problems with builds on older OSes that use macports clang 9.0

https://build.macports.org/builders/ports-10.6_i386-builder/builds/28170/steps/install-port/logs/stdio

```
error: invalid argument '-std=c++11' not allowed with 'C'
```

thats indeed a real bug in the cmake configuration for C builds. Can you take a look please.

**Comment by ryandesign** [comment]
Looks like yet another python module using C++ despite the fact that distutils and setuptools do not support writing modules in C++.

**Comment by essandess** [comment]
Here's the line:

https://github.com/grpc/grpc/blob/53ba4a101e80e1a67d4ec741b7e1aad6ea8d790f/setup.py#L230

The options I see are:
1. patch out this line and hope for the best
2. On older systems, go back to the pre-compiled `.whl`'s provided at [PyPi](https://pypi.org/project/grpcio/#files).
3. Kick this upstream

I have neither access to older macOS, not familiarity with the nuances of C++ library choices, so will need some guidance here.

**Comment by cjones051073** [comment]
I would go with 1. (but also try 3.). Most compilers default to at least c++11 these days, and certainly those we use once c++11 or newer is specified, so patching that line to remove it should still work, as the compiler will anyway default to supporting at least c++11.

**Comment by kencu** [comment]
You don't really need an old OS to test this fix and this up -- just force the build to clang-9.0 and you'll presumably get the same errors.

**Comment by essandess** [comment]
> You don't really need an old OS to test this and fix this up -- just force the build to clang-9.0 (or 10, or 11, or ...) and you'll presumably get the same errors.

How does one do that?

**Comment by cjones051073** [comment]
> > You don't really need an old OS to test this and fix this up -- just force the build to clang-9.0 (or 10, or 11, or ...) and you'll presumably get the same errors.
> 
> How does one do that?

```
sudo port -s -v build grpc configure.compiler=macports-clang-9.0
```

**Comment by cjones051073** [comment]
Actually, remove the `-s` as that seems to cause issues....

**Comment by kencu** [comment]
Apple's fork of clang has a lot of these irritating errors turned off. They let the llvm clang's get several years ahead of them, get all these errors weeded out of the common source trees out there, and then they eventually turn these errors on in Xcode clang, often years afterwards.

**Comment by kencu** [comment]
well I guess I'm wrong... I don't see that error building 
```
sudo port -v build py38-grpcio configure.compiler=macports-clang-9.0
```
on Catalina after all. Huh.

**Comment by kencu** [comment]
That build line seems different:
```
/opt/local/bin/clang-mp-9.0 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -D_WIN32_WINNT=1536 -DOPENSSL_NO_ASM=1 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) PyObject* -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -I/opt/local/include -I/opt/local/include/re2 -I/opt/local/include/openssl -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -I/opt/local/include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c third_party/address_sorting/address_sorting.c -o python_build/temp.macosx-10.15-x86_64-3.8/third_party/address_sorting/address_sorting.o -stdlib=libc++ -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
```

vs

```
/opt/local/bin/clang-mp-9.0 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -arch i386 -isysroot/ -D_WIN32_WINNT=1536 -DOPENSSL_NO_ASM=1 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) PyObject* -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -I/opt/local/include -I/opt/local/include/re2 -I/opt/local/include/openssl -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -I/opt/local/include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c third_party/address_sorting/address_sorting.c -o python_build/temp.macosx-10.10-i386-3.8/third_party/address_sorting/address_sorting.o -std=c++11 -stdlib=libc++ -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
error: invalid argument '-std=c++11' not allowed with 'C'
```

**Comment by essandess** [comment]
> I would go with 1. (but also try 3.). Most compilers default to at least c++11 these days, and certainly those we use once c++11 or newer is specified, so patching that line to remove it should still work, as the compiler will anyway default to supporting at least c++11.

Option 1 not looking so promising, at least with a standard `port destroot py39-grpcio`. Here's what I see, patch and error log attached:
* [patch-setup.py.diff.txt](https://github.com/macports/macports-ports/files/6214904/patch-setup.py.diff.txt)
* [main.log](https://github.com/macports/macports-ports/files/6214902/main.log)

**Comment by essandess** [comment]
> Looks like yet another python module using C++ despite the fact that distutils and setuptools do not support writing modules in C++.

I'm honestly not cognizant of the setuptools/C++ issues here to post an issue upstream other than say, "hey this thing doesn't build on older [possibly unsupported] clangs."

What, technically, is the issue with `grpcio`?

If someone needs `grpcio` on an older system, we can always go with the 2d option above.

**Comment by cjones051073** [comment]
> > Looks like yet another python module using C++ despite the fact that distutils and setuptools do not support writing modules in C++.
> 
> I'm honestly not cognizant of the setuptools/C++ issues here to post an issue upstream other than say, "hey this thing doesn't build on older [possibly unsupported] clangs."
> 
> What, technically, is the issue with `grpcio`?

the issue is very simple.

invalid argument '-std=c++11' not allowed with 'C'

That argument should not be used with clang (as opposed to clang++) to build c sources.

> If someone needs `grpcio` on an older system, we can always go with the 2d option above.

**Comment by cjones051073** [comment]
> > > Looks like yet another python module using C++ despite the fact that distutils and setuptools do not support writing modules in C++.
> > 
> > 
> > I'm honestly not cognizant of the setuptools/C++ issues here to post an issue upstream other than say, "hey this thing doesn't build on older [possibly unsupported] clangs."
> > What, technically, is the issue with `grpcio`?
> 
> the issue is very simple.
> 
> invalid argument '-std=c++11' not allowed with 'C'
> 
> That argument should not be used with clang (as opposed to clang++) to build c sources.

or, in fact with gcc (as opposed to g++)

> 
> > If someone needs `grpcio` on an older system, we can always go with the 2d option above.

**Pull request merged**
