### PR TITLE
shtools: Fix home page only

### PR DESCRIPTION
**Pull request by Dave-Allured**
#### Description

Fix home page only.  Skip CI.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

Portfile doc only.  Not tested.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by MarkWieczorek** [comment]
Thanks for looking into this, even though it's still failing... Do you have any idea on how to debug this? If there is something wrong with the new Meson build backend, we could open an issue with them.

**Comment by Dave-Allured** [comment]
Mark, my initial purpose was only to fix the homepage link, after upstream
split off the fortran version into a separate home page.

I do not understand your failing build scenario.  Can you explain a little
more?  Macports builders show good builds all the way from 10.7 through
14/Sonoma.
https://ports.macports.org/port/shtools/details/

I suggest updating the portfile to the latest shtools version, currently
showing as 4.11.0 on livecheck.  The current portfile is several releases
older.  There may be some build improvements in the latest version.

**Comment by MarkWieczorek** [comment]
Sorry about the "build failure" comment. I mistakenly responded to a different issue here. My bad...

**Comment by Dave-Allured** [comment]
Correction.  I mistyped, the latest upstream version is 4.11.10.

**Pull request merged**
