### PR TITLE
qscintilla-qt5: remove rpath from install_name

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
Currently the library installed by `qscintilla-qt5` (i.e. `libqscintilla2_qt5.15.0.0.dylib`) uses ```@rpath```:
```
otool -L /opt/local/libexec/qt5/lib/libqscintilla2_qt5.15.0.0.dylib | head -n 2
/opt/local/libexec/qt5/lib/libqscintilla2_qt5.15.0.0.dylib:
	@rpath/libqscintilla2_qt5.15.dylib (compatibility version 15.0.0, current version 15.0.0)
```

this results in issues when [trying to import `py38-qscintilla-qt5`](https://trac.macports.org/ticket/60796) and in [`octave`](https://trac.macports.org/ticket/60845).

This PR changes `@rpath` to `/opt/local/libexec/qt5/lib/`. Re-building `py38-qscintilla-qt5` after this changes resolves that ticket (and presumably the one for `octave` as well). If this is the appropriate fix for a situation like this, then all ports that depend on `qscintilla-qt5` will need a rev-bump.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.6 18G5033
Xcode 10.3 10G8

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
in the  qscintilla.pro file, the author added an install_name_tool coomand recently to force rpath use.

we should just patch that out again I think.

**Comment by reneeotten** [comment]
> in the qscintilla.pro file, the author added an install_name_tool coomand recently to force rpath use.
> 
> we should just patch that out again I think.

thanks @kencu I just read your reply on Trac - I'll take another look at it.

**Comment by reneeotten** [comment]
okay, just removing these few lines from ` qscintilla.pro` indeed solves the problem. So this issue is likely also happening for `qscintilla-qt4`, which means rev-bumping all ports that depend on either of them... Should I try and identify which ports need to be rev-bumped and add them to this PR?

**Comment by kencu** [comment]
Looks like qt4 has the same trouble, yes:
```
$ otool -L /opt/local/libexec/qt4/lib/libqscintilla2_qt4.15.0.0.dylib
/opt/local/libexec/qt4/lib/libqscintilla2_qt4.15.0.0.dylib:
	@rpath/libqscintilla2_qt4.15.dylib (compatibility version 15.0.0, current version 15.0.0)
```

**Comment by kencu** [comment]
If you are able commit the revbumps I'd just go ahead and do it rather than waste time and cibot cycles.

**Comment by reneeotten** [comment]
@Veence @i0ntempest @dstrubbe I've rev-bumped ports you maintain for the change in `qsintilla-{qt4|qt5}` - can you please verify this works?

**Comment by i0ntempest** [comment]
Thanks, if this reverts the rpath change I should be able to remove rpath set in my portfile as well.

**Comment by reneeotten** [comment]
> Thanks, if this reverts the rpath change I should be able to remove rpath set in my portfile as well.

I didn't notice that in the Portfile.... do you just want me to remove the line(s) below as part of this PR?
```
cmake.install_rpath-prepend \
                    ${qt_libs_dir} ${prefix}/lib
```

**Comment by i0ntempest** [comment]
> I didn't notice that in the Portfile.... do you just want me to remove the line(s) below as part of this PR?
> 


That would be great, but not that line. You want to remove `QMAKE_RPATHDIR+=${qt_libs_dir}`. I haven't changed the code for linux since I take this over.

**Comment by michaelld** [comment]
Thinking we want to also comment out `Python/configure.py:1520` : `QMAKE_RPATHDIR += $$[QT_INSTALL_LIBS]`. This Python script generates QMake code. I'm testing this right now in addition to the tweak in this PR.

**Comment by reneeotten** [comment]
> Thinking we want to also comment out `Python/configure.py:1520` : `QMAKE_RPATHDIR += $$[QT_INSTALL_LIBS]`. This Python script generates QMake code. I'm testing this right now in addition to the tweak in this PR.

thanks @michaelld  for looking at it! It appears to work for me without changing that (probably it just doesn't hurt to add this to `QMAKE_RPATHDIR`), but perhaps it can be indeed removed.

**Comment by michaelld** [comment]
the Python change isn't required

**Comment by michaelld** [comment]
the only change that's required is the one to the `.pro` file ... and, this does the trick in my testing ... thanks!

**Comment by michaelld** [comment]
In my testing, the PR's changes do the trick, and none of the installed files contain any "rpath" or equivalent that I can track down.

@i0ntempest  @kencu can you elaborate on whatever changes you were proposing beyond those in this direct PR?

**Comment by reneeotten** [comment]
> In my testing, the PR's changes do the trick, and none of the installed files contain any "rpath" or equivalent that I can track down.
> 
> @i0ntempest @kencu can you elaborate on whatever changes you were proposing beyond those in this direct PR?

I don't think either of them are suggesting other changes. The only thing that apparently can be removed from the `sqlitebrowser` port after this change is the line `QMAKE_RPATHDIR+=${qt_libs_dir}`. But @i0ntempest can do that later as well and I think we should just merge this...

**Comment by kencu** [comment]
I see no issues, but if there are some rpath search path additions that have been added to ports to fix this issue before, they should be removed in this PR otherwise those ports will need yet another revbump when they are removed.

**Comment by reneeotten** [comment]
> I see no issues, but if there are some rpath search path additions that have been added to ports to fix this issue before, they should be removed in this PR otherwise those ports will need yet another revbump when they are removed.

wouldn't`QMAKE_RPATHDIR+=${qt_libs_dir}` be a harmless thing to set in a Portfile (i.e., why would a rev-bump be needed to remove this form a Portfile)?

**Comment by michaelld** [comment]
I believe that so long as to a project there is no `rpath` being used -- either directly (what Qsci is nominally doing on macOS) or indirectly (via a dependency) -- then setting `QMAKE_RPATHDIR` does nothing since there is no rpath substitution for QMake to do.

**Comment by michaelld** [comment]
IMHO: If some dependency has an rpath patch (adding or removing the use of such), then we should consider dealing with that too (per my prior comment). That said, I think this PR stands alone in that regard ... that it's up to those ports themselves to deal with this patches.

**Comment by michaelld** [comment]
Hence I'm going to merge this in since it's blocking other ports from working.

**Comment by kencu** [comment]
> wouldn't`QMAKE_RPATHDIR+=${qt_libs_dir}` be a harmless thing to set in a Portfile (i.e., why would a rev-bump be needed to remove this form a Portfile)? Of course I can certainly make the change now to `sqlitebrowser` and then this would be ready-to-go, I am just trying to understand...

The principle is that the files installed by the current Portfile and files on the buildbot have to exactly match. Otherwise, all kinds of unexpected things can happen that are simply impossible to debug.

Once you remove `QMAKE_RPATHDIR+=${qt_libs_dir}`  the executables will no longer be built with that rpath search path added to them. So they are different than the files currently installed by the buildbot, and they will need to be revbumped again. Would this change "really" matter -- it's very hard to say with complete certainty, as these things are surprisingly complex sometimes. So we revbump.

I was just trying to avoid two revbumps to the same port(s) in the same day, which is inefficient.

**Comment by michaelld** [comment]
Makes sense! I _think_ once the dependency that provides an `rpath` is taken care of, then it's really up to the project using the dependency on how to handle itself with respect to `rpath`. The rev-bumps here will take care of the dependency `rpath` issue ... but. If the project itself also uses `rpath` internally then that's a separate issue IMHO. I guess we'll see!

**Comment by michaelld** [comment]
I do agree that avoiding 2 rev-bumps is desirable!

**Pull request merged**
