### PR TITLE
pkgconf: update to 2.1.1

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with ~`sudo port -vst install`~ `sudo port -d destroot`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by TheRealKeto** [comment]
`master_sites` entry is updated. Upstream recommends getting tarballs from https://distfiles.ariadne.space/pkgconf/.

**Comment by herbygillot** [comment]
> `master_sites` entry is outdated. Upstream recommends getting tarballs from https://distfiles.ariadne.space/pkgconf/.

Thank you @TheRealKeto. Can you link where this is stated?

**Comment by TheRealKeto** [comment]
> Thank you @TheRealKeto. Can you link where this is stated?

[Upstream has this on their README](https://github.com/pkgconf/pkgconf?tab=readme-ov-file#release-tarballs).

**Comment by herbygillot** [comment]
> > Thank you @TheRealKeto. Can you link where this is stated?
> 
> [Upstream has this on their README](https://github.com/pkgconf/pkgconf?tab=readme-ov-file#release-tarballs).

OK great, my fault for missing that. Thanks.

**Pull request merged**
