### PR TITLE
frescobaldi: update to 3.3.0

### PR DESCRIPTION
**Pull request by dliessi**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G14042 x86_64
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by kencu** [comment]
qt4-mac builds on all systems! It runs under Rosetta on arm64 systems.

**Comment by reneeotten** [comment]
> qt4-mac builds on all systems! It runs under Rosetta on arm64 systems. 

I see... my bad: the problem is the the poppler-qt4-mac port that fails everywhere except for a handful of old OSes. If that's not fixable this port should probably reflect that.

**Comment by kencu** [comment]
I set up that port some years ago and haven’t looked at it in a long time… let me see what’s going wrong with it.

**Comment by kencu** [comment]
this is the error discussion upstream:

https://gitlab.freedesktop.org/poppler/poppler/-/issues/1060

**Comment by kencu** [comment]
fixed:

https://github.com/macports/macports-ports/commit/dcfcfa91dbbfeb6bd7bcf19cd45453bdd2ba0b24

**Pull request merged**
