### PR TITLE
nco: update to 4.7.9

### PR DESCRIPTION
**Pull request by thiagoveloso**
###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.3
Xcode 10.1

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by thiagoveloso** [comment]
Reverting back to 4.7.7.

**Comment by mojca** [comment]
Out of curiosity: why did you make the revert commit?

**Comment by thiagoveloso** [comment]
In order to avoid conflicts. I thought the maintainer might be working on the same stuff.

**Comment by mojca** [comment]
I mean: if your plan was to close the commit, you could have simply closed it, without the need to apply another commit on top. Also, the maintainer would not be affected in any way as long as he wasn't using your fork directly. If your plan was to fix it (you opened #3731 later with the same request), the idea would be to fix your branch and keep **this** PR open instead of opening a new one. A pull requests consists of everything you push to a particular branch, so you can always modify the contents at any time. You can also modify old commits.

Are you using command line to push to branches or are you using the GitHub's user interface?

I noticed that you used the master branch in #3731. This is generally a very suboptimal practice. By far the easiest workflow is that the master branch in your repository follows the master branch in upstream, pretty much intact. Then you make one new branch for every pull request you might have. For example, you could make a branch called `nco-4.7.9`, push that one branch to your fork and open the PR from that branch. If you use the `master` branch, you'll run into troubles as soon as you'll want to open another pull request for another port. Or, more commonly, users then pull from upstream repository and then end up in some merge hell after their `master` branch no longer corresponds to what's in upstream.

Even if you completely screwed up, you could still locally delete that special branch, create a new one with the same name, edit the contents until you are happy, and force push again, and the original pull request will contain your latest fixes.

You may leave the `master` branch for now for that one PR, just be super careful about what you do with it. If you happen to pull from upstream master, at least do `git pull origin master --rebase`.

**Comment by thiagoveloso** [comment]
Thanks for all the hints @mojca. Truth is: I love MacPorts but I am not very familiar with GIt. I usually try a new port on my computer first and use GitHub's web interface to make small edits to portfiles, but it's definitely not very convenient when something goes wrong and needs to be fixed. I know, I know... I guess I'll have to take a command-line git tutorial before messing up with any port again.

**Comment by pmetzger** [comment]
@kencu Where will you be putting that documentation longer term? It's too good to leave in a comment forever.

**Comment by thiagoveloso** [comment]
That is an awesome resource @kencu, thanks for putting it together. It's already saved in my `Guides` folder.

It should definitely be published somewhere, perhaps in Chapter 7 [here](https://guide.macports.org/#project) ?

**Pull request closed without merging**
