### PR TITLE
add ffmpeg pixeldensity patch for retina

### PR DESCRIPTION
**Pull request by i3roly**
this adds the retina pixel density capability for ffmpeg.

the team doesn't want to add this patch so i think it would be a nice "feature add" for macports users.

i have to apply this patch every time there is an update so i want my life to be easier. this patch is worth it.

credit goes to daniel kaiser: https://fftrac-bg.ffmpeg.org/ticket/7045

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.15.7 19H2026 x86_64
Xcode 12.1.1 12A7605b

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by aeiouaeiouaeiouaeiouaeiouaeiou — CHANGES_REQUESTED** [review]
You have not added these patches and comments to the Portfile. Also, all ports should be tested locally.

**Comment by i3roly** [comment]
i did test them. what kind of answer is that.

didn’t you read my post? i said “i am tired of applying the patch when there’s an update”.

no wonder that donkey @rjvb feels like an allstar.

whatever. don’t use it. i’ll just keep port -v build’ing, interrupting, CDing into the work directory, applying the patch and finishing build and then destroot+installing.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@i3roly MacPorts is a friendly community, please don't be rude.

All you need to do is add
`patchfiles-append   patch-add-pixeldensity.diff`
after ~103 line in `multimedia/ffmpeg/Portfile` and `multimedia/ffmpeg-devel/Portfile`, and increase the number on `revision` lines. Without this, the patches will not have any effect.

**Comment by i3roly** [comment]
done. please give it a go

**Comment by reneeotten** [comment]
what is the reason that upstream doesn't accept such patch: do they not agree on the correctness of the patch or is it a feature they don't want to support? Please add some context in the header of the patchfile(s), with links to upstream tickets/discussion/PR and so on. Ideally, we don't want to carry patches like this forward in MacPorts, but we'll let the maintainers chime in on that.

**Comment by i3roly** [comment]
again, these responses are showing why we are getting beat by brew.

did you read my first post? i showed the bugtracker post referencing the original ticket.

i have no explanation as to why they won’t. probably because APPUL users deserve to be abused, though

https://ffmpeg.org/pipermail/ffmpeg-devel/2024-July/331470.html

this is outrageous.

**Comment by reneeotten** [comment]
@i3roly I don't know what part you think is outrageous... nobody is going to look back at this PR in two years time, so please add the pertinent information into the patchfiles. 

Secondly, new contributors are very welcome but perhaps tone down your responses a bit and behave like a decent community member; for someone who just opened his second PR in the project you seem to have a bit too much attitude...

**Comment by i3roly** [comment]
a “long view” coming from a participant who didn’t care to read the original post, and then decides to lecture me.

we’re getting worked so badly and it doesn’t seem to be getting better.

do what you want.

please, by all means, continue to harm potential growth opportunities for this package manager out of your preference to espouse platitudes contradicted by your lack of critical thinking.

**Comment by i3roly** [comment]
who does this person think he is? he's not even a maintainer and he thinks he has the authority to close a ticket.

lol

**Pull request closed without merging**
