### PR TITLE
beets: switch to python 3.10, part 1

### PR DESCRIPTION
**Pull request by catap**
#### Description

Here the first part of switching beets to python 3.10; it adds to all required python modules py310 subports.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.6 20G165 x86_64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by amake — APPROVED** [review]

**Comment by catap** [comment]
Rebased to last master to re-run CI.

**Comment by catap** [comment]
```
  Total number of ports parsed:	275 
  Ports successfully parsed:	275 
```
... seems that the only way to pass CI it is split this PR into a few smaller PR.

@pmetzger shall I split it?

**Comment by pmetzger** [comment]
Yah, I would do the py-* port updates to 3.10 individually.

**Comment by catap** [comment]
@pmetzger let me remove the last commit when :)

**Review by mascguy — APPROVED** [review]

**Comment by catap** [comment]
@pmetzger  / @mascguy what should I do with this PR? CI is failed because it is too long. I can split it to dozen of dedicated PR, or it can be merged as is.

**Comment by mascguy** [comment]
> @pmetzger / @mascguy what should I do with this PR? CI is failed because it is too long. I can split it to dozen of dedicated PR, or it can be merged as is.

Given how many great contributions you've made, I'm more than happy to test these locally. I'll try to do that tonight, if possible.

Assuming everything builds successfully, I'll merge after that's done.

**Comment by catap** [comment]
@mascguy thanks!

You may use this branch https://github.com/catap/macports-ports/tree/beets-python310 which contains the one more commit with `beets` which was switched to python-3.10. You can use it to easy setup everything that I've changed here.

Thus, I can move this commit back to have delivered all this changes in one shot.

**Comment by mascguy** [comment]
> You may use this branch https://github.com/catap/macports-ports/tree/beets-python310 which contains the one more commit with `beets` which was switched to python-3.10. You can use it to easy setup everything that I've changed here.
> 
> Thus, I can move this commit back to have delivered all this changes in one shot.

Sounds great, that will make it much easier to install all of these ports at once!

**Comment by catap** [comment]
@mascguy let me then return the beets commit back to this PR

**Review by reneeotten — CHANGES_REQUESTED** [review]
are all these added py310 subports tested in that they either pass the test-phase if present in the Portfile or upstream has declared support for Python 3.10?  I don't think we want to en mass add subports without at least doing some basic tests to make sure they actually work.

**Comment by catap** [comment]
@reneeotten I've installed `beets` from this branch and it works for a while. Also, `beets` had added to its CI py310 and it works and passes all tests.

I also did some basic tests for all added subports.

If you have any idea, I'd love to hear that.

**Comment by catap** [comment]
@reneeotten I can split this PR to dozen of dedicated PR. Did it make any differences for you?

**Comment by mascguy** [comment]
> @reneeotten I can split this PR to dozen of dedicated PR. Did it make any differences for you?

@reneeotten It's up to you how we proceed. But I'm going to try my best to assist Kirill, relative to pre-validating all of this before merge. And I'll gladly run the embedded port tests across-the-board, on all of the new Python ports.

But you make a great point, that we should double-check that all of these support Python 3.10.

Thoughts?

**Comment by reneeotten** [comment]
> @reneeotten I've installed beets from this branch and it works for a while. Also, beets had added to its CI py310 and it works and passes all tests.

That's a good start and at least means that the ports will install and their functionality -as far as used by `beets` and covered by that tests-suite` likely works.

> @reneeotten I can split this PR to dozen of dedicated PR. Did it make any differences for you?

No, the issue is not *how* the ports get added and I am sure if the CI would be able to finish they would all *build* correctly. The question is whether they work as intended with Python 3.10 and the only way to verify that is to run the test-suites locally (provided that they are set-up in the Portfile) and/or verify that upstream tests against Python 3.10 or declares compatibility. That is a lot of work, but should ideally be done which is typically why new subports get added gradually over time. This is one of the reason I/we encourage people set-up a test-phase when they add a new port or include one when updating existing ports; so that this can be more easily verified within the context of MacPorts.

**Comment by catap** [comment]
@reneeotten what we/I should do with all this changes? I've splitted all commits per branch https://github.com/catap/macports-ports/branches/all?query=py- but open a dozen of PR seems for me as very bad idea.

From other hand, anyone can install beets and test it to confirm that it is at least works some how.

As proof that I've tested it you may see that I've added some patches inside `py-unicodedata2: add py310 subport` and all this changes was backported to upstream and already merged into its master.

**Comment by mascguy** [comment]
> @reneeotten what we/I should do with all this changes? I've splitted all commits per branch https://github.com/catap/macports-ports/branches/all?query=py- but open a dozen of PR seems for me as very bad idea.
> 
> From other hand, anyone can install beets and test it to confirm that it is at least works some how.
> 
> As proof that I've tested it you may see that I've added some patches inside `py-unicodedata2: add py310 subport` and all this changes was backported to upstream and already merged into its master.

Kirill, Renee is asking that you go through the list of Python subports that you're changing, and verify that each officially supports Python 3.10. Sometimes this is as easy as going to PyPi.org, and checking the page for each. Alternatively, you may need to check the project site - whether on GitHub, or wherever - and check there.

Renee, would you agree? And is there a better place to check for Python 3.10 compatibility?

**Comment by catap** [comment]
@mascguy not all this ports are declared support of Python 3.10 via pypi or its project's homepage; thus some of them isn't active enough.

:(

**Comment by catap** [comment]
@reneeotten / @mascguy and sorry guys, I'm in middle of bureaucracy paper hell in real life, and I can be a lot of inadequate because this hell affect me a lot.

**Comment by mascguy** [comment]
> @reneeotten / @mascguy and sorry guys, I'm in middle of bureaucracy paper hell in real life, and I can be a lot of inadequate because this hell affect me a lot.

No worries Kirill, we'll do our best to help you with all of this!

**Comment by reneeotten** [comment]
There will for sure be ports that are not actively developed (and or maintainers don't care enough about updating classifiers, so the PyPI listings are often unreliable) for which it will be hard to figure out if they "officially" support Python 3.10.

I am not criticizing you for adding these subport @catap and this is an issue that comes up every time a new Python versions gets released: do we just "blindly" add the new subports and hope they work or do we do this carefully and try to run the test-suites and look at upstream for indications of support/potential trouble first. The latter approach would be preferred and for inactive projects we might just go for option 1 and assume since they are used successfully elsewhere as dependencies it's probably okay. 

Finally, I'd like to note that there is no rush to move `beets` or anything else now to Python 3.10 - it will likely works perfectly fine with Python 3.9 for many years to come. So there is time to investigate individual Python packages in the correct way and add py310 subports where possible and make the switch to Python 3.10 once that is completed.

**Comment by catap** [comment]
@reneeotten just for you information: `beets` should have a new release with official python 3.10 support in next few days ;) https://github.com/beetbox/beets/discussions/4144

**Comment by reneeotten** [comment]
> @reneeotten just for you information: `beets` should have a new release with official python 3.10 support in next few days ;) [beetbox/beets#4144](https://github.com/beetbox/beets/discussions/4144)

That's great! However all of what I said above still applies ;)

**Comment by catap** [comment]
@reneeotten I never dissmised it ;) and I agree that migraption from pyX to pyY is pain and I haven't got any solution for this one.

**Comment by catap** [comment]
@reneeotten / @mascguy I've removed a commit which is switched version of beets from this PR.

Anyway, I've tried to enabled / run unit test on all affected ports.

Summary:
 - tested by hand: `py-acoustid`
 - hasn't got tests: `py-flask`, `py-bottlenose`, `py-grapheme`, `py-aubio`, `py-termtables`, `py-ibroadcast`, `py-jsonpath-rw`
 - nose is broken and prevents to run tests: `py-flask-cors`, `py-blinker`, `py-xmltodict`
 - genshi is broken and prevents to run test: `py-html5lib`
 - `py-reflink` tests requires btrf
 - `py-xdg` I can't understand how to enable tests
 - tests are failed on python 3.7 / 3.9: `py-ifaddr`, `py-cached-property`, `py-termplotlib`, `py-fonttools`, `py-ttfquery`
 - all another tests are passed

**Comment by catap** [comment]
@reneeotten / @mascguy I've removed a commit which is switched version of beets from this PR.

Anyway, I've tried to enabled / run unit test on all affected ports.

Summary:
 - tested by hand: `py-acoustid`
 - hasn't got tests: `py-flask`, `py-bottlenose`, `py-grapheme`, `py-aubio`, `py-termtables`, `py-ibroadcast`, `py-jsonpath-rw`
 - nose is broken and prevents to run tests: `py-flask-cors`, `py-blinker`
 - genshi is broken and prevents to run test: `py-html5lib`
 - `py-reflink` tests requires btrfs
 - `py-xdg` I can't understand how to enable tests
 - tests are failed on python 3.7 / 3.9: `py-ifaddr`, `py-cached-property`, `py-termplotlib`, `py-fonttools`, `py-ttfquery`
 - all another tests are passed

**Comment by catap** [comment]
@reneeotten / @mascguy are thoughts?

**Comment by mascguy** [comment]
> Anyway, I've tried to enabled / run unit test on all affected ports.
>     * tested by hand: `py-acoustid`
>     * hasn't got tests: `py-flask`, `py-bottlenose`, `py-grapheme`, `py-aubio`, `py-termtables`, `py-ibroadcast`, `py-jsonpath-rw`
>     * nose is broken and prevents to run tests: `py-flask-cors`, `py-blinker`
>     * genshi is broken and prevents to run test: `py-html5lib`
>     * `py-reflink` tests requires btrfs
>     * `py-xdg` I can't understand how to enable tests
>     * tests are failed on python 3.7 / 3.9: `py-ifaddr`, `py-cached-property`, `py-termplotlib`, `py-fonttools`, `py-ttfquery`
>     * all another tests are passed

Thanks for doing this Kirill!

Maintainers of the various Python ports involved here, what are you thoughts? And @reneeotten, what do you think at this point?

**Comment by catap** [comment]
@mascguy I'm a maintainer for majority of this ports :)

Anyway, adding tests seems for me as good refactoring, and enable py310 subports isn't something dangerous.

The issue was only with py-unicodedata2 which required a patch. But this patch was already merged to its master and maintaner of this ports approved this PR :)

=> from my point of view we may wait a few more days, and merge it.

**Comment by mascguy** [comment]
Kirill, I just rebased against master, to test our new workflow improvement (auto-cancellation of outdated CI jobs). Otherwise, nothing was changed.

**Comment by mascguy** [comment]
> @mascguy I'm a maintainer for majority of this ports :)
> 
> Anyway, adding tests seems for me as good refactoring, and enable py310 subports isn't something dangerous.
> 
> The issue was only with py-unicodedata2 which required a patch. But this patch was already merged to its master and maintaner of this ports approved this PR :)
> 
> => from my point of view we may wait a few more days, and merge it.

Unless anyone has any strong objection - @reneeotten/anyone? - I'm fine with merging this as-is. It seems like you've done as much research and testing as possible, and that's the key.

Thoughts folks?

**Comment by catap** [comment]
@pmetzger / @reneeotten to prove that the last CI changes works as expected, let me rebase this huge PR ;)

**Comment by mascguy** [comment]
There's been plenty of discussion, review, pre-merge testing, etc. So let's merge.

In the unlikely event that there are any issues with the new Python 3.10 subports, I'll assist with fixing them ASAP.

And thanks again for all of your work Kirill. Great stuff!

**Comment by mascguy** [comment]
Kirill, it looks like there are two more Python ports which need support for 3.10, specifically for Beets: `py-gmusicapi` and `py-responses`. Are those on your to-do list?

**Comment by catap** [comment]
@mascguy `py-gmusicapi` is required for not devel support and needs for this port was remove https://github.com/beetbox/beets/issues/4089 => no need to update.

`py-responses` was added with unit tests and I'll do it right away :)

**Comment by mascguy** [comment]
> @mascguy `py-gmusicapi` is required for not devel support and needs for this port was remove [beetbox/beets#4089](https://github.com/beetbox/beets/issues/4089) => no need to update.
> 
> `py-responses` was added with unit tests and I'll do it right away :)

No rush, just trying to help you prepare for the move to 3.10.  :-)

**Pull request merged**
