### PR TITLE
folly & friends: update to 2024.06.03.00

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update these, finally.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Any idea why macOS-11 fails when everything else works?

**Comment by pmetzger** [comment]
FYI, we are removing MacOS 11 from the CI shortly; GitHub will no longer be providing runners.

**Comment by barracuda156** [comment]
I have, but I have no idea why that error. I tested builds locally on Sonoma and 10.6, all good.

Big Sur was a horrible OS, happy to see it go. (I would rather have a runner on Catalina.)

**Comment by barracuda156** [comment]
@pmetzger Since CI for macOS-11 already gone, I cannot see the result of the change. It might or might not fix the build of `folly` there.

**Comment by barracuda156** [comment]
P. S. lint warnings are bogus: it does not understand that static libs are arch-specific.

**Comment by barracuda156** [comment]
@pmetzger @herbygillot Can be merged now.

If old systems with clangs will need some fix, I will make a follow-up.

**Pull request merged**
