### PR TITLE
php: Add php74 subports

### PR DESCRIPTION
**Pull request by chrisminett**
#### Description

Add php74 subports

- Copy php73 with updated checksums.
- Option for `--without-pear` is not needed for php74, as PEAR is now disabled by default.
- Do not add sub-port for `php74-wddx` which is no longer available in core.
- Update configure options for extensions that have moved to pkg-config. See [PHP 7.4 migration notes](https://www.php.net/manual/en/migration74.other-changes.php#migration74.other-changes.pkg-config)
- pkg-config is added a build dependency for php74-*.
- php74-imap: Fix configure issue for OpenSSL by forcing availability. See [Docker Library issue](https://github.com/docker-library/php/issues/891)
- Fixes https://trac.macports.org/ticket/59815

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G2022
Xcode 11.3 11C29

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
Thanks. The php74* ports installed fine for me in trace mode. I still want to reinstall the previous php versions' ports to make sure nothing has gone wrong there. And I have some commits to add here before this is merged.

**Comment by ryandesign** [comment]
> * pkg-config is added a build dependency for php74-*.

php74-dba built fine for me even if I removed the pkg-config dependency. How did you determine that it was needed?

If it's just the fact that the configure script checks for the existence of pkg-config, then I would probably not consider that sufficient reason to add the dependency.

My assumption is that the pkg-config dependency is only needed on those php74 subports where you had to change the configure args from one that specifies the prefix to one that does not.

That's what I meant by building with trace mode: for each subport that failed to build in trace mode, try adding the pkg-config dependency to that subport.

I'm going to push the additional commits I've made. If you have other changes, you can add your commits as well. We'll squash it down to just 1 commit prior to merging.

**Comment by ryandesign** [comment]
> I'm going to push the additional commits I've made

I tried to do that, but it looks like you've rebased the branch onto a newer master and force-pushed it since I pulled it. But I don't see any differences to your commit that actually added the php74 stuff. So if all you did was rebase and force-push, I can do that again, but from here on out it will be easier to collaborate on this if we don't force-push again.

**Comment by chrisminett** [comment]
> php74-dba built fine for me even if I removed the pkg-config dependency. How did you determine that it was needed?

The first time I ran through all the extensions, that one didn't have the warning about pkgconfig being hidden by trace mode, but after making the changes that you suggested about the position to add the dependency, I ran them all in trace mode again (after uninstalling and cleaning) and this time got the warning for _dba_ too:

```
--->  Computing dependencies for php74-dba
--->  Fetching distfiles for php74-dba
--->  Verifying checksums for php74-dba
--->  Extracting php74-dba
--->  Configuring php74-dba
Warning: The following existing file was hidden from the build system by trace mode:
  /opt/local/bin/pkg-config
--->  Building php74-dba
--->  Staging php74-dba into destroot
Warning: The following existing file was hidden from the build system by trace mode:
  /var/root/.CFUserTextEncoding
--->  Installing php74-dba @7.4.1_0
--->  Activating php74-dba @7.4.1_0
--->  Cleaning php74-dba
```

**Comment by chrisminett** [comment]
> So if all you did was rebase and force-push, I can do that again

I haven't rebased since making the PR. But I did when making the changes from your suggestions on the Trac ticket, so that it was all in a single commit.

Don't have any other changes to add, so it's all yours!

**Comment by ryandesign** [comment]
> Still rebuilding the earlier subports to make sure.

All built fine. I'm ready to merge this.

**Comment by chrisminett** [comment]
> Let me know if you see anything awry with them

All looks good to me.

I see you've gone back to including _pkg-config_ as a dependency only in certain extensions. Does that mean I am misunderstanding the trace output? When I saw the output like I included in the earlier comment about DBA, I took that to mean that it was required. But is it instead OK as long as it still builds successfully? I did notice that some only showed the warning but completed, and others showed the warning and then failed.

Also, once this is merged and php74 is available, how do you usually deal with the non-core extensions? Is it just submitting individual PRs to add compatibility for separate extensions, eg. memcached, xdebug, zip, mailparse, etc. I've found some that are just simple changes to the compatible PHP branches, some that need similar build config changes, and some that need newer source versions.

**Comment by chrisminett** [comment]
Actually, one other thing is about if/when you would change the `php.latest_stable_branch` to 7.4 - does that go as part of adding 7.4, or is it usual practice to allow a new version to be used for a while before marking it?

**Comment by ryandesign** [comment]
> I see you've gone back to including _pkg-config_ as a dependency only in certain extensions. Does that mean I am misunderstanding the trace output? When I saw the output like I included in the earlier comment about DBA, I took that to mean that it was required. But is it instead OK as long as it still builds successfully? I did notice that some only showed the warning but completed, and others showed the warning and then failed.

I added the dependency only where the build would fail if I did not.

It appears that in 7.4 phpize was modified so that the configure scripts it generates check for the existence of pkg-config. All extensions, both bundled and third-party, use phpize, so they will all now check for the existence of pkg-config. But the majority of them won't actually end up using that pkg-config for anything. In those cases, adding the dependency would be superfluous.

On my system, because of the extra ports I have installed, trace mode printed a lot more warnings while building php ports:

```
Warning: The following existing files were hidden from the build system by trace mode:
  /opt/local/bin/ar
  /opt/local/bin/gawk
  /opt/local/bin/ggrep
  /opt/local/bin/nm
  /opt/local/bin/pkg-config
  /opt/local/bin/ranlib
  /opt/local/bin/strip
```

That alone is not a reason to add dependencies on them either. In the case of those other tools, the MacPorts versions will be used if present, and if not, the versions from Xcode or the command line tools will be used.

*Sometimes* a build system will look for an optional library at configure time and, if found, link with it at build time. And pkg-config could certainly be involved in the finding of such a library. Trace mode is great for helping to identify those situations, but that's not the situation here for these php ports.

> Also, once this is merged and php74 is available, how do you usually deal with the non-core extensions? Is it just submitting individual PRs to add compatibility for separate extensions, eg. memcached, xdebug, zip, mailparse, etc. I've found some that are just simple changes to the compatible PHP branches, some that need similar build config changes, and some that need newer source versions.

Usually I add the new branch to all of the third-party extensions locally and try to build them, and I commit those that build, usually all at once (why not). Sometimes it'll take me a little longer to investigate those that failed to build. If you've already done some work on this, feel free to submit a PR, otherwise I'll try to get to them soon.

> Actually, one other thing is about if/when you would change the `php.latest_stable_branch` to 7.4 - does that go as part of adding 7.4, or is it usual practice to allow a new version to be used for a while before marking it?

I was going to push this, make sure it builds on all OS versions, fix any problems that we can see from the buildbot output, and then update the latest stable branch in the portgroup.

**Comment by ryandesign** [comment]
> feel free to submit a PR, 

And if it's just adding 7.4 to php.branches, feel free to group as many ports as you like together in one commit. The Travis build may time out if there are very many, but as long as you've verified locally that they build, that's fine. If updating the version number of a port is needed for 7.4 compatibility, I'd probably do that port in a separate commit.

**Comment by chrisminett** [comment]
Fantastic! Thanks so much for taking the time to explain all the nuances!

I'll get this installed on my machine and revisit the extensions I started looking at. Given time of day now in the UK, it's unlikely to be until the start of next week!!

**Pull request merged**
