### PR TITLE
flang-{15–18}: depend on and use bash

### PR DESCRIPTION
**Pull request by markmentovai**
#### Description

flang-to-external-fc-mp-{15–18} delegates to a bash wrapper script that uses modern bash-isms not supported by bash-3.2 shipped by Apple in /bin. A run-time dependency on the bash port is added, and the wrapper script is patched to use MacPorts’ bash as its interpreter rather than whatever happens to be first in the PATH.

flang-14 is being handled in #26039, and flang-13 was handled in c8ea54857743.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 15.0 24A335 arm64
Xcode 16.0 16A242d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by markmentovai** [comment]
https://github.com/macports/macports-ports/pull/26049#issuecomment-2391795000:
> Not sure why the CI is failing, seems like this should just work(tm). Bonus points for the en-dash in the title.

It’s timing out. Because I wanted to use the en-dash so badly that I combined four packages that take a long time to build into a single pull request.

[lint & build changed ports / macos-12 (pull_request)](https://github.com/macports/macports-ports/actions/runs/11145100676/job/30973895494) → [View raw logs](https://productionresultssa15.blob.core.windows.net/actions-results/96aa05fa-1a63-4dda-b9dd-a1055b34f2c4/workflow-job-run-68ae2b36-89dd-55dc-09eb-5ce01d4cd3c7/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-10-03T17%3A32%3A21Z&sig=dCRd6JrqvT4BYMYZ0GfqJTJv%2BlMb4jLbP5KJfILr%2FZo%3D&ske=2024-10-04T03%3A00%3A35Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-10-03T15%3A00%3A35Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-08-04&sp=r&spr=https&sr=b&st=2024-10-03T17%3A22%3A16Z&sv=2024-08-04):

```
2024-10-02T20:00:52.4876070Z ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
2024-10-02T20:00:52.5128810Z DEBUG: process_cmd aborted: SIGTERM signal received
[…]
2024-10-02T20:00:52.5352580Z Error: Aborted: SIGTERM received.
2024-10-02T20:00:52.5478500Z ##[error]The operation was canceled.
2024-10-02T20:00:52.5926080Z Cleaning up orphan processes
```

It was making good and regular progress up until then (and so were the macOS 13 and macOS 14 runs), but it was over 6 hours. Yup, that’s a timeout.

I did test all four locally.

**Comment by markemer** [comment]
> [#26049 (comment)](https://github.com/macports/macports-ports/pull/26049#issuecomment-2391795000):
> 
> > Not sure why the CI is failing, seems like this should just work(tm). Bonus points for the en-dash in the title.
> 
> It’s timing out. Because I wanted to use the en-dash so badly that I combined four packages that take a long time to build into a single pull request.
> 
> [lint & build changed ports / macos-12 (pull_request)](https://github.com/macports/macports-ports/actions/runs/11145100676/job/30973895494) → [View raw logs](https://productionresultssa15.blob.core.windows.net/actions-results/96aa05fa-1a63-4dda-b9dd-a1055b34f2c4/workflow-job-run-68ae2b36-89dd-55dc-09eb-5ce01d4cd3c7/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-10-03T17%3A32%3A21Z&sig=dCRd6JrqvT4BYMYZ0GfqJTJv%2BlMb4jLbP5KJfILr%2FZo%3D&ske=2024-10-04T03%3A00%3A35Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-10-03T15%3A00%3A35Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-08-04&sp=r&spr=https&sr=b&st=2024-10-03T17%3A22%3A16Z&sv=2024-08-04):
> 
> ```
> 2024-10-02T20:00:52.4876070Z ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
> 2024-10-02T20:00:52.5128810Z DEBUG: process_cmd aborted: SIGTERM signal received
> […]
> 2024-10-02T20:00:52.5352580Z Error: Aborted: SIGTERM received.
> 2024-10-02T20:00:52.5478500Z ##[error]The operation was canceled.
> 2024-10-02T20:00:52.5926080Z Cleaning up orphan processes
> ```
> 
> It was making good and regular progress up until then (and so were the macOS 13 and macOS 14 runs), but it was over 6 hours. Yup, that’s a timeout.
> 
> I did test all four locally.

Cool, I use flang, so I'll give this a try and merge if it works, which I expect it will, as it just adds a bash.

**Comment by markmentovai** [comment]
https://github.com/macports/macports-ports/pull/26049#issuecomment-2392459877:
> Cool, I use flang, so I'll give this a try and merge if it works, which I expect it will, as it just adds a bash.

That’s great, thanks. Note that I also have #26039 for flang-14. It’s broken out separately because it was more involved than the comparatively straightforward changes required for flang-15–18: the existing compiler-rt platform SDK workaround for clang-14 needed to be applied to flang-14 as well.

**Comment by markemer** [comment]
Yeah, they built on my machine too, so I'm gonna merge.

**Pull request merged**
