### PR TITLE
mythtv.28: build fix for x264 build 153+

### PR DESCRIPTION
**Pull request by dbevans**
As of build 153, x264 now supports multibitdepth builds, with a slightly changed API to
request bitdepth during initialization. The previous global variable, x264_bit_depth,
used by mythtv, was removed.

Current x264 build is 157.

This PR backports the upstream ffmpeg fix for x264 153+ to the older embedded
copy of ffmpeg in mythtv.28.

See https://github.com/FFmpeg/FFmpeg/commit/c6558e8840fbb2386bf8742e4d68dd6e067d262e

Author: Luca Barbato <lu_zero@gentoo.org>
Date:   Tue Dec 26 12:32:42 2017 +0100

    x264: Support version 153

    It has native simultaneus 8 and 10 bit support.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.3 18D109
Xcode 10.2 10P107d 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by dbevans** [comment]
This same patch has been applied upstream to mythtv 29 after updating the embedded ffmpeg to version 3.2.
https://github.com/MythTV/mythtv/commit/74fff5c2856d592b8b2dfd41ac5cc08f372a8993.

In mythtv 30, ffmpeg has been updated to version 4.0 which includes these changes without modification.  
https://github.com/MythTV/mythtv/commit/76a78d844cfc3903247e5cc0fae39f3df5549731

**Comment by ctreleaven** [comment]
Unfortunately, I still know next to nothing about pull requests.  Is there a button I'm supposed to click to indicate approval?  "Squash and merge"?  I do indeed approve.

**Comment by dbevans** [comment]
> Unfortunately, I still know next to nothing about pull requests. Is there a button I'm supposed to click to indicate approval? "Squash and merge"? I do indeed approve.

To add your review, click on 'files changed' at the top of this PR and then click on 'Review Changes'.  
You can then enter your comments and select your desired review option (e.g. approve).

To merge this PR, just click on the button on this page that says 'Rebase and merge'.  Squashing refers to combining 2 or more commits into a single one using git rebase -i.  Not necessary in this case since there is only one commit to start with.

**Comment by dbevans** [comment]
Merging with maintainers approval.

**Pull request merged**
