### PR TITLE
java PG: allow port to enforce fallback JVM

### PR DESCRIPTION
**Pull request by catap**
#### Description

Sometimes port hard codedes inside produced artifacts path to used Java, and when build bot installs for example OpenJDK11, and user has OpenJDK 17 it can be a disaster.

To reproduce an issue just try to instal and use `abcl` without `openjdk11`.

If you haven't got any JDK => it will work fine. If you have `openjdk17`, well.. java PG decided that it better than 11 and avoid to add dependency, but build bot builds an artifact which hardcoded paths to `openjdk11` ;)

=> nothing works.

###### Type(s)

- [x] bugfix

###### Tested on

macOS 12.6.8 21G725 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
@breun, @mascguy here the fix for an issue which I thought was triggered by https://trac.macports.org/ticket/67935

**Review by mascguy — APPROVED** [review]
This is a great addition Kirill, thank you!

**Comment by mascguy** [comment]
We currently have a significant CI backlog, so it may be a few hours until these changes are built.

I'll check back over the next few hours though, and merge once CI completes.

**Comment by breun** [comment]
> @breun, @mascguy here the fix for an issue which I thought was triggered by https://trac.macports.org/ticket/67935

@catap I think ports shouldn't hardcode a path to Java, but I don't really see how the fix for https://trac.macports.org/ticket/67935 would have changed anything in this area. Can you elaborate?

**Comment by catap** [comment]
> > @breun, @mascguy here the fix for an issue which I thought was triggered by https://trac.macports.org/ticket/67935
> 
> @catap I think ports shouldn't hardcode a path to Java, but I don't really see how the fix for https://trac.macports.org/ticket/67935 would have changed anything in this area. Can you elaborate?

2) I was wrong, and your fixes are innocent, it is very old bug.

1) Unfortunately this is behaviour of ABCL build script and replacing it might be quite tricky :(

**Pull request merged**
