### PR TITLE
opencascade: Stop using DYLD_LIBRARY_PATH

### PR DESCRIPTION
**Pull request by Dave-Allured**
#### Description

* Stop using DYLD_LIBRARY_PATH
* Also stop using LD_LIBRARY_PATH.
* May fix builds on older systems.

Closes: https://trac.macports.org/ticket/70235

###### Type(s)

- [x] bugfix

###### Tested on

CI Only.  OS 13, 14, 15.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@Dave-Allured It builds fine on old systems but does not work correctly. With `libstdc++` it will probably need `DYLD_LIBRARY_PATH` set to `${prefix}/lib/libgcc:$DYLD_LIBRARY_PATH` (like `legacysupport` does), but at the moment I do not have a ready solution.

**Comment by Dave-Allured** [comment]
@barracuda156 This was a hasty experiment to see whether https://trac.macports.org/ticket/70235 had a simple solution for older OS's.  `Opencascade` seems to be working fine for newer OS's.  Based on that and your comments, I will cancel this PR.

**Comment by kencu** [comment]
@Dave-Allured -- I believe you're on the right track with this. 

It may or may not need something extra added for the libstdc++ based systems, but the basic idea of what you did here seems sound.

**Comment by Dave-Allured** [comment]
Ken, thank you for the encouragement.  I would prefer to leave a more refined solution for `opencascade` up to folks like you and @barracuda156, with far more experience than me, dealing with older systems.

**Comment by barracuda156** [comment]
@Dave-Allured Since what we have now does not, at least in my experience, produce a properly functioning app on PowerPC, I have no objections to modifying it in a way that improves it for x86, whether that it consistent with what PowerPC needs or not.
I will try it with your patch from here in a while.

**Comment by Dave-Allured** [comment]
@barracuda156, I am interested in refining this strategy to stop using `DYLD_LIBRARY_PATH`.  Please let me know how your test works out.  Also let me know if you have any suggestions to improve the patch, of course.

I also need to investigate whether `DYLD_LIBRARY_PATH` should be purged in several other places within `opencascade` source.  Some of those other paces might also have an effect on your current testing.

**Pull request closed without merging**
