### PR TITLE
qt*: fix typo in comment

### PR DESCRIPTION
**Pull request by chrstphrchvz**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
Note that the port maintainer has been unavailable for review: https://github.com/macports/macports-ports/pull/13139#issuecomment-980638649

**Comment by mascguy** [comment]
LGTM. @MarcusCalhoun-Lopez ?

**Comment by mascguy** [comment]
> Note that the port maintainer has been unavailable for review: [#13139 (comment)](https://github.com/macports/macports-ports/pull/13139#issuecomment-980638649)

@pmetzger Perry, is Marcus still unavailable?

**Comment by pmetzger** [comment]
So far as I know, he hasn't indicated that he's available again.

**Comment by pmetzger** [comment]
Given that he isn't available and that this changes nothing but comments I would commit it.

**Pull request merged**
