### PR TITLE
libvirt, py-libvirt: Update to 4.7.0

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

Update libvirt and py-libvirt to 4.7.0.

Add py37-libvirt subport.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.6 17G65
Xcode 9.4.1 9F2000 

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Merged. Thanks as always, @ryandesign!

**Comment by pmetzger** [comment]
If you want a 72 hour wait, then don't mark your port `openmaintainer` and you'll always get one...

**Comment by danchr** [comment]
I, for one, always mark the ports I really don't care that much about as `openmaintainer`. In this case, feel free to adopt it; I essentially wrote it to see if I could get `virt-manager` running on my Mac. I could, and didn't find it all that useful…

It seems rather relevant that the bot marks PRs as `by:member` — if someone already has rights to push a PR, they probably posted it to get feedback.

**Comment by pmetzger** [comment]
Oh, I presumed he wanted another set of eyes. I checked the thing before merging.

**Pull request merged**
