### PR TITLE
py-gevent: update to 22.10.2; add python 3.11

### PR DESCRIPTION
**Pull request by gwerbin**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

```none
macOS 12.4 21F79 arm64
Xcode 13.4.1 13F100
```

###### Verification 

Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] ~~referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?~~ 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by stromnov** [comment]
As far as I remember, new gevent requires cython 3 (py-cython-devel).

**Comment by gwerbin** [comment]
> As far as I remember, new gevent requires cython 3 (py-cython-devel).

I didn't realize we had both `py-cython` and `py-cython-devel`. It looks like the former is just a very old version of Cython?

**Comment by mascguy** [comment]
There's a big, big problem with depending on `py-cython-devel`: That conflicts with `py-cython`, which is used in countless other Python ports.

And unfortunately, dependents declare a direct dependency on `py-cython` - by name, rather than a path dep - precluding users from using the upstream version instead. (I suppose that's fixable by changing the deps to path deps, but keep reading.)

In short, if this port depends on `py-cython-devel`, it basically blocks many other Python ports from being used on a user's system. So If they want to use this port, that precludes virtually everything else.

Andrew, is Cython 3 backward-compatible, such that we could upgrade `py-cython` to it? Or are there breaking changes?

Alternatively, are the upstream package name(s) different, such that we could have `py-cython2` and `py-cython3` installed side-by-side, without conflict?

CC: @Schamschula

**Comment by mascguy** [comment]
> Andrew/Marius, is Cython 3 backward-compatible, such that we could upgrade `py-cython` to it? Or are there breaking changes?

Ugh, no, it looks like breaking changes abound:

https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html

> Alternatively, are the upstream package name(s) different, such that we could have `py-cython` and `py-cython-devel` installed side-by-side, without conflict?

Comparing the contents of `py-cython` vs. `py-cython-devel`, nope, that isn't an option either.

**Comment by mascguy** [comment]
@jmroot and @reneeotten , thoughts/guidance on this PR? (See earlier comments, per woes related to `py-cython` vs. `py-cython-devel`.)

**Comment by gwerbin** [comment]
I'm not sure how to handle this within the Macports system.

Nowadays generally in Python, the Pip package manager uses "build isolation", creating a temporary venv with build-time dependencies in it, which should be declared separately from run-time dependencies (and upstream can be patched to do so if it doesn't currently). So normally your "run" environment (in this case managed by Macports) doesn't ever need to know or care about the "build" environment, and the latter can be fully discarded at the end of the build.

I don't know how the Python PortGroup works internally, but if you run something like this, you should get a clean installation:

```bash
python3 -m venv demo-env
./demo-env/bin/python -m pip install -U pip
./demo-env/bin/pip install -U wheel

wget https://pypi.io/packages/source/g/gevent/gevent-23.7.0.tar.gz
./demo-env/bin/pip install --no-deps ./gevent-23.7.0.tar.gz

./demo-env/bin/pip list
# Package    Version
# ---------- -------
# gevent     23.7.0
# pip        23.2.1
# setuptools 65.5.0
# wheel      0.41.1
```

**Comment by mascguy** [comment]
> Nowadays generally in Python, the Pip package manager uses "build isolation", creating a temporary venv with build-time dependencies in it, which should be declared separately from run-time dependencies (and upstream can be patched to do so if it doesn't currently). So normally your "run" environment (in this case managed by Macports) doesn't ever need to know or care about the "build" environment, and the latter can be fully discarded at the end of the build.

I love the idea of doing that, at least in principle. Though we'd probably only want to enable it via an opt-in approach per-port, to avoid potential breakage.

I'm not sure what type of gotchas come along with that though, particularly in combination with MacPorts trace mode.

CC: @jmroot and @reneeotten , for their thoughts...

**Comment by jmroot** [comment]
> I'm curious why packagers are preferring not to do this. Is it a matter of precisely controlling build dependencies for reproducibility, and not allowing external tools to download them?

Well, I'm curious in turn why the Python packaging community considers it reasonable to have to download and install build dependencies every time you build. :)

Yes, reproducibility is part of it, as is efficiency and reuse, and ability to build offline (all downloads should happen in the fetch phase only). The job of a package manager is to manage packages, and whenever we outsource that to another tool we lose control of and visibility over what is being done. Just as one simple example, what if we needed to patch cython?

There are a few ways of approaching this backwards compatibility break.
 * If the sdist is shipped already cythonised, it should be possible to build without running cython.
 * The two incompatible versions of cython could be installed in different places. One of them would not be in the default search path and so would need to be pointed to with `PYTHONPATH` when needed.
 * If truly necessary, it should be possible to enable the venv-based build isolation with `python.pep517 yes` and `build.cmd-delete --no-isolation`.

**Comment by reneeotten** [comment]
port already update to newer versions in 21d143ab5d574027a53f60a647a6dc536320f7ca after the incompatibility with `Cython` was resolved

**Pull request closed without merging**
