### PR TITLE
R: updates for packages

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Updates

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@cjones051073 Any idea what is going on here? Specifically on Sonoma gcc 13.2.0 paths are used which of course fails:
```
  ld: warning: search path '/opt/local/lib/gcc13/gcc/arm64-apple-darwin23/13.2.0' not found
  ld: library 'emutls_w' not found
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
(So everything which uses `gfortran` does not build.)

**Comment by barracuda156** [comment]
Rebased and rerunning now just to make sure the failure is reproducible.

**Comment by cjones051073** [comment]
> @cjones051073 Any idea what is going on here? Specifically on Sonoma gcc 13.2.0 paths are used which of course fails:
> 
> ```
>   ld: warning: search path '/opt/local/lib/gcc13/gcc/arm64-apple-darwin23/13.2.0' not found
>   ld: library 'emutls_w' not found
>   clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> (So everything which uses `gfortran` does not build.)

well clearly the R packages have backed in some way an (internal) version specific path into their builds, which they should not be using. After the update to 13.3.0 that path is of course now

```
Larissa ~/Projects/MacPorts/ports > ls /opt/local/lib/gcc13/gcc/arm64-apple-darwin23/13.3.0
crt3.o			finclude		install-tools		libgcc_eh.a
crtfastmath.o		include			libcaf_single.a		libgcov.a
crttme.o		include-fixed		libemutls_w.a		libheapt_w.a
crttms.o		include-gnu-runtime	libgcc.a		plugin
```

You need to find a way to prevent R from doing this other wise this will happen on every version bump..

**Comment by cjones051073** [comment]
Perhaps a quick fix would be to rev-bump the R port itself, to force a rebuild of the compiler against the update gcc13 compiler.

Note though, gcc14 is now out so perhaps you would want to move to that at the same time.

Longer term fix - R should not bake paths like this into its build in the first place.

**Comment by barracuda156** [comment]
@cjones051073 What I do not get is why only Sonoma build fails.

> Note though, gcc14 is now out so perhaps you would want to move to that at the same time

That will require revbumping every R port which uses `gfortran`, which is 766 ports.
I am fine with that, but this is a thing to consider.

> Perhaps a quick fix would be to rev-bump the R port itself

Let me try this first.

**Comment by cjones051073** [comment]
> @cjones051073 What I do not get is why only Sonoma build fails.
> 
> > Note though, gcc14 is now out so perhaps you would want to move to that at the same time
> 
> That will require revbumping every R port which uses `gfortran`, which is 766 ports. I am fine with that, but this is a thing to consider.

That is of course a problem in itself. For the vast majority of ports no knowledge of, or need of, the compiler used to build them remains. The compiler can be updated/removed freely. R is really bad in this regard if it really does force a rebuild of everything just because of a compiler update...

**Comment by barracuda156** [comment]
@cjones051073 In this instance it is MacPorts, AFAIU, since all Fortran-using ports are built as `+gcc13`. (But yeah, it was done this way because of `R`.)

**Comment by cjones051073** [comment]
> @cjones051073 In this instance it is MacPorts, AFAIU, since all Fortran-using ports are built as `+gcc13`. (But yeah, it was done this way because of `R`.)

That was to prevent issues when new major gcc versions are added and become the 'default' (such as now with gcc14).

However, it does not help R if it also has issues with minor updates, like gcc13 going from 13.2 to 13.3. 

The underlying issue here is with R, not MacPorts. R bakes too much knowledge of the compilers used to build it into itself, such as the example here. This is what needs to be fixed.

**Comment by barracuda156** [comment]
@cjones051073 Revbumping `R` worked, thankfully.

**Comment by cjones051073** [comment]
> @cjones051073 Revbumping `R` worked, thankfully.

For now… as presumably it has now baked a 13.3.0 specific path into itself…

Long term this should be fixed, properly, as otherwise you will have this issue on every gcc minor update.

**Comment by barracuda156** [comment]
> For now… as presumably it has now baked a 13.3.0 specific path into itself…
> 
> Long term this should be fixed, properly, as otherwise you will have this issue on every gcc minor update.

Yeah, but that is a separate issue to deal with, and not in a hurry.

**Comment by barracuda156** [comment]
@herbygillot @reneeotten This one is good to merge now.

**Comment by kencu** [comment]
I believe I pointed out to you 2 years ago exactly where R bakes it the compiler…

**Comment by barracuda156** [comment]
> I believe I pointed out to you 2 years ago exactly where R bakes it the compiler…

But I don’t recall having issues with minor version before, and even now the issue arose only on arm64.

**Comment by cjones051073** [comment]
> > I believe I pointed out to you 2 years ago exactly where R bakes it the compiler…
> 
> 
> 
> But I don’t recall having issues with minor version before, and even now the issue arose only on arm64.

Not relevant. The path R is baking in is a private internal one so its GCC's right to do what they want, which includes behaving differently between arm and intel.

The bottom line is R should not be doing this, and as @kencu points out this has been brought up before and nothing has been done to address it.

**Pull request merged**
