### PR TITLE
ocaml-dune: update to 3.7.0

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Long due update. Now everything installs correctly without earlier trickery.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6 PPC
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
@pmetzger Could you suggest what fails here on bots? (Locally it built fine for me.)

```
File "otherlibs/configurator/src/dune", line 7, characters 17-22:
[951](https://github.com/macports/macports-ports/runs/6541475158?check_suite_focus=true#step:8:957)
  7 |  (libraries unix csexp)
[952](https://github.com/macports/macports-ports/runs/6541475158?check_suite_focus=true#step:8:958)
                       ^^^^^
[953](https://github.com/macports/macports-ports/runs/6541475158?check_suite_focus=true#step:8:959)
  Error: Library "csexp" not found.
[954](https://github.com/macports/macports-ports/runs/6541475158?check_suite_focus=true#step:8:960)
  -> required by library "dune-configurator" in
[955](https://github.com/macports/macports-ports/runs/6541475158?check_suite_focus=true#step:8:961)
     _build/default/otherlibs/configurator/src
[956](https://github.com/macports/macports-ports/runs/6541475158?check_suite_focus=true#step:8:962)
  -> required by _build/default/META.dune-configurator
[957](https://github.com/macports/macports-ports/runs/6541475158?check_suite_focus=true#step:8:963)
  -> required by _build/install/default/lib/dune-configurator/META
[958](https://github.com/macports/macports-ports/runs/6541475158?check_suite_focus=true#step:8:964)
  -> required by _build/default/dune-configurator.install
[959](https://github.com/macports/macports-ports/runs/6541475158?check_suite_focus=true#step:8:965)
  -> required by alias install
[960](https://github.com/macports/macports-ports/runs/6541475158?check_suite_focus=true#step:8:966)
  Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_ocaml_ocaml-dune/ocaml-dune-configurator/work/dune-3.2.0" && /opt/local/bin/dune build -j 3 --root=/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_ocaml_ocaml-dune/ocaml-dune-configurator/work/dune-3.2.0 --profile=release --ignore-promoted-rules --no-config --only-packages=dune-configurator --default-target=@install @install 
[961](https://github.com/macports/macports-ports/runs/6541475158?check_suite_focus=true#step:8:967)
  Exit code: 1
```

**Comment by barracuda156** [comment]
For some reason `configurator` subport fails – it cannot find installed dependency:
```
--->  Configuring ocaml-dune-configurator
--->  Building ocaml-dune-configurator
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_ocaml_ocaml-dune/ocaml-dune-configurator/work/dune-3.4.1" && /opt/local/bin/dune build -j 6 --root=/opt/local/var/macports/build/_opt_PPCRosettaPorts_ocaml_ocaml-dune/ocaml-dune-configurator/work/dune-3.4.1 --profile=release --ignore-promoted-rules --no-config --only-packages=dune-configurator --default-target=@install @install 
File "otherlibs/configurator/src/dune", line 7, characters 17-22:
7 |  (libraries unix csexp)
                     ^^^^^
Error: Library "csexp" not found.
-> required by library "dune-configurator" in
   _build/default/otherlibs/configurator/src
-> required by _build/default/META.dune-configurator
-> required by _build/install/default/lib/dune-configurator/META
-> required by _build/default/dune-configurator.install
-> required by alias install
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_ocaml_ocaml-dune/ocaml-dune-configurator/work/dune-3.4.1" && /opt/local/bin/dune build -j 6 --root=/opt/local/var/macports/build/_opt_PPCRosettaPorts_ocaml_ocaml-dune/ocaml-dune-configurator/work/dune-3.4.1 --profile=release --ignore-promoted-rules --no-config --only-packages=dune-configurator --default-target=@install @install 
Exit code: 1
```

**Comment by barracuda156** [comment]
Hmm, the subport builds locally, just verified that. I will try to figure out why it still fails on bots. This must be fixed.

**Comment by pmetzger** [comment]
Are you attempting to build this on a system with opam? It looks like you're adding an opam file to the build as well? That might explain why it builds on your machine but doesn't build for macports.

**Comment by barracuda156** [comment]
@pmetzger @reneeotten @harens This is neatly fixed now.

**Review by harens — APPROVED** [review]
Thanks @barracuda156!

**Pull request merged**
