### PR TITLE
catgirl: use libretls for libtls dependency by default

### PR DESCRIPTION
**Pull request by causal-agent**
catgirl can build with libtls provided by either libretls when
openssl is installed, or by libressl when libressl is installed.
Since openssl is the default, use libretls to provide the missing
library. Also use a path: dependency since we always want to build
against a MacPorts libtls.

While here, add license_noconflict for both openssl and libressl,
since catgirl's license includes additional permission for
OpenSSL/LibreSSL.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.7 19H1323 x86_64
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryanakca** [comment]
I don't have my macbook handy to test, but OK by me so long as it continues to build against libressl.

Also, please feel free to add yourself as a maintainer.

**Comment by causal-agent** [comment]
Seems I should add `if {[vercmp [macports_version] 2.6.99] >= 0}` before the `configure.checks` line that was suggested to add in libretls' Portfile to fix this build.

**Review by reneeotten — CHANGES_REQUESTED** [review]
@casual-agent @ryanakca since you're changing the dependency here you'll want to make sure that this is picked up by all users. Since the actual `versions` did not change, MacPorts will not consider this change as an update unless you increase the `revision` field. If you can please take care of that, I think this PR is all good to go!

**Comment by causal-agent** [comment]
@reneeotten Ah right, fixed. Thanks

**Review by reneeotten — APPROVED** [review]

**Pull request merged**
