### PR TITLE
xrootd: fix build with gcc

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

The PR:
1. Replaces blacklist of `*gcc*` with `*gcc-4.*`, to allow using new GCC. (Do we actually need those at all, given portfile has `compiler.cxx_standard  2014`? Maybe do away with blacklists altogether?)
2. Fixes an error with `byteswap.h` missing on MacOS. (To be honest I wonder how Clang does not err out on that – FWIU that header is missing on all version of MacOS or at least on majority of them.)

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
clang uses the builtin_bswap compiler intrinsic.

newer gcc versions also have such an intrinsic.

**Comment by barracuda156** [comment]
> clang uses the builtin_bswap compiler intrinsic.
>
> newer gcc versions also have such an intrinsic.

@kencu Okay, but how to include it? Existing code does not build with gcc12 (otherwise I would not made a patch for that case).

**Comment by cjones051073** [comment]
I would rather avoid introducing a patch file to address this…

**Comment by cjones051073** [comment]
Have you discussed this with upstream ?

**Comment by barracuda156** [comment]
> I would rather avoid introducing a patch file to address this…

What alternative would you recommend?

**Comment by cjones051073** [comment]
> > I would rather avoid introducing a patch file to address this…
> 
> What alternative would you recommend?

Well a start would be to determine why current build with clang have no problems.

I would start by discussing the issue with upstream.

**Comment by cjones051073** [comment]
b.t.w. is the issue with all gcc versions, or just gcc12 ?

If only gcc12, or some of the newer ones, and older ones are OK I would prefer as a temporary fix (until upstream fixes support with the newer gcc versions) to just black the specific gcc versions that have problems, and thus use the newest that is OK, without needing a patch.

**Comment by kencu** [comment]
it's a missing header, so it would affect any build on macos that tries to include this file (this module, really).

What is actually going on here is that this gcc-only module is usually never built on macOS (which pretty much never tries to build this with gcc).

https://github.com/xrootd/xrootd/blob/7cc1184aebff87384483ab376d67adbad2405cb2/src/CMakeLists.txt#L63

So upstream would never expect to see or test this.

The patch is OK, I think. I haven't tested it but similar things are seen around the web to work around this issue of the "missing" header on macOS. I kinda doubt upstream would be interested in such a patch (that fixes the build on a totally unsupported system) but you never know. @barracuda156 can be very persuasive :>

**Comment by kencu** [comment]
examples:

https://github.com/sgan81/apfs-fuse/issues/6#issuecomment-363601678

https://debugjournal.tumblr.com/post/99661010362/missing-byteswaph-and-endianh-on-mac-os-x

https://bugs.freedesktop.org/show_bug.cgi?id=8882

**Comment by kencu** [comment]
@barracuda156 -- I suggest you try selling this upstream. You have a fair case, although they may not accept as very few people build this with gcc on darwin.

**Comment by barracuda156** [comment]
@kencu @cjones051073 I will deal with this in 1–2 days.

**Comment by barracuda156** [comment]
> b.t.w. is the issue with all gcc versions, or just gcc12 ?
> 
> If only gcc12, or some of the newer ones, and older ones are OK I would prefer as a temporary fix (until upstream fixes support with the newer gcc versions) to just black the specific gcc versions that have problems, and thus use the newest that is OK, without needing a patch.

The issue is that there is no `byteswap.h` on MacOS, at least on many versions of it.
Example with 10.15: https://github.com/Xilinx/qemu/issues/47
Fix (similar to mine here): https://github.com/Xilinx/qemu/commit/0d8efa472c074fc340a360a9bd74099a5030d7aa

**Comment by barracuda156** [comment]
> @barracuda156 -- I suggest you try selling this upstream. You have a fair case, although they may not accept as very few people build this with gcc on darwin.

@kencu I have an open PR there: https://github.com/xrootd/xrootd/pull/1766

**Comment by barracuda156** [comment]
UPD. Do not merge this yet, upstream suggests possibly moving the definitions to `XrdSysPlatform.hh` for the sake of consistency, and I wait for an update in that PR thread.

**Comment by kencu** [comment]
nice job with upstream, looks like they will accept soon.

**Comment by barracuda156** [comment]
> nice job with upstream, looks like they will accept soon. 

@kencu @cjones051073 Merged in upstream in: https://github.com/xrootd/xrootd/commit/8e1e528232d8ead08468eefcbf991737eb5751da

**Comment by kencu** [comment]
thanks!

**Pull request merged**
