### PR TITLE
Update some python ports and add py312 subport

### PR DESCRIPTION
**Pull request by catap**
#### Description

Here the next bulk from my local branch where I've updated all python ports which I'm care of and added to whem and dependencies py312 subports.

###### Type(s)

- [x] enhancement

###### Tested on

macOS 12.7.1 21G920 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kurthindenburg** [comment]
Fine w/ me if the checks pass for my ports.

**Comment by catap** [comment]
rebased to the master

**Comment by catap** [comment]
@reneeotten , @pmetzger what should I do with this? `pyopenssl-21.0.0.tar.gz` from github and from MacPorts by unknown reason is different right now.

```
√ xxx % wget -O github-pyopenssl-21.0.0.tar.gz https://github.com/pyca/pyopenssl/archive/21.0.0/pyopenssl-21.0.0.tar.gz  
--2023-12-15 12:53:42--  https://github.com/pyca/pyopenssl/archive/21.0.0/pyopenssl-21.0.0.tar.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/pyca/pyopenssl/tar.gz/refs/tags/21.0.0 [following]
--2023-12-15 12:53:42--  https://codeload.github.com/pyca/pyopenssl/tar.gz/refs/tags/21.0.0
Resolving codeload.github.com (codeload.github.com)... 140.82.121.10
Connecting to codeload.github.com (codeload.github.com)|140.82.121.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘github-pyopenssl-21.0.0.tar.gz’

github-pyopenssl-21.0.0.tar.gz                          [ <=>                                                                                                             ] 168.88K  --.-KB/s    in 0.06s   

2023-12-15 12:53:42 (2.63 MB/s) - ‘github-pyopenssl-21.0.0.tar.gz’ saved [172936]

√ xxx % wget -O macports-pyopenssl-21.0.0.tar.gz https://cph.dk.distfiles.macports.org/py-openssl/pyopenssl-21.0.0.tar.gz
--2023-12-15 12:53:46--  https://cph.dk.distfiles.macports.org/py-openssl/pyopenssl-21.0.0.tar.gz
Resolving cph.dk.distfiles.macports.org (cph.dk.distfiles.macports.org)... 91.210.59.156
Connecting to cph.dk.distfiles.macports.org (cph.dk.distfiles.macports.org)|91.210.59.156|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 172965 (169K) [application/x-gzip]
Saving to: ‘macports-pyopenssl-21.0.0.tar.gz’

macports-pyopenssl-21.0.0.tar.gz                    100%[================================================================================================================>] 168.91K  --.-KB/s    in 0.07s   

2023-12-15 12:53:47 (2.32 MB/s) - ‘macports-pyopenssl-21.0.0.tar.gz’ saved [172965/172965]

√ xxx % ls -la                                                                                                           
total 688
drwxr-xr-x   4 catap  wheel     128 Dec 15 12:53 .
drwxrwxrwt  13 root   wheel     416 Dec 15 12:51 ..
-rw-r--r--   1 catap  wheel  172936 Dec 15 12:53 github-pyopenssl-21.0.0.tar.gz
-rw-r--r--   1 catap  wheel  172965 Nov 22  2021 macports-pyopenssl-21.0.0.tar.gz
√ xxx % file *                                                                                                           
github-pyopenssl-21.0.0.tar.gz:   gzip compressed data, from Unix, original size modulo 2^32 716800
macports-pyopenssl-21.0.0.tar.gz: gzip compressed data, from Unix, original size modulo 2^32 716800
√ xxx % md5 *                                                                                                            
MD5 (github-pyopenssl-21.0.0.tar.gz) = 8df85863d5f2af7eee995f5173a42c48
MD5 (macports-pyopenssl-21.0.0.tar.gz) = a59b324ae5e6924565433c32aee771d9
√ xxx % 
```

**Comment by pmetzger** [comment]
@catap Stealth update? There's a section in the MacPorts guide for dealing with stealth updates.

**Comment by catap** [comment]
@pmetzger here an issue: github had changes (sometimes) `.tar.gz`; as you may see right now this PR has passed CI on one builder that means it had downloaded `.tar.gz` with the right checksum, and the second one failed because checsums missmatched.

So, something *very* wrong here and I don't like idea to cover issues, better to understand and fix it.

**Comment by reneeotten** [comment]
> @pmetzger here an issue: github had changes (sometimes) `.tar.gz`; as you may see right now this PR has passed CI on one builder that means it had downloaded `.tar.gz` with the right checksum, and the second one failed because checsums missmatched.
> 
> So, something _very_ wrong here and I don't like idea to cover issues, better to understand and fix it.

not necessarily something very wrong here; this is one of the reasons the recommendation is to set `github.tarball_from` to either `archives` or `releases` since GitHub tags are mutable. I would suggest to update the port to the latest upstream versions and add the same time set `github.tarball_from` appropriately to avoid issues like this in the future (or at least minimize the chances from happening). Of course in the case of a "stealth update" one should attempt to verify what has changed in the downloaded tarballs and make sure that the changes are harmless before applying the "stealth update hack".

**Comment by catap** [comment]
@reneeotten the issue that this had happened only with `py27` subport which is pin to some old version, and this version is used `github.tarball_from archive`.

**Comment by catap** [comment]
The root cause of failure seems was this commit: https://github.com/macports/macports-ports/commit/6580d062562b2dde9043adafb3489d220132c988

pin shouldn't have `github.tarball_from archive` and if I remove it, it works just fine.

**Comment by catap** [comment]
@pmetzger it's passed CI and ready to be merged.

**Comment by catap** [comment]
Thanks, Perry!

**Pull request merged**
