### PR TITLE
pascal-p5: Update homepage to valid URL

### PR DESCRIPTION
**Pull request by kamischi**
The URL was wrong.

###### Type(s)

- [*] bugfix

###### Tested on
Applies to any platform

###### Verification 
Have you

- [*] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [*] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [*] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [*] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [*] checked your Portfile with `port lint`?

### CODE REVIEW

**Comment by emcrisostomo** [comment]
Thanks. In the spirit of the definition of revision, I'm not sure any installation will benefit from an upgrade. Actually, I think the contrary is true.

```
revision
Optional keyword (default is 0) that is used to track port revisions. It should not be incremented for port revisions unless it would benefit users to upgrade an installed port, and cleared when the port is updated to a newer version.

It should be used if a bug in the Portfile was found and all installations of this port have to be updated. If the change only affects new installations, there is no need to increase it.
```

Would you please bump it back to `0` and maintain the `homepage` update?

**Comment by emcrisostomo** [comment]
@pmetzger, what's your opinion?

**Comment by emcrisostomo** [comment]
Also, please follow the commit message guidelines, as specified in the PR template:

https://trac.macports.org/wiki/CommitMessages

Mention the port name in the message, ideally at the beginning, separating the description with a colon, and state the intent of the PR:

```
pascal-p5: update homepage to valid URL
```

**Comment by kamischi** [comment]
Remarks accepted. I try my best to create a better pull request.

**Comment by mf2k** [comment]
There is indeed no reason to update the `revision` in this case because the installed files and dependencies are not changing.

**Comment by cjones051073** [comment]
@kamischi changing the PR title is good but not enough. You also need to change the actual commit description as well to follow our commit guidelines .

**Comment by emcrisostomo** [comment]
Also, please squash commits into one: there currently is:
* One commit that does not follow the commit guidelines
* One commit that is the result of a merge.

**Comment by kamischi** [comment]
Squashing all into one was, what i tried to do, obviously without success. No idea, what caused that merge. I tried "git log ." to get an overview, but it does not mention the merge and i do not know where to rebase for squashing. Can you guide me, as i do not know, how to proceed from here.

**Comment by emcrisostomo** [comment]
Hi @kamischi, yes, no worries. The first thing you have to understand is the current state of the branch you're working on. There's one suspicious thing here: there's a commit (`bb1155f`), that really look like a merge, and that's strange. Furthermore, that merge sets `revision` to `1`, which is what you wanted to roll back.

If the branch you're in is not in the correct state, probably the easiest way to fix it is:
* _Save_ the `Portfile` elsewhere (outside the repo) in order not to lose your work.
* Reset the branch to a clean state (ideally, you should be in an `upstream/master` commit).
* Copy over the `Portfile`, add the changes, commit and force push.
* You should now have one single commit.

Alternatively, you can apply additional changes to your current branch and arrive at the desired final state (remember `revision` should be set to `0`). To squash the last `n` commits you can run:

```
$ git rebase -i HEAD~n
```

If, in your case, you will add a commit to fix the merge, you will end up with 3 commits, in which case you'll run:

```
$ git rebase -i HEAD~3
```

An interactive rebase session will appear where commits are listed in _reverse_ order (oldest to newest). The first one will remain `pick`, while all the following will have to become `squash`, or `s` for short. When you'll save your changes you will be asked for the commit message. Set it correctly (`pascal-p5: update homepage to valid URL`), and force push.

**Comment by kamischi** [comment]
Another try, but that strange additional merge happens again and i have not the slightest clue, why or how.

**Comment by kencu** [comment]
I hope that fixes it up for you. I force-pushed what I believe to be the proper fix to your branch for you.

There were a series of commits in your branch. I did a ```git log``` to get the list back to the first one you made after you made your branch, then I reset the tree back to that commit using

```git reset --hard 4d15cd7ffa465e971e98b47ea5abea18f37d8f83```.

Then I changed your revision back to "0" again, added that commit, and then rebased them as @emcrisostomo explained.

That all looked right, and so I force-pushed it into your branch.

Please let us know if there are any remaining issues with it!

**Comment by kamischi** [comment]
Github Desktop wants me to push 7 commits! If you can deal with the current state, go ahead and i will happily delete all this mess.

**Comment by cjones051073** [comment]
> Github Desktop wants me to push 7 commits! If you can deal with the current state, go ahead and i will happily delete all this mess.

Using GitHub Desktop is probably part of your problem. You need to make sure you configure it to do a rebase when pulling in updates instead of a merge.

**Comment by cjones051073** [comment]
Just to add, I have no clue how to do that, or if it is even possible as I do not use it. Personally I would strongly ,y recommend just using the standard git command line client.

**Comment by cjones051073** [comment]
See the rebasing part of

https://github.blog/2019-06-05-github-desktop-expands-to-support-stashing-and-rebasing/

You need to use that option, as its exactly what we expect in MacPorts.

**Comment by emcrisostomo** [comment]
Thanks @kencu, @cjones051073

**Pull request merged**
