### PR TITLE
doxygen: update to 1.8.19

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Require thread-local storage

Enable tests

Set `homepage`, `master_sites`, and `livecheck` to use https://www.doxygen.nl

###### Tested on

macOS 10.15.6
Xcode command line tools 12 beta 3

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?

```
The following tests FAILED:
	 12 - 012_cite (Failed)
```

- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
Thanks! But we should probably fix this:

> Port doxygen **fail** on xcode7.3. [Log](https://paste.macports.org/00912895ebb0)

```
error: thread-local storage is not supported for the current target
```

The fix for that is to set `compiler.thread_local_storage yes`.

If that doesn't work, you may need to blacklist some compilers manually. I'm not sure if that's still needed with MacPorts 2.6.3 or if the compiler selection has already been fixed.

**Comment by chrstphrchvz** [comment]
Appears to be another case waiting on macports/macports-base#161 to be released.

**Comment by ryandesign** [comment]
> Appears to be another case waiting on [macports/macports-base#161](https://github.com/macports/macports-base/pull/161) to be released.

That PR was merged and was included in 2.6.3.

**Comment by chrstphrchvz** [comment]
> Port doxygen's dependencies **fail** on xcode9.4. [Log](https://paste.macports.org/26d2beee7413)

```
Error: Portfile is from the future - check date and time of your system
```

**Comment by ryandesign** [comment]
> That PR was merged and was included in 2.6.3.

But Travis CI hasn't been updated to use MacPorts 2.6.3 yet; see https://trac.macports.org/ticket/60925.

**Comment by ryandesign** [comment]
> ```
> Error: Portfile is from the future - check date and time of your system
> ```

Ok, we can ignore that. https://trac.macports.org/ticket/58800

**Comment by chrstphrchvz** [comment]
Will reset to ac78cec086 then. Thanks for figuring out the situation here. I wasn't sure since apparently the compiler selection fix was cherry-picked into the release-2.6 branch (macports/macports-base@e140058ef9), meaning GitHub doesn't display the PR merge commit (macports/macports-base@75b23174d3) in any releases, and the PR merge commit (and probably other released improvements) shows up in "commits made to master since this release" (https://github.com/macports/macports-base/compare/v2.6.3...master).

**Comment by ryandesign** [comment]
> apparently the compiler selection fix was cherry-picked into the release-2.6 branch

Yes, that's how we do releases. Commits go to master first and are cherry picked into a release if they're to be included in a bugfix release. Probably later this year around the release of macOS 11 we'll make a new release-2.7 branch from trunk.

**Pull request merged**
