### PR TITLE
xmltooling: needs C++11

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Plus minor improvement to portfile

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by scantor** [comment]
I guess if Xerces (which does not require C++11) was just changed to require it, then this should be too, but it's not a requirement of any of this code by any means. C++ 11 was nowhere near ubiquitious even a few years ago, probably still isn't, so I never adopted it.

As long as it works, I have no objection to it.

**Comment by scantor** [comment]
I guess my point was that whoever changed the Xerces port to require C+11 caused this, Xerces itself does not. I suppose it's possible it's just a Mac compatibility bug though if something drifted, but Xerces is all but dead (I'm the sole maintainner and I'm not even really maintaining it).

Maybe the better fix is rolling Xerces' port back or adding a patch to address whatever is causing the C++11 requirement there?

**Comment by barracuda156** [comment]
> I guess my point was that whoever changed the Xerces port to require C+11 caused this, Xerces itself does not. I suppose it's possible it's just a Mac compatibility bug though if something drifted, but Xerces is all but dead (I'm the sole maintainner and I'm not even really maintaining it).
> 
> Maybe the better fix is rolling Xerces' port back or adding a patch to address whatever is causing the C++11 requirement there?

I have no objections, but I do not have time to deal with that myself. Also if we fix the build now, it does not prevent in any way switching to an earlier standard later on, once/if someone decides to accomplish that.

**Comment by scantor** [comment]
Ok, merged.

**Comment by barracuda156** [comment]
Thank you!

**Pull request merged**
