### PR TITLE
transmission-x11: move to Cmake build system, fixes build on PPC

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Move to `cmake` build system. Only revision changes, `transmission` version remains @3.0.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

### CODE REVIEW

**Comment by i0ntempest** [comment]
There seems to be mixed white spaces and tabs, please see the details in the GitHub CI checks. Other than that LGTM.

**Comment by i0ntempest** [comment]
> > There seems to be mixed white spaces and tabs, please see the details in the GitHub CI checks. Other than that LGTM.
> 
> @i0ntempest Thank you. Could you please say where in particular spaces and tabs get mixed? Checks are reported as passed.

Go to Files changes tab above and scroll down, you’ll see which lines have tabs.

**Comment by barracuda156** [comment]
> Go to Files changed tab above and scroll down, you’ll see which lines have tabs.

@i0ntempest Ah, you don’t like tabs there. No problem, replaced with spaces now.

**Comment by i0ntempest** [comment]
One more tab at line 55, also please add a blank new line at the end.

**Comment by barracuda156** [comment]
@i0ntempest Indeed, thank you. Fixed.

**Comment by i0ntempest** [comment]
Great, now squash your last two commits into one (so have a total of 2) and we'll be ready for merging.

**Comment by barracuda156** [comment]
> Great, now squash your last two commits into one (so have a total of 2) and we'll be ready for merging.

@i0ntempest Two spaces & tabs commits squashed.

**Pull request merged**
