### PR TITLE
fdm: update to 2.2

### PR DESCRIPTION
**Pull request by shuxiao9058**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.3.1 22E772610a arm64
Command Line Tools 14.3.0.0.1.1679647830

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
Observe this warning printed during configuration:
```
Warning: Configuration logfiles contain indications of -Wimplicit-function-declaration; check that features were not accidentally disabled:
    strchr: found in fdm-2.2/config.log
```
Please read [the wiki article about this warning](https://trac.macports.org/wiki/WimplicitFunctionDeclaration), specificaly the section about [suppressing this specific instance of it](https://trac.macports.org/wiki/WimplicitFunctionDeclaration#AddnamestowhitelistviaPortfile).

**Comment by reneeotten** [comment]
that PR/ticket has been closed/fixed upstream. Can this be PR be finalized?

**Comment by shuxiao9058** [comment]
> Observe this warning printed during configuration:
> 
> ```
> Warning: Configuration logfiles contain indications of -Wimplicit-function-declaration; check that features were not accidentally disabled:
>     strchr: found in fdm-2.2/config.log
> ```
> 
> Please read [the wiki article about this warning](https://trac.macports.org/wiki/WimplicitFunctionDeclaration), specificaly the section about [suppressing this specific instance of it](https://trac.macports.org/wiki/WimplicitFunctionDeclaration#AddnamestowhitelistviaPortfile).

issue resolved.

**Comment by ryandesign** [comment]
> issue resolved.

Nope.

**Pull request merged**
