### PR TITLE
mirror_sites.tcl: remove unused xcontrib mirrors

### PR DESCRIPTION
**Pull request by chrstphrchvz**
No longer used as of 17a52241d8.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] ~~referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?~~

### CODE REVIEW

**Comment by pmetzger** [comment]
That was really the only place in the entire tree where xcontrib was referenced?

**Comment by chrstphrchvz** [comment]
> That was really the only place in the entire tree where xcontrib was referenced?

I haven't found a better answer for than "yes, `xpm` was the only port to ever use it, beginning in b9bcfa6b52 (at the time mirrors were in macports-base) and ending with 17a52241d8".

```
~/git/macports-ports$ git log -S 'xcontrib:' --source --all
commit 17a52241d8ef811bc04a796f0a20b8b42b699eab refs/tags/release_1_7_0-archive
Author: Jeremy Huddleston Sequoia <jeremyhu@macports.org>
Date:   Wed Dec 3 21:30:44 2008 +0000

    xpm: Version bump and build universal
    
    git-svn-id: https://svn.macports.org/repository/macports/trunk/dports@43029 d073be05-634f-4543-b044-5fe20cf6d1d6

commit b9bcfa6b52056d8fe2fa28a1e21532a8255921b0 refs/tags/release_1_2_0-archive-rc1
Author: Toby Peterson <toby@macports.org>
Date:   Sun Jan 18 04:13:27 2004 +0000

    use master_sites xcontrib
    
    Bug:
    Submitted by:
    Reviewed by:
    Approved by:
    Obtained from:
    
    git-svn-id: https://svn.macports.org/repository/macports/trunk/dports@4816 d073be05-634f-4543-b044-5fe20cf6d1d6
```

The only port I'm aware of which currently uses a mirror that could otherwise be part of `xcontrib` is `unclutter`.

**Comment by pmetzger** [comment]
Conflicts need resolving...

**Comment by chrstphrchvz** [comment]
> Conflicts need resolving...

Thanks for letting me know, I rebased to resolve the conflict.

**Comment by pmetzger** [comment]
Merged. Thanks for all the help with MacPorts, @chrstphrchvz!

**Pull request merged**
