### PR TITLE
transmission: add myself as maintainer

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@i0ntempest I thought you were the maintainer already :) 

Looks like I should update x11 version to 4.0.6 too.

**Comment by i0ntempest** [comment]
I'm not, didn't bother to add myself until now. Manipulating Xcode builds using CLI only is a major pain in the ass.
Also take a look at [this issue](https://github.com/transmission/transmission/issues/6876) when updating your port, it might help.

**Comment by barracuda156** [comment]
Yeah, I agree, Xcode builds are a pain.

What is even `miniupnp`? Their own internal re-implementation?

**Comment by i0ntempest** [comment]
Looks like their own fork of `miniupnpc`.

**Pull request merged**
