### PR TITLE
dub: update dub 1.3.0->1.11.0

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
muniversal PG no longer requires Makefile.

###### Type(s)

- [X] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.14
Xcode 10.0 

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by MarcusCalhoun-Lopez** [comment]
dub version 1.3.0 did not build for me, but updating to the latest version fixed the problem.

**Comment by pmetzger** [comment]
LGTM, but I don't know anything about this port.

**Comment by seanfarley** [comment]
LGTM but I forgot I had my name on this port. If anyone else wants it, feel free.

**Comment by pmetzger** [comment]
@seanfarley You might want to just make it `nomaintainer` then. Few people who might be interested will have read this PR...

**Pull request merged**
