### PR TITLE
update alps Portfile to 2.3.0

### PR DESCRIPTION
**Pull request by dolfim**

### CODE REVIEW

**Comment by mojca** [comment]
Please squash the second commit, change the commit message to `alps: update to 2.3.0 [and ...]` and perhaps add a bit longer description about the changes you did apart from updating. Then force push to your branch.

(Please note that I'm not in position to actually review the contents.)

**Comment by mojca** [comment]
Also: someone needs to notify the maintainer. (Unless that is you?)

I'm not sure whether he has a GitHub account.

**Comment by dolfim** [comment]
Done with squash and I mailed the maintainer asking to followup on the discussion.

**Comment by gamperl** [comment]
Hi I did create the original port file, but I have no special Github permissions. I reviewed the update and it looks good. So what do I have todo now?

**Pull request merged**
