### PR TITLE
py-asn1-modules: update to 0.4.0

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Should have been updated together, sorry -_-
Support for old pythons were dropped in new versions, so add fallbacks.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
What still needs this with an ancient version of Python?

**Comment by barracuda156** [comment]
@pmetzger `py-twisted`, I think. Those are ports with maintainers in dependents, please leave it to someone else to throw out support for specific Python versions.

I just want to fix `deluge` which is broken by a switch to python312 on a part of libtorrent-rasterbar (resulting in conflicting defaults) and two dependencies (this one and py-constantly).

Let someone else deal with Python ports cleanups. Maintainers for example.

**Comment by barracuda156** [comment]
@pmetzger This is BTW desirable to merge ASAP even unrelated to Deluge, since it is a fix.

**Comment by pmetzger** [comment]
Given how many security problems are caused by ancient ASN.1 parsers I'm kind of terrified of this...

**Comment by barracuda156** [comment]
@pmetzger This port has stayed at “ancient” version forever until I have updated it a few days ago – and no one bothered the least about security issues.

I do not mind someone else removes support for older Python here. Please, let it be not me. This is not my port, I just want to fix the problem which was created by the update.

**Comment by pmetzger** [comment]
It's true that people have not been removing as much of the old Python stuff as they should, but when something with security implications comes to our attention, we should deal with it. What old stuff still depends on this? Could you check?

**Comment by barracuda156** [comment]
@pmetzger This PR literally uses as fallbacks versions which we still used for _every MacOS and every Python_ until few days ago and for one of the ports are still used right now.

Yes, you may also close this PR unmerged, and then `py-asn1-modules` will be outdated for all systems (and also won’t work).

But I have no time or interest to do any Python-related general clean-ups, please excuse me for that. Let maintainers do that at their convenience, or anyone else interested. I am not requesting to retain old Pythons support for this port specifically, but here I just want to fix a specific problem, that is it. Nothing more.

**Comment by pmetzger** [comment]
It would take you a matter of minutes to figure out if the fallback is actually needed. I don't have time to do it. You obviously care about this. Why not do the thing correctly?

**Comment by barracuda156** [comment]
> You obviously care about this.

My only concern is to fix Deluge, it is broken now because of mismatched versions.

> I don't have time to do it. 

This is precisely why I would appreciate not being forced to do unrelated stuff just because I fix something for a given port.
I do not use Python on its own, I do not like Python build system, I want to minimize interaction with it. (Exception being dependencies of my ports and a few select fundamental packages like numpy.)

> Why not do the thing correctly?

IMO, fixing something without breaking anything is the correct thing, and not do changes blindly without any idea what systems and ports may be affected.

There are 12 ports depending just on `py27-asn1` alone. I am not gonna track every of those and their dependencies, and then do the same for `py37` and `py38`. I also have no time, and no interest either.

**Comment by barracuda156** [comment]
@pmetzger @reneeotten @ryandesign Bump, we need this to fix the port and have Deluge working.

**Comment by pmetzger** [comment]
I explained my position here.

**Comment by barracuda156** [comment]
> I explained my position here.

That you prefer having a port broken for all systems, or otherwise I must do a MacPorts-wide clean-up for someone’s Python stuff? Well, no, I am not gonna do that.

**Comment by barracuda156** [comment]
@ryandesign @kencu I guess I need some intervention here to get this going.

We have a disagreement with Perry here, but it does not do any good to anyone to block merging this PR. This is a genuine fix, relevant for all platforms, not only for the legacy ones. Whomever wishes to drop support for older Python versions may do so in a subsequent PR; while I do not support that, I am not opposing that either. I simply have no time to do a clean-ups for unrelated ports in which I have little to no interest. This is not my responsibility, but that of respective ports’ maintainers or whomever is interested in such a task.
This is nothing here about my powerpc or 10.6. It should not be controversial at all.

**Comment by reneeotten** [comment]
@pmetzger I agree with you that clean-up if EOL Python ports would be ideal. However, there are still dependents right now so without a fallback these would all be broken. I'll try and do some work again on a (major) clean-up/removal of EOL subports/ports but don't think we should hold up this PR for that. Just as it is not a requirement to support old OSes it isn't a requirement either to do the clean-up of old subports if you're not the port maintainer. 

I will merge this PR now and will see if I can do the clean-up myself in a subsequent commit.

**Comment by barracuda156** [comment]
@reneeotten Thank you!

@pmetzger I am sorry that this became a debate, but cleanup here was not just a single port, and I am really constrained on time: there are ports which I maintain that need to be attended, for example.

**Pull request merged**
