### PR TITLE
opencv4-devel: update to 4.9.0, use python 3.12

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mascguy** [comment]
Zhenfu, have you tested variant `+contrib`?

**Comment by i0ntempest** [comment]
> Zhenfu, have you tested variant `+contrib`?

Tested & changes pushed

**Comment by mascguy** [comment]
It looks like CI is failing. Can you take a look?

**Comment by i0ntempest** [comment]
It's failing to install dependencies but does not clearly show why...
```
  Installing dependency (97 of 116) 'opencv4-devel' with variants '' ... [OK]
  Installing dependency (98 of 116) 'ninja' with variants '' ... [OK]
  Installing dependency (99 of 116) 'py312-installer' with variants '' ... [OK]
  Installing dependency (100 of 116) 'py312-wheel' with variants '' ... [OK]
  Installing dependency (101 of 116) 'py312-pyproject_metadata' with variants '' ... [OK]
  Installing dependency (102 of 116) 'py312-cython' with variants '' ... [OK]
  Installing dependency (103 of 116) 'py312-oldest-supported-numpy' with variants '' ... [OK]
  Installing dependency (104 of 116) 'py312-meson' with variants '' ... [OK]
  Installing dependency (105 of 116) 'py312-meson-python' with variants '' ... [OK]
  Installing dependency (106 of 116) 'isl' with variants '' ... [OK]
  Installing dependency (107 of 116) 'mpfr' with variants '' ... [OK]
  Installing dependency (108 of 116) 'libmpc' with variants '' ... [OK]
  Installing dependency (109 of 116) 'gcc_select' with variants '' ... [OK]
  Installing dependency (110 of 116) 'gcc13-libcxx' with variants '+clang16' ... [OK]
  Installing dependency (111 of 116) 'ld64-xcode' with variants '' ... [OK]
  Installing dependency (112 of 116) 'ld64' with variants '+ld64_xcode' ... [OK]
  Installing dependency (113 of 116) 'gcc13' with variants '+stdlib_flag' ... [OK]
  Installing dependency (114 of 116) 'py312-pyproject_hooks' with variants '' ... [OK]
  Installing dependency (115 of 116) 'py312-build' with variants '' ... [OK]
  Installing dependency (116 of 116) 'py312-numpy' with variants '+gfortran' ... [MISSING]
  Building 1 dependencies of py312-opencv4-devel:
  Building dependency (1 of 1) 'py312-numpy' with variants '+gfortran' ... [OK]
Error: Failed to install dependencies for py312-opencv4-devel
```

**Comment by i0ntempest** [comment]
I did update py-numpy before but it cleared everything except 10.6 so I don't think that is the problem.

**Comment by i0ntempest** [comment]
Right... a bunch of reruns later it's now passing.

**Review by mascguy — APPROVED** [review]
LGTM

**Pull request merged**
