### PR TITLE
libavif: fix incorrect configure.arg, add tests variant

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Fix incorrect configure.arg (possibly my mistake earlier, sorry).
Drop Rosetta case: `aom` builds now for it.
Add tests variant.
Fix alignments in portfile.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Tests on 10.6:
```
--->  Testing libavif
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libavif/libavif/work/build" && ninja test 
[0/1] Running tests...
Test project /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libavif/libavif/work/build
    Start 1: avifgridapitest
1/3 Test #1: avifgridapitest ..................   Passed   18.39 sec
    Start 2: avifincrtest
2/3 Test #2: avifincrtest .....................   Passed  649.57 sec
    Start 3: avify4mtest
3/3 Test #3: avify4mtest ......................   Passed    0.11 sec

100% tests passed, 0 tests failed out of 3

Total Test time (real) = 668.08 sec
```

**Comment by reneeotten** [comment]
so does this change the build since you changed `configure.args`? If so, the `revision` on these specific OS versions should be increased. Or is this only fixing a build error?

**Comment by barracuda156** [comment]
> so does this change the build since you changed `configure.args`? If so, the `revision` on these specific OS versions should be increased. Or is this only fixing a build error?

@reneeotten Just the build error. (I.e. despite that I change the setting for Rosetta, it was not building with existing one, so no need to revbump.)

**Comment by barracuda156** [comment]
@reneeotten Thank you!

**Pull request merged**
