### PR TITLE
haskell-platform, hs-*: Delete

### PR DESCRIPTION
**Pull request by neverpanic**
##### haskell-platform, hs-*: Delete

It is too complicated to keep up with the development of haskell-platform in its current state, and while there is technically
nothing wrong with the approach, it has turned out that nobody has the time to maintain copies of the hundreds of libraries that are required o provide the full haskell platform as defined at https://www.haskell.org/platform/contents.html.

Fortunately, there is a more modern alternative available in the form of stack, which works similar to virtualenvs for python. We are now using stack (in the form of the haskell_stack PortGroup) for all Haskell tools we are packaging in MacPorts (e.g. darcs, git-annex, pandoc or shellcheck). It is also the best alternative for our users.

I am not marking haskell-platform or any of the hs-* ports as obsoleted using the obsolete PortGroup, because these ports have not built successfully for a while now, and the users that still have successfully compiled copies of these tools and libraries would likely rather keep hem around than having them replaced by a file telling them that the ports are obsolete.

This currently breaks the following ports:
- hedgewars
- hsshellscript
- distract
- buddha

Closes: https://trac.macports.org/ticket/53652
Closes: https://trac.macports.org/ticket/60241
Closes: https://trac.macports.org/ticket/60359
Closes: https://trac.macports.org/ticket/61020
Closes: https://trac.macports.org/ticket/61162
Closes: https://trac.macports.org/ticket/61218
Closes: https://trac.macports.org/ticket/61263

#####  haskell-{chunks,hinstaller,parsedate}: Delete

haskell-chunks doesn't configure.
haskell-hinstaller doesn't build.
haskell-parsedate doesn't fetch.

All three ports have not been modified since 2016 and have not been significantly modified since their original commit in May 2007. None of the ports have dependencies.

##### haskell: Delete unused PortGroups

Remove PortGroups that are no longer used now that haskell-platform and he hs-* ports are removed.

Keep the haskell_stack and haskell_cabal PortGroups for our remaining use cases.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.6 18G6032
Xcode 11.3.1 11C504

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
+1

**Comment by nickgaya** [comment]
> It is too complicated to keep up with the development of haskell-platform in its current state ... nobody has the time to maintain copies of the hundreds of libraries that are required to provide the full haskell platform as defined at https://www.haskell.org/platform/contents.html.

As noted in the link, those hundreds of libraries are no longer part of the platform. The installation instructions at https://www.haskell.org/platform/ indicate that the current version of the Haskell platform is just ghc + cabal-install + stack.

Since there are already ports for all three components, we could maintain `haskell-platform` as an alias for `ghc`, `cabal`, and `stack`.  I think this might be useful for Haskell beginners just looking to install the basic tools and get started on some tutorials.

**Comment by neverpanic** [comment]
> As noted in the link, those hundreds of libraries are no longer part of the platform. The installation instructions at https://www.haskell.org/platform/ indicate that the current version of the Haskell platform is just ghc + cabal-install + stack.
>
> Since there are already ports for all three components, we could maintain `haskell-platform` as an alias for `ghc`, `cabal`, and `stack`. It's debatable whether this would be useful, but let's not make the decision on the basis of incorrect assumptions.

If you look at https://packages.debian.org/sid/haskell-platform (or what other Linux distributions provide), "haskell platform" is still a batteries included distribution. The haskell platform website just seems to recommend a different approach (ghcup and stack) on macOS, rather than what was commonly (and still is) known as haskell platform.

I'd thus still argue if someone installs a port called `haskell-platform`, they'd expect the batteries included package they know from Linux, not an alias for ghc, cabal-install and stack.

 
> Personally, I think this could provide some value for Haskell beginners just looking to install the basic tools and get started on some tutorials.

I think those users are best served by not following a tutorial that recommends installing haskell platform, but following one that recommends the usage of stack.


> There might be relatively few MacPorts users who fall in this category, but the cost of maintaining it is also very low. It could also be useful for existing users of the `haskell-platform` port who would get the latest recommended tools on upgrade.

I disagree, because somebody could still have binaries around that depend on all the libraries that we used to package, and switching `haskell-platform` to mean something different might actually break their setup, while just dropping it will not.

I also think we should stop discussing what "haskell platform" should mean and solve the question of what to do with the remaining four ports that would be broken by this change.

**Comment by kencu** [comment]
I am fine with deleting hedgewars out of our portmix until (and if) I ever get around to making it work again with the new ghc stack / cabal setup.

**Comment by kencu** [comment]
hedgewars is now deleted, as described <https://github.com/macports/macports-ports/commit/279a8fc425a5ba3467beb826c5b063747944aa62> .

**Comment by kencu** [comment]
hsshellscript has been deleted a2c2390539dc1c8eda8fadcfb288c04869c8a198

**Comment by kencu** [comment]
distract : deleted here 45a8de9a272bb16bc22ed2f1f71fb5dbe34b8764

**Comment by kencu** [comment]
buddha deleted: 710b9656868190bebef800aedd98219cc364a0b7

**Comment by kencu** [comment]
That takes care of all the ancient ports that no longer build under the new ghc structure. None of them have been updated in more than a decade. HedgeWars is different -- that was my port originally -- I don't yet know how to use ghc to build something that is not primarily a ghc port, and I'm not sure we're going to figure it out for MacPorts anyway. 

I don't see any reason that we can't commit this PR now. 

24 hour warning! Anyone who has any issues with this plan, please speak up now!

**Pull request merged**
