### PR TITLE
py-django: Update to version 4.1.7

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.2.1 22D68 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by essandess** [comment]
@mojca I see that `port -vst install` also fails on this in the `extract` phase with a `tar` command. I don’t see any issue in the Portfile or distfile, and don’t understand why this isn’t working. `port install` works fine.

**Comment by reneeotten** [comment]
> understand

https://trac.macports.org/ticket/66358

**Comment by mascguy** [comment]
Will the major update to `py-django` - we're jumping from v2.x to v4.x - also require updating all dependents?

```
py-django-allauth
py-django-gravatar2
py-django-htmlmin
py-django-mailman3
py-postorius
```

**Comment by mascguy** [comment]
> Will the major update to `py-django` - we're jumping from v2.x to v4.x - also require updating all dependents?
> 
> ```
> py-django-allauth
> py-django-countries
> py-django-debug-toolbar
> py-django-gravatar2
> py-django-mailman3
> py-django-nose
> py-tastypie
> py-postorius
> ```

Or at the very least, should we also rev-bump all of those...?

**Comment by mascguy** [comment]
> > Will the major update to `py-django` - we're jumping from v2.x to v4.x - also require updating all dependents?
> > ```
> > py-django-allauth
> > py-django-countries
> > py-django-debug-toolbar
> > py-django-gravatar2
> > py-django-mailman3
> > py-django-nose
> > py-tastypie
> > py-postorius
> > ```
> 
> Or at the very least, should we also rev-bump all of those...?

As a starting point, added a commit to rev-bump these. Though I suspect that we'll need to update the various `py-django-xxx` ports, for any that are outdated...

**Comment by mascguy** [comment]
> As a starting point, added a commit to rev-bump these. Though I suspect that we'll need to update the various `py-django-xxx` ports, for any that are outdated...

Yes, we really need to update the other `py-django-xxx` ports:

```
$ port -v livecheck $(for p in python/py-django-* ; do pname="${p##*\/}" ; printf "${pname}\n" ; done)
py-django-allauth seems to have been updated (port version: 0.46.0, new version: 0.54.0)
py-django-countries seems to have been updated (port version: 5.5, new version: 7.5.1)
py-django-debug-toolbar seems to have been updated (port version: 2.2.1, new version: 4.1.0)
py-django-extensions seems to have been updated (port version: 2.2.8, new version: 3.2.1)
py-django-gravatar2 seems to be up to date
py-django-htmlmin seems to have been updated (port version: 0.10.0, new version: 0.11.0)
py-django-mailman3 seems to have been updated (port version: 1.3.7, new version: 1.3.9)
py-django-nose seems to have been updated (port version: 1.4.6, new version: 1.4.7)
```

**Pull request closed without merging**
