### PR TITLE
openexr: update to 3.1.9, drop patches merged to upstream

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mascguy** [comment]
Sergey, after having to deal with multiple rounds of post-update fixes for this port, I'm really not too keen on updating it again.

Why are you spending time updating ports that have maintainers...?

**Comment by mascguy** [comment]
Sorry, to clarify... I meant, why are you specifically updating ports that have active maintainers?

I can understand updating ports that are woefully out-of-date, and/or not actively maintained. But that's not the case for Marcus and myself, nor for this port. Lol

**Comment by barracuda156** [comment]
Sorry, closing this.

**Comment by mascguy** [comment]
> Sorry, closing this.

Since you've created this, we might as well merge. But I was simply asking in-general...?

**Comment by barracuda156** [comment]
@mascguy You are right, I should not create an impression of trying to usurp others’ ports which are maintained normally. (My reasoning was not to usurp, of course, but that I interacted with upstream on fixes for this port and knew what was already merged and therefore which patches to drop. Now, on a second thought, patches won’t apply anyway, so not a great reason to interfere.) Point taken.

**Comment by mascguy** [comment]
> @mascguy You are right, I should not create an impression of trying to usurp others’ ports which are maintained normally. (My reasoning was not to usurp, of course, but that I interacted with upstream on fixes for this port and knew what was already merged and therefore which patches to drop. Now, on a second thought, patches won’t apply anyway, so not a great reason to interfere.) Point taken.

No, you're fine, and such updates are appreciated. Particularly given your point about interacting with upstream on fixes.

In such a case though, it would help to mention that in the description.

Feel free to re-submit this update, and I'll happily merge. Thanks as always Sergey!

**Comment by barracuda156** [comment]
@mascguy Re-opening.

Yeah, I should have mentioned that indeed.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
