### PR TITLE
gtk3, gtk3-devel: fix build with gcc14; gtk3-devel: update to 3.24.42

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

1. `legacy-support` implementation of `sincos` does not work as it should, and the compiler considers the function implicitly defined. With gcc14 it breaks the build. Since `sincos` appears in system `math.h` in 10.9, use the flag for < 10.9.
2. Forgotten update of -devel subport.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by kencu** [comment]
legacysupport’s implementation of sincos works just fine in general, and passes all tests.

sincos is declared in the math.h header:

https://github.com/macports/macports-legacy-support/blob/ed58217dc3cfcf267843c9ee395219826c805393/include/math.h#L88

and implemented in the library here:

https://github.com/macports/macports-legacy-support/blob/master/src/sincos.c


The problem you are running into with gcc14 is therefore of as yet unclear cause, it would seem. Not necessarily anything specific to leggacysupport….

**Comment by barracuda156** [comment]
@kencu It would be helpful to see what happens on 10.5, for example. gcc7 should not err out, so one has to look at the log whether warning was there or not.

P. S. Yes, I have checked headers, of course. And since `sincos` is missing in OS headers up to 10.8, this is not 10.6-specific issue. It could be gcc-specific though.

**Comment by mascguy** [comment]
CC: @fhgwright

**Comment by fhgwright** [comment]
As I already posted in the related ticket, there was a bug in the `legacy-support` `math.h`, which would probably cause this symptom.  The fix is in the latest `legacy-support-devel`, but not the release version.  My suggestion is:

1. Try the build using `legacy-support-devel` and without `0bb2d7d`.  If that works, then the problem is understood, with an upcoming fix.
2. If that works, then wait for the next `legacy-support` release to publish the `gtk3` update.

**Comment by barracuda156** [comment]
@fhgwright Thank you, I will try today.

**Comment by reneeotten** [comment]
ping

**Comment by barracuda156** [comment]
@reneeotten I will try with the current `legacy-support-devel`.

**Comment by barracuda156** [comment]
@fhgwright Sorry, which commit should I try reverting? https://github.com/macports/macports-legacy-support/commit/0bb2d7d leads to nowhere.
With the latest `legacy-support-devel` I will try now.

**Comment by barracuda156** [comment]
So, it still fails with `legacy-support-devel` 20240723_0:

```
FAILED: docs/tools/doc-shooter.p/.._.._tests_gtkgears.c.o 
ccache /opt/local/bin/gcc-mp-14 -arch ppc -Idocs/tools/doc-shooter.p -Idocs/tools -I../gtk+-3.24.42/docs/tools -I. -I../gtk+-3.24.42 -Igdk -I../gtk+-3.24.42/gdk -Igtk -I../gtk+-3.24.42/gtk -I../gtk+-3.24.42/tests -Igdk/x11 -I../gtk+-3.24.42/gdk/x11 -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include/gio-unix-2.0 -I/opt/local/include/pango-1.0 -I/opt/local/include/harfbuzz -I/opt/local/include/fribidi -I/opt/local/include/cairo -I/opt/local/include/pixman-1 -I/opt/local/include/freetype2 -I/opt/local/include/libpng16 -I/opt/local/include/gdk-pixbuf-2.0 -I/opt/local/include/atk-1.0 -I/opt/local/include/at-spi2-atk/2.0 -I/opt/local/include/at-spi-2.0 -I/opt/local/include/dbus-1.0 -I/opt/local/lib/dbus-1.0/include -I/opt/local/include -fdiagnostics-color=always -Wall -Winvalid-pch -O2 -g -DG_LOG_USE_STRUCTURED=1 -DGLIB_MIN_REQUIRED_VERSION=GLIB_VERSION_2_56 -DGLIB_MAX_ALLOWED_VERSION=GLIB_VERSION_2_58 '-DGTK_VERSION="3.24.42"' -D_GNU_SOURCE -DG_ENABLE_DEBUG -pipe -Os -fstrict-aliasing -arch ppc -DX_LOCALE -MD -MQ docs/tools/doc-shooter.p/.._.._tests_gtkgears.c.o -MF docs/tools/doc-shooter.p/.._.._tests_gtkgears.c.o.d -o docs/tools/doc-shooter.p/.._.._tests_gtkgears.c.o -c ../gtk+-3.24.42/tests/gtkgears.c
../gtk+-3.24.42/tests/gtkgears.c: In function 'create_gear':
../gtk+-3.24.42/tests/gtkgears.c:309:5: error: implicit declaration of function 'sincos' [-Wimplicit-function-declaration]
  309 |     sincos(i * 2.0 * G_PI / teeth + da * 0, &s[0], &c[0]);
      |     ^~~~~~
../gtk+-3.24.42/tests/gtkgears.c:46:1: note: include '<math.h>' or provide a declaration of 'sincos'
   45 | #include "gtkgears.h"
  +++ |+#include <math.h>
   46 | 
../gtk+-3.24.42/tests/gtkgears.c:309:5: warning: incompatible implicit declaration of built-in function 'sincos' [-Wbuiltin-declaration-mismatch]
  309 |     sincos(i * 2.0 * G_PI / teeth + da * 0, &s[0], &c[0]);
      |     ^~~~~~
../gtk+-3.24.42/tests/gtkgears.c:309:5: note: include '<math.h>' or provide a declaration of 'sincos'
../gtk+-3.24.42/tests/gtkgears.c: In function 'perspective':
../gtk+-3.24.42/tests/gtkgears.c:522:4: warning: incompatible implicit declaration of built-in function 'sincos' [-Wbuiltin-declaration-mismatch]
  522 |    sincos(radians, &sine, &cosine);
      |    ^~~~~~
../gtk+-3.24.42/tests/gtkgears.c:522:4: note: include '<math.h>' or provide a declaration of 'sincos'
```

**Comment by fhgwright** [comment]
> So, it still fails with `legacy-support-devel` 20240723_0:
> 
> ```
> FAILED: docs/tools/doc-shooter.p/.._.._tests_gtkgears.c.o 
> ccache /opt/local/bin/gcc-mp-14 -arch ppc -Idocs/tools/doc-shooter.p -Idocs/tools -I../gtk+-3.24.42/docs/tools -I. -I../gtk+-3.24.42 -Igdk -I../gtk+-3.24.42/gdk -Igtk -I../gtk+-3.24.42/gtk -I../gtk+-3.24.42/tests -Igdk/x11 -I../gtk+-3.24.42/gdk/x11 -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include/gio-unix-2.0 -I/opt/local/include/pango-1.0 -I/opt/local/include/harfbuzz -I/opt/local/include/fribidi -I/opt/local/include/cairo -I/opt/local/include/pixman-1 -I/opt/local/include/freetype2 -I/opt/local/include/libpng16 -I/opt/local/include/gdk-pixbuf-2.0 -I/opt/local/include/atk-1.0 -I/opt/local/include/at-spi2-atk/2.0 -I/opt/local/include/at-spi-2.0 -I/opt/local/include/dbus-1.0 -I/opt/local/lib/dbus-1.0/include -I/opt/local/include -fdiagnostics-color=always -Wall -Winvalid-pch -O2 -g -DG_LOG_USE_STRUCTURED=1 -DGLIB_MIN_REQUIRED_VERSION=GLIB_VERSION_2_56 -DGLIB_MAX_ALLOWED_VERSION=GLIB_VERSION_2_58 '-DGTK_VERSION="3.24.42"' -D_GNU_SOURCE -DG_ENABLE_DEBUG -pipe -Os -fstrict-aliasing -arch ppc -DX_LOCALE -MD -MQ docs/tools/doc-shooter.p/.._.._tests_gtkgears.c.o -MF docs/tools/doc-shooter.p/.._.._tests_gtkgears.c.o.d -o docs/tools/doc-shooter.p/.._.._tests_gtkgears.c.o -c ../gtk+-3.24.42/tests/gtkgears.c
> ../gtk+-3.24.42/tests/gtkgears.c: In function 'create_gear':
> ../gtk+-3.24.42/tests/gtkgears.c:309:5: error: implicit declaration of function 'sincos' [-Wimplicit-function-declaration]
>   309 |     sincos(i * 2.0 * G_PI / teeth + da * 0, &s[0], &c[0]);
>       |     ^~~~~~
> ../gtk+-3.24.42/tests/gtkgears.c:46:1: note: include '<math.h>' or provide a declaration of 'sincos'
>    45 | #include "gtkgears.h"
>   +++ |+#include <math.h>
>    46 | 
> ../gtk+-3.24.42/tests/gtkgears.c:309:5: warning: incompatible implicit declaration of built-in function 'sincos' [-Wbuiltin-declaration-mismatch]
>   309 |     sincos(i * 2.0 * G_PI / teeth + da * 0, &s[0], &c[0]);
>       |     ^~~~~~
> ../gtk+-3.24.42/tests/gtkgears.c:309:5: note: include '<math.h>' or provide a declaration of 'sincos'
> ../gtk+-3.24.42/tests/gtkgears.c: In function 'perspective':
> ../gtk+-3.24.42/tests/gtkgears.c:522:4: warning: incompatible implicit declaration of built-in function 'sincos' [-Wbuiltin-declaration-mismatch]
>   522 |    sincos(radians, &sine, &cosine);
>       |    ^~~~~~
> ../gtk+-3.24.42/tests/gtkgears.c:522:4: note: include '<math.h>' or provide a declaration of 'sincos'
> ```

I see nothing in the above command that's actually supplying the `legacy-support` include path.  How can `legacy-support` help you if you don't use it? :-)

There's no need to keep trying newer and newer `legacy-support-devel` versions; the relevant fix was in `legacy-support` commit `1849c3a`, which was included in `legacy-support-devel @20240619`, and that aspect hasn't changed since.

This may be another one of those things that's always been broken but didn't actually cause build failures until `gcc14` came along and got more picky.

**Comment by fhgwright** [comment]
> Have you tried without using `ccache`?

Actually, I doubt that `ccache` is the issue in this case, though I have had my suspicions about it in others.

**Comment by fhgwright** [comment]
@barracuda156 
Forgot the notification earlier.  See above.

**Comment by barracuda156** [comment]
> > So, it still fails with `legacy-support-devel` 20240723_0:
> > ```
> > FAILED: docs/tools/doc-shooter.p/.._.._tests_gtkgears.c.o 
> > ccache /opt/local/bin/gcc-mp-14 -arch ppc -Idocs/tools/doc-shooter.p -Idocs/tools -I../gtk+-3.24.42/docs/tools -I. -I../gtk+-3.24.42 -Igdk -I../gtk+-3.24.42/gdk -Igtk -I../gtk+-3.24.42/gtk -I../gtk+-3.24.42/tests -Igdk/x11 -I../gtk+-3.24.42/gdk/x11 -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include/gio-unix-2.0 -I/opt/local/include/pango-1.0 -I/opt/local/include/harfbuzz -I/opt/local/include/fribidi -I/opt/local/include/cairo -I/opt/local/include/pixman-1 -I/opt/local/include/freetype2 -I/opt/local/include/libpng16 -I/opt/local/include/gdk-pixbuf-2.0 -I/opt/local/include/atk-1.0 -I/opt/local/include/at-spi2-atk/2.0 -I/opt/local/include/at-spi-2.0 -I/opt/local/include/dbus-1.0 -I/opt/local/lib/dbus-1.0/include -I/opt/local/include -fdiagnostics-color=always -Wall -Winvalid-pch -O2 -g -DG_LOG_USE_STRUCTURED=1 -DGLIB_MIN_REQUIRED_VERSION=GLIB_VERSION_2_56 -DGLIB_MAX_ALLOWED_VERSION=GLIB_VERSION_2_58 '-DGTK_VERSION="3.24.42"' -D_GNU_SOURCE -DG_ENABLE_DEBUG -pipe -Os -fstrict-aliasing -arch ppc -DX_LOCALE -MD -MQ docs/tools/doc-shooter.p/.._.._tests_gtkgears.c.o -MF docs/tools/doc-shooter.p/.._.._tests_gtkgears.c.o.d -o docs/tools/doc-shooter.p/.._.._tests_gtkgears.c.o -c ../gtk+-3.24.42/tests/gtkgears.c
> > ../gtk+-3.24.42/tests/gtkgears.c: In function 'create_gear':
> > ../gtk+-3.24.42/tests/gtkgears.c:309:5: error: implicit declaration of function 'sincos' [-Wimplicit-function-declaration]
> >   309 |     sincos(i * 2.0 * G_PI / teeth + da * 0, &s[0], &c[0]);
> >       |     ^~~~~~
> > ../gtk+-3.24.42/tests/gtkgears.c:46:1: note: include '<math.h>' or provide a declaration of 'sincos'
> >    45 | #include "gtkgears.h"
> >   +++ |+#include <math.h>
> >    46 | 
> > ../gtk+-3.24.42/tests/gtkgears.c:309:5: warning: incompatible implicit declaration of built-in function 'sincos' [-Wbuiltin-declaration-mismatch]
> >   309 |     sincos(i * 2.0 * G_PI / teeth + da * 0, &s[0], &c[0]);
> >       |     ^~~~~~
> > ../gtk+-3.24.42/tests/gtkgears.c:309:5: note: include '<math.h>' or provide a declaration of 'sincos'
> > ../gtk+-3.24.42/tests/gtkgears.c: In function 'perspective':
> > ../gtk+-3.24.42/tests/gtkgears.c:522:4: warning: incompatible implicit declaration of built-in function 'sincos' [-Wbuiltin-declaration-mismatch]
> >   522 |    sincos(radians, &sine, &cosine);
> >       |    ^~~~~~
> > ../gtk+-3.24.42/tests/gtkgears.c:522:4: note: include '<math.h>' or provide a declaration of 'sincos'
> > ```
> 
> I see nothing in the above command that's actually supplying the `legacy-support` include path. How can `legacy-support` help you if you don't use it? :-)

@fhgwright There is even a ticket about this being broken in `gtk3`: https://trac.macports.org/ticket/70352
But I forgot about it :) 

I will try to inject flags and see if something changes (I have probably tried that before, but not sure now).

**Comment by reneeotten** [comment]
Feel free to reopen once someone actually fixed this - there doesn't appear to be any progress

**Comment by barracuda156** [comment]
@reneeotten Having gtk3 broken is not an acceptable state of things. If someone dislikes flags, then just disable tests. This has to be fixed this or that way.

**Comment by reneeotten** [comment]
well, then work to a finished PR that can be merged

**Pull request closed without merging**
