### PR TITLE
doclifter: update to 2.20

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by reneeotten — CHANGES_REQUESTED** [review]
as usual, please separate functional and non-functional changes into separate commits

**Comment by barracuda156** [comment]
> as usual, please separate functional and non-functional changes into separate commits

Done.

**Comment by reneeotten** [comment]
> > as usual, please separate functional and non-functional changes into separate commits
> 
> 
> 
> Done.

Please use meaningful commit messages, in other words something like: "add modeline, adjust whitespace"

**Comment by barracuda156** [comment]
> something like: "add modeline, adjust whitespace"

Changed to this.

**Review by reneeotten — APPROVED** [review]

**Pull request merged**
