### PR TITLE
vis5d: Drop ImageMagick dependency

### PR DESCRIPTION
**Pull request by Dave-Allured**
#### Description

* Remove optional, problematic ImageMagick dependency ("convert")
* Add completion note to install ImageMagick separately if needed
* Use modern checksums

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.6.7 21G651 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] (n/a) referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tried a full install with `port -v install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
@Dave-Allured this needs some kore content as it isn't clear to me from the description here why this change would be needed/is useful...

**Comment by Dave-Allured** [comment]
> this needs some more content as it isn't clear to me from the description here why this change would be needed/is useful...

Good question.  I need vis5d to work on NCARG family ports.  ImageMagick carries a large amount of dependency baggage; it was blocking build and test of NCARG family ports; this is a recurring problem; and its use in vis5d is peripheral and optional.  It is simple for the user to add it it later, if needed.

The last blocking issue was resolved only yesterday, but IM/cargo/rust will break again.
https://trac.macports.org/ticket/68026

> Also, if this change would be desirable, then the lines should be removed instead of commented out.

I would rather leave them in for documentation, and to facilitate reverting if wanted later.  This is a style issue.  Okay with you?

**Comment by reneeotten** [comment]
We don't want commented out lines, please remove. It's obvious that the dependency would need to be added again when you want to revert this change in the future.

**Comment by Dave-Allured** [comment]
> We don't want commented out lines, please remove.

Agreed.  I need to do more work on this port.  Closing this PR, will start a new one later.

**Pull request closed without merging**
