### PR TITLE
gsl: Update to 2.8

### PR DESCRIPTION
**Pull request by Dave-Allured**
#### Description

* Update GSL 2.7.1 --> 2.8.
* Update python_version from 3.9 to 3.12.
* Remove dynamic_lookup patch.  Was fixed upstream.
* Whitelist two functions for implicit declarations in configure.
* Add myself as co-maintainer.

###### Tested on

macOS 12.7.4 21H1123 x86_64
Xcode 14.2 14C18 / Command Line Tools 14.2.0

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tried a full install with `port -vs install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by Dave-Allured** [comment]
Please squash and merge.  I can not squash myself because my git access is impaired.

**Comment by barracuda156** [comment]
@Dave-Allured @pmetzger This has broken numerous ports. Perhaps everything which depends on `gsl`.

**Comment by pmetzger** [comment]
@barracuda156 Submit fixes?

**Comment by barracuda156** [comment]
@pmetzger Someone can do a mechanical revbump for all remaining ports, which will likely leave quite a number of those broken on CI, and I have no interest to deal with questions in that regard. There are people committing straight into the master here, perhaps a job for them :) 

Everything in R has been fixed, all my ports were, I think, and a number of other dependents.

_Whoever wants to take care of the rest, please do not unnecessarily revbump again those already fixed._

**Pull request merged**
