### PR TITLE
py-hypothesis: update to 4.11.6

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
- update to latest version

###### Tested on

macOS 10.14.3 18D109
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`? N/A
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kurthindenburg** [comment]
Typically for a major update, I try to check the changelog/changes file.  Perhaps add a note section to either check https://github.com/HypothesisWorks/hypothesis/blob/fdc8fce59b75c177e2d3807ddfc525c95d7c20fb/hypothesis-python/docs/changes.rst or maybe something like
"If you were running on the last version of Hypothesis 3.x without any Hypothesis deprecation warnings (or using private APIs), this upgrade should cause no issues.  Otherwise, see website
before removing the 3.x version."

There are a few other ports that use this; might want to check they work as well.

**Comment by reneeotten** [comment]
@kurthindenburg that's a good point. 

I looked closer at the ports that declare a dependency on ```py-hypothesis``` and from this list (py-attrs, py-brotlipy, py-cairo, py-hpack, py-parver, py-pyrsistent, and py-pytest-asyncio) only the tests of ```py-brotlipy``` do not pass anymore. But they don't declare a specific version dependency, so it's hard to tell unless you do run the tests of all ports that depend on py-hypothesis....

So what do you sugggest? I can close this PR and we leave it at version 3 for the time being, or I can add a note to the Portfile; let me know what you prefer.

**Comment by kurthindenburg** [comment]
py-brotlipy is up to date; so how about adding a note in py-hypothesis near the version # say that when updating to 4.0+, check all ports that depend on this and mention py-brotlipy fails ATM

**Comment by reneeotten** [comment]
@kurthindenburg okay, I looked a bit more closely and the only reason that the tests for ```py-brotlipy``` do not pass is because they exceed the 200 ms deadline. In version 4 of hypothesis this now results in an error; patching the tests to have no deadline lets them pass. I would be in favor of doing this and that would allow us to upgrade ```py-hypothesis``` to its latest version.

@yan12125 do you have any concerns/objections with respect to this patch of ```py-brotlipy```?

**Comment by yan12125** [comment]
Changes to py-brotlipy looks good to merge. Thanks for investigation and the patch!

**Comment by kurthindenburg** [comment]
Go ahead - thanks - you still might still add a note to hypothesis about the 3->4 upgrade

**Comment by reneeotten** [comment]
@kurthindenburg how about this? Feel free to merge when you're happy!

**Comment by kurthindenburg** [comment]
You have to revbump py-brotlipy for it to pick up the new patch

**Comment by reneeotten** [comment]
> You have to revbump py-brotlipy for it to pick up the new patch

true... sorry, done now!

**Pull request merged**
