### PR TITLE
gmp: update to 6.3.0

### PR DESCRIPTION
**Pull request by pguyot**
Remove patch that was included upstream
Remove unnecessary platforms line

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.0 23A344 x86_64
Xcode 15.0.1 15A507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
see PR #20313 - it doesn't look like this addresses any of the concerns there, so I don't think this should be merged.

**Comment by pguyot** [comment]
> see PR #20313 - it doesn't look like this addresses any of the concerns there, so I don't think this should be merged.

Didn't see PR #20313 as it was closed. Let's keep this one open and as draft.

**Comment by barracuda156** [comment]
@MarcusCalhoun-Lopez is right, like this it simply fails to build:
```
gen-sieve.c: In function ‘setmask’:
gen-sieve.c:99: error: ‘for’ loop initial declaration used outside C99 mode
./gen-fac 32 0 >fac_table.h || (rm -f fac_table.h; exit 1)
make: *** [gen-sieve] Error 1
```

**Comment by barracuda156** [comment]
On a side-note (unrelated to the failure), this seems incorrect:
```
triplet.cpu.ppc             powerpc750
triplet.cpu.ppc64           powerpc970
```
Why does it force G4 for `ppc`? I do not know how to test for it, but definitely G5 (970) supports `ppc`. AFAIK, `ppc970` is in fact a version of `ppc` (32-bit).

**Comment by barracuda156** [comment]
@catap Any idea how to fix this? The build system is surprisingly stubborn.

**Comment by kencu** [comment]
> On a side-note (unrelated to the failure), this seems incorrect:
> 
> ```
> triplet.cpu.ppc             powerpc750
> triplet.cpu.ppc64           powerpc970
> ```
> 
> Why does it force G4 for `ppc`? I do not know how to test for it, but definitely G5 (970) supports `ppc`. AFAIK, `ppc970` is in fact a version of `ppc` (32-bit).

those are set presuming a buildbot builds the binaries, or they might be used generically for distribution on any system. powerpc 750 assembly will run on all ppc systems. powerpc 970 assembly will run on all ppc64 systems. So those are safe assumptions.

if you want optimized assembly for your system, you build the +native variant.

**Comment by barracuda156** [comment]
@iains Iain, sorry to bother you, is the GCC upstream aware of this issue with the new `gmp`? If it cannot be built with `gcc-4.2`, bootstraps will be broken.

**Comment by iains** [comment]
> @iains Iain, sorry to bother you, is the GCC upstream aware of this issue with the new `gmp`? If it cannot be built with `gcc-4.2`, bootstraps will be broken.

I am not sure what you mean.

As far as GCC is concerned it cannot be bootstrapped by gcc-4.2 / early Xcode clang after GCC-10 (that is the last version buildable with C++98), so for MacOSX 10.4 - 10.8 you need to build gcc-10.x before you can bootstrap trunk.  I do not remember exactly what the prerequisite minimum versions are for GCC-10, but it certainly works properly with GMP-6.2.1.

Bootstrap will only be broken if you specify a non-supportable dependency (i.e. if you need C++11 to build GMP-6.3 and you need GMP to build a C++11 compiler then you need to specify an older GMP version for the bootstrap compiler).

Or, are you saying that GMP-6.3.0 cannot be built by GCC-10.5?

**Comment by iains** [comment]
> > On a side-note (unrelated to the failure), this seems incorrect:

> > `triplet.cpu.ppc             powerpc750`

^^^ this is broken - all the versions of MacOSX you care about need Altivec -  the OS default is **7400** for 10.5+

ppc750 is only relevant <=  MacOSX 10.3

> > ` triplet.cpu.ppc64           powerpc970`

^^^^ this is broken, although it is true that the 64b macOS systems are based on ppc970, that is not what it means in a CPU/CPU-subtype context.

on powerpc MacOSX - the 64 bit CPU is **always** "ppc64" with a sub-type of "all"

> > Why does it force G4 for `ppc`? I do not know how to test for it, but definitely G5 (970) supports `ppc`. 

As noted above, the correct default is "7400" - you will find, for example, that Rosetta-1 will just not work with anything else.

>> AFAIK, `ppc970` is in fact a version of `ppc` (32-bit).

right. although a ppc970 is 64-bit capable, in the Mach-O scheme "ppc970" is a sub-type for powerpc (32bit) with the intention of allowing a wider range of instructions.

One day, I want to investigate re-enabeling the ability to use ppc970 instructions in 32bit code (it would make atomics much nicer) - but that is currently broken [ _so do not do it_ ].

> those are set presuming a buildbot builds the binaries, or they might be used generically for distribution on any system. powerpc 750 assembly will run on all ppc or ppc64 systems. powerpc 970 assembly will run on all ppc64 systems. So those are safe assumptions.
> 
> if you want optimized assembly for your system, you build the +native variant.

triples for powerpc MacOSX are "powerpc-apple-darwinNN" and "powerpc64-apple-darwinNN" - if you want something special in a build you should use --with-tune=G5 or similar.

Alternate schemes might (or might not) work [they are certainly untested, and there is definitely not enough hardware or engineering resources to do so].

**Comment by iains** [comment]
> those are set presuming a buildbot builds the binaries, or they might be used generically for distribution on any system. powerpc 750 assembly will run on all ppc or ppc64 systems. powerpc 970 assembly will run on all ppc64 systems. So those are safe assumptions.

This seems reasonable; however (for example) configuring a compiler for those platforms will be broken on 10.5+ and likely broken for most 10.4 installations.

**Comment by kencu** [comment]
I certainly don't know everything about this!

But MacPorts still tries to support G3 processors for keen folks running TIger on them (@evanmiller , this is you!), so the "buildbot" tries to build ppc for the oldest ppc processor that could be supported. Of course, there is no MacPorts powerpc buildbot, but things are set up as if there were one.

So the most basic ppc processor MacPorts supports is a 750, and the "buildbot" would build for that.

Likewise, the most basic powerpc processor that can support ppc64 is (we think)  a 970.

gmp does a lot of fancy footwork to try to identify the exact processor they are building for (config.guess is a wrapper around configfsf.guess that runs a bunch of assembly tests to find the exact processor it is running on).

Then then once they have it nailed, in the gmp configure script, they do this:
```
      powerpc750)   gcc_cflags_cpu="-mcpu=750" ;;
      powerpc801)   gcc_cflags_cpu="-mcpu=801" ;;
      powerpc821)   gcc_cflags_cpu="-mcpu=821" ;;
      powerpc823)   gcc_cflags_cpu="-mcpu=823" ;;
      powerpc860)   gcc_cflags_cpu="-mcpu=860" ;;
      powerpc970)   gcc_cflags_cpu="-mtune=970"
```

MacPorts overrides this. On a ppc system, the build forces powerpc750 so it can run on all supported machines (G3 and up). On a ppc64 system, the build forces powerpc970, so it can run on all supported systems (G5 and up).

**Comment by kencu** [comment]
> > @iains Iain, sorry to bother you, is the GCC upstream aware of this issue with the new `gmp`? If it cannot be built with `gcc-4.2`, bootstraps will be broken.
> 
> I am not sure what you mean.


This is a "macports-specific" problem.

MacPorts builds gmp separately from gcc, not as part of the build. So the bootstrap on Macports builds all the gcc supporting software first, and then builds gcc against them.

So on macports, if gmp can't build with gcc-4.2, we are hosed for bootstrapping.

Not hosed, exactly .. somebody clever just needs to sort it out. (My suggestion would be to use gcc10-bootstrap to build it).

**Comment by barracuda156** [comment]
> > > @iains Iain, sorry to bother you, is the GCC upstream aware of this issue with the new `gmp`? If it cannot be built with `gcc-4.2`, bootstraps will be broken.
> > 
> > I am not sure what you mean.

@iains Well, gcc needs `gmp`, so if we cannot build `gmp` with a system compiler, it is a problem. In fact I thought it is a result of a negligence – that someone in `gmp` upstream did not bother to test. If it was a deliberate decision, we can’t help that, and should implement a reasonable solution on our end.

> So on macports, if gmp can't build with gcc-4.2, we are hosed for bootstrapping.
> 
> Not hosed, exactly .. somebody just needs to sort it out. (My suggestion would be to use gcc10-bootstrap to build it).

@kencu Yes, exactly. It is a solvable issue, but then we will need to have extra `gmp` pegged to a pre-C11 version – and I also thought about `gcc10-bootstrap` (once we dump gcc7 for good).

**Comment by iains** [comment]
Ah well, I was out of context, somewhat.

I see, (for the record, I did have Tiger installed on a Beige G3 [which is now in the attic], but it (a) required a special bootstrap workaround the fact that Apple did not want you to install it there and (b) was never reliable); 10.3 was a better bet there.

If this relates to GMP only, then perhaps it will be OK.

There comes a point where "one size fits all" is no longer reasonable (in the 10.5 era it was feasible, but that is long past on the x86_64 chain);  It's been a long time since I tried to target 10.3 or PPC750 for the compiler - the system tools on 10.3 are too old (even make) so it needs more-or-less a complete build from scratch, which is a very long job on the hardware I have that supports it.

Anyway, as noted above, the solution (required for many current packages), is to have an intermediate bootstrap compiler; I do plan to release a 10.5-darwin with as many of the current fixes as possible.  A possible scheme to avoiding the issue with needing multiple GMP et. al. would be to arrange to bootstrap the compiler with its prerequisites (actually, that is what I do every day) - that also means the behaviour of the compiler will not then change if someone updates GMP etc.

**Comment by barracuda156** [comment]
> A possible scheme to avoiding the issue with needing multiple GMP et. al. would be to arrange to bootstrap the compiler with its prerequisites (actually, that is what I do every day) - that also means the behaviour of the compiler will not then change if someone updates GMP etc.

@iains This is precisely what @catap ’s `gcc10-bootstrap` is doing; the only – temporary, I hope – issue is that Macports is still stuck with `gcc7` on < 10.6, which does use regular `gmp`.

**Comment by kencu** [comment]
> > > > @iains Iain, sorry to bother you, is the GCC upstream aware of this issue with the new `gmp`? If it cannot be built with `gcc-4.2`, bootstraps will be broken.
> > > 
> > > 
> > > I am not sure what you mean.
> 
> @iains Well, gcc needs `gmp`, so if we cannot build `gmp` with a system compiler, it is a problem. In fact I thought it is a result of a negligence – that someone in `gmp` upstream did not bother to test. If it was a deliberate decision, we can’t help that, and should implement a reasonable solution on our end.
> 
> > So on macports, if gmp can't build with gcc-4.2, we are hosed for bootstrapping.
> > Not hosed, exactly .. somebody just needs to sort it out. (My suggestion would be to use gcc10-bootstrap to build it).
> 
> @kencu Yes, exactly. It is a solvable issue, but then we will need to have extra `gmp` pegged to a pre-C11 version.

no we don’t.

**Comment by kencu** [comment]
> > A possible scheme to avoiding the issue with needing multiple GMP et. al. would be to arrange to bootstrap the compiler with its prerequisites (actually, that is what I do every day) - that also means the behaviour of the compiler will not then change if someone updates GMP etc.
> 
> @iains This is precisely what @catap ’s `gcc10-bootstrap` is doing; the only – temporary, I hope – issue is that Macports is still stuck with `gcc7` on < 10.6, which does use regular `gmp`.

Every gcc on macports uses “regular gmp” except gcc10-bootstrap, and that’s fine…

(caveat - not 100% sure of apple-gcc42, but irrelevant here).

**Comment by barracuda156** [comment]
> > @kencu Yes, exactly. It is a solvable issue, but then we will need to have extra `gmp` pegged to a pre-C11 version.
> 
> no we don’t.

@kencu How do you plan to build the version requiring C11 with a compiler supporting C11, or what do I miss?
`gcc10-bootstrap` just uses its own `gmp`. That should still be pegged for it to be usable.

**Comment by kencu** [comment]
observation: unless someone with some knowledge and interest steps up to do a proper job taking ownership of and maintaing the toolchain on the older systems very soon, MacPorts support for them will be coming to an end. 

You can’t just post endless questions and tickets… you have to post actual solutions and sorted-out fixes.

It is 100% unreasonable to hold this PR up for 2003-era system support…

**Comment by kencu** [comment]
> @kencu How do you plan to build the version requiring C11 with a compiler supporting C11, or what do I miss? `gcc10-bootstrap` just uses its own `gmp`. That should still be pegged for it to be usable.

it is already internally pegged to a suitable version in gcc19-bootstrap, because I pegged it that way

**Comment by barracuda156** [comment]
> observation: unless someone with some knowledge and interest steps up to do a proper job taking ownership of and maintaing the toolchain on the older systems very soon, MacPorts support for them will be coming to an end.

@kencu You know very well that I have been using the latest gcc releases for past 1.5 years, both on 10.6 and 10.5. So solution is there. (Yes, I remember about a recent universal build issue, that we will handle with @catap help.)
Solution has been there for many months, just no interest from anyone to merge it.

Macports artificially pegs Leopard to an awkward archaic config – it could have been using same defaults as on 10.6 (of course, with `libstdc++`, which should have been used for Intel too, as you mentioned you do yourself on your systems).

If `gcc13` works perfectly on 10A190 (with a 4 lines patch), it would work just as well on 10.5.8 (without any patching). _Save for Fortran intrinsics, of course, but that is a separate topic._

> It is 100% unreasonable to hold this PR up for 2003-era system support…

As for myself, I am perfectly fine to use `gcc10-bootstrap` to build `gmp` (and have  it updated). That won’t break old systems, and in fact move them closer to what they should be using – `gcc10-bootstrap` + `gcc13`.

**Comment by barracuda156** [comment]
@kencu @catap It is tricky: setting `gcc10-bootstrap` does not work:
```
configure: summary of build options:

  Version:           GNU MP 6.3.0
  Host type:         powerpc970-apple-darwin9
  ABI:               mode64
  Install prefix:    /opt/local
  Compiler:          /opt/local/libexec/gcc10-bootstrap/bin/gcc -arch ppc64
  Static libraries:  yes
  Shared libraries:  yes

--->  Building gmp
Executing:  cd "/opt/local/var/macports/build/_opt_PPCLeopardPorts_devel_gmp/gmp/work/gmp-6.3.0" && /usr/bin/make -j6 -w all 
make: Entering directory `/opt/local/var/macports/build/_opt_PPCLeopardPorts_devel_gmp/gmp/work/gmp-6.3.0'
/usr/bin/gcc-4.2 -arch ppc64 `test -f 'gen-fac.c' || echo './'`gen-fac.c -o gen-fac
/usr/bin/gcc-4.2 -arch ppc64 `test -f 'gen-sieve.c' || echo './'`gen-sieve.c -o gen-sieve
/usr/bin/gcc-4.2 -arch ppc64 `test -f 'gen-fib.c' || echo './'`gen-fib.c -o gen-fib
/usr/bin/gcc-4.2 -arch ppc64 `test -f 'gen-bases.c' || echo './'`gen-bases.c -o gen-bases -lm
/usr/bin/gcc-4.2 -arch ppc64 `test -f 'gen-trialdivtab.c' || echo './'`gen-trialdivtab.c -o gen-trialdivtab -lm
/usr/bin/gcc-4.2 -arch ppc64 `test -f 'gen-jacobitab.c' || echo './'`gen-jacobitab.c -o gen-jacobitab
/usr/bin/gcc-4.2 -arch ppc64 `test -f 'gen-psqr.c' || echo './'`gen-psqr.c -o gen-psqr -lm
gen-sieve.c: In function ‘setmask’:
gen-sieve.c:99: error: ‘for’ loop initial declaration used outside C99 mode
make: *** [gen-sieve] Error 1
make: *** Waiting for unfinished jobs....
```
The build still pulls out a system compiler.

P. S. This is on 10.5.8, and I just copypasted from my gcc13 portfile:
```
platform darwin {
    if {(${configure.build_arch} in [list ppc ppc64]) || ${os.major} < 10} {
        configure.compiler.add_deps \
                        no
        depends_build-append \
                        port:gcc10-bootstrap
        configure.cc    ${prefix}/libexec/gcc10-bootstrap/bin/gcc
        configure.cxx   ${prefix}/libexec/gcc10-bootstrap/bin/g++
    }
}
```

**Comment by kencu** [comment]
```
Some influential environment variables:
  ABI         desired ABI (for processors supporting more than one ABI)
  CC          C compiler command
  CFLAGS      C compiler flags
  LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
              nonstandard directory <lib dir>
  LIBS        libraries to pass to the linker, e.g. -l<library>
  CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
              you have headers in a nonstandard directory <include dir>
  CPP         C preprocessor
  CC_FOR_BUILD
              build system C compiler
  CPP_FOR_BUILD
              build system C preprocessor
```

try setting:
```
configure.env-append    CC_FOR_BUILD=${prefix}/libexec/gcc10-bootstrap/bin/gcc
```

I can never remember where the quotes are needed in that statement, so if it doesn't fly just like that, then try a couple of versions with quotes.

**Comment by barracuda156** [comment]
UPD. Indeed, this works correctly:
```
platform darwin {
    if {(${configure.build_arch} in [list ppc ppc64]) || ${os.major} < 10} {
        configure.compiler.add_deps \
                        no
        depends_build-append \
                        port:gcc10-bootstrap
        configure.cc    ${prefix}/libexec/gcc10-bootstrap/bin/gcc
        configure.cxx   ${prefix}/libexec/gcc10-bootstrap/bin/g++

        configure.env-append \
                        CC_FOR_BUILD=${prefix}/libexec/gcc10-bootstrap/bin/gcc
    }
}
```
```
36-24:~ svacchanda$ port -v installed gmp
The following ports are currently installed:
  gmp @6.3.0_0+universal (active) requested_variants='+universal' platform='darwin 9' archs='ppc ppc64' date='2023-11-02T01:59:37+0800'
```

**Comment by kencu** [comment]
Let’s get rid of all the 10.6 PPC-specific stuff.

Just use gcc10-bootstrap on all systems < 10.9.

That is neater, better, consistent, and requires nothing special for 10.6 ppc, which you know I will not commit.

**Comment by kencu** [comment]
All we need to see now is if gmp links back into gcc10-bootstrap’s libs. If so, then it either needs to be a lib dep, or static link.

**Comment by barracuda156** [comment]
> Just use gcc10-bootstrap on all systems < 10.9.
> 
> That is neater, better, consistent, and requires nothing special for 10.6 ppc, which you know I will not commit.

It is needed for 10.6.8 Rosetta just as much, since it has the same set of compilers. Xcode 4.2 does not support Rosetta at all, Xcode 3.2.6 has to use gcc-4.2 for ppc, just like 10.5.8.

> > Let’s get rid of all the 10.6 PPC-specific stuff.

The only result you gonna achieve by preventing fixing something is that less stuff will be fixed.

And while I can tolerate your, hmm, peculiar attitude to native 10.6 ppc, if credible fixes for Rosetta gonna be blocked – I will make it easier for you by not committing anything any further.
(_This_ is not my PR, of course, and my opinion is orthogonal; but if the port is left broken here, I will open a follow-up PR to fix it for Rosetta; if that will be vetoed – with no superior fix suggested, I will interpret that as a lack of interest in further cooperation on the project.)

**Comment by kencu** [comment]
I'm merely asking you to simplify your suggestion by using gcc10-bootstrap on all systems < 10.9, and get rid of the completely unnecessary 10.6-PPC specific stuff you have added in there.

ie:
```
platform darwin {
    if {${os.major} < 13} {
        configure.compiler.add_deps  no
        depends_build-append         port:gcc10-bootstrap
        configure.cc                 ${prefix}/libexec/gcc10-bootstrap/bin/gcc
        configure.cxx                ${prefix}/libexec/gcc10-bootstrap/bin/g++
        configure.env-append         CC_FOR_BUILD=${prefix}/libexec/gcc10-bootstrap/bin/gcc
    }
}
```

This is a fine general solution that also happens to fix the builds on the systems you uniquely care about, but without the usual 10.6-PPC spaghetti. This is much preferred.

I'm glad I could sort this out properly for you.

**Comment by kencu** [comment]
All suggestions are debatable, as we know. There are possibly other ways to fix gmp to build with gcc-4.2 again, should someone be interested in that. One might find a way to pass some flags in to the build that fix it, like ```-std=c99``` perhaps being patched in. That might work. Someone might feel there is no need to use gcc10-bootstrap on 10.8 if the system compiler works.

All valid ideas to explore with limitless time on one's hands.

But we're moving towards bootstrapping all newer gcc versions with gcc10-bootstrap on all systems, certainly on all older systems, and (IMHO) we might as well just use gcc10-bootstrap to build gcc's deps as well, and move along.

And these fixes can be applied to the general ports tree, fixing builds on many systems, without any need whatsoever for more and more and more and more 10.6-PPC specific spaghetti code, which will only, in end, drive everyone away from being interested in continuing support for the older systems altogether. 

You are already hearing that drumbeat. It will only get louder if you don't pay attention to it.

**Comment by MarcusCalhoun-Lopez** [comment]
I regret how little time I have been able to give to the MacPorts project.
Please forgive me if I am missing some important aspect of this conversation, but I believe GMP can be built on older systems if `-std=gnu99` is appended to `CC_FOR_BUILD`.
I have attempted to do this in #21224.
However, I would appreciate testing before committing.

**Comment by kencu** [comment]
Marcus has a different better fix for the build failure (setting the c standard) that would be good to go with. 

Another reprieve for old gcc-4.2!

**Comment by pmetzger** [comment]
I think this can be closed in favor of https://github.com/macports/macports-ports/pull/21224.

**Pull request closed without merging**
