### PR TITLE
liblas: create liblas-config needed for grass7

### PR DESCRIPTION
**Pull request by nilason**
#### Description

Presently liblas creates a liblas.pc file if pkg-config is installed. However, grass7 needs a liblas-config file for proper configuration.

This PR make liblas install a liblas-config file (instead of liblas.pc) as well as configures grass7 accordingly.

The other dependant of liblas: saga, compiled without complaint.

Addresses https://trac.macports.org/ticket/62489,

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.7 19H114
Xcode 12.1 12A7403

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by nilason** [comment]
@Veence Any thoughts or objections to this PR.

**Comment by Veence** [comment]
Absolutely not. If this can be done, it’s a wonderful addition!

**Comment by nilason** [comment]
If there are not objections to this PR, please go ahead and merge.
As there is no maintainer, perhaps @Veence , @ryandesign or @mf2k could step in.

**Comment by ryandesign** [comment]
> This PR make liblas install a liblas-config file (instead of liblas.pc)

That seems like a step backwards. -config scripts are deprecated. pkg-config files are the preferred replacement. Wouldn't it be better to fix grass7 so that it can use liblas's pkg-config file? Or to fix liblas so that it can install both a pkg-config file and a -config script instead of just one or the other?

There's another port besides grass7 that depends on liblas: saga. We should check that port as well.

**Comment by ryandesign** [comment]
> There's another port besides grass7 that depends on liblas: saga. We should check that port as well.

You said that it "compiled without complaint" but didn't specify whether that was before or after your change. I see that saga does not have a dependency on the pkgconfig port, so if it is able to use liblas's pkgconfig file then at least that dependency would need to be added to it.

**Comment by nilason** [comment]
> > This PR make liblas install a liblas-config file (instead of liblas.pc)
> 
> That seems like a step backwards. -config scripts are deprecated. pkg-config files are the preferred replacement. Wouldn't it be better to fix grass7 so that it can use liblas's pkg-config file? Or to fix liblas so that it can install both a pkg-config file and a -config script instead of just one or the other?
> 
> There's another port besides grass7 that depends on liblas: saga. We should check that port as well.

First of all `liblas` is on *maintenance* mode and replaced by `pdal`, so fix this upstreams on the liblas side is not a good alternative, nor on the GRASS side. Seems that liblas support has been failing for both [SAGA](https://trac.macports.org/ticket/53033)  and [GRASS](https://trac.macports.org/ticket/62489). This PR enables support for liblas for at least GRASS. I'm not a SAGA user but this PR doesn't make any changes on that side as far as I can tell (still getting `checking for LAS_GetVersion in -llas... no`).

**Comment by nilason** [comment]
Never mind.

**Comment by nilason** [comment]
Reopening, this is is still valid.
If this isn’t an acceptable solution to get liblas actually work with GRASS, do close this PR and remove liblas as a dependency.

**Comment by reneeotten** [comment]
@nilason @ryandesign @Veence I've patched the CMakeList.txt for `liblas` so that it installs both the `.pc` file for use with `pkgconfig` as well as the `liblas-config` file. That should resolve the issue here. In addition a few more corrections to the variants in `liblas` and an update to the latest upstream commit.

Please leave a comment whether you're satisfied with this solution; without any response I will merge this in a couple of days.

**Comment by Veence** [comment]
By all means, if that solves the issue at hand, go ahead!

**Comment by nilason** [comment]
I can’t test this at the moment, but it seems fine to me.

**Comment by nilason** [comment]
Thanks @reneeotten! I have now tested and the track issue leading to this is now resolved.

**Pull request merged**
