### PR TITLE
libplacebo: provide fallback version for old systems

### PR DESCRIPTION
**Pull request by barracuda156**
Closes: https://trac.macports.org/ticket/68962

P. S. This does not help us to fix `mpv` 0.37.0, but it is broken for several other reasons anyway.

UPD. Pause this until `legacysupport` issue is investigated. This may not fix PowerPC, but might fix 10.6 x86.

#### Description

Add a fallback.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by i0ntempest** [comment]
Do you need this for anything on 10.6? This is only there to support mpv 0.37 which does not build on 10.6 anyways.

**Comment by barracuda156** [comment]
@i0ntempest I might get it to work, though not today. So it can be useful for that. Like this we also do not have a broken port, since the earlier version builds normally with no hackery.
It also does not need any maintenance efforts from your side, just peg it and forget about it :)

**Comment by i0ntempest** [comment]
Fair enough. Though for a library like this I think it's better to make a separate `libplacebo5` port like a lot of other library ports do, to avoid incompatibility and stuff. If needed this older version can even be installed into another prefix so both versions can coexist.

**Comment by barracuda156** [comment]
@i0ntempest Ok, I can make a separate port, sure.

**Comment by kencu** [comment]
@i0ntempest -- the build failure on the 10.6 buildbot is exposing a bug with legacysupport's newer libcxx forcing....it has nothing to do with this port specifically.

it looks like this "C" build line has a bunch of cxx-specific stuff on it, and no surprise I guess it ultimately fails running across cxx code. 

Why are the cxx flags showing up on the "C" build? 

Well, it's because  legacysupport is  putting all the cxx-specific modifications onto the CPP flags for some reason, instead of the CXX flags, and so the C builds are picking them up.

```
CPPFLAGS='-isystem/opt/local/include/libcxx/v1 -nostdinc++ -isystem/opt/local/include/LegacySupport -I/opt/local/include'
```

this is just wrong.

```
/opt/local/bin/clang-mp-11 -Isrc/libplacebo.338.dylib.p -Isrc -I../libplacebo-6.338.1/src -Isrc/include -I../libplacebo-6.338.1/src/include -Isrc/opengl/include -I../libplacebo-6.338.1/src/opengl/include -Isrc/shaders -Isrc/vulkan -Isrc/opengl/include/glad -I/opt/local/include -fvisibility=hidden -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -std=c11 -O2 -g -Wundef -Wshadow -Wparentheses -Wpointer-arith -fno-math-errno -D_ISOC99_SOURCE -D_ISOC11_SOURCE -D_GNU_SOURCE -U__STRICT_ANSI__ -Wmissing-prototypes -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-type-limits -Werror=implicit-function-declaration -Werror=incompatible-pointer-types -Wno-missing-braces -Wundef -Wshadow -Wparentheses -Wpointer-arith -fno-math-errno -pipe -Os -arch x86_64 -nostdinc++ -DPL_HAVE_PTHREAD '' -DPL_EXPORT -MD -MQ src/libplacebo.338.dylib.p/meson-generated_.._shaders.c.o -MF src/libplacebo.338.dylib.p/meson-generated_.._shaders.c.o.d -o src/libplacebo.338.dylib.p/meson-generated_.._shaders.c.o -c src/shaders.c
In file included from src/shaders.c:19:
In file included from /opt/local/include/LegacySupport/math.h:77:
/opt/local/include/libcxx/v1/math.h:316:8: error: expected identifier or '('
extern "C" {
       ^
```

This probably means "we" need to go back and sort out properly how to add these flags.

**Comment by kencu** [comment]
(the linking failure on 10.6 PPC building with gcc-13 is some totally different thing).

**Comment by kencu** [comment]
Nothing in these build failures has anything to do with the capabilities of the 10.6 and earlier SDK or systems, by the way. 

Just bugs in the machine that need fixing. And in this case, they are our bugs in legacysupport.

**Comment by barracuda156** [comment]
@kencu Thank you! PowerPC aside, but `legacysupport` is a big concern, of course.

@catap FYI, we just talked about the thing, and here we go.

**Pull request closed without merging**
