### PR TITLE
brlaser: new port

### PR DESCRIPTION
**Pull request by evanmiller**
#### Description

[`brlaser`](https://github.com/pdewacht/brlaser) is an open-source CUPS driver for Brother monochrome laser printers, useful on systems where the proprietary driver is not available. The driver is packaged on FreeBSD as [print/brlaser](https://www.freshports.org/print/brlaser) and on Debian as [printer-driver-brlaser](https://packages.debian.org/sid/text/printer-driver-brlaser).

This port differs from the above packages in that it compiles and installs the PPD files themselves (with help from [`cups-ppdc`](https://ports.macports.org/port/cups-ppdc/details/)) instead of leaving it as a task to the user. The PPD files are installed to the same location that `cups-pdf` uses.

The notes field instructs end users on setting up a printer for the first time. Patches are included to assist with compilation and to enhance duplex printing – submitted upstream but the project is not especially active.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.4.11 8S165 Power Macintosh
Component versions: DevToolsCore-798.0; DevToolsSupport-794.0

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
test.run yes
test.target check

**Comment by kencu** [comment]
because this is nomantainer, and therefore will likely come up with tickets etc that we have to deal with somehow, could you take a few minutes and put a note of some kind into the patches you added (other than the path one, which is obvious) about why the patch is needed, and what it is doing exactly?

That will help someone like me to come along later and possibly fix whatever issues arises in the tickets later.

I have a monochrome brlaser, and it is working nicely with the Brother drivers now. Has been since 2005 in fact, on Tiger. But I guess some newer models might not be supported, etc, so this seems useful.

Is the path that the model ppds are being installed to something that other cups ports might want to also install stuff do (some HP cups port, Canon cups port, etc)? I guess there is no likelihood of trampling?

**Comment by evanmiller** [comment]
@kencu Updated the patches with some additional context.

I suppose a PPD name conflict could occur. We could provide a `brother` subdirectory, or prefix the file names with `brother_` if there is concern.

Debian's approach (or their 2006 approach) is described here: https://wiki.debian.org/PpdFileStructureSpecification

**Comment by evanmiller** [comment]
One other question: Would gzipped PPD files be preferred? Mac's print system can handle them directly back to 10.4 at least. It's as simple as adding `-z` to the `ppdc` command. The only drawback is that ".ppd.gz" files might cause some user confusion.

**Comment by kencu** [comment]
LGTM. Let's see how it flies in the wild.

**Pull request merged**
