### PR TITLE
python PG: prevent setuptool's easy_install from downloading software

### PR DESCRIPTION
**Pull request by kurthindenburg**
This adds an .cfg that forbirds easy_install from downloading any
required software.  It can be used in the buildbot or with port -t
(trace) to find dependencies not listed in a portfile.

See discussion in
https://lists.macports.org/pipermail/macports-dev/2017-November/036794.html

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kurthindenburg** [comment]
The error messages are very verbose and I'm not clear if end users will understand what's going on.  

Example: 
Note: Bypassing https://pypi.python.org/simple/pytest-runner/ (disallowed host;
see http://bit.ly/1dg9ijs for details).
Couldn't find index page for 'pytest-runner' (maybe misspelled?)
Note: Bypassing https://pypi.python.org/simple/ (disallowed host; see http://bit
.ly/1dg9ijs for details).
No local packages or working download links found for pytest-runner

**Comment by mojca** [comment]
I find it a bit weird to call this every single time any given python module gets extracted.

**Comment by raimue** [comment]
We cannot place the configuration file in the system-wide location, as that would affect all uses of setuptools. The only other way would be to move such a configuration setup to base for all ports. But as this is only required for python modules, the python port group seems like the best place to me.

I would not worry too much about the error messages for end users.

**Comment by mojca** [comment]
My only question is: is there an elegant way to make this change just once instead of for every single activation of every single port?

If not and if it works ... go for it.

**Comment by kurthindenburg** [comment]
Would it make sense to have the file somewhere under ${prefix}/etc/macports/ (or somewhere else) and then just copy/ln it to the port's work/.home?

For it to work, I don't how having it for every python extraction can be avoided.

**Comment by ryandesign** [comment]
Wonderfully, the bit.ly URL mentioned in the error message doesn't work. The URL it probably means to refer to is http://setuptools.readthedocs.io/en/latest/easy_install.html#restricting-downloads-with-allow-hosts

It's fine to create the file in the port's home directory every time. The disk I/O involved in creating that file will be dwarfed by the amount of I/O needed to extract the distfile. Still, the file could be made smaller by dispensing with the comments. If you must keep the comments, my nitpick is that your possessives of "MacPorts" and "setuptools" are wrong.

You can avoid the need to escape special characters in the strings by quoting them with `{}` instead of `""`.

Could you use `$env(HOME)` instead of hardcoding its value?

**Comment by kurthindenburg** [comment]
Thanks, I've updated it per your suggestions.  Not sure what to do about the bad URL

**Comment by kurthindenburg** [comment]
I've enter an issue w/ setuptools github - we could patch py-setuptools if necessary

**Comment by kurthindenburg** [comment]
the URL should be fixed in setuptools' next release

**Comment by raimue** [comment]
@kurthindenburg I do not see any updates to the proposed changes. Did you forget to push them to this branch?

**Pull request closed without merging**
