### PR TITLE
Add perl5.32

### PR DESCRIPTION
**Pull request by mojca**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G9016
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
  - tons of failures
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mojca** [comment]
There is a bunch of relatively high priority tickets in trac, but for many of them I'm not exactly sure how to address them. Some about 10.4 support, some about 11.0, some about known long-standing issues that perl bakes in the compiler being used.

I'm getting quite some unit tests failed though.

**Comment by dbevans** [comment]
> There is a bunch of relatively high priority tickets in trac, but for many of them I'm not exactly sure how to address them. Some about 10.4 support, some about 11.0, some about known long-standing issues that perl bakes in the compiler being used.
> 
> I'm getting quite some unit tests failed though.

Most if not all of these occur on 10.6 or earlier with the exception of the 11.0 stuff.  Unfortunately, I don't have access to any of these platforms so no way to work it all out.  Perhaps some of our legacy experts such as @kencu can shed some light on these older problems and/or people with access to BigSur might chime in.  

I'm surprised you're having problems with the unit tests.  I would have expected it to build and test on 10.7-10.15 without problems.  Would sending you my successful build/test log be of any help?  Or I'd be glad to look at your failing one.

**Comment by dbevans** [comment]
Here's my logfile: [main-perl5.32-10.15.log](https://github.com/macports/macports-ports/files/4899791/main-perl5.32-10.15.log)

**Comment by kencu** [comment]
I was wondering if we still needed the miniperl hack to prevent linking against anything in ```${prefix}/lib```. Originally I believe it was placed to prevent picking up the ```libstdc++.6.dylib``` in ```${prefix}/lib```, which was failing. 

I suspect the symlink to ```${prefix}/lib/libstdc++.6.dylib``` has outlived it's usefulness, and removing that symlink would solve the issue in a cleaner fashion, but it's admittedly hard to account for every single possibility without removing it. (I did remove that symlink from my 10.4 systems -- it was causing cross-arch universal builds to fail -- and nothing bad happened doing so.)

Stripping out ```-L${prefix}/lib``` is OK so long as everything is left totally default, and it works as is, but it does make things a bit atypical and generates unexpected linking errors.

1. the configure phase runs it's tests assuming linking into ```${prefix}/lib``` works, but then at build time, the link directory is stripped, so linking can break. That was my primary problem.
2. nothing in ${prefix}/lib can be linked against. That prevents builds with any macports gcc versions, which right now is not an issue I believe, but I haven't tried this perl5.32 against ```gcc-4.2``` yet to see.

**Comment by mojca** [comment]
We also need this: https://github.com/Perl/perl5/pull/17946#issuecomment-657039885

**Pull request merged**
