### PR TITLE
py-openstackclient: submission with deps and update py-novaclient to 17.2.0

### PR DESCRIPTION
**Pull request by someuser12**
#### Description

py-openstackclient: submission with dependencies
py-novaclient: update to 17.2.0 with new dependencies

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.6 / 10.14.6
Xcode 9.1 / 10.3

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by someuser12** [comment]
I don't understand why the build on Azure failed: according to the log, all ports and all subports (for Python 36/37/38) successfully installed, and yet Bash exited with code 1 at the very end of the build and installation process.
Can someone please help? Thanks in advance!

**Comment by ryandesign** [comment]
> I don't understand why the build on Azure failed

Me neither! Let's merge it and if there's a problem on the buildbot hopefully it'll make it more clear.

**Comment by ryandesign** [comment]
```
--->  Fetching distfiles for py36-openstacksdk
Error: No such port: py36-jsonpatch
```
```
--->  Fetching distfiles for py37-keystoneclient
Error: No such port: py37-oslo-config
```

**Comment by ryandesign** [comment]
So the py-oslo-config port is completely missing. Is this another port you developed that you didn't include in this PR? You could add it in a new PR.

As for py-jsonpatch, it's only available for py37 and py38. You could either add py36 to py-jsonpatch, or remove py36 from the ports you added that depend on it.

**Comment by someuser12** [comment]
My mistake, I forgot to add py-oslo-config to the PR. Many thanks for looking into this. I submitted py-oslo-config (along with an updated py-jsonpatch with py36 added as it seems to be supported upstream) in #7915.

**Pull request merged**
