### PR TITLE
py-userpath: update to 1.8.0, add py311 subport

### PR DESCRIPTION
**Pull request by mndavidoff**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.6.3 21G419 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by 0az** [comment]
Feel free to remove me as maintainer, as I haven't gotten around to setting up macports on my new laptop.

**Comment by mndavidoff** [comment]
@0az, I've incorporated your request to drop maintainership into this PR. Thanks!

**Review by reneeotten — CHANGES_REQUESTED** [review]
since the port now uses `hatch` as the build system, `setuptools` is no longer a build dependency. Additionally, `setuptools` is neither a runtime dependency anymore - so the dependency should be removed.

**Comment by mndavidoff** [comment]
@reneeotten, thank you for catching that! I've removed the dependency on `setuptools`.

**Review by reneeotten — APPROVED** [review]

**Comment by reneeotten** [comment]
thanks @mndavidoff !

**Pull request merged**
