### PR TITLE
Update libwebsockets and mosquitto.

### PR DESCRIPTION
**Pull request by slewsys**
#### Description
Update libwebsockets to version 3.0.1.
Fix tests for mosquitto 1.5.1.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Hrm. Your commit message for mosquitto seems wrong. It claims to be an update of the port rather than a bugfix.

**Comment by slewsys** [comment]
On Sep 16, 2018, at 9:45 AM, Perry E. Metzger <notifications@github.com> wrote:
> 
> Hrm. Your commit message for mosquitto seems wrong. It claims to be an update of the port rather than a bugfix.

I realized, after the fact, that an update had already been committed.  But my PR should produce the same binary, so the revision should be okay as is, I think.  In that sense, is it not just an update of the test suite?
-AM

**Comment by pmetzger** [comment]
The commit message needs to reflect what the commit does...

**Comment by slewsys** [comment]
Okay, PR marked as bugfix and commit message for mosquitto marked accordingly.  Sorry for the confusion on my part.

**Comment by pmetzger** [comment]
Merged. Thanks, @slewsys!

**Pull request merged**
