### PR TITLE
py-asn1-modules: update to 0.2.2

### PR DESCRIPTION
**Pull request by skymoo**
also adds python37 subport

### CODE REVIEW

**Comment by pmetzger** [comment]
@eighthave is there a good reason this can't go `openmaintainer`?

**Comment by pmetzger** [comment]
Update looks good to me, btw.

**Comment by reneeotten** [comment]
@pmetzger @skymoo thanks! However, it actually doesn't install with the following error:
```Error: Failed to destroot py27-asn1-modules: xinstall: Cannot stat: README.txt, No such file or directory``` ; that file has been renamed to ```README.md```. 

A few additional suggestions: it should probably declare a dependency on ```py-asn1``` [(see here)](https://github.com/etingof/pyasn1-modules/blob/ac6ae3f2d72dcc53b6e691e218b2c43156aac5cb/setup.py#L71) and I would add ```py-setuptools``` as a build dependency. Finally, the livecheck can/should be simplified and use most of the PyPI defaults, you can remove the last three lines and only add ```livecheck.name pyasn1-modules```.

**Comment by skymoo** [comment]
I noticed that and pushed a fix, not sure why it built initially when I tested it?

**Comment by skymoo** [comment]
All good suggestions, I'll take a look.

**Comment by skymoo** [comment]
Those comments should now be addressed.

**Comment by skymoo** [comment]
I was planning on doing that, once all the comments had been addressed. I'll get that done now and then wait a few days for @eighthave to weigh in.

**Comment by pmetzger** [comment]
@skymoo Can you add `openmaintainer`?

**Comment by skymoo** [comment]
I'll try and do that later, having some technical problems with my internet at the moment. Seems like my WiFi router has died.

**Comment by skymoo** [comment]
Openmaintainer added

**Comment by pmetzger** [comment]
Merged. Thanks, @skymoo!

**Pull request merged**
