### PR TITLE
golang-1.0: use vendored modules

### PR DESCRIPTION
**Pull request by gpanders**
#### Description

This addresses https://trac.macports.org/ticket/61192 by putting vendored dependencies into the `vendor` directory during the extract phase, thus avoiding downloading dependencies during the build phase. However, this also has the added benefit of supporting Go modules (which are increasingly common).

If the package being installed contains a `go.mod` file then this will use the vendored dependencies under the `vendor` directory without downloading anything else; otherwise, the `vendor` directory is simply used as the `GOPATH`.

Some background: I was trying to update the caddy port (which is now quite out-of-date), but the mechanism that Caddy uses to insert version information into the binary is only possible using Go module mode. However, [#61992][1] disables Go's module mode across the board, forcing all Go ports to use the old GOPATH mode.

I think it is a good idea to have some path forward for migrating to module mode, as this is the direction the Go ecosystem is moving and not adapting will just add further maintenance burden to Go port maintainers.

This solution enables Go ports to utilize Go modules while still satisfying the requirements of [#61192][1].

I am new to the MacPorts community and I did my best to adhere to conventions and standards as well as I could, but undoubtedly there are likely ways that this PR can be improved and I am of course happy to accept any feedback.

I am also marking this as a Draft because, as written, this breaks some current Go ports (e.g. I know for sure that it breaks shfmt), but I don't think it is that difficult to fix those. Before going through and extensively testing and fixing existing Go ports, I wanted to solicit feedback from MacPorts maintainers on this idea in general.

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.7 19H524
Xcode 12.4 12D4e

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] ~~checked your Portfile with `port lint`?~~ N/A
- [ ] ~~tried existing tests with `sudo port test`?~~ N/A
- [ ] ~~tried a full install with `sudo port -vst install`?~~ N/A
- [ ] ~~tested basic functionality of all binary files?~~ N/A

[1]: https://trac.macports.org/ticket/61192

### CODE REVIEW

**Comment by herbygillot** [comment]
Thanks for proposing this, @gpanders.

As your solution currently is now, all the pre-downloaded dependencies defined in `go.vendors` are completely ignored when  `go mod vendor` is run. As far as I can tell, Go looks like it's going right to the Internet and downloading them all again when you call that in the `pre-build` phase.

I'm not sure, but perhaps it's a matter of setting `GOPATH` and setting `GOPROXY=off` to get it to vendor from the locally extracted directories of the pre-fetched modules.

Secondly, a number of Go ports already provide their own `vendor` directories as well. So you will probably want to check for that before attempting to create or modify the `vendor` directory within `${worksrcpath}`.

I definitely agree that we should move towards using Go modules proper, but overall I'm not 100% sure about this approach.

In my experience, the bulk of the pain has actually been with defining the `go.vendors` section itself:

- You cannot specify a Go module from just any arbitrary domain in `go.vendors`
- There are issues when specifying nested modules with a common module parent (something like `mydomain/me/my_mod/custom-mod1` and `mydomain/me/my_mod/custom-mod2` will cause a failure if both are defined in `go.vendors`, if I recall correctly).

**Comment by gpanders** [comment]
> On Mar 23, 2021, at 19:36, Herby Gillot ***@***.***> wrote:
> 
> As your solution currently is now, all the pre-downloaded dependencies defined in go.vendors are completely ignored when go mod vendor is run. As far as I can tell, Go looks like it's going right to the Internet and downloading them all again when you call that in the pre-build phase.

I don’t think this is correct. I tried this myself earlier: I put all of the dependencies in the vendor directory (without modules.txt), disabled the Internet connection on my machine, and then ran ‘go mod vendor’. This successfully generated the modules.txt file without attempting to download anything (which would have failed if it tried).

Maybe there are some cases where it will try to re-download the dependencies, but I can at least say that it doesn’t always do this.
> Secondly, a number of Go ports already provide their own vendor directories as well. So you will probably want to check for that before attempting to create or modify the vendor directory within ${worksrcpath}.
> 
If the port does not define the go.vendors variable (which it should not if it is already vendoring its dependencies) then it won’t try to create or modify the vendors directory. I actually think that is a strength of this approach, in that it supports both methods equally.
> In my experience, the bulk of the pain has actually been with defining the go.vendors section itself:
> 
> You cannot specify a Go module from just any arbitrary domain in go.vendors
> There are issues when specifying nested modules with a common module parent (something like mydomain/me/my_mod/custom-mod1 and mydomain/me/my_mod/custom-mod2 will cause a failure if both are defined in go.vendors, if I recall correctly).

Agreed on this point. In fact I ran into both of these issues while working this out earlier today.

**Comment by herbygillot** [comment]
> I don’t think this is correct. I tried this myself earlier: I put all of the dependencies in the vendor directory (without modules.txt), disabled the Internet connection on my machine, and then ran ‘go mod vendor’. This successfully generated the modules.txt file without attempting to download anything (which would have failed if it tried). Maybe there are some cases where it will try to re-download the dependencies, but I can at least say that it doesn’t always do this.

Alright, then perhaps I was missing something.

> Secondly, a number of Go ports already provide their own vendor directories as well. So you will probably want to check for that before attempting to create or modify the vendor directory within ${worksrcpath}.
> If the port does not define the go.vendors variable (which it should not if it is already vendoring its dependencies) then it won’t try to create or modify the vendors directory. I actually think that is a strength of this approach, in that it supports both methods equally.

That's a good point.

It would definitely be good to hear from others. Perhaps @amake, @l2dy, @breun and @cardi could chime in as well.

**Comment by amake** [comment]
> This solution enables Go ports to utilize Go modules while still satisfying the requirements of [#61192](https://trac.macports.org/ticket/61192).

This doesn't address at all one of the major reasons for the efforts in that ticket: if you're not using the MacPorts fetch mechanism then you're not using the MacPorts mirroring infrastructure; if you're not using MacPorts' mirroring then you're a) putting strain on external resources and b) excluding older systems that don't have support for the most recent TLS or whatever.

Maybe we don't care about those things (mostly we hit GitHub and GitHub can handle the strain; systems that old maybe can't run Go anyway). But I wanted to push back on the idea that this PR would solve all concerns.

> I am also marking this as a Draft because, as written, this breaks some current Go ports (e.g. I know for sure that it breaks shfmt), but I don't think it is that difficult to fix those. Before going through and extensively testing and fixing existing Go ports, I wanted to solicit feedback from MacPorts maintainers on this idea in general.

I don't really know off the top of my head if this approach is tenable or not. I think you have to go try fixing the ports that break to see if it will pan out.

**Comment by herbygillot** [comment]
> > This solution enables Go ports to utilize Go modules while still satisfying the requirements of [#61192](https://trac.macports.org/ticket/61192).
> 
> This doesn't address at all one of the major reasons for the efforts in that ticket: if you're not using the MacPorts fetch mechanism then you're not using the MacPorts mirroring infrastructure; if you're not using MacPorts' mirroring then you're a) putting strain on external resources and b) excluding older systems that don't have support for the most recent TLS or whatever.

Just some clarification here, @amake; @gpanders is still using `go.vendors` to populate the `vendor` directory.  MacPorts will still continue to fetch and cache dependencies specified in the `go.vendors` section.  That part doesn't change.

Basically `go.vendors` behaves the same up until extraction.  What will happen with this change is that now the `go.vendors` dependencies will be extracted to an _in-source_ `vendor` directory, _instead_ of to `$GOPATH/src`.

The point of this is so that projects can continue to build without fetching deps at build time, but allows doing so without having to turn off Go modules (`GO111MODULE=off`).

**Comment by amake** [comment]
Thank you @herbygillot, I should have looked more closely at the proposal. Sorry for that.

I guess if it really works as it's supposed to then sure, why not! But again I suspect the true test of feasibility is figuring out what's wrong with the ports that this breaks.

**Comment by breun** [comment]
> It would definitely be good to hear from others. Perhaps @amake, @l2dy, @breun and @cardi could chime in as well.

I maintain a couple of Go-based ports because I use those tools for my daily work, but I don’t understand much about the Go build system. I was just barely able to create working ports for them, so I’m afraid I’m not of much use in this discussion.

By the way, if anyone more familiar with Go knows how to improve my Go-based ports (`gitlab-runner`, `kustomize`, `skaffold`, `k9s`) and make them and make them work with the golang portgroup’s default `GOPROXY=off GO111MODULE=off`, please be my guest. (Also `kubectx` still needs to be switched from the old bash-based version to the new Go-based rewrite.)

**Comment by gpanders** [comment]
@breun `gitlab-runner`, `kustomize`, and `k9s` all install without any modification. `skaffold` does not use the `golang` group so it also doesn't need to be modified.

I added modifications to `kustomize` and `k9s` in this PR to remove the `build.env-delete GOPROXY=off GO111MODULE=off` line, since that is no longer necessary.

@amake I also have a modification to `shfmt` in this PR so that it builds under this new paradigm. The only change is updating its build directory.

I will continue to test other Go ports update them to work and tag their maintainers in this thread.

**Comment by gpanders** [comment]
@ra1nb0w

**Comment by ra1nb0w** [comment]
gopls builds fine.

**Comment by gpanders** [comment]
>As your solution currently is now, all the pre-downloaded dependencies defined in go.vendors are completely ignored when go mod vendor is run. As far as I can tell, Go looks like it's going right to the Internet and downloading them all again when you call that in the pre-build phase.

Alas, I found a scenario where this is true. If a vendored dependency itself has vendored dependencies, then `go mod vendor` will try to "flatten" all of the nested dependencies which results in go downloading some dependencies at build time. I am honestly not sure of a way around this outside of some fragile kind of shell black magic that recursively copies nested `vendor` dependencies up to the top level directory. But then at that point we're on the road to re-creating the Go build system.

Maybe this has already been discussed extensively elsewhere, but I want to at least address the points that @amake brought up about the need for not downloading Go modules directly using `go`:

>This doesn't address at all one of the major reasons for the efforts in that ticket: if you're not using the MacPorts fetch mechanism then you're not using the MacPorts mirroring infrastructure; if you're not using MacPorts' mirroring then you're a) putting strain on external resources and b) excluding older systems that don't have support for the most recent TLS or whatever.

>Maybe we don't care about those things (mostly we hit GitHub and GitHub can handle the strain; systems that old maybe can't run Go anyway). But I wanted to push back on the idea that this PR would solve all concerns.

The cost of doing things the way they are done now is that we are essentially building and maintaining our own Go build system alongside the one that Go itself provides. As others in this thread have pointed out, this is hard and error-prone: it requires a custom tool (`go2port`) to enumerate the dependencies (which is redundant, since they are already enumerated alongside a hash in the `go.mod` and `go.sum` files), it doesn't support all domains, and increasingly more and more Go modules *require* being built in module-mode and won't work in GOPATH mode (just search through the ports directory for ports containing `build.env-delete GO111MODULE=off GOPROXY=off`).

As far as point (a) above, at least since version 1.13, Go uses a proxy by default (https://proxy.golang.org). We can enable this explicitly for older versions with `GOPROXY=https://proxy.golang.org`.

In addition, Go caches all downloaded content by default into the GOPATH. If we run `go mod download` with `GOPATH=/opt/local/var/go` (or perhaps a port-specific directory) then MacPorts can maintain a machine-specific cache of Go modules. This would further reduce network usage when building Go ports from source and reduce strain on external services.

Finally, both points above only apply when someone is building a port from source; once a port is built and cached by MacPorts then we are back to using MacPorts mirroring infrastructure anyway.

**Comment by herbygillot** [comment]
> In addition, Go caches all downloaded content by default into the GOPATH. If we run go mod download with GOPATH=/opt/local/var/go (or perhaps a port-specific directory) then MacPorts can maintain a machine-specific cache of Go modules. This would further reduce network usage when building Go ports from source and reduce strain on external services.
>
> Finally, both points above only apply when someone is building a port from source; once a port is built and cached by MacPorts then we are back to using MacPorts mirroring infrastructure anyway.

The main goal here is to make Golang dependencies visible to MacPorts as **`distfiles`** (replete with associated `checksums`).

This enables MacPorts to cache and distribute every Go module dependency tarball to MacPorts mirrors.  So now even if a particular module disappears from the Internet or its domain or project goes offline, MacPorts will still be able to build the port.  The `go.vendors` section is what abstracts all of the above (adding to `distfiles` and `checksums`).

**Comment by amake** [comment]
> The cost of doing things the way they are done now is that we are essentially building and maintaining our own Go build system alongside the one that Go itself provides

Yes, this is the fundamental disconnect.

Language ecosystems are more and more including package managers in their build systems, and these are in general not compatible with the kind of control that MacPorts, as a package manager, wants to have.

I don't disagree with any of your points. I think it's basically impossible to satisfy all needs at once.

`go2port` represents my best effort at satisfying all of MacPorts' needs, with the limitation that some go projects simply can't be built with it.

The opposite end of the spectrum is to give up and just let `go mod` do its thing entirely. Some packages currently do this.

I would not be surprised if we simply can't find a single solution that satisfies everyone.

**Comment by reneeotten** [comment]
I don't know anything about `go` or the specifics of the PortGroup and such... but, we should either close this PR or try and make progress to get this merged... Opinions?!

**Comment by reneeotten** [comment]
if there are no response here, I'll close the PR by Friday, January 21

**Comment by gpanders** [comment]
@reneeotten I will go ahead and close it now. Thanks to all who participated in the conversation. Maybe in the future someone else can pick this up where I left off.

**Pull request closed without merging**
