### PR TITLE
dns-server: Add hard-coded network settings to address portindex issue

### PR DESCRIPTION
**Pull request by essandess**
dns-server: Add hard-coded network settings to address portindex issue

* Use default hard-coded example configuration settings
* Put network settings in `pre-build` block as recommended
* Use `awks`'s `$NF` to get default interfaces
* Resolves: https://trac.macports.org/ticket/58668

#### Description

@mf2k @kencu @tobypeterson @raimue @jmroot 

Re: this comment:

> This port is broken on 10.15, it makes incorrect assumptions about the output of netstat (looks like you want $4).

I don't see anything online that the basic BSD `netstat` command has changed in Catalina (that would be a big change for long-standing important network system call). I suspect the issue has to do with individual network settings. I fixed it by simply grabbing that last field output by `netstat -nr`, rather than a field number. @tobypeterson would you please confirm the fix?

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.5 18F132
Xcode 10.2.1 10E1001

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jmroot** [comment]
What happens if you perform this sequence of actions?
```
sudo port clean dns-server
sudo port build dns-server
sudo port install dns-server
```
What about this one?
```
sudo port install dns-server
sudo port deactivate dns-server
sudo port activate dns-server
```

**Comment by essandess** [comment]
@jmroot Both sequence of `port` commands work.

**Comment by jmroot** [comment]
I'm sure they execute without errors, but what values end up in the files?

**Comment by essandess** [comment]
> what values end up in the files?

Network values for the specific system doing the build. E.g. from the buildbot logs above, https://paste.macports.org/abf589807b20:
```
        Host                       
        Domain                     Traviss-Mac
        TLD                        local
        Host IP Address            10.182.11.187
        Reverse IP Subnet          11.182.10
```

Even though these are correctly populated, there are two, or maybe 1.5 issues here:

First issue: The MacPorts distro will mirror whatever the buildbot settings were, including `db.*` file names! That’s not good. What’s the right approach?
* Turn off auto-build distribution in the Portfile?
* Turn off all the shell code that generates a network-specific install?
I’m partial to the first option, turning off build distros, both because there’s noting to build and because the installed DNS configuration will likely be much closer to what users want than hard coded defaults.

Second (half) issue: Is it clear enough that the installed DNS configuration must likely be edited further, perhaps a lot, depending on the complexity of the desired configuration? The whole point of this port is to provide a basic working example of a DNS server that’s close to deployment configuration.

**Comment by pmetzger** [comment]
@jmroot Are you happy at this point?

**Comment by jmroot** [comment]
> @jmroot Are you happy at this point?

I don't see how it can possibly work properly, but the change certainly fixes the problem of shelling out multiple times to parse the portfile.

**Comment by mojca** [comment]
I'm not against merging as that's probably better than before (I did not test), but I'm far from happy.

If this absolutely needs to be done, I would do it in post-activate step, even better in port notes, but for other reasons listed by the author, I have some troubles understanding the purpose. What does Debian do/install?

**Comment by pmetzger** [comment]
Regardless, someone will need to make a decision about merging this and not leave @essandess hanging.

**Comment by essandess** [comment]
Is there a Portfile setting that prevents archiving and requires building from source? Like a Portfile-specific `buildfromsource` directive?

That would address my own concerns. If not, we can just use hard-coded example settings.

I’m not in a hurry to get this merged—I just want it done right. My own DNS server is based on this Portfile (and vice-versa) and it’s rock solid.

As noted elsewhere, this port simply provides pre-configured example config files, which will have to be modified by users for their own networks. In that sense, it’s guaranteed not to “work properly,” but this is a lot better than having to start from scratch to configure DNS, which is the situation with a bare-metal `bind9` install. Personally, I think it’s a necessary port to provide a simple, working DNS server configuration.

The situation is the same for configuring the mail server ports, a [calendarserver](https://github.com/apple/ccs-calendarserver) (which must be added), a [VPN server](https://github.com/macports/macports-ports/pull/4743), and possibly more.

I’d like to get some consensus on how to automatically add network settings more-or-less robustly to ports that provide complex configuration files for various server services.

**Comment by essandess** [comment]
> I would do it in post-activate step, even better in port notes

This is probably the easiest/best suggestion. It leaves automatically configured stuff out of destroot, and keeps intact all the `@MAGIC_WORDS@` used for sed substitution, which can be handled in `post-activate`.

> I have some troubles understanding the purpose. What does Debian do/install?

This port provides a simple, working example DNS configuration on top of the `bind9` port.
The DNS config files in this port are basically a copy-and-paste of [now-defunct](https://developer.apple.com/support/macos-server/macOS-Server-Service-Migration-Guide.pdf) macOS Server.app DNS Server. AFAIK, there isn’t a Linux-equivalent rpm for DNS configuration—Linux rpm’s provide a bare-metal `named` binary just like `port:bind9`. But it’s really nice to run a `port install ; port load` command and get a working DNS server without too much effort, just like it was nice to launch Server.app and get a working DNS server.

**Comment by essandess** [comment]
The latest commit addresses all the points above, and works. The contents are listed below, and these template files are configured in the `post-activate` stage:
```
Port dns-server contains:
  /opt/local/etc/named.conf.macports
  /opt/local/var/log/named/.turd_dns-server
  /opt/local/var/named/db.@LAN_REVERSE_IP_SUBNET@.in-addr.arpa.macports
  /opt/local/var/named/db.@domain@.@tld@.macports
  /opt/local/var/named/db.@domain@.private.macports
  /opt/local/var/named/localhost.zone.macports
  /opt/local/var/named/named.ca.macports
  /opt/local/var/named/named.local.macports
```

**Comment by pmetzger** [comment]
@jmroot ?

**Comment by mojca** [comment]
I didn't test anything, but I already like the current state a lot more than what it used to be.

**Comment by jmroot** [comment]
Looks better.

**Comment by pmetzger** [comment]
I'm going to merge this for now. If there's a desire for further improvements, I'm sure they can be made in future commits.

**Pull request merged**
