### PR TITLE
apache-arrow: update to 15.0.1

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Let’s try this again :) 

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
```
  /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
  !!
  
          ********************************************************************************
          Requirements should be satisfied by a PEP 517 installer.
          If you are using pip, you can try `pip install --use-pep517`.
          ********************************************************************************
  
  !!
    dist.fetch_build_eggs(dist.setup_requires)
  WARNING: The index url "''" seems invalid, please provide a scheme.
  WARNING: Location '''/setuptools-scm/' is ignored: it is either a non-existing path or lacks a specific scheme.
  WARNING: Location '''' is ignored: it is either a non-existing path or lacks a specific scheme.
  ERROR: Could not find a version that satisfies the requirement setuptools_scm<8.0.0 (from versions: none)
  ERROR: No matching distribution found for setuptools_scm<8.0.0
  Traceback (most recent call last):
    File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
      subprocess.check_call(cmd)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/opt/local/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_apache-arrow/py39-pyarrow/work/.tmp/tmpvl615im1', '--quiet', '--index-url', "''", '--find-links', "''", 'setuptools_scm<8.0.0']' returned non-zero exit status 1.
```

**Comment by reneeotten** [comment]
Looking at the error message you could/should probably just patch out the version requirement for setuptools-scm

**Comment by barracuda156** [comment]
> Looking at the error message you could/should probably just patch out the version requirement for setuptools-scm

Let me try.

**Comment by barracuda156** [comment]
Let me close this for now :) 
Sorry.

I will need to update this anyway, for `R` at least, but so far v. 13 is acceptable, and I have more urgent stuff to deal with atm.

Gonna return to this in a while, but let not keep this hanging.

**Pull request closed without merging**
