### PR TITLE
mdds: update to 2.1.1

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

UPD. Let us rather do it one by one. Existing in Macports [outdated] version of `libetonyek` does not depend on `mdds`. Update `mdds` first.

Both ports are long due to be updated. `mdds` and `liblangtag` are now dependencies for `libetonyek`.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
While gcc build is fine, clang fails on:
```
  In file included from /opt/local/include/mdds-2.1/mdds/flat_segment_tree.hpp:39:
  /opt/local/include/mdds-2.1/mdds/global.hpp:161:47: error: no template named 'bool_constant' in namespace 'std'; did you mean '_BoolConstant'?
  using const_t = typename const_or_not<T, std::bool_constant<Const>>::type;
                                           ~~~~~^~~~~~~~~~~~~
                                                _BoolConstant
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/c++/v1/__type_traits/integral_constant.h:41:1: note: '_BoolConstant' declared here
  using _BoolConstant _LIBCPP_NODEBUG = integral_constant<bool, _Val>;
  ^
  In file included from IWAParser.cpp:10:
  In file included from ./IWAParser.h:27:
  In file included from /opt/local/include/mdds-2.1/mdds/flat_segment_tree.hpp:39:
  /opt/local/include/mdds-2.1/mdds/global.hpp:179:51: error: no template named 'bool_constant' in namespace 'std'; did you mean '_BoolConstant'?
  using mutable_t = typename mutable_or_not<T, std::bool_constant<Mutable>>::type;
                                               ~~~~~^~~~~~~~~~~~~
                                                    _BoolConstant
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/c++/v1/__type_traits/integral_constant.h:41:1: note: '_BoolConstant' declared here
  using _BoolConstant _LIBCPP_NODEBUG = integral_constant<bool, _Val>;
  ^
  In file included from IWAParser.cpp:10:
  In file included from ./IWAParser.h:27:
  In file included from /opt/local/include/mdds-2.1/mdds/flat_segment_tree.hpp:39:
  /opt/local/include/mdds-2.1/mdds/global.hpp:208:28: error: no template named 'void_t' in namespace 'std'; did you mean '__void_t'?
  struct is_complete<T, std::void_t<decltype(sizeof(T) != 0)>> : std::true_type
                        ~~~~~^~~~~~
                             __void_t
```

**Comment by barracuda156** [comment]
@mascguy Maintainer timeout, perhaps we could merge this?

**Comment by mascguy** [comment]
You should also rev-bump the dependents:

```
* ixion
* libreoffice
* orcus
```

**Comment by barracuda156** [comment]
> You should also rev-bump the dependents:
> 
> ```
> * ixion
> * libreoffice
> * orcus
> ```

@mascguy `libreoffice` looks pretty broken, I will just revbump it and other won’t touch. Other two can be updated instead of revbumping archaic versions. I will try and we see if everything builds.

**Comment by mascguy** [comment]
> > You should also rev-bump the dependents:
> > ```
> > * ixion
> > * libreoffice
> > * orcus
> > ```
> 
> @mascguy `libreoffice` looks pretty broken, I will just revbump it and otherwise won’t touch. Other two can be updated instead of revbumping archaic versions. I will try and we see if everything builds.

If you want, go ahead and drop the rev-bump for `libreoffice`, otherwise the CI will likely fail. (And it will take a LONG time to build anyway.)

**Comment by barracuda156** [comment]
@mascguy Yeah, that is better indeed.

**Comment by barracuda156** [comment]
@mascguy All good without `libreoffice`.

**Review by mascguy — APPROVED** [review]
LGTM

**Comment by mascguy** [comment]
Sergey, I'll rev-bump `libreoffice` directly via master.

**Comment by RJVB** [comment]
>@mascguy Maintainer timeout

Wow, the timeout is 4 days nowadays? :D

**Comment by mascguy** [comment]
> @mascguy Maintainer timeout
> Wow, the timeout is 4 days nowadays? :D

Technically it's only 3 days, so we gave folks an extra day here.  ;-)

**Comment by RJVB** [comment]
>Technically it's only 3 days, so we gave folks an extra day here.  ;-)

Start paying and you can make it 1 day ;)

**Pull request merged**
