### PR TITLE
topgrade: update to 4.8.0

### PR DESCRIPTION
**Pull request by lhaeger**
###### Tested on

macOS 10.15.5 19F101
Xcode 11.5 11E608c

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
@lhaeger the build fails on macOS 10.15 on the [buildbot](https://build.macports.org/builders/ports-10.15_x86_64-builder/builds/32813), whereas you appear to be able to build it locally. Can you please check why that is the case and try to fix that?

**Comment by lhaeger** [comment]
> @lhaeger the build fails on macOS 10.15 on the [buildbot](https://build.macports.org/builders/ports-10.15_x86_64-builder/builds/32813), whereas you appear to be able to build it locally. Can you please check why that is the case and try to fix that?

I've looked at it with 4.7.1 already and it seems the same error again. No idea what causes it, maybe someone else?

```
error: failed to run custom build command for `mac-notification-sys v0.3.0`

Caused by:
  process didn't exit successfully: `/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_sysutils_topgrade/topgrade/work/r-darwish-topgrade-13108cf/target/release/build/mac-notification-sys-f2296c698065d792/build-script-build` (exit code: 1)
--- stdout
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = Some("/usr/bin/clang")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
running: "/usr/bin/clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=x86_64-apple-darwin" "-fmodules" "-o" "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_sysutils_topgrade/topgrade/work/r-darwish-topgrade-13108cf/target/x86_64-apple-darwin/release/build/mac-notification-sys-aee1f985994aca81/out/objc/notify.o" "-c" "objc/notify.m"
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/libxml2/libxml/module.modulemap:1:8: error: redefinition of module 'libxml2'
cargo:warning=module libxml2 [system] [extern_c] {
cargo:warning=       ^
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/libxml2/module.modulemap:1:8: note: previously defined here
cargo:warning=module libxml2 [system] [extern_c] {
cargo:warning=       ^
cargo:warning=While building module 'Foundation' imported from objc/notify.h:1:
cargo:warning=While building module 'CoreFoundation' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
cargo:warning=While building module 'Dispatch' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
cargo:warning=In file included from <module-includes>:1:
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/dispatch/dispatch.h:59:10: fatal error: could not build module 'os_object'
cargo:warning=#include <os/object.h>
cargo:warning= ~~~~~~~~^
cargo:warning=While building module 'Foundation' imported from objc/notify.h:1:
cargo:warning=While building module 'CoreFoundation' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
cargo:warning=In file included from <module-includes>:1:
cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:60:
cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:17:
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:10: fatal error: could not build module 'Dispatch'
cargo:warning=#include <dispatch/dispatch.h>
cargo:warning= ~~~~~~~~^
cargo:warning=While building module 'Foundation' imported from objc/notify.h:1:
cargo:warning=In file included from <module-includes>:1:
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: fatal error: could not build module 'CoreFoundation'
cargo:warning=#include <CoreFoundation/CoreFoundation.h>
cargo:warning= ~~~~~~~~^
cargo:warning=While building module 'Foundation' imported from objc/notify.h:1:
cargo:warning=While building module 'CoreGraphics' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSGeometry.h:9:
cargo:warning=In file included from <module-includes>:1:
cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CoreGraphics.h:8:
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGBase.h:12:10: fatal error: could not build module 'CoreFoundation'
cargo:warning=#include <CoreFoundation/CFBase.h>
cargo:warning= ~~~~~~~~^
cargo:warning=While building module 'Foundation' imported from objc/notify.h:1:
cargo:warning=While building module 'CoreGraphics' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSGeometry.h:9:
cargo:warning=While building module 'IOKit' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDisplayConfiguration.h:12:
cargo:warning=In file included from <module-includes>:4:
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOCFBundle.h:26:10: fatal error: could not build module 'CoreFoundation'
cargo:warning=#include <CoreFoundation/CoreFoundation.h>
cargo:warning= ~~~~~~~~^
cargo:warning=While building module 'Foundation' imported from objc/notify.h:1:
cargo:warning=While building module 'Security' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9:
cargo:warning=In file included from <module-includes>:1:
cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:27:
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:28:10: fatal error: could not build module 'CoreFoundation'
cargo:warning=#include <CoreFoundation/CFBase.h>
cargo:warning= ~~~~~~~~^
cargo:warning=While building module 'Foundation' imported from objc/notify.h:1:
cargo:warning=While building module 'CoreServices' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:15:
cargo:warning=In file included from <module-includes>:1:
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:19:10: fatal error: could not build module 'CoreFoundation'
cargo:warning=#include <CoreFoundation/CoreFoundation.h>
cargo:warning= ~~~~~~~~^
cargo:warning=While building module 'Foundation' imported from objc/notify.h:1:
cargo:warning=While building module 'CoreServices' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:15:
cargo:warning=While building module 'DiskArbitration' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Files.h:56:
cargo:warning=In file included from <module-includes>:1:
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/DiskArbitration.framework/Headers/DiskArbitration.h:27:10: fatal error: could not build module 'CoreFoundation'
cargo:warning=#include <CoreFoundation/CoreFoundation.h>
cargo:warning= ~~~~~~~~^
cargo:warning=While building module 'Foundation' imported from objc/notify.h:1:
cargo:warning=While building module 'CoreServices' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:15:
cargo:warning=While building module 'CFNetwork' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:31:
cargo:warning=In file included from <module-includes>:1:
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CFNetwork.framework/Headers/CFNetwork.h:18:10: fatal error: could not build module 'CoreFoundation'
cargo:warning=#include <CoreFoundation/CoreFoundation.h>
cargo:warning= ~~~~~~~~^
cargo:warning=While building module 'Foundation' imported from objc/notify.h:1:
cargo:warning=While building module 'XPC' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:14:
cargo:warning=In file included from <module-includes>:1:
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/xpc/xpc.h:6:10: fatal error: could not build module 'os_object'
cargo:warning=#include <os/object.h>
cargo:warning= ~~~~~~~~^
cargo:warning=While building module 'Foundation' imported from objc/notify.h:1:
cargo:warning=While building module 'ApplicationServices' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSAppleEventDescriptor.h:9:
cargo:warning=In file included from <module-includes>:1:
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23:10: fatal error: could not build module 'CoreServices'
cargo:warning=#include <CoreServices/CoreServices.h>
cargo:warning= ~~~~~~~~^
cargo:warning=While building module 'Foundation' imported from objc/notify.h:1:
cargo:warning=While building module 'ApplicationServices' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSAppleEventDescriptor.h:9:
cargo:warning=While building module 'CoreText' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/ATS.framework/Headers/SFNTLayoutTypes.h:16:
cargo:warning=In file included from <module-includes>:1:
cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreText.framework/Headers/CoreText.h:20:
cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFont.h:20:
cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFontDescriptor.h:20:
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFontTraits.h:14:10: fatal error: could not build module 'CoreFoundation'
cargo:warning=#include <CoreFoundation/CoreFoundation.h>
cargo:warning= ~~~~~~~~^
cargo:warning=While building module 'Foundation' imported from objc/notify.h:1:
cargo:warning=While building module 'ApplicationServices' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSAppleEventDescriptor.h:9:
cargo:warning=While building module 'ColorSync' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:31:
cargo:warning=In file included from <module-includes>:1:
cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/ColorSync.framework/Headers/ColorSync.h:10:
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/ColorSync.framework/Headers/ColorSyncBase.h:12:10: fatal error: could not build module 'CoreFoundation'
cargo:warning=#include <CoreFoundation/CoreFoundation.h>
cargo:warning= ~~~~~~~~^
cargo:warning=While building module 'Foundation' imported from objc/notify.h:1:
cargo:warning=While building module 'ApplicationServices' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSAppleEventDescriptor.h:9:
cargo:warning=While building module 'ImageIO' imported from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:47:
cargo:warning=In file included from <module-includes>:1:
cargo:warning=In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/ImageIO.framework/Headers/ImageIO.h:10:
cargo:warning=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/ImageIO.framework/Headers/ImageIOBase.h:16:10: fatal error: could not build module 'CoreFoundation'
cargo:warning=#include <CoreFoundation/CoreFoundation.h>
cargo:warning= ~~~~~~~~^
cargo:warning=In file included from objc/notify.m:1:
cargo:warning=objc/notify.h:1:9: fatal error: could not build module 'Foundation'
cargo:warning=#import <Foundation/Foundation.h>
cargo:warning= ~~~~~~~^
cargo:warning=16 errors generated.
exit code: 1

--- stderr


error occurred: Command "/usr/bin/clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=x86_64-apple-darwin" "-fmodules" "-o" "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_sysutils_topgrade/topgrade/work/r-darwish-topgrade-13108cf/target/x86_64-apple-darwin/release/build/mac-notification-sys-aee1f985994aca81/out/objc/notify.o" "-c" "objc/notify.m" with args "clang" did not execute successfully (status code exit code: 1).



warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by lhaeger** [comment]
Hmm, some kind of conflict between the Commadn Line tools and the libxml2 port, maybe? I have 
```
 port installed libxml2
The following ports are currently installed:
  libxml2 @2.9.10_0 (active)
```
locally as a dependency from some other port, I guess.

**Comment by lhaeger** [comment]
please have a look if https://github.com/macports/macports-ports/pull/7487 builds successfully, preferably before merging in to master.

**Pull request merged**
