### PR TITLE
py-setuptools_scm: fix py38–39 subports

### PR DESCRIPTION
**Pull request by barracuda156**
Fixes: https://trac.macports.org/ticket/69106

#### Description

Build fails when earlier versions are installed, but only for Python 3.8–3.9, AFAICT.
See upstream response in: https://github.com/pypa/setuptools_scm/issues/1013

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@stromnov @ryandesign @reneeotten `py35-setuptools_scm` and `py36-setuptools_scm` fail on macOS-14 CI, and I did not touch these subports. Are they even supported on Sonoma?

**Comment by barracuda156** [comment]
Logs do not show what exactly fails. But something with dependencies for py35 and py36 subports.
```
/Users/runner/work/_temp/058d8285-9376-4a3e-90a8-5615335c364f.sh: line 6:  3957 Terminated: 15          tail -f "$workdir/logs/dependencies-progress.txt" 2> /dev/null
```

**Comment by barracuda156** [comment]
Well, amazing, `python36` is marked as known to fail, but CI fails due to that:
```
init took 0 seconds
Deactivating unneeded ports:
deactivating unneeded ports took 0 seconds

Error: python36 is known to fail
Error: mportdepends py36-setuptools_scm activate failed: 1
Processing dependencies for 'py36-setuptools_scm' failed, aborting.
/Users/runner/work/macports-ports/macports-ports/mpbb/mpbb: error: `install-dependencies' failed to run successfully
```

**Comment by barracuda156** [comment]
@jmroot Is this an expected behavior? It seems meaningless to require every dependency of Python 3.6 to be marked as unsupported on Sonoma, yet CI fail due to Python 3.6 being known to fail there.

**Comment by barracuda156** [comment]
@stromnov Should we disable `py35-setuptools_scm` and `py36-setuptools_scm` on Sonoma?

**Comment by barracuda156** [comment]
@reneeotten @herbygillot This is perhaps good to merge now.

**Comment by reneeotten** [comment]
I will take a look, adding a `conflicts_build` on itself isn't a great solution and I am not sure I have seen an issue before and/or whether this is the correct solution

**Comment by reneeotten** [comment]
> I will take a look, adding a `conflicts_build` on itself isn't a great solution and I am not sure I have seen an issue before and/or whether this is the correct solution

please provide exact command to reproduce the issue; I don't see any trouble and also the buildbots seem perfectly fine. So this could possibly just be an issue on very old OSes although that is kind of hard to imagine.... For whoever sees this issues are you 100% sure you haven't installed anything with `pip` or something similar outside of the the usual MacPorts' packages?

**Comment by jmroot** [comment]
Buildbot will never have an older version active. If this needs to override the installed version with the version being built, setting `PYTHONPATH` to its location under `${worksrcpath}` would be the way to do that.

**Comment by reneeotten** [comment]
> Buildbot will never have an older version active. If this needs to override the installed version with the version being built, setting `PYTHONPATH` to its location under `${worksrcpath}` would be the way to do that.

Sure, the buildbot doesn't but I couldn't reproduce this locally quickly/easily either. But your suggestion is for sure a good one, and much better than defining a "conflicts_build".

**Comment by barracuda156** [comment]
@reneeotten @jmroot Let’s go with the solution advised by Josh, of course. (I cannot test anything for older OS at the moment, away from my hardware for a while, but the problem exists there, and any fix to the same effect will do, it does not have to be a self-conflict. My solution was just based on the reply from upstream, who do not know Macports specifics.)

Should it be just `PYTHONPATH=${worksrcpath}/build/lib` passed to `build.env` or something else?

**Comment by barracuda156** [comment]
@jmroot @reneeotten Could someone please say what exactly should be passed? I have tried `build.env-append PYTHONPATH=` with `${worksrcpath}`, `${worksrcpath}/src` and `${worksrcpath}/build/lib`, neither of those helped. (I do not know what is needed, I just tried values seen in other portfiles.)

**Comment by stromnov** [comment]
Is it possible that we just need to upgrade or get rid of py-bootstrap-modules?

**Comment by pmetzger** [comment]
This has been in "draft" for four months. I'd propose we close it until it can be worked on if it cannot be advanced soon.

**Comment by barracuda156** [comment]
We got many people here, who deal with Python ports. Maybe someone can fix it? It should not be something specific to powerpc.

P. S. A trivial solution of self-conflict works fine, by the way. If it is not needed for newer systems, it can easily be done conditionally.

**Comment by pmetzger** [comment]
We have many people who _could_ fix something, but it is difficult to motivate other people to fix things that one cares about oneself. I'd suggest you might want to find a way to fix this, or we might want to close it for now.

**Comment by pmetzger** [comment]
I'm going to close this for now. We can, of course, re-open it at will.

**Comment by barracuda156** [comment]
@kencu Ken, could you say if this is an issue on Intel 10.5?

@pmetzger Of course, if this is really specific to 10.6 ppc, we can ignore it. But I doubt it is the case.

**Comment by pmetzger** [comment]
My issue isn't with whether it is or isn't a problem. It's that the PR queue isn't for reminding us of outstanding bugs, it's a list of things to be committed to the repository. (We really should bring the main bug database into Github of course but that's a distinct issue.)

**Comment by barracuda156** [comment]
@pmetzger My solution with self-conflict mights not be the best possible, _but it fixes the problem_. Honestly, this should just be merged as is. Until someone comes up with a more aesthetically pleasing solution.

Closing the PR you just leave the issue unfixed. One still needs to deactivate `py39-setuptools_scm` to update it, but now one has to _guess_ it is needed.

How is this a better thing than just fixing it?

**Comment by pmetzger** [comment]
If I can't commit a PR, it's not a PR, it's a bug report. Fixing the bug would be great, but until someone tells me that there's a pull request I can click "merge" on, it's not really a pull request at all.

**Pull request closed without merging**
