### PR TITLE
asdf-binary-locations: delete port

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Maintainer recommended this port be deleted.
See: https://trac.macports.org/ticket/56472
See: https://trac.macports.org/ticket/58311

Alternative option: keep the port, ask maintainer if it should be designated `nomaintainer`.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

### CODE REVIEW

**Comment by mf2k** [comment]
A agree about asdf-binary-locations, but not about cl-ppcre. It seems to still be an active port upstream. I also filed a port abandoned ticket for these ports.

**Comment by chrstphrchvz** [comment]
> A agree about asdf-binary-locations, but not about cl-ppcre. It seems to still be an active port upstream.

If preferred, I can split this PR into one for deleting `asdf-binary-locations` and the `cl-ppcre +asdf_binary_locations` variant (which is the only dependency of `asdf-binary-locations`), and then what to do with `cl-ppcre` is decided in another.

In the event `asdf-binary-locations` is kept, it should be marked as deprecated (it is discontinued by its author: https://www.cliki.net/ASDF-Binary-Locations). I wonder if the `cl-ppcre +asdf_binary_locations` variant is still even useful with newer versions of cl-ppcre. 

(Future idea: if MacPorts indeed begins "using" upt, then maybe someone can add a Quicklisp frontend to upt, and let MacPorts use that to get packages like cl-ppcre.)

>I also filed a port abandoned ticket for these ports.

I have revised this PR to mention that ticket.

**Comment by mojca** [comment]
> (Future idea: if MacPorts indeed begins "using" upt, then maybe someone can add a Quicklisp frontend to upt, and let MacPorts use that to get packages like cl-ppcre.)

You should put this idea forward to some more visible place (mailing list etc.). There are too many comments in individual pull requests for the developers to follow, and this one will get lost. (Note: I have no idea what quicklisp is, and didn't try to investigate it now.)

**Comment by chrstphrchvz** [comment]
> You should put this idea forward to some more visible place (mailing list etc.). There are too many comments in individual pull requests for the developers to follow, and this one will get lost. (Note: I have no idea what quicklisp is, and didn't try to investigate it now.)

Will do, thanks for the suggestion.

**Comment by chrstphrchvz** [comment]
To make this more likely to be merged, I have dropped deleting `cl-ppcre` and instead only delete `asdf-binary-locations` and the `cl-ppcre +asdf_binary_locations` variant.

**Comment by cjones051073** [comment]
This PR has hit maintainer timeout. So, where do we stand on merging it ?

**Comment by cjones051073** [comment]
Ping everyone ?

**Comment by mf2k** [comment]
I think we are good to go.

**Pull request merged**
