### PR TITLE
wget: explicit ./configure --options and dependencies

### PR DESCRIPTION
**Pull request by janstary**
Add explicit --options in ./configure --help order.
Fix the hidden dependency on libiconv and zlib.

Tested on 10.13.2

### CODE REVIEW

**Comment by janstary** [comment]
Some of the individual `--options` are debatable of course.

Do we want the valgrnd testing? If so, we need valgrind, and make it a dependency.
Now, valgrind is not available everywhere.  So disable it for now.
Do we want non-English messages? No, so `--disable-nls`.
Persnaly, I would aso disable IDN.

Please speak up if you want other options, or to make them a variant.
Please test everywhere.

**Comment by janstary** [comment]
The `--without-ssl` gets overwriten in the default `+ssl` variant.
There are other SSL options (the naming is a mess), but that's for later.

**Comment by pmetzger** [comment]
Why --without-ssl ?? That means no https: support...

**Comment by pmetzger** [comment]
(Yes, I know it was that way already. But why?)

**Comment by ryandesign** [comment]
We definitely want IDN support and NLS.

**Comment by janstary** [comment]
@ryandesign fixed, thanks. Are there any other objections to the options?

I squashed but messed up. I will prepare a cleaner PR.

Does this warant a revision bump?

**Comment by janstary** [comment]
@pmetzger Yes, it was already like that. Most ports do it like that:
`--without-ssl` in the default `configure.args`,  the the various variants rewrite it,
e.g. `+ssl` does `--with-ssl=openssl`, `+gnutls` does `--with-ssl-gnutls`, etc.
See e.g curl with its many `*ssl` variants.

**Comment by ryandesign** [comment]
`--without-libintl-prefix` is probably wrong, since we do want libintl (a.k.a gettext) for NLS.

The ssl variant could be made more clear: instead of just deleting `--without-ssl`, use `configure.args-replace` to replace `--without-ssl` with whatever the opposite is (either `--with-ssl` or a flag that allows specifying the prefix).

I haven't compared each of the proposed new configure flags with the configure script's defaults so I don't know if a revision increase is needed. If we're just explicitly specifying what the configure script would have already done, then no revision increase.

**Comment by pmetzger** [comment]
I understand that perhaps many ports do this, but it makes no sense to me that they would, since ssl is so critical in a file transfer utility.

**Comment by ryandesign** [comment]
Understand that wget includes https support by default, by virtue of the fact that the +ssl variant is enabled by default. The variant exists so that users who desire to do so can disable ssl support by deselecting the variant.

**Comment by ryandesign** [comment]
wget only has a single variant for ssl support, but other ports like curl have several, so there the user not only has a choice to disable ssl support, but if they do want ssl they can also choose which library they use to provide the ssl implementation.

**Comment by pmetzger** [comment]
Ah, I missed this set of details. Thanks for explaining, @ryandesign!

**Pull request closed without merging**
