### PR TITLE
gds: Modified for C++ 2017 standard

### PR DESCRIPTION
**Pull request by emaros**
* XCode 9.3 enforces more of the C++ 2017 standard

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.12.6 16G1404
Xcode 9.2 9C40b

and

macOS 10.13.3 17D47
Xcode 9.3 9E145

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by emaros** [comment]
This package requires more time than what Travis CI allows.

**Comment by pmetzger** [comment]
Travis often fails on such things. That's not a real problem.

Have these patches been submitted upstream? Are they going to be integrated?

**Comment by pmetzger** [comment]
Oh and btw, not relevant for this update, but Python 2.7 is going out of support soon, so an update upstream to allow use of Python 3 would be a good idea.

**Comment by emaros** [comment]
The patch was derived from working on the upstream code so will not be needed next time the code is release. Python 3 work has started, but is not yet fully vetted.

**Comment by pmetzger** [comment]
One last question: what happens when this builds under an earlier XCode? Does it still work?

**Comment by skymoo** [comment]
I've started a builds on High Sierra and Sierra to confirm.

**Comment by skymoo** [comment]
Builds for me on both platforms.

**Comment by pmetzger** [comment]
Merged. If there are significant buildbot issues, do try to deal with them.

**Comment by emaros** [comment]
The big issue that I have with the buildbot at this point is that one of the dependencies does not install the way I need it. Root5 installs with no variants, but this package requires the +python27 variant. Is there a way I can describe this in the Portfile so the buildbot will install root5 such that I can build against it?

**Comment by pmetzger** [comment]
@emaros I don't know. Perhaps you should ask on the macports-dev mailing list?

**Pull request merged**
