### PR TITLE
py-pypdf: obsolete, replaced by py-pypdf2

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
- obsolete py26-pypdf subport
- obsolete py-pydf, replaced by py-pypdf2 (since ~2010, according to upstream)
- py27-pypdf was a dependency of ```pdfposter```; this PR also updates that port to the most recent version, which depends on py-pypdf2

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.4 17E202
Xcode 9.3 9E145

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. I'd be interested in an opinion from @mojca.

**Comment by mojca** [comment]
Not sure why my opinion matters here :), but it mostly looks Ok (I did not test), except that py26-pypdf now probably redirects twice, first to py27-pypdf, then to py27-pypdf2. I would leave redirection of py26 subport in the same Portfile.

**Comment by pmetzger** [comment]
@reneeotten if you could fix @mojca's suggestion and squash the new commit, I'll merge this.

**Comment by mojca** [comment]
You should not use `replaced_by py${v}-pypdf2`, but `replaced_by py27-pypdf2`.

**Comment by reneeotten** [comment]
ah, sorry... probably haven't had enough coffee yet - will change it shortly. Thanks!

**Comment by pmetzger** [comment]
Merged. Thank you, @reneeotten!

Also, you might want to apply for commit privileges at some point, you certainly maintain enough things. See https://guide.macports.org/#project.membership

**Pull request merged**
