### PR TITLE
redeclipse: new port

### PR DESCRIPTION
**Pull request by jasonliu--**
#### Description

[Red Eclipse](https://www.redeclipse.net/) is a fun-filled new take on the first-person arena shooter, built on the Cube 2 game engine.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.11.6 15G22010 x86_64
Xcode 8.2.1 8C1002

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mascguy — APPROVED** [review]

**Comment by pmetzger** [comment]
What still needs to be done here?

**Comment by jasonliu--** [comment]
> What still needs to be done here?

Nothing, as far as I can tell.

**Comment by ryandesign** [comment]
Let's make sure to squash before or during merging next time.

Also the redeclipse-data port appears to just install data so it probably wants to have `supported_archs noarch`.

**Comment by jasonliu--** [comment]
Oops, not squashing was definitely an oversight. I must have gotten sloppy due to the holidays, lol.

**Comment by pmetzger** [comment]
It's on me for not double checking, not on you, @jasonliu-- . Sorry @ryandesign

**Pull request merged**
