### PR TITLE
dmux: new port

### PR DESCRIPTION
**Pull request by herbygillot**
#### Description

New port for **[dmux](https://github.com/zdcthomas/dmux)**, a `tmux` session manager.

###### Tested on

macOS 10.15.7 19H114
Xcode 12.3 12C33

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -d install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
Herby, you have (I think) a whole bunch of PRs going back for some time.

You're a committer, right? If so, can you just go ahead and commit all the ones that need committing?

**Comment by herbygillot** [comment]
> Herby, you have (I think) a whole bunch of PRs going back for some time.
> 
> You're a committer, right? If so, can you just go ahead and commit all the ones that need committing?

Hey Ken, yes, you're right, but for new ports, I usually aim to have them looked over and committed by other MacPorts vets and maintainers so that they are code reviewed before making it into the ports tree, as a matter of policy. Let me know if you think that that isn't necessary.

**Comment by kencu** [comment]
I know that's what you were doing -- always hurts to get punched out after you commit, I get it.

But there are 200+ PRs in the queue, and nobody is going to review these ones before 2030.

So -- you've been vetted. We need you. We need committers to commit. Take a punch if you get one, roll with it, shrug it off, and keep committing.

**Comment by herbygillot** [comment]
> I know that's what you were doing -- always hurts to get corrections after you commit, I get it.
> 
> But there are 200+ PRs in the queue, and realistically nobody is going to review these ones before 2030.
> 
> So -- you've been vetted. We need you. We need committers to commit. Take a correction if you get one, roll with it, shrug it off, and keep committing!

Appreciated, Ken - I think we should nominate you as MacPorts' official motivational speaker 😄 I will start to get these sorted soon then.  Thanks again.

**Comment by kencu** [comment]
Excellent. The honest truth is if we all just sit around waiting for one person to approve and commit every commit,  MacPorts is DEAD.

**Comment by herbygillot** [comment]
Very true, you're 100% right.

**Pull request merged**
