### PR TITLE
Update py-numba and py-llvmlite and add py310 variants

### PR DESCRIPTION
**Pull request by michaellass**
#### Description

Numba 0.55.0 was released, accompanied by llvmlite 0.38.0, which add support for Python 3.10. llvmlite 0.37.0 additionally added support for LLVM 11. This PR therefore:
* updates both ports to the newest available version,
* adds py310 variants,
* bumps the used LLVM version for py-llvmlite from 10 to 11.

Updating py-llvmlite required updating the `Makefile.osx` patch. However, we still need to keep the old version for pre-py36 setups which are stuck to llvmlite 0.31.0.

_**Current issues / why this should not be merged:**_
* numba 0.54.0 and newer require Python 3.7 (see: https://github.com/numba/numba/blob/0.55.0/CHANGE_LOG#L375). We would therefore need to drop older variants or add a version distinction in the Portfile.
* numba 0.55.0 on import fails with the message `ImportError: Numba needs NumPy 1.21 or less`. The check was introduced in https://github.com/numba/numba/commit/cbef091ec0bc6c68742fdfbc85f6eaf2bfbb26a6 but I don't think that means older numba versions play well with current numpy.

So, what to do at this point? Options I see:
* Downgrade numpy in macports
* Remove the check and hope for the best
* Keep the old version of numba because it does not include the check
* Drop numba from macports

References:
* https://github.com/numba/numba/releases/tag/0.55.0
* https://github.com/numba/llvmlite/blob/v0.38.0/CHANGE_LOG
* https://github.com/numba/numba/blob/0.55.0/CHANGE_LOG
* https://github.com/numba/numba/pull/7661

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.1 21C52 x86_64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?  _(there are none)_
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`? _(there are none)_
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
We're removing support for 3.6 and earlier anyway at the moment.

**Comment by michaellass** [comment]
Thanks for the comment. I added two commits that disable the numpy version check and remove the now broken support for python <3.7.

I tested basic functionality with Python 3.9 and 3.10. However, I'm not a heavy user of numba, so there might be hidden issues with numpy 1.22. We might want to ask upstream if there are any known issues.

CI currently fails due to seemingly broken `sysutils/packer/Portfile`.

**Comment by stromnov** [comment]
AFAIK, Numba 0.55 is still incompatible with Numpy 1.21+ (numba/numba#6864).

**Comment by michaellass** [comment]
1.21 is officially supported now although the referenced bug is not fixed yet: https://github.com/numba/numba/issues/7176#issuecomment-1006957658

However, having a fresh look at the issue tracker, it becomes clear that 1.22 is definitely not supported yet: https://github.com/numba/numba/issues/7754

So I guess this PR really should _not_ be merged. Shall I close it for now?

**Comment by pmetzger** [comment]
BTW, do remember you need to squash your commits before we merge.

**Comment by reneeotten** [comment]
> So I guess this PR really should _not_ be merged. Shall I close it for now?

I agree that this shouldn't be until numba is actually compatible with the current NumPy release. If the py-llmvite can be updated separately one could do that; if not, yes just close the PR.

**Comment by michaellass** [comment]
OK, let's close this for now. While updating numba would probably improve compatibility with newest numpy rather than worsen it, patching out the corresponding check feels bad and will probably cause a lot of confusion when people run into issues due to the known but then hidden incompatiblity.

Personally, I think providing a functioning version of numba via macports may become difficult in future due to the strict version requirements on numpy.

**Pull request closed without merging**
