### PR TITLE
py-qtpy: update to 1.5.1

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
- update to 1.5.1
- add py37 subport
- update post-destroot and description/long_description
- enable tests
- support all possible backends via variants: Qt5 is still the default, now also pyside and pyside2 are optional backends
- the pyside2 backend is only offered for python versions that are listed in the pyside2 port (i.e., py27/py36/py37).

The only current dependencies on py-qtpy use either the qt4 or qt5 variants; I think adding pyside and pyside2 could be useful though. Adding py34/py35 to pyside2 seems unnecessary, unless @pmetzger or @MarcusCalhoun-Lopez feel like this should be done.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65
Xcode 10.0 10A255
Python 2.7, 3.6, 3.7

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. @eborisch ?

**Comment by eborisch** [comment]
Is there a reason to complicate this port? The pyside options don't change anything in the installed files, and the only ports that require qtpy are the Spyder flavors, which both force qt5 anyway. (or qtawesome, which is only required again by the Spyder ports.)

If anything, I'd suggest removing the variants and having it only (and always) rely on Qt5. A user can always install pyside and use it if they would like to (and the software they are using lets you select upside) without complicating the port. Perhaps a note to that effect on install, but extra variants? Please no.

Was there something wrong with the permissions on the LICENSE.txt installation, or is this change in post-destroot to better match some boilerplate?

**Comment by reneeotten** [comment]
It's true that there are a few more variants, but the code in the Portfile is in my opinion clear now. In contrast to the current version, where depends_lib is first set to pyqt4, then a qt5 variant is defined where it pyqt4 is removed and pyqt5 added, and then qt5 is set as the default variant. The whole logic there is a bit counter-intuitive to me. 

Having said that, you're the maintainer so feel free to update in any way you see fit. You're certainly right that the backend can be changed at runtime so there is probably no real need to add variants; I just added the missing two options in a similar vein to what was done already in the Portfile. Adding a note on the different backends would anyway be a good idea. The changes to the post-destroot are to follow the recommendations [here](https://trac.macports.org/wiki/PortfileRecipes#doc). I can close this PR so that you can update the Portfile yourself, or you/me can just push changes to it - let me know what you prefer.

**Comment by eborisch** [comment]
Yes, but this version will install with no Qt if a user requests ‘pyNN-qtpy -qt5’, which seems less useful (for a user) than perhaps having counter-intuitive code in the Portfile. ;)

**Comment by reneeotten** [comment]
Aha, good point! I guess I was thinking in a wrong way about variants... my intention was "the user has to pick one of them", but didn't think about the possibility of not selecting any. So, I agree with you about leaving the variant-stuff as it was (possibly dropping the pyqt4 can be done at a later point), and instead added a note about the backends. My suggested changes are now in the one commit I just pushed - please have a look. Thanks for your explanations!

**Comment by eborisch** [comment]
LGTM. Thanks for adding the test bits.

**Pull request merged**
