### PR TITLE
py-openstackclient: update to 6.2.0; bump dependencies

### PR DESCRIPTION
**Pull request by alexj-wp**
#### Description
py-openstackclient was horribly out of date, and the `--tag` flag was bugged. Newer versions fix this issue, so I've updated the portfiles related.
*most* are nomaintainer, but a couple have maintainers, but I'm only enabling newer Python builds on those as far as I can tell.

OpenStack packages modified:
* py-cinderclient bumped to 9.3.0 and enable <=py3.11
* py-cliff bumped to 4.3.0 and enable <=py3.11
* py-debtcollector bumped to 2.5.0 and enable <=py3.11
* py-keystoneauth1 bumped to 5.2.1 and enable <=py3.11
* py-keystoneclient bumped to 5.1.0 and enable <=py3.11
* py-novaclient bumped to 18.3.0 and enable <=py3.11
* py-openstackclient bumped to 6.2.0 and enable <=py3.11
* py-openstacksdk bumped to 1.4.0 and enable <=py3.11
* py-os-service-types already at 1.7.0; enable <=py3.11
* py-osc-lib bumped to 2.8.0 and enable <=py3.11
* py-oslo-config bumped to 9.1.1 and enable <=py3.11
* py-oslo-i18n bumped to 6.0.0 and enable <=py3.11
* py-oslo-serialization bumped to 5.1.1 and enable <=py3.11
* py-oslo-utils bumped to 6.2.0 and enable <=py3.11

additionally, non-OpenStack packages modified
* py-cmd2 enable <=py3.11
* py-dogpile-cache enable <=py3.11
* py-netifaces enable <=py3.11

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 13.5 22G74 arm64
Xcode 14.3.1 14E300c

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by alexj-wp** [comment]
@reneeotten @pmetzger pinging due to interest on #19922

**Comment by pmetzger** [comment]
Howdy! I'd like to hear @reneeotten's opinion as this is his specialty but it looks perfectly good to me. My only question (for Renee, not for you) is whether py 3.7 should be removed from the portfiles.

**Comment by alexj-wp** [comment]
@pmetzger I know in the prior PR, there was mention of *not* removing the subports for older versions, but this was due to possibly breaking dependencies--then again, 3.7 is EoL as of June, so it is understandable to want to clean out cruft.

More on that, I'd love to set up automation to just pull updates when they're published to PyPi--and I feel like this would be broadly useful for MacPorts Python packages--but I see that some ports are explicitly pinned to certain versions for compatibility with their rdeps. I'll have to join IRC and search the mailing lists...

Not sure if either option would be feasible, but is it possible to set up a different version/checksum for a subport as a variant or something? Or would there need to be unique portfiles if I wanted to, say, pin py38-package to one version and update py311-package to a newer one?

And can one resolve a variant based on an rdep?--as in, not change the "upstream" rdep portfile and still select the correct variant based on the parent package being installed (e.g. if $rdep ~ py-ipython-sql install variant prettytable<1, else install newer version).

**Comment by pmetzger** [comment]
Absent any other comments I'm going to merge this. Thanks, @alexj-wp!

**Pull request merged**
