### PR TITLE
godot: new port

### PR DESCRIPTION
**Pull request by jasonliu--**
#### Description

[Godot](https://godotengine.org) is a cross-platform 2-D and 3-D game development environment.

###### Tested on

macOS 10.11.6 15G22010
Xcode 8.2.1 8C1002

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
Just curious, but what is the rationale for providing the clang variants ? Does the compiler used to build have an impact on the end user ?

**Comment by jasonliu--** [comment]
No, not really any particular reason, other than the fact that choosing to compile using MacPorts clang is actually a selectable option in Godot's SConstruct file.

I basically just copied the code for selecting various python versions from another package's portfile and change the variable names from "python_version" to "clang_version". In addition, the portfile for the root5 package does something very similar to what I'm doing, and allows the user to choose a gcc version.

I have another portfile that will check whether the user has any global variants set, and simply uses the newest installed version to build. Would that be preferable? I've tested building Godot with all of the clang versions in the list, and they all compile fine, so it seems like Godot doesn't really care what version of clang is being used.

**Comment by cjones051073** [comment]
> No, not really any particular reason, other than the fact that choosing to compile using MacPorts clang is actually a selectable option in Godot's SConstruct file.
> 
> I basically just copied the code for selecting various python versions from another package's portfile and change the variable names from "python_version" to "clang_version". In addition, the portfile for the root5 package does something very similar to what I'm doing, and allows the user to choose a gcc version.
> 
> I have another portfile that will check whether the user has any global variants set, and simply uses the newest installed version to build. Would that be preferable? I've tested building Godot with all of the clang versions in the list, and they all compile fine, so it seems like Godot doesn't really care what version of clang is being used.

No, that is in general not favoured. port installs should be entirely deterministic as to what they do, so ports that opportunistically do different things depending on what the user happens to have installed are disfavoured.

If there is not particular reason for the user to care which is used, just pick a version internally and use it. If you think it useful to allow the user a choice, provide variants, with one of them being enabled by default.

**Comment by cjones051073** [comment]
Just to add the root5 port provides compiler options, because the choice has a direct impact on the user. root5 provides an interactive c++ environment, and the compiler used to build is the one that environment is based on. Thats why for that port providing options was potentially of use to the user.

If the compiler is only used at the build phase (as is the norm) and has no impact such as that I describe above, the recommended approach is to pick which you need (using blacklisting). Giving users a choice via variants is of little to no use in this case.

**Comment by jasonliu--** [comment]
> root5 port provides compiler options, because the choice has a direct impact on the user. root5 provides an interactive c++ environment, and the compiler used to build is the one that environment is based on.

That may very well be the case here. Godot has it's own interactive scripting language, called [GDScript](https://docs.godotengine.org/en/stable/about/faq.html#what-were-the-motivations-behind-creating-gdscript), which as far as I can tell, is written in C++. And not only can users write their scripts using GDScript, but somehow Godot also exposes a C# API as well. Plus, there's apparently another API called [GDNative](https://godotengine.org/article/look-gdnative-architecture).

To be honest, even though I previously said there was "not any reason in particular", the truth is that I simply don't know. I'm not really much of a Godot user, other than putzing around with some of their open source [demos](https://github.com/godotengine/tps-demo), and importing some of my assets from Blender over to Godot. I certainly haven't ever written any GDScript or GDNative code. It may very well be possible that Godot's interactive scripting environment might be influenced by what version of clang is used to compile it, since it claims to [support GDScript, Visual Scripting, C#, and **C++**](https://docs.godotengine.org/en/stable/about/faq.html#which-programming-languages-are-supported-in-godot).

> port installs should be entirely deterministic as to what they do, so ports that opportunistically do different things depending on what the user happens to have installed are disfavored.

I'm not quite sure I understand why it wouldn't be deterministic if I simply used what the user already has installed. If I've already gone through and performed MacPorts builds using each and every version of clang that I've whitelisted, and all of them built successfully, then would that not be considered to be deterministic on another user's machine?

**Comment by cjones051073** [comment]
> > root5 port provides compiler options, because the choice has a direct impact on the user. root5 provides an interactive c++ environment, and the compiler used to build is the one that environment is based on.
> 
> That may very well be the case here. Godot has it's own interactive scripting language, called [GDScript](https://docs.godotengine.org/en/stable/about/faq.html#what-were-the-motivations-behind-creating-gdscript), which as far as I can tell, is written in C++. And not only can users write their scripts using GDScript, but somehow Godot also exposes a C# API as well. Plus, there's apparently another API called [GDNative](https://godotengine.org/article/look-gdnative-architecture).
> 
> To be honest, even though I previously said there was "not any reason in particular", the truth is that I simply don't know. I'm not really much of a Godot user, other than putzing around with some of their open source [demos](https://github.com/godotengine/tps-demo), and importing some of my assets from Blender over to Godot. I certainly haven't ever written any GDScript or GDNative code. It may very well be possible that Godot's interactive scripting environment might be influenced by what version of clang is used to compile it, since it claims to [support GDScript, Visual Scripting, C#, and **C++**](https://docs.godotengine.org/en/stable/about/faq.html#which-programming-languages-are-supported-in-godot).
> 
> > port installs should be entirely deterministic as to what they do, so ports that opportunistically do different things depending on what the user happens to have installed are disfavored.
> 
> I'm not quite sure I understand why it wouldn't be deterministic if I simply used what the user already has installed. If I've already gone through and performed MacPorts builds using each and every version of clang that I've whitelisted, and all of them built successfully, then would that not be considered to be deterministic on another user's machine?

If installing the same point, same variants, on two different users machines potentially ended up using different versions, just because of what the users in question happened to have installed, thats non-deterministic and what we want to avoid.

If based on what you say above you think there is merit to letting the user have a choice over the compiler used, then doing that via variants is fine. its just the choice has to be in the hands on the user, via the variant they pick.

**Comment by jasonliu--** [comment]
> If installing the same port, same variants, on two different users machines potentially ended up using different versions, just because of what the users in question happened to have installed, thats non-deterministic and what we want to avoid.

From that perspective, if by non-deterministic you mean that two different machines with different version of clang installed would result in two different compiles, then yes I see your point. I was defining non-deterministic in terms of not being able to know "compile succeeds" vs. "compile will fail". I guess going by your definition of non-deterministic, it would probably be better to just leave a list of clang variants and let the end user decide if they want to use a specific version of clang.

**Comment by cjones051073** [comment]
> > If installing the same port, same variants, on two different users machines potentially ended up using different versions, just because of what the users in question happened to have installed, thats non-deterministic and what we want to avoid.
> 
> From that perspective, if by non-deterministic you mean that two different machines with different version of clang installed would result in two different compiles, then yes I see your point. I was defining non-deterministic in terms of not being able to know "compile succeeds" vs. "compile will fail". I guess going by your definition of non-deterministic, it would probably be better to just leave a list of clang variants and let the end user decide if they want to use a specific version of clang.

Yes, thats what I am referring to by deterministic. If two different users can get different builds, from the exact same port+variants, then thats something we do not want. So please go with the variant approach.

**Comment by jasonliu--** [comment]
Okay, then let's go with what I currently have in the portfile as-is, since I'm not really sure yet how much of clang's features are passed through into the interactive programming interface of Godot.

**Pull request merged**
