### PR TITLE
Add GitHub handle cdeil to maintainers

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

Add GitHub handle @cdeil to maintainers

### CODE REVIEW

**Comment by cdeil** [comment]
@ryandesign - Unfortunately I'm no longer able to maintain the Astrometric ports.
Could you please `git cherry-pick`  7056bb982b058c8b16838222325f3bcc6790099f here?

(Usually I would make a PR against this PR. This doesn't seem to work, your fork doesn't appear in the "base fork" dropdown selection. I have reported this to Github just now.)

**Comment by ryandesign** [comment]
> Could you please `git cherry-pick` 7056bb982b058c8b16838222325f3bcc6790099f here?

I would be happy to, but I don't know how. I tried:

```
$ git cherry-pick 7056bb9
fatal: bad revision '7056bb9'
$ git cherry-pick 7056bb982b058c8b16838222325f3bcc6790099f
fatal: bad object 7056bb982b058c8b16838222325f3bcc6790099f
```

**Comment by cdeil** [comment]
You would have to fetch my branch first. This should work:
```
git remote add cdeil git@github.com:cdeil/macports-ports.git
git fetch cdeil
git cherry-pick 7056bb982b058c8b16838222325f3bcc6790099f
```

**Comment by pmetzger** [comment]
@cdeil, I think @ryandesign doesn't feel entirely comfortable with the git manipulations involved. I think the easier thing is for me to merge this (which I'll do right now), and for you to file a PR relinquishing your maintainership over those ports that I'll merge immediately. That will make things much easier.

**Comment by cdeil** [comment]
@pmetzger - See https://github.com/macports/macports-ports/pull/1648

**Comment by pmetzger** [comment]
Done! And thank you!

**Comment by ryandesign** [comment]
> I think @ryandesign doesn't feel entirely comfortable with the git manipulations involved.

Exactly. I'm trying to learn!

> You would have to fetch my branch first.

How could I have discovered the name of the fork and branch where the commit was located?

**Pull request merged**
