### PR TITLE
ola: build with protobuf-3

### PR DESCRIPTION
**Pull request by peternewman**
closes: closes https://trac.macports.org/ticket/56387

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.12.5 16F73
Xcode 8.2.1 8C1002 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by peternewman** [comment]
Replaces #2548

**Comment by kencu** [comment]
Oh-oh:
```
configure: error: OLA currently requires protobuf < 3.2, see issue 1192
```

**Comment by peternewman** [comment]
Yeah this will be related to https://github.com/macports/macports-ports/pull/2548#issuecomment-419739877 and my "fun" with git.

**Comment by peternewman** [comment]
The patch was missing from the Portfile after the merge, not sure where your comment went @kencu .

**Comment by pmetzger** [comment]
Merged. Thank you for fixing this!

I'm not sure why you're having so much trouble with git. I find that understanding what you're doing when you do git work helps, though, so  I strongly, strongly recommend reading chapter 10 of https://git-scm.com/book/en/v2 to get some knowledge of what is going on behind the scenes.

If you would like to file another PR re-assuming maintainership if you feel you can respond reasonably rapidly to tickets, it would be welcome.

**Comment by pmetzger** [comment]
Cool. You can submit a PR with both at once.

**Pull request merged**
