### PR TITLE
scrcpy: update to 1.23

### PR DESCRIPTION
**Pull request by MarcelBochtler**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.2.1 21D62 arm64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
this fails on the CI with (please check the complete logs): 
```
  Run-time dependency libusb-1.0 found: NO (tried pkgconfig and framework)
  
  app/meson.build:108:8: ERROR: Dependency "libusb-1.0" not found, tried pkgconfig and framework
```

did this build for you locally in trace-mode?

**Comment by MarcelBochtler** [comment]
> did this build for you locally in trace-mode?

Yes, I was able to build it using `sudo port -vst install`.

**Comment by reneeotten** [comment]
> > did this build for you locally in trace-mode?
> 
> Yes, I was able to build it using `sudo port -vst install`.

that's weird as for me (macOS 10.15.7 19H1715 x86_64 Xcode 12.4 12D4e) it fails with the same error as in the CI.... in any case that failure should probably be fixed before the PR can be merged.

**Comment by MarcelBochtler** [comment]
@reneeotten, I found the issue. `libusb` is now required as build dependency.
CI builds are successful now.

**Comment by reneeotten** [comment]
> @reneeotten, I found the issue. `libusb` is now required as build dependency.
> 
> CI builds are successful now.

thanks @MarcelBochtler for fixing this (it does tell us though you didn't build in trace-mode locally, otherwise you would have run into this issue).

**Comment by MarcelBochtler** [comment]
> it does tell us though you didn't build in trace-mode locally, otherwise you would have run into this issue

I actually did build it using the `-vst` flags.
I was able to reproduce this, and attached the logfile.
However, `libusb` was already installed on this arm64 machine. On another machine (x86-64) I was able to reproduce the CI build error.

[scrcpy.log.zip](https://github.com/macports/macports-ports/files/8148916/scrcpy.log.zip)

**Pull request merged**
