### PR TITLE
Update some lisp ports

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [x] enhancement

###### Tested on

macOS 12.7.1 21G920 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
@catap Just a general note: I completely ignore draft PRs. If you want me to look this over, let me know when it isn't a draft any more.

**Comment by catap** [comment]
@pmetzger this is draft because CI localized an issue with ABCL, ok, it was a triger to continue investigating of an issue which I’ve been hunting for couple of months.

https://github.com/macports/macports-ports/pull/21699 should fix it, and I’ve marked it as draft until it’s merged because it is an easy way to confirm the fix.

**Comment by pmetzger** [comment]
I've merged https://github.com/macports/macports-ports/pull/21699

**Comment by catap** [comment]
Thanks! I’ll be near laptop in couple of hours and rebase this

**Comment by pmetzger** [comment]
CI failed.

**Comment by pmetzger** [comment]
https://github.com/macports/macports-ports/pull/21715 is merged.

**Comment by catap** [comment]
Thanks, and now the fix for abcl which should unblock this one: https://github.com/macports/macports-ports/pull/21762

**Comment by catap** [comment]
Now it's blocked by ECL's bug: https://gitlab.com/embeddable-common-lisp/ecl/-/issues/705#note_1692453878

**Comment by catap** [comment]
Long story short: https://gitlab.com/embeddable-common-lisp/ecl/-/issues/718 wasn't enough to fix random failures on ECL, and it requires also https://github.com/ivmai/bdwgc/issues/103 which should be in next release of the GC.

Maybe it will be backported, who knows.

Anyway, until it's merged I've excluded ECL which should allows to pass CI.

**Comment by catap** [comment]
codeberg.org returned 502, rebased to restart CI

**Comment by pmetzger** [comment]
You will have to let me know when you want me to take some sort of action.

**Comment by catap** [comment]
@pmetzger I will. The root cause of CI failure is unstability of ECL which cause by `boehmgc`. The issue was fixed in master branch and was backported to stable branch.

Now, I'm waiting response from upstream to release a new stable version with increase stability for macOS. If it won't happened in week I'll backport nesessary patches to us, because right now `boehmgc` has random crashes on macOS.

**Pull request merged**
