### PR TITLE
py-docutils: add commit r8555 to address various usage issues

### PR DESCRIPTION
**Pull request by michaelld**
Closes: https://trac.macports.org/ticket/63765
Closes: https://trac.macports.org/ticket/63739
Closes: https://trac.macports.org/ticket/63727

#### Description

add commit [r8555](https://sourceforge.net/p/docutils/code/8885/) to address various usage issues

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.6.1 20G224
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mascguy — APPROVED** [review]

**Comment by catap** [comment]
@michaelld any chance that it is fixes https://trac.macports.org/ticket/63915 ?

**Comment by michaelld** [comment]
> @michaelld any chance that it is fixed https://trac.macports.org/ticket/63915 ?

Possibly. Would need to test to verify. The other issues I've already tested / verified / saw were fixed.

**Comment by mascguy** [comment]
Given the number of issues resolved by this fix, let's merge.

**Comment by jmroot** [comment]
@mascguy Please note https://guide.macports.org/#project.update-policies.nonmaintainer
> Pull requests for maintained ports should not be merged by anyone other than their creator or the port maintainer until the 72-hour timeout period has passed, even if the port is openmaintainer.

**Comment by mascguy** [comment]
> @mascguy Please note https://guide.macports.org/#project.update-policies.nonmaintainer
> > Pull requests for maintained ports should not be merged by anyone other than their creator or the port maintainer until the 72-hour timeout period has passed, even if the port is openmaintainer.

Yep, and promptly merging this one was a mistake... as we now have unexpected fallout.

If you could offer any guidance/suggestions on this issue, I'd appreciate it!

https://trac.macports.org/ticket/63915

**Pull request merged**
