### PR TITLE
opensmtpd: update to 7.5.0p0

### PR DESCRIPTION
**Pull request by artkiver**
closes: https://trac.macports.org/ticket/68573
closes: https://trac.macports.org/ticket/69456

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.4.1 23E224 arm64
Command Line Tools 15.3.0.0.1.1708646388

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryanakca** [comment]
I won't be able to test the proposed changes for a few days, but they look reasonable to me. Thanks @artkiver for handling this, and please feel free to add yourself to the maintainer field if you're interested.

**Comment by reneeotten** [comment]
@artkiver the Trac tickets should be added to the body of the commit message in order for them to be closed. Just adding them in the PR description won't do anything. Please amend that.

**Comment by artkiver** [comment]
> @artkiver the Trac tickets should be added to the body of the commit message in order for them to be closed. Just adding them in the PR description won't do anything. Please amend that.

Ah, whoops! Good catch! Thanks @reneeotten!

**Comment by artkiver** [comment]
I'm not sure if my git commit --amend functioned as intended? I can close this PR and open another with a cleaner single commit message from a new local branch though.

**Comment by reneeotten** [comment]
> I'm not sure if my git commit --amend functioned as intended? I can close this PR and open another with a cleaner single commit message from a new local branch though.

No, you didn't make the actual change and introduced a merge commit which we don't want. I'll do a "squash and merge" for now and include the Trac tickets myself.

**Comment by artkiver** [comment]
> > I'm not sure if my git commit --amend functioned as intended? I can close this PR and open another with a cleaner single commit message from a new local branch though.
> 
> No, you didn't make the actual change and introduced a merge commit which we don't want. I'll do a "squash and merge" for now and include the Trac tickets myself.

Thanks for the correction!

**Pull request merged**
