### PR TITLE
ffmpeg7: new port

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

New port.
Patches are copied from `ffmpeg6` port with no changes, but dropping unneeded ones.

@mascguy Christopher, I hope you do not mind being a primary maintainer? (If you would like not to, please let me know.)

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@mascguy I also suggest the following:

1. Update `ffmpeg-devel` to 7.x, switch conflict to ffmpeg7.
2. Change all ports with path-style dependency on ffmpeg to `port:ffmpeg` (= 4.x branch).
3. Use path-style for ports which will use `ffmpeg7`.

**Comment by barracuda156** [comment]
@pmetzger @ryandesign Anyone interested to be a co-maintainer, please. (TBH, I would rather handle powerpc support here, and let someone else manage the port overall.)

**Comment by barracuda156** [comment]
@ryandesign Ryan, would you like to be added?

**Comment by barracuda156** [comment]
@pmetzger @reneeotten Could we get this merged? I wanna use it with my port.
I am open to adding anyone interested to be a co-maintainer.

**Comment by pmetzger** [comment]
So the port is a good idea; my problem is I don't feel comfortable committing things I don't think I can review properly, and this is large and outside of my wheelhouse. I'd like someone who understands ffmpeg to read through the thing. @ryandesign do you think you can look at this?

**Comment by barracuda156** [comment]
@pmetzger It is almost a copy-paste from `ffmpeg6`, which can be seen from diff-ing the two ports, but I tagged you only because you often help with committing things. Of course, there is no obligation here, and I understand that the thing is huge.

@ryandesign Whenever you get time, please take a look, and let me know if you’d like to be added as a maintainer.

**Comment by barracuda156** [comment]
> If all else fails I can look but it's real work in this case and I might not get to it quickly.

Sure, and I think someone will attend this sooner or later, after all `ffmpeg` is a thing which many people use.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
