### PR TITLE
qwt-qt5: update to 6.1.5

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Disable silent rules

#### Description
https://sourceforge.net/p/qwt/code/HEAD/tree/tags/qwt-6.1.5/CHANGES-6.1

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.6
Xcode 12 command line tools

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
Why has parallel building always been disabled for this port? The [upstream installation instructions](https://qwt.sourceforge.io/qwtinstall.html#qwtinstall-unix) suggest using parallel building, and I did not observe any issue with `use_parallel_build yes`.

**Comment by michaelld** [comment]
> Why has parallel building always been disabled for this port? The [upstream installation instructions](https://qwt.sourceforge.io/qwtinstall.html#qwtinstall-unix) suggest using parallel building, and I did not observe any issue with `use_parallel_build yes`.

The port had issues in the past. maybe it no longer does? It's worth pushing a commit to remove that instruction IMHO.

**Review by michaelld — APPROVED** [review]
Works for me on 10.12

**Comment by michaelld** [comment]
I did test earlier both with and without parallel build. Both worked for me on 10.12. So :+1: from me on these changes still.

**Comment by michaelld** [comment]
All looks good with both of the commits on the CI. I'll merge this Monday if it's not done before, per MP maintainer timeout policy.

**Pull request merged**
