### PR TITLE
hackrf: update to 2017.02.1

### PR DESCRIPTION
**Pull request by Fanfwe**
Upstream released a new stable version 2017.02.1
The current hash used in the port is not compatible with the latest firmware for HackRF, which is why I suggest to update this again.

### CODE REVIEW

**Comment by l2dy** [comment]
Please use tag name in github.setup.

Please follow our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages).

You need to list any modified ports first, followed by a colon. See recent commits for examples.

**Comment by ryandesign** [comment]
Looks like @michaelld has updated hackrf to newer development versions since this PR was started. Should we instead switch hackrf to use the latest stable version, as suggested in this PR?

**Comment by michaelld** [comment]
If we want a stable release port, then I'll move the current hackrf to hackrf-devel & set hackrf to be the latest release. Given how often releases are for this port, and the critical fixes that come between them, and how often commits are made (in general), I'm inclined to leave things as they are & just keep hackrf at the latest GIT master commit. That said, "majority rules" of some sort, so please voice your opinion.

**Comment by michaelld** [comment]
Meh. Whatever. I'm going to just move to release and devel subports; it's a very simple change. Folks can choose and/or complain if they want to about updates to the former, and we can tell them to try the latter. Unfortunately, upstream bundles extra files with the release that are useful -- for example, hackrf firmware & the tool to write it to hardware. Not a great solution without some serious hackery that I don't see the immediate benefit in.

**Comment by michaelld** [comment]
I'm going to close this PR since it has been implemented & is no longer needed.

**Pull request closed without merging**
