### PR TITLE
ghostscript: update to 9.24

### PR DESCRIPTION
**Pull request by l2dy**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65
Xcode 9.4.1 9F2000

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files? (only tested `ps2pdf`)

### CODE REVIEW

**Comment by pmetzger** [comment]
There will be another security release in a few days, so watch out for it.

**Comment by l2dy** [comment]
@pmetzger I'm aware that 9.25 will ship more security fixes, but how do you know it would come out in a few days?

**Comment by pmetzger** [comment]
I don't as such, but the open source security mailing list has been discussing new bugs that were not fixed in 9.24 and I presume they will not want to leave them unpatched indefinitely.

**Comment by pmetzger** [comment]
FYI: 9.25rc1 was tagged 12 hours ago.

**Comment by l2dy** [comment]
@pmetzger See https://github.com/macports/macports-ports/pull/2573.

**Pull request merged**
