### PR TITLE
py-plotly:  fix jupyterlab version

### PR DESCRIPTION
**Pull request by jjstickel**
* allow jupyterlab version >3

Closes: https://trac.macports.org/ticket/69416

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.3.1 23D60 arm64
Xcode 15.2 15C500b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ x squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by i0ntempest** [comment]
Still has missing dependencies:
```
  ERROR Missing dependencies:
  	jupyterlab>=3.0; python_version >= "3.6"
  	notebook-shim>=0.2 -> jupyter-server<3,>=1.8 -> nbconvert>=6.4.4 -> jupyterlab-pygments
  	jupyterlab>=3.0; python_version >= "3.6"
  	jupyterlab-server<3,>=2.19.0 -> jupyter-server<3,>=1.21 -> nbconvert>=6.4.4 -> jupyterlab-pygments
  	jupyterlab>=3.0; python_version >= "3.6"
  	jupyter-lsp>=2.0.0 -> jupyter-server>=1.1.2 -> nbconvert>=6.4.4 -> jupyterlab-pygments
  	jupyterlab>=3.0; python_version >= "3.6"
  	jupyter-server<3,>=2.4.0 -> nbconvert>=6.4.4 -> jupyterlab-pygments
```
Looks like a version requirement conflict.

**Comment by jonCAstickel** [comment]
What I know is that it worked for me for py311-plotly. It seems better to me to deploy something that might work for some people than leave things completely broken.

**Comment by jjstickel** [comment]
What I know is that it worked for me for py311-plotly. It seems better to me to deploy something that might work for some people than leave things completely broken.

**Comment by pmetzger** [comment]
Regardless, the CI should be made to pass before we commit.

**Comment by jjstickel** [comment]
> Regardless, the CI should be made to pass before we commit.

Ok. The checks failed for `py311-plotly`, but that failure is not reproducing on my system. Can someone trigger to run the checks again? Some jupyter-ecosystem packages have been updated since they were run.

**Comment by i0ntempest** [comment]
Already did 2 days ago, but did it again just now anyways.

**Comment by jjstickel** [comment]
> Still has missing dependencies:
> 
> Looks like a version requirement conflict. If you're absolutely sure mismatching version won't be a problem, you can put in `build.args-append --skip-dependency-check` temporarily.

I cannot reproduce this error at all. Something seems off with the internal version check with upstream plotly source. So I added the skip-dependency check line as suggested.

**Comment by i0ntempest** [comment]
You may remove the reinplace statement now since dependency check is skipped altogether. Once you do that I’ll merge.

**Comment by jjstickel** [comment]
> You may remove the reinplace statement now since dependency check is skipped altogether. Once you do that I’ll merge.

Done, and checks now pass.

**Pull request merged**
