### PR TITLE
py-toml, py-tomli: add Python 3.12 support

### PR DESCRIPTION
**Pull request by nilason**
#### Description

Add Python 3.12 support to `py-toml` and `py-tomli`.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.6.1 22G313 arm64
Xcode 15.0.1 15A507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by jmroot** [comment]
Out of curiosity, what needs this? Since Python 3.11, `tomli` has been available in the stdlib under the name `tomllib`.

**Comment by tobypeterson** [comment]
I’m sure there are some ports that haven’t adopted tomllib yet. Not sure if we want to take on the task of patching them…

**Comment by nilason** [comment]
My immediate aim for this was to add `py312-sip`. It turned out that SIP indeed does not need neither toml nor tomli for Python >=3.11. Addressed by #21361.

**Comment by tobypeterson** [comment]
Thanks for checking! Maybe we'll get lucky and won't ever need to add python 3.12+ support for these.

**Pull request merged**
