### PR TITLE
varnish: update to 7.0.0

### PR DESCRIPTION
**Pull request by catap**
#### Description

Thus, it also contains fix for varnish7 on macOS: https://github.com/varnishcache/varnish-cache/pull/3700

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.6 20G165 x86_64
Xcode 12.5.1 12E507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by Gminfly** [comment]
Seems like everything is fine just some other ports still depend on 6.4 I'll ask what the procedure is here. Can't merge myself anyways as I do not have write access.

**Comment by catap** [comment]
@Gminfly the only port which is depended is collectd. I’ll check in hour or so is it vmod or not. Because vmod might be broken because API was changed a bit (I know, I’m supporting one very complicated vmod which is working with varnish 3+; it is nightmare)

**Comment by Gminfly** [comment]
@catap hey no Stress, it is great you are doing this work to begin with :)

**Comment by catap** [comment]
@Gminfly thanks for a good point about collectd :) It is included.

**Comment by catap** [comment]
@reneeotten can I ask you also to merge it because I haven't got any rights to do it?

**Pull request merged**
