### PR TITLE
gcr: update to 3.41.2

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
To avoid rebuilding dependents, we need a fix for dylib versions, upstream has broken it:
```
Incompatible library version: /opt/local/bin/pan requires version 1.0.0 or later, but /opt/local/lib/libgck-1.0.dylib provides version 0.0.0
Incompatible library version: /opt/local/bin/pan requires version 2.0.0 or later, but /opt/local/lib/libgcr-base-3.1.dylib provides version 1.0.0
Incompatible library version: /opt/local/bin/pan requires version 2.0.0 or later, but /opt/local/lib/libgcr-ui-3.1.dylib provides version 1.0.0
```

**Comment by reneeotten** [comment]
@barracuda156 please fix or close

**Comment by barracuda156** [comment]
@reneeotten I will try today, we want this updated.

**Comment by barracuda156** [comment]
@reneeotten Sorry for a delay. Looks like it actually installs correct versions. Compare existing 3.38.1:
```
/opt/local/lib/libgck-1.0.dylib
/opt/local/lib/libgck-1.dylib
/opt/local/lib/libgcr-base-3.1.dylib
/opt/local/lib/libgcr-base-3.dylib
/opt/local/lib/libgcr-ui-3.1.dylib
/opt/local/lib/libgcr-ui-3.dylib
```
vs what I get locally from 3.41.2 (tested on Sonoma):
```
x ./opt/local/lib/libgcr-base-3.1.dylib
x ./opt/local/lib/libgcr-ui-3.1.dylib
x ./opt/local/lib/libgck-1.dylib
x ./opt/local/lib/libgcr-ui-3.dylib
x ./opt/local/lib/libgcr-base-3.dylib
x ./opt/local/lib/libgck-1.0.dylib
```
Should be good to go.

**Comment by ryandesign** [comment]
> Sorry for a delay. Looks like it actually installs correct versions. Compare existing [3.38.1](https://ports.macports.org/port/gcr/details):
> 
> ```
> /opt/local/lib/libgck-1.0.dylib
> /opt/local/lib/libgck-1.dylib
> /opt/local/lib/libgcr-base-3.1.dylib
> /opt/local/lib/libgcr-base-3.dylib
> /opt/local/lib/libgcr-ui-3.1.dylib
> /opt/local/lib/libgcr-ui-3.dylib
> ```
> 
> vs what I get locally from 3.41.2 (tested on Sonoma):
> 
> ```
> x ./opt/local/lib/libgcr-base-3.1.dylib
> x ./opt/local/lib/libgcr-ui-3.1.dylib
> x ./opt/local/lib/libgck-1.dylib
> x ./opt/local/lib/libgcr-ui-3.dylib
> x ./opt/local/lib/libgcr-base-3.dylib
> x ./opt/local/lib/libgck-1.0.dylib
> ```

These are library major versions. They haven't changed. That's fine.

> ```
> Incompatible library version: /opt/local/bin/pan requires version 1.0.0 or later, but /opt/local/lib/libgck-1.0.dylib provides version 0.0.0
> Incompatible library version: /opt/local/bin/pan requires version 2.0.0 or later, but /opt/local/lib/libgcr-base-3.1.dylib provides version 1.0.0
> Incompatible library version: /opt/local/bin/pan requires version 2.0.0 or later, but /opt/local/lib/libgcr-ui-3.1.dylib provides version 1.0.0
> ```

These are library minor versions. They have regressed, which is not allowed.

https://trac.macports.org/ticket/70150

**Pull request merged**
