### PR TITLE
cmake-devel: fix a build error on 10.6: undefined _posix_spawn_file_actions_addinherit_np

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Failure on 10.6.8:
```
Undefined symbols:
  "_posix_spawn_file_actions_addinherit_np", referenced from:
      _uv_spawn in uv-src-unix-process.c.o
ld: symbol(s) not found
collect2: error: ld returned 1 exit status
gmake: *** [Makefile:2: cmake] Error 1
```

Fix is borrowed from `libuv` port’s patch.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

macOS 10A190
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Review by michaelld — APPROVED** [review]
LGTM ... let's see how the CI / QA testing does

**Comment by barracuda156** [comment]
@michaelld Checks are good!

**Comment by michaelld** [comment]
Awesome. Thanks for your continued contributions to keep older OSX working!

**Comment by michaelld** [comment]
@barracuda156 have you done a PR upstream for these? I think they would be well received.

**Comment by barracuda156** [comment]
> @barracuda156 have you done a PR upstream for these? I think they would be well received.

@michaelld I think they don’t accept PRs on GitHub. Need to see how Gitlab works, never used it.

**Comment by barracuda156** [comment]
@michaelld By the way, is this fixable or should we blacklist `{clang < 600}`?

https://trac.macports.org/attachment/ticket/66040/

**Pull request merged**
