### PR TITLE
ansible: update to 2.17.2

### PR DESCRIPTION
**Pull request by esafak**
#### Description

Update **py-ansible** _and_ **py-ansible-core** to latest version.

###### Tested on
macOS 14.5 23F79 arm64
Xcode 15.4 15F31d

###### Verification 

```
>ansible

ansible [core 2.17.2]
  config file = None
  configured module search path = ['/Users/emre/.ansible/plugins/modules', '/opt/local/share/ansible/plugins/modules']
  ansible python module location = /opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/emre/.ansible/collections:/opt/local/share/ansible/collections
  executable location = /opt/local/bin/ansible
  python version = 3.12.4 (main, Jun  8 2024, 04:51:36) [Clang 15.0.0 (clang-1500.1.0.2.5)] (/opt/local/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12)
  jinja version = 3.1.4
  libyaml = True
```

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
@esafak CI fails.

**Comment by esafak** [comment]
As mentioned in the description. I'm requesting feedback to resolve it.

**Comment by pmetzger** [comment]
Switch to the github portgroup perhaps? I would make sure that it works locally on your machine of course.

**Comment by pmetzger** [comment]
Didn't notice that these were python ports. @reneeotten generally tells people to set things up to do the fetch from PyPI I believe but I might have that wrong.

**Comment by ryandesign** [comment]
> fetch from PyPI

Right. Use pypi for python modules. The python and github portgroups don't get along well.

The py-ansible-core port is trying to download the file ansible-core-2.17.2.tar.gz. At https://pypi.org/project/ansible-core/#files I see that the file is actually called ansible_core-2.17.2.tar.gz. Looks like it changed from `ansible-core` to `ansible_core` at version 2.16.6. Adding `distname ansible_core-${version}` to the port should fix that.

The PR updates py-ansible-core to 2.17.2 and py-ansible to 10.2.0 but the commit message currently reads "ansible: update to 2.17.2". The two updates in this PR should be separated into two commits with correct commit messages.

The line `conflicts ansible` should be removed from both ports. The ansible port is marked `replaced_by py-ansible`; a port that replaces another should not conflict with it.

ansible has been replaced by py-ansible since 2017—well over a year ago. The ansible port could be deleted.

**Comment by ryandesign** [comment]
> Looks like it changed from `ansible-core` to `ansible_core` at version 2.16.6.

At https://github.com/ansible-community/antsibull-core/blob/main/CHANGELOG.rst#bugfixes it says this is due to https://peps.python.org/pep-0625/#specification specifically the normalization described at https://packaging.python.org/en/latest/specifications/binary-distribution-format/#escaping-and-unicode: "In distribution names, any run of `-_.` characters (HYPHEN-MINUS, LOW LINE and FULL STOP) should be replaced with `_` (LOW LINE)".

**Comment by esafak** [comment]
Thank you, @ryandesign I hope I addressed your concerns.

I suppose we should handle the deletion in another PR.

**Comment by pmetzger** [comment]
Assuming @ryandesign is happy (or that a bit of time passes) I suppose we should merge this.

**Pull request merged**
