### PR TITLE
libuv: update to 1.44.1

### PR DESCRIPTION
**Pull request by michaelld**
#### Description

libuv: update to 1.44.1
+ Move away from GitHub as master_site to the libuv distribution website
+ [but still use the GitHub PG for other things (very convenient)]
+ Removes the ability (and hopefully need) to use_autoconf
+ update all patches to hopefully work without use_autoconf
+ Add Evan's patch to fix the Tiger build

Closes: https://trac.macports.org/ticket/64789

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.6.5 20G517
Xcode 12.3 12C33

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by michaelld** [comment]
There are enough changes to the Portfile that I feel it appropriate to make a PR to see how CI/QA goes, and also give others a chance to try this out for themselves

**Comment by evanmiller** [comment]
On Tiger:

```
:info:build libtool: compile:  /opt/local/bin/gcc-apple-4.2 -std=gnu99 -DPACKAGE_NAME=\"libuv\" -DPACKAGE_TARNAME=\"libuv\" -DPACKAGE_VERSION=\"1.44.0\" "-DPACKAGE_STRING=\"libuv 1.44.0\"" -DPACKAGE_BUGREPORT=\"https://github.com/libuv/libuv/issues\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libuv\" -DVERSION=\"1.44.0\" -DSUPPORT_ATTRIBUTE_VISIBILITY_DEFAULT=1 -DSUPPORT_FLAG_VISIBILITY=1 -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PTHREAD_PRIO_INHERIT=1 -I. -I./include -I./src -I./src/unix -isystem/opt/local/include/LegacySupport -I/opt/local/include -D__DARWIN_UNIX03 -D__OPENTRANSPORTPROVIDERS__ -D_DARWIN_USE_64_BIT_INODE=1 -D_DARWIN_UNLIMITED_SELECT=1 -pipe -Os -arch ppc -fvisibility=hidden -pthread -MT src/unix/libuv_la-process.lo -MD -MP -MF src/unix/.deps/libuv_la-process.Tpo -c src/unix/process.c  -fno-common -DPIC -o src/unix/.libs/libuv_la-process.o
:info:build src/unix/process.c:39:20: error: spawn.h: No such file or directory
:info:build src/unix/process.c:379: warning: type defaults to 'int' in declaration of 'posix_spawn_file_actions_t'
:info:build src/unix/process.c:379: error: expected ';', ',' or ')' before '*' token
:info:build src/unix/process.c:380: warning: no semicolon at end of struct or union
:info:build src/unix/process.c: In function 'uv__spawn_init_posix_spawn_fncs':
:info:build src/unix/process.c:391: error: 'struct <anonymous>' has no member named 'addchdir_np'
:info:build src/unix/process.c: At top level:
:info:build src/unix/process.c:434: error: expected ')' before '*' token
:info:build src/unix/process.c:506: error: expected ')' before '*' token
:info:build src/unix/process.c:643: error: expected declaration specifiers or '...' before 'posix_spawnattr_t'
:info:build src/unix/process.c:644: error: expected declaration specifiers or '...' before 'posix_spawn_file_actions_t'
:info:build src/unix/process.c: In function 'uv__spawn_resolve_and_spawn':
:info:build src/unix/process.c:676: warning: implicit declaration of function 'posix_spawnp'
:info:build src/unix/process.c:676: error: 'actions' undeclared (first use in this function)
:info:build src/unix/process.c:676: error: (Each undeclared identifier is reported only once
:info:build src/unix/process.c:676: error: for each function it appears in.)
:info:build src/unix/process.c:676: error: 'attrs' undeclared (first use in this function)
:info:build src/unix/process.c:720: warning: implicit declaration of function 'posix_spawn'
:info:build src/unix/process.c: In function 'uv__spawn_and_init_child_posix_spawn':
:info:build src/unix/process.c:751: error: 'posix_spawnattr_t' undeclared (first use in this function)
:info:build src/unix/process.c:751: error: expected ';' before 'attrs'
:info:build src/unix/process.c:752: error: 'posix_spawn_file_actions_t' undeclared (first use in this function)
:info:build src/unix/process.c:752: error: expected ';' before 'actions'
:info:build src/unix/process.c:754: warning: implicit declaration of function 'uv__spawn_set_posix_spawn_attrs'
:info:build src/unix/process.c:754: error: 'attrs' undeclared (first use in this function)
:info:build src/unix/process.c:759: warning: implicit declaration of function 'uv__spawn_set_posix_spawn_file_actions'
:info:build src/unix/process.c:759: error: 'actions' undeclared (first use in this function)
:info:build src/unix/process.c:765: warning: implicit declaration of function 'posix_spawnattr_destroy'
:info:build src/unix/process.c:771: error: too many arguments to function 'uv__spawn_resolve_and_spawn'
:info:build src/unix/process.c:775: warning: implicit declaration of function 'posix_spawn_file_actions_destroy'
:info:build make: *** [src/unix/libuv_la-process.lo] Error 1
```

Might be a way to work around this (some projects use `HAVE_SPAWN_H`) but I will have to investigate later.

**Comment by kencu** [comment]
you could bring back the previous libuv peg for older systems if you don't want to hold this up too long.

Updating libuv on < 10.7 is always something of a project, with variable amounts of heartburn.

**Comment by michaelld** [comment]
> you could bring back the previous libuv peg for older systems if you don't want to hold this up too long.
> 
> Updating libuv on < 10.7 is always something of a project, with variable amounts of heartburn.

hmmm ... yeah that's probably the right thing to do, given the regularity of libuv releases & the chances of them not building on older OSX

**Comment by michaelld** [comment]
`:info:build src/unix/process.c:39:20: error: spawn.h: No such file or directory`

whatever who needs that anyway ;)

**Comment by ryandesign** [comment]
I would keep the `PortGroup github` and `github.setup` lines since this project is still hosted at GitHub and since that will prevent the livecheck from breaking.

1.44.1 is out.

**Comment by evanmiller** [comment]
Appending this patch to `patch-libuv-legacy.diff` will fix the Tiger build

```patch
--- src/unix/process.c.orig
+++ src/unix/process.c
@@ -36,7 +36,9 @@
 #include <poll.h>

 #if defined(__APPLE__) && !TARGET_OS_IPHONE
+#if MAC_OS_X_VERSION_MAX_ALLOWED >= 1050
 # include <spawn.h>
+#endif
 # include <paths.h>
 # include <sys/kauth.h>
 # include <sys/types.h>
@@ -373,7 +375,7 @@
 #endif


-#if defined(__APPLE__)
+#if defined(__APPLE__) && MAC_OS_X_VERSION_MIN_REQUIRED >= 1050
 typedef struct uv__posix_spawn_fncs_tag {
   struct {
     int (*addchdir_np)(const posix_spawn_file_actions_t *, const char *);
@@ -836,7 +838,7 @@
   int exec_errorno;
   ssize_t r;

-#if defined(__APPLE__)
+#if defined(__APPLE__) && MAC_OS_X_VERSION_MIN_REQUIRED >= 1050
   uv_once(&posix_spawn_init_once, uv__spawn_init_posix_spawn);

   /* Special child process spawn case for macOS Big Sur (11.0) onwards
```

**Review by kencu — COMMENTED** [review]
Looks like Evan has come up with a Tiger patch, so no need to hold back Tiger this time! The other github vs no github changes I will leave to you and Ryan.

Thanks for asking!

**Comment by michaelld** [comment]
Updated per all of the comments herein thus far

**Review by ryandesign — APPROVED** [review]

**Comment by michaelld** [comment]
@evanmiller can you test / verify on your older OSX system(s)?

**Comment by evanmiller** [comment]
> @evanmiller can you test / verify on your older OSX system(s)?

Builds OK – there are a few test failures but I think this was the case previously.

**Comment by michaelld** [comment]
Wonderful. Thanks for the quick work all around. Merging

**Comment by barracuda156** [comment]
@evanmiller Does it build for you on Leopard? For me it is broken now: https://trac.macports.org/ticket/64828

```
libtool: link: /usr/bin/gcc-4.2 -std=gnu99 -dynamiclib  -o .libs/libuv.1.dylib  src/.libs/libuv_la-fs-poll.o src/.libs/libuv_la-idna.o src/.libs/libuv_la-inet.o src/.libs/libuv_la-random.o src/.libs/libuv_la-strscpy.o src/.libs/libuv_la-threadpool.o src/.libs/libuv_la-timer.o src/.libs/libuv_la-uv-data-getter-setters.o src/.libs/libuv_la-uv-common.o src/.libs/libuv_la-version.o src/unix/.libs/libuv_la-async.o src/unix/.libs/libuv_la-core.o src/unix/.libs/libuv_la-dl.o src/unix/.libs/libuv_la-fs.o src/unix/.libs/libuv_la-getaddrinfo.o src/unix/.libs/libuv_la-getnameinfo.o src/unix/.libs/libuv_la-loop-watcher.o src/unix/.libs/libuv_la-loop.o src/unix/.libs/libuv_la-pipe.o src/unix/.libs/libuv_la-poll.o src/unix/.libs/libuv_la-process.o src/unix/.libs/libuv_la-random-devurandom.o src/unix/.libs/libuv_la-signal.o src/unix/.libs/libuv_la-stream.o src/unix/.libs/libuv_la-tcp.o src/unix/.libs/libuv_la-thread.o src/unix/.libs/libuv_la-tty.o src/unix/.libs/libuv_la-udp.o src/unix/.libs/libuv_la-bsd-ifaddrs.o src/unix/.libs/libuv_la-darwin-proctitle.o src/unix/.libs/libuv_la-darwin.o src/unix/.libs/libuv_la-fsevents.o src/unix/.libs/libuv_la-kqueue.o src/unix/.libs/libuv_la-proctitle.o src/unix/.libs/libuv_la-random-getentropy.o   -L/opt/local/lib -lMacportsLegacySupport  -Os -arch ppc -pthread -Wl,-headerpad_max_install_names -arch ppc   -pthread -install_name  /opt/local/lib/libuv.1.dylib -compatibility_version 2 -current_version 2.0 -Wl,-single_module
Undefined symbols:
  "_posix_spawn_file_actions_addinherit_np", referenced from:
      _uv_spawn in libuv_la-process.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
make: *** [libuv.la] Error 1
```

**Comment by evanmiller** [comment]
@barracuda156 It looks like `posix_spawn_file_actions_addinherit_np` was added in Lion, so the Snow Leopard build is failing as well:

https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/96015

**Comment by barracuda156** [comment]
@evanmiller Yeah, and upstream just closed my ticket: https://github.com/libuv/libuv/issues/3552 (there I used 10.6 PPC, but failure is identical).
Should we just stay on 1.43.0 or try to edit away failing function?

And how did you build it on Tiger though?

**Comment by barracuda156** [comment]
@evanmiller Awesome, thanks!
```
36-120:~ svacchanda$ port -v installed libuv
The following ports are currently installed:
  libuv @1.30.0_0 requested_variants='' platform='darwin 10' archs='ppc' date='2021-10-05T03:44:15+0800'
  libuv @1.42.0_1 requested_variants='' platform='darwin 10' archs='ppc' date='2021-11-12T16:21:25+0800'
  libuv @1.43.0_0 requested_variants='' platform='darwin 10' archs='ppc' date='2022-01-09T01:22:51+0800'
  libuv @1.44.1_0 (active) requested_variants='' platform='darwin 10' archs='ppc' date='2022-03-15T20:49:24+0800'
```

**Comment by barracuda156** [comment]
@michaelld On 10.5.8 `libuv` still fails for ppc64:

```
mv -f src/.deps/libuv_la-version.Tpo src/.deps/libuv_la-version.Plo
/bin/sh ./libtool  --tag=CC   --mode=compile /usr/bin/gcc-4.2 -std=gnu99 -DPACKAGE_NAME=\"libuv\" -DPACKAGE_TARNAME=\"libuv\" -DPACKAGE_VERSION=\"1.44.1\" -DPACKAGE_STRING=\"libuv\ 1.44.1\" -DPACKAGE_BUGREPORT=\"https://github.com/libuv/libuv/issues\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libuv\" -DVERSION=\"1.44.1\" -DSUPPORT_ATTRIBUTE_VISIBILITY_DEFAULT=1 -DSUPPORT_FLAG_VISIBILITY=1 -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PTHREAD_PRIO_INHERIT=1 -I.  -I./include -I./src  -I./src/unix -isystem/opt/local/include/LegacySupport -I/opt/local/include -D__DARWIN_64_BIT_INO_T       -D_DARWIN_USE_64_BIT_INODE=1 -D_DARWIN_UNLIMITED_SELECT=1      -pipe -Os -arch ppc64 -fvisibility=hidden -pthread -MT src/unix/libuv_la-dl.lo -MD -MP -MF src/unix/.deps/libuv_la-dl.Tpo -c -o src/unix/libuv_la-dl.lo `test -f 'src/unix/dl.c' || echo './'`src/unix/dl.c
{standard input}:198:Parameter syntax error (parameter 1)
make: *** [src/unix/libuv_la-async.lo] Error 1
make: *** Waiting for unfinished jobs....
```
https://trac.macports.org/ticket/64262

**Comment by barracuda156** [comment]
@michaelld @evanmiller Here is the specific place where ppc64 build fails:
```
static void uv__async_send(uv_loop_t* loop) {
  const void* buf;
  ssize_t len;
  int fd;
  int r;

  buf = "";
  len = 1;
  fd = loop->async_wfd;

#if defined(__linux__)
  if (fd == -1) {
    static const uint64_t val = 1;
    buf = &val;
    len = sizeof(val);
    fd = loop->async_io_watcher.fd;  /* eventfd */
  }
#endif

  do
    r = write(fd, buf, len);
  while (r == -1 && errno == EINTR);

  if (r == len)
    return;

  if (r == -1)
    if (errno == EAGAIN || errno == EWOULDBLOCK)
      return;

  abort();
}
```

**Pull request merged**
