### PR TITLE
remove opencore-amr

### PR DESCRIPTION
**Pull request by janstary**
This removes the audio/opencore-amr port. If this goes in, https://github.com/macports/macports-ports/pull/1182 can also be closed.

Tested on 10.13.2 with XCode 9.2

### CODE REVIEW

**Comment by janstary** [comment]
The failed check is Travis timing out after 48 minutes.
Does anybody know what this is?

**Comment by janstary** [comment]
Squashed

**Comment by janstary** [comment]
Can we merge this please?

**Comment by pmetzger** [comment]
How long are we expected to wait for a maintainer timeout?

**Comment by pmetzger** [comment]
Also, currently Travis is saying the checks fail.

**Comment by janstary** [comment]
That's Travis timing out after 48 minutes, giving false positves all over the place, yay!

**Comment by pmetzger** [comment]
I take it you've hand checked that all the ports you updated build?

**Pull request merged**
