### PR TITLE
py-robotframework-ride: update to 1.7.3.1

### PR DESCRIPTION
**Pull request by mojca**
I have absolutely no clue how to test this and hope that @jyrkiwahlstedt can provide some insight and testing (and hopefully take the port over?). I just wanted to get rid of dependency on wxWidgets 2.8. Unit tests require some module that was only introduced in Python 3.4. I tried testing with 3.7, but then we miss a bunch of python packages that would need to be ported first before we can run the tests.

They say that this is the last or pre-last version with support for python 2.7. On the other hand I failed to port wxPhoenix multiple times in the past, so we don't yet have an alternative to switch to python 3.

* Update to 1.7.3.1
* Switch to github.
* Remove dependency on wxWidgets 2.8.
* Unfinished attempt to run tests.

See: https://trac.macports.org/ticket/46351

See also #4236.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
So, @mojca, what do you want to do here ?

**Comment by mojca** [comment]
Rebasing should hopefully fix the builds. If you have time, please do the rebase. Feel free to merge if it builds. I don't know if the port works, but keeping the pr open won't answer the question.

**Comment by pmetzger** [comment]
@mojca The Azure build failed. Can you fix it? Then I'd say just merge it if it builds.

**Comment by mojca** [comment]
As I said last time, no changes were needed, I just did a rebase.

**Comment by pmetzger** [comment]
Looks like it's building, too. Merge?

**Comment by pmetzger** [comment]
@mojca You deleted rather than merging?

**Comment by mojca** [comment]
User error, sorry. Not intended.

**Comment by mojca** [comment]
So much for GitHub typing to be helpful:
> Pull request closed
> If you wish, you can delete your fork of macports/macports-ports. [Delete fork]

Thanks, GitHub. But did you perhaps consider that I might have another PR open?

I actually accidentally deleted the branch as I thought this was merged already and didn't double-check. It's a problem that I'm now having a gazillion of dead branches still lying around and it's non-trivial to figure out which ones can be removed.

**Comment by pmetzger** [comment]
@mojca You can probably just extract the diffs from this very page and commit them.

**Comment by mojca** [comment]
I merged it already, I still had the branch locally, so it was trivial, sorry for the misunderstanding.
I'm just saying that github could have had a better interface for such cases.

**Comment by pmetzger** [comment]
Indeed, it could.

**Pull request closed without merging**
