### PR TITLE
onetbb: update to 2021.11.0

### PR DESCRIPTION
**Pull request by mohd-akram**
###### Tested on
macOS 14.2.1 23C71 x86_64
Xcode 15.2 15C500b

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?

### CODE REVIEW

**Comment by barracuda156** [comment]
This has broken the port: https://trac.macports.org/ticket/69091

It would be great to have this allowed to be tested first. It is known to be problematic, and upstream does not care about maintaining compatibility.
I did not know about this PR, and in any case 12 hours to merge is an unrealistic timeline to test and fix anything. People sometimes have to sleep after all :)

**Comment by mohd-akram** [comment]
Sorry about that, I figured there were no patch conflicts so all is good. That said, can you be more specific about the issue? I see [builds](https://ports.macports.org/port/onetbb/builds/) pass except for 10.10 and 10.11, and they fail for a different reason.

**Comment by pmetzger** [comment]
It would not have been great to wait until this had been "tested" on PPC. PPC is not a well supported platform at this point.

@barracuda156 You keep insisting that your work to keep PPC systems alive doesn't hurt anyone else, but you also de facto insist that the rest of us spend time and effort making sure that systems almost no one has or uses any more must receive substantial consideration when updates happen. That's a no. If someone updates something and it breaks PPC, that's on the people trying to keep PPC alive, not on the people trying to serve the overwhelming bulk of Mac owners.

It's fine if you want to submit patches to keep old things going, but complaining that we committed something too quickly and it broke PPC is exactly the reason I think we need to stop this.

**Comment by pmetzger** [comment]
(And @mohd-akram you have nothing to be sorry for. You submitted an update and it passed the CI. It was good to go. There was no obligation on your part to check that obsolete hardware still worked.)

**Comment by pmetzger** [comment]
No 32 bit architecture is supported these days. Keeping those going is best efforts. @mohd-akram did nothing wrong.

Again, you claim that your efforts to support old platforms take up no time or effort for anyone else and that you're not asking them to make such efforts, but this is clearly not true. If you want to keep such things working, there's nothing wrong with submitting a patch to do so, but there's something very wrong with saying "you didn't wait until people checked PowerPC still worked."

**Comment by catap** [comment]
Where I stand PPC or legacy platform should be supported as additional and shouldn't block delivery of new version like we have with rust right now.

If upstream breaks legacy platform as fast solution we should pin the old version on that platform until someone is fixed it.

Right now MacPorts has tons of python ports which has pinned version of python before 3.8, the same logic should be applied and for update of ports.

**Comment by barracuda156** [comment]
This fixes the issue: https://github.com/macports/macports-ports/pull/22131

**Pull request merged**
