### PR TITLE
gnucash: force use of python 3.6, remove peg for webkit-gtk3-2.0 on libstdc++, and add PortGroup cxx11 1.1

### PR DESCRIPTION
**Pull request by kencu**
python 3.6 was previously listed as a build dep,
but was not actually used in many cases. This
commit forces the use of python 3.6 during the build.

closes: https://trac.macports.org/ticket/56538
PS: @horasio: I'll share that beer with drkp :>

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.7.5 11G63
Xcode 4.6.3 4H1503 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
So I went ahead and did the rest of the `gnucash` fixes as add-on commits to the PR, to finish it all off. With these fixes, `gnucash` and `gnucash-devel` build through to completion on `10.7.5` configured with our default `libstcd++` and I believe will very likely build through on the other `libstdc++` systems as well.

**Comment by pmetzger** [comment]
@kencu Will you be merging this yourself?

**Comment by kencu** [comment]
>  Will you be merging this yourself?

I think @drkp would best weigh in first as he's quite involved with gnucash. I just seem to have all these older machines around so I can fix up builds on the older systems for people...

**Comment by drkp** [comment]
LGTM -- thanks!

**Comment by kencu** [comment]
build failed on the buildbots because `yelp` is still pulling the conflicting `webkit-gtk3-2.0`, but there is already a PR in the queue to fix this, and once that is in, then everything should build as it does here for me.

**Pull request merged**
