### PR TITLE
multiple ports: change to cxx11 1.1 PG

### PR DESCRIPTION
**Pull request by kencu**
Mass-change remaining ports from cxx11 1.0 PG to cxx11 1.1 PG.
Not all tested.
This can't break any ports, and may fix some of them.

### CODE REVIEW

**Comment by kencu** [comment]
check. BTW @dbevans and @jeremyhu -- here is a version of webkit2-gtk @2.18.0 that we put together some months ago. It works well, but I have had some hiccups building it against the libgcc headers in the cxx11 1.1 PG that I just didnt' feel like getting into -- against libc++ it seems great.

<https://github.com/kencu/myports/tree/master/www/webkit2-gtk>

**Comment by mamoll** [comment]
:+1: the ompl port compiles fine with this change.

**Comment by kencu** [comment]
thanks, everyone. I know this can't make anything worse, so I went ahead and pushed it through. I hope that meets everyone's approval.

**Comment by ryandesign** [comment]
If you're going to do a pull request, it would be nice if you would allow a little time for the maintainers of the affected ports to respond.

I cannot confirm your assertion:

> This can't break any ports

The cxx11 1.1 portgroup's behavior is tied to the value of `configure.cxx_stdlib` *at the time that the portgroup is included*. The mongodb portfile, for example, changes the value of `configure.cxx_stdlib` after it included the cxx11 1.0 portgroup. This was fine. By changing it to the cxx11 1.1 portgroup, you changed the port's behavior in a way that I did not want. To change it back to its previous behavior, `configure.cxx_stdlib` would have to be set before the portgroup is included. I don't know how many other ports are in a similar situation.

**Comment by kencu** [comment]
I'm sorry. I was overeager. You are correct, I should have been more patient and waited 72 hours. I apologize if I caused any distress.

As I did not mess with any revisions, can I revert that for you? Nothing should have changed on the buildbots, and I would not imagine any more than a couple of people might have tried to install it in the few hours since I did that.

Sheepishly, K

**Comment by kencu** [comment]
@ryandesign  -- done. `mongodb` is back in `PortGroup cxx11 1.0`

**Comment by ryandesign** [comment]
I tried to locate other ports that use the cxx11 portgroups and modify `configure.cxx_stdlib`, and I think the only other affected port is root6.

**Comment by kencu** [comment]
Thank you Ryan. I looked over `mongodb` and as it restricts itself to 10.7+ and forces libc++, I'm not fully sure why you have it in the `PortGroup cxx11 1.0`. Should that be deleted?

At any rate, as always, just trying to be helpful and not make anything worse!

**Comment by ryandesign** [comment]
> I looked over mongodb and as it restricts itself to 10.7+ and forces libc++, I'm not fully sure why you have it in the PortGroup cxx11 1.0. Should that be deleted?

It shouldn't be deleted. As with all other ports that use the portgroup, mongodb uses it to signify to the world that this software requires C++11, and to blacklist old compilers that don't support C++11.

**Pull request merged**
