### PR TITLE
update license

### PR DESCRIPTION
**Pull request by conradsnicta**
versions 7.800+ are licensed under the Apache 2.0 license
http://arma.sourceforge.net/license.html

### CODE REVIEW

**Comment by raimue** [comment]
Please follow [CommitMessages](https://trac.macports.org/wiki/CommitMessages) for the commit message format.

**Comment by conradsnicta** [comment]
The change is a simple 1 liner.  It fixes the license, and doesn't modify any source code whatsoever.

I'm not sure why following specific commit message format is required for such a simple change.

**Comment by Schamschula** [comment]
Thanks for pointing this out!

**Comment by raimue** [comment]
@conradsnicta Thank you for your contribution. Commit messages should always indicate which port you are modifying, in order to make it easier to follow activity on GitHub, in commit mails, or with `git log`.

Look at this pull request, nothing indicates which port this is about without looking at the details of the commit, where it can only be seen by examining modified paths. All I was requesting was to use something like "armadillo: update license to Apache-2" as the first line.

**Pull request merged**
