### PR TITLE
glances: restore Lion compatibility

### PR DESCRIPTION
**Pull request by RobK88**
glances: restore Lion compatibility

* bump revision number
* fix maintainer block

###### Type(s)

- [X] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.7.5 11G63 i386
Xcode 4.6.3 4H1503

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [X] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?
- [X] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by RobK88** [comment]
Without these changes, glances will build on Lion but will crash when you run it with an `ModuleNotFoundError: No module named 'orjson'`.  See below:

```
Grinchs-Mac-Pro-2:~ rob$ glances
Traceback (most recent call last):
  File "/opt/local/bin/glances", line 5, in <module>
    from glances import main
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/glances/__init__.py", line 36, in <module>
    from glances.logger import logger
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/glances/logger.py", line 18, in <module>
    from glances.globals import safe_makedirs
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/glances/globals.py", line 36, in <module>
    import orjson
ModuleNotFoundError: No module named 'orjson'
```

**Comment by herbygillot** [comment]
The maintainers block needs to be corrected.

If one or more people are listed as maintainer for a port, such as yourself for this one, then it should also be marked ` openmaintainer`, not ` nomaintainer`.

`nomaintainer` should only be set for a port when no other names or handles are set.

**Comment by barracuda156** [comment]
@RobK88 Please notice also: https://github.com/nicolargo/glances/issues/2930

**Comment by barracuda156** [comment]
@RobK88 How do you get that though? It seems true that, contrary to the earlier situations, Rust builds on 10.7 now, but `orjson` gets replaced in the patch by `ujson`. It should still work as-is.

**Comment by barracuda156** [comment]
image

**Comment by barracuda156** [comment]
@RobK88 Ok, there is no problem with Lion, the problem is that we did not revbump it here: https://github.com/macports/macports-ports/commit/ef663e11132026ca50ec14e54584f6fba4777992

So I assume, you installed the unpatched version, but then portfile changed dependencies.

Unless you really want Lion users to build Rust, just revbump will work perfectly fine.

**Comment by RobK88** [comment]
Thanks for all the feedback.  And yes, at the end of the day, all that needed to be done was:

* Bump revision number
* Fix maintainer block

I forced pushed the changes.

**Pull request merged**
