### PR TITLE
helm*: Allow for multiple versions of Helm/Tiller

### PR DESCRIPTION
**Pull request by pedrohdz**
Allow for multiple versions of Helm to be installed at the same time.

According to the Helm documentation, Helm (client) and Tiller (server)
have to be on the same minor version to be compatible, only the patch
number can vary.

https://helm.sh/docs/using_helm/#upgrading

Closes: https://trac.macports.org/ticket/58723

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
Please instead use sub-ports to add new ports.

**Comment by pedrohdz** [comment]
@mf2k Sure...  Can you recommend an existing implementations I use as a reference?

**Comment by pedrohdz** [comment]
@mf2k 
Like this?  Please check the new commit.  Thanks!

**Comment by sirn** [comment]
Thanks so much for this! 🙇

**Comment by mf2k** [comment]
It looks like you figured it out! Yes, looking at other ports is the way to go. I'm going to wait a little bit for someone else to possibly chime in.

**Comment by pedrohdz** [comment]
I forgot to add an `obsolete` section.  I just force pushed an update with `obsolete` to force people to upgrade and switch installations.

**Pull request merged**
