### PR TITLE
cgit PG: new port group

### PR DESCRIPTION
**Pull request by catap**
#### Description

A new PG to support cgit as source of artefacts

###### Type(s)

- [x] enhancement

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

### CODE REVIEW

**Comment by pmetzger** [comment]
No one seems to have commented on this. I presume you have ports you want to move over to using it? As it doesn't break anything I'm inclined to commit it.

**Comment by catap** [comment]
@pmetzger yes, I do. `gcl-devel` but it doesn't passed CI yet and I've found number of bugs which need to be taking care of.

See: https://github.com/catap/macports-ports/tree/gcl-devel

**Comment by pmetzger** [comment]
So should I commit it?

**Comment by catap** [comment]
@pmetzger I'll be appricieted

**Pull request merged**
