### PR TITLE
ftgl, yafray: ports abandoned

### PR DESCRIPTION
**Pull request by chrstphrchvz**
See: https://trac.macports.org/ticket/24592
See: https://trac.macports.org/ticket/54418
See: https://trac.macports.org/ticket/61210
Closes: https://trac.macports.org/ticket/61213 &larr; (port abandoned ticket)

#### Description

Maintainer's GitHub handle appears to be @krugazor (let us know if still interested in maintaining these ports!)

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jasonliu--** [comment]
By the way, since the description for the yafray port mentions Blender, I thought that I should point out that even though the YafRay/YafaRay developers do release an exporter that allows YafaRay to render Blender files, the Blender software itself doesn't have any code that has anything to do with YafaRay. So removing the yafray port from the tree won't affect the blender port in any way.

**Comment by chrstphrchvz** [comment]
@jasonliu-- the `yafray` port has been outdated and broken for a long time (last attempt updating it to YafaRay was 4 years ago): https://trac.macports.org/ticket/24592 . I would propose removing it if no one seems to want/need it badly enough.

**Comment by jasonliu--** [comment]
> I would propose removing it if no one seems to want/need it badly enough.

No objections from me. If someone in the future wants to take up the torch and create a new, properly working port for YafaRay, similar to what I've done for Blender, then let them. In the meantime, there's no point in keeping an obsolete, barely functioning port in the tree if no one is using it. If someone does still want or need it, then hopefully they'll speak up sooner rather than later.

**Comment by chrstphrchvz** [comment]
I have added a commit to delete `yafray`.

**Pull request merged**
