### PR TITLE
dspl: new port in science

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

New port in science: http://en.dsplib.org

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Wonder why it cannot find `libgfortran`:
```
/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_dspl/dspl/work/compwrap/cc/usr/bin/clang -shared -o ../_release/libdspl.so obj/array.o obj/convolution.o obj/dft.o obj/filter_design.o obj/gnuplot.o obj/inout.o obj/math.o obj/math_ellipj.o obj/math_poly.o obj/matrix.o obj/mt19937.o obj/psd.o obj/randgen.o obj/resampling.o obj/signals.o obj/statistic.o obj/trapint.o obj/types.o obj/unwrap.o obj/verification.o obj/win.o obj/xcorr.o -lm -L/opt/local/lib -llapack -lblas -lgfortran -lquadmath
  ld: library not found for -lgfortran
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Given that the portfile has `require_fortran`.

**Comment by kencu** [comment]
> Wonder why it cannot find `libgfortran`:
> 
> ```
> /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_dspl/dspl/work/compwrap/cc/usr/bin/clang -shared -o ../_release/libdspl.so obj/array.o obj/convolution.o obj/dft.o obj/filter_design.o obj/gnuplot.o obj/inout.o obj/math.o obj/math_ellipj.o obj/math_poly.o obj/matrix.o obj/mt19937.o obj/psd.o obj/randgen.o obj/resampling.o obj/signals.o obj/statistic.o obj/trapint.o obj/types.o obj/unwrap.o obj/verification.o obj/win.o obj/xcorr.o -lm -L/opt/local/lib -llapack -lblas -lgfortran -lquadmath
>   ld: library not found for -lgfortran
>   clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> Given that the portfile has `require_fortran`.

because ```-lgfortran``` is not in  ```-L/opt/local/lib``` (or any of the default locations the compiler will tell the linker to look for it).

It is here:

```
/opt/local/lib/libgcc/libgfortran.dylib
```

and that search path:

```
-L/opt/local/lib/libgcc
```
has not been added to the linkers search paths yet.

**Comment by barracuda156** [comment]
@kencu Okay, it’s a clang thing. I will add the flag, thank you!

**Comment by barracuda156** [comment]
@kencu Perfect, all works now. Thank you again!

**Comment by barracuda156** [comment]
@harens May I ask you to merge this, please?

**Review by harens — APPROVED** [review]
Thanks @barracuda156 for your work on this! 🎉

**Pull request merged**
