### PR TITLE
sbcl: pin 2.2.5 before 10.7

### PR DESCRIPTION
**Pull request by catap**
#### Description

I've pin 2.2.5 before 10.7 for everything, to make support much easy.

PowerPC support was backported from 2.2.2 into 2.2.5.

I also reorganized patches to keep it as git trees.

###### Type(s)

- [x] bugfix
- [x] enhancement

###### Tested on

macOS 10.5.8 9L34 i386
Xcode 3.1.4 9M2809

and as `port install sbcl` and `port install build_arch=i386` on

macOS 10.6.8 10K549 x86_64
Xcode 3.2.6 10M2518

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
@barracuda156 as a side effect I may fix threads on PowerPC. Anyway, I have no way to test it => I can't fix it blidnly :(

**Comment by barracuda156** [comment]
> @barracuda156 as a side effect I may fix threads on PowerPC. Anyway, I have no way to test it => I can't fix it blidnly :(

@catap Wait with merging, let me try.

**Comment by barracuda156** [comment]
Some define missing:
```
/usr/bin/gcc-4.2 -g -Wall -O2 -fdollars-in-identifiers -mmacosx-version-min=10.4 -isystem/opt/local/include/LegacySupport -I. -no-cpp-precomp  -c -o darwin-os.o darwin-os.c
os.h:233: warning: 'os_sem_init' declared inline after being called
os.h:233: warning: previous declaration of 'os_sem_init' was here
/usr/bin/gcc-4.2 -g -Wall -O2 -fdollars-in-identifiers -mmacosx-version-min=10.4 -isystem/opt/local/include/LegacySupport -I. -no-cpp-precomp  -c -o ppc-darwin-os.o ppc-darwin-os.c
ppc-darwin-os.c:28:2: error: #error "Define threading support functions"
make: *** [ppc-darwin-os.o] Error 1
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_sbcl/sbcl/work/sbcl-2.2.2" && sh make.sh --prefix=/opt/local --xc-host=/opt/local/libexec/sbcl-bootstrap/bin/sbcl --arch=ppc --with-sb-thread --without-mach-exception-handler 
Exit code: 2
```

**Comment by barracuda156** [comment]
@catap I mean, they just broke it intentionally:
```
#ifdef LISP_FEATURE_SB_THREAD
#error "Define threading support functions"
#else
```

**Comment by catap** [comment]
Seems that threads on PPC is broken by design: https://github.com/sbcl/sbcl/commit/33a6b2817f3e2a8cf98d162a2b40c50d259295c4

Or at least compleley disabled since 0.9.14

**Comment by catap** [comment]
@barracuda156 thanks for testings, I've added that commit as note to the port file.

**Comment by barracuda156** [comment]
> Seems that threads on PPC is broken by design: [sbcl/sbcl@33a6b28](https://github.com/sbcl/sbcl/commit/33a6b2817f3e2a8cf98d162a2b40c50d259295c4)
> 
> Or at least compleley disabled since 0.9.14

And that is why 1.0.47 bootstrap binary lacks threads feature.

**Comment by catap** [comment]
Sergey had probably found a cause of failed / disbaled tests. Digging.

**Comment by catap** [comment]
@barracuda156 I not sure that differences between 2.2.2 and 2.2.5 worth to revert removed PPC :)

**Comment by barracuda156** [comment]
@catap It worked:
```
36-25% port -v installed sbcl
The following ports are currently installed:
  sbcl @1.5.9_0 requested_variants='' platform='darwin 10' archs='ppc' date='2022-05-16T17:16:23+0800'
  sbcl @2.0.9_0 requested_variants='' platform='darwin 10' archs='ppc' date='2022-05-20T05:22:37+0800'
  sbcl @2.2.5_0 (active) requested_variants='' platform='darwin 10' archs='ppc' date='2023-06-05T23:15:40+0800'
```

**Comment by catap** [comment]
@barracuda156 am I right that you don't need `patch-legacy-disable-mailbox.diff` to build it?

**Comment by barracuda156** [comment]
UPD. Since there is no clear performance gain in 2.2.5 as compared to 2.2.2, we decided to leave PPC at 2.2.2 for the time-being. May return to this in a while.

**Comment by catap** [comment]
Marked as a draft because I'd like to accomulate @barracuda156 's branch to support PowerPC on 2.2.5; and need some time to stabilize tests

**Comment by barracuda156** [comment]
> Ok, it's done.
> 
> @barracuda156 may I ask you to check that it can be installed on PowerPC? After that may you try to install something trivial without threads... let say `port test cl-ppcre common_lisp.ecl=no common_lisp.clisp=no`.

@catap Sure, will do now. Fortran testing round is finished.

**Comment by barracuda156** [comment]
```
; wrote /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lisp_cl-ppcre/cl-ppcre/work/.home/.cache/common-lisp/sbcl-2.2.5-macosx-ppc32/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lisp_cl-ppcre/cl-ppcre/work/build/source/cl-ppcre/test/perl-tests-tmp70X8ZE5V.fasl
; compilation finished in 0:00:00.311
Test: Running tests in file "perltestdata"
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
...
Test: Optimized test functions - this might take some time...
Test: Simple tests from file "simple"
.......

WARNING:
   Computing just-done stamp in plan NIL for action (ASDF/LISP-ACTION:TEST-OP
                                                     "cl-ppcre"), but dependency (ASDF/LISP-ACTION:LOAD-OP
                                                                                  "cl-ppcre") wasn't done yet!
WARNING:
   Computing just-done stamp in plan NIL for action (ASDF/LISP-ACTION:TEST-OP
                                                     "cl-ppcre"), but dependency (ASDF/FIND-SYSTEM:DEFINE-OP
                                                                                  "cl-ppcre") wasn't done yet!
; 
; compilation unit finished
;   caught 6 STYLE-WARNING conditions
;   printed 1769 notes
All tests passed.
```

**Comment by catap** [comment]
it works!

**Comment by herbygillot** [comment]
Is this ready to merge?

**Comment by barracuda156** [comment]
@herbygillot We are still working on getting the later version fixed (on my end it implies a day or rather two), however the version here is fully functional and in this sense good to merge, AFAIU; any further update can be done in a separate PR.
Let @catap decide, I am okay with either.

**Comment by catap** [comment]
@herbygillot yes, this one is ready. As Sergey said the goal is have the last version on old system also, but it requires some extra work.

=> feel free to merge it. Thanks!

**Pull request merged**
