### PR TITLE
FAudio: update to 24.10

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
@barracuda156 according to the CI this fails on macOS 15 and there is a [Trac ticket ](https://trac.macports.org/ticket/70752) - please take a look.

**Comment by barracuda156** [comment]
@reneeotten I have opened an issue with upstream: https://github.com/FNA-XNA/FAudio/issues/362
Closing this, I have no interest to work on macOS 15 myself.

**Comment by reneeotten** [comment]
no need to close the PR. If it's the same issue as in the ticket there is a workaround that apparently works so you could just use that.
Thanks for opening an issue upstream; it this works elsewhere and only mot on macOS 15 right mow, we can still merge this - but not if you close the PR 😉

**Comment by kencu** [comment]
somehow seems to be building on macOS 15 for homebrew…

https://github.com/Homebrew/homebrew-core/blob/master/Formula/f/faudio.rb

**Comment by kencu** [comment]
ah, it’s the deployment target fix.

you need to modify this:

https://github.com/barracuda156/powerpc-ports/blob/52cb1dbb0cd625f1f46d83e202e971a722dc4bcb/audio/FAudio/Portfile#L40

**Comment by barracuda156** [comment]
@kencu Yeah, was just going to reply that perhaps same bug as on Sonoma.

**Comment by kencu** [comment]
close your upstream issue, or at least modify it.

they set the deployment target in their build so don’t see this… macports strips it out with a patch, so we do.

(still needs fixing upstream, imho, somehow. but we break it.)

**Comment by kencu** [comment]
I guess we'll see if this issue is restricted to arm processors... it might be.

**Pull request merged**
