### PR TITLE
zabbix4[2]*: Update to 4.0.13 and 4.2.7

### PR DESCRIPTION
**Pull request by eborisch**
Maintainer update.

### CODE REVIEW

**Comment by pmetzger** [comment]
Any idea why the CI failed?

**Comment by eborisch** [comment]
I haven’t had a chance to look just yet.

**Comment by pmetzger** [comment]
@eborisch Should I leave this to you to deal with then? (After all, you can merge it yourself...)

**Comment by eborisch** [comment]
Yes; thanks!

**Pull request merged**
