### PR TITLE
qt6: Add initial qt6 ports

### PR DESCRIPTION
**Pull request by jhoyt4**
#### Description

Adds some initial QT6 capabilities / sub ports.

Additional subports will be added in future PR's - this PR is mainly to get an initial set of qt6 based sub ports working.

Happy to have  another set of eyes on this for tips and/or help

Closes [Ticket 62982](https://trac.macports.org/ticket/62982)

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.6 20G165 x86_64
Xcode 13.0 13A233

AND

macOS 11.6 20G165 arm64
Xcode 13.0 13A233

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

"tested basic functionality of all binary files?" - qt6 is rather expansive - saying that I could check all executables would be a stretch....

### CODE REVIEW

**Comment by jhoyt4** [comment]
That last commit should fix a lot of issues for applications that use cmake to build. The main problem was that shifting to build moduls with cmake broken the Portfile's mechanism to symlink the lib/cmake files.

**Comment by jhoyt4** [comment]
Converting back to draft as I work through a TON of new dependency issues as I try to bring additional qt submodule features online

**Comment by jhoyt4** [comment]
I've been hammering away trying to resolve an issue where optional features in a TON of the modules fail to configure if QtQuick (installed by qtdeclarative) is available.  This all started after I added qtshadertools which qtdeclarative automagically picks up as a dependency.  

My current thoughts are that I am going to remove qtshadertools from the portfile / dependencies to get things building / an initial cut at the Portfile ready for submission.  This way we at least get some qt6 functionality (i.e. a default build) working and available.

**Comment by jhoyt4** [comment]
|                     | Builds? | issue                                       | Notes              |
|---------------------|---------|---------------------------------------------|--------------------|
| qt6                 | yes     |                                             |                    |
| qt6-mysql-plugin    | yes     |                                             |                    |
| qt6-psql-plugin     | yes     |                                             |                    |
| qt6-qt3d            | partial |                                             | Fails with QtQuick |
| qt6-qt5compat       | partial |                                             | Fails with QtQuick |
| qt6-qtbase          | yes     |                                             |                    |
| qt6-qtcharts        | no      | Hold back due to qtmultimedia               |                    |
| qt6-qtconnectivity  | yes     |                                             |                    |
| qt6-qtdeclarative   | partial | QtQuick causes issues, thanks qtshadertools |                    |
| qt6-qtimageformats  | yes     |                                             |                    |
| qt6-qtlocation      | partial |                                             | Fails with QtQuick |
| qt6-qtmultimedia    | no      | Hold back due to qtshadertools            |                    |
| qt6-qtnetworkauth   | yes     |                                             |                    |
| qt6-qtremoteobjects | yes     |                                             |                    |
| qt6-qtscxml         | no      | Hold Back due to QtQuick                    | Fails with QtQuick |
| qt6-qtsensors       | partial |                                             | Fails with QtQuick |
| qt6-qtserialbus     | yes     |                                             |                    |
| qt6-qtserialport    | yes     |                                             |                    |
| qt6-qtshadertools   | yes     | Hold Back due to QtQuick                    |                    |
| qt6-qtsvg           | yes     |                                             |                    |
| qt6-qttools         | yes     |                                             |                    |
| qt6-qttranslations  | yes     |                                             |                    |
| qt6-qtwebchannel    | partial |                                             | Fails with QtQuick |
| qt6-qtwebsockets    | partial |                                             | Fails with QtQuick |
| qt6-sqlite-plugin   | yes     |                                             |                    |

**Comment by jhoyt4** [comment]
Assuming I just fixed the conflict with qt-base and the SQL-plugins (i.e. it gets through the lint and build checks), I'll be  marking this "Ready for review"

**Comment by jhoyt4** [comment]
That rebaseline should pull in openssl 3, we'll see how this goes...

**Comment by jhoyt4** [comment]
> That rebaseline should pull in openssl 3, we'll see how this goes...

@mascguy - followed your tip on the other PR to rebase [hopefully] the right way

**Comment by jhoyt4** [comment]
Looks like it built with openssl3.  I also just finished building qt6-qtbase on macOS 12.0.1 21A559 arm64 / Xcode 13.1 13A1030d without any issues.

**Comment by mascguy** [comment]
> Looks like it built with openssl3.  I also just finished building qt6-qtbase on macOS 12.0.1 21A559 arm64 / Xcode 13.1 13A1030d without any issues.

Haven't scrutinized every line, but looks great overall!

Are you ready for us to merge this?

**Comment by jhoyt4** [comment]
I think I'm ready for the merge - would still have liked another few sets of qt-saavy eyes on it.

Either, way, I'll keep an eye on trac to help troubleshoot any tickets that pop up.

**Comment by jhoyt4** [comment]
@reneeotten @kencu - Any chance you two have some additional time to look over the Portfile before it gets merged?

**Comment by chrstphrchvz** [comment]
Could we please not add plugins for end-of-life versions of MariaDB (5.5, 10.1, maybe even soon-to-be EOL 10.2)? It would be easier to propose removing old versions of MySQL, MariaDB, etc. if there weren’t so many ports/variants still depending on them.

**Review by chrstphrchvz — CHANGES_REQUESTED** [review]
I believe qt6-qtbase as proposed is affected by https://trac.macports.org/ticket/62104: qtbase opportunistically enables Vulkan support if Vulkan headers are detected on someone’s system, which may lead to build failure. If others approve of the fix I proposed in #12837 (explicitly disable Vulkan support), I suggest incorporated it into qt6-qtbase as well. Although, it may be desirable to eventually explicitly enable Vulkan support.

**Comment by jhoyt4** [comment]
@chrstphrchvz - Done.  I have removed the EOL database plugins, but if its still reported to be developed (i.e. mariadb-10.2, mysql5.7) I have left it in the portfile.

@mascguy - should I squash all commits into one?  I left them as multiple to help any reviewers understand what was changing while this was a WIP.

**Comment by mascguy** [comment]
> @mascguy - should I squash all commits into one? I left them as multiple to help any reviewers understand what was changing while this was a WIP.

I'm fine with leaving them as multiple commits, to maintain the history. Does anyone have an objection to that?

**Comment by mascguy** [comment]
The CI builds passed, so let's merge. Awesome work @jhoyt4!

**Comment by reneeotten** [comment]
thanks @jhoyt4 ! I am sorry but haven't had the time to take a thorough look at this - will give it a spin myself locally and see if I can get some more things to build and/or if changes are needed.

(The commits should have been squashed though before merging as per our PR checklist; if you ask for opinions you'll need to give some time for people to actually look at it and not just merge the same day)

**Comment by chrstphrchvz** [comment]
> should I squash all commits into one? I left them as multiple to help any reviewers understand what was changing while this was a WIP.

As a note, an open GitHub pull requests shows all of the times when its branch was force-pushed, and all of the previous commits are still available. (I would still squash at least whenever there are changes which should be made simultaneously.)

**Pull request merged**
