### PR TITLE
neomutt: give up maintainership

### PR DESCRIPTION
**Pull request by lbschenkel**
Normal version bumps aside, this port has been frequently modified without me (the maintainer) being notified about the changes. Since I'm not able to participate on setting the future direction of the port nor I feel confident being able to troubleshoot new issues when I'm not aware of the current state of it, I feel that I cannot really function as the responsible person for the port and therefore I'm relinquishing the role.

### CODE REVIEW

**Comment by lbschenkel** [comment]
Amended to 'nomaintainer'.

I didn't want to remove 'openmaintainer' out since I'm OK with simple version bumps and other trivial changes — I certainly have no desire in micromanaging those. As stated in the docs, I should be in the loop regarding other changes. This is especially important since it's to me that any eventual tickets opened against the port will be sent to, and it's unfair if I'm responsible for changes I'm not doing nor I have been aware of.

Plus, since the past changes have been done bypassing policy, there's no indication that removing 'openmaintainer' will do anything to address that particular problem.

**Comment by danielluke** [comment]
I have several ports that don't have openmaintainer (because I want to for sure know about any changes with them) and there have only been rare instances when it wasn't respected. I agree that people making changes under openmaintainer should keep the maintainer in the loop (and that that doesn't always happen). I'm sorry that you feel the best solution for you is to drop maintainership - but am thankful that you spent time maintaining this port.

**Comment by lbschenkel** [comment]
In this case 'nomaintainer' will still allow me to open PRs against this port (which I have do to anyway since I don't have commit rights), but will relieve me of being the person who has to address incoming tickets for the changes I'm not making.

I deliberately didn't ask for commit rights since I like to have another pair of eyes double-checking the changes I do to the ports I maintain, for the benefit of the project (I would do that even if I was a committer). Since I can't even change the ports I maintain, seeing those very same ports changed directly by other committers apparently without consideration of the maintainership role made me disinterested in volunteering my time for this port.

You can please go ahead and merge.

**Comment by l2dy** [comment]
@lbschenkel I'm really sorry for updating your port without your consent. The two relating commit should be ac2d5c99ed8e4b11be8aaeabfec0c2cd064afcef and 1549df2aea47aab40a4d648e5bb6619d7e08c19e.
I directly committed them because I have strong confidence in that the changes won't cause any trouble and I've put explanations in the commit messages.
Both commit intend to remove unrecognized configure args and the first also allowed use of multiple header cache backends.
Sorry again and I will notify the maintainer about nontrivial changes from now on.

**Comment by l2dy** [comment]
I've updated 200+ ports in 440+ commits and finding the corresponding GitHub username on Trac every time costs too much time than I could afford. Tracking maintainer timeouts is also difficult. I'm working on a bot that automatically notifies the maintainer when a PR is submitted and manage PR labels which should solve the problem.

P.S. I too wanted to stick to the always PR approach for the same reason, but committers were tired of reviewing my PRs and asked me to request for commit access.

**Comment by lbschenkel** [comment]
Hi l2dy. Thanks for chiming in.

Just to clarify, I have no issue with the nature of your changes. They all look sensible, and I believe I would have said "sure, go ahead" for all of them. My point is that the concept of maintainership is meaningless if ports are modified (trivial changes aside) without the involvement of the maintainer, at least to be kept in the loop. It just comes with the drawback, since I'm going to be the contact point for issues.

In other words, if committers can directly do non-trivial changes to ports without trying to contact the maintainer, then there's no actual difference among a port with a maintainer, a port with 'openmaintainer', or without a maintainer at all.

I understand that you're just trying to contribute and I appreciate all your effort and it can be frustrating when maintainers are not responsive. However, when you're modifying the Portfile my contact info is just lying there in front of you: that is my e-mail. You don't need to hunt me down. Unless something got lot somewhere, from my perspective there was no single attempt to ever write me an e-mail. All you need to do is to send me the link to the tentative PR, or send a link to your repo, or a diff, and usually I'll reply in less than 24 hours. I don't think that's too much to ask or a great burden to you. (I would also have added by GitHub handle to the Portfile, once I knew it would make your life easier.) I certainly don't want anything more bureaucratic than that, especially to avoid discouraging contributions. In case I was not replying and becoming a bottleneck, I would have been way more sympathetic.

I appreciate your energy and contributions to this port, and you look very invested, so why don't you volunteer to be the maintainer instead?

P.S.: Your latest changes broke the build for 10.6:
```
Status:       Failure
Build slave:  ports-10.6_i386_legacy
Full logs:    https://build.macports.org/builders/ports-10.6_i386_legacy-watcher/builds/6777
Build reason: The SingleBranchScheduler scheduler named 'ports' triggered this build
Port list:    neomutt
Subport list:
	- neomutt
Variants:     None
Revision:     1549df2aea47aab40a4d648e5bb6619d7e08c19e
Build time:   0:06:59
Author:       Zero King <l2dy@macports.org>

Log from failed builds:
	Building 'neomutt' ... [ERROR]
	> maintainers: leonardo@schenkel.net.

Broken ports:
	- neomutt

Responsible maintainers:
	- leonardo@schenkel.net

Links to individual build jobs:
- ports-10.6_i386_legacy-builder #22817
  https://build.macports.org/builders/ports-10.6_i386_legacy-builder/builds/22817
```
Note that I'm the one who is notified and has to figure out what was changed and why it got broken, plus it's likely that somebody will create an issue for this and assign it to me. I hope that you can see how this can also take a toll on my time, and I'm way more willing to volunteer my time on addressing things that I've changed myself or at least I had the change to look at and given the OK to.

Or if you were at least the co-maintainer you could also take responsibility/ownership for these things.

**Comment by l2dy** [comment]
I'm willing to co-maintain the port.

Regarding the broken build, it seems to be https://trac.macports.org/ticket/54219 and my latest commit was made yesterday.

**Comment by lbschenkel** [comment]
The buildbot was trying to build this the port with this change:
https://github.com/macports/macports-ports/commit/1549df2aea47aab40a4d648e5bb6619d7e08c19e

Since you're spending way more time/energy on this port than I am, I am OK with you taking over the maintainership. If I have any contributions I can send them to you instead. This seems to be the optimal solution since you're not going to be burdened with having to contact me and the workflow for me stays exactly the same, since I don't have commit right anyway.

**Comment by l2dy** [comment]
I'm a student right now and I have no idea if I'll have enough time for contributions to OSS after I graduate. If you insist giving up maintainership I'll take it over but please reconsider.

**Comment by l2dy** [comment]
The bot I'm implementing will contact maintainers so It won't be a burden by then.

**Comment by l2dy** [comment]
https://github.com/neomutt/neomutt/commit/fce65a1fa5a6a55d58d6810c80c3782d5ec637a3#diff-8d3e8f7411beefc4b162f0d8a5622353R119

This commit removed the `-` and caused build failure.

**Comment by l2dy** [comment]
#498 attempts to fix the build.

**Comment by l2dy** [comment]
I've added myself as co-maintainer and fixed the build.

**Comment by lbschenkel** [comment]
OK, since you became co-maintainer I'm willing to reconsider. I still would like to be in the loop/be sent a PR for any non-trivial changes (mostly everything that's not a simple version bump); I should in most cases respond within 24h. In case I don't respond for, let's say, 48h, you're always free to go ahead and merge.

Will that work for you?

**Comment by l2dy** [comment]
Works for me.

**Comment by lbschenkel** [comment]
Since you have commit access, I would appreciate if you could add my GitHub handle to the Portfile so you don't need to look me up. Thanks.

**Comment by l2dy** [comment]
Done in ca52ce34ec2e49666c5dff078fcff4a59ec38884.

**Pull request closed without merging**
