### PR TITLE
py-scipy: drop py3{5-7} subports, same for all dependents

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
In preparation for an update to the latest upstream version (1.11.4), clean-up the subports for EOL Python versions in `py-scipy` and all its dependents. In order to make maintenance easier (e.g., the latest SciPy version uses the `meson-python` backend), split off the `py27` subport into its own Portfile (i.e., `py27-scipy`).

There are two ports (`py-mlpy` and `py-pyne`) that do not build with recent Python versions and/or recent OS versions. The first one hasn't seen a release since 2012 and should/could be considered dead; the latter is still actively developed and I tried to update but couldn't get it to work in the amount of time I'm willing to spend on it.

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by jjstickel** [comment]
> @jjstickel for port py-fipy, py-scimath, py-wntr. 

LGTM

**Comment by ra1nb0w** [comment]
> @ra1nb0w for port py-commpy

LGTM

**Review by lpsinger — COMMENTED** [review]
The lal* packages are all very old and of no practical use to the LIGO community at this point. Should we drop them?

**Comment by reneeotten** [comment]
> The lal* packages are all very old and of no practical use to the LIGO community at this point. Should we drop them?

I have no opinion about that as I don't use any of them. You're the maintainer so in the end it's your call I think; as an intermediate step you could use the `obsolete` PortGroup to indicate that upstream isn't supporting the packages anymore and/or you're intending to drop them at some point from MacPorts.

**Comment by pmetzger** [comment]
@reneeotten I think enough time has passed, you can decide how to proceed.

**Comment by lpsinger** [comment]
I'm just going to mark them as `nomaintainer`. If they _were_ updated, they might be useful. I think that most users of lal on macOS either use Conda or pip installation.

**Comment by pmetzger** [comment]
I merged @lpsinger's commit to make those ports `nomaintainer`.

**Pull request merged**
