### PR TITLE
terraform: fix checksums for 1.2 and 1.3

### PR DESCRIPTION
**Pull request by GerardSoleCa**
#### Description

Versions 1.2 and 1.3 of terraform port seem to be broken, at least in my setup I cannot install them. This affects terragrunt port too. Since some versions relay on terraform-1.2 and cannot be installed due to checksum mismatch.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.0 23A344 arm64
Xcode 15.0 15A240d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by herbygillot** [comment]
Can you verify the checksums for amd64 as well?

You can use a command such as `sudo port -d checksum terraform-1.2 build_arch=x86_64`

**Comment by GerardSoleCa** [comment]
> sudo port -d checksum terraform-1.2 build_arch=x86_64

You where right, both where outdated too

**Comment by herbygillot** [comment]
> > sudo port -d checksum terraform-1.2 build_arch=x86_64
> 
> You where right, both where outdated too

Thanks

**Comment by GerardSoleCa** [comment]
@herbygillot I don't understand why pipeline fails for macos-13. I saw the other two platforms succeeding. I've also downloaded the amd64 zip file and checked both checksums. I'm getting the ones seen in this pull request:

```bash
❯ openssl dgst -rmd160 ~/Downloads/terraform_1.3.9_darwin_amd64.zip
RIPEMD-160(/Users/gerard/Downloads/terraform_1.3.9_darwin_amd64.zip)= 0683c695a7c3c40bdb5949a7a021e1c38a89880a
❯ shasum -a 256 ~/Downloads/terraform_1.3.9_darwin_amd64.zip
a73326ea8fb06f6976597e005f8047cbd55ac76ed1e517303d8f6395db6c7805  /Users/gerard/Downloads/terraform_1.3.9_darwin_amd64.zip

**Comment by herbygillot** [comment]
Re-running checks...

**Comment by GerardSoleCa** [comment]
> Re-running checks...

I have figured out what's going on. The test uses the distfile `https://distfiles.macports.org/terraform/terraform_1.3.9_darwin_amd64.zip`. This happens to have a different sum than the releases retrieved from the hashicorp release page configured in the portfile.

```bash
❯ curl https://distfiles.macports.org/terraform/terraform_1.3.9_darwin_amd64.zip -o /tmp/macport-distfile.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.2M  100 20.2M    0     0  1885k      0  0:00:10  0:00:10 --:--:-- 2383k
❯ shasum -a 256 /tmp/macport-distfile.zip
ca78815afd657f887de7f9b74014dc4bddffe80fd28028179b271a3c4f64f29a  /tmp/macport-distfile.zip

**Comment by pmetzger** [comment]
https://trac.macports.org/wiki/PortfileRecipes#stealth-updates

**Comment by GerardSoleCa** [comment]
Hi @pmetzger and @herbygillot,

I've pushed a new commit with the solution proposed by @pmetzger.

Thanks for the documentation of this issue!

**Comment by pmetzger** [comment]
@GerardSoleCa You should document in comments that the lines to deal with the stealth update should be removed in the next update of the port. Once that's done I think we can commit. Thank you so much for your work!

**Comment by GerardSoleCa** [comment]
@pmetzger there you go! Hope the comment is enought!

**Comment by pmetzger** [comment]
I don't think you can remove it when bumping the revision; revision bumps don't imply new distfiles, and the problem is the distfiles. It would be something to remove when upgrading the port to 1.4 etc.

**Comment by GerardSoleCa** [comment]
> I don't think you can remove it when bumping the revision; revision bumps don't imply new distfiles, and the problem is the distfiles. It would be something to remove when upgrading the port to 1.4 etc.

But there are more updates over there, in fact, seems like the port is written in a way that supports multiple versions in parallel. So, I'm not sure which comment would be the good in that situation.

**Comment by pmetzger** [comment]
The point is that new versions that haven't been stealth updated don't need the hack and that people maintaining the file after you should be aware that it's a hack because of a stealth update.

**Comment by GerardSoleCa** [comment]
Uhm, I've updated the comment to something more specific. This way we can let know developers that the version is using that for the stealth update.

**Pull request merged**
