### PR TITLE
Updated Port lttoolbox to version 3.5.0

### PR DESCRIPTION
**Pull request by saptarshi1729**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.15.3 19D76

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?

### CODE REVIEW

**Comment by JacksonIsaac** [comment]
About commit message:
I would skip mentioning Issue #... in the main commit message, you can add it as description. Maybe take a look again at commit guidelines or other commits in the repository for ideas.

About the build error:
Looks like it complains at the maintainers line. Maybe the azure pipeline is broken, since it also mentions that more pipelines were failed in past 24 hours.

Btw, did you try to build this port locally, after the changes ?

About the Pull Request Description:
Please do not delete the entries if it is not checked. For E.g., https://github.com/macports/macports-ports/pull/6648

**Comment by saptarshi1729** [comment]
Hi Sir,

Thanks a lot for the suggestion. It's probably an error with the size of
the zipped file that needs to be specified. I'll try correcting and
verifying it and update it soon. As advised, I'll skip the phrase 'Issue
#'. In regard to the question on 'build', it's true that I had not built
it; I couldn't figure out the command for the same, and *sudo port test* didn't
show any results. (I don't use XCode and am using the MacOS terminal for
all testing purposes.) So, I had skipped that part and also left it
unchecked during submission (in fact, deleted the option from the text).

Thanks and Regards,
Yours Sincerely,
*Saptarshi Mukherjee,*
*Chairperson, Students' Senate,*
*IIT Bhilai.*

**Comment by JacksonIsaac** [comment]
> In regard to the question on 'build', it's true that I had not built it; I couldn't figure out the command for the same, and *sudo port test* didn't show any results. (I don't use XCode and am using the MacOS terminal for all testing purposes.) So, I had skipped that part and also left 

You don't need to run anything using XCode, You may run these commands via the command line, if you have macports installed.

'port test' will run if you have any tests defined in the Portfile.

Most of the times I test my changes by running 'sudo port install -v -t <portname>'

**Comment by saptarshi1729** [comment]
Hi Sir,

Thanks a lot for the valuable suggestions. I've hopefully fixed the error. *May
kindly observe the changes made and provide necessary feedback/review, *I'll
be considerably grateful for the same. I'd like to emphasize that it was
great working on the issue, and I look forward to brighter experiences
while facing more challenging issues or while working on the esteemed
project plans in my proposal.

Thanks and Regards,
Yours Sincerely,
*Saptarshi Mukherjee,*
*Chairperson, Students' Senate,*
*IIT Bhilai.*

**Comment by JacksonIsaac** [comment]
Looks good to me

**Comment by JacksonIsaac** [comment]
Congrats on your first commit to MacPorts!

**Comment by saptarshi1729** [comment]
Thanks Sir.

**Pull request merged**
