### PR TITLE
apache-geode: port abandoned

### PR DESCRIPTION
**Pull request by chrstphrchvz**
See: https://trac.macports.org/ticket/58631
Closes: https://trac.macports.org/ticket/64301

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
I believe the port maintainer’s GitHub handle is @kjduling

**Comment by chrstphrchvz** [comment]
@mascguy since this is another Java-related port, would you be interested in it being kept and updated?

**Comment by mascguy** [comment]
> @mascguy since this is another Java-related port, would you be interested in it being kept and updated?

Well, my interest in Hadoop mostly relates the industry momentum behind it. (Plus it's something I've wanted to look at for a long time anyway.) So it's a special case.

As for other ports like this one, I'll take a look.

Overall though, my plate is already quite full. So I don't anticipate taking on many Java ports. (At least not as an the official maintainer.) Though I'm happy to pitch in and assist with fixes and updates!

Net-Net, I'll get back to you on this one. Lol

**Comment by mascguy** [comment]
Since we're simply updating the maintainer, rather than obsoleting, I'm good with this.

And while I can't commit to formally maintaining this port, let's keep it around for now.

**Review by mascguy — APPROVED** [review]

**Comment by pmetzger** [comment]
Okay, this is now officially "nomaintainer".

**Pull request merged**
