### PR TITLE
gr-air-modes: Use frameworks_dir

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

Use `frameworks_dir`

### CODE REVIEW

**Comment by pmetzger** [comment]
This feels like it falls under the openmaintainer policy.

**Comment by michaelld** [comment]
I'm getting there ... can I please even get 24 hours to see what's going on? There are likely other ports of mine that will benefit from this change.

**Comment by pmetzger** [comment]
@michaelld I'm pretty sure @ryandesign is going to do pull requests for all of them. If you feel like merging this yourself, btw, please do!

**Comment by ryandesign** [comment]
> I'm pretty sure @ryandesign is going to do pull requests for all of them

As I find time. If maintainers want to fix this or any other problems in their own ports, they're highly encouraged to do so.

**Pull request merged**
