### PR TITLE
git: catch any error when reading ${guidir}/Info

### PR DESCRIPTION
**Pull request by kurthindenburg**
This fixes the destroot error "The domain/default pair of ... does not exist"

closes: https://trac.macports.org/ticket/67106

Catch any errors from reading '${destroot}${guidir}/Info'

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.4 22F66 x86_64
Xcode 14.3.1 14E300c

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by kurthindenburg** [comment]
I added this for further discussion if there's a better way of doing this or why everyone isn't having this same issue.

**Comment by pmetzger** [comment]
Sorry that this has apparently languished for half a year without anyone looking at it. @herbygillot what is your opinion?

**Comment by pmetzger** [comment]
@herbygillot ? @ci42 ?

**Comment by pmetzger** [comment]
@herbygillot ?

**Comment by kurthindenburg** [comment]
It was not  obvious to me why it appears that I was the only one having this issue. I know I had to use this patch a few times last year.  But a new install from source today, didn't need this patch to install.

**Comment by reneeotten** [comment]
> It was not obvious to me why it appears that I was the only one having this issue. I know I had to use this patch a few times last year. But a new install from source today, didn't need this patch to install.

strange indeed, but if it works now (and it builds on every buildbot as well, so it seems to be something related to your setup) - then let's just close this?

**Comment by pmetzger** [comment]
Going to close this for now. I'm sorry about how long this took, @kurthindenburg. We try to be more expeditious about things.

**Pull request closed without merging**
