### PR TITLE
py-pyside2: update to 5.15.10; qt5-qtbase: apply workaround and security patches

### PR DESCRIPTION
**Pull request by chrstphrchvz**
###### Tested on

macOS 12.6.8
Xcode 14.2
Python 3.10.12

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
  Separated for clarity.
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
Only tested simplebrowser.py from py310-pyside2.
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
Is the CI failing just because of lack of time?

**Comment by chrstphrchvz** [comment]
> Is the CI failing just because of lack of time?

Yes, it takes several hours just to build Qt5 subports.

**Comment by chrstphrchvz** [comment]
I am wrong, this time the CI failed before running out of time. qt5-qtwebkit-examples failed during patch phase:

```
2023-08-14T14:23:01.3240980Z --->  Applying patch-qtwebkit-examples_header_location.diff
2023-08-14T14:23:01.3245310Z DEBUG: Creating patch directory: /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_aqua_qt5/qt5-qtwebkit-examples/work/qtwebkit-examples-everywhere-src-5.9.1
2023-08-14T14:23:01.3255240Z DEBUG: Environment: 
2023-08-14T14:23:01.3256010Z CC_PRINT_OPTIONS='YES'
2023-08-14T14:23:01.3257140Z CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_aqua_qt5/qt5-qtwebkit-examples/work/.CC_PRINT_OPTIONS'
2023-08-14T14:23:01.3257670Z CPATH='/opt/local/include'
2023-08-14T14:23:01.3258030Z DEVELOPER_DIR='/Library/Developer/CommandLineTools'
2023-08-14T14:23:01.3258520Z LIBRARY_PATH='/opt/local/lib'
2023-08-14T14:23:01.3259000Z MACOSX_DEPLOYMENT_TARGET='13.0'
2023-08-14T14:23:01.3259600Z SDKROOT='/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk'
2023-08-14T14:23:01.3265120Z Executing:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_aqua_qt5/qt5-qtwebkit-examples/work/qtwebkit-examples-everywhere-src-5.9.1" && /usr/bin/patch -p0 < '/Users/runner/work/macports-ports/macports-ports/ports/aqua/qt5/files/patch-qtwebkit-examples_header_location.diff'
2023-08-14T14:23:01.3267250Z DEBUG: system:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_aqua_qt5/qt5-qtwebkit-examples/work/qtwebkit-examples-everywhere-src-5.9.1" && /usr/bin/patch -p0 < '/Users/runner/work/macports-ports/macports-ports/ports/aqua/qt5/files/patch-qtwebkit-examples_header_location.diff'
2023-08-14T14:23:01.3499520Z File to patch: 
2023-08-14T14:23:01.3500280Z No file found--skip this patch? [y] 
2023-08-14T14:23:01.3500880Z 1 out of 1 hunks ignored--saving rejects to Oops.rej
2023-08-14T14:23:01.3501810Z File to patch: 
2023-08-14T14:23:01.3502150Z No file found--skip this patch? [y] 
2023-08-14T14:23:01.3502910Z 1 out of 1 hunks ignored--saving rejects to Oops.rej
2023-08-14T14:23:01.3504520Z File to patch: 
2023-08-14T14:23:01.3505990Z No file found--skip this patch? [y] 
2023-08-14T14:23:01.3506720Z 1 out of 1 hunks ignored--saving rejects to Oops.rej
2023-08-14T14:23:01.3510370Z File to patch: 
2023-08-14T14:23:01.3511230Z No file found--skip this patch? [y] 
2023-08-14T14:23:01.3512410Z 1 out of 1 hunks ignored--saving rejects to Oops.rej
2023-08-14T14:23:01.3514620Z File to patch: 
2023-08-14T14:23:01.3515640Z No file found--skip this patch? [y] 
2023-08-14T14:23:01.3517070Z 1 out of 1 hunks ignored--saving rejects to Oops.rej
2023-08-14T14:23:01.3527250Z Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_aqua_qt5/qt5-qtwebkit-examples/work/qtwebkit-examples-everywhere-src-5.9.1" && /usr/bin/patch -p0 < '/Users/runner/work/macports-ports/macports-ports/ports/aqua/qt5/files/patch-qtwebkit-examples_header_location.diff'
2023-08-14T14:23:01.3527980Z Exit code: 1
2023-08-14T14:23:01.3531500Z Error: Failed to patch qt5-qtwebkit-examples: command execution failed
```

**Comment by chrstphrchvz** [comment]
The only pyXX-pyside subport which the CI encountered an error when building (rather than timeout) was py310-pyside2 on macOS 12 which failed to install dependency `gpgme`.

**Comment by pmetzger** [comment]
Okay, so is this ready to merge now?

**Comment by chrstphrchvz** [comment]
> Okay, so is this ready to merge now?

I believe it is.

**Comment by pmetzger** [comment]
Thanks @chrstphrchvz!

**Pull request merged**
