### PR TITLE
libtapi: update to 1300.6.5-20231128

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [x] enhancement

###### Tested on

macOS 12.7.1 21G920 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
@catap It builds fine on PowerPC, but is installation of headers into `/opt/local/lib/tapi/1300-20231128.6-20231128.5-20231128/include` intended?

**Comment by catap** [comment]
@barracuda156 it installs headers into `/opt/local/include/tapi` and some additional headers into `/opt/local/lib/tapi/[version]/include` ;)


But thanks, I've moved timestamp to revision to avoid broke version.

**Comment by kencu** [comment]
revision is for macports to use for revbumps, etc.

it’s not for use for the port version info, and should not be 20231128

**Comment by catap** [comment]
Ken, fixed

**Pull request merged**
