### PR TITLE
emacs: update to 28.2

### PR DESCRIPTION
**Pull request by amake**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 12.6 21G115 arm64
Xcode 14.0 14A309

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Aaron, have you determined why CI is failing?

**Comment by amake** [comment]
No, to be honest CI seems to fail all the time for spurious reasons, so if it builds locally I don't really pay attention.

**Comment by mascguy** [comment]
> No, to be honest CI seems to fail all the time for spurious reasons, so if it builds locally I don't really pay attention.

Just checked, it looks like it's only the Devel subports that are failing. So no worries.

**Review by mascguy — APPROVED** [review]
LGTM. @drkp ?

**Pull request merged**
