### PR TITLE
scdoc: update to 1.11.1

### PR DESCRIPTION
**Pull request by herbygillot**
###### Tested on

macOS 10.15.7 19H15
Xcode 12.2 12B45b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -d install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
Looks like your changes to the patchfile reintroduce `-Werror`. We don't want `-Werror`; too often a new version of clang will come along with new warnings which old projects didn't know they were supposed to work around, and `-Werror` will turn those future warnings into errors that will prevent the port from building.

**Comment by herbygillot** [comment]
> Looks like your changes to the patchfile reintroduce `-Werror`. We don't want `-Werror`; too often a new version of clang will come along with new warnings which old projects didn't know they were supposed to work around, and `-Werror` will turn those future warnings into errors that will prevent the port from building.

Understood.  Fixed the patch.

**Comment by herbygillot** [comment]
Github Actions for macOS 11 are failing at the Homebrew setup stage... and the Github Actions build for mac 10.15 cancels early for some reason.

**Comment by ryandesign** [comment]
> Github Actions for macOS 11 are failing at the Homebrew setup stage

See https://github.com/macports/macports-ports/pull/9323#issuecomment-739686064

> and the Github Actions build for mac 10.15 cancels early for some reason.

That's new to me.

**Comment by ryandesign** [comment]
> - rename patch to conform to port-lint policy

Note that port lint policy has changed, and now any name ending with .diff or .patch is acceptable. See https://github.com/macports/macports-base/commit/5037999ebd06309ea216110d17befccc960266cf

**Pull request merged**
