### PR TITLE
repo: update to 2.32

### PR DESCRIPTION
**Pull request by armatys**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 13.2.1 22D68 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] ~~tried a full install with `sudo port -vst install`~~ tried a full install with `sudo port -vs install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by reneeotten — COMMENTED** [review]
it seems we don't explicitly depend on a Python port here - is that what we want to do? It assumes that for this to work the system should have Python 3.5+ installed, I don't think that's always the case on newer systems? I *think* newer macOS versions only have "python3" which wouldn't be used here - or?

In other words, should we just depend on MacPorts' default Python versions?

**Comment by armatys** [comment]
Yes, when I installed the `repo` on its own, and then tried to run it, it would complain: `env: python: No such file or directory`.
So it probably makes sense to depend on default Python version as well.

Would adding `python311` to `depends_run` be enough (or is there a way to use a default version, whatever that version might be)?

**Comment by ryandesign** [comment]
> Would adding `python311` to `depends_run` be enough

No. You would need to tell the build system (if there is one, or write a patch and/or reinplace if there is not) to use that specific version of python as well.

> (or is there a way to use a default version, whatever that version might be)?

There is not.

**Comment by herbygillot** [comment]
I've updated this Portfile to modify `repo` to use MacPort's `python311`. Should be good now.

**Pull request merged**
