### PR TITLE
openjdk8: fix for powerpc, improve the port generally

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

This is a huge PR, so I sorted everything per-commit, so that it is readable.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
I do not know whose `Support-arm64-and-fix-zero-assembler.diff` patch is, but looks like Sonoma fails on that:
```
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_java_openjdk8/openjdk8/work/jdk8u-jdk8u372-ga/hotspot/src/os_cpu/bsd_zero/vm/os_bsd_zero.cpp:384:8: error: conflicting types for '_Copy_conjoint_jshorts_atomic'
    void _Copy_conjoint_jshorts_atomic(const jshort* from, jshort* to, size_t count) {
         ^
```
It is applied without any modifications whatsoever, only name of the patch is changed to have consistent numbering.

**Comment by barracuda156** [comment]
Ok, failure on Sonoma is expected and has nothing to do with my PR. See:
https://trac.macports.org/ticket/69120
https://trac.macports.org/ticket/69583

So not a stopper.

**Comment by barracuda156** [comment]
@breun @Dave-Allured FYI

**Comment by barracuda156** [comment]
Confirmed to build on Leopard too.

**Comment by Dave-Allured** [comment]
> I do not know whose `Support-arm64-and-fix-zero-assembler.diff` patch is, but looks like Sonoma fails on that:
> 
> ```
>   /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_java_openjdk8/openjdk8/work/jdk8u-jdk8u372-ga/hotspot/src/os_cpu/bsd_zero/vm/os_bsd_zero.cpp:384:8: error: conflicting types for '_Copy_conjoint_jshorts_atomic'
>     void _Copy_conjoint_jshorts_atomic(const jshort* from, jshort* to, size_t count) {
>          ^
> ```
> 
> It is applied without any modifications whatsoever, only name of the patch is changed to have consistent numbering.

This patch adds the `const` qualifier to the `from` argument in six places IIRC.  This results in headers inconsistent with functions, which is caught by more recent clang versions.  `const` is unnecessary here, IMO.

Resolve these errors by removing those six `const` patch blocks, but keep the rest of the `support_arm64...` patch.  Then you will move on to the next Sonoma problem.

**Comment by Dave-Allured** [comment]
Openjdk8 is actively maintained upstream, including mac fixes.  I suggest patch against the latest version 8u412, rather than 8u372 which is a year old.  Also the next release is expected within the next couple weeks.

**Comment by barracuda156** [comment]
@Dave-Allured Thank you. As long as it is not something mechanical, I would prefer not touching Sonoma here.

I think we are clear on that my PR does not break anything for newer systems (to no surprise, nothing changes for them).

Let’s have PowerPC fixed, finally, and then someone else could deal with Sonoma breakages. I don’t have time for that and don’t need an old JDK on Sonoma, tbh.

**Comment by barracuda156** [comment]
> Openjdk8 is actively maintained upstream, including mac fixes.  I suggest patch against the latest version 8u412, rather than 8u372 which is a year old.  Also the next release is expected within the next couple weeks.

@Dave-Allured As you can see, I already have 8u412 locally. But I do not want to rebase other patches which are irrelevant for me.

This can be merged against 8u372, and for 8u412 one patch will need a small change, I take care of that.

**Comment by Dave-Allured** [comment]
@barracuda156 Okay, that sounds good.  Thanks for working on the fix for powerpc.

**Comment by pmetzger** [comment]
@breun Do you have an interest in this?

**Comment by barracuda156** [comment]
@pmetzger Realistically, no one else will maintain it for PowerPC (for the lack of hardware, if not for lack of time), so ppc part is on me. I can handle rebasing of all specific patches, no extra burden for others.

**Comment by breun** [comment]
> @breun Do you have an interest in this?

No, sorry, I don’t have a PowerPC machine and I can’t judge these patches. I’m not much of a C/C++ programmer.

**Comment by barracuda156** [comment]
@pmetzger @kencu Could someone merge this finally? Sonoma CI does not pass due to a broken arm64: it is not me breaking it. x86 CI pass.
_This port explicitly states support for powerpc_ – which was forever broken, had wrong settings and defunct destroot.

If a port maintainer is not interested to maintain ppc (which is fine, of course), add me as a maintainer. In any case it is not a reason to prevent fixing something.

I am not interested in Intel, should I refuse to accept fixes which someone else make for a port which I maintain? Let’s not make this ridiculous :)

**Comment by pmetzger** [comment]
So the problem is, I can't adequately review this, not even to the point of making sure it's actually harmless to other architectures.

**Comment by barracuda156** [comment]
@breun Could you do me a favor and confirm if this version of the port builds for you on Intel or arm and if changes look safe? Ignoring PowerPC-specific ones.

@pmetzger Well, CI pass for Intel, and for PowerPC we can’t possibly make it worse than it is currently, since existing version is completely broken, starting from wrong deployment target in the portfile and ending with a broken destroot.
Here original author of the main patches confirms that my version installs and works on Leopard: https://github.com/nilsvanvelzen/mac_ppc_openjdk8u60/issues/2#issuecomment-2225582024

**Comment by barracuda156** [comment]
P. S. @pmetzger Perry, I won’t really object if you and others prefer rather having a separate port for ppc. I do not think it is justified here, though it will be easier for me to maintain, since I can trash everything unnecessary and not worry about rebasing patches which I do not use, but I am fine with that. And while I think that my PR fixes minor issues for other archs as well, that is not my personal concern, I will be happy just to have ppc working – this or that way.

**Comment by pmetzger** [comment]
So it's a big advantage when there's a version of something just for PPC; I don't have to review it carefully because it won't break 99.9% of users, so if something goes wrong, it goes wrong for a very limited number of people, most of whom seem to be involved in maintaining the ports anyway.

**Comment by breun** [comment]
> @breun Could you do me a favor and confirm if this version of the port builds for you on Intel or arm and if changes look safe? Ignoring PowerPC-specific ones.

I only have access to an arm64 Mac (M1 Max) with macOS 14.5 and Xcode 15.4, but the build fails for me. See the attached log.

[main.log.gz](https://github.com/user-attachments/files/16404230/main.log.gz)

**Comment by barracuda156** [comment]
> > @breun Could you do me a favor and confirm if this version of the port builds for you on Intel or arm and if changes look safe? Ignoring PowerPC-specific ones.
> 
> 
> 
> I only have access to an arm64 Mac (M1 Max) with macOS 14.5 and Xcode 15.4, but the build fails for me. See the attached log.
> 
> 
> 
> [main.log.gz](https://github.com/user-attachments/files/16404230/main.log.gz)

Arm64 is broken at least by the patch which was in the port earlier. I tried that too.

**Comment by barracuda156** [comment]
> So it's a big advantage when there's a version of something just for PPC; I don't have to review it carefully because it won't break 99.9% of users, so if something goes wrong, it goes wrong for a very limited number of people, most of whom seem to be involved in maintaining the ports anyway.

Ok, no issues. I can make it a standalone `openjdk8-powerpc`.
Will sort it tomorrow, hopefully. Off from the workstation for today.

**Comment by breun** [comment]
> Arm64 is broken at least by the patch which was in the port earlier. I tried that too.

I just tried installing the current `openjdk8` port and it looks like that is indeed also already broken on arm64, which is confirmed by https://ports.macports.org/port/openjdk8/details/, so I guess we need someone who can test on Intel.

Upstream OpenJDK 8 also doesn't have any official arm64 support as far as I know by the way.

**Comment by barracuda156** [comment]
@breun (Well, I wouldn’t have broken arm64 on purpose, and for anything huge and important I run the build on Apple Silicon, unless it is a routine version update.)

But I have no idea who even needs JDK8 on arm64, tbh. No one is trying to fix gcc6 for arm64.

**Comment by breun** [comment]
I use JDK8 on arm64, but I typically use Azul Zulu OpenJDK (`openjdk8-zulu`), which installs a pre-built with arm64 support. There are some more OpenJDK-based distributions that do have arm64 support for Java 8 that we have ports for.

**Comment by barracuda156** [comment]
@breun @pmetzger Closing this one in favor of a separate port.

**Pull request closed without merging**
