### PR TITLE
tesseract*: update version 3.05.02/3.04.00->4.0.0

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.3
Xcode 10.1 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by markemer** [comment]
Hey, nice work, can you squash these into one and make a commit message according to this: [Commit Message Guildlines](https://trac.macports.org/wiki/CommitMessages)

**Comment by MarcusCalhoun-Lopez** [comment]
I would humbly suggest that this is one of the cases where we do **not** want to squash the changes.
Each commit has a distinct motivation.
Each commit leaves the Portfile in a valid state.

See https://github.com/macports/macports-ports/pull/2599#issuecomment-422447892 and https://github.com/macports/macports-ports/pull/2347#issuecomment-411236672 for similar reasoning.

As the maintainer, if you feel the changes should be merged, I am happy to do it.
Are the changes themselves satisfactory?

**Comment by markemer** [comment]
If the multiple commits are cool, which it looks like they are, I'm happy.

**Comment by mojca** [comment]
We only want to avoid multiple commits when new commits fix mistakes from earlier commits. Then doing a bisection to find some issue could cause problems. If commits are nicely split into logical and valid units, this is fine.

**Pull request merged**
