### PR TITLE
cl-split-sequence, cl-nclasses, cl-nkeymaps, cl-iterate: add missed dependency

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [x] bugfix

###### Tested on

macOS 12.6.8 21G725 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?

### CODE REVIEW

**Comment by catap** [comment]
@mascguy, @herbygillot, @reneeotten may I ask you to merge one more cleanup of dependency of lisp ports. This is fixing of an issues which was introduced as side effect of mass creating of this ports :)

**Review by mascguy — APPROVED** [review]
LGTM. But we need approval from the maintainer of `cl-iterate`. @mohd-akram ?

**Comment by catap** [comment]
@mascguy yeah, I'm adding CCL and ABCL into common_lisp PG as default lisp to "compile" and test all ports, and simple testing everything.

=> I need some time to sort things out. majority is  done  and I've discovered a few missed things like this one.

But it quite time consuming process and I may wait @mohd-akram ;)

**Comment by mohd-akram** [comment]
LGTM. You can remove me as maintainer as well tbh. I added this port for nyxt, but didn't continue. I saw that you added it recently which is fantastic.

**Comment by catap** [comment]
@mohd-akram I glad to read that I'm not only user of nyxt here. Ok, you're removed.

**Pull request merged**
