### PR TITLE
R: updates for packages (1)

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Updates

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
@barracuda156 this fails everywhere

**Comment by barracuda156** [comment]
> @barracuda156 this fails everywhere

Some silly stuff going on on CI. Initially macOS 12 and 13 passed, 14 failed without any reasonable message. After a simple rebase to master (no changes to PR itself), only macOS 13 passed.

**Comment by barracuda156** [comment]
Since there is nothing to fix, problem is on CI side (at least nothing suggests otherwise), I can only try rebasing to master over again.

**Comment by barracuda156** [comment]
```
  ** byte-compile and prepare package for lazy loading
  Error in dyn.load(file, DLLpath = DLLpath, ...) : 
    unable to load shared object '/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/qgraph/libs/qgraph.so':
    dlopen(/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/qgraph/libs/qgraph.so, 0x0006): Library not loaded: '@rpath/libc++.1.dylib'
    Referenced from: '/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/qgraph/libs/qgraph.so'
    Reason: tried: '/opt/local/lib/libgcc/libc++.1.dylib' (no such file), '/opt/local/libexec/llvm-16/lib/libc++.1.dylib' (no such file), '/opt/local/lib/libgcc/libc++.1.dylib' (no such file), '/opt/local/libexec/llvm-16/lib/libc++.1.dylib' (no such file), '/opt/local/lib/libgcc/libc++.1.dylib' (no such file), '/opt/local/libexec/llvm-16/lib/libc++.1.dylib' (no such file), '/opt/local/lib/libgcc/libc++.1.dylib' (no such file), '/opt/local/libexec/llvm-16/lib/libc++.1.dylib' (no such file), '/opt/local/Library/Frameworks/R.framework/Resources/lib/libc++.1.dylib' (no such file), '/opt/lo
  Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
  Execution halted
  ERROR: lazy loading failed for package ‘bnmonitor’
```
Another old port happened to be broken with clangs. Let’s see if revbumping that fixes CIs.

**Comment by barracuda156** [comment]
@reneeotten Do you know if there were any changes to CI setup since yesterday?

How things randomly succeed or fail is weird.

image

**Comment by barracuda156** [comment]
@reneeotten Well, I can’t do anything about the broken Xcode 16 and that GH decided to force it upon Sonoma users.

It can either be merged, since other CI pass, or just closed.

**Comment by reneeotten** [comment]
as @jmroot responded to your e-mail about this topic: this will be a combination that end-users might have as well. So that should work for them and thus on the CI as well.

**Comment by barracuda156** [comment]
> as @jmroot responded to your e-mail about this topic: this will be a combination that end-users might have as well. So that should work for them and thus on the CI as well. 

I am open to suggestions, but I am not gonna hack gcc to compile with the defunct Xcode version :) I got neither time nor motivation to do that.
Probably users should be notified to avoid Xcode 16 on Sonoma until Apple fixes it.

**Comment by jmroot** [comment]
> I am open to suggestions, but I am not gonna hack gcc to compile with the defunct Xcode version :) I got neither time nor motivation to do that. Probably users should be notified to avoid Xcode 16 on Sonoma until Apple fixes it.

Good luck with that. The assembler change is unlikely to be reverted. Instead of trying to hold back the tide, you could backport the fix from gcc14 to the older gcc ports.

**Comment by barracuda156** [comment]
> Good luck with that. The assembler change is unlikely to be reverted. Instead of trying to hold back the tide, you could backport the fix from gcc14 to the older gcc ports.

The only thing what I can suggest is switching R to gcc14, whether generally or specifically for macOS using a broken Xcode. Or stop updating R ports, if you wish.

**Comment by barracuda156** [comment]
@jmroot @reneeotten @herbygillot Turned out, buildbots are not affected (since apparently they use the working Xcode on Sonoma still), so CI error on Sonoma can be ignored for now, it is only on CI. Everything should build fine on buildbots.

Example from yesterday: https://build.macports.org/builders/ports-14_arm64-builder/builds/42907/steps/install-port/logs/stdio

**Comment by markemer** [comment]
> @jmroot @reneeotten @herbygillot Turned out, buildbots are not affected (since apparently they use the working Xcode on Sonoma still), so CI error on Sonoma can be ignored for now, it is only on CI. Everything should build fine on buildbots.
> 
> Example from yesterday: https://build.macports.org/builders/ports-14_arm64-builder/builds/42907/steps/install-port/logs/stdio

clang 16 and 17 should be working on macOS 15/Xcode 16 so R should build.

**Comment by barracuda156** [comment]
It needs gcc13 for Fortran too.

**Comment by markemer** [comment]
> It needs gcc13 for Fortran too.

Yeah, I just realized that. gcc14 fortran is working but 13 is still busted - it tried to install g95.

**Comment by barracuda156** [comment]
@markemer There is nothing in principle to prevent from switching to gcc14, but that will require a revbump to a lot of ports. It will probably break some due to being stricter on warnings vs errors, which would not be a big deal, if I was let peacefully to fix those, but that is often not the case either.

**Pull request merged**
