### PR TITLE
pdfbox: update url to legitimate homepage

### PR DESCRIPTION
**Pull request by jbclements**
###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by herbygillot** [comment]
Hey @jbclements, thanks for this submission.  MacPorts has a desired format for the git commit message: `<port name>: <description of update>`

So in this case, the commit message should look something like:

`pdfbox: update to homepage legitimate URL` ....or something similar.

You are welcome to write extra details underneath starting from the 3rd line onwards, but that's the general format that is preferred.  If you could amend the message on this commit, this should be good to merge.

**Comment by jbclements** [comment]
Thanks for your message, apologies for not reading the guidelines carefully enough! title updated to requested.

**Comment by herbygillot** [comment]
> Thanks for your message, apologies for not reading the guidelines carefully enough! title updated to requested.

Sorry, I wasn't clear enough.

I am not referring to the title of the pull request, but the message for this pull request's commit.

You have a single commit that changes the homepage URL, but it is the description on the commit itself that needs to be changed.

**Comment by jbclements** [comment]
Ouch! Not your fault, you were 100% clear, I'm being lazy. commit amended and pushed, many thanks for your patience!

**Comment by herbygillot** [comment]
Merged and thank you for your submission, @jbclements.

**Pull request merged**
