### PR TITLE
tig: add missing dependencies

### PR DESCRIPTION
**Pull request by exg**

### CODE REVIEW

**Review by reneeotten — COMMENTED** [review]
according to the [status website](https://ports.macports.org/port/tig/details/) this port is building everywhere. Why are these dependencies now required?

So it seems (1) this will not just fix a build failure and (2) you are adding ports to depends_lib and thus it would require to increase the "revision".

**Comment by exg** [comment]
> according to the [status website](https://ports.macports.org/port/tig/details/) this port is building everywhere. Why are these dependencies now required?

They are optional dependencies, so adding them fixes opportunistic linking. The latest build for macOS 12 depends on both.

> So it seems (1) this will not just fix a build failure and (2) you are adding ports to depends_lib and thus it would require to increase the "revision".

Yes, a revision bump is missing. Alternatively, I can introduce variants but it seems overkill.

**Comment by reneeotten** [comment]
the alternative would be to make sure not to use the dependencies even if they are installed. But I agree that opportunistic linking should be avoided/resolved. I'll leave it to @cal to decide which of the options to use.

**Review by neverpanic — APPROVED** [review]
pcre2 is a dependency of git already, but since we're depending on `bin:git:git`, I guess it makes sense to add that.

The same applies for readline, which is a dependency through git -> perl -> gdbm -> readline, and will thus always be present unless you're using system git.

**Pull request merged**
