### PR TITLE
hugo: update to 0.93.0

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -d install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
@cardi - I think it would make sense to have Bash completion & tags support be built-in by default instead of optional variants.  Thoughts?

**Comment by herbygillot** [comment]
> I agree. I think that'd be useful, and wouldn't impose an undue overhead for those that don't use those features.
> 
> There is also an existing ticket to update how bash completion is generated: https://trac.macports.org/ticket/64735 that I was building a patch for.
> 
> Would you prefer to have hugo be updated to 0.93.0 first before moving the variants to default in another PR, or should we fold all of those changes into this PR?

I don't have a strong preference either way, but I suppose it probably makes more sense to just fix everything in one PR.

I (_think_) when we remove the variant (because we're consolidating the feature into the main build), whoever who currently has `hugo` installed with the variant enabled might run into an error state (I _think_).  So we will have to mention this in the port notes.

**Comment by cardi** [comment]
I've attached a patch based off of this PR that:
- updates hugo to 0.93.1
- builds and installs bash completions and extended support by default
- removes the `+bash_completion` and `+extended` variants

I've verified the install works with `sudo port -vst install`, and the bash completion scripts are generated and installed properly.

Patch: [0001-hugo-update-to-0.93.1.patch.txt](https://github.com/macports/macports-ports/files/8174174/0001-hugo-update-to-0.93.1.patch.txt)

I think all you'd have to do on your branch is apply the patch and squash the commits (feel free to use or modify my commit message):
```shell
curl -LO https://github.com/macports/macports-ports/files/8174174/0001-hugo-update-to-0.93.1.patch.txt
git am 0001-hugo-update-to-0.93.1.patch.txt
git rebase -i HEAD~2
```

> I (think) when we remove the variant (because we're consolidating the feature into the main build), whoever who currently has hugo installed with the variant enabled might run into an error state (I think). So we will have to mention this in the port notes

I installed this on my own setup with hugo and didn't run into any issues. (I think `port` ignores any variant that doesn't exist, e.g., `sudo port install hugo +foobar` where `foobar` doesn't exist.)

**Comment by pmetzger** [comment]
I think the general consensus for almost a year or two has been to include completion files by default since they are so small compared to the rest of a package, so I agree that should happen.

**Comment by cardi** [comment]
LGTM. Thank you, @herbygillot!

**Comment by herbygillot** [comment]
Thank you @cardi, and also agreed, @pmetzger.

**Pull request merged**
