### PR TITLE
yaz and friends: update to current versions

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Updates

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Opened an issue for the `yazproxy` error: https://github.com/indexdata/yazproxy/issues/21
Everything else builds fine.

**Comment by pmetzger** [comment]
How do we get progress on this?

**Comment by barracuda156** [comment]
We could drop `yazproxy` from the PR? Perhaps it doesn’t build anyway.
It is 3 AM here, I can check tomorrow. If it is already broken, IMO just update the rest.

**Comment by ryandesign** [comment]
> Opened an issue for the `yazproxy` error: [indexdata/yazproxy#21](https://github.com/indexdata/yazproxy/issues/21)

@barracuda156 I fixed the yazproxy issue in ed7fe96f5cd81f59e1fa1714bf2da078a0b24a5b. Do you want to rebase your changes in this PR onto the current master and reopen this PR?

**Pull request closed without merging**
