### PR TITLE
totp-cli:  Update dependencies

### PR DESCRIPTION
**Pull request by RobK88**
totp-cli:  Update dependencies

* Bump revision number
* Update go dependencies to latest versions

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [x] security fix

###### Tested on

macOS 10.13.6 17G14042 x86_64
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by RobK88** [comment]
P.S.  I am curious.  Why is this new line needed in the Portfile:

```
build.args-append   \
    -ldflags \"-X ${go.package}/internal/info.Version=${github.tag_prefix}${version}\"
```

**Comment by herbygillot** [comment]
> P.S.  I am curious.  Why is this new line needed in the Portfile:
> 
> ```
> build.args-append   \
>     -ldflags \"-X ${go.package}/internal/info.Version=${github.tag_prefix}${version}\"
> ```

It's meant to set the version in code. That's what gets displayed when you do `<command> -v` or `<command> version`.

**Comment by RobK88** [comment]
Thanks for the explanation.

I see that without that line in the Portfile, `totp-cli --version` displays `totp-cli version dev`.

But with the line in the Portfile, `totp-cli --version` displays `totp-cli version v1.8.7`

**Comment by herbygillot** [comment]
> Thanks for the explanation.
> 
> I see that without that line in the Portfile, `totp-cli --version` displays `totp-cli version dev`.
> 
> But with the line in the Portfile, `totp-cli --version` displays `totp-cli version v1.8.7`

Yes.  The `-X` build `ldflag` allows you to set a specific value for a given variable at build time.

The default value for the `Version` variable in the `./internal/info` package is `dev`, but we set it to the current version via `-ldflags " -X ... "`.

**Comment by RobK88** [comment]
Thanks!  I learned something new today!

**Comment by herbygillot** [comment]
Np.

So I think for this PR, this change counts as a fix for a stealth update:

https://trac.macports.org/wiki/PortfileRecipes#stealth-updates

Even if we increase the revision, MacPorts users and mirrors who have already downloaded these distfiles will now see a checksum mismatch.

The revision update applies only to the distfile for the main project itself (`totp-cli`), but not for the dependency Go module archives whose checksums have changed.

So we'll have to try setting `dist_subdir` as per the linked stealth update section above.

**Comment by herbygillot** [comment]
Actually I was mistaken - since the version numbers are changing on the Go module archives, this is not a stealth update situation, and this PR looks fine to merge.

Thank you @RobK88

**Pull request merged**
