### PR TITLE
R: revbump ICU dependents to unbreak them; update a few packages

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Revbumping R packages depending on ICU/libxml2 was forgotten during a recent update of ICU. In result, they broke down.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mascguy** [comment]
Hey Sergey, these ports weren't missed with the `icu` update. Rather, they don't declare a dependency on `icu`, but they need to.

Please add the following to your lib deps: `path:lib/pkgconfig/icu-uc.pc:icu`

CC: @catap

**Comment by barracuda156** [comment]
> Hey Sergey, these ports weren't missed with the `icu` update. Rather, they don't declare a dependency on `icu`, but they need to.
> 
> Please add the following to your lib deps: `path:lib/pkgconfig/icu-uc.pc:icu`
> 
> CC: @catap

Aside of `R-stringi`, which links to ICU when it is available (so it was not obvious indeed), other depend on `libxml2` or `harfbuzz-icu`, which pull in dependency on ICU. Or dependency is not transitive in this case? )

**Comment by mascguy** [comment]
> > Hey Sergey, these ports weren't missed with the `icu` update. Rather, they don't declare a dependency on `icu`, but they need to.
> > Please add the following to your lib deps: `path:lib/pkgconfig/icu-uc.pc:icu`
> 
> Aside of `R-stringi`, which links to ICU when it is available (so it was not obvious indeed), other depend on `libxml2` or `harfbuzz-icu`, which pull in dependency on ICU. Or dependency is not transitive in this case?

If they're transitive, then they shouldn't be directly linked to `icu`. In which case, they shouldn't be broken.

Can you run `otool -L <bin>` for the various binaries/libs, to see whether they are linked to it?

**Comment by barracuda156** [comment]
@mascguy They certainly do link to ICU components via `libxml2` (in case of `R-Cairo` via `harfbuzz-icu`):
```
macmini:bmake svacchanda$ otool -L /opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/stringi/libs/stringi.so
/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/stringi/libs/stringi.so:
	stringi.so (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libMacportsLegacySupport.dylib (compatibility version 1.0.0, current version 1.0.99)
	/opt/local/lib/libicui18n.73.dylib (compatibility version 73.0.0, current version 73.1.0)
	/opt/local/lib/libicuuc.73.dylib (compatibility version 73.0.0, current version 73.1.0)
	/opt/local/lib/libicudata.73.dylib (compatibility version 73.0.0, current version 73.1.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 550.44.0)
	/opt/local/lib/libgcc/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.30.0)
	/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/lib/libR.dylib (compatibility version 4.3.0, current version 4.3.0)
	/opt/local/lib/libgcc/libgcc_s.1.1.dylib (compatibility version 1.0.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)
macmini:bmake svacchanda$ otool -L /opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/Cairo/libs/Cairo.so
/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/Cairo/libs/Cairo.so:
	Cairo.so (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libMacportsLegacySupport.dylib (compatibility version 1.0.0, current version 1.0.99)
	/opt/local/lib/libfreetype.6.dylib (compatibility version 25.0.0, current version 25.3.0)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.13)
	/opt/local/lib/libpng16.16.dylib (compatibility version 56.0.0, current version 56.0.0)
	/opt/local/lib/libcairo.2.dylib (compatibility version 11709.0.0, current version 11709.0.0)
	/opt/local/lib/libXext.6.dylib (compatibility version 11.0.0, current version 11.0.0)
	/opt/local/lib/libXrender.1.dylib (compatibility version 5.0.0, current version 5.0.0)
	/opt/local/lib/libX11.6.dylib (compatibility version 11.0.0, current version 11.0.0)
	/opt/local/lib/libjpeg.8.dylib (compatibility version 8.0.0, current version 8.2.2)
	/opt/local/lib/libharfbuzz-icu.0.dylib (compatibility version 60001.0.0, current version 60001.0.0)
	/opt/local/lib/libharfbuzz.0.dylib (compatibility version 60001.0.0, current version 60001.0.0)
	/opt/local/lib/libicuuc.72.dylib (compatibility version 72.0.0, current version 72.1.0)
	/opt/local/lib/libicudata.72.dylib (compatibility version 72.0.0, current version 72.1.0)
	/opt/local/lib/libgcc/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.30.0)
	/opt/local/lib/libtiff.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 550.44.0)
	/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/lib/libR.dylib (compatibility version 4.3.0, current version 4.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)
macmini:bmake svacchanda$ otool -L /opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/XML/libs/XML.so
/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/XML/libs/XML.so:
	XML.so (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libMacportsLegacySupport.dylib (compatibility version 1.0.0, current version 1.0.99)
	/opt/local/lib/libxml2.2.dylib (compatibility version 13.0.0, current version 13.4.0)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.13)
	/opt/local/lib/liblzma.5.dylib (compatibility version 10.0.0, current version 10.2.0)
	/opt/local/lib/libiconv.2.dylib (compatibility version 9.0.0, current version 9.1.0)
	/opt/local/lib/libicui18n.73.dylib (compatibility version 73.0.0, current version 73.1.0)
	/opt/local/lib/libicuuc.73.dylib (compatibility version 73.0.0, current version 73.1.0)
	/opt/local/lib/libicudata.73.dylib (compatibility version 73.0.0, current version 73.1.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 550.44.0)
	/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/lib/libR.dylib (compatibility version 4.3.0, current version 4.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)
macmini:bmake svacchanda$ otool -L /opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/xml2/libs/xml2.so
/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/xml2/libs/xml2.so:
	xml2.so (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libMacportsLegacySupport.dylib (compatibility version 1.0.0, current version 1.0.99)
	/opt/local/lib/libxml2.2.dylib (compatibility version 13.0.0, current version 13.4.0)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.13)
	/opt/local/lib/liblzma.5.dylib (compatibility version 10.0.0, current version 10.2.0)
	/opt/local/lib/libiconv.2.dylib (compatibility version 9.0.0, current version 9.1.0)
	/opt/local/lib/libicui18n.73.dylib (compatibility version 73.0.0, current version 73.1.0)
	/opt/local/lib/libicuuc.73.dylib (compatibility version 73.0.0, current version 73.1.0)
	/opt/local/lib/libicudata.73.dylib (compatibility version 73.0.0, current version 73.1.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 550.44.0)
	/opt/local/lib/libgcc/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.30.0)
	/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/lib/libR.dylib (compatibility version 4.3.0, current version 4.3.0)
	/opt/local/lib/libgcc/libgcc_s.1.1.dylib (compatibility version 1.0.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)
macmini:bmake svacchanda$ otool -L /opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/igraph/libs/igraph.so
/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/igraph/libs/igraph.so:
	igraph.so (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libMacportsLegacySupport.dylib (compatibility version 1.0.0, current version 1.0.99)
	/opt/local/lib/libxml2.2.dylib (compatibility version 13.0.0, current version 13.4.0)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.13)
	/opt/local/lib/liblzma.5.dylib (compatibility version 10.0.0, current version 10.2.0)
	/opt/local/lib/libiconv.2.dylib (compatibility version 9.0.0, current version 9.1.0)
	/opt/local/lib/libicui18n.73.dylib (compatibility version 73.0.0, current version 73.1.0)
	/opt/local/lib/libicuuc.73.dylib (compatibility version 73.0.0, current version 73.1.0)
	/opt/local/lib/libicudata.73.dylib (compatibility version 73.0.0, current version 73.1.0)
	/opt/local/lib/libgmp.10.dylib (compatibility version 15.0.0, current version 15.1.0)
	/opt/local/lib/libglpk.40.dylib (compatibility version 44.0.0, current version 44.1.0)
	/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/lib/libRlapack.dylib (compatibility version 4.3.0, current version 4.3.0)
	/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/lib/libRblas.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libgcc/libgfortran.5.dylib (compatibility version 6.0.0, current version 6.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 550.44.0)
	/opt/local/lib/libgcc/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.30.0)
	/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/lib/libR.dylib (compatibility version 4.3.0, current version 4.3.0)
	/opt/local/lib/libgcc/libgcc_s.1.1.dylib (compatibility version 1.0.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)
```

**Comment by barracuda156** [comment]
@mascguy As an example, `R-xml2` – no declaration of a direct dependency on ICU, only on `libxml2`:

CRAN: https://cran.r-project.org/web/packages/xml2/index.html
Upstream: https://github.com/r-lib/xml2/blob/53575f0156e8713d195be33848b18b231399f4d3/DESCRIPTION#L36

I was having an impression from existing ports that lib dependencies are transitive. In many cases linking command calls a large number of dylibs, but only an umbrella port is declared as a dependency. (This may be a wrong practice though, that I am not sure about.)

**Comment by mascguy** [comment]
> @mascguy As an example, `R-xml2` – no declaration of a direct dependency on ICU, only on `libxml2`:
> 
> CRAN: https://cran.r-project.org/web/packages/xml2/index.html Upstream: https://github.com/r-lib/xml2/blob/53575f0156e8713d195be33848b18b231399f4d3/DESCRIPTION#L36
> 
> I was having an impression from existing ports that lib dependencies are transitive. In many cases linking command calls a large number of dylibs, but only an umbrella port is declared as a dependency. (This may be a wrong practice though, that I am not sure about.)

If you look at the `pkgconfig` file for `libxml2` (`${prefix}/lib/pkgconfig/libxml-2.0.pc`), you'll see that `icu` and other libs are declared private. So that shouldn't cause dependents to directly link with it:

```
Requires:
Libs: -L${libdir} -lxml2
Libs.private: -L/opt/local/lib -lz -L/opt/local/lib -llzma -lpthread  -liconv -L/opt/local/lib -licui18n -licuuc -licudata   
```

So if your `R` packages are linking to `icu`, then perhaps it's intended? Or it's coming from elsewhere, though I don't see where...

**Comment by barracuda156** [comment]
@mascguy Well, for sure I did not explicitly pass extra flags to link them with ICU. In most cases `R` packages “just work”.

So what do you recommend in this instance? Add a direct dep on ICU for these?

**Comment by mascguy** [comment]
> @mascguy Well, for sure I did not explicitly pass extra flags to link them with ICU. (In most cases `R` packages “just work”. Unless something is clearly broken (build or tests, if available), I do not tweak configure and Makevars.)
> 
> So what do you recommend in this instance? Add a direct dep on ICU for these?

Yes, if they're indeed linking to `icu`, then add a lib dep.

**Comment by mascguy** [comment]
> > @mascguy Well, for sure I did not explicitly pass extra flags to link them with ICU. (In most cases `R` packages “just work”. Unless something is clearly broken (build or tests, if available), I do not tweak configure and Makevars.)
> > So what do you recommend in this instance? Add a direct dep on ICU for these?
> 
> Yes, if they're indeed linking to `icu`, then add a lib dep.

Though we should probably take a look, and determine why it's occurring. Because if it's not expected - or perhaps not supposed to be happening - then it would be preferable to fix that, rather than adding `icu` deps to too many of these.

**Comment by barracuda156** [comment]
@mascguy Nothing in configure or Makevars seems to pass flags to ICU: https://github.com/r-lib/xml2/blob/main/configure
https://github.com/r-lib/xml2/blob/main/src/Makevars.in

Apparently it is our `libxml2` and/or `pkgconfig` adding those.

There are not many ports of this kind – in fact, very few. I have no seen ICU coming out of the blue – it is always its dependents that pull it in, and very few `R` packages depend on `libxml2` (I searched through the whole R directory before making this PR).

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
The Monterey CI job has been running for just over 3 hours, presumably due to issues building `gcc12`/`libgcc12` there. But the Big Sur and Ventura jobs completed successfully, so that's sufficient. Merging.

**Comment by barracuda156** [comment]
@mascguy Thank you!

**Comment by catap** [comment]
I feel a dejavu because I've added to some port dependency to ICU which I've discovered by rev-upgrade, which was introduced by libxml.

**Comment by barracuda156** [comment]
> I feel a dejavu because I've added to some port dependency to ICU which I've discovered by rev-upgrade, which was introduced by libxml.

Ok, so R is not to blame. Any idea why this happens?

**Comment by catap** [comment]
> Ok, so R is not to blame. Any idea why this happens?

I hove no idea :(

**Pull request merged**
