### PR TITLE
Update httpie, use Python 3.7

### PR DESCRIPTION
**Pull request by lbschenkel**
As discussed on https://github.com/macports/macports-ports/pull/3845#issuecomment-472067142, now that the original PR has been merged I have updated `httpie` to the latest version and bumped Python to 3.7.

@g5pw

### CODE REVIEW

**Comment by mf2k** [comment]
It look like another (sub-)port needs to be added. 

`Error: Dependency 'py37-parsimonious' not found.
`

**Comment by lbschenkel** [comment]
Damn. Reminder that I shouldn't be submitting PRs just before going to sleep. To my defense, although I should have caught this locally I was counting on Travis to catch any issues. Will keep that in mind for next time.

I have pushed a new commit which introduces the subport.

**Comment by g5pw** [comment]
Ah, I was sure I already pushed that! apparently not :/ thanks, @lbschenkel ! Looks good to me.

**Comment by lbschenkel** [comment]
How can I repeat the Travis build? It looks like the failure was due to a transient network error on 10.2:
```
--->  Fetching distfiles for py37-prompt_toolkit
DEBUG: elevating privileges for fetch: euid changed to 0, egid changed to 0.
DEBUG: dropping privileges: euid changed to 502, egid changed to 501.
DEBUG: Executing org.macports.fetch (py37-prompt_toolkit)
--->  prompt_toolkit-2.0.9.tar.gz does not exist in /opt/local/var/macports/distfiles/py-prompt_toolkit
--->  Attempting to fetch prompt_toolkit-2.0.9.tar.gz from https://distfiles.macports.org/py-prompt_toolkit
DEBUG: Fetching distfile failed: Could not resolve host: distfiles.macports.org
--->  Attempting to fetch prompt_toolkit-2.0.9.tar.gz from https://mirrors.shu.edu.cn/macports/distfiles/py-prompt_toolkit
DEBUG: Fetching distfile failed: Could not resolve host: mirrors.shu.edu.cn
--->  Attempting to fetch prompt_toolkit-2.0.9.tar.gz from https://files.pythonhosted.org/packages/source/p/prompt_toolkit
DEBUG: Fetching distfile failed: Could not resolve host: files.pythonhosted.org
Error: Failed to fetch py37-prompt_toolkit: Could not resolve host: files.pythonhosted.org
DEBUG: Error code: NONE
DEBUG: Backtrace: Could not resolve host: files.pythonhosted.org
    while executing
"error $lastError"
    (procedure "portfetch::fetchfiles" line 62)
    invoked from within
"portfetch::fetchfiles"
    (procedure "portfetch::fetch_main" line 17)
    invoked from within
"$procedure $targetname"
```

**Comment by lbschenkel** [comment]
OK, merged.

**Pull request merged**
