### PR TITLE
py-xraylarch: add Python3.10 variant

### PR DESCRIPTION
**Pull request by joefowler**
Adds Python3.10 variant to larch and 11 of its dependencies.

###### Type(s)

- [x] enhancement

###### Tested on
macOS 11.6.2 20G314 x86_64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
thanks for the PR @joefowler ! 

It seems that there are still missing dependencies:
```
Error: Unknown dependency: py310-fabio
Error: Unknown dependency: py310-wxpython-4.0
```
Also, when adding new subports for newer Python versions ideally one should make sure that upstream claims to support this and/or it passes the test-suite. How much of this was checked - also it's kind of impossible that this build for you locally even though you check this off in the PR checklist?

**Comment by pmetzger** [comment]
It might be that he built the other dependencies but forgot to include them in the pull request.

**Comment by pmetzger** [comment]
@joefowler ?

**Comment by joefowler** [comment]
Hey, sorry for losing track of this. Hmm. I must have tested this commit in parts or on a system with some non-port packages installed? I think I should withdraw this for now....

**Comment by pmetzger** [comment]
Feel free to close it or fix it as you prefer.

**Comment by joefowler** [comment]
Withdrawing until I have time to test and research ports' upstream support more fully.

**Pull request closed without merging**
