### PR TITLE
cgal: update version 4.11->4.12

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.13
Xcode 9.4

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. I would ignore the fact that technically @Veence has to approve given that he has not actually commented on pull requests on his ports in a very long time. (We should probably file a Port Abandoned trac ticket for his stuff.)

**Comment by Veence** [comment]
I’m just not used to this interface. GIT remains for me mostly a mystery, to be honest. Thanks for merging.

**Comment by pmetzger** [comment]
@Veence We are happy to tutor you through using Git. It's annoying but not difficult.

**Comment by Veence** [comment]
I think it wouldn’t be squandered time. When I try to grasp the intricacies of GIT, I felt dimwitted :P

**Comment by pmetzger** [comment]
It's not really hard. The UI is just confusing. Try starting by reading the section of Pro Git explaining the internals (chapter 10): https://git-scm.com/book/en/v2 and it may make a lot more sense afterwards because you'll know what it is that you're doing under the covers.

**Pull request merged**
