### PR TITLE
zabbix42: New(-ish) port.

### PR DESCRIPTION
**Pull request by eborisch**
Maintainer "update" of zabbix4 to zabbix42.

zabbix 4.0 is a LTS branch, so I intend to keep it around at least until the next LTS.

4.2 is the current latest release. Very minor (99% just s/zabbix4/zabbix42/g) changes from previous Portfile. I also plan to start obsoleting old versions (zabbix/zabbix2/zabbix3) in the near future. Not sure if anyone else out there is using them via MP, but just FYI...

### CODE REVIEW

**Comment by eborisch** [comment]
I also removed some of the older database support variants. Debating just removing the runtime dependency variant completely and just adding "install a database matching the interface you have selected on the server of your choice."

**Comment by mf2k** [comment]
Given that changes from the zabbix portfile are minor, I would strongly prefer that you simply make this a sub-port of zabbix.

**Comment by eborisch** [comment]
> Given that changes from the zabbix portfile are minor, I would strongly prefer that you simply make this a sub-port of zabbix.

Working on this....

**Comment by mf2k** [comment]
Wow that looks great! My one request is to modify the commit message to be something like this:

`zabbix4: Add sub-ports for zabbix42, ...`

**Pull request merged**
