### PR TITLE
bazel cleanup

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

Removes useless code from the bazel portfile.

### CODE REVIEW

**Comment by kencu** [comment]
now if we could make that completion thing 
```
# Build the bash completion script
    system -W ${worksrcpath} "./${name} build //scripts:${name}-complete.bash"
```
an option, this port might build in less than 6 hours.

**Comment by ryandesign** [comment]
> now if we could make that completion thing an option

Not related to this PR.

**Comment by pmetzger** [comment]
> > now if we could make that completion thing an option

> Not related to this PR.

It does make it harder to use the CI system though.

**Comment by pmetzger** [comment]
Merged. Thank you, @ryandesign.

Perhaps @kencu would now like to fix the bash completion thing?

**Pull request merged**
