### PR TITLE
mpich: update to 4.1.2

### PR DESCRIPTION
**Pull request by catap**
#### Description

Additional:
 - add myself as co-maintainer
 - add gcc13 and clang17 subport

See: https://github.com/pmodels/mpich/issues/6684

Closes: https://trac.macports.org/ticket/68296
Closes: https://trac.macports.org/ticket/68346
Closes: https://trac.macports.org/ticket/68632
Closes: https://trac.macports.org/ticket/68653

###### Type(s)

- [x] bugfix
- [x] enhancement

###### Tested on

macOS 12.6.8 21G725 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@catap Could we finally also enable Fortran 2008, which is required for some ports?
```
--enable-f08
```
https://trac.macports.org/ticket/67724

P. S. Ideally, we would also want `mpich-default` with `gcc` on PowerPC, and then we do not need an ugly per-port hacks.

**Comment by mascguy** [comment]
Kirill, there's already an open PR, for updating `mpich`.

Also note that I'm not in a hurry to push updates to `openmpi` and `mpich`, as they'll each time up the build bots for several days.

So I'd prefer to handle updates to these. And that needs to wait until I can find time to thoroughly test across macOS releases.

Does that make sense?

**Comment by mascguy** [comment]
> @catap Could we finally also enable Fortran 2008, which is required for some ports?
> ```
> --enable-f08
> ```
> https://trac.macports.org/ticket/67724
> 
> P. S. Ideally, we would also want `mpich-default` with `gcc` on PowerPC, and then we do not need an ugly per-port hacks.

I'm not going to approve that change, until/unless Eric and I have thoroughly vetted the implications.

**Comment by catap** [comment]
@mascguy the root cause for this update is fixing an issue for macOS 14 :)

See: https://github.com/pmodels/mpich/issues/6684#issuecomment-1751198439 where @eborisch confirms that update fixes an issues with macOS 14 that means unblock scotch and tons of software.

**Comment by catap** [comment]
> Kirill, there's already an open PR, for updating `mpich`.

I've tried to find it via link https://github.com/macports/macports-ports/pulls?q=mpich and can't :( may I ask to share the URL?

**Comment by catap** [comment]
@mascguy if you not ok, I can remove to be a co-maintainer as well

**Pull request closed without merging**
