### PR TITLE
wireshark4: update to 4.0.10

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by i0ntempest** [comment]
Unrelated, seems on macOS 14 cmake cannot find any python modules in the `tools/` folder, causing a configure failure.

**Comment by ghosthound** [comment]
> Unrelated, seems on macOS 14 cmake cannot find any python modules in the `tools/` folder, causing a configure failure.

If you have not already, please open a ticket for cmake on macOS 14 (or add to it if a ticket already exists).

**Comment by pmetzger** [comment]
@ghosthound Do you approve this update for commit?

**Comment by ghosthound** [comment]
Thanks for the PR!

**Comment by i0ntempest** [comment]
> > Unrelated, seems on macOS 14 cmake cannot find any python modules in the `tools/` folder, causing a configure failure.
> 
> If you have not already, please open a ticket for cmake on macOS 14 (or add to it if a ticket already exists).

I have figured this out: I have Python 3.12 installed alongside of 3.11 and `imp` (which is what cmake uses to find modules) is gone in that version. In fact Python 3.11 already spits out a deprecation warning when you import it. Then because of [this problem](https://trac.macports.org/ticket/68362), 3.12 is used for building even when `+python311` is specified. Implementing the fix suggested in that ticket fixed the build. Do you want me to open a PR with the suggested fix?

**Comment by pmetzger** [comment]
@i0ntempest Sure, why not submit it?

**Comment by ghosthound** [comment]
> I have figured this out: I have Python 3.12 installed alongside of 3.11 and `imp` (which is what cmake uses to find modules) is gone in that version. In fact Python 3.11 already spits out a deprecation warning when you import it. Then because of [this problem](https://trac.macports.org/ticket/68362), 3.12 is used for building even when `+python311` is specified. Implementing the fix suggested in that ticket fixed the build. Do you want me to open a PR with the suggested fix?

If you have something for the other ticket that'd be great, otherwise I expect to get to it next week.

**Comment by i0ntempest** [comment]
https://github.com/macports/macports-ports/pull/20992

**Pull request merged**
