### PR TITLE
libarchive: 3.2.1 -> 3.2.2

### PR DESCRIPTION
**Pull request by l2dy**
I can put the patch back but is it still needed? (`/* All clang versions have __builtin_bswap16() */`) 

Two relevant upstream commits:

https://github.com/libarchive/libarchive/commit/43d23948f5fd86226fc47e78ce718283ead4f16a

https://github.com/libarchive/libarchive/commit/d2e8111b3a3468102737f7d414ea1bb6f6904bfe

### CODE REVIEW

**Comment by larryv** [comment]
@tobypeterson would know better, but I believe older versions of Clang do not have `__builtin_bswap16`. See 884f9433da84fe0ccf5e27a0723538b17eeecdfa, 0e009e3be4b8b533e3dcb8febd92aed9215ec505, 0b9118626dea59406f6026642ee8177746b73015.

**Comment by larryv** [comment]
Is this update no longer valid?

**Comment by l2dy** [comment]
Still valid, I was clearing old branches and deleted this one by mistake.

**Comment by tobypeterson** [comment]
I don't see how either of those upstream commits resolve the reported issue from https://trac.macports.org/ticket/51711 ... the comment in libarchive claims that all clang versions have __builtin_bswap16, which is demonstrably false. The patch should be adapted to apply to 3.2.2; seems straightforward enough.

**Comment by l2dy** [comment]
@tobypeterson will update soon.

**Comment by l2dy** [comment]
@tobypeterson I was waiting for your comment. Patch is back now.

**Comment by tobypeterson** [comment]
Thanks! LGTM

**Pull request merged**
