### PR TITLE
Drop myself as maintainer and thanks for the fish!

### PR DESCRIPTION
**Pull request by catap**
[skip ci]

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by breun** [comment]
@catap So long and thank you for your fish as well!

**Comment by szhorvat** [comment]
Sorry to see you leaving @catap !

**Comment by barracuda156** [comment]
😢

**Comment by easye** [comment]
On 11/6/24 15:27, Kirill A. Korinsky wrote:

>   * *M* lang/sbcl-bootstrap/Portfile <https://github.com/macports/
>     macports-ports/pull/26457/

I am very sorry to see you go:  your energy and enthusiasm was most 
welcome.  Hopefully your experience with MacPorts rewarded you in some way.

May I ask what will be the fate of the sbcl-bootstrap PPC binaries 
hosted at <https://macos-powerpc.org/compilers/sbcl/boot/>?

Will they continue to be hosted there?

If so, if they need to be updated, who should be contacted?

thanks,
Mark

-- 
"No, this is not a disentanglement, but a progressive /knotting-into/."

**Comment by barracuda156** [comment]
@easye I do not think we will need to update them any soon if ever. Why we needed them is that previous binaries were outright archaic. There is no need to keep updating bootstrap ones, they should be good to build SBCL for years to come.
(I have written in SDCL developer list on that topic, but exotic platforms is not something that is prioritized for immediate replies. I will remind about that in a couple of weeks if nobody responds.)

**Comment by herbygillot** [comment]
Thank you for everything, @catap. Well-wishes and best of luck to you in all your journeys.

**Comment by catap** [comment]
> May I ask what will be the fate of the sbcl-bootstrap PPC binaries hosted at <https://macos-powerpc.org/compilers/sbcl/boot/>? Will they continue to be hosted there? If so, if they need to be updated, who should be contacted? thanks, Mark

I will continue provide hardware which hosts that web-site and to update it feel free to contact @barracuda156 or me, but Sergei manages that web-site and he is the right contact person.

I simple a guy who poriveds hosting for him.

**Comment by mascguy** [comment]
@catap Kirill, we wish you wouldn't go. And you're always welcome to come back anytime.

Thank you so much for all of your contributions, you will be missed!

**Comment by artkiver** [comment]
@catap thank you for all your contributions!

I'm hoping my paranoid comment PR 20092 wasn't a contributing factor, even then I realize you were only working to improve MacPorts.

You'll definitely be missed; but hopefully this is just good bye for now. I had no idea you were a maintainer of SO MANY Portfiles, I would have burnt out long ago with that level of responsibility; I feel as if I barely keep my head above water as it is.

**Comment by catap** [comment]
@artkiver frankly, I had forgot about that PR at all. So, no hard feelings.

**Comment by judaew** [comment]
I remember you from many PRs, thank you for your huge contribution and I wish you good luck!

**Comment by macportsraf** [comment]
@catap Thanks. The fish were well deserved!

**Pull request merged**
