### PR TITLE
delete sign

### PR DESCRIPTION
**Pull request by janstary**
security/sign is 14 years old and has no maintainer.
Is anyone using it?

### CODE REVIEW

**Comment by pmetzger** [comment]
I'm generally suspicious of security utilities without updates or support for 14 years. Again, however, I'd like an opinion from someone like @raimue before removing.

**Comment by raimue** [comment]
Repology: https://repology.org/metapackage/sign/versions

**Comment by raimue** [comment]
Seems old and not very popular. Being 14 years old without updates and using md5/sha1 as a digest algorithm, it should probably not be considered secure anymore. There are more recent alternatives such as `signify(1)` from OpenBSD with similar functionality.

+1 for removal.

**Comment by pmetzger** [comment]
Done.

**Pull request merged**
