### PR TITLE
docker: update to 17.04.0-ce

### PR DESCRIPTION
**Pull request by lbschenkel**

### CODE REVIEW

**Comment by l2dy** [comment]
docker just moved to https://github.com/moby/moby.

**Comment by mojca** [comment]
I guess that means that we should also rename the port(s)?

**Comment by l2dy** [comment]
@mojca See https://github.com/moby/moby/pull/32691#issuecomment-295063346.

**Comment by lbschenkel** [comment]
Both the version of Docker and this PR were created before the rename to Moby, and in case it was merged it would have been a non-issue. In the interest of getting an updated version out, I feel that this discussion should have happened for a release that is actually branded with the new name and with all honestly it appeared like bike shedding to me.

But moving forward, I kinda lost interest in releasing this now. I think it's more productive to have a discussion about which name to use and update to the newest version, 17.05.

**Comment by l2dy** [comment]
@lbschenkel It would become an issue. See 55ae58413848339985e5476fc06233960b52bdcc.

**Comment by lbschenkel** [comment]
Fair enough. I stand corrected.

**Comment by lbschenkel** [comment]
OK, I have updated the PR to point to the new GitHub repository. I think we should sidestep the port name discussion for this PR since 17.04 was released before the whole Moby announcement.

Regarding the future of this port, I still can't really figure out what their plan is and what will be "docker" and what will be "moby". My two cents: in the interest of prevent unnecessary disruption, the name should be kept for now until upstream's strategy becomes clearer -- after all, it is not really causing problem. But I have no desire of getting into a big name discussion, really; I care much more about having an up-to-date, working port, whatever it is called.

**Pull request merged**
