### PR TITLE
boost: fix context for PPC

### PR DESCRIPTION
**Pull request by barracuda156**
[skip ci] – because changes concern _only_ PPC, which is not built anyway.

#### Description

PR fixes `context` for PPC.
Upstream commits:
https://github.com/boostorg/context/commit/a8f60b95767383a9d3f13c36287fc84d14be9ed3
https://github.com/boostorg/context/commit/10310f56642929d78bb4a8621145472fbee49982

P. S. We do not need to revbump 1.80, since it does not build with GCC at the moment: https://github.com/boostorg/json/issues/774

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

macOS 10A190
Xcode 3.2

macOS 10.5.8
Xcode 3.1.4

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by michaelld — APPROVED** [review]
LGTM; thx!

**Comment by michaelld** [comment]
Excellent work @barracuda156 !

**Comment by barracuda156** [comment]
@michaelld Thank you!

**Comment by barracuda156** [comment]
@michaelld Good to merge? Or we do it after `icu` is updated, to avoid revbumping twice?

**Comment by michaelld** [comment]
hoping for a review from @mascguy  ...

**Comment by michaelld** [comment]
what is the PR for the ICU update?

**Comment by barracuda156** [comment]
> what is the PR for the ICU update?

@michaelld We have to ask @catap perhaps, when he is gonna update the regular `icu` port (`icu-devel` already updated).

**Comment by evanmiller** [comment]
Have you tested the context functionality? I see that in one of the PRs that you built `folly`, but I just wanted to make sure that this works as intended at run-time. I believe there are some tests and examples included in the Boost context source tree.

**Comment by barracuda156** [comment]
@michaelld So `icu` done, and I have rebased against master with subsequent revbumps. (No need to revbump `boost180`, which does not build with GCC anyway, so cannot have been built for PPC.)

@evanmiller If you could help here, it would be awesome.

**Comment by evanmiller** [comment]
@barracuda156 I tested previously by running

```
g++-mp-7 fibonacci.cpp -lboost_context-mt -L/opt/local/lib
```

on [fibonacci.cpp](https://github.com/boostorg/context/blob/develop/example/fiber/fibonacci.cpp). If that prints the Fibonacci sequence I will be satisfied :-).

**Comment by barracuda156** [comment]
@evanmiller Well, it compiles, but does not run. I am not sure if it is a context-specific failure though or Boost-general failure.

Here Boost atomics fail with Bus error (context is _not_ used): https://github.com/PurpleI2P/i2pd/issues/1726?notification_referrer_id=NT_kwDOBXwLlrMzMDg4MjkzMTYzOjkyMDE1NTEw#issuecomment-1299053779

Compare with what I got:
```
sergey-fedorovs-power-mac-g5:Dev svacchanda$ /opt/local/bin/g++-mp-11 fibonacci.cpp -I/opt/local/libexec/boost/1.76/include -lboost_context-mt -L/opt/local/libexec/boost/1.76/lib -o boost_test
sergey-fedorovs-power-mac-g5:Dev svacchanda$ /Users/svacchanda/Dev/boost_test 
Bus error
```
```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_PROTECTION_FAILURE at address: 0x00000000
0x0001a200 in jump_fcontext ()
(gdb) where
#0  0x0001a200 in jump_fcontext ()
Cannot access memory at address 0x0
#1  0x00000000 in ?? ()
```
Something seems to be broken with memory access. Any ideas welcome.

**Comment by kencu** [comment]
build it like this, perhaps:

```
g++-mp-7 fibonacci.cpp -I/opt/local/libexec/boost/1.76/include  -std=c++17 -lboost_context-mt -L/opt/local/libexec/boost/1.76/lib -g -O0
```

then load it into the debugger:
```
ggdb ./a.out
```
then set a breakpoint at main:
```
b main
```
then run it:
```
run
```
when it hits the breakpoint at main, you should be able to "step" one step at a time through the source code until you see exactly where it bus errors.

The few steps before that is usually the problem.

You can also look at the backtraces in the crashlog folder. Once it is build with debugging symbols and no optimization, some combination of the crashlogs and what you see stepping through will give you, hopefully, some hint about what is going wrong.

Next step is for you to sort out how to examine the frame variables in the debugger and see what they look like just before the call that causes the bus error.

**Comment by evanmiller** [comment]
@barracuda156 The context error and the atomics error look like two separate issues.

You might also try kencu's advice using the `gdb-apple` port, which I have used successfully on PPC.

**Comment by barracuda156** [comment]
@kencu @evanmiller Here is what I get when trying `b main` with OS `gdb`:
```
(gdb) b main
Die: DW_TAG_unspecified_type (abbrev = 5, offset = 71)
	has children: FALSE
	attributes:
		DW_AT_name (DW_FORM_strp) string: "decltype(nullptr)"
Dwarf Error: Cannot find type of die [in module /Users/svacchanda/Dev/boost/a.out.dSYM/Contents/Resources/DWARF/a.out]
(gdb) run
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_PROTECTION_FAILURE at address: 0x00000000
0x0001a200 in jump_fcontext ()
```
Same from `gdb-apple`:
```
(gdb) b main
Breakpoint 1 at 0x2318: file fibonacci.cpp, line 14.
Breakpoint 2 at 0x2278: file fibonacci.cpp, line 17.
warning: Multiple breakpoints were set.
Use the "delete" command to delete unwanted breakpoints.
(gdb) run
Starting program: /Users/svacchanda/Dev/boost/a.out 
Unable to find Mach task port for process-id 14993: (os/kern) failure (0x5).
```

**Comment by barracuda156** [comment]
So with `gdb-apple`, once run with `sudo`, this is the output:
```
Breakpoint 1, main () at fibonacci.cpp:27
27	        }};
(gdb) c
Continuing.

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_PROTECTION_FAILURE at address: 0x00000000
0x0001a200 in jump_fcontext ()
```

**Comment by kencu** [comment]
there is a learning curve to debugging, and you will enjoy it!

Of course, if you set a breakpoint at main(), and then just hit "c" to continue once you stop there, you will crash without much further information than you had before.:> 

Look back at what I wrote above. You need to step, etc. 

There are many tutorials and books about how to debug with gdb available on the internet and web and at bookstores and online classes. It would frankly be just too hard for me to type that all in here, even if I did have the time to do that.

**Comment by barracuda156** [comment]
@kencu Sure, sorry :) I will deal with this in coming days.

**Comment by barracuda156** [comment]
I will update with some notes first, to keep track.

One thing that we have wrong is “hidden”, which was inherited from Linux and should not be used on Darwin. Found some info here: https://www.mail-archive.com/ports@openbsd.org/msg89321.html

**Comment by barracuda156** [comment]
@evanmiller I have also tried using versions from here with no changes besides correcting a typo: https://github.com/twlostow/libcontext
And they do not work either.

We need help with magic code :)

**Comment by olk** [comment]
Does this happen on a PPC32 or PPC64 system?

`Cannot access memory at address 0x0` - means NULL-pointer.
Probably the assembler instructions / memory alignment isn't correct (check the calling convetions ABI) and requires debugging - stepping through the assembler instructions and comparing the content of the registers.
Unfortunately I don't own a PPC system and I'm too busy.

**Comment by barracuda156** [comment]
@olk I have currently tested only ppc32, since at the moment building Boost as ppc+ppc64 is broken in Macports. Yeah, I will try to debug and figure out what goes wrong. Alignments might be the issue indeed.

**Comment by evanmiller** [comment]
I have an upstream PR going here if any PPCheads want to take it for a spin: https://github.com/boostorg/context/pull/215

Something I noticed though was that while Context and Coroutine now compile on PPC, the Fiber module fails with assembly errors using GCC7 (G++7). So even with the proposed fixes, we might have to keep Fiber excluded on these platforms, at least for `boost181` (haven't tried previous versions).

**Comment by barracuda156** [comment]
> I have an upstream PR going here if any PPCheads want to take it for a spin: https://github.com/boostorg/context/pull/215
> 
> 
> 
> Something I noticed though was that while Context and Coroutine now compile on PPC, the Fiber module fails with assembly errors using GCC7 (G++7). So even with the proposed fixes, we might have to keep Fiber excluded on these platforms, at least for `boost181` (haven't tried previous versions).

@evanmiller I think we a) need to test boost176, which is the default as of now, and b) try building with newer GCC.
If that fails, we should fix fiber rather than disabling it, IMHO.

**Comment by evanmiller** [comment]
> @evanmiller I think we a) need to test boost176, which is the default as of now, and b) try building with newer GCC. If that fails, we should fix fiber rather than disabling it, IMHO.

Let's get Context working then we can worry about enabling Fiber. Since Fiber depends on Context, it's currently implicitly disabled on PPC.

**Comment by barracuda156** [comment]
> > @evanmiller I think we a) need to test boost176, which is the default as of now, and b) try building with newer GCC. If that fails, we should fix fiber rather than disabling it, IMHO.
> 
> Let's get Context working then we can worry about enabling Fiber. Since Fiber depends on Context, it's currently implicitly disabled on PPC.

@evanmiller My concern is that it will take another forever to get the additional fix merged. However, this is your PR, I just expressed my opinion. (It is still better to have something fixed than nothing at all, of course.)

**Comment by barracuda156** [comment]
P. S. It may be worth adding this too: https://github.com/boostorg/smart_ptr/commit/97c9204a952f60d13def0e321c0a92ec6dec148b

Not context-related, but ppc32-related.

**Comment by barracuda156** [comment]
Closing in favor of this: https://github.com/macports/macports-ports/pull/17086

**Pull request closed without merging**
