### PR TITLE
py-typer: Submission

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
Py36 has missing dependencies.

**Comment by cjones051073** [comment]
Has missing dependencies.

**Comment by cjones051073** [comment]
@essandess Have you actually tested all the python versions in this submission ? I just tried to install all the required py-flit_core versions and neither 36 or 37 install correctly (at least on macOS 11).

Many thanks for all these submissions, I do appreciate them, but it is expected that when you submit a new port, or add new python versions to an existing one, you have actually tried to install *all* of the python versions yourself first to confirm they install correctly, on at least on OS.

**Comment by essandess** [comment]
Just rm Python 36, it effectively EOL anyway.

**Comment by essandess** [comment]
@cjones051073 This is now resolved with the merge of #10511.

**Comment by herbygillot** [comment]
> Just rm Python 36, it effectively EOL anyway.

One important thing worth mentioning is that while it's true certain Python versions are end-of-life, we may still have some non-Python ports that do not support the latest version of Python for a Python library dependency they may have.

Thus in some cases, we do have older subports around for a reason.

**Comment by essandess** [comment]
> > Just rm Python 36, it effectively EOL anyway.
> 
> One important thing worth mentioning is that while it's true certain Python versions are end-of-life, we may still have some non-Python ports that do not support the latest version of Python for a Python library dependency they may have.
> 
> Thus in some cases, we do have older subports around for a reason.

Yes, thanks for pointing this out. I still use some 27 stuff and expect to for some time.

**Pull request merged**
