### PR TITLE
gjs: Update to 1.78.4

### PR DESCRIPTION
**Pull request by Dave-Allured**
#### Description

* Update gjs 1.76.2 --> 1.78.4.
* Avoid obsolete broken dependency mozjs102, was updated to mozjs115.
* Fixes Sonoma builds.
* Remove obsolete broken patch file for skip-gtk-tests.
* Upgrade to gitlab portgroup and associated benefits.
* Update master_site, now via portgroup.
* Update home page.
* Update python version to 3.12.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.6.4 22G513 x86_64
Xcode 15.2 / Command Line Tools 15.1.0

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tried a full install with `port -vs install`?
- [ ] tested basic functionality of all binary files?
- [x] tested basic functionality of ONE binary file?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
> * Update home page, now two of them.

There's no such feature in MacPorts. `homepage` can only be a single URL.

**Comment by Dave-Allured** [comment]
> Can you update this PR to update `gjs-devel` instead?

I will update `gjs-devel`.  However, I want to update `gjs` at the same time, because I am trying to fix `glade`.  Will that be okay?  Further thoughts?

**Comment by Dave-Allured** [comment]
> Ultimately I'll update `gjs`, a few days after this has been merged. But first we want to validate via `gjs-devel`.
> 
> Does that make sense?

Yes that makes sense.  I will leave the final strategy up to you.  You are the designated maintainer, and I do not wish to force.

However I am obviously trying to shortcut the process.  If at any point you see your way clear to merge `gjs` without any downside, please do so, so that dependents such as `glade` will clear.  Right now I do not see any downside, but it is not urgent and I will not continue to push that.

If you don't mind, please allow me to process `gjs-devel` in a separate PR.

**Comment by mascguy** [comment]
It looks like we need to fix the build for `mozjs115`, as it's failing for numerous macOS releases:

https://ports.macports.org/port/mozjs115/details/

That's on my to-do list, but may not be able to get to it for a few days.

Can you convert this PR to draft for now, until we've gotten everything ready/fixed?

**Comment by Dave-Allured** [comment]
@mascguy, `mozjs115` is failing for very old OS versions, but doing fine for all modern versions except Catalina/10.15.  `gjs-devel` is tracking the same.  Merge `gjs` now, fix Catalina later (or not)?

**Comment by Dave-Allured** [comment]
FYI there are now three newer tag releases of `gjs`.  All three are failing CI for gjs-devel, for a reason I think is completely unrelated to mozjs.  This version `gjs-1.78.4` is the way to go for right now.

**Comment by Dave-Allured** [comment]
Closing.  `gjs` was updated again.  Go to https://github.com/macports/macports-ports/pull/23177.

**Pull request closed without merging**
