### PR TITLE
qcachegrind: update to 21.08.1

### PR DESCRIPTION
**Pull request by FnControlOption**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6
Xcode 11.3.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
thanks for the update @FnControlOption ! The CI systems fail to build this, but I must admit that the reason why isn't completely clear to me... It might be some intermittent issue and we can of course re-start the tests. However, I notice that you didn't fill out our PR checklist - which parts of the checklist did you complete (e.g., did it build locally for you with `sudo port -dvt install <portnam>`? - that would be useful to know).

**Comment by devernay** [comment]
The CI build fails installing dependencies,  but the only dependency is Qt5...

**Comment by reneeotten** [comment]
> The CI build fails installing dependencies, but the only dependency is Qt5...

I re-started the jobs, let's see whether they finish now. But if you, as the maintainer of the port, have also verified that the updated port builds locally and functions properly then it should be good to go I'd think

**Comment by reneeotten** [comment]
okay, the CI builds pass now (the Azure pipeline fails for unrelated reasons and can be ignored). @devernay can you please indicate whether you approve these changes and it's okay to merge?

**Review by devernay — APPROVED** [review]

**Pull request merged**
