### PR TITLE
mlt/mlt-qt5: merge and update

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.1
Xcode 10.1 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by RJVB** [comment]
Why the merge? I seem to recall that @ddennedy preferred to keep the ports separate.

**Comment by MarcusCalhoun-Lopez** [comment]
There many be good reasons to have two separate ports, but I cannot find them in the [commit message](https://github.com/macports/macports-ports/commit/896b35c26af9a261eeaaa0555f1181d8bd80770b) or [associated ticket](https://trac.macports.org/ticket/51411).
If mlt and mlt-qt5 cannot be installed simultaneously, then I am afraid I do not see the reason for having two ports.
Of course, there may very well be something I am missing, in which case, we should document how mlt is different from the other ports that use variants to choose between Qt4 and QT5.

**Comment by RJVB** [comment]
OK, I spoke too soon and without looking at the status quo. At least until recently (Sept 2018) mlt-qt5 was indeed a subport of a common port that Dan and I maintain(ed). 

If mlt-qt5 now needs merging someone intervened outside of my awareness.

I don't really mind one way or another, but there are enough examples of comparable ports that cannot be coinstalled and yet are standalone ports. In case of mlt-qt5 this could (at some point) be justified if the latest mlt requires a Qt5 version that doesn't run on enough OS versions (in my opinion as the mlt-qt5 maintainer; I'd require Qt 5.9 support).

**Comment by RJVB** [comment]
>Also, I find Qt 5.6 sufficient for MLT's qt module in case that improves OS version coverage.

It does.

**Pull request merged**
