### PR TITLE
openjdk-build port

### PR DESCRIPTION
**Pull request by usersxx**
#### Description
A port for building OpenJDK

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65 x86_64
 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by usersxx** [comment]
@reneeotten Can you review this port

**Comment by usersxx** [comment]
@reneeotten could you check the portfile

**Comment by reneeotten** [comment]
> @reneeotten could you check the portfile

I am sorry - I have not experience nor interest in `java` ports

**Comment by usersxx** [comment]
> > @reneeotten could you check the portfile
> 
> I am sorry - I have not experience nor interest in `java` ports

Ok

**Comment by usersxx** [comment]
@herbygillot could you check the portfile

**Pull request closed without merging**
