### PR TITLE
github-workflows: add support for macOS 12

### PR DESCRIPTION
**Pull request by usersxx**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by usersxx** [comment]
@jmroot / @ryandesign / @raimue 
What do you think?

**Comment by usersxx** [comment]
I also think, `/Users/runner/work/_temp/*.sh: line 16: portlist[@]: unbound variable` bug should be fixed

**Comment by usersxx** [comment]
> I also think, `/Users/runner/work/_temp/*.sh: line 16: portlist[@]: unbound variable` bug should be fixed

This bug occurs few times

**Comment by usersxx** [comment]
Since I have less experience in Github Workflows, could someone could help me with it.

**Comment by mascguy** [comment]
I don't have much experience in this area either, but @catap can provide insight/guidance. Kirill, thoughts on this?

**Comment by l2dy** [comment]
> I think, `/Users/runner/work/_temp/*.sh: line 16: portlist[@]: unbound variable` bug should be fixed

It's a known issue, see https://trac.macports.org/ticket/62071.

**Comment by ryandesign** [comment]
> What do you think?

I think we should enable CI builds for macOS 12 if we can but I have no idea if the change proposed here accomplishes that.

**Comment by l2dy** [comment]
We need to update https://github.com/macports/macports-ci-files first.

**Comment by ryandesign** [comment]
Do you know how to do that? I [tried to do it](https://github.com/macports/macports-ci-files/commit/ce2e6b671917168d2fab18eaf12207f144381dc5) but that hasn't resulted in MacPorts-21.tar.bz2 being created in [the latest release](https://github.com/macports/macports-ci-files/releases/tag/v2.7.2).

**Comment by ryandesign** [comment]
If I understand correctly, the workflow was configured to run only when a new release is created, which seems like a problem if we want to add a new macOS version to CI without also making a new release of MacPorts at the same time. I [added the ability to run the workflow manually](https://github.com/macports/macports-ci-files/commit/88fff46154afc6895753cd586fb166520e47971b), then [ran it](https://github.com/macports/macports-ci-files/runs/5801303142?check_suite_focus=true), which failed to fetch and extract MacPorts, saying "Verification Failure". @jmroot Can you help us understand how to do this?

**Comment by jmroot** [comment]
You have to run the job on the appropriate tag. It's running now.

**Comment by usersxx** [comment]
It is running now but the macos-12 workflows hasn't started yet. (see: https://github.com/macports/macports-ci-files/runs/5803307822?check_suite_focus=true)

**Comment by jmroot** [comment]
> If I understand correctly, the workflow was configured to run only when a new release is created, which seems like a problem if we want to add a new macOS version to CI without also making a new release of MacPorts at the same time.

If you can figure out how to reliably derive the upload URL for a release from outside the context of that release, please do implement that.

**Comment by usersxx** [comment]
> I don't have much experience in this area either, but @catap can provide insight/guidance. Kirill, thoughts on this?



> It is running now but the macos-12 workflows hasn't started yet. (see: https://github.com/macports/macports-ci-files/runs/5803307822?check_suite_focus=true)

The macos-12 workflow hasn't started yet even though it had started more than one day before. @catap, Do you have any idea, how to fix it?

**Comment by catap** [comment]
@usersxx are you sure that `macos-12` runner is available in github? I've checked https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners and haven't found any trace of `macos-12`.

This mean that it won't run until someone provides it.

**Comment by catap** [comment]
> The macos-12 workflow hasn't started running yet even though it had been started yesterday. @catap, Do you have any idea, how to fix it?

It hasn't started running because nobody provides runners for such workflow. As far as I know MacPorts using Github histed runners and Github hasn't provided runners for MacOS 12.

=> I really doubt that it can be done until Github provides such runners.

**Comment by usersxx** [comment]
> > The macos-12 workflow hasn't started running yet even though it had been started yesterday. @catap, Do you have any idea, how to fix it?
> 
> It hasn't started running because nobody provides runners for such workflow. As far as I know MacPorts using Github histed runners and Github hasn't provided runners for MacOS 12.
> 
> => I really doubt that it can be done until Github provides such runners.

I had founded it on [actions/virtual-environment](https://github.com/actions/virtual-environments) repository. (see https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md)

**Comment by usersxx** [comment]
> > > The macos-12 workflow hasn't started running yet even though it had been started yesterday. @catap, Do you have any idea, how to fix it?
> > 
> > 
> > It hasn't started running because nobody provides runners for such workflow. As far as I know MacPorts using Github histed runners and Github hasn't provided runners for MacOS 12.
> > => I really doubt that it can be done until Github provides such runners.
> 
> I had founded it on [actions/virtual-environment](https://github.com/actions/virtual-environments) repository. (see https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md)

Current [macos-12 tag is here](https://github.com/actions/virtual-environments/releases/tag/macOS-12%2F20220323.2)

**Comment by catap** [comment]
@usersxx maybe it has really a few runners or it wasn't ready yeat?

**Comment by usersxx** [comment]
> I think so as it hasn't been added to [README.md](https://github.com/actions/virtual-environments/blob/main/README.md) file

Since it hasn't been added to [README.md](https://github.com/actions/virtual-environments/blob/main/README.md) file and `macos-latest` is set to `macos-11`, It isn't working

**Comment by usersxx** [comment]
@ryandesign / @jmroot 
You should probably remove macos-12 workflows from [.github/main.yml on macports/macports-ci-files](https://github.com/macports/macports-ci-files/blob/main/.github/workflows/main.yml#L16)

**Comment by jmroot** [comment]
> It isn't probably ready.

Seems so. "This request was automatically failed because there were no enabled runners online to process the request for more than 1 days."

**Comment by jmroot** [comment]
> You should probably remove macos-12 workflows from [.github/main.yml on macports/macports-ci-files](https://github.com/macports/macports-ci-files/blob/main/.github/workflows/main.yml#L16)

Doesn't hurt anything to leave it there until runners are added.

**Comment by usersxx** [comment]
I have reopened this pr as I have realised that fail due to a bug. (see: https://github.com/actions/virtual-environments/discussions/5344) This pr can probable be merged after the bug gets fixed.

**Comment by usersxx** [comment]
@jmroot, Can you run the ci again on [macports/macports-ci-files](https://github.com/macports/macports-ci-files)

**Comment by catap** [comment]
@usersxx you may made a force push to your branch (inside your fork) which triggers a CI :)

**Comment by usersxx** [comment]
> @usersxx you may made a force push to your branch (inside your fork) which triggers a CI :)

It had triggered a CI but it failed on macos-10.15 only :(

**Comment by catap** [comment]
@usersxx I've created a branch https://github.com/catap/macports-ports/tree/macos-12-test based on your branch with one additional commit which changes a random port — `xz`.

You may see how CI works: https://github.com/catap/macports-ports/actions/runs/2145100873

**Comment by usersxx** [comment]
Currently, `macos-12` workflows require private preview so I am probably closing this pr

**Pull request closed without merging**
