### PR TITLE
crystal: Update to 1.0.0

### PR DESCRIPTION
**Pull request by judaew**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.2.3 20D91
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mohd-akram** [comment]
Thanks for the PR. Amend the commit with the following:

```diff
diff --git a/lang/crystal/Portfile b/lang/crystal/Portfile
index 154aa8f922a..abbe9eba0d8 100644
--- a/lang/crystal/Portfile
+++ b/lang/crystal/Portfile
@@ -52,14 +52,11 @@ patchfiles          patch-compiler.diff patch-xml.diff \
                     patch-crypto.diff patch-ssl.diff
 
 post-patch {
-    reinplace "s|\"/usr/lib\", \"/usr/local/lib\"|\"${prefix}/lib\"|" \
-        ${worksrcpath}/src/compiler/crystal/codegen/link.cr
-
-    file copy -force ${worksrcpath}/src/lib_c/amd64-unknown-openbsd/c/iconv.cr \
-        ${worksrcpath}/src/lib_c/x86_64-macosx-darwin/c/iconv.cr
+    file copy -force ${worksrcpath}/src/lib_c/x86_64-openbsd/c/iconv.cr \
+        ${worksrcpath}/src/lib_c/x86_64-darwin/c/iconv.cr
 }
 
-configure.cmd       env | grep -v ^PATH=
+configure.cmd       env | grep -E '^(CC?|CPP|CXX|LD)(FLAGS)?='
 configure.pre_args  > Makefile.local
 
 set llvm_version    11
@@ -72,8 +69,7 @@ compiler.whitelist  macports-clang-${llvm_version}
 
 compiler.cxx_standard  2011
 
-build.args          CC="${configure.cc} -L${prefix}/lib" \
-                    FLAGS="--no-debug --release" \
+build.args          FLAGS="--no-debug --release" \
                     EXPORTS="CRYSTAL_CONFIG_PATH=lib:${prefix}/lib/${name} \
                         PATH=${workpath}/${name}-${cr_full_ver}/bin:\$PATH"
 

```

**Comment by judaew** [comment]
Done

**Review by mohd-akram — APPROVED** [review]

**Comment by herbygillot** [comment]
Failing to build: https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/137902/steps/install-port/logs/stdio

**Comment by judaew** [comment]
I'm not good at LLVM errors. As I understand it, so far Crystal advises building with LLVM version 10. I don't think this is the problem, but I wasn't able to find [build information](https://ports.macports.org/port/crystal/builds) for 10.11 after switching to LLVM 11 in 891b025c76834ed4a56583c0114c7b036db0f3cb.

Any ideas @mohd-akram?

**Comment by kencu** [comment]
that function is supposed to be here:
```
$ llvm-nm-mp-11 -a /opt/local/libexec/llvm-11/lib/clang/11.1.0/lib/darwin/libclang_rt.osx.a | grep isOS

0000000000000000 T ___isOSVersionAtLeast
```
and ideally should be automatically used.

People have had some troubles with this, however -- I think due to optimizations? Have to dig a bit...

https://jonnyzzz.com/blog/2018/06/05/link-error-2/

https://jonnyzzz.com/blog/2018/06/13/link-error-3/

**Comment by judaew** [comment]
Found something similar... https://github.com/ddnet/ddnet/commit/e8bd8459a6f556594f48f33f4d145033bc89d46f

**Comment by kencu** [comment]
it looks like perhaps something is trying to call ld directly to do the link, but it should be calling clang (which would then add all the runtime libs automatically).

**Pull request merged**
