### PR TITLE
meson: update to 0.64.1

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Just an update.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

macOS 10A190
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@reneeotten This perhaps can be merged now.

**Comment by harens** [comment]
May I ask why `github.tarball_from archive` was added when force pushing from https://github.com/macports/macports-ports/commit/80fd5d1c5a0a25adfe9b87fccaa94e310cc032d8 to https://github.com/macports/macports-ports/commit/7c5a79d20533b46caf6def01ac3f524bcb802b28. Isn't the top level `github.tarball_from releases` enough? Otherwise LGTM.

**Comment by barracuda156** [comment]
> May I ask why `github.tarball_from archive` was added when force pushing from [80fd5d1](https://github.com/macports/macports-ports/commit/80fd5d1c5a0a25adfe9b87fccaa94e310cc032d8) to [7c5a79d](https://github.com/macports/macports-ports/commit/7c5a79d20533b46caf6def01ac3f524bcb802b28). Isn't the top level `github.tarball_from releases` enough? Otherwise LGTM.

@harens TBH now I cannot remember, let me try with Releases. (Default is from tags.)

**Comment by reneeotten** [comment]
@barracuda156 what @harens is telling you correctly is to remove the line with “archive”

**Comment by barracuda156** [comment]
@reneeotten @harens I have no eyes :)

Removed. Thank you for pointing that out.

**Comment by barracuda156** [comment]
Hopefully now it can be merged.

**Review by harens — APPROVED** [review]
Thanks @barracuda156 for the update 👍

**Pull request merged**
