### PR TITLE
libb64: update to 1.2.1

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
per our usual requirements the functional/non-functional whitespace changes should be separated in two commits

**Comment by barracuda156** [comment]
It is a simple and nomaintainer port, why introduce unnecessary complication? Longer commit history as such is nothing good. (Admittedly, it does make sense when either maintainer wants it or when changes are non-trivial and portfile is huge.)

**Comment by reneeotten** [comment]
> It is a simple and nomaintainer port, why introduce unnecessary complication? Longer commit history as such is nothing good. (Admittedly, it does make sense when either maintainer wants it or when changes are non-trivial and portfile is huge.)

no point arguing about it; this is the way the project wants to do it (i.e., separate functional from non-functional changes) ; so you either follow the guidelines or close the PR. It's that simple.

**Comment by barracuda156** [comment]
@reneeotten Well, right when you make a PR a checklist explicitly asks to squash and minimize commits.

Perhaps if it is not what the project wants, worth clarifying that, and we will save our time on arguing regarding this.

I will change this now.

**Pull request merged**
