### PR TITLE
spring-boot-cli: update to 1.5.7

### PR DESCRIPTION
**Pull request by breun**
###### Description

Update to Spring Boot CLI 1.5.7.

###### Tested on

macOS 10.12.6 16G29
Xcode 8.3 8E162 

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by l2dy** [comment]
Why two commits with the same commit message?

**Comment by breun** [comment]
Just after I committed I remembered that a previous time I was asked to set my GitHub username in the maintainers field, so I did that as well. I believe I've now managed to squash the pushed commits.

**Comment by breun** [comment]
Darn, I messed this up again. Trying again via another PR.

**Comment by l2dy** [comment]
You should add your GitHub username and keep the email.

e.g. `maintainers {@jverne example.org:julesverne}`

**Comment by breun** [comment]
https://guide.macports.org/chunked/development.creating-portfile.html says either a GitHub username or email address is fine: "The maintainers keyword lists the maintainers' GitHub usernames or email addresses (...)" Why should I add both?

**Comment by l2dy** [comment]
In case someone wants to contact the maintainer via email (e.g. CC mailing list too). It's not required to add both, just recommended.

**Comment by mojca** [comment]
The buildbot also needs emails for reporting build failures. Do we need to change the wording in the guide?

**Comment by breun** [comment]
From the guide I got the idea email was completely optional. It would be nice if the guide explained why it’s recommended to put in your email and your GitHub username and what they’ll be used for.

**Pull request closed without merging**
