### PR TITLE
misc noarch ports: update platforms

### PR DESCRIPTION
**Pull request by jmroot**
#### Description

These ports all set `supported_archs noarch`, and appear (from my inspection of the Portfiles and lists of installed files) to install the same files regardless of OS version. This PR updates the `platforms` option so that we don't build a separate archive per macOS version.

If you know that this is not correct for your port or even have significant doubts, please say so and I will remove it from this PR. This change is an optimisation which has the potential to cause incorrect behaviour if applied inappropriately. In case of doubt, it's better for the maintainer to investigate thoroughly before changing this.

###### Type(s)
- [x] enhancement

### CODE REVIEW

**Comment by aalmiray** [comment]
👍 on jreleaser

**Comment by casey** [comment]
Fine for edmv 👍

**Comment by brucemiller** [comment]
latexml should be fine; there are no explicit OS dependences.

**Review by michaelld — APPROVED** [review]
LGTM for my 2 ports here

**Review by maherg — APPROVED** [review]

**Comment by pmoura** [comment]
Fine for `logtalk`.

**Pull request merged**
