### PR TITLE
dd_rescue: update to 1.99.13, fix build

### PR DESCRIPTION
**Pull request by barracuda156**
Closes: https://trac.macports.org/ticket/39427
Closes: https://trac.macports.org/ticket/40424

#### Description

Not sure this will build straightaway, the source is direly broken. Took forever to get it build and seemingly work locally.
Not all tests pass on PowerPC.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
Why is the CI broken?

**Comment by barracuda156** [comment]
```
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_sysutils_dd_rescue/dd_rescue/work/compwrap/cc/usr/bin/clang -Os -Wall -g -D_FORTIFY_SOURCE=2  -I/opt/local/libexec/openssl11/include -arch x86_64 -DHAVE_CONFIG_H -I . -DHAVE_AESNI -O3 -fPIC -o sha512.po -c sha512.c
  sha512.c:99:24: error: expected ')'
  static inline uint64_t htonll(const uint64_t x)
                         ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
  #define htonll(x)       __DARWIN_OSSwapInt64(x)
                          ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/libkern/_OSByteOrder.h:91:30: note: expanded from macro '__DARWIN_OSSwapInt64'
      (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                               ^
  sha512.c:99:24: note: to match this '('
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
  #define htonll(x)       __DARWIN_OSSwapInt64(x)
                          ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/libkern/_OSByteOrder.h:91:5: note: expanded from macro '__DARWIN_OSSwapInt64'
      (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
      ^
  sha512.c:191:31: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
                  sprintf(res, "%016" LL "x", ctx->sha512_h[i]);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
                                %016llx
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
    __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                         ^~~~~~~~~~~
  1 warning and 1 error generated.
  make: *** [sha512.po] Error 1
```

**Comment by pmetzger** [comment]
Okay, so if this doesn't build, maybe we should close the PR until you have a good way forward? You have a lot on your plate right now.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@pmetzger I don't think so, as I believe it is only related to the endianness inclusion patch.
@barracuda156 perhaps the [patches from FreeBSD](https://codeberg.org/FreeBSD/freebsd-ports/src/commit/da312f3f900bd4239d82328db55c5f1f7a82e1ad/sysutils/dd_rescue/files) might be a good clue for you.

**Comment by barracuda156** [comment]
> Okay, so if this doesn't build, maybe we should close the PR until you have a good way forward? You have a lot on your plate right now.

It does build, it is clangs are broken as often the case. I will look into this in coming days.

**Comment by pmetzger** [comment]
This has been sitting in the queue quite a while now. Could we either close it until you have time or finish it now?

**Comment by barracuda156** [comment]
@pmetzger Since I got M1 laptop, testing locally on a new OS became easier. Let me have one go trying fixing it. If it doesn’t work, I will close it for the time-being.

**Comment by barracuda156** [comment]
On Sonoma the first failure is trivially fixable: https://github.com/nxp-imx/mfgtools/commit/3c02ae8b2f2b64823b19c425816252fa36229974

But then the linker cannot find these:
```
ld: Undefined symbols:
  _find_nonzero_arm8, referenced from:
      _blockiszero in dd_rescue-8fb924.o
  _probe_arm8crypto, referenced from:
      _detect_cpu_cap in find_nonzero.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [dd_rescue] Error 1
```
`_probe_arm8crypto` is implemented in assembler, which I do not know for aarch64 at all. Any problem with this?
```
void probe_arm8crypto()
{
	asm volatile(
	"	movi	v0.16b, #0		\n"
	"	movi	v1.16b, #0		\n"
	"	aese v1.16b, v0.16b		\n"
	:
	:
	: "v0", "v1");
}
```

**Comment by pmetzger** [comment]
Why would dd_rescue require assembly language hacking?

**Comment by barracuda156** [comment]
@pmetzger I have no idea, tbh. My general understanding was that assembler tends to be faster, or at least that was the generally accepted opinion some years ago, but possibly developers merely borrowed whatever code they have found.

I am not gonna deal with any assembler besides PowerPC one, that’s both pointless and infeasible practically.

Let me see if this can build for x86 at least. If not, I will drop the PR. This is not a case where I see any need to fix a port just for PPC. It should either work for Intel too, or be removed as a broken one.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
> But then the linker cannot find these:
> 
> ```
> ld: Undefined symbols:
>   _find_nonzero_arm8, referenced from:
>       _blockiszero in dd_rescue-8fb924.o
>   _probe_arm8crypto, referenced from:
>       _detect_cpu_cap in find_nonzero.o
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [dd_rescue] Error 1
> ```
> 
> `_probe_arm8crypto` is implemented in assembler, which I do not know for aarch64 at all. Any problem with this?
> 

FreeBSD Ports has not solved this [5 years old issue](https://codeberg.org/FreeBSD/freebsd-ports/commit/32c8a26e27a4280f446e558efbffd95f7c4da2b7) and still block builds on aarch64.

**Comment by kencu** [comment]
Just to mention, the existing dd_rescue port appears to build and runs on an M1 Sonoma system without any troubles it seems...

sure, needs to be updated, but -- isn't currently broken. I didn't make it do it's "rescuing" to really get into it, though.

```
% port -v installed dd_rescue
The following ports are currently installed:
  dd_rescue @1.14_0 (active) requested_variants='' platform='darwin 23' archs='arm64' date='2023-10-23T09:42:03-0700'
% port contents dd_rescue
Port dd_rescue contains:
  /opt/local/bin/dd_rescue
  /opt/local/share/doc/dd_rescue/COPYING
  /opt/local/share/doc/dd_rescue/README.dd_rescue

% dd_rescue
dd_rescue: (fatal): both input and output have to be specified!

dd_rescue Version 1.14, garloff@suse.de, GNU GPL
 ($Id: dd_rescue.c,v 1.59 2007/08/26 13:42:44 garloff Exp $)
dd_rescue copies data from one file (or block device) to another.
USAGE: dd_rescue [options] infile outfile
Options: -s ipos    start position in  input file (default=0),
         -S opos    start position in output file (def=ipos),
         -b softbs  block size for copy operation (def=65536),
         -B hardbs  fallback block size in case of errs (def=512),
         -e maxerr  exit after maxerr errors (def=0=infinite),
         -m maxxfer maximum amount of data to be transfered (def=0=inf),
         -y syncfrq frequency of fsync calls on outfile (def=512*softbs),
         -l logfile name of a file to log errors and summary to (def=""),
         -o bbfile  name of a file to log bad blocks numbers (def=""),
         -r         reverse direction copy (def=forward),
         -t         truncate output file (def=no),
         -w         abort on Write errors (def=no),
         -a         spArse file writing (def=no),
         -A         Always write blocks, zeroed if err (def=no),
         -i         interactive: ask before overwriting data (def=no),
         -f         force: skip some sanity checks (def=no),
         -p         preserve: preserve ownership / perms (def=no),
         -q         quiet operation,
         -v         verbose operation,
         -V         display version and exit,
         -h         display this help and exit.
Note: Sizes may be given in units b(=512), k(=1024), M(=1024^2) or G(1024^3) bytes
This program is useful to rescue data in case of I/O errors, because
 it does not necessarily abort or truncate the output.
```

**Comment by pmetzger** [comment]
It appears the issue is the cryptography plugin(!!); I suspect if you just disable that (I don't get why one would want it) that the build will no longer be so complicated.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
I think this will be interesting, I dug a little further today and found that in Fedora repository simply [deletes these files before building](https://src.fedoraproject.org/rpms/dd_rescue/c/be11be720623355b8b5ad8ee2bdba6077cf694de).

**Comment by barracuda156** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou Wonder if anyone has communicated to the developer that the code is broken. (I mean, I can understand PowerPC is not being tested, but arm64 should be.)

**Comment by pmetzger** [comment]
We should either get this finished or close it, IMHO.

**Comment by barracuda156** [comment]
@pmetzger Will do either of the two during the coming week. Spent on it quite a bit of time back then, so rather hope to finalize. I have an Intel machine at home. If it doesn’t work, I gonna close this myself.

**Comment by pmetzger** [comment]
FYI, it's not obvious that the cryptography stuff is important.

**Comment by barracuda156** [comment]
> FYI, it's not obvious that the cryptography stuff is important.

Yeah, I will see what can be done. Got to the x86 VM now, so hopefully can finish it overnight.

**Comment by barracuda156** [comment]
@pmetzger Well, while I was half-through with fixing this port for aarch64, you have seen what I was told in the Python PR :) 
I have had enough.

**Pull request closed without merging**
