### PR TITLE
hdf5: update to latest and revbump deps.

### PR DESCRIPTION
**Pull request by eborisch**
#### Description

Updates hdf5 to the latest version and rev-bumps all dependents.

There may be some unnecessary rev-bumps (for ports where non-default variants bring in hdf5; these would trigger local rebuilds from rev-update anyway, but distributed packages won't actually change)... but my one-liner gsed revision updater doesn't grok that. If someone wants to pick those out, feel free. ;)

Default build on my system passed all tests.

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G3025
Xcode 10.1 10B61
###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by Schamschula** [comment]
I'm OK with the rev bump.

**Comment by dstrubbe** [comment]
Revbump isn't needed for berkeleygw: only a non-default variant uses it.

**Comment by MarcusCalhoun-Lopez** [comment]
The rev bump is fine for octave.

**Comment by blair** [comment]
LGTM for field3d.

**Comment by ryandesign** [comment]
> Revbump isn't needed for berkeleygw: only a non-default variant uses it.

But users who have the port installed with that non-default variant will need to rebuild the port. The revbump accomplishes that. (Rev-upgrade would too, but we should not assume all users have it enabled.)

**Comment by dstrubbe** [comment]
> > Revbump isn't needed for berkeleygw: only a non-default variant uses it.
> 
> But users who have the port installed with that non-default variant will need to rebuild the port. The revbump accomplishes that. (Rev-upgrade would too, but we should not assume all users have it enabled.)

Ok.

**Comment by eborisch** [comment]
If we want to revbump everything (not just those with default variant deps) is this ready to go?

**Comment by eborisch** [comment]
Removed lscsoft-deps. Keeping other bumps in keeping with @ryandesign's comment above.

**Pull request merged**
