### PR TITLE
iTerm2: update to 3.4.21

### PR DESCRIPTION
**Pull request by jrabinow**
#### Description

iTerm2: update to 3.4.21

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 14.0 23A344 arm64
Xcode 15.0 15A240d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`? no trace mode
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by jrabinow** [comment]
Hmm. The error here is as follows:
```
  Executing:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_aqua_iTerm2/iTerm2/work/iTerm2-3.4.21" && /usr/bin/make -j3 -w prod 
  DEBUG: system:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_aqua_iTerm2/iTerm2/work/iTerm2-3.4.21" && /usr/bin/make -j3 -w prod 
  make: Entering directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_aqua_iTerm2/iTerm2/work/iTerm2-3.4.21'
  xcodebuild -parallelizeTargets -target iTerm2 -configuration Deployment -scheme iTerm2 -derivedDataPath ./DerivedData && \
  	chmod -R go+rX DerivedData/Build/Products/Deployment
  Command line invocation:
      /Applications/Xcode_14.2.app/Contents/Developer/usr/bin/xcodebuild -parallelizeTargets -target iTerm2 -configuration Deployment -scheme iTerm2 -derivedDataPath ./DerivedData
  
  User defaults from command line:
      IDEDerivedDataPathOverride = /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_aqua_iTerm2/iTerm2/work/iTerm2-3.4.21/DerivedData
      IDEPackageSupportUseBuiltinSCM = YES
  
  2023-10-15 21:45:14.351 xcodebuild[2141:13863] NetworkStorageDB:_openDBReadConnections: failed to open read connection to DB @ /opt/local/var/macports/home/Library/Caches/com.apple.dt.xcodebuild/Cache.db.  Error=14. Cause=unable to open database file
  2023-10-15 21:45:14.351 xcodebuild[2141:13863] The read-connection to the DB=/opt/local/var/macports/home/Library/Caches/com.apple.dt.xcodebuild/Cache.db is NOT valid.  Unable to determine schema version.
```

I'm not quite sure how to fix this one since I'm on Mac 14. The best I can think of here is to special-case things, but to me, that approach is last-resort. Am I missing something here?

**Comment by markemer** [comment]
@jrabinow Yeah - iTerm typically only builds with the latest Xcode on the latest macOS, which has become an increasing problem for this `Portfile` - I'll take a look to see what's up?

**Comment by jrabinow** [comment]
Got it, thanks for looking! Anything I can do to help?

**Comment by markemer** [comment]
It's weird, it passes on 11 and 13 but not 12.

**Comment by jrabinow** [comment]
I'm seeing this error
```
  error: An empty identity is not valid when signing a binary for the product type 'Command-line Tool'. (in target 'iTermServer' from project 'iTerm2')
  warning: iTerm2SandboxedWorker isn't code signed but requires entitlements. It is not possible to add entitlements to a binary without signing it. (in target 'iTerm2SandboxedWorker' from project 'iTerm2')
```
I'm not sure why it needs codesigning but here we are. Inspired by https://sourceware.org/gdb/wiki/PermissionsDarwin and https://github.com/conda-forge/gdb-feedstock/blob/main/recipe/macos-codesign/macos-setup-codesign.sh, maybe something similar would be in order? I can see from my bash history that last time I installed iTerm2 from macports, I wound up running a bunch of codesigning shell commands, though I'm not sure which one did the trick. It was painful enough that I got frustrated.

Also, the other builds are passing but I realized the other day that the iTerm2 I was opening was the wrong one. When I tried to run the locally-built iTerm2, it would refuse to open. Most likely because this time, when I built it, I didn't codesign it.
I'll try building and codesigning shortly.

**Comment by markemer** [comment]
Yeah - I remember signing being a problem before as well. I love iTerm2 and I love building it from macports, but it's becoming more and more of a pain to get working, due to the sensible requirement of the latest Xcode to build, as binary distributions don't care what OS or Xcode you're on.

I've been looking into binary distribution for all but the latest macOS and maybe disabling sparkle somehow in a post install hook.

**Comment by markemer** [comment]
Figured it out - it was the fact we need to sign on macOS 12 as well now. I haven't been able to build iTerm2 on 4 versions of macOS for a while.

**Pull request merged**
