### PR TITLE
Pure Faust update

### PR DESCRIPTION
**Pull request by agraef**
This updates the Faust-related Pure packages to the latest versions, to match the corresponding Faust packages (cf. #138).

### CODE REVIEW

**Comment by ryandesign** [comment]
When the version is increased, the revision line should be removed so that the revision becomes 0.

**Comment by agraef** [comment]
Fixed.

**Comment by mojca** [comment]
The last two commits should be squashed (this can also be done by committer, it's just less work if done properly from the start). But if the last commit was needed, you should have added the port name and a colon as a prefix.

Without testing the changes look ok to me.

**Comment by agraef** [comment]
> The last two commits should be squashed

Again, I'll keep that in mind next time. Doing MP via github is new to me. @ryandesign, can you take care of it, or should I resubmit?

**Comment by agraef** [comment]
Should be in good shape now, can someone please merge?

**Pull request merged**
