### PR TITLE
Mesa@12.0.1_1: opengl fix for <=10.5

### PR DESCRIPTION
**Pull request by ken-cunningham-webuse**
see <https://trac.macports.org/ticket/52811> 
pull request generated per request from Jeremy. 
Needs further review regarding which systems to apply it to, however.

### CODE REVIEW

**Comment by ken-cunningham-webuse** [comment]
Jeremy - I changed this to apply only on 10.5 or less, as per Dave's observations of the buildbots. It could be committed as is, I think - and then if it is found to be needed on other systems later, that could be addressed later on.

**Comment by jeremyhu** [comment]
Could you please squash those into a single commit and update the commit message per guidelines.  Once that's done, I'll give it a merge.

Eg commit message:

    mesa: Address a build failure on Leopard
    
    Fixes https://trac.macports.org/ticket/52811

**Comment by ken-cunningham-webuse** [comment]
Hmm... I've been using the GIThub web-interface for this PR, and I think that function has been disabled by the admins on the web interface for now. To fix this PR as you've asked, I'm pretty sure I'll have to close this PR and reopen a new one (which is no problem at all). Will check.

**Comment by larryv** [comment]
Please do not open a new PR, it is not necessary. You can just squash your local branch and force-push it.

**Comment by ken-cunningham-webuse** [comment]
OK. Figured it out, I think. I'll write this up here for the next me (or some one) needs to find out how to do this). 

Had to - clone the branch to my local machine. Then use git  to merge the four commits into one with `git rebase -i HEAD~4`. Then edit the file to `squash` all but the first line, leaving that as `pick`. Then add the new commit message, and finally `git push --force origin` to shove the branch up to github, which updates the pull request with the new info, as above.

**Pull request merged**
