### PR TITLE
libocca: fix the build on >10.6

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Turned out, due to CIs being non-case-sensitive, an error was missed, and the port is currently failing on build bots.
Thanks to @harens for pointing that out: https://github.com/macports/macports-ports/pull/17796#issuecomment-1445340036
Hopefully this gonna fix the issue.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

* I have verified that the build is still okay with GCC, but we need to check on buildbots if it gets fixed with Clangs.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@harens CI passes, we could try and see :)

**Comment by harens** [comment]
From [10.9 builder](https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/221942/steps/install-port/logs/stdio):

```
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libocca/libocca/work/occa-1.5.0/src/occa/internal/utils/sys.cpp:94:7: error: use of undeclared identifier 'clock_get_time'
      clock_get_time(cclock, &ct);
      ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libocca/libocca/work/occa-1.5.0/src/occa/internal/utils/sys.cpp:96:7: error: use of undeclared identifier 'mach_port_deallocate'
      mach_port_deallocate(mach_task_self(), cclock);
```

Maybe it requires adding `#include <mach/clock.h>` and `#include <mach/mach.h>`?

**Comment by barracuda156** [comment]
@harens Is it still broken across the board, or build bot did not yet update, and I see old results?

**Comment by harens** [comment]
> @harens Is it still broken across the board, or build bot did not yet update, and I see old results?

Easiest method is to check the commit (https://github.com/macports/macports-ports/commit/cb62c184fd17c8b474afefe3655eeb6b99a34b60) and click the tick/cross, followed by details. It takes a bit of time to show up on the MacPorts website.

image

> P. S. Re clock, I wonder if it may be easier to use Linux code with clock_gettime, which we have in LegacySupport…

Is `clock_gettime` interchangable with `clock_get_time`? `clock_gettime` is defined in `<time.h>` whilst `clock_get_time` I think is in `<mach/clock.h>`.

**Comment by barracuda156** [comment]
@harens I don’t know, but the source uses `clock_gettime` right above, for Linux case:

```
#if (OCCA_OS & OCCA_LINUX_OS)
      timespec ct;
      clock_gettime(CLOCK_MONOTONIC, &ct);

      return (double) (ct.tv_sec + (1.0e-9 * ct.tv_nsec));
#elif (OCCA_OS == OCCA_MACOS_OS)
#  if defined __clang__ && defined CLOCK_UPTIME_RAW
      uint64_t nanoseconds = clock_gettime_nsec_np(CLOCK_UPTIME_RAW);

      return 1.0e-9 * nanoseconds;
#  else
      clock_serv_t cclock;
      host_get_clock_service(mach_host_self(), CALENDAR_CLOCK, &cclock);

      mach_timespec_t ct;
      clock_get_time(cclock, &ct);

      mach_port_deallocate(mach_task_self(), cclock);

      return (double) (ct.tv_sec + (1.0e-9 * ct.tv_nsec));
#  endif
```

**Comment by harens** [comment]
Oh ok that sounds good then 👍 As you say, the easiest thing to fix that error is patching to use `clock_gettime` for macOS and throw in some legacysupport.

**Comment by barracuda156** [comment]
> Oh ok that sounds good then 👍 As you say, the easiest thing to fix that error is patching to use `clock_gettime` for macOS and throw in some legacysupport.

I guess let us first wait till all build bots complete their work: I wanna see what exactly fails and where. Logically, at least some systems should be fine now (or else what is allegedly-Mac that code written for?).

**Comment by barracuda156** [comment]
@harens Okay, so it not _totally_ broken anymore, at least: https://ports.macports.org/port/libocca/details
Surprisingly problematic port, as it turned out.

**Pull request merged**
