### PR TITLE
opencoarrays: handle stealth update and fetch from releases

### PR DESCRIPTION
**Pull request by tenomoto**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6.3 21G419 arm64
Command Line Tools 14.2.0.0.1.1668646533

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@tenomoto Is the regular tarball broken? Or what happened? Was working fine.

**Comment by tenomoto** [comment]
The files on https://distfiles.macports.org/OpenCoarrays seems to be old. Besides the changes, I suggest making +openmpi to be default_variants because OpenCoarrays with mpich is slow.

**Comment by barracuda156** [comment]
> The files on https://distfiles.macports.org/OpenCoarrays seems to be old. Besides the changes, I suggest making +openmpi to be default_variants because OpenCoarrays with mpich is slow.

@tenomoto Please allow me to test that. Last time I tried, it was broken on PPC. But I did not look into the failure deeply. I need to reproduce that (or confirm it works).

**Comment by barracuda156** [comment]
It fails badly with `openmpi` whatever I try:
```
Start testing: Jan 28 20:29 CST
----------------------------------------------------------
1/84 Testing: initialize_mpi
1/84 Test: initialize_mpi
Command: "/opt/local/bin/bash" "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_science_OpenCoarrays/OpenCoarrays/work/build/bin/cafrun" "-np" "2" "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_science_OpenCoarrays/OpenCoarrays/work/build/bin/OpenCoarrays-2.10.1-tests/initialize_mpi"
Directory: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_science_OpenCoarrays/OpenCoarrays/work/build
"initialize_mpi" start time: Jan 28 20:29 CST
Output:
----------------------------------------------------------
--------------------------------------------------------------------------
A requested component was not found, or was unable to be opened.  This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded).  Note that
Open MPI stopped checking at the first component that it did not find.

Host:      sergey-fedorovs-power-mac-g5.local
Framework: ras
Component: proxy
--------------------------------------------------------------------------
[sergey-fedorovs-power-mac-g5.local:23862] [[29385,0],0] ORTE_ERROR_LOG: Not found in file /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_science_openmpi/openmpi-gcc12/work/openmpi-4.1.4/orte/mca/ess/hnp/ess_hnp_module.c at line 539
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ras_base_open failed
  --> Returned value Not found (-13) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
[sergey-fedorovs-power-mac-g5.local:23860] [[INVALID],INVALID] ORTE_ERROR_LOG: Unable to start a daemon on the local node in file /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_science_openmpi/openmpi-gcc12/work/openmpi-4.1.4/orte/mca/ess/singleton/ess_singleton_module.c at line 716
[sergey-fedorovs-power-mac-g5.local:23860] [[INVALID],INVALID] ORTE_ERROR_LOG: Unable to start a daemon on the local node in file /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_science_openmpi/openmpi-gcc12/work/openmpi-4.1.4/orte/mca/ess/singleton/ess_singleton_module.c at line 172
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_init failed
  --> Returned value Unable to start a daemon on the local node (-127) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Unable to start a daemon on the local node" (-127) instead of "Success" (0)
--------------------------------------------------------------------------
```

Or like this:
```
"initialize_mpi" end time: Jan 28 20:38 CST
"initialize_mpi" time elapsed: 00:00:00
----------------------------------------------------------

2/84 Testing: register
2/84 Test: register
Command: "/opt/local/bin/bash" "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_science_OpenCoarrays/OpenCoarrays/work/build/bin/cafrun" "-np" "2" "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_science_OpenCoarrays/OpenCoarrays/work/build/bin/OpenCoarrays-2.10.1-tests/register"
Directory: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_science_OpenCoarrays/OpenCoarrays/work/build
"register" start time: Jan 28 20:38 CST
Output:
----------------------------------------------------------
--------------------------------------------------------------------------
mpiexec-openmpi-gcc12 has detected an attempt to run as root.

Running as root is *strongly* discouraged as any mistake (e.g., in
defining TMPDIR) or bug can result in catastrophic damage to the OS
file system, leaving your system in an unusable state.

We strongly suggest that you run mpiexec-openmpi-gcc12 as a non-root user.

You can override this protection by adding the --allow-run-as-root option
to the cmd line or by setting two environment variables in the following way:
the variable OMPI_ALLOW_RUN_AS_ROOT=1 to indicate the desire to override this
protection, and OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 to confirm the choice and
add one more layer of certainty that you want to do so.
We reiterate our advice against doing so - please proceed at your own risk.
--------------------------------------------------------------------------
Error: Command:
   `/opt/local/bin/mpiexec-openmpi-gcc12 -n 2 /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_science_OpenCoarrays/OpenCoarrays/work/build/bin/OpenCoarrays-2.10.1-tests/register`
failed to run.
<end of output>
Test time =   0.15 sec
----------------------------------------------------------
Test Fail Reason:
Required regular expression not found. Regex=[Test passed.
]
"register" end time: Jan 28 20:38 CST
"register" time elapsed: 00:00:00
----------------------------------------------------------
```
In any scenario 83 tests fail out of 84.

Not that with MPICH everything is awesome, but in a comparative perspective much better. Under Macports MPICH tests freeze (so results are unknown), under system MPI half of tests pass:
```
--->  Testing OpenCoarrays
Executing:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_science_OpenCoarrays/OpenCoarrays/work/build" && export TMPDIR=/tmp && /opt/local/bin/ctest check 
Test project /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_science_OpenCoarrays/OpenCoarrays/work/build
      Start  1: initialize_mpi
 1/84 Test  #1: initialize_mpi ...................................   Passed    1.72 sec
      Start  2: register
 2/84 Test  #2: register .........................................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.47 sec
      Start  3: register_vector
 3/84 Test  #3: register_vector ..................................   Passed    0.48 sec
      Start  4: register_alloc_vector
 4/84 Test  #4: register_alloc_vector ............................   Passed    0.48 sec
      Start  5: allocate_as_barrier
 5/84 Test  #5: allocate_as_barrier ..............................***Failed  Required regular expression not found. Regex=[Test passed.
]  1.51 sec
      Start  6: allocate_as_barrier_proc
 6/84 Test  #6: allocate_as_barrier_proc .........................***Failed  Required regular expression not found. Regex=[Test passed.
]  1.86 sec
      Start  7: register_alloc_comp_1
 7/84 Test  #7: register_alloc_comp_1 ............................   Passed    0.43 sec
      Start  8: register_alloc_comp_2
 8/84 Test  #8: register_alloc_comp_2 ............................   Passed    0.42 sec
      Start  9: register_alloc_comp_3
 9/84 Test  #9: register_alloc_comp_3 ............................   Passed    0.42 sec
      Start 10: async_comp_alloc
10/84 Test #10: async_comp_alloc .................................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.64 sec
      Start 11: async_comp_alloc_2
11/84 Test #11: async_comp_alloc_2 ...............................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.51 sec
      Start 12: comp_allocated_1
12/84 Test #12: comp_allocated_1 .................................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.56 sec
      Start 13: comp_allocated_2
13/84 Test #13: comp_allocated_2 .................................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.54 sec
      Start 14: alloc_comp_get_convert_nums
14/84 Test #14: alloc_comp_get_convert_nums ......................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.45 sec
      Start 15: team_number
15/84 Test #15: team_number ......................................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.88 sec
      Start 16: teams_subset
16/84 Test #16: teams_subset .....................................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.58 sec
      Start 17: get_communicator
17/84 Test #17: get_communicator .................................   Passed    0.56 sec
      Start 18: teams_coarray_get
18/84 Test #18: teams_coarray_get ................................   Passed    0.73 sec
      Start 19: teams_coarray_get_by_ref
19/84 Test #19: teams_coarray_get_by_ref .........................   Passed    0.77 sec
      Start 20: teams_coarray_send
20/84 Test #20: teams_coarray_send ...............................   Passed    0.67 sec
      Start 21: teams_coarray_send_by_ref
21/84 Test #21: teams_coarray_send_by_ref ........................   Passed    0.72 sec
      Start 22: teams_coarray_sendget
22/84 Test #22: teams_coarray_sendget ............................   Passed    0.75 sec
      Start 23: sync_team
23/84 Test #23: sync_team ........................................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.82 sec
      Start 24: alloc_comp_multidim_shape
24/84 Test #24: alloc_comp_multidim_shape ........................   Passed   82.10 sec
      Start 25: send_convert_nums
25/84 Test #25: send_convert_nums ................................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.81 sec
      Start 26: sendget_convert_nums
26/84 Test #26: sendget_convert_nums .............................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.54 sec
      Start 27: sendget_convert_char_array
27/84 Test #27: sendget_convert_char_array .......................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.57 sec
      Start 28: send_convert_char_array
28/84 Test #28: send_convert_char_array ..........................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.54 sec
      Start 29: alloc_comp_send_convert_nums
29/84 Test #29: alloc_comp_send_convert_nums .....................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.56 sec
      Start 30: random_init
30/84 Test #30: random_init ......................................   Passed    0.65 sec
      Start 31: get_array
31/84 Test #31: get_array ........................................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.72 sec
      Start 32: get_self
32/84 Test #32: get_self .........................................   Passed    0.53 sec
      Start 33: get_convert_nums
33/84 Test #33: get_convert_nums .................................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.51 sec
      Start 34: get_convert_char_array
34/84 Test #34: get_convert_char_array ...........................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.54 sec
      Start 35: get_with_offset_1d
35/84 Test #35: get_with_offset_1d ...............................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.43 sec
      Start 36: whole_get_array
36/84 Test #36: whole_get_array ..................................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.54 sec
      Start 37: strided_get
37/84 Test #37: strided_get ......................................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.50 sec
      Start 38: get_static_array
38/84 Test #38: get_static_array .................................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.57 sec
      Start 39: send_array
39/84 Test #39: send_array .......................................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.58 sec
      Start 40: convert-before-put
40/84 Test #40: convert-before-put ...............................   Passed    0.65 sec
      Start 41: send_with_vector_index
41/84 Test #41: send_with_vector_index ...........................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.47 sec
      Start 42: strided_sendget
42/84 Test #42: strided_sendget ..................................   Passed    0.61 sec
      Start 43: get_with_vector_index
43/84 Test #43: get_with_vector_index ............................   Passed    0.63 sec
      Start 44: co_sum
44/84 Test #44: co_sum ...........................................   Passed    0.58 sec
      Start 45: co_broadcast
45/84 Test #45: co_broadcast .....................................   Passed    0.64 sec
      Start 46: co_broadcast_derived_type
46/84 Test #46: co_broadcast_derived_type ........................   Passed    0.71 sec
      Start 47: co_broadcast_allocatable_components
47/84 Test #47: co_broadcast_allocatable_components ..............   Passed    0.61 sec
      Start 48: co_broadcast_alloc_mixed
48/84 Test #48: co_broadcast_alloc_mixed .........................   Passed    0.58 sec
      Start 49: co_min
49/84 Test #49: co_min ...........................................   Passed    0.69 sec
      Start 50: co_max
50/84 Test #50: co_max ...........................................   Passed    0.62 sec
      Start 51: co_reduce
51/84 Test #51: co_reduce ........................................   Passed    0.60 sec
      Start 52: co_reduce_res_im
52/84 Test #52: co_reduce_res_im .................................   Passed    0.60 sec
      Start 53: co_reduce_string
53/84 Test #53: co_reduce_string .................................   Passed    0.66 sec
      Start 54: syncimages_status
54/84 Test #54: syncimages_status ................................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.83 sec
      Start 55: sync_ring_abort_np3
55/84 Test #55: sync_ring_abort_np3 ..............................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.63 sec
      Start 56: sync_ring_abort_np7
56/84 Test #56: sync_ring_abort_np7 ..............................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.79 sec
      Start 57: simpleatomics
57/84 Test #57: simpleatomics ....................................***Failed  Required regular expression not found. Regex=[Test passed.
] 13.58 sec
      Start 58: syncall
58/84 Test #58: syncall ..........................................   Passed    6.00 sec
      Start 59: syncimages
59/84 Test #59: syncimages .......................................   Passed    1.58 sec
      Start 60: syncimages2
60/84 Test #60: syncimages2 ......................................   Passed    1.57 sec
      Start 61: duplicate_syncimages
61/84 Test #61: duplicate_syncimages .............................   Passed    1.58 sec
      Start 62: hello_multiverse
62/84 Test #62: hello_multiverse .................................   Passed    0.97 sec
      Start 63: coarray_burgers_pde
63/84 Test #63: coarray_burgers_pde ..............................   Passed    1.79 sec
      Start 64: co_heat
64/84 Test #64: co_heat ..........................................   Passed    0.98 sec
      Start 65: asynchronous_hello_world
65/84 Test #65: asynchronous_hello_world .........................   Passed    0.85 sec
      Start 66: source-alloc-no-sync
66/84 Test #66: source-alloc-no-sync .............................   Passed    0.99 sec
      Start 67: put-allocatable-coarray-comp
67/84 Test #67: put-allocatable-coarray-comp .....................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.80 sec
      Start 68: get-put-allocatable-comp
68/84 Test #68: get-put-allocatable-comp .........................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.93 sec
      Start 69: allocatable_p2p_event_post
69/84 Test #69: allocatable_p2p_event_post .......................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.70 sec
      Start 70: static_event_post_issue_293
70/84 Test #70: static_event_post_issue_293 ......................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.57 sec
      Start 71: co_reduce-factorial
71/84 Test #71: co_reduce-factorial ..............................   Passed    0.59 sec
      Start 72: co_reduce-factorial-int8
72/84 Test #72: co_reduce-factorial-int8 .........................   Passed    0.53 sec
      Start 73: co_reduce-factorial-int64
73/84 Test #73: co_reduce-factorial-int64 ........................   Passed    0.68 sec
      Start 74: issue-493-coindex-slice
74/84 Test #74: issue-493-coindex-slice ..........................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.93 sec
      Start 75: issue-488-multi-dim-cobounds-true
75/84 Test #75: issue-488-multi-dim-cobounds-true ................***Failed  Required regular expression not found. Regex=[Test passed.
]  1.06 sec
      Start 76: issue-488-multi-dim-cobounds-false
76/84 Test #76: issue-488-multi-dim-cobounds-false ...............***Failed  Required regular expression not found. Regex=[Test passed.
]  1.16 sec
      Start 77: issue-503-multidim-array-broadcast
77/84 Test #77: issue-503-multidim-array-broadcast ...............   Passed    0.82 sec
      Start 78: issue-503-non-contig-red-ndarray
78/84 Test #78: issue-503-non-contig-red-ndarray .................   Passed    1.04 sec
      Start 79: issue-552-send_by_ref-singleton
79/84 Test #79: issue-552-send_by_ref-singleton ..................***Failed  Required regular expression not found. Regex=[Test passed.
]  1.11 sec
      Start 80: issue-511-incorrect-shape
80/84 Test #80: issue-511-incorrect-shape ........................   Passed    0.99 sec
      Start 81: issue-515-mimic-mpi-gatherv
81/84 Test #81: issue-515-mimic-mpi-gatherv ......................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.83 sec
      Start 82: issue-700-allow-multiple-scalar-dim-array-gets
82/84 Test #82: issue-700-allow-multiple-scalar-dim-array-gets ...***Failed  Required regular expression not found. Regex=[Test passed.
]  0.92 sec
      Start 83: issue-762-mpi-crashing-on-exit
83/84 Test #83: issue-762-mpi-crashing-on-exit ...................   Passed    0.86 sec
      Start 84: test-installation-scripts.sh
84/84 Test #84: test-installation-scripts.sh .....................   Passed    2.32 sec

54% tests passed, 39 tests failed out of 84

Total Test time (real) = 166.08 sec

The following tests FAILED:
	  2 - register (Failed)
	  5 - allocate_as_barrier (Failed)
	  6 - allocate_as_barrier_proc (Failed)
	 10 - async_comp_alloc (Failed)
	 11 - async_comp_alloc_2 (Failed)
	 12 - comp_allocated_1 (Failed)
	 13 - comp_allocated_2 (Failed)
	 14 - alloc_comp_get_convert_nums (Failed)
	 15 - team_number (Failed)
	 16 - teams_subset (Failed)
	 23 - sync_team (Failed)
	 25 - send_convert_nums (Failed)
	 26 - sendget_convert_nums (Failed)
	 27 - sendget_convert_char_array (Failed)
	 28 - send_convert_char_array (Failed)
	 29 - alloc_comp_send_convert_nums (Failed)
	 31 - get_array (Failed)
	 33 - get_convert_nums (Failed)
	 34 - get_convert_char_array (Failed)
	 35 - get_with_offset_1d (Failed)
	 36 - whole_get_array (Failed)
	 37 - strided_get (Failed)
	 38 - get_static_array (Failed)
	 39 - send_array (Failed)
	 41 - send_with_vector_index (Failed)
	 54 - syncimages_status (Failed)
	 55 - sync_ring_abort_np3 (Failed)
	 56 - sync_ring_abort_np7 (Failed)
	 57 - simpleatomics (Failed)
	 67 - put-allocatable-coarray-comp (Failed)
	 68 - get-put-allocatable-comp (Failed)
	 69 - allocatable_p2p_event_post (Failed)
	 70 - static_event_post_issue_293 (Failed)
	 74 - issue-493-coindex-slice (Failed)
	 75 - issue-488-multi-dim-cobounds-true (Failed)
	 76 - issue-488-multi-dim-cobounds-false (Failed)
	 79 - issue-552-send_by_ref-singleton (Failed)
	 81 - issue-515-mimic-mpi-gatherv (Failed)
	 82 - issue-700-allow-multiple-scalar-dim-array-gets (Failed)
Errors while running CTest
```

I am pretty sure it is not OpenCoarrays problem, but rather MPICH is half-broken, and OpenMPI is broken hopelessly.

**Comment by barracuda156** [comment]
@tenomoto But if you tested OpenMPI on Intel and everything passes, we can make it a default conditionally on not ppc/ppc64. For PPC, I will try to find a relatively better option. Ideally, of course, we should just fix MPICH and HWLOC.

**Comment by reneeotten** [comment]
> @tenomoto Is the regular tarball broken? Or what happened? Was working fine.

fetching from "releases" is the preferred option, so if upstream does make these releases we should use them.

**Comment by barracuda156** [comment]
> > @tenomoto Is the regular tarball broken? Or what happened? Was working fine.
> 
> fetching from "releases" is the preferred option, so if upstream does make these releases we should use them.

Sure, why not. (Maybe worth implementing that in `github` PG?)

**Comment by reneeotten** [comment]
@barracuda156 is this ready to be merged; there is some discussion going on in this PR but it doesn't look like that is relevant to the changes made here - or?

**Comment by barracuda156** [comment]
@reneeotten I think it doesn’t hurt merging it. (Should we verify again checksums are correct? GitHub had a bug in Jan for some time when wrong algorithm was used that resulted in wrong checksums.)

**Comment by reneeotten** [comment]
I'll rerun the CI and if that passes merge the PR

**Comment by barracuda156** [comment]
@reneeotten Me either on the phone atm, that’s why I did not verify rightaway. Can do in a while today though.

**Pull request merged**
