### PR TITLE
openjdk-java port for macos

### PR DESCRIPTION
**Pull request by usersxx**
#### Description
Openjdk is Open Source, Open Innovation, Open Standards implementation of the Java Platform, Standard Edition, and related projects.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
@usersxx I guess it should be merged with https://github.com/macports/macports-ports/blob/master/java/openjdk/Portfile and

Cc: @breun

**Comment by breun** [comment]
It looks like these are the Oracle OpenJDK builds. It might be good to name them `openjdkXX-oracle` to keep the naming consistent with the existing `openjdk*` ports we already have in MacPorts, like `openjdk*-temurin`, `openjdk*-zulu`, `openjdk*-graalvm`, `openjdk*-openj9` (see https://ports.macports.org/search/?q=openjdk&name=on).

It might also be a good idea to add these as subports to https://github.com/macports/macports-ports/blob/master/java/openjdk/Portfile to keep all `openjdk*` ports in one place.

I also see this PR is adding ports for Java major versions that have already reached end of life. Do you have a need for these? Otherwise I would recommend not adding those. I've been actively deprecated and removing end of life versions of other OpenJDK distributions.

**Comment by usersxx** [comment]
It would be good to merge it with [https://github.com/macports/macports-ports/blob/master/java/openjdk/Portfile](url) as it would be a great contribution but I would prefer it to different from other ports as it has old verison. Moreover there are builds that are binaries of some of openjdk projects. Here are links about these projects. 
Valhalla [https://openjdk.java.net/projects/valhalla/](url)
Panama [https://openjdk.java.net/projects/panama/](url)
Loom [https://wiki.openjdk.java.net/display/loom/Main](url) or [https://openjdk.java.net/projects/loom/](url)
Graal (GraalVM) [https://openjdk.java.net/projects/graal/](url) or [https://www.graalvm.org/](url)

Actually the old java have been added to help developer run java in older versions of macOS.

**Comment by usersxx** [comment]
It would be great to merge this port to (https://github.com/macports/macports-ports/blob/master/java/openjdk/Portfile)](url) but this port has been created to distribute openjdk project binaries to eyeryone using macOS as well as older openjdk to  eyeryone using older macOS versions. Openjdk projects binaries that have been included till now

Valhalla by Hotspot group [https://wiki.openjdk.java.net/display/valhalla/Main](url) or [https://openjdk.java.net/projects/valhalla/](url)

Panama by Hotspot Group [https://openjdk.java.net/projects/panama/](url)

Loom by Hotspot Group [https://wiki.openjdk.java.net/display/loom/Main](url) or [https://openjdk.java.net/projects/loom/](url)

Graal or GraalVM by Hotspot Group [https://www.graalvm.org/](url) or [https://openjdk.java.net/projects/graal/](url)

**Comment by breun** [comment]
The OpenJDK project is a source-only project without binary releases. There are various vendors that use the OpenJDK source code to produce binary distributions, (sometimes with their own modifications), like Oracle OpenJDK, Azul Zulu OpenJDK, Eclipse Temurin (formerly known as AdoptOpenJDK), Red Hat OpenJDK, etc. So, it would be good to indicate in the port name that these OpenJDK builds are from Oracle.

MacPorts already has ports for GraalVM (`openjdk*-graalvm`).

**Comment by usersxx** [comment]
I think the ports should merge but with old versions so that developer could debug issues in older system. (see https://jdk.java.net/archive/)

**Comment by catap** [comment]
> I think the ports should merge but with old versions too so that developer could debug issues in older system.

On the system that reached end of life and nobody support it? I really doubt that.

**Comment by usersxx** [comment]
Actually MacPorts also support old version of macOS so I have added old version of jdk for people using old version of macOS

**Comment by breun** [comment]
The current `openjdk*` ports also don't support all macOS versions supported by MacPorts. It seems IBM Semeru claims support back until Mac OS X 10.10 Yosemite for their binaries: https://github.com/macports/macports-ports/blob/master/java/openjdk/Portfile#L615-L639

It is possible that these binaries actually work on older OS versions as well, but I personally have no way to verify that, so I just copied whatever the official documentation says. Do you have a need to run Java on Mac OS X 10.9 or older?

**Comment by breun** [comment]
@catap According to https://github.com/macports/macports-ports/blob/master/devel/sn-demangler/Portfile#L26-L29 `sn-demangler` requires Java 8 or later. If not present `openjdk11` will be installed as a fallback. The `openjdk11` port defers to `openjdk11-temurin` on x86_64 and to `openjdk11-zulu` on arm64 (https://github.com/macports/macports-ports/blob/master/java/openjdk/Portfile#L230-L234), but both of those ports will currently fail to install on Mac OS X 10.7 (https://github.com/macports/macports-ports/blob/master/java/openjdk/Portfile#L615-L639), so whoever is using `sn-demangler` from MacPorts on 10.7 will probably use some other method of installing Java 8 or later. But sure, it could be that those ports would also work on Mac OS X 10.7. If you have access to 10.7-10.9 machines and can verify, I wouldn't mind lowering/removing the OS version checks.

**Comment by catap** [comment]
@breun this port is required java and sbt to be built. As you may see it was suceffuly built on MacPorts buildbots ;) So, at least some java/JDK can be installed via MacPorts on 10.7 :)

**Comment by breun** [comment]
@catap I wonder which port that is then, because looking at https://github.com/macports/macports-ports/blob/master/java/openjdk/Portfile#L615-L639 pretty much all `openjdk*` ports are currently only installable on 10.10 or later. Only `openjdk*-graalvm` ports are currently not covered by an OS version check, and I don't find any OS requirements in the GraalVM docs, so maybe that is used on the buildbots?

**Comment by catap** [comment]
@breun I have virtual machines with old macOS and may run some tests :)

But not right now. Probably on this week.

**Comment by catap** [comment]
@usersxx I suggest to squash all your commits to one, single, commit and forgot about commit "merge brnach ....".

Yeah, use force push to your branch.

**Comment by catap** [comment]
@breun I've made quite fast attempt to test openjdk on macOS Lion

All Zulu builds are failed like this:
```
macOS-Lion:~ catap$ /opt/local/var/macports/build/_Volumes_SharedFolders_Home_src_macports-ports_java_openjdk/openjdk7-zulu/work/zulu7.50.0.11-ca-jdk7.0.322-macosx_x64/zulu-7.jdk/C
ontents/Home/bin/java
Illegal instruction: 4
macOS-Lion:~ catap$ 
```

All adopt builds can't be downloaded because of SSL is too old:
```
--->  Attempting to fetch OpenJDK17U-jdk_x64_mac_hotspot_17.0.1_12.tar.gz from https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/
Error: Failed to fetch openjdk17-temurin: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Error: See /opt/local/var/macports/logs/_Volumes_SharedFolders_Home_src_macports-ports_java_openjdk/openjdk17-temurin/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port openjdk17-temurin failed
```

**Comment by usersxx** [comment]
Actually minimum version of JDK can be found at /jdk/contents/info.plist/ but as the projects from this port are from oracle, I have searched for certified operating system in oracle websites and added it.

**Comment by usersxx** [comment]
Minimum version of macOS required for jdk can be found at ${jdk}/contents/info.plist

**Comment by usersxx** [comment]
Minimum version of macOS required for jdk(JVM) can be found at " ${jdk}/contents/info.plist " directory

**Comment by pmetzger** [comment]
@usersxx You need to squash your commits for them to be considered for merging. This is standard procedure with MacPorts.

**Comment by usersxx** [comment]
Ok

**Comment by usersxx** [comment]
@catap and @pmetzger, I wouldn't update the Portfile and will forget about 'update and merge' unless check fails.

**Comment by catap** [comment]
@usersxx but you still must to squash everything into one commit ;)

**Comment by catap** [comment]
Anyway, I'd like to summarise my points regarding this port.
1. Please add `NoMirror` to `license`;
2. MacPorts already has [openjfx11](https://github.com/macports/macports-ports/blob/master/java/openjfx11/Portfile) and it seems reasonable idea to not introduce one more port.
3. `openjdk-8-graalvm-ce-amd64` repeats port `openjdk8-graalvm`. Same for `openjdk-11-graalvm-ce-amd64`.
4.  Tons of `openjdk-XX` ports should be merged with meta `openjdk` port as `-oracle` and `-ibm` vendor. See `zulu-jdk` which was introduced by me and which was merged into `openjdk` port as `openjdk-*-zulu`.

If you would like to install an old version of port or a port which was obsolete and removed you may temprorary switch your mackports tree to the last commit which contains desired version and simple install it :)

From another hand, it is possible to introduce legacy ports like `openjdk-12-zulu-legacy` but I still haven't see any usecase for it.

I'm working with JVM a lot and I haven't rememer any major differences between 12 and 13. Between 8 and 9, yeah, it defently is. And testing everything under 8, 11 and the-last-release is good enough, isn't it?

**Comment by usersxx** [comment]
Actually I also think this ports should be merged with Openjdk Metaport without old versions now by name of openjdk-java

**Comment by usersxx** [comment]
Actually I also think this ports should be merged with Openjdk Metaport without old versions now by name of openjdk-java [Oracle owns java officially and the website from which it is downloaded is at sidebar of openjdk website (openjdk.java.net) as JDK GA/EA builds]. I also feel more subports can be added to this metaport. Some suggested jdk that can be added are :
Bell-Soft (https://bell-sw.com/java)
SAP machine (https://sap.github.io/SapMachine/)
Amazon Corretto (https://aws.amazon.com/corretto/)

**Comment by usersxx** [comment]
@breun and @catap. So should this pull request be closed ?

**Comment by usersxx** [comment]
Ok

**Comment by usersxx** [comment]
Ok

**Comment by usersxx** [comment]
I might open new pull request

**Comment by usersxx** [comment]
I have built a new pull request [https://github.com/macports/macports-ports/pull/13638](url)

**Pull request closed without merging**
