### PR TITLE
ntpsec: update to 0.9.7

### PR DESCRIPTION
**Pull request by lbschenkel**
The 'crypto' variant has been retired since it was made mandatory in upstream.
The previous patches no longer apply and have been removed as well.

Note that this port does not build on any version earlier than 10.12 (https://trac.macports.org/ticket/53928), I'm going to contact upstream to see if there's anything that can be done about it.

### CODE REVIEW

**Comment by mojca** [comment]
This has already been fixed in 10cd23b5516e44f55f7649e4859ddb06cca88e92.

I guess @ryandesign didn't even see this PR.

**Comment by lbschenkel** [comment]
@ryandesign should I ping you next time for a quicker review?

**Comment by ryandesign** [comment]
I don't look at PRs because I don't know how to test and merge them. If you'd like to submit PRs, please ask another MacPorts committer to review and merge them.

**Comment by mojca** [comment]
What about the ports that you maintain?

You can also download a patch file directly and then someone else can merge the change, but it would be nice to get your approval.

**Comment by ryandesign** [comment]
Fine, I do sometimes look at PRs, but because I don't know how to deal with them I find them inconvenient.

**Comment by lbschenkel** [comment]
I'm a bit confused about the procedure here. I'm the maintainer of this port. Even though I deliberately added the "openmaintainer" when I submitted it and I absolutely don't mind at all that version bumps can be done without my involvement, isn't it still the procedure that you should check Trac and opened PRs here without doing changes to ports? Ultimately I submitted this almost a month ago and ended up wasting the work.

@ryandesign: Don't get me wrong, I would like you to thank you a lot for stepping in and helping me dealing with upstream.

**Comment by mojca** [comment]
Yes, this is still the procedure. I actually hope that @l2dy's project will mitigate some of the initial problems we are facing with migration to GitHub. For example, it was me who added the labels, but I didn't realise you were also the maintainer, for example, and forgot to add that label to make the ticket stand out more.

(I admit that I don't always check for all the Trac tickets of nonmaintained ports. Searching for ports in GitHub might be even more annoying at the moment.)

**Comment by lbschenkel** [comment]
That's fine, to me it's more important that it gets updated than I'm the one updating it — but I have to admit that this time I felt a bit annoyed.

**Comment by ryandesign** [comment]
In this case, I saw a port that was submitted in February, was not merged until April, meanwhile a new version had already been released in March. When the port was merged in April, we noticed it didn't build on anything earlier than Sierra. I filed a MacPorts ticket, you reported it upstream, upstream said it's not their problem. I didn't see the result of that ticket until May, at which point nothing had been done about it for weeks, so I took it upon myself to reopen the dialog with upstream and find the problem.

It was in that process that I found that a new version was available, and that the old version had a bug that caused the error message to be wrong, which may have contributed to upstream's confusion. Once I figured that out, I updated the port, partly to verify that that didn't fix the build failure on older systems. It didn't occur to me at that moment to check the GitHub pull requests. As I've said elsewhere, I check PRs infrequently because I don't know how to use them. There are many other MacPorts developers who have the permission to merge PRs and are much more comfortable with handling them than I am, so insofar as I thought about it at all, I assumed that if you had submitted an update, someone else would have merged it by now. The fact that this hadn't happened made me assume you weren't actively looking after the port; sorry I jumped to the wrong conclusion.

I do often check Trac tickets, and sometimes GitHub PRs, before modifying a port, but not always. The fact that we now have two places to check makes it twice as difficult. It just seems that if checking both places becomes mandatory before any work can be done on a port, that will reduce the likelihood that I will spend my free time working on MacPorts.

**Comment by lbschenkel** [comment]
I'm sure it was simply an oversight. Once again, I thank you very much for helping me with upstream. I wouldn't be able to move it forward since I don't have any pre-10.12 box so I could troubleshoot and argue for a reopening of the ticket.

Having said that, it's a bit weird that there is a procedure that I'm supposed to follow but others argue that they don't need to — because the reverse argument could be made that if maintainers have to sit on patches for a month and others feel that they can just "jump the queue" because they have direct commit privileges, then the former could feel less compelled to spend their time being maintainers since the free time their spent can simply be wasted. I feel that doing a quick search on PRs and a friendly ping is not really asking for too much.

Back to this case, I am sure nothing was done on purpose and there's no ill feelings from my part. It was just an unfortunate combination of circumstances.

**Pull request closed without merging**
