### PR TITLE
Update dvisvgm port to v. 2.1.

### PR DESCRIPTION
**Pull request by RasmusWernerLarsen**
This is an update of the dvisvgm portfile to build 2.1.

Also this disables WOFF support, since this doesn't seem to compile on OSX currently.

I'll be looking to getting the WOFF support working in any case, but the current state should still be an improvement to the current version.

Trac ticket: https://trac.macports.org/ticket/53235

### CODE REVIEW

**Comment by mojca** [comment]
I din't test this commit, but from what I know dvisvgm now requires C++11, so a bit of extra code might be needed to handle pre-10.9 systems. And there were lots of font-related compilation problems (related to locale_t etc.), but maybe you got rid of them with `--disable-woff`. Someone came up with a set of naive patches to build dvisvgm on Mac, they are now "being processed" upstream.

So:
* someone needs to test this on <10.9 (absolutely necessary)
* I would probably prefer to wait for an upstream fix for the build problems unless users really need to get the latest version of dvisvgm asap (that's debatable)

**Comment by RasmusWernerLarsen** [comment]
Thank you for quick feedback, haven't contributed to MacPorts before, so need to figure out how you do stuff.

I have an issue with the Author and he just sent me a working patch that fixes the issue with the woff font handling (it's basically a libc++ vs. libstdc++ issue).
https://github.com/mgieseki/dvisvgm/issues/65

In any case, I'll discuss with him, whether I should update the port with the patch or when he'll do a release.

As for getting it tested on 10.8 or earlier... I'll see if I can dig that up.

**Comment by mojca** [comment]
Let's just wait for the release of 2.1.1 then which should happen in the next few days.

If you are not familiar with C++11 issues on older macs, it might make more sense that one of us does some testing anyway. The only question is whether to allow building on libc++ systems exclusively (this is easily done by simply including the c++11 portgroup) or to allow building it on older boxes with libstdc++. The second is only possible if no other C++ interfaces to dependencies are being used (or with some tricks that are currently being tested by MarcusCalhoun-Lopez).

**Comment by RasmusWernerLarsen** [comment]
@mojca - Just updated with a 2.1.1 build that includes the fix.

This builds as expected on Sierra and it's nice and clean, default configure flags and everything. 
I hope someone here can help with testing on older, (eg. libstdc++) releases.

**Comment by tobypeterson** [comment]
Merged. If it doesn't build on 10.8 or earlier, someone can deal with that.

**Comment by mojca** [comment]
@tobypeterson (as well as @RasmusWernerLarsen): please squash commits next time. It's not too useful to have lots of iterations of improvements (in this case updating the port twice) when only a single change is visible to everyone anyway.

I'll add the `cxx11` PortGroup next, even though the first attempt of the build fails for me in an unrelated way:
```
Making all in doc
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
make[2]: Entering directory `/path/to/dvisvgm-2.1.1/doc'
if [ `type -p asciidoc` ]; then \
		asciidoc -a icons -a 'iconsdir=.' -a badges -a 'revnumber=2.1.1' --unsafe -bdocbook -dmanpage -o dvisvgm-man.xml dvisvgm.txt; \
		sed -i "s#\(</refmeta>\)#<refmiscinfo class='date'></refmiscinfo>\n\1#" dvisvgm-man.xml; \
	fi
sed: 1: "dvisvgm-man.xml": extra characters at the end of d command
make[2]: *** [dvisvgm-man.xml] Error 1
```

**Comment by mojca** [comment]
Also, `Correct the master site.` is a suboptimal commit message for anyone browsing through the complete MacPorts history rather than through individual ports.

Each commit should in principle start with `portname: <what you did>`. This is mainly meant for @tobypeterson (we cannot expect each new contributor to know all of our conventions.)

**Pull request merged**
