### PR TITLE
opencv4: update to 4.5.2

### PR DESCRIPTION
**Pull request by mascguy**
#### Description

* Update opencv4 to 4.5.2
* remove check_macro patch; no longer needed for 4.5.2

###### Type(s)
- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.12.6 16G2136
Xcode 9.2 9C40b

macOS 10.13.6 17G14019
Xcode 10.1 10B61

macOS 10.14.6 18G103
Xcode 11.3.1 11C505

macOS 10.15.6 19G2021
Xcode 12.0 12A7209

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Reviewers: It appears that `gmic` is not currently building properly against `opencv4`, so the former doesn't need a rev-bump. (In short, `gmic` isn't finding `opencv4` during the build process, so there's presently no dependency.)

However, I'm in the process of opening a ticket to track that, along with investigating what the problem is.

**Comment by mascguy** [comment]
FYI, `gmic` no longer enables OpenCV support by default, without an explicit configure option.

Tracked by ticket: [issue 62738](https://trac.macports.org/ticket/62738)

Currently testing out a fix, with a new pull request to follow shortly.

**Comment by mascguy** [comment]
> FYI, `gmic` no longer enables OpenCV support by default, without an explicit configure option.
> 
> Tracked by ticket: [issue 62738](https://trac.macports.org/ticket/62738)
> 
> Currently testing out a fix, with a new pull request to follow shortly.

Pull request created: [PR 10771 - gmic: enable OpenCV usage](https://github.com/macports/macports-ports/pull/10771)

**Comment by mascguy** [comment]
Revised gmic-related comment, as that port will no longer have a hard-coded opencv4 version once [PR 10771 - gmic: enable OpenCV usage](https://github.com/macports/macports-ports/pull/10771) is merged.

**Comment by mascguy** [comment]
FYI, Marius committed my gmic changes separately, so that PR is no longer necessary.

So we're good-to-go here.

**Review by cjones051073 — CHANGES_REQUESTED** [review]
Could you just resolve the lint nitpick warnings, by adding the request new lines after a some PortGroups

**Comment by mascguy** [comment]
> Could you just resolve the lint nitpick warnings, by adding the requested new lines after a some PortGroups

@cjones051073 - Done; change pushed.

**Pull request merged**
