### PR TITLE
ipopt: update to 3.14.12

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [x] bugfix

###### Tested on

macOS 12.6 21G115 arm64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
And CI had failed. Seems that https://github.com/macports/macports-ports/pull/16851 fixed it.

**Comment by catap** [comment]
@reneeotten may I ask you to review this trivial PR to my port? Thanks.

**Comment by reneeotten** [comment]
CI still fails so please fix that first and I can look into merging it.

**Comment by catap** [comment]
@herbygillot, @mascguy may I ask you to review this very old PR?

**Pull request merged**
