### PR TITLE
gdal: do not opportunistically link to armadillo, revbump

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

@Veence @nilason 
Or we should ensure it does not link by default to `armadillo` and then make a variant.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Currently it links:
```
36-25% otool -L /opt/local/lib/libgdal.35.dylib
/opt/local/lib/libgdal.35.dylib:
	/opt/local/lib/libgdal.35.dylib (compatibility version 35.0.0, current version 35.3.9)
	/opt/local/lib/libMacportsLegacySupport.dylib (compatibility version 1.0.0, current version 1.2.99)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.3.1)
	/opt/local/lib/libcurl.4.dylib (compatibility version 13.0.0, current version 13.0.0)
	/opt/local/lib/libxml2.2.dylib (compatibility version 15.0.0, current version 15.7.0)
	/opt/local/libexec/openssl3/lib/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	/opt/local/libexec/openssl3/lib/libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	/opt/local/lib/libdeflate.0.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/liblz4.1.dylib (compatibility version 1.0.0, current version 1.9.4)
	/opt/local/lib/libblosc.1.dylib (compatibility version 1.0.0, current version 1.21.5)
	/opt/local/lib/libjpeg.8.dylib (compatibility version 8.0.0, current version 8.3.2)
	/opt/local/lib/libwebp.7.dylib (compatibility version 9.0.0, current version 9.9.0)
	/opt/local/lib/proj9/lib/libproj.25.dylib (compatibility version 25.0.0, current version 25.9.4)
	/opt/local/lib/libarmadillo.12.dylib (compatibility version 12.0.0, current version 12.8.4)
	/opt/local/lib/libqhull_r.8.0.dylib (compatibility version 8.0.0, current version 8.0.2)
	/opt/local/lib/libpng16.16.dylib (compatibility version 60.0.0, current version 60.0.0)
	/opt/local/lib/libzstd.1.dylib (compatibility version 1.0.0, current version 1.5.6)
	/opt/local/lib/libbrunslienc-c.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libbrunslidec-c.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libaec/lib/libaec.0.dylib (compatibility version 2.0.0, current version 2.3.0)
	/opt/local/lib/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/opt/local/lib/libpcre2-8.0.dylib (compatibility version 13.0.0, current version 13.0.0)
	/opt/local/lib/libspatialite.8.dylib (compatibility version 10.0.0, current version 10.0.0)
	/opt/local/lib/librasterlite2.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/opt/local/lib/libexpat.1.dylib (compatibility version 11.0.0, current version 11.2.0)
	/opt/local/lib/libgeos_c.1.dylib (compatibility version 1.0.0, current version 1.18.1)
	/opt/local/lib/libiconv.2.dylib (compatibility version 9.0.0, current version 9.1.0)
	/opt/local/lib/libgcc/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.32.0)
	/opt/local/lib/libgcc/libgcc_s.1.1.dylib (compatibility version 1.0.0, current version 1.1.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 117.0.0)
```

Which leaves it broken upon a recent update of `armadillo`:
```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/sf/libs/sf.so':
  dlopen(/opt/local/Library/Frameworks/R.framework/Versions/4.4/Resources/library/sf/libs/sf.so, 6): Library not loaded: /opt/local/lib/libarmadillo.12.dylib
  Referenced from: /opt/local/lib/libgdal.35.dylib
  Reason: image not found
```

**Comment by nilason** [comment]
Better to add `GDAL_USE_ARMADILLO=OFF `, see
https://gdal.org/development/building_from_source.html#armadillo.

**Comment by barracuda156** [comment]
@nilason Done

**Review by nilason — APPROVED** [review]

**Comment by barracuda156** [comment]
@nilason @Schamschula Could we merge this?

**Comment by nilason** [comment]
I’m good with it.

**Comment by barracuda156** [comment]
@reneeotten @pmetzger Bump, this is a fix.

**Comment by reneeotten** [comment]
there appear to be a few other PRs for gdal in the queue. This should be done together with the proposed update as not to unnecessarily do rebuilds.

**Comment by barracuda156** [comment]
@reneeotten If the PR is gonna me merged today, then sure.

@nilason Feel free to borrow my commits from here and close this PR then.

If that gonna take time, then this rather be merged first.

**Comment by barracuda156** [comment]
@reneeotten If you refer to my PR with a fix for 32-bit platforms, that one will _not_ trigger any rebuilds.

**Comment by reneeotten** [comment]
As I said, this should be done together with the update of the port. The other PR is fine as I understand that that will not trigger a rebuild. 

As usual, there is really no urgency with any of this - it could perhaps be merged today,  tomorrow, or whenever @nilason has found the time to combine the update PR by @Dave-Allured and this one.

**Comment by Dave-Allured** [comment]
@barracuda156 for expediency I merged your armadillo changes into my new update PR #24695.  Okay with you?  Please review that new PR.

**Comment by barracuda156** [comment]
Closing in favor of https://github.com/macports/macports-ports/pull/24695

**Pull request closed without merging**
