### PR TITLE
log4cxx: update to 1.1.0

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

This is a big update. Move to Cmake build system, significant changes to patches. Feedback welcomed :)

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
I don't see why this should be marked as "draft".

**Comment by mascguy** [comment]
> I don't see why this should be marked as "draft".

We need to do some additional validation against dependents - whether ABI has changed, potential breaking APi changes, etc. Please don't merge until I've helped Sergey with some legwork on this.

**Comment by barracuda156** [comment]
@mascguy Thank you!

**Comment by mascguy** [comment]
Upstream is now at v1.1, so this needs to be updated.

**Comment by barracuda156** [comment]
@mascguy I will try updating now.

**Comment by barracuda156** [comment]
@mascguy So it failed on some dependency:
```
Installing dependency (7 of 15) 'libzookeeper' with variants '' ... [FAIL]
```
I.e. unrelated to `log4cxx` update.

**Comment by mascguy** [comment]
> @mascguy So it failed on some dependency:
> 
> ```
> Installing dependency (7 of 15) 'libzookeeper' with variants '' ... [FAIL]
> ```
> 
> I.e. unrelated to `log4cxx` update.

Yep, that port is broken, which prevents building of `jubatus`. So I dropped the rev-bump for that, as it's pointless.

**Comment by mascguy** [comment]
You were missing several deps, but no worries... I pushed a fix.

**Review by mascguy — APPROVED** [review]
Tested and validated locally, and looks good. Merging.

**Pull request merged**
