### PR TITLE
upt, upt-macports: Update for recursive packaging support

### PR DESCRIPTION
**Pull request by Korusuke**
#### Description

py-upt-macports: update includes recursive packaging feature
upt : update to version 0.10.3

###### Tested on

Ubuntu 18.04

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
Error is:

```
Executing:  cd "/opt/local/var/macports/build/_Users_vsts_agent_2.154.3_work_1_s_sysutils_upt/upt/work/upt-0.10.2" && /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 setup.py --no-user-cfg build 
DEBUG: system:  cd "/opt/local/var/macports/build/_Users_vsts_agent_2.154.3_work_1_s_sysutils_upt/upt/work/upt-0.10.2" && /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 setup.py --no-user-cfg build 
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from wheel.bdist_wheel import bdist_wheel
ModuleNotFoundError: No module named 'wheel'

```

**Comment by mf2k** [comment]
So I 'm guessing upt is missing a build dependency on py-wheel.

**Comment by mojca** [comment]
> So I 'm guessing upt is missing a build dependency on py-wheel.

I would say that the upstream `upt` is buggy and fails to declare dependency in a proper way, so that the automatic update of the `Portfile` would work as expected :) :) :)

**Comment by Steap** [comment]
Oops. It should be better in upt 0.10.3 :)

**Pull request merged**
