### PR TITLE
libqalculate:  update to version 2.4.0

### PR DESCRIPTION
**Pull request by jjstickel**
qalculate-gtk:  update to version 2.4.0

* update to version 2.4.0
* add size to checksum

###### Type(s)

- [x] update

###### Tested on
macOS 10.12.6 16G1314
Xcode 9.0 9A235

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
I wonder if you would mind if I took this update opportunity to add on the app icon I have been working on for this port for you? I'll send you the bits.

**Comment by pmetzger** [comment]
Looks like the build failed only because of a Travis timeout. I'm therefore going to pull this.

**Comment by pmetzger** [comment]
Merged. Thank you!

**Comment by jjstickel** [comment]
@kencu, I'm amenable to adding an app icon to qalculate-gtk. Looks like this was merged, already, though, but we can do it separately.

**Comment by kencu** [comment]
I'll put up another PR with that in place. I thought of this port exactly when I enhanced the app PortGroup :>

**Pull request merged**
