### PR TITLE
faust: update to 2.5.17

### PR DESCRIPTION
**Pull request by agraef**
#### Description
Update to latest stable release from Github at https://github.com/grame-cncm/faust/releases/tag/2.5.17.

###### Tested on
macOS 10.12.6 16G1212
Xcode 9.2 9C40b

### CODE REVIEW

**Comment by agraef** [comment]
2.5.17 just came out, so please hold on while I'll update this PR accordingly!

**Comment by agraef** [comment]
2.5.17 just came out, so please hold on while I'll update this PR accordingly!

**Comment by agraef** [comment]
Updated to faust 2.5.17, should be ready to go in now.

**Comment by pmetzger** [comment]
You left a "#fixme" at the bottom of your portfile...

**Comment by agraef** [comment]
@pmetzger yes that's because I'm not sure whether and how the release livecheck works with releases on GH. So I left that in there as a reminder to check that myself at some point, or leave it up to @ryandesign or to anyone who knows MP much better than I do.

**Pull request merged**
