### PR TITLE
py-shiboken: add py39 subport

### PR DESCRIPTION
**Pull request by erikbs**
#### Description

Adds a py39 subport and a patch that allows it to build successfully.

Since Python 3.9 removed `tp_print` (deprecated since 3.8), a patch was necessary to build `py39-shiboken` successfully. According to the Python docs, `tp_print` has been unused since Python 3.0 anyway.

(Originally part of #8865.)

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.9.5 13F1911
Xcode 6.2 6C131e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by erikbs** [comment]
According to the Azure log files, the build completes successfully, while Bash exits “with code '1'” in when running the tests. The checks probably fail because there are no tests, at least `sudo port test py39-shiboken` fails locally because of that:

```
Error: Failed to test py39-shiboken: py39-shiboken has no tests turned on. see 'test.run' in portfile(7)
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_python_py-shiboken/py39-shiboken/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port py39-shiboken failed
```

I do not know how to solve this. Putting `test.run no` in the Portfile did not work.

**Comment by ryandesign** [comment]
`test.run no` is the default; specifying it again would change nothing.

Our CI infrastructure does not run the tests.

The CI failures are unrelated to your PR. See https://trac.macports.org/ticket/59673.

You've added a patch to all python versions. Wouldn't that patch change how the existing py3x ports build? If so, shouldn't their revisions be increased?

**Comment by erikbs** [comment]
This patch was inspired by #8952. Again the `tp_print` property is not used by Python 3.x ([source](https://docs.python.org/3/c-api/typeobj.html)), so it should not matter whether the property is set or not. In 3.8 it was deprecated and in 3.9 it was removed, breaking libshiboken (which has not been updated in 5+ years, it seems). In 3.9 the slot even seems to have been reused for new functionality (`tp_vectorcall_offset`).

The function that my patch affects does not have any other such version checks, but elsewhere in the files there are a few of them. In this project they test using `#ifndef IS_PY3K` instead of `#if PY_VERSION_HEX < 0x03000000`, so I followed the pattern and used that.

While the code is changed slightly, the functionality should not. I do not know if it is necessary to increase the revision, but I will of course do it if that is preferred.

**Comment by ryandesign** [comment]
Your patch changes how the program behaves. Prior to your change, the program would initialize `type->tp_print`. After your change, it will not initialize `type->tp_print` for python 3 versions. Because you are changing what the program does, or if you had changed the contents of the installed files in any other way, increasing the revision would be appropriate.

Also, I would want to know if this patch came from the developers of this software, and if not, if you have sent the patch to them. Including a URL where you got it from or where you submitted is customary.

**Comment by erikbs** [comment]
I see, I increased the revision to 2 with the last commit. Shiboken has not been updated [since 2015](https://github.com/pyside/Shiboken/commits/master), so the patch is self made. I have not sent it to the developers yet, but when you mention it that is actually a good idea. I must stress that I do not use `py-shiboken` myself, my motivation for submitting this update was to resolve the last missing `py-matplotlib` dependencies.

**Pull request merged**
