### PR TITLE
Update ruby/ruby-build to v20230222

### PR DESCRIPTION
**Pull request by halostatue**
#### Description

* Update ruby-build to 20230222 release

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 13.2.1 22D68 arm64
Xcode 14.2 14C18

###### Verification

Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
  -  **`sudo port -vst install` does not work on macOS 13**
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by halostatue** [comment]
I am willing to become a co-maintainer of ruby-build.

**Comment by herbygillot** [comment]
> I am willing to become a co-maintainer of ruby-build.

Go ahead and add a second commit adding yourself to the maintainers list:

```
maintainers         {mojca @mojca} \
                    {domain.com:you @halostatue} \
                    openmaintainer
```

**Comment by herbygillot** [comment]
Also the format of a commit should be: `<port>: update to x.x.x`, or `<port>: <description>`.

The current commit's commit message should be `ruby-build: update to v20230222`.

And commit adding yourself as co-maintainer should have a message that looks like `ruby-build: add @halostatue as co-maintainer`.

**Comment by halostatue** [comment]
I fixed the format of the first commit and added the second commit as requested.

**Comment by herbygillot** [comment]
> I fixed the format of the first commit and added the second commit as requested.

OK thanks. We'll leave it open a little longer to give @mojca time to review.

**Comment by herbygillot** [comment]
Merging due to maintainer timeout.

**Pull request merged**
