### PR TITLE
py-flake8: update to 3.7.7

### PR DESCRIPTION
**Pull request by reneeotten**
###### Tested on

macOS 10.14.3 18D42
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM

**Comment by pmetzger** [comment]
> Looks ok, but requires maintainer's approval, at least in the first three days.

Just as an aside, there are a lot of maintainers who basically never respond to Github notifications. I wonder if we shouldn't be more aggressive about declaring them to have abandoned their ports.

**Comment by reneeotten** [comment]
I have further update this to version 3.7.7. Once the Azure pipelines is happy with it, can this get merged with the maintainer-timeout? There has been no response in the last four days from @petrrr and I am not expecting anything now either...

**Comment by pmetzger** [comment]
Merged. You might want to file a port abandoned ticket. I think up until now, we were lax at filing them, as it mattered less when ports were openmaintainer. Now, though, I think we should be more aggressive about it.

**Pull request merged**
