### PR TITLE
rtags: clang-3.8 has been removed and replaced by clang-6.0

### PR DESCRIPTION
**Pull request by egorenar**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65
Xcode 9.4.1 9F2000

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
I would change the commit message to:

```
rtags: update dependency to clang-6.0
```

When you do this, please update the message and force push to your branch so there is only one commit.

**Comment by egorenar** [comment]
done.

**Comment by pmetzger** [comment]
Oh, and I forgot something, this likely needs a version bump because the library dependency changed. Can you add `revision 1` after the `github.setup` line? So sorry, I should have mentioned this earlier. (You'll want to squash those changes, too.)

**Comment by egorenar** [comment]
done.

**Comment by pmetzger** [comment]
Merged. Thanks, @egorenar!

**Pull request merged**
