### PR TITLE
Add spice_protocol variant to qemu port

### PR DESCRIPTION
**Pull request by alxtplv**
#### Description
Qemu got its own implementation of the spice agent protocol (ui/vdagent.c)
It only needs spice-protocol port, spice-server port (and all it's dependencies) is not needed.
So, let's separate those variants.

This PR does:
- add +spice_protocol variant to qemu
- change +spice variant to depend on +spice_protocol

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.6.1 21G217 arm64
Xcode 14.0.1 14A400

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM but this is @raimue's port...

**Review by raimue — APPROVED** [review]
Thank you for preparing this pull request. Having both as separate variants seems reasonable.

I think we can omit a revision bump for this, as the resulting featureset for existing installations with the +spice variant will be the same.

**Comment by raimue** [comment]
Please follow [CommitMessages](https://trac.macports.org/wiki/CommitMessages) for the commit message format.

**Comment by raimue** [comment]
As this was the only issue, I applied the patch in 8f516dbf51c611f30471fe8f46ccff4a0cdad69f with an updated commit message. Thanks again for the pull request!

**Comment by alxtplv** [comment]
> Please follow [CommitMessages](https://trac.macports.org/wiki/CommitMessages) for the commit message format.

I'm sorry for the wrong commit message format

**Comment by raimue** [comment]
> > Please follow [CommitMessages](https://trac.macports.org/wiki/CommitMessages) for the commit message format.
> 
> I'm sorry for the wrong commit message format.

@alxtplv No need to be sorry! That is just one small part of the submission process that needs learning. Keep up the good work! :smile:

**Pull request closed without merging**
