### PR TITLE
OpenEXR, Imath: split Portfiles, removed unnecessary code, fix on old systems

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
1. Instead of flags we could patch sources: https://github.com/macports/macports-ports/compare/master...barracuda156:macports-ports:openexr (here everything needed to fix build).
Specifically `__STDC_FORMAT_MACROS` for `openexr`: https://github.com/AcademySoftwareFoundation/openexr/pull/1406

2. Condition for `libdispatch` fallback should incorporate `ppc` on 10.6 (Rosetta and native, whatever):
```
if {${os.major} < 10 || (${os.major} == 10  && ${build_arch} eq "ppc")}  {
```
`libdispatch` is not supported for `ppc`.

3. Big question is whether posix semaphores are fully supported on Darwin. If not, then the fallback should be to posix compat code (see my patches): https://github.com/AcademySoftwareFoundation/openexr/issues/1405

4. Finally, we have this problem on Big endian: https://github.com/AcademySoftwareFoundation/openexr/issues/1404

**Comment by barracuda156** [comment]
> This seems to be the biggest issue.
> Hopefully, it can be solved without too many difficulties.

I agree, that is the biggest concern. Hopefully upstream gonna help sorting that – I have no idea what is going so wrong there.

**Comment by barracuda156** [comment]
This is quite interesting: https://github.com/AcademySoftwareFoundation/openexr/issues/1404#issuecomment-1545793388

**Comment by mascguy** [comment]
Should we go ahead and merge this, and update with additional fixes for PPC later?

**Comment by barracuda156** [comment]
> Should we go ahead and merge this, and update with additional fixes for PPC later?

Why not, I will add a preliminary PPC fix advised by upstream in a follow-up PR then.

**Comment by barracuda156** [comment]
Well, anyway, I will that in a while, after multiple ICU-affected ports are rebuilt.

**Pull request merged**
