### PR TITLE
py-pytorch/py-onnx/py-nbval/py-tabulate: add python 3.9 subports; update py-onnx to v1.8

### PR DESCRIPTION
**Pull request by mascguy**
#### Description

* py-pytorch/py-onnx/py-nbval/py-tabulate: add python 3.9 subport.
* py-onnx: update to v1.8; remove defunct patch; remove redundant cmake build dependency.
* py-pytorch: add missing dependency on py-click.

###### Type(s)
- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.12.6 16G2136
Xcode 9.2 9C40b

macOS 10.13.6 17G14019
Xcode 10.1 10B61

macOS 10.14.6 18G103
Xcode 11.3.1 11C505

macOS 10.15.6 19G2021
Xcode 12.0 12A7209

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
at this point in time, I am assuming you are building these, running the test suite if any, and generally making sure they work before opening PRs for them.

**Comment by kencu** [comment]
Whoa -- hold the phone -- my system says this a "Draft"?

**Comment by mascguy** [comment]
> Whoa -- hold the phone -- my system says this a "Draft"?

Yep, this is a placeholder, while I continue testing.

**Comment by mascguy** [comment]
> at this point in time, I am assuming you are building these, running the test suite if any, and generally making sure they work before opening PRs for them.

Absolutely, as long as they aren't in draft status.  ;-)

**Comment by mascguy** [comment]
But yes, normally I won't even open a draft PR, until all such testing is done. (Not only to avoid wasting everyone's time, but also to avoid impacting the CI system.)

This is one of the rare exceptions, as I had already tested these changes out as part of my PR for opencv and opencv4. But for whatever reason - to simplify that PR, I suppose? - I didn't want to include these. Now that all of that work has been merged, we're ready for this one.

**Comment by reneeotten** [comment]
@mascguy this doesn't seem to be fully tested since there are missing dependencies for the py39 subport. Please check the CI logs.

**Comment by mascguy** [comment]
> @mascguy this doesn't seem to be fully tested since there are missing dependencies for the py39 subport. Please check the CI logs.

Yes, I'm seeing some CI failures which aren't occurring locally. That's why this PR is still marked as a Draft, which blocks folks from merging it.

In any case, I'm in the process of rebuilding these ports within virgin VMs, to see what's happening. Unfortunatetly CI is rebuilding all of the unchanged subports, rather than just the two new Python 3.9 additions. And that's a huge headache...

**Comment by reneeotten** [comment]
> In any case, I'm in the process of rebuilding these ports within virgin VMs, to see what's happening. Unfortunatetly CI is rebuilding all of the unchanged subports, rather than just the two new Python 3.9 additions. And that's a huge headache...

the missing dependencies are `test` dependencies so building the port itself will work fine (but of course running tests will fail).

**Comment by mascguy** [comment]
> the missing dependencies are `test` dependencies so building the port itself will work fine (but of course running tests will fail).

This is my first Python-related PR, so I'd be disappointed if there weren't a few surprises.  :-)

So, are you saying that the test failures are expected? Or are additional changes needed, either in these portfiles, or elsewhere... ?

**Comment by reneeotten** [comment]
> > the missing dependencies are `test` dependencies so building the port itself will work fine (but of course running tests will fail).
> 
> This is my first Python-related PR, so I'd be disappointed if there weren't a few surprises. :-)
> 
> So, are you saying that the test failures are expected? Or are additional changes needed, either in these portfiles, or elsewhere... ?

What I am saying is that you should do ```lint``` on the port locally and see if all dependencies are available:

```
 % port lint --nitpick subportof:py-onnx
--->  Verifying Portfile for py36-onnx
Warning: Dependency path:bin/cmake:cmake specified multiple times in depends_build
--->  0 errors and 1 warnings found.
--->  Verifying Portfile for py37-onnx
Warning: Dependency path:bin/cmake:cmake specified multiple times in depends_build
--->  0 errors and 1 warnings found.
--->  Verifying Portfile for py38-onnx
Warning: Dependency path:bin/cmake:cmake specified multiple times in depends_build
--->  0 errors and 1 warnings found.
--->  Verifying Portfile for py39-onnx
Error: Unknown dependency: py39-nbval
Error: Unknown dependency: py39-tabulate
Warning: Dependency path:bin/cmake:cmake specified multiple times in depends_build
--->  2 errors and 1 warnings found.
```

this is the same as what the CI told you, namely that `py39-nbval` and `py39-tabulate` are not present in MacPorts currently. These are listed in the Portfile as `depend_test`, so building the port will work fine but you cannot run the tests because then it has missing dependencies. 

So what you need to do in this PR is add the py39 subports to py-nbval and py-tabulate as well (and possibly -recursively- to all their dependencies as well).

The ```Warning: Dependency path:bin/cmake:cmake specified multiple times in depends_build``` is because the `cmake` PG already adds this, so you don't need to do this again in the Portfile.

**Comment by reneeotten** [comment]
I also notice that the latest upstream version is 1.8.0, so the port could be updated at the same time (also the license specification is incorrect, it should be `MIT`). So if you're up for it there would be some more work that can be done ;)

**Comment by mascguy** [comment]
> I also notice that the latest upstream version is 1.8.0, so the port could be updated at the same time (also the license specification is incorrect, it should be `MIT`). So if you're up for it there would be some more work that can be done ;)

Sure, happy to help! Does the license fix only apply to `py-onnx`?

**Comment by mascguy** [comment]
As for the two missing test-related dependents, those would have been found before changing the status of this port to ready-for-review. Running tests, along with the lint check, are usually the last things I do before blessing a PR. Going forward, however, I'll be taking care of those earlier in the process...

**Comment by mascguy** [comment]
Updated py-onnx to v1.8, and changed license to MIT.

Since this is now a version upgrade, will we also want to rev-bump dependent py-torch?

**Comment by mascguy** [comment]
I need to call it a night on this, as it's nearly 12:30am here on the east coast.

Leaving the status of this PR as Draft, as I still have to rebuild all of these across 10.12 through 10.15. Once that's been done, I'll update the status to ready-for-review.

And with any luck, perhaps the CI tests will pass overnight, assuming I didn't miss anything else...

**Comment by mascguy** [comment]
Testing across macOS 10.12 through 10.15 complete, including test runs.

Marking this PR as ready-for-review.

**Comment by reneeotten** [comment]
thanks @mascguy for your work on this! 

A few remaining comments/questions:
- ideally there should be one commit per port and have a commit message describing the changes
- why is a revision bump for py-torch necessary, is that port (reported) broken after you upgrade py-onnx?
- there is still the `port lint` message about duplicated cmake dependency; you likely can/should remove the `path:bin/cmake:cmake` from `depends_lib` in the py-onnx port.

**Comment by mascguy** [comment]
> ideally there should be one commit per port and have a commit message describing the changes

I can certainly do that. However, given the inter-dependencies here, wouldn't it make more sense for one squashed, combined commit?

> why is a revision bump for py-torch necessary, is that port (reported) broken after you upgrade py-onnx?

Since we're upgrading py-onnx, shouldn't we rev-bump py-pytorch? Even if there's supposed ABI compatibility for py-onnx, do we really want to trust that?

> there is still the `port lint` message about duplicated cmake dependency; you likely can/should remove the `path:bin/cmake:cmake` from `depends_lib` in the py-onnx port.

Initially I didn't want to make too many changes, but fair enough... change committed.

Your thoughts?

**Comment by reneeotten** [comment]
> > ideally there should be one commit per port and have a commit message describing the changes
> 
> I can certainly do that. However, given the inter-dependencies here, wouldn't it make sense to have one squashed, combined commit?

Not really, there is no problem in having separate commits in the same PR - which is certainly needed because they are interdependent. 

If you want you can combine the py-nbval and py-tabulate changes and have the commit message something like:
`py-{nbval,tabulate}: add py39 subport`

but for `py-onnx` it should certainly be a separate one with a commit message like:
`py-onnx: update to 1.8.0, add py39 subport` and then in the header:
 ```
- update license to MIT
- remove duplicated cmake dependency
```

> > why is a revision bump for py-torch necessary, is that port (reported) broken after you upgrade py-onnx?
> 
> Since we're upgrading py-onnx, shouldn't we rev-bump py-pytorch? Even if there's supposed ABI compatibility for py-onnx, do we really want to trust that?

Sure, but I would assume that py-pytorch does not link directly to py-onnx (i.e., `onnx_cpp2py_export.cpython-38-darwin.so`), right? It probably just uses the py-onnx library somewhere and that will just work as-is I *think*.

**Comment by mascguy** [comment]
> If you want you can combine the py-nbval and py-tabulate changes and have the commit message something like:
> `py-{nbval,tabulate}: add py39 subport`
> 
> but for `py-onnx` it should certainly be a separate one with a commit message like:
> `py-onnx: update to 1.8.0, add py39 subport` and then in the header:
> 
> ```
> - update license to MIT
> - remove duplicated cmake dependency
> ```

Okay, you've convinced me... that makes more sense. I'll try to push those changes tonight, so that we don't have to wait for CI tomorrow.

**Comment by mascguy** [comment]
I'll finish this tomorrow, it's been a good - but absolutely exhausting - day.

**Comment by mascguy** [comment]
Commits now separate, per prior discussion. Also added a py39 subport for py-pytorch, and removed rev-bump.

Renee, when you get a chance, take a look and let me know what you think.

**Comment by mascguy** [comment]
Renee/@cjones051073, while py-pytorch's new py39 subport built and installed successfully, executing the binaries uncovered an issue: Module py39-click is required at runtime, but for whatever reason, it's not being installed by default. And the result is a runtime error.

Installing py39-click solves that issue, and the binaries run successfully.

But given that py-pytorch has no direct dependency on this library, I'm assuming it should generally be pulled in somewhere in the dependency chain? Or is this a missing runtime dependency that needs to be added to the py-pytorch portfile?

**Comment by mascguy** [comment]
Of note, I also compared the recursive dependency list for both py38-pytorch and py39-pytorch, but didn't see any obvious omissions.

**Comment by mascguy** [comment]
Here's the full runtime stacktrace, when py39-click isn't installed:

```
$ convert-onnx-to-caffe2-3.9
Traceback (most recent call last):
  File "/opt/local/bin/convert-onnx-to-caffe2-3.9", line 33, in <module>
    sys.exit(load_entry_point('torch==1.6.0a0+b31f58d', 'console_scripts', 'convert-onnx-to-caffe2')())
  File "/opt/local/bin/convert-onnx-to-caffe2-3.9", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/caffe2/python/onnx/bin/conversion.py", line 11, in <module>
    import click
ModuleNotFoundError: No module named 'click'

```

**Comment by reneeotten** [comment]
a cursory look at v1.6.0 of py-torch suggests that it does not support PY39; there is a newer version that seems to do though... If you want to get this PR finished I would recommend to remove the `py-pytorch` part from this PR (or we'll wait and see what Chris thinks, I requested his review); if you're interested you could always open a PR with the update and PY39 addition of `py-pytorch`.

**Comment by mascguy** [comment]
> a cursory look at v1.6.0 of py-torch suggests that it does not support PY39; there is a newer version that seems to do though... If you want to get this PR finished I would recommend to remove the `py-pytorch` part from this PR (or we'll wait and see what Chris thinks, I requested his review); if you're interested you could always open a PR with the update and PY39 addition of `py-pytorch`.

I noticed that too, though it looked like it wouldn't even build successfully, let alone run. (That was several days ago, so perhaps I'm not recalling correctly.) In my cursory tests, though, it does seem to work. Not just the binaries, but also a simple Python 3.9 test program utilizing PyTorch. That's not 100% definitive, but certainly encouraging.

Can you provide a link to the details? I'm a bit late to the Python party, and if nothing else, it would help bring me up-to-speed.

Anyhow, I'm fine with shelving the new py39 subport, if that's the consensus. But regardless of what we do there, the missing py-click dependency looks like it needs to be fixed. Yes?

**Comment by mascguy** [comment]
One final thought: Bear in mind that these updates were all to support a py39 subport for pytorch. So while we can certainly split the latter out, I'd prefer to see if we can figure out the direction for pytorch, and include that work too. (Unless it's going to take weeks. In which case, sure, let's push the other stuff out now. Lol)

**Comment by mascguy** [comment]
@cjones051073, this definitely isn't urgent. But if you can spare a few minutes to review this PR, we'd be grateful!

Cheers and Thanks,
-Chris

**Comment by mascguy** [comment]
@reneeotten @cjones051073 Given that py-pytorch requires plenty of compilation time, ccache support would be very useful. Based on some quick research, it looks like this isn't quite as simple as it would normally be.

Per the project, as well as various web articles, it sounds like we'd need to create some softlinks in a temporary directory, and then add said directory to the front of `PATH`:

https://raw.githubusercontent.com/pytorch/pytorch/master/CONTRIBUTING.md

But that seems a bit hacky, and wanted to confirm with you folks whether that info is still up-to-date.

I also greped the various python portfiles, as well as the python portgroup, but it looks like py-pyqt4 is the only one that enables it. (And in the latter case, it uses the standard ccache mechanism, which doesn't work for py-pytorch. Tested and confirmed locally.)

While ccache support isn't absolutely critical, it certainly would speed up iterative local rebuilds.

Your folks' thoughts?

**Comment by mascguy** [comment]
@reneeotten Renee, setting aside my question relative to ccache support - as that's not important for this PR - do you have any other thoughts/comments?

**Comment by mascguy** [comment]
Maintainers, while this PR isn't urgent, it's also been sitting idle for days without feedback/responses.

At this point, I'd like to push this through. Any objections?

**Comment by kencu** [comment]
just so we're all on the same page -- every CI build fails. But we're all happy with that.

Right?

**Comment by mascguy** [comment]
I've reviewed the raw logs, and they're truncated. The jobs appear to be timing out, and being forcibly killed.

Not ideal, but not a surprise, either.

Given how many times I've built (and rebuilt) the various subports of each of these, plus running tests via `port -vst`... I'm quite confident they're fine.

**Comment by mascguy** [comment]
Thanks Ken!!!

**Comment by mascguy** [comment]
So far so good, the failures I'm seeing are related to issues with `protobuf3-cpp`.

My guess is that it's a compiler-selection issue with that port, but need to go down that rabbit hole and see what's happening...

**Comment by mascguy** [comment]
To close the CCache loop: Apparently it can be enabled quite easily with newer versions of CMake and Ninja, via CMake flags.

The following is what's needed for Python ports like this. (Tested and verified locally.)
```
    if {[tbool configure.ccache]} {
        build.env-append \
            CMAKE_C_COMPILER_LAUNCHER=${prefix}/bin/ccache \
            CMAKE_CXX_COMPILER_LAUNCHER=${prefix}/bin/ccache
    }
```

Cheers,
-Chris

**Comment by kencu** [comment]
that should be in the cmake PortGroup, if it isn't already there.

There is an open PR with some other nice additions we should have, like making cmake a "no arch check" dependency to avoid it being needlessly built as universal (which can't be done on BigSur intel, and some other cross-arch universals).

**Comment by mascguy** [comment]
> that should be in the cmake PortGroup, if it isn't already there.
> 
> There is an open PR with some other nice additions we should have, like making cmake a "no arch check" dependency to avoid it being needlessly built as universal (which can't be done on BigSur intel, and some other cross-arch universals).

Ah, I checked the python PortGroup, but not cmake. That'll teach me for not grepping the entire portgroup directory!  :-)

Unfortunately, I'm not sure that the current implementation in the cmake 1.1 PortGroup will work as-is:
```
# tell CMake to use ccache via the CMAKE_<LANG>_COMPILER_LAUNCHER variable
# and unset the global configure.ccache option which is not compatible
# with CMake.
# See https://stackoverflow.com/questions/1815688/how-to-use-ccache-with-cmake
proc cmake::ccaching {} {
    global prefix
    namespace upvar ::cmake ccache_cache cccache
    if {${cccache} && [file exists ${prefix}/bin/ccache]} {
        return [list \
            -DCMAKE_C_COMPILER_LAUNCHER=${prefix}/bin/ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=${prefix}/bin/ccache]
    }
}
```

Reason being, those two CMake variables need to be set in the environment, rather than via configure arguments.

Thoughts?

**Comment by kencu** [comment]
If the user is trying to use ccache, being set in macports.conf or wherever (in the Portfile) the cmake PG should obey without further ado.

Somehow or other :>

**Comment by mascguy** [comment]
> If the user is trying to use ccache, being set in macports.conf or wherever (in the Portfile) the cmake PG should obey without further ado.
> 
> Somehow or other :>

No, I've tested with the cmake 1.1 portgroup included, and it doesn't work. I suspect this is because Ninja is being used for the build, and that flag isn't being passed down... or it's being ignored somewhere in the chain.

However, when specified via the environment, it is indeed picked up.

Any ideas?

**Comment by kencu** [comment]
do you mean you are doing this, and it works:
```
configure.env-append CMAKE_C_COMPILER_LAUNCHER=${prefix}/bin/ccache
configure.env-append CMAKE_CXX_COMPILER_LAUNCHER=${prefix}/bin/ccache
```

if that works, but setting 
```
configure.args-append -DCMAKE_C_COMPILER_LAUNCHER=${prefix}/bin/ccache
configure.args-append -DCMAKE_CXX_COMPILER_LAUNCHER=${prefix}/bin/ccache
``` 
doesn't work, then that is pretty hosed up, no?

**Comment by kencu** [comment]
I am not sure I know with certainty how cmake, ccache, and ninja interact. 

I don't know that I have ever seen that tested.

Takes 5s to turn off ninja, though, to see if that is the issue.

**Comment by mascguy** [comment]
The former - setting environment variables - does work, yes.

As for the latter, do I need to do that explicitly, if I'm including the cmake 1.1 portgroup...?

**Comment by kencu** [comment]
If it is being set, it should show up as such in the build folder cmake cache file, where all the other cmake build settings are itemized. 

Maybe it is (somehow...) never being set. :>

**Comment by mascguy** [comment]
Normally I'd consider investigating further, but I'm neck-deep investigating upstream build failures, which are blocking builds of two of the ports for this PR. Sigh...

**Pull request merged**
