### PR TITLE
Remove two ports whose upstream no longer exist

### PR DESCRIPTION
**Pull request by grimreaper**
- mdbconv's upstream domain is for sale
- pilot-link just doesn't resolve

### CODE REVIEW

**Comment by neverpanic** [comment]
@grimreaper Did you check that these ports do not have dependents? (E.g. by using `port echo depends:mdbconv` or grepping for mdbconv in the repository after removal)

**Comment by grimreaper** [comment]
I checked both using the following commands
  810  port echo rdependentof:pilot-link
  823  port echo rdependentof:mdbconv

**Comment by neverpanic** [comment]
`rdependentof` will only list ports you have installed, not those you do not have installed.

At least `pilot-link` still has dependencies:
```
$> port echo depends:pilot-link
jpilot
malsync
```

Those either need to be removed with pilot-link, or pilot-link needs to stay. Pilot-link's files still seems to be available from sourceforge: https://sourceforge.net/projects/pilot-link/files/.

mdbconv can go as far as I can see.

**Comment by grimreaper** [comment]
bah! Thanks!

Updated to remove malsync which is completely useless and mdbconv for the reason already listed.

**Pull request merged**
