### PR TITLE
[WIP] libcxx: Add support for (Intel) Tiger

### PR DESCRIPTION
**Pull request by dgelessus**
#### Description

A few small modifications to enable building libcxx on Intel Tiger.

So far I've only been able to test the build with `-universal`, because compiling for PowerPC requires a newer clang than I currently have working on my Tiger system (see [LibcxxOnOlderSystems](https://trac.macports.org/wiki/LibcxxOnOlderSystems#Leopardppc)). I also haven't been able to test if the built libc++ actually works - the libraries that need it currently don't build for me (for unrelated reasons).

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.4
Xcode 2.5

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
Please be very careful with this port. Any changes would need testing on all affected systems. Most of the build script changes have been very carefully tweaked. The nostdinc was needed for many clang compilers to be able to compile this, as I recall from two years go. I'm very surprised that deleting the c++11 standard could work. What compiler is building libcxx? clang-3.4? It also needs to be able to build with clang-5.0 through clang-9.0 successfully. 

In the past, I ran into quite  few hiccups getting libcxx to build on Tiger -- but I haven't tried in a couple of years. Would be interesting if it builds now...

**Comment by kencu** [comment]
Re: PPC support, it is possible, but incomplete. LLVM has officially dropped Darwin PPC as a platform, and are in the process of stripping that support out of the llvm tree. The last llvm/clang that had a full (but not fully functional) implementation was clang-7.0. There are efforts to get that working properly on PPC, but they may or may not ever be completed. The issue is down in the guts of the ABI (assembly stack structure and calling convetions handling), so it's well over the head of most of us -- and the people who can fix it have better things to do with their time, to be honest. But still, some of us are interested...

**Comment by dgelessus** [comment]
In retrospect, I should have marked this PR as WIP. After some further testing on Tiger I found that I couldn't always build against libc++ (this is using clang-3.4). If I'm understanding things correctly, each Clang version includes its own copy of the libc++ headers, which means that the [Tiger patches to the headers](https://github.com/macports/macports-ports/pull/5783/files#diff-3fa5b7073509ca574f299ca146f3a624) would need to be copied into each clang-x.y port. That wouldn't be very maintainable...

> Please be very careful with this port. Any changes would need testing on all affected systems.

That is a valid concern - testing the build on Tiger of course doesn't confirm that it will also work on later versions.

"Affected systems" would be anything before Mavericks (10.9), right? Sadly Travis CI can't test anything older than 10.11. I have 10.6 (64-bit) and 10.7 installations that I can test on, once I've figured out how I need to handle the header patches.

> The nostdinc was needed for many clang compilers to be able to compile this, as I recall from two years go. I'm very surprised that deleting the c++11 standard could work.

I assume you're referring to [this change](https://github.com/macports/macports-ports/pull/5783/files#diff-cf05c82ea62bdfdda3418ff3f617e157)? My assumption was that the if condidion was *intended* to mean "10.6 or older" and not "only 10.5 and 10.6 specifically", so I also added 10.4 to the list. I haven't tested if the Tiger build also works without this change.

> What compiler is building libcxx? clang-3.4? It also needs to be able to build with clang-5.0 through clang-9.0 successfully.

Yes, it's using clang-3.4 to do the build on Tiger. Can't test with newer compilers on Tiger right now, as I'm still working out how to bootstrap them. Once I get to testing on 10.6 and 10.7 I can try some newer clang versions there too.

> Re: PPC support

PowerPC isn't my main goal with this patch - at the moment I'm mostly working around PowerPC. My change in c590e1edccaf5c18e22f64c5dd48750b6666c43a was only so that I notice more quickly when I build universal by accident. (Without this change, universal builds will attempt to use clang-3.3, which segfaults during the build.) I might look into universal builds if I can get Clang properly working on Tiger in the first place.

Thank you for taking the time to look over the patches by the newbie 😃 I'm still figuring out how all the parts of the clang build process fit together, so the insights are helpful.

**Comment by kencu** [comment]
even then, Travis tests nothing other than for a build error. The functions are not tested whatsoever.

There are very few people using Tiger Intel (after all, why?) and so Tiger and Leopard PPC have been our focus for the pre-10.6 older systems...

no, the nostdinc++ and std=c++11 refer to other issues, not the SDK thing. I was not aware that you could build libc++ with c++11, but I don't know that I ever tried to.

I have clang-3.8 running on Tiger Intel -- but it's a custom build that only I have, and it (presently) does not work against libc++ as I could not get libc++ to build reliably on Tiger Intel before this. I build it with gcc7, but it's non-trivial.

I'm thinking this work is probably more appropriate for a ticket on Trac and then work through various issues over the coming weeks, rather than a github PR.

**Comment by kencu** [comment]
well i meant I was not aware that you could build libc++ withOUT c++11, but I don't know that I ever tried to.

**Comment by dgelessus** [comment]
I've made a Trac ticket with an overview of all the Intel Tiger issues I've run into so far (and which ones I was able to fix): https://trac.macports.org/ticket/59717

I've also made some progress with the libcxx Tiger fixes - basically I copied the header patches from libcxx to the llvm ports and adjusted them as needed. I'll push the changes once I've confirmed that they're working properly.

**Comment by kencu** [comment]
ok if we close this pr, and continue thinking about Tiger Intel on the Trac ticket? There's just too much to work through, test, etc,etc, for a PR for this...

**Comment by dgelessus** [comment]
Sure - I can completely understand that you don't want a big patch like this just for Intel Tiger support, when it could break things on newer systems if not properly tested.

I'll keep this as a branch in my fork in case it's useful to anyone for anything. (I'll probably need to change the branch name so that this PR stops getting notifications whenever I push to the branch.)

**Comment by dgelessus** [comment]
Sure - I can completely understand that you don't want a big patch like this just for Intel Tiger support, when it could break things on newer systems if not properly tested.

I'll keep this as a branch in my fork in case it's useful to anyone for anything. (I'll probably need to change the branch name so that this PR stops getting notifications whenever I push to the branch.)

**Pull request closed without merging**
