### PR TITLE
fheroes2: update to 0.9.6

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.5.1 20G80 x86_64
Xcode 12.5.1 12E507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
@oleg-derevenetz please don't make whitespace changes mixed in with functional changes as it is hard to see the relevant things that changed.

**Comment by oleg-derevenetz** [comment]
Hi @reneeotten

> @oleg-derevenetz please don't make whitespace changes mixed in with functional changes as it is hard to see the relevant things that changed.

Sorry for this. I peeped this style in another Portfile and I liked it :)

**Comment by reneeotten** [comment]
> Sorry for this. I peeped this style in another Portfile and I liked it :)

no worries! Just to make sure: as long as it conforms to the modeline (i.e., spaces with multiples of 4) it's all fine. If you really want to change the white space you can of course do that, but  please do so in a separate commit.

**Comment by oleg-derevenetz** [comment]
@reneeotten Should I split the squashed commit in this PR in two commits?

**Comment by reneeotten** [comment]
> @reneeotten Should I split the squashed commit in this PR in two commits?

Yes, please!

**Comment by reneeotten** [comment]
how about `white space changes` instead of `beautify the Portfile`? ;)

**Comment by reneeotten** [comment]
thanks @oleg-derevenetz !

**Comment by oleg-derevenetz** [comment]
Hi @reneeotten May I ask for an advice for this build on Big Sur for ARM64:

https://build.macports.org/builders/ports-11_arm64-builder/builds/27635

? It seems that `cmake` wasn't installed to build this `Portfile`, should I add it to the `depends_build`? I thought that `PortGroup cmake` implies this... At least there were no issues with this before, and test builds for this PR didn't catch it...

**Comment by oleg-derevenetz** [comment]
@reneeotten I'm sorry, nevermind, it looks like I figured it out - #11812.

**Pull request merged**
