### PR TITLE
clang_select: Add entries for git-clang-format + some others

### PR DESCRIPTION
**Pull request by lukel97**
This adds some more entries for clang_select that were added in 6ff441c but then reverted. I've only filled in the entries for clang-15 and clang-16, since I'm not sure if every binary is available in previous verisons. 

I've left out clangd, see https://github.com/macports/macports-ports/pull/10558 cc @gpanders @kencu

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 13.4 22F66 arm64
Command Line Tools 14.3.1.0.1.1683849156

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [X] checked your Portfile with `port lint --nitpick`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?
- [X] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mascguy** [comment]
Why are you rev-bumping `llvm-15` and `llvm-16`? Unless I'm missing something, that doesn't appear to accomplish anything. (And is something we definitely don't want to do, unless absolutely necessary.)

**Review by mascguy — CHANGES_REQUESTED** [review]
Don't rev-bump `llvm-15` and `llvm-16`.

**Comment by mascguy** [comment]
> Why are you rev-bumping `llvm-15` and `llvm-16`? Unless I'm missing something, that doesn't appear to accomplish anything. (And is something we definitely don't want to do, unless absolutely necessary.)

Ugh, sorry... yes, we do need to rev-bump these ports, since the installed files (specifically `mp-clang-xx`) are being changed. And that can be accomplished no other way, than via a rev-bump.

I'll re-add those, albeit with `[skip ci]`. (Simply because CI has no chance of building all of this successfully, within the 6-hour timeout window.)

**Comment by mascguy** [comment]
From a practical perspective though, rev-bumping even a single `llvm` port will tie up our buildbots for up to 24-ish hours. So we should start with `llvm-16`, and only update one per PR.

So we can drop the changes for `llvm-15`, and add those via a subsequent PR.

**Comment by mascguy** [comment]
> From a practical perspective though, rev-bumping even a single `llvm` port will tie up our buildbots for up to 24-ish hours. So we should start with `llvm-16`, and only update one per PR.
> 
> So we can drop the changes for `llvm-15`, and add those via a subsequent PR.

To make this less painful, we can rev-bump the Clang subport only, as that's the only one that needs to be updated. Done via my latest push.

**Comment by mascguy** [comment]
@cjones051073 and @kencu - just a heads-up regarding this impending enhancement. So if you folks are planning to update any of the LLVM ports anytime soon, can you include this too?

**Comment by reneeotten** [comment]
what was the reason the addition if these entries was reverted preciously?

If it was for a good reason we should not add them here again just to be reverted a bit later...

**Comment by mascguy** [comment]
> what was the reason the addition if these entries was reverted preciously?
> 
> If it was for a good reason we should not add them here again just to be reverted a bit later...

I'm curious as well.

The additions seem reasonable, and unless I'm missing something (?), should be innocuous...

**Comment by lukel97** [comment]
> what was the reason the addition if these entries was reverted preciously?
> 
> If it was for a good reason we should not add them here again just to be reverted a bit later...

That commit was reverted because [it also added a symlink for clang-mp-x](https://github.com/macports/macports-ports/commit/6ff441cef657132ce26c2091c1fc723d5c81fc03#r35775902), which seemed to break things.

**Comment by pmetzger** [comment]
@lukel97 Poke.

**Comment by lukel97** [comment]
@pmetzger Sorry for dropping the ball on this, I've rebased it now and added the entries for llvm-17 too.

**Comment by pmetzger** [comment]
Okay, does anyone object to this being merged?

**Comment by lukel97** [comment]
Gentle ping

**Comment by pmetzger** [comment]
Done.

**Pull request merged**
