### PR TITLE
ghc: Bugfix

### PR DESCRIPTION
**Pull request by essandess**
Fixes:
* https://gitlab.haskell.org/ghc/ghc/-/issues/19646
* https://gitlab.haskell.org/ghc/ghc/-/issues/19655

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by essandess** [comment]
This is ready to merge. The only CI issue is a timeout.

**Review by cjones051073 — CHANGES_REQUESTED** [review]
Can you rid the lint nickpicks please.

**Comment by essandess** [comment]
> Can you rid the lint nickpicks please.

Fixed thanks. Ignore the checksum nitpicks—these are unnecessary for `gpg` signature files.

**Comment by essandess** [comment]
@cjones051073 To the best of my knowledge this is ready to merge.

**Comment by essandess** [comment]
@cjones051073 May we please merge this?

**Review by cjones051073 — APPROVED** [review]

**Pull request merged**
