### PR TITLE
beets: add missed dependency `py-7zr`

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.6 20G165 x86_64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
@xeron Any thoughts/concerns, regarding the change to `py-pycryptodome`?

**Comment by reneeotten** [comment]
@catap the most recent "convention" for portnames for Python ports is `py-<PyPI-name>`, even if this starts already with `py`. This makes automation using things like `upt` easier as there is a way to "translate" PyPI names to MacPorts (exceptions are capitalization, which we ideally don't use for portnames). The `python.rootname` override should therefore be only needed sparingly. I am aware that this isn't done consistently for older ports and even newer additions, but that would be the preference I think.

**Comment by catap** [comment]
@reneeotten thanks, renamed.

Meanwhile I've marked PR as draft and run CI without the last commit that includes beets. I'd love to prove that all dependency is set in the right order.

**Comment by catap** [comment]
@reneeotten yeah, I see you point. Special that I need `pyzstd` and not just `zstd`.

**Comment by catap** [comment]
@macportsbot retry

**Comment by catap** [comment]
@mascguy two of three checks are passed. I hope the third one can build everything until timeout is reached.

Anyway, as soos as loop is finished, I'll add one more commit.

**Comment by catap** [comment]
@mascguy timeout is happened.

Also, I've realized that I needed `py-pycryptodomex` port instead of `py-pycryptodome`. Which I've added.

From my point of view everything is ready for review and merge.

**Comment by mascguy** [comment]
> @mascguy timeout is happened.
> 
> Also, I've realized that I needed `py-pycryptodomex` port instead of `py-pycryptodome`. Which I've added.
> 
> From my point of view everything is ready for review and merge.

Sounds good. And as long as two of the three CI jobs complete successfully, that's enough validation to proceed.

Will merge once we have two successful runs, with your latest push.

**Comment by catap** [comment]
@mascguy last changes included update beets.

I doubt that it pass any CI because of timeout.

yes, last push was just to add beets commit

**Comment by mascguy** [comment]
> @mascguy last changes included update beets.
> 
> I doubt that it pass any CI because of timeout.
> 
> yes, last push was just to add beets’ commit

Ah, gotcha!

**Comment by mascguy** [comment]
@xeron Any concerns with merging this?

**Comment by catap** [comment]
@mascguy I’ve excluded his port from this PR. Instead I’ve created py-pycryptodomex

**Comment by mascguy** [comment]
Beautiful, we can merge then. Thanks for the heads-up!

**Pull request merged**
