### PR TITLE
py-argcomplete: update to 1.12.0

### PR DESCRIPTION
**Pull request by herbygillot**
- remove support for Python 2.7

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mohd-akram** [comment]
Thanks for the update, but upstream still seems to support Python 2.7. Why remove it?

**Comment by mf2k** [comment]
> Thanks for the update, but upstream still seems to support Python 2.7. Why remove it?

Python 2.7 is obsolete and out of support. We are moving away from it in Macports.

**Comment by mohd-akram** [comment]
Ah okay. I guess if anyone needs it they can use pip. LGTM.

**Comment by herbygillot** [comment]
Thanks @mohd-akram

**Pull request merged**
