### PR TITLE
rav1e: update for libgit2 1.7.x

### PR DESCRIPTION
**Pull request by mascguy**
### Description

Proposed update for `rav1e1`, updating various deps - particularly those related to `libgit2` - to fix build issues.

Creating as draft, as multiple iterations may be needed.

CC: @lukaso

### CODE REVIEW

**Comment by mascguy** [comment]
Interestingly enough, while CI fails, `rav1e` builds fine locally. (At least for macOS 11 and 12; not able to create a macOS 13 VM yet.)

Not sure what's going on yet, but have some theories. Stay tuned...

**Comment by mascguy** [comment]
@lukaso Lukas, can you test with my changes from this PR?

It may still fail due to `libiconv`, but the issues related to `libgit2` at least appear to be fixed now. (Going to tackle the `libiconv` issue too, but that requires more digging into what the Rust build is doing under-the-hood.)

**Comment by lukaso** [comment]
> @lukaso Lukas, can you test with my changes from this PR?

I'm not sure how do I do that. I've got a pretty complex build flow unfortunately.

> It may still fail due to `libiconv`, but the issues related to `libgit2` at least appear to be fixed now. (Going to tackle the `libiconv` issue too, but that requires more digging into what the Rust build is doing under-the-hood.)

Rust has just merged this PR: https://github.com/rust-lang/cc-rs/pull/848 which should improve how it handles `MACOSX_DEPLOYMENT_TARGET` and friends. It might just be worth waiting for the next rust release before digging in. I suspect these problems will start to ease once rust's handling is better.

**Comment by pmetzger** [comment]
I would suggest that we either finish this or close it.

**Comment by pmetzger** [comment]
Closing this for now. Feel free to re-open it when you feel you have a version you would like to commit of course.

**Pull request closed without merging**
