### PR TITLE
openssh: update to 8.4p1, drop obsolete Keychain patch

### PR DESCRIPTION
**Pull request by Schamschula**
#### Description

openssh has been updated several times upstream since the last MacPorts update.
MacPorts has tried to maintain the unsupported Apple keychain patch.
Homebrew dropped support for this patch in 2016: https://archive.is/hSB6d#10%25

###### Type(s)

- [x] update
- [x] security fix

###### Tested on

macOS 10.14.6 18G6042
Xcode 10.3 10G8

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by neverpanic** [comment]
@Schamschula did you try the various variants? I'm assuming at least the `+hpn` variant is probably also broken.

**Comment by Schamschula** [comment]
@neverpanic only +kerberos5 +xauth.

I didn't test +gsskex

**Comment by Schamschula** [comment]
Yup. +hpn looks for a non-existent patch file.

**Comment by Schamschula** [comment]
7.7p1 was the last version to support the hpn option in Freshports: See

https://www.freshports.org/security/openssh-portable/

**Comment by neverpanic** [comment]
Then we should probably just drop it?

**Comment by Schamschula** [comment]
I do think so.

I'll have a look at fixing the gsskex variant.

**Pull request closed without merging**
