### PR TITLE
libtranscript: update to 0.3.4

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@herbygillot I do not know what CI dislikes. Everything works on Sonoma:
```
--->  Extracting libtranscript-0.3.4.tar.bz2
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_devel_libtranscript/libtranscript/work" && /usr/bin/bzip2 -dc '/opt/local/var/macports/distfiles/libtranscript/libtranscript-0.3.4.tar.bz2' | /usr/bin/tar -xf - 
--->  Configuring libtranscript
Warning: ccache_dir /opt/local/var/macports/build/.ccache could not be initialized; disabling ccache: couldn't execute "ccache": no such file or directory
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_devel_libtranscript/libtranscript/work/libtranscript-0.3.4" && ./configure --prefix=/opt/local --without-gettext 
Checking for working make (make)... yes
Checking for working C compiler (/usr/bin/clang)... yes
Checking for working libtool C compile... yes
Checking for pkg-config... yes
Checking for Large File Support as default... yes
Checking for opendir/readdir/closedir/dirent.h/stdint.h... yes
Checking for symlink/unlink/lstat... yes
Checking for pthreads... yes
Checking for -pthread flag... yes
Checking for pthreads in -pthread -lpthread... yes
Checking for dlopen/dlsym/dlclose/dlerror in dlfcn.h... yes
Checking for dlopen/dlsym/dlclose/dlerror in standard library... yes
Checking for nl_langinfo... yes
Checking for strdup... yes
Checking for inline keyword... no
Creating libtranscript.pc
Checking for working install (/usr/bin/install)... yes
Creating Makefile
Creating mk/libtranscript
Creating mk/linkltc
--->  Building libtranscript
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_devel_libtranscript/libtranscript/work/libtranscript-0.3.4" && /usr/bin/make -j8 -w all 
make: Entering directory `/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_devel_libtranscript/libtranscript/work/libtranscript-0.3.4'
make[1]: Entering directory `/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_devel_libtranscript/libtranscript/work/libtranscript-0.3.4'
[CCLT] src/sbcs_table_converter.c
[CCLT] src/transcript_io.c
[CCLT] src/state_table_converter.c
[CCLT] src/utf.c
[CCLT] src/transcript_iconv.c
[CCLT] src/transcript.c
[CCLT] src/aliases.c
[CCLT] src/generic_fallbacks.c
[LDLT] src/libtranscript.la
[CCLT] src/tables/ibm1168p1002002.c
[LDLT] src/tables/ibm1168p1002002.la
[CCLT] src/tables/iso2022gb2312.c
[LDLT] src/tables/iso2022gb2312.la
[CCLT] src/tables/windows932.c
[LDLT] src/tables/windows932.la
[CCLT] src/tables/cns116434.c
[LDLT] src/tables/cns116434.la
[CCLT] src/tables/ibm437p1001995.c
[LDLT] src/tables/ibm437p1001995.la
[CCLT] src/tables/cns116436.c
[LDLT] src/tables/cns116436.la
[CCLT] src/tables/shiftjis2004.c
[LDLT] src/tables/shiftjis2004.la
[CCLT] src/tables/big5.c
[LDLT] src/tables/big5.la
[CCLT] src/tables/windows9362000.c
[LDLT] src/tables/windows9362000.la
[CCLT] src/tables/cns116437.c
[LDLT] src/tables/cns116437.la
[CCLT] src/tables/koi8ru.c
[LDLT] src/tables/koi8ru.la
[CCLT] src/tables/viscii.c
[LDLT] src/tables/viscii.la
[CCLT] src/tables/cns116433.c
[LDLT] src/tables/cns116433.la
[CCLT] src/tables/cns116432004e.c
[LDLT] src/tables/cns116432004e.la
[CCLT] src/tables/cns116432004b.c
[LDLT] src/tables/cns116432004b.la
[CCLT] src/tables/eucjp.c
[LDLT] src/tables/eucjp.la
[CCLT] src/tables/cns116432004d.c
[LDLT] src/tables/cns116432004d.la
[CCLT] src/tables/cns116431.c
[LDLT] src/tables/cns116431.la
[CCLT] src/tables/eucjis2004.c
[LDLT] src/tables/eucjis2004.la
[CCLT] src/tables/gb18030table.c
[LDLT] src/tables/gb18030table.la
[CCLT] src/tables/isoir165.c
[LDLT] src/tables/isoir165.la
[CCLT] src/tables/cns11643f.c
[LDLT] src/tables/cns11643f.la
[CCLT] src/tables/windows125x.c
[LDLT] src/tables/windows125x.la
[CCLT] src/tables/shiftjis.c
[LDLT] src/tables/shiftjis.la
[CCLT] src/tables/big5hkscs.c
[LDLT] src/tables/big5hkscs.la
[CCLT] src/tables/jisx2011969.c
[LDLT] src/tables/jisx2011969.la
[CCLT] src/tables/iso8859.c
[LDLT] src/tables/iso8859.la
[CCLT] src/tables/iso2022jisx2121990.c
[LDLT] src/tables/iso2022jisx2121990.la
[CCLT] src/tables/iso2022jisx208.c
[LDLT] src/tables/iso2022jisx208.la
[CCLT] src/tables/iso2022jisx213.c
[LDLT] src/tables/iso2022jisx213.la
[CCLT] src/tables/ibm37p1001995.c
[LDLT] src/tables/ibm37p1001995.la
[CCLT] src/tables/iso2022ksc5601.c
[LDLT] src/tables/iso2022ksc5601.la
[CCLT] src/tables/cns116432004c.c
[LDLT] src/tables/cns116432004c.la
[CCLT] src/tables/iso2022sbcs.c
[LDLT] src/tables/iso2022sbcs.la
[CCLT] src/tables/ibm1047p1001995.c
[LDLT] src/tables/ibm1047p1001995.la
[CCLT] src/tables/cns116432.c
[LDLT] src/tables/cns116432.la
[CCLT] src/tables/cp949.c
[LDLT] src/tables/cp949.la
[CCLT] src/tables/euckr.c
[LDLT] src/tables/euckr.la
[CCLT] src/tables/ibm878p1001996.c
[LDLT] src/tables/ibm878p1001996.la
[CCLT] src/tables/cns116435.c
[LDLT] src/tables/cns116435.la
[CCLT] src/tables/euccn.c
[LDLT] src/tables/euccn.la
[CCLT] src/modules/ascii.c
[LDLT] src/modules/ascii.la
[CCLT] src/modules/unicode.c
[CCLT] src/modules/unicode_gb18030.c
[CCLT] src/modules/unicode_utf7.c
[LDLT] src/modules/unicode.la
[CCLT] src/modules/iso2022.c
[LDLT] src/modules/iso2022.la
[CCLT] src/modules/euctw.c
[LDLT] src/modules/euctw.la
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_devel_libtranscript/libtranscript/work/libtranscript-0.3.4'
make[1]: Entering directory `/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_devel_libtranscript/libtranscript/work/libtranscript-0.3.4'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_devel_libtranscript/libtranscript/work/libtranscript-0.3.4'
make[1]: Entering directory `/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_devel_libtranscript/libtranscript/work/libtranscript-0.3.4'
[CC] src.util/linkltc/linkltc.c
[LD] src.util/linkltc/linkltc
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_devel_libtranscript/libtranscript/work/libtranscript-0.3.4'
make: Leaving directory `/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_devel_libtranscript/libtranscript/work/libtranscript-0.3.4'
```

**Comment by barracuda156** [comment]
Anyway, I will just close this.

**Comment by herbygillot** [comment]
Hey @barracuda156, was wondering why this one got closed?

**Comment by barracuda156** [comment]
> Hey @barracuda156, was wondering why this one got closed?

CI was failing with a silly error that `libtool` was not functional. I could not reproduce that I had no idea why that happens on CI and how to fix it.
Feel free to pick the update from here or reopen the PR (perhaps CI will fail though).

**Pull request closed without merging**
