### PR TITLE
boost: update to 1.70.0

### PR DESCRIPTION
**Pull request by michaelld**
#### Description

Update MP Boost to 1.70.0:

(1) tweak current patches to apply cleanly.

(2) Add patch to revert ABI naming to what we have historically had in MacPorts: "libboost_COMPONENT-mt.dylib", where COMPONENT is the component name e.g., "system" or "thread" or the like.

NOTE: This commit and PR are a "work in progress" WIP. For example, MPI doesn't work right now in destroot & it's not clear to me yet how to fix it!

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
builds cleanly on OSX 10.4.11 & 10.5.8 PPC, OSX 10.5.8 Intel through 10.14.4 Intel.

#### Ports that depend on boost that need to be tested / verified, then once working with this new Boost version, add a commit to this PR that rev-bumps the dependent port & check the box below for that specific port. If the port can't easily be update to work or there is something else worth noting, please edit the listing and add the relevant information after the port name.

- [ ] ADOL-C
- [x] akonadi
- [ ] alps
- [ ] ALPSCore
- [ ] ALPSMaxent
- [ ] arabica
- [ ] aspcud
- [ ] assimp2
- [ ] bali-phy
- [ ] bastet
- [ ] bitcoin
- [ ] boost-build
- [ ] boost-gil-numeric
- [ ] boost-numpy : should work
- [ ] boost-process
- [ ] bulk_extractor
- [ ] cadabra2
- [ ] caffe
- [x] cgal
- [ ] chemkit
- [ ] cicada
- [ ] ckon
- [ ] codeblocks
- [ ] collada-dom
- [ ] cpprestsdk
- [ ] cputhrottle
- [ ] cufflinks
- [ ] cvc4
- [ ] digikam
- [ ] digital_rf
- [ ] dssp
- [ ] enblend
- [ ] encfs
- [ ] expgram
- [ ] fbthrift
- [ ] field3d
- [ ] fife
- [ ] fityk
- [ ] flusspferd
- [ ] folly
- [ ] freecad
- [ ] freeling
- [ ] gearmand
- [ ] gecode
- [ ] gerbil
- [ ] glob2
- [ ] glom
- [ ] gnss-sdr : should work; easy to fix
- [ ] gnss-sdr-devel : should work; easy to fix
- [ ] gnss-sdr-next : should work; easy to fix
- [ ] gnucash
- [ ] gnucash-devel
- [ ] gnuradio : WIP
- [ ] gnuradio-devel : WIP
- [ ] gnuradio-next : WIP
- [ ] gource
- [ ] gpick
- [ ] gr-air-modes
- [ ] gr-ais
- [ ] gr-baz
- [ ] gr-cdma
- [ ] gr-dvbs
- [ ] gr-dvbs2
- [ ] gr-dvbt
- [ ] gr-fcdproplus : works
- [ ] gr-foo
- [ ] gr-fosphor : works
- [ ] gr-gfdm
- [ ] gr-gsm
- [ ] gr-ieee802-11
- [ ] gr-ieee802-15-4 : works
- [ ] gr-iio
- [ ] gr-iqbalance
- [ ] gr-limesdr : might work; easy to fix
- [ ] gr-limesdr-devel : works
- [ ] gr-lora
- [ ] gr-lora-BastilleResearch
- [ ] gr-lora-rpp0 : works
- [ ] gr-lte
- [ ] gr-mac
- [ ] gr-ofdm
- [ ] gr-osmosdr : works
- [ ] gr-osmosdr-38 : might work; easy to fix
- [ ] gr-pcap
- [ ] gr-pyqt
- [ ] gr-rds : works
- [ ] gr-specest
- [ ] Gyoto
- [ ] highlight
- [ ] htcondor
- [ ] hugin-app
- [x] hyperscan
- [ ] iAIDA
- [ ] inkscape
- [ ] inkscape-devel
- [ ] inkscape-gtk3-devel
- [ ] innoextract
- [ ] json_spirit
- [ ] kde4-workspace
- [ ] kdenetwork-strigi-analyzers
- [ ] kdepim4-runtime
- [ ] kdepimlibs4
- [ ] kdepimlibs4-kioslaves
- [ ] kdevplatform
- [ ] kget
- [ ] kig
- [x] ktorrent4
- [ ] lader
- [ ] ledger
- [ ] lib2geom
- [ ] libbert
- [ ] libcdr
- [ ] libcdr-0.1
- [ ] libetonyek
- [ ] libfreehand
- [ ] libftdi1
- [x] libkml
- [x] libktorrent
- [ ] liblas : works
- [ ] liblightgrep
- [ ] libmspub
- [ ] libnifalcon
- [ ] libodfgen
- [x] libopenraw
- [ ] libpagemaker
- [ ] libpcl
- [ ] libphonenumber-cpp
- [ ] LibreCAD
- [ ] LibreCAD-devel
- [ ] librets
- [x] librevenge
- [ ] libtorrent-rasterbar
- [x] libvisio
- [x] libvisio-0.1
- [ ] litecoin
- [ ] logstalgia
- [ ] LucenePlusPlus
- [ ] luminance-hdr
- [ ] LyX
- [ ] magicspp
- [ ] mapnik
- [ ] mariadb-connector-cpp
- [ ] metaproxy
- [ ] metview
- [ ] mgizapp
- [ ] mkhexgrid
- [x] mkvtoolnix
- [ ] mlpack
- [ ] mongo-cxx-driver
- [ ] monotone
- [ ] mosesdecoder
- [ ] mpd
- [ ] mstch
- [ ] mtxclient
- [ ] mysql51-connector-cpp
- [ ] mysql55-connector-cpp
- [ ] mysql56-connector-cpp
- [ ] mysql57-connector-cpp
- [ ] ncmpc
- [ ] ncmpcpp
- [ ] nheko
- [ ] nsrllookup
- [ ] ogre
- [ ] ompl
- [ ] opencolorio
- [ ] openimageio
- [ ] opensaml
- [ ] openscad
- [ ] openscad-devel
- [ ] OpenSceneGraph
- [ ] OpenSceneGraph-devel
- [ ] openvdb
- [ ] openvrml
- [ ] orfeotoolbox
- [ ] orocos-rtt
- [ ] osm2pgsql
- [ ] pdns-recursor
- [ ] peekabot-client
- [ ] peekabot-server
- [ ] percona-connector-cpp
- [ ] php71-mysql-xdevapi
- [ ] php72-mysql-xdevapi
- [ ] php73-mysql-xdevapi
- [ ] pingus
- [ ] playerstage-player
- [ ] poedit1
- [ ] povray
- [ ] py27-graph-tool
- [ ] py27-gyoto
- [ ] py27-pyilmbase
- [ ] py27-pykde4
- [ ] py27-stfio
- [ ] py33-gyoto
- [ ] py34-gyoto
- [ ] py34-pyilmbase
- [ ] py34-pykde4
- [ ] py35-graph-tool
- [ ] py35-gyoto
- [ ] py35-pyilmbase
- [ ] py35-stfio
- [ ] py36-ffc
- [ ] py36-graph-tool
- [ ] py36-gyoto
- [ ] py36-pyilmbase
- [ ] py36-stfio
- [ ] py37-graph-tool
- [ ] py37-pyilmbase
- [ ] py37-stfio
- [x] pythia
- [x] qtiplot
- [ ] QuantLib
- [ ] raceintospace
- [ ] restinio
- [ ] rocs
- [ ] rsgislib
- [ ] scantailor
- [ ] scidavis
- [ ] scribus
- [ ] scribus-devel
- [ ] sdcc
- [ ] seqan-apps
- [ ] shenidam
- [ ] shibboleth
- [ ] simple-web-server
- [ ] simple-websocket-server
- [ ] simplevoc-open
- [ ] SoapyUHD
- [ ] soci
- [ ] source-highlight : works
- [ ] spot
- [ ] srecord
- [ ] stimfit
- [ ] stp
- [ ] strigi
- [ ] synfig
- [ ] tcpflow
- [ ] textmate2
- [ ] thrift
- [ ] thrift-devel
- [ ] tophat
- [ ] uhd : might work; easy to fix
- [ ] uhd-39lts : might work; easy to fix
- [ ] uhd-devel : works
- [x] umbrello
- [ ] vcsn
- [ ] viennacl
- [ ] vigra
- [ ] volk : might work; easy to fix
- [ ] volk-devel : works
- [ ] volk-gnss-sdr : might work; easy to fix
- [ ] volk-gnss-sdr-devel : works
- [ ] volk-gnss-sdr-next : might work; easy to fix
- [ ] vowpal_wabbit
- [ ] wangle
- [ ] wesnoth
- [ ] widelands
- [ ] widelands-devel
- [ ] xmltooling
- [ ] xmlwrapp
- [ ] xylib
- [ ] yazproxy
- [ ] zorba
- [ ] zunda

### CODE REVIEW

**Comment by cjones051073** [comment]
Thanks. Could you please though add to this PR any ports you have already tested and rev-bumped ?

**Comment by michaelld** [comment]
Patience! Yes I was going to do that either here or on the MP ticket.

**Comment by michaelld** [comment]
Question: Should I move the origin account of this PR to the main MP repo?

**Comment by cjones051073** [comment]
> Patience! Yes I was going to do that either here or on the MP ticket.

OK! Please do it here though, as then they will 1) get tested automatically and 2) it will be easier for others to push updates as they test them. git is sooo much easier to work with than trac...

**Comment by cjones051073** [comment]
> Question: Should I move the origin account of this PR to the main MP repo?

No need, just allow others to directly commit to the branch in your fork. it might already be automatically enabled.

**Comment by michaelld** [comment]
Ports that I've tested (build, install, & test [if available] all clean / function):

I maintain: gr-fcdproplus, gr-fosphor, gr-ieee802-15-4, gr-limesdr, gr-lora-rpp0, gr-osmosdr, gr-rds, uhd-devel, volk-devel, volk-gnss-sdr-devel

Others: liblas, source-highlight

**Comment by cjones051073** [comment]
b.t.w. can you also amend the commit message for boost to add

```
closes: https://trac.macports.org/ticket/56294
```

You should also remove any reference to it being WIP in the commit message, as once this finally gets merged it will then no longer be WIP any more, so the comment in the commit history would not make any sense.

??

**Comment by michaelld** [comment]
For the ports I maintain: The non-devel versions (either release or next) will be easily fixable if they don't work, via porting patches if/as required. I have a fix for GNU Radio that I'm testing / verifying with Boost back to 1.65.0, since it needs to handle 3 groups of Boost versions (<= 1.65.0, 1.65.0 < 1.70.0, and >= 1.70.0). I'll fix inside MP as well as push upstream via https://github.com/gnuradio/gnuradio/issues/2452 .

**Comment by cjones051073** [comment]
> Ports that I've tested (build, install, & test [if available] all clean / function):
> 
> I maintain: gr-fcdproplus, gr-fosphor, gr-ieee802-15-4, gr-limesdr, gr-lora-rpp0, gr-osmosdr, gr-rds, uhd-devel, volk-devel, volk-gnss-sdr-devel
> 
> Others: liblas, source-highlight

Thanks, but please can you actually commit updates to this PR rev-bumping the above list (and again sorry if you are about to do this ;)).

**Comment by michaelld** [comment]
Yes I can fixup the commit message. I was guessing there's at least 1 more commit coming to fix the MPI variant, so I didn't want to say that ticket was fixed just yet.

**Comment by michaelld** [comment]
> Thanks, but please can you actually commit updates to this PR rev-bumping the above list (and again sorry if you are about to do this ;)).

NP & Yes I'm working on getting those in place too.

Is there a way to list all of the effected port & then cross them off as each's PR is added? Or do you recommend some other way of keeping track of ports that depend on Boost here?

**Comment by cjones051073** [comment]
> > Thanks, but please can you actually commit updates to this PR rev-bumping the above list (and again sorry if you are about to do this ;)).
> 
> NP & Yes I'm working on getting those in place too.
> 
> Is there a way to list all of the effected port & then cross them off as each's PR is added? Or do you recommend some other way of keeping track of ports that depend on Boost here?

Isn't it better to just directly commit the rev-bumps/updtes for each dependent port directly to the branch here, rather than opening new PRs for them ? That is anyway the only way to test them automatically against the update here.

**Comment by cjones051073** [comment]
b.t.w. you can if you want add your own checklists. See for instance what is done in the description at https://github.com/macports/macports-ports/pull/3822

**Comment by michaelld** [comment]
Oh sorry. I meant as each _commit_ is added here; my bad. So: List all ~260 dependent ports in a comment & then use the markup to strikethrough those that have been addressed ... or something like that ... does this make sense?

**Comment by michaelld** [comment]
> b.t.w. you can if you want add your own checklists. See for instance what is done in the description at #3822

Oh nice! Yes that's what I want here! I'll see about figuring out how to do that! Thx!

**Comment by cjones051073** [comment]
> Oh sorry. I meant as each _commit_ is added here; my bad. So: List all ~260 dependent ports in a comment & then use the markup to strikethrough those that have been addressed ... or something like that ... does this make sense?

I guess it would work. You just need to construct a list like that used in the description of the openssl11 update.

**Comment by michaelld** [comment]
> I guess it would work. You just need to construct a list like that used in the description of the openssl11 update.

`sed` and `awk` are my friends here to coerce the list into a form that I can cut and paste into the description ... let me see what I can come up with ...

**Comment by michaelld** [comment]
OK I've added entries in the main description for the ports that depend on Boost, and I've updated the commit itself as requested. Next I'll start pushing rev-bumps for ports as I do testing on them.

**Comment by michaelld** [comment]
@cjones051073 in the openssl PR, did they just rev-bump all dependent ports to get macportsbot to notify maintainers? Is that what's recommended here, or do we get those some other way? [I've clearly never done this before ...]

**Comment by cjones051073** [comment]
> @cjones051073 in the openssl PR, did they just rev-bump all dependent ports to get macportsbot to notify maintainers? Is that what's recommended here, or do we get those some other way? [I've clearly never done this before ...]

@yan12125 should comment here, but yes, rev bumping all the ports and pushing them here will cause all maintainers to get notified...

**Comment by michaelld** [comment]
> @yan12125 should comment here, but yes, rev bumping all the ports and pushing them here will cause all maintainers to get notified...

OK maybe I'll do that to get the ball moving. I'm not sure how to get the relevant port maintainers to participate otherwise! I might be able to get to it tonight, but it'll probably be tomorrow.

**Comment by cjones051073** [comment]
kgraphviewer is anyway quite out of date and I suspect doesn't build anyway. Been meaning to try and fix it for a while... I've removed it from the list.

**Comment by cjones051073** [comment]
In spare moments I pseudo-randomly picked a few ports today to revbump and test. All them built just fine without needing any other changes.

**Comment by yan12125** [comment]
> @yan12125 should comment here, but yes, rev bumping all the ports and pushing them here will cause all maintainers to get notified...

I notify maintainers of all relevant ports as it's common that a port no longer builds with new OpenSSL and maintainers' actions are needed. I'd like to speed things up, too. There's no policy for such updates IIRC.

**Comment by cjones051073** [comment]
@michaelld I have rebased this branch against master, so you will need to rebase your local checkout.

**Comment by michaelld** [comment]
@cjones051073 Thanks; will do! Just FYI my "paid for" workload (consulting contracts) picked up recently so I have to back off of much of my MP work for a bit. As my free time allows: I'll work on this & the SWIG WIP PR's, and keep ports up to date here and there. I do value MP, and will do my best to respond to queries. When crunch time hits at work it takes priority; I'm sure you understand!

**Comment by cjones051073** [comment]
I think we should try again to push this forward, to get it merged. Ports are increasingly having issues with the old boost currently released, and in some cases (mysql8) forced into using their own internal boost builds, which I think we should avoid.

I have probably mentioned this before, but I also think aiming to find and fix all issues before merging this is impractical. I would favour a more proactive approach, so merge it soon, and just deal with whatever issues come up after the fact.

**Comment by cjones051073** [comment]
P.s. @michaelld can you fix the conflicts , when you have time ?

**Comment by michaelld** [comment]
@cjones051073 agreed & yes I will. Maybe we can push it through in the next 2 weeks, before I head out on a 2 week vacation ...

**Comment by michaelld** [comment]
We need to get someone to fix the MPI variant; I don't use MPI & in my memory it wasn't obvious how to fix the issue (whatever the issue was, which is yet another question).

**Comment by cjones051073** [comment]
> We need to get someone to fix the MPI variant; I don't use MPI & in my memory it wasn't obvious how to fix the issue (whatever the issue was, which is yet another question).

Ok, any chance we could try again to get this through ? We really need an updated boost...

Does anyone actually use the mpi variant? Could we perhaps push this through and then deal with fixing that at a later stage ?

**Comment by cjones051073** [comment]
@michaelld I've fixed the conflicts against master in this branch.

**Comment by michaelld** [comment]
@cjones051073 nice ... thx!

OK so we're not installing the Boost CMake Find scripts ... that's good because they're borked ... will force CMake-based port to use CMake's FindBoost script, which actually works.

How do folks propose we go about testing all of the dependent ports? There are a -lot- of them!

**Comment by cjones051073** [comment]
> @cjones051073 nice ... thx!
> 
> OK so we're not installing the Boost CMake Find scripts ... that's good because they're borked ... will force CMake-based port to use CMake's FindBoost script, which actually works.
> 
> How do folks propose we go about testing all of the dependent ports? There are a -lot- of them!

I suggest we don't ! Its just not practical. I've tested a lot and none had problems. I would suggest just hitting go on this, and dealing with the few that fail later on.

**Comment by cjones051073** [comment]
b.t.w. can you expand on the 'mph' issues ? The mph PG adds a number of variant options for mpi. Do all fail or just some ? I'm building with `+openmpi` just to see what happens...

**Comment by cjones051073** [comment]
Hmmmm. Seems boost 1.70 no longer builds, as a patch file added in

<https://github.com/macports/macports-ports/commit/fb0c6b307699fa7c41f412937c4767b2a21445a0>

does not apply to this version.... will just turn it off for now.

**Comment by cjones051073** [comment]
@mamoll The patch you added in https://github.com/macports/macports-ports/commit/fb0c6b307699fa7c41f412937c4767b2a21445a0 does not apply against this update.  I will remove it from this branch, and if you still need it once this is merged you should open a separate PR adding it back.

**Comment by michaelld** [comment]
> b.t.w. can you expand on the 'mph' issues ? The mph PG adds a number of variant options for mpi. Do all fail or just some ? I'm building with `+openmpi` just to see what happens...

I really don't recall what the issue was. Maybe your building here will show something useful?!

**Comment by michaelld** [comment]
> I suggest we don't ! Its just not practical. I've tested a lot and none had problems. I would suggest just hitting go on this, and dealing with the few that fail later on.

:+1: from me. When you get this stabilized, I say merge. It's been long enough already & we always have a few ports to fixup post-merge anyway ...

**Comment by cjones051073** [comment]
`+openmpi` variant fails during final destroy with

```
Error: Failed to destroot boost: error renaming "/opt/local/var/macports/build/_Users_chris_Projects_MacPorts_ports_devel_boost/boost/work/destroot/opt/local/lib/mpi.so": no such file or directory
```

and indeed looking in that area it is missing.

Build otherwise seemed fine up to that point. Could it be simply that this library is no longer created and thus we should just remove the lines in the port file that attempt to move this file ?

**Comment by michaelld** [comment]
Hmmm ... if you go into the build directory and do a "find" for that library, is one there? If so, then maybe it's not being installed correctly. If not, then yeah I'd say to remove that code from destroot.

**Comment by cjones051073** [comment]
> Hmmm ... if you go into the build directory and do a "find" for that library, is one there? If so, then maybe it's not being installed correctly. If not, then yeah I'd say to remove that code from destroot.

I cannot find one anywhere.

```
Oberon /opt/local/var/macports/build/_Users_chris_Projects_MacPorts_ports_devel_boost/boost/work > find . -name mpi.so
Oberon /opt/local/var/macports/build/_Users_chris_Projects_MacPorts_ports_devel_boost/boost/work > 
```

I've put an exists check on the file before moving it, rather than just remove the block entirely.

boost now builds fine with `+openmpi`. Not that I really know how to go testing it if works or not.

**Comment by cjones051073** [comment]
OK. done. now lets see...

**Comment by michaelld** [comment]
Aw yeah ... nice work @cjones051073 ! Now I have to rev-bump ports . ... but that's pretty simple all things considered! Thx again for seeing this through to the (?bitter?) end!

**Comment by cjones051073** [comment]
I sometimes feel we over think things a bit sometimes with updates like this. The pursuit of perfection can at times get in the way of getting something good out...

Anyway, I suspect most dependants will not even need rev-bumping at all. Given the nature of boost, being largely a header-only package, most ports will be fine as they are, and will naturally pick up the new version the next time they get updated. Only those that actually link against one of the libraries need touching now..

**Comment by michaelld** [comment]
> I sometimes feel we over think things a bit sometimes with updates like this. The pursuit of perfection can at times get in the way of getting something good out...

Agreed! I know I'm party to doing so sometimes.

> Anyway, I suspect most dependants will not even need rev-bumping at all. Given the nature of boost, being largely a header-only package, most ports will be fine as they are, and will naturally pick up the new version the next time they get updated. Only those that actually link against one of the libraries need touching now..

That's likely true. I do know that all of "my" ports build with Boost 1.65 through 1.70 by now ... so worst case is some rebuilding ... not a big deal overall.

**Comment by ra1nb0w** [comment]
Great work! Thank you!! Have a nice holiday from Italy :)

**Comment by cooljeanius** [comment]
>     * [ ]  wesnoth

I think this one got broken by this update

**Pull request merged**
