### PR TITLE
dict+libmaa: address comments raised in the mailing list

### PR DESCRIPTION
**Pull request by lbschenkel**
###### Description

There were some comments in the mailing list [1][2] about my recently merged PR [3] for these ports. In this PR I have implemented the suggested improvements.

[1] https://lists.macports.org/pipermail/macports-dev/2017-September/036487.html
[2] https://lists.macports.org/pipermail/macports-dev/2017-September/036490.html
[3] https://github.com/macports/macports-ports/pull/826

###### Type(s)
- [x] enhancement

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tested basic functionality of all binary files?

Pinging @ryandesign

### CODE REVIEW

**Comment by lbschenkel** [comment]
I don't think the `maintainer:none` label is correct since I'm the maintainer of the port.

**Comment by l2dy** [comment]
@lbschenkel The MacPorts software index was last updated on 2017-09-07 at 13:32:06 UTC, see https://www.macports.org/ports.php. The bot gets maintainer info from this index and assigned the wrong label.

**Comment by l2dy** [comment]
Please resolve conflicts caused by cf38763e36878d0d2b87b8ebac5f8a36b4833223.

**Comment by lbschenkel** [comment]
I'll fixing that right away, but I also feel the need to vent a bit, for the record (not directed to you @l2dy):

1. When the issues were raised in the mailing list, I replied right away (within minutes) saying that I would address them in a PR
2. It was late on that day in my time zone, so I created the PR the next day, pinging @ryandesign for review
3. I don't hear another word in the mailing list or here
4. Even though he was informed by me both via the mailing list and GitHub, a day after I have opened this PR he decides to go and commit directly to the port — causing extra work for me
5. Meanwhile, even though I'm the maintainer of the port in question, I'm reminded by the checklist every time I contribute that I have to check all open PRs before submitting changes (which is totally sensible: if other people submitted before you, you should coordinate with them to avoid creating extra work for them in case your PR ends up being merged first)   
6. It's not the first time that I had to spend extra work fixing conflicts because changes were committed to ports while I had open PRs against them

It might seem like it's a small thing — and it is, in isolation. What bothers me is the "message". When you get the impression that the guidelines apply just to the "lower tier" of contributors you don't feel very motivated to keep volunteering your free time to be maintainer and adopting orphaned ports. This one has been literally outdated for years, and now that I decided to give it a little bit of love apparently fixing a redirect could not wait another day.

**Pull request merged**
