### PR TITLE
clang-*: add clangd to clang_select group

### PR DESCRIPTION
**Pull request by gpanders**
#### Description

Add clangd to clang select group.

I see that clangd was added in #5418 but then reverted by @cjones051073  in #5683. The reversion doesn't provide a reason, so I'm not sure why it was reverted or if clangd is being omitted intentionally for some reason.

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G8022
Xcode 11.3.1 11C505

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
Thanks for the thought and the interest! But -- we can't have clangd in the select group as it doesn't build on all the systems that we deploy clang on.  Therefore it will cause errors during select on the systems where clangd doesn't build. That's why it was reverted out.

Now -- if there is invented some (reasonable) way to have different select files for different systems, I guess we can think about that; but at a certain point it sort of becomes too cumbersome to maintain.

besides -- clangd-mp-10 or clangd-mp-11 is not too much to type, I would think?

I'm going to close this so that nobody accidentally commits it, but if some method comes up we can reopen it!

**Comment by gpanders** [comment]
I see. That makes sense. Thanks for clarifying. 

> besides -- clangd-mp-10 or clangd-mp-11 is not too much to type, I would think?

Of course not :) It's more a matter of convenience -- having simple `clangd` work means I don't have to have special cases in configuration files for macOS vs. Linux.

**Comment by kencu** [comment]
are you using macports clangd for anything, by the way? I know it has a role in certain IDEs for on-the-fly source formatting, etc, but I have yet to find a use for it myself IRL.

**Comment by gpanders** [comment]
Yes, I use it as an LSP server in my editor (Vim) and it works very well!

**Pull request closed without merging**
