### PR TITLE
Remove myself as a maintainer, as apparently support for PowerPC systems is not among Macports interests

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

My participation here was always driven by intention to support macOS on PowerPC, which I was fairly explicit about. Since I am [told](https://github.com/macports/macports-ports/pull/20761#issuecomment-1880252132) now there is no desire to support those and accept required minimal fixes, there is no reason for me to invest time and effort any further either.

Thanks to everyone.

(If anyone happens to bump into this later, looking for PowerPC stuff, I will probably keep what is necessary in my repo.)

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mascguy** [comment]
> Sergey, while PPC changes for Python3.x weren't accepted, that doesn't mean we're suddenly dumping PPC in-general.
> 
> Are you sure this isn't a bit premature?

You've put a tremendous amount of time and effort into all of your contributions - which we very much appreciate! - and you shouldn't simply give up because one PR wasn't accepted.

Why give up so easily?

And you're certainly allowed to change your mind. So perhaps you might want to take a break for a few days, and reconsider before simply walking away?

**Comment by catap** [comment]
@mascguy my guess that the root cause that python 3.12 doesn't work on his setup and his PR can't be merge because python 3.12 is default one (or should be switched soon) and he was asked to do it.

Personally I've asked the same last year one some PR which was opened for months or two for the case python 3.11 and it required to add some dependencies as well to bypass CI.

As personal note I'd like to point that I was in Sergey position more than once and I had almost opened the same PR.

The root cause that someone push directly to master commits which might never be tested locally, also doesn't match checksum.

And from another case for a few persons who contributed a lot like me or Sergey, we must going via Github CI and fixes the ports which is broken by someone else to be able to merge anything.

All of this is quite demotivated behaviour to be honest.

To make myself clear: I've asked to write access serveral times and never had reply to my mail, see:

Screenshot 2024-01-08 at 12 09 10

**Comment by pmetzger** [comment]
One option here is for us to maintain a separate repository for PPC. Then we're no longer in the uncomfortable position where ancient operating systems and hardware are taking up the time of people who aren't interested in them.

**Comment by kamischi** [comment]
@barracuda156: Please stay with me. Although my contributions are slow, I am strongly interested to support older systems with FreePascal and possibly Lazarus. But without you, there is no chance for testing.

**Comment by barracuda156** [comment]
@mascguy It is impossible to bypass a few fundamental ports as dependencies, Python included, and Python 3.12 now, since Macports switched to 3.12 as the default. So while I could stay with 3.11 for my ports (as long as I do not face demands to switch as a condition of merging), it still leaves the whole set-up broken for anyone else. (Obviously, locally I have fixed it for myself.)

I never made an issue of anything not being accepted which was specific to pre-released version of 10.6 on ppc (in fact, almost nothing 10a190-specific has even been ever submitted here).
Python issue, as I have referred in the PR (see linked Iain’s comments), is not specific to pre-release version of 10.6 on PowerPC, but affects 10.6.8 Rosetta as well, which can be easily confirmed by anyone. Proposed fix was just the correct code, fixing an incomplete patch.

So in my view this _is_ indeed different from just some PR not being accepted because improvements are questionable or because a fix is only needed for an exotic developer build and helps nothing else.

I understand it is up to a port maintainer, so Joshua is in his right (which I did not argue against), but IMO there should be some reasonable agreement regarding fundamental ports. Otherwise everything is up to a preference of a single individual, and today ppc is broken, tomorrow i386 is thrown away, or anything below macOS 12, like some other upstreams did.

To be clear, I do not mean that anyone _should_ actively support PowerPC, or 32-bit platforms, or anything at all. There is no obligation whatsoever. But IMO the criterion for accepting a fix should be code soundness (and maintenance burden) and not whether someone personally considers a bug worth fixing or likes a platform in question. And if a fix is credible and does not add up to a burden of a port maintainer (I can understand that huge patches requiring rebasing may be unreasonable to accept), it should be accepted, as a matter of sound policy.
Logically, it is also rather be encouraged to test on non-standard configurations, since that is how obscure bugs are discovered, and because very few will test those to begin with.

Notice, no one in the discussion could point out why the fix is [allegedly] wrong or what breakages it could potentially introduce. No one proposed a better solution (which may be possible, and I am always in favor of such – it does not matter if _my_ PR is accepted, what matters is whether the problem gets fixed by someone).

Could you suggest some general solution to have PowerPC-specific stuff applied only for ppc/ppc64 builds and nothing else, which would not require approval of specific port maintainers? So that patches are not sitting in a given port at all, and are used exclusively for PowerPC case? If it is guaranteed that nothing of those affect non-PowerPC systems in any possible way, I may have less opposition to having stuff fixed.

Having a separate repo is not a practically feasible solution. What may be such is a mechanism which applies needed set of patches conditionally. It will be easy for me – and whomever else has an interest – to maintain. That will be also easy to remove at any point, if Macports decides to drop such support.
If this is done in some way, I can remove everything Rosetta-specific or 10.6 ppc-specific from portfiles, and everyone should be happy: maintenance burden is on those who want to maintain PPC stuff, Intel builds are untouched, Ken won’t complain about “spaghetti code in portfiles”, I can fix broken ports without having to go through extensive arguments and approval of maintainers who are unwilling to maintain systems in question.

**Comment by catap** [comment]
> @catap suggests to move the pthread code to legacysupport instead, which sounds indeed like a better approach. If this can be approved, then we do have a reasonable way to solve the problem without changing much.

Yes, I have suggested that move.

i really think that legacy support is the right place to that hacks, instead of patching each port.

I also see it as a way to find a compromise on that conflict.

**Comment by barracuda156** [comment]
@mascguy @pmetzger @catap If someone with commit access to legacy-support can back this idea, we can resolve the problem, hopefully.

**Comment by kencu** [comment]
I don’t insist on ppc being broken.

Josh decided MacPorts will not patch to support 10.6-on-ppc.

And I happen to agree with that.

**Comment by kencu** [comment]
We will not patch legacysupport to support 10.6-on-ppc either, by the way.

**Comment by barracuda156** [comment]
> We will not patch legacysupport to support 10.6-on-ppc either, by the way.

@kencu Quite amazing how you happen to make a final decision for everyone. (And again pretending the issue in question is specific to 10.6-**on-ppc**, while it is not.)

@mascguy There should be some clarity here, I believe. If there are some privileged individuals with a right to decide what can or cannot be done, then perhaps documenting that will be helpful.
If it will be explicitly stated that Ken is determining the policy, no further questions asked, I am leaving this for good without wasting anyone’s and my own time and further argument.
If the policy is determined not by a specific individual, then perhaps it is worth making clear as well.

**Comment by mascguy** [comment]
> We will not patch legacysupport to support 10.6-on-ppc either, by the way. 

I think we need to decide this is a group, as I don't agree with this statement.

**Comment by pmetzger** [comment]
Just as a reminder: 10.6 was never released for PPC, and in addition, whether something runs on Rosetta on an x86 under a newer OS really isn't germane to the goals of the project.

I'd like to mention something else as well. Support for PPC cannot come at the expense of work being done for modern platforms. It's fine if people who want to keep PPC alive do so. Telling people that they should have waited to update something until it could be tested for PPC is unreasonable, and that has happened even in recent hours.

A port maintainer has to make sure their updates pass the CI work correctly on recent MacOS. If someone wants to submit patches for PPC support that's fine. However, demanding that people take time to make sure they didn't break very old systems that they don't own when they update a port isn't reasonable.

**Comment by mascguy** [comment]
> A port maintainer has to make sure their updates pass the CI work correctly on recent MacOS. If someone wants to submit patches for PPC support that's fine. However, demanding that people take time to make sure they didn't break very old systems that they don't own when they update a port isn't reasonable.

Agreed, we shouldn't be demanding that a given PR works for PPC. However, if folks are interested in helping to ensure something works for PPC - and they're willing to take some extra time to do it - that seems reasonable.

The key is that most PRs don't need to be merged within 72 hours. And there's no reason to rush them.

**Comment by pmetzger** [comment]
There are excellent reasons to merge PRs quickly. For one thing, if we don't, the queue gets overwhelming, and the morale of people who submit PRs drops when they take long periods to get merged. There's also no reason to believe delay improves quality; it has no obvious benefits. (If we actually wanted to make sure PPC worked, we would have PPC CI machines.)

Honestly I'd like us to end the practice of having drafts hanging out in the PR queue as well. One submits a PR at the point where one is confident something can be merged. If it can't be merged, one withdraws it until one thinks it can be merged.

**Comment by catap** [comment]
I guess @pmetzger means https://github.com/macports/macports-ports/pull/22121 which from my point of view was absolutely legitimate to merge as it was merged.

**Comment by kencu** [comment]
10.6-for-ppc is not supported by macports. Anywhere.

Josh has spoken.

let’s start stripping it out.

It never should have been pushed in the first place.

Too many hacks, just encourages more hacks.

**Comment by mascguy** [comment]
> 10.6-for-ppc is not supported by macports. Anywhere.
> 
> Josh has spoken.
> 
> let’s start stripping it out.
> 
> It never should have been pushed in the first place.
> 
> Too many hacks, just encourages more hacks.

Again, this is not an official policy change.

Ultimately this is up to each maintainer. And I, for one, have no interest in ripping things out.

To each their own, though.

**Comment by barracuda156** [comment]
> > We will not patch legacysupport to support 10.6-on-ppc either, by the way.
> 
> I think we need to decide this is a group, as I don't agree with this statement.

@mascguy Clarity on this issue will be helpful. As long as objections to supporting PowerPC systems in some specific way are _rational_ and there is a good will to cooperate based on the understanding that the project benefits from sound contributions, it is possible, I believe, to come to an agreement.

I am fine with not touching in any way Josh’s ports, for example (the problem can be fixed instead via legacysupport), I am fine with not asking anyone to wait for testing something, but fix whatever needed post factum myself, I will not expect anyone to rebase patches specific to PPC etc.
Obviously, no fixes for PPC should harm other systems – but objections to proposed fixes should be rational and safe solutions are to be accepted, in general case.
In essence, for any technical issue there can be found a technical solution.

On the other hand, there is no solution for irrational objections and “let’s start stripping it out because 2 years ago some unrelated folks on Macrumors did not appreciate enough my efforts”.

I do hope that productive cooperation can be prioritized over personal dislikes. But if Macports consensus will be in favor of the latter, I accept that; then we could merge this PR, and then Ken may strip out whatever he likes and delete ports I have added.

**Comment by herbygillot** [comment]
I’d like to revisit the consideration of a middle ground here.

Of all the macOS package management projects, MacPorts is the strongest and best situated to serve users who still want to run software on extremely old Apple hardware, including PPC.

@barracuda156 and @catap have been clear in expressing their willingness to take on the burden. I feel like it's possible for us to make this work while still satisfying the objections against.

The solution which seems most amenable to me seems to be a separate repo (in my opinion).

A few of us have already opined that such a solution wouldn’t be very feasible, but I think we should actually reexamine and deliberately map out how this could work in practice.

A separate repo gives PPC enthusiasts complete and total freedom, while satisfying @kencu’s desire to remove code for an OS context that Apple never really officially released or supported (if I'm understanding his objections correctly).

So we’d have to:

1) macports/macports-ports —( **fork** )—> macports-ports-**legacy**
2) macports/macports-legacy-support —( **fork** )—> macports-legacy-support-**ppc**
3) macports-base (**no change**)

We’d want to make some slight enhancements to base to make life easier for those running macports-ports-legacy.

Perhaps the introduction of an additional `Portfile.ppc`, that gets automatically included (appended) to a port's `Portfile` whenever `port` is doing a build in a PPC context. This second PPC-specific Portfile can help legacy maintainers avoid the many merge conflicts that would otherwise arise as commits get continually synced from the main ports repo to the legacy one. `Portfile.ppc` would only exist in the legacy ports repo.

We could probably use Github Actions to sync to legacy after every commit to the main ports repo.

For `macports-base`, when its updating the local ports tree, we would have to download a `legacy`-specific ports tree tarball on PPC, which is produced from the macports-ports-legacy repo.

We would also want to retool the buildbots to monitor and build from the legacy repo for any builds on PPC.

Overall I don’t think these are huge changes to make.

I think we can certainly find a way that satisfies all involved.

**Comment by pmetzger** [comment]
@herbygillot: I proposed a second repository on -dev, the discussion sort of died.

@mascguy:
> Again, this is not an official policy change.

I think @jmroot was pretty unambiguous; we are not supporting 10.6 on PPC.

**Comment by catap** [comment]
> Perhaps the introduction of an additional `Portfile.ppc`, that gets automatically included (appended) to a port's `Portfile` whenever `port` is doing a build in a PPC context. This second PPC-specific Portfile can help legacy maintainers avoid the many merge conflicts that would otherwise arise as commits get continually synced from the main ports repo to the legacy one. `Portfile.ppc` would only exist in the legacy ports repo.

This can be achieved right now by `platofrm ppc { ... }` block at the end of the port I guess.

As was said in dev list this isn't technical issue :(

**Comment by herbygillot** [comment]
> This can be achieved right now by `platofrm ppc { ... }` block at the end of the port I guess.
> 

The problem with `platform ppc` blocks is that you will have conflicting changes in the same Portfile every time it's time to sync `master` from `macports-ports` to `macports-ports-ppc`.

If you have the changes in separate files (`Portfile` and `Portfile.ppc`), it's a lot easier to do a straightforward merge of both branches in git, otherwise you'll constantly be having to manually edit the `Portfile` to fix conflicts.

**Comment by herbygillot** [comment]
Can we get explicit opinions on the idea of a separate `macports-ports` repo that I proposed above?

- @kencu ?
- @jmroot ?

**Comment by catap** [comment]
> Can we get explicit opinions on the idea of a separate `macports-ports` repo that I proposed above?

Personally I do not like idea of fork at all. And if we support `Portfile.ppc` I don't understand why we can't keep it in main tree.

**Comment by herbygillot** [comment]
> > Can we get explicit opinions on the idea of a separate `macports-ports` repo that I proposed above?
> 
> Personally I do not like idea of fork at all. And if we support `Portfile.ppc` I don't understand why we can't keep it in main tree.

Well the main reason I think a fork make sense is that PPC maintainers will have total and unfettered control. You can change everything from portgroups and core ports, and not require approval from maintainers, neither will there be any risk of your changes inconveniencing non-PPC port maintainers.

**Comment by catap** [comment]
> Well the main reason I think a fork make sense is that PPC maintainers will have total and unfettered control. You can change everything from portgroups to core/critical ports, and not require approval from maintainers, neither will there be any risk of your changes inconveniencing non-PPC port maintainers.

And any that change will introduce a merge conflict, isn't it?

As I said before: idea with fork won't work and it should be avoided because it fragments the user base.

To be honest: I've spent a lot of efforts to bring lisp into MacPorts and right now it has coverage better than Debian (!) and I not sure that I like that's happening here at all.

**Comment by mascguy** [comment]
> @herbygillot: I proposed a second repository on -dev, the discussion sort of died.
> 
> @mascguy:
> > Again, this is not an official policy change.
> 
> I think @jmroot was pretty unambiguous; we are not supporting 10.6 on PPC.

A brief statement, in the context of a PR, does not constitute a policy change.

That would need to be discussed with fellow MacPorts managers and members, with ample opportunity for discussion and feedback.

**Comment by herbygillot** [comment]
> To be honest: I've spent a lot of efforts to bring lisp into MacPorts and right now it has coverage better than Debian (!) and I not sure that I like that's happening here at all.

Understood and apologies, @catap, I was simply trying to find the middle path.

**Comment by catap** [comment]
> > To be honest: I've spent a lot of efforts to bring lisp into MacPorts and right now it has coverage better than Debian (!) and I not sure that I like that's happening here at all.
> 
> Understood and apologies, @catap, I was simply trying to find the middle path.

no hard feeling and no need for apologies, no be honest.

Here a question of policy, and I agree with @mascguy that it should be made transparent and clean.

**Comment by jmroot** [comment]
> I think @jmroot was pretty unambiguous; we are not supporting 10.6 on PPC.

Well I'm not. Other maintainers can if they really want to, but they don't have to.

**Comment by pmetzger** [comment]
> Well the main reason I think a fork make sense is that PPC maintainers will have total and unfettered control. You can change everything from portgroups to core/critical ports, and not require approval from non-PPC maintainers, neither will there be any risk of your changes inconveniencing non-PPC port maintainers.

This was indeed the notion. A separate set of people can have commit permissions to that repository and can operate as they like, without bothering anyone working on the modern systems repository. It would eliminate conflicts.

As for the rest, I think some technical changes (such as permitting overlay Portfiles, like the "Portfile.ppc" notion) would make it easier for the committers to such a repository to get their work done, but ultimately it would be up to them.

**Comment by kencu** [comment]
> Can we get explicit opinions on the idea of a separate `macports-ports` repo that I proposed above?
> 
> * @kencu ?
> * @jmroot ?

I maintained TigerPorts and LeopardPorts for years for this reason. They were overlay port repos used by a number of folks. It was quite easy to do, to be honest. I still have them.

I am amazed/amused the way one person keeps obfuscating MacPorts' PowerPC support and support for 10.6-for-PPC. 

The former is fully supported by MacPorts, can use most existing portfiles transparently, and most maintainers wouldn't even know their port works nicely on a PowerPC system. 

The latter is an abomination that requires hundreds of unpleasant hacks and is utterly, pointlessly stupid, and seems to be all to support approximately one person.

Am I missing something here?

**Comment by kencu** [comment]
I may be the only person besides @barracuda156 who has ever installed and used 10.6-on-PPC, by the way.

I have the unpleasant duty to admit that I first showed him how MacPorts could be made to work on 10.6-on-PPC. Wish I could take that day back, to be honest.

**Comment by catap** [comment]
> I may be the only person besides @barracuda156 who has ever installed and used 10.6-on-PPC, by the way.

Well, at least 3 persons did it:
Screenshot 2024-01-12 at 03 54 58

and my setup is almost fully automated: https://github.com/catap/macos-ansible-playbooks

**Comment by kencu** [comment]
I keep trying to figure @mascguy 's game here... why the hell so strongly support this stupidity?

I guess it's kind of "Switzerland" -- we love everyone, everyone loves us, etc -- but really, there is a limit. 

These hacky patches and garbage Portfile spaghetti workarounds do absolutely nothing to enhance macports, or to bring in any meaningful users.

What's your deal?

**Comment by kencu** [comment]
> > I may be the only person besides @barracuda156 who has ever installed and used 10.6-on-PPC, by the way.
> 
> Well, at least 3 persons did it: Screenshot 2024-01-12 at 03 54 58
> 
> and my setup is almost fully automated: [catap/macos-ansible-playbooks](https://github.com/catap/macos-ansible-playbooks)

That looks like Parallels, and you can't run PPC on Parallels.

So if you mean that you set up an installation of Intel 10.6.8 configured to build as PPC, that is a different animal.

**Comment by kencu** [comment]
I assume most of you folks know what 10.6-for-PPC actually _is_, right?

**Comment by catap** [comment]
> That looks like Parallels, and you can't run PPC on Parallels.
> 
> So if you mean that you set up an installation of Intel 10.6.8 configured to build as PPC, that is a different animal.

Yes, this is so-called rosetta setup.

**Comment by kencu** [comment]
> That looks like Parallels, and you can't run PPC on Parallels. So if you mean that you set up an installation of Intel 10.6.8 configured to build as PPC, that is a different animal.
> Yes, this is so-called rosetta setup.

which is not what we’re talking about, of course

**Comment by mascguy** [comment]
Ken, I don't understand why you're unwilling to let this go.

Okay, we get it. You don't like this type of support in ports.

You made that clear 500 messages ago.

Meanwhile, we've all been utterly spammed by PR comments, messages to the Dev mailing list, etc.

Guess what? I don't like having to support Universal in all of my ports.

So why do I continue to do so? Because it's the right thing to do.

And when there are are an enthusiastic, motivated group of contributors - who've done a heck of a lot of work for PPC - I'm going to support their efforts as well.

Why? Because it's the right thing to do.

So can we cease this nonsense?

**Comment by kencu** [comment]
the nonsense is supporting it.

I just don’t understand your position here at all.

**Comment by kencu** [comment]
I’m no so convinced you’re representing the majority, or the moral high ground, with that statement.

Look, I left this until Josh called the play.

But solidier on…

**Comment by mascguy** [comment]
> I’m not so convinced you’re representing the majority, or the moral high ground, with that statement.
> 
> Look, I left this until Josh called the play.
> 
> But solidier on…

Ultimately the success of MacPorts depends on building goodwill, and retaining motivated contributors.

Okay, I'm stating the obvious, but hear me out.

You were kind enough to encourage and support me in the early days of my tenure, and I'll always appreciate that!

Now I'm trying to do the same here.

So at the end of the day, it's not so much about advocating for PPC. Rather, it's about supporting and encouraging our contributors.

Is that really such a bad thing...?

**Comment by pmetzger** [comment]
I'm mostly with @kencu and apparently @jmroot on this stuff.

**Comment by jmroot** [comment]
> So at the end of the day, it's not so much about advocating for PPC. Rather, it's about supporting and encouraging our contributors.

Wearing my portmgr hat: We should indeed be supportive and encouraging and respectful to contributors—*all* contributors. Unfortunately, sometimes interests come into conflict, and everyone can't always get what they want. A change that benefits one contributor may create a burden for others. We have to weight the costs against the benefits.

We have gone to quite a lot of trouble to ensure that anyone who wants to can use and distribute alternate Portfiles, ports trees, buildbots, signed archives and so on. Base is configurable, the infrastructure is all open source. This is to cater for modifications that are of interest to a subset of users but aren't appropriate for the main repo. It takes work to maintain such a thing, more work the more ports you want to modify, but it is very much possible and various individuals and groups have found it worth doing.

Ken: your points are taken and understood. Be mindful that simple repetition is unlikely to change anyone's mind though.

Everyone also please be mindful of how you phrase things; some recent posts have come close to what could be read as personal attacks, even if that's not how you meant it. I know English isn't everyone's first language, and that should be kept in mind, but we can all work on communicating better.

**Comment by barracuda156** [comment]
> That looks like Parallels, and you can't run 10.6-for-PPC on Parallels.

@kencu Well, obviously you do not have a native PowerPC cpu in Parallels, since the thing runs on Intel. However, you certainly _can_ run 10A190 in Parallels. I literally have it installed that way.
I do not use it much in Parallels, since 10.6.8 with Rosetta is there, but it is installable and it works.

> It is a crippled, early 10.6 version that offers absolutely nothing over 10.5 as Apple added basically nothing to the PPC components of it.

This is incorrect. 10.6 ppc (10A190) has certain components which are newer and improved over 10.5.8, and some components which are identical or a bit older. Specifically for development purposes it does offer an advantage, as long as we talk about 32-bit ppc.
There are minimal complications due to SDK being somewhat in between 10.5.8 and 10.6, most of which can be trivially fixed (by trivially I mean literally a few lines of code and often a single one). Overall, as I said, there are about 20 ports which do need minimal changes to support 10A190 specifically, and even those for the most part can be solved alternatively (say, configuring Macports to use a newer Perl).

There is nothing 10.5.8 can offer over 10.6 ppc, by the way, for 32-bit. Support for ppc64 is a big thing indeed, however presently Macports does not work for ppc64, as I was pointed out a number of times.

In some respects it is easier to use 10.6 ppc in Macports over 10.5.8, since 10.5.8 is stuck with archaic gcc7, and using a modern gcc requires local hacking.

**Comment by pmetzger** [comment]
10.6 was never officially released for PPC. The general consensus among the experts (like @jmroot and @kencu) is that we are not going to support it. You can always create a fork of MacPorts for this on your own if you feel it is important enough.

**Comment by mascguy** [comment]
> 10.6 was never officially released for PPC. The general consensus among the experts (like @jmroot and @kencu) is that we are not going to support it. You can always create a fork of MacPorts for this on your own if you feel it is important enough.

No, I don't think you're accurately representing where things stand.

We can - and will - continue to support these contributions. So essentially nothing has changed at this point.

Maintainers can choose not to accept them, as Josh has opted to do. And we need to respect that, as it's up to each maintainer.

Likewise, those of us who are fine with them, may continue to do accept and support them. It's maintainer choice.

**Comment by catap** [comment]
> Maintainers can choose not to accept them, as Josh has opted to do. And we need to respect that, as it's up to each maintainer.
> 
> Likewise, those of us who are fine with them, may continue to accept and support them. It's maintainer choice.

From another hand MacPorts has some ports which is used by tons of different ports, and decision to be or not to be for that port affects all dependant.
 
An example: if `cmake` do not support anything, it literally means that all ports which uses it to be built can't be used on that anything.

**Comment by mascguy** [comment]
> > Maintainers can choose not to accept them, as Josh has opted to do. And we need to respect that, as it's up to each maintainer.
> > 
> > Likewise, those of us who are fine with them, may continue to accept and support them. It's maintainer choice.
> 
> From another hand MacPorts has some ports which is used by tons of different ports, and decision to be or not to be for that port affects all dependant.
>  
> An example: if `cmake` do not support anything, it literally means that all ports which uses it to be built can't be used on that anything.

For `cmake`, I believe we're using path-style deps everywhere, to support the use of `cmake-devel`. And that allows use of an alternative drop-in replacement, if necessary.

And perhaps more use of path-style deps might be a good compromise: We already utilize them quite a bit - and have adopted them more broadly over the past year or two - making it easier to use alternatives.

We could certainly do the same for Python, for example. (Though I'd want Josh's blessing, before making such a change everywhere.)

But the point is that path-style deps might be the answer, to avoid the need for another repo.

Thoughts?

**Comment by kencu** [comment]
Please try for generically good fixes that improve macports as a whole… testing for functions and using or not using them depending on their presence, adding triples to build arguments when they are generally beneficial to add,  making universal more robust by finding edge cases and improving the muniversal code to cover them … rather than specifically oriented fixes based on what turn out to be fragile system and architecture assumptions.

I am guilty of this too, and it’s neigh time I upped my own game.

An upstreamable cmake test for a function is a much more valuable and robust contribution for everyone than a codeblock based on fragile system and arch assumptions.

Sergey’s building on off-piste systems exposes many flaws that are valuable to find and fix. After finding the same kind of flaws repeating in different builds, the right fix is often pretty clear. We all appreciate that, including upstreams that get clean, thight PRs coming out of macports that they can trust.

**Comment by mascguy** [comment]
> Please try for generically good fixes that improve macports as a whole… testing for functions and using or not using them depending on their presence, adding triples to build arguments when they are generally beneficial to add,  making universal more robust by finding edge cases and improving the muniversal code to cover them … rather than specifically oriented fixes based on what turn out to be fragile system and architecture assumptions.
> 
> I am guilty of this too, and it’s neigh time I upped my own game.
> 
> An upstreamable cmake test for a function is a much more valuable and robust contribution for everyone than a codeblock based on fragile system and arch assumptions.

That's a great point, Ken.

And we may need to coach/assist folks as well, particularly for contributors who don't have deep knowledge of CMake, AutoTools, etc.

**Comment by catap** [comment]
> For `cmake`, I believe we're using path-style deps everywhere, to support the use of `cmake-devel`. And that allows use of an alternative drop-in replacement, if necessary.
> 
> And perhaps more use of path-style deps might be a good compromise: We already utilize them quite a bit - and have adopted them more broadly over the past year or two - making it easier to use alternatives.
> 
> We could certainly do the same for Python, for example. (Though I'd want Josh's blessing, before making such a change everywhere.)
> 
> But the point is that path-style deps might be the answer, to avoid the need for another repo.
> 
> Thoughts?

It will be disaster.

MacPorts contains tons of reinplace where `/urs/bin/python3` is replaced by `${prefix}/...`

**Comment by mascguy** [comment]
> It will be disaster.
> 
> MacPorts contains tons of reinplace where `/urs/bin/python3` is replaced by `${prefix}/...`

Well, the key is that an alternative port would need to provide the same binaries, libs, etc. (Otherwise they couldn't serve as a drop-in replacement.)

Does that make sense?

**Comment by catap** [comment]
> > MacPorts contains tons of reinplace where `/urs/bin/python3` is replaced by `${prefix}/...`
> 
> Well, the key is that an alternative port would need to provide the same binaries, libs, etc. (Otherwise they couldn't serve as a drop-in replacement.)
> 
> Does that make sense?

Yes, and it solves Sergey's python issue on the first place.

**Comment by mascguy** [comment]
> > > MacPorts contains tons of reinplace where `/urs/bin/python3` is replaced by `${prefix}/...`

> > Well, the key is that an alternative port would need to provide the same binaries, libs, etc. (Otherwise they couldn't serve as a drop-in replacement.)
> > 
> > Does that make sense?

> Yes, and it solves Sergey's python issue on the first place.

There's just one caveat: We probably wouldn't want folks to start copy-pasting existing ports, where the new one is 99% identical to the original. (Apart from, say, an additional patch.) So perhaps Python wasn't a good example.

For such a case, perhaps some type of overlay scheme (or optional include) would be better, as suggested by Herby and others.

**Comment by catap** [comment]
> There's just one caveat: We probably wouldn't want folks to start copy-pasting existing ports, where the new one is 99% identical to the original. (Apart from, say, an additional patch.) So perhaps Python wasn't a good example.
> 
> For such a case, perhaps some type of overlay scheme (or optional include) would be better, as suggested by Herby and others.

As far as I dig this topic the question is rewording define at one patch.

So, here we are continue to talk about fork / overlay that means that someone should sync it and solve merge conflict.

Or, this patch should be ship in main tree.

From where I'm the only way is main tree, and it has a dead lock because maintainer of that port is against such changes.

Let me be blank: I did forks a number of times, and I strongly suggest do not do it to anyone, it quite time consuming for things like solving conflict which demotivates guys who supports it, and almost all forks dies.

**Comment by jmroot** [comment]
> No, I don't think you're accurately representing where things stand.
> 
> We can - and will - continue to support these contributions. So essentially nothing has changed at this point.
> 
> Maintainers can choose not to accept them, as Josh has opted to do. And we need to respect that, as it's up to each maintainer.

To be clear, I don't think many maintainers will want to sign up for this.

Something along the lines of LeopardPorts is likely the best way forward. It's much more tractable if you limit it to only ports that you want to actually use. (Making everything work was never a realistic goal even if everyone was on board; look at how many ports don't work on 10.6 x86_64.)

I'll be unsubscribing from notifications for this PR now. I think @barracuda156 has enough information to decide whether to drop maintainership, and the other topics raised should be discussed in a more appropriate forum.

**Comment by barracuda156** [comment]
@mascguy @kencu @catap I close this draft for now, since it looks like we could, hopefully, find a solution which can satisfy at least hard requirements of all sides.

Specifically for Python some Macports-based solution is needed, which would not require touching Josh’s pythons. Since Python upstream was uninterested to fix anything for _any_ macOS – they do not make a difference between 10.6 ppc and x86, they just want everything to remain broken :) 
There is no tremendous urgency with this, and the discussion should be moved to Trac or mailing list.

Besides, given that Python universal builds are broken on 10.5.8, and while I have those fixed, I won’t obviously submit it now, since it gonna be rejected by Josh again, and there is no utility in annoying him when the outcome is known in advance, perhaps path-style dependency may be indeed a workable solution.

**Pull request closed without merging**
