### PR TITLE
asciinema: use Python 3.7

### PR DESCRIPTION
**Pull request by mohd-akram**
Closes: https://trac.macports.org/ticket/57436

###### Type(s)

- [x] enhancement

###### Tested on
macOS 10.14.2 18C54
Xcode 10.1 10B61

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. (Something seems to be wrong with Travis but it seems to have nothing to do with your change.)

**Comment by l2dy** [comment]
> LGTM. (Something seems to be wrong with Travis but it seems to have nothing to do with your change.)

The Travis CI issue has been fixed. `upx` destroyed the binary, so I repacked it with `upx-devel`.

**Comment by pmetzger** [comment]
BTW, @larryv, could this be openmaintainer?

**Comment by l2dy** [comment]
Thanks for your contribution!

**Pull request merged**
