### PR TITLE
c-ares: Add cmake build and .cmake files

### PR DESCRIPTION
**Pull request by essandess**
c-ares: Add cmake build and .cmake files
* Fixes https://trac.macports.org/ticket/62167#ticket
* Related: https://github.com/macports/macports-ports/pull/7791

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by tobypeterson** [comment]
Would you like to maintain this port? 😅

**Comment by tobypeterson** [comment]
Also, can you ensure that this still builds when gtest is installed? I just pushed a commit to try to fix that issue.

**Comment by essandess** [comment]
> Would you like to maintain this port? 😅

I'll update it when I see that's necessary, but I'm unable to commit to port maintenance.

**Comment by tobypeterson** [comment]
This does appear to build with gtest installed, but the cmake build doesn't seem to build the tests which were failing.

Note, since the version didn't change, will probably need to set dist_subdir - by default, it doesn't include the revision, so it'll conflict with existing distfiles.

**Comment by tobypeterson** [comment]
I added `configure.args      -DCARES_BUILD_TESTS=ON` and verified that the gtest-related issue doesn't occur. So my only real feedback (unless you want to enable tests) is the `dist_subdir` issue.

**Comment by essandess** [comment]
Thanks for the great and prompt feedback! I added `dist_subdir` and tests, and am able to run these successfully.

**Comment by tobypeterson** [comment]
Still a slight tweak, I think. dist_subdir should be something starting with `${name}/` so that the files at least go inside the same directory

**Comment by essandess** [comment]
Thanks, changed. No  special reason to use the git tarball, except simplifying and standardizing things like a specialized livecheck.

**Comment by tobypeterson** [comment]
Ugh, I just noticed that this changes the library's compat version from 7 to 2.

**Comment by essandess** [comment]
> Ugh, I just noticed that this changes the library's compat version from 7 to 2.

I know just enough to be dangerous about this stuff. Please advise.

**Comment by tobypeterson** [comment]
Just means that we _may_ need to chase the update with revbumps on dependents. I'm not sure how the rev-upgrade functionality works (tries to automatically rebuild to handle changes like this).

**Comment by essandess** [comment]
Is this an issue that we should report upstream? I honestly don’t know enough about this to characterize the issue and post it.

> Just means that we _may_ need to chase the update with revbumps on dependents. I'm not sure how the rev-upgrade functionality works (tries to automatically rebuild to handle changes like this).
> 
> But it's also concerning, it's a major inconsistency between the project's configure/make build system and the cmake files.

**Comment by essandess** [comment]
There's also this issue with `livecheck` because [c-ares/c-ares](https://github.com/c-ares/c-ares) uses tags like `1_17_1`:
```
port livecheck re2 c-ares
re2 seems to have been updated (port version: 2021-02-01, new version: 2021-02-02)
Error: livecheck failed for c-ares: extracted version '1_17_1' is older than livecheck.version '1.17.1'
```
If anyone knows the `livecheck` fix, please post.

**Comment by tobypeterson** [comment]
> Is this an issue that we should report upstream? I honestly don’t know enough about this to characterize the issue and post it.

Pretty complicated issue. It's not really a bug in c-ares, it's a long-standing bug in GNU libtool; I'm doubtful that the maintainers of GNU libtool agree with me. Arguably the cmake build does the right thing.

To be safe, it probably makes sense to bump the revision for the relatively few ports that depend on c-ares.

**Comment by tobypeterson** [comment]
One thing you can do is add `github.tarball_from releases` (_after_ git.branch, it's a little finicky). Then you can revert to the previous checksums and remove `dist_subdir`. For some reason, they are generating two tarballs per release, what you're currently fetching is github's automatically-generated one, not the real release tarball.

As for the livecheck issue; no immediately obvious solution stands out to me. Could use the previous livecheck, or maybe try extracting from `${github.homepage}/releases` instead of `${github.homepage}/tags`

**Comment by kencu** [comment]
As opposed to re2, #9836, it looks like c-ares has indeed done all the legwork to make it properly build with cmake and provide all the needed tweaks <https://github.com/c-ares/c-ares/blob/master/INSTALL.md>

**Comment by essandess** [comment]
Fixed both the tarball and livecheck issues.

**Comment by tobypeterson** [comment]
Sorry, dropped the ball on this. Can you prepare another PR to bump the revision for the various c-ares dependents? I think, to be safe, we should bump them all to ensure that they rebuild against this.

**Comment by essandess** [comment]
Should this another commit to this PR? Can it be a single commit? Or one commit per port? How does one determine all the ports? `port echo depends:c-ares` looks like it only shows the ones I have installed.

> Sorry, dropped the ball on this. Can you prepare another PR to bump the revision for the various c-ares dependents? I think, to be safe, we should bump them all to ensure that they rebuild against this. This change looks good now.

**Comment by essandess** [comment]
What about adding a single commit to this PR that revamps these ports in a single commit?

```bash
find ${prefix}/var/macports/sources/rsync.macports.org/macports/release/tarballs/ports/ -type f -name Portfile -exec fgrep -l port:c-ares {} ';' | sed -E -e 's|^.+/([^/]+)/Portfile|\1|'
grpc
mosquitto
wireshark2
wireshark3
aria2
etherape
wireshark22
curl
libexosip2
wireshark30
py-gevent
py-grpcio
nghttp2
bzflag
```

**Comment by essandess** [comment]
@tobypeterson ping I believe this is ready to go.

**Comment by tobypeterson** [comment]
CI doesn't seem happy...

**Comment by essandess** [comment]
The number of builds in these two commits almost certainly broke it, so I wouldn’t view its unhappiness as diagnostic.

> CI doesn't seem happy..

**Comment by tobypeterson** [comment]
Alright here we go!

**Pull request merged**
