### PR TITLE
Switch various ports to perl5.28

### PR DESCRIPTION
**Pull request by mojca**
Not yet finished.

See: https://trac.macports.org/ticket/58361

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
@mojca its unclear to me why this is wip. What is stopping us updating the ports this pr currently addresses now ? I am not sure what from the trac ticket the fixes here are waiting for ?

**Comment by mojca** [comment]
I don't recall why exactly I made in WIP.

I certainly didn't do any quality control whatsoever, the CI reports a bunch of build failures (but I would dare to bet none of them are new; one of the failures is in `bugzilla`'s dependency `mysql5`; not sure if that's the only one) and my initial plan was to complete the list of perl's dependents (probably this was the reason for declaring it WIP). But we don't need to do the full list at once, so it's probably ok to merge this now and address the remaining ports later.

**Comment by cjones051073** [comment]
I agree, waiting to get everything done at once does not seem necessary to me. merge what we can when we have it..

**Comment by cjones051073** [comment]
@mojca As you are the author of the commits, I suggest you merge this whenever you see if.

**Pull request merged**
