### PR TITLE
mariadb: use MP libtool

### PR DESCRIPTION
**Pull request by kencu**
closes: https://trac.macports.org/ticket/58271

### CODE REVIEW

**Comment by l2dy** [comment]
Typo in commit message: `s/mariahdb/mariadb/`.

**Comment by michaelld** [comment]
Can we just move the port to use MP's libtool, rather than picking and choosing? I'd prefer a global solution if it works here.

**Comment by kencu** [comment]
Outright simplest would be to just have it call libtool without forcing a specific libtool path. Then the right one is found via your path setting in all situations I can ponder.

**Comment by michaelld** [comment]
If you could, please make it so & force push over this PR, including the commit info fix as requested.

**Pull request merged**
