### PR TITLE
py-matplotlib: update to latest version

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR updates matplotlib to 3.0.0 for supported Python versions (=> 3.5); Python 2.7 and 3.4 are updated to 2.2.3 LTS.

It updates dependencies, patches, variants/backends and such. There are quite some changes and I left it in separate commits to (hopefully) make reviewing easier. I tested a variety of different variant combinations and to me it seems to work as intended... Nevertheless, since ```matplotlib``` probably a package used by many, please do not merge before @seanfarley and possibly others have looked at it to make sure it's all good.

###### Tested on

macOS 10.13.6 17G65
Xcode 10.0 10A255
Python 2.7, 3.6, 3.7

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)? Commits can be squashed if really needed after review...
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`? N/A
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
It doesn't look like we're getting a review from @seanfarley particularly soon. :(

**Comment by pmetzger** [comment]
@reneeotten Do you want me to merge this without review from @seanfarley as it appears we might not be getting that review?

**Comment by michaelld** [comment]
I'm not the owner of this port, and I haven't actually tested building but the buildbots seem happy. A casual read through looks good to me. I like the style used in the changes, and they seem pretty straight forward. Hence, my advice is that if the actual maintainer has been given ample opportunity & has chosen to not respond (due to anything or nothing), then go ahead and merge this as it would be beneficial for MacPorts.

**Comment by michaelld** [comment]
I'm also happy to test on some of my build systems to see what happens, which would add a few days delay.

**Comment by pmetzger** [comment]
@reneeotten If we haven't heard by tomorrow I may merge this.

**Comment by reneeotten** [comment]
@pmetzger @michaelld I am pretty sure it will build correctly (not sure about all systems though). The main point is the different backends - I think they all work, but haven't used all of them extensively so it's hard to tell. I think the update itself shouldn't cause any issues, and if something doesn't work I'd be happy to look into it.

**Comment by pmetzger** [comment]
Merged. Thanks for the update, @reneeotten! Hopefully no bad stuff will come of it.

**Pull request merged**
