### PR TITLE
git: do not bundle tk for gui

### PR DESCRIPTION
**Pull request by mohd-akram**
Fixes: https://trac.macports.org/ticket/62036
Fixes: https://trac.macports.org/ticket/64249

###### Type(s)

- [x] bugfix

###### Tested on
macOS 12.1 21C52 x86_64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
Thanks for this, @mohd-akram.  Thinking about this, Tk feels like quite a heavy requirement for Git.

I'm beginning to think that maybe the GUI features of git should be split into a subport or variant.  Git is such a foundational dependency that its requirements really should be kept as light as possible, and requiring Tk, which itself requires x11 and all of the associated dependencies just to be able to run git feels like way too much.

@ryandesign, thoughts?

**Comment by ryandesign** [comment]
I have recently been using Git Gui so I'm glad it's in MacPorts. Switching it to use MacPorts Tk seems like a good idea. I agree Tk has a lot of dependencies and splitting it off into a separate git-gui subport would be ideal, if that can be achieved.

**Comment by reneeotten** [comment]
I agree that adding these as default dependencies is too much, a variant or subport would be ideal. So since this PR will likely not get merged anyway should we just close it? @herbygillot @ci42 do you add this to your to-do list or should @mohd-akram open a Trac ticket to request this?

**Comment by mohd-akram** [comment]
I've changed the fix to work with whichever tk is in the PATH. If the MacPorts one is installed, it will be used, otherwise the system one will be used. Variant/subport can be done later.

**Comment by reneeotten** [comment]
> I've changed the fix to work with whichever tk is in the PATH. If the MacPorts one is installed, it will be used, otherwise the system one will be used. Variant/subport can be done later.

I am not sure we want to do that as it seems to me that will violate [ReproducibleBuilds](https://trac.macports.org/wiki/ReproducibleBuilds), right?

**Comment by mohd-akram** [comment]
I don't see how it does. If anything, it makes the build reproducible since we're no longer packaging a random version of macOS Tk.

**Comment by chrstphrchvz** [comment]
“Build reproducibility” might be too specific of a term here, in that there would still be non-reproducibility from the user’s perspective if things depend on what is in the path at runtime.

If this PR is closed in favor of ticket investigation, there is already some discussion in https://trac.macports.org/ticket/64249 (which I’ve neglected to follow up on and see if others want to decide whether or not to keep the “.app”s—which presumably require Tk built as a framework, which I don’t know if MacPorts can/wants to provide).

**Comment by reneeotten** [comment]
@herbygillot @mohd-akram can anyone get this moving and add the `git-gui` subport or whatever is the decided solution (I am not convinced we want to merge the current PR, but again I don't use it)

**Review by herbygillot — APPROVED** [review]

**Pull request merged**
