### PR TITLE
upc: upgrade for isl14 port

### PR DESCRIPTION
**Pull request by kencu**
closes: https://trac.macports.org/ticket/54067

###### Tested on
macOS 10.6 and 10.12

### CODE REVIEW

**Comment by kencu** [comment]
FYI this port is maintained by takeshi@macports.org, is labelled openmaintainer, and uses the same fix as @MarcusCalhoun-Lopez used to fix gcc48.

**Comment by kencu** [comment]
This does work, if anyone is stuck trying to install this while we await the maintainer's approval.

**Comment by kencu** [comment]
A month (or so) is long enough to wait, I think. This can be here for anyone who might want it someday.

**Comment by kencu** [comment]
My apologies for closing this. If it makes it easier to fix the port, I'm happy to leave this up. -K

**Comment by kencu** [comment]
```
$ port -v installed upc
The following ports are currently installed:
  upc @5.2.0.1_1 (active) platform='darwin 10' archs='x86_64' date='2017-05-02T21:33:34-0700'

$ port contents upc | grep bin
  /opt/local/bin/gupc
  /opt/local/lib/upc/bin/cpp
  /opt/local/lib/upc/bin/gcc
  /opt/local/lib/upc/bin/gcc-ar
  /opt/local/lib/upc/bin/gcc-nm
  /opt/local/lib/upc/bin/gcc-ranlib
  /opt/local/lib/upc/bin/gcov
  /opt/local/lib/upc/bin/gcov-tool
  /opt/local/lib/upc/bin/gupc
  /opt/local/lib/upc/bin/upc
  /opt/local/lib/upc/bin/x86_64-apple-darwin10-gcc
  /opt/local/lib/upc/bin/x86_64-apple-darwin10-gcc-5.2.0
  /opt/local/lib/upc/bin/x86_64-apple-darwin10-gcc-ar
  /opt/local/lib/upc/bin/x86_64-apple-darwin10-gcc-nm
  /opt/local/lib/upc/bin/x86_64-apple-darwin10-gcc-ranlib
  /opt/local/lib/upc/bin/x86_64-apple-darwin10-gupc
  /opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/include/clwbintrin.h

$ /opt/local/bin/gupc --version
gupc (GCC) 5.2.0 20150816 (GNU UPC 5.2.0-1)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by kencu** [comment]
I don't see any major reason why this couldn't be committed. This fix works as it should, the port works to make a correctly running version of the upc test program from the upc user manual <http://www.gccupc.org/gnu-upc-external/gnu-upc-user-manual>, and this port is broken as it is without the isl14 fix.

Evidence:
```
$ port -v installed upc
The following ports are currently installed:
  upc @5.2.0.1_1 (active) platform='darwin 10' archs='x86_64' date='2017-05-02T21:33:34-0700'
```
```
$ gupc --version
gupc (GCC) 5.2.0 20150816 (GNU UPC 5.2.0-1)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
$ cat count.upc
#include <upc.h>
#include <stdio.h>

int
main ()
{
  int i;
  for (i = 0; i < THREADS; i++)
    {
      if (MYTHREAD == i)
        {
          printf ("%d ", i + 1);
        }
    }
}
```
```
$ gupc -v count.upc
Driving: gupc -fupc -mmacosx-version-min=10.6.8 -v count.upc
Using built-in specs.
COLLECT_GCC=gupc
COLLECT_LTO_WRAPPER=/opt/local/libexec/upc/gcc/x86_64-apple-darwin10/5.2.0/lto-wrapper
Target: x86_64-apple-darwin10
Configured with: /opt/local/var/macports/build/_opt_macports-ports_lang_upc/upc/work/upc-5.2.0.1/configure --prefix=/opt/local --build=x86_64-apple-darwin10 --build=x86_64-apple-darwin10 --bindir=/opt/local/lib/upc/bin --libdir=/opt/local/lib/upc --libexecdir=/opt/local/libexec/upc --datarootdir=/opt/local/share/upc --with-local-prefix=/opt/local --with-system-zlib --disable-nls --without-gnu-ld --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local/libexec/isl14 --disable-isl-version-check --disable-bootstrap --disable-multilib --enable-lto --with-upc-backtrace-gdb=ggdb --enable-languages=c --with-as=/opt/local/bin/as --with-ls=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --build=x86_64-apple-darwin10
Thread model: posix
gcc version 5.2.0 20150816 (GNU UPC 5.2.0-1) (GCC) 
COLLECT_GCC_OPTIONS='-fupc' '-mmacosx-version-min=10.6.8' '-v' '-mtune=core2'
 /opt/local/libexec/upc/gcc/x86_64-apple-darwin10/5.2.0/cc1 -quiet -v -D__DYNAMIC__ count.upc -fupc -include gcc-upc.h -fPIC -quiet -dumpbase count.upc -mmacosx-version-min=10.6.8 -mtune=core2 -auxbase count -version -fupc -o /var/folders/I0/I0fOotq3ErGZHYxrmmWiqU+++TI/-Tmp-//cc5Fc9kY.s
GNU C99 (GCC) version 5.2.0 20150816 (GNU UPC 5.2.0-1) (x86_64-apple-darwin10)
	compiled by GNU C version 4.2.1 Compatible Clang 3.9.1 (tags/RELEASE_391/final), GMP version 6.1.2, MPFR version 3.1.5, MPC version 1.0.3
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/../../../../../x86_64-apple-darwin10/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/include
 /opt/local/include
 /opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/include-fixed
 /usr/include
 /System/Library/Frameworks
 /Library/Frameworks
End of search list.
GNU C99 (GCC) version 5.2.0 20150816 (GNU UPC 5.2.0-1) (x86_64-apple-darwin10)
	compiled by GNU C version 4.2.1 Compatible Clang 3.9.1 (tags/RELEASE_391/final), GMP version 6.1.2, MPFR version 3.1.5, MPC version 1.0.3
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: 2cd8dbc4178224c8da36fabcdc1d574a
COLLECT_GCC_OPTIONS='-fupc' '-mmacosx-version-min=10.6.8' '-v' '-mtune=core2'
 /opt/local/bin/as -v -arch x86_64 -force_cpusubtype_ALL -o /var/folders/I0/I0fOotq3ErGZHYxrmmWiqU+++TI/-Tmp-//cco7yRkn.o /var/folders/I0/I0fOotq3ErGZHYxrmmWiqU+++TI/-Tmp-//cc5Fc9kY.s
Apple Inc version cctools-895, GNU assembler version 1.38
COMPILER_PATH=/opt/local/libexec/upc/gcc/x86_64-apple-darwin10/5.2.0/:/opt/local/libexec/upc/gcc/x86_64-apple-darwin10/5.2.0/:/opt/local/libexec/upc/gcc/x86_64-apple-darwin10/:/opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/:/opt/local/lib/upc/gcc/x86_64-apple-darwin10/
LIBRARY_PATH=/opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/:/opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/../../../:/usr/lib/
Reading specs from /opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/../../../upc-crtbegin.spec
Reading specs from /opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/../../../libgupc.spec
Reading specs from /opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/../../../upc-crtend.spec
COLLECT_GCC_OPTIONS='-fupc' '-mmacosx-version-min=10.6.8' '-v' '-mtune=core2'
 /opt/local/libexec/upc/gcc/x86_64-apple-darwin10/5.2.0/collect2 -dynamic -arch x86_64 -macosx_version_min 10.6.8 -weak_reference_mismatches non-weak -o a.out -lcrt1.10.6.o /opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/../../../upc-crtbegin.o -L/opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0 -L/opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/../../.. /var/folders/I0/I0fOotq3ErGZHYxrmmWiqU+++TI/-Tmp-//cco7yRkn.o -lgupc -lm -no_compact_unwind -lSystem -lgcc_ext.10.5 -lgcc -lSystem /opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/../../../upc-crtend.o -v
collect2 version 5.2.0 20150816 (GNU UPC 5.2.0-1)
/opt/local/bin/ld -dynamic -arch x86_64 -macosx_version_min 10.6.8 -weak_reference_mismatches non-weak -o a.out -lcrt1.10.6.o /opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/../../../upc-crtbegin.o -L/opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0 -L/opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/../../.. /var/folders/I0/I0fOotq3ErGZHYxrmmWiqU+++TI/-Tmp-//cco7yRkn.o -lgupc -lm -no_compact_unwind -lSystem -lgcc_ext.10.5 -lgcc -lSystem /opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/../../../upc-crtend.o -v
@(#)PROGRAM:ld  PROJECT:ld64-274.1
configured to support archs: i386 x86_64 x86_64h armv6 armv7 armv7s armv7m armv7k arm64 (tvOS)
Library search paths:
	/opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0
	/opt/local/lib/upc
	/usr/lib
Framework search paths:
	/Library/Frameworks/
	/System/Library/Frameworks/
 /opt/local/bin/nm -n /opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/../../../upc-crtbegin.o
 /opt/local/bin/nm -n /var/folders/I0/I0fOotq3ErGZHYxrmmWiqU+++TI/-Tmp-//cco7yRkn.o
 /opt/local/bin/nm -n /opt/local/lib/upc/gcc/x86_64-apple-darwin10/5.2.0/../../../upc-crtend.o
```
```
$ ./a.out -fupc-threads-5
1 4 2 5 3
```

**Comment by raimue** [comment]
Thank you for the patch and the detailed test output!

**Pull request closed without merging**
