### PR TITLE
Update multiple python ports

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.5.1 21G83 x86_64
Xcode 14.0 14A309

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
Just for the record: I'm maintainer or co-maintainer of all affected ports.

**Comment by reneeotten** [comment]
@catap what has changed so that none of the ports apparently need to use `setuptools` anymore...? At least for some of the CI failures the removal of that ports is the issue - can you please check this again?

**Comment by catap** [comment]
@reneeotten thanks, my mistake: I thought that PG python adds it always. After double checking I've realized that it's adding such dependencies only when pep517 is enabled and it depends on backend.

=> reverting.

**Comment by reneeotten** [comment]
> @reneeotten thanks, my mistake: I thought that PG python adds it always. After double checking I've realized that it's adding such dependencies only when pep517 is enabled and it depends on backend.
> 
> => reverting.

yes, that happens indeed only when `python.pep517` is set to yes then as default the `setuptools` backend is used and hence the dependency added. I guess you didn't build it locally in trace-mode then as you checked of in the PR checklist - if so you would have seen this ;) 

Thanks for reverting that change. I think everything else looks good so I'll merge!

**Pull request merged**
