### PR TITLE
libevent: update version to 2.1.11

### PR DESCRIPTION
**Pull request by ra1nb0w**
#### Description

- bump version to 2.1.11
- remove patch because already upstream

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.15 19A558d
Xcode 11.0 11A419c

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM.

**Comment by jerryyhom** [comment]
Looks fine, thanks.

**Comment by ra1nb0w** [comment]
thank you!

**Comment by ryandesign** [comment]
I guess this changed the library in some way that required all ports that use the library to be rebuilt. See 8aca3a536325c4c93a076f26ab074447d9ffdb4e. In the future, any such needed revbumps should be done in the same PR as the update.

**Comment by ra1nb0w** [comment]
@ryandesign How do you checks if ABI change? use `rev-upgrade` only?

**Pull request merged**
