### PR TITLE
WIP boost: update to 1.73.0

### PR DESCRIPTION
**Pull request by michaelld**
WIP to Update Boost from 1.71.0 to 1.73.0

Closes: https://trac.macports.org/ticket/59834

Please see the ticket for details. The short version is that we need to rev-bump dependent ports because the ABI has changed from any prior Boost ABI that might be installed.

Please contribute rev-bumps for your Boost-dependent ports!

### CODE REVIEW

**Comment by dbevans** [comment]
@michaelld: the ports that only use boost headers should probably declare boost as a build rather than a lib dependency but I'll handle that independently of this PR.

**Comment by michaelld** [comment]
> @michaelld: the ports that only use boost headers should probably declare boost as a build rather than a lib dependency but I'll handle that independently of this PR.

Agreed! If/when you go through with that change, I'd recommend added in a comment to the effect of what you wrote here: header only, so no rev-bump required for updated Boost!

**Comment by pmetzger** [comment]
There are conflicts to resolve, FYI.

**Comment by michaelld** [comment]
> There are conflicts to resolve, FYI.

That's going to happen, since I'd guess it'll take a while for this PR to get enough additions to it for us to feel like we've done diligence verifying this new Boost within MP. I'll resolve conflicts once we get to to the point of merging.

**Comment by cjones051073** [comment]
So can we make progress on this ? I think waiting for all port maintainers to submit updates here is impractical. I would favour being progress, so make the update and then deal with the bumps as needed (many ports using boost will not need it if they only use header-only features of Boost).

**Comment by michaelld** [comment]
Sadly ... or, maybe not ... Boost 1.73.0 should be released any day now ... there are already commits in Boost GIT noting such. And, the version history shows that there is regularly a release in mid-April: https://www.boost.org/users/history/ ... so, I'm inclined to wait until that release, then go hard-core to update this PR & fix issue with it & get this (update to that version) PR merged.

**Comment by michaelld** [comment]
[drumroll, please] As noted in my prior post: Boost 1.73.0 is released on 2020-04-26 < https://www.boost.org/users/history/version_1_73_0.html >. I'll test / fix locally & update this PR accordingly. Then, I hope to be able to work quickly to get ports rev-bumped & tested, so-as to get this new Boost into MP in reasonably short order. 🤞

**Comment by cjones051073** [comment]
> [drumroll, please] As noted in my prior post: Boost 1.73.0 is released on 2020-04-26 < https://www.boost.org/users/history/version_1_73_0.html >. I'll test / fix locally & update this PR accordingly. Then, I hope to be able to work quickly to get ports rev-bumped & tested, so-as to get this new Boost into MP in reasonably short order. 🤞

I would suggest not wasting too much time on the rev-bumping and testing. Previously experience  suggests this just ends up being long and drawn out and never really ending..  I would be a bit more aggressive, make the update, commit it, and deal with any fallout as is...

**Comment by michaelld** [comment]
> I would suggest not wasting too much time on the rev-bumping and testing. Previously experience suggests this just ends up being long and drawn out and never really ending.. I would be a bit more aggressive, make the update, commit it, and deal with any fallout as is...

I like this idea!

It looks like this Boost changes boost::bind, which is used with many projects including ones I help maintain. So ... testing ports will be more important with this version than some prior versions. 1.72.0 was highly backward compatible.

... so ... let's do some initial testing / fixing and get an idea of roughly how many ports will be impacted, and then we can make a decision on how to proceed.

**Comment by michaelld** [comment]
We're up to Boost 1.74.0 now ... This PR is very stale, so I'm closing it and will do another. Hopefully this new Boost will be more project-compatible than the 1.73.0 was.

**Pull request closed without merging**
