### PR TITLE
ocp: new port @0.2.105

### PR DESCRIPTION
**Pull request by kencu**
Open Cubic Player
closes: https://trac.macports.org/ticket/67733

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.4.1 22F82 arm64
Xcode 14.3.1 14E300c

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by kencu** [comment]
@ryandesign -- I'll leave this here if you're interested

**Comment by barracuda156** [comment]
@kencu It does not support `libsdl` as a fallback, right? (Some currently developed ports still do.)

**Comment by kencu** [comment]
> @kencu It does not support `libsdl` as a fallback, right? (Some currently developed ports still do.)

I believe it can. That might be a nice enhancement for the systems that don’t support libsdl2.

Also sdl is not a hard requirement.

I didn’t try older systems … it uses core audio so there could be issues.

**Comment by ryandesign** [comment]
> I believe it can. That might be a nice enhancement for the systems that don’t support libsdl2.

I'm adding sdl1 and sdl2 variants. Both work for me on Monterey. I think sdl2 works in MacPorts back to Snow Leopard at least but if we need to default to sdl1 on older systems we can.

**Comment by ryandesign** [comment]
> I am not sure about 10.6 Intel

There is a separate [libsdl2-snowleopard port](https://ports.macports.org/port/libsdl2-snowleopard) (which the libsdl2 port uses on Snow Leopard and earlier) so I assume at least the intention is that this would work on Snow Leopard and earlier.

**Comment by barracuda156** [comment]
> > I am not sure about 10.6 Intel
> 
> There is a separate [libsdl2-snowleopard port](https://ports.macports.org/port/libsdl2-snowleopard) (which the libsdl2 port uses on Snow Leopard and earlier) so I assume at least the intention is that this would work on Snow Leopard and earlier.

Thank you, I will try it. Somehow missed that one.

**Comment by kencu** [comment]
libsdl2-snowleopard works nicely for SL Intel.

Defaulting MacPorts SnowLeopard support to what SnowLeopard-PowerPC can support would be an unfortunate approach.

**Comment by barracuda156** [comment]
> libsdl2-snowleopard works nicely for SL Intel.
> 
> Defaulting MacPorts SnowLeopard support to what SnowLeopard-PowerPC can support would be an unfortunate approach.

Thankfully, we have arch settings and do not have to coerce every arch to behave identically :)

**Comment by kencu** [comment]
> Thankfully, we have arch settings and do not have to coerce every arch to behave identically :)

and yet, look what happened here.

**Pull request merged**
