### PR TITLE
cssed: fix the build

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Updated with patches from @kencu 
Now the build should be fine across the board with GCC and Clang alike.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

macOS 10A190
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
CI fails on:
```
then mv -f ".deps/LexCaml.Tpo" ".deps/LexCaml.Po"; else rm -f ".deps/LexCaml.Tpo"; exit 1; fi
  ../src/LexCaml.cxx:278:14: error: assigning to 'char *' from 'const char *' discards qualifiers
                                  || ((o = strchr(")]};,\'\"`#", ch)) != 0)/* "termination" chars */
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
```

**Comment by barracuda156** [comment]
Perhaps related to this in configure log? Just GCC does not err out, but Clang does.
```
configure:7368: checking for memmove
configure:7425: /opt/local/bin/gcc-mp-12 -o conftest -pipe -Os -arch ppc -I/opt/local/include -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc conftest.c  >&5
conftest.c:63:6: warning: conflicting types for built-in function 'memmove'; expected 'void *(void *, const void *, long unsigned int)' [-Wbuiltin-declaration-mismatch]
   63 | char memmove ();
      |      ^~~~~~~
conftest.c:50:1: note: 'memmove' is declared in header '<string.h>'
   49 | # include <limits.h>
   50 | #else
configure:7431: $? = 0
configure:7435: test -z 
			 || test ! -s conftest.err
configure:7438: $? = 0
configure:7441: test -s conftest
configure:7444: $? = 0
configure:7456: result: yes
configure:7368: checking for memset
configure:7425: /opt/local/bin/gcc-mp-12 -o conftest -pipe -Os -arch ppc -I/opt/local/include -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc conftest.c  >&5
conftest.c:64:6: warning: conflicting types for built-in function 'memset'; expected 'void *(void *, int,  long unsigned int)' [-Wbuiltin-declaration-mismatch]
   64 | char memset ();
      |      ^~~~~~
conftest.c:51:1: note: 'memset' is declared in header '<string.h>'
   50 | # include <limits.h>
   51 | #else
configure:7431: $? = 0
configure:7435: test -z 
			 || test ! -s conftest.err
configure:7438: $? = 0
configure:7441: test -s conftest
configure:7444: $? = 0
configure:7456: result: yes
configure:7368: checking for munmap
configure:7425: /opt/local/bin/gcc-mp-12 -o conftest -pipe -Os -arch ppc -I/opt/local/include -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc conftest.c  >&5
configure:7431: $? = 0
configure:7435: test -z 
			 || test ! -s conftest.err
configure:7438: $? = 0
configure:7441: test -s conftest
configure:7444: $? = 0
configure:7456: result: yes
configure:7368: checking for strchr
configure:7425: /opt/local/bin/gcc-mp-12 -o conftest -pipe -Os -arch ppc -I/opt/local/include -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc conftest.c  >&5
conftest.c:66:6: warning: conflicting types for built-in function 'strchr'; expected 'char *(const char *, int)' [-Wbuiltin-declaration-mismatch]
   66 | char strchr ();
      |      ^~~~~~
conftest.c:53:1: note: 'strchr' is declared in header '<string.h>'
   52 | # include <limits.h>
   53 | #else
configure:7431: $? = 0
configure:7435: test -z 
			 || test ! -s conftest.err
configure:7438: $? = 0
configure:7441: test -s conftest
configure:7444: $? = 0
configure:7456: result: yes
configure:7368: checking for strstr
configure:7425: /opt/local/bin/gcc-mp-12 -o conftest -pipe -Os -arch ppc -I/opt/local/include -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc conftest.c  >&5
conftest.c:67:6: warning: conflicting types for built-in function 'strstr'; expected 'char *(const char *, const char *)' [-Wbuiltin-declaration-mismatch]
   67 | char strstr ();
      |      ^~~~~~
conftest.c:54:1: note: 'strstr' is declared in header '<string.h>'
   53 | # include <limits.h>
   54 | #else
```

**Comment by barracuda156** [comment]
@kencu Okay, I need help. This port is broken now on every system after El Capitan. It was also broken on Snow Leopard.

I fixed it on 10.6 (both 10.6.8 and 10A190), but it still fails on new systems with Clang. This could be the reason: https://trac.osgeo.org/geos/ticket/30
Since Clang apparently does not support `-fpermissive`, I wanna try building it with GCC.

The problem: Macports does not honor:
```
if {${os.platform} eq "darwin" && ${os.major} > 15} {
    compiler.blacklist-append *clang*
}
```
and still uses Clang. You said we should avoid whitelists. What to do here? :)

**Comment by barracuda156** [comment]
Okay, it builds fine with GCC. I am not gonna fix this for Clangs. If anyone wishes – fixes are welcome.

**Comment by kencu** [comment]
We can't disable all clang builds on newer systems... usually you'd patch the source to fix this.
```
LexCaml.cxx: error: assigning to 'char *' from 'const char *' discards qualifiers
```

you will probably find that someone upstream has already done this, as clang builds are not rare, and adding ```-fpermissive``` is not a good fix anyway (makes it ignore errors it should generally not ignore).

**Comment by barracuda156** [comment]
> We can't disable all clang builds on newer systems... usually you'd patch the source to fix this.
> you will probably find that someone upstream has already done this, as clang builds are not rare, and adding `-fpermissive` is not a good fix anyway (makes it ignore errors it should generally not ignore).

@kencu Well, It is an old port… to make it more painful, sources use Windows-style line endings, so diff/patch is broken. I had enough of it, really :) Not worth spending another hour, especially given that I cannot test clangs locally (and do not work with them anyway).

If anyone interested to fix it for new Clangs – welcome. Here the choice is either leave it broken for new systems or have it fixed with GCC.
**At the moment it just does not build on any system above El Capitan**: https://ports.macports.org/port/cssed/details/

**Comment by kencu** [comment]
This fixes the build on Mojave, at least, using all default compilers.

```
$ cat patch-cssed-const-char.diff
diff --git scintilla/src/LexCaml.cxx scintilla/src/LexCaml.cxx
index 26b2867..61cdd76 100644
--- scintilla/src/LexCaml.cxx
+++ scintilla/src/LexCaml.cxx
@@ -275,7 +275,7 @@ void ColouriseCamlDoc(
 			// [try to] interpret as [additional] operator char
 			char* o = 0;
 			if (iscaml(ch) || isspace(ch)			/* ident or whitespace */
-				|| ((o = strchr(")]};,\'\"`#", ch)) != 0)/* "termination" chars */
+				|| ((o = (char*)strchr(")]};,\'\"`#", ch)) != 0)/* "termination" chars */
 				|| !strchr("!$%&*+-./:<=>?@^|~", ch)/* "operator" chars */) {
 				// check for INCLUSIVE termination
 				if (o && strchr(")]};,", ch)) {
```

**Comment by kencu** [comment]
this port needs a bit more fixup. the config.guess etc are old. This gets you new ones to properly recognize current systems:

```
platform darwin {
    depends_build-append port:automake
    post-patch {
        # Use newer config.guess and config.sub
        set automake_dirs [glob -directory ${prefix}/share automake-*]
        set automake_dir [lindex [lsort -command vercmp $automake_dirs] end]
        copy -force ${automake_dir}/config.guess ${automake_dir}/config.sub \
            ${worksrcpath}
    }
}
```

and this one gets the system properly recognized as a darwin system:

```
$ cat patch-cssed-configure-system.diff
--- configure.orig	2022-10-24 17:16:19.000000000 -0700
+++ configure	2022-10-24 17:16:42.000000000 -0700
@@ -5919,7 +5919,7 @@
 *-*-cygwin*)
 	OSTYPE="CYGWIN"
 	;;
-powerpc-apple-darwin*)
+*-apple-darwin*)
 	OSTYPE="DARWIN"
 	;;
 i[3456]86-*-*bsd*)
```

**Comment by barracuda156** [comment]
@kencu Thank you! I will implement these. (Converting to draft for now.)

**Comment by barracuda156** [comment]
@kencu Thank you for help, now all should be good.

**Comment by barracuda156** [comment]
@kencu Any issues left to deal with? Or can we merge this?

**Comment by barracuda156** [comment]
@kencu Bump, we should merge this finally.

**Comment by kencu** [comment]
OK, please keep an eye out for build failures.

**Pull request merged**
