### PR TITLE
boehmgc: update to 8.2.4

### PR DESCRIPTION
**Pull request by ivmai**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13
Xcode 9.4

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
CI fails with a checksum mismatch.

**Comment by ryandesign** [comment]
Since this project offers release downloads, they should be used, by setting `github.tarball_from releases` and `distname gc-${version}`. Checksums may need to be updated after doing that. `use_autoreconf yes` and the comments above it can probably be removed then as well. Reverify that the port builds after these changes.

`platforms darwin` is the default now and can be removed.

**Comment by ivmai** [comment]
@ryandesign Could you please recheck this PR?
Thank you

**Comment by ivmai** [comment]
@barracuda156, @mascguy, could you please review the patch?
Thank you

**Comment by barracuda156** [comment]
@ivmai Let me try building it.

**Comment by ryandesign** [comment]
Thanks. I'm moving the `github.tarball_from` and `distname` lines further down in the portfile to where I usually place them. The purpose of putting the `checksums` lines close to where the version is specified (in the `github.setup` line in this case) is so that the two variables that are most likely to be the only ones updated in each version of the port are close together, so that the size of the diff reviewers read is as small as possible. Placing additional nonchanging lines between those two variables is contrary to that goal. I'll squash this down when merging.

**Pull request merged**
