### PR TITLE
py-pytorch: Update to version 1.12.0, Add Python 310

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.4 21F79 x86_64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Steve, will all other Python 3.10 dependencies be in place, once your other PR is merged? (https://github.com/macports/macports-ports/pull/15258)

**Comment by essandess** [comment]
> Steve, will all other Python 3.10 dependencies be in place, once your other PR is merged? (#15258)

I’m trying to update stuff that’s upstream of this (and #15258). I believe this is a stand-alone that should be able to merge.

**Comment by mascguy** [comment]
We'll also want to simplify test-related items for `py-pytorch`, similar to my comment on your other PR: https://github.com/macports/macports-ports/pull/15258#discussion_r922860648

**Comment by essandess** [comment]
> We'll also want to simplify test-related items for `py-pytorch`, similar to my comment on your other PR: [#15258 (comment)](https://github.com/macports/macports-ports/pull/15258#discussion_r922860648)

I do not have the cycles to modify these test phases.

**Comment by mascguy** [comment]
> > We'll also want to simplify test-related items for `py-pytorch`, similar to my comment on your other PR: [#15258 (comment)](https://github.com/macports/macports-ports/pull/15258#discussion_r922860648)
> 
> I do not have the cycles to modify these test phases.

The changes are absolutely trivial; please see my subsequent commit.

Unfortunately I don't have cycles to fix everyone's PRs, either. So going forward, you'll need to address requested items, if you want these committed.

**Review by mascguy — APPROVED** [review]
Fixed test support - the conditional check for CUDA was broken, due to a logic error - and simplified.

But tested locally on 10.15, and looks good. (I'm not sure why we're seeing CI failures... perhaps it's due to the large number of dependencies and such.)

**Pull request merged**
