### PR TITLE
statcvs: delete port

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Port has never been updated since submitted in 2004; has been outdated since release of 0.2.3 in 2006; latest version is 0.7.0, released 2010

Has fallback dependency on deprecated port `kaffe`
See https://trac.macports.org/ticket/60206

Has indirect dependency on EOL port `servlet24-api` (via dependency on outdated port `jfreechart`)
See: https://trac.macports.org/ticket/58389

No dependents.

(Does anyone still even use CVS?)

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

### CODE REVIEW

**Comment by emcrisostomo** [comment]
Is there some way to measure a port's usage statistics (e.g.: number of installations), even if indirectly (for example, through download statistics?)

**Comment by chrstphrchvz** [comment]
> Is there some way to measure a port's usage statistics (e.g.: number of installations), even if indirectly (for example, through download statistics?)

So far I'm only aware of voluntarily-reported statistics at https://ports.macports.org/port/statcvs/stats?days=365&days_ago=0 where no installations are reported.

Also https://ports.macports.org/port/statcvs/builds indicates that this port fails to install on the build bots, but no one has opened a ticket reporting this; I would guess that the dependencies `junit` and `jfreechart` which have issues building might be causing this. I have not tried installing `statcvs` myself.

**Comment by emcrisostomo** [comment]
Thanks. Yeah, with that information it would be astonishing that someone were still using this port out there. I've tried installing it in my machine and a dependency of its (`jfreechart`) fails to build. Apparenty, it uses undocumented APIs:

```/opt/local/var/macports/build/_opt_macports-ports_java_jfreechart/jfreechart/work/jfreechart-1.0.0-pre2/source/org/jfree/chart/encoders/SunJPEGEncoderAdapter.java:42: error: package com.sun.image.codec.jpeg does not exist
```

which were removed in Java 7 more than eight years ago (in 2011)! See here for reference:

[Java SE 7 and JDK 7 Compatibility](https://www.oracle.com/technetwork/java/javase/compatibility-417013.html)

I bet we can delete this port and nobody will notice. Is there anybody else who wants to review this and clarify the port deletion policy?

**Comment by chrstphrchvz** [comment]
> I've tried installing it in my machine and a dependency of its (`jfreechart`) fails to build.

Thanks for trying that. `jfreechart` is another port I have considered deleting, which is why I've started with proposing to delete `statcvs`. I recently opened an update ticket for `jfreechart` (https://trac.macports.org/ticket/60200) since it hasn't been updated since 2005, even though there have been several new upstream releases up until a few years ago. I have now mentioned there that there are issues building the port.

> I bet we can delete this port and nobody will notice. Is there anybody else who wants to review this and clarify the port deletion policy?

I have been told there is no policy on deleting ports; I have found there are a variety of opinions, though. See see https://github.com/macports/macports-ports/pull/4167#issuecomment-486840359 and https://lists.macports.org/pipermail/macports-dev/2019-February/040071.html. Some MacPorts members are more eager to remove ports while others are more hesitant. Sometimes deleting or proposing to delete a port has been enough for someone to step in and finally improve it. The deprecated portgroup was also created as a response to this subject, so that ports can be kept but with slightly better documentation what problems they might have (e.g. discontinued/unsupported by upstream, or lack of support by MacPorts).

**Comment by emcrisostomo** [comment]
I had a look at the information you posted, thanks for the time you're putting into this task. I also had a look at the `deprecated` port group, which basically states that a port is deprecated when at least one of the following is true:
* the port no longer builds on recent versions of macOS and/or Xcode
* the project is no longer maintained upstream
* the port is severely out of date, and maintaining it has become a burden no-one wants to take on

Since it seems there's no port deletion policy, here are my thoughts:
* The last update to this port happened almost ten years ago. That qualifies as `dead` in my dictionary.
* The port's purpose is gathering statistics about a revision control system whose last stable release has been published 12 years ago.
* I haven't been able to find relevant, real world CVS usage statistic, and the lack thereof may be a proof of its irrelevance.
* This port can't build because a dependency doesn't build.
* The dependence doesn't build because it's using an API that has been removed almost 10 years ago. The port _cannot_ and _will not_ work unless somebody ports that code, which seems highly unlikely.

I draw these conclusion:
* The port, as is, is useless, since it relies on deprecated and/or removed dependencies (the aforementioned API).
* Upstream is useless for the same reasons.

Hence, I bet to delete it and reduce its noise.

Let's wait some days to see whether somebody else adds his own opinions.

**Comment by emcrisostomo** [comment]
Ok, it seems like nobody else has something to add, and further investigation seems to indicate that we can assume that this port is more dead than alive.

**Pull request merged**
