### PR TITLE
dejagnu: Add needed dependencies for 10.4 and 10.5.

### PR DESCRIPTION
**Pull request by fhgwright**
The system tcl is too old on 10.4 and 10.5, so the tcl and expect
ports are needed.

TESTED:
Using libffi tests (not always passing) as an example, ran on
10.4-10.5 ppc, 10.4-10.6 i386, and 10.5-10.15 x86_64.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
Mac OS X 10.4.11 8S165, PPC, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, i386, Xcode 2.5 8M2558
Mac OS X 10.5.8 9L31a, PPC, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, i386, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, x86_64, Xcode 3.1.4 9M2809
Mac OS X 10.6.8 10K549, i386, Xcode 3.2.6 10M2518
Mac OS X 10.6.8 10K549, x86_64, Xcode 3.2.6 10M2518
Mac OS X 10.7.5 11G63, x86_64, Xcode 4.6.3 4H1503
OS X 10.8.5 12F2560, x86_64, Xcode 5.1.1 5B1008
OS X 10.9.5 13F1911, x86_64, Xcode 6.2 6C131e
OS X 10.10.5 14F2511, x86_64, Xcode 7.2 7C68
OS X 10.11.6 15G22010, x86_64, Xcode 8.1 8B62
macOS 10.12.6 16G2136, x86_64, Xcode 9.2 9C40b
macOS 10.13.6 17G14033, x86_64, Xcode 10.1 10B61
macOS 10.14.6 18G6032, x86_64, Xcode 11.3.1 11C505
macOS 10.15.6 19G2021, x86_64, Xcode 12.0.1 12A7300

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [N/A] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [N/A] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
LGTM.

FYI -- I have basically given up on fixing libffi 3.3 for 10.4 and 10.5 i386 and so have pegged my systems < 10.6 back to libffi 3.2.1. I can't really see anything that 3.3 adds to those systems that 3.2.1 doesn't already do anyway. There is no version of GO that will ever run on those systems, and the go bindings are totally useless.

Depending on dev-list-thinking, I would think we should just do that for MacPorts as a whole on < 10.6 forever, unless some restless i386 assembly genius comes along with extreme motivation and fixes the test runs.

**Comment by kencu** [comment]
minor change, affects only ancient systems, @larryv has no such systems, and we haven't seen him for -- years.

**Comment by fhgwright** [comment]
Given how miserably libffi 3.2.1 fails tests, even on 10.9, I wouldn't be too quick to conclude that 3.3 has nothing to offer.

"Bare" build (with CFLAGS=-integrated-as) of 3.2.1 on 10.9:
# of expected passes		1205
# of unexpected failures	705
# of unsupported tests		28

MacPorts build of 3.2.1 on 10.9:
# of expected passes		1185
# of unexpected failures	685

"Bare" build (with CFLAGS=-integrated-as) of 3.3 on 10.9:
# of expected passes		544
# of unsupported tests		206

MacPorts build of 3.3 on 10.9:
# of expected passes		544
# of unsupported tests		206

Beware that libffi 3.3 also fails 6 tests on 10.6 i386, all floating-point-related.

**Comment by kencu** [comment]
I left my test runs in the ticket, mostly. At least we've lived with 3.2.1 for years now, so whatever evil it was going to have done, it's done. I have so much potentially useful stuff to get done that spending more time on libffi for me is not on the list any more :>

**Comment by kencu** [comment]
Oh, BTW -- Ryan was not too happy about the PR I committed for you, so if you get some time, please fix it up and resubmit it, for him to review.

**Comment by fhgwright** [comment]
> Oh, BTW -- Ryan was not too happy about the PR I committed for you, so if you get some time, please fix it up and resubmit it, for him to review.

Fix it up in what way?

**Comment by kencu** [comment]
I didn't read it too carefully -- you'll have to take it up with Ryan. His comments are in the commit tree.

**Pull request merged**
