### PR TITLE
py-virtualenv, py-setuptools: bump 16.2.0 & 40.6.3

### PR DESCRIPTION
**Pull request by gthb**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by gthb** [comment]
`sudo port test` failed for me with this in `main.log`:

```
:debug:test LIBRARY_PATH='/opt/local/lib'
:debug:test MACOSX_DEPLOYMENT_TARGET='10.13'
:debug:test PYTHONPATH='/opt/local/var/macports/build/_Users_gthb_macports_python_py-virtualenv/py36-virtualenv/work/virtualenv-16.2.0/build/lib'
:info:test Executing:  cd "/opt/local/var/macports/build/_Users_gthb_macports_python_py-virtualenv/py36-virtualenv/work/virtualenv-16.2.0" && py.test-3.6 
:debug:test system:  cd "/opt/local/var/macports/build/_Users_gthb_macports_python_py-virtualenv/py36-virtualenv/work/virtualenv-16.2.0" && py.test-3.6 
:info:test ImportError while loading conftest '/opt/local/var/macports/build/_Users_gthb_macports_python_py-virtualenv/py36-virtualenv/work/virtualenv-16.2.0/tests/conftest.py'.
:info:test py._path.local.LocalPath.ImportMismatchError: ('conftest', '/Users/bgabor8/git/virtualenv/tests/conftest.py', local('/opt/local/var/macports/build/_Users_gthb_macports_python_py-virtualenv/py36-virtualenv/work/virtualenv-16.2.0/tests/conftest.py'))
:info:test Command failed:  cd "/opt/local/var/macports/build/_Users_gthb_macports_python_py-virtualenv/py36-virtualenv/work/virtualenv-16.2.0" && py.test-3.6 
:info:test Exit code: 4
:error:test Failed to test py36-virtualenv: command execution failed
:debug:test Error code: CHILDSTATUS 18694 4
```

... with a path referencing somebody else's `/Users/foo` folder. And sure enough, the virtualenv-16.2.0 tarball contains `.pyc` files from somebody else, that's definitely a mistake (and not present in the virtualenv-16.1.0 tarball):

```
$ tar tvfz virtualenv-16.2.0.tar.gz | grep pyc
drwxr-xr-x  0 bgabor8 staff       0  4 jan 14:00 virtualenv-16.2.0/tests/__pycache__/
-rw-------  0 bgabor8 staff    4469 27 des 09:40 virtualenv-16.2.0/tests/__pycache__/conftest.cpython-27-PYTEST.pyc
-rw-------  0 bgabor8 staff    3805 27 des 09:41 virtualenv-16.2.0/tests/__pycache__/conftest.cpython-34-PYTEST.pyc
-rw-------  0 bgabor8 staff    3787 31 des 10:56 virtualenv-16.2.0/tests/__pycache__/conftest.cpython-35-PYTEST.pyc
-rw-------  0 bgabor8 staff    3402 31 des 10:57 virtualenv-16.2.0/tests/__pycache__/conftest.cpython-36-PYTEST.pyc
-rw-------  0 bgabor8 staff    3391 26 des 12:10 virtualenv-16.2.0/tests/__pycache__/conftest.cpython-37-PYTEST.pyc
-rw-------  0 bgabor8 staff    4179 31 des 10:59 virtualenv-16.2.0/tests/__pycache__/conftest.pypy-27-PYTEST.pyc
-rw-------  0 bgabor8 staff    4494 27 des 09:40 virtualenv-16.2.0/tests/__pycache__/test_bootstrap.cpython-27-PYTEST
```

**Comment by gthb** [comment]
But removing those `.pyc` files:
```
sudo find python/py-virtualenv/work/virtualenv-16.2.0/ -iname  __pycache__ -delete
```
... got me past that problem, but still yielded test execution errors, which I'm attaching. So I guess port maintainer attention is needed here.

[port-test-py36-virtualenv-16.2.0.log](https://github.com/macports/macports-ports/files/2755442/port-test-py36-virtualenv-16.2.0.log)

**Comment by chrstphrchvz** [comment]
FYI: the maintainer of py-setuptools already decided to skip 40.6.3 due to no substantial changes, see https://github.com/macports/macports-ports/pull/3282#issuecomment-450343438

**Comment by gthb** [comment]
Right. But Virtualenv 16.2.0 declares setup_requires=["setuptools >=
40.6.3"] which is why I included that.

**Comment by pmetzger** [comment]
Conflicts need to be resolved.

**Comment by chrstphrchvz** [comment]
> Conflicts need to be resolved.

The maintainer of `py-setuptools` went ahead and updated it to 40.6.3, so that `py-virtualenv` can be updated: a22099d

**Comment by pmetzger** [comment]
There are conflicts, so we can't merge this as is. Can you fix them?

**Comment by jmroot** [comment]
@gthb indicated that there are problems that need to be fixed before merging anyway.

**Comment by reneeotten** [comment]
```py-virtualenv``` version 16.3.0 was released on January 25. It resolves the issue that ```__pychache__``` directories where included. But, it has now listed several more test dependencies that are not present in MacPorts yet, so for now I would suggest to just not run the tests (we can revisit this later, perhaps add the missing ports, and then re-enable the tests).

@gthb can you rework this PR to update to the newest version (probably after rebasing with master to get rid of the merge commit)?

**Comment by yan12125** [comment]
> so for now I would suggest to just not run the tests

I'm +1 for this idea. The latest virtualenv depends on pypiserver, which brings in a bunch of other dependencies.

**Comment by pmetzger** [comment]
@gthb hasn't commented in a while. Perhaps someone else wants to submit a new PR to do this stuff?

**Comment by reneeotten** [comment]
let’s give @gthb a few days. If nothing happens I can take care of this in the weekend.

**Pull request closed without merging**
