### PR TITLE
sigil: minor improvements; sigil-qt4: new port

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Plus minor improvements.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
sigil

**Comment by i0ntempest** [comment]
Thanks but this is too big of a change. I really don't want another situation like the old mkvtoolnix port. A much better way is a separate port with qt4 and qt5, and this port just remains qt6 only. That way we don't need to deal with version separation crap.
I can happily take your first 3 minor commits though.

**Comment by barracuda156** [comment]
@i0ntempest Is it good now with regard to `sigil` port?

(If qt4 version fails on CI, I restrict it to old systems. No point wasting time to fix it for new ones.)

**Comment by barracuda156** [comment]
macOS-11 failure is unrelated, it is a dependency failure:
```
Building dependency (1 of 1) 'qt6-qtwebengine' with variants '' ... [FAIL]
```

**Comment by i0ntempest** [comment]
If 0.6.2 is the newest version that supports qt4 and you dont want to add qt5, then you should disable livecheck so MP doesn't prompt you to update. Other than that, good to merge.

**Comment by barracuda156** [comment]
> If 0.6.2 is the newest version that supports qt4 and you dont want to add qt5, then you should disable livecheck so MP doesn't prompt you to update. Other than that, good to merge.

Fair point, done.

P. S. Not planning for Qt5 until/unless I can fix it on powerpc. If anyone will be interested, then it can be introduced, perhaps, as `sigil-qt5`.

**Comment by i0ntempest** [comment]
> P. S. Not planning for Qt5 until/unless I can fix it on powerpc. If anyone will be interested, then it can be introduced, perhaps, as `sigil-qt5`.

I meant to suggest putting qt4 and qt5 in the same portfile as sigil-legacy. But on another thought I think it's better to add qt5 back into the main port (if anyone needs it) since the newest sigil version support building with both. Anyways thanks for your contribution.

**Comment by barracuda156** [comment]
@i0ntempest Yeah, it makes a better sense to keep Qt4 separate, both for ease of maintenance and of removal (if Qt5 is fixed for earlier systems).

**Pull request merged**
