### PR TITLE
XLD: new source port

### PR DESCRIPTION
**Pull request by sideeffect42**
#### Description

This PR creates a new port which builds XLD from source (in contrast to audio/XLD which downloads the pre-built DMG).

Currently, this is a **draft**.
The application itself builds on my newer Mac, but without the Plug-Ins.
The Plug-Ins can be enabled in the Xcode build target but there are various build errors inside the plugins which I could not yet resolve.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

* macOS 12.7 21G816 x86_64
  Xcode 14.2 14C18
* Mac OS X 10.5.8 9L31a Power Macintosh
  Xcode 3.1.4 9M2809

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@sideeffect42 Sorry, I was busy with gcc13, and the we got a disaster with `R` ports after a mess with compilers in Macports (still unresolved).

Here is what the developer replied earlier, maybe that will be helpful?

> For XLDGainAnalyzer_* functions, add XLDGainAnalyzer.c/h to the project (which exists in the repository but forgot add to the project). It has a dependency to libebur128 and extra linker flag will also be needed.
> For SCDynamicStoreCopyProxies function linking to SystemConfiguration framework will be required.

**Comment by sideeffect42** [comment]
@barracuda156 np, just wanted to keep you updated.

These linker errors could be resolved and should not occur with this Portfile anymore.
In fact the build should run through and result in a runnable XLD.

The built XLD will, however, have an empty Plug-Ins directory which makes it not really useable as is.

If I enable the Plug-Ins (cf. my [port/aqua/XLD-plugins](https://github.com/sideeffect42/macports-ports/tree/port/aqua/XLD-plugins) branch), it fails already when trying to build `XLDWavpackOutput`:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-macos12.0 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -Wno-implicit-fallthrough -DOBJC_OLD_DISPATCH_PROTOTYPES\=1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -iquote /opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLD/build/XLDWavpackOutput_export.build/Release/XLDWavpackOutput.build/XLDWavpackOutput-generated-files.hmap -I/opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLD/build/XLDWavpackOutput_export.build/Release/XLDWavpackOutput.build/XLDWavpackOutput-own-target-headers.hmap -I/opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLD/build/XLDWavpackOutput_export.build/Release/XLDWavpackOutput.build/XLDWavpackOutput-all-target-headers.hmap -iquote /opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLD/build/XLDWavpackOutput_export.build/Release/XLDWavpackOutput.build/XLDWavpackOutput-project-headers.hmap -I/opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLD/build/Release/include -I/usr/local/include -I/opt/local/include -I/opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLD/build/XLDWavpackOutput_export.build/Release/XLDWavpackOutput.build/DerivedSources-normal/x86_64 -I/opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLD/build/XLDWavpackOutput_export.build/Release/XLDWavpackOutput.build/DerivedSources/x86_64 -I/opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLD/build/XLDWavpackOutput_export.build/Release/XLDWavpackOutput.build/DerivedSources -F/opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLD/build/Release -include /opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/DerivedData/Build/Intermediates.noindex/PrecompiledHeaders/SharedPrecompiledHeaders/3810287692074691938/XLDWavpackOutput_Prefix.pch -MMD -MT dependencies -MF /opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLD/build/XLDWavpackOutput_export.build/Release/XLDWavpackOutput.build/Objects-normal/x86_64/XLDWavpackOutputTask.d --serialize-diagnostics /opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLD/build/XLDWavpackOutput_export.build/Release/XLDWavpackOutput.build/Objects-normal/x86_64/XLDWavpackOutputTask.dia -c /opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLDWavpackOutput/XLDWavpackOutputTask.m -o /opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLD/build/XLDWavpackOutput_export.build/Release/XLDWavpackOutput.build/Objects-normal/x86_64/XLDWavpackOutputTask.o
In file included from /opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLDWavpackOutput/XLDWavpackOutputTask.m:9:
In file included from /opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLDWavpackOutput/XLDWavpackOutputTask.h:11:
/opt/local/include/wavpack/wavpack.h:46:3: error: typedef redefinition with different types ('struct ChunkHeader' (aka 'ChunkHeader') vs 'struct ChunkHeader')
} ChunkHeader;
  ^
In file included from /opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLDWavpackOutput/XLDWavpackOutputTask.m:1:
In file included from /opt/local/var/macports/build/_Development_macports-ports_aqua_XLD/XLD/work/xld-20230627/XLDWavpackOutput/XLDWavpackOutput_Prefix.pch:6:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:91:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:212:
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/AIFF.h:84:41: note: previous definition is here
typedef struct ChunkHeader              ChunkHeader;
                                        ^
```

**Comment by barracuda156** [comment]
@sideeffect42 Few notes:

1. Since we already [have](https://ports.macports.org/port/xld) `xld` port, it makes sense to add this as a subport (which I think I have done in my branch – if not, I should have that locally). @judaew what would you say?
2. Please do not make it abandoned from the go :) I can be a [co-]maintainer, or you guys take it, but no need to set it as `nomaintainer` port. It likely will _need_ to be maintained.
3. Doesn’t it use ALAC codec too? I thought it does, and made a port for it, but not sure it actually links in.
4. In principle, there are no reasons for `ppc64` not to be supported, as long as `ppc` is and 64-bit is. I would drop arch restriction.

**Comment by sideeffect42** [comment]
@barracuda156 

> 1. Since we already [have](https://ports.macports.org/port/xld) `xld` port, it makes sense to add this as a subport (which I think I have done in my branch – if not, I should have that locally). @judaew what would you say?

Having two ports does not make sense for sure. I created a new one in this case to have a cleaner diff while this PR is a draft. It should be cleaned up before merging.

However, I don't think a subport makes sense. Once XLD can be built from source, there is no reason to keep the "download DMG" port.

> 3. Doesn’t it use ALAC codec too? I thought it does, and made a port for it, but not sure it actually links in.

Yes, it also supports ALAC.

> 4. In principle, there are no reasons for `ppc64` not to be supported, as long as `ppc` is and 64-bit is. I would drop arch restriction.

AFAIK XLD uses QuickTime for some codecs, which is 32-bit only.
I'm not sure how amd64 is supported, but a quick grep in the code suggests that the plug-ins using QuickTime just don't get loaded, then.
Let's get everything to build first, and then have a look at this again.

**Comment by sideeffect42** [comment]
Thanks to the subport hint of @barracuda156 I had the idea to make use of subports to build the XLD plugins.

This way, no complex Xcode project magic is required and in combination with variants users can easily choose which plugins/formats they want and which ones they don't need.

There are a few problematic plugins, though:
1. `XLDApeDecoder` needs `libMAC` but the monkeys-audio port only installs the binary;
2. `XLDTakDecoder` needs wine and some DLL's;
3. `XLDHEAACOutput` needs [aacplusenc](https://github.com/teknoraver/aacplusenc) for which no port exists, yet.

**Comment by barracuda156** [comment]
@sideeffect42 Maybe e-mail the developer in regard of failing plug-ins?

**Comment by sideeffect42** [comment]
> @sideeffect42 Maybe e-mail the developer in regard of failing plug-ins?

Currently I don't think it's a problem with the plug-ins.
I tested some which failed using the `Portfile` manually with Xcode 3.1.4 and I could compile them just fine.

So I guess the problems are either due to incompatibilities between Xcode versions and/or missing patches to link to MacPorts-supplied libraries instead of bundled `.framework`s.

**Comment by judaew** [comment]
I like the idea when a package manager building a project from source code. If you can build it from source code, then the prebuild can be left as a subport.

**Comment by sideeffect42** [comment]
> What can be done to finish this off?

Making XLD buildable from source is not easy. It consists of various plug-ins which can be compiled and combined into the final product independently.
Also, building it is harder than necessary because the SVN project does not contain all the files necessary, files are not added to the Xcode projects as they should, or the Xcode projects need to be patched to either link against MacPorts' provided frameworks or target settings need to be adjusted for the build to work on all the different versions of Mac OS X.

The basic `XLD.app` should be buildable with this PR as it is, but the plug-ins are not ready, yet.

@pmetzger, if you want to help you could try to go through all of the plugins and check if they produce a `.bundle` which contains an executable and check if the format shows up in the "Output format" pop-up menu in XLD's General preferences.

What's also left to be done is that the monkeys-audio port produces a `.dylib` in addition to the `mac` binary.
From what I could tell this is an upstream issue.
(Installation of the man page would be a bonus IMO.)

**Comment by pmetzger** [comment]
@sideeffect42 I'm afraid I really don't have time to give that much attention to an individual port.

If this really isn't ready, probably the PR should not be in the queue. It should be worked on in private.

**Comment by sideeffect42** [comment]
This PR was intentionally marked as a draft.

**Comment by pmetzger** [comment]
So, I've said this before, but I kind of don't like the "draft" mechanism. It leads to the pull queue being full of things that really shouldn't be getting attention from people who are trying to groom the queue and get things dealt with.

The price of this is that once in a while (even a few days ago, this actually happen) we'll find stuff where a request that is totally actionable has been sitting in the queue for half a year with no one having noticed it because there's too much stuff competing for attention. In many such cases, I think the lack of attention for prolonged periods of time convinces otherwise valuable contributors to MacPorts to not participate any longer.

Ideally our pull queue would contain no more than a dozen things at a time, the people grooming the queue would know at a glance what the status of all of them was, and everything in it could be resolved quickly one way or another. Unfortunately, we currently sometimes have things sitting in the queue for months or even years without any movement.

**Comment by barracuda156** [comment]
@sideeffect42 How about we work on it ourselves first? I want this port and it will be actually useful to have it. But @pmetzger is right, it is not helpful to have it in the queue as draft for months.

**Comment by pmetzger** [comment]
FWIW, I highly encourage you guys doing the work! Just keep in mind the merge queue is for things that the author thinks can be merged.

**Pull request closed without merging**
