### PR TITLE
legacy-support: update -devel subport and fix some build/test issues

### PR DESCRIPTION
**Pull request by fhgwright**
#### Description

This has three commits - one to fix the 11.x +universal build, one to fix the 10.6-10.8 test build failures, and one to update the -devel subport to the latest master.  See the individual commit messages for more details.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

```
Mac OS X 10.4.11 8S165, PPC, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, i386, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, x86_64, Xcode 2.5 8M2558
Mac OS X 10.5.8 9L31a, PPC, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, i386, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, x86_64, Xcode 3.1.4 9M2809
Mac OS X 10.6.8 10K549, i386, Xcode 3.2.6 10M2518
Mac OS X 10.6.8 10K549, x86_64, Xcode 3.2.6 10M2518
Mac OS X 10.7.5 11G63, x86_64, Xcode 4.6.3 4H1503
OS X 10.8.5 12F2560, x86_64, Xcode 5.1.1 5B1008
OS X 10.9.5 13F1911, x86_64, Xcode 6.2 6C131e
OS X 10.10.5 14F2511, x86_64, Xcode 7.2 7C68
OS X 10.11.6 15G22010, x86_64, Xcode 8.1 8B62
macOS 10.12.6 16G2136, x86_64, Xcode 9.2 9C40b
macOS 10.13.6 17G14042, x86_64, Xcode 10.1 10B61
macOS 10.14.6 18G9323, x86_64, Xcode 11.3.1 11C505
macOS 10.15.7 19H15, x86_64, Xcode 12.4 12D4e
macOS 11.7.10 20G1427, x86_64, Xcode 13.2.1 13C100
macOS 11.7.10 20G1427, arm64, Xcode 13.2.1 13C100
macOS 12.7.3 21H1015, x86_64, Xcode 14.2 14C18
macOS 12.7.3 21H1015, arm64, Xcode 14.2 14C18
macOS 13.6.4 22G513, arm64, Xcode 15.2 15C500b
macOS 14.3.1 23D60, arm64, Xcode 15.2 15C500b
```

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [N/A] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by cjones051073** [comment]
I probably need to give over maintainership of the legacy support ports to someone else at this stage. Since my last intel based mac died I now only have arm machines, and as such can no longer run any of my old system VMs, necessary to test legacy support properly on the older systems it is there for. This is not to say I am not still interested in contributing, just that someone else better suited to directly test might be better off taking over here... any takers ?

**Comment by mascguy** [comment]
> I probably need to give over maintainership of the legacy support ports to someone else at this stage. Since my last intel based mac died I now only have arm machines, and as such can no longer run any of my old system VMs, necessary to test legacy support properly on the older systems it is there for. This is not to say I am not still interested in contributing, just that someone else better suited to directly test might be better off taking over here... any takers ?

I'd be willing to co-maintain it. Anyone else want to join me? @kencu?

**Comment by mascguy** [comment]
> I'd be willing to co-maintain it. Anyone else want to join me? @kencu?

To be fair, there are already a few of us who unofficially shepherd this repo. So it doesn't really matter to me...

**Comment by fhgwright** [comment]
@cjones051073 
> I probably need to give over maintainership of the legacy support ports to someone else at this stage. Since my last intel based mac died I now only have arm machines, and as such can no longer run any of my old system VMs, necessary to test legacy support properly on the older systems it is there for. This is not to say I am not still interested in contributing, just that someone else better suited to directly test might be better off taking over here... any takers ?

I'd be willing to do that.  I can test all non-oddball platforms except 13.x+ x86_64 (which isn't very relevant for `legacy-support`, anyway :-)).  The only oddball cases I can't test are 10.4-10.5 `ppc64`, since my Quad G5 isn't currently usable (needs an LCS overhaul).

**Review by mascguy — APPROVED** [review]

**Comment by cjones051073** [comment]
@fhgwright Please feel free to make the changes to the maintainer settings in the changing myself to you if you are willing to take over.

**Comment by fhgwright** [comment]
> @fhgwright Please feel free to make the changes to the maintainer settings in the changing myself to you if you are willing to take over.

**Comment by cjones051073** [comment]
Likewise @mascguy if you want to co maintain thats totally fine with me as well.

**Comment by fhgwright** [comment]
@cjones051073 
> @fhgwright Please feel free to make the changes to the maintainer settings in the portfile changing myself to you if you are willing to take over.

> Likewise @mascguy if you want to co maintain thats totally fine with me as well.

OK.  That might as well wait until the update for the release version, which I expect will happen fairly soon.

**Comment by cjones051073** [comment]
Just to add, part of maintaining the port is actually also cutt8ng new releases of the underlying code from https://github.com/macports/macports-legacy-support which only mapcorts maintainers can do. I see @mascguy you have already done this a few times, so I think it makes sense you also make yourself maintainer of the port.

**Comment by mascguy** [comment]
> Just to add, part of maintaining the port is actually also cutting new releases of the underlying code from https://github.com/macports/macports-legacy-support which only macports maintainers can do. I see @mascguy you have already done this a few times, so I think it makes sense you also make yourself maintainer of the port.

Works for me!

**Pull request merged**
