### PR TITLE
lua-luasec: fix the broken port, update to 1.2.0, use openssl PG

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

The port is broken across the board now: https://ports.macports.org/port/lua-luasec/details/
Hopefully this PR fixes it, at least for a subset of systems.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

macOS 10A190
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
@mojca Maybe you could help me here?
```
env MACOSX_DEPLOYMENT_TARGET='11.0' /usr/bin/clang -arch x86_64 -D_DARWIN_C_SOURCE -bundle -undefined dynamic_lookup -L./luasocket -L/opt/local/lib -o ssl.so options.o x509.o context.o ssl.o config.o ec.o -lssl -lcrypto -lluasocket
  ld: library not found for -lssl
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  make[2]: *** [ssl.so] Error 1
```
Doesn’t PG set dependency automatically?

**Comment by barracuda156** [comment]
@kencu Any idea what is going wrong and why PG does not work?

**Comment by barracuda156** [comment]
@reneeotten Could you please help with this? This is a totally broken port now. My PR fixes it, as minimum, for 10.6, 11 and 12, likely other systems too.

**Comment by barracuda156** [comment]
@reneeotten @harens I think this is perfectly mergeable.

**Review by harens — APPROVED** [review]
Thanks @barracuda156! 👍

**Pull request merged**
