### PR TITLE
imager: update version to 202311

### PR DESCRIPTION
**Pull request by PenguenJulien**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by reneeotten — CHANGES_REQUESTED** [review]
Please make sure to follow the PR checklist - these things are there for a reason 😉. 

The CI fails, so please fix the error(s) and make sure to squash commits and that the commit message follows our guidelines.

**Comment by PenguenJulien** [comment]
Hello,
I don't understand this error, I try with -p0, -p1, -p2 but always the same problem
Could you help me?

**Comment by barracuda156** [comment]
@PenguenJulien Perhaps you just do not need any patch pre_arg?

Also, please update the PR title, it is unclear which port is being updated.

**Comment by PenguenJulien** [comment]
i try to remove patch.pre_args but always problem ...

**Comment by barracuda156** [comment]
Normally if you generate patches with diff from a root directory, you do not need pre_args, if you generate via git-patch, you need -p1 or otherwise use --no-prefix. Never seen anything besides -p1 (and implicit -p0) being used.

**Comment by barracuda156** [comment]
It fill be far more readable to have the title (both commit itself and PR) as:
“imager: update version to xxxx”.

**Comment by reneeotten** [comment]
ping @PenguenJulien are you planning to finish this up and address the comments?

**Pull request closed without merging**
