### PR TITLE
sphinxtrain: update to 1.0.8

### PR DESCRIPTION
**Pull request by l2dy**
###### Description

*(delete all below for minor changes)*

###### Tested on
macOS 10.12.3
Xcode 8.2.1

###### Verification
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? (Please don't open a new Trac ticket if you are submitting a pull request.)
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -v install`?
- [ ] tested basic functionality of all binary files? (delete if not applicable)

### CODE REVIEW

**Comment by mojca** [comment]
This is a lot more than just a plain update, it would be nice to add a slightly longer description of changes in the commit message as well.

**Comment by l2dy** [comment]
@mojca Amended.

Some problems:
1. I've got no idea how to use this software and thus couldn't test its functionality.
2. Docs are missing from the tarball (alpha version don't have them too).

`sphinxtrain -t a setup` creates the following files:
```
./etc/feat.params
./etc/sphinx_train.cfg
```
But `sphinxtrain run` complains files `etc/a_train.fileids` `etc/a_test.fileids` `etc/a.dic` are missing. I guess these files are to be manually created because they are missing from the tarball (in etc) too.

Port contents:

```
$ port contents sphinxtrain
Port sphinxtrain contains:
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SphinxTrain-1.0-py2.7.egg-info
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/__init__.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/__init__.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/arpalm.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/arpalm.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/classlm2fst.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/classlm2fst.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/cluster_mixw.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/cluster_mixw.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/corpus.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/corpus.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/dict_spd.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/dict_spd.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/divergence.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/divergence.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/evaluation.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/evaluation.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/feat/_1s_c_d_dd.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/feat/_1s_c_d_dd.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/feat/__init__.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/feat/__init__.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/feat/s2_4x.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/feat/s2_4x.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/fstutils.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/fstutils.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/gmm.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/gmm.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/hmm.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/hmm.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/htkmfc.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/htkmfc.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/hypseg.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/hypseg.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lat2dot.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lat2dot.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lat2fsg.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lat2fsg.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lat_rescore.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lat_rescore.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lat_rescore_fst.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lat_rescore_fst.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lattice.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lattice.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lattice_conv.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lattice_conv.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lattice_error.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lattice_error.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lattice_error_fst.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lattice_error_fst.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lattice_prune.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lattice_prune.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lda.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/lda.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/mfcc.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/mfcc.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/mllr.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/mllr.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/mllt.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/mllt.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/prune_mixw.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/prune_mixw.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/quantize_mixw.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/quantize_mixw.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s2mfc.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s2mfc.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3dict.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3dict.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3file.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3file.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3gau.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3gau.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3gaucnt.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3gaucnt.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3lda.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3lda.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3mdef.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3mdef.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3mixw.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3mixw.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3model.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3model.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3senmgau.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3senmgau.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3tmat.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/s3tmat.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/sendump.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/sendump.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/test_arpalm.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/test_arpalm.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/test_corpus.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/test_corpus.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/test_evaluation.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/test_evaluation.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/test_hmm.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/test_hmm.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/test_s3dict.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/test_s3dict.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/test_s3file.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/test_s3file.pyc
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/test_s3model.py
  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmusphinx/test_s3model.pyc
  /opt/local/bin/sphinxtrain
  /opt/local/include/sphinxtrain/acmod_set.h
  /opt/local/include/sphinxtrain/best_q.h
  /opt/local/include/sphinxtrain/ck_seg.h
  /opt/local/include/sphinxtrain/common.h
  /opt/local/include/sphinxtrain/corpus.h
  /opt/local/include/sphinxtrain/cvt2triphone.h
  /opt/local/include/sphinxtrain/div.h
  /opt/local/include/sphinxtrain/dtree.h
  /opt/local/include/sphinxtrain/file.h
  /opt/local/include/sphinxtrain/gauden.h
  /opt/local/include/sphinxtrain/heap.h
  /opt/local/include/sphinxtrain/itree.h
  /opt/local/include/sphinxtrain/kdtree.h
  /opt/local/include/sphinxtrain/kmeans.h
  /opt/local/include/sphinxtrain/lexicon.h
  /opt/local/include/sphinxtrain/metric.h
  /opt/local/include/sphinxtrain/misc.h
  /opt/local/include/sphinxtrain/mk_phone_list.h
  /opt/local/include/sphinxtrain/mk_phone_seq.h
  /opt/local/include/sphinxtrain/mk_sseq.h
  /opt/local/include/sphinxtrain/mk_trans_seq.h
  /opt/local/include/sphinxtrain/mk_ts2ci.h
  /opt/local/include/sphinxtrain/mllr.h
  /opt/local/include/sphinxtrain/mllr_class_io.h
  /opt/local/include/sphinxtrain/mllr_io.h
  /opt/local/include/sphinxtrain/model_def.h
  /opt/local/include/sphinxtrain/model_def_io.h
  /opt/local/include/sphinxtrain/model_inventory.h
  /opt/local/include/sphinxtrain/pset_io.h
  /opt/local/include/sphinxtrain/quest.h
  /opt/local/include/sphinxtrain/remap.h
  /opt/local/include/sphinxtrain/s3.h
  /opt/local/include/sphinxtrain/s3acc_io.h
  /opt/local/include/sphinxtrain/s3cb2mllr_io.h
  /opt/local/include/sphinxtrain/s3gau_io.h
  /opt/local/include/sphinxtrain/s3io.h
  /opt/local/include/sphinxtrain/s3lamb_io.h
  /opt/local/include/sphinxtrain/s3map_io.h
  /opt/local/include/sphinxtrain/s3mixw_io.h
  /opt/local/include/sphinxtrain/s3phseg_io.h
  /opt/local/include/sphinxtrain/s3tmat_io.h
  /opt/local/include/sphinxtrain/s3ts2cb_io.h
  /opt/local/include/sphinxtrain/segdmp.h
  /opt/local/include/sphinxtrain/state.h
  /opt/local/include/sphinxtrain/state_seq.h
  /opt/local/include/sphinxtrain/swap.h
  /opt/local/include/sphinxtrain/time.h
  /opt/local/include/sphinxtrain/topo_read.h
  /opt/local/include/sphinxtrain/ts2cb.h
  /opt/local/include/sphinxtrain/vector.h
  /opt/local/include/sphinxtrain/was_added.h
  /opt/local/lib/sphinxtrain/etc/feat.params
  /opt/local/lib/sphinxtrain/etc/sphinx_train.cfg
  /opt/local/lib/sphinxtrain/python/cmusphinx/__init__.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/arpalm.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/classlm2fst.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/cluster_mixw.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/corpus.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/dict_spd.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/divergence.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/evaluation.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/feat/_1s_c_d_dd.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/feat/__init__.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/feat/s2_4x.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/fstutils.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/gmm.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/hmm.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/htkmfc.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/hypseg.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/lat2dot.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/lat2fsg.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/lat_rescore.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/lat_rescore_fst.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/lattice.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/lattice_conv.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/lattice_error.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/lattice_error_fst.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/lattice_prune.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/lda.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/mfcc.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/mllr.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/mllt.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/prune_mixw.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/qmwx.pyx
  /opt/local/lib/sphinxtrain/python/cmusphinx/quantize_mixw.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/s2mfc.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/s3dict.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/s3file.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/s3gau.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/s3gaucnt.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/s3lda.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/s3mdef.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/s3mixw.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/s3model.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/s3senmgau.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/s3tmat.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/sendump.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/100.arpa.gz
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/bar.dict
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/filler.dict
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/foo.dict
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/sa1.ctl
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/sa1.dict
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/sa1.logspec
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/sa1.lsn
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/sa1.mfc
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/sa1.wav
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/test.ctl
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/tidigits/dictionary
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/tidigits/fillerdict
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/tidigits/man.ah.111a.mfc
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/tidigits/mdef
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/tidigits/means
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/tidigits/mixture_weights
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/tidigits/noisedict
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/tidigits/transition_matrices
  /opt/local/lib/sphinxtrain/python/cmusphinx/test/tidigits/variances
  /opt/local/lib/sphinxtrain/python/cmusphinx/test_arpalm.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/test_corpus.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/test_evaluation.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/test_hmm.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/test_s3dict.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/test_s3file.py
  /opt/local/lib/sphinxtrain/python/cmusphinx/test_s3model.py
  /opt/local/lib/sphinxtrain/python/setup.py
  /opt/local/lib/sphinxtrain/scripts/00.verify/verify_all.pl
  /opt/local/lib/sphinxtrain/scripts/000.comp_feat/make_feats.pl
  /opt/local/lib/sphinxtrain/scripts/000.comp_feat/slave_feat.pl
  /opt/local/lib/sphinxtrain/scripts/0000.g2p_train/calculateER.py
  /opt/local/lib/sphinxtrain/scripts/0000.g2p_train/evaluate.py
  /opt/local/lib/sphinxtrain/scripts/0000.g2p_train/g2p_train.pl
  /opt/local/lib/sphinxtrain/scripts/01.lda_train/baum_welch.pl
  /opt/local/lib/sphinxtrain/scripts/01.lda_train/lda_train.pl
  /opt/local/lib/sphinxtrain/scripts/01.lda_train/norm.pl
  /opt/local/lib/sphinxtrain/scripts/01.lda_train/norm_and_launchbw.pl
  /opt/local/lib/sphinxtrain/scripts/01.lda_train/slave_lda.pl
  /opt/local/lib/sphinxtrain/scripts/02.mllt_train/baum_welch.pl
  /opt/local/lib/sphinxtrain/scripts/02.mllt_train/mllt_train.pl
  /opt/local/lib/sphinxtrain/scripts/02.mllt_train/norm.pl
  /opt/local/lib/sphinxtrain/scripts/02.mllt_train/norm_and_launchbw.pl
  /opt/local/lib/sphinxtrain/scripts/02.mllt_train/slave_mllt.pl
  /opt/local/lib/sphinxtrain/scripts/05.vector_quantize/agg_seg.pl
  /opt/local/lib/sphinxtrain/scripts/05.vector_quantize/kmeans.pl
  /opt/local/lib/sphinxtrain/scripts/05.vector_quantize/slave.VQ.pl
  /opt/local/lib/sphinxtrain/scripts/10.falign_ci_hmm/baum_welch.pl
  /opt/local/lib/sphinxtrain/scripts/10.falign_ci_hmm/norm.pl
  /opt/local/lib/sphinxtrain/scripts/10.falign_ci_hmm/norm_and_launchbw.pl
  /opt/local/lib/sphinxtrain/scripts/10.falign_ci_hmm/slave_convg.pl
  /opt/local/lib/sphinxtrain/scripts/10.falign_ci_hmm/split_gaussians.pl
  /opt/local/lib/sphinxtrain/scripts/11.force_align/force_align.pl
  /opt/local/lib/sphinxtrain/scripts/11.force_align/make_spd.pl
  /opt/local/lib/sphinxtrain/scripts/11.force_align/slave_align.pl
  /opt/local/lib/sphinxtrain/scripts/12.vtln_align/slave_align.pl
  /opt/local/lib/sphinxtrain/scripts/12.vtln_align/vtln_align.pl
  /opt/local/lib/sphinxtrain/scripts/20.ci_hmm/baum_welch.pl
  /opt/local/lib/sphinxtrain/scripts/20.ci_hmm/norm.pl
  /opt/local/lib/sphinxtrain/scripts/20.ci_hmm/norm_and_launchbw.pl
  /opt/local/lib/sphinxtrain/scripts/20.ci_hmm/slave_convg.pl
  /opt/local/lib/sphinxtrain/scripts/20.ci_hmm/split_gaussians.pl
  /opt/local/lib/sphinxtrain/scripts/30.cd_hmm_untied/baum_welch.pl
  /opt/local/lib/sphinxtrain/scripts/30.cd_hmm_untied/norm.pl
  /opt/local/lib/sphinxtrain/scripts/30.cd_hmm_untied/norm_and_launchbw.pl
  /opt/local/lib/sphinxtrain/scripts/30.cd_hmm_untied/slave_convg.pl
  /opt/local/lib/sphinxtrain/scripts/40.buildtrees/buildtree.pl
  /opt/local/lib/sphinxtrain/scripts/40.buildtrees/make_questions.pl
  /opt/local/lib/sphinxtrain/scripts/40.buildtrees/slave.treebuilder.pl
  /opt/local/lib/sphinxtrain/scripts/45.prunetree/prunetree.pl
  /opt/local/lib/sphinxtrain/scripts/45.prunetree/slave.state-tying.pl
  /opt/local/lib/sphinxtrain/scripts/45.prunetree/tiestate.pl
  /opt/local/lib/sphinxtrain/scripts/50.cd_hmm_tied/baum_welch.pl
  /opt/local/lib/sphinxtrain/scripts/50.cd_hmm_tied/norm.pl
  /opt/local/lib/sphinxtrain/scripts/50.cd_hmm_tied/norm_and_launchbw.pl
  /opt/local/lib/sphinxtrain/scripts/50.cd_hmm_tied/slave_convg.pl
  /opt/local/lib/sphinxtrain/scripts/50.cd_hmm_tied/split_gaussians.pl
  /opt/local/lib/sphinxtrain/scripts/60.lattice_generation/force_align.pl
  /opt/local/lib/sphinxtrain/scripts/60.lattice_generation/s3decode.pl
  /opt/local/lib/sphinxtrain/scripts/60.lattice_generation/slave_genlat.pl
  /opt/local/lib/sphinxtrain/scripts/61.lattice_pruning/lattice_prune.pl
  /opt/local/lib/sphinxtrain/scripts/61.lattice_pruning/slave_prune.pl
  /opt/local/lib/sphinxtrain/scripts/62.lattice_conversion/lattice_conv.pl
  /opt/local/lib/sphinxtrain/scripts/62.lattice_conversion/slave_conv.pl
  /opt/local/lib/sphinxtrain/scripts/65.mmie_train/baum_welch.pl
  /opt/local/lib/sphinxtrain/scripts/65.mmie_train/norm.pl
  /opt/local/lib/sphinxtrain/scripts/65.mmie_train/norm_and_launchbw.pl
  /opt/local/lib/sphinxtrain/scripts/65.mmie_train/slave_convg.pl
  /opt/local/lib/sphinxtrain/scripts/80.mllr_adapt/baum_welch.pl
  /opt/local/lib/sphinxtrain/scripts/80.mllr_adapt/mllr_solve.pl
  /opt/local/lib/sphinxtrain/scripts/80.mllr_adapt/slave_adapt.pl
  /opt/local/lib/sphinxtrain/scripts/90.deleted_interpolation/deleted_interpolation.pl
  /opt/local/lib/sphinxtrain/scripts/decode/psdecode.pl
  /opt/local/lib/sphinxtrain/scripts/decode/slave.pl
  /opt/local/lib/sphinxtrain/scripts/decode/verify_dec.pl
  /opt/local/lib/sphinxtrain/scripts/decode/word_align.pl
  /opt/local/lib/sphinxtrain/scripts/lib/Queue.pm
  /opt/local/lib/sphinxtrain/scripts/lib/Queue/Job.pm
  /opt/local/lib/sphinxtrain/scripts/lib/Queue/PBS.pm
  /opt/local/lib/sphinxtrain/scripts/lib/Queue/POSIX.pm
  /opt/local/lib/sphinxtrain/scripts/lib/SimpleConfig.pm
  /opt/local/lib/sphinxtrain/scripts/lib/SphinxTrain/Config.pm
  /opt/local/lib/sphinxtrain/scripts/lib/SphinxTrain/Util.pm
  /opt/local/lib/sphinxtrain/scripts/lib/test_SimpleConfig.pl
  /opt/local/lib/sphinxtrain/scripts/lib/test_SimpleConfig.txt
  /opt/local/lib/sphinxtrain/scripts/prepare/make_phoneset.pl
  /opt/local/lib/sphinxtrain/scripts/prepare/maketopology.pl
  /opt/local/libexec/sphinxtrain/agg_seg
  /opt/local/libexec/sphinxtrain/bldtree
  /opt/local/libexec/sphinxtrain/bw
  /opt/local/libexec/sphinxtrain/cdcn_norm
  /opt/local/libexec/sphinxtrain/cdcn_train
  /opt/local/libexec/sphinxtrain/cp_parm
  /opt/local/libexec/sphinxtrain/delint
  /opt/local/libexec/sphinxtrain/inc_comp
  /opt/local/libexec/sphinxtrain/init_gau
  /opt/local/libexec/sphinxtrain/init_mixw
  /opt/local/libexec/sphinxtrain/kdtree
  /opt/local/libexec/sphinxtrain/kmeans_init
  /opt/local/libexec/sphinxtrain/make_quests
  /opt/local/libexec/sphinxtrain/map_adapt
  /opt/local/libexec/sphinxtrain/mixw_interp
  /opt/local/libexec/sphinxtrain/mk_flat
  /opt/local/libexec/sphinxtrain/mk_mdef_gen
  /opt/local/libexec/sphinxtrain/mk_mllr_class
  /opt/local/libexec/sphinxtrain/mk_s2sendump
  /opt/local/libexec/sphinxtrain/mk_ts2cb
  /opt/local/libexec/sphinxtrain/mllr_solve
  /opt/local/libexec/sphinxtrain/mllr_transform
  /opt/local/libexec/sphinxtrain/norm
  /opt/local/libexec/sphinxtrain/param_cnt
  /opt/local/libexec/sphinxtrain/printp
  /opt/local/libexec/sphinxtrain/prunetree
  /opt/local/libexec/sphinxtrain/tiestate
```

**Comment by l2dy** [comment]
I'm not a native speaker so if the commit message sounds weird please correct me.

**Comment by l2dy** [comment]
@mojca Please review.

**Comment by l2dy** [comment]
Going to merge this if no further comment received.

**Pull request merged**
