### PR TITLE
crossbinutils-1.0.tcl: bugfix 65348

### PR DESCRIPTION
**Pull request by Gcenx**
Closes https://trac.macports.org/ticket/65348

Now also installs target version of `ctf-spec.info`

###### Type(s)

- [x] bugfix
- [x] enhancement

###### Tested on

macOS 11.6.5 20G527 arm64
Xcode 13.2.1 13C100

Tested the following crossbinutils ports
- `arm-none-eabi-binutils` v2.37
- `i686-w64-mingw32-binutils` v2.38

Also tested via actions see https://github.com/Gcenx/macports-ports/actions/runs/2506004208

###### Verification 

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by Gcenx** [comment]
@mojca & @ryandesign

**Comment by linuxgemini** [comment]
Ran `sudo port -vst install "*-binutils"` and it built every port in the glob without any issues. It took `1h 13m 39s` to execute :P. Also works on `msp430-binutils-devel`.

**Comment by Gcenx** [comment]
Still needs more work, `ctf-spec.info` isn't getting renamed correctly this will cause a conflict....

**Comment by Gcenx** [comment]
@mascguy maybe you could also merge this one?

I’d provided a url showing the modified portgroup building the mentioned broken port and one of my usual tests.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
