### PR TITLE
py38-scikit-learn deps: drop python 3.8 or use 3.9

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by i0ntempest** [comment]
This change is needed by https://github.com/macports/macports-ports/pull/25846

**Comment by Schamschula** [comment]
I fine with dropping py38 support for py-geoplot. Once this PR is committed I need to add the missing homepage.

**Comment by i0ntempest** [comment]
Know problems:
py-astroML_addons is no longer compatible with the new setuptools we have.

**Comment by reneeotten** [comment]
okay, none of the failures are because of this PR. Let's merge this and deal with these things later.

**Pull request merged**
