### PR TITLE
graphviz: Update to version 6.0.1

### PR DESCRIPTION
**Pull request by essandess**
### Tested on

macOS 12.5 21G72 x86_64
Xcode 13.4.1 13F100

### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Ryan and I haven't updated `graphviz` to 5.x yet, as there are some potential concerns regarding breaking changes. And we haven't had a chance to discuss.

https://github.com/macports/macports-ports/commit/3931ac66451ad0c7cf42c981e2a3df34f3dab776#commitcomment-78597803

But I suppose this will give us an opportunity.

Also, changes should be limited to the version/checksums, along with anything else needed by 5.x. The latter can be gleaned by diffing the two:

```
$ gdiff graphics/graphviz{,-devel}/Portfile
9c9
< name                            graphviz
---
> name                            graphviz-devel
11,14c11,14
< version                         2.50.0
< checksums                       rmd160  76cc0668568f6bca1ddaf13b44106718fba8b04e \
<                                 sha256  e17021a510bbd2770d4ca4b4eb841138122aaa5948f9e617e6bc12b4bac62e8d \
<                                 size    29761610
---
> version                         5.0.0
> checksums                       rmd160  c779e39f42584e9f946cbe1b9f675193a903b55c \
>                                 sha256  500231f19651455623b9cee0bff93b3dd884df31ec85f7d1436726121f6b7bd1 \
>                                 size    27590532
56a57,61
> PortGroup                       legacysupport 1.1
> 
> # strndup
> legacysupport.newest_darwin_requires_legacy 10
> 
```

**Comment by mascguy** [comment]
Converting to draft, to ensure folks don't merge prematurely.

**Comment by mascguy** [comment]
I reached out to @ryandesign via e-mail, to see what he wants to do.

**Comment by mascguy** [comment]
Some good news: The ABI doesn't appear to have changed between version 2.50.x and 5.0.x. So in theory, we shouldn't need to rev-bump dependents. (That's based on a quick local test, via `port rev-upgrade`.)

However, the various breaking changes - which mostly seem related to how the library uses `boolean` - might cause compilation failures when dependents are updated. (At least for those which haven't been following upstream's changes.)

Summary extracted from the [ChangeLog](https://gitlab.com/graphviz/graphviz/-/blob/5.0.0/CHANGELOG.md):

<details><summary>Graphviz Breaking Changes</summary>

## [5.0.0] – 2022-07-07

### Fixed

- **Breaking**: The 4.0.0 change replacing the `Agiodisc_t` struct member `putstr` by `printf` has been reverted

## [4.0.0] – 2022-05-29

### Changed

- **Breaking**: The `mark` field of the `Agnodeinfo_t` struct is now a `size_t` instead of a `char`.
- **Breaking**: The unused `shape_t` struct has been removed from the public header `types.h`
- **Breaking**: The `Agiodisc_t` struct member `putstr` that was previously an `fputs` analog is replaced by `printf` that is required to behave similar to `fprintf`.

## [3.0.0] – 2022-02-26

### Changed

- **Breaking**: Using Graphviz as a library on Windows now requires the `GVDLL` symbol to be set to ensure correct linking.
- **Breaking**: Graphviz headers no longer define the `boolean` type. A replacement is C99 `bool` in the C standard library’s stdbool.h.
- **Breaking**: The `insidefn` member of the `shape_functions` struct must now be a pointer to a function returning a C99 `bool` instead of a
  Graphviz-specific `boolean`.
- **Breaking**: The `swapEnds` and `splineMerge` members of the `splineInfo` struct must now be pointers to functions returning a C99 `bool`s instead of Graphviz-specific `boolean`s. Similarly the `ignoreSwap` and `isOrtho` members of this struct must now be C99 `bool`s instead of a Graphviz-specific `boolean`s.
- **Breaking**: The `defined`, `constrained`, `clip`, and `dyna` fields of the `port` struct are now C99 `bool`s instead of Graphviz-specific `boolean`s.
- **Breaking**: The `set` and `html` fields of the `textlabel_t` struct are now C99 `bool`s instead of Graphviz-specific `boolean`s.
- **Breaking**: The `usershape` field of the `shape_desc` struct is now a C99 `bool` instead of a Graphviz-specific `boolean`.
- **Breaking**: The `candidate` and `valid` fields of the `rank_t` struct are now C99 `bool`s instead of Graphviz-specific `boolean`s.
- **Breaking**: The `filled`, `landscape`, and `centered` fields of the `layout_t` struct are now C99 `bool`s instead of Graphviz-specific `boolean`s.
- **Breaking**: The `has_images`, `has_flat_edges`, `has_sourcerank`, `has_sinkrank`, `expanded`, and `exact_ranksep` fields of the `Agraphinfo_t` struct are now C99 `bool`s instead of Graphviz-specific `boolean`s.
- **Breaking**: The `clustnode` and `has_port` fields of the `Agnodeinfo_t` struct are now C99 `bool`s instead of Graphviz-specific `boolean`s.
- **Breaking**: The `conc_opp_flag` field of the `Agedgeinfo_t` struct is now a C99 `bool` instead of a Graphviz-specific `boolean`.
- **Breaking**: The `must_inline` and `nocache` fields of the `usershape_t` struct are now C99 `bool`s instead of Graphviz-specific `boolean`s.
- **Breaking**: The `device_sets_dpi`, `external_context`, `fit_mode`, `needs_refresh`, `click`, `has_grown`, and `has_been_rendered` fields of the `GVJ_t` struct are now C99 `bool`s instead of Graphviz-specific `boolean`s.
- **Breaking**: The `loadimage` member of the `gvloadimage_engine_t` struct must now accept a C99 `bool` parameter instead of a former Graphviz-specific `boolean` parameter.
- **Breaking**: The `textlayout` member of the `gvtextlayout_engine_t` struct must now return a C99 `bool` instead of a Graphviz-specific `boolean`.
- **Breaking**: The `config` and `auto_outfile_names` members of the `GVC_common_s` struct are now C99 `bool`s instead of Graphviz-specific
  `boolean`s.
- **Breaking**: The `fixed` member of the `pack_info` struct is now an array of C99 `bool`s instead of an array of Graphviz-specific `boolean`s. Similarly, `pack_graph` now takes a `bool` array instead of a `boolean` array.
- **Breaking**: `pccomps` now takes a C99 `bool` instead of a `boolean` output parameter.
- **Breaking**: `gvusershape_file_access` now returns a C99 `bool` instead of a Graphviz-specific `boolean`.
- **Breaking**: 1-bit fields of the `obj_state_s` struct are now unsigned instead of signed.
- **Breaking**: Graphviz headers no longer define the constant `MAXSHORT`. A drop-in replacement is `SHRT_MAX` in the C standard library’s limits.h.
- **Breaking**: Graphviz headers no lnger define `NIL` macros. A drop-in replacement is `NULL` in the C standard library’s stddef.h.
- **Breaking**: Graphviz headers no longer define the `NOT` macro. A drop-in replacement is the C/C++ operator `!`.
- **Breaking**: Graphviz headers no longer (re-)define the C constants `INT_MIN` and `INT_MAX`. Replacements can be found in the C standard library’s limits.h.
- **Breaking**: Graphviz headers no longer define the constant `_DUMMY_ELEM`.
- **Breaking**: The `-m` memory test option to Graphviz command-line programs has been deprecated. Tools such as
  [Leak Sanitizer](https://clang.llvm.org/docs/LeakSanitizer.html) are a more effective modern way of diagnosing memory safety issues.
- **Breaking**: Graphviz headers no longer define the constant `MAXFLOAT`. A replacement is `FLT_MAX` in the C standard library’s float.h.

</details>

**Comment by mascguy** [comment]
Rebased against master, and updated to 5.0.1 per Ryan's latest commit for `graphviz-devel`: https://github.com/macports/macports-ports/commit/9fdf874133c251340cc3fbee88569c3b8b362fea

**Comment by mascguy** [comment]
@ryandesign I've been using `graphviz-devel` everywhere for the past few months - along with a number of dependents - without any issues. And while I certainly haven't tested everything against it, that's still encouraging.

For this update, we can try to rev-bump all dependents here, and validate via CI. Though I'm guessing we'll have to exclude a few - like `root5` and `root6` - to avoid timeout.

Regardless, it would be good to move forward, and finally update this port. How would you like to proceed?

**Comment by mascguy** [comment]
Since there are several dependents that take an eternity to build, it's not practical to test rev-bumping all dependents via CI. So in the interest of moving forward, I'll rev-bump everything locally, and test with the latest release.

And I'll tackle fixing any issues - if necessary - as well.

Once that's been done, all of those changes will be added to the PR.

This may take a few days, depending on what I encounter. More updates to follow.

**Comment by mascguy** [comment]
> Since there are several dependents that take an eternity to build, it's not practical to test rev-bumping all dependents via CI. So in the interest of moving forward, I'll rev-bump everything locally, and test with the latest release.

To save time, I added rev-bumps for dependents that:
* Successfully build for Big Sur and Monterey;
* Build reasonably quickly.

And this covers the vast majority of dependents. Those that build successfully, but take a long time - such as `retdec` and `root6` - will be validated locally.

**Comment by ryandesign** [comment]
> @ryandesign I've been using `graphviz-devel` everywhere for the past few months - along with a number of dependents - without any issues. And while I certainly haven't tested everything against it, that's still encouraging.

I also generally keep graphviz-devel installed and haven't noticed any problems. But I get most ports as archives from the packages server so I haven't tested rebuilding most things from source (except those I maintain and have updated recently).

**Comment by mascguy** [comment]
Currently reviewing the CI failures.

But it looks like I included a rev-bump, for a port hasn't built in a long time: `gnome-vfsmm`. That one has been removed from the commits.

**Comment by mascguy** [comment]
I've validated `retdec` locally, and looks good. As for some of the other CI failures, they're due to `boost` being installed only for the Python 3.10 variant, causing other subports to fail. (Which shouldn't occur on the buildbots.)

Net-Net, the only thing I'm not able to validate locally, is `root6`: I'm seeing an odd CMake error early in the configure phase, unrelated to `graphviz`. And based on Trac tickets, that doesn't occur on the buildbots, or for others.

So we're good-to-go! Merging.

**Pull request merged**
