### PR TITLE
boost{-numpy}: Convert to a basic shim port

### PR DESCRIPTION
**Pull request by cjones051073**
Installs symbolic links to the include directory and
libraries installed by the default boost PG versioned boost port.

### CODE REVIEW

**Comment by mascguy** [comment]
This is a nice way to simplify the legacy port.

Should there be a statement to set the boost version to 1.71 though...?

**Comment by cjones051073** [comment]
> This is a nice way to simplify the legacy port.
> 
> Should there be a statement to set the boost version to 1.71 though...?

That could be done (although the epoch will then need to be bumped) but I intentionally did not do it as I figured it an opportunity to update to the latest version. The shim ports can then stay, not just for legacy, and just always point to whatever the boost PG declares as its default version. There are only a handful of ports now using these directly, see https://trac.macports.org/ticket/63136 so checking if they are OK with 1.76 or not is not hard. Not though a number there do not build for other reasons as well….

**Comment by mascguy** [comment]
Makes sense, using the latest [by default] is preferable anyway.

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
Looks great to me! @michaelld, your thoughts?

**Comment by cjones051073** [comment]
No problem. I know you are thinking about merging all the boost ports into a single port file. That can still be done, even with the simplifications here, but I'll leave that to you to consider.  Please merge yourself whenever you are happy.

**Comment by michaelld** [comment]
I have no objections to this PR; I rather like it! I'm glad folks are finally working on Boost & related ports!

**Comment by michaelld** [comment]
That said: This PR has been open for ~1 hour as of me writing this note. I was tagged to review it & I am listed as a co-maintainer of the port. My day job (US/Eastern BTW) isn't reliable in allowing me to jump on these PRs, and often I can't get to them for a day or 2. I know the Boost ports are "openmaintainer" along with co-maintaining with @macsguy , but if you tag me to review then unless there's a very good / urgent reason to do so please give me the typical timeout as you would any other port maintainers ... [72 hours according to the MP guide](https://guide.macports.org/chunked/project.update-policies.html). Thx!

**Comment by mascguy** [comment]
> That said: This PR has been open for ~1 hour as of me writing this note. I was tagged to review it & I am listed as a co-maintainer of the port. My day job (US/Eastern BTW) isn't reliable in allowing me to jump on these PRs, and often I can't get to them for a day or 2. I know the Boost ports are "openmaintainer" along with co-maintaining with @macsguy , but if you tag me to review then unless there's a very good / urgent reason to do so please give me the typical timeout as you would any other port maintainers ... [72 hours according to the MP guide](https://guide.macports.org/chunked/project.update-policies.html). Thx!

You're right, I let my enthusiasm cloud my judgment. Will certainly wait for you to respond in the future. My appologies Michael!

**Comment by michaelld** [comment]
Thanks @macsguy ! I'm psyched about the Boost work & I totally get your enthusiasm & I'd want to be moving quickly here too, not having to wait any more than necessary!

**Pull request merged**
