### PR TITLE
py-google-api: update to 2.41.0

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
The update of `py-uritemplate` in 95668cdbdb5652143a474f6384536064d46d0b9e to v4 broke `py-google-api`... sorry about that. This PR updates `py-google-api` to the latest upstream version and adds ports for new requirements. 

From a quick look of ports that depend on `py-google-api` it appears that all of them support the v2 branch, but a bit more testing from maintainers would be beneficial before merging this PR... 

```
py37-google-api: py37-beancount, py37-tensor2tensor, py37-tensorflow-metadata, py37-tfx-bsl
py38-google-api: py38-beancount, py38-tensor2tensor, py38-tensorflow-metadata, py38-tfx-bsl
py39-google-api: gcalcli, py39-beancount, py39-tensor2tensor, py39-tensorflow-metadata, py39-tfx-bsl
py310-google-api: certbot, certbot-apache, certbot-dns-cloudflare, certbot-dns-cloudxns, certbot-dns-digitalocean, certbot-dns-dnsimple, certbot-dns-dnsmadeeasy, certbot-dns-gehirn, certbot-dns-google, certbot-dns-linode, certbot-dns-luadns, certbot-dns-nsone, certbot-dns-ovh, certbot-dns-rfc2136, certbot-dns-route53, certbot-dns-sakuracloud, certbot-nginx, py-google-api, py310-beancount
```

tagging the maintainers  of these ports here for their input: @mrdomino and @Schamschula

###### Tested on
macOS 10.15.7 19H1715 x86_64
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Review by Schamschula — APPROVED** [review]
I locally built the py310 subports to test against my installed version of certbot. There were no errors loading certbot.

I'm good with this update.

**Comment by reneeotten** [comment]
thanks for testing this Marius!

**Comment by mrdomino** [comment]
beancount works. fava does not seem to work (GET / returns a 404), but i doubt this was the source of the regression.

**Comment by reneeotten** [comment]
> beancount works. fava does not seem to work (GET / returns a 404), but i doubt this was the source of the regression.

@mrdomino that is indeed not related to any of this... The port is outdated anyway so I opened a PR for the update with some other changes. `fava` does build for me, but I don't know how to use it so have no idea whether is works as intended. Please feel free to check and comment in that PR.

**Comment by mrdomino** [comment]
fava works today, mysteriously. I have no explanation.

**Pull request merged**
