### PR TITLE
abseil: Fix pkg-config by removing -Xarch_* cflags

### PR DESCRIPTION
**Pull request by judaew**
#### Description

See https://github.com/macports/macports-ports/commit/37d57c306d21bef2074356d24f89103e290ad1de and https://github.com/abseil/abseil-cpp/issues/1168

Commits:
- abseil: Fix pkg-config by removing -Xarch_* cflags
- grpc: apach-arrow: Revbump after fix in abseil

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.1 22C65 x86_64
Xcode 14.1 14B47b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by judaew** [comment]
@neverpanic Can you check Bear port with these changes?

**Comment by barracuda156** [comment]
@judaew I have an update for `grpc` by the way, however could not figure out how to run testsuite properly as a whole. Individual tests run fine, manually.

But I won’t return to it until the third week of Feb, it is on another machine, I am away for a while.

**Comment by judaew** [comment]
@mascguy @essandess You have previously contributed to apache-arrow. The thing is, I updated abseil to the latest version, but I didn't know that it would break apache-arrow. So I updated apache-arrow to the latest version which solves this problem. But py-pyarrow fails to build because the pre-build phase fails. I don't know enough about apache-arrow to fix this problem. I hope you can help me fix it.

**Comment by judaew** [comment]
Thank you @neverpanic!

**Comment by judaew** [comment]
I fixed a bug that caused `py-pyarrow` to fail build. However, CI failed because it could not build `py-tensorflow`. I did some tests, and I was able to use `py-tensorflow-macos` (which is [compiled by Apple](https://developer.apple.com/metal/tensorflow-plugin/)) instead of `py-tensorflow`. Thanks to this, `py-pyarrow` was [able to build successfully](https://github.com/macports/macports-ports/actions/runs/4117450923/attempts/2#summary-11179506409) for macOS 12.0+ and Python 3.8+. So other versions of macOS and Python will use `py-tensorflow` which don't work on macOS 11 (and also 12-13 for Python 3.7) and maybe somewhere else.

`py-tensorflow` is broken for macOS 11-13:
- https://trac.macports.org/ticket/62131
- https://trac.macports.org/ticket/66357

**Comment by judaew** [comment]
CI Build Results on macOS 11-12:
- ✅ abseil
- ✅ apache-arrow
- ⚠️ py37-pyarrow (failed to install dependencies)
- ✅ py38-pyarrow
- ✅ py39-pyarrow
- ✅ py310-pyarrow
- ✅ grpc
- ✅ py37-grpcio
- ✅ py37-grpcio-tools
- ✅ py38-grpcio
- ✅ py38-grpcio-tools
- ✅ py39-grpcio
- ✅ py39-grpcio-tools
- ✅ py310-grpcio
- ✅ py310-grpcio-tools

**Pull request merged**
