### PR TITLE
OpenCoarrays: update to 2.10.2

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@catap @szhorvat Any idea why this specifically fails on macOS 13? _We got a new linker failure!_
```
  [ 18%] Generating coarray_distributed_transpose
  cd /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/src/tests/integration/dist_transpose && /bin/bash /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/bin/caf -DPREFIX_NAME=_gfortran_caf_ -DGCC_GE_7 -DGCC_GE_8 -DHAVE_MPI -DMPI_WORKING_MODULE -o /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/bin/OpenCoarrays-2.10.2-tests/coarray_distributed_transpose /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/OpenCoarrays-2.10.2/src/tests/integration/dist_transpose/coarray_distributed_transpose.F90 /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/lib/libopencoarrays_test_utilities.a /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/lib/libopencoarrays_mod.a
  [ 19%] Generating hello_multiverse
  cd /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/src/tests/integration/coarrayHelloWorld && /bin/bash /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/bin/caf -DPREFIX_NAME=_gfortran_caf_ -DGCC_GE_7 -DGCC_GE_8 -DHAVE_MPI -DMPI_WORKING_MODULE -o /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/bin/OpenCoarrays-2.10.2-tests/hello_multiverse /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/OpenCoarrays-2.10.2/src/tests/integration/coarrayHelloWorld/hello_multiverse.F90 /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/lib/libopencoarrays_test_utilities.a /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/lib/libopencoarrays_mod.a
  ld: unknown options: -commons 
  collect2: error: ld returned 1 exit status
  Error: command:
     `/opt/local/bin/mpif90-mpich-gcc13 -I/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/include/OpenCoarrays-2.10.2_GNU-13.2.0 -fcoarray=lib -lpthread -DPREFIX_NAME=_gfortran_caf_ -DGCC_GE_7 -DGCC_GE_8 -DHAVE_MPI -DMPI_WORKING_MODULE -o /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/bin/OpenCoarrays-2.10.2-tests/hello_multiverse /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/OpenCoarrays-2.10.2/src/tests/integration/coarrayHelloWorld/hello_multiverse.F90 /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/lib/libopencoarrays_test_utilities.a /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/lib/libopencoarrays_mod.a /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/lib/libcaf_mpi.a`
  failed to compile.
  make[2]: *** [src/tests/integration/coarrayHelloWorld/hello_multiverse] Error 1
```

**Comment by catap** [comment]
> @catap @szhorvat Any idea why this specifically fails on macOS 13? _We got a new linker failure!_
> 
> ```
>   [ 18%] Generating coarray_distributed_transpose
>   cd /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/src/tests/integration/dist_transpose && /bin/bash /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/bin/caf -DPREFIX_NAME=_gfortran_caf_ -DGCC_GE_7 -DGCC_GE_8 -DHAVE_MPI -DMPI_WORKING_MODULE -o /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/bin/OpenCoarrays-2.10.2-tests/coarray_distributed_transpose /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/OpenCoarrays-2.10.2/src/tests/integration/dist_transpose/coarray_distributed_transpose.F90 /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/lib/libopencoarrays_test_utilities.a /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/lib/libopencoarrays_mod.a
>   [ 19%] Generating hello_multiverse
>   cd /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/src/tests/integration/coarrayHelloWorld && /bin/bash /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/bin/caf -DPREFIX_NAME=_gfortran_caf_ -DGCC_GE_7 -DGCC_GE_8 -DHAVE_MPI -DMPI_WORKING_MODULE -o /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/bin/OpenCoarrays-2.10.2-tests/hello_multiverse /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/OpenCoarrays-2.10.2/src/tests/integration/coarrayHelloWorld/hello_multiverse.F90 /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/lib/libopencoarrays_test_utilities.a /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/lib/libopencoarrays_mod.a
>   ld: unknown options: -commons 
>   collect2: error: ld returned 1 exit status
>   Error: command:
>      `/opt/local/bin/mpif90-mpich-gcc13 -I/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/include/OpenCoarrays-2.10.2_GNU-13.2.0 -fcoarray=lib -lpthread -DPREFIX_NAME=_gfortran_caf_ -DGCC_GE_7 -DGCC_GE_8 -DHAVE_MPI -DMPI_WORKING_MODULE -o /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/bin/OpenCoarrays-2.10.2-tests/hello_multiverse /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/OpenCoarrays-2.10.2/src/tests/integration/coarrayHelloWorld/hello_multiverse.F90 /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/lib/libopencoarrays_test_utilities.a /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/lib/libopencoarrays_mod.a /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_OpenCoarrays/OpenCoarrays/work/build/lib/libcaf_mpi.a`
>   failed to compile.
>   make[2]: *** [src/tests/integration/coarrayHelloWorld/hello_multiverse] Error 1
> ```
> 
> UPD. Okay, it fails due to [pmodels/mpich#6684](https://github.com/pmodels/mpich/issues/6684)

I guess the root cause of this issue that mpich were build on Xcode which supports that flag, and you’re trying to use it on upgraded Xcode

**Comment by barracuda156** [comment]
> I guess the root cause of this issue that mpich were build on Xcode which supports that flag, and you’re trying to use it on upgraded Xcode

So revbump `mpich`?

**Comment by catap** [comment]
> 
> So revbump `mpich`?
> 

It won't help because as far as I know MacPorts' build bot for macOS 13 hasn't got upgraded to the Xcode 15

**Comment by barracuda156** [comment]
@catap So we have no way to solve this? )

**Comment by catap** [comment]
On Sun, 28 Jan 2024 14:45:51 +0100,
Sergey Fedorov wrote:
> @catap So we have no way to solve this? ) 

Seems so

-- 
wbr, Kirill

**Comment by barracuda156** [comment]
@catap Is it possible to switch to using a linker which accepts that flag?

**Comment by barracuda156** [comment]
(Alternatively, we could leave macOS-13 pegged to an old version for the time-being, since everything else builds, perhaps.)

**Comment by catap** [comment]
> (Alternatively, we could leave macOS-13 pegged to an old version for the time-being, since everything else builds, perhaps.)

I assume that you're trying to pass CI.

If yes, it won't help. It will rebuild that port anyway, and Github CI has Xcode 15.

-- 
wbr, Kirill

**Comment by barracuda156** [comment]
> > (Alternatively, we could leave macOS-13 pegged to an old version for the time-being, since everything else builds, perhaps.)
> 
> I assume that you're trying to pass CI.
> 
> If yes, it won't help. It will rebuild that port anyway, and Github CI has Xcode 15.
> 
> -- 
> wbr, Kirill
> 

Okay, makes sense. Can we patch MPICH so that is does not add a breaking flag to begin with?

**Comment by catap** [comment]
On Sun, 28 Jan 2024 18:16:31 +0100,
Sergey Fedorov wrote:
> 
> Okay, makes sense. Can we patch MPICH so that is does not add a breaking flag to begin with?
> 

Well... You may exclude it form mpich port, but I have no idea how it's used and its building way quite complicated and it may broke something somewhere.

It shouldn't but who knows?

-- 
wbr, Kirill

**Comment by kencu** [comment]
this ticket and comment are relevant I believe:

https://trac.macports.org/ticket/68346#comment:14

**Comment by barracuda156** [comment]
@kencu Thank you for the reference. Indeed, it is that same issue.

**Comment by catap** [comment]
Another approach to avoid this issue is disable f77, see: https://github.com/pmodels/mpich/blob/main/configure.ac#L4148-L4172

-- 
wbr, Kirill

**Comment by kencu** [comment]
It is rather tempting to consider rebuilding mpich-default and manually stripping  ```-Wl,-commons,use_dylibs``` out of  ```/opt/local/bin/mpicc-mpich-mp``` in the post-destroot phase.

**Comment by catap** [comment]
On Sun, 28 Jan 2024 21:54:03 +0100,
Ken wrote:
> 
> It is rather tempting to consider rebuilding mpich-default and manually stripping  ```-Wl,-commons,use_dylibs``` out of  ```/opt/local/bin/mpicc-mpich-mp``` in the post-destroot phase.
> 

Which is impossible in the case of Github CI.

-- 
wbr, Kirill

**Comment by kencu** [comment]
> Which is impossible in the case of Github CI.
> […](#)
> -- wbr, Kirill

why is it impossible? It's an easy, 10 second fix.

But not my call. You'd have to get Erich and Chris to agree.

**Comment by catap** [comment]
> why is it impossible? It's an easy, 10 second fix.
> 
> But not my call. You'd have to get Erich and Chris to agree.

Github CI runs on new machine each time.

I see the only way to apply your hack inside startup scripts to apply it on each
CI cycle that seems quite wrong.

And I haven't see any not wrong way to do it, do you?

-- 
wbr, Kirill

**Comment by kencu** [comment]
What I mean is -- the mpich-default port needs this added (only for the newest machines if you feel you need to, but I prefer all builds to be the same, myself).

**Comment by catap** [comment]
Ken,

Issue with mpich is blocking this PR. Your suggesting to hack works, but it doesn't solve issue with the CI.

-- 
wbr, Kirill

**Comment by barracuda156** [comment]
@catap If we rebuild `mpich` with suggested fix applied after the build, flag gonna be removed, and AFAICT it should actually fix CI, as @kencu suggests. Do I miss something?

What is not clear is whether that is a right thing to merge.

If we just need to see that the build works and CI pass, but do not want to change anything to MPICH in Macports, then the only way will be first to use the hack for MPICH, see the result of CI (presumably it should build), then drop the hack, adding [skip ci] and merge that.

**Comment by catap** [comment]
@barracuda156 it defently help to fix building.

But this option was added for a good reason, see: https://github.com/pmodels/mpich/commit/1ac4e0bfde21877f219ab7571b5b81b583e7c688

And simple remove isn't right move.

**Comment by kencu** [comment]
I read that the reason it was added is no longer valid, and most upstreams find -commons does nothing any more...

but that is to be confirmed with each individual project I guess.

And frankly, if the project requires -commons, it will never work on new MacOS, so it would have to be blocked from installing there, fixed to work properly without -commons, or totally dumped from MacPorts... 

homebrew will probably lead the way on that, with their ruthless cutting of projects that are not actively maintained to work properly on current systems.

**Comment by catap** [comment]
On Tue, 30 Jan 2024 01:46:51 +0100,
Ken wrote:
> 
> And frankly, if the project requires -commons, it will never work on new MacOS, so it would have to be blocked from installing there, fixed to work properly without -commons, or totally dumped from MacPorts... 
> 

Which is requires only for F77 ;)

another way is drop off support of F77.

-- 
wbr, Kirill

**Comment by kencu** [comment]
> On Tue, 30 Jan 2024 01:46:51 +0100, Ken wrote: And frankly, if the project requires -commons, it will never work on new MacOS, so it would have to be blocked from installing there, fixed to work properly without -commons, or totally dumped from MacPorts...
> Which is requires only for F77 ;) another way is drop off support of F77.
> […](#)
> -- wbr, Kirill

Ah... OK, well if that is the case... makes sense.

**Comment by kencu** [comment]
time to upgrade xcode on the buildbots I think….

**Comment by barracuda156** [comment]
@catap @kencu So what should we do now, any conclusion? Or maybe @mascguy could help to run CI manually for 11 and 12, excluding 13, and then we can merge it?

**Comment by kencu** [comment]
well, Eric’s commit to disable “commons” should fix this for most systems.

to avoid heartburn, just disable it on all systems everywhere, I’d suggest… but we’ll see how that plays out

**Comment by barracuda156** [comment]
Let’s see if this builds now.

**Comment by barracuda156** [comment]
@kencu @catap Looks like all good now. Thanks everyone!

**Comment by jeffhammond** [comment]
> well, Eric’s commit to disable “commons” should fix this for most systems.
> 
> to avoid heartburn, just disable it on all systems everywhere, I’d suggest… but we’ll see how that plays out

This will break "19.5.1.5 Linkage association" in the Fortran standard, when shared libraries are used.  I have a test of this that only works when I link with `ld -commons use_dylibs`.

**Comment by kencu** [comment]
> > well, Eric’s commit to disable “commons” should fix this for most systems.
> > to avoid heartburn, just disable it on all systems everywhere, I’d suggest… but we’ll see how that plays out
> 
> This will break "19.5.1.5 Linkage association" in the Fortran standard, when shared libraries are used. I have a test of this that only works when I link with `ld -commons use_dylibs`.

It would appear that is incompatible withball newer MacOS systems then, as commons is no longer supported by Apple.

**Comment by woachk** [comment]
`-Wl,-ld_classic` to use the older linker, can also be invoked via `xcrun ld-classic`.

**Comment by woachk** [comment]
Scratch that, as of Xcode 15.3, that is no longer a thing. Instead of an error being shown, here's what happens:

`ld: warning: -commons use_dylibs is no longer supported, using error treatment instead`

both when using the classic and new linkers

**Comment by kencu** [comment]
I certainly don't know much about what commons did behind the scenes for Fortran global variables, but whatever it was, it will have to change to something else everywhere it seems.

**Pull request merged**
