### PR TITLE
nawk: Update to 20180827

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

nawk: Update to 20180827

Switched to github portgroup, which also fixes the livecheck.

Portfile used a mix of tabs and spaces; added modeline and reformatted to our standard 4-spaces-per-indent style.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.6 17G65
Xcode 9.4.1 9F2000 

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. We should get a github ID in for "toby" btw.

**Comment by ryandesign** [comment]
> We should get a github ID in for "toby" btw.

In a separate PR.

**Comment by pmetzger** [comment]
Merged. Thanks for the update, @ryandesign!

**Comment by ryandesign** [comment]
We should really have given Toby the customary 72 hours to see and review this pull request.

**Comment by pmetzger** [comment]
I had little confidence that he would know it happened, plus it's listed as openmaintainer, and, like it or not, your updates are almost always _perfect_, there's rarely any dissent against them, so you get treated differently.

**Comment by tobypeterson** [comment]
What’s wrong with my github ID?

**Comment by tobypeterson** [comment]
Oh you mean adding it to the port file? I’d rather not.

**Comment by ryandesign** [comment]
> I had little confidence that he would know it happened,

Why? I assigned the PR to him, and macportsbot also notified him.

> plus it's listed as openmaintainer,

Yes but in the past some maintainers have objected even to simple version updates being performed on their openmaintainer ports without their consent. Developers who are not the maintainer might not be aware all the implications that updating the version of one port might have on other ports for example. And this PR was more than just updating the version: I also reformatted the entire port's whitespace. While I stand by those changes, reformatting someone else's port is not something we should probably do without asking permission first; this PR was how I was asking Toby's permission, and by merging the PR before he had a chance to look at it, he didn't get the opportunity to give it.

> and, like it or not, your updates are almost always _perfect_, there's rarely any dissent against them, so you get treated differently.

If I want to commit an update, I'll do that. If I go to the effort of filing a PR, it's because I want to give the maintainer of the port the opportunity to be aware of the proposed change and to voice any objections before it gets committed. I appreciate that you reviewed my changes and found them suitable, but if a port has a maintainer, we should really give them the opportunity to fulfill that role.

**Comment by pmetzger** [comment]
> Yes but in the past some maintainers have objected even to simple version updates being performed on their openmaintainer ports without their consent

Then they should remove `openmaintainer` from their port. `openmaintainer` means that you can perform simple version updates without explicit approval. If they don't want that, they can just commit a change removing it.

We are in a situation where most, if not the overwhelming bulk, of our ports with maintainers are de facto abandoned. The fraction of the time when someone ever comments on a proposed update is very, very low. I don't know why this is, but it's indeed the case. Keeping MacPorts functioning requires that we operate even in the presence of this. `openmaintainer` means that we can keep the pull queue reasonably clear when we have relatively high assurance that an update is harmless and well tested. If it becomes meaningless, we'll have a lot of trouble functioning. If people don't want others touching their ports, they should remove `openmaintainer` and not insist that it means the same thing as closed maintainer.

**Pull request merged**
