### PR TITLE
bulk_extractor: fix "incomplete type 'EVP_MD_CTX'"

### PR DESCRIPTION
**Pull request by chort**
I found a workaround for this error in another Portfile: https://github.com/macports/macports-ports/commit/fb9b14b429de03e4f7e54acff7280b2292a2833d

Worked for me on 10.14.6

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G1012
Xcode 11.2.1 11B500

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
The commit message needs to have the Port name pre-pended to it.

**Comment by chort** [comment]
> The commit message needs to have the Port name pre-pended to it.

Hi, I'm not super-familiar with Git. Is it possible to edit the commit message in the pull request w/o creating a new pull request? The port name is `bulk_extractor`.

**Comment by cjones051073** [comment]
> > The commit message needs to have the Port name pre-pended to it.
> 
> Hi, I'm not super-familiar with Git. Is it possible to edit the commit message in the pull request w/o creating a new pull request? The port name is `bulk_extractor`.

yes, it is. There are a number of ways it could be done, this is just one of them

Starting from the branch here run

```
git commit --amend
```

that will open up the last commit message in your preferred editor. Make the required changes, save and exit.

Then check the commit message is correctly updated with

```
git log
```

if it is, you then finally need to force push the changes to github. Forcing is required as in the above you have rewritten the commit history in your feature branch. To do this just push as you did before, but add the `--force` option

```
git push --force .....
```

**Comment by mf2k** [comment]
@chort : ping? This PR now has conflicts.

**Pull request merged**
