### PR TITLE
py-antlr4-python3-runtime: Update to version 4.13.0; Add Python 311

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
@essandess Do you know why the CI failed?

**Comment by ryandesign** [comment]
It is easy to click on the details of the CI runs to examine the logs and find out why they failed, which is:

```
/opt/local/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10: can't open file '/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-antlr4-python3-runtime/py310-antlr4-python3-runtime/work/antlr4-python3-runtime-4.13.0/setup.py': [Errno 2] No such file or directory
```

**Comment by pmetzger** [comment]
@ryandesign It is indeed easy, but to be direct: Steve has a history of submitting pull requests that do not appear to build, full stop. I think if this happens once in a while it's not such a big deal, but when it happens regularly the burden falls back on the submitter to fix the situation.

**Comment by pmetzger** [comment]
Hi @essandess! It's been over a month and we haven't heard from you on this and the pull request doesn't pass the CI and you've neither explained nor fixed that. I'm going to close this for now. Feel free to request the pull again if it passes the CI or there's a good reason it doesn't.

**Pull request closed without merging**
