### PR TITLE
py-*: remove obsolete py26/py33 subports from various Python ports

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR contains a third round of housekeeping on various Python ports in the tree by removing obsolete py26/py33 subports.

In here is the second half of ports that (i) have a maintainer listed and (ii) have nothing depend on them. No other changes were made, so if a port doesn't build it should not be caused by this PR.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65
Xcode 9.4.1 9F2000

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
If requested commits can be squashed, right now there is one commit per port.
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
I don't know, but you should mention this on the -dev list. At times, the automation just fails and I've never heard a satisfactory answer on why. Given that many of the maintainers probably aren't project members, it will be enough to tag all of them in a comment so they know whether to approve or not. Any you wish for me to request explicit review from (because they're project members) I will add.

**Comment by mojca** [comment]
I believe there's a hardcoded limit of 100 (either files or maintainers, I forgot) in our script (written by @l2dy) that does maintainer assignments. This was added to prevent mentioning 20k maintainers when creating a PR with a mass-edit of all ports. I don't know if there's a way to easily make an exception to the rule.

**Comment by pmetzger** [comment]
86 files in this one.

**Comment by mojca** [comment]
But each one has 3-8 subports.

**Comment by l2dy** [comment]
@mojca I suspect the webhook delivery to the bot failed. We need an admin to check it.

**Comment by petrrr** [comment]
I am fine with removing py26 and p33 subports, indeed I removed most of them from the ones I maintain. For the remaining ones here some note:

* py-lxml had some dependents left I did not want to break
* py-nio/ngl I left for the moment as I was not able to correctly port them to py27 yet. I suspect these will fail.

**Comment by michaelld** [comment]
LGTM for py-zmq

**Comment by duncanmmacleod** [comment]
Ok for py-astropy

**Comment by reneeotten** [comment]
@pmetzger let's wait at least for the weekend for maintainers to respond. I found one minor typo that I introduced instead of fixing... so I'll correct that before this gets merged. I'll not have time to look at this again before Monday anyway, so no rush.

**Comment by pmetzger** [comment]
@reneeotten How about I merge this some time early Saturday morning US/Eastern time, is that good for you?

**Comment by reneeotten** [comment]
@pmetzger no that's not good for me as I commented. I just tagged the maintainers yesterday night so there would be anyway a three day period to give them a chance to look it over. I will be away for the weekend so the earliest time I can look a this again is Sunday night. So I would suggest to wait the three days, I will correct the one mistake on Sunday evening and if there are no other points brought up by maintainers it can be merged on Monday morning.

**Comment by danchr** [comment]
Looked good for `py-subvertpy`, but it needed subports for Python 3, so I applied the change myself.

**Comment by pmetzger** [comment]
@reneeotten Ah, so you meant _after_ the weekend. No problem. We'll merge on Monday.

**Comment by gorticus** [comment]
LGTM for `py-ntplib`

**Comment by pmetzger** [comment]
@reneeotten You might want to resolve the conflicts over the weekend so I can merge easily on Monday.

**Comment by danielluke** [comment]
fine for py-pgsql

**Comment by pmetzger** [comment]
Merged. Thank you for this work, @reneeotten!

**Pull request merged**
