### PR TITLE
various py-* ports: remove obsolete py26/py33 subports

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
First attempt to actively remove py26/py33 subports, for now just a few to start with and only ones that have nothing depend on them. Tested with ```port echo depends:py??-<portname>```, which will not flag ports that used them as dependencies in non-default variants (if I am correct), but probably there aren't many of those... Anyway, if this is deemed an useful activity I can slowly continue to go through the Python ports that still have obsolete  subports (i.e., <27 for Python 2 and <34 for Python 3) and do some housekeeping. After that other ports that use these python versions in variants or as ```python.default_version``` should probably be updated as well. 

Are there any ports that should be kept around explicitly for older Python versions? 

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.4 17E202
Xcode 9.4 9F1027a

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?

### CODE REVIEW

**Comment by pmetzger** [comment]
> Anyway, if this is deemed an useful activity I can slowly continue to go through the Python ports that still have obsolete subports

I would deem this useful activity.

**Comment by reneeotten** [comment]
thanks @mojca for the comments - all good points. It is indeed probably better (or at least easier) to first remove all variants using too old python versions and then remove the subports. In this case I did additionally check that none of these subports are used in any other Portfile, so that should not cause any trouble.

My idea was to start with the py-* ports and go through them alphabetically (this PR contains the ones with py-a* and py-b*) and remove old subports that have nothing depend on them. After a few iterations this should allow for removing the subports in all of the Ports or at least be left with only a subset that should either remain as is or all be removed at the same time. But I can certainly start with removing variants for old Python versions first.

I cannot really oversee the advantage/disadvantage of doing this is batch versus handling all removals in one big PR, so I'll wait for a suggestion/decision for an answer from someone more knowledgeable before continuing. I assume that there is no need in this specific case to build all other subports as nothing has changed for them, but perhaps there is no way to let the buildbot know about this?

**Comment by pmetzger** [comment]
I'd do this in alphabetical batches like the one you just did.

**Comment by pmetzger** [comment]
Merged! Thank you for starting this project, @reneeotten!

I would also suggest separating the `nomaintainer` ports, since we can approve those quickly, from the ones with maintainers.

**Comment by mojca** [comment]
It doesn't really matter in which order one is moving ports to obsolete. I would do it all at once just because that's way less work than checking for consistency of each individual port removal.

**Pull request merged**
