### PR TITLE
watchman, edencommon: Update to 2023.11.13.00

### PR DESCRIPTION
**Pull request by neverpanic**
#### Description
Fix packaging of pywatchman and specify the watchman version number (which cannot be determined from git in our setup).

Drop the first patch, which does no longer seem to be required.

Update edencommon to the same version, because the build will fail otherwise.

This fixes the watchman prebuilt package, which is broken since the last libsodium update in 86381201edd2b233a20f15a542eae461de5eabb6 and was not fixed in https://github.com/macports/macports-ports/pull/20537 either.

Closes: https://trac.macports.org/ticket/65475
Closes: https://trac.macports.org/ticket/68702

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 13.6.1 22G313 x86_64
Xcode 15.0.1 15A507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@neverpanic They do not care about `folly` (and other related ports) version?

If these two are updated, I can bring all the rest to the same version. (Not completely trivial due to patches in `folly`, but should be doable.)

**Comment by neverpanic** [comment]
> @neverpanic They do not care about `folly` (and other related ports) version?
> 
> If these two are updated, I can bring all the rest to the same version. (Not completely trivial due to patches in `folly`, but should be doable.)

This was a request on IRC saying that watchman aborts immediately after installation (from the binary), so that's what I fixed. It was necessary to update `edencommon`, so I did that. It seems it was not necessary to update `folly`. It might make sense to also update that, but `port echo depends:folly` would have required much more testing than I was comfortable with for a drive-by contribution.

**Comment by barracuda156** [comment]
`folly` is a painful thing to update, that is why it isn’t updated often :)

**Comment by neverpanic** [comment]
So what should we do with this PR then? It fixes `watchman`, which is currently broken. If it doesn't really need an updated `folly`, I'd prefer to merge it now. The `folly` update can then always be done later as required.

**Comment by barracuda156** [comment]
@neverpanic I do not use watchman and do not maintain it since it requires Rust. If you can confirm it works, IMO, merge the fix.
Nothing of the folly group depends back on watchman, so it won’t affect anything.

**Comment by neverpanic** [comment]
I have tested that it works, so I'm merging this change.

**Pull request merged**
