### PR TITLE
commons-lang: update to 2.6, fix livecheck and whitespace

### PR DESCRIPTION
**Pull request by chrstphrchvz**
###### ~~Tested on~~

~~macOS 10.x~~
~~Xcode 8.x~~

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
>Port commons-lang **fail** on xcode10.2.
>Port commons-lang **fail** on xcode9.4.

```
compile:
    …
    [javac] error: Source option 1.3 is no longer supported. Use 6 or later.
    [javac] error: Target option 1.3 is no longer supported. Use 1.6 or later.
```

This is another port that requires JDK 8 or earlier to build.

**Comment by mf2k** [comment]
Build error is:

```
compile:
    [mkdir] Created dir: /opt/local/var/macports/build/_Users_vsts_agent_2.155.1_work_1_s_java_commons-lang/commons-lang/work/commons-lang-2.6-src/target/classes
    [javac] /opt/local/var/macports/build/_Users_vsts_agent_2.155.1_work_1_s_java_commons-lang/commons-lang/work/commons-lang-2.6-src/build.xml:62: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 86 source files to /opt/local/var/macports/build/_Users_vsts_agent_2.155.1_work_1_s_java_commons-lang/commons-lang/work/commons-lang-2.6-src/target/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.3
    [javac] error: Source option 1.3 is no longer supported. Use 7 or later.
    [javac] error: Target option 1.3 is no longer supported. Use 7 or later.

```

**Comment by mf2k** [comment]
I'm not sure I see the point of upgrading this to 2.6 which don't seem to build. Why not update to the version in the new port submission commons-lang3? In other words, don't create a new port and just incorporate the changes into this one.

**Comment by chrstphrchvz** [comment]
> I'm not sure I see the point of upgrading this to 2.6 which does not seem to build. Why not update to the version in the new port submission commons-lang3? In other words, don't create a new port and just incorporate the changes into this one.

The short reason for not doing so is that commons-lang3 is not a drop-in replacement for commons-lang 2.x.

I have started looking into whether this port can be deleted: its only dependents are `cassandra`, `commons-cli`, and `xdoclet`.
- `cassandra` has been outdated for several years (https://trac.macports.org/ticket/45004); if it were updated, the new version probably would not depend on `commons-lang` 2.x. However I will likely first propose to delete it before attempting to update it.
- `commons-cli` only has `cassandra` as a dependent. This port is outdated, and probably does not actually depend on commons-lang. If `cassandra` is deleted then `commons-cli` could likely be deleted as well.
- `xdoclet` has no dependents, is very old (~2005), and whose upstream project is defunct. I will see if this project can be deleted.

All three of these ports in their current versions depend on other EOL ports like `servlet23-api` (see https://trac.macports.org/ticket/58389).

I will close this PR in the meantime, unless there is a better way to put it on hold.

**Pull request closed without merging**
