### PR TITLE
rav1e: set target when calling cargo-c

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
See https://trac.macports.org/ticket/66591#comment:19 No revbump since port either builds correctly or not at all

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by kencu** [comment]
Yup, that did it:
```
work % find . | grep librav1e.0.5.1.dylib | xargs file
./destroot/opt/local/lib/librav1e.0.5.1.dylib:           Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64]
./destroot/opt/local/lib/librav1e.0.5.1.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
./destroot/opt/local/lib/librav1e.0.5.1.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
./destroot-arm64/opt/local/lib/librav1e.0.5.1.dylib:     Mach-O 64-bit dynamically linked shared library arm64
./destroot-ppc-intel/opt/local/lib/librav1e.0.5.1.dylib: Mach-O 64-bit dynamically linked shared library x86_64
./destroot-intel/opt/local/lib/librav1e.0.5.1.dylib:     Mach-O 64-bit dynamically linked shared library x86_64
./destroot-x86_64/opt/local/lib/librav1e.0.5.1.dylib:    Mach-O 64-bit dynamically linked shared library x86_64
```

and 
```
% file /opt/local/lib/librav1e.0.5.1.dylib
/opt/local/lib/librav1e.0.5.1.dylib: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64]
/opt/local/lib/librav1e.0.5.1.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
/opt/local/lib/librav1e.0.5.1.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

**Review by kencu — APPROVED** [review]

**Comment by kencu** [comment]
btw -- the static library that is installed with this port is 200 MB in size ... whereas the dylib is a tiny 6MB:

Just FYI, in case the static lib is not needed:

```
% ls -la /opt/local/lib/librav1e.a
-rw-r--r--  1 root  wheel  254824872  2 Jan 15:27 /opt/local/lib/librav1e.a
% ls -la /opt/local/lib/librav1e.0.5.1.dylib
-rwxr-xr-x  1 root  wheel  6445455  2 Jan 15:27 /opt/local/lib/librav1e.0.5.1.dylib
```

**Comment by kencu** [comment]
Thanks, Marcus, for the time you spent fixing these. You really know much more about how rust / cargo / cargo-c etc works, esp on MacPorts, than anyone else does at present.

I appreciate the time you spent on this.

**Comment by MarcusCalhoun-Lopez** [comment]
> Thanks, Marcus, for the time you spent fixing these. You really know much more about how rust / cargo / cargo-c etc works, esp on MacPorts, than anyone else does at present.
> 
> I appreciate the time you spent on this.

You are welcome.

**Pull request merged**
