### PR TITLE
py-poppler-qt5: update to 21.3.0

### PR DESCRIPTION
**Pull request by dliessi**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G14042 x86_64
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
this fails on the CI so perhaps something else is needed for more current macOS versions?

**Comment by dliessi** [comment]
From the log of the macOS 12 machine:
```
  --->  Building py310-poppler-qt5
  DEBUG: Executing proc-pre-org.macports.build-build-0
  DEBUG: Executing org.macports.build (py310-poppler-qt5)
  DEBUG: Environment: 
  CC='/usr/bin/clang'
  CC_PRINT_OPTIONS='YES'
  CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-poppler-qt5/py310-poppler-qt5/work/.CC_PRINT_OPTIONS'
  CFLAGS='-arch x86_64 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk'
  CPATH='/opt/local/include'
  CXX='/usr/bin/clang++'
  CXXFLAGS='-arch x86_64 -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk'
  DEVELOPER_DIR='/Applications/Xcode_14.2.app/Contents/Developer'
  F90FLAGS='-m64'
  FCFLAGS='-m64'
  FFLAGS='-m64'
  LDFLAGS='-arch x86_64'
  LIBRARY_PATH='/opt/local/lib'
  MACOSX_DEPLOYMENT_TARGET='12.0'
  MACPORTS_LEGACY_SUPPORT_DISABLED='1'
  OBJC='/usr/bin/clang'
  OBJCFLAGS='-arch x86_64 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk'
  SDKROOT='/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk'
  Executing:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-poppler-qt5/py310-poppler-qt5/work/python-poppler-qt5-21.3.0" && sip-build-3.10 --qmake /opt/local/libexec/qt5/bin/qmake --verbose 
  DEBUG: system:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-poppler-qt5/py310-poppler-qt5/work/python-poppler-qt5-21.3.0" && sip-build-3.10 --qmake /opt/local/libexec/qt5/bin/qmake --verbose 
  Querying qmake about your Qt installation...
  /opt/local/libexec/qt5/bin/qmake -query
  These bindings will be built: Poppler-Qt5.
  Generating the Poppler-Qt5 bindings...
  Generating the .pro file for the popplerqt5 module...
  Generating the top-level .pro file...
  Generating the Makefiles...
  /opt/local/libexec/qt5/bin/qmake -recursive python-poppler-qt5.pro
  sip-build-3.10: '/opt/local/libexec/qt5/bin/qmake -recursive python-poppler-qt5.pro' failed returning 3
  Project ERROR: Could not resolve SDK Path for 'macosx12.3' using --show-sdk-path
  Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-poppler-qt5/py310-poppler-qt5/work/python-poppler-qt5-21.3.0" && sip-build-3.10 --qmake /opt/local/libexec/qt5/bin/qmake --verbose 
  Exit code: 1
  Error: Failed to build py310-poppler-qt5: command execution failed
  DEBUG: Error code: CHILDSTATUS 6349 1
  DEBUG: Backtrace: command execution failed
      while executing
  "system {*}$notty {*}$callback {*}$nice $fullcmdstring"
      invoked from within
  "command_exec -callback portprogress::target_progress_callback build"
      (procedure "portbuild::build_main" line 8)
      invoked from within
  "$procedure $targetname"
  Error: See /opt/local/var/macports/logs/_Users_runner_work_macports-ports_macports-ports_ports_python_py-poppler-qt5/py310-poppler-qt5/main.log for details.
  Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
  Error: Processing of port py310-poppler-qt5 failed
```

The error looks like https://trac.macports.org/ticket/65293 and similar tickets, but I thought that `use_xcode yes` would solve it, and that instruction is present both on macOS 11 and macOS 12 in this Portfile, as in py-pyqt5.
Unfortunately I do not have a recent Mac to test on.
@reneeotten How can we deal with this?

The current version of the Portfile seems to have worked correctly on recent macOS (see [port health](https://ports.macports.org/port/py310-poppler-qt5/details/)) and the changes between the versions are what was contained in the two patch files that I remove with this PR (see https://github.com/frescobaldi/python-poppler-qt5/commit/85adeddbc4658cd8b2daaaa067484ba9b46ad82c and https://github.com/frescobaldi/python-poppler-qt5/commit/85adeddbc4658cd8b2daaaa067484ba9b46ad82c): apart from the version number the updated Portfile in this PR is building the same source as the current Portfile.
Maybe something is wrong in the builders and not in the Portfile?
I will try opening a dummy PR with some trivial change to the Portfile to trigger the CI builders on the current version and see if they still fail.

**Comment by dliessi** [comment]
The dummy PR #17807, where I simply removed some Python versions, fails with the same error, although, as I already noted, it builds correctly on all versions of macOS from 10.9 to 13. Given that the only difference in the source code with this PR is the version number, @reneeotten could you please ignore the CI results and merge this PR?

Should we open an issue somewhere about this wrong behaviour of the CI builders?

**Comment by dliessi** [comment]
@reneeotten Can you please merge this PR? I believe my observations are enough to justify ignoring the failing CI build.

**Comment by reneeotten** [comment]
> @reneeotten Can you please merge this PR? I believe my observations are enough to justify ignoring the failing CI build.

sorry I forgot about this.... just took this PR and tried to build it locally and indeed it finishes just fine. So yes, I'll merge the PR - thanks!

**Pull request merged**
