### PR TITLE
lazarus: update to 3.4

### PR DESCRIPTION
**Pull request by i0ntempest**
Closes: https://trac.macports.org/ticket/70740

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
It will need follow-up fixes, but does not hurt doing the update first.

**Comment by i0ntempest** [comment]
Merging in 24h if no objections

**Comment by kamischi** [comment]
I agree to merging. I can't test at the moment, because of other trouble due to updating to Sequoia. I should have waited a couple of days.

**Comment by barracuda156** [comment]
> I agree to merging. I can't test at the moment, because of other trouble due to updating to Sequoia. I should have waited a couple of days.

@kamischi It’s perhaps better that this was updated first, and now hopefully I can get powerpc working (otherwise rebasing is a nightmare often).

**Pull request merged**
