### PR TITLE
watchman: revbump after folly update, use libfmt10

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

For some reason CI did not pass initially for this (no error locally though), so it was omitted from `folly` & friends update. Revbump is required, however.
Let us try to fix it now.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.2.1
Xcode 15.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`? (There are multiple lint warnings due to how crates are listed, but I do not touch that part here.)
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@danchr Looks like you were right re setuptools, thank you.

**Comment by pmetzger** [comment]
This is openmaintainer but I am assuming this is necessary to commit immediately to fix the broken build?

**Comment by barracuda156** [comment]
@danchr Could you please confirm if you are okay with this? This is not my port.

**Comment by pmetzger** [comment]
I'm going to merge for now on the basis that without this it is broken. Apologies to @danchr if I messed it up worse.

**Comment by barracuda156** [comment]
@pmetzger Thank you, and sorry again for the initial mess.

**Pull request merged**
