### PR TITLE
R: new packages

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

New ports.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@herbygillot This batch is mergeable!

**Comment by herbygillot** [comment]
My only comment is that `R-duckdb` seems to be building its entire own version of DuckDB... should we be trying to make it use the `duckdb` provided by MacPorts?

**Comment by barracuda156** [comment]
> My only comment is that `R-duckdb` seems to be building its entire own version of DuckDB... should we be trying to make it use the `duckdb` provided by MacPorts?

It did not build for me, I tried. (Likely fixable, but won’t make life easier. As a matter of fact, many R packages prefer bundled software, possibly due to .so format being used with R, or just for the sake of ease of maintenance.)

**Comment by herbygillot** [comment]
Np. Merged.

**Comment by barracuda156** [comment]
@herbygillot I did that hackery for `R-symengine`, as that was huge to build otherwise. Had to cut off chunks of configure and then force our ldflags to Makevars.

When I have time, I will try think through the build system to make it more human-friendly. R and Fortran (FPM) PGs could be improved.

**Pull request merged**
