### PR TITLE
wxWidgets updates

### PR DESCRIPTION
**Pull request by mojca**
#### Description

* Update wxWidgets 3.0 and 3.2 to version 3.0.4 and 3.1.1.
* Port `wxWidgets-3.0-libcxx` removed.
* Needs testing on 10.6 at least.
* We might want to merge it before #1415 (@RJVB).

I guess that dependent ports might need a revbump as well, but I'm not sure.

Trac tickets that were **not yet** taken into account:
* https://trac.macports.org/ticket/55123 (`wxWidgets-3.0 should export @interface ModalDialogDelegate`)
* https://trac.macports.org/ticket/53040 (`py27-wxpython-3.0 @3.0.2.0 fatal error: 'type_traits' file not found on systems upgraded to libc++`)

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.3 17D102
Xcode 9.2 9C40b 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by RJVB** [comment]
>I guess that dependent ports might need a revbump as well, but I'm not sure.

I'll test on 10.9 but as far as I've seen on Linux the 3.0.3 -> 3.0.4 update is just a bugfix release that doesn't impose rebuilding because of ABI changes. Existing installs of at least Audacity and CodeBlocks continued to work just fine after the update.

>Trac tickets that were **not yet** taken into account:
>* https://trac.macports.org/ticket/55123 (wxWidgets-3.0 should export @interface ModalDialogDelegate)

As far as I'm concerned that ticket can be closed (I can't do that myself). The issue has been fixed in port:audacity which would be the sole beneficiary of the proposed change in 55123.

>  * wxWidgets-3.2: update to 3.1.1, fix livecheck

Shouldn't that be wxWidgets-3.1 ?!

**Comment by RJVB** [comment]
> I'll test on 10.9 but as far as I've seen on Linux the 3.0.3 -> 3.0.4 update is just a bugfix release that doesn't impose rebuilding because of ABI changes. Existing installs of at least Audacity and CodeBlocks continued to work just fine after the update.

Confirmed on 10.9 . I think you can safely forget about revbumping the dependents on wxWidgets-3.0 ; IMHO any exception can and should be handled individually.

**Comment by mojca** [comment]
I closed the ticket.

>> * wxWidgets-3.2: update to 3.1.1, fix livecheck
>
> Shouldn't that be wxWidgets-3.1 ?!

I deliberately call version 3.1.x `wxWidgets-3.2` because 3.1 is just a development version that will lead to 3.2 one day. Ports that use it should only need a revbump when that happens as opposed to having to change a large number of ports (lesson learned from transition to 3.0).

**Comment by RJVB** [comment]
>I deliberately call version 3.1.x `wxWidgets-3.2` because 3.1 is just a development version that will lead to 3.2 one day. Ports that use it should only need a revbump when that happens as opposed to having to change a large number of ports (lesson learned from transition to 3.0).

Can't you also say that 3.0 is just a transitional version that will lead to 4.0 one day? ;)

Major version transitions are always annoying to handle in packaging. Minor version should be a lot easier if the project is written properly. Couldn't you just have a port:wxWidgets-3 that always delivers the latest 3.x.y version and only split off wxWidgets-3.x ports when necessary?

**Comment by RJVB** [comment]
FWIW, ports depending on wxWidgets-3.2 may need a revbump.

**Comment by mojca** [comment]
Thanks. I only found one: #1447

**Pull request merged**
