### PR TITLE
wine*: add 64-bit support

### PR DESCRIPTION
**Pull request by casr**
###### Description

I thought it would be easier to manage a patch in Git for enabling Wine 64. This just adds support for the Wine’s `Portfile` at the moment but before this changeset is committed it should add support for `wine-devel` and `wine-crossover`, if appropriate.

Note, that it does not automatically install Gecko or Mono for Wine 64.

Also be aware of this remark from Wine HQ:
> Current Wine includes support for 64 bit Wine on Mac OS X; however, this has not been tested very much, and some applications may never work due to an ABI incompatibility between Win64 and OS X.

Please see https://trac.macports.org/ticket/53651 for further information.

###### Tested on
macOS 10.12.4
Xcode 8.2.1

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by casr** [comment]
Also relevant is #374

**Comment by mf2k** [comment]
How about we instead create a new (sub-)port called wine64 so if the 64-bit version doesn't work well for some applications, they can continue to use the 32-bit version? I would otherwise like to see this version get committed.

**Comment by casr** [comment]
The 64-bit build tools require a regular 32-bit Wine binary so that it can do its "Windows on Windows" thing. For that reason I do not think the stability of using 32-bit Windows should be affected.

But there is a caveat in that I believe `WINE_ARCH` defaults to 64-bit when it is available which we might want to coerce to 32-bit on MacOS.

**Comment by mojca** [comment]
@casr: You other PR was merged, but it's not clear to me what exactly to do with this one as you explained that it is not yet fully finished.

What exactly is still left to be done and is straightforward to do (like applying the same changes to the other two ports), what is still needed and cannot be done so easy? What are potential problems of switching from 32-bit to 64-bit?

I would like to push this forward before it gets stale forever.

**Comment by casr** [comment]
So left to do:

  - Get it to automatically install Gecko and Mono for Wine 64
  - Apply it to the other ports, `wine-devel` and `wine-crossover`, if appropriate.
  - Consider the wider implications of defaulting to Wine 64 or not. As I said above, I do not think Wine 32 should be greatly affected by a change like this (but I could be wrong :) )

I currently haven't got the time to run the compiles and check everything works at the moment so happy if somebody wants to pick this up for now.

**Comment by mojca** [comment]
Just pinging you in case you have more time to continue working on this now.

**Comment by pete27** [comment]
@casr: Like mojca I'd like to ping you. It would be great if you could leave a hint how to setup things to get Gecko and Mono automatically installed for Win 64.
Thanks!

**Comment by ryandesign** [comment]
I'm not looking into this and don't have any advice about it. Someone else should take the lead on this.

**Comment by jeremyhu** [comment]
This is not going to work well on macOS without rewriting the macOS pthreads library because there is conflict between the macOS and Windows ABI for thread local data (specifically, we'd need to switch from %gs to %fs).  You're really better off using a VM if you want Win64.

**Comment by pete27** [comment]
@jeremyhu: Win64 works pretty fine except for Mono and Gecko. Is your comment related to Wine64 at all or only to these two packages?

**Comment by mf2k** [comment]
Going back to my original suggestion, please let's simply make a wine64 port.

**Comment by casr** [comment]
> This is not going to work well on macOS without rewriting the macOS pthreads library because there is conflict between the macOS and Windows ABI for thread local data

@jeremyhu I was not aware of that. Would you be able to provide or link to more information on it? If it is really bad then this PR should be closed. Originally my hope was to put it out there thinking that wider availability would be great for ironing out bugs but that issue sounds deep rooted.

Finally, related to Ryan's point, I won't be the one taking this to the finish line any time soon as I have no interest in any Win64 programmes at the moment and therefore nothing to test against.

**Comment by ryandesign** [comment]
https://trac.macports.org/ticket/53651#comment:2

**Comment by pmetzger** [comment]
Okay, so this has been sitting for a while. What should we do to progress it or close it?

**Comment by mf2k** [comment]
Given that future versions of macOS may not support 32-bit executables, I think we need to create a wine64 port. We don't want to change the existing 32-bit wine port because of the known issues with the 64-bit version.

**Comment by ryandesign** [comment]
> Given that future versions of macOS may not support 32-bit executables, I think we need to create a wine64 port.

But earlier in this PR:

> The 64-bit build tools require a regular 32-bit Wine binary so that it can do its "Windows on Windows" thing.

**Comment by raimue** [comment]
Upstream claims to support 64-bit on macOS as of [wine 2.0](https://www.winehq.org/announce/2.0): "- 64-bit applications are supported on macOS." Why are we questioning this? We need to ask upstream for clarification if there is any doubt instead of making assumptions.

We cannot create a standalone wine64 port, as a pure 64-bit version of wine is not able to execute 32-bit binaries. Such a setup will not be that useful for most users. Therefore you need to build both the 32-bit and 64-bit versions and then merge them. This is exactly what the Portfile submitted in this pull request does, by cleverly using the muniversal port group for this. It looks reasonable to me to just merge it.

Do you expect adding 64-bit support to have any negative effects on users that only need 32-bit? I am with @casr on this one and I don't think it will change anything for users of 32-bit wine, so I am in favor of merging this.

**Comment by raimue** [comment]
I added what appears to be the missing bits. This will install wine_gecko for x86_64 and I merged the changes to wine-devel and wine-crossover.

**Comment by pmetzger** [comment]
> Upstream claims to support 64-bit on macOS as of wine 2.0: "- 64-bit applications are supported on macOS." Why are we questioning this?

I'm questioning it only because people in this thread questioned it. However, the Wine FAQ says:

https://wiki.winehq.org/FAQ#Is_there_a_64_bit_Wine.3F

**Comment by pmetzger** [comment]
Anyway, @raimue, I'm happy to see this merged, as that will close it. If the consensus is to merge, that's fine by me. I'd just prefer we not leave it hanging around not progressing forever.

**Comment by mf2k** [comment]
I agree with merging this PR then!

**Comment by pmetzger** [comment]
Okay, so who (at this point) is opposed? If it's no one, perhaps @raimue would care to do the honors and merge it?

**Comment by pete27** [comment]
Hi,
@casr wrote in his initial post: "Note, that it does not automatically install Gecko or Mono for Wine 64."
This is still the case, right?

**Comment by raimue** [comment]
@pete27 That should be covered by the commits I added. The ports will also download and install the `.msi` for 64-bit wine_gecko. There is no separate download for wine-mono.

**Comment by pmetzger** [comment]
@raimue So is it time to merge?

**Comment by raimue** [comment]
I ran into a problem with wine-devel, because the patch to configure did no longer apply. My test build for wine-devel is still running, but later today I will merge the changes to master.

**Comment by pmetzger** [comment]
Thank you, @raimue! It is appreciated!

**Comment by casr** [comment]
@raimue congrats on getting this over the finish line and thank you for finishing up the last bits 🎉

**Comment by raimue** [comment]
@casr Actually thanks to you for starting this and figuring out the hard part on how to do the build with muniversal. I promise your next contribution will not have to wait almost a year to be picked up. 😉

**Pull request closed without merging**
