### PR TITLE
diff-pdf: update to use wxWidgets-3.2

### PR DESCRIPTION
**Pull request by pietvo**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.6.6 22G630 x86_64
Xcode 15.2 15C500b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@pietvo This should be done conditionally, since `wxWidgets-3.2` is not supported on a number of macOS versions.

**Comment by barracuda156** [comment]
Let me actually see which version works on older systems, gimme a few min.

**Comment by barracuda156** [comment]
Ok, if you could add the following, it gonna fix it for older systems:
```
PortGroup           legacysupport 1.1

if {${os.platform} eq "darwin" && ${os.major} > 10} {
    wxWidgets.use   wxWidgets-3.2
} else {
    wxWidgets.use   wxGTK-3.0
}

# This is only needed for wrappers.
legacysupport.newest_darwin_requires_legacy 0
# diff-pdf(22577) malloc: *** error for object 0x1009034: Non-aligned pointer being freed
legacysupport.redirect_bins diff-pdf
```
P. S. I am not sure whether non-GTK wxWidgets work on non-Apple systems, so that can be adjusted, just make sure that macOS < 10.7 use `wxGTK-3.0` and no `wxWidgets-3.x`.

**Comment by pietvo** [comment]
The `diff-pdf` README.md says

> diff-pdf requires the following libraries:

- wxWidgets >= 3.0
- Cairo >= 1.4
- Poppler >= 0.10

I have no idea if that includes wxGTK-3.0, or that it can't run on older systems. I have no way to check that.

**Comment by barracuda156** [comment]
`wxGTK-3.0` is just `wxWidgets >= 3.0` using GTK3 backend.

I can and I have verified that it works :) 

By the way, `wxWidgets >= 3.2` seems to be broken on every macOS from El Capitan down: https://ports.macports.org/port/wxWidgets-3.2/details/

**Comment by pietvo** [comment]
I have updated the PR (squashed).

**Comment by barracuda156** [comment]
@pietvo Thank you very much!

**Comment by pietvo** [comment]
> if {${os.platform} eq "darwin" && ${os.major} > 10} {
>     wxWidgets.use   wxWidgets-3.2
> } else {
>     wxWidgets.use   wxGTK-3.0
> }

As El Capitan is Darwin 15, should the test not be 
` if {${os.platform} eq "darwin" && ${os.major} > 15} {
`?

**Comment by barracuda156** [comment]
@pietvo I _think_ we rather use a standard `wxWidgets-3.0` where possible and keep `wxGTK-3.0` as a fallback, so maybe:
```
if {${os.platform} eq "darwin" && ${os.major} > 15} {
wxWidgets.use wxWidgets-3.2
} elseif {${os.platform} eq "darwin" && ${os.major} > 10} {
wxWidgets.use wxWidgets-3.0
} else {
wxWidgets.use wxGTK-3.0
}
```

I am not really sure of exact threshold and have no way to establish it though. AFAIK, on 10.6 (any version and all archs) and earlier `wxGTK-3.0` is unavoidable, since `wxWidgets-3.0` has a bug preventing it from being usable. So `> 10` is pretty sure.
But perhaps it is also okay just to use `wxGTK-3.0` on everything prior to El Capitan.

**Comment by pietvo** [comment]
I think all should be settled now for commit. I have checked that the new setup works correctly at my system (Ventura).

**Pull request merged**
