### PR TITLE
py-mitmproxy: Update to version 6.0.2, Add Python 39

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Review by cjones051073 — CHANGES_REQUESTED** [review]
I know you did not introduce them, but could you address the lint errors.

**Comment by essandess** [comment]
> I know you did not introduce them, but could you address the lint errors.

I renamed the patch file appropriately. Some of the missing dips have PRs. It will take longer to chase the others down the DAG.

**Comment by cjones051073** [comment]
Thanks. Are there PRs for the missing py39 deps ?

**Comment by essandess** [comment]
> Thanks. Are there PRs for the missing py39 deps ?

Nope, not yet.

**Comment by essandess** [comment]
> > Thanks. Are there PRs for the missing py39 deps ?
> 
> Nope, not yet.

* #10531
* #10532
* #10533
* #10534

**Comment by ryandesign** [comment]
> I renamed the patch file appropriately.

In the future please don't rename patches for this reason. The lint complaint about patchfile names is outdated and the next major version of MacPorts will have revised guidance. See https://trac.macports.org/ticket/59695.

**Pull request merged**
