### PR TITLE
vim: add modeline

### PR DESCRIPTION
**Pull request by iefdev**
#### Description

vim: add modeline

###### Type(s)

- [x] update

###### Tested on

macOS 10.7.5 11G63
Xcode 4.6.3 4H1503

###### Verification

Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
> * Without cctools vim can't build in trace mode when `strip' is
>   hidden from the build system.

I wouldn't add a cctools dep just for that reason. The same reasoning could apply to hundreds of other ports. The `strip` provided by Xcode should normally be sufficient.

**Comment by iefdev** [comment]
I just took the program that was stated as hidden (and caused the break) and checked what port it was provided by.

```
$ which -a strip
/opt/local/bin/strip
/usr/bin/strip
```

So, how to make it pick up the other strip? Use `path:bin/strip` instead?

**Comment by ryandesign** [comment]
> I just took the program that was stated as hidden (and caused the break)

Could you show us what error message you got?

> So, how to make it pick up the other strip?

I would expect the build to use whatever `strip` is available in PATH, whether that is /opt/local/bin/strip from cctools or /usr/bin/strip from Xcode/command line tools.

> Use `path:bin/strip` instead?

Specifying a dependency `path:bin/strip:cctools` would mean "install the cctools port unless the file /opt/local/bin/strip already exists" so that's not helpful for avoiding an unnecessary cctools install. A dependency `bin:strip:cctools` would mean "install the cctools port unless the file strip already exists in any of the directories in PATH" which by default includes /usr/bin so that could be used, but again, we have not been adding this to the probably at least hundreds of ports that use strip in their build process, just as we have not been adding `bin:sed:gsed`, `bin:grep:grep`, `bin:awk:gawk` to all of the probably thousands of ports that happen to use sed, grep or awk in their build systems. Granted, our decision not to do that predates the existence of trace mode, so if trace mode requires us to reconsider that decision we can.

**Comment by iefdev** [comment]
> Could you show us what error message you got?

Here's the portion about strip:

```bash
:info:destroot strip /opt/local/var/macports/build/_opt_local_var_macports_sources_github.com_macports_macports-ports_editors_vim/vim/work/destroot/opt/local/bin/vim
:info:destroot strip: can't move temporary file:

// ... more “strip: can't move”

:warn:destroot The following existing file was hidden from the build system by trace mode:
:msg:destroot   /opt/local/bin/strip
```

I can remove `cctools` from the Portfile, and make a `-vst destroot` to get the full log if you want.

> I would expect the build to use whatever strip is available in PATH, whether that is /opt/local/bin/strip from cctools or /usr/bin/strip from Xcode/command line tools.

I have both `strip` (as shown above), but appearently it didn't care about looking further and stopped when the first one that was hidden.

**Comment by ryandesign** [comment]
> ```
> :info:destroot strip: can't move temporary file:
> ```

It would be nice to know what temporary file it can't move to where and why. This doesn't sound like a problem of trace mode blocking access to the strip program, since it's the strip program that's printing that message.

**Comment by iefdev** [comment]
I guess _that_ (full) line would be `vim.strip -> vim`:

```
:info:destroot strip: can't move temporary file: /opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/destroot/opt/local/bin/vim.strip to input file: /opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/destroot/opt/local/bin/vim (No such file or directory)
```

<details> 
  <summary>...</summary>

´´´
:debug:destroot Tracemode will respect recursively collected port dependencies: gettext libiconv ncurses
:debug:destroot Executing org.macports.destroot (vim)
:debug:destroot Environment: 
:debug:destroot CC_PRINT_OPTIONS='YES'
:debug:destroot CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/.CC_PRINT_OPTIONS'
:debug:destroot CPATH='/opt/local/include'
:debug:destroot DEVELOPER_DIR='/Applications/Xcode.app/Contents/Developer'
:debug:destroot LIBRARY_PATH='/opt/local/lib'
:debug:destroot MACOSX_DEPLOYMENT_TARGET='10.7'
:info:destroot Executing:  cd "/opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/vim-8.2.1719" && /usr/bin/make -w install DESTDIR=/opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/destroot 
:debug:destroot system:  cd "/opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/vim-8.2.1719" && /usr/bin/make -w install DESTDIR=/opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/destroot 
:info:destroot make: Entering directory `/opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/vim-vim-10e4f12'
:info:destroot Starting make in the src directory.
:info:destroot If there are problems, cd to the src directory and run make there
:info:destroot cd src && /usr/bin/make install
:info:destroot make[1]: Entering directory `/opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/vim-vim-10e4f12/src'
:info:destroot if test -f /opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/destroot/opt/local/bin/vim; then \
:info:destroot 	  mv -f /opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/destroot/opt/local/bin/vim /opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/destroot/opt/local/bin/vim.rm; \
:info:destroot 	  rm -f /opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/destroot/opt/local/bin/vim.rm; \
:info:destroot 	fi
:info:destroot cp vim /opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/destroot/opt/local/bin
:info:destroot strip /opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/destroot/opt/local/bin/vim
:info:destroot strip: can't move temporary file: /opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/destroot/opt/local/bin/vim.strip to input file: /opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/destroot/opt/local/bin/vim (No such file or directory)
:info:destroot make[1]: *** [installvimbin] Error 1
:info:destroot make[1]: Leaving directory `/opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/vim-vim-10e4f12/src'
:info:destroot make: *** [install] Error 2
:info:destroot make: Leaving directory `/opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/vim-vim-10e4f12'
:info:destroot Command failed:  cd "/opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/vim-8.2.1719" && /usr/bin/make -w install DESTDIR=/opt/local/var/macports/build/_opt_ports_dev_editors_vim/vim/work/destroot 
:info:destroot Exit code: 2
:warn:destroot The following existing file was hidden from the build system by trace mode:
:msg:destroot   /opt/local/bin/strip
```

</details>

**Comment by ryandesign** [comment]
Hmm. I don't know why that's happening. And I only see 4 results when I Google that error message and none of them help me understand it.

On 10.13.6 I am unable to get through vim's configure phase when using trace mode because all configure checks fail with:
```
xcrun: error: invalid DEVELOPER_DIR path (/Applications/Xcode.app/Contents/Developer), missing xcrun at: /Applications/Xcode.app/Contents/Developer/usr/bin/xcrun
```

**Comment by iefdev** [comment]
Ok, so there might be more things going on here? I could at least configure and build.

> This doesn't sound like a problem of trace mode blocking access to the strip program, since it's the strip program that's printing that message.

When I read the log a I saw the `strip` msg's, and adding `cctools` fixed it - I thought it was.

**Comment by raimue** [comment]
It is kind of normal that you could be using different tools in a normal build than with trace mode. For example, similar things happen when installing ports like binutils. Some build system will prefer `g*` tools and although they can be compatible and do not harm in a normal build, under trace mode they will be hidden.

The `/opt/local/bin/strip` was hidden by trace mode and I assume it used `/usr/bin/strip` instead. The real error message `strip: can't move temporary file:` must have some other cause...

**Comment by iefdev** [comment]
Yes, it prob is - especially since Ryan's test stopped at config.

I thought I should try again, and make a full log - also including `-d`. And it got all the way to destroot. I looked again at the command I used and noticed I had entered the letters alphabetically (ie `-dstv`).

So, does the order of the options/args really matter?

I retried again with only `-vst`. That one stopped at the same place like before, but `-stv` made it through. o_0

It still complained about the same thing but continued, and then did the same strip error thing with `xxd` later in the log, but it finalized it to destroot. I'm feeling a bit confused by this.

**Comment by iefdev** [comment]
I removed the cctools, but I guess the modeline still could be added. Updated the commit msg to that.

**Comment by ryandesign** [comment]
> So, does the order of the options/args really matter?

Nope.

All single-dash options must appear immediately after the word `port` and before the command, in any order. All double-dash options must appear after the command, in any order.

**Comment by iefdev** [comment]
> Nope.

Yes, that's what I thought. And that's the confusing part - why `-vst` breaks, but `-stv` works.

**Comment by iefdev** [comment]
> I removed the cctools, but I guess the modeline still could be added. Updated the commit msg to that.

Fixed the title, and the 1'st post as well. Is there anything else to do?

**Comment by ryandesign** [comment]
> And that's the confusing part - why `-vst` breaks, but `-stv` works.

I can't see how that could be. Just look at the code for how the flags are processed:

https://github.com/macports/macports-base/blob/master/src/port/port.tcl#L4567

It loops through the flags you set, and for each one, sets the corresponding variable. The order in which the variables are set couldn't matter.

**Pull request merged**
