### PR TITLE
Updated ncview to version 2.1.8

### PR DESCRIPTION
**Pull request by thiagoveloso**
Available at ftp://cirrus.ucsd.edu/pub/ncview/ncview-2.1.8.tar.gz

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
This cannot work because you have not changed the checksums.

**Comment by pmetzger** [comment]
Also, the `revision` line should have been removed.

**Comment by pmetzger** [comment]
@thiagoveloso Why did you close this rather than fixing it?

**Comment by thiagoveloso** [comment]
@pmetzger sorry, that was my first attempt ever to contribute to MacPorts. I'll fix the PR by adding the checksums of the updated file as soon as the Ncview ftp website come online again (it's been down for a few hours).

**Pull request closed without merging**
