### PR TITLE
hptt: fix compiler choice on <10.7, fix build on >10.6 Intel after recent change to gcc settings

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

On 10.6 gcc-4.2 gets picked; fix that.

Macports, unfortunately, moved GCC to use libc++, which is untested. To no surprise, it does not work. Set libstdc++ manually, fix the build.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Hmm, we get an error which was not there earlier (`hiop` has not been updated, so it is either `gcc` or something else).

**Comment by cjones051073** [comment]
I do not think the fix is is the right way to go. See discussion in https://github.com/macports/macports-ports/commit/30a50c174346b502af883ce3d9ca829cf8d256b5#commitcomment-108191462

We should first see if the issues with gcc and libc++ can be addressed, as this goes beyond just this port.

**Comment by barracuda156** [comment]
> I do not think the fix is is the right way to go. See discussion in [30a50c1#commitcomment-108191462](https://github.com/macports/macports-ports/commit/30a50c174346b502af883ce3d9ca829cf8d256b5#commitcomment-108191462)
> 
> We should first see if the issues with gcc and libc++ can be addressed, as this goes beyond just this port.

We can always switch it back for Intel to use `libc++`. What benefit we get by having it broken until someone fixes Clang headers?

**Comment by cjones051073** [comment]
The 'quick_exit' errors above where introduced I suspect by

https://github.com/macports/macports-ports/commit/30a50c174346b502af883ce3d9ca829cf8d256b5#commitcomment-108191462

which updated the LLVM headers gcc uses from clang 14 to clang 16. This improved support for newer c++ standards, but if it also caused this error I will just revert that change and go back to clang-14. At which point you should remove  the line forcing `macports-libstdc++`

**Comment by barracuda156** [comment]
> The 'quick_exit' errors above where introduced I suspect by
> 
> [30a50c1#commitcomment-108191462](https://github.com/macports/macports-ports/commit/30a50c174346b502af883ce3d9ca829cf8d256b5#commitcomment-108191462)
> 
> which updated the LLVM headers gcc uses from clang 14 to clang 16. This improved support for newer c++ standards, but if it also caused this error I will just revert that change and go back to clang-14. At which point you should remove the line forcing `macports-libstdc++`

@cjones051073 Converted this to draft for now – if you could fix Clang header, that gonna solve the problem in a better way indeed.

**Comment by barracuda156** [comment]
Fixed in https://github.com/macports/macports-ports/commit/a13f740688545c194bbac873cb6af818015cc425

**Pull request closed without merging**
