### PR TITLE
remove py34, add py38 subports + various other fixes (maintainer kurthindenburg)

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR removes PY34 subports that have no dependencies from ports maintained by @kurthindenburg 

The use of ```python.versions``` doesn't add subports if a port doesn't start with ```py-```; delete this line in ```speedtest-cli```; if you want to be able to run it with different Python versions you should define ```variants```.

EDIT: it now also includes adding PY38 subports and various other fixes for stuff that I noticed when checking upstream and looking more closely at the Portfiles.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.6 18G95
Xcode 10.3 10G8
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
Please note that the build failures are not related to this PR. 

- the failure of speedtest-cli is already fixed with the commit changing the github PG. 
- the failure for py-cheroot is due to a newer version of py-setuptools; likely updating the py-cheroot port to its latest upstream version will resolve this. I can attempt that later this weekend, or we can leave this to the maintainer to resolve after merging this PR.

**Comment by kurthindenburg** [comment]
go ahead - is there any reason you're not adding py38?  or would that complicate it?

**Comment by reneeotten** [comment]
I can certainly do that! I typically add tests first to confirm the test-suite passes before adding PY38. If you’re fine with me making some more changes to “your” ports I am happy to do that. I’ll update this PR once I am done with that so for your final approval.

**Comment by reneeotten** [comment]
@kurthindenburg okay, that was more work that I initially thought....

I went trough the ports, checked upstream and/or the test-suite and added PY38 subports. While doing so there were quite a few small things in addition to missing/unneeded depedencies and the occasional version update. I've added PY38 subports for required dependencies as well.

So in the end, this PR has became quite a bit more substance; which was kind of what I was trying to avoid when cleaning up obsolete Python versions. All other things should be ideally done by the maintainer; so please take a look and merge if/when you're happy with it. If you want to make changes please do so by pushing to my branch so that we can keep it all nicely organized - thanks!

**Comment by kurthindenburg** [comment]
whoa that's a lot of work - thanks a lot - the things I normally test all appear to work as expected - I haven't installed python3.8 so I can't test that.

**Comment by reneeotten** [comment]
> whoa that's a lot of work - thanks a lot - the things I normally test all appear to work as expected - I haven't installed python3.8 so I can't test that.

I did run the tests for PY38 where available, that all worked as well. If it looks good to you please merge; if something did fall through the cracks we'll fix it afterwards!

**Pull request merged**
