### PR TITLE
.github: Add a GitHub Actions workflow

### PR DESCRIPTION
**Pull request by l2dy**
#### Description
WIP: We are working on dropping the pastebin requirement.

### CODE REVIEW

**Comment by pmetzger** [comment]
You seem to have accidentally included a change to `asciidoctor` along with your proposed addition of the Github CI.

BTW, I'd propose that if we add the Github CI, that we end use of Travis at some point. It doesn't consistently work anyway; it's just a distraction.

**Comment by mojca** [comment]
Github CI is probably not that much different from Azure, but yes, Travis is kind of getting too annoying to be useful.

**Comment by l2dy** [comment]
> You seem to have accidentally included a change to `asciidoctor` along with your proposed addition of the Github CI.

It was there to test the pull request :)

**Comment by pmetzger** [comment]
@l2dy Ah. I didn't realize. It had seemed like an accident.

**Comment by markemer** [comment]
Yeah, Travis always fails. I rarely pay attention to it, and it makes every PR present with a red X.

**Comment by markemer** [comment]
I was able to Github CI working pretty well, actually - I did some weird stuff like building base, but I think it should be reasonable to do.

**Comment by pmetzger** [comment]
@l2dy Any status on this?

**Comment by l2dy** [comment]
> @l2dy Any status on this?

I need to set the paste URL to https://paste.z0k.xyz/ to get logs uploaded.

But I'm not sure if we really need GitHub Actions, we have Azure Pipelines which is basically the same infrastructure with different APIs. GitHub Actions has native integration with the GitHub web interface though.

**Comment by pmetzger** [comment]
I would say that we should get rid of Travis and maybe switch over to GitHub actions? Though I'm not sure about the latter. Dumping Travis seems like a good move, though. It no longer adds value.

**Comment by pmetzger** [comment]
Either way, though, we should put this PR to bed...

**Comment by kencu** [comment]
I'm looking to kill off ancient PRs that aren't going anywhere -- is this one?

**Comment by l2dy** [comment]
I'll check if Azure Pipelines provides a better API now. If it does, we can switch to it and abandon both Travis CI and GitHub Actions.

**Comment by l2dy** [comment]
We could use artifacts to store logs, which would remove the need for a pastebin. https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts

**Comment by mojca** [comment]
I would be in favour of adding support for github actions if we already have the code, even if it duplicates azure. If we can avoid pastebin, the benefit is even bigger. We can later decide to drop azure if results end up being the same.

**Comment by l2dy** [comment]
Merged as db7b40d8691e1fcd8b6be5e3c2a2a00a7ce0bdf4.

**Pull request closed without merging**
