### PR TITLE
libtapi: build by bootstrap compiler

### PR DESCRIPTION
**Pull request by catap**
#### Description

The idea is start to simplify dependencies for old system.

The first step is libtapi which is build by bootstrap compiler.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 10K549 x86_64
Xcode 3.2.6 10M2518

macOS 10.6.8 10K549 x86_64
Xcode 3.2.6 10M2518

macOS 12.4 21F79 arm64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
what happens if you try to build libtapi on 10.6.8 using clang-11-bootstrap?

**Comment by kencu** [comment]
What happens if cctools is already installed, and you try to build this on, say, 10.8 or 10.9? Previously, that errored out, but I see you removed the libtool workaround I put in to fix that. Maybe it is not needed any longer.

**Comment by catap** [comment]
> what happens if you try to build libtapi on 10.6.8 using clang-11-bootstrap?

It can't be linked with error:
```
/Developer/usr/bin/libtool: object: CMakeFiles/LLVMDemangle.dir/ItaniumDemangle.cpp.o malformed object (unknown load command 2)
/Developer/usr/bin/libtool: object: CMakeFiles/LLVMDemangle.dir/MicrosoftDemangle.cpp.o malformed object (unknown load command 2)
/Developer/usr/bin/libtool: object: CMakeFiles/LLVMDemangle.dir/MicrosoftDemangleNodes.cpp.o malformed object (unknown load command 2)
```
=> `libtool` need to be updated :)

By some reason `gcc10-bootstrap` can be used.

> What happens if cctools is already installed, and you try to build this on, say, 10.8 or 10.9? Previously, that errored out, but I see you removed the libtool workaround I put in to fix that. Maybe it is not needed any longer.

It works, but I can't use clang-11-bootstrap for cctools without this patch: https://github.com/llvm/llvm-project/commit/aabaca33635885e81baa79730b6b213fc96ac636

I've already backported it to a branch and right now I'm rebuilding everything.

Let me mark it as draft, maybe updated clang allows to make things simpler :)

**Comment by kencu** [comment]
oh, sure, the objects produced by clang-11 are too new for the stock cctools to handle. I should have anticipated that, as we’ve seen it many times before. I wish there was some option to control that… yes, that will be a problem. Nice that gcc10 is smart enough to know better.

the change in llvm argument handling is why I held our cctools back to llvm10, so there’s another old issue known for years coming around again.

Well, all this is why every system needs testing before anything can be pushed.

But worthwhile once it happens.

**Comment by catap** [comment]
@kencu I'm switched to test on 10.5 and my goal is: clang-11-bootstrap -> cctools -> libtapi -> ld64; or something like that.

Stay tuned :)

**Comment by kencu** [comment]
you’ll have the same bootstrapping issue building cctools with clang11. The objects will be too new.

**Comment by kencu** [comment]
that’s why we built cctools with clang-3.4 so far during bootstrap.

well, we always knew this would be hard.

**Comment by kencu** [comment]
the solution may turn out to be to build cctools with gcc10-bootstrap against libc++.

problem is cctools needs to be built against some newer llvm version, and using the one in clang11-bootstrap is not ideal.

I’ve always resisted the throwaway bootstrap cctools installation, but it may be inevitable.

bootstrapping is fun :)

**Comment by catap** [comment]
@kencu another approach is using lld from clang-11 as linker to link everything at bootstrap stage.

Anyway, an approach "just work" doesn't allow to produce a binary which is linked agains libcxx and which is possible to run on 10.5

You may find some thouhgs here: https://github.com/catap/macports-ports/tree/macOS-10.5 as you may see on of the issue that `dyld` on 10.5 a bit different and hasn't got `dyld_stub_binder` that requires some additional patch inside lld to allow it link something.

Anyway, I really not sure that it is the right direction at all. Maybe idea to build `cctools` by `gcc10-bootstrap` which is used `clang-11-bootstrap` isn't so bad.

**Comment by catap** [comment]
@kencu I've built both `libtapi` and `cctools` on macOS 10.5 by `clang-11-bootstrap`.

Anyway, right now I face an issue:
```
/opt/local/libexec/clang-11-bootstrap/bin/clang++ -Os -Os -std=c++11 -fblocks -Wno-deprecated-declarations -Wno-parentheses-equality -DTARGET_OS_OSX=1 -DTARGET_OS_WATCH=0 -DTARGET_OS_BRIDGE=0 -I/opt/local/libexec/clang-11-bootstrap/include -stdlib=libc++ -stdlib=libc++ -arch i386  -Isrc/abstraction -Isrc/ld -Isrc/ld/parsers -I/opt/local/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_ld64/ld64-latest/work/dyld-655.1.1/include  -c -o src/other/ObjectDump.o src/other/ObjectDump.cpp
/opt/local/libexec/clang-11-bootstrap/bin/clang -Os -Os -arch i386  -Isrc/abstraction -Isrc/ld -Isrc/ld/parsers -I/opt/local/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_ld64/ld64-latest/work/dyld-655.1.1/include  -c -o src/ld/debugline.o src/ld/debugline.c
/opt/local/libexec/clang-11-bootstrap/bin/clang++ -Os -Os -std=c++11 -fblocks -Wno-deprecated-declarations -Wno-parentheses-equality -DTARGET_OS_OSX=1 -DTARGET_OS_WATCH=0 -DTARGET_OS_BRIDGE=0 -I/opt/local/libexec/clang-11-bootstrap/include -stdlib=libc++ -stdlib=libc++ -arch i386  -Isrc/abstraction -Isrc/ld -Isrc/ld/parsers -I/opt/local/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_ld64/ld64-latest/work/dyld-655.1.1/include  -c -o src/ld/parsers/macho_relocatable_file.o src/ld/parsers/macho_relocatable_file.cpp
/opt/local/libexec/clang-11-bootstrap/bin/clang++ -Os -Os -std=c++11 -fblocks -Wno-deprecated-declarations -Wno-parentheses-equality -DTARGET_OS_OSX=1 -DTARGET_OS_WATCH=0 -DTARGET_OS_BRIDGE=0 -I/opt/local/libexec/clang-11-bootstrap/include -stdlib=libc++ -stdlib=libc++ -arch i386  -Isrc/abstraction -Isrc/ld -Isrc/ld/parsers -I/opt/local/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_ld64/ld64-latest/work/dyld-655.1.1/include  -c -o src/ld/parsers/lto_file.o src/ld/parsers/lto_file.cpp
/opt/local/libexec/clang-11-bootstrap/bin/clang++  -L/opt/local/lib -Wl,-headerpad_max_install_names -lBlocksRuntime -L/opt/local/libexec/clang-11-bootstrap/lib -lLTO -lc++abi -stdlib=libc++ -arch i386 src/other/ObjectDump.o src/ld/debugline.o src/ld/parsers/macho_relocatable_file.o src/ld/parsers/lto_file.o -o ObjectDump
ld: atom not found in symbolIndex(__ZdlPv) for /usr/lib/libc++abi.dylib
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

maybe you have an idea what's wrong?

**Comment by Gcenx** [comment]
Please avoid white spaces changes, only making required changes to make it easier to review

**Comment by Gcenx** [comment]
I still believe always forcing a bootstrap compiler for no reason is irritating.

For libtapi anything below 10.12 could just use gcc10-bootstrap, anything later should be able to build using the default toolchain.

I really hate the idea of being forced into building gcc10-bootstrap > clang-11-bootstrap just to build libtapi

**Comment by kencu** [comment]
as a general rule, MacPorts expects everything to always be built with
clang, unless it is impossible to do so.

So you should not be distressed by the recommendation to build libtapi with
clang11-bootstrap. If we did otherwise, there would be questions raised,
and it would almost certainly be changed at some point in the future to
build with clang anyway.

**Comment by Gcenx** [comment]
@kencu the annoyance is for _any_ system that can currently build libtapi without requiring macports-clang would now be required to compile gcc10-bootstrap > clang-11-bootstrap > etc > libtapi

This being the same concern I’d expressed about clang-11-bootstrap always building against gcc10-bootstrap when on systems that could build it directly.

**Comment by kencu** [comment]
sure, systems that can build it with the native toolchain can do so

**Comment by catap** [comment]
Close it in favour of https://github.com/macports/macports-ports/pull/15684

**Pull request closed without merging**
