### PR TITLE
CMake py311 sphinx ports add py311 support

### PR DESCRIPTION
**Pull request by michaelld**
#### Description

Add Python 3.11 support to Python ports required by `cmake +python311` from [this commit](https://github.com/macports/macports-ports/commit/9f6f6bc9cfdbeffe587b236259740d80886ef6f8).

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 11.7.2 20G1008
Xcode 12.3 12C33

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jmroot** [comment]
Also needs pygments and babel (which has its own dependencies).

**Comment by catap** [comment]
and also before simple add `py311` variant, you need to run tests to confirm that it is still working, which leads to much more dependencies...

**Comment by catap** [comment]
@michaelld I'm afraid that it is huge rabbit hole.

`py-babel` includes tests and this tests are also requires some `py311` variants...

**Comment by michaelld** [comment]
> Also needs pygments and babel (which has its own dependencies).

Added. I pulled to the current PortIndex & I think this PR now is complete ... I'll admit I haven't tested the Py311 versions yet of any of these ports, but `cmake +docs +python311` does build, so that's a start.

**Comment by michaelld** [comment]
> @michaelld I'm afraid that it is huge rabbit hole.
> 
> `py-babel` includes tests and this tests are also requires some `py311` variants...

OK I've added py-freezegun which allows `port test py311-babel` to pass ... moving on to other tests now

**Comment by catap** [comment]
> OK I've added py-freezegun which allows `port test py311-babel` to pass ... moving on to other tests now

Last week I've tried to add `py311` to `httpx` and after 50 ports I've gave up.

I wish you shortest path!

**Comment by michaelld** [comment]
> > OK I've added py-freezegun which allows `port test py311-babel` to pass ... moving on to other tests now
> 
> Last week I've tried to add `py311` to `httpx` and after 50 ports I've gave up.
> 
> I wish you shortest path!

LOL thanks! To first order this PR is good to go. I tried `port test` on the ports being tweaked here & either they pass or do not provide `test`. Maybe I just got lucky that the Sphinx Python ports don't do much testing?!

**Comment by catap** [comment]
@michaelld from another had a lot of py311 subports were added last days => it is quite possible that you near the end :)

**Comment by jmroot** [comment]
I guess a missing test dependency isn't fatal in the short term, but this needs to be fixed before too long:
```
port lint py311-freezegun:
Error: Unknown dependency: py311-mock
```

**Review by jmroot — APPROVED** [review]

**Comment by michaelld** [comment]
`py311-mock` added

**Review by reneeotten — APPROVED** [review]

**Comment by michaelld** [comment]
Someone else updated `py-mock` and `py-freezegun` ... will remove them before merging. Will wait another 24 hours to give the full 48 hour maintainer timeout, unless someone else thinks otherwise.

**Comment by michaelld** [comment]
48 hour maintainer timeout for simple changes. Merging

**Pull request merged**
