### PR TITLE
capstone: move to github, fix livecheck

### PR DESCRIPTION
**Pull request by l2dy**
###### Description

*(delete all below for minor changes)*

###### Tested on
macOS 10.12.3
Xcode 8.2.1

###### Verification
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? (Please don't open a new Trac ticket if you are submitting a pull request.)
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -v install`?

### CODE REVIEW

**Comment by tobypeterson** [comment]
Same version but checksum changed? Did you compare the two sets of sources?

**Comment by l2dy** [comment]
No I didn't. The new archive is generated by GitHub and linked on http://www.capstone-engine.org/download.html.

**Comment by tobypeterson** [comment]
Well, I suspect that it may end up being an issue for people who have the previous tarball, as well as for mirroring. Probably need dist_subdir since it will have the same file name as the old one.

**Comment by l2dy** [comment]
Note that suffix is different.

**Comment by tobypeterson** [comment]
Good point. I just checked, there's absolutely no difference between the tarballs that I can see, even though the checksums don't match. Not ideal, but it'll do.

**Pull request merged**
