### PR TITLE
clang-16, llvm-16: restore functionality on macOS 15 (Xcode 16)

### PR DESCRIPTION
**Pull request by markmentovai**
This is a cherry-pick of:
https://github.com/llvm/llvm-project/commit/c57c7b7c99605021123b54c02e57943923874cbe https://github.com/llvm/llvm-project/commit/7939ce39dac0078fef7183d6198598b99c652c88

This enables clang-16 to be built by Xcode 16, making it possible to build on macOS 15, and macOS 14 with Xcode 16. It also enables clang-16 to be built by clang-18 and newer.

References: https://trac.macports.org/ticket/70779

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 15.0 24A335 arm64
Xcode 16.0 16A242d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

@cjones051073

### CODE REVIEW

**Comment by markmentovai** [comment]
Also:
 - clang-17: #25912
 - clang-15: #25918
 - clang-14: #25919

**Comment by cjones051073** [comment]
I am sure @markmentovai tested this himself, but just as the ci builds don't have macOS15 yet I've tested it myself locally (arm64) and seems to work fine.

**Comment by cjones051073** [comment]
@markmentovai can you check the test error here on macOS12 ? I thought with clang-17 it was just a timeout, as these builds are long, but perhaps more to it ?

**Comment by markmentovai** [comment]
https://github.com/macports/macports-ports/pull/25917#issuecomment-2375350146:
> @markmentovai can you check the test error here on macOS12 ? I thought with clang-17 it was just a timeout, as these builds are long, but perhaps more to it ?

[macos-12](https://github.com/macports/macports-ports/actions/runs/11036575259/job/30655327303?pr=25917) → [raw logs](https://productionresultssa18.blob.core.windows.net/actions-results/211b6eec-61d3-40d0-9dc1-5c9f25ffda6b/workflow-job-run-68ae2b36-89dd-55dc-09eb-5ce01d4cd3c7/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-09-26T02%3A07%3A22Z&sig=joOB3As547e9NE7XljMd38ON75YM0%2B0DiCeOPdezO%2F0%3D&ske=2024-09-26T12%3A26%3A47Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-09-26T00%3A26%3A47Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-09-26T01%3A57%3A17Z&sv=2024-05-04)

```
2024-09-25T15:48:36.5782270Z Current runner version: '2.319.1'
[…]
2024-09-25T21:59:33.3877560Z DEBUG: process_cmd aborted: SIGTERM signal received
[…]
2024-09-25T21:59:33.4024380Z Error: Aborted: SIGTERM received.
2024-09-25T21:59:33.4383460Z ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
2024-09-25T21:59:33.5097100Z ##[error]The operation was canceled.
2024-09-25T21:59:33.5562380Z Cleaning up orphan processes
```

Looks like a timeout. It was making regular progress right up until receiving `SIGTERM` at the end. No other errors appear in the log.

**Pull request merged**
