### PR TITLE
adwaita-icon-theme: patch to disable parallel processing

### PR DESCRIPTION
**Pull request by lukaso**
Remove parallel processing which freezes mac

#### Description

Fixes [#67243](https://trac.macports.org/ticket/67243)

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.3.1 22E772610a arm64
Xcode 14.3 14E222b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mascguy** [comment]
There's was one minor issue with the patch, which that the `src/` part of the paths was missing. Was easy enough to fix though, and looks good now.

Will merge once CI completes. Thank you so much for contributing this Lukas!

**Review by mascguy — APPROVED** [review]

**Comment by lukaso** [comment]
Thanks for fixing. It was too late at night for me to go full bore and get it all right. The brain had stopped working.
I wish the development side of macports was easier. I know it's hard to change, but there are a lot of technical barriers to really contributing easily (like properly creating patches in a sudo required directory).

**Comment by mascguy** [comment]
> Thanks for fixing. It was too late at night for me to go full bore and get it all right. The brain had stopped working. I wish the development side of macports was easier. I know it's hard to change, but there are a lot of technical barriers to really contributing easily (like properly creating patches in a sudo required directory).

No worries... you did the hard work, so we're more than happy to jump in and help. Thanks again Lukas!

**Comment by mascguy** [comment]
p.s. Ironically enough, without the parallel processing, `adwaita-icon-theme` appears to build faster than it did before. (Haven't timed it to the second, but it certainly feels faster.) Great stuff!

**Comment by lukaso** [comment]
Yeah, I noticed the same. And much faster than locking up the machine :)

**Pull request merged**
