### PR TITLE
Update to nccmp 1.8.7.0

### PR DESCRIPTION
**Pull request by Dave-Allured**
###### Type(s)

- [x ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6
Xcode 11.3

###### Verification 
Have you

- [x ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

- [x ] checked your Portfile with `port lint`?
- [x ] tried existing tests with `sudo port test`?
- [x ] tried a full install with `sudo port -vst install`?
    * -vst fails, expected, no sudo permission
    * -vs works with no problem, installed in custom user prefix
- [x ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
Your commit does not follow our guidelines. Please update it to have the form 

portname: description

**Comment by Dave-Allured** [comment]
Apologies.  This is my first update PR.  Will fix.

Is it okay for me to edit the current PR message, or do I need to start a new PR?

**Comment by cjones051073** [comment]
> Apologies.  This is my first update PR.  Will fix.
> 
> 
> 
> Is it okay for me to edit the current PR message, or do I need to start a new PR?

No worries.

Please note though it is not the PR title that is wrong but the commit comment itself. 

There is no need to close this and open a new PR. Just ammend the commit message in your local checkout, then force push the change to the same branch in github. This PR will then just adapt.

**Comment by Dave-Allured** [comment]
@ryandesign, thanks for merging.  I will try to get the commit message right, the next time.

**Pull request merged**
