### PR TITLE
H3d patches

### PR DESCRIPTION
**Pull request by jjandersson**
#### Description
Most of the patches are simply fixing python linking issues. Also some fixes for errors related to recent upgrade of Bullet/ODE in h3dphysics.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.4
Xcode 9.4.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jjandersson** [comment]
Hmm I can't seem to be able to figure this one out..

> --->  Applying patch-pytypewrapper.diff
Applying this patch fails. It does however get applied when I install it via my local repository.

The only difference I can see is that the file this patch tries to fix(~include/H3D/PyTypeWrapper.h) for some reason uses a different line-ending than all the others. Now since the patch tool strips leading CR's from the .diff file, but not the file its being applied to, there will be a missmatch. And the only solution would be to create a new Port release (?)

Still strange that the patch gets applied on my machine with a local repository setup..

**Comment by cjones051073** [comment]
Have the maintainers been notified for this ? the portfile does not include a github handle so it isnt automatic.

Also, your commits do not actually follow the guidelines correctly. They should start with ‘name:’

See https://trac.macports.org/wiki/CommitMessages for mor details.

**Comment by pmetzger** [comment]
@cjones051073 Can I leave this to you to shepherd?

**Comment by jjandersson** [comment]
The maintainers are notified. Apologies for the poorly formatted commit comments, let me know if I should create a new PR.

I would like to figure out what is wrong with the patch first though. Seems unlikely, but could it be caused by different versions of _patch_? I have 2.5.8, any way to figure out which version travis workers are using?

**Comment by cjones051073** [comment]
No need to start a new PR. Just roll back in your local branch the commits, recommit with updated messages and then force push the branch back to your fork. This PR will then just adspt.

**Comment by jjandersson** [comment]
@cjones051073 Thanks, I've updated the commit comments. Also added a "closes"-reference to this recently created ticket: https://trac.macports.org/ticket/57465

Still trying to figure out the failing patch, do you have any ideas that I could try?

**Comment by cjones051073** [comment]
Are you sure the source being patched is *exactly* the same as that used to generate the patch ? From the error message, it

**Comment by jjandersson** [comment]
@cjones051073 Thanks a lot, I fetched the source from the mirror and recreated the patch and now it seems to work! What further steps do I need to take for this PR to be accepted and merged? Is this the port maintainers responsibility?

**Comment by cjones051073** [comment]
One thing you need to do is fix the commits. Please squash them together and follow the commit guidelines.

**Comment by pmetzger** [comment]
Your commit messages continue to not mention the port in the first line (or follow standards...)

**Comment by jjandersson** [comment]
Apologize, I got confused by the Github-desktop applications summary entry.
Hope it looks better now!

**Comment by cjones051073** [comment]
Thanks, the commits now look good.

The remaining issue would then be maintainer approval. You say you contacted them, what was the outcome of this ? 

If the maintainers have a github handle, then the maintainers section of the portfile should be extended to add this. For one, it means they are automatically notified in the case of future PRs. It would also be a good opportunity, if they agree, to add the openmaintainer handle. Most ports that do not currently have this do so simple because no one thought to add it when it was first prepared, not because the maintainer explicitly does not want it...

**Comment by SenseGraphics** [comment]
jandersson is a trusted contributor.
This pull request is good.
But how do we go about accepting it? There was not even a github account associated to this email.

**Comment by pmetzger** [comment]
@SenseGraphics We can take your word for it. Probably your github handle should be put in the Portfile as well as a correct email address.

**Comment by jjandersson** [comment]
I added github handle to all Portfiles. This was an exception to the rule "A committ only affects one portfile" if I understand correctly. Hopefully it looks good, let me know if I should change it in any way.

**Comment by mojca** [comment]
There's no rule saying that one commit should affect one portfile. The only rule would be not to make a bunch of **unrelated** changes in a single commit.  The way you did it makes perfect sense.

**Comment by pmetzger** [comment]
Merged. Thanks for the updates, @jjandersson!

**Pull request merged**
