### PR TITLE
qt5-qtwebengine: fix list of build failures

### PR DESCRIPTION
**Pull request by markemer**
#### Description

* Turn off following warnings qt5-qtwebengine to stop errors:
  * `-Wenum-constexpr-conversion`
  * `-Wunused-but-set-variable`
* Fix -Wcast-function-type-struct errors in harfbuzz
* Add missing dependencies in ninja files

Fixes: https://trac.macports.org/ticket/70850

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 15.0 24A335
Xcode 16.0 16A242d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
The failure in the macOS 14 CI log is:

```
deps/boost/1.65.1/include/boost/mpl/aux_/integral_wrapper.hpp:73:31: error: integer value -1 is outside the valid range of values [0, 3] for the enumeration type 'int_float_mixture_enum' [-Wenum-constexpr-conversion]
deps/boost/1.65.1/include/boost/mpl/aux_/static_cast.hpp:24:47: note: expanded from macro 'BOOST_MPL_AUX_STATIC_CAST'
   24 | #   define BOOST_MPL_AUX_STATIC_CAST(T, expr) static_cast<T>(expr)
      |                                               ^
```

This is https://trac.macports.org/ticket/70477.

The errors in the macOS 13 CI log start with:

```
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/c++/v1/cstddef:50:9: error: no member named 'nullptr_t' in the global namespace
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/c++/v1/__type_traits/is_null_pointer.h:24:49: error: use of undeclared identifier 'nullptr_t'
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/c++/v1/exception:149:45: error: field has incomplete type 'exception_ptr'
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/c++/v1/exception:144:24: note: definition of 'std::exception_ptr' is not complete until the closing '}'
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/c++/v1/exception:149:5: error: '__abi_tag__' attribute only applies to structs, variables, functions, and namespaces
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/c++/v1/exception:149:55: error: expected ';' at end of declaration list
```

I don't know what this is.

**Comment by markemer** [comment]
Yeah, the mac12 ones start with that too - I'm not sure the deal - the boost one I saw. Maybe I'll make this into an all purpose fixer-upper since, wow, qt is a hell of a port to build.

**Comment by markemer** [comment]
Before I go off all half-cocked here - qtwebengine just did a patch release - gonna give that a try.

**Comment by markemer** [comment]
It's building on 15 - oof that was an ordeal.

**Comment by markemer** [comment]
The patches are failing on the CI boxes which makes no sense to me as they work just fine from a full clean on my machine.

**Comment by markemer** [comment]
This patch works 100% fine on my machine even from a `clean --all qt5-qtwebengine` - what the heck could be going on?

```
2024-10-01T02:05:13.0597250Z DEBUG: system:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_aqua_qt5/qt5-qtwebengine/work/qtwebengine-5.15.16-lts" && /usr/bin/patch -t -N -p0 < '/Users/runner/work/macports-ports/macports-ports/ports/aqua/qt5/files/patch-qtwebengine-browser-build.gn.diff'
2024-10-01T02:05:13.0602170Z Executing:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_aqua_qt5/qt5-qtwebengine/work/qtwebengine-5.15.16-lts" && /usr/bin/patch -t -N -p0 < '/Users/runner/work/macports-ports/macports-ports/ports/aqua/qt5/files/patch-qtwebengine-browser-build.gn.diff'
2024-10-01T02:05:13.0787930Z patching file src/3rdparty/chromium/components/history/core/browser/BUILD.gn
2024-10-01T02:05:13.0789900Z can't find file to patch at input line 13
2024-10-01T02:05:13.0791030Z Perhaps you used the wrong -p or --strip option?
2024-10-01T02:05:13.0793420Z The text leading up to this was:
2024-10-01T02:05:13.0793980Z --------------------------
2024-10-01T02:05:13.0795030Z |--- 3rdparty/chromium/content/public/browser/BUILD.gn	2024-09-29 19:28:09
2024-10-01T02:05:13.0796150Z |+++ 3rdparty/chromium/content/public/browser/BUILD.gn	2024-09-29 19:29:18
2024-10-01T02:05:13.0796940Z --------------------------
2024-10-01T02:05:13.0797360Z No file to patch.  Skipping patch.
2024-10-01T02:05:13.0797830Z 1 out of 1 hunk ignored
2024-10-01T02:05:13.0800640Z Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_aqua_qt5/qt5-qtwebengine/work/qtwebengine-5.15.16-lts" && /usr/bin/patch -t -N -p0 < '/Users/runner/work/macports-ports/macports-ports/ports/aqua/qt5/files/patch-qtwebengine-browser-build.gn.diff'
2024-10-01T02:05:13.0803800Z Exit code: 1
2024-10-01T02:05:13.0804490Z Error: Failed to patch qt5-qtwebengine: command execution failed
2024-10-01T02:05:13.0805230Z DEBUG: Error code: CHILDSTATUS 76596 1
2024-10-01T02:05:13.0806000Z DEBUG: Backtrace: command execution failed
2024-10-01T02:05:13.0806520Z     while executing
2024-10-01T02:05:13.0806980Z "system {*}$notty {*}$callback {*}$nice $fullcmdstring"
2024-10-01T02:05:13.0807570Z     invoked from within
2024-10-01T02:05:13.0808040Z "command_exec patch "" "< '$patch'""
2024-10-01T02:05:13.0808610Z     (procedure "portpatch::patch_main" line 41)
2024-10-01T02:05:13.0809160Z     invoked from within
2024-10-01T02:05:13.0809550Z "$procedure $targetname"
2024-10-01T02:05:13.0810870Z Error: See /opt/local/var/macports/logs/_Users_runner_work_macports-ports_macports-ports_ports_aqua_qt5/qt5-qtwebengine/main.log for details.
2024-10-01T02:05:13.0842420Z Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
2024-10-01T02:05:13.0843580Z Error: Processing of port qt5-qtwebengine failed
2024-10-01T02:05:13.0879010Z Build of 'qt5-qtwebengine' failed.
```

**Comment by markemer** [comment]
Ok, tonight I'm going to build VMs for mac 12-15 and pull this branch, and try and install from scratch. If that works, I'm gonna merge it.

**Comment by markemer** [comment]
Found it! A missing `src` from a path - not sure why it worked locally. But once I ran it from a full clean slate, blammo.

**Comment by markemer** [comment]
Hey, @reneeotten can you take a look - this works for me locally, but the patches seem to fail, and I think it's an order of operations thing.

**Comment by reneeotten** [comment]
> Hey, @reneeotten can you take a look - this works for me locally, but the patches seem to fail, and I think it's an order of operations thing.

I'm trying this now, we should update as well to the latest version (5.11.17) though even if these fixes are still needed, likely other stuff has been improved.

**Comment by markemer** [comment]
> > Hey, @reneeotten can you take a look - this works for me locally, but the patches seem to fail, and I think it's an order of operations thing.
> 
> I'm trying this now, we should update as well to the latest version (5.11.17) though even if these fixes are still needed, likely other stuff has been improved.

I was thinking that too, myself.

**Comment by reneeotten** [comment]
> > > Hey, @reneeotten can you take a look - this works for me locally, but the patches seem to fail, and I think it's an order of operations thing.
> > 
> > 
> > I'm trying this now, we should update as well to the latest version (5.11.17) though even if these fixes are still needed, likely other stuff has been improved.
> 
> I was thinking that too, myself.

I am building that now, if it works without trouble I'll push a commit to this PR.

**Comment by reneeotten** [comment]
@markemer this works for me, thanks for fixing it - the update to 5.15.17 was trivial of course. I'd be in favor of merging this!

**Pull request merged**
