### PR TITLE
caddy: checksum mismatch in go dep

### PR DESCRIPTION
**Pull request by mrdomino**
#### Description

Caddy fails to build with a checksum error. Apparently the checksum, but not file size, of the tar file for imdario-mergo-v0.3.12.tar.gz has changed.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mrdomino** [comment]
https://trac.macports.org/ticket/69132 tracks.

**Comment by mrdomino** [comment]
Figured out what's going on: https://trac.macports.org/ticket/69132#comment:1

@mohd-akram do you happen to have any idea how to sync the distfiles between macports and github?

**Comment by pmetzger** [comment]
If the issue is a stealth update, see the section of the macports guide for dealing with stealth updates.

**Comment by mrdomino** [comment]
Sounds like we should change the `dist_subdir` for that dependency but not bump the revision, since there is no meaningful change (it's a case of "the base directory got renamed.")

Dunno how to change `dist_subdir` for a go dep.

**Comment by mrdomino** [comment]
Oh fun, something is expecting to extract `imdario-mergo-*` instead of `darccio-mergo-*` and the build is now broken on that too.

**Comment by mrdomino** [comment]
Ok, so I had gotten the diff backwards — the current base directory of `imdario-mergo-v0.3.12.tar.gz` on github starts with `darccio-mergo`. What's happening is that the base directory has gotten out of step with the archive (and repo) name somehow.

**Comment by mrdomino** [comment]
Ok, I think the user just changed their name. Github is redirecting from imdario/mergo to darccio/mergo and the generated tar file is being given the new user's name, which also updates the base dir.

This is really nasty. It breaks dependencies trying to import `github.com/imdario/mergo`.

**Comment by mrdomino** [comment]
This is now officially above my paygrade; I'm going to close this and let further work happen on Trac.

**Pull request closed without merging**
