### PR TITLE
cabal: Update to version 3.8.1.0

### PR DESCRIPTION
**Pull request by essandess**
* Update to version 3.8.1.0
* Add arm64
* Refactor bootstrap approach for ghc-9.4.1
* Update haskel_cabal-1.0.tcl

#### Description

This effectively depends upon #15770 for arm support.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.5.1 21G83 x86_64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by essandess** [comment]
I do not understand why the CI fails after a few seconds. I've tested `sudo port -vstd install cabal` locally and everything works as expected.

**Comment by reneeotten** [comment]
@essandess I restarted the tests but it still fails in boostrapping MacPorts; perhaps rebasing with `master` and a force-push to the PR would resolve this....? 
The new Python ports you added would only be required when building the documentation using Sphinx - most (Python) ports don't build the documentation by default - is that actually happening here and are the dependencies thus needed? Since the CI didn't do an actual build I couldn't really see what was happening (as I didn't want to build this locally....).

**Comment by essandess** [comment]
> @essandess I restarted the tests but it still fails in boostrapping MacPorts; perhaps rebasing with `master` and a force-push to the PR would resolve this....?
> The new Python ports you added would only be required when building the documentation using Sphinx - most (Python) ports don't build the documentation by default - is that actually happening here and are the dependencies thus needed? Since the CI didn't do an actual build I couldn't really see what was happening (as I didn't want to build this locally....).

This version of `cabal` is coupled with the latest version of `ghc`, which is up to 9.4.2. They’ve fixed a lot of stuff, added arm support, a working `DESTDIR` functionality, `hadrian`-based bootsraps, so it’s a bit of a moving target to refactor everything. I have local versions running but am trying to make them robust on arm. See #15770.

Bottom line, let me push another refactor onto #15570, then this PR should just work after rebasing.

As for sphinx, that and a man page are the available documentation for `cabal`. The attached Python libraries are used to build a local version of `cabal` documentation.

**Comment by essandess** [comment]
This PR is superseded by #15770.

**Pull request closed without merging**
