### PR TITLE
Tortoisehg 6.2

### PR DESCRIPTION
**Pull request by Themanwithoutaplan**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.15.7 19H1922 x86_64
Xcode 12.4 12D4e
macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by Themanwithoutaplan** [comment]
I did run port test but the failure did not seem related to the port itself and the app itself runs fine.

One small thing I would also like to change: the name of the app in the Mac menu is "Python" but should be "Tortoisehg" but I don't know how to do this.

**Comment by ryandesign** [comment]
> * [x]  followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?

The commit message should read "tortoisehg: Update to 6.2". You've also got a second "merge" commit in this PR that we don't want. We can fix both of these problems by pressing the "Squash and merge" button and rewording the commit message there when we are ready to merge this PR, or you can fix it in your branch and force-push.

CI failed on macOS 12 while installing a dependency:
```
Installing dependency (155 of 181) 'py310-pyqt5' with variants '' ... [FAIL]
```
I don't see any details about why in the CI logs, but I'll bet it's because of https://trac.macports.org/ticket/65410. CI cancelled the builds on other OS versions because of the failure on macOS 12.

**Comment by Themanwithoutaplan** [comment]
I messed the commit up by being on the wrong origin and updating my fork subsequently. I'm not very familiar with git so if you can make the changes it would probably be better.

This is the test error I got
```
:info:test Command failed:  cd "/opt/local/var/macports/build/_Users_charlieclark_temp_macports-ports_devel_tortoisehg/tortoisehg/work/thg-6.2" && /opt/local/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 ./tests/run-tests.py --tmpdir=/opt/local/var/macports/build/_Users_charlieclark_temp_macports-ports_devel_tortoisehg/tortoisehg/work/testtmp --verbose -o addopts=''
:info:test Exit code: 1
:error:test Failed to test tortoisehg: command execution failed
:debug:test Error code: CHILDSTATUS 77099 1
:debug:test Backtrace: command execution failed
:debug:test     while executing
:debug:test "system {*}$notty {*}$callback {*}$nice $fullcmdstring"
:debug:test     invoked from within
:debug:test "command_exec -callback portprogress::target_progress_callback test"
:debug:test     (procedure "porttest::test_main" line 4)
:debug:test     invoked from within
:debug:test "$procedure $targetname"
```

**Comment by mascguy** [comment]
It looks like @danchr just updated this port to 6.2, but he simply wasn't aware of this PR:

https://github.com/macports/macports-ports/commit/88c684b975345cb8d669aa3c3eea86325903401b

**Pull request closed without merging**
