### PR TITLE
dovecot2 and dovecot2-sieve: Update to version 2.3.8

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [x] update
- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
there is an open PR #5236 with changes to the same port, it appears though that this would upgrade to a higher version. It looks like that other PR has stalled for a while already, but would address some open tickets once merged. Please take a look at that PR and perhaps take some changes from there as well so that both PRs can be closed at the same time?!

**Comment by essandess** [comment]
PR https://github.com/macports/macports-ports/pull/5236 is a major Portfile refactor.

That’s a great idea, but I’d simply like an update of dovecot now.

May we please keep version updates and refactoring on separate tracks, and would you @reneeotten please ask the author of PR https://github.com/macports/macports-ports/pull/5236 to update their PR to reflect current state?

**Comment by essandess** [comment]
@reneeotten @mf2k @cjones051073 

The vulnerability assessment of the previous dovecot version is rather [high](https://www.cvedetails.com/vulnerability-list.php?vendor_id=6485&product_id=0&version_id=0&page=1&hasexp=0&opdos=0&opec=0&opov=0&opcsrf=0&opgpriv=0&opsqli=0&opxss=0&opdirt=0&opmemc=0&ophttprs=0&opbyp=0&opfileinc=0&opginf=0&cvssscoremin=0&cvssscoremax=0&year=0&cweid=0&order=1&trc=37&sha=5fc3ca102d580ee204b181809c720eb094ff796by).

Would someone please merge this update ASAP?

**Comment by cjones051073** [comment]
OK, I'll merge. The author of the other PR, https://github.com/macports/macports-ports/pull/5236, already needs to anyway rebase.

**Pull request merged**
