### PR TITLE
boost178: new port

### PR DESCRIPTION
**Pull request by michaelld**
#### Description

Add Boost 1.78.0 port

Closes: https://trac.macports.org/ticket/64428

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.6.3 20G409
Xcode 12.3 12C33

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by michaelld** [comment]
I copied the whole directory from boost177 & updated the Portfile and patches. I've installed the port and even tested it against a couple ports with success.

**Review by mascguy — APPROVED** [review]
LGTM. @reneeotten ?

**Comment by mascguy** [comment]
Now that the CI jobs have completed, we're ready to merge.

@reneeotten any thoughts/concerns?

**Comment by reneeotten** [comment]
> Now that the CI jobs have completed, we're ready to merge.
> 
> @reneeotten any thoughts/concerns?

this was a very quick turnaround and I'm a bit busy right now.... but I'll take a look when I have time. Of course if both of the maintainers have looked this over/tested it I am fine with merging no need to wait for me to try it out.

**Comment by michaelld** [comment]
Since both maintainers approve, I'm going to go ahead and merge. Thx for the timely commenting!

**Pull request merged**
