### PR TITLE
libepoxy: python is just a build-time dependency

### PR DESCRIPTION
**Pull request by yan12125**
###### Description

As title, python is just a build-time dependency for libepoxy. Installed files of libepoxy:
```
  /opt/local/include/epoxy/common.h
  /opt/local/include/epoxy/gl.h
  /opt/local/include/epoxy/gl_generated.h
  /opt/local/include/epoxy/glx.h
  /opt/local/include/epoxy/glx_generated.h
  /opt/local/lib/libepoxy.0.dylib
  /opt/local/lib/libepoxy.dylib
  /opt/local/lib/pkgconfig/epoxy.pc
```
There are no Python scripts or packages. Headers don't have Python.h inclusions, and libraries does not link to libpython.

###### Tested on
macOS 10.2.5
Xcode 8.3.3

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
 there are no tickets
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`? There are no tests
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files? GTK+3 OpenGL demo runs, so I guess libepoxy is working

### CODE REVIEW

**Comment by neverpanic** [comment]
@dbevans If those are just build dependencies, should we also drop the Python variants and just choose a single version to reduce complexity?

**Comment by neverpanic** [comment]
Oh, and to get rid of the dependency on Python for people that already have this port installed, the `revision` field needs to be increased (or added and set to 1).

**Comment by neverpanic** [comment]
@yan12125 Since @dbevans doesn't seem to have the time to review this right now, would you like to go ahead and drop the Python variants in favor of just 2.7 or 3.5 and bump the revision field?

Or would you rather get this merged as-is?

**Comment by yan12125** [comment]
Keeping only 2.7 and 3.6 sounds better to me. I don't have access to Mac
machines until the next week. I'll update this pull request soon.

**Comment by yan12125** [comment]
Now xcode6.4 (Yosemite) test failed. It's strange because the previous Yosemite run (https://travis-ci.org/macports/macports-ports/jobs/252505313) passed.

**Comment by yan12125** [comment]
https://travis-ci.org/macports/macports-ports/builds/255123145 passed. Maybe the [previous failure](https://travis-ci.org/macports/macports-ports/jobs/254747530) is due to something tricky in mpbb?

**Comment by raimue** [comment]
The integration with Travis CI is an ongoing effort and under development by @l2dy as a GSoC project. No idea what caused the failure here, but it is just not reliable yet.

**Comment by yan12125** [comment]
Thanks everyone!

**Pull request closed without merging**
