### PR TITLE
pulseaudio: update to 17.0

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

A long-due update.

Dependents will need a revbump. Let us confirm the build first.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

macOS 14.2.1
Xcode 15.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Tests on 10.6:
```
--->  Testing pulseaudio
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_audio_pulseaudio/pulseaudio/work/build" && /opt/local/bin/ninja test 
[0/1] Running all tests.
 1/48 Validate xml file default.pa.5.xml           OK               0.13s
 2/48 Validate xml file pacmd.1.xml                OK               0.11s
 3/48 Validate xml file pasuspender.1.xml          OK               0.08s
 4/48 Validate xml file pulse-cli-syntax.5.xml     OK               0.13s
 5/48 Validate xml file pulse-daemon.conf.5.xml    OK               0.12s
 6/48 Validate xml file pulseaudio.1.xml           OK               0.10s
 7/48 Validate xml file start-pulseaudio-x11.1.xml OK               0.13s
 8/48 Validate xml file pacat.1.xml                OK               0.14s
 9/48 Validate xml file pactl.1.xml                OK               0.15s
10/48 Validate xml file pulse-client.conf.5.xml    OK               0.12s
11/48 Validate xml file pax11publish.1.xml         OK               0.15s
12/48 Validate desktop file                        OK               0.15s
13/48 channelmap-test                              OK               0.14s
14/48 get-binary-name-test                         OK               0.11s
15/48 hashmap-test                                 OK               0.12s
16/48 proplist-test                                OK               0.09s
17/48 json-test                                    OK               0.18s
18/48 utf8-test                                    OK               0.08s
19/48 mainloop-test                                OK               2.07s
20/48 mainloop-test-glib                           OK               0.11s
21/48 asyncmsgq-test                               OK               0.09s
22/48 asyncq-test                                  OK               1.10s
23/48 close-test                                   OK               0.07s
24/48 volume-test                                  OK               9.18s
25/48 thread-mainloop-test                         OK              10.09s
26/48 cpu-sconv-test                               OK               0.08s
27/48 cpu-volume-test                              OK               0.11s
28/48 format-test                                  OK               0.10s
29/48 hook-list-test                               OK               0.12s
30/48 lfe-filter-test                              OK               0.12s
31/48 core-util-test                               FAIL            16.32s   exit status 1
>>> MAKE_CHECK=1 ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MALLOC_PERTURB_=29 /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_audio_pulseaudio/pulseaudio/work/build/src/tests/core-util-test
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stdout:
Running suite(s): Core-Util
80%: Checks: 15, Failures: 0, Errors: 3
../pulseaudio-17.0/src/tests/core-util-test.c:265:E:core-util:test_replace_fail_1:0: (after this point) Test timeout expired, expected signal 6 (Abort trap)
../pulseaudio-17.0/src/tests/core-util-test.c:275:E:core-util:test_replace_fail_3:0: (after this point) Test timeout expired, expected signal 6 (Abort trap)
../pulseaudio-17.0/src/tests/core-util-test.c:297:E:core-util:test_replace_fail_4:0: (after this point) Test timeout expired, expected signal 6 (Abort trap)
stderr:
Assertion 's' failed at ../pulseaudio-17.0/src/pulsecore/core-util.c:3345, function pa_replace(). Aborting.
Assertion 'a' failed at ../pulseaudio-17.0/src/pulsecore/core-util.c:3346, function pa_replace(). Aborting.
Assertion 'b' failed at ../pulseaudio-17.0/src/pulsecore/core-util.c:3348, function pa_replace(). Aborting.
Assertion '*a' failed at ../pulseaudio-17.0/src/pulsecore/core-util.c:3347, function pa_replace(). Aborting.
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

32/48 memblock-test                                OK               0.25s
33/48 memblockq-test                               OK               0.21s
34/48 mix-test                                     OK               0.13s
35/48 mult-s16-test                                OK              12.05s
36/48 proplist-modargs-test                        OK               0.10s
37/48 queue-test                                   OK               0.07s
38/48 resampler-test                               OK               0.09s
39/48 resampler-rewind-test                        OK               0.08s
40/48 rtpoll-test                                  OK               0.09s
41/48 smoother-test                                OK               0.11s
42/48 strlist-test                                 OK               0.10s
43/48 lock-autospawn-test                          OK              20.10s
44/48 sigbus-test                                  OK               0.12s
45/48 usergroup-test                               OK               0.64s
46/48 cpu-remap-test                               OK              26.08s
47/48 cpu-mix-test                                 OK              33.60s
48/48 thread-test                                  OK               7.85s

Summary of Failures:

31/48 core-util-test                               FAIL            16.32s   exit status 1

Ok:                 47  
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0
```

**Comment by barracuda156** [comment]
Ok, the build is fine now.

**Comment by barracuda156** [comment]
I skip CI for revbumping dependents, since a) there are some ports which are broken, so CI will not pass due to those and b) it gonna time-out anyway due to Qt5 and Qt6 stuff.

**Comment by ryandesign** [comment]
It's unfortunate that the switch to meson decreased the library's minor version number.

**Comment by pmetzger** [comment]
@barracuda156

**Comment by barracuda156** [comment]
@ryandesign Should we do something about that? Revbumping dependents was done for this.

**Pull request merged**
