### PR TITLE
Jwhowarth pymol 2.4.0 update

### PR DESCRIPTION
**Pull request by jwhowarth**
###### Type(s)

- [ ] bugfix
- [ x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.4 19E287
Xcode 11.5 11E608c 

###### Verification 
Have you

- [ x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ x] checked your Portfile with `port lint`?
- [x ] tried existing tests with `sudo port test`?
- [x ] tried a full install with `sudo port -vst install`?
- [ x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
@jwhowarth thanks for the update. I mentioned this at the previous update: we should really separate the two interfaces (Qt / Tk) now and put the legacy Tk one in an optional variant. Currently `pymol` will never build out-of-the-box due to the use of an non-default variant for `tcl`. Besides that the interface has been obsolete for a while now and there is no need to pull in both the Tk/Tcl and the Qt ports as almost every end-user will only use one of the two.

So I would suggest a slightly other update with the main focus on separating the interfaces, but I would also add `mspack` as a dependency and include the needed `build.args`. I'll take another look tomorrow and can show you my suggested Portfile and we can take it from there.

**Comment by jwhowarth** [comment]
Actually, we'll also want to add the additional string.split() fixes that upstream just committed after I reported the apbs_tools.py instance.

[https://github.com/schrodinger/pymol-open-source/commit/aa0645e90fb6aab6180cca726e3f2a2453cde829](url)
[https://github.com/schrodinger/pymol-open-source/commit/e1122b078e43fb7e503a32ed5c6176e8d36ec4ea](url)

**Comment by cjones051073** [comment]
@jwhowarth Need to squash the commits together, and also please make sure you actually do follow our commit guidelines. i.e. the message needs to take the form `port name: description`.

**Comment by reneeotten** [comment]
closed in favor of a new PR by @jwhowarth

**Pull request closed without merging**
