### PR TITLE
llvm-{11,12,13,14,devel}: fix compatibility with legacy-support on 10.5

### PR DESCRIPTION
**Pull request by catap**
#### Description

legacy-support since v1.0.5 contains `typedef char uuid_string_t[37]` when removed patch contains `typedef char * uuid_string_t`.

An attempt to build it may fail with error:
```
../llvm/tools/dsymutil/SymbolMap.cpp:23:16: error: typedef redefinition with different types ('char *' vs 'char [37]')
typedef char * uuid_string_t;
               ^
/opt/local/include/LegacySupport/uuid/uuid.h:31:14: note: previous definition is here
typedef char uuid_string_t[37];
             ^
1 error generated.
```

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.5.8 9L34 i386
Xcode 3.1.4 9M2809

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
yes, marcus moved that patch into legacysupport, slightly different it seems.

there are probably other patches that could also be either removed now, as they are in legacysupport.... or what is in the patch could be moved into legacysupport instead, now that we have that mechanism working well.

**Review by kencu — APPROVED** [review]
lgtm, untested

**Comment by catap** [comment]
@kencu `llvm-11` has been suceffuly build with local root from this PR + https://github.com/macports/macports-ports/pull/15660 ; `clang-11` is building right now.

**Comment by kencu** [comment]
> @kencu `llvm-11` has been suceffuly build with local root from this PR + #15660 ; `clang-11` is building right now.

of course, #15660 is now unnecessary/optional now that you fixed your sdk.

**Comment by catap** [comment]
@kencu I still would like to merge #15660 to stop distributing wired patches :)

**Comment by kencu** [comment]
i know you would

**Comment by catap** [comment]
@mascguy maybe this also should be merged?

**Comment by mascguy** [comment]
> @mascguy maybe this also should be merged?

@jmroot / @cjones051073, any thoughts/concerns...?

**Review by mascguy — APPROVED** [review]
LGTM, given the nature of the changes. But let's get at least one more thumbs-up before merging.

**Pull request merged**
