### PR TITLE
p5-perl-languageserver: new port

### PR DESCRIPTION
**Pull request by chrstphrchvz**
###### Tested on

macOS 10.15.7
Perl 5.32.0

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
failing every CI test. Please explain

**Comment by chrstphrchvz** [comment]
CI errored while determining what ports to build; I'm not aware why.

**Comment by chrstphrchvz** [comment]
Someone familiar with the CI would have to figure out why it is failing.

**Comment by jmroot** [comment]
Commit is creating a file called `p5-perl-languageserver` rather than a directory of that name with a Portfile inside.

**Pull request merged**
