### PR TITLE
botan: update to 2.10.0; fix/bump dependents

### PR DESCRIPTION
**Pull request by yan12125**
#### Description

This is a preparation step for the OpenSSL 1.1 migration. botan 1.x has
reached EOL in the end of 2018 [1] and will not be compatible with
OpenSSL 1.1.

In this pull request I created monotone-devel and ask existing monotone users to use monotone-devel. Not sure if there is a better approach or not.

Closes: https://trac.macports.org/ticket/58513
Ref: #3822

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [x] security fix

###### Tested on
macOS 10.14.5 18F132
Xcode 10.2 I think - updated to Xcode 11 beta a few days ago and I didn't test it again

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files? Tested monotone-devel - can run `mtn clone "mtn://code.monotone.ca/monotone?net.venge.monotone"`

### CODE REVIEW

**Comment by RJVB** [comment]
2 things:

- one usually doesn't use `revision 0` (it's the default)
- why set `configure.optflags -O3` while -Os is the MacPorts default? Why not simply unset the variable if you don't want to use the MacPorts default?

**Comment by yan12125** [comment]
> - one usually doesn't use `revision 0` (it's the default)

For symmetry between monotone and monotone-devel :)
Some relevant discussions about `revision 0`: https://lists.macports.org/pipermail/macports-dev/2018-December/039928.html

> - why set `configure.optflags -O3` while -Os is the MacPorts default? Why not simply unset the variable if you don't want to use the MacPorts default?

Good catch! I will test and update this PR.

**Comment by RJVB** [comment]
More observations:

- Mac OS X 10.9 doesn't have MAP_ANONYMOUS but MAP_ANON. AFAIK that is actually the cross-platform name.
- I needed to add (on 10.9.5, with clang 5.0 from MacPorts)
```
    if {${os.major} <= 13} {
        depends_lib-append    port:sqlite3
        configure.args-append --disable-modules=certstor_system_macos \
                              --with-sqlite3
    }
```
  No idea if this is required on any of the newer OS versions too. I added sqlite3 so certstor_sqlite3 would be built as an alternative. You may of course consider this a good thing anyway.
  (the error looked like a C++11 error but was apparently due to something else):
```
src/lib/x509/certstor_system_macos/certstor_macos.cpp:297:35: error: no matching constructor for initialization of 'std::vector<CFStringRef>' (aka 'vector<const __CFString *>')
         std::vector<CFStringRef> keys({kSecClass,
```
- you can do
```
if {[tbool configureccache]} {
    configure.args-append   --cc-bin="${prefix}/bin/ccache ${configure.cxx}"
} else {
    configure.args-append   --cc-bin=${configure.cxx}
}
```

**Comment by yan12125** [comment]
> Good catch! I will test and update this PR.

Unsetting optflags removes all optimization flags. Appanrently CXXFLAGS is already overwritten.

And thank you for testing and suggestions! I've incorporated those changes in this PR.

**Comment by RJVB** [comment]
>Unsetting optflags removes all optimization flags. Appanrently CXXFLAGS is already overwritten.

That's possible, I admit I only tested with my own `configure.optflags` on the commandline.

That should leave the possibility to *append* -O3. The way optim. flags work that will override the earlier default -Os but will not remove any other optflags that might have been set before.

**Comment by yan12125** [comment]
> That's possible, I admit I only tested with my own `configure.optflags` on the commandline.

> That should leave the possibility to *append* -O3. The way optim. flags work that will override the earlier default -Os but will not remove any other optflags that might have been set before.

Well, I've tried removing the configure.optflags line, and botan is compiled with `-Os`. `-O3` is set by the build system of botan based on settings in botan-2.10.0/src/build-data/cc/clang.txt, and looks like MacPorts is not aware of that.

**Comment by yan12125** [comment]
OK now all ports should build on at least 10.11+. I'm going to merge this to check if there are failures on older systems. Remaining issues like optflags can be discussed and fixed later.

**Pull request merged**
