### PR TITLE
swipl: junit is not required for build

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Comment by pmetzger** [comment]
Have you contacted either of the maintainers?

**Comment by grimreaper** [comment]
No. I thought we had some automation around pull requests that did that for me?

**Comment by pmetzger** [comment]
I'm fairly new, but I don't think any such automation happens for github PRs where the maintainers don't have listed github IDs.

**Comment by pmetzger** [comment]
Anyway, I'd like to merge this but could you just send email to the maintainers first?

**Comment by grimreaper** [comment]
Sure. Forgot about this for a bit. Will do now.

**Comment by pmoura** [comment]
Can you also apply the same change to the `lang/swi-prolog-devel/Portfile` file?

**Comment by grimreaper** [comment]
done

**Comment by pmoura** [comment]
Thanks. I agree with the changes (but note that neither me or Jan have the necessary permissions to accept the pull request).

**Comment by grimreaper** [comment]
On this page https://github.com/macports/macports-ports/pull/1210/files you should be able to "Accept" it even if you can't merge it.

**Comment by pmetzger** [comment]
As Travis is horribly backlogged and may never actually terminate the CI check I'm going to merge.

**Pull request merged**
