### PR TITLE
yabai: update to version 4.0.0

### PR DESCRIPTION
**Pull request by Ci7rix**
* update to version 4.0.0

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.3.1 21E258 x86_64
Xcode 13.3.1 13E500a

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by TheKevJames** [comment]
@Ci7rix looks like some checksum errors here:
```
  Error: Checksum (size) mismatch for yabai-4.0.0.tar.gz
  The correct checksum line may be:
  checksums           rmd160  951e2b20428fae7ada2ecbe2b75476e5b8405100 \
                      sha256  efadb820b4485208b9267739e4205e2273f1f4a30f270ff411c7c00934fb96ff \
                      size    1525695
  Error: Failed to checksum yabai: Unable to verify file checksums
```

**Comment by Ci7rix** [comment]
@TheKevJames oops, sorry for that.
I just fixed it. I'm a noob with Git, is there something else I should do ?

**Comment by Ci7rix** [comment]
Hi @TheKevJames,

Checks have failed. On my side the build is working fine.

Could you maybe help me with that, if time permits ?
Is there a way I could reproduce the build issue on my computer ? Like installing the same build tools ?  

Thank you.

**Comment by Ci7rix** [comment]
Hi

According to what I could find, the build on macOS 10.15 version does not work because it requires a version identical or higher than Xcode 12.2 in order to build a universal binary (see here https://github.com/koekeishiya/yabai/issues/1191#issuecomment-1069711506).

For macOS 11, if I understand correctly the 'safeAreaInsets' property does not exist yet in this version. I found a similar problem here: https://trac.macports.org/ticket/63824#comment:1

If I understand correctly, it is necessary to set the minimal version of Xcode to 12.2 and the minimal version of macOS to 12.0.

If so, how do I do it?

Thanks

**Comment by TheKevJames** [comment]
Hi @Ci7rix ! My understanding is that you've done the right thing in specifying the minimum xcode version. I think the OS version follows from the xcode version, though: so, for example, since you specified 12.2 as the minimum xcode version, that means the port is meant to build on the earliest version of OSX that supports Xcode v12.2 (OSX 10.15.4, according to [this doc](https://developer.apple.com/support/xcode/)).

I would suspect the right answer here is to mark the minimum Xcode version as 13.3, since that's the oldest Xcode that supports only OSX v12 or newer.

That said, I'm pretty new to working with portfiles, so the above is mostly guesswork!

**Review by TheKevJames — APPROVED** [review]
LGTM assuming this got the build to pass.

I unfortunately don't have permissions to approve test workflows or to merge PRs -- @ryandesign and @reneeotten helped me when I first added this port, maybe one of you would be able to help out again here?

**Comment by Ci7rix** [comment]
Hi @TheKevJames,

Thank you for your help !

**Comment by l2dy** [comment]
Approved by maintainer, merging now. Thanks for your contribution.

**Pull request merged**
