### PR TITLE
py-cvxopt: update to version 1.2.3

### PR DESCRIPTION
**Pull request by jjstickel**
#### Description
In separate commits:
* fix a bug with env use
* update to version 1.2.3

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G103
Xcode 10.3 10G8

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jjstickel** [comment]
I see that @MarcusCalhoun-Lopez has worked on this port in the recent past and may wish to review.

**Comment by mf2k** [comment]
Error is:
`ModuleNotFoundError: No module named 'setuptools'
`

It looks like a missing build dependency on py-setuptools. 

Also, please squash your commits.

**Comment by pmetzger** [comment]
@mf2k I think the separate commits may be appropriate. The problem is the commit message on the bug fix isn't in our usual format; it doesn't mention what port it is for.

**Comment by jjstickel** [comment]
I'll amend the commits to correct the message and add setuptools.

**Comment by pmetzger** [comment]
The commit messages aren't quite right again (they mention fixing the bug with the environment on the wrong commit for example) but I'll just squash and merge these. Thanks, @jjstickel!

**Comment by jjstickel** [comment]
> The commit messages aren't quite right again (they mention fixing the bug with the environment on the wrong commit for example) but I'll just squash and merge these. Thanks, @jjstickel!

Are you sure? I sure thought I did the right thing and triple-checked. This github web app shows the right commit message with the associated changes, e.g.:
https://github.com/macports/macports-ports/pull/5536/commits/628cdaaf8785e61a9b4a4e83b56b5d24c11294ef
Anyway, thanks for merging.

**Pull request merged**
