### PR TITLE
Drop nodejs4

### PR DESCRIPTION
**Pull request by yan12125**
#### Description

This is a follow-up of https://github.com/macports/macports-ports/pull/4113.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
Not tested

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
https://trac.macports.org/ticket/52634 talks about nodejs 4. Not sure if it's still an issue for newer Node.js versions.
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by yan12125** [comment]
Just saw an old ticket https://trac.macports.org/ticket/51753

> Probably we should just remove any such ports that were already added (jake, coffee-script, anything using those ports).

@ryandesign: Do you want me to remove jake instead of updating it in this PR?

**Comment by yan12125** [comment]
Rebased to master for addition of nodejs12.

**Comment by yan12125** [comment]
@ci42 Any comments? Given the maintainer timeout policy, I can merge this by myself, but I still want feedback for commits dropping ports.

**Comment by ci42** [comment]
@yan12125 LGTM

**Comment by yan12125** [comment]
Great! Gonna merge.

**Pull request merged**
