### PR TITLE
cabal, ghc: Bugfix dependencies

### PR DESCRIPTION
**Pull request by essandess**
#### Description

cabal, ghc: Bugfix dependencies
* Fixes: https://trac.macports.org/ticket/65834

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6 21G115 x86_64
Xcode 14.0 14A309

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by essandess** [comment]
For some reason this `-place` line isn't working, which breaks the build when there's an existing installed `ghc-pkg` available.
```
   pre-configure {
        foreach phase {configure build destroot test} {
            ${phase}.env-replace \
                    "PATH=${haskell_cabal.cabal_root}/bin:$env(PATH)" \
                    "PATH=${workpath}/bin:$env(PATH)"
        }
    }
```

**Comment by mascguy** [comment]
> For some reason this `-replace` line isn't working, which breaks the build when there's an existing installed `ghc-pkg` available.
> 
> ```
>    pre-configure {
>         foreach phase {configure build destroot test} {
>             ${phase}.env-replace \
>                     "PATH=${haskell_cabal.cabal_root}/bin:$env(PATH)" \
>                     "PATH=${workpath}/bin:$env(PATH)"
>         }
>     }
> ```

Are you sure you want to directly access/embed the value of `PATH`, via `$env(PATH)`...?

That seems like a potential recipe for mutating weirdness. And if things don't match exactly, then the replace won't work, either.

I understand what you're trying to accomplish, but I'd need to review the full portfile to provide a better critique.

**Comment by mascguy** [comment]
> Are you sure you want to directly access/embed the value of `PATH`, via `$env(PATH)`...?
> 
> That seems like a potential recipe for mutating weirdness. And if things don't match exactly, then the replace won't work, either.
> 
> I understand what you're trying to accomplish, but I'd need to review the full portfile to provide a better critique/suggestion.

Generally speaking, you don't want to be in a situation where you're trying to replace the existing path like that. Ideally you only want to append to it.

**Comment by mascguy** [comment]
Rather than using `-replace`, you should be able to simply append your change to the environment:

```
    pre-configure {
        foreach phase {configure build destroot test} {
            ${phase}.env-append \
                    "PATH=${haskell_cabal.cabal_root}/bin:$env(PATH)" \
                    "PATH=${workpath}/bin:$env(PATH)"
        }
    }
```

Have you tested that approach?

**Comment by essandess** [comment]
> Rather than using `-replace`, you should be able to simply append your change to the environment:
> …
> Have you tested that approach?

It’s a confluence of issues, including some subtlety of how `cabal` finds `ghc-pkg`. Troubleshooting it.

**Comment by essandess** [comment]
> It’s a confluence of issues, including some subtlety of how `cabal` finds `ghc-pkg`. Troubleshooting it.

😱 https://github.com/haskell/cabal/blob/master/release-notes/Cabal-3.6.1.0.md
> Guessing the ghc-pkg path is already a hack and will be solved more appropriately in the future … As such, this patch provides a workaround for older, already existing GHC versions by first always following the symbolic link of the ghc binary (if it is one) and prefering [*sic*] its target directory as the guess lookup location.

**Comment by mascguy** [comment]
Not trying to rush you Steve, but just checking in... how are things looking?

**Comment by essandess** [comment]
@mascguy I’ve successfully tested this on multiple platforms with disparate initial states and believe that it can be merged.

**Review by mascguy — APPROVED** [review]

**Comment by essandess** [comment]
@mascguy @jmroot I see that the buildbots are failing on`ghc` prior to macOS 11.

I don’t have specific insight why, but one guess and am fysa:

There’s a `./configure` script that throws some non-breaking `xcrun` error about the xdk being CLT and not Xcode. So I just set `use_xcode yes` and the non-breaking error message went away.

It may be that using Xcode is an issue on legacy OS’s? I know that the build works with CLT, in spite of the  message.

**Comment by jmroot** [comment]
The failure on 10.14 is: `env: python3: No such file or directory`

**Comment by kencu** [comment]
I saw that python3 failure too, a while back, but along with the ccache failure, figured I’d just let it play out…

The port tries to spect a python3, but it’s not working.

https://github.com/macports/macports-ports/blob/46074d290ad4e4d0a36ee152492d5170cb69673b/lang/ghc/Portfile#L158

**Comment by jmroot** [comment]
The first problem I see is that the PATH manipulation code is in post-patch, and thus won't run if the patch phase was already completed in a previous command.

**Comment by jmroot** [comment]
The second problem is that the pre-configure block that runs `./boot` doesn't include the env.

**Comment by essandess** [comment]
> The second problem is that the pre-configure block that runs `./boot` doesn't include the env.

Thank you. Please see #16141.

**Comment by essandess** [comment]
These suggestions appear not to have resolved build issues prior to macOS 11: https://ports.macports.org/port/ghc/details/

I am unable to see the build logs (blank web page), so am unsure of what the issue is now. I confirm from my own logs and code that all logic is working as expected on macOS 12.

**Comment by mascguy** [comment]
> These suggestions appear not to have resolved build issues prior to macOS 11: https://ports.macports.org/port/ghc/details/
> 
> I am unable to see the build logs (blank web page), so am unsure of what the issue is now. I confirm from my own logs and code that all logic is working as expected on macOS 12.

I'm able to view the build logs. Which one(s) are blank?

**Comment by essandess** [comment]
> I'm able to view the build logs. Which one(s) are blank?

All of them, either via browser or command line:
```sh
wget https://build.macports.org/builders/ports-10.15_x86_64-builder/builds/112933/steps/install-port/logs/main.log/text
wc -l text.1 
       0 text.1
```

**Comment by mascguy** [comment]
> > I'm able to view the build logs. Which one(s) are blank?
> 
> All of them, either via browser or command line:
> 
> ```shell
> wget https://build.macports.org/builders/ports-10.15_x86_64-builder/builds/112933/steps/install-port/logs/main.log/text
> ```

Try this URL instead: https://build.macports.org/builders/ports-10.15_x86_64-builder/builds/112933/steps/install-port/logs/stdio/text

**Comment by essandess** [comment]
> Try this URL instead: https://build.macports.org/builders/ports-10.15_x86_64-builder/builds/112933/steps/install-port/logs/stdio/text
```sh
checking for sphinx-build... /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_ghc/ghc/work/bin/sphinx-build
checking for version of sphinx-build... sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]

configure: WARNING: Sphinx version 1.0.0 or later is required to build documentation
…
   Alex         : /opt/local/bin/alex (3.2.7.1)
   sphinx-build : 
…
# ghc-pkg (for binary-dist-dir)
| Remove file _build/bindist/ghc-9.4.2-x86_64-apple-darwin/lib/settings
Non optional builder 'sphinx-build' is not specified in 'hadrian/cfg/system.config' file.
Build failed.
Command failed:  cd "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_ghc/ghc/work/ghc-9.4.2" && hadrian binary-dist-dir -j8 
Exit code: 1
Error: Failed to build ghc: command execution failed
```

Anyone know why this is breaking on older macOS's?

The simplest thing to do is just turn off the sphinx documentation for older systems—it's all online anyway (but a nice-to-have locally).

**Comment by mascguy** [comment]
> > Try this URL instead: https://build.macports.org/builders/ports-10.15_x86_64-builder/builds/112933/steps/install-port/logs/stdio/text
> ```sh
> checking for sphinx-build... /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_ghc/ghc/work/bin/sphinx-build
> checking for version of sphinx-build... sed: illegal option -- r
> usage: sed script [-Ealn] [-i extension] [file ...]
>        sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
> 
> configure: WARNING: Sphinx version 1.0.0 or later is required to build documentation
> …
>    Alex         : /opt/local/bin/alex (3.2.7.1)
>    sphinx-build : 
> …
> # ghc-pkg (for binary-dist-dir)
> | Remove file _build/bindist/ghc-9.4.2-x86_64-apple-darwin/lib/settings
> Non optional builder 'sphinx-build' is not specified in 'hadrian/cfg/system.config' file.
> Build failed.
> Command failed:  cd "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_ghc/ghc/work/ghc-9.4.2" && hadrian binary-dist-dir -j8 
> Exit code: 1
> Error: Failed to build ghc: command execution failed
> ```
> 
> Anyone know why this is breaking on older macOS's?
> 
> The simplest thing to do is just turn off the sphinx documentation for older systems—it's all online anyway (but a nice-to-have locally).

If the project will find - and/or can be configured to use - `gsed`, that would be my recommendation.

Adding that as a build dep is fine, along with anything else to ensure it's used.

**Pull request merged**
