### PR TITLE
capnproto: update to 0.9.1

### PR DESCRIPTION
**Pull request by judaew**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.5.2 20G95 x86_64
Xcode 12.5.1 12E507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by judaew** [comment]
It looks like this error disappears when using clang 12. The requirements specify the minimum version 5.0, which I wrote about in the https://github.com/capnproto/capnproto/issues/1305.

So I'm not sure if the given PR can be merged since Clang 12 is the latest version of the compiler. A project which supports only the latest version of the compiler...

**Comment by judaew** [comment]
Looks done now.

**Comment by neverpanic** [comment]
If this needs a newer clang, shouldn't we update `compiler.blacklist-append {clang < 1000}` in line 43 to a higher number?
According to https://trac.macports.org/wiki/XcodeVersionInfo#Xcode12.0, that would be `{clang < 1200}`?

**Review by neverpanic — APPROVED** [review]
Nevermind, I see now.

**Comment by judaew** [comment]
Thanks!

**Pull request merged**
