### PR TITLE
py-pyqt5: update to 5.15.1, pin to 5.14.2 for Qt5 < 5.11

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Fixes: https://trac.macports.org/ticket/61006

#### Description
https://www.riverbankcomputing.com/news/PyQt_v5.15.1_Released

###### Tested on

pyqt5 5.15.1: macOS 10.15.6, Xcode 12 beta 5 command line tools, Python 3.8.5
pyqt5 5.14.2 on < Qt 5.11: Untested.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
```
--->  Verifying Portfile for py38-pyqt5
Error: Line 113 repeats inclusion of PortGroup qmake5
--->  1 errors and 0 warnings found.
```
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
The approach in this PR might only be the smallest possible change to get the port working for Qt5 < 5.11, and likely not the approach that should actually be used, as it does not leave the port in the most maintainable state. A better approach might instead involve putting the entire portfile as of 5.14.2 into a section that can be left as-is, keeping the 5.15.0+ port simpler as future changes are made to it. More importantly, I'm not familiar with pinning based on `${qt5.version}` nor am aware of existing examples. I'm also not certain that the ports for PyQtChart and PyQtWebEngine need to be pinned.

**Comment by kencu** [comment]
Instead of this, might it be possible to just disable the new QMultimedia control class on older qt5 versions?

**Comment by chrstphrchvz** [comment]
I will skip pinning PyQtChart and PyQtWebEngine below 5.15.0 until it is confirmed they fail to build with PyQt5 5.14.2.

I reworded the commit to instead say "See:" instead of "Fixes:" in case this PR would be useful to merge now, and a more involved fix can close the issue later.

**Comment by chrstphrchvz** [comment]
Latest Azure CI build failed due to broken `curl` (see #8152)

**Comment by michaelld** [comment]
Trying this PR on macOS 10.9 just now. It does indeed take care of the primary issue as noted in the MP ticket. That said, 2 things:

(1) the is no "version" for the default port.

(2) I get error now:
```
:info:build make[1]: Entering directory `/opt/local/var/macports/build/_Volumes_Common_MacPorts_ports_github_macports_python_py-pyqt5/py38-pyqt5/work/PyQt5-5.14.2/QtQuick'
:info:build /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -stdlib=libc++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9  -Os -std=gnu++11 -fno-exceptions -Wall -W -fPIC -DSIP_PROTECTED_IS_PUBLIC -Dprotected=public -DPy_LIMITED_API=0x03040000 -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I. -I/opt/local/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -I../qpy/QtQuick -I/opt/local/libexec/qt5/lib/QtQuick.framework/Headers -I/opt/local/libexec/qt5/lib/QtGui.framework/Headers -I/opt/local/libexec/qt5/lib/QtQml.framework/Headers -I/opt/local/libexec/qt5/lib/QtNetwork.framework/Headers -I/opt/local/libexec/qt5/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -I/opt/local/libexec/qt5/mkspecs/macx-clang -F/opt/local/libexec/qt5/lib -o sipQtQuickQSGGeometry.o sipQtQuickQSGGeometry.cpp
:info:build /opt/local/var/macports/build/_Volumes_Common_MacPorts_ports_github_macports_python_py-pyqt5/py38-pyqt5/work/PyQt5-5.14.2/QtQuick/sipQtQuickQSGGeometry.cpp:940:59: error: object of type 'QSGGeometry' cannot be assigned because its copy assignment operator is implicitly deleted
:info:build     reinterpret_cast< ::QSGGeometry *>(sipDst)[sipDstIdx] = *reinterpret_cast< ::QSGGeometry *>(sipSrc);
:info:build                                                           ^
:info:build /opt/local/libexec/qt5/lib/QtQuick.framework/Headers/qsggeometry.h:207:25: note: copy assignment operator of 'QSGGeometry' is implicitly deleted because field 'm_attributes' is of reference type 'const QSGGeometry::AttributeSet &'
:info:build     const AttributeSet &m_attributes;
:info:build                         ^
:info:build 1 error generated.
:info:build make[1]: *** [sipQtQuickQSGGeometry.o] Error 1
:info:build make[1]: Leaving directory `/opt/local/var/macports/build/_Volumes_Common_MacPorts_ports_github_macports_python_py-pyqt5/py38-pyqt5/work/PyQt5-5.14.2/QtQuick'
:info:build make: *** [sub-QtQuick-all-ordered] Error 2
:info:build make: Leaving directory `/opt/local/var/macports/build/_Volumes_Common_MacPorts_ports_github_macports_python_py-pyqt5/py38-pyqt5/work/PyQt5-5.14.2'
:info:build Command failed:  cd "/opt/local/var/macports/build/_Volumes_Common_MacPorts_ports_github_macports_python_py-pyqt5/py38-pyqt5/work/PyQt5-5.14.2" && make -w all 
:info:build Exit code: 2
```
Not sure if this is a SIP or Qt5 or PyQt5 issue ...

**Comment by chrstphrchvz** [comment]
@michaelld Thanks for trying this out. The version issue makes sense now: I had moved where it was being set to somewhere I could first check `${qt5.version}` (present when `qmake` portgroup is used), but that meant setting the version only in the subports. I think I've found an alternative (although not used by any other ports): `set just_want_qt5_version_info yes` then use the `qt5` portgroup.

I'm not sure what the error might be from. Looking the 10.9 build history of various py3x-pyqt5 on ports.macports.org, it seems to have been unable to build for several months: latest working builds appear to be from 2019-09-20 (63f346e5e2), and failures began 2019-10-17 (5331889c73), though I don't know what intermediate change to this port might've broken things, so maybe the issue is a change in a dependency.

**Comment by chrstphrchvz** [comment]
The build logs for any `failed install-port` on 10.9 have been deleted. More recent failures were due to `qt58-qt3d` failing, which seems to no longer be an issue (but builds didn't get rescheduled for dependents). Does anyone want to try merging this anyway and let the builders report up-to-date failure info?

**Comment by chrstphrchvz** [comment]
I've incorporated the update from 5.15.0 to 5.15.1 (build is still running on my system). Cc @reneeotten who last updated this port.

**Comment by chrstphrchvz** [comment]
Incorporated update to 5.15.1 for PyQtChart and PyQtWebEngine (builds successfully on macOS 10.15.6 + Xcode 12 command line tools).

**Comment by michaelld** [comment]
All of this LGTM. Let me do some local testing to verify on my current on-metal build system running 10.12. Gonna take a bit since there's various GCC ports to update to get other dependencies updated ...

**Comment by michaelld** [comment]
LGTM. Since this port is nomaintainer, and this will help with older OSs, I'm going ahead with the merge. We can always fix up later if necessary but I don't think there's anything greatly objectionable here that will need fixing up later ;)

**Comment by chrstphrchvz** [comment]
Someone else has opened a ticket (https://trac.macports.org/ticket/62009) for the same issue @michaelld noticed on older macOS (https://github.com/macports/macports-ports/pull/8128#issuecomment-680952659)

**Pull request merged**
