### PR TITLE
rust: update to 1.80.1

### PR DESCRIPTION
**Pull request by herbygillot**
- update cargo to 0.81.0

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by herbygillot** [comment]
This PR needs checksum updates for bootstrap compilers and other build assets needed by legacy systems.

**Comment by herbygillot** [comment]
CC: @catap @barracuda156 for older systems

**Comment by barracuda156** [comment]
@herbygillot Rust is just broken for powerpc at the moment – and until someone fixes it, we cannot break it any further even if we try LOL 
So powerpc is not a concern here. I have no idea about x86 though.

**Comment by herbygillot** [comment]
> @herbygillot Rust is just broken for powerpc at the moment – and until someone fixes it, we cannot break it any further even if we try LOL So powerpc is not a concern here. I have no idea about x86 though.

Taking @barracuda156's comments into account, then this PR should be ready for review if PR passes.

**Comment by MarcusCalhoun-Lopez** [comment]
> > @herbygillot Rust is just broken for powerpc at the moment – and until someone fixes it, we cannot break it any further even if we try LOL So powerpc is not a concern here. I have no idea about x86 though.
> 
> Taking @barracuda156's comments into account, then this PR should be ready for review if CI passes.

I believe this change would break Rust on every machine prior to 10.12.
I am afraid it takes quite a while to upgrade Rust in a way that works on all machines.

**Comment by herbygillot** [comment]
> I believe this change would break Rust on every machine prior to 10.12. I am afraid it takes quite a while to upgrade Rust in a way that works on all machines.

This is unsustainable.

It looks like it really is time to move forward on a separate 'rust-official` port just for macOS versions actually supported by the upstream project.

@MarcusCalhoun-Lopez, is it correct to say that the only missing piece here are the various bootstrap compilers?

**Comment by barracuda156** [comment]
> I believe this change would break Rust on every machine prior to 10.12.
> 
> I am afraid it takes quite a while to upgrade Rust in a way that works on all machines.

Perhaps just peg those to whatever last version which works? We have it for Go for example.

It is indeed infeasible to keep fixing what upstream keeps breaking. But having some working compiler is better than having none at all.

**Comment by catap** [comment]
> @MarcusCalhoun-Lopez, is it correct to say that the only missing piece here for pre-10.12 versions are the various bootstrap compilers?

I had started a while ago to build boostrap chain from mrust to actual rust. But testing it requires almost impossible amount of time. Rust version 1.x can be build only by rust 1.x-1; that means that to support 1.79 we need to have a quite the chain from 1.54 (which is the last supported version by mrustc) with 25 steps. Each step need to be rebuild and tested, and requires some patches which need to be adapted or reworked. Anyway, just build rust on 10+ platforms requires couple of days.

The good news that mrust upstream is working to support 1.74 which should decrease the chain. The bad news: it still quite a challenge.

**Comment by barracuda156** [comment]
@catap This thing is not usable yet? https://github.com/rust-lang/rustc_codegen_gcc

**Comment by catap** [comment]
> @catap This thing is not usable yet? https://github.com/rust-lang/rustc_codegen_gcc

When mrustc supports modern enough rust (1.74 is good), it can be used to try to build native rust for macOS/ppc, but this is quite new road and a lot of things need to be fixed and patched.

**Comment by pmetzger** [comment]
Can this be merged?

**Comment by pmetzger** [comment]
BTW, it seems very important to have a recent Rust in MacPorts; if we can only opportunistically support 20 year old computers, so be it.

**Comment by barracuda156** [comment]
@pmetzger Considering what @MarcusCalhoun-Lopez says, it is perhaps desirable to peg earlier systems instead of breaking Rust for them.

(Intel MacOS is not my personal concern, but generally speaking, it is just wrong to break something which can be working with an absolutely trivial effort like five lines of portfile code.)

**Comment by herbygillot** [comment]
This is becoming more and more unwieldy, but now attempts to peg macOS 10.12 and earlier to Rust 1.78.0 and Cargo 0.79.0.

**Comment by barracuda156** [comment]
> This is becoming more and more unwieldy, but now attempts to peg macOS 10.12 and earlier to Rust 1.78.0 and Cargo 0.79.0.

If it becomes too messy, maybe make a separate port? Maybe even versioned, like we have for gcc. Just a thought, I am no expert on Rust at all.

**Comment by herbygillot** [comment]
> If it becomes too messy, maybe make a separate port? Maybe even versioned, like we have for gcc. Just a thought, I am no expert on Rust at all.

Yes, I think a separate port in the near future is the right way forward, but let's see how this fares for now.

One thing I forgot to mention is that I have not tested this on 10.12 and older, so maybe someone can do that, or at least run `port -d checksum` just to verify that the pulled assets are as expected and checksums look good for that macOS version.

**Comment by MarcusCalhoun-Lopez** [comment]
I completely understand the concerns raised here, and I am sorry it takes weeks for me to set aside the time to get each new version Rust working.
As has been noted, it is would be much easier to support only 10.12 and above, which is what Rust officially supports.
I personally have no need to support older systems.
I have been doing it only because it seems to be of use to others.

Maintaining a separate port for different versions is certainly an understandable strategy.
If the consensus is to move in this direction, I 100% understand.
That being said, I am afraid I have no wish to maintain a separate port for different versions.
If we wish to go in this direction, please remove me as maintainer in the commit.

**Comment by herbygillot** [comment]
> I completely understand the concerns raised here, and I am sorry it takes weeks for me to set aside the time to get each new version Rust working. As has been noted, it is would be much easier to support only 10.12 and above, which is what Rust officially supports. I personally have no need to support older systems. I have been doing it only because it seems to be of use to others.

@MarcusCalhoun-Lopez, first off, I apologize. I do not intend that my exasperation with the situation be taken as disappointment with your efforts.  It's quite the Herculean task you've been undertaking keeping Rust working across such a wide range of platforms and macOS versions, and I must convey proper gratitude for everything you've done.

That said, the Rust community moves quite quickly in terms of requiring very current or close to current versions of Rust every time they release new updates to their software.  Very often, we find that we can't upgrade very many Rust ports because we're stuck on a version of Rust that is just _one_ version behind current.

So while trying to figure out a low friction way to keep up with the Rust project's cadence while still keeping older macOS versions working, a version split or separate port seem like the only ways that I can see to make this happen.

If you have any other ideas, please feel free to suggest.

**Comment by pmetzger** [comment]
I recommend that we simply have the latest rust support only recent MacOS and a separate Rust port that @barracuda156 can maintain on his own only for legacy hardware and OSes.

**Comment by barracuda156** [comment]
> I recommend that we simply have the latest rust support only recent MacOS and a separate Rust port that @barracuda156 can maintain on his own only for legacy hardware and OSes.

As I mentioned above, I have no personal interest in supporting Intel systems, whether new or old. I add some fixes for x86 for my ports or ports which my ports depend on, but no, I am not going to maintain Rust for those.

If it ever happens that Rust will be fixed for PowerPC, then I can consider supporting old x86 as a side-benefit.

Whatever I said above in this discussion is to be understood as merely discussing the issue, where I was tagged. I neither request anyone to support old x86 nor try to convince it is necessary. I only expressed my opinion, thinking that _someone_ may get upset having Rust broken. But I won’t be :)

**Comment by herbygillot** [comment]
@MarcusCalhoun-Lopez, would there be a way for us to automate the generation of the support compilers?

**Comment by pmetzger** [comment]
So how do we move forward from here? I'm thinking we just make 1.80 (the current release) the version in the main port and we let @barracuda156 create one for the machines he cares about.

**Comment by barracuda156** [comment]
@pmetzger @herbygillot Please decide on your own re Rust, it is presently broken on powerpc anyway (completely broken, no version will build), so there are no systems which I care about which are relevant to the issue.

There were some people here supporting Rust for older Intel, as I recall, not sure if they still do, but I am indifferent here.

**Comment by cyckl** [comment]
As much as I love the intention to support older systems and keep them running with modern software, refusing to update Rust because of a lack of PPC support (which isn't a dominant platform anymore) breaks the _entire_ Rust ecosystem on MacPorts.

I have tools that I can't install or build because of the outdated version and I know I'm not the only one. This is the entire toolchain for a very popular language that's broken now.

I have immense respect for that goal, though, and I mean no disrespect to any maintainers by this. @MarcusCalhoun-Lopez, I support only targeting 10.12 and up. You do a lot of work maintaining this port and while I'm new to the MacPorts community, I'd love to get up to speed in the next few months so I could assist with that.

**Comment by barracuda156** [comment]
> refusing to update Rust because of a lack of PPC support

@cyckl How did this myth even originate? No one is refusing to update rust because of PPC support. Moreover, it makes no sense whatsoever, since _any_ rust is broken on powerpc, whether updated or not. It is simply irrelevant.

**Comment by cyckl** [comment]
> @cyckl How did this myth even originate? No one is refusing to update rust because of PPC support. Moreover, it makes no sense whatsoever, since any rust is broken on powerpc, whether updated or not. It is simply irrelevant.

Oh, I must've misinterpreted the thread then. So the hang-up would be losing support for pre 10.12 systems?

**Comment by barracuda156** [comment]
@cyckl I have no idea.

As I said earlier, it is desirable in principle to have a version for older Intel systems (which should be a fairly trivial task, whether via pegging or a separate -legacy port), but it is not my personal concern. It should not be a stopper for updating in any case: I don’t think anyone expects someone else to fix rust, maximum what can be done is a fallback.

**Comment by pmetzger** [comment]
@herbygillot Can we update this PR and merge it?

**Comment by cyckl** [comment]
Perhaps we can use the delay for merge to work on pushing up to 1.80.0 to avoid future issues with builds?

**Comment by cyckl** [comment]
@herbygillot Oh, by the way, thank you for the patch. I finally managed to get it to build locally on my system and Zola built and installed perfectly.

**Comment by pmetzger** [comment]
@cyckl We can always update a second time; it harms nothing.

**Comment by herbygillot** [comment]
Updated this PR to 1.80.0. One big change here is removing `jemalloc`, as I was constantly running into an error about the `jemalloc` crate not being found.  It would be ideal to test this on 10.15 Intel.

**Comment by barracuda156** [comment]
@herbygillot @MarcusCalhoun-Lopez Just for the info, what is the expected status of pre-Catalina x86? Are there plans to have a fallback compatible with those versions?

I do not care about Rust, but we may need to change fallback threshold for some ports if Rust is broken (librsvg, spidermonkey versions, gjs).

**Comment by herbygillot** [comment]
> @herbygillot @MarcusCalhoun-Lopez Just for the info, what is the expected status of pre-Catalina x86? Are there plans to have a fallback compatible with those versions?

According to Rust's platform support page, it's supporting 64-bit x86 on 10.12 and up.
https://doc.rust-lang.org/nightly/rustc/platform-support.html

**Comment by cyckl** [comment]
Alright, I've finally managed to get 10.15 installed and installed Rust, Cargo, and Zola from a clean install and a local Portfile repository. Builds perfectly and runs fine.

Here's some system info

```
cyckl@trashcan ~ % uname -a
Darwin trashcan 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
```

```
cyckl@trashcan ~ % sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15 
```

Here are attached log files for all the builds.

[cargo-1.80.0.log](https://github.com/user-attachments/files/16553866/cargo-1.80.0.log)
[rust-1.80.1.log](https://github.com/user-attachments/files/16553867/rust-1.80.1.log)
[zola-0.19.0.log](https://github.com/user-attachments/files/16553868/zola-0.19.0.log)

**Comment by pmetzger** [comment]
@herbygillot So what's left before you merge? Or can you just do it?

**Comment by herbygillot** [comment]
OK, merged.  @cyckl, thank you very much for testing 10.15 Intel.

**Pull request merged**
