### PR TITLE
py-arpeggio: update to 1.9.2 to fix checksum and permit use of tests

### PR DESCRIPTION
**Pull request by mabraham**
#### Description

Previous checksums did not match the tarball of 1.9.0 on github. Upstream maintainer reports that PyPI tarball didn't have the tests that this port uses until 1.9.1. Previous maintainer of py-arpeggio intended to run the tests, so in order to run tests against a tarball that has them, we
have to update the version. See also https://github.com/textX/Arpeggio/issues/67

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.15 19A583
Xcode 11.1 11A1027 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mabraham** [comment]
Upstream thinks they made no change. Travis looks like there is a cached tarball that matches the checksum, but I don't yet understand the mechanism there to know how to solve it.

**Comment by reneeotten** [comment]
@mabraham thank you for your contribution! I noticed that the PyPI tarballs do not include the tests, so that would be broken with this update. Is there an issue with keep on using the github PG and just increasing the version?

**Comment by mabraham** [comment]
> @mabraham thank you for your contribution! I noticed that the PyPI tarballs do not include the tests, so that would be broken with this update.

PyPI Arpeggio tarballs (e.g. https://pypi.org/project/Arpeggio/#files) have tests since 1.9.1. That's why it's useful to upgrade the version used in macports

> Is there an issue with keep on using the github PG and just increasing the version?

The upstream maintainer recommends the ones that are on PyPI, as the github tarballs are automatically made from tags and contain extra things that he doesn't intend to be in the proper tarball - see https://github.com/textX/Arpeggio/issues/67#issuecomment-546361919

**Comment by reneeotten** [comment]
@mabraham sure, updating to a newer version is almost always a good idea. I was wrong about tests not being included, they are indeed there. However, ```sudo port -dv test py37-arpeggio``` does fail and that should be fixed.

**Comment by mabraham** [comment]
> @mabraham sure, updating to a newer version is almost always a good idea. I was wrong about tests not being included, they are indeed there. However, `sudo port -dv test py37-arpeggio` does fail and that should be fixed. Perhaps it's as easy as clearing `test.target`; I can't test it right now myself...

OK. I can't test it myself until Monday either. But it's likely enough, because I've essentially reverted to the content used by the former maintainer of this port, then made the bump to 1.9.2.

**Comment by reneeotten** [comment]
It is sufficient to leave only ```test.run yes```; the rest can be left to the defaults set by the Python PG. Two tests do fail (but pass outside of MacPorts) with an ```IOError```; it appears that setting the directory to the input files doesn't work correctly, you can likely patch that to also pass within MacPorts. Finally, you can remove the ```else```-block with ```livecheck.type pypi``` as this is the default when using ```pypi``` as ```master_sites```

**Comment by mabraham** [comment]
OK thanks, will try tomorrow!

**Comment by mabraham** [comment]
> It is sufficient to leave only `test.run yes`; the rest can be left to the defaults set by the Python PG.

Done, but e.g. at https://dev.azure.com/macports/macports-ports/_build/results?buildId=4132&view=logs&jobId=dde54236-b8c5-5879-af99-818e7b59912f I don't see any evidence the tests are running and succeeding. I'm pretty new at this, is there somewhere else I should look?

> Two tests do fail (but pass outside of MacPorts) with an `IOError`; it appears that setting the directory to the input files doesn't work correctly, you can likely patch that to also pass within MacPorts.

I'm happy to look into this, but I haven't seen this failure, and haven't produced it with a local run of the Arpeggio tests (ie. outside macports) - where should I look?

> Finally, you can remove the `else`-block with `livecheck.type pypi` as this is the default when using `pypi` as `master_sites`

Done

**Comment by reneeotten** [comment]
thank you for the updates! Indeed, the tests are (currently) not run as part of the CI system. You can run the tests locally by doing ```sudo port -dv test pyXY-arpeggio```. 

As I said earlier, the tests do pass if you run them outside of MacPorts, so you can either disable the two failing tests or try to patch it so that they run from within MacPorts as well. Give it a try to see if you can get the test-suite to pass, but otherwise I'm fine with merging it as-is given that it appears to be something specific with MacPorts. 

One other thing, does this already support/pass the tests on Python 3.8; if so, please add it to ```python.versions```.

**Comment by reneeotten** [comment]
@mabraham did you have time to look at this so that we can merge your PR? We don't need to worry about the two failing tests now, which are MacPorts specific, how about Python 3.8?

**Comment by mabraham** [comment]
Let's do python 3.8 in a subsequent change. Upstream claims 3.4+ support. There's already enough changes here for one commit.

**Comment by reneeotten** [comment]
> Let's do python 3.8 in a subsequent change. Upstream claims 3.4+ support. There's already enough changes here for one commit.

Then I don't see a reason why not to add it at the same time as you make the update to a new version (to which all other changes are related). If it passes the tests, please add it now; otherwise we'll leave it out and add the subport once upstream supports it.

**Comment by mabraham** [comment]
I haven't tested py38-arpeggio locally, as I don't yet know how to get `sudo port -dv test pyXY-arpeggio` to use a local Portfile

**Comment by reneeotten** [comment]
> I haven't tested py38-arpeggio locally, as I don't yet know how to get `sudo port -dv test pyXY-arpeggio` to use a local Portfile

thank you @mabraham ! I just tested it locally and it passes the tests for PY38 as well (the same two IOError failures within the MacPorts, but everything good outside). I'll merge this, thank you for your contribution!

**Comment by mabraham** [comment]
Thanks! I'll look into the test failures next week

**Pull request merged**
