### PR TITLE
kerberos5: update python version to 3.9

### PR DESCRIPTION
**Pull request by ferdy**
###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 11.3.1 20E241
Xcode 12.5 12E262

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [X] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
@ferdy The switch to from python38 to python39 in this PR seems reasonable. Python is only a build dependency, so in what way does this change the installed files? If, as I assume, it does not, then increasing the revision is not warranted.

I don't understand why there are 106 other commits in this PR or know what effect merging this PR with those extra commits would have.

The other comments in this PR appear to be unrelated to it. Presumably they relate to the other commits.

**Comment by ferdy** [comment]
> @ferdy The switch to from python38 to python39 in this PR seems reasonable. Python is only a build dependency, so in what way does this change the installed files? If, as I assume, it does not, then increasing the revision is not warranted.

i see your point, of course you are right.
i have wrongly given for granted you are always supposed to increase the revision. my fault.
 
> I don't understand why there are 106 other commits in this PR or know what effect merging this PR with those extra commits would have.
> 
> The other comments in this PR appear to be unrelated to it. Presumably they relate to the other commits.

actually I do not understand either. surely I created a custerfck messing with git.

right after i opened the pr. i received the message notifying the test failed.
i checked the log and i noticed the it failed to fetch the bzip2 archive, thus i thought it was a temporary error and i pushed again to have the test restarted.

can i just close this pr and open a brand new (i am aware i should amend this, but i do not want to do any further damage).

please let me know,

**Comment by ryandesign** [comment]
> i checked the log and i noticed the it failed to fetch the bzip2 archive, thus i thought it was a temporary error and i pushed again to have the test restarted.

Sorry about that, the archive fetch failures in CI were my fault. They shouldn't happen anymore if your PR is from an up to date master.

> can i just close this pr and open a brand new (i am aware i should amend this, but i do not want to do any further damage).

I think I've rescued the PR with a rebase and force push, and I removed the revision increase. Let's make sure the CI builds pass now and then we can merge it.

**Comment by ferdy** [comment]
sorry for the annoyance and (as always) thank you very much indeed!

**Comment by jmroot** [comment]
CI passed so I went ahead and merged. This also resolves [#63040](https://trac.macports.org/ticket/63040).

**Pull request merged**
