### PR TITLE
alex: Update

### PR DESCRIPTION
**Pull request by essandess**
alex: Update

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kurthindenburg** [comment]
I believe the general idea is to not include white-space changes in the same commit as functional changes.  Also, the revision needs to be changed to 0.

**Comment by herbygillot** [comment]
> I believe the general idea is to not include white-space changes in the same commit as functional changes. Also, the revision needs to be changed to 0.

Changing the revision is not considered a whitespace change.  If you update the version, then you should reset the revision back to 0 in the same commit.

**Comment by essandess** [comment]
Thanks, done.

> I believe the general idea is to not include white-space changes in the same commit as functional changes. Also, the revision needs to be changed to 0.

**Comment by herbygillot** [comment]
Thanks

**Pull request merged**
