### PR TITLE
nano: Update to 4.9.2

### PR DESCRIPTION
**Pull request by saagarjha**
#### Description

I'm running through `port livecheck installed` and trying to update things that have an open maintainer or no maintainer.

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.5 19F53f
Xcode 11.4 11E146 

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] checked your Portfile with `port lint`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mojca** [comment]
While at it, you could align the spaces in other lines to 20 spaces (to match those in checksums) as a separate commit, but that's optional.

**Comment by saagarjha** [comment]
Sure thing.

**Comment by mojca** [comment]
Thank you. Can you please just prefix the last commit message with the port name?

**Comment by saagarjha** [comment]
Done.

**Comment by mojca** [comment]
Thank you very much.

**Pull request merged**
