### PR TITLE
ocaml-*: revbump JaneStreet ports for ocaml-sexplib0 update

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

@pmetzger Could you review this please?

Not that I do this happily, but an alternative is to revbump a lot of OCaml packages: everything JaneStreet, potentially other as well.

Upstream did a weird thing: while `ocaml-sexplib0` 0.17.0 is compatible with OCaml 4.14, all subsequent updates to 0.17.x require OCaml 5.x.
I tried rebuilding `ocaml-base`, `ocaml-ppxlib` and a few other dependents, and it works fine. But there are a lot of dependents, and determining sequentially which need a rebuild will be ridiculously time-consuming. We can just revbump everything that in some way depends indirectly on `ocaml-sexplib0`, but we will need to rebuild everything.

I am fine with just revbump of everything, but not sure it is justified.

Leaving things as they are is not an option though, since nothing builds now, and I cannot update `stanc3`, for example.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Upstream does not appear enthusiastic to address issues, unfortunately, but just in case: https://github.com/janestreet/sexplib0/issues/14

**Comment by pmetzger** [comment]
Why can't we just leave 0.17.0 in place until a few months from now when OCaml 5 is declared stable?

**Comment by barracuda156** [comment]
> Why do we need to revbump everything?

Because nothing works now, every dependent will fail to build with ”makes inconsistent assumptions about…”.
I am away from machine, if you are interested in the logs, I can post those tomorrow.

This applies to ports which depend on sexplib0, others should be not affected.

**Comment by pmetzger** [comment]
I'd like to see the actual error message.

**Comment by barracuda156** [comment]
> I'd like to see the actual error message.

Sure, will post today once back to the machine.

**Comment by barracuda156** [comment]
@pmetzger This is on Sonoma, everything default, I try to update `stanc3`:
```
--->  Building stanc3
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_math_stanc3/stanc3/work/stanc3-2.35.0" && /opt/local/bin/dune build -j 4 --root=/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_math_stanc3/stanc3/work/stanc3-2.35.0 --profile=release --ignore-promoted-rules --no-config --only-packages=stanc --default-target=@install @install 
File "_none_", line 1:
Error: Files /opt/local/lib/ocaml/site-lib/base/base.cmxa
       and /opt/local/lib/ocaml/site-lib/sexplib0/sexplib0.cmxa
       make inconsistent assumptions over interface Sexplib0__Sexp_grammar
Read 410 sample input sentences and 180 error messages.
File "_none_", line 1:
Error: Files /opt/local/lib/ocaml/site-lib/ppxlib/stdppx/stdppx.cmxa
       and /opt/local/lib/ocaml/site-lib/sexplib0/sexplib0.cmxa
       make inconsistent assumptions over interface Sexplib0__Sexp_grammar
Command failed:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_math_stanc3/stanc3/work/stanc3-2.35.0" && /opt/local/bin/dune build -j 4 --root=/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_math_stanc3/stanc3/work/stanc3-2.35.0 --profile=release --ignore-promoted-rules --no-config --only-packages=stanc --default-target=@install @install 
Exit code: 1
Error: Failed to build stanc3: command execution failed
Error: See /opt/local/var/macports/logs/_opt_svacchanda_SonomaPorts_math_stanc3/stanc3/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there
is a bug.
Error: Processing of port stanc3 failed
```

(All the same I was getting also on 10.6 ppc, of course.)

**Comment by pmetzger** [comment]
Okay, so I take it that the interface changed since 1.6. Given that, yes, bump the ports that depend on it. Moving backwards isn't the way to deal with this. It's no different than someone updating any other port whose dependents need to be rebuilt because of a change in interface.

**Comment by barracuda156** [comment]
@pmetzger Okay, will drop the revert and revbump dependents.

**Comment by barracuda156** [comment]
@pmetzger Perhaps this is good to go.

**Comment by barracuda156** [comment]
I can confirm that now building `stanc3` works fine.

**Comment by barracuda156** [comment]
Ah, but another port is broken by that unfortunate change in legacysupport:
```
--->  Building ocaml-core_unix
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_ocaml_ocaml-core_unix/ocaml-core_unix/work/core_unix-0.16.0" && /opt/local/bin/dune build -j 6 --root=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_ocaml_ocaml-core_unix/ocaml-core_unix/work/core_unix-0.16.0 --profile=release --ignore-promoted-rules --no-config --only-packages=core_unix --default-target=@install @install 
getconf: no such configuration parameter `GNU_LIBC_VERSION'
In file included from /opt/local/lib/ocaml/site-lib/jane-street-headers/ocaml_utils.h:6,
                 from filename_unix_stubs.c:5:
filename_unix_stubs.c: In function 'core_unix_realpath':
/opt/local/lib/ocaml/caml/mlvalues.h:290:23: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  290 | #define String_val(x) ((const char *) Bp_val(x))
      |                       ^
filename_unix_stubs.c:32:16: note: in expansion of macro 'String_val'
   32 |   char *path = String_val(v_path);
      |                ^~~~~~~~~~
File "core_unix/src/dune", line 5, characters 29-44:
5 |  (c_names nss_stubs timespec core_unix_stubs core_unix_time_stubs)
                                 ^^^^^^^^^^^^^^^
In file included from core_unix_stubs.c:70:
/opt/local/include/LegacySupport/string.h:24:10: fatal error: _macports_extras/sdkversion.h: No such file or directory
   24 | #include <_macports_extras/sdkversion.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
File "time_stamp_counter/src/dune", line 3, characters 10-34:
3 |  (c_names time_stamp_counter_stubs) (c_library_flags -lMacportsLegacySupport)
              ^^^^^^^^^^^^^^^^^^^^^^^^
In file included from time_stamp_counter_stubs.c:23:
/opt/local/include/LegacySupport/time.h:24:10: fatal error: _macports_extras/sdkversion.h: No such file or directory
   24 | #include <_macports_extras/sdkversion.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

@pmetzger Could you say how to pass include flag to C compiler via Dune?

**Pull request merged**
