### PR TITLE
snappy: Provide shared library only

### PR DESCRIPTION
**Pull request by raimue**
#### Description

The snappy port accidentally only provided a static libsnappy.a instead of libsnappy.dylib as a shared libary. All ports linking with libsnappy need to be rebuilt due to the change in snappy @1.1.7_1.

See: https://trac.macports.org/ticket/55583

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.12.6 16G1408
Xcode 9.2 9C40b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by raimue** [comment]
Thank your for catching the problems. I removed p5-compress-snappy and added qemu to the rev-bumped ports.

Please feel free to add your changes to this PR. Fixing the library versioning is desirable, but I thought we could do without it as we will have to rev-bump dependents any way for this change.

**Comment by pmetzger** [comment]
LGTM.

**Comment by pmetzger** [comment]
I suggest that this be merged soon unless there are objections.

**Comment by pmetzger** [comment]
Merged.

**Pull request merged**
