### PR TITLE
R: add OpenBLAS variant

### PR DESCRIPTION
**Pull request by webbp**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by webbp** [comment]
I did some matrix and data.table benchmarks. (More info available on request.) Matrix ops were typically 1.2 x as fast with OpenBLAS vs accelerate, and 5-6x as fast with OpenBLAS vs default builtin_lapack. data.table ops were typically marginally faster with OpenBLAS than accelerate, and typically 1.1x as fast with OpenBLAS vs default builtin_lapack. I recommend changing the default variant to accelerate or OpenBLAS.

PS: I would prefer OpenBLAS as the default because it is cross-platform and open-source, and because in previous tests I found that using R +accelerate gave inaccurate results for some numerical calculations vs buildin_lapack or OpenBLAS.

PPS: The atlas port won't build for me, so I couldn't test that variant, but I have in the past found that OpenBLAS always outperformed atlas, so I see no reason to file a ticket for that.

PPPS: I also tested anaconda R with intel mkl blas, which was marginally faster than macports R +accelerate, and marginally slower than macports R +OpenBLAS, and I tested cran-r R 3.6.3 .pkg, which uses built in blas and lapack, and it performed very similarly to default macports R.

**Comment by webbp** [comment]
Re: tried existing tests with sudo port test?
sudo port test fails with or without my change

**Comment by kjellpk** [comment]
Old maintainer here, feedback only. New variant looks ok to me.

Thank you for testing/being aware of the numerical inaccuracies in Accelerate. I had left the default as built in because I wanted MacPorts R to be as close to CRAN R as possible. I made that decision 10+ years ago and don't know if it's appropriate today.

It's likely that 'sudo port test' is failing because you do not have all the tools to build the manuals. Can try 'sudo port build' then 'sudo port -v test'. Otherwise check log file.

Hope that helps. Will leave it up to @i0ntempest to proceed.

**Comment by webbp** [comment]
There is one problem with my commit/pull request. I forgot this change:
```
-if {![variant_isset accelerate] && ![variant_isset atlas] && ![variant_isset builtin_lapack]} {
+if {![variant_isset accelerate] && ![variant_isset atlas] && ![variant_isset OpenBLAS] && ![variant_isset builtin_lapack]} {
     default_variants-append +builtin_lapack
```
Please reject this pull request and I'll submit a new one.

**Comment by webbp** [comment]
@kjellpk Re: which default BLAS
I've also encountered an OpenBLAS bug that caused either crashes or numerical inaccuracies (I don't remember which) when running multiple processes that simultaneously used OpenBLAS. It was already fixed and I only had to update OpenBLAS, but default_lapack may still be the safest default.

**Comment by i0ntempest** [comment]
Thanks for the new variant. Tried building on my system; LGTM. And yea, the builtin lapack should be the default.

**Comment by webbp** [comment]
This is my first pull request to macports. Do I need to do anything further?

**Comment by i0ntempest** [comment]
Maybe change your commit message to remove "math/", other than that it's good. We'll need to wait for someone with commit access to merge this

**Comment by i0ntempest** [comment]
Note that I've pushed an update for R 4.0.2, if that got merged first you'll need to change your PR.

**Comment by webbp** [comment]
I have removed "math/" from the commit & pull request titles. R 4.0.2 seems to not yet be in master.

**Comment by i0ntempest** [comment]
It is now, but there's no conflict so you shouldn't need to do anything.
Also, in the future it's better to keep your master branch clean and create new branch for PRs.

**Comment by reneeotten** [comment]
thanks @webbp and @i0ntempest, I'll merge this!

**Pull request merged**
