### PR TITLE
bootstrap.sh: disable clock syncing

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description
Continuing from #8138: allow clock to remain ahead, since forcing it to sync backward seems to be what causes the port tree to reindex and for the `Portfile is from the future` error to occur.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

### CODE REVIEW

**Comment by ryandesign** [comment]
Good idea! Let's try it.

**Comment by chrstphrchvz** [comment]
Didn’t catch this before this was merged:
```
/System/Library/LaunchDaemons/com.apple.timed.plist: Operation not permitted while System Integrity Protection is engaged
```

I would see if the `stop` command might work instead, as long as that’s enough to keep the service from being automatically restarted.

**Comment by chrstphrchvz** [comment]
On 10.11 and 10.12:
```
/System/Library/LaunchDaemons/com.apple.timed.plist: No such file or directory
```

**Comment by chrstphrchvz** [comment]
I haven't found a `launchctl` command that looks like it would do what we want.

Another idea is to reenable clock syncing, but not clone/checkout the repository until after the clock is synced in the bootstrap script; I think that will avoid the port tree reindexing and the `Portfile is from the future` error. It looks like Travis and Azure allow disabling the automatic clone/checkout.

**Pull request merged**
