### PR TITLE
pymol: restore APBS Tools plugin support to default variant - depends…

### PR DESCRIPTION
**Pull request by jwhowarth**
…_run on apbs and pdb2pqr - switch to apbsplugin.py - drop reduntant libGLU dependency

pymol: restore APBS Tools plugin support to default variant
- depends_run on apbs and pdb2pqr
- switch to apbsplugin.py
- drop reduntant libGLU dependency

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.5 19F101
Xcode 11.5 11E608c 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jwhowarth** [comment]
The limited use of X11 by the legacy APBS Tools plugin doesn't appear to involve any threaded code so the requirement of -corefoundation for tcl can be dropped under the default variant of pymol. The apbs_tools.py bundled with pymol 2.4.0 is replaced by the apbsplugin.patch with the copy from [https://github.com/Pymol-Scripts/Pymol-script-repo/blob/master/plugins/apbsplugin.py](url). This replacement APBS Tools plugin, coupled with the recent fix to the pdb2pqr package, allows the previous apbs-psize.patch and pdb2pqr.patch to be dropped. Now the pdb2pqr shell script will be used to invoke pdb2pqr. The redundant libGLU dependency is also dropped.

**Comment by jwhowarth** [comment]
Note that the restored APBS Tools plugin functionality can be tested as follows..

1) sudo port install pymol
2) execute 'pymol'
3) select the 'Get PDB' menu item from the File menu in pymol
4) enter '1hpx' in the PDB ID field of the 'Get PDB File' dialog and click the 'Download' button
5) Select the 'APBS Tools2.1...' menu item from the Legacy Plugins drop down menu in the Plugins menu of pymol
6) click the 'Set grid' button in the 'PyMOL APBS Tools' window that appears
7) click the 'Run APBS' button in the 'PyMOL APBS Tools' window
8) when the Visualization(1) tab is brought forward after the APBS run is complete, click on the 
'Show' button under the Molecular Surfaces subsection.

You will see the electrostatic surfaces rendered now on the top of the 1hpx molecule.

**Comment by jwhowarth** [comment]
Again, the ABPS Tools plugin, which uses pmw to render under tkinter doesn't do any threading unlike the full pymol program. So the stock tcl @8.6.10_0+corefoundation+threads package can be used in this case when pymol is using its QT5 based interface rather then X11.

**Comment by jwhowarth** [comment]
What are these build failures on the buildbots? I am not seeing any problems with local builds using this revised packaging.

**Comment by reneeotten** [comment]
@jwhowarth I do not agree with these changes. We should keep the separation between legacy Tk interaface and the upstream supported Qt5 interface. 

Personally, I have no interest in using `apbs` or `pdb2pqr` and, therefore, have no need for all these extra dependencies nor for the additional requirements regarding `tcl` / `tk` related stuff. Additionally, these things are absolutely not needed to run PyMOL, so please put this in a non-default variant which people can select if they want to use it.

**Pull request closed without merging**
