### PR TITLE
diffoscope: fix dependency type

### PR DESCRIPTION
**Pull request by l2dy**
###### Description
These three dependencies are needed at run time too.

Should I bump the revision?

### CODE REVIEW

**Comment by l2dy** [comment]
Should I bump revision?

**Comment by raimue** [comment]
Yes, a revision bump is necessary when changing dependencies.

I doubt that setuptools is really required at runtime, but the other two changes seem correct.

**Comment by l2dy** [comment]
Without py36-setuptools:
```
Traceback (most recent call last):
  File "/opt/local/bin/diffoscope", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by l2dy** [comment]
I installed the three dependencies one by one, all required at run time.

**Comment by raimue** [comment]
setuptools was indeed required by the launch script it generated. I avoided this dependency by installing a custom launch script to `${prefix}/bin/diffoscope`.

Thank you for the report.

**Comment by l2dy** [comment]
@raimue `--->  patch-bin.diff does not exist in /opt/local/var/macports/distfiles/diffoscope`

**Pull request closed without merging**
