### PR TITLE
rspamd: Update to version 3.2

### PR DESCRIPTION
**Pull request by essandess**
* Fixes: https://github.com/rspamd/rspamd/issues/4131

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.3.1 21E258 x86_64
Xcode 13.3 13E113

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
@essandess can you please check the build failure, which appears is due to a missing dependency? 

```
  CMake Error at cmake/ProcessPackage.cmake:71 (MESSAGE):
    Cannot find library pcre2;pcre2-8 for package PCRE
```

**Comment by essandess** [comment]
> @essandess can you please check the build failure, which appears is due to a missing dependency?
> 
> ```
>   CMake Error at cmake/ProcessPackage.cmake:71 (MESSAGE):
>     Cannot find library pcre2;pcre2-8 for package PCRE
> ```

I don’t understand the CI issue. I have a successful local build that’s running.

I also have `libgcc-devel` installed because of https://trac.macports.org/ticket/64907, but hit this error with a trace build:

`sudo port -vst destroot rspamd`
> ```
> :error:configure Registry error: libgcc not registered as installed & active.
> ```

**Comment by reneeotten** [comment]
> > @essandess can you please check the build failure, which appears is due to a missing dependency?
> > ```
> >   CMake Error at cmake/ProcessPackage.cmake:71 (MESSAGE):
> >     Cannot find library pcre2;pcre2-8 for package PCRE
> > ```
> 
> I don’t understand the CI issue. I have a successful local build that’s running.

I'd guess you probably have `pcre2` installed locally and didn't build in trace-mode.

**Comment by essandess** [comment]
> I'd guess you probably have `pcre2` installed locally and didn't build in trace-mode.

I don't see that `pcre2` has anything to do with this, as it's already a satisfied dependency and always has been:
```bash
port rdeps rspamd | grep pcre2
          pcre2
```

I believe that these specific CI failures are issues with the CI, not an issue with this PR.

**Comment by essandess** [comment]
> <s>I believe that these specific CI failures are issues with the CI, not an issue with this PR.</s>

Revisiting the Portfile code, I now see that my version of macOS no longer has a native library `/usr/lib/libpcre.dylib`, as used to be required. My build must be finding the MacPorts library
```
port provides /opt/local/lib/libpcre.dylib
/opt/local/lib/libpcre.dylib is provided by: pcre
```

This used to break the binary, but now it's apparently working. I'll investigate whether `pcre` or `pcre2` is necessary.

**Comment by essandess** [comment]
@reneeotten Thank you for highlighting the thing to look for.

I believe the latest push has the right code:
```
otool -L `which rspamd` | grep pcre
        /opt/local/lib/libpcre2-8.0.dylib (compatibility version 11.0.0, current version 11.4.0)
```

**Comment by essandess** [comment]
I confirm that `sudo port -vst destroot rspamd` works.

**Pull request merged**
