### PR TITLE
tesseract: require C++11, fix mtree violation, fix library name

### PR DESCRIPTION
**Pull request by dliessi**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.11.6 15G22010
Xcode 8.2.1 8C1002

and

macOS 10.6.8 10K549
Xcode 3.2.6 DevToolsSupport-1806.0 10M2518

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. @markemer ?

**Comment by markemer** [comment]
Awesome. Sign off for sure. This probably closes a ticket as well. I’m on my phone so I can’t look it up now.

**Comment by dliessi** [comment]
> This probably closes a ticket as well.

That is https://trac.macports.org/ticket/56059.
I wrote it in the commit message, so it should close automatically when merged.

**Comment by markemer** [comment]
Cool. I couldn’t expand on my phone. The github mobile experience needs some work.

**Comment by pmetzger** [comment]
Merged. Thanks, @dliessi!

**Pull request merged**
