### PR TITLE
libatomic_ops: update to 7.8.2

### PR DESCRIPTION
**Pull request by ivmai**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ivmai** [comment]
Hello @herbygillot, could you please help me with the build failures?
Thank you

**Comment by reneeotten** [comment]
@ivmai somewhere in the configure or Makefile it appears to be using "find" with an invalid flag "-n". So you will have to figure out where that is and patch that so that it uses a valid flag.

**Comment by ivmai** [comment]
I am sure there is no difference in makefiles of libatomic_ops since previous release (except for version numbers).
But, of course, I could patch the makefile as requested. Could you please point me to some  other package which was patched for the same reason?

**Comment by reneeotten** [comment]
that might actually be a red herring. The CI tells you that the checksums are not correct if you look into the logs.

**Pull request merged**
