### PR TITLE
OpenBLAS: avoid double RPATH on macOS 13 as well

### PR DESCRIPTION
**Pull request by catap**
#### Description

The new linker in Xcode 15 is buggy, causing build failures for many (but not all) ports that link to OpenBLAS. OpenBLAS detects this and includes `-Wl,-ld_classic` in the generated cmake, For compatibility reasons, buildbot uses Xcode 14, and OpenBLAS built on Xcode 14 is broken. on machines with Xcode 14. Here we have only one configuration which has two possible Xcode: MacOS 13. Prevent precompiled binaries on this system.

###### Type(s)

- [x] bugfix

###### Tested on

macOS 13.6.1 22G313 arm64
Xcode 15.0.1 15A507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by catap** [comment]
@szhorvat can you test this one on your machine?

**Comment by szhorvat** [comment]
Thanks for the very quick reaction! Using the `+native` variant does fix the issue for me, as do other means of forcing local compilation. But I also think this change shouldn't be merged, as discussed in the other issue.

**Comment by catap** [comment]
@cjones051073 here it is :)

**Comment by szhorvat** [comment]
OK, then it makes sense. I didn't realize you disabled binaries.

**Comment by cjones051073** [comment]
Is this really only an issue on macOS 13 ? Is it not a problem also on macOS14 with Xcode 15.0 ?

I would I think prefer if you removed the darwin check, and just applied it if Xcode >= 15.0 *and* Xcode < 15.1.

**Comment by cjones051073** [comment]
You also need to bump the revision for the update to take effect...

**Comment by catap** [comment]
Indeed.

**Comment by catap** [comment]
> Is this really only an issue on macOS 13 ? Is it not a problem also on macOS14 with Xcode 15.0 ?

Nope, OpenBLAS detects when it is build under Xcode 15 and propagates `-Wl,-ld_classic` into resulted `.cmake` files.

This was the root cause to move to cmake-based build: better cmake integration with a lot of ports.

**Comment by szhorvat** [comment]
> _and_ Xcode < 15.1.

The problem is still present with Xcode 15.1. Why are you asking to exclude itÞ

**Comment by catap** [comment]
> > _and_ Xcode < 15.1.
> 
> The problem is still present with Xcode 15.1. Why are you asking to exclude itÞ

PR doesn't exclude Xcode 15.1 BTW

**Comment by ryandesign** [comment]
Preventing the use of binaries surely isn't the right solution. A user would also encounter the problem if they installed OpenBLAS with Xcode 14, then upgraded to Xcode 15 and tried to build ports that use OpenBLAS, right? The problem is that software that uses OpenBLAS needs to request the classic linker, and isn't doing so on its own? So the solution would be to fix the other ports to request the classic linker when that's required?

**Comment by catap** [comment]
> A user would also encounter the problem if they installed OpenBLAS with Xcode 14, then upgraded to Xcode 15 and tried to build ports that use OpenBLAS, right? The problem is that software that uses OpenBLAS needs to request the classic linker, and isn't doing so on its own? So the solution would be to fix the other ports to request the classic linker when that's required?

Problem is cmake-integration. It caches flags which was used to build OpenBLAS and when OpenBLAS detects that it's build on system with Xcode 15, it adds classic linker, which is included into generated `.cmake` file. Cmake runs its test without specified flags, but with flags which is included into `.cmake` file.

So, here we are: if OpenBLAS is build under xcode 15 it produces `.cmake` files with classic linker and can be used at cmake projects on this system.

**Comment by kencu** [comment]
you could always fix the openblas build to not have redundant rpath flags instead.

we know the cause.

the linker is not buggy to error on duplicate rpath flags, just stricter.

**Comment by catap** [comment]
> you could always fix the openblas build to not have redundant rpath flags instead.

let try this one, it seems easy to check.

**Comment by kencu** [comment]
I really hope that works. Best of luck with it (I think the extra rpath comes from the compilers PG), and let me know if there is anything I might do to help out.

Chris was hoping the new linker update in Xcode 15.1 might allow duplicate rpaths again, but I'm hearing around MacPorts that no, it does not. I admittedly didn't check that for myself to validate it.

**Comment by catap** [comment]
@kencu I've just checked and cmake complaint for duplicated rpath.

As soon as buildbot builds it, I may test it locally.

Can I ask you to merge it?

**Comment by kencu** [comment]
OK. 

Instead of stripping the extra rpath flag out in every port that shows this issue:

@cjones051073 -- how about we make the compilers PortGroup stop adding the extra rpath flag by default to all builds now? Would that not be logical?

Yes, a while back it was added for a reason. But things change, and it's just wrong now.

You can have have it toggled on with some control option specifically for ports that require it instead, or otherwise sort out a proper way to add it or fix the builds of ports that seemed to need it.

**Comment by catap** [comment]
Ken, let use OpenBLAS as guene pig to proof it.

Thus, we may stop add it since macOS 22, because it works qutie well before xcode 15 :)

**Comment by cjones051073** [comment]
> OK.
> 
> Instead of stripping the extra rpath flag out in every port that shows this issue:
> 
> @cjones051073 -- how about we make the compilers PortGroup stop adding the extra rpath flag by default to all builds now? Would that not be logical?
> 
> Yes, a while back it was added for a reason. But things change, and it's just wrong now.
> 
> You can have have it toggled on with some control option specifically for ports that require it instead, or otherwise sort out a proper way to add it or fix the builds of ports that seemed to need it.

Indeed it might be time to consider that.

Support for adding the rpath should be kept but made an opt in (or opt out, not sure which is best) option.

I am afraid I will have no time to work on this myself for the foreseeable future, for various reasons. I am not though the maintainer of the compilers PG, so anyone who feels this change should be made is free to submit  a PR doing this themselves...

**Comment by catap** [comment]
> I am afraid I will have no time to work on this myself for the foreseeable future, for various reasons. I am not though the maintainer of the compilers PG, so anyone who feels this change should be made is free to submit a PR doing this themselves...

which PR should revbump ~180 heavy ports...

**Comment by kencu** [comment]
well…. the other option is to either manually strip out the extra rpath in each affected port forever —- yuk, or force them all to use the classic linker forever —- also yuk.

am I missing a better choice?

**Comment by kencu** [comment]
imo, we make the change in the portgroup, revbump openblas to fix it, make 100% certain that works right, and then wait to fix the others one by one, stripping out the forcing of the classic linker and the removal of the extra rpaths as they are updated, etc.

what do you think?

**Comment by catap** [comment]
Ken, I'm ready to update this PR to that test.

Anyway, I really thin that we should keep double RPATH for system before macOS 13. It works. Let not touch it.

**Comment by cjones051073** [comment]
> imo, we make the change in the portgroup, revbump openblas to fix it, make 100% certain that works right, and then wait to fix the others one by one, stripping out the forcing of the classic linker and the removal of the extra rpaths as they are updated, etc.
> 
> what do you think?

I agree. There is no need to rev bump every port using the PG, when likely the vast majority are not affected.

make the change to add an option to allow ports to control if the rpath is added, I would go with keeping the default on for now, and test ir via the OpenBLAS port.

i also, if it wheee me, NOT make it OS version dependent. For me thats an unnecessary complication. If its fine on newer Oses it should be fine on all, so just do the same everywhere to avoid unnecessary confusion.

**Comment by catap** [comment]
@kencu, @cjones051073 here it is. Changes quite clean BTW.

**Comment by kencu** [comment]
well done, thanks

**Pull request merged**
