### PR TITLE
mdds: update to 2.0.3

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Simple update, nothing more.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.5.8
Xcode 3.1.4

macOS 10A190
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by Tatsh** [comment]
Does this work with libreoffice? Including the configuration phase?

**Comment by barracuda156** [comment]
> Does this work with libreoffice? Including the configuration phase?

@Tatsh I have built `libetonyek` with it, which is related to libreoffice. I am not sure libreoffice builds for PPC though.
If you could check on Intel, that would be helpful.

**Comment by Tatsh** [comment]
Tested on my system (Intel) and it works fine.

**Comment by barracuda156** [comment]
> Tested on my system (Intel) and it works fine.

@Tatsh Awesome.

**Pull request merged**
