### PR TITLE
devel/meson: trivial update to 0.57.1

### PR DESCRIPTION
**Pull request by adfernandes**

### CODE REVIEW

**Comment by kencu** [comment]
some kind of an issue with your PR here.

here's the (last 250 commits) of the changes <https://github.com/mesonbuild/meson/compare/0.56.2...0.57.1>

**Comment by adfernandes** [comment]
> some kind of an issue with your PR here.
> 
> here's the (last 250 commits) of the changes [mesonbuild/meson@0.56.2...0.57.1](https://github.com/mesonbuild/meson/compare/0.56.2...0.57.1)

So @kencu, there's something weird going on...

On my local repo, I made sure to `git fetch --all --prune` **before** branching. I even checked my shell history to make sure I ran those commands.

Then, surprisingly, github told me I had a merge conflict in the version (`github.setup` and `revision`). Okay...

But I look at my commits, and it seems that my local master was at `0.56.2 revision 0`, while upstream was`0.56.2 revision 2`.

And my local history seems to match upstream.

Oh well. Perhaps I did something... odd... that my brain just isn't seeing. It _has_ been a very long week.

Maybe I'll just close this PR and redo it.

(Hmm. What am I not seeing? This is going to bug me.)

**Comment by adfernandes** [comment]
OMG. I did a `git pull origin master` rather than `upstream` on my personal fork.

Definitely need more sleep. Sorry for the spam!

Thanks for catching this, @kencu!

**Comment by adfernandes** [comment]
(fixed in #10081)

**Pull request closed without merging**
