### PR TITLE
emacs-mac-app-devel: update to 20220113

### PR DESCRIPTION
**Pull request by amake**
#### Description

I am the maintainer of this port, but I can't get this to work so I am hoping for help from anyone knowledgeable.

Upstream has merged in emacs-28.0.91, which means that in principle we should be able to use nativecomp in this port.

However there are problems with paths: `${prefix}/lib/emacs/28.0.91/native-lisp` needs to go somewhere in the app bundle in order to be located, so I have moved it to `EmacsMac.app/Contents/native-lisp` (indicated by the error message shown when the dir is *not* present there).

However doing so reveals other missing paths; the errors now shown are:

```
% /Applications/MacPorts/EmacsMac.app/Contents/MacOS/Emacs -Q
Warning: arch-dependent data dir '/opt/local/libexec/emacs/28.0.91/x86_64-apple-darwin21.2.0/': No such file or directory
Warning: arch-independent data dir '/opt/local/share/emacs/28.0.91/etc/': No such file or directory
Warning: Lisp directory '/opt/local/share/emacs/28.0.91/lisp': No such file or directory
Error: /opt/local/share/emacs/28.0.91/etc/charsets: No such file or directory
Emacs will not function correctly without the character map files.
Please check your installation!
```

Note: This port (temporarily) conflicts with the emacs{,-devel} port because I commented out some deletions for debugging purposes.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 12.1 21C52 x86_64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by amake** [comment]
Any idea, @drkp @catap ?

**Comment by pmetzger** [comment]
See also https://github.com/macports/macports-ports/pull/13628 which this presumably supersedes.

**Comment by amake** [comment]
> See also https://github.com/macports/macports-ports/pull/13628 which this presumably supersedes.

No, that's "vanilla" Emacs and the NS port; this is the Mitsuharu Yamamoto "Mac" port.

**Comment by shuxiao9058** [comment]
the same issue after emacs startup

```
Warning: arch-dependent data dir '/opt/local/libexec/emacs/28.0.91/aarch64-apple-darwin21.2.0/': No such file or directory
```

**Comment by amake** [comment]
I believe I have this all figured out now.

There is now a "blessed" way of creating a "self-contained" app bundle. However it seems that `DESTDIR` is not implemented correctly when doing so; I had to patch several spots to fix this:

- https://github.com/amake/emacs-mac/commit/a4725daa5b93f8a50bd54d3c3dc64122fef8c838
- https://github.com/amake/emacs-mac/commit/1f2cd61f6472ee4b37673899a93160dcae95eac0

I also discovered that the way we were renaming the app bundle from Emacs.app to EmacsMac.app would leave references to Emacs.app compiled into various places. I made a patch to change to EmacsMac.app from configure time instead:

- https://github.com/amake/emacs-mac/commit/7596a8284366fcd34329e899dce463b51550d9b8

**Pull request merged**
