### PR TITLE
libhangul & nabi: update to current versions

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

`libhangul` updated to 2021.12.31. Added a patch suggested by upstream: https://github.com/libhangul/libhangul/issues/63#issuecomment-1218473474
`nabi` updated to 1.0.0.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
So `libhangul` passes checks, `nabi` fails on:
```
handler.c:142:14: error: implicit declaration of function 'nabi_ic_lookup_keysym' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
keysym = nabi_ic_lookup_keysym(ic, kevent);
              ^
```

Wonder where `-Werror` comes from though. Source code seems not to have it, at least explicitly.

**Comment by barracuda156** [comment]
@mascguy @herbygillot Is the maintainer of this port still with us? It has not been updated forever, and the maintainer is not tagged too.

**Comment by mascguy** [comment]
Since the maintainer didn't provide a GitHub handle in the portfile, you'll need to reach out directly via e-mail.

**Comment by barracuda156** [comment]
> Since the maintainer didn't provide a GitHub handle in the portfile, you'll need to reach out directly via e-mail.

Do we really need an approval here though? Maintainer didn’t bother updating these ports for years. Also, nothing controversial here. Checks pass, both Intel and PPC build.

**Comment by mascguy** [comment]
> Do we really need an approval here though? Maintainer didn’t bother updating these ports for years. Also, nothing controversial here. Checks pass, both Intel and PPC build.

While it's possible they are no longer an active contributor, you should still reach out as a courtesy.

**Comment by barracuda156** [comment]
> While it's possible they are no longer an active contributor, you should still reach out as a courtesy.

Okay, sent an e-mail now, and:
nabi

**Comment by mascguy** [comment]
Since the e-mail address is no longer valid, you don't need to worry about maintainer approval.

Meanwhile, I'll create an abandonment ticket.

**Comment by mascguy** [comment]
Not to beat a dead horse, but please please run `port lint --nitpick` before pushing:

```
port lint libhangul:
Warning: Line 14 contains tab but modeline says tabs should be expanded
Warning: Line 24 contains tab but modeline says tabs should be expanded
```

We want to catch these issues before merging.

**Comment by mascguy** [comment]
Another example:

```
port lint nabi: Warning: no license set
```

**Comment by barracuda156** [comment]
@mascguy Will be fixed now, gimme a min.

**Comment by mascguy** [comment]
Everything looks good now. But I'd like you to change `depends_build`, `depends_lib`, `patchfiles`, etc, to their `-append` variations. (Per the comments in your other PR.)

**Comment by barracuda156** [comment]
> Everything looks good now. But I'd like you to change `depends_build`, `depends_lib`, `patchfiles`, etc, to their `-append` variations. (Per the comments in your other PR.)

@mascguy Done, thank you!

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
Ugh, I didn't notice that your commits weren't squashed. Oh well...

**Comment by mascguy** [comment]
Please be sure to squash down to one commit per port. Otherwise our only choice is to completely squash down to one giant commit across multiple ports, or leave them as-is.

**Comment by barracuda156** [comment]
> Please be sure to squash down to one commit per port. Otherwise our only choice is to completely squash down to one giant commit across multiple ports, or leave them as-is.

Just was writing a question on this. Should I rather make separate PRs unless absolutely required to keep updates together for checks to pass? It become a mess to squash when there are more that one port in a PR.

**Comment by mascguy** [comment]
> Just was writing a question on this. Should I rather make separate PRs unless absolutely required to keep updates together for checks to pass? It become a mess to squash when there are more that one port in a PR.

If it's easier to do separate PRs, then sure, let's handle it that way. (Along with stating that PR A requires B to be merged first, etc.)

**Comment by barracuda156** [comment]
> > Just was writing a question on this. Should I rather make separate PRs unless absolutely required to keep updates together for checks to pass? It become a mess to squash when there are more that one port in a PR.
> 
> If it's easier to do separate PRs, then sure, let's handle it that way. (Along with stating that PR A requires B to be merged first, etc.)

Okay, great. That is apparently the case with `folly` & friends. Building `fbthrift` perhaps needs merging `folly`, `fizz` and `wangle` first.

**Comment by mascguy** [comment]
> > If it's easier to do separate PRs, then sure, let's handle it that way. (Along with stating that PR A requires B to be merged first, etc.)
> 
> Okay, great. That is apparently the case with `folly` & friends. Building `fbthrift` perhaps needs merging `folly`, `fizz` and `wangle` first.

Yep, it becomes a bit painful when there are multiple ports, each dependent on the next.

For cases like this PR - as well as those others - it's acceptable to squash everything down to a single commit. Just use a message like `libhangul/nabi: update to current versions`. Or for the other ports you mentioned, those are all from Facebook. So you can use a message like `fb ports: fix for PPC`, or something like that.

**Comment by barracuda156** [comment]
> > > If it's easier to do separate PRs, then sure, let's handle it that way. (Along with stating that PR A requires B to be merged first, etc.)
> > 
> > 
> > Okay, great. That is apparently the case with `folly` & friends. Building `fbthrift` perhaps needs merging `folly`, `fizz` and `wangle` first.
> 
> Yep, it becomes a bit painful when there are multiple ports, each dependent on the next.
> 
> For cases like this PR - as well as those others - it's acceptable to squash everything down to a single commit. Just use a message like `libhangul/nabi: update to current versions`. Or for the other ports you mentioned, those are all from Facebook. So you can use a message like `fb ports: fix for PPC`, or something like that.

Got it, sure.

P. S. If it is acceptable, I would rather keep separate PRs for Facebook ports though, since those are complicated, and it is handy to be able to change or drop specific fixes until everything works nicely.

**Comment by mascguy** [comment]
> If it is acceptable, I would rather keep separate PRs for Facebook ports though, since those are complicated, and it is handy to be able to change or drop specific fixes until everything works nicely.

Works for me!

**Pull request merged**
