### PR TITLE
meson: update to 0.64.1 on Tiger

### PR DESCRIPTION
**Pull request by evanmiller**
#### Description

`glib2` now requires meson 0.60 or later, so it's time to update Tiger's meson again.

Tested building:

* glib2
* gobject-introspection
* gtk3

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.4.11
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Did you face any specific issues with the latest version of meson (currently 1.1.0)?

**Comment by evanmiller** [comment]
> Did you face any specific issues with the latest version of meson (currently 1.1.0)?

I didn't try it; I just wanted to satisfy the `glib2` and minimize the amount of patches I'd need to update.

**Comment by mascguy** [comment]
We might want to consider using an older version of Python for Meson and Ninja on 10.5 and prior, as Python 11 requires a much more extensive toolchain to build. (Including `gcc10-bootstrap`, `clang-7.0`, etc.) And that's incredibly awful to deal with, when you have to build all of those newer toolchain components from source. Personally I'm limping along with just MacPorts' `clang-3.4`, as that still is enough for a basic stack.

But if we pin these at Python 3.10 [for 10.5 and prior], that eliminates the extensive toolchain requirements.

Thoughts?

**Comment by eli-schwartz** [comment]
From meson's end that should be fine -- we scrupulously keep support for all versions of python that aren't actually EOL.

Ninja doesn't require python at all -- it can build with either python configure.py or cmake -- the python option I'm pretty sure still supports python 2.

**Pull request merged**
