### PR TITLE
cmake: Use $cmake.install_prefix for CMAKE_INSTALL_NAME_DIR, CMAKE_INSTALL_RPATH, and CMAKE_SYSTEM_PREFIX_PATH

### PR DESCRIPTION
**Pull request by jeremyhu**
Otherwise, the dylib id will be incorrect if the port changes cmake.install_prefix

### CODE REVIEW

**Comment by mojca** [comment]
This is useful for parallel installation of multiple versions for example. There is at least ROOT6 and Geant4 that do this, but I'm sure there are more.

I have a question though. I Geant4 I currently use
```tcl
configure.args-delete -DCMAKE_INSTALL_NAME_DIR=${prefix}/lib \
                      -DCMAKE_INSTALL_RPATH=${prefix}/lib
configure.args-append -DGEANT4_INSTALL_DATA=OFF \
                      -DCMAKE_INSTALL_BINDIR=${prefix}/libexec/Geant4/Geant${geant.version_simple} \
                      -DCMAKE_INSTALL_DATAROOTDIR=${prefix}/share/Geant4 \
                      -DCMAKE_INSTALL_INCLUDEDIR=${prefix}/include/Geant4/Geant${geant.version_simple} \
                      -DCMAKE_INSTALL_LIBDIR=${prefix}/lib/Geant4/Geant${geant.version_simple} \
                      -DCMAKE_INSTALL_NAME_DIR=${prefix}/lib/Geant4/Geant${geant.version_simple} \
                      -DCMAKE_INSTALL_RPATH=${prefix}/lib/Geant4/Geant${geant.version_simple}
```

I didn't test it yet, but I assume the port will stop working until I adjust it for the new syntax. I wasn't even aware that we had a setting for `cmake.install_prefix`. If it is not yet, it should be documented somewhere (I assume I should then be able to get rid of `configure.args-delete`). It might make sense to check whether any other port messes up with those variables to make sure that the change doesn't break those ports.

**Comment by mkae** [comment]
@mojca, could you test `Geant4` with @RJVB's PR #26 in place?

**Comment by TheStormN** [comment]
@mojca @RJVB So should this PR be closed?

**Comment by mojca** [comment]
I don't know of a good reason for closing this PR, even though "mea culpa" for forgetting about this and for forgetting to test it properly. When I mentioned that one of my ports would break, I didn't really mean that the port would permanently be broken, only that it might need some adjustments to accommodate the changes.

**Comment by gaming-hacker** [comment]
so is this merged or not?

**Comment by pmetzger** [comment]
This is our oldest outstanding PR. Can it be either merged or closed?

**Comment by pmetzger** [comment]
@mojca Can we merge, or should we close this?

**Comment by pmetzger** [comment]
@mojca Thought as another month had passed I'd ping again...

**Comment by neverpanic** [comment]
Let's see who will shout.

**Comment by pmetzger** [comment]
@jeremyhu @mojca I think we're going to merge this if no one shouts. @neverpanic seems to think it would be reasonable to do so.

**Comment by mojca** [comment]
I claim that you are insane for waiting for my feedback for so long :) :) :)

I actually tested some of my ports a while ago. Some files actually go to a different place if I use this patch, but I'm not even sure which path is better and I need to revbump those ports anyway for other reasons. This is perfectly fine to merge.

**Comment by pmetzger** [comment]
Waiting for feedback seems politest if you're not entirely sure of what you're doing. :)

**Pull request merged**
