### PR TITLE
chrony: update to 4.1

### PR DESCRIPTION
**Pull request by cave-canem**
chrony 4.1

###### Type(s)

- [ ] enhancement

###### Tested on

macOS 10.9.5 13F1911 x86_64
Xcode 6.2 6C131e
mp-clang-devel (clang version 13.0.0)

###### Verification 
Have you

- [x] checked your Portfile with `port lint`?

- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by reneeotten — CHANGES_REQUESTED** [review]
thank you for the contribution @cave-canem ! The change itself looks good to me, but we'll wait and see what the maintainer thinks. 

In the meantime, please make sure that your commit message follows our [guidelines](https://trac.macports.org/wiki/CommitMessages). This is part of the PR checklist - you removed it and indeed didn't follow it ;) The commit message should be `portname: short description`, so in this case `chrony: update to 4.1`.

**Comment by ryandesign** [comment]
@lbschenkel You left a thumbs-up on Renee's comment... does that mean you approve the changes in this PR? If so, we can use the "Squash and merge" button to fix the commit message.

**Comment by lbschenkel** [comment]
All right. I was hoping that the submitter would fix the commit message (as a learning exercise), but I ended up fixing myself.

**Comment by lbschenkel** [comment]
But thanks for the submission, @cave-canem.

**Pull request merged**
