### PR TITLE
pnpm: update to 7.8.0

### PR DESCRIPTION
**Pull request by MarcelBochtler**
#### Description

See: https://github.com/pnpm/pnpm/releases/tag/v7.8.0

###### Tested on

macOS 12.4 21F79 arm64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by sainnhe** [comment]
v7.7.0 has been released, maybe we should bump it to v7.7.0?

**Comment by MarcelBochtler** [comment]
> v7.7.0 has been released, maybe we should bump it to v7.7.0?

7.7.0 ist at the moment labeled as pre-release. Therefore, I'd stay on 7.6.0 for now.

**Comment by MarcelBochtler** [comment]
Updated to 7.8.0.

**Comment by MarcelBochtler** [comment]
@sainnhe can this be merged?

**Comment by sainnhe** [comment]
> @sainnhe can this be merged?

IMO, yes. But I'm not a member of macports organization, so I have no permission to merge this PR.

**Comment by kencu** [comment]
thanks!

**Pull request merged**
