### PR TITLE
pandoc: Add arm64 support

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 13.1 22C65 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by kencu** [comment]
our old favourite linker error comes back to haunt us yet again :>

```
gziIconv_iconvEncoding5_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding13_info , _base_GHCziIOziEncodingziIconv_iconvEncoding14_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding10_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding6_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding_info , _hs_iconv , _base_GHCziIOziEncodingziIconv_iconvEncoding16_info , _base_GHCziIOziEncodingziIconv_iconvEncoding1_info , _base_GHCziIOziEncodingziIconv_iconvEncoding9_info , _base_GHCziIOziEncodingziIconv_iconvEncoding12_info , _hs_iconv_close , _base_GHCziIOziEncodingziIconv_iconvEncoding8_info , _base_GHCziIOziEncodingziIconv_iconvEncoding1_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding11_bytes , _base_GHCziIOziEncodingziIconv_iconvEncoding12_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding10_info , _base_GHCziIOziEncodingziIconv_iconvEncoding_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding4_info , _base_GHCziIOziEncodingziIconv_iconvEncoding7_bytes , _base_GHCziIOziEncodingziIconv_iconvEncoding16_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding2_closure , _hs_iconv_open , _base_GHCziIOziEncodingziIconv_iconvEncoding15_bytes , _base_GHCziIOziEncodingziIconv_iconvEncoding2_info , _base_GHCziIOziEncodingziIconv_iconvEncoding9_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding4_closure )
  "_iconv_close", referenced from:
      _hs_iconv_close in libHSbase-4.17.0.0.a(iconv.o)
     (maybe you meant: _hs_iconv_close)
  "_iconv_open", referenced from:
      _hs_iconv_open in libHSbase-4.17.0.0.a(iconv.o)
     (maybe you meant: _hs_iconv_open)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ghc: `clang' failed in phase `Linker'. (Exit code: 1)
Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_alex/alex/work/alex-3.2.7.1" && /opt/local/bin/cabal-prebuilt --config-file=/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_alex/alex/work/.home/.cabal/config build alex -j10 --builddir=/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_alex/alex/work/dist --prefix=/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_alex/alex/work/destroot/opt/local --enable-relocatable 
Exit code: 1
```

**Comment by kencu** [comment]
during the link, I see this:
```
ld: warning: directory not found for option '-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib'
```

and sure enough, there is no MacOSX.sdk installed on Ventura. There are instead two SDKS:
```
drwxr-xr-x  7 root  wheel  224 19 Nov  2021 MacOSX12.1.sdk
drwxr-xr-x  3 root  wheel   96 25 Dec 19:03 MacOSX12.3.sdk
```

and manually creating a link:
```
sudo ln -s MacOSX12.1.sdk MacOSX.sdk 
```
allows the link to succeed. Now you might think you would manually create the link from the newer SDK, which I did at first, but it turns out the newer SDK is incomplete:

```
% ls MacOSX12.3.sdk
System
```

now that the symlink MacOSX.sdk -> MacOSX12.1.sdk has been created, things are moving along

**Comment by essandess** [comment]
Only on `x86_64`. I do not have access now to an `arm64` box now but enough experience to have the confidence to expect that it will build fine on both platforms.

**Comment by judaew** [comment]
Thank you for the good and valuable contribution 🌟

The macos-12 CI check failed due to ghc. If I amn't mistaken, the problem with the ghc building was also in the past updates. Someone needs to fix ghc for macOS 12...

The other check is successful. So I think PR's ready to merge.

**Comment by essandess** [comment]
> The macos-12 CI check failed due to ghc. If I'm not mistaken, the problem with the ghc building was also in the past updates. Someone needs to fix ghc for macOS 12...

That's a CI issue, not a `ghc` issue. `ghc` builds and works fine on macOS 12: https://ports.macports.org/port/pandoc/details/

**Comment by judaew** [comment]
Then everything is fine.

**Pull request merged**
