### PR TITLE
jupyter_core_select: Add new port to select default version of Jupyter

### PR DESCRIPTION
**Pull request by lpsinger**
Based on `ipython_select`.

### CODE REVIEW

**Comment by stromnov** [comment]
AFAIK, selecting jupyter is quite useless without the complementary selectors for the other jupyter executables.

`jupyter` executable is a simple process spawner. Running `jupyter cmd` just translates to `jupyter-cmd`. So for executing canonical `jupyter notebook` you must provide not only selector for `py-jupyter`, but also for `py-notebook` (and do the same for every other executable jupyter package).

**Comment by lpsinger** [comment]
> So for executing canonical jupyter notebook you must provide not only selector for py-jupyter, but also for py-notebook (and do the same for every other executable jupyter package).

That wouldn't be great for users because they would have to run lots of `port select` commands. Is it possible to have a single select group that covers all jupyter subcommands?

**Comment by raimue** [comment]
Maybe jupyter could be replaced with a wrapper script or be patched, such that it will execute the corresponding binaries with the `-X.Y` suffix.

**Comment by stromnov** [comment]
Yes, for example it can be done via substitution of python interpreter path (`${prefix}/Library/Frameworks/Python.framework/Versions/${version}/bin/`) in the beginning of PATH environment variable during `jupyter` execution.

Another option: mark `pyXY-jupyter` packages as conflicting.

**Comment by pmetzger** [comment]
@stromnov @lpsinger This has been sitting in the queue since July. Any thoughts on how to proceed? Should we perhaps close this for now?

**Comment by pmetzger** [comment]
Okay, having heard nothing else for about a month, I'm closing this for now. It can be re-opened at will if anyone wants to proceed with this.

**Pull request closed without merging**
