### PR TITLE
fd: update to 8.1.1

### PR DESCRIPTION
**Pull request by herbygillot**
- remove disable-jemalloc patch as that is currently in upstream code

###### Tested on

macOS 10.15.5 19F101
Xcode 11.5 11E608c

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -d install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by saagarjha** [comment]
Hey, thanks for submitting this! Sorry I didn't get around to looking at it; was a bit busy with WWDC :) I'll see if I can take a look at this soon.

**Comment by herbygillot** [comment]
No worries. Thank you @saagarjha.

**Comment by reneeotten** [comment]
ping @saagarjha this PR has been open for a while now - do you have any comments or requests for changes? If not please merge this PR or I can do so under the `openmaintainer` policy.

**Comment by saagarjha** [comment]
No, nothing concrete. I just wanted someone to confirm that it worked before merging it in, seeing as we had issues with this last time ;) I realized soon after that comment that I don't have access to a system that I could do this on, as none of my devices are anywhere near a state where they can even get Rust working–I should have mentioned that earlier. Feel free to exercise the openmaintainer policy, I'll check that it works myself once I can :)

**Comment by reneeotten** [comment]
okay, thanks @herbygillot and @saagarjha  - in it goes

**Pull request merged**
