### PR TITLE
increase revision of ports that use require_fortran

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
See https://github.com/macports/macports-ports/commit/51aa273d28af88c11e0b4bc148a3f73fe96157d3
Fixes https://trac.macports.org/ticket/57284

###### Type(s)

- [X] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14
Xcode 10.0

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by MarcusCalhoun-Lopez** [comment]
Please note that this pull requests and https://github.com/macports/macports-ports/pull/2739 are mutually exclusive.

**Comment by pmetzger** [comment]
If there are two mutually exclusive pull requests, how are we to know which one should be merged?

**Comment by cjones051073** [comment]
The solution here is definitely the preferable of the two...

**Comment by eborisch** [comment]
I prefer this approach over dragging along old dependencies.

I *think* only the ones I listed in 51aa273 *need* a port bump; all the others could just use a rebuild on the builders to catch new default variants, since a new install will try to fetch +gcc8, find it isn't there, and rebuild locally (until rebuilds are issued on the builders, that is.) A revbump achieves this as well, at the cost of a local recompile for users with non-standard variants.

This list:

```
LORENE
ape
giza
gr-specest
jags
lapack
octave
py-logilab-hmm
py-numpy
py-pymc
py-scipy
splash
````

are the ones that have a **default** +gfortran ***without*** +gcc[78], so a fetch will match (version, revision, variants) and grab a file built against libgcc7 (by way of libgcc), but `port` won't locally enforce libgcc7's presence (and will instead make sure libgcc -> libgcc8 is installed.) Hence, a revision bump is required.

**Pull request merged**
