### PR TITLE
mesa, libepoxy: add EGL support, fix mesa 19.0.8 for 10.6

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

This PR:
1. Adds EGL support to `mesa` and `libepoxy`: needed for `gtk4`.
2. Allows `mesa` 19.0.8 to be built on 10.6.
3. Fixes the patch error: https://trac.macports.org/ticket/65750
4. Adds needed fixes for old systems.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
this should probably be discussed with upstream mesa before being pushed into macports. The mesa test suite would need to be run and examined. nobody so far uses EGL on macOS.

my patch is slightly different than this patch. That would have to be looked at.

But, enabling EGL in mesa may turn out to be OK, after all that has been done. And then after that, a similar project for libepoxy.

To get gtk4 x11 working, it’s probably better to just force gtk4 to use GLX instead. I’ve already done that. So going the EGL path urgently is not needed.

**Comment by barracuda156** [comment]
@kencu Can we first wait for checks result and then convert to draft? I would like to see if both ports build fine on current Intel systems.

**Comment by kencu** [comment]
your EGL fix for libepoxy is briefer than mine was (I was on Monterey)… that’s cool, if it works!

**Comment by barracuda156** [comment]
> also, if EGL is enabled in mesa, no variant needed. Just adds more pathways for build failures and tickets. It either works or doesn’t work.

I am okay with that. I just followed existing arrangement (`mesa` portfile sets 2 variants and adds both as default ones).

> And then after that, a similar project for libepoxy.

Done in the second commit here, just need to see if it also builds with Clangs on new MacOS.

**Comment by kencu** [comment]
the build is in progress…does making it a draft stop that? If so, I had not noticed that previously.

**Comment by barracuda156** [comment]
> your EGL fix for libepoxy is briefer than mine was (I was on Monterey)… that’s cool, if it works!

If it works here, we can fix it with upstream, I guess. These defines should fix one half of the problem (in place of our cppflag):
```
#elif defined(__APPLE__)
#define _DARWIN_C_SOURCE
```
And then `strndup` error, which is fixed by PG here, perhaps can be also fixed in the source by borrowing from PG code.

**Comment by barracuda156** [comment]
@kencu I get one warning when building `libepoxy` with `gcc12` on 10.6.8:
```
WARNING: ['nm'] does not work. Relinking will always happen on source changes.
error: nm: invalid argument --
Usage: nm [-agnopruUmxjlfAPL[s segname sectname] [-] [-t format] [[-arch <arch_flag>] ...] [file ...]
```
Dunno how serious is that.

**Comment by kencu** [comment]
No, this issue needs to back up 10 steps. Nobody but you cares if this builds with gcc12 on 10.6.8, so let's start somewhere realistic: the current macOS, on Intel and M1. THAT needs to work.  No just build, work.

Upstream mesa should be be involved before this can go ahead. 

What is the status of EGL support in mesa on Apple systems? We know it is almost never enabled, but is it reasonably complete, and does it work at all? How does the mesa test suite perform (esp with respect to EGL)?

We're not pushing junk here.

**Comment by kencu** [comment]
Having said that -- it might turn out in the end that enabling EGL support in mesa across-the-board for all systems is OK. But the proper legwork and testing needs to be done.

MacPorts has hundreds of thousands of users, I'm told. Many of these users actually use it for something important. You can't just push things and hope they stick against the wall. You have to test and verify them first.

What is the effect of that MONOTONIC patch? Is that setting needed? If so, what is the APPLE equivalent setting to use? If not needed, what is the least impactful way of excluding it?

**Comment by barracuda156** [comment]
> What is the effect of that MONOTONIC patch? Is that setting needed? If so, what is the APPLE equivalent setting to use? If not needed, what is the least impactful way of excluding it?

There are some related cases due to missing `pthread_condattr_setclock`:

https://github.com/python/cpython/commit/001fee14e0f2ba5f41fb733adc69d5965925a094

https://github.com/farsightsec/fstrm/commit/bedf826e458f34f24f1be628383217dde8d9397a

**Comment by barracuda156** [comment]
So Intel builds are good on 10.6.8:
```
10:bin svacchanda$ ./port -v installed mesa
The following ports are currently installed:
  mesa @19.0.8_2+egl+osmesa+python27 (active) requested_variants='' platform='darwin 10' archs='x86_64' date='2022-09-01T23:26:25+0700'
10:bin svacchanda$ ./port -v installed libepoxy
The following ports are currently installed:
  libepoxy @1.5.10_0 (active) requested_variants='' platform='darwin 10' archs='x86_64' date='2022-09-01T23:33:40+0700'
```

**Comment by kencu** [comment]
so the next step is to take this to the mesa dev mailing list, and ask for
opinions and help there. For now, IMHO, nobody should push this any time
soon.

(the "nm" warning is commonly seen building with meson, I know it came with
libepoxy, and it is nothing to worry about).

Regarding getting gtk4 working as x11, I believe I will force to gtk4 to
build with GLX on Apple x11 systems, and not use EGL, at least for now,
until the EGL issue is all sorted out someday. GLX is more reliable and
actually tested on Apple systems, and the performance with the EGL enabled
in mesa/libepoxy seemed  poor when I tried that a month ago.

If someday EGL is enabled on Apple systems, it might be via ANGLE instead
of mesa, but here we need some folks who actually know about deep OpenGL
issues. Too bad Jeremy moved on.

To be noted that OpenGL is deprecated on MacOS, and it is said support will
be dropped from M1 / arm64 Macs soon enough. I don't actually know what
that means for x11 on MacOS going forward. Some of the mesa devs are trying
to reverse-engineer the video driver subsystem on M1 macs to see if they
can come up with an alternate long-term support plan.

**Comment by kencu** [comment]
I’m going to take up this EGL discussion on the meas mailing list, and see where it leads, so pls don’t merge this yet.

I have a patchset for gtk4 that avoids EGL on MacOS and uses GLX instead that we might better wind up usingbif EGL is too fragile…

**Comment by barracuda156** [comment]
> I’m going to take up this EGL discussion on the mesa mailing list, and see where it leads, so pls don’t merge this yet.
> 
> I have a patchset for gtk4 that avoids EGL on MacOS and uses GLX instead that we might better wind up using if EGL is too fragile…

@kencu If you or others decide not to have EGL at all or have it as a non-default variant, I will modify PR accordingly.
The wrongly used patch should be moved in any case (that is a bug), and perhaps building 19.0.8 should be allowed on 10.6, regardless of EGL decision outcome.

**Comment by kencu** [comment]
> > I’m going to take up this EGL discussion on the mesa mailing list, and see where it leads, so pls don’t merge this yet.
> > I have a patchset for gtk4 that avoids EGL on MacOS and uses GLX instead that we might better wind up using if EGL is too fragile…
> 
> @kencu If you or others decide not to have EGL at all or have it as a non-default variant, I will modify PR accordingly. The wrongly used patch should be moved in any case (that is a bug), and perhaps building 19.0.8 should be allowed on 10.6, regardless of EGL decision outcome.

Agree 100%. 

Maybe mesa will say EGL is pretty good, needs a bit of work, etc. I don't know yet. I hope it's fairly good, because manually fixing ports to build ignoring it is hard.

I think there is an alternate EGL in ANGLE that is used by Apple for Webkit, and by us for Webkit2-gtk, that may be a better option for EGL support. This stuff is complicated, to be honest, and it's hard to unbuild many ports once it's out there and you find out it's all wrong.

**Comment by kencu** [comment]
request for information posted:

https://lists.freedesktop.org/archives/mesa-dev/2022-September/225848.html

**Comment by barracuda156** [comment]
> request for information posted:
> https://lists.freedesktop.org/archives/mesa-dev/2022-September/225848.html

@kencu Thank you! Let us see what they say.

**Comment by kencu** [comment]
So I have been reading through the mesa source code, in particular here:

https://github.com/Mesa3D/mesa/commit/ad503c41557606d15b0420c824369456f6d20a8f

and in the glx subdirectories, and looking at some other references such as I put in the gtk4 PR yesterday.

It looks like what went on here is that in 2010 Apple made all their GLX code available to mesa, and Jeremy integrated it. That gave mesa hardware support for GLX on Apple systems, using Apple's OpenGL. If that is right, and I think it seems right looking through what is in the egl subsystems on mesa, then on darwin, the only performant OpenGL implementation will be GLX. I think the EGL support on darwin via mesa is through their software renderers only.

If EGL support is brought in with this PR, or with one like it, then these EGL headers will be found by various software builds, and perhaps used. But OpenGL performance will probably be dismal -- which is more or less what I saw when I used this approach building gtk4.

So I would not presently be in favour of committing this without some indication of it being workable and performant.

I will tweak in @jeremyhu here, although I know he is way too busy to comment usually.

**Comment by kencu** [comment]
the main driver for this PR was to get gtk4 on x11 for older systems, and I took the approach of forcing GLX for that

https://github.com/macports/macports-ports/commit/a1bf4959c541fe8a00e6ef016c23a9fea810bbe8

if we can get that to build through on all interesting systems, then that might well be the better approach.

No doubt what I did in that commit could be improved; I'm not an OpenGL engineer. I look forward to improvements.

**Comment by kencu** [comment]
btw, there is a PR to update mesa to the latest release here https://github.com/macports/macports-ports/pull/16260 as well.

**Comment by barracuda156** [comment]
@kencu I am certainly no expert here, though I see no harm in adding EGL as an optional variant (why not make it available for testing?). As for `gtk4`, I trust your solution will be better than mine :)

**Comment by kencu** [comment]
If <EGL/egh.h> is found by software (like gtk4 would have found it) then it would often be preferentially used because of how upstream is angling these days. But because it seems so poorly performant, the outcome could be very poor.

On the other hand, if <EGL/egh.h> is not found then attention would be drawn to that fact, and a workaround developed, like happened with gtk4.

So that is the downside of having it there.

**Comment by kencu** [comment]
I am hoping that someone with some deeper knowledge of how mesa implements EGL on macOS might step forward to comment at some point here. But if it is just left to me, as far as I can tell from the source code, Apple's hardware OpenGL implementation only applies to GLX.

**Comment by kencu** [comment]
I am hoping that someone with some deeper knowledge of how mesa implements EGL on macOS might step forward to comment at some point here. But if it is just left to me, as far as I can tell from the source code, Apple's hardware OpenGL implementation only applies to GLX.

**Comment by kencu** [comment]
not going to to enable egl at present.

**Comment by kencu** [comment]
recent info from the guru

https://lists.freedesktop.org/archives/mesa-dev/2023-January/225907.html

**Comment by barracuda156** [comment]
> recent info from the guru
> 
> https://lists.freedesktop.org/archives/mesa-dev/2023-January/225907.html

Thank you.

**Pull request closed without merging**
