### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by jwillemsen**
#### Description

Checks weekly whether the used github actions up to date, if not, it will create a pull request

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

### CODE REVIEW

**Comment by mascguy** [comment]
My knowledge of GitHub Actions is limited at the moment, but I like the idea!

@catap Kirill, any thoughts on this?

**Comment by catap** [comment]
@mascguy I not sure that it can work.

@jwillemsen which dependencies @dependabot should update at this repo?

**Comment by jwillemsen** [comment]
All the uses in https://github.com/macports/macports-ports/blob/master/.github/workflows/main.yml

**Comment by catap** [comment]
@jwillemsen I've checked it and haven't found any :)

**Comment by catap** [comment]
Do you mean `actions/checkout@v2` and `ctions/upload-artifact@v2`? As far as I see it is used the last (=unspecified) version.

Am I wrong?

**Comment by jwillemsen** [comment]
Yes, at the moment a `v3` is released with this new file you get a PR from dependabot automatically

**Comment by catap** [comment]
@jwillemsen here the issue: PR which is opened by dependabot won't pass CI because it must have some edited ports, and otherwise it just fails because it can't test nothing.

And without a port to test it is impossible to be sure that updating `actions/upload-artifact@v2` to `@v3` won't broke anything before it merged.

:)

**Comment by jwillemsen** [comment]
At least the automatic PR will inform you that something has to be updated

**Comment by reneeotten** [comment]
I am not sure this will add much... how often do GitHub action workflows get updated? Is adding yet-another configuration file worth the trouble for something that happens occasionally and can just be done manually when needed? (Of course the use of `dependabot` is helpful in some cases where there are actual dependencies, I am just not sure that's the case for MacPorts)

**Comment by mascguy** [comment]
> I am not sure this will add much... how often do GitHub action workflows get updated? Is adding yet-another configuration file worth the trouble for something that happens occasionally and can just be done manually when needed? (Of course the use of `dependabot` is helpful in some cases where there are actual dependencies, I am just not sure that's the case for MacPorts)

True. But I'm wondering if this idea be useful for anything else for our GitHub configs?

Can't think of a concrete example, particularly this early in the morning. But just throwing it out there...

**Comment by catap** [comment]
@mascguy with some doing it is possible to create a github action which runs `port livechech` and try to bump outdated port.

Anyway, chances that it introduces an error quite high.

**Comment by mascguy** [comment]
> @mascguy with some doing it is possible to create a github action which runs `port livechech` and try to bump outdated port.
> 
> Anyway, chances that it introduces an error quite high.

Yeah for sure.

But perhaps this overall concept might be applicable for something else, which we haven't considered before?

So even if we don't choose to make the specific change currently in this PR, would it make sense to keep this open from an overall GitHub Action/Workflow brainstorming perspective?

**Comment by ryandesign** [comment]
> possible to create a github action which runs `port livechech` and try to bump outdated port

No. Port updates should be submitted by humans who have verified it builds successfully first. There are any number of things that a human may need to check to do an update, such as the release notes, comments left in the Portfile, dependencies that may need to be added, new OS version restrictions, or other cleanup done in the Portfile. It is not appropriate for an automated process to submit pull requests of dubious quality.

**Pull request closed without merging**
