### PR TITLE
msgpack: consolidate all versions in one port

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR consolidates the previous ```msgpack``` and ```msgpack1``` ports. Now ```msgpack``` tracks the latest stable release (currently v3.2.1), and the subports ```msgpack0```, ```msgpack1```, and ```msgpack2``` provide the last release in the 0.x, 1.x, and 2.x branch, respectively.

I have updated and rev-bumped ports that previously depended on ```msgpack``` to now depend on ```msgpack0```. Please note that several of these ports are (very) outdated and/or upstream seem rather inactive; if these do not build right now, it shouldn't have anything to do with the changes in this PR.

###### Tested on
macOS 10.14.6 18G95
Xcode 10.3 10G8

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
Is there a reason to have all of these versions when only the oldest 0.x version is actually being used as a dependency by other ports? Can they not be updated to use the latest version and we just have a single port for msgpack?

**Comment by mf2k** [comment]
It does allow time to transition. So that's good.

**Comment by mf2k** [comment]
It does allow time to transition. So that's good.

**Comment by reneeotten** [comment]
ah, the failure of ```kumofs``` seems real, it appears that with the ```cmake``` installation it only installs ```/opt/local/lib/libmsgpack.* ``` files and not ``/opt/local/lib/libmsgpackc.*```. Let me look at that... it appears correct for the other versions.

**Comment by reneeotten** [comment]
> ah, the failure of `kumofs` seems real, it appears that with the `cmake` installation it only installs `/opt/local/lib/libmsgpack.* ` files and not `/opt/local/lib/libmsgpackc.*`. Let me look at that...

okay, I cannot figure out how to build/install both of them using ```cmake```, reverting to the way as done previously in the ```msgpack``` Portfile for version 0.5.9. 

One additional commit here, should be removed before merging, for the two ports that depend on ```msgpack``` version 1 - just to make sure that it still works.

**Pull request merged**
