### PR TITLE
python38: Disable posix._fcopyfile function on Tiger

### PR DESCRIPTION
**Pull request by dgelessus**
#### Description

Python 3.8's `posix._fcopyfile` implementation unconditionally uses `<copyfile.h>`, which only exists on Leopard ane newer. This patch removes `posix._fcopyfile` on Tiger - this is okay because the rest of the stdlib uses `posix._fcopyfile` only conditionally after checking that the function exists (non-Apple systems don't have `posix._fcopyfile` either).

Fixes https://trac.macports.org/ticket/59827

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.4
Xcode 2.5

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

Note: I can't test this fully at the moment. The patch fixes the copyfile compile error, but the build still doesn't work for me because of another issue (https://trac.macports.org/ticket/59772).

### CODE REVIEW

**Comment by reneeotten** [comment]
@dgelessus thank you for your contribution! Unfortunately I don't feel qualified to determine whether this change is appropriate - perhaps @kencu and/or @jmroot can take a look?

**Comment by kencu** [comment]
Thanks for this. Looks like it will probably become part of the fix for python38 on older systems. I haven't buckled down to fix python38 yet, as there are at least these two issues so far. In general, what I like to do with these multi-part breakages is fix them all at once (see libuv or cmake, for example) and then run the appropriate test suite, if there is one, or at least try to test the functionality in some way if I can, to make sure that the build fixes actually translate into usable real fixes, before I update the port all at once.

**Comment by jmroot** [comment]
Looks reasonable, though I can't test it. I would encourage you to upstream this, though they would probably prefer an autoconf check that sets HAVE_COPYFILE or similar.

**Comment by dgelessus** [comment]
> I would encourage you to upstream this

Hm, I don't know what CPython's support policy is for OS X. The Python.org installers have dropped 10.3/10.4 support in 2013 (last versions are [2.7.6](https://www.python.org/downloads/release/python-276/) and [3.2.5](https://www.python.org/downloads/release/python-325/)), 10.5 support in 2017 (last versions are [2.7.14](https://www.python.org/downloads/release/python-2714/) and [3.4.4](https://www.python.org/downloads/release/python-344/)), and 10.6 - 10.8 support for Python 3 in 2019 (last version is [3.7.5](https://www.python.org/downloads/release/python-375/)). According to [this comment](https://bugs.python.org/issue31931#msg317774) I found on bugs.python.org they also no longer run a 10.4 buildbot.

On the other hand, the repo's [Mac README](https://github.com/python/cpython/blob/a9d0a6a1b932752873e04714c5dda707729078e4/Mac/README.rst) still has instructions for universal builds down to 10.4, so it seems they haven't completely dropped old OS X support yet.

I would wait with submitting an upstream PR though until we have can get Python 3.8 to fully build on Tiger - as @kencu pointed out we have no way to test this patch yet.

**Comment by kencu** [comment]
```
$ port -v installed python38
The following ports are currently installed:
  python38 @3.8.0_1 (active) platform='darwin 8' archs='ppc' date='2019-12-17T22:41:05-0800'
```

bit more testing to go...

**Comment by kencu** [comment]
Not an elegant patch, but gets the job done, I think -- running test suite on Tiger now, and will run a build on Leopard and Snow Leopard to make sure it all works as it should.

<https://trac.macports.org/attachment/ticket/59772/patch-python38-leopard-tiger.diff>

**Comment by dgelessus** [comment]
@kencu Thanks for the patch, it seems to work fine for me on Intel Tiger. The tests for the `shutil` module (which uses `posix._fcopyfile`) run successfully, although I had to adjust one skip condition (it assumed that `posix._fcopyfile` always exists on Mac, which is not the case anymore with my patch).

**Comment by kencu** [comment]
this was incorporated into #6492. Thanks!

**Pull request closed without merging**
