### PR TITLE
wireshark3: add missing minizip dep

### PR DESCRIPTION
**Pull request by Tatsh**
#### Description

- wireshark3: add required minizip dep
- wireshark30: add required minizip dep

Maybe related to https://trac.macports.org/ticket/61414 where Wireshark's system will detect libraries available and enable things based on their presence. In general, I think it's better to just include minizip support, because a package may have a bdep that uses minizip but then it would cleaned out with `port clean`. Then by surprise Wireshark will fail to start.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.0.1 21A559 x86_64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
I think this might deserve a `revision` bump.

**Comment by mascguy** [comment]
> I think this might deserve a `revision` bump.

Agreed, seems reasonable given the change.

**Comment by Tatsh** [comment]
I added the `minizip` variant, with the correct option sent to configure phase. This should fix the original issue. Revbump'ing because this is still a bug fix.

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
LGTM. @ghosthound ?

**Review by ghosthound — APPROVED** [review]
Looks good, thanks for catching it and the PR!

**Pull request merged**
