### PR TITLE
dbeaver-community: fix checksums after silent update

### PR DESCRIPTION
**Pull request by lhaeger**
Closes: https://trac.macports.org/ticket/58860

###### Tested on

macOS 10.14.6 18G84
Xcode 10.3 10G8

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by lhaeger** [comment]
Bumped revision since it's a new build that probably fixes some bug(s).

**Comment by mf2k** [comment]
You will need to make a minor adjustment. See https://trac.macports.org/wiki/PortfileRecipes#stealth-updates

**Comment by lhaeger** [comment]
That build failed with

`Synchronizing the MacPorts installation with the project's rsync server...
Version: 2.5.4
Successful!
Cloning into '../mpbb'...
curl: (22) The requested URL returned error: 502 Bad Gateway
##[error]Bash exited with code '22'.`

How can this be fixed and the build triggered again? Or will that happen automatically after a while?

**Comment by cjones051073** [comment]
@lhaeger rebuilds are not automatic. However, with azure you can just click the details link and request a re-run of the tests from there.

**Comment by lhaeger** [comment]
> with azure you can just click the details link and request a re-run of the tests from there.
Thanks for that, will have a another look next time. Did not catch my eye last time, I'm getting old... :-)

**Comment by cjones051073** [comment]
> > with azure you can just click the details link and request a re-run of the tests from there.
> > Thanks for that, will have a another look next time. Did not catch my eye last time, I'm getting old... :-)

Maybe its just visible to Macports members ...

**Pull request merged**
