### PR TITLE
cask: update to 0.8.3

### PR DESCRIPTION
**Pull request by amake**
#### Description

Update cask to 0.8.3

### CODE REVIEW

**Comment by pmetzger** [comment]
One CI build failed. I'm not sure I get why.

**Comment by pmetzger** [comment]
Anyway, one of the builds did work and this change seems entirely minor so I'm inclined to merge. @amake do you see any reason I should worry about that CI failure?

**Comment by kencu** [comment]
`curl: (56) SSLRead() return error -9806` probably means the SSL version on fairly recent macOS is out of date for communicating with the SSL of the server.

I just installed it without any trouble on 10.6.8, but I have my system bootstrapped to a brand new curl and SSL.

Hmmm. github failures. This might bring the distfile mirroring issue to the forefront pretty quickly...

**Comment by pmetzger** [comment]
I'm going to merge, since this doesn't seem to be an issue with cask.

**Pull request merged**
