### PR TITLE
WIP: dep: update to 0.5.4

### PR DESCRIPTION
**Pull request by umeshksingla**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by emcrisostomo** [comment]
Thankss @umeshksingla

**Comment by umeshksingla** [comment]
@emcrisostomo I am really sorry but this wasn't supposed to be merged yet. I am surprised that the tests didn't fail since I did not change the checksums. Still figuring out how to generate those since `port bump` did not work.

Can you verify the installation?

**Comment by emcrisostomo** [comment]
Oh boy, I opened all the checks and they were green! Let me try in a host.

**Comment by emcrisostomo** [comment]
It worked correctly @umeshksingla:

```
$ sudo port install dep
Password:
--->  Computing dependencies for dep
--->  Fetching archive for dep
--->  Attempting to fetch dep-0.5.4_0.darwin_18.x86_64.tbz2 from https://packages.macports.org/dep
--->  Attempting to fetch dep-0.5.4_0.darwin_18.x86_64.tbz2 from http://lil.fr.packages.macports.org/dep
--->  Attempting to fetch dep-0.5.4_0.darwin_18.x86_64.tbz2 from http://mse.uk.packages.macports.org/sites/packages.macports.org/dep
--->  Fetching distfiles for dep
--->  Verifying checksums for dep
--->  Extracting dep
--->  Configuring dep
--->  Building dep
--->  Staging dep into destroot
--->  Installing dep @0.5.4_0
--->  Activating dep @0.5.4_0
--->  Cleaning dep
--->  Scanning binaries for linking errors
--->  No broken files found.
--->  No broken ports found.
```

Sorry if I state the obvious, but in the future refrain to open a pull request if you're not finished.

**Comment by umeshksingla** [comment]
Ah. I just had no way to check because I already installed `dep` from another source and setting up a new macports copy felt too much. I thought maybe I will give Travis/Azure pipelines a try and see if they report the failures. I wasn't sure if the checks run on a Draft PR, sorrry.

So the binary doesn't get verified or what? Even the previous checksums don't match with the ones with [official](https://github.com/golang/dep/releases/tag/v0.5.0) ones.
cc: @emcrisostomo

**Comment by emcrisostomo** [comment]
Hi @umeshksingla, I just checked the port and it's working fine. The checksums are just ignored because the `fetch.type` is set to `git`. AFAICT, this may be a quick workaround because the build command (`./hack/build-all.bash`), assumes it's building sources in a git repository.

This is suboptimal, because using `git` as a fetch type is discouraged, and can lead to non-reproducible builds.

I examined the `build-all.bash` script and basically all it does is extracting some repository-related variables which are passed as link flags to the build. The current `Portfile` can be easily refactored into a `Portfile` that uses a distribution file (the `docker` port file can be used as an inspiration; nevertheless, there's some work to do. I'll probably open a ticket to track this improvement.

**Comment by emcrisostomo** [comment]
Tracked here:

https://trac.macports.org/ticket/60128

**Pull request merged**
