### PR TITLE
grpc: Update to version 1.56.2

### PR DESCRIPTION
**Pull request by essandess**
* Update to version 1.56.2
* Add Python 311

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.4.1 22F770820d arm64
Xcode 14.3.1 14E300c

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mascguy** [comment]
I did some preliminary work on this a few weeks ago. And the update was troublesome enough, that I shelved it for now. Though your changes are more extensive, so perhaps you covered some bases I missed.

Regardless, have you reviewed the CI logs, to see why the build is failing?

**Comment by essandess** [comment]
I

> I did some preliminary work on this a few weeks ago. And the update was troublesome enough, that I shelved it for now. Though your changes are more extensive, so perhaps you covered some bases I missed.
> 
> Regardless, have you reviewed the CI logs, to see why the build is failing?

Almost certainly a dependency on one of the other PRs. I got all this stuff working together but haven’t teased out the dependency chain so let’s just merge the prs as they build.

**Comment by essandess** [comment]
This PR depends upon:
* #19596

**Comment by pmetzger** [comment]
The PR this depends on has been closed for lack of activity in trying to get it integrated. I'm closing this for now, but feel free to re-open it at an appropriate time.

**Comment by suhailskhan** [comment]
There is a new effort to update this port to 1.72.0 as part of #28321, opened last week. Build is successful, except for the `py-grpcio-tools` subport. @essandess, if you can provide some input then it should help us bring it a lot closer to being ready to merge.

**Pull request closed without merging**
