### PR TITLE
gingerblue: new port

### PR DESCRIPTION
**Pull request by oleaamot**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.0.1 21A559 arm64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Ole, I'll help you squash your commits.

Let me know when you're finished with your changes, and I'll squash for you before we merge.

**Review by mascguy — APPROVED** [review]

**Comment by reneeotten** [comment]
> Ole, I'll help you squash your commits.

or just read/follow the instruction I gave in the other PR ;)

**Comment by mascguy** [comment]
> > Ole, I'll help you squash your commits.
> 
> or just read/follow the instruction I gave in the other PR ;)

Well, it's a bit painful for users new to Git. And we don't want to discourage new contributors, so I'm willing to help the first time.

**Comment by mascguy** [comment]
Thank you so much for your contribution Ole!

**Comment by oleaamot** [comment]
You are welcome!

Hope the binary works for you.  It fails on Monterey.

**Pull request merged**
