### PR TITLE
gsl-devel: New port for testing only

### PR DESCRIPTION
**Pull request by Dave-Allured**
#### Description

Test port for GSL releases and port development.

###### Tested on

CI only.  Macos 11, 12, 13; x86_64. Macos 14 ;arm.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by reneeotten — CHANGES_REQUESTED** [review]
shouldn't this just be a subport of the `gsl` port given the similarity and amount of code duplication? Also, it should likely conflict with that port (and vice versa). Finally, if this is really needed then likely one would need/want to change all ports that depend on `gsl` to use a path-dependency style instead?

**Comment by Dave-Allured** [comment]
> shouldn't this just be a subport of the `gsl` port given the similarity and amount of code duplication? Also, it should likely conflict with that port (and vice versa). Finally, if this is really needed then likely one would need/want to change all ports that depend on `gsl` to use a path-dependency style instead?

Not a subport.  I do not want to touch the working GSL port until I have checked a new upstream version against as many macos versions as possible, using the Macports builders only.  I am checking builds including the port test phase.  I thought that was what devel ports were for.  Please let me know if I have the wrong idea.

**Comment by reneeotten** [comment]
> > shouldn't this just be a subport of the `gsl` port given the similarity and amount of code duplication? Also, it should likely conflict with that port (and vice versa). Finally, if this is really needed then likely one would need/want to change all ports that depend on `gsl` to use a path-dependency style instead?
> 
> Not a subport. I do not want to touch the working GSL port until I have checked a new upstream version against as many macos versions as possible, using the Macports builders only. I am checking builds including the port test phase. I thought that was what devel ports were for. Please let me know if I have the wrong idea.

no, that is not what `-devel` ports are intended for, they are intended for using a development snapshot / pre-release versions; sure you can use that to make sure that everything works. But that can/should in this case still be done as a subport of the `gsl` port as pretty much everything else is the same and there is no need to duplicate a complete Portfile. There are plenty of examples where that is done, for example, one that I maintain is `pymol-devel` which is a subport in the `pymol` port.

**Comment by Dave-Allured** [comment]
> no, that is not what `-devel` ports are intended for

Okay, my misunderstanding.  Sorry.  For this port, normal CI testing should suffice.

**Pull request closed without merging**
