### PR TITLE
mint: new port

### PR DESCRIPTION
**Pull request by klanchman**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.0.1 21A559 arm64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Kyle, looks great overall. And welcome to MacPorts!

One thought though: Would it be better to run the build during the `build` phase, rather than `destroot`?

**Comment by mascguy** [comment]
> Kyle, looks great overall. And welcome to MacPorts!
> 
> One thought though: Would it be better to run the build during the `build` phase, rather than `destroot`?

To be fair though, I haven't looked closely at the numerous ports that build via Xcode. So if this is the established convention, then I'm fine with it.

Anyone else?

**Comment by mascguy** [comment]
> I initially tried splitting it up, but I found that running `make install` caused it to build again during `destroot`. Would it be more typical to `xinstall` during `destroot` instead of using the Makefile in this case? (I was borrowing from the [Carthage Portfile](https://github.com/macports/macports-ports/blob/master/devel/carthage/Portfile) in this case since it was similar and simple 😄)

Yes indeed, so no need to run multiple targets.

> Aside, is the build failure on Xcode 11 something I should deal with? I glanced at it, and the Makefile is using a newer Swift compiler option (`--arch`, Xcode ~12.5?), but I think the project is supposed to build with Xcode 10.2+. If so, should I actually make it work, or just add a minimum Xcode version that works with the Makefile?

For now, we can require macOS 10.15 (or 10.14, if that's the minimum version). But if you can update the port to support older macOS/Xcode releases, that would definitely be preferable!

Also, just pushed some minor changes. Now we're building during that phase, with nothing to be done during phase `destroot`.

Take a look, and let me know if it all makes sense!

**Comment by mascguy** [comment]
Let's merge as-is, as a starting point. And then if you want to refine via a subsequent PR - such as expanding macOS/Xcode support, if possible - we can certainly do that.

And thanks so much for your contribution Kyle!

**Comment by klanchman** [comment]
Sounds good! Thanks for the cleanup, I think it all makes sense 👍

What would be a good way to test if I don’t have easy access to older versions of macOS? Make a draft PR and fiddle with it so the checks here run? Is there some way to try it out against all the configurations shown in the “Port Health” section of the port detail page?

**Comment by mascguy** [comment]
> What would be a good way to test if I don’t have easy access to older versions of macOS? Make a draft PR and fiddle with it so the checks here run? Is there some way to try it out against all the configurations shown in the “Port Health” section of the port detail page?

One of the GitHub CI jobs cover macOS 10 14, so you'll get that validation automatically when creating a PR.

For macOS releases earlier than that, I'm happy to help: I have a suite of macOS VMs covering 10.6 through 10.15, making it easy to validate most anything.

To get started, create a draft PR, and get it working for 10.14. Once that's done, I can assist with validation on earlier releases.

How does that sound?

**Comment by klanchman** [comment]
Excellent! I’ll try to start playing around with this in the next few days.
For some reason it hadn’t really struck me how far back MacPorts tries to support! 🤯

**Pull request merged**
