### PR TITLE
IMAGER v3.9-03

### PR DESCRIPTION
**Pull request by PenguenJulien**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
What is going on here?

**Comment by PenguenJulien** [comment]
hi,
Could you check my request?
Thanks

**Comment by barracuda156** [comment]
@PenguenJulien I do not really understand why my `R` ports are here at all. None of them depend on `imager` port, I believe, and definitely most of them do not.
The PR adds 300k+ LoC. Is this just a rebasing error?

**Comment by PenguenJulien** [comment]
I don't know ...

**Comment by barracuda156** [comment]
@PenguenJulien Well, have you modified something about ports sitting in `R` directory? If not, they should not be here. Try rebasing against the master, I guess?

**Pull request closed without merging**
