### PR TITLE
Gildas: updated to version 201802a.

### PR DESCRIPTION
**Pull request by bardeau**
@smaret can you please accept this PR? This time I think that's worth you try to compile it by yourself before merge, as I had an issue regarding Makefiles. My commit message is reproduced below.

This version also bypasses a MacPorts issue which does not seem to honor
the GNU Making-Makefiles rules (see
https://www.gnu.org/software/make/manual/html_node/Remaking-Makefiles.html
, paragrah 2). This issue is to be confirmed. For the time being,
our "make depend" is added before "make" or "make install", while
GNU make ensures it should be useless.

Also added -w flag to "make" calls. This adds entering/leaving
directory traces for a better compilation log.

### CODE REVIEW

**Comment by bardeau** [comment]
I am working on a feature added + bug fix both ported to branch 201802. I will update this PR when I am ready.

**Comment by bardeau** [comment]
The branch is now ready for merging. Thanks.

**Comment by smaret** [comment]
Thanks for the update.

**Comment by smaret** [comment]
@pmetzger Indeed the PR wasn’t merged, and since I’m connecting with my phone, GitHub does not allows me to merge it. Can you merge it for me please ?

**Pull request merged**
