### PR TITLE
capnproto: update patches to ones merged to upstream, drop earlier hacks

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

@neverpanic All earlier hackery dropped, we have fixed everything correctly now and patches merged to upstream. Therefore, applying them unconditionally.
Many thanks to @catap for fixing broken mutices. And to the upstream for diagnosing sfinae error, which was causing obscure failures.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8
Xcode 3.2.6

macOS 10A190
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@neverpanic Could you please review this?

**Comment by barracuda156** [comment]
@neverpanic 1.0.0 has been released, I run tests and rebase the PR.

**Comment by neverpanic** [comment]
Please add a commit on top that bumps the revision field of all ports in `port echo depends:capnproto`, otherwise those will break with the update to 1.0.

Other than that this looks good to me. Sorry for the delay, it's been a crazy weekend.

**Comment by barracuda156** [comment]
@neverpanic Sure, will be done. We need to fix one issue for v. 1.0.0, that is why turned to draft.

**Comment by barracuda156** [comment]
Should be good now.
https://github.com/capnproto/capnproto/pull/1736

**Comment by barracuda156** [comment]
P. S. Let me revbump dependents now.

**Comment by barracuda156** [comment]
@neverpanic @mascguy `textmate2` fails, with a weird and apparently unrelated error:
```
  /* com.apple.ibtool.errors */
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_editors_textmate2/textmate2/work/textmate-2.0.23/Applications/TextMate/resources/English.lproj/MainMenu.xib: error: Compilation failed. Unable to write to path: /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_editors_textmate2/textmate2/work/.home/build/textmate-2.0.23/release/_CompileXib/Applications/TextMate/resources/English.lproj/MainMenu.nib
      Underlying Errors:
          Description: You don’t have permission to save the file “MainMenu.nib” in the folder “English.lproj”.
          Failure Reason: You don’t have permission.
          Recovery Suggestion: To view or change permissions, select the item in the Finder and choose File > Get Info.
          Underlying Errors:
              Description: The operation couldn’t be completed. Operation not permitted
              Failure Reason: Operation not permitted
          Description: “MainMenu.nib” couldn’t be removed.
          Failure Reason: The file doesn’t exist.
          Underlying Errors:
              Description: The operation couldn’t be completed. No such file or directory
              Failure Reason: No such file or directory
```

**Comment by mascguy** [comment]
> @neverpanic @mascguy `textmate2` fails, with a weird and apparently unrelated error:
> 
> ```
> .../textmate2/work/textmate-2.0.23/Applications/TextMate/resources/English.lproj/MainMenu.xib:
> error: Compilation failed. Unable to write to path:
> .../textmate2/work/.home/build/textmate-2.0.23/release/_CompileXib/Applications/TextMate/resources/English.lproj/MainMenu.nib
> ```

Hmmm, this looks potentially familiar, though it's been a while since I've run across anything similar.

Have you searched old Trac tickets?

**Comment by barracuda156** [comment]
@mascguy Not yet; honestly I hoped that @neverpanic takes a look, since `textmate2` is also his port, and the error is clearly unrelated to added support for `i386` and `ppc`.

Converting to a draft for now, need to sort one issue, working on it with the upstream.

**Comment by neverpanic** [comment]
> @neverpanic @mascguy `textmate2` fails, with a weird and apparently unrelated error:
> 
> ```
>   /* com.apple.ibtool.errors */
>   /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_editors_textmate2/textmate2/work/textmate-2.0.23/Applications/TextMate/resources/English.lproj/MainMenu.xib: error: Compilation failed. Unable to write to path: /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_editors_textmate2/textmate2/work/.home/build/textmate-2.0.23/release/_CompileXib/Applications/TextMate/resources/English.lproj/MainMenu.nib
>       Underlying Errors:
>           Description: You don’t have permission to save the file “MainMenu.nib” in the folder “English.lproj”.
>           Failure Reason: You don’t have permission.
>           Recovery Suggestion: To view or change permissions, select the item in the Finder and choose File > Get Info.
>           Underlying Errors:
>               Description: The operation couldn’t be completed. Operation not permitted
>               Failure Reason: Operation not permitted
>           Description: “MainMenu.nib” couldn’t be removed.
>           Failure Reason: The file doesn’t exist.
>           Underlying Errors:
>               Description: The operation couldn’t be completed. No such file or directory
>               Failure Reason: No such file or directory
> ```

That's unrelated. Did you test that in trace mode, because I believe that causes this. We can ignore this and merge anyway.

**Review by neverpanic — APPROVED** [review]
LGTM, let me do a quick test build and then I'll merge this.

**Comment by neverpanic** [comment]
Build successful, merging.

**Comment by barracuda156** [comment]
Thank you, great!

**Pull request merged**
