### PR TITLE
openal-soft: fix build on 10.4-10.6

### PR DESCRIPTION
**Pull request by evanmiller**
#### Description

`patch-openal-soft-coreaudio.diff` adapted from @kencu's TigerPorts. The other additions are mine.

```
$ openal-info
Available playback devices:
    CoreAudio Default
Available capture devices:
    CoreAudio Default
Default playback device: CoreAudio Default
Default capture device: CoreAudio Default
ALC version: 1.1

** Info for device "CoreAudio Default" **
ALC version: 1.1
ALC extensions:
    ALC_ENUMERATE_ALL_EXT, ALC_ENUMERATION_EXT, ALC_EXT_CAPTURE,
    ALC_EXT_DEDICATED, ALC_EXT_disconnect, ALC_EXT_EFX,
    ALC_EXT_thread_local_context, ALC_SOFT_device_clock, ALC_SOFT_HRTF,
    ALC_SOFT_loopback, ALC_SOFT_loopback_bformat, ALC_SOFT_output_limiter,
    ALC_SOFT_pause_device
Available HRTFs:
    Built-In HRTF
```

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.4.11 8S165 Power Macintosh
Component versions: DevToolsCore-798.0; DevToolsSupport-794.0

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
Looks reasonable, however I may not have the energy to update this patch if a future update of openal-soft makes incompatible changes in the patched files. You may become responsible for maintaining this patch and/or the port if that happens, or rather, I may stop updating it and it will be left to you or anyone else to do so.

Ideally the patch should be submitted to the developers of openal-soft so that they can incorporate it into their code and then everyone can benefit, not just MacPorts users, and then we won't have problems with having to maintain the patch forever.

**Comment by evanmiller** [comment]
@ryandesign Happy to leave this open and pitch the patches upstream if you'd rather not deal with the extra maintenance here.

(I'm not particularly interested in this port; just trying to upstream what I can out of Ken's now-404 TigerPorts repo...)

**Comment by evanmiller** [comment]
Upstream PR for the dispatch diff: https://github.com/kcat/openal-soft/pull/610

If it goes well I'll see about upstreaming the CoreAudio changes. The AudioComponent stuff could also be a good candidate for inclusion in LegacySupport.

**Comment by evanmiller** [comment]
Converting to Draft while the semaphore issue is discussed upstream

**Comment by evanmiller** [comment]
After further discussion even further upstream (GCC) there appear to be blocking issues with the C++ run-time. I will close this PR until those are resolved.

**Pull request closed without merging**
