### PR TITLE
boost177: obsolete, migrate 'bali-phy{,-devel}' to boost181

### PR DESCRIPTION
**Pull request by mascguy**
### Description

* Migrate `bali-phy`/`bali-phy-devel` to `boost181`
* Obsolete `boost177`

### CODE REVIEW

**Comment by reneeotten** [comment]
@mascguy I'll test tonight when I get home. Did you update the default version in the "boost" PG - that should be done for sure and then explicitly adding a boost.version in the Portfile isn't needed anymore.

**Comment by mascguy** [comment]
> Did you update the default version in the "boost" PG - that should be done for sure and then explicitly adding a boost.version in the Portfile isn't needed anymore.

At this point, the goal is simply to reduce the number of Boost ports we have to maintain. So the default version remains at 1.76. (Or 1.71, for 10.5 and earlier.)

We'll revisit the default eventually, but that will require significant testing of all dependents. So there's no plan to tackle that in the near term.

**Comment by mascguy** [comment]
I'll take a closer look at the `dssp` failures a bit later. Switching to draft for now.

**Comment by reneeotten** [comment]
> I'll take a closer look at the `dssp` failures a bit later. Switching to draft for now.

the `dssp` repository has moved and there are newer releases available. It does need a few new dependencies, and I started a branch with this a while back. There were some build issues that I cannot remember right now anymore, so I gave up at that point. I'll revive that branch and see if these problems have magically disappeared in the meantime ;)

**Comment by reneeotten** [comment]
@mascguy the latest version doesn't require `boost` anymore, except for building the test-suite. I've removed that for now, so you can rebase this PR to resolve the conflicts and not worry about it anymore

**Comment by mascguy** [comment]
> @mascguy the latest version doesn't require `boost` anymore, except for building the test-suite. I've removed that for now, so you can rebase this PR to resolve the conflicts and not worry about it anymore

Awesome, thank you Renee!

**Comment by mascguy** [comment]
CI looks good now, with `dssp` out of the mix. Merging.

**Pull request merged**
