### PR TITLE
[update] Update libalkimia to 8.0.3

### PR DESCRIPTION
**Pull request by sxntxn**
#### Description

Needed for most recent kmymoney4.
See also #7489 for a plan.
CC @NicosPavlov

###### Type(s)
- [x] update

###### Tested on
macOS 10.15.5 19F101
Xcode 11.5 11E608c 

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?  -> `libalkimia has no tests turned on`
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by NicosPavlov** [comment]
As discussed in #7489, I would include also the update to kmymoney4 and making kmymoney4-devel in the same PR to avoid having too many. 

Considering this Portfile, there are some changes that I think should be made, as listed above.

**Comment by reneeotten** [comment]
also please make sure your commit message follows the rules (it should be `port: short description`).

**Comment by sxntxn** [comment]
> * Adding port:cmake and port:automoc as build dependencies is redundant as they are included in the PortGroup kde 1.1.

I had to add those to get a clean build with `port -vst install`. Is that a bug in the PortGroup, or intended behavior?

> * The post-destroot step can be simply suppressed by instead passing -DLIB_INSTALL_DIR=${prefix}/lib to configure.args

Thanks, it seems I've been looking for this solution in all the wrong places.

**Comment by NicosPavlov** [comment]
> > * Adding port:cmake and port:automoc as build dependencies is redundant as they are included in the PortGroup kde 1.1.
> 
> I had to add those to get a clean build with `port -vst install`. Is that a bug in the PortGroup, or intended behavior?

You are right, the error is also happening in the checks. This is because you are declaring build dependencies with depends_build, which erases previous declarations. You need to replace it with depends_build-append to keep the dependences declared in the PortGroups.

**Comment by sxntxn** [comment]
> * Thanks for the changes. Libalkimia looks good to me. The last thing is to use depends_build-append to keep the dependences declared in the PortGroup.
> * In the patch (patch-CMakeLists_remove_APIDOC.txt.diff) and in the Portfile, you are requiring gmp. However, to my understanding, mpir is preferred, and is already required by libalkimia. This makes the requirement for gmp useless as it would be superseded anyway.
> * You are removing the mainRaster patch, which should be kept unless there is a specific reason.
> * I would keep the comments about meinproc at the end, as this has been often an issue with kde4 ports.
> * Sorry that I was not clear about kmymoney4-devel, but we avoid directly deleting ports, as this can break users' install. We instead use the obsolete PortGroup to have users transfer to the replacement port. You can find an example in the openssl11 Portfile.

All done.

> * I am not sure of the usefulness of the patch cmake-disable-icon-generation.patch. Based on my tests, not using this patch does not lead to any error. Did you encounter a specific build error?

Yes, but I don't remember specifics. Seems to work without: removed. 

> * The version number should not solely use the hash from git commits, as this will cause trouble with upgrade that need to be incremental. You can use the date with part of the hash as in:
> version 20200520-[string range ${github.version} 0 7]

I've left the release number (4.8.4) in, and changed the date to the git commit's date. Do you think this is appropriate?

**Comment by NicosPavlov** [comment]
> I've left the release number (4.8.4) in, and changed the date to the commit's date, so it's pretty long now:
> `@4.8.4+20200617-f76ab094`
> Do you think this is appropriate?

It is long, but still correct, so I guess that it is fine. 

Everything looks good to me. I'll merge that later.

**Comment by sxntxn** [comment]
Great! Thank you very much!

**Comment by ryandesign** [comment]
Next time you squash and merge please edit the commit message so that it still conforms to our guidelines. Not every intermediate commit that was made in the PR need necessarily appear in the final commit message. For example, the line "Re-add comment about meinproc" is not useful because it had only been removed within the PR. In the context of the final squashed commit, nothing about meinproc got removed or added.

**Comment by NicosPavlov** [comment]
Yes, sorry about that. I actually changed the title and commit message when merging, but an error appeared saying that it could not perform the merge, and next thing that appeared after page reloading was that the merge was performed, with the original title and all the comments. I am not sure of what exactly happened, but that surely was not intended.

**Pull request merged**
