### PR TITLE
irrlichtmt: update

### PR DESCRIPTION
**Pull request by Zweihorn**
PR is READY for review

#### Description

* irrlicht 1.9.0mt9 upstream
* bumped checksums
* **Fix01:** irrlichtmt fails to install on Mac OS 10.6 - ref <https://trac.macports.org/ticket/66439>
* **Fix02:** minetest arm64 support - ref <https://trac.macports.org/ticket/66600>

###### Type(s)

- [X] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.7.2 20G1020 x86_64
Command Line Tools 13.2.0.0.1.1638488800

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by Zweihorn** [comment]
I took the liberty to provide this as **a little courtesy** to a good teacher ...

**Comment by l2dy** [comment]
* Make sure you could build minetest with this version of irrlichtmt.
* Please follow the [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages) instead of using "update MT9".
* if there is an ABI break, you would need to bump revision of the minetest port as well.

**Comment by Zweihorn** [comment]
THX and I appreciate this.

> * Make sure you could build minetest with this version of irrlichtmt.
> 
First things thirst I thought but I see your point.

>     * Please follow the [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages) instead of using "update MT9".
> 
First: What? - Second: Ah yes, my mishap. The "MT9" was the trailer to "irrlichtmt...9" but quite misleading. Sorry.

Reading (again) the a.m. Guidelines helped:
 1 Subject _(short)_
 2  Include the most important information _(but concentrate on this)_
 **3  Be specific.** Avoid vague subjects like "Update to latest version" or "Fix the build". For example, if you are updating a port to a new upstream version, mention the version number. _(be specific means: avoid ambiguity)_
 **4 List any modified** ports. _(and keep blank if there are not any)_

Mea culpa. Will learn and improve.

_Next time_ something more concise like: "irrlichtmt: update"

>     * if there is an ABI break, you would need to bump revision of the minetest port as well.

**Good point.** Wonder what @reneeotten might say to _this rev bump_ but I am happy to oblige if anything with API breaks.

THX again.

**Comment by Zweihorn** [comment]
How to sync with [the "minetest" rev2](https://github.com/macports/macports-ports/pull/17153#issuecomment-1368779244) already in the queue?

@l2dy - IMO this update should be a task specific to  "minetest" rev**3** in due time.

**Comment by l2dy** [comment]
> How to sync with [the "minetest" rev2](https://github.com/macports/macports-ports/pull/17153#issuecomment-1368779244) already in the queue?
> 
> @l2dy - IMO this update should be a task specific to "minetest" rev**3** in due time.

I think you should make a PR with two commits, one updating irrlichtmt and the other bumping revision of minetest (and optionally other changes to the port).

You could do this in your rev2 or rev3 PR, but remember to make the minetest commit on top of irrlichtmt update.

**Comment by Zweihorn** [comment]
Good news apparently:

- https://github.com/minetest/irrlicht/issues/152#issuecomment-1369131242

**Comment by Zweihorn** [comment]
> I think you should make a PR with two commits, one updating irrlichtmt and the other bumping revision of minetest (and optionally include other changes to the port).
> 
> You could do this in your rev2 or rev3 PR, but remember to make the minetest commit on top of irrlichtmt update.

I fear this is new to me and I already destroyed the earlier squash efforts somehow by help of git apparently.

Hold your breath, more chaos to come ...

**Comment by Zweihorn** [comment]
The combined build and install has no problems with the new & amended 'irrlichtmt' API and 'minetest' was installed without any error.

https://github.com/macports/macports-ports/pull/17153#issuecomment-1374555607

**Pull request closed without merging**
