### PR TITLE
maven1, maven2: EOL, mark as unsupported

### PR DESCRIPTION
**Pull request by chrstphrchvz**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
Revised to remove livecheck from `maven2`.

**Comment by chrstphrchvz** [comment]
`maven1` is now `nomaintainer`.

I have opened a port abandoned ticket for `maven2`: https://trac.macports.org/ticket/58861

**Comment by pmetzger** [comment]
LGTM.

**Comment by chrstphrchvz** [comment]
I think this can be merged now.

**Pull request merged**
