### PR TITLE
libtorrent-devel, rtorrent-devel: update to 20230316

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

-devel ports have not been updated for years.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.2.1
Xcode 15.2

macOS 10.6
Xcode 3.2

P. S. `rtorrent-devel` wants a non-default variant of `curl`, I am not sure such a thing will work on CI. It does build without that still, however. If this fails, I could first comment that line out, confirm the build, then add it back with skip ci.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Yeah, it cannot pass CI this way:
```
  DEBUG: curl is installed with the following variants: +http2+ssl
  DEBUG:   required: ares, forbidden: 
  DEBUG:   rejected, because required variant ares is missing
  Error: Failed to configure rtorrent-devel: curl must be installed with +ares.
  DEBUG: Error code: NONE
  DEBUG: Backtrace: curl must be installed with +ares.
      while executing
  "$pre $targetname"
```

**Comment by barracuda156** [comment]
@herbygillot Could you advise me how to proceed here? Existing port of `rtorrent-devel` required `curl` to be installed with `+ares`. This breaks CI, since non-default variants are not allowed to depend on by default.

I have commented out that requirement now, just to make CI pass (that variant is not needed to build `rtorrent`). The only way I see now is to restore it back with `skip ci`, then the history of successful CI is still there. However, we will have two silly commits :) 

Or maybe you could manually merge two commits from here, dropping the one that is CI-related?

**Comment by pmetzger** [comment]
@barracuda156 I presume this is not ready to commit.

**Comment by barracuda156** [comment]
@pmetzger I can drop allow-CI commit and set skip ci, and then it can be merged. Everything builds, I just need someone to take care of this once I set it to skip ci. (I explained the reason above.)

**Comment by reneeotten** [comment]
> @herbygillot Could you advise me how to proceed here? Existing port of `rtorrent-devel` required `curl` to be installed with `+ares`. This breaks CI, since non-default variants are not allowed to depend on by default.

if it needs a non-default variant then indeed it will never pass the CI; that's expected and there is nothing you can do about. So please restore the `require_active_variants` statement as is required (i.e., drop the second commit). I'll merge the PR after that.

**Comment by barracuda156** [comment]
@reneeotten Thank you, will do it now.

**Pull request merged**
