### PR TITLE
libsvm: update to version 3.32

### PR DESCRIPTION
**Pull request by nilason**
#### Description

The version update follows a general overhaul of the port and:
- python subports replaces the python variants
- the tools variant is now included by default
- the java variant has been dropped

This library is a very light-weight library. Now, by default it remains so.
I dropped the java variant and dependencies, for the time being.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.6 22G120 arm64
Xcode 15.0 15A240d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
@nilason thanks for the update! I haven't checked whether the changes you are proposing here affect ports that currently depend on it (see https://ports.macports.org/port/libsvm/details/). I see there, for example, some pyXY ports that depend on this but you do remove earlier versions in your proposed change.
Did you do the usual due diligence to make sure that this doesn't brake anything?

**Comment by nilason** [comment]
There are three ports depending on libsvm: `orfeotoolbox`, `php-svm` and `py37-pymvpa`. All hooks up via C API during build. `py37-pymvpa` is broken because of other missing dependencies (see https://trac.macports.org/ticket/68436), but for the other ones I have included a revision bump.

**Comment by nilason** [comment]
Now also `py-pymvpa` works. It needed a separate (unrelated) fix.

**Comment by pmetzger** [comment]
What's the status here?

**Comment by nilason** [comment]
Mergeable as as far as I can tell.

**Pull request merged**
