### PR TITLE
MenuMeters: update to 1.9.6

### PR DESCRIPTION
**Pull request by myint**
This version supports APFS, which is the default in High Sierra.

### CODE REVIEW

**Comment by raimue** [comment]
Build errors with Xcode 6 were the following and a few more of the same kind:

```
CompileC build/MenuMeters.build/Release/MenuMetersApp.build/Objects-normal/x86_64/MenuMeterDefaults.o Common/MenuMeterDefaults.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_aqua_MenuMeters/MenuMeters/work/MenuMeters-1.9.6
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/xc/thgw2mxx7_5gpx3k9f87szt00000gp/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DELCAPITAN=1 -DNS_BLOCK_ASSERTIONS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wno-deprecated-declarations -mmacosx-version-min=10.10 -fvisibility=hidden -Wno-sign-conversion -iquote /opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_aqua_MenuMeters/MenuMeters/work/MenuMeters-1.9.6/build/MenuMeters.build/Release/MenuMetersApp.build/MenuMetersApp-generated-files.hmap -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_aqua_MenuMeters/MenuMeters/work/MenuMeters-1.9.6/build/MenuMeters.build/Release/MenuMetersApp.build/MenuMetersApp-own-target-headers.hmap -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_aqua_MenuMeters/MenuMeters/work/MenuMeters-1.9.6/build/MenuMeters.build/Release/MenuMetersApp.build/MenuMetersApp-all-target-headers.hmap -iquote /opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_aqua_MenuMeters/MenuMeters/work/MenuMeters-1.9.6/build/MenuMeters.build/Release/MenuMetersApp.build/MenuMetersApp-project-headers.hmap -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_aqua_MenuMeters/MenuMeters/work/MenuMeters-1.9.6/build/Release/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_aqua_MenuMeters/MenuMeters/work/MenuMeters-1.9.6/build/MenuMeters.build/Release/MenuMetersApp.build/DerivedSources/x86_64 -I/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_aqua_MenuMeters/MenuMeters/work/MenuMeters-1.9.6/build/MenuMeters.build/Release/MenuMetersApp.build/DerivedSources -Wall -Werror -Wshorten-64-to-32 -F/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_aqua_MenuMeters/MenuMeters/work/MenuMeters-1.9.6/build/Release -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/PrivateFrameworks -include /var/folders/xc/thgw2mxx7_5gpx3k9f87szt00000gp/C/com.apple.DeveloperTools/6.4-6E35b/Xcode/SharedPrecompiledHeaders/MenuMeters-auonbsyyvhjgrfgdfftmklhgcyax/MenuMeters.pch -MMD -MT dependencies -MF /opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_aqua_MenuMeters/MenuMeters/work/MenuMeters-1.9.6/build/MenuMeters.build/Release/MenuMetersApp.build/Objects-normal/x86_64/MenuMeterDefaults.d --serialize-diagnostics /opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_aqua_MenuMeters/MenuMeters/work/MenuMeters-1.9.6/build/MenuMeters.build/Release/MenuMetersApp.build/Objects-normal/x86_64/MenuMeterDefaults.dia -c /opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_aqua_MenuMeters/MenuMeters/work/MenuMeters-1.9.6/Common/MenuMeterDefaults.m -o /opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_aqua_MenuMeters/MenuMeters/work/MenuMeters-1.9.6/build/MenuMeters.build/Release/MenuMetersApp.build/Objects-normal/x86_64/MenuMeterDefaults.o
/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_aqua_MenuMeters/MenuMeters/work/MenuMeters-1.9.6/Common/MenuMeterDefaults.m:839:37: error: expected ')'
                                                  (__bridge CFPropertyListRef _Nullable)([NSNumber numberWithDouble:value]),
                                                                              ^
/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_aqua_MenuMeters/MenuMeters/work/MenuMeters-1.9.6/Common/MenuMeterDefaults.m:839:9: note: to match this '('
                                                  (__bridge CFPropertyListRef _Nullable)([NSNumber numberWithDouble:value]),
                                                  ^
...
```

I guess the compiler in Xcode 6 is too old to know about `_Nullable` and thus produces this error. Can be ignored safely, but the Xcode requirement for macOS 10.10 Yosemite (Darwin 14) could be added using the xcodeversion port group:

```
PortGroup xcodeversion 1.0

minimum_xcodeversions {14 7.0}
```

**Comment by myint** [comment]
After I added @raimue's suggestion, it outputs a more helpful message [now](https://paste.macports.org/bca16449a56c):

```
Error: On macOS 10.10, MenuMeters @1.9.6 requires Xcode 7.0 or later but you have Xcode 6.4.
```

(It might be cool if Travis could avoid flagging these as failed builds.)

**Comment by raimue** [comment]
I don't think there is a way to flag a build as "known to fail". We have similar problems for ports that take too long and run into the 50 minute time limit on Travis...

Thanks for the pull request. I pushed it after fixing the commit message on the second commit to include the port name.

**Comment by ryandesign** [comment]
But wait, @raimue, you also removed the requirement that macOS 10.10 or later be used. So now users of macOS 10.9 and earlier will receive a less-intelligible error message if they try to install the port. The lines you removed should be put back.

**Comment by myint** [comment]
Yeah, I removed the OS check since it was also added to avoid a compile error. We can put it back.

**Comment by raimue** [comment]
@ryandesign Thanks for noticing. I restored the macOS version check.

**Pull request closed without merging**
