### PR TITLE
libressl-devel: revision 1 to Portfile, improve livecheck.

### PR DESCRIPTION
**Pull request by artkiver**
* closes https://trac.macports.org/ticket/66568

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 13.1 22C65 arm64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by herbygillot** [comment]
Please review: a change to the regular `libressl` `Portfile` snuck in alongside the `libressl-devel` change in this latest commit.

**Comment by artkiver** [comment]
> Please review: a change to the regular `libressl` `Portfile` snuck in alongside the `libressl-devel` change in this latest commit.

Yeah, I noticed that. I have no idea why. I attempted to delete that in the PR, hopefully that was successful?

**Comment by herbygillot** [comment]
Here's one way you can undo this.

1. You'll need to undo the delete attempt, that didn't help:
```bash
$ git checkout libressl-devel.livecheck.3.7.0
$ git reset --hard HEAD^1
# resets the branch to the commit 1 previous from the front-most commit - so rewinding it down one commit
```

2. Checkout a previous copy of the `libressl` Portfile, undoing any changes to it:
```bash
$ git checkout HEAD^1 ../../security/libressl/Portfile
```
If this succeeds, you should see the `libressl` Portfile show up as changed in `git status`

3. If you've successfully done the above, you can add the `libressl` Portfile and amend the commit to cancel out the change to `libressl`:
```bash
$ git add ../../security/libressl/Portfile
$ git commit --amend
```

When all done, verify that you only have the change for `libressl-devel` when you look at `git status`

If everything looks good, force push to your Github repo.

**Review by artkiver — COMMENTED** [review]
Removed extraneous security/libressl/Portfile change, since I only intended this PR to relate to the modifications to security/libressl-devel/Portfile.

**Comment by artkiver** [comment]
So, following your instructions.

When I run git commit --amend I see:

#
# Changes to be committed:
#       modified:   ../../perl/p5-log-dispatch-array/Portfile

So, that doesn't seem consistent.

I am kind of past the point of throwing up my hands. This is consistent with the sorts of problems I have run into repeatedly in the past, and more or less when I decided it's better to delete all my local branches, delete my GitHub repo, fork all over again and start from scratch.

**Comment by herbygillot** [comment]
You don't have to delete the entire rep. You can simply delete the branch, go back to `master`, update it from origin (from the official MacPorts repo), then just creating a new PR branch from the fresh master and making this one commit once again.

**Comment by artkiver** [comment]
> You don't have to delete the entire repo. You can simply delete the branch, go back to `master`, update it from origin (from the official MacPorts repo), then just creating a new PR branch from the fresh master and making this one commit once again.

That seems like another distinct possibility, though it would mean closing this PR and submitting a new one I think? I am OK with that. I want to make sure I am interpreting your suggestion correctly though.

**Comment by herbygillot** [comment]
> > You don't have to delete the entire repo. You can simply delete the branch, go back to `master`, update it from origin (from the official MacPorts repo), then just creating a new PR branch from the fresh master and making this one commit once again.
> 
> That seems like another distinct possibility, though it would mean closing this PR and submitting a new one I think? I am OK with that. I want to make sure I am interpreting your suggestion correctly though.

You actually don't have to.

You would delete the PR branch on your local machine, update your `master`, then create a new PR branch on your local machine with whatever name you want.

Once it looks good, you can force push onto the branch that this PR is referencing.

Let's say you successfully created the branch on your local machine under the name `libressl-devel-livecheck-fix`.

You can overwrite the branch that this PR is referencing using force push:

```
$ git push -f artkiver libressl-devel-livecheck-fix:libressl-devel.livecheck.3.7.0 
```

**Comment by artkiver** [comment]
> > > You don't have to delete the entire repo. You can simply delete the branch, go back to `master`, update it from origin (from the official MacPorts repo), then just creating a new PR branch from the fresh master and making this one commit once again.
> > 
> > 
> > That seems like another distinct possibility, though it would mean closing this PR and submitting a new one I think? I am OK with that. I want to make sure I am interpreting your suggestion correctly though.
> 
> You actually don't have to.
> 
> You would delete the PR branch on your local machine, update your `master`, then create a new PR branch from the updated master on your local machine with whatever name you want.
> 
> Once it looks good, you can force push onto the branch that this PR is referencing.
> 
> Let's say you successfully created the branch on your local machine under the name `libressl-devel-livecheck-fix`.
> 
> You can overwrite the branch that this PR is referencing using force push:
> 
> ```
> $ git push -f artkiver libressl-devel-livecheck-fix:libressl-devel.livecheck.3.7.0 
> ```

I think I clicked the wrong button when I submitted that last comment and it closed the PR anyway.

I submitted a new PR here: https://github.com/macports/macports-ports/pull/17126

My apologies.

You would think since I have been working with git since 2005, and other (D)VCS even earlier, I would have the hang of this, but clearly there are some things which do not seem to be particularly harmonious in my experience.

**Comment by herbygillot** [comment]
No need to apologize.  git can be a bit opaque, and it doesn't have the best user experience.

The important concepts are to understand that there are 3 repos at play here: your local on-disk repo, your personal GH repo, and the official MacPorts repo, and each can have any collection of branches.

Even within solely your local repo, you can destroy, weave together, rewind, merge together branches as you please.

Next important concept is that a Github pull request _references_ a particular branch to be merged to master, and that reference will usually point to the PR branch you have in your personal Github repo.

So you can force push any branch you have locally onto that referenced branch to update the PR.

So this means getting the hang of commands such as `fetch`, `rebase` and `push` while understanding how each command references the "remote" (which is the name for a non-local repo), and the branch references. The syntax isn't consistent between git subcommands, so that adds to the confusion.

**Pull request closed without merging**
