### PR TITLE
py-pyobjc-*: update to 5.1.2

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR updates ```py-pyobjc``` and the frameworks currently available in MacPorts to version 5.1.2.

I used the Portfile of ```py-pyobjc```, most recently updated by @ryandesign, as the basis for the Frameworks and made the Portfiles as similar as possible. That is, I copied the code related to ```sdkroot``` and macOS version check into the framework ports. I am not 100% sure the SDKROOT stuff is needed, but I figure it doesn't hurt either...

Additional changes include:
- removed unused/obsolete patches
- add py37 subports were not yet present
- wrappers do not include documentation anymore
- update homepage
- use ```python.rootname``` to simplify livecheck / master_sites

We could discuss on the mailinglist / Trac whether including all the frameworks (in a vein similar to 9f7482c08397c12d53c25a6d365e10d729407282) would be beneficial, but for  now I think this should address the current issues (see: [ticket 57889](https://trac.macports.org/ticket/57889)).

I think this all works as intended, but please do NOT merge before someone (@ryandesign , @jmroot , @danchr , ..?) leaves an opinion!

###### Tested on

macOS 10.14.2 18C54
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`? N/A
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
@ryandesign sure - can I just do that with ```depends_build {}```, correct?

**Comment by ryandesign** [comment]
The same way that it's already clearing `depends_lib`: just put `depends_build` on a line by itself with no arguments.

**Comment by reneeotten** [comment]
okay, done (sorry, I should have read better... the last question was a bit stupid....)!

**Comment by pmetzger** [comment]
LGTM. I'll merge. Thanks, @reneeotten!

**Pull request merged**
