### PR TITLE
btrfs-progs: delete abandoned port

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Port has never been updated since being submitted in 2009. No dependents.
Closes: https://trac.macports.org/ticket/64196
Closes: https://trac.macports.org/ticket/64299

###### 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
**Do not merge before maintainer timeout.**

I am proposing this port be deleted (see my [comment on ticket 64196](https://trac.macports.org/ticket/64196#comment:1) for some reasons why) rather than be kept and made `nomaintainer`.

I believe the maintainer’s GitHub handle is @0xffea; mentioning them in case of comment.

**Comment by pmetzger** [comment]
I don't see the portfile in the list of removed files?

**Comment by pmetzger** [comment]
BTW, arguably, if updated, this would be useful; as I understand it, it would let you create and manipulate btrfs file system images. That said, without a maintainer, it's going to be hard to keep it working.

**Comment by chrstphrchvz** [comment]
> I don't see the portfile in the list of removed files?

Fixed; I thought I had removed the btrfs-progs directory rather than just the files directory.

**Comment by chrstphrchvz** [comment]
> BTW, arguably, if updated, this would be useful; as I understand it, it would let you create and manipulate btrfs file system images. That said, without a maintainer, it's going to be hard to keep it working.

btrfs-progs is just the userspace offline maintenance utilities, so its usefulness might also be limited by the lack of a btrfs driver for macOS to actually interact with files. I think one is probably better off using a Linux virtual machine even if just for btrfs-progs functionality.

**Comment by pmetzger** [comment]
It's been a while now. How much longer should we wait before committing?

**Comment by chrstphrchvz** [comment]
I would say this has waited long enough and would be okay to merge now.

**Pull request merged**
