### PR TITLE
gnome-settings-daemon: update to 3.38.2

### PR DESCRIPTION
**Pull request by mohd-akram**
#### Description

Closes: https://trac.macports.org/ticket/67749

###### Tested on
macOS 13.4.1 22F770820d x86_64
Xcode 14.3.1 14E300c

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
I'll try to take a closer look at this - and build/test locally - when I can find some time.

**Comment by pmetzger** [comment]
@mascguy Can this be merged?

**Comment by mascguy** [comment]
> @mascguy Can this be merged?

I'll try to make some time to look at this PR, along with https://github.com/macports/macports-ports/pull/19460, over the next day or two. (Shouldn't require much work, apart from some local testing and validation.)

**Comment by pmetzger** [comment]
@mascguy Thank you!

**Comment by mascguy** [comment]
Mohamed, you were close, but several additional deps were needed:

* Build: `gettext`
* Lib: `gettext-runtime`, `glib2`

Technically those are included via others deps like `gtk3`, but this port directly depends on all of those... so better to add them.

Otherwise, looks good. Great work!

**Pull request merged**
