### PR TITLE
miniserve: New port

### PR DESCRIPTION
**Pull request by judaew**
Version: 0.14.0

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.2.3 20D91
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by cjones051073 — COMMENTED** [review]
I really wish cargo based ports like this could be constructed to avoid the huge stream of nickpick errors, as it makes reviewing the changes irritating ...

**Comment by herbygillot** [comment]
Well they have the same problems that golang ports with vendored deps do.

Perhaps macports-base needs a relaxed-checksums option which can be added to both the `cargo` and `golang` portgroups.

**Comment by cjones051073** [comment]
I wouldn’t support that really. We have plenty of these ports that do correctly give all required checksums, e.g.

https://github.com/macports/macports-ports/blob/master/security/gosec/Portfile

i assume maintainers of these ports have means, scripts or similar, to generate these vendor entries ? Surely they aren’t handwritten, in which case adding all the checksums is not really an additional burdon.

**Comment by judaew** [comment]
@cjones051073 Gosec's project on Go and there using `go2port` to collect all the checksums. It still throws warnings anyway, e. g.:

https://github.com/macports/macports-ports/blob/master/sysutils/git-chglog/Portfile

```console
$ port lint --nitpick gosec
--->  Verifying Portfile for gosec
Warning: go-yaml-yaml-9f266ea9e77c.tar.gz - missing recommended checksum type: sha256
Warning: go-yaml-yaml-9f266ea9e77c.tar.gz - missing recommended checksum type: size
Warning: go-yaml-yaml-9f266ea9e77c.tar.gz - missing recommended checksum type: rmd160
Warning: go-yaml-yaml-9f266ea9e77c.tar.gz - missing recommended checksum type: size
Warning: go-yaml-yaml-9f266ea9e77c.tar.gz - missing recommended checksum type: rmd160
Warning: go-yaml-yaml-9f266ea9e77c.tar.gz - missing recommended checksum type: sha256
...
--->  0 errors and 162 warnings found.
```

**Pull request merged**
