### PR TITLE
json-mode.el: Submission

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.1 21C52 x86_64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
I don't get why one would use this over using the built in Emacs package manager for the same functionality. I use both Emacs and MacPorts, and as much as I love MacPorts, it is not the right tool for every job.

**Comment by essandess** [comment]
Any constructive comment on this PR, rather than opinions on personal package manger choices?

**Comment by mascguy** [comment]
> TBH, I haven't looked much at the details because, as I said, I don't think it's a good idea. There are many thousands of Emacs packages. If we package this, how many more are we going to have to package? Why package json-mode and not (say) helm or slime or avy or the thousands of others?
> 
> Emacs packages are designed at this point to be managed and updated by the Emacs package infrastructure using Elpa/Melpa/etc. Alternative sources of Emacs packages are part of the mechanism so you're not beholden to the repositories they manage, and indeed, Melpa is one such mechanism already. It's a good system, well designed for Emacs, and integrates in to Emacs itself via the package management tools. I don't see why we would compete with it. Are we signing up to duplicate the whole infrastructure for thousands of packages?

Unfortunately I can appreciate both sides here, so I can't provide a tie-breaking vote.

Anyone else... thoughts?

**Comment by essandess** [comment]
I also see @pmetzger's side, but also appreciate having a few Emacs options available to install within MacPorts. I'm still on the fence.

**Pull request closed without merging**
