### PR TITLE
qt5-qtwebengine: update to 5.15.9

### PR DESCRIPTION
**Pull request by chrstphrchvz**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [x] security fix

###### Tested on

To be tested on:
macOS 12.3.1 x86_64
Xcode 13.3

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
I am currently building this on x86_64.

Can someone with an Apple Silicon Mac please try this PR?

**Comment by chrstphrchvz** [comment]
Already running into the problem where Xcode 13.3 clang has `-Werror=unused-but-set-variable` by default.

```
:info:build FAILED: obj/third_party/harfbuzz-ng/harfbuzz_source/hb-subset-cff1.o 
:info:build ccache ../../../../../../../../../../../../Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -MMD -MF obj/third_party/harfbuzz-ng/harfbuzz_source/hb-subset-cff1.o.d -DHAVE_OT -DHAVE_FREETYPE -DHAVE_ICU -DHAVE_ICU_BUILTIN -DHAVE_INTEL_ATOMIC_PRIMITIVES -DHAVE_ROUNDF -DHB_NO_MMAP -DHB_NO_RESOURCE_FORK -DHB_NO_SUBSET_LAYOUT -DHB_NO_FALLBACK_SHAPE -DHB_NO_UCD -DHB_NO_METRICS -DHB_NO_WIN1256 -DU_DISABLE_VERSION_SUFFIX=0 -DOFFICIAL_BUILD -DTOOLKIT_QT -D_LIBCPP_HAS_NO_ALIGNED_ALLOCATION -DCR_XCODE_VERSION=1330 -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=0 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DFT_CONFIG_MODULES_H=\"freetype-custom/freetype/config/ftmodule.h\" -DFT_CONFIG_OPTIONS_H=\"freetype-custom/freetype/config/ftoption.h\" -DPDFIUM_REQUIRED_MODULES -DCHROMIUM_RESTRICT_VISIBILITY -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -Igen -I../../3rdparty/chromium -I../../3rdparty/chromium/third_party/freetype/include -I../../3rdparty/chromium/third_party/freetype/include/freetype-custom -I../../3rdparty/chromium/third_party/freetype/src/include -I../../3rdparty/chromium/third_party/harfbuzz-ng/src/src -I../../3rdparty/chromium/third_party/icu/source/common -I../../3rdparty/chromium/third_party/icu/source/i18n -fno-strict-aliasing -fstack-protector -Wno-unknown-attributes -Wno-unknown-pragmas -Wno-unknown-warning-option -fcolor-diagnostics -fmerge-all-constants -arch x86_64 -fno-omit-frame-pointer -g0 -isysroot ../../../../../../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=12.0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wall -Wno-unused-variable -Wno-misleading-indentation -Wunguarded-availability -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-max-tokens -O3 -Wno-parentheses-equality -Wno-tautological-compare -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=c++14 -fno-trigraphs -Wno-trigraphs -stdlib=libc++ -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../3rdparty/chromium/third_party/harfbuzz-ng/src/src/hb-subset-cff1.cc -o obj/third_party/harfbuzz-ng/harfbuzz_source/hb-subset-cff1.o
:info:build ../../3rdparty/chromium/third_party/harfbuzz-ng/src/src/hb-subset-cff1.cc:405:33: error: variable 'supp_size' set but not used [-Werror,-Wunused-but-set-variable]
:info:build     unsigned int  size0, size1, supp_size;
:info:build                                 ^
:info:build 1 error generated.
```

**Comment by chrstphrchvz** [comment]
Built qt5-qtwebengine and qt5-qtwebengine-docs on 12.3 Intel with Xcode 13.3. Tested with simplebrowser.py from py39-pyside2:

Screen Shot 2022-04-06 at 5 23 03 PM

**Comment by abey79** [comment]
Works for me, though i got the following output during the configuring step:

```
--->  Configuring qt5-qtwebengine
objc[40037]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x201291eb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10699c4f8). One of the two will be used. Which one is undefined.
objc[40037]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x201291f00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10699c548). One of the two will be used. Which one is undefined.
objc[40037]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x201291f50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10699c598). One of the two will be used. Which one is undefined.
objc[40037]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x201291fa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10699c5e8). One of the two will be used. Which one is undefined.
objc[40037]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x201291ff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10699c638). One of the two will be used. Which one is undefined.
objc[40037]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x201292040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10699c688). One of the two will be used. Which one is undefined.
objc[40038]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x201291eb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x106abc4f8). One of the two will be used. Which one is undefined.
objc[40038]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x201291f00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x106abc548). One of the two will be used. Which one is undefined.
objc[40038]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x201291f50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x106abc598). One of the two will be used. Which one is undefined.
objc[40038]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x201291fa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x106abc5e8). One of the two will be used. Which one is undefined.
objc[40038]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x201291ff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x106abc638). One of the two will be used. Which one is undefined.
objc[40038]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x201292040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x106abc688). One of the two will be used. Which one is undefined.
2022-04-09 14:06:26.443 xcodebuild[40038:10687485] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-04-09 14:06:26.446 xcodebuild[40038:10687485] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
xcodebuild: error: SDK "macosx12" cannot be located.
xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk macosx12 -find ld 2> /dev/null' failed with exit code 16384: (null) (errno=No such file or directory)
xcrun: error: unable to find utility "ld", not a developer tool or in PATH
```

The last ones might be of greater significance than the first one, which I have been having for a while in various circumstances.

**Comment by sumirati** [comment]
Compiled on MBP 2021 w/ M1 Pro, running MacOS 12.3.1 and Xcode 13.3

But got the same hints as @abey79 during the configure stage - and not only for this port, but many

**Comment by reneeotten** [comment]
@chrstphrchvz is this ready to be merged or are there still outstanding concerns and/or things to test further?

**Comment by chrstphrchvz** [comment]
I believe this is ready to merge.

**Pull request merged**
