### PR TITLE
ncmpc: update to 0.51

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
> @barracuda156 please check the failure on macOS 13

I think we saw this, some bug in Apple clang:
```
  Undefined symbols for architecture x86_64:
    "std::exception_ptr::__from_native_exception_pointer(void*)", referenced from:
        std::exception_ptr std::make_exception_ptr[abi:fe190100]<std::runtime_error>(std::runtime_error) in libclient.a(.._event_net_ConnectSocket.cxx.o)
        std::exception_ptr std::make_exception_ptr[abi:fe190100]<std::__1::system_error>(std::__1::system_error) in libclient.a(.._event_net_ConnectSocket.cxx.o)
    "___cxa_init_primary_exception", referenced from:
        std::exception_ptr std::make_exception_ptr[abi:fe190100]<std::runtime_error>(std::runtime_error) in libclient.a(.._event_net_ConnectSocket.cxx.o)
        std::exception_ptr std::make_exception_ptr[abi:fe190100]<std::__1::system_error>(std::__1::system_error) in libclient.a(.._event_net_ConnectSocket.cxx.o)
  ld: symbol(s) not found for architecture x86_64
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
  Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_audio_ncmpc/ncmpc/work/build" && /opt/local/bin/ninja -j4 -v 
```
I can try switching it to LLVM clang.

**Comment by barracuda156** [comment]
@kencu Ken, do you remember what was the fix for this kind of error on Ventura?

**Comment by kencu** [comment]
I did look in the llvm github tree to see how the visibility of that symbol was guarded, but didn't see the explanation right away at least.

presumably it is not in the libc++ included with macOS-13 when the compiler thinks it should be. But that's all I got for you at the moment.

**Comment by barracuda156** [comment]
@reneeotten Fixed now.

**Pull request merged**
