### PR TITLE
libvpx: remove unused changes to configure.sh

### PR DESCRIPTION
**Pull request by johannkoenig**
#### Description

The other changes to configure.sh are only used when
autodetecting the OS. Because the Macports script passes
in the target, these changes had no effect.

Remove them to keep future updates simple.

The only change necessary is in 'configure' which
is required to allow --target=<arch>-darwin-gcc

An alternative would be to change the macports script
to use --force-target=<arch>-darwin-gcc which would
skip the validation of the target. This would reduce the
number of patches Macports needs to maintain.
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

Untested

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by johannkoenig** [comment]
> Thankyou for your input, and welcome to macports.
> 
> Your commit message though does not follow our guidelines. Please change it to have the form ‘portname: message’
> 
> Also, in future please do not just delete the templated information provided in the description, when you first open a PR. It is there for a reason, and you should follow it and fill it out correctly. Part of this is infact a check box to say you followed our commit guidelines ;)

Woops! Sorry about that. Updated the PR.

**Comment by cjones051073** [comment]
> > Thankyou for your input, and welcome to macports.
> > Your commit message though does not follow our guidelines. Please change it to have the form ‘portname: message’
> > Also, in future please do not just delete the templated information provided in the description, when you first open a PR. It is there for a reason, and you should follow it and fill it out correctly. Part of this is infact a check box to say you followed our commit guidelines ;)
> 
> Woops! Sorry about that. Updated the PR.

Thanks, but you have only changed the PR title. You need to change the message associated with he commit as well.

**Comment by johannkoenig** [comment]
> Thanks, but you have only changed the PR title. You need to change the message associated with the commit as well.

Urgh sorry! I think I have it fixed now? Apologies, I'm new to github.

**Comment by johannkoenig** [comment]
I'm not sure how to clear the "1 change requested" bit. It looks like my force-push to update the commit message left a dangling link?

**Comment by kencu** [comment]
There is another slightly older PR down the queue doing something similar...

**Comment by cjones051073** [comment]
> I'm not sure how to clear the "1 change requested" bit. It looks like my force-push to update the commit message left a dangling link?

Thats normal. Only those requesting the changes can clear them.

**Comment by johannkoenig** [comment]
Thanks! Do I have to do anything to merge this?

**Comment by mf2k** [comment]
We were waiting for @dbevans to commit this.

**Pull request merged**
