### PR TITLE
nethack: update master_sites and livecheck

### PR DESCRIPTION
**Pull request by townba**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.3 22E252 arm64
Xcode 14.3 14E222b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?  *(no existing tickets)*
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`? *(no existing tests)*
- [ ] tried a full install with `sudo port -vst install`? *(`-t` fails on Ventura: https://trac.macports.org/ticket/66358)*
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
@townba what's the reason behind this change as it appears that the actual files are the same (otherwise you would have needed to change the `checksum`). If you want to change and use GitHub (right now you only change the `livecheck` to that) then I would recommend to do so upon the next update and use the `github` PG.

**Comment by townba** [comment]
The reason behind the change is that livecheck is currently wrong. [SourceForge doesn't have releases after 3.6.2](https://sourceforge.net/projects/nethack/files/nethack/) and the current Portfile is interpreting the version incorrectly (362 instead of 3.6.2), so it thinks the older version is a later version.

```
$ port livecheck nethack
nethack seems to have been updated (port version: 3.6.7, new version: 362)
```

I was trying to change as little as possible to get livecheck to work. If you'd rather not change it now, what about disabling it?

**Comment by jflude** [comment]
+1 for dropping `sourceforge`, which the DevTeam hasn't used for 4+ years, and +1 for `livecheck` now they are releasing more often

**Comment by reneeotten** [comment]
okay, let's merge this then. Please do make sure to switch to GitHub completely with the next release (i.e., use the "github" PG and its features)

**Pull request merged**
