### PR TITLE
4ti2, QSopt_ex, TOPCOM: move to libexec

### PR DESCRIPTION
**Pull request by catap**
#### Description

Cleanup `${prefix}/bin` from a lot of wired files like `B_A` or `B_D_center`.

###### Type(s)

- [x] enhancement

###### Tested on
``
macOS 12.6.3 21G419 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
I am personally not a fan of installing ports in a non-standard location if there is no absolute need for it. 

Just moving "weird" files from one place to another is not a good reason IMHO.

**Comment by catap** [comment]
@reneeotten unfortently it isn't just "wired" files. Such naming in math ports creates conflicts.

For example `latte-int` instals application with name `count` and Arch Linux renames it to avoid conflicts: https://gitlab.archlinux.org/archlinux/packaging/packages/latte-integrale/-/blob/main/PKGBUILD

Right now `4ti2` installs `${prefix}/bin/output` and `${prefix}/bin/walk` which is good candidate for conflict :)

**Comment by reneeotten** [comment]
Sure and that would be a fine approach, but that is not what you are doing here. I am not convinced that moving ports (that have no conflicts at the moment) to "libexec" has merit. I'd suggest making your case on the dev list and get consensus before starting to do this.

**Comment by catap** [comment]
@reneeotten before I've started to do that, we simple "removes" some binaries: https://github.com/macports/macports-ports/commit/f7c35c544b27282af8d8f2eb61275c39734cd248

**Comment by catap** [comment]
For example `TOPCOM` install right now an application with name `check` which is also good candidate to not so unique name.

**Comment by catap** [comment]
It was a draft for more than 6 mothns. Seems useless until someone complain to it => close.

**Pull request closed without merging**
