### PR TITLE
swi-prolog-devel: Updated to version 9.3.3

### PR DESCRIPTION
**Pull request by JanWielemaker**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.2.1 23C71 arm64
Xcode 15.3 15E204a

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Fails again trying to resolve www.swi-prolog.org :cry:    I've initiated migrating to a new ISP.  For now, I'm afraid that simply restarting should suffice.   Sorry for the inconvenience.

**Comment by JanWielemaker** [comment]
Hmm.   Still saying   _Error: Failed to fetch swi-prolog-devel: Could not resolve host: www.swi-prolog.org_.    The host does resolve in general, although there are relatively frequent hiccups of the ISPs DNS, none have been reported in the last days.    What did change is that the host now also resolves as IPv6.   That works fine.  I can download both using IPv4 and IPv6.   Could it be there is an issue at the Macport end?

**Comment by reneeotten** [comment]
I restarted them again, let's see how this goes. I don't think anything has changed on MacPorts end.

**Comment by JanWielemaker** [comment]
> I restarted them again, let's see how this goes. I don't think anything has changed on MacPorts end.

Same problem :(   Thursday March 21 swi-prolog.org switches to a new domain registrar.     I propose we wait for that.    I do have the impression something else is wrong though as there are normally a lot of complaints if DNS is not working properly.

**Comment by reneeotten** [comment]
@JanWielemaker it worked now after restarting the CI - so I'll merge. Thanks!

**Comment by JanWielemaker** [comment]
> It worked now after restarting the CI - so I'll merge. Thanks!

swi-prolog.org was moved to a new domain registrar yesterday.    Hopefully this problem is gone.   Thanks for your patience.

**Pull request merged**
