### PR TITLE
tinc-devel: update to 1.1.pre16

### PR DESCRIPTION
**Pull request by joshin42**
Updated tinc-devel to 1.1pre16.

### CODE REVIEW

**Comment by joshin42** [comment]
Okay, hope this is more acceptable. Still not sure about the "size" parameter - or what the heck I'm doing.

**Comment by mf2k** [comment]
`size` is documented in the guide https://guide.macports.org/#reference.phases.checksum.

**Comment by joshin42** [comment]
Fair enough, but I didn't sign up to maintain the package or bring it up to spec. I changed what is there to reflect the latest version. 

I understand your dilemma, but I've put enough time in to this. You can accept my pull request as it is, or reject it.

**Comment by pmetzger** [comment]
Thanks for your contribution. However, we do have quality control rules about pull requests. If you prefer not to fix a very minor issue so your pull request can be accepted, that is of course your prerogative, but it seems a bit unreasonable to me to refuse to add one line to the file when you've been informed that's what we'd prefer. If you want to close your pull request, that's unfortunate, but that's up to you.

**Comment by kencu** [comment]
5b9395f61cb1759051b2d1fca9d5c6046f9b4bf6

**Pull request closed without merging**
