### PR TITLE
webkit2-gtk-devel: add enhancements to WebKitGTK+

### PR DESCRIPTION
**Pull request by jmercouris**
#### Description
This fixes a few things that help webkit2-gtk-devel more suitable for development.

- [ ] enhancement
- [ ] security fix

@pmetzger 
@kencu 

I no longer have a macOS machine handy, so I can't readily test this.

### CODE REVIEW

**Comment by pmetzger** [comment]
Just for @dbevans and @kencu's benefit, this is apparently a prerequisite for packaging the Nyxt browser for MacPorts (see https://nyxt.atlas.engineer/ )

**Comment by kencu** [comment]
Tricky to test this properly indeed. One successful build, and one failed build that might have simply timed out. The changes look reasonable. Nit point is that we'll need a revbump to get it to happen, but that is trivial for me to add.

I suppose I should check it out and test this on at least one system.... when I originally did these webkit patches I ran builds on every system from 10.6 i386 up, but I'm not in a position to invest that kind of time any longer.

I'll run a build, and if it doesn't fail or crash on use, we'll push this with a revbump.

**Comment by jmercouris** [comment]
Thanks @kencu , let me know how it works for you.

**Comment by kencu** [comment]
10.14 worked OK.

**Pull request merged**
