### PR TITLE
Update @emcrisostomo maintainers line

### PR DESCRIPTION
**Pull request by emcrisostomo**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.3 17D2104
Xcode 9.2 9C40b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by emcrisostomo** [comment]
Hi @pmetzger,

I've updated my information in the `maintainers` line as you suggested here: [https://github.com/macports/macports-ports/pull/1377#issuecomment-370156836](url)

**Comment by pmetzger** [comment]
Cool, and thank you! But I'll note you also altered indentation in your terraform Portfile update. Perhaps you could separate that commit out (and I'll happily do that separately)?

**Comment by emcrisostomo** [comment]
Ah yes, I noticed it was completely off and decided to harmonise it. Ok, I'm going to move that to a separate commit and push again.

**Comment by emcrisostomo** [comment]
@pmetzger Done.

**Comment by pmetzger** [comment]
Merged. And thank you!

**Comment by emcrisostomo** [comment]
Thank you @pmetzger

**Pull request merged**
