### PR TITLE
py-torchtext: Update to version 0.13.0, Add Python 310

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Observers: PR https://github.com/macports/macports-ports/pull/15821 must be merged first, as `py310-spaCy*` ports don't exist yet.

**Comment by mascguy** [comment]
> Observers: PR #15821 must be merged first, as `py310-spaCy*` ports don't exist yet.

Rebased against master, now that PR 15821 has been merged.

**Comment by essandess** [comment]
@mascguy The CI is failing on Python 38 with:
```sh
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/_C.cpython-38-darwin.so, 2): Library not loaded: /opt/local/lib/libzmq.5.dylib
[3649](https://github.com/macports/macports-ports/runs/8027818422?check_suite_focus=true#step:8:3658)
```

This doesn't make any sense to me: https://github.com/macports/macports-ports/blob/0c7f7c966283cd32f7910b3ad4189b667cd189da/python/py-pytorch/Portfile#L106

I'd just as well delete Python 38 from this port if it simplifies integration.

**Comment by essandess** [comment]
I just added an explicit dependency to `zmq` in this Portfile and the CI works now.

All that's left for this transformers chain update is to merge:
* #15814
* #15813
* #15456 after a rebase
* #15601 after a rebase

**Review by mascguy — APPROVED** [review]
CI looks good now, merging.

**Pull request merged**
