### PR TITLE
bootstrap.sh: force VM clock to sync over NTP

### PR DESCRIPTION
**Pull request by chrstphrchvz**
See: https://trac.macports.org/ticket/58800

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

### CODE REVIEW

**Comment by ryandesign** [comment]
Thanks! I'll be interested to see if this helps. I certainly hope it does.

**Comment by chrstphrchvz** [comment]
Here's one example so far: https://travis-ci.org/github/macports/macports-ports/jobs/718804314#L91

**Comment by chrstphrchvz** [comment]
What I now notice from looking at some past logs of builds that errored, the time reported in the log for `sudo ./runner` was often negative, which I think indicates that the system clock synchronized at some point during the build, jumping backward by an amount greater than the time the build took. Examples:

https://travis-ci.org/github/macports/macports-ports/jobs/708074361#L146

https://travis-ci.org/github/macports/macports-ports/jobs/717371920#L226

https://travis-ci.org/github/macports/macports-ports/jobs/717381549#L106

The logs of recent builds which forced an NTP sync by a large amount now instead show a large negative time spent running bootstrap.sh, and negative time offset reported by `ntpdate`, meaning the clock is actually starting ahead rather than behind as I wrote in the bootstrap.sh comment. (There also seems to be a problem viewing the logs for these builds that causes my web browser to hang.)

**Comment by ryandesign** [comment]
> which I think indicates that the system clock synchronized at some point during the build, jumping backward by an amount greater than the time the build took.

I agree.

> (There also seems to be a problem viewing the logs for these builds that causes my web browser to hang.)

> Here's one example so far: https://travis-ci.org/github/macports/macports-ports/jobs/718804314#L91
>
> Edit—another one: https://travis-ci.org/github/macports/macports-ports/jobs/718841851#L55

Those logs certainly make my Safari unhappy, possibly due to their length. `portindex` is reindexing everything:

```
Total number of ports parsed:	24210 
Ports successfully parsed:	24210 
Ports failed:			0 
Up-to-date ports skipped:	0
```

It must think that all of the portfiles are newer than the PortIndex...

**Comment by ryandesign** [comment]
We are seeing some PRs fail to build due to:
```
0.us.pool.ntp.org 68.233.45.146 no UCST response after 5 seconds
```

**Comment by chrstphrchvz** [comment]
A build has failed with `Portfile is from the future` despite the clock syncing back: https://travis-ci.org/github/macports/macports-ports/jobs/719972422
https://paste.macports.org/a706b3dc264a

**Comment by ryandesign** [comment]
And in that PR we again see all portfiles being indexed. Why is that happening? Could the reason why it's doing that be the same as the reason why it thinks the portfile is from the future?

**Comment by chrstphrchvz** [comment]
Another idea might be to use some form of `launchctl unload /System/Library/LaunchDaemons/com.apple.timed` and avoid syncing the clock at all—automatically and manually. Is that worth a try?

**Pull request merged**
