### PR TITLE
epoll-shim, wayland: new ports in devel

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

New port

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
@barracuda156 this fails everywhere:

  meson.build:80:14: ERROR: Dependency "epoll-shim" not found, tried pkgconfig and framework

**Comment by barracuda156** [comment]
@reneeotten Thank you. I have seen the error, will look into that.
It did build locally on Sonoma for me (i.e. not just PowerPC).

**Comment by barracuda156** [comment]
Can’t reproduce the error, hmm. This is a build on Catalina with all ports deactivated first:

```
--->  Applying patches to wayland
--->  Applying 0001-Darwin-fixes-from-owl-compositor.patch
Executing:  cd "/opt/local/var/macports/build/_opt_CatalinaPorts_devel_wayland/wayland/work/wayland-04654ba7b57ccbf583db899a327f8f7000f90546" && /usr/bin/patch -p1 < '/opt/CatalinaPorts/devel/wayland/files/0001-Darwin-fixes-from-owl-compositor.patch'
patching file meson.build
patching file src/connection.c
patching file src/event-loop.c
patching file src/wayland-shm.c
patching file tests/event-loop-test.c
--->  Applying 0002-wayland-os.c-LOCAL_PEERPID-may-not-be-defined.patch
Executing:  cd "/opt/local/var/macports/build/_opt_CatalinaPorts_devel_wayland/wayland/work/wayland-04654ba7b57ccbf583db899a327f8f7000f90546" && /usr/bin/patch -p1 < '/opt/CatalinaPorts/devel/wayland/files/0002-wayland-os.c-LOCAL_PEERPID-may-not-be-defined.patch'
patching file src/wayland-os.c
--->  Applying 0003-os-wrappers-test-F_DUPFD_CLOEXEC-may-not-be-defined.patch
Executing:  cd "/opt/local/var/macports/build/_opt_CatalinaPorts_devel_wayland/wayland/work/wayland-04654ba7b57ccbf583db899a327f8f7000f90546" && /usr/bin/patch -p1 < '/opt/CatalinaPorts/devel/wayland/files/0003-os-wrappers-test-F_DUPFD_CLOEXEC-may-not-be-defined.patch'
patching file tests/os-wrappers-test.c
--->  Configuring wayland
Executing:  cd "/opt/local/var/macports/build/_opt_CatalinaPorts_devel_wayland/wayland/work/wayland-04654ba7b57ccbf583db899a327f8f7000f90546" && /opt/local/bin/meson setup --prefix=/opt/local -Ddocumentation=false -Ddtd_validation=true -Dlibraries=true -Dscanner=true -Dtests=true /opt/local/var/macports/build/_opt_CatalinaPorts_devel_wayland/wayland/work/wayland-04654ba7b57ccbf583db899a327f8f7000f90546 /opt/local/var/macports/build/_opt_CatalinaPorts_devel_wayland/wayland/work/build --wrap-mode=default 
The Meson build system
Version: 1.6.0
Source dir: /opt/local/var/macports/build/_opt_CatalinaPorts_devel_wayland/wayland/work/wayland-04654ba7b57ccbf583db899a327f8f7000f90546
Build dir: /opt/local/var/macports/build/_opt_CatalinaPorts_devel_wayland/wayland/work/build
Build type: native build
Project name: wayland
Project version: 1.21.90
C compiler for the host machine: /usr/bin/clang (clang 12.0.0 "Apple clang version 12.0.0 (clang-1200.0.32.29)")
C linker for the host machine: /usr/bin/clang ld64 609.8
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -fvisibility=hidden: YES 
Has header "sys/prctl.h" : NO 
Has header "sys/procctl.h" : NO 
Has header "sys/ucred.h" : YES 
Checking for function "accept4" : NO 
Checking for function "getpeereid" : YES 
Checking for function "mkostemp" : YES 
Checking for function "posix_fallocate" : NO 
Checking for function "prctl" : NO 
Checking for function "memfd_create" : NO 
Checking for function "mremap" : NO 
Checking for function "strndup" : YES 
Checking whether type "struct xucred" has member "cr_pid" : NO 
Found pkg-config: YES (/opt/local/bin/pkg-config) 0.29.2
Found CMake: /opt/local/bin/cmake (3.29.5)
Run-time dependency epoll-shim found: YES
Library ffi found: YES
Header "sys/signalfd.h" has symbol "SFD_CLOEXEC" with dependency epoll-shim: YES 
Header "sys/timerfd.h" has symbol "TFD_CLOEXEC" with dependency epoll-shim: YES 
Header "time.h" has symbol "CLOCK_MONOTONIC" with dependency epoll-shim: YES 
Checking whether type "struct itimerspec" has members "it_interval", "it_value" with dependency epoll-shim: NO 
Configuring config.h using configuration
Configuring wayland-version.h using configuration
Library expat found: YES
Run-time dependency libxml-2.0 found: YES 2.13.5
Program embed.py found: YES (/opt/local/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12 /opt/local/var/macports/build/_opt_CatalinaPorts_devel_wayland/wayland/work/wayland-04654ba7b57ccbf583db899a327f8f7000f90546/src/embed.py)
Library m found: YES
Run-time dependency threads found: YES
Program nm found: YES (/usr/bin/nm)
Program wayland-egl-symbols-check found: YES (/opt/local/var/macports/build/_opt_CatalinaPorts_devel_wayland/wayland/work/wayland-04654ba7b57ccbf583db899a327f8f7000f90546/egl/wayland-egl-symbols-check)
Library dl found: YES
Dependency threads found: YES unknown (cached)
Dependency threads found: YES unknown (cached)
Library dl found: YES
C++ compiler for the host machine: /usr/bin/clang++ (clang 12.0.0 "Apple clang version 12.0.0 (clang-1200.0.32.29)")
C++ linker for the host machine: /usr/bin/clang++ ld64 609.8
Program sed found: YES (/usr/bin/sed)
Program scanner-test.sh found: YES (/opt/local/var/macports/build/_opt_CatalinaPorts_devel_wayland/wayland/work/wayland-04654ba7b57ccbf583db899a327f8f7000f90546/tests/scanner-test.sh)
Build targets in project: 41
NOTICE: Future-deprecated features used:
 * 0.62.0: {'pkgconfig.generate variable for builtin directories'}

wayland 1.21.90

  User defined options
    documentation : false
    dtd_validation: true
    libraries     : true
    prefix        : /opt/local
    scanner       : true
    tests         : true
    wrap_mode     : default

Found ninja-1.12.1 at /opt/local/bin/ninja
--->  Building wayland
```

**Comment by barracuda156** [comment]
@reneeotten Fixed now.

**Comment by barracuda156** [comment]
@reneeotten @herbygillot Could we merge this now?

**Pull request merged**
