### PR TITLE
net-snmp: update to 5.9

### PR DESCRIPTION
**Pull request by amake**
#### Description

Update net-snmp to 5.9. The previous version was failing to build on Big Sur (see https://trac.macports.org/ticket/61624); 5.9 also fails but I have pulled in some upstream patches to (try to) get it working.

However it's not quite there yet; the build phase ~fails~ failed for me (until I rebuilt perl5.28 post-OS-update) like so:

```
/usr/bin/clang -c   -I/opt/local/var/macports/build/_Users_amake_Code_MacPorts_net_net-snmp/net-snmp/work/net-snmp-5.9/include -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk -arch x86_64 -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -DNETSNMP_REMOVE_U64 -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk -arch x86_64 -Udarwin20 -Ddarwin20=darwin20 -I/opt/local/include -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk -I. -I/opt/local/include -fno-common -DPERL_DARWIN -mmacosx-version-min=10.16 -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk  -fno-strict-aliasing -fstack-protector-strong -I/opt/local/include -DPERL_USE_SAFE_PUTENV -Wformat -O3   -DVERSION=\"5.09\" -DXS_VERSION=\"5.09\"  "-I/opt/local/lib/perl5/5.28/darwin-thread-multi-2level/CORE"   default_store.c
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk' [-Wmissing-sysroot]
In file included from default_store.xs:2:
/opt/local/lib/perl5/5.28/darwin-thread-multi-2level/CORE/perl.h:684:10: fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
1 error generated.
```

The problem seems to be the `MacOSX11.0.sdk`, which doesn't exist for me:

```sh
% ls -al /Library/Developer/CommandLineTools/SDKs/
total 0
drwxr-xr-x  5 root  wheel  160 Dec 15 09:35 .
drwxr-xr-x  5 root  wheel  160 Nov 20 10:30 ..
lrwxr-xr-x  1 root  wheel   14 Dec 15 09:34 MacOSX.sdk -> MacOSX11.1.sdk
drwxr-xr-x  8 root  wheel  256 Dec 15 09:35 MacOSX10.15.sdk
drwxr-xr-x  7 root  wheel  224 Nov 30 21:33 MacOSX11.1.sdk
```

But I can't for the life of me figure out where it's coming from.

This is at the limit of my knowledge/ability, so I hope someone can point me in the right direction or pick up the ball themselves.

###### Type(s)
- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 11.1 20C69
Xcode 12.3 12C33

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
> But I can't for the life of me figure out where it's coming from.

I would think the errant SDK reference is most probably baked into the PERL build.

**Comment by amake** [comment]
> I would think the errant SDK reference is most probably baked into the PERL build.

Wow. I rebuilt my perl5.28 from source and now net-snmp builds correctly.

Are you a wizard?

Do you have a newsletter I can subscribe to?

Seriously though: What does this mean? I suppose I must have had perl5.28 installed before updating to Big Sur 11.1, and no updates to perl5.28 were made since, so I was stuck with the problematic build. How should this be dealt with going forward?

**Comment by kencu** [comment]
the rapid sdk renaming is going to be a huge problem for us due to the many ports that still bake in their build sdk.

**Comment by kencu** [comment]
eg now ruby

https://trac.macports.org/ticket/61899

It will be all the rubies, though.

next will be all the pythons, etc, etc, etc.

worse: when to revbump it? Not everyone has update xcode yet.

there are solutions, but no lovely ones. My fav is to strip out all sdk baking, and sort it out with on the fly SDKROOT usage, like Apple does.

ASAP.

**Comment by ryandesign** [comment]
Yes, ports that bake versioned SDK paths into their installed files, like apparently perl, must not do so; replacing the versioned SDK path with the unversioned SDK path might be reasonable.

**Pull request merged**
