### PR TITLE
Enthought update

### PR DESCRIPTION
**Pull request by emstro**
#### Description

Combined Enthought changes into one pull request. Note: it appears that VTK will not compile with Python 3.8 without some modifications, making py38-mayavi not likely to install. Not sure what all the needed mods are, yet.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6
Xcode 11.3.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
> Thank you for bundling these portfile upgrades into one PR.

I will close the other PRs.

**Comment by jjstickel** [comment]
Thanks again!

Sorry I was delayed in approving. For some reason github is not emailing me when commits are made to a PR, only when there is a comment.

**Comment by reneeotten** [comment]
> Thanks again!
> 
> Sorry I was delayed in approving. For some reason github is not emailing me when commits are made to a PR, only when there is a comment.

Just to make before I merge... since all the CI tests fail: can you confirm that this all builds correctly and the failures are just do to time-outs?

**Comment by jjstickel** [comment]
> Just to make before I merge... since all the CI tests fail: can you confirm that locally this all builds correctly and the failures are just do to time-outs?

Yes, it all builds fine on my machine, at least for py36.

**Comment by emstro** [comment]
It builds okay for me for py37.

**Pull request merged**
