### PR TITLE
v2ray: update to 4.31.0 & migrate to the new repo & …

### PR DESCRIPTION
**Pull request by i0ntempest**
vendor go dependencies & use full build.env, proper build.cmd

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by i0ntempest** [comment]
The newest version of v2ray gets rid of GOPATH mode: https://github.com/v2fly/v2ray-core/releases/tag/v4.31.0
It's not going into the correct location to find source files.

**Comment by casouri** [comment]
Why are there so many dist files? Do you mean the current portfile doesn't build anymore?

**Comment by casouri** [comment]
Btw since i0ntempest worked a lot on this port, could we add him as a maintainer?

**Comment by i0ntempest** [comment]
> Btw since i0ntempest worked a lot on this port, could we add him as a maintainer?

I’m already in the maintainer list of this port.


> Why are there so many dist files? Do you mean the current portfile doesn't build anymore?

Go can download dependencies during the build. We don’t want that, we want macports to handle all dist files, so they can be checksum-verified and mirrored onto macports servers. See  https://trac.macports.org/ticket/61192 
By “currently does not build” I mean it won’t build after my changes. I’ll need help from someone with more experience on Go build system.

**Review by amake — APPROVED** [review]
The build error was because the project is namespaced under a custom package name, `v2ray.com/core`. I figured this out by looking at the build error and noting that the classes it said were missing appeared to be from within the project, but were not namespaced under `github.com/v2fly`.

You can find the project's custom package name here:

https://github.com/v2fly/v2ray-core/blob/f7ed96f5d4ebad65527bdb264cdf451c4c62f589/go.mod#L1

I also fixed the build commands to use the full `build.env` (which includes e.g. `CC` to get the right compiler), `build.cmd`, and a common definition for the `ldflags`.

**Comment by casouri** [comment]
Is there anything we can do with the distfiles?

**Comment by amake** [comment]
> Is there anything we can do with the distfiles?

What do you mean?

**Comment by i0ntempest** [comment]
> Is there anything we can do with the distfiles?

No the go.vendor block stay there. In the future all Go ports should look like this. The port “go2port” can generate this for you, you just need to fix some small problems like what we’re doing here, Most other Go ports aren’t as problematic as this.

**Pull request merged**
