### PR TITLE
rb-ronn-ng: Add Ruby 3.1 subport and also for dependencies

### PR DESCRIPTION
**Pull request by judaew**
#### Description

Commits:
- rb-gem-patch: Add Ruby 3.1 subport
- rb-{kramdown,mini_portile2}: Add Ruby 3.1 subport
- rb-{mustache,nokogiri,ronn-ng}: Add Ruby 3.1 subport

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.1 21C52 x86_64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by judaew** [comment]
Notifying maintainers:
@l2dy for port rb-gem-patch.
@kimuraw for port rb-kramdown.

**Comment by reneeotten** [comment]
@judaew how is this going to work then there is no `ruby31` port?

**Comment by l2dy** [comment]
There is, see 560dafc54a49bc2144c339f6db72b142f2bf1e0e.

**Comment by reneeotten** [comment]
> There is, see [560dafc](https://github.com/macports/macports-ports/commit/560dafc54a49bc2144c339f6db72b142f2bf1e0e).

ah, sorry... I guess I hadn't synchronized my local tree yet...

**Pull request merged**
