### PR TITLE
shadowsocks-rust: new port starting from v1.20.3

### PR DESCRIPTION
**Pull request by zonyitoo**
#### Description

Added `shadowsocks-rust` to Macports

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.5 23F79 x86_64
Xcode 15.4 15F31d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by zonyitoo** [comment]
ref https://github.com/shadowsocks/shadowsocks-rust/issues/1607

**Comment by zonyitoo** [comment]
```
--->  Removing work directory for shadowsocks-rust
  DEBUG: Removing directory: /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_net_shadowsocks-rust/shadowsocks-rust
  DEBUG: Removing symlink: /Users/runner/work/macports-ports/macports-ports/ports/net/shadowsocks-rust/work
  DEBUG: Removing directory: /opt/local/var/macports/logs/_Users_runner_work_macports-ports_macports-ports_ports_net_shadowsocks-rust/shadowsocks-rust
  DEBUG: dropping privileges: euid changed to 502, egid changed to 501.
  /Users/runner/work/macports-ports/macports-ports/mpbb/mpbb: error: `install-port' failed to run successfully
  /Users/runner/work/_temp/134eb5b7-e0b7-47fc-bf88-ed9ea1f4041f.sh: line 6:  2375 Terminated: 15          tail -f "$workdir/logs/dependencies-progress.txt" 2> /dev/null
Error: Failed to install shadowsocks-rust
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
Error: Process completed with exit code 1.
```

What was those errors in CI means?

**Comment by herbygillot** [comment]
> ```
> --->  Removing work directory for shadowsocks-rust
>   DEBUG: Removing directory: /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_net_shadowsocks-rust/shadowsocks-rust
>   DEBUG: Removing symlink: /Users/runner/work/macports-ports/macports-ports/ports/net/shadowsocks-rust/work
>   DEBUG: Removing directory: /opt/local/var/macports/logs/_Users_runner_work_macports-ports_macports-ports_ports_net_shadowsocks-rust/shadowsocks-rust
>   DEBUG: dropping privileges: euid changed to 502, egid changed to 501.
>   /Users/runner/work/macports-ports/macports-ports/mpbb/mpbb: error: `install-port' failed to run successfully
>   /Users/runner/work/_temp/134eb5b7-e0b7-47fc-bf88-ed9ea1f4041f.sh: line 6:  2375 Terminated: 15          tail -f "$workdir/logs/dependencies-progress.txt" 2> /dev/null
> Error: Failed to install shadowsocks-rust
> find: illegal option -- n
> usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
>        find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
> Error: Process completed with exit code 1.
> ```
> 
> What did those errors in CI mean?

Hello @zonyitoo, thanks for this submission.  The actual error is actually much earlier in the log:

```
  --->  Checksumming shadowsocks-rust-1.20.3.tar.gz
  DEBUG: Calculated (rmd160) is 35a646945cfcd7ee668d23199384e64ac1c288c6
  Portfile checksum: shadowsocks-rust-1.20.3.tar.gz rmd160 e1c1eeb558c8c222dddd058f634c60f9dbaff041
  Distfile checksum: shadowsocks-rust-1.20.3.tar.gz rmd160 35a646945cfcd7ee668d23199384e64ac1c288c6
  Error: Checksum (rmd160) mismatch for shadowsocks-rust-1.20.3.tar.gz
  DEBUG: Calculated (sha256) is 07d2301cb14d8e1ff653def167604e701ca9a05a140291875e0ec9e6334ad513
  Error: Checksum (sha256) mismatch for shadowsocks-rust-1.20.3.tar.gz
  DEBUG: Calculated (size) is 452767
  Error: Checksum (size) mismatch for shadowsocks-rust-1.20.3.tar.gz
  Portfile checksum: shadowsocks-rust-1.20.3.tar.gz sha256 98ae9b438816a12240f130762dbdb30c03eccef61ba872767cf0dde33e9781e5
  Distfile checksum: shadowsocks-rust-1.20.3.tar.gz sha256 07d2301cb14d8e1ff653def167604e701ca9a05a140291875e0ec9e6334ad513
  Portfile checksum: shadowsocks-rust-1.20.3.tar.gz size 452759
  Distfile checksum: shadowsocks-rust-1.20.3.tar.gz size 452767
```

The checksum for the main distfile looks like it's incorrect.

**Comment by zonyitoo** [comment]
```
$ sudo port checksum shadowsocks-rust
--->  Fetching distfiles for shadowsocks-rust
--->  Verifying checksums for shadowsocks-rust
```

Checksum was running without any errors locally. :(

**Comment by herbygillot** [comment]
When testing checksums, it's always a good idea to do a full `clean` after editing your Portfile:

1. `sudo port -d clean -f --all <portname>` ie., `sudo port -d clean -f --all shadowsocks-rust`
2. `sudo port -d checksum shadowsocks-rust`

**Comment by herbygillot** [comment]
This looks good to merge. Thank you for contributing this, @zonyitoo.

**Pull request merged**
