### PR TITLE
zenmap: create an app bundle

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.3.1 21E258 x86_64
Xcode 13.3.1 13E500a

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by i0ntempest** [comment]
Also, any chance we could let this port use python 3 instead of 2?

**Comment by i0ntempest** [comment]
@danielluke @ghosthound Anything u guys want to say about this?

**Comment by kencu** [comment]
I added the launch script feature to the app PG a few years ago, btw, so in future you could use that instead of redoing it manually…

options app.use_launch_script

**Comment by ghosthound** [comment]
Sorry, been a bit backed up.
I haven't tried this yet but otherwise don't know of a reason not to proceed with it.

**Comment by i0ntempest** [comment]
@kencu unrelated to this port, can I add launch args to pass to the executable if I use that option?

**Comment by kencu** [comment]
> @kencu unrelated to this port, can I add launch args to pass to the executable if I use that option? (Basically recreating [this](https://github.com/macports/macports-ports/blob/master/security/hydra/files/xHydra))

Well that would be a fine addition to the system! My shell is terribly weak, @pmetzger and others much stronger, but I suspect a few %1 %2 %3 etc, well placed, might do it? Great thought.

**Comment by jmroot** [comment]
> Also, any chance we could let this port use python 3 instead of 2?

Not until that support is added upstream. It needs to be ported to gtk3 and gobject-introspection because there is no python3 version of PyGTK.

**Comment by i0ntempest** [comment]
> > Also, any chance we could let this port use python 3 instead of 2?
> 
> Not until that support is added upstream. It needs to be ported to gtk3 and gobject-introspection because there is no python3 version of PyGTK.

Yea, I took a look at upstream issues and seems not much is being done on this.

**Comment by danielluke** [comment]
Can you remove me as a maintainer on this before you commit it, please? I don't use zenmap so I'm not likely to keep it up to date and working.

**Pull request merged**
