### PR TITLE
wireshark2: update to 2.6.4

### PR DESCRIPTION
**Pull request by Schamschula**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix
- [x] update

###### Tested on

macOS 10.13.6 17G65
Xcode 10.0 10A255 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
@Schamschula, is it practical for you to add darkart.com:opendarwin.org's github handle as well? (Oh, and this looks fine to me, I hope the maintainer agrees to make it openmaintainer going forward.)

**Comment by Schamschula** [comment]
I'll leave that up to the maintainer. Historically, wireshark has had some idiosyncrasies, so I can understand it being closed maintainer.

**Comment by pmetzger** [comment]
The maintainer is unlikely to see this conversation and thus unlikely to know that we would like their github handle in the Portfile...

**Comment by Schamschula** [comment]
I don't have a GitHub handle for this maintainer.

Also see https://trac.macports.org/ticket/50243

I guess, I should have gone the traditional route, by putting a ticket on trac...
That has worked in the past.

**Comment by Schamschula** [comment]
On re-reading that ticket, I found darkart.com:opendarwin.org more recently goes by ghosthound.

**Comment by pmetzger** [comment]
Can we add their ID to the Portfile?

**Comment by ghosthound** [comment]
Eventually the maintainer did find this.  Is there a reason no one reached out before altering the port?  Or did I miss that somewhere (totally possible)?

**Comment by Schamschula** [comment]
As @pmetzger posted, this PR was merged prematurely, before maintainer timeout had expired.

**Comment by pmetzger** [comment]
That said, after 16 days the change would have been merged anyway. We don't wait that long for the maintainer to comment. Generally maintainers are given a few days to object, not weeks.

**Comment by Schamschula** [comment]
Never mind that livecheck was showing the update for over a week before I opened the PR.

**Pull request merged**
