### PR TITLE
Add MoltenVK port and use it in wine-devel

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

Add MoltenVK port and use it in wine-devel

It builds for me and wine runs, but I don't know how to test whether Vulkan support is now working.

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.6 17G65
Xcode 9.4.1 9F2000 

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. Thank you for doing this, a Vulkan on Metal package is important.

**Comment by ryandesign** [comment]
It was [pointed out](
https://trac.macports.org/ticket/57005#comment:4) that Metal, on which MoltenVK relies, is 64-bit only. So I should remove the universal variant and set `supported_archs x86_64` before merging.

**Comment by ryandesign** [comment]
And I need to change wine-devel to use `--with-vulkan` on the 64-bit part only.
And Sierra with Xcode 9 should be allowed too.

**Comment by cjones051073** [comment]
LG(reat)TM... I had making a port for VulcanVK on my mental to do list, so glad someone got to it first.

( Now if only they would open source MoltenGL as well, that would be great... )

**Comment by pmetzger** [comment]
Merged. Thank you, @ryandesign!

**Pull request merged**
