### PR TITLE
minpack: update to current version, unbreak the port

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

`minpack` is archaic and fails across the board: https://ports.macports.org/port/minpack/details/
Fix it.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

All tests pass in Rosetta:
```
--->  Testing minpack
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_math_minpack/minpack/work/build" && /opt/local/bin/ninja test 
[0/1] Running all tests.
 1/12 minpack:example / hybrd  OK              0.27s
 2/12 minpack:example / hybrd1 OK              0.26s
 3/12 minpack:example / lmder1 OK              0.24s
 4/12 minpack:example / lmdif1 OK              0.22s
 5/12 minpack:example / primes OK              0.20s
 6/12 minpack:unit / chkder    OK              0.18s
 7/12 minpack:unit / hybrd     OK              0.32s
 8/12 minpack:unit / hybrj     OK              0.31s
 9/12 minpack:api / c-api      OK              0.16s
10/12 minpack:unit / lmder     OK              0.26s
11/12 minpack:unit / lmdif     OK              0.24s
12/12 minpack:unit / lmstr     OK              0.22s

Ok:                 12  
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0
```

### CODE REVIEW

**Comment by barracuda156** [comment]
Destroot fails on CI:
```
Running custom install script '/usr/bin/env python /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_math_minpack/minpack/work/fortran-lang-minpack-c0b5aea/config/install-mod.py include/minpack'
  --- stdout ---
  
  --- stderr ---
  env: python: No such file or directory
  
  FAILED: install script '/usr/bin/env python /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_math_minpack/minpack/work/fortran-lang-minpack-c0b5aea/config/install-mod.py include/minpack' exit code 127, stopped
  FAILED: meson-internal__install
```

Should be fixable.

**Comment by jjstickel** [comment]
I can't remember why I am the maintainer for this, nor what I used it for. If it is still of use use, I'm glad to see it updated. LGTM, but I am not able to test at the moment.

**Comment by barracuda156** [comment]
@reneeotten Could you help merging this please?

@jjstickel Thank you!

**Comment by barracuda156** [comment]
@reneeotten Thank you!

**Pull request merged**
