### PR TITLE
R: updates for packages (2)

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Updates

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
MacOS 15 apparently builds everything from scratch and just times out (6+ hrs).

**Comment by reneeotten** [comment]
@barracuda156 so what's again the issue with macOS 14? That really has to be fixed, we should be fully supporting that platform so we can't just keep merging PRs that fail...

**Comment by barracuda156** [comment]
I guess buildbots use one Xcode version while GH CI use a broken one. I am not an expert here. Everything builds fine with Sonoma native Xcode, but GH switched to using Xcode 16 on it.

**Comment by barracuda156** [comment]
@reneeotten I will break this down, so that hopefully macOS 15 CI can complete. Anyway I wanted to add a few more updates, so I need two PRs.

**Comment by reneeotten** [comment]
> @reneeotten I will break this down, so that hopefully macOS 15 CI can complete. Anyway I wanted to add a few more updates, so I need two PRs.

I am not worried about the macOS 15 CI - that will time-out often as it appears to need to build everything. The point with the macOS 14 runner is that if that fails, it will likely also fail for end-user as it is likely a common configuration. So we/you will have to deal with that at some point in the near future.

**Pull request merged**
