### PR TITLE
curl-ca-bundle: update to aca64a177c44 / 2016-09-22

### PR DESCRIPTION
**Pull request by l2dy**
@ryandesign

### CODE REVIEW

**Comment by smithsp** [comment]
@ryandesign To try this out add the remote
```
git remote add git@github.com:l2dy/macports-ports.git
git checkout curl-ca-bundle-update
```
Test the updated port: 
```
cd net/curl
sudo port install
```
If it works, then come back here and merge (or follow the command line option instructions - I can't see them, so I don't know for sure what they recommend).

**Comment by l2dy** [comment]
Please merge this now and get curl 7.51.0 in as soon as possible!

**Comment by neverpanic** [comment]
@ryandesign What's the status on this?

**Comment by ryandesign** [comment]
I have merged it in 9aa7161c34a1d43dc1a264409f06af09c6b67d57.

**Comment by l2dy** [comment]
@ryandesign Please use rebase and merge here because Merged looks better than Closed which usually means PR rejected.

**Comment by mojca** [comment]
Can we bring this discussion to the mailing list and potentially set up some testing repository for this? Other committers are facing the same problem, see #12

**Pull request closed without merging**
