### PR TITLE
remove createtorrent

### PR DESCRIPTION
**Pull request by janstary**
It is more than a decade old, has no maintainer,
and the homepage is dead. Is anyone using this?

### CODE REVIEW

**Comment by pmetzger** [comment]
I'm inclined, given the lack of a home page or obvious upstream, to kill it, but I'd like an opinion from someone more senior like @raimue.

**Comment by raimue** [comment]
Repology: https://repology.org/metapackage/createtorrent/versions

**Comment by raimue** [comment]
It still exists in other distributions, but upstream dead for a decade should be enough reason to remove it. There are enough alternative tools to create a `.torrent` file.

+1 for removing.

**Comment by pmetzger** [comment]
Done.

**Pull request merged**
