### PR TITLE
libressl-devel: fix build on macOS < 10.14

### PR DESCRIPTION
**Pull request by artkiver**
###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.2 23C5047e arm64
Xcode 15.0 15A5219j

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by TheRealKeto** [comment]
I decided to test this change and it seems to have built just fine on macOS 10.7.5 11G63 x86_64 running Xcode 4.6.3 4H1503. No errors to report.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@artkiver @TheRealKeto @ryandesign buildbot [keeps failing](https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/167792/steps/install-port/logs/stdio) because it can't uninstall openssl...

**Comment by TheRealKeto** [comment]
> buildbot [keeps failing](https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/167792/steps/install-port/logs/stdio) because it can't uninstall openssl...

@aeiouaeiouaeiouaeiouaeiouaeiou openssl should also conflict with libressl{,-devel}; I don't know what openssl is installed for, but it should also have a conflict statement

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
> So, it shouldn't be having openssl as a dependency, yet when looking at the error log, it appears as if it thinks that is the case? I am confused.

Blacklisting an outdated version of clang results in installing the [latest available version](https://ports.macports.org/port/clang-16/details/), which depends on python311 for building. Python in turn [depends](https://ports.macports.org/port/python311/details/) on OpenSSL.
It might be worth trying to use the [bootstrapped version](https://ports.macports.org/port/clang-11-bootstrap/details/) to sort out this recursive mess, but I'd like a knowledgeable person's opinion.

**Pull request merged**
