### PR TITLE
qt4-mac: allow newer compilers on older systems

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by michaelld** [comment]
Lawd have mercy ... more qt4-mac patches!

**Comment by michaelld** [comment]
So do I read this correctly that we're trying to build Qt4 here with C/C++98 unless C++11 is specified? Meaning we specifically tell the compiler the standard to use, all of the time ... trying to avoid using more recent C/C++ standards so-as to avoid the pitfalls of them on such old code?

**Comment by kencu** [comment]
that would appear to work so long as some qt4 dep doesn't go all c++11-only on us...

**Comment by MarcusCalhoun-Lopez** [comment]
> So do I read this correctly that we're trying to build Qt4 here with C/C++98 unless C++11 is specified? Meaning we specifically tell the compiler the standard to use, all of the time ... trying to avoid using more recent C/C++ standards so-as to avoid the pitfalls of them on such old code?

Yes, that is the idea.
I have not tested it, but it may be possible to override the override if a port requires both Qt4 and C++11.

> Lawd have mercy ... more qt4-mac patches!

Sorry.
I could not think of another way to proceed.

**Comment by kencu** [comment]
I have it building away on `10.6.8` 32bit version using `clang-9.0` against `libc++`. will report back in a few hours when it's done.

**Comment by michaelld** [comment]
@kencu It looks like this change doesn't impact 10.13 or 10.14, so there's a good change it'll work with 10.15 as well. If it aloows qt4-mac build on older OSX with more modern compilers, then I'm good with it. I honestly don't think I'll have time to test / verify this coming week. Hence, if you think this change is ready, then go ahead and merge. Thx!

**Pull request merged**
