### PR TITLE
gauche-dbd-pg: delete port

### PR DESCRIPTION
**Pull request by chrstphrchvz**
**Merely proposing deletion—please leave open long enough for discussion**

Port currently does not build, depends (fallback?) on EOL versions of `postgresql`, and has no dependents. The upstream project has had no releases since 2005, and has virtually no development since 2007 (except for one change in 2018 for compatibility with gauche 0.9.7).

Closes: https://trac.macports.org/ticket/58791

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

### CODE REVIEW

**Comment by pmetzger** [comment]
@chrstphrchvz Do you feel we've had enough time for discussion?

**Comment by chrstphrchvz** [comment]
> @chrstphrchvz Do you feel we've had enough time for discussion?

Possibly; one week should be plenty. My main concern is over the PR being merged after only 12-24 hours and then followed by objections or restoration (which is what happened to some previous deletion PRs).

**Comment by chrstphrchvz** [comment]
There is objection to deleting ports with signs of upstream development; closing for now.

**Comment by chrstphrchvz** [comment]
Reopening; I would like to go forward with deleting this port (and then move on to deleting e.g. `postgresql7`).

**Comment by kencu** [comment]
If I commit this someone will immediately ask why we didn't do the usual step of marking it obsolete for 1 year.

**Comment by chrstphrchvz** [comment]
https://guide.macports.org/chunked/development.practices.html#development.practices.removing-port
> If there is no replacement for a port, it can simply be deleted immediately.

I am not aware of a possible replacement port in this case, so I think it can be deleted immediately.

**Pull request merged**
