### PR TITLE
postgresql13–15: fix build with new icu on PPC

### PR DESCRIPTION
**Pull request by barracuda156**
Fixes: https://trac.macports.org/ticket/66060

#### Description

Fixes the build of `postgresql13` and `postgresql14` with new `icu`.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
Leave it for now. Need to find out whether a) fix is only needed for specific old systems and should be restricted, b) fix is needed once non-devel icu is updated to 72 or c) fix is needed for newer systems, but another one.

**Comment by barracuda156** [comment]
@catap What do you think of this? `icu`-related.

**Comment by catap** [comment]
@barracuda156 bool definition was removed from ICU with my the last update. I supprise that you need it.

**Comment by barracuda156** [comment]
> @barracuda156 bool definition was removed from ICU with my the last update. I supprise that you need it.

Hmm, ok. So theoretically this fix is redundant?

I got a failure on two systems however (10.6.8 and 10A190) – that is why I bothered searching for a solution in the first place.
Let me repeat, and if the failure persists, I restrict the fix to 10.6 for now.

**Comment by barracuda156** [comment]
UPD2. On 10.8.5 the patch is not needed, it builds fine.

**Comment by kencu** [comment]
> UPD. Yes, it fails on 10.6.8: [main.log](https://github.com/macports/macports-ports/files/9870586/main.log)

Well -- it fails on 10.6.8 when trying to build as PPC using gcc-4.2 (none of which is standard for MacPorts 10.6.8 support).

**Comment by barracuda156** [comment]
> > UPD. Yes, it fails on 10.6.8: [main.log](https://github.com/macports/macports-ports/files/9870586/main.log)
> 
> Well -- it fails on 10.6.8 when trying to build as PPC using gcc-4.2 (none of which is standard for MacPorts 10.6.8 support).

@kencu I can try x86. Gimme a minute.

**Comment by kencu** [comment]
On 10.6.8, MacPorts' only supported configuration is building on Intel with MacPorts' default compiler (currently clang-11), against libc++. All portfile tweaks and patches should be tested against that.

Beyond that, reasonable tweaks that don't break the supported configuration are acceptable.

As ICU requires c++11, it will never in a million years build with gcc-4.2.

https://github.com/macports/macports-ports/blob/9835062f1df78c7fbefe444d9f9531aaf92629fc/devel/icu/Portfile#L78

**Comment by barracuda156** [comment]
> On 10.6.8, MacPorts' only supported configuration is building on Intel with MacPorts' default compiler (currently clang-11), against libc++. All portfile tweaks and patches should be tested against that.
> 
> Beyond that, reasonable tweaks that don't break the supported configuration are acceptable.

@kencu Okay, weirdly that is a PPC issue. `gcc12` on PPC fails, on Intel no problem using GCC to build. I will restrict the patch to PPC instead.

**Comment by barracuda156** [comment]
@catap Are we good with this fix?

**Comment by catap** [comment]
@barracuda156 I haven't got access to PPC and can't verify your patch :(

Anyway, this isn't openmaintaner port and you need an approve of @jyrkiwahlstedt  :(

**Comment by catap** [comment]
But very strange things that it works fine and were built with the last ICU on all platforms at https://ports.macports.org/port/postgresql13/details/ and https://ports.macports.org/port/postgresql14/details/

**Comment by barracuda156** [comment]
> Anyway, this isn't openmaintaner port and you need an approve of @jyrkiwahlstedt :(

Maintainer timeout, though someone has to approve it anyway.

**Comment by barracuda156** [comment]
> But very strange things that it works fine and were built with the last ICU on all platforms at https://ports.macports.org/port/postgresql13/details/ and https://ports.macports.org/port/postgresql14/details/

We got `postgresql15` also broken with multiple bool errors: https://trac.macports.org/ticket/67365

@catap Since you have Rosetta setup now, maybe you could help to fix this finally?

**Comment by barracuda156** [comment]
Same fix applies to `postgresql15`.

**Comment by barracuda156** [comment]
@mascguy Could we please merge this? GDAL needs `postgresql`, and all these are broken forever, and I need GDAL for several `R` ports.

**Review by mascguy — APPROVED** [review]
LGTM

**Pull request merged**
