### PR TITLE
curl: upstream does not support --with-darwinssl switch, use --with-secure-transport

### PR DESCRIPTION
**Pull request by seabadger**
…; also, --with-ssl is really --with-openssl; --without-ssl means not SSL support at all

#### Description

Fix curl +darwinssl variant. 
The '--with-darwinssl' configure script switch has not worked for a while.
Update port file to use '--with-secure-transport' instead.

(without the fix, curl +darwinssl builds without ssl support at all, since --with-darwinssl was being silently ignored by curl's configure script; upstream curl was recently updated in master (not yet released) to fail the build  as of https://github.com/curl/curl/pull/7200/commits/5731d5a9be4fcf89e356293a28b4289cf65bd0ae).

I also updated the '--with-ssl' switch to the synonymous but more explicit --with-openssl switch.
The reason for this is that '--with-ssl' and '--without-ssl' are not symmetric: the former enables openssl, the latter  disables ALL ssl backends. This should make the +ssl variant clearer. Functionally nothing changes.

###### Type(s)
- [x ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 11.4 20F71 x86_64
Xcode 12.3 12C33
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
Thanks. Can you update your commit message to follow our guidelines please.

portname: description

**Comment by seabadger** [comment]
done (I think). Sorry, I'm relatively new to git. Please let me know if it looks ok, or if not -- how to fix :)

**Comment by cjones051073** [comment]
> done (I think). Sorry, I'm relatively new to git. Please let me know if it looks ok, or if not -- how to fix :)

Thanks for trying, but no, you now have three commits showing up here, one of which is a merge commit.

I've just checked out your branch here, so I can show you how to fix. First, you need to rebase against current master.

```
Oberon ~/Projects/MacPorts/ports > git pull --rebase --autostash origin master
remote: Enumerating objects: 75, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 75 (delta 41), reused 39 (delta 33), pack-reused 20
Unpacking objects: 100% (75/75), 70.85 KiB | 824.00 KiB/s, done.
From github.com:macports/macports-ports
 * branch                    master     -> FETCH_HEAD
   f47db6eb104..b23d1c6d96f  master     -> origin/master
dropping cc4044017d0f7aed371cc345b39c1334904aa40c curl no longer supports --with-darwinssl, use --with-secure-transport; also, --with-ssl is really --with-openssl; --without-ssl means not SSL support at all -- patch contents already upstream
Successfully rebased and updated refs/heads/curl-darwinssl-fix.
```

(note, in my clone, origin is the name I have for the primary macports repo).

Then, if you check the log you will see there is only the one commit from yourself on top of master

```
Oberon ~/Projects/MacPorts/ports > git log
commit 336a1a630e45ae2c624a672b7cb6963e2f641707 (HEAD -> curl-darwinssl-fix)
Author: Vadim Grinshpun <vg23@cornell.edu>
Date:   Mon Jun 7 09:14:50 2021 -0400

    curl: fix +darwinssl variant
    
    curl no longer supports --with-darwinssl, use --with-secure-transport; also, --with-ssl is really --with-openssl; --without-ssl means not SSL support at all

commit b23d1c6d96fcf6e8b0f6216d9c8967f35600f468 (origin/master, origin/HEAD)
Author: Enrico M. Crisostomo <enrico.m.crisostomo@gmail.com>
Date:   Thu Jun 10 21:28:42 2021 +0200

    py-botocore: update to 1.20.91
<snip>
```

so, all you would need to do now is (force) push back. You need to force as you have changed the git history in your branch.

```
Oberon ~/Projects/MacPorts/ports > git push --force seabadger  curl-darwinssl-fix
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.27 KiB | 1.27 MiB/s, done.
Total 5 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:seabadger/macports-ports.git
 + b1feeeff979...afa4122130c curl-darwinssl-fix -> curl-darwinssl-fix (forced update)
```

**Comment by seabadger** [comment]
I tried this, but I am not sure the history looks right... Can you check? Sorry and thanks :-/

**Comment by seabadger** [comment]
OK, I think it's easier to just re-do the pull request with a new branch.
I opened https://github.com/macports/macports-ports/pull/11361 containing the same change but with now hopefully correct single commit with appropriately formatted message.
Closing this PR, please review https://github.com/macports/macports-ports/pull/11361 instead. 
Thanks!

**Pull request closed without merging**
