### PR TITLE
ghostscript: update to 9.25

### PR DESCRIPTION
**Pull request by mojca**
#### Description

This updates ghoscript to the latest version.

However, dependent port need a revupgrade too and I'm not sure how to find all of them. At least `dvisvgm` from `texlive-bin` and ImageMagick depend on it.

The functionality which was broken in 9.24 (and hotfixed) seems to work for me. Patches no longer apply anyway (but the code is also different from the patched one in 9.24), it seems like the code underwent further refactoring anyway.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [x] security fix (@pmetzger says so :)

###### Tested on

macOS 10.13.6 17G65
Xcode 9.4.1 9F2000 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mojca** [comment]
That said ... another user complained about defunct asymptote with 9.25 a few hours ago, so I'm not really sure that this update doesn't introduce other problems.

**Comment by mojca** [comment]
@dports: I'm looking at `texlive-bin` which has a library dependency on ghoscript due to `dvisvgm`, so I need to change `ghoscript` from `depends_run` to `depends_lib`. What about excluding the `dvisvgm` binary from `texlive-bin` since we have a standalone port for that anyway?

**Comment by mojca** [comment]
I revbumped some dependent ports, but it's not anywhere near complete. I blindly guessed that gimp might need a revbump, I didn't check.

@tenomoto: please review the changes for `sam2p`. By quickly looking at it, it seems as if that one doesn't depend on `ghostscript` library itself.

**Comment by mojca** [comment]
I've seen futher bug reports associated primarily with crippled functionality which is unlikely to get fixed for precisely security reasons. My tests work. We need further revbumps in any case. Whether or not to wait for those fixes ...

**Comment by mojca** [comment]
Here's a list of ports that mention ghoscript in their `Portfile`. Absolutely no sanity checks made (many of them are probably just runtime dependencies).
```
editors/TeXmacs
genealogy/gramps
gnome/goffice
graphics/djvu2pdf
graphics/dvisvgm
graphics/fig2ps
graphics/gimp2
graphics/gimp2-devel
graphics/gimp3-devel
graphics/gle-graphics
graphics/ImageMagick
graphics/pstoedit
graphics/sam2p
graphics/xfig
graphics/xpdf
mail/claws-mail
math/DoCon
math/gsl
math/imaxima
math/octave
math/pyxplot
ocaml/camlimages
print/epstool
print/fig2dev
print/ghostscript-fonts-hiragino
print/gv
print/latex2html
print/libspectre
print/ps2eps
print/scribus
print/scribus-devel
python/impressive
python/py-matplotlib
science/gmt4
science/gmt5
science/gri
science/magicspp
sysutils/groff
sysutils/littleutils
tex/dvipng
tex/kde4-kile
tex/latex2rtf
tex/LaTeXiT
tex/texlive-bin
textproc/canna
textproc/doxygen
textproc/lilypond
textproc/lilypond-devel
textproc/psbind
textproc/pstotext
textproc/xmlstarlet
www/gallery
www/pathalizer
www/webdot
x11/xcircuit
x11/xcircuit-devel
```

**Comment by pmetzger** [comment]
I think most of them are runtime dependencies. Is there an easy way to get the "port" command to spit out the things that are more than that? (I suspect not...)

**Comment by mojca** [comment]
I listed all ports which have any kind of dependency on ghoscript. In principle `Portfile` tells you whether something is a runtime dependency or a library dependency, but based on my check of three dependencies, two of which had the wrong type listed, this info is not something I'm highly confident in.

The fasted automated check would be to download the binary archives of the mentioned ports and run `otool -L` on all binary files to see whether ghoscript is linked in as a library or not. Or simply do nothing and wait for revupgrade to do the job. Or revbump all of them just in case, potentially wasting CPU cycles with no good reason. Or trust the info in Portfiles and revbump those with `depends_lib`, getting a bunch of false positives and a bunch of false negatives.

**Comment by pmetzger** [comment]
Given that this is a security problem, maybe we should prioritize it? How hard would running the otool test be?

**Comment by pmetzger** [comment]
Okay, here's my feeling: nothing is _harmed_ by committing this without bumping absolutely everything that needs bumping, and many things are _helped_. I'd therefore suggest that we commit this in the next day and open an issue to track other things that need bumping.

**Comment by pmetzger** [comment]
@mojca So may I merge this?

**Comment by pmetzger** [comment]
How about you remove the `texlive-bin` bump, merge it, and then we'll get #2620 in quickly.

**Comment by pmetzger** [comment]
Merged. Thanks so much, @mojca!

**Pull request merged**
