### PR TITLE
Update to lang/python38-devel

### PR DESCRIPTION
**Pull request by Themanwithoutaplan**
#### Description

Updated Portfile and patches to setup.py, which has seen some significant refactoring.

###### Type(s)
- [ ] bugfix
- [ ] enhancement
- [ ] security fix
- [x] update

###### Tested on
macOS 10.14.5 18F132
Xcode 10.2.1 10E1001

###### Verification 

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
Don't know how to squash, sorry.
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
https://trac.macports.org/ticket/58594 (Ticket was created first)
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
Some test failures due to path length `OSError: AF_UNIX path too long` due to where the repo is.
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by Themanwithoutaplan** [comment]
Sorry if I haven't followed the guidelines 100%. Please advise if I need to do things differently.

**Comment by yan12125** [comment]
Thanks for this PR! I haven't had time to look into details. At the first glance, this update looks good, with just a few minor issues:

* better to squash all commits into one
* better to include the Trac ticket URL in git commit message. You can write `Closes: https://trac.macports.org/ticket/58594` so that the ticket is automatically closed once this PR is merged.

By the way, all builds fail. Could you also have a look?

**Comment by Themanwithoutaplan** [comment]
I saw the failures but don't really understand system details that much. I won't have any more time this weekend to investigate this but will then at least try to squash the PR. I don't normally use git so I'll have to look it up.

I guess the `sed` error might have something to do with `sysconfigdata_m_darwin_darwin.py` being renamed to `sysconfigdata_m_darwin_darwin.py` in the distfiles. But that really is just a guess.

**Comment by herbygillot** [comment]
Also maybe you don't want to merge master in to your dev branch, but update master itself, then rebase your dev branch on top of the updated master?

**Comment by Themanwithoutaplan** [comment]
> Also maybe you don't want to merge master in to your dev branch, but update master itself, then rebase your dev branch on top of the updated master?

Sorry, such nicities are beyond my current git skillset. I could resubmit using a dedicated branch, if that's preferable?

**Comment by yan12125** [comment]
> Sorry, such nicities are beyond my current git skillset. I could resubmit using a dedicated branch, if that's preferable?

I'm fine as long as it works :)

**Comment by ryandesign** [comment]
> I saw the failures but don't really understand system details that much.

The logs show the builds are failing because:

```
DEBUG: couldn't read file "/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_lang_python38-devel/python38-devel/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/config-3.8m-darwin/Makefile": no such file or directory
```

Does that file exist?

Did you encounter this error when you built in on your own system? If not, we should figure out what's different between your system and Travis.

**Comment by Themanwithoutaplan** [comment]
> Did you encounter this error when you built in on your own system? If not, we should figure out what's different between your system and Travis.
Yes, it looks like I did. Looks like the "trailing m" in the `confdir` needed removing, which would make sense considering the other changes. `install -st` now runs locally without problems and I'm hopeful that the automated builds will as well.

**Comment by yan12125** [comment]
@Themanwithoutaplan thank you very much for the update!

**Pull request merged**
