### PR TITLE
libsdl2: minor edits to support building on 10.6.8

### PR DESCRIPTION
**Pull request by ken-cunningham-webuse**

### CODE REVIEW

**Comment by ken-cunningham-webuse** [comment]
for libsdl2

**Comment by mojca** [comment]
Where does your second commit come from?

**Comment by ken-cunningham-webuse** [comment]
Not 100% sure! 

I first tried to edit the file in macports, and github said it would automatically fork it for me, which sounded good --  but in the end, it wouldn't let me create a pull request from that fork. 

So I forked the entire macports tree into my git repository, edited it there, generated a pull request for my macports git repository, and then after I accepted my own pull request into my own repository (!), I saw it was possible to use that to generate a pull request into the main macports repo.

I'm kinda surprised it worked at all for my first try, to be honest. Did I do it wrong ??

**Comment by mojca** [comment]
There's no need for you to create a pull request to your own repository. You just commit there.

As a general rule I would suggest you not to modify the master branch of your own fork at all. Note that as soon as you'll try to pull another change to your tree, it will show up on this pull request. You need to create a separate branch for every change you plan to make and then create a pull request from that branch. Once the pull request is accepted, you can delete that branch.

I'm not telling you that to create more work for you (I hate it when projects won't accept patches just because I have no clue how to submit them properly), but for the next time.

(It usually also helps to prepend the port name to the commit message and mention the full path to the ticket in trac when one exists.)

Not that I'm fully confident yet about how to properly "merge" changes either.

**Comment by raimue** [comment]
You created a pull request with your master branch as source. Everything you add to the source branch will show up in the pull request. This is how you extend a pull request with additional commits.

For each pull request, first push the changes to a new branch in your own repository.

**Comment by jmroot** [comment]
Isn't there a ticket for this?

**Comment by mkae** [comment]
Well, this won't build it on a Snow Leopard buildbot, right? Unless the have that SDK installed...

**Comment by mojca** [comment]
Sorry, I was mistaken, there is no ticket, just a long discussion on the mailing list, so referencing a ticket doesn't make any sense. All additional information (if any is needed) could be provided in this discussion rather that forcing creation of a new ticket on Trac. (One could in theory put a link to the thread on the mailing list archive, but it's not like we did that in the past.)

The patch seems totally reasonable to me:
* it blacklists too old compilers on 10.6
* it's more verbose and tells the user that it might be possible to actually compile the package on 10.6 if SDK is added (whether or not instructions for how to do that should generally be available is a different thing; it might make more sense to provide a binary package)

I'm just not sure how to properly rebase/merge it.

**Comment by jmroot** [comment]
https://trac.macports.org/ticket/52210

**Comment by ken-cunningham-webuse** [comment]
Hi all. Indeed there was a ticket, as jmr points out. Initially not much enthusiasm for it, based on the 10.7SDK issue. I was happy to let it drop back then, but more recently on the mailing list Ryan and others felt this was actually not an unreasonable approach and suggested proceeding on with the patch when more software requiring libsdl2 came forth (ffmpeg, specifically).

It does require the 10.7SDK, no getting around that (well - actually - I'm not sure whether a 10.8 or 10.9 or even another more recent SDK might also work -- defer to jmr there). Whether that is too much to expect a user to understand and figure out how to do I will leave up to your experience and judgement. Ryan indicated he would add this SDK to the buildbot to build the binary package.

I carefully placed the compiler.blacklist in that spot in the hopes of only triggering the clang-3.4 install (with it's mountain of deps) if the user was on 10.6  && had the SDK issue worked out and clang-3.4 was actually going to be used. It could certainly go up in the main part of the portfile if you like, but if it were there, would it trigger the clang-3.4 install even if the MacOSX10.7 SDK were not present?

I thought we had decided to just call all versions macOS now ....

**Comment by ken-cunningham-webuse** [comment]
If I just hit "Close Pull Request" at the bottom of this page, do you imagine it would it delete both of the pull requests, or just one of them (which is what I want)?

**Comment by ken-cunningham-webuse** [comment]
I guess now we know. It closed them both. I'll start over with a new branch and try to do it correctly this time! -- K

**Comment by larryv** [comment]
In the future, you should [revise your PR branch](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) as necessary and force-push it, so that the conversion is not split up between multiple PRs. This should work fine as long as you don’t rename the branch.

**Comment by ken-cunningham-webuse** [comment]
Thanks, Larry -- I'm way behind on GitHub tricks. Thanks for your patience as I work through to a functional state.

**Comment by larryv** [comment]
No worries! We’re all trying to figure this out 😄

**Comment by mojca** [comment]
This was resolved in f944d47 (#10).

**Pull request closed without merging**
