### PR TITLE
[php] add postgresql96 support

### PR DESCRIPTION
**Pull request by xeron**
php port update for postgresql96.
    
* add `postgresql96` variant
* reformat all postgresql variants to make it easier to maintain

Second commit is only trailing whitespace removal. I can remove it if you don't like this whitespace changes.

@ryandesign

### CODE REVIEW

**Comment by larryv** [comment]
It would be nice if the reformatting and whitespace cleanup happened in one commit that came before the commit that adds `+postgresql96`.

**Comment by ryandesign** [comment]
I'm not especially interested in the reformatting. I was already working on this change locally without the reformatting and will commit that later.

**Comment by xeron** [comment]
@ryandesign anything against it? It's quite hard to add anything to this long lines with repeating `postgresql` and I thinks this reformatting makes it easier.

**Comment by ryandesign** [comment]
I don't wish to change the formatting of this Portfile at this time.

**Pull request closed without merging**
