### PR TITLE
Multiple ports: fix triple for Rosetta case

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Multiple ports misdetect OS arch when built on Rosetta. This causes many ports to fail altogether and leads to warnings of mismatching archs in config with others (dependents of `libgpg-error`). The PR fixes that.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Sergey, before submitting additional PRs like this, we need to step back and figure out where we can encapsulate this logic. (Per past discussions with @kencu and others.)

Otherwise we'll end up modifying umpteen ports with hard-coded 10.6/Rosetta fixes, only to have to go back and change them again later.

**Comment by barracuda156** [comment]
> Sergey, before submitting additional PRs like this, we need to step back and figure out where we can encapsulate this logic. (Per past discussions with @kencu and others.)
> Otherwise we'll end up modifying umpteen ports with hard-coded 10.6/Rosetta fixes, only to have to go back and change them again later.

@mascguy You mean whether this can be fixed on a level of PG instead of portfile code? I won’t mind that, but dunno how to do it.
I don’t think the problem is that huge though – not really a gazillion ports have this issue that lead to errors. (Some other misdetect the triple but build fine regardless.)

It may look like many, but:
1. I just brought fixes that I had for many months already. It is not gonna be a constant stream LOL.
2. I had build many ports, so percentage-wise problematic are rather few:
```
10:~ svacchanda$ sw_vers
ProductName:	Mac OS X Server
ProductVersion:	10.6.8
BuildVersion:	10K549
10:~ svacchanda$ port installed | grep active
  a52dec @0.7.4_1 (active)
  abseil @20220623.0_0 (active)
  airctl @0.7.3_0 (active)
  apg @2.3.0b_1 (active)
  apr @1.7.0_3 (active)
  apr-util @1.6.1_2 (active)
  asio @1.23.0_0 (active)
  at-spi2-atk @2.38.0_0 (active)
  at-spi2-core @2.38.0_0 (active)
  atk @2.38.0_1 (active)
  atkmm @2.28.0_0 (active)
  autoconf @2.71_1 (active)
  autoconf-archive @2022.02.11_0 (active)
  automake @1.16.5_0 (active)
  bcprov @1.70_0 (active)
  bcrypt @1.1_0 (active)
  bison @3.8.2_2 (active)
  bison-runtime @3.8.2_0 (active)
  boehmgc @8.2.0_0 (active)
  boost176 @1.76.0_3+no_single+no_static+python310 (active)
  botan @2.19.2_1 (active)
  brotli @1.0.9_2 (active)
  bsdmake @24_1 (active)
  btor2tools @20220518_0 (active)
  bzip2 @1.0.8_0 (active)
  c-ares @1.18.1_0 (active)
  cairo @1.17.4_0+quartz+x11 (active)
  cairomm @1.12.2_0+quartz+x11 (active)
  calife @3.0.6_0 (active)
  ccrypt @1.11_0 (active)
  cctools @949.0.1_2+llvm34 (active)
  cedar @2022-03-18_0 (active)
  cloog @0.18.4_5 (active)
  cmake-bootstrap @3.9.6_0 (active)
  cmake-devel @20220728-3.24.0-rc5-5ead1d0a_0 (active)
  cmph @2.0.2_0 (active)
  coreutils @9.1_0 (active)
  cracklib @2.9.7_0 (active)
  ctorrent @3.3.2_4 (active)
  curl @7.83.1_1+ssl (active)
  curl-ca-bundle @7.84.0_0 (active)
  cyrus-sasl2 @2.1.27_5+kerberos (active)
  cython_select @0.1_1 (active)
  dav1d @1.0.0_0 (active)
  db48 @4.8.30_4+java (active)
  dbacl @1.14_2 (active)
  dbus @1.14.0_0 (active)
  desktop-file-utils @0.26_0 (active)
  diffutils @3.8_0 (active)
  docbook-xml @5.0_3 (active)
  docbook-xml-4.1.2 @5.0_1 (active)
  docbook-xml-4.2 @5.0_1 (active)
  docbook-xml-4.3 @5.0_1 (active)
  docbook-xml-4.4 @5.0_1 (active)
  docbook-xml-4.5 @5.0_1 (active)
  docbook-xml-5.0 @5.0_1 (active)
  docbook-xsl-nons @1.79.2_0 (active)
  doxygen @1.9.3_2 (active)
  duktape @2.7.0_0 (active)
  dyncall @1.3_0 (active)
  eigen3 @3.4.0_0 (active)
  exiv2 @0.27.5_1 (active)
  expat @2.4.8_0 (active)
  fftw-3 @3.3.10_0+gfortran (active)
  findutils @4.9.0_0 (active)
  flex @2.6.4_0 (active)
  fontconfig @2.14.0_0 (active)
  fop @1.1_1 (active)
  freetype @2.12.1_0 (active)
  fribidi @1.0.12_0 (active)
  gawk @5.1.1_1 (active)
  gcc10-bootstrap @10.3.0_4 (active)
  gcc12 @12.1.0_3 (active)
  gcc_select @0.1_9 (active)
  gd2 @2.3.3_1+x11 (active)
  gdbm @1.23_0 (active)
  gdk-pixbuf2 @2.42.8_0 (active)
  gettext @0.21_0 (active)
  gettext-runtime @0.21_0 (active)
  gettext-tools-libs @0.21_0 (active)
  gftp @2.9.1b_0 (active)
  ghc-ppc-bootstrap @7.0.4_0 (active)
  ghostscript @9.56.1_0+x11 (active)
  giflib @4.2.3_0 (active)
  gindent @2.2.12_0 (active)
  git @2.37.1_0+credential_osxkeychain+diff_highlight+doc+pcre+perl5_34 (active)
  glfw @3.1.2-20151024_0 (active)
  glib2-upstream @2.72.3_0+x11 (active)
  glibmm @2.62.0_0+x11 (active)
  glm @0.9.9.8_0 (active)
  gmake @4.3_0 (active)
  gmm @5.4.2_0 (active)
  gmp @6.2.1_1 (active)
  gnome-common @3.18.0_0 (active)
  gnutls-devel @3.7.6_0 (active)
  gobject-introspection @1.72.0_0 (active)
  gperf @3.1_0 (active)
  gperftools @2.9.1_0 (active)
  graphene @1.10.8_0 (active)
  graphite2 @1.3.13_1 (active)
  graphviz @2.50.0_0+pangocairo+x11 (active)
  grep @3.7_2 (active)
  groff @1.22.4_6 (active)
  gsed @4.8_1 (active)
  gsl @2.7.1_0 (active)
  gstreamer1 @1.20.3_0 (active)
  gstreamer1-gst-plugins-base @1.20.3_0+ogg+x11 (active)
  gtest @1.11.0_0 (active)
  gtk-doc @1.32_2+python310 (active)
  gtk2 @2.24.33_3+x11 (active)
  gtk3 @3.24.34_2+x11 (active)
  gts @0.7.6-20121130_1 (active)
  gzip @1.12_0 (active)
  harfbuzz @5.0.1_0 (active)
  help2man @1.49.2_0 (active)
  hicolor-icon-theme @0.17_0 (active)
  hwloc @2.8.0_0 (active)
  icu @67.1_4 (active)
  isl @0.25_0 (active)
  isl18 @0.18_0 (active)
  itstool @2.0.7_2+python310 (active)
  jasper @2.0.33_0 (active)
  jbig2dec @0.19_0 (active)
  jbigkit @2.1_0 (active)
  jemalloc @5.3.0_2 (active)
  kerberos5 @1.20_0 (active)
  lbzip2 @2.5_1 (active)
  lcms @1.19_6 (active)
  lcms2 @2.13.1_0 (active)
  ld64 @3_4+ld64_97 (active)
  ld64-97 @97.17_9+llvm34 (active)
  legacy-support @1.0.6_1 (active)
  lerc @3.0_0 (active)
  libarchive @3.6.1_0 (active)
  libassuan @2.5.5_0 (active)
  libatomic_ops @7.6.12_0 (active)
  libb2 @0.98.1_1 (active)
  libcdata @20220115_0 (active)
  libcdatetime @20220104_0 (active)
  libcerror @20220101_0 (active)
  libcfile @20220106_0 (active)
  libclocale @20220107_0 (active)
  libcnotify @20220108_0 (active)
  libcomerr @1.45.6_0 (active)
  libcsplit @20220109_0 (active)
  libcstring @20150101_0 (active)
  libcthreads @20220102_0 (active)
  libde265 @1.0.8_0 (active)
  libedit @20210910-3.1_1 (active)
  libepoxy @1.5.10_0 (active)
  libevent @2.1.12_1 (active)
  libfetch @9.0.0-RELEASE_3 (active)
  libffi @3.4.2_2 (active)
  libfmt @9.0.0_0 (active)
  libgcc @6.0_0 (active)
  libgcc12 @12.1.0_3+stdlib_flag (active)
  libgcrypt @1.10.1_0 (active)
  libgfshare @2.0.0_0 (active)
  libGLU @9.0.1_0 (active)
  libgpg-error @1.45_0 (active)
  libheif @1.12.0_4 (active)
  libical @3.0.14_0 (active)
  libiconv @1.17_0 (active)
  libidn @1.41_0 (active)
  libidn2 @2.3.3_0 (active)
  libjpeg-turbo @2.1.3_0 (active)
  libksba @1.6.0_0 (active)
  libLASi @1.1.3_1 (active)
  libmacho-headers @949.0.1_0 (active)
  libmicrohttpd @0.9.75_0 (active)
  libmng @2.0.3_1 (active)
  libmpc @1.2.1_0 (active)
  libnetpbm @10.98.02_0 (active)
  libogg @1.3.5_1 (active)
  liboggz @1.1.1_0 (active)
  libopus @1.3.1_0 (active)
  libpaper @1.1.28_0 (active)
  libpixman @0.38.4_0 (active)
  libpng @1.6.37_0 (active)
  libpsl @0.21.1-20220513_0 (active)
  libsigcxx2 @2.10.3_0 (active)
  libsigsegv @2.14_0 (active)
  libtapi @1100.0.11_1 (active)
  libtasn1 @4.18.0_0 (active)
  libtextstyle @0.21_0 (active)
  libtheora @1.1.1_3 (active)
  libtommath @1.2.0_2 (active)
  libtool @2.4.7_0 (active)
  libunistring @1.0_0 (active)
  libusb @1.0.26_0 (active)
  libusb-compat @0.1.7_0 (active)
  libuv @1.44.2_0 (active)
  libvorbis @1.3.7_0 (active)
  libxml2 @2.9.14_0 (active)
  libxslt @1.1.34_6 (active)
  links @2.27_0 (active)
  llvm-3.4 @3.4.2_16 (active)
  llvm_select @2_0 (active)
  lmdb @0.9.29_0 (active)
  log4cxx @0.13.0_0 (active)
  lz4 @1.9.3_1 (active)
  lzip @1.23_0 (active)
  lzma @4.65_1 (active)
  lzo2 @2.10_0 (active)
  m4 @1.4.19_1 (active)
  mathex @0.3-b_0 (active)
  mesa @17.1.6_2+osmesa+python27 (active)
  meson @0.63.0_0 (active)
  mm-common @1.0.1_1 (active)
  MoarVM @2022.07_0 (active)
  mpfr @4.1.0_0 (active)
  mpi-doc @4.0.2_0 (active)
  mpi_select @0.0_3 (active)
  mpich-gcc12 @4.0.2_0+fortran (active)
  mpstats @0.2.0_0 (active)
  muparser @2.3.3-1_0 (active)
  ncurses @6.3_0 (active)
  netpbm @10.98.02_0+x11 (active)
  nettle @3.8_0 (active)
  nifticlib @2.0.0_1 (active)
  ninja @1.11.0_1 (active)
  nnn @4.6_0 (active)
  npth @1.6_0 (active)
  nqp @2022.07_0 (active)
  nspr @4.34_0 (active)
  nss @3.81_0 (active)
  ocaml @4.12.1_1 (active)
  oniguruma6 @6.9.8_0 (active)
  OpenBLAS @0.3.20_1+gcc12+lapack+native (active)
  openjpeg @2.5.0_0 (active)
  openldap @2.6.3_1 (active)
  openssh @9.0p1_6+kerberos5+xauth (active)
  openssl @3_6 (active)
  openssl3 @3.0.5_0+legacy (active)
  openssl11 @1.1.1q_0 (active)
  orc @0.4.32_0 (active)
  ossp-uuid @1.6.2_13+perl5_34 (active)
  p5.34-authen-sasl @2.160.0_0 (active)
  p5.34-b-cow @0.4.0_0 (active)
  p5.34-canary-stability @2013_0 (active)
  p5.34-capture-tiny @0.480.0_0 (active)
  p5.34-cgi @4.540.0_0 (active)
  p5.34-clone @0.450.0_0 (active)
  p5.34-common-sense @3.750.0_0 (active)
  p5.34-compress-raw-bzip2 @2.201.0_0 (active)
  p5.34-compress-raw-zlib @2.202.0_0 (active)
  p5.34-cpan-meta @2.150.10_0 (active)
  p5.34-cpan-meta-check @0.14.0_0 (active)
  p5.34-cpan-meta-requirements @2.140.0_0 (active)
  p5.34-cpan-meta-yaml @0.18.0_0 (active)
  p5.34-data-dump @1.250.0_0 (active)
  p5.34-devel-checkbin @0.40.0_0 (active)
  p5.34-digest-hmac @1.40.0_0 (active)
  p5.34-digest-sha1 @2.130.0_4 (active)
  p5.34-encode @3.190.0_0 (active)
  p5.34-encode-locale @1.50.0_0 (active)
  p5.34-error @0.170.290_0 (active)
  p5.34-extutils-makemaker @7.640.0_1 (active)
  p5.34-extutils-manifest @1.730.0_0 (active)
  p5.34-file-listing @6.150.0_0 (active)
  p5.34-file-slurper @0.13.0_0 (active)
  p5.34-getopt-long @2.520.0_0 (active)
  p5.34-gssapi @0.280.0_3 (active)
  p5.34-html-form @6.70.0_0 (active)
  p5.34-html-parser @3.780.0_0 (active)
  p5.34-html-tagset @3.200.0_4 (active)
  p5.34-http-cookies @6.100.0_0 (active)
  p5.34-http-date @6.50.0_0 (active)
  p5.34-http-message @6.370.0_0 (active)
  p5.34-inc-latest @0.500.0_0 (active)
  p5.34-io-compress @2.201.0_0 (active)
  p5.34-io-compress-brotli @0.4.1_0 (active)
  p5.34-io-html @1.4.0_0 (active)
  p5.34-io-socket-ip @0.410.0_0 (active)
  p5.34-io-socket-ssl @2.74.0_0 (active)
  p5.34-json @4.90.0_0 (active)
  p5.34-json-xs @4.30.0_0 (active)
  p5.34-locale-gettext @1.70.0_1 (active)
  p5.34-lwp-mediatypes @6.40.0_0 (active)
  p5.34-module-build @0.423.100_0 (active)
  p5.34-module-metadata @1.0.37_0 (active)
  p5.34-mozilla-ca @20211001_0 (active)
  p5.34-net-libidn @0.120.0_5 (active)
  p5.34-net-smtp-ssl @1.40.0_0 (active)
  p5.34-net-ssleay @1.920.0_0 (active)
  p5.34-pathtools @3.750.0_0 (active)
  p5.34-perl-ostype @1.10.0_0 (active)
  p5.34-pod-escapes @1.70.0_0 (active)
  p5.34-pod-simple @3.430.0_0 (active)
  p5.34-podlators @4.140.0_0 (active)
  p5.34-scalar-list-utils @1.620.0_0 (active)
  p5.34-socket @2.35.0_0 (active)
  p5.34-sub-name @0.260.0_0 (active)
  p5.34-sub-uplevel @0.280.0_0 (active)
  p5.34-term-readkey @2.380.0_0 (active)
  p5.34-test-cpan-meta @0.250.0_0 (active)
  p5.34-test-cpan-meta-json @0.160.0_0 (active)
  p5.34-test-deep @1.130.0_0 (active)
  p5.34-test-exception @0.430.0_0 (active)
  p5.34-test-fatal @0.16.0_0 (active)
  p5.34-test-needs @0.2.9_0 (active)
  p5.34-test-nowarnings @1.60.0_0 (active)
  p5.34-test-pod @1.520.0_0 (active)
  p5.34-test-requires @0.110.0_0 (active)
  p5.34-test-simple @1.302.191_0 (active)
  p5.34-test-warn @0.360.0_0 (active)
  p5.34-test-warnings @0.31.0_0 (active)
  p5.34-time-hires @1.976.400_0 (active)
  p5.34-time-local @1.300.0_0 (active)
  p5.34-timedate @2.330.0_0 (active)
  p5.34-try-tiny @0.310.0_0 (active)
  p5.34-types-serialiser @1.10.0_0 (active)
  p5.34-uri @5.120.0_0 (active)
  p5.34-version @0.992.900_0 (active)
  p7zip @16.02_5 (active)
  p11-kit @0.24.1_0 (active)
  pango @1.50.7_0+quartz+x11 (active)
  pangomm @2.42.1_1+quartz+x11 (active)
  par2 @0.8.1_0 (active)
  pcre @8.45_0 (active)
  pcre2 @10.40_0 (active)
  perl5 @5.34.1_0+perl5_34 (active)
  perl5.34 @5.34.1_0 (active)
  perl5.36 @5.36.0_0 (active)
  pinentry @1.2.0_0 (active)
  pkgconfig @0.29.2_0 (active)
  policykit @0.121_0 (active)
  popt @1.18_1 (active)
  protobuf3-cpp @3.19.3_0 (active)
  psutils @p17_1 (active)
  pth @2.0.7_1 (active)
  py-bootstrap-modules @2022-07-28_0 (active)
  py27-libxml2 @2.9.14_0 (active)
  py310-anytree @2.8.0_1 (active)
  py310-build @0.8.0_0 (active)
  py310-cython @0.29.32_0 (active)
  py310-installer @0.5.1_0 (active)
  py310-libxml2 @2.9.14_0 (active)
  py310-lxml @4.8.0_0 (active)
  py310-mako @1.2.1_0 (active)
  py310-markdown @3.3.7_0 (active)
  py310-markupsafe @2.1.1_0 (active)
  py310-packaging @21.3_0 (active)
  py310-parsing @3.0.9_0 (active)
  py310-pep517 @0.13.0_0 (active)
  py310-pygments @2.12.0_0 (active)
  py310-setuptools @63.2.0_0 (active)
  py310-six @1.16.0_0 (active)
  py310-tomli @2.0.1_0 (active)
  py310-wheel @0.37.1_0 (active)
  pygments_select @0.1_0 (active)
  python2_select @0.0_3 (active)
  python3_select @0.0_2 (active)
  python27 @2.7.18_10 (active)
  python27-bootstrap @2.7.18_10 (active)
  python39 @3.9.13_0+lto (active)
  python310 @3.10.5_0+lto (active)
  python_select @0.3_9 (active)
  qt4-mac @4.8.7_13 (active)
  rakudo @2022.07_0 (active)
  re2 @2022-04-01_0 (active)
  re2c @3.0_0 (active)
  readline @8.1.2.000_0 (active)
  rsync @3.2.4_0 (active)
  scons @4.4.0_0 (active)
  shared-mime-info @2.2_0 (active)
  slang2 @2.3.2_0 (active)
  speex @1.2.1_0 (active)
  speexdsp @1.2.1_0 (active)
  sqlite3 @3.39.0_0 (active)
  ssh-copy-id @9.0p1_0 (active)
  SuiteSparse_AMD @2.4.6_0 (active)
  SuiteSparse_BTF @1.2.6_0 (active)
  SuiteSparse_COLAMD @2.9.6_0 (active)
  SuiteSparse_config @5.9.0_0 (active)
  SuiteSparse_KLU @1.3.8_0 (active)
  sundials @6.2.0_0+accelerate+gfortran+mpich (active)
  tcp_wrappers @20_5 (active)
  texinfo @6.8_1 (active)
  tiff @4.4.0_0 (active)
  uchardet @0.0.7_0 (active)
  unrar @6.1.7_0 (active)
  urw-fonts @1.0.7pre44_0 (active)
  util-linux @2.38_1 (active)
  vala @0.56.2_0 (active)
  webp @1.2.3_0 (active)
  wget @1.21.3_0+gnutls (active)
  x265 @3.4_0 (active)
  xar @1.8.0.487.100.1_0 (active)
  xauth @1.1.2_0 (active)
  Xft2 @2.3.4_0 (active)
  xmlcatmgr @2.2_1 (active)
  xmlto @0.0.28_5 (active)
  xorg-libice @1.0.10_0 (active)
  xorg-libpthread-stubs @0.4_0 (active)
  xorg-libsm @1.2.3_0 (active)
  xorg-libX11 @1.8.1_0 (active)
  xorg-libXau @1.0.9_0 (active)
  xorg-libXaw @1.0.14_0 (active)
  xorg-libxcb @1.15_0+python310 (active)
  xorg-libXcomposite @0.4.5_0 (active)
  xorg-libXcursor @1.2.1_0 (active)
  xorg-libXdamage @1.1.5_0 (active)
  xorg-libXdmcp @1.1.3_0 (active)
  xorg-libXext @1.3.4_0 (active)
  xorg-libXfixes @6.0.0_0 (active)
  xorg-libXi @1.7.10_0 (active)
  xorg-libXinerama @1.1.4_1 (active)
  xorg-libXmu @1.1.3_0 (active)
  xorg-libXrandr @1.5.2_0 (active)
  xorg-libXt @1.2.1_0 (active)
  xorg-libXtst @1.2.3_1 (active)
  xorg-libXv @1.0.11_1 (active)
  xorg-libXxf86vm @1.1.4_1 (active)
  xorg-util-macros @1.19.3_0 (active)
  xorg-xcb-proto @1.15.2_0+python310 (active)
  xorg-xcb-util @0.4.0_1 (active)
  xorg-xorgproto @2022.1_0 (active)
  xorg-xtrans @1.4.0_0 (active)
  xpm @3.5.13_0 (active)
  xrender @0.9.10_1 (active)
  xxhashlib @0.8.1_1 (active)
  xz @5.2.5_1 (active)
  xz-bootstrap @5.2.5_3 (active)
  yaml-cpp @0.7.0_1 (active)
  zlib @1.2.12_1 (active)
  zstd @1.5.2_0 (active)
```

**Comment by barracuda156** [comment]
@mascguy Okay, I am done collecting similar fixes for Rosetta here :)

TBH I don’t think we need any fancy solution via PG for now, given that a) few ports need these fixes and b) in some cases `--build=` is not enough, so we still gonna need some port-specific code.
And after all, if some centralized solution is developed later on, I can take responsibility for updating 15 ports accordingly :)

Also, without some of these fixes Macports on Rosetta is not really functional – and I think fixing Rosetta case is useful, since few ppl nowadays have PPC hardware, while using 10.6.x in virtual machine is easy for anyone wishing to build, fix or test PPC software.

**Review by mascguy — APPROVED** [review]
LGTM. And let's defer the discussion relative to encapsulating any of this into a portgroup, for a later time: It's easy enough to find all of these based on the fix patterns.

I'll merge, once Kirill's toolchain-related PRs have finished building.

**Comment by mascguy** [comment]
On 2nd thought, given that this only affects 10.6 PPC, there's no need to wait. Thanks Sergey!

**Comment by barracuda156** [comment]
@mascguy Great, thanks!

**Pull request merged**
