### PR TITLE
Improvements for Xcode Clang + OpenMP

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description
Things that would eventually be needed for macports/macports-base#247

###### Type(s)

- [x] bugfix
- [x] enhancement

###### Tested on

macOS 10.15.7
Xcode 12.4 command line tools

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
The only idea I have for this pull request so far is to have CMake portgroups set `OpenMP_C_INCLUDE_DIR` and `OpenMP_CXX_INCLUDE_DIR` (see https://cmake.org/cmake/help/latest/module/FindOpenMP.html). These would be needed because Xcode clang is unaware of ${prefix}/include/libomp headers, unlike MacPorts clang; one port that could use this is `vtk-m +openmp` (ping @reneeotten).

Although the approach I used appears to work as I expect, I do not know if how or where I have proposed setting this is at all correct.

**Comment by chrstphrchvz** [comment]
> Although the approach I used appears to work as I expect, I do not know if how or where I have proposed setting this is at all correct.

I would be inclined to have this reviewed by someone more familiar with the CMake portgroups. Maybe @cjones051073 ?

**Comment by cjones051073** [comment]
Changes seem OK enough to me. cannot really comment on how much they help with OpenMP builds as I am not familiar with them really.

**Comment by chrstphrchvz** [comment]
I do not expect to make any progress on this anytime soon.

**Comment by reneeotten** [comment]
@chrstphrchvz so do you want to close this or do you intend to work on this in the near future?

**Pull request closed without merging**
