### PR TITLE
libopus: update to 1.3

### PR DESCRIPTION
**Pull request by mark4o**
* update to version 1.3
* update homepage to https

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.12.6 16G1510
Xcode 9.2 9C40b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. As @jeremyhu seems to want to review changes to his ports more strictly than other people who set `openmaintainer`, we'll wait for the 72 hour timeout to pass.

**Comment by dbevans** [comment]
This port builds without problems and is ABI compatible with the previous version so no revbumps required.  Otherwise not particularly controversial and, with no objections from @jeremyhu in a week, I see no reason why it shouldn't be merged.

**Comment by pmetzger** [comment]
Merged. Thanks, @dbevans.

**Comment by jeremyhu** [comment]
Thanks

**Pull request merged**
