### PR TITLE
mail/notmuch: Update to 0.29

### PR DESCRIPTION
**Pull request by rseichter**
Notmuch now requires GMime 3.0.3 or higher.

### CODE REVIEW

**Comment by rseichter** [comment]
Anything I can do to have this pull request relabeled as an update? I changed the description, but to no effect.

As for the failed checks, I assume this is due to some issue on the server side that I cannot influence?

**Comment by cjones051073** [comment]
> Anything I can do to have this pull request relabeled as an update? I changed the description, but to no effect.
> 
> As for the failed checks, I assume this is due to some issue on the server side that I cannot influence?

The build failures look real to me, take a look for instance at

https://paste.z0k.xyz/8352cabdee6f

```
install -m0644 doc/_build/texinfo/notmuch-address.info doc/_build/texinfo/notmuch-compact.info doc/_build/texinfo/notmuch-config.info doc/_build/texinfo/notmuch-count.info doc/_build/texinfo/notmuch-dump.info doc/_build/texinfo/notmuch-emacs-mua.info doc/_build/texinfo/notmuch-insert.info doc/_build/texinfo/notmuch-new.info doc/_build/texinfo/notmuch-reindex.info doc/_build/texinfo/notmuch-reply.info doc/_build/texinfo/notmuch-restore.info doc/_build/texinfo/notmuch-search.info doc/_build/texinfo/notmuch-show.info doc/_build/texinfo/notmuch-tag.info doc/_build/texinfo/notmuch.info doc/_build/texinfo/notmuch-hooks.info doc/_build/texinfo/notmuch-properties.info doc/_build/texinfo/notmuch-search-terms.info doc/_build/texinfo/notmuch-emacs.info /opt/local/var/macports/build/_Users_vsts_agent_2.152.1_work_1_s_mail_notmuch/notmuch/work/destroot/opt/local/share/info
install: doc/_build/texinfo/notmuch-emacs.info: No such file or directory
make: *** [install-info] Error 71
make: Leaving directory `/opt/local/var/macports/build/_Users_vsts_agent_2.152.1_work_1_s_mail_notmuch/notmuch/work/notmuch-0.29'
Command failed:  cd "/opt/local/var/macports/build/_Users_vsts_agent_2.152.1_work_1_s_mail_notmuch/notmuch/work/notmuch-0.29" && /usr/bin/make -w install DESTDIR=/opt/local/var/macports/build/_Users_vsts_agent_2.152.1_work_1_s_mail_notmuch/notmuch/work/destroot 
Exit code: 2
```

**Comment by rseichter** [comment]
I based my assumption on the following errors:

> Failed to fetch python36: Could not resolve host: www.python.org
Failed to fetch docbook-xml-4.5: Could not resolve host: docbook.org

These did obviously not look like build-internal issues to me. The following lines found in the log you posted are different:

> WARNING: "texinfo_documents" config value references unknown document notmuch-emacs
[...]
install: doc/_build/texinfo/notmuch-emacs.info: No such file or directory

Looks like that build was done using `--without-emacs`, so it gives me a starting point.

**Comment by cjones051073** [comment]
The travis tend to be much less reliable than the azure ones. If the travis builds fail they can be due to transient issues with travis, and nothing to do with the port. I tend to ignore travis failures.

Azure failures, on the other hand, tend to be more reliable and more often than note point to real issues. This was one of the logs I posted.

**Comment by rseichter** [comment]
I am still trying to figure out how the CI process works. If a port has variants, like this one does (+emacs), will the CI builds be run both with and without variant(s)? If several variants are available, will the builds be run with different combinations of these variants (the number of possible variant combinations can of course rise pretty quickly).

**Comment by rseichter** [comment]
I have reported this as an upstream bug. It has been confirmed as such, and the suggested workaround does prevent the build from breaking, but is not complete yet.

**Comment by pmetzger** [comment]
> If a port has variants, like this one does (+emacs), will the CI builds be run both with and without variant(s)?

No.

**Comment by rseichter** [comment]
Well, the Azure builds were successful with the patch I included, that's a relief.

**Comment by rseichter** [comment]
The patch has now been [made official](https://notmuchmail.org/pipermail/notmuch/2019/028271.html) by David Bremner.

Anything else that needs doing for this pull request?

**Comment by cjones051073** [comment]
I guess not, thanks.
Once the configure patch makes it into an official release, it can then just be removed.

**Comment by cjones051073** [comment]
Seems to be failing during configure for a number of platforms with the buildbots though... 

https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/90727/steps/install-port/logs/stdio

can you please take a look.

**Comment by rseichter** [comment]
Looks weird to me. The sanity checks for Xapian etc. seem to succeed, but then there's an error  "The dependencies of notmuch could not be satisfied."

The following stands out a bit:
```
Checking for GMime session key extraction support... usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
No.
```
Incorrect use of `mktemp` during `configure`?

**Comment by cjones051073** [comment]
Agreed, it looks a little odd. Note the errors are only on 10.10 and older. The newer OSes are OK.
Perhaps they have a macOS version check happening, failing, but not really reporting precisely why ?
Given this is only happening on older systems, its not super urgent, but still we like to support back as far as we can. Also, its often the case upstream thinks older OSes cannot work, but in fact in macports they can because we have mechanisms in place (like our own compilers, and the legacysupport PG) so perhaps if you feel inclined you could follow up with upstream as to what exactly is likely failing here ?

**Comment by cjones051073** [comment]
actually, perhaps it is mktemp. This looks very similar

https://github.com/elasticdog/transcrypt/issues/34

**Comment by rseichter** [comment]
It is mktemp, specifically Apple's ancient version of it. 😡
```
> /usr/bin/mktemp -h
/usr/bin/mktemp: illegal option -- h
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
```
For crying out loud. That one does not even understand the `-p` option which replaces the deprecated `-t` option of GNU coreutils' mktemp.

**Comment by cjones051073** [comment]
Well, to be fair, macOS10.10 is pretty old now as well ;)

Anyway, there  might be a way out. The MacPorts port `coreutils` provides a newer version. However, to avoid conflicts it does not install them in the main prefix, so that they would be found by default. Instead they are installed under `${prefix}/libexec/gnubin` e.g.

```
Oberon ~ > port contents coreutils | grep mktemp
  /opt/local/bin/gmktemp
  /opt/local/libexec/gnubin/man/man1/mktemp.1.gz
  /opt/local/libexec/gnubin/mktemp
  /opt/local/share/man/man1/gmktemp.1.gz
```

Does upstream provide a configuration option to set the `mktemp` binary to use ? If so you could try making `coreutils` a build dependency, and then configure it to use the above. If not, you could try patching the configure script to force it to find ours, via a `reinplace` or similar.

**Comment by rseichter** [comment]
> Well, to be fair, macOS10.10 is pretty old now as well ;)

The output shown [above](https://github.com/macports/macports-ports/pull/4556#issuecomment-500484045) is from macOS 10.14.5, so Apple is still shipping that dinosaur-mktemp as of today. 😝

That actually makes me wonder why the build succeeded in the build farm for recent macOS versions; are these builds based on GNU coreutils? I definitely use coreutils in my shell, so it took me a little while to figure out why the build croaked. I have opened #4573 for now, with a patch that should work for the time being.

**Comment by cjones051073** [comment]
hmmm, whatever they are doing it seems to work on 10.11+...

**Comment by cjones051073** [comment]
The build bots will not be use coreutils, unless the port explicitly depends on it, and then explicitly uses the binaires.

**Comment by rseichter** [comment]
Would it be prudent to add `depends_build port:coreutils` then?

**Comment by rseichter** [comment]
Oh wait, did you mean I'd then need to use `/full/path/to/mktemp` instead of just `mktemp`?

**Pull request merged**
