### PR TITLE
Proguard

### PR DESCRIPTION
**Pull request by lhaeger**
###### Tested on

macOS 10.15.4 19E266
Xcode 11.4 11E146

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
it seems a little strange to add the github PG only for the livecheck and have it keep using sourceforge as master_site. Why don't you fix the livecheck for SourceForge instead if you don't want to migrate completely to GitHub?

**Comment by lhaeger** [comment]
Because it works and I have other things to do. Feel free to change it, I'm not going to maintain this port, this is just a one-off.

**Comment by reneeotten** [comment]
> Because it works and I have other things to do. Feel free to change it, I'm not going to maintain this port, this is just a one-off.

okay, so you can set the `livecheck.regex` to it work for SourceForge as well (in addition I added a modeline and update the homepage). Is it okay for me to force-push to your branch to update the PR with these changes?

**Comment by lhaeger** [comment]
> Is it okay for me to force-push to your branch to update the PR with these changes?

Thanks a lot, just go ahead. "Allow edits from maintainers" is checked.

**Pull request merged**
