### PR TITLE
py-ansible: update to 3.0.0 and introduce port py-ansible-base 2.10.6

### PR DESCRIPTION
**Pull request by tsabirgaliev**
ansible starting with 2.9.x breaks the old ansible into ansible and
ansible-base, thus upgrade and new port introduction comes in a single
commit

fixes https://trac.macports.org/ticket/62324

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.2.1 20D74
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by tsabirgaliev** [comment]
@jhoyt4 do you have any input on this?

**Comment by jhoyt4** [comment]
may conflict with [PR 10074](https://github.com/macports/macports-ports/pull/10074)

**Comment by jhoyt4** [comment]
I personally prefer them to be in the same Portfile - but I'm not the maintainer - so they can choose their preferred path.

**Comment by jhoyt4** [comment]
Won't v3 also require a matching ansible-base? (could be wrong here)

**Comment by tsabirgaliev** [comment]
> Won't v3 also require a matching ansible-base? (could be wrong here)

They appear to be independent, according to https://www.ansible.com/blog/ansible-3.0.0-qa

**Comment by jhoyt4** [comment]
> That is also why I thought they should be represented by separate ports

You have me sold. Let's wait for @adfernandes to weigh in, and then I'll close my PR.

**Comment by adfernandes** [comment]
Thank you very much, both @tsabirgaliev and @jhoyt4! I appreciate both of your work and your diligence!

I'll merge as soon as CI finishes.

**Pull request merged**
