### PR TITLE
apr-util, mod_qos, subversion: use Berkeley db48, add mode line

### PR DESCRIPTION
**Pull request by Schamschula**
See: https://trac.macports.org/ticket/57707

###### Type(s)

- [X] enhancement

###### Tested on
macOS 10.13.6 17G3025
Xcode 10.1 10B61

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] tried a full install with `sudo port -vst install`?

### CODE REVIEW

**Comment by danielluke** [comment]
Quoting from [#56229](https://trac.macports.org/ticket/56229):

"The reason why subversion (and a bunch of other ports) are stuck on bdb4.6 is that was the last release before Oracle changed the license. Originally, Oracle's license for later bdb releases was pretty incompatible with normal use - I think they fixed that. Someone needs to verify that the licensing is OK for newer bdb (I was going to do it, but I guess I've never gotten around to it, and it has been quite a while). We should move to the latest bdb release that is supported by subversion (and the other ports) that has a license that is reasonable."

I think we need to bump at least subversion, apr-util, and openldap.

**Comment by Schamschula** [comment]
Well openldap was switched a while ago:

https://github.com/macports/macports-ports/commit/237761f56c4aac2f6ad6301e4fb6da228b8e9eaf#diff-58264f1fdac2f538224db650c9ecb68c

**Comment by danielluke** [comment]
I assume you haven't run the apr-util and subversion test suites with this change (I'll do that now). As far as de-tabbing and the modeline per policy maintainers aren't required to use them (and I tend to not) ... but I'm sick of people asking about it so I give up ;-)

**Comment by danielluke** [comment]
Change needs to be propagated to all of the subversion-bindings ports as well.

**Comment by Schamschula** [comment]
I ran the test suites for all apr-util and subversion bindings: no errors.

**Comment by danielluke** [comment]
You just beat me to it (javajhl tests are finishing on my local box now). Thanks for your work on this.

**Comment by l2dy** [comment]
```
# port -vt install subversion
[...]
Could not open /opt/local/lib/db46/libdb-4.6.dylib: Error opening or reading file (referenced from /opt/local/lib/libserf-1.dylib)
--->  Found 1 broken file, matching files to ports
--->  Found 1 broken port, determining rebuild order
You can always run 'port rev-upgrade' again to fix errors.
The following ports will be rebuilt: serf1 @1.3.9
```

**Comment by danielluke** [comment]
ok, so serf1 needs a revbump, I'll commit one.

**Comment by jmroot** [comment]
Also serf0. All dependents of apr-util should probably be checked actually.

**Comment by Schamschula** [comment]
Indeed. The link check did not find that apache2 was broken...

There are only a small number of dependents: https://github.com/macports/macports-ports/commit/e7fb8dbdaf60cdc8522cde664d48c7ca39be4016

**Pull request merged**
