### PR TITLE
opencascade: update to 7.7.0 ; gmsh: update to 4.11.0; deal.ii: update to 9.4.0

### PR DESCRIPTION
**Pull request by catap**
#### Description

This is nessesary update of affected ports by https://github.com/macports/macports-ports/pull/16835

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.6 21G115 x86_64
Xcode 14.1 14B47b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by catap** [comment]
CI had failed because of https://trac.macports.org/ticket/66227 ; and based on https://ports.macports.org/port/freecad/details/ it is completley broken.

Shall I exclude revbump from this broken port?

**Comment by catap** [comment]
I've excluded FreeCAD from this PR because it requires opencascade before 7.6.0 which MacPorts already had.

See: https://github.com/macports/macports-ports/pull/16888

**Comment by reneeotten** [comment]
@catap Can you resolve the conflicts - then I'll merge. Thanks!

**Comment by catap** [comment]
@reneeotten may I ask you to review https://github.com/macports/macports-ports/pull/17025 which should fix a build of netgen before I've rebased this? Thanks!

**Comment by reneeotten** [comment]
I merged that PR so once you have a change you can resolve the conflict(s).

**Comment by reneeotten** [comment]
ping @catap - can you resolve the conflict(s) please?

**Comment by reneeotten** [comment]
@catap the "kicad" port appears to be broken - did you observe that locally as well?

**Comment by catap** [comment]
@reneeotten the issue is much deeper.

`tiff` were updated and it changes library name from `libtiff.5.dylib` to `libtiff.6.dylib` that brokes a lot of ports :( 

See: https://github.com/macports/macports-ports/commit/4c3e0a389b469ee94ecd26376f18f1adccb7fde1

On my machine `kicad` is also failed with:
```
:info:configure Traceback (most recent call last):
:info:configure   File "<string>", line 1, in <module>
:info:configure   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wx/__init__.py", line 17, in <module>
:info:configure     from wx.core import *
:info:configure   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wx/core.py", line 12, in <module>
:info:configure     from ._core import *
:info:configure ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wx/_core.cpython-310-darwin.so, 0x0002): Library not loaded: '/opt/local/lib/libtiff.5.dylib'
:info:configure   Referenced from: '/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/libwx_osx_cocoau_core-3.1.5.0.0.dylib'
:info:configure   Reason: tried: '/opt/local/lib/libtiff.5.dylib' (no such file), '/usr/local/lib/libtiff.5.dylib' (no such file), '/usr/lib/libtiff.5.dylib' (no such file)
```

**Comment by catap** [comment]
Here the fix: https://github.com/macports/macports-ports/pull/17169

**Comment by catap** [comment]
@reneeotten seems that CI is failed by timeout. What should I do?

**Comment by catap** [comment]
one more rebase to make one more attempt

**Comment by catap** [comment]
@reneeotten I have no idea how to pass CI because its failed on timeout.

**Comment by MarcusCalhoun-Lopez** [comment]
These changes work on my machine.
Is there any reason to to merge them?

**Comment by catap** [comment]
@MarcusCalhoun-Lopez if you merge it I’ll be very appreciated because it unblocks the Pr to install both TBB on the same machine

**Pull request merged**
