### PR TITLE
gtk-internet-radio-locator: update to 0.0.1

### PR DESCRIPTION
**Pull request by oleaamot**
#### Description

gnome-internet-radio-locator: replace port with gtk-internet-radio-locator
gtk-internet-radio-locator: update to 0.0.1

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.4 17E202
Xcode 9.3.1 9E501 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Why the replacement?

**Comment by oleaamot** [comment]
gtk-internet-radio-locator is a new port of gnome-internet-radio-locator to
gtk+ 4.0.

**Comment by pmetzger** [comment]
Please squash these commits? If you don't know how to do that, ask.

**Comment by pmetzger** [comment]
> I have squashed the update into one commit.

No, you haven't. You just added another commit on top.

**Comment by pmetzger** [comment]
Furthermore, it appears that your new commit altered files in `gnome`, which was not part of your apparent intended commits at all.

**Comment by oleaamot** [comment]
OK.  Cancel this pull request.  I will submit a new pull request.

**Comment by pmetzger** [comment]
I'll close it, but what happens when changes are needed on your next request? It would be worthwhile for you to be in a position to get help from us.

**Pull request closed without merging**
