### PR TITLE
volk: update to 2.5.1

### PR DESCRIPTION
**Pull request by michaelld**
#### Description

volk: update to 2.5.1 ... correctly this time: use `std::filesystem` if it works and otherwise use `boost::filesystem`. While not ideal -- there will be a boost dependnecy regardless of which `::filesystem` is used -- this should work well across all OSX versions.

Closes: https://trac.macports.org/ticket/65377

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.6.8 20G720
Xcode 12.3 12C33

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by michaelld** [comment]
Not sure our QA/CI goes back far enough to verify that this PR will work on older macOS, but it should since it adds back the changes that removed the optional use of `boost::filesystem` in place of `std::filesystem`. Worth considering!

**Comment by mascguy** [comment]
> Not sure our QA/CI goes back far enough to verify that this PR will work on older macOS, but it should since it adds back the changes that removed the optional use of `boost::filesystem` in place of `std::filesystem`. Worth considering!

Michael, let me know if you need help validating this on any particular older macOS release(s).

**Comment by michaelld** [comment]
@mascguy thanks! Even just validating on any of 10.7-10.14 ... those where the default libc++ doesn't provide full std::filesystem functionality even when in c++17 mode ... any one of those would be great to do validation on ... please and thank you!

I will see if I can get one of my buildbots running those older OSX running from remote ... guessing no but sometimes one gets lucky! Won't be back in my office where those systems are until mid-next week.

**Comment by ra1nb0w** [comment]
still get
```
:info:configure -- Looking for C++ include filesystem
:info:configure -- Looking for C++ include filesystem - not found
:info:configure -- Looking for C++ include experimental/filesystem
:info:configure -- Looking for C++ include experimental/filesystem - not found
:info:configure CMake Error at cmake/Modules/FindFILESYSTEM.cmake:272 (message):
:info:configure   Cannot compile a simple program using std::filesystem
:info:configure Call Stack (most recent call first):
:info:configure   CMakeLists.txt:178 (find_package)
:info:configure -- Configuring incomplete, errors occurred!
```
[CMakeError.log](https://github.com/macports/macports-ports/files/9022870/CMakeError.log)
[main.log](https://github.com/macports/macports-ports/files/9022871/main.log)

**Comment by michaelld** [comment]
@ra1nb0w filesystem addback patch wasn't applied somehow ...

**Comment by mascguy** [comment]
> ```
> :info:configure -- Looking for C++ include filesystem
> :info:configure -- Looking for C++ include filesystem - not found
> :info:configure -- Looking for C++ include experimental/filesystem
> :info:configure -- Looking for C++ include experimental/filesystem - not found
> :info:configure CMake Error at cmake/Modules/FindFILESYSTEM.cmake:272 (message):
> :info:configure   Cannot compile a simple program using std::filesystem
> :info:configure Call Stack (most recent call first):
> :info:configure   CMakeLists.txt:178 (find_package)
> :info:configure -- Configuring incomplete, errors occurred!
> ```

I'm seeing the same failure on 10.12. Though both patches are being applied.

**Comment by ra1nb0w** [comment]
> @ra1nb0w filesystem addback patch wasn't applied somehow ...

the patch is applied correctly. You can't use `REQUIRED` in

```
# Check if we have std::filesystem
find_package(FILESYSTEM COMPONENTS Final Experimental)
```

then it builds fine.

**Comment by michaelld** [comment]
Good catch @ra1nb0w  ! I just pushed that tweak here. @mascguy can you retest on 10.12 please? Hopefully this does the trick fully now! If so and one of y'all wants to merge go for it!

**Comment by mascguy** [comment]
> Good catch @ra1nb0w ! I just pushed that tweak here. @mascguy can you retest on 10.12 please? Hopefully this does the trick fully now! If so and one of y'all wants to merge go for it!

Retested on various macOS releases, and builds for some versions (including 10.12). But I'm seeing failures for a few earlier releases:

```
:info:build /opt/local/bin/clang-mp-14 -pipe -Os -DNDEBUG -I/opt/local/libexec/boost/1.76/include -Wall -Werror=incompat
ible-pointer-types -Werror=pointer-sign -O3 -DNDEBUG -arch x86_64 -mmacosx-version-min=10.8 -Wl,-search_paths_first -Wl,
-headerpad_max_install_names -L/opt/local/libexec/boost/1.76/lib -Wl,-headerpad_max_install_names CMakeFiles/list_cpu_fe
atures.dir/src/utils/list_cpu_features.c.o -o list_cpu_features  -Wl,-rpath,/opt/local/lib libcpu_features.a 
:info:build Undefined symbols for architecture x86_64:
:info:build   "_FillX86BrandString", referenced from:
:info:build       _main in list_cpu_features.c.o
:info:build   "_GetX86CacheInfo", referenced from:
:info:build       _main in list_cpu_features.c.o
:info:build   "_GetX86FeaturesEnumName", referenced from:
:info:build       _main in list_cpu_features.c.o
:info:build   "_GetX86FeaturesEnumValue", referenced from:
:info:build       _main in list_cpu_features.c.o
:info:build   "_GetX86Info", referenced from:
:info:build       _main in list_cpu_features.c.o
:info:build   "_GetX86Microarchitecture", referenced from:
:info:build       _main in list_cpu_features.c.o
:info:build   "_GetX86MicroarchitectureName", referenced from:
:info:build       _main in list_cpu_features.c.o
:info:build ld: symbol(s) not found for architecture x86_64
:info:build clang: error: linker command failed with exit code 1 (use -v to see invocation)
:info:build make[2]: *** [cpu_features/list_cpu_features] Error 1
```

Followed by a number of failures related to use of `INT_MAX`:

```
:info:build In file included from /Volumes/Mac-MacPorts/opt/local/var/macports/build/_Volumes_Mac-MacPorts_opt_macports_
sources_ports_enabled_science_volk/volk/work/build/lib/volk_machine_generic_orc.c:86:
:info:build /Volumes/Mac-MacPorts/opt/local/var/macports/build/_Volumes_Mac-MacPorts_opt_macports_sources_ports_enabled_
science_volk/volk/work/volk-2.5.1/kernels/volk/volk_32f_s32f_convert_32i.h:242:21: warning: implicit conversion from 'in
t' to 'float' changes value from 2147483647 to 2147483648 [-Wimplicit-const-int-float-conversion]
:info:build     float max_val = INT_MAX;
:info:build           ~~~~~~~   ^~~~~~~
:info:build /Volumes/Mac-MacPorts/opt/local/libexec/llvm-14/lib/clang/14.0.6/include/limits.h:46:19: note: expanded from
 macro 'INT_MAX'
:info:build #define INT_MAX   __INT_MAX__
:info:build                   ^~~~~~~~~~~
:info:build <built-in>:47:21: note: expanded from here
:info:build #define __INT_MAX__ 2147483647
:info:build                     ^~~~~~~~~~

[...more of the same, across a number of source files...]
```

This is occurring with `clang-14`, so blacklisting older Clangs won't help. But hopefully this is something easily-fixable...?

**Comment by michaelld** [comment]
Interesting. I'm updating my 10.12 buildbot right now for testing NumPy, and will test Volk on it -- though it sounds like that will likely work. Once that's updated I'll boot it into 10.11 & do the same there, but for Volk so it should go faster. Hopefully with hands-on the issues I can more easily fix them.

**Comment by michaelld** [comment]
Might be that if `cpu-features` isn't at the current release/commit then updating it might do the trick. Might not too; might be that those symbols for some reason don't exist on specific OSX and/or Clang ... IDK

**Comment by reneeotten** [comment]
upstream's version is currently at 3.0.0; let's update to that first and see whether some of the issues mentioned here have been resolved. Nothing on this PR has happened in over a year...

**Pull request closed without merging**
