### PR TITLE
arpwatch: fix arm platform and some minor issues.

### PR DESCRIPTION
**Pull request by kamischi**
#### Description

- add arm in configure
- update checksums
- update homepage
- install text files without executable flag.

###### Type(s)
- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 12.2.1 21D62 arm64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kamischi** [comment]
The program has a small usage problems. It uses a file with the default name arp.dat and it closes, if there is no such file. The file name can be passed from the command line with the option -f. The file is then opened in util.c with
`	register FILE *f;

	if ((f = fopen(arpfile, "r")) == NULL) {
`
I am not really good in C, but as much as I understand fopen, it opens in the current directory, which would not really be appropriate. Is this correct?
Am I right, that the source code should be fixed, so that arpfile defaults to /opt/local/share/arpwatch-$version/arp.dat?

Any other suggestions?

Michael Schindler.

**Comment by kamischi** [comment]
Please consider commit d1df372 as a suggestion. I tested it and it works. The files are in  /opt/local/share/arpwatch-$version.

**Comment by reneeotten** [comment]
@kamischi it looks like the latest version is 3.3 (see https://ee.lbl.gov/downloads/arpwatch/) ; please update to this version.

**Comment by reneeotten** [comment]
@kamischi feel free to push to this PR and reopen once you had the chance to take care of the update

**Pull request closed without merging**
