### PR TITLE
cargo2port: Update to 0.2.1

### PR DESCRIPTION
**Pull request by halostatue**
#### Description

cargo2port: Update to 0.2.1

##### Tested on

macOS 14.3 23D56 arm64
Xcode 15.1 15C65

##### Verification

Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by halostatue** [comment]
I can close this one or update it before merge, but I just found a bug in 0.2.0 that I introduced in a PR during test addition. This version should not be merged, but I have opened a new PR (ld2y/cargo2port#5) that should fix this.

**Comment by pmetzger** [comment]
If you think it should be closed, please close it?

**Comment by halostatue** [comment]
@pmetzger This is now properly ready for review.

**Comment by pmetzger** [comment]
LGTM, though @l2dy will have to comment (or 72 hours will have to elapse.)

**Pull request merged**
