### PR TITLE
texlive-bin: rebuild with patch for poppler 0.69.0

### PR DESCRIPTION
**Pull request by dbevans**
This builds for me but I'll leave it to the maintainer to test/verify.

Closes: https://trac.macports.org/ticket/57162

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65
Xcode 10.0 10A255 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?

### CODE REVIEW

**Comment by pmetzger** [comment]
@drkp A quick review would be appreciated. This is a pretty critical port, and it's closed maintainer.

**Comment by norbusan** [comment]
Sorry, I don't have time to check what is going on, but Akira added files specifically for poppler 0.69:
./pdftexdir/pdftoepdf-poppler0.68.0.cc
./pdftexdir/pdftoepdf-poppler0.69.0.cc
./pdftexdir/pdftosrc-newpoppler.cc

**Comment by a-kakuto** [comment]
FYI, the new lua[jit]tex in the present TeX Live SVN never uses poppler.

Best,
Akira

>

**Comment by mojca** [comment]
While true that poppler is no longer used by luatex, it's not too helpful in this case just yet:
* we are packaging TeX Live 2018 (without any package updates other than security fixes until the next release
* the replacement library `pplib` is still in its alpha stage, quite some bugs were discovered and probably not yet fixed (and many not discovered yet)
* aren't there other users of poppler (pdfTeX maybe?)

**Comment by pmetzger** [comment]
Regardless, given that this currently doesn't build, I think we should integrate it soon.  Right now it doesn't build at all, so I think at worst we're changing it from one broken state to another.

**Comment by ProgrammingPoet** [comment]
This seems to be a showstopper when setting up texlive via macports. The only resolution seems to either be accepting the patching or rolling back poppler to last version will allow Tex love to both build and function. I’m not sure why these ports aren’t kept in sync with each other but it seems that one was rushed out before seeing what the downstream effects might be.

**Comment by dbevans** [comment]
@drkp OK, here's my take on this: (sorry its a bit late but I'll add it for completeness)

The patch I proposed in this PR applies to the current version, r47642 to fix build errors due to
the an API change in poppler 0.69.  Use of char * is no longer accepted in arguments to  dictAdd
and similar (must be const char *) and functions that get keys from both obj's and dict's always return const char *.

Files patched by patch-poppler-0.69.diff are:

texk/web2c/luatexdir/lua/lepdflib.cc
texk/web2c/luatexdir/image/pdftoepdf.w
texk/web2c/pdftexdir/pdftoepdf-newpoppler.cc

I fixed this by converting appropiate key variables from char * to const char * and removing (const char *) casts from return values.

The upstream fix at r48742 provides pdftoepdf-poppler0.69.0.cc which replaces pdftoepdf-newpoppler.cc and purportedly the use poppler in the luatex files has been removed entirely in other commits. 

The changes in pdftoepdf-poppler0.69.0.cc are just the opposite of mine.  Use of char * variables is retained and cast to const char * where necessary.  I think the result is equivalent.

In general, I would go with the upstream solution over our own where possible but this make take some time.  The easiest way to do this would to be promote our port version to r48742 and replace references to pdftoepdf-newpoppler.cc to pdftoepdf-poppler0.69.0.cc.

If you want to stay with r47642 then pdftoepdf-newpoppler.cc could be replaced by upstream pdftoepdf-poppler0.69.0.cc but you'd still have to patch the luatex files.

If time is the major concern, I would vote to push this PR for now (assuming you concur that it
fixes the build) as a temporary fix and then work on upgrading to r48742 as the permanent fix.

My two cents.

In self-defense, @ProgrammingPoet,  before pushing the poppler 0.69 update, I did test builds against all  dependents and I only pushed it after I was sure texlive-bin could be fixed by this PR.

**Comment by pmetzger** [comment]
If we don't keep Poppler up to date, we end up with security bugs that are also painful. The situation is bad regardless, but I think @dbevans made the right call.

**Pull request merged**
