### PR TITLE
miniupnpc: update to 2.2.8; update/revbump dependents

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update miniupnpc, update/revbump dependents.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by edilmedeiros** [comment]
6034468e9e6b41070cc458766c9cd8e7b6de6336 by itself looks good to me.

I was keeping this update on hold from my side since it introduces incompatible API changes I believe will break all the dependents builds: [bitcoin](https://ports.macports.org/port/bitcoin/) - patch available in [this PR](https://github.com/bitcoin/bitcoin/pull/30283).
[eiskaltdcpp](https://ports.macports.org/port/eiskaltdcpp/)
[godot](https://ports.macports.org/port/godot/)
[godot-3.2](https://ports.macports.org/port/godot-3.2/)
[i2pd](https://ports.macports.org/port/i2pd/)
[litecoin](https://ports.macports.org/port/litecoin/)
[libretroshare](https://ports.macports.org/port/libretroshare/)
[retroshare-qt4](https://ports.macports.org/port/retroshare-qt4/)
[transmission-qt](https://ports.macports.org/port/transmission-qt/)
[transmission-x11](https://ports.macports.org/port/transmission-x11/)
[Vidalia](https://ports.macports.org/port/Vidalia/)
[wired-server](https://ports.macports.org/port/wired-server/)
[warzone2100](https://ports.macports.org/port/warzone2100/)

**Comment by barracuda156** [comment]
@edilmedeiros Would you like to handle this instead? I can close this PR in favor of yours.
Just pick updates for my ports, so that we do not do unnecessary rebuilds (rather update them than revbump with patches, and then update dropping patches).

**Comment by edilmedeiros** [comment]
No, please do it. Tag me when it's ready so I can review it for you.

**Comment by barracuda156** [comment]
@edilmedeiros I am not planning to update any ports besides of which I maintain myself. Other will be revbumped only (plus patches from upstream, if required).

**Comment by barracuda156** [comment]
> [bitcoin](https://ports.macports.org/port/bitcoin/) - patch available in [this PR]

OMG, this thing builds forever -_-

I have sorted out all my ports and now bitcoin. The rest I will just try to revbump.

P. S. Litecoin no need to revbump, it is broken: https://trac.macports.org/ticket/70470
Vidalia does not link to `miniupnpc` (it might use it at runtime, but the binary is not linked and it did not get broken by miniunpc update).

**Comment by barracuda156** [comment]
@edilmedeiros Provisionally everything should build now.

P. S. Games I have built on Sonoma locally, won’t bother even trying on PowerPC. Other stuff confirmed to build on 10.6 ppc (and on CI for other archs).

**Comment by edilmedeiros** [comment]
I'll have it reviewed by the weekend.

**Comment by edilmedeiros** [comment]
Maybe @catap will want to take a look too.

**Comment by barracuda156** [comment]
@edilmedeiros AFAIK, Kirill is not very active here recently. @catap Just in case, ping :)

**Comment by barracuda156** [comment]
The site is again down:
```
DEBUG: Fetching distfile failed: Failed to connect to miniupnp.free.fr port 80 after 30020 ms: Timeout was reached
  Error: Failed to fetch miniupnpc: Failed to connect to miniupnp.free.fr port 80 after 30020 ms: Timeout was reached
```

**Comment by barracuda156** [comment]
Should we just switch to GitHub instead? This is getting annoying. When I started upgrading, their site was down, and I changed the port to use GutHub tarball. Then site was back, so I submitted without that. Now again nothing fetches from there.

**Comment by edilmedeiros** [comment]
It's annoying indeed. In the bitcoin discussions, we have not settled what to do, but everyone is more concerned about linking sources to the github repo (reproducibility of the builds). I believe we can do it here.

[Brew is linking](https://github.com/Homebrew/homebrew-core/blob/606748f737faf3b2a711b91d799e35feadd0f4c9/Formula/m/miniupnpc.rb#L4C1-L5C64) to https://miniupnp.tuxfamily.org/ which is a mirror maintained by the package maintainers.

```
  url "https://miniupnp.tuxfamily.org/files/download.php?file=miniupnpc-2.2.7.tar.gz"
  mirror "http://miniupnp.free.fr/files/miniupnpc-2.2.7.tar.gz"
```

But I have seen this mirror down as well. Can a port point to alternative sources in case of failure?

**Comment by barracuda156** [comment]
> Can a port point to alternative sources in case of failure?

There can be several master_sites specified, by we need identical checksums. GitHub is unlikely to be down )

**Comment by edilmedeiros** [comment]
It is probably the best to link to github releases at https://github.com/miniupnp/miniupnp/releases and use the other links as alternatives.

Problem: The project doesn't seem to be consistent with releasing versions at all places. Currently 2.1 at github and 2.2.8 at the main websites.

It does seem to tag releases, which seem to spawn tarballs at https://github.com/miniupnp/miniupnp/tags.

Problem: They don't have consistent hashes with what's in the website.

```shell
$ openssl dgst -sha256 miniupnpc-2.2.8.tar.gz
SHA2-256(miniupnpc-2.2.8.tar.gz)= 05b929679091b9921b6b6c1f25e39e4c8d1f4d46c8feb55a412aa697aee03a93

$ openssl dgst -sha256 miniupnp-miniupnpc_2_2_8.tar.gz
SHA2-256(miniupnp-miniupnpc_2_2_8.tar.gz)= 3d0d49f761f09c1321ceb663d1b008825361d7bd242640c60ae467e82642502a
```

**Comment by barracuda156** [comment]
Using archives from GitHubs is consistent. Using tags is not. Archives are preferred option in MacPorts, when releases are not there or lagging behind, like in this case.

**Comment by reneeotten** [comment]
everyone happy with these changes and is this ready to merge? From a  quick read through this looks all fine to me, but I haven't tested anything myself...

**Comment by barracuda156** [comment]
@reneeotten From my side should be good.

**Comment by edilmedeiros** [comment]
LGTM

**Pull request merged**
