### PR TITLE
qgis3[-ltr], py-geojson: bug fixes and update

### PR DESCRIPTION
**Pull request by nilason**
#### Description

Update `py-geojson` to version 3.0.1 and add support for Python 3.9-3.11.

General overhaul and bug fixes for `qgis3` and `qgis3-ltr` with notable changes:

- Find out path to "mpi.h" for building against `gdal +hdf5` (and remove mpi port group dependence)
- Prettify PostgreSQL variant descriptions by removing dot in versions 10+
- Fix flawed implementation of the `+python_support` variant
- Fix failure to install grass dependency
- Add note on plugin "missing PyQt5.QtWebKit module" error warning

Closes: https://trac.macports.org/ticket/67842
See: https://trac.macports.org/ticket/68006
Closes: https://trac.macports.org/ticket/68016
Closes: https://trac.macports.org/ticket/68081

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6.6 21G646 arm64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by nilason** [comment]
Added a fix for `gdal` build failure with `+libkml` reported with  https://trac.macports.org/ticket/68023.

**Comment by nilason** [comment]
Added an update for `proj9` to version 9.3.0. I added a new  `+lto` variant (Enable Link Time Optimization) and changed to PortGroup cmake 1.1.

Notifying maintainers:
@stromnov for port proj9.

**Comment by nilason** [comment]
Although this is more than ready to be merge, I plan to add a GDAL version update very soon (will be release any day), so please hold on...

**Comment by pmetzger** [comment]
@nilason Do you want this merged? Usually the existence of a PR indicates that you want a merge?

**Comment by nilason** [comment]
> @nilason Do you want this merged? Usually the existence of a PR indicates that you want a merge?

I suggested to wait for an addition of GDAL to reduce the re-builds of especially QGIS. Otherwise it is ready for merge.

**Comment by nilason** [comment]
Finally GDAL update is in. Please review, merge.

**Comment by nilason** [comment]
Ping @reneeotten @mascguy @pmetzger 

Please go ahead and merge, this update is way overdue as it is.
(The CI failure is, as you can see, caused by timeout.)

**Comment by i0ntempest** [comment]
QGIS just had a new release, you might want to put that in here.

**Comment by nilason** [comment]
> QGIS (and LTR) just had a new release, you might want to put that in here.

Thanks, you are right, please hold on for this!

**Comment by nilason** [comment]
QGIS update is added, now please merge.

**Comment by nilason** [comment]
@reneeotten Thanks!

**Pull request merged**
