### PR TITLE
qbs: Update to 2.2.2

### PR DESCRIPTION
**Pull request by ABBAPOH**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.2.1 23C71 x86_64
Xcode 15.2 15C500b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
@ABBAPOH the `qbs-doc` port fails to build with:
```
  CMake Warning at cmake/QbsDocumentation.cmake:155 (message):
    Cannot import lxml and bs4 python modules.  Qbs documentation will not be built.
```

**Comment by ABBAPOH** [comment]
Should I better do a squashed commit? Changes are not related though

**Comment by reneeotten** [comment]
sorry, one more comment: Python 3.12 is MacPorts' default now. Can that version be used instead? You can indeed squash the commits after that.

**Comment by ABBAPOH** [comment]
Is there a way to get the default version instead of hardcoding it to 3.12?

**Comment by reneeotten** [comment]
> Is there a way to get the default version instead of hardcoding it to 3.12?

there is but only if you use the `python` PortGroup which isn't applicable here, so not in this case. There is one more `port lint` thing that ideally should be fixed and then I/we will happily merge:
```
Warning: Line 23 contains tab but modeline says tabs should be expanded
```

**Pull request merged**
