### PR TITLE
yewtube: new port, update dependencies

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

See commits

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by herbygillot** [comment]
Python 3.13 is on the map now, so maybe adding subports for those as well if it's not too much hassle.

**Comment by barracuda156** [comment]
> Python 3.13 is on the map now, so maybe adding subports for those as well if it's not too much hassle.

@herbygillot For `pylast` I tried and dependencies were missing. Other two I do not see a reason to have a zoo of Pythons, they are end-user apps, any one working Python will do (which is 312 at the moment).

**Comment by herbygillot** [comment]
OK, that's fair.  Can we add the `homepage` for `youtube-search-python` as per the lint warning? Other than that, looks good.

**Comment by barracuda156** [comment]
> OK, that's fair. Can we add the `homepage` for `youtube-search-python` as per the lint warning? Other than that, looks good.

@herbygillot Done

**Comment by barracuda156** [comment]
@herbygillot Are we good with this?

**Pull request merged**
