### PR TITLE
Sophus: long due update; add tests variant

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

The port has not been update in 5 years since its introduction: https://github.com/macports/macports-ports/pull/1360
Update to current version.
Add support for tests. (Not making a default, since building tests is quite demanding in terms of compilation time.)

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

On PPC there are a few failures with tests: https://github.com/strasdat/Sophus/issues/448

@ex-purple @pmetzger Please review this when you can.

### CODE REVIEW

**Review by harens — COMMENTED** [review]
Thanks @barracuda156. LGTM, but it seems like they've changed the number versioning: https://github.com/strasdat/Sophus/commit/d9610ad5536bd601d42df0d33a3abdff9456679c

**Comment by barracuda156** [comment]
> Thanks @barracuda156. LGTM, but it seems like they've changed the number versioning: https://github.com/strasdat/Sophus/commit/d9610ad5536bd601d42df0d33a3abdff9456679c

Ok, I will update it today. Thank you.

**Comment by barracuda156** [comment]
@harens Updated to changed versioning.

**Review by harens — APPROVED** [review]
Thanks @barracuda156! 👍

**Pull request merged**
