### PR TITLE
mfem: new port in science

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

New port: https://github.com/mfem/mfem

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
For w/e reason, dependencies fail: in particular,
```
Installing dependency (76 of 77) 'mpich-clang16' with variants '+gcc12' ... [FAIL]
```
Why?

**Comment by barracuda156** [comment]
Let me try to trick the incapable build system and put non-required deps into a variant.

**Comment by barracuda156** [comment]
Let me rest from this port for a bit. Configure is broken and ignores passed args…

**Comment by barracuda156** [comment]
Eventually had to move for now all MPICH-seeking dependencies into variants, otherwise CI fail. And I do not want to make this fully MPICH-based, not yet. Without MPICH performance looks good.

**Comment by barracuda156** [comment]
@herbygillot This fantastic piece of scientific software finally has built. After countless iterations.

**Comment by herbygillot** [comment]
Thank you for your efforts, @barracuda156.

**Comment by barracuda156** [comment]
@herbygillot Thank you!

**Pull request merged**
