### PR TITLE
img2pdf: add python313 variant, remove python38 variant (including dependencies)

### PR DESCRIPTION
**Pull request by markmentovai**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 15.1 24B83 arm64
Xcode 16.1 16B40

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by Schamschula** [comment]
I'm OK with removing py38 and adding py313 subports and variants (I would have done so myself in the near future), but please wait to make the python313 variant default in `img2pdf` until January 1, 2025. It is standard MacPorts practice make the new version default at the beginning of the next calendar year.

**Comment by markmentovai** [comment]
@Schamschula OK, updated to keep `img2pdf+python312` the default for now.

**Comment by Schamschula** [comment]
Thanks!

**Comment by Schamschula** [comment]
Did you check that other depend py38 packages have been dropped?

I see:

```
port echo rdepends:py38-deprecated
py-test-runner                  
py38-fabric                     
py38-pikepdf                    
py38-test-runner
```

In other words this update will break `py-test-runner` which apparently is still defaulting to p`py38-test-runner` and `py38-fabric` .

**Comment by markmentovai** [comment]
I did check. That's why I didn’t remove `py38-deprecated`.

**Pull request merged**
