### PR TITLE
mpv: add bluray variant and aacs encryption support 

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by i0ntempest** [comment]
Maybe a better idea is to add this as a variant?

**Comment by kencu** [comment]
> Maybe a better idea is to add this as a variant?

I initially though so myself, but mpv has WWWAAAAYYYY too many variants as it is, I thought (we should maybe start culling those), and this library miraculously builds on everything <http://packages.macports.org/libaacs/> so I figured leave it as you had it. Others may not agree.

**Comment by i0ntempest** [comment]
I've just made a new bluray variant, to avoid undeclared dependency and moved libaacs into it.
I don't think many variants is a bad thing? It just means users have more choices on features. Or maybe you could explain?

**Comment by kencu** [comment]
If you are a user, I think this is very confusing. Not to mention, hardly ever tested on anything, other than the default variants.

If you are a programmer/power user, this many variants might be kinda cool -- but you don't need them anyway, as you just edit the Portfile and flip a few switches.

Homebrew has moved to NO variants for this exact reason. That's a bit extreme for us, but 22 variants (SO FAR) means 22! (factorial) ways of building this.

That is -- IMHO -- insane.

But -- other may (and seeing it's me suggesting this, probably will) have other opinions.

```
$ port variants mpv
mpv has the variants:
[+]audiocd: Enable Audio CD support via libcdio-paranoia
   bundle: Enable the optional macOS bundle of mpv
   caca: Enable animated ASCII art video output
   debug: Compile with debugging symbols
[+]dvd: Enable DVD and DeCSS support
   jack: Enable Jack Audio Connection Kit support
[+]libarchive: Enable transparent handling of Zip files and other compressed
               formats
   libmpv: Enable the libmpv library
[+]network: Enable networking support via youtube-dl (supports wide variety of
            pages)
   openal: Enable OpenAL support
[+]opengl: Enable OpenGL output support. Both the CoreVideo and X11 (GLX)
           outputs are supported
[+]osd: Enable onscreen display and TrueType font support
   printable_doc: Generate printable documents (PDF help)
   pulseaudio: Enable PulseAudio support
   python27: Use python27 to generate man pages
     * conflicts with python38
   python37: Legacy variant for python37 mapping to python38
     * conflicts with python27
     * requires python38
[+]python38: Use python38 to generate man pages
     * conflicts with python27
[+]rubberband: Enable support for the Rubber Band library, adding audio pitch
               and speed control
   screenshot: Enable optional screenshot support
   smb: Enable Samba support
   uchardet: Enable the uchardet encoding detector
[+]x11: Enable X11 support
```

**Comment by kencu** [comment]
well I guess in this case, with each variant being 0 or 1, it would be 2^22 combos, rather than 22! It's a while since I did by combinatorics courses.

**Comment by i0ntempest** [comment]
Well imo it's still easier to have variants than have to edit portfile for every install. It already has a dvd variant so I thought adding a bluray variant makes sense...

**Comment by kencu** [comment]
> Well imo it's still easier to have variants than have to edit portfile for every install. 

Well naturally. Nobody here is suggesting editing the Portfile for every install -- that would be ridiculous, as I think you know. 

The idea is to put everything that a reasonable user might want into a default build of the port, instead of having 22 variants with nobody that knows what they do, certainly not a user who wants to play a video.

But mpv is a lost cause for this anyway. Good luck!

**Pull request merged**
