### PR TITLE
py-typing: update to 3.7.4

### PR DESCRIPTION
**Pull request by aque**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.5 18F132
Xcode 10.2.1 10E1001 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
looks good to me. I know you didn't change that in this PR, but is the workaround for the livecheck still needed? To me it doesn't look like it and in that case you could perhaps remove it?

**Comment by reneeotten** [comment]
as a heads up (@kurthindenburg) this update will break ```py-hypothesis``` as I just experienced myself... It has been fixed upstream though in version 4.24.4 of ```py-hypothesis```:

```
This patch fixes :issue:`2014`, where our compatibility layer broke with version
3.7.4 of the :pypi:`typing` module backport on PyPI.
```

**Comment by aque** [comment]
Thanks @reneeotten. It does not look like I need the workaround anymore. I updated the port and removed it.

So what is the process to avoid `py-hypothesis` breakage? Should we delay this merge?

**Comment by reneeotten** [comment]
my preferred option would be to add the update of ```py-hypothesis``` to this PR, which will notify its maintainer anyways. From a quick glance through the release notes of ```hypothesis``` it seems to me that nothing major has changed compared to the version that is present now in MacPorts (v4.23.5), so I don't foresee issues.

**Comment by reneeotten** [comment]
ping @kurthindenburg: are you okay with this? If no response, I will merge this under ```openmaintainer``` at the end of the day.

**Comment by reneeotten** [comment]
thanks for the updates @aque !

**Pull request merged**
