### PR TITLE
p5-*: add p5.32, remove p5.26 subports

### PR DESCRIPTION
**Pull request by mojca**
#### Description

This update sometimes causes various issues related to our CI, so we want to monitor our services once we push the merge button.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

/

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
    - See #10711
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ctreleaven** [comment]
The build failure on mythweb.28 is expected.  Depends on non-default variants.

At some point, I will go over the myth* ports and update to a supported perl version (or declare some of the ports obsolete) among other maintenance.

**Comment by reneeotten** [comment]
@mojca what do you want to do with this PR? Fix the conflicts and merge, or...? It seems that leaving this open for too long isn't very helpful as it will inevitably result in merge conflicts as soon as one of the packages is updated.

**Comment by mojca** [comment]
I plan to (fix and) merge this. The problem is that there are some open / pending issues with efficiency on the buildbot side, usually resulting in the buildbot stuck building these ports for up to one week (truth to be told I'm not following exactly). From what I remember merging this has always caused one issue or another.

But if there's no activity towards optimisations foreseen in the near future, maybe I'll just merge ...

@ryandesign

**Comment by jmroot** [comment]
A lot of the portfiles seem to have `5.325.32` (sic) in `perl5.branches` now.

**Comment by mojca** [comment]
Arghhhhh. Thanks for pointing this out.
I've been using the same regex for years and it worked well ... until someone decided to only add subports to a handful of ports. I did go through the first round a bit more carefully, but I didn't pay so much attention this time.

I'm fixing it now.

**Comment by ryandesign** [comment]
Thanks. Since the problem affected p5.32-module-build, a lot of p5.32 ports failed to build. We should force build all affected p5.32 ports on those builders that have already processed the initial commits from this PR (10.7, 10.8, 10.14, 10.15, 11 x86_64, 11 arm64). Ideally we should list the p5.32 subports and not the p5 main ports to avoid unnecessary extra processing by the buildbot.

**Comment by mojca** [comment]
I started new forced builds on 10.7, 10.8 and 11 arm64. These are the ones that have completely finished building the ports from that commit. I'll wait for the other workers to finish the job and then extract the summary and reschedule just the failed subports for 5.32. I guess I should add subports for 5.34 as well and then we could try to migrate directly to 5.34.

https://trac.macports.org/ticket/63126

**Pull request merged**
