### PR TITLE
xapian-omega: requires pcre2

### PR DESCRIPTION
**Pull request by chrstphrchvz**
…rather than pcre, as of release 1.4.20
https://trac.xapian.org/wiki/ReleaseOverview/1.4.20

#### Description

Builds of 1.4.20 update failed during configure:

```
checking for pcre2-config... no
configure: error: Can't find pcre2-config.  If the PCRE2 library is installed, you need to add PCRE2_CONFIG=/path/to/pcre2-config to your configure command.
```

###### 

###### Tested on

~~Untested~~ Activated successfully on macOS 10.15 and macOS 11 CI builders; Destroot completed successfully on macOS 12 CI builder.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
macOS 12 CI build for xapian-omega was interrupted during activation—it at least configured/built/destrooted successfully.

**Comment by chrstphrchvz** [comment]
@mascguy I believe this is ready to merge under maintainer timeout

**Comment by mascguy** [comment]
> @mascguy I believe this is ready to merge under maintainer timeout

Restarted the failed CI jobs, let's see if they succeed this time.

**Comment by chrstphrchvz** [comment]
During latest CI attempt, xapian-omega activated successfully on macOS 10.15 and 11; only got as far xapian-bindings-ruby25 on macOS 12 (did not get to xapian-omega).

**Review by mascguy — APPROVED** [review]
Typically I prefer to test locally, when some CI jobs fail. But it's simply not practical to install all of these subports, so let's merge. I'll monitor the buildbots, to ensure there aren't any legitimate issues for Big Sur and Monterey.

Thanks as always Chris!

**Comment by ryandesign** [comment]
Thanks! Sorry I missed this PR until now.

**Pull request merged**
