### PR TITLE
qpdf: update to 7.1.0

### PR DESCRIPTION
**Pull request by amake**
#### Description

Update qpdf to 7.1.0.

Previously a workaround for build issue was present, but the issue appears to have been solved:
https://trac.macports.org/ticket/55675
https://github.com/qpdf/qpdf/issues/158

I was able to upgrade successfully from both 6.0.0 and 7.0.0.

###### Tested on
macOS 10.13.3 17D47
Xcode 9.2 9C40b

### CODE REVIEW

**Comment by pmetzger** [comment]
Any idea why Travis failed?

**Comment by amake** [comment]
No, I couldn't figure it out. Is it possible to re-run the build?

**Comment by pmetzger** [comment]
If you do any push to the branch (including an empty one with a force) it will rebuild.

**Comment by amake** [comment]
This appears to be a Travis issue? I'm not familiar with the build system (nor do I have access?) so it's hard to diagnose further.
https://github.com/travis-ci/travis-ci/issues/8703
https://github.com/direnv/direnv/issues/210

**Pull request merged**
