### PR TITLE
tiledb: update to 2.24.2

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@teo-tsirpanis Looks like this is `clang-18`-related issue. Using an earlier one works.

**Review by reneeotten — CHANGES_REQUESTED** [review]
can you please update to the latest upstream version and see if that makes the patches/blacklisting redundant?

**Comment by barracuda156** [comment]
@reneeotten Still fails on macOS 13.

**Comment by reneeotten** [comment]
> @reneeotten Still fails on macOS 13 (if I drop extra blacklist).

okay, well then you probably should put it back as we'll not merge PRs that don't pass the CI

**Comment by barracuda156** [comment]
> > @reneeotten Still fails on macOS 13 (if I drop extra blacklist).
> 
> okay, well then you probably should put it back as we'll not merge PRs that don't pass the CI

Done

**Pull request merged**
