### PR TITLE
dectalk: multiple fixes to the port

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Backport some upstream fixes.
Enable normal patching.
Fix building with gcc.
Fix build on Darwin < 16.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mohd-akram** [comment]
Builds are failing, converted to draft.

**Comment by barracuda156** [comment]
@mohd-akram I will rebase today, dropping my patches in favor of new backports from upstream, and we can see from there.

**Comment by reneeotten** [comment]
ping

**Comment by barracuda156** [comment]
@mohd-akram Whenever you update the port, please add `legacysupport` and blacklist old Xcode gcc, otherwise it won’t build on legacy systems.
I close this.

**Pull request closed without merging**
