### PR TITLE
dbh: update to 5.0.22

### PR DESCRIPTION
**Pull request by herbygillot**
Running into issues with this one:

```
  CC       dbh.lo
In file included from dbh.c:135:
./dbh_static.i:1978:13: error: implicit declaration of function 'sem_timedwait' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        if (sem_timedwait(dbh->sem, &timeout) < 0){
            ^
./dbh_static.i:1978:13: note: did you mean 'sem_trywait'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/semaphore.h:58:5: note: 'sem_trywait' declared here
int sem_trywait(sem_t *);
    ^
In file included from dbh.c:135:
./dbh_static.i:2001:13: error: implicit declaration of function 'sem_timedwait' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        if (sem_timedwait(dbh->sem, &timeout) < 0){
            ^
In file included from dbh.c:143:
./dbh_exported.i:182:21: error: implicit declaration of function 'sem_timedwait' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                if (sem_timedwait(dbh->sem, &timeout) < 0){
                    ^
./dbh_exported.i:945:13: error: implicit declaration of function 'sem_timedwait' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        if (sem_timedwait(dbh->sem, &timeout) < 0){
            ^
4 errors generated.
```

###### Tested on

macOS 10.15.7 19H114
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -d install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
it appears that ```sem_timedwait``` doesn't exist on darwin.

See <https://stackoverflow.com/questions/641126/posix-semaphores-on-mac-os-x-sem-timedwait-alternative/48778462> for some ideas.

**Review by kencu — CHANGES_REQUESTED** [review]
sem_timedwait does not exist on darwin.

either need a fallback, don't update, or other workaround.

**Comment by herbygillot** [comment]
Well nevermind in that case.  Closing.

**Comment by kencu** [comment]
yeah, that would have been a bit of a project to fix.

**Pull request closed without merging**
