### PR TITLE
curl: Drop patchfile merged upstream

### PR DESCRIPTION
**Pull request by neverpanic**
#### Description

Port currently fails to build because the patch to lib/vtls/openssl.c fails as already applied. I'm assuming this is because upstream adopted the change, and am thus removing it.

No revbump is required, because this did not build at all.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.6 18G6020
Xcode 11.3.1 11C505
Building against OpenSSL.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by neverpanic** [comment]
curl isn't openmaintainer, so let's wait for @ryandesign to react.

**Comment by herbygillot** [comment]
Confirmed that it looks like this patch is already applied upstream.

**Comment by kencu** [comment]
trivial fix to a broken port with many deps....

**Comment by eborisch** [comment]
I would suggest merging this without waiting -- it's broken as is, and curl is depended upon by almost 200 ports.

I have (also) confirmed that the [patch is upstream in 7.72](https://github.com/curl/curl/commit/c71d8bb56d43405d7fa1f6d9cf4af2c3cdf4cdf1).

**Comment by eborisch** [comment]
Pushed the green button. There are other builds that are failing tests waiting for this trivial fix. Hope @ryandesign is OK with it.

**Comment by herbygillot** [comment]
Does it make sense to have a secondary core maintainer alongside @ryandesign for the set of these core-level ports?

**Comment by kencu** [comment]
Due to Ryan's dedication, it has never been needed up to now.

**Comment by ryandesign** [comment]
Sorry for the trouble. I had tested the build on an outdated copy of the port that didn't contain Jeremy's patch. Thank you for fixing it.

If something like this is obviously wrong in my ports please do fix it.

curl is not listed as openmaintainer because it's a critical port that lots of other ports depend on so I'd rather have a chance to approve proposed changes before they're merged -- obvious mistakes like this one excepted of course.

**Pull request merged**
