### PR TITLE
Rev-bumps for hdf5 ABI change

### PR DESCRIPTION
**Pull request by eborisch**
Fix ABI change issues with latest (1.14.4.2) HDF update.

### CODE REVIEW

**Review by mascguy — APPROVED** [review]
LGTM. Other folks?

**Review by Dave-Allured — CHANGES_REQUESTED** [review]
`lscsoft-deps` and `ncpp` are not library dependencies.  If you agree, please remove them.  All other bumps seem fine to me.

**Review by nilason — APPROVED** [review]

**Review by barracuda156 — APPROVED** [review]
Assuming CI pass, all good for my ports.

**Comment by Schamschula** [comment]
My ports should cleanly rebuild with the revision bump

**Comment by barracuda156** [comment]
@eborisch `netcdf-cxx4` was forgotten.

**Comment by Dave-Allured** [comment]
> `netcdf-cxx4` was forgotten.

`netcdf-cxx4` does not list a dependency on HDF5.  My understanding is that HDF5 should only be an indirect dependency through the main `netcdf` port.

If you have a specific error message or source code reference, please show it.  Thanks.

**Comment by barracuda156** [comment]
@Dave-Allured Well, apparently dependencies specs are incomplete then:
```
36-242% port contents netcdf-cxx4
Port netcdf-cxx4 @4.3.1_0 contains:
  /opt/local/bin/ncxx4-config
  /opt/local/include/ncAtt.h
  /opt/local/include/ncByte.h
  /opt/local/include/ncChar.h
  /opt/local/include/ncCheck.h
  /opt/local/include/ncCompoundType.h
  /opt/local/include/ncDim.h
  /opt/local/include/ncDouble.h
  /opt/local/include/ncEnumType.h
  /opt/local/include/ncException.h
  /opt/local/include/ncFile.h
  /opt/local/include/ncFloat.h
  /opt/local/include/ncGroup.h
  /opt/local/include/ncGroupAtt.h
  /opt/local/include/ncInt.h
  /opt/local/include/ncInt64.h
  /opt/local/include/ncOpaqueType.h
  /opt/local/include/ncShort.h
  /opt/local/include/ncString.h
  /opt/local/include/ncType.h
  /opt/local/include/ncUbyte.h
  /opt/local/include/ncUint.h
  /opt/local/include/ncUint64.h
  /opt/local/include/ncUshort.h
  /opt/local/include/ncVar.h
  /opt/local/include/ncVarAtt.h
  /opt/local/include/ncVlenType.h
  /opt/local/include/netcdf
  /opt/local/lib/libh5bzip2.la
  /opt/local/lib/libh5bzip2.so
  /opt/local/lib/libnetcdf_c++4.1.dylib
  /opt/local/lib/libnetcdf_c++4.a
  /opt/local/lib/libnetcdf_c++4.dylib
  /opt/local/lib/libnetcdf_c++4.la
  /opt/local/lib/pkgconfig/netcdf-cxx4.pc
36-242% otool -L /opt/local/lib/libh5bzip2.so
/opt/local/lib/libh5bzip2.so:
	/opt/local/lib/libnetcdf.19.dylib (compatibility version 19.0.0, current version 19.0.0)
	/opt/local/lib/libhdf5.310.dylib (compatibility version 311.0.0, current version 311.0.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 117.0.0)
```
Needless to say, after update of `hdf5` it is broken, since it cannot find the dylib it is linked to.

**Comment by Dave-Allured** [comment]
@barracuda156 Okay, I see that.  I will look into `netcdf-cxx4`.  Right now I do not understand that port, but it needs to be checked.  Thanks for showing.

**Comment by Dave-Allured** [comment]
@barracuda156 I removed the `hdf5` dependency from `netcdf-cxx4` because it appeared to be overlinking.  Please see PR #23743.  Feedback welcome.

**Pull request merged**
