### PR TITLE
Update version to 3.8.0-b2, hashes and filesize.

### PR DESCRIPTION
**Pull request by Themanwithoutaplan**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.5 18F132
Xcode 10.2.1 10E1001

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
Yes, there are some test failures:
```
:info:test Ran 280 tests in 86.566s
:info:test FAILED (failures=1, errors=42, skipped=26)
:info:test 11 tests failed again:
:info:test     test_asyncio test_concurrent_futures test_grp
:info:test     test_multiprocessing_forkserver test_multiprocessing_main_handling
:info:test     test_multiprocessing_spawn test_popen test_readline test_socket
:info:test     test_socketserver test_subprocess
:info:test == Tests result: FAILURE then FAILURE ==
:info:test 392 tests OK.
:info:test 11 tests failed:
:info:test     test_asyncio test_concurrent_futures test_grp
:info:test     test_multiprocessing_forkserver test_multiprocessing_main_handling
:info:test     test_multiprocessing_spawn test_popen test_readline test_socket
:info:test     test_socketserver test_subprocess
:info:test 20 tests skipped:
:info:test     test_devpoll test_epoll test_gdb test_idle test_msilib
:info:test     test_multiprocessing_fork test_ossaudiodev test_poll test_spwd
:info:test     test_startfile test_tcl test_tix test_tk test_ttk_guionly
:info:test     test_ttk_textonly test_turtle test_winconsoleio test_winreg
:info:test     test_winsound test_zipfile64
:info:test 11 re-run tests:
:info:test     test_asyncio test_concurrent_futures test_grp
:info:test     test_multiprocessing_forkserver test_multiprocessing_main_handling
:info:test     test_multiprocessing_spawn test_popen test_readline test_socket
:info:test     test_socketserver test_subprocess
```
But a lot of these releate to path names. There are no changes other than to the metadata
- [x ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by yan12125** [comment]
Thanks for the update! Could you change the commit message and make it start with `python38-devel:`?

**Comment by Themanwithoutaplan** [comment]
> Thanks for the update! Could you change the commit message and make it start with `python38-devel:`?

I don't how to edit commit messages but I'll try. Otherwise I'll just create a new branch.

**Comment by yan12125** [comment]
Thanks for the update! I use GitHub's squash feature to remove commits not starting with `python38-devel: `. If you're interested in how to do that using the command line, `man git-rebase` should be worth a read.

**Comment by Themanwithoutaplan** [comment]
> Thanks for the update! I use GitHub's squash feature to remove commits not starting with `python38-devel: `. If you're interested in how to do that using the command line, `man git-rebase` should be worth a read.
I don't really use git (insert tool here) enough to be able to remember any details. I'll just try and improve in future PRs.
There will soon be a new release of Python 3.7. What's the procedure for testing release candidates?

**Comment by yan12125** [comment]
> I don't really use git (insert tool here) enough to be able to remember any details. I'll just try and improve in future PRs.

No problem!

> There will soon be a new release of Python 3.7. What's the procedure for testing release candidates?

I guess you mean 3.8? Release candidates still go to python38-devel. When the final release is out, a new port python38 will be created and python38-devel will be declared as obsoleted.

**Comment by Themanwithoutaplan** [comment]
> > I don't really use git (insert tool here) enough to be able to remember any details. I'll just try and improve in future PRs.
> 
> No problem!
> 
> > There will soon be a new release of Python 3.7. What's the procedure for testing release candidates?
> 
> I guess you mean 3.8? Release candidates still go to python38-devel. When the final release is out, a new port python38 will be created and python38-devel will be declared as obsoleted.

No, 3.7 https://www.python.org/downloads/release/python-374rc2/

**Comment by yan12125** [comment]
Oops!

Well, usually release candidates for patch releases are not pushed to this repository.

**Pull request merged**
