### PR TITLE
free42: update to 2.0.22

### PR DESCRIPTION
**Pull request by lbschenkel**
I'm the maintainer. I'm experiencing a strange issue when trying to build locally and I want to test in Travis.

### CODE REVIEW

**Comment by cjones051073** [comment]
@lbschenkel Do you intend to eventually have this merged, or is it just for testing ?

**Comment by kencu** [comment]
MacOSX 10.7 is Xcode 4.6 .  And If it builds on 10.7, there is a pretty good chance it builds on everything. Want me to take a look at this?

**Comment by lbschenkel** [comment]
Yes, I intend to merge but I'm abroad on vacation. After I return home next week I should be able to spend time on this again. I'll probably need some help, though.

In the meantime, if somebody has any clue, what I'm trying to address is the build on Xcode 10 (https://paste.macports.org/9a2bf9dc4f92). I don't know much about Xcode, but something changed on 10 that broke the build. I can see that some other ports had to implement workarounds to similar issues (https://github.com/macports/macports-ports/search?q=deriveddata) but they didn't work for me locally. I don't really use Xcode I don't fully understand what this workaround is doing nor why it is necessary.

**Comment by cjones051073** [comment]
Xcode 10 was released with a new build system enabled by default. There are plenty resources on the web explaining the differences, e.g.

https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes/build_system_release_notes_for_xcode_10

some projects might not build with the new system, and need time to adapt. Thats where the flag to revert back comes in.

**Comment by lbschenkel** [comment]
I have fixed Xcode 10 by doing the following:
```
# fix build with Xcode 10
if {${os.platform} eq "darwin" && ([vercmp $xcodeversion 10.0] > 0)} {
       build.pre_args      -UseNewBuildSystem=NO
       destroot.pre_args   ${build.pre_args}
}
```
Patching `MainMenu.xib` was not necessary. Failing on 7.3 is expected since this project requires Xcode 8. I'll give 24 hours for somebody to leave any additional comments before I merge.

**Comment by kencu** [comment]
Without the xib patch, Mojave fails with an error saying deployment targets older than 10.6 are not supported.

**Comment by kencu** [comment]
Besides, it doen't run on 10.5 anyway, even with libc++ installed due to some error I didn't look into.

**Comment by lbschenkel** [comment]
@kencu: Strange, I just built/installed now in a Mojave system without patching `MainMenu.xib` and it built and run without any errors.

**Comment by kencu** [comment]
Ok. See what happens.

**Pull request merged**
