### PR TITLE
livecheck fixes

### PR DESCRIPTION
**Pull request by l2dy**
This PR is used to detect merge conflicts and should be merged before any massive refactoring.

### CODE REVIEW

**Comment by mkae** [comment]
Why is this unstable?

Perhaps it would also be better to squash all of that into one commit, as changes are made only for the livecheck in all ports.

**Comment by l2dy** [comment]
@mkae Because I'd sometimes push unfinished commits.

`capstone: move to github, fix livecheck` is not livecheck only. Should I move it to a seperate PR?

> [16:57:39] <l2dy> I'm trying to fix livecheck of many ports. Should I squash the commits? What should the commit message be?
> [17:02:36] <neverpanic> I'd leave them as separate commits but put them in a single PR

**Comment by mkae** [comment]
Yes, absolutely, move capstone out then.

And, there is the lore that WIP shouldn't be submitted as a PR...

**Comment by l2dy** [comment]
@mkae I said this PR is only used to detect and avoid merge conflicts.

**Comment by l2dy** [comment]
@mkae If there is that much hate around WIP I can start working on a different branch `lv-fix2` and this won't be WIP anymore.

**Comment by mkae** [comment]
It's fine for now, but yes, a seperate branch would be the way to go.

Wouldn't say hate, but preferral, though.

Having said all that, it's great to see what you have achieved so far... You are updating ports at an incredible rate. Thumbs up from me and keep going! :-)

**Comment by l2dy** [comment]
I'm having trouble with ports hosted on Google Code. Since Google Code is archived I'm suggesting that we disable livecheck for googlecode ports.

Ticket: https://trac.macports.org/ticket/53457

**Comment by mojca** [comment]
Tiny suggestion. Since you are manually going through each and every port anyway, could you perhaps add a tiny bit of more meta information about why you make the changes you make (in cases where it's not obvious).

As a random example of hping3. The site says:
> Hping is no longer actively developed, however from time to time, changes are submitted by users and are integrated into the main source tree. The development HQ is the [Hping Github repository](https://github.com/antirez/hping), please grab sources from Github.

It could be helpful to see an additional note saying that the software is no longer being actively developed. (In this particular case it could be worth mentioning GitHub as well and at some point in future looking at using the GitHub PortGroup - but that's beyond the scope of this PR anyway.)

I'm not asking you to review all the past commits, but if there's something worth mentioning as you proceed to other ports, I feel it would be a pity to "forget the results of you research".

**Comment by l2dy** [comment]
@mkae @mojca I'll switch to a new branch, please review this PR.

**Comment by l2dy** [comment]
@mkae @mojca @tobypeterson I'll switch to a new branch, please review this PR.

**Comment by mkae** [comment]
@l2dy, I am not able to test all these fixes ATM, but hopefully @mojca or @tobypeterson will.

**Comment by tobypeterson** [comment]
IMO, @l2dy needs write access to the repo...

**Comment by l2dy** [comment]
@tobypeterson Even if I get write access, big changeset still needs to be peer reviewed.

**Comment by l2dy** [comment]
What is b1baec64ae doing?

**Comment by mkae** [comment]
You should ping the maintainers of all those projects which have one, @l2dy.

**Comment by l2dy** [comment]
@mkae I don't have a batch email to GitHub handle API. 😵

**Comment by mkae** [comment]
One could write a little script which determines all maintainers and sends an email to them pointing to this PR... Shouldn't be too complicated.

But well, this is only livecheck, so, I think we shouldn't make so much fuss about it and simply commit your two PRs, if you took Mojca's hints into account and added a little more info to those commit messages where needed.

What do you think, @mojca?

**Comment by mojca** [comment]
I don't think we really need maintainers' approvals to commit this. We just need a second pair of eyes to go through the list of changes and confirm that `port -v livecheck <list>` is fixed.

(If someone is willing to drop a note to `port info --maintainer <list> | <some regexp to clean up the list>` just to let the few remaining maintainer know about the change, that's OK/polite. But optional.)

**Comment by eborisch** [comment]
There are no changes that impact the actual builds here; just some nice work to make the helper functions work better. lgtm

**Comment by l2dy** [comment]
Since these commits won't make anything worse, can we merge them now? My second round of `port livecheck all` is blocked on the two PRs.

**Comment by tobypeterson** [comment]
Yeah, gonna do it

**Comment by mkae** [comment]
Hi, @l2dy, I've just pulled in this PR, made my git repo overlaying the standard source, ran
```
git log --oneline -70 | sed 's/^.* \(.*\): .*$/\1/' | xargs -I {} port livecheck {}
```
and thus found only these two errors:
```
Error: livecheck failed for http_ping: extracted version '09Mar2016' is older than livecheck.version '29jun2005'
Error: livecheck failed for haskell-platform: extracted version '8.0.2' is older than livecheck.version '2014.2.0.0'
```
which are surely only due to the weird versioning schemes used or changed. 

Only 37 of those 70 ports have a functioning livecheck, but I guess this is much more compared to before this commit.

So, all in all this looks fine to me.

**Pull request merged**
