### PR TITLE
Update pymol to 2.2.0 release

### PR DESCRIPTION
**Pull request by jwhowarth**
#### Description

The attached changes

1) Update both pymol and its py-pmw dependency to support the py37 variant
2) Switches pymol from svn to git as upstream has switched from svn to git
3) Updates pymol to the 2.2.0 release
4) Adds the new glm dependency required for pymol at the 2.2.0 release.
5) Removes the portion of the setup.py.diff patch present now upstream

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.6 17G65
Xcode 10.0 10L213o 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-poxrts/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by yan12125** [comment]
Did you check #2293?

**Comment by jwhowarth** [comment]
From [https://src.fedoraproject.org/rpms/pymol/blob/master/f/pymol.spec](url) it appears that we do need py-num but the py-scipy dependency can be dropped.

**Comment by jwhowarth** [comment]
Update pull request with merge of changes from #2293

**Comment by pmetzger** [comment]
@reneeotten Are the two pull requests now harmonized?

**Comment by jwhowarth** [comment]
FYI, if I recall correctly, the testers often fail because the pymol Portfile has...

require_active_variants tcl "" corefoundation
require_active_variants tk "" quartz

which tends to hang the process as the auto build scripts aren't bright enough to reinstall the correct variants for tk and tcl.

**Comment by reneeotten** [comment]
@pmetzger @jwhowarth yes, looks good! Perhaps remove the last empty line (line 106) and get rid of the spaces on line 26 in the Portfile, but besides that I think it's all good. 

The first commit message should probably become, "py-pmw: add py37 subport"; the other ones can be squashed and the commit messages combined.

**Comment by pmetzger** [comment]
@jwhowarth as soon as you've done those last couple of things we can merge. Perhaps you would also like to add @reneeotten as a co-maintainer?

**Comment by reneeotten** [comment]
I closed my initial PR. As I commented in that one, there are a few old Trac tickets open regarding pymol. I think many of them are not very relevant anymore, so perhaps someone with appropriate permissions could take a look and decide what to do with them?

**Comment by pmetzger** [comment]
@reneeotten I wouldn't know what to do with them, but if you check them out ask me to close a given ticket or tickets, I'm happy to do so.

**Comment by jwhowarth** [comment]
Requested Portfile cleanups added to pull request.

**Comment by pmetzger** [comment]
Merged! Thanks, @jwhowarth and @reneeotten! If there are further fixes, we can do them in an additional PR.

**Comment by pmetzger** [comment]
Argh! Damn, I didn't notice the commits weren't squashed. My bad. They should have been squashed before I did the merge, now it is too late. In the future, though, we have to squash all the commits before merging.

**Comment by reneeotten** [comment]
yes... and the commit messages should have followed the guidelines as I suggested - well, next time.

**Comment by pmetzger** [comment]
It's my fault. That said, perhaps @reneeotten should be added as co-maintainer on the port in a subsequent pull request?

**Pull request merged**
