### PR TITLE
WIP python{27-37}: Add Darwin 18+ workaround

### PR DESCRIPTION
**Pull request by cjones051073**
Closes: https://trac.macports.org/ticket/58882

### CODE REVIEW

**Comment by jmroot** [comment]
I'd really rather not apply a kludgy workaround catering to a prerelease OS when nobody has bothered to investigate why the problem happens or even provide a crash report.

**Comment by cjones051073** [comment]
> I'd really rather not apply a kludgy workaround catering to a prerelease OS when nobody has bothered to investigate why the problem happens or even provide a crash report.

The compilation failure is in the referenced ticket above. I am not sure what more discussion you want to have in an open forum, given the NDA. 

What is wrong with putting workarounds in if it helps people right now testing the beta OS ? Python is a common dependency so anyone wanting to test the OS, to make things better for users when the final OS release comes around, will trip over this very quickly and it prevents them being able to test any other ports. This is not good and putting this out will help. The issue is either an upstream issue python devs are going to have to fix, or an issue with the OS that Apple will finally fix come release, and we will not know this until that happens. Until then, the fix/workaround/call it what you want here helps people right now.

**Comment by jmroot** [comment]
> The compilation failure is in the referenced ticket above. I am not sure what more discussion you want to have in an open forum, given the NDA.

Either the NDA applies and a public report should not have been made in the first place, or it doesn't and the reporter can dig a bit deeper.

> What is wrong with putting workarounds in if it helps people right now testing the beta OS ? Python is a common dependency so anyone wanting to test the OS, to make things better for users when the final OS release comes around, will trip over this very quickly and it prevents them being able to test any other ports. This is not good and putting this out will help. The issue is either an upstream issue python devs are going to have to fix, or an issue with the OS that Apple will finally fix come release, and we will not know this until that happens. Until then, the fix/workaround/call it what you want here helps people right now.

It doesn't really help in the long run, it just hides the problem and has unexplored side effects. If you're going to use a prerelease OS, you need to be prepared to work on fixing the problems you find.

**Comment by cjones051073** [comment]
> > The compilation failure is in the referenced ticket above. I am not sure what more discussion you want to have in an open forum, given the NDA.
> 
> Either the NDA applies and a public report should not have been made in the first place, or it doesn't and the reporter can dig a bit deeper.

OK fine, whatever. I am not a laywer, nor have any real interest in this stuff so going to leave this here.
 
> 
> > What is wrong with putting workarounds in if it helps people right now testing the beta OS ? Python is a common dependency so anyone wanting to test the OS, to make things better for users when the final OS release comes around, will trip over this very quickly and it prevents them being able to test any other ports. This is not good and putting this out will help. The issue is either an upstream issue python devs are going to have to fix, or an issue with the OS that Apple will finally fix come release, and we will not know this until that happens. Until then, the fix/workaround/call it what you want here helps people right now.
> 
> It doesn't really help in the long run, it just hides the problem and has unexplored side effects. If you're going to use a prerelease OS, you need to be prepared to work on fixing the problems you find.

I *am* prepared to work on fixes. That is exactly what I am doing. I've looked into it as much as I can and I cannot conclude if it is an issue with python, or the OS. Either way there is not much more investigating I can/want to do, and this lets me move on to other ports I have more involvement with. I hoped it was clear from the comments I added this wasn't a long term fix but a temporary workaround for right now. If you don't want to merge it, fine, that is your choice, but I am going to leave this PR open so others can find it if then need the work arounds.

**Comment by eirnym** [comment]
You can just make it dependent on Xcode, not command line tools, that's fixes the problem better. I've reported the same on a change with MacPorts base.

**Comment by eirnym** [comment]
As I compile now, this workaround should be applied to more than few ports (Catalina Public Beta 7 & Xcode 11 Beta 7)

**Comment by cjones051073** [comment]
closing as workarounds no longer seem necessary for latest macOS beta and Xcode 11 GM 1

**Pull request closed without merging**
