### PR TITLE
binutils: update to 2.28

### PR DESCRIPTION
**Pull request by l2dy**
###### Tested on
macOS 10.12.3
Xcode 8.2.1

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mojca** [comment]
You can also check other cross tools: https://trac.macports.org/ticket/51935

**Comment by l2dy** [comment]
I'm not able to test all these ports (too many of them). Feel free to take over.

**Comment by mojca** [comment]
It was more of a "while you are at it anyway" kind of thing and is not really a prerequisite to merge this anyway. In any case I don't think that anyone actually uses (or needs) the `binutils` port, I probably even saw warnings that suggest you not to have it installed. The cross tools are the ones where binutils is really useful.

There are a number of ports that need more work (basically all of those that are not at version 2.27 yet) and those have separate tickets. Some of @g5pw's ports, mipsel, the semi-obsolete MinGW32 and `rtems` which is a separate story altogether with a lot more work needed. No need to look at any of those.

But the rest most likely only needs a fix of version number and checksums. I didn't check functionality of any other binutils cross port, I just verified that they built and there were no complaints.

**Comment by l2dy** [comment]
@mojca Updated but didn't verify anything.

**Comment by g5pw** [comment]
Yeah, the msp430 suite is on my backlog for quite a while, sorry. `msp430-*` ports will be substituted by `msp430-elf-*`, which is the officially supported compiler nowadays.

**Comment by mojca** [comment]
I added the two of my ports and left a note to maintainers at Trac. I guess you can wait 72 hours in case some maintainer complains (highly unlikely) and then push this to master.

**Comment by l2dy** [comment]
https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/23358/steps/install-port/logs/stdio

```
*** Configuration arm-unknown-aout is obsolete.
*** Specify --enable-obsolete to build it anyway.
*** Support will be REMOVED in the next major release of BINUTILS,
*** unless a maintainer comes forward.
```

**Pull request merged**
