### PR TITLE
py-platformdirs: update to 2.2.0

### PR DESCRIPTION
**Pull request by harens**
#### Description

- Pin py27/35 to 2.0.2
    - Version 2.1.0 dropped support for py27/35. See the [changelog](https://github.com/platformdirs/platformdirs/blob/main/CHANGES.rst#platformdirs-210) for this release.

- Remove py34 subport
    - I don't think stable platformdirs ever supported py34 (although the original appdirs did). It was removed in the very first alpha https://github.com/platformdirs/platformdirs/commit/b963e64cba68c371248257f1fcfd9345d3c2fb26.
    - Following from https://github.com/macports/macports-ports/commit/055eabbd48a8cde0190851f222e79300da949873, it's no longer a dependency of py-virtualenv.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.1 20C69 x86_64
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by reneeotten — CHANGES_REQUESTED** [review]
thanks @harens - I see that I messed up a bit here... 


> * pin py27/35 to 2.0.2 ; version 2.1.0 dropped support for py27/35. 

That appears indeed the case from upstream's description, although version 2.1.0 builds fine on the earlier Python versions. But you're correct that we should pin these to version 2.0.2 to follow upstream's plan for this. However, since version 2.1.0 was already successfully build for PY27/PY35 you do need to add an `epoch` to make sure that the earlier version is considered "newer".

> * Remove py34 subport

Right, I indeed restricted the PY34 subport for `py-virtualenv` to an earlier version that does not use the `py-platformdirs` but still `py-appdirs`. So yes, I agree with the removal of this subport here. 

If you add the `epoch` as suggested above I am fine with these changes, so feel free to merge yourself.

**Comment by harens** [comment]
> However, since version 2.1.0 was already successfully build for PY27/PY35 you do need to add an epoch to make sure that the earlier version is considered "newer".

I think that's already present @reneeotten in line 34. Is that correct?

**Comment by reneeotten** [comment]
> I think that's already present @reneeotten in line 34. Is that correct?

You're totally correct - I didn't have enough coffee yet ;)

**Comment by harens** [comment]
Thanks for reviewing @reneeotten. Greatly appreciated. 👍

**Pull request merged**
