### PR TITLE
gdal: Update to 3.9.1

### PR DESCRIPTION
**Pull request by Dave-Allured**
#### Description

* Update GDAL 3.9.0 --> 3.9.1
* Includes numerous upstream bug fixes, including compile fixes.
* Includes fixes for the new plugin capability introduced in 3.9.0.
* See release announcement and release notes:
* https://lists.osgeo.org/pipermail/gdal-announce/2024-June/000119.html
* Also do not opportunistically link to armadillo. See PR #24687.
* Also switch to path-style dependency for pkgconfig.

###### Tested on

CI only.  OS 12, 13, 14 only.
Maintainer also tested the RC2.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by nilason — APPROVED** [review]

**Comment by Dave-Allured** [comment]
Closing this PR because I mangled the merge with other PR's.  See new update PR #24695.

**Comment by Dave-Allured** [comment]
The merged PR #24695 did not work out.  Re-opening this independent update request.  Maintainers feel free to copy any part of this PR.

**Comment by barracuda156** [comment]
@Dave-Allured Could you please add an armadillo fix here? It requires rebuild, so it is better to do it at once.

**Comment by reneeotten** [comment]
@Dave-Allured there should be no merge-commit present. You'll have to rebase instead to get a clean history.

**Comment by Dave-Allured** [comment]
@reneeotten Okay.  I am running on github only, without the help of git command line.  This is not good.  I will try to sync this branch on github, and see if that is satisfactory.  If not I will need to resort to a new PR.

**Comment by Dave-Allured** [comment]
Moved to #24707 for clean commits.

**Pull request closed without merging**
