### PR TITLE
evolution-data-server: update to 3.52.1, allow builds without webkit2

### PR DESCRIPTION
**Pull request by barracuda156**
@mascguy I am making this a draft, please review :) 
It builds fine with no hacks like this, but I am not sure about some conditionals. (Probably we rather use OS version, not C++ runtime, since it is rather likely that everything can be built against `libstdc++`, just not on 10.5 or at least not yet.)

Closes: https://trac.macports.org/ticket/69798

#### Description

Update, allow building on systems where webkit2 is broken.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Ah, well, it wants a much newer webkit2 than Macports has:
```
  -- Checking for module 'webkit2gtk-4.1>=2.34.0'
  --   No package 'webkit2gtk-4.1' found
  CMake Error at cmake/modules/PkgConfigEx.cmake:32 (message):
    Necessary libraries not found or not enough version.  If you want to
    disable WebKitGTK gtk3 for built-in OAuth2 authentications, please use
    -DENABLE_OAUTH2_WEBKITGTK=OFF argument to cmake command.
  Call Stack (most recent call first):
    CMakeLists.txt:427 (pkg_check_modules_for_option)
  
  
  -- Configuring incomplete, errors occurred!
```

@mascguy Should we fall back to the last version which work with an old WebKit2 or rather disable OAuth2 for the time-being, and have this version building?

**Comment by mascguy** [comment]
> Ah, well, it wants a much newer webkit2 than Macports has:
> 
> ```
>   -- Checking for module 'webkit2gtk-4.1>=2.34.0'
>   --   No package 'webkit2gtk-4.1' found
>   CMake Error at cmake/modules/PkgConfigEx.cmake:32 (message):
>     Necessary libraries not found or not enough version.  If you want to
>     disable WebKitGTK gtk3 for built-in OAuth2 authentications, please use
>     -DENABLE_OAUTH2_WEBKITGTK=OFF argument to cmake command.
>   Call Stack (most recent call first):
>     CMakeLists.txt:427 (pkg_check_modules_for_option)
>   
>   
>   -- Configuring incomplete, errors occurred!
> ```
> 
> @mascguy Should we fall back to the last version which work with an old WebKit2 or rather disable OAuth2 for the time-being, and have this version building?

Are you sure the various other dependencies are sufficient? Given how much newer this version is, you're likely to be blocked by other dependencies.

I'd like to suggest we avoid updating this port, if at all possible. Which port(s) depend on this for your system?

**Comment by mascguy** [comment]
Fixed via master, so this is no longer needed

**Comment by barracuda156** [comment]
@mascguy Ah, wait, it is not resolved yet, `google-online-accounts` still requires WebKit2, and it is an optional dependency, but the port makes it required even without a variant.

**Pull request closed without merging**
