### PR TITLE
vim: Update to 9.0.0852

### PR DESCRIPTION
**Pull request by sainnhe**
###### Type(s)

- [x] update
- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.0 22A380 arm64
Xcode 14.1 14B47b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by raimue — CHANGES_REQUESTED** [review]
Thank you for the update! But as indicated by the comment in the Portfile, the vim port should always follow the version used in the MacVim port.

Is there a particular bugfix that you need that is not included in the current version?

**Comment by sainnhe** [comment]
@raimue Yes, inlayHints in current version is buggy, I'm using coc.nvim .

**Comment by raimue** [comment]
I see... Would this be fixed with 9.0.0472? That would be the version used in the latest MacVim snapshot 174 which is also pending for an update.

**Comment by sainnhe** [comment]
Yes, patch 100 should be enough.

**Comment by reneeotten** [comment]
looks like this PR is superseded by #16711?

**Comment by raimue** [comment]
> looks like this PR is superseded by #16711?

Yes, indeed. Thanks for the hint.

@sainnhe Thank you again for submitting the port update! I hope your problem has been resolved by the vim update to 9.0.0472. If not, please let me know and we could backport another patch if needed.

**Pull request closed without merging**
