### PR TITLE
qhull: update to 2020.1

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR updates `qhull` to its latest upstream version and now makes use of the `github` PG. 

I couldn't find a requirement for a ```c++11``` compatible compiler, but I cannot get it to compile without adding `-std=c++11` and `compiler.cxx_standard   2011`. The failures are listed in the commit message and I would appreciate it is someone more knowledgeable than me could take a look my solution is the correct/preferred on.

One other question is whether we should rename the `perf` variant to `native` which is more commonly used for this purpose in other ports.

Finally, I have rev-bumped all ports that depend on `qhull` since this version has "increased the SOVERSION to 8.0 due to ABI breakage in 2019.1"

###### Tested on
macOS 10.14.6 18G5033
Xcode 10.3 10G8

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`? One test fails with "child aborted" message, don't know why...
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
the failures of `gdal`, `libpcl`, `saga`, `plplot510-[single`, and `solid` seem unrelated to the `qhull` update as far as I can tell

**Comment by NicosPavlov** [comment]
The upgrade seems not affect palapeli, which uses only qvoronoi in qhull.  The binary is not broken after upgrading qhull, and it rebuilds fine. 

On a side note: it seems that the post-patch reinplace step in qhull's portfile does not change anything at this point.

**Comment by reneeotten** [comment]
> The upgrade seems not affect palapeli, which uses only qvoronoi in qhull. The binary is not broken after upgrading qhull, and it rebuilds fine.

I attempted to build all the ports that list `qhull` as a dependency. Indeed `palapeli` and `ipe` do not link to it so these do not need a revision bump (removed now). The others do and just to be safe I still bump the revision for ports that currently do not build for unrelated reasons (i.e., `plplot510`, `solid`, `gdal`, `libpcl`, `saga`).

> On a side note: it seems that the post-patch reinplace step in qhull's portfile does not change anything at this point.

Thanks, I missed that indeed... remove now.

**Comment by kencu** [comment]
you can probably get rid of the custom blacklisting now that you asked base for a cxx 2011 compatible compiler.

**Comment by reneeotten** [comment]
> you can probably get rid of the custom blacklisting now that you asked base for a cxx 2011 compatible compiler.

thanks @kencu, you're right about that - I have removed it. Also included now the rename of the `perf` variant to `native`.

**Comment by reneeotten** [comment]
if there are no further comments I will merge this by the end of today

**Pull request merged**
