### PR TITLE
atom: remove obsolete port

### PR DESCRIPTION
**Pull request by aeiouaeiouaeiouaeiouaeiouaeiou**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.8.5 12F2560 x86_64
Xcode 5.1.1 5B1008

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
Does it fail to build as-is?

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@barracuda156 this thing is complex to build and using NPM dependencies, whoever needs it uses a standalone installer package. It's definitely not a big loss.

**Comment by barracuda156** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou (My general opinion is that it is better not to break/remove something unnecessarily, even if only few users are there, but if it does not build and fixing is hard, then perhaps removal is an okay option.)

**Comment by pmetzger** [comment]
I think it's not a question of "don't break it, people might want it". This is a complicated package that requires continuous maintenance including for security issues and which will never get any further maintenance. People who wanted what Atom provided have almost all moved to VS Code. Let's respect the maintainers wishes.

**Comment by mascguy** [comment]
If there's no replacement port, there's no need to mark it obsolete. Simply delete it entirely.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
