### PR TITLE
rust: update to 1.81.0

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with ~`sudo port -vst install`~ `sudo port -d destroot`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by herbygillot** [comment]
@cyckl - would it be possible to test on Intel?

**Comment by herbygillot** [comment]
Merging this for now. We'll commit fixes if we run into anything with Intel.

**Comment by cyckl** [comment]
> @cyckl - would it be possible to test on Intel?

Sure, give me a few hours

**Comment by herbygillot** [comment]
> > @cyckl - would it be possible to test on Intel?
> 
> ~Sure, give me a few hours~
> 
> Actually, if it builds properly on the build servers I should expect local testing wont reveal much to us.

Yeah, I merged this before waiting. Still, much appreciated.

**Pull request merged**
