### PR TITLE
libfmt9: update to 9.1.0

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Let’s see if everything builds.
`openimageio` may fail, since it fails on several systems at the moment: https://ports.macports.org/port/openimageio/details

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Two CI passed fine, looks like all good.

**Comment by barracuda156** [comment]
@MarcusCalhoun-Lopez CI for macos-11 failed due to `openimageio`. The port is currently broken, not due to this PR. Could you look into that, please?

**Review by mascguy — APPROVED** [review]
Refined the changes to `libfmt9`, including some additions needed for v9.1.

**Comment by barracuda156** [comment]
@mascguy Thank you!

**Pull request merged**
