### PR TITLE
update wxWidgets-3.2 to 3.1.4

### PR DESCRIPTION
**Pull request by ra1nb0w**
#### Description

update wxWidgets-3.2 to 3.1.4

[Changelog](https://raw.githubusercontent.com/wxWidgets/wxWidgets/v3.1.4/docs/changes.txt)

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.15.6 19G73
Xcode 11.5 11E608c

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by RJVB** [comment]
>@mojca for port wxWidgets-3.2.

Has anyone heard from @mojca?!

As to Audacity, last time I looked even their git/head didn't function properly with wxWidgets after 3.1.2.916 (or so).

**Comment by ra1nb0w** [comment]
Me no. And the last words about Audacity was at https://github.com/macports/macports-ports/pull/5653
Maybe you can open a PL to update audacity.

**Comment by ra1nb0w** [comment]
are there any objections?

**Comment by ctreleaven** [comment]
OK with me.

**Comment by RJVB** [comment]
>are there any objections?

Not if it doesn't break Audacity (I don't have time to check nor fix ATM) ... and I think Mojca should have the final word seeing how she is the main wxWidgets-related maintainer (AFAIK).

**Comment by ra1nb0w** [comment]
> Not if it doesn't break Audacity (I don't have time to check nor fix ATM) ... and I think Mojca should have the final word seeing how she is the main wxWidgets-related maintainer (AFAIK).

Audacity is using `wxWidgets-3.0` and this is why I said that you should open a new PR with your changes to move Audacity to `wxWidgets-3.2`. The maintainer timeout is 72 hours. I wait another day and the I will merge.

**Comment by ra1nb0w** [comment]
maintainer timeout. merge.

**Pull request merged**
