### PR TITLE
libvpx: generic fix for PowerPC

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Generic fix for PowerPC.
@kencu We are finally committing it! :)

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6 PPC
Xcode 3.2

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x ] tested basic functionality of all binary files?

Specific ppc targets remain broken on @1.11.0, though it may be fixable. I will try when get time and mood. (For now, I do not include patches to restore powerpc-apple-darwin target, since it cannot be used at the moment anyway.)
My earlier ticket here: https://trac.macports.org/ticket/64675
Basic functionality has been tried: https://trac.macports.org/ticket/64653

If anyone can test it, please provide feedback.

### CODE REVIEW

**Comment by barracuda156** [comment]
I do not understand what’s up with bots:
```
Run sudo find \
[2](https://github.com/macports/macports-ports/runs/6146151099?check_suite_focus=true#step:9:2)
  sudo find \
[3](https://github.com/macports/macports-ports/runs/6146151099?check_suite_focus=true#step:9:3)
    /tmp/mpbb \
[4](https://github.com/macports/macports-ports/runs/6146151099?check_suite_focus=true#step:9:4)
    -maxdepth 1 \
[5](https://github.com/macports/macports-ports/runs/6146151099?check_suite_focus=true#step:9:5)
    -mindepth 1 \
[6](https://github.com/macports/macports-ports/runs/6146151099?check_suite_focus=true#step:9:6)
    -type d \
[7](https://github.com/macports/macports-ports/runs/6146151099?check_suite_focus=true#step:9:7)
    -print \
[8](https://github.com/macports/macports-ports/runs/6146151099?check_suite_focus=true#step:9:8)
    -exec chmod -R go+rX {} \;
[9](https://github.com/macports/macports-ports/runs/6146151099?check_suite_focus=true#step:9:9)
  shell: /bin/bash -e {0}
[10](https://github.com/macports/macports-ports/runs/6146151099?check_suite_focus=true#step:9:10)
find: /tmp/mpbb: No such file or directory
[11](https://github.com/macports/macports-ports/runs/6146151099?check_suite_focus=true#step:9:11)
Error: Process completed with exit code 1.
```

**Comment by mascguy** [comment]
> I do not understand what’s up with bots:
> [...]

It looks like you have a few minor syntax errors, which is causing the CI failures. In short, your checks for `ppc` and `ppc64` include several extra curly braces, which are the issue:

```
if {${build_arch} eq "ppc" || {${build_arch} eq "ppc64"}} {
```

should be:

```
if {${build_arch} eq "ppc" || ${build_arch} eq "ppc64"} {
```

**Comment by barracuda156** [comment]
> It looks like you have a few minor syntax errors, which is causing the CI failures. In short, your checks for `ppc` and `ppc64` include several extra curly braces, which are the issue:

@mascguy Oops, thank you. Fixed that, but bots still unsatisfied.

I just checked on another machine now, 10.6.8 Server, and it has _parsed and built_ normally, though failed at destroot, oddly:
```
make[1]: Nothing to be done for `all'.
make: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/libvpx-1.11.0'
--->  Staging libvpx into destroot
. changed
	gid expected 0 found 80 modified
./usr missing (created)
. missing (directory not created: File exists)
./Applications missing (created)
./Developer missing (created)
./Library missing (created)
. changed
	gid expected 80 found 0 modified
./bin missing (created)
./etc missing (created)
./include missing (created)
./lib missing (created)
./lib/pkgconfig missing (created)
./libexec missing (created)
./sbin missing (created)
./share missing (created)
./share/doc missing (created)
./share/info missing (created)
./share/man missing (created)
./share/man/cat1 missing (created)
./share/man/cat2 missing (created)
./share/man/cat3 missing (created)
./share/man/cat4 missing (created)
./share/man/cat5 missing (created)
./share/man/cat6 missing (created)
./share/man/cat7 missing (created)
./share/man/cat8 missing (created)
./share/man/cat9 missing (created)
./share/man/catl missing (created)
./share/man/catn missing (created)
./share/man/man1 missing (created)
./share/man/man2 missing (created)
./share/man/man3 missing (created)
./share/man/man4 missing (created)
./share/man/man5 missing (created)
./share/man/man6 missing (created)
./share/man/man7 missing (created)
./share/man/man8 missing (created)
./share/man/man9 missing (created)
./share/man/manl missing (created)
./share/man/mann missing (created)
./share/nls missing (created)
./share/nls/C missing (created)
./share/nls/af_ZA.ISO8859-1 missing (created)
./share/nls/af_ZA.ISO8859-15 missing (created)
./share/nls/bg_BG.CP1251 missing (created)
./share/nls/cs_CZ.ISO8859-2 missing (created)
./share/nls/da_DK.ISO8859-1 missing (created)
./share/nls/da_DK.ISO8859-15 missing (created)
./share/nls/de_AT.ISO8859-1 missing (created)
./share/nls/de_AT.ISO8859-15 missing (created)
./share/nls/de_CH.ISO8859-1 missing (created)
./share/nls/de_CH.ISO8859-15 missing (created)
./share/nls/de_DE.ISO8859-1 missing (created)
./share/nls/de_DE.ISO8859-15 missing (created)
./share/nls/el_GR.ISO8859-7 missing (created)
./share/nls/en_AU.ISO8859-1 missing (created)
./share/nls/en_AU.ISO8859-15 missing (created)
./share/nls/en_AU.US-ASCII missing (created)
./share/nls/en_CA.ISO8859-1 missing (created)
./share/nls/en_CA.ISO8859-15 missing (created)
./share/nls/en_CA.US-ASCII missing (created)
./share/nls/en_GB.ISO8859-1 missing (created)
./share/nls/en_GB.ISO8859-15 missing (created)
./share/nls/en_GB.US-ASCII missing (created)
./share/nls/en_NZ.ISO8859-1 missing (created)
./share/nls/en_NZ.ISO8859-15 missing (created)
./share/nls/en_NZ.US-ASCII missing (created)
./share/nls/en_US.ISO8859-1 missing (created)
./share/nls/en_US.ISO8859-15 missing (created)
./share/nls/es_ES.ISO8859-1 missing (created)
./share/nls/es_ES.ISO8859-15 missing (created)
./share/nls/et_EE.ISO8859-15 missing (created)
./share/nls/fi_FI.ISO8859-1 missing (created)
./share/nls/fi_FI.ISO8859-15 missing (created)
./share/nls/fr_BE.ISO8859-1 missing (created)
./share/nls/fr_BE.ISO8859-15 missing (created)
./share/nls/fr_CA.ISO8859-1 missing (created)
./share/nls/fr_CA.ISO8859-15 missing (created)
./share/nls/fr_CH.ISO8859-1 missing (created)
./share/nls/fr_CH.ISO8859-15 missing (created)
./share/nls/fr_FR.ISO8859-1 missing (created)
./share/nls/fr_FR.ISO8859-15 missing (created)
./share/nls/hi_IN.ISCII-DEV missing (created)
./share/nls/hr_HR.ISO8859-2 missing (created)
./share/nls/hu_HU.ISO8859-2 missing (created)
./share/nls/is_IS.ISO8859-1 missing (created)
./share/nls/is_IS.ISO8859-15 missing (created)
./share/nls/it_CH.ISO8859-1 missing (created)
./share/nls/it_CH.ISO8859-15 missing (created)
./share/nls/it_IT.ISO8859-1 missing (created)
./share/nls/it_IT.ISO8859-15 missing (created)
./share/nls/ja_JP.SJIS missing (created)
./share/nls/ja_JP.eucJP missing (created)
./share/nls/ko_KR.eucKR missing (created)
./share/nls/la_LN.ISO8859-1 missing (created)
./share/nls/la_LN.ISO8859-15 missing (created)
./share/nls/la_LN.ISO8859-2 missing (created)
./share/nls/la_LN.ISO8859-4 missing (created)
./share/nls/la_LN.US-ASCII missing (created)
./share/nls/lt_LT.ISO8859-4 missing (created)
./share/nls/nl_BE.ISO8859-1 missing (created)
./share/nls/nl_BE.ISO8859-15 missing (created)
./share/nls/nl_NL.ISO8859-1 missing (created)
./share/nls/nl_NL.ISO8859-15 missing (created)
./share/nls/no_NO.ISO8859-1 missing (created)
./share/nls/no_NO.ISO8859-15 missing (created)
./share/nls/pl_PL.ISO8859-2 missing (created)
./share/nls/pt_BR.ISO8859-1 missing (created)
./share/nls/pt_PT.ISO8859-1 missing (created)
./share/nls/pt_PT.ISO8859-15 missing (created)
./share/nls/ro_RO.ISO8859-2 missing (created)
./share/nls/ru_RU.CP866 missing (created)
./share/nls/ru_RU.ISO8859-5 missing (created)
./share/nls/ru_RU.KOI8-R missing (created)
./share/nls/sk_SK.ISO8859-2 missing (created)
./share/nls/sl_SI.ISO8859-2 missing (created)
./share/nls/sv_SE.ISO8859-1 missing (created)
./share/nls/sv_SE.ISO8859-15 missing (created)
./share/nls/tr_TR.ISO8859-9 missing (created)
./share/nls/uk_UA.ISO8859-5 missing (created)
./share/nls/uk_UA.KOI8-U missing (created)
./share/nls/zh_CN.eucCN missing (created)
./share/nls/zh_TW.Big5 missing (created)
./share/skel missing (created)
./var missing (created)
./var/cache missing (created)
./var/db missing (created)
./var/log missing (created)
./var/run missing (created)
./var/spool missing (created)
./www missing (created)
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/libvpx-1.11.0" && /usr/bin/make -w install verbose=1 DESTDIR=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot 
make: Entering directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/libvpx-1.11.0'
mkdir -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/
cp -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/libvpx-1.11.0/vpx/vp8.h /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/vp8.h
mkdir -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/
cp -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/libvpx-1.11.0/vpx/vp8cx.h /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/vp8cx.h
mkdir -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/
cp -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/libvpx-1.11.0/vpx/vpx_ext_ratectrl.h /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/vpx_ext_ratectrl.h
mkdir -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/
cp -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/libvpx-1.11.0/vpx/vp8dx.h /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/vp8dx.h
mkdir -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/
cp -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/libvpx-1.11.0/vpx/vpx_codec.h /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/vpx_codec.h
mkdir -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/
cp -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/libvpx-1.11.0/vpx/vpx_frame_buffer.h /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/vpx_frame_buffer.h
mkdir -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/
cp -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/libvpx-1.11.0/vpx/vpx_image.h /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/vpx_image.h
mkdir -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/
cp -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/libvpx-1.11.0/vpx/vpx_integer.h /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/vpx_integer.h
mkdir -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/
cp -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/libvpx-1.11.0/vpx/vpx_decoder.h /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/vpx_decoder.h
mkdir -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/
cp -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/libvpx-1.11.0/vpx/vpx_encoder.h /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/include/vpx/vpx_encoder.h
mkdir -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/lib/
cp -p libvpx.a /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/lib/libvpx.a
mkdir -p /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/lib/pkgconfig/
cp -p vpx.pc /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/lib/pkgconfig/vpx.pc
make[1]: Nothing to be done for `install'.
make[1]: Nothing to be done for `install'.
make: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/libvpx-1.11.0'
Error: Failed to destroot libvpx: no files matched glob pattern "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/work/destroot/opt/local/lib/libvpx.*.dylib"
Error: See /opt/local/var/macports/logs/_opt_PPCSnowLeopardPorts_multimedia_libvpx/libvpx/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there
is a bug.
Error: Processing of port libvpx failed
```
But this is in Rosetta, strange things do happen.

**Comment by barracuda156** [comment]
@evanmiller Could you check it on a PPC machine when you have time, please?

**Comment by barracuda156** [comment]
@mascguy @kencu Any idea what’s still wrong? I do not get errors locally – neither on 10.6 PPC, nor on 10.6.8 where I build for ppc.

**Comment by evanmiller** [comment]
Why don't you make these changes to `libvpx-devel` first? Then it will be easier for others to test it without risk of breaking anything.

**Comment by barracuda156** [comment]
@evanmiller We can’t break something that has been broken for years already :) My changes only concern PowerPC. But anyway, I don’t object making a PR for `libvpx-devel` either.

**Comment by mascguy** [comment]
> Why don't you make these changes to `libvpx-devel` first? Then it will be easier for others to test it without risk of breaking anything.

Agreed, and I was going to suggest the same. And sorry for the delayed response on all of these, have been offline recently due to a nasty case of the Flu.

**Comment by barracuda156** [comment]
> Agreed, and I was going to suggest the same. And sorry for the delayed response on all of these, have been offline recently due to a nasty case of the Flu.

@mascguy Sure, no issues. Get well!

**Review by mascguy — APPROVED** [review]
I squashed a few fix-related commits, and reconciled with the latest changes for `libvpx-devel`.

Thanks again!

**Comment by barracuda156** [comment]
> I squashed a few fix-related commits, and reconciled with the latest changes for `libvpx-devel`.
> 
> Thanks again!

@mascguy Thank you!

**Pull request merged**
