### PR TITLE
proj: rename port to proj5; migrate proj[4-9] ports to subports of `proj`

### PR DESCRIPTION
**Pull request by nilason**
#### Description

This is an attempt to address the issue raised on [macports-dev](https://lists.macports.org/pipermail/macports-dev/2023-June/045029.html), regarding `proj` ports.

- Rename the port `proj` to `proj5`.
- Migrate all ports `proj[4-9]` to be subports of the new stub port `proj`.
- The purpose of the new stub `proj`, is to install the latest `proj[N]` port (presently `proj9`).

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.4.1 23E224 arm64
Xcode 15.3 15E204a

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by nilason** [comment]
The macOS 14 runner failed on rev-bumped `ncarg` and `gerris`. The reasons are independent of this PR, see [ncarg ticket](https://trac.macports.org/ticket/67455) [gerris ticket](https://trac.macports.org/ticket/69726).

**Review by mklein-de — APPROVED** [review]

**Comment by Dave-Allured** [comment]
I support this `proj` refactor.  I suggest that you drop changes for messed up ports `gerris` and `ncarg`, file separate PR's or track tickets for them later.  That should fix CI and get this moving.

**Comment by nilason** [comment]
> I support this `proj` refactor.

Great!

> I suggest that you drop changes for messed up ports `gerris` and `ncarg`, file separate PR's or track tickets for them later. That should fix CI and get this moving.

The dependencies for `gerris` and `ncarg` changes, (actually only by name, as the dependency remain PROJ v.5), so including them is necessary. This could (and should) be merged in spite of the failed runner (as the cause of that is independent of this PR and reported).

@stromnov Being the maintainer for most of the proj ports, it would be good to hear your opinion of this. I'd appreciate this finally moving on.

**Comment by Dave-Allured** [comment]
> > I suggest that you drop changes for messed up ports `gerris` and `ncarg`, file separate PR's or track tickets for them later. That should fix CI and get this moving.
> 
> The dependencies for `gerris` and `ncarg` changes, (actually only by name, as the dependency remain PROJ v.5), so including them is necessary. This could (and should) be merged in spite of the failed runner (as the cause of that is independent of this PR and reported).

I agree that those simple changes for `gerris` and `ncarg` changes are necessary.  However, as a Macports newbie, I was recently lectured on the importance of all CI runners passing before merge.  Therefore I see dropping those two ports and breaking them temporarily,  as the easy way forward.

That rule probably applies only to newbies, not experienced devs.   ;-)   If you can convince the powers that be, to merge in the face of unrelated CI fails, then yes that would be best.

**Comment by nilason** [comment]
I have now rebased. The failing CI is caused by failure to build `gerris` on macos-14 reported with https://trac.macports.org/ticket/69726, which is  **not** related to this PR.

Please, could we move forward with this. This has now been lingering here for soon 3 months.

**Comment by Dave-Allured** [comment]
> could we move forward with this

Macports requires that all CI checks pass.  You are not obligated to fix unrelated ports, especially ones like `gerris` which are not popular and not being maintained.  Your only expedient recourse is to drop the commit for `gerris`.  That port can be fixed later for the `proj` update, if another volunteer becomes interested.

I started to look at `gerris`, and decided it was more work than I could take on at that time.  In case anyone else is interested, I thought that `autoconf` with possible `configure.ac` updates might be a good way forward.

**Comment by nilason** [comment]
> Macports requires that all CI checks pass.

If this is technically necessary to for all CIs to pass, to enable merge of a PR, I'll gladly drop `gerris` from this PR. `gerris` seems to have been abandoned upstream too, with more than 10 years since latest update. Would be good to get some feedback on that issue (too) from a maintainer. Too bad if that broken port alone holds this back.

> I started to look at `gerris`, and decided it was more work than I could take on at that time. In case anyone else is interested, I thought that `autoconf` with possible `configure.ac` updates might be a good way forward.

Patching configure was the easy part.

**Comment by Dave-Allured** [comment]
> Patching configure was the easy part.

LOL!  Someday you can explain to me what *that* means.

**Comment by nilason** [comment]
> > Patching configure was the easy part.
> 
> LOL! Someday you can explain to me what _that_ means.

```diff
--- configure.ac.orig	2013-12-06 16:51:21
+++ configure.ac	2024-07-01 13:38:23
@@ -146,7 +146,7 @@
 # check that pointers can be stored in doubles
 AC_MSG_CHECKING(whether pointers can be stored in doubles)
 AC_TRY_RUN([
-main () {
+int main(void) {
   if (sizeof (void *) > sizeof (double))
     return 1;
   return 0;
--- configure.orig	2013-12-06 16:51:37
+++ configure	2024-07-01 13:38:12
@@ -12399,7 +12399,7 @@
   cat confdefs.h - <<_ACEOF >conftest.$ac_ext
 /* end confdefs.h.  */
 
-main () {
+int main(void) {
   if (sizeof (void *) > sizeof (double))
     return 1;
   return 0;
```

Compilation is then littered with warnings and eventually errors out pretty early on -Wincompatible-function-pointer.

**Comment by Dave-Allured** [comment]
Ah, I see.  I saw only the first two untyped `main`'s, and thought there would be a lot more.  Thus `autoconf`, maybe.  But you nailed that part.

Maybe some day I can look at `gerrit` again, when my workload allows it.

**Comment by nilason** [comment]
I resorted to add cflag `-Wno-error=incompatible-function-pointer-types` to `gerris` for Clang builds on macOS 14+. This is obviously not a future proof solution, but a proper fix isn't trivial.

**Comment by nilason** [comment]
@stromnov As maintainer for the PROJ ports, please notify your opinion on this.

**Review by dgilman — APPROVED** [review]

**Comment by stromnov** [comment]
It looks good to me.

**Comment by nilason** [comment]
> It looks good to me.

Great! Please go ahead and merge, this change is long awaited.

**Comment by nilason** [comment]
@stromnov I have now rebased and added update to PROJ 9.5.0, which was just recently released.

**Comment by reneeotten** [comment]
thanks @nilason since the maintainer has now responded I'm happy to merge. Would you be so kind as to fix the lint warnings about `platforms darwin`; that line can/should be removed as it has been the default since MacPorts 2.7 and now emits a warning about it since MacPorts 2.10.

**Comment by nilason** [comment]
> thanks @nilason since the maintainer has now responded I'm happy to merge. Would you be so kind as to fix the lint warnings about `platforms darwin`; that line can/should be removed as it has been the default since MacPorts 2.7 and now emits a warning about it since MacPorts 2.10.

I removed platforms from gerris and qlandkartegt, the CI linter is not working correctly with regards to proj, with multiple commits, it doesn't take into account only the end result (which doesn't contain platforms).

**Comment by nilason** [comment]
@reneeotten  Thanks!!

**Pull request merged**
