### PR TITLE
perl5: remove special-cased compiler selection for subports on 10.6 a…

### PR DESCRIPTION
**Pull request by dbevans**
…nd earlier

See previous commit https://github.com/macports/macports-ports/commit/c86f124d25636010425a54702171f33156056319 for rationale.  This commit fixed instances of compiler mismatch on 10.7+ when building XS extensions.

However, XS extensions are continuing to fail on 10.6 and earlier where the subports select clang-3.4 rather than the post MP 2.6 default selection clang-9.0.

See the most recent 10.6 build log of p5-encode (https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/15983/steps/install-port/logs/stdio} for a good example.

By removing the special-cased compiler selection, the subports should (hopefully) build using the same compiler as selected for the extensions, removing the conflict.

I'm not able to directly test this theory without committing this change so I call on people who have access to a 10.6 test system to verify the efficacy of the change and report yea or nay.  Note that this will rebuild the subports redundantly on 10.7+ but I don't see a simple way to work around that and it shouldn't do any harm.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
will check

**Comment by dbevans** [comment]
> after this commit, perl5.30 modules do build with clang-9.0, and build correctly even if clang-3.4 is deactivated, as you would expect. So seems to fix this issue.

Thanks, Ken. On that basis, and no objections, I will go ahead the merge the PR.

**Comment by mojca** [comment]
Thanks for working on this.

I failed to see whether anyone actually managed to get rid of the hardcoded compiler for XS in this perl mess.

**Comment by jmroot** [comment]
> I failed to see whether anyone actually managed to get rid of the hardcoded compiler for XS in this perl mess.

There is a default compiler baked in to perl, but the perl5 portgroup sets CC on the command line, which has worked for most XS in the past. You're still doomed if the Makefile ignores the command line setting and you need a compiler other than clang-9.0.

But the bigger immediate issue is that it's now impossible to bootstrap clang-9.0 on 10.6 because of circular dependencies.

**Comment by kencu** [comment]
Before the commit, the perl modules wouldn't build, I guess, which prompted Ryan to ask Dave to fix it. I guess this was going to have to be looked at either way.

perl-bootstrap port?

**Comment by jmroot** [comment]
> perl-bootstrap port?

Maybe, but it wouldn't just be used for bootstrapping, as all clang ports 3.7 and later depend on perl5. The better option would be to fix the perl module builds to use the chosen compiler.

**Comment by kencu** [comment]
to be sure. i guess like your headsches with python, that turns out to be prohibitively difficult. Hopefully we'll eventually succeed in stripping macports of all these baked-in configuration details.

**Pull request merged**
