### PR TITLE
poedit: update to 2.2

### PR DESCRIPTION
**Pull request by l2dy**

### CODE REVIEW

**Comment by pmetzger** [comment]
Your "Description" is a bit minimal. :(

**Comment by l2dy** [comment]
I don't expect this to be merged as is because it only builds with Xcode 10.

**Comment by pmetzger** [comment]
Then why do a pull request?

**Comment by l2dy** [comment]
To test the build with Xcode 10, which I don't have locally.

**Comment by pmetzger** [comment]
You might have mentioned that in the description at top. That said, you can get your own Travis account and use their CI for free very easily.

**Comment by l2dy** [comment]
> You might have mentioned that in the description at top. That said, you can get your own Travis account and use their CI for free very easily.

I am using Travis CI for free here. May I ask you to ignore my pull requests with no description and for my own ports?

**Comment by pmetzger** [comment]
> I am using Travis CI for free here.

You can also use it for free if you turn it on for your own account. There's no difference. It's free for public repositories. You just go to travis-ci.com and log in with your github creds and you're pretty much done.

> May I ask you to ignore my pull requests with no description and for my own ports?

It's difficult to do that.

**Comment by mojca** [comment]
I believe it is perfectly ok to occasionally misuse our PR infrastructure for testing individual strategies, asking users to set up their own Travis account just for that is a huge overkill. But it probably does make sense to add at least something like "Testing, don't merge." in the description.

**Comment by l2dy** [comment]
> I believe it is perfectly ok to occasionally misuse our PR infrastructure for testing individual strategies, asking users to set up their own Travis account just for that is a huge overkill. But it probably does make sense to add at least something like "Testing, don't merge." in the description.

Exactly what I thought. I was considering if I should apply this update to Xcode 10 users or macOS 10.14 users, and currently decided to only update on macOS > 10.13.

> > I am using Travis CI for free here.
> 
> You can also use it for free if you turn it on for your own account. There's no difference. It's free for public repositories. You just go to travis-ci.com and log in with your github creds and you're pretty much done.
> 
> > May I ask you to ignore my pull requests with no description and for my own ports?
> 
> It's difficult to do that.

I understand your wish to clear the PR queue, but Travis CI binds to repositories so I'll need to create a new repository (introducing the third upstream in my local git repo, pushing changes across them is painful due to the slow network here), or use my fork (hard to create PRs in it, because I have to re-select the target repository from macports/macports-ports, and using Travis on branches is an overkill).

**Comment by pmetzger** [comment]
> I understand your wish to clear the PR queue, but Travis CI binds to repositories so I'll need to create a new repository

You can just have travis run against your fork. It's really easy, try it! It might even make your life easier. :)

**Comment by mojca** [comment]
@pmetzger: If anyone, @l2dy is the one who's supposed to know how to use Travis :)
I still agree it's an overkill. Just please: let's not continue this nitpicking here, please, it's getting off-topic and non-productive. Let's not steal creative time and let's not kill enthusiasm from valuable contributors. That goes to both of you.

**Comment by pmetzger** [comment]
@l2dy Can this be closed at this point?

**Comment by l2dy** [comment]
I'd like to provide different versions of poedit for macOS 10.14 or below, but the patch has changed so I need to keep two versions of the patch. I've not decided to split a port out (`poedit21`) or use subports yet. I'll work on this later.

**Pull request closed without merging**
