### PR TITLE
icu: update to 72.1

### PR DESCRIPTION
**Pull request by catap**
#### Description

This is update of MacPorts ICU from 71.1 to 72.1.

I've added a `[skip-ci]` for the second commit because it defently won't be built on GitHub CI timeout.

I also haven't tested all bumped ports, but `icu-devel` with the same version were here a while and all mainteners might have to test it against their ports.

Anyway, I'm willing to fix all broken ports, feel free to open an issues ;)

###### Type(s)

- [x] enhancement

###### Tested on

macOS 12.6 21G115 x86_64
Xcode 14.0.1 14A400

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by judaew — APPROVED** [review]
LGTM for port `libqalculate` and `zk`.

**Comment by catap** [comment]
I've marked it as draft because I've removed the second commit with a massive revision bump to enjoy github CI on the first commit.

In ~20 minutes I'll put it back ;)

**Comment by judaew** [comment]
Warning during reinplace:

```
Warning: reinplace s|host_alias=\".*\"|host_alias=\"\"|g didn't change anything in /opt/local/var/macports/build/_opt_local_var_macports_sources_github.com_judaew_macports-ports_devel_icu/icu/work/icu/source/config/icu-config
```

**Comment by catap** [comment]
@judaew this is a hacks for support old architectures. On modern hardware it may trigger a warning, yes

**Comment by ryandesign** [comment]
> @judaew this is a hacks for support old architectures. On modern hardware it may trigger a warning, yes

Ideally, please fix it so that the warning does not occur. Eventually, this will be a hard error. See https://trac.macports.org/ticket/60844

**Comment by catap** [comment]
@ryandesign ok, I'll keep such notes, but I prefer to do it as separated PR.

**Review by nerdling — APPROVED** [review]

**Comment by catap** [comment]
Rebased to solve conflicts

**Review by i0ntempest — APPROVED** [review]

**Comment by catap** [comment]
@ryandesign I'd like to point a ticket which was a cause for this `reinplace`: https://trac.macports.org/ticket/45268

I'll try to make such differences as part of `icu-devel` port with hope that folks with PPC may try it and test it.

**Review by michaelld — APPROVED** [review]
LGTM all around

**Comment by Schamschula** [comment]
I'm fine with revision bumping my ports.

**Comment by kencu** [comment]
>  folks with old OS may try it and test it.

It has nothing to do with old OS versions. 

ICU was adding ```host_alias``` on all builds, including on Monterey.

Because ```host_alias``` defers between arm64 and Intel, the muniversal merge was failing when trying to merge the ports. So that is why the ```host_alias``` line was stripped out.

```
host_alias = aarch64-apple-darwin20.1.0
host_alias = x86_64-apple-darwin20.1.0
```

If you want to remove the "reinplace didn't replace anything" message you could strip these only if the build is universal, as that is when it really matters. I left it like this when I fixed ICU so the universal and non-universal ports would remain as identical as possible, as consistency is key to 25,000 ports being maintained.

Isn't there an option to make reinplace shut up about this instead?

**Comment by kencu** [comment]
In fact, I only added that a year ago, to fix a long-was-broken universal build of ICU:

https://github.com/macports/macports-ports/commit/f0ec05eb0777ca4d3c5c4232edab387ba7a6f2e5

**Comment by michaelld** [comment]
> Isn't there an option to make reinplace shut up about this instead?

yes: `reinplace -q`

**Comment by catap** [comment]
@kencu, @michaelld, @ryandesign do you have an idea that's happened with `reinplace -q` after nothing had changed is hard error?

**Comment by michaelld** [comment]
> @kencu, @michaelld, @ryandesign do you have an idea that's happened with `reinplace -q` after nothing had changed is hard error?

When using `reinplace -q` the command will not print anything out nor will it error out if it fails. It will only print anything if it succeeds, and even then maybe it doesn't print anything (because `-q`) ... I actually don't recall this scenario. Maybe others remember more clearly than me.

**Comment by kencu** [comment]
> @kencu, @michaelld, @ryandesign do you have an idea that's happened with `reinplace -q` after nothing had changed is hard error?

Good question!

I don't know how exactly the TCL code might make the reinplace a hard error -- or if it could be smart enough to know if the "-q" flag was set. 

If the TCL just looks for non-zero output and makes that an error, I think --- a lot of reinplaces will fail. Sometimes, you want reinplace to strip something out if it is there -- even if it is not always there, like these host_alias lines...

**Comment by catap** [comment]
Just rebased to the last master and fixed a few conflicts.

It was opened for more than 3 days. May I ask anyone to merge it? Otherwise it will be insane.

Thanks.

**Comment by judaew** [comment]
Sure, thank you @catap for the contribution 🌟

**Pull request merged**
