### PR TITLE
[volk-]gnss-sdr: Update to version 0.0.10

### PR DESCRIPTION
**Pull request by carlesfernandez**
gnss-sdr-devel, gnss-sdr-next subports also updated, as well as volk-gnss-sdr counterparts.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.3 18D42
Xcode 10.1 10B61 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by michaelld** [comment]
@carlesfernandez Can this new gnss-sdr release use GR 3.7 latest release, or did you update it for the forthcoming 3.8 release?

**Comment by carlesfernandez** [comment]
@michaelld It can use both (at least it is indended to do so)

**Comment by michaelld** [comment]
OK I'll give it a go using the final 3.7 GIT master commit ("gnuradio-devel" port) and see if it works. Fingers crossed ...

**Comment by mojca** [comment]
Nitpicking: we try to start commit message with port name(s). You could for example use something like this:
```
[volk-]gnss-sdr: Update to version 0.0.10

Also update gnss-sdr-devel, gnss-sdr-next and volk-gnss-sdr counterparts.
```

**Comment by carlesfernandez** [comment]
@mojca thanks, changed.

@michaelld I can't see what failed in the Azure pipeline log. Could be also a timeout?

**Comment by mojca** [comment]
You changed the title of this PR, but not the commit itself.

**Comment by mojca** [comment]
@carlesfernandez: there are two strange issues, probably none of them is your fault.

One is:
```
--->  Computing dependencies for gnuradio
DEBUG: Checking for conflicts against gnuradio
DEBUG: Searching for dependency: gnuradio-next
DEBUG: Didn't find receipt, going to depspec regex for: gnuradio-next
DEBUG: Searching for dependency: gnuradio-devel
DEBUG: Found Dependency: receipt exists for gnuradio-devel
Error: Can't install gnuradio because conflicting ports are active: gnuradio-devel
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port gnuradio failed
```
I don't know if that's because our CI is broken (and doesn't deactivate ports when it should) or because there are in fact some strange dependencies, potentially defined in a way that two dependencies would satisfy the criteria, and it works on your machine where you have the other one installed than the one that gets installed by default. I didn't investigate any further.

The second issue is that our "list dependencies" sometimes takes up to three hours (for one single subport), and there are multiple (sub)ports to process. Not even Azure can help us if we need 10 hours just to generate the list of dependencies to install.

See https://trac.macports.org/ticket/55041

Both issues above should be taken seriously, but the commit doesn't seem problematic on its own, and there's no reason to delay merging because of these two issues.

**Comment by michaelld** [comment]
@carlesfernandez Sorry this is taking so long; a lot on my queue. I'll hopefully get to this next week.

**Comment by cjones051073** [comment]
@michaelld did you manage to test this ?

**Comment by cjones051073** [comment]
@carlesfernandez please can you squash your two commits into one, making sure the commit message follows the Mp guidelines `portname: comment`

**Comment by michaelld** [comment]
I've been able to test the volk-gnss-sdr* ports & they all pass "make test". I'm having issues with GR and UHD right now, so I can't verify that the gnss-sdr* ports build or pass make test. It looks like the build bots are also having issues ... so, no good way to do testing / verification right at the moment. We've waited long enough for this PR, and since @carlesfernandez is a co-maintainer, let's merge this in once he's followed @cjones051073's request for squashing & fixing the commit message format. My apologies for the delay, again; lots on my plate beyond the GR / UHD issues!

**Comment by carlesfernandez** [comment]
Commits squashed and commit message format fixed in #3989 

I'm closing this one.

**Pull request closed without merging**
