### PR TITLE
apr: use the right compiler

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
See https://trac.macports.org/wiki/UsingTheRightCompiler

No revbump since installed files do not change.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by danielluke** [comment]
This looks ok, but where is CC_FOR_BUILD being used (instead of CC?)

**Comment by danielluke** [comment]
This looks like an upstream bug - it appears to only be used for building tools/gen_test_char - can you file a bug upstream about it? The change here looks good for us for now.

**Comment by MarcusCalhoun-Lopez** [comment]
I am not sure this is an upstream bug.
The use of `CC_FOR_BUILD` seems to have been a [conscious choice](https://svn.apache.org/viewvc?view=revision&revision=1871998) in response to a cross-compiling issue.

**Comment by danielluke** [comment]
I think it's still worthy of a bug. If you set CC you don't expect to also have to set CC_FOR_BUILD in order to get the compiler you want used. If they decide not to fix it at least we'll know that we have to carry the patch forward forever...

**Pull request merged**
