### PR TITLE
Bump default Perl from 5.34 to 5.38

### PR DESCRIPTION
**Pull request by glebm**
The Perl for help2man has been bumped to 5.38 in https://github.com/macports/macports-ports/commit/1d6634e749a96b8a89b92a7fccc1fc6b1de36eb2

This results in 2 perl installations even from a simple `sudo port install bash`

This commit bumps all the default perls from 5.34 to 5.38.

Untested

/cc @barracuda156 @kurthindenburg

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by TheRealKeto** [comment]
I truly feel these could have been different commits (since that's a guideline - one change per file?) but shouldn't these ports also recieve a revision bump?

**Comment by glebm** [comment]
That didn't seem to be the case in the previous default Perl version bump by the maintainer @jmroot in https://github.com/macports/macports-ports/commit/d2a7c094acba41c84dbe792480f6a1b32371d5e7, done all in a single commit

Not sure about revision bump, that commit did not bump revisions except for a handful of packages and I wasn't sure what to do there so I didn't bump any.

**Comment by barracuda156** [comment]
@TheRealKeto It would be impractical to make identical changes in hundreds of ports with one port per commit, and indeed, it is not something generally followed.

**Comment by akkornel** [comment]
For the `wallet` port, this is good to go!  Thanks much for the heads-up.

**Comment by reneeotten** [comment]
> The Perl for help2man has been bumped to 5.38 in [1d6634e](https://github.com/macports/macports-ports/commit/1d6634e749a96b8a89b92a7fccc1fc6b1de36eb2)
> 
> This results in 2 perl installations even from a simple `sudo port install bash`
> 
> This commit bumps all the default perls from 5.34 to 5.38.
> 
> Untested
> 
> /cc @barracuda156 @kurthindenburg

For a first time contributor you might be a little too enthusiastic. This a large change you're suggesting here with quite some implications that will require thorough testing. The fact that you already admit this is "untested" is not a good thing. Please start with small contributions that do not affect the whole MacPorts ecosystem and once you feel comfortable move on to more major things. You can feel free to make this change locally, but I doubt this will happen anytime soon in MacPorts without someone knowledgeable about Perl does the proper due diligence.

**Comment by barracuda156** [comment]
@reneeotten We are yet to hear why `help2man` was switched. Probably that has to be reverted first, so that users aren’t forced to build an extra version of perl just for that.

P. S. Seeing that OpenBSD (which is on conservative side with updating components) uses perl5.38, I think it may be the time for someone to start testing it as the default indeed.

**Comment by dgilman** [comment]
+1 to this. I acknowledge that doing the upgrade this way is unfortunate. It is not the MacPorts way to try and "test in prod" by pushing out updates like this. But given the maintainer availability for Perl I think a bulk upgrade like this is justified.

- The perl interpreter is broadly backwards compatible. Testing is welcome but honestly most of these packages probably worked on release day.
- Maybe as a token of goodwill glebm could test the top N most popular perl dependencies? The MacPorts stats website should have this information, but if not, I imagine the maintainer could do a quick sql query.
- Perl 5.38 has already been available for a year and a half. We could assume that any dependency that did a release after July 2023 was compatible with perl 5.38 and cut down on the number of packages to test.
- Perl 5.34 is six months past EOL for security updates. There is an argument to be made that MacPorts users get more value from a security patched perl than they do for known 5.38 compatibility with every single perl dependency.

**Comment by drkp** [comment]
Agree with the above. It'd be good to do at least _some_ testing but unless there's something specific to 5.38 that makes this harder, the odds are good that there won't be many compatibility issues. We're better off attempting a mass upgrade than doing it piecemeal and leaving everyone stuck with multiple perl versions installed.

And if there are issues, we can always roll it back for specific ports...

**Comment by jmroot** [comment]
> RE 1 file per commit: That didn't seem to be the case in the previous default Perl version bump by the maintainer @jmroot in [d2a7c09](https://github.com/macports/macports-ports/commit/d2a7c094acba41c84dbe792480f6a1b32371d5e7). Also two thousand commits doesn't seem sensible at all.

It is better to split it into multiple commits simply because both GitHub's web interface and Buildbot will be overwhelmed by this many files being modified at once. Maybe 100 files per commit or so.

> RE revision bump: Not sure about the revision bump, [d2a7c09](https://github.com/macports/macports-ports/commit/d2a7c094acba41c84dbe792480f6a1b32371d5e7) did not bump revisions except for a handful of packages and I wasn't sure what to do there so I didn't bump any.

In cases where you are adding a subport or adding a variant, don't bump the revision. If a port uses a fixed version of perl and you change that version, you have to bump the revision. The general rule is that if installing the same port with the same variants will result in different installed files after a change, then the version or revision needs to increase.

**Comment by glebm** [comment]
I'll let somebody else handle this I suppose, as I'm focusing on getting modern gcc on PPC Tiger for now.

**Comment by glebm** [comment]
Whoever handles this next, it'd be nice if the current "main" perl version was a variable, so that an update wouldn't require modifying a ton of files. The revision could also be a number added to the revision of individual packages, so that it can be bumped with a one-line change as well whenever perl is bumped.

**Pull request closed without merging**
