### PR TITLE
wezterm: update to 20220807-113146-c2fee766

### PR DESCRIPTION
**Pull request by shuxiao9058**
#### Description

Update Wezterm to version 20220807-113146-c2fee766

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.4 21F79 arm64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
There was a port (`py-kiwisolver`) with a syntax error in its Portfile causing build failures. Please rebase this PR on top of the latest master.

**Comment by shuxiao9058** [comment]
> There was a port (`py-kiwisolver`) with a syntax error in its Portfile causing build failures. Please rebase this PR on top of the latest master.

maybe we should rerun the build test.

**Comment by herbygillot** [comment]
> maybe we should rerun the build test.

That will not work.

This PR is based upon your branch, `wezterm-20220807-113146-c2fee766`.  Your branch contains the bad commit, here: https://github.com/shuxiao9058/macports-ports/commit/12b3b956e8fbc446111d5b21d99e460ce411d411

Re-running the tests will keep failing because your branch does not contain the fix that I just merged to master here: https://github.com/macports/macports-ports/commit/af2dbab09d304de3e92fefb6836b6fbe8aa5bf99

So in order for tests to pass, you need to rebase your branch on top of the very latest master branch of `macports/macports-ports`, which will then pull in the corrective fix, after which tests and builds should then be able to proceed.

**Comment by herbygillot** [comment]
And as proof, I just re-ran the tests, and they failed again.

**Comment by shuxiao9058** [comment]
> And as proof, I just re-ran the tests, and they failed again.

Is the latest commit is right?

**Pull request merged**
