### PR TITLE
py-myst-parser: Add Python 3.10 subport

### PR DESCRIPTION
**Pull request by judaew**
#### Description

- py-{markdown-it-py,mdit-py-plugins}: Add py310 subport
- py-myst-parser: Add py310 subport

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.1 21C52 x86_64
Xcode 13.2 13C90

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Vadim, would you mind enabling tests for these ports too? That's particularly important if upstream doesn't officially publicize support for Python 3.10, so that we can compare results with Python 3.9. (I know you're a not a newbie, and I'm probably restating something you're already well aware of! But just figured I'd mention it...)

**Comment by jjstickel** [comment]
Works for me to bump 3.10 on markdown-it and mdit.

**Comment by judaew** [comment]
Thanks @jjstickel

**Comment by judaew** [comment]
I'll try adding tests for `py-myst-parser`. It will take me a while.

**Comment by judaew** [comment]
I added a testing phase

**Review by mascguy — APPROVED** [review]

**Comment by judaew** [comment]
@jjstickel Since I have added Python 3.10 support for your ports anyway, I will update to the latest version as well.

**Pull request merged**
