### PR TITLE
kb: Update to 0.1.4

### PR DESCRIPTION
**Pull request by harens**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.6 19G73
Xcode 12.0 12A7209

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by harens** [comment]
Can't see what's happened to the `Run bootstrap script` section of the pipeline to see what's happened. It says task not found.

**Comment by herbygillot** [comment]
I would say rebase this branch against the latest master, and just force-push to trigger CI again.

**Comment by harens** [comment]
Not really sure what happened there, but thanks for your suggestion @herbygillot.

**Comment by herbygillot** [comment]
Thanks @harens

**Pull request merged**
