### PR TITLE
Apply upstream patch for SIP 4.19 to QGis 2.18.2

### PR DESCRIPTION
**Pull request by cmutel**
Cherrypick commit [718581](https://github.com/qgis/QGIS/commit/718581ffb12b723f9a3c0ae01b7ec2d8aed9d4bb) from QGis source, following discussion from [QGis bug tracker #16071](https://hub.qgis.org/issues/16071). Fixes [trac bug 53231](https://trac.macports.org/ticket/53231).

### CODE REVIEW

**Comment by sbortman** [comment]
Any idea when this will be merged?   I could really use it.  :-)

**Comment by cmutel** [comment]
**Do not merge this PR** - it does not fix all the problems with the current build of QGis. There is still a problem with the latest version of the QScintilla library (see discussion in [bug tracker](https://trac.macports.org/ticket/53231)).

**Comment by mojca** [comment]
@Veence, can you please take a look at this? The above comment about waiting for the other ticket to be fixed is no longer too relevant now that the other problem has been solved.

**Comment by mojca** [comment]
@cmutel, @Veence: is any of this still relevant? The referenced [ticket](https://trac.macports.org/ticket/53231) seems to have been closed in the meantime.

**Comment by mojca** [comment]
Given that this no longer applies cleanly, that this was backported from upstream and new versions have been released in the meantime, that the ticket referenced here has been marked as fixed ... I'm closing this for now. In case there's still something you want to apply, please reopen this or open a new PR that can be applied cleanly.

**Pull request closed without merging**
