### PR TITLE
tiledb: cleanup and migrate from legacy dependency management mode

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
#### Description

This PR updates the TileDB port to use the new dependency management mode also known as `TILEDB_VCPKG`, although the port does not use vcpkg. By specifying the [`TILEDB_DISABLE_AUTO_VCPKG`](https://github.com/TileDB-Inc/TileDB/blob/dev/doc/dev/BUILD.md#dependency-management-with-vcpkg) environment variable, vcpkg does not get automatically downloaded, and TileDB's calls to `find_package` and co. resolve to the MacPorts-provided packages.

Furthermore, this PR disables TileDB's superbuild architecture, which will improve build-time performance and protect the port from a breaking change that is planned to happen after a couple releases (TileDB-Inc/TileDB#5021).

I also made some miscellaneous clean-ups, such as removing unnecessary dependencies.

Fixes TileDB-Inc/TileDB#4960

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
Only CI, I don't own a Mac.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by teo-tsirpanis** [comment]
[CI is green on my fork.](https://github.com/teo-tsirpanis/macports-ports/actions/runs/9324983041/job/25671226273)

**Comment by barracuda156** [comment]
@teo-tsirpanis Thank you, I will test this locally today.

**Comment by barracuda156** [comment]
@teo-tsirpanis Please hold on, this bug in `zstdConfig.cmake` has to be fixed first: https://trac.macports.org/ticket/70130

**Review by barracuda156 — APPROVED** [review]
Works for me, thank you.

**Comment by barracuda156** [comment]
@herbygillot @pmetzger This should be good to merge.

**Pull request merged**
