### PR TITLE
maestral: update to 1.9.2

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.4.1
Xcode 15.3

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by reneeotten — COMMENTED** [review]
are you sure that the comment: "# We want to have GUI, but pyqt is broken with python 3.11:" is still accurate? 

It looks like `pyXY-pyqt5-sip` that is mentioned in the linked bugreport builds on all buildbot-systems for both py311 and py312. So perhaps this can actually be updated?

**Comment by barracuda156** [comment]
@reneeotten Yes, let me do that. We will have to have it conditionally, since I assume pyqt4 will not, but it should be Python 3.12 for systems with Qt5.

**Comment by barracuda156** [comment]
@reneeotten Move to 3.12 requires a lot of ports to be updated, but I will try now.

**Comment by barracuda156** [comment]
@reneeotten Done.

**Pull request merged**
