### PR TITLE
wxMaxima: fix for old systems and powerpc

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Draft, since I am rerunning the build with a minor change. Looks like for GTK version building a bundle is suboptimal.
Verified also on Sonoma aarch64 against wxGTK (which the profile does not do, but yes, that also works).

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

macOS 14.5
Xcode 15.3

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
image

image

**Comment by barracuda156** [comment]
Yeah all works correctly now.

**Comment by pmetzger** [comment]
What's the fail on MacOS 13?

**Comment by barracuda156** [comment]
> What's the fail on MacOS 13?

@pmetzger SBCL fails to install, according to the log, unrelated and I won’t deal with that here.

**Comment by barracuda156** [comment]
> Also I don't get why the bundle is an issue?

GTK builds are not designed with macOS in mind. If you ask me why specifically it does not work correctly, I have no idea and no interest to rebuild this multiple times to figure out, it takes 2 hrs per go.
I built it as a bundle at first, and the app does not start from the Finder at all. Digging inside the bundle and starting the binary manually from Terminal worked, but produced a bunch of malloc errors along. I don’t know how to apply legacysupport fix with bundles, because that was not designed with bundles in mind. (For that reason R-app, that is a standalone GUI, is still broken btw.)

AFAIK, using a bundle is completely optional, and normal UNIX way works. It always works, not just here.

But given that GTK is used only on archaic systems here anyway, I suggest using what works.

**Comment by barracuda156** [comment]
@pmetzger If you prefer, I can disable bundle with GTK only for PowerPC (since that is tested) and leave 10.6 x86 with GTK + bundle. I won’t test it, and buildbots won’t show us if it works correctly. But no objections, I do not mind that.

Everything from 10.7 up uses bundle build.

**Comment by pmetzger** [comment]
It's fine.

**Pull request merged**
