### PR TITLE
py-ansible: small update to 2.10.5

### PR DESCRIPTION
**Pull request by adfernandes**
Closes: https://trac.macports.org/ticket/61917
Closes: #10030

### CODE REVIEW

**Comment by mf2k** [comment]
To automatically close the Trac ticket, you need to put the ticket reference in the commit message.

**Comment by jhoyt4** [comment]
...so this broke ansible for my (python38 / Big Sur)

[Track Ticket 62324](https://trac.macports.org/ticket/62324)

**Comment by jhoyt4** [comment]
verified to broken on python39 as well

**Comment by adfernandes** [comment]
https://github.com/macports/macports-ports/pull/10073

**Pull request merged**
