### PR TITLE
libreoffice: Update to 7.6.4.1, apply patch for ICU 74

### PR DESCRIPTION
**Pull request by sideeffect42**
#### Description

This PR updates LibreOffice to the latest release version 7.6.4.1.

This version also does not build cleanly with ICU 74 (which is in MacPorts). I found an upstream bug ([Document Foundation #158108](https://bugs.documentfoundation.org/show_bug.cgi?id=158108)) which has a patch.

I don't know if this patch is perfect, but I pulled it in and modified it so that it applies on the release 7.6.4.1.
It fixed the build on my machine and some basic testing with a few documents suggests that LibreOffice works fine with it.

AFAIU (I'm by no means a Unicode expert) the breakage was in the line and/or sentence breaking algorithms. I don't have a means to verify if this patch maybe affects the breaking of lines.

Fixes [#68938](https://trac.macports.org/ticket/68938).

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.7.2 21G1974 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by sideeffect42** [comment]
The reason the CI seems to be failing is due to a `Illegal instruction: 4` in a `gengal` helper utility:
```
2024-01-15T10:02:21.1386200Z [build MOD] postprocess
2024-01-15T10:02:23.4051720Z /bin/sh: line 1: 51715 Illegal instruction: 4  ( DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH:+$DYLD_LIBRARY_PATH:}"$I/LibreOffice.app/Contents/Frameworks:$I/LibreOffice.app/Contents/Frameworks" $I/LibreOffice.app/Contents/MacOS/gengal --build-tree --destdir file://$S/extras/source/gallery --name "backgrounds" --path $W/Gallery/backgrounds --filenames file://$RESPONSEFILE -env:UserInstallation=file://$W/Gallery/backgrounds/user ) > $W/Gallery/backgrounds.done.log 2>&1
2024-01-15T10:02:23.5278310Z /bin/sh: line 1: 51720 Illegal instruction: 4  ( DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH:+$DYLD_LIBRARY_PATH:}"$I/LibreOffice.app/Contents/Frameworks:$I/LibreOffice.app/Contents/Frameworks" $I/LibreOffice.app/Contents/MacOS/gengal --build-tree --destdir file://$S/extras/source/gallery --name "sounds" --path $W/Gallery/sounds --filenames file://$RESPONSEFILE -env:UserInstallation=file://$W/Gallery/sounds/user ) > $W/Gallery/sounds.done.log 2>&1
2024-01-15T10:02:23.6706450Z gmake[1]: *** [/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_office_libreoffice/libreoffice/work/libreoffice-7.6.4.1/solenv/gbuild/Gallery.mk:57: /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_office_libreoffice/libreoffice/work/libreoffice-7.6.4.1/workdir/Gallery/backgrounds.done] Error 1
2024-01-15T10:02:23.6819160Z gmake[1]: *** Waiting for unfinished jobs....
2024-01-15T10:02:23.6878530Z gmake[1]: *** [/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_office_libreoffice/libreoffice/work/libreoffice-7.6.4.1/solenv/gbuild/Gallery.mk:57: /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_office_libreoffice/libreoffice/work/libreoffice-7.6.4.1/workdir/Gallery/sounds.done] Error 1
2024-01-15T10:02:24.4332730Z gmake[1]: Leaving directory '/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_office_libreoffice/libreoffice/work/libreoffice-7.6.4.1'
2024-01-15T10:02:24.4673010Z gmake: *** [Makefile:289: build] Error 2
2024-01-15T10:02:24.4870720Z gmake: Leaving directory '/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_office_libreoffice/libreoffice/work/libreoffice-7.6.4.1'
2024-01-15T10:02:24.5324610Z Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_office_libreoffice/libreoffice/work/libreoffice-7.6.4.1" && /opt/local/bin/gmake -j4 -w build 
2024-01-15T10:02:24.5449830Z Exit code: 2
2024-01-15T10:02:24.7076580Z Error: Failed to build libreoffice: command execution failed
```

I don't know why it affects the macOS 13 runner only. The macOS 12 GitHub runner ran though fine on my branch as it did on my MacBook.

Unfortunately, my Mac does not support running macOS 13.
For such a huge port I fear that without access to a native macOS 13 I cannot dig into this error. Debugging this error with GitHub Actions alone would be madness.

Could somebody with a new enough Mac try to build this port on macOS 13 and see if it fails on a native machine, too?

**Comment by pmetzger** [comment]
@reneeotten Thoughts? We should do something about getting this moving forward. The CI error is very odd.

**Comment by Tatsh** [comment]
That error usually means the compiler built the program with instructions not supported by the CPU. This would usually be caused by `-march` or `-mtune` options, possibly by a `-O` flag combined with those.

**Comment by sideeffect42** [comment]
> That error usually means the compiler built the program with instructions not supported by the CPU. This would usually be caused by `-march` or `-mtune` options, possibly by a `-O` flag combined with those.

Do the different `macos-*` builders use a different CPU or how could it only affect `macos-13`?

**Comment by pmetzger** [comment]
Just in case this was literally a cosmic ray or bad memory or something, I've re-run the job.

**Comment by pmetzger** [comment]
Okay, this time one of them built. Did the -13 runner fail the same way?

**Comment by sideeffect42** [comment]
> Okay, this time one of them built. Did the -13 runner fail the same way?

The `macos-11` and `macos-12` runners always succeed if they don't get interrupted by GitHub.
cf. also the runs in my fork: https://github.com/sideeffect42/macports-ports/actions/runs/7521267253

The `macos-13` runner failed in the same mysterious way, again:
```
2024-01-20T17:41:55.3714550Z /bin/sh: line 1: 52510 Illegal instruction: 4  ( DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH:+$DYLD_LIBRARY_PATH:}"$I/LibreOffice.app/Contents/Frameworks:$I/LibreOffice.app/Contents/Frameworks" $I/LibreOffice.app/Contents/MacOS/gengal --build-tree --destdir file://$S/extras/source/gallery --name "sounds" --path $W/Gallery/sounds --filenames file://$RESPONSEFILE -env:UserInstallation=file://$W/Gallery/sounds/user ) > $W/Gallery/sounds.done.log 2>&1
2024-01-20T17:41:55.4727020Z /bin/sh: line 1: 52505 Illegal instruction: 4  ( DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH:+$DYLD_LIBRARY_PATH:}"$I/LibreOffice.app/Contents/Frameworks:$I/LibreOffice.app/Contents/Frameworks" $I/LibreOffice.app/Contents/MacOS/gengal --build-tree --destdir file://$S/extras/source/gallery --name "backgrounds" --path $W/Gallery/backgrounds --filenames file://$RESPONSEFILE -env:UserInstallation=file://$W/Gallery/backgrounds/user ) > $W/Gallery/backgrounds.done.log 2>&1
2024-01-20T17:41:55.6127800Z gmake[1]: *** [/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_office_libreoffice/libreoffice/work/libreoffice-7.6.4.1/solenv/gbuild/Gallery.mk:57: /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_office_libreoffice/libreoffice/work/libreoffice-7.6.4.1/workdir/Gallery/sounds.done] Error 1
2024-01-20T17:41:55.7179000Z gmake[1]: *** Waiting for unfinished jobs....
2024-01-20T17:41:55.7561300Z gmake[1]: *** [/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_office_libreoffice/libreoffice/work/libreoffice-7.6.4.1/solenv/gbuild/Gallery.mk:57: /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_office_libreoffice/libreoffice/work/libreoffice-7.6.4.1/workdir/Gallery/backgrounds.done] Error 1
2024-01-20T17:41:56.9769540Z gmake[1]: Leaving directory '/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_office_libreoffice/libreoffice/work/libreoffice-7.6.4.1'
2024-01-20T17:41:57.4665550Z gmake: *** [Makefile:289: build] Error 2
2024-01-20T17:41:57.6022800Z gmake: Leaving directory '/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_office_libreoffice/libreoffice/work/libreoffice-7.6.4.1'
2024-01-20T17:41:57.6071830Z Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_office_libreoffice/libreoffice/work/libreoffice-7.6.4.1" && /opt/local/bin/gmake -j4 -w build 
2024-01-20T17:41:57.6073730Z Exit code: 2
2024-01-20T17:41:57.7898520Z Error: Failed to build libreoffice: command execution failed
```

Would it be possible to build this PR on MacPorts' buildbot for comparison?

**Comment by pmetzger** [comment]
Not sure how we might manage that. You might ask on the -dev mailing list?

**Comment by sideeffect42** [comment]
The easiest way would be to just merge this PR if the only blocker is the GitHub Actions run on macos-13 and you're okay with the changes as such.

Let's not make this a bigger problem than it is, please. If it builds on MacPorts' buildbot that's all the counts, right?

Given that the current libreoffice port does not compile anymore since ICU 74.2 is in the port tree, what's the worst that could happen? That libreoffice still does not build on macos-13?

**Comment by ryandesign** [comment]
> Fixes [#68938](https://trac.macports.org/ticket/68938).

> * [x]  referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

You haven't referenced that ticket URL in the commit message; please do.

> Do the different `macos-*` builders use a different CPU

It's possible. I don't know what hardware GitHub Actions uses for its runners. I do know that the macOS 13 runner was not available for several months after the release of macOS 13 (and a macOS 14 runner is still not available months after macOS 14's release) and that GitHub had to make changes to its Actions architecture to accommodate macOS 13. Those changes could have included the need to host the new runners on different hardware.

> Okay, this time one of them built. Did the -13 runner fail the same way?

Remember that MacPorts CI infrastructure is set up to cancel all remaining jobs if one fails. So in this run, the macOS 12 build finished first, then the macOS 13 build failed, which cancelled the macOS 11 build that wasn't finished yet. You can rerun on individual runners if you want to see if they build individually.

> Would it be possible to build this PR on MacPorts' buildbot for comparison?

Only by merging the PR.

> If it builds on MacPorts' buildbot that's all the counts, right?

Well no… we also want it to build on users' systems. If we see a problem in CI, it's likely some user who has a similar system will see the problem too.

> Given that the current libreoffice port does not compile anymore since ICU 74.2 is in the port tree, what's the worst that could happen? That libreoffice still does not build on macos-13?

I agree with that. I am not a stickler for requiring things to build in CI before merging. Failing in CI does not mean it will fail everywhere, and conversely succeeding in CI does not guarantee that there are no problems. The MacPorts project got along fine for well over a decade without a CI system. Before that, it was common to commit what you thought worked, check the buildbot, and if it failed there, commit a fix. (MacPorts also got along fine for nearly a decade without the buildbot, relying on users to report problems.)

**Comment by pmetzger** [comment]
Based on @ryandesign's thoughts on this, I am going to merge and request that @sideeffect42 please pay attention to what happens afterwards.

**Pull request merged**
