### PR TITLE
lzma: update to 22.01

### PR DESCRIPTION
**Pull request by judaew**
#### Description

See https://www.7-zip.org/sdk.html

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6 21G115 x86_64
Command Line Tools 14.0.0.0.1.1661618636

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
@judaew In the interest of avoiding potential breakage for users - this port is a dep for highly-used components like Boost - it would be good to validate the build for a few older macOS releases. (At a minimum, 10.6, 10.8, and 10.10, for example.)

Is that something you've done, or can do? I ask, as if you don't have that capability, I'm happy to do so when I update my suite of macOS VMs. (And this port builds so incredibly quickly, that it's a no-brainer to do so.) Happy to do it, let me know!

**Comment by judaew** [comment]
@mascguy I don't have virtual machines for older macOS releases because I haven't free space on my internal and external drives. I would be very grateful if you could check this port for these macOS releases.

**Comment by mascguy** [comment]
> @mascguy I don't have virtual machines for older macOS releases because I haven't free space on my internal and external drives. I would be very grateful if you could check this port for these macOS releases.

You bet, I'll test on my VMs and report back. More to follow.

**Comment by mascguy** [comment]
> You bet, I'll test on my VMs and report back. More to follow.

With the addition of `legacysupport`, builds looks good for 10.6 thru 10.15. (Plus Big Sur and Monterey, per CI.)

**Comment by judaew** [comment]
Thank you so much @mascguy ❤️

**Review by mascguy — APPROVED** [review]

**Pull request merged**
