### PR TITLE
dotnet-7: checksum fix

### PR DESCRIPTION
**Pull request by silverbzez**
#### Description

Closes https://trac.macports.org/ticket/68580

Looks like Microsoft re-released the version while we were working on last PR.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.6.1 22G313 arm64
Command Line Tools 15.0.0.0.1.1694021235

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by tsabirgaliev** [comment]
LGTM, please someone with apple cpu review this or hint how to do it easily on an Intel mac

**Review by tsabirgaliev — APPROVED** [review]

**Comment by silverbzez** [comment]
I'm on an apple silicon mac so these checksums should be correct or they won't pass my `port install`.

> hint how to do it easily on an Intel mac

I'm headache to this as well. What I did is following these guidelines [here](https://guide.macports.org/#installing.macports.source.multiple) to install another macports instance in another location `${prefix}`, and changing `build_arch` flag to `arm64` in `${prefix}/etc/macports/macports.conf`.

Be sure not to change `/opt/local/etc/macports/macports.conf`!!! The config file for your daily-use macports instance, or it will mess things up.

**Comment by ryandesign** [comment]
> hint how to do it easily on an Intel mac

```
sudo port -d checksum dotnet-cli build_arch=arm64
```

**Comment by tsabirgaliev** [comment]
> > hint how to do it easily on an Intel mac
> 
> ```
> sudo port -d checksum dotnet-cli build_arch=arm64
> ```

@ryandesign thank you, this should definitely be part of macports manual or wiki

**Comment by tsabirgaliev** [comment]
Added the 

> > > hint how to do it easily on an Intel mac
> > 
> > 
> > ```
> > sudo port -d checksum dotnet-cli build_arch=arm64
> > ```
> 
> @ryandesign thank you, this should definitely be part of macports manual or wiki

Added the command here: https://trac.macports.org/wiki/FAQ#usingbuildarch

**Comment by judaew** [comment]
Don't forget about `port clean --all` between different variable values.

**Comment by judaew** [comment]
Thank you for the contribution!

**Comment by silverbzez** [comment]
> Don't forget `port clean --all <portname>` when trying a new value of keyword. In this way, you can also override value for the other Portfile's keywords from the command line. This can be very useful.

Thank you for the tip!

**Comment by ryandesign** [comment]
> this should definitely be part of macports manual or wiki

It's a pretty esoteric use case. Only an extremely small percentage of ports vary their distfiles at all and even fewer do so based on `build_arch`. The more generic idea that you can override MacPorts variables at the command line for debugging purposes should be added to the documentation if it is not there already, though it should be stressed that it is for testing and debugging only and not something users are expected to need to do during normal MacPorts use.

> Closes https://trac.macports.org/ticket/68580

Looks like it was forgotten to include this line in any of the commit messages so the ticket did not get auto-closed. I closed it now.

**Pull request merged**
