### PR TITLE
R: new packages (IV)

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

New ports.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
> ```
> Error: Unknown dependency: R-down
> ```

I don't see a PR for this port.

**Comment by barracuda156** [comment]
> > ```
> > Error: Unknown dependency: R-down
> > ```
> 
> I don't see a PR for this port.

Let me check.

**Comment by barracuda156** [comment]
@herbygillot Could we merge this one? CI passed, finally.

PR with updates https://github.com/macports/macports-ports/pull/18447 needs this one to be merged (tests depend on ports from here).

**Comment by herbygillot** [comment]
Oddly enough, Github is complaining about this one - says that it cannot be merged since there are too many changes in this branch.

**Comment by barracuda156** [comment]
> Oddly enough, Github is complaining about this one - says that it cannot be merged since there are too many changes in this branch.

Ok, let me drop a few ports and move them to other PR, no issues.

**Comment by herbygillot** [comment]
I just randomly gave it another shot and it merged cleanly 🤷🏾‍♂️

**Pull request merged**
