### PR TITLE
gtest(patch): Add gtest version to CMakeLists

### PR DESCRIPTION
**Pull request by judaew**
#### Description

See https://trac.macports.org/ticket/67449 (reported by @barracuda156).

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.3.1 22E772610a x86_64
Xcode 14.3 14E222b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by judaew** [comment]
Hi @barracuda156, I would like to invite you to test this patch.

**Comment by barracuda156** [comment]
> Hi @barracuda156, I would like to invite you to test this patch.

@judaew Thank you for dealing with this issue. I will test it once get back to my Mac.

**Comment by ryandesign** [comment]
Please cite the upstream bug report, pull request, or commit related to this issue.

**Comment by judaew** [comment]
Okay, I will wait for the test result from @barracuda156.

**Comment by barracuda156** [comment]
> Okay, I will wait for the test result from @barracuda156.

@judaew Will do today. Sorry, yesterday been away, no Macports on iPhone :)

**Comment by barracuda156** [comment]
@judaew Yes, this seems to work, at least configure was successful (it was failing otherwise).

BTW, could we also build dynamic libs for `gtest`? Either in addition to static or as a variant?

**Comment by judaew** [comment]
@ryandesign The issue appear when we split the subprojects to place the source code for googlemock and googletest in ${prefix}/src. It appears that ArchLinux also applies a patch in such scenarios. In my view, this isn't a problem with gtest itself. Gtest creates the correct files for CMake and pkg-config.

@barracuda156 Gtest can only build static or dynamic libraries. I prefer dynamic libraries, but since the tests with dynamic library are broken, I created a separate shared_libs variant. See https://github.com/google/googletest/issues/3442.

**Comment by barracuda156** [comment]
@judaew Works fine with `s2geometry` (due to how the project is set up, using static libs there would be undesirable), thank you!

**Pull request merged**
