### PR TITLE
python26: [obsolete/deprecated] remove any vestiges of python26

### PR DESCRIPTION
**Pull request by BjarneDMat**
Additional hanges to be committed:
These didn't use PortGrout python 1.0
        modified:   python/py-libdnet/Portfile
        modified:   python/py-orbit/Portfile

Changes to be committed:
	modified:   lang/python26/Portfile               [obsolete/deprecated]
	deleted:    lang/python26/files/*
	modified:   python/py-Pillow/Portfile
	modified:   python/py-bdist_mpkg/Portfile
	modified:   python/py-chardet/Portfile
	modified:   python/py-clnum/Portfile             [obsolete/deprecated]
	modified:   python/py-cython/Portfile
	modified:   python/py-dice3ds/Portfile
	modified:   python/py-docutils/Portfile
	modified:   python/py-gdbm/Portfile
	modified:   python/py-nose/Portfile
	modified:   python/py-numeric/Portfile
	modified:   python/py-numpy/Portfile
	modified:   python/py-olefile/Portfile
	modified:   python/py-opengl-accelerate/Portfile
	modified:   python/py-opengl/Portfile
	modified:   python/py-pil/Portfile
	modified:   python/py-pip/Portfile
	modified:   python/py-psyco/Portfile             [obsolete/deprecated]
	modified:   python/py-pyrex/Portfile
	modified:   python/py-roman/Portfile
	modified:   python/py-rpncalc/Portfile           [obsolete/deprecated]
	modified:   python/py-setuptools/Portfile
	modified:   python/py-tkinter/Portfile
	modified:   python/py-wxpython-2.8/Portfile

If you are still interested in python26 and any of the [obsolete/deprecated] py-{name} , please create a private repository

see: https://macports.mathiesen.info/portfiles/python/pyPorts.txt
     https://macports.mathiesen.info/portfiles/python/modPorts.bash
     https://macports.mathiesen.info/portfiles/python/cpPortfile.bash
     https://macports.mathiesen.info/portfiles/python/pyPortsStats.bash

see the "[portgroups] Python" discussion in "MacPorts Users"

resolves: https://trac.macports.org/ticket/56853

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

### CODE REVIEW

**Comment by pmetzger** [comment]
My only "objection" is this doesn't go far enough. However, that's not a real objection; I think we should do this.

**Comment by cjones051073** [comment]
> My only "objection" is this doesn't go far enough. However, that's not a real objection; I think we should do this.

In what sense ? That we should also obsolete/remove older 3.x releases, or something else ?

Anyway, I am also in agreement with the changes here.

**Comment by pmetzger** [comment]
> In what sense ? That we should also obsolete/remove older 3.x releases

Yes. But we can do that later. (We should also start removing any instances of ports that default to python 2 of course.)

**Comment by BjarneDMat** [comment]
> > In what sense ? That we should also obsolete/remove older 3.x releases
> 
> Yes. But we can do that later. (We should also start removing any instances of ports that default to python 2 of course. And we can also do _that_ later.)

I intend to look at the python3[2-5] issue as the next thing ; but I'll need some feedback from admins of py-{name} ports that doesn't have a py37 version before I take any measures.

**Comment by michaelld** [comment]
I have no issue with exorcise Py26 from MP. IMHO it no longer has a place in any package manager. One could say the same for some Py3 ... but one step at a time.

**Comment by pmetzger** [comment]
> I intend to look at the python3[2-5] issue as the next thing ; but I'll need some feedback from admins of py-{name} ports that doesn't have a py37 version before I take any measures.

I believe 3.5 is still supported (though 3.4 and before is not.)

**Comment by cjones051073** [comment]
> > > In what sense ? That we should also obsolete/remove older 3.x releases
> > 
> > 
> > Yes. But we can do that later. (We should also start removing any instances of ports that default to python 2 of course. And we can also do _that_ later.)
> 
> I intend to look at the python3[2-5] issue as the next thing ; but I'll need some feedback from admins of py-{name} ports that doesn't have a py37 version before I take any measures.

If just adding a py37 version works then I would say we just do it. Many ports without 37 versions are likely just because it wasn’t available when the port was created, and no one has since added it...

**Comment by BjarneDMat** [comment]
> > I intend to look at the python3[2-5] issue as the next thing ; but I'll need some feedback from admins of py-{name} ports that doesn't have a py37 version before I take any measures.
> 
> I believe 3.5 is still supported (though 3.4 and before is not.)

https://www.python.org/dev/peps/pep-0478/ 
It's still suppported ; but there's no lifespan indicated like there's for python3[6-8]

**Comment by BjarneDMat** [comment]
> > I intend to look at the python3[2-5] issue as the next thing ; but I'll need some feedback from admins of py-{name} ports that doesn't have a py37 version before I take any measures.
> 
> If just adding a py37 version works then I would say we just do it. Many ports without 37 versions are likely just because it wasn’t available when the port was created, and no one has since added it...

So you are of the opinon that if py36 exists and py37 is missing, then just add py37 and remove py3[2-4] ?!?

**Comment by cjones051073** [comment]
> > > I intend to look at the python3[2-5] issue as the next thing ; but I'll need some feedback from admins of py-{name} ports that doesn't have a py37 version before I take any measures.
> > 
> > 
> > If just adding a py37 version works then I would say we just do it. Many ports without 37 versions are likely just because it wasn’t available when the port was created, and no one has since added it...
> 
> So you are of the opinon that if py36 exists and py37 is missing, then just add py37 and remove py3[2-4] ?!?

Please keep these two things separate.

If a port does not have 3.7 (or even 3.6) and if it builds fine out the box we should just add them.

Removing, on mass the 3.(2-4) versions is probably a good idea at this point, but this warrants a PR so it can br discussed.

**Comment by BjarneDMat** [comment]
> If a port does not have 3.7 (or even 3.6) and if it builds fine out the box we should just add them.
> 
> Removing, on mass the 3.(2-4) versions is probably a good idea at this point, but this warrants a PR so it can br discussed.

https://trac.macports.org/ticket/59030

**Comment by cjones051073** [comment]
> > If a port does not have 3.7 (or even 3.6) and if it builds fine out the box we should just add them.
> > Removing, on mass the 3.(2-4) versions is probably a good idea at this point, but this warrants a PR so it can br discussed.
> 
> https://trac.macports.org/ticket/59030

With respect, I will be surprised if a ticket like that gets much attention... 

If a port missing 3.6 or 3.7 builds fine with them added, then please just submit a pr for each adding them.

If a port missing them does not support them, then a ticket specific for that port should be opened.

I would suggest an approach like that much more likely to make progress.

**Comment by BjarneDMat** [comment]
the stats are the following : 
`$=> sed -En -e '/ 3[234] /p' pyPorts.txt | wc -l  = 647`
`$=> sed -E -e '/ 35 /d' -e '/ 3. /!d' pyPorts.txt | wc -l = 231`
`$=> sed -E -e '/ 36 /d' -e '/ 3. /!d' pyPorts.txt | wc -l = 102`
`$=> sed -E -e '/ 37 /d' -e '/ 3. /!d' pyPorts.txt | wc -l = 206`

**Comment by cjones051073** [comment]
> the stats are the following :
> `$=> sed -En -e '/ 3[234] /p' pyPorts.txt | wc -l = 647`
> `$=> sed -E -e '/ 35 /d' -e '/ 3. /!d' pyPorts.txt | wc -l = 231`
> `$=> sed -E -e '/ 36 /d' -e '/ 3. /!d' pyPorts.txt | wc -l = 102`
> `$=> sed -E -e '/ 37 /d' -e '/ 3. /!d' pyPorts.txt | wc -l = 206`

Honestly, no idea what to really make of that.

**Comment by jmroot** [comment]
The policy is to not remove EOL pythons but keep them available with an EOL warning on them, along with the corresponding setuptools, pip and virtualenv subports.

Removing py26 from everything else is fine with the permission of the relevant maintainers.

**Comment by BjarneDMat** [comment]
py26-libdnet                    
py26-orbit                      

I missed those two because they don't use the python PortGroup and thus don't have the 'python.versions' setting. They'll have to be handled specially

**Comment by BjarneDMat** [comment]
<pre><code>grass                       26  27  nomaintainer
gwee                        26      nomaintainer
libhsplasma                 26      macports.org:ryandesign
osgswig-devel               26      nomaintainer
PCLauncher           ->
        libhsplasma         26      macports.org:ryandesign
PlasmaClient                26      macports.org:ryandesign
PlasmaShop           ->
        libhsplasma         26      macports.org:ryandesign
playerstage-player          26      nomaintainer
playerstage-stage   ->
        playerstage-player  26      nomaintainer
sitemap_gen                 26      nomaintainer
sounddecompress             26      nomaintainer
sphinx3                     26      nomaintainer
subdownloader               26      nomaintainer
zopeedit                    26      nomaintainer
</code></pre>

**Comment by pmetzger** [comment]
Okay, so I'd like to split this in two.

1. Remove 2.6 from as many things as possible.
2. Remove 2.6

The first can be accomplished incrementally, which is a win.

**Comment by BjarneDMat** [comment]
@pmetzger 
So, for now you'ld like to keep the lang/python26 & just remove the py26 variant where there's a py27 ?

**Comment by pmetzger** [comment]
@BjarneDMat Probably, yah. I'd suggest multiple PRs so that we can remove 2.6 from the ports where it is easy right away, remove it from the rest when we can, and then remove 2.6

**Comment by BjarneDMat** [comment]
@pmetzger 
As far as I can see, the only outstanding problems are the ports @dbevans  found. 1 on those ought to be easy, as it's got both py26 & py27 (I did take a look at the Portfile)

The rest is more-or-less reduced to ´libhsplasma´ & and bunch of "nomaintainer" ; so @ryandesign will have to take a look at those he's maintaining ; & the rest we can divide between us.

**Comment by mojca** [comment]
Removal of py26-wxpython-2.8 requires a bunch of modifications in other ports. In theory you could switch to py27-wxpython-2.8, but that will interfere with py27-wxpython-3.0. My vote would be to remove anything that still requires wxpython-2.8.

https://trac.macports.org/ticket/46351

@Veence: why are we still shipping grass 6? Can we remove it?

**Comment by dbevans** [comment]
> So, for now you'ld like to keep the lang/python26 & just remove the py26 variant where there's a py27 ?

@BjarneDMat
AND you need to add the removed py26 subports to py-graveyard that will mark them as obsolete
replaced by something else. By default, the py26 subport will be replaced by the py27 subport of the same name.

The intent of the 3 part strategy that I suggested was to make sure that you don't inadvertantly break any dependent ports which still need python26 which would be the case if this PR were merged as is. Then removed the py26 ports/subports and mark obsolete and when nothing is left that depends on python26 you can remove it. Just being careful not to cause problems.

**Comment by reneeotten** [comment]
I am in favor of removing all traces of EOL Python versions; I have removed many of these subports last year and the ones remaining now were those where maintainers objected. If the objections have vanished by now that would be great and one can indeed proceed with the removal.

There are three ports left that are only available for Python 2.6 (see [Ticket 56853](https://trac.macports.org/ticket/56853)); @jmroot mentioned there he wants to keep ```py-psyco``` around and also @ryandesign wasn't very enthusiastic last time to remove ```py-clnum``` and ```py-rpncalc```.

I agree with the comments by @dbevans (i.e., how to do this and missing ports) and @jmroot (about leaving the Python ports and the 3 packages intact). There are however more leftover ```python26``` instances, for examples as defined in variants; ideally these should be made obsolete as well. Also, ports like ```postgresql8?``` use ```python26``` for their ```python``` variant and there are a few others like ```pynmr```, ```osgswig-devel``` and ```canto```. Just grep for ```python.default_version 26```, ```python26``` and whether "26" is present on the same line as ```python.versions```. This should be done in all categories, not only in "python".

Again, I am totally in favor of doing this but kind of gave up after my last attempts. As I said back then, ideally there would be a MacPorts policy for what to do with EOL versions of Python. If that were the case these subports could just be removed en-masse without maintainer approval, which is pretty much the only way this exercise can be done.

**Comment by pmetzger** [comment]
FWIW, I don't think we should keep old ports using insecure versions of python even if the maintainers object. I get the whole "don't lose functionality!" thing, but in the end, unsupported and broken is unsupported and broken. If they care enough about those programs they can port them to Python 3.7 or something.

**Comment by BjarneDMat** [comment]
@reneeotten 
> Also, ports like `postgresql8?` use `python26` for their `python` variant 

All of the postgresql8? versions are **also** [obsolete/deprecated] , so they are up for removal too . I wouldn't vorry about them. Personally, I've removed support from them in the variants I've done/revised lately. I could do a PR for that too ;-)

> whether "26" is present on the same line as `python.versions`/`python.default_version 26`.

I ought to have gotten hold of all of those ;-) Please correct me if I'm wrong. What I haven't looked for (yet) are other programs dependent on python26.

I'm in total agreement w/ @pmetzger  regarding "unsupported and broken is unsupported and broken"

> they can port them to Python 3.7 or something

"or something" could be moving them to a private/local repo. One of my scripts (cpPortfile.bash) can easily be modifed to do just that.

**Comment by yan12125** [comment]
> AND you need to add the removed py26 subports to py-graveyard that will mark them as obsolete
replaced by something else.

There is a proposal to drop *-graveyard ports at https://trac.macports.org/ticket/59051.

**Comment by reneeotten** [comment]
@BjarneDMat just to be sure, we are  not disagreeing on most of the things ;) I am just pointing out the "issues" that came up the last time we attempted such exercise. I do not foresee Python 2.7 be removed completely from MacPorts anytime soon, but it's a discussion worth having on the -devel list. Sure it will not be supported by upstream anymore after 2020-01-01, but that doesn't necessarily mean that it is broken.

> I ought to have gotten hold of all of those ;-) Please correct me if I'm wrong. What I haven't looked for (yet) are other programs dependent on `python26`.

To me it seems that your scripts only check the "python" sub-directory of the ports-tree. Indeed, that is where most of the Python ports will reside (i.e., these are Python modules). However, if a package is a utility that happens to be written in Python and not (intended to be) used as a module, it will be in another category and these are the ones that are missing.

**Comment by pmetzger** [comment]
> I do not foresee Python 2.7 be removed completely from MacPorts anytime soon, but it's a discussion worth having on the -devel list. 

I think it's reasonable to

1. Remove all dependencies _within_ MacPorts to 2.7
2. Leave 2.7 in for a couple of years, with considerable warnings for anyone building it.

The important bit, I think, is (1), that is, that other things in MacPorts itself not depend on 2.7. Given that, we can allow consenting adults to build it for themselves from MacPorts, at least for a while.

**Comment by BjarneDMat** [comment]
@reneeotten 
So, I'll have to do something like this : 
<pre>while read -u 9 -a pName
do
    pInfo=$( port info --subports --depends_lib --depends_build ${pName[0]} )
    [[ $(( $( echo "${pInfo}" | fgrep -c 'python26' ) )) -gt 0 ]] && echo ${pName[@]}
done 9< <( port -q list )</pre>
so we're sure to get hold of every port that's somehow dependent on python26

**Comment by BjarneDMat** [comment]
@dbevans  @yan12125 
regarding `py-graveyard` what's the consensus here : 
- remove py-graveyard
- add to it

?

**Comment by yan12125** [comment]
> regarding `py-graveyard` what's the consensus here :

Sorry if I wasn't clear. The proposal I linked is still under consideration, and the current policy has not changed. You can either add removed subports to py-graveyard or put some efforts to make the proposal accepted (e.g., join the discussion and address concerns of removal of py-graveyard) and thus nothing should be done in this PR.

**Comment by mf2k** [comment]
I believe that we can ignore the `py-graveyard` at this point.

**Comment by pmetzger** [comment]
Okay, so what's the next step here? I'd like to see this progressed.

**Comment by mf2k** [comment]
The GitHub conflict with python26 needs to be fixed and @dbevans needs to approve.

**Comment by reneeotten** [comment]
> The GitHub conflict with python26 needs to be fixed and @dbevans needs to approve.

Yes, the ```python26``` port should be taken out of this PR as @jmroot already added an EOL warning to it. Additionally, the ```py-pip``` and ```py-virtualenv``` should stay as mentioned earlier, and the issue/comment by @mojca needs to be addressed. Finally, the respective port maintainers will need to agree.

**Comment by pmetzger** [comment]
Would it improve things if the individual ports were done in separate PRs so that there was much less to approve to move any given PR forward?

**Comment by cjones051073** [comment]
> Would it improve things if the individual ports were done in separate PRs so that there was much less to approve to move any given PR forward?

I would say so, yes.

**Comment by pmetzger** [comment]
@BjarneDMat Could you start submitting the parts of this (changes to individual ports that don't require other changes be in place) one at a time as their own pull requests? That would dramatically improve our ability to get this done.

**Comment by pmetzger** [comment]
@reneeotten What parts of this still remain to be done? I'd like to clear this old PR.

**Comment by reneeotten** [comment]
some variants and a few py26 subports. I’ll get to this eventually or someone else can do it - I would just close this PR.

**Comment by pmetzger** [comment]
@reneeotten Perhaps you could open a new tracking PR for the portions that aren't done, and then close this one?

**Comment by reneeotten** [comment]
> @reneeotten Perhaps you could open a new tracking PR for the portions that aren't done, and then close this one?

For ports that are ```nomaintainer``` I'll commit the changes directly, for others I will for sure open a PR whenever I get to them; or when I am fed up with doing this I'll open a Trac ticket listing the ports that still needs to be addressed. For now I am just closing this one.

**Comment by pmetzger** [comment]
Please do open a Trac ticket anyway; then others may be able to pitch in and help.

**Pull request closed without merging**
