### PR TITLE
hoard: update to 3.13, fix the broken port, support running test

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

The port is outdated now and totally broken: https://ports.macports.org/port/hoard/details
Let’s see if it builds now. With GCC it does and tests run.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

UPD. Looks like all good.

### CODE REVIEW

**Comment by barracuda156** [comment]
@herbygillot May I ask you to merge this one too? Nomaintainer port.

**Review by reneeotten — COMMENTED** [review]
Please separate functional changes from whitespace changes. Additionally, please ask upstream to tag a new release - we ideally don't want to advertise a version but them take include unreleased commits from "master".

**Comment by barracuda156** [comment]
Given that the current port is literally broken across the board, I do not see any point of beautifying something that does not work in a standalone commit :) 

I will make some minor changes to patches though, upon interaction with upstream.

**Comment by barracuda156** [comment]
@reneeotten Dropped a few patches which got merged, even done a pointless separate commit for lint fixes. Hopefully we can merge it now.

**Comment by barracuda156** [comment]
@reneeotten Could we merge this one, please?

**Pull request merged**
