### PR TITLE
gcc9: fix build on SnowLeopard

### PR DESCRIPTION
**Pull request by kencu**
and make libgcc9 the default libgcc for SnowLeoapard

### CODE REVIEW

**Comment by kencu** [comment]
I built it +universal but did not try a 32bit-only build yet. I can run that today.

**Comment by cjones051073** [comment]
@kencu thanks. Note I saw this first when gcc9 was the ‘devel’ version, before updating to be a production release. If you want to test this outside your own machines, you could first try testing things with gcc10 / libgcc-devel. I think you could safely push changes directly there, to test things via the buildbots, without annoying anyone ;)

**Comment by kencu** [comment]
You're right, there is something else to fix when building on i386:
```
/opt/local/bin/clang++-mp-3.4 -arch i386 -std=gnu++98   -g  -DIN_GCC    -fno-strict-aliasing -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings -fno-common  -DHAVE_CONFIG_H  -DGENERATOR_FILE -fno-PIE -L/opt/local/lib -Wl,-headerpad_max_install_names  -o build/genmodes \
	    build/genmodes.o build/errors.o ../build-i386-apple-darwin10/libiberty/libiberty.a
ld: illegal text-relocation to ___stdoutp in /usr/lib/libSystem.dylib from _main in build/genmodes.o for architecture i386
```

**Comment by kencu** [comment]
I believe I have that i386 build issue sorted out. Will be back shortly with a tweak for that.

**Pull request closed without merging**
