### PR TITLE
Newmat: update to v. 11

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update and unuglify the portfile :)

(`lint` complains about a missing license, but I could not find info on it.)

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Clang build fails on:
```
/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_math_newmat/newmat/work/newmat11/newmat6.cpp:431:13: error: ordered comparison between pointer and zero ('int *' and 'int')
     if (indx > 0) { delete [] indx; indx = 0; }
         ~~~~ ^ ~
  1 error generated.
```

**Comment by herbygillot** [comment]
Every port should have a `license` field.  This one may have to be marked as `Restrictive`.

Ref: https://trac.macports.org/wiki/PortfileRecipes#licensekeyword

**Comment by barracuda156** [comment]
> Every port should have a `license` field. This one may have to be marked as `Restrictive`.
> 
> Ref: https://trac.macports.org/wiki/PortfileRecipes#licensekeyword

Thanks, added.
(Skipped CI, since no other changes in this commit.)

**Comment by herbygillot** [comment]
Thanks @barracuda156

**Pull request merged**
