### PR TITLE
py-httpx: added missed dependencies and select port

### PR DESCRIPTION
**Pull request by catap**
#### Description

httpx can be used as CLI utils which requires optional dependencies, and to make
live easy I've also added a brand new select port.

###### Type(s)

- [x] enhancement

###### Tested on

macOS 12.6 21G115 x86_64
Xcode 14.0.1 14A400

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
@mascguy, @reneeotten may I ask to review this port? A real user asked me directly to fix it :)

**Comment by catap** [comment]
@pmetzger may I ask you to review this one?

**Comment by reneeotten** [comment]
> @mascguy, @reneeotten may I ask to review this port? A real user asked me directly to fix it :)

these changes look okay with regards to the `select` part; I guess the only question is whether the `cli` part should be added as a variant or always installed?

**Comment by catap** [comment]
@reneeotten well... right now port installs cli part, but it simple doesn't work because required dependecies are missed.

If some other port enforced dependencies, the cli part works.

=> I feel that avoid variants is good idea. Plus I not fan of variant concept at all.

**Pull request merged**
