### PR TITLE
clang-11-bootstrap: fix build on macOS 10.9

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.9.5 13F1911 x86_64
Xcode 6.2 6C131e

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
@kencu / @mascguy may I ask you to merge this hotfix? Thanks.

**Review by mascguy — APPROVED** [review]
You bet, thanks for the quick fix!

**Comment by catap** [comment]
@mascguy thanks, I hope that now I have a green panel on this port and may move forward with https://github.com/macports/macports-ports/pull/13995 and https://github.com/macports/macports-ports/pull/13986 ;)

**Comment by Gcenx** [comment]
After both of those get merged/built it would be nice to circular back around to this and have the port copy in libgcc so anyone installing the prebuilt package won’t also need to install gcc10-bootstrap.

I’ve found clang-11-bootstrap rather useful just the current requirement of gcc10-bootstrap as a runtime dep is off putting.

**Comment by catap** [comment]
@Gcenx because all this ports is kind of bootstrap and should be used only to build the real toolchain... well.. I haven't see any benefit to do it :)

**Comment by Gcenx** [comment]
@catap I’ve been using it to bootstrap/breaks some dependency cycles. I was hoping to not always need to carry a custom version but maybe that will be the case.

I still believe these bootstrap changes are a great addition!

**Comment by catap** [comment]
> @catap I’ve been using it to bootstrap/breaks some dependency cycles. I was hoping to not always need to carry a custom version but maybe that will be the case.

**Comment by kencu** [comment]
next will be to see if we can go from system roots right to libtapi + ld64-latest in one step on 10.6 through 10.13, skipping right over all the ld64 manual bootstrapping hassles.

**Comment by catap** [comment]
@kencu maybe you know a way to see a build dependency tree for a port?

**Comment by Gcenx** [comment]
> next will be to see if we can go from system roots right to libtapi + ld64-latest in one step on 10.6 through 10.13, skipping right over all the ld64 manual bootstrapping hassles.

I’ve only done this for 10.9, 10.14 and 11 but it’s possible just a little long winded due to the constant gcc10-bootstrap requirement even for systems that could easily build clang-11-bootstrap directly.

**Comment by catap** [comment]
@kencu / @Gcenx I plan to try to simplify building of `cctools` via `clang-11-boostrap` and `libcxx` when it requries which should broke a lot of dependencies.

**Comment by kencu** [comment]
cctools is pretty easy… just simple c code, IIRC, never had any trouble there.

ld64 is the headache.

**Comment by catap** [comment]
@kencu yeah, but a few step is required before move on ;)

**Comment by Gcenx** [comment]
@kencu are you actually referring to the actual latest version of cctools or the latest on Macports?

ld64 609 will build against clang-11-bootstrap just fine

**Comment by kencu** [comment]
to find all the recursive deps I believe it is 

port -rdeps cctools

from memory. BUT it is not very accurate, I’m afraid, for various reasons, esp “bin” deps and similar. These totally mess you up trying to get accurate deps.

**Comment by kencu** [comment]
> @kencu are you actually referring to the actual latest version of cctools or the latest on Macports?
> 
> ld64 609 will build against clang-11-bootstrap just fine

cctools is (was ) easy, all versions I updated. However, they stopped testing ppc and i386 and those have bitrotted pretty badly, and I had to fix several errors there. So be careful if you try to update cctools for that reason.

ld64 (all newer versions) are much harder to build. If clang11 can build ld64-609 using the system ld64 on 10.6 as a bootstrap that would make things much easier indeed.

**Comment by Gcenx** [comment]
I’ve been using cctools 973.0.1 and ld64 609 for months without issue (outside of my own dumb mistake on an ld64 patch lol)

i386 binaries launched correctly unlike with the stock Xcode11 cctools that produced broken i386 binaries (as)

**Pull request merged**
