### PR TITLE
maxima: update to 5.46.0

### PR DESCRIPTION
**Pull request by someuser12**
#### Description

Update maxima to 5.46.0.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.15.7 19H2026 x86_64
Xcode 12.4 12D4e

macOS 10.13.6 17G14042 x86_64
Xcode 9.1 9B55

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by someuser12** [comment]
Building the doc of `maxima-devel` fails. However, `maxima-devel`'s version seems to be older than the version of `maxima` in the current portfile (before update): 5.43 vs. 5.45.1. Is `maxima-devel` still useful? Should it be updated?

**Comment by catap** [comment]
@someuser12 I think so.

**Comment by catap** [comment]
@someuser12 I suggest to update maxima-devel also. I've just tried:
```diff
diff --git a/math/maxima/Portfile b/math/maxima/Portfile
index 1ee3d913ab5..621dd5d4bec 100644
--- a/math/maxima/Portfile
+++ b/math/maxima/Portfile
@@ -35,14 +35,14 @@ depends_run     port:rlwrap \
 subport maxima-devel {
     conflicts   maxima
 
-    # git describe --tags : branch-5_43-base-278-gd806e84c7
+    # git describe --tags : branch-5_46-base-480-g5b42cccfd
     # Date:  Sun Jan 26 20:10:05 2020 -0800
     # commit 8b2da334e1f6c6b56d90cf3e00c2d67274fa6550
-    version     5.43-dev-20200126
-    revision    28
+    version     5.46-dev-20221029
+    revision    0
     fetch.type  git
     git.url     https://git.code.sf.net/p/maxima/code
-    git.branch  d806e84c719a9fcf023f8829535f593ce9bb7d0c
+    git.branch  5b42cccfd9eee54d0458d8f4e63e6b44c55d48a1
 
     use_autoreconf  yes
```

and it works very well.

Thus, you may also remove `revision 0` because it is default value ;)

**Comment by catap** [comment]
BTW I've pushed my commit here: https://github.com/catap/macports-ports/tree/maxima

Feel free to use it or squash into your PR.

**Review by catap — APPROVED** [review]
I've tested it and it works on:

macOS 12.6 21G115 x86_64
Xcode 14.0.1 14A400

**Comment by someuser12** [comment]
Thanks @catap for your comment. I also updated `maxima-devel`. I left `revision 0` because of the advice of the Macports guide (https://guide.macports.org/#reference.keywords): ``It is recommended to set the revision in all ports, even if the revision is 0''.

**Pull request merged**
