### PR TITLE
xorg-xcb-proto: install xcbgen to the canonical path

### PR DESCRIPTION
**Pull request by yan12125**
#### Description

Closes: https://trac.macports.org/ticket/57329

/cc @larryv: I'm not sure if I should revbump libtool for a patch towards automake. Could you give an advice?

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.4 18E226
Xcode 10.2 10E125

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
     * xorg-libxcb still builds fine

### CODE REVIEW

**Comment by cjones051073** [comment]
Did you conclude on if you need to revbump libtool ?

**Comment by yan12125** [comment]
> Did you conclude on if you need to revbump libtool ?

Sorry, I don't quite understand how mismatched versions between automake and libtool break stuffs, so I hope to hear a comment from @larryv.

I can also revbump libtool anyway. If it's an unnecessary revbump, users only waste less than a minute on rebuilding it.

**Comment by yan12125** [comment]
@macportsbot retry

**Comment by cjones051073** [comment]
Looks ok to me. I suggest you just merge this when ready, as I do not anticipate hearing from @larryv

**Comment by yan12125** [comment]
Thanks for checking and the advice. This PR has passed maintainer timeout, too.

**Pull request merged**
