### PR TITLE
devel/cmake: trivial update to 3.19.1

### PR DESCRIPTION
**Pull request by adfernandes**

### CODE REVIEW

**Comment by kencu** [comment]
I've been waiting for this one. I think this one uses the system libuv even for the bootstrap cmake, so we can (hopefully) delete a bunch of patches with this update for older systems.

**Comment by adfernandes** [comment]
I'll let @michaelld do the merge since he's the port maintainer.

**Comment by kencu** [comment]
Oh, you need not worry, I certainly wasn't planning to merge it for you. Michael has to run tests on all the systems first, as this is significant new version.

But after that is all done, and he gets around to merging it, I will hopefully be able to dump some the patches I've written and added to this port.

**Comment by adfernandes** [comment]
Oh sorry - I was typing too quickly and miscommunicated!

I wasn't sure what you meant, but now I understand.

Yes, definitely, the fewer patches required, the better!

**Review by michaelld — APPROVED** [review]
LGTM ; thx!

**Pull request merged**
