### PR TITLE
ffmpeg7: update to 7.0.2; ffmpeg-devel: switch to branch 7.x

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

1. `ffmpef7`: simple update
2. `ffmpeg-devel`: track current version instead of an archaic 4.x.
3. Adjust conflicts.

I am not patching all dependents of `ffmpeg` (to change path-style to `port:ffmpeg`), since that will have to be done with skipping CI. Will do it in a follow up PR.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@mascguy Are there any objections re switching `ffmpeg-devel` to v. 7? If yes, I can drop this part.

**Comment by barracuda156** [comment]
@mascguy @pmetzger @reneeotten Bump

**Comment by pmetzger** [comment]
It's too many files for me to review at the moment; I've got very little time right now.

**Comment by barracuda156** [comment]
> It's too many files for me to review at the moment; I've got very little time right now. Someone else will have to look it over.

@reneeotten @herbygillot Could someone merge this? This is completely trivial: update micro to ffmpeg7 and a switch of ffmpeg-devel from archaic 4 to 7. (Should have been done long back.)

**Comment by mohd-akram** [comment]
ffmpeg-devel shouldn't install in a prefix and should conflict with ffmpeg not ffmpeg7.

**Comment by barracuda156** [comment]
> and should conflict with ffmpeg not ffmpeg7

Why?

**Comment by mohd-akram** [comment]
Because that would help with testing upgrading ffmpeg to version 7. Right now I'm not sure what's the benefit of the way it is currently.

**Comment by barracuda156** [comment]
@mohd-akram I do not think it will ever be a drop-in replacement, since no one gonna bother, realistically, fixing apps which are no longer maintained by their upstreams, and I was thinking of `ffmpeg-devel` as kinda tracking upstream and a bit ahead of the latest release of ffmpeg (which is currently 7). But please, you may adjust it as better suits your needs, no objections here. If anyone cares about my approval, I will approve your PR.

**Comment by mascguy** [comment]
> Because that would help with testing upgrading ffmpeg to version 7. Right now I'm not sure what's the benefit of the way it is currently.

The various ports are segregated because there were some breaking API changes included in v5 and up. And given the number of dependents, there was simply no way to feasibly update it.

Those ports that can truly benefit from a newer ffmpeg, can be updated to use 6 or 7. And the some have been.

**Comment by mohd-akram** [comment]
> The various ports are segregated because there were some breaking API changes included in v5 and up. And given the number of dependents, there was simply no way to feasibly update it.

Agreed. I created a new ffmpeg4 port, which maybe we can start moving the ports that are guaranteed not to work with newer ffmpeg (which can be easily tested once #27136 is merged). Then, perhaps the ffmpeg port can be like the boost port, which I think you mentioned before, carrying the latest version for use by regular users.

**Comment by barracuda156** [comment]
> Agreed. I created a new ffmpeg4 port, which maybe we can start moving the ports that are guaranteed not to work with newer ffmpeg (which can be easily tested once #27136 is merged). Then, perhaps the ffmpeg port can be like the boost port, which I think you mentioned before, carrying the latest version for use by regular users.

Off topic really, but boost wrapper port does not do that, and in fact does more damage than good.

**Comment by mohd-akram** [comment]
What do you mean? The boost port just symlinks to the actual port, right? That's what I meant.

**Comment by barracuda156** [comment]
> What do you mean? The boost port just symlinks to the actual port, right? That's what I meant.

It does not wrap the latest version of boost.

**Comment by mohd-akram** [comment]
Is there any reason it doesn't? Or just no one bothered updating it?

**Comment by mascguy** [comment]
> Is there any reason it doesn't? Or just no one bothered updating it?

The older version is the most compatible, which is why it's the way it is.

Let's not change how that works please...

**Comment by mohd-akram** [comment]
I don't know enough about Boost to comment, but generally speaking if dependents themselves use the siloed versions, which compatibility are we preserving?

**Comment by mascguy** [comment]
> I don't know enough about Boost to comment, but generally speaking if dependents themselves use the siloed versions, which compatibility are we preserving?

Can we defer the boost topic for now?

**Comment by mohd-akram** [comment]
Sure thing.

**Comment by barracuda156** [comment]
> Let's not change how that works please...

No worries, while I reported that a wrapper ports creates problems, I am not going to interfere with that.

**Pull request merged**
