### PR TITLE
py-luma.emulator: add py313 subport (including dependencies)

### PR DESCRIPTION
**Pull request by markmentovai**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 15.1 24B83 arm64
Xcode 16.1 16B40

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by jmroot** [comment]
Could you please back out the changes to py-game that aren't related to adding 3.13 support? If the change to the patch for Pillow is needed to support 3.13, a brief comment explaining that would be nice. Otherwise it probably belongs in a separate PR?

**Comment by reneeotten** [comment]
there is already an open PR with updates/fixes to “py-numpy” that include the addition if the py313 subport for NumPy and all dependents. There is a bit more testing needed there, but I suspect it will be merged in the next few days. So no need to duplicate that part here.

**Comment by markmentovai** [comment]
@jmroot https://github.com/macports/macports-ports/pull/26424#issuecomment-2455755668:
> Could you please back out the changes to py-game that aren't related to adding 3.13 support?

I backed it out at your request, but it reintroduces a `port lint --nitpick` warning:

```
--->  Verifying Portfile for py313-game
Warning: missing recommended checksum type: size
--->  0 errors and 1 warnings found.
```

> If the change to the patch for Pillow is needed to support 3.13, a brief comment explaining that would be nice. Otherwise it probably belongs in a separate PR?

It’s a backport of https://github.com/python-pillow/Pillow/commit/57399ce204d79c74c80612c622bb788e20d786e8 from Pillow 10.4.0 necessary for Python 3.13 compatibility. I had proper attribution at one point, and then lost it when I saw there was already a patch to `setup.py` and decided to just add this simple patch to that. I’ve noted this in the commit message now.

@reneeotten https://github.com/macports/macports-ports/pull/26424#issuecomment-2456029018:
> there is already an open PR with updates/fixes to “py-numpy” that include the addition if the py313 subport for NumPy and all dependents. There is a bit more testing needed there, but I suspect it will be merged in the next few days. So no need to duplicate that part here.

OK, this is now dependent on https://github.com/macports/macports-ports/pull/26408, and I’ll mark it a draft until that lands as this work isn’t fully usable without py313-numpy.

**Comment by reneeotten** [comment]
@markmentovai can you rebase this with "master" please?

**Comment by markmentovai** [comment]
@reneeotten https://github.com/macports/macports-ports/pull/26424#issuecomment-2460615906:
> @markmentovai can you rebase this with "master" please?

Done.

**Comment by markmentovai** [comment]
At https://github.com/macports/macports-ports/commit/9496c79c00f3ceaed46e20b1502a2d0e75283747, there are [CI failures on macOS 13](https://github.com/macports/macports-ports/actions/runs/11711607708/job/32620482157?pr=26424), but not [14](https://github.com/macports/macports-ports/actions/runs/11711607708/job/32620481580?pr=26424) or [15](https://github.com/macports/macports-ports/actions/runs/11711607708/job/32620481873?pr=26424). The failures are all in installing dependencies, and in particular, `py*-numpy+accelerate+gfortran`, but only on macOS 13.

[macOS 13 artifacts](https://github.com/macports/macports-ports/actions/runs/11711607708/artifacts/2154646262), from (for example) `py313-game/logs/install-dependencies.log`:

```
--->  Building py313-numpy
[…]
Executing:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-numpy/py313-numpy/work/numpy-1.26.4" && /opt/local/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13 -m build --no-isolation --wheel --outdir /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-numpy/py313-numpy/work -Csetup-args=-Dallow-noblas=false -Csetup-args=-Dblas=accelerate -Csetup-args=-Dlapack=accelerate 
DEBUG: system:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-numpy/py313-numpy/work/numpy-1.26.4" && /opt/local/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13 -m build --no-isolation --wheel --outdir /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-numpy/py313-numpy/work -Csetup-args=-Dallow-noblas=false -Csetup-args=-Dblas=accelerate -Csetup-args=-Dlapack=accelerate 
* Getting build dependencies for wheel...
* Building wheel...
+ /opt/local/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13 /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-numpy/py313-numpy/work/numpy-1.26.4/vendored-meson/meson/meson.py setup /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-numpy/py313-numpy/work/numpy-1.26.4 /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-numpy/py313-numpy/work/numpy-1.26.4/.mesonpy-ef7fktxh -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dallow-noblas=false -Dblas=accelerate -Dlapack=accelerate --native-file=/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-numpy/py313-numpy/work/numpy-1.26.4/.mesonpy-ef7fktxh/meson-python-native-file.ini
The Meson build system
[…]
Message: 
CPU Optimization Options
  baseline:
    Requested : min
    Enabled   : SSE SSE2 SSE3
  dispatch:
    Requested : max -xop -fma4
    Enabled   : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL

Library m found: YES
Run-time dependency accelerate found: NO (tried system)

../numpy/meson.build:174:4: ERROR: Problem encountered: No BLAS library detected! Install one, or use the `allow-noblas` build option (note, this may be up to 100x slower for some linear algebra operations).

A full log can be found at /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-numpy/py313-numpy/work/numpy-1.26.4/.mesonpy-ef7fktxh/meson-logs/meson-log.txt

ERROR Backend subprocess exited when trying to invoke build_wheel
Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-numpy/py313-numpy/work/numpy-1.26.4" && /opt/local/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13 -m build --no-isolation --wheel --outdir /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_python_py-numpy/py313-numpy/work -Csetup-args=-Dallow-noblas=false -Csetup-args=-Dblas=accelerate -Csetup-args=-Dlapack=accelerate 
Exit code: 1
Error: Failed to build py313-numpy: command execution failed
```

As of b9b76200f491b248f4ff0461bc325db3c2b984f1 (earlier today, #26408), `py-numpy` has `+accelerate` as a default variant on macOS ≥ 13.3 ([here](https://github.com/macports/macports-ports/blob/95a68617b8d38bc1357c9ed38b9bc51feafaa64f/python/py-numpy/Portfile#L125)). This builder is running macOS 13.7 22H123, so `+accelerate` is expected. That much appears to be working correctly.

This may be because `MACOSX_DEPLOYMENT_TARGET` is set to `13.0`? There’s an awful lot of stuff in Accelerate.framework that declares itself available starting in 13.3.

Regardless, the CI failures aren’t attributable to anything in this pull request.

**Comment by markmentovai** [comment]
@reneeotten https://github.com/macports/macports-ports/pull/26424#issuecomment-2462387089:
> @markmentovai Yep, I noticed that as well. I think the Portfile logic is correct, hut something is amiss in NumPy's detection step; indeed likely caused by the deployment target. I'll take a look; and agree it has nothing to do with this PR. Let me see if I can fix it and then I'll merge this.

Yes, the problem is indeed the deployment target.

[numpy/numpy v1.26.4 vendored-meson](https://github.com/numpy/numpy/tree/v1.26.4/vendored-meson) → [numpy/meson 4e370ca8ab73](https://github.com/numpy/meson/tree/4e370ca8ab73c07f7b84abe8a4b937caace050a4) → [mesonbuild/dependencies/blas_lapack.py:744 AccelerateSystemDependency.check_macOS_recent_enough](https://github.com/numpy/meson/blob/0d93515fb826440d19707eee47fd92655fe2f166/mesonbuild/dependencies/blas_lapack.py#L744):

```py
    def check_macOS_recent_enough(self) -> bool:
        macos_version = platform.mac_ver()[0]
        deploy_target = os.environ.get('MACOSX_DEPLOYMENT_TARGET', macos_version)
        if not mesonlib.version_compare(deploy_target, '>=13.3'):
            return False
```

That snippet is new in https://github.com/numpy/meson/commit/dd86df3b964e5ae960cf71b8ba1d2a7474f85d67 (https://github.com/numpy/meson/pull/6, https://github.com/numpy/numpy/issues/25026, 2023-10-31), later revised in https://github.com/numpy/meson/commit/d80dadbfa45fe1bbab72a24d5e7e97828129e16f (https://github.com/numpy/meson/pull/9, https://github.com/numpy/numpy/issues/25406, 2023-12-22). I’ve confirmed that reverting locally allows `py313-numpy +accelerate+gfortran` to build successfully on macOS 13.6 22G120 arm64 with Command Line Tools 14.3.1.0.1.1683849156 and SDK 13.3 22E245.

The check above can’t succeed when `MACOSX_DEPLOYMENT_TARGET` is set to `13.0` as it on macOS 13-point-anything by default ([macports-base src/macports1.0/macports.tcl](https://github.com/macports/macports-base/blob/v2.10.4/src/macports1.0/macports.tcl#L1604)).

Perhaps py-numpy should consider the deployment target instead of `os.major` and `os.minor` to decide whether or not to use `+accelerate` by default. It does seem wrong to mix `+accelerate` with `MACOSX_DEPLOYMENT_TARGET` < `13.3`.

**Comment by reneeotten** [comment]
Yes, and thus the NumPy check is wrong at least in the context of MacPorts. Should be fixed in bf8714202384c109e20664a710a1c3905b90737d

**Comment by markmentovai** [comment]
Yeah, I agree that would work.

**Comment by markmentovai** [comment]
This now passes checks on macOS 13. Thanks!

**Pull request merged**
