### PR TITLE
openldap: update to 2.6.8

### PR DESCRIPTION
**Pull request by artkiver**
###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.5 23F79 arm64
Xcode 15.3 15E204a

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by artkiver** [comment]
When I ran port test, it had trouble finding the lmdb 0.9.33 tarball:

```
port test        
--->  Fetching archive for lmdb
--->  Attempting to fetch lmdb-0.9.33_0.darwin_23.arm64.tbz2 from http://mirror.fcix.net/macports/packages/lmdb
--->  Attempting to fetch lmdb-0.9.33_0.darwin_23.arm64.tbz2 from https://packages.macports.org/lmdb
--->  Attempting to fetch lmdb-0.9.33_0.darwin_23.arm64.tbz2 from https://ywg.ca.packages.macports.org/mirror/macports/packages/lmdb
--->  Fetching distfiles for lmdb
--->  Attempting to fetch lmdb-0.9.33.tar.gz from http://mirror.fcix.net/macports/distfiles/lmdb
--->  Attempting to fetch lmdb-0.9.33.tar.gz from https://distfiles.macports.org/lmdb
--->  Attempting to fetch lmdb-0.9.33.tar.gz from https://github.com/LMDB/lmdb/archive/LMDB_0.9.33
--->  Attempting to fetch lmdb-0.9.33.tar.gz from https://ywg.ca.distfiles.macports.org/mirror/macports/distfiles/lmdb
--->  Attempting to fetch lmdb-0.9.33.tar.gz from http://ykf.ca.distfiles.macports.org/MacPorts/mpdistfiles/lmdb
--->  Attempting to fetch lmdb-0.9.33.tar.gz from https://kmq.jp.distfiles.macports.org/lmdb
--->  Attempting to fetch lmdb-0.9.33.tar.gz from https://mse.uk.distfiles.macports.org/lmdb
--->  Attempting to fetch lmdb-0.9.33.tar.gz from https://cph.dk.distfiles.macports.org/lmdb
--->  Attempting to fetch lmdb-0.9.33.tar.gz from https://fra.de.distfiles.macports.org/lmdb
--->  Attempting to fetch lmdb-0.9.33.tar.gz from http://cjj.kr.distfiles.macports.org/lmdb
--->  Attempting to fetch lmdb-0.9.33.tar.gz from https://nue.de.distfiles.macports.org/lmdb
--->  Attempting to fetch lmdb-0.9.33.tar.gz from http://fco.it.distfiles.macports.org/lmdb
--->  Attempting to fetch lmdb-0.9.33.tar.gz from http://jog.id.distfiles.macports.org/macports/distfiles/lmdb
--->  Attempting to fetch lmdb-0.9.33.tar.gz from https://pek.cn.distfiles.macports.org/macports/distfiles/lmdb
--->  Attempting to fetch lmdb-0.9.33.tar.gz from https://jnb.za.distfiles.macports.org/distfiles/lmdb
--->  Attempting to fetch lmdb-0.9.33.tar.gz from http://aarnet.au.distfiles.macports.org/pub/macports/distfiles/lmdb
--->  Attempting to fetch lmdb-0.9.33.tar.gz from http://atl.us.distfiles.macports.org/lmdb
Error: Failed to fetch lmdb: The requested URL returned error: 403
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_databases_lmdb/lmdb/main.log for details.
Error: Unable to execute port openldap: upgrade cyrus-sasl2 failed
```
I also tried updating the Portfile for /databases/lmdb to 0.9.33 as well, but it seems to be overly reliant on GitHub maybe?

I had no issues grabbing the tarball from upstream here:
https://git.openldap.org/openldap/openldap/-/tags

(Including hashes of my download as a sanity check just in case something is wonky on my end)

```
% openssl dgst -rmd160 openldap-LMDB_0.9.33.tar.gz
RIPEMD160(openldap-LMDB_0.9.33.tar.gz)= 0055f3855dba392aa4f2aef57de7f4b16d454fbe
% openssl dgst -sha256 openldap-LMDB_0.9.33.tar.gz
SHA256(openldap-LMDB_0.9.33.tar.gz)= 476801f5239c88c7de61c3390502a5d13965ecedef80105b5fb0fcb8373d1e53
% ls -alF openldap-LMDB_0.9.33.tar.gz
-rw-r--r--@ 1 grey  staff  149281 May 22 02:14 openldap-LMDB_0.9.33.tar.gz
```

Anyway, since databases/lmdb has no port maintainer, but openldap has @mascguy  I figured it might be better to offer a PR to this rather than overhaul the lmdb Portfile to source tarballs closer to upstream?

Also, I haven't tested any of the variants and am not a heavy OpenLDAP user at the moment, so I figured it better to err on the side of simplicity and caution rather than over commit myself when more experienced devs may already be on the ball.

**Comment by mascguy** [comment]
Can you update `openldap-devel` instead? Normally that's updated first, to ensure the new version builds (and works) everywhere.

**Comment by artkiver** [comment]
> Can you update `openldap-devel` instead? Normally that's updated first, to ensure the new version builds (and works) everywhere.

Sure thing!

Also, to clarify:

I think the reason %sudo port test failed locally, was because I had modified my databases/lmdb/Portfile to attempt to reference the 0.9.33 LMDB release which coincided with the OpenLDAP 2.6.8 release.

I reverted my databases/lmdb/Portfile to the previous version (0.9.31) and %sudo port test seemed to be running without any immediately identifiable issues.

Seems as if it's probably still wise to update LMDB's Portfile for 0.9.33, but I'll continue working on openldap-devel for the time being.

Thanks for chiming in @mascguy!

**Comment by artkiver** [comment]
openldap-devel PR as requested is here:
https://github.com/macports/macports-ports/pull/24061

**Pull request closed without merging**
