### PR TITLE
openexr: Update Portfile description

### PR DESCRIPTION
**Pull request by cary-ilm**
Use the modern one-line description from the OpenEXR project repo/website https://github.com/AcademySoftwareFoundation/openexr.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 12.6.7 21G651 arm64
Command Line Tools 14.2.0.0.1.1668646533

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by herbygillot** [comment]
Thanks for this submission, but the commit description is format as per MacPorts preferred policy.

Format is usually: `<portname>: <change description>`

So the description for your commit should look like `openexr: update description`.

Please update your commit description.

**Comment by cary-ilm** [comment]
Done, thanks.

**Comment by herbygillot** [comment]
Please squash the most recent change back into the same original commit, and we should be good to go.

**Comment by ryandesign** [comment]
> Please squash the most recent change back into the same original commit, and we should be good to go.

We can fix that ourselves with the "Squash and merge" button.

**Comment by cary-ilm** [comment]
I  squashed them myself, thanks.

**Pull request merged**
