### PR TITLE
tunnelblick: Submission [WIP]

### PR DESCRIPTION
**Pull request by essandess**
tunnelblick: Submission [WIP]

* Currently not building
* See: https://github.com/Tunnelblick/Tunnelblick/issues/592
* Related: https://github.com/Tunnelblick/Tunnelblick/issues/530

@jkbullard Please the build bot logs error logs below.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jkbullard** [comment]
@essandess - What's the build environment? Does "Build mac-10.13" mean it's building on macOS 10.13? See my comment at [Tunnelblick Issue 592](https://github.com/Tunnelblick/Tunnelblick/issues/592).

**Comment by essandess** [comment]
> @essandess - What's the build environment? Does "Build mac-10.13" mean it's building on macOS 10.13? See my comment at [Tunnelblick Issue 592](https://github.com/Tunnelblick/Tunnelblick/issues/592).

This is on macOS 10.14 and Xcode 11.0.0.

Let’s take the discussion to your page, https://github.com/Tunnelblick/Tunnelblick/issues/592, unless there’s some MacPorts-specific thing to bring in.

**Comment by essandess** [comment]
Also, note that MacPorts tries to build across multiple platforms, all the way back to 10.5 ppc (!). But let’s just focus on supported OS’s for now.

**Comment by ryandesign** [comment]
Since Sparkle is used for automatic updates, we would actually want to disable Sparkle in the MacPorts build.

**Comment by essandess** [comment]
> Since Sparkle is used for automatic updates, we would actually want to disable Sparkle in the MacPorts build.

@jkbullard How do we disable Sparkle in the build? Flag somewhere?

**Comment by jkbullard** [comment]
@essandess - Tunnelblick doesn't have any build-time options.

**Comment by ryandesign** [comment]
As maintainer of the port it would be up to you to figure out how to do that. If there are no build options to disable it, you may have to patch the build system.

**Comment by lhaeger** [comment]
https://sparkle-project.org/documentation/customization/ may give some hints.

**Comment by jkbullard** [comment]
@lhaeger, I think @essandess's idea is to skip building Sparkle to avoid the error(s) that occur when building the older version of Sparkle which is used in Tunnelblick. That would require a change to the Tunnelblick build system and changes to Tunnelblick itself and I'm not sure how practical it would be. (Among other things, I don't know how to conditionally include the Sparkle framework into Tunnelblick, or if that can even be done.)

It would also mean that Tunnelblick's original method of updating configurations would no longer work (because it uses Sparkle). Tunnelblick's newer, simpler configuration updating system would be fine; it doesn't use Sparkle.

I think a better approach would be to:
 1. Figure out how to get the old version of Sparkle to build with  newer versions of Xcode;<br>and/or
 2. Update the version of Sparkle included in Tunnelblick.

**Comment by essandess** [comment]
@jkbullard @lhaeger I believe reasonable goals for a MacPorts-based build of Tunnelblick are:
* An independently built and managed Tunnelblick app
* Use latest macOS and Xcode versions in the build
* Use MacPorts for version management/updating/distribution
* Use MacPorts's automated `xcodebuild` system in the Portfile

Also possibly if it's not too much extra work:
* Use the [openvpn2](https://github.com/macports/macports-ports/blob/master/net/openvpn2/Portfile) port as a dependency

If we can get a Tunnelblick build on the latest supported macOS and Xcode, then most of these goals come for free. I'm not personally familiar enough with either Xcode projects or Tunnelblick to have a crack at migrating the current project to the latest Xcode.

**Comment by jkbullard** [comment]
@essandess @lhaeger Tunnelblick includes multiple versions of OpenVPN and static-links each to two versions of OpenSSL and/or LibreSSL, so I'm not sure how a macports build could use the [openvpn2](https://github.com/macports/macports-ports/blob/master/net/openvpn2/Portfile) port as a dependency.

**Comment by essandess** [comment]
@jkbullard That’s fine. It’s more robust to just build it the way the repo says it should be built.

**Comment by essandess** [comment]
@jkbullard I looked into the Tunnelblick build on macOS 10.15 and Xcode 11. I see two major issues:
1. The Tunnelblick build throws several errors
2. Sparkle appears to be pretty deeply woven into the project

These are both too big for me to tackle, so I'd simply suggest going forward  that your project migrate to the latest Xcode for builds, and either deprecates Sparkle or provides it as an option. That would allow straightforward management of Tunnelblick in MacPorts or Homebrew.

**Comment by reneeotten** [comment]
is there any progress on this PR or can/should this be closed until someone finds time/interest to continue to work on this?

**Comment by jkbullard** [comment]
I'm working on getting Tunnelblick building (and working) on macOS 10.15 under Xcode 12 (beta), which needs to be done to build for Apple Silicon Macs.

If/when that's done, it will include getting Tunnelblick's Sparkle to build, so I'll look at making Tunnelblick build and work without Sparkle, too.

**Comment by kencu** [comment]
Please reopen this PR someday if you get it into a workable state for someone to review.

**Pull request closed without merging**
