### PR TITLE
cabal: Update to version 3.4.0.0

### PR DESCRIPTION
**Pull request by essandess**
cabal: Update to version 3.4.0.0

* Update to version 3.4.0.0
* Implement new cabal bootstrap process

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.7 19H524
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
hey! so we can finally close #6182? It's nearly four thousand PRs ago now....

**Comment by essandess** [comment]
@kencu May we please merge this necessary update that fixes bugs that affect other ports?

**Comment by essandess** [comment]
Ping.

**Comment by essandess** [comment]
@kencu Look—all successful builds on a bunch of different version. May we please merge?

**Comment by cjones051073** [comment]
Builds are failing in buildbots, see e.g.

https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/137145/steps/install-port/logs/stdio

**Comment by herbygillot** [comment]
> Builds are failing in buildbots, see e.g.
> 
> https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/137145/steps/install-port/logs/stdio

I think let's see how it does on newer versions of macOS.

**Pull request merged**
