### PR TITLE
Openjdk u subport and Openjdk boot subport

### PR DESCRIPTION
**Pull request by usersxx**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65 x86_64
 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by usersxx** [comment]
First three commits are due to master branch

**Comment by usersxx** [comment]
First three commits are due to master branch of my folk of macports/macports-ports

**Comment by usersxx** [comment]
@pmetzger Can you Re-run workflow files

**Comment by usersxx** [comment]
@pmetzger 
Can you Re-run workflow files

**Comment by pmetzger** [comment]
You will need to squash your commits before they can be considered for merging. I can't speak to whether this change is good or not, @breun can give his opinion.

**Comment by usersxx** [comment]
I didn't make all changes yet, After all changes I would squash these commits (I can't squash first commit, second commit and third commit)

**Pull request closed without merging**
