### PR TITLE
osxfuse: don't build BridgeSupport metadata by default

### PR DESCRIPTION
**Pull request by yan12125**
#### Description

Building BridgeSupport metadata is broken on High Sierra or newer due to
an macOS and/or Xcode bug [1]. As the workaround breaks building iTerm2
[2], I'd like to skip the fragile step instead playing more with Xcode
and macOS.

Apparently BridgeSupport metadata is used when programs using scripting languages want to utilize frameworks written in Objective-C. Examples are MacRuby [3], PyObjC [4] and NodObjC (for node.js) [5]. Looking into ports depending on osxfuse, apparently none uses these technologies. py-fuse and py-llfuse uses the C binding of osxfuse, and other are usual C/C++ programs/libraries. If there's really a port requiring BridgeSupport metadata, I'd like to tell port maintainers for it to use `require_active_variants`.

[1] https://trac.macports.org/ticket/54939
[2] https://github.com/macports/macports-ports/pull/3525#issuecomment-458799559
[3] https://github.com/amirrajan/rubymotion-bridgesupport
[4] https://pythonhosted.org/pyobjc/metadata/bridgesupport.html

###### Type(s)

- [x] bugfix (for other ports, anyway)
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.3 18D42
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
I've built osxfuse without BridgeSuppport metadata and rebuilt VeraCrypt against that modified version. I can still mount my secret volume and read files from it.

### CODE REVIEW

**Comment by yan12125** [comment]
@macportsbot retry

**Comment by yan12125** [comment]
> No version of Xcode found

LOL apparently mdworker (Spotlight) is not enabled on Travis's xcode9.4 builder [1]

[1] https://trac.macports.org/ticket/57142

**Comment by pmetzger** [comment]
@yan12125 But the Azure CI seems to have succeeded just fine.

**Comment by yan12125** [comment]
Do you mean the Azure Pipelines in my previous iTerm2 PR? I've also removed the osxfuse workaround there.

**Comment by pmetzger** [comment]
I mean the Azure Pipelines for this PR as well. They passed even though Travis failed.

**Comment by yan12125** [comment]
> I mean the Azure Pipelines for this PR as well. They passed even though Travis failed.

Yep that's a good sign! Looks like the Azure builders are more close to authentic macOS installations.

**Comment by yan12125** [comment]
No objection for this specific change for a long time - gonna merge.

**Pull request merged**
