### PR TITLE
stubby: update to 0.4.2

### PR DESCRIPTION
**Pull request by neirbowj**
#### Description

stubby: update to 0.4.2

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.7 20G817 arm64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by l2dy** [comment]
Could you update `getdns` first?

**Comment by neirbowj** [comment]
> Could you update `getdns` first?

I didn't see anything in the release notes about an updated version dependency. Did I miss something?

**Comment by l2dy** [comment]
It's not a strict requirement, but I prefer matching the versions of these two ports. https://getdnsapi.net/releases/getdns-1-7-2/ says that "This release has a [Stubby](https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Daemon+-+Stubby) version 0.4.2 included."

**Comment by neirbowj** [comment]
I tried doing the obvious things to update the getdns port and am now getting build errors about implicitly defined `malloc` and `free`. Getting into troubleshooting that seems like more than I am able to bite off at the moment.

**Comment by neirbowj** [comment]
See [getdns-1.7.2.log](https://github.com/macports/macports-ports/files/9742256/getdns-1.7.2.log) for details of the failing build.

getdnsapi/getdns@b181782 replaces `stdlib.h` with `strings.h`, which looks like the proximate cause of the build failure. My C is somewhat rusty at this point, and I don't have a good intuition about whether this is an upstream bug or a port bug. FWIW, `malloc(3)` specifies `stdlib.h` as a requirement, so my next step would be to patch that back in.

For comparison, it turns out that I cannot build 1.7.0 either, but for a different reason having to do with the final destroot installation. See [getdns-1.7.0.log](https://github.com/macports/macports-ports/files/9742257/getdns-1.7.0.log) for details.

**Comment by reneeotten** [comment]
@l2dy can you provide some guidance here to get this PR finalized/merged?

**Comment by l2dy** [comment]
See https://github.com/getdnsapi/getdns/pull/526. Please try the upstream patch https://github.com/getdnsapi/getdns/commit/9c076ca34b9569eb60861da9a99f895a49d5a7b4.

**Comment by neirbowj** [comment]
> See [getdnsapi/getdns#526](https://github.com/getdnsapi/getdns/pull/526). Please try the upstream patch [getdnsapi/getdns@9c076ca](https://github.com/getdnsapi/getdns/commit/9c076ca34b9569eb60861da9a99f895a49d5a7b4).

The patch applies and compilation appears to run successfully to completion. `sudo port install -vst getdns` fails in the destroot phase of the build, and I'm having trouble understanding why. See [getdns-1.7.2-patched.log](https://github.com/macports/macports-ports/files/9844823/getdns-1.7.2-patched.log). It's probably something simple, but I'm just not seeing it.

**Comment by l2dy** [comment]
`sudo port clean getdns` and try again. `Killed by signal: 9` is probably some temporary error on your Mac.

**Comment by neirbowj** [comment]
Thanks, @l2dy. I tried cleaning and rebuilding several times and got the same error.

**Comment by l2dy** [comment]
Interesting. It builds successfully on my machine, so you are on your own to debug this. Nonetheless, you will be able to install binaries once they are built on https://build.macports.org/waterfall and synced to the mirrors.

**Pull request merged**
