### PR TITLE
boehmgc: update to 8.2.6

### PR DESCRIPTION
**Pull request by ivmai**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13
Xcode 9.4

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
> What's the reason of build failure?

It's your pull request, shouldn't you be telling us?

**Comment by pmetzger** [comment]
Checking on what's going wrong with the CI.

**Comment by ivmai** [comment]
Thank you!

**Comment by pmetzger** [comment]
Can you rebase your commit and push it again?

**Comment by reneeotten** [comment]
thanks for the update @ivmai

**Pull request merged**
