### PR TITLE
py-csvkit: Update to 1.0.2, add ports for new dependencies

### PR DESCRIPTION
**Pull request by esafak**
[Introduces new dependencies: py-agate, py-agate_sql, py-agate_dbf, py-agate_excel](https://github.com/wireservice/csvkit/blob/1.0.1/requirements-py3.txt)

Passes linter and installs.

https://trac.macports.org/ticket/53643

### CODE REVIEW

**Comment by g5pw** [comment]
I'm sorry, but your commit messages are not up to our standards. You also added two commits with the same message.
Last but not least, try to separate whitespace-only changes from meaningful ones.

**Comment by mf2k** [comment]
Can openmaintainer be added?

**Comment by raimue** [comment]
Could you please rebase this to current master?

**Comment by esafak** [comment]
Done @raimue, but the travis config is messed up:

> Error: /opt/local/bin/port: Failed to initialize MacPorts, error deleting "/opt/local/var/macports/home/Library/Preferences/com.apple.dt.Xcode.plist": no such file or directory

**Pull request merged**
