### PR TITLE
linear_algebra PG: support FlexiBLAS and blis; adept2, NTPoly: switch to linear_algebra

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Closes:
https://trac.macports.org/ticket/68910
https://trac.macports.org/ticket/68569

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.2.1
Xcode 15.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by szhorvat** [comment]
@barracuda156 @pmetzger :

I'm not sure this was a good idea to merge.

 - **FlexiBLAS** is not a BLAS or LAPACK implementation. Its purpose is to make it possible to switch the BLAS and LAPACK backends at runtime. Since this does not seem to be made possible in MacPorts, what is the point of having FlexiBLAS at all?
 - **BLIS**, as packaged in MacPorts, does not seem to provide LAPACK. A lot of the ports won't build at all with the `+blis` variant, since most software that uses BLAS also uses LAPACK. This PR explicitly sets `-DLAPACK_LIBRARIES=blis`, which seems wrong under these circumstances.

CC @catap in case you have comments.

**Comment by szhorvat** [comment]
I'm sorry, FlexiBLAS does actually work fine, this was my mistake.

The comment on BLIS stands.

**Comment by barracuda156** [comment]
@szhorvat I did try building a few ports against both, of course, prior to making a PR; AFAIR, I did run some tests too, so it should work.

Re lapack – yes, you are right, we should link to `lapack` instead, when `blis` is used. I bumped into that issue later, but did not have time to return to it and fix properly (well, just modifying PG is trivial, but it will need some testing).

**Comment by barracuda156** [comment]
@szhorvat Re `blis`, here: https://github.com/william-dawson/NTPoly/issues/228#issuecomment-1869249473

**Comment by barracuda156** [comment]
> Is it a good idea to link to blis's BLAS and a different LAPACK?

@szhorvat I am not really qualified to answer this, perhaps it is forth asking the upstream.

> That different LAPACK will in turn link to a different BLAS as well

There is a `lapack` port which looks like a standalone Lapack.
```
% port deps lapack
Full Name: lapack @3.12.0_1+gfortran
Build Dependencies:   cmake, gcc13
Library Dependencies: libgcc
```
Would it not work?

> Can blis be configured to provide LAPACK?

I do not see lapack-related configure options for it: https://github.com/flame/blis/blob/1a8c8180b32cf5988bf9eb5d2f0f8111a729993a/configure

**Pull request merged**
