### PR TITLE
py-backports.weakref: fix destroot issue

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
- fix destroot issue with py-backports.weakref (https://trac.macports.org/ticket/58004)
- removed subports for PY35/PY36 as this functionality was introduced in PY34
- fixed py-tensorflow dependency on py-backports.weakref that was incorrect

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.2 18C54
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`? N/A
- [x] tried a full install with `sudo port -vst install`? Yes, for py27-backports.weakref and py36-tensorflow.
```py-tensorflow``` fails on my computer, likely because it doesn't use the RightCompiler. I have followed the instructions [here](https://trac.macports.org/wiki/UsingTheRightCompiler) and the logfile says: 
```
Warning: The following files inside the MacPorts prefix not installed by a port were accessed:
  /opt/local/bin/no_default_gcc/cc
  /opt/local/bin/no_default_gcc/gcc
```
Anyhow, if this is an issue - it's certainly not introduced by this PR. Perhaps @cjones051073 and @emcrisostomo can take a look?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
`py-tensorflow` Is not a port you should be installing, instead, like most py ports, you are expected to pick a particular python version to install.

**Comment by reneeotten** [comment]
> `py-tensorflow` Is not a port you should be installing, instead, like most py ports, you are expected to pick a particular python version to install.

sorry, I meant to say is that I tested ```py36-tensorflow``` and that port doesn't install. I know that one isn't supposed to install the ```py-tensorflow``` port.

**Comment by cjones051073** [comment]
Just to clarify, it builds fine without your changes here for me. If you still hve problems with the build with this PR, please try again without it. If that builds OK, the issue is with your proposed changes here.

**Comment by reneeotten** [comment]
to me the error message suggests that the port isn't using the ```${configure.cc}``` as it should (see https://trac.macports.org/wiki/UsingTheRightCompiler#testing). If follow the recipe described there does it then build for you?

**Comment by cjones051073** [comment]
It should be using it properly. The port is built using bazel though which is really hard to get to do what you want. I did spend some time checking the compiler settings. I see though you are trace mode, which I may never have tried. Can you please

- post the complete clean log file for this. 
- try without trace mode.

**Comment by reneeotten** [comment]
@cjones051073 well, the PR did build successfully according to the Azure pipelines. It's been doing stuff for most of the day on my computer as well and so far hasn't complained yet. I am not sure though whether I am going to wait for it to finish.... Either way, it seems to me the port isn't using the RightCompiler, but I am probably not any better in trying to fix that then you.

**Comment by cjones051073** [comment]
@reneeotten I spent some time getting tensorflow to build using the choosen compiler, and for the most part I know it does. bazel insists on controlling all aspects of the build, and controlling things is complicated. It does not respect the usual flags etc., hence all the stuff in the bazel and tensorflow ports to try and work around this. bazel also insists on building all dependencies itself, which is also a huge pain. Perhaps one of these is not getting passed the correct info on which compiler to use. I would have to look into it. 

Anyway, please do wait for the build to complete. As long as it does, so things are no worse than before, I am fine with this PR.

**Comment by reneeotten** [comment]
@cjones051073 sorry for the delay, this takes forever to build... Anyway, I build both pre/post-PR versions of py36-tensorflow and run the first example under Tutorials on the TensorFlow website. All works as intended as far as I can tell!

**Comment by cjones051073** [comment]
@reneeotten Perfect, thanks. I think this can be merged now then.

( Thanks also for draw my attention to the failing tests when using trace mode etc. I will try and look into this a bit, when I have time, and can muster enough enthusiasm to deal with bazel again, but this does not affect this PR ).

**Comment by pmetzger** [comment]
Merged per @cjones051073. Thanks, @reneeotten!

**Pull request merged**
