### PR TITLE
gmt6: new port

### PR DESCRIPTION
**Pull request by seisman**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.5 18F132
Xcode 10.3 10G8

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

- [X] checked your Portfile with `port lint`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by seisman** [comment]
@mojca The xcode9.4 build fails, possibly due to network issues. Otherwise, it's ready for review.

**Comment by mf2k** [comment]
I agree with @mojca (https://github.com/macports/macports-ports/pull/5224#pullrequestreview-285157541) that this PR should be closed and instead gmt6 should be added as a sub-port of the existing gmt5 port.

**Comment by seisman** [comment]
@mf2k Are there any documentations for subports? I can't find information on https://guide.macports.org.

**Comment by mf2k** [comment]
No. See https://trac.macports.org/ticket/36957. For now, just look at other ports as a guide. For example fltk/fltk-devel.

**Comment by seisman** [comment]
Thanks for the link. subports looks much simpler. I will see how it works.

**Comment by mojca** [comment]
I would merge it as it is and create subports later, but both ways are fine, I just don't want subports to delay the new version for too long.

**Comment by seisman** [comment]
I believe I can finish the subports in a few hours. Maybe merge PR #5224 first, so that I can implement subports on top of it.

**Pull request closed without merging**
