### PR TITLE
libstdcxx-docs: new port

### PR DESCRIPTION
**Pull request by mohd-akram**
Closes: https://trac.macports.org/ticket/64237

###### Tested on
macOS 12.1 21C52 x86_64
Xcode 13.2.1 13C100

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. Do you know why the CI failed?

**Comment by mohd-akram** [comment]
No idea, it worked for me locally and the error doesn't really make sense.

**Comment by pmetzger** [comment]
I'm inclined to commit this anyway unless someone objects. Nothing depends on it yet, so if it fails to build we can always adjust.

**Comment by mohd-akram** [comment]
Looks like `xargs -r` was [only added in macOS 11](https://github.com/apple-open-source/macos/blame/11.5/shell_cmds/xargs/xargs.1#L230), hence the failures on older versions. I thought these utilities were frozen in time.

**Comment by pmetzger** [comment]
No, there are people maintaining them.

**Pull request merged**
