### PR TITLE
newsboat: update to 2.23

### PR DESCRIPTION
**Pull request by herbygillot**
###### Tested on

macOS 10.15.7 19H524
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
```
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      libnewsboat::utils::convert_text::hc50f8385c14b2965 in libnewsboat.a(libnewsboat-d0566c5d00183d65.libnewsboat.7cz4d8uu-cgu.5.rcgu.o)
  "_iconv_close", referenced from:
      libnewsboat::utils::translit::h6d2a7f5e731048a3 in libnewsboat.a(libnewsboat-d0566c5d00183d65.libnewsboat.7cz4d8uu-cgu.5.rcgu.o)
      libnewsboat::utils::convert_text::hc50f8385c14b2965 in libnewsboat.a(libnewsboat-d0566c5d00183d65.libnewsboat.7cz4d8uu-cgu.5.rcgu.o)
  "_iconv_open", referenced from:
      libnewsboat::utils::translit::h6d2a7f5e731048a3 in libnewsboat.a(libnewsboat-d0566c5d00183d65.libnewsboat.7cz4d8uu-cgu.5.rcgu.o)
      libnewsboat::utils::convert_text::hc50f8385c14b2965 in libnewsboat.a(libnewsboat-d0566c5d00183d65.libnewsboat.7cz4d8uu-cgu.5.rcgu.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [podboat] Error 1
```

**Comment by herbygillot** [comment]
There does seem to be a mismatch between the symbols `newsboat` is looking for:

```
_iconv
_iconv_close
_iconv_open
```

...and those actually being exported by `libiconv`:

```
✗ nm -a /opt/macports-test/lib/libiconv.dylib | grep -E '_(close|open)'
00000000000023d1 T _libiconv_close
00000000000010d0 T _libiconv_open
00000000000023de T _libiconv_open_into
```

This is `libiconv` version **1.16._1**.

**Comment by Minoru** [comment]
Hi, Newsboat maintainer here! I'm not sure why this crops up: in my own CI, I found that macOS ships a good enough iconv implementation, so I just use that. On FreeBSD the situation is different (the built-in iconv doesn't support `//TRANSLIT` or something), so I'm using libiconv and rewriting the symbols to link with that. I don't have a macOS machine and did all this testing in VMs on Cirrus CI (which AFAIK uses Anka), and up-to-date macOS docs are hard to come by, so my knowledge might be spotty here.

You probably have much better insight into this, or at least have machines in front of you which you can use for testing. If you grep for `_libiconv` in rust/libnewsboat/src/utils.rs and replace "freebsd" with "macos" in the attributes, does Newsboat compile for you?

Also, I wonder why this [didn't affect Homebrew](https://github.com/Homebrew/homebrew-core/pull/73642). How are MacPorts and Homebrew different?

**Comment by herbygillot** [comment]
> If you grep for _libiconv in rust/libnewsboat/src/utils.rs and replace "freebsd" with "macos" in the attributes, does Newsboat compile for you?

Thank you very much for this pointer, making that change got `newsboat` to build locally.

The reason this works for MacPorts is because MacPorts maintains its own `libiconv` in **/opt/local/lib** that is separate from the macOS _default_ `libiconv`, which lives in **/usr/lib**.

The reasons for why this is the case tie into your next question:

> How are MacPorts and Homebrew different?

MacPorts and Homebrew have fundamentally different core philosophies, which affect how they build software from the ground up.

Homebrew integrates much more with whichever macOS environment it is currently installed in.

MacPorts, on the other hand, tries to maintain its own "self-contained world" inside of **/opt/local**.  So it has its own **libiconv** and other foundation libs.  This enables a lot moe control and stability, no matter which macOS version its installed on, amongs many other benefits.

So it makes sense why when Newboat builds under Homebrew, its using whichever `iconv` is packaged with macOS, as opposed to when it builds under MacPorts, its using a MacPorts-maintained version of `iconv`.

**Comment by herbygillot** [comment]
From: https://trac.macports.org/wiki/FAQ#ownlibs

> ### Why is MacPorts using its own libraries?
>
> There are several reasons why MacPorts uses its own libraries. It makes ports more consistent across different versions of Mac OS X. For example, if we can rely on openssl 1.0.0 from MacPorts, we don't have to test every port that needs ssl for every available openssl installation. Apple's software tends to break from time to time (e.g. openssl refuses to build with an old zlib, but for awhile Apple shipped the old headers of the vulnerable zlib version). Even if Apple's versions aren't broken, they're rarely up-to-date. Apple has a habit of not updating the libraries in Mac OS X until absolutely necessitated by a security vulnerability.
> 
> The drawbacks of this policy are minimal: Wasting a few megabytes for e.g. a Python installation is next to nothing if you have a multi-gigabyte hard disk, and the time required to build the additional ports decreases as computers get faster.

**Comment by Minoru** [comment]
> Thank you very much for this pointer, making that change got newsboat to build locally.

Awesome! Does it pass the tests? (`make check`). It most probably does, but just to be sure.

> The reason this works for MacPorts is because MacPorts maintains its own libiconv in /opt/local/lib that is separate from the macOS default libiconv, which lives in /usr/lib.

Ah, got it. Thanks!

> So it makes sense why when Newboat builds under Homebrew: it's using whichever iconv is packaged with macOS, as opposed to when it builds under MacPorts, where it uses a MacPorts-maintained version of iconv.

This still doesn't quite add up for me. Before you changed the attribute in the code, it should've used the iconv implementation from libc, not libiconv. After changing the attributes, it should use libiconv. This process is unaware of Homebrew and MacPorts, so it should've worked the same way in both.

I mean, it should've linked fine, but there might've been problems later, at runtime, if macOS default libiconv turned out to be old and maybe didn't have some features. But that'd be a different problem.

But oh well. I glad you got it to build :) If the tests pass, I'll go try to incorporate this change into Newsboat proper, without breaking Homebrew.

Incidentally, do you have time to take [our Homebrew CI job](https://github.com/newsboat/newsboat/blob/061d9782227a7d16095f13f368fd7f49f4096de3/.cirrus.yml#L97-L158) as an example and add a similar one for MacPorts? I'd really like to catch those issues in development, before they find their way to you.

**Comment by herbygillot** [comment]
> > Thank you very much for this pointer, making that change got newsboat to build locally.
> 
> Awesome! Does it pass the tests? (`make check`). It most probably does, but just to be sure.

Just ran `make check`, failed with the following:
```
...
cargo test --workspace --exclude libnewsboat-ffi --no-run
   Compiling libc v0.2.90
   Compiling cfg-if v0.1.10
   Compiling getrandom v0.2.0
   Compiling cc v1.0.66
   Compiling ppv-lite86 v0.2.10
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.0.1
   Compiling memchr v2.3.4
   Compiling remove_dir_all v0.5.3
   Compiling bitflags v1.2.1
   Compiling lazy_static v1.4.0
   Compiling regex-syntax v0.6.21
   Compiling pkg-config v0.3.19
   Compiling block v0.1.6
   Compiling getrandom v0.1.15
   Compiling matches v0.1.8
   Compiling radium v0.5.3
   Compiling ryu v1.0.5
   Compiling tinyvec_macros v0.1.0
   Compiling lexical-core v0.7.5
   Compiling version_check v0.9.2
   Compiling wyz v0.2.0
   Compiling percent-encoding v2.1.0
   Compiling adler v0.2.3
   Compiling tap v1.0.0
   Compiling funty v1.1.0
   Compiling arrayvec v0.5.2
   Compiling static_assertions v1.1.0
   Compiling gimli v0.23.0
   Compiling unicode-width v0.1.8
   Compiling libnewsboat v2.23.0 (/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_net_newsboat/newsboat/work/newsboat-r2.23/rust/libnewsboat)
   Compiling byteorder v1.3.4
   Compiling object v0.22.0
   Compiling rustc-demangle v0.1.18
   Compiling xdg v2.2.0
   Compiling natord v1.0.9
   Compiling quick-error v1.2.3
   Compiling fnv v1.0.7
   Compiling once_cell v1.7.2
   Compiling bit-vec v0.6.3
   Compiling section_testing v0.0.5
   Compiling unicode-bidi v0.3.4
   Compiling thread_local v1.0.1
   Compiling tinyvec v1.1.0
   Compiling form_urlencoded v1.0.0
   Compiling textwrap v0.11.0
   Compiling num-traits v0.2.14
   Compiling miniz_oxide v0.4.3
   Compiling num-integer v0.1.44
   Compiling nom v6.1.2
   Compiling bit-set v0.5.2
   Compiling clap v2.33.3
   Compiling bitvec v0.19.4
   Compiling aho-corasick v0.7.15
   Compiling malloc_buf v0.0.6
   Compiling strprintf v0.1.0 (/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_net_newsboat/newsboat/work/newsboat-r2.23/rust/strprintf)
   Compiling time v0.1.44
   Compiling wait-timeout v0.2.0
   Compiling objc v0.2.7
   Compiling libz-sys v1.1.2
   Compiling curl-sys v0.4.41+curl-7.75.0
   Compiling rand_core v0.6.2
   Compiling rand_core v0.5.1
   Compiling unicode-normalization v0.1.16
   Compiling rand_chacha v0.3.0
   Compiling objc_id v0.1.1
   Compiling rand_chacha v0.2.2
   Compiling rand_xorshift v0.2.0
   Compiling objc-foundation v0.1.1
   Compiling rand v0.8.3
   Compiling rand v0.7.3
   Compiling chrono v0.4.19
   Compiling regex v1.4.2
   Compiling idna v0.2.0
   Compiling addr2line v0.14.0
   Compiling tempfile v3.2.0
   Compiling backtrace v0.3.55
   Compiling rusty-fork v0.3.0
   Compiling url v2.2.1
   Compiling gettext-sys v0.21.0
   Compiling proptest v0.10.1
   Compiling locale_config v0.3.0
   Compiling gettext-rs v0.6.0
   Compiling regex-rs v0.1.0 (/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_net_newsboat/newsboat/work/newsboat-r2.23/rust/regex-rs)
warning: panic message is not a string literal
   --> rust/libnewsboat/src/matcher.rs:386:34
    |
386 |                 result => panic!(format!("unexpected result: {:?}", result)),
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(non_fmt_panic)]` on by default
    = note: this is no longer accepted in Rust 2021
    = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: panic message is not a string literal
   --> rust/libnewsboat/src/matcher.rs:404:30
    |
404 |             result => panic!(format!("unexpected result: {:?}", result)),
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this is no longer accepted in Rust 2021
    = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: panic message is not a string literal
   --> rust/libnewsboat/src/matcher.rs:409:30
    |
409 |             result => panic!(format!("unexpected result: {:?}", result)),
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this is no longer accepted in Rust 2021
    = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: 3 warnings emitted

    Finished test [unoptimized + debuginfo] target(s) in 25.49s
(cd test && ./test --order=rand --rng-seed=time)
Error opening terminal: unknown.
make: *** [check] Error 1
Command failed:  cd "/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_net_newsboat/newsboat/work/newsboat-2.23" && /usr/bin/make check CC="/usr/bin/clang" CXX="/usr/bin/clang++" OBJC="/usr/bin/clang" OBJCXX="/usr/bin/clang++" INSTALL="/usr/bin/install -c"
Exit code: 2
```

But I think it might be spurious, as MacPorts builds software within a constrained build sandbox, and that could affect the way that tests run.

> 
> > The reason this works for MacPorts is because MacPorts maintains its own libiconv in /opt/local/lib that is separate from the macOS default libiconv, which lives in /usr/lib.
> 
> Ah, got it. Thanks!
> 
> > So it makes sense why when Newboat builds under Homebrew: it's using whichever iconv is packaged with macOS, as opposed to when it builds under MacPorts, where it uses a MacPorts-maintained version of iconv.
> 
> This still doesn't quite add up for me. Before you changed the attribute in the code, it should've used the iconv implementation from libc, not libiconv. After changing the attributes, it should use libiconv. This process is unaware of Homebrew and MacPorts, so it should've worked the same way in both.

Besides the `freebsd` to `macos` change, I had to patch `config.sh` to detect the `libiconv` in **/opt/local**, because otherwise I kept running into the crash above. See https://github.com/macports/macports-ports/pull/10355/files#diff-8ae91b46c4bf24bb248f62ba7f898b10138ae8f4f3d56be9466f3ada980d23fd

I'm not sure about the `iconv` from libc or not, but this is actually the better situation. Building within MacPorts, `newsboat` should use as many libraries from the MacPorts prefix (**/opt/local/lib**) as possible.  Software building within MacPorts are provided CFLAGS, LDFLAGS and other through environment and/or `make` flags that configure to include from headers in **/opt/local/include** and libraries in **/opt/local/lib**. 

```
$ otool -L ./newsboat
./newsboat:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
	/opt/local/lib/libiconv.2.dylib (compatibility version 9.0.0, current version 9.1.0)
	/opt/local/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	/opt/local/lib/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/opt/local/lib/libcurl.4.dylib (compatibility version 12.0.0, current version 12.0.0)
	/opt/local/lib/libxml2.2.dylib (compatibility version 12.0.0, current version 12.10.0)
	/opt/local/lib/libstfl.0.dylib (compatibility version 0.0.0, current version 0.24.0)
	/opt/local/lib/libncurses.6.dylib (compatibility version 6.0.0, current version 6.0.0)
	/opt/local/lib/libjson-c.5.dylib (compatibility version 5.0.0, current version 5.1.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 59754.60.13)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1770.255.0)
	/opt/local/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/opt/local/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
```

MacPorts' `libiconv` is newer than the default one provided by macOS, and the important point is that this will be the same version of `libiconv` no matter what version of macOS we're in, as that's what MacPorts seeks to do as per its philosophy.  I don't think you can expect the same version of libraries across versions of macOS by default.


On my system (macOS Catalina 10.15.7):
```
$ otool -L /usr/lib/libiconv.2.dylib
/usr/lib/libiconv.2.dylib:
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
        ....
```

vs.

```
/opt/local/lib/libiconv.2.dylib (compatibility version 9.0.0, current version 9.1.0)
```

> 
> I mean, it should've linked fine, but there might've been problems later, at runtime, if macOS default libiconv turned out to be old and maybe didn't have some features. But that'd be a different problem.
> 
> But oh well. I glad you got it to build :) If the tests pass, I'll go try to incorporate this change into Newsboat proper, without breaking Homebrew.

I think this looks good enough to merge into the ports tree for now.  I'm not quite sure what the upstream change should look like tbh... perhaps we just leave this to be a thing we need to patch here in MacPorts as it's specific to MacPorts, and not macOS 🤷🏾‍♂️.

> 
> Incidentally, do you have time to take [our Homebrew CI job](https://github.com/newsboat/newsboat/blob/061d9782227a7d16095f13f368fd7f49f4096de3/.cirrus.yml#L97-L158) as an example and add a similar one for MacPorts? I'd really like to catch those issues in development, before they find their way to you.

I've been meaning to spend more time on figuring out how to automate MacPorts in CI for individual projects, that's been a request from many upstream developers.  Hopefully I can dig in soon.

**Comment by herbygillot** [comment]
I actually just re-ran tests in the way they were supposed to have been run (`port test`), looks fine:

```
cargo test --workspace --exclude libnewsboat-ffi --no-run
   Compiling libc v0.2.90
   Compiling cfg-if v0.1.10
   Compiling getrandom v0.2.0
   Compiling ppv-lite86 v0.2.10
   Compiling cc v1.0.66
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.0.1
   Compiling memchr v2.3.4
   Compiling remove_dir_all v0.5.3
   Compiling bitflags v1.2.1
   Compiling lazy_static v1.4.0
   Compiling pkg-config v0.3.19
   Compiling regex-syntax v0.6.21
   Compiling block v0.1.6
   Compiling getrandom v0.1.15
   Compiling ryu v1.0.5
   Compiling matches v0.1.8
   Compiling tinyvec_macros v0.1.0
   Compiling radium v0.5.3
   Compiling version_check v0.9.2
   Compiling lexical-core v0.7.5
   Compiling adler v0.2.3
   Compiling tap v1.0.0
   Compiling percent-encoding v2.1.0
   Compiling gimli v0.23.0
   Compiling unicode-width v0.1.8
   Compiling wyz v0.2.0
   Compiling funty v1.1.0
   Compiling static_assertions v1.1.0
   Compiling arrayvec v0.5.2
   Compiling object v0.22.0
   Compiling libnewsboat v2.23.0 (/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_net_newsboat/newsboat/work/newsboat-r2.23/rust/libnewsboat)
   Compiling byteorder v1.3.4
   Compiling rustc-demangle v0.1.18
   Compiling quick-error v1.2.3
   Compiling fnv v1.0.7
   Compiling bit-vec v0.6.3
   Compiling xdg v2.2.0
   Compiling natord v1.0.9
   Compiling once_cell v1.7.2
   Compiling section_testing v0.0.5
   Compiling thread_local v1.0.1
   Compiling tinyvec v1.1.0
   Compiling unicode-bidi v0.3.4
   Compiling form_urlencoded v1.0.0
   Compiling textwrap v0.11.0
   Compiling nom v6.1.2
   Compiling bit-set v0.5.2
   Compiling num-traits v0.2.14
   Compiling miniz_oxide v0.4.3
   Compiling num-integer v0.1.44
   Compiling clap v2.33.3
   Compiling bitvec v0.19.4
   Compiling aho-corasick v0.7.15
   Compiling malloc_buf v0.0.6
   Compiling strprintf v0.1.0 (/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_net_newsboat/newsboat/work/newsboat-r2.23/rust/strprintf)
   Compiling time v0.1.44
   Compiling wait-timeout v0.2.0
   Compiling objc v0.2.7
   Compiling libz-sys v1.1.2
   Compiling curl-sys v0.4.41+curl-7.75.0
   Compiling unicode-normalization v0.1.16
   Compiling rand_core v0.6.2
   Compiling rand_core v0.5.1
   Compiling objc_id v0.1.1
   Compiling rand_chacha v0.3.0
   Compiling objc-foundation v0.1.1
   Compiling rand_chacha v0.2.2
   Compiling rand_xorshift v0.2.0
   Compiling rand v0.8.3
   Compiling rand v0.7.3
   Compiling chrono v0.4.19
   Compiling idna v0.2.0
   Compiling regex v1.4.2
   Compiling addr2line v0.14.0
   Compiling tempfile v3.2.0
   Compiling url v2.2.1
   Compiling backtrace v0.3.55
   Compiling rusty-fork v0.3.0
   Compiling gettext-sys v0.21.0
   Compiling proptest v0.10.1
   Compiling locale_config v0.3.0
   Compiling gettext-rs v0.6.0
   Compiling regex-rs v0.1.0 (/opt/macports-test/var/macports/build/_Users_herby_Source_macports-ports_net_newsboat/newsboat/work/newsboat-r2.23/rust/regex-rs)
warning: panic message is not a string literal
   --> rust/libnewsboat/src/matcher.rs:386:34
    |
386 |                 result => panic!(format!("unexpected result: {:?}", result)),
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(non_fmt_panic)]` on by default
    = note: this is no longer accepted in Rust 2021
    = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: panic message is not a string literal
   --> rust/libnewsboat/src/matcher.rs:404:30
    |
404 |             result => panic!(format!("unexpected result: {:?}", result)),
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this is no longer accepted in Rust 2021
    = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: panic message is not a string literal
   --> rust/libnewsboat/src/matcher.rs:409:30
    |
409 |             result => panic!(format!("unexpected result: {:?}", result)),
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this is no longer accepted in Rust 2021
    = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: 3 warnings emitted

    Finished test [unoptimized + debuginfo] target(s) in 7m 59s
DEBUG: Executing proc-post-org.macports.test-test-0
```

**Comment by Minoru** [comment]
> Besides the freebsd to macos change, I had to patch config.sh to detect the ncurses in /opt/local, because otherwise I kept running into the crash above. See https://github.com/macports/macports-ports/pull/10355/files#diff-8ae91b46c4bf24bb248f62ba7f898b10138ae8f4f3d56be9466f3ada980d23fd

Okay! I'll try that out with Homebrew as well. Perhaps Homebrew ships a new enough Ncurses that the same approach will work for both MacPorts and Homebrew.

Good that the tests pass. Everything's fine then :) Thank you for your work here!

**Comment by kencu** [comment]
The issue with libiconv goes back years and years.

For system distributions, libiconv has one symbol. For "user" distributions, another.

<https://stackoverflow.com/questions/57734434/libiconv-or-iconv-undefined-symbol-on-mac-osx>

I believe this is done on purpose, specifically to pick up situations where you are mixing up headers and libraries from different versions of libiconv. By this method, you error out and have to actually fix this problem (that you may not have known you had).

**Comment by kencu** [comment]
Homebrew may not show this is issue because they dump everything in /usr/local/include and /usr/local/lib, and those locations, rightly or wrongly, are always found by compilers like clang ahead of /usr/include and /usr/local.

So you might be using those libraries and headers in /usr/local/* with no idea that you are actually using them.... fun fun fun!

**Pull request merged**
