### PR TITLE
neovim: update to 0.4.2

### PR DESCRIPTION
**Pull request by lbschenkel**
This is work-in-progress. It currently fails during configure phase ~because NeoVim can't find `libuv`~:
```
-- Found LibUV: /opt/local/lib/libuv.dylib (Required is at least version "1.28.0")
-- Found Msgpack: /opt/local/lib/libmsgpackc.dylib (found suitable version "1.4.2", minimum required is "1.0.0")
CMake Error at /opt/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibLUV (missing: LIBLUV_LIBRARY LIBLUV_INCLUDE_DIR)
  (Required is at least version "1.30.0")
Call Stack (most recent call first):
  /opt/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibLUV.cmake:29 (find_package_handle_standard_args)
  CMakeLists.txt:375 (find_package)
```

I have bisected the upstream sources and the culprit seems to be commit
https://github.com/neovim/neovim/commit/c83926cd0aa5720e88e84fa3fae3c0e689cca3ef

 ~I'll report this upstream as well.~

---

I realized now by re-reading the message that I missed that that it's a new lib `libluv`, not `libuv`... It's not on MacPorts. I will attempt to add the port and add to this PR.

### CODE REVIEW

**Comment by lbschenkel** [comment]
Now I entered an inadvertent rabbit hole...  `libluv` needs https://github.com/keplerproject/lua-compat-5.3, but I don't have experience packaging lua modules. I'm pushing what I have for `libluv` so far.

**Comment by lbschenkel** [comment]
@raimue: not sure what were your plans (if any), so I hope you don't mind if this PR becomes a 4.2 upgrade "project"? When I submitted this I was too quick and misread the error, I though it was just about a small patch in the build but now it looks that it'll require at least 2 new dependency ports.

**Comment by pmetzger** [comment]
Regardless: this is perhaps no longer really a pull request given that it might take some time to get it working? Perhaps it should be closed and re-opened later?

**Comment by lbschenkel** [comment]
I respectfully disagree. Even if in this case it was not exactly my initial intent, PRs are a valid form of collaboration and they are not restricted to "small patches" only. I'm sharing work here that can be picked up by others if they're so inclined or if I get stuck or unavailable.

In case @raimue is not comfortable with being the PR assignee, feel free to reassign this PR to me instead. In no case I'll merge without @raimue's approval.

**Comment by pmetzger** [comment]
> they are not restricted to "small patches" only

No, they're not intended for small patches only, but they are intended for _commitable_ patches. The notion is that this is a request to pull something, not an invitation to work on something. For the latter we have git branches. The problem is that the PR queue often ends up being a graveyard for work that isn't really ready, and then it becomes difficult to notice the work that is in fact ready.

**Comment by lbschenkel** [comment]
I apologize in advance because this might not be the best avenue for this meta-discussion (maybe the mailing list), but I have an honest question: what is then the purpose of the "wip" label?

I feel that *if* we (@raimue and I) both agree to collaborate in this way, we should be able to. An open PR makes a branch visible. A branch of my fork is not (in the same way). I hit a roadblock so I pushed my in-progress work so it is able to be reviewed and feedback given while I'm working on it independently.

I also find this narrow interpretation of what a PR is particularly odd, one that I never encountered before in any open source project that I have been involved with. Many projects use PRs for collaborative development. What do you propose otherwise for collaborating in a project such as MacPorts with the source on GitHub, where we don't know each other? Private e-mailing back and forth (something like: "please look at my branch again and mail me any feedback you have about the ongoing work")? Do you believe that's good for the project, in terms of visibility, or in terms of friction for us volunteering our time? This is not searchable nor transparent: if in the meantime somebody is trying the same upgrade, we're just duplicating work -- they could have found the PR and joined (or avoided) the effort. I believe we want open collaboration, and GitHub has a diff UI optimized for giving comments, one of the reasons the source is here is for us to leverage it.

I have to admit that I would be way more sympathetic if we were having this conversation after this PR was lying here without any activity for days/weeks/months. And yet I the discussion started 1 hour after the last push. We didn't even have time to hear back from the maintainer.

My personal stance about this is that the ones that should decide normally if a PR is appropriate is the author/submitter and the assignee(s). In case a PR becomes problematic, such as becoming abandoned, then sure: others can and should act and do the necessary corrective steps.

In case I'm missing or contradicting any project guidelines here, please do point it out so I can correct any misconception or blind spots that I may have.

(P.S.: English is not my native language and my writing style sometimes may read very terse/direct, so please give me the benefit of the doubt in case something might be poorly phrased. It's my intent to be direct but not overly blunt.)

**Comment by pmetzger** [comment]
> what is then the purpose of the "wip" label

I don't think the "WIP" label is a good idea, but it was intended for things that were _near_ commitable.

> I also find this narrow interpretation of what a PR is particularly odd, one that I never encountered before in any open source project that I have been involved with.

I'll repeat: if the pull queue gets beyond a certain size, it starts to grow without bound. No one can find things in it that actually are ready to commit, so no one notices the difference between things that need work now and things that are just rotting, and then the project as a whole starts suffering. We have hit the "expands without bound" problem in the trac database at this point; the odds that it will ever become manageable again are pretty much zero, and bug reports pretty much just go there to die, which is a serious project management problem.

The PR list is already more than a bit problematic now that we're around 50 pull requests, which is beyond the point where a couple of people can remember what needs work. If we got to 100, that would probably be it, and the PR queue would start becoming a graveyard, with no expectation that PRs would be dealt with in bounded time.

**Comment by lbschenkel** [comment]
Another things that kills projects is raising friction and discouraging contribution.

The PR list can be sorted by activity. Nobody is saying that special attention can't be spent on PRs that haven't seen activity for a while (whatever "a while" means).

And yet we are telling somebody volunteering their time, a *couple of hours* after they opened a PR, that they work is not welcome here unless it's in a finished state. And if they need to communicate with the maintainer, they better to this via a different medium and not GitHub. Or do all the work alone, and only then ask for feedback and risk redoing a bunch of it because the maintainer preferred a different approach than the one taken.

Concretely, in this NeoVim upgrade, I was looking forward for @raimue opinion on the following: 
- I'm adding new deps as separate ports, does he agree? NeoVim actually bundles the deps it needs so they don't necessarily need to be ports, if it's an obscure lib not used by anybody else we could just use the bundled version.
- Is he fine with the build flags?
- Is he OK with the new ports and their deps? Maybe we need variants?

By taking a look at the work in progress while I continue the work on this, there's the chance he can give the feedback before I'm done, so I waste less work than rewriting PR after is "finished". 

But now I spent all the energy and free time I had into a discussion that it's bad for the project that PRs like this exist. The number of open PRs is the only metric that matters, above any other concerns.

Very well. I lost all motivation to spend additional effort on this PR. From now on I will also refrain from contributing any non-trivial amount of work to any other port which I don't maintain, because the message I'm hearing is: you're only welcome if you submit the whole completed work to the maintainer. If you would like to communicate to the maintainer during the process or show any partial work you should do that elsewhere. If you do this via GitHub you're making the project suffer, even if your PR would eventually have been completed within 24-48h.

Now that I know what really matters, I'm going to fix my contribution by closing this and having one less PR to worry about.

**Comment by raimue** [comment]
I understand the concerns of @pmetzger. We should prevent the list of PRs to become an unsorted mess. Too many loose ends will make it hard to see the state of a specific port. However, preparing the port update in some fork makes it even harder to find the existing work-in-progress for other contributors and might lead to duplicated efforts.

A while ago, GitHub added [draft pull requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/). Our `wip` label predates that addition, but I think draft pull requests would be the right kind for submissions that are known not to work at first. Although I am not sure how the CI systems would handle such a draft pull request...? :thinking:

It would probably be a good idea to split the review of the new port `lua-luv` from the neovim update. Of course this is the reason the library is required now, but actually it could then already be merged to the ports tree while other parts of the neovim update are still being worked on. Submitting smaller independent units for review also seems like a good way to keep the PR queue lean.

I will also try to answer your questions regarding the new neovim version:

* Yes, please always add new dependencies as separate ports. Bundling libraries might cause unexpected problems later on. MacPorts itself does not have any specific documented policy for that, but as an example see this [list of reasons against bundling libraries]( https://fedoraproject.org/wiki/Bundled_Libraries) collected by Fedora.

* I am not sure which build flags you refer to? Those of lua-luv? That looks all fine to me...

* Yes, please add these ports as needed. We already refer to a bunch of other lua libraries, so I see no reason not to add one more. The only missing thing at first glance was the `depends_lib port:lua-luv` in the neovim port, but I guess it was just not at that state yet.

I will probably not have the time to invest a deeper look into updating neovim myself in the upcoming weeks. I appreciate your efforts and I will try to provide as much review as I can!

**Comment by lbschenkel** [comment]
The exact mechanics of such a PR are unimportant ("wip" tag, draft PR) and either is totally fine -- different projects have different processes and I'm used to both. What I can't agree with is that there's no place at all for this kind of submission and they're always unwelcome, irrespective of circumstance. I feel the urge to speak up about that.

Let me elaborate:

I totally understand the intent. I totally understand why we want PRs to be as "tidy" as possible. I understand how this can get out of hand. However, we ideally should apply the rules when problems happen, not anticipating non-existing problems.

I can't remember ever leaving a PR "hanging" here. Any slow PRs that came to mind were due to delays from another participant to provide the necessary answers. And if I'm forgetting anything it happened once or twice, at most. And the WIP was just due to being unplanned, so the push was just to make the temporary state visible for any feedback while I could work on the rest. Keeping it "hidden" helps nobody. I was expecting to finish all the work in a number of hours, but then the conversation got derailed and I lost all focus.

Let's take a step back: we're putting a hurdle in the process for PRs that are not (yet) problematic, because they could become problematic, because the reasoning is that all work-in-progress is a liability since it will inevitably become abandoned. Period. There's no nuance or benefit of the doubt. So we shouldn't use GitHub as an open/collaborative development tool, which is one of the things that it does best: to put the code in front of somebody else for feedback.

Imagining that any draft/WIP PRs are banned, what would you suggest that should have been the workflow for a scenario in which I have done the work halfway, and I would like to show it to @pmetzger and get his feedback as the maintainer before I spent more effort into finishing it? Do you think this workflow would encourage or discourage most people from volunteering their time, and would add ore removed friction, compared to the GitHub workflow?

What I was expecting to happen here:

- roadbump found, pushing in-progress work for any feedback
- (in parallel) remaining work is going on
- (in parallel) you could take a look and give the feedback you gave above
- (some hours later) feedback received, I split the new ports into their own PRs
- this PR is waiting for those PRs to be merged
- (after other PRs merged) we merge this PR, I was expecting this to happen 24-48h after the initial submission

Note that I'm talking about a specific situation: a WIP PR in active development that will be completed somewhat quickly. If I thought that this needed a week or more, I would already have done some things differently (or would have stated this outright so we decide next step).

If this PR was lying here for days without any sign of activity, I would be the first to say that anybody should just close it with a comment. This could even be automated.

But starting that conversation after 2h of initial submission (without even giving a realistic chance for the submitter to finish the work) does not make anybody feel rewarded, which I presume is the only thing that keeps us going on a volunteer-based project. We give way more time to a maintainer just to look at a PR and say something back.

Anyhow, until this policy is sorted out on a project level I'll refrain to further contribute in anything that is non-trivial and requires back-and-forth with a maintainer, because if it's not going to happen via GitHub it simply don't see it happening in practice.

**Pull request closed without merging**
