### PR TITLE
Wireshark: remove obsolete ports

### PR DESCRIPTION
**Pull request by ra1nb0w**
#### Description

- make obsolete wireshark and wireshark-devel
- make obsolete wireshark24
- wireshark22: default to qt4 as asked by @kencu

Closes: https://trac.macports.org/ticket/58336

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.4 18E226
Xcode 10.2.1 10E1001

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ra1nb0w** [comment]
As discussed on [trac](https://trac.macports.org/ticket/58336) we can make wireshark a dummy port that require the last wireshark; wireshark3 in this moment.

**Comment by mf2k** [comment]
The Trac ticket reference needs to be added to one of the commits.

`Closes: https://trac.macports.org/ticket/58336`

**Comment by ra1nb0w** [comment]
done. thank you

**Comment by cjones051073** [comment]
This pr now has conflicts with master. @ra1nb0w can you take a look ?

**Comment by ra1nb0w** [comment]
Done. @ghosthound commited without see this PR (qt4 as default on wireshark22).

**Comment by cjones051073** [comment]
Thanks. Committing under maintainer timeout.

**Comment by ra1nb0w** [comment]
thank you

**Pull request merged**
