### PR TITLE
clang-11-bootstrap: fix building compiler-rt

### PR DESCRIPTION
**Pull request by catap**
#### Description

I've also migrated all patches to git tree.

A few remarks for migration.

1. `strnlen` patch was split into a few different one. So, I've merged differnet patches related to missed strnlen to `0003-Fix-build-issues-pre-Lion-due-to-missing-a-strnlen-d.patch`

2. Added missed `0009-default-to-libcxx-on-all-systems.patch`, and `0025-clang-support-macports-libstdcxx.patch`. The last one was syncronized with clang-11 port implementation.

Anyway, to keep thing possible to review I've split migration commit per patch, which I'll squash into one commit after review.

Also, I've fixed building compiler-rt with atomics by GCC that allows to make a nice clang compiler :)

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

The test case was to compile a trivial programm which is used `std::atom` and `std::thread` which is available here https://gist.github.com/catap/7d82b348450387bdc59b921f6eba523f as `/opt/local/libexec/clang-11-bootstrap/bin/clang++ -arch XXX test.cc`

with `-arch i386` on:

macOS 10.5.8 9L34 i386
Xcode 3.1.4 9M2809

with `-arch arm64` and `-arm x86_64` on:

macOS 12.4 21F79 arm64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
@mascguy may I ask you about review?

**Review by mascguy — APPROVED** [review]
While I don't have sufficient knowledge to review the patches themselves, the portfile changes look good to me.

@cjones051073 and @kencu, can you folks review as well?

**Comment by catap** [comment]
@MarcusCalhoun-Lopez, I've used your patch for support MacPorts' stdlibcxx here... if you have a chance to review it, I'll be also very appreciated.

**Comment by catap** [comment]
@mascguy what is a timeout for this case should be? Special that I'm a maintaner of this port? :)

**Comment by mascguy** [comment]
> @mascguy what is a timeout for this case should be? Special that I'm a maintaner of this port? :)

Well, for foundational bootstrap ports like this, one of our toolchain folks should provide a thumbs-up. Otherwise I'll be yelled at, if something breaks.  ;-)

@kencu, @cjones051073, @MarcusCalhoun-Lopez, @jmroot ... can someone please review and merge?

**Comment by catap** [comment]
@mascguy but the issue that I did this port :)

So, let's wait for a week more than?

**Comment by catap** [comment]
BTW before merge I'd like to squash all moving commits into one.

**Comment by mascguy** [comment]
> @mascguy but the issue that I did this port :)
> 
> So, let's wait for a week more than?

I feel bad, as I'd really like to merge this... but I don't have the deep knowledge that our veteran members do. And it's better to let one of those folks provide their blessing first.

Hopefully someone will be able to review over the next week. If that doesn't happen, I'll reach out to folks directly.

**Comment by catap** [comment]
@mascguy I've created such port a few months ago. It is quite new and the only things that using it is libcxx.

Here, I may confirm that I've tested that this compiler can be used to compile libcxx which I've used on my 10.6

**Comment by mascguy** [comment]
> @mascguy I've created such port a few months ago. It is quite new and the only things that using it is libcxx.
> 
> Here, I may confirm that I've tested that this compiler can be used to compile libcxx which I've used on my 10.6

Good point, and that makes me more comfortable with merging.

Currently the buildbots are busy with some long-running Python ports, and they'll likely need another 24-48 hours to catch up. Once they're all idle again, I'll go ahead and merge.

And thank you for all of the great work on this Kirill!

**Comment by catap** [comment]
@mascguy thanks. When I'm squashing everything to two commits.

**Comment by catap** [comment]
@mascguy you may see via GitHub UI that my force push are identical in term of files changes. But contains just 2 commits :)

**Comment by catap** [comment]
@mascguy to make you more convinced. I've tested it on much more deeper integration: https://github.com/catap/macports-ports/commits/clang_dependency

**Comment by mascguy** [comment]
> @mascguy to make you more convinced. I've tested it on much more deeper integration: https://github.com/catap/macports-ports/commits/clang_dependency

You always do great work Kirill, and I trust that you're thorough. So no worries there!

Now that our buildbots are almost caught up, let's go ahead and merge. Thanks again!

**Review by mascguy — APPROVED** [review]

**Pull request merged**
