### PR TITLE
py-boto3: update to 1.17.86

### PR DESCRIPTION
**Pull request by emcrisostomo**
py-botocore: update to 1.20.86

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.7 19H1217 x86_64
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by judaew** [comment]
An hour earlier, I already created a PR to update py-botocore in https://github.com/macports/macports-ports/pull/11225.

**Comment by emcrisostomo** [comment]
Oh my, @judaew, I'm afraid I did something wrong parsing the output of `gh` here.
I'll tag this one as WIP, and will rebase when #11225 is closed.

**Comment by judaew** [comment]
Thanks for the contribution 🌟

**Comment by emcrisostomo** [comment]
> OK, thanks for the contribution 🌟

Thank you @judaew, I've just merged #11225 and I've rebased my changes.

**Pull request merged**
