### PR TITLE
Shaderc new port,update vulkan-<all>, glslang, spirv-tools, spirv-headers

### PR DESCRIPTION
**Pull request by christophecvr**
#### Description
See: https://trac.macports.org/ticket/71081
shaderc: Added Newport
vulkan-\<all>: update to 1.3.296.0
glslang: update to 1.3.296.0
spirv-tools: update to 1.3.296.0
spirv-headers: update to 1.3.296.0

Set where it was not done yet the python used version to 3.12
Fixes: https://trac.macports.org/ticket/71081

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15
Xcode 11.5/ Command Line Tools 11.5

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by christophecvr** [comment]
@judaew  If You wish I can remove this pull request again and remake one with the last commit squashed in.
Then we have just a pull request consisting of 4 commits. : 
- upgrade spirv-tools, spirv-headers
- upgrade glslang
- upgrade vulkan-\<all>
- Adding new port shaderc

Squashing it all in one single commit is to much I find

**Review by judaew — APPROVED** [review]
Looks got to me, I see a lot of work has been done. Thank you! I'll try to build it on my laptop tonight.

**Comment by judaew** [comment]
> Squashing it all in one single commit is to much I find

I agree with you.

It's great that you updated glslang! I couldn't figure out what was wrong with it.

**Comment by christophecvr** [comment]
Now that find out the full functionality and goal of building with the trace option, I found a lot more which is not 100% ok .
It actually never was  

> > Squashing it all in one single commit is to much I find
> 
> I agree with you.
> 
> It's great that you updated glslang! I couldn't figure out what was wrong with it.

Yes glslang took me a lot of time before i found out how to best upgrade it. 

However thanks to all this trouble with the fact that the intial checks failed. I discovered finally the real use of -t (trace) option into a build.  I also dscovered a bug (buggy use op GLOB_RECURSE into the vulkan-loader port.
To create the vulkan.framework it does a search of all possible needed header files. Unfortunately this procedure will start a scan of all files into /opt/local/include. When building with trace after two hours it is still stuck during configure phase.
Googling on the web i did found that here it is a wrong use of the GLOB_RECURSE.
The error is : 
loader/CMakeLists.txt line number 463
`file(GLOB_RECURSE CONFIGURE_DEPENDS FRAMEWORK_HEADERS ${VulkanHeaders_INCLUDE_DIRS})`
the ${VulkanHeaders_INCLUDE_DIRS} is just /opt/local/include

I'm currently working on it to solve this issue. Now it search into a massive amount of places.

**Comment by christophecvr** [comment]
So try it all out already by you. In the mean time I'm preparing a new push request with a couple of improvements concerning not set depends-build_append ports and or required tools. Also I will include a patch for the vulkan-loader port.

**Comment by christophecvr** [comment]
Ok I will close this pull request, and then send another complete clean one.

**Comment by judaew** [comment]
I checked again, everything is fine. Thank you so much!

**Comment by judaew** [comment]
I checked again this PR, everything looks is goods. Thank you so much!

> Ok I will close this pull request, and then send another complete clean one.
Then I will merge it immediately after CI checking. I could to merge this PR, but you beat me to it and closed.

**Pull request closed without merging**
