### PR TITLE
iTerm2: disable automatic update functionality

### PR DESCRIPTION
**Pull request by Tatsh**
#### Description

https://trac.macports.org/ticket/56840

Hoping this patch can last a few versions as I do not expect the lines it modifies to change very much.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.7 19H15
Xcode 12.1 12A7403

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`? n/a
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by Tatsh** [comment]
I minimalised the nib file patches, so maybe it can stay compatible with older Xcode versions.

**Comment by markemer** [comment]
Love it. I've been meaning to kill this thing for a long time, hopefully this won't change much.

**Comment by Tatsh** [comment]
Hey do you want to bump the revision? I completely forgot sorry. I'm okay with rebuilding with `port -s` here but the binary that's on the archive will still have the unwanted update functionality.

**Comment by ryandesign** [comment]
Yes, since you changed the functionality of the program, you needed to have increased the port's revision. I'll do it...

**Comment by i0ntempest** [comment]
Did some manual fixing to make the patch work with 3.4.1. I'll update the port & submit modded patch very soon.

**Comment by Tatsh** [comment]
I'll be okay if you just want to stub out the code and leave the related UI elements non-functional. I prefer them removed but...

It's unlikely a nib file patch will last more than one version. Even doing something like parsing the XML and removing the elements we don't want would not be very viable. If iTerm starts receiving rapid updates I think we'll have to forget about editing the nibs.

**Comment by Tatsh** [comment]
Actually a better solution is to give upstream a patch to build a 'No Sparkle' version of the main target. They should understand some would want this in general.

**Comment by i0ntempest** [comment]
How about patching the Xcode project to stop it from bundling sparkle framework? I guess then the buttons would be nonfunctional. Let me try

**Comment by Tatsh** [comment]
Yes we definitely want that as now Sparkle is just wasting space. I forgot to to do that in this PR.

**Comment by i0ntempest** [comment]
Well nope, it won't run without sparkle bundled, even after I remove the library link to it in Xcode. I guess we'll have to talk to upstream if we wanna completely rip sparkle out.

**Comment by Tatsh** [comment]
Also we could remove the related UI elements in code rather than patching the nibs. That is, the checkbox in Preferences and the 'Check for Updates' under the iTerm menu.

It's not too great but that patch may last longer than one version.

**Comment by Tatsh** [comment]
I have my patch ready and it was kind of simple. The only real difference between the two versions were some metrics that changed in the nibs. And I removed the part of the patch removing outlets and custom objects (Sparkle-related) as this is not necessary and just complicates the patch making it more prone to failure.

Do you mind if I submit my patch here as PR now?

```diff
diff --git a/aqua/iTerm2/Portfile b/aqua/iTerm2/Portfile
index e3fae43d8a5..93402689969 100644
--- a/aqua/iTerm2/Portfile
+++ b/aqua/iTerm2/Portfile
@@ -6,11 +6,11 @@ PortGroup           xcodeversion 1.0
 use_xcode           yes
 
 if {${os.major} > 16} {
-    version             3.3.12
-    revision            1
-    checksums           rmd160  37d4204f97ac42431c5774a943ca0ab8f9a4c669 \
-                        sha256  6eeeb3215d6725aa789d39108a8ebedbe1aa9f6d058dd33056d72471ecd02e14 \
-                        size    20602868
+    version             3.4.1
+    revision            0
+    checksums           rmd160  16c6756a058ae2ce829de37d6306ce1bba30a564 \
+                        sha256  fc2bfffaa23c5945a0c7a2bb512e5514e7ee33884594ddfcdb657d8a0fbd5226 \
+                        size    23217922
     patchfiles          patch-Makefile-XC10.diff \
                         patch-remove-sparkle.diff \
                         patch-nsur.diff
diff --git a/aqua/iTerm2/files/patch-remove-sparkle.diff b/aqua/iTerm2/files/patch-remove-sparkle.diff
index 34944b339fe..98ce8a43747 100644
--- a/aqua/iTerm2/files/patch-remove-sparkle.diff
+++ b/aqua/iTerm2/files/patch-remove-sparkle.diff
@@ -32,22 +32,6 @@ index 093a4958c..76521fa89 100644
                              <menuItem isSeparatorItem="YES" id="Dpc-y9-dq3">
                                  <modifierMask key="keyEquivalentModifierMask" command="YES"/>
                              </menuItem>
-@@ -1336,7 +1328,6 @@ DQ
-                 <outlet property="maximizePane" destination="1233" id="1237"/>
-                 <outlet property="selectTab" destination="847" id="863"/>
-                 <outlet property="showFullScreenTabs" destination="1257" id="1260"/>
--                <outlet property="suUpdater" destination="879" id="FRj-mW-Vma"/>
-                 <outlet property="toolbeltMenu" destination="1296" id="1299"/>
-                 <outlet property="useTransparency" destination="1228" id="1230"/>
-                 <outlet property="windowArrangementsAsTabs_" destination="z6V-EJ-Ntf" id="wse-Wc-WVw"/>
-@@ -1344,7 +1335,6 @@ DQ
-             </connections>
-         </customObject>
-         <customObject id="266" userLabel="Font Manager" customClass="NSFontManager"/>
--        <customObject id="879" userLabel="SUUpdater" customClass="SUUpdater"/>
-         <menuItem isSeparatorItem="YES" id="TYx-JS-5H0"/>
-         <menuItem title="Mouse Reporting" id="y5H-9R-t1f">
-             <modifierMask key="keyEquivalentModifierMask"/>
 diff --git Interfaces/PreferencePanel.xib Interfaces/PreferencePanel.xib
 index e0df82e16..e9716d6fb 100644
 --- Interfaces/PreferencePanel.xib
@@ -69,7 +53,7 @@ index e0df82e16..e9716d6fb 100644
 -                                                </connections>
 -                                            </button>
 -                                            <button fixedFrame="YES" translatesAutoresizingMaskIntoConstraints="NO" id="5049">
--                                                <rect key="frame" x="18" y="18" width="195" height="18"/>
+-                                                <rect key="frame" x="18" y="18" width="285" height="18"/>
 -                                                <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMinY="YES"/>
 -                                                <buttonCell key="cell" type="check" title="Update to Beta test releases" bezelStyle="regularSquare" imagePosition="left" alignment="left" inset="2" id="5065">
 -                                                    <behavior key="behavior" changeContents="YES" doesNotDimImage="YES" lightByContents="YES"/>
@@ -80,7 +64,7 @@ index e0df82e16..e9716d6fb 100644
 -                                                </connections>
 -                                            </button>
 -                                            <button fixedFrame="YES" translatesAutoresizingMaskIntoConstraints="NO" id="5048">
--                                                <rect key="frame" x="18" y="38" width="287" height="18"/>
+-                                                <rect key="frame" x="18" y="38" width="285" height="18"/>
 -                                                <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMinY="YES"/>
 -                                                <buttonCell key="cell" type="check" title="Check for updates automatically" bezelStyle="regularSquare" imagePosition="left" alignment="left" inset="2" id="5066">
 -                                                    <behavior key="behavior" changeContents="YES" doesNotDimImage="YES" lightByContents="YES"/>

```

**Comment by Tatsh** [comment]
Oh. Sorry I realise it's already been done. Cool.

**Pull request merged**
