### PR TITLE
clamav-legacy: version for older systems; clamav: improvements to portfile

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

See commits.

@ballapete I have set you as a maintainer, since there is an old draft of the port by you: https://trac.macports.org/ticket/64613
If you are not interested, please let us know, I will set the port to nomaintainer.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
This is supposed to be non-problematic. (If `clamav` port happens not to like `openssl` PG, I will revert that; the rest for it is cosmetic.)

**Comment by danielluke** [comment]
What does adding the cmake and openssl port groups to the clamav port help with/what problem is it fixing?

**Comment by ballapete** [comment]
No, I am not interested in becoming the maintainer. My life has taken a new direction.

**Comment by barracuda156** [comment]
> What does adding the cmake and openssl port groups to the clamav port help with/what problem is it fixing?

@danielluke `cmake` PG was there already. AFAIU, this is a better way to handle dependencies in these cases, and that is why those PGs were created in the first place.

However no issues whatsoever, if you prefer not to have `openssl` PG in your port, I drop it.
(Technically I only need to add a conflict with `clamav-legacy`. I just saw that lint etc. can be fixed for `clamav`. All that is non-essential to introducing `clamav-legacy`.)

**Comment by barracuda156** [comment]
> No, I am not interested in becoming the maintainer. My life has taken a new direction.

@ballapete Got it, I will set it to nomaintainer then. (Perhaps nothing much to maintain anyway, at least until either Rust is fixed for PPC or `gccrs` can be used instead.)

**Comment by barracuda156** [comment]
@danielluke This commit https://github.com/macports/macports-ports/pull/19052/commits/117b4be7f1102fc722f242605976b2dff5e9d73a has PG stuff and python bump (somehow `legacysupport` bump was missed, despite being mentioned), so just let me know, and we can drop it.

**Comment by danielluke** [comment]
I don't think the openssl portgroup adds any value here (you're right, cmake portgroup is already there), so please remove that change and then I'll approve it. It's harder to read the diffs with the whitespace changes (which I don't think are necessary, but I'm mostly indifferent about). If you've tested on a legacy system with the newer legacysupport portgroup, then I'm OK with updating it (I don't have older systems around to test with).

**Comment by barracuda156** [comment]
@danielluke Give me a minute, I will do this now. Been away from a desktop, sorry for a delay.

**Comment by barracuda156** [comment]
@danielluke I have dropped the commit making PG and python changes to `clamav` (and revbump, since it is not needed now).

Please consider merging, if all is good, or let me know if anything stands to be changed, and I will do accordingly. Thank you for reviewing!

**Comment by danielluke** [comment]
LGTM. Thanks.

**Pull request merged**
