### PR TITLE
libuv: update to 1.44.2

### PR DESCRIPTION
**Pull request by michaelld**
#### Description

libuv: update to 1.44.2

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.6.8 20G725
Xcode 12.3 12C33

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mascguy — APPROVED** [review]
LGTM.

Michael, should we merge as-is, or are you interested in making other changes first?

**Comment by barracuda156** [comment]
> LGTM.

@mascguy My `ppc64` patch got included in the master, so it is redundant. Re over patches I will update next month. Perhaps @evanmiller may confirm if `ppc` build succeeds on Tiger.

**Comment by michaelld** [comment]
@barracuda156 does this PR build for you on any PPC? If so, then let's do the merge. Thx!

**Comment by michaelld** [comment]
@mascguy I wanted to let CI/QA run & also give @kencu & @barracuda156 a chance to test on older OSX. QA/CI here looks good. Once we get some feedback & assuming it's positive then let's merge. If not positive, then we can decide whether to fix first them merge or just merge & fix later. Given these quite old OSX, there won't be a lot of users impacted, but as long as it doesn't take too much time I'm fine with the short delay. I'll merge Monday July 18 if no comment one way or the other.

**Comment by mascguy** [comment]
Builds fine for me, on 10.5 PPC.

**Comment by barracuda156** [comment]
> Builds fine for me, on 10.5 PPC.

@mascguy What about `ppc64`?

**Comment by mascguy** [comment]
> @mascguy What about `ppc64`?

I only have a 32-bit PPC machine, so can't help with that! LOL

**Comment by barracuda156** [comment]
> > @mascguy What about `ppc64`?
> 
> I only have a 32-bit PPC machine, so can't help with that! LOL

Ah, got it. Well, then I’ll test it later, but we should be good. Thank you for checking on 10.5 PPC!

**Comment by barracuda156** [comment]
Just for an update, on 10.6.8 Rosetta `libuv` has built fine. While recognized triple was wrong, apparently it still built correctly.

On my end I still added the following to be on a safe side:
```
platform darwin 10 {
# This is a fix for Rosetta
    if {${build_arch} eq "ppc"} {
        configure.args-append --build=powerpc-apple-darwin10
    }
}
```

**Comment by kencu** [comment]
apologies for not getting back to you about this, Michael… looks like everyone pitched it!

**Pull request merged**
