### PR TITLE
smartmontools: version bump to 7.0

### PR DESCRIPTION
**Pull request by danielluke**
#### Description

Update smartmontools

###### Tested on
macOS 10.14.2 18C54
Xcode 10.1 10B61 

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM.

**Comment by pmetzger** [comment]
@danielluke any thoughts on @RJVB's comment?

**Comment by danielluke** [comment]
> 1. why did you remove `--with-drivedbdir=yes`, did it prove to be redundant?

It's not a valid option for the version 7 configure script.

> 2. it's probably a good idea to add `--with-scriptpath=${prefix}/bin:/usr/bin:/bin`
> 3. I remember we discussed how to handle (future) C++11 support in this code and came up with the snippet below from my personal copy:
> 
> ```
> if {${configure.cxx_stdlib} eq "libstdc++"} {
>     configure.args-append \
>                 --with-cxx11-option=no
> } else {
>     configure.args-append \
>                 --with-cxx11-regex=yes
> }
> ```
> The c++11 regex option is new so I haven't tested it much; the rest is future-proofing for legacy systems that haven't been converted to libc++. And why wouldn't we do that so I'd suggest to add this while we're at it.

Feel free to add changes to this PR before you merge it (or just reject it and apply your own version bump + changes). I just made minimal changes to get the newer version running (so it would correctly detect my new SSD's manufacturer and attributes). I don't have older (unsupported) hosts to test the c++ stuff with.

**Comment by RJVB** [comment]
> > 1. why did you remove `--with-drivedbdir=yes`, did it prove to be redundant?
> 
> It's not a valid option for the version 7 configure script.

It is on my end:
```
> `port work smartmontools`/smartmontools-7.0/configure --help | fgrep drivedbdir
  --with-drivedbdir[=DIR|yes|no]
```


> Feel free to add changes to this PR before you merge it (or just reject it and apply your own version bump + changes). I just made minimal changes to get the newer version running (so it would correctly detect my new SSD's manufacturer and attributes). I don't have older (unsupported) hosts to test the c++ stuff with.

I don't have commit rights so I can't merge anything but maybe I can make changes notwithstanding (?).

I also don't have older hosts that don't have libc++ but
1) they certainly won't support C++11 code
2) the only existing C++11 code (optional; C++11 std::regex instead of POSIX regex) works fine on OS X 10.9 AFAICT.

**Comment by mojca** [comment]
If this requires C++11, just add the `cxx11 1.0` PortGroup, no need for hacks and workarounds.

10.9 supports C++11, so any tests there are not in any way relevant for testing machines where C++11 is not supported out of the box.

**Comment by RJVB** [comment]
You don't seem to get it. There are no hacks, the project itself keeps any current and future C++11 code optional and under control of a configure switch. This could thus be tested easily on any platform by adding that flag plus a CXXFLAG setting that disables C++ support in the compiler. I haven't done that because I trust the developers have (and besides, C++11 support isn't automatic in clang as it is in GCC, at least not on Linux).

My remark about 10.9 is about testing the C++11 code itself; the only such code presently in the project has to be activated explicitly.

As to the cxx11 PortGroup, pardon me if I consider that a "hack and workaround" (no matter how well done) to bring legacy systems up to date, and indeed there is no need for such things if you can tell the build system that you don't have C++11.

**Comment by danielluke** [comment]
> > 1. why did you remove `--with-drivedbdir=yes`, did it prove to be redundant? It's not a valid option for the version 7 configure script.
> It is on my end: ```
> `port work smartmontools`/smartmontools-7.0/configure --help | fgrep drivedbdir
> --with-drivedbdir[=DIR|yes|no] ```

oh, but I didn't remove --with-drivedbdir, I removed --with-drivedb which not a valid configure arg.

> Feel free to add changes to this PR before you merge it (or just reject it and apply your own version bump + changes). I just made minimal changes to get the newer version running (so it would correctly detect my new SSD's manufacturer and attributes). I don't have older (unsupported) hosts to test the c++ stuff with.
> I don't have commit rights so I can't merge anything but maybe I can make changes notwithstanding (?). I also don't have older hosts that don't have libc++ but 1) they certainly won't support C++11 code 2) the only existing C++11 code (optional; C++11 std::regex instead of POSIX regex) works fine on OS X 10.9 AFAICT.

ok, do you want to just make a new PR with the changes that you want to the port?

**Comment by RJVB** [comment]
> oh, but I didn't remove --with-drivedbdir, I removed --with-drivedb which not a valid configure arg.

Oops, my bad (or my glasses), sorry :-/
> 

> ok, do you want to just make a new PR with the changes that you want to the port?

or you could give me write access to your smartmontools-7.0 branch?

**Comment by danielluke** [comment]
> or you could give me write access to your smartmontools-7.0 branch?

I don't think I can (I didn't fork + branch, I just made a branch on the macports-ports repo since I have commit access) - I don't have admin on the macports-ports repo, so I can't add you.

My change is so small, it's probably not worth a lot of effort avoiding reproducing it :)

**Comment by mojca** [comment]
> I just made a branch on the macports-ports repo since I have commit access

Please create your own fork in the future and create a PR from a branch in that one.

**Comment by danielluke** [comment]
@RJVB thoughts? I can just close this and remove my branch and you can make a PR for a version bump + changes you want for your port (or we can merge this and you can make a PR for the additional changes you want). I don't mind either way :)

**Comment by RJVB** [comment]
Go ahead, merge this.

**Pull request merged**
