### PR TITLE
gdal, py-gdal: update to 3.7.0

### PR DESCRIPTION
**Pull request by nilason**
Update GDAL and py-gdal to v 3.7.0 and add +opencl variant to gdal.

In order to limit the need for rebuild the following has been added to this PR:

- Update of PDAL to 2.5.3 (with a patch needed for GDAL 3.7).
- py-gdal: add port to 'select' port group and new 'gdal_select' port
- libgeotiff: make +proj9 default

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6.5 21G531 arm64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by nilason** [comment]
#18587 should preferably be merged before this.

**Comment by nilason** [comment]
Now I added to this PR the changes originally made with #18635.

In addition (!) I had to bump the default `proj` version for `libgeotiff` to be in sync (by default) with other common GIS ports. I ran into (first unexplainable) segfaults.

**Comment by mascguy** [comment]
Since CI has no chance of completing without timeout, I'll make some time to test the update on my various macOS VMs. (It probably won't be feasible to test all of the dependents, but I certainly do have some... and will update them too.)

Might need a day or two to get to it, but will report back when complete. Stay tuned...

**Comment by mascguy** [comment]
It looks like upstream is now publishing `gdal` releases via GitHub, so I eliminated the `master_site`. That also required updating the checksums, as the tarball is gzip-compressed.

Otherwise, everything looks good so far, at least for 10.15. But still need to expand testing for a much wider range of macOS releases.

More to follow, as I make progress.

**Comment by mascguy** [comment]
One minor thing I noticed, for the `py-gdal` ports: There's a `reinplace` warning, related to patching of `setup.cfg`:

```
Warning: reinplace s|\.\./\.\./apps/|/opt/local/bin/| didn't change anything in
/opt/local/var/macports/build/_opt_macports_sources_ports_latest_python_py-gdal/py311-gdal/work/GDAL-3.7.0/setup.cfg
```

But for the new release, `setup.cfg` consists of the following:

```
[egg_info]
tag_build = 
tag_date = 0
```

I also checked `setup.py`, but didn't see an obvious match there either.

Does that reinplace logic need to change, or is now unnecessary in the new release...?

**Comment by nilason** [comment]
> It looks like upstream is now publishing `gdal` releases via GitHub, so I eliminated the `master_site`. That also required updating the checksums, as the tarball is gzip-compressed.

GDAL hasn't moved to GH, but release there __too__.  The official release is on https://download.osgeo.org/gdal/, which is to be preferred. With the xz file we also save some 5 MB.

**Comment by nilason** [comment]
> One minor thing I noticed, for the `py-gdal` ports: There's a `reinplace` warning, related to patching of `setup.cfg`:
> 
> ```
> Warning: reinplace s|\.\./\.\./apps/|/opt/local/bin/| didn't change anything in
> /opt/local/var/macports/build/_opt_macports_sources_ports_latest_python_py-gdal/py311-gdal/work/GDAL-3.7.0/setup.cfg
> ```
> 
> But for the new release, `setup.cfg` consists of the following:
> 
> ```
> [egg_info]
> tag_build = 
> tag_date = 0
> ```
> 
> I also checked `setup.py`, but didn't see an obvious match there either.
> 
> Does that reinplace logic need to change, or is it now unnecessary for the new release...?

To be honest, I saw that one but I choose to only bump the version this time. I didn't explore that one further, looks like it might be safely removed (i.e. the "reinplace") though.

**Comment by mascguy** [comment]
Another issue, albeit one that you aren't responsible for: `OpenSceneGraph` was completely broken:

* The patch for OpenEXR 3 didn't work
* The Cxx standard wasn't being set by CMake

Pushed fixes for those too. Still testing...

**Comment by mascguy** [comment]
> GDAL hasn't moved to GH, but release there **too**. The official release is on https://download.osgeo.org/gdal/, which is to be preferred. With the xz file we also save some 5 MB.

Fair enough, I restored that.

**Review by mascguy — APPROVED** [review]
LGTM based on local testing

**Comment by nilason** [comment]
@mascguy Thanks a lot for your time and effort on this!

**Comment by mascguy** [comment]
> @mascguy Thanks a lot for your time and effort on this!

My pleasure. And thank you for your contribution!

**Pull request merged**
