### PR TITLE
mlt-qt5: fix for mlt 6.8.0

### PR DESCRIPTION
**Pull request by RJVB**
###### Type(s)
- [x ] bugfix

###### Tested on
Mac OS X 10.9.5
Xcode 6.2

### CODE REVIEW

**Comment by raimue** [comment]
Sorry, I do not feel competent to review this as I have no experience with the qt5 port group or mlt.

**Comment by pmetzger** [comment]
@raimue Who do you think would be a reasonable reviewer?

**Comment by raimue** [comment]
Do we need another review? The port is maintained by the submitter @RJVB. Unless @ddennedy as co-maintainer wants to intervene, I would accept this as it is.

**Comment by pmetzger** [comment]
@raimue Well, mostly the rationale is I don't like getting yelled at by various parties when I merge something particularly complicated that I don't fully understand. If you would click the button, though, it would obviate this problem. 😃

**Pull request merged**
