### PR TITLE
salt: fix hardcoded PREFIX in patch

### PR DESCRIPTION
**Pull request by l2dy**

### CODE REVIEW

**Comment by ryandesign** [comment]
Doesn't the `revision` need to be increased? The setup.cfg file doesn't get installed, but it looks like the paths set in it get baked into the installed file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/salt/_syspaths.py.

**Comment by l2dy** [comment]
@ryandesign With the default prefix, I don't think any file installed by the port would change.

**Comment by ryandesign** [comment]
Correct. What about for a non-default prefix?

**Comment by l2dy** [comment]
I see. `revision` incremented.

**Pull request merged**
