### PR TITLE
R: switch to clang-16 and gcc13

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Let us finally move everything to using new clangs and gcc. This is desirable for better support of C++17 (more R packages explicitly ask for it) and to avoid a need to build an extra gcc.

I did verify rebuilding quite a number of R packages locally now (using C, C++ and Fortran) on Sonoma; I have also been using gcc13 with R stuff for quite a while on my PPC systems.
So yes, this is reasonably tested.

P. S. Since even if clang-17 is allowed, clang-16 is what is actually picked, I use the latter. (We want to retain control over exact compiler from R side.)

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.1.1
Xcode 15.0.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
@barracuda156 my reading of [Trac ticket 68355](https://trac.macports.org/ticket/68355) from the comments by @jmroot and @ryandesign is to NOT do what your suggesting here, relbuilding all R packages.

**Comment by barracuda156** [comment]
@cjones051073 Chris, I think our conclusion from the last time was that revbumping is in fact necessary, we just detach it from centralized Macports settings and control via PG.

@reneeotten While no revbump was done last time when Fortran setting was changed, Chris has rebuilt all packages on buildbots. With clang changes, many more stuff will be broken, AFAIU; there is a ticket discussing that, referenced in the PG.

P. S. If you insist on no revbump, sure, I will drop that commit, but I take no responsibility then if that results in a disaster :)

**Comment by barracuda156** [comment]
@jmroot That is the whole point. We need to switch R ports to use new clang and new gcc.
It is not because of R compiler change, but vice versa.

**Comment by jmroot** [comment]
I remember a mass build of R modules being done because so many had failed to build previously. The problem is not one of binary compatibility, but just of specifying the right build-time dependencies.

Of course the best solution would be to make R use the compiler that we specify when building modules.

**Comment by barracuda156** [comment]
@jmroot That is already done: for this reason we have settings in R PG and R itself synchronized. Same compilers are being used now.

**Comment by barracuda156** [comment]
So anyway, let it be, I have dropped revbumping packages now.

**Comment by jmroot** [comment]
> @jmroot That is already done: for this reason we have settings in R PG and R itself synchronized. Same compilers are being used now.

Yes, I know. That's why there's no problem. :)

> If you are sure that only build-time deps matter, okay, I gonna drop revbumping packages and only change settings.

It's easy enough to prove me wrong: demonstrate runtime breakage when using the updated R built with the new compiler and an R package that was built with the old compiler.

**Comment by barracuda156** [comment]
@jmroot Let us assume everything works, until, if at all, something fails.

P. S. This should be good to merge then.

**Comment by barracuda156** [comment]
@reneeotten Unless there are any objections from anyone, let’s merge this.

**Comment by barracuda156** [comment]
@jmroot This issue gonna be there:
```
svacchanda@Sergeys-MacBook-Air ~ % sudo port -v install R-caracas 
Error: R-cluster: Variant gcc12 conflicts with gcc13
Error: Unable to open port: Error evaluating variants
Error: Unable to execute port: upgrade R-magrittr failed
```

**Comment by pmetzger** [comment]
I am not going to merge until there seems to be strong consensus and someone explicitly says to merge.

**Comment by barracuda156** [comment]
@jmroot We have arrived to the existing implementation with Chris @cjones051073 – and we did/do have the same problem with mismatching variants (+gfortran vs +gcc12).

It is a bug, IMO, but rather on Macports side: instead of just erring out, it should offer to rebuild specific ports that are affected without a user being required to do it via manual trickery of `--enforce-variants`.

> I'm surprised that these ports offer compiler variants, given the whole having to compile with the same compiler as R thing.

The problem is the following: we need Fortran for a number of R packages, and Fortran in Macports is provided by GCC, while compiler for C/C++ is set to be Clang (I do find this inconsistent, but this is out of scope of this discussion). If we let R port and R PG use general Macports settings, then whenever those are changed, we get a disaster with R, which was described in the ticket referenced above. So that does not work.
What did work was a) blacklisting clangs newer than a chosen one and b) specifying an exact gfortran via gcc version (counterintuitively, +gccX in fact means +gfortranX).

However, due to Macports [mis]handling of these variants, every time Fortran setting is changed, we get a conflict. Obviously, we cannot remain stuck with gcc12 indefinitely, so the problem has to be addressed somehow – or we have to accept variant conflicts.

(All this could be avoided perhaps by simply using GCC instead of Clang, but we have what we have.)

I am open to suggestions here, if you have any, to improve the existing set-up. What is required is to maintain control over compilers choice separate from general Macports settings and being able to change those from R side. The rest is flexible.

**Comment by szhorvat** [comment]
> we need Fortran for a number of R packages, and Fortran in Macports is provided by GCC, while compiler for C/C++ is set to be Clang (I do find this inconsistent, but this is out of scope of this discussion)

Nothing wrong with using clang + gfortran. CRAN's official R distribution does precisely that.

**Comment by barracuda156** [comment]
@szhorvat I did not say it is wrong – it obviously works, after all – but it introduces extra complications.

**Comment by barracuda156** [comment]
> That certainly looks like a bug, but rev bumping everything won't fix it, since the installed variants will just be preserved when users upgrade.

@jmroot I think, default variants are enforced. And then revbumping does fix the issue.

**Comment by barracuda156** [comment]
@jmroot I can confirm that revbumping does help and variant is in fact enforced. Example:

```
svacchanda@Sergeys-MacBook-Air ~ % sudo port -v install R-matsbyname
Error: R-Hmisc: Variant gcc12 conflicts with gcc13
Error: Unable to open port: Error evaluating variants
Error: Unable to execute port: upgrade R-RCLabels failed
```
This happens because R PG is set to use gfortran13, while R-Hmisc was not rebuilt.
I manually edit its portfile to revbump it and run the same command:
```
svacchanda@Sergeys-MacBook-Air ~ % bbedit `port file R-Hmisc`
svacchanda@Sergeys-MacBook-Air ~ % sudo port -v install R-matsbyname
--->  Computing dependencies for R-Hmisc.
--->  Fetching archive for R-Hmisc
--->  R-Hmisc-5.1-1_2+gcc13.darwin_23.arm64.tbz2 doesn't seem to exist in /opt/local/var/macports/incoming/verified
--->  Attempting to fetch R-Hmisc-5.1-1_2+gcc13.darwin_23.arm64.tbz2 from http://jog.id.packages.macports.org/macports/packages/R-Hmisc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   168    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
--->  Attempting to fetch R-Hmisc-5.1-1_2+gcc13.darwin_23.arm64.tbz2 from https://packages.macports.org/R-Hmisc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   126    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
--->  Attempting to fetch R-Hmisc-5.1-1_2+gcc13.darwin_23.arm64.tbz2 from https://pek.cn.packages.macports.org/macports/packages/R-Hmisc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   153    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
--->  Fetching distfiles for R-Hmisc
```
As you can see, now it works.

This should be easily reproducible.

**Comment by jmroot** [comment]
> It is a bug, IMO, but rather on Macports side: instead of just erring out, it should offer to rebuild specific ports that are affected without a user being required to do it via manual trickery of `--enforce-variants`.

It is most certainly a bug in the ports (most likely in one of the portgroups they use, I guess.) If you offer conflicting variants, you must not set one of them in default_variants if another is already set. https://trac.macports.org/wiki/PortfileRecipes#default_variants

Otherwise you get an error even when doing something as simple as this:
```
% port info R-cluster +gcc13
Error: R-cluster: Variant gcc12 conflicts with gcc13
Error: Unable to open port: Error evaluating variants
```

> > I'm surprised that these ports offer compiler variants, given the whole having to compile with the same compiler as R thing.
> 
> The problem is the following: we need Fortran for a number of R packages, and Fortran in Macports is provided by GCC, while compiler for C/C++ is set to be Clang (I do find this inconsistent, but this is out of scope of this discussion). If we let R port and R PG use general Macports settings, then whenever those are changed, we get a disaster with R, which was described in the ticket referenced above. So that does not work. What did work was a) blacklisting clangs newer than a chosen one and b) specifying an exact gfortran via gcc version (counterintuitively, +gccX in fact means +gfortranX).

So it sounds like you don't want to offer variants at all but just use a specific pair of compilers all the time. Using the compilers portgroup is antithetical to this, since its purpose is to offer a choice of compilers. So you might be better off just setting configure.compiler to an appropriate clang, adding a dependency on an appropriate gcc, and setting configure.fc and friends to the corresponding gfortran path.

I understand the portgroup takes care of figuring out what the usable compilers are on each OS version, but it doesn't look like it would be too complicated to split out if you only care about using the latest possible compiler on older OSes. If you feel you need to keep using the portgroup, I believe there is a syntax you can use with compilers.setup to restrict the compilers it offers.

If for some reason you really want to keep offering multiple compiler variants, you at least need to use the active_variants portgroup or set compilers.enforce_fortran and/or compilers.enforce_c so that users get an error if they try to install with a different variant than R.

**Comment by jmroot** [comment]
> @jmroot No, default variants are enforced. And therefore revbumping does fix the issue.

And if a user chose a variant explicitly?

**Comment by barracuda156** [comment]
@jmroot Well, it must be possible to rewrite the needed implementation manually, dropping compilers PG, but what do we gain, avoiding once-a-year revbump? At the cost of more complicated code. (And we will still need to revbump now in order to drop the PG, I guess.)

To be clear, I am not opposing the idea, rather wanna figure out all relevant details prior to making such a radical change to the set-up which currently works fine.

One more consideration, which is not relevant right now, but likely will be, possibly soon: it is desirable to be able to use LLVM `flang` for Fortran on aarch64 and Intel as a non-default option (and eventually also `lfortran`). These are not currently supported in Macports compilers PG, but it makes sense to support them. With this in mind, throwing away a mechanism to choose a specific Fortran from a user side may not be the optimal solution.

**Comment by jmroot** [comment]
> @jmroot Well, it must be possible to rewrite the needed implementation manually, dropping compilers PG, but what do we gain, avoiding once-a-year revbump? At the cost of more complicated code. (And we will still need to revbump now in order to drop the PG, I guess.)

Avoiding a huge use of build resources seems like reason enough to me. And no, you don't need to rev bump to drop the portgroup.

I don't know that the compiler selection code would actually be all that complicated, but if it is, another option would be to split out the knowledge of which gccs work on which OS into a separate portgroup.

> One more consideration, which is not relevant right now, but likely will be, possibly soon: it is desirable to be able to use LLVM `flang` for Fortran on aarch64 and Intel as a non-default option (and eventually also `lfortran`). These are not currently supported in Macports compilers PG, but it makes sense to support them. With this in mind, throwing away a mechanism to choose a specific Fortran from a user side may not be the optimal solution.

Possibly, though I don't think choosing a non-default variant for these ports is a very attractive choice, given that at best it means you won't be able to use binaries for any of them. If flang becomes a clearly better choice, it can become the default.

> > And if a user chose a variant explicitly?
> 
> This should be fixed on PG side, not R side, I think. _Is there a way to do this?_

I'm sure there is, but I'm not very familiar with the internals of the compilers portgroup and honestly would prefer to keep it that way.

**Comment by barracuda156** [comment]
@jmroot Ok, let me think of a way to switch away from compilers PG for R and handle everything internally.

(For `flang` and `lfortran` that can be added into R PG if desired after all, and for that I will not need to bother about a more general compilers PG.)

**Comment by barracuda156** [comment]
I will close this for now, since a) there is no urgency, this is not a bug fix, but an improvement; b) no point to have in hanging, I will make a new PR when I write a non-PG-based re-implementation.

**Pull request closed without merging**
