### PR TITLE
polyml: Fix build for arm64 and Mac OS <= 10.9

### PR DESCRIPTION
**Pull request by pclayton**
#### Description

Some MacPorts builders failed to build Poly/ML because
1. configure did not recognized 'arm64' (it was expecting 'arm')
https://github.com/polyml/polyml/issues/165

2. Mac OS <= 10.9 did not have the included header file 'mach-o/arm64/reloc.h'
https://github.com/polyml/polyml/issues/166

This branch addresses these issues with patches based on [upstream fixes](https://github.com/polyml/polyml/tree/MacPorts).

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.10.5 14F2511 x86_64
Xcode 6.2 6C131e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?  No, port doesn't have tests enabled.
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
LGTM. But I'd like to hear @kencu's thoughts, given some of the tweaks.

**Comment by pclayton** [comment]
@mascguy, thanks for looking at this.  Is there anything I could clarify relating to your concerns?

**Comment by mascguy** [comment]
Seems reasonable. Let's merge, and we can always refine later if necessary.

And thanks for your contribution!

**Comment by ryandesign** [comment]
We should avoid committing enormous patchfiles like the one that updates config.guess / config.sub. It would be simpler and more space-efficient to have the port use autoreconf. Enormous files stay in the git history forever so it is important to consider whether that is the best solution before they ever get merged to master.

The other patch patches both configure and configure.ac. You should either patch the generated files (configure) if you are not running auto(re)conf, or patch the source files (configure.ac et al) if you are running auto(re)conf. By patching both, and specifically by patching the source files after the generated files, a race condition can occur whereby if configure is patched in one second and configure.ac is not patched until the next second, the build system will think configure is out of date and will regenerate it, which might have unintended consequences.

**Comment by pclayton** [comment]
Good point about autoreconf, that may well have resolved that issue.

I agree that only one of configure.ac and configure should have been patched.  As the port isn't running auto(re)conf and configure.ac isn't used, presumably there is no potential for the race condition to occur and the port doesn't need to be updated?

**Pull request merged**
