### PR TITLE
rust, rust-bootstrap, cargo: update versions

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by MarcusCalhoun-Lopez** [comment]
This update will fail on older systems until https://github.com/macports/macports-legacy-support/pull/79 finds its way into MacPorts.

**Comment by eirnym** [comment]
@MarcusCalhoun-Lopez could you please update to the [current stable](https://releases.rs/) 1.77.0?

**Review by eirnym — APPROVED** [review]
Update to the current stable 1.77.0

**Review by eirnym — CHANGES_REQUESTED** [review]
could you please update to the [current stable](https://releases.rs/) 1.77.0?

**Comment by MarcusCalhoun-Lopez** [comment]
> could you please update to the [current stable](https://releases.rs/) 1.77.0?

Thank you for pointing this out.
Update the Rust port is not too difficult, but maintaining support for older systems is quite time-consuming.
It seems that by the time I finish an update, a new version has been released.

**Comment by herbygillot** [comment]
> Update the Rust port is not too difficult, but maintaining support for older systems is quite time-consuming. It seems that by the time I finish an update, a new version has been released.

I've been thinking that it might make sense to have a separate `rust-official` port that runs as close to the purely vanilla version of Rust for newer supported macOS versions and use the current Rust port only for older systems.

This would make it so much easier to keep Rust as close to the current release version as possible.

**Comment by eirnym** [comment]
Can we tell that for older systems we hold the rust versions as it has been done in other ports?

**Comment by herbygillot** [comment]
> Can we tell that for older systems we hold the rust versions as it has been done in other ports?

That depends on how it gets implemented.  The usual approach is a version split depending on a given macOS version - you can see an example of this in the `go` port.

If we were to do a separate `rust-official` port, we'd probably have to have some logic such as version information shared in a portgroup, probably.

**Comment by herbygillot** [comment]
> > could you please update to the [current stable](https://releases.rs/) 1.77.0?
> 
> Thank you for pointing this out. Update the Rust port is not too difficult, but maintaining support for older systems is quite time-consuming. It seems that by the time I finish an update, a new version has been released.

Rust just updated again to 1.77.1 😆

**Comment by eirnym** [comment]
@herbygillot Your logic makes sense, and both of our approaches can be implemented at once.

**Comment by MarcusCalhoun-Lopez** [comment]
While it is certainly a good idea to get the MacPorts Rust version released sooner after upstream release, maintaining another Rust port (e.g., `rust-official`) seems daunting as there is already `rust`, `rust-bootstrap`, `rust-bootstrap-10.7`, `rust-bootstrap-10.6`, `rust-bootstrap-10.5`, `rust-bootstrap-transition`, `rust-1.0.tcl`, `rust_build-1.0.tcl`, and `cargo-1.0.tcl`.

Another approach is to try to build the various rust-bootstrap subports on newer machines.
This would certainly expedite the process of updating rust while still supporting older systems.

**Comment by MarcusCalhoun-Lopez** [comment]
> Rust just updated again to 1.77.1 😆

Thank you for pointing this out.
The pull request should now be updated.

This PR will fail on older systems until https://github.com/macports/macports-legacy-support/pull/81 makes it into a released version.

**Comment by eirnym** [comment]
@MarcusCalhoun-Lopez finally PR you mentioned has been merged

**Comment by herbygillot** [comment]
> @MarcusCalhoun-Lopez finally PR you mentioned has been merged. Could you push this PR as well?

That PR has been merged, but the port for `legacy-support` needs to be updated to make it available to Rust.

**Comment by mascguy** [comment]
> > Rust just updated again to 1.77.1 😆
> 
> Thank you for pointing this out. The pull request should now be updated.
> 
> This PR will fail on older systems until [macports/macports-legacy-support#81](https://github.com/macports/macports-legacy-support/pull/81) makes it into a released version.

While the fix in PR 81 wasn't specifically called out in the release notes, it is included in the latest release of `legacy-support`.

So if that's the final hurdle, we should be good-to-go at this point.

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
Marcus, I'll let you merge at your convenience, but LGTM.

**Comment by herbygillot** [comment]
Thank you very much @MarcusCalhoun-Lopez, @mascguy & @eirnym.

Rust updates feel like such endeavors these days 😅

**Comment by dyne2meter** [comment]
I've successfully updated rust to 1.77.1 on 10.14, building and installing on my own system. Are there plans to release a binary download? Or are rust updates released so frequently that it would be jumping the gun for this version of the OS? Binary releases were available to me on 10.11 and 10.13.

**Comment by herbygillot** [comment]
> I've successfully updated rust to 1.77.1 on 10.14, building and installing on my own system. Are there plans to release a binary download? Or are rust updates released so frequently that it would be jumping the gun for this version of the OS? Binary releases were available to me on 10.11 and 10.13.

When a port is updated, the MacPort buildbots build and create the binary archives for the port across each macOS version.

Using https://ports.macports.org/, you can see the build status for a port across each buildbot in the "Builds" tab.

Here's the one for Rust: https://ports.macports.org/port/rust/builds/

**Pull request merged**
