### PR TITLE
R: third batch of new R-packages

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

New ports.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

macOS 10A190
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by herbygillot** [comment]
This branch is too large to be merged through Github.

**Comment by barracuda156** [comment]
> This branch is too large to be merged through Github.

@herbygillot I can drop a few commits. Is there a way for me to know beforehand what is the may? Like, last time 40 commits were okay.

**Comment by barracuda156** [comment]
Or should I rather squash commits and make it `New R packages`?

It the limit for commit number, lines of code or what in particular?

**Comment by herbygillot** [comment]
I think leave as-is for now and I will commit manually.

**Comment by barracuda156** [comment]
> I think leave as-is for now and I will commit manually.

@herbygillot Okay, thank you, and sorry for this.

With next one, batch 4, I will try squashing into 1 commit then after checks pass. Given that every commit amounts to introduction of a new port within the same category, perhaps still acceptable.

**Comment by herbygillot** [comment]
Please don't squash - MacPorts guidelines prefer each new port be its own commit. This PR is fine, if not for limitations with GitHub.

**Comment by barracuda156** [comment]
> Please don't squash - MacPorts guidelines prefer each new port be its own commit. This PR is fine, if not for limitations with GitHub.

Ok, got it. Then next one I will make with 30 ports in 30 commits. We will need a bit more PRs, but then hopefully without a hassle of manual merging.

**Comment by herbygillot** [comment]
The branch for this PR has been merged to master.

**Comment by barracuda156** [comment]
@herbygillot Thank you!

**Pull request closed without merging**
