### PR TITLE
qt*-qttranslations: remove qttools dependency

### PR DESCRIPTION
**Pull request by catap**
#### Description

qttranslations is a port which contains only .qm files; this ports is runtime dependency for near of all Qt-based applications like wireshark. qttools depends on clang because qdoc uses it to parce C++ files. That makes wireshark to depends on clang via qttranslations.

Fixed this insanity.

###### Type(s)

- [x] bugfix

###### Tested on

macOS 12.6 21G115 x86_64
Xcode 14.1 14B47b

as removing `qt*-qttools` and running `LC_ALL=ru_RU open /Applications/MacPorts/Wireshark.app` and `LC_ALL=de_DE open /Applications/MacPorts/Wireshark.app` to confirm that different locales are working.

and as `port build qt5-qttranslations` and `port build qt6-qttranslations` to confirm that build dependency to `qttools` is required and working.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by MarcusCalhoun-Lopez** [comment]
Please forgive me for not commenting on this pull request sooner.
Doesn't the revision of each `qttranslations` need to be increased since a dependency goes from library to build?

**Comment by catap** [comment]
@MarcusCalhoun-Lopez np, anyway you have raised a good question.

This commit helps me to avoid dependency without any revbump. So, I really not sure about that. Base on https://guide.macports.org/#reference.keywords I think that it should be merged without increase dependency because library dependency is useless for that case.

**Comment by MarcusCalhoun-Lopez** [comment]
My understanding is that a revision increase is warranted because the port is changed on the user's machine.
E.g., `port uninstall qt5-qttools` would behave differently for users who installed qt5-qttranslations before and after the change.

**Comment by catap** [comment]
Ok, let’s be on the safe side of the moon.

I’ll bump revisions in couple hours when I’ll be back to the computer

**Comment by catap** [comment]
@MarcusCalhoun-Lopez here it is

**Comment by MarcusCalhoun-Lopez** [comment]
Thank you.

**Pull request merged**
