### PR TITLE
audacity 2.3.2

### PR DESCRIPTION
**Pull request by mojca**
#### Description

This would be part of #5653, but as it's a bit more massive change, I'm opening a draft PR first.

The work is based on changes by @RJVB, but I updated to the latest development version from git and tried to make sure that all the patches apply cleanly, so I made some semi-redundant copies of the patches. Plus some other changes.

When building the development version one of the steps fails to find some wxWidgets headers, I still need to look into it.

I'll take another look in the evening when I come back.

I also have a massive wxWidgets patch from Audacity, but I need a bit more time for that.

@ra1nb0w 

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by RJVB** [comment]
>The work is based on changes by @RJVB, but I updated to the latest development version from git

I presume that applies to the -devel port? Did you change anything that I really need to look at in the release port? Either way I'll wait until the -devel port builds again ;)

>and tried to make sure that all the patches apply cleanly, so I made some semi-redundant copies of the patches. Plus some other changes.

FWIW, I found some maintainer files for doing patch maintenance using quilt ("patchwork", hah hah) in `port dir openssh`, which should ease the workload of rewriting patchfiles to apply cleanly. The only drawback is that you lose all "decoration", like commit headers and even the `git --diff` lines used by certain editors to fold the different hunks and pieces.

**Comment by mojca** [comment]
>> The work is based on changes by @RJVB, but I updated to the latest development version from git
> I presume that applies to the -devel port?

Yes.

> Did you change anything that I really need to look at in the release port?

No, I don't think there's anything that needs a special attention. I don't particularly like the way patches are duplicated now, but to be honest I don't like the fact that we need to have patches, to start with. I also now removed dependency on wx 3.0 completely, I assume that upstream tested that to a sufficient extest, but I expect to potentially need it back for older OSes.

But one thing that I would be particularly grateful for is a more verbose description of the individual patches, in case someone asks why those are there, and to potentially simplify the upstreaming process. This can as well be done in your own repository. If you have some time before Tuesday, that would be ideal, but even if done later, it would still be helpful.

I've noticed that at least two of your patches have been applied after you last tested the development version, so I removed those.

**Comment by RJVB** [comment]
>But one thing that I would be particularly grateful for is a more verbose description of the individual patches, in case someone asks why those are there, and to potentially simplify the upstreaming process. This can as well be done in your own repository. If you have some time before Tuesday, that would be ideal, but even if done later, it would still be helpful.

A priori I will not have time for that tomorrow, sadly, but I will try to do it when I get around to upgrading the port.

>I've noticed that at least two of your patches have been applied after you last tested the development version, so I removed those.

Yeah, I noticed that too today when I decided to update the Linux version of the -devel port

**Comment by mojca** [comment]
This first fails with a wxWidgets issue, but when I fix that one, it fails with
```
effects/audiounits/AUControl.mm:80:4: error: no matching constructor for initialization of 'wxWidgetCocoaImpl'
:  wxWidgetCocoaImpl(peer, view, false, false)
   ^                 ~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.1/include/wx-3.1/wx/osx/cocoa/private.h:53:5: note: candidate constructor not viable: requires at most 3 arguments, but 4 were provided
    wxWidgetCocoaImpl( wxWindowMac* peer , WXWidget w, int flags = 0 ) ;
    ^
```
which seems related (or at least it comes from the same "private" sector), I need to look into it. There seem to be further wxWidgets-only problems.

**Comment by ra1nb0w** [comment]
> /opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.1/include/wx-3.1/wx/osx/cocoa/private.h:53:5: note: candidate constructor not viable: requires at most 3 arguments, but 4 were provided

API change, now the definition is
```
wxWidgetCocoaImpl( wxWindowMac* peer , WXWidget w, int flags = 0 ) ;
```
https://github.com/wxWidgets/wxWidgets/commit/e5e6ee7e776c8d0d4e739974152d7af2c147c7ee

**Comment by kencu** [comment]
I'm looking to kill off ancient PRs that aren't going anywhere -- is this one?

**Comment by RJVB** [comment]
I cannot answer for Mojca evidently but I can offer the observation that she's been MIA for a while now. She hasn't been responding to my messages about my own, independent upgrade to the current Audicity version.

I'd file a PR for that but I've been building Audacity against a wxWidgets-3.1 port that is a snapshot of the 3.2 beta with which Audacity still worked back then. I've been suggesting to add that port at least temporarily for Audacity's sake, but I've never had any feedback on that.

**Comment by mojca** [comment]
I have a bit of a hard time keeping up, and I'm aware that I still need to come back to the numerous tickets, and those from @RJVB in particular.

I would assume that Rene's work to use CMake for the latest Audacity version supersedes this one (not that Audacidy devs had time to provide compatibility with wx 3.1.3).

**Comment by RJVB** [comment]
Good to hear from you, continued silence in the current context could have meant all kinds of things ...

>I would assume that Rene's work to use CMake for the latest Audacity version supersedes this one 

Probably, yes. I was silently if not secretly hoping you'd test my changes and then incorporate them one way or another (though I had forgotten about this PR).

Would it be an alternative to drop back to building against wxWidgets-3.0 if compatibility with a more recent release is still an issue and my idea of a more-or-less temporary 3.1.2 port (3.1.2.916 to be exact) isn't an option either?

I've been using the -devel build (2.3.3.1029) for recording purposes and it works just fine. Of course I'm doing only relatively simple things so I can't say I notice anything different w.r.t. previous versions.

Now, about CMake and PRs that aren't going anywhere; has anyone noticed the CMake PortGroup PR I put up last week or so?

**Comment by kencu** [comment]
let's close this -- this PR is not going anywhere

**Comment by RJVB** [comment]
On Friday October 02 2020 21:07:20 Ken wrote:
>let's close this -- this PR is not going anywhere

Indeed. I see I'm behind as usual, upstream is at 2.4.2 - and given I've helped setting up a cmake build system that's bound to make things easier.

Any news on/from Mojca?!

**Comment by ra1nb0w** [comment]
@RJVB do you have the time to update to the latest version and then we merge the update? have an old port is not to much useful..

**Comment by kencu** [comment]
a movin' PR is my friend! Get 'er going if you can!

**Comment by RJVB** [comment]
My own version of the port is newer (2.3.3 ATM, 2.4.2.459 for the -devel port). Two obstacles to updating:

- what wxWidgets version to use? I'm using the latest 3.1.x from git that did not give problems; I even made (and suggested) an actual port:wxWidgets-3.1 port for Audacity but I think that was just before Mojca fell off the radar. It hasn't been picked up on, and with Mojca missing I have stopped following wx developments and testing Audacity against it too. I'd need to check what version Audacity suggests, but moving back to wxW 3.0 feels a bit like a regression to me.
- what version of Audacity? Do we stick with 2.3.x or move to 2.4.x which introduces a new, sqlite3-based file format and drops write support for the old format? IOW, recordings made in 2.4.x cannot (easily) be imported in 2.3.x .

**Comment by ra1nb0w** [comment]
> - what wxWidgets version to use? 

wxWidgets-3.2 port

> - what version of Audacity?

stay with the latest stable shown in the Audacity site, so 2.4.2. If there will be issue we can also add audacity-legacy.

**Comment by RJVB** [comment]
>> - what wxWidgets version to use? 
>
>wxWidgets-3.2 port

Last time I tried that did NOT work so I'll probably stick with 3.0 .

>stay with the latest stable shown in the Audacity site, so 2.4.2. If there will be issue we can also add audacity-legacy.

I'll take that under advisement, but I'm more inclined to stick to 2.3.3 and provide 2.4.2.x in the -devel subport. I have made an upstream request to include some option (export option or converter utility) to bring back compatibility with with 2.3.3 and earlier. I don't condone how they stripped out all write support for the old format and even pointed out I was likely to keep my port at the current stable version (2.3.3).

**Comment by ra1nb0w** [comment]
>  It does work with my stock wxWidgets-3.1 port (v3.1.2.916).

So, it should work with macports's wxWidgets-3.2 (3.1.4)

> I'll take that under advisement, but I'm more inclined to stick to 2.3.3 and provide 2.4.2.x

I generally prefer to simplify and avoid user confusion this is why I said 2.4 (also because it is the version shown in the official site). Moreover, maintaining two ports it is always a pain if not strictly required.

**Comment by RJVB** [comment]
>So, it should work with macports's wxWidgets-3.2 (3.1.4)

Not certain at all. As I said, it did not with a version between (almost) 3.1.3 and the then-HEAD. IIRC I spend a lot of time patching Audacity and then ran into runtime errors. There's an exchange about that on one of the PRs (audacity or wxWidgets), and it's why I proposed to make a (possibly temporary) wxWidgets-3.1 port.
wxWidgets isn't too long to build but I'm not going to spend hours patching Audacity this time.

> Moreover, maintaining two ports it is always a pain if not strictly required.

I am already doing that...

**Comment by ra1nb0w** [comment]
> Not certain at all. As I said, it did not with a version between (almost) 3.1.3 and the then-HEAD. 

This will be very confusing and annoying from my point of view. Why they are not supporting the latest stable releases? Since they support ARM64 and better integration with macOS.

> Moreover, maintaining two ports it is always a pain if not strictly required.
> I am already doing that...

Yes, but it is confusing for the user and many times if they see an older version than upstream they think that we are not up to date and start to download the DMG.

**Comment by RJVB** [comment]
>This will be very confusing and annoying from my point of view. Why they are not supporting the latest stable releases? Since they support ARM64 and better integration with macOS.

Ask them. And if this sort is confusing and annoying you (which I can understand, the continuous update-for-updatings-sake dance annoys the heck out of me too) then maybe you should just stay out of it?

>Yes, but it is confusing for the user and many times if they see an older version than upstream they think that we are not up to date and start to download the DMG.

So what? MacPorts is not about competition with official releases.

**Comment by ra1nb0w** [comment]
> Ask them. And if this sort is confusing and annoying you (which I can understand, the continuous update-for-updatings-sake dance annoys the heck out of me too) then maybe you should just stay out of it?

It is consistency. I see that debian (unstable) is using `wxgtk3.0.5.1` with audacity-2.4.2 without out-of-tree patches.
Do you have link to the build issue?
Maybe, I should update wxWidgets-3.0.

> So what? MacPorts is not about competition with official releases.

Nobody said competition. it is only user perspective.

**Comment by RJVB** [comment]
On Friday January 15 2021 03:39:50 ra1nb0w wrote:

>Do you have link to the build issue?

The one I had? No, I just reported on it in one of the tickets where updating audacity or wxWidgets was discussed.

I had those issues with the Linux versions of my ports. Now, with wxWidgets 3.1.4.667 (HEAD) and audacity 2.4.2.543 (HEAD) the initial impression (again on Linux) is that things work OK. I do get some strange error messages and bogus warnings about a recovered project but I cannot be certain those are due to wxWidgets. I'll be trying to repeat these experiments on my Mac.

>Maybe, I should update wxWidgets-3.0.

That would never hurt.

BTW, it was clear during my exchange about the file format support regression (my assessment) that 2.4.2 is in fact an in-between release before 3.0.0 which serves just to introduce the new file format, internal cleanup, a new build system and misc. bug fixes. That's the other basis for my opinion that it makes sense to ship 2.4.x.y via audacity-devel and keep the main port on the actual stable release, 2.3.3 .

**Comment by ra1nb0w** [comment]
> I'll be trying to repeat these experiments on my Mac.

Ok. report back your test.

> That would never hurt. BTW, it was clear during my exchange about the file format support regression (my assessment) that 2.4.2 is in fact an in-between release before 3.0.0 which serves just to introduce the new file format, internal cleanup, a new build system and misc. bug fixes. That's the other basis for my opinion that it makes sense to ship 2.4.x.y via audacity-devel and keep the main port on the actual stable release, 2.3.3 .

These make sense.

**Comment by RJVB** [comment]
>Ok. report back your test.

To be exhaustive I installed the latest wxWidgets that doesn't require 10.10 (v3.1.3-1300-gc7f77afbf4). I had a little run-in with the fact that somewhere after 3.1.3 wx stops adding the private frameworks (= its own dependencies) to the required library list (because that isn't actually necessary on OS X). But the basic features seem to work. I cannot of course speak for long-term runtime stability, but if that becomes an issue the only option might be to consider adding audacity's wx patches to the wxWidgets port, as a build variant. Or, if *that* interferes with other dependent ports I could see with the audacity devs to integrate an option to build a private wxWidgets library from within the audacity cmake build system. wxWidgets can also be built via cmake (my own wxWidgets ports uses that), which should simplify integration.

I'll be syncing the "official" audacity port to mine as soon as I get the chance. I suppose github won't allow me to commandeer this PR, rather than creating a new one?

**Comment by ra1nb0w** [comment]
One thing at time :) if there will be issue we will see..

Yes, you need open a new PR

**Pull request closed without merging**
