### PR TITLE
jikesrvm: delete port

### PR DESCRIPTION
**Pull request by chrstphrchvz**
**Proposing that this port be deleted rather than fixed/updated. Please leave open long enough for discussion.**

Port has not been updated since 2004, and fails to build. No dependents.

Closes: https://trac.macports.org/ticket/35659

#### Description

This port has been known to be broken for several years. The upstream project is fairly dormant and last had a release in 2016.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

### CODE REVIEW

**Comment by pmetzger** [comment]
Seems reasonable to me.

**Comment by mf2k** [comment]
I'm against this. It should be (attempted to) updated first.

**Comment by pmetzger** [comment]
@mf2k But who uses it? I suspect no one.

**Comment by chrstphrchvz** [comment]
Closing for now since there is not a consensus to remove this.

**Pull request closed without merging**
