### PR TITLE
atomvm: bump epoch due to unrecognized update and mbedtls3 API change

### PR DESCRIPTION
**Pull request by barracuda156**
Due to a recent mbedtls3 update, revbump is required. However, going from 0.6.0-beta.1 to 0.6.0 is seen as a version downgrade by Macports, and revbumping does not solve that. Instead, bump epoch, solves both issues.

#### Description

Bump epoch.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by pguyot — APPROVED** [review]

**Comment by ryandesign** [comment]
Both the epoch and revision need to be increased, each for their own reasons:

The atomvm 0.6.0 update was March 5. The buildbot built binaries of that version then and users could have installed it from source or from binary then. You're right that MacPorts considers 0.6.0 to be less than 0.6.0-beta.1 so users who had the previous version installed will not be notified via `port outdated` that a new version exists, therefore the epoch needs to be increased. The epoch has higher precedence than the version so it should be listed before the version.

The mbedtls3 3.6.0 update was March 29. This did indeed increase the major versions and thus the install names of its libraries so everything linking with it including atomvm needs its revision increased. Otherwise, if you just increase the epoch, you'll be pushing the March 5 binaries out to everybody, which are not built for the March 29 version of mbedtls3.

**Comment by barracuda156** [comment]
@ryandesign Done

**Comment by pguyot** [comment]
@ryandesign thanks. Should we also consider fixing the comparison function so that `0.6.0` is greater than `0.6.0-beta.1`?

**Comment by barracuda156** [comment]
> @ryandesign thanks. Should we also consider fixing the comparison function so that `0.6.0` is greater than `0.6.0-beta.1`?

This does not have to be done here, I guess, though. Maybe open an issue on Trac?

**Comment by ryandesign** [comment]
> Should we also consider fixing the comparison function so that `0.6.0` is greater than `0.6.0-beta.1`?

I doubt any changes to the comparison function could be made at this late stage. It's been the way it is for 20 years so changing it now would probably break the assumptions made in several ports and/or base.

**Comment by pguyot** [comment]
> > Should we also consider fixing the comparison function so that `0.6.0` is greater than `0.6.0-beta.1`?
> 
> I doubt any changes to the comparison function could be made at this late stage. It's been the way it is for 20 years so changing it now would probably break the assumptions made in several ports and/or base.

Ugh, I realize how old the project is and found with some nostalgia that my first commit is indeed 20 years old '-(

I didn't mean to have this conversation here, this is definitely unrelated to this PR which is the way to fix it for now, and I see your point. Yet I am a little bit frustrated by this comparison function, especially when using livecheck. I'll give it more thought and if I succeed to convince myself there is something to do, I'll open a conversation elsewhere.

**Pull request merged**
