### PR TITLE
yq: documentation & completion

### PR DESCRIPTION
**Pull request by danchr**
#### Description

Partly inspired by the Debian rules, which also include a manual page and the license file. While at it, I also added shell completion and the bundled examples.

I included a patch to suppress an issue where showing the manual which trigger a warning:

    $ man yq
    This manpage is not compatible with mandoc(1) and might display incorrectly.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by herbygillot** [comment]
It looks like the `depends_build` statement you added for `pandoc` is overwriting the one implicitly set by the `golang` portgroup.

Try changing it to `depends_build-append`.

**Comment by mascguy** [comment]
> It looks like the `depends_build` statement you added for `pandoc` is overwriting the one implicitly set by the `golang` portgroup.
> 
> Try changing it to `depends_build-append`.

Yep, this explains why `go` isn't being found:

```
sh: /opt/local/bin/go: No such file or directory
```

**Comment by danchr** [comment]
> It looks like the `depends_build` statement you added for `pandoc` is overwriting the one implicitly set by the `golang` portgroup.
> 
> Try changing it to `depends_build-append`.

Ah, sorry, what a rookie mistake 😁 Fixed!

**Comment by mascguy** [comment]
It looks like the binaries for `pandoc` may be stale:

```
dyld[3845]: Library not loaded: /opt/local/lib/libz.1.dylib

Referenced from: /opt/local/bin/pandoc
```

**Comment by herbygillot** [comment]
> It looks like the binaries for `pandoc` may be stale:
> 
> ```
> dyld[3845]: Library not loaded: /opt/local/lib/libz.1.dylib
> 
> Referenced from: /opt/local/bin/pandoc
> ```

This looks like `pandoc` needs an explicit dependency listed for `zlib`, which it currently doesn't have: https://ports.macports.org/port/pandoc/details/

**Comment by danchr** [comment]
Oddly enough, the build still fails on macOS 14? 🤔

**Comment by herbygillot** [comment]
> Oddly enough, the build still fails on macOS 14? 🤔

I think we're still seeing issues with `pandoc`, unfortunately.

**Pull request merged**
