### PR TITLE
coreutils{,-devel}, m4: avoid a patch to overstep max path bug; ncurses, gettext: avoid max path bug on macOS 10.5

### PR DESCRIPTION
**Pull request by catap**
#### Description

This is is much more stright forward way to overstep that bug that makes supporting it much easy.

Half year ago I've tried to sent it to upstream, but hasn't been successful, but still we may enjoy it as an easy workaround

See: https://trac.macports.org/ticket/62994
See: https://lists.gnu.org/r/bug-gnulib/2022-09/msg00045.html

###### Type(s)

- [x] bugfix

###### Tested on

macOS 10.5.8 9L34 i386
Xcode 3.1.4 9M2809

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mascguy — APPROVED** [review]
LGTM, much cleaner and simpler than patches. Glad this is an option!

@ryandesign ?

**Comment by catap** [comment]
@mascguy and much easy to move to another portfiles if it required ;)

**Comment by catap** [comment]
I've just catch one more port which requires such hack: ncurses

**Review by kencu — APPROVED** [review]

**Comment by ryandesign** [comment]
I'm sad to hear that the developers of gnulib have been uninterested in fixing this problem. It sounds like they disagree that this test result should be overridden in this way. However, if you are sure that it should always have this value on macOS, then overriding it seems reasonable to me.

**Comment by mascguy** [comment]
@jmroot Josh, any concerns relative to `ncurses`?

**Comment by kencu** [comment]
the developers of gnulib asked that the test program be fixed, and gave some examples how to go about doing that.

But nobody responded to them.

**Pull request merged**
