### PR TITLE
cmake: Use clang_dependency PG

### PR DESCRIPTION
**Pull request by cjones051073**
Switch cmake port to use clang_dependency PG.

### CODE REVIEW

**Comment by cjones051073** [comment]
@kencu FYI

**Comment by cjones051073** [comment]
Yeah sorry. Was my intention to leave it until you commented, but seems @kencu hit go on it himself...

**Comment by michaelld** [comment]
Thanks, @cjones051073 ... Luckily it's generally not a big deal. This one definitely isn't a big deal at all. And I do trust y'all to do the right thing. It's more me finding it humo[u]rous than anything else ... I mean, I think most MP folks know by now that I don't work much on the weekends, and so to have low expectations of me getting to anything until Monday sometime.

**Comment by cjones051073** [comment]
no problem. By the book, the port is not openmaintainer so really @kencu should not have merged it until either getting your go ahead, or waiting for the maintainer timeout... @kencu I know you know what you are doing, and yes the changes here are 'minor', but still we should not by-pass the rules ;)

**Comment by kencu** [comment]
Just seemed such a terribly-low-lying-obvious-get-it-done-thing I frankly could not resist saving Michael the button-push. But you're around a lot, and ...

**Pull request merged**
