### PR TITLE
opencv3: update to 3.4.14; fix paths in pkgconfig

### PR DESCRIPTION
**Pull request by mascguy**
#### Description

* Update opencv3 to 3.4.14
* Fix paths in generated pkgconfig

Fixes: https://trac.macports.org/ticket/62462
Fixes: https://trac.macports.org/ticket/61908

###### Type(s)
- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.12.6 16G2136
Xcode 9.2 9C40b

macOS 10.13.6 17G14019
Xcode 10.1 10B61

macOS 10.14.6 18G103
Xcode 11.3.1 11C505

macOS 10.15.6 19G2021
Xcode 12.0 12A7209

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Reviewers: You may want to hide whitespace changes when reviewing the diff.

**Comment by mascguy** [comment]
I'm not sure why, but the Big Sur CI job was cancelled for whatever reason. Otherwise, it looks like the CI jobs have passed.

**Comment by cjones051073** [comment]
Yeah, the macOS11 CI seems to be doing this a lot at the moment..

**Comment by mascguy** [comment]
Thanks Chris!

**Pull request merged**
