### PR TITLE
metapixel: patch for libpng 1.5+, add license

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Patch suggested in https://trac.macports.org/ticket/38753

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.4 18E226
Xcode 10.2 10E125 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
I have also opened a port abandoned ticket for this port: https://trac.macports.org/ticket/58303

**Comment by cjones051073** [comment]
Patch seems quite extensive. Is this something that has been discussed with upstream ?

**Comment by chrstphrchvz** [comment]
>Patch seems quite extensive. Is this something that has been discussed with upstream ?

Yes, the patch author filed an issue: https://github.com/schani/metapixel/issues/1 which has since been resolved in its repository.

I guess the question is now whether a new Metapixel release will ever be published (current developer wants someone to adopt it): https://github.com/schani/metapixel/issues/8

**Comment by cjones051073** [comment]
OK, I am happy to now merge this under maintainer timeout.

**Pull request merged**
