### PR TITLE
wolfssl: update to 5.0.0

### PR DESCRIPTION
**Pull request by JacobBarthelmeh**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [x] security fix

###### Tested on

macOS 10.15.7
Xcode 12.4

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
I note that the putative maintainer does not have a Github ID in the portfile, which may mean that they aren't really maintaining this any longer. @JacobBarthelmeh you should manually alert them to your pull request.

**Comment by JacobBarthelmeh** [comment]
@pmetzger noted, will contact my co-worker Chris. If updating it to myself as the maintainer can I make that commit directly to this PR? I see now the formmating of the maintier from docs to be this:

```
maintainers         @neverpanic \
                    jdoe \
                    example.org:julesverne
```

**Comment by pmetzger** [comment]
Merging for now as we're past timeout.

That's not the maintainer format we now use. Typically we now have lines of the form

```
maintainers         {example.com:foo @foo} openmaintainer
```

where each maintainer has their email address and their github handle listed between `{}` for grouping.

**Comment by pmetzger** [comment]
(And feel free to submit a pull request to update the docs!)

**Comment by ryandesign** [comment]
This commit changed the wolfssl major library version number from 24 to 30, so you must increase the revision of all ports that could link with wolfssl to rebuild them.

**Comment by JacobBarthelmeh** [comment]
@pmetzger @ryandesign sure could add that in. Just to make sure I understand, does this mean adding a line in just the wolfSSL Portfile with something along the lines "revision 1". Or is this with searching through all of macports for Portfiles that depend on wolfSSL and updating their revision number.

**Comment by pmetzger** [comment]
The latter. grep for all portfiles that specify a dependency on WolfSSL and bump the revisions in them. It should be possible to script this.

**Pull request merged**
