### PR TITLE
db-browser-for-sqlite: move symlink creation into post-destroot, add c++11 to build

### PR DESCRIPTION
**Pull request by i0ntempest**
#### Description
Closes: https://trac.macports.org/ticket/60551
Closes: https://trac.macports.org/ticket/60552

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.4 19E287
Xcode 11.5 11E608c

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
The changes here do not I am afraid fix the problems I address with the compiler blacklist. See my last comment to https://trac.macports.org/ticket/60552

**Comment by cjones051073** [comment]
For some other reason is failing on 10.11 ...

https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/114837/steps/install-port/logs/stdio

**Comment by i0ntempest** [comment]
How?? CI build on 10.11 was successful...

**Comment by cjones051073** [comment]
It can happen I am afraid. You'll need to delve into the logs above to figure out how.

**Pull request merged**
