### PR TITLE
draco, tinygltf: new ports

### PR DESCRIPTION
**Pull request by nilason**
#### Description

Add new ports:

- `draco` version 1.5.6
   3D data compression library: https://google.github.io/draco/
- `tinygltf` version 2.8.17
   Header only C++11 tiny glTF 2.0 library: https://github.com/syoyo/tinygltf

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.6 22G120 arm64
Xcode 15.0 15A240d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
Can you use `github.tarball_from archive`?  You can add this after `github.setup`.  You will need to adjust the checksums because they will differ.  The `github` portgroup uses legacy download links for downloading assets from Github projects by default, and `github.tarball_from archive` makes the portgroup use more modern archive URLs for downloading assets.

**Comment by nilason** [comment]
> Can you use `github.tarball_from archive`? You can add this after `github.setup`. You will need to adjust the checksums because they will differ. The `github` portgroup uses legacy download URLs for downloading assets from Github projects by default, and `github.tarball_from archive` makes the portgroup use more modern archive URLs for downloading assets.

Both ports can download from "archive", now fixed.

**Comment by herbygillot** [comment]
Thanks @nilason.

**Comment by nilason** [comment]
@herbygillot Thank you!

**Pull request merged**
