### PR TITLE
dotnet-8: new set of ports

### PR DESCRIPTION
**Pull request by silverbzez**
#### Description

dotnet-8: runtime verison 8.0.0; sdk version 8.0.100

`port lint --nitpick` is known to fail because `${dotnet_manifest_version}` is the same as `${version}`.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.1.1 23B81 arm64
Command Line Tools 15.0.0.0.1.1694021235

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by judaew — APPROVED** [review]
LGTM

**Comment by judaew** [comment]
Are there any .NET versions in development for dotnet-devel port? If not, could you please add a note to dotnet-devel indicating that dotnet-8 currently has a newer version?

**Comment by silverbzez** [comment]
> Are there any .NET versions in development for `dotnet-devel` port? If not, could you please add a note to `dotnet-devel` indicating that `dotnet-8` currently has a newer version?

Sure, what about marking `dotnet-devel` as `obsolete` and `replaced_by` `dotnet-8`?

**Comment by silverbzez** [comment]
> marking `dotnet-devel` as `obsolete` and `replaced_by` `dotnet-8`

@judaew done! would you please give it a look?

**Comment by judaew** [comment]
I think it's not worth marking as obsoleted, since this port will come in handy in the future when a new version comes out.

**Comment by silverbzez** [comment]
> I think it's not worth marking as obsoleted, since this port will come in handy in the future when a new version comes out.

Isn't that re-doable? Once a new version comes out we can just remove the obsolete mark?


> add a note to `dotnet-devel` indicating that `dotnet-8` currently has a newer version

So the wording will be like:
".NET 8 has become a steady version so please use the ${port_name} instead. The maintenance of this port will be suspended until a new preview version is released."

**Comment by judaew** [comment]
> Isn't that re-doable? Once a new version comes out we can just remove the obsolete mark?

I don't know obsoleted PG logic and don't know if there will be problems for re-doable in the future. I think the notes are enough, considering that this port will be needed in the future. Good wording for a note, thank you ❤️

**Review by judaew — APPROVED** [review]
Thank you 🌟

**Pull request merged**
