### PR TITLE
imager: new port, version 202309

### PR DESCRIPTION
**Pull request by PenguenJulien**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by PenguenJulien** [comment]
Changes have been made, can you run the checks again? thanks

**Comment by mascguy** [comment]
> Changes have been made, can you run the checks again? thanks

One minor fix was needed, which was to remove `use_xz yes`. (Simply because there is no `.xz` archive on the site, only `.gz`.) Let's see how it looks with that update.

**Comment by mascguy** [comment]
> One minor fix was needed, which was to remove `use_xz yes`. (Simply because there is no `.xz` archive on the site, only `.gz`.)

A few other minor fixes were needed, but took care of them for you:
* Checksums needed to be updated
* `worksrcdir` needed to be set to the name of the extracted archive

Looks better now, let's see whether it builds.

**Comment by mascguy** [comment]
Making progress, but it looks like the build is failing with a link error:

```
Undefined symbols for architecture x86_64:
  "_sfftw_destroy_plan_", referenced from:
      _fourt_plan_ in fourt.o
  "_sfftw_execute_dft_", referenced from:
      _fourt_ in fourt.o
  "_sfftw_plan_dft_", referenced from:
      _fourt_plan_ in fourt.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by mascguy** [comment]
> Making progress, but it looks like the build is failing with a link error:
> 
> ```
> Undefined symbols for architecture x86_64:
>   "_sfftw_destroy_plan_", referenced from:
>       _fourt_plan_ in fourt.o
>   "_sfftw_execute_dft_", referenced from:
>       _fourt_ in fourt.o
>   "_sfftw_plan_dft_", referenced from:
>       _fourt_plan_ in fourt.o
> ld: symbol(s) not found for architecture x86_64
> ```

@kencu and @jmroot, could use some hints/help with this PR, as my knowledge of everything Fortran-related is superficial at best. As for the current state of things:

While the portfile originally lacked a lib dep for `fftw-3`, that has since been rectified. But the link error still occurs.

Locally I'm able to reproduce the issue via trace mode, though there's no apparent port/item referenced which would explain the problem. (And the build succeeds without trace mode.)

Can you kind souls help with this one?

**Comment by jmroot** [comment]
Given the `s` prefix in the symbol I would guess it wants `fftw-3-single`?

**Comment by mascguy** [comment]
> Given the `s` prefix in the symbol I would guess it wants `fftw-3-single`?

Geez, it's that easy? Great to know, thank you so much Josh!

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
Looks good now, thank you so much for your contribution!

**Comment by PenguenJulien** [comment]
Wonderful! thank you all for your contributions!

**Pull request merged**
