### PR TITLE
libcerror: update to 20220101

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
@mascguy Could you please take a look and this PR and friends? No maintainer. Should be non-controversial – simple version updates.

**Comment by mascguy** [comment]
> @mascguy Could you please take a look and this PR and friends? No maintainer. Should be non-controversial – simple version updates.

Well, there are a few caveats:
* Given that all of the other `libcXXX` ports depend on this, they should all be updated via one PR.
* For each, you'll want to include a 2nd line for the commit message, referencing this ticket:
  - [54839 - Checksum mismatches for generated tarballs from GitHub](https://trac.macports.org/ticket/54839)
* If there are build issues with any of these ports, you'll be responsible for fixing ASAP.

**Comment by barracuda156** [comment]
> > @mascguy Could you please take a look and this PR and friends? No maintainer. Should be non-controversial – simple version updates.
> 
> Well, there are a few caveats:
> 
> * Given that all of the other `libcXXX` ports depend on this, they should all be updated via one PR.
> * For each, you'll want to include a 2nd line for the commit message, referencing this ticket:
>   
>   * [54839 - Checksum mismatches for generated tarballs from GitHub](https://trac.macports.org/ticket/54839)
> * If there are build issues with any of these ports, you'll be responsible for fixing ASAP.

Ok, I will deal with this.

**Comment by mascguy** [comment]
Depending on how comfortable you are with Git, this should be relatively quick-and-easy: It's simply a matter of adding the commits from the other branches. To avoid issues, you'll probably want to do that via `git cherry-pick`, rather than merging each.

After that's been done, you can quickly reword each commit message, via an interactive rebase: `git rebase -i <your-first-commit>`.

If you're already up-to-speed on all of this, then no worries!

**Comment by mascguy** [comment]
Based on the current state of your repo, the workflow would look like like:

```
$ git switch libcerror
$ git cherry-pick --commit 0d54e92802cd8a2924dc20c5352851d7c72a8d0c
$ git cherry-pick --commit 414ec028dde03c396de1fe53195ccf29278bd9f1
$ git cherry-pick --commit 043009618870608f52e1141160a7bcb9f572c527
$ git cherry-pick --commit 05d16868815fcd218a90a4c81fd056a64fc1f4e9
$ git cherry-pick --commit 58eac504f151f4f3299e4b1cadfd0beefe2b387c
$ git cherry-pick --commit e3a3f52275b0dbe580fc4d1e96767af270612b8b
$ git cherry-pick --commit c58615c96ee5a04e85b33a76f7493c6c58c90ffa
$ git rebase -i f5076ce61367121369cdf212b5efa10538e15fb5
```

**Comment by barracuda156** [comment]
@mascguy TBH `git` is confusing for me, haha, but I will find a way to add commits to this PR.

Is this problem still relevant? https://trac.macports.org/ticket/54839
Maybe just move these ports to use tags normally instead of releases.

**Comment by mascguy** [comment]
> Is this problem still relevant? https://trac.macports.org/ticket/54839 Maybe just move these ports to use tags normally instead of releases.

Most likely, as these ports haven't been updated in years.

If you're not super-comfortable with Git, then don't worry about updating the commit messages. Simply run the `git cherry-pick` commands I provided earlier, and then push.

Once this has been merged, we can manually update the ticket.

**Comment by barracuda156** [comment]
> If you're not super-comfortable with Git, then don't worry about updating the commit messages. Simply run the `git cherry-pick` commands I provided earlier, and then push.
> 
> Once this has been merged, we can manually update the ticket.

@mascguy Done! Thank you.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
