### PR TITLE
libvpx, libvpx-devel: fix portfile code that breaks destroot on PPC

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

When a fix for dylib was added, PPC case was not considered; since on PPC only static lib is built, dylib fix breaks destroot on PPC. Obviously, it should not be used on PPC at all.
PR also improves arch-related syntax in portfile.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

macOS 10A190
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
Please allow me a bit of time, strangely enough, but on two PPC systems I get a failure now at linking:
```
/opt/local/bin/g++-mp-11 -L/opt/local/lib -Wl,-headerpad_max_install_names -m32 -Wl,-syslibroot,/ -o test_intra_pred_speed md5_utils.c.o test/test_intra_pred_speed.cc.o -L. -lvpx -lgtest -lpthread -lm -lpthread
Undefined symbols:
  "_vpx_highbd_v_predictor_8x8_c", referenced from:
      __ZZN27C_TestHighbdIntraPred8_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d207_predictor_8x8_c", referenced from:
      __ZZN27C_TestHighbdIntraPred8_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d63_predictor_16x16_c", referenced from:
      __ZZN28C_TestHighbdIntraPred16_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_dc_left_predictor_16x16_c", referenced from:
      __ZZN28C_TestHighbdIntraPred16_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_dc_predictor_8x8_c", referenced from:
      __ZZN27C_TestHighbdIntraPred8_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d63_predictor_8x8_c", referenced from:
      __ZZN27C_TestHighbdIntraPred8_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_dc_top_predictor_8x8_c", referenced from:
      __ZZN27C_TestHighbdIntraPred8_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_dc_128_predictor_4x4_c", referenced from:
      __ZZN27C_TestHighbdIntraPred4_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d45_predictor_16x16_c", referenced from:
      __ZZN28C_TestHighbdIntraPred16_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d153_predictor_8x8_c", referenced from:
      __ZZN27C_TestHighbdIntraPred8_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_tm_predictor_4x4_c", referenced from:
      __ZZN27C_TestHighbdIntraPred4_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_dc_top_predictor_16x16_c", referenced from:
      __ZZN28C_TestHighbdIntraPred16_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_h_predictor_4x4_c", referenced from:
      __ZZN27C_TestHighbdIntraPred4_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_dc_predictor_16x16_c", referenced from:
      __ZZN28C_TestHighbdIntraPred16_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d207_predictor_16x16_c", referenced from:
      __ZZN28C_TestHighbdIntraPred16_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d63_predictor_32x32_c", referenced from:
      __ZZN28C_TestHighbdIntraPred32_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_dc_left_predictor_32x32_c", referenced from:
      __ZZN28C_TestHighbdIntraPred32_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_v_predictor_4x4_c", referenced from:
      __ZZN27C_TestHighbdIntraPred4_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d153_predictor_16x16_c", referenced from:
      __ZZN28C_TestHighbdIntraPred16_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_dc_left_predictor_8x8_c", referenced from:
      __ZZN27C_TestHighbdIntraPred8_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_v_predictor_16x16_c", referenced from:
      __ZZN28C_TestHighbdIntraPred16_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d207_predictor_4x4_c", referenced from:
      __ZZN27C_TestHighbdIntraPred4_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d45_predictor_8x8_c", referenced from:
      __ZZN27C_TestHighbdIntraPred8_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_dc_128_predictor_16x16_c", referenced from:
      __ZZN28C_TestHighbdIntraPred16_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d45_predictor_32x32_c", referenced from:
      __ZZN28C_TestHighbdIntraPred32_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d135_predictor_16x16_c", referenced from:
      __ZZN28C_TestHighbdIntraPred16_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d135_predictor_8x8_c", referenced from:
      __ZZN27C_TestHighbdIntraPred8_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_dc_predictor_4x4_c", referenced from:
      __ZZN27C_TestHighbdIntraPred4_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d63_predictor_4x4_c", referenced from:
      __ZZN27C_TestHighbdIntraPred4_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_dc_top_predictor_4x4_c", referenced from:
      __ZZN27C_TestHighbdIntraPred4_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_dc_top_predictor_32x32_c", referenced from:
      __ZZN28C_TestHighbdIntraPred32_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_h_predictor_16x16_c", referenced from:
      __ZZN28C_TestHighbdIntraPred16_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d117_predictor_16x16_c", referenced from:
      __ZZN28C_TestHighbdIntraPred16_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d153_predictor_4x4_c", referenced from:
      __ZZN27C_TestHighbdIntraPred4_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_dc_predictor_32x32_c", referenced from:
      __ZZN28C_TestHighbdIntraPred32_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d207_predictor_32x32_c", referenced from:
      __ZZN28C_TestHighbdIntraPred32_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_ppc_simd_caps", referenced from:
      _setup_rtcd_internal in libvpx.a(vpx_scale_rtcd.c.o)
      _setup_rtcd_internal in libvpx.a(rtcd.c.o)
      _setup_rtcd_internal in libvpx.a(vp9_rtcd.c.o)
      _setup_rtcd_internal in libvpx.a(vpx_dsp_rtcd.c.o)
  "_vpx_highbd_tm_predictor_16x16_c", referenced from:
      __ZZN28C_TestHighbdIntraPred16_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d153_predictor_32x32_c", referenced from:
      __ZZN28C_TestHighbdIntraPred32_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_v_predictor_32x32_c", referenced from:
      __ZZN28C_TestHighbdIntraPred32_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_dc_128_predictor_32x32_c", referenced from:
      __ZZN28C_TestHighbdIntraPred32_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d117_predictor_8x8_c", referenced from:
      __ZZN27C_TestHighbdIntraPred8_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d135_predictor_32x32_c", referenced from:
      __ZZN28C_TestHighbdIntraPred32_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_dc_left_predictor_4x4_c", referenced from:
      __ZZN27C_TestHighbdIntraPred4_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d45_predictor_4x4_c", referenced from:
      __ZZN27C_TestHighbdIntraPred4_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_h_predictor_32x32_c", referenced from:
      __ZZN28C_TestHighbdIntraPred32_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d117_predictor_32x32_c", referenced from:
      __ZZN28C_TestHighbdIntraPred32_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d135_predictor_4x4_c", referenced from:
      __ZZN27C_TestHighbdIntraPred4_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_dc_128_predictor_8x8_c", referenced from:
      __ZZN27C_TestHighbdIntraPred8_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_tm_predictor_32x32_c", referenced from:
      __ZZN28C_TestHighbdIntraPred32_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_tm_predictor_8x8_c", referenced from:
      __ZZN27C_TestHighbdIntraPred8_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_h_predictor_8x8_c", referenced from:
      __ZZN27C_TestHighbdIntraPred8_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
  "_vpx_highbd_d117_predictor_4x4_c", referenced from:
      __ZZN27C_TestHighbdIntraPred4_Test8TestBodyEvE14vpx_intra_pred in test_intra_pred_speed.cc.o
ld: symbol(s) not found
collect2: error: ld returned 1 exit status
make[1]: *** [test_intra_pred_speed] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [.DEFAULT] Error 2
```
It has built on two other PPC systems earlier (same `libvpx` version). I do not understand what is going on yet.
All problematic symbols are from one single test file, `test_intra_pred_speed`, and one group of tests in it.

**Comment by barracuda156** [comment]
UPD. Okay, I have no idea why it fails on one system while built on another (either some non-obvious differences with `ld64` or GCC, or could be I had a fix locally which I forgot to add into PR), but I have fixed it now.
The change concerns only PPC and makes static linking work correctly. (Shared has been disabled earlier and remains disabled.)

**Comment by barracuda156** [comment]
Rebased to the current master.

**Comment by barracuda156** [comment]
@reneeotten @harens @herbygillot Is it possible to verify this, amend if anything needed, and merge? Now one of new ports that I added, `toxcore`, depends on `libvpx`, and the latter remains broken in master.

**Comment by barracuda156** [comment]
@reneeotten @harens @herbygillot Bump, we need this fix :)

**Comment by kencu** [comment]
none of those folks have a PPC system to check this, and you're building and testing with gcc11 on 10.6-for-PPC which is not MacPorts default setup, so most of your systems are not PPC standard.

Give me a few minutes to see if it builds properly on a MacPorts' standard setup, PPC Leopard.

**Comment by kencu** [comment]
OK, well is similarly does not build the dylibs on a standard PowerPC Darwin Leopard system, so at least that is confirmed.

The issue is libvpx doesn't have a target for ```powerpc-darwin-*``` in configure, and so it recognizes the system as ```generic-gnu.``` ```generic-gnu``` is not known to be a target that supports shared libraries, so the build sets ```--disable-shared```.

libvpx is famous for doing a lot of it's own target assessment. We've had to fix this port many times before for this issue. We will need to get it to recognize powerpc-darwin-* as a system, and then perhaps upstream that fix.

**Comment by barracuda156** [comment]
@kencu To be clear, I do not care whether _my_ PR is merged or not, I just want the port to be fixed, and it is broken for months now, and no one cares -_-

Sure enough, I would love to see it fixed for `powerpc-darwin*` target, but I do not have time to deal with that – Altivec is not something I understand well, and fixing `libvpx` _a bit better_ is not good enough motivation to read IBM manuals in hope that helps. In fact, we do not even know whether that ever worked correctly.

**Comment by kencu** [comment]
yes, I saw the last hack, and I left more info in the ticket. There are multiple places this same issue is discussed, unfortunately.

I don't think it would be too accurate to say "no one cares--_-"; after all, I'm here trying to clean up the mess and avoid more of a mess right now.... although WHY I am bothering to try to clean this up is a rather good question, I guess...

More accurate would be that no one wants to see one hack piled upon another hack, all as one never-ending pile of cards, until the situation becomes unmaintainable, so they await someone to fix it properly.

If we get dylibs being made instead of static libs, and if the port builds the same on Leopard Intel and Leopard PPC, then that is close enough to maintainable. 

Anything else is a gawdawful mess.

**Comment by kencu** [comment]
> (P. S. And yeah, obviously this has nothing to do with 10.6 PPC, as 99,99% of PPC issues.)

10.6 PPC has SDK definitions and base assumptions for 10.6, and toolchain and system parts that are essentially 10.5. So any errors that might be noted there have to be confirmed on a stock 10.5 PPC system to see if they are reproducible there.

**Comment by barracuda156** [comment]
> > (P. S. And yeah, obviously this has nothing to do with 10.6 PPC, as 99,99% of PPC issues.)
> 
> 
> 
> 10.6 PPC has SDK definitions and base assumptions for 10.6, and toolchain and system parts that are essentially 10.5. So any errors that might be noted there have to be confirmed on a stock 10.5 PPC system to see if they are reproducible there.

10.6.8 Rosetta is just as good for that purpose: assumptions match with SDK.

**Comment by kencu** [comment]
10.6.8 Rosetta builds often default to x86_64, and use base constructs for 10.6 which mostly assume Intel arch on that OS, so it is not a reliable testbed for the “supported” 10.5 PPC.

But enough tangents…. let’s see if we can get libvpx fixed properly here.

**Comment by kencu** [comment]
OK, wasn't too hard to fix, in the end. Builds dylibs and static libs, same as on Intel.

It's hard for me to test universal at the moment, and it won't build cross-arch universal as we don't currently have any compiler that can build c++11 or greater cross arch including PPC, but the Portfile logic doesn't have to be adjusted for lack of dylibs I think.

I will put up a PR for this fix, and if it works out on testing, then this PR here can be closed.

```
LeopardG5:~$ port -v installed libvpx
The following ports are currently installed:
  libvpx @1.12.0_0 (active) requested_variants='' platform='darwin 9' archs='ppc' date='2023-02-25T13:35:52-0800'
LeopardG5:~$ port contents libvpx
Port libvpx contains:
  /opt/local/bin/vpxdec
  /opt/local/bin/vpxenc
  /opt/local/include/vpx/vp8.h
  /opt/local/include/vpx/vp8cx.h
  /opt/local/include/vpx/vp8dx.h
  /opt/local/include/vpx/vpx_codec.h
  /opt/local/include/vpx/vpx_decoder.h
  /opt/local/include/vpx/vpx_encoder.h
  /opt/local/include/vpx/vpx_ext_ratectrl.h
  /opt/local/include/vpx/vpx_frame_buffer.h
  /opt/local/include/vpx/vpx_image.h
  /opt/local/include/vpx/vpx_integer.h
  /opt/local/lib/libvpx.7.dylib
  /opt/local/lib/libvpx.a
  /opt/local/lib/libvpx.dylib
  /opt/local/lib/pkgconfig/vpx.pc
```

**Comment by kencu** [comment]
lets see how this plan works out. I'll broaden it to libvpx and revbump the various ports that depend on it a bit later.

c395e1906711e285b0adb248f4fadbb430018813

**Comment by barracuda156** [comment]
@kencu Great, many thanks!

**Pull request closed without merging**
