### PR TITLE
Switch out dead homepage/src download for mail/alpine.

### PR DESCRIPTION
**Pull request by jcvernaleo**
#### Description

Upstream site for alpine is dead.  Switch to new location.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.12
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jcvernaleo** [comment]
Obviously, if someone finds a better place for alpine, I'm happy to go with that.

**Comment by ryandesign** [comment]
Usually when a homepage disappears we use the Internet Archive copy of the page. So:

    homepage https://web.archive.org/web/20170627061225/http://alpine.freeiz.com

**Comment by jcvernaleo** [comment]
Makes sense.  I switched to the archive.org copy of the homepage.

**Comment by ryandesign** [comment]
Please squash the two commits into one so that we can merge this.

**Comment by jcvernaleo** [comment]
@ryandesign squashed and rebased (I'm a big fan of the linear histories like this so I totally understand wanting that).

**Comment by ryandesign** [comment]
Thanks. The commit message should begin with the port name and a colon, so for example:

"alpine: Update homepage and master_sites"

**Comment by jcvernaleo** [comment]
Fixed the commit message.

Sorry about that.  After all my time managing bitrig ports and trying to get people to do PRs correctly for decred I really should know better so no real excuse for not reading the docs from me.

**Comment by ryandesign** [comment]
Thanks!

**Comment by l2dy** [comment]
https://groups.google.com/forum/#!topic/comp.mail.pine/wdnG4X0zFIk
>The official site for the Alpine source code will be the git repository.

http://repo.or.cz/alpine.git

**Pull request merged**
