### PR TITLE
New portfiles: sign windows exe files with USB tokens

### PR DESCRIPTION
**Pull request by nano103**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.11.6 15G22010
Xcode 8.2.1 8C1002 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
Thanks for the update, but please follow the commit guidelines. Commit Comments should take the form ‘portname: description’.

**Comment by mf2k** [comment]
Given the similarity of osslsigncode-devel to the current osslsigncode port, I think you should make it a sub-port of that one.

**Comment by nano103** [comment]
Hello
Sorry I don’t know what sub-port is and unable to gogle it
Initially my idea was to upgrade osslsigncode — they just did not make a tag of 1.8 and as I understand they will not.
 
  
>Среда, 24 апреля 2019, 18:15 +03:00 от Frank Schima <notifications@github.com>:
> 
>Given the similarity of osslsigncode-devel to the current osslsigncode port, I think you should make it a sub-port of that one.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread . 
 
 
--
Gruzdev Andrey

**Comment by mf2k** [comment]
You need to look at another similar port for guidance. You can use the `eigen3/eigen3-devel` portfile as an example.

**Comment by mf2k** [comment]
Basically you add a block for the sub-port with the differences.

```
subport osslsigncode-devel {
    version ...
    etc.
}

```

**Comment by nano103** [comment]
Yes already find it, testing now
thanx
 

  
>Среда, 24 апреля 2019, 18:53 +03:00 от Frank Schima <notifications@github.com>:
> 
>You need to look at another similar port for guidance. You can use the eigen3/eigen3-devel portfile as an example.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread . 
 
 
--
Gruzdev Andrey

**Pull request closed without merging**
