### PR TITLE
py-scipy: update to 1.14.1

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description

PLEASE NOTE: this PR is on top of #26408 as there are several dependents in that PR that are needed for `py-scipy`. The NumPy PR will likely be merged first and then I will rebase this one. Please only focus on the changes related to SciPy here.

- update to latest upstream version
- drop py38, add py313 subport (to py-scipy as well as dependents)
- pin to 1.13.1 for py39 subport
- switch to PyPI
- add BLAS/LAPACK variants
- add myself as co-maintainer
- completely switch to 'meson' as build backend

Closes: https://trac.macports.org/ticket/70931
Closes: https://trac.macports.org/ticket/69538

@barracuda156 @aeiouaeiouaeiouaeiouaeiouaeiou same invitation to test building on older OSes. Please note that we have switched not completely to the `meson` backend; that is what upstream has done and thus not negotiable ;)

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 15.1 24B83 x86_64
Xcode 16.1 16B40

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by Schamschula** [comment]
You have added `py313-pooch`, while not removing `py38-pooch`. The only dependent of the later is `py38-metpy`.

**Comment by reneeotten** [comment]
> You have added `py313-pooch`, while not removing `py38-pooch`. The only dependent of the later is `py38-metpy`.

Yes, exactly as the commit message says 😉

**Comment by barracuda156** [comment]
@reneeotten Is it ready to be tested? (I.e. just verify that the build is not broken on powerpc/gcc.)

**Comment by reneeotten** [comment]
> @reneeotten Is it ready to be tested? (I.e. just verify that the build is not broken on powerpc/gcc.)

Yes, please!

**Comment by barracuda156** [comment]
@reneeotten A similar bug was fixed in Numpy https://github.com/numpy/numpy/issues/25406 earlier, but turns out not in Scipy:
```
Program pythran found: YES 0.17.0 0.17.0 (/opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/pythran)
Found CMake: /opt/local/bin/cmake (3.29.5)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency xsimd found: NO (tried pkgconfig, framework and cmake)
Run-time dependency threads found: YES
Library npymath found: YES
Run-time dependency pybind11 found: YES 2.13.6
Program f2py found: YES (/opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/f2py)

../scipy/meson.build:185:6: ERROR: Command `/usr/bin/xcrun -sdk macosx --show-sdk-version` failed with status 64.

A full log can be found at /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-scipy/py311-scipy/work/scipy-1.14.1/.mesonpy-ecsezsga/meson-logs/meson-log.txt

ERROR Backend subprocess exited when trying to invoke build_wheel
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-scipy/py311-scipy/work/scipy-1.14.1" && /opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 -m build --no-isolation --wheel --outdir /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-scipy/py311-scipy/work -Csetup-args=-Dblas=openblas -Csetup-args=-Dlapack=openblas -Csetup-args=-Dpkg_config_path=/opt/local/lib/pkgconfig 
Exit code: 1
Error: Failed to build py311-scipy: command execution failed
Error: See /opt/local/var/macports/logs/_opt_PPCSnowLeopardPorts_python_py-scipy/py311-scipy/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there
is a bug.
```
Not a big deal to fix, but not today already.

`libflame` updated normally.

**Comment by reneeotten** [comment]
@barracuda156 I attempted to fix the issue you encountered in `scipy/meson.build` but cannot really test it. Please give it a try and if not sufficient, fix the patch as you can test it locally ;)

**Pull request closed without merging**
