### PR TITLE
Remove myself as maintainer for soxr

### PR DESCRIPTION
**Pull request by casr**
I just got 18 emails in 15 minutes from broken builds that I had no say in and I want out.

**/cc** @dbevans

### CODE REVIEW

**Comment by mojca** [comment]
Please change openmaintainer into nomaintainer.

**Comment by kencu** [comment]
I did in a subsequent commit. Based on @casr 's obvious frustration, I just didn't have it in me to ask him to fix up his PR.

**Comment by casr** [comment]
Thank you for taking care of that.

Perhaps wider discussion on what it means to be a maintainer might be useful. Certainly I think the buildbot could do with a tweak that makes it digest emails (either by time or by when all build machines have built to the same HEAD commit)

**Comment by kencu** [comment]
You're right - the current expectation would be to generate a PR for such an update, give the maintainer 72h to accept it, and then go ahead and merge it if there's no feedback, per the openmaintainer policy.

However, Dave is a ultra-super-heavy contributor (hundreds of ports), and this was a minor version update to soxr, so most of us generally would cut him (and other primaries like Ryan, Josh, and a few others) some leeway given the volume he supports. Presumably he had some other port(s) that depended on soxr that he was updating, and didn't want to have to revisit it again after a minor version soxr update. Mostly Dave would have thought he was doing you a favour, if anything.

I noticed homebrew doesn't use the concept of maintainer, so this never comes up there. It's open season on all formulae.

Please don't be frustrated. It was no reflection on your maintainerness -- soxr had only been updated for a couple of days, after all.

**Comment by mojca** [comment]
I didn't follow the updates of soxr, but let me explain (this is probably documented somewhere in the guide).

Making the port "openmaintainer" means that you allow others to do trivial changes to the port. Most of the time changing the version number and checksums counts as a small change (except if version changes has a significant impact on the software, API changes, dependencies etc.). Any major changes need to be confirmed by maintainer. Despite that it is usually polite to ask the maintainer for confirmation, but sometimes I also end up in situation when I want to update one port and that requires  minor changes of perhaps 50 other ports. If I was to wait for confirmation of all the 20+ maintainers and try to track confirmations, it would be a neverending story and lots of additional administrative work before I was able to fix or update something. This might have happened to @dbevans as well, he's the one with a huge number of commits and made nearly 30 commits in a very short time span around soxr.

Regarding the emails from buildbot, I would say "lucky you". I've been wondering myself why I haven't been receiving any emails since just about forever. That's super annoying because it's nearly impossible to track which of your commits didn't make it, in particular when the buildbot is busy at the time of commit. In case you would be willing to help us figure out how to fit the emails into one, that would be awesome. I didn't find any easy way to merge all the feedback into a single email. That said, there could be situations when one buildbot is super busy. Like, 10.5/ppc being super slow and lagging days behind, one of the builders perhaps broken & offline, one of the builders like 10.14 having a few days of builds ahead in order to catch up. If we wanted to wait for all emails to be collected, we would miss valuable quick feedback. Sometimes I get an error report which is quick to fix and can be pushed to other busy builders before they even start building the known-to-be-broken port and just waste a lot of time. So in a way the current situation might be more optimal. Keep in mind that in ideal world there would be no broken builds.

**Comment by casr** [comment]
I just want to make it clear to @dbevans that I wasn't blaming you at all. My gripe was just with the emails.

@mojca on the point about openmaintainer vs nomaintainer, that is good info to know. Thanks! I don't think I have come across that before. And, of course, updating a lot of ports is admin so anything that can speed that up is a good idea.

On the point about email scheduling, I imagined it might work like:

  - first bot finishes, there was an error, send an email straight away, record a time against that email address
  - next bot finishes, check email address for time, if < 15 mins then hold in a queue
  - repeat 2
  - when 15 minute elapses collect all items from the queue and send as one

Of course, introducing that kind of state management can be quite complex to maintain so it is only worth it if enough people feel it brings value.

**Comment by mojca** [comment]
Would you be willing to ask on the buildbot mailing list if this is feasible to implement without too much hassle? Or at least open the topic on the macports-development mailing list since most people will not be reading this.

**Pull request merged**
