### PR TITLE
gnome-terminal: update to 3.38.3

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
@barracuda156 the build fails but also the patches need to be updated as they don't apply cleanly.

**Comment by barracuda156** [comment]
> @barracuda156 the build fails but also the patches need to be updated as they don't apply cleanly. 

Worked fine locally, but I will look into fixing this.

**Comment by reneeotten** [comment]
ping

**Comment by barracuda156** [comment]
> ping

Ok, will try fixing this tonight.

**Comment by barracuda156** [comment]
@reneeotten Well, since the recent `py-setuptools` update has broken GIR scanner (and no one bothers to fix it or at least revert an update), we cannot build anything:
```
FAILED: gst-libs/gst/play/GstPlay-1.0.gir 
env PKG_CONFIG_PATH=/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_gnome_gstreamer1-gst-plugins-bad/gstreamer1-gst-plugins-bad/work/build/meson-uninstalled PKG_CONFIG=/opt/local/bin/pkg-config /opt/local/bin/g-ir-scanner --quiet --no-libtool --namespace=GstPlay --nsversion=1.0 --warn-all --output gst-libs/gst/play/GstPlay-1.0.gir '--add-init-section=extern void gst_init(gint*,gchar**);g_setenv("GST_REGISTRY_1.0", "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_gnome_gstreamer1-gst-plugins-bad/gstreamer1-gst-plugins-bad/work/build/gir_empty_registry.reg", TRUE);g_setenv("GST_PLUGIN_PATH_1_0", "", TRUE);g_setenv("GST_PLUGIN_SYSTEM_PATH_1_0", "", TRUE);gst_init(NULL,NULL);' --quiet -DGST_USE_UNSTABLE_API --c-include=gst/play/play.h -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_gnome_gstreamer1-gst-plugins-bad/gstreamer1-gst-plugins-bad/work/gst-plugins-bad-1.24.7/gst-libs/gst/play -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_gnome_gstreamer1-gst-plugins-bad/gstreamer1-gst-plugins-bad/work/build/gst-libs/gst/play -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_gnome_gstreamer1-gst-plugins-bad/gstreamer1-gst-plugins-bad/work/gst-plugins-bad-1.24.7/. -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_gnome_gstreamer1-gst-plugins-bad/gstreamer1-gst-plugins-bad/work/build/. -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_gnome_gstreamer1-gst-plugins-bad/gstreamer1-gst-plugins-bad/work/gst-plugins-bad-1.24.7/gst-libs -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_gnome_gstreamer1-gst-plugins-bad/gstreamer1-gst-plugins-bad/work/build/gst-libs --filelist=/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_gnome_gstreamer1-gst-plugins-bad/gstreamer1-gst-plugins-bad/work/build/gst-libs/gst/play/libgstplay-1.0.0.dylib.p/GstPlay_1.0_gir_filelist --include=Gst-1.0 --include=GstPbutils-1.0 --include=GstBase-1.0 --include=GstVideo-1.0 --include=GstAudio-1.0 --include=GstTag-1.0 --symbol-prefix=gst --identifier-prefix=Gst --pkg-export=gstreamer-play-1.0 --cflags-begin -DG_DISABLE_CAST_CHECKS -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_gnome_gstreamer1-gst-plugins-bad/gstreamer1-gst-plugins-bad/work/gst-plugins-bad-1.24.7/. -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_gnome_gstreamer1-gst-plugins-bad/gstreamer1-gst-plugins-bad/work/build/. -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_gnome_gstreamer1-gst-plugins-bad/gstreamer1-gst-plugins-bad/work/gst-plugins-bad-1.24.7/gst-libs -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_gnome_gstreamer1-gst-plugins-bad/gstreamer1-gst-plugins-bad/work/build/gst-libs -I/opt/local/include/gstreamer-1.0 -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include/orc-0.4 -I/opt/local/include/gobject-introspection-1.0 -I/opt/local/include --cflags-end --add-include-path=/opt/local/share/gir-1.0 -L/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_gnome_gstreamer1-gst-plugins-bad/gstreamer1-gst-plugins-bad/work/build/gst-libs/gst/play --library gstplay-1.0 -L/opt/local/lib -L/opt/local/lib -L/opt/local/lib -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lgstvideo-1.0 -lgstaudio-1.0 -lgsttag-1.0 -lgstpbutils-1.0 -lgirepository-1.0
Traceback (most recent call last):
  File "/opt/local/bin/g-ir-scanner", line 103, in <module>
    from giscanner.scannermain import scanner_main
  File "/opt/local/lib/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/opt/local/lib/gobject-introspection/giscanner/ast.py", line 29, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/opt/local/lib/gobject-introspection/giscanner/sourcescanner.py", line 25, in <module>
    from .ccompiler import CCompiler
  File "/opt/local/lib/gobject-introspection/giscanner/ccompiler.py", line 29, in <module>
    from distutils.msvccompiler import MSVCCompiler
ModuleNotFoundError: No module named 'distutils.msvccompiler'
[167/1023] /opt/local/bin/orcc --include glib.h --header -o gst/fieldanalysis/gstfieldanalysisorc.h ../gst-plugins-bad-1.24.7/gst/fieldanalysis/gstfieldanalysisorc.orc
[168/1023] /opt/local/bin/orcc --include glib.h --header -o gst/gaudieffects/gstgaudieffectsorc.h ../gst-plugins-bad-1.24.7/gst/gaudieffects/gstgaudieffectsorc.orc
[169/1023] /opt/local/bin/orcc --include glib.h --header -o gst/bayer/gstbayerorc.h ../gst-plugins-bad-1.24.7/gst/bayer/gstbayerorc.orc
[170/1023] /opt/local/bin/orcc --include glib.h --implementation -o gst/fieldanalysis/gstfieldanalysisorc.c ../gst-plugins-bad-1.24.7/gst/fieldanalysis/gstfieldanalysisorc.orc
[171/1023] /opt/local/bin/orcc --include glib.h --implementation -o gst/bayer/gstbayerorc.c ../gst-plugins-bad-1.24.7/gst/bayer/gstbayerorc.orc
ninja: build stopped: subcommand failed.
Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_gnome_gstreamer1-gst-plugins-bad/gstreamer1-gst-plugins-bad/work/build" && /opt/local/bin/ninja -j8 -v 
Exit code: 1
```

**Comment by kencu** [comment]
> @reneeotten Well, since the recent `py-setuptools` update has broken GIR scanner (and no one bothers to fix it or at least revert an update), we cannot build anything


10 second fix, see ticket:

https://trac.macports.org/ticket/70667#comment:4

**Comment by christophecvr** [comment]
> > @reneeotten Well, since the recent `py-setuptools` update has broken GIR scanner (and no one bothers to fix it or at least revert an update), we cannot build anything
> 
> 10 second fix, see ticket:
> 
> https://trac.macports.org/ticket/70667#comment:4

I will send a pull request for the broken git scanner (just create now a new branch cloned from current master and then will apply and send patch I use by me it works great.

**Comment by reneeotten** [comment]
> @reneeotten Well, since the recent `py-setuptools` update has broken GIR scanner (and no one bothers to fix it or at least revert an update), we cannot build anything:

well... as you know this is a volunteer project. If you care about something feel free to submit a PR to fix it. 

There is no reason to revert an update of py-setuptools the issue is clearly elsewhere; upstream decided to keep on using long deprecated stuff so now complaining about something breaking is futile. Upstream has a patch which linked in that ticket. If you care, you submit a PR - no point in complaining.

**Comment by barracuda156** [comment]
> no point in complaining.

If it was something specific to ppc or some older MacOS, I would not have.  But AFAIU, it is nothing about old systems, and GIR is used by _a lot_ of ports.

**Comment by barracuda156** [comment]
Should be good. I just forgot to remove a redundant line from the portfile.

```
svacchanda@43-200 ~ % port -v installed gnome-terminal 
The following ports are currently installed:
  gnome-terminal @3.38.3_0 (active) requested_variants='' platform='darwin 23' archs='arm64' date='2024-09-06T19:12:32+0800'
```

**Pull request merged**
