### PR TITLE
py-{pysam,htseq}: update to latest version

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
- update `py-pysam` and `py-htseq` to their latest upstream version
- use the MacPorts' port for `htslib` instead of building the internal version for `py-pysam`

Closes: https://trac.macports.org/ticket/64965

###### Tested on
macOS 10.15.7 19H1824 x86_64
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mascguy — APPROVED** [review]

**Comment by reneeotten** [comment]
@mascguy - please follow the established protocols of merging PRs. In other words, keep them open for 72 hours unless the maintainer approves and/or merges it, or the PR submitter merges it.

**Comment by mascguy** [comment]
> @mascguy - please follow the established protocols of merging PRs. In other words, keep them open for 72 hours unless the maintainer approves and/or merges it, or the PR submitter merges it.

If you review the history of this PR, you'll see that GitHub failed to provide a formal notification to the maintainer. And interestingly enough, GitHub also failed to assign any labels to this PR whatsoever - such as the maintainer status, etc - leading me to believe this was a nomaintainer port.

Given that I do my best to follow established procedures, please give folks the benefit of the doubt, before jumping to conclusions.

**Comment by reneeotten** [comment]
thanks @mascguy and it’s certainly not a big deal. I’m not jumping to conclusions though, just reminding you of the guidelines and that it got merged a bit prematurely. 

But, admittedly I didn’t notice on my phone that the labels/maintainers didn’t get assigned (in that case, “@macportsbot retry” is your friend).

**Comment by dliessi** [comment]
It would have been fine for me.
Thanks to both @reneeotten and @mascguy.

**Comment by mascguy** [comment]
> thanks @mascguy and it’s certainly not a big deal. I’m not jumping to conclusions though, just reminding you of the guidelines and that it got merged a bit prematurely.

No worries, I've been trying my darndest to use restraint when merging. But it also should have occurred to me that you submitted a PR for a purposr... but that didn't register. (Boy, I shouldn't do anything without being caffeinated first thing in the morning! Lol)

And sorry if I came off as a bit prickly, that wasn't my intent. Just wanted to try and reassure you that I'm trying to follow policy.

P.s. Thanks as always for putting up with me!

**Pull request merged**
