### PR TITLE
dbcli software updates and python 3.8 / postgresql 12 support

### PR DESCRIPTION
**Pull request by xeron**
##### Version update, add python 3.8, drop 3.4 and 3.5:

* litecli
* pgcli
* mycli
* py-pgspecial
* py-cli-helpers
* py-pymysql

##### Add python 3.8, drop 3.4 and 3.5:

* py-terminaltables
* py-setproctitle
* py-humanize

##### Add python 3.8:

* py-tabulate
* py-sqlparse

##### Add postgresql 12:

* pgcli
* py-psycopg2

###### Type(s)

- [x] update
- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.15
Xcode 11.1 (only CLI tools, without Xcode application)

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
That's a lot of Portfiles changing for one PR but LGTM.

**Comment by xeron** [comment]
These all are dependencies of pgcli/mycli so I wanted to ship them together.

**Comment by xeron** [comment]
Could someone merge please?

**Comment by g5pw** [comment]
@xeron could you avoid or separate out whitespace-only changes to portfiles? Also, was the postgresql-12 patch upstreamed?

**Comment by xeron** [comment]
@g5pw postgresql-12 patch is from upstream master branch.

I don't think I did that many whitespace changes to be worth for separate commits. Just empty line after `revision` for easier version and rev-bumping and fixed indent for docs block of `pgcli`. Which specific change you want to see as separate commit?

**Comment by xeron** [comment]
This is a bit frustrating. Can we merge this? I don't think 2-3 whitespace changes together with actual code changes should block anything.

**Comment by g5pw** [comment]
I understand your frustration. If you could just add some information to the `pgcli` patch (commit SHA, url), I'll merge this promptly.

**Comment by xeron** [comment]
Updated `pgcli` patch with exact commit from pgcli repo.

**Comment by g5pw** [comment]
Thank you, merging!

**Pull request merged**
