### PR TITLE
R: move recommended packages to ports, update PG

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Rationale for the change:
1. Recommended packages are not part of `R` and are developed and maintained by third parties.
2. Since they are not a part of `R`, they get updates in between `R` versions updates, and some `R` packages require a newer version of recommended packages than which was available at the time of `R` release; in result, our current set-up prevents those from updating.

I was aware of the issue for quite a while, but initially it was a single port not being able to get an update, and also I did not see a nice way to handle the matter. Now there are several with broken updates, and I think I came up with an elegant solution, which does not require manually adding dependencies to hundreds of ports and in effect maintains existing set-up: while `R` itself does not force-install recommended packages anymore, they are added as lib deps by R PG – for all `R` ports except recommended ones (so that we avoid circular dependencies).

I also drop `active_variants` PG from `R` port: it is redundant, being added by `compilers` PG, and amend a note re OpenMP, since we have already blacklisted Xcode clangs earlier, and LLVM clangs are being used, which do support OpenMP.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Something with `gfortran` does not work on CI:
```
  * installing *source* package ‘KernSmooth’ ...
  ** package ‘KernSmooth’ successfully unpacked and MD5 sums checked
  ** using staged installation
  ** libs
  using C compiler: ‘clang version 15.0.7’
  sh: /opt/local/bin/gfortran-mp-12: No such file or directory
  using SDK: ‘MacOSX12.3.sdk’
  /opt/local/bin/gfortran-mp-12  -fPIC  -pipe -Os -m64  -c blkest.f -o blkest.o
  make: /opt/local/bin/gfortran-mp-12: No such file or directory
  make: *** [blkest.o] Error 1
  ERROR: compilation failed for package ‘KernSmooth’
  * removing ‘/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-KernSmooth/R-KernSmooth/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/KernSmooth’
  Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-KernSmooth/R-KernSmooth/work/KernSmooth" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-KernSmooth/R-KernSmooth/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library 
  Exit code: 1
```
Weird, since `gcc12` installs fine here, and the portfile requires Fortran to be present.
At the same time, non-Fortran recommended packages install fine, so the change itself works fine.

**Comment by cjones051073** [comment]
> Something with `gfortran` does not work on CI:
> 
> ```
>   * installing *source* package ‘KernSmooth’ ...
>   ** package ‘KernSmooth’ successfully unpacked and MD5 sums checked
>   ** using staged installation
>   ** libs
>   using C compiler: ‘clang version 15.0.7’
>   sh: /opt/local/bin/gfortran-mp-12: No such file or directory
>   using SDK: ‘MacOSX12.3.sdk’
>   /opt/local/bin/gfortran-mp-12  -fPIC  -pipe -Os -m64  -c blkest.f -o blkest.o
>   make: /opt/local/bin/gfortran-mp-12: No such file or directory
>   make: *** [blkest.o] Error 1
>   ERROR: compilation failed for package ‘KernSmooth’
>   * removing ‘/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-KernSmooth/R-KernSmooth/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/KernSmooth’
>   Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-KernSmooth/R-KernSmooth/work/KernSmooth" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_R_R-KernSmooth/R-KernSmooth/work/destroot/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library 
>   Exit code: 1
> ```
> 
> Weird, since `gcc12` installs fine here, and the portfile requires Fortran to be present. At the same time, non-Fortran recommended packages install fine, so the change itself works as intended.

Which R port, specifically, is causing the above error ?

**Comment by barracuda156** [comment]
@cjones051073 From what it looks, any `R` port requiring Fortran will fail now with the same error.

Possibly it is caused by `compilers.setup` being overridden by PG. I am still trying to get it work correctly.

**Comment by i0ntempest** [comment]
Will there be a meta port like `R-recommended` that will install all recommended packages that you removed from `R` port? Rather than removing the variant completely you can make the variant depend on that meta port.

**Comment by barracuda156** [comment]
> Rather than removing the variant completely you can make the variant depend on that meta port.

@i0ntempest Well, that won’t work, since it will introduce a circular dependency. I initially tried to set recommended packages as runtime dependencies, and that also did not work.

In effect, we have to install `R` first in order to install anything which depends on `R`.

However, what I have done here still requires to install all recommended packages – the only difference is that it will be triggered when a user wants to install any other `R` package.

If you wish, we can make a note explaining the change, maybe?

I am also opened to suggestions, if there is a better idea. So far I could not see a better solution.

**Comment by i0ntempest** [comment]
@barracuda156 If the dep route is a no go then I guess a meta port and some notes is enough, as I want users to get (roughly) the same setup after installing R and the meta port as `R +recommended`.

**Comment by barracuda156** [comment]
@i0ntempest The question is how a user is made to install a meta-port? If it is just a standalone port (which pulls in 15 recommended ones), no one is obliged to install it (and we have dependents broken if it is not installed). If it is added to `R` PG as a R-wise lib dep, then the effect is identical to what I suggest, but it introduces a redundant extra step of making a meta-port.

I mean, I am not against the idea, I just do not see how to implement it otherwise. Does Macports has a mechanism how to make _dependents_ obligatory after installation of a port? I am not aware of such. For this reason I use PG to make recommended packages lib deps for other R packages.

**Comment by barracuda156** [comment]
@i0ntempest What we can do, if you prefer, is rename what we have now as `R` port to `R-base`, and then make a new `R` port which will install recommended packages. It does not seem to be a better solution, but I am okay with that, if you think it is in fact preferable.

**Comment by barracuda156** [comment]
Let me actually move packages updates into a separate PR, keeping here only recommended packages change.

**Comment by barracuda156** [comment]
@cjones051073 No, this does not work:
```
  using C compiler: ‘clang version 15.0.7’
  sh: /opt/local/bin/gfortran-mp-12: No such file or directory
  using SDK: ‘MacOSX13.3.sdk’
  /opt/local/bin/clang-mp-15 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk    -fPIC  -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -arch x86_64  -c clara.c -o clara.o
  /opt/local/bin/gfortran-mp-12  -fPIC  -pipe -Os -m64  -c daisy.f -o daisy.o
  make: /opt/local/bin/gfortran-mp-12: No such file or directory
  make: *** [daisy.o] Error 1
  ERROR: compilation failed for package ‘cluster’
```
It looks like a setting in PG overrides a setting in portfile, so fortran is not asked for.

Could we somehow fix it via PG in a way it works correctly? Other than requiring fortran globally.

**Comment by barracuda156** [comment]
@cjones051073 @i0ntempest Upon discussing the matter in https://trac.macports.org/ticket/68355 we decided to try not enforcing identical compiler (and therefore no revbumps across the board when a compiler version changes).

Let us see if this approach works.

**Comment by barracuda156** [comment]
@i0ntempest It keeps failing mystically, omitting dependency on `R-Matrix` for a single non-recommended package here, due to which `R-mgcv` fails to install (but it installs fine on its own). Cannot understand why.
Let me try a meta-port way.

**Comment by cjones051073** [comment]
Dear all. Indeed, it seems my attempt to peg R and all its ports to gcc12 did not work. I have fixed this with

https://github.com/macports/macports-ports/commit/d4a2e7e54e5caba2d72a2daf80e2caac9fe14482

where I instead just request gcc12 to be the default variant when needed.

This seems to work in terms of the port variants and dependencies

{{{
Larissa ~/Projects/MacPorts/ports > port info R-ClusVis R                                
R-ClusVis @1.2.0_1 (R, science)
Variants:             clang11, clang12, clang13, clang14, clang15, clangdevel, g95, gcc10, gcc11, [+]gcc12, gcc13, gccdevel,
                      gfortran

Description:          Gaussian-based visualization of Gaussian and non-Gaussian model-based clustering
Homepage:             https://cran.r-project.org/package=ClusVis

Build Dependencies:   gcc12, clang-15, R
Library Dependencies: R-mvtnorm, R-Rcpp, R-RcppArmadillo, R-Rmixmod, R-VarSelLCM, libgcc, libgcc12
Runtime Dependencies: R
Platforms:            darwin
License:              (GPL-2 or GPL-3)
Maintainers:          none
--
R @4.3.1 (math, science)
Variants:             accelerate, atlas, [+]builtin_lapack, [+]cairo, debug, g95, gcc10, gcc11, [+]gcc12, gcc13, gccdevel, java,
                      latex, openblas, [+]openmp, quartz, [+]recommended, [+]tcltk, tests, [+]x11

Description:          R is a language and environment for statistical computing and graphics. R provides a wide variety of
                      statistical (linear and nonlinear modeling, classical statistical tests, time-series analysis,
                      classification, clustering, ...) and graphical techniques, and is highly extensible.
Homepage:             https://www.r-project.org/

Build Dependencies:   pkgconfig, gcc12, clang-15
Library Dependencies: readline, icu, libiconv, zlib, pcre, pcre2, libjpeg-turbo, tiff, libpng, curl, less, texinfo, bzip2, gzip,
                      zip, unzip, gnutar, xz, libgcc, libgcc12, cairo, pango, glib2, freetype, fontconfig, gettext-runtime, tcl,
                      tk, xorg-libsm, xorg-libice, xorg-libX11, xorg-libXt, libomp
Runtime Dependencies: clang-15
Platforms:            macosx
License:              (GPL-2 or GPL-3)
Maintainers:          Email: kjell.konis@me.com, GitHub: kjellpk
                      Email: i0ntempest@macports.org, GitHub: i0ntempest
                      Policy: openmaintainer
}}}

( R-ClusVis was just a random fortran requiring port I picked to check things )

**Comment by barracuda156** [comment]
@cjones051073 Thank you! I will rebase to this. (Just finishing building gcc13.)

**Comment by barracuda156** [comment]
GH is stuck processing the push. Let’s hope everything works this time.

**Comment by cjones051073** [comment]
> I will probably give up for today, it the current update also fails.
> 
> P. S. Weirdly, `R-mgcv` installs fine as such, but fails to install as a dependency:
> 
> ```
> Installing dependency (16 of 20) 'R-mgcv' with variants '+gcc12' ... [FAIL]
> ```
> 
> which happens because `R-Matrix` gets omitted from dependencies. _But why?_

I doubt this has anything to do with the compiler issues, but more what you are doing in this MR.

**Comment by barracuda156** [comment]
> I doubt this has anything to do with the compiler issues, but more what you are doing in this MR.

It is unrelated to gcc12 changes, I know. Your last fix forks fine for me locally.

**Comment by barracuda156** [comment]
@ryandesign @catap Any idea why dependencies are broken here when R PG add them? Specifically R-Matrix is omitted, which breaks other ports. This is something about Macports options handling, all packages build fine on their own.

**Comment by barracuda156** [comment]
@i0ntempest Got it. This should be no issue, I can do that.

Do you have an idea why the current set-up fails on CI? Locally everything works for me. Lint does not complain. Port deps list all dependencies correctly (whatever I checked). But on CI we get a stupid error with omitted R-Matrix…

Meta-port will likely have the same issue, since I will need to use R PG to set it as a dependency for non-recommended packages.

**Comment by barracuda156** [comment]
P. S. Of course there is a solution to add recommended packages as a regular dependencies to every port which uses them (and have a meta-port as a convenience umbrella), and avoid a need to use R PG for that, but it will require modifying dependencies for thousands of ports, which I hope to avoid ))

**Comment by i0ntempest** [comment]
> Do you have an idea why the current set-up fails on CI? Locally everything works for me. Lint does not complain. Port deps list all dependencies correctly (whatever I checked). But on CI we get a stupid error with omitted R-Matrix…

I'm not sure, I'm not very clear about how the CI environment is setup. Probably the dependency list got reset somewhere by a `depends-*` command (rather than using `depends-*-append`).

**Comment by cjones051073** [comment]
@barracuda156 Strictly not related to this PR but R is now failing to build in the buildbots for OSX10.6 x86_64. See

https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/174373/steps/install-port/logs/stdio

please take a look.

Interestingly, 32bit 10.6 seems OK.

**Comment by cjones051073** [comment]
> @barracuda156 Strictly not related to this PR but R is now failing to build in the buildbots for OSX10.6 x86_64. See
> 
> https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/174373/steps/install-port/logs/stdio
> 
> please take a look.
> 
> Interestingly, 32bit 10.6 seems OK.

https://trac.macports.org/ticket/65246 Is probably related

**Comment by cjones051073** [comment]
I suspect we will need to revert https://github.com/macports/macports-ports/commit/08eb29280698a95127b5f5a237390258324f463b

**Comment by cjones051073** [comment]
https://github.com/macports/macports-ports/commit/3016286b6087f47cf660773c877ab9b70f5896fb

**Comment by barracuda156** [comment]
> @barracuda156 Strictly not related to this PR but R is now failing to build in the buildbots for OSX10.6 x86_64. See
> 
> https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/174373/steps/install-port/logs/stdio
> 
> please take a look.

@cjones051073 This looks like https://trac.macports.org/ticket/68404
Where it is old clangs which fail.

**Comment by cjones051073** [comment]
> > @barracuda156 Strictly not related to this PR but R is now failing to build in the buildbots for OSX10.6 x86_64. See
> > https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/174373/steps/install-port/logs/stdio
> > please take a look.
> 
> @cjones051073 This looks like https://trac.macports.org/ticket/68404 Where it is old clangs which fail.

https://trac.macports.org/ticket/65246 Is the more relevant ticket in this case. See last comment from @kencu 

i have reverted the fallbacks back to the old, stable, situation that allowed clang as the newest on darwin 10 and older. Before anyone considers changing this again the linker issue discussed above will need addressing.

**Comment by cjones051073** [comment]
@barracuda156 Please note the tests are failing again with what is likely more circular dependency issues.

**Comment by barracuda156** [comment]
@cjones051073 Well, I suspect that https://github.com/macports/mpbb/commit/c48853e678871e580dca89232e52a6d965a31812 has broken everything, and we need help from @jmroot or @mascguy to fix it. We cannot just throw away test dependencies for all `R` ports. It makes no sense. Especially given that everything was working perfectly for many months (and still works locally, failing only on CI).

P. S. _This specific PR_ is not a typical one, so it may happen that here it is my error somewhere. But in the earlier case, I am sure, it is the fault of mpbb.

**Comment by barracuda156** [comment]
@cjones051073 From another one:
```
Activating all dependencies...
invalid command name ""
    while executing
"$workername eval {validate_macportsuser}"
    (procedure "mportexec" line 5)
    invoked from within
"mportexec $ditem activate"
Error: Activate failed: invalid command name ""
Activation of dependency 'gcc12-libcxx' with variants '+clang14' failed, aborting.
Processing dependencies for 'R-ic.infer' failed, aborting.
```
So we get all sort of random failures now.

**Comment by barracuda156** [comment]
@cjones051073 By the way, now on 10.6 (and later, I believe) if GCC is used to build R, Macports picks gcc13 for C/C++, but gfortran from gcc12. Not sure it is right. Rather, perhaps, it should either consistently use gcc12 or gcc13.

**Comment by cjones051073** [comment]
> @cjones051073 By the way, now on 10.6 (and later, I believe) if GCC is used to build R, Macports picks gcc13 for C/C++, but gfortran from gcc12. Not sure it is right. Rather, perhaps, it should either consistently use gcc12 or gcc13.

That is because the `+gcc12` default variant I added to the R and R PGs is only used by the compilers PG to pick the compiler for fortran. it will never use that variant for c/c++. For that, you need to do the same as for clang and add MacPorts GCC13 to the blacklists.

**Comment by cjones051073** [comment]
> > @cjones051073 By the way, now on 10.6 (and later, I believe) if GCC is used to build R, Macports picks gcc13 for C/C++, but gfortran from gcc12. Not sure it is right. Rather, perhaps, it should either consistently use gcc12 or gcc13.
> 
> That is because the `+gcc12` default variant I added to the R and R PGs is only used by the compilers PG to pick the compiler for fortran. it will never use that variant for c/c++. For that, you need to do the same as for clang and add MacPorts GCC13 to the blacklists.

.... not that I think there is an issue mixing gcc12 and gcc13 here.

**Comment by barracuda156** [comment]
@cjones051073 Got it. I do not really know what is the opinion of GCC upstream on this. 

Provided we move to gcc13 soon, perhaps not much point to add gcc12 to blacklist, unless some errors show up.

**Comment by cjones051073** [comment]
> @cjones051073 Got it. I do not really know what is the opinion of GCC upstream on this.
> 
> Provided we move to gcc13 soon, perhaps not much point to add gcc13 to blacklist, unless some errors show up due to the combo.

The runtimes used for C/C++ and fortran are anyway different and don't mix, so there is no reason using different gcc's will cause a problem. The default behaviour on OSX10.6+ is anyway to mix c/c++ built with clang and fortran with GCC, and that causes no issues, and you would image the differences there are bigger than just two different GCC versions.

Also note, by design all GCC share the same runtime. Thats what the libgcc port ensures. This is currently provided by libgcc13, and is what you links against even if you use GCC12. 

So, I don't think there is really anything at all to raise with GCC upstream here, and I agree there is little need I think to blacklist gcc13 at this time, if you anyway plan to look into bumping the clang/gcc versions you use.

**Comment by barracuda156** [comment]
@i0ntempest Could you review this please?

@cjones051073 Ok, now everything works!

**Pull request merged**
