### PR TITLE
libgit2-devel: update to 1.8.1

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by mascguy** [comment]
It looks like one of the patches failed to apply.

More troubling, though, is the fact that it failed across all four CI systems... but the failure wasn't properly caught/reported by base, for macOS 13 and 14. (Assuming we aren't doing anything funky in the port, for 13 and later...)

**Comment by mascguy** [comment]
> It looks like one of the patches failed to apply.
> 
> More troubling, though, is the fact that it failed across all four CI systems... but the failure wasn't properly caught/reported by base, for macOS 13 and 14. (Assuming we aren't doing anything funky in the port, for 13 and later...)

Herby, we should probably create a bug for this, assuming one doesn't already exist. (Unable to do it myself at this point, as I am away from my Mac.)

**Comment by ryandesign** [comment]
This is caused by macOS 13 and later containing a different `patch` program (which defaults to applying a patch in reversed order when that works) than macOS 12 and earlier (which defaults to failing when a reversed patch is detected).

The fix is to remove the reversed 0001-process.c-fix-environ-for-macOS.patch patch since the reason it is reversed is that it has been included upstream in this version.

See https://trac.macports.org/ticket/69649 for discussions about how MacPorts can work better with the macOS 13+ `patch` program.

**Comment by reneeotten** [comment]
@herbygillot ping - can you fix this or close the PR please?

**Pull request merged**
