### PR TITLE
mariadb-10.11: fix the build for 32-bit

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

A very simple fix to allow it build.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by evanmiller** [comment]
Disabling a static_assert is generally a bad idea as the program usually depends on the assertion in order for the code to work. Have you run the test suite?

**Comment by barracuda156** [comment]
> Disabling a static_assert is generally a bad idea as the program usually depends on the assertion in order for the code to work. Have you run the test suite?

@evanmiller Unfortunately, the port does not have any tests enabled.
Judging from comments to the code, should not be a big deal IMO. (Isn’t it verified at compile time only?)

**Comment by kencu** [comment]
I presumed that ```sizeof(void*)*2+8``` should probably be ```sizeof(void*)*2+4``` for 32 bit, but I didn't have enough insight to know for certain.

This YYSTYPE business is apparently related to yacc, of which I know next to nothing:

https://silcnitc.github.io/ywl.html

**Comment by barracuda156** [comment]
> I presumed that `sizeof(void*)*2+8` should probably be `sizeof(void*)*2+4` for 32 bit, but I didn't have enough insight to know for certain.

That explains the error `note: the comparison reduces to '(20 == 16)`.
https://trac.macports.org/ticket/67278

**Comment by evanmiller** [comment]
> > I presumed that `sizeof(void*)*2+8` should probably be `sizeof(void*)*2+4` for 32 bit, but I didn't have enough insight to know for certain.
> 
> That explains the error `note: the comparison reduces to '(20 == 16)`. https://trac.macports.org/ticket/67278
> 
> So I can try using `sizeof(void*)*2+4` instead and if it works, we do not need to disable it.

You are missing the point. The comment indicates that the code relies on `YYSTYPE` being a certain size. Please don't modify this without either running a test suite or fully understanding what the code is doing.

**Comment by barracuda156** [comment]
> You are missing the point. The comment indicates that the code relies on `YYSTYPE` being a certain size. Please don't modify this without either running a test suite or fully understanding what the code is doing.

Sorry, missed that it is reverse: reducing right side by 4 won’t make it equal to `YYSTYPE`. Need more caffeine.

**Comment by kencu** [comment]
perhaps the yystype for 32 bit is supposed to be 16. 

you’d have to look at what the union is thinking it is made up of. Why does this check even exist? Somebody thought it important…

perhaps this is a good upstream question.

I did look to see this code seems old, and hasn’t changed recently afaict.

So something odd is happening.

**Pull request closed without merging**
