### PR TITLE
pyinfra: update to 2.9, use Python 3.12

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
CI fails:
```
Installing dependency (22 of 32) 'py311-gevent' with variants '' ... [FAIL]
```
The py-gevent port doesn't have a py311-gevent subport yet. It's added by #18932 but that PR has other problems that need resolving first.

**Comment by reneeotten** [comment]
@herbygillot are you still interested in working on this? If so, please update the PR otherwise please close.

**Comment by reneeotten** [comment]
@herbygillot I am attempting to finish off some PRs to try and clean-up the queue... As far as I can tell this should work now, but please do verify.

**Comment by pmetzger** [comment]
@reneeotten Conflicts with the main branch it seems.

**Comment by pmetzger** [comment]
CI is still failing it seems. What's still wrong?

**Comment by reneeotten** [comment]
> CI is still failing it seems. What's still wrong?

Looks like an issue with the `py36-bcrypt` subport (that old stuff should have been removed a long time ago) but hopefully now fixed....

**Comment by herbygillot** [comment]
Thanks @reneeotten, @pmetzger

**Pull request merged**
