### PR TITLE
openssh: fix error with zlib 1.3

### PR DESCRIPTION
**Pull request by artkiver**
* closes: https://trac.macports.org/ticket/67986

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.5.1 22G90 arm64
Xcode 15.0 15A5219j

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by reneeotten — COMMENTED** [review]
@artkiver Sure you can patch out the version check. But presumably upstream had a reason for this; does the port function correctly with a newer zlib version. 
If this patch was accepted upstream please add a link to that commit/PR.

**Comment by artkiver** [comment]
> @artkiver Sure you can patch out the version check. But presumably upstream had a reason for this; does the port function correctly with a newer zlib version. If this patch was accepted upstream please add a link to that commit/PR.

Thanks for reviewing this @reneeotten!

Regarding your concerns, the pertinent upstream commit was mentioned in the Trac ticket as well but I'll link to it here as well for clarity:

https://github.com/openssh/openssh-portable/commit/cb4ed12ffc332d1f72d054ed92655b5f1c38f621

This PR is basically down streaming that change ahead of a new OpenSSH version release via the added patch/diff.

According to the BugZilla comment here: https://bugzilla.mindrot.org/show_bug.cgi?id=3604#c1 the fix should be in OpenSSH snapshots now. However, since we don't track snapshot OpenSSH releases though, it seemed like maybe the best way to rectify this for the time being was via a Portfile rev? I suppose I could create an openssh-devel MacPort which tries to track snapshot releases as another method though?

**Comment by reneeotten** [comment]
Great - please add that link to the patchfile and we should be good to merge.

**Comment by artkiver** [comment]
> Great - please add that link to the patchfile and we should be good to merge.

To make sure I am understanding you correctly, you want a link to the upstream within the patch/diff?

As like a comment?

e.g.

`
# fix from upstream: https://github.com/openssh/openssh-portable/commit/cb4ed12ffc332d1f72d054ed92655b5f1c38f621
--- configure.ac
+++ configure.ac
@@ -1464,7 +1464,7 @@
        [[
        int a=0, b=0, c=0, d=0, n, v;
        n = sscanf(ZLIB_VERSION, "%d.%d.%d.%d", &a, &b, &c, &d);
-       if (n != 3 && n != 4)
+       if (n < 1)
                exit(1);
        v = a*1000000 + b*10000 + c*100 + d;
        fprintf(stderr, "found zlib version %s (%d)\n", ZLIB_VERSION, v);

`

**Comment by artkiver** [comment]
Wow, that did not paste elegantly. Trying again below

`# fix from upstream: https://github.com/openssh/openssh-portable/commit/cb4ed12ffc332d1f72d054ed92655b5f1c38f621
--- configure.ac
+++ configure.ac
@@ -1464,7 +1464,7 @@
        [[
        int a=0, b=0, c=0, d=0, n, v;
        n = sscanf(ZLIB_VERSION, "%d.%d.%d.%d", &a, &b, &c, &d);
-       if (n != 3 && n != 4)
+       if (n < 1)
                exit(1);
        v = a*1000000 + b*10000 + c*100 + d;
        fprintf(stderr, "found zlib version %s (%d)\n", ZLIB_VERSION, v);
`

**Comment by artkiver** [comment]
Well, I am not sure how GitHub's "Add Code" feature works when it seems to be tripping up on the # comment; but hopefully my question is clear?

**Comment by artkiver** [comment]
Superseded by: https://github.com/macports/macports-ports/pull/19989

**Pull request closed without merging**
