### PR TITLE
gtk-radio: new port

### PR DESCRIPTION
**Pull request by oleaamot**
#### Description

gtk-radio 264.2 from https://www.gtkradio.org/src/gtk-radio-264.2.tar.xz

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.3.1 23D60 arm64
Xcode 15.2 15C500b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
@reneeotten Do you want to have a go at this?

**Comment by reneeotten** [comment]
> @reneeotten Do you want to have a go at this?

not really... I don't have much/any experience or interest in these Gnome related packages.

**Comment by herbygillot** [comment]
Thanks for this submission, @oleaamot.  I actually tried building locally, got the following:

```
No package 'geoclue-2.0' found
No package 'libgeoclue-2.0' found
```

Interesting that it built fine in CI.  Might still make sense to add `geoclue2` as a dependent.

**Comment by herbygillot** [comment]
This built just fine after installing `geoclue2`.

**Pull request closed without merging**
