### PR TITLE
gmsh: add oce and opencascade (default) variants

### PR DESCRIPTION
**Pull request by Schamschula**
###### Type(s)

- [x] enhancement

###### Tested on
macOS 10.14.6 18G103
Xcode 10.3 10G8 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?

### CODE REVIEW

**Comment by MarcusCalhoun-Lopez** [comment]
There are a few issues:
* [minor] the commit message is a little confusing.
The dependency is not redundant (yet), so "remove reduntant opencascade depends-libs entry" is not quite accurate.
* If a user has either opencascade or oce  installed but builds gmsh with `-opencascade -oce`, the build script will opportunistically use whichever is installed without depending on it.

What about
```diff
--- Portfile~	2019-10-27 07:11:59.000000000 -0700
+++ Portfile	2019-10-27 07:13:50.000000000 -0700
@@ -122,6 +122,11 @@
                         apple-gcc-4.2
 }
 
+variant oce description {use Community Edition version of Open CASCADE} {
+    depends_lib-replace port:opencascade \
+                        port:oce
+}
+
 # please remove on 2020-03-16
 subport ${name}-devel {
     replaced_by         ${name}
```

**Comment by Schamschula** [comment]
> There are a few issues:
> 
> * [minor] the commit message is a little confusing.
>   The dependency is not redundant (yet), so "remove reduntant opencascade depends-libs entry" is not quite accurate.

Agreed. I got to quit putting in these commits after I wake up in the morning... 

> * If a user has either opencascade or oce  installed but builds gmsh with `-opencascade -oce`, the build script will opportunistically use whichever is installed without depending on it.
> 
> What about
> 
> ```diff
> --- Portfile~	2019-10-27 07:11:59.000000000 -0700
> +++ Portfile	2019-10-27 07:13:50.000000000 -0700
> @@ -122,6 +122,11 @@
>                          apple-gcc-4.2
>  }
>  
> +variant oce description {use Community Edition version of Open CASCADE} {
> +    depends_lib-replace port:opencascade \
> +                        port:oce
> +}
> +
>  # please remove on 2020-03-16
>  subport ${name}-devel {
>      replaced_by         ${name}
> ```

That's exactly what I first tried. Even, after I deactivated there previous install of gmsh, I wasn't able to install the oce variant.

> neptune:ports marius$ sudo port -tv install gmsh +oce
> --->  Computing dependencies for gmsh..
> Error: Can't install oce because conflicting ports are active: opencascade
> Error: Follow https://guide.macports.org/#project.tickets to report a bug.
> Error: Processing of port gmsh failed
> neptune:ports marius$ sudo port -f deactivate gmsh
> --->  Deactivating gmsh @4.4.1_0+accelerate
> --->  Cleaning gmsh
> neptune:ports marius$ sudo port -tv install gmsh +oce
> --->  Computing dependencies for gmsh..
> Error: Can't install oce because conflicting ports are active: opencascade
> Error: Follow https://guide.macports.org/#project.tickets to report a bug.
> Error: Processing of port gmsh failed
> neptune:ports marius$ sudo port installed gmsh
> The following ports are currently installed:
>   gmsh @4.4.1_0+accelerate

**Comment by Schamschula** [comment]
Hmm. I tried Plan A one more time. Now it worked!

**Comment by Schamschula** [comment]
Looks like I'm having a problem squashing the git commits. Deleting branch and trying it again.

**Pull request closed without merging**
