### PR TITLE
chafa: update to 1.6.1

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
Can you check the build failures pleas ?

**Comment by herbygillot** [comment]
> Can you check the build failures please ?

Yes, I'm aware - don't have a fix just yet.

**Comment by cjones051073** [comment]
@herbygillot ping, any updates here ?

**Comment by herbygillot** [comment]
Closing this, have not gotten this version to build, will spend no more time on this.

**Pull request closed without merging**
