### PR TITLE
MythTV 29.1 and MythWeb 29.1 Updates

### PR DESCRIPTION
**Pull request by Moisie2000**
#### Description

Updating MythTV.28 and MythWeb.28 to MythTV29.1 and MythWeb29.1

Updates Ports:
- mythtv.28
- mythtv-core.28
- mythtv-pkg.28
- mythtv-plugins.28
- mythweb.28

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.12.6 16G29
Xcode 9.2 9C40b 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Thanks for working on this update! Right now, you have a bunch of commits, and not all of them match the macports standard for commit messaging. Squashing them to the minimum number and following the commit message guidelines would be a good thing.

Hopefully @ctreleaven will also have some comments shortly.

**Comment by ctreleaven** [comment]
Not sure what you are trying to do with the name of the port:

`name                mythtv${majorversion}${minorversion} `

Currently, this will name the main port 'mythtv29.1'.  When upstream changes the minor version to '.2', the port will be renamed 'mythtv29.2'.  We don't want that.

**Comment by pmetzger** [comment]
> First, I have absolutely no experience working with pull requests, so I may need some hand-holding.

I can help with the pull request machinery.

**Comment by Moisie2000** [comment]
>> First, I have absolutely no experience working with pull requests, so I may need some hand-holding.

> I can help with the pull request machinery.

Good - this is totally new to me too!

> Right now, you have a bunch of commits, and not all of them match the macports standard for commit messaging. Squashing them to the minimum number and following the commit message guidelines would be a good thing.

Very happy to comply - but I can't see how I can squash the commits or edit the commit messages from inside the GitHub UI. I'm not doing this using a external editor and - as you can probably tell - I'm a bit new to all of this! I've tried to find out how to do this, but can't currently see how to. If it's going to be a blocker, then I'll invest further time in doing so.

> Second, this should not be an UPDATE to mythtv*.28 -- we need to create a NEW mythtv*29 port. Some (many) users will elect to stay with 0.28 and I won't force an upgrade on them.

Agreed - but from what I wrote, I needed to submit this as a patch to the existing myth ports, in order that you (as the maintainer) can then create a new port.

> Please summarize the testing you've done with this version. Have you been running it in 'production'? Using mythfrontend or something else? Using MythWeb? Using the built-in web server?

On my test installs (both running macOS 10.12.6, but two separate machines), I've:
* Successfully compiled;
* Successfully restored a pre-existing database, and run MythSetup to configure to the new hardware;
* Successfully run MythTV front-end, playing existing recordings and navigating the UI;
* Successfully connected to the MythTV back-end from Kodi, playing existing recordings, browsing the guide and set up new recordings;
* Successfully set up MythWeb (note - some details on the Wiki need editing - but I'm still trying to get editing access to the Wiki for this), and connected to it.

Testing has not been exhaustive, but I feel I have tested sufficiently to prove that - on my systems - the port works as expected. However, I obviously cannot guarantee the stability of the core code beyond that noted above.

>Not sure what you are trying to do with the name of the port:
> `name mythtv${majorversion}${minorversion}`

This is to reflect the new version numbering scheme of MythTV: https://www.mythtv.org/wiki/Release_Notes_-_29


I'm very happy for whatever changes you see fit to be made - especially from a perspective of complying with MacPorts standards - but in submitting this PR, I was aiming to do what I could to save you the effort of having to do _all_ the work in bring the port forward to the current Myth release.

**Comment by pmetzger** [comment]
> Very happy to comply - but I can't see how I can squash the commits or edit the commit messages from inside the GitHub UI.

You can't. You have to do it on your Mac at the command line. From there, though, everything is quite easy. The one big issue is that instead of doing your work from a branch, you've done it from "master", so if we end up with merge conflicts you're going to need to move the work onto a branch and probably close this PR and open a new PR (which is not a big deal.) For the moment that's not necessary, though.

The online editing stuff is nice but sadly it isn't really comprehensive.

> Agreed - but from what I wrote, I needed to submit this as a patch to the existing myth ports, in order that you (as the maintainer) can then create a new port.

You can just create a pull request for a new port with @ctreleaven listed as the maintainer if you want.

**Comment by pmetzger** [comment]
@ctreleaven What would you prefer happen here? If you want, you can also just create the new ports using @Moisie2000's patches.

**Comment by ctreleaven** [comment]
Absolultely, we don't want to touch 0.28.  We want a new port for 29.  Remember, the functional differences between 0.28.x and 29.x are really minor.  They just wanted to stop implying that Myth was an unstable beta--which is typically the case with version numbers less than 1.0.

@Moisie2000 No, we don't want to have different ports for 29.1, 29.2, etc.  Upstream takes pains to ensure the database doesn't change within a major release.  Thus users can easily upgrade to any fixes in the 29 branch (and mix/match frontends/backends).  Please undo all the ${minorversion} changes.

Re testing, have you tried starting with a blank database and configuring from scratch?  On the MythTV forum, this was reported to fail due to issues with the pre-upgrade-backup.

**Comment by pmetzger** [comment]
@ctreleaven Just so I understand, if the functional differences are minor, why shouldn't we have just one mythtv port etc? (Not criticizing, I'm really just asking.)

**Comment by Moisie2000** [comment]
@ctreleaven Hi Craig -

> Please undo all the ${minorversion} changes.

So - just to clarify - you favour replacing all references to mythtv.28 and version 0.28 etc to mythtv29 and version 29 etc? (i.e. NOT mythtv29.1, version 29.1 etc)

> Re testing, have you tried starting with a blank database and configuring from scratch? On the MythTV forum, this was reported to fail due to issues with the pre-upgrade-backup.

Yes - that was me highlighting this. Given that the issue also occurs in 0.28 and is not a part of the ports code, I see no reason to hold back with 29.1.

**Comment by pmetzger** [comment]
> So - just to clarify - you favour replacing all references to mythtv.28 and version 0.28 etc to mythtv29 and version 29 etc? (i.e. NOT mythtv29.1, version 29.1 etc)

I presume that's what he means. If it isn't, editing is easy and fast.

Meanwhile, please check out this fork on your own machine and see if you can't figure out how to do things like squashing the git commits etc., as that will be needed before the final merge.

**Comment by ctreleaven** [comment]
@pmetzger Re mythtv versions, users are often very reluctant to upgrade between major versions.  The whole family may be relying on Myth to record their fav TV programs...breaking a working system can be hazardous to your health!

**Comment by ctreleaven** [comment]
> I've targeted the v29.1 release (01-Feb-2018), rather than chasing a potentially-unstable mid-cycle build. I have not attempted to build anything beyond that point.

The project has recommended targeting the head of the fixes branch:

https://www.mythtv.org/wiki/Build_from_Source#Getting_and_compiling_the_source_code

They only infrequently tag point releases so we would be missing out on potentially useful fixes for months otherwise.

**Comment by ctreleaven** [comment]
FFmpeg changes?  I thought they all went into the master branch; not fixes/29.  Are you sure you are working on the right branch?

**Comment by ctreleaven** [comment]
For example, see

https://code.mythtv.org/trac/ticket/13259

Note that the version is "Master head" and the milestone is "30.0".  Peter started this ffmpeg work months ago and all of it went to the master branch so that it will eventually be included in the release of version 30.

**Comment by pmetzger** [comment]
BTW, we generally prefer not to leave works in progress in the pull queue indefinitely, so if this might really take a while, it might be best to close this PR and re-open it when you're ready.

**Comment by Moisie2000** [comment]
> Are you sure you are working on the right branch?

Ah - well - yes, that's a very good question. Silly me - I've been working on the master branch. I'm still getting used to how all this version-control stuff works... ;-)

So, I'll go back and work to the fixes/29 branch and update here when I can; I'm a bit busy over the next few weeks, but hopefully it'll go more smoothly this time.

**Comment by pmetzger** [comment]
Any news? I'd like to get this PR cleared out.

**Comment by Moisie2000** [comment]
Sorry sorry sorry - I've been tied up with other matters of late!

I'm intending to complete this over this weekend, and once I've had - say - a week of running it on my production machine, it should be ready to roll.

**Comment by pmetzger** [comment]
@Moisie2000 Cool, thanks!

**Comment by Moisie2000** [comment]
@pmetzger @ctreleaven Hello!

Sorry for the delay in this, but I think it's all ready now. This build is successfully running on my production machine, so it's probably ready for you to re-review.

It's based on the fixes/29 branch up to 20180820. I've squashed the commits and updated the commit comment (thanks Gitkraken for making the impenetrable _slightly_ more penetrable!).

Obviously it's expecting the ports to be named mythtv29, mythtv-core29, mythtv-plugins29 and mythweb29. There is also a file inside the files folder which needs to be renamed from _README_mythtv.28_MacPorts.txt_ to _README_mythtv29_MacPorts.txt_.


Please let me know if there's anything else I need to do from my end.

**Comment by pmetzger** [comment]
@ctreleaven Opinions?

**Comment by ctreleaven** [comment]
@pmetzger We CANNOT COMMIT as is.  It must be changed to create new portfiles; not modify the existing 0.28 release.

@Moisie2000 As you say, we need to create new ports.  (Although it was easier to review as a diff of 0.28.)  

Also, If you have this line:
`subport mythtv-pkg${majorversion} { }`

delete it.  (It was a mistake in the 0.28 release.)

You can also do the renaming of the README file.

Other than that, based on a visual review of the code--as long as new ports are created for version 29--I see no other problems

**Comment by Moisie2000** [comment]
Hello!

> Also, If you have this line:
> subport mythtv-pkg${majorversion} { }
> delete it. (It was a mistake in the 0.28 release.)

Done.

> You can also do the renaming of the README file.

Done.


As far as I can see, this is now ready for creating the new port - but I'm probably not best placed (or sufficiently well-informed) for doing this! @pmetzger Can you help with this?

**Comment by pmetzger** [comment]
@Moisie2000 You care currently modifying an existing `Portfile`. If you want to create a new port, you need to create a file named something like `multimedia/mythtv.29/Portfile` (note the _9_ in place of the _8_) and associated files.

**Comment by ctreleaven** [comment]
Actually `multimedia/mythtv29/Portfile` -- no need for the dot anymore!

**Comment by Moisie2000** [comment]
Hiya - how are we looking now?

**Comment by pmetzger** [comment]
> Hiya - how are we looking now?

Better, but there are still commits it seems to `mythtv.28/*` files. Those should presumably go. The commit message also should be something like "mythtv29: new port" on its first line. There also seems to be other stuff that needs cleaning. I'd go through what you committed pretty carefully.

**Comment by ctreleaven** [comment]
Yes, as I read it this commit touches most or all of the files in mythtv.28 which is be unnecessary.  
Please correct.

**Comment by Moisie2000** [comment]
Sorry - not sure how that happened - I pulled down fresh copies of the .28 versions to replace the versions I changed, but Git still seemed to have an issue with it.
Corrected now. Fingers crossed...

Thanks for your patience, and apologies for all the to'ing and fro'ing whilst I get my amateur head round this!

**Comment by pmetzger** [comment]
The patches are clean now (or so it seems).

@ctreleaven You'll have to test this and report back on whether you think it's correct.

**Comment by pmetzger** [comment]
@ctreleaven Can you please have a look? I'd like to finish this up.

**Comment by pmetzger** [comment]
@ctreleaven, @Moisie2000 spent time and effort creating this enhancement and it seems impolite of us to leave them hanging indefinitely.

**Comment by ctreleaven** [comment]
Where are the instructions again on getting this branch reflected in my local git?

**Comment by pmetzger** [comment]
@ctreleaven Clone https://github.com/Moisie2000/macports-ports

**Comment by ctreleaven** [comment]
I can't get p5.26-dbd-mysql to update:

`:info:build /opt/local/include/mariadb/mysql/mysql_version.h:16:31: note: expanded from macro 'MARIADB_BASE_VERSION'
:info:build #define MARIADB_BASE_VERSION            "mariadb-5.5"
:info:build                                         ^
:info:build dbdimp.c:1917:56: error: invalid token at start of a preprocessor expression
:info:build #if (MYSQL_VERSION_ID >= 50600) && (MYSQL_VERSION_ID < MARIADB_BASE_VERSION)
:info:build                                                        ^
:info:build /opt/local/include/mariadb/mysql/mysql_version.h:16:31: note: expanded from macro 'MARIADB_BASE_VERSION'
:info:build #define MARIADB_BASE_VERSION            "mariadb-5.5"
:info:build                                         ^
`
Investigating...

**Comment by ctreleaven** [comment]
Appears to be a bug that was fixed a couple of weeks ago:

https://github.com/perl5-dbi/DBD-mysql/issues/262

**Comment by pmetzger** [comment]
@ctreleaven Thanks for your work in maintaining the MythTV ports. Being a port maintainer gives you the ability to block other people's changes to your work, but it also gives you the obligation to help with merging other people's fixes and improvements in a reasonably rapid manner. Three and a half months is probably not reasonable under the circumstances. Could you make a point of helping to take care of this issue sooner rather than later? If you cannot do that, I want to simply commit this. @Moisie2000's work should not sit in the PR queue forever.

**Comment by ctreleaven** [comment]
@Moisie2000 if we commit this as is, will you help with support on https://forum.mythtv.org/index.php and the mythtv-users mailing list?  It doesn't look like I'm going to get any free time to test 29.0 for at least a couple of weeks.  

@pmetzger I did attempt to test but ran into a road block when one of the perl dependencies failed to install (see above).  Anyone trying to install from scratch will run into the same problem.  To my knowledge, it hasn't been fixed in the past 24 days.

**Comment by ctreleaven** [comment]
Incidentally, @Moisie2000 you need to do a selfupdate and then retest the mythtv build.  I suspect the p5.26-dbd-mysql problem will also block you.  I believe there may be a patch out there that addresses this problem but I don't know enough about the port to address it.  See:

https://trac.macports.org/ticket/57240

**Comment by Moisie2000** [comment]
@pmetzger Thanks for staying on top of this, and for your patience with me whilst I sorted out my numerous commit issues early on!

@ctreleaven Please accept my apologies that this has placed a burden on you to deal with - I hadn't realised at the outset what would have been required of you through this process!

> will you help with support on https://forum.mythtv.org/index.php and the mythtv-users mailing list?

Of course - very happy to do what I can, though I freely admit my knowledge is probably substantially less than yours.

> you need to do a selfupdate and then retest the mythtv build.

Sure - will do that this weekend and see what I can find out. Thanks for trying it - for the record, I've been running this PR on my main system for nearly two months (admittedly primarily as a backend for Kodi), and it's been rock-solid for me.

**Comment by pmetzger** [comment]
@Moisie2000 Let me know when you feel comfortable merging this.

**Comment by Moisie2000** [comment]
Hello - sorry, real life has got in the way of me doing anything on this yet. I hope to get to it in the next couple of days.

**Comment by pmetzger** [comment]
It is fine for anyone to submit a patch for any port, not just `nomaintainer` ones, but if there's no maintainer we don't have to wait for the maintainer to approve it to incorporate it. :)

**Comment by Moisie2000** [comment]
Hi - just to post that I haven't abandoned this, but updating the DBD-mysql port doesn't look like the most straightforward thing in the world, and is taking me longer to get my head around! Hope to make some progress over the holiday period...

**Comment by brianboonstra** [comment]
The Travis check failures were all timeouts rather than actual build failures, FYI.

**Comment by pmetzger** [comment]
@brianboonstra That's pretty standard.

**Comment by ctreleaven** [comment]
The stars have aligned and I actually have a little time to spend on this.  I've updated p5-dbd-mysql to 4.049 to catch the fix we need.

Trying to build mythtv-core29, it complained that qt5-mysql-plugin is replaced by qt59-mysql-plugin.  I've modified @Moisie2000 's Portfile to require qt59 for mysql-plugin, qtscript and qtwebkit.  Have a build chugging away now.  Now, my copy diverges from the pull request and I still have no understanding of how to handle this with git.  Can I get some hand-holding?

**Comment by pmetzger** [comment]
What git help do you need? I can help. (If needed, you can email me at <myhandle> at macports.org.)

**Comment by ctreleaven** [comment]
Something is messed up with Qt5.  I got my 10.13 VM running which had a MythTV 29 test from quite a few months ago.  When trying to build Myth with the new portfile, I get:

--->  Computing dependencies for qt5-qtsvg
The following dependencies will be installed:  qt5-qtbase
Continue? [Y/n]: 
--->  Activating qt5-qtbase @5.12.0_2+openssl
Error: Failed to activate qt5-qtbase: Image error: /opt/local/libexec/qt5/bin/qcollectiongenerator is being used by the active qt5-qttools port.  Please deactivate this port first, or use 'port -f activate qt5-qtbase' to force the activation.
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_aqua_qt5/qt5-qtbase/main.log for details.
Error: Unable to execute port: upgrade qt5-qtscript failed

I guess I need to try to decipher the Qt5 portgroup.  Again.

**Comment by ctreleaven** [comment]
BTW I can see the control for posting "code" on this interface but I apparently can not figure out how it works.  Sigh.

**Comment by ctreleaven** [comment]
@moisie2000 Have you updated/tested/used this port recently?  I set up a VM running 10.13 and installed.  mythtv-setup ran fine for me, mythbackend is running, but when I start mythfrontend, I get a "EXC_BAD_ACCESS (SIGSEGV)" crash.  

Note that in the meantime, MacPorts is now installing Qt 5.12 on such a configuration.  That may be related...or not!

**Comment by Moisie2000** [comment]
Hello!

Sorry - I've not been able to do any work on this lately - but here's some responses.

> The stars have aligned and I actually have a little time to spend on this. I've updated p5-dbd-mysql to 4.049 to catch the fix we need.

Amazing - thanks Craig!

> Have you updated/tested/used this port recently?

Yes - it's my daily driver on macOS 10.12.6 - though running the successful build I had when I created this PR. I've not tried an updated version of the port since you reported the p5-dbd-mysql problem - but I'll try it again on my 10.12 test VM.

**Comment by ctreleaven** [comment]
PR needs to be closed as "Won't fix" or whatever the equivalent.

I've banged my head on this for quite some time.  There are non-trivial problems with Myth 29.x on macOS.  Not least is that the front window will loose keyboard focus whenever one enters certain screens.  A mouse click will restore focus but that is a problem.  Myth is designed and intended to be used in a media centre configuration.  Everything should be accessible with a remote control with a limited number of buttons (like the Apple Remote).  A mouse should not be required.

Unfortunately, there is no longer a Mac-centric developer on the upstream project.  When and if one comes along, perhaps these issues will get addressed.  In the longer term, Apple's announced deprecation of OpenGL is likely to be a very significant problem for Myth on Mac.

**Comment by Moisie2000** [comment]
@ctreleaven Hi Craig - many apologies for the lack of updates here, and **very** sorry to have wasted your time with this PR. I hope can contribute something positive to the project in the future!

**Pull request closed without merging**
