### PR TITLE
libvpx: Don't force use of clang-3.9

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

libvpx: Don't force use of clang-3.9

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.6 17G65
Xcode 9.4.1 9F2000 

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
so libvpx needs a newer clang compiler to compile it's fancy assembly -- clang 3.9 or newer. If this PR is committed, then the build will fall back to a failing compiler, and so the build fails on many systems, eg `10.7.5`:

```
In file included from vpx_dsp/x86/vpx_subpixel_8t_intrin_avx2.c:15:
./vpx_dsp/x86/convolve_avx2.h:45:7: error: address expression must be an lvalue or a function designator
      MM256_BROADCASTSI128_SI256(_mm_load_si128((const __m128i *)filter));
      ^                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./vpx_dsp/x86/convolve_avx2.h:25:45: note: expanded from macro 'MM256_BROADCASTSI128_SI256'
  _mm_broadcastsi128_si256((__m128i const *)&(x))
                                            ^
1 error generated.
```
we need a better plan than just deleting the fallback.

**Comment by kencu** [comment]
WIth one tiny change in `portconfigure.tcl`, this port builds correctly on older systems with this PR.

`portconfigure.tcl` has changed a bit since I last looked closely at it. It now adds all the existing `macports-clang-*` compilers to the recommended compiler list, but for some reason, only does that if the stdlib is set to `libc++`. 

There is no reason for these compilers to be available only if the stdlib is set to `libc++`; they all build against `libstdc++` (and most of them against `macports-libstdc++` as well).

Removing the bit that blocks them from these other `stdlib` settings by commenting out the `libc++` test like this:
```
    if {![info exists option_defaults(configure.cxx_stdlib)]} {
        set our_stdlib ${configure.cxx_stdlib}
    } else {
        set our_stdlib $cxx_stdlib
    }
#    if {$our_stdlib eq "libc++"} {
        # clang-3.5+ require libc++
        lappend compilers macports-clang-5.0 macports-clang-4.0

        if {${os.major} < 17} {
            # The High Sierra SDK requires a toolchain that can apply nullability to uuid_t
            lappend compilers macports-clang-3.9
        }

        if {${os.major} < 16} {
            # The Sierra SDK requires a toolchain that supports class properties
            lappend compilers macports-clang-3.7
        }
#    }

    if {${os.major} < 16} {
        # We dropped support for these compilers on Sierra
        lappend compilers macports-clang-3.4 macports-llvm-gcc-4.2 apple-gcc-4.2
    }

    return $compilers
```
makes these compilers available in the list, and then MacPorts correctly selects the first one that is not blacklisted (which is `macports-clang-5.0` in this case), and the build of `libvpx` proceeds apace, without trouble.

Unless I'm missing something obvious here, this change in `portconfigure.tcl` seems like the proper way to fix this -- and then this PR can go ahead and be committed, and everything should work as it is meant to.

**Comment by ryandesign** [comment]
What's supposed to happen is: MacPorts base sets `compiler.fallback` to the list of all compilers that work on this system (based on OS version, Xcode version, C++ stdlib), in order of preference. An individual port can set `compiler.blacklist` to the set of all compilers that are known to be unable to build this port. MacPorts then chooses the first non-blacklisted compiler in the fallback list.

If *all* compilers are blacklisted, that means *no* compiler can compile this software, and the port is effectively incompatible with this system. MacPorts prints a warning, tries to compile the port anyway, using the first compiler in the fallback list, and the build is expected to fail.

If a new compiler has come into existence since the last release of MacPorts base, and a port is only compatible with that new compiler and not any of the compilers MacPorts base would otherwise choose, then it is reasonable to add that new compiler to the fallback list, until such a time as MacPorts base can be updated to include that new compiler. As I understand it, that is the situation that applies for libvpx. This port did not build with clang 3.8 or older, and clang 3.9 was so new that it was not yet in the base fallback list, so the port added it.

The problem is that the port *prepended* clang 3.9 to the list, meaning that as time went on, and as new compilers got added to the base fallback list, the libvpx port still prefered the aging and now quite old clang 3.9 over newer versions that would work fine. Contrary to the original intention of using a bleeding-edge compiler, the port now uses an outdated compiler that is known to be incompatible with the High Sierra SDK and later. If the port *appended* clang 3.9 to the fallback list, rather than prepending it, these problems would be avoided.

In the mean time, clang 3.9 and newer versions were added to MacPorts base, so there should no longer be a need for the port to add it, hence this PR.

Ken claims clang 3.9 works fine with libstdc++. This is contrary to the statements made in the code committed to base and the clang ports by @jeremyhu ("`# clang-3.5+ require libc++`"), so he will have to comment. If clang 3.5+ works with libc++, base should be changed. Until such a time as a new version of base is released containing that change, the port can do whatever it needs to add the compilers that are missing.

Note that extensive work on reworking the compiler selection of base has already been done in https://github.com/macports/macports-base/pull/88. I don't know whether it already makes the needed changes. If not, consider the impact that unrelated changes to base would have on that PR, or consider adding the needed changes to that PR.

**Comment by mojca** [comment]
I agree with @kencu about libc++. That library is definitely needed to build the newer clang compilers, but compilers work on systems where libstdc++ is the default stdlib.

**Comment by kencu** [comment]
<https://github.com/macports/macports-base/pull/88> is indeed a very extensive change to how things are done. I think the `libc++` test I mentioned has been removed in that PR already, but there is so much going on it will take quite some time to digest just how that affects everything....

**Comment by kencu** [comment]
Slightly off topic, but I wonder how much of <https://github.com/macports/macports-base/pull/88> would still be necessary if we just flipped the switch to default MacPorts to `libc++` on all systems, and set the default compilers properly to something like what is currently set in LibCxxOnOlderSystems.

So much of those changes are to accomodate `macports-libstdc++` and set up tricky compiler floors that we really should not need to fuss about, IMHO.

**Comment by ryandesign** [comment]
As far as I know, no solution has yet been proposed for bootstrapping the installation of those compilers.

**Comment by kencu** [comment]
This PR version builds successfully on `10.7.5` configured to the default settings with `libstdc++`.

**Comment by kencu** [comment]
I can confirm this works, on the machines I have available to test it. I'll go ahead and commit it, therefore, and hope we see no fallout...

**Pull request merged**
