### PR TITLE
ola: update to 0.10.3 maintainer

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by peternewman** [comment]
https://trac.macports.org/ticket/53103

**Comment by tobypeterson** [comment]
Thanks

**Comment by raimue** [comment]
Please, do not open both a ticket and a pull request. After the PR was merged, the ticket stayed open because there was no reference to close the ticket in the commit message.

**Comment by peternewman** [comment]
Thanks @tobypeterson . Noted @raimue, will continue discussion on the Trac ticket.

**Pull request merged**
