### PR TITLE
tomcat6, servlet25-api: delete EOL ports

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description

[End-of-lifed by upstream in 2016.](https://tomcat.apache.org/tomcat-60-eol.html)

Closes: https://trac.macports.org/ticket/25663
Closes: https://trac.macports.org/ticket/36792
Closes: https://trac.macports.org/ticket/37515
Closes: https://trac.macports.org/ticket/51099
Closes: https://trac.macports.org/ticket/52449

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

### CODE REVIEW

**Comment by blair** [comment]
Is there a MacPorts policy on deleting EOL ports? We still support older OSes and some newer releases of software may not work on the older OSes.

**Comment by chrstphrchvz** [comment]
> Is there a MacPorts policy on deleting EOL ports?

When the topic of deleting ports (not just EOL ones) [came up on the mailing list in early February](https://lists.macports.org/pipermail/macports-dev/2019-February/040074.html), it was stated that there is no official policy, so I take that as meaning deletions will be handled on a case-by-case basis. I don't know that the lack of policy is intentional, but various conflicting viewpoints have been expressed on what would be criteria for removal.

So far what I've done for some unmaintained ports is to leave open the deletion long enough for comments or some alternative to be chosen. Deletion just tends to be the easiest change for me to propose.

> We still support older OSes and some newer releases of software may not work on the older OSes.

I interpret "support older OSes" as being upon request/best-effort/submissions welcome, and not a guarantee.

I am not familiar with Tomcat, but I think in this case that if a replacement for these should be available in MacPorts while maximizing older OS compatibility, then Tomcat 7 (which is still supported) and a `servlet30-api` port would still be a better option than Tomcat 6 or older. The main dependencies that I am aware of are JDK, and Apache Ant if compiling it is still desired; it appears that JDK 6 and `apache-ant-1.9` might be enough for Tomcat 7 to work on older systems.

However, Tomcat 7 was requested 8 years ago, and porting it has stalled: https://trac.macports.org/ticket/28938. I am aware you indicated that you no longer used Tomcat on Mac and/or had limited availability for maintaining a port for it. Even though this seems like a highly desired port based on the number of subscribers accumulated by the ticket, I wonder if it's still worth adding; at least one person who needed felt compelled to inform MacPorts they've already moved on to obtaining it elsewhere.

**Comment by markemer** [comment]
Tomcat 6 is EOL, but I'm impressed we don't have a tomcat plain port for tomcat 9.0 - does tomcat 6 still run on 10.14? Also, is anyone looking to update tomcat?

**Comment by pmetzger** [comment]
Is there an objection to merging this?

**Comment by blair** [comment]
No objections.

**Comment by pmetzger** [comment]
Merged.

**Pull request merged**
