### PR TITLE
vim: add python311 variant

### PR DESCRIPTION
**Pull request by markmentovai**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 13.0.1 22A400 arm64
Xcode 14.1 14B47b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by raimue** [comment]
Thank you for the new variant. Looks good to me, but we should add the same variant for the MacVim port as well to keep them in sync.

**Comment by raimue** [comment]
Also we might need [this upstream change](https://github.com/vim/vim/commit/5a5f17f9b3fa14c36a7d6c96ac55acaddb6247e1) to get vim to build with this variant. I see from the PR description that you did not try yet.

**Comment by reneeotten** [comment]
ping @markmentovai - can you take care of @raimue his comments in order to get this merged?

**Comment by markmentovai** [comment]
@raimue, @reneeotten Sorry for the delay.

https://github.com/macports/macports-ports/pull/16838#issuecomment-1335080430:
> Thank you for the new variant. Looks good to me, but we should add the same variant for the MacVim port as well to keep them in sync.

Yes. I updated to include this.

https://github.com/macports/macports-ports/pull/16838#issuecomment-1335082911:
> Also we might need [this upstream change](https://github.com/vim/vim/commit/5a5f17f9b3fa14c36a7d6c96ac55acaddb6247e1) to get vim to build with this variant. I see from the PR description that you did not try yet.

I did try, and this variant does build and work. The variant also builds in MacVim.

The upstream patch in question is necessary to silence warnings, but this does not build with `-Werror`, so the warnings do not interfere with the build. There are two `-Wdeprecated-declarations` warnings and one `-Wmacro-redefined` warning when building `vim+python311`:

```
/usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -I…/include -isysroot…/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.sdk -DMACOS_X -DMACOS_X_DARWIN  -pipe -Os -isysroot…/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.sdk -arch arm64 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/job.o job.c
In file included from if_python3.c:69:
In file included from …/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/Python.h:12:
…/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pyconfig.h:292:9: warning: 'HAVE_DUP' macro redefined [-Wmacro-redefined]
#define HAVE_DUP 1
        ^
./os_unix.h:481:10: note: previous definition is here
# define HAVE_DUP               // have dup()
         ^
if_python3.c:1144:3: warning: 'Py_SetPythonHome' is deprecated [-Wdeprecated-declarations]
                Py_SetPythonHome(py_home_buf);
                ^
…/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pylifecycle.h:40:1: note: 'Py_SetPythonHome' has been explicitly marked deprecated here
Py_DEPRECATED(3.11) PyAPI_FUNC(void) Py_SetPythonHome(const wchar_t *);
^
…/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
#define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                     ^
if_python3.c:1872:5: warning: 'PySys_SetArgv' is deprecated [-Wdeprecated-declarations]
    PySys_SetArgv(1, argv);
    ^
…/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/sysmodule.h:13:1: note: 'PySys_SetArgv' has been explicitly marked deprecated here
Py_DEPRECATED(3.11) PyAPI_FUNC(void) PySys_SetArgv(int, wchar_t **);
^
…/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
#define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                     ^
```

To completely avoid the warnings, upstream also has https://github.com/vim/vim/commit/6c3d3e69047438ff5b7f58d44fe66af9e2c4212b to address the `-Wmacro-redefined` warnings. But these warnings aren’t particularly intrusive and have no impact on the build in MacPorts which, as mentioned, does not use `-Werror`. Ignoring them wouldn’t have any impact on the output, and I don’t see any benefit to bringing those two patches into MacPorts. It’d just be churn to add the patches now, only to remove them the next time the ports are updated.

In any case, suppressing the warnings isn’t incredibly helpful. It would be best if upstream would adopt the replacement interface, [PyConfig](https://docs.python.org/3/c-api/init_config.html#pyconfig) (when integrating with Python ≥3.8).

**Review by raimue — APPROVED** [review]

**Comment by raimue** [comment]
Thank you for handling MacVim as well! Sorry that I delayed this even further with the review. And especially thank you for the detailed explanations of the Python compiler warnings. I completely agree with you that it does not help much to backport them only to silence these warnings. Let's move on with this and get support for +python311 into the ports tree.

**Pull request merged**
