### PR TITLE
xca: update to 2.4.0

### PR DESCRIPTION
**Pull request by lhaeger**
###### Tested on

macOS 10.15.7 19H524 x86_64
Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
@lhaeger can you check the build failures ?

**Comment by lhaeger** [comment]
Works on 10.14 and 10.15 (aborted here, successful on my machine). I have no idea what 11 is complaining about, some stricter checks against the 11.3. SDK maybe? 
There's an issue open with upstream, too, so I'll wait for that to be closed before the next attempt.

**Comment by reneeotten** [comment]
@lhaeger can this be pushed over the finish line or do you want to close it first until upstream has resolved things?

**Comment by lhaeger** [comment]
> @lhaeger can this be pushed over the finish line or do you want to close it first until upstream has resolved things?

I'll look into this when I'm back from vacation, in about two weeks, I guess.

**Comment by cjones051073** [comment]
Ping

**Comment by lhaeger** [comment]
> Ping

If someone with a macOS11 machine could test the build maually and it succeeds, it should be fine to merge. I have no Big Sur and won't upgrade anytime soon, sorry.

**Comment by reneeotten** [comment]
> If someone with a macOS11 machine could test the build maually and it succeeds, it should be fine to merge. I have no Big Sur and won't upgrade anytime soon, sorry.

that's where the CI is for, you can see that it fails (similarly as it would when building manually) and can check the logs and try to fix it or report it upstream. To me it appears the issue could be with the `VERSION` file that clashes with the C++ header file on non-casesensitive filesystems. Please try a fix like the one done [here](https://github.com/macports/macports-ports/blob/f7763023b25d7d13291177a59b3853243bb910ce/graphics/tiff/files/rename-VERSION.patch) and elsewhere in the MacPorts tree (i.e., rename the file).

**Comment by lhaeger** [comment]
> that's where the CI is for, you can see that it fails (similarly as it would when building manually) and can check the logs and try to fix it or report it upstream. 
Theory vs. practice. I've seen CI fail for various reasons when my local build for the same OS version succeeded. 
> To me it appears the issue could be with the `VERSION` file that clashes with the C++ header file on non-casesensitive filesystems. 
My Catalina machine uses case-insensitive APFS as well, yet no build error. 
> Please try a fix like the one done [here](https://github.com/macports/macports-ports/blob/f7763023b25d7d13291177a59b3853243bb910ce/graphics/tiff/files/rename-VERSION.patch) and elsewhere in the MacPorts tree (i.e., rename the file).
Gave it a try, let's see if it helps, anyway.

**Pull request merged**
