### PR TITLE
qemu: build with MacPorts meson

### PR DESCRIPTION
**Pull request by evanmiller**
#### Description

qemu's internal meson contains a number of bugs that have been fixed either upstream or by MacPorts patches. One bug prevents building with GCC (#12069); others prevent building with PowerPC and on Tiger. To work around these bugs, supply the MacPorts meson at to qemu's configure, and also skip over an error that disallows both `--python` and `--meson` to be specified.

(For the full context of the commented-out error, see:

https://github.com/qemu/qemu/blob/dd4b0de45965538f19bb40c7ddaaba384a8c613a/configure#L1519-L1530

Both qemu and meson use MacPorts-supplied Python 3.9, so the error is not applicable.)

This is not a complete fix for any particular OS/compiler combination; it is rather a prerequisite to other PRs which will follow.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.4.11
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mascguy — APPROVED** [review]

**Comment by raimue** [comment]
The problem is that we have to ensure qemu and meson will always use the same python version. This is the case at the moment, but as soon as the meson port is updated to the next python release, we also need to update the qemu port at the same time. So... how are we going to do maintain this relationship?

**Comment by evanmiller** [comment]
@raimue I have modified the patch to extract the python path from meson's shebang line. Does that address your concern?

**Comment by raimue** [comment]
This is a nice hack! :+1: 

By deleting the `license_noconflict` I was a bit afraid the port can no longer be distributed as binary archive. However, I think the problem was that Python linked with OpenSSL 1.x with its license being incompatible with the GPL. But with OpenSSL >= 3.0 I expect this to be a thing of the past now anyway. However, I cannot confirm this right now with `port_binary_distributable.tcl` as I am not on my Mac.

**Comment by mascguy** [comment]
Looks good now!

```
$ ../macports-infra/jobs/port_binary_distributable.tcl -v qemu
"qemu" is distributable
```

**Comment by evanmiller** [comment]
One final note: I'm not sure how exactly `python.versions` works, but all of the versions listed in the `meson` Portfile should be compatible with qemu (3.6+, defaulting to 3.9).

**Comment by mascguy** [comment]
Sounds good Evan.

Rainer, are we ready to merge?

**Review by raimue — APPROVED** [review]
Thanks for working on this! It makes a lot of sense to use the patched meson provided by MacPorts. 👍

**Comment by evanmiller** [comment]
Thanks for the quick attention. I have a few more PRs planned for qemu as I work my way backward through the OS versions. (I've sent a couple patches upstream, but it's a pretty busy project and I haven't heard anything from them yet...)

**Pull request merged**
