### PR TITLE
py-sphinx: update to 1.8.3

### PR DESCRIPTION
**Pull request by chrstphrchvz**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.2 18C54
Xcode 10.1 10B61
Python 3.7.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] ~~referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?~~

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Merged! Thanks, @chrstphrchvz!

**Comment by chrstphrchvz** [comment]
In c2ae41e7293d939bfbcaf7aab8d7b7cb15a6f2a7:

```diff
-checksums           rmd160  d4261d472c07152632e327cc0751bd936bd1b796 \
-                    sha256  c4cb17ba44acffae3d3209646b6baec1e215cad3065e852c68cc569d4df1b9f8 \
-                    size    5760197
+checksums           rmd160 d4261d472c07152632e327cc0751bd936bd1b796 \
+                    sha256 c4cb17ba44acffae3d3209646b6baec1e215cad3065e852c68cc569d4df1b9f8

```


Is specifying `size` an issue/no longer recommended?

**Comment by jmroot** [comment]
Just a rebase hiccup.

**Comment by pmetzger** [comment]
size is necessary. If it's now missing, we should re-add it.

**Pull request merged**
