### PR TITLE
py-astropy: upgrade to 2.0.2

### PR DESCRIPTION
**Pull request by lpsinger**
This patch updates Astropy to 2.0.2.

### CODE REVIEW

**Comment by lpsinger** [comment]
Will push under maintainer timeout later today.

**Comment by cdeil** [comment]
@lpsinger - I'm listed as one of the maintainers for the Astropy port. Feel free to go ahead and merge this in now.

Did you check if the Astropy unit tests via `python -c 'import astropy; astropy.test()'` pass?
Do you see a CFITSIO version mismatch when you import `astropy.io.fits`?

Like I mentioned in #576, I would be interested to understand what the "proper" sequence of updates / dependencies of versions for CFITSIO / WCSLIB / Astropy (and possibly other ports that depend on CFITSIO) is, and whether it's "safe" to update Astropy to 2.0.2 before updating CFITSIO.

But my understanding is while there are warnings from CFITSIO version mismatches, in practice CFITSIO and WCSLIB are stable enough that Astropy can mostly work with any version and the order of updates is not critical. Is that correct?

This is just out of curiosity. @lpsinger - Go ahead with any updates you like, no need to wait for maintainer timeout, I think you have more experience / knowledge than me about those version dependencies.

**Comment by lpsinger** [comment]
> Did you check if the Astropy unit tests via python -c 'import astropy; astropy.test()' pass?
> Do you see a CFITSIO version mismatch when you import astropy.io.fits?

It did pass, but this will cause warnings every time you import astropy.wcs or astropy.io.fits. We should update those packages first.

**Comment by cdeil** [comment]
@lpsinger - Thanks!

I just updated and everything seems to work OK. I see this with `python -c 'import astropy; astropy.test()'`:
```
9673 passed, 167 skipped, 54 xfailed, 3 xpassed, 2318 warnings in 257.61 seconds
```
i.e. a ton of warnings.

But if I pip-install the Astropy dev version I see the warnings too:
```
9862 passed, 149 skipped, 53 xfailed, 3 xpassed, 2404 warnings in 258.98 seconds
```
so I think it's normal to see them when running tests via `astropy.test()`

So bottom line: I think everything OK after the update to Astropy 2.0.2 in Macports.

**Pull request merged**
