### PR TITLE
Python 38 beta4

### PR DESCRIPTION
**Pull request by Themanwithoutaplan**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.6 18G95
Xcode 10.3 10G8

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by Themanwithoutaplan** [comment]
Sorry, looks like it sucked in a load of stuff.

**Comment by cjones051073** [comment]
closing this PR was (probably) not necessary. You just needed to fix your branch used here. Most likely you need to probably rebase it against current master. run

```
git pull --rebase --autostash <NAME> master
```

replacing `<NAME>` with whatever you call the primary MacPorts repo in your local checkout.

**Comment by l2dy** [comment]
> closing this PR was (probably) not necessary. You just needed to fix your branch used here. Most likely you need to probably rebase it against current master. [...]

Given the amount of users notified by the bot, creating another PR is better to avoid further disturbance.

**Comment by cjones051073** [comment]
Good point... Same branch though could be used, once fixed.

**Pull request closed without merging**
