### PR TITLE
shellcheck: Use cabal-based native builds

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.5.1 21G83 x86_64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by neverpanic** [comment]
What are the advantages of using a cabal-based build? Why are we keeping the capability to build with stack?

Most of our users will just want a working shellcheck, so we should choose one suitable option and go with it.

It also seems like the build is failing:
```
  Warning: cannot determine version of /opt/local/bin/ghc :
  ""
  Error: cabal: The program 'ghc' version >=7.0.1 is required but the version of
  /opt/local/bin/ghc could not be determined.
```

**Comment by essandess** [comment]
> What are the advantages of using a cabal-based build?

Native build on arm, native MacPorts build that links to MacPorts libraries.

> Why are we keeping the capability to build with stack?

Haskell experience says it always good to have a robust alternate available in case something breaks in the dependency chain.

> Most of our users will just want a working shellcheck, so we should choose one suitable option and go with it.

Agreed, that’s why the variant isn’t a default. But I recommend keeping a variant build option in the back pocket in case the dependency chain breaks.

> It also seems like the build is failing:
> 
> ```
>   Warning: cannot determine version of /opt/local/bin/ghc :
>   ""
>   Error: cabal: The program 'ghc' version >=7.0.1 is required but the version of
>   /opt/local/bin/ghc could not be determined.
> ```

That appears to be a `ghc` buildbot issue that we don’t see locally or in the `ghc` CI. I don’t believe that it’s related to this PR.

**Comment by essandess** [comment]
@mascguy The `x86_64` buildbot for `ghc` is failing on 12.15, apparently affecting the CI on this and recent `cabal`-related PRs. Do you see what the issue is?

**Comment by essandess** [comment]
> @mascguy The `x86_64` buildbot for `ghc` is failing on 12.15, apparently affecting the CI on this and recent `cabal`-related PRs. Do you see what the issue is?
> 
> https://build.macports.org/builders/ports-12_x86_64-builder/builds/40985

FYSA I added parallel builds back in (deleted the `use_parallel no` line) because the switch to `hadrian`-based builds looked okay. I’m not sure if this is related or not. It looks fine on `arm64`.

**Comment by essandess** [comment]
> > @mascguy The `x86_64` buildbot for `ghc` is failing on 12.15, apparently affecting the CI on this and recent `cabal`-related PRs. Do you see what the issue is?
> > https://build.macports.org/builders/ports-12_x86_64-builder/builds/40985
> 
> <s>FYSA I added parallel builds back in (deleted the `use_parallel no` line) because the switch to `hadrian`-based builds looked okay. I’m not sure if this is related or not. It looks fine on `arm64`.</s>

@mascguy I believe these build issues are caused because I didn't include all the necessary dependencies in #15770. I've fixed this in #16089 and sanity checked with trace builds of all new `cabal`-based PRs, including this one.

Once is #16089 is approved and merged, I'll rebase all these PRs and expect it all to just work now.

**Review by mascguy — APPROVED** [review]
LGTM, with the caveat that the Monterey CI jobs are taking an eternity. We simply might need to wait for binaries to be completed, for PR: https://github.com/macports/macports-ports/pull/16089

Clemens?

**Review by neverpanic — APPROVED** [review]
lg2m, at least one of the CIs is now green, too.

**Pull request merged**
