### PR TITLE
Update mercurial (and extensions)

### PR DESCRIPTION
**Pull request by lbschenkel**
Just straightforward version updates, no other changes. Each one on its own commit.
In theory I could just go ahead and merge as this falls within the scope of `openmaintainer` but I'm going to submit to @seanfarley to check if it's OK to merge and ask if I can just do it directly next time.

Note that I'm *not* bumping the `-devel` subports in this PR.

### CODE REVIEW

**Comment by lbschenkel** [comment]
You're probably busy/unavailable @seanfarley, so I'm going to go ahead and merge this since it falls within the spirit of `openmaintainer`. Please do comment here in case you ever read this and there's something I should know for future updates.

**Comment by seanfarley** [comment]
Did I not already push this? ... checks repo ... aw dangit, I totally had this ready to go day of but missed it.

Thanks for doing this (there is a security update today that I'll push out as well)

**Comment by lbschenkel** [comment]
I'm a heavy user of Mercurial and the aforementioned extensions, do you mind if I'm proactive in directly updating those? And do you mind if I do that without updating the `-devel` subports, since I don't use them much and it takes more time to figure out what's the latest commit for each? (If I need to do that as well it will discourage a bit keeping the main ports up-to-date.)

**Comment by seanfarley** [comment]
Nah, it's fine. Just shoot me an email to update `-devel` if you get to it before I do. I have a script that updates the ports (and -devel) automatically that I should probably share with the community. It's extremely hacky (lots of regex and requires each port to be previously installed) but might be useful to some people.

**Comment by lbschenkel** [comment]
Will do, thanks.

**Pull request merged**
