### PR TITLE
lapack 3.9.0 to 3.10.0

### PR DESCRIPTION
**Pull request by michaelld**
#### Description

subject says it all

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.5 20G71
Xcode 12.3 12C33

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by gaming-hacker** [comment]
Bug
Error: lapack: Variant gcc11 conflicts with gfortran
Error: Unable to open port: Error evaluating variants
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug

**Comment by michaelld** [comment]
> The following ports are currently installed:
> lapack @3.9.0_0+gfortran (active)
> 
> upgrade lapack gives
> 
> Bug
> Error: lapack: Variant gcc11 conflicts with gfortran
> Error: Unable to open port: Error evaluating variants
> Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug
> 
> Full Name: lapack @3.10.0+gcc11
> lapack @3.10.0 (math, devel, science)
> Sub-ports: lapack-manpages
> Variants: accelerate, (-)debug, g95, (-)gcc10, (+)gcc11, gcc5, gcc6, (-)gcc7, (-)gcc8, (-)gcc9,
> gfortran, openblas, (-)universal

@gaming-hacker I believe this means you have a default variant set in `$(prefix}/etc/macports/variants.conf` and that variant conflicts with whatever you're trying to do here. This issue pre-dates my proposed changes. That said, let me see if I can fix this issue in this port.

**Comment by michaelld** [comment]
Looking at the info you provided, I'd say multiple negative variants: `-debug, -gcc10, -gcc7, -gcc8, -gcc9, -universal` and 1 positive:  `+gcc11`. The default variant of this port is `+gfortran` ... which does indeed seem to conflict with the positive default you have set. Let me test this & see about fixing it.

**Comment by michaelld** [comment]
Yup what I note is the issue: the default variant(s) in `variants.conf` are conflicting with the variant of the port that's already installed & now being `update`d. Basically: This port was installed using defaults, then `variants.conf` was changed, and how `port` cannot `update` it because the port's default variant is no longer a valid option.

Your choices are to (1) remove the `+gcc11` from `variants.conf` or (2) `sudo port install lapack`. I'm not sure I'd classify this as a `port` bug. It seems like a reasonable response to the situation.

**Comment by michaelld** [comment]
It has been 6 days with no useful feedback. The only feedback is a pre-existing issue with how `port` deals with variants; nothing to do with this PR. All of these ports are `openmaintainer`, and we are well beyond the normal 48 hour maintainer timeout. Hence I'm merging this.

**Comment by gaming-hacker** [comment]
Sorry for late reponse i just pulled lapack from the github and did a manual build/install.  I can confirm that removing sudo port uninstall lapack and reinstalling does not work.  macports still looks at the variants.conf

I commented out +gcc11 from the variants and tried 
sudo port install lapack +gcc11+gfortran+openblas and still bombed with
```
Error: lapack: Variant gcc11 conflicts with gfortran
Error: Unable to open port: Error evaluating variants
```

**Comment by michaelld** [comment]
@gaming-hacker yes I see this same too. apparently it's a 'port' feature: it's the same for all ports that use whatever variants are declared in `variants.conf`. This PR's changes are not related to this issue. If you feel comfortable doing so, please open an issue on [MacPorts' trac site](trac.macports.org).

**Pull request merged**
