### PR TITLE
gnucash: remove unneeded depends_run gnucash-docs

### PR DESCRIPTION
**Pull request by holymonson**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.7.4 21H1123 x86_64
Command Line Tools 14.2.0.0.1.1668646533

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
Without this, does help work in gnucash any more?

**Comment by holymonson** [comment]
> Without this, does help work in gnucash any more?

1. It seems broken anyway (by my test ). With `+quartz`, it show nothing but won't break down gnucash main program.
2. IMHO, we decoupled gnucash and gnucash-docs so we can install one without the other, otherwise we don't need to build 2 seperated ports with the same code pack.
3. As stated below, gnucash-docs is always broken with `+quartz`. If you prefer to keep it as mandatory dependency, then I suggest moving it to `+x11` section only.

https://github.com/macports/macports-ports/blob/2ce8b7fc476954f54546f75ee120814a44325a9d/gnome/gnucash-docs/Portfile#L41-L43

**Comment by pmetzger** [comment]
Why is the documentation dependent on which display system is used?

**Comment by holymonson** [comment]
> Why is the documentation dependent on which display system is used?

It was introduced by #4849, a workaround for https://trac.macports.org/ticket/55345. It should be fixed in glib2, or at least in yelp, but it is still there 6 years later (failed to build yelp with `glib2 +quartz` just now).

Maybe we should add `require_active_variants` in yelp until https://trac.macports.org/ticket/55345 is fixed.

**Comment by drkp** [comment]
It looks like the docs aren't currently working in the x11 variant either, but we should fix that rather than just removing the dependency. I'm going to move this to a trac ticket for that.

**Comment by drkp** [comment]
See https://trac.macports.org/ticket/69942

**Pull request closed without merging**
