### PR TITLE
gcc: Remove c++ symlink

### PR DESCRIPTION
**Pull request by rubendibattista**
Fix https://trac.macports.org/ticket/48647

#### Description

https://lists.macports.org/pipermail/macports-users/2020-October/048907.html

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
FYI, this is three days of compiling on my Leopard systems to delete a symlink...I know it's changing files on disk, but sheesh....I'm going to override this one locally if it gets committed just to save kilowatts...

**Comment by rubendibattista** [comment]
@kencu I know it's heavy, but it caused me a big headache (https://github.com/mutationpp/Mutationpp/issues/143#issuecomment-707742157), so I think it must be done. :)

**Comment by kencu** [comment]
Right. I don't use "gcc select" at all, myself, and this is way too onerous for me for this fix, so I'm going to peg this one for myself until some more substantial need to update that gcc version comes along, but for the buildbot-capable users, makes little difference to people I guess.

**Comment by ryandesign** [comment]
Looks like you forgot to make the corresponding changes in the gcc_select port.

**Comment by rubendibattista** [comment]
It should be ok now @ryandesign

**Comment by kencu** [comment]
Well Yuk -- here comes a bloody **week** of compiling for all those poor sots who build +universal or with systems < darwin10, all to remove a symlink that most people should not be using in the first place.

It is a total shame this could not be coupled with some other needed update, just to avoid the crazy amount of downtime this will being everyone.

BUT, if we're going to do it, let's do it now I guess. All the brass seems on board with this.

Please forgive me.

**Comment by rubendibattista** [comment]
[!Gandalf](https://tse1.mm.bing.net/th?id=OGC.5364aead04076df3b00182a2f60853f0&pid=Api&rurl=https%3a%2f%2fmedia.giphy.com%2fmedia%2fA6PcmRqkyMOBy%2fgiphy.gif&ehk=GNbSN9eRLBYmk9l%2fEzA%2fy%2bcX%2bW2U%2bO4ttZtAgpoTpu4%3d)

**Comment by ryandesign** [comment]
Looks like gcc-devel and gcc_select didn't get revbumped. Revbumping gcc_select is easy. For gcc-devel we should just wait until the next weekly snapshot is available and update to that.

**Comment by rubendibattista** [comment]
> 
> 
> Looks like gcc-devel and gcc_select didn't get revbumped. Revbumping gcc_select is easy. For gcc-devel we should just wait until the next weekly snapshot is available and update to that.

Lol, it's mathematical. I revbump when I don't have to, and I don't when I should. :). 

Sorry.

**Comment by ryandesign** [comment]
Looks like apple-gcc42 and llvm-gcc42 ports were also forgotten.

**Pull request merged**
