### PR TITLE
graphviz: update to 11.0.0

### PR DESCRIPTION
**Pull request by szhorvat**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 14.5 23F79 arm64
Xcode 15.4 15F31d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by szhorvat** [comment]
Tested only `graphviz`, not `graphviz-devel`, since the latter seems identical. Tested through the GUI.

**Comment by szhorvat** [comment]
This built for me successfully locally, but it fails on the CI with:

```
error: failed to deserialize Info.plist task context: Deserialization failed: SDK lookup failed for canonical name: macosx13.3 (in target 'application' from project 'graphviz')
  
  warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'application' from project 'graphviz')
  ** BUILD FAILED **
```

I'm not sure how to fix this and this is not an openmaintainer port, I'd rather leave this to the maintainers. Feel free to continue in this PR or close it.

The same error is mentioned in this ticket: https://trac.macports.org/ticket/68417

**Comment by mascguy** [comment]
> Tested only `graphviz`, not `graphviz-devel`, since the latter seems identical. Tested through the GUI.

The goal of the `-devel` port, is to validate updates like this before rolling them out to everyone. So you'll want to update `graphviz-devel` instead.

**Comment by szhorvat** [comment]
@mascguy As I said above, I won't continue with this PR as I can't fix the issue that causes CI to fail. It's up to you to continue or close it.

**Pull request closed without merging**
