### PR TITLE
fastfetch: rebase patches after update, support 10.4

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

@herbygillot Let’s have a special case, so we do not break something accidentally. (It is not only about rebasing patches, the build should be tested on every update.)

1. Fix Tiger (I do not intend to test it every time, but at least now it works).
2. Add support for humanly-readable host names for PowerPC systems.

(While I have bluetooth and physical memory modules compiling, I cannot verify the first works, and the second does not, and crashes the app when used. So I keep both disabled, no change here.)

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

macOS 10.4.11
Xcode 2.5

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@herbygillot 

10.4 on a PowerMac:
fastfetch_tiger2

10.6 on a PowerBook:
fastfetch_powerbook

**Comment by herbygillot** [comment]
That's fine, we'll merge this.  Thanks @barracuda156

**Comment by barracuda156** [comment]
@herbygillot Thank you for merging! So now the main version can be updated whenever, and no need to worry about patches. And I will try to update it for old systems, as long as it is feasible and makes sense.

**Comment by herbygillot** [comment]
Sounds good, many thanks

**Pull request merged**
