### PR TITLE
nco: Updated to version 4.7.7

### PR DESCRIPTION
**Pull request by thiagoveloso**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.1
Xcode 10.0

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM, but the port is not open maintainer so we'll need an approval from @tenomoto. (@tenomoto, are you willing to have this become openmaintainer?)

**Comment by kencu** [comment]
The checksums in the submission seem to be wrong. Please update them, force push the PR, and we'll see how that builds.

**Comment by kencu** [comment]
yep, that's got it. Thanks!

**Comment by thiagoveloso** [comment]
> yep, that's got it. Thanks!

Thank you for the hint @kencu! Hopefully @tenomoto will be OK with this update.

**Comment by kencu** [comment]
Oh, ya. I momentarily missed the part about it being closed maintainer. Apologies to tenomoto. Hopefully the one-decimal-point update will cause no issues for anyone.

**Pull request merged**
