### PR TITLE
vtm: update to 0.9.0

### PR DESCRIPTION
**Pull request by aeiouaeiouaeiouaeiouaeiouaeiou**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.8.5 12F2560 x86_64
Xcode 5.1.1 5B1008

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
*sigh*

The latest Xcode update on Monterey causes a linking bug: https://github.com/Homebrew/discussions/discussions/3659

**Comment by mascguy** [comment]
It looks like the final link crashes consistently for Monterey:

```
  [100%] Linking CXX executable vtm
  /opt/local/bin/cmake -E cmake_link_script CMakeFiles/vtm.dir/link.txt --verbose=ON
  /opt/local/bin/g++-mp-11 -pipe -Os -DNDEBUG -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -pthread -O3 -DNDEBUG -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -mmacosx-version-min=12.0 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk CMakeFiles/vtm.dir/vtm.cpp.o -o vtm  -Wl,-rpath,/opt/local/lib 
  0  0x101681ffa  __assert_rtn + 139
  1  0x1014b528d  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 4989
  2  0x1014a5f8f  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 207
  3  0x10151c9d4  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 2036
  4  0x10151ffa0  ___ZN2ld4tool10InputFilesC2ER7Options_block_invoke + 48
  5  0x7ff8079f234a  _dispatch_client_callout2 + 8
  6  0x7ff807a04c45  _dispatch_apply_invoke_and_wait + 213
  7  0x7ff807a04161  _dispatch_apply_with_attr_f + 1178
  8  0x7ff807a04327  dispatch_apply + 45
  9  0x10151fe2d  ld::tool::InputFiles::InputFiles(Options&) + 669
  10  0x101490d48  main + 840
  A linker snapshot was created at:
  	/tmp/vtm-2022-10-03-185152.ld-snapshot
  ld: Assertion failed: (_file->_atomsArrayCount == computedAtomCount && "more atoms allocated than expected"), function parse, file macho_relocatable_file.cpp, line 2061.
  collect2: error: ld returned 1 exit status
```

So we'll need to fix, before this can be merged.

**Comment by mascguy** [comment]
Just curious, can this port build with `macports-clang-XX`? I ask, as the following appears to be forcing use of `gcc11`:

```
compiler.fallback-append \
                        macports-gcc-11
```

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
> It looks like the final link crashes consistently for Monterey:

Is this also happening with Command Tools beta?

> Just curious, can this port build with `macports-clang-XX`?

As I commented Clang hangs with a memory leak on both CI and my system.
The topic above [some person suggested](https://github.com/orgs/Homebrew/discussions/3659#discussioncomment-3797873) that the bug occurs when the flag `-O3` is used. I don't know how to remove it from the compilation process, because Cmake adds it automatically when using the Release target.

**Comment by mascguy** [comment]
I just added some proposed changes, as a separate commit. The key changes are:
* Allow use of MacPorts Clang, avoiding Xcode Clang; the latter seems problematic
* Use build type `Debug` for `+debug`, with optimization disabled
* Use build type `RelWithDebInfo` for `-debug`, which uses `-O2` instead

**Comment by mascguy** [comment]
> * Allow use of MacPorts Clang, avoiding Xcode Clang; the latter seems problematic

While Xcode Clang is failing locally on 10.15, it's not a crash; rather, it's an outright build failure.

Might be fixable, but it's easier to avoid it for the moment.

**Comment by mascguy** [comment]
Looks good now, with the latest changes.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
