### PR TITLE
clang-11-bootstrap: fix build on macOS 10.5

### PR DESCRIPTION
**Pull request by catap**
#### Description

It removes runtime dependency from gcc10-bootstrap, and backports patch which allows to use this ports for cctools.

It is the first PR in series which allows to bootstrap ld64-latest on macOS 10.5 as simple as:
```
macos-leopard:~ catap$ sudo port installed
The following ports are currently installed:
  clang-11-bootstrap @11.1.0_1+emulated_tls (active)
  gcc10-bootstrap @10.3.0_5+universal (active)
macos-leopard:~ catap$ sudo port install ld64
--->  Computing dependencies for ld64
The following dependencies will be installed: 
 cctools-bootstrap
 cmake-bootstrap
 ld64-latest
 legacy-support
 libblocksruntime
 libcxx
 libmacho-headers
 libtapi
 libunwind-headers
 python27-bootstrap
 xz-bootstrap
Continue? [Y/n]:
```

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.5.8 9L34 i386
Xcode 3.1.4 9M2809

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
@Gcenx if I recall right you've asked to remove runtime dependency from gcc10 :) here it is.

**Comment by barracuda156** [comment]
@catap Great!
Next we should bring Iain's PPC fixes from `darwin-xtools` into Macports. Then we can get much improved `ld64` on PPC systems too.

**Comment by catap** [comment]
@mascguy maybe also this one if buildbots aren’t used? :)

**Review by mascguy — APPROVED** [review]
LGTM, I'll merge once the buildbots finish with `mustc`.

**Comment by mascguy** [comment]
While the buildbots are still working on `mrustc-rust`, we might as well queue this up before other commits come in. Thanks Kirill!

**Pull request merged**
