### PR TITLE
golang-1.0 portgroup: improve support for dependencies hosted on custom domains

### PR DESCRIPTION
**Pull request by amake**
#### Description

Non-trivial golang projects have lots of dependencies, and sometimes those are hosted on custom domains outside of the usual GitHub, Bitbucket, etc.

This PR adds a new `resolves_to` keyword to `go.vendors`: when a dependency is hosted at a custom domain, specify the package name as referenced in the source code as the "main" package, and specify the resolved GitHub, etc., name with `resolves_to`.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.15.6 19G2021
Xcode 12.0 12A7209

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by amake** [comment]
@herbygillot @breun @i0ntempest 

This is one step towards improving support for golang dependencies with custom domain names.

Do you think it would be better to swap the "resolved" and "alias" packages? I.e. instead of

```
                    github.com/mvdan/editorconfig \
                        alias   mvdan.cc/editorconfig \
                        lock    e40951bde157 \
                        rmd160  1262f81708a7f5f626fa77318897780a3104373a \
                        sha256  ff6d5f23da7cfd2d9afaa6f139365cd6d2a52f56ffc4a44e727bc9096c959744 \
                        size    9311
```

it would be something like

```
                    mvdan.cc/editorconfig \
                        resolves_to   github.com/mvdan/editorconfig \
                        lock    e40951bde157 \
                        rmd160  1262f81708a7f5f626fa77318897780a3104373a \
                        sha256  ff6d5f23da7cfd2d9afaa6f139365cd6d2a52f56ffc4a44e727bc9096c959744 \
                        size    9311
```

...but `alias` was easier to implement and I couldn't think of a good keyword (I don't like `resolves_to`).

I have an update to go2port almost ready that can generate `alias` entries automatically.

**Comment by i0ntempest** [comment]
Personally I prefer it swapped, so the first line of each dep is always what comes directly from the project, then one can manually add the actual URL. `resolves_to` sounds good to me. Others I can think of are `url_override`, `override_url`, `real_url` or just `override`.

**Comment by amake** [comment]
OK, I've changed it to `resolves_to`.

**Comment by mohd-akram** [comment]
Another possibility for the name: `repo`. The [docs](https://golang.org/cmd/go/#hdr-Remote_import_paths) refer to that part as `repo-root`. Later, the `vcs` attribute might be required.

**Comment by amake** [comment]
I'm OK with `repo`.

Does anyone have any other suggestions?

**Pull request merged**
