### PR TITLE
carthage: Update to 0.40.0

### PR DESCRIPTION
**Pull request by nre-ableton**
#### Description

Updates carthage to [0.40.0](https://github.com/Carthage/Carthage/releases/tag/0.40.0).

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.7 23H124 x86_64
Xcode 16.0 16A242d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] ~referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message?~ (N/A) 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by saagarjha — APPROVED** [review]
Built and ran it and it seems to work

**Review by reneeotten — COMMENTED** [review]
Why is this using git instead of fetching a tarball. The comment states it needs submodules but you're not actually doing that. Please verify.

**Comment by nre-ableton** [comment]
> Why is this using git instead of fetching a tarball. The comment states it needs submodules but you're not actually doing that. Please verify.

I have no idea, this is something that @saagarjha might know about. I only opened this PR because I need the latest carthage version, but I haven't done any maintenance for the package in the past.

I would say that this is an improvement that should be done in a future PR unrelated to this one. The priority should be having a port published for the latest version.

**Comment by reneeotten** [comment]
> > Why is this using git instead of fetching a tarball. The comment states it needs submodules but you're not actually doing that. Please verify.
> 
> I have no idea, this is something that @saagarjha might know about. I only opened this PR because I need the latest carthage version, but I haven't done any maintenance for the package in the past.
> 
> I would say that this is an improvement that should be done in a future PR unrelated to this one. The priority should be having a port published for the latest version.

that's fair ;) @saagarjha can you please follow up on this?

**Comment by nre-ableton** [comment]
@reneeotten Thanks for merging!

**Pull request merged**
