### PR TITLE
libqtxdg-legacy, qt4-mimetypes: new ports for Qt4

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

New ports to provide support for Qt4.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Ha, the failure is irrelevant. Let me drop the conflict with `libqtxdg` – it is not my ports which are broken but existing `libqtxdg`.

**Comment by barracuda156** [comment]
@mascguy How could we handle this correctly? In principle, a conflict should be set in `libqtxdg` portfile with this port. However, `libqtxdg` is broken for unrelated reasons, and if I include it, it sabotages CI. Obviously I can skip CI, but then it is not seen that these two ports build fine and can be merged.

**Comment by mascguy** [comment]
> @mascguy How could we handle this correctly? In principle, a conflict should be set in `libqtxdg` portfile with this port. However, `libqtxdg` is broken for unrelated reasons, and if I include it, it sabotages CI. Obviously I can skip CI, but then it is not seen that these two ports build fine and can be merged.

Go ahead and create a separate PR for the conflict addition. Just be sure to make it clear that this PR needs to be merged first.

**Comment by barracuda156** [comment]
> Go ahead and create a separate PR for the conflict addition. Just be sure to make it clear that this PR needs to be merged first.

@mascguy Done! https://github.com/macports/macports-ports/pull/20176

**Comment by barracuda156** [comment]
@mascguy @reneeotten Good to merge now?

**Pull request merged**
