### PR TITLE
hydra: update to 9.1 & new variants

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by i0ntempest** [comment]
No idea why its failing on Xcode 9.4 and below, maybe bad OpenSSL version?

**Comment by kencu** [comment]
> No idea why its failing on Xcode 9.4 and below, maybe bad OpenSSL version?

This port needs work. It's building with "cc" which is a no-go. The build is failing because it is passing ```-L/usr/lib```  totally unnecessarily, and this finds the old system versions of libraries first, rather than the new libraries we want it to find in ```-L/opt/local/lib```, which comes too late in the link line.

Start with the ```makefile``` PG, and then do surgery on the build files to strip out the crud.

**Comment by i0ntempest** [comment]
Added an override and a reinplace, should be fine now

**Comment by kencu** [comment]
Yeah, that's better -- we got a real "CC" now, and the link line is no longer broken, so the port builds on the systems tested here -- bet it still fails building universal though, as there is no ```[get_canonical_archflags cc]```, not to mention in unknown other ways. But at least this does work as far as it is tested here by CI. Thanks.

**Pull request merged**
