### PR TITLE
apache-arrow: update to 14.0.2; R-arrow: update to 14.0.0.2

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update Arrow.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

macOS 14.2.1
Xcode 15.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@mascguy Christopher, could you please say how did you solve this earlier for python subports?
```
  Executing:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_apache-arrow/py39-pyarrow/work/arrow-14.0.1/python" && /opt/local/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 setup.py --no-user-cfg bdist_wheel 
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_apache-arrow/py39-pyarrow/work/arrow-14.0.1/python/setup.py:34: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources
  /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
  !!
  
          ********************************************************************************
          Requirements should be satisfied by a PEP 517 installer.
          If you are using pip, you can try `pip install --use-pep517`.
          ********************************************************************************
  
  !!
    dist.fetch_build_eggs(dist.setup_requires)
  WARNING: The index url "''" seems invalid, please provide a scheme.
  WARNING: Location '''/setuptools-scm/' is ignored: it is either a non-existing path or lacks a specific scheme.
  WARNING: Location '''' is ignored: it is either a non-existing path or lacks a specific scheme.
  ERROR: Could not find a version that satisfies the requirement setuptools_scm<8.0.0 (from versions: none)
  ERROR: No matching distribution found for setuptools_scm<8.0.0
  Traceback (most recent call last):
    File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
      subprocess.check_call(cmd)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/opt/local/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_apache-arrow/py39-pyarrow/work/.tmp/tmptjmoxhwg', '--quiet', '--index-url', "''", '--find-links', "''", 'setuptools_scm<8.0.0']' returned non-zero exit status 1.
```

**Comment by barracuda156** [comment]
@reneeotten @ryandesign @jmroot If anyone knows why python subports fail here, please help me to fix this.

**Comment by jmroot** [comment]
> @reneeotten @ryandesign @jmroot If anyone knows why python subports fail here, please help me to fix this.

Those subports are set up so strangely that it's a case of "If I were going there, I wouldn't start here." I would put them in a separate py-pyarrow Portfile, use the sdist from https://pypi.org/project/pyarrow/ rather than fetching with git, and do a normal PEP 517 build as far as possible (I take it at least some configuration is necessary), and install with installer as per the default, not pip.

The apache-arrow port itself should probably also use the release tarball available at https://arrow.apache.org/install/.

**Comment by barracuda156** [comment]
@jmroot Thank you, I will try changing this according to your suggestion.

**Comment by reneeotten** [comment]
@barracuda156 can you please try and wrap up open/draft PRs -like this one- in the queue?

**Comment by barracuda156** [comment]
@reneeotten I will try to finalize or close pending ones over the weekend.

**Pull request closed without merging**
