### PR TITLE
gjs: fix for systems where latest mozjs fails

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Fix this finally.

I can confirm that it actually works: at least I can build apps requiring it:

polari

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@mascguy Could you please take a look? The change is only for older systems, so should be fairly uncontroversial, I hope. (It depends on `mozjs60` PR for actually working for older systems, but not for CI.)

**Comment by pmetzger** [comment]
You modified patches used on newer systems, not just on older systems.

**Comment by barracuda156** [comment]
> You modified patches used on newer systems, not just on older systems.

@pmetzger Where?

**Comment by pmetzger** [comment]
My mistake. I misread. (One of the reasons why these complicated Portfiles are a pain in the neck to review.)

**Pull request merged**
