### PR TITLE
various Python ports: remove EOL subports

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
- remove subports for EOL Python versions in various ports maintained by @GiovanniBussi
- general clean-up of unnecessary lines (i.e., setting default values) in the Portfiles 

###### Tested on
macOS x.y
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
@reneeotten please wait before merging, I have to fix the checksums. Thanks!

**Comment by GiovanniBussi** [comment]
Please apply [this change](https://github.com/GiovanniBussi/macports-ports/pull/1/commits/81bf4824a96df4ab8962385986f1b94ebeef3c1c) as well.

Then for me it can be merged. Thanks!

**Comment by GiovanniBussi** [comment]
Sorry, the fix didn't work on macos-11... I am not sure you can see the log of my GitHub action.

It seems like the checksum that I used on macos-10.15 is not valid on macos-11. I am really puzzled...

Here's the relevant part of the log:
```
  --->  Checksumming barnaba-0.1.7.tar.gz
  DEBUG: Calculated (rmd160) is f6e4f68d5af8149e9a884e6dc88fbe77545507e6
  Portfile checksum: barnaba-0.1.7.tar.gz rmd160 e57a589dbcaf231e992f0e252517e602495443b6
  Error: Checksum (rmd160) mismatch for barnaba-0.1.7.tar.gz
  Distfile checksum: barnaba-0.1.7.tar.gz rmd160 f6e4f68d5af8149e9a884e6dc88fbe77545507e6
  DEBUG: Calculated (sha256) is 392402230279c710a263062d52a239d5a9cbebd19946f6dd03dbc8453c62dc87
  Portfile checksum: barnaba-0.1.7.tar.gz sha256 217904208a5efb4dbd04d23910fad1ffe201c3dd7607a8adb08b9583bdd08c58
  Error: Checksum (sha256) mismatch for barnaba-0.1.7.tar.gz
  DEBUG: Calculated (size) is 30260068
  Error: Checksum (size) mismatch for barnaba-0.1.7.tar.gz
  Distfile checksum: barnaba-0.1.7.tar.gz sha256 392402230279c710a263062d52a239d5a9cbebd19946f6dd03dbc8453c62dc87
  Portfile checksum: barnaba-0.1.7.tar.gz size 30260069
  Distfile checksum: barnaba-0.1.7.tar.gz size 30260068
  The correct checksum line may be:
  checksums           rmd160  f6e4f68d5af8149e9a884e6dc88fbe77545507e6 \
                      sha256  392402230279c710a263062d52a239d5a9cbebd19946f6dd03dbc8453c62dc87 \
                      size    30260068
```

Do you know which could be the explanation?

**Comment by reneeotten** [comment]
> Do you know which could be the explanation?

It looks like that the file downloaded from GitHub indeed has a different checksum than the the file that was mirrored by MacPorts at the time the Portfile was last updated (see [here](https://distfiles.macports.org/py-barnaba/)).

```
 % openssl dgst -sha256 barnaba-0.1.7-*
SHA2-256(barnaba-0.1.7-github-upstream.tar.gz)= 7751634bdbb700667d683f21f1baf42ebea7b763c35c8c64c3f74698553486df
SHA2-256(barnaba-0.1.7-macports.tar.gz)= 392402230279c710a263062d52a239d5a9cbebd19946f6dd03dbc8453c62dc87
```

as of to why that is the case is another question: upstream might have done a [stealth update](https://trac.macports.org/wiki/PortfileRecipes#stealth-updates).... You could/should probably bring that up with them and/or compare the two archives and see what has changed and if the change is harmless you could follow the recipe for a stealth-update to resolve this. 

Since it is not related to the changes in the current PR I will go ahead and merge this now and leave it up to you to figure out the checksum issue.

**Pull request merged**
