### PR TITLE
[WIP] tcl, tk: update to 8.6.9

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description

**Edit:** updated to use Tcl/Tk 8.6.9rc4.

Tcl/Tk 8.6.9 is not yet officially released; this is just to try out the latest release candidates (`rc4` is temporarily appended to the `distname` for each port). This release has been pushed back a few times to allow for ongoing macOS-related improvements (fixes for 10.14 Mojave, as well as general cleanup).

There is not yet an announcement on when this release will be designated as the final one, but I would guess that rc4 will become the final release in 4 days (Nov. 16-17), based on how the Tcl/Tk team intended to make rc3 the final release after 4 days if objections were not raised.

I am not aware which ports depending on Tcl/Tk need to be revbumped, if any. The past few times the `tcl` and `tk` ports were updated, any revbumping ended up being done after the fact in separate commits.

**Edit:** for reference, here is the Tk commit that supersedes the tkMacOSXXStubs.c patch: https://github.com/tcltk/tk/commit/2b654510d6fca2f2be0c3540816433d768ae2e41#diff-fd5cbb565c67a2dc96a2c3e79cc88a08

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.1 18B75
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

This is the only one I am aware of:
Tkinter test fails with macos Mojave: https://trac.macports.org/ticket/57357

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
See https://github.com/macports/macports-ports/pull/2971#issuecomment-438102141

- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
I tried `tclsh8.6` and `wish8.6`, and a few demos. Also works with `p5.26-tcl-ptk`.

### CODE REVIEW

**Comment by ryandesign** [comment]
> Port tk's dependencies **fail** on xcode10. [Log](https://paste.macports.org/43efcaa0904e)

https://trac.macports.org/ticket/57457

**Comment by pmetzger** [comment]
Is this currently "work in progress/don't merge"? If so, the `WIP` tag should be applied.

**Comment by chrstphrchvz** [comment]
> Is this currently "work in progress/don't merge"? If so, the `WIP` tag should be applied.

Would that be something @macportsbot should apply automatically if e.g. `\[?WIP\]?` in title, or rare enough for a member to handle? 

Yes, I would rather wait until the final release before merging, unless Mojave users are in need of MacPorts' Tk working at all (Tk 8.6.8 windows are completely black in Mojave).

Still waiting on the next RC—Kevin Walzer (Tk Mac developer) [announced yesterday](https://code.activestate.com/lists/tcl-core/20416/) that they are at a point where another one could be built, though [sqlite 3.25.3](https://code.activestate.com/lists/tcl-core/20409/) sounds like another thing they might spend time getting included into the final release (I'm not sure if that has any bearing on the `tcl-sqlite3` port).

**Comment by chrstphrchvz** [comment]
Updated to Tcl/Tk 8.6.9rc4 published today; will edit the first comment. In particular:

- [x] tried existing tests with `sudo port test`?

I have test results for `tcl` as well as `tk +quartz` (by temporarily including `test.run yes` in the portfile`): https://gist.github.com/chrstphrchvz/8564f5525d40e28a47c1ee7571ded10a. Tests aren't enabled for `tk` presumably because they can't be run for the `+x11` variant. They might be run for `+quartz`, but there is an error when attempting to do so at least in trace mode:
```
DYLD_LIBRARY_PATH="`pwd`:/opt/local/lib:${DYLD_LIBRARY_PATH}"; …
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /opt/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
```
I'm guessing `/opt/local/lib/libJPEG.dylib` should be `/opt/local/lib/libjpeg.dylib` (note this is on a case-insensitive APFS volume). I haven't yet found if this is also the case for `tk` 8.6.8; if it is, I'll open a ticket.

**Pull request closed without merging**
