### PR TITLE
aspell-dict-*: Use lang name instead lang code in the description

### PR DESCRIPTION
**Pull request by judaew**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
@judaew Since you're updating these, would you be willing to fix the lint warnings too?

**Comment by judaew** [comment]
@mascguy, done.

**Review by mascguy — APPROVED** [review]
LGTM, will merge once CI completes.

And thank you so much for fixing the lint warnings too, much appreciated!

**Comment by judaew** [comment]
Thanks for the review!

**Pull request merged**
