### PR TITLE
CMake 1.1 PG: samu, distcc and better static lib support

### PR DESCRIPTION
**Pull request by RJVB**
CMake 1.1 PG: samu, distcc and better static lib support

This aggregate commit introduces
- support for using port:samu instead of port:ninja
- support for building with distcc
- improved static library generation using ar/nm/ranlib that match the
  selected compiler (if it's not the default).
- various fixes and improvements I implemented over the years

###### Type(s)

- [x] bugfix
- [x] enhancement

###### Tested on
OS X 10.9

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
I think this PR changes AR to be llvm-ar in many cases, and fwiw llvm-ar is unable to handle +universal builds <https://trac.macports.org/ticket/60169>.

Otherwise many interesting ideas in here. It will be hard for someone to commit this, as it is so core to the builds of so many ports, and the blowback and wreckage from even a tiny error or unexpected change will be extremely severe on the lists and in the tickets.

Your likely path forward would be to factor it into separate, digestible pieces, or to promote a new, parallel cmake-X PG, which will be hard to sell, probably.

**Comment by RJVB** [comment]
>Otherwise many interesting ideas in here.

If the change in ar is the only known blocker: it will be easy to disable that bit when `variant_isset universal` (and not obtained through the muniversal mechanism). It would make sense to do this because AFAICR LTO builds also fail in universal mode (not that I ever do those ... :) )

I'm not at all motivated to break this up, certainly not with the speed at which PRs get processed and I'd apparently have to wait for feedback. I'd rather face the storm and handle everything thrown at me as much as possible in a short lapse of time.
What I could do is have another look at what other changes could lead to unforeseen issues (if you have ideas about that, please spew), and provide options to disable them. Those options can easily be discarded later.

Do remember that I'm not the only one using my ports tree, and I haven't had blowback yet.

**Comment by kencu** [comment]
Understood. There are probably only three or four people on MP who would be able to commit this and withstand the wrath of any errors that turned up in it. We'll leave this here until one of them commits it, or until it's 2025...

**Comment by kencu** [comment]
RVJB -- I greatly appreciate your insights -- your knowledge of MacPorts surpasses my own in every way. There are interesting things in here I may try to incorporate into MacPorts over the next months.

But -- we both know this PR will never be committed, so I'll close it, and return to it for inspiration over time.

**Pull request closed without merging**
