### PR TITLE
leptonica: Update to version 1.74.1

### PR DESCRIPTION
**Pull request by stweil**
This also involves switching to releases from GitHub.
Fix also a typo in the description.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by tobypeterson** [comment]
Why is this pulling from github? This version seems to be available on http://www.leptonica.com/download.html

Presumably that also won't require rerunning all the autotools, too.

**Comment by stweil** [comment]
That's correct. I had chosen GitHub because Leptonica switched to GitHub, so that is the primary source, but as you noticed, Dan is still providing tagged versions on the Leptonica website. I don't mind if you drop my PR. The important thing is the new version.

**Comment by tobypeterson** [comment]
This PR is good, but I think you could simplify things by using the source from the website. It's already been autotooled, so you can probably avoid adding the autoreconf step and all those build dependencies. So it'd be a much more standard update.

**Comment by tobypeterson** [comment]
Closing - simple update done in 590683168cafe732885fde17105f5c39cb032dbc

**Pull request closed without merging**
