### PR TITLE
delete old ports requiring OpenSSL 0.9

### PR DESCRIPTION
**Pull request by janstary**
These ports are more than a decade old, have no maintainer,
have a dead homepage, and ask for OpenSSL 0.9. Nobody should
be using these, and they could not have built in a long time.

### CODE REVIEW

**Comment by pmetzger** [comment]
I think that given that they could not have built in a long time, removing them (rather than obsoleting them) seems fine. I'll give other people some hours to comment and see if anyone disagrees.

**Comment by pmetzger** [comment]
No one seems to have commented, so I'm going to merge. We can always get them back from git if needed. Thanks for your help cleaning this up.

**Comment by gaming-hacker** [comment]
Have you managed to build any version of 1.1.x on osx 10.12+?

**Comment by ryandesign** [comment]
> they could not have built in a long time

Based on what?

Jan mentioned these ports on the mailing list in regard to their dependency declaration `lib:libssl.0.9:openssl`. This method of declaring a dependency has not been recommended for a decade or more, but is not invalid. It means "If a file libssl.0.9.dylib exists in any lib directory, that satisfies the dependency, otherwise install the openssl port to satisfy the dependency."

Some of them install fine:

```
$ sudo port -s install links1 +ssl
--->  Computing dependencies for links1
--->  Fetching distfiles for links1
--->  Verifying checksums for links1
--->  Extracting links1
--->  Configuring links1
--->  Building links1
--->  Staging links1 into destroot
--->  Installing links1 @1.00pre14_0+ssl
--->  Activating links1 @1.00pre14_0+ssl
--->  Cleaning links1
$ sudo port -s install jabber +ssl
--->  Computing dependencies for jabber
--->  Fetching distfiles for jabber
--->  Verifying checksums for jabber
--->  Extracting jabber
--->  Configuring jabber
--->  Building jabber
--->  Staging jabber into destroot
--->  Installing jabber @1.4.2_5+ssl
--->  Activating jabber @1.4.2_5+ssl
--->  Cleaning jabber
$ sudo port -s install qpopper +ssl
--->  Computing dependencies for qpopper
--->  Fetching distfiles for qpopper
--->  Verifying checksums for qpopper
--->  Extracting qpopper
--->  Applying patches to qpopper
--->  Configuring qpopper
--->  Building qpopper
--->  Staging qpopper into destroot
--->  Installing qpopper @4.1.0_0+ssl
--->  Activating qpopper @4.1.0_0+ssl
--->  Cleaning qpopper
--->  Some of the ports you installed have notes:
  qpopper has the following notes:
    To use qpopper, you'll need to add it to inetd.conf/xinetd.d/launchd depending on what you use on your system.
    
    For inetd, something like:
    pop3  stream  tcp  nowait  root  /usr/libexec/tcpd  /opt/local/sbin/popper
    should do it.
    
    For xinetd, you'll find in /opt/local/etc/xinetd.d/ a file called qpopper-dist that you should edit and copy to /etc/xinetd.d/
    
    In both cases, don't forget to tell (x)inetd to reload their configuration.
    For launchd, you'll find in /opt/local/Library/LaunchDaemons/ a file called org.macports.mail.qpopper.plist-dist that you should edit and copy to
    /Library/LaunchDaemons/
    To get TLS/SSL working, you need to set up certificates. Cf: http://www.eudora.com/qpopper/faq.html#tls
```

So please revert the deletion.

**Comment by janstary** [comment]
>>    they could not have built in a long time
> Based on what?

Based on what Perry said; should have checked.

But I do believe these should go at any rate. They are dead, abandoned ports
with dead homepages. And they run on OpenSSL 0.9, which we should discourage.

MP does not provide `libssl.0.9`; the only way to find it (imho) is to link against
the system `/usr/lib/libssl.0.9.*` (which does exist even in 10.13.2 here).

Note the `lib:` vs `path:` elsewhere. In all other ports, we insist on dependencies provided by MP,
as opposed to system defaults (which is debatable of course). Why would we let _these_ slide,
in particular when they demand an _ancient_ utterly broken library which is the opposite of security
it is supposed to provide?

**Comment by pmetzger** [comment]
@janstary, if @ryandesign feels we should revert the deletion, we should very likely do as he asks, and at the very least discuss it.

That said, I'm feeling leery about having very crusty things in the ports tree that no one has done any security vetting on or maintenance of in a long time. But this shouldn't prevent us from reverting this for the moment.

**Comment by pmetzger** [comment]
BTW, I was under the impression that they weren't currently building given what @janstary was saying, I should have checked.

**Comment by janstary** [comment]
> BTW, I was under the impression that they weren't currently building given what @janstary was saying, I should have checked.

My bad for making it look like that, sorry. They apparently do build,
presumably against the system libssl.0.9.x (which nobody should use).

But there are other reason to completely remove them anyway.
Let's see first whether anyone uses them at all.

**Comment by janstary** [comment]
It is imho reasonable to put them back if someone wants them enough to fix them first.

**Comment by pmetzger** [comment]
@janstary, @ryandesign asked us to revert it. Is there a _good_ reason not to do that for the moment?

**Comment by pmetzger** [comment]
Okay, initial attempt to create a pull request reverting just the one change failed. (I find GitHub and Git opaque sometimes.) Will try again shortly.

**Comment by raimue** [comment]
Even if these ports are compatible with OpenSSL 1.x, I see no value in keeping them. Just the fact that they were never touched for a decade shows that they are entirely unmaintained. Probably also no users.

Most of these ports do not even have upstream homepages anymore. Jan even listed reasons for each of them in the linked pull requests. They are obsolete and outdated, enough reason to get rid of them no matter what OpenSSL they link with.

What is the point of bringing them back?

**Comment by pmetzger** [comment]
@raimue I will let you and @ryandesign decide between you then. I feel like I'm not qualified to pick a course of action if the two of you disagree.

**Comment by raimue** [comment]
For the sake of completeness, the ports were restored by @jmroot in c05c88c12dc5dddfdf11bb0a004bd43570e527de and received additional changes afterwards.

**Comment by janstary** [comment]
Yes, they are back, patched with FreeBSD patches. But they should die anyway.
https://github.com/macports/macports-ports/commit/494ceebdd7d1c08b6cde2e071512fc39dade3df1#r28683063

**Comment by pmetzger** [comment]
> But they should die anyway.

Above my pay grade. If more senior members of the project think they should be in place, then I'm not going to argue.

**Pull request merged**
