### PR TITLE
Change over from protobuf-cpp to protobuf3-cpp

### PR DESCRIPTION
**Pull request by pmetzger**
Also from py27-protobuf to py27-protobuf3.

This is intended as a replacement for #690 

Note these changes have been performed quite mechanically, and are not tested. We need to discuss this before it gets merged.

As requested by @mojca 

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Note that I probably should also fix the commit message a bit but I'm not sure what would be the right one.

**Comment by pmetzger** [comment]
It seems like some of the failures above are real. In particular, protobuf-c's failure is real, but it might be that the port just needs updating.

**Comment by pmetzger** [comment]
I'm going to update to add the revbumps (good catch!), but I don't know what to do about the rest.

**Comment by pmetzger** [comment]
So a big problem for me on this is I really just don't know much about the protobuf library or its versions. Someone who is a domain expert could probably tell us if simply obsoleting the old one and switching everything to the new would be practical. As has been said, another alternative would be disambiguating the installed library names so that both can be installed at the same time. 

If the old one is truly no longer needed, then I'd say obsoleting would be better. However, as I said, answering such questions is beyond what I know about the library.

**Comment by raimue** [comment]
I do not know much about this library either, but I did a quick look on what other package managers are doing. It does not seem necessary to provide both protobuf 2.x and protobuf 3.x at the same time. See https://trac.macports.org/ticket/56135#comment:2

**Comment by pmetzger** [comment]
@raimue I commented on the ticket, but your notion of getting rid of the old protobuf library and doing some renaming seems good to me. It will probably require that we upgrade some of the client ports, but that's not a big job.

**Comment by pmetzger** [comment]
I've now requested a pullup for a fully updated `protobuf-c`: https://github.com/macports/macports-ports/pull/1654

The very old version wasn't compatible with protobuf3-cpp.

**Comment by pmetzger** [comment]
By the way, I'm just keeping this open as a placeholder for the project at the moment. We should be done with the whole thing within a few more days. The main current obstacle appears to be "Ola", which will require some patches to build with a recent protobuf implementation.

**Comment by kencu** [comment]
So, @pmetzger, what needs to happen here to get this moving?

**Comment by pmetzger** [comment]
I need to make an hour or two to finish it up. I left tickets for a few ports (like ola) hoping that the maintainers would do something about the issue, but they didn't. I will try to get to this in the next few days.

**Comment by kencu** [comment]
ping

**Comment by ryandesign** [comment]
> if done this way, the update will break for all users of these ports and will need a manual intervention because it will not be possible to install the port protobuf3-cpp as long as protobuf-cpp remains active and conflicting with protobuf3-cpp

Just wanted to point out that [this problem is in fact now occurring](https://lists.macports.org/pipermail/macports-users/2018-July/045480.html) for users.

**Comment by pmetzger** [comment]
My fault. I got quite distracted and busy. If someone wants to pitch in on finishing this up, I wouldn't say no, but I'll try to finish it off ASAP.

**Comment by kencu** [comment]
Most of these ports have been updated in various ways since the (aging) PR. How about we close this PR and deal with this on a port-by-port basis.

**Comment by pmetzger** [comment]
> Most of these ports have been updated in various ways since the (aging) PR. How about we close this PR and deal with this on a port-by-port basis.

I'm okay with closing it, but we need to have something open to track what's left.

**Comment by pmetzger** [comment]
I'm going to close this for the moment. I'll some up with another way to track what is left.

**Pull request closed without merging**
