### PR TITLE
pure-gen: revbump to create binary with latest PG haskell_cabal

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by essandess** [comment]
Should be merged against #22695

**Comment by reneeotten** [comment]
@essandess please address CI failure

**Comment by essandess** [comment]
> @essandess please address CI failure

I'm not sure that there's anything I can do to address these logged CI errors:

> ```sh
> Error: Failed to install dependencies for pure-gen
> /Users/runner/work/_temp/e3a2f3e9-834e-4dde-a1ad-49fe83f3810d.sh: line 77:  4721 Terminated: 15          tail -f "$workdir/logs/dependencies-progress.txt" 2> /dev/null
> Error: Process completed with exit code 1.
> ```

> ```sh
> 2024-02-25T22:35:49.0901800Z ##[group]Run . ports/.github/workflows/bootstrap.sh024-02-25T22:35:49.0902240Z > ESC[36;1m. ports/.github/workflows/bootstrap.shESC[0m
> 2024-02-25T22:35:49.0992120Z shell: /bin/bash -e {0}
> 2024-02-25T22:35:49.0992350Z ##[endgroup]
> 2024-02-25T22:35:49.1625040Z ##[group]Fetching files
> 2024-02-25T22:35:49.1625390Z Fetching getopt...
> 2024-02-25T22:35:49.1627870Z Fetching MacPorts...
> 2024-02-25T22:35:49.1630780Z Fetching PortIndex from https://ftp.fau.de/macports/release/ports/PortIndex_darwin_23_arm/PortIndex ...
> 2024-02-25T22:35:49.1633290Z ##[endgroup]
> 2024-02-25T22:35:49.1634360Z ##[group]Info
> 2024-02-25T22:35:49.1716320Z macOS version: 14.2.1
> 2024-02-25T22:35:49.6868510Z IP address: 13.105.117.124
> 2024-02-25T22:35:49.9528650Z curl: (22) The requested URL returned error: 403
> 2024-02-25T22:35:49.9538440Z Can reach private packages server: no
> 2024-02-25T22:35:49.9544920Z ##[endgroup]
> ```

This is simply a revbump and the linter doesn'tt throw any errors:
> ```sh
> port lint --nitpick pure-gen
> --->  Verifying Portfile for pure-gen
> --->  0 errors and 0 warnings found.
> ```

**Comment by ryandesign** [comment]
> I'm not sure that there's anything I can do to address these logged CI errors:
> 
> > ```shell
> > Error: Failed to install dependencies for pure-gen
> > /Users/runner/work/_temp/e3a2f3e9-834e-4dde-a1ad-49fe83f3810d.sh: line 77:  4721 Terminated: 15          tail -f "$workdir/logs/dependencies-progress.txt" 2> /dev/null
> > Error: Process completed with exit code 1.
> > ```

Right, it's a preexisting problem that pure-gen cannot be built for arm64 because of a port it depends on:

```
Error: Cannot install pure for the arch 'arm64' because
Error: its dependency llvm-3.4 only supports the archs 'ppc ppc64 i386 x86_64'.
```

No need to do anything about that in this PR since it's unrelated.

**Pull request merged**
