### PR TITLE
glab: new port

### PR DESCRIPTION
**Pull request by profclems**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by harens** [comment]
Hi there @profclems, thanks for submitting this port.

Just looking through, it would be preferable if we could build this from source rather than using the binary.

Glancing through your project, it seems like a fairly standard go setup should be sufficient for the port. I advise looking through the [Go PortGroup docs](https://guide.macports.org/chunked/reference.portgroup.html#reference.portgroup.golang), and making use of the [go2port](https://github.com/amake/go2port) tool.

Let me know if you have any questions or need help on anything, and I'd be more than happy to assist. Thanks.

**Comment by profclems** [comment]
Thanks @harens! I will a look at the go2port tool and rewrite the Portfile

**Comment by harens** [comment]
So...I had some free time on my hands, and I thought I'd try and help out on this one :)

On my fork: https://github.com/harens/macports-ports/blob/glab/devel/glab/Portfile
Download: [Portfile.zip](https://github.com/macports/macports-ports/files/5904177/Portfile.zip)

```
```

**Comment by harens** [comment]
So...I had some free time on my hands, so I thought I'd try and help :)

I wrote a portfile that builds successfully on my machine that you might find interesting. You can find it on my fork: https://github.com/harens/macports-ports/blob/glab/devel/glab/Portfile

Since I want this to be a learning experience 📚 (because learning is good), I thought I'd just note what I changed:

- The `go.setup` already defines the name for us, so we don't need to do it again.
- We can break down the long description into different lines.
- The GitHub homepage is set by the Go PortGroup (since it's basically using the GitHub PG in the background)

https://github.com/macports/macports-ports/blob/51dc5d0dd87bfc5918fe730719bc515bd0d831f1/_resources/port1.0/group/golang-1.0.tcl#L75

- You mention in your commit msg that "go.vendors does not support dependencies hosted outside of github.com and bitbucket". This isn't strictly true (e.g. gitlab, gopkg.in, etc. are supported).
- The reason why `go.googlesource.com` didn't work is because they don't serve stable tarballs. I therefore changed it to `github.com/protocolbuffers/protobuf-go`.

Also, I just wanted to mention how amazing your project looks ✨. It supports fish/zsh/bash completion, and we can make use of that! I therefore added that to the port.

Your project also supports man pages. I spent a bit of time trying to set this up (since MacPorts supports this), but since it's generated from a go file, I didn't find it that straightforward.

I tried a few things, but the closest I got was running this during the post-build stage...

```tcl
system "${go.bin} run ${worksrcpath}/cmd/gen-docs/docs.go --manpage --path ${worksrcpath}/share/man/man1"
```

...and then adding the files in the post-destroot stage. For some reason that didn't work, so I don't know if you have any thoughts on this (if we don't get it to work, that's fine too since it's not necessary).

As always, let me know if you have any questions, and thank you for adding this port 👍.

**Comment by profclems** [comment]
Thanks a lot, @harens!

**Comment by profclems** [comment]
@harens you did everything! Thanks a lot. 

I would like you to have the honours.
So if you have some time on your hands, I would like to close this PR, so you reopen it with the changes on your fork and change the maintainer to your name. 

You can later open a PR on [glab](https://github.com/profclems/glab) adding the installation guide for the port on our readme.

Thanks again

**Comment by harens** [comment]
Yay! 🎉 I'm glad everything's worked, and thank you for submitting this portfile @profclems.

> I would like to close this PR, so you reopen it with the changes on your fork and change the maintainer to your name.

I'd be delighted to maintain/co-maintain the port. Let me know which you would prefer.

> You can later open a PR on glab adding the installation guide for the port on our readme.

If the PR is merged, I'd be happy (and honoured) to add the instructions to your readme. Thank you.

All the best.
Haren :)

**Comment by profclems** [comment]
Thanks a lot @harens... As I said, I'm closing this PR so you reopen with your fork.

I will be glad if you maintain this port

**Pull request closed without merging**
