### PR TITLE
qt4-mac/kdelibs4 : convert hardwired graphics system selection to use…

### PR DESCRIPTION
**Pull request by RJVB**
…r option

port:kdelibs4 used to set the Raster graphics system (unless prevented from doing so).
This causes graphics issues on newer OS versions. This change puts the graphics
system under user control via Qt's own qtconfig utility. Port notes and a tooltip
in qtconfig inform and guide the user.

* modifies patch-kapplications-raster.diff (kdelibs4) so it does nothing under
  normal conditions
* patches the Qt4 buildsystem so qtconfig is built on Mac too
* adds a GUI to select the graphics system to qtconfig
* revbumps both ports

Closes: https://trac.macports.org/ticket/57577

### CODE REVIEW

**Comment by pmetzger** [comment]
There are conflicts vs. the master branch.

**Comment by RJVB** [comment]
> There are conflicts vs. the master branch.

Initially yes, but a priori I corrected the one conflict (revision number of port:kdelibs4 ...), and I now see 

```
This branch has no conflicts with the base branch
```
just above this reply box.

**Comment by pmetzger** [comment]
"This branch cannot be rebased due to conflicts"

**Comment by michaelld** [comment]
1) I also see "This branch cannot be rebased due to conflicts". I can't get GitHub to do anything with this PR until whatever the issue is is resolved.

2) I added Nicos for kdelib4 changes. I can see how 1 PR to fix both is desirable, but since I don't use KDE I can't speak as to whether the changes herein work there or not. Hopefully Nicos can.

**Comment by RJVB** [comment]
That's annoying because I cannot get github to correct any conflict and I don't see anything to correct myself either. I left "Allow edits from maintainers" ticket because of that resolved/non-resolved conflict, is that not helpful here?

FWIW, @NicosPavlov had already been assigned automatically.

**Comment by RJVB** [comment]
I recreated my local branch and force-pushed, did that help?

**Comment by michaelld** [comment]
Yes that force push got us back to being able to merge. I'll test this out for the qt4-mac part.

**Comment by michaelld** [comment]
Looks like the patch files "patch-tools-build_qtconfig.diff" and "patch-graphicssystem-via-qtconfig.diff" are missing ...

**Comment by RJVB** [comment]
Of course I had to mess the repair up too...

**Comment by pmetzger** [comment]
@michaelld I'm guessing the ball is in your court?

**Comment by michaelld** [comment]
@pmetzger yes it is ... will try to get to it shortly ... no guarantees as my workload is crazy this week getting code done before the US holiday break.

**Comment by michaelld** [comment]
For the qt4-mac part of this PR, the changes seem to work as advertised. I'm not sure what happens with I run "qtconfig" and change settings, but they do seem to be saved between sessions ... and, just maybe, are actually used when Qt is executed from anywhere by that same user? I'll try out some Qt apps & see what happens ...

**Comment by RJVB** [comment]
Yes, Qtconfig saves settings in a file read by every app (including itself, twice :)) when it starts, and the graphics system setting is applied somewhere in/under the QApplication ctor, just after the check for an existing QT_GRAPHICSSYSTEM env. variable.

2 easy ways to check:
- select native raster mode, save, restart qtconfig.Then pick one of the incompatible widget styles (CDE, Plastique, Windows) and do NOT save; qtconfig is expected to crash
- select opengl mode, save. Start any Qt app and you should see more or less subtle graphic differences (and output on the calling terminal if you start the app that way).

**Comment by michaelld** [comment]
OK I'll try out some things & see what happens. I wonder why the `qtconfig` app wasn't being built by the default OSX Qt4 install ... any ideas?

**Comment by RJVB** [comment]
I think that was purely a Qt decision: "users shouldn't be able to tweak look and feel on Mac" (or Windows or anything not Linux).

**Comment by michaelld** [comment]
Yeah probably. OK so yeah this change seems to allow (1) building and install of "qtconfig", which in turn allows (2) user-global setting of various Qt4 parameters. It looks like any Qt-based apps will use these settings; note that non-Qt-based apps that use Qt will have to issue their own settings; they don't seem to pick up the settings from `qtconfig` or `QT_GRAPHICSSYSTEM`.

**Comment by michaelld** [comment]
All of this said, I can't speak to what this PR does for KDE. I'll let others decide that part. The qt4-mac part is good to go.

**Comment by RJVB** [comment]
> note that non-Qt-based apps that use Qt will have to issue their own settings; they don't seem to pick up the settings from `qtconfig` or `QT_GRAPHICSSYSTEM`.

Do you have examples?

But yeah, applications that don't use QApplication will not see this, but can they use Qt to put up a GUI (= are they even concerned by the graphics system mode)? While testing this I tried to create a QWidget before creating a QApplication instance and got an abort because of that.

But let's face it, the main intended beneficiaries for this change are the KDE4 applications.

**Comment by NicosPavlov** [comment]
I did only a rather quick test, but the change seems to induce quite some instabilities. With the patched kdelibs4, applications crash quite often, to the point of being barely usable. 
This does not seem to occur with the current kdelibs4 (even with the patched qt4-mac). 
This also seem to happen in case of the Raster mode, while the Native mode appears to be more stable.

**Comment by RJVB** [comment]
I don't understand how that can be, doesn't seem to make sense. *Unless* you happen to be using one of the incompatible widget styles, but then native mode should indeed solve any crashing.

I've been running this change since writing it, with raster mode. Not a new issue in sight. But then I rarely run anything except the KDE PIM suite these days. I did try with kate, the oxygen-demo and kdevelop though.

Can you give some examples of which applications crash, and if any way possible, show a backtrace (from DrKonqi or Apple's own crash reporter)?

What happens when you start applications with the current kdelibs4 and RasterOff set in the environment? That should be equivalent to running this patch.

**Comment by RJVB** [comment]
PS: there is of course a tiny possibility that the old/current kapplication patch somehow masked an issue in kdelibs, one that has been addressed in the commits after 4.14.3 .

Don't forget, kdelibs4 has been seeing some continued maintained because not all KDE applications have yet been ported to KF5. Mostly with backports from KF5 frameworks that either make KDE4 apps better behaved alongside KF5 apps, but also some bugfixes.
My port:kdelibs4 has been tracking those commits.

**Comment by NicosPavlov** [comment]
OK, then I am slightly confused. 
This patch aims at building qtconfig, which allows to choose the widget styles and graphics system, and the point is to make it possible for users to choose the Raster graphics system to avoid some graphical glitches in more recent OSes, which I have personally not encountered. Is that correct?

Now you are saying that Raster is expected to crash if used with incompatible widgets. For the best of what I tried, all styles either crash when selected in qtconfig, or lead to crashes in KDE with Raster. Which styles are supposedly compatible with Raster?

I now have even qtconfig crashing with a style I chose, so that I'll have to find the settings file manually to reset that. If such crashes are expected with these patches, I am not sure they should be pushed.

**Comment by RJVB** [comment]
Certain widget styles are expected to crash on Mac when raster mode is activated, yes. You should be able to show that too in the current Qt4 version, or with the qtconfig patch if you set the graphics system to "(unset)". In other words, users who set QT_GRAPHICSSYSTEM=Raster in their environment with unpatched Qt and kdelibs4 that no longer sets raster mode are going to see the same thing IFF they use one of those widget styles.

Among the styles concerned I think there is only Plastique which has some likelihood of being used. But:

- Users of pure Qt applications are not likely to be using a non-default widget style as they never had access to QtConfig before
- KDE users who use that style (or another incompatible style) have the choice of NOT activating raster mode in QtConfig.

If needed I can probably build in a failsafe in qtconfig or in Qt itself that disallows selecting an incompatible combination and it's not excluded that I can patch the actual reason for crashing. Or we could simply remove the widget styles (most of them can be deactivated via the build system) - if that leads to bug reports then at least we will know if anyone actually cares about using them. 

I was incredulous about the graphics glitches at first too, but they seem to be real enough to get this kind of workaround in.

**Comment by NicosPavlov** [comment]
I am not disputing the potential need for that patch, but the fact is that at this point, the notes of the port recommend to use the raster mode to avoid glitches, but I cannot find a style that is stable in that graphics system. 
The styles I have access to are:
- crashing within qtconfig when trying to select it: CDE, Motif, Windows
- crashing in Kate with Raster (when trying to open): Cleanlooks, Macintosh (aqua), Plastique

The trace shows that the crash happens in drawing functions. I could attach it to the related ticket. We should have a clear idea of at least a sure working set that we can point out to users before pushing this, as the current codes and instructions lead to an unstable system, at least according to my tests. 

If I get it right, you have been testing the patches on a different system, as you kept up with updates in KDE4. This might indeed be the difference.

**Comment by RJVB** [comment]
On Saturday November 24 2018 08:04:09 NicosPavlov wrote:

I've been looking at this in more detail:

> The styles I have access to are:
> - crashing within qtconfig when trying to select it: CDE, Motif, Windows

Yes, switching to these styles while in raster mode causes a crash when a CGImageMaskRef is released. It's not a NULL ref but an invalid pointer, which suggests that the actual bug is overwriting an address elsewhere in the Mac drawing code.

> - crashing in Kate with Raster (when trying to open): Cleanlooks, Macintosh (aqua), Plastique

And that doesn't happen for me. I tried that specifically when I got the hunch that the venom is in the style switc. How do you select the style to be used, via the `-style` commandline argument? I tried both that and setting the `widgetStyle` setting in the General section of the kdeglobals settings file. No issues with either.

> We should have a clear idea of at least a sure working set that we can point out to users before pushing this, as the current codes and instructions lead to an unstable system, at least according to my tests. 

I agree, and I've tried to make it clear in the instructions that one should try the Native graphics system in case of issues.
I can also try to make qtconfig run with the native graphics regardless of the choice the user makes, the equivalent of always starting it with `QT_GRAPHICSSYSTEM=Native`.

> If I get it right, you have been testing the patches on a different system, as you kept up with updates in KDE4. This might indeed be the difference.

Except that I don't see any commit since 4.14.3 that appears to affect behaviour when changing widget styles (from platform default to user-selected) during startup.

To summarise,

- you don't see pure Qt applications crashing when started in raster mode and with one of the problem widget styles?
- but with that same combination KDE applications will crash?

Do you have the same widget style selection set via qtconfig and in kdeglobals? I've always done that though it is not a requirement (cf. my tests with Kate above).

What happens when you set the graphics system to "(unset") or "Native" and then launch KDE4 applications with `RasterOn=1` in the environment? This should restart the old behaviour.

If that resolves the issue for you we may have a way out. I should be able to check in `KApplicationPrivate::preqapplicationhack()` whether the user set the preferred graphics system via qtconfig. In absence of such a choice we can activate raster mode as before while otherwise we'd do nothing. That way users can still select Native graphics via qtconfig, and nothing should change for those who do nothing.
In fact, let's try that, I'll post an updated patch (via inline comment, sorry for that)

**Comment by RJVB** [comment]
Below is a new version of the kapplication raster patch that restores the old behaviour for users who have not made any changes through qtconfig:

```
diff --git a/kdeui/kernel/kapplication.cpp b/kdeui/kernel/kapplication.cpp
index b093034..3e1b2f2 100644
--- a/kdeui/kernel/kapplication.cpp
+++ b/kdeui/kernel/kapplication.cpp
@@ -207,7 +207,11 @@ public:
   QString sessionConfigName() const;
   void init(bool GUIenabled=true);
   void parseCommandLine( ); // Handle KDE arguments (Using KCmdLineArgs)
+#ifdef Q_OS_MAC
+  static void preqapplicationhack(bool GUIenabled = true);
+#else
   static void preqapplicationhack();
+#endif
   static void preread_app_startup_id();
   void read_app_startup_id();
 
@@ -342,7 +346,11 @@ static SmcConn mySmcConnection = 0;
 #endif
 
 KApplication::KApplication(bool GUIenabled)
+#ifdef Q_OS_MAC
+    : QApplication((KApplicationPrivate::preqapplicationhack(GUIenabled),KCmdLineArgs::qtArgc()), KCmdLineArgs::qtArgv(), GUIenabled),
+#else
     : QApplication((KApplicationPrivate::preqapplicationhack(),KCmdLineArgs::qtArgc()), KCmdLineArgs::qtArgv(), GUIenabled),
+#endif
     d(new KApplicationPrivate(this))
 {
     d->read_app_startup_id();
@@ -402,10 +432,39 @@ KApplication::KApplication(Display *display, int& argc, char** argv, const QByte
 }
 #endif
 
+#ifdef Q_OS_MAC
+static bool useRaster = true;
+void KApplication::doNotUseRaster()
+{
+    useRaster = false;
+}
+#endif
+
 // this function is called in KApplication ctors while evaluating arguments to QApplication ctor,
 // i.e. before QApplication ctor is called
+#ifdef Q_OS_MAC
+void KApplicationPrivate::preqapplicationhack(bool GUIenabled)
+#else
 void KApplicationPrivate::preqapplicationhack()
+#endif
 {
+#ifdef Q_OS_MAC
+    // Setting env RasterOff avoids setting raster. Can be used for before/after
+    // testing and to work around an application failing when raster is set.
+
+    // Fetch the default graphics system from Qt's settings store managed via qtconfig
+    QSettings settings(QSettings::UserScope, QLatin1String("Trolltech"));
+    settings.beginGroup(QLatin1String("Qt"));
+    const QString defaultGraphicsSystem = settings.value(QLatin1String("DefaultGraphicsSystem")).toString();
+    if (defaultGraphicsSystem.isNull() || defaultGraphicsSystem.isEmpty()) {
+        // only force raster mode here when not overriden via qtconfig or one of our own mechanisms
+        if (getenv("RasterOff") == NULL) {
+            if (useRaster && GUIenabled) {
+                QApplication::setGraphicsSystem(QString("raster"));
+            }
+        }
+    }
+#endif
     preread_app_startup_id();
 
     KGlobal::config(); // initialize qt plugin path (see KComponentDataPrivate::lazyInit)
diff --git a/kdeui/kernel/kapplication.h b/kdeui/kernel/kapplication.h
index fa2ab26..cc21e76 100644
--- a/kdeui/kernel/kapplication.h
+++ b/kdeui/kernel/kapplication.h
@@ -403,6 +403,14 @@ public:
    */
   static bool loadedByKdeinit;
 
+#ifdef Q_OS_MAC
+  /**
+   * Use before creating KApplication in an app which fails with raster
+   * graphics, such as KMyMoney. Most KDE apps on OS X run better with raster.
+   */
+  static void doNotUseRaster();
+#endif
+
 public Q_SLOTS:
   /**
    * Updates the last user action timestamp to the given time, or to the current time,
```

**Comment by RJVB** [comment]
Interesting observation:

I didn't see any of the mentioned crashing in KDE4 application because ... I had QT_GRAPHICSSYSTEM=Raster set in my environment.

Now this is Finagle making overtime: that's just a different way of setting Raster mode... see the proposed change to qapplication.cpp .

Either way, I can thus now confirm myself that the modified (v2.0) kapplication raster patch change provides a useable workaround.

**Comment by RJVB** [comment]
And this can be added to the graphicssystem-via-qtconfig patch:

```
diff --git main.cpp main.cpp
index a0f5dd6ed3cc204f61041bc65f96b1af88bdbb97..1cbb8538d5c8706b223e89fcaca70e9000db1c8b 100644
--- main.cpp
+++ main.cpp
@@ -51,6 +51,13 @@ int main(int argc, char **argv)
 {
     Q_INIT_RESOURCE(qtconfig);
 
+    const QByteArray graphicsSystem = qgetenv("QT_GRAPHICSSYSTEM");
+    if (graphicsSystem.isNull() || graphicsSystem.isEmpty()) {
+        // force native graphics mode unless the user set one via QT_GRAPHICSSYSTEM.
+        // We have to use QT_GRAPHICSSYSTEM because that will override any previous
+        // settings stored in our own settings store.
+        qputenv("QT_GRAPHICSSYSTEM", "Native");
+    }
     QApplication app(argc, argv);
 
     QTranslator translator;
```

**Comment by jjstickel** [comment]
@RJVB  Everything is good to go here, right? We are just waiting for @NicosPavlov to review?

**Comment by RJVB** [comment]
yep!

**Comment by michaelld** [comment]
Looks like there have been a few changes since the last time I checked in. Let me rebuild & verify for qt4-mac ...

**Comment by michaelld** [comment]
--->  Applying patch-graphicssystem-via-qtconfig.diff
Executing:  cd "/opt/local/var/macports/build/_opt_sources_MacPorts_ports_github_macports_aqua_qt4-mac/qt4-mac/work/qt-everywhere-opensource-src-4.8.7" && /usr/bin/patch -p0 < '/opt/sources/MacPorts/ports/github_macports/aqua/qt4-mac/files/patch-graphicssystem-via-qtconfig.diff'
patching file src/gui/kernel/qapplication.cpp
can't find file to patch at input line 30
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git main.cpp main.cpp
|index a0f5dd6ed3cc204f61041bc65f96b1af88bdbb97..1cbb8538d5c8706b223e89fcaca70e9000db1c8b 100644
|--- main.cpp
|+++ main.cpp
--------------------------
File to patch:
Skip this patch? [y]
Skipping patch.
1 out of 1 hunk ignored

**Comment by RJVB** [comment]
OK, my bad for cutting corners...

**Comment by michaelld** [comment]
That works; thanks for updating. I'm building right now ... will post back shortly once I can test the end result.

**Comment by michaelld** [comment]
Ok this latest change still seems to work for qt4-mac. So I'm good to go (again) for that port.

**Comment by michaelld** [comment]
Still waiting for @NicosPavlov to review I guess ...

**Comment by RJVB** [comment]
Great, then someone who can might want to push this...

**Comment by NicosPavlov** [comment]
Sure. I have other obligations right now, but I'll take care of it in the next 1-2 days.

**Pull request merged**
