### PR TITLE
hwloc2: new port submission

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [x] submission
- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G1012
Xcode 11.2.1 11B500
and
macOS 10.15.2 19C56a
Xcode 11.2.1 11B500 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by i0ntempest** [comment]
I have a question though, is xorg(-server) not supposed to be added in dependencies even if the GUI portion of the program cannot be used without it? Like, `R +tcltk` needs `xorg-server` to show GUI but `xorg-server` is not in its dependencies.

**Comment by mf2k** [comment]
Why are you not updating the existing hwloc port?

**Comment by mf2k** [comment]
Any portfile questions should be raised on the [macports-dev mailing list](https://lists.macports.org/mailman/listinfo/macports-dev/).

**Comment by i0ntempest** [comment]
@mf2k Because 1.x is still maintained as “ultrastable” branch on their website and a lot of stuff depends on it, I think maybe it’s better to make a new port so I don’t break stuff.

**Comment by mf2k** [comment]
Are you saying at least some of the ports that depend on the current hwloc port will not work with hwloc 2.x?

**Comment by i0ntempest** [comment]
@mf2k I don't know how to test them so I've no idea if they'll work or not. They do seem to compile and install fine tho.

**Comment by mf2k** [comment]
I'm very much against adding a new port for hwloc based on version especially with no maintainer. I think the current hwloc port should simply be updated to the latest version. If a dependent is found not to work, then a sub-port for the old 1.x version can be added later.

**Comment by i0ntempest** [comment]
Okay then, I'm closing this.

**Pull request closed without merging**
