### PR TITLE
opencv4: fix build on powerpc, add support for gtk

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Some minor general improvements plus fixes for PowerPC.

@mascguy @stromnov When you have time, could you please take a look?

P. S. No revbump, since nothing changes for systems where this port is supported.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@mascguy @reneeotten @pmetzger It’s been 11 days, anyone could review this? Should be uncontroversial.

**Comment by barracuda156** [comment]
Bump

**Comment by pmetzger** [comment]
There is more here than I have time right now to review.

**Comment by barracuda156** [comment]
@reneeotten Could we merge this finally?

**Comment by reneeotten** [comment]
I have no way of validating the changes you are making here. Nothing has been submitted and/or discussed upstream, so I'll not be merging this without maintainer approval.

**Comment by barracuda156** [comment]
@mascguy Any chance of looking into this?

**Comment by mascguy** [comment]
> @mascguy Any chance of looking into this?

The key concern is how much work it will be to maintain these patches. But as long as you will be here to help with those, perhaps we can merge it.

**Comment by barracuda156** [comment]
@mascguy Maybe make a peg with this for legacy systems? It is certainly worth having the port fixed; it may less be to keep updating it for old systems. (Though here I don’t think my patching is particularly huge or complex; Accelerate one is just restored, and it is still there in opencv3 port. Enabling GTK is trivial and arguably a general improvement.)

**Comment by barracuda156** [comment]
Okay, w/e, let it be broken then here.

**Comment by mascguy** [comment]
> Okay, w/e, let it be broken then here.

Geez, please be patient, particularly during the holidays...

**Review by mascguy — APPROVED** [review]

**Comment by kencu** [comment]
and this will only be of use on 10.6-PPC anyway

**Comment by mascguy** [comment]
> and this will only be of use on 10.6-PPC anyway

That's okay, Sergey has contributed a lot to MacPorts. So I'm happy to accept this change.

**Comment by barracuda156** [comment]
@kencu Well, first of all, it is not uncommon that something builds for a newer system but not for the older. There are countless examples of this, and no one seems to object (Go is broken on older Intel, Rust is broken on older Intel, forget individual ports). Then, this still makes it easier to fix it for 10.5, if you or anyone wants to: just switch it from dispatch to mach semaphores. Finally, this may help on i386, though I did not test it.

**Comment by kencu** [comment]
10.6 for PPC should have it’s own custom repo for ports that only are of use there, or for mods to ports that are only of use to support it. 

I think it does, actually.

Why these are being shoehorned into macports is beyond me.

It’s one thing to “be nice” to somebody, I guess… but WTH?

**Comment by barracuda156** [comment]
@kencu Ken, the idea with libdispatch-legacy was to support more than just 10a190. No one had time to make it work on Leopard so far, but it does not mean it’s _impossible_.

There are nearly no 10a190-specific fixes in upstream MacPorts tree, as I have mentioned a number of times. There are not many of them overall, and I can probably list those from memory and count on fingers.

However, those are irrelevant now, and I am gonna retire 10a190 patches to non-default variants locally and subsequently drop.

We have 10.6.8 on PowerPC.

And besides Pythons which Josh and you insist on having broken in MacPorts (Python bugs are not specific to 10a190), everything else builds so far out of the box on 10.6.8.
I started building everything from zero on a clean 10.6.8 on my Quad yesterday, and should have the complete toolchain today. GCC builds and works with zero patches, cmake-bootstap patch is dropped, gnulib PG fix dropped, openssl switch to MacPorts Perl dropped (system one of 10.6.8 is fine). Possibly, a couple of GL-related fixes should be retained (xorg-server is the suspect), I will check that later.

**Comment by barracuda156** [comment]
@kencu Aside of that MacPorts has broken the default Boost now, everything went smoothly, I got gcc14 on 10.6.8 ppc without patching `darwin.h`, and everything works.

**Pull request merged**
