### PR TITLE
Update socket_vmnet to 1.1.4

### PR DESCRIPTION
**Pull request by subpop**
##### Description

Update socket_vmnet to v1.1.4 (this version incorporates the Availability.h patch previously carried downstream).

Set the SOURCE_DATE_EPOCH build variable to a value computed by examining the latest modified times of the source directory.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 14.2.1 23C71 arm64
Xcode 15.2 15C500b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
Doesn't computing the variable based on a time on the build machine mean we can't get a reproducible build? Why not just set the variable to an arbitrary value?

**Comment by pmetzger** [comment]
@subpop ping

**Comment by subpop** [comment]
> Doesn't computing the variable based on a time on the build machine mean we can't get a reproducible build? Why not just set the variable to an arbitrary value?

My understanding of this snippet of code is that it finds the latest modified time of all files in the archive and sets SOURCE_TIME_EPOCH to that value. That shouldn’t change based on the build machine. I suppose we could verify that by comparing the value on the different build machines.

**Comment by pmetzger** [comment]
It finds the latest modified time of the files that are present. Regardless, it doesn't seem like a good idea?

**Comment by subpop** [comment]
I wasn't sure. I read over the [Trac ticket](https://trac.macports.org/ticket/59672) and read through existing implementations of `SOURCE_DATE_EPOCH` in the current ports. There doesn't seem to be a consistent approach, so I picked one. It certainly would be easier to set it to a fixed value instead of computing it from the archive. So unless MacPorts has a documented solution for how to handle `SOURCE_DATE_EPOCH`, I'll revert that change and just set it to a fixed value.

**Comment by subpop** [comment]
Hm. @pmetzger, this was merged before I had a chance to revert the change. How strongly do you feel that the current implementation should be altered to align with our discussion on this PR?

**Comment by pmetzger** [comment]
@reneeotten It doesn't seem correct to me, but if it's widely used that's probably an issue for the dev mailing list.

**Pull request merged**
