### PR TITLE
fsdb, fsdb_select: update to 3.4

### PR DESCRIPTION
**Pull request by cardi**
#### Description
fsdb, fsdb_select: update to 3.4
* update livecheck to working URL
* add new executables to fsdb_select

###### Tested on
macOS 12.7.2 21G1974 arm64
Xcode 13.1 13A1030d

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
@cardi Do you know why the CI failed?

**Comment by reneeotten** [comment]
I did restart a CI run but it fails in the same way as the other. Please take a look and fix @cardi

**Comment by cardi** [comment]
The build was successful for [macos-12](https://github.com/macports/macports-ports/actions/runs/8088609229/job/22349281795?pr=22847) but fails on macos-13 and macos-14.

Looking at one of the [logs for macos-13](https://productionresultssa5.blob.core.windows.net/actions-results/8a972cdb-4dc5-49d6-a3a6-c2ba261a4381/workflow-job-run-3ba6ce1b-6cdc-5f71-375c-479d9e760893/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-03-09T12%3A11%3A54Z&sig=Dn2Caq571MhKoxsuyPIVo81mhao%2FsHB2s6Tj84xRu6Y%3D&sp=r&spr=https&sr=b&st=2024-03-09T12%3A01%3A49Z&sv=2021-12-02):
```
2024-03-06T15:23:45.9370840Z Executing:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_perl_fsdb/fsdb/work/Fsdb-3.4" && /usr/bin/make -j4 -w all 
2024-03-06T15:23:45.9373340Z DEBUG: system:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_perl_fsdb/fsdb/work/Fsdb-3.4" && /usr/bin/make -j4 -w all 
2024-03-06T15:23:45.9688640Z make: Entering directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_perl_fsdb/fsdb/work/Fsdb-3.4'
2024-03-06T15:23:46.0389130Z make: *** No rule to make target `bin/cgi_to_db', needed by `blib/script/cgi_to_db'.  Stop.
2024-03-06T15:23:46.0391850Z make: *** Waiting for unfinished jobs....
```

In the successful [macos-12 build log](https://productionresultssa5.blob.core.windows.net/actions-results/eedf14b5-3b6b-4660-bdeb-36f035bc780c/workflow-job-run-68ae2b36-89dd-55dc-09eb-5ce01d4cd3c7/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-03-09T12%3A06%3A03Z&sig=J%2FjYHBi%2F42ZPPyxcKblXvwsFFfZEAWkgi24f3rL9%2BCo%3D&sp=r&spr=https&sr=b&st=2024-03-09T11%3A55%3A58Z&sv=2021-12-02), we get the expected result:
```
2024-02-28T23:42:14.5401710Z Executing:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_perl_fsdb/fsdb/work/Fsdb-3.4" && /usr/bin/make -j4 -w all 
2024-02-28T23:42:14.5404220Z DEBUG: system:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_perl_fsdb/fsdb/work/Fsdb-3.4" && /usr/bin/make -j4 -w all 
2024-02-28T23:42:14.5668300Z make: Entering directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_perl_fsdb/fsdb/work/Fsdb-3.4'
2024-02-28T23:42:14.6288180Z "/opt/local/bin/perl5.34" ./programize_module cgi_to_db < lib/Fsdb/Filter/cgi_to_db.pm > bin/cgi_to_db
```

So perhaps the Makefile isn't being generated properly, but it's not obvious to me why it's broken only on macos 13 and 14? I'll poke around more, but any general Perl port debugging thoughts are appreciated!

**Comment by cardi** [comment]
@pmetzger @reneeotten The issue is that macOS 13+ no longer has `groff` included by default (previously at `/usr/bin/groff`). `pod2man` (part of `perl5`) requires `groff` (or some sort of *roff)---which probably means that `perl5` should have `groff` as a dependency at some point.

The most recent commit https://github.com/macports/macports-ports/pull/22847/commits/4461893c821958da4801b9f2c4e133052788763f resolves this issue, and the CI now builds successfully.

**Pull request merged**
