### PR TITLE
bash: update to 5.2 patch 37, bash-devel: new port

### PR DESCRIPTION
**Pull request by dgilman**
#### Description

This doesn't have a fix for https://trac.macports.org/ticket/68638 . I made an initial attempt to cherry-pick that patch but it seemed hairy enough it's probably not worth maintaining.

But, to throw the affected a bone, I have added the bash-devel port that pulls in the latest devel branch. The fix is not in the 5.3-alpha release.

I didn't put this in as a Closes: because it doesn't really close the issue but can be persuaded if anyone feels strongly.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 14.6.1 23G93 x86_64
Xcode 16.1 16B40
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by raimue — COMMENTED** [review]
Update to bash @5.2 looks good to me. Thank you for the port update!

Some minor details on the bash-devel port in an inline comment. However, I wonder whether it is really worth to add this port, as I assume the interested audience would be quite small.

**Comment by raimue** [comment]
> Some minor details on the bash-devel port in an inline comment. However, I wonder whether it is really worth to add this port, as I assume the interested audience would be quite small.

Sorry, only now I finally realized you want to add bash-devel to fix the infamous bug with gettext. Yes, that seems enough to justify adding a new port.

**Comment by dgilman** [comment]
Date as the version number is a good idea. Not sure why it is failing on CI, I am going to try forcing it to use MP bison

**Comment by reneeotten** [comment]
@raimue are you okay with merging this; that isn't completely clear to me...

**Review by raimue — APPROVED** [review]
Looks good to me! :+1:

**Comment by raimue** [comment]
@reneeotten Thanks for the reminder. Sorry, I forgot to check again.

**Pull request merged**
