### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by l2dy**
Not having a license makes me feel uncomfortable. 😉

### CODE REVIEW

**Comment by tobypeterson** [comment]
Anyone have any feedback? I'm fairly indifferent. Seems unnecessary but harmless.

**Comment by raimue** [comment]
This is correct as far as LICENSE may only cover Portfiles. The ports tree contains lots of patches that are subject to the particular license of the upstream software they were created against. It is probably safe to assume all prior contributions were made under a 3-clause BSD license, so this should be fine.

As there was not much feedback here, please bring this to [macports-dev](https://lists.macports.org/mailman/listinfo/macports-dev).

**Comment by l2dy** [comment]
I resubscribed with handle@macports.org (as per the approval mail) and just realized that I can no longer post with my original email address. iCloud Mail only allows alias under icloud.com and Gmail asks me to setup SMTP. What should I do now?

**Comment by mojca** [comment]
I use gmail and don't have problems posting as `@macports.org`. I simply added the account without setting up the outgoing server.

**Comment by l2dy** [comment]
@mojca `Couldn't reach server. Please double-check the server and port number.` from that SMTP setup page.

**Comment by l2dy** [comment]
Perhaps adapting https://github.com/NixOS/nixpkgs/blob/master/COPYING would be better?

**Comment by raimue** [comment]
IANAL, but the new wording looks good to me.

Little nitpick: we do not call them "PortGroup scripts" anywhere else, the usual term would be just "PortGroups" or "port groups".

**Comment by l2dy** [comment]
@raimue Fixed.

When can I merge this? I've brought this to the mailing list but got little feedback.

**Comment by neverpanic** [comment]
@raimue @jmroot I think we can merge this. Objections?

**Comment by l2dy** [comment]
Merge OK?

**Pull request merged**
