### PR TITLE
Update to libpst v.0.6.76

### PR DESCRIPTION
**Pull request by srirangav**
#### Description

As requested in trac no. 63060, this pull request is a proposed changed to libpst's portfile to update to version 0.6.76.  See trac no. 63060

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix
- [x] update

###### Tested on

macOS 11.4

###### Verification 
Have you

- [] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [X] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
thanks for the update @srirangav. Please do change your commit message to follow the guidelines as described in the PR checklist. It should be `portname: short description`, so in this case `libpst: update to 0.6.76`. 

Additionally you now have a merge commit in this PR which we don't want. Please change your commit message (`git commit -a --amend`) and then rebase with master (`git fetch upstream ; git fetch rebase upstream/master`). Then you should have only one commit left with your intended changes; force-push to this PR and hopefully all will be good... For future reference, you will make your life easier when you start making changes in a separate branch instead of `master`. You can read up on the suggested workflow [here](https://trac.macports.org/wiki/WorkingWithGit#commit) (or elsewhere on the internet).

**Comment by srirangav** [comment]
Hi @reneeotten, I think I followed the instructions you provided, but I'm not sure I did it properly.  If I've messed this up somehow, I will redo it the way that is suggested in the macports wiki link you included.  Thanks.

**Comment by reneeotten** [comment]
> Hi @reneeotten, I think I followed the instructions you provided, but I'm not sure I did it properly. I think that I have done something wrong because I see more changes than I think I am supposed to (I think I was only supposed to see 1 change, but 'git status' showed me 9).
> 
> Here is what I did:
> 
>     1. Created a fork on github.com
> 
>     2. Clone the fork onto my computer: 'git clone https://github.com/srirangav/macports-ports.git'
> 
>     3. Add the the official repository as the upstream:  'git remote add upstream [git@github.com](mailto:git@github.com):macports/macports-ports.git'
> 
>     4. Updated from the upstream repository: 'git fetch upstream'
> 
>     5. Rebased from the upsteam repositiory: 'git rebase origin/master'
> 
>     6. Committed my changes with an updated message: ' git commit -a --amend -S'
> 
>     7. Pushed my changes back: 'git push origin master'
> 
> 
> I have a feeling the last step may have been a mistake - I think I was supposed to do 'git push upstream master', but I'm not sure how to fix this.
> 
> Should I just create a new fork and start over? Or is there something else I can do?
> 
> Sorry, I'm relatively new to Git. I hope to do this properly the next time I submit something.

As you noticed it didn't work completely as intended as you should have indeed ended up with only one commit for the change in the `libpst` port. I think your fifth command isn't correct as "Rebased from the upsteam repositiory" should be  'git rebase upstream/master'. The last step to push to the repository was correct; you can only push to `origin` (i.e., your fork on your GitHub page) since you do not have commit access to `upstream`. 

Anyway, the the trouble originates likely from the fact that you started making changes in the `master` branch; that is often asking for trouble. So after your forked the repository, added the `upstream` the first thing you should do is make a "branch"  and make your changes in there. 

So for example in this case I would have done:
1. `git checkout -b libpst`
2. edit the Portfile to make your changes
3. commit your changes: `git commit -a -m "libpst: update to 0.6.76"
4. push the changes to your branch: `git push origin`
5. then you can open a PR

If during the review you're asked for changes you can just go back to that branch if needed (i.e., `git checkout libpst`), make the requested changes, amend your commit (`git commit -a --amend`) and then you'll need to force-push to your fork since the commit history has changed (i.e., you will need to use the `-f` flag). You need to be a bit careful with force-pushing so you can add `--dry-run` first and verify that everything would get pushed to the correct location (i.e., `git push origin -f --dry-run`); if you're satisfied with it you do it again but now without the `--dry-run`. That will update the branch in your fork and will, therefore, automatically update the PR as well. 

I hope that helps! You could probably recover to a working situation in this PR, but it's likely easier for now to just close this PR and make a new one. That will also give you the opportunity to figure out if the description above makes sense and works for you.

**Comment by srirangav** [comment]
Hi @reneeotten, 

I deleted my prior fork and started with a new fork.  Here is what I did so far:

1. Cloned my fork to my computer: git clone https://github.com/srirangav/macports-ports.git
2. Set the upstream to the macports repository: git remote add upstream https://github.com/macports/macports-ports.git
3. created a branch to work on my changes: git checkout -b libpst-0.6.76
4. committed my changes: git commit -a -m "libpst: update to 0.6.76" -S

However, when I tried to do a 'git push origin' as you suggested, I received the following error message:

fatal: The current branch libpst-0.6.76 has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin libpst-0.6.76

I wasn't sure if I should push using the --set-upstream option as suggested by git, since I don't want mess this up again.  Could you let me know if I can use the command suggested by git, or if I should try something else?

Thanks very much for all your help!

**Comment by reneeotten** [comment]
Yes, the suggestion by git is correct. I always just copy that as I often cannot remember the exact use of "--set-upstream". After that you will be good to go!

**Comment by srirangav** [comment]
Thanks @reneeotten!  I have done this and will close this pull request and will open a new pull request.  I really appreciate all your help.

**Pull request closed without merging**
