### PR TITLE
gdb-apple: update to 2831

### PR DESCRIPTION
**Pull request by evanmiller**
#### Description

Move to the official GitHub repo (where the original tarball redirects), update the version, and include an i386 fix.

Tested on Tiger/PPC.

Closes: https://trac.macports.org/ticket/67370

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.4.11
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by evanmiller** [comment]
It looks like `/usr/bin/makeinfo` no longer ships with macOS so the build is failing on Ventura. The source files are old and so the MacPorts makeinfo won't work as a substitute. This port is intended for older systems so I am fine with the current behavior.

**Comment by evanmiller** [comment]
Maybe @mascguy or @kencu can take a look?

**Comment by mascguy** [comment]
I'll test this on my old MacBookPro17, running 10.5-x32. More to follow.

**Comment by mascguy** [comment]
> I'll test this on my old MacBookPro17, running 10.5/10.6 i386. More to follow.

Tested both 10.5 and 10.6 i386, as well as 10.15, and looks good.

**Review by mascguy — APPROVED** [review]

**Comment by Cebtenzzre** [comment]
I'm running into [Ticket #51516](https://trac.macports.org/ticket/51516) when trying to install this. Is there an official workaround that would allow me to use this port on macOS <=10.7?
```
:notice:fetch --->  Attempting to fetch gdb-2831.tar.gz from https://codeload.github.com/apple-oss-distributions/gdb/legacy.tar.gz/gdb-2831?dummy=
:debug:fetch Fetching distfile failed: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```

**Comment by evanmiller** [comment]
> I'm running into [Ticket #51516](https://trac.macports.org/ticket/51516) when trying to install this. Is there an official workaround that would allow me to use this port on macOS <=10.7?
> 
> ```
> :notice:fetch --->  Attempting to fetch gdb-2831.tar.gz from https://codeload.github.com/apple-oss-distributions/gdb/legacy.tar.gz/gdb-2831?dummy=
> :debug:fetch Fetching distfile failed: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
> ```

The best we have right now is to install a "bootstrap" version of MacPorts to /opt/bootstrap, use that to install curl, and then manually compile your main MacPorts with `--with-curlprefix=/opt/bootstrap`.

**Pull request merged**
