### PR TITLE
libjpeg-turbo: update to 2.0.6

### PR DESCRIPTION
**Pull request by jmroot**
Use official release tarball instead of github auto-generated snapshot,
re-enable tests, only add nasm dep if building for Intel archs.

###### Tested on
macOS 10.15.7 19H114
Xcode 12.3 12C33

### CODE REVIEW

**Comment by mascguy** [comment]
Looks good to me, very clean and simple. Anyone else?

**Comment by kencu** [comment]
when you try to install this +universal on a BigSur Intel system, it builds ```nasm``` +univeral with an arm64 slice -- which surprisingly does work -- although probably unnecessarily? Dunno -- should nasm be a skip arch_check?

**Comment by kencu** [comment]
universal build of this fails x86_64/arm64 on BigSur Intel.
[bigsur-universal-fail.log.zip](https://github.com/macports/macports-ports/files/5832997/bigsur-universal-fail.log.zip)

**Comment by kencu** [comment]
also fails universal build on BigSur even with muniversal PortGroup.

[bigsur-fail-universal-muniversalPG.log.zip](https://github.com/macports/macports-ports/files/5833016/bigsur-fail-universal-muniversalPG.log.zip)

**Comment by kencu** [comment]
obviously misconfiguring building the arm64 component:
```
--->  Configuring libjpeg-turbo for architecture arm64
Executing:  cd "/opt/local/var/macports/build/_opt_macportsofficial_macports-ports_graphics_libjpeg-turbo/libjpeg-turbo/work/build-arm64" && /opt/local/bin/cmake -G "CodeBlocks - Unix Makefiles" -DCMAKE_BUILD_TYPE=MacPorts -DCMAKE_INSTALL_PREFIX="/opt/local" -DCMAKE_INSTALL_NAME_DIR="/opt/local/lib" -DCMAKE_SYSTEM_PREFIX_PATH="/opt/local;/usr" -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_POLICY_DEFAULT_CMP0060=NEW -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_MODULE_PATH="/opt/local/share/cmake/Modules" -DCMAKE_PREFIX_PATH="/opt/local/share/cmake/Modules" -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH="/opt/local/lib" -Wno-dev -DWITH_JPEG8=1 -DCMAKE_OSX_DEPLOYMENT_TARGET="11.1" -DCMAKE_OSX_SYSROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk" -DCMAKE_OSX_ARCHITECTURES=arm64 /opt/local/var/macports/build/_opt_macportsofficial_macports-ports_graphics_libjpeg-turbo/libjpeg-turbo/work/libjpeg-turbo-2.0.6 
-- The C compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_BUILD_TYPE = MacPorts
-- VERSION = 2.0.6, BUILD = 20210118
-- 64-bit build (x86_64)
-- CMAKE_INSTALL_PREFIX = /opt/local
-- CMAKE_INSTALL_BINDIR = bin (/opt/local/bin)
-- CMAKE_INSTALL_DATAROOTDIR = share (/opt/local/share)
-- CMAKE_INSTALL_DOCDIR = share/doc/libjpeg-turbo (/opt/local/share/doc/libjpeg-turbo)
-- CMAKE_INSTALL_INCLUDEDIR = include (/opt/local/include)
-- CMAKE_INSTALL_LIBDIR = lib (/opt/local/lib)
-- CMAKE_INSTALL_MANDIR = share/man (/opt/local/share/man)
-- Shared libraries enabled (ENABLE_SHARED = 1)
-- Static libraries enabled (ENABLE_STATIC = 1)
-- 12-bit JPEG support disabled (WITH_12BIT = 0)
-- Arithmetic decoding support enabled (WITH_ARITH_DEC = 1)
-- Arithmetic encoding support enabled (WITH_ARITH_ENC = 1)
-- TurboJPEG API library enabled (WITH_TURBOJPEG = 1)
-- TurboJPEG Java wrapper disabled (WITH_JAVA = 0)
-- Emulating libjpeg API/ABI v8.0 (WITH_JPEG7 = 0, WITH_JPEG8 = 1)
-- libjpeg API shared library version = 8.2.2
-- Compiler flags = -pipe -Os -DNDEBUG -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk 
-- Linker flags = -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Performing Test HAVE_BUILTIN_CTZL
-- Performing Test HAVE_BUILTIN_CTZL - Success
-- Looking for include file locale.h
-- Looking for include file locale.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for memset
-- Looking for memset - found
-- Looking for memcpy
-- Looking for memcpy - found
-- Check size of unsigned char
-- Check size of unsigned char - done
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Performing Test INCOMPLETE_TYPES
-- Performing Test INCOMPLETE_TYPES - Success
-- Compiler supports pointers to undefined structures.
-- Performing Test RIGHT_SHIFT_IS_UNSIGNED
sh: /bin/ps: Operation not permitted
-- Performing Test RIGHT_SHIFT_IS_UNSIGNED - Failed
-- Performing Test __CHAR_UNSIGNED__
sh: /bin/ps: Operation not permitted
-- Performing Test __CHAR_UNSIGNED__ - Failed
-- Performing Test INLINE_WORKS
-- Performing Test INLINE_WORKS - Success
-- INLINE = __inline__ __attribute__((always_inline)) (FORCE_INLINE = 1)
-- Performing Test HAVE_THREAD_LOCAL
-- Performing Test HAVE_THREAD_LOCAL - Success
-- THREAD_LOCAL = __thread
-- CMAKE_EXECUTABLE_SUFFIX = 
-- The ASM_NASM compiler identification is NASM
-- Found assembler: /opt/local/bin/nasm
-- CMAKE_ASM_NASM_COMPILER = /opt/local/bin/nasm
-- CMAKE_ASM_NASM_OBJECT_FORMAT = macho64
-- CMAKE_ASM_NASM_FLAGS =  -DMACHO -D__x86_64__ -DPIC 
-- SIMD extensions: x86_64 (WITH_SIMD = 1)
-- FLOATTEST = sse
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_COMPILER


-- Build files have been written to: /opt/local/var/macports/build/_opt_macportsofficial_macports-ports_graphics_libjpeg-turbo/libjpeg-turbo/work/build-arm64

```

**Comment by kencu** [comment]
This is a build recipe for how to cross-compile libjpeg-turbo:
```
The following script demonstrates how to build libjpeg-turbo to run on the iPhone 5S/iPad Mini 2/iPad Air and newer.

IOS_PLATFORMDIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
IOS_SYSROOT=($IOS_PLATFORMDIR/Developer/SDKs/iPhoneOS*.sdk)
export CFLAGS="-Wall -arch arm64 -miphoneos-version-min=8.0 -funwind-tables"

cd {build_directory}

cat <<EOF >toolchain.cmake
set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_C_COMPILER /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang)
EOF

cmake -G"Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake \
  -DCMAKE_OSX_SYSROOT=${IOS_SYSROOT[0]} \
  [additional CMake flags] {source_directory}
make
```

from here: 

<https://chromium.googlesource.com/chromium/deps/libjpeg_turbo/+/HEAD/BUILDING.md>

**Comment by kencu** [comment]
This patch worked, with the muniversal PortGroup:
```
% port -v installed libjpeg-turbo
The following ports are currently installed:
  libjpeg-turbo @2.0.6_0+universal (active) platform='darwin 20' archs='arm64 x86_64' date='2021-01-18T17:50:56-0800'
```

```
--- CMakeLists.txt.orig	2021-01-18 17:45:01.000000000 -0800
+++ CMakeLists.txt	2021-01-18 17:47:33.000000000 -0800
@@ -38,6 +38,8 @@
 
 message(STATUS "VERSION = ${VERSION}, BUILD = ${BUILD}")
 
+set (CMAKE_SYSTEM_PROCESSOR ${CMAKE_OSX_ARCHITECTURES})
+
 # Detect CPU type and whether we're building 64-bit or 32-bit code
 math(EXPR BITS "${CMAKE_SIZEOF_VOID_P} * 8")
 string(TOLOWER ${CMAKE_SYSTEM_PROCESSOR} CMAKE_SYSTEM_PROCESSOR_LC)
```

**Comment by kencu** [comment]
you also will need my patch.

**Comment by kencu** [comment]
[patch-libjpegturbo-universal.diff.zip](https://github.com/macports/macports-ports/files/5833179/patch-libjpegturbo-universal.diff.zip)

**Comment by jmroot** [comment]
> you also will need my patch, I believe -- or something that accomplishes the same outcome.

I expect that's only a problem if building for arm64 on x86_64, but done.

**Pull request merged**
