### PR TITLE
remove man2html

### PR DESCRIPTION
**Pull request by janstary**
man2html only exists in the ports tree because it was agreed four years ago in https://trac.macports.org/ticket/38254
that it is beneficial to have a standalone `man2html` binary:
the `man` port also comes with its own `man2html`, but has dependencies.

However,

 * The output of the standalone `man2html` is of abysmal quality
 * We don't need html versions of manpages in the first place
 * It is unmaintained: the 3.0.1 version is from 1997, current homepage does not exist
 * If someone needs a html manpage, there is `groff -Thtml` in the base system,
    which produces a better output, and the mandoc port whose `mandoc -Thtml`
    produces way better output.

As far as I can see, two port are "using" it: 
 * bibclean's ./configure detects it but never calls it
 * lirc calls what it thinks is man's man2html, producing a set of empty html manpages

Just drop this cruft.

Tested on 10.13.2 with XCode 9.2

### CODE REVIEW

**Comment by ctreleaven** [comment]
Do you propose that we make 'man' a build dep for lirc?  At least for the time being?

**Comment by ctreleaven** [comment]
Sorry, I'm unfamiliar with pull requests.  Have you verified that your proposed changes to lirc will actually allow a successful build?  I believe I added the man2html build dep because the build fell over without it.  (Didn't know that 'man' provides a better version.)

**Comment by janstary** [comment]
@ctreleaven Yes, I changed lirc now to require the 'man' port
- as a side-effect of this man2html removal we see that it never even worked for lirc.

With th standlone `man2html` as provided by the man2html port,
all of the html manpages of LIRC's manual (chapter 4) fail to get generated
- they don;t contain anythong except the failed man2html's error message.

With the `man2html` provided by the man port, they get generated.
They are ugly, don't fit the page width, containa broken link to man2html,
but thay exist and the LIRC information itself  (i.e. the content of the manage) is there.
This is what I propose to do for now (until we talk to upstream).

Without man or the standalone man2html, the lirc build system "builds"
the html manual anyway, with Chapter 4 consisting of broken links to
the nonexistent html manpages.

There is nothing in LIRC's ./configure regarding this.
If a `man2html` is fnd, run it; if not, screw it.

NB: The API ocumentation is a different thing.
It is built with Doxygen an is not related to this.

If @ctreleaven agrees, this removes the man2html as a dependency of lirc.
Removing it as a dependency of bibclean (which doesn't really use it)
then means we can remove man2html altogether.

**Comment by janstary** [comment]
Great, Travis fails after timing out around 48 minutes again.

**Comment by ctreleaven** [comment]
port:man should be in depends_build rather than depends_lib, no?

**Comment by janstary** [comment]
@ctreleaven Sorry, fixed now.

**Comment by ryandesign** [comment]
If bibclean doesn't use man2html, then removing the dependency changes nothing about bibclean's installed files and its revision should not be changed.

**Comment by janstary** [comment]
Doesn't a dropped dependency warant a revision bump?

**Comment by mf2k** [comment]
Not really. It does not change anything in the installed port and forces an unnecessary rebuild for everyone using it.

**Comment by janstary** [comment]
OK, fixed. Thanks.

**Comment by ryandesign** [comment]
If the 4 changes to lirc were squashed into a single commit and the 2 changes to bibclean were squashed into a single commit this would be ready to merge.

**Comment by janstary** [comment]
Should lirc also _not_ bump the revision then?

**Comment by ctreleaven** [comment]
The files installed by the port will change (fixed html man pages) thus the revision must be increased.

**Comment by janstary** [comment]
I prepared a cleaner version of this PR in
https://github.com/macports/macports-ports/pull/1199

**Comment by mojca** [comment]
Please don't open new pull requests when you need to change something, but try to (force) push to the same remote branch instead.

**Comment by janstary** [comment]
I will. I only learned about squashing now, and messed this one up.
The other PRs are squashed and force pushed.

**Pull request closed without merging**
