### PR TITLE
snac: update to version 2.15.

### PR DESCRIPTION
**Pull request by artkiver**
###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 13.1 22C65 arm64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by herbygillot** [comment]
I also notice that you are forking an entirely new repository for each PR.

You can actually maintain a single forked `macports-ports` repo, and maintain multiple branches within that repo.  Within your forked repo, you can create new branches from `master` for each PR you want to open.  It isn't necessary to fork an entirely new _repository_ for each PR.

**Comment by artkiver** [comment]
@herbygillot thanks for merging the commit! 🙏

I looked into using the makefile portgroup before I submitted the original port; but ran into issues. I can experiment with it further and see if maybe I can get a better handle on it though.

Ah, indeed the branching is the way to go! There are occasions where it doesn't seem to go so swimmingly (due to user error) and I have re-forked instead. This time around I actually had a different branch which I bungled slightly and deleted before trying this branch though, so maybe I am getting the hang of it a little bit more? My confidence with git/GH is still somewhat low, but thank you for the perspective!

**Comment by artkiver** [comment]
Ah sure. One common issue I have encountered is that when attempting to push a commit, when I look at the PR, it will have past commits from other branches.

I think that *may* be related to having deleted the branches locally, but not on GitHub? I am not 100% certain, but I have been more mindful about deleting merged PRs first on GitHub, then locally and it seems to be functioning a little bit more smoothly.

**Comment by herbygillot** [comment]
Past commits from other branches can signify that either you are creating your PR branch from an outdated master branch.

The path goes like so:
```
<local repo on your machine> --> <your forked repo in GH> ---> <main project repo on GH>
```

When you clone a repo down to your local machine, references to remote repositories are represented by `remote`s. You can see the list of them with `git remote -v`.

### Initial Setup

Let's say you forked `macports-ports` to your Github account with the intent of using it as your single forked repo.  It would look like `artkiver/macports-ports`.

Now you need to bring this down to your machine.  So you clone it:

```bash
~artkiver $ git clone git@github.com:artkiver/macports-ports.git
```

You would get a local repository whose `origin` remote is pointing to your forked repository on Github:

```bash
~artkiver $ cd macports-ports
macports-ports $ git remote -v
origin	git@github.com:artkiver/macports-ports.git (fetch)
origin	git@github.com:artkiver/macports-ports.git (push)
```

You will want to change this.  You will want the `origin` remote to point to the official `macports-ports` repo, and maybe an `artkiver` remote that points to yours.

This is so that you can update your local repo with the latest `master` from the official repo, and then use that updated `master` as the jump off point to create your PR branches.  In this way, you eliminate the chance of old commits sneaking their way into your PRs as every PR branch is being created from the most up-to-date `master` branch.

So let's add these two remotes.  First, we need to delete the current `origin` remote so that we can replace it:

```bash
macports-ports $ git remote remove origin
macports-ports $ git remote -v
macports-ports $
# nothing listed as we deleted the origin remote
```

Now we need to add the `origin` remote pointing to the official ports repo:
```bash
macports-ports $ git remote add origin git@github.com:macports/macports-ports.git
macports-ports $ git remote -v
origin	git@github.com:macports/macports-ports.git (fetch)
origin	git@github.com:macports/macports-ports.git (push)
# origin is now pointing to the official MacPorts ports repo
```

You can now test this by fetching all the branches from the official repo down into your local one:

```bash
macports-ports $ git fetch origin
remote: Enumerating objects: 21868, done.
remote: Counting objects: 100% (7147/7147), done.
remote: Compressing objects: 100% (280/280), done.
remote: Total 21868 (delta 6713), reused 7092 (delta 6681), pack-reused 14721
Receiving objects: 100% (21868/21868), 7.42 MiB | 24.43 MiB/s, done.
Resolving deltas: 100% (11847/11847), completed with 2833 local objects.
From github.com:macports/macports-ports
 * [new branch]              master         -> origin/master
 * [new tag]                 v2.6.0-archive -> v2.6.0-archive
 * [new tag]                 v2.7.0-archive -> v2.7.0-archive
 * [new tag]                 v2.8.0-archive -> v2.8.0-archive
 ```

Now you want to add a second remote pointing to your forked ports repo:

```bash
macports-ports $ git remote add artkiver git@github.com:artkiver/macports-ports.git
macports-ports $ git remote -v
artkiver    git@github.com:artkiver/macports-ports.git (fetch)
artkiver    git@github.com:artkiver/macports-ports.git (push)
origin      git@github.com:macports/macports-ports.git (fetch)
origin      git@github.com:macports/macports-ports.git (push)
```

Now you have everything you need to both:

1. Keep your local on-disk repository up-to-date with the latest from the official MacPorts ports repository.
2. Push and manage the branches backing your PRs in your personal forked ports repository.

### Creating A New Pull Request

To create a new pull request, you want your local repository's `master` to 100% match the current `master` in the official MacPorts repository.  If your local `master` is simply an older ancestor of the current master, you can use `pull` to bring it up to date.  If `pull` fails though, you can hard reset it:

#### Option A: Via `git pull`

```bash
macports-ports $ git checkout master
macports-ports $ git pull origin master
# this will pull changes from the master branch on origin (which is the official repository) into your local master branch
```

#### Option B: Via `git reset` (panic button)

Only use this method if `pull` fails.  The hard reset will completely obliterate your local `master` branch and forcibly replace it with the branch you specify.  It would look something like this:

```bash
macports-ports $ git fetch origin master
# tells git to just download the master branch from the official repo and keep it on-hand
macports-ports $ git reset --hard origin/master
# forcibly replaces your local master with the master from origin
```

### Creating Your PR Branch

Now that you have what should most assuredly be the latest master branch as `master` in your local repo, you can use that to create your PR branch.  Say you want to call the branch `snac-v2`. You would do something like this:

```bash
macports-ports $ git checkout master
macports-ports $ git checkout -b snac-v2
# creates the new snac-v2 branch from the one you were sitting on at the time you issued the command, which in this case is master
```

Make all edits, changes and test as you want to, then commit.  Use `git status` to ensure that you are on the `snac-v2` branch before you commit:

```bash
# after your Portfile and etc. edits
macports-ports $ git status
On branch snac-v2
...
# make sure it says the right branch above
# now we are ready to commit
macports-ports $ git add Portfile
macports-ports $ git commit -m 'snac: update to v2'
# use git log to ensure it looks the way you expect:
macports-ports $ git log --stat
```

At this point you should have a new local branch (`snac-v2`) with your change. We are ready to push to Github and open the PR.

### Pushing To Github and Opening The Pull Request

Right now your `snac-v2` branch only exists on your local machine and not in Github.

You need to push it to your personal forked repo, and that will provide the link for opening the pull request.

To do this, we need to push to the `artkiver` remote:

```bash
macports-ports $ git push artkiver snac-v2
Enumerating objects: 4408, done.
...
remote: Resolving deltas: 100% (1473/1473), completed with 517 local objects.
remote:
remote: Create a pull request for 'foo' on GitHub by visiting:
remote:      https://github.com/artkiver/macports-ports/pull/new/snac-v2
remote:
To github.com:artkiver/macports-ports.git
```

When you push your `snac-v2` branch, git will show you a link you can use to create the pull request.

If you have further changes you need to make, you can return to your local repository, and after ensuring you're in the correct branch (`snac-v2`), you can make changes and amend your commit:

```bash
# we ensure we are in the right branch using "git status"
macports-ports $ git status
On branch snac-v2
...
macports-ports $ vim Portfile
# make changes, edits, etc.
# now we want to incorporate our new changes into the commit we created
macports-ports $ git add Portfile ....
macports-ports $ git commit --amend
# notice the --amend - this will change the existing commit instead of creating a new one.
# An editor will appear. Edit the commit message as needed then save and exit.
# You can review your work using "git show HEAD"
macports-port $ git show HEAD
```

After modifying your local `snac-v2` by amending the commit, you will need to **OVERWRITE** the `snac-v2` branch in your Github forked repo with your modified local one.  You do this by adding `-f` (force) to the push command:

```bash
macports-ports $ git push -f artkiver snac-v2
```

You can use the same URL you were show previously to create the PR, or if the PR exists already, your forced push will automatically reflect in the open pull request.

**Comment by artkiver** [comment]
Ah wow, thank you for the detailed and thoughtful reply! I am going to reread this a bit and see how I can apply this knowledge moving forward.

**Pull request merged**
