### PR TITLE
sh_select: New port.

### PR DESCRIPTION
**Pull request by graywolf**
#### Description

This allows selecting the shell to provide ${prefix}/bin/sh link.  After selection is made, `/usr/bin/env sh' picks up the shell installed and configured via macports.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.6
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
what problem does this solve?

**Comment by reneeotten** [comment]
there is no”sh” port, so then why would there be a “sh_select” port? Just specify the shell you want to use in the shebang line and you’re done. 

I’m not seeing MacPort’s use-case here for a “select” file and thus will not merge this PR myself.

**Comment by reneeotten** [comment]
just the fact that I don't really see the point doesn't mean it will  not get merged. Just keep it open and get the opinion of some others.

**Comment by pmetzger** [comment]
I suppose I would be more convinced of the utility of this if I wanted a /bin/sh script to know about more things than the POSIX shell knows about (so I could pick /opt/local/bin/sh instead.) But the thing to me is, if I'm specifying sh as the shell, I think I probably want to be as lowest common denominator POSIX shell as possible, in which case, /bin/sh is my right move in general?

**Pull request closed without merging**
