### PR TITLE
p5.34-*: add subports for perl 5.34

### PR DESCRIPTION
**Pull request by mojca**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mojca** [comment]
@ryandesign: I hardly tested anything, but I would be grateful if you could throw a glimpse over this and merge it whenever you feel it makes most sense for the buildbot workers.
I believe that a large number of p5.32 subports might still need to be rebuilt. I'm not sure whether I should schedule them now to slightly decrease the load on the workers during rebuild of 5.34, or simply not care too much and let buildbot build all of 3 or 4k of them at once on some workers.

**Comment by ryandesign** [comment]
> I believe that a large number of p5.32 subports might still need to be rebuilt.

If you mean due to the compiler and SDK selection issues that Josh recently committed fixes for, he also already scheduled builds for all (?) of those on 10.6 x86_64 and 11 x86_64 and some are still building right now on 10.6 i386. I'm not sure if builds got put in for 11 arm64.

**Comment by mojca** [comment]
> If you mean due to the compiler and SDK selection issues that Josh recently committed fixes for, he also already scheduled builds for all (?) of those on 10.6 x86_64 and 11 x86_64 and some are still building right now on 10.6 i386. I'm not sure if builds got put in for 11 arm64.

I believe I have scheduled everything on 11 arm64 as well as a couple of other builders, just not all of them (in particular not on those where the initial portwatcher is no longer accessible due to power outage).

The only question is: should I care about those and schedule those first, or do we simply merge this job and let the buildbot workes build whatever is still missing?

I would like to leave merging this to you, so that you can act appropriately (like check that all the queues are empty, temporarily disable some less important builders, ...).

**Comment by mojca** [comment]
When may this be merged?

**Comment by ryandesign** [comment]
> The only question is: should I care about those and schedule those first, or do we simply merge this job and let the buildbot workes build whatever is still missing?
> 
> I can schedule all the missing ones if you suggest that it would be a good idea to do that first

I don't think we need to bother with that.

> but I would like to leave merging this to you, so that you can act appropriately (like check that all the queues are empty, temporarily disable some less important builders, ...).

That's probably a good idea, thanks.

> When may this be merged?

I see some conflicts have appeared.

The remaining issue that caused many p5 ports to fail to build on 10.6 is https://trac.macports.org/ticket/60028 / https://trac.macports.org/ticket/57648. Do we understand the issue well enough to fix it prior to merging this PR?

**Comment by mojca** [comment]
> The remaining issue that caused many p5 ports to fail to build on 10.6 is https://trac.macports.org/ticket/60028 / https://trac.macports.org/ticket/57648. Do we understand the issue well enough to fix it prior to merging this PR?

According to a super quick glimpse, by far the easiest fix would be to build perl and all of its modules with clang >= 3.6, but don't take my word for it. I suspect that some kind of configure runs when building perl, and depending on compiler features, some options are turned on or off and end up in perl. Later on the modules may be built with a different (newer) compiler, and suddenly expecting those features to be inside the installed perl library.

If I take a look at [#57648](https://trac.macports.org/ticket/57648) and `Symbol not found: _perl_tsa_mutex_lock`, this seems related:
* https://github.com/Perl/perl5/blob/415da10787d8fa5176e711559172aa0604ec3d0d/perl.h#L3237-L3259
* https://github.com/Perl/perl5/blob/3e25f6d2dce9289bf3894d673f992195fb530d8e/thread.h#L201-L207

```c
/* clang Thread Safety Analysis/Annotations/Attributes
 * http://clang.llvm.org/docs/ThreadSafetyAnalysis.html
 *
 * Available since clang 3.6-ish (appeared in 3.4, but shaky still in 3.5).
 * Apple XCode hijacks __clang_major__ and __clang_minor__
 * (6.1 means really clang 3.6), so needs extra hijinks
 * (could probably also test the contents of __apple_build_version__).
 */
#if defined(USE_ITHREADS) && defined(I_PTHREAD) && \
    defined(__clang__) && \
    !defined(SWIG) && \
  ((!defined(__apple_build_version__) &&               \
    ((__clang_major__ == 3 && __clang_minor__ >= 6) || \
     (__clang_major__ >= 4))) || \
   (defined(__apple_build_version__) &&                \
    ((__clang_major__ == 6 && __clang_minor__ >= 1) || \
     (__clang_major__ >= 7))))
#  define PERL_TSA__(x)   __attribute__((x))
#  define PERL_TSA_ACTIVE
#else
#  define PERL_TSA__(x)   /* No TSA, make TSA attributes no-ops. */
#  undef PERL_TSA_ACTIVE
#endif
```

```c
#  ifdef PERL_TSA_ACTIVE
#    define perl_pthread_mutex_lock(m) perl_tsa_mutex_lock(m)
#    define perl_pthread_mutex_unlock(m) perl_tsa_mutex_unlock(m)
#  else
#    define perl_pthread_mutex_lock(m) pthread_mutex_lock(m)
#    define perl_pthread_mutex_unlock(m) pthread_mutex_unlock(m)
#  endif
```

I have no clue how to fix this quickly.

**Comment by ryandesign** [comment]
> According to a super quick glimpse, by far the easiest fix would be to build perl and all of its modules with clang >= 3.6, but don't take my word for it.

I *think* it might suffice to require new clang just for perl. I think if a perl module is later compiled with new or old clang it should work. Should probably do some test builds to verify that.

I filed https://github.com/Perl/perl5/issues/18991 to ask upstream about this.

Blacklisting older clangs for just perl would be easy enough to do, but we'd want to make sure that doesn't introduce any circular dependencies or bootstrapping problems on older systems.

**Comment by ryandesign** [comment]
> require new clang just for perl

And we aren't going to be able to do that since clang-3.7 and later depend on perl.

**Comment by ryandesign** [comment]
> the clang ports depend on perl

Actually it looks like maybe we can use clang-3.7 after all since it only requires port:perl5 with the +analyzer variant which is no longer the default on 10.6 and earlier thanks to 9809d4ba1a7540430d2f8998b211d39c69fc1587. perl5 still probably builds with clang-3.4 as first choice because of the use of the clang_dependency portgroup. We could change perl5 to not include the clang_dependency portgroup on 10.6 and earlier to match the above commit.

**Comment by ryandesign** [comment]
> remove that block

The block and the clang_dependency portgroup were removed in 1d0c2e3ddf025435ecd3f701bbf8ce4a5263f5be. It was pointed out in the commit comments that the clang_dependency portgroup cannot be removed. The block and the clang_dependency portgroup were re-added in 54337dbb2dc9f6dfc20fa59eb819635049851783. I still think the block can be removed (while leaving the clang_dependency portgroup in) and will accomplish our goal.

**Comment by ryandesign** [comment]
> maybe we can use clang-3.7 after all since it only requires port:perl5 with the +analyzer variant which is no longer the default on 10.6 and earlier thanks to [9809d4b](https://github.com/macports/macports-ports/commit/9809d4ba1a7540430d2f8998b211d39c69fc1587)

And for clang 5.0 thru 10 in 6b338b8b0a4fd729e64d35829b0fa3b6d6711b5e. clang 11, 12, and devel still have +analyzer as an unconditional default [intentionally](https://trac.macports.org/ticket/63038) so we still need clang_dependency for those.

> I admit it's probably worth checking whether the bootstrapping still works if we remove that again, it just that testing takes a while.

I can try a build in a clean prefix if we can agree on what changes to make.

In the upstream bug report you wrote:

> There's probably no reason to worry about the scenario of building perl with New Clang and modules with Old Clang since ensuring that all modules build with New Clang should be straightforward

I was not planning on requiring all perl modules to build with New Clang as well. In my opinion that would introduce unnecessary compiler dependencies. If every perl module (on certain older systems) had to activate a clang compiler port to build, that would drastically slow down buildbot builds.

The `perl_tsa_mutex` stuff was added in https://github.com/Perl/perl5/commit/3baee7ccba467a3ddc1cb6bfb1a4cabd40cd7424 in 5.23.6 so we wouldn't need to revbump earlier perls.

**Comment by ryandesign** [comment]
> clang 11, 12, and devel still have +analyzer as an unconditional default [intentionally](https://trac.macports.org/ticket/63038)

Filed https://trac.macports.org/ticket/63265 to see if that can be changed.

This is my proposed modification to perl5: https://github.com/ryandesign/macports-ports/tree/perl5

**Comment by ryandesign** [comment]
> Filed https://trac.macports.org/ticket/63265 to see if that can be changed.
> 
> This is my proposed modification to perl5: https://github.com/ryandesign/macports-ports/tree/perl5

Pushed a revised version based on 63265 having been resolved. Still untested though. Does it seem reasonable to you?

**Comment by mojca** [comment]
Yes, your latest version sounds reasonable. It's getting more complex with each commit, but that's ok ;)
The only question is whether it works correctly and whether it is still able to bootstrap the toolchain on < 10.7 without circular dependencies. I guess that just needs Ken's approval ;)

**Comment by mojca** [comment]
@kencu: can you please check Ryan's suggested changes for perl?

**Comment by kencu** [comment]
sure.

the issue with the perls was building them with clang-3.4 on 10.6 .

perls now build with clang-3.7 at a minumum, so it all works now I believe.

I will see what Ryan had.

**Comment by kencu** [comment]
removing perl from the dep chain on < 10.7 has been why I've been modifying clangs for the past few months. What Ryan proposed is similar to what I was working toward.

The commit I pushed did the removal of clang-3.7 part, and the revbump part, which fixed the buildbot (and user) builds, so we're all in business now.

The blacklisting Ryan proposes matches what we know about clangs that make broken perls, so that looks right to me.

Have to think about the idea of removing the clang dependency PG completely on < 10.7. I didn't want to do that unless the analyzer variant was completely removed from the os.version, like I just did with clang-3.7. Otherwise you can be circular again.

perl5s seem to build nicely with clang-3.7, so no real need to chang it.

**Comment by kencu** [comment]
Thanks for asking me to take another look, Mojca.

This part seems 100% good, along with the blacklist versions PortGroup:
```
        if {${perl5.major} >= 5.24} {
             # Use a new enough compiler that perl_tsa_mutex_lock gets compiled in,
             # since perl modules may try to use it if they get compiled with a
             # newer compiler. See https://github.com/Perl/perl5/issues/18991
             compiler.blacklist-append \
                             {clang < 602} macports-clang-3.3 macports-clang-3.4
         }
```

That should stop people from accidentally building a broken perl.

I believe I would leave the rest alone, though. The tradeoff about changing clang_dependeny is this:


- If you leave things as they are, perl will build with clang-3.7 on any system where the os-provided clang is too old. That's good, clang-3.7 works, perl is built correctly. No problemo. They almost certainly have clang-3.7 installed anyway as several other ports need it, and I trimmed down the size of llvm/clang-3.7 by about 90% a few months ago.

- If you change the ```clang_dependency 1.0``` PortGroup to only apply to systems > 10 as Ryan proposes, then if someone does build some newer macports-clang-N on darwin 8, 9, or 10 and enable +analyzer (which is still an available variant), it will be broken for updates. It is not a default variant, but it is available. Someone will inevitably do it and open a ticket about it.

- If we remove the +analyzer variant completely from all the clangs on < 10.7, no problem, but someone will probably eventually ask why we did that, as it works fine and they want it.


So - IMHO - we could leave the ```clang_dependency 1.0```  changes and not do those.

**Comment by kencu** [comment]
@ryandesign -- does that plan work for you?

**Comment by mojca** [comment]
@kencu: is this how you imagined it?
@ryandesign: does this look reasonable to you?

I would potentially like to add a comment explaining why we are only adding this block to `perl5.34` and not to the older ones as well.

**Comment by kencu** [comment]
we also need the compiler blacklist versions PG, but yes, I think that blacklists the right ones, as Ryan outlined.

It is set to apply to perl 5.24 and up, so that's right.

I think nothing needs revbumping, as the only place I know of that this happened was 10.6 building with clang-3.4, and that was fixed. I never saw this on 10.7 up.

**Comment by kencu** [comment]
this will blacklist systems clangs that were previously used on some systems 10.7 thru 10.9 or so. That changes those to build perl with some macports-clang version...have to see which one in the morning. So yuck the whole corral might revbumping yet again for that... yet I only saw this mutex thing on 10.6 myself, although can't verify it never happened on 10.7-9.

**Comment by kencu** [comment]
so certainly on 10.7 perl builds with the extra symbols when I build it with clang-9.0, and without them when I build it with the system clang. However, try as I may, I can't seem to reproduce the missing symbols error I see on 10.6, even when I build perl without the tsa_mutex symbols and then build one of the troublesome perl ports (that errors on 10.6) with a newer clang like clang-9.0 on 10.7. 

I'm not yet seeing the exact magic problem.

So I'm of two minds. We can blacklist clangs as described, force a rebuild of all the perls again, perl will build with clang-3.7 on all the older systems up to about 10.8 or 10.9 or whatever that clang blacklist calls in, no big issue. The new symbols will then be in the perls on 10.7 through 10.9.

Probably that's best for consistence across all platforms. I don't have a ticket that will fix like we had on 10.6, but maybe we'll save ourselves from trouble down the line.

**Comment by ryandesign** [comment]
> @ryandesign: does this look reasonable to you?

Please proceed at your own discretion.

**Comment by ryandesign** [comment]
I would agree with Ken above that since you are changing the blacklisting for perl5.24 and later, you need to increase the revision fo perl5.24 and later (at least on affected systems). However if there is a reason why you're not doing that, ignore me; I haven't studied everything in this PR closely.

**Comment by mascguy** [comment]
Looking forward to having this merged!

One suggestion though: Given how slow our CI jobs are - at least when dealing with a large number of ports like this - you may want to bypass them via `[skip ci]`. Otherwise precious CI resources will be tied up for six hours.

https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

**Comment by ryandesign** [comment]
To avoid tying up the buildbot for weeks on just these builds, we could turn off github webhook notifications for buildbot, then merge the PR, then turn the notifications back on, and I can force-build small batches of the p5.34 ports when the buildbot is not busy with other builds. I have script I've been using to do do that for the initial builds for the macOS 12 arm64 builder already.

**Comment by reneeotten** [comment]
is there a plan on what to do with this PR and perhaps also updating the "default" perl version to something newer than 5.28 (which reached EOL on 2020-06-01). Any concerns/objections to just bumping that to 5.32?

**Comment by kencu** [comment]
back some months ago, I was going to finish this up and push it at Mojca’s request. But I defer to you now Renee.

My only real input was noting older clangs build a partially-broken perl. So they need to be blacklisted if possible, so long as bootstrapping can somehow still be done.

**Comment by ryandesign** [comment]
Now would be a great time to get this PR merged because it is cold in Texas so the heat generated by the build servers would actually be helpful.

There are some conflicts in the PR right now. Could @mojca or whoever has experience with the process of doing these updates update the PR to resolve the conflicts and add any new p5 ports that might have appeared since the PR was opened? And [revbump perl5.24 and later](https://github.com/macports/macports-ports/pull/11534#issuecomment-961704494). And then as [I said above](https://github.com/macports/macports-ports/pull/11534#issuecomment-974579238) I can turn off GitHub web hooks, merge the PR, turn the web hooks back on, and then manually send small batches of ports to the buildbot when it's not too busy.

Switching the default perl to a newer version seems like a fine idea too but which version it should be is up to someone who follows perl more closely than me and as far as I know this change does not need to be part of this PR.

**Comment by mojca** [comment]
I can fix it later today.

**Pull request merged**
