### PR TITLE
xfce*: follow-up fixes for the ports

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

1. `libxfce4util` has been updated with updating its dependency, `xfce4-dev-tools`. Update the latter.
2. The hack in `libxfce4util` is unneeded and actually breaks the build, at least on some systems. Use a standard autoreconf instead.
3. `libxfce4ui` uses an unsupported configure arg, tries to link to `libglade`, which may fail due to a wrong compiler choice. Fix that.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

@qwertychouskie FYI

### CODE REVIEW

**Comment by barracuda156** [comment]
Maybe that autogen hack was needed because of archaic `xfce4-dev-tools`? Anyway, it should be dropped here and in other XFCE ports.

**Comment by barracuda156** [comment]
What happens now is this:
```
--->  Configuring libxfce4util
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_xfce_libxfce4util/libxfce4util/work/libxfce4util-4.18.2" && /opt/PPCSnowLeopardPorts/xfce/libxfce4util/files/autogen.sh --prefix=/opt/local --disable-visibility 
xdt-autogen: You must have "libtoolize" installed. You can get if from
             https://www.gnu.org/software/libtool/.
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_xfce_libxfce4util/libxfce4util/work/libxfce4util-4.18.2" && /opt/PPCSnowLeopardPorts/xfce/libxfce4util/files/autogen.sh --prefix=/opt/local --disable-visibility 
Exit code: 1
```

By the way, looks like this is not because of `xfce4-dev-tools` version, but because there is a patch for `glibtoolize` which is not applied.

**Comment by barracuda156** [comment]
Then, `libxfce4ui` uses a configure arg which is not recognized:
```
configure: WARNING: unrecognized options: --disable-gladeui
```
And it fails to build:
```
In file included from /opt/local/include/libgladeui-2.0/gladeui/glade.h:26,
                 from libxfce4ui-glade.c:34:
/opt/local/include/libgladeui-2.0/gladeui/glade-widget-adaptor.h:38: error: redefinition of typedef 'GladeWidgetAdaptor'
/opt/local/include/libgladeui-2.0/gladeui/glade-xml-utils.h:48: error: previous declaration of 'GladeWidgetAdaptor' was here
make[3]: *** [libxfce4uiglade2_la-libxfce4ui-glade.lo] Error 1
make[3]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_xfce_libxfce4ui/libxfce4ui/work/libxfce4ui-4.18.6/glade'
make[2]: *** [all-recursive] Error 1
```

**Comment by barracuda156** [comment]
@mascguy @ryandesign Could someone say if that hacky patch in `libxfce4ui` is still needed? I have no idea what it does and why it was added, the port builds fine without it.

**Comment by mascguy** [comment]
For your various questions, I'd defer to @qwertychouskie. (So perhaps leave this open for a few days, to provide time for a response.)

**Comment by qwertychouskie** [comment]
As far as I can tell, libglade was [deprecated in 2009](http://mail.gnome.org/archives/devel-announce-list/2009-May/msg00003.html) and seems to only be applicable for GTK2.  Is there any good reason to bring it back?  All of XFCE nowadays is either GTK3 by default or GTK3 only.

**Comment by barracuda156** [comment]
> As far as I can tell, libglade was [deprecated in 2009](http://mail.gnome.org/archives/devel-announce-list/2009-May/msg00003.html) and seems to only be applicable for GTK2. Is there any good reason to bring it back? All of XFCE nowadays is either GTK3 by default or GTK3 only.

Need to check, perhaps it was linking to `libgladeui`, for which there is a whole section: https://gitlab.xfce.org/xfce/libxfce4ui/-/blob/master/configure.ac?ref_type=heads#L257-295
If it is unneeded, we should explicitly disable it, and not let the build decide on its own.

**Comment by barracuda156** [comment]
This is what configure does without arguments being specified:
```
--->  Configuring libxfce4ui
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_xfce_libxfce4ui/libxfce4ui/work/libxfce4ui-4.18.6" && ./configure --prefix=/opt/local --disable-visibility 
checking build system type... powerpc-apple-darwin10.0.0d2
checking host system type... powerpc-apple-darwin10.0.0d2
checking target system type... powerpc-apple-darwin10.0.0d2
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /opt/local/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... /usr/bin/gcc-4.2
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether /usr/bin/gcc-4.2 accepts -g... yes
checking for /usr/bin/gcc-4.2 option to enable C11 features... unsupported
checking for /usr/bin/gcc-4.2 option to enable C99 features... none needed
checking whether /usr/bin/gcc-4.2 understands -c and -o together... yes
checking dependency style of /usr/bin/gcc-4.2... gcc3
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking platform... checking for gcc... (cached) /usr/bin/gcc-4.2
checking whether the compiler supports GNU C... (cached) yes
checking whether /usr/bin/gcc-4.2 accepts -g... (cached) yes
checking for /usr/bin/gcc-4.2 option to enable C11 features... (cached) unsupported
checking for /usr/bin/gcc-4.2 option to enable C99 features... (cached) none needed
checking whether /usr/bin/gcc-4.2 understands -c and -o together... (cached) yes
checking dependency style of /usr/bin/gcc-4.2... (cached) gcc3
checking for a sed that does not truncate output... /opt/local/bin/gsed
checking for grep that handles long lines and -e... /opt/local/bin/ggrep
checking for egrep... /opt/local/bin/ggrep -E
checking for fgrep... /opt/local/bin/ggrep -F
checking how to print strings... printf
checking for ld used by /usr/bin/gcc-4.2... /usr/libexec/gcc/powerpc-apple-darwin10/4.2.1/ld
checking if the linker (/usr/libexec/gcc/powerpc-apple-darwin10/4.2.1/ld) is GNU ld... no
checking whether NLS is requested... yes
checking for intltool >= 0.35.0... 0.51.0 found
checking for intltool-update... /opt/local/bin/intltool-update
checking for intltool-merge... /opt/local/bin/intltool-merge
checking for intltool-extract... /opt/local/bin/intltool-extract
checking for xgettext... /opt/local/bin/xgettext
checking for msgmerge... /opt/local/bin/msgmerge
checking for msgfmt... /opt/local/bin/msgfmt
checking for gmsgfmt... /opt/local/bin/msgfmt
checking for perl... /opt/local/bin/perl
checking for perl >= 5.8.1... 5.34.3
checking for XML::Parser... ok
checking for perl5... perl5
checking for glib-compile-resources... /opt/local/bin/glib-compile-resources
checking for BSD- or MS-compatible name lister (nm)... /opt/local/bin/nm -B
checking the name lister (/opt/local/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert powerpc-apple-darwin10.0.0d2 file names to powerpc-apple-darwin10.0.0d2 format... func_convert_file_noop
checking how to convert powerpc-apple-darwin10.0.0d2 file names to toolchain format... func_convert_file_noop
checking for /usr/libexec/gcc/powerpc-apple-darwin10/4.2.1/ld option to reload object files... -r
checking for file... file
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /opt/local/bin/nm -B output from /usr/bin/gcc-4.2 object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... ld: unknown option: -force_load
no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /usr/bin/gcc-4.2 supports -fno-rtti -fno-exceptions... no
checking for /usr/bin/gcc-4.2 option to produce PIC... -fno-common -DPIC
checking if /usr/bin/gcc-4.2 PIC flag -fno-common -DPIC works... yes
checking if /usr/bin/gcc-4.2 static flag -static works... no
checking if /usr/bin/gcc-4.2 supports -c -o file.o... yes
checking if /usr/bin/gcc-4.2 supports -c -o file.o... (cached) yes
checking whether the /usr/bin/gcc-4.2 linker (/usr/libexec/gcc/powerpc-apple-darwin10/4.2.1/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin10.0.0d2 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for crt_externs.h... yes
checking for errno.h... yes
checking for fcntl.h... yes
checking for limits.h... yes
checking for locale.h... yes
checking for math.h... yes
checking for memory.h... yes
checking for signal.h... yes
checking for stdarg.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for /usr/bin/gcc-4.2 options needed to detect all undeclared functions... none needed
checking whether environ is declared... no
checking for _NSGetEnviron... yes
checking for library containing bind_textdomain_codeset... -lintl
checking for locales directory... ${prefix}/share/locale
checking for library containing bind_textdomain_codeset... (cached) -lintl
checking how to run the C preprocessor... /usr/bin/gcc-4.2 -E
checking for X... libraries , headers 
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking for main in -lX11... yes
checking for SmcSaveYourselfDone in -lSM... yes
checking for pkg-config... /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for glib-2.0 >= 2.66.0... 2.78.4
checking GLIB_CFLAGS... -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include
checking GLIB_LIBS... -L/opt/local/lib -lglib-2.0 -lintl
configure: setting GLIB_VERSION_MAX_ALLOWED and GLIB_VERSION_MIN_REQUIRED according to 2.66.0
checking for pkg-config... (cached) /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gtk+-3.0 >= 3.24.0... 3.24.41
checking GTK3_CFLAGS... -I/opt/local/include/gtk-3.0 -I/opt/local/include/at-spi2-atk/2.0 -I/opt/local/include/at-spi-2.0 -I/opt/local/include/dbus-1.0 -I/opt/local/lib/dbus-1.0/include -I/opt/local/include/gtk-3.0 -I/opt/local/include/gio-unix-2.0 -I/opt/local/include/cairo -I/opt/local/include/pango-1.0 -I/opt/local/include/harfbuzz -I/opt/local/include/pango-1.0 -I/opt/local/include/fribidi -I/opt/local/include/harfbuzz -I/opt/local/include/atk-1.0 -I/opt/local/include/cairo -I/opt/local/include/pixman-1 -I/opt/local/include/freetype2 -I/opt/local/include/gdk-pixbuf-2.0 -I/opt/local/include/libpng16 -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include
checking GTK3_LIBS... -L/opt/local/lib -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl
checking for pkg-config... (cached) /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libxfce4util-1.0 >= 4.17.2... 4.18.2
checking LIBXFCE4UTIL_CFLAGS... -I/opt/local/include/xfce4 -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include
checking LIBXFCE4UTIL_LIBS... -L/opt/local/lib -lxfce4util -lglib-2.0 -lintl
checking for pkg-config... (cached) /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libxfconf-0 >= 4.12.0... 4.18.3
checking XFCONF_CFLAGS... -I/opt/local/include/xfce4/xfconf-0 -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include
checking XFCONF_LIBS... -L/opt/local/lib -lxfconf-0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl
checking for optional package libgtop-2.0 >= 2.24.0... not found
checking for gobject-introspection... yes
checking for pkg-config... (cached) /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for vapigen... yes
checking for pkg-config... (cached) /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libstartup-notification-1.0 >= 0.4... 0.12
checking LIBSTARTUP_NOTIFICATION_CFLAGS... -I/opt/local/include/startup-notification-1.0
checking LIBSTARTUP_NOTIFICATION_LIBS... -L/opt/local/lib -lstartup-notification-1
checking for additional vendor name and/or info... not set
checking for a custom manual website location... https://docs.xfce.org/help.php
checking for pkg-config... (cached) /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gladeui-2.0 >= 3.5.0... 3.40.0
checking GLADEUI2_CFLAGS... -I/opt/local/include/libgladeui-2.0 -I/opt/local/include/gtk-3.0 -I/opt/local/include/at-spi2-atk/2.0 -I/opt/local/include/at-spi-2.0 -I/opt/local/include/dbus-1.0 -I/opt/local/lib/dbus-1.0/include -I/opt/local/include/gtk-3.0 -I/opt/local/include/gio-unix-2.0 -I/opt/local/include/cairo -I/opt/local/include/pango-1.0 -I/opt/local/include/harfbuzz -I/opt/local/include/pango-1.0 -I/opt/local/include/fribidi -I/opt/local/include/harfbuzz -I/opt/local/include/atk-1.0 -I/opt/local/include/cairo -I/opt/local/include/pixman-1 -I/opt/local/include/freetype2 -I/opt/local/include/gdk-pixbuf-2.0 -I/opt/local/include/libpng16 -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include
checking GLADEUI2_LIBS... -L/opt/local/lib -lgladeui-2 -lgmodule-2.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl
checking for gtk-doc... yes
checking for gtkdoc-check... gtkdoc-check.test
checking for gtkdoc-check... /opt/local/bin/gtkdoc-check
checking for gtkdoc-rebase... /opt/local/bin/gtkdoc-rebase
checking for gtkdoc-mkpdf... /opt/local/bin/gtkdoc-mkpdf
checking whether to build gtk-doc documentation... no
checking for glib-2.0 >= 2.10.0 gobject-2.0  >= 2.10.0... yes
checking whether to build with debugging support... minimum
checking if /usr/bin/gcc-4.2 supports -Wall... yes
checking if /usr/bin/gcc-4.2 supports -Wextra... yes
checking if /usr/bin/gcc-4.2 supports -Wno-missing-field-initializers... yes
checking if /usr/bin/gcc-4.2 supports -Wno-unused-parameter... yes
checking if /usr/bin/gcc-4.2 supports -Wmissing-declarations... yes
checking if /usr/bin/gcc-4.2 supports -Wmissing-noreturn... yes
checking if /usr/bin/gcc-4.2 supports -Wpointer-arith... yes
checking if /usr/bin/gcc-4.2 supports -Wcast-align... yes
checking if /usr/bin/gcc-4.2 supports -Wformat... yes
checking if /usr/bin/gcc-4.2 supports -Wformat-security... yes
checking if /usr/bin/gcc-4.2 supports -Wformat-y2k... yes
checking if /usr/bin/gcc-4.2 supports -Winit-self... yes
checking if /usr/bin/gcc-4.2 supports -Wmissing-include-dirs... yes
checking if /usr/bin/gcc-4.2 supports -Wundef... yes
checking if /usr/bin/gcc-4.2 supports -Wredundant-decls... yes
checking if /usr/bin/gcc-4.2 supports -Wshadow... yes
checking if /usr/bin/gcc-4.2 supports -Wnested-externs... yes
checking if /usr/bin/gcc-4.2 supports -Wold-style-definition... yes
checking if /usr/bin/gcc-4.2 supports -Wall... yes
checking if /usr/bin/gcc-4.2 supports -Wextra... yes
checking if /usr/bin/gcc-4.2 supports -Wno-missing-field-initializers... yes
checking if /usr/bin/gcc-4.2 supports -Wno-unused-parameter... yes
checking if /usr/bin/gcc-4.2 supports -Wmissing-declarations... yes
checking if /usr/bin/gcc-4.2 supports -Wmissing-noreturn... yes
checking if /usr/bin/gcc-4.2 supports -Wpointer-arith... yes
checking if /usr/bin/gcc-4.2 supports -Wcast-align... yes
checking if /usr/bin/gcc-4.2 supports -Wformat... yes
checking if /usr/bin/gcc-4.2 supports -Wformat-security... yes
checking if /usr/bin/gcc-4.2 supports -Wformat-y2k... yes
checking if /usr/bin/gcc-4.2 supports -Winit-self... yes
checking if /usr/bin/gcc-4.2 supports -Wmissing-include-dirs... yes
checking if /usr/bin/gcc-4.2 supports -Wundef... yes
checking if /usr/bin/gcc-4.2 supports -Wredundant-decls... yes
checking if /usr/bin/gcc-4.2 supports -Wshadow... yes
checking whether /usr/libexec/gcc/powerpc-apple-darwin10/4.2.1/ld accepts --as-needed... no
checking whether /usr/libexec/gcc/powerpc-apple-darwin10/4.2.1/ld accepts -O1... no
checking if /usr/bin/gcc-4.2 supports -Wno-sign-compare... yes
checking whether to build the validation test framework... no
checking PLATFORM_CPPFLAGS... 
checking PLATFORM_CFLAGS... 
checking PLATFORM_LDFLAGS... 
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating docs/Makefile
config.status: creating docs/reference/Makefile
config.status: creating glade/Makefile
config.status: creating glade/icons/Makefile
config.status: creating glade/icons/16x16/Makefile
config.status: creating glade/icons/22x22/Makefile
config.status: creating icons/Makefile
config.status: creating icons/16x16/Makefile
config.status: creating icons/48x48/Makefile
config.status: creating icons/128x128/Makefile
config.status: creating icons/scalable/Makefile
config.status: creating libxfce4kbd-private/libxfce4kbd-private-3.pc
config.status: creating libxfce4kbd-private/Makefile
config.status: creating libxfce4ui/libxfce4ui-2.pc
config.status: creating libxfce4ui/libxfce4ui-config.h
config.status: creating libxfce4ui/Makefile
config.status: creating xfce4-about/Makefile
config.status: creating po/Makefile.in
config.status: creating tests/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing po/stamp-it commands

Build Configuration:

* Glade 3.0 UI Designer:     yes
  - Catalog directory:       /opt/local/share/glade/catalogs
  - Module directory:        /opt/local/lib/glade/modules
  - Pixmap directory:        /opt/local/share/glade/pixmaps
* Keyboard library support:  yes
* Startup notification:      yes
* X11 session management:    yes
* Debug support:             minimum
* Build tests:               no
* GNU Visibility:            no
* Vendor:                    none
* System Info (libgtop):     no
* System Info (epoxy):       no (assumes libgtop)
* System Info (gudev):       no (assumes libgtop)
* Manual website:            https://docs.xfce.org/help.php
```

So yeah, I have put the wrong dependency for the variant. It should be `glade`, not `libglade2`:
```
36-242% port provides /opt/local/lib/libgladeui-2.dylib
/opt/local/lib/libgladeui-2.dylib is provided by: glade
```

**Comment by qwertychouskie** [comment]
The `glade` port is for the GUI application called Glade, version 3.40, and Glade, the GUI application, outputs XML files in the GtkBuilder format to be used by applications.  The old `libglade2` was for UI files in the old `glade` format, which was a predecessor to the GtkBuilder format.  As far as I can tell, there should be no reason for any library to link to Glade the GUI application, and as far as I understand, any use of `libglade2` is only potentially applicable to GTK2 applications.

It's possible I'm missing something, so I'm going to poke around the `lixfce4ui` GitLab repo a bit, but my understanding as it is now is that anything Glade related in this library is legacy cruft from the GTK2 days and shouldn't be left around when all of Xfce has been GTK3 for a while now.

**Comment by qwertychouskie** [comment]
(Also, the `glade` port has some heavy dependencies)

**Comment by barracuda156** [comment]
> (Also, the `glade` port has some heavy dependencies)

@qwertychouskie Those are optional, and `glade` builds even on PowerPC now, but after all, I am not insisting at all.
I will just keep an arg to disable using glade then, and drop the variant.

**Comment by qwertychouskie** [comment]
FWIW, I did figure out what the glade stuff was supposed to be, apparently it's optional support to add XFCE widgets to the Glade interface design tool, to be used for developing XFCE stuff.  Since the amount of people doing upstream XFCE development on macOS is almost certainly 0, no need to have the additional complexity around.

Everything else is probably fine, I'm not an expert but this is probably safe to merge given that all tests have passed.

**Comment by barracuda156** [comment]
@reneeotten @pmetzger @herbygillot Could someone please help with merging this? We are good to go now.

**Pull request merged**
