### PR TITLE
amule: new port

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Let’s see if this builds.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
So CI fails to link precisely on same symbols which were failing for me on PPC. So apparently it is neither PPC issue nor some GCC quirk.

@kencu @evanmiller Any idea why this occurs and how to fix it?

**Comment by kencu** [comment]
most likely would need to add a link against the FrameWorks where those are defined ..

**Comment by barracuda156** [comment]
> most likely would need to add a link against the FrameWorks where those are defined .. 

I will try to find that, thanks.

**Comment by kencu** [comment]
iokit and coreservices look promising

**Comment by barracuda156** [comment]
@kencu Locally everything is good now, all patches dropped. Thank you!

**Comment by barracuda156** [comment]
CI pass now on Intel too, awesome.

**Comment by barracuda156** [comment]
@herbygillot @reneeotten If there are no objections, could we merge this? Thanks to Ken’s advice, all patches dropped, so should be uncontroversial.

**Pull request merged**
