### PR TITLE
Removed wikkawiki port (project has been retired and is no longer maintained)

### PR DESCRIPTION
**Pull request by bakoontz**
#### Description

WikkaWiki has been retired and is no longer maintained:

http://wikkawiki.org

###### Type(s)
Remove port

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
n/a

###### Verification 
n/a

### CODE REVIEW

**Comment by pmetzger** [comment]
Does anything else depend on this port?

**Comment by bakoontz2** [comment]
Not unless someone else has come along and create a dependency.  It's a user app, so I doubt it.

**Comment by pmetzger** [comment]
"Doubt" isn't sufficient. Grep the repository. It will take you a minute or two. (And please don't ask me to do it, I have a lot of PRs to deal with.)

**Comment by bakoontz** [comment]
Repository grepped, no hits on "wikka" (case-insensitive).

**Comment by pmetzger** [comment]
Thanks!

**Pull request merged**
