### PR TITLE
kitten: new port in devel

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

New port: https://github.com/rvarago/kitten

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

Test passes on Rosetta:
```
--->  Testing kitten
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_math_kitten/kitten/work/build" && ctest test 
Test project /opt/local/var/macports/build/_opt_PPCRosettaPorts_math_kitten/kitten/work/build
    Start 1: kitten_tests
1/1 Test #1: kitten_tests .....................   Passed    0.03 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.05 sec
```

### CODE REVIEW

**Comment by szhorvat** [comment]
This was added in the `math` subdirectory, but it's not a tool for doing mathematics. It seems to me that it's just a helper library for generic programming tasks.

**Comment by barracuda156** [comment]
> This was added in the `math` subdirectory, but it's not a tool for doing mathematics. It seems to me that it's just a helper library for generic programming tasks.

@szhorvat Category theory is a branch of algebra, but no issues, I can move it to devel.

**Comment by szhorvat** [comment]
What is the purpose of this library? Is it used for research in category theory? Or does it merely get inspiration from category theory to implement some programming helpers?

**Comment by barracuda156** [comment]
> What is the purpose of this library? Is it used for research in category theory? Or does it merely get inspiration from category theory to implement some programming helpers?

I get your point, no objections. I will have to add a fix for Clang build anyway, so gonna move it to devel with rebasing.

**Comment by barracuda156** [comment]
Forgot that tests are built by default. Gimme a min, I will change the portfile logic a bit.

**Pull request merged**
