### PR TITLE
Wireshark*: updates

### PR DESCRIPTION
**Pull request by ra1nb0w**
#### Description

update the following packages:
- wireshark3 to 3.0.1
- wireshark2 to 2.6.8
- wireshark24 to 2.4.14

Removed unused patches.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.4 18E226
Xcode 10.2 10E125

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ra1nb0w** [comment]
What do you think about removing old wireshark like
- `wireshark`
- `wireshark-devel`
- `wireshark22`
and maybe create a wireshark meta package that point to the last wireshark?

**Comment by ra1nb0w** [comment]
> Thanks for the PR - I'd already done the wireshark 3.0.1 bump separately but not the patch file deletions. If you'd like to redo the wireshark3 PR to be just the patch file deletions feel free, or let me know and I'll remove them.

done.
what do you think about removing (obsolete) old wireshark ports?

**Comment by ghosthound** [comment]
In regards to removing the older wireshark ports, I think it'd be good to open up to a broader discussion - I don't know if anyone has reasons to keep them and the wireshark-devel port is maintained by someone else.
Maybe open a trac ticket and assign the various maintainers.

**Comment by ra1nb0w** [comment]
thank you! I open a track ticket.

**Pull request merged**
