### PR TITLE
gpsd: update to 3.21

### PR DESCRIPTION
**Pull request by SeekingMeaning**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by michaelld** [comment]
LOL: "Change Version to 3.21 for release.  But not yet a release." ... nice commit message!

**Comment by fhgwright** [comment]
> LOL: "Change Version to 3.21 for release. But not yet a release." ... nice commit message!

Yeah, typos and inaccuracies are common in gpsd commit messages.

PLEASE don't update the gpsd port without checking with me.  I was planning to do it myself, and there is at least one important regression that I found during prerelease testing (and which Gary refused to fix) that will almost certainly require patching.  In any case, I'm sure you don't have the same range of VMs and bootable partitions as I do to fully test an update.

I.e.,

!LGTM

**Comment by michaelld** [comment]
> > LOL: "Change Version to 3.21 for release. But not yet a release." ... nice commit message!
> 
> Yeah, typos and inaccuracies are common in gpsd commit messages.

Indeed!
 
> PLEASE don't update the gpsd port without checking with me. I was planning to do it myself, and there is at least one important regression that I found during prerelease testing (and which Gary refused to fix) that will almost certainly require patching. In any case, I'm sure you don't have the same range of VMs and bootable partitions as I do to fully test an update.
> 
> I.e.,
> 
> !LGTM

Apologies ... I thought your were the originator of the PR ... that was my bad & I will strive to do better.

I'm sure you know what I write below, and I'm sure you'll poke holes in it ... but I'm sending it anyway since I've written it and feel strongly that if nothing else it needs to be said:

That said, if there is a new release and it builds cleanly on the MP CI -- which I'm sure is less limited than your overall CI (as noted: VMs and bootable partitions -- same as what I do) -- then I don't see why we shouldn't merge it in.

MP is not responsible for regressions or bugs in the upstream code; that's the responsibility of upstream & when found and fixed if any are serious enough then the code version needs to be bumped. [We in MP might fix them via a temporary patch; and, yes, sometimes we do patch code to make it more MP compatible ... and I'm sure sometimes even to tweak functionality to a certain degree that some MP devs would say go beyond the scope of what MP should be doing.] Anyway: MP in not responsible for intra-project issues. We do our best to keep up with the releases as best makes sense. Each project has to figure out when and how to do their own release.

If the MP fails CI and/or the update does not build locally -- or, dependencies fail when using the updated code -- then that's a different matter & the PR should not be merged in the first place until enough of the issues are worked out that it makes sense to do the merge.

For this specific PR, all CI passed and it built on my local system ... all of which are positive indicators. Hence between those positives and my mistaking the PR as being from you rather than just tagging you, I went ahead with the merge.

**Comment by fhgwright** [comment]
> > PLEASE don't update the gpsd port without checking with me. I was planning to do it myself, and there is at least one important regression that I found during prerelease testing (and which Gary refused to fix) that will almost certainly require patching. In any case, I'm sure you don't have the same range of VMs and bootable partitions as I do to fully test an update.
> > I.e.,
> > !LGTM
> 
> Apologies ... I thought your were the originator of the PR ... that was my bad & I will strive to do better.

Thanks for trying to merge "my" commit promptly, but it wasn't mine.  My commits are normally better documented. :-)

> I'm sure you know what I write below, and I'm sure you'll poke holes in it ... but I'm sending it anyway since I've written it and feel strongly that if nothing else it needs to be said:
> 
> That said, if there is a new release and it builds cleanly on the MP CI -- which I'm sure is less limited than your overall CI (as noted: VMs and bootable partitions -- same as what I do) -- then I don't see why we shouldn't merge it in.

There is a lot of variation in how well upstream developers support the Mac, and one shouldn't assume that the upstream code is well-tested on the Mac, especially across OS versions.  CI systems are good for ***additional*** testing, but often an inadequate substitute for other tests.

There are some things that are difficult or impossible to test in the CI environment.  For example, a while back, someone changed the default Python version in the Python PortGroup, with the effect that ntpsec would build and install just fine, but none of the included Python programs actually worked.

> MP is not responsible for regressions or bugs in the upstream code; that's the responsibility of upstream & when found and fixed if any are serious enough then the code version needs to be bumped. [We in MP might fix them via a temporary patch; and, yes, sometimes we do patch code to make it more MP compatible ... and I'm sure sometimes even to tweak functionality to a certain degree that some MP devs would say go beyond the scope of what MP should be doing.] Anyway: MP in not responsible for intra-project issues. We do our best to keep up with the releases as best makes sense. Each project has to figure out when and how to do their own release.

I don't think most users are interested in a finger-pointing contest between MacPorts and upstream developers.  From their POV, broken is broken, and MacPorts is the first line of blame when that's where they got the software.  Granted, port maintainers may not want to do the extra work of fully testing upstream code, and most of them don't test on older systems, but one shouldn't get in the way when they do.

> If the MP fails CI and/or the update does not build locally -- or, dependencies fail when using the updated code -- then that's a different matter & the PR should not be merged in the first place until enough of the issues are worked out that it makes sense to do the merge.
> 
> For this specific PR, all CI passed and it built on my local system ... all of which are positive indicators. Hence between those positives and my mistaking the PR as being from you rather than just tagging you, I went ahead with the merge.

As it turns out, the problem I saw in prerelease testing didn't recur when I was testing the port version (for unknown reasons), so the current update is OK, but I submitted a PR (#8014) with some cleanups, after more thorough testing.

**Pull request merged**
