### PR TITLE
ocaml: update to 4.14

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

@pmetzger Portfile only updates the version and checksums, nothing else touched. Patches for PPC are updated to fit into the changed configure script, but otherwise are the same.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8
Xcode 3.2.6

macOS 10A190
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Seems fine by me, though we will need to bump the tiny rev on all OCaml packages after this. (Best, of course, to do any required real updates at the same time.)

**Comment by pmetzger** [comment]
BTW, FWIW, 5.0 isn't very far off, but it's not as such harmful to do this twice.

**Comment by pmetzger** [comment]
Sorry for being slow about this. FYI, OCaml 5.0 is now out. Will try to reply to your email.

**Comment by barracuda156** [comment]
> Sorry for being slow about this. Will try to reply to your email.

@pmetzger No worries, take your time. I am quite busy atm with unrelated stuff, and also finalizing another PR dealing with R ports: https://github.com/macports/macports-ports/pull/16916

But I hope we can get back to OCaml ports in the meanwhile and sort that out before end of January. (I am away from native PPC hardware until mid Jan, which makes testing less robust. However, for `stanc3` everything with OCaml was already confirmed to build – what is left is sort out dependency lists which may be incomplete for some new ports and also fix a still broken `ocaml-dune-configurator`.)

> FYI, OCaml 5.0 is now out.

Do you think it is better to move directly to OCaml 5.0, skipping 4.14? Or do it gradually, leaving 5.0 for somewhat later? (I just follow you here – you know the subject better.)

**Comment by pmetzger** [comment]
5.0 is a giant change. I'd assume we will switch to it in a couple of months, but that switching to 4.14 in the interim is probably safer.

**Comment by barracuda156** [comment]
@pmetzger Could you please say where are we here? I would prefer having this merged, since until then I cannot make a PR for `Stanc` – it requires many new OCaml ports, and a) we rather have them built with one OCaml version, else something may need to be rebuilt, and b) I tested everything with 4.14.

**Comment by barracuda156** [comment]
@pmetzger When you have a chance to reply, where we are on this? Update should be trivial, and would make submissions for OCaml ports a bit easier.

**Comment by barracuda156** [comment]
@pmetzger @reneeotten @harens This is perhaps good to merge finally :) Minimal update, CI pass, `ppc` works fine.

**Comment by barracuda156** [comment]
@mascguy Maybe this can be merged finally? @pmetzger agreed with an interim update to 4.14 https://github.com/macports/macports-ports/pull/16741#issuecomment-1357849526 but since then PR got stalled.

**Review by mascguy — APPROVED** [review]
LGTM

**Comment by pmetzger** [comment]
We really should bump at this point to OCaml 5. All the things that were broken when it was released now work.

**Comment by barracuda156** [comment]
@pmetzger @mascguy I looked at available versions, and apparently it is either 5.0.0 (initial release), dating back to December, or 5.1.0 _alpha,_ which is perhaps not stable, judging by the tag?

**Comment by barracuda156** [comment]
Admittedly I just tried to fun it (5.0.0) after a quick manual fix to configure (nothing beyond what we had in 4.x, had to remove on flag due to number-of-arguments complaint or the build system), but this version appears raw at best. Configure fails on:
```
config.status: creating ocamltest/ocamltest_config.ml
config.status: error: cannot find input file: `utils/config.generated.ml.in'
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_ocaml/ocaml/work/ocaml-5.0.0" && ./configure --prefix=/opt/local --mandir=/opt/local/share/man 
Exit code: 1
```

**Comment by pmetzger** [comment]
5.0 isn't the least bit raw. It's what everyone is using. You shouldn't expect it to work on Snow Leopard or other things that are more than a decade old.

**Comment by pmetzger** [comment]
(Pretty soon it will be impossible to use new OCaml code without 5.0 because of the changes to the language for parallelism.)

**Comment by barracuda156** [comment]
@pmetzger Are there any particular – know to you – reasons why it won’t work on SL?
If it is something really unfixable, then we should pin PowerPC and <= 10.6 x86 to 4.14.x.

@catap I know you have been busy with SBCL (so myself), but when you got a few minutes, could you take a look at OCaml 5 on 10.5–10.6 Intel? I think if SDK issues are sorted (if anything is a blocker), I can take care of the arch fixes for PowerPC.

**Pull request merged**
