### PR TITLE
ruby: some new ports

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

New ports, a couple of updates

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.3.1
Xcode 15.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
No idea why this silly failure claiming to fail to install dependencies when the log shows that all dependencies were in fact successfully installed 🤷🏻‍♂️

**Comment by barracuda156** [comment]
@pmetzger @herbygillot Should be good to merge, I guess.

**Comment by pmetzger** [comment]
On what basis are you adding these? Are they needed for some other port?

**Comment by barracuda156** [comment]
@pmetzger I guess, we add ports because either intend to use them or think they may be useful for others?

But yeah, it is not random out of the blue stuff.
Most of these are to support Twitter API-related stuff, like: https://twterm.ryota-ka.me

I do not have a plan to add the whole of rubygems here, of course.
I was thinking of a) cleaning up what we have (remove archaic Ruby, update ports to current versions), b) adding select ports for development and math, and c) adding apps which can be usable for the web (not much here: besides Twitter stuff I want to add `sup` e-mail client).

**Pull request merged**
