### PR TITLE
py-netcdf4: revbump

### PR DESCRIPTION
**Pull request by mojca**
#### Description

Just resolving
```
--->  Scanning binaries for linking errors
Could not open /opt/local/lib/libhdf5.101.dylib: Error opening or reading file (referenced from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/netCDF4/_netCDF4.so)
--->  Found 2 broken files, matching files to ports      
--->  Found 2 broken ports, determining rebuild order
You can always run 'port rev-upgrade' again to fix errors.
The following ports will be rebuilt:
 py27-netcdf4 @1.2.9
 py37-netcdf4 @1.2.9
```
and wondering if perhaps these ports also need an explicit dependency on `hdf5`.

@mamoll

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by seanfarley** [comment]
Fine by me. I don't know about the `hdf5` dependency, though. I'd have to investigate that more (IIRC it's an optional dependency for netcdf; though not sure if that changed).

**Comment by ryandesign** [comment]
> I don't know about the `hdf5` dependency, though. I'd have to investigate that more (IIRC it's an optional dependency for netcdf; though not sure if that changed).

See https://trac.macports.org/ticket/57733

**Comment by seanfarley** [comment]
It's because netcdf4 is built on top of hdf5: http://unidata.github.io/netcdf4-python/ (that's a python link but explains the netcdf4 file format vs netcdf3). The port does add a hdf5 dependency for the `+netcdf4` variant:

```
variant netcdf4 description {enable support for netcdf-4 API} {
    depends_lib-append      port:hdf5
    configure.args-delete   -DENABLE_NETCDF_4=OFF
    configure.args-append   -DENABLE_NETCDF_4=ON
}
```

but I suspect the difficult here is that we can't easily test dependencies on variants. The easiest solution would be to always build netcdf4 but I'm not sure of the fallout on that.

**Comment by mojca** [comment]
We definitely can test for variants of dependencies. What we cannot do is force a particular variant on a dependency (i.e. reinstall the dependency with the desired variant).

What you can do for example is check with what variant a dependency is built, and then use the same variant in your port. (I think I do this in `gate`, but I'm not 100 % sure.)

**Comment by mojca** [comment]
One request though: could we revbump now just to avoid the warnings, and then separately solve the rest of the issues if it takes longer to figure out what the proper approach is?

**Comment by seanfarley** [comment]
Yes, please revbump; sorry that wasn't clear before.

**Pull request merged**
