### PR TITLE
help2man: add perl5_28 and [+]perl5_30 variants

### PR DESCRIPTION
**Pull request by FnControlOption**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G9323 x86_64
Xcode 11.3.1 11C505

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
The idea I thought we have been trying to promote is that MacPorts uses one blessed version of perl (and, as much as possible, python) for everything, so users don't need three, four, or six perls installed to satisfy all the various different ports.

And then at one time, en masse, everything changes to the new blessed perl, as specified by the perl5 PortGrou, which is, I understand, just about to happen, and the PR is in place to move all of the perl ports in MacPorts to perl5.34 just about any moment.

@mojca  -- can you shed any light? I though this kind of multi-perling was what we were trying to avoid, but it's not my core area.

**Comment by mojca** [comment]
Yes, what @kencu says is true.
While it's nothing wrong in principle to add variants for multiple perl versions, making 5.30 the default at this moment doesn't make any sense whatsoever. 5.30 is already obsolete (no longer supported), we have 5.32 subports available, but the plan would be to do a mass switch to 5.34.

Now, to be fair, "at one time, en masse" often used to mean around one year in the past since there are hundreds of port that depend on perl, and nobody took the time and effort to migrate everything, but ideally that's what we would strive for.

**Comment by mojca** [comment]
That said, using the perl portgroup (without actually creating variants) is potentially helpful in making the ports more consistent.

**Comment by FnControlOption** [comment]
Okay. Thanks for clarifying. Until the mass migration is complete, should I add 5.32 and make it the default variant? I made 5.30 the default here because that's the version that the port was already using.

I should have mentioned this, but my reason for adding these variants was so that I could use perl 5.28 installed by the default `git` variant. Why is 5.28 the default `git` variant, anyway? Is perl 5.28 similar to ruby 2.6 in that it works on most macOS versions?

**Comment by kurthindenburg** [comment]
Go ahead and do whatever is "standard" now - anything that makes upgrading perl/python versions easier is better MHO

**Comment by reneeotten** [comment]
can someone (@mojca @kurthindenburg ?) please make a decision on what changes to make and get this PR merged?

**Pull request closed without merging**
