### PR TITLE
bsdsfv: cleanup MacPorts < 2.6.0 handling

### PR DESCRIPTION
**Pull request by chrstphrchvz**
###### 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
This port's maintainer has not had any activity with MacPorts in a long time, but I wouldn't say for certain that this port is necessarily abandoned; it is at the final release published in 2003, and doesn't seem to have had any issues reported.

The maintainer's GitHub handle is @simmel: is the maintainer still interested in this port? If so, would the maintainer prefer if this port be made `openmaintainer`?

Given the upstream project's dormancy, is this still a good port to keep in MacPorts, or is there reason to remove it?

**Comment by simmel** [comment]
Hey @chrstphrchvz! Old sins come to haunt me, huh? = ) I sadly don't use MacPorts anymore (but Homebrew is soon on the last staw so I might switch soon) and as you said there is no new version of bsdsfv (and the SFV standard is pretty much complete and never going to update).

Why I wanted to import bsdsfv was because it was the best SFV checker I could find.

The lint warnings seems easy to fix, I can give it a shot if you want me to?

**Comment by simmel** [comment]
> If so, would the maintainer prefer if this port be made openmaintainer?

I don't know what this means, I guess that there is no maintainer?

**Comment by mf2k** [comment]
It just means that you are OK with other people making changes to this port without your approval.

**Comment by simmel** [comment]
Oh, totally = )

**Pull request merged**
