### PR TITLE
opam: update to @2.1.2

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Just version update.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by usersxx** [comment]
@barracuda156, Instead of [x ], use [x]
Difference:
- [x ] option
- [x] option

**Comment by barracuda156** [comment]
@kencu Any idea how to fix undefined `__Unwind_Resume`? I get this error on 10.6 PPC, however it is clearly not due to some deficiency of 10.6 PPC, since a similar error was reported for older systems: https://lists.apple.com/archives/xcode-users/2005/Nov/msg00716.html
```
Undefined symbols:
  "__Unwind_Resume", referenced from:
      __Z19call_mccs_protected6SolverPciP11CUDFproblem in libmccs_stubs.a(mccs_stubs.o)
      _call_solver in libmccs_stubs.a(mccs_stubs.o)
      __Z13ml2c_propertyP16Virtual_packagesPSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEP12CUDFPropertySt4lessIS7_ESaISt4pairIKS7_S9_EEEl in libmccs_stubs.a(mccs_stubs.o)
      __Z16ml2c_propertydefP16Virtual_packagesl in libmccs_stubs.a(mccs_stubs.o)
      __Z12ml2c_packageP16Virtual_packagesPSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEP12CUDFPropertySt4lessIS7_ESaISt4pairIKS7_S9_EEERil in libmccs_stubs.a(mccs_stubs.o)
      __Z20ml2c_propertydeflistB5cxx11P16Virtual_packagesl in libmccs_stubs.a(mccs_stubs.o)
      _gen_problem in libmccs_stubs.a(mccs_stubs.o)
      __ZN16Virtual_packages3getEPKc in libmccs_stubs.a(mccs_stubs.o)
      __ZN20CUDFVersionedPackageC4EPKci in libmccs_stubs.a(cudf_tools.o)
      __ZN18CUDFVirtualPackageC4EPKci in libmccs_stubs.a(cudf_tools.o)
      __Z19get_criteria_lambdaPcRjc in libmccs_stubs.a(mccscudf.o)
      __Z26get_criteria_property_namePcRj in libmccs_stubs.a(mccscudf.o)
      __Z36get_criteria_property_name_and_scopePcRjR11Count_scope in libmccs_stubs.a(mccscudf.o)
      __Z9call_mccs6SolverPciP11CUDFproblemPP15abstract_solver in libmccs_stubs.a(mccscudf.o)
      __ZN9lp_solver13add_objectiveEv in libmccs_stubs.a(lp_solver.o)
      __Z20compute_reduced_CUDFP11CUDFproblem in libmccs_stubs.a(cudf_reductions.o)
      __ZNSt8_Rb_treeIySt4pairIKySt6vectorIP20CUDFVersionedPackageSaIS4_EEESt10_Select1stIS7_ESt4lessIyESaIS7_EE17_M_construct_nodeIJRKS7_EEEvPSt13_Rb_tree_nodeIS7_EDpOT_.isra.0 in libmccs_stubs.a(constraint_generation.o)
      __ZNSt8_Rb_treeIySt4pairIKySt6vectorIP20CUDFVersionedPackageSaIS4_EEESt10_Select1stIS7_ESt4lessIyESaIS7_EE7_M_copyILb0ENSD_11_Alloc_nodeEEEPSt13_Rb_tree_nodeIS7_ESI_PSt18_Rb_tree_node_baseRT0_.isra.0 in libmccs_stubs.a(constraint_generation.o)
      __ZNSt8_Rb_treeIySt4pairIKySt6vectorIP20CUDFVersionedPackageSaIS4_EEESt10_Select1stIS7_ESt4lessIyESaIS7_EE7_M_copyILb0ENSD_20_Reuse_or_alloc_nodeEEEPSt13_Rb_tree_nodeIS7_ESI_PSt18_Rb_tree_node_baseRT0_.isra.0 in libmccs_stubs.a(constraint_generation.o)
      __Z18preprocess_upgradeP11CUDFproblemRiRSt6vectorI14an_upgrade_setSaIS3_EE in libmccs_stubs.a(constraint_generation.o)
      __Z20generate_constraintsP11CUDFproblemR15abstract_solverR17abstract_combiner in libmccs_stubs.a(constraint_generation.o)
      __ZN11glpk_solver5solveEi in libmccs_stubs.a(glpk_solver.o)
      __ZN11glpk_solver13add_objectiveEv in libmccs_stubs.a(glpk_solver.o)
ld: symbol(s) not found
```
On 10.6.8 `opam` @2.1.2 builds normally. Identical build of `ocaml`, `gcc11` 11.3.0.

**Comment by pmetzger** [comment]
Manually upgraded in [1d03d9f](https://github.com/macports/macports-ports/commit/1d03d9fe49a5ce896f896d03daebc8a3e2246516) — note that I didn't do the various unicode comment changes etc. as they seemed unneeded.

**Comment by kencu** [comment]
> @kencu Any idea how to fix undefined `__Unwind_Resume`? I get this error on 10.6 PPC, however it is clearly not due to some deficiency of 10.6 PPC, since a similar error was reported for older systems: https://lists.apple.com/archives/xcode-users/2005/Nov/msg00716.html
> 
> ```
> Undefined symbols:
>   "__Unwind_Resume", referenced from:
>       __Z19call_mccs_protected6SolverPciP11CUDFproblem in libmccs_stubs.a(mccs_stubs.o)
>       _call_solver in libmccs_stubs.a(mccs_stubs.o)

You need to find the library where Unwind_Resume is available, and make sure it is being linked in.

Where this symbol is found can vary depending on the system version, and in the case of 10.6 on PPC, who knows exactly, as it is neither 10.5 nor 10.6.

You can google which library it is in, but likely candidates would be libSystem.dylib (some system version), libunwind.dylib (as supplied by MacPorts), and some of those weirdly-named gcc libraries, like libgcc.S.1.c4657585994.xyz.dylib, for which I am sure Iain would immediately know which one to check, but I do not, so would just start checking them all until I found it.

"nm -a | grep Unwind_Resume libMyLibrary.dylib" is your friend.

Good luck!

(probably this: 
```
depends.lib-append port:libunwind
configure.ldflags-append -lunwind
```

**Comment by barracuda156** [comment]
@pmetzger Thank you.

@kencu I will try to sort this out, thank you very much for guidelines!

**Pull request closed without merging**
