### PR TITLE
nodejs6: update to 6.9.4

### PR DESCRIPTION
**Pull request by CarloQ**

### CODE REVIEW

**Comment by mojca** [comment]
There is already #128. (I was hoping to get maintainer's feedback.)

**Comment by CarloQ** [comment]
Sorry, I didn't see it...

**Comment by g5pw** [comment]
@mojca Could you apply changes from this one into #128 so we can close this PR and continue discussion over?

**Comment by mojca** [comment]
> @mojca Could you apply changes from this one into #128 so we can close this PR and continue discussion over there?

Done.

**Pull request closed without merging**
