### PR TITLE
py-dns, lamson: delete ports

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description

- Lamson's [repository](https://github.com/zedshaw/lamson) was last updated ~2013, and its homepage was already offline in 2015. There is an actively maintained GPLv3 fork of it, [Salmon](https://github.com/moggers87/salmon), which doesn't already have a port. There is a 5-year-old open ticket for this port (missing dependency not in MP): https://trac.macports.org/ticket/40001

- PyDNS does not appear to be maintained by its developer any longer. It was last updated in 2012 (2.3.6, which MP never adopted), and it does not support Python 3. dnspython seems like the far more popular and actively maintained alternative; but since it's not a drop-in replacement for PyDNS, and the only dependent of `py-dns` is `lamson`, I think the port can be removed.

I'm not familiar with deleting ports, so any advice or suggestions are appreciated. I'd be interested in cleaning out more old ports, yet I imagine it might be either more worthwhile or a higher priority to focus on more actively-used/maintained ports.

Also, should Python packages that happen to be named "PyFoo" have their ports consistently named `py-pyfoo` instead of `py-foo`? I think doing so is better at preserving/respecting the package's name, and also so that the `py-` prefix only indicates it's a Python-related port and avoids confusion of whether the package itself is named "Foo" or "PyFoo". I can ask on the dev mailing list unless there's already a consensus. I haven't yet found any examples which are actively maintained though.

### CODE REVIEW

**Comment by pmetzger** [comment]
Does anything depend on either of these two? If not, I think we can probably get rid of them, yes.

**Comment by mf2k** [comment]
It appears so for py-dns:
```
$ port echo depends:py27-dns
lamson                          
ligo-lvalert                    
linkchecker                     
mailman                         
py-dns                          
py-dnspython                    
py27-ipwhois                    
py27-libnamebench               
py27-pyxmpp                     
dnsviz                          

$ port echo depends:lamson
```

**Comment by pmetzger** [comment]
The fact that there are dependent ports seems like an issue.

**Comment by chrstphrchvz** [comment]
@mf2k I appreciate you checking, I had not used that command, nor was I expecting it to list that many ports after searching portfiles for `port:py{python.version}-dns` and only finding `lamson`.

However, since `py27-dnspython` does not depend on `py27-dns`, I think `port echo depends:py27-dns` is outputting dependents of `py27-dnspython` in addition to `py27-dns`, as if it's looking for any dependencies containing the string (rather than exactly matching) `py27-dns`:

```
$ port echo depends:py27-dns
lamson
ligo-lvalert
linkchecker
mailman
py-dns
py-dnspython
py27-ipwhois
py27-libnamebench
py27-pyxmpp
dnsviz

$ port echo depends:py27-dnspython
ligo-lvalert
linkchecker
mailman
py-dnspython
py27-ipwhois
py27-libnamebench
py27-pyxmpp
dnsviz

$ port info py27-dnsp
Error: Port py27-dnsp not found
$ port echo depends:py27-dnsp
ligo-lvalert
linkchecker
mailman
py-dnspython
py27-ipwhois
py27-libnamebench
py27-pyxmpp
dnsviz
```

I'm not sure if this is the expected or documented behavior, since the [guide](https://guide.macports.org/#using.port.dependents) has the usage:
```
$ port echo depends:portname
```
rather than some sort of `depends:pattern`.

**Comment by tobypeterson** [comment]
Regex works, do: `port echo depends:py27-dns$`

Looks safe to remove both.

**Comment by mf2k** [comment]
Interesting, I did not realize that. Thank you both!

**Comment by tobypeterson** [comment]
Actually, it looks like that'll only match if py27-dns is the last dependency (it is, in this case). So something more like:

`port echo 'depends:py27-dns ' or 'depends:py27-dns$'`

Would be better if we supported more regex, something like this:

`port echo 'depends:py27-dns\W*+'`

**Comment by pmetzger** [comment]
Okay, so is it agreed that it's safe to remove both? If so, I'll commit the change soon.

**Comment by mf2k** [comment]
@pmetzger: Yes, it is safe to remove them.

**Comment by pmetzger** [comment]
Merged. Thanks, @chrstphrchvz!

**Comment by jmroot** [comment]
> Would be better if we supported more regex, something like this:
> 
> `port echo 'depends:py27-dns\W*+'`

Best way is probably `port echo 'depends:\mpy27-dns\M'`. That anchors to a single word in Tcl's AREs (\m matches the empty string at the start of a word and \M at the end of a word).

**Pull request merged**
