### PR TITLE
gnome-radio: update to 46.0 (Los Angeles, United States of America)

### PR DESCRIPTION
**Pull request by oleaamot**
#### Description

Update gnome-radio 46.0 from www.gnomeradio.org (Los Angeles, United States of America)

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.5 21G72 arm64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Ole, I'll squash the commits on merge.

**Comment by oleaamot** [comment]
Thank you.

**Review by mascguy — APPROVED** [review]

**Comment by oleaamot** [comment]
@mascguy Checkout P3X in Oslo, Norway (text search).  Currently broadcasting Norwegian duo Karpe.

**Comment by oleaamot** [comment]
@mascguy Thanks for the push.

**Pull request merged**
