### PR TITLE
iTerm2: update to 3.2.0

### PR DESCRIPTION
**Pull request by l2dy**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65
Xcode 9.4.1 9F2000

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. @markemer is there a good reason this isn't OpenMaintainer?

**Comment by pmetzger** [comment]
CI system failed on anything other than the latest XCode...

**Comment by markemer** [comment]
Awesome. My email has been broken, glad to see this made it in.

**Comment by pmetzger** [comment]
@l2dy or @markemer Can you submit a pull request to make it openmaintainer and to add an error message for people trying to build it < 10.12?

**Comment by l2dy** [comment]
@pmetzger You can directly push the openmaintainer change. And the error message:

https://github.com/macports/macports-ports/blob/f8b3159f9030ce2765067e522b59330ceb99f6c4/aqua/iTerm2/Portfile#L46-L53

**Comment by pmetzger** [comment]
> You can directly push the openmaintainer change.

Normally I prefer to go through the PR process but in this case at your suggestion I simply pushed this.

**Pull request merged**
