### PR TITLE
jenkins-cli: update to 0.0.32

### PR DESCRIPTION
**Pull request by harens**
#### Description

Out of curiosity, is there any way to integrate the changes from https://github.com/macports/macports-ports/pull/8644 following an update without doing it all manually? Thanks.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.6 19G73
xcode-select version 2373

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
Hey @harens, so most of this is meant to be done by @amake's `go2port` utility, which is also available via ports.

For example, you can do:
```
go2port get github.com/jenkins-zh/jenkins-cli v0.0.32
```

...to generate a Portfile template for this version you're updating `jenkins-cli` to.  I usually keep `checksums` and `go.vendors` as the last portion of my Portfiles so that it's easier to append `go2port`'s output.  `go2port` also has functionality to update existing Portfiles as well, if I recall correctly.

You may run into trouble with any Go packages that aren't in domains supported by the `golang` portgroup, which include github.com and gopkg.in, so you may occassionally have to hunt for and use the `repo` directive to specify the Github repo for a given package, ie.:

```
          honnef.co/go/tools \
               repo    github.com/dominikh/go-tools \
...
```

**Comment by harens** [comment]
Thanks @herbygillot for your explanation.

I realise that I phrased my question quite badly. I already use the very useful `go2port`, I was wondering if there's a way to automate @amake's manual corrections (which are very well written) since there's quite a lot of them. 

But now I have realised that the whole point of manual changes is that they're meant to be done manually :) Sorry for asking and thanks for your help.

**Comment by herbygillot** [comment]
> Thanks @herbygillot for your explanation.
> 
> I realise that I phrased my question quite badly. I already use the very useful `go2port`, I was wondering if there's a way to automate @amake's manual corrections (which are very well written) since there's quite a lot of them.
> 
> But now I have realised that the whole point of manual changes is that they're meant to be done manually :) Sorry for asking and thanks for your help.

It can all definitely be improved, there's no reason for manual steps to remain manual.  If you can think of some changes to make to either or both of the `golang` portgroup or the `go2port` tool itself, or maybe an entirely new way of approaching things, do feel free.

**Comment by herbygillot** [comment]
As for right now, these changes LGTM, so I will merge.

**Pull request merged**
