### PR TITLE
openjdk8: add arm64 support

### PR DESCRIPTION
**Pull request by usersxx**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
@usersxx did you test this locally? It fails in both CI runs; also, please do fill in the PR checklist, it's there for a reason 😉

**Comment by usersxx** [comment]
I don't have an arm64 machine to test. If someone can test, it would be nice.

**Comment by usersxx** [comment]
It builds fine on my folk
[See: CI runs](https://github.com/usersxx/macports-ports/actions/runs/4582495078/jobs/8092755523)

**Comment by reneeotten** [comment]
@usersxx well - it failed the first time around otherwise I wouldn't have said so... no need to close this PR, it might have been an intermittent error with the CI.

**Comment by usersxx** [comment]
@reneeotten  #18298

**Pull request closed without merging**
