### PR TITLE
qt59, qt511, qt513, qt5, qt6: various build fixes

### PR DESCRIPTION
**Pull request by chrstphrchvz**
* qt59-qtlocation, qt511-qtlocation, qt513-qtlocation, qt5-qtlocation, qt6-qtlocation: use `conflicts_build boost` to prevent headers in `${prefix}/include/boost` from taking precedence
  (I only encountered a build error for qt59-qtlocation, but I suggest applying this change to all qtlocation versions containing bundled boost in bundled mapbox-gl-native.)

* qt59, qt511, qt513: fix to allow building on macOS 11/12
  See: https://trac.macports.org/ticket/62190
  See: https://trac.macports.org/ticket/63154

* qt59-qtlocation, qt511-qtlocation: fix build for Xcode ≥ 11
  Fixes: https://trac.macports.org/ticket/61031

* qt5-qtbase: keep Rez patch related lines together

* qt513-qtdeclarative: copy build fix over from qt5
  Put changes intended to be applied simultaneously in a single patchfile
  See: https://trac.macports.org/ticket/62806

[skip ci]

###### Tested on

macOS 12.5 21G72 x86_64
Xcode 14.0 14A5270f

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
qt59-qtlocation fails due to https://trac.macports.org/ticket/61031, that will likely need `known_fail yes` for now.

**Comment by chrstphrchvz** [comment]
Also looking into building qt511/qt513 on macOS 12 (so that 37f083d1fb14da9f589ccccbba3b8e705dd447a6 can be reverted)

**Comment by chrstphrchvz** [comment]
qt513-qtdeclarative is affected by https://trac.macports.org/ticket/62806

This is already a lot more than I intended to put in a single pull request. I would like to keep similar changes for different Qt versions together, however I know this is going to trigger a large number of builds (macOS 11/12 will be particularly busy building qt511/qt513). But as long as I don’t squash things, I don’t see why this PR should be split up when doing so would just trigger additional unnecessary builds.

**Comment by mascguy** [comment]
Chris, do you want to go ahead and fix the merge conflicts for this PR?

**Review by mascguy — APPROVED** [review]
Is this ready for merge as well?

**Pull request merged**
