### PR TITLE
elmerfem: update to 2023.10.02

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@cjones051073 May be unrelated, but CI here fail on `gcc12` now:
```
Installing dependency (51 of 65) 'gcc12-libcxx' with variants '+clang14' ... [FAIL]
```

**Comment by cjones051073** [comment]
> @cjones051073 May be unrelated, but CI here fail on `gcc12` now:
> 
> ```
> Installing dependency (51 of 65) 'gcc12-libcxx' with variants '+clang14' ... [FAIL]
> ```

everything is fine in the buildbots.

Please try rebasing your branch here to pick up the latest master changes.

**Comment by cjones051073** [comment]
Note I just saw a build failure for libgcc12 in the buildbots for a few OSes, which lead me to

https://github.com/macports/macports-ports/commit/5545667f53a49a9bf37d67d5b8da20505b630629

depending on which platforms failed here you might also need that.

**Comment by barracuda156** [comment]
All good here after rebase.

**Pull request merged**
