### PR TITLE
optool: fix build on macOS 12

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.0.1 21A559 x86_64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
LGTM. Rainer?

**Comment by raimue** [comment]
Looks good to me as well! Thanks for the patch! :+1: 

Do you intent to also submit these to https://github.com/alexzielenski/optool? Although it looks abandoned by now...

**Comment by catap** [comment]
@raimue a patch is needed for it's dependency. And the tricky part that dependency are moved away from dependency which required the patch.

:)

To be honest: I have no idea how to submit it.

**Comment by raimue** [comment]
Oh yes, you are completely right. I missed that latest ArgumentParser does not use CoreParse any longer. Thanks for explaining, there is indeed no way to get it into upstream.

**Pull request merged**
