### PR TITLE
ruby27: Fix build on 10.4, 10.5

### PR DESCRIPTION
**Pull request by fhgwright**
This adds patches in three categories:

1) Applicable patches carried forward from ruby26.

2) Proper source fixes for two issues previously worked around with Portfile hacks in ruby26.

3) Fixes for new OS- and CPU-related issues in ruby2.7.

Also, although .gdbinit isn't actually installed, this fixes it since a working gdb is useful when debugging port brokenness.

All new source patches are in a single patchfile derived from the ruby fork at github.com/fhgwright/ruby.  The changes are much more readable in the git repo.  A second patchfile (also derived from the GitHub fork) patches 'configure' to reflect the source changes without rerunning autoconf.

Although this update mostly only affects previously failing builds, it also changes the i386 context handling in successful builds as well, therefore requiring a revbump.

In theory, the installed content should be unchanged on successful non-i386 builds.  In practice, there appear to be nonreproducible build issues affecting libruby.2.7-static.a and many .gemspec files, though there are presumably no effective differences.

Fixes a couple of typos in a Portfile comment.

Adds a comment to the Portfile regarding a known trace-mode issue.

Also adds self as co-maintainer.

TESTED:
Built successfully -universal on OSX 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-10.15 x86_64, and 11.x-13.x arm64.  Also successfully built +universal in all such cases except where the +universal dependencies failed to build (as well as in 10.14-10.15, where +universal is unavailable).

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

Mac OS X 10.4.11 8S165, PPC, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, i386, Xcode 2.5 8M2558
Mac OS X 10.5.8 9L31a, PPC, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, i386, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, x86_64, Xcode 3.1.4 9M2809
Mac OS X 10.6.8 10K549, i386, Xcode 3.2.6 10M2518
Mac OS X 10.6.8 10K549, x86_64, Xcode 3.2.6 10M2518
Mac OS X 10.7.5 11G63, x86_64, Xcode 4.6.3 4H1503
OS X 10.8.5 12F2560, x86_64, Xcode 5.1.1 5B1008
OS X 10.9.5 13F1911, x86_64, Xcode 6.2 6C131e
OS X 10.10.5 14F2511, x86_64, Xcode 7.2 7C68
OS X 10.11.6 15G22010, x86_64, Xcode 8.1 8B62
macOS 10.12.6 16G2136, x86_64, Xcode 9.2 9C40b
macOS 10.13.6 17G14042, x86_64, Xcode 10.1 10B61
macOS 10.14.6 18G9323, x86_64, Xcode 11.3.1 11C505
macOS 10.15.7 19H2, x86_64, Xcode 12.4 12D4e
macOS 11.7.2 20G1020, arm64, Xcode 13.2.1 13C100
macOS 12.6.2 21G320, arm64, Xcode 14.2 14C18
macOS 13.1 22C65, arm64, Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [N/A] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [KNOWN FAIL] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Have you tried tests on PPC? Do they pass? I was having issues with test suite freezing at some point: https://trac.macports.org/ticket/64906

**Comment by fhgwright** [comment]
@barracuda156 
> Have you tried tests on PPC? Do they pass? I was having issues with test suite freezing at some point: https://trac.macports.org/ticket/64906

The ruby tests have never worked.  In most cases they just hang, probably due to some bug in the test runner, and when they don't hang they fail on a test that uses a local-domain socket which exceeds the OS-imposed socket-name length limit when the build-tree root is an insanely long path (as it always is in MacPorts).

Back when I was working on ruby26, I found that out and decided against enabling the test phase, but then someone else did it without bothering to notice that they don't actually work.  That would be nice to fix, but not trivial.

**Comment by barracuda156** [comment]
> The ruby tests have never worked. In most cases they just hang, probably due to some bug in the test runner, and when they don't hang they fail on a test that uses a local-domain socket which exceeds the OS-imposed socket-name length limit when the build-tree root is an insanely long path (as it always is in MacPorts).
> 
> Back when I was working on ruby26, I found that out and decided against enabling the test phase, but then someone else did it without bothering to notice that they don't actually work. That would be nice to fix, but not trivial.

Aha, okay, so it is not only with me. What you described sounds exactly like what I got as well.

**Comment by fhgwright** [comment]
I updated this to fold the preexisting patchfile into the combined patchfiles.  I'd originally left the old patchfile alone in the interests of reducing the change volume, but in view of the lack of response, I changed it to the cleaner long-term setup, which is also more similar to the `ruby30` changes already merged (in fact, the `ruby27` and `ruby30` code fixes are effectively identical).

**Comment by fhgwright** [comment]
Also, although I didn't redo the testing, I did verify that this latest change didn't alter the results of the patch phase.

**Comment by barracuda156** [comment]
@fhgwright I sorta realise that I am the only one here to care about 10.6 (so this is just for the record), but now, after reverting back `asciidoctor` to `ruby30`, it is again broken on 10.6 for ppc. While `ruby30` builds successfully after the recent update, it does not work. At the same time `ruby31` works fine.

With `ruby30`, the build freezes on:
```
Executing:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_textproc_asciidoctor/asciidoctor/work/asciidoctor-2.0.18" && /opt/local/bin/gem3.0 install --local --force --install-dir /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_textproc_asciidoctor/asciidoctor/work/destroot/opt/local/lib/ruby3.0/gems/3.0.0 /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_textproc_asciidoctor/asciidoctor/work/asciidoctor-2.0.18/asciidoctor.gem
```
It freezes so badly that Control+C does not help.
Here is the process snapshot:
```
Analysis of sampling ruby3.0 (pid 70845) every 1 millisecond
Call graph:
    1795 Thread_350b
      1795 start
        1795 main
          1795 ruby_run_node
            1795 rb_ec_exec_node
              1795 rb_vm_exec
                1795 vm_exec_core
                  1795 vm_sendish
                    1795 vm_call_cfunc_with_frame
                      1795 rb_ary_each
                        1795 rb_yield
                          1795 rb_yield_0
                            1795 rb_vm_exec
                              1795 vm_exec_core
                                1795 vm_sendish
                                  1795 vm_call_cfunc_with_frame
                                    1795 rb_ary_each
                                      1795 rb_yield
                                        1795 rb_yield_0
                                          1795 rb_vm_exec
                                            1795 vm_exec_core
                                              1795 vm_sendish
                                                1795 vm_call_cfunc_with_frame
                                                  1795 rb_ensure
                                                    1795 rb_yield
                                                      1795 rb_yield_0
                                                        1795 rb_vm_exec
                                                          1795 vm_exec_core
                                                            1795 vm_sendish
                                                              1795 vm_call_cfunc_with_frame
                                                                1795 rb_ensure
                                                                  1795 rb_yield
                                                                    1795 rb_yield_0
                                                                      1795 rb_vm_exec
                                                                        1795 vm_exec_core
                                                                          1795 vm_sendish
                                                                            1795 vm_call_cfunc_with_frame
                                                                              1795 gzfile_read
                                                                                1795 zstream_shift_buffer
                                                                                  1795 str_new0
                                                                                    1795 newobj_of
                                                                                      1795 newobj_slowpath_wb_protected
                                                                                        1795 ractor_cache_slots
                                                                                          1795 heap_increment
                                                                                            1795 heap_assign_page
                                                                                              1795 rb_aligned_malloc
                                                                                                1795 posix_memalign
                                                                                                  1795 malloc_zone_memalign
                                                                                                    1795 szone_memalign
                                                                                                      1795 szone_free
                                                                                                        1795 small_free_detach_region
                                                                                                          1795 small_free_detach_region
    1795 Thread_3603
      1795 timer_pthread_fn
        1795 poll$UNIX2003
          1795 poll$UNIX2003

Total number in stack (recursive counted multiple, when >=5):
        5       rb_vm_exec
        5       vm_call_cfunc_with_frame
        5       vm_exec_core
        5       vm_sendish

Sort by top of stack, same collapsed (when >= 5):
        poll$UNIX2003        1795
        small_free_detach_region        1795
```

**Comment by fhgwright** [comment]
Note that this PR is for `ruby27`, not `ruby30`, though they're similar enough that the same issues might apply.  Nevertheless, a ticket is a better place to discuss this.

See:
https://trac.macports.org/ticket/66908

**Comment by barracuda156** [comment]
`ruby27` 2.7.7 fails to build on 10.6 ppc now:
```
gmake[1]: *** [ext/configure-ext.mk:174: ext/syslog/exts.mk] Abort trap
gmake[1]: Leaving directory '/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_ruby27/ruby27/work/ruby-2.7.7'
gmake: *** [uncommon.mk:277: exts.mk] Error 2
gmake: *** Waiting for unfinished jobs....
making encs
gmake[1]: Entering directory '/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_ruby27/ruby27/work/ruby-2.7.7'
```

**Pull request merged**
