### PR TITLE
ImageMagick7: New port

### PR DESCRIPTION
**Pull request by Dave-Allured**
#### Description

New port for ImageMagick version 7.  This port is intended to coexist peacefully with the traditional ImageMagick version 6 on MacPorts.   Libraries, include files, and run commands should be non-conflicting, with some "minor exceptions" to be sorted out.  IM6 and IM6 dependencies are left untouched.

This is a work in progress.  It may be possible to merge now, but numerous checks and refinements are incomplete.  Comment on this PR.  Suggestions and pull requests are welcome.  Help wanted.  See below.

Previous discussion:  https://trac.macports.org/ticket/51310
Prior work and discussion:  PR https://github.com/macports/macports-ports/pull/16945

This initial IM7 portfile is an updated clone of the current IM6 portfile.  Acknowledgement and thanks for previous efforts by Ryan Schmidt, Joseph Sacco, Joost de Keijzer, and Steve Smith.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [x] security fix

###### Tested on

macOS 12.7.3 21H1015 x86_64
Xcode 14.2 / Command Line Tools 14.2.0

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [x] tested basic functionality of ONE binary file (convert sym link)?

### CODE REVIEW

**Comment by Dave-Allured** [comment]
**Task list and Help Wanted**

**High priority**
* Check for conflicts with IM6.
* Check for conflict with "magick-script".  Find resolution.
  * Previous discussion: https://trac.macports.org/ticket/51310#comment:77

**Low priority**
* Try `sudo port test`.
* Test builds and binaries on various OS versions.  Report results here.
* Add dependants and test them.
* Review, reconstruct and re-test the port dependencies.
* Locate and remove transitive dependencies.
* Check license.
* Check configure args.
* Check variants.
* Check and fix livecheck.

**Comment by diekhans** [comment]
The below install conflicts remain.  Additionally, the imagemagic7 install is missing the command compatibility symlinks for the v6 names seen in a standard install.  This will create more end-user incompatibility issues.


```
/opt/local/bin/Magick++-config
/opt/local/bin/MagickCore-config
/opt/local/bin/MagickWand-config
/opt/local/lib/pkgconfig/ImageMagick.pc
/opt/local/lib/pkgconfig/Magick++.pc
/opt/local/lib/pkgconfig/MagickCore.pc
/opt/local/lib/pkgconfig/MagickWand.pc
/opt/local/share/man/man1/ImageMagick.1.gz
/opt/local/share/man/man1/Magick++-config.1.gz
/opt/local/share/man/man1/MagickCore-config.1.gz
/opt/local/share/man/man1/MagickWand-config.1.gz
/opt/local/share/man/man1/animate.1.gz
/opt/local/share/man/man1/compare.1.gz
/opt/local/share/man/man1/composite.1.gz
/opt/local/share/man/man1/conjure.1.gz
/opt/local/share/man/man1/convert.1.gz
/opt/local/share/man/man1/display.1.gz
/opt/local/share/man/man1/identify.1.gz
/opt/local/share/man/man1/import.1.gz
/opt/local/share/man/man1/mogrify.1.gz
/opt/local/share/man/man1/montage.1.gz
/opt/local/share/man/man1/stream.1.gz
```

**Comment by Dave-Allured** [comment]
@diekhans, thank you for checking conflicts.  I believe that the man page conflicts can be resolved simply by `port activate`.  The others are config issues which I do not think will be difficult to solve.  I will look into that.  Suggestions are welcome.

**Comment by diekhans** [comment]
Even if it is force to install, this seems to leave lots of
dependent ports unable to function.

Given the comments in the ticket, plus the commit rules, I don't
see how this approach will make it in.  Something similar to
what HomeBrew did seems smoother, if taking more elapses time.
Plus it make it easy for others to help.

1) Create a second ImageMagick 6 port that installs in hidden
   location.  Leave the existing v6 port alone for now.  These
   don't conflict.
2) Get PR merged.
3) Convert all dependencies to use hidden v6 port. PR one at a
   time.  Get people to help with this.  A large amount of work
   for one person, reasonable for ten working in parallel.
4) once all ports are updated to the hidden v6 port, convert the
   ImageMagick port to your V7 portfile and PR it.

No particular rush to convert the dependencies to V7, the port
maintainers need to decide.  That can be complex.

**Comment by Dave-Allured** [comment]
> ... Additionally, the imagemagic7 install is missing the command compatibility symlinks for the v6 names seen in a standard install. This will create more end-user incompatibility issues.

How widespread is demand for using the old IM6 commands with IM7?  The primary IM7 commands are well documented and completely different from IM6.

For full coexistence, the first cut of port imagemagick7 will need to omit those IM6 sym links.  If user enters an IM6 command, they will get the actual IM6 function.  This will simplify initial development.  IM7 users will have to use the intended IM7 commands.  Also, the user can easily add custom IM6 --> IM7 sym links manually in their own search path, if they have some critical need for replacement functionality, and they are unable to directly switch to IM7 commands.

Later we can investigate a switch mechanism that is supported by Macports.

**Comment by diekhans** [comment]
> How widespread is demand for using the old IM6 commands with IM7? The primary IM7 commands are well documented and completely different from IM6.

This seems hard to know.  With, Home Brew IM6 is not symlinked from its keg.  If one needs the IM6 commands, the PATH needs to be adjusted to pick this up.

I have no idea if a ''hidden" install of a package has ever been done with MacPorts or if there is a standard mechanism.
 
> Later we can investigate a switch mechanism that is supported by Macports.

it there is a hidden version for dependencies, then port select could be used for the end user.

**Comment by pmetzger** [comment]
@Dave-Allured How can we get this progressed?

**Comment by Dave-Allured** [comment]
@pmetzger  Sorry, I need to learn how to do some conflict resolutions, and my day job has been interfering.   ;-)

My first idea is to aim everything IM7 to install within $prefix/lib/imagemagick7.  Take proj8/proj9 etc. as a good example of this strategy.  Perhaps it does not need to be everything, because I think the libs and includes are already non-conflicting.  But then I would need to know how to manage those separately.

With nothing else, the user would then "select" the desired default version by changing $PATH etc.  There is probably a good Macports way to do that, but I do not know what that is.  (Look at gcc-select?)  That can wait.

I will take a look at this in the next few days, starting with whatever they are doing in proj.  Meanwhile, contributions would be welcome.

**Comment by Dave-Allured** [comment]
@pmetzger @diekhans  Okay, I copied the conflict avoidance used in proj8/proj9.  That seemed to go well.  Now everything IM7 should be installing to unique location ${prefix}/lib/imagemagick7.  Everything IM6 remains unchanged, within the standard ${prefix}.  Let me know what you think.

@diekhans  Please check this again for conflicts.  I did not do anything special about those sym links that you requested.  We can look at that later.  My priority is on getting the basic IM7 port going, without breaking anything IM6.

**Comment by pmetzger** [comment]
I think the general strategy is good. Do you manage to install both at this point without a problem?

**Comment by Dave-Allured** [comment]
> Do you manage to install both at this point without a problem?

Not yet.  My system requires everything installed from source, and dependency meson fails to install.  It would be helpful if someone else would test IM 6 & 7 together.

**Comment by Dave-Allured** [comment]
> dependency meson fails to install

Okay.  I got past the meson problem.  I now have IM6 and IM7 installed side by side.  I can use the `convert` executable from either version, and both work fine.

**Comment by pmetzger** [comment]
@Dave-Allured Okay, so what remains before we can merge this?

**Comment by Dave-Allured** [comment]
@pmetzger, I think this is ready to go.  There are no red or yellow flags from my installation and quick test of the IM7 `convert` command (sym linked).  All conflicts with IM6 seem to be avoided.  Let's release so that user base can assist with testing.

See secondary checklist above.  Dependencies should be minimized, but that can be done later.

**Comment by Dave-Allured** [comment]
@pmetzger, can you squash commits for me, then merge?  I am not up to speed yet on using git.

**Comment by diekhans** [comment]
Nice progress

Why change the case of the port name (ImageMagick vs
imagemagick7)? This seems to add no value at the cost of
annoying the user.

Do all of the port dependent on ImageMagick still compile when
both V6 and V7 ports are installed?

Sorry, don't have time to test right now...

**Comment by Dave-Allured** [comment]
> Why change the case of the port name (ImageMagick vs
imagemagick7)? This seems to add no value at the cost of
annoying the user.

Personal taste.  I dislike CamelCase.  Since you brought it up, I will gladly switch back to CamelCase if you want.  Okay?

> Do all of the port dependent on ImageMagick still compile when
both V6 and V7 ports are installed?

Did not test.  I am fairly confident in the conflict avoidance.  I suggest merge this now, then deal with bug reports later.  I too do not have time to test.

**Comment by diekhans** [comment]
Dave Allured ***@***.***> writes:
> Personal taste.  I dislike CamelCase.  Since you brought it up, I will gladly switch back to CamelCase if you want.  Okay?

Yes, taste. If there wasn't the existing name, I don't think it
would matter.  Since there is, consistency is more important,
especially since the actual software is 


> > Do all of the port dependent on ImageMagick still compile when
> both V6 and V7 ports are installed?
> 
> Did not test.  I am fairly confident in the conflict avoidance.  I suggest merge this now, then deal with bug reports later.  I too do not have time to test.

If I was part of the MacPorts team, I wouldn't allow approve a
pull request unless it was demonstrated that the dependencies
didn't break under various combinations.  This could waste a lot
of people's time.

I might have more time in a week.

**Comment by Dave-Allured** [comment]
Okay.  The new port name is now changed to ImageMagick7.

> If I was part of the MacPorts team, I wouldn't allow approve a
pull request unless it was demonstrated that the dependencies
didn't break under various combinations.  This could waste a lot
of people's time.

I think you meant to say "dependants".  Testing dependants is not a normal requirement for Macports pull requests.  While an ideal goal, that is difficult to achieve, especially in the mostly volunteer context of MacPorts.  I look forward to new port testing and feedback from the user base.

@pmetzger unless there are new requests, then I think this is ready for merge.  Please squash commits.  Discard all except the last two:  create directory, and new portfile.  Thank you.

**Pull request merged**
