### PR TITLE
netatalk: update to 2.2.8, fix the broken port

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

`netatalk` is broken across the board now. Hopefully this PR fixes it finally.

Note: there is a newer branch of `netatalk`, but it rather be made into a separate port. `netatalk` 2.x is still maintained with upstream, and 2.2.8 is its recent release.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Now it fails strangely:
```
Undefined symbols for architecture x86_64:
    "_append", referenced from:
        _noauth_printer in uams_guest.o
    "_make_log_entry", referenced from:
        _noauth_login in uams_guest.o
        _noauth_printer in uams_guest.o
    "_type_configs", referenced from:
        _noauth_login in uams_guest.o
        _noauth_printer in uams_guest.o
    "_uam_afpserver_option", referenced from:
        _noauth_login in uams_guest.o
    "_uam_register", referenced from:
        _uam_setup in uams_guest.o
    "_uam_unregister", referenced from:
        _uam_cleanup in uams_guest.o
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Can’t see what is wrong specifically with this file.

**Comment by rdmark** [comment]
FWIW I'm the author of the `netatalk 2.x` fork and I plan to eventually deprecate it in favor of 2.2 proper (which I'm now a maintainer of as well.) The only thing 2.x has going for it right now is some code cleanup and aggressive deprecation of less useful features.

**Comment by rdmark** [comment]
FWIW there is a 2.2.9 release available now, and I plan to tag 2.2.10 within a month or so.

**Comment by barracuda156** [comment]
> FWIW there is a 2.2.9 release available now, and I plan to tag 2.2.10 within a month or so.

@rdmark Thank you! I will update this PR soon to 2.2.9, hopefully it builds with clangs.

Should I restore that server-dropping commit for older systems though?

**Comment by rdmark** [comment]
Do you mean the MACOSX_SERVER conditionals that we removed in the development branch yesterday?

**Comment by reneeotten** [comment]
@barracuda156 version 2.2.10 was released; can this PR be updated and pushed towards completion?

**Comment by barracuda156** [comment]
> @barracuda156 version 2.2.10 was released; can this PR be updated and pushed towards completion?

@reneeotten Yes, it should be done. Perhaps not today itself, but I will find time for it shortly. Thank you for reminding.

**Comment by rdmark** [comment]
> > FWIW there is a 2.2.9 release available now, and I plan to tag 2.2.10 within a month or so.
> 
> @rdmark Thank you! I will update this PR soon to 2.2.9, hopefully it builds with clangs.

Making the code compile cleanly with clang on macOS was one of the goals of the release. We also have a CI job running on Github that build and tests on macOS Ventura every PR, so it *should* work.

Do make note of this PR however, where we did major cleanup of the traditional `MACOX_SERVER` compatibility macros to make it work better on modern macOS via the `__APPLE__` macro and other autoconf checks. This will definitely have impact if you're trying to build for ancient OSX versions.

**Comment by barracuda156** [comment]
> Making the code compile cleanly with clang on macOS was one of the goals of the release. We also have a CI job running on Github that build and tests on macOS Ventura every PR, so it _should_ work.
> 
> Do make note of this PR however, where we did major cleanup of the traditional `MACOSX_SERVER` compatibility macros to make it work better on modern macOS via the `__APPLE__` macro and other autoconf checks. This will definitely have impact if you're trying to build for ancient OSX versions.

@rdmark Thank you. I will see if it still builds locally for me; if not, then I will either need to revert that change (conditionally, of course), or if that does not work either, set an earlier version for older OS.

**Comment by reneeotten** [comment]
@barracuda156 please fix this PR or close it.

**Comment by barracuda156** [comment]
@reneeotten Yes, will do today. 2.2.10 builds fine on Sonoma.

**Pull request merged**
