### PR TITLE
The versions of babl-devel and babl are the same, and also gegl-devel...

### PR DESCRIPTION
**Pull request by nakatamaho**
... and gegl are the same.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
@nakatamaho at the moment that is indeed true, but there is no reason why that would remain like this in the future. I'm pretty sure we don't want to make this change.... if anything they could perhaps be specified as a `path` dependency so that both ports devel/non-devel ports could satisfy the dependency - why do you think this is useful?

**Comment by reneeotten** [comment]
@macportsbot retry

**Comment by mascguy** [comment]
Agreed, this is not a change we need/want to make.

**Comment by mascguy** [comment]
That being said, I'm open to switching these to a path-style dependency.

**Comment by mascguy** [comment]
Port updated to use path-style deps for `babl` and `gegl`:

https://github.com/macports/macports-ports/commit/9de25789d4b24beddf0a9abb02084f2df7d580b7

**Pull request closed without merging**
