### PR TITLE
any: new port in devel

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

New port: https://github.com/thelink2012/any

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

Test passes in Rosetta:
```
--->  Testing any
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_any/any/work/build" && /usr/bin/make test 
Running tests...
/opt/local/bin/ctest --force-new-ctest-process 
Test project /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_any/any/work/build
    Start 1: test_any
1/1 Test #1: test_any .........................   Passed    0.03 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.05 sec
```

### CODE REVIEW

**Comment by barracuda156** [comment]
Clang build fails on:
```
In file included from /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_any/any/work/any-bfc77f2e4be6e9a093dd645ef3f1aa30620c9205/test_shared_lib.hpp:3:
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_any/any/work/any-bfc77f2e4be6e9a093dd645ef3f1aa30620c9205/any.hpp:279:13: error: no matching 'operator new' function for non-allocating placement new expression; include <new>
              new (&dest.stack) T(reinterpret_cast<const T&>(src.stack));
              ^~~
```

**Comment by harens** [comment]
Saw you submitted the patch upstream and it was merged: https://github.com/thelink2012/any/pull/20. Nice job 👍

Might be worth updating the commit hash and removing the patch.

**Comment by barracuda156** [comment]
> Saw you submitted the patch upstream and it was merged: [thelink2012/any#20](https://github.com/thelink2012/any/pull/20). Nice job 👍
> 
> Might be worth updating the commit hash and removing the patch.

Will do tomorrow! (Night now, off from machines with git and ports.)

**Comment by barracuda156** [comment]
@harens Done!

**Review by harens — APPROVED** [review]
Thanks @barracuda156!

**Pull request merged**
