### PR TITLE
vms-empire: update to 1.17

### PR DESCRIPTION
**Pull request by mohd-akram**
###### Tested on
macOS 14.4.1 23E224 x86_64
Xcode 15.3 15E204a

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
Does it make sense to shift this project to using the `gitlab` portgroup against its Gitlab project ( https://gitlab.com/esr/vms-empire ) ?

**Comment by mohd-akram** [comment]
I haven't tried building from git and the project doesn't use GitLab releases to host the tarball AFAICT. At minimum, it will require some extra dependencies to build the man page since that's pre-built in the tarball, IMO not worth it.

**Comment by herbygillot** [comment]
Got it. Also seeing `use_configure no` present, this could also be set to use the `makefile` portgroup.

**Comment by mohd-akram** [comment]
@herbygillot Good point, updated.

**Comment by herbygillot** [comment]
Thanks @mohd-akram

**Pull request merged**
