### PR TITLE
opencv3: new port to replace opencv, with opencv4-style isolation

### PR DESCRIPTION
**Pull request by mascguy**
#### Description

This is a critical step supporting reinstatement of OpenCV 2 port, and upcoming reconciliation of all OpenCV-related ports into subports.

This is phase two, of a five-phase rollout:
1. Add variants missed during opencv/opencv4 reconciliation (opencv +openmp, opencv4 +openni). [Open PR 9777](https://github.com/macports/macports-ports/pull/9777)
1. Add new port opencv3, segregated like opencv4. Also include initial changes, supporting later conversion to subport.
1. Update ports presently dependent upon opencv, to use opencv3. And update port opencv to be a stub port, with `replaced_by opencv3`, etc.
1. Add new port opencv2, using same segregation strategy.
1. Reconcile all three into single opencv port, with three subports. This step may be combined with previous.

Details provided in tickets:
- [opencv/opencv4: eliminate portfile duplication, via subport](https://trac.macports.org/ticket/62011)
- [OpenCV 2.x (please re-instate or provide a new opencv2 port)](https://trac.macports.org/ticket/49670)

###### Type(s)
- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.8.5 12F2560
Xcode 5.1.1 5B1008

macOS 10.9.5 13F1911
Xcode 6.2 6C131e

macOS 10.10.5 14F2511
Xcode 6.4 6E35b

macOS 10.11.6 15G22010
Xcode 7.3.1 7D1014

macOS 10.12.6 16G2136
Xcode 9.2 9C40b

macOS 10.13.6 17G14019
Xcode 10.1 10B61

macOS 10.14.6 18G103
Xcode 11.3.1 11C505

macOS 10.15.6 19G2021
Xcode 12.0 12A7209

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mascguy — COMMENTED** [review]
Note to Reviewers:

This port is 98% the same as our existing `opencv` port. The differences involve:
* Additional CMake arguments, to enforce segregation: Headers and Libs pushed down a level, into `${prefix}/include/opencv3` and `${prefix}/lib/opencv3`, respectively; everything else hosted under `${prefix}/libexec/opencv3/...`.
* Changes to eliminate copy-paste of port name, replaced with `${subport}`.
* Two additional procs from port `opencv4`, supporting cleanup, as well as soft-linking binaries via prefix `${subport}_`.

Nonetheless, for thoroughness, testing involved several install variations:
* Stock install, with no variants selected.
* Fully-loaded installation, with the following variants selected: `+eigen +gdal +java +nonfree +opencl +openni +python37 +qt5 +tbb +vtk`

**Comment by mf2k** [comment]
Is the buildbot failures in the Portfile or in the buildbot itself?

**Comment by mascguy** [comment]
> Are the buildbot failures in the Portfile or in the buildbot itself?

It's definitely not an issue with the portfile:

```
$ port lint opencv3
--->  Verifying Portfile for opencv3
--->  0 errors and 0 warnings found.
```

I've also installed (and re-installed) numerous times, across all of the macOS releases in the PR description.

Is the buildbot choking, because this is a new port...?

**Comment by mascguy** [comment]
I did a git force-push a few minutes ago, and this time around, the CI buildbots aren't chocking within seconds. So perhaps there was some issue last night?

**Comment by mascguy** [comment]
@mf2k Last night was apparently a fluke, as it looks fine now...

**Comment by mascguy** [comment]
Thanks Frank!

**Pull request merged**
