### PR TITLE
db-browser-for-sqlite: submission

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by amake** [comment]
I'm confused why this was added when we have `sqlitebrowser`, which appears to be the same thing. It even uses the same distfile.

**Comment by cjones051073** [comment]
well clearly it was just a mistake...

**Comment by amake** [comment]
Was it? This portfile is significantly less complicated, so I wasn’t sure if there was maybe a reason to add it separately. 

Should this one be removed? If not, the two ports should at least be marked as conflicting.

**Comment by cjones051073** [comment]
I think this one should just be removed, and marked as 'replaced' by the original one.

**Comment by i0ntempest** [comment]
I didn’t know that one was already in there... but we use different build systems and my version is Darwin only. Plus I don’t really like sqlitebrowser makes the app bundle manually when build can generate it for you. I might try to merge the two if possible

**Comment by cjones051073** [comment]
By all means submit a PR to improve the original one, if you think there are things there that can be done. Having both ports though clearly makes no sense, so as this one is the latest, it should go and the original one remain. I'll submit the update obsoleting this one.

**Pull request merged**
