### PR TITLE
saga: update to 9.3.0 and new py*-pysaga subports

### PR DESCRIPTION
**Pull request by nilason**
#### Description

Update `saga` to version 9.3.0 and add new `py*-pysaga` subports, which replaces former `saga` Python variants.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.2.1 23C71 arm64
Xcode 15.1 15C65

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by nilason** [comment]
Note: there is a stub [`py-saga`](https://ports.macports.org/port/py-saga/) for [`py27-saga`](https://ports.macports.org/port/py27-saga/), which is a port not updated since 2015. On PyPi this module is named [radical.saga](https://pypi.org/project/radical.saga/) from https://radical-cybertools.github.io/saga-python/.

The new `py3xx-saga` ports this PR adds will not directly conflict with the existing ones, but may lead to confusion.
The question is whether to keep the existing py-saga and py27-saga at all, or delete/make them obsolete ?
Notifying maintainer: @petrrr

**Comment by pmetzger** [comment]
I think for the python stuff I'd also like @reneeotten's opinion.

**Comment by nilason** [comment]
Alternative name for the new python subports for SAGA may be `py-pysaga`. The module name is actually PySAGA, as in:
```py
import PySAGA
```

**Comment by reneeotten** [comment]
> Alternative name for the new python subports for SAGA may be `py-pysaga`. The module name is actually PySAGA, as in:
> 
> ```python
> import PySAGA
> ```

Ideally Python packages should be named after how they appear on PyPI, without any capitalization; in other words `py-<pypi-name>`. I am not sure though whether this is found on PyPI or not as a separate package...

**Comment by nilason** [comment]
> > Alternative name for the new python subports for SAGA may be `py-pysaga`. The module name is actually PySAGA, as in:
> > ```python
> > import PySAGA
> > ```
> 
> Ideally Python packages should be named after how they appear on PyPI, without any capitalization; in other words `py-<pypi-name>`. I am not sure though whether this is found on PyPI or not as a separate package...

There is no such package at PyPI, this is supposed to be installed together with SAGA to the default Python (which e.g. Debian and FreeBSD do). Given this another thought, I'd say I prefer `py-pysaga`.

**Comment by reneeotten** [comment]
that sounds good @nilason. Once you have updated it I will merge

**Comment by nilason** [comment]
> that sounds good @nilason. Once you have updated it I will merge

Ok, updated to py-pysaga.

**Pull request merged**
