### PR TITLE
py-igraph: update to 0.11.8

### PR DESCRIPTION
**Pull request by szhorvat**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 14.7 23H124 arm64
Xcode 16.1 16B40

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by szhorvat** [comment]
I am aware that the test dependencies for the Python 3.13 variant are not yet in place, but I do not have the time to special-case this, and then later come back to remove that special-casing, as we did last time. The variant works fine, and has all library dependencies present.  [We test with Python 3.13 during development.](https://github.com/igraph/python-igraph/) Missing test dependencies are already extremely widespread in MacPorts anyway (as revealed by the analysis https://trac.macports.org/ticket/71182).

I believe there is more value in providing this variant early, however, if this is not acceptable, I will remove it.

**Review by nerdling — APPROVED** [review]
Not a huge fan of having broken ports but I agree this would need done eventually anyways.

**Comment by szhorvat** [comment]
Just to clarify: It's not a broken port. It can be installed, and it has full functionality. Only `port test` is broken.

**Comment by reneeotten** [comment]
> Missing test dependencies are already extremely widespread in MacPorts anyway (as revealed by the analysis https://trac.macports.org/ticket/71182).

Let's not use a Trac ticket that you open yourself to show issue with dependencies as a justification to do the exact same thing purposefully yourself ;)

Having said that, the `py313-scipy` is available already and I will add the `py313-matplotlib` shortly; given that you say you test upstream Python 3.13 already one can assume that the other two missing dependencies will work with Python 3.13 and thus getting them added soon-ish is doable. So I am fine with merging this now.

**Pull request merged**
