### PR TITLE
apache-arrow: Update to version 12.0.0

### PR DESCRIPTION
**Pull request by essandess**
# apache-arrow: Update to version 12.0.0

Note: I am submitting this PR from a machine on which building neither 11.0.0 nor 12.0.0 works. However, I see on other machines (configured exactly like this one) that these builds do work. So I am submitting this and will cross fingers for the CI.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.3.1 22E772610a x86_64
Xcode 14.3 14E222b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@essandess It is perhaps again failing on some Python dependencies, like in my PR with fixes for Arrow: https://github.com/macports/macports-ports/pull/18244

**Comment by reneeotten** [comment]
Error appears to be:

  Error: Failed to destroot py310-pyarrow: no files matched glob pattern "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_apache-arrow/py310-pyarrow/work/destroot/opt/local/bin/*"

**Comment by mascguy** [comment]
In order to merge this, we'll need to drop support for Python 3.7 and 3.8. That's necessary because `py-tensorflow` no longer supports those versions.

Which also means dropping 3.7 and 3.8 for the following dependents:

```
py-apache-beam
py-datasets
py-kraken
py-magenta
py-sentence-transformers
py-tensorflow-data-validation
py-tensorflow-transform
py-tfx-bsl
py-transformers
```

**Comment by barracuda156** [comment]
@mascguy Once this is merged, I will rebase my PR with fix-ups for `apache-arrow`.

**Comment by mascguy** [comment]
> @mascguy Once this is merged, I will rebase my PR with fix-ups for `apache-arrow`.

Do you mean another PR?

**Comment by barracuda156** [comment]
> > @mascguy Once this is merged, I will rebase my PR with fix-ups for `apache-arrow`.
> 
> Which other PR are you referring to...?

https://github.com/macports/macports-ports/pull/18244

**Review by mascguy — APPROVED** [review]
CI has no chance of completing successfully, but looks good locally. Merging.

**Comment by barracuda156** [comment]
> CI has no chance of completing successfully, but looks good locally. Merging.

Great, I will port my fix-ups then.

**Pull request merged**
