### PR TITLE
retdec-devel: update to 20220920, fix build on 10.6

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 10K549 x86_64
Xcode 3.2.6 10M2518

macOS 12.6 21G115 x86_64
Xcode 14.0 14A309

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
I've tried to test it on my 10.6 and can't because I've been blocked by https://trac.macports.org/ticket/65861

@mascguy as far as I recall you have access to 10.6; if you can test it I'll be appricieted.

**Comment by mascguy** [comment]
> I've tried to test it on my 10.6 and can't because I've been blocked by https://trac.macports.org/ticket/65861
> 
> @mascguy as far as I recall you have access to 10.6; if you can test it I'll be appreciated.

See my workaround in the ticket. It will build that way.

**Comment by catap** [comment]
Reported to upstream issue with 10.6: https://github.com/avast/retdec/issues/1114

It is clear an issue with very tricky build process.

**Comment by catap** [comment]
@mascguy why have you marked it as draft?

**Comment by mascguy** [comment]
> @mascguy why have you marked it as a draft?

Because you've made numerous pushes, suggesting it's not done.

So let's keep these as draft, until you're completely done making changes. Okay?  ;-)

**Comment by catap** [comment]
@mascguy the last push was to upgrade revision of dev port. retdec is rearly updated, and when I've waited to Review it just upgraded one more time with trivial fix that I've noticied last night ;)

**Comment by mascguy** [comment]
> @mascguy the last push was to upgrade revision of dev port. retdec is rearly updated, and when I've waited to Review it just upgraded one more time with trivial fix that I've noticied last night ;)

Okay. So this is done then?

**Comment by catap** [comment]
Yes, it is done.

**Review by mascguy — APPROVED** [review]

**Comment by catap** [comment]
@macportsbot and buildbot for 10.6 is failed because `graphviz` aren't available :)

**Comment by mascguy** [comment]
> @macportsbot and buildbot for 10.6 is failed because `graphviz` aren't available :)

That's a new issue, tracked by: [65868 - graphviz: build failure on 10.6 buildbot: PSNormalizer.framework: can't open hostfont cache lock file](https://trac.macports.org/ticket/65868)

Feel free to suggest a fix!  ;-)

**Pull request merged**
