### PR TITLE
diffutils: update maintainer

### PR DESCRIPTION
**Pull request by schaiba**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ra1nb0w** [comment]
I don't see any previous contribution from you therefore you should not be the maintainer.
Said that, you need to add `openmaintainer` and use the tag `diffutils:` in the commit.
Read https://guide.macports.org/#project.contributing

**Comment by ra1nb0w** [comment]
Why do you want to be the maintainer since you haven't pushed any commit in the past?

**Comment by schaiba** [comment]
> Why do you want to be the maintainer since you haven't pushed any commit in the past?

I maintain diffutils in FreeBSD as well, so I thought I might be able to help here as well.

**Comment by ra1nb0w** [comment]
Please, merge the two commits in one using the prefix `diffutils:` in the header. See the other commits in macports-ports and the url that I post.
Personally, before changing the maintainer I would like to see a few contributions. But listen what others developers have to say.

**Comment by kencu** [comment]
that didn't work out too well.

**Comment by reneeotten** [comment]
@ra1nb0w this doesn't seem to be the best way to welcome newcomers with an interest to contribute...

@schaiba open a Trac ticket about this and I suggested him to submit a PR instead as that is the way we would like people to contribute their updates/changes. I agree that changing just the maintainer line without having contributed before to MacPorts might seem a little awkward, but I would just view it as showing interest to go and maintain this port and would be perfectly fine with that.

**Pull request closed without merging**
