### PR TITLE
gcc{12,-devel}: disable stdlib_flag on PPC by default

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
Cc: @barracuda156

**Comment by barracuda156** [comment]
@catap Awesome.

**Comment by catap** [comment]
@barracuda156 I prefer to use unavailable until someone can make public available instruction how to build it and use it :)

**Comment by barracuda156** [comment]
@catap I am not gonna argue over a comment wording, w/e LOL
Disabling the flag for PPC is what we need, for the time-being.

**Comment by barracuda156** [comment]
@catap Any idea why checks fail?

**Comment by catap** [comment]
@barracuda156 github actions had a time limit for 6 hours. My guess that it isn't enough to build 4 gcc: gcc12, libgcc12, gcc-devel and libgcc-devel.

**Comment by catap** [comment]
@mascguy may I ask you to review this one?

It won't touch buildbot at all :)

**Comment by barracuda156** [comment]
@catap @mascguy Maybe also correct the triple, in one go? It should not be `${build_arch}-apple-darwin${os.major}` for all cases, that gets PPC wrong: archs are `ppc` and `ppc64`, but triple should be `powerpc*-*`.

(Can be done in a different PR, but again, buildbots.)

**Comment by catap** [comment]
@barracuda156 if you haven't touch revision and artifacts already was built => buildbots are ignoring it :)

**Comment by barracuda156** [comment]
@catap Ok cool, then I do it myself separately.

**Comment by mascguy** [comment]
So are additional changes needed for this PR, or is it ready to merge?

**Review by mascguy — APPROVED** [review]

**Pull request merged**
