### PR TITLE
py-requests.oauthlib (and dependencies): add py312 subports, remove py37 subports

### PR DESCRIPTION
**Pull request by markmentovai**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.2.1 23C71 arm64
Xcode 15.2 15C500b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by lpsinger — APPROVED** [review]

**Comment by Schamschula** [comment]
The title includes add py312 subport, but in the case of `py-twython` the title should be: remove py37 subport.

I'm fine with the proposed change.

However, I really should delete the port as it no longer has any functionality.

**Comment by markmentovai** [comment]
@Schamschula, that commit’s title (https://github.com/macports/macports-ports/pull/22205/commits/c18b14d2a3d9788dceab5e52534dc5b577e63cd7) is “py-twython: remove py37 subport”.

Did you mean that you wanted the pull request’s title to also say something about py37?

**Comment by catap** [comment]
@markmentovai just to be double sure: how you checked that no one depends on removed py37 subports, like ` port echo depends:py37-requests-oauthlib`?

If yes, and as you stated you've run tests => I'm find with this as well.

**Comment by Schamschula** [comment]
> @Schamschula, that commit’s title ([c18b14d](https://github.com/macports/macports-ports/commit/c18b14d2a3d9788dceab5e52534dc5b577e63cd7)) is “py-twython: remove py37 subport”.
> 
> Did you mean that you wanted the pull request’s title to also say something about py37?

Yes. As you are removing py37 subports.

I agree with @catap - make sure to run `port echo rdepends::py37-requests-oauthlib` to get the recursive dependencies on py37.

**Comment by markmentovai** [comment]
https://github.com/macports/macports-ports/pull/22205#issuecomment-1894082299:
> > @Schamschula, that commit’s title ([c18b14d](https://github.com/macports/macports-ports/commit/c18b14d2a3d9788dceab5e52534dc5b577e63cd7)) is “py-twython: remove py37 subport”.
> > Did you mean that you wanted the pull request’s title to also say something about py37?
> 
> Yes. As you are removing py37 subports.

Done.

> I agree with @catap - make sure to run `port echo rdepends::py37-requests-oauthlib` to get the recursive dependencies on py37.

https://github.com/macports/macports-ports/pull/22205#issuecomment-1894051741:
> @markmentovai just to be double sure: how you checked that no one depends on removed py37 subports, like  port echo depends:py37-requests-oauthlib?

Yes:

```
mark@arm-and-hammer zsh% port echo rdepends:py37-jwt      
py37-pygithub                   
py37-twilio                     
mark@arm-and-hammer zsh% port echo rdepends:py37-oauthlib            
mark@arm-and-hammer zsh% port echo rdepends:py37-requests-oauthlib
py-tweepy                       
py37-tweepy                     
py37-twython                    
```

**Review by catap — APPROVED** [review]
LGTM as soon as CI is passed!

**Comment by markmentovai** [comment]
[Passed now.](https://github.com/macports/macports-ports/actions/runs/7546267391/)

**Pull request merged**
