### PR TITLE
lowdown: new port

### PR DESCRIPTION
**Pull request by janstary**
lowdown translates markdown to either HTML or roff

Works on 10.13.2, fails on 10.5.8 and 10.6.8 which do not have `strndup()`.
Does anyone now since when does MacOS have `strndup()` please?

### CODE REVIEW

**Comment by kencu** [comment]
strndup is in 10.7+. 

`PortGroup snowleopard_fixes 1.0` replaces it for 10.6 and lower, however.

**Comment by janstary** [comment]
Updated, thanks.

Should these portgroups be documented in portgroup(7)?
Should they be mentioned in the Guide?

**Comment by pmetzger** [comment]
I suspect Travis is never going to terminate here, the CI system is now 3,000 builds behind. I'm simply going to merge.

BTW, I note that your indentation of the "version" and "license" is weird.

**Comment by janstary** [comment]
Thanks for merging.

(That's github's identation.)

**Comment by mojca** [comment]
No, that's usually a symptom of misuse of tabs.

**Comment by janstary** [comment]
(You mean, github's misuse of tabs)

**Comment by kencu** [comment]
There should be no tabs in your Portfile. Convert them to spaces (or we will).

**Comment by pmetzger** [comment]
Agreed. Tabstops aren't standard (or at least not any longer) so it isn't safe to use them.

**Comment by janstary** [comment]
What would you say are the three most serious safety issues when using tabs?

**Comment by kencu** [comment]
paper cuts, the potential for ocular gyrations, and most importantly, their clear contributions to global warming, which of course threantens not only us, but our children as well

**Comment by pmetzger** [comment]
It also can lead to birth defects in laboratory animals.

More seriously, having stuff fail to line up when different tools are used isn't exceptionally harmful but it is really annoying.

**Comment by cjones051073** [comment]
Most software projects will have coding conventions that contributors are expected to adhere to. This is very common. You don’t have to like those conventions, you just have to stick to them. MacPorts is the same, and not using tabs is just one of them.

**Pull request merged**
