### PR TITLE
py-awscli: update to 1.14.24

### PR DESCRIPTION
**Pull request by emcrisostomo**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix
- [x] update

###### Tested on

macOS 10.13.2 17C205
Xcode 9.2 9C40b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by emcrisostomo** [comment]
ping

**Comment by pmetzger** [comment]
So these are all Open Maintainer. Travis has gone south for the moment. I'll do the merge if you will verify that these build for you.

**Comment by emcrisostomo** [comment]
Hi @pmetzger,

Yes, I'm actually using them since before creating the PR:

```% aws --version
aws-cli/1.14.24 Python/2.7.14 Darwin/17.3.0 botocore/1.8.28```

**Comment by pmetzger** [comment]
Merged, and thank you.

**Comment by emcrisostomo** [comment]
Thanks @pmetzger

**Pull request merged**
