### PR TITLE
py-cmake: Submission

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by reneeotten — CHANGES_REQUESTED** [review]
why would we have another port to install `cmake` - what's the reason that one cannot use the normal `cmake` port?

**Comment by essandess** [comment]
> why would we have another port to install `cmake` - what's the reason that one cannot use the normal `cmake` port?

Because the latest version of `py-onnx` in #24097 has this module as a required dependency. Without this dependency, this `py-onnx` build error is thrown:

```sh
:info:build writing manifest file 'onnx.egg-info/SOURCES.txt'
:info:build ERROR Missing dependencies:
:info:build     cmake
:info:build Command failed:  cd "/opt/local/var/macports/build/_opt_local_ports_python_py-onnx/py312-onnx/work/onnx-1.16.1" && /opt/local/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12 -m build --no-isolation --wheel --outdir /opt/local/var/macports/build/_opt_local_ports_python_py-onnx/py312-onnx/work 
:info:build Exit code: 1
```

**Comment by essandess** [comment]
@reneeotten The objective of this PR is to get the latest version of PyTorch in the latest Python version ASAP in #24098.

If there’s a better way to do that through the `py-onnx` dependency #24097, then that’s fine with me.

I’m just trying to get an up-t to o-date PyTorch merged.

**Comment by essandess** [comment]
Per https://github.com/macports/macports-ports/pull/24097#discussion_r1614732457, we can close this submission without merging.

**Pull request closed without merging**
