### PR TITLE
bitwarden-cli: update to 2024.2.1

### PR DESCRIPTION
**Pull request by contextnerror**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G9323 x86_64
Command Line Tools 10.3.0.0.1.1562985497

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by MarcelBochtler** [comment]
Hi @contextnerror, thanks for the change.
I installed this updated version using your changes and I'm getting this error, when using `bw`:

```sh
❯ bw --version
/opt/local/lib/node_modules/@bitwarden/cli/build/bw.js:18708
        const toStore = structuredClone(obj);
                        ^

ReferenceError: structuredClone is not defined
    at MemoryStorageService.save (/opt/local/lib/node_modules/@bitwarden/cli/build/bw.js:18708:25)
    at StateService.<anonymous> (/opt/local/lib/node_modules/@bitwarden/cli/build/bw.js:24046:45)
    at Generator.next (<anonymous>)
    at /opt/local/lib/node_modules/@bitwarden/cli/build/bw.js:21988:71
    at new Promise (<anonymous>)
    at state_service_awaiter (/opt/local/lib/node_modules/@bitwarden/cli/build/bw.js:21984:12)
    at StateService.setState (/opt/local/lib/node_modules/@bitwarden/cli/build/bw.js:24045:16)
    at StateService.<anonymous> (/opt/local/lib/node_modules/@bitwarden/cli/build/bw.js:22071:32)
    at Generator.next (<anonymous>)
    at /opt/local/lib/node_modules/@bitwarden/cli/build/bw.js:21988:71
```

Any idea what could case this? This is the system I'm using:
```
macOS 14.3.1 23D60 arm64
Xcode 15.3 15E204a
```

**Comment by ryandesign** [comment]
Is this working now?

**Comment by ryandesign** [comment]
> The only hangup is that the port seems to accept older versions of node as a substitute for the nodejs20 called for in the dependencies. I can't figure out how to make it stop doing that.

That seems to be how the npm portgroup is designed.

The fix would be to resolve https://trac.macports.org/ticket/63035.

**Comment by reneeotten** [comment]
Feel free to reopen this once the PortGroup is fixed or something else is done to make sure things don't break.

**Pull request closed without merging**
