### PR TITLE
Nethack361

### PR DESCRIPTION
**Pull request by jflude**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.3 18D109
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jflude** [comment]
(haven't heard yet from the maintainer, so unsure what to put for maintainer with the new version...)

**Comment by mf2k** [comment]
Why are you creating an old nethack port? Let's just update the nethack port to the latest version.

**Comment by jflude** [comment]
Games sometimes last a long time (ie. weeks or months), and the save files (and "bones" files) from the old version are not compatible with the new.  So I think it's a good idea to keep the old version available for a while (for example, suppose someone gets a new machine and reinstalls MacPorts, should they therefore become unable to continue playing their saved game?)

**Comment by mf2k** [comment]
If you need the old version, then you don't have to upgrade until your game is complete. There is no need to keep the old version around.

**Comment by jflude** [comment]
Except in the scenario I just described, where a long-lasting game is lost because the old version is no longer available on a new installation of MacPorts.  I think the situation is exactly as it is with a programming language, where old ports *are* kept - if a new port is incompatible with old files, it's nice for users to keep the old version available for a while, rather than render their data useless.  Is this not a question best answered by the maintainer, though?  I understand he is a NetHack aficionado, so perhaps he is the best to judge...?

**Comment by Nax** [comment]
NetHack has both a very long release cycle (3.4.3 was released in 2004, and 3.6.0 about two years ago), and breaking upgrades. There are plenty of people who continue playing 3.4.3, either as their only NetHack version or alongside 3.6.x.

I think we should seriously consider letting people install multiple versions of the game in parallel. Nobody plays pre-3.4.3 anymore, so we have to consider 3.4.3, 3.6.1 and maybe 3.6.0.

**Comment by mf2k** [comment]
@Nax: You are the maintainer, so it is your call. If you want to go the route of multiple versions, then simply make them a sub-port(s) of the existing nethack Portfile instead of creating a new Portfile.

**Comment by jflude** [comment]
I can modify the PR to create a sub-port that will allow parallel installation.

**Comment by jflude** [comment]
Superseded by new PR which includes suggested fixes: https://github.com/macports/macports-ports/pull/3774

**Pull request closed without merging**
