### PR TITLE
cdrtools: unbreak after pulseaudio update, fix universal flags for Leopard on powerpc

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

See commits.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
@RobK88 Why does the universal variant hardcode architectures? Why doesn't it use `${universal_archs}`?

**Comment by barracuda156** [comment]
@ryandesign I do not know, this is not my design. I just corrected a choice for PowerPC on Leopard to a more sensible one.

**Comment by pmetzger** [comment]
I'm going to merge this for now, but the question posed to @RobK88 stands I think.

**Comment by barracuda156** [comment]
@pmetzger I agree but that is a separate issue.

**Pull request merged**
