### PR TITLE
Various updates of python packages

### PR DESCRIPTION
**Pull request by mojca**
#### Description

Note that some tests fail.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.4 17E199
Xcode 9.3 9E145

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
1. Why didn't the automatic system tell us about the `lint` status of these? Sometimes we get reports in, sometimes we don't. It seems very mysterious to me.
2. Do you know why the CI system spat up so quickly?
3. For the tests you did that failed, were they failing before the update?
3. In terms of merging: the only port here with a maintainer is listed as openmaintainer and all you added to that one was 35 and 36. All the rest of these are nomaintainer. I would say that we can therefore merge these quite quickly once you yourself are comfortable.

**Comment by mojca** [comment]
I would be grateful if maintainer was willing to check compatibility with Python 3 slightly beyond my super basic tests and I realized that I forgot to check whether the new port might perhaps be `supported_archs none`.

**Comment by pmetzger** [comment]
You mean @stromnov for that one port?

**Comment by mojca** [comment]
I don't see any added value of detaching that trivial change to a separate PR. If he's willing to test, I would be happy as some dependencies have been updated as well. But there's absolutely no time-critical fix in this PR, so it can easily wait for three days if needed and opening another PR will not shorten your PR queue in any way. I leave it up to you to decide whether or not to wait.

I checked the contents of the port. It seems to contain juts `py` and `pyc` files. I don't know if pyc counts as noarch or not, but other port saying `noarch` have those files as well.

**Comment by pmetzger** [comment]
I'll be merging this in the next few hours. Thanks as always, @mojca!

**Pull request merged**
