### PR TITLE
ci: add new github macos-14 builders

### PR DESCRIPTION
**Pull request by markemer**
#### Description

Add the newly available macOS 14 builders to main.yml

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 14

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

### CODE REVIEW

**Comment by markemer** [comment]
I converted this to draft because a simple fix is doing this:

```
  macOS version: 14.2.1
  curl: (22) The requested URL returned error: 404
  IP address: 13.105.117.171
  curl: (22) The requested URL returned error: 404
  curl: (22) The requested URL returned error: 403
  Can reach private packages server: no
```

**Comment by markemer** [comment]
Ok, it appears this will depend on https://github.com/macports/macports-ci-files/blob/main/.github/workflows/main.yml being changed too - I'll put up a PR for that.

**Comment by pmetzger** [comment]
Do we want to keep MacOS 11 in the runners?

**Comment by markemer** [comment]
That's a good question. The buildbot has everything going back to the beginning of time, so it might be safer to ditch it.

**Comment by ryandesign** [comment]
The more systems we can test on in CI, the better, no?

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
It's better to keep all build machines while official support is ongoing. They use only GitHub infrastructure and don't require payment (unlike arm64 VMs - need them too, but it's quite an expensive piece of cake).

**Comment by ryandesign** [comment]
Oh: https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/

* the macos-14 runner is arm64
* the macos-11 runner is now deprecated and will be eliminated by June 2024

**Comment by ryandesign** [comment]
> ```
>   macOS version: 14.2.1
>   curl: (22) The requested URL returned error: 404
>   IP address: 13.105.117.171
>   curl: (22) The requested URL returned error: 404
>   curl: (22) The requested URL returned error: 403
>   Can reach private packages server: no
> ```

I need to update the list of allowed IP address ranges on the private server, and automate that while I'm at it.

**Comment by markemer** [comment]
Keeping in draft until it works - which I think is just waiting on IP changes?

**Comment by ryandesign** [comment]
> waiting on IP changes?

The new IP address ranges are already in use by the existing runners so fixing that needn't prevent this from being merged.

Until I fix the IP allow list on the private server, it'll just mean that the runners have to build any nondistributable ports from source, if they happen to be using one of those new IPs.

The reason why it's not a simple change is that I had been using a few allow rules for the IP addresses I had observed being in use before, but now that I want to use the official GitHub API for determining their IP addresses I see that there are over 3,500 IP address *ranges* used for Actions runners and I don't think it is designed to accommodate that many allow rules. Even if I limit it to the 450 or so IP address ranges that I suspect are the ones used for macOS runners, that's still a lot and I want to switch to a different method.

**Comment by markemer** [comment]
Oh, ok - so that's not the cause of the failure maybe then? I'll play around.

**Comment by markemer** [comment]
I figured it out - macports-ci-files doesn't have files for major number 23 - that's the 404s - but they're async so they threw me off.

**Comment by jmroot** [comment]
I was going to update the CI config next week, as per https://github.com/macports/macports-base/blob/master/portmgr/ReleaseProcess.md#use-of-new-features-in-portfiles

**Comment by markemer** [comment]
> I was going to update the CI config next week, as per https://github.com/macports/macports-base/blob/master/portmgr/ReleaseProcess.md#use-of-new-features-in-portfiles

This could wait - should just be ready to go then. I could also fix it for 2.9.0 major 23 but it doesn't seem like it's worth it.

**Pull request closed without merging**
