### PR TITLE
leveldb: expose memenv

### PR DESCRIPTION
**Pull request by catap**
#### Description

See: https://trac.macports.org/ticket/68132

###### Type(s)

- [x] bugfix

###### Tested on

macOS 12.6.8 21G725 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by nilason** [comment]
This works fine for qgis, but leveldb dependencies should be rev-bumped.

**Comment by catap** [comment]
@nilason why? old library hadn't changed. I simple adds `.h` and `symlink`.

**Comment by nilason** [comment]
> @nilason why? old library hadn't changed. I simple adds `.h` and `symlink`.

The library version number (its "SO version") has changed with https://github.com/macports/macports-ports/commit/9a7a13c0a82e0ff23bc4e1d4335ef6c537f59a65, that is the one that should have prompted a revision increase of its dependencies. Now you could use this change to trigger a rebuild for them anyway.

**Comment by nilason** [comment]
See https://github.com/macports/macports-ports/pull/18077#issuecomment-1517641654 for some related background (and a good find script command).

**Comment by catap** [comment]
@nilason I've tested it with minetest which depends on LevelDB and it works:
```
√ ~ % port installed | grep minetest
√ ~ % sudo port install --unrequested minetest
Password:
--->  Computing dependencies for minetest
--->  Fetching archive for minetest
--->  Attempting to fetch minetest-5.7.0_0.darwin_21.x86_64.tbz2 from https://packages.macports.org/minetest
--->  Attempting to fetch minetest-5.7.0_0.darwin_21.x86_64.tbz2.rmd160 from https://packages.macports.org/minetest
--->  Installing minetest @5.7.0_0
--->  Activating minetest @5.7.0_0
--->  Cleaning minetest
--->  Scanning binaries for linking errors
--->  No broken files found.                             
--->  No broken ports found.
√ ~ % 
```

Are you sure that we need to revbump all qt ports?

**Comment by nilason** [comment]
Convenient overview for dependencies (not included deps via variants) is listed in https://ports.macports.org/port/leveldb/details/.

**Comment by catap** [comment]
> I believe. At least I had to rebuild `qt5-qtwebkit` to make QGIS work. It was linked to something like libleveldb.1.20.0.dylib and now it is libleveldb.1.23.0.dylib), I suppose it depends on if a port is linked to the more general libleveldb.dylib (being a symlink to the versioned dylib) or directly to the versioned file.

Got it. Revbumping everything when.

**Comment by catap** [comment]
Here it is. Anyway, I've missed `py-plyvel` which I've updated at https://github.com/macports/macports-ports/pull/20327 and CI because it hasn't got any chance to build it on time.

**Pull request merged**
