### PR TITLE
fontforge: update to latest master, use CMake

### PR DESCRIPTION
**Pull request by mojca**
#### Description

@tessus

Preliminary version which hopefully works (or at least builds) much better than the existing port. This has been brought to our attention in https://github.com/fontforge/fontforge/issues/3281. Apparently a new version is about to be released very soon, so I would probably wait for the new release.

* This might need a review of dependencies.
* Do we really need to make `python` and `gui` variants optional? I would simply unconditionally include them unless there's a good reason not to do so. In the past it might  have been the difficulty to build it.
* I tested with `gtk3 +x11` which I happen to have installed on my computer. It would make sense to test with `gtk3 +quartz` which probably also works much better.
* Maybe we need an explicit variant based on what variant `gtk3` has been built with. I didn't check  whether the files installed by fontforge are the same or not.
* Please note that I did absolutely zero checking on any older systems, I didn't even test if patches still apply in a clean fashion.
* I didn't bother checking the "requires some recent C standard" part.
* I'm pretty sure that the port has some dependents which would require revbumping. I didn't check those either.
* Upstream ships all resources required to build the app bundle and already contains a cmake target to build it, but that target does the build from scratch. It would be nice if someone would be willing to take some time to adapt CMakeLists.txt to allow using those same existing resources to create MacPorts-friendly FontForge.app without the app PortGroup.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.6 17G9016
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by tessus** [comment]
> Do we really need to make python and gui variants optional? 

I certainly do not want the UI compiled/nstalled automatically. I use fontforge exclusively on the command line via the python bindings in the ForkAwesome project.

Most of the time I use command line tools and in rare occasions I do use a GUI. However, I do not have X11 nor Quartz depenencies on my machine, so this would automatically be added when installing fontforge without having the choice not to install the UI.

**Comment by mojca** [comment]
Ok, noted. Does this port work for you?

**Comment by tessus** [comment]
I haven't tried it, because it would screw with all my other ports due to py37 -> py38 and I also do not want to install any X11/Quartz/gtk3 libraries.

**Comment by kencu** [comment]
Works perfectly on 10.6.8 with all default settings. +1

**Comment by kencu** [comment]
IMHO the GUI is magnificent and should be the default, btw.

**Comment by emcrisostomo** [comment]
I agree with @kencu

**Comment by tessus** [comment]
As long as I can install it witout the GUI I don't care. I certainly don't want to install all the X11/gtk rubbish, when all I need is a simple commandline tool.

**Comment by mojca** [comment]
Replaced by #7040

**Pull request closed without merging**
