### PR TITLE
ffmpeg: enable av1 codec support with aom/rav1e

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by i0ntempest** [comment]
There's also [SVT-AV1](https://github.com/AOMediaCodec/SVT-AV1) encoder, but better add this after we have ffmpeg 5.1+.
Also FFmpeg 4.4.2 was released, do you guys want it together with this PR?

**Comment by kencu** [comment]
rav1e requires rust, so some systems will break.

Folks have recently got rust working on 10.6.

Not sure if rust can build universal atm.

**Comment by kencu** [comment]
https://trac.macports.org/ticket/62650

**Comment by mascguy** [comment]
> rav1e requires rust, so some systems will break.

Great point.

Also, from a bigger-picture perspective, I'm wondering whether `ffmpeg` is becoming a bit bloated.

While I'm all for supporting as many codecs, filters, etc, as possible... we already have a boatload of support.

Perhaps some things like this should only be enabled via a new variant? Thoughts?

**Comment by i0ntempest** [comment]
Given av1 isn't a widely used codec yet I can accept it being in a variant, it's also going to make adding SVT-AV1 easier later. I also want to add libass support later, should that also be a variant? And should we break more features out of the current configuration as variants for better control?
Also I see you added ffmpeg-upstream port, what purpose do you intent it to serve that ffmpeg-devel can't?

**Comment by mascguy** [comment]
> Also I see you added ffmpeg-upstream port, what purpose do you intent it to serve that ffmpeg-devel can't?

That's explained via my latest commit: https://github.com/macports/macports-ports/commit/29bc6b1a80cd02dcd1734f4722367aa003d39af6

But in short, `ffmpeg-upstream` now provides the latest upstream release. While `ffmpeg-devel` now aligns with `ffmpeg`, to support pre-rollout testing and validation. So you'll want to rebase against master, and update `ffmpeg-devel` instead.

> Given av1 isn't a widely used codec yet I can accept it being in a variant, it's also going to make adding SVT-AV1 easier later. I also want to add libass support later, should that also be a variant? And should we break more features out of the current configuration as variants for better control? 

I need to ponder how to handle this, before we add any further bloat to `ffmpeg`. As such, changing the status of this PR to draft.

**Comment by mascguy** [comment]
Also, from a holistic perspective: `ffmpeg` builds across-the-board - and is supported on - macOS releases as far back as 10.4 and 10.5. And our users of legacy hardware very much appreciate that!

So additions/changes should continue that support. And if there are any barriers to that - such as per Ken's comments regarding Rust - that also must be taken into account.

**Comment by i0ntempest** [comment]
Somehow I messed up and its not letting me reopen. See https://github.com/macports/macports-ports/pull/15219

**Pull request closed without merging**
