### PR TITLE
bali-phy: Blacklist compilers that don't know -std=c++14

### PR DESCRIPTION
**Pull request by bredelings**
#### Description

Unbreak build-bots by blacklisting compilers that don't recognized -std=c++14

### CODE REVIEW

**Comment by pmetzger** [comment]
There are probably versions of gcc that also don't understand -std=c++14, correct?

**Comment by bredelings** [comment]
Hmm... I suppose this is true.  I stole the line from other files, which don't mention gcc.
How would you blacklist versions of gcc before version 5?

**Comment by bredelings** [comment]
I suppose the proper way to do this is to copy the cxx11 portgroup to cxx14 and update it.

**Comment by pmetzger** [comment]
Okay, for now, I'm going to merge just so that you have fewer problems with broken builds — strictly speaking this doesn't make anything _worse_ than it was, and makes things a bit better — but I'd suggest that you get on macports-dev and ask what the correct fix is rather than leaving this be.

**Comment by pmetzger** [comment]
(Just to make it clear: I want see this fixed more correctly, but it would be better if the build cluster gave you as much feedback as possible about the port as it is brand new.)

**Pull request merged**
