### PR TITLE
icu update to 63.1 and bump all deps

### PR DESCRIPTION
**Pull request by kencu**
resuscitated, sort of, with the help of @lbschenkel

### CODE REVIEW

**Comment by dbevans** [comment]
As mentioned above libphonenumber-cpp and mapnik have been updated since you committed this PR and so your PR needs to be updated accordingly to allow a smooth rebase with current master.

**Comment by kencu** [comment]
Thanks -- I messed that up so horrendously last time I am trying for a quiet bit to get it done :>

**Comment by kencu** [comment]
fixed, thanks for the eyeballs.

**Comment by mojca** [comment]
I'm not maintaining any of those ports, but we should merge it soon and fix any remaining issues later like @michaelld said, else it can take another 10 years before you are able to update ICU :)

**Comment by pmetzger** [comment]
Agreed. Merge quickly, fix fallout quickly.

**Comment by kencu** [comment]
It would be difficult to commit this without some hint from Ryan as the maintainer to go ahead with it.

**Comment by pmetzger** [comment]
@kencu Maybe send him email?

**Comment by kencu** [comment]
Not hearing any objections, I'll commit this tomorrow morning.

**Comment by kencu** [comment]
I will admit I was tempted to commit this, but in the end I feel we can't/shouldn't until and if Ryan weighs in as maintainer.

**Comment by pmetzger** [comment]
@kencu I recommend getting directly in touch with him. He often doesn't notice Github notifications.

**Comment by kencu** [comment]
building `icu` on 10.5 PPC fails with the `std::math` errors that are present with `gcc` less than version 7 on those systems. building `icu` with `gcc7` is successful. So `gcc` versions less than 7 will need to be blacklisted at present.

**Comment by kencu** [comment]
also, have not as yet tested universal builds. For sure `i386 ppc` universal builds will not work, as `gcc` > 4.2 cannot do cross -arch builds on MacPorts at present (and probably never will).

**Comment by kencu** [comment]
So -- given all that, perhaps it is best to park these patches off in a ticket, for future consideration.

**Comment by kencu** [comment]
Yes, I think so. Reading through the details of the portfile, I see all the hassles that were faced trying to get it to the state it is in now.  We'll get Ryan in on it when there is enthusiasm and we can sort out the last few bumps (ie universal builds on < 10.6 won't work, and gcc versions < 7 need to be blacklisted and the fallbacks set up correctly). At the moment, the number of ports that can't update is reasonably small still. I have put the patches that this PR represented here in this ticket <https://trac.macports.org/ticket/56754>.

**Pull request closed without merging**
