### PR TITLE
py-typing: reverse py35/py36 subports added by 6c05e98

### PR DESCRIPTION
**Pull request by aque**
This is one of the ports listed under [ticket #56357](https://trac.macports.org/ticket/56357).

@mojca, I was not sure from the ticket whether I am supposed to submit the PR, or you were planning to.

### CODE REVIEW

**Comment by pmetzger** [comment]
@mojca Should do it, but I can merge this for you without any trouble.

**Comment by aque** [comment]
Thanks @pmetzger.

**Comment by mojca** [comment]
I broke it, so I guess it would be nice from me to fix stuff I broke, but it's super helpful if others jump in and do it instead of me :) Thank you.

I'm currently at location where most of the time not even 2G works, so most of the time I'm not even able to read emails.

**Comment by mojca** [comment]
Next time please reference the ticket in the commit message.

**Comment by aque** [comment]
Will do.

**Pull request merged**
