### PR TITLE
py-reproject: update to 0.4

### PR DESCRIPTION
**Pull request by lpsinger**

### CODE REVIEW

**Comment by cdeil** [comment]
@lpsinger - The build logs for this PR all seem to fail when trying to install the `astropy-healpix` dependency because no Cython is available.
Could you please declare the Cython build dependency for astropy-healpix here, or in a separate PR?

Otherwise, 👍 to merge this, thanks!

**Comment by cdeil** [comment]
Looks like Python 3.4 has to be removed or declared non-supported somehow: https://paste.macports.org/4af2a3ab845a

Otherwise, 👍 to merge.

**Comment by lpsinger** [comment]
> Looks like Python 3.4 has to be removed or declared non-supported somehow

Oops! Fixed in c216d008253ead4cf01801d6e60b0dd2c55befac.

**Comment by cdeil** [comment]
@lpsinger - Thank you!

**Pull request merged**
