### PR TITLE
shairport-sync: fix for older systems (patch from upstream)

### PR DESCRIPTION
**Pull request by barracuda156**
Closes: https://trac.macports.org/ticket/70148

#### Description

Fix from upstream

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
I don't see what most of these changes have to do with the compilation problem?

**Comment by barracuda156** [comment]
@pmetzger Patches are backports of two commits:
https://github.com/mikebrady/shairport-sync/commit/0412a84006773098c558ed3f8d4b57b8540244ce
https://github.com/mikebrady/shairport-sync/commit/c064b8bae5f1d2816857646382de5ca3a1ab5e15

They contain one unrelated to older OS fix, but I just took them as-they-were-committed by upstream.

**Comment by pmetzger** [comment]
The second commit is very long and mostly has nothing to do with MacOS.

**Comment by barracuda156** [comment]
@ pmetzger What is the problem though? Why should I do a surgery on a commit from upstream? It will be dropped with the next release anyway.

**Comment by pmetzger** [comment]
I'm tempted to suggest we just wait for the upstream release, but I suppose that's probably excessive and we should just commit. We'll see whether the maintainer pipes up. (I sadly suspect they won't; they don't have a github handle registered.)

**Comment by pmetzger** [comment]
When Mike updates to the next version, please update this so we can get rid of the ugly patch.

**Comment by barracuda156** [comment]
@pmetzger This is why we want patches unconditional: they won’t apply on the next update, so cannot be left by accident.

**Pull request merged**
