### PR TITLE
get_iplayer: update to 3.31

### PR DESCRIPTION
**Pull request by aeiouaeiouaeiouaeiouaeiouaeiou**
Should be merged after #17433.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.8.5 12F2560 x86_64
Xcode 5.1.1 5B1008

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by dliessi** [comment]
I haven't tested it, but LGTM and can be merged.
This change is actually independent of #17433, so there is no need to wait for that PR.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
>This change is actually independent of https://github.com/macports/macports-ports/pull/17433, so there is no need to wait for that PR.

The latest version of get_iplayer [updates the use](https://github.com/get-iplayer/get_iplayer/commit/f7dcdd5e2a15f3c093a399083d1cb9006eab1d70) of [`--hdvideo` flag](https://github.com/wez/atomicparsley/commit/202c1085861afa16b8dc0fa69e61b1e8646cbcb1), which is not fully implemented in the current version of AtomicParsley from MacPorts.

**Comment by dliessi** [comment]
Just for precision: [that very commit](https://github.com/get-iplayer/get_iplayer/commit/f7dcdd5e2a15f3c093a399083d1cb9006eab1d70) shows that get_iplayer determines whether AtomicParsley supports the old or the new `--hdvideo` flag and translates the value accordingly.
Anyway, I am not opposed to waiting (and I would welcome the update to AtomicParsley), I was just noting that it is not necessary.

@aeiouaeiouaeiouaeiouaeiouaeiou Thank you for your contributions!

**Comment by dliessi** [comment]
> (and I would welcome the update to AtomicParsley)

...which in the meantime has been merged... :)

**Pull request merged**
