### PR TITLE
OpenBLAS: fix linking on older Mac versions

### PR DESCRIPTION
**Pull request by erikbs**
#### Description

Tweak ar options instead of using weak linking. Ensure that the `_xerbla_` symbol exists by always writing the correct `xerbla.c.o` file to the archive regardless of compilation order.

Fixes: https://trac.macports.org/ticket/68810

Upstream PR: https://github.com/OpenMathLib/OpenBLAS/pull/4353

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.9.5 13F1911 x86_64
Xcode 6.2 6C131e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by cooljeanius — APPROVED** [review]

**Comment by barracuda156** [comment]
@catap It is still broken at configure:
```
-- fortran lapack
-- Building deprecated routines
-- Building Single Precision
-- Building Double Precision
-- Building Single Precision Complex
-- Building Double Precision Complex
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - no
-- Could NOT find Threads (missing: Threads_FOUND) 
-- Generating openblas_config.h in include/openblas
-- Generating f77blas.h in include/openblas
-- Generating cblas.h in include/openblas
-- Copying LAPACKE header files to include/openblas
-- Configuring incomplete, errors occurred!
See also "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_math_OpenBLAS/OpenBLAS-devel/work/build/CMakeFiles/CMakeOutput.log".
See also "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_math_OpenBLAS/OpenBLAS-devel/work/build/CMakeFiles/CMakeError.log".
Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_math_OpenBLAS/OpenBLAS-devel/work/build" && /opt/local/bin/cmake -G "CodeBlocks - Unix Makefiles" -DCMAKE_BUILD_TYPE=MacPorts -DCMAKE_INSTALL_PREFIX="/opt/local" -DCMAKE_INSTALL_NAME_DIR="/opt/local/lib" -DCMAKE_SYSTEM_PREFIX_PATH="/opt/local;/usr" -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_OBJC_COMPILER="$CC" -DCMAKE_OBJCXX_COMPILER="$CXX" -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_POLICY_DEFAULT_CMP0060=NEW -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_MODULE_PATH="/opt/local/share/cmake/Modules" -DCMAKE_PREFIX_PATH="/opt/local/share/cmake/Modules" -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=OFF -DCMAKE_INSTALL_RPATH="/opt/local/lib" -Wno-dev -DCOMMON_PROF=-pg -DNO_AVX=ON -DNO_AVX2=ON -DNO_AVX512=ON -DCMAKE_AR=/opt/local/bin/ar -DCMAKE_NM=/opt/local/bin/nm -DCMAKE_OBJDUMP=/opt/local/bin/objdump -DCMAKE_RANLIB=/opt/local/bin/ranlib -DCMAKE_STRIP=/opt/local/bin/strip -DCMAKE_LINKER=/opt/local/bin/ld -DBUILD_SHARED_LIBS=ON -DCMAKE_OSX_ARCHITECTURES="ppc" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.6" -DCMAKE_OSX_SYSROOT="/" /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_math_OpenBLAS/OpenBLAS-devel/work/OpenBLAS-864c65b526945604597ef9da1571a2f36b408054 
Exit code: 1
```

**Comment by barracuda156** [comment]
@catap Oh, it does some phenomenal nonsense:
```
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_math_OpenBLAS/OpenBLAS-devel/work/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_d8baf/fast && /usr/bin/make  -f CMakeFiles/cmTC_d8baf.dir/build.make CMakeFiles/cmTC_d8baf.dir/build
Building C object CMakeFiles/cmTC_d8baf.dir/src.c.o
/opt/local/bin/gcc-mp-13 -DCMAKE_HAVE_LIBC_PTHREAD  -pipe -O3 -DNDEBUG -I/opt/local/include -arch ppc  -DHAVE_C11 -Wall -m64 -fPIC -DNO_AVX -DNO_AVX2 -DNO_AVX512 -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DMAX_STACK_ALLOC=2048 -DNO_AFFINITY -DVERSION="\"0.3.25.dev\"" -DBUILD_SINGLE -DBUILD_DOUBLE -DBUILD_COMPLEX -DBUILD_COMPLEX16  -arch ppc -mmacosx-version-min=10.6 -o CMakeFiles/cmTC_d8baf.dir/src.c.o -c /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_math_OpenBLAS/OpenBLAS-devel/work/build/CMakeFiles/CMakeTmp/src.c
gcc-mp-13: warning: '-m64' conflicts with '-arch ppc' ('-m64' ignored)
{standard input}:1:invalid .machine argument: ppc7400
make[1]: *** [CMakeFiles/cmTC_d8baf.dir/src.c.o] Error 1
make: *** [cmTC_d8baf/fast] Error 2


Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_math_OpenBLAS/OpenBLAS-devel/work/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_f215a/fast && /usr/bin/make  -f CMakeFiles/cmTC_f215a.dir/build.make CMakeFiles/cmTC_f215a.dir/build
Building C object CMakeFiles/cmTC_f215a.dir/CheckFunctionExists.c.o
/opt/local/bin/gcc-mp-13   -pipe -O3 -DNDEBUG -I/opt/local/include -arch ppc  -DHAVE_C11 -Wall -m64 -fPIC -DNO_AVX -DNO_AVX2 -DNO_AVX512 -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DMAX_STACK_ALLOC=2048 -DNO_AFFINITY -DVERSION="\"0.3.25.dev\"" -DBUILD_SINGLE -DBUILD_DOUBLE -DBUILD_COMPLEX -DBUILD_COMPLEX16 -DCHECK_FUNCTION_EXISTS=pthread_create -arch ppc -mmacosx-version-min=10.6 -o CMakeFiles/cmTC_f215a.dir/CheckFunctionExists.c.o -c /opt/local/share/cmake-3.24/Modules/CheckFunctionExists.c
gcc-mp-13: warning: '-m64' conflicts with '-arch ppc' ('-m64' ignored)
{standard input}:1:invalid .machine argument: ppc7400
make[1]: *** [CMakeFiles/cmTC_f215a.dir/CheckFunctionExists.c.o] Error 1
make: *** [cmTC_f215a/fast] Error 2



Determining if the function pthread_create exists in the pthread failed with the following output:
Change Dir: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_math_OpenBLAS/OpenBLAS-devel/work/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_42ce4/fast && /usr/bin/make  -f CMakeFiles/cmTC_42ce4.dir/build.make CMakeFiles/cmTC_42ce4.dir/build
Building C object CMakeFiles/cmTC_42ce4.dir/CheckFunctionExists.c.o
/opt/local/bin/gcc-mp-13   -pipe -O3 -DNDEBUG -I/opt/local/include -arch ppc  -DHAVE_C11 -Wall -m64 -fPIC -DNO_AVX -DNO_AVX2 -DNO_AVX512 -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DMAX_STACK_ALLOC=2048 -DNO_AFFINITY -DVERSION="\"0.3.25.dev\"" -DBUILD_SINGLE -DBUILD_DOUBLE -DBUILD_COMPLEX -DBUILD_COMPLEX16 -DCHECK_FUNCTION_EXISTS=pthread_create -arch ppc -mmacosx-version-min=10.6 -o CMakeFiles/cmTC_42ce4.dir/CheckFunctionExists.c.o -c /opt/local/share/cmake-3.24/Modules/CheckFunctionExists.c
gcc-mp-13: warning: '-m64' conflicts with '-arch ppc' ('-m64' ignored)
{standard input}:1:invalid .machine argument: ppc7400
make[1]: *** [CMakeFiles/cmTC_42ce4.dir/CheckFunctionExists.c.o] Error 1
make: *** [cmTC_42ce4/fast] Error 2



Determining if compiler accepts -pthread failed with the following output:
Change Dir: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_math_OpenBLAS/OpenBLAS-devel/work/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_676bc/fast && /usr/bin/make  -f CMakeFiles/cmTC_676bc.dir/build.make CMakeFiles/cmTC_676bc.dir/build
Building C object CMakeFiles/cmTC_676bc.dir/CheckForPthreads.c.o
/opt/local/bin/gcc-mp-13   -pipe -O3 -DNDEBUG -I/opt/local/include -arch ppc  -DHAVE_C11 -Wall -m64 -fPIC -DNO_AVX -DNO_AVX2 -DNO_AVX512 -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DMAX_STACK_ALLOC=2048 -DNO_AFFINITY -DVERSION="\"0.3.25.dev\"" -DBUILD_SINGLE -DBUILD_DOUBLE -DBUILD_COMPLEX -DBUILD_COMPLEX16  -arch ppc -mmacosx-version-min=10.6 -o CMakeFiles/cmTC_676bc.dir/CheckForPthreads.c.o -c /opt/local/share/cmake-3.24/Modules/CheckForPthreads.c
gcc-mp-13: warning: '-m64' conflicts with '-arch ppc' ('-m64' ignored)
{standard input}:1:invalid .machine argument: ppc7400
make[1]: *** [CMakeFiles/cmTC_676bc.dir/CheckForPthreads.c.o] Error 1
make: *** [cmTC_676bc/fast] Error 2
```

**Comment by catap** [comment]
Is it Rosetta or native PPC?

**Comment by barracuda156** [comment]
> Is it Rosetta or native PPC?

Native, on G5.

**Comment by catap** [comment]
> invalid .machine argument: ppc7400

seems like GCC13 issue, isn’t it?

**Comment by barracuda156** [comment]
> > invalid .machine argument: ppc7400
> 
> seems like GCC13 issue, isn’t it?

Well, I have multiple GCCs to check, but I would be surprised if it is GCC at fault here.

**Comment by barracuda156** [comment]
@catap Okay, it is just upstream code is broken for arch detection.

**Comment by barracuda156** [comment]
@catap So -m64 for 32-bit arch is forced in system_check, which unsurprisingly breaks configure. Once that is fixed, pthreads are found normally.
However something else further is broken:
```
-- Reading vars from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_math_OpenBLAS/OpenBLAS-devel/work/OpenBLAS-864c65b526945604597ef9da1571a2f36b408054/kernel/power/KERNEL...
-- Reading vars from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_math_OpenBLAS/OpenBLAS-devel/work/OpenBLAS-864c65b526945604597ef9da1571a2f36b408054/kernel/power/KERNEL.PPC970...
CMake Error at cmake/utils.cmake:106 (string):
  string sub-command REGEX, mode MATCHALL needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  kernel/CMakeLists.txt:13 (ParseMakefileVars)
  kernel/CMakeLists.txt:1371 (build_core)


CMake Error at cmake/utils.cmake:106 (string):
  string sub-command REGEX, mode MATCHALL needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  kernel/CMakeLists.txt:13 (ParseMakefileVars)
  kernel/CMakeLists.txt:1371 (build_core)


CMake Error at cmake/utils.cmake:106 (string):
  string sub-command REGEX, mode MATCHALL needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  kernel/CMakeLists.txt:13 (ParseMakefileVars)
  kernel/CMakeLists.txt:1371 (build_core)


CMake Error at cmake/utils.cmake:106 (string):
  string sub-command REGEX, mode MATCHALL needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  kernel/CMakeLists.txt:13 (ParseMakefileVars)
  kernel/CMakeLists.txt:1371 (build_core)
```

**Pull request merged**
