### PR TITLE
Qemu 6.2.0

### PR DESCRIPTION
**Pull request by srirangav**
#### Description

Update qemu to version 6.2.0

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.6.2 20G314 arm64
Xcode 12.5.1 12E507

###### Verification 
Have you

- [ X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [X ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ X] tried a full install with `sudo port -vst install`?
- [X ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
This change failed to build in CI.  It looks like it's because one of the `qemu` patches does not apply cleanly against 6.2.0:

```
--->  Applying patch-qemu-punchhole.diff
...
  patching file block/file-posix.c
  Hunk #1 FAILED at 1830.
  1 out of 1 hunk FAILED -- saving rejects to file block/file-posix.c.rej
  Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_emulators_qemu/qemu/work/qemu-6.2.0" && /usr/bin/patch -p0 < '/Users/runner/work/macports-ports/macports-ports/ports/emulators/qemu/files/patch-qemu-punchhole.diff'
  Exit code: 1
  Error: Failed to patch qemu: command execution failed
...
```

Did you test any of this locally?

**Comment by reneeotten** [comment]
> Some of the recent patchwork was my doing so I will take a look at this in detail.

You don't have to - it's the PR submitter's task to make sure that patches apply cleanly

**Comment by srirangav** [comment]
Hi @reneeotten, @herbygillot, 

I built this on BigSur (11.6.2 / M1) and did not see any errors.  I tested x86_64, i386, ppc, and arm VMs and they worked fine for me.  I am not sure why, but I don't see the file "patch-qemu-punchhole.diff" in my local git repository (I did a git fetch upstream and a git pull before creating my branch, but perhaps I missed something), which is maybe why I didn't get this error.

Sorry for any inconvenience.  

-ranga

**Comment by reneeotten** [comment]
now there is an update PR for the changes to `qemu`, please do remove that commit from this PR so that you have only the changes to `dosbox-x` left here (and update the description and such)

**Comment by srirangav** [comment]
Hi @reneeotten,

I provided a PR for dosxbox-x (https://github.com/macports/macports-ports/pull/13217) that was already merged.  I'm not sure why it is showing up here.  

Since there is a separate PR for updating qemu to 6.2.0, I will just close this PR.

Thanks,

-ranga

**Pull request closed without merging**
