### PR TITLE
asciinema: update to 2.1.0, use python39

### PR DESCRIPTION
**Pull request by laggardkernel**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6
xcode-select version 2354

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`? (No test)
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
@laggardkernel thanks for the update! The changes look good to me, but let's have the CI build this and see what happens. If you feel like making the change you could remove all the `livecheck.*` stuff at the end of the file, the `gitbhub` PG will take care of all of this and it's all redundant.

**Comment by laggardkernel** [comment]
>  you could remove all the livecheck.* stuff at the end of the file, the gitbhub PG will take care of all of this and it's all redundant
Thanks, didn't notice about it. `livecheck` removed and force pushed.

In the last check, one of the pipeline failed to bootstrap MacPorts, is it related to my change?

**Comment by reneeotten** [comment]
> In the last check, one of the pipeline failed to bootstrap MacPorts, is it related to my change?

no, this is a known issue...

**Comment by reneeotten** [comment]
thanks for the update @laggardkernel !

**Pull request merged**
