### PR TITLE
meson-1.0: Add setup using configure.pre_args

### PR DESCRIPTION
**Pull request by Gcenx**
Adding via configure.pre_args to avoid https://trac.macports.org/ticket/66761

###### Type(s)

- [x] bugfix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

### CODE REVIEW

**Comment by kencu** [comment]
But I believe the default configure.pre_args already contain some things…like prefix , set by base. 

So if they are overridden, the prefix will be unset…

Did this change work for you when you tested it?

**Comment by kencu** [comment]
I tried a couple of simple fixes, but realized it was going to take a bit of a deeper test.

IDKY, but maybe the meson PG might have to use

configure.pre_args-prepend setup

to get this robustly right? I can’t imagine any Portfiles using meson using that, so it should be robust (although if a meson-using Portfile did use configure.pre_args-prepend, things would break).

Or tack setup back onto the configure.cmd, but rejig muniversal 1.0 and 1.1 to work properly with that (I tried that too, it works, bit less elegant, may be best…)

**Comment by Gcenx** [comment]
I’ll dig into this more after work today

**Comment by Gcenx** [comment]
@kencu maybe we simply do:
```
default configure.pre_args  {setup --prefix=${prefix}}
```

**Comment by kencu** [comment]
> @kencu maybe we simply do:
> 
> ```
> default configure.pre_args  {setup --prefix=${prefix}}
> ```

That might well work. Is there any other part of base, or these myriad of Portgroups we have, that might monkey with the configure.pre_args, I wonder? 

It's just almost impossible to know the answer to that. Might have to just go for it and see what fallout might occur.

**Comment by Gcenx** [comment]
> That might well work. Is there any other part of base, or these myriad of Portgroups we have, that might monkey with the configure.pre_args, I wonder?

Only one that comes to mind is the cmake Portgroups and those wouldn't affect correctly configured meson projects _unless someone forgotten to use a "port" and meson falls back to a wrap for a cmake project, aka the reason for #16810_
 
> It's just almost impossible to know the answer to that. Might have to just go for it and see what fallout might occur.

Agreed

**Comment by Gcenx** [comment]
Simply put there's no legitimate reason to have a cmake portgroup added to a meson project.

There are some weird and wonderful meson wraps that handle many different deps but these are not _real_ meson projects.

**Pull request merged**
