### PR TITLE
 py-m2crypto: fix reinplace warning, add swig build.env

### PR DESCRIPTION
**Pull request by aque**
###### Description
Minor bugfix.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13 17A405
Xcode 9.0 9A235 

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by aque** [comment]
The port built fine so I don't think it needs a revbump. The swig env was to follow upstream [macOS install documentation](https://gitlab.com/m2crypto/m2crypto/blob/master/INSTALL.rst), but there were no errors in building without it.

**Comment by aque** [comment]
@neverpanic as you approved this change, can you merge this as well?

**Comment by neverpanic** [comment]
Right, missed your reply. Sorry about the delay.

**Comment by aque** [comment]
No problem @neverpanic. I completely forgot this as well. 😄

**Pull request merged**
