### PR TITLE
wxWidgets, wxPython: fixes after upgrade to 3.0.3

### PR DESCRIPTION
**Pull request by mojca**
###### Description

This update should fix issues after upgrade of wxWidgets to 3.0.3, in particular for wxPython. It also upgrades wxWidgets-3.2 to the latest version from master.

I would be particularly grateful for additional testing on < 10.9, perhaps on 10.5-10.7 in particular. Maybe try to run `sudo port -v test p5.26-wx`.

(I would suggest to remove `wxWidgets-libcxx` in the next step: it was only used in FileZilla. https://trac.macports.org/ticket/55221)

Relevant tickets:
* https://trac.macports.org/ticket/54296
* https://trac.macports.org/ticket/54978
* https://trac.macports.org/ticket/54476

Still unresolved (waiting for upstream):
* https://trac.macports.org/ticket/55123

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.1 17B48
Xcode 9.1 9B55

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mojca** [comment]
If @yan12125 agrees, I would also patch FileZilla in the same batch and then remove `wxWidgets-3.0-libcxx`. See the patch in https://trac.macports.org/ticket/55221.

**Comment by yan12125** [comment]
I'm definitely fine with these changes as long as FileZilla builds and works. I don't have < 10.9 to test, though.

**Comment by mojca** [comment]
Please do some testing on your OS. (I would be quite surprised if there are any users on < 10.9 anyway.)

**Comment by kencu** [comment]
I have posted the results of ```sudo port -v test p5.26-wx``` in the trac ticket ```https://trac.macports.org/ticket/54296```. It builds, but did not pass all the tests.

**Comment by yan12125** [comment]
@mojca: Tried this pull request with the FileZilla patch in https://trac.macports.org/ticket/55221. FileZilla builds and runs fine.

My system:
```
macOS 10.13.1 17B48
Xcode 9.1 9B55
```

**Pull request merged**
