### PR TITLE
gobject-introspection PG: respect all CFLAGS

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
Fixes https://trac.macports.org/ticket/62410

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G14042
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
Thanks Marcus, looks like an elegant fix.

I suppose I am the goat for merging your last gir PR, but it had sat there for months and months and everyone felt it was the right fix to do. Who knew the wreckage that would result.

For that reason, if no other, I will let someone else merge this one, once it reaches timeout, assuming @dbevans has no objections.

**Comment by cjones051073** [comment]
Hmm, its a little difficult to review this given the significant changes to the PG and the fact the builds fail presumably due to the number of touched ports. Are we happy to merge as is and assume the PG changes work ?

**Review by cjones051073 — CHANGES_REQUESTED** [review]
Could you please mention in the commit message that you also bump dependent ports.

**Comment by MarcusCalhoun-Lopez** [comment]
I have updated the commit message.
Some of these ports do not build on any platform.
However, the ones that do build seem to build properly on a macOS 10.13 VM.

**Pull request merged**
