### PR TITLE
mesos: use HTTPS URL for livecheck

### PR DESCRIPTION
**Pull request by chrstphrchvz**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] ~~referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?~~

- [ ] checked your Portfile with `port lint`?

### CODE REVIEW

**Comment by pmetzger** [comment]
I think this is allowed to be committed immediately under openmaintainer. That said, I'm a bit concerned about the failure in the Azure CI?

**Comment by chrstphrchvz** [comment]
> I think this is allowed to be committed immediately under openmaintainer. That said, I'm a bit concerned about the failure in the Azure CI?

I have opened a ticket to report the build issue: https://trac.macports.org/ticket/58680

**Comment by dgilman** [comment]
I opened https://issues.apache.org/jira/browse/MESOS-9752 to mesos upstream over this, there's something about the macports cyrus-sasl2 that's causing the build to fail.  I took a couple of whacks at it a few months ago but was never able to get it to work. It might be worth removing the package from MacPorts instead but I don't know the policy around that.

**Comment by pmetzger** [comment]
If the package has been broken for more than a year, removing it is fine.

**Comment by dgilman** [comment]
I have opened PR #4788 which includes this https change and obsoletes this PR.

**Comment by pmetzger** [comment]
#4788 has been merged, so I'm going to close this.

**Pull request closed without merging**
