### PR TITLE
macos-fortress: update to version 2023.09.16

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
This does not pass the CI.

**Comment by essandess** [comment]
> This does not pass the CI.

I am unable to determine why the CI fails. It builds fine on multiple boxes, and the CI error message doesn’t reveal the cause to the best of my knowledge.

**Comment by pmetzger** [comment]
Well, shall we close this then?

**Comment by essandess** [comment]
> Well, shall we close this then?

No, please merge it. The updates are necessary to work with the new dshield secure downloads.

**Comment by pmetzger** [comment]
We aren't merging anything that doesn't pass the CI. It will just fail to build both on the buildbots and for end users building from source. If you are not willing to debug the CI failure then we should close this.

**Comment by kencu** [comment]
I don't understand the CI failure either.

```
  ...
  Installing dependency (56 of 68) 'privoxy-pki-bundle' with variants '+user_pki_bundle' ... [OK]
  Installing dependency (57 of 68) 'sf-pwgen' with variants '' ... [OK]
  Installing dependency (58 of 68) 'privoxy' with variants '+https_inspection' ... [OK]
  Installing dependency (59 of 68) 'libtextstyle' with variants '' ... [OK]
  Installing dependency (60 of 68) 'gettext-tools-libs' with variants '' ... [OK]
  Installing dependency (61 of 68) 'gettext' with variants '' ... [OK]
  Installing dependency (62 of 68) 'libpsl' with variants '' ... [OK]
  Installing dependency (63 of 68) 'pcre2' with variants '' ... [OK]
  Installing dependency (64 of 68) 'wget' with variants '+gnutls' ... [OK]
  Installing dependency (65 of 68) 'adblock2privoxy' with variants '+https_inspection' ... [OK]
  Installing dependency (66 of 68) 'p5.34-net-domain-tld' with variants '' ... [OK]
  Installing dependency (67 of 68) 'p5.34-data-validate-domain' with variants '' ... [OK]
  Installing dependency (68 of 68) 'macos-fortress-hosts' with variants '' ... [OK]
Error: Failed to install dependencies for macos-fortress-proxy
```

After installing all 68 dependents of macos-fortress-proxy, all labelled as [OK], it then says it failed.

No idea at all what is going on there.

**Comment by essandess** [comment]
> We aren't merging anything that doesn't pass the CI. It will just fail to build both on the buildbots and for end users building from source. If you are not willing to debug the CI failure then we should close this.

I am willing to debug the CI failure and have attempted to do so with multiple, different approaches. But I cannot because I do not observe the failure myself, and the logs do not indicate what the failure is.

This PR fixes an issue with a new download approach to dshield and the port will not work without this update. Please merge the PR.

**Comment by pmetzger** [comment]
The PR cannot be merged unless we know that the update works. As for what is going wrong, it appears to be:

> macos-fortress-proxy
> 
> ⚠️ Failed to install dependencies

And beyond that I didn't dig. The full logs of the build on macos-13 are available to download as a zipfile of course.

 I'll say, directly, that in the past you have claimed that updates are obvious or clearly work in spite of the fact that the CI failed, and then others have found out that something is in fact wrong. When told what is wrong, you've then failed to reply, sometimes for months on end. If you want to ask on the developers list for assistance that's fine, but we can't generally merge things that fail the CI unless there's a good explanation.

**Comment by essandess** [comment]
> The PR cannot be merged unless we know that the update works. As for what is going wrong, it appears to be, as you said:
> 
> > macos-fortress-proxy
> > ⚠️ Failed to install dependencies
> 
> And beyond that I didn't dig. The full logs of the build on macos-13 are available to download as a zipfile of course.
> 
> I'll say, directly, that in the past you have claimed that updates are obvious or clearly work in spite of the fact that the CI failed, and then others have found out that something is in fact wrong. When told what is wrong, you've then failed to reply, sometimes for months on end. This makes it hard to grant you the benefit of the doubt without an explanation for the failure. If you want to ask on the developers list for assistance that's fine, but we can't generally merge things that fail the CI unless there's a good explanation.

Your responses here and in other posts are an unprofessional and unwarranted characterization of my contributions.

Please delete this post, or respond with a private email so that the issue of your conduct may be taken off of this PR thread.

cc: @ryandesign, @jmroot

**Comment by jmroot** [comment]
Please rebase against master to pick up a789b83f

**Pull request merged**
