### PR TITLE
sbcl: update to 2.3.5; pin for old macOS; add myself as co-maintainer

### PR DESCRIPTION
**Pull request by catap**
#### Description

I also fixed build on old macOS

Closes: https://trac.macports.org/ticket/61717
Closes: https://trac.macports.org/ticket/65188
Closes: https://trac.macports.org/ticket/65484
Closes: https://trac.macports.org/ticket/66002

###### Type(s)

- [x] bugfix
- [x] enhancement

###### Tested on

macOS 10.5.8 9L34 i386
Xcode 3.1.4 9M2809

macOS 10.6.8 10K549 x86_64
Xcode 3.2.6 10M2518

macOS 10.11.6 15G22010 x86_64
Xcode 8.2.1 8C1002

macOS 12.6.3 21G419 x86_64
Xcode 14.2 14C18

macOS 13.3.1 22E261 arm64
Xcode 14.1 14B47b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by catap** [comment]
@barracuda156, @evanmiller  may I ask you to check it on your PowerPC? I did my best to make it works on PowerPC and probably it will, but I haven't tested it.

**Comment by catap** [comment]
Switched to a draft because I’d like to migrate it to legacy support

**Comment by barracuda156** [comment]
> @barracuda156, @evanmiller may I ask you to check it on your PowerPC? I did my best to make it works on PowerPC and probably it will, but I haven't tested it.

@catap already knows, but for the record, `sbcl` 2.0.9 builds fine on 10.6 ppc, though without threads. (Nothing new here, it was building earlier as well.) My earlier procedure via extra bootstrap port is unnecessary – 1.0.47 can directly build 2.0.9.
Rosetta is broken though, since 1.0.47 does not boot there.

**Comment by catap** [comment]
It is ready for review.

**Pull request merged**
