### PR TITLE
gpgme: remove old conflict handler

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Was added in f8da039c58 over two years ago.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] ~~referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?~~

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by lbschenkel** [comment]
+1 from me. Feel free to merge if all builds pass (or if you don't have the rights let me know and I'll merge it). Thank you for the PR.

**Comment by chrstphrchvz** [comment]
Hi @lbschenkel, I do not have commit rights, so I will need someone else to merge it when ready. Thanks for reviewing this!

**Comment by lbschenkel** [comment]
I will wait some hours to give @dbevans  the opportunity to nack this, but given the low risk I think that will be unlikely.

**Comment by lbschenkel** [comment]
Merged. Thanks again.

**Pull request merged**
