### PR TITLE
openjdk17-graalvm: fix subport pollution

### PR DESCRIPTION
**Pull request by breun**
#### Description

Don't apply `pre-install`, variants, etc. to subports.

###### Type(s)

- [x] bugfix

###### Tested on

macOS 13.5.1 22G90 arm64
Xcode 14.3.1 14E300c

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by breun** [comment]
@mascguy Another one.

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
Looks like the subport failed, as the archive couldn't be fetched

**Comment by mascguy** [comment]
> Looks like the subport failed, as the archive couldn't be fetched

Ah, didn't scrutinize the subport earlier: You need to make it a formal stub, to ensure nothing is fetched, etc. And using pg `stub` takes care of all of that for you.

I updated via a separate commit, so the changes are clear. But I'll squash on merge.

**Comment by breun** [comment]
@mascguy Thanks for fixing this one up.

**Comment by mascguy** [comment]
> @mascguy Thanks for fixing this one up.

Happy to help. And thank you so much for updating all of the JDK ports, to install into the MacPorts tree!

**Pull request merged**
