### PR TITLE
Tcl/Tk: update to 8.6.12

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Ignore implicit declarations of functions not available on macOS (`readdir64()`, `rewinddir64()`, `closedir64()`) during configure
Fixes: https://trac.macports.org/ticket/63128

`tk`: drop patch-unix-Makefile.in.diff incorporated upstream (see https://core.tcl-lang.org/tk/tktview?name=3598664)

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.7
Xcode 12.4 command line tools

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mascguy — APPROVED** [review]

**Comment by pmetzger** [comment]
I believe that @MarcusCalhoun-Lopez is not in a position to review fixes to his ports at the very moment.

**Comment by mascguy** [comment]
> I believe that @MarcusCalhoun-Lopez is not in a position to review fixes to his ports at the very moment.

Good to know!

@chrstphrchvz Is it OK if this stays open until Marcus has time to review?

**Comment by pmetzger** [comment]
@MarcusCalhoun-Lopez has indicated he doesn't have time to review things right now.

**Comment by herbygillot** [comment]
My fault, I think I merged this prematurely before @jmroot had a chance to review...

**Pull request merged**
