### PR TITLE
mu: update to 1.12.7, fix build

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update, fix broken build

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ra1nb0w** [comment]
adding python just to get a date is not great but anyway, LGTM.
thank you very much!

**Comment by ra1nb0w** [comment]
yes, we should not touch the meson file and generally python is always available.
your are welcome ;-)

**Comment by barracuda156** [comment]
In fact since `meson` requires Python anyway, there is no overhead (as long as identical version is being used).

**Comment by ra1nb0w** [comment]
Hi @barracuda156, someone opened a [ticket](https://trac.macports.org/ticket/71534#comment:1) that the latest mu port is missing manuals and the documentation. Do you have the time and the desire to find out the issue?
thanks

**Pull request merged**
