### PR TITLE
py-mitmproxy: restore interception of http://mitm.it 

### PR DESCRIPTION
**Pull request by yan12125**
#### Description

Ref: mitmproxy/mitmproxy#3513
Closes: https://trac.macports.org/ticket/58343

###### Type(s)
- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.4 18E226
Xcode 10.2.1 10E1001

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by stromnov** [comment]
I'm not sure that's a good decision to revert tornado to old version:
1) mitmproxy can be simply bounded to python < 35 by default (simply by deactivating/removing py36 and py37 subports)
2) mitmproxy is a quite specific tool that require some low-level understanding of network stack, and users of mitmproxy are usually smart enough to install mitmproxy using alternative techniques such as virtualenv or brew.
3) mitmproxy's onboarding plugin is not mandatory (user can install certificates using alternative well-documented technique https://docs.mitmproxy.org/stable/concepts-certificates/#installing-the-mitmproxy-ca-certificate-manually)
4) Tornado's WSGIAdapter was marked as deprecated at 12 July 2018 (https://www.tornadoweb.org/en/stable/releases/v5.1.0.html#tornado-wsgi)
5) mitmproxy internally make use of tornado IOLoop and use native tornado-based OnboardingApp, but then it trying to convert it to some WSGI Application using mitmproxy WSGIAdapter, then trying to wrap it to obsoleted tornado WSGIAdapter, and then serve it via native tornado IOLoop. It looks very strange and overcomplicated. So I'm sure that OnboardingApp addon can be rewritten without use of deprecated tornado WSGI adapters.

**Comment by yan12125** [comment]
> mitmproxy can be simply bounded to python < 35 by default (simply by deactivating/removing py36 and py37 subports)

The latest stable version of mitmproxy does not officially support python < 3.5: https://github.com/mitmproxy/mitmproxy/blob/v4.0.4/setup.py#L38. I haven't tried to force it to run under 3.4 though. Also, CPython 3.4 branch has been reached end-of-life and might have security issues in near future.

> mitmproxy's onboarding plugin is not mandatory (user can install certificates using alternative well-documented technique

That's what I thought when I first patched mitmproxy and disabled the onboarding plugin. But an upstream developer suggests something different:

> Is there any way you can ship mitmproxy without disabling builtin features? This ultimately ends in support requests and confused users, which takes our time.

(https://github.com/mitmproxy/mitmproxy/issues/3513#issuecomment-483186855)

> Tornado's WSGIAdapter was marked as deprecated at 12 July 2018
> I'm sure that OnboardingApp addon can be rewritten without use of deprecated tornado WSGI adapters.

I'm afraid it will be far from trivial. Actually I've once tried to rewrite the onboarding plugin for Tornado 6.x compatibility but failed due to my limited knowledge about Tornado and/or mitmproxy. That said, this PR is the simplest fix out of my head to achieve upstream expectations.

How do you think @petrrr?

**Comment by markemer** [comment]
Could we add a tornado5 port or install tornado 5 with mitmproxy? Or will they conflict?

**Comment by yan12125** [comment]
Yes they will conflict. Without sophiscated patches, both tornado 5 and
tornado 6 install to
`$prefix/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torndo`.

It's possible to make them co-installable. For example, change the Python
package name from "tornado" to "tornado5", or move tornado to a folder
inside mitmproxy and replace all references from "tornado" to
"mitmproxy.tornado" or adjust `sys.path` carefully to make sure tornado is
always imported from the copy inside mitmproxy. Either approach requires
mass and/or non-trivial patching and can be fragile. I prefer not to go
that way.

Mark Anderson <notifications@github.com> 於 2019年5月22日 週三 上午8:09寫道：

**Comment by markemer** [comment]
Yeah, I don't like any of these options.

**Comment by yan12125** [comment]
A variant sounds good. I will try it out this weekend.

**Comment by yan12125** [comment]
@markemer: Here you go :)

**Comment by markemer** [comment]
I like it. I'm ready to push the button, but maybe we should get a second opinion from another commiter besides us? Up to you, I'm still feeling my way around.

**Comment by yan12125** [comment]
Agree that more comments are better. I'll wait a few days before merging.

**Comment by markemer** [comment]
Sounds like a plan.

**Comment by yan12125** [comment]
3 days passed. I guess either it looks just fine or nobody else cares about it. Gonna merge.

Thanks for looking into it @markemer!

**Pull request merged**
