### PR TITLE
FEniCS: update version 2017.2.0->2018.1.0

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
Instant has "been retired"
See https://bitbucket.org/fenics-project/instant

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.13
Xcode 9.4

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by seanfarley** [comment]
Oh wow, I never in my life thought someone would be willing to try to update the fenics suite! Can we hold off on merging this until I can test this with petsc?

**Comment by pmetzger** [comment]
@seanfarley How long do you want?

**Comment by seanfarley** [comment]
Looks like `dolfin` is missing the python package. I'll have to investigate some more.

**Comment by MarcusCalhoun-Lopez** [comment]
I have modified the pull request so that the python package for dolfin can be installed using the port `py-dolfin`.
Is there anything else that needs to be done for this pull request to be merged?

**Comment by seanfarley** [comment]
Thanks for fixing this. I'm not sure about splitting this into a new port (`dolfin` is both a C++ and python package) but I don't have the time to really complain; so feel free to push this.

**Pull request merged**
