### PR TITLE
openbabel2: fix C++ standard, fix opportunistic usage of wxWidgets

### PR DESCRIPTION
**Pull request by barracuda156**
Closes: https://trac.macports.org/ticket/71480

#### Description

Fix this finally.

(Revbump due to opportunistic usage of wxWidgets, not due to C++ standard.)

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
this doesn't appear too much of an issue as it builds fine all the way down to 10.6... So where exactly do you encounter these build problems? The changes look okay as far as I can tell, but I am just surprised it doesn't show up on any buildbot...

**Comment by reneeotten** [comment]
Also, it this patch solves the problem with wxWidgets, then perhaps the same should be applied to the `openbabel` port - you [opened a ticket for that one a while ago as well](https://trac.macports.org/ticket/68559) but I could never reproduce that error.

**Comment by barracuda156** [comment]
> this doesn't appear too much of an issue as it builds fine all the way down to 10.6... So where exactly do you encounter these build problems? The changes look okay as far as I can tell, but I am just surprised it doesn't show up on any buildbot...

I do not see the logs from buildbots; I am not saying the build must fail (10.6 on x86 uses clang-11, which supports C++11, so Eigen will be happy, perhaps), rather than the GUI will be unusable. Wx apps build fine with incompatible ABI, you just get crashes when trying to launch any. This is not seen on buildbots, obviously.

Also it is just wrong – regardless of whether the app is totally broken in result or merely linked to unwanted components – that the build adds flags to use wxWidgets when the portfile disables GUI: and that happens because CMakeLists have the chunk of code for that outside of the macro.

**Comment by barracuda156** [comment]
> Also, it this patch solves the problem with wxWidgets, then perhaps the same should be applied to the `openbabel` port - you [opened a ticket for that one a while ago as well](https://trac.macports.org/ticket/68559) but I could never reproduce that error.

Yeah, that is the same issue. `eigen3-devel` requires at least C++14, but since gcc defaults to C++17 now, it will probably work fine, provided a) at least C++11 is required, so that MacPorts picks the right compiler and passes C++ ABI flag, and b) CMake does not force a lower standard (passing `-std=c++11` will break the build, for example). To reproduce the failure you will need to use specifically `eigen3-devel` (since the old 3.4.0 is okay with C++11) and have a compiler defaulting to C++ < 14.

With wxWidgets one has to check the logs, not rely on a build being successful. I am pretty sure it will build, but the point is that it should not use wxWidgets at all, when not asked, and not use archaic Apple one in any case, but choose the correct version from MacPorts.

**Pull request merged**
