### PR TITLE
submission: redwax.eu apache modules (pki, signing, timestamping, etc).

### PR DESCRIPTION
**Pull request by dirkx**
Set of new modules - done in one pull request as there are interdependencies.

- [X] enhancement

###### Tested on

macOS 10.13, 10.14, 10.15

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by dirkx** [comment]
Just realised I forgot to squash the commit. fixing.

**Comment by dirkx** [comment]
Fixed, squashed and tested.

**Comment by ra1nb0w** [comment]
you should create a commit per every module, like 
`mod_ca: new port` and then a description.

**Comment by dirkx** [comment]
@ra1nb0w what is the right way of dealing with interdependencies between them ? 

As currently the CI test will fail if I submit them one by one ?

**Comment by ra1nb0w** [comment]
No. Use this PR with multiple commits (one per port)

**Comment by dirkx** [comment]
@ra1nb0w  -- Ok - many thanks for the help. 

I've submitted as 6607 and following (in the order of their inter dependency). 

Let me know if there is anything else I can do to lighten loads.

**Comment by ra1nb0w** [comment]
probably I was not clear; you should use this PR with multiple commits, one per port. One PR with multiple commits and the CI works fine. Like
- first commit: `mod_ca: new port`
- seconf commit: `mod_scep: new port`

Therefore, you don't need to open multiple PR (one for each commit).
Anyway, the commit subject must be `port_name: new port` and nothing more.

**Comment by dirkx** [comment]
Ok - understood. Will fix & as that needs a force - close this one.

**Pull request closed without merging**
