### PR TITLE
fsp: update to 2.8.1b29

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update to 2.8.1b29. The build system has changes to `SCons`.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6 PPC (10A190)
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
The bot is doing a strange thing:
```
scons: Building targets ...
[934](https://github.com/macports/macports-ports/runs/6669351172?check_suite_focus=true#step:8:937)
  scons: *** [/usr/local/share] /usr/local/share: Operation not permitted
[935](https://github.com/macports/macports-ports/runs/6669351172?check_suite_focus=true#step:8:938)
  scons: building terminated because of errors.
[936](https://github.com/macports/macports-ports/runs/6669351172?check_suite_focus=true#step:8:939)
  Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_net_fsp/fsp/work/fsp-2.8.1b29" && /opt/local/bin/scons install DESTDIR=/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_net_fsp/fsp/work/destroot 
[937](https://github.com/macports/macports-ports/runs/6669351172?check_suite_focus=true#step:8:940)
  Exit code: 2
[938](https://github.com/macports/macports-ports/runs/6669351172?check_suite_focus=true#step:8:941)
  Error: Failed to destroot fsp: command execution failed
[939](https://github.com/macports/macports-ports/runs/6669351172?check_suite_focus=true#step:8:942)
  DEBUG: Error code: CHILDSTATUS 4363 2
[940](https://github.com/macports/macports-ports/runs/6669351172?check_suite_focus=true#step:8:943)
  DEBUG: Backtrace: command execution failed
[941](https://github.com/macports/macports-ports/runs/6669351172?check_suite_focus=true#step:8:944)
      while executing
[942](https://github.com/macports/macports-ports/runs/6669351172?check_suite_focus=true#step:8:945)
  "system {*}$notty {*}$callback {*}$nice $fullcmdstring"
[943](https://github.com/macports/macports-ports/runs/6669351172?check_suite_focus=true#step:8:946)
      invoked from within
[944](https://github.com/macports/macports-ports/runs/6669351172?check_suite_focus=true#step:8:947)
  "command_exec -callback portprogress::target_progress_callback destroot"
[945](https://github.com/macports/macports-ports/runs/6669351172?check_suite_focus=true#step:8:948)
      (procedure "portdestroot::destroot_main" line 2)
[946](https://github.com/macports/macports-ports/runs/6669351172?check_suite_focus=true#step:8:949)
      invoked from within
[947](https://github.com/macports/macports-ports/runs/6669351172?check_suite_focus=true#step:8:950)
  "$procedure $targetname"
```

I will see what can be done about it.

**Comment by reneeotten** [comment]
@barracuda156 are you saying that this did build for you locally in trace-mode? If so, then it *should* typicslly also work on the buildbots.

**Comment by barracuda156** [comment]
> @barracuda156 are you saying that this did build for you locally in trace-mode? If so, then it _should_ typicslly also work on the buildbots.

@reneeotten I ran tests, not trace in this case. (As I mentioned in other thread, there is a dylib error on 10.6, unrelated to any particular port.)

**Comment by reneeotten** [comment]
as soon as you see `use_configure no` you have to remember that now you're responsible for making sure that the build will use [TheRightCompiler](https://trac.macports.org/wiki/UsingTheRightCompiler) and flags. Sometimes the `makefile` PG can help with that, alternatively you can specify the things yourself (I just grabbed the current version from the `glob2` Portfile that also uses SCons to build). 

Additionally I added the modeline and made the whitespace changing so that the Porftile conforms to it.

**Comment by reneeotten** [comment]
I'll take a look now at the issue you're seeing; it's understandable that writing to /usr/local/share doesn't work; it should not be doing that, instead ${prefix} should be used

**Comment by barracuda156** [comment]
> It looks like `PREFIX` is hardcoded in `SConstruct` you probably need to add a patchfile to change that; additionally it looks like you might need to set the environment variable `LIBPATH` as well. Just go through the `SConstruct` to make sure you find all the needed variables (and admittedly, some of the ones I copy-pasted might not be used - I didn't check carefully yet).

Thanks! I think I had patched it already, but found it unneeded eventually. I will go through that once again.

**Comment by barracuda156** [comment]
UPD. Wait, this fails for me locally too.

**Comment by barracuda156** [comment]
@reneeotten Okay, this works:
```
post-patch {
    reinplace "s|/usr/local|${prefix}|" ${worksrcpath}/SConstruct
}

use_configure       no

build.cmd             ${prefix}/bin/scons
build.target
build.args             prefix=${prefix}
destroot.destdir    prefix=${destroot}${prefix}
```

**Comment by kencu** [comment]
> UPD. Wait, this fails for me locally too.

reinplace globally by adding “g” on the end. Otherwise just does 1st one it finds then stops. See many other portfiles.

**Comment by barracuda156** [comment]
@kencu Thank you!

@reneeotten Then:
```
post-patch {
    reinplace "s|/usr/local|${prefix}|g" ${worksrcpath}/SConstruct
}

use_configure       no

build.cmd           ${prefix}/bin/scons
build.target
build.args          prefix=${prefix}
destroot.destdir    prefix=${destroot}${prefix}
```

**Comment by kencu** [comment]
> @kencu Thank you!
> 
> @reneeotten Then:
> 
> ```
> post-patch {
>     reinplace "s|/usr/local|${prefix}|g" ${worksrcpath}/SConstruct
> }
`

no, that will not be acceptable to @ryandesign or any other admins. 

I meant use your patchfile like before to put the changes exactly where you meant to have them, and then reinplace them all like this:

```
post-patch {
    reinplace "s|@PREFIX@|${prefix}|g" ${worksrcpath}/SConstruct
}
```

It (probably) failed before because you only reinplaced the first one.

**Comment by kencu** [comment]
In 100% of cases, the blind reinplacing of text in a file will be overthrown by the admins of MacPorts. The only way it will slip through is if @ryandesign doesn't notice it, or if there is no other way to do the change.

I know homebrew uses 99.9% "inreplace" patches for their formulae. But you will see and admit that actual patches and then reinplacing specific placeholders is more accurate and less likely to do unpredictable things, and that is what MacPorts requires.

Otherwise somebody will just come along right behind you and redo it the right way, and who wants that kind of feedback all the time?

**Comment by barracuda156** [comment]
@kencu Okay, got it.

@reneeotten Then, take a patch from above: https://github.com/macports/macports-ports/pull/14994?notification_referrer_id=NT_kwDOBXwLlrMzNzE4NjE2OTExOjkyMDE1NTEw#issuecomment-1146042464

And have this in portfile (please notice `destroot.dir` part).
```
patchfiles      patch-sconstruct.diff

post-patch {
    reinplace "s|@PREFIX@|${prefix}|g" ${worksrcpath}/SConstruct
}

use_configure       no

build.cmd           ${prefix}/bin/scons
build.target
build.args          prefix=${prefix}
destroot.destdir    prefix=${destroot}${prefix}
```

**Comment by barracuda156** [comment]
> > @reneeotten Then, take a patch from above: #14994
> 
> @barracuda156 please make the changes based on @kencu his comments yourself. I was just added few commits fixing some of the remaining issues I noticed, but if there is more to do so.

@reneeotten Ok, will be done, but next month (I am physically away from all my PPC hardware atm).

**Comment by reneeotten** [comment]
@barracuda156 are you planning to finish this up or is this PR abandoned?

**Comment by barracuda156** [comment]
> @barracuda156 are you planning to finish this up or is this PR abandoned?

Nothing is abandoned :)
I will.

**Comment by barracuda156** [comment]
@reneeotten @mascguy Okay, this one fixed.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
