### PR TITLE
FileZilla,libfilezilla: update to the latest versions

### PR DESCRIPTION
**Pull request by yan12125**
###### Type(s)
- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.4 17E202
Xcode 9.3 9E145

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? (N/A)
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. Will merge when Travis finishes.

**Comment by yan12125** [comment]
From https://paste.macports.org/9568daf23c16:
```
string.cpp:205:10: error: thread-local storage is not supported for the current target
                static thread_local iconv_t_holder holder(wchar_t_encoding(), "UTF-8");
                       ^
string.cpp:266:10: error: thread-local storage is not supported for the current target
                static thread_local iconv_t_holder holder("UTF-8", wchar_t_encoding());
                       ^
```
Seems {clang < 800} should be blacklisted in libfilezilla, too, just like FileZilla.

**Comment by pmetzger** [comment]
@yan12125 I'll let you push those updates and lets see what Travis does next time.

**Comment by yan12125** [comment]
I pushed a try commit. If it fixes building on older systems, I'll squash it.

**Comment by pmetzger** [comment]
It looks both like the pastebin push failed _and_ like the thing that failed on the failed build was a dependent, so I'm merging. Do let us know if the buildbot has trouble, and thanks for your contributions to MacPorts, @yan12125!

**Comment by yan12125** [comment]
Builds are fine for 10.9+ (FileZilla uses an API available since 10.9), but lint errors should be fixed anyway. I'll do that later.

**Pull request merged**
