### PR TITLE
VLC : fix and upgrade to 3.0.11.1

### PR DESCRIPTION
**Pull request by RJVB**
VLC has become too hard to build "the MacPorts way" on enough supported
OS versions and esp. the newer versions. The official build runs on OS X
10.7 (!) and up. It may not take any of its dependencies from MacPorts
but nowadays it can be used as a dependency itself (the embedded libVLC).
This new port implementation installs the app bundle from the distribution
DMG and puts up symlinks to expose the shared libraries and headerfiles
under libexec/vlc3. Part of the headerfiles are installed from the source
tarball; the pkgconfig files are provided by the port.

VLC2: With this change there is no longer a need to impose an OS dependent
hard-wired choice of VLC2 or VLC(3); being able to install VLC2 in
addition to VLC(3) can have an interest (for watching streamed videos).

phonon-backend-vlc : don't depend on libVLC any longer (+vlc2 it still
makes sense to depend on libVLC2).

kde-extra-cmake-modules : upgrade to 5.75.0

###### Type(s)

- [ X] bugfix
- [X ] enhancement

###### Tested on

OS X 10.9

###### Verification 
Have you

- [x ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ x] tried a full install with `sudo port -vs install`?
- [ x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
You can click through the CI results to get log details, sometimes. I don't think we've succeeded in implementing it for GitHub Actions yet. For Azure, the log for VLC2 could not be uploaded:
```
POST https://paste.z0k.xyz/ giving up after 5 attempts
```
Maybe it was too big; I don't know what the limits are.

For libVLC2 the log was uploaded to https://paste.z0k.xyz/dc244e0e70eb, is only 2.3MB, and the error is:

```
Windows.m:434:9: error: use of undeclared identifier '_styleMask'
    if (_styleMask & NSResizableWindowMask) {
        ^
```

**Comment by ryandesign** [comment]
On 10.14, libVLC2's log is https://paste.z0k.xyz/4056c183603f and the error is:
```
2020-10-10 16:18:50.468 xcodebuild[44023:621078] Error Domain=com.apple.CoreSimulator.SimError Code=160 "Unable to determine SimDeviceSet, set_path=(null)" UserInfo={NSLocalizedDescription=Unable to determine SimDeviceSet, set_path=(null), NSUnderlyingError=0x7ffe296d6420 {Error Domain=NSPOSIXErrorDomain Code=12 "Cannot allocate memory" UserInfo={NSLocalizedFailureReason=Allocation or initialization failed., NSLocalizedDescription=Failed to initialize simulator device set.}}}
2020-10-10 16:18:50.470 xcodebuild[44023:621078]  iOSSimulator: [SimServiceContext defaultDeviceSetWithError:] returned nil (Error Domain=com.apple.CoreSimulator.SimError Code=160 "Failed to initialize simulator device set." UserInfo={NSLocalizedFailureReason=Failed to subscribe to notifications from CoreSimulatorService., NSLocalizedDescription=Failed to initialize simulator device set., NSUnderlyingError=0x7ffe296d6a40 {Error Domain=com.apple.CoreSimulator.SimError Code=160 "Unable to determine SimDeviceSet, set_path=(null)" UserInfo={NSLocalizedDescription=Unable to determine SimDeviceSet, set_path=(null), NSUnderlyingError=0x7ffe296d6420 {Error Domain=NSPOSIXErrorDomain Code=12 "Cannot allocate memory" UserInfo={NSLocalizedFailureReason=Allocation or initialization failed., NSLocalizedDescription=Failed to initialize simulator device set.}}}}}). Simulator device support disabled.
2020-10-10 16:18:51.094 xcodebuild[44023:621076] [MT] IDELogStore: Failed to open log store at /opt/local/var/macports/home/Library/Developer/Xcode/DerivedData/vlc-fhxkqmezcoxkyherltfvyhwtxzyn/Logs/Build
2020-10-10 16:18:51.094 xcodebuild[44023:621076] [MT] IDELogStore: Failed to open Build log store: Error Domain=IDEFoundationErrorDomain Code=1 "Unable to create log store directory at '/opt/local/var/macports/home/Library/Developer/Xcode/DerivedData/vlc-fhxkqmezcoxkyherltfvyhwtxzyn/Logs/Build': (513) You don’t have permission to save the file “Build” in the folder “Logs”." UserInfo={NSLocalizedDescription=Unable to create log store directory at '/opt/local/var/macports/home/Library/Developer/Xcode/DerivedData/vlc-fhxkqmezcoxkyherltfvyhwtxzyn/Logs/Build': (513) You don’t have permission to save the file “Build” in the folder “Logs”.}. User info: {
    NSLocalizedDescription = "Unable to create log store directory at '/opt/local/var/macports/home/Library/Developer/Xcode/DerivedData/vlc-fhxkqmezcoxkyherltfvyhwtxzyn/Logs/Build': (513) You don\U2019t have permission to save the file \U201cBuild\U201d in the folder \U201cLogs\U201d.";
}.
2020-10-10 16:18:51.283 xcodebuild[44023:621076] [MT] IDELogStore: Failed to open log store at /opt/local/var/macports/home/Library/Developer/Xcode/DerivedData/vlc-fhxkqmezcoxkyherltfvyhwtxzyn/Logs/Package
2020-10-10 16:18:51.283 xcodebuild[44023:621076] [MT] IDELogStore: Failed to open Package log store: Error Domain=IDEFoundationErrorDomain Code=1 "Unable to create log store directory at '/opt/local/var/macports/home/Library/Developer/Xcode/DerivedData/vlc-fhxkqmezcoxkyherltfvyhwtxzyn/Logs/Package': (513) You don’t have permission to save the file “Package” in the folder “Logs”." UserInfo={NSLocalizedDescription=Unable to create log store directory at '/opt/local/var/macports/home/Library/Developer/Xcode/DerivedData/vlc-fhxkqmezcoxkyherltfvyhwtxzyn/Logs/Package': (513) You don’t have permission to save the file “Package” in the folder “Logs”.}. User info: {
    NSLocalizedDescription = "Unable to create log store directory at '/opt/local/var/macports/home/Library/Developer/Xcode/DerivedData/vlc-fhxkqmezcoxkyherltfvyhwtxzyn/Logs/Package': (513) You don\U2019t have permission to save the file \U201cPackage\U201d in the folder \U201cLogs\U201d.";
}.
2020-10-10 16:18:51.329 xcodebuild[44023:621076] [MT] IDELogStore: Failed to open log store at /opt/local/var/macports/home/Library/Developer/Xcode/DerivedData/vlc-fhxkqmezcoxkyherltfvyhwtxzyn/Logs/Test
2020-10-10 16:18:51.329 xcodebuild[44023:621076] [MT] IDELogStore: Failed to open Test log store: Error Domain=IDEFoundationErrorDomain Code=1 "Unable to create log store directory at '/opt/local/var/macports/home/Library/Developer/Xcode/DerivedData/vlc-fhxkqmezcoxkyherltfvyhwtxzyn/Logs/Test': (513) You don’t have permission to save the file “Test” in the folder “Logs”." UserInfo={NSLocalizedDescription=Unable to create log store directory at '/opt/local/var/macports/home/Library/Developer/Xcode/DerivedData/vlc-fhxkqmezcoxkyherltfvyhwtxzyn/Logs/Test': (513) You don’t have permission to save the file “Test” in the folder “Logs”.}. User info: {
    NSLocalizedDescription = "Unable to create log store directory at '/opt/local/var/macports/home/Library/Developer/Xcode/DerivedData/vlc-fhxkqmezcoxkyherltfvyhwtxzyn/Logs/Test': (513) You don\U2019t have permission to save the file \U201cTest\U201d in the folder \U201cLogs\U201d.";
}.
2020-10-10 16:18:51.339 xcodebuild[44023:621076] Couldn't create intermediates directory: You don’t have permission to save the file “Intermediates.noindex” in the folder “Build”.
2020-10-10 16:18:52.082 xcodebuild[44023:621076] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-15715/IDEFoundation/Buildables/IDEWorkspaceArena.m:1131
Details:  Failed to create workspace arena at <DVTFilePath:0x7ffe29c78110:'/opt/local/var/macports/home/Library/Developer/Xcode/DerivedData/vlc-fhxkqmezcoxkyherltfvyhwtxzyn'>: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “vlc-fhxkqmezcoxkyherltfvyhwtxzyn” in the folder “DerivedData”." UserInfo={NSFilePath=/opt/local/var/macports/home/Library/Developer/Xcode/DerivedData/vlc-fhxkqmezcoxkyherltfvyhwtxzyn, NSUnderlyingError=0x7ffe296d10e0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
Object:   <IDEWorkspaceArena: 0x7ffe29a30fb0>
Method:   -createWorkspaceArenaFolderIfNecessary
Thread:   <NSThread: 0x7ffe26c15750>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
note: Using new build system
error: Build service could not start build operation: unknown error while handling message: fopen(/opt/local/var/macports/home/Library/Developer/Xcode/DerivedData/vlc-fhxkqmezcoxkyherltfvyhwtxzyn/Build/Intermediates.noindex/XCBuildData/PIFCache/WORKSPACE@v11_mod=(null)_hash=68621a23a9f7c91ea2b8b771166657f4_subobjects=B438BC4AD0E1FFD02C0BA7C281531516-Workspace.lock, wb): No such file or directory (2)
```
This looks like https://trac.macports.org/ticket/57137.

**Comment by kencu** [comment]
rene, I plan to push this tomorrow unless you feel it should not be.

this is your port, and what you say goes here, as it's waaaaaay too complicated for anyone else to take over.

**Comment by RJVB** [comment]
The installed results are still working fine for me, and I see no reason why the install shouldn't anymore since my last changes. So I'd say go ahead, and we'll address any issues as they appear.

I'm trying to catch up with my maintainer "duties", not making much progress sadly...

**Comment by kencu** [comment]
has conflicts now -- if there were conflicts yesterday, I didn't notice I guess. So 'no bueno' until those get sorted.

**Comment by RJVB** [comment]
>has conflicts now -- if there were conflicts yesterday, I didn't notice I guess. So 'no bueno' until those get sorted.

 I also didn't notice them this morning before replying. Strange... and annoying since it's been long enough that I'll probably have to scratch my head a while to fix the conflicts.

**Comment by kencu** [comment]
I fixed this up for you, Rene. I'm trying to get the PR queue down to < 15.

**Comment by RJVB** [comment]
Thanks. I'm hopeless in organising my time ATM, way too many distractions around the house that always seems to be more urgent than anything else...

**Comment by kencu** [comment]
Dying:
```
021-02-05T10:46:29.8834570Z CMake Warning at CMakeLists.txt:9 (find_package):
2021-02-05T10:46:29.8835940Z   Could not find a configuration file for package "ECM" that is compatible
2021-02-05T10:46:29.8842080Z   with requested version "5.60".
2021-02-05T10:46:29.8842690Z 
2021-02-05T10:46:29.8843640Z   The following configuration files were considered but not accepted:
2021-02-05T10:46:29.8844400Z 
2021-02-05T10:46:29.8845200Z     /opt/local/share/ECM/cmake/ECMConfig.cmake, version: 5.59.0
2021-02-05T10:46:29.8845880Z 
2021-02-05T10:46:29.8846370Z 
2021-02-05T10:46:29.8847120Z 
2021-02-05T10:46:29.8847910Z CMake Error at CMakeLists.txt:16 (include):
2021-02-05T10:46:29.8848730Z   include could not find load file:
2021-02-05T10:46:29.8849300Z 
2021-02-05T10:46:29.8850070Z     KDEInstallDirs
2021-02-05T10:46:29.8850640Z 
2021-02-05T10:46:29.8851110Z 
2021-02-05T10:46:29.8851830Z CMake Error at CMakeLists.txt:17 (include):
2021-02-05T10:46:29.8852660Z   include could not find load file:
2021-02-05T10:46:29.8853460Z 
2021-02-05T10:46:29.8854090Z     ECMPoQmTools
2021-02-05T10:46:29.8854620Z 
2021-02-05T10:46:29.8855100Z 
2021-02-05T10:46:29.8855920Z CMake Error at CMakeLists.txt:18 (include):
2021-02-05T10:46:29.8856750Z   include could not find load file:
2021-02-05T10:46:29.8857310Z 
2021-02-05T10:46:29.8857970Z     KDECMakeSettings
2021-02-05T10:46:29.8858530Z 
2021-02-05T10:46:29.8858990Z 
2021-02-05T10:46:29.8859710Z CMake Error at CMakeLists.txt:19 (include):
2021-02-05T10:46:29.8860520Z   include could not find load file:
2021-02-05T10:46:29.8861090Z 
2021-02-05T10:46:29.8861800Z     KDECompilerSettings
2021-02-05T10:46:29.8862380Z 
2021-02-05T10:46:29.8862850Z 
2021-02-05T10:46:29.8863580Z CMake Error at CMakeLists.txt:20 (include):
2021-02-05T10:46:29.8864400Z   include could not find load file:
2021-02-05T10:46:29.8865620Z 
2021-02-05T10:46:29.8866440Z     ECMSetupVersion
2021-02-05T10:46:29.8867030Z 
2021-02-05T10:46:29.8867520Z 
2021-02-05T10:46:29.8986820Z CMake Warning at CMakeLists.txt:23 (find_package):
2021-02-05T10:46:29.8988030Z   Could not find a configuration file for package "Phonon4Qt5" that is
2021-02-05T10:46:29.8989070Z   compatible with requested version "4.10.60".
2021-02-05T10:46:29.8989700Z 
2021-02-05T10:46:29.8990560Z   The following configuration files were considered but not accepted:
2021-02-05T10:46:29.8991610Z 
2021-02-05T10:46:29.8992640Z     /opt/local/lib/cmake/phonon4qt5/Phonon4Qt5Config.cmake, version: 4.10.3
2021-02-05T10:46:29.8993440Z 
2021-02-05T10:46:29.8993910Z 
2021-02-05T10:46:29.8994390Z 
2021-02-05T10:46:29.9131890Z -- Could NOT find Phonon4Qt5Experimental (missing: Phonon4Qt5Experimental_DIR)
2021-02-05T10:46:30.0469560Z -- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.29.2") 
2021-02-05T10:46:30.0478740Z -- Checking for module 'libvlc'
2021-02-05T10:46:30.1116290Z --   Found libvlc, version 3.0.11.1
2021-02-05T10:46:30.2796080Z -- Found LibVLC include-dir path: /opt/local/libexec/vlc3/include
2021-02-05T10:46:30.2797390Z -- Found LibVLC library path:/opt/local/libexec/vlc3/lib/libvlc.dylib
2021-02-05T10:46:30.2798600Z -- Found LibVLCcore library path:/opt/local/libexec/vlc3/lib/libvlccore.dylib
2021-02-05T10:46:30.2799700Z -- Found LibVLC version: 3.0.11.1 (searched for: 0.0)
2021-02-05T10:46:30.2800360Z CMake Error at CMakeLists.txt:45 (ecm_setup_version):
2021-02-05T10:46:30.2800990Z   Unknown CMake command "ecm_setup_version".
2021-02-05T10:46:30.2801340Z 
2021-02-05T10:46:30.2801530Z 
2021-02-05T10:46:30.2802360Z -- Configuring incomplete, errors occurred!
2021-02-05T10:46:30.2804110Z See also "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_audio_phonon-backend-vlc/phonon-backend-vlc-qt5/work/build/CMakeFiles/CMakeOutput.log".

```

**Comment by kencu** [comment]
OK, Rene -- you've put 1.2 million hours into this. Let's commit this, get it off the table for(ever) now, and deal with any residual tweaks later on.

Thanks for sticking with this so long.

**Comment by RJVB** [comment]
Apparently there are still issues on 10.11, grrr. Annoyingly it does take a long time for me (scroll, click, wait, repeat) to find the cause, like the required phonon update (why that wasn't a problem on the other OS versions stymies me)...

**Pull request merged**
