### PR TITLE
kotlin: Update to version 1.0.5

### PR DESCRIPTION
**Pull request by breun**
Announcement: https://blog.jetbrains.com/kotlin/2016/11/kotlin-1-0-5-is-here/

Changelog: https://github.com/JetBrains/kotlin/blob/1.0.5/ChangeLog.md

### CODE REVIEW

**Comment by raimue** [comment]
Please follow [CommitMessages](https://trac.macports.org/wiki/CommitMessages) for the commit message format. For example:

    kotlin: Update to version 1.0.5

The patch itself looks good to me.

**Comment by breun** [comment]
@raimue I think I just changed the commit message. Hopefully it's ok now, I'm not a Git expert yet.

**Comment by raimue** [comment]
Not quite, you added merge commits to the pull request branch, where you should have edited the existing commit and rebased on top of the current master. I also did not notice before that you used your master branch for the pull request. Now all changes you do on this branch will turn up here. Always create a separate branch for each pull request.

To fix this, please follow these steps. This assumes that the remote "origin" is the macports/macports-ports repository and "breun" is breun/macports-ports. Use `git remote -v` to verify this. If not, adapt accordingly.

   # Create a new branch, based on your local master branch
   git checkout -b kotlin-1.0.5 master
   # This will open your editor to edit the branch interactively
   git rebase -i origin/master
   # Leave the first commit as "pick", change the other two to "squash". Save and exit.
   # When executing this, the editor will open again with the commit message. Edit, save and exit.
   # Verify you now have a single new commit on this branch, with the changes you want:
   git log origin/master..kotlin-1.0.5
   git diff origin/master..kotlin-1.0.5
   # Push your new branch to your personal GitHub repository
   git push breun kotlin-1.0.5
  
Now change the base branch of this pull request on GitHub to the new branch named kotlin-1.0.5:
https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/

**Comment by breun** [comment]
Thanks for walking me through this. I wasn't on planning on doing any other changes on my master branch for now, but I've gone and created a branch anyway. The last command should be `git push origin kotlin-1.0.5` I guess?

So I've created the branch (https://github.com/breun/macports-ports/tree/kotlin-1.0.5), but I can't seem to change the base branch of this pull request. If I press the edit button on the top right of this pull request I can only change the branch I want the pull request to be merged into, but I can't seem to change the 'from breun:master' part. Am I missing something?

**Comment by raimue** [comment]
The last command depends on which remote on your local copy names which repository. You are only allowed to push to your own repository on GItHub, so this has to match your breun/macports-ports and you might be right.

Apparently I understood the GitHub lingo wrong and "base branch" is the branch where changes are meant to be merged to. In this case, you will need to do `git push --force origin kotlin-1.0.5:master` to update this pull request (or close this one and reopen a new pull request from another branch).

Sorry for the confusion, I am also new to be on the receiving side of pull requests.

**Comment by breun** [comment]
I ran `git push --force origin kotlin-1.0.5:master`. Is it ok now?

**Comment by raimue** [comment]
I corrected the non-squashed commit message and pushed the result to master.

Thanks for your contribution!

**Pull request closed without merging**
