### PR TITLE
Poppler update 20.12.01 to 21.01.0

### PR DESCRIPTION
**Pull request by michaelld**
#### Description

update Poppler from 20.12.01 to 21.01.0 & rev-bump all dependencies as found via `port echo depends:poppler`.
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.2 20D5029f
Xcode 12.3 12C33

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by michaelld** [comment]
Ping on this PR. Since the port is `openmaintainer` I'll merge this in 2 more days unless it is already merged or there is discussion otherwise (after rebasing to fix the conflict, of course). It's a pretty trivial update, but I do want to give the port owners plenty of time to handle this PR themselves.

**Comment by Schamschula** [comment]
`littleutils` uses `pdftocairo`. Updates to poppler should not require a rebuild.

**Comment by michaelld** [comment]
> `littleutils` uses `pdftocairo`. Updates to poppler should not require a rebuild.

According to `port info littleutils`, it has a library dependency on `poppler`, and hence if it truly links to the poppler ABI then it will require a rev-bump because the ABI changes names in this PR.
```
% port info littleutils
littleutils @1.2.3 (sysutils)
Variants:             python37, (+)python38, universal

Description:          The littleutils include a duplicate file finder (repeats), image optimizers
                      (opt-jpg, opt-png, opt-gif, recomp-jpg), file rename tools (lowercase, uppercase,
                      pren), archive recompressors (to-gzip, to-bzip, to-7zip, to-lzma, to-lzip, to-xz),
                      a tempfile utility (tempname), file property tools (filedate, filemode, filenode,
                      fileown, filesize, and lrealpath), and others.
Homepage:             https://sourceforge.net/projects/littleutils/

Extract Dependencies: xz
Library Dependencies: bash, bzip2, dash, file, gettext, ghostscript, gifsicle, gzip, img2pdf, imlib2,
                      lzip, lzma, lzop, p7zip, perl5, pngcrush, poppler, xz, zstd, python38
Platforms:            darwin
License:              GPL-3+ and ijg and permissive
Maintainers:          Email: mps@macports.org, GitHub: Schamschula
                      Policy: openmaintainer
```

**Comment by michaelld** [comment]
As noted in the commit message, I look the output of `port echo depends:poppler` and did a rev-bump on those ports. This method might bring in more ports than required. If there's an issue with ports that `port` says depend on poppler, then let's fix those ports or `port` itself.

**Comment by Schamschula** [comment]
The configure script checks for pdftocairo:

> checking for pdftocairo... yes

however, the pdf related utilities were never installed. I've now fixed that by adding the `install-extras` target.

I then checked if these files are binaries. No, they are bash scripts calling the `pdftocairo` binary, among others.

As the configure script checks for the presence of these binaries, I don't think moving these dependencies to `depends_run` will work.

**Comment by dliessi** [comment]
As far as I understand, the argument of `depends:` is a regular expression that is matched against the dependencies, so `depends:poppler` matches ports depending on ports whose name contains `poppler` instead of only those depending on the port `poppler`.

The ports `frescobaldi` and `py-qpageview` depend on `poppler` only via `py-poppler-qt4` and `py-poppler-qt5`, so there is no need to revbump them.

I agree with the revbump of my other ports, i.e. `DiffPDF`, `py-poppler-qt4` and `py-poppler-qt5`.

**Comment by NicosPavlov** [comment]
No visible problem with pdf2djvu, so the upgrade is all fine with me.

**Comment by pietvo** [comment]
`diff-pdf` compiles and runs fine with the new `poppler`.
Actually, it just runs fine even with no recompilation, because it links with `libpoppler-glib.8.19.0.dylib`, which is still part of the new `poppler` port. Although the file itself is changed, the file name is still the same, but it links with the new `libpoppler.106.0.0.dylib` instead of `libpoppler.105.0.0.dylib`.
So the change is transparent to `diff-pdf`.

**Comment by medoc92** [comment]
Recoll only uses pdftotext, so I guess that nothing needs to be done.

**Comment by michaelld** [comment]
I've heard no direct issues with merging this once it's rebased. I will try to take into account the comments about ports that actually don't require the rev-bump, but it's likely I'll mess one or more of those up ... so thanks in advance for your forgiveness & luckily it's not that big of a deal :)

**Comment by kimuraw** [comment]
@michaelld, I deleted rb-gnome and rb-poppler from ports at 820ff9c008bea9f7a2883806d26ac5d5df4a6cd0.
these ports were broken.

We need not revbump for rb-gnome and rb-poppler.

**Comment by kencu** [comment]
many conflicts now. I think @dbevans is getting just too busy to manage these PRs, so either we consider just not doing any more PRs involving Dave's ports, or we actually do start committing them after the 3 day timeout (although I'm not sure we have the stomach for that either).

So -- no more PRs for ports that Dave maintains? Hate to see everyone waste their time.

**Comment by michaelld** [comment]
I need to rebase this one. Given that lack of response, once this is rebased & CI passes, we can merge quickly. Beyond this PR - which is partly meant to fix rev-bumps that didn't happen last time -- I think we should in general leave Dave's ports alone per his request for doing updates.

**Comment by michaelld** [comment]
Closing as this is horribly outdated & needs to be rebased. Will try again with the most recent release when I get a chance.

**Pull request closed without merging**
