### PR TITLE
upx-devel: 20161114 -> 20161130

### PR DESCRIPTION
**Pull request by l2dy**
devel was merged to master.

### CODE REVIEW

**Comment by larryv** [comment]
Thanks. In future updates, you don't have to mention the old version.

**Comment by l2dy** [comment]
I thought more information would be better. Thanks for the advice.

**Comment by larryv** [comment]
"Update to" is just our convention, and it reads better. If someone wants to know what the previous version is, they are free to look at the diff.

**Comment by l2dy** [comment]
I've seen "Update to", "update to version" and "update to" + version number, which one is preferred?

**Comment by larryv** [comment]
I prefer "Update to", but we don't really care much about capitalization. I don't know why some of us say "version x.y.z"; the word "version" is not useful.

**Pull request merged**
