### PR TITLE
openjdk-source: transition to new ports

### PR DESCRIPTION
**Pull request by usersxx**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by usersxx** [comment]
@breun, This pr is based on `openjdk6` port on [OpenJDK's official BSD port](https://wiki.openjdk.java.net/display/BSDPort)

**Comment by usersxx** [comment]
@mascguy Can you merge this pr

**Comment by usersxx** [comment]
> Notifying maintainers: @breun for port openjdk-distributions, openjdk11, openjdk13, openjdk15, openjdk17, openjdk8.

?

**Comment by usersxx** [comment]
> > Notifying maintainers: @breun for port openjdk-distributions, openjdk11, openjdk13, openjdk15, openjdk17, openjdk8.
> 
> ?

[`openjdk8`](https://github.com/macports/macports-ports/blob/2181bf72f9a67d7652446aeac5c703f7a4006911/java/openjdk8/Portfile#L16), [`openjdk11`](https://github.com/macports/macports-ports/blob/2181bf72f9a67d7652446aeac5c703f7a4006911/java/openjdk11/Portfile#L13), [`openjdk13`](https://github.com/macports/macports-ports/blob/2181bf72f9a67d7652446aeac5c703f7a4006911/java/openjdk13/Portfile#L13), [`openjdk15`](https://github.com/macports/macports-ports/blob/2181bf72f9a67d7652446aeac5c703f7a4006911/java/openjdk15/Portfile#L13) as well as [`openjdk17`](https://github.com/macports/macports-ports/blob/2181bf72f9a67d7652446aeac5c703f7a4006911/java/openjdk17/Portfile#L13) are set to `nomaintainer `

**Comment by breun** [comment]
> > > Notifying maintainers: @breun for port openjdk-distributions, openjdk11, openjdk13, openjdk15, openjdk17, openjdk8.
> > 
> > 
> > ?
> 
> [`openjdk8`](https://github.com/macports/macports-ports/blob/2181bf72f9a67d7652446aeac5c703f7a4006911/java/openjdk8/Portfile#L16), [`openjdk11`](https://github.com/macports/macports-ports/blob/2181bf72f9a67d7652446aeac5c703f7a4006911/java/openjdk11/Portfile#L13), [`openjdk13`](https://github.com/macports/macports-ports/blob/2181bf72f9a67d7652446aeac5c703f7a4006911/java/openjdk13/Portfile#L13), [`openjdk15`](https://github.com/macports/macports-ports/blob/2181bf72f9a67d7652446aeac5c703f7a4006911/java/openjdk15/Portfile#L13) as well as [`openjdk17`](https://github.com/macports/macports-ports/blob/2181bf72f9a67d7652446aeac5c703f7a4006911/java/openjdk17/Portfile#L13) is set to `nomaintainer`

[I am currently the maintainer for those ports](https://github.com/macports/macports-ports/blob/master/java/openjdk-distributions/Portfile#L7), so that's why I get notified. Could you please first discuss changes to ports maintained by others before making the changes?

I think it's a regression to switch existing users to ports that are set to `nomaintainer`. If you don't intend to maintain these new ports yourself, then I think we should keep using the current maintained implementations for these ports.

I think existing users of these ports might also be surprised to suddenly get a different OpenJDK implementation when updating, but that might be ok if the change is not breaking in practice.

**Comment by usersxx** [comment]
> I think it's a regression to switch existing users to ports that are set to `nomaintainer`. If you don't intend to maintain these new ports yourself, then I think we should keep using the current maintained implementations for these ports.
> 
> I think existing users of these ports might also be surprised to suddenly get a different OpenJDK implementation when updating, but that might be ok if the change is not breaking in practice.

I am not a active user so I had set it to `nomaintainer` though I am going to update these ports and contributions are always welcome. The change is not totally breaking. It is just building the port or simply [downloading the files from macports archives](https://trac.macports.org/wiki/FAQ#fromsource). The files built will be just little bit different as vendors provided openjdk are built from modified source code

**Comment by usersxx** [comment]
> I think it's a regression to switch existing users to ports that are set to `nomaintainer`. If you don't intend to maintain these new ports yourself, then I think we should keep using the current maintained implementations for these ports.

Based on `openjdk8` and `openjdk11` meta subports, these meta ports install different types of OpenJDK where Eclipse Temurin is built from little bit modified OpenJDK Source code whereas Azul Zulu built from totally modified OpenJDK Source code and based on Macports, a port should have [Reproducible Builds](https://trac.macports.org/wiki/ReproducibleBuilds) which states that if a user installs a port today, and another user installs the port tomorrow, and the Portfile has not been changed in between, both users should get the same software (allowing of course for possible differences due to architecture or OS X version).

**Comment by breun** [comment]
> I am not a active user so I had set it to `nomaintainer` though I am going to update these ports and contributions are always welcome.

If nobody is committing to keeping these new ports up to date, then I don't think we should be making these the default `openjdk${version}` ports (which also get installed when the `java.version` property is used by a Portfile that uses the `java` PortGroup).

**Comment by breun** [comment]
> Based on `openjdk8` and `openjdk11` meta subports, these meta ports install different types of OpenJDK where Eclipse Temurin is built from little bit modified OpenJDK Source code whereas Azul Zulu built from totally modified OpenJDK Source code and based on Macports, a port should have [Reproducible Builds](https://trac.macports.org/wiki/ReproducibleBuilds) which states that if a user installs a port today, and another user installs the port tomorrow, and the Portfile has not been changed in between, both users should get the same software (allowing of course for possible differences due to architecture or OS X version).

I know that that is how it works. AdoptOpenJDK used to be the default, but that became Eclipse Temurin, and then Apple released the ARM64 processors, but there are no Eclipse Temurin builds yet (and Azul has MTS releases which are supported longer than Eclipse Temurin releases), so that is why Azul Zulu was made the default for ARM64. I don't know what this has to do with reproducible builds, and I'm not sure what point you want to make.

**Comment by usersxx** [comment]
> AdoptOpenJDK used to be the default, but that became Eclipse Temurin, and then Apple released the ARM64 processors, but there are no Eclipse Temurin builds for ARM64 yet and Azul has MTS releases which are supported longer than Eclipse Temurin releases, so that is why Azul Zulu was made the default for ARM64. I don't know what this has to do with reproducible builds, and I'm not sure what point you want to make.

It has to do with [Reproducible Builds](https://trac.macports.org/wiki/ReproducibleBuilds) as the `openjdk8` and `openjdk11` distributes different software. My few points are:

- There can be of course for possible differences due to architecture or OS X version but distributing different software isn't allowed at all.

**Comment by usersxx** [comment]
> If nobody is committing to keeping these new ports up to date, then I don't think we should be making these the default `openjdk${version}` ports (which also get installed when the `java.version` property is used by a Portfile that uses the `java` PortGroup).

Actually I think we should make these oirt . These port follow old format found at [Official OpenJDK wiki](https://wiki.openjdk.java.net/display/BSDPort/Main) because most users who have found this page wouldn't find `openjdk6`, so they would probably try for newer versions or [find it](https://ports.macports.org/) and install it but wouldn't get the same type of OpenJDK built from sources as distributed with [`openjdk6`](https://github.com/macports/macports-ports/blob/release_2_1_0-archive/java/openjdk6/Portfile#L238) port, so I would suggest to follow the official format format of the [`openjdk6`](https://wiki.openjdk.java.net/display/BSDPort/Main) to distribute OpenJDK

**Comment by usersxx** [comment]
> Actually I think we should make these ports the default `openjdk${version}` ports. These ports follow old format found at [Official OpenJDK wiki](https://wiki.openjdk.java.net/display/BSDPort/Main) because most users who have found this page wouldn't find `openjdk6`, so they would probably try for newer versions or [find it](https://ports.macports.org/) and install it but wouldn't get the same type of OpenJDK built from sources as distributed with [`openjdk6`](https://github.com/macports/macports-ports/blob/release_2_1_0-archive/java/openjdk6/Portfile#L238) port, so I would suggest to follow the official formal format of the [`openjdk6`](https://wiki.openjdk.java.net/display/BSDPort/Main) to distribute OpenJDK

Moreover, [Official MacOSX port of OpenJDK](https://wiki.openjdk.java.net/display/MacOSXPort) provides tutorial to build OpenJDK and not distribute pre-built binaries, so these ports would be great.

**Comment by usersxx** [comment]
> AdoptOpenJDK used to be the default, but that became Eclipse Temurin,

?

**Comment by usersxx** [comment]
> > AdoptOpenJDK used to be the default, but that became Eclipse Temurin
> 
> ?

What do you mean ?

**Comment by usersxx** [comment]
> > AdoptOpenJDK used to be the default, but that became Eclipse Temurin
> 
> What do you mean ?

I don't think AdoptOpenJDK was ever default. It began providing OpenJDK 8 or later and not OpenJDK 6 or at least OpenJDK 7. Even Azul Zulu began providing OpenJDK 7 to mac at JDK7u55 release of OpenJDK source. Apple's provided java was default. Apple provided JDK was the default JDK as Apple provided JDK per macOS version aka, for [Mac OS X 10.3](https://support.apple.com/kb/DL280?viewlocale=en_US&locale=en_US), [Mac OS X 10.4](https://support.apple.com/kb/DL847?viewlocale=en_US&locale=en_US), [Mac OS X 10.5](https://support.apple.com/kb/DL1359?viewlocale=en_US&locale=en_US), [Mac OS X 10.6](https://support.apple.com/kb/DL1573?viewlocale=en_US&locale=en_US) and [Mac OS X 10.7 up to MacOS 10.13](https://support.apple.com/kb/DL1572?viewlocale=en_US&locale=en_US) until it got replaced by Oracle JDK.

**Comment by usersxx** [comment]
> > AdoptOpenJDK used to be the default, but that became Eclipse Temurin
> 
> What do you mean ?

I don't think AdoptOpenJDK was ever default. It began providing OpenJDK 8 or later and not OpenJDK 6 or at least OpenJDK 7. Even Azul Zulu began providing OpenJDK 7 to mac at JDK7u55 release of OpenJDK source. Apple's provided java was default. Apple provided JDK was the default JDK as Apple provided JDK per macOS version aka, for [Mac OS X 10.3](https://support.apple.com/kb/DL280?viewlocale=en_CA&locale=en_CA), [Mac OS X 10.4](https://support.apple.com/kb/DL847?viewlocale=en_CA&locale=en_CA), [Mac OS X 10.5](https://support.apple.com/kb/DL1359?viewlocale=en_CA&locale=en_CA), [Mac OS X 10.6](https://support.apple.com/kb/DL1573?viewlocale=en_CA&locale=en_CA) and [Mac OS X 10.7 up to MacOS 10.13](https://support.apple.com/kb/DL1572?viewlocale=en_CA&locale=en_CA) until it got replaced by Oracle JDK.

**Comment by usersxx** [comment]
> > > AdoptOpenJDK used to be the default, but that became Eclipse Temurin
> > 
> > 
> > ?
> 
> I don't think AdoptOpenJDK was ever default. It began providing OpenJDK 8 or later and not OpenJDK 6 or at least OpenJDK 7. Even Azul Zulu began providing OpenJDK 7 to mac at JDK7u55 release of OpenJDK source. Apple's provided java was default. Apple provided JDK was the default JDK as Apple provided JDK per macOS version aka, for [Mac OS X 10.3](https://support.apple.com/kb/DL280?viewlocale=en_CA&locale=en_CA), [Mac OS X 10.4](https://support.apple.com/kb/DL847?viewlocale=en_CA&locale=en_CA), [Mac OS X 10.5](https://support.apple.com/kb/DL1359?viewlocale=en_CA&locale=en_CA), [Mac OS X 10.6](https://support.apple.com/kb/DL1573?viewlocale=en_CA&locale=en_CA) and [Mac OS X 10.7 up to MacOS 10.13](https://support.apple.com/kb/DL1572?viewlocale=en_CA&locale=en_CA) until it got replaced by Oracle JDK.

Only for Mac OS

**Comment by usersxx** [comment]
> AdoptOpenJDK used to be the default, but that became Eclipse Temurin

For MacPorts, OpenJDK built from source was default and officially supported by OpenJDK community

**Comment by usersxx** [comment]
@mascguy, What do you think ?

**Comment by usersxx** [comment]
@ryandesign Can you check the portfile

**Comment by breun** [comment]
> Moreover, [Official MacOSX port of OpenJDK](https://wiki.openjdk.java.net/display/MacOSXPort) provides tutorial to build OpenJDK and not distribute pre-built binaries, so these ports would be great.

I agree that it would be nice to offer these builds by default, but only when they have a maintainer in the MacPorts project.

**Comment by breun** [comment]
> I don't think AdoptOpenJDK was ever default.

It used to be the default when you installed `openjdk*` from MacPorts.

**Comment by usersxx** [comment]
> > I don't think AdoptOpenJDK was ever default.
> 
> AdoptOpenJDK used to be the default when you installed `openjdk*` from MacPorts.

Yea, It used to be but before that, it was build from source when the first `openjdk*` port was introduced

**Comment by usersxx** [comment]
> > I don't think AdoptOpenJDK was ever default.
> 
> AdoptOpenJDK used to be the default when you installed `openjdk*` from MacPorts.

It used to be build from source when [`openjdk6`](https://github.com/macports/macports-ports/commit/5cf88ae8439f3976fcd70b6308e30e5d99762d47) was introduced until @landonf didn't introduce `openjdk7`, `openjdk8`, `openjdk9` and finally `openjdk10` after which the [`openjdk8` meta port](https://github.com/macports/macports-ports/commit/a9c8334be20ea49ed7ac8dd7630aa3d12bd48285) was created where AdoptOpenJDK was used.

**Comment by usersxx** [comment]
> > Moreover, [Official MacOSX port of OpenJDK](https://wiki.openjdk.java.net/display/MacOSXPort) provides tutorial to build OpenJDK and not distribute pre-built binaries, so these ports would be great.
> 
> I agree that it would be nice to switch the `openjdk{version}` ports to install these 'from source' builds, but only when those new ports have a maintainer in the MacPorts project. Introducing these ports as replacements with `nomaintainer` would be a regression in my opinion.

Added myself as maintainer

**Comment by usersxx** [comment]
@mascguy What do you think?

**Comment by mascguy** [comment]
> @mascguy What do you think?

Just want to be sure there's agreement and consensus between you and @breun.

Nils, are you fine with this, now that the maintainer aspect has been addressed?

**Comment by breun** [comment]
> Nils, are you fine with this, now that the maintainer aspect has been addressed?

Yes, fine with me. 👍

**Comment by usersxx** [comment]
> > Nils, are you fine with this, now that the maintainer aspect has been addressed?
> 
> Yes, fine with me. 👍

Good

**Comment by usersxx** [comment]
> > > Nils, are you fine with this, now that the maintainer aspect has been addressed?
> > 
> > 
> > Yes, fine with me. 👍
> 
> Good

I though if it would affect other few other ports

**Review by mascguy — APPROVED** [review]

**Comment by cabelitos** [comment]
Hello @usersxx and @breun I just noticed that with this change there's no more openjdk11-zulu. Since I'm running macports on Apple Silicon (ARM64) it's a huge blow on my side.
Do you guys plan to restore it?
Unfortunately to me, it's not feasible to update to a newer JDK at this point.

**Comment by usersxx** [comment]
> Hello @usersxx and @breun I just noticed that with this change there's no more openjdk11-zulu. Since I'm running macports on Apple Silicon (ARM64) it's a huge blow on my side. Do you guys plan to restore it? Unfortunately to me, it's not feasible to update to a newer JDK at this point.
> 
> Thank you very much for your help

Yes, I am planning to introduce arm64 build. Currently OpenJDK 11.0.15 or later would build on arm but with patches, I can introduce arm build for OpenJDK 11.0.14.1.

**Comment by cabelitos** [comment]
@usersxx Awesome, please let me know if I can help you with anything.

**Comment by usersxx** [comment]
> @usersxx Awesome, please let me know if I can help you with anything.

You can follow all the steps mentioned mentioned:

1. run `sudo mkdir -p /opt/local/repo/openjdkXX-fix-configure-flags` in terminal
2. run `cd /opt/local/repo/openjdkXX-fix-configure-flags` in terminal
3. run `git clone --single-branch --branch openjdkXX-fix-configure-flags https://github.com/usersxx/macports-ports.git openjdk11-arm-port` in terminal
4. run `cd /opt/local/repo/openjdkXX-fix-configure-flags/openjdk11-arm-port` in terminal
5. run `sudo mkdir -p /opt/local/repo/openjdkXX-fix-configure-flags/openjdk11-arm/java` in terminal
6. run `cp /opt/local/repo/openjdkXX-fix-configure-flags/openjdk11-arm-port/java/openjdk11 /opt/local/repo/openjdkXX-fix-configure-flags/openjdk11-arm/java` in terminal
7.  run `sudo rm -rf /opt/local/repo/openjdkXX-fix-configure-flags/openjdk11-arm-port` in terminal
8. run `cd /opt/local/repo/openjdkXX-fix-configure-flags/openjdk11-arm` in terminal
9. run `portindex` in terminal
10. run `cp /opt/local/etc/macports/sources.conf /opt/local/repo/openjdkXX-fix-configure-flags` in terminal
11. run `open -e /opt/local/repo/openjdkXX-fix-configure-flags/sources.conf` in terminal
12. add "file:///opt/local/repo/openjdkXX-fix-configure-flags/openjdk11-arm [nosync]" as new line just before "rsync://rsync.macports.org/macports/release/tarballs/ports.tar [default]"
13. run `sudo rm /opt/local/etc/macports/sources.conf` in terminal
14. run `sudo cp  /opt/local/repo/openjdkXX-fix-configure-flags/sources.conf /opt/local/etc/macports` in terminal
15. run `sudo port install openjdk11` in terminal

**Comment by usersxx** [comment]
> > @usersxx Awesome, please let me know if I can help you with anything.
> 
> @cabelitos, You can follow all the steps mentioned mentioned and test the `openjdk11` port in your Apple Silicon Mac:
> 
> 1. run `sudo mkdir -p /opt/local/repo/openjdkXX-fix-configure-flags` in terminal
> 2. run `cd /opt/local/repo/openjdkXX-fix-configure-flags` in terminal
> 3. run `git clone --single-branch --branch openjdkXX-fix-configure-flags https://github.com/usersxx/macports-ports.git openjdk11-arm-port` in terminal
> 4. run `cd /opt/local/repo/openjdkXX-fix-configure-flags/openjdk11-arm-port` in terminal
> 5. run `sudo mkdir -p /opt/local/repo/openjdkXX-fix-configure-flags/openjdk11-arm/java` in terminal
> 6. run `cp /opt/local/repo/openjdkXX-fix-configure-flags/openjdk11-arm-port/java/openjdk11 /opt/local/repo/openjdkXX-fix-configure-flags/openjdk11-arm/java` in terminal
> 7. run `sudo rm -rf /opt/local/repo/openjdkXX-fix-configure-flags/openjdk11-arm-port` in terminal
> 8. run `cd /opt/local/repo/openjdkXX-fix-configure-flags/openjdk11-arm` in terminal
> 9. run `portindex` in terminal
> 10. run `cp /opt/local/etc/macports/sources.conf /opt/local/repo/openjdkXX-fix-configure-flags` in terminal
> 11. run `open -e /opt/local/repo/openjdkXX-fix-configure-flags/sources.conf` in terminal
> 12. add "file:///opt/local/repo/openjdkXX-fix-configure-flags/openjdk11-arm [nosync]" as new line just before "rsync://rsync.macports.org/macports/release/tarballs/ports.tar [default]"
> 13. run `sudo rm /opt/local/etc/macports/sources.conf` in terminal
> 14. run `sudo cp  /opt/local/repo/openjdkXX-fix-configure-flags/sources.conf /opt/local/etc/macports` in terminal
> 15. run `sudo port install openjdk11` in terminal
> 
> If it would work, I can merge #14436 which adds support to flags as well as arm64

Latest Version of Macports should be installed to run few commands.

**Comment by usersxx** [comment]
You can let me know on #14436 so that, this pr would be ready to merge.

**Comment by usersxx** [comment]
> @usersxx Awesome, please let me know if I can help you with anything.

Currently building `openjdk11` on arm64 requires Xcode.

**Comment by breun** [comment]
> Hello @usersxx and @breun I just noticed that with this change there's no more openjdk11-zulu. Since I'm running macports on Apple Silicon (ARM64) it's a huge blow on my side. Do you guys plan to restore it? Unfortunately to me, it's not feasible to update to a newer JDK at this point.
> 
> Thank you very much for your help

As far as I know `openjdk11-zulu` still exists: https://ports.macports.org/port/openjdk11-zulu/

Does `sudo port install openjdk11-zulu` not work for you?

**Comment by cabelitos** [comment]
@usersxx I'll take a look and let you know. Thank you very much.

@breun I'm not familiar on how macports advertises its ports. I can see it when I search using `port search`, however the installation does not install any binary.

Then I went to this folder (https://github.com/macports/macports-ports/tree/master/java) and checked that there are no more portfiles that declares openjdk11-zulu.

See the instalation output attached.

Screen Shot 2022-04-01 at 20 48 25

**Comment by cabelitos** [comment]
@breun what an embarrassment, ignore me. I'm able to install openjdk11-zulu. Please ignore my last message that I told that I was not able to install it. My mistake was that I had openjdk11 installed, which before this change installed zulu automatically. However after this change it automatically installed the OpenJDK version (the x86) and led to this confusion.

**Comment by cabelitos** [comment]
@usersxx I'm moving this discussion of your new port to its PR,  ok? I tried to test it locally in here.

**Comment by breun** [comment]
@cabelitos It’s currently still hiding here as a subport: https://github.com/macports/macports-ports/blob/master/java/openjdk-distributions/Portfile#L305

The fact that `openjdk11` was replaced with a port without support for arm64 was a mistake. I understand this will be corrected, but for now installing `openjdk11-zulu` or another `openjdk11-*` distribution with arm64 support should get you a native binary for your arm64 machine again.

**Comment by cabelitos** [comment]
@breun Yeah, I'm able to install zulu directly and it's working fine. I'm really sorry for the confusion.

**Pull request merged**
