### PR TITLE
legacy-support-devel: update to latest master

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by mascguy — APPROVED** [review]

**Comment by barracuda156** [comment]
@MarcusCalhoun-Lopez @mascguy Apparently this update has broken it, for the first time ever it does not even build.
```
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_legacy-support/legacy-support-devel/work/compwrap/cc/usr/bin/gcc-4.2 -arch ppc -c -Iinclude -Os -fPIC src/macports_legacy_symbol_aliases.c -o src/macports_legacy_symbol_aliases.dl.o
src/macports_legacy_symbol_aliases.c: In function ‘dirfd’:
src/macports_legacy_symbol_aliases.c:45: error: ‘NULL’ undeclared (first use in this function)
src/macports_legacy_symbol_aliases.c:45: error: (Each undeclared identifier is reported only once
src/macports_legacy_symbol_aliases.c:45: error: for each function it appears in.)
make: *** [src/macports_legacy_symbol_aliases.dl.o] Error 1
```

**Comment by fhgwright** [comment]
@barracuda156 
> @MarcusCalhoun-Lopez @mascguy Apparently this update has broken it, for the first time ever it does not even build.
> 
> ```
> /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_legacy-support/legacy-support-devel/work/compwrap/cc/usr/bin/gcc-4.2 -arch ppc -c -Iinclude -Os -fPIC src/macports_legacy_symbol_aliases.c -o src/macports_legacy_symbol_aliases.dl.o
> src/macports_legacy_symbol_aliases.c: In function ‘dirfd’:
> src/macports_legacy_symbol_aliases.c:45: error: ‘NULL’ undeclared (first use in this function)
> src/macports_legacy_symbol_aliases.c:45: error: (Each undeclared identifier is reported only once
> src/macports_legacy_symbol_aliases.c:45: error: for each function it appears in.)
> make: *** [src/macports_legacy_symbol_aliases.dl.o] Error 1
> ```

Yes, it now fails on 10.6 and 10.7, though the 10.7 error is different from the above.  And the 10.6 failure isn't limited to ppc. :-)

The last commit seems to be the offender - it builds and passes tests at HEAD^.

**Comment by fhgwright** [comment]
I of course was referring to the commits in `macports-legacy-support`, not `macports-ports`.  I.e., the bare project code passes at `61263ec` and fails at `a1e2bb0`.

**Comment by MarcusCalhoun-Lopez** [comment]
> @MarcusCalhoun-Lopez @mascguy Apparently this update has broken it, for the first time ever it does not even build.
> 
> ```
> /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_legacy-support/legacy-support-devel/work/compwrap/cc/usr/bin/gcc-4.2 -arch ppc -c -Iinclude -Os -fPIC src/macports_legacy_symbol_aliases.c -o src/macports_legacy_symbol_aliases.dl.o
> src/macports_legacy_symbol_aliases.c: In function ‘dirfd’:
> src/macports_legacy_symbol_aliases.c:45: error: ‘NULL’ undeclared (first use in this function)
> src/macports_legacy_symbol_aliases.c:45: error: (Each undeclared identifier is reported only once
> src/macports_legacy_symbol_aliases.c:45: error: for each function it appears in.)
> make: *** [src/macports_legacy_symbol_aliases.dl.o] Error 1
> ```

Thank you for pointing out this error.
It should be fixed by https://github.com/macports/macports-legacy-support/pull/81.

> Yes, it now fails on 10.6 and 10.7, though the 10.7 error is different from the above. 

If you could please explain how the error is different, it would help track down the error.

**Pull request merged**
