### PR TITLE
Bring Common Lisp to MacPorts

### PR DESCRIPTION
**Pull request by catap**
#### Description

I've bring a brand new port group to manage Common Lisp packages in a debian way.

Some packages are fetching from Debian because it is maintaned by Debian Lisp Team.

The goal of this PR is bring hunchentoot to MacPorts.

This PR works on SBCL, and support another lisp can be includes by fixing lisps :)

It was tested by https://gist.github.com/catap/6d392f3cf17353599649a24a39d75c3b as:
```
> sudo port install cl-hunchentoot cl-drakma sbcl
...
> sbcl --script /tmp/demo-hunchentoot.lisp
...
127.0.0.1 - [2023-05-26 18:12:33] "GET /foo HTTP/1.1" 200 5 "-" "Drakma/2.0.9 (SBCL 2.3.4; Darwin; 21.6.0; http://weitz.de/drakma/)"
```

Thus, almost all ports has tests :)

###### Type(s)

- [x] enhancement

###### Tested on

macOS 12.6.3 21G419 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
I've added support of that packages to [ecl](https://github.com/macports/macports-ports/pull/18838) and [clisp](https://github.com/macports/macports-ports/pull/18832).

**Comment by herbygillot** [comment]
Hey @catap, amazing work here.  Unfortunately I think we'll need to break this PR down into smaller branches, as Github is complaining that there are too many commits to merge. @barracuda156 has had to deal with this often with submissions for R.

**Comment by barracuda156** [comment]
@catap In our experience 26–29 commits per PR usually works fine, but not more than that.

**Comment by barracuda156** [comment]
@catap By the way, what is the optimal manner to support building SBCL (or possibly something else) for PPC?

At the moment we got SBCL 2.0.9 at max working on PPC. But I think it needs an intermediate compiler. I.e., I have built like that: 1.0.47 binary > 1.2.8 / 1.5.9 > 2.0.9.
Then we have CCL 1.6, untested, but provisionally should work (last official build). Someone said they had 1.7 working, but it may be some developer pre-release build.

**Comment by catap** [comment]
@barracuda156 yes, I'm working on bringing support of i386 and maybe PPC to SBCL. Let start with this ones and I'll try my best to open PR to improve SBCL port this week.

[I've already started, but hasn't got time to finish it]

**Comment by catap** [comment]
@mascguy here the second part. I just rebased it. May I ask you to review it?

**Review by mascguy — APPROVED** [review]
LGTM, will merge once CI completes

**Pull request merged**
