### PR TITLE
lens: update to 5.5.3

### PR DESCRIPTION
**Pull request by herbygillot**
- force permit the use of newer versions of Node

Fixes: https://trac.macports.org/ticket/64911

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
Looks like the CI builds failed: it built successfully but then failed afterward trying to create a dmg:
```
• building        target=macOS zip arch=x64 file=dist/OpenLens-5.4.6-latest.1651965931007-mac.zip
    • building        target=DMG arch=x64 file=dist/OpenLens-5.4.6-latest.1651965931007.dmg
    • Above command failed, retrying 5 more times
    • Above command failed, retrying 4 more times
    • Above command failed, retrying 3 more times
    • Above command failed, retrying 2 more times
    • Above command failed, retrying 1 more times
    • Above command failed, retrying 0 more times
    • building block map  blockMapFile=dist/OpenLens-5.4.6-latest.1651965931007-mac.zip.blockmap
    ⨯ hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  failedTask=build stackTrace=Error: hdiutil exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
      at ChildProcess.<anonymous> (/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_sysutils_lens/lens/work/lens-5.4.6/node_modules/builder-util/src/util.ts:250:14)
      at Object.onceWrapper (node:events:642:26)
      at ChildProcess.emit (node:events:527:28)
      at maybeClose (node:internal/child_process:1092:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
  error Command failed with exit code 1.
  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  make: *** [build] Error 1
```
Assuming that this port does not actually install the disk image, can the build system be told not to try to build it, since it appears not to work?

**Comment by mascguy** [comment]
> Looks like the CI builds failed: it built successfully but then failed afterward trying to create a dmg:
>
> [...]
>
> Assuming that this port does not actually install the disk image, can the build system be told not to try to build it, since it appears not to work?

Herby, any thoughts on this?

**Comment by herbygillot** [comment]
Took another go at this based on Ryan's finding. Looking a whole lot better.

**Review by mascguy — APPROVED** [review]
Awesome, thanks so much Herby!

**Pull request merged**
