### PR TITLE
Add xdebug 2.7 for PHP 7.3

### PR DESCRIPTION
**Pull request by RasmusWernerLarsen**
This version is only installed for PHP 7.3, previous versions should
keep using the 2.6 branch for now.

#### Description

This adds xdebug v. 2.7.0beta1, installed only for PHP 7.3. Since PHP 7.3 doesn't have an existing xdebug package and this version is only installed for 7.3, this should be a reasonably low-impact change.

This particular xdebug version has been in beta for ~3 months now and since xdebug is an essential tool in many debugging environments (for php), making it installable in MacPorts should be generally useful.

###### Type(s)
- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.1 18B75
Xcode 10.1 10B61

###### Verification 

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
See #3380...

**Comment by vnyx** [comment]
Please release a stable version of xdebug 2.7 as soon as possible so we can add it to PHP 7.3 in Macports.

**Comment by ryandesign** [comment]
> Please release a stable version of xdebug 2.7 as soon as possible so we can add it to PHP 7.3 in Macports.

You should notify the developer of xdebug of this request. They're probably not reading this MacPorts PR, so they will not see your message here.

**Comment by RasmusWernerLarsen** [comment]
@ryandesign - I understand the reason for the conclusion and for Cyrills deciding to drop the PR, but I think providing the package as-is for PHP 7.3 would be better, perhaps with an added note to users that the package has known bugs.

It's certainly true that the current xdebug 2.7.0beta1 release is broken for some usecases, but it works well for quite a few others as well. Early xdebug releases, beta or otherwise, have always tended to be somewhat unstable for the first few months of a new php major, with significant functionality causing crashes.

Given that we're only updating it for PHP 7.3 I also don't see too much risk of user confusion. It is a piece of development tooling that isn't really used in production and people installing it for php 7.3 should already understand the implications.

That said, as mentioned, a port note might be a good addition.

**Comment by ryandesign** [comment]
I understand what you've said.

I wouldn't particularly want to add a note to the port that advises the user there might be bugs. That's a given for all software.

The one reason why I'm hesitating is that if we do this, then when a final version of 2.7.0 is released and we want to update the port to that version we will need to add `epoch 1` to the php73-xdebug subport. (The MacPorts `vercmp` procedure will not understand that `2.7.0` is greater than `2.7.0beta1`; increasing the epoch overrides `vercmp`.) The `epoch` can never be decreased for the lifetime of a port, so we will need to keep that line in the Portfile forever. Having different subports with different epochs is possible, but is a little messy, and just one more thing we'll have to pay attention to for the lifetime of the port. (Then again, I'm already using differing epochs in the main php port, so it is workable.)

**Comment by RasmusWernerLarsen** [comment]
Purity... I can respect that argument.

In any case, I think we agree on the arguments for and against so I'll leave the decision to you and I won't complain if you don't merge it. I can handle my own main usecase with some alternative automation if so.

Thanks for great feedback btw.

**Comment by RasmusWernerLarsen** [comment]
The response refers to this issue I believe:
https://bugs.xdebug.org/view.php?id=1583

In the issue Derickr says:

>Hi everybody,this turned out to be a bug in PHP's OPcache >extension: https://bugs.php.net/bug.php?id=77287 [^] — a fix for this was committed today, and >will make it into the next PHP release (PHP 7.3.2). I will leave this issue open and linked to the 2.7.0 >release. I intend to release 2.7.0 soon after PHP 7.3.2 is released.cheers,Derick
>--

There is current a 7.3.2 RC1 out, so I suspect they'll be releasing very soon and presumably xdebug will come out pretty quickly... So yeah, let's wait a bit.

**Comment by RasmusWernerLarsen** [comment]
An RC1 of Xdebug has been released which apparently includes a workaround on the blocking issue. I'll update the pull request when a final release arrives.

**Comment by mojca** [comment]
RC2 seems to be out.

@ryandesign: maybe we need to introduce some kind of fake version field that would be used for version comparison only if non-empty, and would not require increasing the epoch later. In this case you would set something along these lines:
```
version 2.7.0rc2
compare-as-version 2.6.99
```

**Comment by RasmusWernerLarsen** [comment]
@ryandesign - This should be ready for merge now.

**Comment by kirmorozov** [comment]
Safe to merge, and works with php 7.3.3.

**Comment by ralfbecker** [comment]
What is blocking this merge?
Unavailability of xdebug keeps MacPorts users from moving to PHP 7.3.
Ralf

**Pull request closed without merging**
