### PR TITLE
libproxy: update to 0.4.18

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

There are no changes to the code.
First commit updates the port to current version. Second makes a few minor non-functional improvements to portfile (adds -append, sorts dependencies alphabetically).

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
Hmm, bot fails on:
```
/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_net_libproxy/libproxy/work/libproxy-0.4.18/libproxy/modules/config_kde.cpp:211:31: error: expected expression
          auto getenv_default = [](const char *name, const std::string &def) {
                                ^
  1 warning and 1 error generated.
  make[2]: *** [libproxy/CMakeFiles/config_kde.dir/modules/config_kde.cpp.o] Error 1
```

**Comment by barracuda156** [comment]
@mascguy Fixed now. Apparently `cxx_standard` 2011 does not add standard flag itself. Adding `-std=c++11` solves the problem, like here: https://clay-atlas.com/us/blog/2021/09/18/cpp-en-warning-auto-extension/

**Comment by mascguy** [comment]
> @mascguy Fixed now. Apparently `cxx_standard` 2011 does not add standard flag itself. Adding `-std=c++11` solves the problem, like here: https://clay-atlas.com/us/blog/2021/09/18/cpp-en-warning-auto-extension/

For projects using the CMake 1.1 portgroup - like this one - you should use the following instead:

```
cmake.set_cxx_standard  yes
```

**Comment by barracuda156** [comment]
> > @mascguy Fixed now. Apparently `cxx_standard` 2011 does not add standard flag itself. Adding `-std=c++11` solves the problem, like here: https://clay-atlas.com/us/blog/2021/09/18/cpp-en-warning-auto-extension/
> 
> For projects using the CMake 1.1 portgroup - like this one - you should use the following instead:
> 
> ```
> cmake.set_cxx_standard  yes
> ```

@mascguy Perhaps I misunderstood. This still does not add `-std=c++11` and we get same error as before. Let me add back the flag.

**Comment by mascguy** [comment]
> @mascguy Perhaps I misunderstood. This still does not add `-std=c++11` and we get same error as before. Let me add back the flag.

No, you understood correctly. And `cmake.set_cxx_standard` is the preferred approach.

You may need to patch upstream's CMake file, as it looks like they're also specifying it.

**Comment by barracuda156** [comment]
> > @mascguy Perhaps I misunderstood. This still does not add `-std=c++11` and we get same error as before. Let me add back the flag.
> 
> No, you understood correctly. And `cmake.set_cxx_standard` is the preferred approach.
> 
> You may need to patch upstream's CMake file, as it looks like they're also specifying it.

@mascguy Yeah, `cmake.set_cxx_standard` fails with or without the flag added. Let me see what can be done with CMakeLists.

**Comment by mascguy** [comment]
> @mascguy Yeah, `cmake.set_cxx_standard` fails with or without the flag added. Let me see what can be done with CMakeLists.

Does it work when you don't use `cmake.set_cxx_standard`, combined with setting `-std=c++11`?

**Comment by barracuda156** [comment]
> > @mascguy Yeah, `cmake.set_cxx_standard` fails with or without the flag added. Let me see what can be done with CMakeLists.
> 
> Does it work when you don't use `cmake.set_cxx_standard`, combined with setting `-std=c++11`?

@mascguy Yes, all checks passed before. Let me revert, and we hopefully get a reproducible success.

**Comment by barracuda156** [comment]
@mascguy So yeah, like this it builds fine.

**Comment by mascguy** [comment]
> @mascguy So yeah, like this it builds fine.

I'm not seeing anything immediately-obvious in the CMake files, so that's fine. But add the following comment, so folks know that you tried doing the right thing:

```
# Set standard via cxx flags, as cmake.set_cxx_flags not working properly
configure.cxxflags-append -std=c++11
```

**Comment by mascguy** [comment]
Ah, I think (?) this might be due to one of the policies that upstream is enabling, via their top-level `CMakeLists.txt`. Didn't confirm, but might be this:

https://cmake.org/cmake/help/latest/policy/CMP0067.html

**Comment by mascguy** [comment]
> Ah, I think (?) this might be due to one of the policies that upstream is enabling, via their top-level `CMakeLists.txt`. Didn't confirm, but might be this:
> 
> https://cmake.org/cmake/help/latest/policy/CMP0067.html

But we probably don't want to patch that out, unless we're absolutely certain it doesn't cause other issues. But just for awareness.

**Comment by mascguy** [comment]
> > Ah, I think (?) this might be due to one of the policies that upstream is enabling, via their top-level `CMakeLists.txt`. Didn't confirm, but might be this:
> > https://cmake.org/cmake/help/latest/policy/CMP0067.html
> 
> @mascguy Should we leave it for now like this (I added the comment re cxx flags) or try to do smth about `CMakeLists.txt`?

Nope, let's leave the CMake files alone, because it's possible that we could break something else.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
