### PR TITLE
py-sip: update to latest version

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR renames the current `py-sip` port to `py-sip4` to provide the legacy version and updates all dependents to use this "new" port. Additionally, it updates the `py-sip` port to the latest upstream version (6.1.1) and adds the `py-pyqt5-sip` port.

This doesn't changes the status quo in MacPorts, but will allow to move the PyQt packages to use the new `py-sip` port and upstreams build system (i.e., `pyqtbuild`) and once this is merged I will transitions the ports to this. Once we have all (Py)Qt5 related ports building as upstream "wants" it will be easier to add Qt6 ports in the future.

[edit: the CI do time-out with changes to this number of ports, but as stated above nothing actually changes for them...]

###### Type(s)
- [ ] bugfix
- [x] enhancement
- [ ] security fix
- [x] update

###### Tested on
macOS 10.15.7 19H1323 x86_64
Xcode 12.4 12D4e
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Review by michaelld — APPROVED** [review]
LGTM ; I will try to get some testing in on these new SIP ports to see what's what with them

**Comment by michaelld** [comment]
Ug ....
```
--->  Computing dependencies for py37-sip4
Error: Can't install py37-sip4 because conflicting ports are active: py37-sip
Error: Problem while installing py37-sip4
```

**Comment by reneeotten** [comment]
> maybe do a quickie for the `disable hack` for prior SIP?

right... hopefully fixed in ae8596d9e3d3c798ec5e911d5e1cdcbf52ae77e3

**Comment by michaelld** [comment]
ah ... OK so py*-sip upgrades just fine, but then upgrading py*-pyqt5 fails because those require py*-sip4 which conflicts with py*-sip ... hmmm ...

**Comment by reneeotten** [comment]
well... I don't know how to force the `py-pyqt5` port to first move it's dependency to `py-sip4` before updating the already installed `py-sip` port. I guess at least that that's the cause of the problem your'e seeing?

**Comment by reneeotten** [comment]
oh, perhaps I should just not do the version comparison... and always deactivate the `py-sip` when installing the `py-sip4` port?

**Comment by reneeotten** [comment]
@michaelld this doesn't work either... it still complains about the `conflict` part and, therefore, doesn't make it to the `pre-activate` part where the deactivate-hack is present. So what's the correct way of doing this: not have the ports conflicting right now and use the deactivate hack...?

**Comment by michaelld** [comment]
hmmm ... IDK ... was hoping you did!

**Comment by reneeotten** [comment]
I am trying now... I think I'll just remove the conflict from `py-sip4` with `py-sip` and do the deactivate hack if `py-sip` version 4.19.25 is installed. I *think* that will work for the update part now (and nothing else uses the `py-sip` port yet), so that should work. The problem will go away once we transition the PyQt ports using `py-sip` I hope...

**Comment by michaelld** [comment]
Yes I was just testing the first part there: remove the conflicts ... seems to work, though we'll see if it works beyond just activation!

**Pull request merged**
