### PR TITLE
poco: fix tests, fix powerpc, add mongodb variant

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

(_Why on earth did it even have arch restriction?_)

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Net-related tests fail for me; not sure, maybe a consequence of my set-up here (university network). Otherwise things work just fine:
```
--->  Testing poco
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_poco/poco/work/build" && /usr/bin/make test 
Running tests...
/opt/local/bin/ctest --force-new-ctest-process 
Test project /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_poco/poco/work/build
      Start  1: Foundation
 1/15 Test  #1: Foundation .......................   Passed  178.83 sec
      Start  2: Encodings
 2/15 Test  #2: Encodings ........................   Passed    0.05 sec
      Start  3: XML
 3/15 Test  #3: XML ..............................   Passed    0.08 sec
      Start  4: JSON
 4/15 Test  #4: JSON .............................   Passed    0.10 sec
      Start  5: Util
 5/15 Test  #5: Util .............................   Passed   10.03 sec
      Start  6: Net
 6/15 Test  #6: Net ..............................***Failed   89.47 sec
      Start  7: Redis
 7/15 Test  #7: Redis ............................***Failed    0.07 sec
      Start  8: Prometheus
 8/15 Test  #8: Prometheus .......................   Passed  217.63 sec
      Start  9: JWT
 9/15 Test  #9: JWT ..............................   Passed    0.22 sec
      Start 10: NetSSL
10/15 Test #10: NetSSL ...........................Subprocess aborted***Exception:   2.57 sec
      Start 11: Crypto
11/15 Test #11: Crypto ...........................   Passed   89.76 sec
      Start 12: DataSQLite
12/15 Test #12: DataSQLite .......................   Passed    7.49 sec
      Start 13: Data
13/15 Test #13: Data .............................   Passed    5.06 sec
      Start 14: ActiveRecord
14/15 Test #14: ActiveRecord .....................   Passed    0.19 sec
      Start 15: Zip
15/15 Test #15: Zip ..............................   Passed    0.51 sec

80% tests passed, 3 tests failed out of 15

Total Test time (real) = 602.16 sec

The following tests FAILED:
	  6 - Net (Failed)
	  7 - Redis (Failed)
	 10 - NetSSL (Subprocess aborted)
Errors while running CTest
```

**Comment by barracuda156** [comment]
@mascguy Thank you for looking into this!

**Review by mascguy — APPROVED** [review]
LGTM. @arjanvandervelde ?

**Comment by reneeotten** [comment]
@barracuda156 please add the `license` field as pointed out by `port lint`

**Comment by barracuda156** [comment]
> @barracuda156 please add the `license` field as pointed out by `port lint`

@reneeotten It is actually there, and was there before: https://github.com/macports/macports-ports/blob/4187b946818f36f17a78e126780ff901be1e5d0e/devel/poco/Portfile#L10

**Comment by reneeotten** [comment]
> > @barracuda156 please add the `license` field as pointed out by `port lint`
> 
> 
> 
> @reneeotten It is actually there, and was there before: https://github.com/macports/macports-ports/blob/4187b946818f36f17a78e126780ff901be1e5d0e/devel/poco/Portfile#L10

The poco-docs port has an invalid license set.

**Comment by barracuda156** [comment]
> The poco-docs port has an invalid license set.

I see. How to do it correctly? Just drop that line, and the generally set license will apply?

**Comment by reneeotten** [comment]
> > The poco-docs port has an invalid license set.
> 
> I see. How to do it correctly? Just drop that line, and the generally set license will apply?

Provided both licenses are the same, yes you can just drop that line. If it's not the same then you should set it appropriately.

**Comment by barracuda156** [comment]
> > > The poco-docs port has an invalid license set.
> > 
> > 
> > I see. How to do it correctly? Just drop that line, and the generally set license will apply?
> 
> Provided both licenses are the same, yes you can just drop that line. If it's not the same then you should set it appropriately.

I have no idea, it is Macports that extracts docs into a separate port. (Also, this is not my port, I am just fixing what is broken.)

**Comment by mascguy** [comment]
> I have no idea, it is Macports that extracts docs into a separate port. (Also, this is not my port, I am just fixing what is broken.)

Sergey, upstream projects almost always publish their license, typically via a text file like `LICENSE` at the root of their project. (And typically it's mentioned in their readme as well.)

So go to the project source, and check there:

https://github.com/pocoproject/poco

**Comment by barracuda156** [comment]
> > I have no idea, it is Macports that extracts docs into a separate port. (Also, this is not my port, I am just fixing what is broken.)
> 
> Sergey, upstream projects almost always publish their license, typically via a text file like `LICENSE` at the root of their project. (And it's usually mentioned in their readme as well.)
> 
> So go to the project source, and check there:
> 
> https://github.com/pocoproject/poco

Yes, I already did that of course, but the license is for the port itself, and it is already set in `poco` port. I have dropped invalid line for docs.

**Comment by mascguy** [comment]
License for docs fixed, and maintainer timeout reached. Merging.

**Comment by barracuda156** [comment]
@mascguy Thank you!

**Pull request merged**
