### PR TITLE
openjdk10: obsolete, replace with openjdk11

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Public updates ended 2018-09. No dependents.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by breun** [comment]
While I'm personally fine with dropping `openjdk10`, I wonder if/when we should do the same for `openjdk12*` and `openjdk13*`, which have also reached end of life. (A handful of ports still seem to reference 12 or 13.) And 14 will also reach en of life next month when 15 gets released.

**Comment by chrstphrchvz** [comment]
I have a few PRs open already both to start moving ports away from openjdk12/13 (so that those versions can be retired), as well as encourage them to instead use an LTS Java version as the fallback (openjdk8/11, rather than openjdk14 only to then update it to openjdk15 next month, openjdk16 in 7 months, etc.). I will likely propose that the Java portgroup comments and guide recommend using LTS version as the fallback.

**Comment by breun** [comment]
Ok, sounds good. We’ll have a new LTS next year when Java 17 gets released.

**Comment by chrstphrchvz** [comment]
Rebased to resolve conflict and push back date in "remove after" notice.

**Comment by chrstphrchvz** [comment]
Once again rebased to resolve conflict and pushed back removal date.

**Comment by chrstphrchvz** [comment]
@breun Does this PR look good to you? If so, we can notify a committer to merge this.

**Comment by breun** [comment]
@chrstphrchvz Yes, looks good to me.

**Pull request merged**
