### PR TITLE
py-transformers: Update to version 4.20.1, Add Python 310, Update dependencies

### PR DESCRIPTION
**Pull request by essandess**
#### Description

Depends upon:
* <s>#15397</s>
* #15458

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.5 21G72 x86_64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by essandess** [comment]
I've updated this PR to remove the dependency on #15397 in the hopes that it can be merged sooner.

Several of the updated ports in this PR no longer build or can be installed, e.g. `py-spaCy`, `py-transformers`.

**Comment by essandess** [comment]
I confirm that this PR builds and works on multiple systems and is ready to merge to the best of my knowledge.

**Comment by essandess** [comment]
@reneeotten I have this dependency chain of commits all running well, and it’s convenient to have organized within a single PR as you’ve asked before, but if it’s more efficient to break apart to speed up the updates please let me know. The current version of many of these ports is broken and they will not build or install.

**Comment by reneeotten** [comment]
> @reneeotten I have this dependency chain of commits all running well, and it’s convenient to have organized within a single PR as you’ve asked before, but if it’s more efficient to break apart to speed up the updates please let me know. The current version of many of these ports is broken and they will not build or install.

well... having things in one PR is nice to make sure that all dependent ports are together and the CI has a chance of building the package(s). In this case having 40+ ports in the same PR will make sure that things never finish anyway so there is no real point of doing that. So ideally you would brake this up in smaller subset, with things that are lowest on the dependency ladder and will build; once things are merged you can move on with more.

**Comment by essandess** [comment]
I've cherry picked all `py-transformer` dependency updates into separate PRs.

**Comment by mascguy** [comment]
Rebased against master, to pick up new py310 ports.

**Comment by mascguy** [comment]
> > @reneeotten I have this dependency chain of commits all running well, and it’s convenient to have organized within a single PR as you’ve asked before, but if it’s more efficient to break apart to speed up the updates please let me know. The current version of many of these ports is broken and they will not build or install.
> 
> well... having things in one PR is nice to make sure that all dependent ports are together and the CI has a chance of building the package(s). In this case having 40+ ports in the same PR will make sure that things never finish anyway so there is no real point of doing that. So ideally you would brake this up in smaller subset, with things that are lowest on the dependency ladder and will build; once things are merged you can move on with more.

I think we need to find a reasonable compromise, as splitting each port into a separate PR is also a nightmare. And it required nearly a full day of baby sitting - continually rebasing numerous PRs against master, after first merging the requisite dep PR - etc, etc, etc.

This was really NOT fun...

**Comment by essandess** [comment]
Thanks for the hard unfun work @mascguy. In the future, I don't mind rebasing multi-port interdependent PRs.

These machine learning packages likely have the longest dependency trees in MacPorts, so there will always ne an update hell issue if versions get old and broken as these had been.

**Comment by reneeotten** [comment]
@essandess there are lint warnings about missing dependencies

**Comment by mascguy** [comment]
> @essandess there are lint warnings about missing dependencies

Yep, this needs a rebase

**Comment by essandess** [comment]
@reneeotten It looks like there's a dependency bug with `py38-importlib_metadata` somewhere. This is what I see then I try to install `py38-transformers` in trace mode:

```sh
DEBUG: system:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_python_py-flatbuffers/py38-flatbuffers/work/flatbuffers-2.0.7" && /opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 setup.py --no-user-cfg build -j12 
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    from setuptools import setup
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
    from ._importlib import metadata
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/_importlib.py", line 39, in <module>
    disable_importlib_metadata_finder(metadata)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/_importlib.py", line 28, in disable_importlib_metadata_finder
    to_remove = [
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/_importlib.py", line 31, in <listcomp>
    if isinstance(ob, importlib_metadata.MetadataPathFinder)
AttributeError: module 'importlib_metadata' has no attribute 'MetadataPathFinder'
Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_python_py-flatbuffers/py38-flatbuffers/work/flatbuffers-2.0.7" && /opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 setup.py --no-user-cfg build -j12 
Exit code: 1
```

**Comment by essandess** [comment]
These build failures aren’t related to the PR. If you all agree, I’d argue to merge and put this PR chain to rest.

**Comment by mascguy** [comment]
> @reneeotten It looks like there's a dependency bug with `py38-importlib_metadata` somewhere. This is what I see then I try to install `py38-transformers` in trace mode:
> 
> ```shell
> DEBUG: system:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_python_py-flatbuffers/py38-flatbuffers/work/flatbuffers-2.0.7" && /opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 setup.py --no-user-cfg build -j12 
> Traceback (most recent call last):
>   File "setup.py", line 20, in <module>
>     from setuptools import setup
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 18, in <module>
>     from setuptools.dist import Distribution
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
>     from ._importlib import metadata
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/_importlib.py", line 39, in <module>
>     disable_importlib_metadata_finder(metadata)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/_importlib.py", line 28, in disable_importlib_metadata_finder
>     to_remove = [
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/_importlib.py", line 31, in <listcomp>
>     if isinstance(ob, importlib_metadata.MetadataPathFinder)
> AttributeError: module 'importlib_metadata' has no attribute 'MetadataPathFinder'
> Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_python_py-flatbuffers/py38-flatbuffers/work/flatbuffers-2.0.7" && /opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 setup.py --no-user-cfg build -j12 
> Exit code: 1
> ```

Steve, is this specific to the Python 3.8 subport, or does it occur for all?

**Comment by reneeotten** [comment]
it's actually the interaction with setuptools I think; I've seen this many times before - it checks whether a package is available (which appears to work in trace mode) but then fails when trying to do the actual import. Similar issue happens with all Python ports that use pep517 that all fail in trace-mode.

**Comment by mascguy** [comment]
> it's actually the interaction with setuptools I think; I've seen this many times before - it checks whether a package is available (which appears to work in trace mode) but then fails when trying to do the actual import. Similar issue happens with all Python ports that use pep517 that all fail in trace-mode.

Fair enough. But should CI still fail?

**Comment by reneeotten** [comment]
Probably not...

**Comment by mascguy** [comment]
>> Fair enough. But should CI still fail?

> Probably not...

Let's give CI one more try. If it fails again, I'll download the raw logs and dig into further.

**Comment by mascguy** [comment]
Just downloaded the logs, and the issues are intertwined:
* `py38/py39-tensorflow` isn't building for Monterey, perhaps due to the issues with Bazel. (And it also fails for Big Sur ARM, whether expectedly or not.)
* `py310-tensorflow` doesn't exist yet, which is necessary for `py310-transformers`.

So [PR 15397 - py-tensorflow, bazel: bugfixes and updates](https://github.com/macports/macports-ports/pull/15397) needs to be completed and merged, before we can move forward. Which is noted in the PR description, but which we've all forgotten about. Lol

**Comment by essandess** [comment]
> Just downloaded the logs, and the issues are intertwined:
> 
> * `py38/py39-tensorflow` isn't building for Monterey, perhaps due to the issues with Bazel.
> * `py310-tensorflow` doesn't exist yet, which is necessary for `py310-transformers`.
> 
> So [PR 15397 - py-tensorflow, bazel: bugfixes and updates](https://github.com/macports/macports-ports/pull/15397) needs to be completed and merged, before we can move forward. Which is noted in the PR description, but which we've all forgotten about. Lol 

Groan, no. `py*-tensorflow` is effectively obsolete now that we have `py*-tensorflow-macos` and `py*-tensorflow-metal`. I updated the dependency.

**Comment by mascguy** [comment]
> > Groan, no. `py*-tensorflow` is effectively obsolete now that we have `py*-tensorflow-macos` and `py*-tensorflow-metal`. I updated the dependency.
> 
> It looks like `py-tensorflow` was still being pulled in, via `py-tensorflow-data-validation`. Rebased and force-pushed, now that the latter has been fixed.

Well, we're getting closer, as builds succeed for Python 3.10. But dependency installation allegedly fails for 3.8 and 3.9; though my middle-aged eyes aren't seeing a root cause this time. (Only showing 3.9 here, but failure pattern is identical for 3.8.)

```
[...snip...]
2022-08-31T17:13:49.7663000Z Installing dependency (255 of 257) 'py39-asgiref' with variants '' ... [OK]
2022-08-31T17:13:49.7663750Z Installing dependency (256 of 257) 'py39-h11' with variants '' ... [OK]
2022-08-31T17:13:49.7664280Z Installing dependency (257 of 257) 'py39-uvicorn' with variants '' ... [OK]
2022-08-31T17:13:50.1419740Z ##[endgroup]
2022-08-31T17:13:50.1421990Z ##[error]Failed to install dependencies for py39-transformers
2022-08-31T17:13:50.1433630Z ##[error]Process completed with exit code 1.
```

Someone else should review the raw CI logs, as I must be missing something...?

[ci-py-transformers-macos-11.txt.gz](https://github.com/macports/macports-ports/files/9465773/ci-py-transformers-macos-11.txt.gz)

**Review by mascguy — APPROVED** [review]

**Pull request merged**
