### PR TITLE
arabica: fix the broken port

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

The port in abandoned (not updated since 2007) and totally broken: https://ports.macports.org/port/arabica/details
Fix this.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
I tried to inform the maintainer over e-mail, but:
> Your message to [isak@hypergene.com](mailto:isak@hypergene.com) couldn't be delivered.

**Comment by herbygillot** [comment]
Looks good. Also, let's modify `homepage` to be HTTPS.

**Comment by barracuda156** [comment]
> Looks good. Also, let's modify `homepage` to be HTTPS.

@herbygillot There was some issue with GH notifications apparently, I am getting messages only now. `https` added.

**Comment by herbygillot** [comment]
Thanks, merged.

**Pull request merged**
