### PR TITLE
py-graphviz: update to 0.20.1, add py310 subport

### PR DESCRIPTION
**Pull request by barracuda156**
Fixes: https://trac.macports.org/ticket/65812

#### Description

Presently py310 subport is not there. But:
```
  py310-automat has the following notes:
    py310-automat requires py310-twisted and py310-graphviz to enable the visualize
    feature.
    However, py310-twisted depends on py310-automat to run correctly.
    Please install py310-twisted and py310-graphviz manually for full
    functionality.
```

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Sergey, you'll also want to update this port to the latest version.

**Comment by barracuda156** [comment]
> update this port to the latest version.

@mascguy Done!

**Comment by mascguy** [comment]
@pmetzger Perry, is Marcus presently MIA? I haven't seen any activity from him since June.

**Comment by mascguy** [comment]
The tests needed `py-pytest-mock`, so I just added.

With that in place, 326 tests succeed, with just one lone failure. (And based on the some quick Googling, I'm not too concerned about that one.) The failure is also occurring for Python 3.9, providing consistent behavior. So we're good to merge.

**Comment by barracuda156** [comment]
@mascguy Sounds good, thank you!

**Review by mascguy — APPROVED** [review]
Maintainer timeout exceeded, merging.

**Pull request merged**
