### PR TITLE
openssh remove gsskex patch references from previous 8.8p1.

### PR DESCRIPTION
**Pull request by artkiver**
#### Description

Closes: https://trac.macports.org/ticket/64748

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.2.1 21D62 arm64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
In the future, you do not need to close a PR and open a new one to update or add changes to your pull request.  You can use `git commit --amend`, as [described here](https://www.atlassian.com/git/tutorials/syncing/git-push#:~:text=Amended%20force%20push&text=A%20commit%20is%20often%20amended,to%20push%20an%20amended%20commit.).

Basically edit your file to add whatever changes, `git add` or `git rm` as needed, then you can apply these to your currently existing commit using `git commit --amend`.  Afterwards you would `git push` using `--force` (to forcibly overwrite your pushed branch with your amended one).

**Comment by herbygillot** [comment]
Since removing the patch will result in a changed OpenSSH, we need to signal to MacPorts that the software is changing even though the version number is staying the same.  That's done via `revision`.  We'll need to increment `revision` as part of this change:

```suggestion
revision            3
```

**Comment by reneeotten** [comment]
why would one want to remove this patch? Is it no longer required with the latest version of `openssh` or should it just be updated to apply cleanly to the latest version. Unless there is a clear reason to remove it I am not convinced yes that this is the right thing to do...

**Comment by artkiver** [comment]
> why would one want to remove this patch? Is it no longer required with the latest version of `openssh` or should it just be updated to apply cleanly to the latest version. Unless there is a clear reason to remove it I am not convinced yes that this is the right thing to do...

Hi @reneeotten! That is a reasonable question. The simple answer is: it does not apply cleanly to the latest version as pointed out here: https://trac.macports.org/ticket/64748#comment:4 my initial PR attempt after confirming this on OS X El Capitan, simply removed the line for the patch, in the Portfile but did not perform a git rm on the patch itself. Per @herbygillot's suggestion, I also removed the patch in a later PR, though again, not being a git wizard, I probably should have gone about that differently, whoops!

A longer answer might be found within the Trac ticket, I actually owe thetrial (alabay)/ another reply on there as well though life has been getting in between me and reviewing this since last Thursday. tbh, given that I do not have any infrastructure with which to test GSSAPI/openssh-gsskex and the previous patch has some pretty strongly worded language of why the upstream OpenSSH project did not merge that patchset to begin with, and the openssh-gsskex project itself is approximately four months behind the current OpenSSH release, I am probably not the best person to attempt to refactor the patch for the current version as I wouldn't have anything with which to test it against to ensure that it is functioning.

Hopefully that answers your question? I am not entirely sure how to proceed with this PR, but I am happy to defer to others or find some other consensus on this.

One concern, again, not being a git wizard, is that if this PR with its git rm of the patch, I would hope that would only apply to 8.9p1 and that it would still be available for the previous 8.8p1 release? I am uncertain though, if it is the case that git rm makes the patch unavailable for previous versions, then certainly that aspect seems wise to avoid lest it cause additional challenges for individuals who may utilize instructions such as https://trac.macports.org/wiki/howto/InstallingOlderPort to install a previous version where the GSSAPI/gsskex variant functioned.

**Comment by reneeotten** [comment]
well, it sounds like the initial PR should not have been merged and removing the patchfile "because it doesn't apply cleanly" is not the way to go.

I would say there are two options: (1) revert to the previous version, (2) adapt the patch so that it works with the latest upstream version. I have no opinion either way as I don't use the port and have no interest in it - I'll defer to @herbygillot who merged the initial PR or one could send a message to the `devel` list.

**Comment by artkiver** [comment]
@reneeotten out of curiosity, if you, "have no opinion either way as I don't use the port and have no interest in it" is there any particular reason why you choose to comment on my PRs? In other words rather than mincing them as you seem to be: if you have no opinion, then why are you contradicting yourself and sharing one?

I am know myriad OpenSSH and OpenBSD developers personally, have been an editor of undeadly.org (the OpenBSD Journal) since its inception, and additionally was part of wheel (the BSD equivalent of "/etc/sudoers" when jkh [one of the founders of MacPorts, when it was known as DarwinPorts, long before they moved their infrastructure to GitHub, conspicuously absent: are commits from jkh since the move to GitHub, it is my observation, that perhaps this project has alienated one of its founders, whom I also: know personally] joined as CTO at iXSystems after he left Apple).

When the patch in question itself, if you bothered to read it explicitly states the following:

"This patch has been rejected upstream: 'None of the OpenSSH developers are
in favour of adding this, and this situation has not changed for several
years.  This is not a slight on Simon's patch, which is of fine quality, but
just that a) we don't trust GSSAPI implementations that much and b) we don't
like adding new KEX since they are pre-auth attack surface.  This one is
particularly scary, since it requires hooks out to typically root-owned
system resources.'"

My interpretation from the above is: this patch screams: plausible security hole and the OpenSSH team was correct in rejecting it. Moreover, the OpenSSH-gsskex project itself (https://github.com/openssh-gsskex) has not been update since September, and if you look at its open PRs, it has other bugs related to being incompatible with other previous builds of OpenSSH.

In digging around other fora on the web, such as https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg5954299.html you can read the phrase: 

"PermitRootLogin=yes

And logging in as root, will prompt for the root password and get you a
proper ssh connection."

If you aren't aware, OpenSSH and OpenBSD *defaults* to PermitRootLogin=no in their sshd_config. For sysadmins who are not savvy enough to understand why that is a REALLY BAD IDEA to enable, to also be contributing in threads related to the GSSAPI/gsskex patch, to me reads as if you don't have people who are even distantly cognoscente of rudimentary security pitfalls. 

TO hammer that home, after a lot of additional research, my read is: the gsskex patch, as it previously stood, adds an unnecessary attack surface, and the upstream project, OpenSSH was correct in rejecting it. It is beyond me why MacPorts chose to add in the patch, since it seems predominantly in use in Fedora and Ubuntu from what I can glean from cursory glances into other related hits via search engines.

As someone, who has been a Senior System Administrator, with Fortune 1 level clients, I would be disinclined to accept the previous patch, ever. That MacPorts had it applied in previous version, and that meanwhile 8.9p1 offers numerous bug fixes, as well as a "near miss" security fix in 8.9p1 if you read the releasenotes (https://www.openssh.com/txt/release-8.9) I think take precedence over supporting a 3rd party, plausibly riddled with security holes backport to a patch for a port, which MacPorts' own statistics indicate is only being utilized by approximately 117 installations.

But, if you want to try to convince me, or Herby, or anyone, why you, who claim to not even use the port, think that your opinion should take precedence, by all means, waste more words.

**Comment by reneeotten** [comment]
> @reneeotten out of curiosity, if you, "have no opinion either way as I don't use the port and have no interest in it" is there any particular reason why you choose to comment on my PRs? In other words rather than mincing them as you seem to be: if you have no opinion, then why are you contradicting yourself and sharing one?

as you might have noticed I try to get PRs merged from contributors and if they don't seem to be ready yet I add a comment or give a suggestion. If I have experience in a certain area (e.g., Python ports) giving actual useful suggestions is often easier, if I am personally interested in a package I might investigate certain issues myself and try to help.

In other cases, like this one - it seems the merge button was pushed too quickly and now an issue needs to be fixed. I just pointed out that just removing a patch because it doesn't apply cleanly is typically not what we do. On the other hand as I said I have personally no interest in this port and thus will certainly not go and read through a 4000+ line patchfile to figure out what to do with it. Feel free to go whatever way you want with this and perhaps there will be interested parties coming along in this PR to help get it merged; I'll unsubscribe from this one now.

**Comment by artkiver** [comment]
> > @reneeotten out of curiosity, if you, "have no opinion either way as I don't use the port and have no interest in it" is there any particular reason why you choose to comment on my PRs? In other words rather than mincing them as you seem to be: if you have no opinion, then why are you contradicting yourself and sharing one?
> 
> as you might have noticed I try to get PRs merged from contributors and if they don't seem to be ready yet I add a comment or give a suggestion. If I have experience in a certain area (e.g., Python ports) giving actual useful suggestions is often easier, if I am personally interested in a package I might investigate certain issues myself and try to help.
> 
> In other cases, like this one - it seems the merge button was pushed too quickly and now an issue needs to be fixed. I just pointed out that just removing a patch because it doesn't apply cleanly is typically not what we do. On the other hand as I said I have personally no interest in this port and thus will certainly not go and read through a 4000+ line patchfile to figure out what to do with it. Feel free to go whatever way you want with this and perhaps there will be interested parties coming along in this PR to help get it merged; I'll unsubscribe from this one now.

OK, thanks for the clarification. I do appreciate that you are giving attention to ports, especially such as this one which lamentably appears to be without an active maintainer.

I would posit that it would probably also make sense to remove the HPN patches from the files subdirectory as they also appear to be deprecated and are no longer referenced in the Portfile as an active variant.

It wasn't my initial intention when submitting the 8.9p1 PR to also be doing some bitrot housekeeping, but in this instance it seems as if it may be merited. Other eyes and contributors are of course welcome as I am clearly not the most adept at using GitHub (and some of those reasons are pretty deeply rooted and not likely to change so much as better discussed offline over tea in a more casual setting).

**Comment by artkiver** [comment]
Ah, good suggestion! I have emailed the macports-dev mailing list with a request for feedback and perspective along similar lines. A link to the archived message I just sent may be found here: 

https://lists.macports.org/pipermail/macports-dev/2022-March/044179.html

**Comment by neverpanic** [comment]
I think we should just drop the gsskex variant completely.

**Comment by artkiver** [comment]
I'm going to close this PR as stipulated here: https://trac.macports.org/ticket/64748#comment:20 I would suggest that Trac ticket 64748 can also be closed with https://trac.macports.org/ticket/64835 taking its place for any additional work which may be done on the OpenSSH 8.9p1 port (e.g. refactoring or [my and perhaps some others' preference] completely removing the gsskex variant, as well as removing associated patches in the files subdirectory as related to the the deprecated HPN variant, and maybe some other house keeping, which this PR didn't attempt to do as efficaciously).

Anyway, I can't seem to close https://trac.macports.org/ticket/64748, but I can at least close this PR. Thanks for all the discourse and guidance!

**Pull request closed without merging**
