### PR TITLE
strumpack: update to 7.1.3; hiop: support strumpack backend

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

macOS 10A190
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
I do not understand what CI is doing here:
```
Run . ports/.github/workflows/bootstrap.sh
Fetching files
Info
Disabling Spotlight
Uninstalling Homebrew
Installing getopt
Installing MacPorts
Configuring MacPorts
Updating PortIndex
  From https://github.com/macports/macports-ports
   * branch              master     -> FETCH_HEAD
   * [new branch]        master     -> macports/master
  Error: Process completed with exit code 60.
```

**Comment by barracuda156** [comment]
@mascguy @ryandesign @reneeotten Something has broken CI? Next PR also fails immediately with the same weird output: https://github.com/macports/macports-ports/pull/19052

**Comment by barracuda156** [comment]
Since CI are broken anyway, let me try adding MPI variant to this.

**Comment by ryandesign** [comment]
CI is fixed. If the PR is ready for review, please mark it as such.

**Comment by barracuda156** [comment]
> CI is fixed.

@ryandesign Thank you.

> If the PR is ready for review, please mark it as such.

Need to see if this builds fine with clangs.

**Comment by barracuda156** [comment]
@herbygillot This likely can be merged :)

**Pull request merged**
