### PR TITLE
rb-rake: update to 13.0.6

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update and bring portfile to sanity.
Closes: https://trac.macports.org/ticket/54732

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6 PPC
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by l2dy** [comment]
>   Error: Failed to activate rb31-rake: Image error: /opt/local/lib/ruby3.1/gems/3.1.0/cache/rake-13.0.6.gem is being used by the active ruby31 port.  Please deactivate this port first, or use 'port -f activate rb31-rake' to force the activation.

**Comment by barracuda156** [comment]
@l2dy Any idea which port is causing this?

**Comment by l2dy** [comment]
rb31-rake installs a file that ruby31 already provides. If ruby31 already bundles rake, the rb31-rake subport should be removed, i.e. remove 3.1 from `ruby.branches`.

**Comment by barracuda156** [comment]
> rb31-rake installs a file that ruby31 already provides. If ruby31 already bundles rake, the rb31-rake subport should be removed, i.e. remove 3.1 from `ruby.branches`.

@l2dy Thanks! Removed 3.1 variant.

**Pull request merged**
