### PR TITLE
meson-1.0: allow control over downloading of subprojects, via new option 'meson.wrap_mode'

### PR DESCRIPTION
**Pull request by Gcenx**
#### Description

https://mesonbuild.com/Wrap-dependency-system-manual.html
> The Wrap dependency system of Meson aims to provide an automated way to do this.

This really goes against what packages managers want to be doing, so disable this functionality by default.

Added a new option `wrap_mode` this defaults to `nodownload` but can be overwritten as needed by the Port
> possible values: default, nofallback, nodownload, forcefallback or nopromote

###### Type(s)

- [x] enhancement

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

### CODE REVIEW

**Comment by Gcenx** [comment]
@SoapZA tagging you since your the `meson` maintainer.

**Review by eli-schwartz — APPROVED** [review]
Makes sense. Meson specifically has this as a core feature so that there's a consistent UX allowing people to disable it when packaging for a package manager.

**Comment by harens** [comment]
Definitely a good idea. My only concern is that this will break any ports that have been implicitly relying on downloaded subprojects.

It might be a better idea for now to apply this fix within individual portfiles.

**Comment by Gcenx** [comment]
I’ll be altering this so it can be controlled easily from the Portfile.

> My only concern is that this will break any ports that have been implicitly relying on downloaded subprojects.

Maybe but there the other side to this. Let’s take `gst-libav` someone might assume it’s completely stand-alone and updates the Portfile accordingly.

Now I go to install it and see `gst-libav` conflicts with `ffmpeg`, this could have easily been avoided by defaulting to not allowing downloading of subprojects.

This example is the simplest one possible but some meson projects actually default to downloading subprojects over even attempting to use locally available libraries/headers.

> It might be a better idea for now to apply this fix within individual portfiles.

That seems backwards, the Portfiles should be the place to allow the downloading of subprojects not blocking them.

**Comment by eli-schwartz** [comment]
Change the default and run a world rebuild to test that it works?

**Comment by Gcenx** [comment]
Instead of hard-coding `--wrap-mode` it's now configurable via `wrap_mode` and defaults to `nodownload` this can be overwritten in the individual Ports as needed.

**Comment by reneeotten** [comment]
there are about 120 ports that currently use the `meson` PG, have any of these been tested to verify that they still build from source after this change? This should be tested locally and/or as part of the CI for at least a subset of them, at least the ones that are dependents of many other ports (e.g., `mesa`, `pango`, some of the ones in `gnome`).

**Comment by mascguy** [comment]
> Instead of hard-coding `--wrap-mode=nodownload` it's now configurable via `wrap_mode` and defaults to `nodownload` this can be overwritten in the individual Ports as needed.

I definitely love the idea of adding this functionality, and support it 110%.

As for the default behavior: I recall seeing at least a few ports in the GNOME space, that need to download subprojects. (Unfortunately I don't recall which ones at the moment, but will try to keep a list going forward.) And there are undoubtedly others.

So in the interest of adding this - without risking breakage - let's merge with `wrap_mode` set to `default`.

We can then test defaulting to `nodownload` in a subsequent PR, with rev-bumps of all dependents.

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
> @mascguy if the behavior is going to be set as default that honestly defeats the purpose unless there’s some timeline were meson ports need to work with downloading of subprojects being set to disabled.
> 
> For the occasional port that requires downloading a subproject that there’s no point in adding an actual Portfile or can be overridden within the Portfile with a note as to _why_ it’s avoiding the default behavior.

Actually I just identified a port - `gdk-pixbuf2` - which downloads a subproject for `gi-docgen`. And that's done regardless, even if its use is disabled via a meson option.

I've wanted to block that behavior for many months, and now I finally can. So that'll be the first port to take advantage of the `nodownload` option. And that's been added as a separate commit.

Over the next few weeks, I'll go through the various Meson-based ports I maintain - and there are quite a few! - and add that option. (Either `nodownload` in most cases, or `default` for those rare cases where download is needed.)

And we can go through and tackle others' ports via PRs - say, 10 at a time - and ensure the desired option is declared everywhere.

Once that's been taken care of for all ports, the final pass will be to change the default to `nodownload`. (And removing that declaration from all ports that use it.)

**Comment by mascguy** [comment]
p.s. Dean, I'll take the lead on updating others' ports too, once mine have been taken care of. You're certainly welcome to help with that too, but I'm fine with taking this on.

In terms of a timeline, this is very straightforward, and shouldn't take more than a few weeks. So we'll get there!

**Comment by mascguy** [comment]
And thank you so much for adding this functionality, we've needed this level of subproject control for a long time!

**Comment by mascguy** [comment]
> p.s. Dean, I'll take the lead on updating others' ports too, once mine have been taken care of. You're certainly welcome to help with that too, but I'm fine with taking this on.
> 
> In terms of a timeline, this is very straightforward, and shouldn't take more than a few weeks. So we'll get there!

Ticket created, to track the update effort:

[66990 - meson ports: subproject handling: update all, to explicitly declare whether subproject download allowed](https://trac.macports.org/ticket/67990)

**Pull request merged**
