### PR TITLE
opendx: fix implicitly declared function errors in compilation

### PR DESCRIPTION
**Pull request by bernstei**
#### Description
Make it possible to compile opendx with modern compilers by ignoring implicitly declared functions (bison/flex-related).

Fixes trac ticket 61842 https://trac.macports.org/ticket/61842

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

```
macOS 11.7.8 20G1351 arm64
Xcode 13.2.1 13C100
```

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by kencu** [comment]
The reason that Apple upgraded this to an error is that for arm64 Macs you often need the functions to have proper definitions, especially when building universal.

So MacPorts normally finds and adds the proper definitions for the functions instead of switching the error off.

**Comment by bernstei** [comment]
Well, this port's been broken this way for several years, so macports apparently isn't adding definitions.  It's some subtle issue with functions that are generated by flex, I think. The trac ticket has a bit of the investigation we've done.  No one's found any other workaround that I know of.

**Comment by bernstei** [comment]
Also, note that we've tested this and it works both on an M1 and Intel CPU macs.

**Comment by kencu** [comment]
> Well, this port's been broken this way for several years, so macports apparently isn't adding definitions.

Various people have added hundreds or thousands of them, in fact.

**Comment by kencu** [comment]
> Also, note that we've tested this and it works both on an M1 and Intel CPU macs.

good to hear. this may be quieting a function that is resilient to the arm64/intel issues.

**Comment by bernstei** [comment]
I didn't actively select anything w.r.t. architecture, and I don't see a universal variant. We got the same error on Intel and M1, and the PR fixes it on both machines.  When I check the executable I see
```
$ file  /opt/local/libexec/opendx/dx/bin_macos/dxexec
/opt/local/libexec/opendx/dx/bin_macos/dxexec: Mach-O 64-bit executable arm64
```

**Comment by kencu** [comment]
I see this port's been on life-support since about 2019, so it's something of a special case. 

In this case, simply toggling the error off and moving on may be reasonable, as upstream is apparently long dormant.

If I commit this I'll hear about it, so we'll leave this here for a little bit until we see if someone wants to try a proper fix. If nobody bites after a short while, IMHO it would be reasonable to commit this.

**Comment by kencu** [comment]
ah - this port has no universal variant due to other constraints. Should be fine to disable the error then.

**Comment by bernstei** [comment]
Thanks a lot.  We're really glad you're willing to keep opendx limping along - it's very useful for us.

**Comment by kencu** [comment]
https://trac.macports.org/wiki/WimplicitFunctionDeclaration

for MacPorts official approach to this problem.

**Comment by bernstei** [comment]
Interesting, and good to know for the future. I may try to track it down, but because it appears to be in functions automatically generated by flex/bison, it's going to be hard.  I guess maybe that means that it's a bug in those programs, rather than the opendx source as such, and so may even get fixed properly some day (unless the opendx source includes statically the functions auto-generated by those tools).

**Pull request merged**
