### PR TITLE
py-sentence-transformers: Update to version 2.2.2; Add Python 310, 311

### PR DESCRIPTION
**Pull request by essandess**
#### Description

* Depends upon #15456

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.5 21G72 x86_64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Observers: PR https://github.com/macports/macports-ports/pull/15823 must be merged first, as `py310-sentencepiece` doesn't exist yet.

**Comment by essandess** [comment]
> Observers: PR #15823 must be merged first, as `py310-sentencepiece` doesn't exist yet.

Note: This isn't a must, because this port simply declares a conflict with a currently nonexistent port, which isn't a runtime error.

Given the reality of https://github.com/macports/macports-ports/pull/15823#issuecomment-1227169572, I'd suggest overlooking the nonexistent port, hope upstream fixes their stuff, and we can fight the build error in #15823 another day after one hopes it goes away.

**Comment by essandess** [comment]
@mascguy I believe that PR this can be merged.

**Comment by mascguy** [comment]
> @mascguy I believe that PR this can be merged.

I'll wait for CI to complete, but otherwise no concerns here.

**Comment by essandess** [comment]
It fails on `py38-transformers`. Was that a tensorflow issue?

**Comment by mascguy** [comment]
> It fails on `py38-transformers`. Was that a tensorflow issue?

It looks like it could be, and for Python 3.9 as well.

**Comment by essandess** [comment]
> > It fails on `py38-transformers`. Was that a tensorflow issue?
> 
> It looks like it could be, and for Python 3.9 as well.

There's still some dependency on `py*-tensorflow`. I'll have to hunt it down and swap in `tensor flow-macos`.
```sh
port echo rdepof:py38-sentence-transformers | grep tensorflow
py38-tensorflow
```

**Comment by essandess** [comment]
I used tensorflow-macos in pyarrow, but py37-tensorflow will break this now.

#15397 and the inability to install plain tensorflow is creating a chain of breakage.

```
port echo rdepends:py37-pyarrow
py37-apache-beam                
py37-datasets                   
py37-magenta                    
py37-tensorflow-data-validation  
py37-tensorflow-transform       
py37-tfx-bsl
```

**Comment by mascguy** [comment]
> I used tensorflow-macos in pyarrow, but py37-tensorflow will break this now.
> 
> #15397 and the inability to install plain tensorflow is creating a chain of breakage.
> 
> ```
> port echo rdepends:py37-pyarrow
> py37-apache-beam                
> py37-datasets                   
> py37-magenta                    
> py37-tensorflow-data-validation  
> py37-tensorflow-transform       
> py37-tfx-bsl
> ```

As a suggestion: Rather than duplicating logic related to selection of the appropriate tensorflow in every port, we could instead make tensorflow a stub that depends on the appropriate one.

Then we can simplify dependents, to just depend on that.

And while thay won't solve world hunger, it might help here.

Your thoughts?

**Comment by essandess** [comment]
> > I used tensorflow-macos in pyarrow, but py37-tensorflow will break this now.
> > #15397 and the inability to install plain tensorflow is creating a chain of breakage.
> > ```
> > port echo rdepends:py37-pyarrow
> > py37-apache-beam                
> > py37-datasets                   
> > py37-magenta                    
> > py37-tensorflow-data-validation  
> > py37-tensorflow-transform       
> > py37-tfx-bsl
> > ```
> 
> As a suggestion: Rather than duplicating logic related to selection of the appropriate tensorflow in every port, we could instead make tensorflow a stub that depends on the appropriate one.
> 
> Then we can simplify dependents, to just depend on that.
> 
> And while that won't solve world hunger, it might help here.
> 
> Your thoughts?

I honestly don’t think that’s a great idea—`tensorflow` implies a specific Python package, and that’s what `py*-tensorflow` should install. #15397 works. Why don’t we just merge it?

**Comment by mascguy** [comment]
> I honestly don’t think that’s a great idea—`tensorflow` implies a specific Python package, and that’s what `py*-tensorflow` should install. #15397 works. Why don’t we just merge it?

CI is still failing for #15397. Do we need to rebase, and/or add other changes/fixes...?

**Comment by mascguy** [comment]
Rebased against master, now that the PR for `py-sentencepiece` has been merged

**Review by mascguy — APPROVED** [review]

**Comment by reneeotten** [comment]
@essandess  please rebase this PR and, if needed, make further updates if these happened upstream.

**Comment by pmetzger** [comment]
I just re-ran the CI. It does not pass. This merge request has now been in the queue for over a year. I suggest that we close it.

**Comment by pmetzger** [comment]
I'm closing this.

**Pull request closed without merging**
