### PR TITLE
py-apptools: update to 4.5.0, add py38 subport

### PR DESCRIPTION
**Pull request by emstro**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6
Xcode 11.3.1

###### Verification 
Have you

- [ x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
Error is for the py38 sub-port.

`Error: Dependency 'py38-traitsui' not found.
`

**Comment by mf2k** [comment]
I see that is in another PR. Probably would have been better to add that change to this PR.

**Comment by jjstickel** [comment]
> I see that is in another PR. Probably would have been better to add that change to this PR.
I have often bundled updates to the Enthought ports in one PR because of their inter-dependencies. I'll try to approve these today, and then I suppose they can can be merged sequentially.

**Comment by jjstickel** [comment]
LGTM. I approve this PR, but it should not be merged until after #6591 .

**Comment by reneeotten** [comment]
this is not really ideal... none of the PRs actually builds correctly due to the inter-dependencies... an you not combine the 6 PRs into one and see if everything is okay? Alternatively, please make sure it all builds locally and give the order of PRs/ports to merge (right now they all say "not until after ####", which makes it harder to follow)

**Comment by jjstickel** [comment]
> this is not really ideal... none of the PRs actually builds correctly due to the inter-dependencies... Can you not combine the 6 PRs into one and see if everything is okay? Alternatively, please make sure it all builds locally and give the order of PRs/ports to merge (right now they all say "not until after ####", which makes it harder to follow)

I agree this is not ideal, but I appreciate the contributions from @emstro. The order that they should be applied is:

traits -> pyface -> traitsui -> apptools -> envisage -> mayavi

Traits is failing only on py27, and I remark on that ticket (#6590) that it is because python 2 is no longer supported by Enthought, and so that subport should be removed in all of these PRs.

I'd like to let @emstro resolve these couple of issues in the next few days. If that doesn't happen, I can submit a new PR with the changes for all these ports together.

**Comment by reneeotten** [comment]
certainly the contributions are much appreciated! Thank you for clarifying the order of things to merge; I'm happy to take care of this once you're satisfied with all updates! 

As a side-note: if you prefer to keep the PY27 subport you could pin that to the latest supported version, but removing it is also an option.

**Comment by reneeotten** [comment]
updates of all interdependent ports are now together in #6646

**Pull request closed without merging**
