### PR TITLE
libical: Update to 3.0.4

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

This updates libical to version 3.0.4, removes the obsolete libical-devel subport, and revbumps everything linking with libical because there is a new library version.

@dbevans: gnome-calendar does not build:

```
gcal-utils.c:161:13: error: no member named 'is_utc' in 'struct icaltimetype'
  new_date->is_utc = date->is_utc;
  ~~~~~~~~  ^
gcal-utils.c:161:28: error: no member named 'is_utc' in 'struct icaltimetype'
  new_date->is_utc = date->is_utc;
                     ~~~~  ^
2 errors generated.
```

I notice it's out of date. Maybe a newer version fixes it. Could it be updated?

@NicosPavlov: kdepimlibs4 does not build:

```
kcalcore/icalformat_p.cpp:2304:7: error: no member named 'is_utc' in 'icaltimetype'
    t.is_utc = 0;
    ~ ^
kcalcore/icalformat_p.cpp:2326:7: error: no member named 'is_utc' in 'icaltimetype'
    t.is_utc = datetime.isUtc() ? 1 : 0;
    ~ ^
kcalcore/icalformat_p.cpp:2401:12: error: no member named 'is_utc' in 'icaltimetype'
    if (!t.is_utc) {
         ~ ^
kcalcore/icalformat_p.cpp:2434:11: error: no member named 'is_utc' in 'icaltimetype'
    if (t.is_utc  ||  t.zone == icaltimezone_get_utc_timezone()) {
        ~ ^
```

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.6 17G65
Xcode 9.4.1 9F2000 

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
See https://github.com/libical/libical/commit/a2bc4844bd54f8431f5c80706e12ef1a94877041

**Comment by pmetzger** [comment]
LGTM from a claws-mail point of view.

**Comment by dbevans** [comment]
Adoption of ical 3 has been slow.  Currently some ports support it but others don't.  Let's hold off for now  to avoid breaking anything but I will do a survey of the dependents today and give you a better answer shortly.

**Comment by ryandesign** [comment]
> some ports support it but others don't

Right—claws-mail, gnokii, and evolution-data-server do, while kdepimlibs4 and the old version of gnome-calendar that we have in MacPorts don't. I thought maybe a more recent version of gnome-calendar might have added support for it, but I couldn't immediately see mention of it looking through the news files.

**Comment by pmetzger** [comment]
Perhaps make it possible to install and use both versions?

**Comment by NicosPavlov** [comment]
I could try to have a better look, but considering has been KDE4 unmaintained for quite some time, it makes sense that it does not support a newer format. The package is also considered required by kdepimlibs4, so that building without an older libical around would require specific patching with most likely some loss of features.

**Comment by ryandesign** [comment]
What loss of features do you anticipate?

**Comment by NicosPavlov** [comment]
For what I could see, it is mainly libkcal that depends on libical. A quick and dirty fix would be to remove this library from the built targets of kdepimlibs4, or selectively remove support for libical if possible. 
However, this would then cascade to other port that depend on libkcal to work, such as several applications in kdepim4, for example. I am not sure of how many ports selectively depend on this library.

**Comment by pmetzger** [comment]
So, let me ask again, could we successfully install both libraries and have only the ports that can use the newer ical get updated?

**Comment by kencu** [comment]
why don't we close this and come back some day if interest exists?

**Comment by pmetzger** [comment]
I think interest exists right now, and it's a mistake to be so far behind on libraries. The problem, I think, is there is no one right now to push this through.

**Comment by kencu** [comment]
Oh, must have read it wrong. It looked a) broken and b) hasn't been touched since 1 Nov.

**Comment by pmetzger** [comment]
It certainly isn't currently commitable and certainly hasn't been touched in a long time.

**Comment by pmetzger** [comment]
I hope this PR doesn't survive to it's first birthday...

**Comment by pmetzger** [comment]
Okay, I'm inclined to close this until such a date as someone has time and space to work on it. What do people think?

**Comment by pmetzger** [comment]
Okay, if no one has any further comment, I'll close this when I next look at it, no earlier than a few days from now.

**Comment by cjones051073** [comment]
Agree this should be closed for now.

**Pull request closed without merging**
