### PR TITLE
OnyX: new port, installs pre-built app

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

OnyX: https://www.titanium-software.fr/en/onyx.html

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.7 (x86_64)

macOS 10A190 (ppc)
Xcode 3.2

macOS 10.5.8 (ppc)
Xcode 3.1.4

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Looks great except it's not open source software...

**Comment by kencu** [comment]
You did a fine job here, lots of great work. MacPorts has been playing tennis with this concept of installing such prebuilt software for a long time. Homebrew offers 5000 of these, and it is a selling feature for them.

There have been concerns raised about this idea, and also a lot of back and forth about quibbly little details about how the ports should be named to identify them properly etc that are too pointless to resurrect here, but that aside, nice work. I hope we find a way to accept these someday.

**Comment by barracuda156** [comment]
> Looks great except it's not open source software...

@aeiouaeiouaeiouaeiouaeiouaeiou Terms pretty explicitly allow distributing OnyX non-commercially:

“**They are free, fully usable, and no registration is necessary. You may download, copy, and distribute them at no charge;** however, you may not modify the software for distribution. You can use them for as long a time as you want to do so. If you want to do so, you can [make a donation](https://www.titanium-software.fr/en/donate.html).”

https://www.titanium-software.fr/en/index.html

**Comment by barracuda156** [comment]
> There have been concerns raised about this idea, and also a lot of back and forth about quibbly little details about how the ports should be named to identify them properly, but that aside, nice work. I hope we find a way to accept these someday.

@kencu From what I can see, there _are_ ports that install pre-built apps. I am not a lawyer, but T&C appears to allow non-commercial distribution, no strings attached. However, as I said in a comment above, we can ask the developer, be it desirable.

**Comment by kencu** [comment]
After two month's discussion, it was decided to not allow such ports, and discussion stopped.

Before that, and after, occasionally such ports have been accepted anyway, at times.

**Comment by barracuda156** [comment]
@kencu Got it. Well, maybe we can ask what others think at the moment.

@ryandesign @reneeotten Are we okay with a port installing pre-built utility, provided the developer explicitly allows non-commercial copying and distribution, and the utility in question is quite popular among Mac-users across all OSs?

**Comment by reneeotten** [comment]
@kencu statements are what I remember as well. We want to build software from source, not install pre-built binaries. You can download those from the developers website and typically keep them up-to-date with some internal update mechanism.

**Comment by barracuda156** [comment]
> @kencu statements are what I remember as well. We want to build software from source, not install pre-built binaries. You can download those from the developers website and typically keep them up-to-date with some internal update mechanism.

@reneeotten I think there is no equally functional alternative that is built from source.

P. S. I am not gonna argue of course, if no one wants this, I just close the PR.

**Comment by kencu** [comment]
I think bring this up again on macports-dev and see if the mood has shifted, if you like.

**Pull request closed without merging**
