### PR TITLE
qgis3: update to 3.2.1

### PR DESCRIPTION
**Pull request by willcohen**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65
Xcode 9.4.1 9F2000 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM, but @Veence doesn't have this marked `openmaintainer` so presumably we need to wait for his opinion.

**Comment by pmetzger** [comment]
@Veence timed out, so I'm merging. Someone might want to do a "port abandoned" ticket...

**Comment by pmetzger** [comment]
Merged. Thank you, @willcohen!

**Comment by pmetzger** [comment]
We have a process for declaring a port abandoned by its maintainer and moving it to `nomaintainer`, but none for making it `openmaintainer` against the maintainer's will.

**Comment by Veence** [comment]
Well, fact is, I was a bit swamped, now I’m away in vacation but in a place where the Internet is really flaky. Anyways, I’m currently working on the fact that Grass script won’t execute properly in QGis3. I was about to update Grass to trunk. I think it’s a major issue to fix, unless 3.2.1 fixes it.

**Comment by Veence** [comment]
I’ll add openmaintener to QGis3, so feel free to go ahead and bypass me for minor upgrades, since I might be busy elsewhere

**Pull request merged**
