### PR TITLE
lilypond: make devel version use Guile 2; remove dependency on netpbm

### PR DESCRIPTION
**Pull request by lemzwerg**
###### Type(s)
- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.7.5 11G63 x86_64
Xcode 4.6.3 4H1503

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
I am updating `guile` to @3.0.8 now: https://github.com/macports/macports-ports/pull/14600

**Comment by lemzwerg** [comment]
Uh, oh, right now LilyPond *needs* guile 2.x!  It doesn't work yet with 3.x.

So please provide a subport for 2.x.

**Comment by kencu** [comment]
guile is a bit tricky, as many ports that use it have specific version requirements.

having multiple installed guile versions has in the past been more difficult to implement than expected:

https://trac.macports.org/ticket/54856

**Comment by lemzwerg** [comment]
Sigh.  How to proceed?  Are there ports that ultimately need guile 3.x and fail with 2.x?

**Comment by kencu** [comment]
perhaps it will be easier now to set up parallel guile versions, if someone tries thar

**Comment by lemzwerg** [comment]
Hopefully.  Note that I have zero experience with guile 3, so I'm not the right person to take care of that.  Additionally, as mentioned many times before, I'm not a Mac user at all :-)

**Comment by barracuda156** [comment]
> perhaps it will be easier now to set up parallel guile versions, if someone tries that

@kencu Make guile-devel to use @3.0.6?

For compatibility, I just patched configure of dependencies to look for 3.0 instead of 2.0, that worked. In fact, @2.9.9 already required that.

**Pull request merged**
