### PR TITLE
py-tox: update to 2.7.0

### PR DESCRIPTION
**Pull request by steenzout**
###### Description

Use [tox 2.7.0](https://github.com/tox-dev/tox).

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification

Have you
- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] checked your Portfile with `port lint`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by l2dy** [comment]
Please use "update to" in the commit message.

**Comment by steenzout** [comment]
@l2dy done ^.

**Comment by mojca** [comment]
You are the maintainer, right? I'm asking just in case. You happen to be registered with the same name, but different email from the maintainer's email address. You should add your github handle as `maintainers {obfuscated:email @steenzout} ...`.

**Comment by steenzout** [comment]
@mojca yes, I am the maintainer.
I don't really understand what is the format I should use.
Please send me a `Portfile` with the correct format and I'll patch this.

**Comment by steenzout** [comment]
@mojca, I found a closed PR which had some format and patched my branch.
hope that works.

note: I don't want my email published.
since now everything is on GitHub people can @ me here.

**Comment by l2dy** [comment]
@steenzout Not everything is on GitHub. We still have https://trac.macports.org/ and can't @ you there.

**Comment by steenzout** [comment]
@l2dy patched again.

**Comment by l2dy** [comment]
@steenzout FYI, emails on Trac are semi-public and yours there seems to be a different one. You can edit it at https://trac.macports.org/prefs.

**Comment by mojca** [comment]
That's ok, there's no need to do anything. The only important thing was to make it clear which github handle was used by maintainer. And well, to make zteenzout aware that we can "see" two emails in case he wanted to hide one of them.

**Comment by steenzout** [comment]
both are "me".
gmail I don't mind exposing because they have a good spam filter.
my other personal email addresses I try not to but I'll update my trac to match my gmail account to avoid confusion.

**Pull request merged**
