### PR TITLE
ghc: Update to version 9.2.1 and add native arm64 support

### PR DESCRIPTION
**Pull request by essandess**
#### Description

This implements a simple patch used for (unreleased) version 9.2.2 that fixes bootstrapping (https://gitlab.haskell.org/ghc/ghc/-/issues/19631).

See #12730 for the previous submission (which I am unable to reopen for some GitHub reason).

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.2.1 21D62 x86_64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by essandess** [comment]
This PR is ready to merge to the best of my knowledge. The failed checks are CI issues.

**Comment by essandess** [comment]
Version 9.2.2 is out, but bootstrapping appears to be broken a different way. See https://gitlab.haskell.org/ghc/ghc/-/issues/21188.

@mascguy I recommend merging this PR, given the time lag to get a working `ghc` bootstrap.

**Comment by mascguy** [comment]
> @mascguy I recommend merging this PR, given the time lag to get a working `ghc` bootstrap.

Rerunning the CI jobs. Unless it's expected that they'll fail...?

**Comment by mascguy** [comment]
It looks like the 10.15 CI job completed successfully this time, so that's good.

Not sure why the macOS 11 job timed out though. Steve/anyone, is that expected?

**Comment by essandess** [comment]
I expected all the CIs to timeout based on prior experience.

I recommend merging and watch how the builedbot's do. Prior experience is that it will work. My local install works fine.

**Pull request merged**
