### PR TITLE
apache-arrow: Remove unnecessary libunwind dependency

### PR DESCRIPTION
**Pull request by essandess**
* Fixes: https://lists.macports.org/pipermail/macports-dev/2022-August/044668.html

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.5.1 21G83 x86_64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
@essandess the builds fail, so perhaps this is not the only fix needed (admittedly I didn't look carefully at the CI logs, but did this build for you locally?)

**Comment by essandess** [comment]
> @essandess the builds fail, so perhaps this is not the only fix needed (admittedly I didn't look carefully at the CI logs, but did this build for you locally?)

Yes, tested with trace mode. I also don’t understand the CI failure.

**Comment by mascguy** [comment]
Testing locally on 10.15, Big Sur, and Monterey, to see what the results are. More to follow.

**Comment by essandess** [comment]
A couple comments on this PR:
* It’s a simple fix to address a long `libunwind` dependency chain. The current implementation of `libunwind` can cause issues.
* `apache-arrow` does not need or use `lbunwind` to the best of my knowledge, but I’d appreciate a sanity check.
* @jmroot identifies the best approach by fixing `libunwind`: https://lists.macports.org/pipermail/macports-dev/2022-August/044670.html

**Comment by mascguy** [comment]
> @jmroot identifies the best approach by fixing `libunwind`: https://lists.macports.org/pipermail/macports-dev/2022-August/044670.html

So do we want to defer this PR, until someone tackles fixing `libunwind`? Or merge this as-is, assuming my testing checks out?

**Comment by mascguy** [comment]
> > @jmroot identifies the best approach by fixing `libunwind`: https://lists.macports.org/pipermail/macports-dev/2022-August/044670.html
> 
> So do we want to defer this PR, until someone tackles fixing `libunwind`? Or merge this as-is, assuming my testing checks out?

Unless someone is actively working on changes to `libunwind`, my recommendation is to merge [if all looks OK]. Steve, your thoughts?

**Comment by mascguy** [comment]
On a separate note, should this port be selecting `py-tensorflow-macos` for all Python versions, on Big Sur and later? Or is that port only supported for Python 3.10?

I ask, as installation of `py-tensorflow` appears to be what's failing, for Python 3.7 thru 3.9.

**Comment by mascguy** [comment]
> On a separate note, should this port be selecting `py-tensorflow-macos` for all Python versions, on Big Sur and later? Or is that port only supported for Python 3.10?
> 
> I ask, as installation of `py-tensorflow` appears to be what's failing, for Python 3.7 thru 3.9.

Or do we need to merge this first, to fix the issues: [PR 15397 - py-tensorflow, bazel: Bugfixes and Updates](https://github.com/macports/macports-ports/pull/15397)

**Comment by essandess** [comment]
> > On a separate note, should this port be selecting `py-tensorflow-macos` for all Python versions, on Big Sur and later? Or is that port only supported for Python 3.10?
> > I ask, as installation of `py-tensorflow` appears to be what's failing, for Python 3.7 thru 3.9.
> 
> Or do we need to merge this first, to fix the issues: [PR 15397 - py-tensorflow, bazel: Bugfixes and Updates](https://github.com/macports/macports-ports/pull/15397)

Yes, `py-tensorflow` is completely broken now and blocking this.

We could merge #15397, or delete Python 37 from this port and have it depend on `py-tensorflow-macos`.

**Comment by essandess** [comment]
> Unless someone is actively working on changes to `libunwind`, my recommendation is to merge [if all looks OK]. Steve, your thoughts?

`libunwind` issues are independent of this PR, so merge this regardless.

**Comment by mascguy** [comment]
> > Or do we need to merge this first, to fix the issues: [PR 15397 - py-tensorflow, bazel: Bugfixes and Updates](https://github.com/macports/macports-ports/pull/15397)
> 
> Yes, `py-tensorflow` is completely broken now and blocking this.
> 
> We could merge #15397, or delete Python 37 from this port and have it depend on `py-tensorflow-macos`.

I'd suggest eliminating Python 3.7 support then. Ditto for dependents, if any.

**Review by mascguy — APPROVED** [review]
Tested on 10.15, Big Sur, and Monterey, and all look good. Merging.

**Pull request merged**
