### PR TITLE
py-qpageview: add Python 3.9

### PR DESCRIPTION
**Pull request by dliessi**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G14042
Xcode 9.4.1 9F2000

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
this cannot have worked for you locally, as it is missing a dependency: 
```
port lint --nitpick py39-qpageview:
Error: Unknown dependency: py39-poppler-qt5
```

It also fails in the CI: 
```
Installing dependencies for py39-qpageview
Error: Failed to install dependencies for py39-qpageview
``` 
, but for some reason none of this is flagged as a failure and it states that all tests have been successful (CC @neverpanic).

**Comment by dliessi** [comment]
> this cannot have worked for you locally, as it is missing a dependency:
> 
> ```
> port lint --nitpick py39-qpageview:
> Error: Unknown dependency: py39-poppler-qt5
> ```

I'm sorry, I made several changes in a single branch and then divided them into separate branch to open the pull requests: I tested the changes mostly in the single branch and I missed this problem.
py39-poppler-qt5 is added in #9543: I can add this commit to that PR, or we can let this one wait until the other is merged.

**Comment by neverpanic** [comment]
I'm not currently treating failure to install dependencies as a failure of the entire CI run, which is why this isn't failing.

I can change that, if you'd prefer?

**Comment by reneeotten** [comment]
> I'm not currently treating failure to install dependencies as a failure of the entire CI run, which is why this isn't failing.

that makes sense to me.

> I can change that, if you'd prefer?

but the `lint` gives an error about an unknown dependency, in that case the build should fail in my opinion as such a PR shouldn't be merged in that state.

**Comment by neverpanic** [comment]
> but the `lint` gives an error about an unknown dependency, in that case the build should fail in my opinion as such a PR shouldn't be merged in that state.

Unfortunately `port lint` does not have a different return code for warnings and errors. Only parse failures would currently fail the port lint check, and both errors and warnings are posted as comments.

**Pull request merged**
