### PR TITLE
qbittorrent: new port submission

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.2 19C57
Xcode 11.3 11C29
and
macOS 10.15.3 19D49f
Xcode 11.3 11C29

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by dbevans** [comment]
Thanks for the PR.  I'm a bit skeptical of the need to use C++14 with libtorrent-rasterbar but will test and get back to you with a detailed review over the weekend.

**Comment by i0ntempest** [comment]
@dbevans qbittorrent 4.2 requires libtorrent-rasterbar to be build with c++14 or it’s gonna throw linker errors. I can remove the default variant if it should be c++11 unless needed.

**Comment by dbevans** [comment]
> @dbevans qbittorrent 4.2 requires libtorrent-rasterbar to be build with c++14 or it’s gonna throw linker errors. I can remove the default variant if it should be c++11 unless needed.

Yes, I see.  I have gone ahead and updated libtorrent-rasterbar to always build using C++14 rather than add a variant.  This allows qBittorrent to build successfully and doesn't affect the only other dependent deluge since it doesn't link directly with the library but uses the python bindings exclusively. The only
consequence is that future C++ dependents, if any, will have to use C++14 as well.

In testing, I was able to run both deluge and qBittorent simultaeously, without any issues, both for downloading and seeding of large torrents.

**Comment by i0ntempest** [comment]
@dbevans Thank you, I'll make changes to my PR soon.

**Comment by i0ntempest** [comment]
@dbevans Thanks for the review. The qbittorrent-nox binary doesn't have GUI so Dock doesn't know how to handle it. It only has a web interface and is normally used as a daemon.
Also I got a bunch of email from MacPorts Buildbot saying build failures, are those to be expected?

**Comment by ryandesign** [comment]
> I got a bunch of email from MacPorts Buildbot saying build failures, are those to be expected?

Since this is a new port, we have no idea what to expect from it. It looks like on some OS versions, it failed because its dependency libtorrent-rasterbar did not build. So you could look into why that was and maybe fix it, if you're interested.

**Comment by ryandesign** [comment]
But yes, it is expected that, when a port of yours doesn't build on the buildbot, you should receive failure emails about that so that you can investigate (although this [does not work for all users](https://trac.macports.org/ticket/56045)).

**Comment by ryandesign** [comment]
> when a port of yours doesn't build on the buildbot, you should receive failure emails about that so that you can investigate

And indeed, the port does fail on all macOS versions on the buildbot. So you should look at the logs and figure it out and fix it. It may be related to using `exec` instead of `system`, as I suggested in a comment on the commit. Or maybe some error is occurring with the command that you are running; you are directing all output to /dev/null so we cannot see what happened in the log.

**Pull request merged**
