### PR TITLE
Remove PHP PEAR modules and PortGroup

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Closes: https://trac.macports.org/ticket/56424 ← (see this one for background/proposal for removing)

Closes: https://trac.macports.org/ticket/34063
Closes: https://trac.macports.org/ticket/35228
Closes: https://trac.macports.org/ticket/37119
Closes: https://trac.macports.org/ticket/37683
Closes: https://trac.macports.org/ticket/38910
Closes: https://trac.macports.org/ticket/39869
Closes: https://trac.macports.org/ticket/46688
Closes: https://trac.macports.org/ticket/53510
Closes: https://trac.macports.org/ticket/53632
See: https://trac.macports.org/ticket/54839 ← (applied to `pear-TCPDF`)
Closes: https://trac.macports.org/ticket/57316
Closes: https://trac.macports.org/ticket/57318
Closes: https://trac.macports.org/ticket/57320
Closes: https://trac.macports.org/ticket/57321

Closes: https://trac.macports.org/ticket/37524 (no longer be applicable if `pear` portgroup is deleted)

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
Should ports for PEAR modules from pear.phpunit.de be deleted as well?

**Comment by cjones051073** [comment]
LGTM, but I am a little wary of merging without a little more feedback from members ? Maybe you could promote this on the devel list first ?

**Comment by Korusuke** [comment]
So I came across the recent mail in mailing list stating this PR for deletion of PHP PEAR ports.

I went through a few of the ports and it seems that once the update functionality of [UPT](https://framagit.org/upt/upt) is completed the updation of these ports could be easily automated just by adding a PEAR frontend to upt which won't take much time.
If PEAR ports are useful to the community then I would like to take this as stretch goals / after GSoC goal.

I am adding this here as suggested by @mojca in this [mail](https://lists.macports.org/pipermail/macports-dev/2019-May/040666.html).
As a context to people who might not know about UPT and my GSoC proposal, you might want to go over the [original proposal](https://docs.google.com/document/d/1T0EItL09lk_oL36v6_BgvwRb_9E_FLKVdrOd-Nt8VYo/edit?usp=sharing).

**Comment by cjones051073** [comment]
So whats the situation here ?

**Comment by pmetzger** [comment]
My suspicion is that no one cares very much, and that @Korusuke's work would be wasted. I think we should just do the deletion.

**Comment by pmetzger** [comment]
@chrstphrchvz could you fix the conflicts and then we'll merge this?

**Comment by chrstphrchvz** [comment]
I'm not able to handle this or any other contributions for MacPorts anytime soon. If this change is desirable, I'm fine with someone else updating this PR or opening a new PR based on this one.

**Comment by pmetzger** [comment]
Manually committed in a161124315

**Pull request closed without merging**
