### PR TITLE
poco: fix build issue and bump version to 1.8.0.1

### PR DESCRIPTION
**Pull request by arjanvandervelde**
Bumped the version of this broken port to 1.8.0.1. This also this fixes (or supersedes) the build error in https://trac.macports.org/ticket/55112.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by arjanvandervelde** [comment]
closing the previous pull request.

**Comment by kencu** [comment]
Installed cleanly on 10.13 / Xcode9. Seems to have both the dylibs and the static libs as billed. Trying out the binaries does not crash. I don't know how to test it in detail, but I trust you do, and did. So great! Thanks for the submission, and your patience. Much appreciated.

Lets see what havoc we may or may not find when the buildbots go at this one.

Thanks for your willingness to be the maintainer.

**Comment by kencu** [comment]
Feel free to add your maintainer line at a subsequent commit.

**Comment by kencu** [comment]
Not too bad -- build succeeded on everything except 10.5 and 10.6. (I can't see 10.7). This is probably fixable - I may look at this later for you, unless you want to take it on. Possibly the `cxx11 1.1 PortGroup` might fix it, or alternatively a requirement for libcxx depending on what other linkages this port needs.

**Comment by arjanvandervelde** [comment]
Thank you very much! I'n not sure if I have access to any build logs. It would be great if you can have a look or send me the logs. Thanks!

**Comment by kencu** [comment]
<https://build.macports.org/waterfall>

<https://build.macports.org/builders/ports-10.6_x86_64_legacy-builder/builds/51438/steps/install-port/logs/stdio>

<https://build.macports.org/builders/ports-10.6_i386_legacy-builder/builds/34082/steps/install-port/logs/stdio>

<https://build.macports.org/builders/ports-10.5_ppc_legacy-builder/builds/49468/steps/install-port/logs/stdio>

**Comment by arjanvandervelde** [comment]
Ok, yes, these seem to be C++11 related indeed; how do I force a compiler with C++11 capabilities? The PPC log shows a different error. I seems unable to verify certificates for the download. That looks like a local issue on the build host to me.

**Comment by kencu** [comment]
Usually the first step is to try adding ```PortGroup cxx11 1.1``` to the Portfile. I'll try that and see if it builds on one of my VMs. I'll get back to you about that in a day or so.

**Comment by kencu** [comment]
Well, the `cxx11 1.1` PortGroup didn't work. This port appears to have hardcoded scripts in it that reference -libc++ and clang++. Fixing the old builds may not be so easy, at least without using the full LibcxxOnOlderSystems approach.

**Pull request merged**
