### PR TITLE
get_iplayer: update to 3.21; use perl5.28

### PR DESCRIPTION
**Pull request by dliessi**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.11.6 15G22010
Xcode 8.2.1 8C1002

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
@dliessi I note that this seems to have failed the CI. Do you know why?

**Comment by dliessi** [comment]
@pmetzger 10.13 succeeded; 10.14 failed with `Installing dependency (104 of 270) 'llvm-7.0' with variants '' (requesting '') ... [FAIL] (archivefetch)` (see [log](https://dev.azure.com/macports/macports-ports/_build/results?buildId=2907&view=logs&jobId=572c5e49-83d5-5271-390a-e6dc77f89c6b&taskId=dc0e3943-5e6f-5774-1185-a5d3fcb2289e&lineStart=432&lineEnd=432&colStart=1&colEnd=105)).
The port is simply a Perl script and the Portfile only does some reinplaces and copies files in the correct locations, so it basically "cannot fail"...

**Comment by dliessi** [comment]
I was referring to Azure builds; the Travis jobs failed due to timeout or fetching some other dependency.
In any case the failure was not in executing the Portfile.

**Comment by dliessi** [comment]
> perl5.branches will then revert to the current default (5.28)

That is not actually how the perl5 portgroup works: the default 5.28 is used unless the user installed the perl5 port, in which case the version of the perl5 port is used.
The Perl modules which are dependencies of get_iplayer only support 5.26 and 5.28, while the perl5 versions go back to 5.16, so I cannot rely on the default behavior of the perl5 portgroup.

Instead of removing that line, I could add 5.26 (and specify that variants must conflict), but I'm not sure it is worth doing and I would prefer to avoid introducing variants where they are not needed.
Many ports in the tree specify only one version of Perl.

**Comment by dbevans** [comment]
> > perl5.branches will then revert to the current default (5.28)
> 
> That is not actually how the perl5 portgroup works: the default 5.28 is used unless the user installed the perl5 port, in which case the version of the perl5 port is used.
> The Perl modules which are dependencies of get_iplayer only support 5.26 and 5.28, while the perl5 versions go back to 5.16, so I cannot rely on the default behavior of the perl5 portgroup.
This is true but the intent is for the portgroup to specify the default unless the user overides it as you say.  However, perl5 only supports +perl5_26 +perl5_28 variants and just installing one or more older perls will not affect the portgroups choice so I think this is save.
> 
> Instead of removing that line, I could add 5.26 (and specify that variants must conflict), but I'm not sure it is worth doing and I would prefer to avoid introducing variants where they are not needed.
> Many ports in the tree specify only one version of Perl.

True but I don't see any point in adding variants unless the port uses perl modules that are provided by MacPorts (in which case you probably should to support the various versioned subports.  So I suggest using this default mechanism in the case where you can accept the default.  This makes things go much easier when the default is changed -- ports just need to be rebuilt without specifying a perl version explicitly.  Of course, if the port really only works with a particular perl version then specifying that explicitly is your only way out. 

By the way, I confess that I owe you an apology in forgetting about this PR and submitting another to update to latest version 3.22 including my proposed change. Sorry.

I'll leave it up to you as the maintainer: may I merge the newer PR, or merge this one as is and let you update it later. Or  perhaps update this PR to 3.22 then merge?

**Comment by dliessi** [comment]
After reading again the code of the perl5 port and portgroup, I am now convinced of [your proposal](https://github.com/macports/macports-ports/pull/5018#pullrequestreview-276302343).
I am closing this PR and moving the discussion to #5503.

**Pull request closed without merging**
