### PR TITLE
TeXShop: restore version for old systems

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Restore a version for pre-Lion systems. (This merely restores what we already had before.)

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by Schamschula** [comment]
According to https://ports.macports.org/port/texlive/details/ `texlive` doesn't build for Snow Leopard.

`TeXShop` makes no sense w/o a `texlive` being installed.

**Comment by barracuda156** [comment]
@Schamschula It certainly does build.

**Comment by Schamschula** [comment]
It could very well been that the build bots failed due to a dependency having previously failed (and not having been rebuilt).

**Comment by barracuda156** [comment]
Fair enough, that happens pretty often. I will try to remember checking the status of the build of TeXLive on an Intel machine.

**Pull request merged**
