### PR TITLE
remove obsolete Python subports (various maintainers)

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR removes obsolete Python subports for various maintained ports that have no dependencies. Subports for newer Python versions were added for ports if the test-suite passes and, additionally, I updated some ports to their latest version. 

###### Tested on
macOS 10.14.6 18G95
Xcode 10.3 10G8

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by raphael-st** [comment]
LGTM for py-djvubind.

**Comment by g5pw** [comment]
LGTM for my ports. Thank you!

**Comment by Synss** [comment]
LGTM for py-ezodf

**Comment by jjstickel** [comment]
It looks like you already committed the changes for py-cvxopt in 2d5ac76.

**Comment by reneeotten** [comment]
> It looks like you already committed the changes for py-cvxopt in [2d5ac76](https://github.com/macports/macports-ports/commit/2d5ac7620d2036a54f6a2dd96b36b5ae0187496a).

No, if you look in ```master``` that change has not been committed; it's part of this PR.

**Comment by jjstickel** [comment]
> > It looks like you already committed the changes for py-cvxopt in [2d5ac76](https://github.com/macports/macports-ports/commit/2d5ac7620d2036a54f6a2dd96b36b5ae0187496a).
> 
> No, if you look in `master` that change has not been committed; it's part of this PR.

Ah, OK. LGTM.

**Comment by reneeotten** [comment]
merging under ```openmaintainer``` / ```maintainer timeout```

**Pull request merged**
