### PR TITLE
gr-adapt: new port

### PR DESCRIPTION
**Pull request by ra1nb0w**
#### Description

Adaptive filters for GNU Radio

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.15 19A582a
Xcode 11.2 11B41

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ra1nb0w** [comment]
add @michaelld

**Comment by ra1nb0w** [comment]
about "QR decomposition": I think that should always enabled, what do you think?

**Comment by michaelld** [comment]
> about "QR decomposition": I think that should always enabled, what do you think?

Agreed! I like that it's a variant that's default.

I'll be testing / verifying shortly.

**Comment by ra1nb0w** [comment]
Error
```
Fetching distfile failed: Could not resolve host: distfiles.macports.org
```

**Comment by michaelld** [comment]
I get the following error when linking the top-level `libgnuradio-adapt.dylib`:
```:info:build /usr/bin/clang++ -pipe -Os -DNDEBUG -I/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14 -dynamiclib -Wl,-headerpad_max_install_names -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -compatibility_version 0.1.0 -o libgnuradio-adapt.0.1.0git.dylib -install_name /opt/local/lib/libgnuradio-adapt.0.1.0git.dylib CMakeFiles/gnuradio-adapt.dir/lms_filter_ff_impl.cc.o CMakeFiles/gnuradio-adapt.dir/lms_filter_cc_impl.cc.o CMakeFiles/gnuradio-adapt.dir/nlms_filter_ff_impl.cc.o CMakeFiles/gnuradio-adapt.dir/nlms_filter_cc_impl.cc.o CMakeFiles/gnuradio-adapt.dir/rls_filter_ff_impl.cc.o CMakeFiles/gnuradio-adapt.dir/rls_filter_cc_impl.cc.o CMakeFiles/gnuradio-adapt.dir/qrd_rls_filter_ff_impl.cc.o CMakeFiles/gnuradio-adapt.dir/qrd_rls_filter_cc_impl.cc.o CMakeFiles/gnuradio-adapt.dir/iqrd_rls_filter_ff_impl.cc.o CMakeFiles/gnuradio-adapt.dir/iqrd_rls_filter_cc_impl.cc.o  -Wl,-rpath,/opt/local/lib /opt/local/lib/libvolk.2.0.dylib /opt/local/lib/libboost_filesystem-mt.dylib /opt/local/lib/libboost_system-mt.dylib /opt/local/lib/libgnuradio-runtime.dylib /opt/local/lib/libgnuradio-pmt.dylib /opt/local/lib/liblog4cpp.dylib /opt/local/lib/libgnuradio-filter.dylib /opt/local/lib/libgnuradio-fft.dylib /opt/local/lib/liborc-0.4.dylib -lm 
:info:build Undefined symbols for architecture x86_64:
:info:build   "_cgemm_", referenced from:
:info:build       void arma::glue_times::apply<std::__1::complex<float>, false, true, false, arma::Col<std::__1::complex<float> >, arma::Col<std::__1::complex<float> > >(arma::Mat<std::__1::complex<float> >&, arma::Col<std::__1::complex<float> > const&, arma::Col<std::__1::complex<float> > const&, std::__1::complex<float>) in rls_filter_cc_impl.cc.o
:info:build   "_cgemv_", referenced from:
:info:build       gr::adapt::lms_filter_cc_impl::work(int, std::__1::vector<void const*, std::__1::allocator<void const*> >&, std::__1::vector<void*, std::__1::allocator<void*> >&) in lms_filter_cc_impl.cc.o
:info:build   "_cherk_", referenced from:
:info:build       void arma::herk<true, false, false>::apply_blas_type<float, arma::Col<std::__1::complex<float> > >(arma::Mat<std::__1::complex<float> >&, arma::Col<std::__1::complex<float> > const&, float, float) in rls_filter_cc_impl.cc.o
```
and so on. Looks like LAPACK or the like isn't being linked in here. I'll attach the build log for your edification.  [gr-adapt.log.txt](https://github.com/macports/macports-ports/files/3721023/gr-adapt.log.txt)

**Comment by michaelld** [comment]
Maybe it's an indirect requirement when using Armadillo? Not sure why the CI / BuildBots are succeeding & my setup isn't ...

**Comment by ra1nb0w** [comment]
can you check with
```
nm /opt/local/lib/libarmadillo.9.80.1.dylib |grep _cgemm_
```

**Comment by michaelld** [comment]
```
% nm /opt/local/lib/libarmadillo.9.80.1.dylib |grep _cgemm_
                 U _cgemm_
0000000000002aa4 T _wrapper2_cgemm_
00000000000020f4 T _wrapper_cgemm_```

**Comment by ra1nb0w** [comment]
Can you check the values of

- `LAPACK_FOUND`
- `ARMADILLO_FOUND`
- `LAPACK_LIBRARIES`
- `ARMADILLO_LIBRARIES`

on CMakeCache.txt

**Comment by michaelld** [comment]
Armadillo
```
//Details about finding Armadillo
FIND_PACKAGE_MESSAGE_DETAILS_Armadillo:INTERNAL=[/opt/local/lib/libarmadillo.dylib][/opt/local/include][v9.800.1()]
```

**Comment by michaelld** [comment]
Not sure if `Armadillo_FOUND` or any CAP variants of it are defined ... nothing in the `CMakeCache.txt` file

**Comment by michaelld** [comment]
LAPACK:
```
//Have function cheev_
LAPACK_WORKS:INTERNAL=1
```

**Comment by michaelld** [comment]
Relevant output from cmake:
```
:info:configure -- Looking for sgemm_
:info:configure -- Looking for sgemm_ - found
:info:configure -- Found BLAS: /opt/local/lib/libopenblas.dylib  
:info:configure -- Looking for cheev_
:info:configure -- Looking for cheev_ - found
:info:configure -- A library with LAPACK API found.
:info:configure -- Found Armadillo: /opt/local/lib/libarmadillo.dylib (found version "9.800.1") 
```

**Comment by ra1nb0w** [comment]
Strange, on `work/build/CMakeCache.txt` you should have
```
ARMADILLO_INCLUDE_DIR:PATH=/opt/local/include
ARMADILLO_LIBRARY:FILEPATH=/opt/local/lib/libarmadillo.dylib
```
If the `ARMADILLO_LIBRARY` is not present the linking fail (not `target_link_libraries`) in fact in the `clang++` you don't have the `libarmadillo.dylib` library and this can happen only if cached (not done at configuration time)
the `_FOUND` is generally runtime only so not in cache; the project define `#define ARMADILLO_FOUND` on `work/build/lib/config.h`

maybe you should check
- /opt/local/share/Armadillo/CMake/ArmadilloConfig.cmake

The CMakeLists.txt seems correct.

**Comment by michaelld** [comment]
I see all of the ARMADILLO variables as you note. In CMake, "ARMADILLO_FOUND" is TRUE. As is "LAPACK_FOUND".

**Comment by michaelld** [comment]
So the issue is here: < https://github.com/karel/gr-adapt/blob/master/lib/CMakeLists.txt#L51-L56 >. What happens if both LAPACK and ARMADILLO are found? Seem like a conflict!

**Comment by ra1nb0w** [comment]
if you call `target_link_libraries` multiple times it appends the items.
is this your question?

**Comment by michaelld** [comment]
> if you call `target_link_libraries` multiple times it appends the items.
> is this your question?

Nope. Here's the code with the issue:
```
if(LAPACK_FOUND)
	target_link_libraries(gnuradio-adapt ${LAPACK_LIBRARIES} ${Boost_LIBRARIES} ${GNURADIO_ALL_LIBRARIES})
elseif(ARMADILLO_FOUND)
	target_link_libraries(gnuradio-adapt ${ARMADILLO_LIBRARIES} ${Boost_LIBRARIES} ${GNURADIO_ALL_LIBRARIES})
else(LAPACK_FOUND)
	target_link_libraries(gnuradio-adapt ${Boost_LIBRARIES} ${GNURADIO_ALL_LIBRARIES})
endif(LAPACK_FOUND)
```
My question is: what happens if both `LAPACK_FOUND` and `ARMADILLO_FOUND` are TRUE? From the above code, it's clear that only the `LAPACK_LIBRARIES` are linked against. But both LAPACK and ARMADILLO headers are used when compiling the code. Hence the error I'm seeing that ARMADILLO libraries aren't being linked against.

Thus: Can we use both LAPACK and ARMADILLO at the same time? If not, then we need logic to pick one or the other when both are found.

**Comment by ra1nb0w** [comment]
I used the link above that refer to the master branch not the maint-3.7 and therefore I didn't see the error. Yes you are right, it is wrong.
This [line](https://github.com/karel/gr-adapt/blob/maint-3.7/CMakeLists.txt#L160) infer that both should used. Now I create the patch (like master) for macports and then also submit to upstream.
Strange that it works ;-)

**Comment by michaelld** [comment]
FYI I pulled that code from what this PR used for gr-adapt + patching ...

**Comment by ra1nb0w** [comment]
try it

**Comment by michaelld** [comment]
on it

**Comment by ra1nb0w** [comment]
and if you have the time check https://github.com/macports/macports-ports/pull/5501

**Comment by michaelld** [comment]
not quite yet ... let me take a look at the current logic & see if I can make sense of it. ...

**Comment by michaelld** [comment]
So the issue is the following ... 
```
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /opt/local/lib/libopenblas.dylib
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- Found Armadillo: /opt/local/lib/libarmadillo.dylib (found version "9.800.1")
-- LAPACK_FOUND is 'TRUE'
-- LAPACK_INCLUDE_DIRS is ''
-- LAPACK_LIBRARIES is ''
-- LAPACK_LINKER_FLAGS is ''
-- LAPACK95_FOUND is 'FALSE'
-- LAPACK95_INCLUDE_DIRS is ''
-- LAPACK95_LIBRARIES is ''
-- LAPACK95_LINKER_FLAGS is ''
-- ARMADILLO_FOUND is 'TRUE'
-- ARMADILLO_INCLUDE_DIRS is '/opt/local/include'
-- ARMADILLO_LIBRARIES is '/opt/local/lib/libarmadillo.dylib'
```
So ... LAPACK is found, but no specific library is noted for use. I have OpenBLAS installed, and if it doesn't find that it'll use the Accelerate framework.

Have you have success with the LAPACK variables from finding it?

**Comment by ra1nb0w** [comment]
Mine
```
-- LAPACK_FOUND TRUE
-- LAPACK_INCLUDE_DIRS
-- LAPACK_LIBRARIES /opt/local/lib/libopenblas.dylib
-- LAPACK_LINKER_FLAGS
-- LAPACK95_FOUND FALSE
-- LAPACK95_INCLUDE_DIRS
-- LAPACK95_LIBRARIES
-- LAPACK95_LINKER_FLAGS
-- ARMADILLO_FOUND TRUE
-- ARMADILLO_INCLUDE_DIRS /opt/local/include
-- ARMADILLO_LIBRARIES /opt/local/lib/libarmadillo.dylib
```
with
```
  lapack @3.8.0_2+gfortran (active)
  OpenBLAS @0.3.7_0+gcc9+lapack (active)
```
Anyway, `lapack` has pkgconfig and cmake config on wrong place
```
  /opt/local/lib/lapack/cmake/cblas-3.8.0/cblas-config-version.cmake
  /opt/local/lib/lapack/cmake/cblas-3.8.0/cblas-config.cmake
  /opt/local/lib/lapack/cmake/cblas-3.8.0/cblas-targets-release.cmake
  /opt/local/lib/lapack/cmake/cblas-3.8.0/cblas-targets.cmake
  /opt/local/lib/lapack/cmake/lapack-3.8.0/lapack-config-version.cmake
  /opt/local/lib/lapack/cmake/lapack-3.8.0/lapack-config.cmake
  /opt/local/lib/lapack/cmake/lapack-3.8.0/lapack-targets-release.cmake
  /opt/local/lib/lapack/cmake/lapack-3.8.0/lapack-targets.cmake
  /opt/local/lib/lapack/cmake/lapacke-3.8.0/lapacke-config-version.cmake
  /opt/local/lib/lapack/cmake/lapacke-3.8.0/lapacke-config.cmake
  /opt/local/lib/lapack/cmake/lapacke-3.8.0/lapacke-targets-release.cmake
  /opt/local/lib/lapack/cmake/lapacke-3.8.0/lapacke-targets.cmake
  /opt/local/lib/lapack/pkgconfig/blas.pc
  /opt/local/lib/lapack/pkgconfig/cblas.pc
  /opt/local/lib/lapack/pkgconfig/lapack.pc
  /opt/local/lib/lapack/pkgconfig/lapacke.pc
```
Should be on
```
/opt/local/lib/pkgconfig/
/opt/local/share/cmake/lapack
```

**Comment by karel** [comment]
I am glad to see this effort here and sorry that the CMakeLists in gr-adapt have caused you problems. I agree with @ra1nb0w on `if(LAPACK_FOUND AND ARMADILLO_FOUND)`. I updated both the master and maint-3.7 branches to use this variant in both of the CMakeLists.

**Comment by michaelld** [comment]
@karel thanks!

**Comment by ra1nb0w** [comment]
@karel can you also add [this](https://github.com/karel/gr-adapt/commit/d36e0d26ee6911d976c85c4fb3619ba3e95baff8) to maint-3.7?

**Comment by karel** [comment]
@ra1nb0w, [sure](https://github.com/karel/gr-adapt/commit/4bbdde4ce52e88365ab8f51c05b7f08f90573275)!

**Comment by michaelld** [comment]
this is looking positive!

**Comment by michaelld** [comment]
@ra1nb0w please ping here when you've update the PR & I'll give it one more go-over ... fingers crossed this does it!

**Comment by ra1nb0w** [comment]
moved to `maint-3.7` and latest commit

**Comment by michaelld** [comment]
If y'all look at the top-level build file `CMakeCache.txt`, and search (not literally) for "BLAS_*_LIBRARY", what do you find?

**Comment by ra1nb0w** [comment]
```
BLAS_openblas_LIBRARY:FILEPATH=/opt/local/lib/libopenblas.dylib
```

side note https://github.com/macports/macports-ports/pull/5490#issuecomment-542543239 about wrong lapack pkgconfig folder.

**Comment by michaelld** [comment]
OK. What does this return `port installed lapack "openblas*" | grep active"?

Mine:
```
  lapack @3.8.0_2+gfortran (active)
  OpenBLAS-devel @20191006-aa04b092_0+gcc9+lapack+native (active)
```

**Comment by ra1nb0w** [comment]
I am not using OpenBLAS-devel
```
  lapack @3.8.0_2+gfortran (active)
  OpenBLAS @0.3.7_0+gcc9+lapack (active)
```

**Comment by michaelld** [comment]
same-same for all practical purposes ... strange!

In the CMakeCache.txt file, are any of the other "BLAS_*_LIBRARIES" set? Mine are all "NOTFOUND" ...

**Comment by michaelld** [comment]
Ignore the prior. What does this return:
```
port installed "cmake*"
```

**Comment by michaelld** [comment]
I'm running "cmake-devel", which I bet contains this commit https://cmake.org/gitweb?p=cmake.git;a=commit;h=68dcbeee01a301876011a8310509e3860cbb9b34 ... which seems to be messing up this Find ...

**Comment by ra1nb0w** [comment]
```
  cmake @3.15.4_0 (active)
```
and that commit is not present on 3.15

**Comment by michaelld** [comment]
OK. So we can work around this issue by setting the `BLA_VENDOR` as follows:
```
variant qr description "Enable QR decomposition on RLS filters" {
    depends_lib-append \
        port:lapack \
        port:armadillo \
        path:lib/libopenblas.dylib:openblas

    configure.env-append BLA_VENDOR=OpenBLAS
}
```

**Comment by michaelld** [comment]
this is wise, since we should define the BLAS to use instead of allowing opportunistic linking to some arbitrary BLAS (default if none are installed is Apple's Accelerate, which would be fine if it worked LOL).

**Comment by michaelld** [comment]
That change allows gr-adapt to install & work for me. Hopefully it does for you too!

**Comment by ra1nb0w** [comment]
works. updated.

**Comment by michaelld** [comment]
Thx! I'll test / verify tomorrow morning.

**Comment by ra1nb0w** [comment]
I am happy ;-)

**Pull request merged**
