### PR TITLE
`openjdk8*`: update to newer version

### PR DESCRIPTION
**Pull request by usersxx**
#### Description
Fixes: https://trac.macports.org/ticket/65039
Fixes: https://trac.macports.org/ticket/65049
Update `openjdk8` to 8.332.09.1 and add `openjdk7-bootstrap` as new port for bootstrapping on ppc arch (requires testing)

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by usersxx** [comment]
@evanmiller Can you test this port.

**Comment by usersxx** [comment]
> > @barracuda156, Can you test this port now?

> Sure, I will do it by tomorrow.

@barracuda156, Can you test this port now

**Comment by reneeotten** [comment]
@usersxx please squash the last five `openjdk8` commits into one?

**Comment by usersxx** [comment]
> @usersxx please squash the last five `openjdk8` commits into one?

I would squash all the commits after the testing `openjdk8` port on ppc.

**Comment by barracuda156** [comment]
@usersxx Please bear with me, been away from the office. I will provide an update in an hour from 10.6 PPC and 10.5.8.

**Comment by barracuda156** [comment]
@usersxx Hmm, I am getting:
```
--->  Extracting jdk8u332-b09.tar.gz
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work" && /usr/bin/gzip -dc '/opt/local/var/macports/distfiles/openjdk8/jdk8u332-b09.tar.gz' | /usr/bin/gnutar --no-same-owner -xf - 
--->  Applying patches to openjdk8
--->  Applying patch-openjdk8-xcode.diff
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/openjdk8" && /usr/bin/patch -p0 < '/opt/PPCSnowLeopardPorts/java/openjdk8/files/patch-openjdk8-xcode.diff'
patching file common/autoconf/toolchain.m4
patching file common/autoconf/generated-configure.sh
--->  Patching gcc.make: s|WARNINGS_ARE_ERRORS = -Werror|WARNING_FLAGS =|g
--->  Patching gcc.make: s|WARNING_FLAGS = -Wpointer-arith -Wsign-compare -Wundef -Wunused-function -Wformat=2|WARNING_FLAGS = |g
--->  Patching platform_zero.in: s|@ZERO_ARCHDEF@|PPC|g
--->  Patching platform_zero.in: s|@ZERO_LIBARCH@|ppc|g
Error: Failed to patch openjdk8: extra characters after close-quote
```

**Comment by barracuda156** [comment]
Did I pick a wrong version? I took the portfile and the new patch from here: https://github.com/usersxx/macports-ports/tree/%60openjdk8%60-updates/java/openjdk8

**Comment by barracuda156** [comment]
@usersxx Now this:
```
--->  Applying patch-openjdk8-xcode.diff
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/openjdk8" && /usr/bin/patch -p0 < '/opt/PPCSnowLeopardPorts/java/openjdk8/files/patch-openjdk8-xcode.diff'
patching file common/autoconf/toolchain.m4
patching file common/autoconf/generated-configure.sh
--->  Patching gcc.make: s|WARNINGS_ARE_ERRORS = -Werror|WARNING_FLAGS =|g
--->  Patching gcc.make: s|WARNING_FLAGS = -Wpointer-arith -Wsign-compare -Wundef -Wunused-function -Wformat=2|WARNING_FLAGS = |g
--->  Patching platform_zero.in: s|@ZERO_ARCHDEF@|PPC|g
--->  Patching platform_zero.in: s|@ZERO_LIBARCH@|ppc|g
--->  Patching os_perf_bsd.cpp: s|vm_version_ext_x86.hpp| |g
--->  Patching os_perf_bsd.cpp: s|_cpu_info->set_number_of_hardware_threads(VM_Version_Ext::number_of_threads());| |g
--->  Patching os_perf_bsd.cpp: s|_cpu_info->set_number_of_cores(VM_Version_Ext::number_of_cores());| |g
--->  Patching os_perf_bsd.cpp: s|_cpu_info->set_number_of_sockets(VM_Version_Ext::number_of_sockets());| |g
--->  Patching os_perf_bsd.cpp: s|_cpu_info->set_cpu_name(VM_Version_Ext::cpu_name());| |g
--->  Patching os_perf_bsd.cpp: s|_cpu_info->set_cpu_description(VM_Version_Ext::cpu_description());| |g
--->  Patching vm.make: s|dtraceCheck| |g
--->  Patching LP64=1: s|MFLAGS += 
Error: reinplace: couldn't read file "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/LP64=1": no such file or directory
Error: Failed to patch openjdk8: reinplace sed(1) failed
```

**Comment by barracuda156** [comment]
@usersxx I guess this does not work:
```
reinplace "s|MFLAGS += " LP64=1 "|MFLAGS += " LP64=0 "|g" hotspot/make/bsd/Makefile
```

**Comment by barracuda156** [comment]
@usersxx @nilsvanvelzen Now it fails here:
```
Compiling /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/src/share/vm/runtime/compilationPolicy.cpp
Compiling /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/src/share/vm/compiler/compileBroker.cpp
Compiling /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/src/share/vm/compiler/compileLog.cpp
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/src/share/vm/compiler/compileBroker.cpp: In static member function ‘static void CompileBroker::invoke_compiler_on_method(CompileTask*)’:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/src/share/vm/compiler/compileBroker.cpp:1970: error: invalid conversion from ‘const char*’ to ‘char*’
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/src/share/vm/compiler/compileBroker.cpp:1970: error:   initializing argument 1 of ‘void __dtrace_probe$hotspot$method__compile__begin$v1$63686172202a$75696e747074725f74$63686172202a$75696e747074725f74$63686172202a$75696e747074725f74$63686172202a$75696e747074725f74(char*, uintptr_t, char*, uintptr_t, char*, uintptr_t, char*, uintptr_t)’
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/src/share/vm/compiler/compileBroker.cpp:2074: error: invalid conversion from ‘const char*’ to ‘char*’
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/src/share/vm/compiler/compileBroker.cpp:2074: error:   initializing argument 1 of ‘void __dtrace_probe$hotspot$method__compile__end$v1$63686172202a$75696e747074725f74$63686172202a$75696e747074725f74$63686172202a$75696e747074725f74$63686172202a$75696e747074725f74$75696e747074725f74(char*, uintptr_t, char*, uintptr_t, char*, uintptr_t, char*, uintptr_t, uintptr_t)’
gmake[6]: *** [/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/make/bsd/makefiles/rules.make:151: compileBroker.o] Error 1
gmake[6]: *** Waiting for unfinished jobs....
gmake[6]: Leaving directory '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/jdk8u-jdk8u332-b09/build/openjdk8/hotspot/bsd_ppc_zero/product'
gmake[5]: *** [/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/make/bsd/makefiles/top.make:129: the_vm] Error 2
gmake[5]: Leaving directory '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/jdk8u-jdk8u332-b09/build/openjdk8/hotspot/bsd_ppc_zero/product'
gmake[4]: *** [/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/make/bsd/Makefile:314: productzero] Error 2
gmake[4]: Leaving directory '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/jdk8u-jdk8u332-b09/build/openjdk8/hotspot'
gmake[3]: *** [Makefile:261: generic_buildzero] Error 2
gmake[3]: Leaving directory '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/jdk8u-jdk8u332-b09/hotspot/make'
gmake[2]: *** [Makefile:185: productzero] Error 2
gmake[2]: Leaving directory '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/jdk8u-jdk8u332-b09/hotspot/make'
gmake[1]: *** [HotspotWrapper.gmk:45: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/build/openjdk8/hotspot/_hotspot.timestamp] Error 2
gmake[1]: Leaving directory '/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/jdk8u-jdk8u332-b09/make'
gnumake: *** [hotspot-only] Error 2
gnumake: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/jdk8u-jdk8u332-b09'
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_java_openjdk8/openjdk8/work/openjdk8" && /usr/bin/gnumake -j1 -w images 
Exit code: 2
```

**Comment by nilsvanvelzen** [comment]
@usersxx. This is dtrace stuff. I suppose the interface has changed between the dtrace implementation used on with the old Xcode and what is currently used on Mac-osx. I have never been able to successfully compile JDK 1.7 or 1.8 on powerpc with dtrace. In my 1.8 port I have disabled it completely, which includes numerous changes to the makefiles since it is a hard-coded switch/assumption that Sun and Mac use dtrace. It is a nice to have but as far as I understand not essential voor a functional JDK.

**Comment by barracuda156** [comment]
@usersxx And on 10.5.8:
```
Compiling /opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/src/share/vm/runtime/compilationPolicy.cpp
Compiling /opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/src/share/vm/compiler/compileBroker.cpp
/opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/src/share/vm/compiler/compileBroker.cpp: In static member function ‘static void CompileBroker::invoke_compiler_on_method(CompileTask*)’:
/opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/src/share/vm/compiler/compileBroker.cpp:1970: error: invalid conversion from ‘const char*’ to ‘char*’
/opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/src/share/vm/compiler/compileBroker.cpp:1970: error:   initializing argument 1 of ‘void __dtrace_probe$hotspot$method__compile__begin$v1$63686172202a$75696e747074725f74$63686172202a$75696e747074725f74$63686172202a$75696e747074725f74$63686172202a$75696e747074725f74(char*, uintptr_t, char*, uintptr_t, char*, uintptr_t, char*, uintptr_t)’
/opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/src/share/vm/compiler/compileBroker.cpp:2074: error: invalid conversion from ‘const char*’ to ‘char*’
/opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/src/share/vm/compiler/compileBroker.cpp:2074: error:   initializing argument 1 of ‘void __dtrace_probe$hotspot$method__compile__end$v1$63686172202a$75696e747074725f74$63686172202a$75696e747074725f74$63686172202a$75696e747074725f74$63686172202a$75696e747074725f74$75696e747074725f74(char*, uintptr_t, char*, uintptr_t, char*, uintptr_t, char*, uintptr_t, uintptr_t)’
gmake[6]: *** [/opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/make/bsd/makefiles/rules.make:151: compileBroker.o] Error 1
gmake[6]: *** Waiting for unfinished jobs....
gmake[6]: Leaving directory '/opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/jdk8u-jdk8u332-b09/build/openjdk8/hotspot/bsd_ppc_zero/product'
gmake[5]: *** [/opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/make/bsd/makefiles/top.make:129: the_vm] Error 2
gmake[5]: Leaving directory '/opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/jdk8u-jdk8u332-b09/build/openjdk8/hotspot/bsd_ppc_zero/product'
gmake[4]: *** [/opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/hotspot/make/bsd/Makefile:314: productzero] Error 2
gmake[4]: Leaving directory '/opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/jdk8u-jdk8u332-b09/build/openjdk8/hotspot'
gmake[3]: *** [Makefile:261: generic_buildzero] Error 2
gmake[3]: Leaving directory '/opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/jdk8u-jdk8u332-b09/hotspot/make'
gmake[2]: *** [Makefile:185: productzero] Error 2
gmake[2]: Leaving directory '/opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/jdk8u-jdk8u332-b09/hotspot/make'
gmake[1]: *** [HotspotWrapper.gmk:45: /opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/openjdk8/build/openjdk8/hotspot/_hotspot.timestamp] Error 2
gmake[1]: Leaving directory '/opt/local/var/macports/build/_opt_PPCLeopardPorts_java_openjdk8/openjdk8/work/jdk8u-jdk8u332-b09/make'
gnumake: *** [hotspot-only] Error 2
```
So an identical failure.

**Comment by barracuda156** [comment]
> @usersxx. This is dtrace stuff. I suppose the interface has changed between the dtrace implementation used with the old Xcode and what is currently used on Mac-OSX. I have never been able to successfully compile JDK 1.7 or 1.8 on powerpc with dtrace. In my 1.8 port I have disabled it completely, which includes numerous changes to the makefiles since it is a hard-coded switch/assumption that Sun and Mac use dtrace. It is a nice to have but as far as I understand not essential voor a functional JDK.

@nilsvanvelzen So basically just disabling `dtrace` should get us through?

**Comment by nilsvanvelzen** [comment]
> > @usersxx. This is dtrace stuff. I suppose the interface has changed between the dtrace implementation used with the old Xcode and what is currently used on Mac-OSX. I have never been able to successfully compile JDK 1.7 or 1.8 on powerpc with dtrace. In my 1.8 port I have disabled it completely, which includes numerous changes to the makefiles since it is a hard-coded switch/assumption that Sun and Mac use dtrace. It is a nice to have but as far as I understand not essential voor a functional JDK.
> 
> @nilsvanvelzen So basically just disabling `dtrace` should get us through?

No that is only part of the solution. See my earlier post that contained a diff file. For the hotspot some other issues in de c-code need to be fixed as well.  https://github.com/macports/macports-ports/pull/14662#issuecomment-1114521732. After the hotspot there is the challenge of a (headless) jdk. I'm at the point to a version where it does compile but that crashes when I try to use it. However it involves XCODE specific C code to which I'm not familiar so I have not been able to fix it (and my time is limited)

**Comment by barracuda156** [comment]
@usersxx @nilsvanvelzen This won’t help us in any way, right? https://bell-sw.com/pages/downloads/#/java-8-lts
The source has `ppc64`, but for Linux.

**Comment by nilsvanvelzen** [comment]
> @usersxx @nilsvanvelzen This won’t help us in any way, right? https://bell-sw.com/pages/downloads/#/java-8-lts
> The source has `ppc64`, but for Linux.

I do not think so. Most probably just a fork of openjdk and the processor itself is not the biggest challenge(since the zero hotspot can be used). The problem is more related to code that is too modern for the latest Xcode on 10.5.

**Comment by barracuda156** [comment]
@nilsvanvelzen Got it. Then doing without Xcode sounds like a better pathway to try. We got `gcc11` now on 10.5/10.6 PPC.

**Comment by mascguy** [comment]
Folks, where do things stand with this PR?

**Comment by barracuda156** [comment]
@mascguy Well, there were no updates from @usersxx since then.

I don’t see any reasons not to approve it though. For one thing, it brings `openjdk7` onto PPC, which is already good. And while `openjdk8` build still fails, it doesn’t hurt having a PPC case: maybe we or someone else gonna fix it eventually.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
