### PR TITLE
py-awscli: update to 1.16.303

### PR DESCRIPTION
**Pull request by emcrisostomo**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G2022
Xcode 11.3 11C29

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by emcrisostomo** [comment]
Some builds have timed-out, I would merge. Does it look good to you @reneeotten?

**Comment by emcrisostomo** [comment]
Hi @reneeotten, I've actually tested some commands of the AWS CLI on my machine. Running `port test` on `py37-botocore` on my machine fails with an unsatisfied dependency and here's the relevant fragment of the `Portfile`:

```
    depends_test-append \
                    port:py${python.version}-behave \
```

It seems like `py-behave` is not in the ports tree, as far as I can tell. Perhaps somebody is working on it and hasn't pushed yet?

**Comment by reneeotten** [comment]
> Hi @reneeotten, I've actually tested some commands of the AWS CLI on my machine. Running `port test` on `py37-botocore` on my machine fails with an unsatisfied dependency and here's the relevant fragment of the `Portfile`:
> 
> ```
>     depends_test-append \
>                     port:py${python.version}-behave \
> ```
> 
> It seems like `py-behave` is not in the ports tree, as far as I can tell. Perhaps somebody is working on it and hasn't pushed yet?

I remember to have merged a PR with that port in it (https://github.com/macports/macports-ports/pull/5879). For some reason it wasn't part of that PR at the end anymore.... @essandess do you have that Portfile still somewhere and, if so, can you please submit a PR with it. Otherwise, we'll just have to add it.

**Comment by essandess** [comment]
> I remember to have merged a PR with that port in it (#5879). For some reason it wasn't part of that PR at the end anymore.... @essandess do you have that Portfile still somewhere and, if so, can you please submit a PR with it. Otherwise, we'll just have to add it.

It must've fallen through the cracks. I still have a local copy. See https://github.com/macports/macports-ports/pull/6004

**Comment by emcrisostomo** [comment]
Great, thank you all guys. I'll test it and merge if everything is ok.

**Comment by emcrisostomo** [comment]
I've tried testing the `py37-botocore` package and a lot of tests fail and the errors seem to indicate a credential misconfiguration. E.g.:

```
:info:test botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

I've got `~/.aws/credentials` configured with an user with administrator access, and indeed the AWS CLI seems to work correctly. @essandess, looking at #6004 I've got the impression you've successfully tested boto. If that's true, do you have any insights to give?

**Comment by essandess** [comment]
> I've tried testing the `py37-botocore` package and a lot of tests fail and the errors seem to indicate a credential misconfiguration. … looking at #6004 I've got the impression you've successfully tested boto.

Most of the tests run successfully, some fail. The `boto` package is working with the actual Python packages that I’ve used. The three seconds I spent looking at test output I concluded that it’s likely an upstream issue.

**Comment by emcrisostomo** [comment]
Thanks @essandess, I suspect the same thing's happening here. I'm merging this PR then.

**Pull request merged**
