### PR TITLE
R: update recently updated packages, add support for tests

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Several new ports are dependencies for testing.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@herbygillot This should be good to merge!

**Comment by herbygillot** [comment]
We hit that limit with Github on this one, unfortunately

**Comment by barracuda156** [comment]
> We hit that limit with Github on this one, unfortunately

@herbygillot No issues, gimme a minute, I drop some.

**Comment by barracuda156** [comment]
@herbygillot Could you check now? CI passed (expectedly, I only removed some ports).

I will another PR then with remaining ones.

**Pull request merged**
