### PR TITLE
py-*: remove obsolete py26/py33 subports from various Python ports

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR does some initial housekeeping on various Python ports in the tree. In particular, it removes py26/py33 subports from ports that (i) are ```nomaintainer``` and (ii) have nothing depend on them. No other changes were made, so if a port doesn't build it should not be caused by this PR. 

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65
Xcode 9.4.1 9F2000

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
I didn't squash commits yet, if this PR is deemed useful and commits need to be squashed I will do so.
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. It's extensive enough that I'd like a couple more people to comment but I think this is pretty clearly something we should commit.

Points of curiosity:
1. How many `nomaintainer` Python packages are there that have 26/33 but that something else depends on?
2. How many maintained Python packages that nothing depends on have 26/33?
3. How many maintained python packages are dependencies but have 26/33 versions?

**Comment by reneeotten** [comment]
@pmetzger I have been using a probably rather inefficient script to check for python packages with py26/py33 subports (and whether they're maintained and have dependencies). I didn't separate all three categories, but in total there are about ~200 ports left that have traces of py26/py33 divided over the three categories, with probably most in number 2 (or only have py26 subports, see also https://trac.macports.org/ticket/56853).

To keep the buildbot happy and PRs of reasonable size, I started with the easiest category (i.e., no maintainer and dependencies). Next will be maintained, but no dependencies - we'll see how that goes..

**Comment by pmetzger** [comment]
> To keep the buildbot happy and PRs of reasonable size, I started with the easiest category (i.e., no maintainer and dependencies). Next will be maintained, but no dependencies - we'll see how that goes.

It will probably require the full three-day timeout unfortunately, because most people will fail to respond meaningfully to being tagged on the pull request.

**Comment by pmetzger** [comment]
Merged. Thank you, @reneeotten!

**Pull request merged**
