### PR TITLE
ghc: Update to version 9.6.5

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
Checking the log on the macOS 13 runner, dependency poppler is failing to build because:

```
[ 98%] Generating Poppler-0.18.gir
cd /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/build/glib && /opt/local/bin/g-ir-scanner --add-include-path=/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib --warn-all --library-path=/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/build/glib --namespace=Poppler --nsversion=0.18 --no-libtool --library=poppler-glib --library=poppler --include=GObject-2.0 --include=Gio-2.0 --include=cairo-1.0 --pkg-export=poppler-glib --c-include=poppler.h -v -I/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0 -I/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/fofi -I/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/goo -I/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/poppler -I/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/build -I/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/build/poppler -I/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib -I/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/build/glib -I/opt/local/include -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include -I/opt/local/include/cairo -I/opt/local/include/cairo -I/opt/local/include -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include -I/opt/local/include/pixman-1 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include -I/opt/local/include/libpng16 -I/opt/local/include -L/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/build -L/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/build/glib /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-action.cc /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-date.cc /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-document.cc /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-page.cc /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-attachment.cc /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-form-field.cc /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-annot.cc /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-layer.cc /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-movie.cc /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-media.cc /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler.cc /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-cached-file-loader.cc /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-input-stream.cc /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-structure-element.cc /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-action.h /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-date.h /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-document.h /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-page.h /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-attachment.h /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-form-field.h /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-annot.h /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-layer.h /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-movie.h /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-media.h /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler.h /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/poppler-24.04.0/glib/poppler-structure-element.h /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/build/glib/poppler-enums.c /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/build/glib/poppler-enums.h /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/build/glib/poppler-features.h /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/build/glib/poppler-macros.h --output /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_graphics_poppler/poppler/work/build/glib/Poppler-0.18.gir
Traceback (most recent call last):
  File "/opt/local/bin/g-ir-scanner", line 99, in <module>
    from giscanner.utils import dll_dirs
  File "/opt/local/lib/gobject-introspection/giscanner/utils.py", line 385, in <module>
    import distutils.cygwinccompiler
ModuleNotFoundError: No module named 'distutils'
```

I thought [I fixed that months ago](https://trac.macports.org/ticket/69105).

**Comment by ryandesign** [comment]
The recent gobject-introspection update has been reverted so if you rebase onto the latest changes from master and force push hopefully it will work now.

**Comment by essandess** [comment]
FWIW I'm getting a local build failure and am of the mind to blame upstream and post an issue.
```sh
:info:build # cabal-configure (for _build/stage0/libraries/mtl/setup-config)
:info:build dieVerbatim: user error (Error: hadrian:
:info:build '/opt/local/var/macports/build/_opt_local_ports_lang_ghc/ghc/work/.home/.cabal/bin/ghc'
:info:build exited with an error:
:info:build ghc: can't find a package database at
:info:build _build/stage0/libraries/ghc-boot-th/build/package.conf.inplace
:info:build )
```

**Comment by essandess** [comment]
See https://gitlab.haskell.org/ghc/ghc/-/issues/24694

**Comment by reneeotten** [comment]
feel free to reopen this PR once you had the time to fix this.

**Pull request closed without merging**
