### PR TITLE
py-wxpython-4.0: update to 4.2.2

### PR DESCRIPTION
**Pull request by nilason**
###### Type(s)

Update `py-wxpython-4.0` to 4.2.2.

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.7.1 23H222 arm64
Xcode 16.1 16B40

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by nilason** [comment]
I have tested this with `grass`, without issues.

I invite @ra1nb0w for testing with `kicad`, and @joefowler with `py311-wxmplot` and `py311-wxutils`.

**Comment by reneeotten** [comment]
Are you sure this builds on macOS 15? That's I think where issues were reported on Trac.

**Comment by nilason** [comment]
> Are you sure this builds on macOS 15? That's I think where issues were reported on Trac.

No, I'm not sure, I can't test this on 15 (still on 14), so therefore I didn't mention the ticket in commit message.

**Comment by nilason** [comment]
I did add a comment in https://trac.macports.org/ticket/71150.

**Pull request merged**
