### PR TITLE
bmon: update to 4.0

### PR DESCRIPTION
**Pull request by l2dy**

### CODE REVIEW

**Comment by g5pw** [comment]
@l2dy thanks for the code! Since this port has no maintainer, would you like to adopt it? :)

**Comment by l2dy** [comment]
@g5pw How can I list and livecheck all ports I maintain? I'm worried that I might forgot a port and leave it not updated. If there is a easy way I'd surely adopt this port.

**Comment by g5pw** [comment]
> @g5pw How can I list and livecheck all ports I maintain?

You can use the pseudo-portname selector 'maintainer' or 'maintainers', for example:
`port livecheck maintainer:g5pw`

**Comment by l2dy** [comment]
Thanks. Port adopted.

**Comment by g5pw** [comment]
Hurray for adopted ports! 😄 Thanks for your contribution. Merging.

**Pull request merged**
