### PR TITLE
limesuite: add application bundle

### PR DESCRIPTION
**Pull request by ra1nb0w**
#### Description

create application bundle to easily launch the GUI

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.15 19A558d
Xcode 11.0 11A419c

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
very nice! You might also appreciate the app 1.0 PortGroup that tries to do a lot of this kind of work in a PG. We made some enhancements to that PG last year to improve it. IMHO that app 1.0 PG is quite underutilized for the macOS experience...

**Comment by ra1nb0w** [comment]
@kencu WOW!! thank you!
I moved to that. Just one suggestion that should be added to `app`. Sometimes I need to use:
```
        <key>NSRequiresAquaSystemAppearance</key>
        <string>True</string>
```
and from mojave should be nice to implement the permission, like
```
        <key>NSMicrophoneUsageDescription</key>
        <string>Allow for using Sound input devices</string>
```
do you want that I create a PRs about those?

**Comment by kencu** [comment]
I think people are quite responsive to enhancements that improve the app PG. Sometimes it takes a bit of thinking to implement things right, as many are not as familiar with some of those more esoteric settings. Also, some should be system defaults probably, others app PG options.

Sure, PR away!

**Comment by kencu** [comment]
Your suggested enhancements might use this commit <https://github.com/macports/macports-ports/commit/146dbe01ad7b85a6b0b7db3af78a59e5a4927bb1> as a template, perhaps.

**Comment by michaelld** [comment]
@ra1nb0w any more changes here?

**Comment by ra1nb0w** [comment]
> Your suggested app PG enhancements might use this commit [146dbe0](https://github.com/macports/macports-ports/commit/146dbe01ad7b85a6b0b7db3af78a59e5a4927bb1) as a template, perhaps.

thank you!

**Comment by ra1nb0w** [comment]
> @ra1nb0w any more changes here?

No. seems ok to me.

**Comment by ra1nb0w** [comment]
thank you!

**Comment by ra1nb0w** [comment]
> Sure, PR away!

FYI: https://github.com/macports/macports-ports/pull/5328

**Pull request merged**
