### PR TITLE
openjdk-source: remove build.post_args

### PR DESCRIPTION
**Pull request by usersxx**
Removed CONF_CHECK=ignore to do a more proper build and added openjdk8-java

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65 x86_64
Xcode Command Line Tool Only

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by usersxx** [comment]
@ryandesign , based on your [MacOSX.sdk port](https://github.com/macports/macports-ports/blob/master/devel/MacOSX.sdk/Portfile), I would like to ask you that how did you get the [.pkg file](https://github.com/macports/macports-ports/blob/master/devel/MacOSX.sdk/Portfile#L198) from the [.dmg file](https://github.com/macports/macports-ports/blob/master/devel/MacOSX.sdk/Portfile#L154)

**Comment by ryandesign** [comment]
Well you can read the code and find out. 😄 If you just want MacPorts to copy everything from the dmg into `${worksrcpath}` all you have to do is say `use_dmg yes`. I only wanted to copy specific things from the dmg which is why the MacOSX.sdk port doesn't use `use_dmg yes`.

**Comment by usersxx** [comment]
> Well you can read the code and find out. 😄 If you just want MacPorts to copy everything from the dmg into `${worksrcpath}` all you have to do is say `use_dmg yes`. I only wanted to copy specific things from the dmg which is why the MacOSX.sdk port doesn't use `use_dmg yes`.

Thanks

**Comment by ryandesign** [comment]
(That port has its own [extract code](https://github.com/macports/macports-ports/blob/master/devel/MacOSX.sdk/Portfile#L451-L476) for handling the various types of distfiles it will encounter.)

**Pull request closed without merging**
