### PR TITLE
qt5-qtwebengine: update to 5.15.16

### PR DESCRIPTION
**Pull request by chrstphrchvz**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [x] security fix

###### Tested on

macOS 12.7.1 Intel
Xcode 14.2
`configure.sdk_version=13.1`
simplebrowser.py from py311-pyside2:
Screen Shot 2023-11-17 at 1 19 39 PM

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
I am skipping the CI. It is going to fail at least for the same reason as during the last update: https://github.com/macports/macports-ports/pull/20264#issuecomment-1703701842

**Comment by chrstphrchvz** [comment]
The CI ran anyway and failed as predicted: https://github.com/macports/macports-ports/actions/runs/6905572095

**Comment by chrstphrchvz** [comment]
@pmetzger I think this is ready to merge.

**Comment by reneeotten** [comment]
> @pmetzger I think this is ready to merge.

@MarcusCalhoun-Lopez hasn't been around much lately but I'd suggest to merge at the end of the weekend to give an opportunity to respond.

**Pull request merged**
