### PR TITLE
py-matplotlib: update to 2.2.4 and 3.0.3

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
- update to latest versions: 2.2.4 for PY27/PY34, 3.0.3 for all others
- refresh patches
- assume maintainership

###### Tested on

macOS 10.14.3 18D109
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
The build failure on Azure looks to be:

```
byte-compiling /opt/local/var/macports/build/_Users_vsts_agent_2.147.1_work_1_s_python_py-matplotlib/py37-matplotlib/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mpl_toolkits/mplot3d/proj3d.py to proj3d.cpython-37.pyc
error: Failed to download jquery-ui.  Please download https://jqueryui.com/resources/download/jquery-ui-1.12.1.zip and extract it to /opt/local/var/macports/build/_Users_vsts_agent_2.147.1_work_1_s_python_py-matplotlib/py37-matplotlib/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/backends/web_backend/.

```

**Comment by yan12125** [comment]
I cancelled remaining builds on Travis CI as previous builds for this PR timed out and provide no useful information. On the other hand, Azure Pipelines reports an error:

> error: Failed to download jquery-ui.  Please download https://jqueryui.com/resources/download/jquery-ui-1.12.1.zip and extract it to /opt/local/var/macports/build/_Users_vsts_agent_2.147.1_work_1_s_python_py-matplotlib/py37-matplotlib/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/backends/web_backend/.

Could you have a look? @reneeotten

**Comment by mf2k** [comment]
@yan12125: Hah, beat you by a few minutes!

**Comment by reneeotten** [comment]
right.... ```jquery-ui``` is no longer in the GitHub tarball (as the release notes stated). I didn't see any issues locally though, but after another look it's probably because it was using a cached version on my local machine. Sorry... I will take another look, perhaps just switching to PyPI is sufficient as there the files might be included (at least from reading the release notes, haven't checked yet).

**Comment by reneeotten** [comment]
the PyPI files indeed include ```jquery-ui```, let's see if switching makes everyone happy ;)

**Comment by reneeotten** [comment]
both version 2.2.4 and 3.0.3 from PyPI contain ```jquery-ui``` and it builds now on Azure pipelines for all versions except on PY34. I have a hard time seeing why this is the case. From the log is shows that it's trying to download ```jquery-ui```, which shouldn't happen as it is already present in the source...

**Comment by yan12125** [comment]
There might be some bug in Python 3.4. Given the 3.4 branch of CPython will reach end-of-life in 10 days [1], how about just moving the py34 variant to the graveyard instead of spending time on investigating the issue?

[1] https://devguide.python.org/

**Comment by reneeotten** [comment]
well, moving of ```py34``` subports to the ```py-graveyard``` is a lot more involved than only moving matplotlib. I have done most of that work for py26/py33 a while back and it isn't much fun... That process should -in my opinion- be done all at once, including removing all the python34 variants; I suppose that the exact decision on when that should happen might need some discussion on the mailinglist. For now, I will push a workaround in a few minutes, just testing the last Python versions locally.

**Comment by mf2k** [comment]
That is a good point. 

```
$ port echo depends:py34-matplotlib
py34-astlib                     
py34-astroML                    
py34-cartopy                    
py34-control                    
py34-descartes                  
py34-healpy                     
py34-matplotlib-basemap         
py34-mpld3                      
py34-nltk                       
py34-pandas                     
py34-pytest-mpl                 
py34-seaborn                    
py34-spacepy                    
py34-spyder                     
py34-aplpy                      
py34-memprof                    
py34-pyregion                   
py34-scikit-image               
py34-yt                         
```

I personally don't think we should let problems with py34 hold this up.

**Comment by reneeotten** [comment]
> I personally don't think we should let problems with py34 hold this up.

I don't think there are any problems left ; I am fairly confident that the Azure pipelines will finish with the last commit I added, but let's wait and see!

**Comment by mf2k** [comment]
Thank you!

**Pull request merged**
