### PR TITLE
py-sip: backport upstream fixes

### PR DESCRIPTION
**Pull request by i0ntempest**
Backport changes between 6.6.1 and a59cb21d25c6, fixes building QGIS3

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.4 21F79 x86_64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
@i0ntempest I'll take a closer look once I am behind a computer. But my initial response is "I doubt we want to add a 2,500+ line patchfile to essentially make this a -devel port". The QGIS3 package should not be using unreleased features of SIP so I personally consider the fact that it doesn't build with a released version "their" problem.

**Comment by i0ntempest** [comment]
@reneeotten True, I don't want add this huge patch file either. I tried adding smaller patches to the few file mentioned in the error I got: I add a patch, I get a different error; I add another one, I get a different error... eventually I ran out of patience.
Also if you see their commit messages you'll see a bunch of them are bug fixes.

**Comment by reneeotten** [comment]
hi @i0ntempest, I do not want to add this patch and then still pretend that we install version 6.6.1. I am okay with adding a `-devel` port so that one can change for now the dependency in `qgis3` to use that one. I will make that change that will -once committed- close this PR. Is that okay with you?

**Comment by i0ntempest** [comment]
@reneeotten Awsome, I see it's in now. I'll update QGIS3 so it can use the devel port.

**Pull request closed without merging**
