### PR TITLE
deno: add support for aarch64

### PR DESCRIPTION
**Pull request by davidbailey00**
#### Description

Add support for `aarch64` to deno

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.3 Beta (20E5172i)
Xcode CLT 12.5 beta

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`? n/a (no tests)
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by davidbailey00** [comment]
seems like the failure is due to a typo of `supported_arches` instead of `supported_archs` in an unrelated port

**Comment by herbygillot** [comment]
That was me 😑.  Corrected, please rebase.

**Comment by davidbailey00** [comment]
no worries, I've rebased now!

**Comment by herbygillot** [comment]
Thank you @davidbailey00

**Pull request merged**
