### PR TITLE
Fix typo: Change "XCode" to "Xcode"

### PR DESCRIPTION
**Pull request by ryandesign**

### CODE REVIEW

**Comment by pmetzger** [comment]
With one exception, these are all changes to comments and messages. I don't think we actually need maintainer approval for something that's so obviously correct and so harmless, so I'm inclined to merge this later today unless there are objections.

**Comment by Schamschula** [comment]
I'm OK with the change (as it is in a comment, in my case), but also agree that maintainer approval shouldn't be needed here.

**Comment by danielluke** [comment]
I'm OK with the change for apr. I'm strongly opposed to merging changes in violation of our policy (https://guide.macports.org/chunked/project.update-policies.html#project.update-policies.nonmaintainer). For ports that don't have openmaintainer/nomaintainer, we should abide by the maintainer timeout rule for changes like this since they aren't fixing critical brokenness. (If we want to change the policy, we should have a discussion on the mailing list).

**Comment by mf2k** [comment]
Daniel is correct on this issue based on that stated policy. 

I think the main argument against committing even minor changes without consent is that a maintainer might be working on other changes to the port, and if the Portfile gets updated, then it messes up their changes and wastes their time.

**Comment by pmetzger** [comment]
This is less of a problem in git than in the past. Generally at worst you'll do a pull and get a conflict, which you'll resolve in your editor in a few moments.

**Comment by danielluke** [comment]
We should follow our policy and/or change it if community members desire it to change.

Almost all of my ports are not 'openmaintainer' - because I provide support to consumers of those ports and I don't want changes to them that I don't know about.

Maintainers may have many reasons for choosing how they maintain their ports - I think a reasonable argument can be made for many different policy positions, but we owe it to our volunteer community to apply our policies consistently.

**Comment by jeremyhu** [comment]
LGTM

**Comment by pmetzger** [comment]
Merged. Thanks as always, @ryandesign!

**Pull request merged**
