### PR TITLE
caddy: new port

### PR DESCRIPTION
**Pull request by mohd-akram**
###### Tested on
macOS 10.14.3 18D109
Xcode 10.1 10B61

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
builds and runs on Mojave. 

Is any of that launchd stuff useful? Should there be a startup item or an option for same to launch this? The port doesn't indicate that this capability is included in the distribution.

I haven't the foggiest idea how to run the (extensive) test suite that seems to be included with this port. Perhaps that might be reassuring. I don't really speak `go` at this point.

**Comment by mohd-akram** [comment]
Startup item might be useful, but the last time I messed with them I couldn't get them to work. I don't speak go either so I just learned enough to get it to build :D

**Comment by kencu** [comment]
@l2dy -- I think you're the `go` expert around MacPorts. Is it easy to run the test suite on `go` ports like this?

**Comment by l2dy** [comment]
@kencu Try `go test -race ./...` in `${worksrcpath}`, see https://github.com/mholt/caddy/blob/v0.11.4/.travis.yml#L34.

**Pull request merged**
