### PR TITLE
mediainfo: update to 0.7.98

### PR DESCRIPTION
**Pull request by l2dy**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.11
Xcode 8.2.1

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vs install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ctreleaven** [comment]
Re the failed CI build, is this a real problem or just an issue with the CI system?

**Comment by l2dy** [comment]
@ctreleaven It's a real problem on OS X 10.10.

**Comment by l2dy** [comment]
https://paste.macports.org/3776fa9b4b11
```
libtool: link: /usr/bin/clang++ -arch x86_64 -mmacosx-version-min=10.5 -O2 -DUNICODE -DUNICODE -DSIZE_T_IS_LONG -mmacosx-version-min=10.5 -o mediainfo CLI_Main.o CommandLine_Parser.o Help.o Core.o  -framework CoreFoundation /opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_multimedia_mediainfo/mediainfo/work/MediaInfo_CLI_GNU_FromSource/MediaInfoLib/Project/GNU/Library/.libs/libmediainfo.a -lz /opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_multimedia_mediainfo/mediainfo/work/MediaInfo_CLI_GNU_FromSource/ZenLib/Project/GNU/Library/.libs/libzen.a -lpthread -lstdc++
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mediainfo] Error 1
Problem while compiling MediaInfo (CLI)
```

**Comment by mojca** [comment]
It looks as if `-mmacosx-version-min=10.5` shouldn't be used.

**Comment by l2dy** [comment]
@ctreleaven Can I commit the lint fix (trailing whitespace) separately?

**Comment by ctreleaven** [comment]
@l2dy, sure.  I don't know when I'll get a chance to look at this.  (Just sold a house.)

**Comment by ryandesign** [comment]
The `-mmacosx-version-min=10.5` flag was used in 0.7.97 too, and that built successfully on the buildbot workers, so I assume 0.7.98 will too. Yes, ideally this project would not specify that flag. MacPorts already species the `MACOSX_DEPLOYMENT_TARGET` environment variable, whose value would be used if the project did not override it with `-mmacosx-version-min`. The problem is probably that /usr/lib/libgcc_s.10.5.dylib does not exist on the Travis build machines. I don't know why. Maybe it's part of the command line tools and they don't have those installed, or maybe it's one of the "additional components" that get installed when you launch Xcode for the first time, and they have not launched Xcode on their machines.

**Comment by l2dy** [comment]
There's only `libgcc_s.10.5.tbd` on OS X 10.10 on Travis CI. Should I report this to https://github.com/travis-ci/travis-ci?

https://travis-ci.org/macports-staging/macports-ports/jobs/266649829#L53

**Pull request merged**
