### PR TITLE
libcxx-powerpc: libc++ and libc++abi for PowerPC

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

(Don’t really know why we did not make this earlier.)

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by catap** [comment]
I'm ok to be co-maintainer

**Comment by kencu** [comment]
any test results at all?

**Comment by barracuda156** [comment]
> any test results at all?

@kencu I am rebuilding `gcc12` now to see if it works with `libc++`. Obviously clangs won’t work, they never did.
Or how do you suggest to test it otherwise?

**Comment by barracuda156** [comment]
@kencu Seems to work, BUT we have to change @rpath to absolute path (will fix now).

Example:
```
36-250% otool -L /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_archivers_unrar/unrar/work/destroot/opt/local/bin/unrar
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_archivers_unrar/unrar/work/destroot/opt/local/bin/unrar:
	/opt/local/lib/libMacportsLegacySupport.dylib (compatibility version 1.0.0, current version 1.1.99)
	/opt/local/libexec/libcxx-7.1.1/lib/libc++.1.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/libexec/libcxx-7.1.1/lib/libc++abi.1.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/lib/libgcc/libgcc_s.1.1.dylib (compatibility version 1.0.0, current version 1.1.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 117.0.0)
```
```
36-250% file /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_archivers_unrar/unrar/work/destroot/opt/local/bin/unrar
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_archivers_unrar/unrar/work/destroot/opt/local/bin/unrar: Mach-O ppc_7400 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK>
```
```
36-250% /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_archivers_unrar/unrar/work/destroot/opt/local/bin/unrar

UNRAR 6.24 freeware      Copyright (c) 1993-2023 Alexander Roshal

Usage:     unrar <command> -<switch 1> -<switch N> <archive> <files...>
               <@listfiles...> <path_to_extract/>

<Commands>
  e             Extract files without archived paths
  l[t[a],b]     List archive contents [technical[all], bare]
  p             Print file to stdout
  t             Test archive files
  v[t[a],b]     Verbosely list archive contents [technical[all],bare]
  x             Extract files with full path

<Switches>
  -             Stop switches scanning
  @[+]          Disable [enable] file lists
  ad[1,2]       Alternate destination path
  ag[format]    Generate archive name using the current date
  ai            Ignore file attributes
  ap<path>      Set path inside archive
  c-            Disable comments show
  cfg-          Disable read configuration
  cl            Convert names to lower case
  cu            Convert names to upper case
  dh            Open shared files
  ep            Exclude paths from names
  ep3           Expand paths to full including the drive letter
  ep4<path>     Exclude the path prefix from names
  f             Freshen files
  id[c,d,n,p,q] Display or disable messages
  ierr          Send all messages to stderr
  inul          Disable all messages
  kb            Keep broken extracted files
  me[par]       Set encryption parameters
  n<file>       Additionally filter included files
  n@            Read additional filter masks from stdin
  n@<list>      Read additional filter masks from list file
  o[+|-]        Set the overwrite mode
  ol[a]         Process symbolic links as the link [absolute paths]
  op<path>      Set the output path for extracted files
  or            Rename files automatically
  ow            Save or restore file owner and group
  p[password]   Set password
  r             Recurse subdirectories
  sc<chr>[obj]  Specify the character set
  si[name]      Read data from standard input (stdin)
  sl<size>      Process files with size less than specified
  sm<size>      Process files with size more than specified
  ta[mcao]<d>   Process files modified after <d> YYYYMMDDHHMMSS date
  tb[mcao]<d>   Process files modified before <d> YYYYMMDDHHMMSS date
  tn[mcao]<t>   Process files newer than <t> time
  to[mcao]<t>   Process files older than <t> time
  ts[m,c,a,p]   Save or restore time (modification, creation, access, preserve)
  u             Update files
  v             List all volumes
  ver[n]        File version control
  vp            Pause before each volume
  x<file>       Exclude specified file
  x@            Read file names to exclude from stdin
  x@<list>      Exclude files listed in specified list file
  y             Assume Yes on all queries
```
(I had to fix paths manually to make it work here.)

**Comment by barracuda156** [comment]
Perhaps it also gonna make a better sense to install into `${prefix}` instead of `${prefix}/libexec/libcxx-${version}`. As long as the port is explicitly for PowerPC, we can be sure that no conflict can arise, and as long as there is only one such port, we do not need versioned installations.

Otherwise with libexec we gonna need to pass custom ldflags every time. (Of course I forgot about that at first, got errors that `-lc++` not found, compiler does not work.)

**Comment by barracuda156** [comment]
P. S. I can confirm that `unrar` linked to `libc++` actually works: I downloaded a random .rar archive and unpacked it with no issues.

**Comment by pmetzger** [comment]
@kencu Can you be in charge of deciding when this should be committed?

**Comment by barracuda156** [comment]
@kencu I guess, this should build on Leopard and provisionally work with gcc (though that would require a newer gcc than gcc7, obviously).

@pmetzger Well, in my opinion, there should be no harm in having this merged, since a) it is explicitly for `powerpc`, so no one gonna install that on other systems, b) nothing depends on it, and we do not enable it in gcc here, c) nothing depends on `libc++` on PPC systems at all. The only thing what this PR does is to make `libc++` available to experiment with on PPC systems. It cannot break anything.

P. S. While I switched it to install in prefix, I am fine with a dedicated subprefix in libexec, if anyone thinks that is preferable.

**Comment by barracuda156** [comment]
Turned out, that setting install paths via patching does not make those correct in result.
I will switch now to `install_name_tool` to fix those at post-destroot.

**Comment by barracuda156** [comment]
@kencu Just to be clear, I am not gonna switch anything on PPC to use libcxx, or enable it in gcc variant (until that is well-tested), or enable it in compilers PG etc. As such, this ports changes nothing at all, even if installed, and certainly not otherwise. Nothing is made to depend on it. The only point at the moment is make it available for testing for those who may be interested.
IMO, it is perfectly safe to have merged, for these reasons.

**Comment by kencu** [comment]
You and @catap thought that about darwin-xtools as well, as a variant for cctools.

Until somebody actually installed it as their default variant for cctools -- on 10.15 of all things -- and then started posting tickets about how the cctools assembler in MacPorts was totally hosed.

@jmroot and @ryandesign got involved trying to figure out what the heck was going on with the user's apparently weirdly broken system, until we realized he had somehow installed cctools +xtools and hosed himself.


So -- some user is going to install this libcxx-powerpc, have no idea what the h3ll is going on with it, and get themselves all messed up in some way.

For -- nothing -- as MacPorts doesn't use it.

If you and others want to play, -- play. Nobody is stopping you.

But don't push stuff like this, and cctools +xtools, to MacPorts repo "just for fun" , to "try it out", and "it can't hurt", and "perfectly safe"... 

because it frankly is none of those things.

IMHO. 

Which is one of the 10 reasons I'm not shepherding this one :>

**Comment by kencu** [comment]
In fact -- MacPorts is rather due for the "grand simplification" I believe.

Every port that has no obvious purpose is dumped. Every variant that isn't actively used is removed. Every portgroup that has no defendable purpose being there is removed. Every simple environment variable that is supposed to be set through a silly arcane configure.XYZ command instead of just being set directly is simplified, and the arcand portfile commands removed.

The "Grand Purge" is coming to MacPorts, because -- it is long, long, long overdue, frankly.

**Comment by barracuda156** [comment]
@kencu The obvious difference is that there is nothing to install this libcxx with, since nothing is made to depend on it. It is impossible to build ports against it without explicit manual changes to Macports setup. So it is *not* like darwin-xtools case (which should be reported to Iain, I believe, since anything besides 10.6 ppc and possibly 10.4 is supposed to be supported, AFAIU).

If you think it makes sense, we can add a warning to notes to this port.

**Comment by barracuda156** [comment]
> In fact -- MacPorts is rather due for a "grand simplification" I believe.
> 
> Every port that has no obvious purpose is obsoleted. 
> 
> Every variant that isn't actively used is removed.

That way you can fit Macports to your personal needs, sure enough, but it will inevitably make the product worse overall, since no one has the accurate information to begin with. Something not having an obvious purpose for one individual does not equal to not having obvious purpose for someone else.
Central planning always fails.

**Comment by barracuda156** [comment]
@kencu P. S. The odd thing is that you seem to apply completely different standards to literally every PowerPC-specific submission than to anything else. We have numerous cases of breaking commits, on a regular basis (I hope you don’t need a list of examples, I would prefer not pointing to specific instances), we got numerous unsafe, questionable and breaking hacks, yet I do not see your objections there, or at least not with this intensity. We have things broken on PowerPC for months or years with no one being concerned (for example, ppc64 being the case, and I pointed at specific issues multiple times – no one bothered to try fixing those).

Yet whenever we try to improve something for PowerPC, there is every reason to postpone that indefinitely. Anything else can be committed ”with verification of checksums”, but for PowerPC we need a comprehensive testing with every possible OS and compiler combo, from multiple people, with screenshots and vids to support every statement. (In fact, in some instances those were provided, with no effect.)

I do not get this attitude.

The eventual and inevitable outcome of such an approach will be merely to discourage contributions.

**Comment by kencu** [comment]
> @kencu P. S. The odd thing is that you seem to apply completely different standards to literally every PowerPC-specific submission than to anything else. 

Thanks -- glad to be helpful :>

And @pmetzger -- this is why I'm not taking responsibility for this.

**Comment by kencu** [comment]
> Yet whenever we try to improve something for PowerPC, there is every reason to postpone that indefinitely. 

"Whenever we try to improve something" ... we being you, I presume -- well so far you have done absolutely nothing useful for the PowerPC toolchains. It pretty much sits exactly where I left it two years ago. Catap pushed my gcc10bootstrap and clang11bootstrap ports, and that is about it.

So be cautious about how you throw that "we" around, as that "we" is really -- so far -- me.

No I assume you are talking about your PR to attempt to upgrade  Leopard PPC to libgcc13... I wish you would/could finish that, but ... it's not done.

You seem to feel that just because you PR'd that, incomplete as it is, it should be pushed. That is not how this works.  Someone will eventually do the proper work to update older systems to a newer gcc version. I did the last 10 updates.

**Comment by kencu** [comment]
Anyway, once again, sucked into yet another pointless discussion.

My PowerPC systems run Debian now.

Signing off this.

**Comment by pmetzger** [comment]
Okay, given that @kencu doesn't want to be involved, I'm going to have to accept someone else's word for what the state of this is like. Not sure how to figure it out, I'm not able to make a judgement on my own. I'm inclined to simply take @catap and @barracuda156 at their word provided you guys are willing to accept responsibility for any fallout.

**Comment by catap** [comment]
@pmetzger this can be done on antoher way: add this as parallel implementation for `libcxx` port. Right now `libcxx` contains the `if` which can be extened to include that changes into original `libcxx` port to avoid any future confustion.

**Comment by pmetzger** [comment]
@catap Let me know when you guys have decided on a course of action.

**Comment by barracuda156** [comment]
@catap Sure, we can set archs to ppc ppc64, so that we are 100% sure nothing else is affected. Will do this tonight.

I am not sure re combining two libcxx into one port, since that gonna make things more complicated. Also, libcxx (Intel one) is not CMake-based at the moment. How about we first have this one merged in a safe way, as ppc-only?
Then once the regular libcxx is moved to CMake, and provided no one objects, these can be blended into a single portfile.

@pmetzger Thank you. I hope we gonna finalize this in a day or two.

**Pull request merged**
