### PR TITLE
gstreamer1*: Update to 1.16.1

### PR DESCRIPTION
**Pull request by Gcenx**
gstreamer1 and all plugins updated to 1.16.1 to keep in sync, resolves
https://trac.macports.org/ticket/59428

#### Description

Updates;
- `gstreamer1` (v1.16.1)
- `gstreamer1-gst-libav` (v1.16.1)
- `gstreamer1-gst-plugins-bad` (v1.16.1)
- `gstreamer1-gst-plugins-base` (v1.16.1)
- `gstreamer1-gst-plugins-good` (v1.16.1)
- `gstreamer1-gst-plugins-ugly` (v1.16.1)
resolves https://trac.macports.org/ticket/59428

###### Type(s)

- [x] enhancement

###### Tested on

macOS 10.14.6 18G103
Xcode 10.3 10G8

###### Verification 

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by dbevans** [comment]
Doing test build.

**Comment by Gcenx** [comment]
@dbevans if that was the only issue you encountered I can get that fixed up tonight.

**Comment by dbevans** [comment]
> @dbevans if that was the only issue you encountered I can get that fixed up tonight.

Yes, I did a double check this morning and this seems to be the only issue at the moment.

**Comment by Gcenx** [comment]
@dbevans done, also rebased the commits into a single one so its clean

**Comment by dbevans** [comment]
Merged with minor fix to deactivate hack in commit https://github.com/macports/macports-ports/commit/b649b01287f28442fd290ccff1df282b5ee70b75.  For the hack to work as desired, must compare version against a value that is greater than the old port's version but less than or equal that of the new one.

Thanks for the PR.

**Pull request closed without merging**
