### PR TITLE
ld64: default to ld64-97 for all PPC

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

PR affects _only_ PPC systems.
Default to `ld64-97` for all PPC, since it works the best.
See also: https://github.com/iains/darwin-toolchains-start-here/discussions/37#discussioncomment-3285847

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.5.8 (ppc/ppc64)
Xcode 3.1.4

macOS 10A190 (ppc)
Xcode 3.2

macOS 10.6.8 Server (ppc)
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

@kencu I dunno how to request a review via settings. Could you please take a look?

### CODE REVIEW

**Comment by barracuda156** [comment]
CI error is unrelated to suggested fix:
```
Exit code: 2
  Error: Failed to build ld64-127: command execution failed
  DEBUG: Error code: CHILDSTATUS 4243 2
```
Nothing has been changed in the code of `ld64-127` or any other variant by this PR.

**Comment by kencu** [comment]
using ld64-97, without llvm, is what ppc needs... but ... doing this is not without some possible troubles.

There is an issue having 10.5 Intel and 10.5 PPC diverge in their toolchains like this. Things that are done to make 10.5 PPC ports build may break 10.5 Intel, and vice versa. Having different linkers is difficult to manage elegantly in portfiles. That means the potential for more fragile spaghetti code, which we all dislike.

On the other hand, we see changes being made for 10.5 Intel to support newer clangs, newer ld versions, etc, that will (most likely) never be right for 10.5 PPC. So you could say the toolchains are already diverging.

**Comment by barracuda156** [comment]
@kencu I forgot to revbump ld64 port. Could you help with that, so we don’t need another PR just for that?

**Comment by barracuda156** [comment]
@kencu Thank you!

**Pull request merged**
