### PR TITLE
parallel-netcdf: update to 1.12.3

### PR DESCRIPTION
**Pull request by thiagoveloso**
Also changed the name of the port to reflect changes made by the developer (otherwise the source file could not be downloaded).

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS Ventura 13.5 (22G74)
Xcode 14.3.1 / Command Line Tools 14.3.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by herbygillot** [comment]
Since `pnetcdf` is replacing `parallel-netcdf`, then `parallel-netcdf`'s Portfile should be marked using the `obsolete` portgroup, and a new and separate Portfile should be created for `pnetcdf`.  Details here: https://guide.macports.org/chunked/development.practices.html#development.practices.rename-replace-port

Secondly, since `pnetcdf` is a Github project, its Portfile should use the `github` portgroup and `github.setup`.

**Comment by pmetzger** [comment]
@thiagoveloso Could you make the needed changes, squash, and push?

**Comment by reneeotten** [comment]
oh, sorry… I totally missed these comments and certainly merged this prematurely. Apologies for that; I suppose we can just revert the name change and it should be fine. 
I will not have time or sit behind a Mac until tonight after work..

**Comment by tobypeterson** [comment]
Alternatively, don't rename the port, just set `distname` appropriately. (probably `pnetcdf-${version}`)

**Pull request merged**
