### PR TITLE
Wireguard updates & fix livecheck

### PR DESCRIPTION
**Pull request by lbschenkel**
Although these ports are `openmantainer`, since I have fixed the livechecks I'm submitting all changes via this PR so the maintainer (@cardi) has the opportunity to take a look.

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. @cardi ?

**Comment by cardi** [comment]
Thanks, @lbschenkel and @pmetzger.

I don't think it's necessary to bump the version for `wireguard-tools`: please see my inlined comment.

The [livecheck](https://guide.macports.org/chunked/reference.livecheck.html) looks reasonable, but I'm not familiar with its usage: will this automatically check the latest tags and send a notification to the maintainers or users?

**Comment by pmetzger** [comment]
It seems easier to unnecessarily merge the update than to explain to people that we're keeping it back because it's unnecessary. :)

**Comment by cardi** [comment]
An explanation was written in the `Portfile`:

https://github.com/macports/macports-ports/blob/bc6ed747d7042c60e54830b4f56762724d1de5e8/net/wireguard-tools/Portfile#L6-L11

But I'm OK with merging this.

(I suppose it's a bit difficult to convey that the lack of version bumps != the port is not being maintained.)

**Comment by pmetzger** [comment]
Merged. Thanks @lbschenkel and @cardi!

**Comment by lbschenkel** [comment]
@cardi:

AFAIK livecheck is not used in any automated fashion, but users and/or maintainers can use `port livecheck` to check if there are upstream updates. For example, I use `port livecheck installed` to check for updates to the ports I use and `port livecheck maintainer:lbschenkel` for the ports I maintain. I noticed that the livecheck for the `wireguard-*` ports were not working (server returned 403, listing is now disallowed) so I decided to fix those by pointing to the repo tags.

Regarding the `-tools` update, you're right. I checked the git log: https://git.zx2c4.com/WireGuard/log/src/tools which indicated that there were updates to `wg-quick` but I didn't realize that by a closer inspection of dates and changes that none of the commits in the interval touched the Darwin code.

**Pull request merged**
