### PR TITLE
mk-configure: new port in devel; developer_cmds: fix the port

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

New port.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@herbygillot Could you please take a look?

**Comment by herbygillot** [comment]
If checksums have changed, but the version has not, this qualifies as a stealth update and needs to be treated as such.

`revision` should be bumped, and `dist_subdir` set with a new (incremented) subdir alongside the updated checksum: https://trac.macports.org/wiki/PortfileRecipes#stealth-updates

**Comment by barracuda156** [comment]
@herbygillot Thank you! Will fix this soon (on mobile at the moment still).

**Comment by barracuda156** [comment]
@herbygillot Done, CI passed.

**Comment by herbygillot** [comment]
Thanks @barracuda156

**Pull request merged**
