### PR TITLE
qt5-qtwebengine: update to 5.15.15

### PR DESCRIPTION
**Pull request by chrstphrchvz**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [x] security fix

###### Tested on

macOS 12.6.8 Intel
Xcode 14.2 (with `configure.sdk_version=13.1`)

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
Tested with simplebrowser.py from py310-pyside2
image
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
Ideally the CI builds of qt5-qtwebengine would have timed out. However the macOS 12 CI failed to configure qt5-qtwebengine because of the familiar error: `Project ERROR: Could not resolve SDK Path for 'macosx12.3' using --show-sdk-path`. This caused any qt5-qtwebengine dependents to also fail. It also failed to build qt5-qtwebkit for a reason I have not previously seen:
```
2023-09-01T12:13:54.9432050Z bison -d -p xpathyy xml/XPathGrammar.y -o generated/XPathGrammar.tab.c && mv -f generated/XPathGrammar.tab.c generated/XPathGrammar.cpp && mv -f generated/XPathGrammar.tab.h generated/XPathGrammar.h
2023-09-01T12:13:54.9579940Z xml/XPathGrammar.y:54.1-12: warning: deprecated directive: ‘%pure_parser’, use ‘%define api.pure’ [-Wdeprecated]
2023-09-01T12:13:54.9580830Z    54 | %pure_parser
2023-09-01T12:13:54.9581340Z       | ^~~~~~~~~~~~
2023-09-01T12:13:54.9581790Z       | %define api.pure
…
2023-09-01T12:13:55.0904070Z xml/XPathGrammar.y: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
…
2023-09-01T12:13:55.1008000Z Could not open /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_aqua_qt5/qt5-qtwebkit/work/qtwebkit-opensource-src-5.9.2/Source/WebCore/generated/XPathGrammar.tab.c.
2023-09-01T12:13:55.1013920Z make[2]: *** [fwheader_generator] Error 2
```

**Comment by nilason** [comment]
> Ideally the CI builds of qt5-qtwebengine would have timed out. However the macOS 12 CI failed to configure qt5-qtwebengine because of the familiar error: `Project ERROR: Could not resolve SDK Path for 'macosx12.3' using --show-sdk-path`. This caused any qt5-qtwebengine dependents to also fail. 

Possibly related: https://trac.macports.org/ticket/68073

**Comment by pmetzger** [comment]
@chrstphrchvz Should this be merged?

**Comment by chrstphrchvz** [comment]
> @chrstphrchvz Should this be merged?

I believe it should be.

**Comment by pmetzger** [comment]
Merged. Thanks, @chrstphrchvz !

**Pull request merged**
