### PR TITLE
folly and friends: update to 2023.01.02.00; proxygen: new port in folly group

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update to the current upstream version, 2023.01.02.00.
Patches are moved to Git – easier to maintain. Content of patches is retained: I only had to add a fix for missing `IP_RECVTOS`.
Claim maintainership for now; if anyone is interested to co-maintain the port, please.
I also made some non-functional changes to the portfile: spaces to multiples of 4, alphabetic sorting and removal of redundant flag, which is added by CMake anyway.

**Current status:** everything builds fine (failures were due to broken checksums), but `watchman` needs to be updated, therefore draft atm.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@danchr Could you please check if `watchman` builds with these versions? If yes, should be safe to merge.

**Comment by barracuda156** [comment]
Let me update to the current versions.

**Comment by barracuda156** [comment]
@harens May I ask you to help with this? We obviously cannot update these ports every two weeks like Facebook does, but last update (by myself) was 6 months ago. Time for an update.

**Comment by danchr** [comment]
Did you try installing `watchman`? From past experience, updating one port requires updating them all. A simple install should suffice, as errors usually occur during the build.

**Comment by barracuda156** [comment]
> Did you try installing `watchman`? From past experience, updating one port requires updating them all. A simple install should suffice, as errors usually occur during the build.

@danchr May I just add it here to see if it builds? I cannot test it, since it requires Node, Yarn and Rust. Though possibly we can avoid at least the latter: https://github.com/facebook/watchman/issues/1088#issuecomment-1401319402

Do you know if Node is unavoidable? CMakeLists ask for it, though do not declare it required.

**Comment by barracuda156** [comment]
Actually let me try adding it with matching version, we gonna see straightaway if it builds.

**Comment by barracuda156** [comment]
For some reason checksums are suddenly broken 🤷🏻‍♂️
Okay, let me replace with new values.

**Comment by barracuda156** [comment]
@danchr I would appreciate if you help a bit with `watchman`. I have adapted your earlier patch (but please check), but now it complains about reinplace. I have no environment to test it, and I do not understand this port – but we need to build it in order to update the whole `folly` group, finally.

**Comment by danchr** [comment]
So, I tried building `watchman` with this, and it failed. Of course 🙄 They added a new dependency, `edencommon`, and there's some other stuff too. I'll see if I can make `watchman` easier to build for you…

**Comment by danchr** [comment]
Okay, I pushed an update to your branch that removes the dependency on Node, and gets Watchman to build 🙂

**Comment by barracuda156** [comment]
@danchr Thank you very much!

**Comment by barracuda156** [comment]
GitHub again broken checksums for two of the ports. Amazing. Will fix now, and hopefully everything then ready.

**Comment by barracuda156** [comment]
@danchr @harens Ready to merge!

@danchr Thanks again for helping with `watchman`.

**Comment by harens** [comment]
@barracuda156 for me it's a lot of changes in one PR for ports I'm not familiar with, so I personally can't review it thoroughly. Thank you very much for your work on this though.

**Comment by barracuda156** [comment]
> @barracuda156 for me it's a lot of changes in one PR for ports I'm not familiar with, so I personally can't review it thoroughly. Thank you very much for your work on this though.

Pretty much everything is an earlier work already merged previously. Only patches to Folly itself were consolidated and slightly refactored based on comments from upstream. Aside of that, I dropped few redundant args in portfiles, which are added by the build system anyway.

For `watchman`, I totally trust @danchr 

@herbygillot Maybe you could help with merging this? Other than `watchman`, these are no one’s ports.

**Comment by barracuda156** [comment]
@herbygillot Bump :)

**Pull request merged**
