### PR TITLE
py-*: add missing subports for python 3.5 and 3.6

### PR DESCRIPTION
**Pull request by mojca**
Untested addition of python 3.5 and 3.6 subports.

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM, but perhaps we should remove 2.6 at the same time? It's pretty crusty at this point. Then we'll only have one giant blind commit. If you don't feel comfortable with doing that at the same time I understand.

**Comment by mf2k** [comment]
Do we know if upstream supports 3.6 on all of these? I know a few python modules are for specific versions of python that python 3 base now includes, and so a py36 sub-port is not needed while a py34 is. Off the top of my head, I cannot remember the specific one I'm thinking of however.

**Comment by mojca** [comment]
We could identify which ports fail to build on the buildbot and look at those individually. I would then (later, in a separate commit, once we also have a better understanding of which ports work with 3.4 and fail with 3.6) put some effort into phasing out 2.6 and 3.4, either together or separately. For perl we make subports obsolete in a single step. We might also need to check if any other ports outside of `python` folder depend on 3.4 or 2.6 before removing anything.

**Comment by mojca** [comment]
I was actually hoping that the PR would notify maintainers, but the number of changed ports probably exceeds the limit to notify anyone. I suggest to merge this once the buildbot is entirely free to simplify getting the feedback.

**Pull request merged**
