### PR TITLE
oof2: update to version 3.2.1, oofcanvas: update to version 1.1.1

### PR DESCRIPTION
**Pull request by snarkhunter**
Update to the latest versions. oof2 and oofcanvas must be updated together.

#### Description

OOF2 and OOFCanvas now use python3, and build with cmake.  The full changelog is at 
https://www.ctcms.nist.gov/oof/oof2/changes.html

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 13.5.2 22G91 x86_64
Xcode 15.0 15A240d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [?] tried a full install with `sudo port -vst install`?   "Sandbox-exec quit unexpectedly" when I use -v.
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by herbygillot** [comment]
Looks good, though we'd want a separate commit for each update to `oof2` and `oofcanvas`.  It's understandable that they need to be updated together, and that will still happen with 2 commits within the same PR. It looks like it should be the commit for `oofcanvas` first followed by the update for `oof2`.

**Comment by snarkhunter** [comment]
Arrgh.  I thought one commit was ok if they were related.  Can I modify this PR or should I just start over?  I'm not terribly experienced with git.   Can I make two commits on the same branch, or do I need to use separate branches?

**Comment by herbygillot** [comment]
On your local branch for this PR, simply do `git reset HEAD^1`.

This will reset the branch minus 1 commit, basically "uncommit"-ing your changes by removing the commit, but keeping the local changes to your 2 Portfiles still present.

Then you can add each Portfile and make an individual commit per Portfile.

After that, force push the branch to this PR, and that should do it.

**Comment by snarkhunter** [comment]
Thanks.  It looks like it worked.
 -- Steve

**Comment by herbygillot** [comment]
Looks good and merged. Thanks @snarkhunter.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@snarkhunter @herbygillot portfile [fails to build on macOS <10.12](https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/236335/steps/install-port/logs/stdio), maybe it makes sense to block `clang < 900`.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@snarkhunter #20536 is done right and it worked.

**Pull request merged**
