### PR TITLE
Gildas: update to 201910b

### PR DESCRIPTION
**Pull request by bardeau**
Can someone please accept this PR for Gildas oct19b release? Thanks.

### CODE REVIEW

**Comment by pmetzger** [comment]
I note the CI failed. Is that expected?

**Comment by mf2k** [comment]
Error is:

`DEBUG: Backtrace: cfitsio not installed with a Fortran variant`

**Comment by bardeau** [comment]
The Travis build failed because of the timeout, as usual.

Regarding the Azure errors, I just can't find where are the relevant build logs.

**Comment by bardeau** [comment]
> Error is:
> 
> `DEBUG: Backtrace: cfitsio not installed with a Fortran variant`

Yes, this is a prerequisite we clearly state to our users.

**Comment by pmetzger** [comment]
Merged.

**Pull request merged**
