### PR TITLE
rawtherapee: add missing lib deps

### PR DESCRIPTION
**Pull request by mascguy**
### Description

So happy to see this port working again!

Based on the output from the configure phase, a number of ports need to be added as lib deps. This PR takes care of that.

### CODE REVIEW

**Comment by mascguy** [comment]
Since this port requires Quartz, CI will not succeed. As such, I cancelled the workflow, to avoid wasting compute cycles.

**Comment by jasonliu--** [comment]
Is there a reason why most of the dependencies that you've added are path-style dependencies, rather than simply being dependent on the port?

**Comment by mascguy** [comment]
> Is there a reason why most of the dependencies that you've added are path-style dependencies, rather than simply being dependent on the port?

Yep, many of these ports have `-devel` variations, so it's important to use the path style.

**Comment by jasonliu--** [comment]
Ah okay, thanks for the explanation!

**Comment by mascguy** [comment]
> Ah okay, thanks for the explanation!

Any concerns with merging?

**Comment by jasonliu--** [comment]
Nope, LGTM! 😃

**Pull request merged**
