### PR TITLE
cmake-devel: fixes

### PR DESCRIPTION
**Pull request by kencu**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

several systems, but not Tiger

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by kencu** [comment]
This version works properly on 10.5 PPC and 10.7 without kernel panics.

Run through the CI system for unexpected issues, then will commit.

**Comment by kencu** [comment]
changing the branch to 3.29.0 in the version name just corrects my previous error of saying it was 3.29.1

I thought that was how the cmake-devel port was naming branches, as 3.29.0 has been released, but it's the branch name in gitlab that is being specified there, not the technical release version.

**Comment by barracuda156** [comment]
@kencu Thank you, now 3.29.0 works on 10.6 ppc. (And I believe, this means it works on 10.5 as well.)

**Comment by mascguy** [comment]
Ken, thanks for assisting with these, much appreciated!

**Comment by kencu** [comment]
happy to pitch in. We can see you’re quite busy lately.

**Pull request merged**
