### PR TITLE
InsightToolkit*: Remove unnecessary expr

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

Removes seemingly unnecessary use of `expr`.

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. The use of `expr` here was pretty odd.

**Comment by pmetzger** [comment]
@ryandesign no license seems to be set in this, which is causing a lint failure (and possibly a CI failure). I hesitate to ask, but if you could fix that?

**Comment by pmetzger** [comment]
Merged.

**Comment by ryandesign** [comment]
I'll add the `license` separately.

The build failures are because `Error: python25 is not supported on Yosemite or later.` There are numerous open tickets for these ports, including for this python issue, update requests, build failures. I'm not working on those issues.

**Comment by pmetzger** [comment]
@ryandesign Would it be reasonable for someone to propose removing all support for python < 2.7 from MacPorts?

**Comment by ryandesign** [comment]
Feel free to ask on the mailing list.

**Comment by pmetzger** [comment]
Done.

**Pull request merged**
