### PR TITLE
python/: update checksums.

### PR DESCRIPTION
**Pull request by Steap**

### CODE REVIEW

**Comment by Steap** [comment]
This is completely untested, to be honest.

**Comment by jmroot** [comment]
Why?

**Comment by dliessi** [comment]
I am in favour of adding missing checksum methods, but they should be tested since wrong checksums prevent users from installing.
Maybe you just need to inspect the output of the CI builds.

Instead, I can't see the point in removing existing checksum methods: can you please explain why this is necessary?
If it is not, which is my strong conviction, I would vote for keeping them.

**Comment by cjones051073** [comment]
> I am in favour of adding missing checksum methods, but they should be tested since wrong checksums prevent users from installing.
> Maybe you just need to inspect the output of the CI builds.
> 
> Instead, I can't see the point in removing existing checksum methods: can you please explain why this is necessary?
> If it is not, which is my strong conviction, I would vote for keeping them.

I disagree. For a while now we have dis-favoured `md5` checksums, so if we are going to make a bulk update like this, to for instance add `size` where missing, then removing the older ones at the same time is the right thing to do. Right now, `rmd160`, `sha256` and `size` are the three recommended to be used.

**Comment by jmroot** [comment]
MD5 is one of the checksums published by pypi; don't remove please.

**Comment by reneeotten** [comment]
> MD5 is one of the checksums published by pypi; don't remove please.

True, but also SHA256 is present. We are anyway including that as one-of-the-three checksums, that should be sufficient - right? 

I assume that this PR was generated by the "update" feature for ```upt``` that @Steap is working on. To me it appears the part of updating/completing the checksums in that procedure works very well; and I'm sure we could leave in the MD5 checksum for PyPI ports for now, provided that there is community consensus that this should be done.

**Comment by Steap** [comment]
I'm sorry for the late reply.

As @reneeotten guessed, this is related to the "update" feature of upt-macports. I'm trying to get rid of "deprecated" checksums such as MD5 in order to not have to handle them in upt itself.

Do we agree on the idea, and should I send an updated version of this patch?

**Comment by kencu** [comment]
please reopen this with updates someday if relevant

**Pull request closed without merging**
