### PR TITLE
Also allow Travis to download private archives

### PR DESCRIPTION
**Pull request by ryandesign**
#### Description

Also allow Travis to download private archives

See: https://trac.macports.org/ticket/54800

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

### CODE REVIEW

**Comment by ryandesign** [comment]
Don't merge this yet... let me check one thing...

**Comment by ryandesign** [comment]
Ok, added `preferred_hosts` so that it shouldn't try to get public archives from the private server. This should be ready to merge, if @l2dy agrees.

**Comment by ryandesign** [comment]
Wait, I need to sign all those private archives first.

**Comment by ryandesign** [comment]
Ok, the private archives are signed.

**Comment by ryandesign** [comment]
I've merged this, then I submitted two new PRs, and I do not see these changes reflected in those builds. Does something else need to be done to get Travis to use these changes? Or does it just take some time for Travis to update to them?

**Comment by l2dy** [comment]
> I've merged this, then I submitted two new PRs, and I do not see these changes reflected in those builds. Does something else need to be done to get Travis to use these changes? Or does it just take some time for Travis to update to them?

The Travis configuration is read from your PR, so you need to rebase your changes onto the current master.

**Comment by ryandesign** [comment]
It turns out `archive_site_local` is [completely broken](https://trac.macports.org/ticket/57717). I thought I had tested this on my system and it worked, however I forgot that I had also set up archive_sites.conf, and that's what was working.

Let me think about what I want to do. One options is to switch to using archive_sites.conf, which would work for Travis but would be confusing for our buildbot setup, and I'd like to keep them similar where possible.

Alternately, I could have Travis patch MacPorts to fix the bug. This is probably what I want to do since it's a three-character fix. There is still [another bug](https://trac.macports.org/ticket/57718) in MacPorts' handling of `archive_site_local` but the bug will not affect Travis because it only happens when multiple URLs are specified.

**Pull request merged**
