### PR TITLE
Lisp: new ports

### PR DESCRIPTION
**Pull request by catap**
#### Description

Here the first portion of new lisp ports.

###### Type(s)

- [x] enhancement

###### Tested on

macOS 12.6.8 21G725 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
@mascguy, @herbygillot may I ask you to review this PR? It is the first one (with limit of less than 30 commits) in the series with goal to bring https://nyxt.atlas.engineer into MacPorts.

**Comment by mascguy** [comment]
> @mascguy, @herbygillot may I ask you to review this PR? It is the first one (with limit of less than 30 commits) in the series with goal to bring [nyxt.atlas.engineer](https://nyxt.atlas.engineer) into MacPorts.

Looking forward to seeing the end result Kirill!

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
Observers: Note that the only change to others' ports - and specifically `slime` - is limited to the addition of a comment. So no concerns with merging prior to the 72-hour maintainer timeout.

**Comment by catap** [comment]
@mascguy thanks!

**Comment by mascguy** [comment]
> @mascguy thanks!

Great work Kirill, thanks as always!

**Pull request merged**
