### PR TITLE
Remove port for COT; latest versions are available through pip.

### PR DESCRIPTION
**Pull request by glennmatthews**
COT port is quite outdated (v1.4.1 versus latest of 2.1.0); as it's a Python package, it's better managed via `pip` than `port` in any case. Removing it.

### CODE REVIEW

**Comment by pmetzger** [comment]
Is there anything that depends on this port?

**Comment by glennmatthews** [comment]
Not that I know of offhand - it depends on the `vmdktool` and `fatdisk` ports but not vice versa.

**Comment by pmetzger** [comment]
I've asked @raimue for a second opinion here, but I presume that we can in fact just remove this since there's no replacement, and the guide says:

> If there is no replacement for a port, it can simply be deleted immediately.

**Comment by raimue** [comment]
Please follow [CommitMessages](https://trac.macports.org/wiki/CommitMessages) for the commit message format.

Otherwise, this looks good to me.

**Comment by pmetzger** [comment]
Okay, if the commit message gets updated, I'll merge.

**Comment by raimue** [comment]
The commit message needs to include everything that is required to understand the reasons. This is what will be archived in the Git repository. What you wrote in the pull request message should have been the commit message.

**Comment by pmetzger** [comment]
Merged. Thank you, @glennmatthews.

**Comment by kencu** [comment]
how would this be managed as a dependency now?

**Comment by raimue** [comment]
@kencu As far as I checked, there are no dependents in the ports tree.

**Comment by kencu** [comment]
Thanks, @raimue -- I think it was more the premise of this PR I was wondering about, which appears to be that out of date python package ports should be deleted and people advised to use pip instead -- and if that approach were generally taken, then the system of deps would break down. 

But certainly if nobody is using the port and it's far out of date and nobody wants to update it, it might as well be deleted.

**Comment by pmetzger** [comment]
> When nobody uses and nobody is willing to maintain a port, that's a different story.

That seems to be the case here, fwiw.

**Comment by glennmatthews** [comment]
To be honest, I haven't seen the value add of maintaining an up-to-date port of this python package. Perhaps it's just that the user base I have is already familiar with Python package management and hence is perfectly comfortable using pip and virtualenv; I don't know, but people are consistently using the latest PyPI version and not the out-of-date MacPorts version of COT.

That's not to say I don't see the advantage of MacPorts - being able to use it to install the non-Python binary tools like vmdktool, fatdisk, qemu that COT depends on has absolutely been a time-saver and made it easier to maintain COT. Just my 2¢. :-)

**Comment by kencu** [comment]
The issue comes to installing ports. If the ports are up to date, you can just say
```
sudo port -v install my_special_thingy
```
and MacPorts will do it all, including all deps.

If you rely on `pip` and other things, you need a pageful of instructions as to what gets installed via MacPorts, then  what to do in `pip`, and then what to do in MacPorts again, etc, etc, etc.

And then when something breaks -- and something always breaks -- it's very difficult to sort out what went wrong.

It would be nice if MacPorts could drive `pip`. I'm sure this was considered, and the idea abandoned.

**Comment by pmetzger** [comment]
There are two issues here.

1. It's reasonable to get rid of ports no one is using or maintaining. They add maintenance load even without being worth anything to anyone.
2. For ports whose native management method is some external tool like `pip`, `gem`, `opam`, etc., it would be nice to have a way of using those tools from within MacPorts. Right now, for example, I'm designing changes to `opam` that the `opam` maintainers have largely agreed to that will allow `opam` to be used as though it was a funny sort of `make` command, so that a very minimal `opam2portfile` script would be all that was needed to maintain an `opam` port.

**Pull request merged**
