### PR TITLE
the_Foundation: define environ correctly

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

The port is broken quite on a number of systems: https://ports.macports.org/port/the_Foundation/details/
While logs are dead, likely it is caused by missing `environ` define. Fix that.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by sikmir** [comment]
FYI @skyjake

**Comment by barracuda156** [comment]
@sikmir @skyjake Failure looks unrelated to the fix:
```
[ 84%] Building C object CMakeFiles/string_Foundation.dir/tests/t_string.c.o
  /usr/bin/clang  -I/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_the_Foundation/the_Foundation/work/the_foundation/include -I/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_the_Foundation/the_Foundation/work/build -pipe -Os -DNDEBUG -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -mmacosx-version-min=13.0 -Wall -Wpedantic -Werror -Wno-deprecated-declarations -Wno-format-pedantic -Wno-format -msse4.1 -std=gnu11 -MD -MT CMakeFiles/string_Foundation.dir/tests/t_string.c.o -MF CMakeFiles/string_Foundation.dir/tests/t_string.c.o.d -o CMakeFiles/string_Foundation.dir/tests/t_string.c.o -c /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_the_Foundation/the_Foundation/work/the_foundation/tests/t_string.c
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_the_Foundation/the_Foundation/work/the_foundation/tests/t_test.c:407:13: error: variable 'remCount' set but not used [-Werror,-Wunused-but-set-variable]
          int remCount = 0;
              ^
  1 error generated.
  make[2]: *** [CMakeFiles/test_Foundation.dir/tests/t_test.c.o] Error 1
  make[2]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_the_Foundation/the_Foundation/work/build'
  make[1]: *** [CMakeFiles/test_Foundation.dir/all] Error 2
```

**Review by ryandesign — APPROVED** [review]
I ran a new buildbot builds. It failed on 10.8–10.10 (using Xcode clang) due to:

```
error: unknown warning option '-Wno-format-pedantic' [-Werror,-Wunknown-warning-option]
```

It failed on 10.6–10.7 (using newer MacPorts clang) due to:

```
Undefined symbols for architecture x86_64:
  "_environ", referenced from:
      _start_Process in process.c.o
ld: symbol(s) not found for architecture x86_64
```

So your fixes are exactly right; thanks.

Can you also [submit an issue or pull request to the developers](https://codeberg.org/skyjake/the_Foundation) about the `environ` problem?

**Comment by barracuda156** [comment]
Sure, will do once back to the desktop.

**Comment by barracuda156** [comment]
@ryandesign Could we merge it now, perhaps?

**Pull request merged**
