### PR TITLE
Bump a revision at two of my ports

### PR DESCRIPTION
**Pull request by catap**
#### Description

Here a simple revision bump for two ports which I'm care on.

The cause is broken cmake which was fixed.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
why - did these ports not build before, what has cmake to do with this? If they did build earlier is there a reason to rebuild them for people who installed them already?

**Comment by catap** [comment]
[cmake's update](https://github.com/macports/macports-ports/commit/0b8b396b43192cd7803e7a8b34a53953adfcc0a9) broke cmake on old platform. It was [fixed in few days](https://github.com/macports/macports-ports/commit/d9e3218c0d5cee4b33860b5fbdc6164138997d3f). This ports were updated / introduced when cmake were broken => buildbot can't build it because missed dependencies.

`scalapack` is heavy used across math-ports, and if it doesn't available for some version, it means that a lot of ports will be skipt by buildbot.

**Comment by reneeotten** [comment]
then these builds should be rescheduled on the buildbot instead of increasing the "revision"

**Comment by catap** [comment]
@reneeotten I have no way to do it.

**Comment by reneeotten** [comment]
neither do I - ask on the mailinglist or open a Trac ticket.

**Pull request closed without merging**
