### PR TITLE
New muniversal PG & fix isl universal build

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.5.8 9L31a i386
Xcode 3.1.4 9M2809

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
Could you give a short explanation of why a new version of the muniversal portgroup needs to be created?

**Comment by MarcusCalhoun-Lopez** [comment]
> Could you give a short explanation of why a new version of the muniversal portgroup needs to be created?

I doubt I am capable of giving a _short_ explanation of anything, but I will give it a try.
The hope for the new muniversal PG is twofold:
* do things in a more MacPorts way and
* greatly reduce the footprint of a universal build.

The current [Portfile for GMP](https://github.com/macports/macports-ports/blob/06db9c619aa5188b254b2bfc600d108e12dc5a9f/devel/gmp/Portfile#L148) has something along the lines of:
```
if {!${universal_possible} || ![variant_isset universal]} {
    if {${build_arch} eq "i386" || ${build_arch} eq "ppc"} {
        configure.env-append   ABI=32
    } elseif {${build_arch} eq "ppc64"} {
        configure.env-append   ABI=mode64
    } else {
        configure.env-append   ABI=64
    }
} else {
    array set merger_configure_env {
        ppc     ABI=32
        i386    ABI=32
        ppc64   ABI=mode64
        x86_64  ABI=64
        arm64   ABI=64
    }
}
```
The new muniversal PG can achieve the same result for **both** universal and non-universal builds with:
```
configure.env.arm64-append  ABI=64
configure.env.x86_64-append ABI=64
configure.env.i386-append   ABI=32
configure.env.ppc-append    ABI=32
configure.env.ppc64-append  ABI=mode64
```
This seems both simpler and more consistent with how MacPorts usually works.

As another example, the current [current Portfile of Octave](https://github.com/macports/macports-ports/blob/06db9c619aa5188b254b2bfc600d108e12dc5a9f/math/octave/Portfile#L675) uses `merger-post-destroot`:
```
if {!${universal_possible} || ![variant_isset universal]} {
    post-destroot {
	set octave_packages_file ${destroot}${prefix}/share/octave/octave_packages
        system -W ${worksrcpath} "./run-octave ..."
    }
} else {
    merger-post-destroot {
        foreach arch ${universal_archs_to_use} {
            set octave_packages_file ${destroot}-${arch}${prefix}/share/octave/octave_packages
            system -W ${worksrcpath}-${arch} "./run-octave ..."
        }
    }
}
```
The new muniversal PG automatically reruns procedures with appropriate changes to `${worksrcpath}`, `${destroot}`, etc.
The following should work for **both** universal and non-universal builds:
```
post-destroot {
    set octave_packages_file ${destroot}${prefix}/share/octave/octave_packages
    ssystem -W ${worksrcpath} "./run-octave ..."
}
```
There are a few more features, but the basic idea is to minimize the universal code in the MacPorts style.
The initial motivation for this new code base was to reintroduce the universal build into the rust package.
The last time rust was able to build universal, I think is fair to say the universal code [left a heavy footprint](https://github.com/macports/macports-ports/blob/e19d3fa794437ac624e2bb0d796b22ac486e5206/lang/rust/Portfile).

**Review by mascguy — APPROVED** [review]
Haven't tested locally with it - or scrutinized every line of code in the new pg - but looks great overall!

**Comment by kencu** [comment]
seems like the next step here is to get this in and try it out in more detail, so

**Pull request merged**
