### PR TITLE
clang-11-bootstrap: build by bootstrap before 10.12 only

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.12.6 16G2136 x86_64
Xcode 9.2 9C40b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
@Gcenx after a while thinking I'd like to agree that we don't need to use gcc10-bootstrap when it's possible.

**Comment by Gcenx** [comment]
@catap this should apply to _all_ the new bootstrapping changes. The idea of bootstrap ports to to break dependency cycles.

**Comment by catap** [comment]
@Gcenx yep, I'm working on creating "boostrap tolchain" PG which can be used to easy manage such dependencies.

**Comment by catap** [comment]
@mascguy may I ask you to review this one?

**Pull request merged**
