### PR TITLE
terragrunt: update to 0.55.18

### PR DESCRIPTION
**Pull request by GerardSoleCa**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.2.1 23C71 arm64
Xcode 15.3 15E204a

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
@GerardSoleCa thanks for the update but the CI fails - please take a look and fix.

**Comment by GerardSoleCa** [comment]
> @GerardSoleCa thanks for the update but the CI fails - please take a look and fix.

Hi, I do suspect that the failing ports are not supported/have never been built for mac14. Last terragrunt change was also mine (https://github.com/macports/macports-ports/pull/20825) and in that case the CICD image for mac14 was not even existing.

How should we address this issue?

**Comment by saj** [comment]
I don't know anything, but this PR has been sitting around a while so I felt bad.

Sonoma is probably not the problem.  Do we have more bad hash digests?

Here are some old commits on trunk.
(oldest first)

```
8c61282d6b0 terraform: fix checksums across versions
81006d867ce terraform: fix checksums for 1.2 and 1.3
```

herby sent the first; you sent the second.

Since 8c61282d6b0, there have been subport updates to `terraform` majors 1.3, 1.4, 1.5, 1.6, 1.7, and 1.8.  In addition, you updated the hash digests on 1.2 (and 1.3).  That leaves a whole bunch of old `terraform` subports that might still have wonky hash digests in MacPorts.

macos-12 executes on x86_64.
macos-13 probably also executes on x86_64.
macos-14 executes on arm64.

I think your tests succeeded on macos-12, and failed on macos-14, because MacPorts was able to satisfy the `terraform` subport dependency using a MacPorts **binary archive** on x86_64 but not on arm64.  The arm64 runner then fell back to a '**source**' (spoiler: not really source) build of the `terraform` subport, then it hit the latent wonky hash digest.

```
Installing dependencies for terragrunt-0.29
  Installing 3 dependencies of terragrunt-0.29:
  go 
  terraform_select 
  terraform-0.15 
  
  Installing dependency (1 of 3) 'go' with variants '' ... [OK]
  Installing dependency (2 of 3) 'terraform_select' with variants '' ... [OK]
  Installing dependency (3 of 3) 'terraform-0.15' with variants '' ... [MISSING]
  Building 1 dependencies of terragrunt-0.29:
  Building dependency (1 of 1) 'terraform-0.15' with variants '' ... [FAIL] (checksum)
```

Let's pick on `terraform-0.15` as one example.

MacPorts trunk has this:

```
subport terraform-0.15 {
    set patchNumber     5
    revision            1
    checksums           rmd160  6cf3903793848fd2ef0180ec37b3989f1117536a \
                        sha256  4ee2ed9b769426cc9f13bd26c133ee66c6046acffeef632ddf0ef66e3d36a981 \
                        size    33932321
}
```

upstream have this:

```
% curl -Ss https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_SHA256SUMS | grep darwin
5ad75ed3def05f36b5c5dab97dee00b5d3d86be9f9dcd205b48136312505f3fc  terraform_0.15.5_darwin_amd64.zip
```

```
% curl -Ss --head https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_SHA256SUMS | grep -i last-mod
last-modified: Mon, 20 Mar 2023 19:03:02 GMT

% curl -Ss --head https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_darwin_amd64.zip | grep -i last-mod
last-modified: Mon, 20 Mar 2023 19:03:03 GMT
```

```
commit 8c61282d6b03c0898e7c0cf1a3beb9477d5ea926
Author: Herby Gillot <herby.gillot@gmail.com>
Date:   Tue Feb 21 19:59:01 2023 -0500

    terraform: fix checksums across versions

...

 subport terraform-0.15 {
     set patchNumber     5
-    checksums           rmd160  d57fbd764112a5cc7d46b04c8d17d220eb5fddc8 \
-                        sha256  27d5ae2431240dff928e6483170b570782a8dd1a2b7c32ce1793097af1acb9bd \
-                        size    33803323
+    revision            1
+    checksums           rmd160  6cf3903793848fd2ef0180ec37b3989f1117536a \
+                        sha256  4ee2ed9b769426cc9f13bd26c133ee66c6046acffeef632ddf0ef66e3d36a981 \
+                        size    33932321
 }
```

Oddly, the upstream digest we observe today matches neither digest from that patch.

Upstream admit to having done this once, for 0.11.13, but then promised never to do it again.
https://github.com/hashicorp/terraform/issues/20701

Where did the digests in MP actually come from?  (Did upstream really stealth update all these releases?)
Does the problem go away if you update the digests on the old `terraform` subports?
Maybe 81006d867ce did not go back far enough.

cc @herbygillot

**Comment by GerardSoleCa** [comment]
Thanks Saj for the updates. When I updated the checksum on the stealth updated packages, those where the ones were failing.

I'll try to get some time this week with your insights and try to get this fixed.

I'll ping back in case of more help is required.

Cheers!

**Comment by reneeotten** [comment]
@GerardSoleCa please feel free to reopen this PR once you have found the time to work on it.

**Pull request closed without merging**
