### PR TITLE
Bugfix: (various) Fix fish completion scripts destination

### PR DESCRIPTION
**Pull request by halostatue**
#### Description

All twelve of the ports in this PR have the same issue:

`$destroot/$prefix/share/fish/completions` is for the completion files included with fish, not for use by package managers installing additional files. The correct location is `$destroot/$prefix/share/fish/vendor_completions.d`.

###### Type(s)

- [x] bugfix

###### Tested on

macOS 13.6 22G120 arm64
Xcode 15.0 15A240d

###### Verification

Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?

  - Ports `scientiaCLI`, `doggo`, ripgrep`, `folderify`, and `fem` report the same number of warnings before and after.

- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

No to all of the above, but I ran the following tests because these are all *installation* changes, not source or build changes:

1. Installed all of the ports: `sudo port install --unrequested {buku,kubectx,scientiaCLI,doggo,seaport,glab,flyctl,dagger,ripgrep,folderify,fnm,eza}`
2. Listed the completions:

   ```console
   $ ls /opt/local/share/fish/{completions,vendor_completions.d}/{buku,dagger,doggo,eza,flyctl,fnm,folderify,glab,kubectx,kubens,rg,ripgrep,scientia-cli,seaport}*
   /opt/local/share/fish/completions/buku.fish
   /opt/local/share/fish/completions/dagger.fish
   /opt/local/share/fish/completions/doggo.fish*
   /opt/local/share/fish/completions/eza.fish
   /opt/local/share/fish/completions/flyctl.fish
   /opt/local/share/fish/completions/folderify.fish
   /opt/local/share/fish/completions/glab.fish
   /opt/local/share/fish/completions/kubectx
   /opt/local/share/fish/completions/kubens
   /opt/local/share/fish/completions/rg.fish
   /opt/local/share/fish/completions/scientia-cli.fish
   /opt/local/share/fish/completions/seaport.fish
   ```
3. Uninstalled the ports: `sudo port uninstall {buku,kubectx,scientiaCLI,doggo,seaport,glab,flyctl,dagger,ripgrep,folderify,fnm,eza}`
4. Reinstalled from tree (fish format):

   ```fish
   for p in {buku,kubectx,scientiaCLI,doggo,seaport,glab,flyctl,dagger,ripgrep,folderify,fnm,eza}
     pushd */$p
     sudo port install --unrequested
     popd end
   end
   ```
5. Listed the completions again:

   ```console
   $ ls /opt/local/share/fish/{completions,vendor_completions.d}/{buku,dagger,doggo,eza,flyctl,fnm,folderify,glab,kubectx,kubens,rg,ripgrep,scientia-cli,seaport}*
   /opt/local/share/fish/vendor_completions.d/buku.fish
   /opt/local/share/fish/vendor_completions.d/dagger.fish
   /opt/local/share/fish/vendor_completions.d/doggo.fish
   /opt/local/share/fish/vendor_completions.d/eza.fish
   /opt/local/share/fish/vendor_completions.d/flyctl.fish
   /opt/local/share/fish/vendor_completions.d/folderify.fish
   /opt/local/share/fish/vendor_completions.d/glab.fish
   /opt/local/share/fish/vendor_completions.d/kubectx.fish
   /opt/local/share/fish/vendor_completions.d/kubens.fish
   /opt/local/share/fish/vendor_completions.d/rg.fish
   /opt/local/share/fish/vendor_completions.d/scientia-cli.fish
   /opt/local/share/fish/vendor_completions.d/seaport.fish
   ```

### CODE REVIEW

**Comment by judaew** [comment]
LGTM for the `dagger`.

The commit header is better to write as: `dagger: fix fish completion locations`.

I think this commits can be squashed to one commit before merging.

**Review by judaew — APPROVED** [review]

**Comment by halostatue** [comment]
I’ll reword the commits now following your suggested pattern.

**Review by cardi — APPROVED** [review]

**Review by breun — APPROVED** [review]

**Review by raimue — APPROVED** [review]
Changes to ripgrep look good to me. :+1:

**Review by harens — APPROVED** [review]
Thanks @halostatue 👍

**Comment by pmetzger** [comment]
I believe all the relevant maintainers have signed off.

**Pull request merged**
