### PR TITLE
VLC2: fix the port for some older systems

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

This is an old version of VLC, no longer supported by upstream and targeting older systems. Possibly, it should even be restricted further down to < 10.7.

Given that at the moment VLC2 is [broken across the board](https://ports.macports.org/port/VLC2/details), this PR is safe: while it is not supposed to fix VLC2 for every system, I did get it to work with X11. (If someone remembers my comments few months ago re wrong colors – turned out, it was not caused by endianness, but by a conflict between X11 headers and/or libs. Colors are normal now.)

Several types of video output work, but at least on my system X11 and SDL seem to work better. Anything OpenGL is very fragile (perhaps due to archaic OpenGL in 10.6?).
Unfortunately, I cannot use SDL2 with this, since the code was written for SDL1, and API changed quite a bit.
Default audio works fine. PortAudio support builds, but apparently requires some manual set-up to work correctly (I have seen a similar issue on Sonoma with another port).
_Do not expect this to work robustly_ :) 

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

vlc2

### CODE REVIEW

**Comment by barracuda156** [comment]
This PR depends on https://github.com/macports/macports-ports/pull/23143 and should be merged after `live555` one (because it includes a patch to support the current `live555`).

**Comment by RJVB** [comment]
>Notifying maintainers:
>@RJVB for port VLC2.

As I implied in a reaction on the trac ticket, I'd prefer to not be involved anymore, esp. if the VLC2 port becomes targeted at systems <<10.9

I got the port thrown into my lap by the then-maintainer when I presented a couple of patches to get it to build again, I'm continuing that tradition now ^^

**Comment by barracuda156** [comment]
> Notifying maintainers: @RJVB for port VLC2.
> As I implied in a reaction on the trac ticket, I'd prefer to not be involved anymore, esp. if the VLC2 port becomes targeted at systems <<10.9 I got the port thrown into my lap by the then-maintainer when I presented a couple of patches to get it to build again, I'm continuing that tradition now ^^

Got it, will remove you from maintainers here.

**Comment by barracuda156** [comment]
@herbygillot We can merge this now, I believe. It is certainly an improvement over what we have now and contains some general fixes (the exiting code cannot build at least due to wrong prefix in post-activate for example).
I will do some follow-up fixes, but let’s do this step-wise, it is already huge.

It will also make testing easier, I want to get some feedback from others.

**Comment by RJVB** [comment]
>(the exiting code cannot build at least due to wrong prefix in post-activate for example).

Are you telling me that nobody noticed that (supposedly) I missed changing

```
            system "${prefix}/lib/vlc/vlc-cache-gen -f ${prefix}/lib/vlc"
```

to

```
            system "${vlcprefix}/lib/vlc/vlc-cache-gen -f ${vlcprefix}/lib/vlc"
```

during (I presume) the last set of changes to the port??

It's been done from the start in my own version of the port so if it was I who introduced the error it is a bit a testament to the lack of demand for this port that such a trivial oversight has never been corrected.

**Comment by barracuda156** [comment]
@RJVB In fact it could be that my assumption is wrong, and I changed the way it installs first, and then it turned out that activation does not work. But in any case installing that binary with other VLC binaries is logical, I think (and install destination was changed earlier to make it co-existing with VLC3).

**Comment by RJVB** [comment]
On Friday March 22 2024 12:21:40 Sergey Fedorov wrote:
>(and install destination was changed earlier to make it co-existing with VLC3).

I seem to recall that I initiated that change, and even had to justify it. Doesn't really matter, it's clear that the path must correspond to where the binary is installed, and somebody would surely have realised that if the port were in demand.

**Comment by barracuda156** [comment]
@RJVB Let me actually make an effort and build this on x86 too.

@herbygillot I will update soon, then we can merge it, hopefully.

**Comment by barracuda156** [comment]
@RJVB Yeah, I think nobody tried to build it on older systems, since old Clangs cannot handle it due to missing `stdatomic.h`.

**Comment by barracuda156** [comment]
@RJVB There is some other stuff broken in quartz variant.

However, I think I have fixed everything. Will rebase soon.

vlc_app

**Comment by barracuda156** [comment]
Well, not really. The app builds, but video does not work yet (at least in VM):
```
[00007fd4be01ef38] macosx vout display error: Initialization of open gl view failed
[00007fd4bd8b34b8] core video output error: video output creation failed
[00007fd4bc8870b8] core decoder error: failed to create video output
```

**Comment by barracuda156** [comment]
@RJVB Could you actually try building this on 10.9? It could be that I do not get video output because I use a VM, and I have no suitable native setup.

To be clear, I am interested to know if +quartz works. Standard Macports is assumed (libc++, clang).

**Comment by RJVB** [comment]
>@RJVB Could you actually try building this on 10.9? 

When I find a moment I'll try rebuilding my own version and yours. It is indeed quite possible that you do not get OpenGL video output if your VM doesn't have any form of hardware acceleration but in that case I would expect VLC3 to be affected too.
The easiest test of that would be to find an official build that supports 10.9 and see if it works in your VM.

**Comment by barracuda156** [comment]
@RJVB I have downloaded official app from VLC (2.2.8), and there is no video with it as well, it behaves identically. I am sure now it must be a VM issue.

I will rerun the build again to make sure nothing is messed with the patches in my last commit, and this will be good to merge, I guess.

**Comment by RJVB** [comment]
>@RJVB I have downloaded official app from VLC (2.2.8), and there is no video with it as well, it behaves identically. I am sure now it must be a VM issue.

Ah, good to know, thank. It's not like I don't already have a long enough backlog ;)

**Comment by barracuda156** [comment]
@RJVB Do you know why is VLC so much dependent on hardware acceleration? FFMPeg does not require it, AFAIK.

**Comment by barracuda156** [comment]
@herbygillot If you help to merge it, would be great. We will likely need some follow-up, but let’s start from somewhere at least.

**Comment by barracuda156** [comment]
@RJVB Well, we did get a few systems fixed: https://ports.macports.org/port/VLC2/details

Yosemite fails because of its Xcode clang. Blacklist should be adjusted (Mavericks works because it uses clang-16).

**Comment by RJVB** [comment]
>(Mavericks works because it uses clang-16).

It would probably build just as well (and a lot faster) with clang-5.0 ... but I think the compiler auto-selection has been fine-tuned to use whatever the youngest, new-enough compiler is used that the user has installed, no?

**Comment by barracuda156** [comment]
@RJVB I am not the one to know how clang choice works, since I never use them on my own: my systems are either tweaked to use GCC, or use whatever defaults Macports supplies.

But I can’t remember seeing anything that old to be used. (For some reason `clang-3.7` gets picked on older Intel systems, and then, I think, `clang-11`.)

**Comment by RJVB** [comment]
>But I can’t remember seeing anything that old to be used. 

You have to have them installed, of course. Clang has long lost its advantage of compiling (much) faster than equivalent GCC versions, and apparently only the very latest versions generate somewhat faster code, sometimes. But for building old code on legacy systems the compilers from back in the day should usually be as sufficient as they used to be ;)

I still use clang-5 from regularly because it's fast and does the job without any obvious drawbacks compared to newer versions, though my go-to compiler now is clang-9. Clang 15 or 16 I only use when really necessary and I can easily imagine how they'd bring a lesser system than mine on its knees.

**Comment by barracuda156** [comment]
> You have to have them installed, of course.

I don’t like clangs. (They do have some advantages on Intel, due to Apple not bothering with gcc compatibility, but they do have disadvantages as well.)

The only reason I have systems with them is because I need to tests stuff locally, but for that purpose I need the standard environment, otherwise it won’t be indicative of what will build on CI and buildbots.
Given poor backward support of clangs, I can imagine that some older versions may in fact perform better, but I got neither motivation nor time to investigate it, to be honest.

**Comment by RJVB** [comment]
>I don’t like clangs. (They do have some advantages on Intel, due to Apple not bothering with gcc compatibility, but they do have disadvantages as well.)

As I've been (re)discovering the past time, Apple's ObjC dialect isn't grokked by GCC, things like @autoreleasepool . GCC also doesn't support blocks (as used by GCD) AFAICT. I have forgotten which OS X version introduced those niceties but they're unavoidable parts of "Apple and GCC not bothering with reciprocal compatibility"...

>Given poor backward support of clangs, I can imagine that some older versions may in fact perform better, but I got neither motivation nor time to investigate it, to be honest.

I was just putting it out there. As long as my observation is correct *and* can be generalised that the youngest installed new-enough compiler will be picked (to avoid installing another one) there is little more to discuss.

**Comment by barracuda156** [comment]
> Apple's ObjC dialect isn't grokked by GCC, things like autoreleasepool.

I am not sure what prevented Apple to go with the standard implementation, but we have what we have. `autoreleasepool` can be rewritten in a normal syntax acceptable to GCC. (But perhaps something else may not be.)

> GCC also doesn't support blocks (as used by GCD) AFAICT

This is correct, unfortunately, though it is said that plans are there: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78352

There was a GCC compiler claiming some level of blocks support, though I have no idea whether it was useful for anything IRL: https://code.google.com/archive/p/plblocks/

> can be generalised that the youngest installed new-enough compiler will be picked

I have an impression that this is not how it works now in Macports, but I can be totally wrong here. I just think I did not see clangs between 4 to 10 ever picked or built. (It would be surprising if of them are broken on Intel.)

**Comment by RJVB** [comment]
On Friday March 29 2024 14:30:12 Sergey Fedorov wrote:

>I am not sure what prevented Apple to go with the standard implementation

They *are* the (de facto) standard...

>This is correct, unfortunately, though it is said that plans are there: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78352

I was surprised to be reminded of this the other day, since I'm pretty certain I used to add `-fblocks` to my compiler flags at some point, and `gcc-mp-12 --verbose --help` even lists the option (but only on Mac).

>I have an impression that this is not how it works now in Macports

I used to use a combination of black white (or fallback) listing that had this effect *) , in a number of my ports, but have been seeing similar behaviour in ports I didn't touch the past times. If older OS versions already "push" clang-11 there should be no reason why I have been seeing clang-9.0 as the proposed build compiler. Beyond the fact I have it installed but not clang-11 . 

But with me it's also always possible that I hacked something somewhere, or kept a crucial file at an older version.

*) again, it'd pick the most recent acceptable compiler from the ones you had installed, or else trigger the installation of the newest from the list. I still think that's the preferred mechanism.

**Pull request merged**
