### PR TITLE
py-scrapy: update to 2.7.1

### PR DESCRIPTION
**Pull request by catap**
#### Description

I've also updated twisted and fixed missed dependency of scrapy.

###### Type(s)

- [x] bugfix
- [x] enhancement

###### Tested on

macOS 12.6 21G115 x86_64
Xcode 14.1 14B47b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by catap** [comment]
@reneeotten may I ask you to review this PR?

**Comment by kurthindenburg** [comment]
please wait until the py-openssl is merged

https://github.com/macports/macports-ports/pull/16687

**Comment by catap** [comment]
@kurthindenburg I'm wondering why we need to wait until `py-openssl` is merged. As far as I understand it doesn't creates any conflicts and any dependency hell which forces to bump a revision.

**Comment by catap** [comment]
@reneeotten I've asked it only out of my curiosity :) I don't try to push anyone to merge it as soon as possible.

**Comment by kurthindenburg** [comment]
py-scrapy update will not work w/o py-openssl and there was another person in IRC that had issues with their port that the openssl will fix.

**Comment by catap** [comment]
@kurthindenburg / @reneeotten seems that now we may move forward with this one!

**Comment by catap** [comment]
@kurthindenburg / @reneeotten I'd like to ping you on this PR.

**Pull request merged**
