### PR TITLE
thrift: update to 0.19.0, fix build on Sonoma/Ventura, do not opportunistically build lisp lib

### PR DESCRIPTION
**Pull request by barracuda156**
Fixes: https://trac.macports.org/ticket/68475
Closes: https://trac.macports.org/ticket/68025

#### Description

Update and fix for Sonoma/Ventura.
Do not build lisp portion opportunistically; make it a variant.
Switch to Boost 1.81 to match `apache-arrow`.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14
Xcode 15

macOS 10A190
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Let me also fix checksums for `apache-arrow` here, since it needs a revbump anyway.

**Comment by barracuda156** [comment]
@mascguy Could you please review this?

**Comment by mascguy** [comment]
> @mascguy Could you please review this?

Do any other ports require rev-bumps?

**Comment by barracuda156** [comment]
> > @mascguy Could you please review this?
> 
> Do any other ports require rev-bumps?

Looks like there is nothing else: all are either its own subports or Arrow’s: https://ports.macports.org/port/thrift/details

**Comment by mascguy** [comment]
> > > @mascguy Could you please review this?
> > 
> > Do any other ports require rev-bumps?
> 
> Looks like there is nothing else: all are either its own subports or Arrow’s: https://ports.macports.org/port/thrift/details

It looks like there's also a Perl port as well, `p5-thrift`. Should that also be rev-bumped?

**Comment by barracuda156** [comment]
@mascguy Done now. Sorry for a delay.

**Comment by barracuda156** [comment]
@mascguy Should be good to merge?

**Pull request merged**
