### PR TITLE
terragrunt: new port submission

### PR DESCRIPTION
**Pull request by szczad**
###### Type(s)

- [x] submission
- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G95
Xcode 11.2.1 11B500

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
@szczad thank you for your contribution and sorry for the delay. It appears that you're just downloading a binary file, that's not what is preferred in MacPorts. Instead, please update the Portfile so that it downloads the source and builds it from there.

**Comment by szczad** [comment]
@reneeotten I've tried that approach, however building this application with `golang` port group fails because project depends on libraries outside of `bitbucket` or `github` repositories.

**Comment by reneeotten** [comment]
I don't think you *need* to have libraries on ```bitbucket``` or ```github```, if that's the case the PG will just set-up some stuff automagically.

I think it's more likely to get this PR moving if you'd add a Portfile with that approach and we try to solve this issues that you run into instead of downloading a pre-compiled binary. Of course, do save this Portfile somewhere in case it actually does turn out we cannot fix the issues ;)

But, admittedly I have little to no experience with ```go``` based packages and/or the ```golang``` PG - perhaps @amake who authored the ```golang``` PG can provide any insights here?

**Comment by amake** [comment]
> I don't think you need to have libraries on bitbucket or github, if that's the case the PG will just set-up some stuff automagically.

@szczad is pointing out, correctly, that some of the dependencies are *not* on Bitbucket or GitHub, and that prevents usage of the golang portgroup's `go.vendors` as-is. Here is a portfile generated with `go2port`:

```tcl
# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4

PortSystem          1.0
PortGroup           golang 1.0

go.setup            github.com/gruntwork-io/terragrunt v0.21.6
categories
maintainers
license

description

long_description

checksums           ${distname}${extract.suffix} \
                        rmd160  42a1cd72a333bf8623adc04fde460ae835054779 \
                        sha256  4e1a65551427f7722944ef65c5469c3fade5c8d2aeb2d67716db70f1b1bd1337 \
                        size    193167

go.vendors          cloud.google.com/go \
                        lock    28a4bc8c44b3acbcc482cff0cdf7de29a4688b61 \
                        rmd160  0 \
                        sha256  0 \
                        size    0 \
                    github.com/agext/levenshtein \
                        lock    0ded9c86537917af2ff89bc9c78de6bd58477894 \
                        rmd160  43d4530cd4150510224aab964a8ff5959e2c3973 \
                        sha256  b92ec48f119fcde6b309139499b3395f1e2616edf62399d1d68fe22e63a2a095 \
                        size    13106 \
                    github.com/apparentlymart/go-cidr \
                        lock    b1115bf8e14a60131a196f908223e4506b0ddc35 \
                        rmd160  a3ef55adad8daf0d760b6dc7abda3d15e204bc65 \
                        sha256  badea2a6dae51e3bd9845f355287a255837df86b5ed68c676e3c8403d4b45aa9 \
                        size    5718 \
                    github.com/apparentlymart/go-textseg \
                        lock    fb01f485ebef760e5ee06d55e1b07534dda2d295 \
                        rmd160  a0a83af400f83916b768f7e62b3817f8dd2d1974 \
                        sha256  5ad808a40833bdab751f9e5cd6f22fe2f6673ae3ffd74b7513304b0069517631 \
                        size    129578 \
                    github.com/aws/aws-sdk-go \
                        lock    572908275ed4e38fef7ccb7d507f2faacaa7ab36 \
                        rmd160  2d7716086204943cf572e8000a2d72253f2b3547 \
                        sha256  c630bc05a2f6ecdc40bc748033e8c713c41bf1073e0c0d9f6a17008aa58b6c41 \
                        size    11929330 \
                    github.com/bgentry/go-netrc \
                        lock    9fd32a8b3d3d3f9d43c341bfe098430e07609480 \
                        rmd160  aed207effc15727c87b76b4ac4bc88ff90c674c2 \
                        sha256  87c46c2ad046961c1f465eadd0dde06cfa3851f9bbe10e94177c50934f6f0d6a \
                        size    8411 \
                    github.com/bmatcuk/doublestar \
                        lock    2437321e1473408f122a95f65df3d8841fec4fba \
                        rmd160  b736a3c7ccf8b028d10c9852c33c60754f03ff01 \
                        sha256  28bf3426e055459da6feee84cb9d639325462a195cb28f725e75cf5d69249c2d \
                        size    8727 \
                    github.com/davecgh/go-spew \
                        lock    8991bc29aa16c548c550c7ff78260e27b9ab7c73 \
                        rmd160  d9379d4bcd71fea8043987bba01a0e22f502a6d4 \
                        sha256  80ad9d9a204c9add05bbca1c8d75ebc9574bd4a36537ee233cbd3f0d65711972 \
                        size    42171 \
                    github.com/fatih/color \
                        lock    5b77d2a35fb0ede96d138fc9a99f5c9b6aef11b4 \
                        rmd160  8a65cf00de5399f4498b41b0baed82da363f02d5 \
                        sha256  a553c1229fe10a6b0765cbbb90245bf3383a99ba52b9608052420b40ca30d148 \
                        size    816675 \
                    github.com/go-errors/errors \
                        lock    a6af135bd4e28680facf08a3d206b454abc877a4 \
                        rmd160  22a0344a550bf59c7efcea8876f8f5c06ba9f7f3 \
                        sha256  e627783d715b21fa562c87daee06c30cc5889b87c625e6ad2c06c20e13946494 \
                        size    8650 \
                    github.com/golang/protobuf \
                        lock    b5d812f8a3706043e23a9cd5babf2e5423744d30 \
                        rmd160  801150957b99de8eef10cb8d5ea2a08b240f2cb5 \
                        sha256  a53c2c8c5c02311d2fa3bc6656614e20f9e5568b87c9f07702f083457e69f7d2 \
                        size    310935 \
                    github.com/google/go-cmp \
                        lock    6f77996f0c42f7b84e5a2b252227263f93432e9b \
                        rmd160  023b52ba78fcaa734cfa0f54111e6ee8aba4777b \
                        sha256  0672ceb4418adc04c39047892ec8f6322165c099ac3755c491ff722c47897cae \
                        size    76135 \
                    github.com/google/uuid \
                        lock    0cd6bf5da1e1c83f8b45653022c74f71af0538a4 \
                        rmd160  69112e9735ecc1d5360a3cc31531f8be661a007f \
                        sha256  70be7dec37826f2cbe13acfe534ce74cbb2107c1e348eb4e8365f7d900002e40 \
                        size    13552 \
                    github.com/googleapis/gax-go \
                        lock    beaecbbdd8af86aa3acf14180d53828ce69400b2 \
                        rmd160  29d7b5f51e7d314a6ce76e70442aa8c53c2649ce \
                        sha256  6c36fe0b3c4ceeba533f20f851d33cbd226c55708b7f68387a0dd279431be6de \
                        size    14344 \
                    github.com/gruntwork-io/terratest \
                        lock    a02960d4ef0711ae95ae2651271b4e073f88da4e \
                        rmd160  81da8082bead75c8499183106c96e1a1d9869773 \
                        sha256  d2510eb28c0960422e7f22917121ab84b843266715a7e431ac64b06aea9ca1db \
                        size    594212 \
                    github.com/hashicorp/errwrap \
                        lock    8a6fb523712970c966eefc6b39ed2c5e74880354 \
                        rmd160  d9bf75f667d7bec9b4b11ca34de7ca722495b914 \
                        sha256  49e80cf52f294ce69fcc8cd26f06b8d8cee2623f6e0012df871b355fb7b17787 \
                        size    8351 \
                    github.com/hashicorp/go-cleanhttp \
                        lock    eda1e5db218aad1db63ca4642c8906b26bcf2744 \
                        rmd160  421ba8dea2ca1d8a013b682866e75d4a0d724d2f \
                        sha256  f51adef8dd7f4cd168516a57c65d10d6bdc844e65f86e2c04af95f1afc1b870a \
                        size    8068 \
                    github.com/hashicorp/go-getter \
                        lock    f9ec369200fd2163b8f452e5e45696d83ae3f4b6 \
                        rmd160  6e7c2e76bc4932365f0d561bd76e3b463db7f793 \
                        sha256  d8a0dfa0483ac639acb2069bd047c3aa5b3cb2198b9bcefbebad2c1887c8c044 \
                        size    75393 \
                    github.com/hashicorp/go-multierror \
                        lock    886a7fbe3eb1c874d46f623bfa70af45f425b3d1 \
                        rmd160  5654b3418ddaf1fc69a9f6387126c1445259114a \
                        sha256  b16af039752b3be7ccefe05422dc2a48b6b3318188e0ef54ef61276c776f4eb6 \
                        size    10071 \
                    github.com/hashicorp/go-safetemp \
                        lock    c9a55de4fe06c920a71964b53cfe3dd293a3c743 \
                        rmd160  2ef6f7b930acfb72354c168b7b03c8b46c9beb0d \
                        sha256  c2a03e89a84033f548b14f85f24e992991e56c5ab84dac494df9949fe31f09cb \
                        size    6552 \
                    github.com/hashicorp/go-uuid \
                        lock    4f571afc59f3043a65f8fe6bf46d887b10a01d43 \
                        rmd160  d0c4a2e7216c1afccbfce3094b53574f66aad0b1 \
                        sha256  da0b9cf0aa9e613a8f0878cf43fc2c16eaab83b6dad2c1f0d31221764d2d8aef \
                        size    6848 \
                    github.com/hashicorp/go-version \
                        lock    ac23dc3fea5d1a983c43f6a0f6e2c13f0195d8bd \
                        rmd160  4e05420a3160fff330d734de9060dd590fdfb2db \
                        sha256  aa7d6e4b1b2c7baa447561c3b141780048f9f2fcca8873c9b212792819093470 \
                        size    13099 \
                    github.com/hashicorp/golang-lru \
                        lock    7087cb70de9f7a8bc0a10c375cb0d2280a8edf9c \
                        rmd160  dd02645a94c90ef435ed1662531754761e4a4d8b \
                        sha256  d9393f70b3fcd62d078e0ceefe9f6605d5086a986ba6cd7ed268b980eb1b6bf4 \
                        size    12986 \
                    github.com/hashicorp/hcl2 \
                        lock    318e80eefe28c3aa01b434c61bcf4c83a0cc6b25 \
                        rmd160  22955cc03e2818eadee5e9bd60db9d68f84d66c8 \
                        sha256  5ee67bca3115b94f00c2a41820ea87e22b74a35c946a82c6b3915d7b524e2e28 \
                        size    380785 \
                    github.com/hashicorp/terraform \
                        lock    abec0acf40d8e31ac612a244cf3886fb3bcce0bb \
                        rmd160  988db2a2036349c9861999b42d3fce9c62f895c5 \
                        sha256  296ecf97f77e263f645dacf89a18ba46760ae843a49b375c57b1d90b7526bcb2 \
                        size    10090893 \
                    github.com/jmespath/go-jmespath \
                        lock    c2b33e84 \
                        rmd160  5599516af7167f50fd50b90f7f7247658275032c \
                        sha256  08f16ad09da5b3d22b2500d1b37abd7170654184292f6869c551f0de13ad9013 \
                        size    48224 \
                    github.com/mattn/go-colorable \
                        lock    167de6bfdfba052fa6b2d3664c8f5272e23c9072 \
                        rmd160  7251bb6bf8e5651a52c8e3244d7117918e812f89 \
                        sha256  22ae6fdf63bccd195bf108013ba477c896a11fffdbb3398487914e32e1db9b2a \
                        size    7602 \
                    github.com/mattn/go-isatty \
                        lock    e1f7b56ace729e4a73a29a6b4fac6cd5fcda7ab3 \
                        rmd160  1d29798d07ac2024366657bf4fbe6fc38ab09e2e \
                        sha256  136c9995213583e6341d6dbab4cf0852554227fbf5716189defe25682c11d716 \
                        size    3910 \
                    github.com/mattn/go-zglob \
                        lock    2ea3427bfa539cca900ca2768d8663ecc8a708c1 \
                        rmd160  4fee750ce871ba2c7fbf917599baac7791a4f958 \
                        sha256  8b8b0cd95a5ee0637876ae404359ecb3df11f878782a0c1318663b418ff0b35a \
                        size    7711 \
                    github.com/mitchellh/go-homedir \
                        lock    af06845cf3004701891bf4fdb884bfe4920b3727 \
                        rmd160  44b3985e40e5bbb22d11f8622c340f9ed727ea91 \
                        sha256  024c8a57316c7fbc0eb23cdbfd57f72a74b51beb83d714034d67ee9aba48100c \
                        size    3366 \
                    github.com/mitchellh/go-testing-interface \
                        lock    6d0b8010fcc857872e42fc6c931227569016843c \
                        rmd160  93edee720b3f88e9ccf24cbd0a03078462db3075 \
                        sha256  5b9a2f2fddbf035e32aac433c0fe5d9e99aede1db77c13a6c4e8929cd7e06cb5 \
                        size    2814 \
                    github.com/mitchellh/go-wordwrap \
                        lock    9e67c67572bc5dd02aef930e2b0ae3c02a4b5a5c \
                        rmd160  9019795baad40dfcaa09ac4b45a8ebc3ff13b6f0 \
                        sha256  319bf49230fa54f8cf5f18cbfcf5f22fca4aae90a517c77ae5d1fbb13684afa5 \
                        size    2781 \
                    github.com/mitchellh/mapstructure \
                        lock    3536a929edddb9a5b34bd6861dc4a9647cb459fe \
                        rmd160  a4e01781ea5bb0c987e18e8e450c8f1023d5a857 \
                        sha256  9c1076f5a8e923d028cb65c36143f3b1478cbaa4420e2e8f332719edc2fc4f71 \
                        size    20992 \
                    github.com/pmezard/go-difflib \
                        lock    792786c7400a136282c1664665ae0a8db921c6c2 \
                        rmd160  3c099c2b9aa004bbb2dc29cd3ea6e2c5f4e378aa \
                        sha256  a3974cf6636de96512b3c312bd73c0c6d7e7460dda24688b3f058ea30b092a2b \
                        size    11404 \
                    github.com/stretchr/testify \
                        lock    ffdc059bfe9ce6a4e144ba849dbedead332c6053 \
                        rmd160  80582370443047a1d7020211865d85d54c036eea \
                        sha256  ac782171992e3af1c8ac8384cbf4a39706ec5f9e3c6eed57a246e02dce571762 \
                        size    102899 \
                    github.com/ulikunitz/xz \
                        lock    6f934d456d51e742b4eeab20d925a827ef22320a \
                        rmd160  518e14e0d9d8ea7f2b0eccc69ae8c773d68b2da0 \
                        sha256  b201ef442ce23b8b3005f5767aa519b622db64e600f608446d27a5a19593970c \
                        size    477447 \
                    github.com/urfave/cli \
                        lock    cfb38830724cc34fedffe9a2a29fb54fa9169cd1 \
                        rmd160  b54f7232fbbfda640f7d9411a5dedab3adf6a888 \
                        sha256  94f12754129bce1d3435efd84826a73fc8af70f61f9264c60c1f554d425d503a \
                        size    58405 \
                    github.com/zclconf/go-cty \
                        lock    6fd39ad70c3a6bbdb1b4e47444e4cce72f901200 \
                        rmd160  fcf245626a2f4d8f8cb25c934d19693378afcae7 \
                        sha256  c768d7b5807ecbc67180b423feb16f5b4dc2799adb2cd6caf9e0fe0ae6fce6db \
                        size    137785 \
                    github.com/zclconf/go-cty-yaml \
                        lock    bc34c981dadb5ed30af852693e3aba8fb6546f42 \
                        rmd160  56c8239cfc1e9e8d58ccef06b331d7e071137bdc \
                        sha256  302b200bf8f6fc17ed7dd35245c1ef819b01129c22124c8b4d02e9c76f095c05 \
                        size    59051 \
                    go.opencensus.io \
                        lock    9c377598961b706d1542bd2d84d538b5094d596e \
                        rmd160  0 \
                        sha256  0 \
                        size    0 \
                    golang.org/x/crypto \
                        lock    5c40567a22f818bd14a1ea7245dad9f8ef0691aa \
                        rmd160  2451a55f60529c1f9f4220594ba47132e63079e7 \
                        sha256  50a14a9e51490474c216a5b232f44e1496f71f154a44d7fc023cd587e1e164ac \
                        size    1690714 \
                    golang.org/x/net \
                        lock    461777fb6f67e8cb9d70cda16573678d085a74cf \
                        rmd160  f7a2fcc1cd22317a8dbb98493fed0405332415e4 \
                        sha256  ceb6c342d036b279af701059593c114dd9db2d7820d54b17eaec078e87b6aa53 \
                        size    1097085 \
                    golang.org/x/oauth2 \
                        lock    0f29369cfe4552d0e4bcddc57cc75f4d7e672a33 \
                        rmd160  a2ebd909ab79d080e72933bb8ba5020a6eb71fbc \
                        sha256  9461d6f2f43e6da87c77d3f93f08cc43b3f5dd96bbc5fb41714bcc0cca17df5b \
                        size    45486 \
                    golang.org/x/sys \
                        lock    93c9922d18aeb82498a065f07aec7ad7fa60dfb7 \
                        rmd160  9d8aef76b38f0920cc7546aedbea1f5d36675fc5 \
                        sha256  baaedaaffe4605146e1ca36dc40f01eb4259661937bba9a2451af18cbb380fdb \
                        size    1427474 \
                    golang.org/x/text \
                        lock    342b2e1fbaa52c93f31447ad2c6abc048c63e475 \
                        rmd160  acc843fa89b718f85b869fc2964f2b6eb292f4bd \
                        sha256  859f042702a69cc885226520c19e14ef12c5779041df73575ecdf3466f4ac665 \
                        size    7168441 \
                    google.golang.org/api \
                        lock    890e5eb51fe205e56dc55eb68d63e82039730816 \
                        rmd160  0 \
                        sha256  0 \
                        size    0 \
                    google.golang.org/appengine \
                        lock    b2f4a3cf3c67576a2ee09e1fe62656a5086ce880 \
                        rmd160  0 \
                        sha256  0 \
                        size    0 \
                    google.golang.org/genproto \
                        lock    eb0b1bdb6ae60fcfc41b8d907b50dfb346112301 \
                        rmd160  0 \
                        sha256  0 \
                        size    0 \
                    google.golang.org/grpc \
                        lock    501c41df7f472c740d0674ff27122f3f48c80ce7 \
                        rmd160  0 \
                        sha256  0 \
                        size    0

destroot {
    xinstall -m 755 ${worksrcpath}/${name} ${destroot}${prefix}/bin/
}
```

You can see deps from unknown hosts:

- `google.golang.org`
- `go.opencensus.io`
- `cloud.google.com`

These would need to be handled in the portgroup [here](https://github.com/macports/macports-ports/blob/3c405693f56a34a25a8b7f0b5491a3b7c6f57a4c/_resources/port1.0/group/golang-1.0.tcl#L197) if they are actual hosts like Bitbucket or GitHub, or [here](https://github.com/macports/macports-ports/blob/3c405693f56a34a25a8b7f0b5491a3b7c6f57a4c/_resources/port1.0/group/golang-1.0.tcl#L91) if they are redirectors.

Alternatively you could leave the portgroup as-is and handle them manually by adding the appropriate `master_sites`, `distfiles`, and `checksums` entries in the portfile.

**Comment by szczad** [comment]
The amount of dependencies (both handled by `golang` PG and those that aren't) add a lot of complexity to the port file's maintenance. 

I have tried building that using `go2port` as @amake suggested with the same result. Honestly, I am not a golang or MacPorts ninja. Building the app manually goes smoothly for me, however I have trouble adding not handled dependencies on my own. But I still have some ideas to try maybe later this week.

**Pull request closed without merging**
