### PR TITLE
udunits2: retroactive license update

### PR DESCRIPTION
**Pull request by Dave-Allured**
* Update udunits2 port license from private, to OSI-approved Apache-2.0.
* Update retroactively for current and upcoming Macports versions.
* Purpose:  Make udunits2 and dependents binary distributable.

Upstream already changed their license two months ago to Apache-2.0:
https://github.com/Unidata/UDUNITS-2/commit/c790c5bbe23c2cb2b4c56671a4570cabf439c06c
https://github.com/Unidata/UDUNITS-2/issues/102

However, the updated package version 2.3.0 is not released, and there is no time table for release.  Macports binaries of udunits2 and dependents, such as ncarg/NCL, are currently blocked for public distribution.

I would like to accelerate distributability for both current 2.2.27.27 and upcoming 2.2.28 versions.  Therefore I propose this retroactive license update.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

NOT TESTED.  PORTFILE ADMINISTRATIVE CHANGE ONLY.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by Dave-Allured** [comment]
Note.  This PR does not change the actual legal license.  The original license embedded by Unidata in each udunits-2 version remains in force for all legal purposes.

The actual change is a one-line command that tells MacPorts automata how to interpret the license for automatic purposes only, such as determining binary distributability.

**Comment by ryandesign** [comment]
> Therefore I propose this retroactive license update.

It's not up to us to decide whether this is acceptable. If the upstream developer has stated that this previous version is now retroactively under this new license, then this is fine. (I did not see such a statement; if I missed it, please point it out.) If they have not said this, then this is not fine and should be reverted and we should manually delete the packages from the public packages server.

In addition, although it can't be changed back now, *please* do not increase a port's revision unnecessarily. It causes everyone to have to rebuild or at least reinstall the port, with no benefit to anyone. Examples of situations when it is and is not appropriate to increase the revision are documented extensively in the guide. [Please read it](https://guide.macports.org/#reference.keywords).

**Comment by Dave-Allured** [comment]
My apologies.  Thank you for pointing out the section on when not to increase the revision.

@cjones051073, would you please revert this PR?  I can not do it myself because I do not have write privileges.  Thank you.

**Comment by Dave-Allured** [comment]
Okay.  The upstream developer has now retroactively approved the Apache 2.0 License for application to UDUNITS version 2.2.28.  Public distribution of the Macports udunits2 binary is now permitted.

I will ensure the portfile is accurate, and add a comment about this.

**Pull request merged**
