### PR TITLE
drupal8, drush: delete ports

### PR DESCRIPTION
**Pull request by chrstphrchvz**
* `drush`: No one reported that this port is broken and outdated. Latest upstream release compatible with Drupal 7 is 8.4.8, published 2021-03-22; Drupal 8 is end-of-life. Port broke at some point because `${worksrcpath}` is now a symbolic link to the actual extracted source directory `drush-ops-drush-b1f1e42` (in `${worksrcdir}`), causing destroot to only create two broken symbolic links. No dependents.

* `drupal8`: Upstream support for Drupal 8.x ended on 2021-11-02. No other dependents.
    Closes: https://trac.macports.org/ticket/60606

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

### CODE REVIEW

**Comment by pmetzger** [comment]
Agreed. There is no point in maintaining ports that are clearly broken and that no one has complained are broken.

**Comment by chrstphrchvz** [comment]
Alternatively, drush could be kept/fixed for drupal7 (it has 1 year left before EOL), while still removing drupal8 and drush `+drupal8`. The php71 dependency in drush should probably also be removed or changed; drupal7 already depends on php74.

**Comment by chrstphrchvz** [comment]
Given no comments in 2 weeks, I think it is okay to proceed with deleting these ports.

**Comment by pmetzger** [comment]
Done.

**Pull request merged**
