### PR TITLE
eigen3: backport upstream PPC patch; eigen3-devel: update to current upstream

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

1. https://gitlab.com/libeigen/eigen/-/commit/4d05765345e7e4a984d600039f797e2fede924f3
2. Update of `eigen3-devel`, long due.

Why fix is needed: https://trac.macports.org/ticket/66602

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Okay, looks like for `eigen3-devel` Fortran is needed:
```
CMake Error at /opt/local/share/cmake-3.24/Modules/CMakeDetermineFortranCompiler.cmake:33 (message):
    Could not find compiler set in environment variable FC:
  
    nofortran.
  Call Stack (most recent call first):
    CMakeLists.txt:495 (include)
  
  
  -- Configuring incomplete, errors occurred!
```

**Comment by eborisch** [comment]
I was planning to drop eigen3-devel next time I updated the port, but otherwise I'm fine with the backport.

**Comment by barracuda156** [comment]
> I was planning to drop eigen3-devel next time I updated the port, but otherwise I'm fine with the backport.

@eborisch Perhaps does not hurt keeping it? I can update it once in a while.

**Comment by barracuda156** [comment]
@eborisch Having said that, I am okay to drop `eigen3-devel` too, if you prefer so. (But if the only issue is a burden of updating it, I can handle it.)

**Comment by eborisch** [comment]
It's more that time between minor version upgrades has gotten much longer as the project matures (five years for 3.3 -> 3.4), so I don't need to build the "upcoming version" as frequently for testing.

So for me, the administrative overhead of keeping it around isn't worth the times when I might want it, but if you're up for maintaining the -devel flavor, feel free to add to yourself as a co-maintainer and go for it.

**Comment by barracuda156** [comment]
> So for me, the administrative overhead of keeping it around isn't worth the times when I might want it, but if you're up for maintaining the -devel flavor, feel free to add to yourself as a co-maintainer and go for it.

@eborisch Thank you! Done.

**Comment by barracuda156** [comment]
@eborisch Could we merge this now?

**Comment by eborisch** [comment]
How does #17607 look for this?

**Comment by barracuda156** [comment]
@eborisch Great, thanks.

**Pull request closed without merging**
