### PR TITLE
opam: update to 2.2.0

### PR DESCRIPTION
**Pull request by kit-ty-kate**
#### Description

cc @pmetzger if you have some time to continue this. I don't know the reason for the patches and i do not have the necessary `rmd160sum` program on my current machine.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
> i do not have the necessary `rmd160sum` program on my current machine.

Sure you do. It's on every Mac: `openssl dgst -rmd160`. But you don't need to generate checksums manually; MacPorts will do it for you and even print out the revised `checksums` lines for you if you run `sudo port -d checksum`.

You shouldn't submit incomplete and untested PRs.

**Comment by barracuda156** [comment]
@kit-ty-kate This should really be marked a draft, until tested.

**Comment by pmetzger** [comment]
Looks like the patches no longer apply.

**Comment by pmetzger** [comment]
Kate, the patches are pretty simple, and the reason they are there is in comments in the Portfile. If you want, you can fix them, or if you need me to, I can do it.

**Comment by barracuda156** [comment]
I can check later today, but at least something of patches may not be needed, since the related issue could have been solved by upstream.
But some should still be needed, perhaps (whatever Dune port uses, should apply here as well).

**Comment by kit-ty-kate** [comment]
> I can do it

I don't have much time for that at the moment so i'd appreciate it if you have some

**Comment by pmetzger** [comment]
I'll fix this later today.

**Comment by pmetzger** [comment]
@kit-ty-kate I have the patches etc. applying and the whole thing (seemingly) building.

Questions:

1. Are there tests? The Portfile has never had any, but it might be nice to add them.
2. Is it the case that there is no longer installed documentation other than the manual pages? If so, I can drop the `--docdir` patch.

**Comment by kit-ty-kate** [comment]
> Are there tests? The Portfile has never had any, but it might be nice to add them.

Yes `make test` however they cannot be ran from a sandbox and require network access

> Is it the case that there is no longer installed documentation other than the manual pages? If so, I can drop the `--docdir` patch.

i don't think the manual pages were ever installed but in any case what is installed is defined by dune which will install `CHANGES`, `LICENSE` and `README.md` so i believe this patch is still required.

**Comment by pmetzger** [comment]
The man pages are in fact installed. CHANGES, LICENSE and README.md are no longer installed when I do the obvious thing. This is what gets installed when I naively update the patches:

```
/opt/local/bin/opam
/opt/local/bin/opam-installer
/opt/local/share/man/man1/opam-admin-add-constraint.1.gz
/opt/local/share/man/man1/opam-admin-add-hashes.1.gz
/opt/local/share/man/man1/opam-admin-cache.1.gz
/opt/local/share/man/man1/opam-admin-check.1.gz
/opt/local/share/man/man1/opam-admin-filter.1.gz
/opt/local/share/man/man1/opam-admin-help.1.gz
/opt/local/share/man/man1/opam-admin-index.1.gz
/opt/local/share/man/man1/opam-admin-lint.1.gz
/opt/local/share/man/man1/opam-admin-list.1.gz
/opt/local/share/man/man1/opam-admin-make.1.gz
/opt/local/share/man/man1/opam-admin-update-extrafiles.1.gz
/opt/local/share/man/man1/opam-admin-upgrade.1.gz
/opt/local/share/man/man1/opam-admin.1.gz
/opt/local/share/man/man1/opam-clean.1.gz
/opt/local/share/man/man1/opam-config.1.gz
/opt/local/share/man/man1/opam-env.1.gz
/opt/local/share/man/man1/opam-exec.1.gz
/opt/local/share/man/man1/opam-help.1.gz
/opt/local/share/man/man1/opam-info.1.gz
/opt/local/share/man/man1/opam-init.1.gz
/opt/local/share/man/man1/opam-install.1.gz
/opt/local/share/man/man1/opam-installer.1.gz
/opt/local/share/man/man1/opam-lint.1.gz
/opt/local/share/man/man1/opam-list.1.gz
/opt/local/share/man/man1/opam-lock.1.gz
/opt/local/share/man/man1/opam-option.1.gz
/opt/local/share/man/man1/opam-pin.1.gz
/opt/local/share/man/man1/opam-reinstall.1.gz
/opt/local/share/man/man1/opam-remote.1.gz
/opt/local/share/man/man1/opam-remove.1.gz
/opt/local/share/man/man1/opam-repository.1.gz
/opt/local/share/man/man1/opam-search.1.gz
/opt/local/share/man/man1/opam-show.1.gz
/opt/local/share/man/man1/opam-source.1.gz
/opt/local/share/man/man1/opam-switch.1.gz
/opt/local/share/man/man1/opam-tree.1.gz
/opt/local/share/man/man1/opam-uninstall.1.gz
/opt/local/share/man/man1/opam-unpin.1.gz
/opt/local/share/man/man1/opam-update.1.gz
/opt/local/share/man/man1/opam-upgrade.1.gz
/opt/local/share/man/man1/opam-var.1.gz
/opt/local/share/man/man1/opam-why.1.gz
/opt/local/share/man/man1/opam.1.gz
```

**Comment by kit-ty-kate** [comment]
ah sorry i thought you were referring to the opam manual in `doc/manual` not the "man" pages. Yes they are indeed always installed

**Comment by pmetzger** [comment]
Hrm. It also looks like nothing else was being installed for 2.1.6 anyway, so I'm going to update things and we can figure out what might or might not be needed for a revision 1 of the Portfile.

**Comment by pmetzger** [comment]
Updated in https://github.com/macports/macports-ports/commit/387c95d6c33514b17104888cb2220994717a1dc9 but we should still figure out the rest of what we want to do here. @kit-ty-kate feel free to comment on this closed pull request so we can figure out anything else we need.

**Comment by pmetzger** [comment]
BTW, opam seems to be behaving more or less correctly out of MacPorts on my test machines.

**Comment by kit-ty-kate** [comment]
Thanks a lot!

**Comment by pmetzger** [comment]
@kit-ty-kate I'm still unclear on how the opam build process is supposed to be told to build documentation and where it is supposed to install it; the README on Github isn't explicit.

**Comment by barracuda156** [comment]
Just for the record, 2.2.0 built fine on my PowerPC system.

**Pull request closed without merging**
