### PR TITLE
hyper: update to 3.3.0

### PR DESCRIPTION
**Pull request by herbygillot**
Fixes: https://trac.macports.org/ticket/65020

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
@reneeotten

**Comment by pmetzger** [comment]
@reneeotten ?

**Comment by reneeotten** [comment]
I commented in the associated Trac ticket - the issue regarding the compiler still persists

**Comment by herbygillot** [comment]
I spent some time on this, and had zero success convincing `node_gyp` to use a given compiler.  I think we should just update this port to its latest and deal with the compiler issue some other time.

**Comment by reneeotten** [comment]
thanks @herbygillot - fine with me!

**Pull request merged**
