### PR TITLE
mupdf: update to 1.13.0, remove x11

### PR DESCRIPTION
**Pull request by mojca**
* Update to 1.13.0
* Use OpenGL instead of X11

Closes: https://trac.macports.org/ticket/57102

#### Description

I updated to 1.13.0 and introduced some patches to make it work with OpenGL instead of X11 (in particular I had to enable the "if this is Linux" portion of `Makerules`, else it would not pull in any flags for compiling the dependencies). Note however that if X11 is needed, `mupdf` actually creates two binaries, `mupdf-gl` and `mupdf-x11`, so one can have both installed simultaneously. In fact, removing `HAVE_X11=no` from `destroot.args` seems to be sufficient to get X11 working (X11 itself is also pulled in as a dependency of `harfbuzz`).

(Experienced `mupdf` users complained that some keys from X11 don't seem to be working in the OpenGL version which might be another reason to keep the X11 support around if desired, but I cannot judge.)

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65
Xcode 9.4.1 9F2000 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`? (complains about name of patch, not sure if I should obey)
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files? (would be grateful if others tested as well)

### CODE REVIEW

**Comment by pmetzger** [comment]
This is sufficiently intrusive that I don't think it falls under `openmaintainer`. @harciga, do you have an opinion on these changes?

**Comment by mojca** [comment]
No, it certainly doesn't fall into the openmaintainer policy. On the other hand I'm not sure when @harciga was last seen around (I would suggest to send an email). I would prefer if there was an actual user of the software confirming that the it works fine, and provide feedback about whether or not we want both OpenGL and X11 builds.

**Comment by pmetzger** [comment]
@mojca If you know someone who uses it, maybe add them to the reviewers or tag them? Most people aren't maniacs like me who look at every single PR.

**Comment by mojca** [comment]
I have no idea who uses the software. People who committed any changes in the last two years include @ryandesign, @kurthindenburg, @dbevans, @neverpanic, @g5pw. I included some of them in the Trac ticket.

Based on feedback by @braslau it seems that some keys are ignored and apparently other distributions would ship both versions (gl and x11). So maybe I should create an optional (on by default) variant `+x11` which would install both.

**Comment by g5pw** [comment]
I used `mupdf` as an engine for `zathura`, and that run without X11 IIRC. it's been a couple of years since I last run it on Mac though...

**Comment by neverpanic** [comment]
I've just tested `zathura-plugin-pdf-mupdf` works with your updated version of `mupdf`, so I guess you can go ahead and merge this.

**Comment by mojca** [comment]
There doesn't seem to be any objections, so I can merge this.

I now added an optional second commit which (re)introduces `x11` as a non-default variant just in case that anyone would want to stick with X11 for whatever reason. (Being used to key shortcuts? Having a workaround for the rumour of OpenGL being excluded from newer OSes?) I can either include it (squash the changes) or remove it. I'm slightly inclined towards keeping it as non-default, but I have no strong feelings about that. If there will be no votes, I'll squash the changes.

**Comment by pmetzger** [comment]
Go for it.

**Comment by mojca** [comment]
Accidentally closed by bd6735be711d8ed9edeb9a26bcbf88b2a1a6c1c2.

**Pull request closed without merging**
