### PR TITLE
Update librdkafka to v1.1.0

### PR DESCRIPTION
**Pull request by diogovieira**

### CODE REVIEW

**Comment by mf2k** [comment]
LGTM. But the commit message needs to be tweaked to follow our guidelines. Use this instead:

librdkafka: Update to version v1.1.0

**Comment by jmroot** [comment]
I don't think it's necessary to insist on following the recommended format exactly, as long as all the necessary information is conveyed, which it is here.

**Comment by cjones051073** [comment]
> I don't think it's necessary to insist on following the recommended format exactly, as long as all the necessary information is conveyed, which it is here.

I very much disagree. We have this convention for a reason as it makes scan reading the commits much easier if they all follow the same pattern. Its in our guidelines

https://trac.macports.org/wiki/CommitMessages

So we should follow it, or start a discussion as to changing our guidelines.

**Comment by cjones051073** [comment]
@diogovieira many thanks for your contribution. I fixed the commit message this time, but in future please follow our guidelines.

Also, please in future do not just delete everything from the commit description. The template is there for you to follow to provide us useful information on the MR. Please follow it.

**Comment by diogovieira** [comment]
@mf2k @jmroot @cjones051073 thanks for the feedback. Sorry for not answering and fixing this soon by I didn't get to it. I just deleted the description since at the time it seemed to me to be useful for bug fixes, not for version bumps. But I'll keep that in mind.

Glad to have contributed.

**Pull request merged**
