### PR TITLE
py-poppler-qt4: force rebuild

### PR DESCRIPTION
**Pull request by kencu**
against new poppler-qt4-mac

### CODE REVIEW

**Comment by kencu** [comment]
only builds once poppler-qt4-mac is installed, of course.

**Comment by pmetzger** [comment]
So, again: I feel really weird about intentionally maintaining support for something known insecure, especially without Big Red Warnings discouraging people from using them. The world is a dangerous place these days, and I'd rather we not keep around things that can't be maintained in a safe state. Do you disagree strongly?

**Comment by kencu** [comment]
I agree completely, Perry. We'll see if we can come up with a better option for the future. Ports will move towards poppler-qt5, and that will be the default on all ports that support it. Only ports that don't support poppler-qt5, or systems that don't, will use this older version (which is in fact much newer than the version we had up until a week ago, as you know.).

**Comment by kencu** [comment]
As poppler-qt4-mac has built on all systems now, I think we can pop in this update to use it and keep this port functional.

**Pull request merged**
