### PR TITLE
p5-future: update to version 0.46

### PR DESCRIPTION
**Pull request by dbevans**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.7 19H2
Xcode 12.0.1 12A7300 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
> ###### Tested on
> macOS 10.15.7 19H2
> Xcode 12.0.1 12A7300

Xcode version is irrelevant for ports that do not use Xcode tools, as is often the case for `noarch` ports. In this case, what could be relevant is the version of Perl tested. Maybe the PR template could suggest providing this, although it may not be as trivial to check for.

**Review by chrstphrchvz — APPROVED** [review]
I have basically not used this module since submitting it to MacPorts; I can be dropped as a maintainer. Likewise for IO::Async.

**Comment by chrstphrchvz** [comment]
> Xcode version is irrelevant for ports that do not use Xcode tools, as is often the case for `noarch` ports.

…unless this is what provides e.g. `make` to ports not using MacPorts' version; I primarily meant that it was not using the Xcode compilers.

**Comment by dbevans** [comment]
> I have basically not used this module since submitting it to MacPorts; I can be dropped as a maintainer. Likewise for IO::Async.
OK, will do.

**Pull request merged**
