### PR TITLE
cmh: new port in math; pari (one of dependencies): fix target for Rosetta

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Since `fplll` and `mpfrcx` are merged, here is their dependent: https://www.multiprecision.org/cmh/home.html

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Interesting: gcc-4.2 builds `cmh` with no issues, but clang fails:
```
cm2.c:933:14: error: implicit declaration of function 'asprintf' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      int rc = asprintf(&tmp, LOG_PROGRESS LOG_NOTIMESTAMP "%s", fmt);
               ^
  cm2.c:1558:18: error: implicit declaration of function 'asprintf' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
          int rc = asprintf(&outputname_temp, "%s.tmp", outputname);
                   ^
  cm2.c:1705:55: error: implicit declaration of function 'strsignal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
     fprintf (stderr, "ERROR Received signal \"%s\"\n", strsignal (signum));
                                                        ^
  cm2.c:1705:55: warning: format specifies type 'char *' but the argument has type 'int' [-Wformat]
     fprintf (stderr, "ERROR Received signal \"%s\"\n", strsignal (signum));
                                               ~~       ^~~~~~~~~~~~~~~~~~
                                               %d
  1 warning and 3 errors generated.
```

**Comment by barracuda156** [comment]
@harens Could you please take a look? This is perhaps good to merge. Rosetta fix for `pari` affects only 10.6.x when the build is for ppc. `cmh` is a new port, builds fine here and locally.

**Review by harens — APPROVED** [review]
LGTM. Thanks for all of the great work you've been doing @barracuda156 👍

**Comment by barracuda156** [comment]
@harens Thank you!

**Pull request merged**
