### PR TITLE
rubberband: fix system test for < 10.7

### PR DESCRIPTION
**Pull request by kencu**
closes: https://trac.macports.org/ticket/56541

### CODE REVIEW

**Comment by ryandesign** [comment]
Please add a link to the upstream PR in the header of the patchfile.

According to [Apple documentation](https://developer.apple.com/documentation/accelerate/1470393-vvfabsf?language=objc), `vvfabsf` is in 10.7 and later. So should the test be `< 1070` rather than `<= 1070`?

**Comment by kencu** [comment]
> According to Apple documentation, vvfabsf is in 10.7 and later. So should the test be < 1070 rather than <= 1070?

I spent a few hours updating a 10.7 system I use to the current versions of MacPorts and all the ports, and so I can now answer this question.

both vvfabsf and vvfabf are in 10.7. The latter works, but is marked deprecated. The former would be preferred to avoid the deprecation warning, although in the end gives the same result... the test as currently written functions properly on 10.7.

If I was writing rubberband, I would have marked the test as < 1070 myself, just to avoid the deprecated warning. 

I already know what you're going to say, so I can update the test for our purposes and then feed the suggestion upstream.

**Comment by ryandesign** [comment]
> the test as currently written functions properly on 10.7

My point was that testing `<= 1070` is always incorrect, as I understand it. If the intention was to have something happen on 10.7.x and earlier, then the correct test was `< 1080`. I do not know how Apple uses the last digit of that number on 10.7.x, but [it seems](https://opensource.apple.com/source/xnu/xnu-4570.41.2/EXTERNAL_HEADERS/AvailabilityMacros.h.auto.html) that at least as of 10.10, the last digit(s) are mapped to the minor version number. In which case, testing `<= 1070` doesn't mean "10.7.x or earlier", it means "10.7.0 or earlier", which is probably not what was intended, unless there's some 10.7.0-specific bug in this function that I don't know about.

**Comment by kencu** [comment]
> I do not know how Apple uses the last digit of that number on 10.7.x


 I believe they only started that kind of granularity on 10.10 and up, e.g.:

```
#define __MAC_10_0            1000
#define __MAC_10_1            1010
#define __MAC_10_2            1020
#define __MAC_10_3            1030
#define __MAC_10_4            1040
#define __MAC_10_5            1050
#define __MAC_10_6            1060
#define __MAC_10_7            1070
#define __MAC_10_8            1080
#define __MAC_10_9            1090
#define __MAC_10_10         101000
#define __MAC_10_10_2       101002
#define __MAC_10_10_3       101003
```

**Comment by kencu** [comment]
@ryandesign -- I know you're busy keeping everything afloat. Is there anything I can do with this to make your life any easier?

**Comment by ryandesign** [comment]
The changes seem reasonable. If the developers agree, let's merge it.

**Comment by kencu** [comment]
We await some upstream response then. Will let you know if / when I hear anything.

**Comment by pmetzger** [comment]
Are we close to being able to merge this?

**Comment by kencu** [comment]
I'll leave this with you and Ryan now, Perry. Close it or merge it as you prefer, if it goes on for too long without an upstream response.

**Comment by pmetzger** [comment]
@kencu am I correct in saying based on the patch this only impacts <10.7?

**Comment by kencu** [comment]
Impacts only < 10.7, yes.

**Comment by pmetzger** [comment]
Merged then. Thanks, @kencu.

**Pull request merged**
