### PR TITLE
cppman: update version 0.4.8->0.4.9 & use Python 3.7

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.14
Xcode 10.0

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
The commit message should mention the switch to python 3.7.

**Comment by pmetzger** [comment]
LGTM.

**Comment by MarcusCalhoun-Lopez** [comment]
As requested by @mf2k, I have updated the commit message.

**Comment by pmetzger** [comment]
Merged. Thanks as always, @MarcusCalhoun-Lopez!

**Pull request merged**
