### PR TITLE
perl5: update to 5.24.2

### PR DESCRIPTION
**Pull request by l2dy**
###### Tested on
macOS 10.12
Xcode 8.3.3

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

- [x] checked your Portfile with `port lint`?
`Warning: Variant perl5_24 conflicts with non-existing variant`
- [x] tried existing tests with `sudo port test`?
```
dist/Time-HiRes/t/clock ....................................... Time::HiRes::clock_nanosleep(): unimplemented in this platform at t/clock.t line 74.
# Looks like you planned 5 tests but ran 3.
# Looks like your test exited with 60 just after 3.
FAILED--expected 5 tests, saw 3
...
Failed 1 test out of 2319, 99.96% okay.
	../dist/Time-HiRes/t/clock.t
```
- [x] tried a full install with `sudo port -vs install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mojca** [comment]
OK from my point of view, perhaps we should check the failing test (I cannot install Sierra). Is it also failing with old/existing version?

**Comment by l2dy** [comment]
Sorry for the late reply, power and network outage in school.

Same error in `perl5.24 @5.24.1_0`.
```
dist/Time-HiRes/t/clock ....................................... Time::HiRes::clock_nanosleep(): unimplemented in this platform at t/clock.t line 74.
# Looks like you planned 5 tests but ran 3.
# Looks like your test exited with 60 just after 3.
FAILED--expected 5 tests, saw 3
...
Failed 1 test out of 2318, 99.96% okay.
	../dist/Time-HiRes/t/clock.t
```

**Comment by danielluke** [comment]
I imagine replacing the Time::HiRes patch with https://perl5.git.perl.org/perl.git/commitdiff/c4a535af41823cc84534bf8dbecfdcc3eb7daa86 will fix it.

**Comment by l2dy** [comment]
@mojca Should I test that patch?

**Comment by mojca** [comment]
Please do. My hardware is too old for Sierra.

What I don't understand is why this patch didn't make it to the current release (I admit that I didn't actually check) if it's been committed more than a year ago. If we find a fix fast, fine (even though it's pretty big), else just upgrading should work equally well.

**Comment by l2dy** [comment]
`All tests successful.` with patch.

**Comment by mojca** [comment]
Oh, wait, so this is only for perl 5.24, while it's fixed on 5.26? I took me a while to figure out it's just the old version that's broken, sorry. There's only one remaining question then. Does tha patch break ABI compatibility? I don't know how to check that other than running a whole lot of software that links against dylibs and wait for a crash. Or ask on IRC. If it does, we should probably ignore this for now, then bump all software to 5.26 and only potentially patch it afterwards. If it doesn't, we could patch it together with upgrade rather than revbumping it later. Perhaps limiting the patch to Sierra and above for now.

Then again, I don't remember any serious complaints from any MacPorts user due to this problem. So I wonder if we should really worry about it :) or simply revbump and be done with it, given that we should switch to 5.26 very soon anyway.

I don't care that much. I would be fine with either solution. It's just nice to include a reference to the patch that fixes the failed test in case we don't patch it ourselves.

**Comment by danielluke** [comment]
I haven't reviewed both patches, but IIRC the current macports patch already includes the changes to Time::HiRes, the patch I posted just also includes changes that fix the test case (but we should probably review them both to verify).

**Comment by l2dy** [comment]
I didn't check if it's fixed in 5.26. No idea about ABI compatibility too. I'll add references to this PR and the patch to the diff file.

Should we ignore this for now or not?

**Comment by danielluke** [comment]
perl 5.26 builds without any patches - so upstream at least incorporated some Time::HiRes fix (presumably the one linked above or a later version of the Time::HiRes module).

**Comment by mojca** [comment]
I wanted to commit this now, then I ran `destroot` followed by `test` and ran into:
```
error: unable to open output file 'perlmain.o': 'Error opening output file 'perlmain.o''
1 error generated.
make: *** [perlmain.o] Error 1
```
I guess that's unrelated to the patch anyway, but: does destroot actually remove some files?

**Comment by l2dy** [comment]
Run `port test` after `port -k install` would fail too.

**Comment by mojca** [comment]
They say that the patches will make it into perl5.24.3

https://rt.perl.org/Public/Bug/Display.html?id=128427

**Pull request merged**
