### PR TITLE
tor: update to 0.4.6.8

### PR DESCRIPTION
**Pull request by Knapoc**
#### Description

updates tor to 0.4.6.8
###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.0.1 21A559 x86_64
Xcode 13.1 13A1030d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
@Knapoc could you resolve the conflict and force push?

**Comment by Knapoc** [comment]
@pmetzger sure but I don't know whether it's wanted. Maybe @reneeotten had some other aspects in mind when updating the port

**Comment by pmetzger** [comment]
I think it was just a patch added for the new OpenSSL. There is no reason for you not to fix the conflicts and push.

**Comment by pmetzger** [comment]
Your push removes the OpenSSL 3 stuff. Is that what you meant to do?

**Comment by Knapoc** [comment]
Yup that was intended. The OpenSSL 3 patch was [merged upstream](https://gitlab.torproject.org/tpo/core/tor/-/merge_requests/390/#d93aeab458142a0111a5b258bd66a6f01c166fbd) a while ago. Locally the tests ran fine, no build errors and I also made sure that the connecting to the tor network/proxy was successful.

**Comment by reneeotten** [comment]
@Knapoc @pmetzger oh sorry, I clearly mistyped the version number when trying to update the port and fix [Trac ticket 63856](https://trac.macports.org/ticket/63856). With that version I updated the port to the patch I added was needed, but I see that in the latest upstream version it is indeed working as it should.

**Pull request merged**
