### PR TITLE
lsh: fix a broken port

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

The port currently is broken across the board: https://ports.macports.org/port/lsh/details
Fix it.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

macOS 14.5
Xcode 15.4

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Wait with this. First version (no autotools) built on ppc, but failed on arm64. This one builds on arm64 but fails on ppc.
I need both working.

**Comment by barracuda156** [comment]
Should work now.

**Comment by ryandesign** [comment]
I hope you've reported these issues to the developers.

**Comment by pmetzger** [comment]
Looks okay, but I really don't understand why anyone would want a broken unmaintained SSH implementation that is doubtless horribly insecure. Why don't we just remove the thing?

**Comment by barracuda156** [comment]
@pmetzger The problem here was unrelated to security, it is essentially a build system. We have seen horrible build systems with many ports, including actively maintained ones. (NodeJS, for example.)

**Comment by pmetzger** [comment]
This is not a build system, it is an ssh implementation. It's an ancient, unmaintained ssh implementation that probably is filled with security holes. Why do we want it around instead of removed?

**Comment by barracuda156** [comment]
@pmetzger I am not in favor of throwing stuff out, unless it is known to be unusable (indeed, we do not need any ICQ ports when ICQ service is shut down, for example) or hopelessly broken. I am regularly facing issues because someone else thrown a port out which happens to be needed or desirable for another system. And I do not want to be a potential cause for someone’s frustration myself.

Perhaps it could have been removed earlier, if it was so much desirable?

I leave it at this. If anyone wishes to remove the port, it can be done either after merging the PR at an arbitrary point of time or right away, together with closing the PR.

**Comment by barracuda156** [comment]
On a side note, maybe it is too early to bury ICQ clients: https://nina.chat

**Comment by pmetzger** [comment]
I am absolutely, positively in favor of making sure that we provide software that's as secure as possible for the end user, and OpenSSH is a superior alternative in literally every respect. I'm not even sure what inspired you to make this work. How did you encounter it?

**Comment by pmetzger** [comment]
BTW, we tossed all the ICQ ports already.

**Comment by pmetzger** [comment]
I have removed the underlying port. In the future, before putting work into fixing something, one should first ask if there's any point in having the thing available in the first place. If the answer is a clear "we should not be providing this", then time spent on it is counterproductive.

**Comment by pmetzger** [comment]
Also, in general, there are a vast number of ports, and sometimes we don't notice that something is unmaintained, broken, and hopelessly obsolete, but that does not mean that it is worth fixing on the basis that if it was worth removing someone else would have removed it. There are only so many of us working on MacPorts and we can miss things.

**Pull request closed without merging**
