### PR TITLE
cargo_fetch PG: replace with rust PG

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
The rust PG is more closely tied to the current build of Rust.

Fixes https://trac.macports.org/ticket/65195
Fixes https://trac.macports.org/ticket/65025

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.3.1 21E258 x86_64
Command Line Tools 13.3.1.0.1.1648687083

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mascguy — APPROVED** [review]
Tested building all of these locally, and LGTM.

Anyone else?

**Comment by herbygillot** [comment]
lgtm.

**Comment by mascguy** [comment]
It looks like we're past the 72-hour threshold, and this is also fixes broken port `mesalink`. So promptly merging would be good.

Does anyone have any final thoughts/concerns? @danchr , @raimue , @Raimondi ?

**Comment by mascguy** [comment]
Thanks as always Marcus!

**Pull request merged**
