### PR TITLE
libflame: new port in math

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

This is an initial support for LAPACK-like library for `blis` (which currently has no lapack).
At the moment I just add the port, but do not use it anywhere.

@catap Kirill, I add you as a maintainer, since you are a maintainer of `blis`, and this is supposed to be its lapack.
(If you prefer not to be involved here, please let me know.)

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.4
Xcode 15.3

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@herbygillot May I ask you to merge this one please?

**Comment by barracuda156** [comment]
@catap Could you please chime in?

**Comment by kencu** [comment]
Is your plan to have all builds on older systems you control use python3.11 until and unless someone fixes python3.12 for 10.6-PPC?

**Comment by barracuda156** [comment]
@kencu This is a counterpart of `blis`, is should use the same version of Python. (Notice, Python 3.11 is not used for any newer macOS.)

P. S. Python 3.12 works fine, I just need a fix that Python upstream can accept, for reasons you well know.

**Comment by catap** [comment]
Im not active here on the moment but O don’t mind

**Comment by barracuda156** [comment]
@herbygillot So Kirill is fine with this, though apparently won’t actively take part for the time being.
Let’s have this port in sync with `blis` anyway.

**Pull request merged**
