### PR TITLE
postgresql81, pg2xbase: delete ports

### PR DESCRIPTION
**Pull request by chrstphrchvz**
postgresql81: EOL was almost 13 years ago.
See: https://trac.macports.org/ticket/58630

Remove variants of dependents without deprecating first: for over 4 years, they have been unusable due to postgresql81 failing to build.

pg2xbase: Upstream gone since 2008. No dependents. Not offered by other package managers.
Closes: https://trac.macports.org/ticket/38840

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
If #20653 gets merged first, I can then push 14b37392ba1 to resolve conflicts in this PR.

**Comment by pmetzger** [comment]
@chrstphrchvz Can you resolve the conflicts please?

**Comment by chrstphrchvz** [comment]
> @chrstphrchvz Can you resolve the conflicts please?

Done

**Comment by pmetzger** [comment]
Done! Thanks for the cleanup!

**Pull request merged**
