### PR TITLE
WIP ShellCheck: update to 0.6.0

### PR DESCRIPTION
**Pull request by sirn**
#### Description

This PR update ShellCheck to 0.6.0 and upgrade/introduce a new port of all dependencies required to get it running. ShellCheck has since switched from `hs-json` to `hs-aeson`, and even though [ShellCheck dependencies](https://hackage.haskell.org/package/ShellCheck-0.6.0/dependencies) says any version of `aeson` is fine, it actually requires a newer version of `aeson` (thus existing `hs-aeson` does not work). 

So instead of updating `hs-aeson`, which may break other packages in process, I decided to create `hs-aeson-devel` and add new port for its dependencies, using `-devel` suffix in its name (if the package already exists). Some `-devel` package can be link against the existing `hs-hashable` in MacPorts, but `hs-aeson-devel` require `hashable >=1.2.7.0`, so I have to link its dependencies with `hs-hashable-devel` because otherwise `hs-aeson` will fail to build (due to deriving error with `Hashable Text`).

I tried to keep the dependencies tree clean by following few rules:

* Any dependencies of `hs-aeson-devel` are linked against `hs-hashable-devel`
* Any `-devel` packages are linked against `-devel` packages instead of haskell-platform
* Any non-`-devel` packages are linked against packages in haskell-platforms if possible

Please consider this PR as a **WIP**, as I believe it require a lot more work to be done before it can be merged, but I need feedback from existing maintainers, so I'm sorry for opening a WIP PR.

Thanks!

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15 19A471t
Xcode 11.0 11M336w

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

I used `sudo port -vs install` to install because I cannot enable tracing on GHC possibly because I'm running a beta software (sorry about this); the process simply hangs and require kill -9 to exit.

### CODE REVIEW

**Comment by pmetzger** [comment]
@cjones051073 Are you shepherding this?

**Comment by sirn** [comment]
Heads-up, my Mac is currently dead so I can’t work on this for a week, but please do leave comment! Thanks!

**Comment by neverpanic** [comment]
Sorry for not seeing this any earlier – there is currently some work going on to get Haskell modernized based on stack, see #4794, #5049, #4633 and as an example port update, #4698.

We may eventually go down the stack-based route, since it's just much easier to package the binaries we want without worrying about all the different library dependencies.

Cc: @essandess.

**Comment by sirn** [comment]
Makes sense, I actually prefer stack-based installations than manually managing dependencies (of which I have no idea what to do with the `-devel` packages once MacPorts updated GHC :-) I may find some time to port ShellCheck to stack-based build once the relevant PRs are merged.

**Comment by essandess** [comment]
>  I may find some time to port ShellCheck to stack-based build once the relevant PRs are merged.

@sirn It’s pretty fast and simple. Here are a couple examples:
* https://github.com/macports/macports-ports/pull/4698
* https://github.com/macports/macports-ports/pull/4632

**Comment by essandess** [comment]
@sirn BTW, it would be helpful if you looked at those Portfile examples with a critical eye. Specifically, I haven’t fully checked if those `.env` settings are actually used or necessary (MacPorts tcl is opaque in this way). And I haven’t tried to get a working build with MacPorts `gcc`. Though that should work, running it out-of-the-box breaks stack builds, so I explicitly set the macOS native `gcc`.

Please post any corrections you feel are necessary, or a way to use MacPorts compilers if you get a chance to figure that one out.

**Comment by sirn** [comment]
@essandess I'll take a look and will try to port this to stack-based Portfile during the weekend. Thanks!

**Comment by essandess** [comment]
@sirn Also, take a critical look at the binary that stack produces. stack doesn’t really do `DESTDIR` or `PREFIX`. Often it works anyway. If not, some hackiness will be required.

**Comment by neverpanic** [comment]
Right, I should have checked before, but shellcheck was just updated to 0.7.0 in https://github.com/macports/macports-ports/pull/5142.

**Pull request closed without merging**
