### PR TITLE
Ocaml update

### PR DESCRIPTION
**Pull request by pmetzger**
#### Description

Update a number of OCaml infrastructure ports, and one OCaml using port (Coq), and take ownership of the same.

This will possibly break some other OCaml using software. I'm committed to fixing such breaks quickly.

Closes: https://trac.macports.org/ticket/55358

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.1 17B48
Xcode 9.1 9B55

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mojca** [comment]
Without actually testing any of the functionality, the updates and commits generally look ok to me. I hope that some other OCaml addict will take a look.

My question is: do any other ports need a revbump? With other words: will other ports (excluding those that might break due to incompatible version of ocaml) fail to work until being rebuilt? Example: if `libpng` gets updated in an ABI-incopatible way, all binaries that link against that library need to be rebuilt. In case of scripting languages (python and perl modules which don't link against `libperl.dylib` for example), a rebuild is not needed. I have no clue how exactly OCaml works, but you might know the answer to that question already.

To answer your question from the mailing list: you did exactly the right thing with commit messages. Generally, even if you didn't know how to tweak git, some other developer could split or combine the commits for you. It is generally faster if the patch author does it that if the reviewer needs to fix the issues, but not doing it should not be a reason for being afraid to open a PR. (And there's no need to open a new Trac ticket if you already have a patch. You could have submitted some suboptimal patch as well and fix it later.)

**Comment by pmetzger** [comment]
On Sun, 19 Nov 2017 17:33:49 +0000 (UTC) Mojca Miklavec
<notifications@github.com> wrote:
> Without actually testing any of the functionality, the updates and
> commits generally look ok to me. I hope that some other OCaml
> addict will take a look.

I suspect I might be the only one now that mww is gone. :(

> My question is: do any other ports need a revbump? With other
> words: will other ports (excluding those that might break due to
> incompatible version of ocaml) fail to work until being rebuilt?
> Example: if `libpng` gets updated in an ABI-incopatible way, all
> binaries that link against that library need to be rebuilt. In case
> of scripting languages (python and perl modules which don't link
> against `libperl.dylib` for example), a rebuild is not needed. I
> have no clue how exactly OCaml works, but you might know the answer
> to that question already.

So we've updated the compiler but not any libraries, so that shouldn't
be necessary. I _do_ strongly guess that other things will break --
some ports will probably need to explicitly add ocaml-ocamlbuild as a
dependency now that ocamlbuild has been unbundled from the compiler,
and there will probably be other sorts of breakage. I'll fix those as
they show up.

> To answer your question from the mailing list: you did exactly the
> right thing with commit messages.

Cool. I'll try to stick to this format going forward in the future.

> Generally, even if you didn't know how to tweak git, some other
> developer could split or combine the commits for you.

Cool. My original commits before I rebased and altered things to do
one commit per portfile with a clear explanation, it was kind of
messy, so I was hoping to save others time by doing this.

> It is generally faster if the patch author
> does it that if the reviewer needs to fix the issues, but not doing
> it should not be a reason for being afraid to open a PR. (And
> there's no need to open a new Trac ticket if you already have a
> patch. You could have submitted some suboptimal patch as well and
> fix it later.)

Thank you! And thank you for reviewing!

Perry
-- 
Perry E. Metzger		perry@piermont.com

**Comment by mojca** [comment]
I CC-ed some maintainers in the ticket. Let's give it a few days and if nobody complains ...

**Comment by pmetzger** [comment]
Sounds good. I suspect there may not be a failure seen in any of the other ports until people try doing a build of all the dependent ports with the patches in place, but they should have a chance to complain.

**Comment by pmetzger** [comment]
BTW, in an upcoming step, I'm going to move all the ocaml- ports in devel/ into a new ocaml/ category. There are a lot of them, so it seems worth it.

**Comment by mojca** [comment]
> I suspect there may not be a failure seen in any of the other ports until people try doing a build of all the dependent ports with the patches in place, but they should have a chance to complain.

Exactly.

**Comment by fhgwright** [comment]
Do WIP PRs get Travis runs?  If so, here's something that *might* work to test the dependents:

1) Create a new branch, say 'ocaml-test', derived from 'ocaml-update'.

2) Add a commit which revbumps all dependent ports.

3) Submit a WIP PR for the test branch.

4) Look at the Travis results when available.

5) Close the PR (unmerged, of course).


BTW, is it still necessary to revbump dependents in some cases (aside from this testing), or is rev-upgrade expected to take care of that?

**Comment by mojca** [comment]
Travis doesn't know the concept of a "WIP" PR. It will build anything you feed it. The problem is that it will most like time out if you feed it too many ports, it only has 48 minutes to run.

For the sake of testing you could even add an additional commit to this PR that does just `git mv` of ports to a different subfolder, wait for results from Travis and then remove that commit again. But I'm pretty sure that Travis will time out. You already consumed 32 minutes for these ports which means that you only have 15 minutes left for the rest. I wouldn't worry about this as much, one can fix other ports later. If there was a high demand, there would be more people involved with these ports. The reason why I CCed some people was in the hope to get at least some feedback. But the only maintainer with slightly more ports doesn't even have a GitHub account, meaning that he didn't log into trac for at least a year.

The best way to test all other ports would be to prepare a list of potentially affected ports, merge this PR, wait for the buildbot to finish the job and then try to manually force a build of all those ports on the builder. Then you'll have a much better statistics to deal.

An alternative is to try to build those ports manually before committing this, but testing all > 100 ports at once sounds like a bit of a challenge.

**Comment by pmetzger** [comment]
> An alternative is to try to build those ports manually before committing this, but testing all > 100 ports at once sounds like a bit of a challenge.

It's close to 300 in fact. No way a Travis run has enough time for that.

I think I'm more comfortable just rapidly fixing them after this goes in. I bet a bunch of them are already broken and haven't been fixed, btw.

**Comment by pmetzger** [comment]
@mojca Looks like no OCaml port maintainers have commented at all. Can we pull up?

**Comment by mojca** [comment]
We usually give developers at least 3 days (72 hours) to respond.

Here are links to build logs to follow for any potential problems:
* [10.5](https://build.macports.org/builders/ports-10.5_ppc_legacy-watcher/builds/9926)
* [10.6/i386](https://build.macports.org/builders/ports-10.6_i386_legacy-watcher/builds/10741), [10.6/x86_64](https://build.macports.org/builders/ports-10.6_x86_64_legacy-watcher/builds/10715)
* [10.7](https://build.macports.org/builders/ports-10.7_x86_64_legacy-watcher/builds/10752)
* [10.8](https://build.macports.org/builders/ports-10.8_x86_64_legacy-watcher/builds/10713)
* [10.9](https://build.macports.org/builders/ports-10.9_x86_64-watcher/builds/10672)
* [10.10](https://build.macports.org/builders/ports-10.10_x86_64-watcher/builds/10666)
* [10.11](https://build.macports.org/builders/ports-10.11_x86_64-watcher/builds/10675)
* [10.12](https://build.macports.org/builders/ports-10.12_x86_64-watcher/builds/9610)
* [10.13](https://build.macports.org/builders/ports-10.13_x86_64-watcher/builds/1560)

If you plan to move the ports to a different folder, we could use that commit to (try to) rebuild everything on the buildbot and see which ports fail.

**Pull request merged**
