### PR TITLE
Update kmymoney4 to latest version.

### PR DESCRIPTION
**Pull request by sxntxn**
#### Description

This updates kmymoney4 and all dependencies to the latest versions.
This brings feature updates, such as PhotoTAN  and other PSD2 related issues support.

As this branch modifies multiple ports at once, I am not sure how to proceed from here. Please advise.

###### Tested on
macOS 10.15.5 19F101
Xcode 11.3.1 11C504

### CODE REVIEW

**Comment by NicosPavlov** [comment]
I am not sure to see the point of upgrading kmymoney4 to the latest git commit, when we already have kmymoney4-devel which follows the git repository. It would make more sense to just update the commit of the -devel and keep kmymoney4 on the stable release.

There are also multiple changes in the PR which are not related to the upgrade, such as deletion of comments and build instructions (such as build.asroot) which might have to be kept. You are also changing maintainers, which you should not do. 

Also, it seems to me that the two ports you are adding are actually new versions of ports that are already present in MacPorts. Is there a reason to create new ports instead of updating the existing ones?

**Comment by sxntxn** [comment]
> I am not sure to see the point of upgrading kmymoney4 to the latest git commit, when we already have kmymoney4-devel which follows the git repository. It would make more sense to just update the commit of the -devel and keep kmymoney4 on the stable release.

IMHO, it does not make much sense to keep the -devel port, as 4.8 is in maintenance mode. Disruptive changes are not expected (I discussed this with the maintainer via email).

> There are also multiple changes in the PR which are not related to the upgrade, such as deletion of comments and build instructions (such as build.asroot) which might have to be kept. You are also changing maintainers, which you should not do.

I forked this several years ago when kmymoney4 was without maintainer. I wasn't aware somebody picked up.

> Also, it seems to me that the two ports you are adding are actually new versions of ports that are already present in MacPorts. Is there a reason to create new ports instead of updating the existing ones?

Incompatible API. Updating would break other ports relying on the old versions.

**Comment by NicosPavlov** [comment]
So I tested the ports in the PR, and while there are some things that should be addressed in my opinion, the main problem is that kmymoney4 does not compile. 
The reason for that is that after they introduced gwenhywfar5 and aqbanking6, they reverted it later as there are some support problems (see commit 88e0a2cc5 in kmymoney's repo). In some way this confirms me in thinking that following the latest changes in the repo should be placed in the -devel port. I noticed that the port is presently broken as it links to a repository that is not used anymore, so that including your changes in that way would also fix that.

In any case, this implies that the new ports  gwenhywfar5 and aqbanking6 are not needed at this point to upgrade kmymoney4, so that I would rather treat them separately.

**Comment by sxntxn** [comment]
> So I tested the ports in the PR, and while there are some things that should be addressed in my opinion, the main problem is that kmymoney4 does not compile.

Works for me. Where does it fail?

> The reason for that is that after they introduced gwenhywfar5 and aqbanking6, they reverted it later as there are some support problems (see commit 88e0a2cc5 in kmymoney's repo).

That's not what this commit does.
88e0a2cc5 adds a configure-time multiplex for aqbanking5 and aqbanking6 ("aq" in the following). 
aq6 was not feature-complete in January, but aq5 was already discontinued. Some banks could be accessed with aq6 but not aq5 and vice-versa.
My bank is in the aq6-but-not-aq5 group, that's why I submitted 3bf1e5d82b8 and c5c2681a5b184 to kmymoney.
88e0a2cc5 was for users in the other group, to get online access to their bank. (I haven't followed the development for quite some time, but the most recent aq6 works like a charm -- for me.)

Adding a variant to build with either aq5 or aq6 would IMHO be a good way to address this. What do you think?

**Comment by NicosPavlov** [comment]
I see, sorry for the misunderstanding. In my case, it fails with the error:

CMake Error at /opt/local/lib/cmake/gwenhywfar-5.3/gwenhywfar-config.cmake:7 (message):
  File or directory /opt/local/lib/libgwenhywfar.so.79 referenced by variable
  GWENHYWFAR_LIBRARIES does not exist !

So that it cannot find gwenhywfar. I then noticed that the configuration file searches first for earlier version of gwewnhywfar and aqbanking, and when I tried with these, the build worked, so that I attributed the commits I reference to a revert. 

I agree that variants could make sense, but it starts to be quite some changes. How about first updating kmymoney4 to git latest commits, update libalkimia, and make kmymoney4-devel obsolete (as it is replaced with this one), and then later add the variants with the new ports?

**Comment by sxntxn** [comment]
IIRC there are some dependency changes to libalkimia (refactoring of online quote). 
So, my proposed approach would be:

1. update libalkimia
2. (remove kmymoney4-devel)
3. update kmymoney4 to latest git
4. (remove gwenhywfar4-devel and aqbanking5*-devel)
5. submit  gwenhywfar5
6. submit  aqbanking6
7. add "aqbanking6" variant to kmymoney4


What do you think?

**Comment by NicosPavlov** [comment]
Sounds like a good plan. I would say that this should be done in several steps. If you want to make the PRs, feel free to do so, but please make then based on the present versions of ports. If you prefer, I can make them. What I suggest is:

- (1-3) can make one clean PR. pixilla must be included as he is the maintainer of kmymoney4. I'll take maintainership of libalkimia as there is no maintainer for now (I assume you don't have commit rights on MacPorts). 
- As you hinted, removing gwenhywfar4-devel and aqbanking5-devel is somewhat of a separate issue. This should involve @drkp as he is the maintainer for these.
- (5-7) or (5-6) and then 7 can make clean PR(s) too.

**Comment by sxntxn** [comment]
Now that all dependencies are met, here's the "+aqbanking6" variant.

However, this currently fails to build: it seems CMAKE cannot find `libgwengui-cpp.dylib`. It fails in `kmymoney/plugins/kbanking/CMakeFiles/kmm_kbanking.dir/build.make` at the line:
  `lib/kmm_kbanking.so: gwenhywfar::gui-cpp-NOTFOUND`

I'll try my best to find a solution, but unfortunately I don't know much about CMAKE. Help would be appreciated.

**Comment by kencu** [comment]
One year, no movement. Please reopen this PR if you get it to a committable state!

**Pull request closed without merging**
