### PR TITLE
boost: Update to version 1.76.0

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.4 20F71 x86_64
Xcode 12.5 12E262

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Steve, this is covered by new port `boost176`.

**Comment by mascguy** [comment]
Also, use of boost by dependents is now simplified via new portgroup `boost`. See the comments in this PR for details:

https://github.com/macports/macports-ports/pull/11185

**Comment by essandess** [comment]
Great—thanks! But should port `boost` be obsoleted now?

**Comment by mascguy** [comment]
> Great—thanks! But shouldn't port `boost` be obsoleted now?

Not until we've migrated everything off it. But soon, hopefully

**Comment by mascguy** [comment]
More notable info: Now that we have segregated boost ports that can coexist side-by-side, we're in the process of refactoring those. Eliminating the copy-pasta between them is one of the goals, but we also plan to migrate from Python variants to subports. That work is still pending, but I'm hopping to tackle that within the next few weeks.

All of that work is covered by ticket:
[59834 - Boost: refactor and enhance](https://trac.macports.org/ticket/59834)

**Pull request closed without merging**
