### PR TITLE
libdeflate: new port

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -d install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by dankamongmen** [comment]
I just packaged libdeflate for fedora last week, and what you have looks pretty solid. The only thing I'd note is that position-independent code isn't being used by default; if MacPorts wants that enabled, I can help you turn it on. Otherwise, LGTM.

**Review by mascguy — APPROVED** [review]

**Comment by herbygillot** [comment]
Thanks @mascguy, @dankamongmen. To be honest, I'm not sure what MacPorts' policy is on position independent code. It does seem like a net benefit that should be fine to add, but I'm not sure about any tertiary impact. @ryandesign?

**Comment by ryandesign** [comment]
I thought PIC has always been the default on macOS. If this build system is going to great lengths to force non-PIC on macOS, then maybe they have a good reason to do that.

**Comment by kencu** [comment]
PIC is the default, but just for good measure, the Makefile turns it on anyway:

https://github.com/ebiggers/libdeflate/blob/0a2b40203db489551bcbd0fe914092c51da08986/Makefile#L118

**Comment by herbygillot** [comment]
OK nice, thank you for the clarifications @ryandesign, @kencu.

**Pull request merged**
