### PR TITLE
i2pd: update to 2.46.1

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with ~~`sudo port -vst install`~~ `sudo port -d install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@herbygillot LGTM. I think upstream would not have broken anything :) 

On a side note, do you have an idea how to fix building shared libs? I tried passing a standard CMake arg for that, tried explicitly setting a target, but the build fails badly at linking then.
According to upstream, with Makefiles it works correctly (not sure if on macOS though and when last time tested).

Not that we can’t live with a static lib, but would be nice to fix (and upstream it, of course).

**Comment by herbygillot** [comment]
> @herbygillot LGTM. I think upstream would not have broken anything :)
> 
> On a side note, do you have an idea how to fix building shared libs? I tried passing a standard CMake arg for that, tried explicitly setting a target, but the build fails badly at linking then. According to upstream, with Makefiles it works correctly (not sure if on macOS though and when last time tested).
> 
> Not that we can’t live with a static lib, but would be nice to fix (and upstream it, of course).
> 
> Ticket here: [PurpleI2P/i2pd#1860](https://github.com/PurpleI2P/i2pd/issues/1860)

I think I'll just shoot to only update `i2pd` for now - I created a separate ticket in Trac to track the shared libs issue: https://trac.macports.org/ticket/66965

**Comment by barracuda156** [comment]
@herbygillot Sure, there is no urgency with shared lib thing. Thank you for an update!

**Comment by barracuda156** [comment]
@herbygillot Dunno why, I am getting a different checksum:
```
checksums           rmd160  aa83c76392940fb2e03983a5f63b97020bdd11dc \
                    sha256  af0b710d867981228b7034962d85d7e785b6adb178a8f6ae978e26f4fa9e748c \
                    size    644845
```

**Comment by herbygillot** [comment]
> @herbygillot Dunno why, I am getting a different checksum:
> 
> ```
> checksums           rmd160  aa83c76392940fb2e03983a5f63b97020bdd11dc \
>                     sha256  af0b710d867981228b7034962d85d7e785b6adb178a8f6ae978e26f4fa9e748c \
>                     size    644845
> ```

Can you do a `sudo port clean -f --all i2pd`? Looks like it works for me, and all buildbots seemed to build it successfully.

**Comment by barracuda156** [comment]
@herbygillot Same thing. Yes, I understand it is likely a local problem, just wondering what goes wrong. Other ports checksums are all fine, whatever I build today.

**Pull request merged**
