### PR TITLE
nco: update to 4.7.9 and netcdf-fortran: update to 4.4.5

### PR DESCRIPTION
**Pull request by thiagoveloso**
I am proposing again to update nco to v.4.7.9, because 4.7.7 breaks with netCDF-C 4.6.2 (see https://github.com/nco/nco/issues/108).

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.4
Xcode 10.1

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by cjones051073** [comment]
This pr has conflicts that need resolving. @thiagoveloso please can you take a look and address them ?

**Comment by cjones051073** [comment]
B.t.w. I suspect part of your problems here stem from the fact you used the master branch of your fork as the branch foe this PR. This is normally a bad idea, as it can easily lead to issues such as these. You should instead create a new feature branch for each PR you wish to commit, branched from a clean master branch.

**Comment by cjones051073** [comment]
Also, please squash the commits in this PR, so there is only one per port with all the required updates to that port.

**Comment by cjones051073** [comment]
OK, looking at the diffs this PR now actually has w.r.t. origin master, it is just to update netcdf-fortran to 4.4.5. I propose I close this PR, and make this change independently myself, as I suspect you are going to have issues cleaning this up given what you have done to the history in your master fork.

Many thanks for the update, but please in future bear in mind my suggestion to not use your master branch for feature PRs, but instead to follow standard practise and create a feature branch for each.

**Comment by thiagoveloso** [comment]
Thanks for the feedback @cjones051073, I agree it was the best thing to do in this case. I will definitely be more careful in my next contribution to macports.

**Comment by cjones051073** [comment]
No problem, glad I could help. Update is now commited to master.

**Pull request closed without merging**
