### PR TITLE
mysql8: change ssl flag to system vs copy for libcrypto and openssl

### PR DESCRIPTION
**Pull request by jhoyt4**
#### Description
  mysql8 has two mechanisms for linking to openssl libraries, system
  and copy/update.  Per the mysql8 devs the "system" method is
  perferred and the one they use internally.  To implement it,
  -DWITH_SSL must be set to "system"  and -DCMAKE_PREFIX_PATH should be
  set to the open ssl lib path to aide cmake in finding the preferred
  version of openssl.

  Previously, the copy and update mehtod was used due to setting the
  following flags via the openssl portgroup
    -DOPENSSL_ROOT_DIR=[openssl::install_area],
    -DOPENSSL_INCLUDE_DIR=[openssl::include_dir]
    -DWITH_SSL=[openssl::install_area]
  All three must be removed from the configure process to prevent the
  copy/paste

This PR should make maintenance slightly easier than the hacked up cmake files I previously requested be committed.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.5 23F79 arm64
Xcode 15.4 15F31d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by jhoyt4** [comment]
@herbygillot - This rolls back the cmake files I hacked up in the last commit.  Per the mysql8 devs, this is their perferred method.  They were resistant to getting the cmake files non-homebrew hard coded.

**Comment by jhoyt4** [comment]
That last force push was to move the SSL configure-args.delete to the proper pre-configure stage per @ryandesign's suggestion on the mailing list.

**Comment by barracuda156** [comment]
@jhoyt4 How is it gonna find MacPorts openssl3 installation without PG flags?

**Comment by jhoyt4** [comment]
@barracuda156 - These two flags point it to the macports open ssl dylibs:
  -DCMAKE_PREFIX_PATH=[openssl::install_area]
  -DWITH_SSL=system 

This is how mysql8 handles this in house with non-system openssl dylibs.

**Comment by jhoyt4** [comment]
From the test build on my system:

 % otool -L /opt/local/lib/mysql8/mysql/libmysqlclient.dylib 
/opt/local/lib/mysql8/mysql/libmysqlclient.dylib:
	/opt/local/lib/mysql8/mysql/libmysqlclient.24.dylib (compatibility version 24.0.0, current version 24.0.0)
	/opt/local/libexec/openssl3/lib/libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	/opt/local/libexec/openssl3/lib/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.3.1)
	/opt/local/lib/libzstd.1.dylib (compatibility version 1.0.0, current version 1.5.6)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1700.255.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.100.2)

**Comment by jhoyt4** [comment]
Per the bug thread with mysql8 devs, the "system" trick may be used for other libs
https://bugs.mysql.com/bug.php?id=115421

**Comment by herbygillot** [comment]
Thank you for your efforts here, @jhoyt4.

**Pull request merged**
