### PR TITLE
Add `+spice` variant to qemu, and fix build for `spice-server`

### PR DESCRIPTION
**Pull request by furkanmustafa**
#### Description

First contribution here.

Qemu port had no option to enable spice support. When I tried enabling it simply, I have found out that `spice-server` port was failing to build as well.

This PR does;
* Add `+spice` variant to qemu, requiring `spice-protocol` and `spice-server` ports
* Fix build for `spice-server` port

Any additional test, check, guidance is welcome :pray:

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### ~~Tested~~ WIP! STILL TESTING on

macOS 12.5 21G72 x86_64
Xcode 13.3.1 13E500a

Python 3.10

###### Test TODO / Issues

* [x] Compiles and installs fine
* [x] Libvirt invocation ( reportedly working, [tested by](https://github.com/macports/macports-ports/pull/15723#issuecomment-1215676878) @brad-x )
* [x] Direct qemu invocation ( reportedly working, [tested by](https://github.com/macports/macports-ports/pull/15723#issuecomment-1215676878) @brad-x )
* [ ] Python 3.8 / 3.10 issue
  * I have 3.10 installed as well, but even though I set 3.8 as default, the build scripts used python3.10 for some reason.. had to install python packages for that version as well)
  * ~~(It is probably just fine)~~
    * [CI says it isn't fine](https://github.com/macports/macports-ports/pull/15723#issuecomment-1226704058)
* [ ] ~~Consider testing & including `spice-protocol` and `spice-server` version updates as well~~
  * It is apparently working fine with current versions, version updates could be left for another PR I guess?

###### Verification

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] ~~squashed and [minimized your commits](https://guide.macports.org/#project.github)?~~ probably not necessary, no non-significant commits.
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files? => almost

[skip notification]

### CODE REVIEW

**Comment by brad-x** [comment]
Can confirm libvirt and direct invocation with QXL graphics and connection via a SPICE client is functional

**Comment by furkanmustafa** [comment]
@brad-x thanks for the test! did the spice-server port work just as in this branch? (python3.8)

if so, then python3.10 issue is probably due to my local setup somehow, and we can clear that out as well.

also for qemu/libvirt, if you have basic invocation commands/xml that you have used for testing SPICE, sharing them here would be nice as well. :pray:

**Comment by furkanmustafa** [comment]
Hmm.. looks like the CI is [having](https://github.com/macports/macports-ports/runs/8004916966) the same python version problem as I did. It cannot find python module `six`..

dependencies declare python 3.8 and modules for that version, but if the system has some other python version, installing a python module for 3.8 doesn't work.

It worked for me when I switched dependencies as follows;

```diff
-    port:python38 port:py38-six port:py38-parsing
+    port:python310 port:py310-six port:py310-parsing
```
But it doesn't make sense to adapt this to everyone's own setup, or get into race with py311 py95 py98 ..

I have no idea how to fix this (and it's an issue before this PR). Any suggestions?

**Comment by mascguy** [comment]
Sorry for the delayed response on this! I'll try to take a look today, if possible.

**Comment by mascguy** [comment]
@furkanmustafa Furkan, can you please enable option "Allow edits and access to secrets by maintainers" for this PR? I need to push some minor cleanup, and cannot do so until you enable that.

p.s. FYI, it's safe to keep that option enabled, and that's why it's on by default: Only trusted members of our organization can push to your branch.

**Comment by mascguy** [comment]
It may be at the bottom of the page, below the comment section.

**Comment by furkanmustafa** [comment]
Ok, that's a github issue apparently;
* https://github.com/community/community/discussions/9921
* https://github.com/orgs/community/discussions/5634

As a workaround, I could add you to my forked project as a collaborator maybe, if that's OK?

**Comment by mascguy** [comment]
> As a workaround, I could add you to my forked project as a collaborator maybe, if that's OK?

Sure, that works!

**Comment by mascguy** [comment]
Changes pushed.

The only one of consequence, is rebasing against master. Otherwise, I just made some minor tweaks to your commit message formatting.

**Review by mascguy — APPROVED** [review]
All good now, will merge once Ci completes.

And thank you so much for your contribution Furkan!

**Comment by furkanmustafa** [comment]
Thank you!

**Comment by mascguy** [comment]
> > Hmm.. looks like the CI is [having](https://github.com/macports/macports-ports/runs/8004916966) the same python version problem as I did. It cannot find python module `six`.
> >
> > It worked for me when I switched dependencies as follows;
> > ```
> > port:python310 port:py310-six port:py310-parsing
> > ```
> 
> Ah, missed this earlier, I'll take a look. More to follow.

We've migrated everything to Python 3.10 where possible, and it makes sense to do so here as well. (And just did so, via the latest commits.)

Assuming there aren't any issues with that...?

**Review by mascguy — APPROVED** [review]

**Pull request merged**
