### PR TITLE
pd-faust: update to 0.15

### PR DESCRIPTION
**Pull request by agraef**
#### Description

Update to latest release (now hosted on Github, so I adjusted the Portfile accordingly).

###### Tested on
macOS 10.12.6 16G1212
Xcode 9.2 9C40b

### CODE REVIEW

**Comment by agraef** [comment]
Fixed up as discussed in #1260. Should be good to go now. Similarly fixed companion updates of faust2pd and pure-faust are in #1272 and #1273, it would be good if these could all be merged at the same time.

**Comment by pmetzger** [comment]
I'll merge now. That said, @agraef, I recommend doing a PR some time soon to fix your entry in the maintainer line. It should read 

`maintainers                     ryandesign {@agraef gmail.com:aggraef}`

or even better

`maintainers                     ryandesign {@agraef gmail.com:aggraef} openmaintainer`

if you are okay with third parties doing fixes. It would be good to fix the other two ports as well (and to whatever else you maintain.)

**Comment by agraef** [comment]
@pmetzger thanks, I'll do as you suggested. Is it ok if I update all those maintainer lines in one big bulk update, without bumping the revision numbers?

**Comment by pmetzger** [comment]
That should be fine. You don't need to bump revision numbers for a change like that. You only need to bump the revision if it has a material impact on the built package.

**Pull request merged**
