### PR TITLE
[WIP] wormhole-william: new port

### PR DESCRIPTION
**Pull request by jasperweiss**
#### Description

_wormhole-william is a go (golang) implementation of magic wormhole. It provides secure end-to-end encrypted file transfers between computers. The endpoints are connected using the same "wormhole code"._

_wormhole-william is compatible with the official python magic wormhole cli tool._

First attempt at a Portfile. I generated the portfile with [go2port](https://github.com/amake/go2port) but wasn't able to use `port lint`, `sudo port -vst install` or test it in general since I couldn't find the macports sources file under /etc/macports/sources.conf and add the local port. Some help would be appreciated.

Edit: I'm still trying to get this working but it would probably be better if I could troubleshoot this locally rather than waiting for automated tests to complete.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS macOS 10.15.7 19H2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jasperweiss** [comment]
Azure pipeline returns the following error:

`Fetching 'wormhole-william' ... [ERROR] maintainers: .`

**Comment by iefdev** [comment]
> Azure pipeline returns the following error:
>
> `Fetching 'wormhole-william' ... [ERROR] maintainers: .`

You could've kept: `maintainers         @jasperweiss openmaintainer`

But you need to add the email addr, somthing like:

`maintainers         {domain.tld:name @jasperweiss} openmaintainer`

_// If you don't want to use your own email addr, sign up for another one like, `jasperweiss.macports@disroot.org` or whatever service you'd prefer._

**Comment by jasperweiss** [comment]
> But you need to add the email addr, somthing like:

Are you sure? there seem to be plenty of Portfiles without email addresses. Or is that a new requirement for new ports?

**Comment by iefdev** [comment]
> Are you sure? there seem to be plenty of Portfiles without email addresses.

Yes, there are a lot of port written the way you just did, with `{jasper @jasperweiss}`. No email, and just a name = you email adress is `jasper@macports.org`. If it's not - add the mail like: `domian.tld:jasper` - which equals to `jasper@domain.tld`.

https://guide.macports.org/#reference.keywords.maintainers

**Comment by jasperweiss** [comment]
> Yes, there are a lot of port written the way you just did, with {jasper @jasperweiss}. No email, and just a name = you email adress is jasper@macports.org. If it's not - add the mail like: domian.tld:jasper - which equals to jasper@domain.tld

Ah, I figured since it says "The maintainers keyword lists the maintainers' GitHub usernames **or** email addresses" the email address isn't mandatory. I'll make set up an email address then.

**Comment by jasperweiss** [comment]
@iefdev I'm not sure what the problem is at this point. It's set to `maintainers {@jasperweiss protonmail.com:ecgmgg} openmaintainer`. Shouldn't that be fine?

**Comment by jasperweiss** [comment]
Closing the pull request for now since I first need to figure out how to test locally.

**Pull request closed without merging**
