### PR TITLE
dovecot2: Upgrade to v2.3.6 and major Portfile overhaul

### PR DESCRIPTION
**Pull request by essandess**
dovecot2: Upgrade to v2.3.6 and major Portfile overhaul

* Upgrade to dovecot 2.3.6
* Overhaul Portfile to use GitHub releases
* Remove deprecated source links
* Hardcode _dovecot:_dovenull default user and group
* Hardcode `last_valid_gid = 100` to avoid macOS [issue](https://www.systemcodegeeks.com/mac-os/macos-dovecot-setgroups-failed/)

###### Type(s)

- [x] bugfix
- [x] enhancement
- [x] security fix

###### Tested on

macOS 10.14.5 18F132
Xcode 10.2.1 10E1001

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by essandess** [comment]
May I please have some help with these Azure build tests? According to the logs that point to this paste file, https://paste.z0k.xyz/d7f5bab96d80, the failure is some wrong working directory thing for `./configure`:
```
Executing:  cd "/opt/local/var/macports/build/_Users_vsts_agent_2.150.3_work_1_s_mail_dovecot2/dovecot2/work/core-2.3.6" && ./configure --prefix=/opt/local --sysconfdir=/opt/local/etc --localstatedir=/opt/local/var --with-ssl=openssl --with-zlib --with-bzlib --with-ssldir=/opt/local/etc/openssl --with-shared-libs --with-pam 
DEBUG: system:  cd "/opt/local/var/macports/build/_Users_vsts_agent_2.150.3_work_1_s_mail_dovecot2/dovecot2/work/core-2.3.6" && ./configure --prefix=/opt/local --sysconfdir=/opt/local/etc --localstatedir=/opt/local/var --with-ssl=openssl --with-zlib --with-bzlib --with-ssldir=/opt/local/etc/openssl --with-shared-libs --with-pam 
sh: ./configure: No such file or directory
```

What I see on my box is a correctly working Portfile build, install, and deployed binary.

**Comment by mf2k** [comment]
I think it may have simply timed out.

**Comment by essandess** [comment]
@mf2k What’s the path forward? Kick it with a `commit  --amend --allow-empty --no-edit && push -f`? Haskell is monadically awesome, but `pandoc` installs a whole Haskell stack that takes forever in a docker container.

**Comment by mf2k** [comment]
I was hoping that someone who knows the buildbot system better would chime in.

**Comment by mf2k** [comment]
We can fix issues that may exist going forward.

**Comment by mf2k** [comment]
Thank you!

**Comment by reneeotten** [comment]
this failed all CI tests as a PR on Travis/Azure and now fails on all buildbots as well with the same error as mentioned above...

**Comment by mf2k** [comment]
I see the error now. Let's move this to the Trac ticket I created for it:

https://trac.macports.org/ticket/58544

**Comment by essandess** [comment]
Thanks all for addressing the missing build dependencies. FWIW, I've successfully built and installed this on multiple independent boxes and concur that all `depends_build` should need is `port:autoconf` and `port:wget` so that `./autogen.sh` will create a `./configure` file.

**Comment by essandess** [comment]
Comment: It might also be nice to add in the port notes for people behind proxies that installers must configure `${prefix}/local/wgetrc` to reach through their proxy:

```
https_proxy = http://proxy.example.com:8080/
http_proxy = http://proxy.example.com:8080/
use_proxy = on
```

**Pull request merged**
