### PR TITLE
go-1.4: attempt to add legacysupport for clock_gettime

### PR DESCRIPTION
**Pull request by herbygillot**
See: https://trac.macports.org/ticket/62337

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
@ci42, this port (`go-1.4`) is not set `openmaintainer`.  This PR attempts to address https://trac.macports.org/ticket/62337.

Any thoughts?

**Comment by kencu** [comment]
it's more complicated:

see https://trac.macports.org/ticket/58935 and many, many other go tickets

**Comment by herbygillot** [comment]
> it's more complicated:
> 
> see https://trac.macports.org/ticket/58935 and many, many other go tickets

OK, that looks pretty bleak.  Should I just close this PR and leave things be?

**Comment by herbygillot** [comment]
> there are people that are interested in making go work on older systems, but I think in fairness this one will take hands-on work to accomplish.
> 
> When I first came up with legacysupport back in 2016, named snowleopardfixes then, I had hopes it would be helpful; it's worked better than I ever dreamed, but some things, like go and rust and others, are quite tricky.
> 
> I'd say close this, yes.

`legacysupport` is definitely huge, so thank you for making it a thing, @kencu.

Closing this one.

**Pull request closed without merging**
