### PR TITLE
OpenBLAS,OpenBLAS-devel: Re-enable AVX2 support

### PR DESCRIPTION
**Pull request by cjones051073**
#### Description

Now that https://github.com/macports/macports-ports/pull/3486 is merged, it is no longer necessary to disable AVX2, as the cctools toolkit now supports it. This MR reenables it, on 'recent' OS versions.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.3 18D42
Xcode 10.1 10B61 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
Of course, avx512 works fine all the way back to 10.5 if the user has clang-7.0 installed. With the right llvm variants of cctools. But, I guess, ... compromises. I can change it on my own system.

Also, I kinda doubt that the `/usr/bin/clang` will support avx512 on anything older than about 10.10 or 10.12, but that remains to be seen.  It **think** it showed up about clang-3.9 or so, and that would be clang 900, more or less.

**Comment by kencu** [comment]
Oh, right. Thanks Chris -- I didn't notice that first time through.

**Comment by mojca** [comment]
There's something I'm confused about. Yes, you can always compile with AVX512 enabled (provided you have a compiler that's new enough), but doesn't the resulting binary crash if your processor doesn't support it? Also, if the processor doesn't support AVX2, the binary would also likely crash?

**Comment by cjones051073** [comment]
The current makefile based build system that is used already checks to see if the machine being built on supports avx2, and only qctually enables it if it does. So on my mac book pro which has tha se extensions, it is used, whilst on my older mac mini, which only supports avx, avx2 is corrctly not enabled. So there is no problem here.

**Comment by kencu** [comment]
If it does that, why are we having so much trouble with it?

**Comment by cjones051073** [comment]
Because the build system did not know that as from cctools could not previously handle the avx2 instructions. The issue was never with OpenBLAS incorrectly enabling AVX2 when not supported.

**Comment by kencu** [comment]
Ah -- took me a bit, I get it now. 

It runs some avx tests with clang. They pass, because clang uses it's integrated assembler. But openblas doesn't know we are going to use gcc to do the fortran stuff, and gcc fails.

So -- their avx testing will _never_ work for us, unless they throw in some fortran tests specifically. We'll always have to force it. I gotcha.

**Comment by cjones051073** [comment]
> Ah -- took me a bit, I get it now.
> 
> It runs some avx tests with clang. They pass, because clang uses it's integrated assembler. But openblas doesn't know we are going to use gcc to do the fortran stuff, and gcc fails.

No, not quite. We are currently using what looks like a basic makefile based build system, and this simple chcks the host cpu capabilities and if it detects the cpu supports avx2, enables it in the build. There is no checking via a compiler test, its purely based on whether or not the cpu has the specific silicon bits to support it or not.

> So -- their avx testing will _never_ work for us, unless they throw in some fortran tests specifically. We'll always have to force it. I gotcha.

In so far as the tests go, there is nohting specific to any language, c, c++ or fortran.

**Comment by NicosPavlov** [comment]
Indeed, as it is explicitly mentioned that cmake is considered experimental (see warning message in CMakeLists.txt), it not used by the Portfile at this point. Another thing is that I do not have an AVX512-capable processor myself, it is somewhat difficult to test what could be used.

Concerning AVX2, the changes seem pretty straightforward, thanks for posting them. 

For AVX512, the ticket describing the problem is still open: https://trac.macports.org/ticket/57912.

**Comment by michaelld** [comment]
I've been out sick & I'm just getting to MP issues from the weekend. Thanks for the PR @cjones051073 & for handling it @NicosPavlov ... LGTM BTW. I'll update openblas-devel soonish & see if that helps, too, since there's been at least 1 commit that -might- change AVX2 / AVX512 support testing.

**Pull request merged**
