### PR TITLE
kde-extra-cmake-modules: update to 5.29.0 + 3 new patches

### PR DESCRIPTION
**Pull request by mkae**
- upgrade to 5.30.0 rc2 (5.29.92)
- upstreamed app icon patch
- fixes an incompatibility with recent Qt5 PG changes

### CODE REVIEW

**Comment by mkae** [comment]
@RJVB, thanks for your submission of this update. (Sorry, I haven't yet fixed the authorship.)

I created this PR for you, because I saw another looming update in livecheck:
```
MVM7-4:kde-extra-cmake-modules marko$ port livecheck
kde-extra-cmake-modules seems to have been updated (port version: 5.29.0, new version: 5.29.1)
```
Did you test this? Perhaps the update then already incorporates a patch of this commit?

**Comment by mkae** [comment]
I fixed the authorship now.

**Comment by RJVB** [comment]
Actually, that's a livecheck glitch; only KPackage has had a point upgrade, not extra-cmake-modules.

**Comment by mkae** [comment]
OK, thanks for clearing that up. Thus this can be committed.

**Pull request closed without merging**
