### PR TITLE
Revert poetry v1.6.1 update

### PR DESCRIPTION
**Pull request by dgilman**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 13.5.1 22G90 x86_64
Command Line Tools 14.3.1.0.1.1683849156

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by catap** [comment]
David, you must also increase `epoch`

**Comment by jmroot** [comment]
I don't think there's any need to revert the whole thing, just restore py37-poetry-core at the old version.

**Comment by jmroot** [comment]
Like this:
```diff
diff --git a/python/py-poetry-core/Portfile b/python/py-poetry-core/Portfile
index 43fb01c8ad3..5321955dcc4 100644
--- a/python/py-poetry-core/Portfile
+++ b/python/py-poetry-core/Portfile
@@ -25,16 +25,25 @@ maintainers         {gmail.com:davidgilman1 @dgilman} openmaintainer
 
 homepage            https://github.com/python-poetry/poetry-core
 description         A PEP 517 build backend implementation developed for Poetry.
-long_description    ${description} This project is intended to be a light \
+long_description    {*}${description} This project is intended to be a light \
                     weight, fully compliant, self-contained package allowing PEP 517 \
                     compatible build frontends to build Poetry managed projects.
 
-python.versions     38 39 310 311
+python.versions     37 38 39 310 311
 python.pep517       yes
 # Bootstraps itself, no backend dependencies needed
 python.pep517_backend
 
 if {${name} ne ${subport}} {
+    if {${python.version} == 37} {
+        version     1.6.1
+        revision    0
+        distname    poetry_core-${version}
+        checksums   rmd160  1d3c7bfed575e4fb9424dc78b2f1c4524141aeb5 \
+                    sha256  0f9b0de39665f36d6594657e7d57b6f463cc10f30c28e6d1c3b9ff54c26c9ac3 \
+                    size    443618
+        depends_lib-append  port:py${python.version}-importlib-metadata
+    }
     post-destroot {
         set docdir ${prefix}/share/doc/${subport}
         xinstall -m 0644 -W ${worksrcpath} README.md LICENSE \
```
I can commit that if you like.

**Comment by dgilman** [comment]
Thank you, I was unable to make changes during the work day

**Pull request closed without merging**
