### PR TITLE
geany: update to 1.33, fixes

### PR DESCRIPTION
**Pull request by mojca**
* Update to version 1.33.
* Fix dependencies and make the +gtk3 variant default.
* Call the old default a gtk2 variant (just in case anyone still needs it).

See: https://trac.macports.org/ticket/57151
Closes: https://trac.macports.org/ticket/56124

#### Description

Update & bugfix as described in the ticket. VTE might need an update as well, but I leave it up to @dbevans.

@dbevans: is running `./autogen.sh` still needed? (It works without, but I'm not sure what the issue was.)

@majoc-at-astro: please test.

###### Type(s)

- [x] bugfix

###### Tested on

macOS 10.13.6 17G65
Xcode 9.4.1 9F2000 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM, but as it isn't openmaintainer we have to wait, sadly. A suggestion: you might email si-co.net:kiarash to ask what their github handle is and whether this can be made openmaintainer so that can be fixed at the same time.

**Comment by mojca** [comment]
Link to port abandoned ticket is linked above, I have no intention to separately ask for openmaintainer, at least not until the user responds.

Also, it would be cool if someone would actually test a bit and if we could get rid of `autogen.sh` which throws quite some warnings about some missing files.

**Comment by majoc-at-astro** [comment]
On Sat, Sep 22, 2018 at 05:07:13PM -0700, Mojca Miklavec wrote:

> @majoc-at-astro: please test.

Once it propagates to production, I'll let you know.

-- 
Dr Martin J Carter
Computer System Administrator
Astrophysics, University of Oxford

**Comment by pmetzger** [comment]
Merged. I suggest we count the port as abandoned soon, btw.

**Pull request merged**
