### PR TITLE
poac: remove port

### PR DESCRIPTION
**Pull request by ken-matsui**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
@ken-matsui can you elaborate on why you would like to remove this port?

**Comment by ken-matsui** [comment]
@reneeotten The main reason is that I do not have enough time to maintain this port. I wanted to remove myself as maintainer (https://github.com/macports/macports-ports/pull/17996), but the CI failed because of https://github.com/macports/macports-ports/pull/17773. If you can merge https://github.com/macports/macports-ports/pull/17996 or both, we do not need to remove this port.

**Comment by reneeotten** [comment]
> @reneeotten The main reason is that I do not have enough time to maintain this port. I wanted to remove myself as maintainer (#17996), but the CI failed because of #17773. If you can merge #17996 or both, we do not need to remove this port.

thanks @ken-matsui - I will just set the port then to "nomaintainer" and close this PR.

**Comment by ken-matsui** [comment]
@reneeotten thank you!

**Pull request closed without merging**
