### PR TITLE
haskell_cabal: Submission of portgroup, ports aeson-pretty, cpphs, hlint

### PR DESCRIPTION
**Pull request by essandess**
haskell_cabal: Submission of portgroup `haskell_cabal `, ports `aeson-pretty`, `cpphs`, `hlint`

* Submission of portgroup `haskell_cabal` for building cabal projects
* Submission of Haskell ports `aeson-pretty`, `cpphs`, `hlint`
* Remove `ihaskell` installation of these binaries

Related/parent: https://github.com/macports/macports-ports/pull/5272

cc @neverpanic @amake 

###### Type(s)

- [x] submission
- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G95
Xcode 10.3 10G8

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by essandess** [comment]
@cjones051073 @neverpanic I added this PR as a branch of https://github.com/macports/macports-ports/pull/5272, hoping that it would just affect the new files I added. But I see that it's swallowed https://github.com/macports/macports-ports/pull/5272 and this PR.

Please advise. If PR https://github.com/macports/macports-ports/pull/5272 is merged I can just delete this branch and add it again off of `master` (or ask @cjones051073 to do this with some magic git command), but I'm not sure how you wish to handle this.

**Comment by essandess** [comment]
@amake @neverpanic @mojca The `hlint` hackage package provides a `.cabal` file, not a `stack.yaml`, and  doesn’t successfully build using the default `stack init` In the `haskell_stack` portgroup. It does build successfully using MacPorts `cabal` and `ghc` with the attached portgroup `haskell_cabal` .

I expect that there are other hackage packages like this.

**Comment by essandess** [comment]
Ping. This is ready to merge.

**Comment by mf2k** [comment]
My only complaint is that each new port should have been in its own commit. But I won't let that hold up this PR.

**Pull request merged**
