### PR TITLE
glib2-upstream: new port for latest upstream release, to proactively support testing

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

New port `glib2-upstream`, covering the latest-and-greatest release of `glib2`. 

Includes updated patches, along with a fix for building 10.6 PPC. (Only applied in that specific case.)

###### Type(s)
- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.15.7
Xcode 12.4

macOS 10.6 PPC (10A190)
Xcode 3.2

macOS 10.5.8
Xcode 3.1.4

macOS 10.4.11
Xcode 2.5

### CODE REVIEW

**Comment by barracuda156** [comment]
@evanmiller Turns out `glib2` @2.72.1 fails to build on Tiger. Can we fix that?

```
[40/1087] /opt/local/bin/gcc-mp-7 -Iglib/libglib-2.0.0.dylib.p -Iglib -I../glib-2.72.1/glib -I. -I../glib-2.72.1 -I/opt/local/include -fdiagnostics-color=always -std=gnu99 -O2 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_ENABLE_DEBUG -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wunused -Wno-unused-parameter -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Wstrict-prototypes -Wno-bad-function-cast -Wno-declaration-after-statement -Werror=implicit-function-declaration -Werror=missing-prototypes -pipe -Os -fstrict-aliasing -Wno-deprecated-declarations -Wno-declaration-after-statement -arch ppc '-DG_LOG_DOMAIN="GLib"' -DGLIB_COMPILATION -fvisibility=hidden -MD -MQ glib/libglib-2.0.0.dylib.p/gmem.c.o -MF glib/libglib-2.0.0.dylib.p/gmem.c.o.d -o glib/libglib-2.0.0.dylib.p/gmem.c.o -c ../glib-2.72.1/glib/gmem.c
FAILED: glib/libglib-2.0.0.dylib.p/gmem.c.o 
/opt/local/bin/gcc-mp-7 -Iglib/libglib-2.0.0.dylib.p -Iglib -I../glib-2.72.1/glib -I. -I../glib-2.72.1 -I/opt/local/include -fdiagnostics-color=always -std=gnu99 -O2 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_ENABLE_DEBUG -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wunused -Wno-unused-parameter -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Wstrict-prototypes -Wno-bad-function-cast -Wno-declaration-after-statement -Werror=implicit-function-declaration -Werror=missing-prototypes -pipe -Os -fstrict-aliasing -Wno-deprecated-declarations -Wno-declaration-after-statement -arch ppc '-DG_LOG_DOMAIN="GLib"' -DGLIB_COMPILATION -fvisibility=hidden -MD -MQ glib/libglib-2.0.0.dylib.p/gmem.c.o -MF glib/libglib-2.0.0.dylib.p/gmem.c.o.d -o glib/libglib-2.0.0.dylib.p/gmem.c.o -c ../glib-2.72.1/glib/gmem.c
In file included from ../glib-2.72.1/glib/gmem.c:29:0:
./config.h:344:0: warning: "__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4" redefined
 #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4
 
<built-in>: note: this is the location of the previous definition
../glib-2.72.1/glib/gmem.c: In function 'g_aligned_alloc':
../glib-2.72.1/glib/gmem.c:629:3: error: #error "This platform does not have an aligned memory allocator."
 # error "This platform does not have an aligned memory allocator."
   ^~~~~
ninja: build stopped: subcommand failed.
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCTigerPorts_devel_glib2/glib2/work/build" && /opt/local/bin/ninja -j1 --verbose -v 
Exit code: 1
```

**Comment by ryandesign** [comment]
I do not want to update glib2-devel all the way to the latest version. We only just updated glib2-devel to 2.66.x. The next step should be to port those changes to the glib2 port. The next step after that would be to update glib2-devel to 2.68.x. etc. One step at a time with lots of time in between. This gives other ports time to adapt to the changes.

**Comment by kencu** [comment]
the way to get past the aligned memory access error is to either use legacysupport, which often works, or to patch gmem.c manually to do the same thing legacysupport does.

https://github.com/macports/macports-legacy-support/blob/master/src/posix_memalign_emulation.c

**Comment by barracuda156** [comment]
@kencu Thank you so much! On Leopard it has built successfully! Tiger I will check later on, but the error was identical, so likely it will also work.
```
36-61:~ svacchanda$ port -v installed glib2
The following ports are currently installed:
  glib2 @2.62.6_2+x11 requested_variants='-universal' platform='darwin 9' archs='ppc' date='2021-12-22T12:28:22+0800'
  glib2 @2.64.6_0+x11 requested_variants='' platform='darwin 9' archs='ppc' date='2021-12-29T16:07:42+0800'
  glib2 @2.64.6_1+universal+x11 requested_variants='+universal' platform='darwin 9' archs='ppc ppc64' date='2022-04-06T02:12:47+0800'
  glib2 @2.64.6_1+x11 requested_variants='-universal' platform='darwin 9' archs='ppc64' date='2022-03-08T06:30:55+0800'
  glib2 @2.72.1_0+universal+x11 (active) requested_variants='+universal' platform='darwin 9' archs='ppc ppc64' date='2022-04-24T19:58:58+0800'
```

**Comment by barracuda156** [comment]
> the way to get past the aligned memory access error is to either use legacysupport, which often works, or to patch gmem.c manually to do the same thing legacysupport does.
> 
> https://github.com/macports/macports-legacy-support/blob/master/src/posix_memalign_emulation.c

@kencu And it has built on Tiger after adding `legacysupport` too.

**Comment by mascguy** [comment]
@ryandesign Ryan, would you be opposed to creating a 3rd port for `glib2` - named something like `glib2-upstream`, or whatever we want to call it - to start proactively vetting the latest release?

Ultimately it won't be needed, once we've gotten to parity with upstream. But in the interim, it would give us an opportunity to start testing everything with it.

Thoughts?

**Comment by barracuda156** [comment]
> As for maintaining it, I'm happy to take that on, until we're at a point that we can obsolete it.
> 
> Thoughts?

@mascguy Sounds good to me.

**Review by mascguy — APPROVED** [review]

**Comment by ryandesign** [comment]
Whatever you want to do.

**Comment by mascguy** [comment]
> Whatever you want to do.

Thanks Ryan!

Sergey, I've tested locally, and all looks good. Will merge once CI completes.

**Comment by mascguy** [comment]
> @ryandesign @mascguy Thank you!
> 
> Now two questions:
> 
>     1. _Can_ we make some port to depend on `glib2-upstream`? I mean, is it acceptable?
> 
>     2. If yes, how to do that technically?

Yes, a dependency on `glib2-upstream` is acceptable... though it should only be done for Devel ports.

As for the specifics, it's simply a matter of changing the path-style dep, to `port:glib2-upstream`.

**Comment by mascguy** [comment]
One other comment: We should limit the number of ports dependent upon `glib2-upstream`. For a case like your pending update to `libsoup-devel` - which absolutely requires the latest version of `glib2` - that's fine.

In short, we'll take this on a case-by-case basis.

**Pull request merged**
