### PR TITLE
libsndfile: description

### PR DESCRIPTION
**Pull request by janstary**
Make the short description fit `port search --line`
take long description from the homepage.
No functional change.

### CODE REVIEW

**Comment by janstary** [comment]
The failed check is in fact Travis's own
```
./_ci/bootstrap.sh: line 57: shell_session_update: command not found
```

**Comment by jmroot** [comment]
No, the relevant error is earlier: `Failed to parse file audio/libsndfile/Portfile: invalid command name "*"`
You forgot some line continuation backslashes.

**Comment by ryandesign** [comment]
It looks like you're trying to have a bulleted list in the long description. If you want it to actually display that way when the user runs `port info`, add a newline (`\n`) before each bullet. See the mongo-tools port for an example. If you then squash all the commits into one, we can merge it.

**Comment by janstary** [comment]
Clean PR in https://github.com/macports/macports-ports/pull/1200

**Pull request closed without merging**
