### PR TITLE
libxmlxx5: update to 5.0.3

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
CI fail on:
```
  [85/92] /usr/bin/python3 /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_textproc_libxmlxx5/libxmlxx5/work/libxml++-5.0.3/tools/build_scripts/tutorial-custom-cmd.py insert_example_code /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_textproc_libxmlxx5/libxmlxx5/work/libxml++-5.0.3/docs/manual /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_textproc_libxmlxx5/libxmlxx5/work/libxml++-5.0.3/examples ../libxml++-5.0.3/docs/manual/libxml++_without_code.xml docs/manual/libxml++.xml
  [86/92] /usr/bin/python3 /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_textproc_libxmlxx5/libxmlxx5/work/libxml++-5.0.3/tools/build_scripts/tutorial-custom-cmd.py html docs/manual/libxml++.xml docs/manual/html
  FAILED: docs/manual/html 
  /usr/bin/python3 /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_textproc_libxmlxx5/libxmlxx5/work/libxml++-5.0.3/tools/build_scripts/tutorial-custom-cmd.py html docs/manual/libxml++.xml docs/manual/html
  error : Unknown IO error
  warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl"
  cannot parse http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl
```

**Comment by barracuda156** [comment]
`+docs` fails to build on CI with:
```
  [86/92] /opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_textproc_libxmlxx5/libxmlxx5/work/libxml++-5.0.3/tools/build_scripts/tutorial-custom-cmd.py html docs/manual/libxml++.xml docs/manual/html
  FAILED: docs/manual/html 
  /opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_textproc_libxmlxx5/libxmlxx5/work/libxml++-5.0.3/tools/build_scripts/tutorial-custom-cmd.py html docs/manual/libxml++.xml docs/manual/html
  error : Unknown IO error
  warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl"
  cannot parse http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl
```

**Comment by catap** [comment]
@barracuda156 try to replace `http://` into `https://` inside `http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl` in files.

**Comment by barracuda156** [comment]
@catap Thank you. Let’s see if it works.

**Comment by mascguy** [comment]
> @catap Thank you. Let’s see if it works.

Still failing. Are you sure you patched all URLs in the docs?

**Comment by barracuda156** [comment]
> > @catap Thank you. Let’s see if it works.
> 
> Still failing. Are you sure you patched all URLs in the docs?

No, only the one which Kirill pointed to. I will return to this later today.

**Comment by reneeotten** [comment]
ping @barracuda156

**Comment by mascguy** [comment]
> `+docs` fails to build on CI with:
> 
> ```
>   FAILED: docs/manual/html 
>   error : Unknown IO error
>   warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl"
>   cannot parse http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl
> ```

Okay, so the reason this is happening, is that several deps need to be added. Specifically, `docbook-xml`, along with `docbook-xsl-nons`.

With those pulled in, all of the DTDs, etc, are provided locally. And no network access occurs.

The key to figuring this out is trace mode, which shows what's happening.

Anyhow, all fixed, and looks good now. Will merge once CI completes.

**Review by mascguy — APPROVED** [review]

**Comment by barracuda156** [comment]
@mascguy Great, thanks for fixing this properly!

**Pull request merged**
