### PR TITLE
py-photomosaic: Add Python 310, Update dependencies

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6 21G115 x86_64
Xcode 14.0 14A309

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
@essandess these CI failures are likely not due to timeouts - can you take a look please?

**Comment by essandess** [comment]
> @essandess these CI failures are likely not due to timeouts - can you take a look please?

I've redone trace installs of all the different ports in this PR and don't observe any issues. I also don't see what the issue is from the CI logs. I just rebased and hope it works this time.

**Comment by reneeotten** [comment]
> > @essandess these CI failures are likely not due to timeouts - can you take a look please?
> 
> I've redone trace installs of all the different ports in this PR and don't observe any issues. I also don't see what the issue is from the CI logs. 

the CI says: ``` Installing dependency (183 of 204) 'py310-nbconvert' with variants '' ... [FAIL]```

> I just rebased and hope it works this time.

it didn't...

**Comment by someuser12** [comment]
You might want to try again, if the building of py310-nbconvert by the CI bots was hindered by the issue in https://trac.macports.org/ticket/65809 .

**Comment by essandess** [comment]
> You might want to try again, if the building of py310-nbconvert by the CI bots was hindered by the issue in https://trac.macports.org/ticket/65809 .

Thanks. Did a fast forward and this is good to merge.

**Pull request merged**
