### PR TITLE
mumps: respect MacPorts build flags & add scotch dep

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.13
Xcode 9.4

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by seanfarley** [comment]
Why did you add the scotch dependency? It's horrible and doesn't scale at all.

**Comment by MarcusCalhoun-Lopez** [comment]
I did not know that about the quality of [Scotch](http://gforge.inria.fr/projects/scotch).
Thank you for the information.

I was only going by the `Makefile.inc`, which says
"Metis/ParMetis and SCOTCH/PT-SCOTCH (ver 6.0 and later) orderings are recommended."
Also, Gentoo Linux uses Scotch as [a default option](https://gitweb.gentoo.org/repo/gentoo.git/tree/sci-libs/mumps/mumps-4.10.0-r1.ebuild).

Personally, I have no strong feelings.
Would you like me to
1) remove the dependency altogether?
1) make it a variant?

Either is easy enough to do.

**Comment by seanfarley** [comment]
I can't remember which graph partitioning is used by default so I'll check that first. Scotch used to be recommend circa pre-2010 but metis / parmetis surpassed it long ago. Only HPC really care, I guess (fwiw we didn't recommend scotch in PETSc).

**Comment by pmetzger** [comment]
So how do we move this forward?

**Comment by seanfarley** [comment]
Apologies; been away for a while. I checked this out and I couldn't find anything conclusive so I imagine this won't actually be a real-life problem. If it turns out to be a problem, it won't be hard to solve in the future. Go ahead and merge; looks good to me.

**Comment by MarcusCalhoun-Lopez** [comment]
Thank you for the review.

**Pull request merged**
