### PR TITLE
lazarus: symlink app bundle to applications_dir

### PR DESCRIPTION
**Pull request by kencu**
this leaves the original bundle structure in place and allows the lazarus application to rebuild itself in ~/.lazarus as designed if needed when adding modules

The ```${prefix}/share/lazarus``` directory contains executables, and therefore cannot be, at least by default, world writable and executable. The security concerns are too great for abuse.

This approach is the upstream recommended approach, and it does work, although slightly imperfectly. Launching ```lazarus.app``` from the applications directory will launch the secured application in ```${prefix}/share/lazarus```. This runs normally, as expected. 

If a user recompiles in some modules, a new ```lazarus.app``` binary is generate in the user's home directory, in the ~/.lazarus subdirectory.

The issue is that when the ```lazarus.app``` is again later launched from the applications dir, you again get the original, not your modified application. There is a ```restart``` option in the lazarus.app menus that will relaunch the application, and if present, will use your customized version in ~/.lazarus.

The command line ```startlazarus``` command will also start the customized version of lazarus.app in ~/.lazarus, although this does not work quite correctly, and insists on giving a warning about there being no "lazarus" binary in the directory in which you are when you run ```startlazarus```, which is annoying. But then, if one exists, it at least offers to run the customized version in ~/.lazarus, which is what you presumably want.

At present, this approach, although imperfect, seems the only secure way to allow this port in MacPorts. The situation might be improved with a shell script application that looks for the customized version of lazarus.app in ~/.lazarus (or some other path) and runs that if one exists. 

I had hoped that just changing the existing lazarus.app launcher in ```${prefix}/share/lazarus``` to run ```startlazarus``` instead of running ```lazarus``` might have accomplished that, but unfortunately it did not, and generate errors doing so. Still, a custom shell script might succeed where that simple symlink approach failed.

This is, at least, a step in the right direction.

I don't see how we could allow a world-writable and world-executable binary directory to exist on any MacPorts installation. I think I stepped in it this time, in my eagerness to see your months of work and hopes with this port get accepted.

### CODE REVIEW

**Comment by kencu** [comment]
I'm wondering about an ```/Applications/MacPorts/lazarus.app``` that launches a simple shell script, that does something like this (pseudocode):

```
if there exists ~/.lazarus/bin/lazarus.app
   open it and exit the launcher
otherwise
  open ${prefix}/share/lazarus/lazarus.app and exit the launcher
```

that would appear cover off the majority of the cases. If someone starts installing custom-built versions of lazarus.app in non-standard locations -- well -- presumably they know how to make their own symlink to their favourite lazarus.app in their ~/Applications folder themselves, for goodness sakes. After all, these are programmers we'd be talking about here...

**Comment by kencu** [comment]
It looks like ```/opt/local/bin/startlazarus``` can be made to work correctly if you change it from symlink (which gives me a warning dialog box every time I use it) to a shell script (on 10.14 with bash at least) that looks like this:
```
pushd /opt/local/share/lazarus 
/opt/local/share/lazarus/startlazarus
popd
```

obviously the path would be changed to ${prefix} on actual installation.

**Comment by kencu** [comment]
that little script also seems to launch a clean version of the origin lazarus.app if there is nothing in ~/.lazarus, which is pretty much what you want.

And that gives me another idea -- perhaps the better thing to do here for the /Applications/MacPorts launcher is to symlink the startlazarus.app instead, which just might always (TM)DoTheRightThing.

**Comment by kencu** [comment]
> And that gives me another idea -- perhaps the better thing to do here for the /Applications/MacPorts launcher is to symlink the startlazarus.app instead, which just might always (TM)DoTheRightThing.

That actually does seem to work correctly, and better than just symlinking the lazarus.app. It initializes a new ~/.lazarus if there isn't one, and launches the prebuilt lazarus.app in /opt/local/share/lazarus. If you rebuild lazarus with addition modules, it launches the new one you want in ~/.lazarus. 

It just looks a bit ugly, because it has no icon attached to it, but that would seem trivial to fix. Or, we could use our app PortGroup instead, but that seems overkill as there is almost all the work done already in the port to make the proper executable bundle.

**Comment by pmetzger** [comment]
A shell script is certainly one way to do it. Why does your latest attempt need the pushd/popd?

For the startlazarus.app idea, it seems like adding the icon would be easy, yes.

**Comment by kencu** [comment]
the startlazarus application seems to look for a binary called "lazarus" in the cwd, ergo the pushd/popd. Doesn't even work if I put a symlink to "lazarus" in the /opt/local/bin directory.

I think we'll get this working just as it should. We're quite close now...

**Comment by pmetzger** [comment]
Well, sure, but why not just cd to the directory? It's not like you need to return afterwards?

**Comment by kencu** [comment]
I think you wrote the "bash" guide, if I recall correctly, so you would know,  but if you did that from a terminal, I was led to believe (without extensively testing it) that it would leave you with the wrong cwd when it was done (it would have changed it on you). So says Dr. Google, anyways... incorrect?

**Comment by pmetzger** [comment]
A subshell can't change the CWD in the parent. When the subshell exits, the parent doesn't know (or care) what working directory it was in. As the script does nothing after executing the binary, there's no need to return to the original working directory.

**Comment by kencu** [comment]
It's not a subshell, though, is it? You run this command from an active terminal window. (the existing /opt/local/bin/startlazarus command is a symlink that doesn't work).

(This isn't the shell script that I was thinking of using the app bundle -- I found that wasn't needed.)

**Comment by pmetzger** [comment]
When you run a shell script, it is run in a subshell. Only if you explicitly source a file (with `source` or `.`) does it run in the shell you are typing at.

**Comment by kencu** [comment]
@kamischi -- have you had a chance to try this? It seems like an elegant solution to the issues. I note also that Lazarus has been updated, so perhaps we might consider incorporating that update into this PR, as Lazarus is such a behemoth to build for the buildbot...

**Comment by kencu** [comment]
added two commits -- use "cd" like Perry suggested, which works and doesn't change the cwd, like he said it wouldn't -- and updated Lazarus to 2.0.6 in the same commit series so as to minimize work and disk space on the buildbot.

**Pull request merged**
