### PR TITLE
diff-pdf: new Portfile

### PR DESCRIPTION
**Pull request by pietvo**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6
Xcode 10.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by MarcusCalhoun-Lopez** [comment]
Just out of curiosity, is there a reason this submission was closed?
I was reviewing the Portfile when the PR was closed.
There were some issues, which is why it was taking me a while.

**Comment by pietvo** [comment]
I closed it because it consisted of two commits, which is generally frowned upon. So I closed it and made a new one, with a single commit. The result is the same, however.

I don't do this often, so it is a bit of a challenge to get it correct, conforming to all the rules.

**Comment by MarcusCalhoun-Lopez** [comment]
Thank you for the response.
I see the new PR.

I am no expert it git/github (far from it), but I believe that [Squashing Commits](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing) is one way of dealing with this kind of situation.

**Comment by mojca** [comment]
Yes, please aviod creating new PRs. Yes, squashing might be requested, but that's easy to do at the end once everyone is happy with the contents. (We can either help you do it or do it instead of you.)

**Comment by pietvo** [comment]
I see, I did not know that you could do squashing at the end. I agree that it is the best. I saw that you get an option to squash and commit for a PR on your own fork, so I expected that also on the PR to the parent repository, but I did not get it, and then the PR was already submitted. Anyway, I have learned something new.

**Pull request closed without merging**
