### PR TITLE
nushell: update to 0.88.1

### PR DESCRIPTION
**Pull request by b4nst**
#### Description

Update Nushell to 0.88.1.

> Note that this needs #21985 to land, as it requires rustc 1.72.1 or newer

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.2.1 23C71 arm64
Xcode 15.1 15C65

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
Rust has been updated. Can you update this, please?

**Comment by herbygillot** [comment]
I've recently updated `nushell` to 0.89.0 in https://github.com/macports/macports-ports/commit/bb9a4c5d451bcd02ef6d4637cfd0cb9e45c304a9

Closing this.

**Comment by herbygillot** [comment]
Though I see this PR changes the notes for the port, so @b4nst, if you think that's still a necessity, you can open a new PR to do that.

**Comment by b4nst** [comment]
Ah sorry I dropped the ball on this one, I was afk for few weeks. Thanks for taking over @herbygillot. I think we can wait next release before including the nodtes change, that's okay.

**Pull request closed without merging**
