### PR TITLE
Dbcli related ports updates

### PR DESCRIPTION
**Pull request by xeron**
#### Description

Added new ports:
* `py-terminaltables`
* `py-backports.csv`
* `py-cli-helpers`

Updated ports:
* `py-pymysql` to `0.8.0` (https://trac.macports.org/ticket/56203)
* `py-pgspecial` to `1.10.0`
* `mycli` to `1.16.0`
* `pgcli` to `1.9.0`

###### Type(s)

- [x] update
- [x] submission

###### Tested on

macOS 10.13.4 17E199
Xcode 9.3 9E145 

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by g5pw** [comment]
uh, @l2dy is that a bug in the regex? (last line of the macportsbot comment)

**Comment by l2dy** [comment]
@g5pw Travis API probably returned corrupted logs. I could regex the URL but I'm not sure if its length is constant.

**Comment by mojca** [comment]
But many of the summaries of logs are missing a line or two, so it's not just this one example, I doubt that Travis logs would be corrupted so often (it's just that nobody notices a missing line, while this error is more obvious).

**Comment by mojca** [comment]
More precisely: the last log is always missing.

**Comment by pmetzger** [comment]
Do any of you have any comments on the pull request itself? :)

**Comment by pmetzger** [comment]
@xeron: wherever you have

`gmail.com:xeron.oskom`

in your `maintainers` lines, you should now probably have

`{@xeron gmail.com:xeron.oskom}`

instead. This indicates both your email address and your github handle to the system.

**Comment by mojca** [comment]
The patches look clean to me. Yes, it would be nice to add github handle of the maintainer and for the next update it would be nice to add `size`, but I'm not sure if we want to insist going back in history to edit all those commits just for the sake of these two minor issues. Unless @g5pw has any concerns why this should not be merged for this port, it can get merged and then all ports maintained by @xeron (I guess there are others that were not part of this PR) could be mass-changed to add the github handle at once.

**Comment by g5pw** [comment]
Well, @pmetzger and @mojca I did open a request for review, but I checked upstream an it looks like a new `pgcli` release is available with the patch already merged. @xeron could you update the pgcli port, or should I do it? :)

**Comment by xeron** [comment]
Updated `pgcli` to `1.9.1`.

**Comment by xeron** [comment]
I'll open a new PR with `maintainer` info update.

**Comment by pmetzger** [comment]
Since everyone seemed happy, I've merged this. Thank you for your contributions to Macports, @xeron! And please do submit that pull request updating your maintainer lines.

**Pull request merged**
