### PR TITLE
mesa: update to  22.1.7

### PR DESCRIPTION
**Pull request by kencu**
### Description

- move to meson build
- trim deps
- use python3
- enabled tests
- default to osmesa always
- require appropriate compilers

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G14042 x86_64
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
I have so far tested this on 10.13 only... it will need testing on newer and older systems, and universal testing.

The test suite is enabled and passes 100% on 10.13.
glxgears works nicely, and glxinfo returns reasonable-looking information.

**Comment by mascguy** [comment]
> I have so far tested this on 10.13 only... it will need testing on newer and older systems, and universal testing.
> 
> The test suite is enabled and passes 100% on 10.13. glxgears works nicely, and glxinfo returns reasonable-looking information.

Let's change to draft then, so that it's not inadvertently merged yet.

**Comment by kencu** [comment]
Yes, if you can add some testing that would be helpful. 10.7 thru 10.12 in particular. I’ll do 10.6 later on in a bit.

**Comment by kencu** [comment]
It has the scandir issue seen on 10.8 and less… will fix that soon.

**Comment by kencu** [comment]
getting very close now; 10.6 works, universal works.
```
$ port -v installed mesa
The following ports are currently installed:
  mesa @22.1.7_0+universal (active) requested_variants='+universal' platform='darwin 10' archs='i386 x86_64' date='2022-10-01T04:24:04-0700'
```

there are a couple of test errors on 10.6 that I didn't see on 10.13, that don't seem to affect the functioning of a few test programs.

**Comment by barracuda156** [comment]
@kencu @mascguy Let me try this on 10.6 for ppc32.

**Comment by kencu** [comment]
There were a couple of Tiger fixes I passed over gor now that may still be needed. 

Building w gcc may need libatomic added.

**Comment by barracuda156** [comment]
> There were a couple of Tiger fixes I passed over for now that may still be needed.
> 
> Building w gcc may need libatomic added to ldflags I suspect.

@kencu Give me a day please, I will check. Right now building gcc12 on both available machines :)

**Comment by kencu** [comment]
I added the atomic flag and the Tiger bits back again.

**Comment by barracuda156** [comment]
@mascguy @kencu On Rosetta builds fine:
```
macmini:~ svacchanda$ port -v installed mesa
The following ports are currently installed:
  mesa @17.1.6_2+osmesa+python27 requested_variants='' platform='darwin 10' archs='ppc' date='2022-04-10T13:36:54+0800'
  mesa @22.1.7_0 (active) requested_variants='' platform='darwin 10' archs='ppc' date='2022-10-05T06:32:37+0800'
```

**Comment by barracuda156** [comment]
@mascguy @kencu However 10.5.8 may need `-fpermissive` or something alike, given this error on 10.6 PPC:
```
../mesa-22.1.7/src/util/u_thread.h: In function 'void u_thread_setname(const char*)':
../mesa-22.1.7/src/util/u_thread.h:142:23: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
  142 |    pthread_setname_np(name);
      |                       ^~~~
      |                       |
      |                       const char*
```

**Comment by barracuda156** [comment]
This fixes the native PPC build:
```
if {[string match *gcc* ${configure.compiler}]} {
    if {${build_arch} in [list ppc ppc64]} {
        configure.cxxflags-append -fpermissive
    }
    configure.ldflags-append -latomic
}
```

**Comment by kencu** [comment]
most likely the Intel build with gcc is broken too, if the root cause is using gcc as the compiler.

Have you sorted out what the root problem is here, though? Is the definition of pthread_setname_np(name) in legacysupport wrong?

**Comment by kencu** [comment]
done, thanks!

https://github.com/macports/macports-ports/commit/c3977c61681f4f65c8b663040bf8633c1b90d72f

**Comment by barracuda156** [comment]
> most likely the Intel build with gcc is broken too, if the root cause is using gcc as the compiler.
> 
> Have you sorted out what the root problem is here, though? Is the definition of pthread_setname_np(name) in legacysupport wrong?

@kencu I will look into that, thank you. So far I just wanted to verify if the build succeeds or not.

**Pull request merged**
