### PR TITLE
psi: update to 1.5, fix build for 10.14+

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
Let me fix loading, apparently it is not powerpc-specific issue at all; will do today.

**Comment by pmetzger** [comment]
Howdy! This has been a draft since June. Can we finish it or close it?

**Comment by barracuda156** [comment]
@pmetzger Yes, let me deal with it shortly. If it won’t yet work correctly on old systems (build itself works, running does not, one link is set wrong by the build system), but works on the new, we can merge this first, and I fix ppc in a separate PR.
If it fails to run on a new macOS as well, I gonna close this for the time-being.

Allow me 2–3 days, and this will be sorted.

**Comment by rowue** [comment]
Hi,

as I'm no using my mac too much (in principle only for some ports), someone else can take maintainership.

Best,


   Rolf

**Comment by barracuda156** [comment]
@pmetzger I realized that this will not build on aarch64 due to our broken qt4-mac, hence the delay, but I have finally got to an Intel setup and switched it to non-universal builds, so I do not need to waste hours building everything from source.
Should be complete tonight.

**Comment by barracuda156** [comment]
@pmetzger Ok, I can confirm it starts normally on 10.6.8 x86_64, so w/e is the cause for a failure on ppc is either SDK-specific, arch-specific or 32-bit specific (I am not gonna bother testing i386 now).

So I suggest merging this, since x86_64 works. I gonna deal with fixing ppc when I have time and mood, no hurry with that.

**Comment by Neustradamus** [comment]
To follow this PR.

Note that there is Psi+ with improvements and other features like OMEMO...
- https://github.com/psi-im
- https://github.com/psi-plus

**Comment by Neustradamus** [comment]
There is Psi+ with improvements and other features like OMEMO...
- https://github.com/psi-im
- https://github.com/psi-plus

For macOS, there are here:
- https://sourceforge.net/projects/psiplus/files/macOS/
- https://sourceforge.net/projects/psi/files/Experimental-Builds/macOS/

**Comment by barracuda156** [comment]
@Neustradamus Thank you! I will look into that and see if it can help with PowerPC build.

**Pull request merged**
