### PR TITLE
blosc: update to 1.21.4, fix build with gcc on 10.6.8 x86

### PR DESCRIPTION
**Pull request by barracuda156**
###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@mascguy @stromnov Could we merge this? Should be uncontroversial.

**Comment by mascguy** [comment]
A few things to check:

* Do any ports depend on this?
* If so, are you rev-bumping those?

That's the standard checklist, which you should always ask yourself before declaring a PR as ready for merging.

**Comment by barracuda156** [comment]
@mascguy Gonna handle this by tomorrow.

**Comment by barracuda156** [comment]
@mascguy Revbump dependents, let us see whether everything builds.

**Review by mascguy — APPROVED** [review]

**Pull request merged**
