### PR TITLE
kubectl_select: keep completions directory

### PR DESCRIPTION
**Pull request by tsabirgaliev**
Closes: https://trac.macports.org/ticket/66987

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.2.1 22D68 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
The commit message should have not just the ticket URL but:

```
Closes: https://trac.macports.org/ticket/66987
```

so that Trac will close the ticket when the PR is merged.

**Comment by tsabirgaliev** [comment]
@herbygillot can you please review this?

**Comment by herbygillot** [comment]
> @herbygillot can you please review this?

Apologies - I didn't look because the PR was marked as failing.

It looks good. If you modify your commit msg as @ryandesign requested, we'll be good to merge.

**Comment by tsabirgaliev** [comment]
> > @herbygillot can you please review this?
> 
> Apologies - I didn't look because the PR was marked as failing.
> 
> It looks good. If you modify your commit msg as @ryandesign requested, we'll be good to merge.

I apologize, I edited the PR description, but not the commit message.

Cleaned it up, rebased and force-pushed.

**Comment by herbygillot** [comment]
Thanks - merged.

**Pull request merged**
