### PR TITLE
mspdebug: update to 0.25, switch to github

### PR DESCRIPTION
**Pull request by mojca**
See also the related #3336.

@g5pw: would it be OK to make the port openmaintainer?
(Please don't hurry with merging before the maintainer approves the changes.)

###### Tested on
macOS 10.13.6 17G3025
Xcode 10.1 10B61 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by g5pw** [comment]
yes, actually, feel free to adopt it. I'm not using this software anymore :/

**Comment by mojca** [comment]
I'm not sure if I'll ever use it at all (I don't know how to use it yet), I just wanted to figure out how to test the msp crosscompiler (I don't have any hardware available anyway).

**Comment by g5pw** [comment]
I see. I have some hardware at Mittelab I can test stuff on.

**Comment by g5pw** [comment]
It looks like `patch-Makefile.diff` is missing in the commit?

**Comment by mojca** [comment]
I'm sorry, hopefully fixed now. This has been fixed upstream, but there has been no release since the summer 2017.

**Pull request merged**
