### PR TITLE
GROMACS: update to 2021.3

### PR DESCRIPTION
**Pull request by btywoniuk**
#### Description

This PR is updating the GROMACS port to the last released version (2021.3). 
It also fixing:

- Compilation errors due to outdated dependencies.
- Removed selecting clang 5.0 as the default compiler. 
- Removed some variants that seem to be no longer relevant on macOS

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 11.5.2 20G95 x86_64
Xcode 12.5.1 12E507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
thanks for the PR @btywoniuk ! Your changes remove quite a bit of features (i.e., variants and subports) from what's currently in the Portfile. A slightly later PR (#12184) has done the same update while retaining most of the current features - likely that's an approach that the maintainer (@dstrubbe) is more likely to take. We're waiting for a comment from him on that (or this PR) and hopefully can get an update merged soon!

**Comment by reneeotten** [comment]
just merged PR #12184 which included the changes here (and a few more); thanks again for submitting a PR!

**Comment by btywoniuk** [comment]
I admit that might went a bit too far with removing some options but GROMACS does a pretty good job of determining optimal parameters so some of them might be not really needed but still, they could be left. 
The only option I would really be against is gromacs-plumed. PLUMED is an independently developed library and it's not always in sync with GROMACS so this should be kept as a totally separate package with the supported GROMACS version by PLUMED.

**Comment by reneeotten** [comment]
> I admit that might went a bit too far with removing some options but GROMACS does a pretty good job of determining optimal parameters so some of them might be not really needed but still, they could be left. The only option I would really be against is gromacs-plumed. PLUMED is an independently developed library and it's not always in sync with GROMACS so this should be kept as a totally separate package with the supported GROMACS version by PLUMED.

`gromacs-plumed` is a subport that is is defined in the same file and they could (but currently don't) easily install a different version of gromacs. There is no difference in doing that compared to having it in a separate Portfile, which I assume you mean by "a totally separate package`?

**Pull request closed without merging**
