### PR TITLE
gavl: update to 1.4.0, fix the build on new macOS

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update, fix the build on new macOS and on Rosetta.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
Ok, so it remains broken on later OS. Earlier version also fails: https://ports.macports.org/port/gavl/details/

CI error:
```
dsp_c.c:131:14: error: SSE register return with SSE disabled
  static float sad_f_c(const uint8_t * src_1, const uint8_t * src_2, 
               ^
```

**Comment by barracuda156** [comment]
Hmm, this looks strange (from build bot on macOS 12):
```
2022-10-29T21:39:55.7175930Z checking build system type... i386-apple-darwin21.6.0
2022-10-29T21:39:55.7177540Z checking host system type... i386-apple-darwin21.6.0
2022-10-29T21:39:55.7376310Z checking for style of include used by make... GNU
2022-10-29T21:39:55.7411860Z checking for gcc... /usr/bin/clang
2022-10-29T21:39:56.6622170Z checking whether the C compiler works... yes
2022-10-29T21:39:56.6622850Z checking for C compiler default output file name... a.out
2022-10-29T21:39:56.7664140Z checking for suffix of executables... 
2022-10-29T21:39:57.0557100Z checking whether we are cross compiling... no
2022-10-29T21:39:57.1279310Z checking for suffix of object files... o
2022-10-29T21:39:57.1939430Z checking whether we are using the GNU C compiler... yes
```

Presumably, it should be `x86_64-*` and _not_ GNU C.

**Comment by pmetzger** [comment]
What's the status on this?

**Comment by barracuda156** [comment]
> What's the status on this?

@pmetzger Unless someone has objections, IMO ready to merge.

**Pull request merged**
