### PR TITLE
qgis3: Update to 3.28.6 with new PROJ and GRASS variants

### PR DESCRIPTION
**Pull request by nilason**
#### Description

Bump to latest version 3.28.6 ~3.28.5~.

In addition adds the variant "+grass" for plugin with latest GRASS version (presently GRASS 8) and enables setting `proj` version (which was previously hardcoded to proj v8).

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6.3 21G419 arm64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by i0ntempest** [comment]
3.30.1 is the newest version, is there any reason for keeping this at 3.28 rather than updating to that?

**Comment by nilason** [comment]
> 3.30.1 is the newest version, is there any reason for keeping this at 3.28 rather than updating to that?

The qgis team have a pretty high-paced development and release cycle. Using this software in production setting is in my experience safer with the long-term-release (now 3.28 from Oct ‘22). If I’m not mistaken the qgis version on MacPorts has always been the LTR version and I’m happy about that.

**Comment by i0ntempest** [comment]
> the qgis version on MacPorts has always been the LTR version

Good points, tho I'm not 100% sure about this, the live check returns the latest version and I have personally updated this port to latest in the past. If we want to keep this at LTR from now on maybe we should change the livecheck?

**Comment by nilason** [comment]
> > the qgis version on MacPorts has always been the LTR version
> 
> Good points, tho I'm not 100% sure about this, the live check returns the latest version and I have personally updated this port to latest in the past. If we want to keep this at LTR from now on maybe we should change the livecheck?

I have to admit I’ve had too much trouble (mainly with qt) to rely on MP’s dist of qgis. The official bundle app bundle however starts to lag behind in maintenance and I thought I’ll have a go with MP (which I use anyway for other software on daily basis). Re. livecheck, I’m not sure how that could be implemented, see https://www.qgis.org/en/site/getinvolved/development/roadmap.html.

**Comment by nilason** [comment]
There is a file at https://qgis.org/version-ltr.txt which might (?) be used.

**Comment by i0ntempest** [comment]
We can now merge this under maintainer timeout. Do you want to wait until all of the PRs of the dependencies of QGIS3 to be merged first?

**Comment by nilason** [comment]
> We can now merge this under maintainer timeout. Do you want to wait until all of the PRs of the dependencies of QGIS3 to be merged first?

Let’s wait for #18077 to be merged first. Minimise the need to rebuild qgis.

**Comment by i0ntempest** [comment]
We now have 3.28.6, you may want to update the PR.

**Comment by nilason** [comment]
> We now have 3.28.6, you may want to update the PR.

Done.

**Pull request merged**
