### PR TITLE
apr: update to 1.6.5

### PR DESCRIPTION
**Pull request by dgilman**
#### Description
I tested this with `port -d test apr`, and it worked, although I am not sure if I was able to do integration tests with users of apr. At any rate, I can tell you that looking at the changelog there were hardly any changes and nothing API breaking so things look safe.

###### Type(s)

- [x] enhancement

###### Tested on
macOS 10.13.6 17G4015
Xcode 10.1 10B61

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
It looks like there are some weird formatting issues in the changes. Do you think you could minimize the diff?

**Comment by danielluke** [comment]
I should be able to get to this today. I usually run the apr, apr-util, and subversion test suites before doing updates to apr.

**Comment by dgilman** [comment]
The formatting: I just straight-up reformatted the thing to get the columns to align. If this is unacceptable I can revert that. Also, if you need me to be the one who runs those tests I can give that a shot.

**Comment by mf2k** [comment]
@dgilman: Please do formatting changes as a separate commit without functional changes.

**Comment by pmetzger** [comment]
@dgilman Precisely what @mf2k said, but one issue is this: the new formatting looks wrong, too. I think you are using a mix of tabs and spaces or some such. You should only use spaces.

**Comment by pmetzger** [comment]
All looks good now! I'll merge. Thanks, @dgilman!

**Pull request merged**
