### PR TITLE
arc, ha, unarj: ports abandoned, cleanup MacPorts < 2.6.0 handling, fix implicit function declaration

### PR DESCRIPTION
**Pull request by chrstphrchvz**
No MX record for maintainer email address domain.
Maintainer was removed from other ports as early as 2008.
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
```
--->  Verifying Portfile for arc
Warning: missing recommended checksum type: size
--->  0 errors and 1 warnings found.
--->  Verifying Portfile for ha
Warning: missing recommended checksum type: sha256
Warning: missing recommended checksum type: size
--->  0 errors and 2 warnings found.
--->  Verifying Portfile for unarj
Warning: missing recommended checksum type: sha256
Warning: missing recommended checksum type: size
Warning: no license set
--->  0 errors and 3 warnings found.
```
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
Added fix for implicit function declaration in `unarj`

**Comment by chrstphrchvz** [comment]
`ha` and `unarj` aren't using the right compiler…

**Comment by chrstphrchvz** [comment]
Implicit function declarations in `ha`:
```
machine.c:218:10: error: implicitly declaring library function 'strcmp' with type 'int (const char *, const char *)' [-Werror,-Wimplicit-function-declaration]
    if (!strcmp(name,".") || !strcmp(name,"..")) return T_SKIP;
         ^
machine.c:218:10: note: include the header <string.h> or explicitly provide a declaration for 'strcmp'
machine.c:350:9: error: implicitly declaring library function 'strlen' with type 'unsigned long (const char *)' [-Werror,-Wimplicit-function-declaration]
    pos=strlen(name_req);
        ^
machine.c:350:9: note: include the header <string.h> or explicitly provide a declaration for 'strlen'
machine.c:356:5: error: implicitly declaring library function 'strcpy' with type 'char *(char *, const char *)' [-Werror,-Wimplicit-function-declaration]
    strcpy(newname,name_req);
    ^
machine.c:356:5: note: include the header <string.h> or explicitly provide a declaration for 'strcpy'
3 errors generated.
```

and in `arc` (there is already a patch removing the existing incomplete function declarations):
```
marc.c:157:3: error: implicit declaration of function 'makefnam' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                makefnam(arg[1],".arc",arcname);
                ^
marc.c:330:8: error: implicit declaration of function 'makefnam' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    {    makefnam(p,".CMD",buf);
         ^
2 errors generated.
```

**Comment by ryandesign** [comment]
> `ha` and `unarj` aren't using the right compiler…

Your changes improve that situation, but they're still not using the right `-arch` flags. Using the makefile 1.0 portgroup correctly can solve all of those types of problems at once.

**Pull request merged**
