### PR TITLE
memtester: update to newer upstream version 4.5.1

### PR DESCRIPTION
**Pull request by kamischi**
Minor changes:
- Add license
- Change from http to https
- Add size in checksums
- Convert tabs to spaces in pre-patch.

#### Description

memtester: update to newer upstream version 4.5.1

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 12.1 21C52 arm64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kamischi** [comment]
Hi.

The problem is when fetching the sources. It fails with: Fetching distfile failed: Maximum (50) redirects followed. 
Once I had the source file all went well. But I am at the end of my wisdom, how to resolve the endless redirect loop.

MiSchi.

**Comment by ryandesign** [comment]
Thanks for the update!

> It fails with: Fetching distfile failed: Maximum (50) redirects followed.

The web server is broken. I reported this problem to the developer.

**Comment by kamischi** [comment]
Thanks for fixing.

**Comment by ryandesign** [comment]
If you're interested, the developer says his web server is fine and that it's curl that's broken. You can follow that discussion at https://github.com/curl/curl/issues/8290.

**Pull request merged**
