### PR TITLE
hdf5: update to 1.10.7

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Disable silent rules

Fixes: https://trac.macports.org/ticket/61229

#### Description
https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.7/src/hdf5-1.10.7-RELEASE.txt

###### Type(s)

- [x] bugfix
- [x] enhancement
- [x] security fix

###### Tested on

macOS 10.15.6
Xcode 12 command line tools

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
In progress (`+openmpi` variant; waiting on `openmpi-default`, which got stuck under trace mode).  
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
Normally this ports' dependents get revbumped whenever this port is updated. Is doing so still necessary given the [upstream API compatibility report](https://portal.hdfgroup.org/display/support/HDF5%201.10.7#compatibility1107) claiming it to be source- and binary-compatible with 1.10.6?

**Comment by eborisch** [comment]
Deps will all need bumps; HDF5 complains loudly even for minor version updates. (Compiles, links, and then complains unless an environment variable is set.)

I believe there is a compile-time setting we can select to suppress these checks (and then not revbump all the deps unless we feel there is something that requires it, as informed by the upstream API report) but we would have to decide if we want to do that against the (default) design from upstream, but I'm open to the discussion.

**Comment by chrstphrchvz** [comment]
I've successfully compiled `hdf5 +openmpi` (including compiling t_cache.c) with Xcode 12, so I am certain [trac#61229](https://trac.macports.org/ticket/61229) is addressed by this PR. (The Azure CI Xcode 12 `-openmpi` build succeeded, but didn't indicate whether t_cache.c could be compiled.)

I'm inclined to let someone else take over for handling dependents; even if I had an easy recipe for finding what ports to revbump, it may be a while before I can get to adjusting all of them.

**Comment by eborisch** [comment]
Closing in favor of #8616.

**Pull request closed without merging**
