### PR TITLE
moon-buggy: new port submission

### PR DESCRIPTION
**Pull request by kencu**
a fun little console-based game

### CODE REVIEW

**Comment by ken-cunningham-webuse** [comment]
I saw this one on homebrew and thought macports should have it too.

**Comment by ken-cunningham-webuse** [comment]
so - pretty sure this can just be committed. doesn't get much simpler, really. whaddaya think?

**Comment by ken-cunningham-webuse** [comment]
Oh dear -- I can understand the hesitation over committing a GL binding port that takes some thinking about -- but nobody  wants moon-buggy? Now I'm feeling so disappointed :>

**Comment by raimue** [comment]
Oh, I remember good old moon-buggy. :-)

Is this really `GPL-3` and not `GPL-3+`? That would be quite unusual.

Judging from the patch to Makefile.am, `depends_build` seems to miss port:automake. Actually `use_autoreconf yes` will add these automatically, so you can just remove the `depends_build` option completely.

Why is `patchfiles-append` inside `post-extract`? I see no reason to do it this way. Just use a plain `patchfiles` option.

`--prefix=${prefix}` is already in configure.pre_args, no need to pass it twice. The values passed to `--mandir` and `--infodir` look like default values in usual configure scripts, so they can probably be removed as well.

**Comment by ken-cunningham-webuse** [comment]
Thanks for the review.

> Is this really GPL-3 and not GPL-3+? That would be quite unusual.

I can't find 'and later version' written anywhere in the code for moon-buggy. The license badge on github says GPL-3. Looks like GPL-3 to me. Some of the included utility scripts have different licenses. 

>Judging from the patch to Makefile.am, depends_build seems to miss port:automake. Actually use_autoreconf yes will add these automatically, so you can just remove the depends_build option completely.

Done. (I saw a trac ticket that suggested use_autoreconf might do that, but couldn't confirm that behaviour and my last port failed on the bots due to a missing dep just like that so I actually went back and added it. Removed again.)

> Why is patchfiles-append inside post-extract? I see no reason to do it this way. Just use a plain patchfiles option.

Done.

> look like default values in usual configure scripts, so they can probably be removed as well.

Done. And - thanks. Much tighter.

**Comment by larryv** [comment]
@raimue
> Is this really `GPL-3` and not `GPL-3+`? That would be quite unusual.

Annoyingly, the source files don't appear to include the usual GPL header.

**Comment by kencu** [comment]
Is this one dead too then?

**Comment by kencu** [comment]
Do you think there is anything else that needs to be done with this port before it gets pulled in? I don't think we're going to get any further on the license question than we are now, unless we call in the author.

This is a really simple port. I have about a half dozen more ready to submit that are incredibly more complex than this one.

**Comment by raimue** [comment]
Does closing this imply we should no longer merge it? I understand that waiting for someone to pick that up is tedious. I just did not have the time to test this once more and then merge it to master. Updates to existing ports and infrastructure tasks take precedence for me.

We need to find a way to get more people from @macports/developers to review and merge port submissions to handle them in a timely manner. The [current recommendation](https://guide.macports.org/#project.contributing.new) for tickets is to ping macports-dev when the submission gets stalled. For pull requests, I am now trying to mention the developers team to raise attention.

**Comment by kencu** [comment]
@raimue 
It was just a silly little lark of a thing. I saw it on homebrew and I thought we should have it too. It looked like a 10-second commit. I never imagined it would cause such trouble -- I'm very sorry to have even bothered anyone with something so trivial. You all have much better things to do. Have a Happy Christmas -- sorry to hear about all the troubles recently over in your part of the world. -- K

**Comment by mojca** [comment]
Ken, I still don't understand why you are closing the tickets yourself.

Yes, MacPorts has a huge lack of manpower to maintain tens of thousands of ports + the infrastructure and a way too high number of open tickets, but that doesn't mean that you should close tickets just because handling them takes longer than expected.

By closing tickets you are telling people that they should not ever commit this. (Which is probably the opposite of what you want?)

**Comment by kencu** [comment]
@mojca 
It's not a big thing -- the liblogmich submission was a tiny two-file port, and as you saw, was never going to be accepted because I wrote up the cmake build file for it. The SCONS build file that came with it was a total mess and I wasn't going to spend another minute on that, so I killed that PR to put it out of it's misery.

cpplocate and glbinding turned out to need more work, and both still exist as active trac tickets -- michael looked them over a couple of days ago, and I'll fix them up in short order. I had written up PRs for them thinking they were ready to commit and trying to make it easy for Ryan to do so, but that was an error on my part because 1) Ryan doesn't like PRs anyway, and didn't commit them, and 2) michael found a few more things to buff up, and 3) don't write PRs if there are trac tickets already.


This port, as above, was a silly little thing, and it just sat here forever catching no interest at all, and rightfully so. There was a question about the license. Nobody wants moon-buggy anyway, and I never should have bothered to submit it. Once I realized that, I just dropped it out of embarrassment rather than have it sit here forever and never attract anyone's attention to get around to committing it, because it's so nutty. The working portfile is still up there if anyone really wants it -- but nobody does, and I know that.

Now I do have some good ones -- minetest is ready to go, and apparently it's the #1 most popular open source game on the web. I just fixed a MacOS bug last week that had held it up on homebrew for six months, and I have the portfile sitting in my repo ready to go. My teen-ager is making sure it works right.  Also, I'm just trying to anticipate the issues people might find with it before I put it up for critique, so I don't submit something that will get killed on opening night. And by the way, the OpenGL library I ported in to support it (libirrlicht) has quite a few more similar openGL games written against it, so once those two are in, a bunch more should follow.

Best of the season, -- Ken

**Comment by mojca** [comment]
> the liblogmich submission was a tiny two-file port, and as you saw, was never going to be accepted because I wrote up the cmake build file for it.

That's not true: like I already explained. Yes, it's **generally** favourable to use the same method as upstream and to submit patches upstream, so that we don't need to maintain patches that cause headaches when something changes upstream. But doing otherwise should not be the reason for blocking a submissions.

> cpplocate and glbinding turned out to need more work, and both still exist as active trac tickets /.../ and 3) don't write PRs if there are trac tickets already.

OK, if tickets exists on Trac (and code is not yet ready), that's fine.

> This port, as above, was a silly little thing, and it just sat here forever catching no interest at all

This is a stupid reason for closing a PR.

First of all: **it didn't sit forever**, it was "merely" 24 days. Yes, I admit that this is waaaay too long, but our [oldest open ticket](https://trac.macports.org/ticket/777) is from August 2003. And very recently I committed ports for MinGW to address the ticket that was 3.5 years old (and closed another 5-year old ticket about GCC from MinGW from 2006).

Second: it's not true that nobody was interested. You got two replies suggesting improvements of the code rather than saying that the contribution doesn't make any sense. And one of them with fond memories of the software, willing to accept it. Plus probably others who did not see the ticket or did not leave a "me too" notice. In the case above only 4 people other than me expressed any interest in those 3.5 years, but to me that's one of the very important pieces of software, also present in most linux distributions. There are many important changes that need to be done where I don't get any feedback. Others work on very important pieces of software (software or dependencies of software that I'm using on regular basis) where I don't test anything and/or don't leave any feedback. We have limited time resources.

I don't want to make this thread too long. If you want the ports to be submitted, please reopen the pull requests.

**Pull request closed without merging**
