### PR TITLE
Python PG: add outdated_versions. [RFC]

### PR DESCRIPTION
**Pull request by eborisch**
Any interest in adding an (implemented in this PR) outdated_versions setting to the python PortGroup?

Usage:

```
PortGroup                   python 1.0
[...]
python.outdated_versions    26 36
```

where each listed version will have a stub port with `replaced_by py${python.default_version}-foo` generated.

Or is there an existing and similarly terse approach that I've missed?

### CODE REVIEW

**Comment by eborisch** [comment]
I believe the checks failed because no ports changed. (?)

**Comment by reneeotten** [comment]
> where each listed version will have a stub port with `replaced_by py${python.default_version}-foo` generated.
> 
> Or is there an existing and similarly terse approach that I've missed?

we have stopped doing the `replaced_by` to another subports probably years ago now, so I would say there is no reason to add this. You can use the `obsolete` PG is you want to keep subports for now but warn the enduser that they are obsolete and can/will be removed in the future.

**Comment by eborisch** [comment]
> > where each listed version will have a stub port with `replaced_by py${python.default_version}-foo` generated.
> > Or is there an existing and similarly terse approach that I've missed?
> 
> we have stopped doing the `replaced_by` to another subports probably years ago now, so I would say there is no reason to add this. You can use the `obsolete` PG is you want to keep subports for now but warn the enduser that they are obsolete and can/will be removed in the future.

I recall the -graveyard going away, but I couldn’t recall the discussion around it. We should update the Portfile Recipes (or maybe I missed the section.)

This actually uses the obsolete PG, it just makes it much easier to do in the Portfile by only needing one line.

**Review by jmroot — COMMENTED** [review]
Yeah, I'm inclined to reject this change. This is more or less the functionality of the of the old graveyard ports, implemented a slightly different way. One of the reasons we stopped using them is that setting replaced_by in this way is almost never more useful than simply deleting the subports.

**Comment by eborisch** [comment]
> Yeah, I'm inclined to reject this change. This is more or less the functionality of the of the old graveyard ports, implemented a slightly different way. One of the reasons we stopped using them is that setting replaced_by in this way is almost never more useful than simply deleting the subports.

Fair enough. We’ve (perhaps previously) decided it’s not worth notifying a user when they are stranded on an old flavor, then? (I’m fine if that’s the choice.)

**Comment by jmroot** [comment]
They can find that out like any other removed port, with e.g. `port echo obsolete`.

**Pull request closed without merging**
