### PR TITLE
portaudio: explicit ./configure --options

### PR DESCRIPTION
**Pull request by janstary**
Explicitly disable ALSA and WINAPI and all the other audio output drivers
that do not exist here. Enable option checking while here.

This should be functionally the same, except now `./configure`
does not check for`-lasound`, `linux/soundcard.h`, etc.

Tested on 10.13.2 and 10.6.8 an 10.5.8.

### CODE REVIEW

**Comment by janstary** [comment]
Note that the code that portaudio uses for macOS in `src/hostapi/coreaudio/`
is reported as deprecated even on 10.5.8. This port is rotting (no maintainer).

**Comment by janstary** [comment]
We also have `audio/portaudio/files/patch-audacity-portmixer.diff` from 2011
which patches `pa_linux_alsa.c` and `pa_win_ds` and other code we don't use.
I suppose the patch was blindly taken from Audacity.

**Comment by pmetzger** [comment]
I think I'd still bump the revision number just in case. Given that, I think a merge would be appropriate.

**Comment by janstary** [comment]
Any other opinion about the version bump?

**Comment by pmetzger** [comment]
Apparently not. Do you mind bumping?

**Pull request merged**
