### PR TITLE
wesnoth: Update to 1.14.17 and add a new variant

### PR DESCRIPTION
**Pull request by cooljeanius**
The new variant is to apply the patch from this thread: https://forums.wesnoth.org/viewtopic.php?f=10&t=53824&start=15 
Unfortunately, while updating, I broke `xcode.patch`, though, so I'll want help getting that fixed... (I'm marking it as a draft until I get that fixed)

###### Tested on
macOS 11.5 20G71 x86_64
Xcode 12.5.1 12E507

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [ ] tried a full install with `sudo port -vst install`? (can't because I broke it)
- [ ] tested basic functionality of all binary files? (can't because I broke it)

### CODE REVIEW

**Comment by ryandesign** [comment]
> Unfortunately, while updating, I broke `xcode.patch`, though, so I'll want help getting that fixed... (I'm marking it as a draft until I get that fixed)

I'm sure I tried to update the port in the past and had some difficulty, perhaps with this. Keeping that patch updated is the bulk of the work in updating the port to new versions, so without that work being done, this PR isn't helpful yet.

> The new variant is to apply the patch from this thread: https://forums.wesnoth.org/viewtopic.php?f=10&t=53824&start=15

This patch is nearly a megabyte in size. Certainly, I would have no interest in maintaining such a large patch, so we would have to wait for the original author of the patch to update it for a new version of wesnoth before we could update the port to that new version; that could be limiting. In https://forums.wesnoth.org/viewtopic.php?p=666265#p666265, the original author said "After 6 months from the opening post, it is time for me to take on long break on this" so that doesn't give me hope that future updates to this patch would be forthcoming in a timely fashion.

I see that you've opened an upstream PR where much feedback was provided, and that this patch would not be accepted for the 1.14 branch and would require some reworking to be able to apply to 1.16. If you or the original author or someone can address those issues and get the patch merged into mainline wesnoth code, then it can appear in MacPorts sometime after that.

**Comment by cooljeanius** [comment]
> 
> > The new variant is to apply the patch from this thread: https://forums.wesnoth.org/viewtopic.php?f=10&t=53824&start=15
> 
> This patch is nearly a megabyte in size. Certainly, I would have no interest in maintaining such a large patch, so we would have to wait for the original author of the patch to update it for a new version of wesnoth before we could update the port to that new version; that could be limiting. In https://forums.wesnoth.org/viewtopic.php?p=666265#p666265, the original author said "After 6 months from the opening post, it is time for me to take on long break on this" so that doesn't give me hope that future updates to this patch would be forthcoming in a timely fashion.
> 
> I see that you've opened an upstream PR where much feedback was provided, and that this patch would not be accepted for the 1.14 branch and would require some reworking to be able to apply to 1.16. If you or the original author or someone can address those issues and get the patch merged into mainline wesnoth code, then it can appear in MacPorts sometime after that.

The idea isn't to maintain the patch for future releases, it'd just be a temporary variant for as long as the Wesnoth port is still on 1.14, seeing as the 1.14 branch is no longer receiving updates upstream. I was thinking it could be removed again once there's an upstream release that includes it, but in the meantime it'd be nice to get a build that includes the patch until we can get it merged upstream.

**Comment by reneeotten** [comment]
@ryandesign so is the conclusion to wait until upstream has merged the required patch and then update the port? If so, let's just close this PR until that has happened - there hasn't been any progress here for a few months.

**Comment by reneeotten** [comment]
Closing this PR as there isn't any progress - please re-open once there is a consensus on what to do with it

**Pull request closed without merging**
