### PR TITLE
usd: update to version 20.05

### PR DESCRIPTION
**Pull request by jasonliu--**
#### Description

New variants: `+examples`, `+tutorials`, `+openvdb`. Upstream authors added CMake options to control whether examples and tutorials get included in the final products. Also, initial support for OpenVDB was added in this version.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.11.6 15G22010
Xcode 8.2.1 8C1002

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mf2k — CHANGES_REQUESTED** [review]
Please mention adding the new variants in the commit message.

**Comment by jasonliu--** [comment]
There's a build error when generating the documentation. Adding "WIP" to PR title so that I can get this fixed.

**Comment by jasonliu--** [comment]
Alright, it looks like I've fixed the build error.

**Comment by jasonliu--** [comment]
> Please mention adding the new variants in the commit message.

Done.

**Review by mf2k — APPROVED** [review]

**Pull request merged**
