### PR TITLE
openjdk8-powerpc: update to 8u432

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Also make `openjdk8` a stub on powerpc, otherwise users try installing it and it expectedly fails.

P. S. @breun Please take a look. Hope this is fine, the change in the main port only concerns powerpc. Otherwise I got complaints when someone tried to install it and got a bunch of errors: it is not really evident that one should install `-powerpc` port and not the generic one.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
CI will fails since `openjdk8` does not build now. _This is unrelated to my PR._
It is also broken on buildbots: https://ports.macports.org/port/openjdk8/details

**Comment by breun** [comment]
@barracuda156 I don't see any obvious problems with this particular change.

(It is kind of sad that `openjdk8` is broken, but I don't maintain it and also don't know how to get it fixed.)

**Comment by barracuda156** [comment]
@breun Thank you. This change is inconsequential for me personally, but I rather avoid accidentally wasting hours of someone’s time unnecessarily :) 
I borrowed stub code from `libsdl2`, which has a similar arrangement with powerpc in a separate port (and 10.6 x86 in another).

**Comment by barracuda156** [comment]
@herbygillot @reneeotten Could someone merge this please? Failures on arm64 are unrelated.

**Pull request merged**
