### PR TITLE
tomcat-native: update to version 1.2.21

### PR DESCRIPTION
**Pull request by mattbishop**
#### Description
Update to version 1.2.21 tomcat-native.

###### Type(s)
- [X] bugfix

###### Tested on
macOS 10.13.6 17G5019
Xcode 10.1 10B61 

###### Verification
Have you

- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?

### CODE REVIEW

**Comment by mattbishop** [comment]
I don't have Xcode 10.2 to try to build and figure out why this is failing.

**Comment by pmetzger** [comment]
Error seems to be:

```
checking for JDK os include directory... Cannot find jni_md.h in /System/Library/Frameworks/JavaVM.framework/
```

**Comment by mf2k** [comment]
This fails on the builders due to:

`Error: Unable to open port: can't read "(/usr/libexec/java_home)": no such variable
`

I'm guessing this is the result if java is not installed on the system. You need to account for that with an error message to the user requesting that they install java.

**Comment by mattbishop** [comment]
@pmetzger @mf2k This PR is ready for merging.

**Comment by mf2k** [comment]
Done. Thank you!

**Pull request merged**
