### PR TITLE
postfix: Bugfix manpage files

### PR DESCRIPTION
**Pull request by essandess**
postfix: Bugfix manpage files
* Fix issue where `postfix set-permissions` fails because MacPorts compresses manpages to .gz files
* Provide troubleshooting notes for issues like incorrect logfile permissions (specified by user main.cf)

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 13.1 22C65 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by herbygillot** [comment]
Can we address the `port lint` warning: `port lint postfix:
Warning: missing recommended checksum type: size`

...and add the `size` checksum, if even as a 2nd commit?

**Comment by essandess** [comment]
> Can we address the `port lint` warning: `port lint postfix: Warning: missing recommended checksum type: size`
> 
> ...and add the `size` checksum, if even as a 2nd commit?

Thanks, fixed, along with other minor whitespace and lint fixes.

**Comment by herbygillot** [comment]
Thanks @essandess. Let's wait for @jmroot to review.

**Comment by jmroot** [comment]
I'll fix this a different way. It's not desirable for postfix to be changing the permissions of files managed by the package manager in the first place.

**Comment by essandess** [comment]
> I'll fix this a different way. It's not desirable for postfix to be changing the permissions of files managed by the package manager in the first place.

I understand the logic, but however this is fixed, the standard command `postfix set-permissions` must work.

Postfix is a complex, configurable environment with multiple user-specified `.cf` files beyond what's installed by the package manager. If anything ever gets out of whack, users must be able to run `postfix set-permissions` for their own environment.

**Comment by essandess** [comment]
> I'll fix this a different way. It's not desirable for postfix to be changing the permissions of files managed by the package manager in the first place.

@jmroot This `postfix` issue is still broken, and breaks `postfix` after every update. I just had my own MDA silently down for several days because of this issue.

The logfile permissions must be set by hand after every update:

> ```sh
> sudo chown _postfix:mail /opt/local/var/log/mail/postfix.log
> ```

This is impracticable for a deployed mail server—the MacPorts Portfile must take care of this automatically. If not the code in this PR, what solution do you propose?

**Comment by essandess** [comment]
Also, thank you for addressing the `postfix set-permissions` issue in the latest update: https://github.com/macports/macports-ports/commit/69c9ad36dc23a8b6da2f4ffc91dcc310ec03c19c

There is still some issue with logfile permissions being broken through an update. I’ll try to track that down and post a trac issue.

I recommend that the troubleshooting guidance be added to notes:

```sh
postfix set-permissions
superpost -sv
```

**Pull request closed without merging**
