### PR TITLE
Per issue 60156 - patch app.vala to build with newer vala in macports

### PR DESCRIPTION
**Pull request by brad-x**
https://trac.macports.org/ticket/60156

### CODE REVIEW

**Comment by mf2k** [comment]
The commit message needs to updated to [follow the guidelines](https://trac.macports.org/wiki/CommitMessages). You need to begin with the port name and add a reference to the Trac ticket.

**Comment by brad-x** [comment]
> The commit message needs to updated to [follow the guidelines](https://trac.macports.org/wiki/CommitMessages). You need to begin with the port name and add a reference to the Trac ticket.

I've updated the commit message

**Comment by mf2k** [comment]
Please squash the commits into 1 and force push.

**Comment by mf2k** [comment]
Looks good. Let's give Dave some time to look at this.

**Comment by dbevans** [comment]
You might update the PR title as well as I didn't understand that this about vte until now.  Testing the PR now.

**Comment by dbevans** [comment]
Works for me.  Thanks for the PR.

**Pull request merged**
