### PR TITLE
various Python ports: update to latest version

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
This PR updates a variety of Python ports to their latest version.

###### Tested on
macOS 10.14.6 18G95
Xcode 10.3 10G8

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`? 
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by tobypeterson** [comment]
I'm not sure this (multiple ports in one PR) is the best approach for updating python ports, especially ones with different maintainers.

**Comment by reneeotten** [comment]
> I'm not sure this (multiple ports in one PR) is the best approach for updating python ports, especially ones with different maintainers.

Perhaps, but it's certainly better for me than to open seven different PRs. More importantly, there is no difference in amount of work for the assigned maintainer in either of the two cases and I am happy to wait for the 72-hours time period. Finally, experience from the past shows that (with the exeception of @g5pw) the maintainers listed here are very unlikely to respond to PRs anyway.

I'll wait a bit longer and merge this at some point during the weekend.

**Comment by g5pw** [comment]
Thank you for this PR, @reneeotten, I agree that it's sometime simpler to update python ports in batches. I have a question about my port, added inline :)

**Comment by reneeotten** [comment]
> Thank you for this PR, @reneeotten, I agree that it's sometime simpler to update python ports in batches. I have a question about my port, added inline :)

sure, ask away ;) You likely forgot to submit the review though because I don't see anything inline..

**Comment by g5pw** [comment]
I have to say, the GitHub review in the middle of a discussion is not really intuitive at all. Anyway, I requested a review before I submitted my comment, you'll find it somewhere above. 😃

**Comment by reneeotten** [comment]
> I have to say, the GitHub review in the middle of a discussion is not really intuitive at all. Anyway, I requested a review before I submitted my comment, you'll find it somewhere above. 😃

I only see the review in the e-mail notification... but anyway. There is a comment about why Python 3.4 is singled out there - we've been removing py34 subports and I don't want to add them again for only testing this port.

**Comment by g5pw** [comment]
Oh, I see. I think we should perhaps just remove py34-six then...

**Comment by reneeotten** [comment]
> Oh, I see. I think we should perhaps just remove py34-six then...

that still has some dependencies last time I checked. I would just like to merge this and we can deal with that later... if that's okay with you.

**Comment by g5pw** [comment]
Sure, it’s fine by me!


Aljaž Srebrnič

Sent from mobile
-- --
My public key: https://g5pw.me/key

**Comment by reneeotten** [comment]
> Sure, it’s fine by me! 

okay, it' actually only one dependency left... so I'll resolve that and then remove the py34-six subport before merging this PR later today

**Comment by g5pw** [comment]
Thanks for your work @reneeotten!

**Pull request merged**
