### PR TITLE
webkit-sharp: remove outdated port

### PR DESCRIPTION
**Pull request by dbevans**
* no dependents
* depends on deprecated webkit-gtk/webkit-gtk-2.0
* github repo is now archived/readonly

See https://trac.macports.org/ticket/52398
Closes https://trac.macports.org/ticket/52399

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.3 18D42
Xcode 10.1 10B61 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM.

**Comment by dbevans** [comment]
Waiting for comment from @ryandesign.

**Comment by pmetzger** [comment]
@dbevans He doesn't seem to be commenting.

**Comment by dbevans** [comment]
Yes, but I would like to get the thumbs up from him since he is the maintainer and has, in general, expressed a reticence to remove outdated ports.  But it's OK with me if you want to go ahead.

> @dbevans He doesn't seem to be commenting.

Yes, but it would be nice to get the thumbs up from him since he is the maintainer and has, in general, expressed a reticence to remove outdated ports.  But it's been some time now, so I'm OK with going ahead if you want to. @ryandesign ?

**Comment by pmetzger** [comment]
@dbevans I'll let you merge it; I think if he wanted to comment he would have.

**Pull request merged**
