### PR TITLE
trash: Fix build on Lion and older

### PR DESCRIPTION
**Pull request by dgelessus**
The original code uses the `NSByteCountFormatter` class, which only exists in Mountain Lion and later. To allow running on older systems, the code checks at runtime whether the class exists, and uses a fallback implementation otherwise. However because this is purely a runtime check, *compiling* the code still requires the `NSByteCountFormatter` header, which breaks builds on Lion and older.

This change adds a compile-time version check for building with a pre-10.8 SDK, in which case the fallback implementation without `NSByteCountFormatter` is always used.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.7
Xcode 4.6.3

macOS 10.14
Xcode 11.0

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] ~~referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?~~ (n/a)

- [x] checked your Portfile with `port lint`?
- [x] ~~tried existing tests with `sudo port test`?~~ (n/a)
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
This is heading in the right direction, and thanks!

If you want to enable/disable bits of code based on the SDK that you are building against, the right macro is MAC_OS_X_VERSION_MAX_ALLOWED. I know this is a bit confusing, and you see this done different ways on the internet. Chris Espinosa, who is/was in charge of this at Apple, outlines it here: <https://lists.apple.com/archives/xcode-users/2005/Aug/msg00399.html>.

Because of various differences in the way the system is defined, we usually (always) just use the system version number.

So the proper test would be:

```
#if MAC_OS_X_VERSION_MAX_ALLOWED >= 1080
      if (NSClassFromString(@"NSByteCountFormatter")) {
          return [NSByteCountFormatter
              stringFromByteCount: aSize
              countStyle: NSByteCountFormatterCountStyleFile];
      }
#endif
```

The only Availability header that is always available is "AvailabilityMacros.h", I believe.

Sometimes, you don't want to worry about whether `AvailablityMacros.h` has been included. If you're prepared to support building the software to match to deployment target set in build line by the compiler (which is almost all cases on MacPorts matches the system that you are currently building on), you can use this construction:
```
#if __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ >= 1080
```

That macro is set by (AFAIK) every compiler on macOS/MacOSX/Darwin and can be relied upon to be available. Dunno about compilers like nasm or similar, though.

**Comment by dgelessus** [comment]
Ah, thanks for the link - that explanation is quite helpful. You're right - the right macro to check here is `MAX_ALLOWED` (≈ SDK version), as the `#if` is meant to guard against a missing header (and the runtime check following it makes sure that the class is only used if it actually exists at runtime). I'll adjust the patch.

In this case I've worked around the missing header problem by conditionally including `<Availability.h>` only if it exists, and then checking that the `MAX_ALLOWED` macro is defined before using it. (If the header doesn't exist, the macro is undefined, so the guard always evaluates to false.)

PS: I recognized Chris Espinosa's name from some folklore.org stories, so I looked him up. Apparently he's been at Apple almost since the beginning and is still working there today. Seems fitting that he would know a few things about version compatibility macros. :)

**Comment by kencu** [comment]
But your way, using Availability.h, will fail on Tiger. And then we'll have to switch it to AvailabilityMacros.h later on anyway.

**Comment by dgelessus** [comment]
Hm, I'll need to check that again. IIRC I based this on a check that MacPorts patches into clang, and that check seems to be working fine on Tiger (without `<Availability.h>`).

(I tried building `trash` on Tiger with this patch before, but it failed for reasons unrelated to this version check. IIRC it had something to do with how `trash` communicates with the Finder via Apple Events.)

**Comment by kencu** [comment]
you could test for and use Availability.h if it exists, and fallback to AvailabilityMacros.h if it doesn't.

So far, I am not aware of any reason why doing this would he better in any way than just including AvailabilityMacros.h, but I am always seeking enlightenment!

Indeed, if the software can never work on Tiger, the point is moot.

**Comment by kencu** [comment]
This should work. The test will fail if <Availability.h> does not exist anyway, as it does not exist on Tiger.

**Pull request merged**
