### PR TITLE
py-oci-cli, oci-cli_select: submission

### PR DESCRIPTION
**Pull request by linuxgemini**
This PR adds the `py-oci-cli` and `oci-cli_select` packages.

This package pair is for the Oracle Cloud Infrastructure CLI, utilizing the SDK package `py-oci`.

The Python package is version-limited to 3.8 and 3.9 as these are currently (as of commit date) officially supported by Oracle.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.0 23A344 arm64
Xcode 15.0.1 15A507

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
@reneeotten Could you review the python bits here? You're the domain expert.

**Comment by pmetzger** [comment]
@reneeotten ?

**Comment by reneeotten** [comment]
> @reneeotten ?

sorry, I forgot about this - will take a look tonight and finish this up.

**Comment by pmetzger** [comment]
@reneeotten Just a friendly ping. (I've been away for a few days myself given the holidays.)

**Comment by reneeotten** [comment]
@linuxgemini from the description and upstream repository it appears to me that port falls in the category "not likely to be used as a Python module, but it's a package written in Python". 
In that case I think it's preferable to have it added as `oci-cli` and not add subports for it; that also avoids the need for a `*-select` package as it will just install for only one version.

If that observation is correct, then please change accordingly and update at the same time to the latest upstream version. Ideally, all port should use MacPorts' default Python version, which is currently 3.11; so if that works, then please use it; if not you can keep it as Python 3.9.

**Comment by linuxgemini** [comment]
heya, so sorry for the delay; i've applied your recommendations and the scope of the package changed a bit (moved the cli package under net) so i'll do a sdk update + new pr for this. jsyk.

**Pull request closed without merging**
