### PR TITLE
miniserve: Update to 0.19.1

### PR DESCRIPTION
**Pull request by judaew**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by judaew** [comment]
Hi @herbygillot, I get the following error:

```console
:info:extract Adding mime_guess-ac76840e14bc6f2f7cbbb347052ec7e4de7e3043.tar.gz from github to cargo home
:debug:extract system -W /opt/local/var/macports/build/_opt_local_var_macports_sources_github.com_judaew_macports-ports_net_miniserve/miniserve/work/.home/.cargo/macports: /usr/bin/tar -xf /opt/local/var/macports/distfiles/cargo-crates/mime_guess-ac76840e14bc6f2f7cbbb347052ec7e4de7e3043.tar.gz
:error:extract Failed to extract miniserve: can't read "cversion": no such variable
:debug:extract Error code: NONE
:debug:extract Backtrace: can't read "cversion": no such variable
```

I think the problem is somewhere in the `cargo_fetch` PG. The `mime_guess` package uses the `cargo.crates_github` option.

**Comment by herbygillot** [comment]
> Hi @herbygillot, I get the following error:
> 
> ```
> :info:extract Adding mime_guess-ac76840e14bc6f2f7cbbb347052ec7e4de7e3043.tar.gz from github to cargo home
> :debug:extract system -W /opt/local/var/macports/build/_opt_local_var_macports_sources_github.com_judaew_macports-ports_net_miniserve/miniserve/work/.home/.cargo/macports: /usr/bin/tar -xf /opt/local/var/macports/distfiles/cargo-crates/mime_guess-ac76840e14bc6f2f7cbbb347052ec7e4de7e3043.tar.gz
> :error:extract Failed to extract miniserve: can't read "cversion": no such variable
> :debug:extract Error code: NONE
> :debug:extract Backtrace: can't read "cversion": no such variable
> ```
> 
> I think the problem is somewhere in the `cargo_fetch` PG. The `mime_guess` package uses the `cargo.crates_github` option.

I notice the same issue is happening in the previous version of `miniserve` as well.  Why this is happening wasn't clear to me at first glance, will revisit.  BTW doesn't `mime_guess` also need to be updated as part of this change? The change that this Portfile was waiting on in `mime_guess` has been merged.

**Comment by judaew** [comment]
> I notice the same issue is happening in the previous version of miniserve as well. Why this is happening wasn't clear to me at first glance, will revisit.

There was no problem in the previous version here you can see that we have a pre-built package for 0.18.0: http://packages.macports.org/miniserve/. But now it's broken.

> The change that this Portfile was waiting on in mime_guess has been merged.

The PR has been merged, but the author of `mime_guess` still hasn't released a new version. See https://github.com/abonander/mime_guess/issues/68. Therefore, in any case for port need to get `mime_guess` from GitHub.

**Comment by svenstaro** [comment]
FYI I just released miniserve 0.19.1 which builds the released version of mime_guess.

**Comment by judaew** [comment]
@svenstaro This is great news, thanks!

**Comment by harens** [comment]
> Hi @herbygillot, I get the following error:
> 
> ```
> :info:extract Adding mime_guess-ac76840e14bc6f2f7cbbb347052ec7e4de7e3043.tar.gz from github to cargo home
> :debug:extract system -W /opt/local/var/macports/build/_opt_local_var_macports_sources_github.com_judaew_macports-ports_net_miniserve/miniserve/work/.home/.cargo/macports: /usr/bin/tar -xf /opt/local/var/macports/distfiles/cargo-crates/mime_guess-ac76840e14bc6f2f7cbbb347052ec7e4de7e3043.tar.gz
> :error:extract Failed to extract miniserve: can't read "cversion": no such variable
> :debug:extract Error code: NONE
> :debug:extract Backtrace: can't read "cversion": no such variable
> ```
> 
> I think the problem is somewhere in the `cargo_fetch` PG. The `mime_guess` package uses the `cargo.crates_github` option.

Just ran into this now on a port I'm working on. The error comes from this procedure:

https://github.com/macports/macports-ports/blob/6c8ae331b5ff17cccc7bb5ac85d89d66e46dcbb6/_resources/port1.0/group/cargo_fetch-1.0.tcl#L156-L166

More specifically, the last line references `cversion` which doesn't exist for github crates. It was added in https://github.com/macports/macports-ports/commit/8f43fdc08107e2f7fa6527eaae8ba0ea3f35b6c0 with the purpose of modifying the `crypto-hash` and `curl-sys` dependencies if they exist. 

I think the easiest fix would be to remove this line and assume that if these dependencies are being fetched, it would be from cargo and not github. There might be a better solution however that I'm missing. Thoughts? CC @catap

**Pull request merged**
