### PR TITLE
Ruby: new ports: glib2 and gobject bindings

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

New ports with Gnome bindings.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 14.4.1
Xcode 15.3

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@ryandesign Ryan, is this again that bug in CI setup?
```
  Building native extensions. This could take a while...
  ERROR:  Error installing /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_ruby_rb-atk/rb32-atk/work/atk-4.2.1/atk.gem:
  	ERROR: Failed to build gem native extension.
  
      current directory: /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_ruby_rb-atk/rb32-atk/work/destroot/opt/local/lib/ruby3.2/gems/3.2.0/gems/atk-4.2.1/dependency-check
  /opt/local/bin/rake3.2 RUBYARCHDIR\=/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_ruby_rb-atk/rb32-atk/work/destroot/opt/local/lib/ruby3.2/gems/3.2.0/extensions/arm64-darwin-23/3.2.0/atk-4.2.1 RUBYLIBDIR\=/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_ruby_rb-atk/rb32-atk/work/destroot/opt/local/lib/ruby3.2/gems/3.2.0/extensions/arm64-darwin-23/3.2.0/atk-4.2.1
  installing 'atk' native package... error deleting "/opt/local/var/macports/home/Library/Preferences/com.apple.dt.Xcode.plist": not owner
      while executing
  "file delete -force "${target_dir}/com.apple.dt.Xcode.plist""
      (procedure "macports::copy_xcode_plist" line 5)
      invoked from within
  "macports::copy_xcode_plist $env(HOME)"
      (procedure "mportinit" line 654)
      invoked from within
  "mportinit ui_options global_options global_variations"
  Error: /opt/local/bin/port: Failed to initialize MacPorts, error deleting "/opt/local/var/macports/home/Library/Preferences/com.apple.dt.Xcode.plist": not owner
  installing 'atk' native package... failed
  failed
  Failed to run 'port install -y atk'.
  Failed to run 'port install -y atk'.
```

Locally on Sonoma the package installs fine in trade mode. I have no idea why it should fail on CI.

**Comment by barracuda156** [comment]
@herbygillot This is ready now.

**Comment by herbygillot** [comment]
Nitpick: `rb-cairo: update to 1.17.13` seems like it should `rb-cairo: new port` instead

**Comment by barracuda156** [comment]
> Nitpick: `rb-cairo: update to 1.17.13` seems like it should `rb-cairo: new port` instead

Yes and no. We did not have a port with this name, but we have this: https://ports.macports.org/port/rb-rcairo (which is why I retained original maintainer for it).

By the way, let me delete those older ports, they have no dependents, so it is safe.

**Pull request merged**
