### PR TITLE
security/signify: update to 1.4

### PR DESCRIPTION
**Pull request by jpouellet**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.13
"Apple LLVM 9.1.0"

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

[skip notification]

### CODE REVIEW

**Comment by ryandesign** [comment]
> Port signify **fail** on xcode7.3. [Log](https://paste.macports.org/70c358210737)

```
src/usr.bin/signify/signify.c:264:15: error: use of undeclared identifier 'RPP_STDIN'
```

**Comment by jpouellet** [comment]
Yeah, that's expected. I'm the upstream author too. RPP_STDIN is a flag to readpassphrase(3) which was only introduced in OS X 10.12. Prior to that I was including a version of readpassphrase from OpenBSD's libc, but dropped that compat/portability shim now that it's in OS X.

I could add a ./configure-like thing to detect if it's present or not, but I'd rather not have to unless someone actually wants/needs it because it makes the common case more complex and requires more effort for 3rd parties to audit.

Would it be okay to just drop support for pre-10.12? If not I can go add support for it upstream.

**Comment by mf2k** [comment]
It is your call on that. Officially Macports supports the current and prior two (2) versions of macOS, but I cannot currently find where that is documented. Many port maintainers do support older versions of macOS however.

**Comment by kencu** [comment]
perhaps it would be more comprehensive to add the functionality once to the legacy support PG, instead of individually to each port.

**Comment by pmetzger** [comment]
@kencu Would you like to add the functionality to legacy support and then we can merge this?

**Comment by kencu** [comment]
IMHO - go ahead and merge this, and we'll add to the legacy-support PG in a bit.

**Comment by pmetzger** [comment]
Merged per @kencu. Thanks for the update, @jpouellet!

**Pull request merged**
