### PR TITLE
re2: update to 2024-02-01

### PR DESCRIPTION
**Pull request by herbygillot**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with ~`sudo port -vst install`~ `sudo port -d destroot`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by pmetzger** [comment]
@herbygillot Any idea what went wrong in the CI?

**Comment by herbygillot** [comment]
> @herbygillot Any idea what went wrong in the CI?

The `py*-grpcio*` ports are failing to build, however they look as if they've been failing even before this change:

- https://ports.macports.org/port/py38-grpcio/details/
- https://ports.macports.org/port/py39-grpcio/details/
- https://ports.macports.org/port/py310-grpcio/details/

**Comment by herbygillot** [comment]
`grpc` and the other ports seem as if they successfully built against the updated `re2`.

**Comment by pmetzger** [comment]
If they were already broken, probably commit this and put in a ticket for the broken ports? (BTW, it's long past time that we moved to using Github for tickets. As nice as Trac was, it's now an impediment.)

**Pull request merged**
