### PR TITLE
Follow up update blender-related ports

### PR DESCRIPTION
**Pull request by catap**
#### Description

Here I'm fixing things which was missed at https://github.com/macports/macports-ports/pull/16893

###### Type(s)

- [x] bugfix

###### Tested on

macOS 10.7.5 11G63 x86_64
Xcode 4.6.3 4H1503

macOS 10.11.6 15G22010 x86_64
Xcode 7.3.1 7D1014

macOS 13.0.1 22A400 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?

### CODE REVIEW

**Comment by catap** [comment]
BTW some ports are used OpenBLAS and it requires fixes from https://github.com/macports/macports-ports/pull/18459

**Comment by catap** [comment]
OpenBLAS has successfully builded everywhere. It can be merged.

**Review by mascguy — APPROVED** [review]
LGTM.

@MarcusCalhoun-Lopez and @jasonliu-- ?

**Comment by jasonliu--** [comment]
Also LGTM. 👍

**Comment by mascguy** [comment]
> Also LGTM. 👍

Great, thanks for reviewing Jason! Merging.

**Pull request merged**
