### PR TITLE
p5-datemanip: update 6.72, rename to p5-date-manip

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description

Note: p5-test-inter was moved from ~~depends_test to depends_build~~ **depends_build to depends_test** since the only files needing it are t/*.t 
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.5 17F77
Xcode 9.4 9F1027a

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] ~~referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?~~

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?

<details><summary>Full test results:</summary>
<pre>
--->  Testing p5.26-date-manip
Executing:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_github.com_macports_macports-ports_perl_p5-date-manip/p5.26-date-manip/work/Date-Manip-6.72" && /usr/bin/make test
PERL_DL_NONLAZY=1 "/opt/local/bin/perl5.26" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/base._calc_date_ymwd.t .................. ok
t/base._config.t .......................... ok
t/base._critical_date.t ................... ok
t/base._fix_year.50.t ..................... ok
t/base._fix_year.c.t ...................... ok
t/base._fix_year.c18.t .................... ok
t/base._fix_year.c1890.t .................. ok
t/base.calc_date_date.t ................... ok
t/base.calc_date_days.t ................... ok
t/base.calc_date_delta.t .................. ok
t/base.calc_date_time.t ................... ok
t/base.calc_time_time.t ................... ok
t/base.check.t ............................ ok
t/base.cmp.t .............................. ok
t/base.day_of_week.t ...................... ok
t/base.day_of_year.0.t .................... ok
t/base.day_of_year.1.t .................... ok
t/base.days_in_month.t .................... ok
t/base.days_in_year.t ..................... ok
t/base.days_since_1bc.t ................... ok
t/base.join.t ............................. ok
t/base.leapyear.t ......................... ok
t/base.nth_day_of_week.t .................. ok
t/base.secs_since_1970.t .................. ok
t/base.split.t ............................ ok
t/base.week1_day1.t ....................... ok
t/base.week_of_year.0.t ................... ok
t/base.week_of_year.1.t ................... ok
t/base.weeks_in_year.t .................... ok
t/date.calc.data_date_bsemi.t ............. ok
t/date.calc.date_date_approx.t ............ ok
t/date.calc.date_date_bapprox.t ........... ok
t/date.calc.date_date_business.t .......... ok
t/date.calc.date_date_exact.t ............. ok
t/date.calc.date_date_semi.t .............. ok
t/date.calc.date_delta.romanian.t ......... ok
t/date.calc.date_delta_approx.t ........... ok
t/date.calc.date_delta_business.0.t ....... ok
t/date.calc.date_delta_business.1.t ....... ok
t/date.calc.date_delta_business.2.t ....... ok
t/date.calc.date_delta_business.3.t ....... ok
t/date.calc.date_delta_business.4.t ....... ok
t/date.calc.date_delta_business.french.t .. ok
t/date.calc.date_delta_exact.t ............ ok
t/date.cmp.t .............................. ok
t/date.complete.t ......................... ok
t/date.convert.t .......................... ok
t/date.holiday.0.t ........................ ok
t/date.holiday.1.t ........................ ok
t/date.init_args.t ........................ ok
t/date.is.t ............................... ok
t/date.is_business_day.t .................. ok
t/date.list_events.0.t .................... ok
t/date.list_events.1.t .................... ok
t/date.list_holidays.0.t .................. ok
t/date.list_holidays.1.t .................. ok
t/date.list_holidays.2.t .................. ok
t/date.list_holidays.3.t .................. ok
t/date.list_holidays.4.t .................. ok
t/date.nearest_business_day.t ............. ok
t/date.next.t ............................. ok
t/date.next_business_day.t ................ ok
t/date.parse.catalan.t .................... ok
t/date.parse.common.t ..................... ok
t/date.parse.danish.t ..................... ok
t/date.parse.delta.t ...................... ok
t/date.parse.dst.t ........................ ok
t/date.parse.dutch.t ...................... ok
t/date.parse.english.t .................... ok
t/date.parse.french.t ..................... ok
t/date.parse.holidays.t ................... ok
t/date.parse.invalid.t .................... ok
t/date.parse.iso.t ........................ ok
t/date.parse.italian.t .................... ok
t/date.parse.misc.0.t ..................... ok
t/date.parse.misc.1.t ..................... ok
t/date.parse.mmmyyyy.first.t .............. ok
t/date.parse.mmmyyyy.last.t ............... ok
t/date.parse.mmmyyyy.t .................... ok
t/date.parse.period.t ..................... ok
t/date.parse.polish.t ..................... ok
t/date.parse.portuguese.t ................. ok
t/date.parse.romanian.t ................... ok
t/date.parse.russian.cp1251.t ............. ok
t/date.parse.russian.koi8-r.t ............. ok
t/date.parse.russian.t .................... ok
t/date.parse.spanish.t .................... ok
t/date.parse.swedish.t .................... ok
t/date.parse.timezone.t ................... ok
t/date.parse.turkish.t .................... ok
t/date.parse_date.common.t ................ ok
t/date.parse_date.iso.t ................... ok
t/date.parse_date.misc.0.t ................ ok
t/date.parse_date.misc.1.t ................ ok
t/date.parse_date.mmmyyyy.first.t ......... ok
t/date.parse_date.mmmyyyy.last.t .......... ok
t/date.parse_date.mmmyyyy.t ............... ok
t/date.parse_format.0.t ................... ok
t/date.parse_format.1.t ................... ok
t/date.parse_time.t ....................... ok
t/date.prev.t ............................. ok
t/date.prev_business_day.t ................ ok
t/date.printf.0.t ......................... ok
t/date.printf.1.t ......................... ok
t/date.secs_since_1970_GMT.0.t ............ ok
t/date.secs_since_1970_GMT.1.t ............ ok
t/date.set.0.t ............................ ok
t/date.set.1.t ............................ ok
t/date.set.2.t ............................ ok
t/date.set.3.t ............................ ok
t/date.week_of_year.0.t ................... ok
t/date.week_of_year.1.t ................... ok
t/delta.calc.delta_delta_approx.t ......... ok
t/delta.calc.delta_delta_business.0.t ..... ok
t/delta.calc.delta_delta_business.1.t ..... ok
t/delta.calc.delta_delta_semi.t ........... ok
t/delta.cmp.t ............................. ok
t/delta.convert.t ......................... ok
t/delta.init_args.t ....................... ok
t/delta.is.t .............................. ok
t/delta.parse.fract.t ..................... ok
t/delta.parse.t ........................... ok
t/delta.printf.t .......................... ok
t/delta.set.1.t ........................... ok
t/delta.set.2.t ........................... ok
t/delta.set.3.t ........................... ok
t/delta.type.t ............................ ok
t/delta.value.t ........................... ok
t/dm5.convtz.t ............................ skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date.t .............................. skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_date_0.t ....................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_date_1.t ....................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_date_2a.t ...................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_date_2b.t ...................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_delta_0.t ...................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_delta_1.t ...................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_delta_2a.t ..................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_delta_2b.t ..................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_delta_french.t ................. skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_delta_sign.t ................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_french.t ....................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_german.t ....................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_misc_a.t ....................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_misc_b.t ....................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_romanian.t ..................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_today_0.t ...................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.date_today_1.t ...................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.delta_a.t ........................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.delta_b.t ........................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.delta_delta_0.t ..................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.delta_delta_1.t ..................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.delta_delta_2a.t .................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.delta_delta_2b.t .................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.delta_format.t ...................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.delta_romanian.t .................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.events.t ............................ skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.getnext.t ........................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.getprev.t ........................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.normalize_business.t ................ skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.nthday.t ............................ skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.recur_0.t ........................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.recur_1.t ........................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.settime.t ........................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/dm5.unixdate.t .......................... skipped: Date::Manip 5.xx tests ignored (set DATE_MANIP_TEST_DM5 to test)
t/obj.t ................................... ok
t/orig.convtz.t ........................... ok
t/orig.date_isholiday.t ................... ok
t/orig.datecalc.date_date.t ............... ok
t/orig.datecalc.date_delta.0.t ............ ok
t/orig.datecalc.date_delta.1.t ............ ok
t/orig.delta_format.t ..................... ok
t/orig.eventslist.t ....................... ok
t/orig.getnext.t .......................... ok
t/orig.getprev.t .......................... ok
t/orig.nthdayofyear.t ..................... ok
t/orig.parsedatedelta.t ................... ok
t/orig.parsedateformat.t .................. ok
t/orig.parsedatestring.t .................. ok
t/orig.parserecur.t ....................... ok
t/orig.settime.t .......................... ok
t/orig.unixdate.t ......................... ok
t/pod.t ................................... skipped: Author tests not required for installation
t/pod_coverage.t .......................... skipped: Author tests not required for installation
t/recur.dates.0.t ......................... ok
t/recur.dates.1.t ......................... ok
t/recur.dates.2.t ......................... ok
t/recur.dates.3.t ......................... ok
t/recur.frequency.t ....................... ok
t/recur.init_args.t ....................... ok
t/recur.is.t .............................. ok
t/recur.nth.t ............................. ok
t/tz.all_periods.t ........................ ok
t/tz.convert.t ............................ ok
t/tz.convert_from_gmt.t ................... ok
t/tz.convert_to_gmt.t ..................... ok
t/tz.date_period.t ........................ ok
t/tz.define_abbrev.t ...................... ok
t/tz.define_alias.t ....................... ok
t/tz.define_offset.t ...................... ok
t/tz.periods.t ............................ ok
t/tz.zone.t ............................... ok
t/tzdata._ruleinfo.t ...................... ok
t/tzdata._zoneinfo.t ...................... ok
All tests successful.
Files=203, Tests=3685, 56 wallclock secs ( 0.85 usr  0.54 sys + 42.65 cusr  7.93 csys = 51.97 CPU)
Result: PASS
</pre></details><br />

- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mf2k** [comment]
All of the ports that depend on p5.26-datemanip will also need to be updated. I see these:

```
gnucash                         
gnucash-devel                   
gnupod                          
log2timeline                    
mythtv-core.27                  
mythtv-core.28                  
mythtv-plugins.27               
mythtv-plugins.28               
p5-datemanip                    
p5.26-astro-app-satpass2        
p5.26-finance-quotehist         
p5.26-gedcom                    
p5.26-libxml-enno               
p5.26-www-search                
sleuthkit                       
imapsync                        
```

Should updating them also be part of this PR?

**Comment by pmetzger** [comment]
@mf2k Just a side note, I find the need to bump `revision` on dependents tiresome. It really would be nice to have an automated way to handle this someday.

**Comment by chrstphrchvz** [comment]
@mf2k Thanks for catching that, I thought I had searched for dependent ports but didn't do so correctly. I had used `port echo depends:p5-datemanip` instead of `port echo depends:p5.26-datemanip`.

**Comment by chrstphrchvz** [comment]
@mf2k Three of the maintainers are @ctreleaven (mythtv.27 and mythtv.28), @drkp (gnucash), and @dbevans (p5-astro-app-satpass2). The last one doesn't have a github handle specified: worldnet.att.net:james.toth (p5-gedcom)

**Comment by chrstphrchvz** [comment]
According to [a search on Trac](https://trac.macports.org/search?q=james.toth) I don't believe the maintainer of p5-gedcom (and p5-roman) has been active in 13 years.

**Comment by mf2k** [comment]
Thanks for looking into that. I created a port abandoned ticket for him:

https://trac.macports.org/ticket/56654

**Comment by ctreleaven** [comment]
Appears OK to me.

**Comment by mf2k** [comment]
An email to worldnet.att.net:james.toth bounced, so that is a thumbs up from him in absentia!

**Comment by drkp** [comment]
LGTM

**Comment by pmetzger** [comment]
@mf2k I was not under the impression you needed permission to do a rev bump on someone's port to deal with a dependency update. Am I mistaken?

**Comment by mojca** [comment]
Generally increasing the revision number doesn't need approval from maintainer. But for tricky cases like poppler or ICU update (or any other similar case for that matter) where an updated dependency has a high chance of breaking the port, or when the dependent port is something heavy like Qt, it's at least polite to notify the maintainers and give them a chance to test or maybe include something else in the same revbump.

Except for renaming issue which needs to be tested by the submitter (and reviewer), updating a perl module is usually a trivial issue, so there should be no formal need to wait for everyone's approval.

**Pull request merged**
