### PR TITLE
po4a: update to 0.73

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by i0ntempest** [comment]
It looks like the system Perl is slipping in, as can be seen from the include paths:
`po4a::chooser: Module loading error: Can't locate Pod/Parser.pm in @INC (you may need to install the Pod::Parser module) (@INC contains: lib /Library/Perl/5.34/darwin-thread-multi-2level /Library/Perl/5.34 /Network/Library/Perl/5.34/darwin-thread-multi-2level /Network/Library/Perl/5.34 /Library/Perl/Updates/5.34.1 /System/Library/Perl/5.34/darwin-thread-multi-2level /System/Library/Perl/5.34 /System/Library/Perl/Extras/5.34/darwin-thread-multi-2level /System/Library/Perl/Extras/5.34) at lib/Locale/Po4a/Pod.pm line 14.`
I tried to patch the system Perl out to no avail. Need a bit of help here.

**Comment by ryandesign** [comment]
> ```
> po4a::chooser: Module loading error: Can't locate Pod/Parser.pm in @INC (you may need to install the Pod::Parser module) (@INC contains: lib /Library/Perl/5.34/darwin-thread-multi-2level /Library/Perl/5.34 /Network/Library/Perl/5.34/darwin-thread-multi-2level /Network/Library/Perl/5.34 /Library/Perl/Updates/5.34.1 /System/Library/Perl/5.34/darwin-thread-multi-2level /System/Library/Perl/5.34 /System/Library/Perl/Extras/5.34/darwin-thread-multi-2level /System/Library/Perl/Extras/5.34) at lib/Locale/Po4a/Pod.pm line 14.
> ```

This is only happening on the macOS 14 runner.

On the macOS 11, 12, and 13 runners, and locally on my macOS 12 machine, this happens instead:

```
Malformed encoding while writing to file /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_textproc_po4a/po4a/work/po4a-0.71/blib/man/ca/man3/Locale::Po4a::Xml.3pm.pod with charset UTF-8: "\x{fffd}" does not map to UTF-8 at lib/Locale/Po4a/TransTractor.pm line 513.
```

**Comment by ryandesign** [comment]
> This is only happening on the macOS 14 runner.

Might be worth rechecking after fixes for https://trac.macports.org/ticket/69661 happen.

**Comment by i0ntempest** [comment]
I've added a workaround. Despite the different errors on different systems it seems to have fixed both. Please take another look.

**Comment by i0ntempest** [comment]
@ryandesign Looks like removing homebrew did not fix this.

**Comment by reneeotten** [comment]
is there a path forward here? If so, let's make some progress, otherwise let's close the PR

**Comment by i0ntempest** [comment]
I have a temporary workaround in place ready for review (the second commit). The third one causing the failure is just a test showing removing homebrew did not solve the problem.

**Comment by reneeotten** [comment]
well... the CI fails so this has of chance of getting merged. If something doesn't solve the problem, then remove that commit and/or find a correct solution.

**Comment by i0ntempest** [comment]
Right, what about now?

**Comment by i0ntempest** [comment]
Since checks are passing and I don't see any problems, I'm merging this in 24h if there's no objections.

**Pull request merged**
