### PR TITLE
icu: update to 76.1

### PR DESCRIPTION
**Pull request by mohd-akram**
#### Description

Closes: https://trac.macports.org/ticket/69880

###### Tested on
macOS 15.1.1 24B2091 arm64
Xcode 16.1 16B40

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by i0ntempest** [comment]
OK with revbumping R

**Comment by barracuda156** [comment]
@mohd-akram Maybe first update `icu-devel` port, like @catap was doing when he managed the port? So that those who care can verify first that no apocalyptic disaster ensues :) 

P. S. To be clear, this is not a powerpc-motivated concern. FWIW, `icu` works pretty well on powerpc so far, and in any case I can fix it for myself, if things go wrong. I will try the build anyway, but have no time to test any dependents.

**Comment by barracuda156** [comment]
@mohd-akram I have built `icu-devel` 76.1 from your tree on PowerPC, so that works.

**Comment by catap** [comment]
@mohd-akram I see that you had increased compiler version for boost. Are you sure that such increases do not needed for some (all?) dependant of boost?

**Comment by mohd-akram** [comment]
@catap The compiler version increase is for Boost to be able to consume ICU headers. I don't think it should affect dependents.

> Also, CI hasn't got any chances to build all ports in timeout.

Worth a shot :) At the very least we'll figure out if this upgrade is roughly feasible.

**Comment by mascguy** [comment]
> @catap The compiler version increase is for Boost to be able to consume ICU headers. I don't think it should affect dependents.
> 
> > Also, CI hasn't got any chances to build all ports in timeout.
> 
> Worth a shot :) At the very least we'll figure out if this upgrade is roughly feasible.

Ideally at least a few maintainers would install `icu-devel` locally, and test building some of their dependent ports with it. We've tried to do that in the past when Kirill was updating the port, and it's a sensible strategy.

I'm certainly willing to do that over the next day or two, and report back. Is anyone else willing to pitch in and help test?

**Comment by catap** [comment]
> @catap The compiler version increase is for Boost to be able to consume ICU headers. I don't think it should affect dependents.
> 

If ICU uses only in "internal" headers, it will work. But boost is mainly header templates which may bring new ICU to the end program. I really have no idea about it, but, personally, I won't be supprised if it affects end software.

**Comment by mohd-akram** [comment]
@catap Haven't experienced any such issue during my testing.

This is in pretty good shape now, and should be ready to merge soon. Check your ports to make sure things are working as intended.

**Pull request merged**
