### PR TITLE
lang/sbcl: update to sbcl-2.4.8

### PR DESCRIPTION
**Pull request by easye**

### CODE REVIEW

**Comment by barracuda156** [comment]
So we can merge a PR which fails CI on two latest macOS versions, but cannot merge a PR which fixed SBCL on PowerPC and affects nothing else whatsoever…

**Comment by easye** [comment]
The failures didn't seem to be "real" as far as I could tell.

Which PR would you like to merge for PowerPC?

**Comment by barracuda156** [comment]
> Which PR would you like to merge for PowerPC?  

@easye Until this is merged, all PowerPC builds are broken: https://github.com/macports/macports-ports/pull/24806
(Discussion with upstream is in the SBCL developers mailing list.)

**Comment by barracuda156** [comment]
@easye Any chance of helping there? This is a port on which Kirill and myself spent a lot of time. Quite upsetting to see that it is now broken on platforms of interest.

**Pull request merged**
