### PR TITLE
ruby27,30: update to 2.7.8, 3.0.6

### PR DESCRIPTION
**Pull request by fhgwright**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

Mac OS X 10.4.11 8S165, PPC, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, i386, Xcode 2.5 8M2558
Mac OS X 10.5.8 9L31a, PPC, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, i386, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, x86_64, Xcode 3.1.4 9M2809
Mac OS X 10.6.8 10K549, i386, Xcode 3.2.6 10M2518
Mac OS X 10.6.8 10K549, x86_64, Xcode 3.2.6 10M2518
Mac OS X 10.7.5 11G63, x86_64, Xcode 4.6.3 4H1503
OS X 10.8.5 12F2560, x86_64, Xcode 5.1.1 5B1008
OS X 10.9.5 13F1911, x86_64, Xcode 6.2 6C131e
OS X 10.10.5 14F2511, x86_64, Xcode 7.2 7C68
OS X 10.11.6 15G22010, x86_64, Xcode 8.1 8B62
macOS 10.12.6 16G2136, x86_64, Xcode 9.2 9C40b
macOS 10.13.6 17G14042, x86_64, Xcode 10.1 10B61
macOS 10.14.6 18G9323, x86_64, Xcode 11.3.1 11C505
macOS 10.15.7 19H15, x86_64, Xcode 12.4 12D4e
macOS 11.7.6 20G1231, arm64, Xcode 13.2.1 13C100
macOS 12.6.5 21G531, arm64, Xcode 14.2 14C18
macOS 13.3.1 22E261, arm64, Xcode 14.3 14E222b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [N/A] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [KNOWN FAIL] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by fhgwright** [comment]
It wouldn't hurt to also merge #17500 for `ruby26`, which has been outstanding for 94 days so far.

**Comment by herbygillot** [comment]
> It wouldn't hurt to also merge #17500 for `ruby26`, which has been outstanding for 94 days so far.

Merged

**Comment by barracuda156** [comment]
@fhgwright @herbygillot This has either broken `ruby27` on ppc or, possibly, I just had a fixed version locally for 2.7.7, while it was broken in MacPorts earlier.

In any case, 2.7.8 installed from this commit fails to build a trivial package, freezing at destroot (Ruby compiles stuff in destroot).

Perhaps I won't pursue fixing it, it is archaic, but just for the record: a fact that something builds does not prove it works, and for compilers it _is_ important.

**Comment by fhgwright** [comment]
@barracuda156 
> @fhgwright @herbygillot This has either broken `ruby27` on ppc or, possibly, I just had a fixed version locally for 2.7.7, while it was broken in MacPorts earlier.
> 
> In any case, 2.7.8 installed from this commit fails to build a trivial package, freezing at destroot (Ruby compiles stuff in destroot).

This is woefully lacking in specifics, but a few points:

1. Ruby itself builds with Ruby, in its `miniruby` form, so even just building requires a working Ruby, albeit a cut-down version.
2. I always test Ruby's own builds up through `destroot`
3. `ruby26`, `ruby27`, `ruby30`, `ruby32`, and `ruby33` all build successfully on all _supported_ platforms, including 10.4-10.5 _real_ `ppc`.
4. Ruby doesn't play nicely with Rosetta.  No version of Ruby is able to build for Rosetta without hanging in an infinite loop during its miniruby-based build.  Until some unknown and probably substantial effort is expended fixing this low-priority and never officially supported case, Rosetta should not be considered a valid Ruby target.

> Perhaps I won't pursue fixing it, it is archaic, but just for the record: a fact that something builds does not prove it works, and for compilers it _is_ important.

True, but the fact that something _doesn't_ build definitely proves that it _doesn't_ work, which has been the state of every version of Ruby on at least one platform until I fixed it.

At least I didn't take some `ppc64` assembly code, stuff it into a 32-bit `ppc` context, and expect it to work.  That's more than I can say for `ruby31`.

**Comment by barracuda156** [comment]
> At least I didn't take some ppc64 assembly code, stuff it into a 32-bit ppc context, and expect it to work. That's more than I can say for ruby31

@fhgwright Well, FWIW that has been working: ruby31+ can build other ruby and can build ruby ports. It is possible that assembler code has mistakes, and you are welcome to help me and upstream to fix those.

But earlier rubies do not work at all for me. It is likely that they are inherently broken as they are, and not broken by any of your patches. I did not review every modification, I can only say as a matter of fact that the resulting binary does not work correctly. It might be working on some other ppc systems, of course.

I do not have a fix for Rosetta and never tried to fix it. So there no recent Ruby works for me as well.

**Comment by barracuda156** [comment]
@fhgwright I thought if I borrow a pre-built `ruby33` from 10.6 ppc into 10.6.8 Rosetta, it gonna work, but no, it is freezes when trying to compile code. So no luck here, Rosetta remains broken for some reason.

**Pull request merged**
