### PR TITLE
yash: update to 2.49

### PR DESCRIPTION
**Pull request by l2dy**

### CODE REVIEW

**Comment by larryv** [comment]
> [Travis Build #10208](https://travis-ci.org/macports/macports-ports/builds/645090893) Passed.
> Lint results
> 
> Port yash success on xcode10.3. [Log](https://paste.macports.org/d45066079b56)
> Port yash success on xcode9.4. [Log](https://paste.macports.org/216122624d53)
> Port yash success on xcode8.3. [Log](https://paste.macports.org/4f79aa32bf02)
> Port yash success on xcode7.3. [Log](https://paste.macports.org/f027ac7baaf5)

wow, things are real fancy now

**Comment by larryv** [comment]
I made some trivial tweaks in the final commit, but everything's fine. Thanks!

**Comment by mf2k** [comment]
@larryv It looks like you accidentally closed rather than committed this PR.

**Comment by l2dy** [comment]
Merged as c09caed79ca41377b2794d52f609ddbdf3ccfdcc.

**Pull request closed without merging**
