### PR TITLE
py-pycryptodome{,x}: update to 3.15.0

### PR DESCRIPTION
**Pull request by catap**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 12.4 21F79 x86_64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Kirill, you can simplify tests, via recent changes from this merged PR: https://github.com/macports/macports-ports/pull/15001

**Comment by catap** [comment]
Unfortunately it broken tests here :(

**Review by xeron — APPROVED** [review]

**Comment by mascguy** [comment]
> Unfortunately it broken tests here :(

Kirill, do you want to keep this open then?

**Comment by catap** [comment]
@mascguy I mean that #15001 broke tests at this PR.

**Comment by mascguy** [comment]
> @mascguy I mean that #15001 broke tests at this port. And to fix it I've added a direct call of `setup.py test` without any arguments.

Can you provide more detail? Perhaps this is something that can be fixed in the `python` portgroup.

CC: @reneeotten

**Comment by catap** [comment]
Christopher, I've simplified as I can. 

Without `test.cmd        ${python.bin} setup.py test` a lot of tests failed with issue like:
```
E   OSError: Cannot load native module 'Cryptodome.Util._strxor': Not found '_strxor.cpython-38-darwin.so', Not found '_strxor.abi3.so', Not found '_strxor.so'
```
and without empty `test.args` it fails as:
```
Compiling support for CLMUL instructions
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option -o not recognized
```

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
Looks good now, and @xeron approved. Merging.

**Comment by catap** [comment]
@mascguy FYI I'm also a maintainer of this port ;)

**Pull request merged**
