### PR TITLE
grib_api: Update to 1.19.0.

### PR DESCRIPTION
**Pull request by woodruffw**
Updates the `grib_api` package to `1.19.0`.

### CODE REVIEW

**Comment by Schamschula** [comment]
Please reset the revision to 0, or remove the revision line completely (preferred)

**Comment by woodruffw** [comment]
> remove the revision line completely (preferred)

Done.

**Comment by Schamschula** [comment]
Also you will need to revision bump port that depend on grib_api:

gnudatalanguage
py-pygrib
cdo
gri
libemos
magicspp
metview

**Comment by woodruffw** [comment]
> gnudatalanguage
> py-pygrib
> cdo
> gri
> libemos
> magicspp
> metview

Done, let me know if you want those changes squashed into the first commit.

**Comment by Schamschula** [comment]
Thanks,

Now we wait for Takeshi Enomoto, who is the maintainer of grib_api. If this were openmaintainer,  I could commit, but the policy is maintainer only in this case.

**Comment by woodruffw** [comment]
Got it, thanks for the help!

**Comment by larryv** [comment]
Do not worry about merging the commits; I have done so.

**Comment by woodruffw** [comment]
@larryv Any update on this? I don't see the `grib_api` commits in the repo history (sorry if I'm looking in the wrong place, new to macports!)

**Comment by Schamschula** [comment]
I think we have reached maintainer timeout.

**Pull request merged**
