### PR TITLE
qscintilla: update version 2.10.8->2.11.1

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.3
Xcode 10.1 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mojca** [comment]
There's also py-qscintilla-qt4/5.

**Comment by michaelld** [comment]
I just updated the Qsci ports to 2.11[.0] ... didn't realize there's a 2.11.1 out already. I'll update it separately from this PR.

@MarcusCalhoun-Lopez would you prefer that we do a PR for this port since we're co-maintainers of it? Doing so would help avoid this situation ...

**Comment by michaelld** [comment]
Literally "just" ... LOL

**Comment by MarcusCalhoun-Lopez** [comment]
@michaelld, I do not think it is absolutely necessary to create a pull  request for every change.
The main reason I did so this time is that a patch was necessary for the Qt4 version, and I was not 100% sure of the best way to fix it.
However, you and I seem to have ended up with the same solution.

As a side note, the patch `patch-Qt4Qt5_qsciscintillabase.cpp.diff` does not seem to be necessary for the Qt5 version.
I am not sure why.

**Comment by michaelld** [comment]
Ok that makes sense. Great minds think alike on the solution? Next time a patch is required I'll do a PR instead; it's just more thoughtful. Thanks for doing this PR & getting this discussion moving.

**Comment by michaelld** [comment]
Yes, I also saw that the patch was not necessary for Qt5 ... but it doesn't hurt the Qt5 build to include it in this manner & eventually it will be in the source in this way .. so, let's just patch it for both Qt4 and Qt5.

**Comment by michaelld** [comment]
FYI I did just update the Qsci ports to 2.11.1 as like this PR.

**Pull request closed without merging**
