### PR TITLE
Nagios ports: use https urls

### PR DESCRIPTION
**Pull request by chrstphrchvz**
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

- [x] checked your Portfile with `port lint`?
See https://github.com/macports/macports-ports/pull/3545#issuecomment-459601527

### CODE REVIEW

**Comment by yan12125** [comment]
There's an error while installing nrpe:

> checking for SSL headers... configure: error: Cannot find ssl headers

(From https://paste.macports.org/0a94acbe96d4)

@chrstphrchvz Could you have a look?

**Comment by chrstphrchvz** [comment]
@yan12125 I hadn't tried building these ports, but since all I changed in `nrpe` was the `homepage`, which isn't reused anywhere, so that issue is likely present in the existing port.

The `nrpe` and `ncsa` ports are very outdated (the versions in MacPorts are ~11 years old, but each has been updated within the past 3-6 years); I am not a user of them nor interesting in maintaining them. I'm inclined to submit another PR to see whether those two ports can be removed or if they should be updated.

**Comment by yan12125** [comment]
Sounds reasonable to drop both nsca and nrpe. There are no Trac traffic for them since 4 years ago, either.

**Comment by pmetzger** [comment]
@yan12125 Please shepherd this.

**Comment by yan12125** [comment]
Sure! @chrstphrchvz please open another PR to remove both ports.

**Pull request merged**
