### PR TITLE
MoarVM, nqp, rakudo: update to 2022.12 and some fixes

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Commits are hopefully self-explanatory.

Fixing prefix for `MoarVM` has consequences down the road. Compare the following from `rakudo` Makefile.
Before fix-up:
```
M_LDFLAGS =  -O3 -DNDEBUG -Wl,-headerpad_max_install_names -L/opt/local/lib -lMacportsLegacySupport -arch ppc -Wl,-rpath,"//opt/local/lib"
M_LDLIBS  =  -L/usr/local/lib -ldyncall_s -ldyncallback_s -ldynload_s -ltommath -luv -lpthread
```
After fix-up:
```
M_LDFLAGS =  -O3 -DNDEBUG -Wl,-headerpad_max_install_names -L/opt/local/lib -lMacportsLegacySupport -arch ppc -Wl,-rpath,"/opt/local/lib"
M_LDLIBS  =  -L/opt/local/lib -ldyncall_s -ldyncallback_s -ldynload_s -ltommath -luv -lpthread
```
In result, `ld` warnings are gone.

P. S. `malloc` errors on PPC are _mostly_ gone now, but still show up at one spot.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Rosetta
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@mojca Could you please take a look?

**Comment by barracuda156** [comment]
@herbygillot @reneeotten Could we merge this please?

The PR includes update and minor fix-ups. CI pass, locally PPC builds fine.

**Comment by barracuda156** [comment]
@herbygillot @harens @reneeotten Bump! This is ready to be merged, checks pass, PPC feels better :)

**Review by harens — COMMENTED** [review]
I'm guessing `depends_lib-append` is required to not overwrite legacysupport, but is there any benefit in changing the original `depends_build` to `depends_build-append`?

Otherwise this seems like great work! Thanks @barracuda156 👍

**Comment by barracuda156** [comment]
> I'm guessing `depends_lib-append` is required to not overwrite legacysupport, but is there any benefit in changing the original `depends_build` to `depends_build-append`?
> 
> Otherwise this seems like great work! Thanks @barracuda156 👍

I think the reasoning was “it does not hurt and just in case”, but I was asked a few times by senior members to add `-append` in cases where it was not strictly necessary.

**Comment by harens** [comment]
No that seems fair enough, just thought I'd check. Thank you for all the time and work you've put into this PR @barracuda156!

**Comment by barracuda156** [comment]
@harens Thank you!

**Pull request merged**
