### PR TITLE
libsecret: update to 0.20.5

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

This will require revbumping dependents.

@mascguy How should we do this? CI for revbumping will fail, since there are several WebKit versions etc.

UPD. Well, we could just do a follow-up revbump for all dependents then.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
> This will require revbumping dependents.

Not expected in a minor revision increase. Is this because of the switch to meson? The developers did not maintain the same library versioning information in all of their build systems? Upstream bug report about that? Is switching to meson required?

**Comment by barracuda156** [comment]
@ryandesign It is likely due to a switch to Meson. I cannot check every dependent, but at least one of those needed a revbump locally. (It could be that not every of them needs.)

AFAIK, all Gnome ports are moving or have moved to Meson (and I hate it by the way).

**Comment by mascguy** [comment]
> @ryandesign It is likely due to a switch to Meson. I cannot check every dependent, but at least one of those needed a revbump locally. (It could be that not every of them needs.)

This is due to the usual situation: Some projects haven't implemented dylib versioning in their Meson builds, breaking ABI compatibility.

So we need to add a patch to fix that. (And submit to upstream.)

A recent example is here:

https://github.com/macports/macports-ports/commit/c17ed8e724e9d0cf163a4993b90a563c41473e25

> AFAIK, all Gnome ports are moving or have moved to Meson (and I hate it by the way).

As with anything new/unfamiliar, there's a learning curve with Meson. But once you understand the basics, it's actually quite nice.

**Comment by mascguy** [comment]
Sergey, be sure to check the output from the configure phase, with trace mode enabled.

From that, it was immediately clear that a few deps were missing.

**Comment by barracuda156** [comment]
@mascguy (Trace was broken earlier for me due to Macports base hardcoding arch flags and ignoring `--build=` setting, but it actually may be working now, as I found a way to ensure the correct build. So I will check it, thank you for reminding.)

**Comment by barracuda156** [comment]
@mascguy Thank you!

**Comment by ryandesign** [comment]
> This is due to the usual situation: Some projects haven't implemented dylib versioning in their Meson builds, breaking ABI compatibility.

It is unfortunate that it is "usual" that projects screw up their library versioning when they switch build systems. I wish there were some way to get the message to project developers to BE MORE CAREFUL *before* a release with such a change ships. Maybe there needs to be a huge red warning plastered all over the meson and cmake documentation about this.

@mascguy You added a patch here described as "Expected to be included in next release" but I did not see an upstream bug report or merge request about this. Please add the URL.

Note also that what we updated to here is a two-year-old version. The current stable version is 0.21.4. Livecheck did not identify this; I've fixed that.

**Comment by barracuda156** [comment]
@ryandesign Ah, sorry, I relied on live check here and did not look into the upstream. This is a simple port, I can update it to the latest, if desirable.

**Comment by mascguy** [comment]
> @mascguy You added a patch here described as "Expected to be included in next release" but I did not see an upstream bug report or merge request about this. Please add the URL.

Finally had a chance to submit a merge request, and the URL is:

https://gitlab.gnome.org/GNOME/libsecret/-/merge_requests/143

Once upstream responds to it, I'll update the portfile - and the patch as well - to include the above.

**Pull request merged**
