### PR TITLE
py-twine: upgrade to 1.11.0

### PR DESCRIPTION
**Pull request by duncanmmacleod**
#### Description

This PR upgrades `py-twine` to 1.11.0 (latest release on pypi.org), and `py-pkginfo` to 1.4.2 to match.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.13.6 17G65
Xcode 9.4.1 9F2000

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@pmetzger, done. I originally had these as separate commits but squashed them to abide by the guidelines...

**Comment by jjstickel** [comment]
@duncanmmacleod, thanks for the PRs.

**Comment by pmetzger** [comment]
Squashing is the right thing, but you also need to have one commit per logical change so that the logs can be read. Sadly picking the right number of commits requires a bit of exposure to how it is done, so don't worry, we'll tell you if it needs to be changed.

**Comment by pmetzger** [comment]
Merged. Thank you as always, @duncanmmacleod!

**Pull request merged**
