### PR TITLE
blender: update to 2.93.11

### PR DESCRIPTION
**Pull request by catap**
#### Description

Update to blender 3.x is required to update much more ports. Frankly, all this ports contains tons of patches and `reinplace` that makes such update a nightmare.

But I've achieved TLS version of blender which I can build via MacPorts on my laptop.

Much better than port which can't be build :)

Unfortently I can't switch it to OneTBB because some dependencies haven't supported OneTBB yet: https://github.com/PixarAnimationStudios/USD/issues/1471 or https://github.com/PixarAnimationStudios/OpenSubdiv/pull/1234 for example

###### Type(s)

- [x] bugfix
- [x] enhancement

###### Tested on

macOS 12.6 21G115 x86_64
Xcode 14.1 14B47b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by jasonliu--** [comment]
Do you know whether your PR is able to be built on MacOS 10.11? I use MacPorts on my 10.11 laptop, and I have spent quite a lot of effort to keep the MacPorts builds for Blender running under 10.11.

**Comment by catap** [comment]
@jasonliu-- I haven't tried it on 10.11 to be honest

**Comment by jasonliu--** [comment]
Is this ticket either a blocker for openvdb, or is your PR supposed to resolve this issue?

https://trac.macports.org/ticket/66463

**Comment by catap** [comment]
@jasonliu-- yes, it should fix this ticket

**Comment by catap** [comment]
Just rebased to the last master.

**Comment by jasonliu--** [comment]
I would like to verify that this PR still allows the Blender port to work on my 10.11 machine. Since there are so many changes, it will take me some time to re-compile all of the dependencies. I will report back here when I have obtained results.

**Comment by catap** [comment]
@reneeotten if I rebase this one are you willing to merge it? :)

**Comment by reneeotten** [comment]
I will not unless @jasonliu-- agrees/approves

**Comment by jasonliu--** [comment]
I'm have a difficult time coming to grips with all of the changes that were made in this PR. So many dependent ports have been updated at once in this one PR... in addition, some dependencies have also received an update in #16915.

I appreciate all of the effort that I'm sure you have put into these couple of PRs, but as the person who generally maintains most of these ports, it's quite difficult to do verification if you lump all of the updates into one PR.

**Comment by catap** [comment]
@jasonliu-- #16915 is blocked by this PR. As soon as this one is merged, it decreases the size of #16915 :) because it contains this one and a lot of another PRs.

:)

**Comment by catap** [comment]
BTW I've just rebased it to the last master

**Comment by reneeotten** [comment]
since January 1st, Python 3.11 is the default so if possible let’s set that as the default for ports in this PR as well?

**Comment by catap** [comment]
@reneeotten I'm a bit lazy to double test that all dependencies exists for py311 and it works at py311, let me be honest :)

Is py311 a kind of blocker here?

**Comment by catap** [comment]
@reneeotten ping here

**Comment by catap** [comment]
@herbygillot, @mascguy may I ask you to review this very old PR? I really won't like to retest it and this is a blocker (or a large part of) https://github.com/macports/macports-ports/pull/16915.

**Comment by catap** [comment]
Rebase brokes it :(

**Comment by catap** [comment]
@reneeotten this one was switched to Python 3.11 as requested.

**Comment by reneeotten** [comment]
@catap thanks for changing it to Python 3.11 but as I said most of these ports are maintained by @jasonliu-- and some sort of positive response from him would be great. I will not test any of this myself... If there is no response and/or promise to get the work done to get this merged from the maintainer, then I'll merge the PR myself. Let's aim for Wednesday

**Comment by catap** [comment]
@reneeotten thanks!

**Comment by mascguy** [comment]
> I would like to verify that this PR still allows the Blender port to work on my 10.11 machine. Since there are so many changes, it will take me some time to re-compile all of the dependencies. I will report back here when I have obtained results.

@jasonliu-- Jason, once Kirill is done making changes, I'll test this on my 10.11 VM.

**Comment by catap** [comment]
@mascguy the last changes was adding that line: https://github.com/macports/macports-ports/pull/16893/commits/f41d03f56b6afec9a9bfe44933758f69eb9fb543#diff-b39fcc115b0c9cd3de6eced77008b985f02ce12965201a757b93b89fbd507dc3R32-R33 which was discovered by github's CI.

I have local version of that archive and it had passed checksums, but CI's complains. I hope that it should be ok now.

**Comment by catap** [comment]
Well.. now I need to add `extract.rename yes` :( Too many things had changes for 4 months, since this PR has been created.

**Comment by catap** [comment]
@mascguy finally, CI happy!

**Comment by mascguy** [comment]
> @mascguy finally, CI happy!

I tried testing with 10.11, but I'm seeing build errors for `openimagio`. So we might want to move the updates for `blender` to a separate PR, and just update the various dependencies via this one. That way we can commit those, and fix issues with the deps first, prior to updating `blender`.

Thoughts?

**Comment by catap** [comment]
@mascguy the issue that blender is broken right now :) at least on macOS 12. Can you build blender from a master branch?

**Comment by catap** [comment]
My point: base on https://ports.macports.org/port/blender/details/ blender is broken completley. Here I've fixed it for at least macOS 12 (where I've tested) and probably 13 and 11.

`openimageio` seems also to be broken for 10.11: https://ports.macports.org/port/openimageio/details/

**Comment by catap** [comment]
But let me try to build it on 10.11

**Comment by catap** [comment]
I've just tried the master branch: it also fails `openimageio`. My branch is fails on `opencolorio` because a new version doesn't support new macOS.

Here the trade off: we need to upgrade to the new version to support modern python. It is impossible to keep some dependencies on python2.7, and some on python3.11.

Can I fix `opencolorio` for example to be build on 10.11? Yes, but it required in addition to "remove" support of metal framework (or rewrite it to support metal from 10.11), and a few similar things.

I'm not a user of that, I'm only fixing thinkgs. Right now it can't be installed at all, after this PR it can be installed on the last macOS.

From my point of view it's faaar better.

**Comment by mascguy** [comment]
A simpler approach might be to have the various ports fallback to their current release for older macOS releases - including `blender` - so that older macOS releases are still supported.

Perhaps that might be the better option? Thoughts...?

**Comment by catap** [comment]
@mascguy yes, I'm going by this road right now. I've pin some dependencies on the old version to make it possible to build on 10.11.
 - `opencolorio` required Metal API on state of 10.13, so, I've pin it;
 - `openimageio` depends on `opencolorio` and I've also forced to pin it without update;
 - old `openimageio` is broken by update of `libraw`, so, a bit of backporting of patches here;
 -  ...
 
 I let you know here as soon as I reach something.

**Comment by catap** [comment]
Well, in addition `partio` is used two different LLVM version to mach the version which is used by `osl` which depends on `openimageio` :)

Frankly speaking this things are broken on 10.11, but I may able to fix it. Maybe it had worked a while ago, I have no idea. But not today.

**Comment by catap** [comment]
Well.. when PR was open a new version of blender 2.93 was released. Let me include it.

**Comment by catap** [comment]
@mascguy, @jasonliu--, @reneeotten I really doubt that I can fix it. Blender port says that it won't work on 10.11. See: https://github.com/macports/macports-ports/commit/7ea91ffd87861b40f5343617ced522aff55a1057

**Comment by catap** [comment]
Building it finally on 10.11

**Comment by catap** [comment]
@mascguy it successfully builds on macOS 10.11, anyway, it won't start in virtual machine because it required OpenGL 3.1 or something like that.

But after diging for couple of hours (like 6) why I've discovered a bypass: `BLENDER_SOFTWAREGL`. This is an environment variable. So, by running a command `env BLENDER_SOFTWAREGL=1 open /Applications/MacPorts/Blender.app` I've started it and captures screenshots.

Screenshot 2023-04-25 at 22 16 43

Screenshot 2023-04-25 at 22 16 47

**Comment by mascguy** [comment]
> @mascguy it successfully builds on macOS 10.11, anyway, it won't start in virtual machine because it required OpenGL 3.1 or something like that.
> 
> But after diging for couple of hours (like 6) why I've discovered a bypass: `BLENDER_SOFTWAREGL`. This is an environment variable. So, by running a command `env BLENDER_SOFTWAREGL=1 open /Applications/MacPorts/Blender.app` I've started it and captures screenshots.

That is awesome Kirill, great work!

So are we ready to merge, once CI completes?

**Comment by catap** [comment]
@mascguy I guess this was the last remark :)

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
Given that Kirill has confirmed that this all works on 10.11, are there any objections to merging (once CI conpletes)?

@reneeotten and @jasonliu-- ?

**Comment by catap** [comment]
@mascguy from my point of view all remarks addresed and this is ready to be merged.

**Comment by mascguy** [comment]
> @mascguy from my point of view all remarks addresed and this is ready to be merged.

Sounds good, let's give Renee and Jason a few days to respond.

**Comment by catap** [comment]
@mascguy that should we do with this one?

**Comment by mascguy** [comment]
I'm definitely fine with this, and would love to see it merged.

But it's only been two days, so let's give folks another few days to respond.

**Comment by catap** [comment]
@mascguy thanks, it's clear. I'm pushing at two PRs because they are blocker for my huge TBB/OneTBB mess fix up, which is blocking a few another updates :)

**Comment by jasonliu--** [comment]
@mascguy, do you need to run the command with the added environment variable each and every time you start Blender? Or is this something the could be incorporated during the build process?

**Comment by mascguy** [comment]
> @mascguy, do you need to run the command with the added environment variable each and every time you start Blender? Or is this something the could be incorporated during the build process?

To make it seamless, we'd probably want to use a launch script [within the app bundle] to set it when necessary.

Kirill, is that something you'd mind doing?

**Comment by jasonliu--** [comment]
If it should be in a launch script, then maybe we could make it a separate PR. I would be willing to submit that PR, since I have to create launch scripts for some of the open source games that I have made Portfiles for, so I could probably grab some of my existing code from those to repurpose for this case.

**Comment by mascguy** [comment]
> If it should be in a launch script, then maybe we could make it a separate PR. I would be willing to submit that PR, since I have to create launch scripts for some of the open source games that I have made Portfiles for, so I could probably grab some of my existing code from those to repurpose for this case.

Sounds great! So can can we go ahead and merge this PR as-is then?

**Comment by catap** [comment]
@jasonliu--, @mascguy this environment variable only required because I've tested it inside virtual machine with quite poor OpenGL implementation.

For real use case it doesn't needed.

Have I missed something?

**Review by mascguy — APPROVED** [review]
Everything is now covered - including 10.11 - so we're good-to-go.

**Comment by catap** [comment]
Yahooo! Thanks Christopher!

**Comment by jasonliu--** [comment]
> @jasonliu--, @mascguy this environment variable only required because I've tested it inside virtual machine with quite poor OpenGL implementation.
> 
> For real use case it doesn't needed.
> 
> Have I missed something?

That probably makes a certain amount of sense, since many virtual machine softwares aren't perfectly able to pass through hardware graphics rendering between the guest and host OSes. My googling skills are failing me right now, but I seem to recall that using `BLENDER_SOFTWAREGL=1` was also quite inefficient, and puts a lot of additional load on the CPU.

**Pull request merged**
