### PR TITLE
gnome-internet-radio-locator version 1.1.2

### PR DESCRIPTION
**Pull request by oleaamot**
gnome-internet-radio-locator: update to version 1.1.2

* update to version 1.1.2

Closes: https://trac.macports.org/ticket/56368

### CODE REVIEW

**Comment by oleaamot** [comment]
This is my first pull request against https://github.com/macports/macports-ports.git
from https://github.com/oleaamot/macports-ports.git

**Comment by pmetzger** [comment]
Hi! Can you change the commit message to: 

`gnome-internet-radio-locator: update to version 1.1.2`

(The pull request should have given you a checklist suggesting that you follow our commit name standard.)

If you fix that, I'll pull this after the CI system finishes running. Please squash your commits so we only get the one. Thanks!

**Comment by oleaamot** [comment]
OK.

**Comment by oleaamot** [comment]
Sorry, I could not do the new commit.

Hope it is possible to fix.

**Comment by pmetzger** [comment]
I manually applied your patch. In the future, you may want to learn how to do git pull requests cleanly, it will assure your port updates are applied within a short period of time. There are general instructions in the macports guide.

**Comment by mojca** [comment]
@pmetzger: next time it makes more sense to force push to the branch with PR, so that it gets properly recognised by GitHub and marked as merged rather than closed (which looks like rejected). Or at least mention the commit which closed it (bc13c05c264c79c0ae465514e923e5f2e3e442f0 in this case).

**Comment by pmetzger** [comment]
@mojca I mentioned the closing merge in the Trac ticket.

And yah, I probably should have done a force push but I was a bit distracted.

**Pull request closed without merging**
