### PR TITLE
grpc: Update to version 1.48.0; apache-arrow: revbump, Add Python 310

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.5 21G72 x86_64
Xcode 13.4.1 13F100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
@essandess There is bug in the code to be fixed: https://trac.macports.org/ticket/65525

**Comment by essandess** [comment]
> @essandess There is bug in the code to be fixed: https://trac.macports.org/ticket/65525

I only have access to macOS 12. I suggest we update to the latest `grpc` version, then issue a separate PR to address the issue in https://trac.macports.org/ticket/65525.

**Comment by barracuda156** [comment]
> I only have access to macOS 12. I suggest we update to the latest `grpc` version, then issue a separate PR to address the issue in https://trac.macports.org/ticket/65525.

@essandess Ok, sounds good.

**Comment by jmroot** [comment]
Lint errors do need to be fixed.

**Comment by mascguy** [comment]
> Lint errors do need to be fixed.

Yes indeed, particularly this fatal issue:

```
port lint py310-pyarrow: Error: Unknown dependency: py310-pytest-lazy-fixture
```

**Comment by essandess** [comment]
> Lint errors do need to be fixed.

Thanks. This is done now.

**Comment by essandess** [comment]
To the best of my knowledge the CI errors are issues with CI, not the PR, and this PR may be merged.

This PR is necessary to merge #15456.

**Comment by jmroot** [comment]
```
-- Downloading...
[943](https://github.com/macports/macports-ports/runs/7510760636?check_suite_focus=true#step:8:946)
     dst='/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_apache-arrow/apache-arrow/work/build/orc_ep-prefix/src/orc-1.7.3.tar.gz'
[944](https://github.com/macports/macports-ports/runs/7510760636?check_suite_focus=true#step:8:947)
     timeout='none'
[945](https://github.com/macports/macports-ports/runs/7510760636?check_suite_focus=true#step:8:948)
     inactivity timeout='none'
[946](https://github.com/macports/macports-ports/runs/7510760636?check_suite_focus=true#step:8:949)
  -- Using src='https://www.apache.org/dyn/closer.cgi?action=download&filename=/orc/orc-1.7.3/orc-1.7.3.tar.gz'
[947](https://github.com/macports/macports-ports/runs/7510760636?check_suite_focus=true#step:8:950)
  -- Using src='https://downloads.apache.org/orc/orc-1.7.3/orc-1.7.3.tar.gz'
[948](https://github.com/macports/macports-ports/runs/7510760636?check_suite_focus=true#step:8:951)
  -- [download 0% complete]
[949](https://github.com/macports/macports-ports/runs/7510760636?check_suite_focus=true#step:8:952)
  -- Using src='https://github.com/apache/orc/archive/rel/release-1.7.3.tar.gz'
[950](https://github.com/macports/macports-ports/runs/7510760636?check_suite_focus=true#step:8:953)
  -- verifying file...
[951](https://github.com/macports/macports-ports/runs/7510760636?check_suite_focus=true#step:8:954)
         file='/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_apache-arrow/apache-arrow/work/build/orc_ep-prefix/src/orc-1.7.3.tar.gz'
[952](https://github.com/macports/macports-ports/runs/7510760636?check_suite_focus=true#step:8:955)
  -- SHA256 hash of
[953](https://github.com/macports/macports-ports/runs/7510760636?check_suite_focus=true#step:8:956)
      /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_apache-arrow/apache-arrow/work/build/orc_ep-prefix/src/orc-1.7.3.tar.gz
[954](https://github.com/macports/macports-ports/runs/7510760636?check_suite_focus=true#step:8:957)
    does not match expected value
[955](https://github.com/macports/macports-ports/runs/7510760636?check_suite_focus=true#step:8:958)
      expected: '535c4d7588172e85b8fc941cd0575d67f2155a55e4cd65d87d5b194b0bb28a31'
[956](https://github.com/macports/macports-ports/runs/7510760636?check_suite_focus=true#step:8:959)
        actual: 'e81da15df2084a9b5578bc4585406391cafec3edb6e724c66e165f21f11abd77'
[957](https://github.com/macports/macports-ports/runs/7510760636?check_suite_focus=true#step:8:960)
  -- Hash mismatch, removing...
```
There are two problems there, the hash mismatch and the fact that it's downloading things in the build phase.

**Comment by essandess** [comment]
> There are two problems there, the hash mismatch and the fact that it's downloading things in the build phase.

Upstream requires a git repo to build. This is necessary, and it works as with previous MacPorts versions of the same ports.

**Comment by jmroot** [comment]
I don't see any git repo involvement in the failure. As far as I can gather from the log, it's repeatedly downloading a .tar.gz file because the hash doesn't match. I see no reason why it would be impossible to download the correct version of this file in the fetch phase and then put it where the build expects it later on.

**Comment by essandess** [comment]
> I don't see any git repo involvement in the failure. As far as I can gather from the log, it's repeatedly downloading a .tar.gz file because the hash doesn't match. I see no reason why it would be impossible to download the correct version of this file in the fetch phase and then put it where the build expects it later on.

Okay thanks for spotting this. This issue was that the Portfile wasn't initializing all the repos that `cmake` wants to see, and it was downloading them directly.

This is fixed in the latest push.

https://github.com/grpc/grpc/blob/658632fcd82aa673addc2b4b91860d4e2738f574/CMakeLists.txt#L330-L405

**Comment by essandess** [comment]
I believe the CI error is simply a timeout and that this PR may be merged.

**Pull request merged**
