### PR TITLE
libgit2: Update to 1.3.0

### PR DESCRIPTION
**Pull request by judaew**
- libgit2: update to 1.3.0
- Revision bump after update libgit2

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.6 20G165 x86_64
Xcode 13.0 13A233

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Review by amake — APPROVED** [review]

**Comment by judaew** [comment]
After updating libgit2, the ports that depend on it may break, so I raised the revision for them.

**Comment by herbygillot** [comment]
Can you verify that `pygit2` builds with v1.3.0?

I had seen some issues when I took a look not too long ago, and in discussion it was pointed out that the current version of pygit2 (v1.6.1) needs a patch to build against libgit2 v1.3.0: https://github.com/libgit2/pygit2/issues/1090#issuecomment-930342585

**Comment by judaew** [comment]
@herbygillot Thank you, done. I applied a patch for `py-pygit2` and checked the port is working. I successfully created a repository using the port, everything looks good.

**Comment by herbygillot** [comment]
Tested `rust` against this PR, and it built successfully.  I think we can merge this and rebuild any ports missed in this PR going forward.

**Comment by judaew** [comment]
Thanks @herbygillot

**Pull request merged**
