### PR TITLE
crystal: new port

### PR DESCRIPTION
**Pull request by mohd-akram**
#### Description

Add the Crystal language. Could not test in tracing mode as it stalls forever for some reason.

###### Tested on

macOS 10.13.4 17E199
Xcode 9.3 9E145

###### Verification

Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM, but as the Portfile is relatively complicated I'd like a second opinion on it if possible.

**Comment by kencu** [comment]
Agree, this is a bit complicated. Some build tricks noted. I know nothing about crystal or how to test the installation.

Fails on 10.11 (and all earlier, no doubt) with 
```
dyld: _dyld_bind_fully_image_containing_address() error
dyld: Symbol not found: _clock_gettime
 ```

**Comment by mohd-akram** [comment]
@kencu Seems that the bootstrap Crystal binary was built for 10.12 and above, even though [the code takes care to avoid that](https://github.com/crystal-lang/crystal/blob/master/src/crystal/system/unix/time.cr). I've confirmed this with `otool -l`. I'll see if I can raise an issue with them about that. There are indeed some build tricks (lol) which I guess I should explain:

* All the patches are to allow static linking Crystal-produced binaries. One of them is a backport from master and two will hopefully be merged into Crystal.

* The post-patch replacements are because Crystal hardcodes `-L` linking directories and because MacPorts' iconv has a `lib` prefix before its functions (libiconv_open instead of iconv_open). Apparently OpenBSD is the same so I'm just using its file.

* Overriding `CC` is to force Crystal to look in `$prefix/lib` (because of the aforementioned hardcode). Tried to use a build flag (`--link-flags`), but it didn't work.

I've added Crystal's builtin tests which pass (changing `PATH` is required for a specific test to pass).

**Comment by kencu** [comment]
nearly 13000 examples built during the tests, with zero errors, so I guess you have it sorted out 😀 

all the destrooting looks as it should look.

can you put a pre-fetch block in to stop compilation on 10.11 and less? Something like this should do it:

```
if { ${os.platform} eq "darwin" && ${os.major} <= 15} {
    pre-fetch {
        ui_error "${name} ${version} requires macOS 10.12 or greater at present."
        return -code error "incompatible OS X version"
    }
}

```
After that, should be good to go, I think.

**Comment by mohd-akram** [comment]
Yeah, there are quite a few tests! I've added the code to the Portfile.

**Comment by kencu** [comment]
With ports like that, pretty much time you asked for commit rights, no?

**Comment by pmetzger** [comment]
@mohd-akram see: https://guide.macports.org/chunked/project.membership.html

**Pull request merged**
