### PR TITLE
[WIP] Fix broken Haskell world

### PR DESCRIPTION
**Pull request by amake**
#### Description

#4699 / #4794 bumped the ghc port, but in doing so appears to have broken the entire Haskell world. [These important comments](https://github.com/macports/macports-ports/pull/4794/files/c862681d2f9c20639ca1df1d7a30eed5d8c4cc7a#diff-b8586042762378b45ceaa428e6d749a8L7) in the ghc portfile were deleted without explanation or action:

```
# Do not update GHC separate from Haskell Platform.
# When updating GHC, make sure to revbump all Haskell ports.
# Also make sure to update the version in the Haskell PortGroup.
```

Now, for instance, all existing Haskell library port binaries will install but fail to be found because they install to `${prefix}/lib/ghc-7.8.3` instead of `-8.6.5`.

This PR attempts to address all of this, but it's a lot of work so I will do it incrementally.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.6 18G87
Xcode 10.3 10G8 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by neverpanic** [comment]
I think @essandess wanted to switch to builds based on stack, see #4633 and #4698. That would likely make most of our ports for haskell libraries obsolete (which I think is a good thing).

We might then eventually drop haskell-platform completely.

**Comment by essandess** [comment]
@amake Perhaps these modules will all compile with the latest ghc 8.6.5, but the great majority (perhaps all) are years out of date. For example, the MacPorts `hs-crypto-api` version 12.2 is **[six years](https://hackage.haskell.org/package/crypto-api-0.12.2.2)** out of date.

As @neverpanic points out, just use Haskell development tools cabal (https://github.com/macports/macports-ports/pull/4715) or stack (https://github.com/macports/macports-ports/pull/4633), which will take care of downloading whatever `ghc` and Haskell code versions are specified in `cabal.yaml` or `stack.yaml`.

It’s completely unnecessary and counterproductive to use MacPorts as a package manager for a package manager.

I can envision scenarios where some of these ports would be convenient to download for specific projects, but in general just let cabal and stack take care of it.

**Comment by amake** [comment]
> It’s completely unnecessary and counterproductive to use MacPorts as a package manager for a package manager.

I agree completely. However the fact is that your update to ghc broke a whole bunch of stuff, and

1. it seems like nothing is being done about that, and
2. your suggested solutions (stack, cabal) are not available, and
3. even when they become available (when?), everything will still be broken until each port is fixed

At the very least there could have been an effort to keep existing ports working: make the old ghc portfile available as e.g. "ghc7" and set the haskell portgroup to use that.

I may give up on this PR and look into that (a ghc7 port) instead.

**Comment by essandess** [comment]
> update to ghc broke a whole bunch of stuff … it seems like nothing is being done about that … suggested solutions (stack, cabal) are not available … even when they become available (when?), everything will still be broken until each port is fixed … I may give up on this PR and look into that (a ghc7 port) instead.

Comments:
* The reason the MacPorts Haskell stack is years out of date is because Haskell builds are very fragile and dependent upon specific compiler and module versions (that’s why `cabal` and `stack` were developed). It’s easy to find examples of MacPorts people trying and giving up trying to update `ghc` along with all those `hs-*` ports. 
* Even if you get a `ghc7` working, it will almost certainly break on the next update of an `hs-*` dependency, and no one will bother or be able to update anything in Haskell ports because it’s too fragile and difficult. If you have the cycles for this you’re welcome to try, but this model has already been shown not to work over time, but in Haskell world and in MacPorts. If you need `ghc7`, it’s much, much more robust and sane to tell `stack` to use it with the appropriate `lts-*` resolver.
* Anything that breaks because its compiler was updated is itself broken—not the compiler.
* The solution to all this is simple: use `cabal` and `stack`. These PRs exist, work robustly, and are ready to merge. You can use the Portfiles yourself locally if you need them.
* I don’t know what the hold up is. I can only suggest opening an issue or requesting that the MacPorts team drive a decision so that they can be used to fix and build other Haskell-dependent ports.

**Comment by essandess** [comment]
@pmetzger @neverpanic @mf2k @mojca @cjones051073 

Would one of you please drive a decision getting `stack` PR https://github.com/macports/macports-ports/pull/4633 and `cabal` PR

**Comment by amake** [comment]
> Even if you get a ghc7 working,

I'm talking about restoring the version of the portfile previous to your update. It *was* working. And I'm not talking about maintaining it: I would mark it obsolete and it would only exist to fix the current breakage while application ports (as opposed to `hs-*` library ports) move to stack or whatever.

>  If you need ghc7, it’s much, much more robust and sane to tell stack

It's not a matter of what's better; it's a matter of keeping the existing MacPorts Haskell world working while we transition to the new way of doing things.

> Anything that breaks because its compiler was updated is itself broken—not the compiler.

You might think so, but because the compiled files are stored in a versioned directory (`ghc-x.y.z`), until someone revbumps every affected port *literally everything is broken`. All binary builds of everything Haskell currently installs into `${prefix}/lib/ghc-7.8.3` while the new ghc only looks at `${prefix}/lib/ghc-8.6.5`.

> The solution to all this is simple: use cabal and stack. These PRs exist, work robustly, and are ready to merge. You can use the Portfiles yourself locally if you need them.

This is not acceptable when things that *were* working just days ago now *don't*. Even if "use this unmerged portfile" was reasonable (it's not), end users have no way of even knowing about these things without crawling through PRs on GitHub.

If it seems like I'm annoyed by all this, then yes, I am: comments in the ghc port made it clear that updating ghc had huge implications for the entire MacPorts Haskell world, yet they were entirely ignored and now there's a ton of breakage. But I should also say that something absolutely needed to be done about the status quo by someone knowledgeable, so thank you @essandess for bringing your expertise to bear and for all your hard work in this area.

**Comment by essandess** [comment]
@amake 
> It's not a matter of what's better; it's a matter of keeping the existing MacPorts Haskell world working while we transition to the new way of doing things.

I honestly don't believe that's possible given both the fragility of Haskell world tools and the half-decade+ age of the existing MacPorts versions. The entire MacPorts Haskell world is a house of cards—that's why no one touched it for so long.

I get the frustration, but really a six-year-old version of a package under active development can't considered to be "working" anymore. The most efficient path forward is to use modern Haskell development tools to fix what needs fixing, and if those aren't available or working yet, please open a ticket at https://trac.macports.org.

**Comment by essandess** [comment]
@amake The port `stack is now merged and two Portfiles I wrote to use it both work out-of-the-box.

Assuming that the package you’re trying to fix provides a `stack.yaml` I suggest using these Portfiles as a template to fix whatever Haskell package is breaking for you.

After we build up some experience with `stack` on MacPorts, we can figure out how to write a portgroup stack that simplifies this process.

**Comment by amake** [comment]
> I honestly don't believe that's possible

> a six-year-old version of a package under active development can't considered to be "working" anymore

There seems to be a fundamental disconnect here.

Everything *was* working before the ghc update. Note that "working" doesn't mean "a healthy and maintainable ecosystem"; it means the existing ports, such as they are, built and ran. After the ghc update, that was no longer true. The fact that this was not even on anyone's radar is baffling to me.

**Comment by neverpanic** [comment]
As a way forward now that stack is merged, I'd propose to drop all `hs-*` ports, remove `haskell-platform` and re-package the 3 or 4 haskell tools (shellcheck, darcs, pandoc) as stack ports.

I wouldn't even mark the deleted ports as obsolete, since we don't really have a replacement for them.

**Comment by mojca** [comment]
It would definitely be the fastest to package the few missing tools as stack ports for now as is done in #4698, to spare users the troubles of having to live with broken tools.

In general such a breakage should not happen to our users, but after @neverpanic could no longer manage to properly maintain hundreds of packages, there was nobody else stepping in for years, and the pull requests for merging the Haskell tools was open for a relatively long time, not really getting much attention either (@pmetzger doesn't count :).

I'm not really opposing the idea of fixing these packages, in particular not if anyone is willing to maintain them. If @Korusuke's method of updating haskell modules via `upt` works already, this might even be feasible again. Even if these patches just spare problems to some users in the short term and the ports would be deleted later, they might be still worth applying.

(One thing that's nicely demonstrated here is the argument that lots of developers seem to be advocating with removing Perl version from Perl modules. If we did that, it would get super interesting when we would be updating Perl, similar to what happens here when Haskell gets updated.)

Note: I didn't test anything.

**Comment by amake** [comment]
I agree that removing these ports and moving the Haskell-based applications to `stack` is the best solution.

For posterity, I investigated these options:

1. Do the usual update of haskell-platform and revbump hs-* ports: This is just too much work.
2. Just revbump hs-* ports to use the new ghc: This doesn't work because ghc 8 bundles different packages from ghc 7, and you end up needing to update haskell-platform anyway.
3. Restore the previous ghc as a new `ghc7` port, move existing hs-* ports to use this. This can work, but `ghc7` must conflict with `ghc`, so anyone who had `ghc` installed and updated to the latest version will need to manually deactivate/uninstall, and it's all just ugly.

**Comment by neverpanic** [comment]
shellcheck and pandoc use stack now. What else should we update before just dropping the rest of the haskell stack?

**Comment by neverpanic** [comment]
@essandess While trying to write a Portfile for `git-annex` with stack, I noticed that it fails to build on 10.12 because the downloaded copy of GHC assumes the `utimensat(2)` system call is available and the `unix` library shipped with this copy of GHC links against it. This causes the build to fail with a linker error, because 10.12 does not have this system call.

How do you propose we solve this? It seems the prebuilt copies of GHC downloaded by stack are not specific to the macOS version.

**Comment by cjones051073** [comment]
> `utimensat`

@kencu There have been discussions about whether or not adding these methods to the legacy support package would make sense or not. The question is does it make sense to add something to this library, to emulate those methods, on systems which can never support ns precision. I am not sure, but perhaps it is as if you look into those methods they do not guarantee to use the full ns precision, only 'if the underlying filesystme supports it'.

http://man7.org/linux/man-pages/man2/utimensat.2.html

So that might be one solution, for someone to implement a fallback method there, and then to use the legacy support PortGroup.

**Comment by neverpanic** [comment]
Just to re-iterate what Josh already said in https://trac.macports.org/ticket/57821#comment:17 in the ticket. Even if `/usr/lib/libiconv.dylib` and `/opt/local/lib/libiconv.dylib` did provide the same symbol names (which they don't), you could still not assume that they are binary compatible. For example, the developers of iconv could have changed the value of a constant in one of their header files that would make your program behave differently when compiled with headers from one version but linked against the library from a different version.

The symbol renaming done by the iconv developers is really just an exercise in catching you early before you otherwise shoot your foot and get a weird crash. There is no alternative option other than to use the specific copy of libiconv the developers of GHC used to build the binary copy of libHSbase.a (and considering that it seems that this library may have been built on a newer version of macOS than our users may attempt to use it, hope that the versions shipped by Apple are sufficiently compatible to not cause crashes; c.f. https://github.com/macports/macports-ports/pull/5145, which requires compiling with `--system-ghc` because the downloaded copy assumes availability of `utimensat`).

As was correctly point out in this discussion, this will likely cause problems as soon as one of the tools we're trying to build from the Haskell world needs a macports-installed library from `/opt/local/lib` unless we jump through hoops to avoid this problem. Enabling trace mode can fix this because it would hide `libiconv`, but only iff the library required by this theoretical haskell port would not itself depend on macports' `libiconv` (note that loading two versions of libiconv would *not* be a problem on macOS due to how Mach-O's two-level namespacing works).

The simplest way to fix this is to somehow bring GHC/stack/cabal to link against `/usr/lib/libiconv.dylib` using its full path whenever it links `libHSbase.a`, and that is the solution we should be investigating.

**Comment by essandess** [comment]
@mouse07410 
> I found it better not to rely on the Macports Haskell port, but install it via `ghcup`, and let Haskell tools (`cabal` or `stack`) install `pandoc`, `shellcheck`, etc.

Thanks for your comments. We’re trying to address this one by using Haskell tools to build MacPorts ports. Personally, relying on a bunch of separate by-hand installs pretty much guarantees that they’ll **all** be out of date for me, so I like getting it done on MacPorts if possible.

**Comment by kencu** [comment]
We had a big discussion about this issue a few months ago, and basically concluded it was not possible to keep up with the haskell world manually. 

Updating haskell to > 8 was put off for several years because of the wreckage that we all knew would ensue from doing that. 

We really only use haskell in MacPorts for building a few other ports that we really want (one of the games I was maintaining used it to build, for example).

The current version runs on very few systems, and all the ports that we wanted to use haskell for have been pretty much wrecked now -- no idea what we'll do about that. Having ghc7 around for the use we have it for makes sense to me, but again, PITA.

anyone actually interested in haskell might better do it outside macports, if you ask me, unless some magic cabal to Portfile translator shows up that could fill in the missing work. 

Re: Chris's question --- we discussed something similar with Rene (RJVB) a couple of months ago. I personally would think adding a "best approximation" function to legacy support for functions that don't exist on older systems is better than letting them just fail (and I have done such fixes already in legacysupport), so I'd vote to do it, but I get your point that if the OS doesn't support the functionality, then we shouldn't pretend it does. Both approaches are valid. I would vote to put it in, but I certainly wouldn't argue about it.

My $0.02 (only because I was asked).

**Comment by mojca** [comment]
> anyone actually interested in haskell might better do it outside macports, if you ask me, unless some magic cabal to Portfile translator shows up that could fill in the missing work.

I sadly didn't manage to test it yet (despite me being the one who requested it: shame on me), but I wanted to mention that @Korusuke actually wrote one (for `hackage`; I didn't yet clarify the confusion between the zillion different tools from the Haskell world in my head).

* https://framagit.org/upt/upt-hackage
* https://github.com/macports/upt-macports/pull/39

Regarding compatibility with the old OS versions: `stack` also seems to be broken on < 10.9 due to certificate issues: https://ports.macports.org/port/stack (a known problem for which we created workarounds for the rest of MacPorts which don't apply here).

**Comment by markemer** [comment]
I have tilted at this particular windmill for a while. I'm glad to see someone else jump in. Let me know if you need any help.

**Comment by amake** [comment]
@neverpanic 
> shellcheck and pandoc use stack now. What else should we update before just dropping the rest of the haskell stack?

My interest was in shellcheck and erd, which was not buildable with the old Haskell world but I was able to get working quite easily with the new `haskell_stack` portgroup, so I'm quite happy about that.

Other "application" ports that depend on Haskell libraries, as far as I can tell:

- darcs
- gf
- lhs2tex
- pxsl-tools

So once these can be moved to `haskell_stack`, we can remove all `hs-*` ports and `haskell-platform`? And by remove, I mean we delete the ports entirely?

**Comment by essandess** [comment]
@neverpanic If it’s not too painful, I also think we need a binary checker that greps for appearance of the deleted, temporary `.stack` root directory., then errors out to prompts the Portfile author to jump through the `cabal` configuration hoops to add `--datadir` or whatever is necessary.

For most the Haskell packages this is unnecessary, but if the Haskell code has side effect file outputs, the compiler will stick them in `--datadir`, `--libdir` and the like. Personally, I’m not familiar with the details, but I observe the behavior in certain cases (`ihaskell` PR https://github.com/macports/macports-ports/pull/4706, `adblock2privoxy` PR https://github.com/macports/macports-ports/pull/5180).

This is further complicated by the lack of `DESTDIR` and `PREFIX` across Haskell world. See https://github.com/commercialhaskell/stack/issues/848 and https://github.com/commercialhaskell/stack/issues/4857.

This bit me recently and my recommended fix is in PR https://github.com/macports/macports-ports/pull/5180.

Aside from just calling `fgrep "[option haskell_stack.stack.root]"`, is there an better way to detect lack of destroot in the binary? What happens if it’s detected? Throw a `ui_error` and exit?

**Comment by essandess** [comment]
@neverpanic @cjones051073 @amake @mojca @nerdling 

Also, this being Haskell, I think that it’s a moral imperative that we use portgroup `haskell_stack` within port `stack` so that `stack` builds itself.

What happens if `stack` declares itself as a build dependency? A MacPorts error I presume? What’s the conditional to detect this?

I suggest refactoring the Portfile so that the initial `stack` binary is downloaded (and perhaps installed within a `subport`), then let `haskell_stack` defaults take over and finish the job.

If anyone knows how to do these steps, please jump in with a commit or post the code.

**Comment by amake** [comment]
I found that several ports required running `stack init` before `stack build`. I'm not sure if that's the right thing to do, but it worked. Any thoughts, @essandess?

**Comment by essandess** [comment]
@amake 
> I found that several ports required running `stack init` before `stack build`. I'm not sure if that's the right thing to do, but it worked. Any thoughts, @essandess?
```
stack --help
```

Those are projects without a `stack.yaml` for which the author hasn’t explicitly specified `stack` As the development environment. Stack is robust enough that it can create one on-the-fly with `stack init`. If it works, great. But I would think you want the `stack init` command in `pre-configure` (== `stack setup` ), not `pre-build` (== `stack build` ). I’d try that first.

**Comment by amake** [comment]
As I mentioned, it did work at `pre-build` (`stack configure` did not fail for any of the ports, only `stack build` failed).

This sounds like something we should be handling in the portgroup: detect the absence of a stack config and run `stack init` if appropriate. I noted that e.g. [gf-core](https://github.com/GrammaticalFramework/gf-core) has multiple `stack*.yaml` files; does stack intelligently use the appropriate one? Would it be sufficient to merely check for any `stack*.yaml` file?

**Comment by neverpanic** [comment]
> @neverpanic @cjones051073 @amake @mojca @nerdling
> 
> Also, this being Haskell, I think that it’s a moral imperative that we use portgroup `haskell_stack` within port `stack` so that `stack` builds itself.
> 
> What happens if `stack` declares itself as a build dependency? A MacPorts error I presume? What’s the conditional to detect this?

It'll fail. We have cases where PortGroups wrap code in `if {${name} ne "bootstrapping-port"} {...}` to prevent this, to I'd suggest the same solution.

**Comment by kencu** [comment]
In the hedgewars port, haskell is used to build only the server component. So I think just that part can be disabled until such time as I see if it works with the new stack-based layout.

**Comment by essandess** [comment]
@neverpanic 
> > What happens if `stack` declares itself as a build dependency? A MacPorts error I presume? What’s the conditional to detect this?
> 
> It'll fail. We have cases where PortGroups wrap code in `if {${name} ne "bootstrapping-port"} {...}` to prevent this, to I'd suggest the same solution.

I'm simply trying this in a modified Portfile:
```
depends_build-delete \
                port:stack
```

But `port -s install stack` still trys to install `stack` first and I'm still seeing this:
```
port deps stack
Full Name: stack @2.1.3_1
Build Dependencies:   stack
```

Shouldn't that simply work without modding the portgroup? Any idea why I can't edit out the dependency?

**Comment by neverpanic** [comment]
> No problem, I thought, I'll simply delete it in the refactored Portfile like this:
> 
> ```
> depends_build-delete \
>                 port:stack
> ```

By the time you delete the stack dependency, it isn't in the list yet. This is due to the PortGroup's use of `port::register_callback`, which allows PortGroups to register a callback that gets executed when the rest of the Portfile was run. In the case of this PortGroup, the registered callback adds the dependencies. The rationale for using this method is that you can't accidentally forget to add the stack dependency, e.g. by using `depends_build port:somethingelse` in the Portfile, and that you only get the GHC dependency when `haskell_stack.system_ghc` is yes (and you don't need complicated logic to add it to `depends_build` when `haskell_stack.system_ghc` is set to yes and remove it again when it gets set to no).

> Shouldn't that simply work without modding the portgroup? Any idea why I can't edit out a build dependency?

In this case (and others where we have done the same thing), just add an if in the PortGroup so that it doesn't add the dependency if `$subport eq "stack"`, because it just doesn't make sense to add a self-dependency.

**Comment by cjones051073** [comment]
> > No problem, I thought, I'll simply delete it in the refactored Portfile like this:
> > ```
> > depends_build-delete \
> >                 port:stack
> > ```
> 
> By the time you delete the stack dependency, it isn't in the list yet. This is due to the PortGroup's use of `port::register_callback`, which allows PortGroups to register a callback that gets executed when the rest of the Portfile was run. In the case of this PortGroup, the registered callback adds the dependencies. The rationale for using this method is that you can't accidentally forget to add the stack dependency, e.g. by using `depends_build port:somethingelse` in the Portfile, and that you only get the GHC dependency when `haskell_stack.system_ghc` is yes (and you don't need complicated logic to add it to `depends_build` when `haskell_stack.system_ghc` is set to yes and remove it again when it gets set to no).

Generally speaking, its always better to use `depends_build-append` etc. In portfiles, to avoid this sort if problem, implicitly removing dependencies added by portgroups.

> 
> > Shouldn't that simply work without modding the portgroup? Any idea why I can't edit out a build dependency?
> 
> In this case (and others where we have done the same thing), just add an if in the PortGroup so that it doesn't add the dependency if `$subport eq "stack"`, because it just doesn't make sense to add a self-dependency.

**Comment by cjones051073** [comment]
@amake can you please address the conflicts?

**Comment by essandess** [comment]
> the PortGroup's use of `port::register_callback`, which allows PortGroups to register a callback that gets executed when the rest of the Portfile was run.

Oh I see now. I was scratching my head about your suggestion above to use `${name}` because I though that wouldn't be defined yet.

I have a refactor ready to go, but I don't know how to do a local test with a modified portgroup, so I'll just kick it into an azure build and see what happens.

**Comment by cjones051073** [comment]
> > the PortGroup's use of `port::register_callback`, which allows PortGroups to register a callback that gets executed when the rest of the Portfile was run.
> 
> Oh I see now. I was scratching my head about your suggestion above to use `${name}` because I though that wouldn't be defined yet.
> 
> I have a refactor ready to go, but I don't know how to do a local test with a modified portgroup, so I'll just kick it into an azure build and see what happens.

That is easy. Just configure macports to use your ports checkout as its primary source. Then whatever you change in that check is what is used.

**Comment by essandess** [comment]
> That is easy. Just configure macports to use your ports checkout as its primary source. Then whatever you change in that checkout is what is used.

🤷🏼‍♂️🤷🏼‍♂️🤷🏼‍♂️🧐

Easier:
```
sudo vi /opt/local/var/macports/sources/rsync.macports.org/macports/release/tarballs/ports/_resources/port1.0/group/haskell_stack-1.0.tcl
```

**Comment by cjones051073** [comment]
> > That is easy. Just configure macports to use your ports checkout as its primary source. Then whatever you change in that checkout is what is used.
> 
> 🤷🏼‍♂️🤷🏼‍♂️🤷🏼‍♂️🧐
> 
> Easier:
> 
> ```
> sudo vi /opt/local/var/macports/sources/rsync.macports.org/macports/release/tarballs/ports/_resources/port1.0/group/haskell_stack-1.0.tcl
> ```

Thats far from idea as run port sync will just over write whatever you do there. Also using sudo just to edit is unpleasant.

Just follow

https://trac.macports.org/wiki/howto/SyncingWithGit

**Comment by essandess** [comment]
> > > That is easy. Just configure macports to use your ports checkout as its primary source. Then whatever you change in that checkout is what is used.
> > 
> > 
> > 🤷🏼‍♂️🤷🏼‍♂️🤷🏼‍♂️🧐
> > Easier:
> > ```
> > sudo vi /opt/local/var/macports/sources/rsync.macports.org/macports/release/tarballs/ports/_resources/port1.0/group/haskell_stack-1.0.tcl
> > ```
> 
> Thats far from idea as run port sync will just over write whatever you do there. Also using sudo just to edit is unpleasant.

I just need a 3 second debug before throwing this over the wall to azure.

How do I write the portgroup to detect that I'm calling it from the port `stack`? This code throws an error:
```
proc haskell_stack.add_dependencies {} {
    if {${name} ne "stack"} { 
        depends_build-append port:stack
    } 
    if {[option haskell_stack.system_ghc]} {
        depends_build-append port:ghc
    }
}
```

Badness on a local Portfile of `stack`:
```
$ sudo port clean --all stack
Error: Unable to open port: can't read "name": no such variable
```

**Comment by cjones051073** [comment]
> > > > That is easy. Just configure macports to use your ports checkout as its primary source. Then whatever you change in that checkout is what is used.
> > > 
> > > 
> > > 🤷🏼‍♂️🤷🏼‍♂️🤷🏼‍♂️🧐
> > > Easier:
> > > ```
> > > sudo vi /opt/local/var/macports/sources/rsync.macports.org/macports/release/tarballs/ports/_resources/port1.0/group/haskell_stack-1.0.tcl
> > > ```
> > 
> > 
> > Thats far from idea as run port sync will just over write whatever you do there. Also using sudo just to edit is unpleasant.
> 
> I just need a 3 second debug before throwing this over the wall to azure.
> 
> How do I write the portgroup to detect that I'm calling it from the port `stack`? This code throws an error:
> 
> ```
> proc haskell_stack.add_dependencies {} {
>     if {${name} ne "stack"} { 
>         depends_build-append port:stack
>     } 
>     if {[option haskell_stack.system_ghc]} {
>         depends_build-append port:ghc
>     }
> }
> ```
> 
> Badness on a local Portfile of `stack`:
> 
> ```
> $ sudo port clean --all stack
> Error: Unable to open port: can't read "name": no such variable
> ```

You need to define the fact you are using a global variable. Add

`global name`

In the callback before using it.

**Comment by essandess** [comment]
> You need to define the fact you are using a global variable. Add
> 
> `global name`
> 
> In the callback before using it.

Thanks, using `{${name}}` appears to be working too, which looks like it prevents variable expansion until the `register_callback` when `name` is actually defined. Isn't that what I want?

Otherwise, `name` wouldn't be set to `stack` yet, right?

**Comment by essandess** [comment]
This code:
```
proc haskell_stack.add_dependencies {} {
    if { {${name}} ne "stack" } {
        depends_build-append port:stack
    }
…
```

**Comment by cjones051073** [comment]
> > You need to define the fact you are using a global variable. Add
> > `global name`
> > In the callback before using it.
> 
> Thanks, using `{${name}}` appears to be working too, which looks like it prevents variable expansion until the `register_callback` when `name` is actually defined. Isn't that what I want?
> 
> Otherwise, `name` wouldn't be set to `stack` yet, right?

I don’t know enough tcl to comment. All i can say is if you check other PGs doing similar things, they use the global declarations for used variables. So if that works i would do the same.

If you want more clarification,  best asking on the devel list for someone with more tcl experience to comment.

**Comment by essandess** [comment]
@cjones051073 @neverpanic 

Separate MacPorts question for the `stack` self-referencing Portfile.

I need to make sure that `${worksrcpath}` points to the downloaded source code, and that I can just grab the prebuilt binary from some other directory. This code isn't working to mirror the files I need.

How do I tell MacPorts grab this distill from this location, and this other distfile from this other location?

Not-working Portfile code:
```
master_sites        \
                    ${github.homepage}/archive \
                    ${github.homepage}/releases/download/v${github.version}

distname            ${name}-${github.version}-osx-x86_64

distfiles           \
                    v${github.version}${extract.suffix} \
                    ${distname}${extract.suffix}
```

**Comment by essandess** [comment]
> if you check other PGs doing similar things, they use the global declarations for used variables. So if that works i would do the same.

As usual @cjones051073 is right. See PR https://github.com/macports/macports-ports/pull/5275.

**Comment by essandess** [comment]
> > So once these can be moved to `haskell_stack`, we can remove all `hs-*` ports and `haskell-platform`? And by remove, I mean we delete the ports entirely?
> 
> 
> With those ports merged now and #5264 around the corner, should we now continue to remove the rest of the ports? I'm not sure going through the obsoleting process makes sense for those, since we don't have a replacement, so I'd in fact just outright delete them.

I've been copy-and-pasting descriptions and the like from the existing `hs-*` ports. I think it's too early to delete these because they'll still be useful as references as we modernize the Haskell stack.

See what was necessary to pull in pieces of the missing Haskell Platform (`alex`, `happy`, `HsColour`) in PR https://github.com/macports/macports-ports/pull/5272 for `ghc`.

Ultimately, all the things in Haskell Platform should probably be organized as supports in a `Haskell_platform` port that consistent with its namesake, but with modernized/robust build recipes.

**Comment by neverpanic** [comment]
> I've been copy-and-pasting descriptions and the like from the existing `hs-*` ports. I think it's too early to delete these because they'll still be useful as references as we modernize the Haskell stack.

The descriptions are verbatim copies from hackage.haskell.org. Also, deleting these ports doesn't mean they will be gone from the git history.

**Comment by essandess** [comment]
> deleting these ports doesn't mean they will be gone from the git history.

Sounds good.

**Comment by amake** [comment]
> @amake can you please address the conflicts?

I'm going to discard the PR in its current state and instead remove all `hs-*` ports once I've dealt with DoCon, HaXml, distract and hedgewars.

I investigated DoCon, and even the newest version (2.12 from 2014) is simply too old to be built with stack, cabal, or current ghc. So I think we may just have to abandon that one. Now to look at the others...

**Comment by amake** [comment]
I've updated HaXml.

- distract is too old (I tried both cabal and stack)
- hedgewars is too complicated: even without building the server component, we are using Haskell instead of fpc for some core Pascal components, and I just couldn't get it to work. Maybe we could switch to fpc but it claims to need a prerelease version, which would mean adding an fpc-devel subport and I haven't looked into that.

Then there are some more ports I noticed are likely affected:

- thrift (+haskell variant)
- buddha
- pure-gen

My appetite for this is waning rapidly.

**Comment by kencu** [comment]
I can look into fixing hedgewars if it's fixable; I have the fpc version of hedgewars here in a repo. Please leave it with me.

**Comment by kencu** [comment]
I'm looking to kill off ancient PRs that aren't going anywhere -- is this one?

**Comment by amake** [comment]
Yeah I'm not working on it anymore. I'll close it.

**Comment by essandess** [comment]
Note that there remains of ton of dead or obsolete Haskell ports: `ghc-bootstrap`, `haskell-platform`, `hs-*`, groups `haskell-1.0` and `haskell-2.0`, and more.

https://github.com/macports/macports-ports/search?p=1&q=haskell&unscoped_q=haskell

**Comment by neverpanic** [comment]
We should probably just delete those, unless somebody objects?

**Comment by nickgaya** [comment]
Any progress on cleaning up obsolete ports?  See comments on https://trac.macports.org/ticket/61263

**Pull request closed without merging**
