### PR TITLE
libaacs: update to 0.9.0

### PR DESCRIPTION
**Pull request by i0ntempest**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
The port doesn't list the maintainer's GitHub handle so they weren't notified. I notified them by email now. Let's give them another three days from now to reply before merging.

**Comment by ryandesign** [comment]
Stuart indicated approval by email.

**Comment by i0ntempest** [comment]
I'll to do an upgrade to 0.10.x when the segfault problem is fixed, do you have the maintainer's GitHub username so I could put it in?

**Comment by ryandesign** [comment]
He didn't mention his GitHub handle but said it would be fine if someone else wanted to take over this port. Do you want to? If not, I'll get his GitHub handle and add it.

Also note that the livecheck doesn't seem to be accurate: it doesn't find the (faulty) 0.10 release. That is to say, the project's homepage is inaccurate because it doesn't mention the 0.10 release.

Do we have an upstream bug report URL for the 0.10 problem that we could put into a comment in the port?

**Comment by i0ntempest** [comment]
Yea I opened a ticket for the problem. I'll attach it and change maintainer to myself as well.

**Comment by ryandesign** [comment]
Would you like Stuart's other port libbdplus as well? If not, I'll set it to nomaintainer.

**Comment by i0ntempest** [comment]
I guess yes, I don't actively use that port but I can do the updates.

**Pull request merged**
