### PR TITLE
jenkins-cli: new port

### PR DESCRIPTION
**Pull request by harens**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.6 19G73
xcode-select version 2373

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

###### Notes

Closes https://github.com/jenkins-zh/jenkins-cli/issues/402

### CODE REVIEW

**Comment by herbygillot** [comment]
Thanks for this submission @harens; my only comment is that `supported_archs     noarch` is inaccurate because this is a Golang program, which is compiled for specific architectures.  `noarch` suggests that this is like an interpreted program, like something written in Python or Javascript, that doesn't care about processor architecture.

You are using the `golang` portgroup, which not only takes care of specifying `supported_archs` for you, but building the Go executable in the right way for each architecture.

So that line should be removed.

**Comment by harens** [comment]
Thanks again for your detailed help @herbygillot. I've removed the `supported_archs noarch` line

**Comment by herbygillot** [comment]
Thanks @harens. Merging.

**Comment by ryandesign** [comment]
@herbygillot Remember before merging to verify that the commit message meets our guidelines, and if it doesn't, use the Squash and merge button to reword it. In this case, the intermediate message "noarch removed" should not have been in the final commit message.

**Comment by harens** [comment]
For next time, I will be sure to remove the commit msg. Sorry about this and thanks for reraising the issue @ryandesign.

**Pull request merged**
