### PR TITLE
texlive-bin-extra: exclude dvisvgm

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
See https://github.com/macports/macports-ports/commit/4049a91919e377a7d6872b77a0026d870a7340c5

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.5
Xcode 10.2.1

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by MarcusCalhoun-Lopez** [comment]
dvisvgm was excluded in https://github.com/macports/macports-ports/commit/4049a91919e377a7d6872b77a0026d870a7340c5.
The reasons were given by @mojca in the commit message.
It was partially reinstated in https://github.com/macports/macports-ports/commit/2fb36b2a9df13e9c6f30b9af195cf3ff49c175c1.
However, the texlive-bin port still has [--disable-dvisvgm](https://github.com/macports/macports-ports/blob/868db434b72a8b4b397b32a54aeecbc9b74be8c5/tex/texlive-bin/Portfile#L178), so dvisvgm does not seem to have been completely reinstated.

Based on my somewhat limited understanding of the inner workings of TeX Live, it seems that we should do one of the following:
* exclude dvisvgm from texlive-bin-extra (this PR)
* remove `--disable-dvisvgm` from texlive-bin and mark texlive-bin-extra and dvisvgm as conflicting.

**Comment by mojca** [comment]
> Based on my somewhat limited understanding of the inner workings of TeX Live, it seems that we should do one of the following:
> 
> * exclude dvisvgm from texlive-bin-extra (this PR)
> * remove `--disable-dvisvgm` from texlive-bin and mark texlive-bin-extra and dvisvgm as conflicting.

Or remove the dvisvgm port completely :)

I would be in favour of merging this in precisely the suggested way.

**Comment by michaelld** [comment]
My vote is to replace the `dvisvgm` port by `texlive-bin-extras` by enabling it here and in `texlive-bin`. As far as I can tell, there is just 1 other port that depends on it (`port echo depends:dvisvgm` -> `stog`), and this port already depends on `texlive-bin` ... so, enabling `dvisvgm` in `texlive-bin` and `texlive-bin-extras` seems like a fine way to go. Really not sure why `dvisvgm` was separate in the first place!

**Comment by drkp** [comment]
Replacing the dvisvgm port seems like the right thing to do here, especially if @michaelld agrees. 

Does anyone remember why we have dvisvgm as a separate port in the first place? Looks like it dates back to 2012, so possibly it wasn't in TeX Live at the time?

(I would like to do the same with pgf also, now that it is nomaintainer, but that's a separate issue)

**Comment by michaelld** [comment]
I agree & I also have no idea why it's separate. I'd say for those ports we can aggregate into texlive-bin, we do so!

**Comment by drkp** [comment]
I'm gonna merge this for now to fix the conflict, but let's move it into texlive-bin-extra afterwards.

**Comment by mojca** [comment]
Citing myself from commit 4049a91919e377a7d6872b77a0026d870a7340c5:

The dvisvgm binary is available as a standalone port which depends on ghostscript.

Removing it from the TeX Live package has a number of benefits:
* No need to revbump texlive-bin after each ghoscript update.
* No need for a (missing) conflict between texlive-bin-extra and dvisvgm.
* Users of texlive-bin-extra get a newer version of dvisvgm.

See also: https://github.com/macports/macports-ports/pull/2573

The second point is moot, but it's still true that:
* Every gs update would require a full rebuild of texlive if dvisvgm is installed along (it takes quite some time to build and uses quite some space).
* We can get updates more frequently.
* We cannot run dvisvgm's unit tests from texlive build.
* Dvisvgm is one of the rare programs that constantly keeps adopting new technologies (a few years back it was the first and the only software in texlive which required C++11, so we dropped it from building for some older OSes).
* As a consequence it may require a bit more testing and bug reporting (I was involved in 15 email threads in the last two years, just dealing and discussing some issues with it)
* I wouldn't be willing (and probably able either) to do such testing if I had to build the full texlive each time that something strange needs to be tested. Not that I contributed a lot, but still.
* It's one of the rare programs that's shipped with TeX Live binaries, but doesn't work well out of the box because TeX Live doesn't provide the ghostscript library (doing that would mean opening a can of worms). The binary is still trying to search for ghoscript in the standard places, but `/opt/local` (or some other obscure location picked by macports users) is obviously not one of them. So there might be users who install MacTeX, but want a functional dvisvgm and they can just install that one single port (with a small number of dependencies) as opposed to having to install a huge collection of packages and binaries that just conflict with everything else in MacTeX anyway.

**Comment by michaelld** [comment]
@mojca OK those are strong arguments, IMHO. I'm good with leaving it as a separate port.

**Pull request merged**
