### PR TITLE
paraview: use qt5.depends_component syntax

### PR DESCRIPTION
**Pull request by kencu**
and set the current qt5 min version required
this is 5.6 as of 20190427

### CODE REVIEW

**Comment by reneeotten** [comment]
there is another, few weeks old, PR that proposes changes to this port as well (#4045). Ideally if/when the maintainer responds to this PR, he should also take care of the other as well.

**Comment by rubendibattista** [comment]
Sorry, got a bit overwhelmed by things to do. I'll take care of this soon... I'll track the progress on the previous PR. :)

**Comment by cjones051073** [comment]
@rubendibattista any progress. This pr seems quite straight forward so would be good to merge it..

**Comment by reneeotten** [comment]
> @rubendibattista any progress. This pr seems quite straight forward so would be good to merge it..

my earlier comment was not addressed towards @rubendibattista and I do agree that this PR is independent of the updates in the other PR. It looks like @dstrubbe and @jjstickel are not going to respond to this (or the other thread) so I would vote just to merge this PR now and rebase the other one, which will anyway need more changes.

**Comment by rubendibattista** [comment]
Ok, sounds good to me.

**Comment by jjstickel** [comment]
Hi, sorry, I just don't have time to look at this at the moment. It looks like there has been review, and I trust some of you have tested the builds. So merging is fine with me.

**Comment by cjones051073** [comment]
@kencu this is failing in the buildbots, can you please take a look. e.g.

https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/30175/steps/install-port/logs/stdio

**Comment by kencu** [comment]
It's failing with the error in this ticket <https://trac.macports.org/ticket/57433> which I presume means it needs to be updated to build against certain newer versions of qt5 (and that would be the other PR https://github.com/macports/macports-ports/pull/4045 , which is a separate issue from the minor tweaks here).

**Pull request merged**
