### PR TITLE
fbthrift: update to 2018.05.28.00

### PR DESCRIPTION
**Pull request by mohd-akram**
#### Description

https://trac.macports.org/ticket/56572

###### Tested on
macOS 10.13.4 17E202
Xcode 9.4 9F1027a

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Not sure who would be good at reviewing this, but to the extent that I understand it seems okay?

**Comment by mf2k** [comment]
Please add a link to the Trac ticket to the commit message. 

Why have configure.env-append python statements been removed? Add the reason to the commit message.

**Comment by mohd-akram** [comment]
@mf2k Updated.

**Comment by pmetzger** [comment]
@mf2k You feel okay with this now?

**Comment by mf2k** [comment]
@pmetzger: Yes!

**Comment by pmetzger** [comment]
Merged! Thank you, @mohd-akram!

**Comment by ryandesign** [comment]
> Why have the `configure.env-append` python statements been removed? Add the reason to the commit message.

A satisfactory explanation was not provided. All references to python27 were removed from the Portfile *except* the dependency on it. That can't be correct. Either the port still uses python27 in which case the build system needs to somehow be told where it is, or it doesn't use it anymore in which case the dependency needs to be removed.

**Comment by pmetzger** [comment]
@mohd-akram Can you answer @ryandesign ?

**Comment by mohd-akram** [comment]
`PYTHON_EXTRA_LDFLAGS` is for autoconf, and I can't find a reference to `PY_INSTALL_ARGS` or `PYTHON` so I believe they aren't used, especially since this port hasn't been updated in a while. I'm not yet 100% sure if python (or any of the other dependencies) is needed.

**Pull request merged**
