### PR TITLE
Update to Vc 1.4.1

### PR DESCRIPTION
**Pull request by olupton**
#### Description
Bump Vc to new version https://github.com/VcDevel/Vc/releases

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.12.6 16G1618
Xcode 9.2 9C40b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by RJVB** [comment]
LGTM.

**Comment by RJVB** [comment]
One thing: did you check ABI compatibility (i.e. are there dependents that need to be rev-bumped)?

**Comment by cjones051073** [comment]
As far as I can tell there are no dependent ports.

**Comment by cjones051073** [comment]
thanks @olupton !

**Comment by olupton** [comment]
Thanks @cjones051073 and sorry for the slow reply.
On my system the only port that depends on `Vc` is `root6` (which I have installed with the nonstandard `+vc` variant).

**Pull request merged**
