### PR TITLE
v2ray: update to 4.23.4

### PR DESCRIPTION
**Pull request by i0ntempest**
Update Portfile

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [x] security fix

###### Tested on

macOS 10.x
Xcode 8.x

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by i0ntempest** [comment]
This release patched some serious vulnerabilities in the protocol so please merge asap.

**Comment by casouri** [comment]
I doubt that this will work man. There just aren’t that many committers for macports.

**Comment by i0ntempest** [comment]
¯\_(ツ)_/¯ We'll have to wait. I've applied for committer access but got no response.

**Comment by ryandesign** [comment]
@casouri since you commented here I assume you approve this PR. In the future, when a PR is filed about your port, you should indicate whether or not you approve so that we'll know if we can merge the PR.

**Comment by casouri** [comment]
Got it, thanks.

**Pull request merged**
