### PR TITLE
hugin-app: update to 2021.0.0; fix deprecated finite() problem, and several runtime path problems

### PR DESCRIPTION
**Pull request by bal-agates**
#### Description

With hugin-app 2019.2.0 I ran into several problems.  

- Use of the deprecated finite() caused compile time error.  That fix was straightfoward.  
- Several runtime path issues.  The bundled applications could not locate other utility programs.  Complicated to fix because of multiple methods to get paths to executable.

Before trying to fix the runtime problems I upgraded the latest sources 2021.0.0.  

I tried to keep my fixes as small as possible which made them somewhat uglier than I like.  Someone who understand MacPorts and CMake better could probably figure out better fixes?

Closes [#62445](https://trac.macports.org/ticket/62445).  
Closes [#64601](https://trac.macports.org/ticket/64601).  

"port lint hugin-app" reports (1) error in a reimplace but I do not think this is a real error.  The reference to "/opt/local/bin" in a string and is required for my patch.  Maybe there is a better way?

There still are likely problems with OpenMP but it seems to revert to single thread mode which still had good performance on my computer.  The past OpenMP patch caused errors so I commented out.

Removed <patch-terios.diff>.  I had no issues without this.

Tested major functions in Hugin.app and PTStitcherGUI.app.  This utilizes some subset of utility programs (cpfind, enblend, nona).  I have not tested calibrate_lens_gui.app or HuginStitchProject.app because I do not know how to use them.

Maintainer might consider making this version a hugin-devel port because it is not completely test?  However, if the hugin-app@2019.2.0 doesn't work at all these updates probably better.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 12.2 21D49 arm64
Xcode 13.2.1 13C100

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?  See comment above.
- [ ] tried existing tests with `sudo port test`?  No tests.
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?  No.  See comments above.

### CODE REVIEW

**Comment by mascguy** [comment]
Tested locally on 10.15, and there are link failures related to Boost:

```
Undefined symbols for architecture x86_64:
  "boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, unsigned int, boost::system::error_code*)", referenced from:
      boost::filesystem::directory_iterator::directory_iterator(boost::filesystem::path const&, boost::filesystem::directory_options) in hugin_lensdb.cpp.o
  "boost::filesystem::detail::recursive_directory_iterator_construct(boost::filesystem::recursive_directory_iterator&, boost::filesystem::path const&, unsigned int, boost::system::error_code*)", referenced from:
      boost::filesystem::recursive_directory_iterator::recursive_directory_iterator(boost::filesystem::path const&) in hugin_lensdb.cpp.o
  "boost::filesystem::detail::recursive_directory_iterator_increment(boost::filesystem::recursive_directory_iterator&, boost::system::error_code*)", referenced from:
      bool iterateFileSystem<boost::filesystem::recursive_directory_iterator>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path> >&) in hugin_lensdb.cpp.o
  "boost::filesystem::detail::absolute(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)", referenced from:
      _main in hugin_lensdb.cpp.o
ld: symbol(s) not found for architecture x86_64
make[2]: *** [src/tools/hugin_lensdb] Error 1

Undefined symbols for architecture x86_64:
  "boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, unsigned int, boost::system::error_code*)", referenced from:
      boost::filesystem::directory_iterator::directory_iterator(boost::filesystem::path const&, boost::filesystem::directory_options) in pto_move.cpp.o
  "boost::filesystem::detail::recursive_directory_iterator_construct(boost::filesystem::recursive_directory_iterator&, boost::filesystem::path const&, unsigned int, boost::system::error_code*)", referenced from:
      boost::filesystem::recursive_directory_iterator::recursive_directory_iterator(boost::filesystem::path const&) in pto_move.cpp.o
  "boost::filesystem::detail::recursive_directory_iterator_increment(boost::filesystem::recursive_directory_iterator&, boost::system::error_code*)", referenced from:
      bool iterateFileSystem<boost::filesystem::recursive_directory_iterator>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::set<boost::filesystem::path, std::__1::less<boost::filesystem::path>, std::__1::allocator<boost::filesystem::path> >&) in pto_move.cpp.o
  "boost::filesystem::detail::absolute(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)", referenced from:
      RebaseFilename(boost::filesystem::path, boost::filesystem::path&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in pto_move.cpp.o
      checkDestinationDirectory(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, boost::filesystem::path&) in pto_move.cpp.o
      PTOCopyMove(bool, boost::filesystem::path, boost::filesystem::path, bool) in pto_move.cpp.o
      _main in pto_move.cpp.o
  "boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, unsigned int, boost::system::error_code*)", referenced from:
      PTOCopyMove(bool, boost::filesystem::path, boost::filesystem::path, bool) in pto_move.cpp.o
ld: symbol(s) not found for architecture x86_64
make[2]: *** [src/tools/pto_move] Error 1

Undefined symbols for architecture x86_64:
  "boost::filesystem::detail::absolute(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)", referenced from:
      CreateMissingImages(HuginBase::Panorama&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in checkpto.cpp.o
ld: symbol(s) not found for architecture x86_64
make[2]: *** [src/tools/checkpto] Error 1
```

**Comment by mascguy** [comment]
> Tested locally on 10.15, and there are link failures related to Boost:
> [...]

Using a newer version of Boost solves that problem. The remaining issue is a link error related to use of `_Gestalt`.

Getting warmer!

**Comment by mascguy** [comment]
NOTE: PR https://github.com/macports/macports-ports/pull/15075 will need to be merged first, as `vigra` doesn't currently support Python 3.10.

**Comment by mascguy** [comment]
Rebased against master, fixing merge conflicts.

The only known remaining issue, is the link error for `_Gestalt`. @MarcusCalhoun-Lopez / Anyone, what am I missing...?

**Comment by reneeotten** [comment]
> The only known remaining issue, is the link error for `_Gestalt`. @MarcusCalhoun-Lopez / Anyone, what am I missing...?

@mascguy: it seems to pass in the CI so it should work on the latest three OSes, that's all what's formally needed. Any reason not to merge this?

**Comment by mascguy** [comment]
> > The only known remaining issue, is the link error for `_Gestalt`. @MarcusCalhoun-Lopez / Anyone, what am I missing...?
> 
> @mascguy: it seems to pass in the CI so it should work on the latest three OSes, that's all what's formally needed. Any reason not to merge this?

Wow, I completely forgot about this. And builds fine locally on 10.15 now too, so that's a good sign.

Thanks for the reminder Renee. Let's merge!

**Comment by mascguy** [comment]
And thank you so much for the contribution @bal-agates!

**Comment by bal-agates** [comment]
This was my first pull request for macports-ports.  Can anyone suggest things I should have done differently to make things go smoother?  One mistake I made was forking macports-ports to my GitHub and then working under master.  I should have made a branch on my fork for these changes.  To fix that mistake for future work I plan delete my current fork of macports-ports.  Can anyone confirm we will not loose any useful history when I do that.

**Comment by mascguy** [comment]
> One mistake I made was forking macports-ports to my GitHub and then working under master. I should have made a branch on my fork for these changes.

Yep, that's always preferable.

> To fix that mistake for future work I plan delete my current fork of macports-ports. Can anyone confirm we will not loose any useful history when I do that.

As long as you don't have any local branches that haven't been pushed to GitHub - and/or any uncommitted changes - there shouldn't be an issue.

With that said, it's not necessary to delete your fork. Instead, you can resync with our upstream repo. That can be done on the GitHub site, or the cmd-line. (I typically prefer to use the cmd-line, but that's purely a personal choice.)

First, verify that you have your remotes setup correctly, via `git remote -v`:

```
$ git remote -v
origin	git@github.com:mascguy/macports-ports (fetch)
origin	git@github.com:mascguy/macports-ports (push)
upstream	git@github.com:macports/macports-ports.git (fetch)
upstream	git@github.com:macports/macports-ports.git (push)
```

If you don't have entries for `upstream`, add those via:

```
$ git remote add upstream git@github.com:macports/macports-ports.git
```

Then run `git remote -v` again, to confirm they've been added. (That's not strictly necessary, but it's something I always do to double-check that all is well.)

Once that's been done, ensure your local repo is back to a good known state:

```
$ git reset --hard upstream/master
```

But be careful when using `git reset --hard`, as it effectively wipes any and all local uncommitted (or unpushed) changes! (It should be fine in this case, but otherwise, it's something you shouldn't need to use very often.)

And finally, to pull our latest changes, run:

```
$ git pull upstream master
$ git push --force
```

Let me know if that makes sense, as well as if you encounter any issues!

> This was my first pull request for macports-ports. Can anyone suggest things I should have done differently to make things go smoother?

Given the number of changes necessary for this PR, I think you did a great job overall!

In terms of potential improvements, please see my cleanup commit from earlier today: https://github.com/macports/macports-ports/commit/1921cfe9d77150b79409d72cf8fdac3bd423ac0c

The key thing to avoid, is hard-coding of `/opt/local/bin` anywhere. Instead, use a unique placeholder: We typically use a pattern like `@@my_identifier@@`, to avoid any potential clashes/overlap with unrelated code.

Another thing to do, is always run `port lint --nitpick` to validate that there aren't any portfile issues.

Otherwise, my cleanup was mostly stylistic in nature. But these changes make it easier for others to understand what the port is doing:
* Minimize the number of separate phase blocks, for things like `post-patch`.
* Group patchfiles together in the same area of the portfile, at least for those that are always applied.

But again, given how much work that was necessary for the PR, these are all minor nits. And I'm more than happy to take care of them after-the-fact, given that you did the hard work!

**Comment by mascguy** [comment]
As for your choice to use separate `post-patch` blocks, one for each associated patch: That approach is just as valid - and in some ways, arguably better - than grouping things like I did in my subsequent cleanup commit. Indeed, now that I look at my changes, I'm thinking I should have left those as-is!

So you're certainly welcome to use that convention going forward.

**Pull request merged**
