### PR TITLE
uv: new port (0.1.10)

### PR DESCRIPTION
**Pull request by TheRealKeto**
#### Description

Add `uv`, a fast Python dependency installer and resolver written in Rust.

###### Tested on

macOS 12.6 21G115 arm64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -d destroot`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by herbygillot** [comment]
Would it be better to generate the auto-completions from the command in a `post-destroot` phase? In that way we ensure that the auto-complete logic matches all updates to `uv`.

**Comment by TheRealKeto** [comment]
> Would it be better to generate the auto-completions from the command in a `post-destroot` phase? In that way we ensure that the auto-complete logic matches all updates to `uv`.

@herbygillot I considered this but hadn't found an appropriate way. This has changed - will commit soon.

**Comment by herbygillot** [comment]
Oops I meant `post-build`

**Comment by TheRealKeto** [comment]
> Oops I meant `post-build`

@herbygillot No worries. I checked some examples so adapting shouldn't take much. Will commit the new changes soon.

**Comment by herbygillot** [comment]
This looks good.

**Pull request merged**
