### PR TITLE
snmptt: update to 1.5

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by herbygillot** [comment]
Can we change the URL to HTTPS while we're here?

**Comment by barracuda156** [comment]
> Can we change the homepage URL to HTTPS while we're here?

Yeah, once I’m back to the machine today.

**Comment by barracuda156** [comment]
@herbygillot Looks like they do not provide https version.

**Comment by herbygillot** [comment]
That's odd,  https://www.snmptt.org/ works for me, but OK.

**Comment by barracuda156** [comment]
> That's odd, https://www.snmptt.org/ works for me, but OK.

Address worked for me, but browser shown that it is not a secure connection.

**Pull request merged**
