### PR TITLE
mysql8: rev bump to 8.4.2

### PR DESCRIPTION
**Pull request by jhoyt4**
#### Description

Update mysql 8 to 8.4.2

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.6.1 23G93 arm64
Xcode 15.4 15F31d
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by jhoyt4** [comment]
I was hoping 8.4.2 would help resolve the "Undefined symbols "std::exception_ptr::__from_native_exception_pointer(void*)" I'm now seeing on macOS 13, but alas no.  Back to draft...

**Comment by jhoyt4** [comment]
It appears the issue is related to llvm, other projects are seeing the same thing:
https://reviews.llvm.org/D148266
https://geant4-forum.web.cern.ch/t/clang-error-linker-command-failed-with-exit-code-1-use-v-to-see-invocation/12372

Let's see if forcing the macports clang will resolve this...

**Comment by jhoyt4** [comment]
Changed from clang 14 to 18 (should have started with the latest).  Let's see if that gets macOS 13 working...

**Comment by jhoyt4** [comment]
Well, 18 hung, time to try 15...

**Comment by herbygillot** [comment]
Thank you for running this thorough validation process, @jhoyt4.

**Pull request merged**
