### PR TITLE
gtk3: update to version 3.24.10

### PR DESCRIPTION
**Pull request by jjstickel**
* update to version 3.24.10
* remove a patch that is no longer needed

Closes: https://trac.macports.org/ticket/58730
Closes: https://trac.macports.org/ticket/58130

#### Description

This update is needed to resolve a problem with dependent ports with +quartz variant, specifically gnucash. See the ticket reference above.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.5 18F132
Xcode 10.2.1 10E1001

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by dbevans** [comment]
Thanks for the PR.

Testing to check effect on previously reported problems. In addition, I'd like to finish updating the underlying dependencies before merging this update. Patience is appreciated.

**Comment by cjones051073** [comment]
Any news on this ?

**Comment by pmetzger** [comment]
@dbevans Ping?

**Comment by jjstickel** [comment]
This port does have `openmainter` for policy.

**Comment by pmetzger** [comment]
@jjstickel Even if a port is openmaintainer, if the maintainer responds and says to hold off, we listen to them. In this case, @dbevans responded. However, it would be nice if he gave an indication of his intentions.

**Comment by jjstickel** [comment]
> @jjstickel Even if a port is openmaintainer, if the maintainer responds and says to hold off, we listen to them.
Understood. Although there might not be a formal policy, I wasn't sure if other devs might be able to move on it given openmaintainer and it's been almost a month.

**Comment by kencu** [comment]
gtk3 has moved on to `3.23.12` and this PR is just sitting. 

TBH, @dbevans will update this when he is ready to do so (he updates a dozen ports a day), so IMHO, you might as well close this.

**Comment by pmetzger** [comment]
I'd like us to get _explicit_ instructions from @dbevans on this before closing it.

**Comment by michaelld** [comment]
Do we have another PR to update gtk3 to the latest (right now: 3.24.12) ... or at least something close to it? If not, then merging this one at least gets us a step closer to being there! If so, then let's defer to it instead & close this one.

**Comment by michaelld** [comment]
IMHO: "openmaintainer" is meant just for times like this: when the primary port maintainer(s) isn't commenting on a PR ... for whatever reason: too busy; doesn't care; just because; no reason. We provide opportunities by tagging the maintainer(s), and once the timeout comes and goes, we can choose to merge or not, with the implicit approval of the maintainer(s). Of course it's always kind to give extra time to maintainer(s), especially over weekends -- but not necessary once the timeout comes and goes. If the maintainer(s) with the have formal control (excepting minor and/or emergency changes), then the port should not be "openmaintainer".

**Comment by kencu** [comment]
I don't believe that Dave really feels (or treats) gtk3 as openmaintainer, other than very minor fixes. Do we have any idea what the wreckage will be in the 200+ gtk port dave maintains by updating this? Is anyone going to look at that? There is a reason he hasn't updated it.

**Comment by kencu** [comment]
At least, I think that is why he hasn't moved on this.

**Comment by dbevans** [comment]
> I don't believe that Dave really feels (or treats) gtk3 as openmaintainer, other than very minor fixes. Do we have any idea what the wreckage will be in the 200+ gtk ports dave maintains by updating this? Is anyone going to look at that? There is a reason he hasn't updated it.

Well to be fair this has just dropped off my screen.  My plan for merging this was to get it's dependencies update to date first (my usual plan of attack) and in particular glib2 which is maintained
by @ryandesign but both he and I have been backed up over the transition to meson which has been exacerbated by delays caused by medical issues (CABG x4 for Ken's benefit).  Good news is that over the past 6 months, I've been getting back to normal but with a new appreciation for smelling the roses
which hasn't helped much either.  And let's face it, I'm not as young as I used to be.

In general, I do consider gtk3 to be openmaintainer and, at this point, open to new maintainers or co-maintainers if anyone would like to step up.  Some new blood would be beneficial. This applies to the rest of my GNOME ports as well. Let me know. I really don't want to just get to the point where I just have to drop maintaining them without others to follow on. 'Nuff said.

In the meantime, I don't see any reason why this can't be merged now and I don't expect any significant impact on the other GNOME ports.  If there is, we can deal with it. Again please forgive me for the delay and thanks for the nudge.

**Comment by kencu** [comment]
Glad to see you're up and around! No wonder I couldn't reach you some weeks ago when I passed through Berkeley...

**Pull request merged**
