### PR TITLE
hdf5: update version 1.12.2->1.14.0 & revbump deps

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Review by remkos — APPROVED** [review]
Revbump approved

**Comment by eborisch** [comment]
h5py won’t [build against](https://github.com/h5py/h5py/pull/2194)  1.14.0 just yet. I was planning to hold off a bit for at least that to be merged.

**Comment by Schamschula** [comment]
Both armadillo and mathgl are good to go!

**Comment by MarcusCalhoun-Lopez** [comment]
@eborisch, I included in this pull request the [merged upstream patches](https://github.com/h5py/h5py/pull/2194) to make h5py work with hdf5 1.14.0.
Does this address your concerns?

**Comment by eborisch** [comment]
> @eborisch, I included in this pull request the [merged upstream patches](https://github.com/h5py/h5py/pull/2194) to make h5py work with hdf5 1.14.0.
> Does this address your concerns?

Yes; works for (compiles h5py & functions) for me. Thanks!

py-h5py, HDF5-External-Filter-Plugins, and ismrmrd are good-to-go.

Thanks for doing this.

**Comment by MarcusCalhoun-Lopez** [comment]
May this pull request be merged?
I am happy to wait if more testing is needed.

**Comment by rdbisme** [comment]
I don't have a mac anynmore for the time being, Can someone check if `vtk` compiles? Considering the minor version update, I hope it will.

**Comment by MarcusCalhoun-Lopez** [comment]
vtk seems to compile.

**Pull request merged**
