### PR TITLE
commons-logging: update to 1.2, fix livecheck and whitespace

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Closes https://trac.macports.org/ticket/58675

###### ~~Tested on~~

~~macOS 10.x~~
~~Xcode 8.x~~

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
>Port commons-logging fail on xcode9.4.

```
compile-non-log4j:
    …
    [javac] error: Source option 1.3 is no longer supported. Use 6 or later.
    [javac] error: Target option 1.2 is no longer supported. Use 1.6 or later.
```
JDK 8 is the last version able to build this port; JDK 9 and later will not build it. Is there a way to specify a maximum version?

**Comment by cjones051073** [comment]
> > Port commons-logging **fail** on xcode9.4.
> 
> ```
> compile-non-log4j:
>     …
>     [javac] error: Source option 1.3 is no longer supported. Use 6 or later.
>     [javac] error: Target option 1.2 is no longer supported. Use 1.6 or later.
> ```
> 
> JDK 8 is the last version able to build this port; JDK 9 and later will not build it. Is there a way to specify a maximum should take 

> > Port commons-logging **fail** on xcode9.4.
> 
> ```
> compile-non-log4j:
>     …
>     [javac] error: Source option 1.3 is no longer supported. Use 6 or later.
>     [javac] error: Target option 1.2 is no longer supported. Use 1.6 or later.
> ```
> 
> JDK 8 is the last version able to build this port; JDK 9 and later will not build it. Is there a way to specify a maximum version?

Yes. Take a look at ports using the java port group. E.g. bazel and py-tensorflow. These set a minimum, but the same can be used for a maximum.

**Comment by cjones051073** [comment]
> > > Port commons-logging **fail** on xcode9.4.
> > 
> > 
> > ```
> > compile-non-log4j:
> >     …
> >     [javac] error: Source option 1.3 is no longer supported. Use 6 or later.
> >     [javac] error: Target option 1.2 is no longer supported. Use 1.6 or later.
> > ```
> > 
> > 
> > JDK 8 is the last version able to build this port; JDK 9 and later will not build it. Is there a way to specify a maximum should take
> 
> > > Port commons-logging **fail** on xcode9.4.
> > 
> > 
> > ```
> > compile-non-log4j:
> >     …
> >     [javac] error: Source option 1.3 is no longer supported. Use 6 or later.
> >     [javac] error: Target option 1.2 is no longer supported. Use 1.6 or later.
> > ```
> > 
> > 
> > JDK 8 is the last version able to build this port; JDK 9 and later will not build it. Is there a way to specify a maximum version?
> 
> Yes. Take a look at ports using the java port group. E.g. bazel and py-tensorflow. These set a minimum, but the same can be used for a maximum.

Actually, after taking a look back at bazel it infact does set an explicit version, so you could just do the same, just for the older jdk.

**Comment by chrstphrchvz** [comment]
> > > JDK 8 is the last version able to build this port; JDK 9 and later will not build it. Is there a way to specify a maximum version?
> > 
> > 
> > Yes. Take a look at ports using the java port group. E.g. bazel and py-tensorflow. These set a minimum, but the same can be used for a maximum.
> 
> Actually, after taking a look back at bazel it infact does set an explicit version, so you could just do the same, just for the older jdk.

I wasn't sure if that approach should be used, since it would always require JDK 8, and disallow older yet compatible versions. (At first I thought JDK 8 would only be available on 10.8+ based on the system requirements for Oracle Java 8, but MacPorts appears to have compiled it successfully on 10.6.) It might be the easiest approach for now, though; is that what we should do?

Looking at the Java portgroup, it uses the `/usr/libexec/java_home` command, which only supports specifying a minimum or single exact version, and does not support a maximum version, or reflect whether it supports compiling some earlier version. There might be a way for the Java portgroup to wrap the command to allow ports to specify a maximum version (or a minimum unsupported version), and then by checking `java_home` with the `maximum_version+1` version, if `java_home says that version is supported, then the older fallback/maximum version is needed. However the `java_home` command is not always used to find the java version (e.g. an environment variable might be used instead). And maybe this isn't something the Java portgroup should support; i.e., ports which can't be compiled by newer JDK versions should instead be discontinued (or they should instead use a binary release if available, such as for this port).

There are currently 10 other ports directly or indirectly depending on this port.

**Comment by cjones051073** [comment]
> > > > JDK 8 is the last version able to build this port; JDK 9 and later will not build it. Is there a way to specify a maximum version?
> > > 
> > > 
> > > Yes. Take a look at ports using the java port group. E.g. bazel and py-tensorflow. These set a minimum, but the same can be used for a maximum.
> > 
> > 
> > Actually, after taking a look back at bazel it infact does set an explicit version, so you could just do the same, just for the older jdk.
> 
> I wasn't sure if that approach should be used, since it would always require JDK 8, and disallow older yet compatible versions. (At first I thought JDK 8 would only be available on 10.8+ based on the system requirements for Oracle Java 8, but MacPorts appears to have compiled it successfully on 10.6.) It might be the easiest approach for now, though; is that what we should do?
> 
> Looking at the Java portgroup, it uses the `/usr/libexec/java_home` command, which only supports specifying a minimum or single exact version, and does not support a maximum version, or reflect whether it supports compiling some earlier version. There might be a way for the Java portgroup to wrap the command to allow ports to specify a maximum version (or a minimum unsupported version), and then by checking `java_home` with the `maximum_version+1` version, if `java_home says that version is supported, then the older fallback/maximum version is needed. However the `java_home` command is not always used to find the java version (e.g. an environment variable might be used instead). And maybe this isn't something the Java portgroup should support; i.e., ports which can't be compiled by newer JDK versions should instead be discontinued (or they should instead use a binary release if available, such as for this port).
> 
> There are currently 10 other ports directly or indirectly depending on this port.

Personally , I have no issues with  the port forcing the use of jdk8, even if in theory an older jdk could also work. So I would still use the current java PG as is here.

**Comment by chrstphrchvz** [comment]
I have now forced JDK 8 to be used.

**Comment by cjones051073** [comment]
Thanks.

**Pull request merged**
