### PR TITLE
webkit2-gtk-devel: fix for older systems

### PR DESCRIPTION
**Pull request by kencu**
identical to changes recently made to webkit2-gtk
allows use of MiniBrowser, epiphany web browsers on older systems, and other software that requires webkit2-gtk

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6 / libc++
Xcode 4.2

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
```
$ port -v installed webkit2-gtk-devel
The following ports are currently installed:
  webkit2-gtk-devel @2.15.1_2+gtk2+minibrowser+x11 (active) platform='darwin 10' archs='x86_64' date='2017-08-17T22:32:11-0700'
```

**Comment by kencu** [comment]
screen shot 2017-08-18 at 8 31 06 am

**Comment by kencu** [comment]
screen shot 2017-08-18 at 8 45 13 am

**Comment by kencu** [comment]
travis times out

**Comment by kencu** [comment]
could we assign this PR to @jeremyhu & @dbevans ?

**Comment by kencu** [comment]
@jeremyhu -- what do you think? This minor fix works well, and appears solid on all tested systems so far.

**Comment by kencu** [comment]
10.6.8 running surf 4.7 with webkit2-gtk-devel

screen shot 2017-09-05 at 5 53 40 pm

**Comment by mojca** [comment]
Some builds broke on our buildbot (10.5 due to apparently broken cmake which is a huge problem):
- [10.5/ppc](https://build.macports.org/builders/ports-10.5_ppc_legacy-watcher/builds/8011)
- [10.6/i386](https://build.macports.org/builders/ports-10.6_i386_legacy-watcher/builds/8842)
- [10.6/x86_64](https://build.macports.org/builders/ports-10.6_x86_64_legacy-watcher/builds/8815)

Are you willing to take a look?

Probably the same errors on non-devel version (I didn't check):

- [10.5/ppc](https://build.macports.org/builders/ports-10.5_ppc_legacy-watcher/builds/8010)
- [10.6/i386](https://build.macports.org/builders/ports-10.6_i386_legacy-watcher/builds/8841)
- [10.6/x86_64](https://build.macports.org/builders/ports-10.6_x86_64_legacy-watcher/builds/8814)

**Pull request merged**
