### PR TITLE
port pymol: update to 2.4.0, introduce x11/python38 variants, add string.split patch and use mmtf-cpp

### PR DESCRIPTION
**Pull request by jwhowarth**
port pymol: This commit updates the pymol package to the 2.4.0 release, adds upstream patches for the deprecated string.split python call, introduces an x11 variant and uses the default mmtf-cpp support . The APBS Tools plugin requires pmg_tk (X11) in order to run. The pdb2pqr functionality of APBS Tools also requires python2.7. So the x11 variant defaults to python27 while the -x11 variant defaults to python38. The x11 variant switches the default options.gui to pmg_tk to prevent pymol from favoring the pmg_qt gui. Use msgpack package dependency rather than msgpack2.

###### Type(s)

- [ ] bugfix
- [x ] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.4 19E287
Xcode 11.5 11E608c 

###### Verification 
Have you

- [x ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ x] checked your Portfile with `port lint`?
- [ x] tried existing tests with `sudo port test`?
- [x ] tried a full install with `sudo port -vst install`?
- [x ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jwhowarth** [comment]
What is the issue with the Travis CI builds? I don't see any actual errors listed in those logs. Just timeouts.

**Comment by reneeotten** [comment]
> What is the issue with the Travis CI builds? I don't see any actual errors listed in those logs. Just timeouts.

It's just that the port (and all of it dependencies) cannot be build within the 50 minute time limit that Travis imposes. I think this looks good now and will merge shortly - thanks @jhowarth! There are some simplifications possible, but the functionality is there (I might open up a PR at a later point).

**Comment by jwhowarth** [comment]
On Sun, May 24, 2020 at 9:56 AM Renee Otten <notifications@github.com>
wrote:

> What is the issue with the Travis CI builds? I don't see any actual errors
> listed in those logs. Just timeouts.
>
> It's just that the port (and all of it dependencies) cannot be build
> within the 50 minute time limit that Travis imposes. I think this looks
> good now and will merge shortly - thanks @jhowarth
> <https://github.com/jhowarth>! There are some simplifications possible,
> but the functionality is there (I might open up a PR at a later point).
>

Looking on GitHub at...

 https://github.com/macports/macports-ports/tree/master/science/pymol

...I see a red X next to the commit note 'Latest commitd062ce0
<https://github.com/macports/macports-ports/commit/d062ce04e78ae04cf7780196cfacfd67ae042f83>1
hour ago'

Clicking on that shows the failed builds are 10.6 and 10.9 build bots.
Could this just be the line...

compiler.cxx_standard 2011


...blocking the builds on those old Xcode releases?
          Jack
ps  Does the failed builds inhibit movement of the GitHub files to rsync? I
ask because catch2 seemed to have been committed into GitHub at the same
time as the pymol 2.4.0 update but only the catch2 changes have landed in
rsync.

**Comment by reneeotten** [comment]
If you click a bit further you can see the actual build issues on 10.6 and 10.9. It's related to pyqt5 on 10.6 (`failed to install dependency 'py38-pyqt5'`) and Qt on 10.9 (`failed to install dependency 'qt58-qt3d'`). This has nothing to do with the compiler standard and is probably not something anyone can or will fix.

The `catch2` port was committed 16 hours ago, so that had some more time to get synced. I don't know just try it again in a bit and it should work.

**Pull request merged**
