### PR TITLE
qt5-qtwebkit: Add logic to allow compiling on ARM64 architectures

### PR DESCRIPTION
**Pull request by jhoyt4**
#### Description
Fixes to allow qt5-qtwebkit to successfully compile on ARM64.

Patches required to FastMalloc.cpp to point to the correct PGSIZE variable
Update to Source/WTF/wtf/Platform.h to add ARM64 as an ARCH option [derived from here](https://opensource.apple.com/source/WTF/WTF-7601.1.46.42/wtf/Platform.h.auto.html)
Update to Source/JavaScriptCore/heap/MachineStackMarker.cpp to accept the new ARCH options.

Related to [trac ticket 62027](https://trac.macports.org/ticket/62027)

I have tested what I can, but am still having ARM issues with my test application (mythtv) that prevent a thorough test. Request help from the community to verify.

BTW - I fully expect the buildbots to time out testing this.  QT5 is a behemoth and the last several updates have all timed out.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 11.2.2 20D80
Xcode 12.4 12D4e
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jhoyt4** [comment]
That last force push was a removal of date stamps in the the FastMalloc patch (they sometimes trip up the patch process).

**Comment by jhoyt4** [comment]
@kencu - can I get a review and perhaps some suggestions on how to proceed?

**Comment by kencu** [comment]
looks great. Just have to get someone to build it, and then ideally run something with it, as proof-of-life.

Shouldn't take long -- lots of enthusiasm for this one.

Great job!

**Comment by jhoyt4** [comment]
As expected, the buildbots timed out/failed.  10.15 timed out on qt5-qtspeech.  It looks like 11 failed later at qt5-qtdeclarative-docs. 

Neither of these should be effected by the update to qt5-qtwebkit.

**Comment by jhoyt4** [comment]
I just got my test application compiling.  It looks like qtwebkit is working for me on all of the tests I just ran.

**Comment by pmetzger** [comment]
I suggest someone fix the port lint problems so that it is easier to review the changes...

**Comment by kencu** [comment]
LGTM. What you've patched here would not appear to be able to damage any Intel builds, looks right to fix the arm64 builds to me, and you confirm it works. So -- OK.

Perry, you're right, there's some cleanup to be done on these Portfiles, but not the job of this patch IMHO so I'll let that pass. the qt5 Portfile needs a bit more cleanup, and I haven't event begun to start on qt6 yet :>

**Comment by kencu** [comment]
@jhoyt4 -- don't disappear on me now. 

now is when all the blowback happens, so you need to stick around to weather the storms with me.

**Comment by jhoyt4** [comment]
@kencu, I'll be here to help

**Pull request merged**
