### PR TITLE
py-pytest-mpl: Update to version 0.12.0, Add Python 39, Remove Python 35

### PR DESCRIPTION
**Pull request by essandess**
###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Review by lpsinger — APPROVED** [review]

**Comment by essandess** [comment]
I do not see these CI errors for
```bash
sudo port -vst install py*-pytest-mpl
```

**Comment by lpsinger** [comment]
Odd. I don't either. But the error message is clear enough about what is going wrong:

```
LookupError: setuptools-scm was unable to detect version for '/opt/local/var/macports/build/_Users_runner_work_1_s_ports_python_py-pytest-mpl/py39-pytest-mpl/work/matplotlib-pytest-mpl-5c60ea6'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

Why would this work on our own Macs but not in the CI pipeline?

**Comment by cjones051073** [comment]
lets see what the buildbots make of this.

**Comment by cjones051073** [comment]
Installs fine for me here. My suspicion is there is a required dependency not listed in the port ?

**Comment by essandess** [comment]
> @essandess Builds are failing, please look at e.g.
> 
> https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/137551/steps/install-port/logs/stdio

Looks like it may need `py-setuptools_scm`. Or perhaps wants a git fetch [?]. Please see #10543.

**Comment by essandess** [comment]
> > @essandess Builds are failing, please look at e.g.
> > https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/137551/steps/install-port/logs/stdio
> 
> Looks like it may need `py-setuptools_scm`. Or perhaps wants a git fetch [?]. Please see #10543.

Both of those did the trick. I don't understand why some Python builds require building within a git clone.

**Pull request merged**
