### PR TITLE
ffmpeg/ffmpeg-devel: enable public binary publish

### PR DESCRIPTION
**Pull request by mascguy**
#### Description

Per the following commit discussion, public binaries for these two ports have been blocked since `glib2` was updated to 2.62.6. That's because the latter is now dependent on Python 3.9. However, it's not 100% clear whether that should prevent binary distribution:

https://github.com/macports/macports-ports/commit/c2dfd7f59fd6e10d26e6fdef9245cc44eab56ad0#commitcomment-55609268

This PR serves as a formal opportunity for review and discussion. And if folks agree that MacPorts can distribute binaries for these ports, then the changes will also enable that.

Present state of these ports:
```
macports-infra$ jobs/port_binary_distributable.tcl -v ffmpeg
"ffmpeg" is not distributable because its license "GPL" conflicts with license "OpenSSL": librsvg -> glib2 -> python39 -> openssl -> openssl11
"ffmpeg" is not distributable because its license "GPL" conflicts with license "SSLeay": librsvg -> glib2 -> python39 -> openssl -> openssl11
```

After making the change:
```
macports-infra$ jobs/port_binary_distributable.tcl -v ffmpeg
"ffmpeg" is distributable
```

###### Type(s)
- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.6 17G14019
Xcode 10.1 10B61

###### Verification
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?

### CODE REVIEW

**Comment by mascguy** [comment]
Reviewers: Added the "do not merge yet" label, since we need to validate the legality of publishing these binaries.

**Comment by kencu** [comment]
I don't really know why Josh didn't put "license noconflict" in the python ports years ago -- presumably he felt he could not.

But here is the good news -- all the python ports build trivially easily against openssl3 without any modifications.

So IMHO just do that (figure out how to change the pythons to build against openssl3 in MacPorts, however that is done) and you are done with all the ports that have this problem due to python, forever. (That might be fixing 5,000 ports at once.)

**Comment by mascguy** [comment]
> I don't really know why Josh didn't put "license noconflict" in the python ports years ago -- presumably he felt he could not.
> 
> But here is the good news -- all the python ports build trivially easily against openssl3 without any modifications.
> 
> So IMHO just do that (figure out how to change the pythons to build against openssl3 in MacPorts, however that is done) and you are done with all the ports that have this problem due to python, forever. (That might be fixing 5,000 ports at once.)

Ticket created, covering the switch to OpenSSL 3 for our various Python ports:

**Comment by mascguy** [comment]
Now that our core Python ports use OpenSSL 3, this is no longer an issue! Closing.

**Pull request closed without merging**
