### PR TITLE
harfbuzz{,-devel}, graphics{,-devel}: add legacysupport before 10.7

### PR DESCRIPTION
**Pull request by catap**
#### Description

Depends on https://github.com/macports/macports-legacy-support/pull/51

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.5.8 9L34 i386
Xcode 3.1.4 9M2809

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Changing to draft, since it depends on: https://github.com/macports/macports-legacy-support/pull/51

**Comment by catap** [comment]
@barracuda156 I know you have something not clang friendly and old. May I ask you to check this PR? Is it required or should be closed?

**Comment by barracuda156** [comment]
> @barracuda156 I know you have something not clang friendly and old. May I ask you to check this PR? Is it required or should be closed?

@catap I think that `harfbuzz` builds fine as-is, but let me check today again to be on a safe side.

**Comment by ryandesign** [comment]
To my knowledge harfbuzz builds fine on 10.6 and later. Haven't tested earlier. harfbuzz-devel doesn't which is a matter I've been discussing with upstream and is the reason why the harfbuzz port hasn't been updated to a newer version.

If graphviz/graphviz-devel require legacy support, please restrict it to only the affected subports.

**Comment by barracuda156** [comment]
> To my knowledge harfbuzz builds fine on 10.6 and later. Haven't tested earlier. harfbuzz-devel doesn't which is a matter I've been discussing with upstream and is the reason why the harfbuzz port hasn't been updated to a newer version.
> 
> If graphviz/graphviz-devel require legacy support, please restrict it to only the affected subports.

I have indeed not tried -devel versions of either. I will test those too.

**Comment by barracuda156** [comment]
@catap @ryandesign On 10.6 PPC both `harfbuzz-devel` and `graphviz-devel` build fine with gcc12 with no modifications to portfiles.

**Comment by catap** [comment]
=> let close it as useless

**Comment by barracuda156** [comment]
@catap I will try not to forget to try in on Tiger, a bit later.

**Pull request closed without merging**
