### PR TITLE
gtk-radio: new port

### PR DESCRIPTION
**Pull request by oleaamot**
#### Description

gtk-radio 264.2 for macports 2.9.1

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.3.1 23D60 arm64
Xcode 15.2 15C500b

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [x] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
Looks like this was previously submitted as #22839. In the future, it's best to keep things in one PR than to close and open a new one.

This failed in CI with the error:

```
DEBUG: Executing proc-post-org.macports.destroot-destroot-0
Error: Failed to destroot gtk-radio: app.icon '/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_gnome_gtk-radio/gtk-radio/work/gtk-radio-264.2/data/icons/1024x1024/apps/gtk-radio.png' does not exist
```

**Comment by oleaamot** [comment]
https://ports.macports.org/port/gtk-radio/ is still missing

**Comment by herbygillot** [comment]
> https://ports.macports.org/port/gtk-radio/ is still missing

`gtk-radio` did not get merged yet, hence why. But with the second commit you added, it looks like this PR is building now.

**Comment by herbygillot** [comment]
I've squashed these into a single commit and merged. Thanks for this submission, @oleaamot.

**Pull request merged**
