### PR TITLE
ttfautohint: update to version 1.8.2

### PR DESCRIPTION
**Pull request by lemzwerg**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.7.5 11G63
Xcode 4.6.3 4H1503 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
I'd like the maintainer's opinion on this and I'm not sure they've been contacted given the old style `maintainer` line.

**Comment by lemzwerg** [comment]
??? According to the first comment from macportsbot, it *did* contact the maintainer.

**Comment by tuffnatty** [comment]
Maintainer here. Looks good for me!

**Comment by pmetzger** [comment]
Merged per the maintainer's request.

**Pull request merged**
